MercuryDPM: CombineParallelDataFiles.cpp File Reference
CombineParallelDataFiles.cpp File Reference
#include <iostream>
#include <fstream>
#include <File.h>
#include <Math/Helpers.h>
#include "Logger.h"
#include "vector"
#include "string"
Classes
struct IFile
class DataFiles
Functions
std::string getName (int argc, char *argv[])
int main (int argc, char *argv[])
Function Documentation
getName()
std::string getName (int argc, char * argv[])
extracts the file name from the command line input
{
     logger.assert_always(argc>1,"Please provide name of first data file as input argument");
     return std::string(argv[1]);
 }
References logger, and oomph::Global_string_for_annotation::string().
Referenced by MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::copyInto(), Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::copyInto(), DataFiles::DataFiles(), statistics_while_running< T >::finishStatistics(), BaseCoupling< M, O >::getName(), HeatFluidCoupled< Particle >::getName(), LiquidFilm< Particle >::getName(), Thermal< Particle >::getName(), BaseHandler< T >::getObject(), BaseHandler< T >::getObjectById(), BaseHandler< T >::getObjectsById(), Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::mixAll(), BaseHandler< T >::read(), BaseHandler< T >::removeLastObject(), BaseHandler< T >::removeObject(), FlowRule::run(), statistics_while_running< T >::run(), AngleOfRepose::run(), and MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::write().
main()
int main (int argc , char * argv[])
 {
     DataFiles dataFiles(argc,argv);
     return 0;
 }
References calibrate::dataFiles.