MercuryDPM: unstructured_two_d_curved.cc File Reference
unstructured_two_d_curved.cc File Reference
#include "axisym_poroelasticity.h"
#include "meshes/triangle_mesh.h"
Classes
class AxiPoroProblem< ELEMENT, TIMESTEPPER >
Problem class.
Namespaces
ProblemParameters
Namespace for exact solution and problem parameters.
Functions
void ProblemParameters::update_dependent_parameters ()
Helper function to update dependent parameters.
double ProblemParameters::zero_fct (const double &time, const Vector< double > &x)
double ProblemParameters::boundary_displ_0 (const double &time, const Vector< double > &x)
Imposed boundary displacement in r-direction.
double ProblemParameters::boundary_displ_1 (const double &time, const Vector< double > &x)
Imposed boundary displacement in z-direction.
double ProblemParameters::boundary_veloc_0 (const double &time, const Vector< double > &x)
Imposed boundary velocity in r-direction.
double ProblemParameters::boundary_veloc_1 (const double &time, const Vector< double > &x)
Imposed boundary velocity in z-direction.
double ProblemParameters::boundary_accel_0 (const double &time, const Vector< double > &x)
Imposed boundary accel in r-direction.
double ProblemParameters::boundary_accel_1 (const double &time, const Vector< double > &x)
Imposed boundary accel in z-direction.
double ProblemParameters::boundary_flux_0 (const double &time, const Vector< double > &x)
Imposed boundary flux in r-direction.
double ProblemParameters::boundary_flux_1 (const double &time, const Vector< double > &x)
Imposed boundary flux in z-direction.
double ProblemParameters::boundary_dfluxdt_0 (const double &time, const Vector< double > &x)
Imposed boundary d/dt flux in r-direction.
double ProblemParameters::boundary_dfluxdt_1 (const double &time, const Vector< double > &x)
Imposed boundary d/dt flux in z-direction.
double ProblemParameters::boundary_d2fluxdt2_0 (const double &time, const Vector< double > &x)
Imposed boundary d2/dt2 flux in r-direction.
double ProblemParameters::boundary_d2fluxdt2_1 (const double &time, const Vector< double > &x)
Imposed boundary d2/dt2 flux in z-direction.
void ProblemParameters::exact_soln (const double &time, const Vector< double > &x, Vector< double > &soln)
void ProblemParameters::Solid_body_force (const double &time, const Vector< double > &x, Vector< double > &b)
Solid body force.
void ProblemParameters::Fluid_body_force (const double &time, const Vector< double > &x, Vector< double > &f)
Fluid body force.
void ProblemParameters::Mass_source (const double &time, const Vector< double > &x, double &f)
Source term for continuity.
double ProblemParameters::pressure_magnitude (const double &time)
Get time-dep pressure magnitude.
void ProblemParameters::boundary_pressure (const double &time, const Vector< double > &x, const Vector< double > &n, double &result)
Pressure around the boundary of the domain.
void ProblemParameters::boundary_traction (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction)
Boundary traction.
std::string ProblemParameters::Directory ("RESLT")
template<class ELEMENT >
void ProblemParameters::edge_sign_setup (Mesh *mesh_pt)
int main (int argc, char **argv)
Main function.
Variables
bool ProblemParameters::Steady =false
Steady flag.
double ProblemParameters::Dt =0.01
Timestep.
double ProblemParameters::Lambda_sq =0.7
Timescale ratio (non-dim density)
double ProblemParameters::Permeability =1.0
Permeability.
double ProblemParameters::E_mod =1.0
double ProblemParameters::Nu =0.3
Poisson's ratio.
double ProblemParameters::Alpha =0.5
Alpha, the Biot parameter.
double ProblemParameters::Porosity =0.3
Porosity.
double ProblemParameters::Density_ratio =0.6
Ratio of pore fluid density to solid matrix density.
double ProblemParameters::P =1.0
double ProblemParameters::T_tanh =0.25
Parameter for tanh origin for pressure incrementation.
double ProblemParameters::Alpha_tanh =100.0
Steepness parameter for tanh for pressure incrementation.
double ProblemParameters::Lambda = 0.0
double ProblemParameters::Mu = 0.0
double ProblemParameters::Rho_f_over_rho = 0.0
double ProblemParameters::Domain_radius =1.0
Radius of the smaller arcs in the curved mesh.
double ProblemParameters::Inner_radius =0.3
double ProblemParameters::Element_area = 0.01
Target area for initial mesh.
TimeStepper * ProblemParameters::Internal_time_stepper_pt =0
Pointer to timestepper for internal dofs.
Function Documentation
main()
int main (int argc , char ** argv)
Main function.
Set dependent parameters
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Output directory
  CommandLineArgs::specify_command_line_flag("--dir",
                                             &ProblemParameters::Directory);
  // Validation?
  CommandLineArgs::specify_command_line_flag("--validation");
  // Target element area for triangle
  CommandLineArgs::specify_command_line_flag("--element_area",
                                             &ProblemParameters::Element_area);
  // Steady solve?
  CommandLineArgs::specify_command_line_flag("--steady");
  // Biot parameter
  CommandLineArgs::specify_command_line_flag("--alpha",
                                             &ProblemParameters::Alpha);
  // Density ratio (fluid to solid)
  CommandLineArgs::specify_command_line_flag("--density_ratio",
                                             &ProblemParameters::Density_ratio);
  // Intertia parameter
  CommandLineArgs::specify_command_line_flag("--lambda_sq",
                                             &ProblemParameters::Lambda_sq);
  // Timestep
  CommandLineArgs::specify_command_line_flag("--dt",
                                             &ProblemParameters::Dt);
  // Steepness parameter for tanh increment of pressure load
  CommandLineArgs::specify_command_line_flag("--alpha_tanh",
                                             &ProblemParameters::Alpha_tanh);
  // "Time" for tanh increment of pressure load
  CommandLineArgs::specify_command_line_flag("--t_tanh",
                                             &ProblemParameters::T_tanh);
  // Precalculate n_steps based on defaults
  unsigned n_steps=unsigned(1.0/ProblemParameters::Dt);
  // Override n_steps if provided
  CommandLineArgs::specify_command_line_flag("--n_steps",
                                             &n_steps);
  // Max number of adaptations per Newton solve
  unsigned max_adapt=0;
  CommandLineArgs::specify_command_line_flag("--max_adapt",
                                             &max_adapt);
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Don't override the value of Lambda^2 set on the command line
  if(!CommandLineArgs::command_line_flag_has_been_set("--lambda_sq"))
   {
    // And if it's steady
    if(CommandLineArgs::command_line_flag_has_been_set("--steady"))
     {
      // Switch on steady flag
      ProblemParameters::Steady=true;
      // Disable inertia
      ProblemParameters::Lambda_sq=0;
     }
    else // Unsteady
     {
      // Disable steady flag
      ProblemParameters::Steady=false;
      // Set default inertia parameter value
      ProblemParameters::Lambda_sq=1e-5;
     }
   }
  ProblemParameters::update_dependent_parameters();
 #ifdef ADAPTIVE
  // The problem instance
  AxiPoroProblem<ProjectableAxisymmetricPoroelasticityElement<
   TAxisymmetricPoroelasticityElement<1> >, Newmark<1> > problem;
 #else
  // The problem instance
  AxiPoroProblem<TAxisymmetricPoroelasticityElement<1>, Newmark<1> > problem;
 #endif
  // Doc initial configuration
  problem.doc_solution(0);
  // If we're doing a steady solve
  if(CommandLineArgs::command_line_flag_has_been_set("--steady"))
   {
    // Set time to 1 so that the exact solution reduces to the steady solution
    problem.time_pt()->time()=1.0;
    // Set the BCs
    problem.set_boundary_values();
    // Do the steady solve
    problem.steady_newton_solve();
    // Doc the solution
    problem.doc_solution(1);
   }
  else
   {
    // Set the initial time to t=0
    problem.time_pt()->time()=0.0;
    // Initialise the timestep
    problem.initialise_dt(ProblemParameters::Dt);
    // Set up the initial conditions
    problem.set_initial_condition();
 #ifdef ADAPTIVE
    // We're doing the first timestep
    bool first=true;
 #endif
    // Loop over timesteps
    for(unsigned i=1;i<=n_steps;i++)
     {
      // Output current time
      oomph_info << "Solving at time "
                 << problem.time_pt()->time()+ProblemParameters::Dt << std::endl;
 #ifdef ADAPTIVE
      // Solve the problem with the adaptive Newton's method, allowing
      // up to max_adapt mesh adaptations after every solve.
      problem.unsteady_newton_solve(ProblemParameters::Dt,max_adapt,first);
      // Now we've done the first timestep...
      first=false;
 #else
      // Do the unsteady solve
      problem.unsteady_newton_solve(ProblemParameters::Dt);
 #endif
      // Doc the solution
      problem.doc_solution(i);
     }
   }
  return 0;
 }
References ProblemParameters::Alpha, ProblemParameters::Alpha_tanh, oomph::CommandLineArgs::command_line_flag_has_been_set(), ProblemParameters::Density_ratio, ProblemParameters::Directory, oomph::CommandLineArgs::doc_specified_flags(), ProblemParameters::Dt, e(), ProblemParameters::Element_area, i, ProblemParameters::Lambda_sq, oomph::oomph_info, oomph::CommandLineArgs::parse_and_assign(), problem, oomph::CommandLineArgs::setup(), oomph::CommandLineArgs::specify_command_line_flag(), ProblemParameters::Steady, ProblemParameters::T_tanh, and ProblemParameters::update_dependent_parameters().