MercuryDPM: Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr > Class Template Reference
Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr > Class Template Reference
#include <BlasUtil.h>
Classes
struct storePacketBlock_helper
struct storePacketBlock_helper< SubPacket, Scalar_, n, -1 >
struct storePacketBlock_helper< SubPacket, std::complex< double >, n, -1 >
struct storePacketBlock_helper< SubPacket, std::complex< double >, n, idx >
struct storePacketBlock_helper< SubPacket, std::complex< float >, n, -1 >
struct storePacketBlock_helper< SubPacket, std::complex< float >, n, idx >
Public Types
typedef BlasLinearMapper< Scalar, Index, AlignmentType, Incr > LinearMapper
typedef blas_data_mapper SubMapper
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE blas_data_mapper (Scalar *data, Index stride, Index incr)
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE SubMapper getSubMapper (Index i, Index j) const
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE LinearMapper getLinearMapper (Index i, Index j) const
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void prefetch (Index i, Index j) const
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Scalar & operator() (Index i, Index j) const
template<typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE PacketType loadPacket (Index i, Index j) const
template<typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE PacketType loadPacketPartial (Index i, Index j, Index n, Index=0) const
template<typename PacketT , int AlignmentT>
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE PacketT load (Index i, Index j) const
template<typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void storePacket (Index i, Index j, const PacketType &p) const
template<typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void storePacketPartial (Index i, Index j, const PacketType &p, Index n, Index=0) const
template<typename SubPacket >
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void scatterPacket (Index i, Index j, const SubPacket &p) const
template<typename SubPacket >
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE SubPacket gatherPacket (Index i, Index j) const
template<typename SubPacket , int n>
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void storePacketBlock (Index i, Index j, const PacketBlock< SubPacket, n > &block) const
EIGEN_DEVICE_FUNC const Index stride () const
EIGEN_DEVICE_FUNC const Index incr () const
constexpr EIGEN_DEVICE_FUNC Scalar * data () const
Protected Attributes
Scalar *EIGEN_RESTRICT m_data
const Index m_stride
const internal::variable_if_dynamic< Index, Incr > m_incr
Member Typedef Documentation
LinearMapper
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType, int Incr> typedef BlasLinearMapper<Scalar, Index, AlignmentType, Incr> Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::LinearMapper
SubMapper
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType, int Incr> typedef blas_data_mapper Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::SubMapper
Constructor & Destructor Documentation
blas_data_mapper()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType, int Incr> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::blas_data_mapper (Scalar * data, Index stride, Index incr) inline
       : m_data(data), m_stride(stride), m_incr(incr) {}
Member Function Documentation
data()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType, int Incr> constexpr EIGEN_DEVICE_FUNC Scalar* Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::data () const inline constexpr
 { return m_data; }
References Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_data.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
gatherPacket()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType, int Incr> template<typename SubPacket > EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE SubPacket Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::gatherPacket (Index i, Index j) const inline
{
     return pgather<Scalar, SubPacket>(&operator()(i, j), m_stride);
   }
References i, j, and Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_stride.
getLinearMapper()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType, int Incr> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE LinearMapper Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::getLinearMapper (Index i, Index j) const inline
{
     return LinearMapper(&operator()(i, j), m_incr.value());
   }
References i, j, Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_incr, and Eigen::internal::variable_if_dynamic< T, Value >::value().
getSubMapper()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType, int Incr> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE SubMapper Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::getSubMapper (Index i, Index j) const inline
{
     return SubMapper(&operator()(i, j), m_stride, m_incr.value());
   }
References i, j, Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_incr, Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_stride, and Eigen::internal::variable_if_dynamic< T, Value >::value().
incr()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType, int Incr> EIGEN_DEVICE_FUNC const Index Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::incr () const inline
 { return m_incr.value(); }
References Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_incr, and Eigen::internal::variable_if_dynamic< T, Value >::value().
Referenced by Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::blas_data_mapper().
load()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType, int Incr> template<typename PacketT , int AlignmentT> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE PacketT Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::load (Index i, Index j) const inline
{
     return pgather<Scalar, PacketT>(&operator()(i, j), m_incr.value());
   }
References i, j, Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_incr, and Eigen::internal::variable_if_dynamic< T, Value >::value().
loadPacket()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType, int Incr> template<typename PacketType > EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE PacketType Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::loadPacket (Index i, Index j) const inline
{
     return pgather<Scalar, PacketType>(&operator()(i, j), m_incr.value());
   }
References i, j, Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_incr, and Eigen::internal::variable_if_dynamic< T, Value >::value().
loadPacketPartial()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType, int Incr> template<typename PacketType > EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE PacketType Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::loadPacketPartial (Index i, Index j, Index n, Index = 0) const inline
{
     return pgather_partial<Scalar, PacketType>(&operator()(i, j), m_incr.value(), n);
   }
References i, j, Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_incr, n, and Eigen::internal::variable_if_dynamic< T, Value >::value().
operator()()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType, int Incr> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Scalar& Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::operator() (Index i, Index j) const inline
{
     return m_data[StorageOrder == RowMajor ? j * m_incr.value() + i * m_stride : i * m_incr.value() + j * m_stride];
   }
References i, j, Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_data, Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_incr, Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_stride, Eigen::RowMajor, and Eigen::internal::variable_if_dynamic< T, Value >::value().
prefetch()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType, int Incr> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::prefetch (Index i, Index j) const inline
 { internal::prefetch(&operator()(i, j)); }
References i, j, and Eigen::internal::prefetch().
scatterPacket()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType, int Incr> template<typename SubPacket > EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::scatterPacket (Index i, Index j, const SubPacket & p) const inline
{
     pscatter<Scalar, SubPacket>(&operator()(i, j), p, m_stride);
   }
References i, j, Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_stride, and p.
storePacket()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType, int Incr> template<typename PacketType > EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::storePacket (Index i, Index j, const PacketType & p) const inline
{
     pscatter<Scalar, PacketType>(&operator()(i, j), p, m_incr.value());
   }
References i, j, Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_incr, p, and Eigen::internal::variable_if_dynamic< T, Value >::value().
storePacketBlock()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType, int Incr> template<typename SubPacket , int n> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::storePacketBlock (Index i, Index j, const PacketBlock< SubPacket, n > & block) const inline
{
     storePacketBlock_helper<SubPacket, Scalar, n, n - 1> spb;
     spb.store(this, i, j, block);
   }
References block(), i, j, and n.
storePacketPartial()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType, int Incr> template<typename PacketType > EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::storePacketPartial (Index i, Index j, const PacketType & p, Index n, Index = 0) const inline
{
     pscatter_partial<Scalar, PacketType>(&operator()(i, j), p, m_incr.value(), n);
   }
References i, j, Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_incr, n, p, and Eigen::internal::variable_if_dynamic< T, Value >::value().
stride()
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType, int Incr> EIGEN_DEVICE_FUNC const Index Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::stride () const inline
 { return m_stride; }
References Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_stride.
Member Data Documentation
m_data
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType, int Incr> Scalar* EIGEN_RESTRICT Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_data protected
Referenced by Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::data(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::data(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::firstAligned(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::operator()(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::operator()(), and Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::storePacketBlock().
m_incr
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType, int Incr> const internal::variable_if_dynamic<Index, Incr> Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_incr protected
Referenced by Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::getLinearMapper(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::getSubMapper(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::incr(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::load(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::loadPacket(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::loadPacketPartial(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::operator()(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::storePacket(), and Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::storePacketPartial().
m_stride
template<typename Scalar , typename Index , int StorageOrder, int AlignmentType, int Incr> const Index Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::m_stride protected
Referenced by Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::gatherPacket(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::gatherPacket(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::getSubMapper(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::getSubMapper(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::operator()(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::operator()(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::scatterPacket(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::scatterPacket(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::storePacketBlock(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::stride(), and Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::stride().
The documentation for this class was generated from the following file:
BlasUtil.h