MercuryDPM: oomph::ContinuousBermudezPMLMapping Class Reference
oomph::ContinuousBermudezPMLMapping Class Reference
#include <pml_mapping_functions.h>
Public Member Functions
ContinuousBermudezPMLMapping ()
Default constructor (empty)
std::complex< double > gamma (const double &nu_i, const double &pml_width_i, const double &wavenumber_squared, const double &alpha_shift=0.0)
Public Member Functions inherited from oomph::PMLMapping
PMLMapping ()
Default constructor (empty)
Detailed Description
A mapping function proposed by Bermudez et al, similar to the one above but is continuous across the inner Pml boundary appears to be the best for TimeHarmonicLinearElasticity and so this will be the default mapping
Constructor & Destructor Documentation
ContinuousBermudezPMLMapping()
oomph::ContinuousBermudezPMLMapping::ContinuousBermudezPMLMapping () inline
Default constructor (empty)
 {};
Member Function Documentation
gamma()
std::complex<double> oomph::ContinuousBermudezPMLMapping::gamma (const double & nu_i, const double & pml_width_i, const double & wavenumber_squared, const double & alpha_shift = 0.0) inline virtual
Overwrite the pure Pml mapping coefficient function to return the coeffcients proposed by Bermudez et al
return \(\gamma=1 + (i/k)(1/|outer_boundary - x|-1/|pml width|)\)
Implements oomph::PMLMapping.
     {
       return 1.0 + MathematicalConstants::I / sqrt(wavenumber_squared) *
                      (1.0 / std::fabs(pml_width_i - nu_i) -
                       1.0 / std::fabs(pml_width_i));
     }
References boost::multiprecision::fabs(), oomph::MathematicalConstants::I(), and sqrt().
The documentation for this class was generated from the following file:
pml_mapping_functions.h