MercuryDPM: oomph::DoubleVectorWithHaloEntries Class Reference
oomph::DoubleVectorWithHaloEntries Class Reference
#include <double_vector_with_halo.h>
Public Member Functions
DoubleVectorWithHaloEntries ()
Constructor for an uninitialized DoubleVectorWithHaloEntries.
DoubleVectorWithHaloEntries (const LinearAlgebraDistribution *const &dist_pt, DoubleVectorHaloScheme *const &halo_scheme_pt=0, const double &v=0.0)
DoubleVectorWithHaloEntries (const LinearAlgebraDistribution &dist, DoubleVectorHaloScheme *const &halo_scheme_pt=0, const double &v=0.0)
~DoubleVectorWithHaloEntries ()
Destructor.
DoubleVectorWithHaloEntries (const DoubleVectorWithHaloEntries &new_vector)
Copy constructor from any DoubleVector.
DoubleVectorWithHaloEntries (const DoubleVector &new_vector, DoubleVectorHaloScheme *const &halo_scheme_pt=0)
Copy constructor from any DoubleVector.
void operator= (const DoubleVectorWithHaloEntries &old_vector)
assignment operator
double & global_value (const unsigned &i)
Direct access to global entry.
const double & global_value (const unsigned &i) const
Direct access to the global entry (const version)
void synchronise ()
Synchronise the halo data.
void sum_all_halo_and_haloed_values ()
DoubleVectorHaloScheme *& halo_scheme_pt ()
Access function for halo scheme.
DoubleVectorHaloScheme *const & halo_scheme_pt () const
Access function for halo scheme (const version)
void build_halo_scheme (DoubleVectorHaloScheme *const &halo_scheme_pt)
Construct the halo scheme and storage for the halo data.
Public Member Functions inherited from oomph::DoubleVector
DoubleVector ()
Constructor for an uninitialized DoubleVector.
DoubleVector (const LinearAlgebraDistribution *const &dist_pt, const double &v=0.0)
DoubleVector (const LinearAlgebraDistribution &dist, const double &v=0.0)
~DoubleVector ()
DoubleVector (const DoubleVector &new_vector)
Copy constructor.
void operator= (const DoubleVector &old_vector)
assignment operator
void build (const DoubleVector &old_vector)
Just copys the argument DoubleVector.
void build (const LinearAlgebraDistribution &dist, const double &v)
void build (const LinearAlgebraDistribution *const &dist_pt, const double &v)
void build (const LinearAlgebraDistribution &dist, const Vector< double > &v)
void build (const LinearAlgebraDistribution *const &dist_pt, const Vector< double > &v)
void initialise (const double &v)
initialise the whole vector with value v
void initialise (const Vector< double > v)
void clear ()
wipes the DoubleVector
bool built () const
void set_external_values (const LinearAlgebraDistribution *const &dist_pt, double *external_values, bool delete_external_values)
void set_external_values (double *external_values, bool delete_external_values)
void redistribute (const LinearAlgebraDistribution *const &dist_pt)
double & operator[] (int i)
[] access function to the (local) values of this vector
bool operator== (const DoubleVector &v)
== operator
void operator+= (const DoubleVector &v)
+= operator with another vector
void operator-= (const DoubleVector &v)
-= operator with another vector
void operator*= (const double &d)
multiply by a double
void operator/= (const double &d)
divide by a double
const double & operator[] (int i) const
[] access function to the (local) values of this vector
double max () const
returns the maximum coefficient
double * values_pt ()
access function to the underlying values
double * values_pt () const
access function to the underlying values (const version)
void output (std::ostream &outfile, const int &output_precision=-1) const
output the global contents of the vector
void output (std::string filename, const int &output_precision=-1) const
output the global contents of the vector
void output_local_values (std::ostream &outfile, const int &output_precision=-1) const
output the local contents of the vector
void output_local_values (std::string filename, const int &output_precision=-1) const
output the local contents of the vector
void output_local_values_with_offset (std::ostream &outfile, const int &output_precision=-1) const
output the local contents of the vector
void output_local_values_with_offset (std::string filename, const int &output_precision=-1) const
output the local contents of the vector
double dot (const DoubleVector &vec) const
compute the dot product of this vector with the vector vec.
double norm () const
compute the 2 norm of this vector
double norm (const CRDoubleMatrix *matrix_pt) const
compute the A-norm using the matrix at matrix_pt
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
void build_distribution (const LinearAlgebraDistribution &dist)
Private Attributes
DoubleVectorHaloScheme * Halo_scheme_pt
Vector< double > Halo_value
Vector of the halo values.
Additional Inherited Members
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
Detailed Description
===================================================================== An extension of DoubleVector that allows access to certain global entries that are not stored locally. Synchronisation of these values must be performed manually by calling the synchronise() function. Synchronisation can only be from the haloed to the halo, but the local halo entries can all be summed and stored in the
haloed value.
Constructor & Destructor Documentation
DoubleVectorWithHaloEntries() [1/5]
oomph::DoubleVectorWithHaloEntries::DoubleVectorWithHaloEntries () inline
Constructor for an uninitialized DoubleVectorWithHaloEntries.
 : DoubleVector(), Halo_scheme_pt(0) {}
DoubleVectorWithHaloEntries() [2/5]
oomph::DoubleVectorWithHaloEntries::DoubleVectorWithHaloEntries (const LinearAlgebraDistribution *const & dist_pt, DoubleVectorHaloScheme *const & halo_scheme_pt = 0, const double & v = 0.0) inline
Constructor. Assembles a DoubleVectorWithHaloEntries with a prescribed distribution. Additionally every entry can be set (with argument v - defaults to 0).
       : DoubleVector(dist_pt, v)
     {
       // construct the halo scheme
       this->build_halo_scheme(halo_scheme_pt);
     }
References build_halo_scheme(), and halo_scheme_pt().
DoubleVectorWithHaloEntries() [3/5]
oomph::DoubleVectorWithHaloEntries::DoubleVectorWithHaloEntries (const LinearAlgebraDistribution & dist, DoubleVectorHaloScheme *const & halo_scheme_pt = 0, const double & v = 0.0) inline
Constructor. Assembles a DoubleVectorWithHaloEntries with a prescribed distribution. Additionally every entry can be set (with argument v - defaults to 0).
       : DoubleVector(dist, v)
     {
       // construct the halo scheme
       this->build_halo_scheme(halo_scheme_pt);
     }
References build_halo_scheme(), and halo_scheme_pt().
~DoubleVectorWithHaloEntries()
oomph::DoubleVectorWithHaloEntries::~DoubleVectorWithHaloEntries () inline
Destructor.
 {}
DoubleVectorWithHaloEntries() [4/5]
oomph::DoubleVectorWithHaloEntries::DoubleVectorWithHaloEntries (const DoubleVectorWithHaloEntries & new_vector) inline
Copy constructor from any DoubleVector.
       : DoubleVector(new_vector)
     {
       // Build the appropriate halo scheme
       this->build_halo_scheme(new_vector.halo_scheme_pt());
     }
References build_halo_scheme(), and halo_scheme_pt().
DoubleVectorWithHaloEntries() [5/5]
oomph::DoubleVectorWithHaloEntries::DoubleVectorWithHaloEntries (const DoubleVector & new_vector, DoubleVectorHaloScheme *const & halo_scheme_pt = 0) inline
Copy constructor from any DoubleVector.
       : DoubleVector(new_vector)
     {
       // Construct the halo scheme
       this->build_halo_scheme(halo_scheme_pt);
     }
References build_halo_scheme(), and halo_scheme_pt().
Member Function Documentation
build_halo_scheme()
void oomph::DoubleVectorWithHaloEntries::build_halo_scheme (DoubleVectorHaloScheme *const & halo_scheme_pt)
Construct the halo scheme and storage for the halo data.
Construct the halo scheme and storage for the halo data
   {
     Halo_scheme_pt = halo_scheme_pt;
     if (Halo_scheme_pt != 0)
     {
       // Need to set up the halo data
       unsigned n_halo_data = halo_scheme_pt->Local_index.size();
       // Resize the halo storage
       Halo_value.resize(n_halo_data);
       // Now let's get the initial values from the other processors
       this->synchronise();
     }
   }
References Halo_scheme_pt, halo_scheme_pt(), Halo_value, oomph::DoubleVectorHaloScheme::Local_index, and synchronise().
Referenced by DoubleVectorWithHaloEntries(), operator=(), oomph::PitchForkHandler::PitchForkHandler(), and oomph::Problem::setup_element_count_per_dof().
global_value() [1/2]
double& oomph::DoubleVectorWithHaloEntries::global_value (const unsigned & i) inline
Direct access to global entry.
     {
       // Only need to worry about the distributed case if
       // we have compiled with MPI
 #ifdef OOMPH_HAS_MPI
       if (this->distributed())
       {
         const unsigned first_row_local = this->first_row();
         const unsigned n_row_local = this->nrow_local();
         // If we are in range then just call the local value
         if ((i >= first_row_local) && (i < first_row_local + n_row_local))
         {
           return (*this)[i - first_row_local];
         }
         // Otherwise the entry is not stored in the local processor
         // and we must have haloed it
         else
         {
 #ifdef PARANOID
           if (Halo_scheme_pt == 0)
           {
             std::ostringstream error_stream;
             error_stream
               << "Halo data requested, but no halo scheme has been setup\n"
               << "You should call this->build_halo_scheme(halo_scheme_pt).\n"
               << "You may wish to setup the scheme for the Problem using \n"
               << "Problem::setup_dof_halo_scheme()\n";
             throw OomphLibError(error_stream.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
           }
 #endif
           return Halo_value[Halo_scheme_pt->local_index(i)];
         }
       }
       // If not distributed the global entry is
       // the local entry
       else
 #endif
       {
         return (*this)[i];
       }
     }
References oomph::DistributableLinearAlgebraObject::distributed(), oomph::DistributableLinearAlgebraObject::first_row(), Halo_scheme_pt, Halo_value, i, oomph::DoubleVectorHaloScheme::local_index(), oomph::DistributableLinearAlgebraObject::nrow_local(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::PitchForkHandler::get_dresiduals_dparameter(), oomph::PitchForkHandler::get_jacobian(), oomph::PitchForkHandler::get_residuals(), oomph::PitchForkHandler::PitchForkHandler(), and oomph::Problem::setup_element_count_per_dof().
global_value() [2/2]
const double& oomph::DoubleVectorWithHaloEntries::global_value (const unsigned & i) const inline
Direct access to the global entry (const version)
     {
       // Only need to worry about the distributed case if
       // we have compiled with MPI
 #ifdef OOMPH_HAS_MPI
       if (this->distributed())
       {
         const unsigned first_row_local = this->first_row();
         const unsigned n_row_local = this->nrow_local();
         // If we are in range then just call the local value
         if ((i >= first_row_local) && (i < first_row_local + n_row_local))
         {
           return (*this)[i - first_row_local];
         }
         // Otherwise the entry is not stored in the local processor
         // and we must have haloed it
         else
         {
 #ifdef PARANOID
           if (Halo_scheme_pt == 0)
           {
             std::ostringstream error_stream;
             error_stream
               << "Halo data requested, but no halo scheme has been setup\n"
               << "You should call this->build_halo_scheme(halo_scheme_pt).\n"
               << "You may wish to setup the scheme for the Problem using \n"
               << "Problem::setup_dof_halo_scheme()\n";
             throw OomphLibError(error_stream.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
           }
 #endif
           return Halo_value[Halo_scheme_pt->local_index(i)];
         }
       }
       // If not distributed the global entry is
       // the local entry
       else
 #endif
       {
         return (*this)[i];
       }
     }
References oomph::DistributableLinearAlgebraObject::distributed(), oomph::DistributableLinearAlgebraObject::first_row(), Halo_scheme_pt, Halo_value, i, oomph::DoubleVectorHaloScheme::local_index(), oomph::DistributableLinearAlgebraObject::nrow_local(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
halo_scheme_pt() [1/2]
DoubleVectorHaloScheme*& oomph::DoubleVectorWithHaloEntries::halo_scheme_pt () inline
Access function for halo scheme.
     {
       return Halo_scheme_pt;
     }
References Halo_scheme_pt.
Referenced by build_halo_scheme(), DoubleVectorWithHaloEntries(), and operator=().
halo_scheme_pt() [2/2]
DoubleVectorHaloScheme* const& oomph::DoubleVectorWithHaloEntries::halo_scheme_pt () const inline
Access function for halo scheme (const version)
     {
       return Halo_scheme_pt;
     }
References Halo_scheme_pt.
operator=()
void oomph::DoubleVectorWithHaloEntries::operator= (const DoubleVectorWithHaloEntries & old_vector) inline
assignment operator
     {
       this->build(old_vector);
       // Do some other stuff
       this->build_halo_scheme(old_vector.halo_scheme_pt());
     }
References oomph::DoubleVector::build(), build_halo_scheme(), and halo_scheme_pt().
sum_all_halo_and_haloed_values()
void oomph::DoubleVectorWithHaloEntries::sum_all_halo_and_haloed_values ()
Sum all the data, store in the master (haloed) data and then synchronise
Gather all ther data from multiple processors and sum the result which will be stored in the master copy and then synchronised to all copies. This requires two "all to all" communications
   {
 #ifdef OOMPH_HAS_MPI
     // Only need to do anything if the DoubleVector is distributed
     if (this->distributed())
     {
       // Send the Halo entries to the master processor
       const unsigned n_send = Halo_scheme_pt->Halo_eqns.size();
       Vector<double> send_data(n_send);
       // Read out the data values
       for (unsigned i = 0; i < n_send; i++)
       {
         send_data[i] = Halo_value[Halo_scheme_pt->Halo_eqns[i]];
       }
       // Read out the number of entries to receive
       const unsigned n_receive = Halo_scheme_pt->Haloed_eqns.size();
       Vector<double> receive_data(n_receive);
       // Make sure that the send and receive data have size at least one
       if (n_send == 0)
       {
         send_data.resize(1);
       }
       if (n_receive == 0)
       {
         receive_data.resize(1);
       }
       // Communicate
       MPI_Alltoallv(&send_data[0],
                     &Halo_scheme_pt->Halo_n[0],
                     &Halo_scheme_pt->Halo_displacement[0],
                     MPI_DOUBLE,
                     &receive_data[0],
                     &Halo_scheme_pt->Haloed_n[0],
                     &Halo_scheme_pt->Haloed_displacement[0],
                     MPI_DOUBLE,
                     this->distribution_pt()->communicator_pt()->mpi_comm());
       // Now I need simply to update and sum my  local values
       for (unsigned i = 0; i < n_receive; i++)
       {
         (*this)[Halo_scheme_pt->Haloed_eqns[i]] += receive_data[i];
       }
       // Then synchronise
       this->synchronise();
     }
 #endif
   }
References oomph::DistributableLinearAlgebraObject::distributed(), oomph::DoubleVectorHaloScheme::Halo_displacement, oomph::DoubleVectorHaloScheme::Halo_eqns, oomph::DoubleVectorHaloScheme::Halo_n, Halo_scheme_pt, Halo_value, oomph::DoubleVectorHaloScheme::Haloed_displacement, oomph::DoubleVectorHaloScheme::Haloed_eqns, oomph::DoubleVectorHaloScheme::Haloed_n, i, and synchronise().
Referenced by oomph::PitchForkHandler::PitchForkHandler(), and oomph::Problem::setup_element_count_per_dof().
synchronise()
void oomph::DoubleVectorWithHaloEntries::synchronise ()
Synchronise the halo data.
Synchronise the halo data within the vector. This requires one "all to all" communnication.
   {
 #ifdef OOMPH_HAS_MPI
     // Only need to do anything if the DoubleVector is distributed
     if (this->distributed())
     {
       // Read out the number of entries to send
       const unsigned n_send = Halo_scheme_pt->Haloed_eqns.size();
       Vector<double> send_data(n_send);
       // Read out the data values
       for (unsigned i = 0; i < n_send; i++)
       {
         send_data[i] = (*this)[Halo_scheme_pt->Haloed_eqns[i]];
       }
       // Read out the number of entries to receive
       const unsigned n_receive = Halo_scheme_pt->Halo_eqns.size();
       Vector<double> receive_data(n_receive);
       // Make sure that the send and receive data have size at least one
       if (n_send == 0)
       {
         send_data.resize(1);
       }
       if (n_receive == 0)
       {
         receive_data.resize(1);
       }
       // Communicate
       MPI_Alltoallv(&send_data[0],
                     &Halo_scheme_pt->Haloed_n[0],
                     &Halo_scheme_pt->Haloed_displacement[0],
                     MPI_DOUBLE,
                     &receive_data[0],
                     &Halo_scheme_pt->Halo_n[0],
                     &Halo_scheme_pt->Halo_displacement[0],
                     MPI_DOUBLE,
                     this->distribution_pt()->communicator_pt()->mpi_comm());
       // Now I need simply to update my local values
       for (unsigned i = 0; i < n_receive; i++)
       {
         Halo_value[Halo_scheme_pt->Halo_eqns[i]] = receive_data[i];
       }
     }
 #endif
   }
References oomph::DistributableLinearAlgebraObject::distributed(), oomph::DoubleVectorHaloScheme::Halo_displacement, oomph::DoubleVectorHaloScheme::Halo_eqns, oomph::DoubleVectorHaloScheme::Halo_n, Halo_scheme_pt, Halo_value, oomph::DoubleVectorHaloScheme::Haloed_displacement, oomph::DoubleVectorHaloScheme::Haloed_eqns, oomph::DoubleVectorHaloScheme::Haloed_n, and i.
Referenced by build_halo_scheme(), and sum_all_halo_and_haloed_values().
Member Data Documentation
Halo_scheme_pt
DoubleVectorHaloScheme* oomph::DoubleVectorWithHaloEntries::Halo_scheme_pt private
Pointer to the lookup scheme that stores information about on which processor the required information is haloed
Referenced by build_halo_scheme(), global_value(), halo_scheme_pt(), sum_all_halo_and_haloed_values(), and synchronise().
Halo_value
Vector<double> oomph::DoubleVectorWithHaloEntries::Halo_value private
Vector of the halo values.
Referenced by build_halo_scheme(), global_value(), sum_all_halo_and_haloed_values(), and synchronise().
The documentation for this class was generated from the following files:
double_vector_with_halo.h
double_vector_with_halo.cc