MercuryDPM: multi_domain_boussinesq_convection.cc File Reference
mpi/multi_domain/boussinesq_convection/multi_domain_boussinesq_convection.cc File Reference
#include "generic.h"
#include "advection_diffusion.h"
#include "navier_stokes.h"
#include "multi_physics.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class ConvectionProblem< NST_ELEMENT, AD_ELEMENT >
Namespaces
Global_Physical_Variables
Global variables.
Functions
int main (int argc, char **argv)
Driver code for 2D Boussinesq convection problem.
Variables
double Global_Physical_Variables::Inverse_Prandtl =1.0
1/Prandtl number
double Global_Physical_Variables::Rayleigh = 1800.0
Rayleigh number.
Vector< double > Global_Physical_Variables::Direction_of_gravity (2)
Gravity vector.
Function Documentation
main()
int main (int argc , char ** argv)
Driver code for 2D Boussinesq convection problem.
 {
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::init(argc,argv);
 #endif
   // Switch off output modifier
  oomph_info.output_modifier_pt() = &default_output_modifier;
  // Define processor-labeled output file for all on-screen stuff
  std::ofstream output_stream;
  char filename[100];
  sprintf(filename,"OUTPUT.%i",MPI_Helpers::communicator_pt()->my_rank());
  output_stream.open(filename);
  oomph_info.stream_pt() = &output_stream;
  OomphLibWarning::set_stream_pt(&output_stream);
  OomphLibError::set_stream_pt(&output_stream);
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Set the direction of gravity
  Global_Physical_Variables::Direction_of_gravity[0] = 0.0;
  Global_Physical_Variables::Direction_of_gravity[1] = -1.0;
  //Construct our problem
  ConvectionProblem<
  NavierStokesBoussinesqElement<QCrouzeixRaviartElement<2>,
                                QAdvectionDiffusionElement<2,3> > ,
   AdvectionDiffusionBoussinesqElement<QAdvectionDiffusionElement<2,3>,
                                       QCrouzeixRaviartElement<2> >
   >
   problem;
  // Apply the boundary condition at time zero
  problem.set_boundary_conditions(0.0);
  // Distribute the problem
  //-----------------------
 #ifdef OOMPH_HAS_MPI
  DocInfo mesh_doc_info;
  mesh_doc_info.number()=0;
 #ifdef USE_FD_JACOBIAN_NST_IN_MULTI_DOMAIN_BOUSSINESQ
  mesh_doc_info.set_directory("RESLT_FD");
 #else
  mesh_doc_info.set_directory("RESLT");
 #endif
  bool report_stats=true;
  // Are there command-line arguments?
  if (CommandLineArgs::Argc==1)
   {
    // No arguments, so distribute without reference to partition vector
    problem.distribute(mesh_doc_info,report_stats);
   }
  else
   {
    // Command line argument(s), so read in partition from file
    std::ifstream input_file;
    std::ofstream output_file;
    char filename[100];
    // Get partition from file
    unsigned n_element=problem.mesh_pt()->nelement();
    Vector<unsigned> element_partition(n_element);
    // Two possible partitions on two processors - one for "normal"
    // METIS behaviour, the other gives one mesh to one processor
    // and the other mesh to the other processor
    if (atoi(argv[2])==2)
     {
      oomph_info << "Using connected partitioning" << std::endl;
      sprintf(filename,"multi_domain_boussinesq_partition_2.dat");
     }
    else
     {
      oomph_info << "Giving a mesh to each processor" << std::endl;
      sprintf(filename,"multi_domain_boussinesq_partition.dat");
     }
    input_file.open(filename);
    oomph_info << "Opened: " << filename << std::endl;
    if (!input_file.is_open())
     {
      oomph_info << "Error opening input file\n";
      exit(1);
     }
    std::string input_string;
    for (unsigned e=0;e<n_element;e++)
     {
      if (getline(input_file,input_string,'\n'))
       {
        element_partition[e]=atoi(input_string.c_str());
       }
      else
       {
        oomph_info << "Reached end of file when reading partitioning file\n";
        exit(1);
       }
     }
    input_file.close();
    // Create storage for actually used partitioning
    Vector<unsigned> used_element_partition;
    used_element_partition=problem.distribute(element_partition,
                                              mesh_doc_info,report_stats);
    // Write used partition to disk
    sprintf(filename,"RESLT/partitioning.dat");
    output_file.open(filename);
    unsigned n_used=used_element_partition.size();
    output_file << n_used << std::endl;
    for (unsigned e=0;e<n_used;e++)
     {
      output_file << used_element_partition[e] << std::endl;
     }
    output_file.close();
   }
 #endif
  //Perform a single steady Newton solve
  problem.steady_newton_solve();
  //Document the solution
  problem.doc_solution();
  //Set the timestep
  double dt = 0.1;
  //Initialise the value of the timestep and set an impulsive start
  problem.assign_initial_values_impulsive(dt);
  //Set the number of timesteps to our default value
  unsigned n_steps = 200;
  //If we have a command line argument, perform fewer steps
  //(used for self-test runs)
  if(argc > 1) {n_steps = 5;}
  //Perform n_steps timesteps
  for(unsigned i=0;i<n_steps;++i)
   {
    problem.unsteady_newton_solve(dt);
    problem.doc_solution();
   }
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::finalize();
 #endif
 } // end of main
References oomph::CommandLineArgs::Argc, oomph::MPI_Helpers::communicator_pt(), oomph::default_output_modifier, oomph::Global_Physical_Variables::Direction_of_gravity, e(), MergeRestartFiles::filename, oomph::MPI_Helpers::finalize(), i, oomph::MPI_Helpers::init(), oomph::DocInfo::number(), oomph::oomph_info, oomph::OomphInfo::output_modifier_pt(), problem, oomph::DocInfo::set_directory(), oomph::OomphLibError::set_stream_pt(), oomph::OomphLibWarning::set_stream_pt(), oomph::CommandLineArgs::setup(), oomph::OomphInfo::stream_pt(), and oomph::Global_string_for_annotation::string().