MercuryDPM: Eigen::internal::triangular_solve_retval< Side, TriangularType, Rhs > Struct Template Reference
Eigen::internal::triangular_solve_retval< Side, TriangularType, Rhs > Struct Template Reference
#include <SolveTriangular.h>
Public Types
typedef remove_all_t< typename Rhs::Nested > RhsNestedCleaned
typedef ReturnByValue< triangular_solve_retval > Base
Public Types inherited from Eigen::ReturnByValue< triangular_solve_retval< Side, TriangularType, Rhs > >
typedef internal::traits< triangular_solve_retval< Side, TriangularType, Rhs > >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Public Member Functions
triangular_solve_retval (const TriangularType &tri, const Rhs &rhs)
EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
template<typename Dest >
void evalTo (Dest &dst) const
Public Member Functions inherited from Eigen::ReturnByValue< triangular_solve_retval< Side, TriangularType, Rhs > >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Protected Attributes
const TriangularType & m_triangularMatrix
Rhs::Nested m_rhs
Member Typedef Documentation
Base
template<int Side, typename TriangularType , typename Rhs > typedef ReturnByValue<triangular_solve_retval> Eigen::internal::triangular_solve_retval< Side, TriangularType, Rhs >::Base
RhsNestedCleaned
template<int Side, typename TriangularType , typename Rhs > typedef remove_all_t<typename Rhs::Nested> Eigen::internal::triangular_solve_retval< Side, TriangularType, Rhs >::RhsNestedCleaned
Constructor & Destructor Documentation
triangular_solve_retval()
template<int Side, typename TriangularType , typename Rhs > Eigen::internal::triangular_solve_retval< Side, TriangularType, Rhs >::triangular_solve_retval (const TriangularType & tri, const Rhs & rhs) inline
 : m_triangularMatrix(tri), m_rhs(rhs) {}
Member Function Documentation
cols()
template<int Side, typename TriangularType , typename Rhs > EIGEN_CONSTEXPR Index Eigen::internal::triangular_solve_retval< Side, TriangularType, Rhs >::cols () const inline
 { return m_rhs.cols(); }
References Eigen::internal::triangular_solve_retval< Side, TriangularType, Rhs >::m_rhs.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
evalTo()
template<int Side, typename TriangularType , typename Rhs > template<typename Dest > void Eigen::internal::triangular_solve_retval< Side, TriangularType, Rhs >::evalTo (Dest & dst) const inline
{
     if (!is_same_dense(dst, m_rhs)) dst = m_rhs;
     m_triangularMatrix.template solveInPlace<Side>(dst);
   }
References Eigen::internal::is_same_dense(), Eigen::internal::triangular_solve_retval< Side, TriangularType, Rhs >::m_rhs, and Eigen::internal::triangular_solve_retval< Side, TriangularType, Rhs >::m_triangularMatrix.
rows()
template<int Side, typename TriangularType , typename Rhs > EIGEN_CONSTEXPR Index Eigen::internal::triangular_solve_retval< Side, TriangularType, Rhs >::rows () const inline
 { return m_rhs.rows(); }
References Eigen::internal::triangular_solve_retval< Side, TriangularType, Rhs >::m_rhs.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_rhs
template<int Side, typename TriangularType , typename Rhs > Rhs::Nested Eigen::internal::triangular_solve_retval< Side, TriangularType, Rhs >::m_rhs protected
Referenced by Eigen::internal::triangular_solve_retval< Side, TriangularType, Rhs >::cols(), Eigen::internal::triangular_solve_retval< Side, TriangularType, Rhs >::evalTo(), and Eigen::internal::triangular_solve_retval< Side, TriangularType, Rhs >::rows().
m_triangularMatrix
template<int Side, typename TriangularType , typename Rhs > const TriangularType& Eigen::internal::triangular_solve_retval< Side, TriangularType, Rhs >::m_triangularMatrix protected
Referenced by Eigen::internal::triangular_solve_retval< Side, TriangularType, Rhs >::evalTo().
The documentation for this struct was generated from the following file:
SolveTriangular.h