MercuryDPM: oomph::EllipticalTube Class Reference
oomph::EllipticalTube Class Reference
#include <geom_objects.h>
Public Member Functions
EllipticalTube (const double &a, const double &b)
Constructor: Specify radius.
EllipticalTube (const EllipticalTube &node)=delete
Broken copy constructor.
void operator= (const EllipticalTube &)=delete
Broken assignment operator.
double & a ()
Access function to x-half axis.
double & b ()
Access function to y-half axis.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
Position vector (dummy unsteady version returns steady version)
virtual unsigned ngeom_data () const
How many items of Data does the shape of the object depend on?
void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
Position Vector and 1st and 2nd derivs w.r.t. zeta.
void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Position Vector and 1st and 2nd derivs w.r.t. zeta.
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual Data * geom_data_pt (const unsigned &j)
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Private Attributes
double A
x-half axis
double B
x-half axis
Additional Inherited Members
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Elliptical tube with half axes a and b.
\[ {\bf r} = (a \cos(\zeta_1), b \sin(zeta_1), \zeta_0)^T \]
Constructor & Destructor Documentation
EllipticalTube() [1/2]
oomph::EllipticalTube::EllipticalTube (const double & a, const double & b) inline
Constructor: Specify radius.
       : GeomObject(2, 3), A(a), B(b)
     {
     }
EllipticalTube() [2/2]
oomph::EllipticalTube::EllipticalTube (const EllipticalTube & node) delete
Broken copy constructor.
Member Function Documentation
a()
double& oomph::EllipticalTube::a () inline
Access function to x-half axis.
     {
       return A;
     }
References A.
b()
double& oomph::EllipticalTube::b () inline
Access function to y-half axis.
     {
       return B;
     }
References B.
d2position() [1/2]
void oomph::EllipticalTube::d2position (const Vector< double > & zeta, RankThreeTensor< double > & ddrdzeta) const inline virtual
Position Vector and 1st and 2nd derivs w.r.t. zeta.
Reimplemented from oomph::GeomObject.
     {
       ddrdzeta(0, 0, 0) = 0.0;
       ddrdzeta(0, 0, 1) = 0.0;
       ddrdzeta(0, 0, 2) = 0.0;
       ddrdzeta(1, 1, 0) = -A * cos(zeta[1]);
       ddrdzeta(1, 1, 1) = -B * sin(zeta[1]);
       ddrdzeta(1, 1, 2) = 0.0;
       ddrdzeta(0, 1, 0) = ddrdzeta(1, 0, 0) = 0.0;
       ddrdzeta(0, 1, 1) = ddrdzeta(1, 0, 1) = 0.0;
       ddrdzeta(0, 1, 2) = ddrdzeta(1, 0, 2) = 0.0;
     }
References cos(), sin(), and Eigen::zeta().
d2position() [2/2]
void oomph::EllipticalTube::d2position (const Vector< double > & zeta, Vector< double > & r, DenseMatrix< double > & drdzeta, RankThreeTensor< double > & ddrdzeta) const inline virtual
Position Vector and 1st and 2nd derivs w.r.t. zeta.
Reimplemented from oomph::GeomObject.
     {
       // Let's just do a simple tube
       r[0] = A * cos(zeta[1]);
       r[1] = B * sin(zeta[1]);
       r[2] = zeta[0];
       // Do the azetaal derivatives
       drdzeta(0, 0) = 0.0;
       drdzeta(0, 1) = 0.0;
       drdzeta(0, 2) = 1.0;
       // Do the azimuthal derivatives
       drdzeta(1, 0) = -A * sin(zeta[1]);
       drdzeta(1, 1) = B * cos(zeta[1]);
       drdzeta(1, 2) = 0.0;
       // Now let's do the second derivatives
       ddrdzeta(0, 0, 0) = 0.0;
       ddrdzeta(0, 0, 1) = 0.0;
       ddrdzeta(0, 0, 2) = 0.0;
       ddrdzeta(1, 1, 0) = -A * cos(zeta[1]);
       ddrdzeta(1, 1, 1) = -B * sin(zeta[1]);
       ddrdzeta(1, 1, 2) = 0.0;
       // Mixed derivatives
       ddrdzeta(0, 1, 0) = ddrdzeta(1, 0, 0) = 0.0;
       ddrdzeta(0, 1, 1) = ddrdzeta(1, 0, 1) = 0.0;
       ddrdzeta(0, 1, 2) = ddrdzeta(1, 0, 2) = 0.0;
     }
References cos(), UniformPSDSelfTest::r, sin(), and Eigen::zeta().
ngeom_data()
virtual unsigned oomph::EllipticalTube::ngeom_data () const inline virtual
How many items of Data does the shape of the object depend on?
Reimplemented from oomph::GeomObject.
     {
       return 0;
     }
operator=()
void oomph::EllipticalTube::operator= (const EllipticalTube &) delete
Broken assignment operator.
position() [1/2]
void oomph::EllipticalTube::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector (dummy unsteady version returns steady version)
Reimplemented from oomph::GeomObject.
     {
       position(zeta, r);
     }
References position(), UniformPSDSelfTest::r, and Eigen::zeta().
position() [2/2]
void oomph::EllipticalTube::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector.
Implements oomph::GeomObject.
     {
       r[0] = A * cos(zeta[1]);
       r[1] = B * sin(zeta[1]);
       r[2] = zeta[0];
     }
References cos(), UniformPSDSelfTest::r, sin(), and Eigen::zeta().
Referenced by position().
Member Data Documentation
A
double oomph::EllipticalTube::A private
x-half axis
Referenced by a().
B
double oomph::EllipticalTube::B private
x-half axis
Referenced by b().
The documentation for this class was generated from the following file:
geom_objects.h