MercuryDPM: two_d_unsteady_heat_t_adapt.cc File Reference
two_d_unsteady_heat_t_adapt.cc File Reference
#include "generic.h"
#include "unsteady_heat.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class UnsteadyHeatProblem< ELEMENT >
UnsteadyHeat problem.
Namespaces
ExactSolnForUnsteadyHeat
Namespace for unforced exact solution for UnsteadyHeat equation.
Functions
void ExactSolnForUnsteadyHeat::get_exact_u (const double &time, const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void ExactSolnForUnsteadyHeat::get_exact_u (const double &time, const Vector< double > &x, double &u)
Exact solution as a scalar.
void ExactSolnForUnsteadyHeat::get_source (const double &time, const Vector< double > &x, double &source)
Source function to make it an exact solution.
int main (int argc, char *argv[])
Variables
double ExactSolnForUnsteadyHeat::Gamma =10.0
Factor controlling the rate of change.
Function Documentation
main()
int main (int argc , char * argv[])
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Driver code for the adaptive solution of an unsteady heat equation with option for restart from disk: Only a single command line argument is allowed. If specified it is interpreted as the name of the restart file.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Build problem
  UnsteadyHeatProblem<QUnsteadyHeatElement<2,4> >
   problem(&ExactSolnForUnsteadyHeat::get_source);
  // Setup labels for output
  DocInfo doc_info;
  // Output directory
  doc_info.set_directory("RESLT");
  // Output number
  doc_info.number()=0;
  // Open a trace file
  ofstream trace_file;
  char filename[100];
  sprintf(filename,"%s/trace.dat",doc_info.directory().c_str());
  trace_file.open(filename);
  trace_file << "VARIABLES=\"time\",\"dt\",\"u<SUB>FE</SUB>\","
             << "\"u<SUB>exact</SUB>\",\"norm of error\",\"norm of solution\""
             << std::endl;
  // Choose simulation interval
  double t_max=0.18; // 2.0;
  // Set IC
  problem.set_initial_condition();
  // Initial timestep: Use the one used when setting up the initial
  // condition
  double dt=problem.time_pt()->dt();
  //Output initial condition
  problem.doc_solution(doc_info,trace_file);
  //Increment counter for solutions
  doc_info.number()++;
  // Target error for adaptive timestepping
  double epsilon_t=1.0e-4;
  // Timestepping loop: Don't know how many steps we're going to take
  // in advance
  while (problem.time_pt()->time()<t_max)
   {
    // Take an adaptive timestep -- the input dt is the suggested timestep.
    // The adaptive timestepper will adjust dt until the required error
    // tolerance is satisfied. The function returns a suggestion
    // for the timestep that should be taken for the next step. This
    // is either the actual timestep taken this time or a larger
    // value if the solution was found to be "too accurate".
    double dt_next=problem.adaptive_unsteady_newton_solve(dt,epsilon_t);
    // Use dt_next as suggestion for the next timestep
    dt=dt_next;
    //Output solution
    problem.doc_solution(doc_info,trace_file);
    //Increment counter for solutions
    doc_info.number()++;
   } // end of timestepping loop
  // Close trace file
  trace_file.close();
 }; // end of main
References oomph::DocInfo::directory(), MergeRestartFiles::filename, ExactSolnForUnsteadyHeat::get_source(), oomph::DocInfo::number(), problem, oomph::DocInfo::set_directory(), and Flag_definition::setup().