MercuryDPM: Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device > Struct Template Reference
#include <TensorVolumePatch.h>
Public Types
enum {
IsAligned = false , PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess , BlockAccess = false , PreferBlockAccess = TensorEvaluator<ArgType, Device>::PreferBlockAccess ,
CoordAccess = false , RawAccess = false
}
typedef TensorVolumePatchOp< Planes, Rows, Cols, ArgType > XprType
typedef XprType::Index Index
typedef DSizes< Index, NumDims > Dimensions
typedef std::remove_const_t< typename XprType::Scalar > Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorBlockNotImplemented TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EvaluatorPointerType data () const
const TensorEvaluator< ArgType, Device > & impl () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index planePaddingTop () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rowPaddingTop () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index colPaddingLeft () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index outputPlanes () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index outputRows () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index outputCols () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index userPlaneStride () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index userRowStride () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index userColStride () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index userInPlaneStride () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index userInRowStride () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index userInColStride () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index planeInflateStride () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rowInflateStride () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index colInflateStride () const
Static Public Attributes
static constexpr int NumInputDims
static constexpr int NumDims = NumInputDims + 1
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Protected Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packetWithPossibleZero (Index index) const
Protected Attributes
Dimensions m_dimensions
Index m_plane_strides
Index m_row_strides
Index m_col_strides
Index m_outputPlanes
Index m_outputRows
Index m_outputCols
Index m_planePaddingTop
Index m_rowPaddingTop
Index m_colPaddingLeft
Index m_in_plane_strides
Index m_in_row_strides
Index m_in_col_strides
Index m_plane_inflate_strides
Index m_row_inflate_strides
Index m_col_inflate_strides
Index m_inputDepth
Index m_inputPlanes
Index m_inputRows
Index m_inputCols
Index m_outputPlanesRows
Index m_input_planes_eff
Index m_input_rows_eff
Index m_input_cols_eff
Index m_patch_planes_eff
Index m_patch_rows_eff
Index m_patch_cols_eff
Index m_otherStride
Index m_patchStride
Index m_rowStride
Index m_colStride
Index m_planeInputStride
Index m_rowInputStride
Index m_colInputStride
Index m_otherInputStride
internal::TensorIntDivisor< Index > m_fastOtherStride
internal::TensorIntDivisor< Index > m_fastPatchStride
internal::TensorIntDivisor< Index > m_fastColStride
internal::TensorIntDivisor< Index > m_fastRowStride
internal::TensorIntDivisor< Index > m_fastInputPlaneStride
internal::TensorIntDivisor< Index > m_fastInputRowStride
internal::TensorIntDivisor< Index > m_fastInputColStride
internal::TensorIntDivisor< Index > m_fastInputColsEff
internal::TensorIntDivisor< Index > m_fastOutputPlanesRows
internal::TensorIntDivisor< Index > m_fastOutputPlanes
internal::TensorIntDivisor< Index > m_fastOutputDepth
Scalar m_paddingValue
TensorEvaluator< ArgType, Device > m_impl
Member Typedef Documentation
CoeffReturnType
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::CoeffReturnType
Dimensions
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > typedef DSizes<Index, NumDims> Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::Dimensions
EvaluatorPointerType
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::EvaluatorPointerType
Index
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::Index
PacketReturnType
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::PacketReturnType
Scalar
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > typedef std::remove_const_t<typename XprType::Scalar> Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::Scalar
Storage
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::Storage
TensorBlock
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > typedef internal::TensorBlockNotImplemented Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::TensorBlock
XprType
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > typedef TensorVolumePatchOp<Planes, Rows, Cols, ArgType> Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = false,
     PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess,
     BlockAccess = false,
     PreferBlockAccess = TensorEvaluator<ArgType, Device>::PreferBlockAccess,
     CoordAccess = false,
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
                                                                                : m_impl(op.expression(), device) {
     EIGEN_STATIC_ASSERT((NumDims >= 5), YOU_MADE_A_PROGRAMMING_MISTAKE);
     m_paddingValue = op.padding_value();
     const typename TensorEvaluator<ArgType, Device>::Dimensions& input_dims = m_impl.dimensions();
     // Cache a few variables.
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       m_inputDepth = input_dims[0];
       m_inputPlanes = input_dims[1];
       m_inputRows = input_dims[2];
       m_inputCols = input_dims[3];
     } else {
       m_inputDepth = input_dims[NumInputDims - 1];
       m_inputPlanes = input_dims[NumInputDims - 2];
       m_inputRows = input_dims[NumInputDims - 3];
       m_inputCols = input_dims[NumInputDims - 4];
     }
     m_plane_strides = op.plane_strides();
     m_row_strides = op.row_strides();
     m_col_strides = op.col_strides();
     // Input strides and effective input/patch size
     m_in_plane_strides = op.in_plane_strides();
     m_in_row_strides = op.in_row_strides();
     m_in_col_strides = op.in_col_strides();
     m_plane_inflate_strides = op.plane_inflate_strides();
     m_row_inflate_strides = op.row_inflate_strides();
     m_col_inflate_strides = op.col_inflate_strides();
     // The "effective" spatial size after inflating data with zeros.
     m_input_planes_eff = (m_inputPlanes - 1) * m_plane_inflate_strides + 1;
     m_input_rows_eff = (m_inputRows - 1) * m_row_inflate_strides + 1;
     m_input_cols_eff = (m_inputCols - 1) * m_col_inflate_strides + 1;
     m_patch_planes_eff = op.patch_planes() + (op.patch_planes() - 1) * (m_in_plane_strides - 1);
     m_patch_rows_eff = op.patch_rows() + (op.patch_rows() - 1) * (m_in_row_strides - 1);
     m_patch_cols_eff = op.patch_cols() + (op.patch_cols() - 1) * (m_in_col_strides - 1);
     if (op.padding_explicit()) {
       m_outputPlanes =
           numext::ceil((m_input_planes_eff + op.padding_top_z() + op.padding_bottom_z() - m_patch_planes_eff + 1.f) /
                        static_cast<float>(m_plane_strides));
       m_outputRows = numext::ceil((m_input_rows_eff + op.padding_top() + op.padding_bottom() - m_patch_rows_eff + 1.f) /
                                   static_cast<float>(m_row_strides));
       m_outputCols = numext::ceil((m_input_cols_eff + op.padding_left() + op.padding_right() - m_patch_cols_eff + 1.f) /
                                   static_cast<float>(m_col_strides));
       m_planePaddingTop = op.padding_top_z();
       m_rowPaddingTop = op.padding_top();
       m_colPaddingLeft = op.padding_left();
     } else {
       // Computing padding from the type
       switch (op.padding_type()) {
         case PADDING_VALID:
           m_outputPlanes =
               numext::ceil((m_input_planes_eff - m_patch_planes_eff + 1.f) / static_cast<float>(m_plane_strides));
           m_outputRows = numext::ceil((m_input_rows_eff - m_patch_rows_eff + 1.f) / static_cast<float>(m_row_strides));
           m_outputCols = numext::ceil((m_input_cols_eff - m_patch_cols_eff + 1.f) / static_cast<float>(m_col_strides));
           m_planePaddingTop = 0;
           m_rowPaddingTop = 0;
           m_colPaddingLeft = 0;
           break;
         case PADDING_SAME: {
           m_outputPlanes = numext::ceil(m_input_planes_eff / static_cast<float>(m_plane_strides));
           m_outputRows = numext::ceil(m_input_rows_eff / static_cast<float>(m_row_strides));
           m_outputCols = numext::ceil(m_input_cols_eff / static_cast<float>(m_col_strides));
           const Index dz = (m_outputPlanes - 1) * m_plane_strides + m_patch_planes_eff - m_input_planes_eff;
           const Index dy = (m_outputRows - 1) * m_row_strides + m_patch_rows_eff - m_input_rows_eff;
           const Index dx = (m_outputCols - 1) * m_col_strides + m_patch_cols_eff - m_input_cols_eff;
           m_planePaddingTop = dz / 2;
           m_rowPaddingTop = dy / 2;
           m_colPaddingLeft = dx / 2;
           break;
         }
         default: {
           eigen_assert(false && "unexpected padding");
           return;
         }
       }
     }
     eigen_assert(m_outputRows > 0);
     eigen_assert(m_outputCols > 0);
     eigen_assert(m_outputPlanes > 0);
     // Dimensions for result of extraction.
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       // ColMajor
       // 0: depth
       // 1: patch_planes
       // 2: patch_rows
       // 3: patch_cols
       // 4: number of patches
       // 5 and beyond: anything else (such as batch).
       m_dimensions[0] = input_dims[0];
       m_dimensions[1] = op.patch_planes();
       m_dimensions[2] = op.patch_rows();
       m_dimensions[3] = op.patch_cols();
       m_dimensions[4] = m_outputPlanes * m_outputRows * m_outputCols;
       for (int i = 5; i < NumDims; ++i) {
         m_dimensions[i] = input_dims[i - 1];
       }
     } else {
       // RowMajor
       // NumDims-1: depth
       // NumDims-2: patch_planes
       // NumDims-3: patch_rows
       // NumDims-4: patch_cols
       // NumDims-5: number of patches
       // NumDims-6 and beyond: anything else (such as batch).
       m_dimensions[NumDims - 1] = input_dims[NumInputDims - 1];
       m_dimensions[NumDims - 2] = op.patch_planes();
       m_dimensions[NumDims - 3] = op.patch_rows();
       m_dimensions[NumDims - 4] = op.patch_cols();
       m_dimensions[NumDims - 5] = m_outputPlanes * m_outputRows * m_outputCols;
       for (int i = NumDims - 6; i >= 0; --i) {
         m_dimensions[i] = input_dims[i];
       }
     }
     // Strides for the output tensor.
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       m_rowStride = m_dimensions[1];
       m_colStride = m_dimensions[2] * m_rowStride;
       m_patchStride = m_colStride * m_dimensions[3] * m_dimensions[0];
       m_otherStride = m_patchStride * m_dimensions[4];
     } else {
       m_rowStride = m_dimensions[NumDims - 2];
       m_colStride = m_dimensions[NumDims - 3] * m_rowStride;
       m_patchStride = m_colStride * m_dimensions[NumDims - 4] * m_dimensions[NumDims - 1];
       m_otherStride = m_patchStride * m_dimensions[NumDims - 5];
     }
     // Strides for navigating through the input tensor.
     m_planeInputStride = m_inputDepth;
     m_rowInputStride = m_inputDepth * m_inputPlanes;
     m_colInputStride = m_inputDepth * m_inputRows * m_inputPlanes;
     m_otherInputStride = m_inputDepth * m_inputRows * m_inputCols * m_inputPlanes;
     m_outputPlanesRows = m_outputPlanes * m_outputRows;
     // Fast representations of different variables.
     m_fastOtherStride = internal::TensorIntDivisor<Index>(m_otherStride);
     m_fastPatchStride = internal::TensorIntDivisor<Index>(m_patchStride);
     m_fastColStride = internal::TensorIntDivisor<Index>(m_colStride);
     m_fastRowStride = internal::TensorIntDivisor<Index>(m_rowStride);
     m_fastInputRowStride = internal::TensorIntDivisor<Index>(m_row_inflate_strides);
     m_fastInputColStride = internal::TensorIntDivisor<Index>(m_col_inflate_strides);
     m_fastInputPlaneStride = internal::TensorIntDivisor<Index>(m_plane_inflate_strides);
     m_fastInputColsEff = internal::TensorIntDivisor<Index>(m_input_cols_eff);
     m_fastOutputPlanes = internal::TensorIntDivisor<Index>(m_outputPlanes);
     m_fastOutputPlanesRows = internal::TensorIntDivisor<Index>(m_outputPlanesRows);
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       m_fastOutputDepth = internal::TensorIntDivisor<Index>(m_dimensions[0]);
     } else {
       m_fastOutputDepth = internal::TensorIntDivisor<Index>(m_dimensions[NumDims - 1]);
     }
   }
References Eigen::numext::ceil(), Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), eigen_assert, EIGEN_STATIC_ASSERT, i, Eigen::TensorEvaluator< Derived, Device >::Layout, op, Eigen::PADDING_SAME, and Eigen::PADDING_VALID.
Member Function Documentation
cleanup()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::cleanup () inline
 { m_impl.cleanup(); }
Referenced by framework.Frame::__init__().
coeff()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::coeff (Index index) const inline
{
     // Patch index corresponding to the passed in index.
     const Index patchIndex = index / m_fastPatchStride;
     // Spatial offset within the patch. This has to be translated into 3D
     // coordinates within the patch.
     const Index patchOffset = (index - patchIndex * m_patchStride) / m_fastOutputDepth;
     // Batch, etc.
     const Index otherIndex = (NumDims == 5) ? 0 : index / m_fastOtherStride;
     const Index patch3DIndex = (NumDims == 5) ? patchIndex : (index - otherIndex * m_otherStride) / m_fastPatchStride;
     // Calculate column index in the input original tensor.
     const Index colIndex = patch3DIndex / m_fastOutputPlanesRows;
     const Index colOffset = patchOffset / m_fastColStride;
     const Index inputCol = colIndex * m_col_strides + colOffset * m_in_col_strides - m_colPaddingLeft;
     const Index origInputCol =
         (m_col_inflate_strides == 1) ? inputCol : ((inputCol >= 0) ? (inputCol / m_fastInputColStride) : 0);
     if (inputCol < 0 || inputCol >= m_input_cols_eff ||
         ((m_col_inflate_strides != 1) && (inputCol != origInputCol * m_col_inflate_strides))) {
       return Scalar(m_paddingValue);
     }
     // Calculate row index in the original input tensor.
     const Index rowIndex = (patch3DIndex - colIndex * m_outputPlanesRows) / m_fastOutputPlanes;
     const Index rowOffset = (patchOffset - colOffset * m_colStride) / m_fastRowStride;
     const Index inputRow = rowIndex * m_row_strides + rowOffset * m_in_row_strides - m_rowPaddingTop;
     const Index origInputRow =
         (m_row_inflate_strides == 1) ? inputRow : ((inputRow >= 0) ? (inputRow / m_fastInputRowStride) : 0);
     if (inputRow < 0 || inputRow >= m_input_rows_eff ||
         ((m_row_inflate_strides != 1) && (inputRow != origInputRow * m_row_inflate_strides))) {
       return Scalar(m_paddingValue);
     }
     // Calculate plane index in the original input tensor.
     const Index planeIndex = (patch3DIndex - m_outputPlanes * (colIndex * m_outputRows + rowIndex));
     const Index planeOffset = patchOffset - colOffset * m_colStride - rowOffset * m_rowStride;
     const Index inputPlane = planeIndex * m_plane_strides + planeOffset * m_in_plane_strides - m_planePaddingTop;
     const Index origInputPlane =
         (m_plane_inflate_strides == 1) ? inputPlane : ((inputPlane >= 0) ? (inputPlane / m_fastInputPlaneStride) : 0);
     if (inputPlane < 0 || inputPlane >= m_input_planes_eff ||
         ((m_plane_inflate_strides != 1) && (inputPlane != origInputPlane * m_plane_inflate_strides))) {
       return Scalar(m_paddingValue);
     }
     const int depth_index = static_cast<int>(Layout) == static_cast<int>(ColMajor) ? 0 : NumDims - 1;
     const Index depth = index - (index / m_fastOutputDepth) * m_dimensions[depth_index];
     const Index inputIndex = depth + origInputRow * m_rowInputStride + origInputCol * m_colInputStride +
                              origInputPlane * m_planeInputStride + otherIndex * m_otherInputStride;
     return m_impl.coeff(inputIndex);
   }
References Eigen::ColMajor, and Eigen::TensorEvaluator< Derived, Device >::Layout.
colInflateStride()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::colInflateStride () const inline
 { return m_col_inflate_strides; }
colPaddingLeft()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::colPaddingLeft () const inline
 { return m_colPaddingLeft; }
costPerCoeff()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     const double compute_cost =
         10 * TensorOpCost::DivCost<Index>() + 21 * TensorOpCost::MulCost<Index>() + 8 * TensorOpCost::AddCost<Index>();
     return TensorOpCost(0, 0, compute_cost, vectorized, PacketSize);
   }
References Eigen::TensorEvaluator< Derived, Device >::PacketSize.
data()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EvaluatorPointerType Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::dimensions () const inline
 { return m_dimensions; }
evalSubExprsIfNeeded()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
{
     m_impl.evalSubExprsIfNeeded(NULL);
     return true;
   }
impl()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > const TensorEvaluator<ArgType, Device>& Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::impl () const inline
 { return m_impl; }
outputCols()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::outputCols () const inline
 { return m_outputCols; }
outputPlanes()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::outputPlanes () const inline
 { return m_outputPlanes; }
outputRows()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::outputRows () const inline
 { return m_outputRows; }
packet()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::packet (Index index) const inline
{
     eigen_assert(index + PacketSize - 1 < dimensions().TotalSize());
     if (m_in_row_strides != 1 || m_in_col_strides != 1 || m_row_inflate_strides != 1 || m_col_inflate_strides != 1 ||
         m_in_plane_strides != 1 || m_plane_inflate_strides != 1) {
       return packetWithPossibleZero(index);
     }
     const Index indices[2] = {index, index + PacketSize - 1};
     const Index patchIndex = indices[0] / m_fastPatchStride;
     if (patchIndex != indices[1] / m_fastPatchStride) {
       return packetWithPossibleZero(index);
     }
     const Index otherIndex = (NumDims == 5) ? 0 : indices[0] / m_fastOtherStride;
     eigen_assert(otherIndex == indices[1] / m_fastOtherStride);
     // Find the offset of the element wrt the location of the first element.
     const Index patchOffsets[2] = {(indices[0] - patchIndex * m_patchStride) / m_fastOutputDepth,
                                    (indices[1] - patchIndex * m_patchStride) / m_fastOutputDepth};
     const Index patch3DIndex =
         (NumDims == 5) ? patchIndex : (indices[0] - otherIndex * m_otherStride) / m_fastPatchStride;
     eigen_assert(patch3DIndex == (indices[1] - otherIndex * m_otherStride) / m_fastPatchStride);
     const Index colIndex = patch3DIndex / m_fastOutputPlanesRows;
     const Index colOffsets[2] = {patchOffsets[0] / m_fastColStride, patchOffsets[1] / m_fastColStride};
     // Calculate col indices in the original input tensor.
     const Index inputCols[2] = {colIndex * m_col_strides + colOffsets[0] - m_colPaddingLeft,
                                 colIndex * m_col_strides + colOffsets[1] - m_colPaddingLeft};
     if (inputCols[1] < 0 || inputCols[0] >= m_inputCols) {
       return internal::pset1<PacketReturnType>(Scalar(m_paddingValue));
     }
     if (inputCols[0] != inputCols[1]) {
       return packetWithPossibleZero(index);
     }
     const Index rowIndex = (patch3DIndex - colIndex * m_outputPlanesRows) / m_fastOutputPlanes;
     const Index rowOffsets[2] = {(patchOffsets[0] - colOffsets[0] * m_colStride) / m_fastRowStride,
                                  (patchOffsets[1] - colOffsets[1] * m_colStride) / m_fastRowStride};
     eigen_assert(rowOffsets[0] <= rowOffsets[1]);
     // Calculate col indices in the original input tensor.
     const Index inputRows[2] = {rowIndex * m_row_strides + rowOffsets[0] - m_rowPaddingTop,
                                 rowIndex * m_row_strides + rowOffsets[1] - m_rowPaddingTop};
     if (inputRows[1] < 0 || inputRows[0] >= m_inputRows) {
       return internal::pset1<PacketReturnType>(Scalar(m_paddingValue));
     }
     if (inputRows[0] != inputRows[1]) {
       return packetWithPossibleZero(index);
     }
     const Index planeIndex = (patch3DIndex - m_outputPlanes * (colIndex * m_outputRows + rowIndex));
     const Index planeOffsets[2] = {patchOffsets[0] - colOffsets[0] * m_colStride - rowOffsets[0] * m_rowStride,
                                    patchOffsets[1] - colOffsets[1] * m_colStride - rowOffsets[1] * m_rowStride};
     eigen_assert(planeOffsets[0] <= planeOffsets[1]);
     const Index inputPlanes[2] = {planeIndex * m_plane_strides + planeOffsets[0] - m_planePaddingTop,
                                   planeIndex * m_plane_strides + planeOffsets[1] - m_planePaddingTop};
     if (inputPlanes[1] < 0 || inputPlanes[0] >= m_inputPlanes) {
       return internal::pset1<PacketReturnType>(Scalar(m_paddingValue));
     }
     if (inputPlanes[0] >= 0 && inputPlanes[1] < m_inputPlanes) {
       // no padding
       const int depth_index = static_cast<int>(Layout) == static_cast<int>(ColMajor) ? 0 : NumDims - 1;
       const Index depth = index - (index / m_fastOutputDepth) * m_dimensions[depth_index];
       const Index inputIndex = depth + inputRows[0] * m_rowInputStride + inputCols[0] * m_colInputStride +
                                m_planeInputStride * inputPlanes[0] + otherIndex * m_otherInputStride;
       return m_impl.template packet<Unaligned>(inputIndex);
     }
     return packetWithPossibleZero(index);
   }
References Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), eigen_assert, Eigen::TensorEvaluator< Derived, Device >::Layout, and Eigen::TensorEvaluator< Derived, Device >::PacketSize.
packetWithPossibleZero()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::packetWithPossibleZero (Index index) const inline protected
{
     EIGEN_ALIGN_MAX std::remove_const_t<CoeffReturnType> values[PacketSize];
     EIGEN_UNROLL_LOOP
     for (int i = 0; i < PacketSize; ++i) {
       values[i] = coeff(index + i);
     }
     PacketReturnType rslt = internal::pload<PacketReturnType>(values);
     return rslt;
   }
References Eigen::TensorEvaluator< Derived, Device >::coeff(), EIGEN_ALIGN_MAX, EIGEN_UNROLL_LOOP, i, and Eigen::TensorEvaluator< Derived, Device >::PacketSize.
planeInflateStride()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::planeInflateStride () const inline
 { return m_plane_inflate_strides; }
planePaddingTop()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::planePaddingTop () const inline
 { return m_planePaddingTop; }
rowInflateStride()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::rowInflateStride () const inline
 { return m_row_inflate_strides; }
rowPaddingTop()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::rowPaddingTop () const inline
 { return m_rowPaddingTop; }
userColStride()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::userColStride () const inline
 { return m_col_strides; }
userInColStride()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::userInColStride () const inline
 { return m_in_col_strides; }
userInPlaneStride()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::userInPlaneStride () const inline
 { return m_in_plane_strides; }
userInRowStride()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::userInRowStride () const inline
 { return m_in_row_strides; }
userPlaneStride()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::userPlaneStride () const inline
 { return m_plane_strides; }
userRowStride()
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::userRowStride () const inline
 { return m_row_strides; }
Member Data Documentation
Layout
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_col_inflate_strides
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_col_inflate_strides protected
m_col_strides
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_col_strides protected
m_colInputStride
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_colInputStride protected
m_colPaddingLeft
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_colPaddingLeft protected
m_colStride
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_colStride protected
m_dimensions
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Dimensions Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_dimensions protected
m_fastColStride
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_fastColStride protected
m_fastInputColsEff
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_fastInputColsEff protected
m_fastInputColStride
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_fastInputColStride protected
m_fastInputPlaneStride
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_fastInputPlaneStride protected
m_fastInputRowStride
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_fastInputRowStride protected
m_fastOtherStride
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_fastOtherStride protected
m_fastOutputDepth
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_fastOutputDepth protected
m_fastOutputPlanes
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_fastOutputPlanes protected
m_fastOutputPlanesRows
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_fastOutputPlanesRows protected
m_fastPatchStride
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_fastPatchStride protected
m_fastRowStride
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_fastRowStride protected
m_impl
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_impl protected
m_in_col_strides
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_in_col_strides protected
m_in_plane_strides
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_in_plane_strides protected
m_in_row_strides
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_in_row_strides protected
m_input_cols_eff
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_input_cols_eff protected
m_input_planes_eff
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_input_planes_eff protected
m_input_rows_eff
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_input_rows_eff protected
m_inputCols
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_inputCols protected
m_inputDepth
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_inputDepth protected
m_inputPlanes
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_inputPlanes protected
m_inputRows
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_inputRows protected
m_otherInputStride
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_otherInputStride protected
m_otherStride
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_otherStride protected
m_outputCols
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_outputCols protected
m_outputPlanes
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_outputPlanes protected
m_outputPlanesRows
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_outputPlanesRows protected
m_outputRows
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_outputRows protected
m_paddingValue
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Scalar Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_paddingValue protected
m_patch_cols_eff
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_patch_cols_eff protected
m_patch_planes_eff
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_patch_planes_eff protected
m_patch_rows_eff
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_patch_rows_eff protected
m_patchStride
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_patchStride protected
m_plane_inflate_strides
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_plane_inflate_strides protected
m_plane_strides
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_plane_strides protected
m_planeInputStride
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_planeInputStride protected
m_planePaddingTop
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_planePaddingTop protected
m_row_inflate_strides
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_row_inflate_strides protected
m_row_strides
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_row_strides protected
m_rowInputStride
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_rowInputStride protected
m_rowPaddingTop
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_rowPaddingTop protected
m_rowStride
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::m_rowStride protected
NumDims
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::NumDims = NumInputDims + 1 static constexpr
NumInputDims
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::NumInputDims static constexpr
Initial value:
=
      internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value
PacketSize
template<DenseIndex Planes, DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorVolumePatch.h