MercuryDPM: turek_flag.cc File Reference
interaction/turek_flag/turek_flag.cc File Reference
#include "generic.h"
#include "solid.h"
#include "navier_stokes.h"
#include "multi_physics.h"
#include "meshes/cylinder_with_flag_mesh.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >
Problem class.
Namespaces
Global_Parameters
Namespace for global parameters.
Functions
void Global_Parameters::gravity (const double &time, const Vector< double > &xi, Vector< double > &b)
Non-dimensional gravity as body force.
double Global_Parameters::flux (const double &t)
Flux: Pulsatile flow.
void Global_Parameters::set_parameters (const string &case_id)
Set parameters for the various test cases.
int main (int argc, char *argv[])
Driver.
Variables
string Global_Parameters::Case_ID ="FSI1"
Default case ID.
double Global_Parameters::St =0.5
Strouhal number (default assignment for FSI1 test case)
double Global_Parameters::Centre_x =2.0
x position of centre of cylinder
double Global_Parameters::Centre_y =2.0
y position of centre of cylinder
double Global_Parameters::Radius =0.5
Radius of cylinder.
ConstitutiveLaw * Global_Parameters::Constitutive_law_pt =0
Pointer to constitutive law.
bool Global_Parameters::Ignore_fluid_loading =false
Ignore fluid (default assignment for FSI1 test case)
double Global_Parameters::Gravity =0.0
Non-dim gravity (default assignment for FSI1 test case)
double Global_Parameters::Ramp_period =2.0
Period for ramping up in flux.
double Global_Parameters::Min_flux =0.0
Min. flux.
double Global_Parameters::Max_flux =1.0
Max. flux.
Function Documentation
main()
int main (int argc , char * argv[])
Driver.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Get case id as string
  string case_id="FSI1";
  if (CommandLineArgs::Argc==1)
   {
    oomph_info << "No command line arguments; running self-test FSI1"
               << std::endl;
   }
  else if (CommandLineArgs::Argc==2)
   {
    case_id=CommandLineArgs::Argv[1];
   }
  else
   {
    oomph_info << "Wrong number of command line arguments" << std::endl;
    oomph_info << "Enter none (for default) or one (namely the case id"
               << std::endl;
    oomph_info << "which should be one of: FSI1, FSI2, FSI3, CSM1"
               << std::endl;
   }
  std::cout << "Running case " << case_id << std::endl;
  // Setup parameters for case identified by command line
  // argument
  Global_Parameters::set_parameters(case_id);
  // Prepare output
  DocInfo doc_info;
  ofstream trace_file;
  doc_info.set_directory("RESLT");
  trace_file.open("RESLT/trace.dat");
  // Length and height of domain
  double length=25.0;
  double height=4.1;
  //Set up the problem
  TurekProblem<AlgebraicElement<RefineableQTaylorHoodElement<2> >,
   RefineableQPVDElement<2,3> > problem(length, height);
  // Default number of timesteps
  unsigned nstep=4000;
  if (Global_Parameters::Case_ID=="FSI1")
   {
    std::cout << "Reducing number of steps for FSI1 " << std::endl;
    nstep=400;
   }
  if (CommandLineArgs::Argc==1)
   {
    std::cout << "Reducing number of steps for validation " << std::endl;
    nstep=2;
   }
  //Timestep:
  double dt=Global_Parameters::Dt;
  // Initialise timestep
  problem.initialise_dt(dt);
  // Impulsive start
  problem.assign_initial_values_impulsive(dt);
  // Doc the initial condition
  problem.doc_solution(doc_info,trace_file);
  doc_info.number()++;
  // Don't re-set the initial conditions when adapting during first
  // timestep
  bool first = false;
  // Max number of adaptation for time-stepping
  unsigned max_adapt=1;
  for(unsigned i=0;i<nstep;i++)
   {
   // Solve the problem
   problem.unsteady_newton_solve(dt,max_adapt,first);
   // Output the solution
   problem.doc_solution(doc_info,trace_file);
   // Step number
   doc_info.number()++;
  }
  trace_file.close();
 }//end of main
References oomph::CommandLineArgs::Argc, oomph::CommandLineArgs::Argv, Global_Parameters::Case_ID, Global_Parameters::Dt, Global_Physical_Variables::height(), i, oomph::DocInfo::number(), oomph::oomph_info, problem, oomph::DocInfo::set_directory(), Global_Parameters::set_parameters(), and Flag_definition::setup().