MercuryDPM: Eigen::internal::redux_impl< Func, Evaluator, LinearVectorizedTraversal, NoUnrolling > Struct Template Reference
Eigen::internal::redux_impl< Func, Evaluator, LinearVectorizedTraversal, NoUnrolling > Struct Template Reference
#include <Redux.h>
Public Types
typedef Evaluator::Scalar Scalar
typedef redux_traits< Func, Evaluator >::PacketType PacketScalar
Static Public Member Functions
template<typename XprType >
static Scalar run (const Evaluator &eval, const Func &func, const XprType &xpr)
Member Typedef Documentation
PacketScalar
template<typename Func , typename Evaluator > typedef redux_traits<Func, Evaluator>::PacketType Eigen::internal::redux_impl< Func, Evaluator, LinearVectorizedTraversal, NoUnrolling >::PacketScalar
Scalar
template<typename Func , typename Evaluator > typedef Evaluator::Scalar Eigen::internal::redux_impl< Func, Evaluator, LinearVectorizedTraversal, NoUnrolling >::Scalar
Member Function Documentation
run()
template<typename Func , typename Evaluator > template<typename XprType > static Scalar Eigen::internal::redux_impl< Func, Evaluator, LinearVectorizedTraversal, NoUnrolling >::run (const Evaluator & eval, const Func & func, const XprType & xpr) inline static
{
     const Index size = xpr.size();
     constexpr Index packetSize = redux_traits<Func, Evaluator>::PacketSize;
     constexpr int packetAlignment = unpacket_traits<PacketScalar>::alignment;
     constexpr int alignment0 =
         (bool(Evaluator::Flags & DirectAccessBit) && bool(packet_traits<Scalar>::AlignedOnScalar))
             ? int(packetAlignment)
             : int(Unaligned);
     constexpr int alignment = plain_enum_max(alignment0, Evaluator::Alignment);
     const Index alignedStart = internal::first_default_aligned(xpr);
     const Index alignedSize2 = ((size - alignedStart) / (2 * packetSize)) * (2 * packetSize);
     const Index alignedSize = ((size - alignedStart) / (packetSize)) * (packetSize);
     const Index alignedEnd2 = alignedStart + alignedSize2;
     const Index alignedEnd = alignedStart + alignedSize;
     Scalar res;
     if (alignedSize) {
       PacketScalar packet_res0 = eval.template packet<alignment, PacketScalar>(alignedStart);
       if (alignedSize > packetSize)  // we have at least two packets to partly unroll the loop
       {
         PacketScalar packet_res1 = eval.template packet<alignment, PacketScalar>(alignedStart + packetSize);
         for (Index index = alignedStart + 2 * packetSize; index < alignedEnd2; index += 2 * packetSize) {
           packet_res0 = func.packetOp(packet_res0, eval.template packet<alignment, PacketScalar>(index));
           packet_res1 = func.packetOp(packet_res1, eval.template packet<alignment, PacketScalar>(index + packetSize));
         }
         packet_res0 = func.packetOp(packet_res0, packet_res1);
         if (alignedEnd > alignedEnd2)
           packet_res0 = func.packetOp(packet_res0, eval.template packet<alignment, PacketScalar>(alignedEnd2));
       }
       res = func.predux(packet_res0);
       for (Index index = 0; index < alignedStart; ++index) res = func(res, eval.coeff(index));
       for (Index index = alignedEnd; index < size; ++index) res = func(res, eval.coeff(index));
     } else  // too small to vectorize anything.
             // since this is dynamic-size hence inefficient anyway for such small sizes, don't try to optimize.
     {
       res = eval.coeff(0);
       for (Index index = 1; index < size; ++index) res = func(res, eval.coeff(index));
     }
     return res;
   }
References Eigen::DirectAccessBit, Eigen::internal::first_default_aligned(), int(), Eigen::internal::plain_enum_max(), res, size, and Eigen::Unaligned.
The documentation for this struct was generated from the following file:
Redux.h