MercuryDPM: CircularPeriodicBoundary Class Reference
CircularPeriodicBoundary Class Reference
used to create a circular periodic boundary
#include <CircularPeriodicBoundary.h>
Public Member Functions
CircularPeriodicBoundary ()
default constructor
CircularPeriodicBoundary (double innerRadius)
Constructor.
~CircularPeriodicBoundary () override
destructor
CircularPeriodicBoundary * copy () const override
Used to create a copy of the object NB: purely virtual function.
void rotateParticle (BaseParticle *P, double angle)
void createPeriodicParticle (BaseParticle *p, ParticleHandler &pH) override
void createPeriodicParticles (ParticleHandler &pH) override
bool checkBoundaryAfterParticleMoved (BaseParticle *P, ParticleHandler &pH)
void checkBoundaryAfterParticlesMove (ParticleHandler &pH) override
void read (std::istream &is) override
reads the CircularPeriodicBoundary
void oldRead (std::istream &is)
void write (std::ostream &os) const override
outputs the CircularPeriodicBoundary
std::string getName () const override
Returns the name of the object.
Public Member Functions inherited from BaseBoundary
BaseBoundary ()
default constructor.
BaseBoundary (const BaseBoundary &b)
copy constructor
~BaseBoundary () override
destructor
virtual void createPeriodicParticle (BaseParticle *p UNUSED, ParticleHandler &pH UNUSED)
Creates a periodic particle in case of periodic boundaries in serial build.
virtual void createPeriodicParticles (ParticleHandler &pH UNUSED)
Creates periodic copies of given particle in case of periodic boundaries.
virtual void checkBoundaryBeforeTimeStep (DPMBase *md)
Virtual function that does things before each time step.
virtual void actionsBeforeTimeLoop ()
Virtual function that does something after DPMBase::setupInitialConditions but before the first time step.
virtual void modifyGhostAfterCreation (BaseParticle *particle, int i)
virtual void writeVTK (std::fstream &file)
void setHandler (BoundaryHandler *handler)
Sets the boundary's BoundaryHandler.
BoundaryHandler * getHandler () const
Returns the boundary's BoundaryHandler.
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
double innerRadius_
Detailed Description
used to create a circular periodic boundary
Constructor & Destructor Documentation
CircularPeriodicBoundary() [1/2]
CircularPeriodicBoundary::CircularPeriodicBoundary ()
default constructor
         : BaseBoundary()
 {
     innerRadius_ = 1.0;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout << "CircularPeriodicBoundary::CircularPeriodicBoundary() finished" << std::endl;
 #endif
 #ifdef MERCURYDPM_USE_MPI
     MPIContainer& communicator = MPIContainer::Instance();
     if (communicator.getNumberOfProcessors() > 1)
     {
         logger(WARN,"CircularPeriodicBoundaries are currently not implemented in parallel MercuryDPM");
     }
 #endif
 }
References MPIContainer::getNumberOfProcessors(), innerRadius_, MPIContainer::Instance(), logger, and WARN.
Referenced by copy().
CircularPeriodicBoundary() [2/2]
CircularPeriodicBoundary::CircularPeriodicBoundary (double innerRadius) explicit
Constructor.
         : BaseBoundary()
 {
     this->innerRadius_ = innerRadius;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout << "CircularPeriodicBoundary::CircularPeriodicBoundary(double innerRadius) finished" << std::endl;
 #endif
 }
References innerRadius_.
~CircularPeriodicBoundary()
CircularPeriodicBoundary::~CircularPeriodicBoundary () override
destructor
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cerr << "CircularPeriodicBoundary::~CircularPeriodicBoundary() finished" << std::endl;
 #endif
 }
Member Function Documentation
checkBoundaryAfterParticleMoved()
bool CircularPeriodicBoundary::checkBoundaryAfterParticleMoved (BaseParticle * P, ParticleHandler & pH)
Todo:
TW: Dinant, please confirm that i and oldI should be integer
 {
     double R = sqrt(pow(P->getPosition().X, 2) + pow(P->getPosition().Y, 2));
     double alpha = atan2(P->getPosition().Y, P->getPosition().X);
     int i = static_cast<int>(std::floor(std::log(R / innerRadius_) / std::log(2.0))) + 1;
     double pieSize = 2.0 / pow(2.0, i) * constants::pi;
     double oldR = sqrt(
             pow(P->getPreviousPosition().X, 2) + pow(P->getPreviousPosition().Y, 2));
     int oldI = static_cast<int>(std::floor(std::log(oldR / innerRadius_) / std::log(2.0))) + 1;
     if (i > 0 && i > oldI) //Particle moves outward so it may have to be deleted
     {
         //std::cout<<"Particle="<<P->getIndex()<<" moving outward with alpha="<<alpha<<" and pieSize="<<pieSize<<" ";
         if (alpha < 0 || alpha > pieSize)
         {
             if (alpha > 2.0 * pieSize)
             {
                 //std::cout<<"and it is rotated into the pie"<<std::endl;
                 rotateParticle(P, -pieSize);
             }
             else
             {
                 //Delete particle
                 //std::cout<<"and it should be deleted"<<std::endl;
                 pH.removeObject(P->getIndex());
                 return true;
             }
         }
         //else
         //std::cout<<"and nothing happens"<<std::endl;
     }
     else if (i >= 0 && i < oldI) //Particle moves inward so it has to be copied
     {
         //std::cout<<"Particle="<<P->getIndex()<<" moving inward and is thus coppied with alpha="<<alpha<<" and pieSize="<<pieSize<<std::endl;
         //std::cout<<"i="<<i<<" oldI="<<oldI<<" R="<<R<<" oldR="<<oldR<<std::endl;
         //std::cout<<"Position="<<P->getPosition()<<" Displacement="<<P->get_Displacement()<<std::endl;
         BaseParticle* F0 = P->copy();
         F0->setPreviousPosition(F0->getPosition());
         if (alpha < 0)
         {
             rotateParticle(P, pieSize);
             rotateParticle(F0, 0.5 * pieSize);
         }
         else if (alpha < 0.5 * pieSize)
         {
             rotateParticle(F0, 0.5 * pieSize);
         }
         else if (alpha < pieSize)
         {
             rotateParticle(F0, -0.5 * pieSize);
         }
         else
         {
             rotateParticle(P, -pieSize);
             rotateParticle(F0, -0.5 * pieSize);
         }
         pH.addObject(F0);
     }
     else if (i > 0 && alpha < 0)
     {
         //std::cout<<"Particle="<<P->getIndex()<<" i="<<i<<" R="<<R<<" alpha="<<alpha<<" positive rotated pieSize="<<pieSize<<std::endl;
         rotateParticle(P, pieSize);
     }
     else if (i > 0 && alpha > pieSize)
     {
         //std::cout<<"Particle="<<P->getIndex()<<" i="<<i<<" R="<<R<<" alpha="<<alpha<<" negative rotated pieSize="<<pieSize<<std::endl;
         rotateParticle(P, -pieSize);
     }
     return false;
 }
References ParticleHandler::addObject(), alpha, atan2(), Eigen::bfloat16_impl::floor(), BaseInteractable::getPosition(), i, innerRadius_, Eigen::bfloat16_impl::log(), Global_Physical_Variables::P, constants::pi, Eigen::bfloat16_impl::pow(), R, ParticleHandler::removeObject(), rotateParticle(), BaseParticle::setPreviousPosition(), and sqrt().
Referenced by checkBoundaryAfterParticlesMove().
checkBoundaryAfterParticlesMove()
void CircularPeriodicBoundary::checkBoundaryAfterParticlesMove (ParticleHandler & pH) override virtual
Todo:
MX: When implementing this function, I realised there might not be a unit test for this boundary
Reimplemented from BaseBoundary.
 {
     for (auto p = pH.begin(); p != pH.end(); ++p)
     {
         if (checkBoundaryAfterParticleMoved(*p, pH))
         {
             p--;
         }
     }
 }
References BaseHandler< T >::begin(), checkBoundaryAfterParticleMoved(), BaseHandler< T >::end(), and p.
copy()
CircularPeriodicBoundary * CircularPeriodicBoundary::copy () const override virtual
Used to create a copy of the object NB: purely virtual function.
Implements BaseBoundary.
 {
 #ifdef DEBUG_CONSTRUCTOR
     std::cerr << "CircularPeriodicBoundary::copy() const finished" << std::endl;
 #endif
     return new CircularPeriodicBoundary(*this);
 }
References CircularPeriodicBoundary().
createPeriodicParticle()
void CircularPeriodicBoundary::createPeriodicParticle (BaseParticle * p, ParticleHandler & pH) override
Parameters
[in]
Todo:
TW getLargestParticle()->getInteractionRadius() should be getLargestInteractionRadius()
 {
     double R = sqrt(pow(p->getPosition().X, 2) + pow(p->getPosition().Y, 2));
     double alpha = atan2(p->getPosition().Y, p->getPosition().X);
     unsigned int i = static_cast<unsigned int>(std::floor(std::log(R / innerRadius_) / std::log(2.0))) + 1;
     double pieSize = 2.0 / pow(2.0, i) * constants::pi;
     //std::cout<<"R="<<R<<" alpha="<<alpha<<" i="<<i<<" pieSize="<<pieSize<<std::endl;
     //Check if the particle is close to it's inner Radius or is is close to zero alpha (small y)
     const Mdouble maxDistance = p->getMaxInteractionRadius() + pH.getLargestParticle()->getMaxInteractionRadius();
     if (i > 0 && (R - maxDistance <
                   pow(2.0, i - 1) * innerRadius_ ||
                   p->getPosition().Y < maxDistance))
     {
         //std::cout<<"Going to shift because "<<R-P->getRadius()<<"<"<<pow(2,i-1)*innerRadius<<" or "<<P->getPosition().Y<<"<"<<P->getRadius()<<std::endl;
         //std::cout<<*P<<" has been shifted"<<std::endl;
         BaseParticle* F0 = p->copy();
         rotateParticle(F0, pieSize);
         //If Particle is Mdouble shifted, get correct original particle
         BaseParticle* From = p;
         while (From->getPeriodicFromParticle() != nullptr)
             From = From->getPeriodicFromParticle();
         F0->setPeriodicFromParticle(From);
         //std::cout<<*F0<<" is the result"<<std::endl;
         pH.addObject(F0);
     }
     //Check here only for i>0 becuase for i=1 they both give the same particle
     if (i > 1 && R * R * (1 - pow(cos(alpha - pieSize), 2)) < maxDistance)
     {
         //std::cout<<*P<<" has been shifted back"<<std::endl;
         BaseParticle* F0 = p->copy();
         rotateParticle(F0, -pieSize);
         //If Particle is Mdouble shifted, get correct original particle
         BaseParticle* From = p;
         while (From->getPeriodicFromParticle() != nullptr)
             From = From->getPeriodicFromParticle();
         F0->setPeriodicFromParticle(From);
         //std::cout<<*F0<<" is the result"<<std::endl;
         pH.addObject(F0);
     }
 }
References ParticleHandler::addObject(), alpha, atan2(), cos(), Eigen::bfloat16_impl::floor(), ParticleHandler::getLargestParticle(), BaseParticle::getMaxInteractionRadius(), BaseParticle::getPeriodicFromParticle(), i, innerRadius_, Eigen::bfloat16_impl::log(), p, constants::pi, Eigen::bfloat16_impl::pow(), R, rotateParticle(), BaseParticle::setPeriodicFromParticle(), and sqrt().
Referenced by createPeriodicParticles().
createPeriodicParticles()
void CircularPeriodicBoundary::createPeriodicParticles (ParticleHandler & pH) override
 {
     unsigned numberOfParticles = pH.getSize();
     for (unsigned i = 0; i < numberOfParticles; i++)
     {
         createPeriodicParticle(pH.getObject(i), pH);
     }
 }
References createPeriodicParticle(), BaseHandler< T >::getObject(), BaseHandler< T >::getSize(), and i.
getName()
std::string CircularPeriodicBoundary::getName () const override virtual
Returns the name of the object.
Returns
string type
Implements BaseObject.
 {
     return "CircularPeriodicBoundary";
 }
oldRead()
void CircularPeriodicBoundary::oldRead (std::istream & is)
 {
     std::string dummy;
     is >> dummy >> innerRadius_;
 }
References innerRadius_, and oomph::Global_string_for_annotation::string().
read()
void CircularPeriodicBoundary::read (std::istream & is) override virtual
reads the CircularPeriodicBoundary
Implements BaseBoundary.
 {
     BaseBoundary::read(is);
     std::string dummy;
     is >> dummy >> innerRadius_;
 }
References innerRadius_, BaseBoundary::read(), and oomph::Global_string_for_annotation::string().
rotateParticle()
void CircularPeriodicBoundary::rotateParticle (BaseParticle * P, double angle)
Parameters
[in]
todo{Do we need to update rotations and rotational velocitys?}
 {
     double R = sqrt(pow(P->getPosition().X, 2) + pow(P->getPosition().Y, 2));
     double alphaPos = atan2(P->getPosition().Y, P->getPosition().X);
     double V = sqrt(pow(P->getVelocity().X, 2) + pow(P->getVelocity().Y, 2));
     double alphaVel = atan2(P->getVelocity().Y, P->getVelocity().X);
     alphaPos += angle;
     alphaVel += angle;
     P->setPosition(Vec3D(cos(alphaPos) * R, sin(alphaPos * R), P->getPosition().Z));
     P->setVelocity(Vec3D(cos(alphaVel) * V, sin(alphaVel * V), P->getVelocity().Z));
 }
References Jeffery_Solution::angle(), atan2(), cos(), Global_Physical_Variables::P, Eigen::bfloat16_impl::pow(), R, sin(), sqrt(), and V.
Referenced by checkBoundaryAfterParticleMoved(), and createPeriodicParticle().
write()
void CircularPeriodicBoundary::write (std::ostream & os) const override virtual
outputs the CircularPeriodicBoundary
Implements BaseBoundary.
 {
     BaseBoundary::write(os);
     os << " innerRadius " << innerRadius_;
 }
References innerRadius_, and BaseBoundary::write().
Member Data Documentation
innerRadius_
double CircularPeriodicBoundary::innerRadius_ private
Referenced by checkBoundaryAfterParticleMoved(), CircularPeriodicBoundary(), createPeriodicParticle(), oldRead(), read(), and write().
The documentation for this class was generated from the following files:
CircularPeriodicBoundary.h
CircularPeriodicBoundary.cc