MercuryDPM: Eigen::internal::AllRange< SizeAtCompileTime_ > Class Template Reference
Eigen::internal::AllRange< SizeAtCompileTime_ > Class Template Reference
#include <IndexedViewHelper.h>
Public Member Functions
constexpr AllRange (Index size)
constexpr Index operator[] (Index i) const noexcept
constexpr Index first () const noexcept
constexpr Index size () const noexcept
constexpr Index incr () const noexcept
Static Public Attributes
static constexpr Index FirstAtCompileTime = Index(0)
static constexpr Index SizeAtCompileTime = SizeAtCompileTime_
static constexpr Index IncrAtCompileTime = Index(1)
Private Attributes
variable_if_dynamic< Index, int(SizeAtCompileTime)> size_
Constructor & Destructor Documentation
AllRange()
template<Index SizeAtCompileTime_> constexpr Eigen::internal::AllRange< SizeAtCompileTime_ >::AllRange (Index size) inline constexpr
 : size_(size) {}
Member Function Documentation
first()
template<Index SizeAtCompileTime_> constexpr Index Eigen::internal::AllRange< SizeAtCompileTime_ >::first () const inline constexpr noexcept
 { return FirstAtCompileTime; }
References Eigen::internal::AllRange< SizeAtCompileTime_ >::FirstAtCompileTime.
Referenced by Eigen::internal::IndexedViewHelper< AllRange< SizeAtCompileTime_ >, void >::first().
incr()
template<Index SizeAtCompileTime_> constexpr Index Eigen::internal::AllRange< SizeAtCompileTime_ >::incr () const inline constexpr noexcept
 { return IncrAtCompileTime; }
References Eigen::internal::AllRange< SizeAtCompileTime_ >::IncrAtCompileTime.
Referenced by Eigen::internal::IndexedViewHelper< AllRange< SizeAtCompileTime_ >, void >::incr().
operator[]()
template<Index SizeAtCompileTime_> constexpr Index Eigen::internal::AllRange< SizeAtCompileTime_ >::operator[] (Index i) const inline constexpr noexcept
 { return i; }
References i.
size()
template<Index SizeAtCompileTime_> constexpr Index Eigen::internal::AllRange< SizeAtCompileTime_ >::size () const inline constexpr noexcept
 { return size_.value(); }
References Eigen::internal::AllRange< SizeAtCompileTime_ >::size_, and Eigen::internal::variable_if_dynamic< T, Value >::value().
Referenced by Eigen::internal::IndexedViewHelper< AllRange< SizeAtCompileTime_ >, void >::size().
Member Data Documentation
FirstAtCompileTime
template<Index SizeAtCompileTime_> constexpr Index Eigen::internal::AllRange< SizeAtCompileTime_ >::FirstAtCompileTime = Index(0) static constexpr
Referenced by Eigen::internal::AllRange< SizeAtCompileTime_ >::first().
IncrAtCompileTime
template<Index SizeAtCompileTime_> constexpr Index Eigen::internal::AllRange< SizeAtCompileTime_ >::IncrAtCompileTime = Index(1) static constexpr
Referenced by Eigen::internal::AllRange< SizeAtCompileTime_ >::incr().
size_
template<Index SizeAtCompileTime_> variable_if_dynamic<Index, int(SizeAtCompileTime)> Eigen::internal::AllRange< SizeAtCompileTime_ >::size_ private
Referenced by Eigen::internal::AllRange< SizeAtCompileTime_ >::size().
SizeAtCompileTime
template<Index SizeAtCompileTime_> constexpr Index Eigen::internal::AllRange< SizeAtCompileTime_ >::SizeAtCompileTime = SizeAtCompileTime_ static constexpr
The documentation for this class was generated from the following file:
IndexedViewHelper.h