MercuryDPM: oomph::Domain Class Reference
oomph::Domain Class Reference abstract
#include <domain.h>
Public Member Functions
Domain ()
Constructor.
Domain (const Domain &)=delete
Broken copy constructor.
void operator= (const Domain &)=delete
Broken assignment operator.
virtual ~Domain ()
MacroElement * macro_element_pt (const unsigned &i)
Access to i-th macro element.
unsigned nmacro_element ()
Number of macro elements in domain.
void output (const std::string &filename, const unsigned &nplot)
Output macro elements.
void output (std::ostream &outfile, const unsigned &nplot)
Output macro elements.
virtual void macro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)=0
virtual void macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void output_macro_element_boundaries (const std::string &filename, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
void output_macro_element_boundaries (std::ostream &outfile, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
virtual void dmacro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void dmacro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void dmacro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void d2macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
Protected Attributes
Vector< MacroElement * > Macro_element_pt
Vector of pointers to macro elements.
Detailed Description
Base class for Domains with curvilinear and/or time-dependent boundaries. Domain boundaries are typically represented by GeomObject s and the Domain itself is decomposed into a number of MacroElement s as shown in this 2D example:
Any instantiation of a specific Domain needs to implement the pure virtual member function
Domain::macro_element_boundary(...)
which returns a Vector representation of each of the MacroElement s' boundaries, parametrised by the coordinate(s) along this boundary. For instance, in the above example, the eastern boundary of MacroElement 1 is given by the appropriate fraction of the curvilinear boundary; its northern boundary (which coincides with the southern boundary of MacroElement 2) is given by the straight line emanating from the curvilinear boundary, etc. The MacroElement s obtain their boundary positions via member function pointers to Domain::macro_element_boundary(...).
Constructor & Destructor Documentation
Domain() [1/2]
oomph::Domain::Domain () inline
Constructor.
     {
       // Make sure all containers are empty (a bit paranoid, I know...)
       Macro_element_pt.resize(0);
     }
References Macro_element_pt.
Domain() [2/2]
oomph::Domain::Domain (const Domain &) delete
Broken copy constructor.
~Domain()
virtual oomph::Domain::~Domain () inline virtual
Destructor: Strictly speaking, whoever creates an object dynamically should be responsible for the cleanup of said object but it makes sense here for the Domain to generically kill any MacroElements left over in the MacroElement container (if it hasn't already been done in the derived class) to avoid memory leaks.
     {
       // How many macro elements are there?
       unsigned n_macro_element = Macro_element_pt.size();
       // Loop over the macro elements
       for (unsigned i = 0; i < n_macro_element; i++)
       {
         // They might have already deleted (some or all of) the macro elements
         // so skip them if they've already been made null pointers
         if (Macro_element_pt[i] != 0)
         {
           // Delete the i-th macro element
           delete Macro_element_pt[i];
           // Make it a null pointer
           Macro_element_pt[i] = 0;
         }
       } // for (unsigned i=0;i<n_macro_element;i++)
       // Now clear the storage. NOTE: We can't just call this function
       // as this would only delete the pointers to the macro elements,
       // not the macro elements themselves!
       Macro_element_pt.clear();
     } // End of ~Domain
References i, and Macro_element_pt.
Member Function Documentation
d2macro_element_boundary() [1/3]
virtual void oomph::Domain::d2macro_element_boundary (const double & t, const unsigned & i_macro, const unsigned & i_direct, const Vector< double > & s, Vector< double > & f) inline virtual
Vector representation of the i_macro-th macro element boundary seocond derivatives i_direct (e.g. N/S/W/E in 2D) at continuous time level t. Broken virtual.
     {
       throw OomphLibError(
         "Domain::d2macro_element_boundary() is broken virtual.",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
d2macro_element_boundary() [2/3]
void oomph::Domain::d2macro_element_boundary (const unsigned & i_macro, const unsigned & i_direct, const Vector< double > & s, Vector< double > & f) inline
Vector representation of the i_macro-th macro element boundary second derivatives i_direct (e.g. N/S/W/E in 2D) at current time: f(s).
     {
       // Call unsteady version for current time
       unsigned t = 0;
       d2macro_element_boundary(t, i_macro, i_direct, s, f);
     }
References d2macro_element_boundary(), f(), s, and plotPSD::t.
d2macro_element_boundary() [3/3]
virtual void oomph::Domain::d2macro_element_boundary (const unsigned & t, const unsigned & i_macro, const unsigned & i_direct, const Vector< double > & s, Vector< double > & f) inline virtual
Vector representation of the i_macro-th macro element boundary second derivatives i_direct (e.g. N/S/W/E in 2D) at time level t (t=0: present; t>0: previous): f(s). Broken virtual.
Reimplemented in oomph::TopologicallyRectangularDomain.
     {
       throw OomphLibError(
         "Domain::d2macro_element_boundary() is broken virtual.",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::QMacroElement< 2 >::assemble_macro_to_eulerian_jacobian2(), and d2macro_element_boundary().
dmacro_element_boundary() [1/3]
virtual void oomph::Domain::dmacro_element_boundary (const double & t, const unsigned & i_macro, const unsigned & i_direct, const Vector< double > & s, Vector< double > & f) inline virtual
Vector representation of the i_macro-th macro element boundary derivatives i_direct (e.g. N/S/W/E in 2D) at continuous time level t. Broken virtual.
     {
       throw OomphLibError(
         "Domain::dmacro_element_boundary() is broken virtual.",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
dmacro_element_boundary() [2/3]
void oomph::Domain::dmacro_element_boundary (const unsigned & i_macro, const unsigned & i_direct, const Vector< double > & s, Vector< double > & f) inline
Vector representation of the i_macro-th macro element boundary derivatives i_direct (e.g. N/S/W/E in 2D) at current time: f(s).
     {
       // Call unsteady version for current time
       unsigned t = 0;
       dmacro_element_boundary(t, i_macro, i_direct, s, f);
     }
References dmacro_element_boundary(), f(), s, and plotPSD::t.
dmacro_element_boundary() [3/3]
virtual void oomph::Domain::dmacro_element_boundary (const unsigned & t, const unsigned & i_macro, const unsigned & i_direct, const Vector< double > & s, Vector< double > & f) inline virtual
Vector representation of the i_macro-th macro element boundary derivatives i_direct (e.g. N/S/W/E in 2D) at time level t (t=0: present; t>0: previous): f(s). Broken virtual.
Reimplemented in oomph::TopologicallyRectangularDomain.
     {
       throw OomphLibError(
         "Domain::dmacro_element_boundary() is broken virtual.",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::QMacroElement< 2 >::assemble_macro_to_eulerian_jacobian(), oomph::QMacroElement< 2 >::assemble_macro_to_eulerian_jacobian2(), and dmacro_element_boundary().
macro_element_boundary() [1/3]
virtual void oomph::Domain::macro_element_boundary (const double & t, const unsigned & i_macro, const unsigned & i_direct, const Vector< double > & s, Vector< double > & f) inline virtual
Vector representation of the i_macro-th macro element boundary i_direct (e.g. N/S/W/E in 2D) at continuous time, t
Reimplemented in oomph::RectangleWithHoleAndAnnularRegionDomain.
     {
       // Throw an error
       throw OomphLibError("Domain::macro_element_boundary() is broken virtual.",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     } // End of macro_element_boundary
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
macro_element_boundary() [2/3]
void oomph::Domain::macro_element_boundary (const unsigned & i_macro, const unsigned & i_direct, const Vector< double > & s, Vector< double > & f) inline
Vector representation of the i_macro-th macro element boundary i_direct (e.g. N/S/W/E in 2D) at current time: f(s).
     {
       // Call unsteady version for current time
       unsigned t = 0;
       macro_element_boundary(t, i_macro, i_direct, s, f);
     }
References f(), macro_element_boundary(), s, and plotPSD::t.
macro_element_boundary() [3/3]
virtual void oomph::Domain::macro_element_boundary (const unsigned & t, const unsigned & i_macro, const unsigned & i_direct, const Vector< double > & s, Vector< double > & f) pure virtual
Vector representation of the i_macro-th macro element boundary i_direct (e.g. N/S/W/E in 2D) at time level t (t=0: present; t>0: previous): f(s)
Implemented in oomph::RectangleWithHoleAndAnnularRegionDomain, oomph::RectangleWithHoleDomain, oomph::CylinderWithFlagDomain, RectangleWithHoleDomain, CylinderAndInterfaceDomain, oomph::HalfRectangleWithHoleDomain, oomph::HalfRectangleWithHoleDomain, RectangleWithHoleDomain, RectangleWithHoleDomain, oomph::ExtrudedDomain, oomph::CollapsibleChannelDomain, oomph::ChannelWithLeafletDomain, oomph::EighthSphereDomain, oomph::FishDomain, oomph::TubeDomain, oomph::TopologicallyRectangularDomain, oomph::QuarterTubeDomain, oomph::QuarterPipeDomain, oomph::QuarterCircleSectorDomain, oomph::FullCircleDomain, oomph::AnnularDomain, and oomph::WarpedCubeDomain.
Referenced by oomph::QMacroElement< 2 >::assemble_macro_to_eulerian_jacobian(), oomph::QMacroElement< 2 >::assemble_macro_to_eulerian_jacobian2(), macro_element_boundary(), oomph::ExtrudedDomain::macro_element_boundary(), oomph::QMacroElement< 2 >::macro_map(), oomph::QMacroElement< 3 >::macro_map(), oomph::QMacroElement< 2 >::output_macro_element_boundaries(), and oomph::QMacroElement< 3 >::output_macro_element_boundaries().
macro_element_pt()
MacroElement* oomph::Domain::macro_element_pt (const unsigned & i) inline
Access to i-th macro element.
     {
       return Macro_element_pt[i];
     }
References i, and Macro_element_pt.
Referenced by oomph::ChannelWithLeafletMesh< ELEMENT >::ChannelWithLeafletMesh(), oomph::CollapsibleChannelMesh< ELEMENT >::CollapsibleChannelMesh(), CylinderAndInterfaceMesh< ELEMENT >::CylinderAndInterfaceMesh(), oomph::EighthSphereMesh< ELEMENT >::EighthSphereMesh(), oomph::ElasticRefineableQuarterPipeMesh< ELEMENT >::ElasticRefineableQuarterPipeMesh(), oomph::FullCircleMesh< ELEMENT >::FullCircleMesh(), oomph::ExtrudedDomain::macro_element_boundary(), output_macro_element_boundaries(), oomph::QuarterCircleSectorMesh< ELEMENT >::QuarterCircleSectorMesh(), oomph::QuarterPipeMesh< ELEMENT >::QuarterPipeMesh(), oomph::QuarterTubeMesh< ELEMENT >::QuarterTubeMesh(), oomph::RectangleWithHoleMesh< ELEMENT >::RectangleWithHoleMesh(), oomph::RefineableEighthSphereMesh< ELEMENT >::RefineableEighthSphereMesh(), oomph::RefineableFullCircleMesh< ELEMENT >::RefineableFullCircleMesh(), oomph::RefineableQuarterTubeMesh< ELEMENT >::RefineableQuarterTubeMesh(), oomph::RefineableRectangleWithHoleAndAnnularRegionMesh< ELEMENT >::RefineableRectangleWithHoleAndAnnularRegionMesh(), oomph::RefineableRectangleWithHoleMesh< ELEMENT >::RefineableRectangleWithHoleMesh(), oomph::RefineableTubeMesh< ELEMENT >::RefineableTubeMesh(), oomph::RefineableTwoDAnnularMesh< ELEMENT >::RefineableTwoDAnnularMesh(), and oomph::TubeMesh< ELEMENT >::TubeMesh().
nmacro_element()
unsigned oomph::Domain::nmacro_element () inline
Number of macro elements in domain.
     {
       return Macro_element_pt.size();
     }
References Macro_element_pt.
Referenced by oomph::ExtrudedCubeMeshFromQuadMesh< ELEMENT >::build_mesh(), CylinderAndInterfaceMesh< ELEMENT >::CylinderAndInterfaceMesh(), oomph::ExtrudedDomain::ExtrudedDomain(), oomph::ExtrudedDomain::macro_element_boundary(), output_macro_element_boundaries(), oomph::RectangleWithHoleAndAnnularRegionMesh< ELEMENT >::RectangleWithHoleAndAnnularRegionMesh(), oomph::RectangleWithHoleMesh< ELEMENT >::RectangleWithHoleMesh(), and oomph::RefineableRectangleWithHoleAndAnnularRegionMesh< ELEMENT >::RefineableRectangleWithHoleAndAnnularRegionMesh().
operator=()
void oomph::Domain::operator= (const Domain &) delete
Broken assignment operator.
output() [1/2]
void oomph::Domain::output (const std::string & filename, const unsigned & nplot) inline
Output macro elements.
     {
       std::ofstream outfile;
       outfile.open(filename.c_str());
       output(outfile, nplot);
       outfile.close();
     }
References MergeRestartFiles::filename.
Referenced by main().
output() [2/2]
void oomph::Domain::output (std::ostream & outfile, const unsigned & nplot) inline
Output macro elements.
     {
       unsigned nmacro = Macro_element_pt.size();
       for (unsigned i_macro = 0; i_macro < nmacro; i_macro++)
       {
         Macro_element_pt[i_macro]->output(outfile, nplot);
       }
     }
References Macro_element_pt.
output_macro_element_boundaries() [1/2]
void oomph::Domain::output_macro_element_boundaries (const std::string & filename, const unsigned & nplot) inline
Output all macro element boundaries as tecplot zones.
     {
       std::ofstream outfile;
       outfile.open(filename.c_str());
       output_macro_element_boundaries(outfile, nplot);
       outfile.close();
     }
References MergeRestartFiles::filename.
Referenced by main().
output_macro_element_boundaries() [2/2]
void oomph::Domain::output_macro_element_boundaries (std::ostream & outfile, const unsigned & nplot) inline
Output all macro element boundaries as tecplot zones.
     {
       // Loop over macro elements
       unsigned nmacro = nmacro_element();
       for (unsigned i = 0; i < nmacro; i++)
       {
         macro_element_pt(i)->output_macro_element_boundaries(outfile, nplot);
       }
     }
References i, macro_element_pt(), nmacro_element(), and oomph::MacroElement::output_macro_element_boundaries().
Member Data Documentation
Macro_element_pt
Vector<MacroElement*> oomph::Domain::Macro_element_pt protected
Vector of pointers to macro elements.
Referenced by oomph::AnnularDomain::AnnularDomain(), oomph::ChannelWithLeafletDomain::ChannelWithLeafletDomain(), oomph::CollapsibleChannelDomain::CollapsibleChannelDomain(), oomph::CylinderWithFlagDomain::CylinderWithFlagDomain(), Domain(), oomph::EighthSphereDomain::EighthSphereDomain(), oomph::ExtrudedDomain::ExtrudedDomain(), oomph::FishDomain::FishDomain(), oomph::FullCircleDomain::FullCircleDomain(), macro_element_pt(), oomph::ExtrudedDomain::macro_element_pt(), nmacro_element(), oomph::ExtrudedDomain::nmacro_element(), output(), oomph::QuarterCircleSectorDomain::QuarterCircleSectorDomain(), oomph::QuarterPipeDomain::QuarterPipeDomain(), oomph::QuarterTubeDomain::QuarterTubeDomain(), oomph::RectangleWithHoleAndAnnularRegionDomain::RectangleWithHoleAndAnnularRegionDomain(), oomph::RectangleWithHoleDomain::RectangleWithHoleDomain(), oomph::TopologicallyRectangularDomain::TopologicallyRectangularDomain(), oomph::TubeDomain::TubeDomain(), oomph::WarpedCubeDomain::WarpedCubeDomain(), and ~Domain().
The documentation for this class was generated from the following file:
domain.h