MercuryDPM: Eigen::internal::mapbase_evaluator< Derived, PlainObjectType > Struct Template Reference
Eigen::internal::mapbase_evaluator< Derived, PlainObjectType > Struct Template Reference
#include <CoreEvaluators.h>
Public Types
enum { IsRowMajor = XprType::RowsAtCompileTime , ColsAtCompileTime = XprType::ColsAtCompileTime , CoeffReadCost = NumTraits<Scalar>::ReadCost }
typedef Derived XprType
typedef XprType::PointerType PointerType
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
Public Types inherited from Eigen::internal::evaluator_base< Derived >
enum
typedef traits< Derived > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE mapbase_evaluator (const XprType &map)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
template<int LoadMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType packet (Index index) const
template<int StoreMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void writePacket (Index row, Index col, const PacketType &x)
template<int StoreMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void writePacket (Index index, const PacketType &x)
Public Member Functions inherited from Eigen::internal::evaluator_base< Derived >
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE evaluator_base ()=default
Protected Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index rowStride () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index colStride () const EIGEN_NOEXCEPT
Protected Attributes
PointerType m_data
const internal::variable_if_dynamic< Index, XprType::InnerStrideAtCompileTime > m_innerStride
const internal::variable_if_dynamic< Index, XprType::OuterStrideAtCompileTime > m_outerStride
Member Typedef Documentation
CoeffReturnType
template<typename Derived , typename PlainObjectType > typedef XprType::CoeffReturnType Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::CoeffReturnType
PointerType
template<typename Derived , typename PlainObjectType > typedef XprType::PointerType Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::PointerType
Scalar
template<typename Derived , typename PlainObjectType > typedef XprType::Scalar Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::Scalar
XprType
template<typename Derived , typename PlainObjectType > typedef Derived Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::XprType
Member Enumeration Documentation
anonymous enum
template<typename Derived , typename PlainObjectType > anonymous enum
Enumerator
IsRowMajor
ColsAtCompileTime
CoeffReadCost
        {
     IsRowMajor = XprType::RowsAtCompileTime,
     ColsAtCompileTime = XprType::ColsAtCompileTime,
     CoeffReadCost = NumTraits<Scalar>::ReadCost
   };
Constructor & Destructor Documentation
mapbase_evaluator()
template<typename Derived , typename PlainObjectType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::mapbase_evaluator (const XprType & map) inline explicit
       : m_data(const_cast<PointerType>(map.data())),
         m_innerStride(map.innerStride()),
         m_outerStride(map.outerStride()) {
     EIGEN_STATIC_ASSERT(check_implication((evaluator<Derived>::Flags & PacketAccessBit) != 0,
                                           internal::inner_stride_at_compile_time<Derived>::ret == 1),
                         PACKET_ACCESS_REQUIRES_TO_HAVE_INNER_STRIDE_FIXED_TO_1);
     EIGEN_INTERNAL_CHECK_COST_VALUE(CoeffReadCost);
   }
References Eigen::internal::check_implication(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::CoeffReadCost, EIGEN_INTERNAL_CHECK_COST_VALUE, EIGEN_STATIC_ASSERT, and Eigen::PacketAccessBit.
Member Function Documentation
coeff() [1/2]
template<typename Derived , typename PlainObjectType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::coeff (Index index) const inline
{
     return m_data[index * m_innerStride.value()];
   }
References Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::m_data, Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::m_innerStride, and Eigen::internal::variable_if_dynamic< T, Value >::value().
coeff() [2/2]
template<typename Derived , typename PlainObjectType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::coeff (Index row, Index col) const inline
{
     return m_data[col * colStride() + row * rowStride()];
   }
References col(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::colStride(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::m_data, row(), and Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::rowStride().
coeffRef() [1/2]
template<typename Derived , typename PlainObjectType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::coeffRef (Index index) inline
 { return m_data[index * m_innerStride.value()]; }
References Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::m_data, Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::m_innerStride, and Eigen::internal::variable_if_dynamic< T, Value >::value().
coeffRef() [2/2]
template<typename Derived , typename PlainObjectType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::coeffRef (Index row, Index col) inline
{
     return m_data[col * colStride() + row * rowStride()];
   }
References col(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::colStride(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::m_data, row(), and Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::rowStride().
colStride()
template<typename Derived , typename PlainObjectType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::colStride () const inline protected
{
     return XprType::IsRowMajor ? m_innerStride.value() : m_outerStride.value();
   }
References Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::m_innerStride, Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::m_outerStride, and Eigen::internal::variable_if_dynamic< T, Value >::value().
Referenced by Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::coeff(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::coeffRef(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::packet(), and Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::writePacket().
packet() [1/2]
template<typename Derived , typename PlainObjectType > template<int LoadMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::packet (Index index) const inline
{
     return internal::ploadt<PacketType, LoadMode>(m_data + index * m_innerStride.value());
   }
References Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::m_data, Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::m_innerStride, and Eigen::internal::variable_if_dynamic< T, Value >::value().
packet() [2/2]
template<typename Derived , typename PlainObjectType > template<int LoadMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::packet (Index row, Index col) const inline
{
     PointerType ptr = m_data + row * rowStride() + col * colStride();
     return internal::ploadt<PacketType, LoadMode>(ptr);
   }
References col(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::colStride(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::m_data, row(), and Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::rowStride().
rowStride()
template<typename Derived , typename PlainObjectType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::rowStride () const inline protected
{
     return XprType::IsRowMajor ? m_outerStride.value() : m_innerStride.value();
   }
References Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::m_innerStride, Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::m_outerStride, and Eigen::internal::variable_if_dynamic< T, Value >::value().
Referenced by Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::coeff(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::coeffRef(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::packet(), and Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::writePacket().
writePacket() [1/2]
template<typename Derived , typename PlainObjectType > template<int StoreMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::writePacket (Index index, const PacketType & x) inline
{
     internal::pstoret<Scalar, PacketType, StoreMode>(m_data + index * m_innerStride.value(), x);
   }
References Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::m_data, Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::m_innerStride, Eigen::internal::variable_if_dynamic< T, Value >::value(), and plotDoE::x.
writePacket() [2/2]
template<typename Derived , typename PlainObjectType > template<int StoreMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::writePacket (Index row, Index col, const PacketType & x) inline
{
     PointerType ptr = m_data + row * rowStride() + col * colStride();
     return internal::pstoret<Scalar, PacketType, StoreMode>(ptr, x);
   }
References col(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::colStride(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::m_data, row(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::rowStride(), and plotDoE::x.
Member Data Documentation
m_data
template<typename Derived , typename PlainObjectType > PointerType Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::m_data protected
Referenced by Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::coeff(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::coeffRef(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::packet(), and Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::writePacket().
m_innerStride
template<typename Derived , typename PlainObjectType > const internal::variable_if_dynamic<Index, XprType::InnerStrideAtCompileTime> Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::m_innerStride protected
Referenced by Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::coeff(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::coeffRef(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::colStride(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::packet(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::rowStride(), and Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::writePacket().
m_outerStride
template<typename Derived , typename PlainObjectType > const internal::variable_if_dynamic<Index, XprType::OuterStrideAtCompileTime> Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::m_outerStride protected
Referenced by Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::colStride(), and Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::rowStride().
The documentation for this struct was generated from the following file:
CoreEvaluators.h