MercuryDPM: Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device > Struct Template Reference
#include <TensorMorphing.h>
Public Types
enum {
IsAligned = false , PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess , BlockAccess , PreferBlockAccess = true ,
CoordAccess = false , RawAccess = false
}
typedef TensorSlicingOp< StartIndices, Sizes, ArgType > XprType
typedef XprType::Index Index
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef Sizes Dimensions
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef StorageMemory< std::remove_const_t< CoeffReturnType >, Device > ConstCastStorage
typedef Storage::Type EvaluatorPointerType
typedef std::remove_const_t< Scalar > ScalarNoConst
typedef internal::TensorBlockDescriptor< NumDims, Index > TensorBlockDesc
typedef internal::TensorBlockScratchAllocator< Device > TensorBlockScratch
typedef TensorEvaluator< const ArgType, Device >::TensorBlock TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType data)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements getResourceRequirements () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock block (TensorBlockDesc &desc, TensorBlockScratch &scratch, bool=false) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Storage::Type data () const
Static Public Attributes
static constexpr int NumDims = internal::array_size<Sizes>::value
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Protected Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index srcCoeff (Index index) const
Protected Attributes
array< Index, NumDims > m_outputStrides
array< internal::TensorIntDivisor< Index >, NumDims > m_fastOutputStrides
array< Index, NumDims > m_inputStrides
TensorEvaluator< ArgType, Device > m_impl
const Device EIGEN_DEVICE_REF m_device
Dimensions m_dimensions
bool m_is_identity
const StartIndices m_offsets
Member Typedef Documentation
CoeffReturnType
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::CoeffReturnType
ConstCastStorage
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef StorageMemory<std::remove_const_t<CoeffReturnType>, Device> Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::ConstCastStorage
Dimensions
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef Sizes Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::Dimensions
EvaluatorPointerType
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::EvaluatorPointerType
Index
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::Index
PacketReturnType
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::PacketReturnType
Scalar
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::Scalar
ScalarNoConst
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef std::remove_const_t<Scalar> Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::ScalarNoConst
Storage
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::Storage
TensorBlock
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef TensorEvaluator<const ArgType, Device>::TensorBlock Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::TensorBlock
TensorBlockDesc
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef internal::TensorBlockDescriptor<NumDims, Index> Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::TensorBlockDesc
TensorBlockScratch
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef internal::TensorBlockScratchAllocator<Device> Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::TensorBlockScratch
XprType
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef TensorSlicingOp<StartIndices, Sizes, ArgType> Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     // Alignment can't be guaranteed at compile time since it depends on the
     // slice offsets and sizes.
     IsAligned = false,
     PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess,
     BlockAccess = TensorEvaluator<ArgType, Device>::BlockAccess &&
                   // FIXME: Temporary workaround for bug in slicing of bool tensors.
                   !internal::is_same<std::remove_const_t<Scalar>, bool>::value,
     PreferBlockAccess = true,
     CoordAccess = false,
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_impl(op.expression(), device), m_device(device), m_dimensions(op.sizes()), m_offsets(op.startIndices()) {
     m_is_identity = true;
     for (int i = 0; i < internal::array_size<Dimensions>::value; ++i) {
       eigen_assert(m_impl.dimensions()[i] >= op.sizes()[i] + op.startIndices()[i]);
       if (m_impl.dimensions()[i] != op.sizes()[i] || op.startIndices()[i] != 0) {
         m_is_identity = false;
       }
     }
     // No strides for scalars.
     if (NumDims == 0) return;
     const typename TensorEvaluator<ArgType, Device>::Dimensions& input_dims = m_impl.dimensions();
     const Sizes& output_dims = op.sizes();
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       m_inputStrides[0] = 1;
       for (int i = 1; i < NumDims; ++i) {
         m_inputStrides[i] = m_inputStrides[i - 1] * input_dims[i - 1];
       }
       // Don't initialize m_fastOutputStrides[0] since it won't ever be accessed.
       m_outputStrides[0] = 1;
       for (int i = 1; i < NumDims; ++i) {
         m_outputStrides[i] = m_outputStrides[i - 1] * output_dims[i - 1];
         m_fastOutputStrides[i] = internal::TensorIntDivisor<Index>(m_outputStrides[i] > 0 ? m_outputStrides[i] : 1);
       }
     } else {
       m_inputStrides[NumDims - 1] = 1;
       for (int i = NumDims - 2; i >= 0; --i) {
         m_inputStrides[i] = m_inputStrides[i + 1] * input_dims[i + 1];
       }
       // Don't initialize m_fastOutputStrides[NumDims-1] since it won't ever be accessed.
       m_outputStrides[NumDims - 1] = 1;
       for (int i = NumDims - 2; i >= 0; --i) {
         m_outputStrides[i] = m_outputStrides[i + 1] * output_dims[i + 1];
         m_fastOutputStrides[i] = internal::TensorIntDivisor<Index>(m_outputStrides[i] > 0 ? m_outputStrides[i] : 1);
       }
     }
   }
References Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), eigen_assert, i, Eigen::TensorEvaluator< Derived, Device >::Layout, op, and Eigen::value.
Member Function Documentation
block()
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::block (TensorBlockDesc & desc, TensorBlockScratch & scratch, bool = false) const inline
{
     TensorBlockDesc arg_desc = desc.WithOffset(srcCoeff(desc.offset()));
     TensorBlock block = m_impl.block(arg_desc, scratch);
     if (!arg_desc.HasDestinationBuffer()) desc.DropDestinationBuffer();
     return block;
   }
References Eigen::TensorEvaluator< Derived, Device >::block(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::DropDestinationBuffer(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::HasDestinationBuffer(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::offset(), and Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::WithOffset().
cleanup()
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::cleanup () inline
 { m_impl.cleanup(); }
Referenced by framework.Frame::__init__().
coeff()
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::coeff (Index index) const inline
{
     if (m_is_identity) {
       return m_impl.coeff(index);
     } else {
       return m_impl.coeff(srcCoeff(index));
     }
   }
costPerCoeff()
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     return m_impl.costPerCoeff(vectorized) + TensorOpCost(0, 0, m_is_identity ? 1 : NumDims);
   }
data()
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Storage::Type Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::data () const inline
{
     typename Storage::Type result = constCast(m_impl.data());
     if (result) {
       Index offset = 0;
       if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
         for (int i = 0; i < NumDims; ++i) {
           if (m_dimensions[i] != m_impl.dimensions()[i]) {
             offset += m_offsets[i] * m_inputStrides[i];
             for (int j = i + 1; j < NumDims; ++j) {
               if (m_dimensions[j] > 1) {
                 return NULL;
               }
               offset += m_offsets[j] * m_inputStrides[j];
             }
             break;
           }
         }
       } else {
         for (int i = NumDims - 1; i >= 0; --i) {
           if (m_dimensions[i] != m_impl.dimensions()[i]) {
             offset += m_offsets[i] * m_inputStrides[i];
             for (int j = i - 1; j >= 0; --j) {
               if (m_dimensions[j] > 1) {
                 return NULL;
               }
               offset += m_offsets[j] * m_inputStrides[j];
             }
             break;
           }
         }
       }
       return result + offset;
     }
     return NULL;
   }
References Eigen::ColMajor, Eigen::constCast(), i, j, and Eigen::TensorEvaluator< Derived, Device >::Layout.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::dimensions () const inline
 { return m_dimensions; }
evalSubExprsIfNeeded()
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType data) inline
{
     m_impl.evalSubExprsIfNeeded(NULL);
     if (!NumTraits<std::remove_const_t<Scalar>>::RequireInitialization && data && m_impl.data()) {
       Index contiguous_values = 1;
       if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
         for (int i = 0; i < NumDims; ++i) {
           contiguous_values *= dimensions()[i];
           if (dimensions()[i] != m_impl.dimensions()[i]) {
             break;
           }
         }
       } else {
         for (int i = NumDims - 1; i >= 0; --i) {
           contiguous_values *= dimensions()[i];
           if (dimensions()[i] != m_impl.dimensions()[i]) {
             break;
           }
         }
       }
       // Use memcpy if it's going to be faster than using the regular evaluation.
       const internal::MemcpyTriggerForSlicing<Index, Device, BlockAccess> trigger(m_device);
       if (trigger(internal::array_prod(dimensions()), contiguous_values)) {
         EvaluatorPointerType src = (EvaluatorPointerType)m_impl.data();
         for (Index i = 0; i < internal::array_prod(dimensions()); i += contiguous_values) {
           Index offset = srcCoeff(i);
           m_device.memcpy((void*)(m_device.get(data + i)), m_device.get(src + offset),
                           contiguous_values * sizeof(Scalar));
         }
         return false;
       }
     }
     return true;
   }
References Eigen::internal::array_prod(), Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::data(), Eigen::TensorEvaluator< Derived, Device >::dimensions(), i, Eigen::TensorEvaluator< Derived, Device >::Layout, and Eigen::TensorEvaluator< Derived, Device >::m_device.
getResourceRequirements()
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::getResourceRequirements () const inline
{
     const size_t target_size = m_device.lastLevelCacheSize();
     return internal::TensorBlockResourceRequirements::merge(
         internal::TensorBlockResourceRequirements::skewed<Scalar>(target_size), m_impl.getResourceRequirements());
   }
References Eigen::TensorEvaluator< Derived, Device >::m_device, and Eigen::internal::TensorBlockResourceRequirements::merge().
packet()
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::packet (Index index) const inline
{
     const int packetSize = PacketType<CoeffReturnType, Device>::size;
     EIGEN_STATIC_ASSERT((packetSize > 1), YOU_MADE_A_PROGRAMMING_MISTAKE)
     eigen_assert(index + packetSize - 1 < internal::array_prod(dimensions()));
     if (m_is_identity) {
       return m_impl.template packet<LoadMode>(index);
     }
     Index inputIndices[] = {0, 0};
     Index indices[] = {index, index + packetSize - 1};
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       EIGEN_UNROLL_LOOP
       for (int i = NumDims - 1; i > 0; --i) {
         const Index idx0 = indices[0] / m_fastOutputStrides[i];
         const Index idx1 = indices[1] / m_fastOutputStrides[i];
         inputIndices[0] += (idx0 + m_offsets[i]) * m_inputStrides[i];
         inputIndices[1] += (idx1 + m_offsets[i]) * m_inputStrides[i];
         indices[0] -= idx0 * m_outputStrides[i];
         indices[1] -= idx1 * m_outputStrides[i];
       }
       inputIndices[0] += (indices[0] + m_offsets[0]);
       inputIndices[1] += (indices[1] + m_offsets[0]);
     } else {
       EIGEN_UNROLL_LOOP
       for (int i = 0; i < NumDims - 1; ++i) {
         const Index idx0 = indices[0] / m_fastOutputStrides[i];
         const Index idx1 = indices[1] / m_fastOutputStrides[i];
         inputIndices[0] += (idx0 + m_offsets[i]) * m_inputStrides[i];
         inputIndices[1] += (idx1 + m_offsets[i]) * m_inputStrides[i];
         indices[0] -= idx0 * m_outputStrides[i];
         indices[1] -= idx1 * m_outputStrides[i];
       }
       inputIndices[0] += (indices[0] + m_offsets[NumDims - 1]);
       inputIndices[1] += (indices[1] + m_offsets[NumDims - 1]);
     }
     if (inputIndices[1] - inputIndices[0] == packetSize - 1) {
       PacketReturnType rslt = m_impl.template packet<Unaligned>(inputIndices[0]);
       return rslt;
     } else {
       EIGEN_ALIGN_MAX std::remove_const_t<CoeffReturnType> values[packetSize];
       values[0] = m_impl.coeff(inputIndices[0]);
       values[packetSize - 1] = m_impl.coeff(inputIndices[1]);
       EIGEN_UNROLL_LOOP
       for (int i = 1; i < packetSize - 1; ++i) {
         values[i] = coeff(index + i);
       }
       PacketReturnType rslt = internal::pload<PacketReturnType>(values);
       return rslt;
     }
   }
References Eigen::internal::array_prod(), Eigen::TensorEvaluator< Derived, Device >::coeff(), Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), EIGEN_ALIGN_MAX, eigen_assert, EIGEN_STATIC_ASSERT, EIGEN_UNROLL_LOOP, i, and Eigen::TensorEvaluator< Derived, Device >::Layout.
srcCoeff()
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::srcCoeff (Index index) const inline protected
{
     Index inputIndex = 0;
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       EIGEN_UNROLL_LOOP
       for (int i = NumDims - 1; i > 0; --i) {
         const Index idx = index / m_fastOutputStrides[i];
         inputIndex += (idx + m_offsets[i]) * m_inputStrides[i];
         index -= idx * m_outputStrides[i];
       }
       inputIndex += (index + m_offsets[0]);
     } else {
       EIGEN_UNROLL_LOOP
       for (int i = 0; i < NumDims - 1; ++i) {
         const Index idx = index / m_fastOutputStrides[i];
         inputIndex += (idx + m_offsets[i]) * m_inputStrides[i];
         index -= idx * m_outputStrides[i];
       }
       inputIndex += (index + m_offsets[NumDims - 1]);
     }
     return inputIndex;
   }
References Eigen::ColMajor, EIGEN_UNROLL_LOOP, i, and Eigen::TensorEvaluator< Derived, Device >::Layout.
Member Data Documentation
Layout
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_device
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > const Device EIGEN_DEVICE_REF Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::m_device protected
m_dimensions
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > Dimensions Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::m_dimensions protected
m_fastOutputStrides
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > array<internal::TensorIntDivisor<Index>, NumDims> Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::m_fastOutputStrides protected
m_impl
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::m_impl protected
m_inputStrides
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > array<Index, NumDims> Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::m_inputStrides protected
m_is_identity
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > bool Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::m_is_identity protected
m_offsets
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > const StartIndices Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::m_offsets protected
m_outputStrides
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > array<Index, NumDims> Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::m_outputStrides protected
NumDims
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::NumDims = internal::array_size<Sizes>::value static constexpr
The documentation for this struct was generated from the following file:
TensorMorphing.h