MercuryDPM: Eigen::internal::igamma_series_impl< Scalar, mode > Struct Template Reference
Eigen::internal::igamma_series_impl< Scalar, mode > Struct Template Reference
#include <SpecialFunctionsImpl.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC Scalar run (Scalar a, Scalar x)
Member Function Documentation
run()
template<typename Scalar , IgammaComputationMode mode> static EIGEN_DEVICE_FUNC Scalar Eigen::internal::igamma_series_impl< Scalar, mode >::run (Scalar a, Scalar x) inline static
{
     const Scalar zero = 0;
     const Scalar one = 1;
     const Scalar machep = cephes_helper<Scalar>::machep();
     Scalar ax = main_igamma_term<Scalar>(a, x);
     // This is independent of mode. If this value is zero,
     // then the function value is zero. If the function value is zero,
     // then we are in a neighborhood where the function value evaluates to zero,
     // so the derivative is zero.
     if (ax == zero) {
       return zero;
     }
     ax /= a;
     /* power series */
     Scalar r = a;
     Scalar c = one;
     Scalar ans = one;
     Scalar dc_da = zero;
     Scalar dans_da = zero;
     for (int i = 0; i < igamma_num_iterations<Scalar, mode>(); i++) {
       r += one;
       Scalar term = x / r;
       Scalar dterm_da = -x / (r * r);
       dc_da = term * dc_da + dterm_da * c;
       dans_da += dc_da;
       c *= term;
       ans += c;
       if (mode == VALUE) {
         if (c <= machep * ans) {
           break;
         }
       } else {
         if (numext::abs(dc_da) <= machep * numext::abs(dans_da)) {
           break;
         }
       }
     }
     Scalar dlogax_da = numext::log(x) - digamma_impl<Scalar>::run(a + one);
     Scalar dax_da = ax * dlogax_da;
     switch (mode) {
       case VALUE:
         return ans * ax;
       case DERIVATIVE:
         return ans * dax_da + dans_da * ax;
       case SAMPLE_DERIVATIVE:
       default:  // this is needed to suppress clang warning
         return -(dans_da + ans * dlogax_da) * x / a;
     }
   }
References a, Eigen::numext::abs(), plotDoE::ax, calibrate::c, Eigen::internal::DERIVATIVE, i, Eigen::numext::log(), Eigen::internal::cephes_helper< Scalar >::machep(), UniformPSDSelfTest::r, Eigen::internal::digamma_impl< Scalar >::run(), Eigen::internal::SAMPLE_DERIVATIVE, Eigen::internal::VALUE, Eigen::numext::x, and zero().
The documentation for this struct was generated from the following file:
SpecialFunctionsImpl.h