MercuryDPM: refineable_spin_up.cc File Reference
refineable_spin_up.cc File Reference
#include "generic.h"
#include "spherical_navier_stokes.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class RefineableSphericalSpinUpProblem< ELEMENT >
Driven cavity problem in rectangular domain - time dependent version.
Namespaces
Global_Physical_Variables
Global variables.
Boundary_Items
Functions
void Boundary_Items::get_exact_u_b1 (double &time, const Vector< double > &x, double &u)
int main ()
Driver for RefineableSphericalSpinUp test problem using a.
Variables
double Global_Physical_Variables::lambda =1.0
Function Documentation
main()
int main ()
Driver for RefineableSphericalSpinUp test problem using a.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
 {
  // Choose simulation interval and timestep
  unsigned nstep = 1;
  double dt = 0.25;
  // Set up doc info
  // ---------------
  // Label for output
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory("RESLT");
  // Step number
  doc_info.number()=0;
  // ---------------
  // end of Set up doc info
  // Doing QCrouzeixRaviartElements
  {
   // Build the problem with QCrouzeixRaviartElements
   RefineableSphericalSpinUpProblem<RefineableQSphericalCrouzeixRaviartElement >
    problem;
   cout << "Doing QCrouzeixRaviartElement" << std::endl;
     // Open a trace file
     ofstream trace_file;
     char filename[100];
     sprintf(filename,"%s/trace0.dat",doc_info.directory().c_str());
     trace_file.open(filename);
     trace_file << "time " << "u " << "v " << "w "
                << std::endl;
      //Refine uniformly once
     problem.refine_uniformly();
     // Initialise timestep -- also sets the weights for all timesteppers
     // in the problem.
     problem.initialise_dt(dt);
     // Set initial conditions
     problem.set_initial_condition();
     // Over-ride the maximum and minimum permitted errors
     problem.mesh_pt()->max_permitted_error() = 1.0e-2; //Default = 1.0e-3
     problem.mesh_pt()->min_permitted_error() = 1.0e-3; //Default = 1.0e-5
     // Over-ride the maximum and minimum permitted refinement levels
     problem.mesh_pt()->max_refinement_level() = 4;//maximum_ref_level;
     problem.mesh_pt()->min_refinement_level() = 1;//minimum_ref_level;
     //Specify the normalising factor explicitly
     Z2ErrorEstimator* error_pt = dynamic_cast<Z2ErrorEstimator*>(
      problem.mesh_pt()->spatial_error_estimator_pt());
     error_pt->reference_flux_norm() = 0.01;
     //Output initial condition
     problem.doc_solution(doc_info,trace_file);
     //Increment counter for solutions
     doc_info.number()++;
     //Set the maximum adaptation
     unsigned max_adapt = 3;
     bool first = true;
     // Timestepping loop
     for (unsigned istep=0;istep<nstep;istep++)
      {
       cout << " Timestep " << istep << std::endl;
       // Take timestep
       problem.unsteady_newton_solve(dt,max_adapt,first);
       //Set first to false
       first=false;
       max_adapt=1;
       //Output solution
       problem.doc_solution(doc_info,trace_file);
       Node* nod_pt = //problem.mesh_pt()->finite_element_pt(435)->node_pt(0);
        problem.mesh_pt()->node_pt(50);
       trace_file << problem.time() << " "
                  << nod_pt->x(0) << " " << nod_pt->x(1)
                  << " " << nod_pt->value(2) << std::endl;
       //Increment counter for solutions
       doc_info.number()++;
      }
     // Close trace file
     trace_file.close();
  } // end of QCrouzeixRaviartElements
 } // end_of_main
References oomph::DocInfo::directory(), MergeRestartFiles::filename, oomph::DocInfo::number(), problem, oomph::Z2ErrorEstimator::reference_flux_norm(), oomph::DocInfo::set_directory(), oomph::Node::value(), and oomph::Node::x().