MercuryDPM: Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device > Struct Template Reference
#include <TensorFFT.h>
Public Types
enum {
IsAligned = false , PacketAccess = true , BlockAccess = false , PreferBlockAccess = false ,
CoordAccess = false , RawAccess = false
}
typedef TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir > XprType
typedef XprType::Index Index
typedef DSizes< Index, NumDims > Dimensions
typedef XprType::Scalar Scalar
typedef Eigen::NumTraits< Scalar >::Real RealScalar
typedef std::complex< RealScalar > ComplexScalar
typedef TensorEvaluator< ArgType, Device >::Dimensions InputDimensions
typedef internal::traits< XprType > XprTraits
typedef XprTraits::Scalar InputScalar
typedef std::conditional_t< FFTResultType==RealPart||FFTResultType==ImagPart, RealScalar, ComplexScalar > OutputScalar
typedef OutputScalar CoeffReturnType
typedef PacketType< OutputScalar, Device >::type PacketReturnType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorBlockNotImplemented TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType data)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EvaluatorPointerType data () const
Static Public Attributes
static constexpr int NumDims = internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value
static constexpr int PacketSize = internal::unpacket_traits<PacketReturnType>::size
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Protected Attributes
Index m_size
const FFT EIGEN_DEVICE_REF m_fft
Dimensions m_dimensions
array< Index, NumDims > m_strides
TensorEvaluator< ArgType, Device > m_impl
EvaluatorPointerType m_data
const Device EIGEN_DEVICE_REF m_device
const RealScalar m_sin_PI_div_n_LUT [32]
const RealScalar m_minus_sin_2_PI_div_n_LUT [32]
Private Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void evalToBuf (EvaluatorPointerType data)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void processDataLineCooleyTukey (ComplexScalar *line_buf, Index line_len, Index log_len)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void processDataLineBluestein (ComplexScalar *line_buf, Index line_len, Index good_composite, Index log_len, ComplexScalar *a, ComplexScalar *b, const ComplexScalar *pos_j_base_powered)
template<int Dir>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void butterfly_2 (ComplexScalar *data)
template<int Dir>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void butterfly_4 (ComplexScalar *data)
template<int Dir>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void butterfly_8 (ComplexScalar *data)
template<int Dir>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void butterfly_1D_merge (ComplexScalar *data, Index n, Index n_power_of_2)
template<int Dir>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void compute_1D_Butterfly (ComplexScalar *data, Index n, Index n_power_of_2)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index getBaseOffsetFromIndex (Index index, Index omitted_dim) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index getIndexFromOffset (Index base, Index omitted_dim, Index offset) const
Static Private Member Functions
EIGEN_DEVICE_FUNC static EIGEN_STRONG_INLINE bool isPowerOfTwo (Index x)
EIGEN_DEVICE_FUNC static EIGEN_STRONG_INLINE Index findGoodComposite (Index n)
EIGEN_DEVICE_FUNC static EIGEN_STRONG_INLINE Index getLog2 (Index m)
EIGEN_DEVICE_FUNC static EIGEN_STRONG_INLINE void scramble_FFT (ComplexScalar *data, Index n)
Member Typedef Documentation
CoeffReturnType
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> typedef OutputScalar Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::CoeffReturnType
ComplexScalar
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> typedef std::complex<RealScalar> Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::ComplexScalar
Dimensions
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> typedef DSizes<Index, NumDims> Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::Dimensions
EvaluatorPointerType
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> typedef Storage::Type Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::EvaluatorPointerType
Index
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> typedef XprType::Index Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::Index
InputDimensions
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> typedef TensorEvaluator<ArgType, Device>::Dimensions Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::InputDimensions
InputScalar
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> typedef XprTraits::Scalar Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::InputScalar
OutputScalar
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> typedef std::conditional_t<FFTResultType == RealPart || FFTResultType == ImagPart, RealScalar, ComplexScalar> Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::OutputScalar
PacketReturnType
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> typedef PacketType<OutputScalar, Device>::type Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::PacketReturnType
RealScalar
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> typedef Eigen::NumTraits<Scalar>::Real Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::RealScalar
Scalar
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> typedef XprType::Scalar Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::Scalar
Storage
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::Storage
TensorBlock
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> typedef internal::TensorBlockNotImplemented Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::TensorBlock
XprTraits
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> typedef internal::traits<XprType> Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::XprTraits
XprType
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> typedef TensorFFTOp<FFT, ArgType, FFTResultType, FFTDir> Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = false,
     PacketAccess = true,
     BlockAccess = false,
     PreferBlockAccess = false,
     CoordAccess = false,
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_fft(op.fft()), m_impl(op.expression(), device), m_data(NULL), m_device(device) {
     const typename TensorEvaluator<ArgType, Device>::Dimensions& input_dims = m_impl.dimensions();
     for (int i = 0; i < NumDims; ++i) {
       eigen_assert(input_dims[i] > 0);
       m_dimensions[i] = input_dims[i];
     }
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       m_strides[0] = 1;
       for (int i = 1; i < NumDims; ++i) {
         m_strides[i] = m_strides[i - 1] * m_dimensions[i - 1];
       }
     } else {
       m_strides[NumDims - 1] = 1;
       for (int i = NumDims - 2; i >= 0; --i) {
         m_strides[i] = m_strides[i + 1] * m_dimensions[i + 1];
       }
     }
     m_size = m_dimensions.TotalSize();
   }
References Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), eigen_assert, i, and Eigen::TensorEvaluator< Derived, Device >::Layout.
Member Function Documentation
butterfly_1D_merge()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> template<int Dir> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::butterfly_1D_merge (ComplexScalar * data, Index n, Index n_power_of_2) inline private
{
     // Original code:
     // RealScalar wtemp = std::sin(M_PI/n);
     // RealScalar wpi =  -std::sin(2 * M_PI/n);
     const RealScalar wtemp = m_sin_PI_div_n_LUT[n_power_of_2];
     const RealScalar wpi =
         (Dir == FFT_FORWARD) ? m_minus_sin_2_PI_div_n_LUT[n_power_of_2] : -m_minus_sin_2_PI_div_n_LUT[n_power_of_2];
     const ComplexScalar wp(wtemp, wpi);
     const ComplexScalar wp_one = wp + ComplexScalar(1, 0);
     const ComplexScalar wp_one_2 = wp_one * wp_one;
     const ComplexScalar wp_one_3 = wp_one_2 * wp_one;
     const ComplexScalar wp_one_4 = wp_one_3 * wp_one;
     const Index n2 = n / 2;
     ComplexScalar w(1.0, 0.0);
     for (Index i = 0; i < n2; i += 4) {
       ComplexScalar temp0(data[i + n2] * w);
       ComplexScalar temp1(data[i + 1 + n2] * w * wp_one);
       ComplexScalar temp2(data[i + 2 + n2] * w * wp_one_2);
       ComplexScalar temp3(data[i + 3 + n2] * w * wp_one_3);
       w = w * wp_one_4;
       data[i + n2] = data[i] - temp0;
       data[i] += temp0;
       data[i + 1 + n2] = data[i + 1] - temp1;
       data[i + 1] += temp1;
       data[i + 2 + n2] = data[i + 2] - temp2;
       data[i + 2] += temp2;
       data[i + 3 + n2] = data[i + 3] - temp3;
       data[i + 3] += temp3;
     }
   }
References Eigen::TensorEvaluator< Derived, Device >::data(), Eigen::FFT_FORWARD, i, n, and w.
butterfly_2()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> template<int Dir> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::butterfly_2 (ComplexScalar * data) inline private
{
     ComplexScalar tmp = data[1];
     data[1] = data[0] - data[1];
     data[0] += tmp;
   }
References Eigen::TensorEvaluator< Derived, Device >::data(), and tmp.
butterfly_4()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> template<int Dir> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::butterfly_4 (ComplexScalar * data) inline private
{
     ComplexScalar tmp[4];
     tmp[0] = data[0] + data[1];
     tmp[1] = data[0] - data[1];
     tmp[2] = data[2] + data[3];
     if (Dir == FFT_FORWARD) {
       tmp[3] = ComplexScalar(0.0, -1.0) * (data[2] - data[3]);
     } else {
       tmp[3] = ComplexScalar(0.0, 1.0) * (data[2] - data[3]);
     }
     data[0] = tmp[0] + tmp[2];
     data[1] = tmp[1] + tmp[3];
     data[2] = tmp[0] - tmp[2];
     data[3] = tmp[1] - tmp[3];
   }
References Eigen::TensorEvaluator< Derived, Device >::data(), Eigen::FFT_FORWARD, and tmp.
butterfly_8()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> template<int Dir> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::butterfly_8 (ComplexScalar * data) inline private
{
     ComplexScalar tmp_1[8];
     ComplexScalar tmp_2[8];
     tmp_1[0] = data[0] + data[1];
     tmp_1[1] = data[0] - data[1];
     tmp_1[2] = data[2] + data[3];
     if (Dir == FFT_FORWARD) {
       tmp_1[3] = (data[2] - data[3]) * ComplexScalar(0, -1);
     } else {
       tmp_1[3] = (data[2] - data[3]) * ComplexScalar(0, 1);
     }
     tmp_1[4] = data[4] + data[5];
     tmp_1[5] = data[4] - data[5];
     tmp_1[6] = data[6] + data[7];
     if (Dir == FFT_FORWARD) {
       tmp_1[7] = (data[6] - data[7]) * ComplexScalar(0, -1);
     } else {
       tmp_1[7] = (data[6] - data[7]) * ComplexScalar(0, 1);
     }
     tmp_2[0] = tmp_1[0] + tmp_1[2];
     tmp_2[1] = tmp_1[1] + tmp_1[3];
     tmp_2[2] = tmp_1[0] - tmp_1[2];
     tmp_2[3] = tmp_1[1] - tmp_1[3];
     tmp_2[4] = tmp_1[4] + tmp_1[6];
 // SQRT2DIV2 = sqrt(2)/2
 #define SQRT2DIV2 0.7071067811865476
     if (Dir == FFT_FORWARD) {
       tmp_2[5] = (tmp_1[5] + tmp_1[7]) * ComplexScalar(SQRT2DIV2, -SQRT2DIV2);
       tmp_2[6] = (tmp_1[4] - tmp_1[6]) * ComplexScalar(0, -1);
       tmp_2[7] = (tmp_1[5] - tmp_1[7]) * ComplexScalar(-SQRT2DIV2, -SQRT2DIV2);
     } else {
       tmp_2[5] = (tmp_1[5] + tmp_1[7]) * ComplexScalar(SQRT2DIV2, SQRT2DIV2);
       tmp_2[6] = (tmp_1[4] - tmp_1[6]) * ComplexScalar(0, 1);
       tmp_2[7] = (tmp_1[5] - tmp_1[7]) * ComplexScalar(-SQRT2DIV2, SQRT2DIV2);
     }
     data[0] = tmp_2[0] + tmp_2[4];
     data[1] = tmp_2[1] + tmp_2[5];
     data[2] = tmp_2[2] + tmp_2[6];
     data[3] = tmp_2[3] + tmp_2[7];
     data[4] = tmp_2[0] - tmp_2[4];
     data[5] = tmp_2[1] - tmp_2[5];
     data[6] = tmp_2[2] - tmp_2[6];
     data[7] = tmp_2[3] - tmp_2[7];
   }
References Eigen::TensorEvaluator< Derived, Device >::data(), Eigen::FFT_FORWARD, and SQRT2DIV2.
cleanup()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::cleanup () inline
{
     if (m_data) {
       m_device.deallocate(m_data);
       m_data = NULL;
     }
     m_impl.cleanup();
   }
References Eigen::TensorEvaluator< Derived, Device >::m_data, and Eigen::TensorEvaluator< Derived, Device >::m_device.
Referenced by framework.Frame::__init__().
coeff()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::coeff (Index index) const inline
 { return m_data[index]; }
References Eigen::TensorEvaluator< Derived, Device >::m_data.
compute_1D_Butterfly()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> template<int Dir> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::compute_1D_Butterfly (ComplexScalar * data, Index n, Index n_power_of_2) inline private
{
     eigen_assert(isPowerOfTwo(n));
     if (n > 8) {
       compute_1D_Butterfly<Dir>(data, n / 2, n_power_of_2 - 1);
       compute_1D_Butterfly<Dir>(data + n / 2, n / 2, n_power_of_2 - 1);
       butterfly_1D_merge<Dir>(data, n, n_power_of_2);
     } else if (n == 8) {
       butterfly_8<Dir>(data);
     } else if (n == 4) {
       butterfly_4<Dir>(data);
     } else if (n == 2) {
       butterfly_2<Dir>(data);
     }
   }
References Eigen::TensorEvaluator< Derived, Device >::data(), eigen_assert, and n.
costPerCoeff()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::costPerCoeff (bool vectorized) const inline
{
     return TensorOpCost(sizeof(CoeffReturnType), 0, 0, vectorized, PacketSize);
   }
References Eigen::TensorEvaluator< Derived, Device >::PacketSize.
data()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> EIGEN_DEVICE_FUNC EvaluatorPointerType Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::data () const inline
 { return m_data; }
References Eigen::TensorEvaluator< Derived, Device >::m_data.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::dimensions () const inline
 { return m_dimensions; }
evalSubExprsIfNeeded()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType data) inline
{
     m_impl.evalSubExprsIfNeeded(NULL);
     if (data) {
       evalToBuf(data);
       return false;
     } else {
       m_data = (EvaluatorPointerType)m_device.get(
           (CoeffReturnType*)(m_device.allocate_temp(sizeof(CoeffReturnType) * m_size)));
       evalToBuf(m_data);
       return true;
     }
   }
References Eigen::TensorEvaluator< Derived, Device >::data(), Eigen::TensorEvaluator< Derived, Device >::m_data, and Eigen::TensorEvaluator< Derived, Device >::m_device.
evalToBuf()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::evalToBuf (EvaluatorPointerType data) inline private
{
     const bool write_to_out = internal::is_same<OutputScalar, ComplexScalar>::value;
     ComplexScalar* buf =
         write_to_out ? (ComplexScalar*)data : (ComplexScalar*)m_device.allocate(sizeof(ComplexScalar) * m_size);
     for (Index i = 0; i < m_size; ++i) {
       buf[i] = MakeComplex<internal::is_same<InputScalar, RealScalar>::value>()(m_impl.coeff(i));
     }
     for (size_t i = 0; i < m_fft.size(); ++i) {
       Index dim = m_fft[i];
       eigen_assert(dim >= 0 && dim < NumDims);
       Index line_len = m_dimensions[dim];
       eigen_assert(line_len >= 1);
       ComplexScalar* line_buf = (ComplexScalar*)m_device.allocate(sizeof(ComplexScalar) * line_len);
       const bool is_power_of_two = isPowerOfTwo(line_len);
       const Index good_composite = is_power_of_two ? 0 : findGoodComposite(line_len);
       const Index log_len = is_power_of_two ? getLog2(line_len) : getLog2(good_composite);
       ComplexScalar* a =
           is_power_of_two ? NULL : (ComplexScalar*)m_device.allocate(sizeof(ComplexScalar) * good_composite);
       ComplexScalar* b =
           is_power_of_two ? NULL : (ComplexScalar*)m_device.allocate(sizeof(ComplexScalar) * good_composite);
       ComplexScalar* pos_j_base_powered =
           is_power_of_two ? NULL : (ComplexScalar*)m_device.allocate(sizeof(ComplexScalar) * (line_len + 1));
       if (!is_power_of_two) {
         // Compute twiddle factors
         //   t_n = exp(sqrt(-1) * pi * n^2 / line_len)
         // for n = 0, 1,..., line_len-1.
         // For n > 2 we use the recurrence t_n = t_{n-1}^2 / t_{n-2} * t_1^2
         // The recurrence is correct in exact arithmetic, but causes
         // numerical issues for large transforms, especially in
         // single-precision floating point.
         //
         // pos_j_base_powered[0] = ComplexScalar(1, 0);
         // if (line_len > 1) {
         //   const ComplexScalar pos_j_base = ComplexScalar(
         //       numext::cos(M_PI / line_len), numext::sin(M_PI / line_len));
         //   pos_j_base_powered[1] = pos_j_base;
         //   if (line_len > 2) {
         //     const ComplexScalar pos_j_base_sq = pos_j_base * pos_j_base;
         //     for (int i = 2; i < line_len + 1; ++i) {
         //       pos_j_base_powered[i] = pos_j_base_powered[i - 1] *
         //           pos_j_base_powered[i - 1] /
         //           pos_j_base_powered[i - 2] *
         //           pos_j_base_sq;
         //     }
         //   }
         // }
         // TODO(rmlarsen): Find a way to use Eigen's vectorized sin
         // and cosine functions here.
         for (int j = 0; j < line_len + 1; ++j) {
           double arg = ((EIGEN_PI * j) * j) / line_len;
           std::complex<double> tmp(numext::cos(arg), numext::sin(arg));
           pos_j_base_powered[j] = static_cast<ComplexScalar>(tmp);
         }
       }
       for (Index partial_index = 0; partial_index < m_size / line_len; ++partial_index) {
         const Index base_offset = getBaseOffsetFromIndex(partial_index, dim);
         // get data into line_buf
         const Index stride = m_strides[dim];
         if (stride == 1) {
           m_device.memcpy(line_buf, &buf[base_offset], line_len * sizeof(ComplexScalar));
         } else {
           Index offset = base_offset;
           for (int j = 0; j < line_len; ++j, offset += stride) {
             line_buf[j] = buf[offset];
           }
         }
         // process the line
         if (is_power_of_two) {
           processDataLineCooleyTukey(line_buf, line_len, log_len);
         } else {
           processDataLineBluestein(line_buf, line_len, good_composite, log_len, a, b, pos_j_base_powered);
         }
         // write back
         if (FFTDir == FFT_FORWARD && stride == 1) {
           m_device.memcpy(&buf[base_offset], line_buf, line_len * sizeof(ComplexScalar));
         } else {
           Index offset = base_offset;
           const ComplexScalar div_factor = ComplexScalar(1.0 / line_len, 0);
           for (int j = 0; j < line_len; ++j, offset += stride) {
             buf[offset] = (FFTDir == FFT_FORWARD) ? line_buf[j] : line_buf[j] * div_factor;
           }
         }
       }
       m_device.deallocate(line_buf);
       if (!is_power_of_two) {
         m_device.deallocate(a);
         m_device.deallocate(b);
         m_device.deallocate(pos_j_base_powered);
       }
     }
     if (!write_to_out) {
       for (Index i = 0; i < m_size; ++i) {
         data[i] = PartOf<FFTResultType>()(buf[i]);
       }
       m_device.deallocate(buf);
     }
   }
References a, b, Eigen::numext::cos(), Eigen::TensorEvaluator< Derived, Device >::data(), eigen_assert, EIGEN_PI, Eigen::FFT_FORWARD, i, j, Eigen::TensorEvaluator< Derived, Device >::m_device, Eigen::numext::sin(), and tmp.
findGoodComposite()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> EIGEN_DEVICE_FUNC static EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::findGoodComposite (Index n) inline static private
{
     Index i = 2;
     while (i < 2 * n - 1) i *= 2;
     return i;
   }
References i, and n.
getBaseOffsetFromIndex()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::getBaseOffsetFromIndex (Index index, Index omitted_dim) const inline private
{
     Index result = 0;
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       for (int i = NumDims - 1; i > omitted_dim; --i) {
         const Index partial_m_stride = m_strides[i] / m_dimensions[omitted_dim];
         const Index idx = index / partial_m_stride;
         index -= idx * partial_m_stride;
         result += idx * m_strides[i];
       }
       result += index;
     } else {
       for (Index i = 0; i < omitted_dim; ++i) {
         const Index partial_m_stride = m_strides[i] / m_dimensions[omitted_dim];
         const Index idx = index / partial_m_stride;
         index -= idx * partial_m_stride;
         result += idx * m_strides[i];
       }
       result += index;
     }
     // Value of index_coords[omitted_dim] is not determined to this step
     return result;
   }
References Eigen::ColMajor, i, and Eigen::TensorEvaluator< Derived, Device >::Layout.
getIndexFromOffset()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::getIndexFromOffset (Index base, Index omitted_dim, Index offset) const inline private
{
     Index result = base + offset * m_strides[omitted_dim];
     return result;
   }
getLog2()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> EIGEN_DEVICE_FUNC static EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::getLog2 (Index m) inline static private
{
     Index log2m = 0;
     while (m >>= 1) log2m++;
     return log2m;
   }
References m.
isPowerOfTwo()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> EIGEN_DEVICE_FUNC static EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::isPowerOfTwo (Index x) inline static private
{
     eigen_assert(x > 0);
     return !(x & (x - 1));
   }
References eigen_assert, and plotDoE::x.
packet()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::packet (Index index) const inline
{
     return internal::ploadt<PacketReturnType, LoadMode>(m_data + index);
   }
References Eigen::TensorEvaluator< Derived, Device >::m_data.
processDataLineBluestein()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::processDataLineBluestein (ComplexScalar * line_buf, Index line_len, Index good_composite, Index log_len, ComplexScalar * a, ComplexScalar * b, const ComplexScalar * pos_j_base_powered) inline private
{
     Index n = line_len;
     Index m = good_composite;
     ComplexScalar* data = line_buf;
     for (Index i = 0; i < n; ++i) {
       if (FFTDir == FFT_FORWARD) {
         a[i] = data[i] * numext::conj(pos_j_base_powered[i]);
       } else {
         a[i] = data[i] * pos_j_base_powered[i];
       }
     }
     for (Index i = n; i < m; ++i) {
       a[i] = ComplexScalar(0, 0);
     }
     for (Index i = 0; i < n; ++i) {
       if (FFTDir == FFT_FORWARD) {
         b[i] = pos_j_base_powered[i];
       } else {
         b[i] = numext::conj(pos_j_base_powered[i]);
       }
     }
     for (Index i = n; i < m - n; ++i) {
       b[i] = ComplexScalar(0, 0);
     }
     for (Index i = m - n; i < m; ++i) {
       if (FFTDir == FFT_FORWARD) {
         b[i] = pos_j_base_powered[m - i];
       } else {
         b[i] = numext::conj(pos_j_base_powered[m - i]);
       }
     }
     scramble_FFT(a, m);
     compute_1D_Butterfly<FFT_FORWARD>(a, m, log_len);
     scramble_FFT(b, m);
     compute_1D_Butterfly<FFT_FORWARD>(b, m, log_len);
     for (Index i = 0; i < m; ++i) {
       a[i] *= b[i];
     }
     scramble_FFT(a, m);
     compute_1D_Butterfly<FFT_REVERSE>(a, m, log_len);
     // Do the scaling after ifft
     for (Index i = 0; i < m; ++i) {
       a[i] /= m;
     }
     for (Index i = 0; i < n; ++i) {
       if (FFTDir == FFT_FORWARD) {
         data[i] = a[i] * numext::conj(pos_j_base_powered[i]);
       } else {
         data[i] = a[i] * pos_j_base_powered[i];
       }
     }
   }
References a, b, conj(), Eigen::TensorEvaluator< Derived, Device >::data(), Eigen::FFT_FORWARD, i, m, and n.
processDataLineCooleyTukey()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::processDataLineCooleyTukey (ComplexScalar * line_buf, Index line_len, Index log_len) inline private
{
     eigen_assert(isPowerOfTwo(line_len));
     scramble_FFT(line_buf, line_len);
     compute_1D_Butterfly<FFTDir>(line_buf, line_len, log_len);
   }
References eigen_assert.
scramble_FFT()
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> EIGEN_DEVICE_FUNC static EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::scramble_FFT (ComplexScalar * data, Index n) inline static private
{
     eigen_assert(isPowerOfTwo(n));
     Index j = 1;
     for (Index i = 1; i < n; ++i) {
       if (j > i) {
         std::swap(data[j - 1], data[i - 1]);
       }
       Index m = n >> 1;
       while (m >= 2 && j > m) {
         j -= m;
         m >>= 1;
       }
       j += m;
     }
   }
References Eigen::TensorEvaluator< Derived, Device >::data(), eigen_assert, i, j, m, n, and swap().
Member Data Documentation
Layout
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> constexpr int Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_data
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> EvaluatorPointerType Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::m_data protected
m_device
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> const Device EIGEN_DEVICE_REF Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::m_device protected
m_dimensions
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> Dimensions Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::m_dimensions protected
m_fft
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> const FFT EIGEN_DEVICE_REF Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::m_fft protected
m_impl
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::m_impl protected
m_minus_sin_2_PI_div_n_LUT
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> const RealScalar Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::m_minus_sin_2_PI_div_n_LUT[32] protected
m_sin_PI_div_n_LUT
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> const RealScalar Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::m_sin_PI_div_n_LUT[32] protected
m_size
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> Index Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::m_size protected
m_strides
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> array<Index, NumDims> Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::m_strides protected
NumDims
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> constexpr int Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::NumDims = internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value static constexpr
PacketSize
template<typename FFT , typename ArgType , typename Device , int FFTResultType, int FFTDir> constexpr int Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::PacketSize = internal::unpacket_traits<PacketReturnType>::size static constexpr
The documentation for this struct was generated from the following file:
TensorFFT.h