MercuryDPM: Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::DisjointSet Struct Reference
Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::DisjointSet Struct Reference
#include <SimplicialCholesky_impl.h>
Public Member Functions
DisjointSet (StorageIndex *set, StorageIndex size)
StorageIndex find (StorageIndex u) const
void compress (StorageIndex u, StorageIndex v)
Public Attributes
StorageIndex * m_set
Constructor & Destructor Documentation
DisjointSet()
template<typename Scalar , typename StorageIndex > Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::DisjointSet::DisjointSet (StorageIndex * set, StorageIndex size) inline
 : m_set(set) { std::iota(set, set + size, 0); }
References set(), and size.
Member Function Documentation
compress()
template<typename Scalar , typename StorageIndex > void Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::DisjointSet::compress (StorageIndex u, StorageIndex v) inline
{
       eigen_assert(u != kEmpty);
       eigen_assert(v != kEmpty);
       while (m_set[u] != v) {
         StorageIndex next = m_set[u];
         m_set[u] = v;
         u = next;
       }
     };
References eigen_assert, Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::kEmpty, Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::DisjointSet::m_set, and v.
Referenced by Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::calc_etree().
find()
template<typename Scalar , typename StorageIndex > StorageIndex Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::DisjointSet::find (StorageIndex u) const inline
{
       eigen_assert(u != kEmpty);
       while (m_set[u] != u) {
         // manually unroll the loop by a factor of 2 to improve performance
         u = m_set[m_set[u]];
       }
       return u;
     }
References eigen_assert, Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::kEmpty, and Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::DisjointSet::m_set.
Referenced by Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::calc_etree().
Member Data Documentation
m_set
template<typename Scalar , typename StorageIndex > StorageIndex* Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::DisjointSet::m_set
Referenced by Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::DisjointSet::compress(), and Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::DisjointSet::find().
The documentation for this struct was generated from the following file:
SimplicialCholesky_impl.h