MercuryDPM: LiquidBridgeBagheriSpecies Class Reference
LiquidBridgeBagheriSpecies Class Reference
LiquidBridgeBagheriSpecies contains the parameters used to describe a short-range force caused by liquid bridges.
#include <LiquidBridgeBagheriSpecies.h>
Public Types
typedef LiquidBridgeBagheriInteraction InteractionType
The correct Interaction type for this AdhesiveForceSpecies.
Public Member Functions
LiquidBridgeBagheriSpecies ()
The default constructor.
LiquidBridgeBagheriSpecies (const LiquidBridgeBagheriSpecies &s)
The default copy constructor.
~LiquidBridgeBagheriSpecies ()
The default destructor.
void read (std::istream &is)
Reads the species properties from an input stream.
void write (std::ostream &os) const
Writes the species properties to an output stream.
std::string getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
void mix (LiquidBridgeBagheriSpecies *S, LiquidBridgeBagheriSpecies *T)
creates default values for mixed species
void setInteractionDistance ()
void setLiquidBridgeVolume (Mdouble liquidBridgeVolume)
used to set the Volume of the liquid bridge.
Mdouble getLiquidBridgeVolume () const
used to access the Volume of the liquid bridge.
void setSurfaceTension (Mdouble surfaceTension)
used to set the surface tension of the liquid.
Mdouble getSurfaceTension () const
used to access the surface tension of the liquid.
void setContactAngle (Mdouble contactAngle)
used to set the contact angle between particle and liquid bridge surface.
Mdouble getContactAngle () const
used to access the contact angle between particle and liquid bridge surface.
void setMeanRadius (Mdouble meanRadius)
used to access the mean radius of the particle.
Mdouble getMeanRadius () const
used to access the mean radius of the particle.
Public Member Functions inherited from BaseForce
BaseSpecies * getBaseSpecies () const
void setBaseSpecies (BaseSpecies *baseSpecies)
Private Attributes
Mdouble liquidBridgeVolume_
Volume of the liquid bridge.
Mdouble cbrtLiquidBridgeVolume_
Cube root of the liquid bridge.
Mdouble contactAngle_
contact angle between particle and liquid bridge surface
Mdouble surfaceTension_
surface tension of the liquid
Mdouble meanRadius_
mean radius of the particles
Detailed Description
LiquidBridgeBagheriSpecies contains the parameters used to describe a short-range force caused by liquid bridges.
See LiquidBridgeBagheriInteraction::computeForce for a description of the force law.
Member Typedef Documentation
InteractionType
typedef LiquidBridgeBagheriInteraction LiquidBridgeBagheriSpecies::InteractionType
The correct Interaction type for this AdhesiveForceSpecies.
Constructor & Destructor Documentation
LiquidBridgeBagheriSpecies() [1/2]
LiquidBridgeBagheriSpecies::LiquidBridgeBagheriSpecies ()
The default constructor.
 {
     liquidBridgeVolume_ = 0;
     cbrtLiquidBridgeVolume_ = 0;
     surfaceTension_ = 0;
     contactAngle_ = 0;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"LiquidBridgeBagheriSpecies::LiquidBridgeBagheriSpecies() finished"<<std::endl;
 #endif
 }
References cbrtLiquidBridgeVolume_, contactAngle_, liquidBridgeVolume_, and surfaceTension_.
LiquidBridgeBagheriSpecies() [2/2]
LiquidBridgeBagheriSpecies::LiquidBridgeBagheriSpecies (const LiquidBridgeBagheriSpecies & s)
The default copy constructor.
Parameters
[in] the species that is copied
 {
     liquidBridgeVolume_ = s.liquidBridgeVolume_;
     cbrtLiquidBridgeVolume_ = s.cbrtLiquidBridgeVolume_;
     surfaceTension_ = s.surfaceTension_;
     contactAngle_ = s.contactAngle_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"LiquidBridgeBagheriSpecies::LiquidBridgeBagheriSpecies(const LiquidBridgeBagheriSpecies &p) finished"<<std::endl;
 #endif
 }
References cbrtLiquidBridgeVolume_, contactAngle_, liquidBridgeVolume_, s, and surfaceTension_.
~LiquidBridgeBagheriSpecies()
LiquidBridgeBagheriSpecies::~LiquidBridgeBagheriSpecies ()
The default destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"LiquidBridgeBagheriSpecies::~LiquidBridgeBagheriSpecies() finished"<<std::endl;
 #endif
 }
Member Function Documentation
getBaseName()
std::string LiquidBridgeBagheriSpecies::getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
Returns
a string containing the name of the species (minus the word "Species")
 {
     return "LiquidBridgeBagheri";
 }
getContactAngle()
Mdouble LiquidBridgeBagheriSpecies::getContactAngle () const
used to access the contact angle between particle and liquid bridge surface.
Returns
the contact angle between particle and liquid bridge surface.
 {
     return contactAngle_;
 }
References contactAngle_.
Referenced by LiquidBridgeBagheriInteraction::computeAdhesionForce().
getLiquidBridgeVolume()
Mdouble LiquidBridgeBagheriSpecies::getLiquidBridgeVolume () const
used to access the Volume of the liquid bridge.
Returns
the volume of the liquid bridge.
 {
     return liquidBridgeVolume_;
 }
References liquidBridgeVolume_.
Referenced by LiquidBridgeBagheriInteraction::computeAdhesionForce().
getMeanRadius()
Mdouble LiquidBridgeBagheriSpecies::getMeanRadius () const
used to access the mean radius of the particle.
getSurfaceTension()
Mdouble LiquidBridgeBagheriSpecies::getSurfaceTension () const
used to access the surface tension of the liquid.
Returns
the surface tension of the liquid.
 {
     return surfaceTension_;
 }
References surfaceTension_.
Referenced by LiquidBridgeBagheriInteraction::computeAdhesionForce().
mix()
void LiquidBridgeBagheriSpecies::mix (LiquidBridgeBagheriSpecies * S, LiquidBridgeBagheriSpecies * T)
creates default values for mixed species
For all parameters we assume that the harmonic mean of the parameters of the original two species is a sensible default.
Parameters
[in] S,T the two species whose properties are mixed to create the new species
 {
     liquidBridgeVolume_ = BaseSpecies::average(S->getLiquidBridgeVolume(), T->getLiquidBridgeVolume());
     cbrtLiquidBridgeVolume_ = cbrt(liquidBridgeVolume_);
     surfaceTension_ = BaseSpecies::average(S->getSurfaceTension(), T->getSurfaceTension());
     contactAngle_ = BaseSpecies::average(S->getContactAngle(), T->getContactAngle());
     setInteractionDistance();
 }
References BaseSpecies::average(), Eigen::numext::cbrt(), cbrtLiquidBridgeVolume_, contactAngle_, liquidBridgeVolume_, oomph::QuadTreeNames::S, setInteractionDistance(), and surfaceTension_.
read()
void LiquidBridgeBagheriSpecies::read (std::istream & is)
Reads the species properties from an input stream.
Parameters
[in] input stream (typically the restart file)
 {
     std::string dummy;
     is >> dummy >> liquidBridgeVolume_;
     cbrtLiquidBridgeVolume_ = cbrt(liquidBridgeVolume_);
     is >> dummy >> surfaceTension_;
     is >> dummy >> contactAngle_;
     setInteractionDistance();
 }
References Eigen::numext::cbrt(), cbrtLiquidBridgeVolume_, contactAngle_, liquidBridgeVolume_, setInteractionDistance(), oomph::Global_string_for_annotation::string(), and surfaceTension_.
setContactAngle()
void LiquidBridgeBagheriSpecies::setContactAngle (Mdouble contactAngle)
used to set the contact angle between particle and liquid bridge surface.
Parameters
[in] contactAngle the contact angle between particle and liquid bridge surface.
 {
     // Only allow contact angles which are valid according to https://doi.org/10.1007/s40571-024-00772-5
     // i.e. angles smaller than 50 degrees
     logger.assert_debug(contactAngle >= 0 && contactAngle <= constants::pi * 5.0 / 18.0, "LiquidBridgeBagheriSpecies::setContactAngle: Contact angle must be in the range [0, 5/18 pi]");
     contactAngle_ = contactAngle;
     setInteractionDistance();
 }
References contactAngle_, logger, constants::pi, and setInteractionDistance().
setInteractionDistance()
void LiquidBridgeBagheriSpecies::setInteractionDistance () virtual
Returns
the maximum separation distance below which adhesive forces can occur (needed for contact detection)
Reimplemented from BaseAdhesiveForce.
 {
     getBaseSpecies()->setInteractionDistance((1.0 + 0.5 * contactAngle_) * cbrtLiquidBridgeVolume_);
 }
References cbrtLiquidBridgeVolume_, contactAngle_, BaseForce::getBaseSpecies(), and BaseSpecies::setInteractionDistance().
Referenced by mix(), read(), setContactAngle(), and setLiquidBridgeVolume().
setLiquidBridgeVolume()
void LiquidBridgeBagheriSpecies::setLiquidBridgeVolume (Mdouble liquidBridgeVolume)
used to set the Volume of the liquid bridge.
Parameters
[in] liquidBridgeVolume the volume of the liquid bridge.
 {
     logger.assert_always(liquidBridgeVolume >= 0, "Error in setLiquidBridgeVolume(%), liquidBridgeVolume should be >= 0", liquidBridgeVolume);
     liquidBridgeVolume_ = liquidBridgeVolume;
     cbrtLiquidBridgeVolume_ = cbrt(liquidBridgeVolume);
     setInteractionDistance();
 }
References Eigen::numext::cbrt(), cbrtLiquidBridgeVolume_, liquidBridgeVolume_, logger, and setInteractionDistance().
setMeanRadius()
void LiquidBridgeBagheriSpecies::setMeanRadius (Mdouble meanRadius)
used to access the mean radius of the particle.
setSurfaceTension()
void LiquidBridgeBagheriSpecies::setSurfaceTension (Mdouble surfaceTension)
used to set the surface tension of the liquid.
Parameters
[in] surfaceTension the surface tension of the liquid.
 {
     logger.assert_always(surfaceTension >= 0, "Error in setSurfaceTension(%), surfaceTension should be >= 0", surfaceTension);
     surfaceTension_ = surfaceTension;
 }
References logger, and surfaceTension_.
write()
void LiquidBridgeBagheriSpecies::write (std::ostream & os) const
Writes the species properties to an output stream.
Parameters
[out] output stream (typically the restart file)
 {
     os << " liquidBridgeVolume " << liquidBridgeVolume_;
     os << " surfaceTension " << surfaceTension_;
     os << " contactAngle " << contactAngle_;
 }
References contactAngle_, liquidBridgeVolume_, and surfaceTension_.
Member Data Documentation
cbrtLiquidBridgeVolume_
Mdouble LiquidBridgeBagheriSpecies::cbrtLiquidBridgeVolume_ private
Cube root of the liquid bridge.
This is a slave variable of liquidBridgeVolume_ (i.e. it is always set together) but is useful, because the cube root has to be calculated to obtain the liquid bridge adhesive force.
Referenced by LiquidBridgeBagheriSpecies(), mix(), read(), setInteractionDistance(), and setLiquidBridgeVolume().
contactAngle_
Mdouble LiquidBridgeBagheriSpecies::contactAngle_ private
contact angle between particle and liquid bridge surface
Referenced by getContactAngle(), LiquidBridgeBagheriSpecies(), mix(), read(), setContactAngle(), setInteractionDistance(), and write().
liquidBridgeVolume_
Mdouble LiquidBridgeBagheriSpecies::liquidBridgeVolume_ private
Volume of the liquid bridge.
Currently, this is a Species property (i.e. all particles have the same liquid bridge volume), but this should probably become a Particle or Interaction property.
Referenced by getLiquidBridgeVolume(), LiquidBridgeBagheriSpecies(), mix(), read(), setLiquidBridgeVolume(), and write().
meanRadius_
Mdouble LiquidBridgeBagheriSpecies::meanRadius_ private
mean radius of the particles
surfaceTension_
Mdouble LiquidBridgeBagheriSpecies::surfaceTension_ private
surface tension of the liquid
Referenced by getSurfaceTension(), LiquidBridgeBagheriSpecies(), mix(), read(), setSurfaceTension(), and write().
The documentation for this class was generated from the following files:
LiquidBridgeBagheriSpecies.h
LiquidBridgeBagheriSpecies.cc