MercuryDPM: Eigen::internal::TensorPrinter< Tensor, rank, Format, EnableIf > Struct Template Reference
Eigen::internal::TensorPrinter< Tensor, rank, Format, EnableIf > Struct Template Reference
#include <TensorIO.h>
Public Types
using Scalar = std::remove_const_t< typename Tensor::Scalar >
Static Public Member Functions
static void run (std::ostream &s, const Tensor &tensor, const Format &fmt)
Member Typedef Documentation
Scalar
template<typename Tensor , std::size_t rank, typename Format , typename EnableIf > using Eigen::internal::TensorPrinter< Tensor, rank, Format, EnableIf >::Scalar = std::remove_const_t<typename Tensor::Scalar>
Member Function Documentation
run()
template<typename Tensor , std::size_t rank, typename Format , typename EnableIf > static void Eigen::internal::TensorPrinter< Tensor, rank, Format, EnableIf >::run (std::ostream & s, const Tensor & tensor, const Format & fmt) inline static
{
     typedef typename Tensor::Index IndexType;
     eigen_assert(Tensor::Layout == RowMajor);
     typedef std::conditional_t<is_same<Scalar, char>::value || is_same<Scalar, unsigned char>::value ||
                                    is_same<Scalar, numext::int8_t>::value || is_same<Scalar, numext::uint8_t>::value,
                                int,
                                std::conditional_t<is_same<Scalar, std::complex<char>>::value ||
                                                       is_same<Scalar, std::complex<unsigned char>>::value ||
                                                       is_same<Scalar, std::complex<numext::int8_t>>::value ||
                                                       is_same<Scalar, std::complex<numext::uint8_t>>::value,
                                                   std::complex<int>, const Scalar&>>
         PrintType;
     const IndexType total_size = array_prod(tensor.dimensions());
     std::streamsize explicit_precision;
     if (fmt.precision == StreamPrecision) {
       explicit_precision = 0;
     } else if (fmt.precision == FullPrecision) {
       if (NumTraits<Scalar>::IsInteger) {
         explicit_precision = 0;
       } else {
         explicit_precision = significant_decimals_impl<Scalar>::run();
       }
     } else {
       explicit_precision = fmt.precision;
     }
     std::streamsize old_precision = 0;
     if (explicit_precision) old_precision = s.precision(explicit_precision);
     IndexType width = 0;
     bool align_cols = !(fmt.flags & DontAlignCols);
     if (align_cols) {
       // compute the largest width
       for (IndexType i = 0; i < total_size; i++) {
         std::stringstream sstr;
         sstr.copyfmt(s);
         ScalarPrinter<Scalar, Format>::run(sstr, static_cast<PrintType>(tensor.data()[i]), fmt);
         width = std::max<IndexType>(width, IndexType(sstr.str().length()));
       }
     }
     s << fmt.tenPrefix;
     for (IndexType i = 0; i < total_size; i++) {
       std::array<bool, rank> is_at_end{};
       std::array<bool, rank> is_at_begin{};
       // is the ith element the end of an coeff (always true), of a row, of a matrix, ...?
       for (std::size_t k = 0; k < rank; k++) {
         if ((i + 1) % (std::accumulate(tensor.dimensions().rbegin(), tensor.dimensions().rbegin() + k, 1,
                                        std::multiplies<IndexType>())) ==
             0) {
           is_at_end[k] = true;
         }
       }
       // is the ith element the begin of an coeff (always true), of a row, of a matrix, ...?
       for (std::size_t k = 0; k < rank; k++) {
         if (i % (std::accumulate(tensor.dimensions().rbegin(), tensor.dimensions().rbegin() + k, 1,
                                  std::multiplies<IndexType>())) ==
             0) {
           is_at_begin[k] = true;
         }
       }
       // do we have a line break?
       bool is_at_begin_after_newline = false;
       for (std::size_t k = 0; k < rank; k++) {
         if (is_at_begin[k]) {
           std::size_t separator_index = (k < fmt.separator.size()) ? k : fmt.separator.size() - 1;
           if (fmt.separator[separator_index].find('\n') != std::string::npos) {
             is_at_begin_after_newline = true;
           }
         }
       }
       bool is_at_end_before_newline = false;
       for (std::size_t k = 0; k < rank; k++) {
         if (is_at_end[k]) {
           std::size_t separator_index = (k < fmt.separator.size()) ? k : fmt.separator.size() - 1;
           if (fmt.separator[separator_index].find('\n') != std::string::npos) {
             is_at_end_before_newline = true;
           }
         }
       }
       std::stringstream suffix, prefix, separator;
       for (std::size_t k = 0; k < rank; k++) {
         std::size_t suffix_index = (k < fmt.suffix.size()) ? k : fmt.suffix.size() - 1;
         if (is_at_end[k]) {
           suffix << fmt.suffix[suffix_index];
         }
       }
       for (std::size_t k = 0; k < rank; k++) {
         std::size_t separator_index = (k < fmt.separator.size()) ? k : fmt.separator.size() - 1;
         if (is_at_end[k] &&
             (!is_at_end_before_newline || fmt.separator[separator_index].find('\n') != std::string::npos)) {
           separator << fmt.separator[separator_index];
         }
       }
       for (std::size_t k = 0; k < rank; k++) {
         std::size_t spacer_index = (k < fmt.spacer.size()) ? k : fmt.spacer.size() - 1;
         if (i != 0 && is_at_begin_after_newline && (!is_at_begin[k] || k == 0)) {
           prefix << fmt.spacer[spacer_index];
         }
       }
       for (int k = rank - 1; k >= 0; k--) {
         std::size_t prefix_index = (static_cast<std::size_t>(k) < fmt.prefix.size()) ? k : fmt.prefix.size() - 1;
         if (is_at_begin[k]) {
           prefix << fmt.prefix[prefix_index];
         }
       }
       s << prefix.str();
       // So we don't mess around with formatting, output scalar to a string stream, and adjust the width/fill manually.
       std::stringstream sstr;
       sstr.copyfmt(s);
       ScalarPrinter<Scalar, Format>::run(sstr, static_cast<PrintType>(tensor.data()[i]), fmt);
       std::string scalar_str = sstr.str();
       IndexType scalar_width = scalar_str.length();
       if (width && scalar_width < width) {
         std::string filler;
         for (IndexType j = scalar_width; j < width; ++j) {
           filler.push_back(fmt.fill);
         }
         s << filler;
       }
       s << scalar_str;
       s << suffix.str();
       if (i < total_size - 1) {
         s << separator.str();
       }
     }
     s << fmt.tenSuffix;
     if (explicit_precision) s.precision(old_precision);
   }
References Eigen::internal::array_prod(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::data(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::dimensions(), Eigen::DontAlignCols, eigen_assert, Eigen::FullPrecision, i, int(), j, k, Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::Layout, Eigen::RowMajor, Eigen::internal::significant_decimals_impl< Scalar >::run(), Eigen::internal::ScalarPrinter< Scalar, Format, EnableIf >::run(), s, Eigen::StreamPrecision, oomph::Global_string_for_annotation::string(), and Eigen::value.
The documentation for this struct was generated from the following file:
TensorIO.h