MercuryDPM: Eigen::internal::unary_evaluator< IndexedView< ArgType, RowIndices, ColIndices >, IndexBased > Struct Template Reference
Eigen::internal::unary_evaluator< IndexedView< ArgType, RowIndices, ColIndices >, IndexBased > Struct Template Reference
#include <IndexedView.h>
Public Types
enum {
CoeffReadCost = evaluator<ArgType>::CoeffReadCost , FlagsLinearAccessBit , FlagsRowMajorBit = traits<XprType>::FlagsRowMajorBit , Flags ,
Alignment = 0
}
typedef IndexedView< ArgType, RowIndices, ColIndices > XprType
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
Public Types inherited from Eigen::internal::evaluator_base< IndexedView< ArgType, RowIndices, ColIndices > >
enum
typedef traits< IndexedView< ArgType, RowIndices, ColIndices > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC unary_evaluator (const XprType &xpr)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & coeffRef (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CoeffReturnType coeff (Index index) const
Public Member Functions inherited from Eigen::internal::evaluator_base< IndexedView< ArgType, RowIndices, ColIndices > >
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE evaluator_base ()=default
Protected Attributes
evaluator< ArgType > m_argImpl
const XprType & m_xpr
Member Typedef Documentation
CoeffReturnType
template<typename ArgType , typename RowIndices , typename ColIndices > typedef XprType::CoeffReturnType Eigen::internal::unary_evaluator< IndexedView< ArgType, RowIndices, ColIndices >, IndexBased >::CoeffReturnType
Scalar
template<typename ArgType , typename RowIndices , typename ColIndices > typedef XprType::Scalar Eigen::internal::unary_evaluator< IndexedView< ArgType, RowIndices, ColIndices >, IndexBased >::Scalar
XprType
template<typename ArgType , typename RowIndices , typename ColIndices > typedef IndexedView<ArgType, RowIndices, ColIndices> Eigen::internal::unary_evaluator< IndexedView< ArgType, RowIndices, ColIndices >, IndexBased >::XprType
Member Enumeration Documentation
anonymous enum
template<typename ArgType , typename RowIndices , typename ColIndices > anonymous enum
Enumerator
CoeffReadCost
FlagsLinearAccessBit
FlagsRowMajorBit
Flags
Alignment
        {
     CoeffReadCost = evaluator<ArgType>::CoeffReadCost /* TODO + cost of row/col index */,
     FlagsLinearAccessBit =
         (traits<XprType>::RowsAtCompileTime == 1 || traits<XprType>::ColsAtCompileTime == 1) ? LinearAccessBit : 0,
     FlagsRowMajorBit = traits<XprType>::FlagsRowMajorBit,
     Flags = (evaluator<ArgType>::Flags & (HereditaryBits & ~RowMajorBit /*| LinearAccessBit | DirectAccessBit*/)) |
             FlagsLinearAccessBit | FlagsRowMajorBit,
     Alignment = 0
   };
Constructor & Destructor Documentation
unary_evaluator()
template<typename ArgType , typename RowIndices , typename ColIndices > EIGEN_DEVICE_FUNC Eigen::internal::unary_evaluator< IndexedView< ArgType, RowIndices, ColIndices >, IndexBased >::unary_evaluator (const XprType & xpr) inline explicit
                                                                  : m_argImpl(xpr.nestedExpression()), m_xpr(xpr) {
     EIGEN_INTERNAL_CHECK_COST_VALUE(CoeffReadCost);
   }
References EIGEN_INTERNAL_CHECK_COST_VALUE.
Member Function Documentation
coeff() [1/2]
template<typename ArgType , typename RowIndices , typename ColIndices > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CoeffReturnType Eigen::internal::unary_evaluator< IndexedView< ArgType, RowIndices, ColIndices >, IndexBased >::coeff (Index index) const inline
{
     Index row = XprType::RowsAtCompileTime == 1 ? 0 : index;
     Index col = XprType::RowsAtCompileTime == 1 ? index : 0;
     eigen_assert(m_xpr.rowIndices()[row] >= 0 && m_xpr.rowIndices()[row] < m_xpr.nestedExpression().rows() &&
                  m_xpr.colIndices()[col] >= 0 && m_xpr.colIndices()[col] < m_xpr.nestedExpression().cols());
     return m_argImpl.coeff(m_xpr.rowIndices()[row], m_xpr.colIndices()[col]);
   }
References col(), eigen_assert, and row().
coeff() [2/2]
template<typename ArgType , typename RowIndices , typename ColIndices > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< IndexedView< ArgType, RowIndices, ColIndices >, IndexBased >::coeff (Index row, Index col) const inline
{
     eigen_assert(m_xpr.rowIndices()[row] >= 0 && m_xpr.rowIndices()[row] < m_xpr.nestedExpression().rows() &&
                  m_xpr.colIndices()[col] >= 0 && m_xpr.colIndices()[col] < m_xpr.nestedExpression().cols());
     return m_argImpl.coeff(m_xpr.rowIndices()[row], m_xpr.colIndices()[col]);
   }
References col(), eigen_assert, and row().
coeffRef() [1/3]
template<typename ArgType , typename RowIndices , typename ColIndices > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::unary_evaluator< IndexedView< ArgType, RowIndices, ColIndices >, IndexBased >::coeffRef (Index index) inline
{
     EIGEN_STATIC_ASSERT_LVALUE(XprType)
     Index row = XprType::RowsAtCompileTime == 1 ? 0 : index;
     Index col = XprType::RowsAtCompileTime == 1 ? index : 0;
     eigen_assert(m_xpr.rowIndices()[row] >= 0 && m_xpr.rowIndices()[row] < m_xpr.nestedExpression().rows() &&
                  m_xpr.colIndices()[col] >= 0 && m_xpr.colIndices()[col] < m_xpr.nestedExpression().cols());
     return m_argImpl.coeffRef(m_xpr.rowIndices()[row], m_xpr.colIndices()[col]);
   }
References col(), eigen_assert, EIGEN_STATIC_ASSERT_LVALUE, and row().
coeffRef() [2/3]
template<typename ArgType , typename RowIndices , typename ColIndices > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar& Eigen::internal::unary_evaluator< IndexedView< ArgType, RowIndices, ColIndices >, IndexBased >::coeffRef (Index index) const inline
{
     Index row = XprType::RowsAtCompileTime == 1 ? 0 : index;
     Index col = XprType::RowsAtCompileTime == 1 ? index : 0;
     eigen_assert(m_xpr.rowIndices()[row] >= 0 && m_xpr.rowIndices()[row] < m_xpr.nestedExpression().rows() &&
                  m_xpr.colIndices()[col] >= 0 && m_xpr.colIndices()[col] < m_xpr.nestedExpression().cols());
     return m_argImpl.coeffRef(m_xpr.rowIndices()[row], m_xpr.colIndices()[col]);
   }
References col(), eigen_assert, and row().
coeffRef() [3/3]
template<typename ArgType , typename RowIndices , typename ColIndices > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::unary_evaluator< IndexedView< ArgType, RowIndices, ColIndices >, IndexBased >::coeffRef (Index row, Index col) inline
{
     eigen_assert(m_xpr.rowIndices()[row] >= 0 && m_xpr.rowIndices()[row] < m_xpr.nestedExpression().rows() &&
                  m_xpr.colIndices()[col] >= 0 && m_xpr.colIndices()[col] < m_xpr.nestedExpression().cols());
     return m_argImpl.coeffRef(m_xpr.rowIndices()[row], m_xpr.colIndices()[col]);
   }
References col(), eigen_assert, and row().
Member Data Documentation
m_argImpl
template<typename ArgType , typename RowIndices , typename ColIndices > evaluator<ArgType> Eigen::internal::unary_evaluator< IndexedView< ArgType, RowIndices, ColIndices >, IndexBased >::m_argImpl protected
m_xpr
template<typename ArgType , typename RowIndices , typename ColIndices > const XprType& Eigen::internal::unary_evaluator< IndexedView< ArgType, RowIndices, ColIndices >, IndexBased >::m_xpr protected
The documentation for this struct was generated from the following file:
IndexedView.h