MercuryDPM: benchBlasGemm.cpp File Reference
benchBlasGemm.cpp File Reference
#include <iostream>
#include <Eigen/Core>
#include "BenchTimer.h"
#include <cblas.h>
#include <string>
Macros
#define _FLOAT
#define CBLAS_GEMM cblas_sgemm
#define MYVERIFY(A, M)
Typedefs
typedef float Scalar
typedef Eigen::Matrix< Scalar, Eigen::Dynamic, Eigen::Dynamic > MyMatrix
Functions
void bench_eigengemm (MyMatrix &mc, const MyMatrix &ma, const MyMatrix &mb, int nbloops)
void check_product (int M, int N, int K)
void check_product (void)
int main (int argc, char *argv[])
Macro Definition Documentation
_FLOAT
#define _FLOAT
CBLAS_GEMM
#define CBLAS_GEMM cblas_sgemm
MYVERIFY
#define MYVERIFY (A, M)
Value:
  if (!(A)) {                           \
    std::cout << "FAIL: " << M << "\n"; \
  }
Typedef Documentation
MyMatrix
typedef Eigen::Matrix<Scalar, Eigen::Dynamic, Eigen::Dynamic> MyMatrix
Scalar
typedef float Scalar
Function Documentation
bench_eigengemm()
void bench_eigengemm (MyMatrix & mc, const MyMatrix & ma, const MyMatrix & mb, int nbloops)
{
   for (uint j = 0; j < nbloops; ++j) mc.noalias() += ma * mb;
 }
References j.
Referenced by main().
check_product() [1/2]
void check_product (int M, int N, int K)
{
   MyMatrix ma(M, K), mb(K, N), mc(M, N), maT(K, M), mbT(N, K), meigen(M, N), mref(M, N);
   ma = MyMatrix::Random(M, K);
   mb = MyMatrix::Random(K, N);
   maT = ma.transpose();
   mbT = mb.transpose();
   mc = MyMatrix::Random(M, N);
   MyMatrix::Scalar eps = 1e-4;
   meigen = mref = mc;
   CBLAS_GEMM(CblasColMajor, CblasNoTrans, CblasNoTrans, M, N, K, 1, ma.data(), M, mb.data(), K, 1, mref.data(), M);
   meigen += ma * mb;
   MYVERIFY(meigen.isApprox(mref, eps), ". * .");
   meigen = mref = mc;
   CBLAS_GEMM(CblasColMajor, CblasTrans, CblasNoTrans, M, N, K, 1, maT.data(), K, mb.data(), K, 1, mref.data(), M);
   meigen += maT.transpose() * mb;
   MYVERIFY(meigen.isApprox(mref, eps), "T * .");
   meigen = mref = mc;
   CBLAS_GEMM(CblasColMajor, CblasTrans, CblasTrans, M, N, K, 1, maT.data(), K, mbT.data(), N, 1, mref.data(), M);
   meigen += (maT.transpose()) * (mbT.transpose());
   MYVERIFY(meigen.isApprox(mref, eps), "T * T");
   meigen = mref = mc;
   CBLAS_GEMM(CblasColMajor, CblasNoTrans, CblasTrans, M, N, K, 1, ma.data(), M, mbT.data(), N, 1, mref.data(), M);
   meigen += ma * mbT.transpose();
   MYVERIFY(meigen.isApprox(mref, eps), ". * T");
 }
References CBLAS_GEMM, Eigen::PlainObjectBase< Derived >::data(), e(), CRBond_Bessel::eps, PlanarWave::K, MYVERIFY, and N.
Referenced by check_product(), and main().
check_product() [2/2]
void check_product (void)
{
   int M, N, K;
   for (uint i = 0; i < 1000; ++i) {
     M = internal::random<int>(1, 64);
     N = internal::random<int>(1, 768);
     K = internal::random<int>(1, 768);
     M = (0 + M) * 1;
     std::cout << M << " x " << N << " x " << K << "\n";
     check_product(M, N, K);
   }
 }
References check_product(), i, PlanarWave::K, and N.
main()
int main (int argc , char * argv[])
{
 // disable SSE exceptions
 #ifdef __GNUC__
   {
     int aux;
     asm("stmxcsr   %[aux]           \n\t"
         "orl       $32832, %[aux]   \n\t"
         "ldmxcsr   %[aux]           \n\t"
         :
         : [aux] "m"(aux));
   }
 #endif
   int nbtries = 1, nbloops = 1, M, N, K;
   if (argc == 2) {
     if (std::string(argv[1]) == "check")
       check_product();
     else
       M = N = K = atoi(argv[1]);
   } else if ((argc == 3) && (std::string(argv[1]) == "auto")) {
     M = N = K = atoi(argv[2]);
     nbloops = 1000000000 / (M * M * M);
     if (nbloops < 1) nbloops = 1;
     nbtries = 6;
   } else if (argc == 4) {
     M = N = K = atoi(argv[1]);
     nbloops = atoi(argv[2]);
     nbtries = atoi(argv[3]);
   } else if (argc == 6) {
     M = atoi(argv[1]);
     N = atoi(argv[2]);
     K = atoi(argv[3]);
     nbloops = atoi(argv[4]);
     nbtries = atoi(argv[5]);
   } else {
     std::cout << "Usage: " << argv[0] << " size  \n";
     std::cout << "Usage: " << argv[0] << " auto size\n";
     std::cout << "Usage: " << argv[0] << " size nbloops nbtries\n";
     std::cout << "Usage: " << argv[0] << " M N K nbloops nbtries\n";
     std::cout << "Usage: " << argv[0] << " check\n";
     std::cout << "Options:\n";
     std::cout << "    size       unique size of the 2 matrices (integer)\n";
     std::cout << "    auto       automatically set the number of repetitions and tries\n";
     std::cout << "    nbloops    number of times the GEMM routines is executed\n";
     std::cout << "    nbtries    number of times the loop is benched (return the best try)\n";
     std::cout << "    M N K      sizes of the matrices: MxN  =  MxK * KxN (integers)\n";
     std::cout << "    check      check eigen product using cblas as a reference\n";
     exit(1);
   }
   double nbmad = double(M) * double(N) * double(K) * double(nbloops);
   if (!(std::string(argv[1]) == "auto")) std::cout << M << " x " << N << " x " << K << "\n";
   Scalar alpha, beta;
   MyMatrix ma(M, K), mb(K, N), mc(M, N);
   ma = MyMatrix::Random(M, K);
   mb = MyMatrix::Random(K, N);
   mc = MyMatrix::Random(M, N);
   Eigen::BenchTimer timer;
   // we simply compute c += a*b, so:
   alpha = 1;
   beta = 1;
   // bench cblas
   // ROWS_A, COLS_B, COLS_A, 1.0,  A, COLS_A, B, COLS_B, 0.0, C, COLS_B);
   if (!(std::string(argv[1]) == "auto")) {
     timer.reset();
     for (uint k = 0; k < nbtries; ++k) {
       timer.start();
       for (uint j = 0; j < nbloops; ++j)
 #ifdef EIGEN_DEFAULT_TO_ROW_MAJOR
         CBLAS_GEMM(CblasRowMajor, CblasNoTrans, CblasNoTrans, M, N, K, alpha, ma.data(), K, mb.data(), N, beta,
                    mc.data(), N);
 #else
         CBLAS_GEMM(CblasColMajor, CblasNoTrans, CblasNoTrans, M, N, K, alpha, ma.data(), M, mb.data(), K, beta,
                    mc.data(), M);
 #endif
       timer.stop();
     }
     if (!(std::string(argv[1]) == "auto"))
       std::cout << "cblas: " << timer.value() << " (" << 1e-3 * floor(1e-6 * nbmad / timer.value()) << " GFlops/s)\n";
     else
       std::cout << M << " : " << timer.value() << " ; " << 1e-3 * floor(1e-6 * nbmad / timer.value()) << "\n";
   }
   // clear
   ma = MyMatrix::Random(M, K);
   mb = MyMatrix::Random(K, N);
   mc = MyMatrix::Random(M, N);
   // eigen
   //   if (!(std::string(argv[1])=="auto"))
   {
     timer.reset();
     for (uint k = 0; k < nbtries; ++k) {
       timer.start();
       bench_eigengemm(mc, ma, mb, nbloops);
       timer.stop();
     }
     if (!(std::string(argv[1]) == "auto"))
       std::cout << "eigen : " << timer.value() << " (" << 1e-3 * floor(1e-6 * nbmad / timer.value()) << " GFlops/s)\n";
     else
       std::cout << M << " : " << timer.value() << " ; " << 1e-3 * floor(1e-6 * nbmad / timer.value()) << "\n";
   }
   std::cout << "l1: " << Eigen::l1CacheSize() << std::endl;
   std::cout << "l2: " << Eigen::l2CacheSize() << std::endl;
   return 0;
 }
References alpha, bench_eigengemm(), beta, CBLAS_GEMM, check_product(), Eigen::PlainObjectBase< Derived >::data(), e(), Eigen::bfloat16_impl::floor(), j, k, PlanarWave::K, Eigen::l1CacheSize(), Eigen::l2CacheSize(), N, and oomph::Global_string_for_annotation::string().