MercuryDPM: oomph::RefineableQElement< 2 > Class Reference
oomph::RefineableQElement< 2 > Class Reference abstract
#include <refineable_quad_element.h>
Public Types
typedef void(RefineableQElement< 2 >::* VoidMemberFctPt) ()
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Member Functions
RefineableQElement ()
Constructor: Pass refinement level (default 0 = root)
RefineableQElement (const RefineableQElement< 2 > &dummy)=delete
Broken copy constructor.
virtual ~RefineableQElement ()
Broken assignment operator.
unsigned required_nsons () const
A refineable quad element has four sons.
virtual Node * node_created_by_neighbour (const Vector< double > &s_fraction, bool &is_periodic)
virtual Node * node_created_by_son_of_neighbour (const Vector< double > &s_fraction, bool &is_periodic)
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)
void check_integrity (double &max_error)
void output_corners (std::ostream &outfile, const std::string &colour) const
Print corner nodes, use colour.
QuadTree * quadtree_pt ()
Pointer to quadtree representation of this element.
QuadTree * quadtree_pt () const
Pointer to quadtree representation of this element.
void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
virtual void further_setup_hanging_nodes ()=0
void get_boundaries (const int &edge, std::set< unsigned > &boundaries) const
void get_bcs (int bound, Vector< int > &bound_cons) const
void interpolated_zeta_on_edge (const unsigned &boundary, const int &edge, const Vector< double > &s, Vector< double > &zeta)
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void rebuild_from_sons (Mesh *&mesh_pt)=0
virtual void unbuild ()
virtual void deactivate_element ()
virtual bool nodes_built ()
Return true if all the nodes have been built, false if not.
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual unsigned ncont_interpolated_values () const =0
virtual void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
virtual void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)=0
virtual Node * interpolating_node_pt (const unsigned &n, const int &value_id)
virtual double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
virtual Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
virtual unsigned ninterpolating_node (const int &value_id)
virtual unsigned ninterpolating_node_1d (const int &value_id)
virtual void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual RefineableElement * root_element_pt ()
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
virtual void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
virtual void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
Pre-build the element.
virtual void further_build ()
Further build: e.g. deal with interpolation of internal values.
void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
unsigned nshape_controlling_nodes ()
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (std::ostream &outfile)
virtual void output (std::ostream &outfile, const unsigned &n_plot)
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output (FILE *file_pt)
virtual void output (FILE *file_pt, const unsigned &n_plot)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::QuadElementBase
QuadElementBase ()
Constructor. Empty.
virtual unsigned nvertex_node () const =0
Number of vertex nodes in the element.
virtual Node * vertex_node_pt (const unsigned &j) const =0
Pointer to the j-th vertex node in the element.
Public Member Functions inherited from oomph::QElementBase
QElementBase ()
Constructor: Initialise pointers to macro element reference coords.
QElementBase (const QElementBase &)=delete
Broken copy constructor.
virtual ~QElementBase ()
Broken assignment operator.
bool local_coord_is_valid (const Vector< double > &s)
Check whether the local coordinate are valid or not.
void move_local_coord_back_into_element (Vector< double > &s) const
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
double & s_macro_ll (const unsigned &i)
double & s_macro_ur (const unsigned &i)
double s_macro_ll (const unsigned &i) const
double s_macro_ur (const unsigned &i) const
void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
unsigned nnode_on_face () const
ElementGeometry::ElementGeometry element_geometry () const
It's a Q element!
Public Member Functions inherited from oomph::QElementGeometricBase
QElementGeometricBase ()
Empty default constructor.
QElementGeometricBase (const QElementGeometricBase &)=delete
Broken copy constructor.
Protected Member Functions
void setup_father_bounds ()
void get_edge_bcs (const int &edge, Vector< int > &bound_cons) const
Determine Vector of boundary conditions along edge (N/S/W/E)
void setup_hang_for_value (const int &value_id)
virtual void quad_hang_helper (const int &value_id, const int &my_edge, std::ofstream &output_hangfile)
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Static Protected Attributes
static std::map< unsigned, DenseMatrix< int > > Father_bound
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Additional Inherited Members
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number – for plotting/validation purposes.
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
Refineable version of QElement<2,NNODE_1D>.
Refinement is performed by quadtree procedures. When the element is subdivided, the geometry of its sons is established by calls to their father's
get_x(...)
function which refers to
the father element's geometric FE mapping (this is the default)
or
to a MacroElement 's MacroElement::macro_map (if the pointer to the macro element is non-NULL)
The class provides a generic RefineableQElement<2>::build() function which deals with generic isoparametric QElements in which all values are associated with nodes. The RefineableQElement<2>::further_build() function provides an interface for any element-specific non-generic build operations.
Member Typedef Documentation
VoidMemberFctPt
typedef void(RefineableQElement<2>::* oomph::RefineableQElement< 2 >::VoidMemberFctPt) ()
Shorthand for pointer to an argument-free void member function of the refineable element
Constructor & Destructor Documentation
RefineableQElement() [1/2]
oomph::RefineableQElement< 2 >::RefineableQElement () inline
Constructor: Pass refinement level (default 0 = root)
                          : RefineableElement()
     {
 #ifdef LEAK_CHECK
       LeakCheckNames::RefineableQElement<2> _build += 1;
 #endif
     }
RefineableQElement() [2/2]
oomph::RefineableQElement< 2 >::RefineableQElement (const RefineableQElement< 2 > & dummy) delete
Broken copy constructor.
~RefineableQElement()
virtual oomph::RefineableQElement< 2 >::~RefineableQElement () inline virtual
Broken assignment operator.
Destructor
     {
 #ifdef LEAK_CHECK
       LeakCheckNames::RefineableQElement<2> _build -= 1;
 #endif
     }
Member Function Documentation
build()
void oomph::RefineableQElement< 2 >::build (Mesh *& mesh_pt, Vector< Node * > & new_node_pt, bool & was_already_built, std::ofstream & new_nodes_file) virtual
Build the element, i.e. give it nodal positions, apply BCs, etc. Pointers to any new nodes will be returned in new_node_pt. If it is open, the positions of the new nodes will be written to the file stream new_nodes_file
Build the element by doing the following:
Give it nodal positions (by establishing the pointers to its nodes)
In the process create new nodes where required (i.e. if they don't exist in father element or have already been created while building new neighbour elements). Node building involves the following steps:
Get nodal position from father element.
Establish the time-history of the newly created nodal point (its coordinates and the previous values) consistent with the father's history.
Determine the boundary conditions of the nodes (newly created nodes can only lie on the interior of any edges of the father element – this makes it possible to to figure out what their bc should be...)
Add node to the mesh's stoarge scheme for the boundary nodes.
Add the new node to the mesh itself
Doc newly created nodes in "new_nodes.dat" stored in the directory of the DocInfo object (only if it's open!)
Finally, excute the element-specific further_build() (empty by default – must be overloaded for specific elements). This deals with any build operations that are not included in the generic process outlined above. For instance, in Crouzeix Raviart elements we need to initialise the internal pressure values in manner consistent with the pressure distribution in the father element.
Implements oomph::RefineableElement.
Reimplemented in oomph::RefineableSolidQElement< 2 >.
   {
     using namespace QuadTreeNames;
     // Get the number of 1d nodes
     unsigned n_p = nnode_1d();
     // Check whether static father_bound needs to be created
     if (Father_bound[n_p].nrow() == 0)
     {
       setup_father_bounds();
     }
     // Pointer to my father (in quadtree impersonation)
     QuadTree* father_pt = dynamic_cast<QuadTree*>(quadtree_pt()->father_pt());
     // What type of son am I? Ask my quadtree representation...
     int son_type = Tree_pt->son_type();
     // Has somebody build me already? (If any nodes have not been built)
     if (!nodes_built())
     {
 #ifdef PARANOID
       if (father_pt == 0)
       {
         std::string error_message =
           "Something fishy here: I have no father and yet \n";
         error_message += "I have no nodes. Who has created me then?!\n";
         throw OomphLibError(
           error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Indicate status:
       was_already_built = false;
       // Return pointer to father element
       RefineableQElement<2>* father_el_pt =
         dynamic_cast<RefineableQElement<2>*>(father_pt->object_pt());
       // Timestepper should be the same for all nodes in father
       // element -- use it create timesteppers for new nodes
       TimeStepper* time_stepper_pt =
         father_el_pt->node_pt(0)->time_stepper_pt();
       // Number of history values (incl. present)
       unsigned ntstorage = time_stepper_pt->ntstorage();
       // Currently we can't handle the case of generalised coordinates
       // since we haven't established how they should be interpolated
       // Buffer this case:
       if (father_el_pt->node_pt(0)->nposition_type() != 1)
       {
         throw OomphLibError("Can't handle generalised nodal positions (yet).",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       Vector<double> s_lo(2);
       Vector<double> s_hi(2);
       Vector<double> s(2);
       Vector<double> x(2);
       // Setup vertex coordinates in father element:
       //--------------------------------------------
       switch (son_type)
       {
         case SW:
           s_lo[0] = -1.0;
           s_hi[0] = 0.0;
           s_lo[1] = -1.0;
           s_hi[1] = 0.0;
           break;
         case SE:
           s_lo[0] = 0.0;
           s_hi[0] = 1.0;
           s_lo[1] = -1.0;
           s_hi[1] = 0.0;
           break;
         case NE:
           s_lo[0] = 0.0;
           s_hi[0] = 1.0;
           s_lo[1] = 0.0;
           s_hi[1] = 1.0;
           break;
         case NW:
           s_lo[0] = -1.0;
           s_hi[0] = 0.0;
           s_lo[1] = 0.0;
           s_hi[1] = 1.0;
           break;
       }
       // Pass macro element pointer on to sons and
       // set coordinates in macro element
       // hierher why can I see this?
       if (father_el_pt->Macro_elem_pt != 0)
       {
         set_macro_elem_pt(father_el_pt->Macro_elem_pt);
         for (unsigned i = 0; i < 2; i++)
         {
           s_macro_ll(i) =
             father_el_pt->s_macro_ll(i) +
             0.5 * (s_lo[i] + 1.0) *
               (father_el_pt->s_macro_ur(i) - father_el_pt->s_macro_ll(i));
           s_macro_ur(i) =
             father_el_pt->s_macro_ll(i) +
             0.5 * (s_hi[i] + 1.0) *
               (father_el_pt->s_macro_ur(i) - father_el_pt->s_macro_ll(i));
         }
       }
       // If the father element hasn't been generated yet, we're stuck...
       if (father_el_pt->node_pt(0) == 0)
       {
         throw OomphLibError(
           "Trouble: father_el_pt->node_pt(0)==0\n Can't build son element!\n",
           OOMPH_CURRENT_FUNCTION,
           OOMPH_EXCEPTION_LOCATION);
       }
       else
       {
         unsigned jnod = 0;
         Vector<double> x_small(2);
         Vector<double> x_large(2);
         Vector<double> s_fraction(2);
         // Loop over nodes in element
         for (unsigned i0 = 0; i0 < n_p; i0++)
         {
           // Get the fractional position of the node in the direction of s[0]
           s_fraction[0] = local_one_d_fraction_of_node(i0, 0);
           // Local coordinate in father element
           s[0] = s_lo[0] + (s_hi[0] - s_lo[0]) * s_fraction[0];
           for (unsigned i1 = 0; i1 < n_p; i1++)
           {
             // Get the fractional position of the node in the direction of s[1]
             s_fraction[1] = local_one_d_fraction_of_node(i1, 1);
             // Local coordinate in father element
             s[1] = s_lo[1] + (s_hi[1] - s_lo[1]) * s_fraction[1];
             // Local node number
             jnod = i0 + n_p * i1;
             // Check whether the father's node is periodic if so, complain
             /* {
              Node* father_node_pt = father_el_pt->node_pt(jnod);
              if((father_node_pt->is_a_copy()) ||
                 (father_node_pt->position_is_a_copy()))
               {
                throw OomphLibError(
                 "Can't handle periodic nodes (yet).",
                 OOMPH_CURRENT_FUNCTION,
                 OOMPH_EXCEPTION_LOCATION);
               }
               }*/
             // Initialise flag: So far, this node hasn't been built
             // or copied yet
             bool node_done = false;
             // Get the pointer to the node in the father, returns NULL
             // if there is not node
             Node* created_node_pt =
               father_el_pt->get_node_at_local_coordinate(s);
             // Does this node already exist in father element?
             //------------------------------------------------
             if (created_node_pt != 0)
             {
               // Copy node across
               node_pt(jnod) = created_node_pt;
               // Make sure that we update the values at the node so that
               // they are consistent with the present representation.
               // This is only need for mixed interpolation where the value
               // at the father could now become active.
               // Loop over all history values
               for (unsigned t = 0; t < ntstorage; t++)
               {
                 // Get values from father element
                 // Note: get_interpolated_values() sets Vector size itself.
                 Vector<double> prev_values;
                 father_el_pt->get_interpolated_values(t, s, prev_values);
                 // Find the minimum number of values
                 //(either those stored at the node, or those returned by
                 // the function)
                 unsigned n_val_at_node = created_node_pt->nvalue();
                 unsigned n_val_from_function = prev_values.size();
                 // Use the ternary conditional operator here
                 unsigned n_var = n_val_at_node < n_val_from_function ?
                                    n_val_at_node :
                                    n_val_from_function;
                 // Assign the values that we can
                 for (unsigned k = 0; k < n_var; k++)
                 {
                   created_node_pt->set_value(t, k, prev_values[k]);
                 }
               }
               // Node has been created by copy
               node_done = true;
             }
             // Node does not exist in father element but might already
             //--------------------------------------------------------
             // have been created by neighbouring elements
             //-------------------------------------------
             else
             {
               // Was the node created by one of its neighbours
               // Whether or not the node lies on an edge can be calculated
               // by from the fractional position
               bool is_periodic = false;
               ;
               created_node_pt =
                 node_created_by_neighbour(s_fraction, is_periodic);
               // If the node was so created, assign the pointers
               if (created_node_pt != 0)
               {
                 // If the node is periodic
                 if (is_periodic)
                 {
                   // Now the node must be on a boundary, but we don't know which
                   // one
                   // The returned created_node_pt is actually the neighbouring
                   // periodic node
                   Node* neighbour_node_pt = created_node_pt;
                   // Determine the edge on which the new node will live
                   int father_bound = Father_bound[n_p](jnod, son_type);
                   // Storage for the set of Mesh boundaries on which the
                   // appropriate father edge lives.
                   // [New nodes should always be mid-edge nodes in father
                   // and therefore only live on one boundary but just to
                   // play it safe...]
                   std::set<unsigned> boundaries;
                   // Only get the boundaries if we are at the edge of
                   // an element. Nodes in the centre of an element cannot be
                   // on Mesh boundaries
                   if (father_bound != Tree::OMEGA)
                   {
                     father_el_pt->get_boundaries(father_bound, boundaries);
                   }
 #ifdef PARANOID
                   // Case where a new node lives on more than one boundary
                   // seems fishy enough to flag
                   if (boundaries.size() > 1)
                   {
                     throw OomphLibError(
                       "boundaries.size()!=1 seems a bit strange..\n",
                       OOMPH_CURRENT_FUNCTION,
                       OOMPH_EXCEPTION_LOCATION);
                   }
                   // Case when there are no boundaries, we are in big trouble
                   if (boundaries.size() == 0)
                   {
                     std::ostringstream error_stream;
                     error_stream << "Periodic node is not on a boundary...\n"
                                  << "Coordinates: " << created_node_pt->x(0)
                                  << " " << created_node_pt->x(1) << "\n";
                     throw OomphLibError(error_stream.str(),
                                         OOMPH_CURRENT_FUNCTION,
                                         OOMPH_EXCEPTION_LOCATION);
                   }
 #endif
                   // Create node and set the pointer to it from the element
                   created_node_pt =
                     construct_boundary_node(jnod, time_stepper_pt);
                   // Make the node periodic from the neighbour
                   created_node_pt->make_periodic(neighbour_node_pt);
                   // Add to vector of new nodes
                   new_node_pt.push_back(created_node_pt);
                   // Loop over # of history values
                   for (unsigned t = 0; t < ntstorage; t++)
                   {
                     // Get position from father element -- this uses the macro
                     // element representation if appropriate. If the node
                     // turns out to be a hanging node later on, then
                     // its position gets adjusted in line with its
                     // hanging node interpolation.
                     Vector<double> x_prev(2);
                     father_el_pt->get_x(t, s, x_prev);
                     // Set previous positions of the new node
                     for (unsigned i = 0; i < 2; i++)
                     {
                       created_node_pt->x(t, i) = x_prev[i];
                     }
                   }
                   // Next, we Update the boundary lookup schemes
                   // Loop over the boundaries stored in the set
                   for (std::set<unsigned>::iterator it = boundaries.begin();
                        it != boundaries.end();
                        ++it)
                   {
                     // Add the node to the boundary
                     mesh_pt->add_boundary_node(*it, created_node_pt);
                     // If we have set an intrinsic coordinate on this
                     // mesh boundary then it must also be interpolated on
                     // the new node
                     // Now interpolate the intrinsic boundary coordinate
                     if (mesh_pt->boundary_coordinate_exists(*it) == true)
                     {
                       Vector<double> zeta(1);
                       father_el_pt->interpolated_zeta_on_edge(
                         *it, father_bound, s, zeta);
                       created_node_pt->set_coordinates_on_boundary(*it, zeta);
                     }
                   }
                   // Make sure that we add the node to the mesh
                   mesh_pt->add_node_pt(created_node_pt);
                 } // End of periodic case
                 // Otherwise the node is not periodic, so just set the
                 // pointer to the neighbours node
                 else
                 {
                   node_pt(jnod) = created_node_pt;
                 }
                 // Node has been created
                 node_done = true;
               }
               // Node does not exist in neighbour element but might already
               //-----------------------------------------------------------
               // have been created by a son of a neighbouring element
               //-----------------------------------------------------
               else
               {
                 // Was the node created by one of its neighbours' sons
                 // Whether or not the node lies on an edge can be calculated
                 // by from the fractional position
                 bool is_periodic = false;
                 ;
                 created_node_pt =
                   node_created_by_son_of_neighbour(s_fraction, is_periodic);
                 // If the node was so created, assign the pointers
                 if (created_node_pt != 0)
                 {
                   // If the node is periodic
                   if (is_periodic)
                   {
                     // Now the node must be on a boundary, but we don't know
                     // which one The returned created_node_pt is actually the
                     // neighbouring periodic node
                     Node* neighbour_node_pt = created_node_pt;
                     // Determine the edge on which the new node will live
                     int father_bound = Father_bound[n_p](jnod, son_type);
                     // Storage for the set of Mesh boundaries on which the
                     // appropriate father edge lives.
                     // [New nodes should always be mid-edge nodes in father
                     // and therefore only live on one boundary but just to
                     // play it safe...]
                     std::set<unsigned> boundaries;
                     // Only get the boundaries if we are at the edge of
                     // an element. Nodes in the centre of an element cannot be
                     // on Mesh boundaries
                     if (father_bound != Tree::OMEGA)
                     {
                       father_el_pt->get_boundaries(father_bound, boundaries);
                     }
 #ifdef PARANOID
                     // Case where a new node lives on more than one boundary
                     // seems fishy enough to flag
                     if (boundaries.size() > 1)
                     {
                       throw OomphLibError(
                         "boundaries.size()!=1 seems a bit strange..\n",
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
                     }
                     // Case when there are no boundaries, we are in big trouble
                     if (boundaries.size() == 0)
                     {
                       std::ostringstream error_stream;
                       error_stream << "Periodic node is not on a boundary...\n"
                                    << "Coordinates: " << created_node_pt->x(0)
                                    << " " << created_node_pt->x(1) << "\n";
                       throw OomphLibError(error_stream.str(),
                                           OOMPH_CURRENT_FUNCTION,
                                           OOMPH_EXCEPTION_LOCATION);
                     }
 #endif
                     // Create node and set the pointer to it from the element
                     created_node_pt =
                       construct_boundary_node(jnod, time_stepper_pt);
                     // Make the node periodic from the neighbour
                     created_node_pt->make_periodic(neighbour_node_pt);
                     // Add to vector of new nodes
                     new_node_pt.push_back(created_node_pt);
                     // Loop over # of history values
                     for (unsigned t = 0; t < ntstorage; t++)
                     {
                       // Get position from father element -- this uses the macro
                       // element representation if appropriate. If the node
                       // turns out to be a hanging node later on, then
                       // its position gets adjusted in line with its
                       // hanging node interpolation.
                       Vector<double> x_prev(2);
                       father_el_pt->get_x(t, s, x_prev);
                       // Set previous positions of the new node
                       for (unsigned i = 0; i < 2; i++)
                       {
                         created_node_pt->x(t, i) = x_prev[i];
                       }
                     }
                     // Next, we Update the boundary lookup schemes
                     // Loop over the boundaries stored in the set
                     for (std::set<unsigned>::iterator it = boundaries.begin();
                          it != boundaries.end();
                          ++it)
                     {
                       // Add the node to the boundary
                       mesh_pt->add_boundary_node(*it, created_node_pt);
                       // If we have set an intrinsic coordinate on this
                       // mesh boundary then it must also be interpolated on
                       // the new node
                       // Now interpolate the intrinsic boundary coordinate
                       if (mesh_pt->boundary_coordinate_exists(*it) == true)
                       {
                         Vector<double> zeta(1);
                         father_el_pt->interpolated_zeta_on_edge(
                           *it, father_bound, s, zeta);
                         created_node_pt->set_coordinates_on_boundary(*it, zeta);
                       }
                     }
                     // Make sure that we add the node to the mesh
                     mesh_pt->add_node_pt(created_node_pt);
                   } // End of periodic case
                   // Otherwise the node is not periodic, so just set the
                   // pointer to the neighbours node
                   else
                   {
                     node_pt(jnod) = created_node_pt;
                   }
                   // Node has been created
                   node_done = true;
                 } // Node does not exist in son of neighbouring element
               } // Node does not exist in neighbouring element
             } // Node does not exist in father element
             // Node has not been built anywhere ---> build it here
             if (!node_done)
             {
               // Firstly, we need to determine whether or not a node lies
               // on the boundary before building it, because
               // we actually assign a different type of node on boundaries.
               // The node can only be on a Mesh boundary if it
               // lives on an edge that is shared with an edge of its
               // father element; i.e. it is not created inside the father
               // element Determine the edge on which the new node will live
               int father_bound = Father_bound[n_p](jnod, son_type);
               // Storage for the set of Mesh boundaries on which the
               // appropriate father edge lives.
               // [New nodes should always be mid-edge nodes in father
               // and therefore only live on one boundary but just to
               // play it safe...]
               std::set<unsigned> boundaries;
               // Only get the boundaries if we are at the edge of
               // an element. Nodes in the centre of an element cannot be
               // on Mesh boundaries
               if (father_bound != Tree::OMEGA)
               {
                 father_el_pt->get_boundaries(father_bound, boundaries);
               }
 #ifdef PARANOID
               // Case where a new node lives on more than one boundary
               // seems fishy enough to flag
               if (boundaries.size() > 1)
               {
                 throw OomphLibError(
                   "boundaries.size()!=1 seems a bit strange..\n",
                   OOMPH_CURRENT_FUNCTION,
                   OOMPH_EXCEPTION_LOCATION);
               }
 #endif
               // If the node lives on a mesh boundary,
               // then we need to create a boundary node
               if (boundaries.size() > 0)
               {
                 // Create node and set the pointer to it from the element
                 created_node_pt =
                   construct_boundary_node(jnod, time_stepper_pt);
                 // Add to vector of new nodes
                 new_node_pt.push_back(created_node_pt);
                 // Now we need to work out whether to pin the values at
                 // the new node based on the boundary conditions applied at
                 // its Mesh boundary
                 // Get the boundary conditions from the father
                 Vector<int> bound_cons(ncont_interpolated_values());
                 father_el_pt->get_bcs(father_bound, bound_cons);
                 // Loop over the values and pin, if necessary
                 unsigned n_value = created_node_pt->nvalue();
                 for (unsigned k = 0; k < n_value; k++)
                 {
                   if (bound_cons[k])
                   {
                     created_node_pt->pin(k);
                   }
                 }
                 // Solid node? If so, deal with the positional boundary
                 // conditions:
                 SolidNode* solid_node_pt =
                   dynamic_cast<SolidNode*>(created_node_pt);
                 if (solid_node_pt != 0)
                 {
                   // Get the positional boundary conditions from the father:
                   unsigned n_dim = created_node_pt->ndim();
                   Vector<int> solid_bound_cons(n_dim);
                   RefineableSolidQElement<2>* father_solid_el_pt =
                     dynamic_cast<RefineableSolidQElement<2>*>(father_el_pt);
 #ifdef PARANOID
                   if (father_solid_el_pt == 0)
                   {
                     std::string error_message =
                       "We have a SolidNode outside a refineable SolidElement\n";
                     error_message +=
                       "during mesh refinement -- this doesn't make sense";
                     throw OomphLibError(error_message,
                                         OOMPH_CURRENT_FUNCTION,
                                         OOMPH_EXCEPTION_LOCATION);
                   }
 #endif
                   father_solid_el_pt->get_solid_bcs(father_bound,
                                                     solid_bound_cons);
                   // Loop over the positions and pin, if necessary
                   for (unsigned k = 0; k < n_dim; k++)
                   {
                     if (solid_bound_cons[k])
                     {
                       solid_node_pt->pin_position(k);
                     }
                   }
                 } // End of if solid_node_pt
                 // Next, we Update the boundary lookup schemes
                 // Loop over the boundaries stored in the set
                 for (std::set<unsigned>::iterator it = boundaries.begin();
                      it != boundaries.end();
                      ++it)
                 {
                   // Add the node to the boundary
                   mesh_pt->add_boundary_node(*it, created_node_pt);
                   // If we have set an intrinsic coordinate on this
                   // mesh boundary then it must also be interpolated on
                   // the new node
                   // Now interpolate the intrinsic boundary coordinate
                   if (mesh_pt->boundary_coordinate_exists(*it) == true)
                   {
                     Vector<double> zeta(1);
                     father_el_pt->interpolated_zeta_on_edge(
                       *it, father_bound, s, zeta);
                     created_node_pt->set_coordinates_on_boundary(*it, zeta);
                   }
                 }
               }
               // Otherwise the node is not on a Mesh boundary and
               // we create a normal "bulk" node
               else
               {
                 // Create node and set the pointer to it from the element
                 created_node_pt = construct_node(jnod, time_stepper_pt);
                 // Add to vector of new nodes
                 new_node_pt.push_back(created_node_pt);
               }
               // Now we set the position and values at the newly created node
               // In the first instance use macro element or FE representation
               // to create past and present nodal positions.
               // (THIS STEP SHOULD NOT BE SKIPPED FOR ALGEBRAIC
               // ELEMENTS AS NOT ALL OF THEM NECESSARILY IMPLEMENT
               // NONTRIVIAL NODE UPDATE FUNCTIONS. CALLING
               // THE NODE UPDATE FOR SUCH ELEMENTS/NODES WILL LEAVE
               // THEIR NODAL POSITIONS WHERE THEY WERE (THIS IS APPROPRIATE
               // ONCE THEY HAVE BEEN GIVEN POSITIONS) BUT WILL
               // NOT ASSIGN SENSIBLE INITIAL POSITONS!
               // Loop over # of history values
               for (unsigned t = 0; t < ntstorage; t++)
               {
                 // Get position from father element -- this uses the macro
                 // element representation if appropriate. If the node
                 // turns out to be a hanging node later on, then
                 // its position gets adjusted in line with its
                 // hanging node interpolation.
                 Vector<double> x_prev(2);
                 father_el_pt->get_x(t, s, x_prev);
                 // Set previous positions of the new node
                 for (unsigned i = 0; i < 2; i++)
                 {
                   created_node_pt->x(t, i) = x_prev[i];
                 }
               }
               // Loop over all history values
               for (unsigned t = 0; t < ntstorage; t++)
               {
                 // Get values from father element
                 // Note: get_interpolated_values() sets Vector size itself.
                 Vector<double> prev_values;
                 father_el_pt->get_interpolated_values(t, s, prev_values);
                 // Initialise the values at the new node
                 unsigned n_value = created_node_pt->nvalue();
                 for (unsigned k = 0; k < n_value; k++)
                 {
                   created_node_pt->set_value(t, k, prev_values[k]);
                 }
               }
               // Add new node to mesh
               mesh_pt->add_node_pt(created_node_pt);
             } // End of case when we build the node ourselves
             // Check if the element is an algebraic element
             AlgebraicElementBase* alg_el_pt =
               dynamic_cast<AlgebraicElementBase*>(this);
             // If the element is an algebraic element, setup
             // node position (past and present) from algebraic node update
             // function. This over-writes previous assingments that
             // were made based on the macro-element/FE representation.
             // NOTE: YES, THIS NEEDS TO BE CALLED REPEATEDLY IF THE
             // NODE IS MEMBER OF MULTIPLE ELEMENTS: THEY ALL ASSIGN
             // THE SAME NODAL POSITIONS BUT WE NEED TO ADD THE REMESH
             // INFO FOR *ALL* ROOT ELEMENTS!
             if (alg_el_pt != 0)
             {
               // Build algebraic node update info for new node
               // This sets up the node update data for all node update
               // functions that are shared by all nodes in the father
               // element
               alg_el_pt->setup_algebraic_node_update(
                 node_pt(jnod), s, father_el_pt);
             }
             // If we have built the node and we are documenting our progress
             // write the (hopefully consistent position) to  the outputfile
             if ((!node_done) && (new_nodes_file.is_open()))
             {
               new_nodes_file << node_pt(jnod)->x(0) << " "
                              << node_pt(jnod)->x(1) << std::endl;
             }
           } // End of vertical loop over nodes in element
         } // End of horizontal loop over nodes in element
         // If the element is a MacroElementNodeUpdateElement, set
         // the update parameters for the current element's nodes --
         // all this needs is the vector of (pointers to the)
         // geometric objects that affect the MacroElement-based
         // node update -- this is the same as that in the father element
         MacroElementNodeUpdateElementBase* father_m_el_pt =
           dynamic_cast<MacroElementNodeUpdateElementBase*>(father_el_pt);
         if (father_m_el_pt != 0)
         {
           // Get vector of geometric objects from father (construct vector
           // via copy operation)
           Vector<GeomObject*> geom_object_pt(father_m_el_pt->geom_object_pt());
           // Cast current element to MacroElementNodeUpdateElement:
           MacroElementNodeUpdateElementBase* m_el_pt =
             dynamic_cast<MacroElementNodeUpdateElementBase*>(this);
 #ifdef PARANOID
           if (m_el_pt == 0)
           {
             std::string error_message =
               "Failed to cast to MacroElementNodeUpdateElementBase*\n";
             error_message +=
               "Strange -- if the father is a MacroElementNodeUpdateElement\n";
             error_message += "the son should be too....\n";
             throw OomphLibError(
               error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
           }
 #endif
           // Build update info by passing vector of geometric objects:
           // This sets the current element to be the update element
           // for all of the element's nodes -- this is reversed
           // if the element is ever un-refined in the father element's
           // rebuild_from_sons() function which overwrites this
           // assignment to avoid nasty segmentation faults that occur
           // when a node tries to update itself via an element that no
           // longer exists...
           m_el_pt->set_node_update_info(geom_object_pt);
         }
 #ifdef OOMPH_HAS_MPI
         // Pass on non-halo proc id
         Non_halo_proc_ID =
           tree_pt()->father_pt()->object_pt()->non_halo_proc_ID();
 #endif
         // Is it an ElementWithMovingNodes?
         ElementWithMovingNodes* aux_el_pt =
           dynamic_cast<ElementWithMovingNodes*>(this);
         // Pass down the information re the method for the evaluation
         // of the shape derivatives
         if (aux_el_pt != 0)
         {
           ElementWithMovingNodes* aux_father_el_pt =
             dynamic_cast<ElementWithMovingNodes*>(father_el_pt);
 #ifdef PARANOID
           if (aux_father_el_pt == 0)
           {
             std::string error_message =
               "Failed to cast to ElementWithMovingNodes*\n";
             error_message +=
               "Strange -- if the son is a ElementWithMovingNodes\n";
             error_message += "the father should be too....\n";
             throw OomphLibError(
               error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
           }
 #endif
           // If evaluating the residuals by finite differences in the father
           // continue to do so in the child
           if (aux_father_el_pt
                 ->are_dresidual_dnodal_coordinates_always_evaluated_by_fd())
           {
             aux_el_pt
               ->enable_always_evaluate_dresidual_dnodal_coordinates_by_fd();
           }
           aux_el_pt->method_for_shape_derivs() =
             aux_father_el_pt->method_for_shape_derivs();
           // If bypassing the evaluation of fill_in_jacobian_from_geometric_data
           // continue to do so
           if (aux_father_el_pt
                 ->is_fill_in_jacobian_from_geometric_data_bypassed())
           {
             aux_el_pt->enable_bypass_fill_in_jacobian_from_geometric_data();
           }
         }
         // Now do further build (if any)
         further_build();
       } // Sanity check: Father element has been generated
     }
     // Element has already been built
     else
     {
       was_already_built = true;
     }
   }
References oomph::Mesh::add_boundary_node(), oomph::Mesh::add_node_pt(), oomph::Mesh::boundary_coordinate_exists(), oomph::ElementWithMovingNodes::enable_always_evaluate_dresidual_dnodal_coordinates_by_fd(), oomph::ElementWithMovingNodes::enable_bypass_fill_in_jacobian_from_geometric_data(), oomph::MacroElementNodeUpdateElementBase::geom_object_pt(), get_bcs(), get_boundaries(), oomph::RefineableElement::get_interpolated_values(), oomph::FiniteElement::get_node_at_local_coordinate(), oomph::RefineableSolidQElement< 2 >::get_solid_bcs(), oomph::FiniteElement::get_x(), i, interpolated_zeta_on_edge(), k, oomph::FiniteElement::Macro_elem_pt, oomph::Node::make_periodic(), oomph::ElementWithMovingNodes::method_for_shape_derivs(), oomph::Node::ndim(), oomph::QuadTreeNames::NE, oomph::FiniteElement::node_pt(), oomph::Node::nposition_type(), oomph::Data::nvalue(), oomph::QuadTreeNames::NW, oomph::Tree::object_pt(), oomph::Tree::OMEGA, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Data::pin(), oomph::SolidNode::pin_position(), s, oomph::QElementBase::s_macro_ll(), oomph::QElementBase::s_macro_ur(), oomph::QuadTreeNames::SE, oomph::Node::set_coordinates_on_boundary(), oomph::MacroElementNodeUpdateElementBase::set_node_update_info(), oomph::Data::set_value(), oomph::AlgebraicElementBase::setup_algebraic_node_update(), oomph::Tree::son_type(), oomph::Global_string_for_annotation::string(), oomph::QuadTreeNames::SW, plotPSD::t, oomph::Data::time_stepper_pt(), plotDoE::x, oomph::Node::x(), and Eigen::zeta().
check_integrity()
void oomph::RefineableQElement< 2 >::check_integrity (double & max_error) virtual
Check the integrity of the element: ensure that the position and values are continuous across the element edges
Check inter-element continuity of
nodal positions
(nodally) interpolated function values
Implements oomph::RefineableElement.
   {
     using namespace QuadTreeNames;
     // Number of nodes along edge
     unsigned n_p = nnode_1d();
     // Number of timesteps (incl. present) for which continuity is
     // to be checked.
     unsigned n_time = 1;
     // Initialise errors
     max_error = 0.0;
     Vector<double> max_error_x(2, 0.0);
     double max_error_val = 0.0;
     Vector<int> edges(4);
     edges[0] = S;
     edges[1] = N;
     edges[2] = W;
     edges[3] = E;
     // Loop over the edges
     for (unsigned edge_counter = 0; edge_counter < 4; edge_counter++)
     {
       Vector<unsigned> translate_s(2);
       Vector<double> s(2), s_lo_neigh(2), s_hi_neigh(2), s_fraction(2);
       int neigh_edge, diff_level;
       bool in_neighbouring_tree;
       // Find pointer to neighbour in this direction
       QuadTree* neigh_pt;
       neigh_pt = quadtree_pt()->gteq_edge_neighbour(edges[edge_counter],
                                                     translate_s,
                                                     s_lo_neigh,
                                                     s_hi_neigh,
                                                     neigh_edge,
                                                     diff_level,
                                                     in_neighbouring_tree);
       // Neighbour exists and has existing nodes
       if ((neigh_pt != 0) && (neigh_pt->object_pt()->nodes_built()))
       {
         // Need to exclude periodic nodes from this check
         // There are only periodic nodes if we are in a neighbouring tree
         bool is_periodic = false;
         if (in_neighbouring_tree)
         {
           // Is it periodic
           is_periodic =
             tree_pt()->root_pt()->is_neighbour_periodic(edges[edge_counter]);
         }
         // Loop over nodes along the edge
         for (unsigned i0 = 0; i0 < n_p; i0++)
         {
           // Storage for pointer to the local node
           Node* local_node_pt = 0;
           switch (edge_counter)
           {
             case 0:
               // Local fraction of node
               s_fraction[0] = local_one_d_fraction_of_node(i0, 0);
               s_fraction[1] = 0.0;
               // Get pointer to local node
               local_node_pt = node_pt(i0);
               break;
             case 1:
               // Local fraction of node
               s_fraction[0] = local_one_d_fraction_of_node(i0, 0);
               s_fraction[1] = 1.0;
               // Get pointer to local node
               local_node_pt = node_pt(i0 + n_p * (n_p - 1));
               break;
             case 2:
               // Local fraction of node
               s_fraction[0] = 0.0;
               s_fraction[1] = local_one_d_fraction_of_node(i0, 1);
               // Get pointer to local node
               local_node_pt = node_pt(n_p * i0);
               break;
             case 3:
               // Local fraction of node
               s_fraction[0] = 1.0;
               s_fraction[1] = local_one_d_fraction_of_node(i0, 1);
               // Get pointer to local node
               local_node_pt = node_pt(n_p - 1 + n_p * i0);
               break;
           }
           // Calculate the local coordinate and the local coordinate as viewed
           // from the neighbour
           Vector<double> s_in_neighb(2);
           for (unsigned i = 0; i < 2; i++)
           {
             // Local coordinate in this element
             s[i] = -1.0 + 2.0 * s_fraction[i];
             // Local coordinate in the neighbour
             s_in_neighb[i] = s_lo_neigh[i] + s_fraction[translate_s[i]] *
                                                (s_hi_neigh[i] - s_lo_neigh[i]);
           }
           // Loop over timesteps
           for (unsigned t = 0; t < n_time; t++)
           {
             // Get the nodal position from neighbour element
             Vector<double> x_in_neighb(2);
             neigh_pt->object_pt()->interpolated_x(t, s_in_neighb, x_in_neighb);
             // Check error only if the node is NOT periodic
             if (is_periodic == false)
             {
               for (int i = 0; i < 2; i++)
               {
                 // Find the spatial error
                 double err = std::fabs(local_node_pt->x(t, i) - x_in_neighb[i]);
                 // If it's bigger than our tolerance, say so
                 if (err > 1e-9)
                 {
                   oomph_info << "errx " << err << " " << t << " "
                              << local_node_pt->x(t, i) << " " << x_in_neighb[i]
                              << std::endl;
                   oomph_info << "at " << local_node_pt->x(0) << " "
                              << local_node_pt->x(1) << std::endl;
                 }
                 // If it's bigger than the previous max error, it is the
                 // new max error!
                 if (err > max_error_x[i])
                 {
                   max_error_x[i] = err;
                 }
               }
             }
             // Get the values from neighbour element. Note: # of values
             // gets set by routine (because in general we don't know
             // how many interpolated values a certain element has
             Vector<double> values_in_neighb;
             neigh_pt->object_pt()->get_interpolated_values(
               t, s_in_neighb, values_in_neighb);
             // Get the values in current element.
             Vector<double> values;
             get_interpolated_values(t, s, values);
             // Now figure out how many continuously interpolated values there
             // are
             unsigned num_val =
               neigh_pt->object_pt()->ncont_interpolated_values();
             // Check error
             for (unsigned ival = 0; ival < num_val; ival++)
             {
               double err = std::fabs(values[ival] - values_in_neighb[ival]);
               if (err > 1.0e-10)
               {
                 oomph_info << local_node_pt->x(0) << " " << local_node_pt->x(1)
                            << " \n# "
                            << "erru (S)" << err << " " << ival << " "
                            << get_node_number(local_node_pt) << " "
                            << values[ival] << " " << values_in_neighb[ival]
                            << std::endl;
               }
               if (err > max_error_val)
               {
                 max_error_val = err;
               }
             }
           }
         }
       }
     }
     max_error = max_error_x[0];
     if (max_error_x[1] > max_error) max_error = max_error_x[1];
     if (max_error_val > max_error) max_error = max_error_val;
     if (max_error > 1e-9)
     {
       oomph_info << "\n#------------------------------------ \n#Max error ";
       oomph_info << max_error_x[0] << " " << max_error_x[1] << " "
                  << max_error_val << std::endl;
       oomph_info << "#------------------------------------ \n " << std::endl;
     }
   }
References Global_Physical_Variables::E, e(), boost::multiprecision::fabs(), oomph::RefineableElement::get_interpolated_values(), oomph::QuadTree::gteq_edge_neighbour(), i, oomph::FiniteElement::interpolated_x(), MeshRefinement::max_error, N, oomph::RefineableElement::ncont_interpolated_values(), oomph::RefineableElement::nodes_built(), oomph::Tree::object_pt(), oomph::oomph_info, s, oomph::QuadTreeNames::S, plotPSD::t, oomph::QuadTreeNames::W, and oomph::Node::x().
further_setup_hanging_nodes()
virtual void oomph::RefineableQElement< 2 >::further_setup_hanging_nodes () pure virtual
Perform additional hanging node procedures for variables that are not interpolated by all nodes (e.g. lower order interpolations as for the pressure in Taylor Hood).
Reimplemented from oomph::RefineableElement.
Implemented in oomph::RefineableQYoungLaplaceElement< NNODE_1D >, oomph::RefineableQSphericalCrouzeixRaviartElement, oomph::RefineableQSphericalTaylorHoodElement, oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >, oomph::RefineableQSphericalAdvectionDiffusionElement< 3 >, oomph::RefineablePolarCrouzeixRaviartElement, oomph::RefineablePolarTaylorHoodElement, oomph::RefineableLinearisedQTaylorHoodElement, oomph::RefineableLinearisedQCrouzeixRaviartElement, oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement, oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement, oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >, oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement, oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement, oomph::RefineableAxisymmetricQCrouzeixRaviartElement, oomph::RefineableAxisymmetricQTaylorHoodElement, oomph::RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::RefineableQAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::RefineableQAxisymAdvectionDiffusionElement< 3 >, oomph::RefineablePolarStreamfunctionElement, oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement, and oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement.
get_bcs()
void oomph::RefineableQElement< 2 >::get_bcs (int bound, Vector< int > & bound_cons) const
Determine Vector of boundary conditions along edge (or on vertex) bound (S/W/N/E/SW/SE/NW/NE): For value ival on this boundary, bound_cons[ival]=1 if pinned and 0 if free.
Determine Vector of boundary conditions along the element's boundary (or vertex) bound (S/W/N/E/SW/SE/NW/NE).
This function assumes that the same boundary condition is applied along the entire length of an element's edge (of course, the vertices combine the boundary conditions of their two adjacent edges in the most restrictive combination. Hence, if we're at a vertex, we apply the most restrictive boundary condition of the two adjacent edges. If we're on an edge (in its proper interior), we apply the least restrictive boundary condition of all nodes along the edge.
Usual convention:
bound_cons[ival]=0 if value ival on this boundary is free
bound_cons[ival]=1 if value ival on this boundary is pinned
   {
     using namespace QuadTreeNames;
     // Max. number of nodal data values in element
     unsigned nvalue = ncont_interpolated_values();
     // Set up temporary vectors to hold edge boundary conditions
     Vector<int> bound_cons1(nvalue), bound_cons2(nvalue);
     // Which boundary are we on?
     switch (bound)
     {
         // If on edge, just get the bcs
       case N:
       case S:
       case W:
       case E:
         get_edge_bcs(bound, bound_cons);
         break;
         // Most restrictive boundary at SE corner
       case SE:
         get_edge_bcs(S, bound_cons1);
         get_edge_bcs(E, bound_cons2);
         for (unsigned k = 0; k < nvalue; k++)
         {
           bound_cons[k] = (bound_cons1[k] || bound_cons2[k]);
         }
         break;
         // Most restrictive boundary at SW corner
       case SW:
         get_edge_bcs(S, bound_cons1);
         get_edge_bcs(W, bound_cons2);
         for (unsigned k = 0; k < nvalue; k++)
         {
           bound_cons[k] = (bound_cons1[k] || bound_cons2[k]);
         }
         break;
         // Most restrictive boundary at NW corner
       case NW:
         get_edge_bcs(N, bound_cons1);
         get_edge_bcs(W, bound_cons2);
         for (unsigned k = 0; k < nvalue; k++)
         {
           bound_cons[k] = (bound_cons1[k] || bound_cons2[k]);
         }
         break;
         // Most restrictive boundary at NE corner
       case NE:
         get_edge_bcs(N, bound_cons1);
         get_edge_bcs(E, bound_cons2);
         for (unsigned k = 0; k < nvalue; k++)
         {
           bound_cons[k] = (bound_cons1[k] || bound_cons2[k]);
         }
         break;
       default:
         throw OomphLibError(
           "Wrong boundary", OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
   }
References Global_Physical_Variables::E, k, N, oomph::QuadTreeNames::NE, oomph::QuadTreeNames::NW, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::QuadTreeNames::S, oomph::QuadTreeNames::SE, oomph::QuadTreeNames::SW, and oomph::QuadTreeNames::W.
Referenced by build(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::rebuild_from_sons(), and oomph::RefineableQSpectralElement< 2 >::rebuild_from_sons().
get_boundaries()
void oomph::RefineableQElement< 2 >::get_boundaries (const int & edge, std::set< unsigned > & boundary) const
Determine set of (mesh) boundaries that the element edge/vertex lives on
Given an element edge/vertex, return a set that contains all the (mesh-)boundary numbers that this element edge/vertex lives on.
For proper edges, the boundary is the one (if any) that is shared by both vertex nodes). For vertex nodes, we just return their boundaries.
   {
     using namespace QuadTreeNames;
     // Number of 1d nodes along an edge
     unsigned n_p = nnode_1d();
     // Left and right-hand nodes
     int left_node = -1, right_node = -1;
     // Set the left (lower) and right (upper) nodes for the edge
     switch (edge)
     {
       case N:
         left_node = n_p * (n_p - 1);
         right_node = n_p * n_p - 1;
         break;
       case S:
         left_node = 0;
         right_node = n_p - 1;
         break;
       case W:
         left_node = 0;
         right_node = n_p * (n_p - 1);
         break;
       case E:
         left_node = n_p - 1;
         right_node = n_p * n_p - 1;
         break;
         // Vertices do not have left nodes!
       case SE:
         right_node = n_p - 1;
         break;
       case SW:
         right_node = 0;
         break;
       case NE:
         right_node = n_p * n_p - 1;
         break;
       case NW:
         right_node = n_p * (n_p - 1);
         break;
       default:
         std::ostringstream error_stream;
         error_stream << "Wrong edge " << edge << " passed" << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Empty the boundary set: Edge does not live on any boundary
     boundary.clear();
     // Storage for the nodes that the right node lives on
     std::set<unsigned>* right_boundaries_pt = 0;
     // Get the boundaries that the right node lives on
     node_pt(right_node)->get_boundaries_pt(right_boundaries_pt);
     // If the right node lives on some boundaries
     if (right_boundaries_pt != 0)
     {
       // If the node is a vertex then add the boundaries at the node
       // into the vector boundary
       if (left_node < 0)
       {
         copy(right_boundaries_pt->begin(),
              right_boundaries_pt->end(),
              inserter(boundary, boundary.begin()));
       }
       // Otherwise only add if the boundary also exists at the left hand node
       else
       {
         std::set<unsigned>* left_boundaries_pt = 0;
         node_pt(left_node)->get_boundaries_pt(left_boundaries_pt);
         // If the left node is on some boundaries
         if (left_boundaries_pt != 0)
         {
           // Use the standard algorithms to compute the boundaries in
           // common between the left and right nodes
           std::set_intersection(right_boundaries_pt->begin(),
                                 right_boundaries_pt->end(),
                                 left_boundaries_pt->begin(),
                                 left_boundaries_pt->end(),
                                 inserter(boundary, boundary.begin()));
         }
       }
     }
   }
References copy(), Global_Physical_Variables::E, N, oomph::QuadTreeNames::NE, oomph::QuadTreeNames::NW, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::QuadTreeNames::S, oomph::QuadTreeNames::SE, oomph::QuadTreeNames::SW, and oomph::QuadTreeNames::W.
Referenced by build(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::rebuild_from_sons(), and oomph::RefineableQSpectralElement< 2 >::rebuild_from_sons().
get_edge_bcs()
void oomph::RefineableQElement< 2 >::get_edge_bcs (const int & edge, Vector< int > & bound_cons) const protected
Determine Vector of boundary conditions along edge (N/S/W/E)
Determine Vector of boundary conditions along the element's edge (S/N/W/E) – BC is the least restrictive combination of all the nodes on this edge
Usual convention:
bound_cons[ival]=0 if value ival on this boundary is free
bound_cons[ival]=1 if value ival on this boundary is pinned
   {
     using namespace QuadTreeNames;
     // Number of nodes along 1D edge
     unsigned n_p = nnode_1d();
     // Left- and Right-hand nodes
     unsigned left_node, right_node;
     // Set the left (lower) and right (upper) nodes for the edge
     switch (edge)
     {
       case N:
         left_node = n_p * (n_p - 1);
         right_node = n_p * n_p - 1;
         break;
       case S:
         left_node = 0;
         right_node = n_p - 1;
         break;
       case W:
         left_node = 0;
         right_node = n_p * (n_p - 1);
         break;
       case E:
         left_node = n_p - 1;
         right_node = n_p * n_p - 1;
         break;
       default:
         std::ostringstream error_stream;
         error_stream << "Wrong edge " << edge << " passed to get_edge_bcs(..)"
                      << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Max. number of nodal data values in element
     unsigned maxnvalue = ncont_interpolated_values();
     // Loop over all values, the least restrictive value is
     // the boundary condition at the left multiplied by that at the right
     // Assuming that free is always zero and pinned is one
     for (unsigned k = 0; k < maxnvalue; k++)
     {
       bound_cons[k] =
         node_pt(left_node)->is_pinned(k) * node_pt(right_node)->is_pinned(k);
     }
   }
References Global_Physical_Variables::E, k, N, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::QuadTreeNames::S, and oomph::QuadTreeNames::W.
interpolated_zeta_on_edge()
void oomph::RefineableQElement< 2 >::interpolated_zeta_on_edge (const unsigned & boundary, const int & edge, const Vector< double > & s, Vector< double > & zeta)
Return the value of the intrinsic boundary coordinate interpolated along the edge (S/W/N/E)
   {
     using namespace QuadTreeNames;
     // Number of 1D nodes along an edge
     unsigned n_p = nnode_1d();
     // Storage for the shape functions
     Shape psi(n_p * n_p);
     // Get the shape functions at the passed position
     this->shape(s, psi);
     // Unsigned data that give starts and multipliers for the loop
     // over the nodes on the edges.
     unsigned start = 0, multiplier = 1;
     // Which edge?
     switch (edge)
     {
       case S:
 #ifdef PARANOID
         if (s[1] != -1.0)
         {
           std::ostringstream error_stream;
           error_stream << "Coordinate " << s[0] << " " << s[1]
                        << " is not on South edge\n";
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         // Start is zero and multiplier is one
         break;
       case N:
 #ifdef PARANOID
         if (s[1] != 1.0)
         {
           std::ostringstream error_stream;
           error_stream << "Coordinate " << s[0] << " " << s[1]
                        << " is not on North edge\n";
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         // Start from the top left corner of the element, multiplier still one
         start = n_p * (n_p - 1);
         break;
       case W:
 #ifdef PARANOID
         if (s[0] != -1.0)
         {
           std::ostringstream error_stream;
           error_stream << "Coordinate " << s[0] << " " << s[1]
                        << " is not on West edge\n";
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         // Loop over left-hand edge of element (start from zero)
         multiplier = n_p;
         break;
       case E:
 #ifdef PARANOID
         if (s[0] != 1.0)
         {
           std::ostringstream error_stream;
           error_stream << "Coordinate " << s[0] << " " << s[1]
                        << " is not on East edge\n";
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         // Start from the bottom right-hand corner
         start = n_p - 1;
         // Loop over the right-hand edge of the element
         multiplier = n_p;
         break;
       default:
         std::ostringstream error_stream;
         error_stream << "Wrong edge " << edge << " passed" << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Initialise the intrinsic coordinate
     double inter_zeta = 0.0;
     // Loop over the nodes on the edge
     for (unsigned n = 0; n < n_p; n++)
     {
       // Get the node number
       unsigned node_number = start + multiplier * n;
       // Now get the intrinsic coordinate
       node_pt(node_number)->get_coordinates_on_boundary(boundary, zeta);
       // Now multiply by the shape function
       inter_zeta += zeta[0] * psi(node_number);
     }
     // Set the value of the intrinsic coordinate
     zeta[0] = inter_zeta;
   }
References Global_Physical_Variables::E, Global_Physical_Variables::multiplier(), n, N, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, s, oomph::QuadTreeNames::S, oomph::OneDimLagrange::shape(), oomph::CumulativeTimings::start(), oomph::QuadTreeNames::W, and Eigen::zeta().
Referenced by build(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::rebuild_from_sons(), and oomph::RefineableQSpectralElement< 2 >::rebuild_from_sons().
node_created_by_neighbour()
Node * oomph::RefineableQElement< 2 >::node_created_by_neighbour (const Vector< double > & s_fraction, bool & is_periodic) virtual
If a neighbouring element has already created a node at a position corresponding to the local fractional position within the present element, s_fraction, return a pointer to that node. If not, return NULL (0). If the node is on a periodic boundary the flag is_periodic is true, otherwise it will be false.
If a neighbouring element has already created a node at a position corresponding to the local fractional position within the present element, s_fraction, return a pointer to that node. If not, return NULL (0). If the node is periodic the flag is_periodic will be true
Reimplemented in oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >.
   {
     using namespace QuadTreeNames;
     // Calculate the edges on which the node lies
     Vector<int> edges;
     if (s_fraction[0] == 0.0)
     {
       edges.push_back(W);
     }
     if (s_fraction[0] == 1.0)
     {
       edges.push_back(E);
     }
     if (s_fraction[1] == 0.0)
     {
       edges.push_back(S);
     }
     if (s_fraction[1] == 1.0)
     {
       edges.push_back(N);
     }
     // Find the number of edges
     unsigned n_size = edges.size();
     // If there are no edges, then there is no neighbour, return 0
     if (n_size == 0)
     {
       return 0;
     }
     Vector<unsigned> translate_s(2);
     Vector<double> s_lo_neigh(2);
     Vector<double> s_hi_neigh(2);
     Vector<double> s(2);
     int neigh_edge, diff_level;
     bool in_neighbouring_tree;
     // Loop over the edges
     for (unsigned j = 0; j < n_size; j++)
     {
       // Find pointer to neighbouring element along edge
       QuadTree* neigh_pt;
       neigh_pt = quadtree_pt()->gteq_edge_neighbour(edges[j],
                                                     translate_s,
                                                     s_lo_neigh,
                                                     s_hi_neigh,
                                                     neigh_edge,
                                                     diff_level,
                                                     in_neighbouring_tree);
       // Neighbour exists
       if (neigh_pt != 0)
       {
         // Have its nodes been created yet?
         // if(neigh_pt->object_pt()->node_pt(0)!=0)
         if (neigh_pt->object_pt()->nodes_built())
         {
           // We now need to translate the nodal location
           // as defined in terms of the fractional coordinates of the present
           // element into those of its neighbour
           // Calculate the local coordinate in the neighbour
           // Note that we need to use the translation scheme in case
           // the local coordinates are swapped in the neighbour.
           for (unsigned i = 0; i < 2; i++)
           {
             s[i] = s_lo_neigh[i] +
                    s_fraction[translate_s[i]] * (s_hi_neigh[i] - s_lo_neigh[i]);
           }
           // Find the node in the neighbour
           Node* neighbour_node_pt =
             neigh_pt->object_pt()->get_node_at_local_coordinate(s);
           // If there is a node, return it
           if (neighbour_node_pt != 0)
           {
             // Now work out whether it's a periodic boundary
             // only possible if we have moved into a neighbouring tree
             if (in_neighbouring_tree)
             {
               // Return whether the neighbour is periodic
               is_periodic =
                 quadtree_pt()->root_pt()->is_neighbour_periodic(edges[j]);
             }
             // Return the pointer to the neighbouring node
             return neighbour_node_pt;
           }
         }
       }
     }
     // Node not found, return null
     return 0;
   }
References Global_Physical_Variables::E, oomph::FiniteElement::get_node_at_local_coordinate(), oomph::QuadTree::gteq_edge_neighbour(), i, j, N, oomph::RefineableElement::nodes_built(), oomph::Tree::object_pt(), s, oomph::QuadTreeNames::S, and oomph::QuadTreeNames::W.
node_created_by_son_of_neighbour()
virtual Node* oomph::RefineableQElement< 2 >::node_created_by_son_of_neighbour (const Vector< double > & s_fraction, bool & is_periodic) inline virtual
If a son of a neighbouring element has already created a node at a position corresponding to the local fractional position within the present element, s_fraction, return a pointer to that node. If not, return NULL (0). If the node is on a periodic boundary the flag is_periodic is true, otherwise it will be false.
Reimplemented in oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >.
     {
       // It is impossible for this situation to arise in meshes
       // containing elements of uniform p-order. This is here so
       // that it can be overloaded for p-refineable elements.
       return 0;
     }
output_corners()
void oomph::RefineableQElement< 2 >::output_corners (std::ostream & outfile, const std::string & colour) const
Print corner nodes, use colour.
Print corner nodes, use colour (default "BLACK")
   {
     Vector<double> s(2);
     Vector<double> corner(2);
     outfile << "ZONE I=2,J=2, C=" << colour << std::endl;
     s[0] = -1.0;
     s[1] = -1.0;
     get_x(s, corner);
     outfile << corner[0] << " " << corner[1] << " " << Number << std::endl;
     s[0] = 1.0;
     s[1] = -1.0;
     get_x(s, corner);
     outfile << corner[0] << " " << corner[1] << " " << Number << std::endl;
     s[0] = -1.0;
     s[1] = 1.0;
     get_x(s, corner);
     outfile << corner[0] << " " << corner[1] << " " << Number << std::endl;
     s[0] = 1.0;
     s[1] = 1.0;
     get_x(s, corner);
     outfile << corner[0] << " " << corner[1] << " " << Number << std::endl;
     outfile << "TEXT  CS = GRID, X = " << corner[0] << ",Y = " << corner[1]
             << ", HU = GRID, H = 0.01, AN = MIDCENTER, T =\"" << Number << "\""
             << std::endl;
   }
References oomph::TecplotNames::colour, oomph::Global_unsigned::Number, and s.
quad_hang_helper()
void oomph::RefineableQElement< 2 >::quad_hang_helper (const int & value_id, const int & my_edge, std::ofstream & output_hangfile) protected virtual
Internal helper function that is used to construct the hanging node schemes for the positions.
Internal function to set up the hanging nodes on a particular edge of the element
Reimplemented in oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >.
   {
     using namespace QuadTreeNames;
     Vector<unsigned> translate_s(2);
     Vector<double> s_lo_neigh(2);
     Vector<double> s_hi_neigh(2);
     int neigh_edge, diff_level;
     bool in_neighbouring_tree;
     // Find pointer to neighbour in this direction
     QuadTree* neigh_pt;
     neigh_pt = quadtree_pt()->gteq_edge_neighbour(my_edge,
                                                   translate_s,
                                                   s_lo_neigh,
                                                   s_hi_neigh,
                                                   neigh_edge,
                                                   diff_level,
                                                   in_neighbouring_tree);
     // Neighbour exists and all nodes have been created
     if (neigh_pt != 0)
     {
       // Different sized element?
       if (diff_level != 0)
       {
         // Test for the periodic node case
         // Are we crossing a periodic boundary
         bool is_periodic = false;
         if (in_neighbouring_tree)
         {
           is_periodic = tree_pt()->root_pt()->is_neighbour_periodic(my_edge);
         }
         // If it is periodic we actually need to get the node in
         // the neighbour of the neighbour (which will be a parent of
         // the present element) so that the "fixed" coordinate is
         // correctly calculated.
         // The idea is to replace the neigh_pt and associated data
         // with those of the neighbour of the neighbour
         if (is_periodic)
         {
           // Required data for the neighbour finding routine
           Vector<unsigned> translate_s_in_neigh(2);
           Vector<double> s_lo_neigh_of_neigh(2);
           Vector<double> s_hi_neigh_of_neigh(2);
           int neigh_edge_of_neigh, diff_level_of_neigh;
           bool in_neighbouring_tree_of_neigh;
           // Find pointer to neighbour of the neighbour on the edge
           // that we are currently considering
           QuadTree* neigh_of_neigh_pt;
           neigh_of_neigh_pt =
             neigh_pt->gteq_edge_neighbour(neigh_edge,
                                           translate_s_in_neigh,
                                           s_lo_neigh_of_neigh,
                                           s_hi_neigh_of_neigh,
                                           neigh_edge_of_neigh,
                                           diff_level_of_neigh,
                                           in_neighbouring_tree_of_neigh);
           // Set the value of the NEW neighbour and edge
           neigh_pt = neigh_of_neigh_pt;
           neigh_edge = neigh_edge_of_neigh;
           // Set the values of the translation schemes
           // Need to find the values of s_lo and s_hi
           // in the neighbour of the neighbour
           // Get the minimum and maximum values of the coordinate
           // in the neighbour (don't like this, but I think it's
           // necessary) Note that these values are hardcoded
           // in the quadtrees at some point!!
           double s_min = neigh_pt->object_pt()->s_min();
           double s_max = neigh_pt->object_pt()->s_max();
           Vector<double> s_lo_frac(2), s_hi_frac(2);
           // Work out the fractional position of the low and high points
           // of the original element
           for (unsigned i = 0; i < 2; i++)
           {
             s_lo_frac[i] = (s_lo_neigh[i] - s_min) / (s_max - s_min);
             s_hi_frac[i] = (s_hi_neigh[i] - s_min) / (s_max - s_min);
           }
           // We should now be able to construct the low and high points in
           // the neighbour of the neighbour
           for (unsigned i = 0; i < 2; i++)
           {
             s_lo_neigh[i] = s_lo_neigh_of_neigh[i] +
                             s_lo_frac[translate_s_in_neigh[i]] *
                               (s_hi_neigh_of_neigh[i] - s_lo_neigh_of_neigh[i]);
             s_hi_neigh[i] = s_lo_neigh_of_neigh[i] +
                             s_hi_frac[translate_s_in_neigh[i]] *
                               (s_hi_neigh_of_neigh[i] - s_lo_neigh_of_neigh[i]);
           }
           // Finally we must sort out the translation scheme
           Vector<unsigned> temp_translate(2);
           for (unsigned i = 0; i < 2; i++)
           {
             temp_translate[i] = translate_s_in_neigh[translate_s[i]];
           }
           for (unsigned i = 0; i < 2; i++)
           {
             translate_s[i] = temp_translate[i];
           }
         } // End of special treatment for periodic hanging nodes
         // Number of nodes in one dimension
         unsigned n_p = ninterpolating_node_1d(value_id);
         // Storage for the local nodes along the edge of the quadtree
         Node* local_node_pt = 0;
         // Loop over nodes along the edge
         for (unsigned i0 = 0; i0 < n_p; i0++)
         {
           // Storage for the fractional position of the node in the element
           Vector<double> s_fraction(2);
           // Find the local node and the fractional position of the node
           // which depends on the edge, of course
           switch (my_edge)
           {
             case N:
               s_fraction[0] =
                 local_one_d_fraction_of_interpolating_node(i0, 0, value_id);
               s_fraction[1] = 1.0;
               local_node_pt =
                 interpolating_node_pt(i0 + n_p * (n_p - 1), value_id);
               break;
             case S:
               s_fraction[0] =
                 local_one_d_fraction_of_interpolating_node(i0, 0, value_id);
               s_fraction[1] = 0.0;
               local_node_pt = interpolating_node_pt(i0, value_id);
               break;
             case E:
               s_fraction[0] = 1.0;
               s_fraction[1] =
                 local_one_d_fraction_of_interpolating_node(i0, 1, value_id);
               local_node_pt =
                 interpolating_node_pt(n_p - 1 + n_p * i0, value_id);
               break;
             case W:
               s_fraction[0] = 0.0;
               s_fraction[1] =
                 local_one_d_fraction_of_interpolating_node(i0, 1, value_id);
               local_node_pt = interpolating_node_pt(n_p * i0, value_id);
               break;
             default:
               throw OomphLibError("my_edge not N, S, W, E\n",
                                   OOMPH_CURRENT_FUNCTION,
                                   OOMPH_EXCEPTION_LOCATION);
           }
           // Calculate the local coordinates of the node in the neighbour
           Vector<double> s_in_neighb(2);
           for (unsigned i = 0; i < 2; i++)
           {
             s_in_neighb[i] = s_lo_neigh[i] + s_fraction[translate_s[i]] *
                                                (s_hi_neigh[i] - s_lo_neigh[i]);
           }
           // Find the Node in the neighbouring element
           Node* neighbouring_node_pt =
             neigh_pt->object_pt()->get_interpolating_node_at_local_coordinate(
               s_in_neighb, value_id);
           // If the neighbour does not have a node at this point
           if (0 == neighbouring_node_pt)
           {
             // Do we need to make a hanging node, we assume that we don't
             // initially
             bool make_hanging_node = false;
             // If the node is not hanging geometrically, then we must make
             // it hang
             if (!local_node_pt->is_hanging())
             {
               make_hanging_node = true;
             }
             // Otherwise, it could be hanging geometrically, but still
             // require a different hanging scheme for this data value
             else
             {
               if (local_node_pt->hanging_pt(value_id) ==
                   local_node_pt->hanging_pt())
               {
                 make_hanging_node = true;
               }
             }
             // If we do need to make the hanging node, then let's do it
             if (make_hanging_node == true)
             {
               // Cache refineable element used here
               RefineableElement* const obj_pt = neigh_pt->object_pt();
               // Get shape functions in neighbour element
               Shape psi(obj_pt->ninterpolating_node(value_id));
               obj_pt->interpolating_basis(s_in_neighb, psi, value_id);
               // Allocate the storage for the Hang pointer
               // which contains n_p nodes
               HangInfo* hang_pt = new HangInfo(n_p);
               // Loop over nodes on edge in neighbour and mark them as nodes
               // that this node depends on
               unsigned n_neighbour;
               // Number of nodes along edge in neighbour element
               for (unsigned n_edge = 0; n_edge < n_p; n_edge++)
               {
                 switch (neigh_edge)
                 {
                   case N:
                     n_neighbour = n_p * (n_p - 1) + n_edge;
                     break;
                   case S:
                     n_neighbour = n_edge;
                     break;
                   case W:
                     n_neighbour = n_p * n_edge;
                     break;
                   case E:
                     n_neighbour = n_p * n_edge + (n_p - 1);
                     break;
                   default:
                     throw OomphLibError("neigh_edge not N, S, W, E\n",
                                         OOMPH_CURRENT_FUNCTION,
                                         OOMPH_EXCEPTION_LOCATION);
                 }
                 // Push back neighbouring node and weight into
                 // Vector of (pointers to)
                 // master nodes and weights
                 // The weight is merely the value of the shape function
                 // corresponding to the node in the neighbour
                 hang_pt->set_master_node_pt(
                   n_edge,
                   obj_pt->interpolating_node_pt(n_neighbour, value_id),
                   psi[n_neighbour]);
               }
               // Now set the hanging data for the position
               // This also constrains the data values associated with the
               // value id
               local_node_pt->set_hanging_pt(hang_pt, value_id);
             }
             // Dump the output if the file has been openeed
             if (output_hangfile.is_open())
             {
               output_hangfile << local_node_pt->x(0) << " "
                               << local_node_pt->x(1) << std::endl;
             }
           }
           // Otherwise check that the nodes are the same
           else
           {
 #ifdef PARANOID
             if (local_node_pt != neighbouring_node_pt)
             {
               std::ostringstream warning_stream;
               warning_stream << "SANITY CHECK in quad_hang_helper      \n"
                              << "Current node      " << local_node_pt << " at "
                              << "(" << local_node_pt->x(0) << ", "
                              << local_node_pt->x(1) << ")"
                              << " is not hanging and has " << std::endl
                              << "Neighbour's node  " << neighbouring_node_pt
                              << " at "
                              << "(" << neighbouring_node_pt->x(0) << ", "
                              << neighbouring_node_pt->x(1) << ")" << std::endl
                              << "even though the two should be "
                              << "identical" << std::endl;
               OomphLibWarning(warning_stream.str(),
                               "RefineableQElement<2>::quad_hang_helper()",
                               OOMPH_EXCEPTION_LOCATION);
             }
 #endif
           }
           // If we are doing the position, then
           if (value_id == -1)
           {
             // Get the nodal position from neighbour element
             Vector<double> x_in_neighb(2);
             neigh_pt->object_pt()->interpolated_x(s_in_neighb, x_in_neighb);
             // Fine adjust the coordinates (macro map will pick up boundary
             // accurately but will lead to different element edges)
             local_node_pt->x(0) = x_in_neighb[0];
             local_node_pt->x(1) = x_in_neighb[1];
           }
         }
       }
     }
   }
References Global_Physical_Variables::E, oomph::RefineableElement::get_interpolating_node_at_local_coordinate(), oomph::QuadTree::gteq_edge_neighbour(), oomph::Node::hanging_pt(), i, oomph::FiniteElement::interpolated_x(), oomph::RefineableElement::interpolating_basis(), oomph::RefineableElement::interpolating_node_pt(), oomph::Node::is_hanging(), N, oomph::RefineableElement::ninterpolating_node(), oomph::Tree::object_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::QuadTreeNames::S, oomph::FiniteElement::s_max(), oomph::FiniteElement::s_min(), oomph::Node::set_hanging_pt(), oomph::HangInfo::set_master_node_pt(), oomph::QuadTreeNames::W, and oomph::Node::x().
quadtree_pt() [1/2]
QuadTree* oomph::RefineableQElement< 2 >::quadtree_pt () inline
Pointer to quadtree representation of this element.
     {
       return dynamic_cast<QuadTree*>(Tree_pt);
     }
Referenced by oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::further_build(), oomph::RefineableAxisymmetricQCrouzeixRaviartElement::further_build(), oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::further_build(), oomph::RefineableLinearisedQCrouzeixRaviartElement::further_build(), oomph::RefineablePolarCrouzeixRaviartElement::further_build(), oomph::RefineableQSphericalCrouzeixRaviartElement::further_build(), oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::rebuild_from_sons(), oomph::RefineableAxisymmetricQCrouzeixRaviartElement::rebuild_from_sons(), oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::rebuild_from_sons(), oomph::RefineableLinearisedQCrouzeixRaviartElement::rebuild_from_sons(), oomph::RefineablePolarCrouzeixRaviartElement::rebuild_from_sons(), and oomph::RefineableQSphericalCrouzeixRaviartElement::rebuild_from_sons().
quadtree_pt() [2/2]
QuadTree* oomph::RefineableQElement< 2 >::quadtree_pt () const inline
Pointer to quadtree representation of this element.
     {
       return dynamic_cast<QuadTree*>(Tree_pt);
     }
required_nsons()
unsigned oomph::RefineableQElement< 2 >::required_nsons () const inline virtual
A refineable quad element has four sons.
Reimplemented from oomph::RefineableElement.
     {
       return 4;
     }
setup_father_bounds()
void oomph::RefineableQElement< 2 >::setup_father_bounds () protected
Setup static matrix for coincidence between son nodal points and father boundaries
Setup static matrix for coincidence between son nodal points and father boundaries:
Father_boundd[nnode_1d](nnode_son,son_type)={SW/SE/NW/NE/S/E/N/W/OMEGA}
so that node nnode_son in element of type son_type lies on boundary/vertex Father_boundd[nnode_1d](nnode_son,son_type) in its father element. If the node doesn't lie on a boundary the value is OMEGA.
   {
     using namespace QuadTreeNames;
     // Find the number of nodes along a 1D edge
     unsigned n_p = nnode_1d();
     // Allocate space for the boundary information
     Father_bound[n_p].resize(n_p * n_p, 4);
     // Initialise: By default points are not on the boundary
     for (unsigned n = 0; n < n_p * n_p; n++)
     {
       for (unsigned ison = 0; ison < 4; ison++)
       {
         Father_bound[n_p](n, ison) = Tree::OMEGA;
       }
     }
     // Southwest son
     //--------------
     // SW node (0) is the SW node of the parent
     Father_bound[n_p](0, SW) = SW;
     // Southern boundary is the southern boundary of the parent
     for (unsigned n = 1; n < n_p; n++)
     {
       Father_bound[n_p](n, SW) = S;
     }
     // Western boundary is the western boundary of the parent
     for (unsigned n = 1; n < n_p; n++)
     {
       Father_bound[n_p](n_p * n, SW) = W;
     }
     // Other boundaries are in the interior
     // Northwest son
     //--------------
     // NW node (n_p*(n_p-1))is the NW node of the parent
     Father_bound[n_p](n_p * (n_p - 1), NW) = NW;
     // Northern boundary is the northern boundary of the parent
     for (unsigned n = 1; n < n_p; n++)
     {
       Father_bound[n_p](n_p * (n_p - 1) + n, NW) = N;
     }
     // Western boundary is the western boundary of the parent
     for (unsigned n = 0; n < (n_p - 1); n++)
     {
       Father_bound[n_p](n_p * n, NW) = W;
     }
     // Other boundaries are in the interior
     // Northeast son
     //--------------
     // NE node (n_p*n_p-1) is the NE node of the parent
     Father_bound[n_p](n_p * n_p - 1, NE) = NE;
     // Northern boundary is the northern boundary of the parent
     for (unsigned n = 0; n < (n_p - 1); n++)
     {
       Father_bound[n_p](n_p * (n_p - 1) + n, NE) = N;
     }
     // Eastern boundary is the eastern boundary of the parent
     for (unsigned n = 0; n < (n_p - 1); n++)
     {
       Father_bound[n_p](n_p - 1 + n_p * n, NE) = E;
     }
     // Other boundaries are in the interior
     // Southeast son
     //--------------
     // SE node (n_p-1) is the SE node of the parent
     Father_bound[n_p](n_p - 1, SE) = SE;
     // Southern boundary is the southern boundary of the parent
     for (unsigned n = 0; n < (n_p - 1); n++)
     {
       Father_bound[n_p](n, SE) = S;
     }
     // Eastern boundary is the eastern boundary of the parent
     for (unsigned n = 1; n < n_p; n++)
     {
       Father_bound[n_p](n_p - 1 + n_p * n, SE) = E;
     }
   }
References Global_Physical_Variables::E, n, N, oomph::QuadTreeNames::NE, oomph::QuadTreeNames::NW, oomph::Tree::OMEGA, oomph::QuadTreeNames::S, oomph::QuadTreeNames::SE, oomph::QuadTreeNames::SW, and oomph::QuadTreeNames::W.
setup_hang_for_value()
void oomph::RefineableQElement< 2 >::setup_hang_for_value (const int & value_id) protected
Internal helper function that is used to construct the hanging node schemes for the value_id-th interpolated value
Internal function that sets up the hanging node scheme for a particular continuously interpolated value
   {
     using namespace QuadTreeNames;
     std::ofstream dummy_hangfile;
     quad_hang_helper(value_id, S, dummy_hangfile);
     quad_hang_helper(value_id, N, dummy_hangfile);
     quad_hang_helper(value_id, W, dummy_hangfile);
     quad_hang_helper(value_id, E, dummy_hangfile);
   }
References Global_Physical_Variables::E, N, oomph::QuadTreeNames::S, and oomph::QuadTreeNames::W.
Referenced by oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::further_setup_hanging_nodes(), oomph::RefineableAxisymmetricQTaylorHoodElement::further_setup_hanging_nodes(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::further_setup_hanging_nodes(), oomph::RefineableLinearisedQTaylorHoodElement::further_setup_hanging_nodes(), oomph::RefineablePolarTaylorHoodElement::further_setup_hanging_nodes(), and oomph::RefineableQSphericalTaylorHoodElement::further_setup_hanging_nodes().
setup_hanging_nodes()
void oomph::RefineableQElement< 2 >::setup_hanging_nodes (Vector< std::ofstream * > & output_stream) virtual
Markup all hanging nodes & document the results in the output streams contained in the vector output_stream, if they are open.
Set up all hanging nodes. If we are documenting the output then open the output files and pass the open files to the helper function
Reimplemented from oomph::RefineableElement.
   {
 #ifdef PARANOID
     if (output_stream.size() != 4)
     {
       throw OomphLibError("There must be four output streams",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     using namespace QuadTreeNames;
     // Setup hanging nodes on each edge of the element
     quad_hang_helper(-1, S, *(output_stream[0]));
     quad_hang_helper(-1, N, *(output_stream[1]));
     quad_hang_helper(-1, W, *(output_stream[2]));
     quad_hang_helper(-1, E, *(output_stream[3]));
   }
References Global_Physical_Variables::E, N, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::QuadTreeNames::S, and oomph::QuadTreeNames::W.
Member Data Documentation
Father_bound
std::map< unsigned, DenseMatrix< int > > oomph::RefineableQElement< 2 >::Father_bound static protected
Coincidence between son nodal points and father boundaries: Father_bound[node_1d](jnod_son,son_type)={SW/SE/NW/NE/S/E/N/W/OMEGA}
Static matrix for coincidence between son nodal points and father boundaries
The documentation for this class was generated from the following files:
refineable_quad_element.h
refineable_quad_element.cc