MercuryDPM: Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ > Class Template Reference
Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ > Class Template Reference
#include <IndexedViewHelper.h>
Public Member Functions
constexpr ArithmeticSequenceRange (Index first, Index size, Index incr)
constexpr Index operator[] (Index i) const
constexpr Index first () const noexcept
constexpr Index size () const noexcept
constexpr Index incr () const noexcept
Static Public Attributes
static constexpr Index FirstAtCompileTime = FirstAtCompileTime_
static constexpr Index SizeAtCompileTime = SizeAtCompileTime_
static constexpr Index IncrAtCompileTime = IncrAtCompileTime_
Private Attributes
variable_if_dynamicindex< Index, int(FirstAtCompileTime)> first_
variable_if_dynamic< Index, int(SizeAtCompileTime)> size_
variable_if_dynamicindex< Index, int(IncrAtCompileTime)> incr_
Constructor & Destructor Documentation
ArithmeticSequenceRange()
template<Index FirstAtCompileTime_, Index SizeAtCompileTime_, Index IncrAtCompileTime_> constexpr Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::ArithmeticSequenceRange (Index first, Index size, Index incr) inline constexpr
 : first_{first}, size_{size}, incr_{incr} {}
Member Function Documentation
first()
template<Index FirstAtCompileTime_, Index SizeAtCompileTime_, Index IncrAtCompileTime_> constexpr Index Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::first () const inline constexpr noexcept
 { return first_.value(); }
References Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::first_, and Eigen::internal::variable_if_dynamicindex< T, Value >::value().
Referenced by Eigen::internal::IndexedViewHelper< ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >, void >::first(), and Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::operator[]().
incr()
template<Index FirstAtCompileTime_, Index SizeAtCompileTime_, Index IncrAtCompileTime_> constexpr Index Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::incr () const inline constexpr noexcept
 { return incr_.value(); }
References Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::incr_, and Eigen::internal::variable_if_dynamicindex< T, Value >::value().
Referenced by Eigen::internal::IndexedViewHelper< ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >, void >::incr(), and Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::operator[]().
operator[]()
template<Index FirstAtCompileTime_, Index SizeAtCompileTime_, Index IncrAtCompileTime_> constexpr Index Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::operator[] (Index i) const inline constexpr
 { return first() + i * incr(); }
References Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::first(), i, and Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::incr().
size()
template<Index FirstAtCompileTime_, Index SizeAtCompileTime_, Index IncrAtCompileTime_> constexpr Index Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::size () const inline constexpr noexcept
 { return size_.value(); }
References Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::size_, and Eigen::internal::variable_if_dynamic< T, Value >::value().
Referenced by Eigen::internal::IndexedViewHelper< ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >, void >::size().
Member Data Documentation
first_
template<Index FirstAtCompileTime_, Index SizeAtCompileTime_, Index IncrAtCompileTime_> variable_if_dynamicindex<Index, int(FirstAtCompileTime)> Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::first_ private
Referenced by Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::first().
FirstAtCompileTime
template<Index FirstAtCompileTime_, Index SizeAtCompileTime_, Index IncrAtCompileTime_> constexpr Index Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::FirstAtCompileTime = FirstAtCompileTime_ static constexpr
incr_
template<Index FirstAtCompileTime_, Index SizeAtCompileTime_, Index IncrAtCompileTime_> variable_if_dynamicindex<Index, int(IncrAtCompileTime)> Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::incr_ private
Referenced by Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::incr().
IncrAtCompileTime
template<Index FirstAtCompileTime_, Index SizeAtCompileTime_, Index IncrAtCompileTime_> constexpr Index Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::IncrAtCompileTime = IncrAtCompileTime_ static constexpr
size_
template<Index FirstAtCompileTime_, Index SizeAtCompileTime_, Index IncrAtCompileTime_> variable_if_dynamic<Index, int(SizeAtCompileTime)> Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::size_ private
Referenced by Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::size().
SizeAtCompileTime
template<Index FirstAtCompileTime_, Index SizeAtCompileTime_, Index IncrAtCompileTime_> constexpr Index Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::SizeAtCompileTime = SizeAtCompileTime_ static constexpr
The documentation for this class was generated from the following file:
IndexedViewHelper.h