MercuryDPM: Eigen::internal::trmv_selector< Mode, RowMajor > Struct Template Reference
Eigen::internal::trmv_selector< Mode, RowMajor > Struct Template Reference
#include <TriangularMatrixVector.h>
Static Public Member Functions
template<typename Lhs , typename Rhs , typename Dest >
static void run (const Lhs &lhs, const Rhs &rhs, Dest &dest, const typename Dest::Scalar &alpha)
Member Function Documentation
run()
template<int Mode> template<typename Lhs , typename Rhs , typename Dest > static void Eigen::internal::trmv_selector< Mode, RowMajor >::run (const Lhs & lhs, const Rhs & rhs, Dest & dest, const typename Dest::Scalar & alpha) inline static
{
     typedef typename Lhs::Scalar LhsScalar;
     typedef typename Rhs::Scalar RhsScalar;
     typedef typename Dest::Scalar ResScalar;
     typedef internal::blas_traits<Lhs> LhsBlasTraits;
     typedef typename LhsBlasTraits::DirectLinearAccessType ActualLhsType;
     typedef internal::blas_traits<Rhs> RhsBlasTraits;
     typedef typename RhsBlasTraits::DirectLinearAccessType ActualRhsType;
     typedef internal::remove_all_t<ActualRhsType> ActualRhsTypeCleaned;
     std::add_const_t<ActualLhsType> actualLhs = LhsBlasTraits::extract(lhs);
     std::add_const_t<ActualRhsType> actualRhs = RhsBlasTraits::extract(rhs);
     LhsScalar lhs_alpha = LhsBlasTraits::extractScalarFactor(lhs);
     RhsScalar rhs_alpha = RhsBlasTraits::extractScalarFactor(rhs);
     ResScalar actualAlpha = alpha * lhs_alpha * rhs_alpha;
     constexpr bool DirectlyUseRhs = ActualRhsTypeCleaned::InnerStrideAtCompileTime == 1;
     const RhsScalar* actualRhsPtr = actualRhs.data();
     // Potentially create a temporary buffer to copy RHS to contiguous memory.
     gemv_static_vector_if<RhsScalar, ActualRhsTypeCleaned::SizeAtCompileTime,
                           ActualRhsTypeCleaned::MaxSizeAtCompileTime, !DirectlyUseRhs>
         static_rhs;  // Fixed-sized array.
     RhsScalar* buffer = nullptr;
     if (!DirectlyUseRhs) {
       // Maybe used fixed-sized buffer, otherwise allocate.
       if (static_rhs.data() != nullptr) {
         buffer = static_rhs.data();
       } else {
         // Allocate either with alloca or malloc.
         Eigen::internal::check_size_for_overflow<RhsScalar>(actualRhs.size());
 #ifdef EIGEN_ALLOCA
         buffer = static_cast<RhsScalar*>((sizeof(RhsScalar) * actualRhs.size() <= EIGEN_STACK_ALLOCATION_LIMIT)
                                              ? EIGEN_ALIGNED_ALLOCA(sizeof(RhsScalar) * actualRhs.size())
                                              : Eigen::internal::aligned_malloc(sizeof(RhsScalar) * actualRhs.size()));
 #else
         buffer = static_cast<RhsScalar*>(Eigen::internal::aligned_malloc(sizeof(RhsScalar) * actualRhs.size()));
 #endif
       }
 #ifdef EIGEN_DENSE_STORAGE_CTOR_PLUGIN
       constexpr int Size = ActualRhsTypeCleaned::SizeAtCompileTime;
       Index size = actualRhs.size();
       EIGEN_DENSE_STORAGE_CTOR_PLUGIN
 #endif
       Map<typename ActualRhsTypeCleaned::PlainObject, Eigen::AlignedMax>(buffer, actualRhs.size()) = actualRhs;
       actualRhsPtr = buffer;
     }
     // Deallocate only if malloced.
     Eigen::internal::aligned_stack_memory_handler<RhsScalar> buffer_stack_memory_destructor(
         buffer, actualRhs.size(),
         !DirectlyUseRhs && static_rhs.data() == nullptr && actualRhs.size() > EIGEN_STACK_ALLOCATION_LIMIT);
     internal::triangular_matrix_vector_product<Index, Mode, LhsScalar, LhsBlasTraits::NeedToConjugate, RhsScalar,
                                                RhsBlasTraits::NeedToConjugate, RowMajor>::run(actualLhs.rows(),
                                                                                               actualLhs.cols(),
                                                                                               actualLhs.data(),
                                                                                               actualLhs.outerStride(),
                                                                                               actualRhsPtr, 1,
                                                                                               dest.data(),
                                                                                               dest.innerStride(),
                                                                                               actualAlpha);
     if (((Mode & UnitDiag) == UnitDiag) && !numext::is_exactly_one(lhs_alpha)) {
       Index diagSize = (std::min)(lhs.rows(), lhs.cols());
       dest.head(diagSize) -= (lhs_alpha - LhsScalar(1)) * rhs.head(diagSize);
     }
   }
References Eigen::internal::aligned_malloc(), alpha, EIGEN_STACK_ALLOCATION_LIMIT, Eigen::numext::is_exactly_one(), min, Eigen::RowMajor, Eigen::run(), size, and Eigen::UnitDiag.
The documentation for this struct was generated from the following file:
TriangularMatrixVector.h