MercuryDPM: oomph::RefineableQuarterTubeMesh< ELEMENT > Class Template Reference
oomph::RefineableQuarterTubeMesh< ELEMENT > Class Template Reference
#include <quarter_tube_mesh.template.h>
Public Member Functions
RefineableQuarterTubeMesh (GeomObject *wall_pt, const Vector< double > &xi_lo, const double &fract_mid, const Vector< double > &xi_hi, const unsigned &nlayer, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual ~RefineableQuarterTubeMesh ()
Destructor: empty.
Public Member Functions inherited from oomph::QuarterTubeMesh< ELEMENT >
QuarterTubeMesh (GeomObject *wall_pt, const Vector< double > &xi_lo, const double &fract_mid, const Vector< double > &xi_hi, const unsigned &nlayer, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual ~QuarterTubeMesh ()
Destructor: empty.
GeomObject *& wall_pt ()
Access function to GeomObject representing wall.
QuarterTubeDomain * domain_pt ()
Access function to domain.
QuarterTubeDomain::BLSquashFctPt & bl_squash_fct_pt ()
virtual QuarterTubeDomain::AxialSpacingFctPt & axial_spacing_fct_pt ()
Function pointer for function for axial spacing.
QuarterTubeDomain * domain_pt () const
Access function to underlying domain.
Public Member Functions inherited from oomph::BrickMeshBase
BrickMeshBase ()
Constructor (empty)
BrickMeshBase (const BrickMeshBase &)=delete
Broken copy constructor.
virtual ~BrickMeshBase ()
Broken assignment operator.
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Public Member Functions inherited from oomph::RefineableBrickMesh< ELEMENT >
RefineableBrickMesh ()
Constructor: Setup static octree data.
RefineableBrickMesh (const RefineableBrickMesh &dummy)=delete
Broken copy constructor.
void operator= (const RefineableBrickMesh &)=delete
Broken assignment operator.
virtual ~RefineableBrickMesh ()
Destructor:
virtual void setup_tree_forest ()
void setup_octree_forest ()
Do what it says...
Public Member Functions inherited from oomph::TreeBasedRefineableMesh< ELEMENT >
TreeBasedRefineableMesh ()
Constructor, call the constructor of the base class.
TreeBasedRefineableMesh (const TreeBasedRefineableMesh &dummy)=delete
Broken copy constructor.
virtual ~TreeBasedRefineableMesh ()
Empty virtual destructor.
Public Member Functions inherited from oomph::TreeBasedRefineableMeshBase
TreeBasedRefineableMeshBase ()
Constructor.
TreeBasedRefineableMeshBase (const TreeBasedRefineableMeshBase &dummy)=delete
Broken copy constructor.
void operator= (const TreeBasedRefineableMeshBase &)=delete
Broken assignment operator.
virtual ~TreeBasedRefineableMeshBase ()
Empty Destructor:
void adapt (const Vector< double > &elemental_error)
void p_adapt (const Vector< double > &elemental_error)
void refine_uniformly (DocInfo &doc_info)
Refine mesh uniformly and doc process.
void refine_uniformly ()
Refine mesh uniformly.
void p_refine_uniformly (DocInfo &doc_info)
p-refine mesh uniformly and doc process
void p_refine_uniformly ()
p-refine mesh uniformly
unsigned unrefine_uniformly ()
void p_unrefine_uniformly (DocInfo &doc_info)
p-unrefine mesh uniformly
TreeForest * forest_pt ()
Return pointer to the Forest represenation of the mesh.
void doc_adaptivity_targets (std::ostream &outfile)
Doc the targets for mesh adaptation.
unsigned & max_refinement_level ()
Access fct for max. permissible refinement level (relative to base mesh)
unsigned & min_refinement_level ()
Access fct for min. permissible refinement level (relative to base mesh)
unsigned & max_p_refinement_level ()
unsigned & min_p_refinement_level ()
virtual void adapt_mesh (DocInfo &doc_info)
virtual void adapt_mesh ()
void p_adapt_mesh (DocInfo &doc_info)
void p_adapt_mesh ()
virtual void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
virtual void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
p-refine mesh by refining the elements identified by their numbers.
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
p-refine mesh by refining the elements identified by their pointers.
virtual void refine_base_mesh_as_in_reference_mesh (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
Refine to same degree as the reference mesh.
virtual bool refine_base_mesh_as_in_reference_mesh_minus_one (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
virtual void refine_as_in_reference_mesh (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
virtual void get_refinement_levels (unsigned &min_refinement_level, unsigned &max_refinement_level)
Get max/min refinement levels in mesh.
virtual void get_elements_at_refinement_level (unsigned &refinement_level, Vector< RefineableElement * > &level_elements)
virtual void get_refinement_pattern (Vector< Vector< unsigned >> &to_be_refined)
void refine_base_mesh (Vector< Vector< unsigned >> &to_be_refined)
Refine base mesh according to specified refinement pattern.
virtual void refine (std::ifstream &restart_file)
Refine mesh according to refinement pattern in restart file.
virtual void dump_refinement (std::ostream &outfile)
Dump refinement pattern to allow for rebuild.
virtual void read_refinement (std::ifstream &restart_file, Vector< Vector< unsigned >> &to_be_refined)
Read refinement pattern to allow for rebuild.
unsigned uniform_refinement_level_when_pruned () const
unsigned & uniform_refinement_level_when_pruned ()
Level to which the mesh was uniformly refined when it was pruned.
Public Member Functions inherited from oomph::RefineableMeshBase
bool adapt_flag ()
RefineableMeshBase ()
RefineableMeshBase (const RefineableMeshBase &dummy)=delete
Broken copy constructor.
void operator= (const RefineableMeshBase &)=delete
Broken assignment operator.
virtual ~RefineableMeshBase ()
Empty Destructor:
unsigned nrefined ()
Access fct for number of elements that were refined.
unsigned nunrefined ()
Access fct for number of elements that were unrefined.
unsigned & nrefinement_overruled ()
unsigned & max_keep_unrefined ()
ErrorEstimator *& spatial_error_estimator_pt ()
Access to spatial error estimator.
ErrorEstimator * spatial_error_estimator_pt () const
Access to spatial error estimator (const version.
double & min_permitted_error ()
double & max_permitted_error ()
double & min_error ()
double & max_error ()
DocInfo *& doc_info_pt ()
Access fct for pointer to DocInfo.
void enable_adaptation ()
Enable adaptation.
void disable_adaptation ()
Disable adaptation.
void enable_p_adaptation ()
Enable adaptation.
void disable_p_adaptation ()
Disable adaptation.
void enable_additional_synchronisation_of_hanging_nodes ()
Enable additional synchronisation of hanging nodes.
void disable_additional_synchronisation_of_hanging_nodes ()
Disable additional synchronisation of hanging nodes.
bool is_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_p_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_additional_synchronisation_of_hanging_nodes_disabled () const
Return whether additional synchronisation is enabled.
DocInfo doc_info ()
Access fct for DocInfo.
void p_unrefine_uniformly (DocInfo &doc_info)
p-unrefine mesh uniformly
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Member Functions inherited from oomph::TreeBasedRefineableMeshBase
void complete_hanging_nodes (const int &ncont_interpolated_values)
Complete the hanging node scheme recursively.
void complete_hanging_nodes_recursively (Node *&nod_pt, Vector< Node * > &master_nodes, Vector< double > &hang_weights, const int &ival)
Auxiliary routine for recursive hanging node completion.
Protected Attributes inherited from oomph::QuarterTubeMesh< ELEMENT >
QuarterTubeDomain * Domain_pt
Pointer to domain.
GeomObject * Wall_pt
Pointer to the geometric object that represents the curved wall.
Vector< double > Xi_lo
Lower limits for the coordinates along the wall.
double Fract_mid
Fraction along wall where outer ring is to be divided.
Vector< double > Xi_hi
Upper limits for the coordinates along the wall.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Protected Attributes inherited from oomph::TreeBasedRefineableMeshBase
unsigned Uniform_refinement_level_when_pruned
Level to which the mesh was uniformly refined when it was pruned.
unsigned Max_refinement_level
Max. permissible refinement level (relative to base mesh)
unsigned Min_refinement_level
Min. permissible refinement level (relative to base mesh)
unsigned Max_p_refinement_level
Max. permissible p-refinement level (relative to base mesh)
unsigned Min_p_refinement_level
Min. permissible p-refinement level (relative to base mesh)
TreeForest * Forest_pt
Forest representation of the mesh.
Protected Attributes inherited from oomph::RefineableMeshBase
ErrorEstimator * Spatial_error_estimator_pt
Pointer to spatial error estimator.
double Max_permitted_error
Max. error (i.e. split elements if their error is larger)
double Min_permitted_error
Min. error (i.e. (try to) merge elements if their error is smaller)
double Min_error
Min.actual error.
double Max_error
Max. actual error.
unsigned Nrefined
Stats: Number of elements that were refined.
unsigned Nunrefined
Stats: Number of elements that were unrefined.
bool Adapt_flag
Flag that requests adaptation.
bool P_adapt_flag
Flag that requests p-adaptation.
bool Additional_synchronisation_of_hanging_nodes_not_required
Flag that disables additional synchronisation of hanging nodes.
DocInfo * Doc_info_pt
Pointer to DocInfo.
unsigned Max_keep_unrefined
unsigned Nrefinement_overruled
Detailed Description
template<class ELEMENT>
class oomph::RefineableQuarterTubeMesh< ELEMENT >
///////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////// Adaptative version of the QuarterTubeMesh base mesh. The domain is specified by the GeomObject that identifies boundary 3.
The mesh boundaries are numbered as follows:
Boundary 0: "Inflow" cross section; located along the line parametrised by \(\xi_0 = \xi_0^{lo} \) on the geometric object that specifies the wall.
Boundary 1: Plane x=0
Boundary 2: Plane y=0
Boundary 3: The curved wall
Boundary 4: "Outflow" cross section; located along the line parametrised by \(\xi_0 = \xi_0^{hi} \) on the geometric object that specifies the wall.
Constructor & Destructor Documentation
RefineableQuarterTubeMesh()
template<class ELEMENT > oomph::RefineableQuarterTubeMesh< ELEMENT >::RefineableQuarterTubeMesh (GeomObject * wall_pt, const Vector< double > & xi_lo, const double & fract_mid, const Vector< double > & xi_hi, const unsigned & nlayer, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Constructor for adaptive deformable quarter tube mesh class. The domain is specified by the GeomObject that identifies boundary 3. Pass pointer to geometric object that specifies the wall, start and end coordinates on the geometric object, and the fraction along which the dividing line is to be placed, and the timestepper. Timestepper defaults to Steady dummy timestepper.
       : QuarterTubeMesh<ELEMENT>(
           wall_pt, xi_lo, fract_mid, xi_hi, nlayer, time_stepper_pt)
     {
       // Loop over all elements and set macro element pointer
       for (unsigned ielem = 0; ielem < QuarterTubeMesh<ELEMENT>::nelement();
            ielem++)
       {
         dynamic_cast<RefineableQElement<3>*>(
           QuarterTubeMesh<ELEMENT>::element_pt(ielem))
           ->set_macro_elem_pt(this->Domain_pt->macro_element_pt(ielem));
       }
       // Setup Octree forest: Turn elements into individual octrees
       // and plant in forest
       Vector<TreeRoot*> trees_pt;
       for (unsigned iel = 0; iel < QuarterTubeMesh<ELEMENT>::nelement(); iel++)
       {
         FiniteElement* el_pt = QuarterTubeMesh<ELEMENT>::finite_element_pt(iel);
         ELEMENT* ref_el_pt = dynamic_cast<ELEMENT*>(el_pt);
         OcTreeRoot* octree_root_pt = new OcTreeRoot(ref_el_pt);
         trees_pt.push_back(octree_root_pt);
       }
       this->Forest_pt = new OcTreeForest(trees_pt);
 #ifdef PARANOID
       // Run self test
       unsigned success_flag =
         dynamic_cast<OcTreeForest*>(this->Forest_pt)->self_test();
       if (success_flag == 0)
       {
         oomph_info << "Successfully built octree forest " << std::endl;
       }
       else
       {
         throw OomphLibError("Trouble in building octree forest ",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
     }
References oomph::QuarterTubeMesh< ELEMENT >::Domain_pt, oomph::Mesh::element_pt(), oomph::Mesh::finite_element_pt(), oomph::TreeBasedRefineableMeshBase::Forest_pt, oomph::Domain::macro_element_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, and oomph::Mesh::self_test().
~RefineableQuarterTubeMesh()
template<class ELEMENT > virtual oomph::RefineableQuarterTubeMesh< ELEMENT >::~RefineableQuarterTubeMesh () inline virtual
Destructor: empty.
 {}
The documentation for this class was generated from the following file:
quarter_tube_mesh.template.h