MercuryDPM: Eigen::internal::triangular_dense_assignment_kernel< UpLo, SelfAdjoint, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version > Class Template Reference
Eigen::internal::triangular_dense_assignment_kernel< UpLo, SelfAdjoint, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version > Class Template Reference
#include <SelfAdjointView.h>
Public Types
typedef Base::DstEvaluatorType DstEvaluatorType
typedef Base::SrcEvaluatorType SrcEvaluatorType
typedef Base::Scalar Scalar
typedef Base::AssignmentTraits AssignmentTraits
Public Types inherited from Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >
typedef DstEvaluatorTypeT DstEvaluatorType
typedef SrcEvaluatorTypeT SrcEvaluatorType
typedef DstEvaluatorType::Scalar Scalar
typedef copy_using_evaluator_traits< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor > AssignmentTraits
typedef AssignmentTraits::PacketType PacketType
Public Member Functions
EIGEN_DEVICE_FUNC triangular_dense_assignment_kernel (DstEvaluatorType &dst, const SrcEvaluatorType &src, const Functor &func, DstXprType &dstExpr)
EIGEN_DEVICE_FUNC void assignCoeff (Index row, Index col)
EIGEN_DEVICE_FUNC void assignDiagonalCoeff (Index id)
EIGEN_DEVICE_FUNC void assignOppositeCoeff (Index, Index)
Public Member Functions inherited from Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE generic_dense_assignment_kernel (DstEvaluatorType &dst, const SrcEvaluatorType &src, const Functor &func, DstXprType &dstExpr)
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index innerSize () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index outerSize () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index outerStride () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC DstEvaluatorType & dstEvaluator () EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC const SrcEvaluatorType & srcEvaluator () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignCoeff (Index row, Index col)
Assign src(row,col) to dst(row,col) through the assignment functor.
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignCoeff (Index index)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignCoeffByOuterInner (Index outer, Index inner)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignPacket (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignPacket (Index index)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignPacketByOuterInner (Index outer, Index inner)
EIGEN_DEVICE_FUNC const Scalar * dstDataPtr () const
Protected Types
typedef generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version > Base
typedef Base::DstXprType DstXprType
typedef Base::SrcXprType SrcXprType
Protected Types inherited from Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >
typedef DstEvaluatorTypeT::XprType DstXprType
typedef SrcEvaluatorTypeT::XprType SrcXprType
Additional Inherited Members
Static Public Member Functions inherited from Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rowIndexByOuterInner (Index outer, Index inner)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index colIndexByOuterInner (Index outer, Index inner)
Protected Attributes inherited from Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >
DstEvaluatorType & m_dst
const SrcEvaluatorType & m_src
const Functor & m_functor
DstXprType & m_dstExpr
Member Typedef Documentation
AssignmentTraits
template<int UpLo, int SetOpposite, typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version> typedef Base::AssignmentTraits Eigen::internal::triangular_dense_assignment_kernel< UpLo, SelfAdjoint, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::AssignmentTraits
Base
template<int UpLo, int SetOpposite, typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version> typedef generic_dense_assignment_kernel<DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version> Eigen::internal::triangular_dense_assignment_kernel< UpLo, SelfAdjoint, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::Base protected
DstEvaluatorType
template<int UpLo, int SetOpposite, typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version> typedef Base::DstEvaluatorType Eigen::internal::triangular_dense_assignment_kernel< UpLo, SelfAdjoint, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::DstEvaluatorType
DstXprType
template<int UpLo, int SetOpposite, typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version> typedef Base::DstXprType Eigen::internal::triangular_dense_assignment_kernel< UpLo, SelfAdjoint, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::DstXprType protected
Scalar
template<int UpLo, int SetOpposite, typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version> typedef Base::Scalar Eigen::internal::triangular_dense_assignment_kernel< UpLo, SelfAdjoint, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::Scalar
SrcEvaluatorType
template<int UpLo, int SetOpposite, typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version> typedef Base::SrcEvaluatorType Eigen::internal::triangular_dense_assignment_kernel< UpLo, SelfAdjoint, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::SrcEvaluatorType
SrcXprType
template<int UpLo, int SetOpposite, typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version> typedef Base::SrcXprType Eigen::internal::triangular_dense_assignment_kernel< UpLo, SelfAdjoint, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::SrcXprType protected
Constructor & Destructor Documentation
triangular_dense_assignment_kernel()
template<int UpLo, int SetOpposite, typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version> EIGEN_DEVICE_FUNC Eigen::internal::triangular_dense_assignment_kernel< UpLo, SelfAdjoint, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::triangular_dense_assignment_kernel (DstEvaluatorType & dst, const SrcEvaluatorType & src, const Functor & func, DstXprType & dstExpr) inline
       : Base(dst, src, func, dstExpr) {}
Member Function Documentation
assignCoeff()
template<int UpLo, int SetOpposite, typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version> EIGEN_DEVICE_FUNC void Eigen::internal::triangular_dense_assignment_kernel< UpLo, SelfAdjoint, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignCoeff (Index row, Index col) inline
{
     eigen_internal_assert(row != col);
     Scalar tmp = m_src.coeff(row, col);
     m_functor.assignCoeff(m_dst.coeffRef(row, col), tmp);
     m_functor.assignCoeff(m_dst.coeffRef(col, row), numext::conj(tmp));
   }
References col(), conj(), eigen_internal_assert, Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Specialized >::m_dst, Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Specialized >::m_functor, Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Specialized >::m_src, row(), and tmp.
assignDiagonalCoeff()
template<int UpLo, int SetOpposite, typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version> EIGEN_DEVICE_FUNC void Eigen::internal::triangular_dense_assignment_kernel< UpLo, SelfAdjoint, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignDiagonalCoeff (Index id) inline
 { Base::assignCoeff(id, id); }
References Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignCoeff().
assignOppositeCoeff()
template<int UpLo, int SetOpposite, typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version> EIGEN_DEVICE_FUNC void Eigen::internal::triangular_dense_assignment_kernel< UpLo, SelfAdjoint, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignOppositeCoeff (Index , Index) inline
 { eigen_internal_assert(false && "should never be called"); }
References eigen_internal_assert.
The documentation for this class was generated from the following file:
SelfAdjointView.h