MercuryDPM: oomph::BlockPrecQTaylorHoodMixedOrderSpaceTimeElement Class Reference
oomph::BlockPrecQTaylorHoodMixedOrderSpaceTimeElement Class Reference
#include <mixed_order_petrov_galerkin_space_time_block_preconditionable_elements.h>
Public Member Functions
BlockPrecQTaylorHoodMixedOrderSpaceTimeElement ()
Empty constructor.
~BlockPrecQTaylorHoodMixedOrderSpaceTimeElement ()
Empty destructor.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
The setup function...
Public Member Functions inherited from oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >
QTaylorHoodMixedOrderSpaceTimeElement ()
Constructor, no internal data points.
~QTaylorHoodMixedOrderSpaceTimeElement ()
virtual unsigned required_nvalue (const unsigned &n) const
Node * pressure_node_pt (const unsigned &n_p)
Pointer to n_p-th pressure node.
int element_node_index_to_pressure_node_index (const unsigned &n)
bool is_pressure_node (const unsigned &n) const
void shape_u_nst (const Vector< double > &s, Shape &psi) const
DRAIG: Fill in later...
void shape_u_nst (const Vector< double > &s, Shape &psi) const
2D (in space): Velocity shape functions
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
void pshape_nst (const Vector< double > &s, Shape &psi) const
2D (in space): Pressure shape functions
void ptest_nst (const Vector< double > &s, Shape &psi) const
Pressure test functions at local coordinate s.
void ptest_nst (const Vector< double > &s, Shape &test) const
2D (in space): Pressure shape functions
virtual int p_nodal_index_nst () const
Set the value at which the pressure is stored in the nodes.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
double p_nst (const unsigned &n_p) const
double p_nst (const unsigned &t, const unsigned &n_p) const
unsigned npres_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)
void identify_load_data (std::set< std::pair< Data *, unsigned >> &paired_load_data)
void identify_pressure_data (std::set< std::pair< Data *, unsigned >> &paired_pressure_data)
void output (std::ostream &outfile)
Redirect output to NavierStokesMixedOrderEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesMixedOrderEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesMixedOrderEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to NavierStokesMixedOrderEquations output.
Public Member Functions inherited from oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >
SpaceTimeNavierStokesMixedOrderEquations ()
void store_reynolds_strouhal_as_external_data (Data *reynolds_strouhal_data_pt)
Function that tells us whether the period is stored as external data.
bool is_reynolds_strouhal_stored_as_external_data () const
Are we storing the Strouhal number as external data?
const double & re () const
Reynolds number.
double *& re_pt ()
Pointer to Reynolds number.
const double & re_st () const
ReSt parameter (const. version)
double * re_st_pt () const
Pointer to Strouhal parameter (const. version)
double *& re_st_pt ()
Pointer to ReSt number (can only assign to private member data)
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
NavierStokesMixedOrderBodyForceFctPt & body_force_fct_pt ()
Access function for the body-force pointer.
NavierStokesMixedOrderBodyForceFctPt body_force_fct_pt () const
Access function for the body-force pointer. Const version.
NavierStokesMixedOrderSourceFctPt & source_fct_pt ()
Access function for the source-function pointer.
NavierStokesMixedOrderSourceFctPt source_fct_pt () const
Access function for the source-function pointer. Const version.
NavierStokesMixedOrderPressureAdvDiffSourceFctPt & source_fct_for_pressure_adv_diff ()
NavierStokesMixedOrderPressureAdvDiffSourceFctPt source_fct_for_pressure_adv_diff () const
int & pinned_fp_pressure_eqn ()
double u_nst (const unsigned &n, const unsigned &i) const
double u_nst (const unsigned &t, const unsigned &n, const unsigned &i) const
virtual unsigned u_index_nst (const unsigned &i) const
unsigned n_u_nst () const
double get_du_dt (const unsigned &n, const unsigned &i) const
double du_dt_nst (const unsigned &n, const unsigned &i) const
double interpolated_du_dt_nst (const Vector< double > &s, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
double pressure_integral () const
Integral of pressure over element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute the vorticity vector at local coordinate s.
void get_vorticity (const Vector< double > &s, double &vorticity) const
Compute the vorticity vector at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
double d_kin_energy_dt () const
Get integral of time derivative of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j+du_j/dx_i)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction_p, Vector< double > &traction_visc_n, Vector< double > &traction_visc_t)
void get_load (const Vector< double > &s, const Vector< double > &N, Vector< double > &load)
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
std::string scalar_name_paraview (const unsigned &i) const
void full_output (std::ostream &outfile)
void full_output (std::ostream &outfile, const unsigned &n_plot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void output_vorticity (std::ostream &outfile, const unsigned &nplot)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_norm (Vector< double > &norm)
Compute the vector norm of the FEM solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
void fill_in_pressure_advection_diffusion_residuals (Vector< double > &residuals)
void fill_in_pressure_advection_diffusion_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void pin_all_non_pressure_dofs (std::map< Data *, std::vector< int >> &eqn_number_backup)
Pin all non-pressure dofs and backup eqn numbers.
void output_pressure_advection_diffusion_robin_elements (std::ostream &outfile)
void delete_pressure_advection_diffusion_robin_elements ()
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
void interpolated_u_nst (const Vector< double > &s, Vector< double > &velocity) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void dinterpolated_u_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
virtual double interpolated_p_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_p_nst (const unsigned &t, const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s at time level t.
void point_output_data (const Vector< double > &s, Vector< double > &data)
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
void get_vorticity (const Vector< double > &s, double &vorticity) const
Public Member Functions inherited from oomph::FSIFluidElement
FSIFluidElement ()
Constructor.
FSIFluidElement (const FSIFluidElement &)=delete
Broken copy constructor.
void operator= (const FSIFluidElement &)=delete
Broken assignment operator.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (double &norm)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::TemplateFreeSpaceTimeNavierStokesMixedOrderEquationsBase
TemplateFreeSpaceTimeNavierStokesMixedOrderEquationsBase ()
Constructor (empty)
virtual ~TemplateFreeSpaceTimeNavierStokesMixedOrderEquationsBase ()
Virtual destructor (empty)
Public Member Functions inherited from oomph::NavierStokesElementWithDiagonalMassMatrices
NavierStokesElementWithDiagonalMassMatrices ()
Empty constructor.
virtual ~NavierStokesElementWithDiagonalMassMatrices ()
Virtual destructor.
NavierStokesElementWithDiagonalMassMatrices (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken copy constructor.
void operator= (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken assignment operator.
Public Member Functions inherited from oomph::BlockPreconditionableSpaceTimeElementBase
BlockPreconditionableSpaceTimeElementBase ()
Constructor (empty)
~BlockPreconditionableSpaceTimeElementBase ()
Destructor (empty)
void set_time_slab_id (const int &time_slice_id)
Access function to assign the time slice this element lies in.
void set_ndof_types (const unsigned &n_dof_types)
unsigned ndof_types () const
Additional Inherited Members
Public Types inherited from oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >
typedef void(* NavierStokesMixedOrderBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
typedef double(* NavierStokesMixedOrderSourceFctPt) (const double &time, const Vector< double > &x)
Function pointer to source function fct(t,x) (x is a Vector!)
typedef double(* NavierStokesMixedOrderPressureAdvDiffSourceFctPt) (const Vector< double > &x)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Attributes inherited from oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >
static Vector< double > Gamma
Navier-Stokes equations static data.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions inherited from oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >
const unsigned Pconv [8]
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
void dshape_local_u_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
DRAIG: Fill in later...
void dshape_local_u_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
2D (in space): Velocity shape functions and derivs w.r.t. local coords
void dtest_local_u_nst (const Vector< double > &s, Shape &test, DShape &dtestdx) const
DRAIG: Fill in later...
void dtest_local_u_nst (const Vector< double > &s, Shape &test, DShape &dtestdx) const
2D (in space): Velocity test functions and derivs w.r.t. local coords
double dpshape_eulerian (const Vector< double > &s, Shape &ppsi, DShape &dppsidx) const
double dpshape_eulerian (const Vector< double > &s, Shape &ppsi, DShape &dppsidx) const
double dptest_eulerian (const Vector< double > &s, Shape &ptest, DShape &dptestdx) const
double dptest_eulerian (const Vector< double > &s, Shape &ptest, DShape &dptestdx) const
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Protected Member Functions inherited from oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >
virtual void get_body_force_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
virtual void get_body_force_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
virtual double get_source_nst (const double &time, const unsigned &ipt, const Vector< double > &x)
Calculate the source fct at a given time and Eulerian position.
virtual void get_source_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
virtual void fill_in_generic_residual_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, const unsigned &flag)
virtual void fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
virtual void fill_in_generic_dresidual_contribution_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, const unsigned &flag)
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes inherited from oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
bool ReynoldsStrouhal_is_stored_as_external_data
double * ReInvFr_pt
Vector< double > * G_pt
Pointer to global gravity Vector.
NavierStokesMixedOrderBodyForceFctPt Body_force_fct_pt
Pointer to body force function.
NavierStokesMixedOrderSourceFctPt Source_fct_pt
Pointer to volumetric source function.
NavierStokesMixedOrderPressureAdvDiffSourceFctPt Press_adv_diff_source_fct_pt
bool ALE_is_disabled
Vector< FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElementBase * > Pressure_advection_diffusion_robin_element_pt
int Pinned_fp_pressure_eqn
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::BlockPreconditionableSpaceTimeElementBase
unsigned N_dof_types
The number of time slices in the mesh.
int Time_slab_id
The time slice this element lies within.
Static Protected Attributes inherited from oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >
static const unsigned Pconv []
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
Block preconditionable version of the QTaylorHoodMixedOrderSpaceTimeElement
Constructor & Destructor Documentation
BlockPrecQTaylorHoodMixedOrderSpaceTimeElement()
oomph::BlockPrecQTaylorHoodMixedOrderSpaceTimeElement::BlockPrecQTaylorHoodMixedOrderSpaceTimeElement () inline
Empty constructor.
       : QTaylorHoodMixedOrderSpaceTimeElement<2>(),
         BlockPreconditionableSpaceTimeElementBase()
     {
     }
~BlockPrecQTaylorHoodMixedOrderSpaceTimeElement()
oomph::BlockPrecQTaylorHoodMixedOrderSpaceTimeElement::~BlockPrecQTaylorHoodMixedOrderSpaceTimeElement () inline
Empty destructor.
 {}
Member Function Documentation
get_dof_numbers_for_unknowns()
void oomph::BlockPrecQTaylorHoodMixedOrderSpaceTimeElement::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> & dof_lookup_list) const virtual
The setup function...
Overload the pure virtual base class implementation. Create a list of pairs for all unknowns in this element, so the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the "DOF type" that this unknown is associated with.
Implements oomph::BlockPreconditionableSpaceTimeElementBase.
   {
     // Number of nodes
     unsigned n_node = this->nnode();
     // Temporary pair (used to store dof lookup prior to being added to list)
     std::pair<unsigned, unsigned> dof_lookup;
     // The number of nodes in the each direction
     unsigned n_node_1d = this->nnode_1d();
     // Make sure that we're using quadratic interpolation otherwise this might
     // go wrong...
     if (n_node_1d != 3)
     {
       // Create an output stream
       std::ostringstream error_message_stream;
       // Create an error message
       error_message_stream
         << "Can only deal with Navier-Stokes elements which "
         << "use quadratic interpolation at the moment. Using " << n_node_1d
         << " nodes in each direction" << std::endl;
       // Throw an error
       throw OomphLibError(error_message_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
     // Loop over the nodes
     for (unsigned j = 0; j < n_node; j++)
     {
       // Only bother if the node isn't a copy...
       if (!(this->node_pt(j)->is_a_copy()))
       {
         // Storage for the local time slice ID (0<i_local<n_node_1d)
         unsigned i_local = 0;
         // If we're on the first time slice
         if (j < n_node_1d * n_node_1d)
         {
           // In the first local time slice
           i_local = 0;
         }
         // If we're in the second time slice (already excluded the first time
         // slice)
         else if (j < 2 * n_node_1d * n_node_1d)
         {
           // In the second local time slice
           i_local = 1;
         }
         // If we're in the final time slice (already excluded the first/second
         // slice)
         else if (j < 3 * n_node_1d * n_node_1d)
         {
           // In the final local time slice
           i_local = 2;
         }
         // We should never get here
         else
         {
           // Create an output stream
           std::ostringstream error_message_stream;
           // Create an error message
           error_message_stream << "Looping over too many nodes!" << std::endl;
           // Throw an error
           throw OomphLibError(error_message_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
         // The number of dofs at this node
         unsigned n_dof = this->node_pt(j)->nvalue();
         // Loop over components
         for (unsigned i = 0; i < n_dof; i++)
         {
           // Determine local eqn number
           int local_eqn_number = this->nodal_local_eqn(j, i);
           // Ignore pinned values - far away degrees of freedom resulting
           // from hanging nodes can be ignored since these are be dealt
           // with by the element containing their master nodes
           if (local_eqn_number >= 0)
           {
             // The id shift (depending on which elemental time slice we're in)
             unsigned elemental_id_shift = 3 * Time_slab_id;
             // Store dof lookup in temporary pair: Global equation number
             // is the first entry in pair
             dof_lookup.first = this->eqn_number(local_eqn_number);
             // If we're on the first time slice
             if (i_local == 0)
             {
               // Set dof numbers: Dof number is the second entry in pair
               dof_lookup.second = elemental_id_shift + i;
             }
             // If we're on the second time slice
             else if (i_local == 1)
             {
               // Create an output stream
               std::ostringstream error_message_stream;
               // Create an error message
               error_message_stream
                 << "All nodes strictly on the interior of the "
                 << "elements temporal\nboundaries should be pinned "
                 << "in the mixed order element!" << std::endl;
               // Throw an error
               throw OomphLibError(error_message_stream.str(),
                                   OOMPH_CURRENT_FUNCTION,
                                   OOMPH_EXCEPTION_LOCATION);
             }
             // If we're on the final time slice
             else if (i_local == 2)
             {
               // The local dof shift given which local time slice we're on (i.e.
               // which node we're on in the time-direction). We've already
               // covered 2 velocities and 1 pressure so the dof shift is 3.
               unsigned local_id_shift = 3;
               // Set dof numbers: Dof number is the second entry in pair
               dof_lookup.second = elemental_id_shift + local_id_shift + i;
             } // if (i_local==0)
             // Add to list
             dof_lookup_list.push_front(dof_lookup);
           }
         } // for (unsigned i=0;i<DIM;i++)
       } // if (!(this->node_pt(j)->is_a_copy()))
     } // for (unsigned j=0;j<n_node;j++)
   } // End of get_dof_numbers_for_unknowns
References oomph::GeneralisedElement::eqn_number(), i, j, oomph::GeneralisedElement::local_eqn_number(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), oomph::Data::nvalue(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::BlockPreconditionableSpaceTimeElementBase::Time_slab_id.
The documentation for this class was generated from the following files:
mixed_order_petrov_galerkin_space_time_block_preconditionable_elements.h
mixed_order_petrov_galerkin_space_time_block_preconditionable_elements.cc