MercuryDPM: oomph::SuperLUPreconditioner Class Reference
oomph::SuperLUPreconditioner Class Reference
An interface to allow SuperLU to be used as an (exact) Preconditioner.
#include <SuperLU_preconditioner.h>
Public Member Functions
SuperLUPreconditioner ()
Constructor.
~SuperLUPreconditioner ()
Destructor.
SuperLUPreconditioner (const SuperLUPreconditioner &)=delete
Broken copy constructor.
void operator= (const SuperLUPreconditioner &)=delete
Broken assignment operator.
void setup ()
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
void preconditioner_solve_transpose (const DoubleVector &r, DoubleVector &z)
virtual void clean_up_memory ()
double get_memory_usage_for_lu_factors ()
Get the amount of memory used to store the LU factors inside SuperLU.
double get_total_memory_needed_for_superlu ()
Vector< double > get_memory_usage_for_superlu ()
void enable_doc_stats ()
Enable documentation of solver statistics.
void disable_doc_stats ()
Enable documentation of solver statistics.
Public Member Functions inherited from oomph::Preconditioner
Preconditioner ()
Constructor.
Preconditioner (const Preconditioner &)=delete
Broken copy constructor.
void operator= (const Preconditioner &)=delete
Broken assignment operator.
virtual ~Preconditioner ()
Destructor (empty)
void setup (DoubleMatrixBase *matrix_pt)
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
void enable_silent_preconditioner_setup ()
Set up the block preconditioner quietly!
void disable_silent_preconditioner_setup ()
Be verbose in the block preconditioner setup.
virtual DoubleMatrixBase * matrix_pt () const
Get function for matrix pointer.
virtual void set_matrix_pt (DoubleMatrixBase *matrix_pt)
Set the matrix pointer.
virtual const OomphCommunicator * comm_pt () const
Get function for comm pointer.
virtual void set_comm_pt (const OomphCommunicator *const comm_pt)
Set the communicator pointer.
double setup_time () const
Returns the time to setup the preconditioner.
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> &doftype_coarsen_map_coarse)
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
void build_distribution (const LinearAlgebraDistribution &dist)
Private Attributes
SuperLUSolver Solver
the SuperLU solver emplyed by this preconditioner
Additional Inherited Members
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
Protected Attributes inherited from oomph::Preconditioner
bool Silent_preconditioner_setup
Boolean to indicate whether or not the build should be done silently.
std::ostream * Stream_pt
Pointer to the output stream – defaults to std::cout.
Detailed Description
An interface to allow SuperLU to be used as an (exact) Preconditioner.
Constructor & Destructor Documentation
SuperLUPreconditioner() [1/2]
oomph::SuperLUPreconditioner::SuperLUPreconditioner () inline
Constructor.
     {
       Solver.disable_doc_stats();
       Solver.disable_doc_time();
     }
References oomph::SuperLUSolver::disable_doc_stats(), oomph::LinearSolver::disable_doc_time(), and Solver.
~SuperLUPreconditioner()
oomph::SuperLUPreconditioner::~SuperLUPreconditioner () inline
Destructor.
 {}
SuperLUPreconditioner() [2/2]
oomph::SuperLUPreconditioner::SuperLUPreconditioner (const SuperLUPreconditioner &) delete
Broken copy constructor.
Member Function Documentation
clean_up_memory()
virtual void oomph::SuperLUPreconditioner::clean_up_memory () inline virtual
Clean up memory – forward the call to the version in SuperLU in its LinearSolver incarnation.
Reimplemented from oomph::Preconditioner.
     {
       Solver.clean_up_memory();
     }
References oomph::SuperLUSolver::clean_up_memory(), and Solver.
disable_doc_stats()
void oomph::SuperLUPreconditioner::disable_doc_stats () inline
Enable documentation of solver statistics.
     {
       // Disable the documentation of statistics inside SuperLU
       Solver.disable_doc_stats();
     } // End of disable_doc_stats
References oomph::SuperLUSolver::disable_doc_stats(), and Solver.
enable_doc_stats()
void oomph::SuperLUPreconditioner::enable_doc_stats () inline
Enable documentation of solver statistics.
     {
       // Enable the documentation of statistics inside SuperLU
       Solver.enable_doc_stats();
     } // End of enable_doc_stats
References oomph::SuperLUSolver::enable_doc_stats(), and Solver.
get_memory_usage_for_lu_factors()
double oomph::SuperLUPreconditioner::get_memory_usage_for_lu_factors () inline
Get the amount of memory used to store the LU factors inside SuperLU.
     {
       // Return the appropriate result
       return Solver.get_memory_usage_for_lu_factors();
     } // End of get_memory_usage_for_lu_factors
References oomph::SuperLUSolver::get_memory_usage_for_lu_factors(), and Solver.
get_memory_usage_for_superlu()
Vector<double> oomph::SuperLUPreconditioner::get_memory_usage_for_superlu () inline
Get the amount of memory taken up by SuperLU. The first entry of the returned result contains the memory used to store the LU factors and the second entry contains the total memory used to store AND calculate the LU factors
     {
       // Allocate storage for the memory statistics
       Vector<double> memory_usage(2, 0.0);
       // The first entry contains the memory used to store the LU factors
       memory_usage[0] = Solver.get_memory_usage_for_lu_factors();
       // The second entry contains the total memory used to both calculate
       // and store the LU factors
       memory_usage[1] = Solver.get_total_needed_memory();
       // Now return the calculated result
       return memory_usage;
     } // End of get_memory_usage_for_superlu
References oomph::SuperLUSolver::get_memory_usage_for_lu_factors(), oomph::SuperLUSolver::get_total_needed_memory(), and Solver.
get_total_memory_needed_for_superlu()
double oomph::SuperLUPreconditioner::get_total_memory_needed_for_superlu () inline
Get the total memory needed by SuperLU to store AND calculate the LU factors
     {
       // Return the appropriate result
       return Solver.get_total_needed_memory();
     } // End of get_memory_usage_for_superlu
References oomph::SuperLUSolver::get_total_needed_memory(), and Solver.
operator=()
void oomph::SuperLUPreconditioner::operator= (const SuperLUPreconditioner &) delete
Broken assignment operator.
preconditioner_solve()
void oomph::SuperLUPreconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) inline virtual
Function applies SuperLU to vector r for (exact) preconditioning, this requires a call to setup(...) first.
Implements oomph::Preconditioner.
     {
       Solver.resolve(r, z);
     }
References UniformPSDSelfTest::r, oomph::SuperLUSolver::resolve(), and Solver.
preconditioner_solve_transpose()
void oomph::SuperLUPreconditioner::preconditioner_solve_transpose (const DoubleVector & r, DoubleVector & z) inline virtual
Function applies SuperLU to vector r for (exact) preconditioning (of the transposed matrix system) this requires a call to setup(...) first.
Reimplemented from oomph::Preconditioner.
     {
       Solver.resolve_transpose(r, z);
     }
References UniformPSDSelfTest::r, oomph::SuperLUSolver::resolve_transpose(), and Solver.
setup()
void oomph::SuperLUPreconditioner::setup () inline virtual
Function to set up a preconditioner for the linear system defined by matrix_pt. This function must be called before using preconditioner_solve. Note: matrix_pt must point to an object of class CRDoubleMatrix or CCDoubleMatrix
Implements oomph::Preconditioner.
     {
       oomph_info << "Setting up SuperLU (exact) preconditioner" << std::endl;
       if (dynamic_cast<DistributableLinearAlgebraObject*>(matrix_pt()) != 0)
       {
         LinearAlgebraDistribution dist(
           (dynamic_cast<DistributableLinearAlgebraObject*>(matrix_pt()))
             ->distribution_pt());
         this->build_distribution(dist);
         Solver.factorise(matrix_pt());
       }
       else
       {
         std::ostringstream error_message_stream;
         error_message_stream
           << "SuperLUPreconditioner can only be applied to matrices derived \n"
           << "DistributableLinearAlgebraObject.\n"
           << "You are most likely to be here because you are using the\n "
           << "soon to be obsolete CCDoubleMatrix\n";
         throw OomphLibError(error_message_stream.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
     }
References oomph::DistributableLinearAlgebraObject::build_distribution(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::SuperLUSolver::factorise(), oomph::Preconditioner::matrix_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, and Solver.
Referenced by oomph::NavierStokesSchurComplementPreconditioner::setup().
Member Data Documentation
Solver
SuperLUSolver oomph::SuperLUPreconditioner::Solver private
the SuperLU solver emplyed by this preconditioner
Referenced by clean_up_memory(), disable_doc_stats(), enable_doc_stats(), get_memory_usage_for_lu_factors(), get_memory_usage_for_superlu(), get_total_memory_needed_for_superlu(), preconditioner_solve(), preconditioner_solve_transpose(), setup(), and SuperLUPreconditioner().
The documentation for this class was generated from the following file:
SuperLU_preconditioner.h