MercuryDPM: Case.cc File Reference
Case.cc File Reference
#include <cstdio>
#include <cstring>
#include <cctype>
#include <cstdlib>
Functions
char * strtolower (char *str)
Converts a string to all lower case.
char * strtoupper (char *str)
Converts a string to all upper case.
int strcicmp (const char *s1, const char *s2)
Case-insensitive string comparison.
Function Documentation
strcicmp()
int strcicmp (const char * s1, const char * s2)
Case-insensitive string comparison.
The original strings are not overwritten.
Parameters
[in] s1 A C-string (char*)
[in] s2 A C-string (char*)
Returns
As with strcmp, returns 0 if the strings are identical up to case, and otherwise 1.
 {
     char* t1 = (char*) calloc(strlen(s1) + 1, sizeof(char));
     char* t2 = (char*) calloc(strlen(s2) + 1, sizeof(char));
     strncpy(t1, s1, strlen(s1));
     strncpy(t2, s2, strlen(s2));
     strtolower(t1);
     strtolower(t2);
     int out = strcmp(t1, t2);
     if (out != 0)
         out = 1;
     free(t1);
     free(t2);
     return out;
 }
References out(), and strtolower().
strtolower()
char* strtolower (char * str)
Converts a string to all lower case.
The original string is overwritten.
Parameters
[in] str A C-string (char*), that will be overwritten.
Returns
str
 {
     for (int i = 0; i < strlen(str); i++)
         str[i] = tolower(str[i]);
     return str;
 }
References i, and compute_granudrum_aor::str.
Referenced by strcicmp().
strtoupper()
char* strtoupper (char * str)
Converts a string to all upper case.
The original string is overwritten.
Parameters
[in] str A C-string (char*), that will be overwritten.
Returns
str
 {
     for (int i = 0; i < strlen(str); i++)
         str[i] = toupper(str[i]);
     return str;
 }
References i, and compute_granudrum_aor::str.