MercuryDPM: mapstaticmethods.cpp File Reference
mapstaticmethods.cpp File Reference
#include "main.h"
Classes
struct mapstaticmethods_impl< PlainObjectType, IsDynamicSize, IsVector >
struct mapstaticmethods_impl< PlainObjectType, false, IsVector >
struct mapstaticmethods_impl< PlainObjectType, true, false >
struct mapstaticmethods_impl< PlainObjectType, true, true >
Functions
template<typename PlainObjectType >
void mapstaticmethods (const PlainObjectType &m, float *ptr, const float *const_ptr)
EIGEN_DECLARE_TEST (mapstaticmethods)
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (mapstaticmethods)
{
   float* ptr = internal::aligned_new<float>(1000);
   for (int i = 0; i < 1000; i++) ptr[i] = float(i);
   const float* const_ptr = ptr;
   CALL_SUBTEST_1((mapstaticmethods(Matrix<float, 1, 1>(), ptr, const_ptr)));
   CALL_SUBTEST_1((mapstaticmethods(Vector2f(), ptr, const_ptr)));
   CALL_SUBTEST_2((mapstaticmethods(Vector3f(), ptr, const_ptr)));
   CALL_SUBTEST_2((mapstaticmethods(Matrix2f(), ptr, const_ptr)));
   CALL_SUBTEST_3((mapstaticmethods(Matrix4f(), ptr, const_ptr)));
   CALL_SUBTEST_3((mapstaticmethods(Array4f(), ptr, const_ptr)));
   CALL_SUBTEST_4((mapstaticmethods(Array3f(), ptr, const_ptr)));
   CALL_SUBTEST_4((mapstaticmethods(Array33f(), ptr, const_ptr)));
   CALL_SUBTEST_5((mapstaticmethods(Array44f(), ptr, const_ptr)));
   CALL_SUBTEST_5((mapstaticmethods(VectorXf(1), ptr, const_ptr)));
   CALL_SUBTEST_5((mapstaticmethods(VectorXf(8), ptr, const_ptr)));
   CALL_SUBTEST_6((mapstaticmethods(MatrixXf(1, 1), ptr, const_ptr)));
   CALL_SUBTEST_6((mapstaticmethods(MatrixXf(5, 7), ptr, const_ptr)));
   CALL_SUBTEST_7((mapstaticmethods(ArrayXf(1), ptr, const_ptr)));
   CALL_SUBTEST_7((mapstaticmethods(ArrayXf(5), ptr, const_ptr)));
   CALL_SUBTEST_8((mapstaticmethods(ArrayXXf(1, 1), ptr, const_ptr)));
   CALL_SUBTEST_8((mapstaticmethods(ArrayXXf(8, 6), ptr, const_ptr)));
   internal::aligned_delete(ptr, 1000);
 }
References Eigen::internal::aligned_delete(), CALL_SUBTEST_1, CALL_SUBTEST_2, CALL_SUBTEST_3, CALL_SUBTEST_4, CALL_SUBTEST_5, CALL_SUBTEST_6, CALL_SUBTEST_7, CALL_SUBTEST_8, i, and mapstaticmethods().
mapstaticmethods()
template<typename PlainObjectType > void mapstaticmethods (const PlainObjectType & m, float * ptr, const float * const_ptr)
{
   mapstaticmethods_impl<PlainObjectType>::run(m, ptr, const_ptr);
   VERIFY(true);  // just to avoid 'unused function' warning
 }
References m, run(), and VERIFY.
Referenced by EIGEN_DECLARE_TEST().