MercuryDPM: NonIsothermalAxisymmetricQCrouzeixRaviartElement Class Reference
NonIsothermalAxisymmetricQCrouzeixRaviartElement Class Reference
#include <non_isothermal_axisym_nst_elements.h>
Public Types
typedef void(* ViscosityRatioFctPt) (double &temperature, double &result)
Public Member Functions
NonIsothermalAxisymmetricQCrouzeixRaviartElement ()
unsigned required_nvalue (const unsigned &n) const
void output (ostream &outfile)
Overload the standard output function with the broken default.
void output (ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
C-style output function: Broken default.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: Broken default.
void output_fct (ostream &outfile, const unsigned &Nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: Broken default.
unsigned u_index_axisym_adv_diff () const
void compute_error (ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
ViscosityRatioFctPt & viscosity_ratio_fct_pt ()
Access function: Pointer to viscosity ratio function.
ViscosityRatioFctPt viscosity_ratio_fct_pt () const
Access function: Pointer to viscosity ratio function. Const version.
virtual void get_viscosity_ratio_axisym_nst (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, double &visco)
void get_wind_axisym_adv_diff (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &wind) const
void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Private Attributes
ViscosityRatioFctPt Viscosity_ratio_fct_pt
Detailed Description
A class that solves the nonisothermal melt spinning problem using the axisymmetric Navier–Stokes and energy equations by coupling two pre- existing classes. The QSteadyAxisymAdvectionDiffusionElement<Nnode1d> with bi-quadratic interpolation for the scalar variable (temperature) and QCrouzeixRaviartElement which solves the Navier–Stokes equations using bi-quadratic interpolation for the velocities and a discontinuous bi-linear interpolation for the pressure. Note that we are free to choose the order in which we store the variables at the nodes. In this case we choose to store the variables in the order fluid velocities followed by temperature. We must, therefore, overload the function AxisymAdvectionDiffusionEquations::u_index_axisym_adv_diff() to indicate that the temperature is stored at the 3-th position not the 0-th. We do not need to overload the corresponding function in the AxisymmetricNavierStokesEquations class because the velocities are stored first.
Member Typedef Documentation
ViscosityRatioFctPt
typedef void(* NonIsothermalAxisymmetricQCrouzeixRaviartElement::ViscosityRatioFctPt) (double &temperature, double &result)
Function pointer to the function that specifies the viscosity ratio as function of the temperature.
Constructor & Destructor Documentation
NonIsothermalAxisymmetricQCrouzeixRaviartElement()
NonIsothermalAxisymmetricQCrouzeixRaviartElement::NonIsothermalAxisymmetricQCrouzeixRaviartElement () inline
Constructor: call the QSteadyAxisymAdvectionDiffusionElement and AxisymmetricQCrouzeixRaviartElement
                                                     :
   QSteadyAxisymAdvectionDiffusionElement<3>(),
   AxisymmetricQCrouzeixRaviartElement(),
   Viscosity_ratio_fct_pt(0)
   {}
Member Function Documentation
compute_error()
void NonIsothermalAxisymmetricQCrouzeixRaviartElement::compute_error (ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) inline
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element Call the broken default
  {
   FiniteElement::compute_error(outfile,exact_soln_pt,error,norm);
  }
References oomph::compute_error(), and calibrate::error.
fill_in_contribution_to_jacobian()
void NonIsothermalAxisymmetricQCrouzeixRaviartElement::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline
Compute the element's residual vector and the Jacobian matrix. Jacobian is computed by finite-differencing.
   {
    // This function computes the Jacobian by finite-differencing
    FiniteElement::fill_in_contribution_to_jacobian(residuals,jacobian);
   }
References oomph::fill_in_contribution_to_jacobian().
fill_in_contribution_to_residuals()
void NonIsothermalAxisymmetricQCrouzeixRaviartElement::fill_in_contribution_to_residuals (Vector< double > & residuals) inline
Calculate the element's contribution to the residual vector. Recall that fill_in_* functions MUST NOT initialise the entries in the vector to zero. This allows us to call the fill_in_* functions of the constituent single-physics elements sequentially, without wiping out any previously computed entries.
   {
    //Fill in the residuals of the Navier-Stokes equations
    AxisymmetricNavierStokesEquations::fill_in_contribution_to_residuals(residuals);
    //Fill in the residuals of the advection-diffusion eqautions
    SteadyAxisymAdvectionDiffusionEquations::fill_in_contribution_to_residuals(residuals);
   }
References oomph::fill_in_contribution_to_residuals().
get_viscosity_ratio_axisym_nst()
virtual void NonIsothermalAxisymmetricQCrouzeixRaviartElement::get_viscosity_ratio_axisym_nst (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, double & visco) inline virtual
Overload the viscosity ratio in the Navier-Stokes equations This provides the coupling from axisymmetric advection-diffusion equations to the Axisymmetric Navier–Stokes equations.
   {
    //If the function pointer is zero return zero
    if (Viscosity_ratio_fct_pt == 0)
     {
      visco = *Viscosity_Ratio_pt;
     }
    //Otherwise call the function
    else
     {
      //Get the temperature
      double interpolated_t = this->interpolated_u_adv_diff(s);
      // Valuate viscosity ratio
      (*Viscosity_ratio_fct_pt)(interpolated_t,visco);
     }
 /*    //Get the temperature */
 /*    const double interpolated_t = this->interpolated_u_adv_diff(s); */
 /*    // Parameters that modeling the viscosity */
 /*    double G = 1.0; */
 /*    double eta = 0.0; */
 /*    visco = G*exp(eta*(1.0-interpolated_t)); */
   } // end of get_visco_axisym_nst
References s, and Viscosity_ratio_fct_pt.
get_wind_axisym_adv_diff()
void NonIsothermalAxisymmetricQCrouzeixRaviartElement::get_wind_axisym_adv_diff (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & wind) const inline
Overload the wind function in the advection-diffusion equations. This provides the coupling from the Navier–Stokes equations to the advection-diffusion equations because the wind is the fluid velocity.
  {
    //The wind function is simply the velocity at the points
    this->interpolated_u_axi_nst(s,wind);
  } // end of get_wind_axisym_adv_diff
References s.
output() [1/4]
void NonIsothermalAxisymmetricQCrouzeixRaviartElement::output (FILE * file_pt) inline
C-style output function: Broken default.
   {
    FiniteElement::output(file_pt);
   }
References output().
output() [2/4]
void NonIsothermalAxisymmetricQCrouzeixRaviartElement::output (FILE * file_pt, const unsigned & n_plot) inline
C-style output function: Broken default.
   {
    FiniteElement::output(file_pt,n_plot);
   }
References output().
output() [3/4]
void NonIsothermalAxisymmetricQCrouzeixRaviartElement::output (ostream & outfile) inline
Overload the standard output function with the broken default.
   {
    FiniteElement::output(outfile);
   }
References output().
output() [4/4]
void NonIsothermalAxisymmetricQCrouzeixRaviartElement::output (ostream & outfile, const unsigned & nplot) inline
Output function:
Output r, z, u, w, v, p, theta at Nplot^2 plot points
   {
    //vector of local coordinates
    Vector<double> s(2);
    // Tecplot header info
    outfile << this->tecplot_zone_string(nplot);
    // Loop over plot points
    unsigned num_plot_points=this->nplot_points(nplot);
    for (unsigned iplot=0;iplot<num_plot_points;iplot++)
     {
      // Get local coordinates of plot point
      this->get_s_plot(iplot,nplot,s);
      // Output the position (r,z) of the plot point
      for(unsigned i=0;i<2;i++)
       {
        outfile << this->interpolated_x(s,i) << " ";
       }
      // Output the fluid velocities (u,w,v) at the plot point
      for(unsigned i=0;i<3;i++)
       {
        outfile << this->interpolated_u_axi_nst(s,i) << " ";
       }
      // Output the fluid pressure at the plot point
      outfile << this->interpolated_p_axi_nst(s)  << " ";
      // Output the temperature (the advected variable) at the plot point
      outfile << this->interpolated_u_adv_diff(s) << std::endl;
     }
    outfile << std::endl;
    // Write tecplot footer (e.g. FE connectivity lists)
    this->write_tecplot_zone_footer(outfile,nplot);
   } //End of output function
References i, and s.
output_fct()
void NonIsothermalAxisymmetricQCrouzeixRaviartElement::output_fct (ostream & outfile, const unsigned & Nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) inline
Output function for an exact solution: Broken default.
   {
    FiniteElement::output_fct(outfile,Nplot,exact_soln_pt);
   }
References oomph::output_fct().
required_nvalue()
unsigned NonIsothermalAxisymmetricQCrouzeixRaviartElement::required_nvalue (const unsigned & n) const inline
The required number of values stored at the nodes is the sum of the required values of the two single-physics elements. Note that this step is generic for any multi-physics element of this type.
   {
    return ( QSteadyAxisymAdvectionDiffusionElement<3>::required_nvalue(n) +
             AxisymmetricQCrouzeixRaviartElement::required_nvalue(n) );
   }
References n.
u_index_axisym_adv_diff()
unsigned NonIsothermalAxisymmetricQCrouzeixRaviartElement::u_index_axisym_adv_diff () const inline
Overload the index at which the temperature variable is stored. We choose to store it after the fluid velocities.
   {
    return 3;
   }
viscosity_ratio_fct_pt() [1/2]
ViscosityRatioFctPt& NonIsothermalAxisymmetricQCrouzeixRaviartElement::viscosity_ratio_fct_pt () inline
Access function: Pointer to viscosity ratio function.
 {return Viscosity_ratio_fct_pt;}
References Viscosity_ratio_fct_pt.
viscosity_ratio_fct_pt() [2/2]
ViscosityRatioFctPt NonIsothermalAxisymmetricQCrouzeixRaviartElement::viscosity_ratio_fct_pt () const inline
Access function: Pointer to viscosity ratio function. Const version.
   {return Viscosity_ratio_fct_pt;}
References Viscosity_ratio_fct_pt.
Member Data Documentation
Viscosity_ratio_fct_pt
ViscosityRatioFctPt NonIsothermalAxisymmetricQCrouzeixRaviartElement::Viscosity_ratio_fct_pt private
Function pointer to the function that specifies the viscosity ratio as a function of the temperature
Referenced by get_viscosity_ratio_axisym_nst(), and viscosity_ratio_fct_pt().
The documentation for this class was generated from the following file:
non_isothermal_axisym_nst_elements.h