MercuryDPM: TanhSolnForAdvectionDiffusion Namespace Reference
TanhSolnForAdvectionDiffusion Namespace Reference
Functions
void get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void get_exact_u (const Vector< double > &x, double &u)
Exact solution as a scalar.
void source_function (const Vector< double > &x_vect, double &source)
Source function required to make the solution above an exact solution.
void wind_function (const Vector< double > &x, Vector< double > &wind)
Wind.
void tanh_profile (const Vector< double > &x, Vector< double > &u)
Tanh profile for assignment of boundary conditons as a Vector.
void tanh_profile (const Vector< double > &x, double &u)
Tanh profile for assignment of boundary conditons as a Vector.
void prescribed_flux_on_fixed_x_boundary (const Vector< double > &x, double &flux)
Flux required by the exact solution on a boundary on which x is fixed.
Variables
double Peclet =200.0
Peclet number.
double Alpha =10.0
Parameter for steepness of step.
double TanPhi =1.0
Parameter for angle of step.
Detailed Description
Namespace for exact solution for AdvectionDiffusion equation with "sharp" step
Namespace for physical parameters and boundary conditions "sharp" step
Function Documentation
get_exact_u() [1/2]
void TanhSolnForAdvectionDiffusion::get_exact_u (const Vector< double > & x, double & u)
Exact solution as a scalar.
  {
   u=tanh(1.0-Alpha*(TanPhi*x[0]-x[1]));
  }
References Alpha, Eigen::bfloat16_impl::tanh(), TanPhi, and plotDoE::x.
get_exact_u() [2/2]
void TanhSolnForAdvectionDiffusion::get_exact_u (const Vector< double > & x, Vector< double > & u)
Exact solution as a Vector.
  {
   u[0]=tanh(1.0-Alpha*(TanPhi*x[0]-x[1]));
  }
References Alpha, Eigen::bfloat16_impl::tanh(), TanPhi, and plotDoE::x.
Referenced by RefineableAdvectionDiffusionProblem< ELEMENT >::actions_before_newton_solve(), TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::actions_before_newton_solve(), RefineableAdvectionDiffusionProblem< ELEMENT >::doc_solution(), and TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::doc_solution().
prescribed_flux_on_fixed_x_boundary()
void TanhSolnForAdvectionDiffusion::prescribed_flux_on_fixed_x_boundary (const Vector< double > & x, double & flux)
Flux required by the exact solution on a boundary on which x is fixed.
  {
   //The outer unit normal to the boundary is (1,0)
   double N[2] = {1.0, 0.0};
   //The flux in terms of the normal is
   flux =
    -(1.0-pow(tanh(-1.0+Alpha*(TanPhi*x[0]-x[1])),2.0))*Alpha*TanPhi*N[0]+(
    1.0-pow(tanh(-1.0+Alpha*(TanPhi*x[0]-x[1])),2.0))*Alpha*N[1];
 //  Use this one for the funky unforced solution
 //  flux=-1.0;
  }
References Alpha, ProblemParameters::flux(), N, Eigen::bfloat16_impl::pow(), Eigen::bfloat16_impl::tanh(), TanPhi, and plotDoE::x.
Referenced by TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::actions_after_adapt(), and TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::TwoMeshFluxAdvectionDiffusionProblem().
source_function()
void TanhSolnForAdvectionDiffusion::source_function (const Vector< double > & x_vect, double & source)
Source function required to make the solution above an exact solution.
Zero source function.
  {
   double x=x_vect[0];
   double y=x_vect[1];
   source =
 2.0*tanh(-0.1E1+Alpha*(TanPhi*x-y))*(1.0-pow(tanh(-0.1E1+Alpha*(
 TanPhi*x-y)),2.0))*Alpha*Alpha*TanPhi*TanPhi+2.0*tanh(-0.1E1+Alpha*(TanPhi*x-y)
 )*(1.0-pow(tanh(-0.1E1+Alpha*(TanPhi*x-y)),2.0))*Alpha*Alpha-Peclet*(-sin(6.0*y
 )*(1.0-pow(tanh(-0.1E1+Alpha*(TanPhi*x-y)),2.0))*Alpha*TanPhi+cos(6.0*x)*(1.0-
 pow(tanh(-0.1E1+Alpha*(TanPhi*x-y)),2.0))*Alpha);
  }
References Alpha, cos(), Peclet, Eigen::bfloat16_impl::pow(), sin(), TestProblem::source(), Eigen::bfloat16_impl::tanh(), TanPhi, plotDoE::x, and y.
Referenced by main(), and run_it().
tanh_profile() [1/2]
void TanhSolnForAdvectionDiffusion::tanh_profile (const Vector< double > & x, double & u)
Tanh profile for assignment of boundary conditons as a Vector.
  {
   u=tanh(1.0-Alpha*(TanPhi*x[0]-x[1]));
  }
References Alpha, Eigen::bfloat16_impl::tanh(), TanPhi, and plotDoE::x.
tanh_profile() [2/2]
void TanhSolnForAdvectionDiffusion::tanh_profile (const Vector< double > & x, Vector< double > & u)
Tanh profile for assignment of boundary conditons as a Vector.
  {
   u[0]=tanh(1.0-Alpha*(TanPhi*x[0]-x[1]));
  }
References Alpha, Eigen::bfloat16_impl::tanh(), TanPhi, and plotDoE::x.
wind_function()
void TanhSolnForAdvectionDiffusion::wind_function (const Vector< double > & x, Vector< double > & wind)
Wind.
Wind: Recirculating cells.
  {
   wind[0]=sin(6.0*x[1]);
   wind[1]=cos(6.0*x[0]);
  }
References cos(), sin(), and plotDoE::x.
Referenced by main(), and run_it().
Variable Documentation
Alpha
double TanhSolnForAdvectionDiffusion::Alpha =10.0
Parameter for steepness of step.
Parameter for steepness of step in tanh profile.
Referenced by EntryFlowProblem< ELEMENT >::actions_before_newton_solve(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), QThermalPVDElement< DIM >::Default_Physical_Constant_Value(), oomph::PolarStreamfunctionTractionElement< ELEMENT >::fill_in_generic_residual_contribution(), oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution(), oomph::PolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarStreamfunctionEquations::fill_in_generic_residual_contribution(), oomph::PolarStreamfunctionEquations::fill_in_generic_residual_contribution(), TanhSolnForLinearWave::get_exact_gradient(), TanhSolnForPoisson::get_exact_gradient(), ArcTanSolnForPoisson::get_exact_gradient(), get_exact_u(), GlobalParameters::get_source(), PolarNSProblem< ELEMENT >::header(), oomph::PolarStreamfunctionEquations::interpolated_vorticity(), main(), oomph::PolarNavierStokesEquations::output(), prescribed_flux_on_fixed_x_boundary(), TanhSolnForPoisson::prescribed_flux_on_fixed_x_boundary(), Global_Parameters::pressure_load(), FlowAroundCylinderProblem< ELEMENT >::set_boundary_conditions(), InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::solve_steady(), TanhSolnForPoisson::source_function(), source_function(), oomph::PolarNavierStokesEquations::strain_rate(), oomph::PolarNavierStokesEquations::strain_rate_by_r(), and tanh_profile().
Peclet
double TanhSolnForAdvectionDiffusion::Peclet =200.0
Peclet number.
Referenced by RefineableBuoyantQCrouzeixRaviartElement< DIM >::Default_Physical_Constant_Value(), QCrouzeixRaviartElementWithTwoExternalElement< DIM >::Default_Physical_Constant_Value(), main(), RefineableAdvectionDiffusionProblem< ELEMENT >::RefineableAdvectionDiffusionProblem(), source_function(), and TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::TwoMeshFluxAdvectionDiffusionProblem().
TanPhi
double TanhSolnForAdvectionDiffusion::TanPhi =1.0
Parameter for angle of step.
Parameter for angle of step in tanh profile.
Referenced by TanhSolnForPoisson::get_exact_gradient(), get_exact_u(), GlobalParameters::get_source(), main(), prescribed_flux_on_fixed_x_boundary(), TanhSolnForPoisson::prescribed_flux_on_fixed_x_boundary(), source_function(), and tanh_profile().