MercuryDPM: Eigen::Transpose< TranspositionsBase< TranspositionsDerived > > Class Template Reference
Eigen::Transpose< TranspositionsBase< TranspositionsDerived > > Class Template Reference
#include <Transpositions.h>
Public Member Functions
Transpose (const TranspositionType &t)
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
template<typename OtherDerived >
const Product< Transpose, OtherDerived, AliasFreeProduct > operator* (const MatrixBase< OtherDerived > &matrix) const
EIGEN_DEVICE_FUNC const TranspositionType & nestedExpression () const
Protected Attributes
const TranspositionType & m_transpositions
Private Types
typedef TranspositionsDerived TranspositionType
typedef TranspositionType::IndicesType IndicesType
Friends
template<typename OtherDerived >
const Product< OtherDerived, Transpose, AliasFreeProduct > operator* (const MatrixBase< OtherDerived > &matrix, const Transpose &trt)
Member Typedef Documentation
IndicesType
template<typename TranspositionsDerived > typedef TranspositionType::IndicesType Eigen::Transpose< TranspositionsBase< TranspositionsDerived > >::IndicesType private
TranspositionType
template<typename TranspositionsDerived > typedef TranspositionsDerived Eigen::Transpose< TranspositionsBase< TranspositionsDerived > >::TranspositionType private
Constructor & Destructor Documentation
Transpose()
template<typename TranspositionsDerived > Eigen::Transpose< TranspositionsBase< TranspositionsDerived > >::Transpose (const TranspositionType & t) inline explicit
 : m_transpositions(t) {}
Member Function Documentation
cols()
template<typename TranspositionsDerived > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::Transpose< TranspositionsBase< TranspositionsDerived > >::cols () const inline
 { return m_transpositions.size(); }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
nestedExpression()
template<typename TranspositionsDerived > EIGEN_DEVICE_FUNC const TranspositionType& Eigen::Transpose< TranspositionsBase< TranspositionsDerived > >::nestedExpression () const inline
 { return m_transpositions; }
operator*()
template<typename TranspositionsDerived > template<typename OtherDerived > const Product<Transpose, OtherDerived, AliasFreeProduct> Eigen::Transpose< TranspositionsBase< TranspositionsDerived > >::operator* (const MatrixBase< OtherDerived > & matrix) const inline
Returns
the matrix with the inverse transpositions applied to the rows.
{
     return Product<Transpose, OtherDerived, AliasFreeProduct>(*this, matrix.derived());
   }
References matrix().
rows()
template<typename TranspositionsDerived > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::Transpose< TranspositionsBase< TranspositionsDerived > >::rows () const inline
 { return m_transpositions.size(); }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
size()
template<typename TranspositionsDerived > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::Transpose< TranspositionsBase< TranspositionsDerived > >::size () const inline
 { return m_transpositions.size(); }
Friends And Related Function Documentation
operator*
template<typename TranspositionsDerived > template<typename OtherDerived > const Product<OtherDerived, Transpose, AliasFreeProduct> operator* (const MatrixBase< OtherDerived > & matrix, const Transpose< TranspositionsBase< TranspositionsDerived > > & trt) friend
Returns
the matrix with the inverse transpositions applied to the columns.
{
     return Product<OtherDerived, Transpose, AliasFreeProduct>(matrix.derived(), trt);
   }
Member Data Documentation
m_transpositions
template<typename TranspositionsDerived > const TranspositionType& Eigen::Transpose< TranspositionsBase< TranspositionsDerived > >::m_transpositions protected
The documentation for this class was generated from the following file:
Transpositions.h