MercuryDPM: Eigen::internal::generic_i1e< T, float > Struct Template Reference
Eigen::internal::generic_i1e< T, float > Struct Template Reference
#include <BesselFunctionsImpl.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T run (const T &x)
Member Function Documentation
run()
template<typename T > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T Eigen::internal::generic_i1e< T, float >::run (const T & x) inline static
{
     /* i1ef.c
      *
      *  Modified Bessel function of order one,
      *  exponentially scaled
      *
      *
      *
      * SYNOPSIS:
      *
      * float x, y, i1ef();
      *
      * y = i1ef( x );
      *
      *
      *
      * DESCRIPTION:
      *
      * Returns exponentially scaled modified Bessel function
      * of order one of the argument.
      *
      * The function is defined as i1(x) = -i exp(-|x|) j1( ix ).
      *
      *
      *
      * ACCURACY:
      *
      *                      Relative error:
      * arithmetic   domain     # trials      peak         rms
      *    IEEE      0, 30       30000       1.5e-6      1.5e-7
      * See i1().
      *
      */
     const float A[] = {9.38153738649577178388E-9f,  -4.44505912879632808065E-8f, 2.00329475355213526229E-7f,
                        -8.56872026469545474066E-7f, 3.47025130813767847674E-6f,  -1.32731636560394358279E-5f,
                        4.78156510755005422638E-5f,  -1.61760815825896745588E-4f, 5.12285956168575772895E-4f,
                        -1.51357245063125314899E-3f, 4.15642294431288815669E-3f,  -1.05640848946261981558E-2f,
                        2.47264490306265168283E-2f,  -5.29459812080949914269E-2f, 1.02643658689847095384E-1f,
                        -1.76416518357834055153E-1f, 2.52587186443633654823E-1f};
     const float B[] = {-3.83538038596423702205E-9f, -2.63146884688951950684E-8f, -2.51223623787020892529E-7f,
                        -3.88256480887769039346E-6f, -1.10588938762623716291E-4f, -9.76109749136146840777E-3f,
                        7.78576235018280120474E-1f};
     T y = pabs(x);
     T y_le_eight = pmul(y, internal::pchebevl<T, 17>::run(pmadd(pset1<T>(0.5f), y, pset1<T>(-2.0f)), A));
     T y_gt_eight = pmul(internal::pchebevl<T, 7>::run(psub(pdiv(pset1<T>(32.0f), y), pset1<T>(2.0f)), B), prsqrt(y));
     // TODO: Perhaps instead check whether all packet elements are in
     // [-8, 8] and evaluate a branch based off of that. It's possible
     // in practice most elements are in this region.
     y = pselect(pcmp_le(y, pset1<T>(8.0f)), y_le_eight, y_gt_eight);
     return pselect(pcmp_lt(x, pset1<T>(0.0f)), pnegate(y), y);
   }
References Eigen::internal::pabs(), Eigen::internal::pcmp_le(), Eigen::internal::pcmp_lt(), Eigen::internal::pdiv(), Eigen::internal::pmadd(), Eigen::internal::pmul(), Eigen::internal::pnegate(), Eigen::internal::prsqrt(), Eigen::internal::pselect(), Eigen::internal::psub(), plotDoE::x, and Eigen::internal::y.
The documentation for this struct was generated from the following file:
BesselFunctionsImpl.h