MercuryDPM: oomph::GeompackQuadScaffoldMesh Class Reference
oomph::GeompackQuadScaffoldMesh Class Reference
#include <geompack_scaffold_mesh.h>
Public Member Functions
GeompackQuadScaffoldMesh ()
Empty constructor.
GeompackQuadScaffoldMesh (const std::string &mesh_file_name, const std::string &curve_file_name)
Constructor: Pass the filename of the mesh files.
GeompackQuadScaffoldMesh (const GeompackQuadScaffoldMesh &)=delete
Broken copy constructor.
void operator= (const GeompackQuadScaffoldMesh &)=delete
Broken assignment operator.
~GeompackQuadScaffoldMesh ()
Empty destructor.
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void setup_boundary_element_info ()
virtual void setup_boundary_element_info (std::ostream &outfile)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Detailed Description
Mesh that is based on input files generated by the quadrilateral mesh generator Geompack.
Constructor & Destructor Documentation
GeompackQuadScaffoldMesh() [1/3]
oomph::GeompackQuadScaffoldMesh::GeompackQuadScaffoldMesh () inline
Empty constructor.
 {}
GeompackQuadScaffoldMesh() [2/3]
oomph::GeompackQuadScaffoldMesh::GeompackQuadScaffoldMesh (const std::string & mesh_file_name, const std::string & curve_file_name)
Constructor: Pass the filename of the mesh files.
   {
     // Read the output mesh file to find informations about the nodes
     // and elements of the mesh
     // Process mesh file
     //---------------------
     std::ifstream mesh_file(mesh_file_name.c_str(), std::ios_base::in);
     // Number of nodes
     unsigned n_node;
     mesh_file >> n_node;
     // Coordinates of nodes and extra information index
     Vector<double> x_node(n_node);
     Vector<double> y_node(n_node);
     Vector<int> vertinfo(n_node);
     for (unsigned i = 0; i < n_node; i++)
     {
       mesh_file >> x_node[i];
       mesh_file >> y_node[i];
       mesh_file >> vertinfo[i];
     }
     // Extra information (nodes lying on a curve)
     unsigned n_vx;
     mesh_file >> n_vx;
     // Dummy storage for the node code
     int dummy_node_code;
     // Storage for the curve indice
     Vector<int> icurv(n_vx); // it's negative if not used
     // Dummy storage for the location of the point on the curve
     double dummy_ucurv;
     for (unsigned i = 0; i < n_vx; i++)
     {
       mesh_file >> dummy_node_code;
       mesh_file >> icurv[i];
       mesh_file >> dummy_ucurv;
     }
     // Number of local nodes per element
     unsigned n_local_node;
     mesh_file >> n_local_node;
     // Number of elements
     unsigned n_element;
     mesh_file >> n_element;
     // Storage for global node numbers for all elements
     Vector<unsigned> global_node(n_local_node * n_element);
     // Storage for edge information
     // (needed for a possible construction of midside node
     // in the following build from scaffold function)
     Vector<int> edgeinfo(n_local_node * n_element);
     // Initialize counter
     unsigned k = 0;
     // Read global node numbers for all elements
     for (unsigned i = 0; i < n_element; i++)
     {
       for (unsigned j = 0; j < n_local_node; j++)
       {
         mesh_file >> global_node[k];
         k++;
       }
     }
     // Initialize counter
     unsigned l = 0;
     // Read the edge information
     for (unsigned i = 0; i < n_element; i++)
     {
       for (unsigned j = 0; j < n_local_node; j++)
       {
         mesh_file >> edgeinfo[l];
         l++;
       }
     }
     mesh_file.close();
     // Create a vector of boolean so as not to create the same node twice
     std::vector<bool> done(n_node);
     for (unsigned i = 0; i < n_node; i++)
     {
       done[i] = false;
     }
     // Resize the Node vector
     Node_pt.resize(n_node, 0);
     // Resize the Element vector
     Element_pt.resize(n_element);
     // Process curve file to extract information about boundaries
     // ----------------------------------------------------------
     // Important: the input file must NOT have NURBS curve
     std::ifstream curve_file(curve_file_name.c_str(), std::ios_base::in);
     // Number of curves
     unsigned n_curv;
     curve_file >> n_curv;
     // Storage of several information for each curve
     Vector<Vector<int>> curv;
     // Resize to n_curv rows
     curv.resize(n_curv);
     // Curve type
     unsigned type;
     // Loop over the curves to extract information
     for (unsigned i = 0; i < n_curv; i++)
     {
       curve_file >> type;
       if (type == 1)
       {
         curv[i].resize(4);
         curv[i][0] = type;
         for (unsigned j = 1; j < 4; j++)
         {
           curve_file >> curv[i][j];
         }
       }
       else if (type == 2)
       {
         curv[i].resize(5);
         curv[i][0] = type;
         for (unsigned j = 1; j < 5; j++)
         {
           curve_file >> curv[i][j];
         }
       }
       else
       {
         std::ostringstream error_stream;
         error_stream << "Current we can only process curves of\n"
                      << "type 1 (straight lines) and 2 (circular arcs\n"
                      << "You've specified: type " << type << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
     }
     curve_file.close();
     // Searching the number of boundaries
     int d = 0;
     for (unsigned i = 0; i < n_curv; i++)
     {
       if (d < curv[i][1])
       {
         d = curv[i][1]; // the boundary code is the 2nd value of each curve
       }
     }
     oomph_info << "The number of boundaries is " << d << std::endl;
     // Set number of boundaries
     if (d > 0)
     {
       set_nboundary(d);
     }
     // Search the boundary number of node located on a boundary
     // If after this, boundary_of_node[j][0] is -1 then node j
     // is not located on any boundary.
     // If boundary_of_node[j][0] is positive, the node is located
     // on the boundary indicated by that number.
     // If boundary_of_node[j][1] is also positive, the node is also
     // located on that boundary. Note: We're ignoring the (remote)
     // possibility that node is located on 3 or more boundaries
     // as one of them would have to be an internal boundary which
     // would be odd...
     Vector<Vector<int>> boundary_of_node;
     boundary_of_node.resize(n_node);
     unsigned n;
     for (unsigned i = 0; i < n_node; i++)
     {
       n = 0;
       boundary_of_node[i].resize(2);
       boundary_of_node[i][0] = -1;
       boundary_of_node[i][1] = -1;
       if (vertinfo[i] == 2) // it's an endpoint
       {
         for (unsigned j = 0; j < n_curv; j++)
         {
           for (unsigned m = 2; m < curv[j].size(); m++)
           {
             if (curv[j][m] ==
                 static_cast<int>(i + 1)) // node number begins at 1
             { // in the mesh file !!!
               boundary_of_node[i][n] = curv[j][1];
               n++;
             }
           }
         }
       }
       if (vertinfo[i] > 20)
       {
         int a = 0;
         a = (vertinfo[i]) / 20;
         int b;
         b = icurv[a - 1]; // 1st value of vector at [0] !!
         boundary_of_node[i][0] =
           curv[b - 1][1]; // 1st value of vector at [0] !!
       }
     }
     // Create the elements
     //--------------------
     unsigned count = 0;
     unsigned c;
     for (unsigned e = 0; e < n_element; e++)
     {
       // Build simplex four node quad in the scaffold mesh
       Element_pt[e] = new QElement<2, 2>;
       // Construction of the two first nodes of the element
       for (unsigned j = 0; j < 2; j++)
       {
         c = global_node[count];
         if (done[c - 1] == false) // c-1 because node number begins
         // at 1 in the mesh file
         {
           // If the node is located on a boundary construct a boundary node
           if ((d > 0) && ((boundary_of_node[c - 1][0] > 0) ||
                           (boundary_of_node[c - 1][1] > 0)))
           {
             // Construct a boundary node
             Node_pt[c - 1] = finite_element_pt(e)->construct_boundary_node(j);
             // Add to the look=up schemes
             if (boundary_of_node[c - 1][0] > 0)
             {
               add_boundary_node(boundary_of_node[c - 1][0] - 1, Node_pt[c - 1]);
             }
             if (boundary_of_node[c - 1][1] > 0)
             {
               add_boundary_node(boundary_of_node[c - 1][1] - 1, Node_pt[c - 1]);
             }
           }
           // Otherwise construct a normal node
           else
           {
             Node_pt[c - 1] = finite_element_pt(e)->construct_node(j);
           }
           done[c - 1] = true;
           Node_pt[c - 1]->x(0) = x_node[c - 1];
           Node_pt[c - 1]->x(1) = y_node[c - 1];
         }
         else
         {
           finite_element_pt(e)->node_pt(j) = Node_pt[c - 1];
         }
         count++;
       }
       // Construction of the third node not in anticlockwise order
       c = global_node[count + 1];
       if (done[c - 1] ==
           false) // c-1 because node number begins at 1 in the mesh file
       {
         // If the node is on a boundary, construct a boundary node
         if ((d > 0) && ((boundary_of_node[c - 1][0] > 0) ||
                         (boundary_of_node[c - 1][1] > 0)))
         {
           // Construct the node
           Node_pt[c - 1] = finite_element_pt(e)->construct_boundary_node(2);
           // Add to the look-up schemes
           if (boundary_of_node[c - 1][0] > 0)
           {
             add_boundary_node(boundary_of_node[c - 1][0] - 1, Node_pt[c - 1]);
           }
           if (boundary_of_node[c - 1][1] > 0)
           {
             add_boundary_node(boundary_of_node[c - 1][1] - 1, Node_pt[c - 1]);
           }
         }
         // otherwise construct a normal node
         else
         {
           Node_pt[c - 1] = finite_element_pt(e)->construct_node(2);
         }
         done[c - 1] = true;
         Node_pt[c - 1]->x(0) = x_node[c - 1];
         Node_pt[c - 1]->x(1) = y_node[c - 1];
       }
       else
       {
         finite_element_pt(e)->node_pt(2) = Node_pt[c - 1];
       }
       count++;
       // Construction of the fourth node
       c = global_node[count - 1];
       if (done[c - 1] ==
           false) // c-1 because node number begins at 1 in the mesh file
       {
         // If the node is on a boundary, constuct a boundary node
         if ((d > 0) && ((boundary_of_node[c - 1][0] > 0) ||
                         (boundary_of_node[c - 1][1] > 0)))
         {
           // Construct the boundary node
           Node_pt[c - 1] = finite_element_pt(e)->construct_boundary_node(3);
           // Add to the look-up schemes
           if (boundary_of_node[c - 1][0] > 0)
           {
             add_boundary_node(boundary_of_node[c - 1][0] - 1, Node_pt[c - 1]);
           }
           if (boundary_of_node[c - 1][1] > 0)
           {
             add_boundary_node(boundary_of_node[c - 1][1] - 1, Node_pt[c - 1]);
           }
         }
         // Otherwise construct a normal node
         else
         {
           Node_pt[c - 1] = finite_element_pt(e)->construct_node(3);
         }
         done[c - 1] = true;
         Node_pt[c - 1]->x(0) = x_node[c - 1];
         Node_pt[c - 1]->x(1) = y_node[c - 1];
       }
       else
       {
         finite_element_pt(e)->node_pt(3) = Node_pt[c - 1];
       }
       count++;
     }
   }
References a, oomph::Mesh::add_boundary_node(), b, calibrate::c, oomph::FiniteElement::construct_boundary_node(), oomph::FiniteElement::construct_node(), e(), oomph::Mesh::Element_pt, oomph::Mesh::finite_element_pt(), i, j, k, m, n, oomph::FiniteElement::node_pt(), oomph::Mesh::Node_pt, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, oomph::Mesh::set_nboundary(), and compute_granudrum_aor::type.
GeompackQuadScaffoldMesh() [3/3]
oomph::GeompackQuadScaffoldMesh::GeompackQuadScaffoldMesh (const GeompackQuadScaffoldMesh &) delete
Broken copy constructor.
~GeompackQuadScaffoldMesh()
oomph::GeompackQuadScaffoldMesh::~GeompackQuadScaffoldMesh () inline
Empty destructor.
 {}
Member Function Documentation
operator=()
void oomph::GeompackQuadScaffoldMesh::operator= (const GeompackQuadScaffoldMesh &) delete
Broken assignment operator.
The documentation for this class was generated from the following files:
geompack_scaffold_mesh.h
geompack_scaffold_mesh.cc