MercuryDPM: Eigen::internal::nearest_integer_packetop_impl< Packet, IsScalar, IsInteger > Struct Template Reference
Eigen::internal::nearest_integer_packetop_impl< Packet, IsScalar, IsInteger > Struct Template Reference
#include <GenericPacketMath.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet run_floor (const Packet &x)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet run_ceil (const Packet &x)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet run_rint (const Packet &x)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet run_round (const Packet &x)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet run_trunc (const Packet &x)
Member Function Documentation
run_ceil()
template<typename Packet , bool IsScalar = is_scalar<Packet>::value, bool IsInteger = NumTraits<typename unpacket_traits<Packet>::type>::IsInteger> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::nearest_integer_packetop_impl< Packet, IsScalar, IsInteger >::run_ceil (const Packet & x) inline static
 { return numext::ceil(x); }
References Eigen::numext::ceil(), and plotDoE::x.
Referenced by Eigen::internal::pceil().
run_floor()
template<typename Packet , bool IsScalar = is_scalar<Packet>::value, bool IsInteger = NumTraits<typename unpacket_traits<Packet>::type>::IsInteger> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::nearest_integer_packetop_impl< Packet, IsScalar, IsInteger >::run_floor (const Packet & x) inline static
 { return numext::floor(x); }
References Eigen::numext::floor(), and plotDoE::x.
Referenced by Eigen::internal::pfloor().
run_rint()
template<typename Packet , bool IsScalar = is_scalar<Packet>::value, bool IsInteger = NumTraits<typename unpacket_traits<Packet>::type>::IsInteger> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::nearest_integer_packetop_impl< Packet, IsScalar, IsInteger >::run_rint (const Packet & x) inline static
 { return numext::rint(x); }
References Eigen::numext::rint(), and plotDoE::x.
Referenced by Eigen::internal::print().
run_round()
template<typename Packet , bool IsScalar = is_scalar<Packet>::value, bool IsInteger = NumTraits<typename unpacket_traits<Packet>::type>::IsInteger> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::nearest_integer_packetop_impl< Packet, IsScalar, IsInteger >::run_round (const Packet & x) inline static
 { return numext::round(x); }
References Eigen::numext::round(), and plotDoE::x.
Referenced by Eigen::internal::pround().
run_trunc()
template<typename Packet , bool IsScalar = is_scalar<Packet>::value, bool IsInteger = NumTraits<typename unpacket_traits<Packet>::type>::IsInteger> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::nearest_integer_packetop_impl< Packet, IsScalar, IsInteger >::run_trunc (const Packet & x) inline static
 { return numext::trunc(x); }
References Eigen::numext::trunc(), and plotDoE::x.
Referenced by Eigen::internal::ptrunc().
The documentation for this struct was generated from the following file:
GenericPacketMath.h