MercuryDPM: oomph::WarpedCubeDomain Class Reference
oomph::WarpedCubeDomain Class Reference
#include <domain.h>
Public Member Functions
WarpedCubeDomain ()
Constructor:
WarpedCubeDomain (const WarpedCubeDomain &)=delete
Broken copy constructor.
void operator= (const WarpedCubeDomain &)=delete
Broken assignment operator.
~WarpedCubeDomain ()
Destructor (empty; clean up handled in base class)
void warp_it (Vector< double > &f)
Warp the unit cube.
void macro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
Public Member Functions inherited from oomph::Domain
Domain ()
Constructor.
Domain (const Domain &)=delete
Broken copy constructor.
void operator= (const Domain &)=delete
Broken assignment operator.
virtual ~Domain ()
MacroElement * macro_element_pt (const unsigned &i)
Access to i-th macro element.
unsigned nmacro_element ()
Number of macro elements in domain.
void output (const std::string &filename, const unsigned &nplot)
Output macro elements.
void output (std::ostream &outfile, const unsigned &nplot)
Output macro elements.
virtual void macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void output_macro_element_boundaries (const std::string &filename, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
void output_macro_element_boundaries (std::ostream &outfile, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
virtual void dmacro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void dmacro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void dmacro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void d2macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
Private Member Functions
void r_L (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_R (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_D (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_U (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_B (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_F (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Additional Inherited Members
Protected Attributes inherited from oomph::Domain
Vector< MacroElement * > Macro_element_pt
Vector of pointers to macro elements.
Detailed Description
////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// Warped cube as domain which is parametrised by a single macro element
Constructor & Destructor Documentation
WarpedCubeDomain() [1/2]
oomph::WarpedCubeDomain::WarpedCubeDomain () inline
Constructor:
     {
       // Resize
       Macro_element_pt.resize(1);
       // Create macro element
       Macro_element_pt[0] = new QMacroElement<3>(this, 0);
     }
References oomph::Domain::Macro_element_pt.
WarpedCubeDomain() [2/2]
oomph::WarpedCubeDomain::WarpedCubeDomain (const WarpedCubeDomain &) delete
Broken copy constructor.
~WarpedCubeDomain()
oomph::WarpedCubeDomain::~WarpedCubeDomain () inline
Destructor (empty; clean up handled in base class)
 {}
Member Function Documentation
macro_element_boundary()
void oomph::WarpedCubeDomain::macro_element_boundary (const unsigned & t, const unsigned & imacro, const unsigned & idirect, const Vector< double > & s, Vector< double > & f) virtual
Vector representation of the i_macro-th macro element boundary i_direct (L/R/D/U/B/F) at time level t (t=0: present; t>0: previous): f(s).
////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// Vector representation of the imacro-th macro element boundary idirect (L/R/D/B/F) at time level t (t=0: present; t>0: previous): f(s)
Implements oomph::Domain.
   {
     using namespace OcTreeNames;
 #ifdef WARN_ABOUT_SUBTLY_CHANGED_OOMPH_INTERFACES
     // Warn about time argument being moved to the front
     OomphLibWarning(
       "Order of function arguments has changed between versions 0.8 and 0.85",
       "WarpedCubeDomain::macro_element_boundary(...)",
       OOMPH_EXCEPTION_LOCATION);
 #endif
     // Which direction?
     if (idirect == L)
     {
       r_L(t, s, f);
     }
     else if (idirect == R)
     {
       r_R(t, s, f);
     }
     else if (idirect == D)
     {
       r_D(t, s, f);
     }
     else if (idirect == U)
     {
       r_U(t, s, f);
     }
     else if (idirect == B)
     {
       r_B(t, s, f);
     }
     else if (idirect == F)
     {
       r_F(t, s, f);
     }
     else
     {
       std::ostringstream error_stream;
       error_stream << "idirect is " << idirect << " not one of U, D, L, R, B, F"
                    << std::endl;
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
   }
References D, f(), oomph::OcTreeNames::F, L, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, R, r_B(), r_D(), r_F(), r_L(), r_R(), r_U(), s, plotPSD::t, and RachelsAdvectionDiffusion::U.
operator=()
void oomph::WarpedCubeDomain::operator= (const WarpedCubeDomain &) delete
Broken assignment operator.
r_B()
void oomph::WarpedCubeDomain::r_B (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Back boundary face zeta \(\in [-1,1]^2 \)
   {
     f[0] = zeta[0];
     f[1] = zeta[1];
     f[2] = -1.0;
     // Warp it
     warp_it(f);
   }
References f(), warp_it(), and Eigen::zeta().
Referenced by macro_element_boundary().
r_D()
void oomph::WarpedCubeDomain::r_D (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Down boundary face zeta \(\in [-1,1]^2 \)
   {
     f[0] = zeta[0];
     f[1] = -1.0;
     f[2] = zeta[1];
     // Warp it
     warp_it(f);
   }
References f(), warp_it(), and Eigen::zeta().
Referenced by macro_element_boundary().
r_F()
void oomph::WarpedCubeDomain::r_F (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Front boundary face zeta \(\in [-1,1]^2 \)
   {
     f[0] = zeta[0];
     f[1] = zeta[1];
     f[2] = 1.0;
     // Warp it
     warp_it(f);
   }
References f(), warp_it(), and Eigen::zeta().
Referenced by macro_element_boundary().
r_L()
void oomph::WarpedCubeDomain::r_L (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Left boundary face zeta \(\in [-1,1]^2 \)
   {
     f[0] = -1.0;
     f[1] = zeta[0];
     f[2] = zeta[1];
     // Warp it
     warp_it(f);
   }
References f(), warp_it(), and Eigen::zeta().
Referenced by macro_element_boundary().
r_R()
void oomph::WarpedCubeDomain::r_R (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Right boundary face zeta \(\in [-1,1]^2 \)
   {
     f[0] = 1.0;
     f[1] = zeta[0];
     f[2] = zeta[1];
     // Warp it
     warp_it(f);
   }
References f(), warp_it(), and Eigen::zeta().
Referenced by macro_element_boundary().
r_U()
void oomph::WarpedCubeDomain::r_U (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Up boundary face zeta \(\in [-1,1]^2 \)
   {
     f[0] = zeta[0];
     f[1] = 1.0;
     f[2] = zeta[1];
     // Warp it
     warp_it(f);
   }
References f(), warp_it(), and Eigen::zeta().
Referenced by macro_element_boundary().
warp_it()
void oomph::WarpedCubeDomain::warp_it (Vector< double > & f)
Warp the unit cube.
   {
     Vector<double> f_aux(f);
     double x = 0.5 * (1.0 + f_aux[0]);
     double y = 0.5 * (1.0 + f_aux[1]);
     double z = 0.5 * (1.0 + f_aux[2]);
     f[0] = (1.0 + x) * cos(y + 0.5 * z);
     f[1] = (2.0 + 3 * x) * sin(y + 0.5 * z);
     f[2] = sin(z) + 0.1 * (x * x + y * y);
   }
References cos(), f(), sin(), plotDoE::x, and y.
Referenced by r_B(), r_D(), r_F(), r_L(), r_R(), and r_U().
The documentation for this class was generated from the following files:
domain.h
domain.cc