MercuryDPM: oomph::NodeElementSolidOnlyMortaringElement Class Reference
oomph::NodeElementSolidOnlyMortaringElement Class Reference
#include <node_element_constraint_elements.h>
Public Member Functions
NodeElementSolidOnlyMortaringElement (SolidNode *node_pt, FiniteElement *elem_pt, Vector< double > &s)
void fill_in_contribution_to_residuals (Vector< double > &residuals) override
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian) override
void position_in_element (Vector< double > &x)
SolidNode * solid_node_pt ()
Public Member Functions inherited from oomph::ConstraintElement
ConstraintElement (Vector< Data * > &data_pt)
ConstraintElement (Vector< Data * > data_pt)
virtual void construct_lagrange_multipliers ()
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual unsigned self_test ()
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Private Member Functions
void fill_in_contribution_to_jacobian_mortared_nodes (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &flag)
Static Private Member Functions
static Vector< Data * > node_and_vector_to_data_pt (SolidNode *node_pt, FiniteElement *elem_pt)
Private Attributes
Vector< double > Local_Coord
SolidNode * Node_pt
FiniteElement * Element_pt
unsigned Dim
Additional Inherited Members
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions inherited from oomph::ConstraintElement
virtual void evaluate_constraint_functions (Vector< double > &error)
Vector< unsigned > get_constrained_data_local_index ()
unsigned get_lagrange_multiplier_index ()
Data * lagrange_multiplier ()
const int lagrange_eqn (const unsigned &i)
Data * ext_data_pt (const unsigned &i)
const int ext_eqn (const unsigned &i, const unsigned &j)
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes inherited from oomph::ConstraintElement
Vector< unsigned > Constrained_Data_Local_Index
unsigned Num_Constrained_Data
unsigned Lagrange_Multiplier_Index
unsigned Num_Constraints
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Constructor & Destructor Documentation
NodeElementSolidOnlyMortaringElement()
oomph::NodeElementSolidOnlyMortaringElement::NodeElementSolidOnlyMortaringElement (SolidNode * node_pt, FiniteElement * elem_pt, Vector< double > & s) inline
   : ConstraintElement(NodeElementSolidOnlyMortaringElement::node_and_vector_to_data_pt(node_pt, elem_pt)),
     Local_Coord(s),
     Node_pt(node_pt),
     Element_pt(elem_pt),
     Dim(node_pt->ndim())
   {
    if(Dim != elem_pt->dim())
    {
     throw OomphLibError("Mortaring element and node do not have the same number of dimensions " + std::to_string(Dim) + " " + std::to_string(elem_pt->dim()),
                          OOMPH_CURRENT_FUNCTION,
                          OOMPH_EXCEPTION_LOCATION);
    }
    // Build the lagrange multipliers
    Num_Constraints = Dim;
    Lagrange_Multiplier_Index = add_internal_data(new Data(Dim), false);
   }
References oomph::GeneralisedElement::add_internal_data(), Dim, oomph::FiniteElement::dim(), oomph::ConstraintElement::Lagrange_Multiplier_Index, oomph::ConstraintElement::Num_Constraints, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::StringConversion::to_string().
Member Function Documentation
fill_in_contribution_to_jacobian()
void oomph::NodeElementSolidOnlyMortaringElement::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline override virtual
Add the elemental contribution to the jacobian matrix. and the residuals vector. Note that this function will NOT initialise the residuals vector or the jacobian matrix. It must be called after the residuals vector and jacobian matrix have been initialised to zero. The default is to use finite differences to calculate the jacobian
Reimplemented from oomph::GeneralisedElement.
   {
    fill_in_contribution_to_jacobian_mortared_nodes(residuals, jacobian, 1);
   }
References fill_in_contribution_to_jacobian_mortared_nodes().
fill_in_contribution_to_jacobian_mortared_nodes()
void oomph::NodeElementSolidOnlyMortaringElement::fill_in_contribution_to_jacobian_mortared_nodes (Vector< double > & residuals, DenseMatrix< double > & jacobian, const bool & flag) inline private
   {
    // The number of nodes in the element
    const unsigned n_node = Element_pt->nnode();
    // The shape function
    Shape psi(n_node);
    Element_pt->shape(Local_Coord, psi);
    // Loop over the dimensions
    for(unsigned i=0; i<Dim; i++)
    {
     // eqn numbers
     const int lambda_eqn = lagrange_eqn(i);
     const int node_eqn = ext_eqn(0,i);
     Vector<int> element_node_eqn(n_node);
     // Get the lagrange multiplier value
     const double lambda = lagrange_multiplier()->value(i);
     // The node coordinate
     const double x_node = ext_data_pt(0)->value(i);
     // Get the interpolated element coordinate
     double x_elem = 0.0;
     for(unsigned l=0;l<n_node;l++)
     {
      // Get the eqn number
      element_node_eqn[l] = ext_eqn(1+l, i);
      // Get the coordinate of the node
      x_elem += psi[l] * ext_data_pt(1+l)->value(i);
     }
     // Fill in the residuals and jacobian entries
     // Lambda residual
     if(lambda_eqn>=0)
     {
      residuals[lambda_eqn] += (x_node - x_elem);
      if(flag)
      {
       if(node_eqn>=0)
       {
        jacobian(lambda_eqn, node_eqn) += 1.0;
       }
       for(unsigned l=0;l<n_node;l++)
       {
        if(element_node_eqn[l]>=0)
        {
         jacobian(lambda_eqn, element_node_eqn[l]) -= psi[l];
        }
       }
      }
     }
     // Node residual
     if(node_eqn>=0)
     {
      residuals[node_eqn] += lambda;
      if(flag)
      {
       if(lambda_eqn>=0)
       {
        jacobian(node_eqn, lambda_eqn) += 1.0;
       }
      }
     }
     // Element node residual
     for(unsigned l=0;l<n_node;l++)
     {
      if(element_node_eqn[l]>=0)
      {
       residuals[element_node_eqn[l]] -= lambda*psi[l];
       if(flag)
       {
        if(lambda_eqn>=0)
        {
         jacobian(element_node_eqn[l], lambda_eqn) -= psi[l];
        }
       }
      }
     }
    }
   }
References Dim, Element_pt, oomph::ConstraintElement::ext_data_pt(), oomph::ConstraintElement::ext_eqn(), i, oomph::ConstraintElement::lagrange_eqn(), oomph::ConstraintElement::lagrange_multiplier(), lambda, Local_Coord, oomph::FiniteElement::nnode(), oomph::FiniteElement::shape(), and oomph::Data::value().
Referenced by fill_in_contribution_to_jacobian(), and fill_in_contribution_to_residuals().
fill_in_contribution_to_residuals()
void oomph::NodeElementSolidOnlyMortaringElement::fill_in_contribution_to_residuals (Vector< double > & residuals) inline override virtual
Add the elemental contribution to the residuals vector. Note that this function will NOT initialise the residuals vector. It must be called after the residuals vector has been initialised to zero.
Reimplemented from oomph::ConstraintElement.
   {
    fill_in_contribution_to_jacobian_mortared_nodes(residuals, GeneralisedElement::Dummy_matrix, 0);
   }
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_contribution_to_jacobian_mortared_nodes().
node_and_vector_to_data_pt()
static Vector<Data*> oomph::NodeElementSolidOnlyMortaringElement::node_and_vector_to_data_pt (SolidNode * node_pt, FiniteElement * elem_pt) inline static private
   {
    const unsigned n_node_element = elem_pt->nnode();
    Vector<Data*> data_pt(1 + n_node_element);
    data_pt[0] = node_pt->variable_position_pt();
    for(unsigned i=0; i<n_node_element; i++)
    {
     data_pt[i+1] = dynamic_cast<SolidNode*>(elem_pt->node_pt(i))->variable_position_pt();
    }
    return data_pt;
   }
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::SolidNode::variable_position_pt().
position_in_element()
void oomph::NodeElementSolidOnlyMortaringElement::position_in_element (Vector< double > & x) inline
   {
    // The number of nodes in the element
    const unsigned n_node = Element_pt->nnode();
    // The shape function
    Shape psi(n_node);
    Element_pt->shape(Local_Coord, psi);
    // Get the interpolated element coordinate
    for(unsigned i=0; i<Dim; i++)
    {
     x[i] = 0.0;
     for(unsigned l=0; l<n_node; l++)
     {
      // Get the coordinate of the node
      x[i] += psi[l] * ext_data_pt(1+l)->value(i);
     }
    }
   }
References Dim, Element_pt, oomph::ConstraintElement::ext_data_pt(), i, Local_Coord, oomph::FiniteElement::nnode(), oomph::FiniteElement::shape(), oomph::Data::value(), and plotDoE::x.
Referenced by MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::verify_mortared_nodes_coincide().
solid_node_pt()
SolidNode* oomph::NodeElementSolidOnlyMortaringElement::solid_node_pt () inline
   {
    return Node_pt;
   }
References Node_pt.
Referenced by MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::verify_mortared_nodes_coincide().
Member Data Documentation
Dim
unsigned oomph::NodeElementSolidOnlyMortaringElement::Dim private
Referenced by fill_in_contribution_to_jacobian_mortared_nodes(), NodeElementSolidOnlyMortaringElement(), and position_in_element().
Element_pt
FiniteElement* oomph::NodeElementSolidOnlyMortaringElement::Element_pt private
Referenced by fill_in_contribution_to_jacobian_mortared_nodes(), and position_in_element().
Local_Coord
Vector<double> oomph::NodeElementSolidOnlyMortaringElement::Local_Coord private
Referenced by fill_in_contribution_to_jacobian_mortared_nodes(), and position_in_element().
Node_pt
SolidNode* oomph::NodeElementSolidOnlyMortaringElement::Node_pt private
Referenced by solid_node_pt().
The documentation for this class was generated from the following file:
node_element_constraint_elements.h