MercuryDPM: MovingIntersectionOfWallsUnitTest.cpp File Reference
MovingIntersectionOfWallsUnitTest.cpp File Reference
#include <cmath>
#include <iostream>
#include <iomanip>
#include "Logger.h"
#include "DPMBase.h"
#include "Walls/IntersectionOfWalls.h"
#include "Species/LinearViscoelasticSpecies.h"
Classes
class MovingIntersectionOfWallsUnitTest_Basic
class MovingIntersectionOfWallsUnitTest_MovingReferenceFrame
Functions
void compareParticles (BaseParticle *Ptest, BaseParticle *Pref, double absError, Vec3D positionDifference, Vec3D velocityDifference, Quaternion orientationDifference, Vec3D AngularVelocityDifference)
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
compareParticles()
void compareParticles (BaseParticle * Ptest, BaseParticle * Pref, double absError, Vec3D positionDifference, Vec3D velocityDifference, Quaternion orientationDifference, Vec3D AngularVelocityDifference)
 {
     if (!mathsFunc::isEqual(Ptest->getPosition(), Pref->getPosition() + positionDifference, absError))
     {
         logger(FATAL, "The particle has the wrong position. It is %, however is should be %, the difference is %", Ptest->getPosition(), Pref->getPosition() + positionDifference, Ptest->getPosition() - Pref->getPosition() - positionDifference);
     }
     if (!mathsFunc::isEqual(Ptest->getVelocity(), Pref->getVelocity() + velocityDifference, absError))
     {
         logger(FATAL, "The particle has the wrong velocity. It is %, however is should be %, the difference is %", Ptest->getVelocity(), Pref->getVelocity() + velocityDifference, Ptest->getVelocity() - Pref->getVelocity() - velocityDifference);
     }
     if (!mathsFunc::isEqual(Ptest->getOrientation(), Pref->getOrientation() + orientationDifference, absError))
     {
         logger(FATAL, "The particle has the wrong orientation. It is %, however is should be %, the difference is %", Ptest->getOrientation(), Pref->getOrientation() + orientationDifference, Ptest->getOrientation() - Pref->getOrientation() - orientationDifference);
     }
     if (!mathsFunc::isEqual(Ptest->getAngularVelocity(), Pref->getAngularVelocity() + AngularVelocityDifference, absError))
     {
         logger(FATAL, "The particle has the wrong angular velocity. It is %, however is should be %, the difference is %", Ptest->getAngularVelocity(), Pref->getAngularVelocity() + AngularVelocityDifference, Ptest->getAngularVelocity() - Pref->getAngularVelocity() - AngularVelocityDifference);
     }
 }
References FATAL, BaseInteractable::getAngularVelocity(), BaseInteractable::getOrientation(), BaseInteractable::getPosition(), BaseInteractable::getVelocity(), mathsFunc::isEqual(), and logger.
Referenced by main().
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     MovingIntersectionOfWallsUnitTest_Basic basic;
     MovingIntersectionOfWallsUnitTest_MovingReferenceFrame movingReferenceFrame;
     basic.setName("MovingIntersectionOfWallsUnitTest_Basic");
     movingReferenceFrame.setName("MovingIntersectionOfWallsUnitTest_MovingReferenceFrame");
     basic.solve();
     movingReferenceFrame.solve();
     compareParticles(movingReferenceFrame.p1f,basic.p1f, 1e-10, movingReferenceFrame.velocity*movingReferenceFrame.getTime(), movingReferenceFrame.velocity, {0,0,0,0}, {0,0,0});
     compareParticles(movingReferenceFrame.p2f,basic.p2f, 1e-10, movingReferenceFrame.velocity*movingReferenceFrame.getTime(), movingReferenceFrame.velocity, {0,0,0,0}, {0,0,0});
     compareParticles(movingReferenceFrame.p3f,basic.p3f, 1e-10, movingReferenceFrame.velocity*movingReferenceFrame.getTime(), movingReferenceFrame.velocity, {0,0,0,0}, {0,0,0});
     compareParticles(movingReferenceFrame.p1e,basic.p1e, 1e-10, movingReferenceFrame.velocity*movingReferenceFrame.getTime(), movingReferenceFrame.velocity, {0,0,0,0}, {0,0,0});
     compareParticles(movingReferenceFrame.p2e,basic.p2e, 1e-10, movingReferenceFrame.velocity*movingReferenceFrame.getTime(), movingReferenceFrame.velocity, {0,0,0,0}, {0,0,0});
     compareParticles(movingReferenceFrame.p3e,basic.p3e, 1e-10, movingReferenceFrame.velocity*movingReferenceFrame.getTime(), movingReferenceFrame.velocity, {0,0,0,0}, {0,0,0});
 }
References compareParticles(), e(), DPMBase::getTime(), MovingIntersectionOfWallsUnitTest_Basic::p1e, MovingIntersectionOfWallsUnitTest_Basic::p1f, MovingIntersectionOfWallsUnitTest_Basic::p2e, MovingIntersectionOfWallsUnitTest_Basic::p2f, MovingIntersectionOfWallsUnitTest_Basic::p3e, MovingIntersectionOfWallsUnitTest_Basic::p3f, DPMBase::setName(), DPMBase::solve(), and MovingIntersectionOfWallsUnitTest_MovingReferenceFrame::velocity.