MercuryDPM: oomph::TriangleMeshBase Class Reference
oomph::TriangleMeshBase Class Reference
#include <triangle_mesh.h>
Public Member Functions
TriangleMeshBase ()
Constructor.
TriangleMeshBase (const TriangleMeshBase &node)=delete
Broken copy constructor.
virtual ~TriangleMeshBase ()
Broken assignment operator.
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
virtual void load_balance (const Vector< unsigned > &target_domain_for_local_non_halo_element)
Virtual function to perform the load balance rutines.
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
Public Member Functions inherited from oomph::UnstructuredTwoDMeshGeometryBase
UnstructuredTwoDMeshGeometryBase ()
Empty constructor.
UnstructuredTwoDMeshGeometryBase (const UnstructuredTwoDMeshGeometryBase &dummy)=delete
Broken copy constructor.
void operator= (const UnstructuredTwoDMeshGeometryBase &)=delete
Broken assignment operator.
~UnstructuredTwoDMeshGeometryBase ()
Empty destructor.
unsigned nregion ()
Return the number of regions specified by attributes.
unsigned nregion_element (const unsigned &i)
Return the number of elements in the i-th region.
FiniteElement * region_element_pt (const unsigned &i, const unsigned &e)
Return the e-th element in the i-th region.
unsigned nregion_attribute ()
Return the number of attributes used in the mesh.
double region_attribute (const unsigned &i)
Return the attribute associated with region i.
GeomObject * boundary_geom_object_pt (const unsigned &b)
std::map< unsigned, GeomObject * > & boundary_geom_object_pt ()
Return direct access to the geometric object storage.
std::map< unsigned, Vector< double > > & boundary_coordinate_limits ()
Vector< double > & boundary_coordinate_limits (const unsigned &b)
unsigned nboundary_element_in_region (const unsigned &b, const unsigned &r) const
Return the number of elements adjacent to boundary b in region r.
FiniteElement * boundary_element_in_region_pt (const unsigned &b, const unsigned &r, const unsigned &e) const
Return pointer to the e-th element adjacent to boundary b in region r.
int face_index_at_boundary_in_region (const unsigned &b, const unsigned &r, const unsigned &e) const
Return face index of the e-th element adjacent to boundary b in region r.
TriangleMeshPolyLine * boundary_polyline_pt (const unsigned &b)
std::map< unsigned, std::set< Node * > > & nodes_on_boundary_pt ()
const bool get_connected_vertex_number_on_destination_polyline (TriangleMeshPolyLine *dst_polyline_pt, Vector< double > &vertex_coordinates, unsigned &vertex_number)
void check_contiguousness_on_polylines_helper (Vector< TriangleMeshPolyLine * > &polylines_pt, unsigned &index)
void check_contiguousness_on_polylines_helper (Vector< TriangleMeshPolyLine * > &polylines_pt, unsigned &index_halo_start, unsigned &index_halo_end)
bool is_point_inside_polygon_helper (Vector< Vector< double >> polygon_vertices, Vector< double > point)
Helper function that checks if a given point is inside a polygon.
void enable_automatic_creation_of_vertices_on_boundaries ()
void disable_automatic_creation_of_vertices_on_boundaries ()
bool is_automatic_creation_of_vertices_on_boundaries_allowed ()
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, std::ofstream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::UnstructuredTwoDMeshGeometryBase
static bool Suppress_warning_about_regions_and_boundaries
Public static flag to suppress warning; defaults to false.
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::UnstructuredTwoDMeshGeometryBase
void snap_nodes_onto_geometric_objects ()
void copy_connection_information (TriangleMeshCurveSection *input_curve_pt, TriangleMeshCurveSection *output_curve_pt)
void copy_connection_information_to_sub_polylines (TriangleMeshCurveSection *input_curve_pt, TriangleMeshCurveSection *output_curve_pt)
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes inherited from oomph::UnstructuredTwoDMeshGeometryBase
bool Allow_automatic_creation_of_vertices_on_boundaries
std::map< unsigned, Vector< FiniteElement * > > Region_element_pt
Vector< double > Region_attribute
Vector of attributes associated with the elements in each region.
std::map< unsigned, GeomObject * > Boundary_geom_object_pt
Storage for the geometric objects associated with any boundaries.
std::map< unsigned, Vector< double > > Boundary_coordinate_limits
Vector< TriangleMeshPolygon * > Outer_boundary_pt
Polygon that defines outer boundaries.
Vector< TriangleMeshPolygon * > Internal_polygon_pt
Vector of polygons that define internal polygons.
Vector< TriangleMeshOpenCurve * > Internal_open_curve_pt
Vector of open polylines that define internal curves.
Vector< Vector< double > > Extra_holes_coordinates
Storage for extra coordinates for holes.
std::map< unsigned, Vector< double > > Regions_coordinates
std::map< unsigned, TriangleMeshCurveSection * > Boundary_curve_section_pt
Vector< std::map< unsigned, Vector< FiniteElement * > > > Boundary_region_element_pt
Storage for elements adjacent to a boundary in a particular region.
Vector< std::map< unsigned, Vector< int > > > Face_index_region_at_boundary
Storage for the face index adjacent to a boundary in a particular region.
std::map< unsigned, Vector< std::pair< double, double > > > Polygonal_vertex_arclength_info
std::map< unsigned, std::set< Node * > > Nodes_on_boundary_pt
std::set< TriangleMeshCurveSection * > Free_curve_section_pt
std::set< TriangleMeshPolygon * > Free_polygon_pt
std::set< TriangleMeshOpenCurve * > Free_open_curve_pt
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Detailed Description
Base class for triangle meshes (meshes made of 2D triangle elements). Note: we choose to template TriangleMeshBase here because certain functions in UnstructuredTwoDMeshGeometryBase need template parameters and it's much cleaner simply to template the entire class
Constructor & Destructor Documentation
TriangleMeshBase() [1/2]
oomph::TriangleMeshBase::TriangleMeshBase () inline
Constructor.
     {
 #ifdef OOMPH_HAS_TRIANGLE_LIB
       // Initialise the TriangulateIO Data structure
       TriangleHelper::initialise_triangulateio(Triangulateio);
       // Enable triangulateio specific parts for dump/restart by default.
       Use_triangulateio_restart = true;
 #endif
     }
TriangleMeshBase() [2/2]
oomph::TriangleMeshBase::TriangleMeshBase (const TriangleMeshBase & node) delete
Broken copy constructor.
~TriangleMeshBase()
virtual oomph::TriangleMeshBase::~TriangleMeshBase () inline virtual
Broken assignment operator.
Destructor (empty)
     {
 #ifdef OOMPH_HAS_TRIANGLE_LIB
       // Clear the triangulate data structure
       TriangleHelper::clear_triangulateio(Triangulateio);
 #endif
     }
Member Function Documentation
load_balance()
virtual void oomph::TriangleMeshBase::load_balance (const Vector< unsigned > & target_domain_for_local_non_halo_element) inline virtual
Virtual function to perform the load balance rutines.
     {
       std::ostringstream error_stream;
       error_stream << "Empty default load balancing function called.\n";
       error_stream << "This should be overloaded in a specific TriangleMesh\n";
       throw OomphLibError(error_stream.str(),
                           "TriangleMeshBase::load_balance()",
                           OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_EXCEPTION_LOCATION.
reset_boundary_element_info()
virtual void oomph::TriangleMeshBase::reset_boundary_element_info (Vector< unsigned > & ntmp_boundary_elements, Vector< Vector< unsigned >> & ntmp_boundary_elements_in_region, Vector< FiniteElement * > & deleted_elements) inline virtual
Virtual function to perform the reset boundary elements info rutines.
Reimplemented from oomph::Mesh.
     {
       std::ostringstream error_stream;
       error_stream << "Empty default reset boundary element info function"
                    << "called.\n";
       error_stream << "This should be overloaded in a specific "
                    << "TriangleMesh\n";
       throw OomphLibError(error_stream.str(),
                           "TriangleMeshBase::reset_boundary_element_info()",
                           OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_EXCEPTION_LOCATION.
setup_boundary_element_info() [1/2]
void oomph::TriangleMeshBase::setup_boundary_element_info () inline virtual
Setup lookup schemes which establish whic elements are located next to mesh's boundaries (wrapper to suppress doc).
Reimplemented from oomph::Mesh.
     {
       std::ofstream outfile;
       setup_boundary_element_info(outfile);
     }
setup_boundary_element_info() [2/2]
void oomph::TriangleMeshBase::setup_boundary_element_info (std::ostream & outfile) virtual
Setup lookup schemes which establish which elements are located next to mesh's boundaries. Doc in outfile (if it's open).
Setup lookup schemes which establish which elements are located next to which boundaries (Doc to outfile if it's open).
Reimplemented from oomph::Mesh.
   {
     // Should we document the output here
     bool doc = false;
     if (outfile) doc = true;
     // Number of boundaries
     unsigned nbound = nboundary();
     // Wipe/allocate storage for arrays
     Boundary_element_pt.clear();
     Face_index_at_boundary.clear();
     Boundary_element_pt.resize(nbound);
     Face_index_at_boundary.resize(nbound);
     // Temporary vector of vectors of pointers to elements on the boundaries:
     // This is a vector to ensure that order is strictly preserved
     Vector<Vector<FiniteElement*>> vector_of_boundary_element_pt;
     vector_of_boundary_element_pt.resize(nbound);
     // Matrix map for working out the fixed face for elements on boundary
     MapMatrixMixed<unsigned, FiniteElement*, int> face_identifier;
     // Loop over elements
     //-------------------
     unsigned nel = nelement();
     // Get pointer to vector of boundaries that the
     // node lives on
     Vector<std::set<unsigned>*> boundaries_pt(3, 0);
     // Data needed to deal with edges through the
     // interior of the domain
     std::map<Edge, unsigned> edge_count;
     std::map<Edge, TriangleBoundaryHelper::BCInfo> edge_bcinfo;
     std::map<Edge, TriangleBoundaryHelper::BCInfo> face_info;
     MapMatrixMixed<unsigned, FiniteElement*, int> face_count;
     Vector<unsigned> bonus(nbound);
     // When using internal boundaries, an edge can be related to more than
     // one element (because of both sides of the internal boundaries)
     std::map<Edge, Vector<TriangleBoundaryHelper::BCInfo>> edge_internal_bnd;
     for (unsigned e = 0; e < nel; e++)
     {
       // Get pointer to element
       FiniteElement* fe_pt = finite_element_pt(e);
       if (doc)
       {
         outfile << "Element: " << e << " " << fe_pt << std::endl;
       }
       // Only include 2D elements! Some meshes contain interface elements too.
       if (fe_pt->dim() == 2)
       {
         // Loop over the element's nodes and find out which boundaries they're
         // on
         // ----------------------------------------------------------------------
         // We need only loop over the corner nodes
         for (unsigned i = 0; i < 3; i++)
         {
           fe_pt->node_pt(i)->get_boundaries_pt(boundaries_pt[i]);
         }
         // Find the common boundaries of each edge
         Vector<std::set<unsigned>> edge_boundary(3);
         // Edge 0 connects points 1 and 2
         //-----------------------------
         if (boundaries_pt[1] && boundaries_pt[2])
         {
           // Create the corresponding edge
           Edge edge0(fe_pt->node_pt(1), fe_pt->node_pt(2));
           // Update infos about this edge
           TriangleBoundaryHelper::BCInfo info;
           info.Face_id = 0;
           info.FE_pt = fe_pt;
           std::set_intersection(boundaries_pt[1]->begin(),
                                 boundaries_pt[1]->end(),
                                 boundaries_pt[2]->begin(),
                                 boundaries_pt[2]->end(),
                                 std::insert_iterator<std::set<unsigned>>(
                                   edge_boundary[0], edge_boundary[0].begin()));
           std::set<unsigned>::iterator it0 = edge_boundary[0].begin();
           // Edge does exist:
           if (edge_boundary[0].size() > 0)
           {
             info.Boundary = *it0;
             // How many times this edge has been visited
             edge_count[edge0]++;
             // Update edge_bcinfo
             edge_bcinfo.insert(std::make_pair(edge0, info));
             // ... and also update the info associated with internal bnd
             edge_internal_bnd[edge0].push_back(info);
           }
         }
         // Edge 1 connects points 0 and 2
         //-----------------------------
         if (boundaries_pt[0] && boundaries_pt[2])
         {
           std::set_intersection(boundaries_pt[0]->begin(),
                                 boundaries_pt[0]->end(),
                                 boundaries_pt[2]->begin(),
                                 boundaries_pt[2]->end(),
                                 std::insert_iterator<std::set<unsigned>>(
                                   edge_boundary[1], edge_boundary[1].begin()));
           // Create the corresponding edge
           Edge edge1(fe_pt->node_pt(0), fe_pt->node_pt(2));
           // Update infos about this edge
           TriangleBoundaryHelper::BCInfo info;
           info.Face_id = 1;
           info.FE_pt = fe_pt;
           std::set<unsigned>::iterator it1 = edge_boundary[1].begin();
           // Edge does exist:
           if (edge_boundary[1].size() > 0)
           {
             info.Boundary = *it1;
             // How many times this edge has been visited
             edge_count[edge1]++;
             // Update edge_bcinfo
             edge_bcinfo.insert(std::make_pair(edge1, info));
             // ... and also update the info associated with internal bnd
             edge_internal_bnd[edge1].push_back(info);
           }
         }
         // Edge 2 connects points 0 and 1
         //-----------------------------
         if (boundaries_pt[0] && boundaries_pt[1])
         {
           std::set_intersection(boundaries_pt[0]->begin(),
                                 boundaries_pt[0]->end(),
                                 boundaries_pt[1]->begin(),
                                 boundaries_pt[1]->end(),
                                 std::insert_iterator<std::set<unsigned>>(
                                   edge_boundary[2], edge_boundary[2].begin()));
           // Create the corresponding edge
           Edge edge2(fe_pt->node_pt(0), fe_pt->node_pt(1));
           // Update infos about this edge
           TriangleBoundaryHelper::BCInfo info;
           info.Face_id = 2;
           info.FE_pt = fe_pt;
           std::set<unsigned>::iterator it2 = edge_boundary[2].begin();
           // Edge does exist:
           if (edge_boundary[2].size() > 0)
           {
             info.Boundary = *it2;
             // How many times this edge has been visited
             edge_count[edge2]++;
             // Update edge_bcinfo
             edge_bcinfo.insert(std::make_pair(edge2, info));
             // ... and also update the info associated with internal bnd
             edge_internal_bnd[edge2].push_back(info);
           }
         }
 #ifdef PARANOID
         // Check if edge is associated with multiple boundaries
         // We now know whether any edges lay on the boundaries
         for (unsigned i = 0; i < 3; i++)
         {
           // How many boundaries are there
           unsigned count = 0;
           // Loop over all the members of the set and add to the count
           // and set the boundary
           for (std::set<unsigned>::iterator it = edge_boundary[i].begin();
                it != edge_boundary[i].end();
                ++it)
           {
             ++count;
           }
           // If we're on more than one boundary, this is weird, so die
           if (count > 1)
           {
             std::ostringstream error_stream;
             error_stream << "Edge " << i << " is located on " << count
                          << " boundaries.\n";
             error_stream << "This is rather strange, so I'm going to die\n";
             throw OomphLibError(error_stream.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
           }
         }
 #endif
         // Now we set the pointers to the boundary sets to zero
         for (unsigned i = 0; i < 3; i++)
         {
           boundaries_pt[i] = 0;
         }
       }
     } // end of loop over all elements
     // Loop over all edges that are located on a boundary
     typedef std::map<Edge, TriangleBoundaryHelper::BCInfo>::iterator ITE;
     for (ITE it = edge_bcinfo.begin(); it != edge_bcinfo.end(); it++)
     {
       Edge current_edge = it->first;
       unsigned bound = it->second.Boundary;
       // If the edge has been visited only once
       if (edge_count[current_edge] == 1)
       {
         // Count the edges that are on the same element and on the same boundary
         face_count(static_cast<unsigned>(bound), it->second.FE_pt) =
           face_count(static_cast<unsigned>(bound), it->second.FE_pt) + 1;
         // If such edges exist, let store the corresponding element
         if (face_count(bound, it->second.FE_pt) > 1)
         {
           // Update edge's infos
           TriangleBoundaryHelper::BCInfo info;
           info.Face_id = it->second.Face_id;
           info.FE_pt = it->second.FE_pt;
           info.Boundary = it->second.Boundary;
           // Add it to FIinfo, that stores infos of problematic elements
           face_info.insert(std::make_pair(current_edge, info));
           // How many edges on which boundary have to be added
           bonus[bound]++;
         }
         else
         {
           // Add element and face to the appropriate vectors
           // Does the pointer already exits in the vector
           Vector<FiniteElement*>::iterator b_el_it = std::find(
             vector_of_boundary_element_pt[static_cast<unsigned>(bound)].begin(),
             vector_of_boundary_element_pt[static_cast<unsigned>(bound)].end(),
             it->second.FE_pt);
           // Only insert if we have not found it (i.e. got to the end)
           if (b_el_it ==
               vector_of_boundary_element_pt[static_cast<unsigned>(bound)].end())
           {
             vector_of_boundary_element_pt[static_cast<unsigned>(bound)]
               .push_back(it->second.FE_pt);
           }
           // set_of_boundary_element_pt[static_cast<unsigned>(bound)].insert(
           // it->second.FE_pt);
           face_identifier(static_cast<unsigned>(bound), it->second.FE_pt) =
             it->second.Face_id;
         }
       }
     } // End of "adding-boundaries"-loop
     // Now copy everything across into permanent arrays
     //-------------------------------------------------
     // Loop over boundaries
     for (unsigned i = 0; i < nbound; i++)
     {
       // Number of elements on this boundary that have to be added
       // in addition to other elements
       unsigned bonus1 = bonus[i];
       // Number of elements on this boundary
       unsigned nel = vector_of_boundary_element_pt[i].size() + bonus1;
       // Allocate storage for the coordinate identifiers
       Face_index_at_boundary[i].resize(nel);
       unsigned e_count = 0;
       typedef Vector<FiniteElement*>::iterator IT;
       for (IT it = vector_of_boundary_element_pt[i].begin();
            it != vector_of_boundary_element_pt[i].end();
            it++)
       {
         // Recover pointer to element
         FiniteElement* fe_pt = *it;
         // Add to permanent storage
         Boundary_element_pt[i].push_back(fe_pt);
         Face_index_at_boundary[i][e_count] = face_identifier(i, fe_pt);
         // Increment counter
         e_count++;
       }
       // We add the elements that have two or more edges on this boundary
       for (ITE itt = face_info.begin(); itt != face_info.end(); itt++)
       {
         if (itt->second.Boundary == i)
         {
           // Add to permanent storage
           Boundary_element_pt[i].push_back(itt->second.FE_pt);
           Face_index_at_boundary[i][e_count] = itt->second.Face_id;
           e_count++;
         }
       }
     } // End of loop over boundaries
     // Doc?
     //-----
     if (doc)
     {
       // Loop over boundaries
       for (unsigned i = 0; i < nbound; i++)
       {
         unsigned nel = Boundary_element_pt[i].size();
         outfile << "Boundary: " << i << " is adjacent to " << nel << " elements"
                 << std::endl;
         // Loop over elements on given boundary
         for (unsigned e = 0; e < nel; e++)
         {
           FiniteElement* fe_pt = Boundary_element_pt[i][e];
           outfile << "Boundary element:" << fe_pt
                   << " Face index of boundary is "
                   << Face_index_at_boundary[i][e] << std::endl;
         }
       }
     }
     // Lookup scheme has now been setup yet
     Lookup_for_elements_next_boundary_is_setup = true;
   }
References oomph::Mesh::Boundary_element_pt, oomph::FiniteElement::dim(), e(), Eigen::placeholders::end, oomph::Mesh::Face_index_at_boundary, oomph::Mesh::finite_element_pt(), oomph::Node::get_boundaries_pt(), i, info, oomph::Mesh::Lookup_for_elements_next_boundary_is_setup, oomph::Mesh::nboundary(), oomph::Mesh::nelement(), oomph::FiniteElement::node_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and size.
The documentation for this class was generated from the following files:
generic/triangle_mesh.h
triangle_mesh.cc