MercuryDPM: Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols > Class Template Reference
Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols > Class Template Reference
#include <SparseBlock.h>
Public Types
enum { IsRowMajor = internal::traits<BlockType>::IsRowMajor }
Public Types inherited from Eigen::SparseCompressedBase< Block< SparseMatrixType, BlockRows, BlockCols, true > >
typedef SparseMatrixBase< Block< SparseMatrixType, BlockRows, BlockCols, true > > Base
Public Types inherited from Eigen::SparseMatrixBase< Block< SparseMatrixType, BlockRows, BlockCols, true > >
enum
typedef internal::traits< Block< SparseMatrixType, BlockRows, BlockCols, true > >::Scalar Scalar
typedef Scalar value_type
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef internal::traits< Block< SparseMatrixType, BlockRows, BlockCols, true > >::StorageKind StorageKind
typedef internal::traits< Block< SparseMatrixType, BlockRows, BlockCols, true > >::StorageIndex StorageIndex
typedef internal::add_const_on_value_type_if_arithmetic< typename internal::packet_traits< Scalar >::type >::type PacketReturnType
typedef SparseMatrixBase StorageBaseType
typedef Matrix< StorageIndex, Dynamic, 1 > IndexVector
typedef Matrix< Scalar, Dynamic, 1 > ScalarVector
typedef std::conditional_t< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, Eigen::Transpose< const Block< SparseMatrixType, BlockRows, BlockCols, true > > >, Transpose< const Block< SparseMatrixType, BlockRows, BlockCols, true > > > AdjointReturnType
typedef Transpose< Block< SparseMatrixType, BlockRows, BlockCols, true > > TransposeReturnType
typedef Transpose< const Block< SparseMatrixType, BlockRows, BlockCols, true > > ConstTransposeReturnType
typedef SparseMatrix< Scalar, Flags &RowMajorBit ? RowMajor :ColMajor, StorageIndex > PlainObject
typedef NumTraits< Scalar >::Real RealScalar
typedef std::conditional_t< HasDirectAccess_, const Scalar &, Scalar > CoeffReturnType
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, Matrix< Scalar, Dynamic, Dynamic > > ConstantReturnType
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime > DenseMatrixType
typedef Matrix< Scalar, internal::max_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime), internal::max_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime)> SquareMatrixType
typedef EigenBase< Block< SparseMatrixType, BlockRows, BlockCols, true > > Base
Public Types inherited from Eigen::EigenBase< Block< SparseMatrixType, BlockRows, BlockCols, true > >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Block< SparseMatrixType, BlockRows, BlockCols, true > >::StorageKind StorageKind
Public Member Functions
sparse_matrix_block_impl (SparseMatrixType &xpr, Index i)
sparse_matrix_block_impl (SparseMatrixType &xpr, Index startRow, Index startCol, Index blockRows, Index blockCols)
template<typename OtherDerived >
BlockType & operator= (const SparseMatrixBase< OtherDerived > &other)
BlockType & operator= (const BlockType &other)
const Scalar * valuePtr () const
Scalar * valuePtr ()
const StorageIndex * innerIndexPtr () const
StorageIndex * innerIndexPtr ()
const StorageIndex * outerIndexPtr () const
StorageIndex * outerIndexPtr ()
const StorageIndex * innerNonZeroPtr () const
StorageIndex * innerNonZeroPtr ()
bool isCompressed () const
Scalar & coeffRef (Index row, Index col)
const Scalar coeff (Index row, Index col) const
const Scalar coeff (Index index) const
const Scalar & lastCoeff () const
EIGEN_STRONG_INLINE Index rows () const
EIGEN_STRONG_INLINE Index cols () const
const SparseMatrixType & nestedExpression () const
SparseMatrixType & nestedExpression ()
Index startRow () const
Index startCol () const
Index blockRows () const
Index blockCols () const
Public Member Functions inherited from Eigen::SparseCompressedBase< Block< SparseMatrixType, BlockRows, BlockCols, true > >
Index nonZeros () const
const Scalar * valuePtr () const
Scalar * valuePtr ()
const StorageIndex * innerIndexPtr () const
StorageIndex * innerIndexPtr ()
const StorageIndex * outerIndexPtr () const
StorageIndex * outerIndexPtr ()
const StorageIndex * innerNonZeroPtr () const
StorageIndex * innerNonZeroPtr ()
bool isCompressed () const
const Map< const Array< Scalar, Dynamic, 1 > > coeffs () const
Map< Array< Scalar, Dynamic, 1 > > coeffs ()
void sortInnerIndices (Index begin, Index end)
void sortInnerIndices ()
Index innerIndicesAreSorted (Index begin, Index end) const
Index innerIndicesAreSorted () const
Block< SparseMatrixType, BlockRows, BlockCols, true > & operator= (const EigenBase< OtherDerived > &other)
Block< SparseMatrixType, BlockRows, BlockCols, true > & operator= (const ReturnByValue< OtherDerived > &other)
Block< SparseMatrixType, BlockRows, BlockCols, true > & operator= (const SparseMatrixBase< OtherDerived > &other)
Block< SparseMatrixType, BlockRows, BlockCols, true > & operator= (const Block< SparseMatrixType, BlockRows, BlockCols, true > &other)
Public Member Functions inherited from Eigen::SparseMatrixBase< Block< SparseMatrixType, BlockRows, BlockCols, true > >
Block< SparseMatrixType, BlockRows, BlockCols, true > & operator= (const EigenBase< OtherDerived > &other)
Block< SparseMatrixType, BlockRows, BlockCols, true > & operator= (const ReturnByValue< OtherDerived > &other)
Block< SparseMatrixType, BlockRows, BlockCols, true > & operator= (const SparseMatrixBase< OtherDerived > &other)
Block< SparseMatrixType, BlockRows, BlockCols, true > & operator= (const Block< SparseMatrixType, BlockRows, BlockCols, true > &other)
const Block< SparseMatrixType, BlockRows, BlockCols, true > & derived () const
Block< SparseMatrixType, BlockRows, BlockCols, true > & derived ()
Block< SparseMatrixType, BlockRows, BlockCols, true > & const_cast_derived () const
Index rows () const
Index cols () const
Index size () const
bool isVector () const
Index outerSize () const
Index innerSize () const
bool isRValue () const
Block< SparseMatrixType, BlockRows, BlockCols, true > & markAsRValue ()
SparseMatrixBase ()
Block< SparseMatrixType, BlockRows, BlockCols, true > & operator+= (const SparseMatrixBase< OtherDerived > &other)
Block< SparseMatrixType, BlockRows, BlockCols, true > & operator+= (const DiagonalBase< OtherDerived > &other)
Block< SparseMatrixType, BlockRows, BlockCols, true > & operator+= (const EigenBase< OtherDerived > &other)
EIGEN_STRONG_INLINE Block< SparseMatrixType, BlockRows, BlockCols, true > & operator+= (const SparseMatrixBase< OtherDerived > &other)
Block< SparseMatrixType, BlockRows, BlockCols, true > & operator-= (const SparseMatrixBase< OtherDerived > &other)
Block< SparseMatrixType, BlockRows, BlockCols, true > & operator-= (const DiagonalBase< OtherDerived > &other)
Block< SparseMatrixType, BlockRows, BlockCols, true > & operator-= (const EigenBase< OtherDerived > &other)
EIGEN_STRONG_INLINE Block< SparseMatrixType, BlockRows, BlockCols, true > & operator-= (const SparseMatrixBase< OtherDerived > &other)
Block< SparseMatrixType, BlockRows, BlockCols, true > & operator*= (const Scalar &other)
Block< SparseMatrixType, BlockRows, BlockCols, true > & operator*= (const SparseMatrixBase< OtherDerived > &other)
Block< SparseMatrixType, BlockRows, BlockCols, true > & operator/= (const Scalar &other)
EIGEN_STRONG_INLINE const CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
EIGEN_STRONG_INLINE const SparseMatrixBase< Block< SparseMatrixType, BlockRows, BlockCols, true > >::template CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
const Product< Block< SparseMatrixType, BlockRows, BlockCols, true >, OtherDerived > operator* (const DiagonalBase< OtherDerived > &other) const
const Product< Block< SparseMatrixType, BlockRows, BlockCols, true >, OtherDerived, AliasFreeProduct > operator* (const SparseMatrixBase< OtherDerived > &other) const
const Product< Block< SparseMatrixType, BlockRows, BlockCols, true >, OtherDerived > operator* (const MatrixBase< OtherDerived > &other) const
SparseSymmetricPermutationProduct< Block< SparseMatrixType, BlockRows, BlockCols, true >, Upper|Lower > twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > &perm) const
const TriangularView< const Block< SparseMatrixType, BlockRows, BlockCols, true >, Mode > triangularView () const
ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
SparseMatrixBase< Block< SparseMatrixType, BlockRows, BlockCols, true > >::template ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
SparseMatrixBase< Block< SparseMatrixType, BlockRows, BlockCols, true > >::template SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
Scalar dot (const MatrixBase< OtherDerived > &other) const
Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
internal::traits< Block< SparseMatrixType, BlockRows, BlockCols, true > >::Scalar dot (const MatrixBase< OtherDerived > &other) const
internal::traits< Block< SparseMatrixType, BlockRows, BlockCols, true > >::Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
RealScalar squaredNorm () const
RealScalar norm () const
RealScalar blueNorm () const
TransposeReturnType transpose ()
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
DenseMatrixType toDense () const
bool isApprox (const SparseMatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isApprox (const MatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
const internal::eval< Block< SparseMatrixType, BlockRows, BlockCols, true > >::type eval () const
Scalar sum () const
const SparseView< Block< SparseMatrixType, BlockRows, BlockCols, true > > pruned (const Scalar &reference=Scalar(0), const RealScalar &epsilon=NumTraits< Scalar >::dummy_precision()) const
Public Member Functions inherited from Eigen::EigenBase< Block< SparseMatrixType, BlockRows, BlockCols, true > >
constexpr EIGEN_DEVICE_FUNC Block< SparseMatrixType, BlockRows, BlockCols, true > & derived ()
constexpr EIGEN_DEVICE_FUNC const Block< SparseMatrixType, BlockRows, BlockCols, true > & derived () const
EIGEN_DEVICE_FUNC Block< SparseMatrixType, BlockRows, BlockCols, true > & const_cast_derived () const
EIGEN_DEVICE_FUNC const Block< SparseMatrixType, BlockRows, BlockCols, true > & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< Block< SparseMatrixType, BlockRows, BlockCols, true >, Device > device (Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const Block< SparseMatrixType, BlockRows, BlockCols, true >, Device > device (Device &device) const
Protected Types
enum { OuterSize = IsRowMajor ? BlockRows : BlockCols }
typedef Base::IndexVector IndexVector
Protected Types inherited from Eigen::SparseCompressedBase< Block< SparseMatrixType, BlockRows, BlockCols, true > >
typedef Base::IndexVector IndexVector
Protected Attributes
internal::ref_selector< SparseMatrixType >::non_const_type m_matrix
Index m_outerStart
const internal::variable_if_dynamic< Index, OuterSize > m_outerSize
Protected Attributes inherited from Eigen::SparseMatrixBase< Block< SparseMatrixType, BlockRows, BlockCols, true > >
bool m_isRValue
Private Types
typedef internal::remove_all_t< typename SparseMatrixType::Nested > MatrixTypeNested_
typedef Block< SparseMatrixType, BlockRows, BlockCols, true > BlockType
typedef SparseCompressedBase< Block< SparseMatrixType, BlockRows, BlockCols, true > > Base
Additional Inherited Members
Protected Member Functions inherited from Eigen::SparseCompressedBase< Block< SparseMatrixType, BlockRows, BlockCols, true > >
Eigen::Map< IndexVector > innerNonZeros ()
const Eigen::Map< const IndexVector > innerNonZeros () const
SparseCompressedBase ()
internal::LowerBoundIndex lower_bound (Index row, Index col) const
Protected Member Functions inherited from Eigen::SparseMatrixBase< Block< SparseMatrixType, BlockRows, BlockCols, true > >
Block< SparseMatrixType, BlockRows, BlockCols, true > & assign (const OtherDerived &other)
void assignGeneric (const OtherDerived &other)
Static Protected Member Functions inherited from Eigen::SparseMatrixBase< Block< SparseMatrixType, BlockRows, BlockCols, true > >
static StorageIndex convert_index (const Index idx)
Member Typedef Documentation
Base
template<typename SparseMatrixType , int BlockRows, int BlockCols> typedef SparseCompressedBase<Block<SparseMatrixType, BlockRows, BlockCols, true> > Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::Base private
BlockType
template<typename SparseMatrixType , int BlockRows, int BlockCols> typedef Block<SparseMatrixType, BlockRows, BlockCols, true> Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::BlockType private
IndexVector
template<typename SparseMatrixType , int BlockRows, int BlockCols> typedef Base::IndexVector Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::IndexVector protected
MatrixTypeNested_
template<typename SparseMatrixType , int BlockRows, int BlockCols> typedef internal::remove_all_t<typename SparseMatrixType::Nested> Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::MatrixTypeNested_ private
Member Enumeration Documentation
anonymous enum
template<typename SparseMatrixType , int BlockRows, int BlockCols> anonymous enum
Enumerator
IsRowMajor
 { IsRowMajor = internal::traits<BlockType>::IsRowMajor };
anonymous enum
template<typename SparseMatrixType , int BlockRows, int BlockCols> anonymous enum protected
Enumerator
OuterSize
 { OuterSize = IsRowMajor ? BlockRows : BlockCols };
Constructor & Destructor Documentation
sparse_matrix_block_impl() [1/2]
template<typename SparseMatrixType , int BlockRows, int BlockCols> Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::sparse_matrix_block_impl (SparseMatrixType & xpr, Index i) inline
       : m_matrix(xpr), m_outerStart(convert_index(i)), m_outerSize(OuterSize) {}
sparse_matrix_block_impl() [2/2]
template<typename SparseMatrixType , int BlockRows, int BlockCols> Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::sparse_matrix_block_impl (SparseMatrixType & xpr, Index startRow, Index startCol, Index blockRows, Index blockCols) inline
       : m_matrix(xpr),
         m_outerStart(convert_index(IsRowMajor ? startRow : startCol)),
         m_outerSize(convert_index(IsRowMajor ? blockRows : blockCols)) {}
Member Function Documentation
blockCols()
template<typename SparseMatrixType , int BlockRows, int BlockCols> Index Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::blockCols () const inline
 { return IsRowMajor ? m_matrix.cols() : m_outerSize.value(); }
References Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::IsRowMajor, Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_matrix, Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_outerSize, and Eigen::internal::variable_if_dynamic< T, Value >::value().
blockRows()
template<typename SparseMatrixType , int BlockRows, int BlockCols> Index Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::blockRows () const inline
 { return IsRowMajor ? m_outerSize.value() : m_matrix.rows(); }
References Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::IsRowMajor, Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_matrix, Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_outerSize, and Eigen::internal::variable_if_dynamic< T, Value >::value().
coeff() [1/2]
template<typename SparseMatrixType , int BlockRows, int BlockCols> const Scalar Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::coeff (Index index) const inline
{
     return m_matrix.coeff(IsRowMajor ? m_outerStart : index, IsRowMajor ? index : m_outerStart);
   }
References Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::IsRowMajor, Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_matrix, and Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_outerStart.
coeff() [2/2]
template<typename SparseMatrixType , int BlockRows, int BlockCols> const Scalar Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::coeff (Index row, Index col) const inline
{
     return m_matrix.coeff(row + (IsRowMajor ? m_outerStart : 0), col + (IsRowMajor ? 0 : m_outerStart));
   }
References col(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::IsRowMajor, Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_matrix, Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_outerStart, and row().
coeffRef()
template<typename SparseMatrixType , int BlockRows, int BlockCols> Scalar& Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::coeffRef (Index row, Index col) inline
{
     return m_matrix.coeffRef(row + (IsRowMajor ? m_outerStart : 0), col + (IsRowMajor ? 0 : m_outerStart));
   }
References col(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::IsRowMajor, Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_matrix, Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_outerStart, and row().
cols()
template<typename SparseMatrixType , int BlockRows, int BlockCols> EIGEN_STRONG_INLINE Index Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::cols () const inline
 { return IsRowMajor ? m_matrix.cols() : m_outerSize.value(); }
References Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::IsRowMajor, Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_matrix, Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_outerSize, and Eigen::internal::variable_if_dynamic< T, Value >::value().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
innerIndexPtr() [1/2]
template<typename SparseMatrixType , int BlockRows, int BlockCols> StorageIndex* Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::innerIndexPtr () inline
 { return m_matrix.innerIndexPtr(); }
References Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_matrix.
innerIndexPtr() [2/2]
template<typename SparseMatrixType , int BlockRows, int BlockCols> const StorageIndex* Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::innerIndexPtr () const inline
 { return m_matrix.innerIndexPtr(); }
References Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_matrix.
innerNonZeroPtr() [1/2]
template<typename SparseMatrixType , int BlockRows, int BlockCols> StorageIndex* Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::innerNonZeroPtr () inline
 { return isCompressed() ? 0 : (m_matrix.innerNonZeroPtr() + m_outerStart); }
References Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::isCompressed(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_matrix, and Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_outerStart.
innerNonZeroPtr() [2/2]
template<typename SparseMatrixType , int BlockRows, int BlockCols> const StorageIndex* Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::innerNonZeroPtr () const inline
{
     return isCompressed() ? 0 : (m_matrix.innerNonZeroPtr() + m_outerStart);
   }
References Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::isCompressed(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_matrix, and Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_outerStart.
isCompressed()
template<typename SparseMatrixType , int BlockRows, int BlockCols> bool Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::isCompressed () const inline
 { return m_matrix.innerNonZeroPtr() == 0; }
References Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_matrix.
Referenced by Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::innerNonZeroPtr().
lastCoeff()
template<typename SparseMatrixType , int BlockRows, int BlockCols> const Scalar& Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::lastCoeff () const inline
{
     EIGEN_STATIC_ASSERT_VECTOR_ONLY(sparse_matrix_block_impl);
     eigen_assert(Base::nonZeros() > 0);
     if (m_matrix.isCompressed())
       return m_matrix.valuePtr()[m_matrix.outerIndexPtr()[m_outerStart + 1] - 1];
     else
       return m_matrix.valuePtr()[m_matrix.outerIndexPtr()[m_outerStart] + m_matrix.innerNonZeroPtr()[m_outerStart] - 1];
   }
References eigen_assert, EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_matrix, Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_outerStart, and Eigen::SparseCompressedBase< Block< SparseMatrixType, BlockRows, BlockCols, true > >::nonZeros().
nestedExpression() [1/2]
template<typename SparseMatrixType , int BlockRows, int BlockCols> SparseMatrixType& Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::nestedExpression () inline
 { return m_matrix; }
References Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_matrix.
nestedExpression() [2/2]
template<typename SparseMatrixType , int BlockRows, int BlockCols> const SparseMatrixType& Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::nestedExpression () const inline
 { return m_matrix; }
References Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_matrix.
operator=() [1/2]
template<typename SparseMatrixType , int BlockRows, int BlockCols> BlockType& Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::operator= (const BlockType & other) inline
 { return operator= <BlockType>(other); }
operator=() [2/2]
template<typename SparseMatrixType , int BlockRows, int BlockCols> template<typename OtherDerived > BlockType& Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::operator= (const SparseMatrixBase< OtherDerived > & other) inline
{
     typedef internal::remove_all_t<typename SparseMatrixType::Nested> NestedMatrixType_;
     NestedMatrixType_& matrix = m_matrix;
     // This assignment is slow if this vector set is not empty
     // and/or it is not at the end of the nonzeros of the underlying matrix.
     // 1 - eval to a temporary to avoid transposition and/or aliasing issues
     Ref<const SparseMatrix<Scalar, IsRowMajor ? RowMajor : ColMajor, StorageIndex> > tmp(other.derived());
     eigen_internal_assert(tmp.outerSize() == m_outerSize.value());
     // 2 - let's check whether there is enough allocated memory
     Index nnz = tmp.nonZeros();
     Index start =
         m_outerStart == 0 ? 0 : m_matrix.outerIndexPtr()[m_outerStart];        // starting position of the current block
     Index end = m_matrix.outerIndexPtr()[m_outerStart + m_outerSize.value()];  // ending position of the current block
     Index block_size = end - start;                                            // available room in the current block
     Index tail_size = m_matrix.outerIndexPtr()[m_matrix.outerSize()] - end;
     Index free_size = m_matrix.isCompressed() ? Index(matrix.data().allocatedSize()) + block_size : block_size;
     Index tmp_start = tmp.outerIndexPtr()[0];
     bool update_trailing_pointers = false;
     if (nnz > free_size) {
       // realloc manually to reduce copies
       typename SparseMatrixType::Storage newdata(m_matrix.data().allocatedSize() - block_size + nnz);
       internal::smart_copy(m_matrix.valuePtr(), m_matrix.valuePtr() + start, newdata.valuePtr());
       internal::smart_copy(m_matrix.innerIndexPtr(), m_matrix.innerIndexPtr() + start, newdata.indexPtr());
       internal::smart_copy(tmp.valuePtr() + tmp_start, tmp.valuePtr() + tmp_start + nnz, newdata.valuePtr() + start);
       internal::smart_copy(tmp.innerIndexPtr() + tmp_start, tmp.innerIndexPtr() + tmp_start + nnz,
                            newdata.indexPtr() + start);
       internal::smart_copy(matrix.valuePtr() + end, matrix.valuePtr() + end + tail_size,
                            newdata.valuePtr() + start + nnz);
       internal::smart_copy(matrix.innerIndexPtr() + end, matrix.innerIndexPtr() + end + tail_size,
                            newdata.indexPtr() + start + nnz);
       newdata.resize(m_matrix.outerIndexPtr()[m_matrix.outerSize()] - block_size + nnz);
       matrix.data().swap(newdata);
       update_trailing_pointers = true;
     } else {
       if (m_matrix.isCompressed() && nnz != block_size) {
         // no need to realloc, simply copy the tail at its respective position and insert tmp
         matrix.data().resize(start + nnz + tail_size);
         internal::smart_memmove(matrix.valuePtr() + end, matrix.valuePtr() + end + tail_size,
                                 matrix.valuePtr() + start + nnz);
         internal::smart_memmove(matrix.innerIndexPtr() + end, matrix.innerIndexPtr() + end + tail_size,
                                 matrix.innerIndexPtr() + start + nnz);
         update_trailing_pointers = true;
       }
       internal::smart_copy(tmp.valuePtr() + tmp_start, tmp.valuePtr() + tmp_start + nnz, matrix.valuePtr() + start);
       internal::smart_copy(tmp.innerIndexPtr() + tmp_start, tmp.innerIndexPtr() + tmp_start + nnz,
                            matrix.innerIndexPtr() + start);
     }
     // update outer index pointers and innerNonZeros
     if (IsVectorAtCompileTime) {
       if (!m_matrix.isCompressed()) matrix.innerNonZeroPtr()[m_outerStart] = StorageIndex(nnz);
       matrix.outerIndexPtr()[m_outerStart] = StorageIndex(start);
     } else {
       StorageIndex p = StorageIndex(start);
       for (Index k = 0; k < m_outerSize.value(); ++k) {
         StorageIndex nnz_k = internal::convert_index<StorageIndex>(tmp.innerVector(k).nonZeros());
         if (!m_matrix.isCompressed()) matrix.innerNonZeroPtr()[m_outerStart + k] = nnz_k;
         matrix.outerIndexPtr()[m_outerStart + k] = p;
         p += nnz_k;
       }
     }
     if (update_trailing_pointers) {
       StorageIndex offset = internal::convert_index<StorageIndex>(nnz - block_size);
       for (Index k = m_outerStart + m_outerSize.value(); k <= matrix.outerSize(); ++k) {
         matrix.outerIndexPtr()[k] += offset;
       }
     }
     return derived();
   }
References Eigen::SparseMatrixBase< Block< SparseMatrixType, BlockRows, BlockCols, true > >::derived(), Eigen::SparseMatrixBase< Derived >::derived(), eigen_internal_assert, Eigen::placeholders::end, Eigen::SparseMatrixBase< Block< SparseMatrixType, BlockRows, BlockCols, true > >::IsVectorAtCompileTime, k, Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_matrix, Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_outerSize, Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_outerStart, matrix(), p, Eigen::internal::smart_copy(), Eigen::internal::smart_memmove(), oomph::CumulativeTimings::start(), tmp, and Eigen::internal::variable_if_dynamic< T, Value >::value().
outerIndexPtr() [1/2]
template<typename SparseMatrixType , int BlockRows, int BlockCols> StorageIndex* Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::outerIndexPtr () inline
 { return m_matrix.outerIndexPtr() + m_outerStart; }
References Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_matrix, and Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_outerStart.
outerIndexPtr() [2/2]
template<typename SparseMatrixType , int BlockRows, int BlockCols> const StorageIndex* Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::outerIndexPtr () const inline
 { return m_matrix.outerIndexPtr() + m_outerStart; }
References Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_matrix, and Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_outerStart.
rows()
template<typename SparseMatrixType , int BlockRows, int BlockCols> EIGEN_STRONG_INLINE Index Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::rows () const inline
 { return IsRowMajor ? m_outerSize.value() : m_matrix.rows(); }
References Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::IsRowMajor, Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_matrix, Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_outerSize, and Eigen::internal::variable_if_dynamic< T, Value >::value().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
startCol()
template<typename SparseMatrixType , int BlockRows, int BlockCols> Index Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::startCol () const inline
 { return IsRowMajor ? 0 : m_outerStart; }
References Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::IsRowMajor, and Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_outerStart.
startRow()
template<typename SparseMatrixType , int BlockRows, int BlockCols> Index Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::startRow () const inline
 { return IsRowMajor ? m_outerStart : 0; }
References Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::IsRowMajor, and Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_outerStart.
valuePtr() [1/2]
template<typename SparseMatrixType , int BlockRows, int BlockCols> Scalar* Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::valuePtr () inline
 { return m_matrix.valuePtr(); }
References Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_matrix.
valuePtr() [2/2]
template<typename SparseMatrixType , int BlockRows, int BlockCols> const Scalar* Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::valuePtr () const inline
 { return m_matrix.valuePtr(); }
References Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_matrix.
Member Data Documentation
m_matrix
template<typename SparseMatrixType , int BlockRows, int BlockCols> internal::ref_selector<SparseMatrixType>::non_const_type Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_matrix protected
Referenced by Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::blockCols(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::blockRows(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::coeff(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::coeffRef(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::cols(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::innerIndexPtr(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::innerNonZeroPtr(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::isCompressed(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::lastCoeff(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::nestedExpression(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::operator=(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::outerIndexPtr(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::rows(), and Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::valuePtr().
m_outerSize
template<typename SparseMatrixType , int BlockRows, int BlockCols> const internal::variable_if_dynamic<Index, OuterSize> Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_outerSize protected
Referenced by Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::blockCols(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::blockRows(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::cols(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::operator=(), and Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::rows().
m_outerStart
template<typename SparseMatrixType , int BlockRows, int BlockCols> Index Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::m_outerStart protected
Referenced by Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::coeff(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::coeffRef(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::innerNonZeroPtr(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::lastCoeff(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::operator=(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::outerIndexPtr(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::startCol(), and Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::startRow().
The documentation for this class was generated from the following file:
SparseBlock.h