MercuryDPM: FishSolnOneDPoisson Namespace Reference
FishSolnOneDPoisson Namespace Reference
Namespace for fish-shaped solution of 1D Poisson equation.
Functions
void get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact, fish-shaped solution as a 1D vector.
void source_function (const Vector< double > &x, double &source)
Source function required to make the fish shape an exact solution.
Variables
int Sign =-1
Detailed Description
Namespace for fish-shaped solution of 1D Poisson equation.
Function Documentation
get_exact_u()
void FishSolnOneDPoisson::get_exact_u (const Vector< double > & x, Vector< double > & u)
Exact, fish-shaped solution as a 1D vector.
  {
   u[0] = double(Sign)*((sin(sqrt(30.0))-1.0)*x[0]-sin(sqrt(30.0)*x[0]));
  }
References Sign, sin(), sqrt(), and plotDoE::x.
Referenced by OneDPoissonProblem< ELEMENT >::actions_before_newton_solve(), and OneDPoissonProblem< ELEMENT >::doc_solution().
source_function()
void FishSolnOneDPoisson::source_function (const Vector< double > & x, double & source)
Source function required to make the fish shape an exact solution.
  {
   source = double(Sign)*30.0*sin(sqrt(30.0)*x[0]);
  }
References Sign, sin(), TestProblem::source(), sqrt(), and plotDoE::x.
Referenced by construct_and_solve_problem(), and main().
Variable Documentation
Sign
int FishSolnOneDPoisson::Sign =-1
Sign of the source function (- gives the upper half of the fish, + the lower half)
Referenced by construct_and_solve_problem(), mathsFunc::cos(), DemoPoissonProblem::DemoPoissonProblem(), TwoNodePoissonElement::f(), get_exact_u(), main(), TwoNodePoissonElement::self_test(), TwoNodePoissonElement::sign(), mathsFunc::sin(), source_function(), and TwoNodePoissonElement::TwoNodePoissonElement().