MercuryDPM: Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IteratorBased >::InnerVectorInnerIterator Class Reference
Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IteratorBased >::InnerVectorInnerIterator Class Reference
#include <SparseBlock.h>
Public Member Functions
EIGEN_STRONG_INLINE InnerVectorInnerIterator (const unary_evaluator &aEval, Index outer)
StorageIndex index () const
Index outer () const
Index row () const
Index col () const
operator bool () const
Private Types
enum { XprIsRowMajor = unary_evaluator::IsRowMajor }
Private Attributes
const XprType & m_block
Index m_end
Member Enumeration Documentation
anonymous enum
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> anonymous enum private
Enumerator
XprIsRowMajor
 { XprIsRowMajor = unary_evaluator::IsRowMajor };
Constructor & Destructor Documentation
InnerVectorInnerIterator()
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> EIGEN_STRONG_INLINE Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IteratorBased >::InnerVectorInnerIterator::InnerVectorInnerIterator (const unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IteratorBased > & aEval, Index outer) inline
       : EvalIterator(aEval.m_argImpl, outer + (XprIsRowMajor ? aEval.m_block.startRow() : aEval.m_block.startCol())),
         m_block(aEval.m_block),
         m_end(XprIsRowMajor ? aEval.m_block.startCol() + aEval.m_block.blockCols()
                             : aEval.m_block.startRow() + aEval.m_block.blockRows()) {
     while ((EvalIterator::operator bool()) &&
            (EvalIterator::index() < (XprIsRowMajor ? m_block.startCol() : m_block.startRow())))
       EvalIterator::operator++();
   }
References Eigen::bfloat16_impl::operator++().
Member Function Documentation
col()
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> Index Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IteratorBased >::InnerVectorInnerIterator::col () const inline
 { return EvalIterator::col() - m_block.startCol(); }
References col().
index()
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> StorageIndex Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IteratorBased >::InnerVectorInnerIterator::index () const inline
{
     return EvalIterator::index() - convert_index<StorageIndex>(XprIsRowMajor ? m_block.startCol() : m_block.startRow());
   }
operator bool()
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IteratorBased >::InnerVectorInnerIterator::operator bool () const inline
 { return EvalIterator::operator bool() && EvalIterator::index() < m_end; }
outer()
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> Index Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IteratorBased >::InnerVectorInnerIterator::outer () const inline
{
     return EvalIterator::outer() - (XprIsRowMajor ? m_block.startRow() : m_block.startCol());
   }
row()
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> Index Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IteratorBased >::InnerVectorInnerIterator::row () const inline
 { return EvalIterator::row() - m_block.startRow(); }
References row().
Member Data Documentation
m_block
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> const XprType& Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IteratorBased >::InnerVectorInnerIterator::m_block private
m_end
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> Index Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IteratorBased >::InnerVectorInnerIterator::m_end private
The documentation for this class was generated from the following file:
SparseBlock.h