MercuryDPM: MyUnitCircle Class Reference
MyUnitCircle Class Reference
Public Member Functions
MyUnitCircle ()
virtual ~MyUnitCircle ()
Destructor: Empty.
void position (const Vector< double > &xi, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &xi, Vector< double > &r) const
MyUnitCircle ()
virtual ~MyUnitCircle ()
Destructor: Empty.
void position (const Vector< double > &xi, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &xi, Vector< double > &r) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual unsigned ngeom_data () const
virtual Data * geom_data_pt (const unsigned &j)
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Additional Inherited Members
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Unit circle as GeomObject
\[ x = \cos(\xi) \]
\[ y = \sin(\xi) \]
Constructor & Destructor Documentation
MyUnitCircle() [1/2]
MyUnitCircle::MyUnitCircle () inline
Constructor: The circle is a 1D object (i.e. it's parametrised by one intrinsic coordinate) in 2D space. Pass these arguments to the constructor of the GeomObject base class.
 : GeomObject(1,2) {}
~MyUnitCircle() [1/2]
virtual MyUnitCircle::~MyUnitCircle () inline virtual
Destructor: Empty.
 {}
MyUnitCircle() [2/2]
MyUnitCircle::MyUnitCircle () inline
Constructor: The circle is a 1D object (i.e. it's parametrised by one intrinsic coordinate) in 2D space. Pass these arguments to the constructor of the GeomObject base class.
 : GeomObject(1,2) {}
~MyUnitCircle() [2/2]
virtual MyUnitCircle::~MyUnitCircle () inline virtual
Destructor: Empty.
 {}
Member Function Documentation
position() [1/4]
void MyUnitCircle::position (const unsigned & t, const Vector< double > & xi, Vector< double > & r) const inline virtual
Parametrised position on object: r(xi). Evaluated at previous time level. t=0: current time; t>0: previous time level. Circle is fixed – simply call the steady version.
Reimplemented from oomph::GeomObject.
   {
    // Call steady version
    position(xi,r);
   } // end of position(...)
References UniformPSDSelfTest::r.
position() [2/4]
void MyUnitCircle::position (const unsigned & t, const Vector< double > & xi, Vector< double > & r) const inline virtual
Parametrised position on object: r(xi). Evaluated at previous time level. t=0: current time; t>0: previous time level. Circle is fixed – simply call the steady version.
Reimplemented from oomph::GeomObject.
   {
    // Call steady version
    position(xi,r);
   } // end of position(...)
References UniformPSDSelfTest::r.
position() [3/4]
void MyUnitCircle::position (const Vector< double > & xi, Vector< double > & r) const inline virtual
Current position vector to material point at Lagrangian coordinate xi
Implements oomph::GeomObject.
   {
    // Position vector
    r[0] = cos(xi[0]);
    r[1] = sin(xi[0]);
   } // end of position(...)
References cos(), UniformPSDSelfTest::r, and sin().
position() [4/4]
void MyUnitCircle::position (const Vector< double > & xi, Vector< double > & r) const inline virtual
Current position vector to material point at Lagrangian coordinate xi
Implements oomph::GeomObject.
   {
    // Position vector
    r[0] = cos(xi[0]);
    r[1] = sin(xi[0]);
   } // end of position(...)
References cos(), UniformPSDSelfTest::r, and sin().
The documentation for this class was generated from the following file:
optimisation/disable_ALE/unsteady_heat/two_d_unsteady_heat_adapt.cc