MercuryDPM: ArcTanSolnForPoisson Namespace Reference
ArcTanSolnForPoisson Namespace Reference
Namespace for exact solution for Poisson equation with "sharp step".
Functions
void get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void get_source (const Vector< double > &x, double &source)
Source function required to make the solution above an exact solution.
void get_exact_gradient (const Vector< double > &x, Vector< double > &dudx)
Exact gradient as a Vector.
Variables
double Alpha =100.0
Parameter for steepness of "step".
Detailed Description
Namespace for exact solution for Poisson equation with "sharp step".
Function Documentation
get_exact_gradient()
void ArcTanSolnForPoisson::get_exact_gradient (const Vector< double > & x, Vector< double > & dudx)
Exact gradient as a Vector.
  {
   dudx[0] = Alpha/(1.0+(Alpha*(x[0]-0.5))*(Alpha*(x[0]-0.5)));
  }
References TanhSolnForAdvectionDiffusion::Alpha, and plotDoE::x.
get_exact_u()
void ArcTanSolnForPoisson::get_exact_u (const Vector< double > & x, Vector< double > & u)
Exact solution as a Vector.
  {
   u[0] = atan(Alpha*(x[0]-0.5));
  }
References Alpha, Eigen::bfloat16_impl::atan(), and plotDoE::x.
Referenced by RefineableOneDPoissonProblem< ELEMENT >::actions_before_newton_solve(), PRefineableOneDPoissonProblem< ELEMENT >::actions_before_newton_solve(), RefineableOneDPoissonProblem< ELEMENT >::doc_solution(), and PRefineableOneDPoissonProblem< ELEMENT >::doc_solution().
get_source()
void ArcTanSolnForPoisson::get_source (const Vector< double > & x, double & source)
Source function required to make the solution above an exact solution.
  {
   // Cache tan( atan(Alpha*(x[0]-0.5)) ) term
   double tan_term = tan( atan(Alpha*(x[0]-0.5)) );
   // Compute source function
   source = -(2.0 * Alpha*Alpha * tan_term) /
    ( (1.0 + tan_term*tan_term)*(1.0 + tan_term*tan_term) );
  }
References Alpha, Eigen::bfloat16_impl::atan(), TestProblem::source(), Eigen::bfloat16_impl::tan(), and plotDoE::x.
Referenced by main().
Variable Documentation
Alpha
double ArcTanSolnForPoisson::Alpha =100.0
Parameter for steepness of "step".
Referenced by get_exact_u(), get_source(), and main().