MercuryDPM: CGFields::DisplacementField Class Reference
CGFields::DisplacementField Class Reference
Computed the displacement fields.
#include <DisplacementField.h>
Public Member Functions
DisplacementField ()
DisplacementField (const DisplacementField &other)=default
~DisplacementField ()=default
void write (std::ostream &os) const
Writes class content into an output stream, typically a stat file.
void output (std::ostream &os) const
Writes human-readable class content into an output stream, typically a stat file.
void setZero ()
Sets all fields to zero.
DisplacementField getSquared () const
Returns the square of all field values (to calculate standard deviation).
DisplacementField & operator= (const DisplacementField &P)
Copies all field values.
DisplacementField & operator+= (const DisplacementField &P)
Adds the field values on the RHS to the LHS of the equation.
DisplacementField & operator-= (const DisplacementField &P)
Subtracts the field values on the RHS from the LHS of the equation.
DisplacementField & operator/= (Mdouble a)
Divides the field values on the LHS by the RHS of the equation.
DisplacementField operator* (Mdouble a) const
Multiplies the field values on the left of the '*' by the scalar value on the right of the '*' and returns the answer.
void addParticleStatistics (Mdouble phi, const DisplacementField &currentInteraction)
This function should be called from within a loop over all particles to compute all the fields that are defined as a sum over all particles (e.g. density, momentum).
void setFields (const BaseParticle &p)
void setCylindricalFields (const BaseParticle &p)
MatrixSymmetric3D getDisplacementMomentumFlux () const
Vec3D getDisplacementMomentum () const
void setFields (const BaseInteraction &c, IntegralType type)
void setCylindricalFields (const BaseInteraction &c, IntegralType type)
void addParticleDifferentialStatistics (Vec3D &dphi, const DisplacementField &currentInteraction)
void addInteractionStatistics (Mdouble psi, const DisplacementField &currentInteraction)
void addContactPointStatistics (Mdouble phi, const DisplacementField &currentInteraction)
Public Member Functions inherited from CGFields::BaseFields
void setCG (BaseCG *cg)
BaseCG * getCG ()
Static Public Member Functions
static void writeNames (std::ostream &os, unsigned countVariables)
static bool evaluateFixedParticles ()
static bool doInteractionStatistics ()
static bool isDifferentialField ()
Private Attributes
MatrixSymmetric3D displacementMomentumFlux_
Vec3D displacementMomentum_
Additional Inherited Members
Protected Attributes inherited from CGFields::BaseFields
BaseCG * cg_ = nullptr
Stores a pointer to the baseCG instance to get e.g. the handler and time information.
Detailed Description
Computed the displacement fields.
The displacement moment and the displacement moment flux are calculated from the previous position of the particle and the time since the last evaluation of the data files
Constructor & Destructor Documentation
DisplacementField() [1/2]
CGFields::DisplacementField::DisplacementField ()
     {
         setZero();
         logger(DEBUG, "DisplacementField::DisplacementField() finished");
     }
References DEBUG, logger, and setZero().
Referenced by getSquared().
DisplacementField() [2/2]
CGFields::DisplacementField::DisplacementField (const DisplacementField & other) default
~DisplacementField()
CGFields::DisplacementField::~DisplacementField () default
Member Function Documentation
addContactPointStatistics()
void CGFields::DisplacementField::addContactPointStatistics (Mdouble phi, const DisplacementField & currentInteraction) inline
         {}
addInteractionStatistics()
void CGFields::DisplacementField::addInteractionStatistics (Mdouble psi, const DisplacementField & currentInteraction) inline
         {}
addParticleDifferentialStatistics()
void CGFields::DisplacementField::addParticleDifferentialStatistics (Vec3D & dphi, const DisplacementField & currentInteraction) inline
         {}
addParticleStatistics()
void CGFields::DisplacementField::addParticleStatistics (Mdouble phi, const DisplacementField & currentInteraction)
This function should be called from within a loop over all particles to compute all the fields that are defined as a sum over all particles (e.g. density, momentum).
     {
         displacementMomentum_ += currentInteraction.getDisplacementMomentum() * phi;
         displacementMomentumFlux_ += currentInteraction.getDisplacementMomentumFlux() * phi;
     }
References displacementMomentum_, displacementMomentumFlux_, getDisplacementMomentum(), and getDisplacementMomentumFlux().
doInteractionStatistics()
static bool CGFields::DisplacementField::doInteractionStatistics () inline static
         {
             return false;
         }
evaluateFixedParticles()
static bool CGFields::DisplacementField::evaluateFixedParticles () inline static
         {
             return false;
         }
getDisplacementMomentum()
Vec3D CGFields::DisplacementField::getDisplacementMomentum () const inline
 { return displacementMomentum_; }
References displacementMomentum_.
Referenced by addParticleStatistics().
getDisplacementMomentumFlux()
MatrixSymmetric3D CGFields::DisplacementField::getDisplacementMomentumFlux () const inline
 { return displacementMomentumFlux_; }
References displacementMomentumFlux_.
Referenced by addParticleStatistics().
getSquared()
DisplacementField CGFields::DisplacementField::getSquared () const
Returns the square of all field values (to calculate standard deviation).
     {
         DisplacementField DisplacementField;
         DisplacementField.displacementMomentum_ = Vec3D::square(displacementMomentum_);
         DisplacementField.displacementMomentumFlux_ = MatrixSymmetric3D::square(displacementMomentumFlux_);
         return DisplacementField;
     }
References DisplacementField(), displacementMomentum_, displacementMomentumFlux_, MatrixSymmetric3D::square(), and Vec3D::square().
isDifferentialField()
static bool CGFields::DisplacementField::isDifferentialField () inline static
A bool that determines if the derivative of the CG function has to be computed
         {
             return false;
         }
operator*()
DisplacementField CGFields::DisplacementField::operator* (Mdouble a) const
Multiplies the field values on the left of the '*' by the scalar value on the right of the '*' and returns the answer.
     {
         DisplacementField p;
         p.displacementMomentum_ = displacementMomentum_ * a;
         p.displacementMomentumFlux_ = displacementMomentumFlux_ * a;
         return p;
     }
References a, displacementMomentum_, displacementMomentumFlux_, and p.
operator+=()
DisplacementField & CGFields::DisplacementField::operator+= (const DisplacementField & P)
Adds the field values on the RHS to the LHS of the equation.
     {
         displacementMomentum_ += P.displacementMomentum_;
         displacementMomentumFlux_ += P.displacementMomentumFlux_;
         return *this;
     }
References displacementMomentum_, displacementMomentumFlux_, and Global_Physical_Variables::P.
operator-=()
DisplacementField & CGFields::DisplacementField::operator-= (const DisplacementField & P)
Subtracts the field values on the RHS from the LHS of the equation.
     {
         displacementMomentum_ -= P.displacementMomentum_;
         displacementMomentumFlux_ -= P.displacementMomentumFlux_;
         return *this;
     }
References displacementMomentum_, displacementMomentumFlux_, and Global_Physical_Variables::P.
operator/=()
DisplacementField & CGFields::DisplacementField::operator/= (Mdouble a)
Divides the field values on the LHS by the RHS of the equation.
     {
         displacementMomentum_ /= a;
         displacementMomentumFlux_ /= a;
         return *this;
     }
References a, displacementMomentum_, and displacementMomentumFlux_.
operator=()
DisplacementField & CGFields::DisplacementField::operator= (const DisplacementField & P) default
Copies all field values.
output()
void CGFields::DisplacementField::output (std::ostream & os) const
Writes human-readable class content into an output stream, typically a stat file.
     {
         os << "displacementMomentum " << displacementMomentum_ << " ";
         os << "displacementMomentumFlux " << displacementMomentumFlux_ << " ";
     }
References displacementMomentum_, and displacementMomentumFlux_.
setCylindricalFields() [1/2]
void CGFields::DisplacementField::setCylindricalFields (const BaseInteraction & c, IntegralType type) inline
         {}
setCylindricalFields() [2/2]
void CGFields::DisplacementField::setCylindricalFields (const BaseParticle & p)
     {
         setFields(p);
     }
References p, and setFields().
setFields() [1/2]
void CGFields::DisplacementField::setFields (const BaseInteraction & c, IntegralType type) inline
         {}
setFields() [2/2]
void CGFields::DisplacementField::setFields (const BaseParticle & p)
     {
         CGHandler* cgHandler = getCG()->getHandler();
         DPMBase* dpmBase = getCG()->getHandler()->getDPMBase();
         Vec3D displacement = p.getDisplacement2(dpmBase->getXMin(), dpmBase->getXMax(),
                                                 dpmBase->getYMin(), dpmBase->getYMax(),
                                                 dpmBase->getZMin(), dpmBase->getZMax(),
                                                 dpmBase->getTime() - cgHandler->getPreviousEvaluationTime());
         displacementMomentum_ = displacement * p.getMass();
         displacementMomentumFlux_ = MatrixSymmetric3D::selfDyadic(displacement) * p.getMass();
     }
References displacementMomentum_, displacementMomentumFlux_, CGFields::BaseFields::getCG(), BaseHandler< T >::getDPMBase(), BaseCG::getHandler(), CGHandler::getPreviousEvaluationTime(), DPMBase::getTime(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), DPMBase::getZMax(), DPMBase::getZMin(), p, and MatrixSymmetric3D::selfDyadic().
Referenced by setCylindricalFields().
setZero()
void CGFields::DisplacementField::setZero ()
Sets all fields to zero.
     {
         displacementMomentum_.setZero();
         displacementMomentumFlux_.setZero();
     }
References displacementMomentum_, displacementMomentumFlux_, MatrixSymmetric3D::setZero(), and Vec3D::setZero().
Referenced by DisplacementField().
write()
void CGFields::DisplacementField::write (std::ostream & os) const
Writes class content into an output stream, typically a stat file.
     {
         os << displacementMomentum_ << " "
            << displacementMomentumFlux_ << " ";
     }
References displacementMomentum_, and displacementMomentumFlux_.
writeNames()
void CGFields::DisplacementField::writeNames (std::ostream & os, unsigned countVariables) static
     {
         os << countVariables + 1 << "-" << countVariables + 3 << ":displacementMomentum " //orientation
            << countVariables + 4 << "-" << countVariables + 9 << ":displacementMomentumFlux ";
     }
Member Data Documentation
displacementMomentum_
Vec3D CGFields::DisplacementField::displacementMomentum_ private
Referenced by addParticleStatistics(), getDisplacementMomentum(), getSquared(), operator*(), operator+=(), operator-=(), operator/=(), output(), setFields(), setZero(), and write().
displacementMomentumFlux_
MatrixSymmetric3D CGFields::DisplacementField::displacementMomentumFlux_ private
Referenced by addParticleStatistics(), getDisplacementMomentumFlux(), getSquared(), operator*(), operator+=(), operator-=(), operator/=(), output(), setFields(), setZero(), and write().
The documentation for this class was generated from the following files:
DisplacementField.h
DisplacementField.cc