MercuryDPM: oomph::OomphCommunicator Class Reference
oomph::OomphCommunicator Class Reference
#include <communicator.h>
Public Member Functions
OomphCommunicator ()
Serial constructor.
OomphCommunicator (const OomphCommunicator &communicator)
Copy constructor.
OomphCommunicator (const OomphCommunicator *communicator_pt)
Pointer (copy) constructor.
~OomphCommunicator ()
void operator= (const OomphCommunicator &communicator)
assignment operator
int nproc () const
number of processors
int my_rank () const
my rank
bool operator== (const OomphCommunicator &other_comm) const
bool operator!= (const OomphCommunicator &other_comm) const
Detailed Description
An oomph-lib wrapper to the MPI_Comm communicator object. Just contains an MPI_Comm object (which is a pointer) and wrappers to the MPI_... methods.
Constructor & Destructor Documentation
OomphCommunicator() [1/3]
oomph::OomphCommunicator::OomphCommunicator () inline
Serial constructor.
       : Owns_mpi_comm(false), Serial_communicator(true)
 #endif
     {
     }
OomphCommunicator() [2/3]
oomph::OomphCommunicator::OomphCommunicator (const OomphCommunicator & communicator) inline
Copy constructor.
       : Owns_mpi_comm(false)
     {
       if (communicator.serial_communicator())
       {
         Serial_communicator = true;
       }
       else
       {
         Comm = communicator.mpi_comm();
         Serial_communicator = false;
       }
     }
 #else
     {
     }
OomphCommunicator() [3/3]
oomph::OomphCommunicator::OomphCommunicator (const OomphCommunicator * communicator_pt) inline
Pointer (copy) constructor.
       : Owns_mpi_comm(false)
     {
       if (communicator_pt->serial_communicator())
       {
         Serial_communicator = true;
       }
       else
       {
         Comm = communicator_pt->mpi_comm();
         Serial_communicator = false;
       }
     }
 #else
     {
     }
~OomphCommunicator()
oomph::OomphCommunicator::~OomphCommunicator () inline
Destructor. If MPI and this preconditioner owns the MPI_Comm object then MPI_Comm_free is called, otherwise nothing happens as the destruction of the underlying MPI_Comm object is the responsibility of another communicator.
     {
 #ifdef OOMPH_HAS_MPI
       if (Owns_mpi_comm)
       {
         MPI_Comm_free(&Comm);
       }
 #endif
     }
Member Function Documentation
my_rank()
int oomph::OomphCommunicator::my_rank () const inline
my rank
     {
 #ifdef OOMPH_HAS_MPI
       if (Serial_communicator)
       {
         return 0;
       }
       else
       {
         int My_rank = 0;
         MPI_Comm_rank(Comm, &My_rank);
         return My_rank;
       }
 #else
       return 0;
 #endif
     }
Referenced by oomph::NavierStokesSchurComplementPreconditioner::assemble_inv_press_and_veloc_mass_matrix_diagonal(), oomph::PressureBasedSolidLSCPreconditioner::assemble_mass_matrix_diagonal(), oomph::Multi_domain_functions::aux_setup_multi_domain_interaction(), oomph::LinearAlgebraDistribution::build(), oomph::CRDoubleMatrixHelpers::concatenate(), oomph::DoubleVectorHelpers::concatenate(), oomph::LinearAlgebraDistributionHelpers::concatenate(), oomph::Z2ErrorEstimator::doc_flux(), oomph::DoubleVectorHaloScheme::DoubleVectorHaloScheme(), oomph::Problem::dump(), oomph::MumpsSolver::factorise(), oomph::LinearAlgebraDistribution::first_row(), oomph::Z2ErrorEstimator::get_element_errors(), oomph::LineVisualiser::get_output_data(), oomph::Node::hanging_pt(), oomph::BlockPreconditioner< MATRIX >::internal_dof_number(), main(), oomph::LinearAlgebraDistribution::nrow_local(), parallel_test(), oomph::PitchForkHandler::PitchForkHandler(), oomph::Problem::read(), oomph::DoubleMultiVector::redistribute(), oomph::DoubleVector::redistribute(), oomph::CRDoubleMatrix::redistribute(), oomph::BlockPitchForkLinearSolver::resolve(), oomph::MemoryUsage::run_continous_top(), oomph::LineVisualiser::setup(), oomph::BlockPitchForkLinearSolver::solve(), oomph::MumpsSolver::solve(), oomph::PitchForkHandler::solve_full_system(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_lists(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_maps(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_two_arrays(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_two_vectors(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_vectors_of_pairs(), oomph::DoubleVectorHelpers::split(), oomph::MemoryUsage::stop_continous_top(), and oomph::LineVisualiser::update_plot_points_coordinates().
nproc()
int oomph::OomphCommunicator::nproc () const inline
number of processors
     {
 #ifdef OOMPH_HAS_MPI
       if (Serial_communicator)
       {
         return 1;
       }
       else
       {
         int n_proc = 1;
         MPI_Comm_size(Comm, &n_proc);
         return n_proc;
       }
 #else
       return 1;
 #endif
     }
Referenced by oomph::NavierStokesSchurComplementPreconditioner::assemble_inv_press_and_veloc_mass_matrix_diagonal(), oomph::PressureBasedSolidLSCPreconditioner::assemble_mass_matrix_diagonal(), oomph::Problem::assign_eqn_numbers(), oomph::Multi_domain_functions::aux_setup_multi_domain_interaction(), oomph::LinearAlgebraDistribution::build(), oomph::Problem::calculate_continuation_derivatives_fd_helper(), oomph::Problem::calculate_continuation_derivatives_helper(), oomph::CRDoubleMatrixHelpers::concatenate(), oomph::DoubleVectorHelpers::concatenate(), oomph::LinearAlgebraDistributionHelpers::concatenate(), oomph::DoubleVectorHelpers::concatenate_without_communication(), oomph::CRDoubleMatrixHelpers::concatenate_without_communication(), oomph::HypreHelpers::create_HYPRE_Matrix(), oomph::DoubleVectorHaloScheme::DoubleVectorHaloScheme(), oomph::SuperLUSolver::factorise(), oomph::MumpsSolver::factorise(), oomph::LinearAlgebraDistribution::first_row(), oomph::CRDoubleMatrixHelpers::gershgorin_eigenvalue_estimate(), oomph::Multi_domain_functions::get_dim_helper(), oomph::Problem::get_eigenproblem_matrices(), oomph::Z2ErrorEstimator::get_element_errors(), oomph::Problem::get_jacobian(), oomph::LineVisualiser::get_output_data(), oomph::Problem::get_residuals(), oomph::CRDoubleMatrix::global_matrix(), oomph::HypreInterface::hypre_matrix_setup(), oomph::CRDoubleMatrixHelpers::inf_norm(), oomph::BlockPreconditioner< MATRIX >::internal_get_block(), oomph::MGSolver< DIM >::interpolation_matrix_set(), oomph::HelmholtzMGPreconditioner< DIM >::interpolation_matrix_set(), main(), oomph::Problem::newton_solve_continuation(), oomph::LinearAlgebraDistribution::nrow_local(), oomph::LinearAlgebraDistribution::operator==(), oomph::DoubleMultiVector::output(), oomph::DoubleVector::output(), parallel_test(), oomph::PitchForkHandler::PitchForkHandler(), oomph::DoubleMultiVector::redistribute(), oomph::DoubleVector::redistribute(), oomph::CRDoubleMatrix::redistribute(), oomph::MGSolver< DIM >::self_test(), oomph::LineVisualiser::setup(), oomph::MGSolver< DIM >::setup_mg_structures(), oomph::HelmholtzMGPreconditioner< DIM >::setup_mg_structures(), oomph::MGSolver< DIM >::setup_smoothers(), oomph::HelmholtzMGPreconditioner< DIM >::setup_smoothers(), oomph::DenseLU::solve(), oomph::HSL_MA42::solve(), oomph::SuperLUSolver::solve(), oomph::MumpsSolver::solve(), oomph::SuperLUSolver::solve_transpose(), oomph::DoubleVectorHelpers::split(), oomph::DoubleVectorHelpers::split_without_communication(), and oomph::LineVisualiser::update_plot_points_coordinates().
operator!=()
bool oomph::OomphCommunicator::operator!= (const OomphCommunicator & other_comm) const inline
!= operator returns !(==operator) (see ==operator for more details)
     {
       return !(*this == other_comm);
     }
operator=()
void oomph::OomphCommunicator::operator= (const OomphCommunicator & communicator) inline
assignment operator
     {
 #ifdef OOMPH_HAS_MPI
       if (Owns_mpi_comm)
       {
         MPI_Comm_free(&Comm);
       }
       Owns_mpi_comm = false;
       if (communicator.serial_communicator())
       {
         Serial_communicator = true;
       }
       else
       {
         Serial_communicator = false;
         Comm = communicator.mpi_comm();
       }
 #endif
     }
operator==()
bool oomph::OomphCommunicator::operator== (const OomphCommunicator & other_comm) const inline
== operator - only returns true if communicators are MPI_IDENT, i.e. if both group and context are the same
     {
 #ifdef OOMPH_HAS_MPI
       if (Serial_communicator != other_comm.serial_communicator())
       {
         return false;
       }
       else if (Serial_communicator)
       {
         return true;
       }
       else
       {
         int flag;
         MPI_Comm_compare(Comm, other_comm.mpi_comm(), &flag);
         if (flag == MPI_IDENT)
         {
           return true;
         }
         return false;
       }
 #else
       return true;
 #endif
     }
The documentation for this class was generated from the following file:
communicator.h