MercuryDPM: HouseholderQR_householderQ.cpp File Reference
HouseholderQR_householderQ.cpp File Reference
Functions
MatrixXf A (MatrixXf::Random(5, 3))
MatrixXf thinQ (MatrixXf::Identity(5, 3))
A setRandom ()
HouseholderQR< MatrixXf > qr (A)
Variables
MatrixXf Q = qr.householderQ()
thinQ = qr.householderQ() * thinQ
Function Documentation
A()
MatrixXf A (MatrixXf::Random(5, 3))
qr()
HouseholderQR<MatrixXf> qr (A)
Referenced by bench(), EIGEN_DECLARE_TEST(), householder(), Eigen::internal::idrs(), Eigen::internal::idrstabl(), Eigen::SplineFitting< SplineType >::Interpolate(), Eigen::internal::lmpar2(), main(), and svd_min_norm().
setRandom()
m2 setRandom ()
Referenced by Eigen::PlainObjectBase< Derived >::setRandom().
thinQ()
MatrixXf thinQ (MatrixXf::Identity(5, 3))
Variable Documentation
Q
Q = qr.householderQ()
Referenced by ChangingTOIParticle::actionsAfterTimeStep(), check_generateRandomUnitaryMatrix(), WearableNurbsWall::computeWear(), WearableTriangleMeshWall::computeWear(), WearableTriangulatedWall::computeWear(), BaseWall::getAxis(), hessenberg(), nlerp(), randMatrixSpecialUnitary(), randMatrixUnitary(), ClumpParticle::rotateTensorOfInertia(), Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, false >::run(), Global_Parameters::set_parameters(), Global_Physical_Variables::set_params(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), slerp_legacy(), slerp_legacy_nlerp(), test_sparseqr_scalar(), Eigen::umfpack_get_numeric(), and Global_Physical_Variables::update_dependent_parameters().
thinQ
thinQ = qr.householderQ() * thinQ