MercuryDPM: VChute Class Reference
VChute Class Reference
#include <VChute.h>
Public Member Functions
VChute ()
VChute (const VChute &other)
VChute (Mdouble length, Mdouble width, Mdouble alpha)
~VChute () override
void set (Mdouble length, Mdouble width, Mdouble alpha)
VChute * copy () const override
Pure virtual function that can be overwritten in inherited classes in order to copy a BaseWall.
bool getDistanceAndNormal (const BaseParticle &p, Mdouble &distance, Vec3D &normal_return) const override
Pure virtual function that computes the distance of a BaseParticle to this wall and returns the normal of this wall if there is a collision.
BaseInteraction * getInteractionWith (BaseParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler) override
Returns the interaction between this wall and a given particle, nullptr if there is no interaction.
void read (std::istream &is) override
void write (std::ostream &os) const override
std::string getName () const override
Public Member Functions inherited from BaseWall
BaseWall ()
Default constructor.
BaseWall (const BaseWall &w)
Copy constructor.
~BaseWall () override
Default destructor.
virtual bool getDistanceNormalOverlap (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual bool getDistanceNormalOverlapSuperquadric (const SuperQuadricParticle &p, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual Vec3D getFurthestPointSuperQuadric (const Vec3D &normalBodyFixed, const Vec3D &axes, Mdouble eps1, Mdouble eps2) const
virtual void setHandler (WallHandler *handler)
A function which sets the WallHandler for this BaseWall.
WallHandler * getHandler () const
A function which returns the WallHandler that handles this BaseWall.
void setIndSpecies (unsigned int indSpecies) override
Define the species of this wall using the index of the species in the SpeciesHandler in this DPMBase.
void setSpecies (const ParticleSpecies *species)
Defines the species of the current wall.
bool isFixed () const override
void setForceControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity={0, 0, 0})
Slowly adjusts the force on a wall towards a specified goal, by adjusting (prescribing) the velocity of the wall.
virtual bool isLocal (Vec3D &min, Vec3D &max) const
bool getLinePlaneIntersect (Vec3D &intersect, const Vec3D &p0, const Vec3D &p1, const Vec3D &n, const Vec3D &p)
bool isInsideWallVTK (const Vec3D &point, const Vec3D &normal, const Vec3D &position) const
void projectOntoWallVTK (Vec3D &point0, const Vec3D &point1, const Vec3D &normal, const Vec3D &position) const
void intersectVTK (std::vector< Vec3D > &points, Vec3D normal, Vec3D position) const
virtual BaseInteraction * getInteractionWithSuperQuad (SuperQuadricParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler)
virtual void writeVTK (VTKContainer &vtk) const
void getVTK (std::vector< Vec3D > &points, std::vector< std::vector< double >> &triangleStrips)
const Vec3D getAxis () const
virtual void actionsOnRestart ()
No implementation but can be overidden in its derived classes.
virtual void actionsAfterParticleGhostUpdate ()
No implementation but can be overidden in its derived classes.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
virtual void handleParticleRemoval (unsigned int id)
Handles the addition of particles to the particleHandler.
virtual void checkInteractions (InteractionHandler *interactionHandler, unsigned int timeStamp)
Check if all interactions are valid.
bool getVTKVisibility () const
void setVTKVisibility (bool vtkVisibility)
void addRenderedWall (BaseWall *w)
BaseWall * getRenderedWall (size_t i) const
std::vector< BaseWall * > getRenderedWalls () const
void removeRenderedWalls ()
void renderWall (VTKContainer &vtk)
void addParticlesAtWall (unsigned numElements=50)
void setVelocityControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity)
virtual void writeWallDetailsVTK (VTKData &data) const
virtual void computeWear ()
Public Member Functions inherited from BaseInteractable
BaseInteractable ()
Default BaseInteractable constructor.
BaseInteractable (const BaseInteractable &p)
Copy constructor.
~BaseInteractable () override
Destructor, it simply destructs the BaseInteractable and all the objects it contains.
unsigned int getIndSpecies () const
Returns the index of the species associated with the interactable object.
const ParticleSpecies * getSpecies () const
Returns a pointer to the species of this BaseInteractable.
void setSpecies (const ParticleSpecies *species)
Sets the species of this BaseInteractable.
const Vec3D & getForce () const
Returns the force on this BaseInteractable.
const Vec3D & getTorque () const
Returns the torque on this BaseInteractable.
void setForce (const Vec3D &force)
Sets the force on this BaseInteractable.
void setTorque (const Vec3D &torque)
Sets the torque on this BaseInteractable.
void addForce (const Vec3D &addForce)
Adds an amount to the force on this BaseInteractable.
void addTorque (const Vec3D &addTorque)
Adds an amount to the torque on this BaseInteractable.
virtual void resetForceTorque (int numberOfOMPthreads)
void sumForceTorqueOMP ()
const Vec3D & getPosition () const
Returns the position of this BaseInteractable.
const Quaternion & getOrientation () const
Returns the orientation of this BaseInteractable.
virtual void setPosition (const Vec3D &position)
Sets the position of this BaseInteractable.
void setOrientationViaNormal (Vec3D normal)
Sets the orientation of this BaseInteractable by defining the vector that results from the rotation of the (1,0,0) vector.
void setOrientationViaEuler (Vec3D eulerAngle)
Sets the orientation of this BaseInteractable by defining the euler angles.
virtual void setOrientation (const Quaternion &orientation)
Sets the orientation of this BaseInteractable.
virtual void move (const Vec3D &move)
Moves this BaseInteractable by adding an amount to the position.
virtual void rotate (const Vec3D &angularVelocityDt)
Rotates this BaseInteractable.
const std::vector< BaseInteraction * > & getInteractions () const
Returns a list of interactions which belong to this interactable.
void addInteraction (BaseInteraction *I)
Adds an interaction to this BaseInteractable.
bool removeInteraction (BaseInteraction *I)
Removes an interaction from this BaseInteractable.
void copyInteractionsForPeriodicParticles (const BaseInteractable &p)
Copies interactions to this BaseInteractable whenever a periodic copy made.
void setVelocity (const Vec3D &velocity)
set the velocity of the BaseInteractable.
void setAngularVelocity (const Vec3D &angularVelocity)
set the angular velocity of the BaseInteractble.
void addVelocity (const Vec3D &velocity)
adds an increment to the velocity.
void addAngularVelocity (const Vec3D &angularVelocity)
add an increment to the angular velocity.
virtual const Vec3D & getVelocity () const
Returns the velocity of this interactable.
virtual const Vec3D & getAngularVelocity () const
Returns the angular velocity of this interactable.
void setPrescribedPosition (const std::function< Vec3D(double)> &prescribedPosition)
Allows the position of an infinite mass interactable to be prescribed.
void applyPrescribedPosition (double time)
Computes the position from the user defined prescribed position function.
void setPrescribedVelocity (const std::function< Vec3D(double)> &prescribedVelocity)
Allows the velocity of an infinite mass interactable to be prescribed.
void applyPrescribedVelocity (double time)
Computes the velocity from the user defined prescribed velocity function.
void setPrescribedOrientation (const std::function< Quaternion(double)> &prescribedOrientation)
Allows the orientation of the infinite mass interactbale to be prescribed.
void applyPrescribedOrientation (double time)
Computes the orientation from the user defined prescribed orientation function.
void setPrescribedAngularVelocity (const std::function< Vec3D(double)> &prescribedAngularVelocity)
Allows the angular velocity of the infinite mass interactable to be prescribed.
void applyPrescribedAngularVelocity (double time)
Computes the angular velocity from the user defined prescribed angular velocity.
virtual const Vec3D getVelocityAtContact (const Vec3D &contact) const
Returns the velocity at the contact point, use by many force laws.
void integrateBeforeForceComputation (double time, double timeStep)
This is part of integrate routine for objects with infinite mass.
void integrateAfterForceComputation (double time, double timeStep)
This is part of the integration routine for objects with infinite mass.
virtual Mdouble getInvMass () const
virtual Mdouble getCurvature (const Vec3D &labFixedCoordinates) const
virtual bool isFaceContact (const Vec3D &normal) const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
Mdouble l_
Mdouble w_
Mdouble alpha_
Additional Inherited Members
Static Public Member Functions inherited from BaseWall
static void addToVTK (const std::vector< Vec3D > &points, VTKContainer &vtk)
Takes the points provided and adds a triangle strip connecting these points to the vtk container.
Constructor & Destructor Documentation
VChute() [1/3]
VChute::VChute ()
 {
     l_ = 1.0;
     w_ = 1.0;
     alpha_ = 20.0 / 180.0 * constants::pi;
 }
References alpha_, l_, constants::pi, and w_.
Referenced by copy().
VChute() [2/3]
VChute::VChute (const VChute & other)
                                   : BaseWall(other)
 {
     l_ = other.l_;
     w_ = other.w_;
     alpha_ = other.alpha_;
 }
References alpha_, l_, and w_.
VChute() [3/3]
VChute::VChute (Mdouble length, Mdouble width, Mdouble alpha)
 {
     l_ = length;
     w_ = width;
     alpha_ = alpha;
 }
References alpha, alpha_, l_, and w_.
~VChute()
VChute::~VChute () override default
Member Function Documentation
copy()
VChute * VChute::copy () const override virtual
Pure virtual function that can be overwritten in inherited classes in order to copy a BaseWall.
Returns
A pointer to the new BaseWall.
Implements BaseWall.
 {
     return new VChute(*this);
 }
References VChute().
getDistanceAndNormal()
bool VChute::getDistanceAndNormal (const BaseParticle & P, Mdouble & distance, Vec3D & normal_return) const override virtual
Pure virtual function that computes the distance of a BaseParticle to this wall and returns the normal of this wall if there is a collision.
Beware, the distance and normal are output parameters, not return values!
Parameters
[in] P Reference to the BaseParticle we want to compute the distance to the BaseWall of.
[out] distance Distance of the BaseParticle to the BaseWall.
[out] normal_return The normal of the wall. Is only given if there is a collision.
Returns
A boolean which indicates if there is a collision between the BaseParticle and the wall.
Implements BaseWall.
 {
     /* define shortcuts */
     const Mdouble x0 = p.getPosition().X;
     const Mdouble y0 = p.getPosition().Y;
     const Mdouble z0 = p.getPosition().Z;
     const Mdouble ra = p.getWallInteractionRadius(this); // note, not getRadius()
     /* Has the particle flown off the ends of the chute? */
     if (x0 < -ra || x0 > l_ + ra)
         return false;
     /* Don't bother bounding in the y, z directions. The wall is linear, so
      * calculating collisions isn't that expensive anyway. */
     /*
     if (fabs(y0) > w_ + ra
      || z0 < -ra || z0 > tan(alpha_)*(w_ + ra) + ra ) {
         return false;
     }
     */
     /* Get the distance and normal. */
     // Newton is unnecessary, because linear problem.
     // The special case y0==0 is problematic because it means double-contact, but
     // let's just hope it doesn't come up. (TODO)
     Mdouble q;
     Mdouble distanceSquared;
     if (y0 > 0)
     {
         q = y0 * pow(cos(alpha_), 2) + z0 * tan(alpha_);
         distanceSquared = pow(
                 y0 * (pow(cos(alpha_), 2) - 1) + z0 * sin(alpha_) * cos(alpha_), 2)
                           + pow(
                 y0 * sin(alpha_) * cos(alpha_) + z0 * (pow(sin(alpha_), 2) - 1), 2);
     }
     else if (y0 < 0)
     {
         q = y0 * pow(cos(alpha_), 2) - z0 * tan(alpha_);
         distanceSquared = pow(
                 y0 * (pow(cos(alpha_), 2) - 1) - z0 * sin(alpha_) * cos(alpha_), 2)
                           + pow(
                 -y0 * sin(alpha_) * cos(alpha_) + z0 * (pow(sin(alpha_), 2) - 1), 2);
     }
     else
     {
         /* The case y=0 requires special handling... */
         /* In the past, this case simply triggered an error and died. */
         // return false;
         /* If the particle has y=0 then it is in contact with both sides of the
          * V-chute; both sides will exert a force on the particle
          * simultaneously. This is difficult to handle. I shall assume that the
          * resultant force is exactly upwards, as though the particle was in
          * contact with a flat plane (z=0).
          * TODO try to make this more realistic
          */
         logger(WARN, "y0 == 0, dangerous");
         q = 0;
         distanceSquared = pow(z0, 2);
     }
     //If distance is too large there is no contact
     if (distanceSquared >= pow(p.getWallInteractionRadius(this), 2))
     {
         return false;
     }
     Vec3D ContactPoint;
     distance = sqrt(distanceSquared);
     ContactPoint.X = x0;
     ContactPoint.Y = q;
     ContactPoint.Z = fabs(q) * tan(alpha_);
     normal_return = ContactPoint - p.getPosition();
     normal_return /= normal_return.getLength();
     return true;
 }
References alpha_, cos(), boost::multiprecision::fabs(), Vec3D::getLength(), l_, logger, p, Eigen::bfloat16_impl::pow(), Eigen::numext::q, sin(), sqrt(), Eigen::bfloat16_impl::tan(), WARN, Vec3D::X, Global::x0, Vec3D::Y, and Vec3D::Z.
Referenced by getInteractionWith().
getInteractionWith()
BaseInteraction * VChute::getInteractionWith (BaseParticle * p, unsigned timeStamp, InteractionHandler * interactionHandler) override virtual
Returns the interaction between this wall and a given particle, nullptr if there is no interaction.
Parameters
[in] p Pointer to the BaseParticle which we want to check the interaction for.
[in] timeStamp The time at which we want to look at the interaction.
[in] interactionHandler A pointer to the InteractionHandler in which the interaction can be found.
Returns
A pointer to the BaseInteraction that happened between this BaseWall and the BaseParticle at the timeStamp.
Todo:
Hacked please fix
Reimplemented from BaseWall.
 {
     Mdouble distance;
     Vec3D normal;
     if (getDistanceAndNormal(*p, distance, normal))
     {
         BaseInteraction* c = interactionHandler->getInteraction(p, this, timeStamp);
         c->setNormal(-normal);
         c->setDistance(distance);
         c->setOverlap(p->getRadius() - distance);
         c->setContactPoint(p->getPosition() - (p->getRadius() - 0.5 * c->getOverlap()) * c->getNormal());
         return c;
     }
     else
         return nullptr;
 }
References calibrate::c, getDistanceAndNormal(), InteractionHandler::getInteraction(), WallFunction::normal(), and p.
getName()
std::string VChute::getName () const override virtual
Returns
The string "VChute".
Implements BaseObject.
 {
     return "VChute";
 }
read()
void VChute::read (std::istream & is) override virtual
Parameters
[in,out] is The input stream from which the Coil is read.
Reimplemented from BaseWall.
 {
     BaseWall::read(is);
     std::string dummy;
     is >> dummy >> l_
        >> dummy >> w_
        >> dummy >> alpha_;
 }
References alpha_, l_, BaseWall::read(), oomph::Global_string_for_annotation::string(), and w_.
set()
void VChute::set (Mdouble length, Mdouble width, Mdouble alpha)
 {
     l_ = length;
     w_ = width;
     alpha_ = alpha;
 }
References alpha, alpha_, l_, and w_.
write()
void VChute::write (std::ostream & os) const override virtual
Parameters
[in,out] os The outpus stream to which the Coil is written.
Reimplemented from BaseWall.
 {
     BaseWall::write(os);
     os << " Length " << l_
        << " Width " << w_
        << " alpha " << alpha_;
 }
References alpha_, l_, w_, and BaseWall::write().
Member Data Documentation
alpha_
Mdouble VChute::alpha_ private
Referenced by getDistanceAndNormal(), read(), set(), VChute(), and write().
l_
Mdouble VChute::l_ private
Referenced by getDistanceAndNormal(), read(), set(), VChute(), and write().
w_
Mdouble VChute::w_ private
Referenced by read(), set(), VChute(), and write().
The documentation for this class was generated from the following files:
VChute.h
VChute.cc