MercuryDPM: Eigen::internal::generic_matrix_wrapper< MatrixType, false > Class Template Reference
Eigen::internal::generic_matrix_wrapper< MatrixType, false > Class Template Reference
#include <IterativeSolverBase.h>
Classes
struct ConstSelfAdjointViewReturnType
Public Types
enum { MatrixFree = false }
typedef Ref< const MatrixType > ActualMatrixType
Public Member Functions
generic_matrix_wrapper ()
template<typename InputType >
generic_matrix_wrapper (const InputType &mat)
const ActualMatrixType & matrix () const
template<typename MatrixDerived >
void grab (const EigenBase< MatrixDerived > &mat)
void grab (const Ref< const MatrixType > &mat)
Protected Attributes
MatrixType m_dummy
ActualMatrixType m_matrix
Member Typedef Documentation
ActualMatrixType
template<typename MatrixType > typedef Ref<const MatrixType> Eigen::internal::generic_matrix_wrapper< MatrixType, false >::ActualMatrixType
Member Enumeration Documentation
anonymous enum
template<typename MatrixType > anonymous enum
Enumerator
MatrixFree
 { MatrixFree = false };
Constructor & Destructor Documentation
generic_matrix_wrapper() [1/2]
template<typename MatrixType > Eigen::internal::generic_matrix_wrapper< MatrixType, false >::generic_matrix_wrapper () inline
 : m_dummy(0, 0), m_matrix(m_dummy) {}
generic_matrix_wrapper() [2/2]
template<typename MatrixType > template<typename InputType > Eigen::internal::generic_matrix_wrapper< MatrixType, false >::generic_matrix_wrapper (const InputType & mat) inline
 : m_matrix(mat) {}
Member Function Documentation
grab() [1/2]
template<typename MatrixType > template<typename MatrixDerived > void Eigen::internal::generic_matrix_wrapper< MatrixType, false >::grab (const EigenBase< MatrixDerived > & mat) inline
{
     internal::destroy_at(&m_matrix);
     internal::construct_at(&m_matrix, mat.derived());
   }
References Eigen::internal::construct_at(), Eigen::SparseMatrixBase< Derived >::derived(), and Eigen::internal::destroy_at().
grab() [2/2]
template<typename MatrixType > void Eigen::internal::generic_matrix_wrapper< MatrixType, false >::grab (const Ref< const MatrixType > & mat) inline
{
     if (&(mat.derived()) != &m_matrix) {
       internal::destroy_at(&m_matrix);
       internal::construct_at(&m_matrix, mat);
     }
   }
References Eigen::internal::construct_at(), Eigen::SparseMatrixBase< Derived >::derived(), and Eigen::internal::destroy_at().
matrix()
template<typename MatrixType > const ActualMatrixType& Eigen::internal::generic_matrix_wrapper< MatrixType, false >::matrix () const inline
 { return m_matrix; }
Member Data Documentation
m_dummy
template<typename MatrixType > MatrixType Eigen::internal::generic_matrix_wrapper< MatrixType, false >::m_dummy protected
m_matrix
template<typename MatrixType > ActualMatrixType Eigen::internal::generic_matrix_wrapper< MatrixType, false >::m_matrix protected
The documentation for this class was generated from the following file:
IterativeSolverBase.h