MercuryDPM: oomph::ConstitutiveLaw Class Reference
oomph::ConstitutiveLaw Class Reference abstract
#include <constitutive_laws.h>
Public Member Functions
ConstitutiveLaw ()
Empty constructor.
virtual ~ConstitutiveLaw ()
Empty virtual destructor.
virtual void calculate_second_piola_kirchhoff_stress (const DenseMatrix< double > &g, const DenseMatrix< double > &G, DenseMatrix< double > &sigma)=0
virtual void calculate_d_second_piola_kirchhoff_stress_dG (const DenseMatrix< double > &g, const DenseMatrix< double > &G, const DenseMatrix< double > &sigma, RankFourTensor< double > &d_sigma_dG, const bool &symmetrize_tensor=true)
virtual void calculate_second_piola_kirchhoff_stress (const DenseMatrix< double > &g, const DenseMatrix< double > &G, DenseMatrix< double > &sigma_dev, DenseMatrix< double > &G_contra, double &Gdet)
virtual void calculate_d_second_piola_kirchhoff_stress_dG (const DenseMatrix< double > &g, const DenseMatrix< double > &G, const DenseMatrix< double > &sigma, const double &detG, const double &interpolated_solid_p, RankFourTensor< double > &d_sigma_dG, DenseMatrix< double > &d_detG_dG, const bool &symmetrize_tensor=true)
virtual void calculate_second_piola_kirchhoff_stress (const DenseMatrix< double > &g, const DenseMatrix< double > &G, DenseMatrix< double > &sigma_dev, DenseMatrix< double > &Gcontra, double &gen_dil, double &inv_kappa)
virtual void calculate_d_second_piola_kirchhoff_stress_dG (const DenseMatrix< double > &g, const DenseMatrix< double > &G, const DenseMatrix< double > &sigma, const double &gen_dil, const double &inv_kappa, const double &interpolated_solid_p, RankFourTensor< double > &d_sigma_dG, DenseMatrix< double > &d_gen_dil_dG, const bool &symmetrize_tensor=true)
virtual bool requires_incompressibility_constraint ()=0
Protected Member Functions
bool is_matrix_square (const DenseMatrix< double > &M)
Test whether a matrix is square.
bool are_matrices_of_equal_dimensions (const DenseMatrix< double > &M1, const DenseMatrix< double > &M2)
Test whether two matrices are of equal dimensions.
void error_checking_in_input (const DenseMatrix< double > &g, const DenseMatrix< double > &G, DenseMatrix< double > &sigma)
double calculate_contravariant (const DenseMatrix< double > &Gcov, DenseMatrix< double > &Gcontra)
The function to calculate the contravariant tensor from a covariant one.
void calculate_d_contravariant_dG (const DenseMatrix< double > &Gcov, RankFourTensor< double > &dGcontra_dG, DenseMatrix< double > &d_detG_dG)
Detailed Description
///////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////// A class for constitutive laws for elements that solve the equations of solid mechanics based upon the principle of virtual displacements. In that formulation, the information required from a constitutive law is the (2nd Piola-Kirchhoff) stress tensor \(\sigma^{ij} \) as a function of the (Green) strain \(\gamma^{ij} \):
\[ \sigma^{ij} = \sigma^{ij}(\gamma_{ij}). \]
The Green strain is defined as
\[ \gamma_{ij} = \frac{1}{2} (G_{ij} - g_{ij}), \ \ \ \ \ \ \ \ \ \ \ (1) \]
where \(G_{ij} \) and \(g_{ij}\) are the metric tensors in the deformed and undeformed (stress-free) configurations, respectively. A specific ConstitutiveLaw needs to be implement the pure virtual function
ConstitutiveLaw::calculate_second_piola_kirchhoff_stress(...)
Equation (1) shows that the strain may be calculated from the undeformed and deformed metric tensors. Frequently, these tensors are also required in the constitutive law itself. To avoid unnecessary re-computation of these quantities, we pass the deformed and undeformed metric tensor to calculate_second_piola_kirchhoff_stress(...) rather than the strain tensor itself.
The functional form of the constitutive equation is different for compressible/incompressible/near-incompressible behaviour and we provide interfaces that are appropriate for all of these cases.
Compressible Behaviour:
If the material is compressible, the stress can be computed from the deformed and undeformed metric tensors,
\[ \sigma^{ij} = \sigma^{ij}(\gamma_{ij}) = \sigma^{ij}\bigg(\frac{1}{2} (G_{ij} - g_{ij})\bigg), \]
using the interface
// 2nd Piola Kirchhoff stress tensor
DenseMatrix<double> sigma(DIM,DIM);
// Metric tensor in the undeformed (stress-free) configuration
DenseMatrix<double> g(DIM,DIM);
// Metric tensor in the deformed  configuration
DenseMatrix<double> G(DIM,DIM);
// Compute stress from the two metric tensors:
calculate_second_piola_kirchhoff_stress(g,G,sigma);
Incompressible Behaviour:
If the material is incompressible, its deformation is constrained by the condition that
\[ \det G_{ij} - \det g_{ij}= 0 \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ (2) \]
which ensures that the volume of infinitesimal material elements remains constant during the deformation. This condition is typically enforced by a Lagrange multiplier which plays the role of a pressure. In such cases, the stress tensor has form
\[ \sigma^{ij} = -p G^{ij} + \overline{\sigma}^{ij}\big(\gamma_{kl}\big), \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ (3) \]
where only the deviatoric part of the stress tensor, \(\overline{\sigma}^{ij}, \) depends directly on the strain. The pressure \(p \) needs to be determined independently from (2). Given the deformed and undeformed metric tensors, the computation of the stress tensor \(\sigma^{ij} \) for an incompressible material therefore requires the computation of the following quantities:
The deviatoric stress \(\overline{\sigma}^{ij} \)
The contravariant deformed metric tensor \(G^{ij} \)
The determinant of the deformed metric tensors, \(\det G_{ij}, \) which is required in equation (2) whose solution determines the pressure.
These quantities can be obtained from the following interface
// Deviatoric part of the 2nd Piola Kirchhoff stress tensor
DenseMatrix<double> sigma_dev(DIM,DIM);
// Metric tensor in the undeformed (stress-free) configuration
DenseMatrix<double> g(DIM,DIM);
// Metric tensor in the deformed  configuration
DenseMatrix<double> G(DIM,DIM);
// Determinant of the deformed metric tensor
double Gdet;
// Contravariant deformed metric tensor
DenseMatrix<double> G_contra(DIM,DIM);
// Compute stress from the two metric tensors:
calculate_second_piola_kirchhoff_stress(g,G,sigma_dev,G_contra,Gdet);
Nearly Incompressible Behaviour:
If the material is nearly incompressible, it is advantageous to split the stress into its deviatoric and hydrostatic parts by writing the constitutive law in the form
\[ \sigma^{ij} = -p G^{ij} + \overline{\sigma}^{ij}\big(\gamma_{kl}\big), \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ (3) \]
where the deviatoric part of the stress tensor, \(\overline{\sigma}^{ij}, \) depends on the strain. This form of the constitutive law is identical to that of the incompressible case and it involves a pressure \(p \) which needs to be determined from an additional equation. In the incompressible case, this equation was given by the incompressibility constraint (2). Here, we need to augment the constitutive law (3) by a separate equation for the pressure. Generally this takes the form
\[ p = - \kappa \ d \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ (4) \]
where \(\kappa \) is the "bulk modulus", a material property that needs to be specified by the constitutive law. \(d \) is the (generalised) dilatation, i.e. the relative change in the volume of an infinitesimal material element (or some suitable generalised quantitiy that is related to it). As the material approaches incompressibility, \(\kappa \to \infty\), so that infinitely large pressures would be required to achieve any change in volume. To facilitate the implementation of (4) as the equation for the pressure, we re-write it in the form
\[ p \ \frac{1}{\kappa} + d\big(g_{ij},G_{ij}\big) = 0 \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ (5) \]
which only involves quantities that remain finite as we approach true incompressibility.
Given the deformed and undeformed metric tensors, the computation of the stress tensor \(\sigma^{ij} \) for a nearly incompressible material therefore requires the computation of the following quantities:
The deviatoric stress \(\overline{\sigma}^{ij} \)
The contravariant deformed metric tensor \(G^{ij} \)
The generalised dilatation \(d \)
The inverse of the bulk modulus \(\kappa \)
These quantities can be obtained from the following interface
// Deviatoric part of the 2nd Piola Kirchhoff stress tensor
DenseMatrix<double> sigma_dev(DIM,DIM);
// Metric tensor in the undeformed (stress-free) configuration
DenseMatrix<double> g(DIM,DIM);
// Metric tensor in the deformed  configuration
DenseMatrix<double> G(DIM,DIM);
// Contravariant deformed metric tensor
DenseMatrix<double> G_contra(DIM,DIM);
// Inverse of the bulk modulus
double inv_kappa;
// Generalised dilatation
double gen_dil;
// Compute stress from the two metric tensors:
calculate_second_piola_kirchhoff_stress(g,G,sigma_dev,G_contra,inv_kappa,gen_dil);
Constructor & Destructor Documentation
ConstitutiveLaw()
oomph::ConstitutiveLaw::ConstitutiveLaw () inline
Empty constructor.
 {}
~ConstitutiveLaw()
virtual oomph::ConstitutiveLaw::~ConstitutiveLaw () inline virtual
Empty virtual destructor.
 {}
Member Function Documentation
are_matrices_of_equal_dimensions()
bool oomph::ConstitutiveLaw::are_matrices_of_equal_dimensions (const DenseMatrix< double > & M1, const DenseMatrix< double > & M2) protected
Test whether two matrices are of equal dimensions.
This function is used to check whether matrices are of equal dimension.
   {
     // If the numbers of rows and columns are not the same, then the
     // matrices are not of equal dimension
     if ((M1.nrow() != M2.nrow()) || (M1.ncol() != M2.ncol()))
     {
       return false;
     }
     else
     {
       return true;
     }
   }
References M1, and M2().
Referenced by calculate_contravariant(), calculate_d_second_piola_kirchhoff_stress_dG(), and error_checking_in_input().
calculate_contravariant()
double oomph::ConstitutiveLaw::calculate_contravariant (const DenseMatrix< double > & Gcov, DenseMatrix< double > & Gcontra) protected
The function to calculate the contravariant tensor from a covariant one.
Calculate a contravariant tensor from a covariant tensor, and return the determinant of the covariant tensor.
Three dimensions
   {
     // Initial error checking
 #ifdef PARANOID
     // Test that the matrices are of the same dimension
     if (!are_matrices_of_equal_dimensions(Gdown, Gup))
     {
       throw OomphLibError("Matrices passed to calculate_contravariant() are "
                           "not of equal dimension",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Find the dimension of the matrix
     unsigned dim = Gdown.ncol();
     // If it's not square, I don't know what to do (yet)
 #ifdef PARANOID
     if (!is_matrix_square(Gdown))
     {
       std::string error_message =
         "Matrix passed to calculate_contravariant() is not square\n";
       error_message += "non-square matrix inversion not implemented yet!\n";
       throw OomphLibError(
         error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Define the determinant of the matrix
     double det = 0.0;
     // Now the inversion depends upon the dimension of the matrix
     switch (dim)
     {
         // Zero dimensions
       case 0:
         throw OomphLibError("Zero dimensional matrix",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
         break;
         // One dimension
       case 1:
         // The determinant is just the value of the only entry
         det = Gdown(0, 0);
         // The inverse is just the inverse of the value
         Gup(0, 0) = 1.0 / Gdown(0, 0);
         break;
         // Two dimensions
       case 2:
         // Calculate the determinant
         det = Gdown(0, 0) * Gdown(1, 1) - Gdown(0, 1) * Gdown(1, 0);
         // Calculate entries of the contravariant tensor (inverse)
         Gup(0, 0) = Gdown(1, 1) / det;
         Gup(0, 1) = -Gdown(0, 1) / det;
         Gup(1, 0) = -Gdown(1, 0) / det;
         Gup(1, 1) = Gdown(0, 0) / det;
         break;
       case 3:
         // Calculate the determinant of the matrix
         det = Gdown(0, 0) * Gdown(1, 1) * Gdown(2, 2) +
               Gdown(0, 1) * Gdown(1, 2) * Gdown(2, 0) +
               Gdown(0, 2) * Gdown(1, 0) * Gdown(2, 1) -
               Gdown(0, 0) * Gdown(1, 2) * Gdown(2, 1) -
               Gdown(0, 1) * Gdown(1, 0) * Gdown(2, 2) -
               Gdown(0, 2) * Gdown(1, 1) * Gdown(2, 0);
         // Calculate entries of the inverse matrix
         Gup(0, 0) =
           (Gdown(1, 1) * Gdown(2, 2) - Gdown(1, 2) * Gdown(2, 1)) / det;
         Gup(0, 1) =
           -(Gdown(0, 1) * Gdown(2, 2) - Gdown(0, 2) * Gdown(2, 1)) / det;
         Gup(0, 2) =
           (Gdown(0, 1) * Gdown(1, 2) - Gdown(0, 2) * Gdown(1, 1)) / det;
         Gup(1, 0) =
           -(Gdown(1, 0) * Gdown(2, 2) - Gdown(1, 2) * Gdown(2, 0)) / det;
         Gup(1, 1) =
           (Gdown(0, 0) * Gdown(2, 2) - Gdown(0, 2) * Gdown(2, 0)) / det;
         Gup(1, 2) =
           -(Gdown(0, 0) * Gdown(1, 2) - Gdown(0, 2) * Gdown(1, 0)) / det;
         Gup(2, 0) =
           (Gdown(1, 0) * Gdown(2, 1) - Gdown(1, 1) * Gdown(2, 0)) / det;
         Gup(2, 1) =
           -(Gdown(0, 0) * Gdown(2, 1) - Gdown(0, 1) * Gdown(2, 0)) / det;
         Gup(2, 2) =
           (Gdown(0, 0) * Gdown(1, 1) - Gdown(0, 1) * Gdown(1, 0)) / det;
         break;
       default:
         throw OomphLibError("Dimension of matrix must be 0, 1, 2 or 3\n",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
         break;
     }
     // Return the determinant of the matrix
     return (det);
   }
References are_matrices_of_equal_dimensions(), is_matrix_square(), oomph::DenseMatrix< T >::ncol(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
Referenced by oomph::GeneralisedHookean::calculate_second_piola_kirchhoff_stress(), and oomph::IsotropicStrainEnergyFunctionConstitutiveLaw::calculate_second_piola_kirchhoff_stress().
calculate_d_contravariant_dG()
void oomph::ConstitutiveLaw::calculate_d_contravariant_dG (const DenseMatrix< double > & Gdown, RankFourTensor< double > & d_Gup_dG, DenseMatrix< double > & d_detG_dG) protected
Calculate the derivatives of the contravariant tensor and the derivatives of the determinant of the covariant tensor with respect to the components of the covariant tensor
The function to calculate the derivatives of the contravariant tensor and determinant of covariant tensor with respect to the components of the covariant tensor
Three dimensions
   {
     // Find the dimension of the matrix
     const unsigned dim = Gdown.ncol();
     // If it's not square, I don't know what to do (yet)
 #ifdef PARANOID
     if (!is_matrix_square(Gdown))
     {
       std::string error_message =
         "Matrix passed to calculate_contravariant() is not square\n";
       error_message += "non-square matrix inversion not implemented yet!\n";
       throw OomphLibError(
         error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Define the determinant of the matrix
     double det = 0.0;
     // Now the inversion depends upon the dimension of the matrix
     switch (dim)
     {
         // Zero dimensions
       case 0:
         throw OomphLibError("Zero dimensional matrix",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
         break;
         // One dimension
       case 1:
         // There is only one entry, so derivatives are easy
         d_detG_dG(0, 0) = 1.0;
         d_Gup_dG(0, 0, 0, 0) = -1.0 / (Gdown(0, 0) * Gdown(0, 0));
         break;
         // Two dimensions
       case 2:
         // Calculate the determinant
         det = Gdown(0, 0) * Gdown(1, 1) - Gdown(0, 1) * Gdown(1, 0);
         // Calculate the derivatives of the determinant
         d_detG_dG(0, 0) = Gdown(1, 1);
         // Need to use symmetry here
         d_detG_dG(0, 1) = d_detG_dG(1, 0) = -2.0 * Gdown(0, 1);
         d_detG_dG(1, 1) = Gdown(0, 0);
         // Calculate the "upper triangular" derivatives of the contravariant
         // tensor
         {
           const double det2 = det * det;
           d_Gup_dG(0, 0, 0, 0) = -Gdown(1, 1) * d_detG_dG(0, 0) / det2;
           d_Gup_dG(0, 0, 0, 1) = -Gdown(1, 1) * d_detG_dG(0, 1) / det2;
           d_Gup_dG(0, 0, 1, 1) =
             1.0 / det - Gdown(1, 1) * d_detG_dG(1, 1) / det2;
           d_Gup_dG(0, 1, 0, 0) = Gdown(0, 1) * d_detG_dG(0, 0) / det2;
           d_Gup_dG(0, 1, 0, 1) =
             -1.0 / det + Gdown(0, 1) * d_detG_dG(0, 1) / det2;
           d_Gup_dG(0, 1, 1, 1) = Gdown(0, 1) * d_detG_dG(1, 1) / det2;
           d_Gup_dG(1, 1, 0, 0) =
             1.0 / det - Gdown(0, 0) * d_detG_dG(0, 0) / det2;
           d_Gup_dG(1, 1, 0, 1) = -Gdown(0, 0) * d_detG_dG(0, 1) / det2;
           d_Gup_dG(1, 1, 1, 1) = -Gdown(0, 0) * d_detG_dG(1, 1) / det2;
         }
         // Calculate entries of the contravariant tensor (inverse)
         // Gup(0,0) = Gdown(1,1)/det;
         // Gup(0,1) = -Gdown(0,1)/det;
         // Gup(1,0) = -Gdown(1,0)/det;
         // Gup(1,1) = Gdown(0,0)/det;
         break;
       case 3:
         // This is not yet implemented
         throw OomphLibError(
           "Analytic derivatives of metric tensors not yet implemented in 3D\n",
           OOMPH_CURRENT_FUNCTION,
           OOMPH_EXCEPTION_LOCATION);
         // Calculate the determinant of the matrix
         det = Gdown(0, 0) * Gdown(1, 1) * Gdown(2, 2) +
               Gdown(0, 1) * Gdown(1, 2) * Gdown(2, 0) +
               Gdown(0, 2) * Gdown(1, 0) * Gdown(2, 1) -
               Gdown(0, 0) * Gdown(1, 2) * Gdown(2, 1) -
               Gdown(0, 1) * Gdown(1, 0) * Gdown(2, 2) -
               Gdown(0, 2) * Gdown(1, 1) * Gdown(2, 0);
         // Calculate entries of the inverse matrix
         // Gup(0,0) =  (Gdown(1,1)*Gdown(2,2) - Gdown(1,2)*Gdown(2,1))/det;
         // Gup(0,1) = -(Gdown(0,1)*Gdown(2,2) - Gdown(0,2)*Gdown(2,1))/det;
         // Gup(0,2) =  (Gdown(0,1)*Gdown(1,2) - Gdown(0,2)*Gdown(1,1))/det;
         // Gup(1,0) = -(Gdown(1,0)*Gdown(2,2) - Gdown(1,2)*Gdown(2,0))/det;
         // Gup(1,1) =  (Gdown(0,0)*Gdown(2,2) - Gdown(0,2)*Gdown(2,0))/det;
         // Gup(1,2) = -(Gdown(0,0)*Gdown(1,2) - Gdown(0,2)*Gdown(1,0))/det;
         // Gup(2,0) =  (Gdown(1,0)*Gdown(2,1) - Gdown(1,1)*Gdown(2,0))/det;
         // Gup(2,1) = -(Gdown(0,0)*Gdown(2,1) - Gdown(0,1)*Gdown(2,0))/det;
         // Gup(2,2) =  (Gdown(0,0)*Gdown(1,1) - Gdown(0,1)*Gdown(1,0))/det;
         break;
       default:
         throw OomphLibError("Dimension of matrix must be 0, 1, 2 or 3\n",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
         break;
     }
   }
References is_matrix_square(), oomph::DenseMatrix< T >::ncol(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
calculate_d_second_piola_kirchhoff_stress_dG() [1/3]
void oomph::ConstitutiveLaw::calculate_d_second_piola_kirchhoff_stress_dG (const DenseMatrix< double > & g, const DenseMatrix< double > & G, const DenseMatrix< double > & sigma, const double & detG, const double & interpolated_solid_p, RankFourTensor< double > & d_sigma_dG, DenseMatrix< double > & d_detG_dG, const bool & symmetrize_tensor = true) virtual
Calculate the derivatives of the contravariant 2nd Piola Kirchhoff stress tensor \(\sigma^{ij}\). with respect to the deformed metric tensor. Also return the derivatives of the determinant of the deformed metric tensor with respect to the deformed metric tensor. This form is appropriate for truly-incompressible materials. The default implementation uses finite differences for the derivatives that depend on the constitutive law, but not for the derivatives of the determinant, which are generic. / If the boolean flag symmetrize_tensor is false, only the "upper triangular" entries of the tensor will be filled in. This is a useful efficiency when using the derivatives in Jacobian calculations.
Calculate the derivatives of the contravariant 2nd Piola Kirchhoff stress tensor \(\sigma^{ij}\). with respect to the deformed metric tensor. Also return the derivatives of the determinant of the deformed metric tensor with respect to the deformed metric tensor. This form is appropriate for truly-incompressible materials. The default implementation uses finite differences for the derivatives that depend on the constitutive law, but not for the derivatives of the determinant, which are generic.
   {
     // Initial error checking
 #ifdef PARANOID
     // Test that the matrices are of the same dimension
     if (!are_matrices_of_equal_dimensions(g, G))
     {
       throw OomphLibError("Matrices passed are not of equal dimension",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Find the dimension of the matrix (assuming that it's square)
     const unsigned dim = G.ncol();
     // FD step
     const double eps_fd = GeneralisedElement::Default_fd_jacobian_step;
     // Advanced metric tensor etc.
     DenseMatrix<double> G_pls(dim, dim);
     DenseMatrix<double> sigma_dev_pls(dim, dim);
     DenseMatrix<double> Gup_pls(dim, dim);
     double detG_pls;
     // Copy across
     for (unsigned i = 0; i < dim; i++)
     {
       for (unsigned j = 0; j < dim; j++)
       {
         G_pls(i, j) = G(i, j);
       }
     }
     // Do FD -- only w.r.t. to upper indices, exploiting symmetry.
     // NOTE: We exploit the symmetry of the stress and metric tensors
     //       by incrementing G(i,j) and G(j,i) simultaenously and
     //       only fill in the "upper" triangles without copying things
     //       across the lower triangle. This is taken into account
     //       in the remaining code further below.
     for (unsigned i = 0; i < dim; i++)
     {
       for (unsigned j = i; j < dim; j++)
       {
         G_pls(i, j) += eps_fd;
         G_pls(j, i) = G_pls(i, j);
         // Get advanced stress
         this->calculate_second_piola_kirchhoff_stress(
           g, G_pls, sigma_dev_pls, Gup_pls, detG_pls);
         // Derivative of determinant of deformed metric tensor
         d_detG_dG(i, j) = (detG_pls - detG) / eps_fd;
         // Derivatives of deviatoric stress and "upper" deformed metric
         // tensor
         for (unsigned ii = 0; ii < dim; ii++)
         {
           for (unsigned jj = ii; jj < dim; jj++)
           {
             d_sigma_dG(ii, jj, i, j) =
               (sigma_dev_pls(ii, jj) - interpolated_solid_p * Gup_pls(ii, jj) -
                sigma(ii, jj)) /
               eps_fd;
           }
         }
         // Reset
         G_pls(i, j) = G(i, j);
         G_pls(j, i) = G(j, i);
       }
     }
     // If we are symmetrising the tensor, do so
     if (symmetrize_tensor)
     {
       for (unsigned i = 0; i < dim; i++)
       {
         for (unsigned j = 0; j < i; j++)
         {
           d_detG_dG(i, j) = d_detG_dG(j, i);
           for (unsigned ii = 0; ii < dim; ii++)
           {
             for (unsigned jj = 0; jj < ii; jj++)
             {
               d_sigma_dG(ii, jj, i, j) = d_sigma_dG(jj, ii, j, i);
             }
           }
         }
       }
     }
   }
References are_matrices_of_equal_dimensions(), calculate_second_piola_kirchhoff_stress(), oomph::GeneralisedElement::Default_fd_jacobian_step, G, i, j, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and calibrate::sigma.
calculate_d_second_piola_kirchhoff_stress_dG() [2/3]
void oomph::ConstitutiveLaw::calculate_d_second_piola_kirchhoff_stress_dG (const DenseMatrix< double > & g, const DenseMatrix< double > & G, const DenseMatrix< double > & sigma, const double & gen_dil, const double & inv_kappa, const double & interpolated_solid_p, RankFourTensor< double > & d_sigma_dG, DenseMatrix< double > & d_gen_dil_dG, const bool & symmetrize_tensor = true) virtual
Calculate the derivatives of the contravariant 2nd Piola Kirchoff stress tensor with respect to the deformed metric tensor. Also return the derivatives of the generalised dilatation, \(d, \) with respect to the deformed metric tensor. This form is appropriate for near-incompressible materials. The default implementation uses finite differences. If the boolean flag symmetrize_tensor is false, only the "upper triangular" entries of the tensor will be filled in. This is a useful efficiency when using the derivatives in Jacobian calculations.
Calculate the derivatives of the contravariant 2nd Piola Kirchoff stress tensor with respect to the deformed metric tensor. Also return the derivatives of the generalised dilatation, \(d, \) with respect to the deformed metric tensor. This form is appropriate for near-incompressible materials. The default implementation uses finite differences.
   {
     // Initial error checking
 #ifdef PARANOID
     // Test that the matrices are of the same dimension
     if (!are_matrices_of_equal_dimensions(g, G))
     {
       throw OomphLibError("Matrices passed are not of equal dimension",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Find the dimension of the matrix (assuming that it's square)
     const unsigned dim = G.ncol();
     // FD step
     const double eps_fd = GeneralisedElement::Default_fd_jacobian_step;
     // Advanced metric tensor etc
     DenseMatrix<double> G_pls(dim, dim);
     DenseMatrix<double> sigma_dev_pls(dim, dim);
     DenseMatrix<double> Gup_pls(dim, dim);
     double gen_dil_pls;
     double inv_kappa_pls;
     // Copy across
     for (unsigned i = 0; i < dim; i++)
     {
       for (unsigned j = 0; j < dim; j++)
       {
         G_pls(i, j) = G(i, j);
       }
     }
     // Do FD -- only w.r.t. to upper indices, exploiting symmetry.
     // NOTE: We exploit the symmetry of the stress and metric tensors
     //       by incrementing G(i,j) and G(j,i) simultaenously and
     //       only fill in the "upper" triangles without copying things
     //       across the lower triangle. This is taken into account
     //       in the remaining code further below.
     for (unsigned i = 0; i < dim; i++)
     {
       for (unsigned j = i; j < dim; j++)
       {
         G_pls(i, j) += eps_fd;
         G_pls(j, i) = G_pls(i, j);
         // Get advanced stress
         this->calculate_second_piola_kirchhoff_stress(
           g, G_pls, sigma_dev_pls, Gup_pls, gen_dil_pls, inv_kappa_pls);
         // Derivative of generalised dilatation
         d_gen_dil_dG(i, j) = (gen_dil_pls - gen_dil) / eps_fd;
         // Derivatives of deviatoric stress and "upper" deformed metric
         // tensor
         for (unsigned ii = 0; ii < dim; ii++)
         {
           for (unsigned jj = ii; jj < dim; jj++)
           {
             d_sigma_dG(ii, jj, i, j) =
               (sigma_dev_pls(ii, jj) - interpolated_solid_p * Gup_pls(ii, jj) -
                sigma(ii, jj)) /
               eps_fd;
           }
         }
         // Reset
         G_pls(i, j) = G(i, j);
         G_pls(j, i) = G(j, i);
       }
     }
     // If we are symmetrising the tensor, do so
     if (symmetrize_tensor)
     {
       for (unsigned i = 0; i < dim; i++)
       {
         for (unsigned j = 0; j < i; j++)
         {
           d_gen_dil_dG(i, j) = d_gen_dil_dG(j, i);
           for (unsigned ii = 0; ii < dim; ii++)
           {
             for (unsigned jj = 0; jj < ii; jj++)
             {
               d_sigma_dG(ii, jj, i, j) = d_sigma_dG(jj, ii, j, i);
             }
           }
         }
       }
     }
   }
References are_matrices_of_equal_dimensions(), calculate_second_piola_kirchhoff_stress(), oomph::GeneralisedElement::Default_fd_jacobian_step, G, i, j, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and calibrate::sigma.
calculate_d_second_piola_kirchhoff_stress_dG() [3/3]
void oomph::ConstitutiveLaw::calculate_d_second_piola_kirchhoff_stress_dG (const DenseMatrix< double > & g, const DenseMatrix< double > & G, const DenseMatrix< double > & sigma, RankFourTensor< double > & d_sigma_dG, const bool & symmetrize_tensor = true) virtual
Calculate the derivatives of the contravariant 2nd Piola Kirchhoff stress tensor with respect to the deformed metric tensor. Arguments are the covariant undeformed and deformed metric tensor, the current value of the stress tensor and the rank four tensor in which to return the derivatives of the stress tensor The default implementation uses finite differences, but can be overloaded for constitutive laws in which an analytic formulation is possible. If the boolean flag symmetrize_tensor is false, only the "upper triangular" entries of the tensor will be filled in. This is a useful efficiency when using the derivatives in Jacobian calculations.
Calculate the derivatives of the contravariant 2nd Piola Kirchhoff stress tensor with respect to the deformed metric tensor. Arguments are the covariant undeformed and deformed metric tensor and the matrix in which to return the derivatives of the stress tensor The default implementation uses finite differences, but can be overloaded for constitutive laws in which an analytic formulation is possible.
   {
     // Initial error checking
 #ifdef PARANOID
     // Test that the matrices are of the same dimension
     if (!are_matrices_of_equal_dimensions(g, G))
     {
       throw OomphLibError("Matrices passed are not of equal dimension",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Find the dimension of the matrix (assuming that it's square)
     const unsigned dim = G.ncol();
     // Find the dimension
     // FD step
     const double eps_fd = GeneralisedElement::Default_fd_jacobian_step;
     // Advanced metric tensor
     DenseMatrix<double> G_pls(dim, dim);
     DenseMatrix<double> sigma_pls(dim, dim);
     // Copy across the original value
     for (unsigned i = 0; i < dim; i++)
     {
       for (unsigned j = 0; j < dim; j++)
       {
         G_pls(i, j) = G(i, j);
       }
     }
     // Do FD -- only w.r.t. to upper indices, exploiting symmetry.
     // NOTE: We exploit the symmetry of the stress and metric tensors
     //       by incrementing G(i,j) and G(j,i) simultaenously and
     //       only fill in the "upper" triangles without copying things
     //       across the lower triangle. This is taken into account
     //       in the solid mechanics codes.
     for (unsigned i = 0; i < dim; i++)
     {
       for (unsigned j = i; j < dim; j++)
       {
         G_pls(i, j) += eps_fd;
         G_pls(j, i) = G_pls(i, j);
         // Get advanced stress
         this->calculate_second_piola_kirchhoff_stress(g, G_pls, sigma_pls);
         for (unsigned ii = 0; ii < dim; ii++)
         {
           for (unsigned jj = ii; jj < dim; jj++)
           {
             d_sigma_dG(ii, jj, i, j) =
               (sigma_pls(ii, jj) - sigma(ii, jj)) / eps_fd;
           }
         }
         // Reset
         G_pls(i, j) = G(i, j);
         G_pls(j, i) = G(j, i);
       }
     }
     // If we are symmetrising the tensor, do so
     if (symmetrize_tensor)
     {
       for (unsigned i = 0; i < dim; i++)
       {
         for (unsigned j = 0; j < i; j++)
         {
           for (unsigned ii = 0; ii < dim; ii++)
           {
             for (unsigned jj = 0; jj < ii; jj++)
             {
               d_sigma_dG(ii, jj, i, j) = d_sigma_dG(jj, ii, j, i);
             }
           }
         }
       }
     }
   }
References are_matrices_of_equal_dimensions(), calculate_second_piola_kirchhoff_stress(), oomph::GeneralisedElement::Default_fd_jacobian_step, G, i, j, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and calibrate::sigma.
Referenced by oomph::PVDEquationsWithPressure< DIM >::get_d_stress_dG_upper(), and oomph::PVDEquations< DIM >::get_d_stress_dG_upper().
calculate_second_piola_kirchhoff_stress() [1/3]
virtual void oomph::ConstitutiveLaw::calculate_second_piola_kirchhoff_stress (const DenseMatrix< double > & g, const DenseMatrix< double > & G, DenseMatrix< double > & sigma) pure virtual
Calculate the contravariant 2nd Piola Kirchhoff stress tensor. Arguments are the covariant undeformed and deformed metric tensor and the matrix in which to return the stress tensor
Implemented in oomph::IsotropicStrainEnergyFunctionConstitutiveLaw, oomph::GeneralisedHookean, and oomph::AnisotropicHookean.
Referenced by calculate_d_second_piola_kirchhoff_stress_dG(), oomph::AxisymmetricPVDEquations::get_stress(), oomph::PVDEquations< DIM >::get_stress(), oomph::AxisymmetricPVDEquationsWithPressure::get_stress(), and oomph::PVDEquationsWithPressure< DIM >::get_stress().
calculate_second_piola_kirchhoff_stress() [2/3]
virtual void oomph::ConstitutiveLaw::calculate_second_piola_kirchhoff_stress (const DenseMatrix< double > & g, const DenseMatrix< double > & G, DenseMatrix< double > & sigma_dev, DenseMatrix< double > & G_contra, double & Gdet) inline virtual
Calculate the deviatoric part \(\overline{ \sigma^{ij}}\) of the contravariant 2nd Piola Kirchhoff stress tensor \(\sigma^{ij}\). Also return the contravariant deformed metric tensor and the determinant of the deformed metric tensor. This form is appropriate for truly-incompressible materials for which \(\sigma^{ij} = - p G^{ij} +\overline{ \sigma^{ij}} \) where the "pressure" \(p \) is determined by \(\det G_{ij} - \det g_{ij} = 0 \).
Reimplemented in oomph::IsotropicStrainEnergyFunctionConstitutiveLaw, and oomph::GeneralisedHookean.
     {
       throw OomphLibError(
         "Incompressible formulation not implemented for this constitutive law",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
calculate_second_piola_kirchhoff_stress() [3/3]
virtual void oomph::ConstitutiveLaw::calculate_second_piola_kirchhoff_stress (const DenseMatrix< double > & g, const DenseMatrix< double > & G, DenseMatrix< double > & sigma_dev, DenseMatrix< double > & Gcontra, double & gen_dil, double & inv_kappa) inline virtual
Calculate the deviatoric part of the contravariant 2nd Piola Kirchoff stress tensor. Also return the contravariant deformed metric tensor, the generalised dilatation, \(d, \) and the inverse of the bulk modulus \(\kappa\). This form is appropriate for near-incompressible materials for which \(\sigma^{ij} = -p G^{ij} + \overline{ \sigma^{ij}} \) where the "pressure" \(p \) is determined from \(p / \kappa - d =0 \).
Reimplemented in oomph::IsotropicStrainEnergyFunctionConstitutiveLaw, and oomph::GeneralisedHookean.
     {
       throw OomphLibError(
         "Near-incompressible formulation not implemented for constitutive law",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
error_checking_in_input()
void oomph::ConstitutiveLaw::error_checking_in_input (const DenseMatrix< double > & g, const DenseMatrix< double > & G, DenseMatrix< double > & sigma) protected
Check for errors in the input, i.e. check that the dimensions of the arrays are all consistent
This function is used to provide simple error (bounce) checks on the input to any calculate_second_piola_kirchhoff_stress
   {
     // Test whether the undeformed metric tensor is square
     if (!is_matrix_square(g))
     {
       throw OomphLibError("Undeformed metric tensor not square",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
     // If the deformed metric tensor does not have the same dimension as
     // the undeformed tensor, complain
     if (!are_matrices_of_equal_dimensions(g, G))
     {
       std::string error_message = "Deformed metric tensor does  \n";
       error_message +=
         "not have same dimensions as the undeformed metric tensor\n";
       throw OomphLibError(
         error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // If the stress tensor does not have the same dimensions as the others
     // complain.
     if (!are_matrices_of_equal_dimensions(g, sigma))
     {
       std::string error_message =
         "Strain tensor passed to calculate_green_strain() does  \n";
       error_message +=
         "not have same dimensions as the undeformed metric tensor\n";
       throw OomphLibError(
         error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
   }
References are_matrices_of_equal_dimensions(), G, is_matrix_square(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, calibrate::sigma, and oomph::Global_string_for_annotation::string().
Referenced by oomph::GeneralisedHookean::calculate_second_piola_kirchhoff_stress(), and oomph::IsotropicStrainEnergyFunctionConstitutiveLaw::calculate_second_piola_kirchhoff_stress().
is_matrix_square()
bool oomph::ConstitutiveLaw::is_matrix_square (const DenseMatrix< double > & M) protected
Test whether a matrix is square.
This function is used to check whether a matrix is square.
   {
     // If the number rows and columns is not equal, the matrix is not square
     if (M.nrow() != M.ncol())
     {
       return false;
     }
     else
     {
       return true;
     }
   }
Referenced by calculate_contravariant(), calculate_d_contravariant_dG(), and error_checking_in_input().
requires_incompressibility_constraint()
virtual bool oomph::ConstitutiveLaw::requires_incompressibility_constraint () pure virtual
Pure virtual function in which the user must declare if the constitutive equation requires an incompressible formulation in which the volume constraint is enforced explicitly. Used as a sanity check in PARANOID mode.
Implemented in oomph::IsotropicStrainEnergyFunctionConstitutiveLaw, and oomph::GeneralisedHookean.
Referenced by oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::PVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), and oomph::PVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure().
The documentation for this class was generated from the following files:
constitutive_laws.h
constitutive_laws.cc