MercuryDPM: Eigen::SPQR_QProduct< SPQRType, Derived > Struct Template Reference
Eigen::SPQR_QProduct< SPQRType, Derived > Struct Template Reference
#include <SuiteSparseQRSupport.h>
Public Types
typedef SPQRType::Scalar Scalar
typedef SPQRType::StorageIndex StorageIndex
Public Types inherited from Eigen::ReturnByValue< SPQR_QProduct< SPQRType, Derived > >
typedef internal::traits< SPQR_QProduct< SPQRType, Derived > >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Public Member Functions
SPQR_QProduct (const SPQRType &spqr, const Derived &other, bool transpose)
Index rows () const
Index cols () const
template<typename ResType >
void evalTo (ResType &res) const
Public Member Functions inherited from Eigen::ReturnByValue< SPQR_QProduct< SPQRType, Derived > >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Public Attributes
const SPQRType & m_spqr
const Derived & m_other
bool m_transpose
Member Typedef Documentation
Scalar
template<typename SPQRType , typename Derived > typedef SPQRType::Scalar Eigen::SPQR_QProduct< SPQRType, Derived >::Scalar
StorageIndex
template<typename SPQRType , typename Derived > typedef SPQRType::StorageIndex Eigen::SPQR_QProduct< SPQRType, Derived >::StorageIndex
Constructor & Destructor Documentation
SPQR_QProduct()
template<typename SPQRType , typename Derived > Eigen::SPQR_QProduct< SPQRType, Derived >::SPQR_QProduct (const SPQRType & spqr, const Derived & other, bool transpose) inline
       : m_spqr(spqr), m_other(other), m_transpose(transpose) {}
Member Function Documentation
cols()
template<typename SPQRType , typename Derived > Index Eigen::SPQR_QProduct< SPQRType, Derived >::cols () const inline
 { return m_other.cols(); }
References Eigen::SPQR_QProduct< SPQRType, Derived >::m_other.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
evalTo()
template<typename SPQRType , typename Derived > template<typename ResType > void Eigen::SPQR_QProduct< SPQRType, Derived >::evalTo (ResType & res) const inline
{
     cholmod_dense y_cd;
     cholmod_dense* x_cd;
     int method = m_transpose ? SPQR_QTX : SPQR_QX;
     cholmod_common* cc = m_spqr.cholmodCommon();
     y_cd = viewAsCholmod(m_other.const_cast_derived());
     x_cd = SuiteSparseQR_qmult<Scalar>(method, m_spqr.m_H, m_spqr.m_HTau, m_spqr.m_HPinv, &y_cd, cc);
     res = Matrix<Scalar, ResType::RowsAtCompileTime, ResType::ColsAtCompileTime>::Map(
         reinterpret_cast<Scalar*>(x_cd->x), x_cd->nrow, x_cd->ncol);
     cholmod_l_free_dense(&x_cd, cc);
   }
References Eigen::SPQR_QProduct< SPQRType, Derived >::m_other, Eigen::SPQR_QProduct< SPQRType, Derived >::m_spqr, Eigen::SPQR_QProduct< SPQRType, Derived >::m_transpose, Eigen::PlainObjectBase< Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ > >::Map(), res, and Eigen::viewAsCholmod().
rows()
template<typename SPQRType , typename Derived > Index Eigen::SPQR_QProduct< SPQRType, Derived >::rows () const inline
 { return m_transpose ? m_spqr.rows() : m_spqr.cols(); }
References Eigen::SPQR_QProduct< SPQRType, Derived >::m_spqr, and Eigen::SPQR_QProduct< SPQRType, Derived >::m_transpose.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_other
template<typename SPQRType , typename Derived > const Derived& Eigen::SPQR_QProduct< SPQRType, Derived >::m_other
Referenced by Eigen::SPQR_QProduct< SPQRType, Derived >::cols(), and Eigen::SPQR_QProduct< SPQRType, Derived >::evalTo().
m_spqr
template<typename SPQRType , typename Derived > const SPQRType& Eigen::SPQR_QProduct< SPQRType, Derived >::m_spqr
Referenced by Eigen::SPQR_QProduct< SPQRType, Derived >::evalTo(), and Eigen::SPQR_QProduct< SPQRType, Derived >::rows().
m_transpose
template<typename SPQRType , typename Derived > bool Eigen::SPQR_QProduct< SPQRType, Derived >::m_transpose
Referenced by Eigen::SPQR_QProduct< SPQRType, Derived >::evalTo(), and Eigen::SPQR_QProduct< SPQRType, Derived >::rows().
The documentation for this struct was generated from the following file:
SuiteSparseQRSupport.h