MercuryDPM: Eigen::internal::inner_sort_impl< Derived, Comp, true > Struct Template Reference
Eigen::internal::inner_sort_impl< Derived, Comp, true > Struct Template Reference
#include <SparseCompressedBase.h>
Public Types
typedef Derived::Scalar Scalar
typedef Derived::StorageIndex StorageIndex
Static Public Member Functions
static void run (SparseCompressedBase< Derived > &obj, Index, Index)
static Index check (const SparseCompressedBase< Derived > &obj, Index, Index)
Member Typedef Documentation
Scalar
template<typename Derived , class Comp > typedef Derived::Scalar Eigen::internal::inner_sort_impl< Derived, Comp, true >::Scalar
StorageIndex
template<typename Derived , class Comp > typedef Derived::StorageIndex Eigen::internal::inner_sort_impl< Derived, Comp, true >::StorageIndex
Member Function Documentation
check()
template<typename Derived , class Comp > static Index Eigen::internal::inner_sort_impl< Derived, Comp, true >::check (const SparseCompressedBase< Derived > & obj, Index , Index) inline static
{
     Index begin_offset = 0;
     Index end_offset = obj.nonZeros();
     const StorageIndex* begin_it = obj.innerIndexPtr() + begin_offset;
     const StorageIndex* end_it = obj.innerIndexPtr() + end_offset;
     return std::is_sorted(begin_it, end_it, Comp()) ? 1 : 0;
   }
References Eigen::SparseCompressedBase< Derived >::innerIndexPtr(), is_sorted(), and Eigen::SparseCompressedBase< Derived >::nonZeros().
run()
template<typename Derived , class Comp > static void Eigen::internal::inner_sort_impl< Derived, Comp, true >::run (SparseCompressedBase< Derived > & obj, Index , Index) inline static
{
     Index begin_offset = 0;
     Index end_offset = obj.nonZeros();
     CompressedStorageIterator<Scalar, StorageIndex> begin_it(begin_offset, obj.innerIndexPtr(), obj.valuePtr());
     CompressedStorageIterator<Scalar, StorageIndex> end_it(end_offset, obj.innerIndexPtr(), obj.valuePtr());
     std::sort(begin_it, end_it, Comp());
   }
References Eigen::SparseCompressedBase< Derived >::innerIndexPtr(), Eigen::SparseCompressedBase< Derived >::nonZeros(), and Eigen::SparseCompressedBase< Derived >::valuePtr().
The documentation for this struct was generated from the following file:
SparseCompressedBase.h