MercuryDPM: oomph::ElasticallySupportedRingElement Class Reference
oomph::ElasticallySupportedRingElement Class Reference
#include <circle_as_generalised_element.h>
Public Member Functions
ElasticallySupportedRingElement (const double &x_c, const double &y_c, const double &r)
virtual ~ElasticallySupportedRingElement ()
Destructor:
void set_load_pt (Data *load_pt)
double load ()
"Load" acting on the ring
double & k_stiff ()
Access function for the spring stiffness.
void pin_yc ()
Pin the vertical displacement.
void unpin_yc ()
Unpin the vertical displacement.
void get_residuals (Vector< double > &residuals)
Compute element residual vector (wrapper)
void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute element residual Vector and element Jacobian matrix (wrapper)
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual unsigned self_test ()
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeneralCircle
GeneralCircle (const double &x_c, const double &y_c, const double &r)
Constructor: Pass x and y-coords of centre and radius (all pinned)
GeneralCircle (Data *geom_data_pt)
virtual ~GeneralCircle ()
Destructor: Clean up if necessary.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position Vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
double & x_c ()
Access function to x-coordinate of centre of circle.
double & y_c ()
Access function to y-coordinate of centre of circle.
double & R ()
Access function to radius of circle.
unsigned ngeom_data () const
How many items of Data does the shape of the object depend on?
Data * geom_data_pt (const unsigned &j)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Protected Member Functions
void fill_in_generic_residual_contribution (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Private Attributes
double K_stiff
Stiffness of the ring's "elastic" support.
unsigned External_load_index
unsigned Internal_geometric_data_index
bool Load_data_has_been_set
Flag to indicate that load data has been set.
Additional Inherited Members
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Attributes inherited from oomph::GeneralCircle
Vector< Data * > Geom_data_pt
Vector of pointers to Data items that affects the object's shape.
bool Must_clean_up
Do I need to clean up?
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
/////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////// GeneralCircle "upgraded" to a GeneralisedElement: Circular ring whose position is given by
\[ x = X_c + R \cos(\zeta) \]
\[ y = Y_c + R \sin(\zeta) \]
The ring's vertical position \(Y_c \) is determined by "pseudo elasticity":
\[ 0 = f_{load} - Y_c \ k_{stiff} \]
This simulates the case where the centre of the ring is mounted on an elastic spring of stiffness \(k_{stiff} \) and loaded by the force \(f_{load}. \) The "load" is specified by the Data object load_pt().
Constructor & Destructor Documentation
ElasticallySupportedRingElement()
oomph::ElasticallySupportedRingElement::ElasticallySupportedRingElement (const double & x_c, const double & y_c, const double & r) inline
Constructor: Build ring from doubles that describe the geometry: x and y positions of centre and the radius. Initialise stiffness to 1.0. By default, no load is set.
                                                   :
   GeneralCircle(x_c,y_c,r), K_stiff(1.0), Load_data_has_been_set(false)
   {
    // The geometric data is internal to the element -- we copy the pointers
    // to the GeomObject's geometric data to the element's internal
    // data to ensure that any unknown values of geometric data are
    // given global equation numbers. The add_internal_data(...)
    // function returns the index by which the added Data item
    // is accessible from internal_data_pt(...).
    Internal_geometric_data_index=add_internal_data(Geom_data_pt[0]);
    // Geometric Data for the GeomObject has been set up (and pinned) in
    // constructor for geometric object. Now free the y-position
    // of the centre because we want to determine it as an unknown
    internal_data_pt(Internal_geometric_data_index)->unpin(1);
    // Change cleanup responsibilities: The GeomData will now be killed
    // by the GeneralisedElement when it wipes its internal Data
    Must_clean_up=false;
   }
References oomph::GeneralisedElement::add_internal_data(), oomph::GeneralCircle::Geom_data_pt, oomph::GeneralisedElement::internal_data_pt(), Internal_geometric_data_index, oomph::GeneralCircle::Must_clean_up, and oomph::Data::unpin().
~ElasticallySupportedRingElement()
virtual oomph::ElasticallySupportedRingElement::~ElasticallySupportedRingElement () inline virtual
Destructor:
   {
    // The GeomObject's GeomData is mirrored in the element's
    // Internal Data and therefore gets wiped in the
    // destructor of GeneralisedElement --> No need to kill it here
   }
Member Function Documentation
fill_in_generic_residual_contribution()
void oomph::ElasticallySupportedRingElement::fill_in_generic_residual_contribution (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) inline protected
Compute element residual Vector (only if flag=0) and also the element Jacobian matrix (if flag=1)
   {
    //Find out how may dofs there are in the element
    unsigned n_dof = ndof();
    //If everything is pinned return straight away
    if (n_dof==0) return;
    // Pseudo-elastic force balance to determine the position of the
    // ring's centre for a given load.
    // What's the local equation number of the force balance equation
    // [It's the equation that "determines" the value of the internal
    // dof, y_c, which is stored as the second value of the one-and-only
    // internal data object in this element]
    int local_eqn_number_for_yc =
     internal_local_eqn(Internal_geometric_data_index,1);
    // Add residual to appropriate entry in the element's residual
    // vector:
    residuals[local_eqn_number_for_yc]=load()-K_stiff*y_c();
    // Work out Jacobian:
    if (flag)
     {
      // Derivative of residual w.r.t. the internal dof, i.e. the vertical
      // position of the ring's centre: d residual[0]/d y_c
      jacobian(local_eqn_number_for_yc,local_eqn_number_for_yc) = -K_stiff;
      // Derivative with respect to external dof, i.e. the applied
      // load: d residual[0]/d load -- but only if the load is an unknown
      if (n_dof==2)
       {
        // What's the local equation number of the load parameter?
        // It's stored as the 0th value in the the element's
        // one-and-only external data item:
        int local_eqn_number_for_load =
         external_local_eqn(External_load_index,0);
 #ifdef PARANOID
        if (local_eqn_number_for_load<0)
         {
          throw OomphLibError(
           "Load is pinned and yet n_dof=2?\n This is very fishy!\n",
           OOMPH_CURRENT_FUNCTION,
           OOMPH_EXCEPTION_LOCATION);
         }
 #endif
        // Add entry into element Jacobian
        jacobian(local_eqn_number_for_yc,local_eqn_number_for_load) = 1.0;
       }
     }
   } // end of get_residuals_generic(...)
References External_load_index, oomph::GeneralisedElement::external_local_eqn(), Internal_geometric_data_index, oomph::GeneralisedElement::internal_local_eqn(), K_stiff, load(), oomph::GeneralisedElement::ndof(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::GeneralCircle::y_c().
Referenced by get_jacobian(), and get_residuals().
get_jacobian()
void oomph::ElasticallySupportedRingElement::get_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Compute element residual Vector and element Jacobian matrix (wrapper)
Reimplemented from oomph::GeneralisedElement.
   {
    //Initialise residuals to zero
    residuals.initialise(0.0);
    //Initialise the jacobian matrix to zero
    jacobian.initialise(0.0);
    //Call the generic routine with the flag set to 1
    fill_in_generic_residual_contribution(residuals,jacobian,1);
   } // end of get_jacobian(...)
References fill_in_generic_residual_contribution(), oomph::Vector< _Tp >::initialise(), and oomph::DenseMatrix< T >::initialise().
get_residuals()
void oomph::ElasticallySupportedRingElement::get_residuals (Vector< double > & residuals) inline virtual
Compute element residual vector (wrapper)
Reimplemented from oomph::GeneralisedElement.
   {
    //Initialise residuals to zero
    residuals.initialise(0.0);
    //Create a dummy matrix
    DenseMatrix<double> dummy(1);
    //Call the generic residuals function with flag set to 0
    fill_in_generic_residual_contribution(residuals,dummy,0);
    }
References fill_in_generic_residual_contribution(), and oomph::Vector< _Tp >::initialise().
k_stiff()
double& oomph::ElasticallySupportedRingElement::k_stiff () inline
Access function for the spring stiffness.
 {return K_stiff;}
References K_stiff.
Referenced by GeomObjectAsGeneralisedElementProblem::GeomObjectAsGeneralisedElementProblem().
load()
double oomph::ElasticallySupportedRingElement::load () inline
"Load" acting on the ring
   {
    // Return the load if it has been set
    if (Load_data_has_been_set)
     {
      return external_data_pt(External_load_index)->value(0);
     }
    // ...otherwise return zero load
    else
     {
      return 0.0;
     }
   } // end of load()
References oomph::GeneralisedElement::external_data_pt(), External_load_index, Load_data_has_been_set, and oomph::Data::value().
Referenced by fill_in_generic_residual_contribution().
pin_yc()
void oomph::ElasticallySupportedRingElement::pin_yc () inline
Pin the vertical displacement.
   {
    // Vertical position of centre is stored as value 1 in the
    // element's one and only internal Data object.
    internal_data_pt(Internal_geometric_data_index)->pin(1);
   }
References oomph::GeneralisedElement::internal_data_pt(), Internal_geometric_data_index, and oomph::Data::pin().
set_load_pt()
void oomph::ElasticallySupportedRingElement::set_load_pt (Data * load_pt) inline
Set pointer to Data object that specifies the "load" on the ElasticallySupportedRingElement
   {
 #ifdef PARANOID
    if (load_pt->nvalue()!=1)
     {
      std::ostringstream error_stream;
      error_stream << "The data object that stores the load on the "
                   << "ElasticallySupportedRingElement\n"
                   << "should only contain a single data value\n"
                   << "This one contains " << load_pt->nvalue() << std::endl;
      throw OomphLibError(error_stream.str(),
                          OOMPH_CURRENT_FUNCTION,
                          OOMPH_EXCEPTION_LOCATION);
     }
 #endif
    // Add load to the element's external data and store
    // its index within that storage scheme: Following this assignment,
    // the load Data is accessible from
    // GeneralisedElement::external_data_pt(External_load_index)
    External_load_index = add_external_data(load_pt);
    // Load has now been set
    Load_data_has_been_set=true;
   } // end of set_load_pt(...)
References oomph::GeneralisedElement::add_external_data(), External_load_index, Load_data_has_been_set, oomph::Data::nvalue(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by GeomObjectAsGeneralisedElementProblem::GeomObjectAsGeneralisedElementProblem().
unpin_yc()
void oomph::ElasticallySupportedRingElement::unpin_yc () inline
Unpin the vertical displacement.
   {
    // Vertical position of centre is stored as value 1 in the
    // element's one and only internal Data object.
    internal_data_pt(Internal_geometric_data_index)->unpin(1);
   } // end of unpin_yc()
References oomph::GeneralisedElement::internal_data_pt(), Internal_geometric_data_index, and oomph::Data::unpin().
Member Data Documentation
External_load_index
unsigned oomph::ElasticallySupportedRingElement::External_load_index private
Index of the location of the load Data in the element's array of external data
Referenced by fill_in_generic_residual_contribution(), load(), and set_load_pt().
Internal_geometric_data_index
unsigned oomph::ElasticallySupportedRingElement::Internal_geometric_data_index private
Index of the location of the geometric Data in the element's array of internal data
Referenced by ElasticallySupportedRingElement(), fill_in_generic_residual_contribution(), pin_yc(), and unpin_yc().
K_stiff
double oomph::ElasticallySupportedRingElement::K_stiff private
Stiffness of the ring's "elastic" support.
Referenced by fill_in_generic_residual_contribution(), and k_stiff().
Load_data_has_been_set
bool oomph::ElasticallySupportedRingElement::Load_data_has_been_set private
Flag to indicate that load data has been set.
Referenced by load(), and set_load_pt().
The documentation for this class was generated from the following file:
circle_as_generalised_element.h