MercuryDPM: oomph::MPI_Helpers Class Reference
oomph::MPI_Helpers Class Reference
#include <oomph_utilities.h>
Static Public Member Functions
static void init (int argc, char **argv, const bool &make_duplicate_of_mpi_comm_world=true)
static void finalize ()
finalize mpi
static OomphCommunicator * communicator_pt ()
access to the global oomph-lib communicator
static bool mpi_has_been_initialised ()
return true if MPI has been initialised
Private Member Functions
MPI_Helpers ()
MPI_Helpers (const MPI_Helpers &)
Static Private Attributes
static bool MPI_has_been_initialised = false
Bool set to true if MPI has been initialised.
static OomphCommunicator * Communicator_pt = 0
the global communicator
Detailed Description
MPI_Helpers class contains static helper methods to support MPI within oomph-lib. The methods init(...) and finalize() initialize and finalize MPI in oomph-lib and manage the oomph-libs global communicator communicator_pt(). NOTE: This class encapsulates static helper methods and instances of it CANNOT be instantiated.
Constructor & Destructor Documentation
MPI_Helpers() [1/2]
oomph::MPI_Helpers::MPI_Helpers () private
private default constructor definition (to prevent instances of the class being instantiated)
MPI_Helpers() [2/2]
oomph::MPI_Helpers::MPI_Helpers (const MPI_Helpers &) private
private copy constructor definition (to prevent instances of the class being instantiated)
Member Function Documentation
communicator_pt()
OomphCommunicator * oomph::MPI_Helpers::communicator_pt () static
access to the global oomph-lib communicator
access to global communicator. This is the oomph-lib equivalent of MPI_COMM_WORLD
   {
 #ifdef MPI
 #ifdef PARANOID
     if (!MPI_has_been_initialised)
     {
       std::ostringstream error_message_stream;
       error_message_stream
         << "MPI has not been initialised.\n Call MPI_Helpers::init(...)";
       throw OomphLibError(error_message_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     return Communicator_pt;
 #else // ifndef MPI
     // If MPI is not enabled then we are unlikely to have called init, so to
     // be nice to users create a new serial comm_pt if none exits.
     if (Communicator_pt == 0)
     {
       Communicator_pt = new OomphCommunicator;
     }
     // #ifdef PARANOID
     //  if(!Communicator_pt->serial_communicator())
     //   {
     //    std::string error_msg =
     //     "MPI_Helpers has somehow ended up with a non-serial\n"
     //     + "communicator pointer even though MPI is disabled!";
     //    throw OomphLibError(error_msg.str(),
     //                        OOMPH_CURRENT_FUNCTION,
     //                        OOMPH_EXCEPTION_LOCATION);
     //   }
     // #endif
     return Communicator_pt;
 #endif // end ifdef MPI
   }
References Communicator_pt, MPI_has_been_initialised, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::Z2ErrorEstimator::doc_flux(), oomph::MemoryUsage::doc_total_memory_usage(), oomph::HelmholtzMGPreconditioner< DIM >::full_setup(), oomph::Z2ErrorEstimator::get_element_errors(), oomph::Node::hanging_pt(), oomph::HypreInterface::hypre_solve(), oomph::HypreInterface::HypreInterface(), main(), oomph::Problem::Problem(), oomph::MemoryUsage::run_continous_top(), oomph::MGPreconditioner< DIM >::setup(), oomph::HelmholtzGMRESMG< MATRIX >::solve(), oomph::HelmholtzFGMRESMG< MATRIX >::solve(), and oomph::MemoryUsage::stop_continous_top().
finalize()
void oomph::MPI_Helpers::finalize () static
finalize mpi
finalize mpi (oomph-lib equivalent of MPI_Finalize()) Deletes the global oomph-lib communicator and finalizes MPI.
   {
     // delete the communicator
     delete Communicator_pt;
     // and call MPI_Finalize
 #ifdef OOMPH_HAS_MPI
     MPI_Finalize();
 #endif
   }
References Communicator_pt.
Referenced by main(), and oomph::CommandLineArgs::parse_and_assign().
init()
void oomph::MPI_Helpers::init (int argc, char ** argv, const bool & make_duplicate_of_mpi_comm_world = true) static
initialise mpi (oomph-libs equivalent of MPI_Init(...)) Initialises MPI and creates the global oomph-lib communicator. If optional boolean flag is set to false, we use MPI_COMM_WORLD itself as oomph-lib's communicator. Defaults to true.
Initialize mpi. If optional boolean flag is set to false, we use MPI_COMM_WORLD itself as oomph-lib's communicator. Defaults to true.
   {
 #ifdef OOMPH_HAS_MPI
     // call mpi int
     MPI_Init(&argc, &argv);
     // By default, create the oomph-lib communicator using MPI_Comm_dup so that
     // the communicator has the same group of processes but a new context
     MPI_Comm oomph_comm_world = MPI_COMM_WORLD;
     if (make_duplicate_of_mpi_comm_world)
     {
       MPI_Comm_dup(MPI_COMM_WORLD, &oomph_comm_world);
     }
     if (MPI_COMM_WORLD != oomph_comm_world)
     {
       oomph_info << "Oomph-lib communicator is a duplicate of MPI_COMM_WORLD\n";
     }
     else
     {
       oomph_info << "Oomph-lib communicator is MPI_COMM_WORLD\n";
     }
     // create the oomph-lib communicator
     // note: oomph_comm_world is deleted when the destructor of
     // Communicator_pt is called
     Communicator_pt = new OomphCommunicator(oomph_comm_world, true);
     // Change MPI error handler so that error will return
     // rather than aborting
     MPI_Comm_set_errhandler(oomph_comm_world, MPI_ERRORS_RETURN);
     // Use MPI output modifier: Each processor precedes its output
     // by its rank
     oomph_mpi_output.communicator_pt() = Communicator_pt;
     oomph_info.output_modifier_pt() = &oomph_mpi_output;
 #else
     // create a serial communicator
     Communicator_pt = new OomphCommunicator;
 #endif
     MPI_has_been_initialised = true;
   }
References Communicator_pt, MPI_has_been_initialised, oomph::oomph_info, and oomph::OomphInfo::output_modifier_pt().
Referenced by main().
mpi_has_been_initialised()
static bool oomph::MPI_Helpers::mpi_has_been_initialised () inline static
return true if MPI has been initialised
     {
       return MPI_has_been_initialised;
     }
Referenced by BoussinesqPreconditioner::BoussinesqPreconditioner(), oomph::HypreHelpers::create_HYPRE_Matrix(), oomph::MemoryUsage::doc_total_memory_usage(), oomph::SuperLUSolver::factorise(), oomph::Z2ErrorEstimator::get_element_errors(), oomph::HypreInterface::hypre_solve(), oomph::HypreInterface::HypreInterface(), oomph::Problem::newton_solve(), oomph::Problem::Problem(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project(), oomph::MemoryUsage::run_continous_top(), oomph::MatrixVectorProduct::setup(), oomph::MemoryUsage::stop_continous_top(), RefineableConvectionProblem< NST_ELEMENT, AD_ELEMENT >::switch_to_iterative_linear_solver(), and oomph::TimingHelpers::timer().
Member Data Documentation
Communicator_pt
OomphCommunicator * oomph::MPI_Helpers::Communicator_pt = 0 static private
the global communicator
Referenced by communicator_pt(), finalize(), and init().
MPI_has_been_initialised
bool oomph::MPI_Helpers::MPI_has_been_initialised = false static private
Bool set to true if MPI has been initialised.
Referenced by communicator_pt(), and init().
The documentation for this class was generated from the following files:
oomph_utilities.h
oomph_utilities.cc