MercuryDPM: Eigen::internal::evaluator< SparseCompressedBase< Derived > > Struct Template Reference
Eigen::internal::evaluator< SparseCompressedBase< Derived > > Struct Template Reference
#include <SparseCompressedBase.h>
Public Types
enum { CoeffReadCost = NumTraits<Scalar>::ReadCost , Flags = Derived::Flags }
typedef Derived::Scalar Scalar
typedef Derived::InnerIterator InnerIterator
typedef DenseCoeffsBase< Derived, ReadOnlyAccessors >::CoeffReturnType CoeffReturnType
Public Types inherited from Eigen::internal::evaluator_base< Derived >
enum
typedef traits< Derived > ExpressionTraits
Public Member Functions
evaluator ()
evaluator (const Derived &mat)
Index nonZerosEstimate () const
operator Derived & ()
operator const Derived & () const
const Scalar & coeff (Index row, Index col) const
Scalar & coeffRef (Index row, Index col)
Public Member Functions inherited from Eigen::internal::evaluator_base< Derived >
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE evaluator_base ()=default
Protected Member Functions
Index find (Index row, Index col) const
Protected Attributes
const Derived * m_matrix
const Scalar m_zero
Member Typedef Documentation
CoeffReturnType
template<typename Derived > typedef DenseCoeffsBase<Derived, ReadOnlyAccessors>::CoeffReturnType Eigen::internal::evaluator< SparseCompressedBase< Derived > >::CoeffReturnType
InnerIterator
template<typename Derived > typedef Derived::InnerIterator Eigen::internal::evaluator< SparseCompressedBase< Derived > >::InnerIterator
Scalar
template<typename Derived > typedef Derived::Scalar Eigen::internal::evaluator< SparseCompressedBase< Derived > >::Scalar
Member Enumeration Documentation
anonymous enum
template<typename Derived > anonymous enum
Enumerator
CoeffReadCost
Flags
 { CoeffReadCost = NumTraits<Scalar>::ReadCost, Flags = Derived::Flags };
Constructor & Destructor Documentation
evaluator() [1/2]
template<typename Derived > Eigen::internal::evaluator< SparseCompressedBase< Derived > >::evaluator () inline
 : m_matrix(0), m_zero(0) { EIGEN_INTERNAL_CHECK_COST_VALUE(CoeffReadCost); }
References EIGEN_INTERNAL_CHECK_COST_VALUE.
evaluator() [2/2]
template<typename Derived > Eigen::internal::evaluator< SparseCompressedBase< Derived > >::evaluator (const Derived & mat) inline explicit
 : m_matrix(&mat), m_zero(0) { EIGEN_INTERNAL_CHECK_COST_VALUE(CoeffReadCost); }
References EIGEN_INTERNAL_CHECK_COST_VALUE.
Member Function Documentation
coeff()
template<typename Derived > const Scalar& Eigen::internal::evaluator< SparseCompressedBase< Derived > >::coeff (Index row, Index col) const inline
{
     Index p = find(row, col);
     if (p == Dynamic)
       return m_zero;
     else
       return m_matrix->const_cast_derived().valuePtr()[p];
   }
References col(), Eigen::Dynamic, p, and row().
coeffRef()
template<typename Derived > Scalar& Eigen::internal::evaluator< SparseCompressedBase< Derived > >::coeffRef (Index row, Index col) inline
{
     Index p = find(row, col);
     eigen_assert(p != Dynamic && "written coefficient does not exist");
     return m_matrix->const_cast_derived().valuePtr()[p];
   }
References col(), Eigen::Dynamic, eigen_assert, p, and row().
find()
template<typename Derived > Index Eigen::internal::evaluator< SparseCompressedBase< Derived > >::find (Index row, Index col) const inline protected
{
     internal::LowerBoundIndex p = m_matrix->lower_bound(row, col);
     return p.found ? p.value : Dynamic;
   }
References col(), Eigen::Dynamic, p, and row().
nonZerosEstimate()
template<typename Derived > Index Eigen::internal::evaluator< SparseCompressedBase< Derived > >::nonZerosEstimate () const inline
 { return m_matrix->nonZeros(); }
operator const Derived &()
template<typename Derived > Eigen::internal::evaluator< SparseCompressedBase< Derived > >::operator const Derived & () const inline
 { return *m_matrix; }
operator Derived &()
template<typename Derived > Eigen::internal::evaluator< SparseCompressedBase< Derived > >::operator Derived & () inline
 { return m_matrix->const_cast_derived(); }
Member Data Documentation
m_matrix
template<typename Derived > const Derived* Eigen::internal::evaluator< SparseCompressedBase< Derived > >::m_matrix protected
m_zero
template<typename Derived > const Scalar Eigen::internal::evaluator< SparseCompressedBase< Derived > >::m_zero protected
The documentation for this struct was generated from the following file:
SparseCompressedBase.h