MercuryDPM: negate_test_impl< Scalar, Packet, HasNegate > Struct Template Reference
negate_test_impl< Scalar, Packet, HasNegate > Struct Template Reference
Static Public Member Functions
static void run_negate (Scalar *data1, Scalar *data2, Scalar *ref, int PacketSize)
static void run_nmsub (Scalar *data1, Scalar *data2, Scalar *ref, int PacketSize)
Member Function Documentation
run_negate()
template<typename Scalar , typename Packet , bool HasNegate = internal::packet_traits<Scalar>::HasNegate> static void negate_test_impl< Scalar, Packet, HasNegate >::run_negate (Scalar * data1, Scalar * data2, Scalar * ref, int PacketSize) inline static
{
     CHECK_CWISE1_IF(HasNegate, test::negate, internal::pnegate);
   }
References CHECK_CWISE1_IF, Eigen::test::negate(), and Eigen::internal::pnegate().
Referenced by negate_test().
run_nmsub()
template<typename Scalar , typename Packet , bool HasNegate = internal::packet_traits<Scalar>::HasNegate> static void negate_test_impl< Scalar, Packet, HasNegate >::run_nmsub (Scalar * data1, Scalar * data2, Scalar * ref, int PacketSize) inline static
{
     CHECK_CWISE3_IF(HasNegate, REF_NMSUB, internal::pnmsub);
   }
References CHECK_CWISE3_IF, Eigen::internal::pnmsub(), and REF_NMSUB().
Referenced by nmsub_test().
The documentation for this struct was generated from the following file:
packetmath.cpp