MercuryDPM: CGFields::StandardFields Class Reference
CGFields::StandardFields Class Reference
Contains the computed field values, like density, momentum and stress.
#include <StandardFields.h>
Public Member Functions
StandardFields ()
Default constructor, sets all field values to zero.
StandardFields (const StandardFields &P)=default
Default copy constructor, copies the values of all fields.
~StandardFields ()=default
Destructor, it simply destructs the StandardFields and all the objects it contains.
void write (std::ostream &os) const
Writes class content into an output stream, typically a stat file.
void output (std::ostream &os) const
Writes human-readable class content into an output stream, typically a stat file.
void setZero ()
Sets all fields to zero.
StandardFields getSquared () const
Returns the square of all field values (to calculate standard deviation).
StandardFields & operator= (const StandardFields &P)
Copies all field values.
StandardFields & operator+= (const StandardFields &P)
Adds the field values on the RHS to the LHS of the equation.
StandardFields & operator-= (const StandardFields &P)
Subtracts the field values on the RHS from the LHS of the equation.
StandardFields & operator/= (Mdouble a)
Divides the field values on the LHS by the RHS of the equation.
StandardFields operator* (Mdouble a) const
Multiplies the field values on the left of the '*' by the scalar value on the right of the '*' and returns the answer.
void addParticleStatistics (Mdouble phi, const StandardFields &currentInteraction)
This function should be called from within a loop over all particles to compute all the fields that are defined as a sum over all particles (e.g. density, momentum).
void addParticleDifferentialStatistics (Vec3D &dphi, const StandardFields &currentInteraction)
void addInteractionStatistics (Mdouble psi, const StandardFields &currentInteraction)
This function should be called from within a loop over all Interactions to compute all the fields that are defined as a sum over all Interactions (e.g. stress).
void addContactPointStatistics (Mdouble phi, const StandardFields &currentInteraction)
This function should be called from within a loop over all Interactions to compute all the fields that are defined as a sum over all Interactions with external objects (e.g. IFD).
void setFields (const BaseInteraction &c, IntegralType type)
void setCylindricalFields (const BaseInteraction &c, IntegralType type)
void setFields (const BaseParticle &p)
void setCylindricalFields (const BaseParticle &p)
Mdouble getVolumeFraction () const
Mdouble getDensity () const
Vec3D getMomentum () const
MatrixSymmetric3D getMomentumFlux () const
Matrix3D getContactStress () const
Vec3D getInteractionForceDensity () const
Mdouble getParticleSizeDensity (size_t i) const
std::array< Mdouble, 6 > getParticleSizeDensity () const
std::array< Mdouble, 6 > getParticleSizeMomenta () const
std::array< Mdouble, 6 > getCentralParticleSizeMomenta () const
std::array< Mdouble, 6 > getStandardisedParticleSizeMomenta () const
void outputStandardisedParticleSizeMomenta (std::ostream &os) const
Public Member Functions inherited from CGFields::BaseFields
void setCG (BaseCG *cg)
BaseCG * getCG ()
Static Public Member Functions
static void writeNames (std::ostream &os, unsigned countVariables)
static bool doInteractionStatistics ()
Returns true if the class contains fields that are defined as a sum over all Interactions (e.g. stress), else returns false.
static bool evaluateFixedParticles ()
static bool isDifferentialField ()
Protected Member Functions
void setContactStress (Matrix3D contactStress)
void addContactStress (Matrix3D contactStress)
void setInteractionForceDensity (Vec3D interactionForceDensity)
void addInteractionForceDensity (Vec3D interactionForceDensity)
Private Attributes
Mdouble volumeFraction_
Mdouble density_
Vec3D momentum_
MatrixSymmetric3D momentumFlux_
Matrix3D contactStress_
Vec3D interactionForceDensity_
std::array< Mdouble, 6 > particleSizeDensity_
Additional Inherited Members
Protected Attributes inherited from CGFields::BaseFields
BaseCG * cg_ = nullptr
Stores a pointer to the baseCG instance to get e.g. the handler and time information.
Detailed Description
Contains the computed field values, like density, momentum and stress.
CGPoints inherits from this class; CGPoints::evaluate adds to the values of these variables.
Todo:
These are currently the only fields that are computed. However, this class is destined to be extended to contain additional information such as fabric, energy, local angular momentum. Also, a simpler version is planned, where only particle statistics are evaluated (density and momentum).
Constructor & Destructor Documentation
StandardFields() [1/2]
CGFields::StandardFields::StandardFields ()
Default constructor, sets all field values to zero.
 {
     setZero();
 #ifdef DEBUG_CONSTRUCTOR
     std::cerr << "StandardFields::StandardFields() finished" << std::endl;
 #endif
 }
References setZero().
StandardFields() [2/2]
CGFields::StandardFields::StandardFields (const StandardFields & P) default
Default copy constructor, copies the values of all fields.
~StandardFields()
CGFields::StandardFields::~StandardFields () default
Destructor, it simply destructs the StandardFields and all the objects it contains.
Member Function Documentation
addContactPointStatistics()
void CGFields::StandardFields::addContactPointStatistics (Mdouble phi, const StandardFields & currentInteraction)
This function should be called from within a loop over all Interactions to compute all the fields that are defined as a sum over all Interactions with external objects (e.g. IFD).
Parameters
[in] phi the value of the cg function for the contact point of c and the current CGPoint
[in] c the interaction which is used in the cg function
 {
     interactionForceDensity_ += currentInteraction.getInteractionForceDensity() * phi;
 }
References getInteractionForceDensity(), and interactionForceDensity_.
addContactStress()
void CGFields::StandardFields::addContactStress (Matrix3D contactStress) inline protected
     {
         contactStress_ += contactStress;
     }
References contactStress_.
Referenced by CGFields::StandardFieldsBinning::addParticleStatistics().
addInteractionForceDensity()
void CGFields::StandardFields::addInteractionForceDensity (Vec3D interactionForceDensity) inline protected
     {
         interactionForceDensity_ += interactionForceDensity;
     }
References interactionForceDensity_.
Referenced by CGFields::StandardFieldsBinning::addParticleStatistics().
addInteractionStatistics()
void CGFields::StandardFields::addInteractionStatistics (Mdouble psi, const StandardFields & currentInteraction)
This function should be called from within a loop over all Interactions to compute all the fields that are defined as a sum over all Interactions (e.g. stress).
Parameters
[in] psi the value of the line integral from C to P at the current CGPoint
[in] c the contact which is used in the line integral
 {
     contactStress_ += currentInteraction.getContactStress() * psi;
 }
References contactStress_, and getContactStress().
addParticleDifferentialStatistics()
void CGFields::StandardFields::addParticleDifferentialStatistics (Vec3D & dphi, const StandardFields & currentInteraction)
 {
 }
addParticleStatistics()
void CGFields::StandardFields::addParticleStatistics (Mdouble phi, const StandardFields & currentInteraction)
This function should be called from within a loop over all particles to compute all the fields that are defined as a sum over all particles (e.g. density, momentum).
Parameters
[in] phi the value of the cg function at the current CGPoint
[in] currentInteraction the fields which are produced due to the particle at its centre
 {
     volumeFraction_ += currentInteraction.getVolumeFraction() * phi;
     density_ += currentInteraction.getDensity() * phi;
     momentum_ += currentInteraction.getMomentum() * phi;
     momentumFlux_ += currentInteraction.getMomentumFlux() * phi;
     for (size_t i = 0; i < particleSizeDensity_.size(); ++i)
         particleSizeDensity_[i] += currentInteraction.getParticleSizeDensity(i) * phi;
 }
References density_, getDensity(), getMomentum(), getMomentumFlux(), getParticleSizeDensity(), getVolumeFraction(), i, momentum_, momentumFlux_, particleSizeDensity_, and volumeFraction_.
Referenced by CGFields::StandardFieldsBinning::addParticleStatistics().
doInteractionStatistics()
bool CGFields::StandardFields::doInteractionStatistics () static
Returns true if the class contains fields that are defined as a sum over all Interactions (e.g. stress), else returns false.
If the functions returns false, addInteractionStatistics and addContactPointStatistics are never called.
Returns
True if the class contains fields that are defined as a sum over all Interactions, else false.
 {
     return true;
 }
evaluateFixedParticles()
static bool CGFields::StandardFields::evaluateFixedParticles () inline static
     {
         return false;
     }
getCentralParticleSizeMomenta()
std::array< Mdouble, 6 > CGFields::StandardFields::getCentralParticleSizeMomenta () const
 {
     //https://en.wikipedia.org/wiki/Central_moment
     auto momenta = getParticleSizeMomenta();
     Mdouble mean = momenta[1];
     momenta[5] += -5 * mean * momenta[4] + 10 * mean * mean * momenta[3]
                   - 10 * mean * mean * mean * momenta[2] + 4 * mean * mean * mean * mean * mean;
     momenta[4] += -4 * mean * momenta[3] + 6 * mean * mean * momenta[2] - 3 * mean * mean * mean * mean;
     momenta[3] += -3 * mean * momenta[2] + 2 * mean * mean * mean;
     momenta[2] += -mean * mean;
     return momenta;
 }
References getParticleSizeMomenta().
Referenced by getStandardisedParticleSizeMomenta().
getContactStress()
Matrix3D CGFields::StandardFields::getContactStress () const inline
     {
         return contactStress_;
     }
References contactStress_.
Referenced by addInteractionStatistics(), and CGFields::StandardFieldsBinning::addParticleStatistics().
getDensity()
Mdouble CGFields::StandardFields::getDensity () const inline
     {
         return density_;
     }
References density_.
Referenced by addParticleStatistics(), and testCGHandler().
getInteractionForceDensity()
Vec3D CGFields::StandardFields::getInteractionForceDensity () const inline
     {
         return interactionForceDensity_;
     }
References interactionForceDensity_.
Referenced by addContactPointStatistics(), CGFields::StandardFieldsBinning::addParticleStatistics(), and testCGHandler().
getMomentum()
Vec3D CGFields::StandardFields::getMomentum () const inline
     {
         return momentum_;
     }
References momentum_.
Referenced by addParticleStatistics().
getMomentumFlux()
MatrixSymmetric3D CGFields::StandardFields::getMomentumFlux () const inline
     {
         return momentumFlux_;
     }
References momentumFlux_.
Referenced by addParticleStatistics().
getParticleSizeDensity() [1/2]
std::array<Mdouble, 6> CGFields::StandardFields::getParticleSizeDensity () const inline
     {
         return particleSizeDensity_;
     }
References particleSizeDensity_.
getParticleSizeDensity() [2/2]
Mdouble CGFields::StandardFields::getParticleSizeDensity (size_t i) const inline
     {
         return particleSizeDensity_[i];
     }
References i, and particleSizeDensity_.
Referenced by addParticleStatistics().
getParticleSizeMomenta()
std::array< Mdouble, 6 > CGFields::StandardFields::getParticleSizeMomenta () const
 {
     //https://en.wikipedia.org/wiki/Moment_(mathematics)
     auto momenta = particleSizeDensity_;
     for (size_t i = 1; i < particleSizeDensity_.size(); ++i)
     {
         momenta[i] /= particleSizeDensity_[0];
     }
     return momenta;
 }
References i, and particleSizeDensity_.
Referenced by getCentralParticleSizeMomenta().
getSquared()
StandardFields CGFields::StandardFields::getSquared () const
Returns the square of all field values (to calculate standard deviation).
Returns
a CGField containing the square of the values in the current object
 {
     StandardFields P;
     P.volumeFraction_ = mathsFunc::square(volumeFraction_);
     P.density_ = mathsFunc::square(density_);
     P.momentum_ = Vec3D::square(momentum_);
     P.momentumFlux_ = MatrixSymmetric3D::square(momentumFlux_);
     P.contactStress_ = Matrix3D::square(contactStress_);
     P.interactionForceDensity_ = Vec3D::square(interactionForceDensity_);
     P.particleSizeDensity_ = particleSizeDensity_;
     for (auto& p : P.particleSizeDensity_) p *= p;
     return P;
 }
References contactStress_, density_, interactionForceDensity_, momentum_, momentumFlux_, Global_Physical_Variables::P, p, particleSizeDensity_, Matrix3D::square(), MatrixSymmetric3D::square(), mathsFunc::square(), Vec3D::square(), and volumeFraction_.
getStandardisedParticleSizeMomenta()
std::array< Mdouble, 6 > CGFields::StandardFields::getStandardisedParticleSizeMomenta () const
 {
     auto momenta = getCentralParticleSizeMomenta();
     Mdouble std = std::sqrt(momenta[2]);
     momenta[3] /= std * std * std;
     momenta[4] /= std * std * std * std;
     momenta[5] /= std * std * std * std * std;
     return momenta;
 }
References getCentralParticleSizeMomenta(), and sqrt().
Referenced by outputStandardisedParticleSizeMomenta().
getVolumeFraction()
Mdouble CGFields::StandardFields::getVolumeFraction () const inline
     {
         return volumeFraction_;
     }
References volumeFraction_.
Referenced by addParticleStatistics().
isDifferentialField()
static bool CGFields::StandardFields::isDifferentialField () inline static
A bool that determines if the derivative of the CG function has to be computed
     {
         return false;
     }
operator*()
StandardFields CGFields::StandardFields::operator* (Mdouble a) const
Multiplies the field values on the left of the '*' by the scalar value on the right of the '*' and returns the answer.
Parameters
[in] a the scalar that we multiply with
Returns
the CGField to which the multiplied values are written
 {
     StandardFields p;
     p.volumeFraction_ = volumeFraction_ * a;
     p.density_ = density_ * a;
     p.momentum_ = momentum_ * a;
     p.momentumFlux_ = momentumFlux_ * a;
     p.contactStress_ = contactStress_ * a;
     p.interactionForceDensity_ = interactionForceDensity_ * a;
     for (size_t i = 0; i < particleSizeDensity_.size(); ++i)
         p.particleSizeDensity_[i] = particleSizeDensity_[i] * a;
     return p;
 }
References a, contactStress_, density_, i, interactionForceDensity_, momentum_, momentumFlux_, p, particleSizeDensity_, and volumeFraction_.
operator+=()
StandardFields & CGFields::StandardFields::operator+= (const StandardFields & P)
Adds the field values on the RHS to the LHS of the equation.
Parameters
[in] P the CGField that has to be added
Returns
the CGField to which the values are added
 {
     volumeFraction_ += P.volumeFraction_;
     density_ += P.density_;
     momentum_ += P.momentum_;
     momentumFlux_ += P.momentumFlux_;
     contactStress_ += P.contactStress_;
     interactionForceDensity_ += P.interactionForceDensity_;
     for (size_t i = 0; i < particleSizeDensity_.size(); ++i) particleSizeDensity_[i] += P.particleSizeDensity_[i];
     return *this;
 }
References contactStress_, density_, i, interactionForceDensity_, momentum_, momentumFlux_, Global_Physical_Variables::P, particleSizeDensity_, and volumeFraction_.
operator-=()
StandardFields & CGFields::StandardFields::operator-= (const StandardFields & P)
Subtracts the field values on the RHS from the LHS of the equation.
Parameters
[in] P the CGField that has to be subtracted
Returns
the CGField from which the values are subtracted
 {
     volumeFraction_ -= P.volumeFraction_;
     density_ -= P.density_;
     momentum_ -= P.momentum_;
     momentumFlux_ -= P.momentumFlux_;
     contactStress_ -= P.contactStress_;
     interactionForceDensity_ -= P.interactionForceDensity_;
     for (size_t i = 0; i < particleSizeDensity_.size(); ++i) particleSizeDensity_[i] -= P.particleSizeDensity_[i];
     return *this;
 }
References contactStress_, density_, i, interactionForceDensity_, momentum_, momentumFlux_, Global_Physical_Variables::P, particleSizeDensity_, and volumeFraction_.
operator/=()
StandardFields & CGFields::StandardFields::operator/= (Mdouble a)
Divides the field values on the LHS by the RHS of the equation.
Parameters
[in] a the scalar that we divide by
Returns
the CGField to which the divided values are written
 {
     volumeFraction_ /= a;
     density_ /= a;
     momentum_ /= a;
     momentumFlux_ /= a;
     contactStress_ /= a;
     interactionForceDensity_ /= a;
     for (auto& p : particleSizeDensity_) p /= a;
     return *this;
 }
References a, contactStress_, density_, interactionForceDensity_, momentum_, momentumFlux_, p, particleSizeDensity_, and volumeFraction_.
operator=()
StandardFields & CGFields::StandardFields::operator= (const StandardFields & P) default
Copies all field values.
Parameters
[in] P the CGField that has to be copied
Returns
the CGField into which the values are copied
output()
void CGFields::StandardFields::output (std::ostream & os) const
Writes human-readable class content into an output stream, typically a stat file.
Parameters
[in,out] os the ostream into which the data is written.
 {
     os << "VolumeFraction " << volumeFraction_;
     os << " Density " << density_;
     os << " Momentum " << momentum_;
     os << " MomentumFlux " << momentumFlux_;
     os << " ContactStress " << contactStress_;
     os << " InteractionForce " << interactionForceDensity_;
     os << " ParticleSize";
     for (const auto p : particleSizeDensity_) os << ' ' << p;
 }
References contactStress_, density_, interactionForceDensity_, momentum_, momentumFlux_, p, particleSizeDensity_, and volumeFraction_.
outputStandardisedParticleSizeMomenta()
void CGFields::StandardFields::outputStandardisedParticleSizeMomenta (std::ostream & os) const
 {
     //https://en.wikipedia.org/wiki/Moment_%28mathematics%29#Higher_moments
     auto momenta = getStandardisedParticleSizeMomenta();
     os << "Particle number: " << momenta[0] << '\n';
     os << "Mean radius: " << momenta[1] << '\n';
     os << "Standard deviation: " << std::sqrt(momenta[2]) << '\n';
     os << "Skewness: " << momenta[3] << '\n'; //left- or right-sided
     os << "Kurtosis: " << momenta[4] << '\n'; //heavy or light tailed (3 for normal distribution)
     os << "5-th moment: " << momenta[5] << '\n'; //hyper skewness (0 for normal dist)
 }
References getStandardisedParticleSizeMomenta(), and sqrt().
setContactStress()
void CGFields::StandardFields::setContactStress (Matrix3D contactStress) inline protected
     {
         contactStress_ = contactStress;
     }
References contactStress_.
Referenced by CGFields::StandardFieldsBinning::setFields().
setCylindricalFields() [1/2]
void CGFields::StandardFields::setCylindricalFields (const BaseInteraction & c, IntegralType type)
 {
     setFields(c, type);
     contactStress_ = contactStress_.getCylindricalTensorField(c.getContactPoint());
     interactionForceDensity_ = interactionForceDensity_.getCylindricalTensorField(c.getContactPoint());
 }
References calibrate::c, contactStress_, Matrix3D::getCylindricalTensorField(), Vec3D::getCylindricalTensorField(), interactionForceDensity_, setFields(), and compute_granudrum_aor::type.
setCylindricalFields() [2/2]
void CGFields::StandardFields::setCylindricalFields (const BaseParticle & p)
 {
     setFields(p);
     momentum_ = momentum_.getCylindricalTensorField(p.getPosition());
     momentumFlux_ = momentumFlux_.getCylindricalTensorField(p.getPosition());
 }
References MatrixSymmetric3D::getCylindricalTensorField(), Vec3D::getCylindricalTensorField(), momentum_, momentumFlux_, p, and setFields().
setFields() [1/2]
void CGFields::StandardFields::setFields (const BaseInteraction & c, IntegralType type)
 {
     //P is always real, but I not
     if (type == IntegralType::I_TO_P)
     {
         contactStress_ = Matrix3D::dyadic(c.getForce(), c.getIP());
     }
     else if (type == IntegralType::I_TO_CONTACT)
     {
         interactionForceDensity_ = -c.getForce();
         contactStress_ = Matrix3D::dyadic(c.getForce(), c.getIC());
     }
     else
     {
         interactionForceDensity_ = c.getForce();
         contactStress_ = Matrix3D::dyadic(c.getForce(), c.getCP());
     }
 }
References calibrate::c, contactStress_, Matrix3D::dyadic(), I_TO_CONTACT, I_TO_P, interactionForceDensity_, and compute_granudrum_aor::type.
Referenced by setCylindricalFields(), and CGFields::StandardFieldsBinning::setFields().
setFields() [2/2]
void CGFields::StandardFields::setFields (const BaseParticle & p)
 {
     volumeFraction_ = p.getVolume();
     density_ = p.getMass();
     momentum_ = p.getVelocity() * p.getMass();
     momentumFlux_ = MatrixSymmetric3D::selfDyadic(p.getVelocity()) * p.getMass();
     Mdouble particleSize = 1.0;
     for (auto& ps : particleSizeDensity_)
     {
         ps = particleSize;
         particleSize *= p.getRadius();
     }
 }
References density_, momentum_, momentumFlux_, p, particleSizeDensity_, ps, MatrixSymmetric3D::selfDyadic(), and volumeFraction_.
setInteractionForceDensity()
void CGFields::StandardFields::setInteractionForceDensity (Vec3D interactionForceDensity) inline protected
     {
         interactionForceDensity_ = interactionForceDensity;
     }
References interactionForceDensity_.
Referenced by CGFields::StandardFieldsBinning::setFields().
setZero()
void CGFields::StandardFields::setZero ()
Sets all fields to zero.
 {
     volumeFraction_ = 0.0;
     density_ = 0.0;
     momentum_.setZero();
     momentumFlux_.setZero();
     contactStress_.setZero();
     interactionForceDensity_.setZero();
     for (auto& p : particleSizeDensity_) p = 0;
 }
References contactStress_, density_, interactionForceDensity_, momentum_, momentumFlux_, p, particleSizeDensity_, Matrix3D::setZero(), MatrixSymmetric3D::setZero(), Vec3D::setZero(), and volumeFraction_.
Referenced by StandardFields(), and CGFields::StandardFieldsBinning::StandardFieldsBinning().
write()
void CGFields::StandardFields::write (std::ostream & os) const
Writes class content into an output stream, typically a stat file.
Parameters
[in,out] os the ostream into which the data is written.
 {
     os << volumeFraction_;
     os << ' ' << density_;
     os << ' ' << momentum_;
     os << ' ' << momentumFlux_;
     os << ' ' << contactStress_;
     os << ' ' << interactionForceDensity_;
     for (const auto p : particleSizeDensity_) os << ' ' << p;
 }
References contactStress_, density_, interactionForceDensity_, momentum_, momentumFlux_, p, particleSizeDensity_, and volumeFraction_.
writeNames()
void CGFields::StandardFields::writeNames (std::ostream & os, unsigned countVariables) static
Parameters
[in,out] os the ostream into which the data is written.
[in] countVariables The number of variables in the field (including time), e.g. 1 for O, 4 for XYZ
 {
     os << countVariables + 1 << ":VolumeFraction "; //volume
     os << countVariables + 2 << ":Density "; //mass
     os << countVariables + 3 << '-' << countVariables + 5 << ":Momentum ";
     os << countVariables + 6 << '-' << countVariables + 11 << ":MomentumFlux ";
     os << countVariables + 12 << '-' << countVariables + 20 << ":ContactStress ";
     os << countVariables + 21 << '-' << countVariables + 23 << ":InteractionForce ";
     os << countVariables + 24 << '-' << countVariables + 29 << ":ParticleSize ";
 }
Member Data Documentation
contactStress_
Matrix3D CGFields::StandardFields::contactStress_ private
Contact stress, computed as the sum over all contacts between particle i and particle/wall/fixed particle j
\[\mathbf \sigma^{c}(\vec r,t)=\sum_{ij} \vec f_{ij} \otimes \vec l_{ij} \psi(\vec r,\vec r_i,\vec r_j),\]
with contact force \(\vec f_{ij}\), branch vector \(\vec l_{ij}= \vec c_{ij}-\vec r_i\), particle position \(\vec r_i\), contact point \(\vec c_{ij}\), and cg line integral \(\psi(\vec r,\vec r_i,\vec r_j)\), see CGFunctions::Gauss::evaluateCGIntegral.
Referenced by addContactStress(), addInteractionStatistics(), getContactStress(), getSquared(), operator*(), operator+=(), operator-=(), operator/=(), output(), setContactStress(), setCylindricalFields(), setFields(), setZero(), and write().
density_
Mdouble CGFields::StandardFields::density_ private
(Mass) density, computed as the sum over all particles i
\[\rho(\vec r,t)=\sum_i m_i \phi(\vec r,\vec r_i)\]
with particle mass m_i and cg function \(\phi(\vec r,\vec r_i),\), see CGFunctions::Gauss::evaluateCGFunction.
Referenced by addParticleStatistics(), getDensity(), getSquared(), operator*(), operator+=(), operator-=(), operator/=(), output(), setFields(), setZero(), and write().
interactionForceDensity_
Vec3D CGFields::StandardFields::interactionForceDensity_ private
Interaction force density, computed as the sum over all contacts between particle i and (external) wall/fixed particle j
\[\vec{IFD}(\vec r,t)=\sum_{ij} f_{ij} \phi(\vec r,\vec c_{ij}),\]
with contact force \(\vec f_{ij}\) and cg function \(\phi(\vec r,\vec r_i)\), see CGFunctions::Gauss::evaluateCGFunction.
Referenced by addContactPointStatistics(), addInteractionForceDensity(), getInteractionForceDensity(), getSquared(), operator*(), operator+=(), operator-=(), operator/=(), output(), setCylindricalFields(), setFields(), setInteractionForceDensity(), setZero(), and write().
momentum_
Vec3D CGFields::StandardFields::momentum_ private
Momentum, computed as the sum over all particles i
\[\vec j(\vec r,t)=\sum_i m_i \vec v_i\phi(\vec r,\vec r_i),\]
with particle momentum \(m_i\vec v_i\) and cg function \(\phi(\vec r,\vec r_i)\), see CGFunctions::Gauss::evaluateCGFunction.
Velocity can be calculated in a post-processing step from momentum and density as
\[\vec V(\vec r,t) = \frac{\vec j(\vec r,t)}{\rho(\vec r,t)}.\]
Referenced by addParticleStatistics(), getMomentum(), getSquared(), operator*(), operator+=(), operator-=(), operator/=(), output(), setCylindricalFields(), setFields(), setZero(), and write().
momentumFlux_
MatrixSymmetric3D CGFields::StandardFields::momentumFlux_ private
Momentum, computed as the sum over all particles i
\[\mathbf k(\vec r,t)=\sum_i m_i \vec v_i \otimes \vec v_i\phi(\vec r,\vec r_i),\]
with particle momentum flux \(m_i\vec v_i \otimes \vec v_i\) and cg function \(\phi(\vec r,\vec r_i)\), see CGFunctions::Gauss::evaluateCGFunction.
Kinetic stress can be calculated in a post-processing step from momentum flux and density as
\[\mathbf \sigma^{k} = \mathbf k - \rho \vec V \otimes \vec V.\]
Referenced by addParticleStatistics(), getMomentumFlux(), getSquared(), operator*(), operator+=(), operator-=(), operator/=(), output(), setCylindricalFields(), setFields(), setZero(), and write().
particleSizeDensity_
std::array<Mdouble, 6> CGFields::StandardFields::particleSizeDensity_ private
Density of particle size, and powers of particle size,
\[ \vec{PS}_k(\vec r,t)= \sum_i r_i^k \phi(\vec r),\]
with radius \(r_i\).
Used to compute the first five moments of the particle size distribution,
\[ <r^k>(\vec r,t)= \vec{PS}_k / \vec{PS}_0, \]
with \(\vec{PS}_0\) denoting the number density.
Referenced by addParticleStatistics(), getParticleSizeDensity(), getParticleSizeMomenta(), getSquared(), operator*(), operator+=(), operator-=(), operator/=(), output(), setFields(), setZero(), and write().
volumeFraction_
Mdouble CGFields::StandardFields::volumeFraction_ private
Particle volume fraction, computed as the sum over all particles i
\[\nu(\vec r,t)=\sum_i V_i \phi(\vec r,\vec r_i),\]
with particle volume V_i and cg function \(\phi(\vec r,\vec r_i)\), see CGFunctions::Gauss::evaluateCGFunction.
Referenced by addParticleStatistics(), getSquared(), getVolumeFraction(), operator*(), operator+=(), operator-=(), operator/=(), output(), setFields(), setZero(), and write().
The documentation for this class was generated from the following files:
StandardFields.h
StandardFields.cc