MercuryDPM: Eigen::internal::matrix_function_compute< MatrixType, 1 > Struct Template Reference
Eigen::internal::matrix_function_compute< MatrixType, 1 > Struct Template Reference
Partial specialization of MatrixFunction for complex matrices.
#include <MatrixFunction.h>
Static Public Member Functions
template<typename MatA , typename AtomicType , typename ResultType >
static void run (const MatA &A, AtomicType &atomic, ResultType &result)
Detailed Description
template<typename MatrixType>
struct Eigen::internal::matrix_function_compute< MatrixType, 1 >
Partial specialization of MatrixFunction for complex matrices.
Member Function Documentation
run()
template<typename MatrixType > template<typename MatA , typename AtomicType , typename ResultType > static void Eigen::internal::matrix_function_compute< MatrixType, 1 >::run (const MatA & A, AtomicType & atomic, ResultType & result) inline static
{
     typedef internal::traits<MatrixType> Traits;
     // compute Schur decomposition of A
     const ComplexSchur<MatrixType> schurOfA(A);
     eigen_assert(schurOfA.info() == Success);
     MatrixType T = schurOfA.matrixT();
     MatrixType U = schurOfA.matrixU();
     // partition eigenvalues into clusters of ei'vals "close" to each other
     std::list<std::list<Index> > clusters;
     matrix_function_partition_eigenvalues(T.diagonal(), clusters);
     // compute size of each cluster
     Matrix<Index, Dynamic, 1> clusterSize;
     matrix_function_compute_cluster_size(clusters, clusterSize);
     // blockStart[i] is row index at which block corresponding to i-th cluster starts
     Matrix<Index, Dynamic, 1> blockStart;
     matrix_function_compute_block_start(clusterSize, blockStart);
     // compute map so that eivalToCluster[i] = j means that i-th ei'val is in j-th cluster
     Matrix<Index, Dynamic, 1> eivalToCluster;
     matrix_function_compute_map(T.diagonal(), clusters, eivalToCluster);
     // compute permutation which groups ei'vals in same cluster together
     Matrix<Index, Traits::RowsAtCompileTime, 1> permutation;
     matrix_function_compute_permutation(blockStart, eivalToCluster, permutation);
     // permute Schur decomposition
     matrix_function_permute_schur(permutation, U, T);
     // compute result
     MatrixType fT;  // matrix function applied to T
     matrix_function_compute_block_atomic(T, atomic, blockStart, clusterSize, fT);
     matrix_function_compute_above_diagonal(T, blockStart, clusterSize, fT);
     result = U * (fT.template triangularView<Upper>() * U.adjoint());
   }
References eigen_assert, Eigen::internal::matrix_function_compute_above_diagonal(), Eigen::internal::matrix_function_compute_block_atomic(), Eigen::internal::matrix_function_compute_block_start(), Eigen::internal::matrix_function_compute_cluster_size(), Eigen::internal::matrix_function_compute_map(), Eigen::internal::matrix_function_compute_permutation(), Eigen::internal::matrix_function_partition_eigenvalues(), Eigen::internal::matrix_function_permute_schur(), schurOfA(), Eigen::Success, and RachelsAdvectionDiffusion::U.
The documentation for this struct was generated from the following file:
MatrixFunction.h