MercuryDPM: Combtooth Class Reference
Combtooth Class Reference
#include <Combtooth.h>
Public Member Functions
Combtooth ()
Default constructor.
Combtooth (const Combtooth &ct)
Copy constructor.
~Combtooth () override
Default destructor.
void set (Vec3D axis, Vec3D position, Mdouble radius)
Set.
Combtooth * copy () const override
Copy.
bool getDistanceAndNormal (const BaseParticle &p, Mdouble &distance, Vec3D &normal_return) const override
Pure virtual function that computes the distance of a BaseParticle to this wall and returns the normal of this wall if there is a collision.
BaseInteraction * getInteractionWith (BaseParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler) override
Returns the interaction between this wall and a given particle, nullptr if there is no interaction.
void read (std::istream &is) override
Function that reads a BaseWall from an input stream, usually a restart file.
void write (std::ostream &os) const override
Function that writes a BaseWall to an output stream, usually a restart file.
std::string getName () const override
A purely virtual function.
Public Member Functions inherited from BaseWall
BaseWall ()
Default constructor.
BaseWall (const BaseWall &w)
Copy constructor.
~BaseWall () override
Default destructor.
virtual bool getDistanceNormalOverlap (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual bool getDistanceNormalOverlapSuperquadric (const SuperQuadricParticle &p, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual Vec3D getFurthestPointSuperQuadric (const Vec3D &normalBodyFixed, const Vec3D &axes, Mdouble eps1, Mdouble eps2) const
virtual void setHandler (WallHandler *handler)
A function which sets the WallHandler for this BaseWall.
WallHandler * getHandler () const
A function which returns the WallHandler that handles this BaseWall.
void setIndSpecies (unsigned int indSpecies) override
Define the species of this wall using the index of the species in the SpeciesHandler in this DPMBase.
void setSpecies (const ParticleSpecies *species)
Defines the species of the current wall.
bool isFixed () const override
void setForceControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity={0, 0, 0})
Slowly adjusts the force on a wall towards a specified goal, by adjusting (prescribing) the velocity of the wall.
virtual bool isLocal (Vec3D &min, Vec3D &max) const
bool getLinePlaneIntersect (Vec3D &intersect, const Vec3D &p0, const Vec3D &p1, const Vec3D &n, const Vec3D &p)
bool isInsideWallVTK (const Vec3D &point, const Vec3D &normal, const Vec3D &position) const
void projectOntoWallVTK (Vec3D &point0, const Vec3D &point1, const Vec3D &normal, const Vec3D &position) const
void intersectVTK (std::vector< Vec3D > &points, Vec3D normal, Vec3D position) const
virtual BaseInteraction * getInteractionWithSuperQuad (SuperQuadricParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler)
virtual void writeVTK (VTKContainer &vtk) const
void getVTK (std::vector< Vec3D > &points, std::vector< std::vector< double >> &triangleStrips)
const Vec3D getAxis () const
virtual void actionsOnRestart ()
No implementation but can be overidden in its derived classes.
virtual void actionsAfterParticleGhostUpdate ()
No implementation but can be overidden in its derived classes.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
virtual void handleParticleRemoval (unsigned int id)
Handles the addition of particles to the particleHandler.
virtual void checkInteractions (InteractionHandler *interactionHandler, unsigned int timeStamp)
Check if all interactions are valid.
bool getVTKVisibility () const
void setVTKVisibility (bool vtkVisibility)
void addRenderedWall (BaseWall *w)
BaseWall * getRenderedWall (size_t i) const
std::vector< BaseWall * > getRenderedWalls () const
void removeRenderedWalls ()
void renderWall (VTKContainer &vtk)
void addParticlesAtWall (unsigned numElements=50)
void setVelocityControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity)
virtual void writeWallDetailsVTK (VTKData &data) const
virtual void computeWear ()
Public Member Functions inherited from BaseInteractable
BaseInteractable ()
Default BaseInteractable constructor.
BaseInteractable (const BaseInteractable &p)
Copy constructor.
~BaseInteractable () override
Destructor, it simply destructs the BaseInteractable and all the objects it contains.
unsigned int getIndSpecies () const
Returns the index of the species associated with the interactable object.
const ParticleSpecies * getSpecies () const
Returns a pointer to the species of this BaseInteractable.
void setSpecies (const ParticleSpecies *species)
Sets the species of this BaseInteractable.
const Vec3D & getForce () const
Returns the force on this BaseInteractable.
const Vec3D & getTorque () const
Returns the torque on this BaseInteractable.
void setForce (const Vec3D &force)
Sets the force on this BaseInteractable.
void setTorque (const Vec3D &torque)
Sets the torque on this BaseInteractable.
void addForce (const Vec3D &addForce)
Adds an amount to the force on this BaseInteractable.
void addTorque (const Vec3D &addTorque)
Adds an amount to the torque on this BaseInteractable.
virtual void resetForceTorque (int numberOfOMPthreads)
void sumForceTorqueOMP ()
const Vec3D & getPosition () const
Returns the position of this BaseInteractable.
const Quaternion & getOrientation () const
Returns the orientation of this BaseInteractable.
virtual void setPosition (const Vec3D &position)
Sets the position of this BaseInteractable.
void setOrientationViaNormal (Vec3D normal)
Sets the orientation of this BaseInteractable by defining the vector that results from the rotation of the (1,0,0) vector.
void setOrientationViaEuler (Vec3D eulerAngle)
Sets the orientation of this BaseInteractable by defining the euler angles.
virtual void setOrientation (const Quaternion &orientation)
Sets the orientation of this BaseInteractable.
virtual void move (const Vec3D &move)
Moves this BaseInteractable by adding an amount to the position.
virtual void rotate (const Vec3D &angularVelocityDt)
Rotates this BaseInteractable.
const std::vector< BaseInteraction * > & getInteractions () const
Returns a list of interactions which belong to this interactable.
void addInteraction (BaseInteraction *I)
Adds an interaction to this BaseInteractable.
bool removeInteraction (BaseInteraction *I)
Removes an interaction from this BaseInteractable.
void copyInteractionsForPeriodicParticles (const BaseInteractable &p)
Copies interactions to this BaseInteractable whenever a periodic copy made.
void setVelocity (const Vec3D &velocity)
set the velocity of the BaseInteractable.
void setAngularVelocity (const Vec3D &angularVelocity)
set the angular velocity of the BaseInteractble.
void addVelocity (const Vec3D &velocity)
adds an increment to the velocity.
void addAngularVelocity (const Vec3D &angularVelocity)
add an increment to the angular velocity.
virtual const Vec3D & getVelocity () const
Returns the velocity of this interactable.
virtual const Vec3D & getAngularVelocity () const
Returns the angular velocity of this interactable.
void setPrescribedPosition (const std::function< Vec3D(double)> &prescribedPosition)
Allows the position of an infinite mass interactable to be prescribed.
void applyPrescribedPosition (double time)
Computes the position from the user defined prescribed position function.
void setPrescribedVelocity (const std::function< Vec3D(double)> &prescribedVelocity)
Allows the velocity of an infinite mass interactable to be prescribed.
void applyPrescribedVelocity (double time)
Computes the velocity from the user defined prescribed velocity function.
void setPrescribedOrientation (const std::function< Quaternion(double)> &prescribedOrientation)
Allows the orientation of the infinite mass interactbale to be prescribed.
void applyPrescribedOrientation (double time)
Computes the orientation from the user defined prescribed orientation function.
void setPrescribedAngularVelocity (const std::function< Vec3D(double)> &prescribedAngularVelocity)
Allows the angular velocity of the infinite mass interactable to be prescribed.
void applyPrescribedAngularVelocity (double time)
Computes the angular velocity from the user defined prescribed angular velocity.
virtual const Vec3D getVelocityAtContact (const Vec3D &contact) const
Returns the velocity at the contact point, use by many force laws.
void integrateBeforeForceComputation (double time, double timeStep)
This is part of integrate routine for objects with infinite mass.
void integrateAfterForceComputation (double time, double timeStep)
This is part of the integration routine for objects with infinite mass.
virtual Mdouble getInvMass () const
virtual Mdouble getCurvature (const Vec3D &labFixedCoordinates) const
virtual bool isFaceContact (const Vec3D &normal) const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
Vec3D axis_
Vec3D position_
Mdouble radius_
Additional Inherited Members
Static Public Member Functions inherited from BaseWall
static void addToVTK (const std::vector< Vec3D > &points, VTKContainer &vtk)
Takes the points provided and adds a triangle strip connecting these points to the vtk container.
Constructor & Destructor Documentation
Combtooth() [1/2]
Combtooth::Combtooth ()
Default constructor.
 {
     axis_ = Vec3D(0, 0, 1);
     position_ = Vec3D(0, 0, 0);
     radius_ = 1;
 }
References axis_, position_, and radius_.
Referenced by copy().
Combtooth() [2/2]
Combtooth::Combtooth (const Combtooth & ct)
Copy constructor.
                                            : BaseWall(other)
 {
     axis_ = other.axis_;
     position_ = other.position_;
     radius_ = other.radius_;
     /* Normalise axis_ */
     axis_ /= axis_.getLength();
 }
References axis_, Vec3D::getLength(), position_, and radius_.
~Combtooth()
Combtooth::~Combtooth () override default
Default destructor.
Member Function Documentation
copy()
Combtooth * Combtooth::copy () const override virtual
Copy.
Implements BaseWall.
 {
     return new Combtooth(*this);
 }
References Combtooth().
getDistanceAndNormal()
bool Combtooth::getDistanceAndNormal (const BaseParticle & P, Mdouble & distance, Vec3D & normal_return) const override virtual
Pure virtual function that computes the distance of a BaseParticle to this wall and returns the normal of this wall if there is a collision.
Beware, the distance and normal are output parameters, not return values!
Parameters
[in] P Reference to the BaseParticle we want to compute the distance to the BaseWall of.
[out] distance Distance of the BaseParticle to the BaseWall.
[out] normal_return The normal of the wall. Is only given if there is a collision.
Returns
A boolean which indicates if there is a collision between the BaseParticle and the wall.
Implements BaseWall.
 {
     // distance between x0 and the *surface* (not the axis)
     distance = sqrt(
             pow((p.getPosition() - position_).getLength(), 2)
             - pow(Vec3D::dot(p.getPosition() - position_, axis_), 2)
     ) - radius_;
     if (distance >= p.getWallInteractionRadius(this))
         return false;
     else
     {
         Vec3D axisContactPoint; // the point on the axis closest to the particle
         axisContactPoint = position_ + Vec3D::dot(p.getPosition() - position_, axis_) * axis_;
         normal_return = (axisContactPoint - p.getPosition()); // inward-pointing normal
         normal_return /= normal_return.getLength();
         return true;
     }
 }
References axis_, Vec3D::dot(), Vec3D::getLength(), p, position_, Eigen::bfloat16_impl::pow(), radius_, and sqrt().
Referenced by getInteractionWith().
getInteractionWith()
BaseInteraction * Combtooth::getInteractionWith (BaseParticle * p, unsigned timeStamp, InteractionHandler * interactionHandler) override virtual
Returns the interaction between this wall and a given particle, nullptr if there is no interaction.
Parameters
[in] p Pointer to the BaseParticle which we want to check the interaction for.
[in] timeStamp The time at which we want to look at the interaction.
[in] interactionHandler A pointer to the InteractionHandler in which the interaction can be found.
Returns
A pointer to the BaseInteraction that happened between this BaseWall and the BaseParticle at the timeStamp.
Todo:
Quick hack JMF2 please clean up with the new way
Reimplemented from BaseWall.
 {
     Mdouble distance;
     Vec3D normal;
     if (getDistanceAndNormal(*p, distance, normal))
     {
         BaseInteraction* c = interactionHandler->getInteraction(p, this, timeStamp);
         c->setNormal(-normal); // outward-pointing normal to cylinder
         c->setDistance(distance);
         c->setOverlap(p->getRadius() - distance);
         c->setContactPoint(p->getPosition() - (p->getRadius() - 0.5 * c->getOverlap()) * c->getNormal());
         return c;
     }
     else
         return nullptr;
 }
References calibrate::c, getDistanceAndNormal(), InteractionHandler::getInteraction(), WallFunction::normal(), and p.
getName()
std::string Combtooth::getName () const override virtual
A purely virtual function.
Implements BaseObject.
 {
     return "Combtooth";
 }
read()
void Combtooth::read (std::istream & is) override virtual
Function that reads a BaseWall from an input stream, usually a restart file.
The BaseWall takes no more information than for a BaseInteractable. (A derived class' read method does most of the work.)
Parameters
[in] is - The input stream from which the BaseWall is read.
Reimplemented from BaseWall.
 {
     BaseWall::read(is);
     std::string dummy;
     is >> dummy >> axis_
        >> dummy >> position_
        >> dummy >> radius_;
 }
References axis_, position_, radius_, BaseWall::read(), and oomph::Global_string_for_annotation::string().
set()
void Combtooth::set (Vec3D axis, Vec3D position, Mdouble radius)
Set.
 {
     axis_ = axis / axis.getLength();
     position_ = position;
     radius_ = radius;
 }
References axis_, Vec3D::getLength(), position_, UniformPSDSelfTest::radius, and radius_.
write()
void Combtooth::write (std::ostream & os) const override virtual
Function that writes a BaseWall to an output stream, usually a restart file.
Reimplemented from BaseWall.
 {
     BaseWall::write(os);
     os << " axis " << axis_
        << " position " << position_
        << " radius " << radius_;
 }
References axis_, position_, radius_, and BaseWall::write().
Member Data Documentation
axis_
Vec3D Combtooth::axis_ private
Referenced by Combtooth(), getDistanceAndNormal(), read(), set(), and write().
position_
Vec3D Combtooth::position_ private
Referenced by Combtooth(), getDistanceAndNormal(), read(), set(), and write().
radius_
Mdouble Combtooth::radius_ private
Referenced by Combtooth(), getDistanceAndNormal(), read(), set(), and write().
The documentation for this class was generated from the following files:
Combtooth.h
Combtooth.cc