MercuryDPM: Eigen::internal::unary_evaluator< SparseView< Product< Lhs, Rhs, Options > >, IteratorBased > Struct Template Reference
Eigen::internal::unary_evaluator< SparseView< Product< Lhs, Rhs, Options > >, IteratorBased > Struct Template Reference
#include <SparseProduct.h>
Public Types
typedef SparseView< Product< Lhs, Rhs, Options > > XprType
typedef XprType::PlainObject PlainObject
typedef evaluator< PlainObject > Base
Public Types inherited from Eigen::internal::evaluator< Product< Lhs, Rhs, DefaultProduct >::PlainObject >
typedef unary_evaluator< Product< Lhs, Rhs, DefaultProduct >::PlainObject > Base
Public Member Functions
unary_evaluator (const XprType &xpr)
Public Member Functions inherited from Eigen::internal::evaluator< Product< Lhs, Rhs, DefaultProduct >::PlainObject >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE evaluator (const Product< Lhs, Rhs, DefaultProduct >::PlainObject &xpr)
Protected Attributes
PlainObject m_result
Member Typedef Documentation
Base
template<typename Lhs , typename Rhs , int Options> typedef evaluator<PlainObject> Eigen::internal::unary_evaluator< SparseView< Product< Lhs, Rhs, Options > >, IteratorBased >::Base
PlainObject
template<typename Lhs , typename Rhs , int Options> typedef XprType::PlainObject Eigen::internal::unary_evaluator< SparseView< Product< Lhs, Rhs, Options > >, IteratorBased >::PlainObject
XprType
template<typename Lhs , typename Rhs , int Options> typedef SparseView<Product<Lhs, Rhs, Options> > Eigen::internal::unary_evaluator< SparseView< Product< Lhs, Rhs, Options > >, IteratorBased >::XprType
Constructor & Destructor Documentation
unary_evaluator()
template<typename Lhs , typename Rhs , int Options> Eigen::internal::unary_evaluator< SparseView< Product< Lhs, Rhs, Options > >, IteratorBased >::unary_evaluator (const XprType & xpr) inline explicit
                                                : m_result(xpr.rows(), xpr.cols()) {
     using std::abs;
     internal::construct_at<Base>(this, m_result);
     typedef typename nested_eval<Lhs, Dynamic>::type LhsNested;
     typedef typename nested_eval<Rhs, Dynamic>::type RhsNested;
     LhsNested lhsNested(xpr.nestedExpression().lhs());
     RhsNested rhsNested(xpr.nestedExpression().rhs());
     internal::sparse_sparse_product_with_pruning_selector<remove_all_t<LhsNested>, remove_all_t<RhsNested>,
                                                           PlainObject>::run(lhsNested, rhsNested, m_result,
                                                                             abs(xpr.reference()) * xpr.epsilon());
   }
References abs(), Eigen::SparseView< MatrixType >::epsilon(), Eigen::SparseView< MatrixType >::nestedExpression(), Eigen::SparseView< MatrixType >::reference(), and Eigen::run().
Member Data Documentation
m_result
template<typename Lhs , typename Rhs , int Options> PlainObject Eigen::internal::unary_evaluator< SparseView< Product< Lhs, Rhs, Options > >, IteratorBased >::m_result protected
The documentation for this struct was generated from the following file:
SparseProduct.h