MercuryDPM: Eigen::internal::cross3_impl< Architecture::Target, VectorLhs, VectorRhs, float, true > Struct Template Reference
Eigen::internal::cross3_impl< Architecture::Target, VectorLhs, VectorRhs, float, true > Struct Template Reference
#include <Geometry_SIMD.h>
Public Types
using DstPlainType = typename plain_matrix_type< VectorLhs >::type
Static Public Member Functions
static DstPlainType run (const VectorLhs &lhs, const VectorRhs &rhs)
Static Public Attributes
static constexpr int DstAlignment = evaluator<DstPlainType>::Alignment
static constexpr int LhsAlignment = evaluator<VectorLhs>::Alignment
static constexpr int RhsAlignment = evaluator<VectorRhs>::Alignment
Member Typedef Documentation
DstPlainType
template<typename VectorLhs , typename VectorRhs > using Eigen::internal::cross3_impl< Architecture::Target, VectorLhs, VectorRhs, float, true >::DstPlainType = typename plain_matrix_type<VectorLhs>::type
Member Function Documentation
run()
template<typename VectorLhs , typename VectorRhs > static DstPlainType Eigen::internal::cross3_impl< Architecture::Target, VectorLhs, VectorRhs, float, true >::run (const VectorLhs & lhs, const VectorRhs & rhs) inline static
{
     evaluator<VectorLhs> lhs_eval(lhs);
     evaluator<VectorRhs> rhs_eval(rhs);
     Packet4f a = lhs_eval.template packet<LhsAlignment, Packet4f>(0);
     Packet4f b = rhs_eval.template packet<RhsAlignment, Packet4f>(0);
     Packet4f mul1 = pmul(vec4f_swizzle1(a, 1, 2, 0, 3), vec4f_swizzle1(b, 2, 0, 1, 3));
     Packet4f mul2 = pmul(vec4f_swizzle1(a, 2, 0, 1, 3), vec4f_swizzle1(b, 1, 2, 0, 3));
     DstPlainType res;
     pstoret<float, Packet4f, DstAlignment>(res.data(), psub(mul1, mul2));
     // Ensure last component is 0 in case original a or b contain inf/nan.
     res[3] = 0.0f;
     return res;
   }
References a, b, Eigen::internal::pmul(), Eigen::internal::psub(), res, and Eigen::internal::vec4f_swizzle1().
Member Data Documentation
DstAlignment
template<typename VectorLhs , typename VectorRhs > constexpr int Eigen::internal::cross3_impl< Architecture::Target, VectorLhs, VectorRhs, float, true >::DstAlignment = evaluator<DstPlainType>::Alignment static constexpr
LhsAlignment
template<typename VectorLhs , typename VectorRhs > constexpr int Eigen::internal::cross3_impl< Architecture::Target, VectorLhs, VectorRhs, float, true >::LhsAlignment = evaluator<VectorLhs>::Alignment static constexpr
RhsAlignment
template<typename VectorLhs , typename VectorRhs > constexpr int Eigen::internal::cross3_impl< Architecture::Target, VectorLhs, VectorRhs, float, true >::RhsAlignment = evaluator<VectorRhs>::Alignment static constexpr
The documentation for this struct was generated from the following file:
Geometry_SIMD.h