MercuryDPM: oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations Class Reference
oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations Class Reference abstract
Refineable version of the Axisymmetric Navier–Stokes equations.
#include <generalised_newtonian_refineable_axisym_navier_stokes_elements.h>
Public Member Functions
RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations ()
Empty Constructor.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
double geometric_jacobian (const Vector< double > &x)
Fill in the geometric Jacobian, which in this case is r.
void further_build ()
Further build: pass the pointers down to the sons.
void dinterpolated_u_axi_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
Public Member Functions inherited from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations
GeneralisedNewtonianAxisymmetricNavierStokesEquations ()
Constructor: NULL the body force and source function.
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const double & re_invro () const
Global Reynolds number multiplied by inverse Rossby number.
double *& re_invro_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
GeneralisedNewtonianConstitutiveEquation< 3 > *& constitutive_eqn_pt ()
Access function for the constitutive equation pointer.
void use_current_strainrate_to_compute_second_invariant ()
Switch to fully implict evaluation of non-Newtonian const eqn.
void use_extrapolated_strainrate_to_compute_second_invariant ()
Use extrapolation for non-Newtonian const eqn.
virtual unsigned npres_axi_nst () const =0
Function to return number of pressure degrees of freedom.
virtual unsigned u_index_axi_nst (const unsigned &i) const
unsigned u_index_nst (const unsigned &i) const
unsigned n_u_nst () const
double du_dt_axi_nst (const unsigned &n, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
virtual double p_axi_nst (const unsigned &n_p) const =0
virtual int p_nodal_index_axi_nst () const
Which nodal value represents the pressure?
double pressure_integral () const
Integral of pressure over element.
void max_and_min_invariant_and_viscosity (double &min_invariant, double &max_invariant, double &min_viscosity, double &max_viscosity) const
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
void strain_rate (const unsigned &t, const Vector< double > &s, DenseMatrix< double > &strain_rate) const
virtual void extrapolated_strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
virtual void extrapolated_strain_rate (const unsigned &ipt, DenseMatrix< double > &strain_rate) const
void traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction) const
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
std::string scalar_name_paraview (const unsigned &i) const
void point_output_data (const Vector< double > &s, Vector< double > &data)
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &nplot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Compute the element's residual Vector.
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
void interpolated_u_axi_nst (const Vector< double > &s, Vector< double > &veloc) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_axi_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_axi_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_p_axi_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_duds_axi_nst (const Vector< double > &s, const unsigned &i, const unsigned &j) const
double interpolated_dudx_axi_nst (const Vector< double > &s, const unsigned &i, const unsigned &j) const
double interpolated_dudt_axi_nst (const Vector< double > &s, const unsigned &i) const
double interpolated_d_dudx_dX_axi_nst (const Vector< double > &s, const unsigned &p, const unsigned &q, const unsigned &i, const unsigned &k) const
double compute_physical_size () const
Compute the volume of the element.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::NavierStokesElementWithDiagonalMassMatrices
NavierStokesElementWithDiagonalMassMatrices ()
Empty constructor.
virtual ~NavierStokesElementWithDiagonalMassMatrices ()
Virtual destructor.
NavierStokesElementWithDiagonalMassMatrices (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken copy constructor.
void operator= (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken assignment operator.
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
virtual unsigned required_nsons () const
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)=0
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void rebuild_from_sons (Mesh *&mesh_pt)=0
virtual void unbuild ()
virtual void deactivate_element ()
virtual bool nodes_built ()
Return true if all the nodes have been built, false if not.
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual unsigned ncont_interpolated_values () const =0
virtual void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
virtual void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)=0
virtual Node * interpolating_node_pt (const unsigned &n, const int &value_id)
virtual double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
virtual Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
virtual unsigned ninterpolating_node (const int &value_id)
virtual unsigned ninterpolating_node_1d (const int &value_id)
virtual void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
virtual void check_integrity (double &max_error)=0
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual RefineableElement * root_element_pt ()
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
virtual void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
virtual void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
Pre-build the element.
virtual void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
virtual void further_setup_hanging_nodes ()
void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
unsigned nshape_controlling_nodes ()
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Public Member Functions inherited from oomph::ElementWithZ2ErrorEstimator
ElementWithZ2ErrorEstimator ()
Default empty constructor.
ElementWithZ2ErrorEstimator (const ElementWithZ2ErrorEstimator &)=delete
Broken copy constructor.
void operator= (const ElementWithZ2ErrorEstimator &)=delete
Broken assignment operator.
virtual unsigned ncompound_fluxes ()
virtual void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
virtual void get_Z2_compound_flux_indices (Vector< unsigned > &flux_index)
virtual unsigned nvertex_node () const =0
Number of vertex nodes in the element.
virtual Node * vertex_node_pt (const unsigned &j) const =0
virtual unsigned nrecovery_order ()=0
Order of recovery shape functions.
Static Public Member Functions
static void pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > &element_pt)
static void unpin_all_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in vector.
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Protected Member Functions
virtual Node * pressure_node_pt (const unsigned &n_p)
virtual void unpin_elemental_pressure_dofs ()=0
Unpin all pressure dofs in the element.
virtual void pin_elemental_redundant_nodal_pressure_dofs ()
Protected Member Functions inherited from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations
virtual int p_local_eqn (const unsigned &n) const =0
virtual double dshape_and_dtest_eulerian_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const =0
virtual void pshape_axi_nst (const Vector< double > &s, Shape &psi) const =0
Compute the pressure shape functions at local coordinate s.
virtual void pshape_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const =0
virtual void get_body_force_axi_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
Calculate the body force fct at a given time and Eulerian position.
virtual void get_body_force_gradient_axi_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
double get_source_fct (const double &time, const unsigned &ipt, const Vector< double > &x)
Calculate the source fct at given time and Eulerian position.
virtual void get_source_fct_gradient (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
virtual void get_viscosity_ratio_axisym_nst (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, double &visc_ratio)
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Private Member Functions
void fill_in_generic_residual_contribution_axi_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
void fill_in_generic_dresidual_contribution_axi_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, unsigned flag)
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Attributes inherited from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations
void(*&)(const double &time, const Vector< double > &x, Vector< double > &f) axi_nst_body_force_fct_pt ()
Access function for the body-force pointer.
double(*&)(const double &time, const Vector< double > &x) source_fct_pt ()
Access function for the source-function pointer.
Static Public Attributes inherited from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Protected Attributes inherited from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
double * ReInvFr_pt
double * ReInvRo_pt
Vector< double > * G_pt
Pointer to global gravity Vector.
void(* Body_force_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
Pointer to body force function.
double(* Source_fct_pt)(const double &time, const Vector< double > &x)
Pointer to volumetric source function.
GeneralisedNewtonianConstitutiveEquation< 3 > * Constitutive_eqn_pt
Pointer to the generalised Newtonian constitutive equation.
bool Use_extrapolated_strainrate_to_compute_second_invariant
bool ALE_is_disabled
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number – for plotting/validation purposes.
Static Protected Attributes inherited from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations
static bool Pre_multiply_by_viscosity_ratio
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Detailed Description
Refineable version of the Axisymmetric Navier–Stokes equations.
Constructor & Destructor Documentation
RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations()
oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations () inline
Empty Constructor.
       : GeneralisedNewtonianAxisymmetricNavierStokesEquations(),
         RefineableElement(),
         ElementWithZ2ErrorEstimator()
     {
     }
Member Function Documentation
dinterpolated_u_axi_nst_ddata()
void oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata (const Vector< double > & s, const unsigned & i, Vector< double > & du_ddata, Vector< unsigned > & global_eqn_number) inline virtual
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. Overload the non-refineable version to take account of hanging node information
Reimplemented from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
     {
       // Find number of nodes
       unsigned n_node = this->nnode();
       // Local shape function
       Shape psi(n_node);
       // Find values of shape function at the given local coordinate
       this->shape(s, psi);
       // Find the index at which the velocity component is stored
       const unsigned u_nodal_index = this->u_index_axi_nst(i);
       // Storage for hang info pointer
       HangInfo* hang_info_pt = 0;
       // Storage for global equation
       int global_eqn = 0;
       // Find the number of dofs associated with interpolated u
       unsigned n_u_dof = 0;
       for (unsigned l = 0; l < n_node; l++)
       {
         unsigned n_master = 1;
         // Local bool (is the node hanging)
         bool is_node_hanging = this->node_pt(l)->is_hanging();
         // If the node is hanging, get the number of master nodes
         if (is_node_hanging)
         {
           hang_info_pt = this->node_pt(l)->hanging_pt();
           n_master = hang_info_pt->nmaster();
         }
         // Otherwise there is just one master node, the node itself
         else
         {
           n_master = 1;
         }
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // Get the equation number
           if (is_node_hanging)
           {
             // Get the equation number from the master node
             global_eqn =
               hang_info_pt->master_node_pt(m)->eqn_number(u_nodal_index);
           }
           else
           {
             // Global equation number
             global_eqn = this->node_pt(l)->eqn_number(u_nodal_index);
           }
           // If it's positive add to the count
           if (global_eqn >= 0)
           {
             ++n_u_dof;
           }
         }
       }
       // Now resize the storage schemes
       du_ddata.resize(n_u_dof, 0.0);
       global_eqn_number.resize(n_u_dof, 0);
       // Loop over th nodes again and set the derivatives
       unsigned count = 0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_node; l++)
       {
         unsigned n_master = 1;
         double hang_weight = 1.0;
         // Local bool (is the node hanging)
         bool is_node_hanging = this->node_pt(l)->is_hanging();
         // If the node is hanging, get the number of master nodes
         if (is_node_hanging)
         {
           hang_info_pt = this->node_pt(l)->hanging_pt();
           n_master = hang_info_pt->nmaster();
         }
         // Otherwise there is just one master node, the node itself
         else
         {
           n_master = 1;
         }
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // If the node is hanging get weight from master node
           if (is_node_hanging)
           {
             // Get the hang weight from the master node
             hang_weight = hang_info_pt->master_weight(m);
           }
           else
           {
             // Node contributes with full weight
             hang_weight = 1.0;
           }
           // Get the equation number
           if (is_node_hanging)
           {
             // Get the equation number from the master node
             global_eqn =
               hang_info_pt->master_node_pt(m)->eqn_number(u_nodal_index);
           }
           else
           {
             // Local equation number
             global_eqn = this->node_pt(l)->eqn_number(u_nodal_index);
           }
           if (global_eqn >= 0)
           {
             // Set the global equation number
             global_eqn_number[count] = global_eqn;
             // Set the derivative with respect to the unknown
             du_ddata[count] = psi[l] * hang_weight;
             // Increase the counter
             ++count;
           }
         }
       }
     }
References oomph::Data::eqn_number(), oomph::Node::hanging_pt(), oomph::Node::is_hanging(), m, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::shape(), and oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::u_index_axi_nst().
fill_in_contribution_to_hessian_vector_products()
void oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products (Vector< double > const & Y, DenseMatrix< double > const & C, DenseMatrix< double > & product) inline private virtual
Compute the hessian tensor vector products required to perform continuation of bifurcations analytically
Reimplemented from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
     {
       throw OomphLibError("Not yet implemented\n",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
fill_in_generic_dresidual_contribution_axi_nst()
void oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam, DenseMatrix< double > & dmass_matrix_dparam, unsigned flag) inline private virtual
Add element's contribution to the derivative of the elemental residual vector and/or Jacobian matrix and/or mass matrix flag=2: compute all flag=1: compute both residual and Jacobian flag=0: compute only residual vector
Reimplemented from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
     {
       throw OomphLibError("Not yet implemented\n",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
fill_in_generic_residual_contribution_axi_nst()
void oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) private virtual
Add element's contribution to the elemental residual vector and/or Jacobian matrix and mass matrix flag=2: compute all flag=1: compute both residual and Jacobian flag=0: compute only residual vector
Add element's contribution to the elemental residual vector and/or Jacobian matrix. flag=1: compute both flag=0: compute only residual vector
Reimplemented from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
   {
     // The dimension is actually two
     unsigned DIM = 2;
     // Find out how many nodes there are
     unsigned n_node = nnode();
     // Get continuous time from timestepper of first node
     double time = node_pt(0)->time_stepper_pt()->time_pt()->time();
     // Find out how many pressure dofs there are
     unsigned n_pres = npres_axi_nst();
     // Get the local indices of the nodal coordinates
     unsigned u_nodal_index[3];
     for (unsigned i = 0; i < 3; ++i)
     {
       u_nodal_index[i] = u_index_axi_nst(i);
     }
     // Which nodal value represents the pressure? (Negative if pressure
     // is not based on nodal interpolation).
     int p_index = this->p_nodal_index_axi_nst();
     // Local array of booleans that are true if the l-th pressure value is
     // hanging (avoid repeated virtual function calls)
     bool pressure_dof_is_hanging[n_pres];
     // If the pressure is stored at a node
     if (p_index >= 0)
     {
       // Read out whether the pressure is hanging
       for (unsigned l = 0; l < n_pres; ++l)
       {
         pressure_dof_is_hanging[l] = pressure_node_pt(l)->is_hanging(p_index);
       }
     }
     // Otherwise the pressure is not stored at a node and so cannot hang
     else
     {
       for (unsigned l = 0; l < n_pres; ++l)
       {
         pressure_dof_is_hanging[l] = false;
       }
     }
     // Set up memory for the shape and test functions
     Shape psif(n_node), testf(n_node);
     DShape dpsifdx(n_node, DIM), dtestfdx(n_node, DIM);
     // Set up memory for pressure shape and test functions
     Shape psip(n_pres), testp(n_pres);
     // Set the value of Nintpt
     unsigned Nintpt = integral_pt()->nweight();
     // Set the Vector to hold local coordinates
     Vector<double> s(DIM);
     // Get Physical Variables from Element
     // Reynolds number must be multiplied by the density ratio
     double scaled_re = re() * density_ratio();
     double scaled_re_st = re_st() * density_ratio();
     double scaled_re_inv_fr = re_invfr() * density_ratio();
     double scaled_re_inv_ro = re_invro() * density_ratio();
     double visc_ratio = viscosity_ratio(); // hierher -- rewrite and
                                            // make consistent with
                                            // non-refineable version
     Vector<double> G = g();
     // Integers to store the local equation and unknown numbers
     int local_eqn = 0, local_unknown = 0;
     // Local storage for pointers to hang info objects
     HangInfo *hang_info_pt = 0, *hang_info2_pt = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < Nintpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < DIM; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the shape and test functions
       double J = dshape_and_dtest_eulerian_at_knot_axi_nst(
         ipt, psif, dpsifdx, testf, dtestfdx);
       // Call the pressure shape and test functions
       pshape_axi_nst(s, psip, testp);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Calculate local values of the pressure and velocity components
       //--------------------------------------------------------------
       double interpolated_p = 0.0;
       Vector<double> interpolated_u(DIM + 1, 0.0);
       Vector<double> interpolated_x(DIM, 0.0);
       Vector<double> mesh_veloc(DIM, 0.0);
       Vector<double> dudt(DIM + 1, 0.0);
       DenseMatrix<double> interpolated_dudx(DIM + 1, DIM, 0.0);
       // Calculate pressure
       for (unsigned l = 0; l < n_pres; l++)
       {
         interpolated_p += p_axi_nst(l) * psip[l];
       }
       // Calculate velocities and derivatives
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Cache the shape function
         const double psif_ = psif(l);
         // Loop over directions
         for (unsigned i = 0; i < DIM; i++)
         {
           interpolated_x[i] += nodal_position(l, i) * psif_;
           // mesh_veloc[i] +=dnodal_position_dt(l,i)*psif(l);
         }
         for (unsigned i = 0; i < DIM + 1; i++)
         {
           const double u_value = nodal_value(l, u_nodal_index[i]);
           interpolated_u[i] += u_value * psif_;
           dudt[i] += du_dt_axi_nst(l, i) * psif_;
           // Loop over derivative directions for gradients
           for (unsigned j = 0; j < DIM; j++)
           {
             interpolated_dudx(i, j) += u_value * dpsifdx(l, j);
           }
         }
       }
       // Get the mesh velocity if ALE is enabled
       if (!ALE_is_disabled)
       {
         // Loop over nodes
         for (unsigned l = 0; l < n_node; l++)
         {
           // Loop over the two coordinate directions
           for (unsigned i = 0; i < 2; i++)
           {
             mesh_veloc[i] += this->dnodal_position_dt(l, i) * psif(l);
           }
         }
       }
       // The strainrate used to compute the second invariant
       DenseMatrix<double> strainrate_to_compute_second_invariant(3, 3, 0.0);
       // the strainrate used to calculate the second invariant
       // can be either the current one or the one extrapolated from
       // previous velocity values
       if (!Use_extrapolated_strainrate_to_compute_second_invariant)
       {
         strain_rate(s, strainrate_to_compute_second_invariant);
       }
       else
       {
         extrapolated_strain_rate(ipt, strainrate_to_compute_second_invariant);
       }
       // Calculate the second invariant
       double second_invariant = SecondInvariantHelper::second_invariant(
         strainrate_to_compute_second_invariant);
       // Get the viscosity according to the constitutive equation
       double viscosity = Constitutive_eqn_pt->viscosity(second_invariant);
       // Get the user-defined body force terms
       Vector<double> body_force(DIM + 1);
       get_body_force_axi_nst(time, ipt, s, interpolated_x, body_force);
       // Get the user-defined source function
       double source = get_source_fct(time, ipt, interpolated_x);
       // r is the first postition component
       double r = interpolated_x[0];
       // obacht set up vectors of the viscosity differentiated w.r.t.
       // the velocity components (radial, axial, azimuthal)
       Vector<double> dviscosity_dUr(n_node, 0.0);
       Vector<double> dviscosity_dUz(n_node, 0.0);
       Vector<double> dviscosity_dUphi(n_node, 0.0);
       if (!Use_extrapolated_strainrate_to_compute_second_invariant)
       {
         // Calculate the derivate of the viscosity w.r.t. the second invariant
         double dviscosity_dsecond_invariant =
           Constitutive_eqn_pt->dviscosity_dinvariant(second_invariant);
         // calculate a reference strainrate
         DenseMatrix<double> strainrate_ref(3, 3, 0.0);
         strain_rate(s, strainrate_ref);
         // pre-compute the derivative of the second invariant w.r.t. the
         // entries in the rate of strain tensor
         DenseMatrix<double> dinvariant_dstrainrate(3, 3, 0.0);
         // d I_2 / d epsilon_{r,r}
         dinvariant_dstrainrate(0, 0) =
           strainrate_ref(1, 1) + strainrate_ref(2, 2);
         // d I_2 / d epsilon_{z,z}
         dinvariant_dstrainrate(1, 1) =
           strainrate_ref(0, 0) + strainrate_ref(2, 2);
         // d I_2 / d epsilon_{phi,phi}
         dinvariant_dstrainrate(2, 2) =
           strainrate_ref(0, 0) + strainrate_ref(1, 1);
         // d I_2 / d epsilon_{r,z}
         dinvariant_dstrainrate(0, 1) = -strainrate_ref(1, 0);
         // d I_2 / d epsilon_{z,r}
         dinvariant_dstrainrate(1, 0) = -strainrate_ref(0, 1);
         // d I_2 / d epsilon_{r,phi}
         dinvariant_dstrainrate(0, 2) = -strainrate_ref(2, 0);
         // d I_2 / d epsilon_{phi,r}
         dinvariant_dstrainrate(2, 0) = -strainrate_ref(0, 2);
         // d I_2 / d epsilon_{phi,z}
         dinvariant_dstrainrate(2, 1) = -strainrate_ref(1, 2);
         // d I_2 / d epsilon_{z,phi}
         dinvariant_dstrainrate(1, 2) = -strainrate_ref(2, 1);
         // loop over the nodes
         for (unsigned l = 0; l < n_node; l++)
         {
           // Get pointer to l-th local node
           // Node* nod_pt = node_pt(l);
           // loop over the three velocity components
           for (unsigned i = 0; i < 3; i++)
           {
             // initialise the derivative of the second invariant w.r.t. the
             // unknown velocity U_{i,l}
             double dinvariant_dunknown = 0.0;
             // loop over the entries of the rate of strain tensor
             for (unsigned m = 0; m < 3; m++)
             {
               for (unsigned n = 0; n < 3; n++)
               {
                 // initialise the derivative of the strainrate w.r.t. the
                 // unknown velocity U_{i,l}
                 double dstrainrate_dunknown = 0.0;
                 // switch based on first index
                 switch (m)
                 {
                     // epsilon_{r ...}
                   case 0:
                     // switch for second index
                     switch (n)
                     {
                         // epsilon_{r r}
                       case 0:
                         if (i == 0)
{
                           dstrainrate_dunknown = dpsifdx(l, 0);
                         }
                         break;
                         // epsilon_{r z}
                       case 1:
                         if (i == 0)
{
                           dstrainrate_dunknown = 0.5 * dpsifdx(l, 1);
                         }
                         else if (i == 1)
{
                           dstrainrate_dunknown = 0.5 * dpsifdx(l, 0);
                         }
                         break;
                         // epsilon_{r phi}
                       case 2:
                         if (i == 2)
{
                           dstrainrate_dunknown =
                             0.5 * dpsifdx(l, 0) - 0.5 / r * psif[l];
                         }
                         break;
                       default:
                         std::ostringstream error_stream;
                         error_stream << "Should never get here...";
                         throw OomphLibError(error_stream.str(),
                                             OOMPH_CURRENT_FUNCTION,
                                             OOMPH_EXCEPTION_LOCATION);
                     }
                     break;
                     // epsilon_{z ...}
                   case 1:
                     // switch for second index
                     switch (n)
                     {
                         // epsilon_{z r}
                       case 0:
                         if (i == 0)
{
                           dstrainrate_dunknown = 0.5 * dpsifdx(l, 1);
                         }
                         else if (i == 1)
{
                           dstrainrate_dunknown = 0.5 * dpsifdx(l, 0);
                         }
                         break;
                         // epsilon_{z z}
                       case 1:
                         if (i == 1)
{
                           dstrainrate_dunknown = dpsifdx(l, 1);
                         }
                         else
{
                           // dstrainrate_dunknown=0.0;
                         }
                         break;
                         // epsilon_{z phi}
                       case 2:
                         if (i == 2)
{
                           dstrainrate_dunknown = 0.5 * dpsifdx(l, 1);
                         }
                         break;
                       default:
                         std::ostringstream error_stream;
                         error_stream << "Should never get here...";
                         throw OomphLibError(error_stream.str(),
                                             OOMPH_CURRENT_FUNCTION,
                                             OOMPH_EXCEPTION_LOCATION);
                     }
                     break;
                     // epsilon_{phi ...}
                   case 2:
                     // switch for second index
                     switch (n)
                     {
                         // epsilon_{phi r}
                       case 0:
                         if (i == 2)
{
                           dstrainrate_dunknown =
                             0.5 * dpsifdx(l, 0) - 0.5 / r * psif[l];
                         }
                         break;
                         // epsilon_{phi z}
                       case 1:
                         if (i == 2)
{
                           dstrainrate_dunknown = 0.5 * dpsifdx(l, 1);
                         }
                         break;
                         // epsilon_{phi phi}
                       case 2:
                         if (i == 0)
{
                           dstrainrate_dunknown = 1.0 / r * psif[l];
                         }
                         break;
                       default:
                         std::ostringstream error_stream;
                         error_stream << "Should never get here...";
                         throw OomphLibError(error_stream.str(),
                                             OOMPH_CURRENT_FUNCTION,
                                             OOMPH_EXCEPTION_LOCATION);
                     }
                     break;
                   default:
                     std::ostringstream error_stream;
                     error_stream << "Should never get here...";
                     throw OomphLibError(error_stream.str(),
                                         OOMPH_CURRENT_FUNCTION,
                                         OOMPH_EXCEPTION_LOCATION);
                 }
                 dinvariant_dunknown +=
                   dinvariant_dstrainrate(m, n) * dstrainrate_dunknown;
               }
             }
             switch (i)
             {
               case 0:
                 dviscosity_dUr[l] =
                   dviscosity_dsecond_invariant * dinvariant_dunknown;
                 break;
               case 1:
                 dviscosity_dUz[l] =
                   dviscosity_dsecond_invariant * dinvariant_dunknown;
                 break;
               case 2:
                 dviscosity_dUphi[l] =
                   dviscosity_dsecond_invariant * dinvariant_dunknown;
                 break;
               default:
                 std::ostringstream error_stream;
                 error_stream << "Should never get here...";
                 throw OomphLibError(error_stream.str(),
                                     OOMPH_CURRENT_FUNCTION,
                                     OOMPH_EXCEPTION_LOCATION);
             }
           }
         }
       }
       // MOMENTUM EQUATIONS
       //==================
       // Number of master nodes and storage for the weight of the shape function
       unsigned n_master = 1;
       double hang_weight = 1.0;
       // Loop over the nodes for the test functions/equations
       //----------------------------------------------------
       for (unsigned l = 0; l < n_node; l++)
       {
         // Local boolean that indicates the hanging status of the node
         bool is_node_hanging = node_pt(l)->is_hanging();
         // If the node is hanging
         if (is_node_hanging)
         {
           // Get the hanging pointer
           hang_info_pt = node_pt(l)->hanging_pt();
           // Read out number of master nodes from hanging data
           n_master = hang_info_pt->nmaster();
         }
         // Otherwise the node is its own master
         else
         {
           n_master = 1;
         }
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // Loop over velocity components for equations
           for (unsigned i = 0; i < DIM + 1; i++)
           {
             // Get the equation number
             // If the node is hanging
             if (is_node_hanging)
             {
               // Get the equation number from the master node
               local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                                u_nodal_index[i]);
               // Get the hang weight from the master node
               hang_weight = hang_info_pt->master_weight(m);
             }
             // If the node is not hanging
             else
             {
               // Local equation number
               local_eqn = this->nodal_local_eqn(l, u_nodal_index[i]);
               // Node contributes with full weight
               hang_weight = 1.0;
             }
             // If it's not a boundary condition...
             if (local_eqn >= 0)
             {
               // initialise for residual calculation
               double sum = 0.0;
               switch (i)
               {
                   // RADIAL MOMENTUM EQUATION
                 case 0:
                   // Add the user-defined body force terms
                   sum += r * body_force[0] * testf[l] * W * hang_weight;
                   // Add the gravitational body force term
                   sum +=
                     r * scaled_re_inv_fr * testf[l] * G[0] * W * hang_weight;
                   // Add the pressure gradient term
                   sum += interpolated_p * (testf[l] + r * dtestfdx(l, 0)) * W *
                          hang_weight;
                   // Add in the stress tensor terms
                   // The viscosity ratio needs to go in here to ensure
                   // continuity of normal stress is satisfied even in flows
                   // with zero pressure gradient!
                   // stress term 1
                   sum -= visc_ratio * viscosity * r * (1.0 + Gamma[0]) *
                          interpolated_dudx(0, 0) * dtestfdx(l, 0) * W *
                          hang_weight;
                   // stress term 2
                   sum -= visc_ratio * viscosity * r *
                          (interpolated_dudx(0, 1) +
                           Gamma[0] * interpolated_dudx(1, 0)) *
                          dtestfdx(l, 1) * W * hang_weight;
                   // stress term 3
                   sum -= visc_ratio * viscosity * (1.0 + Gamma[0]) *
                          interpolated_u[0] * testf[l] * W * hang_weight / r;
                   // Add in the inertial terms
                   // du/dt term
                   sum -=
                     scaled_re_st * r * dudt[0] * testf[l] * W * hang_weight;
                   // Convective terms
                   sum -= scaled_re *
                          (r * interpolated_u[0] * interpolated_dudx(0, 0) -
                           interpolated_u[2] * interpolated_u[2] +
                           r * interpolated_u[1] * interpolated_dudx(0, 1)) *
                          testf[l] * W * hang_weight;
                   // Mesh velocity terms
                   if (!ALE_is_disabled)
                   {
                     for (unsigned k = 0; k < 2; k++)
                     {
                       sum += scaled_re_st * r * mesh_veloc[k] *
                              interpolated_dudx(0, k) * testf[l] * W *
                              hang_weight;
                     }
                   }
                   // Coriolis term
                   sum += 2.0 * r * scaled_re_inv_ro * interpolated_u[2] *
                          testf[l] * W * hang_weight;
                   break;
                   // AXIAL MOMENTUM EQUATION
                 case 1:
                   // If it's not a boundary condition
                   // Add the user-defined body force terms
                   // Remember to multiply by the density ratio!
                   sum += r * body_force[1] * testf[l] * W * hang_weight;
                   // Add the gravitational body force term
                   sum +=
                     r * scaled_re_inv_fr * testf[l] * G[1] * W * hang_weight;
                   // Add the pressure gradient term
                   sum += r * interpolated_p * dtestfdx(l, 1) * W * hang_weight;
                   // Add in the stress tensor terms
                   // The viscosity ratio needs to go in here to ensure
                   // continuity of normal stress is satisfied even in flows
                   // with zero pressure gradient!
                   // stress term 1
                   sum -= visc_ratio * viscosity * r *
                          (interpolated_dudx(1, 0) +
                           Gamma[1] * interpolated_dudx(0, 1)) *
                          dtestfdx(l, 0) * W * hang_weight;
                   // stress term 2
                   sum -= visc_ratio * viscosity * r * (1.0 + Gamma[1]) *
                          interpolated_dudx(1, 1) * dtestfdx(l, 1) * W *
                          hang_weight;
                   // Add in the inertial terms
                   // du/dt term
                   sum -=
                     scaled_re_st * r * dudt[1] * testf[l] * W * hang_weight;
                   // Convective terms
                   sum -= scaled_re *
                          (r * interpolated_u[0] * interpolated_dudx(1, 0) +
                           r * interpolated_u[1] * interpolated_dudx(1, 1)) *
                          testf[l] * W * hang_weight;
                   // Mesh velocity terms
                   if (!ALE_is_disabled)
                   {
                     for (unsigned k = 0; k < 2; k++)
                     {
                       sum += scaled_re_st * r * mesh_veloc[k] *
                              interpolated_dudx(1, k) * testf[l] * W *
                              hang_weight;
                     }
                   }
                   break;
                   // AZIMUTHAL MOMENTUM EQUATION
                 case 2:
                   // Add the user-defined body force terms
                   // Remember to multiply by the density ratio!
                   sum += r * body_force[2] * testf[l] * W * hang_weight;
                   // Add the gravitational body force term
                   sum +=
                     r * scaled_re_inv_fr * testf[l] * G[2] * W * hang_weight;
                   // There is NO pressure gradient term
                   // Add in the stress tensor terms
                   // The viscosity ratio needs to go in here to ensure
                   // continuity of normal stress is satisfied even in flows
                   // with zero pressure gradient!
                   // stress term 1
                   sum -= visc_ratio * viscosity *
                          (r * interpolated_dudx(2, 0) -
                           Gamma[0] * interpolated_u[2]) *
                          dtestfdx(l, 0) * W * hang_weight;
                   // stress term 2
                   sum -= visc_ratio * viscosity * r * interpolated_dudx(2, 1) *
                          dtestfdx(l, 1) * W * hang_weight;
                   // stress term 3
                   sum -= visc_ratio * viscosity *
                          ((interpolated_u[2] / r) -
                           Gamma[0] * interpolated_dudx(2, 0)) *
                          testf[l] * W * hang_weight;
                   // Add in the inertial terms
                   // du/dt term
                   sum -=
                     scaled_re_st * r * dudt[2] * testf[l] * W * hang_weight;
                   // Convective terms
                   sum -= scaled_re *
                          (r * interpolated_u[0] * interpolated_dudx(2, 0) +
                           interpolated_u[0] * interpolated_u[2] +
                           r * interpolated_u[1] * interpolated_dudx(2, 1)) *
                          testf[l] * W * hang_weight;
                   // Mesh velocity terms
                   if (!ALE_is_disabled)
                   {
                     for (unsigned k = 0; k < 2; k++)
                     {
                       sum += scaled_re_st * r * mesh_veloc[k] *
                              interpolated_dudx(2, k) * testf[l] * W *
                              hang_weight;
                     }
                   }
                   // Coriolis term
                   sum -= 2.0 * r * scaled_re_inv_ro * interpolated_u[0] *
                          testf[l] * W * hang_weight;
                   break;
               }
               // Add contribution
               residuals[local_eqn] += sum;
               // CALCULATE THE JACOBIAN
               if (flag)
               {
                 // Number of master nodes and weights
                 unsigned n_master2 = 1;
                 double hang_weight2 = 1.0;
                 // Loop over the velocity nodes for columns
                 for (unsigned l2 = 0; l2 < n_node; l2++)
                 {
                   // Local boolean for hanging status
                   bool is_node2_hanging = node_pt(l2)->is_hanging();
                   // If the node is hanging
                   if (is_node2_hanging)
                   {
                     hang_info2_pt = node_pt(l2)->hanging_pt();
                     // Read out number of master nodes from hanging data
                     n_master2 = hang_info2_pt->nmaster();
                   }
                   // Otherwise the node is its own master
                   else
                   {
                     n_master2 = 1;
                   }
                   // Loop over the master nodes
                   for (unsigned m2 = 0; m2 < n_master2; m2++)
                   {
                     // Loop over the velocity components
                     for (unsigned i2 = 0; i2 < DIM + 1; i2++)
                     {
                       // Get the number of the unknown
                       // If the node is hanging
                       if (is_node2_hanging)
                       {
                         // Get the equation number from the master node
                         local_unknown = this->local_hang_eqn(
                           hang_info2_pt->master_node_pt(m2), u_nodal_index[i2]);
                         hang_weight2 = hang_info2_pt->master_weight(m2);
                       }
                       else
                       {
                         local_unknown =
                           this->nodal_local_eqn(l2, u_nodal_index[i2]);
                         hang_weight2 = 1.0;
                       }
                       // If the unknown is non-zero
                       if (local_unknown >= 0)
                       {
                         // Different results for i and i2
                         switch (i)
{
                             // RADIAL MOMENTUM EQUATION
                           case 0:
                             switch (i2)
{
                                 // radial component
                               case 0:
                                 // Add the mass matrix entries
                                 if (flag == 2)
{
                                   mass_matrix(local_eqn, local_unknown) +=
                                     scaled_re_st * r * psif[l2] * testf[l] * W *
                                     hang_weight * hang_weight2;
                                 }
                                 // Add contribution to the Jacobian matrix
                                 // stress term 1
                                 jacobian(local_eqn, local_unknown) -=
                                   visc_ratio * viscosity * r *
                                   (1.0 + Gamma[0]) * dpsifdx(l2, 0) *
                                   dtestfdx(l, 0) * W * hang_weight *
                                   hang_weight2;
                                 if (
                                   !Use_extrapolated_strainrate_to_compute_second_invariant)
{
                                   // stress term 1 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUr[l2] * r *
                                     (1.0 + Gamma[0]) * interpolated_dudx(0, 0) *
                                     dtestfdx(l, 0) * W * hang_weight *
                                     hang_weight2;
                                 }
                                 // stress term 2
                                 jacobian(local_eqn, local_unknown) -=
                                   visc_ratio * viscosity * r * dpsifdx(l2, 1) *
                                   dtestfdx(l, 1) * W * hang_weight *
                                   hang_weight2;
                                 if (
                                   !Use_extrapolated_strainrate_to_compute_second_invariant)
{
                                   // stress term 2 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUr[l2] * r *
                                     (interpolated_dudx(0, 1) +
                                      Gamma[0] * interpolated_dudx(1, 0)) *
                                     dtestfdx(l, 1) * W * hang_weight *
                                     hang_weight2;
                                 }
                                 // stress term 3
                                 jacobian(local_eqn, local_unknown) -=
                                   visc_ratio * viscosity * (1.0 + Gamma[0]) *
                                   psif[l2] * testf[l] * W * hang_weight *
                                   hang_weight2 / r;
                                 if (
                                   !Use_extrapolated_strainrate_to_compute_second_invariant)
{
                                   // stress term 3 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUr[l2] *
                                     (1.0 + Gamma[0]) * interpolated_u[0] *
                                     testf[l] * W * hang_weight * hang_weight2 /
                                     r;
                                 }
                                 // Add in the inertial terms
                                 // du/dt term
                                 jacobian(local_eqn, local_unknown) -=
                                   scaled_re_st * r *
                                   node_pt(l2)->time_stepper_pt()->weight(1, 0) *
                                   psif[l2] * testf[l] * W * hang_weight *
                                   hang_weight2;
                                 // Convective terms
                                 jacobian(local_eqn, local_unknown) -=
                                   scaled_re *
                                   (r * psif[l2] * interpolated_dudx(0, 0) +
                                    r * interpolated_u[0] * dpsifdx(l2, 0) +
                                    r * interpolated_u[1] * dpsifdx(l2, 1)) *
                                   testf[l] * W * hang_weight * hang_weight2;
                                 // Mesh velocity terms
                                 if (!ALE_is_disabled)
{
                                   for (unsigned k = 0; k < 2; k++)
{
                                     jacobian(local_eqn, local_unknown) +=
                                       scaled_re_st * r * mesh_veloc[k] *
                                       dpsifdx(l2, k) * testf[l] * W *
                                       hang_weight * hang_weight2;
                                   }
                                 }
                                 break;
                                 // axial component
                               case 1:
                                 // no stress term 1
                                 if (
                                   !Use_extrapolated_strainrate_to_compute_second_invariant)
{
                                   // stress term 1 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUz[l2] * r *
                                     (1.0 + Gamma[0]) * interpolated_dudx(0, 0) *
                                     dtestfdx(l, 0) * W * hang_weight *
                                     hang_weight2;
                                 }
                                 // stress term 2
                                 jacobian(local_eqn, local_unknown) -=
                                   visc_ratio * viscosity * r * Gamma[0] *
                                   dpsifdx(l2, 0) * dtestfdx(l, 1) * W *
                                   hang_weight * hang_weight2;
                                 if (
                                   !Use_extrapolated_strainrate_to_compute_second_invariant)
{
                                   // stress term 2 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUz[l2] * r *
                                     (interpolated_dudx(0, 1) +
                                      Gamma[0] * interpolated_dudx(1, 0)) *
                                     dtestfdx(l, 1) * W * hang_weight *
                                     hang_weight2;
                                 }
                                 // no stress term 3
                                 if (
                                   !Use_extrapolated_strainrate_to_compute_second_invariant)
{
                                   // stress term 3 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUz[l2] *
                                     (1.0 + Gamma[0]) * interpolated_u[0] *
                                     testf[l] * W * hang_weight * hang_weight2 /
                                     r;
                                 }
                                 // Convective terms
                                 jacobian(local_eqn, local_unknown) -=
                                   scaled_re * r * psif[l2] *
                                   interpolated_dudx(0, 1) * testf[l] * W *
                                   hang_weight * hang_weight2;
                                 break;
                                 // azimuthal component
                               case 2:
                                 // no stress term 1
                                 if (
                                   !Use_extrapolated_strainrate_to_compute_second_invariant)
{
                                   // stress term 1 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUphi[l2] * r *
                                     (1.0 + Gamma[0]) * interpolated_dudx(0, 0) *
                                     dtestfdx(l, 0) * W * hang_weight *
                                     hang_weight2;
                                 }
                                 // no stress term 2
                                 if (
                                   !Use_extrapolated_strainrate_to_compute_second_invariant)
{
                                   // stress term 2 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUphi[l2] * r *
                                     (interpolated_dudx(0, 1) +
                                      Gamma[0] * interpolated_dudx(1, 0)) *
                                     dtestfdx(l, 1) * W * hang_weight *
                                     hang_weight2;
                                 }
                                 // no stress term 3
                                 if (
                                   !Use_extrapolated_strainrate_to_compute_second_invariant)
{
                                   // stress term 3 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUphi[l2] *
                                     (1.0 + Gamma[0]) * interpolated_u[0] *
                                     testf[l] * W * hang_weight * hang_weight2 /
                                     r;
                                 }
                                 // Convective terms
                                 jacobian(local_eqn, local_unknown) -=
                                   -scaled_re * 2.0 * interpolated_u[2] *
                                   psif[l2] * testf[l] * W * hang_weight *
                                   hang_weight2;
                                 // Coriolis terms
                                 jacobian(local_eqn, local_unknown) +=
                                   2.0 * r * scaled_re_inv_ro * psif[l2] *
                                   testf[l] * W * hang_weight * hang_weight2;
                                 break;
                             } /*End of contribution radial momentum eqn*/
                             break;
                             // AXIAL MOMENTUM EQUATION
                           case 1:
                             switch (i2)
{
                                 // radial component
                               case 0:
                                 // Add in the stress tensor terms
                                 // The viscosity ratio needs to go in here to
                                 // ensure continuity of normal stress is
                                 // satisfied even in flows with zero pressure
                                 // gradient!
                                 // stress term 1
                                 jacobian(local_eqn, local_unknown) -=
                                   visc_ratio * viscosity * r * Gamma[1] *
                                   dpsifdx(l2, 1) * dtestfdx(l, 0) * W *
                                   hang_weight * hang_weight2;
                                 if (
                                   !Use_extrapolated_strainrate_to_compute_second_invariant)
{
                                   // stress term 1 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUr[l2] * r *
                                     (interpolated_dudx(1, 0) +
                                      Gamma[1] * interpolated_dudx(0, 1)) *
                                     dtestfdx(l, 0) * W * hang_weight *
                                     hang_weight2;
                                 }
                                 // no stress term 2
                                 if (
                                   !Use_extrapolated_strainrate_to_compute_second_invariant)
{
                                   // stress term 2 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUr[l2] * r *
                                     (1.0 + Gamma[1]) * interpolated_dudx(1, 1) *
                                     dtestfdx(l, 1) * W * hang_weight *
                                     hang_weight2;
                                 }
                                 // Convective terms
                                 jacobian(local_eqn, local_unknown) -=
                                   scaled_re * r * psif[l2] *
                                   interpolated_dudx(1, 0) * testf[l] * W *
                                   hang_weight * hang_weight2;
                                 break;
                                 // axial component
                               case 1:
                                 // Add the mass matrix terms
                                 if (flag == 2)
{
                                   mass_matrix(local_eqn, local_unknown) +=
                                     scaled_re_st * r * psif[l2] * testf[l] * W *
                                     hang_weight * hang_weight2;
                                 }
                                 // Add in the stress tensor terms
                                 // The viscosity ratio needs to go in here to
                                 // ensure continuity of normal stress is
                                 // satisfied even in flows with zero pressure
                                 // gradient!
                                 // stress term 1
                                 jacobian(local_eqn, local_unknown) -=
                                   visc_ratio * viscosity * r * dpsifdx(l2, 0) *
                                   dtestfdx(l, 0) * W * hang_weight *
                                   hang_weight2;
                                 if (
                                   !Use_extrapolated_strainrate_to_compute_second_invariant)
{
                                   // stress term 1 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUz[l2] * r *
                                     (interpolated_dudx(1, 0) +
                                      Gamma[1] * interpolated_dudx(0, 1)) *
                                     dtestfdx(l, 0) * W * hang_weight *
                                     hang_weight2;
                                 }
                                 // stress term 2
                                 jacobian(local_eqn, local_unknown) -=
                                   visc_ratio * viscosity * r *
                                   (1.0 + Gamma[1]) * dpsifdx(l2, 1) *
                                   dtestfdx(l, 1) * W * hang_weight *
                                   hang_weight2;
                                 if (
                                   !Use_extrapolated_strainrate_to_compute_second_invariant)
{
                                   // stress term 2 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUz[l2] * r *
                                     (1.0 + Gamma[1]) * interpolated_dudx(1, 1) *
                                     dtestfdx(l, 1) * W * hang_weight *
                                     hang_weight2;
                                 }
                                 // Add in the inertial terms
                                 // du/dt term
                                 jacobian(local_eqn, local_unknown) -=
                                   scaled_re_st * r *
                                   node_pt(l2)->time_stepper_pt()->weight(1, 0) *
                                   psif[l2] * testf[l] * W * hang_weight *
                                   hang_weight2;
                                 // Convective terms
                                 jacobian(local_eqn, local_unknown) -=
                                   scaled_re *
                                   (r * interpolated_u[0] * dpsifdx(l2, 0) +
                                    r * psif[l2] * interpolated_dudx(1, 1) +
                                    r * interpolated_u[1] * dpsifdx(l2, 1)) *
                                   testf[l] * W * hang_weight * hang_weight2;
                                 // Mesh velocity terms
                                 if (!ALE_is_disabled)
{
                                   for (unsigned k = 0; k < 2; k++)
{
                                     jacobian(local_eqn, local_unknown) +=
                                       scaled_re_st * r * mesh_veloc[k] *
                                       dpsifdx(l2, k) * testf[l] * W *
                                       hang_weight * hang_weight2;
                                   }
                                 }
                                 break;
                                 // azimuthal component
                               case 2:
                                 // There are no azimithal terms in the axial
                                 // momentum equation
                                 // edit: for the generalised Newtonian elements
                                 // there are...
                                 if (
                                   !Use_extrapolated_strainrate_to_compute_second_invariant)
{
                                   // stress term 1 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUphi[l2] * r *
                                     (interpolated_dudx(1, 0) +
                                      Gamma[1] * interpolated_dudx(0, 1)) *
                                     dtestfdx(l, 0) * W * hang_weight *
                                     hang_weight2;
                                   // stress term 2 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUphi[l2] * r *
                                     (1.0 + Gamma[1]) * interpolated_dudx(1, 1) *
                                     dtestfdx(l, 1) * W * hang_weight *
                                     hang_weight2;
                                 }
                                 break;
                             }
                             break;
                             // AZIMUTHAL MOMENTUM EQUATION
                           case 2:
                             switch (i2)
{
                                 // radial component
                               case 0:
                                 if (
                                   !Use_extrapolated_strainrate_to_compute_second_invariant)
{
                                   // stress term 1 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUr[l2] *
                                     (r * interpolated_dudx(2, 0) -
                                      Gamma[0] * interpolated_u[2]) *
                                     dtestfdx(l, 0) * W * hang_weight *
                                     hang_weight2;
                                   // stress term 2 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUr[l2] * r *
                                     interpolated_dudx(2, 1) * dtestfdx(l, 1) *
                                     W * hang_weight * hang_weight2;
                                   // stress term 3 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUr[l2] *
                                     ((interpolated_u[2] / r) -
                                      Gamma[0] * interpolated_dudx(2, 0)) *
                                     testf[l] * W * hang_weight * hang_weight2;
                                 }
                                 // Convective terms
                                 jacobian(local_eqn, local_unknown) -=
                                   scaled_re *
                                   (r * psif[l2] * interpolated_dudx(2, 0) +
                                    psif[l2] * interpolated_u[2]) *
                                   testf[l] * W * hang_weight * hang_weight2;
                                 // Coriolis term
                                 jacobian(local_eqn, local_unknown) -=
                                   2.0 * r * scaled_re_inv_ro * psif[l2] *
                                   testf[l] * W * hang_weight * hang_weight2;
                                 break;
                                 // axial component
                               case 1:
                                 if (
                                   !Use_extrapolated_strainrate_to_compute_second_invariant)
{
                                   // stress term 1 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUz[l2] *
                                     (r * interpolated_dudx(2, 0) -
                                      Gamma[0] * interpolated_u[2]) *
                                     dtestfdx(l, 0) * W * hang_weight *
                                     hang_weight2;
                                   // stress term 2 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUz[l2] * r *
                                     interpolated_dudx(2, 1) * dtestfdx(l, 1) *
                                     W * hang_weight * hang_weight2;
                                   // stress term 3 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUz[l2] *
                                     ((interpolated_u[2] / r) -
                                      Gamma[0] * interpolated_dudx(2, 0)) *
                                     testf[l] * W * hang_weight * hang_weight2;
                                 }
                                 // Convective terms
                                 jacobian(local_eqn, local_unknown) -=
                                   scaled_re * r * psif[l2] *
                                   interpolated_dudx(2, 1) * testf[l] * W *
                                   hang_weight * hang_weight2;
                                 break;
                                 // azimuthal component
                               case 2:
                                 // Add the mass matrix terms
                                 if (flag == 2)
{
                                   mass_matrix(local_eqn, local_unknown) +=
                                     scaled_re_st * r * psif[l2] * testf[l] * W *
                                     hang_weight * hang_weight2;
                                 }
                                 // Add in the stress tensor terms
                                 // The viscosity ratio needs to go in here to
                                 // ensure continuity of normal stress is
                                 // satisfied even in flows with zero pressure
                                 // gradient!
                                 // stress term 1
                                 jacobian(local_eqn, local_unknown) -=
                                   visc_ratio * viscosity *
                                   (r * dpsifdx(l2, 0) - Gamma[0] * psif[l2]) *
                                   dtestfdx(l, 0) * W * hang_weight *
                                   hang_weight2;
                                 if (
                                   !Use_extrapolated_strainrate_to_compute_second_invariant)
{
                                   // stress term 1 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUphi[l2] *
                                     (r * interpolated_dudx(2, 0) -
                                      Gamma[0] * interpolated_u[2]) *
                                     dtestfdx(l, 0) * W * hang_weight *
                                     hang_weight2;
                                 }
                                 // stress term 2
                                 jacobian(local_eqn, local_unknown) -=
                                   visc_ratio * viscosity * r * dpsifdx(l2, 1) *
                                   dtestfdx(l, 1) * W * hang_weight *
                                   hang_weight2;
                                 if (
                                   !Use_extrapolated_strainrate_to_compute_second_invariant)
{
                                   // stress term 2 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUphi[l2] * r *
                                     interpolated_dudx(2, 1) * dtestfdx(l, 1) *
                                     W * hang_weight * hang_weight2;
                                 }
                                 // stress term 3
                                 jacobian(local_eqn, local_unknown) -=
                                   visc_ratio * viscosity *
                                   ((psif[l2] / r) - Gamma[0] * dpsifdx(l2, 0)) *
                                   testf[l] * W * hang_weight * hang_weight2;
                                 if (
                                   !Use_extrapolated_strainrate_to_compute_second_invariant)
{
                                   // stress term 3 contribution from
                                   // generalised Newtonian model
                                   jacobian(local_eqn, local_unknown) -=
                                     visc_ratio * dviscosity_dUphi[l2] *
                                     ((interpolated_u[2] / r) -
                                      Gamma[0] * interpolated_dudx(2, 0)) *
                                     testf[l] * W * hang_weight * hang_weight2;
                                 }
                                 // Add in the inertial terms
                                 // du/dt term
                                 jacobian(local_eqn, local_unknown) -=
                                   scaled_re_st * r *
                                   node_pt(l2)->time_stepper_pt()->weight(1, 0) *
                                   psif[l2] * testf[l] * W * hang_weight *
                                   hang_weight2;
                                 // Convective terms
                                 jacobian(local_eqn, local_unknown) -=
                                   scaled_re *
                                   (r * interpolated_u[0] * dpsifdx(l2, 0) +
                                    interpolated_u[0] * psif[l2] +
                                    r * interpolated_u[1] * dpsifdx(l2, 1)) *
                                   testf[l] * W * hang_weight * hang_weight2;
                                 // Mesh velocity terms
                                 if (!ALE_is_disabled)
{
                                   for (unsigned k = 0; k < 2; k++)
{
                                     jacobian(local_eqn, local_unknown) +=
                                       scaled_re_st * r * mesh_veloc[k] *
                                       dpsifdx(l2, k) * testf[l] * W *
                                       hang_weight * hang_weight2;
                                   }
                                 }
                                 break;
                             }
                             break;
                         }
                       }
                     }
                   }
                 } // End of loop over the nodes
                 // Loop over the pressure shape functions
                 for (unsigned l2 = 0; l2 < n_pres; l2++)
                 {
                   // If the pressure dof is hanging
                   if (pressure_dof_is_hanging[l2])
                   {
                     // Pressure dof is hanging so it must be nodal-based
                     hang_info2_pt = pressure_node_pt(l2)->hanging_pt(p_index);
                     // Get the number of master nodes from the pressure node
                     n_master2 = hang_info2_pt->nmaster();
                   }
                   // Otherwise the node is its own master
                   else
                   {
                     n_master2 = 1;
                   }
                   // Loop over the master nodes
                   for (unsigned m2 = 0; m2 < n_master2; m2++)
                   {
                     // Get the number of the unknown
                     // If the pressure dof is hanging
                     if (pressure_dof_is_hanging[l2])
                     {
                       // Get the unknown from the node
                       local_unknown = local_hang_eqn(
                         hang_info2_pt->master_node_pt(m2), p_index);
                       // Get the weight from the hanging object
                       hang_weight2 = hang_info2_pt->master_weight(m2);
                     }
                     else
                     {
                       local_unknown = p_local_eqn(l2);
                       hang_weight2 = 1.0;
                     }
                     // If the unknown is not pinned
                     if (local_unknown >= 0)
                     {
                       // Add in contributions to different equations
                       switch (i)
                       {
                           // RADIAL MOMENTUM EQUATION
                         case 0:
                           jacobian(local_eqn, local_unknown) +=
                             psip[l2] * (testf[l] + r * dtestfdx(l, 0)) * W *
                             hang_weight * hang_weight2;
                           break;
                           // AXIAL MOMENTUM EQUATION
                         case 1:
                           jacobian(local_eqn, local_unknown) +=
                             r * psip[l2] * dtestfdx(l, 1) * W * hang_weight *
                             hang_weight2;
                           break;
                           // AZIMUTHAL MOMENTUM EQUATION
                         case 2:
                           break;
                       }
                     }
                   }
                 } // End of loop over pressure dofs
               } // End of Jacobian calculation
             } // End of if not boundary condition statement
           } // End of loop over velocity components
         } // End of loop over master nodes
       } // End of loop over nodes
       // CONTINUITY EQUATION
       //===================
       // Loop over the pressure shape functions
       for (unsigned l = 0; l < n_pres; l++)
       {
         // If the pressure dof is hanging
         if (pressure_dof_is_hanging[l])
         {
           // Pressure dof is hanging so it must be nodal-based
           hang_info_pt = pressure_node_pt(l)->hanging_pt(p_index);
           // Get the number of master nodes from the pressure node
           n_master = hang_info_pt->nmaster();
         }
         // Otherwise the node is its own master
         else
         {
           n_master = 1;
         }
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // Get the number of the unknown
           // If the pressure dof is hanging
           if (pressure_dof_is_hanging[l])
           {
             local_eqn =
               local_hang_eqn(hang_info_pt->master_node_pt(m), p_index);
             hang_weight = hang_info_pt->master_weight(m);
           }
           else
           {
             local_eqn = p_local_eqn(l);
             hang_weight = 1.0;
           }
           // If the equation is not pinned
           if (local_eqn >= 0)
           {
             // Source term
             residuals[local_eqn] -= r * source * testp[l] * W * hang_weight;
             // Gradient terms
             residuals[local_eqn] +=
               (interpolated_u[0] + r * interpolated_dudx(0, 0) +
                r * interpolated_dudx(1, 1)) *
               testp[l] * W * hang_weight;
             // CALCULATE THE JACOBIAN
             //======================
             if (flag)
             {
               unsigned n_master2 = 1;
               double hang_weight2 = 1.0;
               // Loop over the velocity nodes for columns
               for (unsigned l2 = 0; l2 < n_node; l2++)
               {
                 // Local boolean to indicate whether the node is hanging
                 bool is_node2_hanging = node_pt(l2)->is_hanging();
                 // If the node is hanging
                 if (is_node2_hanging)
                 {
                   hang_info2_pt = node_pt(l2)->hanging_pt();
                   // Read out number of master nodes from hanging data
                   n_master2 = hang_info2_pt->nmaster();
                 }
                 // Otherwise the node is its own master
                 else
                 {
                   n_master2 = 1;
                 }
                 // Loop over the master nodes
                 for (unsigned m2 = 0; m2 < n_master2; m2++)
                 {
                   // Loop over the velocity components
                   for (unsigned i2 = 0; i2 < DIM + 1; i2++)
                   {
                     // Get the number of the unknown
                     // If the node is hanging
                     if (is_node2_hanging)
                     {
                       // Get the equation number from the master node
                       local_unknown = local_hang_eqn(
                         hang_info2_pt->master_node_pt(m2), u_nodal_index[i2]);
                       hang_weight2 = hang_info2_pt->master_weight(m2);
                     }
                     else
                     {
                       local_unknown =
                         this->nodal_local_eqn(l2, u_nodal_index[i2]);
                       hang_weight2 = 1.0;
                     }
                     // If the unknown is not pinned
                     if (local_unknown >= 0)
                     {
                       switch (i2)
                       {
                           // radial component
                         case 0:
                           jacobian(local_eqn, local_unknown) +=
                             (psif[l2] + r * dpsifdx(l2, 0)) * testp[l] * W *
                             hang_weight * hang_weight2;
                           break;
                           // axial component
                         case 1:
                           jacobian(local_eqn, local_unknown) +=
                             r * dpsifdx(l2, 1) * testp[l] * W * hang_weight *
                             hang_weight2;
                           break;
                           // azimuthal component
                         case 2:
                           break;
                       }
                     }
                   }
                 }
               } // End of loop over nodes
               // NO PRESSURE CONTRIBUTIONS TO CONTINUITY EQUATION
             } // End of Jacobian calculation
           }
         }
       } // End of loop over pressure nodes
     } // End of loop over integration points
   } // End of fill_in_generic_residual_contribution_axi_nst(...)
References oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::ALE_is_disabled, Global_Parameters::body_force(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Constitutive_eqn_pt, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::density_ratio(), DIM, oomph::FiniteElement::dnodal_position_dt(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::dshape_and_dtest_eulerian_at_knot_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::du_dt_axi_nst(), oomph::GeneralisedNewtonianConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::extrapolated_strain_rate(), G, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::g(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Gamma, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_body_force_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_source_fct(), oomph::Node::hanging_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::Node::is_hanging(), J, j, k, oomph::Integral::knot(), oomph::RefineableElement::local_hang_eqn(), m, m2(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), n, GlobalParameters::Nintpt, oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::npres_axi_nst(), oomph::Integral::nweight(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::p_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::p_local_eqn(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::p_nodal_index_axi_nst(), pressure_node_pt(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::pshape_axi_nst(), UniformPSDSelfTest::r, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::re(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::re_invfr(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::re_invro(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::re_st(), s, oomph::SecondInvariantHelper::second_invariant(), TestProblem::source(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::strain_rate(), oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Data::time_stepper_pt(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::u_index_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Use_extrapolated_strainrate_to_compute_second_invariant, oomph::GeneralisedNewtonianConstitutiveEquation< DIM >::viscosity(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::viscosity_ratio(), w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and oomph::TimeStepper::weight().
further_build()
void oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::further_build () inline virtual
Further build: pass the pointers down to the sons.
Reimplemented from oomph::RefineableElement.
Reimplemented in oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement.
     {
       // Find the father element
       RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations*
         cast_father_element_pt = dynamic_cast<
           RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations*>(
           this->father_element_pt());
       // Set the viscosity ratio pointer
       this->Viscosity_Ratio_pt = cast_father_element_pt->viscosity_ratio_pt();
       // Set the density ratio pointer
       this->Density_Ratio_pt = cast_father_element_pt->density_ratio_pt();
       // Set pointer to global Reynolds number
       this->Re_pt = cast_father_element_pt->re_pt();
       // Set pointer to global Reynolds number x Strouhal number (=Womersley)
       this->ReSt_pt = cast_father_element_pt->re_st_pt();
       // Set pointer to global Reynolds number x inverse Froude number
       this->ReInvFr_pt = cast_father_element_pt->re_invfr_pt();
       // Set pointer to the global Reynolds number x inverse Rossby number
       this->ReInvRo_pt = cast_father_element_pt->re_invro_pt();
       // Set pointer to global gravity Vector
       this->G_pt = cast_father_element_pt->g_pt();
       // Set pointer to body force function
       this->Body_force_fct_pt =
         cast_father_element_pt->axi_nst_body_force_fct_pt();
       // Set pointer to volumetric source function
       this->Source_fct_pt = cast_father_element_pt->source_fct_pt();
       // Set the ALE_is_disabled flag
       this->ALE_is_disabled = cast_father_element_pt->ALE_is_disabled;
     }
References oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::ALE_is_disabled, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::axi_nst_body_force_fct_pt, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Body_force_fct_pt, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Density_Ratio_pt, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::density_ratio_pt(), oomph::RefineableElement::father_element_pt(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::G_pt, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::g_pt(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::re_invfr_pt(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::re_invro_pt(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Re_pt, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::re_pt(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::re_st_pt(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::ReInvFr_pt, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::ReInvRo_pt, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::ReSt_pt, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::source_fct_pt, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Source_fct_pt, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Viscosity_Ratio_pt, and oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::viscosity_ratio_pt().
Referenced by oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::further_build().
geometric_jacobian()
double oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::geometric_jacobian (const Vector< double > & x) inline virtual
Fill in the geometric Jacobian, which in this case is r.
Reimplemented from oomph::ElementWithZ2ErrorEstimator.
     {
       return x[0];
     }
References plotDoE::x.
get_dresidual_dnodal_coordinates()
void oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates (RankThreeTensor< double > & dresidual_dnodal_coordinates) virtual
Compute derivatives of elemental residual vector with respect to nodal coordinates. This function computes these terms analytically and overwrites the default implementation in the FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}
Compute derivatives of elemental residual vector with respect to nodal coordinates. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij} Overloads the FD-based version in the FiniteElement base class.
Reimplemented from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
   {
     // Create an Oomph Lib warning
     std::string warning_message = "This function has not been tested.\n";
     std::string function =
       "RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::\n";
     function += "get_dresidual_dnodal_coordinates(...)";
     OomphLibWarning(warning_message, function, OOMPH_EXCEPTION_LOCATION);
     // Return immediately if there are no dofs
     if (ndof() == 0)
     {
       return;
     }
     // Determine number of nodes in element
     const unsigned n_node = nnode();
     // Get continuous time from timestepper of first node
     double time = node_pt(0)->time_stepper_pt()->time_pt()->time();
     // Determine number of pressure dofs in element
     const unsigned n_pres = this->npres_axi_nst();
     // Find the indices at which the local velocities are stored
     unsigned u_nodal_index[3];
     for (unsigned i = 0; i < 3; i++)
     {
       u_nodal_index[i] = this->u_index_axi_nst(i);
     }
     // Which nodal value represents the pressure? (Negative if pressure
     // is not based on nodal interpolation).
     const int p_index = this->p_nodal_index_axi_nst();
     // Local array of booleans that are true if the l-th pressure value is
     // hanging (avoid repeated virtual function calls)
     bool pressure_dof_is_hanging[n_pres];
     // If the pressure is stored at a node
     if (p_index >= 0)
     {
       // Read out whether the pressure is hanging
       for (unsigned l = 0; l < n_pres; ++l)
       {
         pressure_dof_is_hanging[l] = pressure_node_pt(l)->is_hanging(p_index);
       }
     }
     // Otherwise the pressure is not stored at a node and so cannot hang
     else
     {
       for (unsigned l = 0; l < n_pres; ++l)
       {
         pressure_dof_is_hanging[l] = false;
       }
     }
     // Set up memory for the shape and test functions
     // Note that there are only two dimensions, r and z, in this problem
     Shape psif(n_node), testf(n_node);
     DShape dpsifdx(n_node, 2), dtestfdx(n_node, 2);
     // Set up memory for pressure shape and test functions
     Shape psip(n_pres), testp(n_pres);
     // Determine number of shape controlling nodes
     const unsigned n_shape_controlling_node = nshape_controlling_nodes();
     // Deriatives of shape fct derivatives w.r.t. nodal coords
     RankFourTensor<double> d_dpsifdx_dX(2, n_shape_controlling_node, n_node, 2);
     RankFourTensor<double> d_dtestfdx_dX(
       2, n_shape_controlling_node, n_node, 2);
     // Derivative of Jacobian of mapping w.r.t. to nodal coords
     DenseMatrix<double> dJ_dX(2, n_shape_controlling_node);
     // Derivatives of derivative of u w.r.t. nodal coords
     // Note that the entry d_dudx_dX(p,q,i,k) contains the derivative w.r.t.
     // nodal coordinate X_pq of du_i/dx_k. Since there are three velocity
     // components, i can take on the values 0, 1 and 2, while k and p only
     // take on the values 0 and 1 since there are only two spatial dimensions.
     RankFourTensor<double> d_dudx_dX(2, n_shape_controlling_node, 3, 2);
     // Derivatives of nodal velocities w.r.t. nodal coords:
     // Assumption: Interaction only local via no-slip so
     // X_pq only affects U_iq.
     // Note that the entry d_U_dX(p,q,i) contains the derivative w.r.t. nodal
     // coordinate X_pq of nodal value U_iq. In other words this entry is the
     // derivative of the i-th velocity component w.r.t. the p-th spatial
     // coordinate, taken at the q-th local node.
     RankThreeTensor<double> d_U_dX(2, n_shape_controlling_node, 3, 0.0);
     // Determine the number of integration points
     const unsigned n_intpt = integral_pt()->nweight();
     // Vector to hold local coordinates (two dimensions)
     Vector<double> s(2);
     // Get physical variables from element
     // (Reynolds number must be multiplied by the density ratio)
     const double scaled_re = this->re() * this->density_ratio();
     const double scaled_re_st = this->re_st() * this->density_ratio();
     const double scaled_re_inv_fr = this->re_invfr() * this->density_ratio();
     const double scaled_re_inv_ro = this->re_invro() * this->density_ratio();
     const double visc_ratio = this->viscosity_ratio();
     const Vector<double> G = this->g();
     // FD step
     double eps_fd = GeneralisedElement::Default_fd_jacobian_step;
     // Pre-compute derivatives of nodal velocities w.r.t. nodal coords:
     // Assumption: Interaction only local via no-slip so
     // X_ij only affects U_ij.
     bool element_has_node_with_aux_node_update_fct = false;
     std::map<Node*, unsigned> local_shape_controlling_node_lookup =
       shape_controlling_node_lookup();
     // FD loop over shape-controlling nodes
     for (std::map<Node*, unsigned>::iterator it =
            local_shape_controlling_node_lookup.begin();
          it != local_shape_controlling_node_lookup.end();
          it++)
     {
       // Get pointer to q-th local shape-controlling node
       Node* nod_pt = it->first;
       // Get its number
       unsigned q = it->second;
       // Only compute if there's a node-update fct involved
       if (nod_pt->has_auxiliary_node_update_fct_pt())
       {
         element_has_node_with_aux_node_update_fct = true;
         // This functionality has not been tested so issue a warning
         // to this effect
         std::ostringstream warning_stream;
         warning_stream << "\nThe functionality to evaluate the additional"
                        << "\ncontribution to the deriv of the residual eqn"
                        << "\nw.r.t. the nodal coordinates which comes about"
                        << "\nif a node's values are updated using an auxiliary"
                        << "\nnode update function has NOT been tested for"
                        << "\nrefineable axisymmetric Navier-Stokes elements."
                        << "\nUse at your own risk" << std::endl;
         OomphLibWarning(warning_stream.str(),
                         "RefineableGeneralisedNewtonianAxisymmetricNavierStokes"
                         "Equations::get_dresidual_dnodal_coordinates",
                         OOMPH_EXCEPTION_LOCATION);
         // Current nodal velocity
         Vector<double> u_ref(3);
         for (unsigned i = 0; i < 3; i++)
         {
           u_ref[i] = *(nod_pt->value_pt(u_nodal_index[i]));
         }
         // FD
         for (unsigned p = 0; p < 2; p++)
         {
           // Make backup
           double backup = nod_pt->x(p);
           // Do FD step. No node update required as we're
           // attacking the coordinate directly...
           nod_pt->x(p) += eps_fd;
           // Do auxiliary node update (to apply no slip)
           nod_pt->perform_auxiliary_node_update_fct();
           // Loop over velocity components
           for (unsigned i = 0; i < 3; i++)
           {
             // Evaluate
             d_U_dX(p, q, i) =
               (*(nod_pt->value_pt(u_nodal_index[p])) - u_ref[p]) / eps_fd;
           }
           // Reset
           nod_pt->x(p) = backup;
           // Do auxiliary node update (to apply no slip)
           nod_pt->perform_auxiliary_node_update_fct();
         }
       }
     }
     // Integer to store the local equation number
     int local_eqn = 0;
     // Pointers to hang info object
     HangInfo* hang_info_pt = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < 2; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       const double w = integral_pt()->weight(ipt);
       // Call the derivatives of the shape and test functions
       const double J =
         this->dshape_and_dtest_eulerian_at_knot_axi_nst(ipt,
                                                         psif,
                                                         dpsifdx,
                                                         d_dpsifdx_dX,
                                                         testf,
                                                         dtestfdx,
                                                         d_dtestfdx_dX,
                                                         dJ_dX);
       // Call the pressure shape and test functions
       this->pshape_axi_nst(s, psip, testp);
       // Allocate storage for the position and the derivative of the
       // mesh positions w.r.t. time
       Vector<double> interpolated_x(2, 0.0);
       Vector<double> mesh_velocity(2, 0.0);
       // Allocate storage for the pressure, velocity components and their
       // time and spatial derivatives
       double interpolated_p = 0.0;
       Vector<double> interpolated_u(3, 0.0);
       Vector<double> dudt(3, 0.0);
       DenseMatrix<double> interpolated_dudx(3, 2, 0.0);
       // Calculate pressure at integration point
       for (unsigned l = 0; l < n_pres; l++)
       {
         interpolated_p += this->p_axi_nst(l) * psip[l];
       }
       // Calculate velocities and derivatives at integration point
       // ---------------------------------------------------------
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Cache the shape function
         const double psif_ = psif(l);
         // Loop over the two coordinate directions
         for (unsigned i = 0; i < 2; i++)
         {
           interpolated_x[i] += nodal_position(l, i) * psif_;
         }
         // Loop over the three velocity directions
         for (unsigned i = 0; i < 3; i++)
         {
           // Get the nodal value
           const double u_value = nodal_value(l, u_nodal_index[i]);
           interpolated_u[i] += u_value * psif_;
           dudt[i] += this->du_dt_axi_nst(l, i) * psif_;
           // Loop over derivative directions
           for (unsigned j = 0; j < 2; j++)
           {
             interpolated_dudx(i, j) += u_value * dpsifdx(l, j);
           }
         }
       }
       // Get the mesh velocity if ALE is enabled
       if (!this->ALE_is_disabled)
       {
         // Loop over nodes
         for (unsigned l = 0; l < n_node; l++)
         {
           // Loop over the two coordinate directions
           for (unsigned i = 0; i < 2; i++)
           {
             mesh_velocity[i] += this->dnodal_position_dt(l, i) * psif[l];
           }
         }
       }
       // Calculate derivative of du_i/dx_k w.r.t. nodal positions X_{pq}
       // Loop over shape-controlling nodes
       for (unsigned q = 0; q < n_shape_controlling_node; q++)
       {
         // Loop over the two coordinate directions
         for (unsigned p = 0; p < 2; p++)
         {
           // Loop over the three velocity components
           for (unsigned i = 0; i < 3; i++)
           {
             // Loop over the two coordinate directions
             for (unsigned k = 0; k < 2; k++)
             {
               double aux = 0.0;
               // Loop over nodes and add contribution
               for (unsigned j = 0; j < n_node; j++)
               {
                 aux +=
                   nodal_value(j, u_nodal_index[i]) * d_dpsifdx_dX(p, q, j, k);
               }
               d_dudx_dX(p, q, i, k) = aux;
             }
           }
         }
       }
       // Get weight of actual nodal position/value in computation of mesh
       // velocity from positional/value time stepper
       const double pos_time_weight =
         node_pt(0)->position_time_stepper_pt()->weight(1, 0);
       const double val_time_weight =
         node_pt(0)->time_stepper_pt()->weight(1, 0);
       // Get the user-defined body force terms
       Vector<double> body_force(3);
       this->get_body_force_axi_nst(time, ipt, s, interpolated_x, body_force);
       // Get the user-defined source function
       const double source = this->get_source_fct(time, ipt, interpolated_x);
       // Get gradient of body force function
       DenseMatrix<double> d_body_force_dx(3, 2, 0.0);
       this->get_body_force_gradient_axi_nst(
         time, ipt, s, interpolated_x, d_body_force_dx);
       // Get gradient of source function
       Vector<double> source_gradient(2, 0.0);
       this->get_source_fct_gradient(time, ipt, interpolated_x, source_gradient);
       // Cache r (the first position component)
       const double r = interpolated_x[0];
       // Assemble shape derivatives
       // --------------------------
       // ==================
       // MOMENTUM EQUATIONS
       // ==================
       // Number of master nodes and storage for the weight of the shape function
       unsigned n_master = 1;
       double hang_weight = 1.0;
       // Loop over the test functions
       for (unsigned l = 0; l < n_node; l++)
       {
         // Cache the test function
         const double testf_ = testf[l];
         // Local boolean to indicate whether the node is hanging
         bool is_node_hanging = node_pt(l)->is_hanging();
         // If the node is hanging
         if (is_node_hanging)
         {
           hang_info_pt = node_pt(l)->hanging_pt();
           // Read out number of master nodes from hanging data
           n_master = hang_info_pt->nmaster();
         }
         // Otherwise the node is its own master
         else
         {
           n_master = 1;
         }
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // --------------------------------
           // FIRST (RADIAL) MOMENTUM EQUATION
           // --------------------------------
           // Get the equation number
           // If the node is hanging
           if (is_node_hanging)
           {
             // Get the equation number from the master node
             local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                              u_nodal_index[0]);
             // Get the hang weight from the master node
             hang_weight = hang_info_pt->master_weight(m);
           }
           // If the node is not hanging
           else
           {
             // Local equation number
             local_eqn = this->nodal_local_eqn(l, u_nodal_index[0]);
             // Node contributes with full weight
             hang_weight = 1.0;
           }
           // If it's not a boundary condition
           if (local_eqn >= 0)
           {
             // Loop over the two coordinate directions
             for (unsigned p = 0; p < 2; p++)
             {
               // Loop over shape controlling nodes
               for (unsigned q = 0; q < n_shape_controlling_node; q++)
               {
                 // Residual x deriv of Jacobian
                 // ----------------------------
                 // Add the user-defined body force terms
                 double sum = r * body_force[0] * testf_;
                 // Add the gravitational body force term
                 sum += r * scaled_re_inv_fr * testf_ * G[0];
                 // Add the pressure gradient term
                 sum += interpolated_p * (testf_ + r * dtestfdx(l, 0));
                 // Add the stress tensor terms
                 // The viscosity ratio needs to go in here to ensure
                 // continuity of normal stress is satisfied even in flows
                 // with zero pressure gradient!
                 sum -= visc_ratio * r * (1.0 + Gamma[0]) *
                        interpolated_dudx(0, 0) * dtestfdx(l, 0);
                 sum -= visc_ratio * r *
                        (interpolated_dudx(0, 1) +
                         Gamma[0] * interpolated_dudx(1, 0)) *
                        dtestfdx(l, 1);
                 sum -= visc_ratio * (1.0 + Gamma[0]) * interpolated_u[0] *
                        testf_ / r;
                 // Add the du/dt term
                 sum -= scaled_re_st * r * dudt[0] * testf_;
                 // Add the convective terms
                 sum -= scaled_re *
                        (r * interpolated_u[0] * interpolated_dudx(0, 0) -
                         interpolated_u[2] * interpolated_u[2] +
                         r * interpolated_u[1] * interpolated_dudx(0, 1)) *
                        testf_;
                 // Add the mesh velocity terms
                 if (!ALE_is_disabled)
                 {
                   for (unsigned k = 0; k < 2; k++)
                   {
                     sum += scaled_re_st * r * mesh_velocity[k] *
                            interpolated_dudx(0, k) * testf_;
                   }
                 }
                 // Add the Coriolis term
                 sum += 2.0 * r * scaled_re_inv_ro * interpolated_u[2] * testf_;
                 // Multiply through by deriv of Jacobian and integration weight
                 dresidual_dnodal_coordinates(local_eqn, p, q) +=
                   sum * dJ_dX(p, q) * w * hang_weight;
                 // Derivative of residual x Jacobian
                 // ---------------------------------
                 // Body force
                 sum = r * d_body_force_dx(0, p) * psif[q] * testf_;
                 if (p == 0)
                 {
                   sum += body_force[0] * psif[q] * testf_;
                 }
                 // Gravitational body force
                 if (p == 0)
                 {
                   sum += scaled_re_inv_fr * G[0] * psif[q] * testf_;
                 }
                 // Pressure gradient term
                 sum += r * interpolated_p * d_dtestfdx_dX(p, q, l, 0);
                 if (p == 0)
                 {
                   sum += interpolated_p * psif[q] * dtestfdx(l, 0);
                 }
                 // Viscous terms
                 sum -=
                   r * visc_ratio *
                   ((1.0 + Gamma[0]) *
                      (d_dudx_dX(p, q, 0, 0) * dtestfdx(l, 0) +
                       interpolated_dudx(0, 0) * d_dtestfdx_dX(p, q, l, 0)) +
                    (d_dudx_dX(p, q, 0, 1) + Gamma[0] * d_dudx_dX(p, q, 1, 0)) *
                      dtestfdx(l, 1) +
                    (interpolated_dudx(0, 1) +
                     Gamma[0] * interpolated_dudx(1, 0)) *
                      d_dtestfdx_dX(p, q, l, 1));
                 if (p == 0)
                 {
                   sum -=
                     visc_ratio *
                     ((1.0 + Gamma[0]) *
                        (interpolated_dudx(0, 0) * psif[q] * dtestfdx(l, 0) -
                         interpolated_u[0] * psif[q] * testf_ / (r * r)) +
                      (interpolated_dudx(0, 1) +
                       Gamma[0] * interpolated_dudx(1, 0)) *
                        psif[q] * dtestfdx(l, 1));
                 }
                 // Convective terms, including mesh velocity
                 for (unsigned k = 0; k < 2; k++)
                 {
                   double tmp = scaled_re * interpolated_u[k];
                   if (!ALE_is_disabled)
                   {
                     tmp -= scaled_re_st * mesh_velocity[k];
                   }
                   sum -= r * tmp * d_dudx_dX(p, q, 0, k) * testf_;
                   if (p == 0)
                   {
                     sum -= tmp * interpolated_dudx(0, k) * psif[q] * testf_;
                   }
                 }
                 if (!ALE_is_disabled)
                 {
                   sum += scaled_re_st * r * pos_time_weight *
                          interpolated_dudx(0, p) * psif[q] * testf_;
                 }
                 // du/dt term
                 if (p == 0)
                 {
                   sum -= scaled_re_st * dudt[0] * psif[q] * testf_;
                 }
                 // Coriolis term
                 if (p == 0)
                 {
                   sum += 2.0 * scaled_re_inv_ro * interpolated_u[2] * psif[q] *
                          testf_;
                 }
                 // Multiply through by Jacobian and integration weight
                 dresidual_dnodal_coordinates(local_eqn, p, q) +=
                   sum * J * w * hang_weight;
               } // End of loop over shape controlling nodes q
             } // End of loop over coordinate directions p
             // Derivs w.r.t. to nodal velocities
             // ---------------------------------
             if (element_has_node_with_aux_node_update_fct)
             {
               // Loop over local nodes
               for (unsigned q_local = 0; q_local < n_node; q_local++)
               {
                 // Number of master nodes and storage for the weight of
                 // the shape function
                 unsigned n_master2 = 1;
                 double hang_weight2 = 1.0;
                 HangInfo* hang_info2_pt = 0;
                 // Local boolean to indicate whether the node is hanging
                 bool is_node_hanging2 = node_pt(q_local)->is_hanging();
                 Node* actual_shape_controlling_node_pt = node_pt(q_local);
                 // If the node is hanging
                 if (is_node_hanging2)
                 {
                   hang_info2_pt = node_pt(q_local)->hanging_pt();
                   // Read out number of master nodes from hanging data
                   n_master2 = hang_info2_pt->nmaster();
                 }
                 // Otherwise the node is its own master
                 else
                 {
                   n_master2 = 1;
                 }
                 // Loop over the master nodes
                 for (unsigned mm = 0; mm < n_master2; mm++)
                 {
                   if (is_node_hanging2)
                   {
                     actual_shape_controlling_node_pt =
                       hang_info2_pt->master_node_pt(mm);
                     hang_weight2 = hang_info2_pt->master_weight(mm);
                   }
                   // Find the corresponding number
                   unsigned q = local_shape_controlling_node_lookup
                     [actual_shape_controlling_node_pt];
                   // Loop over the two coordinate directions
                   for (unsigned p = 0; p < 2; p++)
                   {
                     // Contribution from deriv of first velocity component
                     double tmp = scaled_re_st * r * val_time_weight *
                                  psif[q_local] * testf_;
                     tmp += r * scaled_re * interpolated_dudx(0, 0) *
                            psif[q_local] * testf_;
                     for (unsigned k = 0; k < 2; k++)
                     {
                       double tmp2 = scaled_re * interpolated_u[k];
                       if (!ALE_is_disabled)
                       {
                         tmp2 -= scaled_re_st * mesh_velocity[k];
                       }
                       tmp += r * tmp2 * dpsifdx(q_local, k) * testf_;
                     }
                     tmp += r * visc_ratio * (1.0 + Gamma[0]) *
                            dpsifdx(q_local, 0) * dtestfdx(l, 0);
                     tmp +=
                       r * visc_ratio * dpsifdx(q_local, 1) * dtestfdx(l, 1);
                     tmp += visc_ratio * (1.0 + Gamma[0]) * psif[q_local] *
                            testf_ / r;
                     // Multiply through by dU_0q/dX_pq
                     double sum = -d_U_dX(p, q_local, 0) * tmp;
                     // Contribution from deriv of second velocity component
                     tmp = scaled_re * r * interpolated_dudx(0, 1) *
                           psif[q_local] * testf_;
                     tmp += r * visc_ratio * Gamma[0] * dpsifdx(q_local, 0) *
                            dtestfdx(l, 1);
                     // Multiply through by dU_1q/dX_pq
                     sum -= d_U_dX(p, q, 1) * tmp;
                     // Contribution from deriv of third velocity component
                     tmp =
                       2.0 *
                       (r * scaled_re_inv_ro + scaled_re * interpolated_u[2]) *
                       psif[q_local] * testf_;
                     // Multiply through by dU_2q/dX_pq
                     sum += d_U_dX(p, q, 2) * tmp;
                     // Multiply through by Jacobian and integration weight
                     dresidual_dnodal_coordinates(local_eqn, p, q) +=
                       sum * J * w * hang_weight * hang_weight2;
                   }
                 } // End of loop over master nodes
               } // End of loop over local nodes
             } // End of if(element_has_node_with_aux_node_update_fct)
           } // End of if it's not a boundary condition
           // --------------------------------
           // SECOND (AXIAL) MOMENTUM EQUATION
           // --------------------------------
           // Get the equation number
           // If the node is hanging
           if (is_node_hanging)
           {
             // Get the equation number from the master node
             local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                              u_nodal_index[1]);
             // Get the hang weight from the master node
             hang_weight = hang_info_pt->master_weight(m);
           }
           // If the node is not hanging
           else
           {
             // Local equation number
             local_eqn = this->nodal_local_eqn(l, u_nodal_index[1]);
             // Node contributes with full weight
             hang_weight = 1.0;
           }
           // If it's not a boundary condition
           if (local_eqn >= 0)
           {
             // Loop over the two coordinate directions
             for (unsigned p = 0; p < 2; p++)
             {
               // Loop over shape controlling nodes
               for (unsigned q = 0; q < n_shape_controlling_node; q++)
               {
                 // Residual x deriv of Jacobian
                 // ----------------------------
                 // Add the user-defined body force terms
                 double sum = r * body_force[1] * testf_;
                 // Add the gravitational body force term
                 sum += r * scaled_re_inv_fr * testf_ * G[1];
                 // Add the pressure gradient term
                 sum += r * interpolated_p * dtestfdx(l, 1);
                 // Add the stress tensor terms
                 // The viscosity ratio needs to go in here to ensure
                 // continuity of normal stress is satisfied even in flows
                 // with zero pressure gradient!
                 sum -= visc_ratio * r *
                        (interpolated_dudx(1, 0) +
                         Gamma[1] * interpolated_dudx(0, 1)) *
                        dtestfdx(l, 0);
                 sum -= visc_ratio * r * (1.0 + Gamma[1]) *
                        interpolated_dudx(1, 1) * dtestfdx(l, 1);
                 // Add the du/dt term
                 sum -= scaled_re_st * r * dudt[1] * testf_;
                 // Add the convective terms
                 sum -= scaled_re *
                        (r * interpolated_u[0] * interpolated_dudx(1, 0) +
                         r * interpolated_u[1] * interpolated_dudx(1, 1)) *
                        testf_;
                 // Add the mesh velocity terms
                 if (!ALE_is_disabled)
                 {
                   for (unsigned k = 0; k < 2; k++)
                   {
                     sum += scaled_re_st * r * mesh_velocity[k] *
                            interpolated_dudx(1, k) * testf_;
                   }
                 }
                 // Multiply through by deriv of Jacobian and integration weight
                 dresidual_dnodal_coordinates(local_eqn, p, q) +=
                   sum * dJ_dX(p, q) * w * hang_weight;
                 // Derivative of residual x Jacobian
                 // ---------------------------------
                 // Body force
                 sum = r * d_body_force_dx(1, p) * psif[q] * testf_;
                 if (p == 0)
                 {
                   sum += body_force[1] * psif[q] * testf_;
                 }
                 // Gravitational body force
                 if (p == 0)
                 {
                   sum += scaled_re_inv_fr * G[1] * psif[q] * testf_;
                 }
                 // Pressure gradient term
                 sum += r * interpolated_p * d_dtestfdx_dX(p, q, l, 1);
                 if (p == 0)
                 {
                   sum += interpolated_p * psif[q] * dtestfdx(l, 1);
                 }
                 // Viscous terms
                 sum -=
                   r * visc_ratio *
                   ((d_dudx_dX(p, q, 1, 0) + Gamma[1] * d_dudx_dX(p, q, 0, 1)) *
                      dtestfdx(l, 0) +
                    (interpolated_dudx(1, 0) +
                     Gamma[1] * interpolated_dudx(0, 1)) *
                      d_dtestfdx_dX(p, q, l, 0) +
                    (1.0 + Gamma[1]) * d_dudx_dX(p, q, 1, 1) * dtestfdx(l, 1) +
                    (1.0 + Gamma[1]) * interpolated_dudx(1, 1) *
                      d_dtestfdx_dX(p, q, l, 1));
                 if (p == 0)
                 {
                   sum -=
                     visc_ratio * ((interpolated_dudx(1, 0) +
                                    Gamma[1] * interpolated_dudx(0, 1)) *
                                     psif[q] * dtestfdx(l, 0) +
                                   (1.0 + Gamma[1]) * interpolated_dudx(1, 1) *
                                     psif[q] * dtestfdx(l, 1));
                 }
                 // Convective terms, including mesh velocity
                 for (unsigned k = 0; k < 2; k++)
                 {
                   double tmp = scaled_re * interpolated_u[k];
                   if (!ALE_is_disabled)
                   {
                     tmp -= scaled_re_st * mesh_velocity[k];
                   }
                   sum -= r * tmp * d_dudx_dX(p, q, 1, k) * testf_;
                   if (p == 0)
                   {
                     sum -= tmp * interpolated_dudx(1, k) * psif[q] * testf_;
                   }
                 }
                 if (!ALE_is_disabled)
                 {
                   sum += scaled_re_st * r * pos_time_weight *
                          interpolated_dudx(1, p) * psif[q] * testf_;
                 }
                 // du/dt term
                 if (p == 0)
                 {
                   sum -= scaled_re_st * dudt[1] * psif[q] * testf_;
                 }
                 // Multiply through by Jacobian and integration weight
                 dresidual_dnodal_coordinates(local_eqn, p, q) +=
                   sum * J * w * hang_weight;
               } // End of loop over shape controlling nodes q
             } // End of loop over coordinate directions p
             // Derivs w.r.t. to nodal velocities
             // ---------------------------------
             if (element_has_node_with_aux_node_update_fct)
             {
               // Loop over local nodes
               for (unsigned q_local = 0; q_local < n_node; q_local++)
               {
                 // Number of master nodes and storage for the weight of
                 // the shape function
                 unsigned n_master2 = 1;
                 double hang_weight2 = 1.0;
                 HangInfo* hang_info2_pt = 0;
                 // Local boolean to indicate whether the node is hanging
                 bool is_node_hanging2 = node_pt(q_local)->is_hanging();
                 Node* actual_shape_controlling_node_pt = node_pt(q_local);
                 // If the node is hanging
                 if (is_node_hanging2)
                 {
                   hang_info2_pt = node_pt(q_local)->hanging_pt();
                   // Read out number of master nodes from hanging data
                   n_master2 = hang_info2_pt->nmaster();
                 }
                 // Otherwise the node is its own master
                 else
                 {
                   n_master2 = 1;
                 }
                 // Loop over the master nodes
                 for (unsigned mm = 0; mm < n_master2; mm++)
                 {
                   if (is_node_hanging2)
                   {
                     actual_shape_controlling_node_pt =
                       hang_info2_pt->master_node_pt(mm);
                     hang_weight2 = hang_info2_pt->master_weight(mm);
                   }
                   // Find the corresponding number
                   unsigned q = local_shape_controlling_node_lookup
                     [actual_shape_controlling_node_pt];
                   // Loop over the two coordinate directions
                   for (unsigned p = 0; p < 2; p++)
                   {
                     // Contribution from deriv of first velocity component
                     double tmp = scaled_re * r * interpolated_dudx(1, 0) *
                                  psif[q_local] * testf_;
                     tmp += r * visc_ratio * Gamma[1] * dpsifdx(q_local, 1) *
                            dtestfdx(l, 0);
                     // Multiply through by dU_0q/dX_pq
                     double sum = -d_U_dX(p, q, 0) * tmp;
                     // Contribution from deriv of second velocity component
                     tmp = scaled_re_st * r * val_time_weight * psif[q_local] *
                           testf_;
                     tmp += r * scaled_re * interpolated_dudx(1, 1) *
                            psif[q_local] * testf_;
                     for (unsigned k = 0; k < 2; k++)
                     {
                       double tmp2 = scaled_re * interpolated_u[k];
                       if (!ALE_is_disabled)
                       {
                         tmp2 -= scaled_re_st * mesh_velocity[k];
                       }
                       tmp += r * tmp2 * dpsifdx(q_local, k) * testf_;
                     }
                     tmp +=
                       r * visc_ratio *
                       (dpsifdx(q_local, 0) * dtestfdx(l, 0) +
                        (1.0 + Gamma[1]) * dpsifdx(q_local, 1) * dtestfdx(l, 1));
                     // Multiply through by dU_1q/dX_pq
                     sum -= d_U_dX(p, q, 1) * tmp;
                     // Multiply through by Jacobian and integration weight
                     dresidual_dnodal_coordinates(local_eqn, p, q) +=
                       sum * J * w * hang_weight * hang_weight2;
                   }
                 } // End of loop over master nodes
               } // End of loop over local nodes
             } // End of if(element_has_node_with_aux_node_update_fct)
           } // End of if it's not a boundary condition
           // -----------------------------------
           // THIRD (AZIMUTHAL) MOMENTUM EQUATION
           // -----------------------------------
           // Get the equation number
           // If the node is hanging
           if (is_node_hanging)
           {
             // Get the equation number from the master node
             local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                              u_nodal_index[2]);
             // Get the hang weight from the master node
             hang_weight = hang_info_pt->master_weight(m);
           }
           // If the node is not hanging
           else
           {
             // Local equation number
             local_eqn = this->nodal_local_eqn(l, u_nodal_index[2]);
             // Node contributes with full weight
             hang_weight = 1.0;
           }
           // If it's not a boundary condition
           if (local_eqn >= 0)
           {
             // Loop over the two coordinate directions
             for (unsigned p = 0; p < 2; p++)
             {
               // Loop over shape controlling nodes
               for (unsigned q = 0; q < n_shape_controlling_node; q++)
               {
                 // Residual x deriv of Jacobian
                 // ----------------------------
                 // Add the user-defined body force terms
                 double sum = r * body_force[2] * testf_;
                 // Add the gravitational body force term
                 sum += r * scaled_re_inv_fr * testf_ * G[2];
                 // There is NO pressure gradient term
                 // Add in the stress tensor terms
                 // The viscosity ratio needs to go in here to ensure
                 // continuity of normal stress is satisfied even in flows
                 // with zero pressure gradient!
                 sum -=
                   visc_ratio *
                   (r * interpolated_dudx(2, 0) - Gamma[0] * interpolated_u[2]) *
                   dtestfdx(l, 0);
                 sum -=
                   visc_ratio * r * interpolated_dudx(2, 1) * dtestfdx(l, 1);
                 sum -= visc_ratio *
                        ((interpolated_u[2] / r) -
                         Gamma[0] * interpolated_dudx(2, 0)) *
                        testf_;
                 // Add the du/dt term
                 sum -= scaled_re_st * r * dudt[2] * testf_;
                 // Add the convective terms
                 sum -= scaled_re *
                        (r * interpolated_u[0] * interpolated_dudx(2, 0) +
                         interpolated_u[0] * interpolated_u[2] +
                         r * interpolated_u[1] * interpolated_dudx(2, 1)) *
                        testf_;
                 // Add the mesh velocity terms
                 if (!ALE_is_disabled)
                 {
                   for (unsigned k = 0; k < 2; k++)
                   {
                     sum += scaled_re_st * r * mesh_velocity[k] *
                            interpolated_dudx(2, k) * testf_;
                   }
                 }
                 // Add the Coriolis term
                 sum -= 2.0 * r * scaled_re_inv_ro * interpolated_u[0] * testf_;
                 // Multiply through by deriv of Jacobian and integration weight
                 dresidual_dnodal_coordinates(local_eqn, p, q) +=
                   sum * dJ_dX(p, q) * w * hang_weight;
                 // Derivative of residual x Jacobian
                 // ---------------------------------
                 // Body force
                 sum = r * d_body_force_dx(2, p) * psif[q] * testf_;
                 if (p == 0)
                 {
                   sum += body_force[2] * psif[q] * testf_;
                 }
                 // Gravitational body force
                 if (p == 0)
                 {
                   sum += scaled_re_inv_fr * G[2] * psif[q] * testf_;
                 }
                 // There is NO pressure gradient term
                 // Viscous terms
                 sum -= visc_ratio * r *
                        (d_dudx_dX(p, q, 2, 0) * dtestfdx(l, 0) +
                         interpolated_dudx(2, 0) * d_dtestfdx_dX(p, q, l, 0) +
                         d_dudx_dX(p, q, 2, 1) * dtestfdx(l, 1) +
                         interpolated_dudx(2, 1) * d_dtestfdx_dX(p, q, l, 1));
                 sum += visc_ratio * Gamma[0] * d_dudx_dX(p, q, 2, 0) * testf_;
                 if (p == 0)
                 {
                   sum -= visc_ratio *
                          (interpolated_dudx(2, 0) * psif[q] * dtestfdx(l, 0) +
                           interpolated_dudx(2, 1) * psif[q] * dtestfdx(l, 1) +
                           interpolated_u[2] * psif[q] * testf_ / (r * r));
                 }
                 // Convective terms, including mesh velocity
                 for (unsigned k = 0; k < 2; k++)
                 {
                   double tmp = scaled_re * interpolated_u[k];
                   if (!ALE_is_disabled)
                   {
                     tmp -= scaled_re_st * mesh_velocity[k];
                   }
                   sum -= r * tmp * d_dudx_dX(p, q, 2, k) * testf_;
                   if (p == 0)
                   {
                     sum -= tmp * interpolated_dudx(2, k) * psif[q] * testf_;
                   }
                 }
                 if (!ALE_is_disabled)
                 {
                   sum += scaled_re_st * r * pos_time_weight *
                          interpolated_dudx(2, p) * psif[q] * testf_;
                 }
                 // du/dt term
                 if (p == 0)
                 {
                   sum -= scaled_re_st * dudt[2] * psif[q] * testf_;
                 }
                 // Coriolis term
                 if (p == 0)
                 {
                   sum -= 2.0 * scaled_re_inv_ro * interpolated_u[0] * psif[q] *
                          testf_;
                 }
                 // Multiply through by Jacobian and integration weight
                 dresidual_dnodal_coordinates(local_eqn, p, q) +=
                   sum * J * w * hang_weight;
               } // End of loop over shape controlling nodes q
             } // End of loop over coordinate directions p
             // Derivs w.r.t. to nodal velocities
             // ---------------------------------
             if (element_has_node_with_aux_node_update_fct)
             {
               // Loop over local nodes
               for (unsigned q_local = 0; q_local < n_node; q_local++)
               {
                 // Number of master nodes and storage for the weight of
                 // the shape function
                 unsigned n_master2 = 1;
                 double hang_weight2 = 1.0;
                 HangInfo* hang_info2_pt = 0;
                 // Local boolean to indicate whether the node is hanging
                 bool is_node_hanging2 = node_pt(q_local)->is_hanging();
                 Node* actual_shape_controlling_node_pt = node_pt(q_local);
                 // If the node is hanging
                 if (is_node_hanging2)
                 {
                   hang_info2_pt = node_pt(q_local)->hanging_pt();
                   // Read out number of master nodes from hanging data
                   n_master2 = hang_info2_pt->nmaster();
                 }
                 // Otherwise the node is its own master
                 else
                 {
                   n_master2 = 1;
                 }
                 // Loop over the master nodes
                 for (unsigned mm = 0; mm < n_master2; mm++)
                 {
                   if (is_node_hanging2)
                   {
                     actual_shape_controlling_node_pt =
                       hang_info2_pt->master_node_pt(mm);
                     hang_weight2 = hang_info2_pt->master_weight(mm);
                   }
                   // Find the corresponding number
                   unsigned q = local_shape_controlling_node_lookup
                     [actual_shape_controlling_node_pt];
                   // Loop over the two coordinate directions
                   for (unsigned p = 0; p < 2; p++)
                   {
                     // Contribution from deriv of first velocity component
                     double tmp = (2.0 * r * scaled_re_inv_ro +
                                   r * scaled_re * interpolated_dudx(2, 0) -
                                   scaled_re * interpolated_u[2]) *
                                  psif[q_local] * testf_;
                     // Multiply through by dU_0q/dX_pq
                     double sum = -d_U_dX(p, q, 0) * tmp;
                     // Contribution from deriv of second velocity component
                     // Multiply through by dU_1q/dX_pq
                     sum -= d_U_dX(p, q, 1) * scaled_re * r *
                            interpolated_dudx(2, 1) * psif[q_local] * testf_;
                     // Contribution from deriv of third velocity component
                     tmp = scaled_re_st * r * val_time_weight * psif[q_local] *
                           testf_;
                     tmp -=
                       scaled_re * interpolated_u[0] * psif[q_local] * testf_;
                     for (unsigned k = 0; k < 2; k++)
                     {
                       double tmp2 = scaled_re * interpolated_u[k];
                       if (!ALE_is_disabled)
                       {
                         tmp2 -= scaled_re_st * mesh_velocity[k];
                       }
                       tmp += r * tmp2 * dpsifdx(q_local, k) * testf_;
                     }
                     tmp +=
                       visc_ratio *
                       (r * dpsifdx(q_local, 0) - Gamma[0] * psif[q_local]) *
                       dtestfdx(l, 0);
                     tmp +=
                       r * visc_ratio * dpsifdx(q_local, 1) * dtestfdx(l, 1);
                     tmp +=
                       visc_ratio *
                       ((psif[q_local] / r) - Gamma[0] * dpsifdx(q_local, 0)) *
                       testf_;
                     // Multiply through by dU_2q/dX_pq
                     sum -= d_U_dX(p, q, 2) * tmp;
                     // Multiply through by Jacobian and integration weight
                     dresidual_dnodal_coordinates(local_eqn, p, q) +=
                       sum * J * w * hang_weight * hang_weight2;
                   }
                 } // End of loop over master nodes
               } // End of loop over local nodes
             } // End of if(element_has_node_with_aux_node_update_fct)
           } // End of if it's not a boundary condition
         } // End of loop over master nodes
       } // End of loop over test functions
       // ===================
       // CONTINUITY EQUATION
       // ===================
       // Loop over the shape functions
       for (unsigned l = 0; l < n_pres; l++)
       {
         // If the pressure dof is hanging
         if (pressure_dof_is_hanging[l])
         {
           // Pressure dof is hanging so it must be nodal-based
           // Get the hang info object
           hang_info_pt = this->pressure_node_pt(l)->hanging_pt(p_index);
           // Get the number of master nodes from the pressure node
           n_master = hang_info_pt->nmaster();
         }
         // Otherwise the node is its own master
         else
         {
           n_master = 1;
         }
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // Get the number of the unknown
           // If the pressure dof is hanging
           if (pressure_dof_is_hanging[l])
           {
             // Get the local equation from the master node
             local_eqn =
               this->local_hang_eqn(hang_info_pt->master_node_pt(m), p_index);
             // Get the weight for the node
             hang_weight = hang_info_pt->master_weight(m);
           }
           else
           {
             local_eqn = this->p_local_eqn(l);
             hang_weight = 1.0;
           }
           // Cache the test function
           const double testp_ = testp[l];
           // If not a boundary conditions
           if (local_eqn >= 0)
           {
             // Loop over the two coordinate directions
             for (unsigned p = 0; p < 2; p++)
             {
               // Loop over shape controlling nodes
               for (unsigned q = 0; q < n_shape_controlling_node; q++)
               {
                 // Residual x deriv of Jacobian
                 //-----------------------------
                 // Source term
                 double aux = -r * source;
                 // Gradient terms
                 aux += (interpolated_u[0] + r * interpolated_dudx(0, 0) +
                         r * interpolated_dudx(1, 1));
                 // Multiply through by deriv of Jacobian and integration weight
                 dresidual_dnodal_coordinates(local_eqn, p, q) +=
                   aux * dJ_dX(p, q) * testp_ * w * hang_weight;
                 // Derivative of residual x Jacobian
                 // ---------------------------------
                 // Gradient of source function
                 aux = -r * source_gradient[p] * psif[q];
                 if (p == 0)
                 {
                   aux -= source * psif[q];
                 }
                 // Gradient terms
                 aux += r * (d_dudx_dX(p, q, 0, 0) + d_dudx_dX(p, q, 1, 1));
                 if (p == 0)
                 {
                   aux += (interpolated_dudx(0, 0) + interpolated_dudx(1, 1)) *
                          psif[q];
                 }
                 // Multiply through by Jacobian and integration weight
                 dresidual_dnodal_coordinates(local_eqn, p, q) +=
                   aux * testp_ * J * w * hang_weight;
               }
             }
             // Derivs w.r.t. to nodal velocities
             // ---------------------------------
             if (element_has_node_with_aux_node_update_fct)
             {
               // Loop over local nodes
               for (unsigned q_local = 0; q_local < n_node; q_local++)
               {
                 // Number of master nodes and storage for the weight of
                 // the shape function
                 unsigned n_master2 = 1;
                 double hang_weight2 = 1.0;
                 HangInfo* hang_info2_pt = 0;
                 // Local boolean to indicate whether the node is hanging
                 bool is_node_hanging2 = node_pt(q_local)->is_hanging();
                 Node* actual_shape_controlling_node_pt = node_pt(q_local);
                 // If the node is hanging
                 if (is_node_hanging2)
                 {
                   hang_info2_pt = node_pt(q_local)->hanging_pt();
                   // Read out number of master nodes from hanging data
                   n_master2 = hang_info2_pt->nmaster();
                 }
                 // Otherwise the node is its own master
                 else
                 {
                   n_master2 = 1;
                 }
                 // Loop over the master nodes
                 for (unsigned mm = 0; mm < n_master2; mm++)
                 {
                   if (is_node_hanging2)
                   {
                     actual_shape_controlling_node_pt =
                       hang_info2_pt->master_node_pt(mm);
                     hang_weight2 = hang_info2_pt->master_weight(mm);
                   }
                   // Find the corresponding number
                   unsigned q = local_shape_controlling_node_lookup
                     [actual_shape_controlling_node_pt];
                   // Loop over the two coordinate directions
                   for (unsigned p = 0; p < 2; p++)
                   {
                     double aux = d_U_dX(p, q, 0) *
                                    (psif[q_local] + r * dpsifdx(q_local, 0)) +
                                  d_U_dX(p, q, 1) * r * dpsifdx(q_local, 1);
                     // Multiply through by Jacobian, test function and
                     // integration weight
                     dresidual_dnodal_coordinates(local_eqn, p, q) +=
                       aux * testp_ * J * w * hang_weight * hang_weight2;
                   }
                 } // End of loop over (mm) master nodes
               } // End of loop over local nodes q_local
             } // End of if(element_has_node_with_aux_node_update_fct)
           } // End of if it's not a boundary condition
         } // End of loop over (m) master nodes
       } // End of loop over shape functions for continuity eqn
     } // End of loop over integration points
   } // End of get_dresidual_dnodal_coordinates(...)
References oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::ALE_is_disabled, Global_Parameters::body_force(), oomph::GeneralisedElement::Default_fd_jacobian_step, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::density_ratio(), oomph::FiniteElement::dnodal_position_dt(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::dshape_and_dtest_eulerian_at_knot_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::du_dt_axi_nst(), G, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::g(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Gamma, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_body_force_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_body_force_gradient_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_source_fct(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_source_fct_gradient(), oomph::Node::hanging_pt(), oomph::Node::has_auxiliary_node_update_fct_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::Node::is_hanging(), J, j, k, oomph::Integral::knot(), oomph::RefineableElement::local_hang_eqn(), m, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::GeneralisedElement::ndof(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::npres_axi_nst(), oomph::RefineableElement::nshape_controlling_nodes(), oomph::Integral::nweight(), OOMPH_EXCEPTION_LOCATION, p, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::p_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::p_local_eqn(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::p_nodal_index_axi_nst(), oomph::Node::perform_auxiliary_node_update_fct(), oomph::Node::position_time_stepper_pt(), pressure_node_pt(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::pshape_axi_nst(), Eigen::numext::q, UniformPSDSelfTest::r, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::re(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::re_invfr(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::re_invro(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::re_st(), s, oomph::RefineableElement::shape_controlling_node_lookup(), TestProblem::source(), oomph::Global_string_for_annotation::string(), oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Data::time_stepper_pt(), tmp, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::u_index_axi_nst(), oomph::Data::value_pt(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::viscosity_ratio(), w, oomph::Integral::weight(), oomph::TimeStepper::weight(), and oomph::Node::x().
get_Z2_flux()
void oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) inline virtual
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       // Specify the number of velocity dimensions
       unsigned DIM = 3;
 #ifdef PARANOID
       unsigned num_entries = DIM + ((DIM * DIM) - DIM) / 2;
       if (flux.size() < num_entries)
       {
         std::ostringstream error_message;
         error_message << "The flux vector has the wrong number of entries, "
                       << flux.size() << ", whereas it should be " << num_entries
                       << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Get strain rate matrix
       DenseMatrix<double> strainrate(DIM);
       this->strain_rate(s, strainrate);
       // Pack into flux Vector
       unsigned icount = 0;
       // Start with diagonal terms
       for (unsigned i = 0; i < DIM; i++)
       {
         flux[icount] = strainrate(i, i);
         icount++;
       }
       // Off diagonals row by row
       for (unsigned i = 0; i < DIM; i++)
       {
         for (unsigned j = i + 1; j < DIM; j++)
         {
           flux[icount] = strainrate(i, j);
           icount++;
         }
       }
     }
References DIM, ProblemParameters::flux(), i, j, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::strain_rate().
num_Z2_flux_terms()
unsigned oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::num_Z2_flux_terms () inline virtual
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       // 3 diagonal strain rates, 3 off diagonal
       return 6;
     }
pin_elemental_redundant_nodal_pressure_dofs()
virtual void oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::pin_elemental_redundant_nodal_pressure_dofs () inline protected virtual
Pin unused nodal pressure dofs (empty by default, because by default pressure dofs are not associated with nodes)
Reimplemented in oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement.
 {}
Referenced by pin_redundant_nodal_pressures().
pin_redundant_nodal_pressures()
static void oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > & element_pt) inline static
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function
RefineableAxisymmetricNavierStokesEquations:: pin_all_nodal_pressure_dofs()
which is empty by default and should be implemented for elements with nodal pressure degrees of freedom (e.g. for refineable Taylor-Hood.)
     {
       // Loop over all elements to brutally pin all nodal pressure degrees of
       // freedom
       unsigned n_element = element_pt.size();
       for (unsigned e = 0; e < n_element; e++)
       {
         dynamic_cast<
           RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations*>(
           element_pt[e])
           ->pin_elemental_redundant_nodal_pressure_dofs();
       }
     }
References e(), and pin_elemental_redundant_nodal_pressure_dofs().
pressure_node_pt()
virtual Node* oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::pressure_node_pt (const unsigned & n_p) inline protected virtual
Pointer to n_p-th pressure node (Default: NULL, indicating that pressure is not based on nodal interpolation).
Reimplemented in oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement.
     {
       return NULL;
     }
Referenced by fill_in_generic_residual_contribution_axi_nst(), and get_dresidual_dnodal_coordinates().
unpin_all_pressure_dofs()
static void oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::unpin_all_pressure_dofs (const Vector< GeneralisedElement * > & element_pt) inline static
Unpin all pressure dofs in elements listed in vector.
     {
       // Loop over all elements to brutally unpin all nodal pressure degrees of
       // freedom and internal pressure degrees of freedom
       unsigned n_element = element_pt.size();
       for (unsigned e = 0; e < n_element; e++)
       {
         dynamic_cast<
           RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations*>(
           element_pt[e])
           ->unpin_elemental_pressure_dofs();
       }
     }
References e(), and unpin_elemental_pressure_dofs().
unpin_elemental_pressure_dofs()
virtual void oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::unpin_elemental_pressure_dofs () protected pure virtual
Unpin all pressure dofs in the element.
Implemented in oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement, and oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement.
Referenced by unpin_all_pressure_dofs().
The documentation for this class was generated from the following files:
generalised_newtonian_refineable_axisym_navier_stokes_elements.h
generalised_newtonian_refineable_axisym_navier_stokes_elements.cc