MercuryDPM: Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version > Struct Template Reference
Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version > Struct Template Reference
#include <GeneralMatrixVector.h>
Public Types
typedef gemv_traits< LhsScalar, RhsScalar > Traits
typedef gemv_traits< LhsScalar, RhsScalar, GEMVPacketHalf > HalfTraits
typedef gemv_traits< LhsScalar, RhsScalar, GEMVPacketQuarter > QuarterTraits
typedef ScalarBinaryOpTraits< LhsScalar, RhsScalar >::ReturnType ResScalar
typedef Traits::LhsPacket LhsPacket
typedef Traits::RhsPacket RhsPacket
typedef Traits::ResPacket ResPacket
typedef HalfTraits::LhsPacket LhsPacketHalf
typedef HalfTraits::RhsPacket RhsPacketHalf
typedef HalfTraits::ResPacket ResPacketHalf
typedef QuarterTraits::LhsPacket LhsPacketQuarter
typedef QuarterTraits::RhsPacket RhsPacketQuarter
typedef QuarterTraits::ResPacket ResPacketQuarter
Static Public Member Functions
EIGEN_DEVICE_FUNC static EIGEN_DONT_INLINE void run (Index rows, Index cols, const LhsMapper &lhs, const RhsMapper &rhs, ResScalar *res, Index resIncr, RhsScalar alpha)
Member Typedef Documentation
HalfTraits
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef gemv_traits<LhsScalar, RhsScalar, GEMVPacketHalf> Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::HalfTraits
LhsPacket
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef Traits::LhsPacket Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::LhsPacket
LhsPacketHalf
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef HalfTraits::LhsPacket Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::LhsPacketHalf
LhsPacketQuarter
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef QuarterTraits::LhsPacket Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::LhsPacketQuarter
QuarterTraits
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef gemv_traits<LhsScalar, RhsScalar, GEMVPacketQuarter> Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::QuarterTraits
ResPacket
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef Traits::ResPacket Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::ResPacket
ResPacketHalf
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef HalfTraits::ResPacket Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::ResPacketHalf
ResPacketQuarter
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef QuarterTraits::ResPacket Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::ResPacketQuarter
ResScalar
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef ScalarBinaryOpTraits<LhsScalar, RhsScalar>::ReturnType Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::ResScalar
RhsPacket
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef Traits::RhsPacket Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::RhsPacket
RhsPacketHalf
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef HalfTraits::RhsPacket Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::RhsPacketHalf
RhsPacketQuarter
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef QuarterTraits::RhsPacket Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::RhsPacketQuarter
Traits
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef gemv_traits<LhsScalar, RhsScalar> Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::Traits
Member Function Documentation
run()
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> EIGEN_DEVICE_FUNC EIGEN_DONT_INLINE void Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::run (Index rows, Index cols, const LhsMapper & lhs, const RhsMapper & rhs, ResScalar * res, Index resIncr, RhsScalar alpha) static
{
   EIGEN_UNUSED_VARIABLE(resIncr);
   eigen_internal_assert(resIncr == 1);
   // The following copy tells the compiler that lhs's attributes are not modified outside this function
   // This helps GCC to generate proper code.
   LhsMapper lhs(alhs);
   conj_helper<LhsScalar, RhsScalar, ConjugateLhs, ConjugateRhs> cj;
   conj_helper<LhsPacket, RhsPacket, ConjugateLhs, ConjugateRhs> pcj;
   conj_helper<LhsPacketHalf, RhsPacketHalf, ConjugateLhs, ConjugateRhs> pcj_half;
   conj_helper<LhsPacketQuarter, RhsPacketQuarter, ConjugateLhs, ConjugateRhs> pcj_quarter;
   const Index lhsStride = lhs.stride();
   // TODO: for padded aligned inputs, we could enable aligned reads
   enum {
     LhsAlignment = Unaligned,
     ResPacketSize = Traits::ResPacketSize,
     ResPacketSizeHalf = HalfTraits::ResPacketSize,
     ResPacketSizeQuarter = QuarterTraits::ResPacketSize,
     LhsPacketSize = Traits::LhsPacketSize,
     HasHalf = (int)ResPacketSizeHalf < (int)ResPacketSize,
     HasQuarter = (int)ResPacketSizeQuarter < (int)ResPacketSizeHalf
   };
   const Index n8 = rows - 8 * ResPacketSize + 1;
   const Index n4 = rows - 4 * ResPacketSize + 1;
   const Index n3 = rows - 3 * ResPacketSize + 1;
   const Index n2 = rows - 2 * ResPacketSize + 1;
   const Index n1 = rows - 1 * ResPacketSize + 1;
   const Index n_half = rows - 1 * ResPacketSizeHalf + 1;
   const Index n_quarter = rows - 1 * ResPacketSizeQuarter + 1;
   // TODO: improve the following heuristic:
   const Index block_cols = cols < 128 ? cols : (lhsStride * sizeof(LhsScalar) < 32000 ? 16 : 4);
   ResPacket palpha = pset1<ResPacket>(alpha);
   ResPacketHalf palpha_half = pset1<ResPacketHalf>(alpha);
   ResPacketQuarter palpha_quarter = pset1<ResPacketQuarter>(alpha);
   for (Index j2 = 0; j2 < cols; j2 += block_cols) {
     Index jend = numext::mini(j2 + block_cols, cols);
     Index i = 0;
     for (; i < n8; i += ResPacketSize * 8) {
       ResPacket c0 = pset1<ResPacket>(ResScalar(0)), c1 = pset1<ResPacket>(ResScalar(0)),
                 c2 = pset1<ResPacket>(ResScalar(0)), c3 = pset1<ResPacket>(ResScalar(0)),
                 c4 = pset1<ResPacket>(ResScalar(0)), c5 = pset1<ResPacket>(ResScalar(0)),
                 c6 = pset1<ResPacket>(ResScalar(0)), c7 = pset1<ResPacket>(ResScalar(0));
       for (Index j = j2; j < jend; j += 1) {
         RhsPacket b0 = pset1<RhsPacket>(rhs(j, 0));
         c0 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + LhsPacketSize * 0, j), b0, c0);
         c1 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + LhsPacketSize * 1, j), b0, c1);
         c2 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + LhsPacketSize * 2, j), b0, c2);
         c3 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + LhsPacketSize * 3, j), b0, c3);
         c4 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + LhsPacketSize * 4, j), b0, c4);
         c5 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + LhsPacketSize * 5, j), b0, c5);
         c6 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + LhsPacketSize * 6, j), b0, c6);
         c7 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + LhsPacketSize * 7, j), b0, c7);
       }
       pstoreu(res + i + ResPacketSize * 0, pmadd(c0, palpha, ploadu<ResPacket>(res + i + ResPacketSize * 0)));
       pstoreu(res + i + ResPacketSize * 1, pmadd(c1, palpha, ploadu<ResPacket>(res + i + ResPacketSize * 1)));
       pstoreu(res + i + ResPacketSize * 2, pmadd(c2, palpha, ploadu<ResPacket>(res + i + ResPacketSize * 2)));
       pstoreu(res + i + ResPacketSize * 3, pmadd(c3, palpha, ploadu<ResPacket>(res + i + ResPacketSize * 3)));
       pstoreu(res + i + ResPacketSize * 4, pmadd(c4, palpha, ploadu<ResPacket>(res + i + ResPacketSize * 4)));
       pstoreu(res + i + ResPacketSize * 5, pmadd(c5, palpha, ploadu<ResPacket>(res + i + ResPacketSize * 5)));
       pstoreu(res + i + ResPacketSize * 6, pmadd(c6, palpha, ploadu<ResPacket>(res + i + ResPacketSize * 6)));
       pstoreu(res + i + ResPacketSize * 7, pmadd(c7, palpha, ploadu<ResPacket>(res + i + ResPacketSize * 7)));
     }
     if (i < n4) {
       ResPacket c0 = pset1<ResPacket>(ResScalar(0)), c1 = pset1<ResPacket>(ResScalar(0)),
                 c2 = pset1<ResPacket>(ResScalar(0)), c3 = pset1<ResPacket>(ResScalar(0));
       for (Index j = j2; j < jend; j += 1) {
         RhsPacket b0 = pset1<RhsPacket>(rhs(j, 0));
         c0 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + LhsPacketSize * 0, j), b0, c0);
         c1 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + LhsPacketSize * 1, j), b0, c1);
         c2 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + LhsPacketSize * 2, j), b0, c2);
         c3 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + LhsPacketSize * 3, j), b0, c3);
       }
       pstoreu(res + i + ResPacketSize * 0, pmadd(c0, palpha, ploadu<ResPacket>(res + i + ResPacketSize * 0)));
       pstoreu(res + i + ResPacketSize * 1, pmadd(c1, palpha, ploadu<ResPacket>(res + i + ResPacketSize * 1)));
       pstoreu(res + i + ResPacketSize * 2, pmadd(c2, palpha, ploadu<ResPacket>(res + i + ResPacketSize * 2)));
       pstoreu(res + i + ResPacketSize * 3, pmadd(c3, palpha, ploadu<ResPacket>(res + i + ResPacketSize * 3)));
       i += ResPacketSize * 4;
     }
     if (i < n3) {
       ResPacket c0 = pset1<ResPacket>(ResScalar(0)), c1 = pset1<ResPacket>(ResScalar(0)),
                 c2 = pset1<ResPacket>(ResScalar(0));
       for (Index j = j2; j < jend; j += 1) {
         RhsPacket b0 = pset1<RhsPacket>(rhs(j, 0));
         c0 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + LhsPacketSize * 0, j), b0, c0);
         c1 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + LhsPacketSize * 1, j), b0, c1);
         c2 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + LhsPacketSize * 2, j), b0, c2);
       }
       pstoreu(res + i + ResPacketSize * 0, pmadd(c0, palpha, ploadu<ResPacket>(res + i + ResPacketSize * 0)));
       pstoreu(res + i + ResPacketSize * 1, pmadd(c1, palpha, ploadu<ResPacket>(res + i + ResPacketSize * 1)));
       pstoreu(res + i + ResPacketSize * 2, pmadd(c2, palpha, ploadu<ResPacket>(res + i + ResPacketSize * 2)));
       i += ResPacketSize * 3;
     }
     if (i < n2) {
       ResPacket c0 = pset1<ResPacket>(ResScalar(0)), c1 = pset1<ResPacket>(ResScalar(0));
       for (Index j = j2; j < jend; j += 1) {
         RhsPacket b0 = pset1<RhsPacket>(rhs(j, 0));
         c0 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + LhsPacketSize * 0, j), b0, c0);
         c1 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + LhsPacketSize * 1, j), b0, c1);
       }
       pstoreu(res + i + ResPacketSize * 0, pmadd(c0, palpha, ploadu<ResPacket>(res + i + ResPacketSize * 0)));
       pstoreu(res + i + ResPacketSize * 1, pmadd(c1, palpha, ploadu<ResPacket>(res + i + ResPacketSize * 1)));
       i += ResPacketSize * 2;
     }
     if (i < n1) {
       ResPacket c0 = pset1<ResPacket>(ResScalar(0));
       for (Index j = j2; j < jend; j += 1) {
         RhsPacket b0 = pset1<RhsPacket>(rhs(j, 0));
         c0 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + 0, j), b0, c0);
       }
       pstoreu(res + i + ResPacketSize * 0, pmadd(c0, palpha, ploadu<ResPacket>(res + i + ResPacketSize * 0)));
       i += ResPacketSize;
     }
     if (HasHalf && i < n_half) {
       ResPacketHalf c0 = pset1<ResPacketHalf>(ResScalar(0));
       for (Index j = j2; j < jend; j += 1) {
         RhsPacketHalf b0 = pset1<RhsPacketHalf>(rhs(j, 0));
         c0 = pcj_half.pmadd(lhs.template load<LhsPacketHalf, LhsAlignment>(i + 0, j), b0, c0);
       }
       pstoreu(res + i + ResPacketSizeHalf * 0,
               pmadd(c0, palpha_half, ploadu<ResPacketHalf>(res + i + ResPacketSizeHalf * 0)));
       i += ResPacketSizeHalf;
     }
     if (HasQuarter && i < n_quarter) {
       ResPacketQuarter c0 = pset1<ResPacketQuarter>(ResScalar(0));
       for (Index j = j2; j < jend; j += 1) {
         RhsPacketQuarter b0 = pset1<RhsPacketQuarter>(rhs(j, 0));
         c0 = pcj_quarter.pmadd(lhs.template load<LhsPacketQuarter, LhsAlignment>(i + 0, j), b0, c0);
       }
       pstoreu(res + i + ResPacketSizeQuarter * 0,
               pmadd(c0, palpha_quarter, ploadu<ResPacketQuarter>(res + i + ResPacketSizeQuarter * 0)));
       i += ResPacketSizeQuarter;
     }
     for (; i < rows; ++i) {
       ResScalar c0(0);
       for (Index j = j2; j < jend; j += 1) c0 += cj.pmul(lhs(i, j), rhs(j, 0));
       res[i] += alpha * c0;
     }
   }
 }
References alpha, cols, eigen_internal_assert, EIGEN_UNUSED_VARIABLE, i, int(), j, Eigen::numext::mini(), palpha, Eigen::internal::conj_helper< LhsType, RhsType, ConjLhs, ConjRhs >::pmadd(), Eigen::internal::pmadd(), Eigen::internal::conj_helper< LhsType, RhsType, ConjLhs, ConjRhs >::pmul(), Eigen::internal::pstoreu(), res, rows, and Eigen::Unaligned.
The documentation for this struct was generated from the following file:
GeneralMatrixVector.h