MercuryDPM: FSICollapsibleChannelProblem< ELEMENT > Class Template Reference
FSICollapsibleChannelProblem< ELEMENT > Class Template Reference
Problem class.
#include <fsi_chan_problem.h>
Public Member Functions
FSICollapsibleChannelProblem (const unsigned &nup, const unsigned &ncollapsible, const unsigned &ndown, const unsigned &ny, const double &lup, const double &lcollapsible, const double &ldown, const double &ly, const bool &displ_control, const bool &steady_flag)
Constructor for the collapsible channel problem.
~FSICollapsibleChannelProblem ()
Destructor.
virtual void steady_run ()
Steady run.
virtual void unsteady_run (const double &dt=0.1)
Unsteady run. Specify timestep or use default of 0.1.
AlgebraicCollapsibleChannelMesh< ELEMENT > * bulk_mesh_pt ()
Access function for the specific bulk (fluid) mesh.
OneDLagrangianMesh< FSIHermiteBeamElement > * wall_mesh_pt ()
Access function for the wall mesh.
void actions_before_newton_solve ()
Actions before solve. Reset counter for number of Newton iterations.
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_newton_convergence_check ()
virtual void doc_solution_steady (DocInfo &doc_info, ofstream &trace_file, const double &cpu, const unsigned &niter)
Doc the steady solution.
virtual void doc_solution_unsteady (DocInfo &doc_info, ofstream &trace_file, const double &cpu, const unsigned &niter)
Doc the unsteady solution.
void set_initial_condition ()
Apply initial conditions.
FSICollapsibleChannelProblem (const unsigned &nup, const unsigned &ncollapsible, const unsigned &ndown, const unsigned &ny, const double &lup, const double &lcollapsible, const double &ldown, const double &ly)
Constructor for the collapsible channel problem.
~FSICollapsibleChannelProblem ()
Destructor (empty)
AlgebraicCollapsibleChannelMesh< ELEMENT > * bulk_mesh_pt ()
Access function for the specific bulk (fluid) mesh.
OneDLagrangianMesh< FSIHermiteBeamElement > * wall_mesh_pt ()
Access function for the wall mesh.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_newton_convergence_check ()
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution.
void set_initial_condition ()
Apply initial conditions.
FSICollapsibleChannelProblem (const unsigned &nup, const unsigned &ncollapsible, const unsigned &ndown, const unsigned &ny, const double &lup, const double &lcollapsible, const double &ldown, const double &ly)
~FSICollapsibleChannelProblem ()
Destructor (empty)
RefineableAlgebraicCollapsibleChannelMesh< ELEMENT > * bulk_mesh_pt ()
Access function for the specific bulk (fluid) mesh.
OneDLagrangianMesh< FSIHermiteBeamElement > * wall_mesh_pt ()
Access function for the wall mesh.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of prescribed traction elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of prescribed traction elements.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_newton_convergence_check ()
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution.
void set_initial_condition ()
Apply initial conditions.
FSICollapsibleChannelProblem (const unsigned &nup, const unsigned &ncollapsible, const unsigned &ndown, const unsigned &ny, const double &lup, const double &lcollapsible, const double &ldown, const double &ly)
~FSICollapsibleChannelProblem ()
Destructor (empty)
ElasticCollapsibleChannelMesh< ELEMENT > * bulk_mesh_pt ()
Access function for the specific bulk (fluid) mesh.
OneDLagrangianMesh< FSIHermiteBeamElement > * wall_mesh_pt ()
Access function for the wall mesh.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_newton_convergence_check ()
Update no slip before Newton convergence check.
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution.
void set_initial_condition ()
Apply initial conditions.
FSICollapsibleChannelProblem (const unsigned &nup, const unsigned &ncollapsible, const unsigned &ndown, const unsigned &ny, const double &lup, const double &lcollapsible, const double &ldown, const double &ly)
~FSICollapsibleChannelProblem ()
Destructor (empty)
ElasticRefineableCollapsibleChannelMesh< ELEMENT > * bulk_mesh_pt ()
Access function for the specific bulk (fluid) mesh.
OneDLagrangianMesh< FSIHermiteBeamElement > * wall_mesh_pt ()
Access function for the wall mesh.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of prescribed traction elements.
void actions_after_adapt ()
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_newton_convergence_check ()
Update no slip before Newton convergence check.
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution.
void set_initial_condition ()
Apply initial conditions.
FSICollapsibleChannelProblem (const unsigned &nup, const unsigned &ncollapsible, const unsigned &ndown, const unsigned &ny, const double &lup, const double &lcollapsible, const double &ldown, const double &ly)
~FSICollapsibleChannelProblem ()
Destructor (empty)
RefineableAlgebraicCollapsibleChannelMesh< ELEMENT > * bulk_mesh_pt ()
Access function for the specific bulk (fluid) mesh.
OneDLagrangianMesh< FSIHermiteBeamElement > *& wall_mesh_pt ()
Access function for the wall mesh.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of prescribed traction elements.
void actions_after_adapt ()
void actions_before_distribute ()
Actions before distribute: wipe the mesh of prescribed traction elements.
void actions_after_distribute ()
Actions after distribute: create traction elements and reset FSI.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_newton_convergence_check ()
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution.
void set_initial_condition ()
Apply initial conditions.
FSICollapsibleChannelProblem (const unsigned &nup, const unsigned &ncollapsible, const unsigned &ndown, const unsigned &ny, const double &lup, const double &lcollapsible, const double &ldown, const double &ly, const bool &wall_jacobian_ignores_fluid_shear_stress_data, const bool &wall_jacobian_ignores_geometric_data, const bool &fluid_jacobian_ignores_geometric_data)
Constructor for the collapsible channel problem.
~FSICollapsibleChannelProblem ()
Destructor (empty)
AlgebraicCollapsibleChannelMesh< ELEMENT > * bulk_mesh_pt ()
Access function for the specific bulk (fluid) mesh.
OneDLagrangianMesh< FSIHermiteBeamElement > * wall_mesh_pt ()
Access function for the wall mesh.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_newton_convergence_check ()
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution.
void set_initial_condition ()
Apply initial conditions.
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Protected Member Functions
void dump_it (ofstream &dump_file)
Dump problem to disk to allow for restart.
void restart (ifstream &restart_file)
Read problem for restart from specified restart file.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_before_implicit_timestep ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes
unsigned Nup
Number of elements in the x direction in the upstream part of the channel.
unsigned Ncollapsible
unsigned Ndown
Number of elements in the x direction in the downstream part of the channel.
unsigned Ny
Number of elements across the channel.
double Lup
x-length in the upstream part of the channel
double Lcollapsible
x-length in the collapsible part of the channel
double Ldown
x-length in the downstream part of the channel
double Ly
Transverse length.
AlgebraicCollapsibleChannelMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the "bulk" mesh.
Mesh * Displ_control_mesh_pt
Pointer to the mesh that contains the displacement control element.
bool Displ_control
Use displacement control?
OneDLagrangianMesh< FSIHermiteBeamElement > * Wall_mesh_pt
Pointer to the "wall" mesh.
Node * Left_node_pt
Pointer to the left control node.
Node * Right_node_pt
Pointer to right control node.
Node * Wall_node_pt
Pointer to control node on the wall.
bool Steady_flag
Flag for steady run.
GeomObject * Ctrl_geom_obj_pt
Vector< double > S_displ_ctrl
MeshAsGeomObject * Wall_geom_object_pt
Geometric object incarnation of the wall mesh.
unsigned Newton_iter
Counter for Newton iterations.
DocInfo Doc_info
DocInfo object.
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Private Member Functions
void create_traction_elements (const unsigned &b, Mesh *const &bulk_mesh_pt, Mesh *const &traction_mesh_pt)
Create the prescribed traction elements on boundary b.
void create_traction_elements (const unsigned &b, Mesh *const &bulk_mesh_pt, Mesh *const &traction_mesh_pt)
Create the prescribed traction elements on boundary b.
void delete_traction_elements (Mesh *const &traction_mesh_pt)
Delete prescribed traction elements from the surface mesh.
void create_traction_elements (const unsigned &b, Mesh *const &bulk_mesh_pt, Mesh *const &traction_mesh_pt)
Create the prescribed traction elements on boundary b.
void delete_traction_elements (Mesh *const &traction_mesh_pt)
Delete prescribed traction elements from the surface mesh.
void create_lagrange_multiplier_elements ()
Create elements that impose the prescribed boundary displacement.
void delete_lagrange_multiplier_elements ()
void create_traction_elements (const unsigned &b, Mesh *const &bulk_mesh_pt, Mesh *const &traction_mesh_pt)
Create the prescribed traction elements on boundary b.
void delete_traction_elements (Mesh *const &traction_mesh_pt)
Delete prescribed traction elements from the surface mesh.
void create_lagrange_multiplier_elements ()
void delete_lagrange_multiplier_elements ()
void create_traction_elements (const unsigned &b, Mesh *const &bulk_mesh_pt, Mesh *const &traction_mesh_pt)
Create the prescribed traction elements on boundary b.
void delete_traction_elements (Mesh *const &traction_mesh_pt)
Delete prescribed traction elements from the surface mesh.
void create_traction_elements (const unsigned &b, Mesh *const &bulk_mesh_pt, Mesh *const &traction_mesh_pt)
Create the prescribed traction elements on boundary b.
Private Attributes
Mesh * Applied_fluid_traction_mesh_pt
RefineableAlgebraicCollapsibleChannelMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the "bulk" mesh.
ElasticCollapsibleChannelMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the "bulk" mesh.
SolidMesh * Lagrange_multiplier_mesh_pt
Pointers to mesh of Lagrange multiplier elements.
ConstitutiveLaw * Constitutive_law_pt
Constitutive law used to determine the mesh deformation.
ElasticRefineableCollapsibleChannelMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the "bulk" mesh.
Mesh * Displacement_control_mesh_pt
Pointer to mesh containing the displacement control element (only!)
bool Fluid_jacobian_ignores_geometric_data
bool Wall_jacobian_ignores_geometric_data
bool Wall_jacobian_ignores_fluid_shear_stress_data
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class ELEMENT>
class FSICollapsibleChannelProblem< ELEMENT >
Problem class.
Constructor & Destructor Documentation
FSICollapsibleChannelProblem() [1/7]
template<class ELEMENT > FSICollapsibleChannelProblem< ELEMENT >::FSICollapsibleChannelProblem (const unsigned & nup, const unsigned & ncollapsible, const unsigned & ndown, const unsigned & ny, const double & lup, const double & lcollapsible, const double & ldown, const double & ly, const bool & displ_control, const bool & steady_flag)
Constructor for the collapsible channel problem.
Constructor: The arguments are the number of elements and the lengths of the domain.
 {
  // Initialise number of Newton iterations
  Newton_iter=0;
  // Store problem parameters
  Nup=nup;
  Ncollapsible=ncollapsible;
  Ndown=ndown;
  Ny=ny;
  Lup=lup;
  Lcollapsible=lcollapsible;
  Ldown=ldown;
  Ly=ly;
  Steady_flag=steady_flag;
  // Displacement control only makes sense for steady problems
  if (Steady_flag)
   {
    Displ_control=displ_control;
   }
  else
   {
    Displ_control=false;
    if (displ_control)
     {
      std::cout << "Switched off displacement control for unsteady run!"
                << std::endl;
     }
   }
  // Overwrite maximum allowed residual to accomodate bad initial guesses
  Problem::Max_residuals=1000.0;
  // Allocate the timestepper -- this constructs the Problem's
  // time object with a sufficient amount of storage to store the
  // previous timsteps. Note: This is appropriate even for
  // the steady problem as we'll explicitly call the *steady*
  // Newton solver which disables the timesteppers
  // during the solve.
  add_time_stepper_pt(new BDF<2>);
  // Create a dummy Steady timestepper that stores two history values
  Steady<2>* wall_time_stepper_pt = new Steady<2>;
  // Add the wall timestepper to the Problem's collection of timesteppers.
  add_time_stepper_pt(wall_time_stepper_pt);
  // Geometric object that represents the undeformed wall:
  // A straight line at height y=ly; starting at x=lup.
  UndeformedWall* undeformed_wall_pt=new UndeformedWall(lup,ly);
  //Create the "wall" mesh with FSI Hermite elements
  Wall_mesh_pt = new OneDLagrangianMesh<FSIHermiteBeamElement>
   (Ncollapsible,Lcollapsible,undeformed_wall_pt,wall_time_stepper_pt);
  // Build a geometric object (one Lagrangian, two Eulerian coordinates)
  // from the wall mesh
  Wall_geom_object_pt=
   new MeshAsGeomObject(Wall_mesh_pt);
  // Get pointer to/local coordinate in wall geom object that contains
  // control node -- adjusted for different values of Q, so that
  // the point is located near the point of strongest collapse.
  Vector<double> zeta_displ_ctrl(1);
  zeta_displ_ctrl[0]=3.5;
  if (std::abs(Global_Physical_Variables::Q-1.0e-3)<1.0e-10)
   {
    zeta_displ_ctrl[0]=3.0;
   }
  //if (std::abs(Global_Physical_Variables::Q-1.0e-4)<1.0e-10)
  if (Global_Physical_Variables::Q<=1.0e-4)
   {
    zeta_displ_ctrl[0]=2.5;
   }
  std::cout << "Wall control point located at zeta=" <<zeta_displ_ctrl[0]
            << std::endl;
  S_displ_ctrl.resize(1);
  // Locate control point (pointer to GeomObject and local coordinate in it)
  Wall_geom_object_pt->locate_zeta(zeta_displ_ctrl,
                                   Ctrl_geom_obj_pt,
                                   S_displ_ctrl);
  // Normal load incrementation or unsteady run
  //===========================================
  Displ_control_mesh_pt=new Mesh;
  // Choose element in which displacement control is applied:
  SolidFiniteElement* controlled_element_pt=
   dynamic_cast<SolidFiniteElement*>(Ctrl_geom_obj_pt);
  // Fix the displacement in the vertical (1) direction...
  unsigned controlled_direction=1;
  // Pointer to displacement control element
  DisplacementControlElement* displ_control_el_pt;
  // Build displacement control element
  displ_control_el_pt=
   new DisplacementControlElement(controlled_element_pt,
                                  S_displ_ctrl,
                                  controlled_direction,
                                  &Global_Physical_Variables::Yprescr);
  // The constructor of the  DisplacementControlElement has created
  // a new Data object whose one-and-only value contains the
  // adjustable load: Use this Data object in the load function:
  Global_Physical_Variables::P_ext_data_pt=displ_control_el_pt->
   displacement_control_load_pt();
  // Add the displacement-control element to its own mesh
  Displ_control_mesh_pt->add_element_pt(displ_control_el_pt);
  if (!Displ_control)
   {
    // Create Data object whose one-and-only value contains the
    // (in principle) adjustable load
    Global_Physical_Variables::P_ext_data_pt=new Data(1);
    //Pin the external pressure because it isn't actually adjustable.
    Global_Physical_Variables::P_ext_data_pt->pin(0);
   }
  //Build bulk (fluid) mesh
  Bulk_mesh_pt =
   new AlgebraicCollapsibleChannelMesh<ELEMENT>
   (nup, ncollapsible, ndown, ny,
    lup, lcollapsible, ldown, ly,
    Wall_geom_object_pt,
    time_stepper_pt());
  // Add the sub meshes to the problem
  add_sub_mesh(Bulk_mesh_pt);
  add_sub_mesh(Wall_mesh_pt);
  add_sub_mesh(Displ_control_mesh_pt);
  // Combine all submeshes into a single Mesh
  build_global_mesh();
  // Complete build of fluid mesh
  //-----------------------------
  // Loop over the elements to set up element-specific
  // things that cannot be handled by constructor
  unsigned n_element=Bulk_mesh_pt->nelement();
  for(unsigned e=0;e<n_element;e++)
   {
    // Upcast from GeneralisedElement to the present element
    ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e));
    //Set the Reynolds number
    el_pt->re_pt() = &Global_Physical_Variables::Re;
    // Set the Womersley number
    el_pt->re_st_pt() = &Global_Physical_Variables::ReSt;
    // Switch off mesh velocity in steady runs
    if (Flags::Steady_flag)
     {
      el_pt->disable_ALE();
     }
    else
     {
      // Is element in rigid part?
      bool is_in_rigid_part=true;
      // Number of nodes
      unsigned nnod=el_pt->nnode();
      for (unsigned j=0;j<nnod;j++)
       {
        double x=el_pt->node_pt(j)->x(0);
        if ((x>=Lup)&&(x<=(Lup+Lcollapsible)))
         {
          is_in_rigid_part=false;
          break;
         }
       }
      if (is_in_rigid_part)
       {
        el_pt->disable_ALE();
       }
     }
   } // end loop over elements
  // Apply boundary conditions for fluid
  //------------------------------------
  //Pin the velocity on the boundaries
  //x and y-velocities pinned along boundary 0 (bottom boundary) :
  unsigned ibound=0;
  unsigned num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  for (unsigned inod=0;inod<num_nod;inod++)
   {
    for(unsigned i=0;i<2;i++)
     {
      bulk_mesh_pt()->boundary_node_pt(ibound, inod)->pin(i);
     }
   }
  //x and y-velocities pinned along boundaries 2, 3, 4 (top boundaries) :
  for(ibound=2;ibound<5;ibound++)
   {
    num_nod= bulk_mesh_pt()->nboundary_node(ibound);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      for(unsigned i=0;i<2;i++)
       {
        bulk_mesh_pt()->boundary_node_pt(ibound, inod)->pin(i);
       }
     }
   }
  //y-velocity pinned along boundary 1 (right boundary):
  ibound=1;
  num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  for (unsigned inod=0;inod<num_nod;inod++)
   {
    bulk_mesh_pt()->boundary_node_pt(ibound, inod)->pin(1);
   }
  //Both velocities pinned along boundary 5 (left boundary):
  ibound=5;
  num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  for (unsigned inod=0;inod<num_nod;inod++)
   {
    bulk_mesh_pt()->boundary_node_pt(ibound, inod)->pin(0);
    bulk_mesh_pt()->boundary_node_pt(ibound, inod)->pin(1);
   }
 //end of pin_velocity
  // Complete build of wall elements
  //--------------------------------
  //Loop over the elements to set physical parameters etc.
  n_element = wall_mesh_pt()->nelement();
  for(unsigned e=0;e<n_element;e++)
   {
    // Upcast to the specific element type
    FSIHermiteBeamElement *elem_pt =
     dynamic_cast<FSIHermiteBeamElement*>(wall_mesh_pt()->element_pt(e));
    // Set physical parameters for each element:
    elem_pt->sigma0_pt() = &Global_Physical_Variables::Sigma0;
    elem_pt->h_pt() = &Global_Physical_Variables::H;
    // Set the load vector for each element
    elem_pt->load_vector_fct_pt() = &Global_Physical_Variables::load;
    // Function that specifies the load ratios
    elem_pt->q_pt() = &Global_Physical_Variables::Q;
    // Set the undeformed shape for each element
    elem_pt->undeformed_beam_pt() = undeformed_wall_pt;
    // The normal on the wall elements as computed by the FSIHermiteElements
    // points away from the fluid rather than into the fluid (as assumed
    // by default)
    elem_pt->set_normal_pointing_out_of_fluid();
    // Displacement control? If so, the load on *all* elements
    // is affected by an unknown -- the external pressure, stored
    // as the one-and-only value in a Data object: Add it to the
    // elements' external Data.
    if (Displ_control)
     {
      //The external pressure is external data for all elements
      elem_pt->add_external_data(Global_Physical_Variables::P_ext_data_pt);
     }
   } // end of loop over elements
  // Boundary conditions for wall mesh
  //----------------------------------
  // Set the boundary conditions: Each end of the beam is fixed in space
  // Loop over the boundaries (ends of the beam)
  for(unsigned b=0;b<2;b++)
   {
    // Pin displacements in both x and y directions
    wall_mesh_pt()->boundary_node_pt(b,0)->pin_position(0);
    wall_mesh_pt()->boundary_node_pt(b,0)->pin_position(1);
   }
  //Choose control nodes
  //---------------------
  // Left boundary
  ibound=5;
  num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  unsigned control_nod=num_nod/2;
  Left_node_pt= bulk_mesh_pt()->boundary_node_pt(ibound, control_nod);
  // Right boundary
  ibound=1;
  num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  control_nod=num_nod/2;
  Right_node_pt= bulk_mesh_pt()->boundary_node_pt(ibound, control_nod);
  // Set the pointer to the control node on the wall
  num_nod= wall_mesh_pt()->nnode();
  Wall_node_pt=wall_mesh_pt()->node_pt(Ncollapsible/2);
  // Setup FSI
  //----------
  // The velocity of the fluid nodes on the wall (fluid mesh boundary 3)
  // is set by the wall motion -- hence the no-slip condition must be
  // re-applied whenever a node update is performed for these nodes.
  // Such tasks may be performed automatically by the auxiliary node update
  // function specified by a function pointer:
  ibound=3;
  num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  for (unsigned inod=0;inod<num_nod;inod++)
   {
    static_cast<AlgebraicNode*>(
     bulk_mesh_pt()->boundary_node_pt(ibound, inod))->
     set_auxiliary_node_update_fct_pt(
      FSI_functions::apply_no_slip_on_moving_wall);
   }
  // Work out which fluid dofs affect the residuals of the wall elements:
  // We pass the boundary between the fluid and solid meshes and
  // pointers to the meshes. The interaction boundary is boundary 3 of the
  // 2D fluid mesh.
  FSI_functions::setup_fluid_load_info_for_solid_elements<ELEMENT,2>
   (this,3,Bulk_mesh_pt,Wall_mesh_pt);
  // Setup equation numbering scheme
  cout <<"Total number of equations: " << assign_eqn_numbers() << std::endl;
 }//end of constructor
References abs(), oomph::FSI_functions::apply_no_slip_on_moving_wall(), b, e(), Global_Physical_Variables::H, i, j, Global_Parameters::Ldown, Global_Physical_Variables::load(), Global_Parameters::Lup, Mesh_Parameters::ly, Global_Parameters::Ly, Mesh_Parameters::ny, GlobalParameters::Ny, Global_Physical_Variables::P_ext_data_pt, Global_Physical_Variables::Q, Global_Physical_Variables::Re, Global_Physical_Variables::ReSt, Global_Physical_Variables::Sigma0, Flags::Steady_flag, plotDoE::x, and Global_Physical_Variables::Yprescr.
~FSICollapsibleChannelProblem() [1/7]
template<class ELEMENT > FSICollapsibleChannelProblem< ELEMENT >::~FSICollapsibleChannelProblem () inline
Destructor.
   {
    // Mesh gets killed in general problem destructor
   }
FSICollapsibleChannelProblem() [2/7]
template<class ELEMENT > FSICollapsibleChannelProblem< ELEMENT >::FSICollapsibleChannelProblem (const unsigned & nup, const unsigned & ncollapsible, const unsigned & ndown, const unsigned & ny, const double & lup, const double & lcollapsible, const double & ldown, const double & ly)
Constructor for the collapsible channel problem.
Constructor: The arguments are the number of elements and the lengths of the domain.
 {
  // Store problem parameters
  Nup=nup;
  Ncollapsible=ncollapsible;
  Ndown=ndown;
  Ny=ny;
  Lup=lup;
  Lcollapsible=lcollapsible;
  Ldown=ldown;
  Ly=ly;
  // Overwrite maximum allowed residual to accomodate bad initial guesses
  Problem::Max_residuals=1000.0;
  // Allocate the timestepper -- this constructs the Problem's
  // time object with a sufficient amount of storage to store the
  // previous timsteps.
  add_time_stepper_pt(new BDF<2>);
  // Geometric object that represents the undeformed wall:
  // A straight line at height y=ly; starting at x=lup.
  UndeformedWall* undeformed_wall_pt=new UndeformedWall(lup,ly);
  //Create the "wall" mesh with FSI Hermite elements
  Wall_mesh_pt = new OneDLagrangianMesh<FSIHermiteBeamElement>
   //(2*Ncollapsible+5,Lcollapsible,undeformed_wall_pt);
   (Ncollapsible,Lcollapsible,undeformed_wall_pt);
  // Build a geometric object (one Lagrangian, two Eulerian coordinates)
  // from the wall mesh
  MeshAsGeomObject* wall_geom_object_pt=
   new MeshAsGeomObject(Wall_mesh_pt);
 #ifdef MACRO_ELEMENT_NODE_UPDATE
  //Build bulk (fluid) mesh
  Bulk_mesh_pt =
   new MacroElementNodeUpdateCollapsibleChannelMesh<ELEMENT>
   (nup, ncollapsible, ndown, ny,
    lup, lcollapsible, ldown, ly,
    wall_geom_object_pt,
    time_stepper_pt());
  // Set a non-trivial boundary-layer-squash function...
  Bulk_mesh_pt->bl_squash_fct_pt() = &BL_Squash::squash_fct;
  // ... and update the nodal positions accordingly
  Bulk_mesh_pt->node_update();
 #else
  //Build bulk (fluid) mesh
  Bulk_mesh_pt =
   new AlgebraicCollapsibleChannelMesh<ELEMENT>
   (nup, ncollapsible, ndown, ny,
    lup, lcollapsible, ldown, ly,
    wall_geom_object_pt,
    &BL_Squash::squash_fct,
    time_stepper_pt());
 #endif
  // Create "surface mesh" that will contain only the prescribed-traction
  // elements. The constructor just creates the mesh without
  // giving it any elements, nodes, etc.
  Applied_fluid_traction_mesh_pt = new Mesh;
  // Create prescribed-traction elements from all elements that are
  // adjacent to boundary 5 (left boundary), but add them to a separate mesh.
  create_traction_elements(5,Bulk_mesh_pt,Applied_fluid_traction_mesh_pt);
  // Add the sub meshes to the problem
  add_sub_mesh(Bulk_mesh_pt);
  add_sub_mesh(Applied_fluid_traction_mesh_pt);
  add_sub_mesh(Wall_mesh_pt);
  // Combine all submeshes into a single Mesh
  build_global_mesh();
  // Complete build of fluid mesh
  //-----------------------------
  // Loop over the elements to set up element-specific
  // things that cannot be handled by constructor
  unsigned n_element=Bulk_mesh_pt->nelement();
  for(unsigned e=0;e<n_element;e++)
   {
    // Upcast from GeneralisedElement to the present element
    ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e));
    //Set the Reynolds number
    el_pt->re_pt() = &Global_Physical_Variables::Re;
    // Set the Womersley number
    el_pt->re_st_pt() = &Global_Physical_Variables::ReSt;
   } // end loop over elements
  // Apply boundary conditions for fluid
  //------------------------------------
  //Pin the velocity on the boundaries
  //x and y-velocities pinned along boundary 0 (bottom boundary) :
  unsigned ibound=0;
  unsigned num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  for (unsigned inod=0;inod<num_nod;inod++)
   {
    for(unsigned i=0;i<2;i++)
     {
      bulk_mesh_pt()->boundary_node_pt(ibound, inod)->pin(i);
     }
   }
  //x and y-velocities pinned along boundaries 2, 3, 4 (top boundaries) :
  for(ibound=2;ibound<5;ibound++)
   {
    num_nod= bulk_mesh_pt()->nboundary_node(ibound);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      for(unsigned i=0;i<2;i++)
       {
        bulk_mesh_pt()->boundary_node_pt(ibound, inod)->pin(i);
       }
     }
   }
  //y-velocity pinned along boundary 1 (right boundary):
  ibound=1;
  num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  for (unsigned inod=0;inod<num_nod;inod++)
   {
    bulk_mesh_pt()->boundary_node_pt(ibound, inod)->pin(1);
   }
  //y-velocity pinned along boundary 5 (left boundary):
  ibound=5;
  num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  for (unsigned inod=0;inod<num_nod;inod++)
   {
    bulk_mesh_pt()->boundary_node_pt(ibound, inod)->pin(1);
   }
 //end of pin_velocity
  // Complete build of applied traction elements
  //--------------------------------------------
  // Loop over the traction elements to pass pointer to prescribed
  // traction function
  unsigned n_el=Applied_fluid_traction_mesh_pt->nelement();
  for(unsigned e=0;e<n_el;e++)
   {
    // Upcast from GeneralisedElement to NavierStokes traction element
    NavierStokesTractionElement<ELEMENT> *el_pt =
     dynamic_cast< NavierStokesTractionElement<ELEMENT>*>(
      Applied_fluid_traction_mesh_pt->element_pt(e));
    // Set the pointer to the prescribed traction function
    el_pt->traction_fct_pt() = &Global_Physical_Variables::prescribed_traction;
   }
  // Complete build of wall elements
  //--------------------------------
  //Loop over the elements to set physical parameters etc.
  n_element = wall_mesh_pt()->nelement();
  for(unsigned e=0;e<n_element;e++)
   {
    // Upcast to the specific element type
    FSIHermiteBeamElement *elem_pt =
     dynamic_cast<FSIHermiteBeamElement*>(wall_mesh_pt()->element_pt(e));
    // Set physical parameters for each element:
    elem_pt->sigma0_pt() = &Global_Physical_Variables::Sigma0;
    elem_pt->h_pt() = &Global_Physical_Variables::H;
    // Set the load vector for each element
    elem_pt->load_vector_fct_pt() = &Global_Physical_Variables::load;
    // Function that specifies the load ratios
    elem_pt->q_pt() = &Global_Physical_Variables::Q;
    // Set the undeformed shape for each element
    elem_pt->undeformed_beam_pt() = undeformed_wall_pt;
    // The normal on the wall elements as computed by the FSIHermiteElements
    // points away from the fluid rather than into the fluid (as assumed
    // by default)
    elem_pt->set_normal_pointing_out_of_fluid();
   } // end of loop over elements
  // Boundary conditions for wall mesh
  //----------------------------------
  // Set the boundary conditions: Each end of the beam is fixed in space
  // Loop over the boundaries (ends of the beam)
  for(unsigned b=0;b<2;b++)
   {
    // Pin displacements in both x and y directions
    wall_mesh_pt()->boundary_node_pt(b,0)->pin_position(0);
    wall_mesh_pt()->boundary_node_pt(b,0)->pin_position(1);
   }
  //Choose control nodes
  //---------------------
  // Left boundary
  ibound=5;
  num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  unsigned control_nod=num_nod/2;
  Left_node_pt= bulk_mesh_pt()->boundary_node_pt(ibound, control_nod);
  // Right boundary
  ibound=1;
  num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  control_nod=num_nod/2;
  Right_node_pt= bulk_mesh_pt()->boundary_node_pt(ibound, control_nod);
  // Set the pointer to the control node on the wall
  Wall_node_pt=wall_mesh_pt()->node_pt(Ncollapsible/2);
  // Setup FSI
  //----------
  // The velocity of the fluid nodes on the wall (fluid mesh boundary 3)
  // is set by the wall motion -- hence the no-slip condition must be
  // re-applied whenever a node update is performed for these nodes.
  // Such tasks may be performed automatically by the auxiliary node update
  // function specified by a function pointer:
  ibound=3;
  num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  for (unsigned inod=0;inod<num_nod;inod++)
   {
    bulk_mesh_pt()->boundary_node_pt(ibound, inod)->
     set_auxiliary_node_update_fct_pt(
      FSI_functions::apply_no_slip_on_moving_wall);
   }
  // Work out which fluid dofs affect the residuals of the wall elements:
  // We pass the boundary between the fluid and solid meshes and
  // pointers to the meshes. The interaction boundary is boundary 3 of the
  // 2D fluid mesh.
  FSI_functions::setup_fluid_load_info_for_solid_elements<ELEMENT,2>
   (this,3,Bulk_mesh_pt,Wall_mesh_pt);
  // Setup equation numbering scheme
  cout <<"Number of equations: " << assign_eqn_numbers() << std::endl;
 }//end of constructor
References oomph::FSI_functions::apply_no_slip_on_moving_wall(), b, e(), Global_Physical_Variables::H, oomph::KirchhoffLoveBeamEquations::h_pt(), i, Global_Parameters::Ldown, Global_Physical_Variables::load(), oomph::KirchhoffLoveBeamEquations::load_vector_fct_pt, Global_Parameters::Lup, Mesh_Parameters::ly, Global_Parameters::Ly, Mesh_Parameters::ny, GlobalParameters::Ny, Global_Physical_Variables::prescribed_traction(), Global_Physical_Variables::Q, oomph::FSIWallElement::q_pt(), Global_Physical_Variables::Re, Global_Physical_Variables::ReSt, oomph::FSIHermiteBeamElement::set_normal_pointing_out_of_fluid(), Global_Physical_Variables::Sigma0, oomph::KirchhoffLoveBeamEquations::sigma0_pt(), BL_Squash::squash_fct(), oomph::NavierStokesTractionElement< ELEMENT >::traction_fct_pt, and oomph::KirchhoffLoveBeamEquations::undeformed_beam_pt().
~FSICollapsibleChannelProblem() [2/7]
template<class ELEMENT > FSICollapsibleChannelProblem< ELEMENT >::~FSICollapsibleChannelProblem () inline
Destructor (empty)
 {}
FSICollapsibleChannelProblem() [3/7]
template<class ELEMENT > FSICollapsibleChannelProblem< ELEMENT >::FSICollapsibleChannelProblem (const unsigned & nup, const unsigned & ncollapsible, const unsigned & ndown, const unsigned & ny, const double & lup, const double & lcollapsible, const double & ldown, const double & ly)
Constructor: The arguments are the number of elements and the lengths of the domain.
~FSICollapsibleChannelProblem() [3/7]
template<class ELEMENT > FSICollapsibleChannelProblem< ELEMENT >::~FSICollapsibleChannelProblem () inline
Destructor (empty)
 {}
FSICollapsibleChannelProblem() [4/7]
template<class ELEMENT > FSICollapsibleChannelProblem< ELEMENT >::FSICollapsibleChannelProblem (const unsigned & nup, const unsigned & ncollapsible, const unsigned & ndown, const unsigned & ny, const double & lup, const double & lcollapsible, const double & ldown, const double & ly)
Constructor: The arguments are the number of elements and the lengths of the domain.
~FSICollapsibleChannelProblem() [4/7]
template<class ELEMENT > FSICollapsibleChannelProblem< ELEMENT >::~FSICollapsibleChannelProblem () inline
Destructor (empty)
 {}
FSICollapsibleChannelProblem() [5/7]
template<class ELEMENT > FSICollapsibleChannelProblem< ELEMENT >::FSICollapsibleChannelProblem (const unsigned & nup, const unsigned & ncollapsible, const unsigned & ndown, const unsigned & ny, const double & lup, const double & lcollapsible, const double & ldown, const double & ly)
Constructor: The arguments are the number of elements and the lengths of the domain.
~FSICollapsibleChannelProblem() [5/7]
template<class ELEMENT > FSICollapsibleChannelProblem< ELEMENT >::~FSICollapsibleChannelProblem () inline
Destructor (empty)
 {}
FSICollapsibleChannelProblem() [6/7]
template<class ELEMENT > FSICollapsibleChannelProblem< ELEMENT >::FSICollapsibleChannelProblem (const unsigned & nup, const unsigned & ncollapsible, const unsigned & ndown, const unsigned & ny, const double & lup, const double & lcollapsible, const double & ldown, const double & ly)
Constructor: The arguments are the number of elements and the lengths of the domain.
~FSICollapsibleChannelProblem() [6/7]
template<class ELEMENT > FSICollapsibleChannelProblem< ELEMENT >::~FSICollapsibleChannelProblem () inline
Destructor (empty)
 {}
FSICollapsibleChannelProblem() [7/7]
template<class ELEMENT > FSICollapsibleChannelProblem< ELEMENT >::FSICollapsibleChannelProblem (const unsigned & nup, const unsigned & ncollapsible, const unsigned & ndown, const unsigned & ny, const double & lup, const double & lcollapsible, const double & ldown, const double & ly, const bool & wall_jacobian_ignores_fluid_shear_stress_data, const bool & wall_jacobian_ignores_geometric_data, const bool & fluid_jacobian_ignores_geometric_data)
Constructor for the collapsible channel problem.
Constructor: The arguments are the number of elements and the lengths of the domain.
 {
  // Store problem parameters
  Nup=nup;
  Ncollapsible=ncollapsible;
  Ndown=ndown;
  Ny=ny;
  Lup=lup;
  Lcollapsible=lcollapsible;
  Ldown=ldown;
  Ly=ly;
  Wall_jacobian_ignores_fluid_shear_stress_data =
   wall_jacobian_ignores_fluid_shear_stress_data;
  Wall_jacobian_ignores_geometric_data=wall_jacobian_ignores_geometric_data;
  Fluid_jacobian_ignores_geometric_data=fluid_jacobian_ignores_geometric_data;
  // Overwrite maximum allowed residual to accomodate bad initial guesses
  Problem::Max_residuals=100000.0;
  // Allow a few extra Newton iterations
  Max_newton_iterations=20;
  // Allocate the timestepper -- this constructs the Problem's
  // time object with a sufficient amount of storage to store the
  // previous timsteps.
  add_time_stepper_pt(new BDF<2>);
  // Geometric object that represents the undeformed wall:
  // A straight line at height y=ly; starting at x=lup.
  UndeformedWall* undeformed_wall_pt=new UndeformedWall(lup,ly);
  //Create the "wall" mesh with FSI Hermite elements
  Wall_mesh_pt = new OneDLagrangianMesh<FSIHermiteBeamElement>
   //(2*Ncollapsible+5,Lcollapsible,undeformed_wall_pt);
   (Ncollapsible,Lcollapsible,undeformed_wall_pt);
  // Build a geometric object (one Lagrangian, two Eulerian coordinates)
  // from the wall mesh
  MeshAsGeomObject* wall_geom_object_pt=
   new MeshAsGeomObject(Wall_mesh_pt);
  //Build bulk (fluid) mesh
  Bulk_mesh_pt =
   new AlgebraicCollapsibleChannelMesh<ELEMENT>
   (nup, ncollapsible, ndown, ny,
    lup, lcollapsible, ldown, ly,
    wall_geom_object_pt,
    &BL_Squash::squash_fct,
    time_stepper_pt());
  // Create "surface mesh" that will contain only the prescribed-traction
  // elements. The constructor just creates the mesh without
  // giving it any elements, nodes, etc.
  Applied_fluid_traction_mesh_pt = new Mesh;
  // Create prescribed-traction elements from all elements that are
  // adjacent to boundary 5 (left boundary), but add them to a separate mesh
  create_traction_elements(5,Bulk_mesh_pt,Applied_fluid_traction_mesh_pt);
  // Complete build of fluid mesh
  //-----------------------------
  // Loop over the elements to set up element-specific
  // things that cannot be handled by constructor
  unsigned n_element=Bulk_mesh_pt->nelement();
  for(unsigned e=0;e<n_element;e++)
   {
    // Upcast from GeneralisedElement to the present element
    ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e));
    // Set flag which controls whether geometric data is ignored
    // when calculating the fluid Jacobian
    if(Fluid_jacobian_ignores_geometric_data)
     {
      el_pt->enable_bypass_fill_in_jacobian_from_geometric_data();
     }
    //Set the Reynolds number
    el_pt->re_pt() = &Global_Physical_Variables::Re;
    // Set the Womersley number
    el_pt->re_st_pt() = &Global_Physical_Variables::ReSt;
   } // end loop over elements
  // Apply boundary conditions for fluid
  //------------------------------------
  //Pin the velocity on the boundaries
  //x and y-velocities pinned along boundary 0 (bottom boundary) :
  unsigned ibound=0;
  unsigned num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  for (unsigned inod=0;inod<num_nod;inod++)
   {
    for(unsigned i=0;i<2;i++)
     {
      bulk_mesh_pt()->boundary_node_pt(ibound, inod)->pin(i);
     }
   }
  //x and y-velocities pinned along boundaries 2, 3, 4 (top boundaries) :
  for(ibound=2;ibound<5;ibound++)
   {
    num_nod= bulk_mesh_pt()->nboundary_node(ibound);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      for(unsigned i=0;i<2;i++)
       {
        bulk_mesh_pt()->boundary_node_pt(ibound, inod)->pin(i);
       }
     }
   }
  //y-velocity pinned along boundary 1 (right boundary):
  ibound=1;
  num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  for (unsigned inod=0;inod<num_nod;inod++)
   {
    bulk_mesh_pt()->boundary_node_pt(ibound, inod)->pin(1);
   }
  //y-velocity pinned along boundary 5 (left boundary):
  ibound=5;
  num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  for (unsigned inod=0;inod<num_nod;inod++)
   {
    bulk_mesh_pt()->boundary_node_pt(ibound, inod)->pin(1);
   }
 //end of pin_velocity
  // Complete build of applied traction elements
  //--------------------------------------------
  // Loop over the traction elements to pass pointer to prescribed
  // traction function
  unsigned n_el=Applied_fluid_traction_mesh_pt->nelement();
  for(unsigned e=0;e<n_el;e++)
   {
    // Upcast from GeneralisedElement to NavierStokes traction element
    NavierStokesTractionElement<ELEMENT> *el_pt =
     dynamic_cast< NavierStokesTractionElement<ELEMENT>*>(
      Applied_fluid_traction_mesh_pt->element_pt(e));
    // Set the pointer to the prescribed traction function
    el_pt->traction_fct_pt() = &Global_Physical_Variables::prescribed_traction;
   }
  //-------------------------------------------------------------
  // Set up displacement control mesh if required for steady run
  //-------------------------------------------------------------
  Displacement_control_mesh_pt=0;
  if (Control_Flags::Steady_run)
   {
    // Choose element in which displacement control is applied as
    // halfway along wall
    unsigned nel_ctrl=Ncollapsible/2;
    // Deal with even/odd number of wall elements
    Vector<double> s_displ_control(1);
    if (n_element%2==1)
     {
      s_displ_control[0]=0.0;
     }
    else
     {
      s_displ_control[0]=-1.0;
     }
    // Controlled element
    FSIHermiteBeamElement* controlled_element_pt=
     dynamic_cast<FSIHermiteBeamElement*>(Wall_mesh_pt->element_pt(nel_ctrl));
    // Fix the displacement in the y (1) direction...
    unsigned controlled_direction=1;
    // Output control point
    Vector<double> xi(1);
    Vector<double> x(2);
    controlled_element_pt->interpolated_xi(s_displ_control,xi);
    controlled_element_pt->interpolated_x(s_displ_control,x);
    oomph_info << "Displacement control for element: "
               << nel_ctrl << std::endl;
    oomph_info << "Displacement control applied at xi = ("
               << xi[0] << ")" << std::endl;
    oomph_info << "Corresponding to                x  = ("
               << x[0] << ", " << x[1] << ")" << std::endl;
    // Build displacement control element
    DisplacementControlElement* displ_control_el_pt=
     new DisplacementControlElement(controlled_element_pt,
                                    s_displ_control,
                                    controlled_direction,
                                    &Global_Physical_Variables::Prescribed_y);
    // set Pext_data_pt to point at displacement control load
    Global_Physical_Variables::Pext_data_pt=
     displ_control_el_pt->displacement_control_load_pt();
    // Create dedicated mesh
    Displacement_control_mesh_pt=new Mesh;
    // Add the displacement-control element to the mesh
    Displacement_control_mesh_pt->add_element_pt(displ_control_el_pt);
   }
  else
   {
    // Create Data object whose one-and-only value contains the
    // (in principle) adjustable load
    Global_Physical_Variables::Pext_data_pt=new Data(1);
    // Pin the external pressure because it isn't actually adjustable.
    Global_Physical_Variables::Pext_data_pt->pin(0);
    // Set the value of external pressure
    Global_Physical_Variables::external_pressure() = 0.0;
   }
  // Complete build of wall elements
  //--------------------------------
  //Loop over the elements to set physical parameters etc.
  n_element = wall_mesh_pt()->nelement();
  for(unsigned e=0;e<n_element;e++)
   {
    // Upcast to the specific element type
    FSIHermiteBeamElement *elem_pt =
     dynamic_cast<FSIHermiteBeamElement*>(wall_mesh_pt()->element_pt(e));
    // Do elememts take account of fluid shear stress when calculating Jacobian?
    if(Wall_jacobian_ignores_fluid_shear_stress_data)
     {
      elem_pt->disable_shear_stress_in_jacobian();
     }
    else
     {
      elem_pt->enable_shear_stress_in_jacobian();
     }
    // Set physical parameters for each element:
    elem_pt->sigma0_pt() = &Global_Physical_Variables::Sigma0;
    elem_pt->h_pt() = &Global_Physical_Variables::H;
    // Set the load vector for each element
    elem_pt->load_vector_fct_pt() = &Global_Physical_Variables::load;
    // Function that specifies the load ratios
    elem_pt->q_pt() = &Global_Physical_Variables::Q;
    // Set the undeformed shape for each element
    elem_pt->undeformed_beam_pt() = undeformed_wall_pt;
    // The normal on the wall elements as computed by the FSIHermiteElements
    // points away from the fluid rather than into the fluid (as assumed
    // by default)
    elem_pt->set_normal_pointing_out_of_fluid();
    // Displacement control for steady problem? If so, the load on *all*
    // elements is affected by an unknown -- the external pressure, stored
    // as the one-and-only value in a Data object: Add it to the
    // elements' external Data.
    if (Control_Flags::Steady_run)
     {
      //The external pressure is external data for all elements
      elem_pt->add_external_data(Global_Physical_Variables::Pext_data_pt);
     }
   } // end of loop over elements
  // Boundary conditions for wall mesh
  //----------------------------------
  // Set the boundary conditions: Each end of the beam is fixed in space
  // Loop over the boundaries (ends of the beam)
  for(unsigned b=0;b<2;b++)
   {
    // Pin displacements in both x and y directions
    wall_mesh_pt()->boundary_node_pt(b,0)->pin_position(0);
    wall_mesh_pt()->boundary_node_pt(b,0)->pin_position(1);
   }
  //Choose control nodes
  //---------------------
  // Left boundary
  ibound=5;
  num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  unsigned control_nod=num_nod/2;
  Left_node_pt= bulk_mesh_pt()->boundary_node_pt(ibound, control_nod);
  // Right boundary
  ibound=1;
  num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  control_nod=num_nod/2;
  Right_node_pt= bulk_mesh_pt()->boundary_node_pt(ibound, control_nod);
  // Set the pointer to the control node on the wall
  Wall_node_pt=wall_mesh_pt()->node_pt(Ncollapsible/2);
  // Add the sub meshes to the problem
  add_sub_mesh(Bulk_mesh_pt);
  add_sub_mesh(Applied_fluid_traction_mesh_pt);
  add_sub_mesh(Wall_mesh_pt);
  if (Displacement_control_mesh_pt != 0)
   {
    add_sub_mesh(Displacement_control_mesh_pt);
   }
  // Combine all submeshes into a single Mesh
  build_global_mesh();
  // Setup FSI
  //----------
  // The velocity of the fluid nodes on the wall (fluid mesh boundary 3)
  // is set by the wall motion -- hence the no-slip condition must be
  // re-applied whenever a node update is performed for these nodes.
  // Such tasks may be performed automatically by the auxiliary node update
  // function specified by a function pointer:
  ibound=3;
  num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  for (unsigned inod=0;inod<num_nod;inod++)
   {
    static_cast<AlgebraicNode*>(
     bulk_mesh_pt()->boundary_node_pt(ibound, inod))->
     set_auxiliary_node_update_fct_pt(
      FSI_functions::apply_no_slip_on_moving_wall);
   }
  // Work out which fluid dofs affect the residuals of the wall elements:
  // We pass the boundary between the fluid and solid meshes and
  // pointers to the meshes. The interaction boundary is boundary 3 of the
  // 2D fluid mesh.
  FSI_functions::setup_fluid_load_info_for_solid_elements<ELEMENT,2>
   (this,3,Bulk_mesh_pt,Wall_mesh_pt);
  // Setup equation numbering scheme
  oomph_info <<"Number of equations: " << assign_eqn_numbers() << std::endl;
 }//end of constructor
References oomph::Mesh::add_element_pt(), oomph::GeneralisedElement::add_external_data(), oomph::FSI_functions::apply_no_slip_on_moving_wall(), b, oomph::FSIWallElement::disable_shear_stress_in_jacobian(), oomph::DisplacementControlElement::displacement_control_load_pt(), e(), oomph::FSIWallElement::enable_shear_stress_in_jacobian(), Global_Physical_Variables::external_pressure(), Global_Physical_Variables::H, oomph::KirchhoffLoveBeamEquations::h_pt(), i, oomph::FiniteElement::interpolated_x(), oomph::SolidFiniteElement::interpolated_xi(), Global_Parameters::Ldown, Global_Physical_Variables::load(), oomph::KirchhoffLoveBeamEquations::load_vector_fct_pt, Global_Parameters::Lup, Mesh_Parameters::ly, Global_Parameters::Ly, oomph::Locate_zeta_helpers::Max_newton_iterations, Mesh_Parameters::ny, GlobalParameters::Ny, oomph::oomph_info, Global_Physical_Variables::Pext_data_pt, oomph::Data::pin(), Global_Physical_Variables::prescribed_traction(), Global_Physical_Variables::Prescribed_y, Global_Physical_Variables::Q, oomph::FSIWallElement::q_pt(), Global_Physical_Variables::Re, Global_Physical_Variables::ReSt, oomph::FSIHermiteBeamElement::set_normal_pointing_out_of_fluid(), Global_Physical_Variables::Sigma0, oomph::KirchhoffLoveBeamEquations::sigma0_pt(), BL_Squash::squash_fct(), Control_Flags::Steady_run, oomph::NavierStokesTractionElement< ELEMENT >::traction_fct_pt, oomph::KirchhoffLoveBeamEquations::undeformed_beam_pt(), and plotDoE::x.
~FSICollapsibleChannelProblem() [7/7]
template<class ELEMENT > FSICollapsibleChannelProblem< ELEMENT >::~FSICollapsibleChannelProblem () inline
Destructor (empty)
 {}
Member Function Documentation
actions_after_adapt() [1/3]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_after_adapt virtual
Actions after adapt: Rebuild the mesh of prescribed traction elements.
Actions after adapt: Rebuild the mesh of prescribed traction elements and reset FSI
Reimplemented from oomph::Problem.
 {
  // Create prescribed-flux elements from all elements that are
  // adjacent to boundary 5 and add them to surface mesh
  create_traction_elements(5,Bulk_mesh_pt,Applied_fluid_traction_mesh_pt);
  // Rebuild the global mesh
  rebuild_global_mesh();
  // Unpin all pressure dofs
  RefineableNavierStokesEquations<2>::
   unpin_all_pressure_dofs(Bulk_mesh_pt->element_pt());
  // Pin redundant pressure dofs
  RefineableNavierStokesEquations<2>::
   pin_redundant_nodal_pressures(Bulk_mesh_pt->element_pt());
  // Loop over the traction elements to pass pointer to prescribed
  // traction function
  unsigned n_element=Applied_fluid_traction_mesh_pt->nelement();
  for(unsigned e=0;e<n_element;e++)
   {
    // Upcast from GeneralisedElement to NavierStokesTractionElement element
    NavierStokesTractionElement<ELEMENT> *el_pt =
     dynamic_cast<NavierStokesTractionElement<ELEMENT>*>(
      Applied_fluid_traction_mesh_pt->element_pt(e));
    // Set the pointer to the prescribed traction function
    el_pt->traction_fct_pt() = &Global_Physical_Variables::prescribed_traction;
   }
  // The functions used to update the no slip boundary conditions
  // must be set on any new nodes that have been created during the
  // mesh adaptation process.
  // There is no mechanism by which auxiliary update functions
  // are copied to newly created nodes.
  // (because, unlike boundary conditions, they don't occur exclusively
  // at boundaries)
  // The velocity of the fluid nodes on the wall (fluid mesh boundary 3)
  // is set by the wall motion -- hence the no-slip condition needs to be
  // re-applied whenever a node update is performed for these nodes.
  // Such tasks may be performed automatically by the auxiliary node update
  // function specified by a function pointer:
  unsigned ibound=3;
  unsigned num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  for (unsigned inod=0;inod<num_nod;inod++)
   {
    bulk_mesh_pt()->boundary_node_pt(ibound, inod)->
     set_auxiliary_node_update_fct_pt(
      FSI_functions::apply_no_slip_on_moving_wall);
   }
  // (Re-)setup fsi: Work out which fluid dofs affect wall elements
  // the correspondance between wall dofs and fluid elements is handled
  // during the remeshing, but the "reverse" association must be done
  // separately. We need to set up the interaction every time because the fluid
  // element adjacent to a given solid element's integration point may have
  // changed.We pass the boundary between the fluid and solid meshes and
  // pointers to the meshes. The interaction boundary is boundary 3 of
  // the Fluid mesh.
  FSI_functions::setup_fluid_load_info_for_solid_elements<ELEMENT,2>
   (this,3,Bulk_mesh_pt,Wall_mesh_pt);
 } // end of actions_after_adapt
References oomph::FSI_functions::apply_no_slip_on_moving_wall(), oomph::Mesh::boundary_node_pt(), e(), oomph::Mesh::nboundary_node(), Global_Physical_Variables::prescribed_traction(), and oomph::NavierStokesTractionElement< ELEMENT >::traction_fct_pt.
actions_after_adapt() [2/3]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_after_adapt () virtual
Actions after adapt: Rebuild the mesh of prescribed traction elements and reset FSI
Reimplemented from oomph::Problem.
actions_after_adapt() [3/3]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_after_adapt () virtual
Actions after adapt: Rebuild the mesh of prescribed traction elements and reset FSI
Reimplemented from oomph::Problem.
actions_after_distribute()
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_after_distribute () inline
Actions after distribute: create traction elements and reset FSI.
   {
    // Just call actions_after_adapt
    actions_after_adapt();
   }
actions_after_newton_solve() [1/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [2/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [3/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [4/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [5/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [6/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [7/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_adapt() [1/3]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_before_adapt virtual
Actions before adapt: Wipe the mesh of prescribed traction elements.
Reimplemented from oomph::Problem.
 {
  // Kill the traction elements and wipe surface mesh
  delete_traction_elements(Applied_fluid_traction_mesh_pt);
  // Rebuild the global mesh.
  rebuild_global_mesh();
 } // end of actions_before_adapt
actions_before_adapt() [2/3]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_before_adapt () virtual
Actions before adapt: Wipe the mesh of prescribed traction elements.
Reimplemented from oomph::Problem.
actions_before_adapt() [3/3]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_before_adapt () virtual
Actions before adapt: Wipe the mesh of prescribed traction elements.
Reimplemented from oomph::Problem.
actions_before_distribute()
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_before_distribute () inline
Actions before distribute: wipe the mesh of prescribed traction elements.
   {
    // actions_before_adapt does exactly the same thing, so just call it
    actions_before_adapt();
   }
actions_before_newton_convergence_check() [1/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_convergence_check () inline virtual
Update before checking Newton convergence: Update the nodal positions in the fluid mesh in response to possible changes in the wall shape.
Reimplemented from oomph::Problem.
Reimplemented in SegregatedFSICollapsibleChannelProblem< ELEMENT >, and SegregatedFSICollapsibleChannelProblem< ELEMENT >.
   {
    // Update mesh
    Bulk_mesh_pt->node_update();
    // Increment counter
    Newton_iter++;
   }
References FSICollapsibleChannelProblem< ELEMENT >::Bulk_mesh_pt, and FSICollapsibleChannelProblem< ELEMENT >::Newton_iter.
actions_before_newton_convergence_check() [2/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_convergence_check () inline virtual
Update before checking Newton convergence: Update the nodal positions in the fluid mesh in response to possible changes in the wall shape
Reimplemented from oomph::Problem.
   {
    Bulk_mesh_pt->node_update();
   }
actions_before_newton_convergence_check() [3/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_convergence_check () inline virtual
Update before checking Newton convergence: Update the nodal positions in the fluid mesh in response to possible changes in the wall shape
Reimplemented from oomph::Problem.
   {
    Bulk_mesh_pt->node_update();
   }
actions_before_newton_convergence_check() [4/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_convergence_check () inline virtual
Update no slip before Newton convergence check.
Reimplemented from oomph::Problem.
   {
    // Moving wall: No slip; this implies that the velocity needs
    // to be updated in response to wall motion
    unsigned ibound=3;
    unsigned num_nod=bulk_mesh_pt()->nboundary_node(ibound);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      // Which node are we dealing with?
      Node* node_pt=bulk_mesh_pt()->boundary_node_pt(ibound,inod);
      // Apply no slip
      FSI_functions::apply_no_slip_on_moving_wall(node_pt);
     }
   }
References oomph::FSI_functions::apply_no_slip_on_moving_wall().
actions_before_newton_convergence_check() [5/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_convergence_check () inline virtual
Update no slip before Newton convergence check.
Reimplemented from oomph::Problem.
   {
    // Moving wall: No slip; this implies that the velocity needs
    // to be updated in response to wall motion
    unsigned ibound=3;
    unsigned num_nod=bulk_mesh_pt()->nboundary_node(ibound);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      // Which node are we dealing with?
      Node* node_pt=bulk_mesh_pt()->boundary_node_pt(ibound,inod);
      // Apply no slip
      FSI_functions::apply_no_slip_on_moving_wall(node_pt);
     }
   }
References oomph::FSI_functions::apply_no_slip_on_moving_wall().
actions_before_newton_convergence_check() [6/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_convergence_check () inline virtual
Update before checking Newton convergence: Update the nodal positions in the fluid mesh in response to possible changes in the wall shape
Reimplemented from oomph::Problem.
   {
    Bulk_mesh_pt->node_update();
   }
actions_before_newton_convergence_check() [7/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_convergence_check () inline virtual
Update before checking Newton convergence: Update the nodal positions in the fluid mesh in response to possible changes in the wall shape
Reimplemented from oomph::Problem.
   {
    Bulk_mesh_pt->node_update();
   }
actions_before_newton_solve() [1/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Actions before solve. Reset counter for number of Newton iterations.
Reimplemented from oomph::Problem.
Reimplemented in SegregatedFSICollapsibleChannelProblem< ELEMENT >.
   {
    Newton_iter=0;
   }
References FSICollapsibleChannelProblem< ELEMENT >::Newton_iter.
actions_before_newton_solve() [2/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [3/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [4/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [5/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [6/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [7/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
bulk_mesh_pt() [1/7]
template<class ELEMENT > AlgebraicCollapsibleChannelMesh<ELEMENT>* FSICollapsibleChannelProblem< ELEMENT >::bulk_mesh_pt () inline
Access function for the specific bulk (fluid) mesh.
   {
    // Upcast from pointer to the Mesh base class to the specific
    // element type that we're using here.
    return dynamic_cast<
     AlgebraicCollapsibleChannelMesh<ELEMENT>*>
     (Bulk_mesh_pt);
   }
References FSICollapsibleChannelProblem< ELEMENT >::Bulk_mesh_pt.
bulk_mesh_pt() [2/7]
template<class ELEMENT > AlgebraicCollapsibleChannelMesh<ELEMENT>* FSICollapsibleChannelProblem< ELEMENT >::bulk_mesh_pt () inline
Access function for the specific bulk (fluid) mesh.
   {
    // Upcast from pointer to the Mesh base class to the specific
    // element type that we're using here.
    return dynamic_cast<
     AlgebraicCollapsibleChannelMesh<ELEMENT>*>
     (Bulk_mesh_pt);
   }
bulk_mesh_pt() [3/7]
template<class ELEMENT > RefineableAlgebraicCollapsibleChannelMesh<ELEMENT>* FSICollapsibleChannelProblem< ELEMENT >::bulk_mesh_pt () inline
Access function for the specific bulk (fluid) mesh.
   {
    // Upcast from pointer to the Mesh base class to the specific
    // element type that we're using here.
    return dynamic_cast<
     RefineableAlgebraicCollapsibleChannelMesh<ELEMENT>*>
     (Bulk_mesh_pt);
   }
bulk_mesh_pt() [4/7]
template<class ELEMENT > ElasticCollapsibleChannelMesh<ELEMENT>* FSICollapsibleChannelProblem< ELEMENT >::bulk_mesh_pt () inline
Access function for the specific bulk (fluid) mesh.
   {
    // Upcast from pointer to the Mesh base class to the specific
    // element type that we're using here.
    return dynamic_cast<
     ElasticCollapsibleChannelMesh<ELEMENT>*>
     (Bulk_mesh_pt);
   }
bulk_mesh_pt() [5/7]
template<class ELEMENT > ElasticRefineableCollapsibleChannelMesh<ELEMENT>* FSICollapsibleChannelProblem< ELEMENT >::bulk_mesh_pt () inline
Access function for the specific bulk (fluid) mesh.
   {
    // Upcast from pointer to the Mesh base class to the specific
    // element type that we're using here.
    return dynamic_cast<
     ElasticRefineableCollapsibleChannelMesh<ELEMENT>*>
     (Bulk_mesh_pt);
   }
bulk_mesh_pt() [6/7]
template<class ELEMENT > RefineableAlgebraicCollapsibleChannelMesh<ELEMENT>* FSICollapsibleChannelProblem< ELEMENT >::bulk_mesh_pt () inline
Access function for the specific bulk (fluid) mesh.
   {
    // Upcast from pointer to the Mesh base class to the specific
    // element type that we're using here.
    return dynamic_cast<
     RefineableAlgebraicCollapsibleChannelMesh<ELEMENT>*>
     (Bulk_mesh_pt);
   }
bulk_mesh_pt() [7/7]
template<class ELEMENT > AlgebraicCollapsibleChannelMesh<ELEMENT>* FSICollapsibleChannelProblem< ELEMENT >::bulk_mesh_pt () inline
Access function for the specific bulk (fluid) mesh.
   {
    // Upcast from pointer to the Mesh base class to the specific
    // element type that we're using here.
    return dynamic_cast<
     AlgebraicCollapsibleChannelMesh<ELEMENT>*>
     (Bulk_mesh_pt);
   }
create_lagrange_multiplier_elements() [1/2]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::create_lagrange_multiplier_elements private
Create elements that impose the prescribed boundary displacement.
Create elements that enforce prescribed boundary motion by Lagrange multipliers
 {
  // Lagrange multiplier elements are located on boundary 3:
  unsigned b=3;
  // How many bulk elements are adjacent to boundary b?
  unsigned n_element = bulk_mesh_pt()->nboundary_element(b);
  // Loop over the bulk elements adjacent to boundary b?
  for(unsigned e=0;e<n_element;e++)
   {
    // Get pointer to the bulk element that is adjacent to boundary b
    ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
     bulk_mesh_pt()->boundary_element_pt(b,e));
    //Find the index of the face of element e along boundary b
    int face_index = bulk_mesh_pt()->face_index_at_boundary(b,e);
    // Create new element and add to mesh
    Lagrange_multiplier_mesh_pt->add_element_pt(
     new ImposeDisplacementByLagrangeMultiplierElement<ELEMENT>(
      bulk_elem_pt,face_index));
   }
  // Loop over the elements in the Lagrange multiplier element mesh
  // for elements on the top boundary (boundary 3)
  n_element=Lagrange_multiplier_mesh_pt->nelement();
  for(unsigned i=0;i<n_element;i++)
   {
    //Cast to a Lagrange multiplier element
    ImposeDisplacementByLagrangeMultiplierElement<ELEMENT> *el_pt =
     dynamic_cast<ImposeDisplacementByLagrangeMultiplierElement<ELEMENT>*>
     (Lagrange_multiplier_mesh_pt->element_pt(i));
    // Set the GeomObject that defines the boundary shape and set
    // which bulk boundary we are attached to(needed to extract
    // the boundary coordinate from the bulk nodes)
    el_pt->set_boundary_shape_geom_object_pt(Wall_geom_object_pt,b);
    // Loop over the nodes
    unsigned nnod=el_pt->nnode();
    for (unsigned j=0;j<nnod;j++)
     {
      Node* nod_pt = el_pt->node_pt(j);
      // Is the node also on boundary 2 or 4?
      if ((nod_pt->is_on_boundary(2))||(nod_pt->is_on_boundary(4)))
       {
        // How many nodal values were used by the "bulk" element
        // that originally created this node?
        unsigned n_bulk_value=el_pt->nbulk_value(j);
        // The remaining ones are Lagrange multipliers and we pin them.
        unsigned nval=nod_pt->nvalue();
        for (unsigned j=n_bulk_value;j<nval;j++)
         {
          nod_pt->pin(j);
         }
       }
     }
   }
 } // end of create_lagrange_multiplier_elements
References b, oomph::Mesh::boundary_element_pt(), e(), oomph::Mesh::face_index_at_boundary(), i, oomph::Node::is_on_boundary(), j, oomph::Mesh::nboundary_element(), oomph::FaceElement::nbulk_value(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Data::nvalue(), oomph::Data::pin(), and oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt().
create_lagrange_multiplier_elements() [2/2]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::create_lagrange_multiplier_elements () private
Create elements that enforce prescribed boundary motion by Lagrange multiplilers
create_traction_elements() [1/6]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::create_traction_elements (const unsigned & b, Mesh *const & bulk_mesh_pt, Mesh *const & traction_mesh_pt) private
Create the prescribed traction elements on boundary b.
Create the traction elements.
 {
  // How many bulk elements are adjacent to boundary b?
  unsigned n_element = bulk_mesh_pt->nboundary_element(b);
  // Loop over the bulk elements adjacent to boundary b?
  for(unsigned e=0;e<n_element;e++)
   {
    // Get pointer to the bulk element that is adjacent to boundary b
    ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>
     (bulk_mesh_pt->boundary_element_pt(b,e));
    //What is the index of the face of element e along boundary b
    int face_index = bulk_mesh_pt->face_index_at_boundary(b,e);
    // Build the corresponding prescribed-traction element
    NavierStokesTractionElement<ELEMENT>* flux_element_pt =
     new  NavierStokesTractionElement<ELEMENT>(bulk_elem_pt,face_index);
    //Add the prescribed-traction element to the surface mesh
    traction_mesh_pt->add_element_pt(flux_element_pt);
   } //end of loop over bulk elements adjacent to boundary b
 } // end of create_traction_elements
References oomph::Mesh::add_element_pt(), b, oomph::Mesh::boundary_element_pt(), e(), oomph::Mesh::face_index_at_boundary(), and oomph::Mesh::nboundary_element().
create_traction_elements() [2/6]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::create_traction_elements (const unsigned & b, Mesh *const & bulk_mesh_pt, Mesh *const & traction_mesh_pt) private
Create the prescribed traction elements on boundary b.
create_traction_elements() [3/6]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::create_traction_elements (const unsigned & b, Mesh *const & bulk_mesh_pt, Mesh *const & traction_mesh_pt) private
Create the prescribed traction elements on boundary b.
create_traction_elements() [4/6]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::create_traction_elements (const unsigned & b, Mesh *const & bulk_mesh_pt, Mesh *const & traction_mesh_pt) private
Create the prescribed traction elements on boundary b.
create_traction_elements() [5/6]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::create_traction_elements (const unsigned & b, Mesh *const & bulk_mesh_pt, Mesh *const & traction_mesh_pt) private
Create the prescribed traction elements on boundary b.
create_traction_elements() [6/6]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::create_traction_elements (const unsigned & b, Mesh *const & bulk_mesh_pt, Mesh *const & traction_mesh_pt) private
Create the prescribed traction elements on boundary b.
delete_lagrange_multiplier_elements() [1/2]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::delete_lagrange_multiplier_elements private
Delete elements that enforce prescribed boundary motion by Lagrange multipliers
Delete elements that impose the prescribed boundary displacement and wipe the associated mesh
 {
  // How many surface elements are in the surface mesh
  unsigned n_element = Lagrange_multiplier_mesh_pt->nelement();
  // Loop over the surface elements
  for(unsigned e=0;e<n_element;e++)
   {
    // Kill surface element
    delete Lagrange_multiplier_mesh_pt->element_pt(e);
   }
  // Wipe the mesh
  Lagrange_multiplier_mesh_pt->flush_element_and_node_storage();
 } // end of delete_lagrange_multiplier_elements
References e().
delete_lagrange_multiplier_elements() [2/2]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::delete_lagrange_multiplier_elements () private
Delete elements that enforce prescribed boundary motion by Lagrange multiplilers
delete_traction_elements() [1/4]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::delete_traction_elements (Mesh *const & traction_mesh_pt) private
Delete prescribed traction elements from the surface mesh.
Delete traction elements and wipe the surface mesh.
 {
  // How many surface elements are in the surface mesh
  unsigned n_element = surface_mesh_pt->nelement();
  // Loop over the surface elements
  for(unsigned e=0;e<n_element;e++)
   {
    // Kill surface element
    delete surface_mesh_pt->element_pt(e);
   }
  // Wipe the mesh
  surface_mesh_pt->flush_element_and_node_storage();
 } // end of delete_traction_elements
References e(), oomph::Mesh::element_pt(), oomph::Mesh::flush_element_and_node_storage(), and oomph::Mesh::nelement().
delete_traction_elements() [2/4]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::delete_traction_elements (Mesh *const & traction_mesh_pt) private
Delete prescribed traction elements from the surface mesh.
delete_traction_elements() [3/4]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::delete_traction_elements (Mesh *const & traction_mesh_pt) private
Delete prescribed traction elements from the surface mesh.
delete_traction_elements() [4/4]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::delete_traction_elements (Mesh *const & traction_mesh_pt) private
Delete prescribed traction elements from the surface mesh.
doc_solution() [1/6]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution.
 {
 #ifdef MACRO_ELEMENT_NODE_UPDATE
  // Doc fsi
  if (CommandLineArgs::Argc>1)
   {
    FSI_functions::doc_fsi<MacroElementNodeUpdateNode>(Bulk_mesh_pt,Wall_mesh_pt,doc_info);
   }
 #else
  // Doc fsi
  if (CommandLineArgs::Argc>1)
   {
    FSI_functions::doc_fsi<AlgebraicNode>(Bulk_mesh_pt,Wall_mesh_pt,doc_info);
   }
 #endif
  ofstream some_file;
  char filename[100];
  // Number of plot points
  unsigned npts;
  npts=5;
  // Output fluid solution
  sprintf(filename,"%s/soln%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  bulk_mesh_pt()->output(some_file,npts);
  some_file.close();
  // Document the wall shape
  sprintf(filename,"%s/beam%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  wall_mesh_pt()->output(some_file,npts);
  some_file.close();
  // Write trace file
  trace_file << time_pt()->time() << " "
             << Wall_node_pt->x(1) << " "
             << Left_node_pt->value(0) << " "
             << Right_node_pt->value(0) << " "
             << Global_Physical_Variables::P_ext  << " "
             << std::endl;
 } // end_of_doc_solution
References oomph::CommandLineArgs::Argc, oomph::DocInfo::directory(), MergeRestartFiles::filename, oomph::DocInfo::number(), and Global_Physical_Variables::P_ext.
doc_solution() [2/6]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution.
doc_solution() [3/6]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution.
doc_solution() [4/6]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution.
doc_solution() [5/6]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution.
doc_solution() [6/6]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution.
doc_solution_steady()
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::doc_solution_steady (DocInfo & doc_info, ofstream & trace_file, const double & cpu, const unsigned & niter) virtual
Doc the steady solution.
Doc the solution for a steady run.
 {
  ofstream some_file;
  char filename[100];
  // Number of plot points
  unsigned npts;
  npts=5;
  // Output fluid solution
  sprintf(filename,"%s/soln%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  bulk_mesh_pt()->output(some_file,npts);
  some_file.close();
  // Document the wall shape
  sprintf(filename,"%s/beam%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  wall_mesh_pt()->output(some_file,npts);
  some_file.close();
 // Write restart file
  sprintf(filename,"%s/restart%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  some_file.precision(16);
  dump_it(some_file);
  some_file.close();
  // Write trace file
  trace_file << Global_Physical_Variables::P_ext_data_pt->value(0)  << " ";
  trace_file << Global_Physical_Variables::Yprescr  << " ";
  // Write trace file
  trace_file << Left_node_pt->value(0) << " "
             << Right_node_pt->value(0) << " "
             << cpu << " "
             << Newton_iter << " "
             << std::endl;
 } // end_of_doc_solution_steady
References GlobalParameters::Doc_info, MergeRestartFiles::filename, Global_Physical_Variables::P_ext_data_pt, and Global_Physical_Variables::Yprescr.
doc_solution_unsteady()
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::doc_solution_unsteady (DocInfo & doc_info, ofstream & trace_file, const double & cpu, const unsigned & niter) virtual
Doc the unsteady solution.
Doc the solution for an unstady run.
 {
  ofstream some_file;
  char filename[100];
  // Number of plot points
  unsigned npts;
  npts=5;
  // Output fluid solution
  sprintf(filename,"%s/soln%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  bulk_mesh_pt()->output(some_file,npts);
  some_file.close();
  // Document the wall shape
  sprintf(filename,"%s/beam%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  wall_mesh_pt()->output(some_file,npts);
  some_file.close();
 // Write restart file
  sprintf(filename,"%s/restart%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  dump_it(some_file);
  some_file.close();
  // Write trace file
  trace_file << time_pt()->time() << " ";
  // Get/doc y-coordinate of control point
  Vector<double> r(2);
  Ctrl_geom_obj_pt->position(S_displ_ctrl,r);
  trace_file << r[1]  << " ";
  // Write trace file
  trace_file << Left_node_pt->value(0) << " "
             << Right_node_pt->value(0) << " "
             << cpu << " "
             << Newton_iter << " "
             << std::endl;
 } // end_of_doc_solution_steady
References GlobalParameters::Doc_info, MergeRestartFiles::filename, and UniformPSDSelfTest::r.
dump_it()
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::dump_it (ofstream & dump_file) protected
Dump problem to disk to allow for restart.
Dump the solution to disk to allow for restart.
 {
  // Number of submeshes must agree when dumping/restarting so
  // temporarily add displacement control mesh back in before dumping...
  if (!Displ_control)
   {
    flush_sub_meshes();
    add_sub_mesh(Bulk_mesh_pt);
    add_sub_mesh(Wall_mesh_pt);
    add_sub_mesh(Displ_control_mesh_pt);
    rebuild_global_mesh();
    assign_eqn_numbers();
   }
  // Write current external pressure
  dump_file <<  Global_Physical_Variables::P_ext_data_pt->value(0)
            << " # external pressure" << std::endl;
  // Call generic dump()
  Problem::dump(dump_file);
  // ...strip displacement control mesh back out after dumping if
  // we don't actually need it
  if (!Displ_control)
   {
    flush_sub_meshes();
    add_sub_mesh(Bulk_mesh_pt);
    add_sub_mesh(Wall_mesh_pt);
    rebuild_global_mesh();
    assign_eqn_numbers();
   }
 } // end of dump_it
References Global_Physical_Variables::P_ext_data_pt.
restart()
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::restart (ifstream & restart_file) protected
Read problem for restart from specified restart file.
Read solution from disk for restart.
 {
 // Read external pressure
 // Read line up to termination sign
  string input_string;
  getline(restart_file,input_string,'#');
  restart_file.ignore(80,'\n');
  if (Global_Physical_Variables::P_step!=0.0)
   {
    std::cout
     << "Increasing external pressure from "
     << double(atof(input_string.c_str())) << " to "
     << double(atof(input_string.c_str()))+Global_Physical_Variables::P_step
     << std::endl;
   }
  else
   {
    std::cout << "Running with unchanged external pressure of "
              << double(atof(input_string.c_str())) << std::endl;
   }
  // Set external pressure
  Global_Physical_Variables::P_ext_data_pt->
   set_value(0,double(atof(input_string.c_str()))+
             Global_Physical_Variables::P_step);
  // Read the generic problem data from restart file
  Problem::read(restart_file);
  //Now update the position of the nodes to be consistent with
  //the possible precision loss caused by reading in the data from disk
  this->Bulk_mesh_pt->node_update();
  // Strip out displacement control mesh if we don't need it
  if (!Displ_control)
   {
    flush_sub_meshes();
    add_sub_mesh(Bulk_mesh_pt);
    add_sub_mesh(Wall_mesh_pt);
    rebuild_global_mesh();
    assign_eqn_numbers();
   }
 } // end of restart
References Global_Physical_Variables::P_ext_data_pt, Global_Physical_Variables::P_step, and Eigen::TensorSycl::internal::read().
set_initial_condition() [1/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::set_initial_condition virtual
Apply initial conditions.
Reimplemented from oomph::Problem.
 {
  // Check that timestepper is from the BDF family
  if (!Steady_flag)
   {
    if (time_stepper_pt()->type()!="BDF")
     {
      std::ostringstream error_stream;
      error_stream << "Timestepper has to be from the BDF family!\n"
                   << "You have specified a timestepper from the "
                   << time_stepper_pt()->type() << " family" << std::endl;
      throw OomphLibError(error_stream.str(),
                          OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
     }
   }
  // Pointer to restart file
  ifstream* restart_file_pt=0;
  // Restart?
  //---------
  if (Flags::Restart_file_name!="")
   {
    // Open restart file
    restart_file_pt= new ifstream(Flags::Restart_file_name.c_str(),
                                  ios_base::in);
    if (restart_file_pt!=0)
     {
      cout << "Have opened " << Flags::Restart_file_name <<
       " for restart. " << std::endl;
      restart(*restart_file_pt);
      return;
     }
    else
     {
      std::ostringstream error_stream;
      error_stream
       << "ERROR while trying to open " << Flags::Restart_file_name <<
       " for restart." << std::endl;
      throw OomphLibError(
       error_stream.str(),
       OOMPH_CURRENT_FUNCTION,
       OOMPH_EXCEPTION_LOCATION);
     }
   }
  // No restart
  else
   {
    // Update the mesh
    bulk_mesh_pt()->node_update();
    // Loop over the nodes to set initial guess everywhere
    unsigned num_nod = bulk_mesh_pt()->nnode();
    for (unsigned n=0;n<num_nod;n++)
     {
      // Get nodal coordinates
      Vector<double> x(2);
      x[0]=bulk_mesh_pt()->node_pt(n)->x(0);
      x[1]=bulk_mesh_pt()->node_pt(n)->x(1);
      // Assign initial condition: Steady Poiseuille flow
      bulk_mesh_pt()->node_pt(n)->set_value(0,6.0*(x[1]/Ly)*(1.0-(x[1]/Ly)));
      bulk_mesh_pt()->node_pt(n)->set_value(1,0.0);
     }
    // Assign initial values for an impulsive start
    bulk_mesh_pt()->assign_initial_values_impulsive();
   }
 } // end of set_initial_condition
References Global_Parameters::Ly, n, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, Flags::Restart_file_name, Flags::Steady_flag, compute_granudrum_aor::type, and plotDoE::x.
set_initial_condition() [2/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::set_initial_condition () virtual
Apply initial conditions.
Reimplemented from oomph::Problem.
set_initial_condition() [3/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::set_initial_condition () virtual
Apply initial conditions.
Reimplemented from oomph::Problem.
set_initial_condition() [4/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::set_initial_condition () virtual
Apply initial conditions.
Reimplemented from oomph::Problem.
set_initial_condition() [5/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::set_initial_condition () virtual
Apply initial conditions.
Reimplemented from oomph::Problem.
set_initial_condition() [6/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::set_initial_condition () virtual
Apply initial conditions.
Reimplemented from oomph::Problem.
set_initial_condition() [7/7]
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::set_initial_condition () virtual
Apply initial conditions.
Reimplemented from oomph::Problem.
steady_run()
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::steady_run virtual
Steady run.
Steady run; virtual so it can be overloaded in derived problem classes
Reimplemented in SegregatedFSICollapsibleChannelProblem< ELEMENT >, and SegregatedFSICollapsibleChannelProblem< ELEMENT >.
 {
  // Set initial value for external pressure (on the wall stiffness scale).
  // This can be overwritten in set_initial_condition.
  Global_Physical_Variables::P_ext_data_pt->
   set_value(0,Global_Physical_Variables::Pmin);
  // Apply initial condition
  set_initial_condition();
  //Set output directory
  Doc_info.set_directory("RESLT");
  // Open a trace file
  ofstream trace_file;
  char filename[100];
  sprintf(filename,"%s/trace.dat",Doc_info.directory().c_str());
  trace_file.open(filename);
  // Write trace file header
  trace_file << "VARIABLES=\"p<sub>ext</sub>\","
             << "\"y<sub>ctrl</sub>\",";
  trace_file << "\"u_1\","
             << "\"u_2\","
             << "\"CPU time for solve\","
             << "\"Number of Newton iterations\","
             << std::endl;
  trace_file << "ZONE T=\"";
  trace_file << "Re=" << Global_Physical_Variables::Re << ", ";
  trace_file << "Q=" << Global_Physical_Variables::Q << ", ";
  trace_file << "resolution factor: " << Flags::Resolution_factor << ". ";
   trace_file << Flags::Run_identifier_string << "\" ";
  trace_file << std::endl;
  // Output the initial solution (dummy for CPU time)
  doc_solution_steady(Doc_info,trace_file,0.0,0);
  // Increment step number
  Doc_info.number()++;
  // Increment for external pressure (on the wall stiffness scale)
  double delta_p=(Global_Physical_Variables::Pmax-
                  Global_Physical_Variables::Pmin)/double(Flags::Nsteps-1);
  // Initial and final values for control position
  Global_Physical_Variables::Yprescr=1.0;
  // Steady run
  double delta_y=
   (Global_Physical_Variables::Yprescr_min-Global_Physical_Variables::Yprescr)/
   double(Flags::Nsteps-1);
  // Parameter study
  //----------------
  for (unsigned istep=0;istep<Flags::Nsteps;istep++)
   {
    // Displacement control?
    if (Displ_control)
     {
      std::cout << "Solving for control displ = "
                << Global_Physical_Variables::Yprescr
                << std::endl;
     }
    else
     {
      std::cout << "Solving for p_ext = "
                << Global_Physical_Variables::P_ext_data_pt->value(0)
                << std::endl;
     }
    // Solve the problem
    //------------------
    clock_t t_start = clock();
    // Explit call to the steady Newton solve.
    steady_newton_solve();
    clock_t t_end= clock();
    double cpu=double(t_end-t_start)/CLOCKS_PER_SEC;
    // Outpt the solution
    //-------------------
    doc_solution_steady(Doc_info,trace_file,cpu,0);
    // Step number
    Doc_info.number()++;
    // Adjust control parameter
    if (Displ_control)
     {
      // Increment control position
      Global_Physical_Variables::Yprescr+=delta_y;
     }
    else
     {
      // Increment external pressure
      double old_p=Global_Physical_Variables::P_ext_data_pt->value(0);
      Global_Physical_Variables::P_ext_data_pt->set_value(0,old_p+delta_p);
     }
   }
  // Close trace file.
  trace_file.close();
 }
References GlobalParameters::Doc_info, MergeRestartFiles::filename, Flags::Nsteps, Global_Physical_Variables::P_ext_data_pt, Global_Physical_Variables::Pmax, Global_Physical_Variables::Pmin, Global_Physical_Variables::Q, Global_Physical_Variables::Re, Flags::Resolution_factor, Flags::Run_identifier_string, Global_Physical_Variables::Yprescr, and Global_Physical_Variables::Yprescr_min.
unsteady_run()
template<class ELEMENT > void FSICollapsibleChannelProblem< ELEMENT >::unsteady_run (const double & dt = 0.1) virtual
Unsteady run. Specify timestep or use default of 0.1.
Unsteady run; virtual so it can be overloaded in derived problem classes. Specify timestep or use default of 0.1
Reimplemented in SegregatedFSICollapsibleChannelProblem< ELEMENT >.
 {
   // Set initial value for external pressure (on the wall stiffness scale).
   // Will be overwritten by restart data if a restart file (and pressure
   // jump) are specified
   Global_Physical_Variables::P_ext_data_pt->
    set_value(0,Global_Physical_Variables::Pmax);
   // Initialise timestep -- also sets the weights for all timesteppers
   // in the problem.
   initialise_dt(dt);
   std::cout << "Pressure before set initial: "
             << Global_Physical_Variables::P_ext_data_pt->value(0)
             << std::endl;
   // Apply initial condition
   set_initial_condition();
   std::cout << "Pressure after set initial: "
             << Global_Physical_Variables::P_ext_data_pt->value(0)
             << std::endl;
   //Set output directory
   Doc_info.set_directory("RESLT");
   // Open a trace file
   ofstream trace_file;
   char filename[100];
   sprintf(filename,"%s/trace.dat",Doc_info.directory().c_str());
   trace_file.open(filename);
  // Write trace file header
  trace_file << "VARIABLES=\"time\","
             << "\"y<sub>ctrl</sub>\",";
  trace_file << "\"u_1\","
             << "\"u_2\","
             << "\"CPU time for solve\","
             << "\"Number of Newton iterations\""
             << std::endl;
   trace_file << "ZONE T=\"";
   trace_file << "Re=" << Global_Physical_Variables::Re << ", ";
   trace_file << "Q=" << Global_Physical_Variables::Q << ", ";
   trace_file << "resolution factor: " << Flags::Resolution_factor << ". ";
   trace_file << Flags::Run_identifier_string << "\" ";
   trace_file << std::endl;
   // Output the initial solution (dummy for CPU time)
   doc_solution_unsteady(Doc_info,trace_file,0.0,0);
   // Increment step number
   Doc_info.number()++;
   // Timestepping loop
   //------------------
   for (unsigned istep=0;istep<Flags::Nsteps;istep++)
    {
     // Solve the problem
     //------------------
     clock_t t_start = clock();
     // Explit call to the unsteady Newton solve.
     unsteady_newton_solve(dt);
     clock_t t_end= clock();
     double cpu=double(t_end-t_start)/CLOCKS_PER_SEC;
     // Output the solution
     //--------------------
     doc_solution_unsteady(Doc_info,trace_file,cpu,0);
     // Step number
     Doc_info.number()++;
    }
   // Close trace file.
   trace_file.close();
 }
References GlobalParameters::Doc_info, MergeRestartFiles::filename, Flags::Nsteps, Global_Physical_Variables::P_ext_data_pt, Global_Physical_Variables::Pmax, Global_Physical_Variables::Q, Global_Physical_Variables::Re, Flags::Resolution_factor, and Flags::Run_identifier_string.
wall_mesh_pt() [1/7]
template<class ELEMENT > OneDLagrangianMesh<FSIHermiteBeamElement>* FSICollapsibleChannelProblem< ELEMENT >::wall_mesh_pt () inline
Access function for the wall mesh.
   {
    return Wall_mesh_pt;
   } // end of access to wall mesh
References FSICollapsibleChannelProblem< ELEMENT >::Wall_mesh_pt.
wall_mesh_pt() [2/7]
template<class ELEMENT > OneDLagrangianMesh<FSIHermiteBeamElement>* FSICollapsibleChannelProblem< ELEMENT >::wall_mesh_pt () inline
Access function for the wall mesh.
   {
    return Wall_mesh_pt;
   } // end of access to wall mesh
wall_mesh_pt() [3/7]
template<class ELEMENT > OneDLagrangianMesh<FSIHermiteBeamElement>* FSICollapsibleChannelProblem< ELEMENT >::wall_mesh_pt () inline
Access function for the wall mesh.
   {
    return Wall_mesh_pt;
   } // end of access to wall mesh
wall_mesh_pt() [4/7]
template<class ELEMENT > OneDLagrangianMesh<FSIHermiteBeamElement>* FSICollapsibleChannelProblem< ELEMENT >::wall_mesh_pt () inline
Access function for the wall mesh.
   {
    return Wall_mesh_pt;
   } // end of access to wall mesh
wall_mesh_pt() [5/7]
template<class ELEMENT > OneDLagrangianMesh<FSIHermiteBeamElement>* FSICollapsibleChannelProblem< ELEMENT >::wall_mesh_pt () inline
Access function for the wall mesh.
   {
    return Wall_mesh_pt;
   } // end of access to wall mesh
wall_mesh_pt() [6/7]
template<class ELEMENT > OneDLagrangianMesh<FSIHermiteBeamElement>* & FSICollapsibleChannelProblem< ELEMENT >::wall_mesh_pt () inline
Access function for the wall mesh.
   {
    return Wall_mesh_pt;
   } // end of access to wall mesh
wall_mesh_pt() [7/7]
template<class ELEMENT > OneDLagrangianMesh<FSIHermiteBeamElement>* FSICollapsibleChannelProblem< ELEMENT >::wall_mesh_pt () inline
Access function for the wall mesh.
   {
    return Wall_mesh_pt;
   } // end of access to wall mesh
Member Data Documentation
Applied_fluid_traction_mesh_pt
template<class ELEMENT > Mesh * FSICollapsibleChannelProblem< ELEMENT >::Applied_fluid_traction_mesh_pt private
Pointer to the "surface" mesh that applies the traction at the inflow
Bulk_mesh_pt [1/4]
template<class ELEMENT > AlgebraicCollapsibleChannelMesh< ELEMENT > * FSICollapsibleChannelProblem< ELEMENT >::Bulk_mesh_pt protected
Pointer to the "bulk" mesh.
Referenced by FSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_convergence_check(), and FSICollapsibleChannelProblem< ELEMENT >::bulk_mesh_pt().
Bulk_mesh_pt [2/4]
template<class ELEMENT > RefineableAlgebraicCollapsibleChannelMesh<ELEMENT>* FSICollapsibleChannelProblem< ELEMENT >::Bulk_mesh_pt private
Pointer to the "bulk" mesh.
Bulk_mesh_pt [3/4]
template<class ELEMENT > ElasticCollapsibleChannelMesh<ELEMENT>* FSICollapsibleChannelProblem< ELEMENT >::Bulk_mesh_pt private
Pointer to the "bulk" mesh.
Bulk_mesh_pt [4/4]
template<class ELEMENT > ElasticRefineableCollapsibleChannelMesh<ELEMENT>* FSICollapsibleChannelProblem< ELEMENT >::Bulk_mesh_pt private
Pointer to the "bulk" mesh.
Constitutive_law_pt
template<class ELEMENT > ConstitutiveLaw * FSICollapsibleChannelProblem< ELEMENT >::Constitutive_law_pt private
Constitutive law used to determine the mesh deformation.
Ctrl_geom_obj_pt
template<class ELEMENT > GeomObject* FSICollapsibleChannelProblem< ELEMENT >::Ctrl_geom_obj_pt protected
Pointer to GeomObject at which displacement control is applied (or at which wall displacement is monitored in unsteady runs)
Displ_control
template<class ELEMENT > bool FSICollapsibleChannelProblem< ELEMENT >::Displ_control protected
Use displacement control?
Displ_control_mesh_pt
template<class ELEMENT > Mesh* FSICollapsibleChannelProblem< ELEMENT >::Displ_control_mesh_pt protected
Pointer to the mesh that contains the displacement control element.
Displacement_control_mesh_pt
template<class ELEMENT > Mesh* FSICollapsibleChannelProblem< ELEMENT >::Displacement_control_mesh_pt private
Pointer to mesh containing the displacement control element (only!)
Doc_info
template<class ELEMENT > DocInfo FSICollapsibleChannelProblem< ELEMENT >::Doc_info protected
DocInfo object.
Fluid_jacobian_ignores_geometric_data
template<class ELEMENT > bool FSICollapsibleChannelProblem< ELEMENT >::Fluid_jacobian_ignores_geometric_data private
Flag controlling whether geometric data is ignored when the fluid elements calculate their Jacobian contribution
Lagrange_multiplier_mesh_pt
template<class ELEMENT > SolidMesh * FSICollapsibleChannelProblem< ELEMENT >::Lagrange_multiplier_mesh_pt private
Pointers to mesh of Lagrange multiplier elements.
Pointers to meshes of Lagrange multiplier elements.
Lcollapsible
template<class ELEMENT > double FSICollapsibleChannelProblem< ELEMENT >::Lcollapsible protected
x-length in the collapsible part of the channel
Referenced by SegregatedFSICollapsibleChannelProblem< ELEMENT >::SegregatedFSICollapsibleChannelProblem().
Ldown
template<class ELEMENT > double FSICollapsibleChannelProblem< ELEMENT >::Ldown protected
x-length in the downstream part of the channel
Left_node_pt
template<class ELEMENT > Node * FSICollapsibleChannelProblem< ELEMENT >::Left_node_pt protected
Pointer to the left control node.
Lup
template<class ELEMENT > double FSICollapsibleChannelProblem< ELEMENT >::Lup protected
x-length in the upstream part of the channel
Ly
template<class ELEMENT > double FSICollapsibleChannelProblem< ELEMENT >::Ly protected
Transverse length.
Ncollapsible
template<class ELEMENT > unsigned FSICollapsibleChannelProblem< ELEMENT >::Ncollapsible protected
Number of elements in the x direction in the collapsible part of the channel
Ndown
template<class ELEMENT > unsigned FSICollapsibleChannelProblem< ELEMENT >::Ndown protected
Number of elements in the x direction in the downstream part of the channel.
Newton_iter
template<class ELEMENT > unsigned FSICollapsibleChannelProblem< ELEMENT >::Newton_iter protected
Counter for Newton iterations.
Referenced by FSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_convergence_check(), and FSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_solve().
Nup
template<class ELEMENT > unsigned FSICollapsibleChannelProblem< ELEMENT >::Nup protected
Number of elements in the x direction in the upstream part of the channel.
Ny
template<class ELEMENT > unsigned FSICollapsibleChannelProblem< ELEMENT >::Ny protected
Number of elements across the channel.
Right_node_pt
template<class ELEMENT > Node * FSICollapsibleChannelProblem< ELEMENT >::Right_node_pt protected
Pointer to right control node.
S_displ_ctrl
template<class ELEMENT > Vector<double> FSICollapsibleChannelProblem< ELEMENT >::S_displ_ctrl protected
Vector of local coordinates of displacement control point in Ctrl_geom_obj_pt
Steady_flag
template<class ELEMENT > bool FSICollapsibleChannelProblem< ELEMENT >::Steady_flag protected
Flag for steady run.
Wall_geom_object_pt
template<class ELEMENT > MeshAsGeomObject * FSICollapsibleChannelProblem< ELEMENT >::Wall_geom_object_pt protected
Geometric object incarnation of the wall mesh.
Pointer to geometric object (one Lagrangian, two Eulerian coordinates) that will be built from the wall mesh
Referenced by SegregatedFSICollapsibleChannelProblem< ELEMENT >::SegregatedFSICollapsibleChannelProblem().
Wall_jacobian_ignores_fluid_shear_stress_data
template<class ELEMENT > bool FSICollapsibleChannelProblem< ELEMENT >::Wall_jacobian_ignores_fluid_shear_stress_data private
Flag controlling whether fluid shear stress is ignored when wall elements calculate their Jacobian contribition
Wall_jacobian_ignores_geometric_data
template<class ELEMENT > bool FSICollapsibleChannelProblem< ELEMENT >::Wall_jacobian_ignores_geometric_data private
Flag controlling whether geometric data is ignored when the wall elements calculate their Jacobian contribution
Wall_mesh_pt
template<class ELEMENT > OneDLagrangianMesh< FSIHermiteBeamElement > * FSICollapsibleChannelProblem< ELEMENT >::Wall_mesh_pt protected
Pointer to the "wall" mesh.
Referenced by FSICollapsibleChannelProblem< ELEMENT >::wall_mesh_pt().
Wall_node_pt
template<class ELEMENT > Node * FSICollapsibleChannelProblem< ELEMENT >::Wall_node_pt protected
Pointer to control node on the wall.
The documentation for this class was generated from the following files:
fsi_chan_problem.h
fsi_collapsible_channel.cc
interaction/fsi_collapsible_channel/fsi_collapsible_channel_adapt.cc
fsi_pseudo_solid_collapsible_channel.cc
fsi_pseudo_solid_collapsible_channel_adapt.cc
fsi_jacobian_approximation.cc