MercuryDPM: oomph::TElement2FaceToBulkCoordinates Namespace Reference
oomph::TElement2FaceToBulkCoordinates Namespace Reference
Functions
void face0 (const Vector< double > &s, Vector< double > &s_bulk)
The translation scheme for the face s0 = 0.
void face1 (const Vector< double > &s, Vector< double > &s_bulk)
The translation scheme for the face s1 = 0.
void face2 (const Vector< double > &s, Vector< double > &s_bulk)
The translation scheme for the face s2 = 0.
Detailed Description
Namespace for the functions that translate local face coordinates to the coordinates in the bulk element
Function Documentation
face0()
void oomph::TElement2FaceToBulkCoordinates::face0 (const Vector< double > & s, Vector< double > & s_bulk)
The translation scheme for the face s0 = 0.
     {
       s_bulk[0] = 0.0;
       s_bulk[1] = s[0];
     }
References s.
Referenced by oomph::TElement< 2, NNODE_1D >::build_face_element().
face1()
void oomph::TElement2FaceToBulkCoordinates::face1 (const Vector< double > & s, Vector< double > & s_bulk)
The translation scheme for the face s1 = 0.
     {
       s_bulk[0] = s[0];
       s_bulk[1] = 0.0;
     }
References s.
Referenced by oomph::TElement< 2, NNODE_1D >::build_face_element().
face2()
void oomph::TElement2FaceToBulkCoordinates::face2 (const Vector< double > & s, Vector< double > & s_bulk)
The translation scheme for the face s2 = 0.
     {
       s_bulk[0] = 1.0 - s[0];
       s_bulk[1] = s[0];
     }
References s.
Referenced by oomph::TElement< 2, NNODE_1D >::build_face_element().