MercuryDPM: TreeTest< Dim > Struct Template Reference
TreeTest< Dim > Struct Template Reference
Public Types
typedef Matrix< double, Dim, 1 > VectorType
typedef std::vector< VectorType, aligned_allocator< VectorType > > VectorTypeList
typedef Ball< Dim > BallType
typedef std::vector< BallType, aligned_allocator< BallType > > BallTypeList
typedef AlignedBox< double, Dim > BoxType
Public Member Functions
void testIntersect1 ()
void testMinimize1 ()
void testIntersect2 ()
void testMinimize2 ()
Member Typedef Documentation
BallType
template<int Dim> typedef Ball<Dim> TreeTest< Dim >::BallType
BallTypeList
template<int Dim> typedef std::vector<BallType, aligned_allocator<BallType> > TreeTest< Dim >::BallTypeList
BoxType
template<int Dim> typedef AlignedBox<double, Dim> TreeTest< Dim >::BoxType
VectorType
template<int Dim> typedef Matrix<double, Dim, 1> TreeTest< Dim >::VectorType
VectorTypeList
template<int Dim> typedef std::vector<VectorType, aligned_allocator<VectorType> > TreeTest< Dim >::VectorTypeList
Member Function Documentation
testIntersect1()
template<int Dim> void TreeTest< Dim >::testIntersect1 () inline
{
     BallTypeList b;
     for (int i = 0; i < 500; ++i) {
       b.push_back(BallType(VectorType::Random(), 0.5 * internal::random(0., 1.)));
     }
     KdBVH<double, Dim, BallType> tree(b.begin(), b.end());
     VectorType pt = VectorType::Random();
     BallPointStuff<Dim> i1(pt), i2(pt);
     for (int i = 0; i < (int)b.size(); ++i) i1.intersectObject(b[i]);
     BVIntersect(tree, i2);
     VERIFY(i1.count == i2.count);
   }
References b, Eigen::BVIntersect(), BallPointStuff< Dim >::count, i, int(), and VERIFY.
Referenced by EIGEN_DECLARE_TEST().
testIntersect2()
template<int Dim> void TreeTest< Dim >::testIntersect2 () inline
{
     BallTypeList b;
     VectorTypeList v;
     for (int i = 0; i < 50; ++i) {
       b.push_back(BallType(VectorType::Random(), 0.5 * internal::random(0., 1.)));
       for (int j = 0; j < 3; ++j) v.push_back(VectorType::Random());
     }
     KdBVH<double, Dim, BallType> tree(b.begin(), b.end());
     KdBVH<double, Dim, VectorType> vTree(v.begin(), v.end());
     BallPointStuff<Dim> i1, i2;
     for (int i = 0; i < (int)b.size(); ++i)
       for (int j = 0; j < (int)v.size(); ++j) i1.intersectObjectObject(b[i], v[j]);
     BVIntersect(tree, vTree, i2);
     VERIFY(i1.count == i2.count);
   }
References b, Eigen::BVIntersect(), BallPointStuff< Dim >::count, i, int(), BallPointStuff< Dim >::intersectObjectObject(), j, v, and VERIFY.
Referenced by EIGEN_DECLARE_TEST().
testMinimize1()
template<int Dim> void TreeTest< Dim >::testMinimize1 () inline
{
     BallTypeList b;
     for (int i = 0; i < 500; ++i) {
       b.push_back(BallType(VectorType::Random(), 0.01 * internal::random(0., 1.)));
     }
     KdBVH<double, Dim, BallType> tree(b.begin(), b.end());
     VectorType pt = VectorType::Random();
     BallPointStuff<Dim> i1(pt), i2(pt);
     double m1 = (std::numeric_limits<double>::max)(), m2 = m1;
     for (int i = 0; i < (int)b.size(); ++i) m1 = (std::min)(m1, i1.minimumOnObject(b[i]));
     m2 = BVMinimize(tree, i2);
     VERIFY_IS_APPROX(m1, m2);
   }
References b, Eigen::BVMinimize(), i, int(), m1, m2(), max, min, and VERIFY_IS_APPROX.
Referenced by EIGEN_DECLARE_TEST().
testMinimize2()
template<int Dim> void TreeTest< Dim >::testMinimize2 () inline
{
     BallTypeList b;
     VectorTypeList v;
     for (int i = 0; i < 50; ++i) {
       b.push_back(BallType(VectorType::Random(), 1e-7 + 1e-6 * internal::random(0., 1.)));
       for (int j = 0; j < 3; ++j) v.push_back(VectorType::Random());
     }
     KdBVH<double, Dim, BallType> tree(b.begin(), b.end());
     KdBVH<double, Dim, VectorType> vTree(v.begin(), v.end());
     BallPointStuff<Dim> i1, i2;
     double m1 = (std::numeric_limits<double>::max)(), m2 = m1;
     for (int i = 0; i < (int)b.size(); ++i)
       for (int j = 0; j < (int)v.size(); ++j) m1 = (std::min)(m1, i1.minimumOnObjectObject(b[i], v[j]));
     m2 = BVMinimize(tree, vTree, i2);
     VERIFY_IS_APPROX(m1, m2);
   }
References b, Eigen::BVMinimize(), e(), i, int(), j, m1, m2(), max, min, BallPointStuff< Dim >::minimumOnObjectObject(), v, and VERIFY_IS_APPROX.
Referenced by EIGEN_DECLARE_TEST().
The documentation for this struct was generated from the following file:
BVH.cpp