MercuryDPM: Eigen::internal::InnerMostDimReducer< Self, Op, true, true > Struct Template Reference
Eigen::internal::InnerMostDimReducer< Self, Op, true, true > Struct Template Reference
#include <TensorReduction.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Self::CoeffReturnType reduce (const Self &self, typename Self::Index firstIndex, typename Self::Index numValuesToReduce, Op &reducer)
Member Function Documentation
reduce()
template<typename Self , typename Op > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Self::CoeffReturnType Eigen::internal::InnerMostDimReducer< Self, Op, true, true >::reduce (const Self & self, typename Self::Index firstIndex, typename Self::Index numValuesToReduce, Op & reducer) inline static
{
     const Index kLeafSize = LeafSize<typename Self::CoeffReturnType>();
     const typename Self::Index packetSize = internal::unpacket_traits<typename Self::PacketReturnType>::size;
     typename Self::CoeffReturnType accum = reducer.initialize();
     if (numValuesToReduce > packetSize * kLeafSize) {
       // Make sure the split point is aligned on a packet boundary.
       const typename Self::Index split =
           packetSize *
           numext::div_ceil(firstIndex + numext::div_ceil(numValuesToReduce, typename Self::Index(2)), packetSize);
       const typename Self::Index num_left = numext::mini(split - firstIndex, numValuesToReduce);
       reducer.reduce(reduce(self, firstIndex, num_left, reducer), &accum);
       if (num_left < numValuesToReduce) {
         reducer.reduce(reduce(self, split, numValuesToReduce - num_left, reducer), &accum);
       }
       return reducer.finalize(accum);
     } else {
       return InnerMostDimReducer<Self, Op, true, false>::reduce(self, firstIndex, numValuesToReduce, reducer);
     }
   }
References Eigen::numext::div_ceil(), Eigen::numext::mini(), Eigen::internal::InnerMostDimReducer< Self, Op, Vectorizable, UseTreeReduction >::reduce(), and oomph::DoubleVectorHelpers::split().
The documentation for this struct was generated from the following file:
TensorReduction.h