MercuryDPM: oomph::Preconditioner Class Reference
oomph::Preconditioner Class Reference abstract
#include <preconditioner.h>
Public Member Functions
Preconditioner ()
Constructor.
Preconditioner (const Preconditioner &)=delete
Broken copy constructor.
void operator= (const Preconditioner &)=delete
Broken assignment operator.
virtual ~Preconditioner ()
Destructor (empty)
virtual void preconditioner_solve (const DoubleVector &r, DoubleVector &z)=0
virtual void preconditioner_solve_transpose (const DoubleVector &r, DoubleVector &z)
void setup (DoubleMatrixBase *matrix_pt)
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
void enable_silent_preconditioner_setup ()
Set up the block preconditioner quietly!
void disable_silent_preconditioner_setup ()
Be verbose in the block preconditioner setup.
virtual void setup ()=0
virtual void clean_up_memory ()
Clean up memory (empty). Generic interface function.
virtual DoubleMatrixBase * matrix_pt () const
Get function for matrix pointer.
virtual void set_matrix_pt (DoubleMatrixBase *matrix_pt)
Set the matrix pointer.
virtual const OomphCommunicator * comm_pt () const
Get function for comm pointer.
virtual void set_comm_pt (const OomphCommunicator *const comm_pt)
Set the communicator pointer.
double setup_time () const
Returns the time to setup the preconditioner.
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> &doftype_coarsen_map_coarse)
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
void build_distribution (const LinearAlgebraDistribution &dist)
Protected Attributes
bool Silent_preconditioner_setup
Boolean to indicate whether or not the build should be done silently.
std::ostream * Stream_pt
Pointer to the output stream – defaults to std::cout.
Private Attributes
DoubleMatrixBase * Matrix_pt
Storage for a pointer to the matrix.
const OomphCommunicator * Comm_pt
double Setup_time
The time it takes to set up this preconditioner.
Additional Inherited Members
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
Detailed Description
Preconditioner base class. Gives an interface to call all other preconditioners through and stores the matrix and communicator pointers. All preconditioners should be derived from this class.
Constructor & Destructor Documentation
Preconditioner() [1/2]
oomph::Preconditioner::Preconditioner () inline
Constructor.
       : Silent_preconditioner_setup(false),
         Stream_pt(0),
         Matrix_pt(0),
         Comm_pt(0),
         Setup_time(0){};
Preconditioner() [2/2]
oomph::Preconditioner::Preconditioner (const Preconditioner &) delete
Broken copy constructor.
~Preconditioner()
virtual oomph::Preconditioner::~Preconditioner () inline virtual
Destructor (empty)
 {}
Member Function Documentation
clean_up_memory()
virtual void oomph::Preconditioner::clean_up_memory () inline virtual
Clean up memory (empty). Generic interface function.
Reimplemented in oomph::GMRESBlockPreconditioner, oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner, oomph::GMRESBlockPreconditioner, oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner, oomph::BandedBlockTriangularPreconditioner< MATRIX >, oomph::ExactDGPBlockPreconditioner< MATRIX >, oomph::PressureBasedSolidLSCPreconditioner, oomph::HelmholtzMGPreconditioner< DIM >, oomph::HelmholtzGMRESMG< MATRIX >, oomph::NavierStokesSchurComplementPreconditioner, oomph::LagrangeEnforcedFlowPreconditioner, oomph::PseudoElasticPreconditionerSubsidiaryBlockPreconditionerOld, oomph::PseudoElasticPreconditionerSubsidiaryPreconditionerOld, oomph::PseudoElasticPreconditionerOld, oomph::PseudoElasticPreconditioner, oomph::PseudoElasticFSIPreconditioner, oomph::TrilinosPreconditionerBase, oomph::SuperLUPreconditioner, oomph::NewMumpsPreconditioner, oomph::HyprePreconditioner, oomph::MGPreconditioner< DIM >, oomph::InnerIterationPreconditioner< SOLVER, PRECONDITIONER >, oomph::MatrixBasedLumpedPreconditioner< MATRIX >, oomph::MatrixBasedLumpedPreconditioner< oomph::CRDoubleMatrix >, oomph::BlockTriangularPreconditioner< MATRIX >, oomph::BlockDiagonalPreconditioner< MATRIX >, oomph::GeneralPurposeBlockPreconditioner< MATRIX >, oomph::InexactSubBiharmonicPreconditioner, oomph::ExactSubBiharmonicPreconditioner, oomph::BiharmonicPreconditioner, BoussinesqPreconditioner, and SimpleLSCPreconditioner.
 {}
Referenced by oomph::TrilinosAztecOOSolver::clean_up_memory(), and oomph::PseudoElasticFSIPreconditioner::clean_up_memory().
comm_pt()
virtual const OomphCommunicator* oomph::Preconditioner::comm_pt () const inline virtual
Get function for comm pointer.
     {
       // If we are using MPI then the comm pointer should not be null.
 #ifdef OOMPH_HAS_MPI
 #ifdef PARANOID
       if (Comm_pt == 0)
       {
         std::ostringstream error_msg;
         error_msg << "Tried to access a null communicator pointer. This might "
                      "mean you are\n"
                   << "trying to use it in a non-parallel case. Or it might "
                      "mean you haven't\n"
                   << "set it properly.";
         throw OomphLibError(
           error_msg.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
 #endif
       return Comm_pt;
     }
References Comm_pt, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::NavierStokesSchurComplementPreconditioner::assemble_inv_press_and_veloc_mass_matrix_diagonal(), oomph::PressureBasedSolidLSCPreconditioner::assemble_mass_matrix_diagonal(), oomph::NavierStokesSchurComplementPreconditioner::get_pressure_advection_diffusion_matrix(), oomph::BlockPreconditioner< MATRIX >::internal_dof_number(), set_comm_pt(), oomph::ILUZeroPreconditioner< CCDoubleMatrix >::setup(), oomph::InnerIterationPreconditioner< SOLVER, PRECONDITIONER >::setup(), oomph::IdentityPreconditioner::setup(), and oomph::PseudoElasticPreconditionerOld::setup().
disable_silent_preconditioner_setup()
void oomph::Preconditioner::disable_silent_preconditioner_setup () inline
Be verbose in the block preconditioner setup.
     {
       // Set the appropriate (silencing) boolean to false
       Silent_preconditioner_setup = false;
     } // End of disable_silent_preconditioner_setup
References Silent_preconditioner_setup.
enable_silent_preconditioner_setup()
void oomph::Preconditioner::enable_silent_preconditioner_setup () inline
Set up the block preconditioner quietly!
     {
       // Set the appropriate (silencing) boolean to true
       Silent_preconditioner_setup = true;
     } // End of enable_silent_preconditioner_setup
References Silent_preconditioner_setup.
Referenced by NavierStokesProblem< ELEMENT >::set_up_spacetime_solver(), and UnsteadyHeatProblem< ELEMENT >::set_up_spacetime_solver().
matrix_pt()
virtual DoubleMatrixBase* oomph::Preconditioner::matrix_pt () const inline virtual
Get function for matrix pointer.
Reimplemented in oomph::BlockPreconditioner< MATRIX >, and oomph::BlockPreconditioner< CRDoubleMatrix >.
     {
 #ifdef PARANOID
       if (Matrix_pt == 0)
       {
         std::ostringstream error_msg;
         error_msg << "Matrix pointer is null.";
         throw OomphLibError(
           error_msg.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return Matrix_pt;
     }
References Matrix_pt, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::BlockPreconditioner< MATRIX >::matrix_pt(), set_matrix_pt(), oomph::MatrixBasedDiagPreconditioner::setup(), oomph::ILUZeroPreconditioner< CCDoubleMatrix >::setup(), oomph::ILUZeroPreconditioner< CRDoubleMatrix >::setup(), oomph::InnerIterationPreconditioner< SOLVER, PRECONDITIONER >::setup(), oomph::HyprePreconditioner::setup(), oomph::NewMumpsPreconditioner::setup(), oomph::IdentityPreconditioner::setup(), oomph::SuperLUPreconditioner::setup(), oomph::TrilinosPreconditionerBase::setup(), and setup().
operator=()
void oomph::Preconditioner::operator= (const Preconditioner &) delete
Broken assignment operator.
preconditioner_solve()
virtual void oomph::Preconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) pure virtual
Apply the preconditioner. Pure virtual generic interface function. This method should apply the preconditioner operator to the vector r and return the vector z.
Implemented in oomph::MGPreconditioner< DIM >, oomph::PseudoElasticPreconditionerSubsidiaryBlockPreconditionerOld, oomph::GMRESBlockPreconditioner, oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner, oomph::GMRESBlockPreconditioner, oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner, oomph::BandedBlockTriangularPreconditioner< MATRIX >, oomph::ExactDGPBlockPreconditioner< MATRIX >, oomph::PressureBasedSolidLSCPreconditioner, oomph::HelmholtzMGPreconditioner< DIM >, oomph::HelmholtzGMRESMG< MATRIX >, oomph::NavierStokesSchurComplementPreconditioner, oomph::LagrangeEnforcedFlowPreconditioner, oomph::PseudoElasticPreconditionerScalingHelperOld, oomph::PseudoElasticPreconditionerSubsidiaryPreconditionerOld, oomph::PseudoElasticPreconditionerOld, oomph::PseudoElasticPreconditioner, oomph::PseudoElasticFSIPreconditioner, oomph::SimpleFSIPreconditioner< MATRIX >, oomph::FSIPreconditioner, oomph::TrilinosPreconditionerBase, oomph::SuperLUPreconditioner, oomph::IdentityPreconditioner, oomph::NewMumpsPreconditioner, oomph::HyprePreconditioner, oomph::InnerIterationPreconditioner< SOLVER, PRECONDITIONER >, oomph::ILUZeroPreconditioner< CRDoubleMatrix >, oomph::ILUZeroPreconditioner< CCDoubleMatrix >, oomph::MatrixBasedLumpedPreconditioner< MATRIX >, oomph::MatrixBasedLumpedPreconditioner< oomph::CRDoubleMatrix >, oomph::MatrixBasedDiagPreconditioner, oomph::DummyBlockPreconditioner< MATRIX >, oomph::ExactBlockPreconditioner< MATRIX >, oomph::BlockTriangularPreconditioner< MATRIX >, oomph::BlockDiagonalPreconditioner< MATRIX >, oomph::InexactSubBiharmonicPreconditioner, oomph::ExactSubBiharmonicPreconditioner, oomph::BiharmonicPreconditioner, BoussinesqPreconditioner, SimpleFSIPreconditioner< MATRIX >, oomph::SimpleBlockDiagonalPreconditioner< MATRIX >, oomph::SimpleBlockDiagonalPreconditioner< CRDoubleMatrix >, oomph::OnePlusFourWithTwoCoarse< MATRIX >, oomph::CoarseTwoPlusTwoPlusOne< MATRIX >, oomph::TwoPlusThreeUpperTriangularWithReplace< MATRIX >, oomph::TwoPlusThreeUpperTriangularWithTwoLevelSubsidiary< MATRIX >, oomph::TwoPlusOneUpperTriangularPreconditioner< MATRIX >, oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >, oomph::TwoPlusThreeUpperTriangular< MATRIX >, oomph::TwoPlusThree< MATRIX >, oomph::UpperTriangular< MATRIX >, oomph::CoarseTwoIntoOne< MATRIX >, oomph::SimpleOneDofOnly< MATRIX >, oomph::SimpleTwoDofOnly< MATRIX >, oomph::Diagonal< MATRIX >, and SimpleLSCPreconditioner.
Referenced by oomph::AugmentedProblemGMRES::apply_schur_complement_preconditioner(), oomph::OomphLibPreconditionerEpetraOperator::ApplyInverse(), oomph::PseudoElasticPreconditioner::elastic_preconditioner_solve(), oomph::PseudoElasticPreconditionerOld::elastic_preconditioner_solve(), oomph::BiharmonicPreconditioner::preconditioner_solve(), oomph::ExactSubBiharmonicPreconditioner::preconditioner_solve(), oomph::InexactSubBiharmonicPreconditioner::preconditioner_solve(), oomph::FSIPreconditioner::preconditioner_solve(), oomph::PseudoElasticFSIPreconditioner::preconditioner_solve(), oomph::PseudoElasticPreconditionerSubsidiaryPreconditionerOld::preconditioner_solve(), oomph::LagrangeEnforcedFlowPreconditioner::preconditioner_solve(), oomph::PressureBasedSolidLSCPreconditioner::preconditioner_solve(), oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::preconditioner_solve(), oomph::AugmentedProblemGMRES::solve_helper(), oomph::GMRES< MATRIX >::update(), and oomph::HelmholtzGMRESMG< MATRIX >::update().
preconditioner_solve_transpose()
virtual void oomph::Preconditioner::preconditioner_solve_transpose (const DoubleVector & r, DoubleVector & z) inline virtual
Apply the preconditioner. Pure virtual generic interface function. This method should apply the preconditioner operator to the vector r and return the vector z. (broken virtual)
Reimplemented in oomph::SuperLUPreconditioner, and oomph::IdentityPreconditioner.
     {
       // Throw an error
       throw OomphLibError("This function hasn't been implemented yet!",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
set_comm_pt()
virtual void oomph::Preconditioner::set_comm_pt (const OomphCommunicator *const comm_pt) inline virtual
Set the communicator pointer.
     {
       Comm_pt = comm_pt;
     }
References comm_pt(), and Comm_pt.
Referenced by oomph::PseudoElasticPreconditionerScalingHelperOld::PseudoElasticPreconditionerScalingHelperOld(), setup(), oomph::HelmholtzGMRESMG< MATRIX >::solve(), and oomph::HelmholtzFGMRESMG< MATRIX >::solve().
set_matrix_pt()
virtual void oomph::Preconditioner::set_matrix_pt (DoubleMatrixBase * matrix_pt) inline virtual
Set the matrix pointer.
     {
       Matrix_pt = matrix_pt;
     }
References matrix_pt(), and Matrix_pt.
Referenced by oomph::PseudoElasticPreconditionerScalingHelperOld::PseudoElasticPreconditionerScalingHelperOld(), oomph::BlockPreconditioner< MATRIX >::set_master_matrix_pt(), setup(), oomph::HelmholtzGMRESMG< MATRIX >::solve(), oomph::HelmholtzFGMRESMG< MATRIX >::solve(), and oomph::TrilinosAztecOOSolver::solver_setup().
setup() [1/3]
virtual void oomph::Preconditioner::setup () pure virtual
Setup the preconditioner. Pure virtual generic interface function.
Implemented in oomph::GMRESBlockPreconditioner, oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner, oomph::GMRESBlockPreconditioner, oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner, oomph::HelmholtzMGPreconditioner< DIM >, oomph::NavierStokesSchurComplementPreconditioner, oomph::MatrixBasedLumpedPreconditioner< MATRIX >, oomph::MatrixBasedLumpedPreconditioner< oomph::CRDoubleMatrix >, oomph::TwoPlusThreeUpperTriangularWithTwoLevelSubsidiary< MATRIX >, oomph::TwoPlusOneUpperTriangularPreconditioner< MATRIX >, oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >, oomph::TwoPlusThreeUpperTriangular< MATRIX >, oomph::UpperTriangular< MATRIX >, oomph::CoarseTwoIntoOne< MATRIX >, oomph::SimpleOneDofOnly< MATRIX >, oomph::SimpleTwoDofOnly< MATRIX >, oomph::Diagonal< MATRIX >, oomph::GMRESBlockPreconditioner, oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner, oomph::GMRESBlockPreconditioner, oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner, oomph::HelmholtzMGPreconditioner< DIM >, oomph::NavierStokesSchurComplementPreconditioner, oomph::MatrixBasedLumpedPreconditioner< MATRIX >, oomph::MatrixBasedLumpedPreconditioner< oomph::CRDoubleMatrix >, oomph::TwoPlusThreeUpperTriangularWithTwoLevelSubsidiary< MATRIX >, oomph::TwoPlusOneUpperTriangularPreconditioner< MATRIX >, oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >, oomph::TwoPlusThreeUpperTriangular< MATRIX >, oomph::UpperTriangular< MATRIX >, oomph::CoarseTwoIntoOne< MATRIX >, oomph::SimpleOneDofOnly< MATRIX >, oomph::SimpleTwoDofOnly< MATRIX >, oomph::Diagonal< MATRIX >, oomph::GMRESBlockPreconditioner, oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner, oomph::GMRESBlockPreconditioner, oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner, oomph::HelmholtzMGPreconditioner< DIM >, oomph::NavierStokesSchurComplementPreconditioner, oomph::MatrixBasedLumpedPreconditioner< MATRIX >, oomph::MatrixBasedLumpedPreconditioner< oomph::CRDoubleMatrix >, oomph::TwoPlusThreeUpperTriangularWithTwoLevelSubsidiary< MATRIX >, oomph::TwoPlusOneUpperTriangularPreconditioner< MATRIX >, oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >, oomph::TwoPlusThreeUpperTriangular< MATRIX >, oomph::UpperTriangular< MATRIX >, oomph::CoarseTwoIntoOne< MATRIX >, oomph::SimpleOneDofOnly< MATRIX >, oomph::SimpleTwoDofOnly< MATRIX >, oomph::Diagonal< MATRIX >, oomph::GMRESBlockPreconditioner, oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner, oomph::GMRESBlockPreconditioner, oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner, oomph::BandedBlockTriangularPreconditioner< MATRIX >, oomph::ExactDGPBlockPreconditioner< MATRIX >, oomph::PressureBasedSolidExactPreconditioner< MATRIX >, oomph::PressureBasedSolidLSCPreconditioner, oomph::HelmholtzMGPreconditioner< DIM >, oomph::HelmholtzGMRESMG< MATRIX >, oomph::NavierStokesExactPreconditioner< MATRIX >, oomph::NavierStokesSchurComplementPreconditioner, oomph::LagrangeEnforcedFlowPreconditioner, oomph::PseudoElasticPreconditionerScalingHelperOld, oomph::PseudoElasticPreconditionerSubsidiaryBlockPreconditionerOld, oomph::PseudoElasticPreconditionerSubsidiaryPreconditionerOld, oomph::PseudoElasticPreconditionerOld, oomph::PseudoElasticPreconditioner, oomph::PseudoElasticFSIPreconditioner, oomph::SimpleFSIPreconditioner< MATRIX >, oomph::FSIPreconditioner, oomph::TrilinosPreconditionerBase, oomph::SuperLUPreconditioner, oomph::IdentityPreconditioner, oomph::NewMumpsPreconditioner, oomph::HyprePreconditioner, oomph::MGPreconditioner< DIM >, oomph::InnerIterationPreconditioner< SOLVER, PRECONDITIONER >, oomph::ILUZeroPreconditioner< CRDoubleMatrix >, oomph::ILUZeroPreconditioner< CCDoubleMatrix >, oomph::MatrixBasedLumpedPreconditioner< MATRIX >, oomph::MatrixBasedLumpedPreconditioner< oomph::CRDoubleMatrix >, oomph::MatrixBasedDiagPreconditioner, oomph::MatrixBasedLumpedPreconditioner< MATRIX >, oomph::MatrixBasedLumpedPreconditioner< oomph::CRDoubleMatrix >, oomph::MatrixBasedLumpedPreconditioner< MATRIX >, oomph::MatrixBasedLumpedPreconditioner< oomph::CRDoubleMatrix >, oomph::DummyBlockPreconditioner< MATRIX >, oomph::ExactBlockPreconditioner< MATRIX >, oomph::BlockTriangularPreconditioner< MATRIX >, oomph::BlockDiagonalPreconditioner< MATRIX >, oomph::InexactSubBiharmonicPreconditioner, oomph::ExactSubBiharmonicPreconditioner, oomph::BiharmonicPreconditioner, BoussinesqPreconditioner, SimpleFSIPreconditioner< MATRIX >, oomph::SimpleBlockDiagonalPreconditioner< MATRIX >, oomph::SimpleBlockDiagonalPreconditioner< CRDoubleMatrix >, oomph::OnePlusFourWithTwoCoarse< MATRIX >, oomph::CoarseTwoPlusTwoPlusOne< MATRIX >, oomph::TwoPlusThreeUpperTriangularWithReplace< MATRIX >, oomph::TwoPlusThreeUpperTriangularWithTwoLevelSubsidiary< MATRIX >, oomph::TwoPlusOneUpperTriangularPreconditioner< MATRIX >, oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >, oomph::TwoPlusThreeUpperTriangular< MATRIX >, oomph::TwoPlusThree< MATRIX >, oomph::UpperTriangular< MATRIX >, oomph::CoarseTwoIntoOne< MATRIX >, oomph::SimpleOneDofOnly< MATRIX >, oomph::SimpleTwoDofOnly< MATRIX >, oomph::Diagonal< MATRIX >, and SimpleLSCPreconditioner.
Referenced by setup().
setup() [2/3]
void oomph::Preconditioner::setup (const Problem * problem_pt, DoubleMatrixBase * matrix_pt) inline
Compatability layer for old preconditioners where problem pointers were needed. The problem pointer is only used to get a communicator pointer.
     {
       ObsoleteCode::obsolete();
       setup(matrix_pt);
     }
References matrix_pt(), oomph::ObsoleteCode::obsolete(), and setup().
setup() [3/3]
void oomph::Preconditioner::setup (DoubleMatrixBase * matrix_pt) inline
Setup the preconditioner: store the matrix pointer and the communicator pointer then call preconditioner specific setup() function.
     {
       // Store matrix pointer
       set_matrix_pt(matrix_pt);
       // Extract and store communicator pointer
       DistributableLinearAlgebraObject* dist_obj_pt =
         dynamic_cast<DistributableLinearAlgebraObject*>(matrix_pt);
       if (dist_obj_pt != 0)
       {
         set_comm_pt(dist_obj_pt->distribution_pt()->communicator_pt());
       }
       else
       {
         set_comm_pt(0);
       }
       double setup_time_start = TimingHelpers::timer();
       setup();
       double setup_time_finish = TimingHelpers::timer();
       Setup_time = setup_time_finish - setup_time_start;
     }
References oomph::LinearAlgebraDistribution::communicator_pt(), oomph::DistributableLinearAlgebraObject::distribution_pt(), matrix_pt(), set_comm_pt(), set_matrix_pt(), setup(), Setup_time, and oomph::TimingHelpers::timer().
Referenced by oomph::BiharmonicPreconditioner::setup(), oomph::ExactSubBiharmonicPreconditioner::setup(), oomph::InexactSubBiharmonicPreconditioner::setup(), oomph::FSIPreconditioner::setup(), oomph::PseudoElasticFSIPreconditioner::setup(), oomph::PseudoElasticPreconditionerSubsidiaryPreconditionerOld::setup(), oomph::LagrangeEnforcedFlowPreconditioner::setup(), oomph::PressureBasedSolidLSCPreconditioner::setup(), oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::setup(), oomph::AugmentedProblemGMRES::solve_helper(), and oomph::TrilinosAztecOOSolver::solver_setup().
setup_time()
double oomph::Preconditioner::setup_time () const inline
Returns the time to setup the preconditioner.
     {
       return Setup_time;
     }
References Setup_time.
Referenced by oomph::FSIPreconditioner::setup().
turn_into_subsidiary_block_preconditioner() [1/2]
virtual void oomph::Preconditioner::turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > * master_block_prec_pt, const Vector< unsigned > & doftype_in_master_preconditioner_coarse) inline virtual
Virtual interface function for making a preconditioner a subsidiary of a block preconditioner. By default nothing is needed, but if this preconditioner is also a block preconditioner then things need to happen. There's an assumption here that the block preconditioner will be in CR form but since that assumption is hard coded all over BlockPreconditioner we're safe.
     {
     }
turn_into_subsidiary_block_preconditioner() [2/2]
virtual void oomph::Preconditioner::turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > * master_block_prec_pt, const Vector< unsigned > & doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> & doftype_coarsen_map_coarse) inline virtual
Virtual interface function for making a preconditioner a subsidiary of a block preconditioner. By default nothing is needed, but if this preconditioner is also a block preconditioner then things need to happen. Version for coarsening dof-types.
     {
     }
Member Data Documentation
Comm_pt
const OomphCommunicator* oomph::Preconditioner::Comm_pt private
Storage for a pointer to the communicator. Null if the preconditioner should not be distributed.
Referenced by comm_pt(), and set_comm_pt().
Matrix_pt
DoubleMatrixBase* oomph::Preconditioner::Matrix_pt private
Storage for a pointer to the matrix.
Referenced by matrix_pt(), and set_matrix_pt().
Setup_time
double oomph::Preconditioner::Setup_time private
The time it takes to set up this preconditioner.
Referenced by setup(), and setup_time().
Silent_preconditioner_setup
bool oomph::Preconditioner::Silent_preconditioner_setup protected
Boolean to indicate whether or not the build should be done silently.
Referenced by disable_silent_preconditioner_setup(), enable_silent_preconditioner_setup(), oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::setup(), and oomph::GMRESBlockPreconditioner::setup().
Stream_pt
std::ostream* oomph::Preconditioner::Stream_pt protected
Pointer to the output stream – defaults to std::cout.
Referenced by oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::setup(), and oomph::GMRESBlockPreconditioner::setup().
The documentation for this class was generated from the following file:
preconditioner.h