MercuryDPM: fish_poisson_adapt.cc File Reference
fish_poisson_adapt.cc File Reference
#include "generic.h"
#include "poisson.h"
#include "meshes/fish_mesh.h"
Classes
class RefineableFishPoissonProblem< ELEMENT >
Namespaces
ConstSourceForPoisson
Namespace for const source term in Poisson equation.
Functions
void ConstSourceForPoisson::get_source (const Vector< double > &x, double &source)
Const source function.
void solve_with_incremental_adaptation ()
int main ()
Function Documentation
main()
int main ()
Demonstrate how to solve 2D Poisson problem in fish-shaped domain with mesh adaptation.
 {
  // Solve with adaptation, docing the intermediate steps
  solve_with_incremental_adaptation();
 } // end of main
References solve_with_incremental_adaptation().
solve_with_incremental_adaptation()
void solve_with_incremental_adaptation ()
Demonstrate how to solve 2D Poisson problem in fish-shaped domain with mesh adaptation. First we solve on the original coarse mesh. Next we do a few uniform refinement steps and resolve. Finally, we enter into an automatic adapation loop.
 {
  //Set up the problem with 4 node refineable Poisson elements
  RefineableFishPoissonProblem<RefineableQPoissonElement<2,2> > problem;
  // Setup labels for output
  //------------------------
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory("RESLT");
  // Step number
  doc_info.number()=0;
  // Doc (default) refinement targets
  //----------------------------------
  problem.mesh_pt()->doc_adaptivity_targets(cout);
  // Solve/doc the problem on the initial, very coarse mesh
  //-------------------------------------------------------
  // Solve the problem
  problem.newton_solve();
  //Output solution
  problem.doc_solution(doc_info);
  //Increment counter for solutions
  doc_info.number()++;
  // Do three rounds of uniform mesh refinement and re-solve
  //--------------------------------------------------------
  unsigned n_uniform=3;
  for (unsigned isolve=0;isolve<n_uniform;isolve++)
   {
    // Refine the problem uniformly
    problem.refine_uniformly();
    // Solve the problem
    problem.newton_solve();
    //Output solution
    problem.doc_solution(doc_info);
    //Increment counter for solutions
    doc_info.number()++;
   }
  // Now do (up to) four rounds of fully automatic adapation in response to
  //-----------------------------------------------------------------------
  // error estimate
  //---------------
  unsigned max_solve=4;
  for (unsigned isolve=0;isolve<max_solve;isolve++)
   {
    // Adapt problem/mesh
    problem.adapt();
    // Re-solve the problem if the adaptation has changed anything
    if ((problem.mesh_pt()->nrefined()  !=0)||
        (problem.mesh_pt()->nunrefined()!=0))
     {
      problem.newton_solve();
     }
    else
     {
      cout << "Mesh wasn't adapted --> we'll stop here" << std::endl;
      break;
     }
    //Output solution
    problem.doc_solution(doc_info);
    //Increment counter for solutions
    doc_info.number()++;
   }
 } // end of incremental
References oomph::DocInfo::number(), problem, and oomph::DocInfo::set_directory().
Referenced by main().