MercuryDPM: Mercury3D Class Reference
Mercury3D Class Reference
This adds on the hierarchical grid code for 3D problems.
#include <Mercury3D.h>
Public Member Functions
Mercury3D ()
This is the default constructor. All it does is set sensible defaults.
Mercury3D (const DPMBase &other)
Copy-constructor for creates an Mercury3D problem from an existing MD problem.
Mercury3D (const Mercury3D &other)
Copy-constructor.
void constructor ()
Function that sets the SystemDimension and ParticleDimension to 3.
std::vector< BaseParticle * > hGridFindParticleContacts (const BaseParticle *obj) override
Returns all particles that have a contact with a given particle.
Public Member Functions inherited from MercuryBase
MercuryBase ()
This is the default constructor. It sets sensible defaults.
~MercuryBase () override
This is the default destructor.
MercuryBase (const MercuryBase &mercuryBase)
Copy-constructor.
void constructor ()
This is the actual constructor, it is called do both constructors above.
void hGridActionsBeforeTimeLoop () override
This sets up the broad phase information, has to be done at this stage because it requires the particle size.
void hGridActionsBeforeTimeStep () override
Performs all necessary actions before a time-step, like updating the particles and resetting all the bucket information, etc.
void read (std::istream &is, ReadOptions opt=ReadOptions::ReadAll) override
Reads the MercuryBase from an input stream, for example a restart file.
void write (std::ostream &os, bool writeAllParticles=true) const override
Writes all data into a restart file.
Mdouble getHGridCurrentMaxRelativeDisplacement () const
Returns hGridCurrentMaxRelativeDisplacement_.
Mdouble getHGridTotalCurrentMaxRelativeDisplacement () const
Returns hGridTotalCurrentMaxRelativeDisplacement_.
void setHGridUpdateEachTimeStep (bool updateEachTimeStep)
Sets whether or not the HGrid must be updated every time step.
bool getHGridUpdateEachTimeStep () const final
Gets whether or not the HGrid is updated every time step.
void setHGridMaxLevels (unsigned int HGridMaxLevels)
Sets the maximum number of levels of the HGrid in this MercuryBase.
unsigned int getHGridMaxLevels () const
Gets the maximum number of levels of the HGrid in this MercuryBase.
HGridMethod getHGridMethod () const
Gets whether the HGrid in this MercuryBase is BOTTOMUP or TOPDOWN.
void setHGridMethod (HGridMethod hGridMethod)
Sets the HGridMethod to either BOTTOMUP or TOPDOWN.
HGridDistribution getHGridDistribution () const
Gets how the sizes of the cells of different levels are distributed.
void setHGridDistribution (HGridDistribution hGridDistribution)
Sets how the sizes of the cells of different levels are distributed.
Mdouble getHGridCellOverSizeRatio () const
Gets the ratio of the smallest cell over the smallest particle.
void setHGridCellOverSizeRatio (Mdouble cellOverSizeRatio)
Sets the ratio of the smallest cell over the smallest particle.
bool hGridNeedsRebuilding ()
Gets if the HGrid needs rebuilding before anything else happens.
virtual unsigned int getHGridTargetNumberOfBuckets () const
Gets the desired number of buckets, which is the maximum of the number of particles and 10.
virtual Mdouble getHGridTargetMinInteractionRadius () const
Gets the desired size of the smallest cells of the HGrid.
virtual Mdouble getHGridTargetMaxInteractionRadius () const
Gets the desired size of the largest cells of the HGrid.
bool checkParticleForInteraction (const BaseParticle &P) final
Checks if given BaseParticle has an interaction with a BaseWall or other BaseParticle.
bool checkParticleForInteractionLocal (const BaseParticle &P) final
Checks if the given BaseParticle has an interaction with a BaseWall or other BaseParticles in a local domain.
virtual Mdouble userHGridCellSize (unsigned int level)
Virtual function that enables inheriting classes to implement a function to let the user set the cell size of the HGrid.
void hGridInfo (std::ostream &os=std::cout) const
Writes the info of the HGrid to the screen in a nice format.
Public Member Functions inherited from DPMBase
void constructor ()
A function which initialises the member variables to default values, so that the problem can be solved off the shelf; sets up a basic two dimensional problem which can be solved off the shelf. It is called in the constructor DPMBase().
DPMBase ()
Constructor that calls the "void constructor()".
DPMBase (const DPMBase &other)
Copy constructor type-2.
virtual ~DPMBase ()
virtual destructor
void autoNumber ()
The autoNumber() function calls three functions: setRunNumber(), readRunNumberFromFile() and incrementRunNumberInFile().
std::vector< int > get1DParametersFromRunNumber (int size_x) const
This turns a counter into 1 index, which is a useful feature for performing 1D parameter study. The index run from 1:size_x, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get2DParametersFromRunNumber (int size_x, int size_y) const
This turns a counter into 2 indices which is a very useful feature for performing a 2D study. The indices run from 1:size_x and 1:size_y, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get3DParametersFromRunNumber (int size_x, int size_y, int size_z) const
This turns a counter into 3 indices, which is a useful feature for performing a 3D parameter study. The indices run from 1:size_x, 1:size_y and 1:size_z, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
int launchNewRun (const char *name, bool quick=false)
This launches a code from within this code. Please pass the name of the code to run.
void setRunNumber (int runNumber)
This sets the counter/Run number, overriding the defaults.
int getRunNumber () const
This returns the current value of the counter (runNumber_)
virtual void decompose ()
Sends particles from processorId to the root processor.
void solve ()
The work horse of the code.
void initialiseSolve ()
Beginning of the solve routine, before time stepping.
void finaliseSolve ()
End of the solve routine, after time stepping.
virtual void computeOneTimeStep ()
Performs everything needed for one time step, used in the time-loop of solve().
void checkSettings ()
Checks if the essentials are set properly to go ahead with solving the problem.
void forceWriteOutputFiles ()
Writes output files immediately, even if the current time step was not meant to be written. Also resets the last saved time step.
virtual void writeOutputFiles ()
Writes simulation data to all the main Mercury files: .data, .ene, .fstat, .xballs and .restart (see the Mercury website for more details regarding these files).
void solve (int argc, char *argv[])
The work horse of the code. Can handle flags from the command line.
virtual void setupInitialConditions ()
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
virtual void writeXBallsScript () const
This writes a script which can be used to load the xballs problem to display the data just generated.
virtual Mdouble getInfo (const BaseParticle &P) const
A virtual function that returns some user-specified information about a particle.
ParticleVtkWriter * getVtkWriter () const
virtual void writeRestartFile ()
Stores all the particle data for current save time step to a "restart" file, which is a file simply intended to store all the information necessary to "restart" a simulation from a given time step (see also MercuryDPM.org for more information on restart files).
void writeDataFile ()
void writeEneFile ()
void writeFStatFile ()
void fillDomainWithParticles (unsigned N=50)
bool readRestartFile (ReadOptions opt=ReadOptions::ReadAll)
Reads all the particle data corresponding to a given, existing . restart file (for more details regarding restart files, refer to the training materials on the MercuryDPM website).Returns true if it is successful, false otherwise.
int readRestartFile (std::string fileName, ReadOptions opt=ReadOptions::ReadAll)
The same as readRestartFile(bool), but also reads all the particle data corresponding to the current saved time step.
virtual BaseWall * readUserDefinedWall (const std::string &type) const
Allows you to read in a wall defined in a Driver directory; see USER/Luca/ScrewFiller.
virtual void readOld (std::istream &is)
Reads all data from a restart file, e.g. domain data and particle data; old version.
bool readDataFile (std::string fileName="", unsigned int format=0)
This allows particle data to be reloaded from data files.
bool readParAndIniFiles (std::string fileName)
Allows the user to read par.ini files (useful to read files produced by the MDCLR simulation code - external to MercuryDPM)
bool readNextDataFile (unsigned int format=0)
Reads the next data file with default format=0. However, one can modify the format based on whether the particle data corresponds to 3D or 2D data- see Visualising data in xballs.
void readNextFStatFile ()
Reads the next fstat file.
bool findNextExistingDataFile (Mdouble tMin, bool verbose=true)
Finds and opens the next data file, if such a file exists.
bool readArguments (int argc, char *argv[])
Can interpret main function input arguments that are passed by the driver codes.
bool checkParticleForInteractionLocalPeriodic (const BaseParticle &P)
void readSpeciesFromDataFile (bool read=true)
void importParticlesAs (ParticleHandler &particleHandler, InteractionHandler &interactionHandler, const ParticleSpecies *species)
Copies particles, interactions assigning species from a local simulation to a global one. Useful for the creation of a cluster.
MERCURYDPM_DEPRECATED File & getDataFile ()
The non const version. Allows one to edit the File::dataFile.
MERCURYDPM_DEPRECATED File & getEneFile ()
The non const version. Allows to edit the File::eneFile.
MERCURYDPM_DEPRECATED File & getFStatFile ()
The non const version. Allows to edit the File::fStatFile.
MERCURYDPM_DEPRECATED File & getRestartFile ()
The non const version. Allows to edit the File::restartFile.
MERCURYDPM_DEPRECATED File & getStatFile ()
The non const version. Allows to edit the File::statFile.
File & getInteractionFile ()
Return a reference to the file InteractionsFile.
MERCURYDPM_DEPRECATED const File & getDataFile () const
The const version. Does not allow for any editing of the File::dataFile.
MERCURYDPM_DEPRECATED const File & getEneFile () const
The const version. Does not allow for any editing of the File::eneFile.
MERCURYDPM_DEPRECATED const File & getFStatFile () const
The const version. Does not allow for any editing of the File::fStatFile.
MERCURYDPM_DEPRECATED const File & getRestartFile () const
The const version. Does not allow for any editing of the File::restartFile.
MERCURYDPM_DEPRECATED const File & getStatFile () const
The const version. Does not allow for any editing of the File::statFile.
const File & getInteractionFile () const
Returns a constant reference to an Interactions file.
const std::string & getName () const
Returns the name of the file. Does not allow to change it though.
void setName (const std::string &name)
Allows to set the name of all the files (ene, data, fstat, restart, stat)
void setName (const char *name)
Calls setName(std::string)
void setSaveCount (unsigned int saveCount)
Sets File::saveCount_ for all files (ene, data, fstat, restart, stat)
void setFileType (FileType fileType)
Sets File::fileType_ for all files (ene, data, fstat, restart, stat)
void setOpenMode (std::fstream::openmode openMode)
Sets File::openMode_ for all files (ene, data, fstat, restart, stat)
void resetFileCounter ()
Resets the file counter for each file i.e. for ene, data, fstat, restart, stat)
void closeFiles ()
Closes all files (ene, data, fstat, restart, stat) that were opened to read or write.
void setVTKOutputDirectory (const std::string &dir)
Sets the output directory of the VTK files.
void setLastSavedTimeStep (unsigned int nextSavedTimeStep)
Sets the next time step for all the files (ene, data, fstat, restart, stat) at which the data is to be written or saved.
Mdouble getTime () const
Returns the current simulation time.
Mdouble getNextTime () const
Returns the current simulation time.
unsigned int getNumberOfTimeSteps () const
Returns the current counter of time-steps, i.e. the number of time-steps that the simulation has undergone so far.
void setTime (Mdouble time)
Sets a new value for the current simulation time.
void setTimeMax (Mdouble newTMax)
Sets a new value for the maximum simulation duration.
Mdouble getTimeMax () const
Returns the maximum simulation duration.
void setLogarithmicSaveCount (Mdouble logarithmicSaveCountBase)
Sets File::logarithmicSaveCount_ for all files (ene, data, fstat, restart, stat)
void setNToWrite (int nToWrite)
set the number of elements to write to the screen
int getNToWrite () const
get the number of elements to write to the
void setRotation (bool rotation)
Sets whether particle rotation is enabled or disabled.
bool getRotation () const
Indicates whether particle rotation is enabled or disabled.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (FileType writeWallsVTK)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (bool)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setInteractionsWriteVTK (bool)
Sets whether interactions are written into a VTK file.
void setParticlesWriteVTK (bool writeParticlesVTK)
Sets whether particles are written in a VTK file.
void setSuperquadricParticlesWriteVTK (bool writeSuperquadricParticlesVTK)
MERCURYDPM_DEPRECATED FileType getWallsWriteVTK () const
Returns whether walls are written in a VTK file.
bool getParticlesWriteVTK () const
Returns whether particles are written in a VTK file.
bool getSuperquadricParticlesWriteVTK () const
Mdouble getXMin () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMin() returns XMin.
Mdouble getXMax () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMax() returns XMax.
Mdouble getYMin () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMin() returns YMin.
Mdouble getYMax () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMax() returns XMax.
Mdouble getZMin () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMin() returns ZMin.
Mdouble getZMax () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMax() returns ZMax.
Mdouble getXCenter () const
Mdouble getYCenter () const
Mdouble getZCenter () const
Vec3D getCenter () const
get center of domain
Vec3D getMin () const
Returns the minimum coordinates of the problem domain.
Vec3D getMax () const
Returns the maximum coordinates of the problem domain.
void setXMin (Mdouble newXMin)
Sets the value of XMin, the lower bound of the problem domain in the x-direction.
void setYMin (Mdouble newYMin)
Sets the value of YMin, the lower bound of the problem domain in the y-direction.
void setZMin (Mdouble newZMin)
Sets the value of ZMin, the lower bound of the problem domain in the z-direction.
void setXMax (Mdouble newXMax)
Sets the value of XMax, the upper bound of the problem domain in the x-direction.
void setYMax (Mdouble newYMax)
Sets the value of YMax, the upper bound of the problem domain in the y-direction.
void setZMax (Mdouble newZMax)
Sets the value of ZMax, the upper bound of the problem domain in the z-direction.
void setMax (const Vec3D &max)
Sets the maximum coordinates of the problem domain.
void setMax (Mdouble, Mdouble, Mdouble)
Sets the maximum coordinates of the problem domain.
void setDomain (const Vec3D &min, const Vec3D &max)
Sets the minimum coordinates of the problem domain.
void setMin (const Vec3D &min)
Sets the minimum coordinates of the problem domain.
void setMin (Mdouble, Mdouble, Mdouble)
Sets the minimum coordinates of the problem domain.
void setTimeStep (Mdouble newDt)
Sets a new value for the simulation time step.
Mdouble getTimeStep () const
Returns the simulation time step.
void setNumberOfOMPThreads (int numberOfOMPThreads)
Sets the number of omp threads.
int getNumberOfOMPThreads () const
Returns the number of omp threads.
void setXBallsColourMode (int newCMode)
Set the xballs output mode.
int getXBallsColourMode () const
Get the xballs colour mode (CMode).
void setXBallsVectorScale (double newVScale)
Set the scale of vectors in xballs.
double getXBallsVectorScale () const
Returns the scale of vectors used in xballs.
void setXBallsAdditionalArguments (std::string newXBArgs)
Set the additional arguments for xballs.
std::string getXBallsAdditionalArguments () const
Returns the additional arguments for xballs.
void setXBallsScale (Mdouble newScale)
Sets the scale of the view (either normal, zoom in or zoom out) to display in xballs. The default is fit to screen.
double getXBallsScale () const
Returns the scale of the view in xballs.
void setGravity (Vec3D newGravity)
Sets a new value for the gravitational acceleration.
Vec3D getGravity () const
Returns the gravitational acceleration.
void setBackgroundDrag (Mdouble backgroundDrag)
Simple access function to turn on a background drag. The force of particleVelocity*drag is applied (note, it allowed to be negative i.e. create energy)
const Mdouble getBackgroundDrag () const
Return the background drag.
void setDimension (unsigned int newDim)
Sets both the system dimensions and the particle dimensionality.
void setSystemDimensions (unsigned int newDim)
Sets the system dimensionality.
unsigned int getSystemDimensions () const
Returns the system dimensionality.
void setParticleDimensions (unsigned int particleDimensions)
Sets the particle dimensionality.
unsigned int getParticleDimensions () const
Returns the particle dimensionality.
std::string getRestartVersion () const
This is to take into account for different Mercury versions. Returns the version of the restart file.
void setRestartVersion (std::string newRV)
Sets restart_version.
bool getRestarted () const
Returns the flag denoting if the simulation was restarted or not.
void setRestarted (bool newRestartedFlag)
Allows to set the flag stating if the simulation is to be restarted or not.
bool getAppend () const
Returns whether the "append" option is on or off.
void setAppend (bool newAppendFlag)
Sets whether the "append" option is on or off.
Mdouble getElasticEnergy () const
Returns the global elastic energy within the system.
Mdouble getKineticEnergy () const
Returns the global kinetic energy stored in the system.
Mdouble getGravitationalEnergy (Vec3D origin={0, 0, 0}) const
Returns the global gravitational potential energy stored relative to a user-defined origin in the system. Note, if no origin is specified the real origin i.e. (0,0,0) is taken.
Mdouble getRotationalEnergy () const
Returns the global rotational energy stored in the system.
Mdouble getTotalEnergy () const
Mdouble getTotalMass () const
JMFT: Return the total mass of the system, excluding fixed particles.
Vec3D getCentreOfMass () const
JMFT: Return the centre of mass of the system, excluding fixed particles.
Vec3D getTotalMomentum () const
JMFT: Return the total momentum of the system, excluding fixed particles.
double getCPUTime ()
double getWallTime ()
virtual void hGridInsertParticle (BaseParticle *obj UNUSED)
virtual void hGridUpdateParticle (BaseParticle *obj UNUSED)
virtual void hGridRemoveParticle (BaseParticle *obj UNUSED)
bool mpiIsInCommunicationZone (BaseParticle *particle)
Checks if the position of the particle is in an mpi communication zone or not.
bool mpiInsertParticleCheck (BaseParticle *P)
Function that checks if the mpi particle should really be inserted by the current domain.
void insertGhostParticle (BaseParticle *P)
This function inserts a particle in the mpi communication boundaries.
void updateGhostGrid (BaseParticle *P)
Checks if the Domain/periodic interaction distance needs to be updated and updates it accordingly.
virtual void gatherContactStatistics (unsigned int index1, int index2, Vec3D Contact, Mdouble delta, Mdouble ctheta, Mdouble fdotn, Mdouble fdott, Vec3D P1_P2_normal_, Vec3D P1_P2_tangential)
//Not unsigned index because of possible wall collisions.
void setNumberOfDomains (std::vector< unsigned > direction)
Sets the number of domains in x-,y- and z-direction. Required for parallel computations.
void splitDomain (DomainSplit domainSplit)
std::vector< unsigned > getNumberOfDomains ()
returns the number of domains
Domain * getCurrentDomain ()
Function that returns a pointer to the domain corresponding to the processor.
void removeOldFiles () const
void setMeanVelocity (Vec3D V_mean_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
void setMeanVelocityAndKineticEnergy (Vec3D V_mean_goal, Mdouble Ek_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
Mdouble getTotalVolume () const
Get the total volume of the cuboid system.
Matrix3D getKineticStress () const
Calculate the kinetic stress tensor in the system averaged over the whole volume.
Matrix3D getStaticStress () const
Calculate the static stress tensor in the system averaged over the whole volume.
Matrix3D getTotalStress () const
Calculate the total stress tensor in the system averaged over the whole volume.
virtual void handleParticleRemoval (unsigned int id)
Handles the removal of particles from the particleHandler.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
void writePythonFileForVTKVisualisation () const
writes .py file for ParaView
void setWritePythonFileForVTKVisualisation (bool forceWritePythonFileForVTKVisualisation)
bool getWritePythonFileForVTKVisualisation () const
WallVTKWriter & getWallVTKWriter ()
Protected Member Functions
void hGridFindContactsWithinTargetCell (int x, int y, int z, unsigned int l)
Finds contacts between particles in the target cell.
void hGridFindContactsWithTargetCell (int x, int y, int z, unsigned int l, BaseParticle *obj)
Finds contacts between the BaseParticle and the target cell.
void computeWallForces (BaseWall *w) override
Compute contacts with a wall.
void hGridFindParticlesWithTargetCell (int x, int y, int z, unsigned int l, BaseParticle *obj, std::vector< BaseParticle * > &list)
Finds particles within target cell and stores them in a list.
void hGridGetInteractingParticleList (BaseParticle *obj, std::vector< BaseParticle * > &list) override
Obtains all neighbour particles of a given object, obtained from the hgrid.
void computeInternalForces (BaseParticle *obj) override
Finds contacts with the BaseParticle; avoids multiple checks.
bool hGridHasContactsInTargetCell (int x, int y, int z, unsigned int l, const BaseParticle *obj) const
Tests if the BaseParticle has contacts with other Particles in the target cell.
bool hGridHasParticleContacts (const BaseParticle *obj) override
Tests if a BaseParticle has any contacts in the HGrid.
void hGridRemoveParticle (BaseParticle *obj) override
Removes a BaseParticle from the HGrid.
void hGridUpdateParticle (BaseParticle *obj) override
Updates the cell (not the level) of a BaseParticle.
Protected Member Functions inherited from MercuryBase
void hGridRebuild ()
This sets up the parameters required for the contact model.
void hGridInsertParticle (BaseParticle *obj) final
Inserts a single Particle to current grid.
void hGridUpdateMove (BaseParticle *iP, Mdouble move) final
Computes the relative displacement of the given BaseParticle and updates the currentMaxRelativeDisplacement_ accordingly.
void hGridActionsBeforeIntegration () override
Resets the currentMaxRelativeDisplacement_ to 0.
void hGridActionsAfterIntegration () override
This function has to be called before integrateBeforeForceComputation.
HGrid * getHGrid ()
Gets the HGrid used by this problem.
const HGrid * getHGrid () const
Gets the HGrid used by this problem, const version.
bool readNextArgument (int &i, int argc, char *argv[]) override
Reads the next command line argument.
Protected Member Functions inherited from DPMBase
virtual void computeAllForces ()
Computes all the forces acting on the particles using the BaseInteractable::setForce() and BaseInteractable::setTorque()
virtual void computeInternalForce (BaseParticle *, BaseParticle *)
Computes the forces between two particles (internal in the sense that the sum over all these forces is zero i.e. fully modelled forces)
virtual void computeExternalForces (BaseParticle *)
Computes the external forces, such as gravity, acting on particles.
virtual void computeForcesDueToWalls (BaseParticle *, BaseWall *)
Computes the forces on the particles due to the walls (normals are outward normals)
virtual void actionsOnRestart ()
A virtual function where the users can add extra code which is executed only when the code is restarted.
virtual void actionsBeforeTimeLoop ()
A virtual function. Allows one to carry out any operations before the start of the time loop.
virtual void actionsBeforeTimeStep ()
A virtual function which allows to define operations to be executed before the new time step.
virtual void computeAdditionalForces ()
A virtual function which allows to define operations to be executed prior to the OMP force collect.
virtual void actionsAfterSolve ()
A virtual function which allows to define operations to be executed after the solve().
virtual void actionsAfterTimeStep ()
A virtual function which allows to define operations to be executed after time step.
void writeVTKFiles () const
virtual void outputXBallsData (std::ostream &os) const
This function writes the location of the walls and particles in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void outputXBallsDataParticle (unsigned int i, unsigned int format, std::ostream &os) const
This function writes out the particle locations into an output stream in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void writeEneHeader (std::ostream &os) const
Writes a header with a certain format for ENE file.
virtual void writeFstatHeader (std::ostream &os) const
Writes a header with a certain format for FStat file.
virtual void writeEneTimeStep (std::ostream &os) const
Write the global kinetic, potential energy, etc. in the system.
virtual void initialiseStatistics ()
virtual void outputStatistics ()
void gatherContactStatistics ()
virtual void processStatistics (bool)
virtual void finishStatistics ()
virtual void integrateBeforeForceComputation ()
Update particles' and walls' positions and velocities before force computation.
virtual void integrateAfterForceComputation ()
Update particles' and walls' positions and velocities after force computation.
virtual void checkInteractionWithBoundaries ()
There are a range of boundaries one could implement depending on ones' problem. This methods checks for interactions between particles and such range of boundaries. See BaseBoundary.h and all the boundaries in the Boundaries folder.
void setFixedParticles (unsigned int n)
Sets a number, n, of particles in the particleHandler as "fixed particles".
virtual void printTime () const
Displays the current simulation time and the maximum simulation duration.
virtual bool continueSolve () const
A virtual function for deciding whether to continue the simulation, based on a user-specified criterion.
void outputInteractionDetails () const
Displays the interaction details corresponding to the pointer objects in the interaction handler.
bool isTimeEqualTo (Mdouble time) const
Checks whether the input variable "time" is the current time in the simulation.
void removeDuplicatePeriodicParticles ()
Removes periodic duplicate Particles.
void checkAndDuplicatePeriodicParticles ()
For simulations using periodic boundaries, checks and adds particles when necessary into the particle handler. See DPMBase.cc and PeriodicBoundary.cc for more details.
void performGhostParticleUpdate ()
When the Verlet scheme updates the positions and velocities of particles, ghost particles will need an update as wel. Their status will also be updated accordingly.
void deleteGhostParticles (std::set< BaseParticle * > &particlesToBeDeleted)
void synchroniseParticle (BaseParticle *, unsigned fromProcessor=0)
void performGhostVelocityUpdate ()
updates the final time-step velocity of the ghost particles
void disableSoftStop ()
This prevents the initialisation of the soft stop feature.
void discontinueSolve ()
This discontinues the solve loop after the current time step is finished.
Additional Inherited Members
Public Types inherited from DPMBase
enum class ReadOptions : int { ReadAll , ReadNoInteractions , ReadNoParticlesAndInteractions }
enum class DomainSplit {
X , Y , Z , XY ,
XZ , YZ , XYZ
}
Static Public Member Functions inherited from DPMBase
static void incrementRunNumberInFile ()
Increment the run Number (counter value) stored in the file_counter (COUNTER_DONOTDEL) by 1 and store the new value in the counter file.
static int readRunNumberFromFile ()
Read the run number or the counter from the counter file (COUNTER_DONOTDEL)
static bool areInContact (const BaseParticle *pI, const BaseParticle *pJ)
Checks if two particle are in contact or is there any positive overlap.
Public Attributes inherited from DPMBase
SpeciesHandler speciesHandler
A handler to that stores the species type i.e. LinearViscoelasticSpecies, etc.
RNG random
This is a random generator, often used for setting up the initial conditions etc...
ParticleHandler particleHandler
An object of the class ParticleHandler, contains the pointers to all the particles created.
ParticleHandler paoloParticleHandler
Fake particleHandler created by Paolo needed temporary by just Paolo.
WallHandler wallHandler
An object of the class WallHandler. Contains pointers to all the walls created.
BoundaryHandler boundaryHandler
An object of the class BoundaryHandler which concerns insertion and deletion of particles into or from regions.
PeriodicBoundaryHandler periodicBoundaryHandler
Internal handler that deals with periodic boundaries, especially in a parallel build.
DomainHandler domainHandler
An object of the class DomainHandler which deals with parallel code.
InteractionHandler interactionHandler
An object of the class InteractionHandler.
CGHandler cgHandler
Object of the class cgHandler.
File dataFile
An instance of class File to handle in- and output into a .data file.
File fStatFile
An instance of class File to handle in- and output into a .fstat file.
File eneFile
An instance of class File to handle in- and output into a .ene file.
File restartFile
An instance of class File to handle in- and output into a .restart file.
File statFile
An instance of class File to handle in- and output into a .stat file.
File interactionFile
File class to handle in- and output into .interactions file. This file hold information about interactions.
Time clock_
record when the simulation started
Detailed Description
This adds on the hierarchical grid code for 3D problems.
Constructor & Destructor Documentation
Mercury3D() [1/3]
Mercury3D::Mercury3D ()
This is the default constructor. All it does is set sensible defaults.
 {
     constructor();
     logger(DEBUG, "Mercury3D::Mercury3D() finished");
 }
References constructor(), DEBUG, and logger.
Mercury3D() [2/3]
Mercury3D::Mercury3D (const DPMBase & other) explicit
Copy-constructor for creates an Mercury3D problem from an existing MD problem.
Parameters
[in] other DPMBase which has to be copied and converted to a Mercury3D.
Constructor that makes a Mercury3D out of a DPMBase. The "copy"-constructor of DPMBase has to be called because the link from DPMBase to MercuryBase is virtual.
         : DPMBase(other), MercuryBase()
 {
     constructor();
     logger(DEBUG, "Mercury3D::Mercury3D(DPMBase& other) constructor finished");
 }
References constructor(), DEBUG, and logger.
Mercury3D() [3/3]
Mercury3D::Mercury3D (const Mercury3D & other)
Copy-constructor.
Parameters
[in] other Mercury3D that must be copied.
Copy constructor, note that the copy-constructor of DPMBase has to be called because the link from DPMBase to MercuryBase is virtual.
         : DPMBase(other), MercuryBase(other)
 {
     logger(DEBUG, "Mercury3D::Mercury3D(Mercury3D& other) copy constructor finished.");
 }
References DEBUG, and logger.
Member Function Documentation
computeInternalForces()
void Mercury3D::computeInternalForces (BaseParticle * obj) override protected virtual
Finds contacts with the BaseParticle; avoids multiple checks.
Parameters
[in] obj A pointer to the BaseParticle for which we want to check for contacts.
Computes all collision between given BaseParticle and all other particles in the grid. Please note that we're looking only one way, so that interactions are not detected twice.
Reimplemented from DPMBase.
 {
     HGrid* const hgrid = getHGrid();
     const unsigned int startLevel = obj->getHGridLevel();
     if (getHGridMethod() == TOPDOWN)
     {
         int occupiedLevelsMask = hgrid->getOccupiedLevelsMask();
         for (unsigned int level = 0; level <= startLevel && occupiedLevelsMask != 0; occupiedLevelsMask >>= 1, level++)
         {
             // If no objects at this level, go on to the next level
             if ((occupiedLevelsMask & 1) == 0)
             {
                 continue;
             }
             if (level == startLevel)
             {
                 const int x = obj->getHGridX();
                 const int y = obj->getHGridY();
                 const int z = obj->getHGridZ();
                 hGridFindContactsWithinTargetCell(x, y, z, level);
                 hGridFindContactsWithTargetCell(x + 1, y - 1, z, level, obj);
                 hGridFindContactsWithTargetCell(x + 1, y, z, level, obj);
                 hGridFindContactsWithTargetCell(x + 1, y + 1, z, level, obj);
                 hGridFindContactsWithTargetCell(x + 1, y - 1, z + 1, level, obj);
                 hGridFindContactsWithTargetCell(x + 1, y, z + 1, level, obj);
                 hGridFindContactsWithTargetCell(x + 1, y + 1, z + 1, level, obj);
                 hGridFindContactsWithTargetCell(x + 1, y - 1, z - 1, level, obj);
                 hGridFindContactsWithTargetCell(x + 1, y, z - 1, level, obj);
                 hGridFindContactsWithTargetCell(x + 1, y + 1, z - 1, level, obj);
                 hGridFindContactsWithTargetCell(x, y + 1, z, level, obj);
                 hGridFindContactsWithTargetCell(x, y, z - 1, level, obj);
                 hGridFindContactsWithTargetCell(x, y + 1, z - 1, level, obj);
                 hGridFindContactsWithTargetCell(x, y + 1, z + 1, level, obj);
             }
             else
             {
                 const Mdouble inv_size = getHGrid()->getInvCellSize(level);
                 const int xs = static_cast<int>(std::floor(
                         (obj->getPosition().X - obj->getMaxInteractionRadius()) * inv_size - 0.5));
                 const int xe = static_cast<int>(std::floor(
                         (obj->getPosition().X + obj->getMaxInteractionRadius()) * inv_size + 0.5));
                 const int ys = static_cast<int>(std::floor(
                         (obj->getPosition().Y - obj->getMaxInteractionRadius()) * inv_size - 0.5));
                 const int ye = static_cast<int>(std::floor(
                         (obj->getPosition().Y + obj->getMaxInteractionRadius()) * inv_size + 0.5));
                 const int zs = static_cast<int>(std::floor(
                         (obj->getPosition().Z - obj->getMaxInteractionRadius()) * inv_size - 0.5));
                 const int ze = static_cast<int>(std::floor(
                         (obj->getPosition().Z + obj->getMaxInteractionRadius()) * inv_size + 0.5));
                 for (int x = xs; x <= xe; ++x)
                 {
                     for (int y = ys; y <= ye; ++y)
                     {
                         for (int z = zs; z <= ze; ++z)
{
                             hGridFindContactsWithTargetCell(x, y, z, level, obj);
                         }
                     }
                 }
             }
         }
     }
     else
     {
         int occupiedLevelsMask = hgrid->getOccupiedLevelsMask() >> obj->getHGridLevel();
         for (unsigned int level = startLevel; level < hgrid->getNumberOfLevels(); occupiedLevelsMask >>= 1, level++)
         {
             // If no objects in rest of grid, stop now
             if (occupiedLevelsMask == 0)
             {
                 break;
             }
             // If no objects at this level, go on to the next level
             if ((occupiedLevelsMask & 1) == 0)
             {
                 continue;
             }
             if (level == startLevel)
             {
                 const int x = obj->getHGridX();
                 const int y = obj->getHGridY();
                 const int z = obj->getHGridZ();
                 hGridFindContactsWithinTargetCell(x, y, z, level);
                 hGridFindContactsWithTargetCell(x + 1, y - 1, z, level, obj);
                 hGridFindContactsWithTargetCell(x + 1, y, z, level, obj);
                 hGridFindContactsWithTargetCell(x + 1, y + 1, z, level, obj);
                 hGridFindContactsWithTargetCell(x + 1, y - 1, z + 1, level, obj);
                 hGridFindContactsWithTargetCell(x + 1, y, z + 1, level, obj);
                 hGridFindContactsWithTargetCell(x + 1, y + 1, z + 1, level, obj);
                 hGridFindContactsWithTargetCell(x + 1, y - 1, z - 1, level, obj);
                 hGridFindContactsWithTargetCell(x + 1, y, z - 1, level, obj);
                 hGridFindContactsWithTargetCell(x + 1, y + 1, z - 1, level, obj);
                 hGridFindContactsWithTargetCell(x, y + 1, z, level, obj);
                 hGridFindContactsWithTargetCell(x, y, z - 1, level, obj);
                 hGridFindContactsWithTargetCell(x, y + 1, z - 1, level, obj);
                 hGridFindContactsWithTargetCell(x, y + 1, z + 1, level, obj);
             }
             else
             {
                 const Mdouble inv_size = hgrid->getInvCellSize(level);
                 const int xs = static_cast<int>(std::floor(
                         (obj->getPosition().X - obj->getMaxInteractionRadius()) * inv_size - 0.5));
                 const int xe = static_cast<int>(std::floor(
                         (obj->getPosition().X + obj->getMaxInteractionRadius()) * inv_size + 0.5));
                 const int ys = static_cast<int>(std::floor(
                         (obj->getPosition().Y - obj->getMaxInteractionRadius()) * inv_size - 0.5));
                 const int ye = static_cast<int>(std::floor(
                         (obj->getPosition().Y + obj->getMaxInteractionRadius()) * inv_size + 0.5));
                 const int zs = static_cast<int>(std::floor(
                         (obj->getPosition().Z - obj->getMaxInteractionRadius()) * inv_size - 0.5));
                 const int ze = static_cast<int>(std::floor(
                         (obj->getPosition().Z + obj->getMaxInteractionRadius()) * inv_size + 0.5));
                 for (int x = xs; x <= xe; ++x)
                 {
                     for (int y = ys; y <= ye; ++y)
                     {
                         for (int z = zs; z <= ze; ++z)
{
                             hGridFindContactsWithTargetCell(x, y, z, level, obj);
                         }
                     }
                 }
             }
         }
     }
 }
References Eigen::bfloat16_impl::floor(), MercuryBase::getHGrid(), BaseParticle::getHGridLevel(), MercuryBase::getHGridMethod(), BaseParticle::getHGridX(), BaseParticle::getHGridY(), BaseParticle::getHGridZ(), HGrid::getInvCellSize(), BaseParticle::getMaxInteractionRadius(), HGrid::getNumberOfLevels(), HGrid::getOccupiedLevelsMask(), BaseInteractable::getPosition(), hGridFindContactsWithinTargetCell(), hGridFindContactsWithTargetCell(), TOPDOWN, plotDoE::x, Vec3D::X, y, Vec3D::Y, and Vec3D::Z.
computeWallForces()
void Mercury3D::computeWallForces (BaseWall * w) override protected virtual
Compute contacts with a wall.
Reimplemented from DPMBase.
 {
     // if wall is not local, use the non-hGrid version for finding wall contacts
     Vec3D min, max;
     if (w->isLocal(min, max)==false)
     {
         return DPMBase::computeWallForces(w);
     }
     //compute forces for all particles that are neither fixed or ghosts
     if (getHGrid() == nullptr || getHGrid()->getNeedsRebuilding())
     {
         logger(INFO, "HGrid needs rebuilding for \"bool Mercury3D::hGridHasParticleContacts(BaseParticle *obj)\"");
         hGridRebuild();
     }
     HGrid* const hGrid = getHGrid();
     int occupiedLevelsMask = hGrid->getOccupiedLevelsMask();
     for (unsigned int level = 0; level < hGrid->getNumberOfLevels(); occupiedLevelsMask >>= 1, level++)
     {
         // If no objects in rest of grid, stop now
         if (occupiedLevelsMask == 0)
         {
             logger(VERBOSE, "Level % and higher levels are empty", level);
             break;
         }
         // If no objects at this level, go on to the next level
         if ((occupiedLevelsMask & 1) == 0)
         {
             logger(VERBOSE, "Level % is empty", level);
             continue;
         }
         const Mdouble inv_size = hGrid->getInvCellSize(level);
         const int xs = static_cast<int>(std::floor(min.X * inv_size - 0.5));
         const int xe = static_cast<int>(std::floor(max.X * inv_size + 0.5));
         const int ys = static_cast<int>(std::floor(min.Y * inv_size - 0.5));
         const int ye = static_cast<int>(std::floor(max.Y * inv_size + 0.5));
         const int zs = static_cast<int>(std::floor(min.Z * inv_size - 0.5));
         const int ze = static_cast<int>(std::floor(max.Z * inv_size + 0.5));
         //logger(INFO, "Level % grid cells [%,%] x [%,%] x [%,%]", level, xs, xe, ys, ye, zs, ze);
         for (int x = xs; x <= xe; ++x)
         {
             for (int y = ys; y <= ye; ++y)
             {
                 for (int z = zs; z <= ze; ++z)
                 {
                     // Loop through all objects in the bucket to find nearby objects
                     const unsigned int bucket = hGrid->computeHashBucketIndex(x, y, z, level);
                     BaseParticle* p = hGrid->getFirstBaseParticleInBucket(bucket);
                     while (p != nullptr)
                     {
                         if (!p->isFixed() && p->getPeriodicFromParticle() == nullptr &&
                             p->getHGridCell().equals(x, y, z, level))
{
                             //logger(INFO, "t % p % Size % level % cells % % %", getNumberOfTimeSteps(), p->getIndex(), hGrid->getCellSize(level), level, x,y,z);
                             computeForcesDueToWalls(p, w);
                             //w->computeForces(p);
                         }
                         p = p->getHGridNextObject();
                     }
                 }
             }
         }
     } //end for level
 }
References DPMBase::computeForcesDueToWalls(), HGrid::computeHashBucketIndex(), DPMBase::computeWallForces(), Eigen::bfloat16_impl::floor(), HGrid::getFirstBaseParticleInBucket(), MercuryBase::getHGrid(), HGrid::getInvCellSize(), HGrid::getNumberOfLevels(), HGrid::getOccupiedLevelsMask(), MercuryBase::hGridRebuild(), INFO, logger, max, min, p, VERBOSE, w, plotDoE::x, and y.
constructor()
void Mercury3D::constructor ()
Function that sets the SystemDimension and ParticleDimension to 3.
 {
     setParticleDimensions(3);
     setSystemDimensions(3);
 }
References DPMBase::setParticleDimensions(), and DPMBase::setSystemDimensions().
Referenced by Mercury3D().
hGridFindContactsWithinTargetCell()
void Mercury3D::hGridFindContactsWithinTargetCell (int x, int y, int z, unsigned int l) protected
Finds contacts between particles in the target cell.
Parameters
[in] x Coordinate of the target cell in x direction.
[in] y Coordinate of the target cell in y direction.
[in] z Coordinate of the target cell in z direction.
[in] l Level in the HGrid of the target cell.
Computes all collision between particles in the same bucket as cell (x,y,z,l), please note that all the particles are in the same cell.
Todo:
replace this generic check of the each bucket to checking only the object to avoid the critical
Bug:
TW: This check is not necessary, I believe. This is the most-expensive function in most codes (the two checks in this function slows down granular jet by 15%) and the selftests are not affected.
Bug:
DK: I do think this is necessary, for example: If two cells hash to the same bucket and a particle in one of these cells check for collisions with the other cell. Then due to the hashing collision it also gets all particles in it's own cell and thus generating false collisions.
 {
     HGrid* const hgrid = getHGrid();
     const unsigned int bucket = hgrid->computeHashBucketIndex(x, y, z, l);
     //Check if this function is already applied to this bucket
     bool bucketIsChecked;
     #pragma omp critical
     {
         bucketIsChecked = hgrid->getBucketIsChecked(bucket);
         hgrid->setBucketIsChecked(bucket);
     }
     if (bucketIsChecked) return;
     BaseParticle* p1 = hgrid->getFirstBaseParticleInBucket(bucket);
     while (p1 != nullptr)
     {
         BaseParticle* p2 = p1->getHGridNextObject();
         while (p2 != nullptr)
         {
             //Check if the BaseParticle* p1 and BaseParticle* p2 are really in the same cell (i.e. no hashing error has occurred)
             if (p1->getHGridCell() == (p2->getHGridCell()))
             {
                 computeInternalForce(p1, p2);
             }
             p2 = p2->getHGridNextObject();
         }
         p1 = p1->getHGridNextObject();
     }
 }
References HGrid::computeHashBucketIndex(), DPMBase::computeInternalForce(), HGrid::getBucketIsChecked(), HGrid::getFirstBaseParticleInBucket(), MercuryBase::getHGrid(), BaseParticle::getHGridCell(), BaseParticle::getHGridNextObject(), p1, HGrid::setBucketIsChecked(), plotDoE::x, and y.
Referenced by computeInternalForces().
hGridFindContactsWithTargetCell()
void Mercury3D::hGridFindContactsWithTargetCell (int x, int y, int z, unsigned int l, BaseParticle * obj) protected
Finds contacts between the BaseParticle and the target cell.
Parameters
[in] x The coordinate of the target cell in x direction.
[in] y The coordinate of the target cell in y direction.
[in] z The coordinate of the target cell in z direction.
[in] l The level in the HGrid of the target cell.
[in] obj A pointer to the BaseParticle for which we want to have interactions.
Computes all collisions between given BaseParticle and particles in cell (x,y,z,l). This is done by first checking if the BaseParticle is indeed from another cell, then for all BaseParticle in the target cell it is checked what the forces between that BaseParticle and given BaseParticle are.
 {
     //Check if the object is not in the same cell as being checked, CheckCell_current should handle these cases.
     //TW a speedcheck revealed that this check costs a 10% performance decrease; it's only a safety check, so I made it an assert.
     logger.assert_debug(!obj->getHGridCell().equals(x, y, z, l),
                   "hGridFindContactsWithTargetCell should not be called if object is in the same cell");
     HGrid* const hgrid = getHGrid();
     // Calculate the bucket
     const unsigned int bucket = hgrid->computeHashBucketIndex(x, y, z, l);
     // Loop through all objects in the bucket to find nearby objects
     for (BaseParticle* p = hgrid->getFirstBaseParticleInBucket(bucket); p != nullptr; p = p->getHGridNextObject())
     {
         //This is the most-expensive function in most codes (the two checks in this function slows down granular jet by 15%). It is neccesary, for example: If two cells hash to the same bucket and a particle in one of these cells check for collisions with the other cell. Then due to the hashing collision it also gets all particles in it's own cell and thus generating false collisions.
         //Check if the BaseParticle *p really is in the target cell (i.e. no hashing error has occurred)
         //TW speedcheck revealed that this pre-check is cheaper than allowing computeInternalForces to sort out mismatches; even if a large number of hash cells (10*Np) is used.
         if (p->getHGridCell().equals(x, y, z, l))
         {
             if (Vec3D::getDistanceSquared(p->getPosition(),obj->getPosition()) < mathsFunc::square(p->getMaxInteractionRadius()+obj->getMaxInteractionRadius()))
                 computeInternalForce(obj, p);
         }
     }
 }
References HGrid::computeHashBucketIndex(), DPMBase::computeInternalForce(), HGridCell::equals(), Vec3D::getDistanceSquared(), HGrid::getFirstBaseParticleInBucket(), MercuryBase::getHGrid(), BaseParticle::getHGridCell(), BaseParticle::getMaxInteractionRadius(), BaseInteractable::getPosition(), logger, p, mathsFunc::square(), plotDoE::x, and y.
Referenced by computeInternalForces().
hGridFindParticleContacts()
std::vector< BaseParticle * > Mercury3D::hGridFindParticleContacts (const BaseParticle * obj) override virtual
Returns all particles that have a contact with a given particle.
Implements MercuryBase.
 {
     if (getHGrid() == nullptr || getHGrid()->getNeedsRebuilding())
     {
         logger(INFO, "HGrid needs rebuilding for \"bool Mercury3D::hGridHasParticleContacts(BaseParticle *obj)\"");
         hGridRebuild();
     }
     int occupiedLevelsMask = getHGrid()->getOccupiedLevelsMask();
     std::vector<BaseParticle*> particlesInContact;
     for (unsigned int level = 0; level < getHGrid()->getNumberOfLevels(); occupiedLevelsMask >>= 1, level++)
     {
         // If no objects in rest of grid, stop now
         if (occupiedLevelsMask == 0)
         {
             logger(VERBOSE, "Level % and higher levels are empty", level);
             break;
         }
         // If no objects at this level, go on to the next level
         if ((occupiedLevelsMask & 1) == 0)
         {
             logger(VERBOSE, "Level % is empty", level);
             continue;
         }
         const Mdouble inv_size = getHGrid()->getInvCellSize(level);
         const int xs = static_cast<int>(std::floor(
                 (obj->getPosition().X - obj->getMaxInteractionRadius()) * inv_size - 0.5));
         const int xe = static_cast<int>(std::floor(
                 (obj->getPosition().X + obj->getMaxInteractionRadius()) * inv_size + 0.5));
         const int ys = static_cast<int>(std::floor(
                 (obj->getPosition().Y - obj->getMaxInteractionRadius()) * inv_size - 0.5));
         const int ye = static_cast<int>(std::floor(
                 (obj->getPosition().Y + obj->getMaxInteractionRadius()) * inv_size + 0.5));
         const int zs = static_cast<int>(std::floor(
                 (obj->getPosition().Z - obj->getMaxInteractionRadius()) * inv_size - 0.5));
         const int ze = static_cast<int>(std::floor(
                 (obj->getPosition().Z + obj->getMaxInteractionRadius()) * inv_size + 0.5));
         logger(VERBOSE, "Level = % grid cells [%,%] x [%,%] x [%,%]", level, xs, xe, ys, ye, zs, ze);
         for (int x = xs; x <= xe; ++x)
         {
             for (int y = ys; y <= ye; ++y)
             {
                 for (int z = zs; z <= ze; ++z)
                 {
                     // Loop through all objects in the bucket to find nearby objects
                     const unsigned int bucket = getHGrid()->computeHashBucketIndex(x, y, z, level);
                     BaseParticle* p = getHGrid()->getFirstBaseParticleInBucket(bucket);
                     while (p != nullptr)
                     {
                         if (p->getHGridCell().equals(x, y, z, level))
{
                             if (areInContact(obj, p))
{
                                 particlesInContact.push_back(p);
                             }
                         }
                         p = p->getHGridNextObject();
                     }
                 }
             }
         }
     } //end for level
     return particlesInContact;
 }
References DPMBase::areInContact(), HGrid::computeHashBucketIndex(), Eigen::bfloat16_impl::floor(), HGrid::getFirstBaseParticleInBucket(), MercuryBase::getHGrid(), HGrid::getInvCellSize(), BaseParticle::getMaxInteractionRadius(), HGrid::getNumberOfLevels(), HGrid::getOccupiedLevelsMask(), BaseInteractable::getPosition(), MercuryBase::hGridRebuild(), INFO, logger, p, VERBOSE, plotDoE::x, Vec3D::X, y, Vec3D::Y, and Vec3D::Z.
hGridFindParticlesWithTargetCell()
void Mercury3D::hGridFindParticlesWithTargetCell (int x, int y, int z, unsigned int l, BaseParticle * obj, std::vector< BaseParticle * > & list) protected
Finds particles within target cell and stores them in a list.
 {
     HGrid* const hgrid = getHGrid();
     // Calculate the bucket
     const unsigned int bucket = hgrid->computeHashBucketIndex(x, y, z, l);
     // Loop through all objects in the bucket to find nearby objects
     BaseParticle* p = hgrid->getFirstBaseParticleInBucket(bucket);
     while (p != nullptr)
     {
         if (p->getHGridCell().equals(x, y, z, l))
         {
             list.push_back(p);
         }
         p = p->getHGridNextObject();
     }
 }
References HGrid::computeHashBucketIndex(), HGrid::getFirstBaseParticleInBucket(), MercuryBase::getHGrid(), p, plotDoE::x, and y.
Referenced by hGridGetInteractingParticleList().
hGridGetInteractingParticleList()
void Mercury3D::hGridGetInteractingParticleList (BaseParticle * obj, std::vector< BaseParticle * > & list) override protected virtual
Obtains all neighbour particles of a given object, obtained from the hgrid.
Bug:
find out why this is necessary; if this is not there, the code sometimes segfaults.
Reimplemented from DPMBase.
 {
     HGrid* hgrid = getHGrid();
     if (hGridNeedsRebuilding())
     {
         hGridRebuild();
         hgrid = getHGrid();
     }
     logger(DEBUG, "hgrid %, object %", hgrid, obj);
     int occupiedLevelsMask = hgrid->getOccupiedLevelsMask() >> obj->getHGridLevel();
     for (unsigned int level = 0; level < hgrid->getNumberOfLevels(); level++)
     {
         // If no objects in rest of grid, stop now
         if (occupiedLevelsMask == 0)
         {
             break;
         }
         // If no objects at this level, go on to the next level
         if ((occupiedLevelsMask & 1) == 0)
         {
             continue;
         }
         const Mdouble inv_size = hgrid->getInvCellSize(level);
         const int xs = static_cast<int>(std::floor(
                 (obj->getPosition().X - obj->getMaxInteractionRadius()) * inv_size - 0.5));
         const int xe = static_cast<int>(std::floor(
                 (obj->getPosition().X + obj->getMaxInteractionRadius()) * inv_size + 0.5));
         const int ys = static_cast<int>(std::floor(
                 (obj->getPosition().Y - obj->getMaxInteractionRadius()) * inv_size - 0.5));
         const int ye = static_cast<int>(std::floor(
                 (obj->getPosition().Y + obj->getMaxInteractionRadius()) * inv_size + 0.5));
         const int zs = static_cast<int>(std::floor(
                 (obj->getPosition().Z - obj->getMaxInteractionRadius()) * inv_size - 0.5));
         const int ze = static_cast<int>(std::floor(
                 (obj->getPosition().Z + obj->getMaxInteractionRadius()) * inv_size + 0.5));
         for (int x = xs; x <= xe; ++x)
         {
             for (int y = ys; y <= ye; ++y)
             {
                 for (int z = zs; z <= ze; ++z)
                 {
                     hGridFindParticlesWithTargetCell(x, y, z, level, obj, list);
                 }
             }
         }
     }
 }
References DEBUG, Eigen::bfloat16_impl::floor(), MercuryBase::getHGrid(), BaseParticle::getHGridLevel(), HGrid::getInvCellSize(), BaseParticle::getMaxInteractionRadius(), HGrid::getNumberOfLevels(), HGrid::getOccupiedLevelsMask(), BaseInteractable::getPosition(), hGridFindParticlesWithTargetCell(), MercuryBase::hGridNeedsRebuilding(), MercuryBase::hGridRebuild(), logger, plotDoE::x, Vec3D::X, y, Vec3D::Y, and Vec3D::Z.
hGridHasContactsInTargetCell()
bool Mercury3D::hGridHasContactsInTargetCell (int x, int y, int z, unsigned int l, const BaseParticle * obj) const protected
Tests if the BaseParticle has contacts with other Particles in the target cell.
Parameters
[in] x The coordinate of the target cell in x direction.
[in] y The coordinate of the target cell in y direction.
[in] z The coordinate of the target cell in z direction.
[in] l The level of the HGrid of the target cell.
[in] obj A pointer to the BaseParticle which is checked for contacts.
Tests if there are any collisions between given BaseParticle and particles in cell (x, y, z, l).
 {
     // Loop through all objects in the bucket to find nearby objects
     const unsigned int bucket = getHGrid()->computeHashBucketIndex(x, y, z, l);
     const BaseParticle* p = getHGrid()->getFirstBaseParticleInBucket(bucket);
     while (p != nullptr)
     {
         if (p->getHGridCell().equals(x, y, z, l))
         {
             if (areInContact(obj, p))
             {
                 return true;
             }
         }
         //std::cout << "HERE!" << std::endl;
         p = p->getHGridNextObject();
     }
     return false;
 }
References DPMBase::areInContact(), HGrid::computeHashBucketIndex(), HGrid::getFirstBaseParticleInBucket(), MercuryBase::getHGrid(), p, plotDoE::x, and y.
Referenced by hGridHasParticleContacts().
hGridHasParticleContacts()
bool Mercury3D::hGridHasParticleContacts (const BaseParticle * obj) override protected virtual
Tests if a BaseParticle has any contacts in the HGrid.
Parameters
[in] obj A pointer to the BaseParticle that is tested for contacts.
Tests if there are any collisions between the given BaseParticle and all other particles in the HGrid. Do this by going through all levels, find if there is a collision in any of the levels in any cell of the HGrid.
Implements MercuryBase.
 {
     if (getHGrid() == nullptr || getHGrid()->getNeedsRebuilding())
     {
         logger(INFO, "HGrid needs rebuilding for \"bool Mercury3D::hGridHasParticleContacts(BaseParticle *obj)\"");
         hGridRebuild();
     }
     int occupiedLevelsMask = getHGrid()->getOccupiedLevelsMask();
     for (unsigned int level = 0; level < getHGrid()->getNumberOfLevels(); occupiedLevelsMask >>= 1, level++)
     {
         // If no objects in rest of grid, stop now
         if (occupiedLevelsMask == 0)
         {
             logger(VERBOSE, "Level % and higher levels are empty", level);
             break;
         }
         // If no objects at this level, go on to the next level
         if ((occupiedLevelsMask & 1) == 0)
         {
             logger(VERBOSE, "Level % is empty", level);
             continue;
         }
         const Mdouble inv_size = getHGrid()->getInvCellSize(level);
         const int xs = static_cast<int>(std::floor(
                 (obj->getPosition().X - obj->getMaxInteractionRadius()) * inv_size - 0.5));
         const int xe = static_cast<int>(std::floor(
                 (obj->getPosition().X + obj->getMaxInteractionRadius()) * inv_size + 0.5));
         const int ys = static_cast<int>(std::floor(
                 (obj->getPosition().Y - obj->getMaxInteractionRadius()) * inv_size - 0.5));
         const int ye = static_cast<int>(std::floor(
                 (obj->getPosition().Y + obj->getMaxInteractionRadius()) * inv_size + 0.5));
         const int zs = static_cast<int>(std::floor(
                 (obj->getPosition().Z - obj->getMaxInteractionRadius()) * inv_size - 0.5));
         const int ze = static_cast<int>(std::floor(
                 (obj->getPosition().Z + obj->getMaxInteractionRadius()) * inv_size + 0.5));
         logger(VERBOSE, "Level = % grid cells [%,%] x [%,%] x [%,%]", level, xs, xe, ys, ye, zs, ze);
         for (int x = xs; x <= xe; ++x)
         {
             for (int y = ys; y <= ye; ++y)
             {
                 for (int z = zs; z <= ze; ++z)
                 {
                     if (hGridHasContactsInTargetCell(x, y, z, level, obj))
                     {
                         return true;
                     }
                 }
             }
         }
     } //end for level
     return false;
 }
References Eigen::bfloat16_impl::floor(), MercuryBase::getHGrid(), HGrid::getInvCellSize(), BaseParticle::getMaxInteractionRadius(), HGrid::getNumberOfLevels(), HGrid::getOccupiedLevelsMask(), BaseInteractable::getPosition(), hGridHasContactsInTargetCell(), MercuryBase::hGridRebuild(), INFO, logger, VERBOSE, plotDoE::x, Vec3D::X, y, Vec3D::Y, and Vec3D::Z.
hGridRemoveParticle()
void Mercury3D::hGridRemoveParticle (BaseParticle * obj) override protected
Removes a BaseParticle from the HGrid.
Parameters
[in] obj A pointer to the BaseParticle that needs to be removed.
Removes the given BaseParticle from the HGrid.
 {
     HGrid* const hGrid = getHGrid();
     if (hGrid)
     {
         const unsigned int bucket = hGrid->computeHashBucketIndex(obj->getHGridCell());
         if (obj->getHGridPrevObject())
         {
             obj->getHGridPrevObject()->setHGridNextObject(obj->getHGridNextObject());
         }
         else
         {
             if (hGrid->getFirstBaseParticleInBucket(bucket) == obj)
             {
                 hGrid->setFirstBaseParticleInBucket(bucket, obj->getHGridNextObject());
             }
         }
         if (obj->getHGridNextObject())
         {
             obj->getHGridNextObject()->setHGridPrevObject(obj->getHGridPrevObject());
         }
     }
 }
References HGrid::computeHashBucketIndex(), HGrid::getFirstBaseParticleInBucket(), MercuryBase::getHGrid(), BaseParticle::getHGridCell(), BaseParticle::getHGridNextObject(), BaseParticle::getHGridPrevObject(), HGrid::setFirstBaseParticleInBucket(), BaseParticle::setHGridNextObject(), and BaseParticle::setHGridPrevObject().
Referenced by hGridUpdateParticle(), and ChuteWithPeriodicInflow::integrateBeforeForceComputation().
hGridUpdateParticle()
void Mercury3D::hGridUpdateParticle (BaseParticle * obj) override protected
Updates the cell (not the level) of a BaseParticle.
Parameters
[in] obj A pointer to the BaseParticle that must be updated.
Updates the HGrid positions (x, y and z) of the given BaseParticle.
 {
     HGrid* const hGrid = getHGrid();
     if (hGrid)
     {
         const unsigned int l = obj->getHGridLevel();
         const Mdouble inv_size = hGrid->getInvCellSize(l);
         int x = static_cast<int>(std::floor(obj->getPosition().X * inv_size));
         int y = static_cast<int>(std::floor(obj->getPosition().Y * inv_size));
         int z = static_cast<int>(std::floor(obj->getPosition().Z * inv_size));
 #ifdef CONTACT_LIST_HGRID
         if(obj->getHGridX() != x || obj->getHGridY() != y || obj->getHGridZ() != z)
         {
             int bucket = hGrid->computeHashBucketIndex(x, y, z, l);
             //First the object has to be removed
             hGridRemoveParticle(obj);
             //Also remove all contact associated with it
             getPossibleContactList().remove_ParticlePosibleContacts(obj);
             //And now reinserted
             obj->setHGridNextObject(hGrid->getFirstBaseParticleInBucket(bucket));
             obj->setHGridPrevObject(nullptr);
             if(hGrid->getFirstBaseParticleInBucket(bucket))
             {
                 hGrid->getFirstBaseParticleInBucket(bucket)->setHGridPrevObject(obj);
             }
             hGrid->setFirstBaseParticleInBucket(bucket,obj);
             obj->setHGridX(x);
             obj->setHGridY(y);
             obj->setHGridZ(z);
             InsertObjAgainstGrid(obj);
         }
 #else
         const unsigned int bucket = hGrid->computeHashBucketIndex(x, y, z, l);
         // this needs to be defined as #pragma omp critical if MercuryBase::hGridActionsBeforeTimeStep is parallelised; however, parallelising it make the code slower, not faster.
         {
             obj->setHGridNextObject(hGrid->getFirstBaseParticleInBucket(bucket));
             obj->setHGridPrevObject(nullptr);
             if (hGrid->getFirstBaseParticleInBucket(bucket)) {
                 hGrid->getFirstBaseParticleInBucket(bucket)->setHGridPrevObject(obj);
             }
             hGrid->setFirstBaseParticleInBucket(bucket, obj);
         }
         obj->setHGridX(x);
         obj->setHGridY(y);
         obj->setHGridZ(z);
 #endif
     }
 }
References HGrid::computeHashBucketIndex(), Eigen::bfloat16_impl::floor(), HGrid::getFirstBaseParticleInBucket(), MercuryBase::getHGrid(), BaseParticle::getHGridLevel(), BaseParticle::getHGridX(), BaseParticle::getHGridY(), BaseParticle::getHGridZ(), HGrid::getInvCellSize(), BaseInteractable::getPosition(), hGridRemoveParticle(), HGrid::setFirstBaseParticleInBucket(), BaseParticle::setHGridNextObject(), BaseParticle::setHGridPrevObject(), BaseParticle::setHGridX(), BaseParticle::setHGridY(), BaseParticle::setHGridZ(), plotDoE::x, Vec3D::X, y, Vec3D::Y, and Vec3D::Z.
Referenced by ChuteWithPeriodicInflow::integrateBeforeForceComputation().
The documentation for this class was generated from the following files:
Mercury3D.h
Mercury3D.cc