MercuryDPM: Eigen::TensorEvaluator< TensorReshapingOp< NewDimensions, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< TensorReshapingOp< NewDimensions, ArgType >, Device > Struct Template Reference
#include <TensorMorphing.h>
Public Types
enum {
IsAligned = TensorEvaluator<ArgType, Device>::IsAligned , PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess , BlockAccess = TensorEvaluator<ArgType, Device>::RawAccess , PreferBlockAccess = false ,
CoordAccess = false , RawAccess = TensorEvaluator<ArgType, Device>::RawAccess
}
typedef TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device > Base
typedef TensorReshapingOp< NewDimensions, ArgType > XprType
typedef NewDimensions Dimensions
typedef XprType::Index Index
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef internal::TensorBlockDescriptor< TensorEvaluator::NumOutputDims, Index > TensorBlockDesc
Public Types inherited from Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >
enum ReshapingKind { OneByN = 0 , NByOne = 1 , Runtime = 2 }
enum { IsAligned = TensorEvaluator<ArgType, Device>::IsAligned , PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess }
typedef TensorReshapingOp< NewDimensions, ArgType > XprType
typedef NewDimensions Dimensions
typedef XprType::Index Index
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef StorageMemory< std::remove_const_t< CoeffReturnType >, Device > ConstCastStorage
typedef std::remove_const_t< Scalar > ScalarNoConst
typedef internal::TensorBlockDescriptor< NumOutputDims, Index > TensorBlockDesc
typedef internal::TensorBlockScratchAllocator< Device > TensorBlockScratch
typedef internal::TensorMaterializedBlock< ScalarNoConst, NumOutputDims, Layout, Index > TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType & coeffRef (Index index) const
template<int StoreMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void writePacket (Index index, const PacketReturnType &x) const
template<typename TensorBlock >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void writeBlock (const TensorBlockDesc &desc, const TensorBlock &block)
Public Member Functions inherited from Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType data)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements getResourceRequirements () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock block (TensorBlockDesc &desc, TensorBlockScratch &scratch, bool=false) const
EIGEN_DEVICE_FUNC Storage::Type data () const
EIGEN_DEVICE_FUNC const TensorEvaluator< ArgType, Device > & impl () const
Static Public Attributes
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Static Public Attributes inherited from Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >
static constexpr int NumOutputDims = internal::array_size<Dimensions>::value
static constexpr int NumInputDims
static const ReshapingKind kind
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Additional Inherited Members
Protected Attributes inherited from Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >
TensorEvaluator< ArgType, Device > m_impl
NewDimensions m_dimensions
Member Typedef Documentation
Base
template<typename NewDimensions , typename ArgType , typename Device > typedef TensorEvaluator<const TensorReshapingOp<NewDimensions, ArgType>, Device> Eigen::TensorEvaluator< TensorReshapingOp< NewDimensions, ArgType >, Device >::Base
CoeffReturnType
template<typename NewDimensions , typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< TensorReshapingOp< NewDimensions, ArgType >, Device >::CoeffReturnType
Dimensions
template<typename NewDimensions , typename ArgType , typename Device > typedef NewDimensions Eigen::TensorEvaluator< TensorReshapingOp< NewDimensions, ArgType >, Device >::Dimensions
Index
template<typename NewDimensions , typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< TensorReshapingOp< NewDimensions, ArgType >, Device >::Index
PacketReturnType
template<typename NewDimensions , typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< TensorReshapingOp< NewDimensions, ArgType >, Device >::PacketReturnType
Scalar
template<typename NewDimensions , typename ArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< TensorReshapingOp< NewDimensions, ArgType >, Device >::Scalar
TensorBlockDesc
template<typename NewDimensions , typename ArgType , typename Device > typedef internal::TensorBlockDescriptor<TensorEvaluator::NumOutputDims, Index> Eigen::TensorEvaluator< TensorReshapingOp< NewDimensions, ArgType >, Device >::TensorBlockDesc
XprType
template<typename NewDimensions , typename ArgType , typename Device > typedef TensorReshapingOp<NewDimensions, ArgType> Eigen::TensorEvaluator< TensorReshapingOp< NewDimensions, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename NewDimensions , typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = TensorEvaluator<ArgType, Device>::IsAligned,
     PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess,
     BlockAccess = TensorEvaluator<ArgType, Device>::RawAccess,
     PreferBlockAccess = false,
     CoordAccess = false,  // to be implemented
     RawAccess = TensorEvaluator<ArgType, Device>::RawAccess
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename NewDimensions , typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< TensorReshapingOp< NewDimensions, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
 : Base(op, device) {}
Member Function Documentation
coeffRef()
template<typename NewDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType& Eigen::TensorEvaluator< TensorReshapingOp< NewDimensions, ArgType >, Device >::coeffRef (Index index) const inline
{
     return this->m_impl.coeffRef(index);
   }
writeBlock()
template<typename NewDimensions , typename ArgType , typename Device > template<typename TensorBlock > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< TensorReshapingOp< NewDimensions, ArgType >, Device >::writeBlock (const TensorBlockDesc & desc, const TensorBlock & block) inline
{
     eigen_assert(this->m_impl.data() != NULL);
     typedef typename TensorBlock::XprType TensorBlockExpr;
     typedef internal::TensorBlockAssignment<Scalar, TensorEvaluator::NumOutputDims, TensorBlockExpr, Index>
         TensorBlockAssign;
     TensorBlockAssign::Run(TensorBlockAssign::target(desc.dimensions(), internal::strides<Layout>(this->dimensions()),
                                                      this->m_impl.data(), desc.offset()),
                            block.expr());
   }
References Eigen::TensorEvaluator< Derived, Device >::block(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::dimensions(), eigen_assert, Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::expr(), and Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::offset().
writePacket()
template<typename NewDimensions , typename ArgType , typename Device > template<int StoreMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< TensorReshapingOp< NewDimensions, ArgType >, Device >::writePacket (Index index, const PacketReturnType & x) const inline
{
     this->m_impl.template writePacket<StoreMode>(index, x);
   }
References plotDoE::x.
Member Data Documentation
Layout
template<typename NewDimensions , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< TensorReshapingOp< NewDimensions, ArgType >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
The documentation for this struct was generated from the following file:
TensorMorphing.h