MercuryDPM: MatrixBase_template_int_start.cpp File Reference
MatrixBase_template_int_start.cpp File Reference
Functions
cout<< "Here is the vector v:"<< endl<< v<< endl;cout<< "Here is v.head(2):"<< endl<< v.head< 2 > ()<< endl
v head< 2 > ().setZero()
Variables
RowVector4i v = RowVector4i::Random()
Function Documentation
cout<< "Here is the vector v:"<< endl<< v<< endl;cout<< "Here is v.head(2):"<< endl<< v.head< 2 >()
cout<< "Here is the vector v:"<< endl<< v<< endl;cout<< "Here is v.head(2):"<< endl<< v.head< 2 > ()
head< 2 >()
v head< 2 > ()
Referenced by block(), orthomethods(), orthomethods_2(), and Eigen::internal::unitOrthogonal_selector< Derived, 3 >::run().
Variable Documentation
v
RowVector4i v = RowVector4i::Random()