MercuryDPM: oomph::RefineableAlgebraicCylinderWithFlagMesh< ELEMENT > Class Template Reference
oomph::RefineableAlgebraicCylinderWithFlagMesh< ELEMENT > Class Template Reference
Refineable version of AlgebraicCylinderWithFlagMesh.
#include <cylinder_with_flag_mesh.template.h>
Public Member Functions
RefineableAlgebraicCylinderWithFlagMesh (Circle *cylinder_pt, GeomObject *top_flag_pt, GeomObject *bottom_flag_pt, GeomObject *tip_flag_pt, const double &length, const double &height, const double &flag_length, const double &flag_height, const double &centre_x, const double &centre_y, const double &a, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
void update_node_update (AlgebraicNode *&node_pt)
Update the node update functions.
Public Member Functions inherited from oomph::RefineableQuadMesh< ELEMENT >
RefineableQuadMesh ()
Constructor: Setup static quadtree data.
RefineableQuadMesh (const RefineableQuadMesh &dummy)=delete
Broken copy constructor.
virtual ~RefineableQuadMesh ()
Broken assignment operator.
virtual void setup_tree_forest ()
void setup_quadtree_forest ()
Public Member Functions inherited from oomph::TreeBasedRefineableMesh< ELEMENT >
TreeBasedRefineableMesh ()
Constructor, call the constructor of the base class.
TreeBasedRefineableMesh (const TreeBasedRefineableMesh &dummy)=delete
Broken copy constructor.
virtual ~TreeBasedRefineableMesh ()
Empty virtual destructor.
Public Member Functions inherited from oomph::TreeBasedRefineableMeshBase
TreeBasedRefineableMeshBase ()
Constructor.
TreeBasedRefineableMeshBase (const TreeBasedRefineableMeshBase &dummy)=delete
Broken copy constructor.
void operator= (const TreeBasedRefineableMeshBase &)=delete
Broken assignment operator.
virtual ~TreeBasedRefineableMeshBase ()
Empty Destructor:
void adapt (const Vector< double > &elemental_error)
void p_adapt (const Vector< double > &elemental_error)
void refine_uniformly (DocInfo &doc_info)
Refine mesh uniformly and doc process.
void refine_uniformly ()
Refine mesh uniformly.
void p_refine_uniformly (DocInfo &doc_info)
p-refine mesh uniformly and doc process
void p_refine_uniformly ()
p-refine mesh uniformly
unsigned unrefine_uniformly ()
void p_unrefine_uniformly (DocInfo &doc_info)
p-unrefine mesh uniformly
TreeForest * forest_pt ()
Return pointer to the Forest represenation of the mesh.
void doc_adaptivity_targets (std::ostream &outfile)
Doc the targets for mesh adaptation.
unsigned & max_refinement_level ()
Access fct for max. permissible refinement level (relative to base mesh)
unsigned & min_refinement_level ()
Access fct for min. permissible refinement level (relative to base mesh)
unsigned & max_p_refinement_level ()
unsigned & min_p_refinement_level ()
virtual void adapt_mesh (DocInfo &doc_info)
virtual void adapt_mesh ()
void p_adapt_mesh (DocInfo &doc_info)
void p_adapt_mesh ()
virtual void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
virtual void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
p-refine mesh by refining the elements identified by their numbers.
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
p-refine mesh by refining the elements identified by their pointers.
virtual void refine_base_mesh_as_in_reference_mesh (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
Refine to same degree as the reference mesh.
virtual bool refine_base_mesh_as_in_reference_mesh_minus_one (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
virtual void refine_as_in_reference_mesh (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
virtual void get_refinement_levels (unsigned &min_refinement_level, unsigned &max_refinement_level)
Get max/min refinement levels in mesh.
virtual void get_elements_at_refinement_level (unsigned &refinement_level, Vector< RefineableElement * > &level_elements)
virtual void get_refinement_pattern (Vector< Vector< unsigned >> &to_be_refined)
void refine_base_mesh (Vector< Vector< unsigned >> &to_be_refined)
Refine base mesh according to specified refinement pattern.
virtual void refine (std::ifstream &restart_file)
Refine mesh according to refinement pattern in restart file.
virtual void dump_refinement (std::ostream &outfile)
Dump refinement pattern to allow for rebuild.
virtual void read_refinement (std::ifstream &restart_file, Vector< Vector< unsigned >> &to_be_refined)
Read refinement pattern to allow for rebuild.
unsigned uniform_refinement_level_when_pruned () const
unsigned & uniform_refinement_level_when_pruned ()
Level to which the mesh was uniformly refined when it was pruned.
Public Member Functions inherited from oomph::RefineableMeshBase
bool adapt_flag ()
RefineableMeshBase ()
RefineableMeshBase (const RefineableMeshBase &dummy)=delete
Broken copy constructor.
void operator= (const RefineableMeshBase &)=delete
Broken assignment operator.
virtual ~RefineableMeshBase ()
Empty Destructor:
unsigned nrefined ()
Access fct for number of elements that were refined.
unsigned nunrefined ()
Access fct for number of elements that were unrefined.
unsigned & nrefinement_overruled ()
unsigned & max_keep_unrefined ()
ErrorEstimator *& spatial_error_estimator_pt ()
Access to spatial error estimator.
ErrorEstimator * spatial_error_estimator_pt () const
Access to spatial error estimator (const version.
double & min_permitted_error ()
double & max_permitted_error ()
double & min_error ()
double & max_error ()
DocInfo *& doc_info_pt ()
Access fct for pointer to DocInfo.
void enable_adaptation ()
Enable adaptation.
void disable_adaptation ()
Disable adaptation.
void enable_p_adaptation ()
Enable adaptation.
void disable_p_adaptation ()
Disable adaptation.
void enable_additional_synchronisation_of_hanging_nodes ()
Enable additional synchronisation of hanging nodes.
void disable_additional_synchronisation_of_hanging_nodes ()
Disable additional synchronisation of hanging nodes.
bool is_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_p_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_additional_synchronisation_of_hanging_nodes_disabled () const
Return whether additional synchronisation is enabled.
DocInfo doc_info ()
Access fct for DocInfo.
void p_unrefine_uniformly (DocInfo &doc_info)
p-unrefine mesh uniformly
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Public Member Functions inherited from oomph::QuadMeshBase
QuadMeshBase ()
Constructor (empty)
QuadMeshBase (const QuadMeshBase &node)=delete
Broken copy constructor.
void operator= (const QuadMeshBase &)=delete
Broken assignment operator.
virtual ~QuadMeshBase ()
Destructor (empty)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >
AlgebraicCylinderWithFlagMesh (Circle *cylinder_pt, GeomObject *top_flag_pt, GeomObject *bottom_flag_pt, GeomObject *tip_flag_pt, const double &length, const double &height, const double &flag_length, const double &flag_height, const double &centre_x, const double &centre_y, const double &a, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual ~AlgebraicCylinderWithFlagMesh ()
Destructor: empty.
void set_bottom_flag_pt (GeomObject *bottom_flag_pt)
void set_top_flag_pt (GeomObject *top_flag_pt)
void set_tip_flag_pt (GeomObject *tip_flag_pt)
GeomObject * bottom_flag_pt () const
GeomObject * top_flag_pt () const
GeomObject * tip_flag_pt () const
void algebraic_node_update (const unsigned &t, AlgebraicNode *&node_pt)
The algebraic node update function.
Public Member Functions inherited from oomph::AlgebraicMesh
AlgebraicMesh ()
AlgebraicMesh (const AlgebraicMesh &)=delete
Broken copy constructor.
~AlgebraicMesh ()
Broken assignment operator.
AlgebraicNode * node_pt (const unsigned long &n)
Return a pointer to the n-th global AlgebraicNode.
void node_update (const bool &update_all_solid_nodes=false)
unsigned self_test ()
Self test: check consistentency of multiple node updates.
void add_geom_object_list_pt (GeomObject *geom_object_pt)
unsigned ngeom_object_list_pt ()
Return number of geometric objects associated with AlgebraicMesh.
GeomObject * geom_object_list_pt (const unsigned &i)
Access function to the ith GeomObject.
Public Member Functions inherited from oomph::CylinderWithFlagMesh< ELEMENT >
CylinderWithFlagMesh (Circle *cylinder_pt, GeomObject *top_flag_pt, GeomObject *bottom_flag_pt, GeomObject *tip_flag_pt, const double &length, const double &height, const double &flag_length, const double &flag_height, const double &centre_x, const double &centre_y, const double &a, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual ~CylinderWithFlagMesh ()
Destructor: Kill the domain.
CylinderWithFlagDomain * domain_pt ()
Access function to the domain.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::TreeBasedRefineableMeshBase
void complete_hanging_nodes (const int &ncont_interpolated_values)
Complete the hanging node scheme recursively.
void complete_hanging_nodes_recursively (Node *&nod_pt, Vector< Node * > &master_nodes, Vector< double > &hang_weights, const int &ival)
Auxiliary routine for recursive hanging node completion.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Member Functions inherited from oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >
void setup_algebraic_node_update ()
Function to setup the algebraic node update.
void node_update_I (const unsigned &t, AlgebraicNode *&node_pt)
Helper function.
void node_update_II (const unsigned &t, AlgebraicNode *&node_pt)
Helper function.
void node_update_III (const unsigned &t, AlgebraicNode *&node_pt)
Helper function.
void node_update_IV (const unsigned &t, AlgebraicNode *&node_pt)
Helper function.
void node_update_V (const unsigned &t, AlgebraicNode *&node_pt)
Helper function.
void node_update_VI (const unsigned &t, AlgebraicNode *&node_pt)
Helper function.
void node_update_VII (const unsigned &t, AlgebraicNode *&node_pt)
Helper function.
void node_update_VIII (const unsigned &t, AlgebraicNode *&node_pt)
Helper function.
void node_update_IX (const unsigned &t, AlgebraicNode *&node_pt)
Helper function.
Protected Attributes inherited from oomph::TreeBasedRefineableMeshBase
unsigned Uniform_refinement_level_when_pruned
Level to which the mesh was uniformly refined when it was pruned.
unsigned Max_refinement_level
Max. permissible refinement level (relative to base mesh)
unsigned Min_refinement_level
Min. permissible refinement level (relative to base mesh)
unsigned Max_p_refinement_level
Max. permissible p-refinement level (relative to base mesh)
unsigned Min_p_refinement_level
Min. permissible p-refinement level (relative to base mesh)
TreeForest * Forest_pt
Forest representation of the mesh.
Protected Attributes inherited from oomph::RefineableMeshBase
ErrorEstimator * Spatial_error_estimator_pt
Pointer to spatial error estimator.
double Max_permitted_error
Max. error (i.e. split elements if their error is larger)
double Min_permitted_error
Min. error (i.e. (try to) merge elements if their error is smaller)
double Min_error
Min.actual error.
double Max_error
Max. actual error.
unsigned Nrefined
Stats: Number of elements that were refined.
unsigned Nunrefined
Stats: Number of elements that were unrefined.
bool Adapt_flag
Flag that requests adaptation.
bool P_adapt_flag
Flag that requests p-adaptation.
bool Additional_synchronisation_of_hanging_nodes_not_required
Flag that disables additional synchronisation of hanging nodes.
DocInfo * Doc_info_pt
Pointer to DocInfo.
unsigned Max_keep_unrefined
unsigned Nrefinement_overruled
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Protected Attributes inherited from oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >
GeomObject * Cylinder_pt
Cylinder.
GeomObject * Top_flag_pt
Top flag.
GeomObject * Bottom_flag_pt
Bottom flag.
GeomObject * Tip_flag_pt
Tip flag.
double Length
Length of the domain.
double Height
Height of the domain.
double Flag_length
Flag length.
double Flag_height
Flag thickness.
double Centre_x
x position of the centre of the cylinder
double Centre_y
x position of the centre of the cylinder
double A
radius of the cylinder
Protected Attributes inherited from oomph::CylinderWithFlagMesh< ELEMENT >
CylinderWithFlagDomain * Domain_pt
Pointer to the domain.
Detailed Description
template<class ELEMENT>
class oomph::RefineableAlgebraicCylinderWithFlagMesh< ELEMENT >
Refineable version of AlgebraicCylinderWithFlagMesh.
//////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
RefineableAlgebraicCylinderWithFlagMesh()
template<class ELEMENT > oomph::RefineableAlgebraicCylinderWithFlagMesh< ELEMENT >::RefineableAlgebraicCylinderWithFlagMesh (Circle * cylinder_pt, GeomObject * top_flag_pt, GeomObject * bottom_flag_pt, GeomObject * tip_flag_pt, const double & length, const double & height, const double & flag_length, const double & flag_height, const double & centre_x, const double & centre_y, const double & a, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Constructor: Pass the pointers to the GeomObjects that parametrise the cylinder, the three edges of the flag, the length and height of the domain, the length and height of the flag, the coordinates of the centre of the cylinder and its radius. Timestepper defaults to Steady default timestepper.
       : CylinderWithFlagMesh<ELEMENT>(cylinder_pt,
                                       top_flag_pt,
                                       bottom_flag_pt,
                                       tip_flag_pt,
                                       length,
                                       height,
                                       flag_length,
                                       flag_height,
                                       centre_x,
                                       centre_y,
                                       a,
                                       time_stepper_pt),
         AlgebraicCylinderWithFlagMesh<ELEMENT>(cylinder_pt,
                                                top_flag_pt,
                                                bottom_flag_pt,
                                                tip_flag_pt,
                                                length,
                                                height,
                                                flag_length,
                                                flag_height,
                                                centre_x,
                                                centre_y,
                                                a,
                                                time_stepper_pt)
     {
       // Build quadtree forest
       this->setup_quadtree_forest();
     }
References oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest().
Member Function Documentation
update_node_update()
template<class ELEMENT > void oomph::RefineableAlgebraicCylinderWithFlagMesh< ELEMENT >::update_node_update (AlgebraicNode *& node_pt) virtual
Update the node update functions.
Update the node update data for specified node following any mesh adapation
//////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Reimplemented from oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >.
   {
     // Extract ID
     unsigned id = node_pt->node_update_fct_id();
     if (id == 8)
     {
       // Extract geometric objects for update by copy construction
       Vector<GeomObject*> geom_object_pt(node_pt->vector_geom_object_pt());
       // Extract reference values for node update by copy construction
       Vector<double> ref_value(node_pt->vector_ref_value());
       // Get zeta coordinate of reference point
       Vector<double> zeta_ref_flag(1);
       zeta_ref_flag[0] = ref_value[2];
       // Get the sub-geomobject and the local coordinate containing the
       // reference point
       Vector<double> s(1);
       GeomObject* geom_obj_pt;
       this->Top_flag_pt->locate_zeta(zeta_ref_flag, geom_obj_pt, s);
       // Update the pointer to the (sub-)GeomObject within which the
       // reference point is located.
       geom_object_pt[0] = geom_obj_pt;
       // Update second reference value: Reference local coordinate
       // in flag sub-element
       ref_value[3] = s[0];
       // Get zeta coordinate of point at end of macro element
       Vector<double> zeta_end_flag(1);
       zeta_end_flag[0] = ref_value[4];
       // Get the sub-geomobject and the local coordinate containing the
       // point at the end of the macro element
       this->Top_flag_pt->locate_zeta(zeta_end_flag, geom_obj_pt, s);
       // Update the pointer to the (sub-)GeomObject within which the
       // point at the end of the macro element is located
       geom_object_pt[1] = geom_obj_pt;
       // Update second reference value: Reference local coordinate
       // in flag sub-element
       ref_value[5] = s[0];
       // Kill the existing node update info
       node_pt->kill_node_update_info(8);
       // Setup algebraic update for node: Pass update information
       node_pt->add_node_update_info(8, // id
                                     this, // mesh
                                     geom_object_pt, // vector of geom objects
                                     ref_value); // vector of ref. values
     }
     else if (id == 9)
     {
       // Extract geometric objects for update by copy construction
       Vector<GeomObject*> geom_object_pt(node_pt->vector_geom_object_pt());
       // Extract reference values for node update by copy construction
       Vector<double> ref_value(node_pt->vector_ref_value());
       // Get zeta coordinate of reference point
       Vector<double> zeta_ref_flag(1);
       zeta_ref_flag[0] = ref_value[2];
       // Get the sub-geomobject and the local coordinate containing the
       // reference point
       Vector<double> s(1);
       GeomObject* geom_obj_pt;
       this->Bottom_flag_pt->locate_zeta(zeta_ref_flag, geom_obj_pt, s);
       // Update the pointer to the (sub-)GeomObject within which the
       // reference point is located.
       geom_object_pt[0] = geom_obj_pt;
       // Update second reference value: Reference local coordinate
       // in flag sub-element
       ref_value[3] = s[0];
       // Get zeta coordinate of point at end of macro element
       Vector<double> zeta_end_flag(1);
       zeta_end_flag[0] = ref_value[4];
       // Get the sub-geomobject and the local coordinate containing the
       // point at the end of the macro element
       this->Bottom_flag_pt->locate_zeta(zeta_end_flag, geom_obj_pt, s);
       // Update the pointer to the (sub-)GeomObject within which the
       // point at the end of the macro element is located
       geom_object_pt[1] = geom_obj_pt;
       // Update second reference value: Reference local coordinate
       // in flag sub-element
       ref_value[5] = s[0];
       // Kill the existing node update info
       node_pt->kill_node_update_info(9);
       // Setup algebraic update for node: Pass update information
       node_pt->add_node_update_info(9, // id
                                     this, // mesh
                                     geom_object_pt, // vector of geom objects
                                     ref_value); // vector of ref. values
     }
     if ((id == 1) || (id == 6))
     {
       // Extract reference values for node update by copy construction
       Vector<double> ref_value(node_pt->vector_ref_value());
       // Get zeta coordinate on flag
       Vector<double> zeta_flag(1);
       zeta_flag[0] = ref_value[2];
       // Get the sub-geomobject and the local coordinate
       Vector<double> s(1);
       GeomObject* geom_obj_pt;
       this->Top_flag_pt->locate_zeta(zeta_flag, geom_obj_pt, s);
       // Extract geometric objects for update by copy construction
       Vector<GeomObject*> geom_object_pt(node_pt->vector_geom_object_pt());
       // Update the pointer to the (sub-)GeomObject within which the
       // reference point is located. (If the flag is simple GeomObject
       // this is the same as Leaflet_pt; if it's a compound GeomObject
       // this points to the sub-object)
       geom_object_pt[0] = geom_obj_pt;
       // Update second reference value: Reference local coordinate
       // in flag sub-element
       ref_value[3] = s[0];
       if (id == 1)
       {
         // Kill the existing node update info
         node_pt->kill_node_update_info(1);
         // Setup algebraic update for node: Pass update information
         node_pt->add_node_update_info(1, // id
                                       this, // mesh
                                       geom_object_pt, // vector of geom objects
                                       ref_value); // vector of ref. values
       }
       else if (id == 6)
       {
         // Kill the existing node update info
         node_pt->kill_node_update_info(6);
         // Setup algebraic update for node: Pass update information
         node_pt->add_node_update_info(6, // id
                                       this, // mesh
                                       geom_object_pt, // vector of geom objects
                                       ref_value); // vector of ref. values
       }
     }
     if ((id == 2) || (id == 7))
     {
       // Extract reference values for node update by copy construction
       Vector<double> ref_value(node_pt->vector_ref_value());
       // Get zeta coordinate on flag
       Vector<double> zeta_flag(1);
       zeta_flag[0] = ref_value[2];
       // Get the sub-geomobject and the local coordinate
       Vector<double> s(1);
       GeomObject* geom_obj_pt;
       this->Bottom_flag_pt->locate_zeta(zeta_flag, geom_obj_pt, s);
       // Extract geometric objects for update by copy construction
       Vector<GeomObject*> geom_object_pt(node_pt->vector_geom_object_pt());
       // Update the pointer to the (sub-)GeomObject within which the
       // reference point is located. (If the flag is simple GeomObject
       // this is the same as Leaflet_pt; if it's a compound GeomObject
       // this points to the sub-object)
       geom_object_pt[0] = geom_obj_pt;
       // Update second reference value: Reference local coordinate
       // in flag sub-element
       ref_value[3] = s[0];
       if (id == 2)
       {
         // Kill the existing node update info
         node_pt->kill_node_update_info(2);
         // Setup algebraic update for node: Pass update information
         node_pt->add_node_update_info(2, // id
                                       this, // mesh
                                       geom_object_pt, // vector of geom objects
                                       ref_value); // vector of ref. values
       }
       else if (id == 7)
       {
         // Kill the existing node update info
         node_pt->kill_node_update_info(7);
         // Setup algebraic update for node: Pass update information
         node_pt->add_node_update_info(7, // id
                                       this, // mesh
                                       geom_object_pt, // vector of geom objects
                                       ref_value); // vector of ref. values
       }
     }
     if ((id == 3) || (id == 4) || (id == 5))
     {
       // Extract reference values for node update by copy construction
       Vector<double> ref_value(node_pt->vector_ref_value());
       // Get zeta coordinate on flag
       Vector<double> zeta_flag(1);
       if (id == 3)
       {
         zeta_flag[0] = ref_value[2];
       }
       else if (id == 4)
       {
         zeta_flag[0] = this->Flag_height / 2.;
       }
       else if (id == 5)
       {
         zeta_flag[0] = -this->Flag_height / 2.;
       }
       // Get the sub-geomobject and the local coordinate
       Vector<double> s(1);
       GeomObject* geom_obj_pt;
       this->Tip_flag_pt->locate_zeta(zeta_flag, geom_obj_pt, s);
       // Extract geometric objects for update by copy construction
       Vector<GeomObject*> geom_object_pt(node_pt->vector_geom_object_pt());
       // Update the pointer to the (sub-)GeomObject within which the
       // reference point is located. (If the flag is simple GeomObject
       // this is the same as Leaflet_pt; if it's a compound GeomObject
       // this points to the sub-object)
       geom_object_pt[0] = geom_obj_pt;
       if (id == 3)
       {
         // Update second reference value: Reference local coordinate
         // in flag sub-element
         ref_value[3] = s[0];
         // Kill the existing node update info
         node_pt->kill_node_update_info(3);
         // Setup algebraic update for node: Pass update information
         node_pt->add_node_update_info(3, // id
                                       this, // mesh
                                       geom_object_pt, // vector of geom objects
                                       ref_value); // vector of ref. values
       }
       else if (id == 4)
       {
         // Update second reference value: Reference local coordinate
         // in flag sub-element
         ref_value[2] = s[0];
         // Kill the existing node update info
         node_pt->kill_node_update_info(4);
         // Setup algebraic update for node: Pass update information
         node_pt->add_node_update_info(4, // id
                                       this, // mesh
                                       geom_object_pt, // vector of geom objects
                                       ref_value); // vector of ref. values
       }
       else if (id == 5)
       {
         // Update second reference value: Reference local coordinate
         // in flag sub-element
         ref_value[2] = s[0];
         // Kill the existing node update info
         node_pt->kill_node_update_info(5);
         // Setup algebraic update for node: Pass update information
         node_pt->add_node_update_info(5, // id
                                       this, // mesh
                                       geom_object_pt, // vector of geom objects
                                       ref_value); // vector of ref. values
       }
     }
   }
References oomph::AlgebraicNode::add_node_update_info(), Flag_definition::Bottom_flag_pt, oomph::AlgebraicNode::kill_node_update_info(), oomph::GeomObject::locate_zeta(), oomph::AlgebraicNode::node_update_fct_id(), s, Flag_definition::Tip_flag_pt, Flag_definition::Top_flag_pt, oomph::AlgebraicNode::vector_geom_object_pt(), and oomph::AlgebraicNode::vector_ref_value().
The documentation for this class was generated from the following files:
cylinder_with_flag_mesh.template.h
cylinder_with_flag_mesh.template.cc