MercuryDPM: Eigen::internal::default_digits_impl< T, false, false > Struct Template Reference
Eigen::internal::default_digits_impl< T, false, false > Struct Template Reference
#include <NumTraits.h>
Static Public Member Functions
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR int run ()
Member Function Documentation
run()
template<typename T > EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR int Eigen::internal::default_digits_impl< T, false, false >::run () inline static
{
     using std::ceil;
     using std::log2;
     typedef typename NumTraits<T>::Real Real;
     return int(ceil(-log2(NumTraits<Real>::epsilon())));
   }
References Eigen::bfloat16_impl::ceil(), int(), and log2().
The documentation for this struct was generated from the following file:
NumTraits.h