MercuryDPM: oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM > Class Template Reference
oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM > Class Template Reference
#include <generalised_newtonian_refineable_navier_stokes_elements.h>
Public Member Functions
RefineableGeneralisedNewtonianQTaylorHoodElement ()
Constructor.
unsigned required_nvalue (const unsigned &n) const
unsigned ncont_interpolated_values () const
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: empty.
unsigned nrecovery_order ()
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
void further_setup_hanging_nodes ()
Node * pressure_node_pt (const unsigned &n_p)
Pointer to n_p-th pressure node.
Node * interpolating_node_pt (const unsigned &n, const int &value_id)
double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
unsigned ninterpolating_node_1d (const int &value_id)
unsigned ninterpolating_node (const int &value_id)
void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
void identify_load_data (std::set< std::pair< Data *, unsigned >> &paired_load_data)
Public Member Functions inherited from oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >
GeneralisedNewtonianQTaylorHoodElement ()
Constructor, no internal data points.
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
virtual int p_nodal_index_nst () const
Set the value at which the pressure is stored in the nodes.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
double p_nst (const unsigned &n_p) const
double p_nst (const unsigned &t, const unsigned &n_p) const
unsigned npres_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void identify_pressure_data (std::set< std::pair< Data *, unsigned >> &paired_pressure_data)
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
unsigned ndof_types () const
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
void pshape_nst (const Vector< double > &s, Shape &psi) const
void pshape_nst (const Vector< double > &s, Shape &psi) const
Public Member Functions inherited from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >
GeneralisedNewtonianNavierStokesEquations ()
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
NavierStokesBodyForceFctPt & body_force_fct_pt ()
Access function for the body-force pointer.
NavierStokesBodyForceFctPt body_force_fct_pt () const
Access function for the body-force pointer. Const version.
NavierStokesSourceFctPt & source_fct_pt ()
Access function for the source-function pointer.
NavierStokesSourceFctPt source_fct_pt () const
Access function for the source-function pointer. Const version.
GeneralisedNewtonianConstitutiveEquation< DIM > *& constitutive_eqn_pt ()
Access function for the constitutive equation pointer.
void use_current_strainrate_to_compute_second_invariant ()
Switch to fully implict evaluation of non-Newtonian const eqn.
void use_extrapolated_strainrate_to_compute_second_invariant ()
Use extrapolation for non-Newtonian const eqn.
double u_nst (const unsigned &n, const unsigned &i) const
double u_nst (const unsigned &t, const unsigned &n, const unsigned &i) const
virtual unsigned u_index_nst (const unsigned &i) const
unsigned n_u_nst () const
double du_dt_nst (const unsigned &n, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
double pressure_integral () const
Integral of pressure over element.
void max_and_min_invariant_and_viscosity (double &min_invariant, double &max_invariant, double &min_viscosity, double &max_viscosity) const
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute the vorticity vector at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
double d_kin_energy_dt () const
Get integral of time derivative of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j + du_j/dx_i)
void strain_rate (const unsigned &t, const Vector< double > &s, DenseMatrix< double > &strain_rate) const
virtual void extrapolated_strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
virtual void extrapolated_strain_rate (const unsigned &ipt, DenseMatrix< double > &strain_rate) const
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction_p, Vector< double > &traction_visc_n, Vector< double > &traction_visc_t)
void get_load (const Vector< double > &s, const Vector< double > &N, Vector< double > &load)
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
std::string scalar_name_paraview (const unsigned &i) const
void full_output (std::ostream &outfile)
void full_output (std::ostream &outfile, const unsigned &nplot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void output_vorticity (std::ostream &outfile, const unsigned &nplot)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Compute the element's residual Vector.
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
void pin_all_non_pressure_dofs (std::map< Data *, std::vector< int >> &eqn_number_backup)
Pin all non-pressure dofs and backup eqn numbers.
void interpolated_u_nst (const Vector< double > &s, Vector< double > &veloc) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual double interpolated_p_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_p_nst (const unsigned &t, const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s at time level t.
void point_output_data (const Vector< double > &s, Vector< double > &data)
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute 3D vorticity vector at local coordinate s.
Public Member Functions inherited from oomph::FSIFluidElement
FSIFluidElement ()
Constructor.
FSIFluidElement (const FSIFluidElement &)=delete
Broken copy constructor.
void operator= (const FSIFluidElement &)=delete
Broken assignment operator.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase
GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase ()
Constructor (empty)
virtual ~GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase ()
Virtual destructor (empty)
Public Member Functions inherited from oomph::NavierStokesElementWithDiagonalMassMatrices
NavierStokesElementWithDiagonalMassMatrices ()
Empty constructor.
virtual ~NavierStokesElementWithDiagonalMassMatrices ()
Virtual destructor.
NavierStokesElementWithDiagonalMassMatrices (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken copy constructor.
void operator= (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken assignment operator.
Public Member Functions inherited from oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >
RefineableGeneralisedNewtonianNavierStokesEquations ()
Constructor.
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
void further_build ()
Further build, pass the pointers down to the sons.
void dinterpolated_u_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
virtual unsigned required_nsons () const
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)=0
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void unbuild ()
virtual void deactivate_element ()
virtual bool nodes_built ()
Return true if all the nodes have been built, false if not.
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual void check_integrity (double &max_error)=0
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual RefineableElement * root_element_pt ()
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
virtual void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
virtual void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
Pre-build the element.
virtual void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
unsigned nshape_controlling_nodes ()
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Public Member Functions inherited from oomph::ElementWithZ2ErrorEstimator
ElementWithZ2ErrorEstimator ()
Default empty constructor.
ElementWithZ2ErrorEstimator (const ElementWithZ2ErrorEstimator &)=delete
Broken copy constructor.
void operator= (const ElementWithZ2ErrorEstimator &)=delete
Broken assignment operator.
virtual unsigned ncompound_fluxes ()
virtual void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
virtual void get_Z2_compound_flux_indices (Vector< unsigned > &flux_index)
virtual double geometric_jacobian (const Vector< double > &x)
Public Member Functions inherited from oomph::RefineableQElement< DIM >
RefineableQElement ()
Empty constuctor.
Private Member Functions
void unpin_elemental_pressure_dofs ()
Unpin all pressure dofs.
void pin_elemental_redundant_nodal_pressure_dofs ()
Pin all nodal pressure dofs that are not required.
Additional Inherited Members
Public Types inherited from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >
typedef void(* NavierStokesBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
typedef double(* NavierStokesSourceFctPt) (const double &time, const Vector< double > &x)
typedef double(* NavierStokesPressureAdvDiffSourceFctPt) (const Vector< double > &x)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Member Functions inherited from oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >
static void pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > &element_pt)
static void unpin_all_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in vector.
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Static Public Attributes inherited from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions inherited from oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
const unsigned Pconv [4]
const unsigned Pconv [8]
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Protected Member Functions inherited from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >
virtual void get_body_force_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
virtual void get_body_force_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
virtual double get_source_nst (const double &time, const unsigned &ipt, const Vector< double > &x)
virtual void get_source_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
virtual void fill_in_generic_dresidual_contribution_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, unsigned flag)
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >
void fill_in_generic_residual_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Protected Attributes inherited from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
double * ReInvFr_pt
Vector< double > * G_pt
Pointer to global gravity Vector.
NavierStokesBodyForceFctPt Body_force_fct_pt
Pointer to body force function.
NavierStokesSourceFctPt Source_fct_pt
Pointer to volumetric source function.
GeneralisedNewtonianConstitutiveEquation< DIM > * Constitutive_eqn_pt
Pointer to the generalised Newtonian constitutive equation.
bool Use_extrapolated_strainrate_to_compute_second_invariant
bool ALE_is_disabled
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number – for plotting/validation purposes.
Static Protected Attributes inherited from oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >
static const unsigned Pconv []
Static Protected Attributes inherited from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >
static bool Pre_multiply_by_viscosity_ratio = false
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Detailed Description
template<unsigned DIM>
class oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >
Refineable version of Taylor Hood elements. These classes can be written in total generality.
Constructor & Destructor Documentation
RefineableGeneralisedNewtonianQTaylorHoodElement()
template<unsigned DIM> oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::RefineableGeneralisedNewtonianQTaylorHoodElement () inline
Constructor.
       : RefineableElement(),
         RefineableGeneralisedNewtonianNavierStokesEquations<DIM>(),
         RefineableQElement<DIM>(),
         GeneralisedNewtonianQTaylorHoodElement<DIM>()
     {
     }
Member Function Documentation
further_setup_hanging_nodes()
template<unsigned DIM> void oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::further_setup_hanging_nodes () inline virtual
Perform additional hanging node procedures for variables that are not interpolated by all nodes. The pressures are stored at the p_nodal_index_nst-th location in each node
Reimplemented from oomph::RefineableElement.
     {
       this->setup_hang_for_value(this->p_nodal_index_nst());
     }
References oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::p_nodal_index_nst().
get_interpolated_values() [1/2]
template<unsigned DIM> void oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) inline virtual
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
     {
       // Set size of Vector: u,v,p
       values.resize(DIM + 1);
       // Initialise
       for (unsigned i = 0; i < DIM + 1; i++)
       {
         values[i] = 0.0;
       }
       // Find out how many nodes there are
       unsigned n_node = this->nnode();
       // Shape functions
       Shape psif(n_node);
       this->shape(s, psif);
       // Calculate velocities: values[0],...
       for (unsigned i = 0; i < DIM; i++)
       {
         // Get the index at which the i-th velocity is stored
         unsigned u_nodal_index = this->u_index_nst(i);
         for (unsigned l = 0; l < n_node; l++)
         {
           values[i] += this->nodal_value(t, l, u_nodal_index) * psif[l];
         }
       }
       // Calculate pressure: values[DIM]
       //(no history is carried in the pressure)
       values[DIM] = this->interpolated_p_nst(s);
     }
References DIM, i, oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::interpolated_p_nst(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::u_index_nst().
get_interpolated_values() [2/2]
template<unsigned DIM> void oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) inline virtual
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
     {
       // Set size of Vector: u,v,p and initialise to zero
       values.resize(DIM + 1, 0.0);
       // Calculate velocities: values[0],...
       for (unsigned i = 0; i < DIM; i++)
       {
         values[i] = this->interpolated_u_nst(s, i);
       }
       // Calculate pressure: values[DIM]
       values[DIM] = this->interpolated_p_nst(s);
     }
References DIM, i, oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::interpolated_p_nst(), and oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::interpolated_u_nst().
get_interpolating_node_at_local_coordinate()
template<unsigned DIM> Node* oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::get_interpolating_node_at_local_coordinate (const Vector< double > & s, const int & value_id) inline virtual
The velocity nodes are the same as the geometric nodes. The pressure nodes must be calculated by using the same methods as the geometric nodes, but by recalling that there are only two pressure nodes per edge.
Construct the general pressure index from the components.
Reimplemented from oomph::RefineableElement.
     {
       // If we are calculating pressure nodes
       if (value_id == DIM)
       {
         // Storage for the index of the pressure node
         unsigned total_index = 0;
         // The number of nodes along each 1d edge is 2.
         unsigned NNODE_1D = 2;
         // Storage for the index along each boundary
         Vector<int> index(DIM);
         // Loop over the coordinates
         for (unsigned i = 0; i < DIM; i++)
         {
           // If we are at the lower limit, the index is zero
           if (s[i] == -1.0)
           {
             index[i] = 0;
           }
           // If we are at the upper limit, the index is the number of nodes
           // minus 1
           else if (s[i] == 1.0)
           {
             index[i] = NNODE_1D - 1;
           }
           // Otherwise, we have to calculate the index in general
           else
           {
             // For uniformly spaced nodes the 0th node number would be
             double float_index = 0.5 * (1.0 + s[i]) * (NNODE_1D - 1);
             index[i] = int(float_index);
             // What is the excess. This should be safe because the
             // taking the integer part rounds down
             double excess = float_index - index[i];
             // If the excess is bigger than our tolerance there is no node,
             // return null
             if ((excess > FiniteElement::Node_location_tolerance) &&
                 ((1.0 - excess) > FiniteElement::Node_location_tolerance))
             {
               return 0;
             }
           }
           total_index +=
             index[i] * static_cast<unsigned>(pow(static_cast<float>(NNODE_1D),
                                                  static_cast<int>(i)));
         }
         // If we've got here we have a node, so let's return a pointer to it
         return this->pressure_node_pt(total_index);
       }
       // Otherwise velocity nodes are the same as pressure nodes
       else
       {
         return this->get_node_at_local_coordinate(s);
       }
     }
References DIM, oomph::FiniteElement::get_node_at_local_coordinate(), i, int(), oomph::FiniteElement::Node_location_tolerance, Eigen::bfloat16_impl::pow(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::pressure_node_pt(), and s.
identify_load_data()
template<unsigned DIM> void oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::identify_load_data (std::set< std::pair< Data *, unsigned >> & paired_load_data) inline virtual
Add to the set paired_load_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function. (Overloads non-refineable version and takes hanging nodes into account)
Reimplemented from oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >.
     {
       // Get the nodal indices at which the velocities are stored
       unsigned u_index[DIM];
       for (unsigned i = 0; i < DIM; i++)
       {
         u_index[i] = this->u_index_nst(i);
       }
       // Loop over the nodes
       unsigned n_node = this->nnode();
       for (unsigned n = 0; n < n_node; n++)
       {
         // Pointer to current node
         Node* nod_pt = this->node_pt(n);
         // Check if it's hanging:
         if (nod_pt->is_hanging())
         {
           // It's hanging -- get number of master nodes
           unsigned nmaster = nod_pt->hanging_pt()->nmaster();
           // Loop over masters
           for (unsigned j = 0; j < nmaster; j++)
           {
             Node* master_nod_pt = nod_pt->hanging_pt()->master_node_pt(j);
             // Loop over the velocity components and add pointer to their data
             // and indices to the vectors
             for (unsigned i = 0; i < DIM; i++)
             {
               paired_load_data.insert(
                 std::make_pair(master_nod_pt, u_index[i]));
             }
           }
         }
         // Not hanging
         else
         {
           // Loop over the velocity components and add pointer to their data
           // and indices to the vectors
           for (unsigned i = 0; i < DIM; i++)
           {
             paired_load_data.insert(
               std::make_pair(this->node_pt(n), u_index[i]));
           }
         }
       }
       // Get the nodal index at which the pressure is stored
       int p_index = this->p_nodal_index_nst();
       // Loop over the pressure data
       unsigned n_pres = this->npres_nst();
       for (unsigned l = 0; l < n_pres; l++)
       {
         // Get the pointer to the nodal pressure
         Node* pres_node_pt = this->pressure_node_pt(l);
         // Check if the pressure dof is hanging
         if (pres_node_pt->is_hanging(p_index))
         {
           // Get the pointer to the hang info object
           // (pressure is stored as p_index--th nodal dof).
           HangInfo* hang_info_pt = pres_node_pt->hanging_pt(p_index);
           // Get number of pressure master nodes (pressure is stored
           unsigned nmaster = hang_info_pt->nmaster();
           // Loop over pressure master nodes
           for (unsigned m = 0; m < nmaster; m++)
           {
             // The p_index-th entry in each nodal data is the pressure, which
             // affects the traction
             paired_load_data.insert(
               std::make_pair(hang_info_pt->master_node_pt(m), p_index));
           }
         }
         // It's not hanging
         else
         {
           // The p_index-th entry in each nodal data is the pressure, which
           // affects the traction
           paired_load_data.insert(std::make_pair(pres_node_pt, p_index));
         }
       }
     }
References DIM, oomph::Node::hanging_pt(), i, oomph::Node::is_hanging(), j, m, oomph::HangInfo::master_node_pt(), n, oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::npres_nst(), oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::p_nodal_index_nst(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::pressure_node_pt(), and oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::u_index_nst().
interpolating_basis()
template<unsigned DIM> void oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::interpolating_basis (const Vector< double > & s, Shape & psi, const int & value_id) const inline virtual
The basis interpolating the pressure is given by pshape(). / The basis interpolating the velocity is shape().
Reimplemented from oomph::RefineableElement.
     {
       if (value_id == DIM)
       {
         return this->pshape_nst(s, psi);
       }
       else
       {
         return this->shape(s, psi);
       }
     }
References DIM, oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::pshape_nst(), and oomph::FiniteElement::shape().
interpolating_node_pt()
template<unsigned DIM> Node* oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::interpolating_node_pt (const unsigned & n, const int & value_id) inline virtual
The velocities are isoparametric and so the "nodes" interpolating the velocities are the geometric nodes. The pressure "nodes" are a subset of the nodes, so when value_id==DIM, the n-th pressure node is returned.
Reimplemented from oomph::RefineableElement.
     {
       // The only different nodes are the pressure nodes
       if (value_id == DIM)
       {
         return this->pressure_node_pt(n);
       }
       // The other variables are interpolated via the usual nodes
       else
       {
         return this->node_pt(n);
       }
     }
References DIM, oomph::FiniteElement::node_pt(), and oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::pressure_node_pt().
local_one_d_fraction_of_interpolating_node()
template<unsigned DIM> double oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::local_one_d_fraction_of_interpolating_node (const unsigned & n1d, const unsigned & i, const int & value_id) inline virtual
The pressure nodes are the corner nodes, so when n_value==DIM, the fraction is the same as the 1d node number, 0 or 1.
Reimplemented from oomph::RefineableElement.
     {
       if (value_id == DIM)
       {
         // The pressure nodes are just located on the boundaries at 0 or 1
         return double(n1d);
       }
       // Otherwise the velocity nodes are the same as the geometric ones
       else
       {
         return this->local_one_d_fraction_of_node(n1d, i);
       }
     }
References DIM, i, and oomph::FiniteElement::local_one_d_fraction_of_node().
ncont_interpolated_values()
template<unsigned DIM> unsigned oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::ncont_interpolated_values () const inline virtual
Number of continuously interpolated values: (DIM velocities + 1 pressure)
Implements oomph::RefineableElement.
     {
       return DIM + 1;
     }
References DIM.
ninterpolating_node()
template<unsigned DIM> unsigned oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::ninterpolating_node (const int & value_id) inline virtual
The number of pressure nodes is 2^DIM. The number of velocity nodes is the same as the number of geometric nodes.
Reimplemented from oomph::RefineableElement.
     {
       if (value_id == DIM)
       {
         return static_cast<unsigned>(pow(2.0, static_cast<int>(DIM)));
       }
       else
       {
         return this->nnode();
       }
     }
References DIM, oomph::FiniteElement::nnode(), and Eigen::bfloat16_impl::pow().
ninterpolating_node_1d()
template<unsigned DIM> unsigned oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::ninterpolating_node_1d (const int & value_id) inline virtual
The number of 1d pressure nodes is 2, the number of 1d velocity nodes is the same as the number of 1d geometric nodes.
Reimplemented from oomph::RefineableElement.
     {
       if (value_id == DIM)
       {
         return 2;
       }
       else
       {
         return this->nnode_1d();
       }
     }
References DIM, and oomph::FiniteElement::nnode_1d().
nrecovery_order()
template<unsigned DIM> unsigned oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::nrecovery_order () inline virtual
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       return 2;
     }
nvertex_node()
template<unsigned DIM> unsigned oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::nvertex_node () const inline virtual
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       return GeneralisedNewtonianQTaylorHoodElement<DIM>::nvertex_node();
     }
References oomph::FiniteElement::nvertex_node().
pin_elemental_redundant_nodal_pressure_dofs()
template<unsigned DIM> void oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs () inline private virtual
Pin all nodal pressure dofs that are not required.
Reimplemented from oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >.
     {
       // Find the pressure index
       int p_index = this->p_nodal_index_nst();
       // Loop over all nodes
       unsigned n_node = this->nnode();
       // loop over all nodes and pin all  the nodal pressures
       for (unsigned n = 0; n < n_node; n++)
       {
         this->node_pt(n)->pin(p_index);
       }
       // Loop over all actual pressure nodes and unpin if they're not hanging
       unsigned n_pres = this->npres_nst();
       for (unsigned l = 0; l < n_pres; l++)
       {
         Node* nod_pt = this->pressure_node_pt(l);
         if (!nod_pt->is_hanging(p_index))
         {
           nod_pt->unpin(p_index);
         }
       }
     }
References oomph::Node::is_hanging(), n, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::npres_nst(), oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::p_nodal_index_nst(), oomph::Data::pin(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::pressure_node_pt(), and oomph::Data::unpin().
pressure_node_pt()
template<unsigned DIM> Node* oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::pressure_node_pt (const unsigned & n_p) inline virtual
Pointer to n_p-th pressure node.
Reimplemented from oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >.
     {
       return this->node_pt(this->Pconv[n_p]);
     }
References oomph::FiniteElement::node_pt(), and oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::Pconv.
Referenced by oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::get_interpolating_node_at_local_coordinate(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::identify_load_data(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::interpolating_node_pt(), and oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs().
rebuild_from_sons()
template<unsigned DIM> void oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::rebuild_from_sons (Mesh *& mesh_pt) inline virtual
Rebuild from sons: empty.
Implements oomph::RefineableElement.
 {}
required_nvalue()
template<unsigned DIM> unsigned oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::required_nvalue (const unsigned & n) const inline virtual
Number of values required at local node n. In order to simplify matters, we allocate storage for pressure variables at all the nodes and then pin those that are not used.
Reimplemented from oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >.
     {
       return DIM + 1;
     }
References DIM.
unpin_elemental_pressure_dofs()
template<unsigned DIM> void oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::unpin_elemental_pressure_dofs () inline private virtual
Unpin all pressure dofs.
Implements oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >.
     {
       // find the index at which the pressure is stored
       int p_index = this->p_nodal_index_nst();
       unsigned n_node = this->nnode();
       // loop over nodes
       for (unsigned n = 0; n < n_node; n++)
       {
         this->node_pt(n)->unpin(p_index);
       }
     }
References n, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::p_nodal_index_nst(), and oomph::Data::unpin().
vertex_node_pt()
template<unsigned DIM> Node* oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::vertex_node_pt (const unsigned & j) const inline virtual
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       return GeneralisedNewtonianQTaylorHoodElement<DIM>::vertex_node_pt(j);
     }
References j, and oomph::FiniteElement::vertex_node_pt().
The documentation for this class was generated from the following file:
generalised_newtonian_refineable_navier_stokes_elements.h