MercuryDPM: SSP_RungeKutta< ORDER > Class Template Reference
SSP_RungeKutta< ORDER > Class Template Reference
Public Member Functions
SSP_RungeKutta ()
Constructor, set the type.
SSP_RungeKutta (const SSP_RungeKutta &)
Broken copy constructor.
void operator= (const SSP_RungeKutta &)
Broken assignment operator.
void timestep (ExplicitTimeSteppableObject *const &object_pt, const double &dt)
Function that is used to advance time in the object.
void timestep (ExplicitTimeSteppableObject *const &object_pt, const double &dt)
Explicit specialisation for second-order RK scheme.
Public Member Functions inherited from oomph::ExplicitTimeStepper
ExplicitTimeStepper ()
Empty Constructor.
ExplicitTimeStepper (const ExplicitTimeStepper &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeStepper &)=delete
Broken assignment operator.
virtual ~ExplicitTimeStepper ()
Empty virtual destructor — no memory is allocated in this class.
Additional Inherited Members
Protected Attributes inherited from oomph::ExplicitTimeStepper
std::string Type
Detailed Description
template<unsigned ORDER>
class SSP_RungeKutta< ORDER >
=========================================================== Strong Stability preserving Runge Kutta Timestepping
Constructor & Destructor Documentation
SSP_RungeKutta() [1/2]
template<unsigned ORDER> SSP_RungeKutta< ORDER >::SSP_RungeKutta () inline
Constructor, set the type.
   {
    Type="SSP_RungeKutta";
   }
SSP_RungeKutta() [2/2]
template<unsigned ORDER> SSP_RungeKutta< ORDER >::SSP_RungeKutta (const SSP_RungeKutta< ORDER > &) inline
Broken copy constructor.
   {
    BrokenCopy::broken_copy("SS_PRungeKutta");
   }
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
operator=()
template<unsigned ORDER> void SSP_RungeKutta< ORDER >::operator= (const SSP_RungeKutta< ORDER > &) inline
Broken assignment operator.
   {
    BrokenCopy::broken_assign("SSP_RungeKutta");
   }
References oomph::BrokenCopy::broken_assign().
timestep() [1/2]
template<unsigned ORDER> void SSP_RungeKutta< ORDER >::timestep (ExplicitTimeSteppableObject *const & object_pt, const double & dt) virtual
Function that is used to advance time in the object.
Implements oomph::ExplicitTimeStepper.
 {
  std::ostringstream error_stream;
  error_stream << "Timestep not implemented for order " << ORDER << "\n";
  throw OomphLibError(error_stream.str(),
                      OOMPH_CURRENT_FUNCTION,
                      OOMPH_EXCEPTION_LOCATION);
 }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
timestep() [2/2]
void SSP_RungeKutta< 2 >::timestep (ExplicitTimeSteppableObject *const & object_pt, const double & dt)
Explicit specialisation for second-order RK scheme.
 {
  object_pt->actions_before_explicit_timestep();
  //Store the initial values and initial time
  DoubleVector u;
  object_pt->get_dofs(u);
  // Stage 1
  // ============================================================
  object_pt->actions_before_explicit_stage();
  //Now get the first unknowns
  DoubleVector k1;
  object_pt->get_dvaluesdt(k1);
  //Add to the residuals
  object_pt->add_to_dofs(dt,k1);
  //Increment the time
  object_pt->time() += dt;
  object_pt->actions_after_explicit_stage();
  // Stage 2
  // ============================================================
  object_pt->actions_before_explicit_stage();
  //Get the next unknowns
  DoubleVector k2;
  object_pt->get_dvaluesdt(k2);
  //Add to the residuals so that the current value of the unknowns
  //is the result of two forward Euler steps of time dt
  object_pt->add_to_dofs(dt,k2);
  //Set the final values of the unknowns by taking the average of the
  //initial value and the result of the two forward Euler steps
  //Get the current value
  DoubleVector u_final;
  object_pt->get_dofs(u_final);
  //Now take the average
  unsigned n_dof = u_final.nrow();
  for(unsigned n=0;n<n_dof;n++)
   {
    u_final[n] += u[n];
    u_final[n] *= 0.5;
   }
  //Set the dofs to the new final value
  object_pt->set_dofs(u_final);
  //Time remains the same
  // Actions functions
  object_pt->actions_after_explicit_stage();
  object_pt->actions_after_explicit_timestep();
 }
References oomph::ExplicitTimeSteppableObject::actions_after_explicit_stage(), oomph::ExplicitTimeSteppableObject::actions_after_explicit_timestep(), oomph::ExplicitTimeSteppableObject::actions_before_explicit_stage(), oomph::ExplicitTimeSteppableObject::actions_before_explicit_timestep(), oomph::ExplicitTimeSteppableObject::add_to_dofs(), oomph::ExplicitTimeSteppableObject::get_dofs(), oomph::ExplicitTimeSteppableObject::get_dvaluesdt(), n, oomph::DistributableLinearAlgebraObject::nrow(), oomph::ExplicitTimeSteppableObject::set_dofs(), and oomph::ExplicitTimeSteppableObject::time().
The documentation for this class was generated from the following file:
ff_step.cc