MercuryDPM: Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV1D > Struct Template Reference
Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV1D > Struct Template Reference
#include <TensorConvolutionSycl.h>
Public Types
typedef cl::sycl::accessor< CoeffReturnType, 1, cl::sycl::access::mode::read_write, cl::sycl::access::target::local > Local_accessor
Public Member Functions
EigenConvolutionKernel (Local_accessor local_acc_, Evaluator device_evaluator_, Kernel_accessor kernel_filter_, Buffer_accessor buffer_acc_, internal::IndexMapper< Index, InputDims, 1, Evaluator::Layout > indexMapper_, const size_t kernelSize_, const cl::sycl::range< 2 > input_range_)
template<typename BooleanDim2 >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool boundary_check (const BooleanDim2 boolean_check) const
void operator() (cl::sycl::nd_item< 2 > itemID) const
Public Attributes
Local_accessor local_acc
Evaluator device_evaluator
Kernel_accessor kernel_filter
Buffer_accessor buffer_acc
internal::IndexMapper< Index, InputDims, 1, Evaluator::Layout > indexMapper
const size_t kernelSize
const cl::sycl::range< 2 > input_range
Member Typedef Documentation
Local_accessor
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > typedef cl::sycl::accessor<CoeffReturnType, 1, cl::sycl::access::mode::read_write, cl::sycl::access::target::local> Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV1D >::Local_accessor
Constructor & Destructor Documentation
EigenConvolutionKernel()
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV1D >::EigenConvolutionKernel (Local_accessor local_acc_, Evaluator device_evaluator_, Kernel_accessor kernel_filter_, Buffer_accessor buffer_acc_, internal::IndexMapper< Index, InputDims, 1, Evaluator::Layout > indexMapper_, const size_t kernelSize_, const cl::sycl::range< 2 > input_range_) inline
       : local_acc(local_acc_),
         device_evaluator(device_evaluator_),
         kernel_filter(kernel_filter_),
         buffer_acc(buffer_acc_),
         indexMapper(indexMapper_),
         kernelSize(kernelSize_),
         input_range(input_range_) {}
Member Function Documentation
boundary_check()
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > template<typename BooleanDim2 > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV1D >::boundary_check (const BooleanDim2 boolean_check) const inline
{
     return (boolean_check[0] && boolean_check[1]);
   }
operator()()
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > void Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV1D >::operator() (cl::sycl::nd_item< 2 > itemID) const inline
fill the shared memory
{
     auto buffer_ptr = buffer_acc;
     auto kernel_ptr = kernel_filter;
     // the required row to be calculated for the for each plane in shered memory
     const size_t num_input = (itemID.get_local_range()[0] + kernelSize - 1);
     const size_t plane_kernel_offset = itemID.get_local_id(1) * num_input;
     const size_t input_offset = itemID.get_group(0) * itemID.get_local_range()[0];
     const size_t plane_tensor_offset = indexMapper.mapGpuInputPlaneToTensorInputOffset(itemID.get_global_id(1));
     for (size_t i = itemID.get_local_id(0); i < num_input; i += itemID.get_local_range()[0]) {
       const size_t local_index = i + plane_kernel_offset;
       const size_t tensor_index =
           plane_tensor_offset + indexMapper.mapGpuInputKernelToTensorInputOffset(i + input_offset);
       local_acc[local_index] =
           (((i + input_offset) < (input_range[0] + kernelSize - 1)) && itemID.get_global_id(1) < input_range[1])
               ? device_evaluator.coeff(tensor_index)
               : CoeffReturnType(0);
     }
     itemID.barrier(cl::sycl::access::fence_space::local_space);
     // calculate the convolution // output start x
     const size_t first_output_start = itemID.get_group(0) * (itemID.get_local_range()[0]);
     if (boundary_check(itemID.get_global_id() < input_range)) {
       CoeffReturnType result = static_cast<CoeffReturnType>(0);
       const size_t index = plane_kernel_offset + itemID.get_local_id(0);
       for (size_t k = 0; k < kernelSize; ++k) {
         result += (local_acc[k + index] * kernel_ptr[k]);
       }
       const size_t tensor_index =
           indexMapper.mapGpuOutputPlaneToTensorOutputOffset(itemID.get_global_id(1)) +
           indexMapper.mapGpuOutputKernelToTensorOutputOffset(itemID.get_local_id(0) + first_output_start);
       buffer_ptr[tensor_index] = result;
     }
   }
References i, k, Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapGpuInputKernelToTensorInputOffset(), Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapGpuInputPlaneToTensorInputOffset(), Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapGpuOutputKernelToTensorOutputOffset(), and Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapGpuOutputPlaneToTensorOutputOffset().
Member Data Documentation
buffer_acc
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > Buffer_accessor Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV1D >::buffer_acc
device_evaluator
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > Evaluator Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV1D >::device_evaluator
indexMapper
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > internal::IndexMapper<Index, InputDims, 1, Evaluator::Layout> Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV1D >::indexMapper
input_range
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > const cl::sycl::range<2> Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV1D >::input_range
kernel_filter
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > Kernel_accessor Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV1D >::kernel_filter
kernelSize
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > const size_t Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV1D >::kernelSize
local_acc
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > Local_accessor Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV1D >::local_acc
The documentation for this struct was generated from the following file:
TensorConvolutionSycl.h