MercuryDPM: MembraneDemo.cpp File Reference
MembraneDemo.cpp File Reference
#include <Mercury3D.h>
#include <Species/HertzianViscoelasticMindlinSpecies.h>
#include <Walls/Membrane/Membrane.h>
#include <climits>
Classes
class MembraneDemo
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc , char ** argv)
 {
   MembraneDemo problem;
   problem.setTimeMax(3.0);
   problem.setGravity(Vec3D(0.0,0.0,-9.81));
   /* Make sure to add an (unique) name here */
   problem.setName("MembraneDemo");
   problem.setFileType(FileType::ONE_FILE);
   //Add any configuration which is modified often below...
   problem.setTimeStep(1e-5);
   problem.setSaveCount(floor(0.01/problem.getTimeStep()));
   if (helpers::readFromCommandLine(argc, argv, "-vtk", true))
   {
       problem.setParticlesWriteVTK(true);
       // Write one file per timestep
       problem.wallHandler.setWriteVTK(FileType::MULTIPLE_FILES);
   }
   problem.setNumberOfOMPThreads(helpers::readFromCommandLine(argc, argv, "-omp",1));
   problem.random.setRandomSeed(helpers::readFromCommandLine(argc, argv, "-seed",1));
   problem.solve(argc,argv);
   return 0;
 }
References e(), Eigen::bfloat16_impl::floor(), MULTIPLE_FILES, ONE_FILE, problem, and helpers::readFromCommandLine().