MercuryDPM: Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > > Struct Template Reference
Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > > Struct Template Reference
#include <CoreEvaluators.h>
Public Types
enum { Factor = (RowFactor == Dynamic || ColFactor == Dynamic) ? Dynamic : RowFactor * ColFactor }
enum { CoeffReadCost = evaluator<ArgTypeNestedCleaned>::CoeffReadCost , LinearAccessMask = XprType::IsVectorAtCompileTime ? LinearAccessBit : 0 , Flags , Alignment = evaluator<ArgTypeNestedCleaned>::Alignment }
typedef Replicate< ArgType, RowFactor, ColFactor > XprType
typedef XprType::CoeffReturnType CoeffReturnType
typedef internal::nested_eval< ArgType, Factor >::type ArgTypeNested
typedef internal::remove_all_t< ArgTypeNested > ArgTypeNestedCleaned
Public Types inherited from Eigen::internal::evaluator_base< Replicate< ArgType, RowFactor, ColFactor > >
enum
typedef traits< Replicate< ArgType, RowFactor, ColFactor > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE unary_evaluator (const XprType &replicate)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType packet (Index index) const
Public Member Functions inherited from Eigen::internal::evaluator_base< Replicate< ArgType, RowFactor, ColFactor > >
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE evaluator_base ()=default
Protected Attributes
const ArgTypeNested m_arg
evaluator< ArgTypeNestedCleaned > m_argImpl
const variable_if_dynamic< Index, ArgType::RowsAtCompileTime > m_rows
const variable_if_dynamic< Index, ArgType::ColsAtCompileTime > m_cols
Member Typedef Documentation
ArgTypeNested
template<typename ArgType , int RowFactor, int ColFactor> typedef internal::nested_eval<ArgType, Factor>::type Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >::ArgTypeNested
ArgTypeNestedCleaned
template<typename ArgType , int RowFactor, int ColFactor> typedef internal::remove_all_t<ArgTypeNested> Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >::ArgTypeNestedCleaned
CoeffReturnType
template<typename ArgType , int RowFactor, int ColFactor> typedef XprType::CoeffReturnType Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >::CoeffReturnType
XprType
template<typename ArgType , int RowFactor, int ColFactor> typedef Replicate<ArgType, RowFactor, ColFactor> Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >::XprType
Member Enumeration Documentation
anonymous enum
template<typename ArgType , int RowFactor, int ColFactor> anonymous enum
Enumerator
Factor
 { Factor = (RowFactor == Dynamic || ColFactor == Dynamic) ? Dynamic : RowFactor * ColFactor };
anonymous enum
template<typename ArgType , int RowFactor, int ColFactor> anonymous enum
Enumerator
CoeffReadCost
LinearAccessMask
Flags
Alignment
        {
     CoeffReadCost = evaluator<ArgTypeNestedCleaned>::CoeffReadCost,
     LinearAccessMask = XprType::IsVectorAtCompileTime ? LinearAccessBit : 0,
     Flags = (evaluator<ArgTypeNestedCleaned>::Flags & (HereditaryBits | LinearAccessMask) & ~RowMajorBit) |
             (traits<XprType>::Flags & RowMajorBit),
     Alignment = evaluator<ArgTypeNestedCleaned>::Alignment
   };
Constructor & Destructor Documentation
unary_evaluator()
template<typename ArgType , int RowFactor, int ColFactor> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >::unary_evaluator (const XprType & replicate) inline explicit
       : m_arg(replicate.nestedExpression()),
         m_argImpl(m_arg),
         m_rows(replicate.nestedExpression().rows()),
         m_cols(replicate.nestedExpression().cols()) {}
Member Function Documentation
coeff() [1/2]
template<typename ArgType , int RowFactor, int ColFactor> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >::coeff (Index index) const inline
{
     // try to avoid using modulo; this is a pure optimization strategy
     const Index actual_index = internal::traits<XprType>::RowsAtCompileTime == 1
                                    ? (ColFactor == 1 ? index : index % m_cols.value())
                                    : (RowFactor == 1 ? index : index % m_rows.value());
     return m_argImpl.coeff(actual_index);
   }
coeff() [2/2]
template<typename ArgType , int RowFactor, int ColFactor> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >::coeff (Index row, Index col) const inline
{
     // try to avoid using modulo; this is a pure optimization strategy
     const Index actual_row = internal::traits<XprType>::RowsAtCompileTime == 1 ? 0
                              : RowFactor == 1                                  ? row
                                                                                : row % m_rows.value();
     const Index actual_col = internal::traits<XprType>::ColsAtCompileTime == 1 ? 0
                              : ColFactor == 1                                  ? col
                                                                                : col % m_cols.value();
     return m_argImpl.coeff(actual_row, actual_col);
   }
References col(), and row().
packet() [1/2]
template<typename ArgType , int RowFactor, int ColFactor> template<int LoadMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >::packet (Index index) const inline
{
     const Index actual_index = internal::traits<XprType>::RowsAtCompileTime == 1
                                    ? (ColFactor == 1 ? index : index % m_cols.value())
                                    : (RowFactor == 1 ? index : index % m_rows.value());
     return m_argImpl.template packet<LoadMode, PacketType>(actual_index);
   }
packet() [2/2]
template<typename ArgType , int RowFactor, int ColFactor> template<int LoadMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >::packet (Index row, Index col) const inline
{
     const Index actual_row = internal::traits<XprType>::RowsAtCompileTime == 1 ? 0
                              : RowFactor == 1                                  ? row
                                                                                : row % m_rows.value();
     const Index actual_col = internal::traits<XprType>::ColsAtCompileTime == 1 ? 0
                              : ColFactor == 1                                  ? col
                                                                                : col % m_cols.value();
     return m_argImpl.template packet<LoadMode, PacketType>(actual_row, actual_col);
   }
References col(), and row().
Member Data Documentation
m_arg
template<typename ArgType , int RowFactor, int ColFactor> const ArgTypeNested Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >::m_arg protected
m_argImpl
template<typename ArgType , int RowFactor, int ColFactor> evaluator<ArgTypeNestedCleaned> Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >::m_argImpl protected
m_cols
template<typename ArgType , int RowFactor, int ColFactor> const variable_if_dynamic<Index, ArgType::ColsAtCompileTime> Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >::m_cols protected
m_rows
template<typename ArgType , int RowFactor, int ColFactor> const variable_if_dynamic<Index, ArgType::RowsAtCompileTime> Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >::m_rows protected
The documentation for this struct was generated from the following file:
CoreEvaluators.h