MercuryDPM: PlanarWave Namespace Reference
PlanarWave Namespace Reference
Functions
std::complex< double > I (0.0, 1.0)
Imaginary unit.
void get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector of size 2, containing real and imag parts.
void plot ()
Plot.
Variables
unsigned N_terms =100
Number of terms in series.
double K =3.0*MathematicalConstants::Pi
Wave number.
Detailed Description
Namespace to test representation of planar wave in spherical polars
////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// Namespace to test representation of planar wave in spherical polars
Function Documentation
get_exact_u()
void PlanarWave::get_exact_u (const Vector< double > & x, Vector< double > & u)
Exact solution as a Vector of size 2, containing real and imag parts.
  {
   // Switch to spherical coordinates
   double R=sqrt(x[0]*x[0]+x[1]*x[1]);
   double theta;
   theta=atan2(x[0],x[1]);
   // Argument for Bessel/Hankel functions
   double kr = K*R;
   // Need half-order Bessel functions
   double bessel_offset=0.5;
   // Evaluate Bessel/Hankel functions
   Vector<double> jv(N_terms);
   Vector<double> yv(N_terms);
   Vector<double> djv(N_terms);
   Vector<double> dyv(N_terms);
   double order_max_in=double(N_terms-1)+bessel_offset;
   double order_max_out=0;
   // This function returns vectors containing
   // J_k(x), Y_k(x) and their derivatives
   // up to k=order_max, with k increasing in
   // integer increments starting with smallest
   // positive value. So, e.g. for order_max=3.5
   // jv[0] contains J_{1/2}(x),
   // jv[1] contains J_{3/2}(x),
   // jv[2] contains J_{5/2}(x),
   // jv[3] contains J_{7/2}(x).
   CRBond_Bessel::bessjyv(order_max_in,
                          kr,
                          order_max_out,
                          &jv[0],&yv[0],
                          &djv[0],&dyv[0]);
   // Assemble  exact solution (actually no need to add terms
   // below i=N_fourier as Legendre polynomial would be zero anyway)
   complex<double> u_ex(0.0,0.0);
   for(unsigned i=0;i<N_terms;i++)
    {
     //Associated_legendre_functions
     double p=Legendre_functions_helper::plgndr2(i,0,cos(theta));
     // Set exact solution
     u_ex+=(2.0*i+1.0)*pow(I,i)*
      sqrt(MathematicalConstants::Pi/(2.0*kr))*jv[i]*p;
    }
   // Get the real & imaginary part of the result
   u[0]=u_ex.real();
   u[1]=u_ex.imag();
  }//end of get_exact_u
References atan2(), CRBond_Bessel::bessjyv(), cos(), i, I, K, ProblemParameters::N_terms, p, oomph::MathematicalConstants::Pi, oomph::Legendre_functions_helper::plgndr2(), Eigen::bfloat16_impl::pow(), R, sqrt(), BiharmonicTestFunctions2::theta, and plotDoE::x.
I()
std::complex< double > PlanarWave::I (0. 0, 1. 0)
Imaginary unit.
plot()
void PlanarWave::plot ()
Plot.
  {
   unsigned nr=20;
   unsigned nz=100;
   unsigned nt=40;
   ofstream some_file("planar_wave.dat");
   for (unsigned i_t=0;i_t<nt;i_t++)
    {
     double t=2.0*MathematicalConstants::Pi*double(i_t)/double(nt-1);
     some_file << "ZONE I="<< nz << ", J="<< nr << std::endl;
     Vector<double> x(2);
     Vector<double> u(2);
     for (unsigned i=0;i<nr;i++)
      {
       x[0]=0.001+double(i)/double(nr-1);
       for (unsigned j=0;j<nz;j++)
        {
         x[1]=double(j)/double(nz-1);
         get_exact_u(x,u);
         complex<double> uu=complex<double>(u[0],u[1])*exp(-I*t);
         some_file << x[0] << " " << x[1] << " "
                   << uu.real() << " " << uu.imag() << "\n";
        }
      }
    }
  }
References Eigen::bfloat16_impl::exp(), ProblemParameters::get_exact_u(), i, I, j, Mesh_Parameters::nz, oomph::MathematicalConstants::Pi, plotPSD::t, and plotDoE::x.
Referenced by oomph::MGSolver< DIM >::interpolation_self_test(), oomph::FiniteElement::output_paraview(), oomph::MGSolver< DIM >::restriction_self_test(), oomph::QElement< 1, NNODE_1D >::write_paraview_output_offset_information(), oomph::QElement< 2, NNODE_1D >::write_paraview_output_offset_information(), oomph::QElement< 3, NNODE_1D >::write_paraview_output_offset_information(), and oomph::TElement< 1, NNODE_1D >::write_paraview_output_offset_information().
Variable Documentation
K
double PlanarWave::K =3.0*MathematicalConstants::Pi
Wave number.
Referenced by oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::add_additional_residual_contributions_interface(), bench_prod(), oomph::IsotropicStrainEnergyFunctionConstitutiveLaw::calculate_second_piola_kirchhoff_stress(), Eigen::internal::visitor_impl< Visitor, Derived, UnrollCount, Vectorize, false, ShortCircuitEvaluation >::CanVectorize(), Eigen::internal::visitor_impl< Visitor, Derived, UnrollCount, Vectorize, true, ShortCircuitEvaluation >::CanVectorize(), check_product(), WearableNurbsWall::computeWear(), WearableTriangulatedWall::computeWear(), Eigen::internal::copyBToRowMajor(), oomph::SolubleSurfactantTransportInterfaceElement::dflux_from_bulk_dC(), oomph::SolubleSurfactantTransportInterfaceElement::dflux_from_bulk_dC_bulk(), EIGEN_DECLARE_TEST(), oomph::SolubleSurfactantTransportInterfaceElement::flux_from_bulk(), Eigen::internal::gemmKernel(), get_exact_u(), Eigen::TensorEvaluator< const TensorContractionOp< Indices, LeftArgType, RightArgType, OutputKernelType >, Eigen::SyclDevice >::launchSC(), main(), SmallMatrix< numberOfRows, numberOfColumns >::operator*(), Eigen::internal::lhs_process_fraction_of_packet< nr, LhsProgress, RhsProgress, LhsScalar, RhsScalar, ResScalar, AccPacket, LhsPacket, RhsPacket, ResPacket, GEBPTraits, LinearMapper, DataMapper >::peeled_kc_onestep(), Eigen::internal::lhs_process_one_packet< nr, LhsProgress, RhsProgress, LhsScalar, RhsScalar, ResScalar, AccPacket, LhsPacket, RhsPacket, ResPacket, GEBPTraits, LinearMapper, DataMapper >::peeled_kc_onestep(), loop_on_k< M, N, K >::run(), loop_on_n< M, N, K, Scalar, Mode >::run(), Eigen::internal::visitor_impl< Visitor, Derived, UnrollCount, Vectorize, false, ShortCircuitEvaluation >::run(), Eigen::internal::visitor_impl< Visitor, Derived, UnrollCount, Vectorize, true, ShortCircuitEvaluation >::run(), test_linear_but_not_vectorizable(), Eigen::internal::triSolveKernel(), and Eigen::internal::triSolveKernelLxK().
N_terms
unsigned PlanarWave::N_terms =100
Number of terms in series.
Referenced by oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::setup_gamma().