MercuryDPM: BiharmonicTestFunctions1 Namespace Reference
BiharmonicTestFunctions1 Namespace Reference
Functions
void u_NE (const double &s, double &u)
void dudn_NE (const double &s, double &dudn)
void u_SW (const double &s, double &u)
void dudn_SW (const double &s, double &dudn)
void surface_load (const Vector< double > &x, double &f)
void flux1_NE (const double &s, double &flux1)
void flux0_NE (const double &s, double &flux0)
void solution (const Vector< double > &x, Vector< double > &u)
Function Documentation
dudn_NE()
void BiharmonicTestFunctions1::dudn_NE (const double & s, double & dudn)
  {
   double x = (s+1) / 2;
   dudn = 3*x*x*x;
  }
References s, and plotDoE::x.
Referenced by BiharmonicTestProblem1::BiharmonicTestProblem1().
dudn_SW()
void BiharmonicTestFunctions1::dudn_SW (const double & s, double & dudn)
  {
   dudn = 0;
  }
Referenced by BiharmonicTestProblem1::BiharmonicTestProblem1().
flux0_NE()
void BiharmonicTestFunctions1::flux0_NE (const double & s, double & flux0)
  {
   double x = (s+1) / 2;
   flux0 = 6*(x*x*x + x);
  }
References s, and plotDoE::x.
flux1_NE()
void BiharmonicTestFunctions1::flux1_NE (const double & s, double & flux1)
  {
   double x = (s+1) / 2;
   flux1 = 6*x*x*x + 18*x;
  }
References s, and plotDoE::x.
solution()
void BiharmonicTestFunctions1::solution (const Vector< double > & x, Vector< double > & u)
  {
   u[0] = x[0]*x[0]*x[0]*x[1]*x[1]*x[1];
  }
References plotDoE::x.
Referenced by Global_Parameters::analytic_solution1(), Global_Parameters::analytic_solution2(), oomph::HelmholtzSmoother::check_validity_of_solve_helper_inputs(), oomph::Smoother::check_validity_of_solve_helper_inputs(), oomph::ComplexDampedJacobi< MATRIX >::complex_smoother_solve(), oomph::ComplexGMRES< MATRIX >::complex_smoother_solve(), oomph::ComplexDampedJacobi< MATRIX >::complex_solve_helper(), oomph::ComplexGMRES< MATRIX >::complex_solve_helper(), oomph::HypreInterface::hypre_solve(), main(), oomph::GMRESBlockPreconditioner::preconditioner_solve(), oomph::HypreSolver::resolve(), oomph::TrilinosAztecOOSolver::resolve(), run_it(), oomph::DampedJacobi< MATRIX >::smoother_solve(), oomph::CG< MATRIX >::solve(), oomph::BiCGStab< MATRIX >::solve(), oomph::GS< MATRIX >::solve(), oomph::GS< CRDoubleMatrix >::solve(), oomph::DampedJacobi< MATRIX >::solve(), oomph::GMRES< MATRIX >::solve(), oomph::AugmentedProblemGMRES::solve(), oomph::HypreSolver::solve(), oomph::TrilinosAztecOOSolver::solve(), oomph::CG< MATRIX >::solve_helper(), oomph::BiCGStab< MATRIX >::solve_helper(), oomph::GS< MATRIX >::solve_helper(), oomph::GS< CRDoubleMatrix >::solve_helper(), oomph::DampedJacobi< MATRIX >::solve_helper(), oomph::GMRES< MATRIX >::solve_helper(), oomph::AugmentedProblemGMRES::solve_helper(), oomph::HelmholtzGMRESMG< MATRIX >::solve_helper(), and oomph::HelmholtzFGMRESMG< MATRIX >::solve_helper().
surface_load()
void BiharmonicTestFunctions1::surface_load (const Vector< double > & x, double & f)
  {
    //f = 1.0;
    f = 72*x[0]*x[1];
  }
References f(), and plotDoE::x.
u_NE()
void BiharmonicTestFunctions1::u_NE (const double & s, double & u)
  {
   double x = (s+1) / 2;
   u = x*x*x;
  }
References s, and plotDoE::x.
Referenced by BiharmonicTestProblem1::BiharmonicTestProblem1().
u_SW()
void BiharmonicTestFunctions1::u_SW (const double & s, double & u)
  {
   u = 0;
  }
Referenced by BiharmonicTestProblem1::BiharmonicTestProblem1().