MercuryDPM: unstructured_two_d_solid.cc File Reference
solid/unstructured_solid/unstructured_two_d_solid.cc File Reference
#include "generic.h"
#include "solid.h"
#include "constitutive.h"
#include "meshes/triangle_mesh.h"
Classes
class ElasticTriangleMesh< ELEMENT >
Triangle-based mesh upgraded to become a (pseudo-) solid mesh.
class UnstructuredSolidProblem< ELEMENT, MESH >
Unstructured solid problem.
Namespaces
Global_Physical_Variables
Global variables.
Functions
void Global_Physical_Variables::gravity (const double &time, const Vector< double > &xi, Vector< double > &b)
Non-dimensional gravity as body force.
void Global_Physical_Variables::constant_pressure (const Vector< double > &xi, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction)
Constant pressure load.
int main ()
Demonstrate how to solve an unstructured solid problem.
Function Documentation
main()
int main ()
Demonstrate how to solve an unstructured solid problem.
 {
  // Label for output
  DocInfo doc_info;
  // Output directory
  doc_info.set_directory("RESLT");
  // Create generalised Hookean constitutive equations
  Global_Physical_Variables::Constitutive_law_pt =
   new GeneralisedHookean(&Global_Physical_Variables::Nu);
  {
   std::cout << "Running with pure displacement formulation\n";
   //Set up the problem
   UnstructuredSolidProblem<TPVDElement<2,3> > problem;
   //Output initial configuration
   problem.doc_solution(doc_info);
   doc_info.number()++;
   // Parameter study
   Global_Physical_Variables::Gravity=2.0e-4;
   Global_Physical_Variables::P=0.0;
   double pressure_increment=-1.0e-4;
   unsigned nstep=2; // 10;
   for (unsigned istep=0;istep<nstep;istep++)
    {
     // Solve the problem
     problem.newton_solve();
     //Output solution
     problem.doc_solution(doc_info);
     doc_info.number()++;
     // Bump up suction
     Global_Physical_Variables::P+=pressure_increment;
    }
  } //end_displacement_formulation
  //Repeat for displacement/pressure formulation
  {
   std::cout << "Running with pressure/displacement formulation\n";
   // Change output directory
   doc_info.set_directory("RESLT_pres_disp");
   //Reset doc_info number
   doc_info.number() = 0;
   //Set up the problem
   UnstructuredSolidProblem<TPVDElementWithContinuousPressure<2> > problem;
   //Output initial configuration
   problem.doc_solution(doc_info);
   doc_info.number()++;
   // Parameter study
   Global_Physical_Variables::Gravity=2.0e-4;
   Global_Physical_Variables::P=0.0;
   double pressure_increment=-1.0e-4;
   unsigned nstep=2;
   for (unsigned istep=0;istep<nstep;istep++)
    {
     // Solve the problem
     problem.newton_solve();
     //Output solution
     problem.doc_solution(doc_info);
     doc_info.number()++;
     // Bump up suction
     Global_Physical_Variables::P+=pressure_increment;
    }
  }
  //Repeat for displacement/pressure formulation
  //enforcing incompressibility
  {
   std::cout <<
    "Running with pressure/displacement formulation (incompressible) \n";
   // Change output directory
   doc_info.set_directory("RESLT_pres_disp_incomp");
   //Reset doc_info number
   doc_info.number() = 0;
   //Set up the problem
   UnstructuredSolidProblem<TPVDElementWithContinuousPressure<2> > problem;
   //Loop over all elements and set incompressibility flag
   {
    const unsigned n_element = problem.mesh_pt()->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      //Cast the element to the equation base of our 2D elastiticy elements
      PVDEquationsWithPressure<2> *cast_el_pt =
       dynamic_cast<PVDEquationsWithPressure<2>*>(
        problem.mesh_pt()->element_pt(e));
      //If the cast was successful, it's a bulk element,
      //so set the incompressibilty flag
      if(cast_el_pt) {cast_el_pt->set_incompressible();}
     }
   }
   //Output initial configuration
   problem.doc_solution(doc_info);
   doc_info.number()++;
   // Parameter study
   Global_Physical_Variables::Gravity=2.0e-4;
   Global_Physical_Variables::P=0.0;
   double pressure_increment=-1.0e-4;
   unsigned nstep=2;
   for (unsigned istep=0;istep<nstep;istep++)
    {
     // Solve the problem
     problem.newton_solve();
     //Output solution
     problem.doc_solution(doc_info);
     doc_info.number()++;
     // Bump up suction
     Global_Physical_Variables::P+=pressure_increment;
    }
  }
 } // end main
References Global_Physical_Variables::Constitutive_law_pt, e(), Global_Physical_Variables::Gravity, Global_Physical_Variables::Nu, oomph::DocInfo::number(), Global_Physical_Variables::P, problem, oomph::DocInfo::set_directory(), and oomph::PVDEquationsWithPressure< DIM >::set_incompressible().