MercuryDPM: Eigen::internal::dhs_pack< double, DataMapper, Packet2d, StorageOrder, PanelMode, true > Struct Template Reference
Eigen::internal::dhs_pack< double, DataMapper, Packet2d, StorageOrder, PanelMode, true > Struct Template Reference
#include <MatrixProduct.h>
Public Member Functions
template<Index n>
EIGEN_ALWAYS_INLINE void dhs_copy (double *blockA, const DataMapper &lhs2, Index &i, Index &ri, Index depth, const Index vectorSize)
EIGEN_STRONG_INLINE void operator() (double *blockA, const DataMapper &lhs, Index depth, Index rows, Index stride, Index offset)
Member Function Documentation
dhs_copy()
template<typename DataMapper , int StorageOrder, bool PanelMode> template<Index n> EIGEN_ALWAYS_INLINE void Eigen::internal::dhs_pack< double, DataMapper, Packet2d, StorageOrder, PanelMode, true >::dhs_copy (double * blockA, const DataMapper & lhs2, Index & i, Index & ri, Index depth, const Index vectorSize) inline
{
     PacketBlock<Packet2d, 2> block[n];
     for (; i + n * vectorSize <= depth; i += n * vectorSize) {
       for (Index k = 0; k < n; k++) {
         if (StorageOrder == RowMajor) {
           block[k].packet[0] = lhs2.template loadPacket<Packet2d>(0, i + k * vectorSize);
           block[k].packet[1] = lhs2.template loadPacket<Packet2d>(1, i + k * vectorSize);
         } else {
           block[k].packet[0] = lhs2.template loadPacket<Packet2d>(0, i + k * vectorSize + 0);
           block[k].packet[1] = lhs2.template loadPacket<Packet2d>(0, i + k * vectorSize + 1);
         }
       }
       if (StorageOrder == RowMajor) {
         for (Index k = 0; k < n; k++) {
           ptranspose(block[k]);
         }
       }
       for (Index k = 0; k < n; k++) {
         storeBlock<double, Packet2d, 2>(blockA + ri + k * 2 * vectorSize, block[k]);
       }
       ri += n * 2 * vectorSize;
     }
   }
References block(), i, k, n, Eigen::internal::ptranspose(), and Eigen::RowMajor.
operator()()
template<typename DataMapper , int StorageOrder, bool PanelMode> EIGEN_STRONG_INLINE void Eigen::internal::dhs_pack< double, DataMapper, Packet2d, StorageOrder, PanelMode, true >::operator() (double * blockA, const DataMapper & lhs, Index depth, Index rows, Index stride, Index offset) inline
{
     const Index vectorSize = quad_traits<double>::vectorsize;
     Index ri = 0, j = 0;
     for (; j + vectorSize <= rows; j += vectorSize) {
       const DataMapper lhs2 = lhs.getSubMapper(j, 0);
       Index i = 0;
       if (PanelMode) ri += vectorSize * offset;
       dhs_copy<4>(blockA, lhs2, i, ri, depth, vectorSize);
       dhs_copy<2>(blockA, lhs2, i, ri, depth, vectorSize);
       dhs_copy<1>(blockA, lhs2, i, ri, depth, vectorSize);
       for (; i < depth; i++) {
         if (StorageOrder == RowMajor) {
           blockA[ri + 0] = lhs2(0, i);
           blockA[ri + 1] = lhs2(1, i);
         } else {
           Packet2d lhsV = lhs2.template loadPacket<Packet2d>(0, i);
           pstore<double>(blockA + ri, lhsV);
         }
         ri += vectorSize;
       }
       if (PanelMode) ri += vectorSize * (stride - offset - depth);
     }
     if (j < rows) {
       if (PanelMode) ri += offset * (rows - j);
       for (Index i = 0; i < depth; i++) {
         Index k = j;
         for (; k < rows; k++) {
           blockA[ri] = lhs(k, i);
           ri += 1;
         }
       }
     }
   }
References i, j, k, Eigen::internal::pstore< double >(), Eigen::RowMajor, and rows.
The documentation for this struct was generated from the following file:
MatrixProduct.h