MercuryDPM: Eigen::ReturnByValue< Derived > Class Template Reference
Eigen::ReturnByValue< Derived > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
#include <ReturnByValue.h>
Classes
class Unusable
Public Types
typedef internal::traits< Derived >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Public Member Functions
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Member Typedef Documentation
Base
template<typename Derived > typedef internal::dense_xpr_base<ReturnByValue>::type Eigen::ReturnByValue< Derived >::Base
ReturnType
template<typename Derived > typedef internal::traits<Derived>::ReturnType Eigen::ReturnByValue< Derived >::ReturnType
Member Function Documentation
coeff() [1/2]
template<typename Derived > const Unusable& Eigen::ReturnByValue< Derived >::coeff (Index) const inline
 { return *reinterpret_cast<const Unusable*>(this); }
coeff() [2/2]
template<typename Derived > const Unusable& Eigen::ReturnByValue< Derived >::coeff (Index , Index) const inline
 { return *reinterpret_cast<const Unusable*>(this); }
coeffRef() [1/2]
template<typename Derived > Unusable& Eigen::ReturnByValue< Derived >::coeffRef (Index) inline
 { return *reinterpret_cast<Unusable*>(this); }
coeffRef() [2/2]
template<typename Derived > Unusable& Eigen::ReturnByValue< Derived >::coeffRef (Index , Index) inline
 { return *reinterpret_cast<Unusable*>(this); }
cols()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::ReturnByValue< Derived >::cols () const inline
{
     return static_cast<const Derived*>(this)->cols();
   }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), Eigen::PlainObjectBase< Derived >::_init1(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::PlainObjectBase< Derived >::PlainObjectBase(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
evalTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::ReturnByValue< Derived >::evalTo (Dest & dst) const inline
{
     static_cast<const Derived*>(this)->evalTo(dst);
   }
Referenced by Eigen::PlainObjectBase< Derived >::_init1(), Eigen::internal::evaluator< ReturnByValue< Derived > >::evaluator(), Eigen::ArrayBase< ArrayWrapper< ExpressionType > >::lazyAssign(), Eigen::DenseBase< Derived >::operator=(), Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >::operator=(), Eigen::SparseMatrixBase< Derived >::operator=(), Eigen::PlainObjectBase< Derived >::PlainObjectBase(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::SparseMatrix(), and Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >::Transform().
rows()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::ReturnByValue< Derived >::rows () const inline
{
     return static_cast<const Derived*>(this)->rows();
   }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), Eigen::PlainObjectBase< Derived >::_init1(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::PlainObjectBase< Derived >::PlainObjectBase(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
The documentation for this class was generated from the following file:
ReturnByValue.h