MercuryDPM: Chutebelt Class Reference
Chutebelt Class Reference
if you restart this code the third argument will be used as the number of large particles to add and the forth the number of small.
Public Member Functions
Chutebelt ()
void setupInitialConditions () override
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
void actionsOnRestart () override
A virtual function where the users can add extra code which is executed only when the code is restarted.
void actionsAfterTimeStep () override
A virtual function which allows to define operations to be executed after time step.
void actionsBeforeTimeStep () override
A virtual function which allows to define operations to be executed before the new time step.
void set_beltSpeed (double new_speed)
void set_particle_numbers (int new_num_small, int new_num_large)
void set_particle_numbers (int new_num_small)
void set_radiusLarge (double new_large_radius)
void set_particle_number_volRatio (double new_volume_ratio)
Public Member Functions inherited from Chute
Chute ()
This is the default constructor. All it does is set sensible defaults.
Chute (const DPMBase &other)
Copy constructor, converts an existing DPMBase problem into a Chute problem.
Chute (const MercuryBase &other)
Copy constructor, converts an existing MercuryBase problem into a Chute problem.
Chute (const Mercury3D &other)
Copy constructor, converts an existing Mercury3D problem into a Chute problem.
Chute (const Chute &other)
Default copy constructor.
void constructor ()
This is the actual constructor METHOD; it is called by all constructors above (except the default copy constructor).
bool readNextArgument (int &i, int argc, char *argv[]) override
This method can be used for reading object properties from a string.
void setupSideWalls ()
Creates chute side walls (either solid or periodic)
void makeChutePeriodic ()
This makes the chute periodic in Y.
bool getIsPeriodic () const
Returns whether the chute is periodic in Y.
void setupInitialConditions () override
Creates bottom, side walls and a particle insertion boundary.
void read (std::istream &is, ReadOptions opt=ReadOptions::ReadAll) override
Reads all chute properties from an istream.
void write (std::ostream &os, bool writeAllParticles=true) const override
This function writes the Chute properties to an ostream, and adds the properties of ALL chute particles as well.
void setFixedParticleRadius (Mdouble fixedParticleRadius)
Sets the particle radius of the fixed particles which constitute the (rough) chute bottom.
Mdouble getFixedParticleRadius () const
Returns the particle radius of the fixed particles which constitute the (rough) chute bottom.
void setFixedParticleSpacing (Mdouble fixedParticleSpacing)
Sets the spacing of the fixed particles which constitute the (rough) chute bottom; used in triangular packing only.
Mdouble getFixedParticleSpacing () const
Returns the particle radius of the fixed particles which constitute the (rough) chute bottom; used in triangular packing only.
void setRoughBottomType (RoughBottomType roughBottomType)
Sets the type of rough bottom of the chute.
void setRoughBottomType (std::string roughBottomTypeString)
Sets the type of rough bottom of the chute, using a string with the EXACT enum type as input.
RoughBottomType getRoughBottomType () const
Returns the type of (rough) bottom of the chute.
void setChuteAngle (Mdouble chuteAngle)
Sets gravity vector according to chute angle (in degrees)
void setChuteAngleAndMagnitudeOfGravity (Mdouble chuteAngle, Mdouble gravity)
Sets gravity vector according to chute angle (in degrees)
Mdouble getChuteAngle () const
Returns the chute angle (in radians)
Mdouble getChuteAngleDegrees () const
Returns the chute angle (in degrees)
void setMaxFailed (unsigned int maxFailed)
Sets the number of times a particle will be tried to be added to the insertion boundary.
unsigned int getMaxFailed () const
Returns the number of times a particle will be tried to be added to the insertion boundary.
void setInflowParticleRadius (Mdouble inflowParticleRadius)
Sets the radius of the inflow particles to a single one (i.e. ensures a monodisperse inflow).
void setInflowParticleRadius (Mdouble minInflowParticleRadius, Mdouble maxInflowParticleRadius)
Sets the minimum and maximum radius of the inflow particles.
void setMinInflowParticleRadius (Mdouble minInflowParticleRadius)
sets the minimum radius of inflow particles
void setMaxInflowParticleRadius (Mdouble maxInflowParticleRadius)
Sets the maximum radius of inflow particles.
Mdouble getInflowParticleRadius () const
Returns the average radius of inflow particles.
Mdouble getMinInflowParticleRadius () const
returns the minimum radius of inflow particles
Mdouble getMaxInflowParticleRadius () const
Returns the maximum radius of inflow particles.
void setInflowHeight (Mdouble inflowHeight)
Sets maximum inflow height (Z-direction)
Mdouble getInflowHeight () const
Returns the maximum inflow height (Z-direction)
void setInflowVelocity (Mdouble inflowVelocity)
Sets the average inflow velocity.
Mdouble getInflowVelocity () const
Returns the average inflow velocity.
void setInflowVelocityVariance (Mdouble inflowVelocityVariance)
Sets the inflow velocity variance.
Mdouble getInflowVelocityVariance () const
Returns the inflow velocity variance.
void setChuteWidth (Mdouble chuteWidth)
Sets the chute width (Y-direction)
Mdouble getChuteWidth () const
Returns the chute width (Y-direction)
virtual void setChuteLength (Mdouble chuteLength)
Sets the chute length (X-direction)
Mdouble getChuteLength () const
Returns the chute length (X-direction)
void setInsertionBoundary (InsertionBoundary *insertionBoundary)
Sets the chute insertion boundary.
Public Member Functions inherited from Mercury3D
Mercury3D ()
This is the default constructor. All it does is set sensible defaults.
Mercury3D (const DPMBase &other)
Copy-constructor for creates an Mercury3D problem from an existing MD problem.
Mercury3D (const Mercury3D &other)
Copy-constructor.
void constructor ()
Function that sets the SystemDimension and ParticleDimension to 3.
std::vector< BaseParticle * > hGridFindParticleContacts (const BaseParticle *obj) override
Returns all particles that have a contact with a given particle.
Public Member Functions inherited from MercuryBase
MercuryBase ()
This is the default constructor. It sets sensible defaults.
~MercuryBase () override
This is the default destructor.
MercuryBase (const MercuryBase &mercuryBase)
Copy-constructor.
void constructor ()
This is the actual constructor, it is called do both constructors above.
void hGridActionsBeforeTimeLoop () override
This sets up the broad phase information, has to be done at this stage because it requires the particle size.
void hGridActionsBeforeTimeStep () override
Performs all necessary actions before a time-step, like updating the particles and resetting all the bucket information, etc.
void read (std::istream &is, ReadOptions opt=ReadOptions::ReadAll) override
Reads the MercuryBase from an input stream, for example a restart file.
void write (std::ostream &os, bool writeAllParticles=true) const override
Writes all data into a restart file.
Mdouble getHGridCurrentMaxRelativeDisplacement () const
Returns hGridCurrentMaxRelativeDisplacement_.
Mdouble getHGridTotalCurrentMaxRelativeDisplacement () const
Returns hGridTotalCurrentMaxRelativeDisplacement_.
void setHGridUpdateEachTimeStep (bool updateEachTimeStep)
Sets whether or not the HGrid must be updated every time step.
bool getHGridUpdateEachTimeStep () const final
Gets whether or not the HGrid is updated every time step.
void setHGridMaxLevels (unsigned int HGridMaxLevels)
Sets the maximum number of levels of the HGrid in this MercuryBase.
unsigned int getHGridMaxLevels () const
Gets the maximum number of levels of the HGrid in this MercuryBase.
HGridMethod getHGridMethod () const
Gets whether the HGrid in this MercuryBase is BOTTOMUP or TOPDOWN.
void setHGridMethod (HGridMethod hGridMethod)
Sets the HGridMethod to either BOTTOMUP or TOPDOWN.
HGridDistribution getHGridDistribution () const
Gets how the sizes of the cells of different levels are distributed.
void setHGridDistribution (HGridDistribution hGridDistribution)
Sets how the sizes of the cells of different levels are distributed.
Mdouble getHGridCellOverSizeRatio () const
Gets the ratio of the smallest cell over the smallest particle.
void setHGridCellOverSizeRatio (Mdouble cellOverSizeRatio)
Sets the ratio of the smallest cell over the smallest particle.
bool hGridNeedsRebuilding ()
Gets if the HGrid needs rebuilding before anything else happens.
virtual unsigned int getHGridTargetNumberOfBuckets () const
Gets the desired number of buckets, which is the maximum of the number of particles and 10.
virtual Mdouble getHGridTargetMinInteractionRadius () const
Gets the desired size of the smallest cells of the HGrid.
virtual Mdouble getHGridTargetMaxInteractionRadius () const
Gets the desired size of the largest cells of the HGrid.
bool checkParticleForInteraction (const BaseParticle &P) final
Checks if given BaseParticle has an interaction with a BaseWall or other BaseParticle.
bool checkParticleForInteractionLocal (const BaseParticle &P) final
Checks if the given BaseParticle has an interaction with a BaseWall or other BaseParticles in a local domain.
virtual Mdouble userHGridCellSize (unsigned int level)
Virtual function that enables inheriting classes to implement a function to let the user set the cell size of the HGrid.
void hGridInfo (std::ostream &os=std::cout) const
Writes the info of the HGrid to the screen in a nice format.
Public Member Functions inherited from DPMBase
void constructor ()
A function which initialises the member variables to default values, so that the problem can be solved off the shelf; sets up a basic two dimensional problem which can be solved off the shelf. It is called in the constructor DPMBase().
DPMBase ()
Constructor that calls the "void constructor()".
DPMBase (const DPMBase &other)
Copy constructor type-2.
virtual ~DPMBase ()
virtual destructor
void autoNumber ()
The autoNumber() function calls three functions: setRunNumber(), readRunNumberFromFile() and incrementRunNumberInFile().
std::vector< int > get1DParametersFromRunNumber (int size_x) const
This turns a counter into 1 index, which is a useful feature for performing 1D parameter study. The index run from 1:size_x, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get2DParametersFromRunNumber (int size_x, int size_y) const
This turns a counter into 2 indices which is a very useful feature for performing a 2D study. The indices run from 1:size_x and 1:size_y, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get3DParametersFromRunNumber (int size_x, int size_y, int size_z) const
This turns a counter into 3 indices, which is a useful feature for performing a 3D parameter study. The indices run from 1:size_x, 1:size_y and 1:size_z, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
int launchNewRun (const char *name, bool quick=false)
This launches a code from within this code. Please pass the name of the code to run.
void setRunNumber (int runNumber)
This sets the counter/Run number, overriding the defaults.
int getRunNumber () const
This returns the current value of the counter (runNumber_)
virtual void decompose ()
Sends particles from processorId to the root processor.
void solve ()
The work horse of the code.
void initialiseSolve ()
Beginning of the solve routine, before time stepping.
void finaliseSolve ()
End of the solve routine, after time stepping.
virtual void computeOneTimeStep ()
Performs everything needed for one time step, used in the time-loop of solve().
void checkSettings ()
Checks if the essentials are set properly to go ahead with solving the problem.
void forceWriteOutputFiles ()
Writes output files immediately, even if the current time step was not meant to be written. Also resets the last saved time step.
virtual void writeOutputFiles ()
Writes simulation data to all the main Mercury files: .data, .ene, .fstat, .xballs and .restart (see the Mercury website for more details regarding these files).
void solve (int argc, char *argv[])
The work horse of the code. Can handle flags from the command line.
virtual void writeXBallsScript () const
This writes a script which can be used to load the xballs problem to display the data just generated.
virtual Mdouble getInfo (const BaseParticle &P) const
A virtual function that returns some user-specified information about a particle.
ParticleVtkWriter * getVtkWriter () const
virtual void writeRestartFile ()
Stores all the particle data for current save time step to a "restart" file, which is a file simply intended to store all the information necessary to "restart" a simulation from a given time step (see also MercuryDPM.org for more information on restart files).
void writeDataFile ()
void writeEneFile ()
void writeFStatFile ()
void fillDomainWithParticles (unsigned N=50)
bool readRestartFile (ReadOptions opt=ReadOptions::ReadAll)
Reads all the particle data corresponding to a given, existing . restart file (for more details regarding restart files, refer to the training materials on the MercuryDPM website).Returns true if it is successful, false otherwise.
int readRestartFile (std::string fileName, ReadOptions opt=ReadOptions::ReadAll)
The same as readRestartFile(bool), but also reads all the particle data corresponding to the current saved time step.
virtual BaseWall * readUserDefinedWall (const std::string &type) const
Allows you to read in a wall defined in a Driver directory; see USER/Luca/ScrewFiller.
virtual void readOld (std::istream &is)
Reads all data from a restart file, e.g. domain data and particle data; old version.
bool readDataFile (std::string fileName="", unsigned int format=0)
This allows particle data to be reloaded from data files.
bool readParAndIniFiles (std::string fileName)
Allows the user to read par.ini files (useful to read files produced by the MDCLR simulation code - external to MercuryDPM)
bool readNextDataFile (unsigned int format=0)
Reads the next data file with default format=0. However, one can modify the format based on whether the particle data corresponds to 3D or 2D data- see Visualising data in xballs.
void readNextFStatFile ()
Reads the next fstat file.
bool findNextExistingDataFile (Mdouble tMin, bool verbose=true)
Finds and opens the next data file, if such a file exists.
bool readArguments (int argc, char *argv[])
Can interpret main function input arguments that are passed by the driver codes.
bool checkParticleForInteractionLocalPeriodic (const BaseParticle &P)
void readSpeciesFromDataFile (bool read=true)
void importParticlesAs (ParticleHandler &particleHandler, InteractionHandler &interactionHandler, const ParticleSpecies *species)
Copies particles, interactions assigning species from a local simulation to a global one. Useful for the creation of a cluster.
MERCURYDPM_DEPRECATED File & getDataFile ()
The non const version. Allows one to edit the File::dataFile.
MERCURYDPM_DEPRECATED File & getEneFile ()
The non const version. Allows to edit the File::eneFile.
MERCURYDPM_DEPRECATED File & getFStatFile ()
The non const version. Allows to edit the File::fStatFile.
MERCURYDPM_DEPRECATED File & getRestartFile ()
The non const version. Allows to edit the File::restartFile.
MERCURYDPM_DEPRECATED File & getStatFile ()
The non const version. Allows to edit the File::statFile.
File & getInteractionFile ()
Return a reference to the file InteractionsFile.
MERCURYDPM_DEPRECATED const File & getDataFile () const
The const version. Does not allow for any editing of the File::dataFile.
MERCURYDPM_DEPRECATED const File & getEneFile () const
The const version. Does not allow for any editing of the File::eneFile.
MERCURYDPM_DEPRECATED const File & getFStatFile () const
The const version. Does not allow for any editing of the File::fStatFile.
MERCURYDPM_DEPRECATED const File & getRestartFile () const
The const version. Does not allow for any editing of the File::restartFile.
MERCURYDPM_DEPRECATED const File & getStatFile () const
The const version. Does not allow for any editing of the File::statFile.
const File & getInteractionFile () const
Returns a constant reference to an Interactions file.
const std::string & getName () const
Returns the name of the file. Does not allow to change it though.
void setName (const std::string &name)
Allows to set the name of all the files (ene, data, fstat, restart, stat)
void setName (const char *name)
Calls setName(std::string)
void setSaveCount (unsigned int saveCount)
Sets File::saveCount_ for all files (ene, data, fstat, restart, stat)
void setFileType (FileType fileType)
Sets File::fileType_ for all files (ene, data, fstat, restart, stat)
void setOpenMode (std::fstream::openmode openMode)
Sets File::openMode_ for all files (ene, data, fstat, restart, stat)
void resetFileCounter ()
Resets the file counter for each file i.e. for ene, data, fstat, restart, stat)
void closeFiles ()
Closes all files (ene, data, fstat, restart, stat) that were opened to read or write.
void setVTKOutputDirectory (const std::string &dir)
Sets the output directory of the VTK files.
void setLastSavedTimeStep (unsigned int nextSavedTimeStep)
Sets the next time step for all the files (ene, data, fstat, restart, stat) at which the data is to be written or saved.
Mdouble getTime () const
Returns the current simulation time.
Mdouble getNextTime () const
Returns the current simulation time.
unsigned int getNumberOfTimeSteps () const
Returns the current counter of time-steps, i.e. the number of time-steps that the simulation has undergone so far.
void setTime (Mdouble time)
Sets a new value for the current simulation time.
void setTimeMax (Mdouble newTMax)
Sets a new value for the maximum simulation duration.
Mdouble getTimeMax () const
Returns the maximum simulation duration.
void setLogarithmicSaveCount (Mdouble logarithmicSaveCountBase)
Sets File::logarithmicSaveCount_ for all files (ene, data, fstat, restart, stat)
void setNToWrite (int nToWrite)
set the number of elements to write to the screen
int getNToWrite () const
get the number of elements to write to the
void setRotation (bool rotation)
Sets whether particle rotation is enabled or disabled.
bool getRotation () const
Indicates whether particle rotation is enabled or disabled.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (FileType writeWallsVTK)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (bool)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setInteractionsWriteVTK (bool)
Sets whether interactions are written into a VTK file.
void setParticlesWriteVTK (bool writeParticlesVTK)
Sets whether particles are written in a VTK file.
void setSuperquadricParticlesWriteVTK (bool writeSuperquadricParticlesVTK)
MERCURYDPM_DEPRECATED FileType getWallsWriteVTK () const
Returns whether walls are written in a VTK file.
bool getParticlesWriteVTK () const
Returns whether particles are written in a VTK file.
bool getSuperquadricParticlesWriteVTK () const
Mdouble getXMin () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMin() returns XMin.
Mdouble getXMax () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMax() returns XMax.
Mdouble getYMin () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMin() returns YMin.
Mdouble getYMax () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMax() returns XMax.
Mdouble getZMin () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMin() returns ZMin.
Mdouble getZMax () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMax() returns ZMax.
Mdouble getXCenter () const
Mdouble getYCenter () const
Mdouble getZCenter () const
Vec3D getCenter () const
get center of domain
Vec3D getMin () const
Returns the minimum coordinates of the problem domain.
Vec3D getMax () const
Returns the maximum coordinates of the problem domain.
void setXMin (Mdouble newXMin)
Sets the value of XMin, the lower bound of the problem domain in the x-direction.
void setYMin (Mdouble newYMin)
Sets the value of YMin, the lower bound of the problem domain in the y-direction.
void setZMin (Mdouble newZMin)
Sets the value of ZMin, the lower bound of the problem domain in the z-direction.
void setXMax (Mdouble newXMax)
Sets the value of XMax, the upper bound of the problem domain in the x-direction.
void setYMax (Mdouble newYMax)
Sets the value of YMax, the upper bound of the problem domain in the y-direction.
void setZMax (Mdouble newZMax)
Sets the value of ZMax, the upper bound of the problem domain in the z-direction.
void setMax (const Vec3D &max)
Sets the maximum coordinates of the problem domain.
void setMax (Mdouble, Mdouble, Mdouble)
Sets the maximum coordinates of the problem domain.
void setDomain (const Vec3D &min, const Vec3D &max)
Sets the minimum coordinates of the problem domain.
void setMin (const Vec3D &min)
Sets the minimum coordinates of the problem domain.
void setMin (Mdouble, Mdouble, Mdouble)
Sets the minimum coordinates of the problem domain.
void setTimeStep (Mdouble newDt)
Sets a new value for the simulation time step.
Mdouble getTimeStep () const
Returns the simulation time step.
void setNumberOfOMPThreads (int numberOfOMPThreads)
Sets the number of omp threads.
int getNumberOfOMPThreads () const
Returns the number of omp threads.
void setXBallsColourMode (int newCMode)
Set the xballs output mode.
int getXBallsColourMode () const
Get the xballs colour mode (CMode).
void setXBallsVectorScale (double newVScale)
Set the scale of vectors in xballs.
double getXBallsVectorScale () const
Returns the scale of vectors used in xballs.
void setXBallsAdditionalArguments (std::string newXBArgs)
Set the additional arguments for xballs.
std::string getXBallsAdditionalArguments () const
Returns the additional arguments for xballs.
void setXBallsScale (Mdouble newScale)
Sets the scale of the view (either normal, zoom in or zoom out) to display in xballs. The default is fit to screen.
double getXBallsScale () const
Returns the scale of the view in xballs.
void setGravity (Vec3D newGravity)
Sets a new value for the gravitational acceleration.
Vec3D getGravity () const
Returns the gravitational acceleration.
void setBackgroundDrag (Mdouble backgroundDrag)
Simple access function to turn on a background drag. The force of particleVelocity*drag is applied (note, it allowed to be negative i.e. create energy)
const Mdouble getBackgroundDrag () const
Return the background drag.
void setDimension (unsigned int newDim)
Sets both the system dimensions and the particle dimensionality.
void setSystemDimensions (unsigned int newDim)
Sets the system dimensionality.
unsigned int getSystemDimensions () const
Returns the system dimensionality.
void setParticleDimensions (unsigned int particleDimensions)
Sets the particle dimensionality.
unsigned int getParticleDimensions () const
Returns the particle dimensionality.
std::string getRestartVersion () const
This is to take into account for different Mercury versions. Returns the version of the restart file.
void setRestartVersion (std::string newRV)
Sets restart_version.
bool getRestarted () const
Returns the flag denoting if the simulation was restarted or not.
void setRestarted (bool newRestartedFlag)
Allows to set the flag stating if the simulation is to be restarted or not.
bool getAppend () const
Returns whether the "append" option is on or off.
void setAppend (bool newAppendFlag)
Sets whether the "append" option is on or off.
Mdouble getElasticEnergy () const
Returns the global elastic energy within the system.
Mdouble getKineticEnergy () const
Returns the global kinetic energy stored in the system.
Mdouble getGravitationalEnergy (Vec3D origin={0, 0, 0}) const
Returns the global gravitational potential energy stored relative to a user-defined origin in the system. Note, if no origin is specified the real origin i.e. (0,0,0) is taken.
Mdouble getRotationalEnergy () const
Returns the global rotational energy stored in the system.
Mdouble getTotalEnergy () const
Mdouble getTotalMass () const
JMFT: Return the total mass of the system, excluding fixed particles.
Vec3D getCentreOfMass () const
JMFT: Return the centre of mass of the system, excluding fixed particles.
Vec3D getTotalMomentum () const
JMFT: Return the total momentum of the system, excluding fixed particles.
double getCPUTime ()
double getWallTime ()
virtual void hGridInsertParticle (BaseParticle *obj UNUSED)
virtual void hGridUpdateParticle (BaseParticle *obj UNUSED)
virtual void hGridRemoveParticle (BaseParticle *obj UNUSED)
bool mpiIsInCommunicationZone (BaseParticle *particle)
Checks if the position of the particle is in an mpi communication zone or not.
bool mpiInsertParticleCheck (BaseParticle *P)
Function that checks if the mpi particle should really be inserted by the current domain.
void insertGhostParticle (BaseParticle *P)
This function inserts a particle in the mpi communication boundaries.
void updateGhostGrid (BaseParticle *P)
Checks if the Domain/periodic interaction distance needs to be updated and updates it accordingly.
virtual void gatherContactStatistics (unsigned int index1, int index2, Vec3D Contact, Mdouble delta, Mdouble ctheta, Mdouble fdotn, Mdouble fdott, Vec3D P1_P2_normal_, Vec3D P1_P2_tangential)
//Not unsigned index because of possible wall collisions.
void setNumberOfDomains (std::vector< unsigned > direction)
Sets the number of domains in x-,y- and z-direction. Required for parallel computations.
void splitDomain (DomainSplit domainSplit)
std::vector< unsigned > getNumberOfDomains ()
returns the number of domains
Domain * getCurrentDomain ()
Function that returns a pointer to the domain corresponding to the processor.
void removeOldFiles () const
void setMeanVelocity (Vec3D V_mean_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
void setMeanVelocityAndKineticEnergy (Vec3D V_mean_goal, Mdouble Ek_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
Mdouble getTotalVolume () const
Get the total volume of the cuboid system.
Matrix3D getKineticStress () const
Calculate the kinetic stress tensor in the system averaged over the whole volume.
Matrix3D getStaticStress () const
Calculate the static stress tensor in the system averaged over the whole volume.
Matrix3D getTotalStress () const
Calculate the total stress tensor in the system averaged over the whole volume.
virtual void handleParticleRemoval (unsigned int id)
Handles the removal of particles from the particleHandler.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
void writePythonFileForVTKVisualisation () const
writes .py file for ParaView
void setWritePythonFileForVTKVisualisation (bool forceWritePythonFileForVTKVisualisation)
bool getWritePythonFileForVTKVisualisation () const
WallVTKWriter & getWallVTKWriter ()
Public Attributes
unsigned int num_restart_small
unsigned int num_restart_large
Public Attributes inherited from DPMBase
SpeciesHandler speciesHandler
A handler to that stores the species type i.e. LinearViscoelasticSpecies, etc.
RNG random
This is a random generator, often used for setting up the initial conditions etc...
ParticleHandler particleHandler
An object of the class ParticleHandler, contains the pointers to all the particles created.
ParticleHandler paoloParticleHandler
Fake particleHandler created by Paolo needed temporary by just Paolo.
WallHandler wallHandler
An object of the class WallHandler. Contains pointers to all the walls created.
BoundaryHandler boundaryHandler
An object of the class BoundaryHandler which concerns insertion and deletion of particles into or from regions.
PeriodicBoundaryHandler periodicBoundaryHandler
Internal handler that deals with periodic boundaries, especially in a parallel build.
DomainHandler domainHandler
An object of the class DomainHandler which deals with parallel code.
InteractionHandler interactionHandler
An object of the class InteractionHandler.
CGHandler cgHandler
Object of the class cgHandler.
File dataFile
An instance of class File to handle in- and output into a .data file.
File fStatFile
An instance of class File to handle in- and output into a .fstat file.
File eneFile
An instance of class File to handle in- and output into a .ene file.
File restartFile
An instance of class File to handle in- and output into a .restart file.
File statFile
An instance of class File to handle in- and output into a .stat file.
File interactionFile
File class to handle in- and output into .interactions file. This file hold information about interactions.
Time clock_
record when the simulation started
Private Attributes
std::vector< BaseParticle * > BedParticles
double beltSpeed
double radius_l
const double radius_s
int num_small
int num_large
double particleVolRatio
InfiniteWall * gateLeft_
InfiniteWall * gateRight_
CubeInsertionBoundary * smallInsertionBoundary
CubeInsertionBoundary * largeInsertionBoundary
unsigned step =0
Tracks where we are up to in setting the problem up.
Additional Inherited Members
Public Types inherited from DPMBase
enum class ReadOptions : int { ReadAll , ReadNoInteractions , ReadNoParticlesAndInteractions }
enum class DomainSplit {
X , Y , Z , XY ,
XZ , YZ , XYZ
}
Static Public Member Functions inherited from DPMBase
static void incrementRunNumberInFile ()
Increment the run Number (counter value) stored in the file_counter (COUNTER_DONOTDEL) by 1 and store the new value in the counter file.
static int readRunNumberFromFile ()
Read the run number or the counter from the counter file (COUNTER_DONOTDEL)
static bool areInContact (const BaseParticle *pI, const BaseParticle *pJ)
Checks if two particle are in contact or is there any positive overlap.
Protected Member Functions inherited from Chute
void actionsBeforeTimeStep () override
Calls Chute::cleanChute().
void cleanChute ()
Deletes all outflow particles once every 100 time steps.
virtual void createBottom ()
Creates the chute bottom, which can be either flat or one of three flavours of rough.
virtual void addFlowParticlesCompactly ()
Add initial flow particles in a dense packing.
virtual SphericalParticle createFlowParticle ()
void printTime () const override
prints time, max time and number of particles
Protected Member Functions inherited from Mercury3D
void hGridFindContactsWithinTargetCell (int x, int y, int z, unsigned int l)
Finds contacts between particles in the target cell.
void hGridFindContactsWithTargetCell (int x, int y, int z, unsigned int l, BaseParticle *obj)
Finds contacts between the BaseParticle and the target cell.
void computeWallForces (BaseWall *w) override
Compute contacts with a wall.
void hGridFindParticlesWithTargetCell (int x, int y, int z, unsigned int l, BaseParticle *obj, std::vector< BaseParticle * > &list)
Finds particles within target cell and stores them in a list.
void hGridGetInteractingParticleList (BaseParticle *obj, std::vector< BaseParticle * > &list) override
Obtains all neighbour particles of a given object, obtained from the hgrid.
void computeInternalForces (BaseParticle *obj) override
Finds contacts with the BaseParticle; avoids multiple checks.
bool hGridHasContactsInTargetCell (int x, int y, int z, unsigned int l, const BaseParticle *obj) const
Tests if the BaseParticle has contacts with other Particles in the target cell.
bool hGridHasParticleContacts (const BaseParticle *obj) override
Tests if a BaseParticle has any contacts in the HGrid.
void hGridRemoveParticle (BaseParticle *obj) override
Removes a BaseParticle from the HGrid.
void hGridUpdateParticle (BaseParticle *obj) override
Updates the cell (not the level) of a BaseParticle.
Protected Member Functions inherited from MercuryBase
void hGridRebuild ()
This sets up the parameters required for the contact model.
void hGridInsertParticle (BaseParticle *obj) final
Inserts a single Particle to current grid.
void hGridUpdateMove (BaseParticle *iP, Mdouble move) final
Computes the relative displacement of the given BaseParticle and updates the currentMaxRelativeDisplacement_ accordingly.
void hGridActionsBeforeIntegration () override
Resets the currentMaxRelativeDisplacement_ to 0.
void hGridActionsAfterIntegration () override
This function has to be called before integrateBeforeForceComputation.
HGrid * getHGrid ()
Gets the HGrid used by this problem.
const HGrid * getHGrid () const
Gets the HGrid used by this problem, const version.
bool readNextArgument (int &i, int argc, char *argv[]) override
Reads the next command line argument.
Protected Member Functions inherited from DPMBase
virtual void computeAllForces ()
Computes all the forces acting on the particles using the BaseInteractable::setForce() and BaseInteractable::setTorque()
virtual void computeInternalForce (BaseParticle *, BaseParticle *)
Computes the forces between two particles (internal in the sense that the sum over all these forces is zero i.e. fully modelled forces)
virtual void computeExternalForces (BaseParticle *)
Computes the external forces, such as gravity, acting on particles.
virtual void computeForcesDueToWalls (BaseParticle *, BaseWall *)
Computes the forces on the particles due to the walls (normals are outward normals)
virtual void actionsBeforeTimeLoop ()
A virtual function. Allows one to carry out any operations before the start of the time loop.
virtual void computeAdditionalForces ()
A virtual function which allows to define operations to be executed prior to the OMP force collect.
virtual void actionsAfterSolve ()
A virtual function which allows to define operations to be executed after the solve().
void writeVTKFiles () const
virtual void outputXBallsData (std::ostream &os) const
This function writes the location of the walls and particles in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void outputXBallsDataParticle (unsigned int i, unsigned int format, std::ostream &os) const
This function writes out the particle locations into an output stream in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void writeEneHeader (std::ostream &os) const
Writes a header with a certain format for ENE file.
virtual void writeFstatHeader (std::ostream &os) const
Writes a header with a certain format for FStat file.
virtual void writeEneTimeStep (std::ostream &os) const
Write the global kinetic, potential energy, etc. in the system.
virtual void initialiseStatistics ()
virtual void outputStatistics ()
void gatherContactStatistics ()
virtual void processStatistics (bool)
virtual void finishStatistics ()
virtual void integrateBeforeForceComputation ()
Update particles' and walls' positions and velocities before force computation.
virtual void integrateAfterForceComputation ()
Update particles' and walls' positions and velocities after force computation.
virtual void checkInteractionWithBoundaries ()
There are a range of boundaries one could implement depending on ones' problem. This methods checks for interactions between particles and such range of boundaries. See BaseBoundary.h and all the boundaries in the Boundaries folder.
void setFixedParticles (unsigned int n)
Sets a number, n, of particles in the particleHandler as "fixed particles".
virtual bool continueSolve () const
A virtual function for deciding whether to continue the simulation, based on a user-specified criterion.
void outputInteractionDetails () const
Displays the interaction details corresponding to the pointer objects in the interaction handler.
bool isTimeEqualTo (Mdouble time) const
Checks whether the input variable "time" is the current time in the simulation.
void removeDuplicatePeriodicParticles ()
Removes periodic duplicate Particles.
void checkAndDuplicatePeriodicParticles ()
For simulations using periodic boundaries, checks and adds particles when necessary into the particle handler. See DPMBase.cc and PeriodicBoundary.cc for more details.
void performGhostParticleUpdate ()
When the Verlet scheme updates the positions and velocities of particles, ghost particles will need an update as wel. Their status will also be updated accordingly.
void deleteGhostParticles (std::set< BaseParticle * > &particlesToBeDeleted)
void synchroniseParticle (BaseParticle *, unsigned fromProcessor=0)
void performGhostVelocityUpdate ()
updates the final time-step velocity of the ghost particles
void disableSoftStop ()
This prevents the initialisation of the soft stop feature.
void discontinueSolve ()
This discontinues the solve loop after the current time step is finished.
Detailed Description
if you restart this code the third argument will be used as the number of large particles to add and the forth the number of small.
Constructor & Destructor Documentation
Chutebelt()
Chutebelt::Chutebelt () inline
                 : radius_s(0.5)
     {
     }
Member Function Documentation
actionsAfterTimeStep()
void Chutebelt::actionsAfterTimeStep () inline override virtual
A virtual function which allows to define operations to be executed after time step.
no implementation but can be overridden in its derived classes.
Todo:
Work out why the volume inserted is not what I expext
Reimplemented from DPMBase.
     {
         setParticlesWriteVTK(true);
         switch (step)
         {
             case 0 :
                 logger(INFO,"Finished create base now moving to insert large particles");
                 setChuteAngle(0.0);
                 step++;
                 break;
             case 1 :
                 largeInsertionBoundary->activate();
                 logger(DEBUG,"Inserted volume of % of larger particles, tagget is %",largeInsertionBoundary->getMassOfParticlesInserted(),largeInsertionBoundary->getInitialVolume());
                 if (getTime()>50.0)
                 {
                     logger(INFO,"Moving on to insert small particles");
                     largeInsertionBoundary->deactivate();
                     smallInsertionBoundary->activate();
                     step++;
                 }
                 break;
             case 2:
                 if (getTime()>100.0)
                 {
                     logger(INFO,"Now starting the simulations");
                     step++;
                     setTime(0.0);
                     setZMax(100.0*radius_l);
                     smallInsertionBoundary->deactivate();
                     setChuteAngle(25.0);
                     //To not clear hte boundary is this includes the periodic boundaries.
                     //boundaryHandler.clear();
                     //wallHandler.clear();
                     wallHandler.removeObject(gateLeft_->getIndex());
                     if (getIsPeriodic())
                     {
                         wallHandler.removeObject(gateRight_->getIndex());
                         //Periodic in y
                         PeriodicBoundary b0;
                         //b0.set(Vec3D(0.0, 1.0, 0.0), getYMin(), getYMax());
                         //boundaryHandler.copyAndAddObject(b0);
                         //Periodic in x
                         b0.set(Vec3D(1.0, 0.0, 0.0), getXMin(), getXMax());
                         boundaryHandler.copyAndAddObject(b0);
                     }
                 }
                 break;
         }
     }
References InsertionBoundary::activate(), DPMBase::boundaryHandler, BaseHandler< T >::copyAndAddObject(), InsertionBoundary::deactivate(), DEBUG, gateLeft_, gateRight_, BaseObject::getIndex(), InsertionBoundary::getInitialVolume(), Chute::getIsPeriodic(), InsertionBoundary::getMassOfParticlesInserted(), DPMBase::getTime(), DPMBase::getXMax(), DPMBase::getXMin(), INFO, largeInsertionBoundary, logger, radius_l, BaseHandler< T >::removeObject(), PeriodicBoundary::set(), Chute::setChuteAngle(), DPMBase::setParticlesWriteVTK(), DPMBase::setTime(), DPMBase::setZMax(), smallInsertionBoundary, step, and DPMBase::wallHandler.
actionsBeforeTimeStep()
void Chutebelt::actionsBeforeTimeStep () inline override virtual
A virtual function which allows to define operations to be executed before the new time step.
no implementation but can be overridden in its derived classes.
Reimplemented from DPMBase.
     {
         if (BedParticles.empty())
         {
             for (int i = 0; i < particleHandler.getNumberOfObjects(); i++)
             {
                 BaseParticle* P0 = particleHandler.getObject(i);
                 if (P0->getIndSpecies() == 0)
                 {
                     P0->setVelocity(Vec3D(0.0,0.0,0.0));
                     BedParticles.push_back(P0);
                 }
             }
             logger(INFO, "Finished storing bed particles");
         }
         if (getTime() > 1.0)
         {
             for (int i = 0; i < BedParticles.size(); i++)
             {
                 BaseParticle* P0 = BedParticles[i];
                 if (P0->getIndSpecies() == 0)
                 {
                     Vec3D position;
                     position = P0->getPosition();
                     double dt = getTimeStep();
                     position.X = position.X - beltSpeed * dt;
                     if (position.X < getXMin())
                     {
                         position.X = position.X - getXMin() + getXMax();
                     }
                     P0->setPosition(position);
                 }
             }
         }
     }
References BedParticles, beltSpeed, ParticleHandler::getNumberOfObjects(), BaseHandler< T >::getObject(), DPMBase::getTime(), DPMBase::getTimeStep(), DPMBase::getXMax(), DPMBase::getXMin(), i, INFO, logger, Problem_Parameter::P0, DPMBase::particleHandler, and Vec3D::X.
actionsOnRestart()
void Chutebelt::actionsOnRestart () inline override virtual
A virtual function where the users can add extra code which is executed only when the code is restarted.
no implementation but can be overridden in its derived classes.
Reimplemented from DPMBase.
     {
         int Ns = num_restart_small;
         int Nl = num_restart_large;
         auto species0 = speciesHandler.getObject(0);
         auto species1 = speciesHandler.getObject(1);
         auto species2 = speciesHandler.getObject(2);
         logger(INFO, "Restarting and adding % small particles and % large particles", Ns, Nl);
         SphericalParticle P0;
         while ((Ns > 0) || (Nl > 0))
         {
             //random to see if want to generate a large or small particles, helps makes the initial conditions homogenious
             if (random.getRandomNumber(1.0, Nl + Ns) > Nl)
             {
                 P0.setRadius(radius_s);
                 P0.setSpecies(species1);
                 Ns--;
             }
             else
             {
                 P0.setRadius(radius_l);
                 P0.setSpecies(species2);
                 Nl--;
             }
             //randomise particle position, zero intial velocity
             do
             {
                 P0.setPosition(
                                Vec3D(random.getRandomNumber(getXMin() + radius_l + 2 * getFixedParticleRadius(),
                                                             getXMax() - radius_l - 2 * getFixedParticleRadius()),
                                      random.getRandomNumber(getYMin() + radius_l, getYMax() - radius_l),
                                      random.getRandomNumber(getZMin() + radius_l, getZMax() - radius_l)));
                 P0.setVelocity(Vec3D(0.0, 0.0, 0.0));
             } while (!checkParticleForInteraction(P0));
             particleHandler.copyAndAddObject(P0);
         }
         logger(INFO, "Finished adding new particles. Now simulation will restart");
     }
References MercuryBase::checkParticleForInteraction(), BaseHandler< T >::copyAndAddObject(), Chute::getFixedParticleRadius(), BaseHandler< T >::getObject(), RNG::getRandomNumber(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), DPMBase::getZMax(), DPMBase::getZMin(), INFO, logger, num_restart_large, num_restart_small, Problem_Parameter::P0, DPMBase::particleHandler, radius_l, radius_s, DPMBase::random, and DPMBase::speciesHandler.
set_beltSpeed()
void Chutebelt::set_beltSpeed (double new_speed) inline
     {
         beltSpeed = new_speed;
     }
References beltSpeed.
set_particle_number_volRatio()
void Chutebelt::set_particle_number_volRatio (double new_volume_ratio) inline
     {
         particleVolRatio = new_volume_ratio;
     }
References particleVolRatio.
set_particle_numbers() [1/2]
void Chutebelt::set_particle_numbers (int new_num_small) inline
     {
         if (new_num_small > 0)
         {
             num_small = new_num_small;
             num_large = std::pow(radius_s / radius_l, 3) * num_small * particleVolRatio;
         }
         else
         {
             logger(ERROR, "Please give a positive number of particles");
         }
     }
References ERROR, logger, num_large, num_small, particleVolRatio, Eigen::bfloat16_impl::pow(), radius_l, and radius_s.
set_particle_numbers() [2/2]
void Chutebelt::set_particle_numbers (int new_num_small, int new_num_large) inline
     {
         if (new_num_small > 0)
         {
             num_small = new_num_small;
         }
         else
         {
             logger(ERROR, "Please give a positive number if small particles");
         }
         if (new_num_large > 0)
         {
             num_large = new_num_large;
         }
         else
         {
             logger(ERROR, "Please give a positive number if small particles");
         }
     }
References ERROR, logger, num_large, and num_small.
set_radiusLarge()
void Chutebelt::set_radiusLarge (double new_large_radius) inline
     {
         if (new_large_radius > 0)
         {
             radius_l = new_large_radius;
         }
         else
         {
             logger(ERROR, "Radius must be greater than zero");
         }
     }
References ERROR, logger, and radius_l.
setupInitialConditions()
void Chutebelt::setupInitialConditions () inline override virtual
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
A virtual function with no implementation but can be overridden.
Todo:
I (Anthony) wants to change this to be an external function. This has a lot of advantages especially when using copy-constructors. This is a major change and will break other codes, so therefore has to be done carefully.
This sets up the particles initial conditions it is as you expect the user to override this. By default the particles are randomly distributed
Reimplemented from DPMBase.
     {
         //Number of small particles
         int Ns = num_small;
         int Nl = num_large;
         setZMax(200.0*radius_l);
         //Set up live statistics
         //CG<CGCoordinates::Z> cg; //declare a cg object
         //cg.setN(50); //set the CG to be 100 by 100.
         //cg.setWidth(5.0*radius_s);
         //cg.statFile.setSaveCount(200); //set parameters such as the output frequency
         //cgHandler.copyAndAddObject(cg); // add the CG object to the cgHandler*/
         //setInflowParticleRadius(radius_s, radius_l);
         double rho = 6.0 / constants::pi;
         double tc = 1.0 / 200.0;
         double r = 0.1;
         double mass_small = 4.0 / 3.0 * constants::pi * pow(radius_s, 3.0) * rho;
         double mass_large = 4.0 / 3.0 * constants::pi * pow(radius_l, 3.0) * rho;
         auto species0 = speciesHandler.copyAndAddObject(LinearViscoelasticFrictionSpecies());
         auto species1 = speciesHandler.copyAndAddObject(species0);
         auto species2 = speciesHandler.copyAndAddObject(species0);
         auto species01 = speciesHandler.getMixedObject(species0, species1);
         auto species02 = speciesHandler.getMixedObject(species0, species2);
         auto species12 = speciesHandler.getMixedObject(species1, species2);
         //  Set the contact time (tc), resitution coefficeient (r) and density (rho) for small for all particles
         //
         species0->setDensity(rho);
         species0->setCollisionTimeAndRestitutionCoefficient(tc, r, mass_small); //MD::setCollisionTimeAndRestitutionCoefficient(tc, r,mass_small);
         species0->setSlidingDissipation(species0->getDissipation()); //  Set the tangential dissipation equal to the normal disipation for small-small collsions
         species0->setSlidingStiffness(species0->getStiffness()*2.0/7.0);
         species0->setSlidingFrictionCoefficient(0.5);
         //
         species1->setDensity(rho);
         species1->setCollisionTimeAndRestitutionCoefficient(tc, r, mass_small);
         species1->setSlidingDissipation(species1->getDissipation()); //  Set the tangential dissipationequal to the normal disipation for large-large collision
         species1->setSlidingStiffness(species1->getStiffness()*2.0/7.0);
         species1->setSlidingFrictionCoefficient(0.5);
         //
         species2->setDensity(rho);
         species2->setCollisionTimeAndRestitutionCoefficient(tc, r, mass_large);
         species2->setSlidingDissipation(species2->getDissipation());
         species2->setSlidingStiffness(species2->getStiffness()*2.0/7.0);
         species2->setSlidingFrictionCoefficient(0.5);
         //
         //
         species01->setCollisionTimeAndRestitutionCoefficient(tc, r, mass_small, mass_small);
         species01->setSlidingDissipation(
                 species01->getDissipation()); //  Set the tangential dissipation equal to the normal disipation for mixed collision
         species01->setSlidingFrictionCoefficient(0.5);
         species01->setSlidingStiffness(species01->getStiffness() * 2.0 / 7.0);
         species02->setCollisionTimeAndRestitutionCoefficient(tc, r, mass_small, mass_large);
         species02->setSlidingDissipation(
                 species01->getDissipation()); //  Set the tangential dissipation equal to the normal disipation
         species02->setSlidingFrictionCoefficient(0.5);
         species02->setSlidingStiffness(species02->getStiffness() * 2.0 / 7.0);
         species12->setCollisionTimeAndRestitutionCoefficient(tc, r, mass_small, mass_large);
         species12->setSlidingDissipation(
                 species01->getDissipation()); //  Set the tangential dissipation equal to the normal disipation
         species12->setSlidingFrictionCoefficient(0.5);
         species12->setSlidingStiffness(species12->getStiffness() * 2.0 / 7.0);
         logger(INFO, "Number of large particles:%\n", Flusher::NO_FLUSH, Nl);
         logger(INFO, "Number of small particles:%", Ns);
         Chute::setupInitialConditions();
         // Remove the two existing boundaries insertion and periodic and put the peroidic back if perodic else put
         boundaryHandler.clear();
         //Now add two extra solid walls at the end
         //InfiniteWall w0;
         gateLeft_ = new InfiniteWall;
         //w0.set(Vec3D(-1.0, 0.0, 0.0), Vec3D(getXMin() + 2 * getFixedParticleRadius(),0,0));
         //wallHandler.copyAndAddObject(w0);
         gateLeft_->set(Vec3D(1.0, 0.0, 0.0), Vec3D(getXMax(),0,0));
         gateLeft_->setSpecies(species0);
         wallHandler.addObject(gateLeft_);
         gateRight_ = new InfiniteWall;
         gateRight_->set(Vec3D(-1.0, 0.0, 0.0), Vec3D(getXMin() ,0,0));
         gateRight_->setSpecies(species0);
         wallHandler.addObject(gateRight_);
         //wallHandler.copyAndAddObject(w0);
         if (getIsPeriodic())
         {
             //Periodic in y
             PeriodicBoundary b0;
             b0.set(Vec3D(0.0, 1.0, 0.0), getYMin(), getYMax());
             boundaryHandler.copyAndAddObject(b0);
             //Periodic in x
            // b0.set(Vec3D(1.0, 0.0, 0.0), getXMin(), getXMax());
             // boundaryHandler.copyAndAddObject(b0);
         }
         // CREATE THE PARTICLES
         SphericalParticle p0;
         smallInsertionBoundary = new CubeInsertionBoundary();
         largeInsertionBoundary = new CubeInsertionBoundary();
         double volumeToInsert = num_small * 4.0 / 3.0 * constants::pi * pow(1.0, 3);
         logger(INFO, "Need to insert a volume of % of each particle type", volumeToInsert);
         smallInsertionBoundary->set(p0, 1000000, Vec3D(getXMin(), getYMin(), getZMax() / 2.0),
                                     Vec3D(getXMax(), getYMax(), getZMax()), Vec3D(0.0, 0.0, 0.0), Vec3D(0.0, 0.0, 0.0));
         smallInsertionBoundary->setInitialVolume(volumeToInsert);
         smallInsertionBoundary->deactivate();
         boundaryHandler.addObject(smallInsertionBoundary);
         largeInsertionBoundary->set(p0, 1000000, Vec3D(getXMin(), getYMin(), getZMin()),
                                     Vec3D(getXMax(), getYMax(), getZMax() / 2.0), Vec3D(0.0, 0.0, 0.0),
                                     Vec3D(0.0, 0.0, 0.0));
         largeInsertionBoundary->setInitialVolume(volumeToInsert);
         largeInsertionBoundary->deactivate();
         boundaryHandler.addObject(largeInsertionBoundary);
         /* while ((Ns > 0) || (Nl > 0))
          {
              //random to see if want to generate a large or small particles, helps makes the initial conditions homogenious
              if (random.getRandomNumber(1.0, Nl + Ns) > Nl)
              {
                  P0.setRadius(radius_s);
                  P0.setSpecies(species1);
                  Ns--;
              }
              else
              {
                  P0.setRadius(radius_l);
                  P0.setSpecies(species2);
                  Nl--;
              }
              //randomise particle position, zero intial velocity
          do
                  {
                  P0.setPosition(
                      Vec3D(random.getRandomNumber(getXMin() + radius_l + 2 * getFixedParticleRadius(),
                              getXMax() - radius_l - 2 * getFixedParticleRadius()),
                              random.getRandomNumber(getYMin() + radius_l, getYMax() - radius_l),
                              random.getRandomNumber(getZMin() + radius_l, getZMax() - radius_l)));
                  P0.setVelocity(Vec3D(0.0, 0.0, 0.0));
                   }
               while (!checkParticleForInteraction(P0));
           particleHandler.copyAndAddObject(P0);
          }*/
         logger(INFO, "Finished creating particles");
         for (int i = 0; i < particleHandler.getNumberOfObjects(); i++)
         {
             BaseParticle* P0 = particleHandler.getObject(i);
             if (P0->getIndSpecies() == 0)
             {
                 BedParticles.push_back(P0);
             }
         }
         logger(INFO, "Finished storing bed particles");
     }
References BoundaryHandler::addObject(), WallHandler::addObject(), BedParticles, DPMBase::boundaryHandler, BaseHandler< T >::clear(), BaseHandler< T >::copyAndAddObject(), InsertionBoundary::deactivate(), gateLeft_, gateRight_, Chute::getIsPeriodic(), SpeciesHandler::getMixedObject(), ParticleHandler::getNumberOfObjects(), BaseHandler< T >::getObject(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), DPMBase::getZMax(), DPMBase::getZMin(), i, INFO, largeInsertionBoundary, logger, NO_FLUSH, num_large, num_small, p0, Problem_Parameter::P0, DPMBase::particleHandler, constants::pi, Eigen::bfloat16_impl::pow(), UniformPSDSelfTest::r, radius_l, radius_s, CubeInsertionBoundary::set(), PeriodicBoundary::set(), InfiniteWall::set(), InsertionBoundary::setInitialVolume(), BaseWall::setSpecies(), Chute::setupInitialConditions(), DPMBase::setZMax(), smallInsertionBoundary, DPMBase::speciesHandler, and DPMBase::wallHandler.
Member Data Documentation
BedParticles
std::vector<BaseParticle*> Chutebelt::BedParticles private
Referenced by actionsBeforeTimeStep(), and setupInitialConditions().
beltSpeed
double Chutebelt::beltSpeed private
Referenced by actionsBeforeTimeStep(), and set_beltSpeed().
gateLeft_
InfiniteWall* Chutebelt::gateLeft_ private
Referenced by actionsAfterTimeStep(), and setupInitialConditions().
gateRight_
InfiniteWall* Chutebelt::gateRight_ private
Referenced by actionsAfterTimeStep(), and setupInitialConditions().
largeInsertionBoundary
CubeInsertionBoundary* Chutebelt::largeInsertionBoundary private
Referenced by actionsAfterTimeStep(), and setupInitialConditions().
num_large
int Chutebelt::num_large private
Referenced by set_particle_numbers(), and setupInitialConditions().
num_restart_large
unsigned int Chutebelt::num_restart_large
Referenced by actionsOnRestart().
num_restart_small
unsigned int Chutebelt::num_restart_small
Referenced by actionsOnRestart().
num_small
int Chutebelt::num_small private
Referenced by set_particle_numbers(), and setupInitialConditions().
particleVolRatio
double Chutebelt::particleVolRatio private
Referenced by set_particle_number_volRatio(), and set_particle_numbers().
radius_l
double Chutebelt::radius_l private
Referenced by actionsAfterTimeStep(), actionsOnRestart(), set_particle_numbers(), set_radiusLarge(), and setupInitialConditions().
radius_s
const double Chutebelt::radius_s private
Referenced by actionsOnRestart(), set_particle_numbers(), and setupInitialConditions().
smallInsertionBoundary
CubeInsertionBoundary* Chutebelt::smallInsertionBoundary private
Referenced by actionsAfterTimeStep(), and setupInitialConditions().
step
unsigned Chutebelt::step =0 private
Tracks where we are up to in setting the problem up.
Step 0 : Insert small particles at the bottom Step 1 : Insert large particles at the top. Both step 0 and 1 setup are done with a gate at the right but the correct chute angle
Referenced by actionsAfterTimeStep().
The documentation for this class was generated from the following file:
SegregationNew.cpp