MercuryDPM: Eigen::internal::TensorPrinter< Tensor, 0, Format > Struct Template Reference
Eigen::internal::TensorPrinter< Tensor, 0, Format > Struct Template Reference
#include <TensorIO.h>
Static Public Member Functions
static void run (std::ostream &s, const Tensor &tensor, const Format &fmt)
Member Function Documentation
run()
template<typename Tensor , typename Format > static void Eigen::internal::TensorPrinter< Tensor, 0, Format >::run (std::ostream & s, const Tensor & tensor, const Format & fmt) inline static
{
     using Scalar = std::remove_const_t<typename Tensor::Scalar>;
     std::streamsize explicit_precision;
     if (fmt.precision == StreamPrecision) {
       explicit_precision = 0;
     } else if (fmt.precision == FullPrecision) {
       if (NumTraits<Scalar>::IsInteger) {
         explicit_precision = 0;
       } else {
         explicit_precision = significant_decimals_impl<Scalar>::run();
       }
     } else {
       explicit_precision = fmt.precision;
     }
     std::streamsize old_precision = 0;
     if (explicit_precision) old_precision = s.precision(explicit_precision);
     s << fmt.tenPrefix;
     ScalarPrinter<Scalar, Format>::run(s, tensor.coeff(0), fmt);
     s << fmt.tenSuffix;
     if (explicit_precision) s.precision(old_precision);
   }
References Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::coeff(), Eigen::FullPrecision, Eigen::internal::significant_decimals_impl< Scalar >::run(), Eigen::internal::ScalarPrinter< Scalar, Format, EnableIf >::run(), s, and Eigen::StreamPrecision.
The documentation for this struct was generated from the following file:
TensorIO.h