MercuryDPM: refineable_t_junction.cc File Reference
refineable_t_junction.cc File Reference
#include "generic.h"
#include "young_laplace.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class RefineableYoungLaplaceProblem< ELEMENT >
Namespaces
GlobalParameters
Global parameters.
Functions
void GlobalParameters::spine_base_function (const Vector< double > &x, Vector< double > &spine_B, Vector< Vector< double > > &dspine_B)
void GlobalParameters::spine_function (const Vector< double > &x, Vector< double > &spine, Vector< Vector< double > > &dspine)
int main ()
Drive code.
Function Documentation
main()
int main ()
Drive code.
 {
  // Create label for output
  DocInfo doc_info;
  // Trace file
  ofstream trace_file;
  // Set output directory
  doc_info.set_directory("RESLT");
  // Open a trace file
  char filename[100];
  sprintf(filename,"%s/trace.dat",doc_info.directory().c_str());
  trace_file.open(filename);
  // Tecplot header for trace file: kappa and height value
  trace_file << "VARIABLES=\"<GREEK>k</GREEK>\",\"h\"" << std::endl;
  trace_file << "ZONE" << std::endl;
  //Set up the problem
  //------------------
  // Create the problem with 2D nine-node elements from the
  // RefineableQYoungLaplaceElement family.
  RefineableYoungLaplaceProblem<RefineableQYoungLaplaceElement<3> > problem;
  // Perform one uniform refinement
  problem.refine_uniformly();
  //Output the solution
  problem.doc_solution(doc_info,trace_file);
  //Increment counter for solutions
  doc_info.number()++;
  // Parameter incrementation
  //-------------------------
  double increment=0.1;
  // Loop over steps
  unsigned nstep=2; // 10;
  for (unsigned istep=0;istep<nstep;istep++)
   {
    GlobalParameters::Controlled_height+=increment;
    // Solve the problem
    unsigned max_adapt=1;
    problem.newton_solve(max_adapt);
    //Output the solution
    problem.doc_solution(doc_info,trace_file);
    //Increment counter for solutions
    doc_info.number()++;
   }
  // Close output file
  trace_file.close();
 } //end of main
References GlobalParameters::Controlled_height, oomph::DocInfo::directory(), MergeRestartFiles::filename, oomph::DocInfo::number(), problem, and oomph::DocInfo::set_directory().