MercuryDPM: oomph::Hypre_default_settings Namespace Reference
oomph::Hypre_default_settings Namespace Reference
Default settings for various uses of the HYPRE solver.
Functions
void set_defaults_for_2D_poisson_problem (HyprePreconditioner *hypre_preconditioner_pt)
void set_defaults_for_3D_poisson_problem (HyprePreconditioner *hypre_preconditioner_pt)
void set_defaults_for_navier_stokes_momentum_block (HyprePreconditioner *hypre_preconditioner_pt)
Detailed Description
Default settings for various uses of the HYPRE solver.
Default settings for various uses of the Hypre solver.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Function Documentation
set_defaults_for_2D_poisson_problem()
void oomph::Hypre_default_settings::set_defaults_for_2D_poisson_problem (HyprePreconditioner * hypre_preconditioner_pt)
Set default parameters for use as preconditioner in 2D Poisson-type problem.
     {
       // Set iterations to 1
       hypre_preconditioner_pt->set_amg_iterations(1);
       // Use simple smoother
       hypre_preconditioner_pt->amg_using_simple_smoothing();
       // Smoother types:
       //           0=Jacobi
       //           1=Gauss-Seidel
       hypre_preconditioner_pt->amg_simple_smoother() = 1;
       // AMG preconditioner
       hypre_preconditioner_pt->hypre_method() = HyprePreconditioner::BoomerAMG;
       // Choose strength parameter for amg
       hypre_preconditioner_pt->amg_strength() = 0.25;
       // Coarsening type
       hypre_preconditioner_pt->amg_coarsening() = 0;
     }
References oomph::HyprePreconditioner::amg_coarsening(), oomph::HyprePreconditioner::amg_simple_smoother(), oomph::HyprePreconditioner::amg_strength(), oomph::HyprePreconditioner::amg_using_simple_smoothing(), oomph::HypreInterface::BoomerAMG, oomph::HyprePreconditioner::hypre_method(), and oomph::HyprePreconditioner::set_amg_iterations().
Referenced by FpTestProblem::FpTestProblem(), FSIChannelWithLeafletProblem< ELEMENT >::FSIChannelWithLeafletProblem(), main(), PreconditionedFSICollapsibleChannelProblem< ELEMENT >::PreconditionedFSICollapsibleChannelProblem(), RectangularDrivenCavityProblem< ELEMENT >::RectangularDrivenCavityProblem(), set_defaults_for_3D_poisson_problem(), set_defaults_for_navier_stokes_momentum_block(), FSIChannelWithLeafletProblem< ELEMENT >::set_iterative_solver(), oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::setup(), TorusProblem< ELEMENT >::TorusProblem(), and TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem().
set_defaults_for_3D_poisson_problem()
void oomph::Hypre_default_settings::set_defaults_for_3D_poisson_problem (HyprePreconditioner * hypre_preconditioner_pt)
Set default parameters for use as preconditioner in 3D Poisson-type problem.
     {
       // Set default settings as for 2D Poisson
       set_defaults_for_2D_poisson_problem(hypre_preconditioner_pt);
       // Change strength parameter for amg
       hypre_preconditioner_pt->amg_strength() = 0.7;
     }
References oomph::HyprePreconditioner::amg_strength(), and set_defaults_for_2D_poisson_problem().
Referenced by BoussinesqPreconditioner::BoussinesqPreconditioner(), and RefineableConvectionProblem< NST_ELEMENT, AD_ELEMENT >::switch_to_iterative_linear_solver().
set_defaults_for_navier_stokes_momentum_block()
void oomph::Hypre_default_settings::set_defaults_for_navier_stokes_momentum_block (HyprePreconditioner * hypre_preconditioner_pt)
Set default parameters for use as preconditioner in for momentum block in Navier-Stokes problem
     {
       // Set default settings as for 2D Poisson
       set_defaults_for_2D_poisson_problem(hypre_preconditioner_pt);
       // Change smoother type:
       //           0=Jacobi
       //           1=Gauss-Seidel
       hypre_preconditioner_pt->amg_simple_smoother() = 0;
       // Set smoother damping
       hypre_preconditioner_pt->amg_damping() = 0.5;
       // Change strength parameter for amg
       hypre_preconditioner_pt->amg_strength() = 0.75;
     }
References oomph::HyprePreconditioner::amg_damping(), oomph::HyprePreconditioner::amg_simple_smoother(), oomph::HyprePreconditioner::amg_strength(), and set_defaults_for_2D_poisson_problem().
Referenced by BoussinesqPreconditioner::BoussinesqPreconditioner(), FSIChannelWithLeafletProblem< ELEMENT >::FSIChannelWithLeafletProblem(), RectangularDrivenCavityProblem< ELEMENT >::RectangularDrivenCavityProblem(), and RefineableConvectionProblem< NST_ELEMENT, AD_ELEMENT >::switch_to_iterative_linear_solver().