MercuryDPM: TanhSolnForSteadyAxisymAdvectionDiffusion Namespace Reference
TanhSolnForSteadyAxisymAdvectionDiffusion Namespace Reference
Functions
Exact solution as a Vector void get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a scalar void get_exact_u (const Vector< double > &x, double &u)
Source function required to make the solution above an exact solution void source_function (const Vector< double > &x_vect, double &source)
Beta required by the exact solution on a boundary on which r is fixed void prescribed_beta_on_fixed_r_boundary (const Vector< double > &x_vect, double &beta)
Alfa required by the exact solution on a boundary on which r is fixed void prescribed_alpha_on_fixed_r_boundary (const Vector< double > &x_vect, double &alpha)
Wind void wind_function (const Vector< double > &x, Vector< double > &wind)
Variables
double Peclet = 0.0
Peclet number.
double TanPhi = 0.5
Parameter for angle of step.
double Omega = 0.5
Parameter for switch z-dependence.
double Epsilon = 0.1
Amplitude of boundary deflection (Epsilon<R!!!)
double K_Alpha = 1.0
Relation between alfa and beta (.
Detailed Description
Namespace for exact solution for SteadyAxisymAdvectionDiffusion equation with "sharp" step
Function Documentation
get_exact_u() [1/2]
Exact solution as a scalar void TanhSolnForSteadyAxisymAdvectionDiffusion::get_exact_u (const Vector< double > & x, double & u)
  {
   double f_rz = 1.0-(TanPhi*pow(x[0],2.0)-Omega*x[1]);
   u = tanh(f_rz);
  }
References Omega, Eigen::bfloat16_impl::pow(), Eigen::bfloat16_impl::tanh(), TanPhi, and plotDoE::x.
get_exact_u() [2/2]
Exact solution as a Vector void TanhSolnForSteadyAxisymAdvectionDiffusion::get_exact_u (const Vector< double > & x, Vector< double > & u)
  {
   double f_rz = 1.0-(TanPhi*pow(x[0],2.0)-Omega*x[1]);
   u[0] = tanh(f_rz);
  }
References Omega, Eigen::bfloat16_impl::pow(), Eigen::bfloat16_impl::tanh(), TanPhi, and plotDoE::x.
Referenced by TwoMeshFluxSteadyAxisymAdvectionDiffusionProblem< ELEMENT >::doc_solution(), and for().
prescribed_alpha_on_fixed_r_boundary()
Alfa required by the exact solution on a boundary on which r is fixed void TanhSolnForSteadyAxisymAdvectionDiffusion::prescribed_alpha_on_fixed_r_boundary (const Vector< double > & x_vect, double & alpha)
  {
   double r = x_vect[0];
   double z = x_vect[1];
   double f_rz = 1.0-(TanPhi*pow(r,2.0)-Omega*z);
   alpha = -K_Alpha*( 1.0/( sqrt(1.0 + pow(Epsilon*cos(z),2.0) ) ) )*
                    ( 1.0/( 1.0 -  K_Alpha*tanh(f_rz) ) )*
                    ( 1.0 - pow(tanh(f_rz),2.0))*
                    (-2.0*TanPhi*r + Epsilon*cos(z)*Omega);
  }
References alpha, cos(), Epsilon, K_Alpha, Omega, Eigen::bfloat16_impl::pow(), UniformPSDSelfTest::r, sqrt(), Eigen::bfloat16_impl::tanh(), and TanPhi.
Referenced by Wind_fct_pt().
prescribed_beta_on_fixed_r_boundary()
Beta required by the exact solution on a boundary on which r is fixed void TanhSolnForSteadyAxisymAdvectionDiffusion::prescribed_beta_on_fixed_r_boundary (const Vector< double > & x_vect, double & beta)
  {
   double r = x_vect[0];
   double z = x_vect[1];
   double f_rz = 1.0-(TanPhi*pow(r,2.0)-Omega*z);
   //The beta is (for the problem with bound1 = F(z) = R + epsilon*sin(z) with 0<z<H=2*Pi)
   beta = -1.0*( 1.0/( sqrt(1.0 + pow(Epsilon*cos(z),2.0) ) ) )*
               ( 1.0/( 1.0 -  K_Alpha*tanh(f_rz) ) )*
               ( 1.0 - pow(tanh(f_rz),2.0))*
               (-2.0*TanPhi*r + Epsilon*cos(z)*Omega);
  }
References beta, cos(), Epsilon, K_Alpha, Omega, Eigen::bfloat16_impl::pow(), UniformPSDSelfTest::r, sqrt(), Eigen::bfloat16_impl::tanh(), and TanPhi.
Referenced by Wind_fct_pt().
source_function()
Source function required to make the solution above an exact solution void TanhSolnForSteadyAxisymAdvectionDiffusion::source_function (const Vector< double > & x_vect, double & source)
  {
   double r = x_vect[0];
   double z = x_vect[1];
   double f_rz = 1.0-(TanPhi*pow(r,2.0)-Omega*z);
    source =
     (1.0-pow(tanh(f_rz),2.0))*
     ( Peclet*(-2*r*TanPhi*sin(6.0*z) + Omega*cos(6.0*r)) +
       2.0*tanh(f_rz)*( pow(Omega,2.0) + 4.0*pow(r*TanPhi,2.0) ) +
       4.0*TanPhi);
  }
References cos(), Omega, Peclet, Eigen::bfloat16_impl::pow(), UniformPSDSelfTest::r, sin(), TestProblem::source(), Eigen::bfloat16_impl::tanh(), and TanPhi.
Referenced by main().
wind_function()
Wind void TanhSolnForSteadyAxisymAdvectionDiffusion::wind_function (const Vector< double > & x, Vector< double > & wind)
  {
   double r = x[0];
   double z = x[1];
   wind[0] = sin(6.0*z);
   wind[1] = cos(6.0*r);
  }
References cos(), UniformPSDSelfTest::r, sin(), and plotDoE::x.
Referenced by main().
Variable Documentation
Epsilon
double TanhSolnForSteadyAxisymAdvectionDiffusion::Epsilon = 0.1
Amplitude of boundary deflection (Epsilon<R!!!)
Referenced by prescribed_alpha_on_fixed_r_boundary(), prescribed_beta_on_fixed_r_boundary(), and Wind_fct_pt().
K_Alpha
double TanhSolnForSteadyAxisymAdvectionDiffusion::K_Alpha = 1.0
Relation between alfa and beta (.
Referenced by prescribed_alpha_on_fixed_r_boundary(), and prescribed_beta_on_fixed_r_boundary().
Omega
double TanhSolnForSteadyAxisymAdvectionDiffusion::Omega = 0.5
Parameter for switch z-dependence.
Referenced by get_exact_u(), prescribed_alpha_on_fixed_r_boundary(), prescribed_beta_on_fixed_r_boundary(), and source_function().
Peclet
double TanhSolnForSteadyAxisymAdvectionDiffusion::Peclet = 0.0
Peclet number.
Referenced by source_function(), and Wind_fct_pt().
TanPhi
double TanhSolnForSteadyAxisymAdvectionDiffusion::TanPhi = 0.5
Parameter for angle of step.
Referenced by get_exact_u(), prescribed_alpha_on_fixed_r_boundary(), prescribed_beta_on_fixed_r_boundary(), and source_function().