MercuryDPM: Eigen::MatrixExponentialReturnValue< Derived > Struct Template Reference
Eigen::MatrixExponentialReturnValue< Derived > Struct Template Reference
Proxy for the matrix exponential of some matrix (expression).
#include <MatrixExponential.h>
Public Member Functions
MatrixExponentialReturnValue (const Derived &src)
Constructor.
template<typename ResultType >
void evalTo (ResultType &result) const
Compute the matrix exponential.
Index rows () const
Index cols () const
Public Member Functions inherited from Eigen::ReturnByValue< MatrixExponentialReturnValue< Derived > >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Protected Attributes
const internal::ref_selector< Derived >::type m_src
Additional Inherited Members
Public Types inherited from Eigen::ReturnByValue< MatrixExponentialReturnValue< Derived > >
typedef internal::traits< MatrixExponentialReturnValue< Derived > >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Detailed Description
template<typename Derived>
struct Eigen::MatrixExponentialReturnValue< Derived >
Proxy for the matrix exponential of some matrix (expression).
Template Parameters
Derived Type of the argument to the matrix exponential.
This class holds the argument to the matrix exponential until it is assigned or evaluated for some other reason (so the argument should not be changed in the meantime). It is the return type of MatrixBase::exp() and most of the time this is the only way it is used.
Constructor & Destructor Documentation
MatrixExponentialReturnValue()
template<typename Derived > Eigen::MatrixExponentialReturnValue< Derived >::MatrixExponentialReturnValue (const Derived & src) inline
Constructor.
Parameters
src Matrix (expression) forming the argument of the matrix exponential.
 : m_src(src) {}
Member Function Documentation
cols()
template<typename Derived > Index Eigen::MatrixExponentialReturnValue< Derived >::cols () const inline
 { return m_src.cols(); }
References Eigen::MatrixExponentialReturnValue< Derived >::m_src.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
evalTo()
template<typename Derived > template<typename ResultType > void Eigen::MatrixExponentialReturnValue< Derived >::evalTo (ResultType & result) const inline
Compute the matrix exponential.
Parameters
result the matrix exponential of src in the constructor.
{
     const typename internal::nested_eval<Derived, 10>::type tmp(m_src);
     internal::matrix_exp_compute(tmp, result, internal::is_exp_known_type<typename Derived::RealScalar>());
   }
References Eigen::MatrixExponentialReturnValue< Derived >::m_src, Eigen::internal::matrix_exp_compute(), and tmp.
rows()
template<typename Derived > Index Eigen::MatrixExponentialReturnValue< Derived >::rows () const inline
 { return m_src.rows(); }
References Eigen::MatrixExponentialReturnValue< Derived >::m_src.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_src
template<typename Derived > const internal::ref_selector<Derived>::type Eigen::MatrixExponentialReturnValue< Derived >::m_src protected
Referenced by Eigen::MatrixExponentialReturnValue< Derived >::cols(), Eigen::MatrixExponentialReturnValue< Derived >::evalTo(), and Eigen::MatrixExponentialReturnValue< Derived >::rows().
The documentation for this struct was generated from the following files:
ForwardDeclarations.h
MatrixExponential.h