MercuryDPM: oomph::HelmholtzDtNMesh< ELEMENT > Class Template Reference
oomph::HelmholtzDtNMesh< ELEMENT > Class Template Reference
#include <helmholtz_bc_elements.h>
Public Member Functions
HelmholtzDtNMesh (const double &outer_radius, const unsigned &nfourier_terms)
void setup_gamma ()
of the mesh's constituent elements
void compute_fourier_components (Vector< std::complex< double >> &a_coeff_pos, Vector< std::complex< double >> &a_coeff_neg)
Vector< std::complex< double > > & gamma_at_gauss_point (FiniteElement *el_pt)
Vector< std::map< unsigned, std::complex< double > > > & d_gamma_at_gauss_point (FiniteElement *el_pt)
double & outer_radius ()
The outer radius.
unsigned & nfourier_terms ()
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void setup_boundary_element_info ()
virtual void setup_boundary_element_info (std::ostream &outfile)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Private Attributes
double Outer_radius
Outer radius.
unsigned Nfourier_terms
Nbr of Fourier terms used in the Gamma computation.
std::map< FiniteElement *, Vector< std::complex< double > > > Gamma_at_gauss_point
std::map< FiniteElement *, Vector< std::map< unsigned, std::complex< double > > > > D_Gamma_at_gauss_point
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Detailed Description
template<class ELEMENT>
class oomph::HelmholtzDtNMesh< ELEMENT >
/////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////// ================================================================= Mesh for DtN boundary condition elements – provides functionality to apply Sommerfeld radiation condtion
via DtN BC
Constructor & Destructor Documentation
HelmholtzDtNMesh()
template<class ELEMENT > oomph::HelmholtzDtNMesh< ELEMENT >::HelmholtzDtNMesh (const double & outer_radius, const unsigned & nfourier_terms) inline
Constructor: Specify radius of outer boundary and number of Fourier terms used in the computation of the gamma integral
       : Outer_radius(outer_radius), Nfourier_terms(nfourier_terms)
     {
     }
Member Function Documentation
compute_fourier_components()
template<class ELEMENT > void oomph::HelmholtzDtNMesh< ELEMENT >::compute_fourier_components (Vector< std::complex< double >> & a_coeff_pos, Vector< std::complex< double >> & a_coeff_neg)
Compute Fourier components of the solution – length of vector indicates number of terms to be computed.
////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// ================================================================ Compute Fourier components of the solution – length of
vector indicates number of terms to be computed.
   {
 #ifdef PARANOID
     if (a_coeff_pos.size() != a_coeff_neg.size())
     {
       std::ostringstream error_stream;
       error_stream << "a_coeff_pos and a_coeff_neg must have "
                    << "the same size. \n";
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Initialise
     unsigned n = a_coeff_pos.size();
     Vector<std::complex<double>> el_a_coeff_pos(n);
     Vector<std::complex<double>> el_a_coeff_neg(n);
     for (unsigned i = 0; i < n; i++)
     {
       a_coeff_pos[i] = std::complex<double>(0.0, 0.0);
       a_coeff_neg[i] = std::complex<double>(0.0, 0.0);
     }
     // Loop over elements e
     unsigned nel = this->nelement();
     for (unsigned e = 0; e < nel; e++)
     {
       // Get a pointer to element
       HelmholtzBCElementBase<ELEMENT>* el_pt =
         dynamic_cast<HelmholtzBCElementBase<ELEMENT>*>(this->element_pt(e));
       // Compute contribution
       el_pt->compute_contribution_to_fourier_components(el_a_coeff_pos,
                                                         el_a_coeff_neg);
       // Add to coefficients
       for (unsigned i = 0; i < n; i++)
       {
         a_coeff_pos[i] += el_a_coeff_pos[i];
         a_coeff_neg[i] += el_a_coeff_neg[i];
       }
     }
   }
References oomph::HelmholtzBCElementBase< ELEMENT >::compute_contribution_to_fourier_components(), e(), i, n, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
d_gamma_at_gauss_point()
template<class ELEMENT > Vector<std::map<unsigned, std::complex<double> > >& oomph::HelmholtzDtNMesh< ELEMENT >::d_gamma_at_gauss_point (FiniteElement * el_pt) inline
Derivative of Gamma integral w.r.t global unknown, evaluated at Gauss points for specified element
     {
       return D_Gamma_at_gauss_point[el_pt];
     }
References oomph::HelmholtzDtNMesh< ELEMENT >::D_Gamma_at_gauss_point.
gamma_at_gauss_point()
template<class ELEMENT > Vector<std::complex<double> >& oomph::HelmholtzDtNMesh< ELEMENT >::gamma_at_gauss_point (FiniteElement * el_pt) inline
Gamma integral evaluated at Gauss points for specified element
     {
       return Gamma_at_gauss_point[el_pt];
     }
References oomph::HelmholtzDtNMesh< ELEMENT >::Gamma_at_gauss_point.
nfourier_terms()
template<class ELEMENT > unsigned& oomph::HelmholtzDtNMesh< ELEMENT >::nfourier_terms () inline
Number of Fourier terms used in the computation of the gamma integral
     {
       return Nfourier_terms;
     }
References oomph::HelmholtzDtNMesh< ELEMENT >::Nfourier_terms.
outer_radius()
template<class ELEMENT > double& oomph::HelmholtzDtNMesh< ELEMENT >::outer_radius () inline
The outer radius.
     {
       return Outer_radius;
     }
References oomph::HelmholtzDtNMesh< ELEMENT >::Outer_radius.
setup_gamma()
template<class ELEMENT > void oomph::HelmholtzDtNMesh< ELEMENT >::setup_gamma
of the mesh's constituent elements
Compute and store the gamma integral at all integration points of the constituent elements.
================================================================ Compute and store the gamma integral and derivates
   {
 #ifdef PARANOID
     {
       // Loop over elements e
       unsigned nel = this->nelement();
       for (unsigned e = 0; e < nel; e++)
       {
         FiniteElement* fe_pt = finite_element_pt(e);
         unsigned nnod = fe_pt->nnode();
         for (unsigned j = 0; j < nnod; j++)
         {
           Node* nod_pt = fe_pt->node_pt(j);
           // Extract nodal coordinates from node:
           Vector<double> x(2);
           x[0] = nod_pt->x(0);
           x[1] = nod_pt->x(1);
           // Evaluate the radial distance
           double r = sqrt(x[0] * x[0] + x[1] * x[1]);
           // Check
           if (Outer_radius == 0.0)
           {
             throw OomphLibError("Outer radius for DtN BC must not be zero!",
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
           }
           if (std::fabs((r - this->Outer_radius) / Outer_radius) >
               ToleranceForHelmholtzOuterBoundary::Tol)
           {
             std::ostringstream error_stream;
             error_stream << "Node at " << x[0] << " " << x[1] << " has radius "
                          << r << " which does not "
                          << " agree with \nspecified outer radius "
                          << this->Outer_radius << " within relative tolerance "
                          << ToleranceForHelmholtzOuterBoundary::Tol
                          << ".\nYou can adjust the tolerance via\n"
                          << "ToleranceForHelmholtzOuterBoundary::Tol\n"
                          << "or recompile without PARANOID.\n";
             throw OomphLibError(error_stream.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
           }
         }
       }
     }
 #endif
     // Get Helmholtz parameter from bulk element
     HelmholtzDtNBoundaryElement<ELEMENT>* el_pt =
       dynamic_cast<HelmholtzDtNBoundaryElement<ELEMENT>*>(this->element_pt(0));
     double k =
       sqrt(dynamic_cast<ELEMENT*>(el_pt->bulk_element_pt())->k_squared());
     // Precompute factors in sum
     Vector<std::complex<double>> h_a(Nfourier_terms), hp_a(Nfourier_terms),
       q(Nfourier_terms);
     Hankel_functions_for_helmholtz_problem::Hankel_first(
       Nfourier_terms, Outer_radius * k, h_a, hp_a);
     for (unsigned i = 0; i < Nfourier_terms; i++)
     {
       q[i] = (k / (2.0 * MathematicalConstants::Pi)) * (hp_a[i] / h_a[i]);
     }
     // first loop over elements e
     unsigned nel = this->nelement();
     for (unsigned e = 0; e < nel; e++)
     {
       // Get a pointer to element
       HelmholtzDtNBoundaryElement<ELEMENT>* el_pt =
         dynamic_cast<HelmholtzDtNBoundaryElement<ELEMENT>*>(
           this->element_pt(e));
       // Set the value of n_intpt
       const unsigned n_intpt = el_pt->integral_pt()->nweight();
       // initialise gamma integral and its derivatives
       Vector<std::complex<double>> gamma_vector(n_intpt,
                                                 std::complex<double>(0.0, 0.0));
       Vector<std::map<unsigned, std::complex<double>>> d_gamma_vector(n_intpt);
       // Loop over the integration points
       for (unsigned ipt = 0; ipt < n_intpt; ipt++)
       {
         // Allocate and initialise coordinate
         unsigned ndim_local = el_pt->dim();
         Vector<double> x(ndim_local + 1, 0.0);
         // Set the Vector to hold local coordinates
         Vector<double> s(ndim_local, 0.0);
         for (unsigned i = 0; i < ndim_local; i++)
         {
           s[i] = el_pt->integral_pt()->knot(ipt, i);
         }
         // Get the coordinates of the integration point
         el_pt->interpolated_x(s, x);
         // Polar angle
         double phi = atan2(x[1], x[0]);
         // Elemental contribution to gamma integral and its derivative
         std::complex<double> gamma_con_p(0.0, 0.0), gamma_con_n(0.0, 0.0);
         std::map<unsigned, std::complex<double>> d_gamma_con_p, d_gamma_con_n;
         // loop over the Fourier terms
         for (unsigned nn = 0; nn < Nfourier_terms; nn++)
         {
           // Second loop over the element
           // to evaluate the complete integral
           for (unsigned ee = 0; ee < nel; ee++)
           {
             HelmholtzDtNBoundaryElement<ELEMENT>* eel_pt =
               dynamic_cast<HelmholtzDtNBoundaryElement<ELEMENT>*>(
                 this->element_pt(ee));
             // contribution of the positive term in the sum
             eel_pt->compute_gamma_contribution(
               phi, int(nn), gamma_con_p, d_gamma_con_p);
             // contribution of the negative term in the sum
             eel_pt->compute_gamma_contribution(
               phi, -int(nn), gamma_con_n, d_gamma_con_n);
             unsigned n_node = eel_pt->nnode();
             if (nn == 0)
             {
               gamma_vector[ipt] += q[nn] * gamma_con_p;
               for (unsigned l = 0; l < n_node; l++)
               {
                 // Add the contribution of the real local data
                 int local_unknown_p_real = eel_pt->nodal_local_eqn(
                   l, eel_pt->u_index_helmholtz().real());
                 if (local_unknown_p_real >= 0)
                 {
                   int global_unknown_p_real =
                     eel_pt->eqn_number(local_unknown_p_real);
                   d_gamma_vector[ipt][global_unknown_p_real] +=
                     q[nn] * d_gamma_con_p[global_unknown_p_real];
                 }
                 // Add the contribution of the imag local data
                 int local_unknown_p_imag = eel_pt->nodal_local_eqn(
                   l, eel_pt->u_index_helmholtz().imag());
                 if (local_unknown_p_imag >= 0)
                 {
                   int global_unknown_p_imag =
                     eel_pt->eqn_number(local_unknown_p_imag);
                   d_gamma_vector[ipt][global_unknown_p_imag] +=
                     q[nn] * d_gamma_con_p[global_unknown_p_imag];
                 }
               } // end of loop over the node
             } // End of if
             else
             {
               gamma_vector[ipt] += q[nn] * (gamma_con_p + gamma_con_n);
               for (unsigned l = 0; l < n_node; l++)
               {
                 // Add the contribution of the real local data
                 int local_unknown_real = eel_pt->nodal_local_eqn(
                   l, eel_pt->u_index_helmholtz().real());
                 if (local_unknown_real >= 0)
                 {
                   int global_unknown_real =
                     eel_pt->eqn_number(local_unknown_real);
                   d_gamma_vector[ipt][global_unknown_real] +=
                     q[nn] * (d_gamma_con_p[global_unknown_real] +
                              d_gamma_con_n[global_unknown_real]);
                 }
                 // Add the contribution of the imag local data
                 int local_unknown_imag = eel_pt->nodal_local_eqn(
                   l, eel_pt->u_index_helmholtz().imag());
                 if (local_unknown_imag >= 0)
                 {
                   int global_unknown_imag =
                     eel_pt->eqn_number(local_unknown_imag);
                   d_gamma_vector[ipt][global_unknown_imag] +=
                     q[nn] * (d_gamma_con_p[global_unknown_imag] +
                              d_gamma_con_n[global_unknown_imag]);
                 }
               } // end of loop over the node
             } // End of else
           } // End of second loop over the elements
         } // End of loop over Fourier terms
       } // end of loop over integration point
       // Store it in map
       Gamma_at_gauss_point[el_pt] = gamma_vector;
       D_Gamma_at_gauss_point[el_pt] = d_gamma_vector;
     } // end of first loop over element
   }
References atan2(), oomph::FaceElement::bulk_element_pt(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::compute_gamma_contribution(), oomph::FiniteElement::dim(), e(), oomph::GeneralisedElement::eqn_number(), boost::multiprecision::fabs(), oomph::Hankel_functions_for_helmholtz_problem::Hankel_first(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), j, k, oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, GlobalParameters::Outer_radius, oomph::MathematicalConstants::Pi, Eigen::numext::q, UniformPSDSelfTest::r, s, sqrt(), oomph::ToleranceForHelmholtzOuterBoundary::Tol, oomph::HelmholtzBCElementBase< ELEMENT >::u_index_helmholtz(), plotDoE::x, and oomph::Node::x().
Member Data Documentation
D_Gamma_at_gauss_point
template<class ELEMENT > std::map<FiniteElement*, Vector<std::map<unsigned, std::complex<double> > > > oomph::HelmholtzDtNMesh< ELEMENT >::D_Gamma_at_gauss_point private
Container to store the derivate of Gamma integral w.r.t global unknown evaluated at Gauss points for specified element
Referenced by oomph::HelmholtzDtNMesh< ELEMENT >::d_gamma_at_gauss_point().
Gamma_at_gauss_point
template<class ELEMENT > std::map<FiniteElement*, Vector<std::complex<double> > > oomph::HelmholtzDtNMesh< ELEMENT >::Gamma_at_gauss_point private
Container to store the gamma integral for given Gauss point and element
Referenced by oomph::HelmholtzDtNMesh< ELEMENT >::gamma_at_gauss_point().
Nfourier_terms
template<class ELEMENT > unsigned oomph::HelmholtzDtNMesh< ELEMENT >::Nfourier_terms private
Nbr of Fourier terms used in the Gamma computation.
Referenced by oomph::HelmholtzDtNMesh< ELEMENT >::nfourier_terms().
Outer_radius
template<class ELEMENT > double oomph::HelmholtzDtNMesh< ELEMENT >::Outer_radius private
Outer radius.
Referenced by oomph::HelmholtzDtNMesh< ELEMENT >::outer_radius().
The documentation for this class was generated from the following file:
helmholtz_bc_elements.h