MercuryDPM: oomph::QuarterPipeMesh< ELEMENT > Class Template Reference
oomph::QuarterPipeMesh< ELEMENT > Class Template Reference
#include <quarter_pipe_mesh.template.h>
Public Member Functions
QuarterPipeMesh (const unsigned &ntheta, const unsigned &nr, const unsigned &nz, const double &rmin, const double &rmax, const double &length, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual ~QuarterPipeMesh ()
Empty Destructor.
QuarterPipeDomain * domain_pt ()
Access function to domain.
QuarterPipeDomain * domain_pt () const
Access function to underlying domain.
Public Member Functions inherited from oomph::SimpleCubicMesh< ELEMENT >
SimpleCubicMesh (const unsigned &nx, const unsigned &ny, const unsigned &nz, const double &lx, const double &ly, const double &lz, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
SimpleCubicMesh (const unsigned &nx, const unsigned &ny, const unsigned &nz, const double &xmin, const double &xmax, const double &ymin, const double &ymax, const double &zmin, const double &zmax, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
const unsigned & nx () const
Access function for number of elements in x directions.
const unsigned & ny () const
Access function for number of elements in y directions.
const unsigned & nz () const
Access function for number of elements in y directions.
Public Member Functions inherited from oomph::BrickMeshBase
BrickMeshBase ()
Constructor (empty)
BrickMeshBase (const BrickMeshBase &)=delete
Broken copy constructor.
virtual ~BrickMeshBase ()
Broken assignment operator.
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Protected Attributes
unsigned Ntheta
Number of elements azimuthal direction.
unsigned Nr
Number of elements radial direction.
unsigned Nz
Number of elements axial direction.
double Rmin
Inner radius.
double Rmax
Outer radius.
double Length
Length.
QuarterPipeDomain * Domain_pt
Pointer to domain.
Protected Attributes inherited from oomph::SimpleCubicMesh< ELEMENT >
unsigned Nx
Number of elements in x direction.
unsigned Ny
Number of elements in y direction.
unsigned Nz
Number of elements in y direction.
double Xmin
Minimum value of x coordinate.
double Xmax
Maximum value of x coordinate.
double Ymin
Minimum value of y coordinate.
double Ymax
Minimum value of y coordinate.
double Zmin
Minimum value of z coordinate.
double Zmax
Maximum value of z coordinate.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::SimpleCubicMesh< ELEMENT >
void build_mesh (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Generic mesh construction function: contains all the hard work.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Detailed Description
template<class ELEMENT>
class oomph::QuarterPipeMesh< ELEMENT >
Non refineable quarter pipe mesh class Deform a simple cubic mesh into a quarter pipe r: radial direction theta: azimuthal direction z: axis direction
Constructor & Destructor Documentation
QuarterPipeMesh()
template<class ELEMENT > oomph::QuarterPipeMesh< ELEMENT >::QuarterPipeMesh (const unsigned & ntheta, const unsigned & nr, const unsigned & nz, const double & rmin, const double & rmax, const double & length, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass number of elements in various directions, the inner and outer radius and the length of the tube
     : SimpleCubicMesh<ELEMENT>(
         ntheta, nr, nz, 1.0, 1.0, length, time_stepper_pt)
   {
     // Mesh can only be built with 3D Qelements.
     MeshChecker::assert_geometric_element<QElementGeometricBase, ELEMENT>(3);
     // Variables declaration
     Ntheta = ntheta;
     Nr = nr;
     Nz = nz;
     Rmin = rmin;
     Rmax = rmax;
     Length = length;
     // Build macro element-based domain
     Domain_pt = new QuarterPipeDomain(ntheta, nr, nz, rmin, rmax, length);
     // Loop over all elements
     unsigned nel = this->nelement();
     for (unsigned e = 0; e < nel; e++)
     {
       // Try to cast to FiniteElement
       FiniteElement* el_pt = dynamic_cast<FiniteElement*>(this->element_pt(e));
       // Set macro element pointer
       el_pt->set_macro_elem_pt(Domain_pt->macro_element_pt(e));
     }
     // Update node coordinates with macroelement coordinates,
     // updating solid coordinates too.
     this->node_update(true);
     // Setup boundary coordinates on inner boundary (boundary 1)
     unsigned b = 1;
     unsigned nnod = this->nboundary_node(b);
     for (unsigned j = 0; j < nnod; j++)
     {
       // Pointer to node
       Node* nod_pt = this->boundary_node_pt(b, j);
       // Get the Eulerian coordinates
       double x = nod_pt->x(0);
       double y = nod_pt->x(1);
       double z = nod_pt->x(2);
       // Polar angle
       double phi = atan2(y, x);
       // Set boundary coordinates
       Vector<double> zeta(2);
       zeta[0] = z;
       zeta[1] = phi;
       nod_pt->set_coordinates_on_boundary(b, zeta);
     }
     this->Boundary_coordinate_exists[b] = true;
   }
References atan2(), b, oomph::Mesh::Boundary_coordinate_exists, oomph::Mesh::boundary_node_pt(), oomph::QuarterPipeMesh< ELEMENT >::Domain_pt, e(), oomph::Mesh::element_pt(), j, oomph::QuarterPipeMesh< ELEMENT >::Length, oomph::Domain::macro_element_pt(), oomph::Mesh::nboundary_node(), oomph::Mesh::nelement(), oomph::Mesh::node_update(), oomph::QuarterPipeMesh< ELEMENT >::Nr, oomph::QuarterPipeMesh< ELEMENT >::Ntheta, oomph::QuarterPipeMesh< ELEMENT >::Nz, oomph::SimpleCubicMesh< ELEMENT >::nz(), Global_Parameters::rmax, oomph::QuarterPipeMesh< ELEMENT >::Rmax, Global_Parameters::rmin, oomph::QuarterPipeMesh< ELEMENT >::Rmin, oomph::Node::set_coordinates_on_boundary(), oomph::FiniteElement::set_macro_elem_pt(), plotDoE::x, oomph::Node::x(), y, and Eigen::zeta().
~QuarterPipeMesh()
template<class ELEMENT > virtual oomph::QuarterPipeMesh< ELEMENT >::~QuarterPipeMesh () inline virtual
Empty Destructor.
     {
       delete Domain_pt;
     }
References oomph::QuarterPipeMesh< ELEMENT >::Domain_pt.
Member Function Documentation
domain_pt() [1/2]
template<class ELEMENT > QuarterPipeDomain* oomph::QuarterPipeMesh< ELEMENT >::domain_pt () inline
Access function to domain.
     {
       return Domain_pt;
     }
References oomph::QuarterPipeMesh< ELEMENT >::Domain_pt.
domain_pt() [2/2]
template<class ELEMENT > QuarterPipeDomain* oomph::QuarterPipeMesh< ELEMENT >::domain_pt () const inline
Access function to underlying domain.
     {
       return Domain_pt;
     }
References oomph::QuarterPipeMesh< ELEMENT >::Domain_pt.
Member Data Documentation
Domain_pt
template<class ELEMENT > QuarterPipeDomain* oomph::QuarterPipeMesh< ELEMENT >::Domain_pt protected
Pointer to domain.
Referenced by oomph::QuarterPipeMesh< ELEMENT >::domain_pt(), oomph::ElasticRefineableQuarterPipeMesh< ELEMENT >::ElasticRefineableQuarterPipeMesh(), oomph::QuarterPipeMesh< ELEMENT >::QuarterPipeMesh(), and oomph::QuarterPipeMesh< ELEMENT >::~QuarterPipeMesh().
Length
template<class ELEMENT > double oomph::QuarterPipeMesh< ELEMENT >::Length protected
Length.
Referenced by oomph::QuarterPipeMesh< ELEMENT >::QuarterPipeMesh().
Nr
template<class ELEMENT > unsigned oomph::QuarterPipeMesh< ELEMENT >::Nr protected
Number of elements radial direction.
Referenced by oomph::QuarterPipeMesh< ELEMENT >::QuarterPipeMesh().
Ntheta
template<class ELEMENT > unsigned oomph::QuarterPipeMesh< ELEMENT >::Ntheta protected
Number of elements azimuthal direction.
Referenced by oomph::QuarterPipeMesh< ELEMENT >::QuarterPipeMesh().
Nz
template<class ELEMENT > unsigned oomph::QuarterPipeMesh< ELEMENT >::Nz protected
Number of elements axial direction.
Referenced by oomph::QuarterPipeMesh< ELEMENT >::QuarterPipeMesh().
Rmax
template<class ELEMENT > double oomph::QuarterPipeMesh< ELEMENT >::Rmax protected
Outer radius.
Referenced by oomph::QuarterPipeMesh< ELEMENT >::QuarterPipeMesh().
Rmin
template<class ELEMENT > double oomph::QuarterPipeMesh< ELEMENT >::Rmin protected
Inner radius.
Referenced by oomph::QuarterPipeMesh< ELEMENT >::QuarterPipeMesh().
The documentation for this class was generated from the following files:
quarter_pipe_mesh.template.h
quarter_pipe_mesh.template.cc