MercuryDPM: Eigen::EigenSolver< MatrixType_ > Class Template Reference
Eigen::EigenSolver< MatrixType_ > Class Template Reference
Dense linear problems and decompositions » Reference » Eigenvalues_Module
Computes eigenvalues and eigenvectors of general matrices.
#include <EigenSolver.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime , ColsAtCompileTime = MatrixType::ColsAtCompileTime , Options = internal::traits<MatrixType>::Options , MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
}
typedef MatrixType_ MatrixType
Synonym for the template parameter MatrixType_.
typedef MatrixType::Scalar Scalar
Scalar type for matrices of type MatrixType.
typedef NumTraits< Scalar >::Real RealScalar
typedef Eigen::Index Index
typedef std::complex< RealScalar > ComplexScalar
Complex scalar type for MatrixType.
typedef Matrix< ComplexScalar, ColsAtCompileTime, 1, Options &~RowMajor, MaxColsAtCompileTime, 1 > EigenvalueType
Type for vector of eigenvalues as returned by eigenvalues().
typedef Matrix< ComplexScalar, RowsAtCompileTime, ColsAtCompileTime, Options, MaxRowsAtCompileTime, MaxColsAtCompileTime > EigenvectorsType
Type for matrix of eigenvectors as returned by eigenvectors().
Public Member Functions
EigenSolver ()
Default constructor.
EigenSolver (Index size)
Default constructor with memory preallocation.
template<typename InputType >
EigenSolver (const EigenBase< InputType > &matrix, bool computeEigenvectors=true)
Constructor; computes eigendecomposition of given matrix.
EigenvectorsType eigenvectors () const
Returns the eigenvectors of given matrix.
const MatrixType & pseudoEigenvectors () const
Returns the pseudo-eigenvectors of given matrix.
MatrixType pseudoEigenvalueMatrix () const
Returns the block-diagonal matrix in the pseudo-eigendecomposition.
const EigenvalueType & eigenvalues () const
Returns the eigenvalues of given matrix.
template<typename InputType >
EigenSolver & compute (const EigenBase< InputType > &matrix, bool computeEigenvectors=true)
Computes eigendecomposition of given matrix.
ComputationInfo info () const
EigenSolver & setMaxIterations (Index maxIters)
Sets the maximum number of iterations allowed.
Index getMaxIterations ()
Returns the maximum number of iterations.
template<typename InputType >
EigenSolver< MatrixType > & compute (const EigenBase< InputType > &matrix, bool computeEigenvectors)
Protected Types
typedef Matrix< Scalar, ColsAtCompileTime, 1, Options &~RowMajor, MaxColsAtCompileTime, 1 > ColumnVectorType
Static Protected Member Functions
static void check_template_parameters ()
Protected Attributes
MatrixType m_eivec
EigenvalueType m_eivalues
bool m_isInitialized
bool m_eigenvectorsOk
ComputationInfo m_info
RealSchur< MatrixType > m_realSchur
MatrixType m_matT
ColumnVectorType m_tmp
Private Member Functions
void doComputeEigenvectors ()
Detailed Description
template<typename MatrixType_>
class Eigen::EigenSolver< MatrixType_ >
Computes eigenvalues and eigenvectors of general matrices.
\eigenvalues_module
Template Parameters
MatrixType_ the type of the matrix of which we are computing the eigendecomposition; this is expected to be an instantiation of the Matrix class template. Currently, only real matrices are supported.
The eigenvalues and eigenvectors of a matrix \(A \) are scalars \(\lambda \) and vectors \(v \) such that \(Av = \lambda v \). If \(D \) is a diagonal matrix with the eigenvalues on the diagonal, and \(V \) is a matrix with the eigenvectors as its columns, then \(A V = V D \). The matrix \(V \) is almost always invertible, in which case we have \(A = V D V^{-1} \). This is called the eigendecomposition.
The eigenvalues and eigenvectors of a matrix may be complex, even when the matrix is real. However, we can choose real matrices \(V \) and \(D \) satisfying \(A V = V D \), just like the eigendecomposition, if the matrix \(D \) is not required to be diagonal, but if it is allowed to have blocks of the form
\[ \begin{bmatrix} u & v \\ -v & u \end{bmatrix} \]
(where \(u \) and \(v \) are real numbers) on the diagonal. These blocks correspond to complex eigenvalue pairs \(u \pm iv \). We call this variant of the eigendecomposition the pseudo-eigendecomposition.
Call the function compute() to compute the eigenvalues and eigenvectors of a given matrix. Alternatively, you can use the EigenSolver(const MatrixType&, bool) constructor which computes the eigenvalues and eigenvectors at construction time. Once the eigenvalue and eigenvectors are computed, they can be retrieved with the eigenvalues() and eigenvectors() functions. The pseudoEigenvalueMatrix() and pseudoEigenvectors() methods allow the construction of the pseudo-eigendecomposition.
The documentation for EigenSolver(const MatrixType&, bool) contains an example of the typical use of this class.
Note
The implementation is adapted from JAMA (public domain). Their code is based on EISPACK.
See also
MatrixBase::eigenvalues(), class ComplexEigenSolver, class SelfAdjointEigenSolver
Member Typedef Documentation
ColumnVectorType
template<typename MatrixType_ > typedef Matrix<Scalar, ColsAtCompileTime, 1, Options & ~RowMajor, MaxColsAtCompileTime, 1> Eigen::EigenSolver< MatrixType_ >::ColumnVectorType protected
ComplexScalar
template<typename MatrixType_ > typedef std::complex<RealScalar> Eigen::EigenSolver< MatrixType_ >::ComplexScalar
Complex scalar type for MatrixType.
This is std::complex<Scalar> if Scalar is real (e.g., float or double) and just Scalar if Scalar is complex.
EigenvalueType
template<typename MatrixType_ > typedef Matrix<ComplexScalar, ColsAtCompileTime, 1, Options & ~RowMajor, MaxColsAtCompileTime, 1> Eigen::EigenSolver< MatrixType_ >::EigenvalueType
Type for vector of eigenvalues as returned by eigenvalues().
This is a column vector with entries of type ComplexScalar. The length of the vector is the size of MatrixType.
EigenvectorsType
template<typename MatrixType_ > typedef Matrix<ComplexScalar, RowsAtCompileTime, ColsAtCompileTime, Options, MaxRowsAtCompileTime, MaxColsAtCompileTime> Eigen::EigenSolver< MatrixType_ >::EigenvectorsType
Type for matrix of eigenvectors as returned by eigenvectors().
This is a square matrix with entries of type ComplexScalar. The size is the same as the size of MatrixType.
Index
template<typename MatrixType_ > typedef Eigen::Index Eigen::EigenSolver< MatrixType_ >::Index
Deprecated:
since Eigen 3.3
MatrixType
template<typename MatrixType_ > typedef MatrixType_ Eigen::EigenSolver< MatrixType_ >::MatrixType
Synonym for the template parameter MatrixType_.
RealScalar
template<typename MatrixType_ > typedef NumTraits<Scalar>::Real Eigen::EigenSolver< MatrixType_ >::RealScalar
Scalar
template<typename MatrixType_ > typedef MatrixType::Scalar Eigen::EigenSolver< MatrixType_ >::Scalar
Scalar type for matrices of type MatrixType.
Member Enumeration Documentation
anonymous enum
template<typename MatrixType_ > anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
Options
MaxRowsAtCompileTime
MaxColsAtCompileTime
        {
     RowsAtCompileTime = MatrixType::RowsAtCompileTime,
     ColsAtCompileTime = MatrixType::ColsAtCompileTime,
     Options = internal::traits<MatrixType>::Options,
     MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
     MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
   };
Constructor & Destructor Documentation
EigenSolver() [1/3]
template<typename MatrixType_ > Eigen::EigenSolver< MatrixType_ >::EigenSolver () inline
Default constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via EigenSolver::compute(const MatrixType&, bool).
See also
compute() for an example.
       : m_eivec(), m_eivalues(), m_isInitialized(false), m_eigenvectorsOk(false), m_realSchur(), m_matT(), m_tmp() {}
EigenSolver() [2/3]
template<typename MatrixType_ > Eigen::EigenSolver< MatrixType_ >::EigenSolver (Index size) inline explicit
Default constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
EigenSolver()
       : m_eivec(size, size),
         m_eivalues(size),
         m_isInitialized(false),
         m_eigenvectorsOk(false),
         m_realSchur(size),
         m_matT(size, size),
         m_tmp(size) {}
EigenSolver() [3/3]
template<typename MatrixType_ > template<typename InputType > Eigen::EigenSolver< MatrixType_ >::EigenSolver (const EigenBase< InputType > & matrix, bool computeEigenvectors = true) inline explicit
Constructor; computes eigendecomposition of given matrix.
Parameters
[in] matrix Square matrix whose eigendecomposition is to be computed.
[in] computeEigenvectors If true, both the eigenvectors and the eigenvalues are computed; if false, only the eigenvalues are computed.
This constructor calls compute() to compute the eigenvalues and eigenvectors.
Example:
MatrixXd A = MatrixXd::Random(6, 6);
cout << "Here is a random 6x6 matrix, A:" << endl << A << endl << endl;
EigenSolver<MatrixXd> es(A);
cout << "The eigenvalues of A are:" << endl << es.eigenvalues() << endl;
cout << "The matrix of eigenvectors, V, is:" << endl << es.eigenvectors() << endl << endl;
complex<double> lambda = es.eigenvalues()[0];
cout << "Consider the first eigenvalue, lambda = " << lambda << endl;
VectorXcd v = es.eigenvectors().col(0);
cout << "If v is the corresponding eigenvector, then lambda * v = " << endl << lambda * v << endl;
cout << "... and A * v = " << endl << A.cast<complex<double> >() * v << endl << endl;
MatrixXcd D = es.eigenvalues().asDiagonal();
MatrixXcd V = es.eigenvectors();
cout << "Finally, V * D * V^(-1) = " << endl << V * D * V.inverse() << endl;
Output:
See also
compute()
       : m_eivec(matrix.rows(), matrix.cols()),
         m_eivalues(matrix.cols()),
         m_isInitialized(false),
         m_eigenvectorsOk(false),
         m_realSchur(matrix.cols()),
         m_matT(matrix.rows(), matrix.cols()),
         m_tmp(matrix.cols()) {
     compute(matrix.derived(), computeEigenvectors);
   }
References Eigen::EigenSolver< MatrixType_ >::compute(), and matrix().
Member Function Documentation
check_template_parameters()
template<typename MatrixType_ > static void Eigen::EigenSolver< MatrixType_ >::check_template_parameters () inline static protected
{
     EIGEN_STATIC_ASSERT_NON_INTEGER(Scalar);
     EIGEN_STATIC_ASSERT(!NumTraits<Scalar>::IsComplex, NUMERIC_TYPE_MUST_BE_REAL);
   }
References EIGEN_STATIC_ASSERT, and EIGEN_STATIC_ASSERT_NON_INTEGER.
compute() [1/2]
template<typename MatrixType_ > template<typename InputType > EigenSolver<MatrixType>& Eigen::EigenSolver< MatrixType_ >::compute (const EigenBase< InputType > & matrix, bool computeEigenvectors)
{
   check_template_parameters();
   using numext::isfinite;
   using std::abs;
   using std::sqrt;
   eigen_assert(matrix.cols() == matrix.rows());
   // Reduce to real Schur form.
   m_realSchur.compute(matrix.derived(), computeEigenvectors);
   m_info = m_realSchur.info();
   if (m_info == Success) {
     m_matT = m_realSchur.matrixT();
     if (computeEigenvectors) m_eivec = m_realSchur.matrixU();
     // Compute eigenvalues from matT
     m_eivalues.resize(matrix.cols());
     Index i = 0;
     while (i < matrix.cols()) {
       if (i == matrix.cols() - 1 || m_matT.coeff(i + 1, i) == Scalar(0)) {
         m_eivalues.coeffRef(i) = m_matT.coeff(i, i);
         if (!(isfinite)(m_eivalues.coeffRef(i))) {
           m_isInitialized = true;
           m_eigenvectorsOk = false;
           m_info = NumericalIssue;
           return *this;
         }
         ++i;
       } else {
         Scalar p = Scalar(0.5) * (m_matT.coeff(i, i) - m_matT.coeff(i + 1, i + 1));
         Scalar z;
         // Compute z = sqrt(abs(p * p + m_matT.coeff(i+1, i) * m_matT.coeff(i, i+1)));
         // without overflow
         {
           Scalar t0 = m_matT.coeff(i + 1, i);
           Scalar t1 = m_matT.coeff(i, i + 1);
           Scalar maxval = numext::maxi<Scalar>(abs(p), numext::maxi<Scalar>(abs(t0), abs(t1)));
           t0 /= maxval;
           t1 /= maxval;
           Scalar p0 = p / maxval;
           z = maxval * sqrt(abs(p0 * p0 + t0 * t1));
         }
         m_eivalues.coeffRef(i) = ComplexScalar(m_matT.coeff(i + 1, i + 1) + p, z);
         m_eivalues.coeffRef(i + 1) = ComplexScalar(m_matT.coeff(i + 1, i + 1) + p, -z);
         if (!((isfinite)(m_eivalues.coeffRef(i)) && (isfinite)(m_eivalues.coeffRef(i + 1)))) {
           m_isInitialized = true;
           m_eigenvectorsOk = false;
           m_info = NumericalIssue;
           return *this;
         }
         i += 2;
       }
     }
     // Compute eigenvectors.
     if (computeEigenvectors) doComputeEigenvectors();
   }
   m_isInitialized = true;
   m_eigenvectorsOk = computeEigenvectors;
   return *this;
 }
References abs(), eigen_assert, i, Eigen::numext::isfinite(), isfinite, matrix(), Eigen::NumericalIssue, p, p0, sqrt(), and Eigen::Success.
compute() [2/2]
template<typename MatrixType_ > template<typename InputType > EigenSolver& Eigen::EigenSolver< MatrixType_ >::compute (const EigenBase< InputType > & matrix, bool computeEigenvectors = true)
Computes eigendecomposition of given matrix.
Parameters
[in] matrix Square matrix whose eigendecomposition is to be computed.
[in] computeEigenvectors If true, both the eigenvectors and the eigenvalues are computed; if false, only the eigenvalues are computed.
Returns
Reference to *this
This function computes the eigenvalues of the real matrix matrix. The eigenvalues() function can be used to retrieve them. If computeEigenvectors is true, then the eigenvectors are also computed and can be retrieved by calling eigenvectors().
The matrix is first reduced to real Schur form using the RealSchur class. The Schur decomposition is then used to compute the eigenvalues and eigenvectors.
The cost of the computation is dominated by the cost of the Schur decomposition, which is very approximately \(25n^3 \) (where \(n \) is the size of the matrix) if computeEigenvectors is true, and \(10n^3 \) if computeEigenvectors is false.
This method reuses of the allocated data in the EigenSolver object.
Example:
EigenSolver<MatrixXf> es;
MatrixXf A = MatrixXf::Random(4, 4);
es.compute(A, /* computeEigenvectors = */ false);
cout << "The eigenvalues of A are: " << es.eigenvalues().transpose() << endl;
es.compute(A + MatrixXf::Identity(4, 4), false);  // re-use es to compute eigenvalues of A+I
cout << "The eigenvalues of A+I are: " << es.eigenvalues().transpose() << endl;
Output:
Referenced by __attribute__(), ctms_decompositions(), Eigen::EigenSolver< MatrixType_ >::EigenSolver(), eigensolver(), and eigensolver_verify_assert().
doComputeEigenvectors()
template<typename MatrixType > void Eigen::EigenSolver< MatrixType >::doComputeEigenvectors private
{
   using std::abs;
   const Index size = m_eivec.cols();
   const Scalar eps = NumTraits<Scalar>::epsilon();
   // inefficient! this is already computed in RealSchur
   Scalar norm(0);
   for (Index j = 0; j < size; ++j) {
     norm += m_matT.row(j).segment((std::max)(j - 1, Index(0)), size - (std::max)(j - 1, Index(0))).cwiseAbs().sum();
   }
   // Backsubstitute to find vectors of upper triangular form
   if (norm == Scalar(0)) {
     return;
   }
   for (Index n = size - 1; n >= 0; n--) {
     Scalar p = m_eivalues.coeff(n).real();
     Scalar q = m_eivalues.coeff(n).imag();
     // Scalar vector
     if (q == Scalar(0)) {
       Scalar lastr(0), lastw(0);
       Index l = n;
       m_matT.coeffRef(n, n) = Scalar(1);
       for (Index i = n - 1; i >= 0; i--) {
         Scalar w = m_matT.coeff(i, i) - p;
         Scalar r = m_matT.row(i).segment(l, n - l + 1).dot(m_matT.col(n).segment(l, n - l + 1));
         if (m_eivalues.coeff(i).imag() < Scalar(0)) {
           lastw = w;
           lastr = r;
         } else {
           l = i;
           if (m_eivalues.coeff(i).imag() == Scalar(0)) {
             if (w != Scalar(0))
               m_matT.coeffRef(i, n) = -r / w;
             else
               m_matT.coeffRef(i, n) = -r / (eps * norm);
           } else  // Solve real equations
           {
             Scalar x = m_matT.coeff(i, i + 1);
             Scalar y = m_matT.coeff(i + 1, i);
             Scalar denom = (m_eivalues.coeff(i).real() - p) * (m_eivalues.coeff(i).real() - p) +
                            m_eivalues.coeff(i).imag() * m_eivalues.coeff(i).imag();
             Scalar t = (x * lastr - lastw * r) / denom;
             m_matT.coeffRef(i, n) = t;
             if (abs(x) > abs(lastw))
               m_matT.coeffRef(i + 1, n) = (-r - w * t) / x;
             else
               m_matT.coeffRef(i + 1, n) = (-lastr - y * t) / lastw;
           }
           // Overflow control
           Scalar t = abs(m_matT.coeff(i, n));
           if ((eps * t) * t > Scalar(1)) m_matT.col(n).tail(size - i) /= t;
         }
       }
     } else if (q < Scalar(0) && n > 0)  // Complex vector
     {
       Scalar lastra(0), lastsa(0), lastw(0);
       Index l = n - 1;
       // Last vector component imaginary so matrix is triangular
       if (abs(m_matT.coeff(n, n - 1)) > abs(m_matT.coeff(n - 1, n))) {
         m_matT.coeffRef(n - 1, n - 1) = q / m_matT.coeff(n, n - 1);
         m_matT.coeffRef(n - 1, n) = -(m_matT.coeff(n, n) - p) / m_matT.coeff(n, n - 1);
       } else {
         ComplexScalar cc =
             ComplexScalar(Scalar(0), -m_matT.coeff(n - 1, n)) / ComplexScalar(m_matT.coeff(n - 1, n - 1) - p, q);
         m_matT.coeffRef(n - 1, n - 1) = numext::real(cc);
         m_matT.coeffRef(n - 1, n) = numext::imag(cc);
       }
       m_matT.coeffRef(n, n - 1) = Scalar(0);
       m_matT.coeffRef(n, n) = Scalar(1);
       for (Index i = n - 2; i >= 0; i--) {
         Scalar ra = m_matT.row(i).segment(l, n - l + 1).dot(m_matT.col(n - 1).segment(l, n - l + 1));
         Scalar sa = m_matT.row(i).segment(l, n - l + 1).dot(m_matT.col(n).segment(l, n - l + 1));
         Scalar w = m_matT.coeff(i, i) - p;
         if (m_eivalues.coeff(i).imag() < Scalar(0)) {
           lastw = w;
           lastra = ra;
           lastsa = sa;
         } else {
           l = i;
           if (m_eivalues.coeff(i).imag() == RealScalar(0)) {
             ComplexScalar cc = ComplexScalar(-ra, -sa) / ComplexScalar(w, q);
             m_matT.coeffRef(i, n - 1) = numext::real(cc);
             m_matT.coeffRef(i, n) = numext::imag(cc);
           } else {
             // Solve complex equations
             Scalar x = m_matT.coeff(i, i + 1);
             Scalar y = m_matT.coeff(i + 1, i);
             Scalar vr = (m_eivalues.coeff(i).real() - p) * (m_eivalues.coeff(i).real() - p) +
                         m_eivalues.coeff(i).imag() * m_eivalues.coeff(i).imag() - q * q;
             Scalar vi = (m_eivalues.coeff(i).real() - p) * Scalar(2) * q;
             if ((vr == Scalar(0)) && (vi == Scalar(0)))
               vr = eps * norm * (abs(w) + abs(q) + abs(x) + abs(y) + abs(lastw));
             ComplexScalar cc = ComplexScalar(x * lastra - lastw * ra + q * sa, x * lastsa - lastw * sa - q * ra) /
                                ComplexScalar(vr, vi);
             m_matT.coeffRef(i, n - 1) = numext::real(cc);
             m_matT.coeffRef(i, n) = numext::imag(cc);
             if (abs(x) > (abs(lastw) + abs(q))) {
               m_matT.coeffRef(i + 1, n - 1) = (-ra - w * m_matT.coeff(i, n - 1) + q * m_matT.coeff(i, n)) / x;
               m_matT.coeffRef(i + 1, n) = (-sa - w * m_matT.coeff(i, n) - q * m_matT.coeff(i, n - 1)) / x;
             } else {
               cc = ComplexScalar(-lastra - y * m_matT.coeff(i, n - 1), -lastsa - y * m_matT.coeff(i, n)) /
                    ComplexScalar(lastw, q);
               m_matT.coeffRef(i + 1, n - 1) = numext::real(cc);
               m_matT.coeffRef(i + 1, n) = numext::imag(cc);
             }
           }
           // Overflow control
           Scalar t = numext::maxi<Scalar>(abs(m_matT.coeff(i, n - 1)), abs(m_matT.coeff(i, n)));
           if ((eps * t) * t > Scalar(1)) m_matT.block(i, n - 1, size - i, 2) /= t;
         }
       }
       // We handled a pair of complex conjugate eigenvalues, so need to skip them both
       n--;
     } else {
       eigen_assert(0 && "Internal bug in EigenSolver (INF or NaN has not been detected)");  // this should not happen
     }
   }
   // Back transformation to get eigenvectors of original matrix
   for (Index j = size - 1; j >= 0; j--) {
     m_tmp.noalias() = m_eivec.leftCols(j + 1) * m_matT.col(j).segment(0, j + 1);
     m_eivec.col(j) = m_tmp;
   }
 }
References abs(), eigen_assert, CRBond_Bessel::eps, oomph::SarahBL::epsilon, i, imag(), j, max, n, p, Eigen::numext::q, UniformPSDSelfTest::r, size, plotPSD::t, w, plotDoE::x, and y.
eigenvalues()
template<typename MatrixType_ > const EigenvalueType& Eigen::EigenSolver< MatrixType_ >::eigenvalues () const inline
Returns the eigenvalues of given matrix.
Returns
A const reference to the column vector containing the eigenvalues.
Precondition
Either the constructor EigenSolver(const MatrixType&,bool) or the member function compute(const MatrixType&, bool) has been called before.
The eigenvalues are repeated according to their algebraic multiplicity, so there are as many eigenvalues as rows in the matrix. The eigenvalues are not sorted in any particular order.
Example:
MatrixXd ones = MatrixXd::Ones(3, 3);
EigenSolver<MatrixXd> es(ones, false);
cout << "The eigenvalues of the 3x3 matrix of ones are:" << endl << es.eigenvalues() << endl;
Output:
See also
eigenvectors(), pseudoEigenvalueMatrix(), MatrixBase::eigenvalues()
{
     eigen_assert(m_isInitialized && "EigenSolver is not initialized.");
     return m_eivalues;
   }
References eigen_assert, Eigen::EigenSolver< MatrixType_ >::m_eivalues, and Eigen::EigenSolver< MatrixType_ >::m_isInitialized.
Referenced by eigensolver(), eigensolver_generic_extra(), eigensolver_verify_assert(), and Eigen::internal::eigenvalues_selector< Derived, false >::run().
eigenvectors()
template<typename MatrixType > EigenSolver< MatrixType >::EigenvectorsType Eigen::EigenSolver< MatrixType >::eigenvectors
Returns the eigenvectors of given matrix.
Returns
Matrix whose columns are the (possibly complex) eigenvectors.
Precondition
Either the constructor EigenSolver(const MatrixType&,bool) or the member function compute(const MatrixType&, bool) has been called before, and computeEigenvectors was set to true (the default).
Column \(k \) of the returned matrix is an eigenvector corresponding to eigenvalue number \(k \) as returned by eigenvalues(). The eigenvectors are normalized to have (Euclidean) norm equal to one. The matrix returned by this function is the matrix \(V \) in the eigendecomposition \(A = V D V^{-1} \), if it exists.
Example:
MatrixXd ones = MatrixXd::Ones(3, 3);
EigenSolver<MatrixXd> es(ones);
cout << "The first eigenvector of the 3x3 matrix of ones is:" << endl << es.eigenvectors().col(0) << endl;
Output:
See also
eigenvalues(), pseudoEigenvectors()
{
   eigen_assert(m_isInitialized && "EigenSolver is not initialized.");
   eigen_assert(m_eigenvectorsOk && "The eigenvectors have not been computed together with the eigenvalues.");
   const RealScalar precision = RealScalar(2) * NumTraits<RealScalar>::epsilon();
   Index n = m_eivec.cols();
   EigenvectorsType matV(n, n);
   for (Index j = 0; j < n; ++j) {
     if (internal::isMuchSmallerThan(numext::imag(m_eivalues.coeff(j)), numext::real(m_eivalues.coeff(j)), precision) ||
         j + 1 == n) {
       // we have a real eigen value
       matV.col(j) = m_eivec.col(j).template cast<ComplexScalar>();
       matV.col(j).normalize();
     } else {
       // we have a pair of complex eigen values
       for (Index i = 0; i < n; ++i) {
         matV.coeffRef(i, j) = ComplexScalar(m_eivec.coeff(i, j), m_eivec.coeff(i, j + 1));
         matV.coeffRef(i, j + 1) = ComplexScalar(m_eivec.coeff(i, j), -m_eivec.coeff(i, j + 1));
       }
       matV.col(j).normalize();
       matV.col(j + 1).normalize();
       ++j;
     }
   }
   return matV;
 }
References Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::coeffRef(), eigen_assert, oomph::SarahBL::epsilon, i, imag(), Eigen::internal::isMuchSmallerThan(), j, and n.
Referenced by __attribute__(), eigensolver(), eigensolver_generic_extra(), and eigensolver_verify_assert().
getMaxIterations()
template<typename MatrixType_ > Index Eigen::EigenSolver< MatrixType_ >::getMaxIterations () inline
Returns the maximum number of iterations.
 { return m_realSchur.getMaxIterations(); }
References Eigen::RealSchur< MatrixType_ >::getMaxIterations(), and Eigen::EigenSolver< MatrixType_ >::m_realSchur.
Referenced by eigensolver().
info()
template<typename MatrixType_ > ComputationInfo Eigen::EigenSolver< MatrixType_ >::info () const inline
Returns
NumericalIssue if the input contains INF or NaN values or overflow occurred. Returns Success otherwise.
{
     eigen_assert(m_isInitialized && "EigenSolver is not initialized.");
     return m_info;
   }
References eigen_assert, Eigen::EigenSolver< MatrixType_ >::m_info, and Eigen::EigenSolver< MatrixType_ >::m_isInitialized.
Referenced by eigensolver().
pseudoEigenvalueMatrix()
template<typename MatrixType > MatrixType Eigen::EigenSolver< MatrixType >::pseudoEigenvalueMatrix
Returns the block-diagonal matrix in the pseudo-eigendecomposition.
Returns
A block-diagonal matrix.
Precondition
Either the constructor EigenSolver(const MatrixType&,bool) or the member function compute(const MatrixType&, bool) has been called before.
The matrix \(D \) returned by this function is real and block-diagonal. The blocks on the diagonal are either 1-by-1 or 2-by-2 blocks of the form \(\begin{bmatrix} u & v \\ -v & u \end{bmatrix} \). These blocks are not sorted in any particular order. The matrix \(D \) and the matrix \(V \) returned by pseudoEigenvectors() satisfy \(AV = VD \).
See also
pseudoEigenvectors() for an example, eigenvalues()
{
   eigen_assert(m_isInitialized && "EigenSolver is not initialized.");
   const RealScalar precision = RealScalar(2) * NumTraits<RealScalar>::epsilon();
   const Index n = m_eivalues.rows();
   MatrixType matD = MatrixType::Zero(n, n);
   Index i = 0;
   for (; i < n - 1; ++i) {
     RealScalar real = numext::real(m_eivalues.coeff(i));
     RealScalar imag = numext::imag(m_eivalues.coeff(i));
     matD.coeffRef(i, i) = real;
     if (!internal::isMuchSmallerThan(imag, real, precision)) {
       matD.coeffRef(i, i + 1) = imag;
       matD.coeffRef(i + 1, i) = -imag;
       matD.coeffRef(i + 1, i + 1) = real;
       ++i;
     }
   }
   if (i == n - 1) {
     matD.coeffRef(i, i) = numext::real(m_eivalues.coeff(i));
   }
   return matD;
 }
References eigen_assert, oomph::SarahBL::epsilon, i, imag(), Eigen::imag(), Eigen::internal::isMuchSmallerThan(), n, Eigen::real(), and oomph::PseudoSolidHelper::Zero.
Referenced by eigensolver(), eigensolver_generic_extra(), and eigensolver_verify_assert().
pseudoEigenvectors()
template<typename MatrixType_ > const MatrixType& Eigen::EigenSolver< MatrixType_ >::pseudoEigenvectors () const inline
Returns the pseudo-eigenvectors of given matrix.
Returns
Const reference to matrix whose columns are the pseudo-eigenvectors.
Precondition
Either the constructor EigenSolver(const MatrixType&,bool) or the member function compute(const MatrixType&, bool) has been called before, and computeEigenvectors was set to true (the default).
The real matrix \(V \) returned by this function and the block-diagonal matrix \(D \) returned by pseudoEigenvalueMatrix() satisfy \(AV = VD \).
Example:
MatrixXd A = MatrixXd::Random(6, 6);
cout << "Here is a random 6x6 matrix, A:" << endl << A << endl << endl;
EigenSolver<MatrixXd> es(A);
MatrixXd D = es.pseudoEigenvalueMatrix();
MatrixXd V = es.pseudoEigenvectors();
cout << "The pseudo-eigenvalue matrix D is:" << endl << D << endl;
cout << "The pseudo-eigenvector matrix V is:" << endl << V << endl;
cout << "Finally, V * D * V^(-1) = " << endl << V * D * V.inverse() << endl;
Output:
See also
pseudoEigenvalueMatrix(), eigenvectors()
{
     eigen_assert(m_isInitialized && "EigenSolver is not initialized.");
     eigen_assert(m_eigenvectorsOk && "The eigenvectors have not been computed together with the eigenvalues.");
     return m_eivec;
   }
References eigen_assert, Eigen::EigenSolver< MatrixType_ >::m_eigenvectorsOk, Eigen::EigenSolver< MatrixType_ >::m_eivec, and Eigen::EigenSolver< MatrixType_ >::m_isInitialized.
Referenced by eigensolver(), eigensolver_generic_extra(), and eigensolver_verify_assert().
setMaxIterations()
template<typename MatrixType_ > EigenSolver& Eigen::EigenSolver< MatrixType_ >::setMaxIterations (Index maxIters) inline
Sets the maximum number of iterations allowed.
{
     m_realSchur.setMaxIterations(maxIters);
     return *this;
   }
References Eigen::EigenSolver< MatrixType_ >::m_realSchur, and Eigen::RealSchur< MatrixType_ >::setMaxIterations().
Referenced by eigensolver().
Member Data Documentation
m_eigenvectorsOk
template<typename MatrixType_ > bool Eigen::EigenSolver< MatrixType_ >::m_eigenvectorsOk protected
Referenced by Eigen::EigenSolver< MatrixType_ >::pseudoEigenvectors().
m_eivalues
template<typename MatrixType_ > EigenvalueType Eigen::EigenSolver< MatrixType_ >::m_eivalues protected
Referenced by Eigen::EigenSolver< MatrixType_ >::eigenvalues().
m_eivec
template<typename MatrixType_ > MatrixType Eigen::EigenSolver< MatrixType_ >::m_eivec protected
Referenced by Eigen::EigenSolver< MatrixType_ >::pseudoEigenvectors().
m_info
template<typename MatrixType_ > ComputationInfo Eigen::EigenSolver< MatrixType_ >::m_info protected
Referenced by Eigen::EigenSolver< MatrixType_ >::info().
m_isInitialized
template<typename MatrixType_ > bool Eigen::EigenSolver< MatrixType_ >::m_isInitialized protected
Referenced by Eigen::EigenSolver< MatrixType_ >::eigenvalues(), Eigen::EigenSolver< MatrixType_ >::info(), and Eigen::EigenSolver< MatrixType_ >::pseudoEigenvectors().
m_matT
template<typename MatrixType_ > MatrixType Eigen::EigenSolver< MatrixType_ >::m_matT protected
m_realSchur
template<typename MatrixType_ > RealSchur<MatrixType> Eigen::EigenSolver< MatrixType_ >::m_realSchur protected
Referenced by Eigen::EigenSolver< MatrixType_ >::getMaxIterations(), and Eigen::EigenSolver< MatrixType_ >::setMaxIterations().
m_tmp
template<typename MatrixType_ > ColumnVectorType Eigen::EigenSolver< MatrixType_ >::m_tmp protected
The documentation for this class was generated from the following file:
EigenSolver.h