MercuryDPM: oomph::AnnularDomain Class Reference
oomph::AnnularDomain Class Reference
Annular domain.
#include <annular_domain.h>
Public Member Functions
AnnularDomain (const double &azimuthal_fraction, const unsigned &ntheta, const unsigned &nr, const double &a, const double &h, const double &phi)
AnnularDomain (const AnnularDomain &)=delete
Broken copy constructor.
void operator= (const AnnularDomain &)=delete
Broken assignment operator.
~AnnularDomain ()
Destructor: Empty; cleanup done in base class.
void macro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
Public Member Functions inherited from oomph::Domain
Domain ()
Constructor.
Domain (const Domain &)=delete
Broken copy constructor.
void operator= (const Domain &)=delete
Broken assignment operator.
virtual ~Domain ()
MacroElement * macro_element_pt (const unsigned &i)
Access to i-th macro element.
unsigned nmacro_element ()
Number of macro elements in domain.
void output (const std::string &filename, const unsigned &nplot)
Output macro elements.
void output (std::ostream &outfile, const unsigned &nplot)
Output macro elements.
virtual void macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void output_macro_element_boundaries (const std::string &filename, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
void output_macro_element_boundaries (std::ostream &outfile, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
virtual void dmacro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void dmacro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void dmacro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void d2macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
Private Attributes
double Azimuthal_fraction
Azimuthal fraction.
double Inner_radius
Inner radius.
double Thickness
Thickness.
unsigned Ntheta
Number of macro elements in azimuthal direction.
unsigned Nr
Number of macro elements in radial direction.
double Phi
Rotation angle.
Additional Inherited Members
Protected Attributes inherited from oomph::Domain
Vector< MacroElement * > Macro_element_pt
Vector of pointers to macro elements.
Detailed Description
Annular domain.
Constructor & Destructor Documentation
AnnularDomain() [1/2]
oomph::AnnularDomain::AnnularDomain (const double & azimuthal_fraction, const unsigned & ntheta, const unsigned & nr, const double & a, const double & h, const double & phi) inline
Constructor: Specify azimuthal fraction (1.0 is 360 degrees) number of macro elements in azimuthal and radial direction, inner radius and thickness. Rotate mesh by angle phi.
       : Azimuthal_fraction(azimuthal_fraction),
         Inner_radius(a),
         Thickness(h),
         Ntheta(ntheta),
         Nr(nr),
         Phi(phi)
     {
       const unsigned n_macro = ntheta * nr;
       Macro_element_pt.resize(n_macro);
       // Create the macro elements
       for (unsigned i = 0; i < n_macro; i++)
       {
         Macro_element_pt[i] = new QMacroElement<2>(this, i);
       }
     }
References i, and oomph::Domain::Macro_element_pt.
AnnularDomain() [2/2]
oomph::AnnularDomain::AnnularDomain (const AnnularDomain &) delete
Broken copy constructor.
~AnnularDomain()
oomph::AnnularDomain::~AnnularDomain () inline
Destructor: Empty; cleanup done in base class.
 {}
Member Function Documentation
macro_element_boundary()
void oomph::AnnularDomain::macro_element_boundary (const unsigned & t, const unsigned & imacro, const unsigned & idirect, const Vector< double > & s, Vector< double > & f) virtual
Vector representation of the i_macro-th macro element boundary i_direct (N/S/W/E) at time level t (t=0: present; t>0: previous): f(s).
////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// Vector representation of the imacro-th macro element boundary idirect (N/S/W/E) at time level t (t=0: present; t>0: previous): f(s)
Implements oomph::Domain.
   {
     using namespace QuadTreeNames;
     // Get coordinates of macro element
     unsigned i_theta = imacro % Ntheta;
     unsigned i_r = (imacro - i_theta) / Ntheta;
     // Angle and radius limits
     double theta_lo = Azimuthal_fraction * 2.0 * MathematicalConstants::Pi *
                       double(i_theta) / double(Ntheta);
     double theta_hi = Azimuthal_fraction * 2.0 * MathematicalConstants::Pi *
                       double(i_theta + 1) / double(Ntheta);
     // Revert direction (convoluted -- don't ask. It mirrors what happens
     // in the mesh...
     theta_lo = -MathematicalConstants::Pi +
                Azimuthal_fraction * 2.0 * MathematicalConstants::Pi - theta_lo;
     theta_hi = -MathematicalConstants::Pi +
                Azimuthal_fraction * 2.0 * MathematicalConstants::Pi - theta_hi;
     double r_lo = Inner_radius + Thickness * double(i_r) / double(Nr);
     double r_hi = Inner_radius + Thickness * double(i_r + 1) / double(Nr);
     // Actual radius and angle
     double r = 0.0;
     double theta = 0.0;
     // Which direction?
     switch (idirect)
     {
       case N:
         theta = theta_lo + 0.5 * (s[0] + 1.0) * (theta_hi - theta_lo);
         r = r_hi;
         break;
       case S:
         theta = theta_lo + 0.5 * (s[0] + 1.0) * (theta_hi - theta_lo);
         r = r_lo;
         break;
       case W:
         theta = theta_lo;
         r = r_lo + 0.5 * (s[0] + 1.0) * (r_hi - r_lo);
         break;
       case E:
         theta = theta_hi;
         r = r_lo + 0.5 * (s[0] + 1.0) * (r_hi - r_lo);
         break;
       default:
         std::ostringstream error_stream;
         error_stream << "idirect is " << idirect << " not one of N, S, W, E"
                      << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     f[0] = r * cos(theta + Phi);
     f[1] = r * sin(theta + Phi);
   }
References Azimuthal_fraction, cos(), Global_Physical_Variables::E, f(), Inner_radius, N, Nr, Ntheta, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, Phi, oomph::MathematicalConstants::Pi, UniformPSDSelfTest::r, s, oomph::QuadTreeNames::S, sin(), BiharmonicTestFunctions2::theta, Thickness, and oomph::QuadTreeNames::W.
operator=()
void oomph::AnnularDomain::operator= (const AnnularDomain &) delete
Broken assignment operator.
Member Data Documentation
Azimuthal_fraction
double oomph::AnnularDomain::Azimuthal_fraction private
Azimuthal fraction.
Referenced by macro_element_boundary().
Inner_radius
double oomph::AnnularDomain::Inner_radius private
Inner radius.
Referenced by macro_element_boundary().
Nr
unsigned oomph::AnnularDomain::Nr private
Number of macro elements in radial direction.
Referenced by macro_element_boundary().
Ntheta
unsigned oomph::AnnularDomain::Ntheta private
Number of macro elements in azimuthal direction.
Referenced by macro_element_boundary().
Phi
double oomph::AnnularDomain::Phi private
Rotation angle.
Referenced by macro_element_boundary().
Thickness
double oomph::AnnularDomain::Thickness private
Thickness.
Referenced by macro_element_boundary().
The documentation for this class was generated from the following file:
annular_domain.h