MercuryDPM: Eigen::internal::unary_evaluator< SparseView< ArgType >, IteratorBased >::InnerIterator Class Reference
Eigen::internal::unary_evaluator< SparseView< ArgType >, IteratorBased >::InnerIterator Class Reference
#include <SparseView.h>
Public Member Functions
EIGEN_STRONG_INLINE InnerIterator (const unary_evaluator &sve, Index outer)
EIGEN_STRONG_INLINE InnerIterator & operator++ ()
Protected Types
typedef XprType::Scalar Scalar
Protected Attributes
const XprType & m_view
Private Member Functions
void incrementToNonZero ()
Member Typedef Documentation
Scalar
template<typename ArgType > typedef XprType::Scalar Eigen::internal::unary_evaluator< SparseView< ArgType >, IteratorBased >::InnerIterator::Scalar protected
Constructor & Destructor Documentation
InnerIterator()
template<typename ArgType > EIGEN_STRONG_INLINE Eigen::internal::unary_evaluator< SparseView< ArgType >, IteratorBased >::InnerIterator::InnerIterator (const unary_evaluator< SparseView< ArgType >, IteratorBased > & sve, Index outer) inline
         : EvalIterator(sve.m_argImpl, outer), m_view(sve.m_view) {
       incrementToNonZero();
     }
Member Function Documentation
incrementToNonZero()
template<typename ArgType > void Eigen::internal::unary_evaluator< SparseView< ArgType >, IteratorBased >::InnerIterator::incrementToNonZero () inline private
{
       while ((bool(*this)) && internal::isMuchSmallerThan(value(), m_view.reference(), m_view.epsilon())) {
         EvalIterator::operator++();
       }
     }
References Eigen::SparseView< MatrixType >::epsilon(), Eigen::internal::isMuchSmallerThan(), Eigen::bfloat16_impl::operator++(), Eigen::SparseView< MatrixType >::reference(), and Eigen::value.
operator++()
template<typename ArgType > EIGEN_STRONG_INLINE InnerIterator& Eigen::internal::unary_evaluator< SparseView< ArgType >, IteratorBased >::InnerIterator::operator++ () inline
{
       EvalIterator::operator++();
       incrementToNonZero();
       return *this;
     }
References Eigen::bfloat16_impl::operator++().
Member Data Documentation
m_view
template<typename ArgType > const XprType& Eigen::internal::unary_evaluator< SparseView< ArgType >, IteratorBased >::InnerIterator::m_view protected
The documentation for this class was generated from the following file:
SparseView.h