MercuryDPM: oomph::BrickMeshBase Class Reference
oomph::BrickMeshBase Class Reference
Base class for brick meshes (meshes made of 3D brick elements).
#include <brick_mesh.h>
Public Member Functions
BrickMeshBase ()
Constructor (empty)
BrickMeshBase (const BrickMeshBase &)=delete
Broken copy constructor.
virtual ~BrickMeshBase ()
Broken assignment operator.
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Detailed Description
Base class for brick meshes (meshes made of 3D brick elements).
//////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
BrickMeshBase() [1/2]
oomph::BrickMeshBase::BrickMeshBase () inline
Constructor (empty)
 {}
BrickMeshBase() [2/2]
oomph::BrickMeshBase::BrickMeshBase (const BrickMeshBase &) delete
Broken copy constructor.
~BrickMeshBase()
virtual oomph::BrickMeshBase::~BrickMeshBase () inline virtual
Broken assignment operator.
Destructor (empty)
 {}
Member Function Documentation
setup_boundary_element_info() [1/2]
void oomph::BrickMeshBase::setup_boundary_element_info () inline virtual
Setup lookup schemes which establish whic elements are located next to mesh's boundaries (wrapper to suppress doc).
Reimplemented from oomph::Mesh.
     {
       std::ofstream outfile;
       setup_boundary_element_info(outfile);
     }
Referenced by oomph::EighthSphereMesh< ELEMENT >::EighthSphereMesh(), oomph::QuarterTubeMesh< ELEMENT >::QuarterTubeMesh(), oomph::RefineableSolidCubicMesh< ELEMENT >::setup_boundary_element_info(), and oomph::TubeMesh< ELEMENT >::TubeMesh().
setup_boundary_element_info() [2/2]
void oomph::BrickMeshBase::setup_boundary_element_info (std::ostream & outfile) virtual
Setup lookup schemes which establish whic elements are located next to mesh's boundaries. Doc in outfile (if it's open).
//////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// Setup lookup schemes which establish which elements are located next to which boundaries (Doc to outfile if it's open).
Reimplemented from oomph::Mesh.
   {
     // Martina's fixed and commented version of the code.
     // Define variable doc and set the initial value to False.
     bool doc = false;
     // If file declared in outfile exists,set doc=true to enable writing to
     // stream
     if (outfile) doc = true;
     // Number of boundaries. Gives the value assigned by the function
     // nboundary()
     unsigned nbound = nboundary();
     if (doc)
     {
       outfile << "The number of boundaries is " << nbound << "\n";
     }
     // Wipe/allocate storage for arrays
     // Command clear will reomve all elements of vectors
     // Command resize will adapt pointer to correct boundary size. Internal data
     Boundary_element_pt.clear();
     Face_index_at_boundary.clear();
     Boundary_element_pt.resize(nbound);
     Face_index_at_boundary.resize(nbound);
     // Temporary vector of vectors of pointers to elements on the boundaries:
     // vector_of_boundary_element_pt[i] is the vector of pointers to all
     // elements that have nodes on boundary i.
     // This is not a set to ensure UNIQUE ordering on every processor
     // There are a number of elements with nodes on each boundary.
     // For each boundary we store the appropriate elements in a vector.
     // There is therefore a vector for each boundary, which we store in
     // another vector, i.e. a matrix (vector of vectors).
     // Then vector_of_boundary_element_pt[0] is a vector of pointers to elements
     // with nodes on boundary 0 and vector_of_boundary_element_pt[0][0] is the
     // first element with nodes on boundary 0.
     Vector<Vector<FiniteElement*>> vector_of_boundary_element_pt;
     vector_of_boundary_element_pt.resize(nbound);
     // Matrix map for working out the fixed local coord for elements on boundary
     // Calling pointer to FiniteElement and pointer to  Vector<int> defining
     // the matrix to identify each element on boundary
     MapMatrixMixed<unsigned, FiniteElement*, Vector<int>*> boundary_identifier;
     // Temporary container to store pointers to temporary vectors
     // so they can be deleted. Creating storage to store these
     // temporary vectors of vectors of pointers previously defined
     Vector<Vector<int>*> tmp_vect_pt;
     // Loop over elements
     //-------------------
     unsigned nel = nelement();
     for (unsigned e = 0; e < nel; e++)
     {
       // Get pointer to element
       // and put it in local storage fe_pt.
       FiniteElement* fe_pt = finite_element_pt(e);
       // print out values of all elements to doc
       if (doc) outfile << "Element: " << e << " " << fe_pt << std::endl;
       // Loop over the element's nodes and find out which boundaries they're on
       // ----------------------------------------------------------------------
       // Return number of nodes along one edge of the current element defined by
       // fe_pt hence, loop over nodes of each element in 3D-dimension
       unsigned nnode_1d = fe_pt->nnode_1d();
       // Loop over nodes in order
       for (unsigned i0 = 0; i0 < nnode_1d; i0++)
       {
         for (unsigned i1 = 0; i1 < nnode_1d; i1++)
         {
           for (unsigned i2 = 0; i2 < nnode_1d; i2++)
           {
             // Local node number, which is an assumed ordering defined in our
             // underlying finite element scheme.
             unsigned j = i0 + i1 * nnode_1d + i2 * nnode_1d * nnode_1d;
             // Get pointer to the set of boundaries that this node lives on
             // for each node reset boundaries_pt to 0,
             // create pointer to each node in each element
             // and give boundaries_pt a value
             std::set<unsigned>* boundaries_pt = 0;
             fe_pt->node_pt(j)->get_boundaries_pt(boundaries_pt);
             // If the node lives on some boundaries....
             // If not equal to 0, node is on boundary
             // Loop through values of the current node stored in boundaries_pt
             if (boundaries_pt != 0)
             {
               // Loop over the entries in the set "it" (name we use to refer to
               // the iterator)
               for (std::set<unsigned>::iterator it = boundaries_pt->begin();
                    it != boundaries_pt->end();
                    ++it)
               {
                 // What's the boundary?
                 // Define boundary_id to have the value pointed to by
                 // boundaries_pt
                 unsigned boundary_id = *it;
                 // Add pointer to finite element to vector for the appropriate
                 // boundary
                 // Does the pointer already exist in the vector
                 Vector<FiniteElement*>::iterator b_el_it =
                   std::find(vector_of_boundary_element_pt[*it].begin(),
                             vector_of_boundary_element_pt[*it].end(),
                             fe_pt);
                 // Only insert if we have not found it (i.e. got to the end)
                 if (b_el_it == vector_of_boundary_element_pt[*it].end())
                 {
                   vector_of_boundary_element_pt[*it].push_back(fe_pt);
                 }
                 // For the current element/boundary combination, create
                 // a vector that stores an indicator which element boundaries
                 // the node is located (boundary_identifier=-/+1 for nodes
                 // on the left/right boundary; boundary_identifier=-/+2 for
                 // nodes on the lower/upper boundary. We determine these indices
                 // for all corner nodes of the element and add them to a vector
                 // to a vector. This allows us to decide which faces of the
                 // element coincide with the boundary since each face of the
                 // element must have all four corner nodes on the boundary.
                 if (boundary_identifier(boundary_id, fe_pt) == 0)
                 {
                   // Here we make our vector of integers and keep track of the
                   // pointer to it The vector stores information about local
                   // node position for each boundary element
                   Vector<int>* tmp_pt = new Vector<int>;
                   // Add to the local scheme that will allow us to delete it
                   // later at the very end of the function
                   tmp_vect_pt.push_back(tmp_pt);
                   // Add the pointer to the storage scheme defined by
                   // boundary_id and pointer to finite element
                   boundary_identifier(boundary_id, fe_pt) = tmp_pt;
                 }
                 // Are we at a corner node? (local for each boundary element)
                 // i0,i1,i2 represent the current 3D coordinates- which local
                 // corner node.
                 if (((i0 == 0) || (i0 == nnode_1d - 1)) &&
                     ((i1 == 0) || (i1 == nnode_1d - 1)) &&
                     ((i2 == 0) || (i2 == nnode_1d - 1)))
                 {
                   // Create index to represent position relative to s_0
                   // s_0,s_1,s_2 are local 3D directions
                   (*boundary_identifier(boundary_id, fe_pt))
                     .push_back(1 * (2 * i0 / (nnode_1d - 1) - 1));
                   // Create index to represent position relative to s_1
                   (*boundary_identifier(boundary_id, fe_pt))
                     .push_back(2 * (2 * i1 / (nnode_1d - 1) - 1));
                   // Create index to represent position relative to s_2
                   (*boundary_identifier(boundary_id, fe_pt))
                     .push_back(3 * (2 * i2 / (nnode_1d - 1) - 1));
                 }
               }
             }
           }
         }
       }
     }
     // Now copy everything across into permanent arrays
     //-------------------------------------------------
     // Loop over boundaries
     //---------------------
     for (unsigned i = 0; i < nbound; i++)
     {
       // Loop over elements on given boundary
       typedef Vector<FiniteElement*>::iterator IT;
       for (IT it = vector_of_boundary_element_pt[i].begin();
            it != vector_of_boundary_element_pt[i].end();
            it++)
       {
         // Recover pointer to element for each element
         FiniteElement* fe_pt = (*it);
         // Initialise count for boundary identities (-3,-2,-1,1,2,3)
         std::map<int, unsigned> count;
         // Loop over coordinates in 3D dimension
         for (int ii = 0; ii < 3; ii++)
         {
           // Loop over upper/lower end of coordinates
           // count -/+ for each direction separately
           for (int sign = -1; sign < 3; sign += 2)
           {
             count[(ii + 1) * sign] = 0;
             // Initialise map of counts to 0 before loop
             // count boundary indicator for each element
             // and its nodes
           }
         }
         // Loop over boundary indicators for this element/boundary
         // count nodes for any one fixed boundary determined by
         // boundary indicator
         unsigned n_indicators = (*boundary_identifier(i, fe_pt)).size();
         for (unsigned j = 0; j < n_indicators; j++)
         {
           count[(*boundary_identifier(i, fe_pt))[j]]++;
         }
         // Determine the correct boundary indicator by checking that it
         // occurs four times (since four corner nodes of the element's boundary
         // need to be located on the boundary domain)
         int indicator = -10;
         // Loop over coordinates
         for (int ii = 0; ii < 3; ii++)
         {
           // Loop over upper/lower end of coordinates
           for (int sign = -1; sign < 3; sign += 2)
           {
             // If an index occurs four times then a face is on the boundary
             // But we can have multiple faces on the same boundary, so add all
             // the ones that we find!
             if (count[(ii + 1) * sign] == 4)
             {
               indicator = (ii + 1) * sign;
               // Copy into the member data structures
               Boundary_element_pt[i].push_back(*it);
               Face_index_at_boundary[i].push_back(indicator);
             }
           }
         }
       }
     }
     // Doc?
     //-----
     if (doc)
     {
       // Loop over boundaries
       for (unsigned i = 0; i < nbound; i++)
       {
         unsigned nel = Boundary_element_pt[i].size();
         outfile << "Boundary: " << i << " is adjacent to " << nel << " elements"
                 << std::endl;
         // Loop over elements on given boundary
         for (unsigned e = 0; e < nel; e++)
         {
           FiniteElement* fe_pt = Boundary_element_pt[i][e];
           outfile << "Boundary element:" << fe_pt
                   << " Face index along boundary is "
                   << Face_index_at_boundary[i][e] << std::endl;
         }
       }
     }
     // Lookup scheme has now been setup yet
     Lookup_for_elements_next_boundary_is_setup = true;
     // Cleanup temporary vectors
     unsigned n = tmp_vect_pt.size();
     for (unsigned i = 0; i < n; i++)
     {
       delete tmp_vect_pt[i];
     }
     return;
     // Doc?
     /*bool doc=false;
     if (outfile) doc=true;
     // Number of boundaries
     unsigned nbound=nboundary();
     // Wipe/allocate storage for arrays
     Boundary_element_pt.clear();
     Face_index_at_boundary.clear();
     Boundary_element_pt.resize(nbound);
     Face_index_at_boundary.resize(nbound);
     // Temporary vector of vectors of pointers to elements on the boundaries:
     // vector_of_boundary_element_pt[i] is the vector of pointers to all
     // elements that have nodes on boundary i.
     // This is not a set to ensure UNIQUE ordering on every processor
     Vector<Vector<FiniteElement*> > vector_of_boundary_element_pt;
     vector_of_boundary_element_pt.resize(nbound);
     // Matrix map for working out the fixed local coord for elements on boundary
     MapMatrixMixed<unsigned,FiniteElement*,Vector<int>* >
      boundary_identifier;
     // Tmp container to store pointers to tmp vectors so they can be deleted
     Vector<Vector<int>*> tmp_vect_pt;
     // Loop over elements
     //-------------------
     unsigned nel=nelement();
     for (unsigned e=0;e<nel;e++)
      {
       // Get pointer to element
       FiniteElement* fe_pt=finite_element_pt(e);
       if (doc) outfile << "Element: " << e << " " << fe_pt << std::endl;
       // Loop over the element's nodes and find out which boundaries they're on
       // ----------------------------------------------------------------------
       unsigned nnode_1d=fe_pt->nnode_1d();
       // Loop over nodes in order
       for (unsigned i0=0;i0<nnode_1d;i0++)
        {
         for (unsigned i1=0;i1<nnode_1d;i1++)
          {
           for (unsigned i2=0;i2<nnode_1d;i2++)
            {
             // Local node number
             unsigned j=i0+i1*nnode_1d+i2*nnode_1d*nnode_1d;
             // Get pointer to set of boundaries that this
             // node lives on
             std::set<unsigned>* boundaries_pt=0;
             fe_pt->node_pt(j)->get_boundaries_pt(boundaries_pt);
             // If the node lives on some boundaries....
             if (boundaries_pt!=0)
              {
               for (std::set<unsigned>::iterator it=boundaries_pt->begin();
                    it!=boundaries_pt->end();++it)
                {
                 // What's the boundary?
                 unsigned boundary_id=*it;
                 // Add pointer to finite element to vector for the appropriate
                 // boundary
                 // Does the pointer already exits in the vector
                 Vector<FiniteElement*>::iterator b_el_it =
                  std::find(vector_of_boundary_element_pt[*it].begin(),
                            vector_of_boundary_element_pt[*it].end(),
                            fe_pt);
                 //Only insert if we have not found it (i.e. got to the end)
                 if(b_el_it == vector_of_boundary_element_pt[*it].end())
                  {
                   vector_of_boundary_element_pt[*it].push_back(fe_pt);
                  }
                 // For the current element/boundary combination, create
                 // a vector that stores an indicator which element boundaries
                 // the node is located (boundary_identifier=-/+1 for nodes
                 // on the left/right boundary; boundary_identifier=-/+2 for
     nodes
                 // on the lower/upper boundary. We determine these indices
                 // for all corner nodes of the element and add them to a vector
                 // to a vector. This allows us to decide which face of the
     element
                 // coincides with the boundary since the (brick!) element must
                 // have exactly four corner nodes on the boundary.
                 if (boundary_identifier(boundary_id,fe_pt)==0)
                  {
                   Vector<int>* tmp_pt=new Vector<int>;
                   tmp_vect_pt.push_back(tmp_pt);
                   boundary_identifier(boundary_id,fe_pt)=tmp_pt;
                  }
                 // Are we at a corner node?
                 if (((i0==0)||(i0==nnode_1d-1))&&((i1==0)||(i1==nnode_1d-1))
                     &&((i2==0)||(i2==nnode_1d-1)))
                  {
                   // Create index to represent position relative to s_0
                   (*boundary_identifier(boundary_id,fe_pt)).
                    push_back(1*(2*i0/(nnode_1d-1)-1));
                   // Create index to represent position relative to s_1
                   (*boundary_identifier(boundary_id,fe_pt)).
                    push_back(2*(2*i1/(nnode_1d-1)-1));
                   // Create index to represent position relative to s_2
                   (*boundary_identifier(boundary_id,fe_pt)).
                    push_back(3*(2*i2/(nnode_1d-1)-1));
                  }
                }
              }
            }
          }
        }
      }
     // Now copy everything across into permanent arrays
     //-------------------------------------------------
     // Loop over boundaries
     //---------------------
     for (unsigned i=0;i<nbound;i++)
      {
       // Loop over elements on given boundary
       typedef Vector<FiniteElement*>::iterator IT;
       for (IT it=vector_of_boundary_element_pt[i].begin();
            it!=vector_of_boundary_element_pt[i].end();
            it++)
        {
         // Recover pointer to element
         FiniteElement* fe_pt=(*it);
         // Initialise count for boundary identiers (-3,-2,-1,1,2,3)
         std::map<int,unsigned> count;
         // Loop over coordinates
         for (int ii=0;ii<3;ii++)
          {
           // Loop over upper/lower end of coordinates
           for (int sign=-1;sign<3;sign+=2)
            {
             count[(ii+1)*sign]=0;
            }
          }
         // Loop over boundary indicators for this element/boundary
         unsigned n_indicators=(*boundary_identifier(i,fe_pt)).size();
         for (unsigned j=0;j<n_indicators;j++)
          {
           count[(*boundary_identifier(i,fe_pt))[j] ]++;
          }
         // Determine the correct boundary indicator by checking that it
         // occurs four times (since four corner nodes of the element's boundary
         // need to be located on the domain boundary
         int indicator=-10;
         //Check that we're finding exactly one boundary indicator
         bool found=false;
         // Loop over coordinates
         for (int ii=0;ii<3;ii++)
          {
           // Loop over upper/lower end of coordinates
           for (int sign=-1;sign<3;sign+=2)
            {
             if (count[(ii+1)*sign]==4)
              {
               // Check that we haven't found multiple boundaries
               if (found)
                {
                 throw OomphLibError(
                  "Trouble: Multiple boundary identifiers!\n",
                  OOMPH_CURRENT_FUNCTION,
                  OOMPH_EXCEPTION_LOCATION);
                }
               found=true;
               indicator=(ii+1)*sign;
              }
            }
          }
         // Check if we've found one boundary
         if (found)
          {
           // Store element
           Boundary_element_pt[i].push_back(*it);
           // Now convert boundary indicator into information required
           // for FaceElements
           switch (indicator)
            {
            case -3:
             // s_2 is fixed at -1.0:
             Face_index_at_boundary[i].push_back(-3);
             break;
            case -2:
             // s_1 is fixed at -1.0:
             Face_index_at_boundary[i].push_back(-2);
             break;
            case -1:
             // s_0 is fixed at -1.0:
             Face_index_at_boundary[i].push_back(-1);
             break;
            case 1:
             // s_0 is fixed at 1.0:
             Face_index_at_boundary[i].push_back(1);
             break;
            case 2:
             // s_1 is fixed at 1.0:
             Face_index_at_boundary[i].push_back(2);
             break;
            case 3:
             // s_2 is fixed at 1.0:
             Face_index_at_boundary[i].push_back(3);
             break;
            default:
             throw OomphLibError("Never get here",
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
            }
          }
        }
      }
     // Doc?
     //-----
     if (doc)
      {
       // Loop over boundaries
       for (unsigned i=0;i<nbound;i++)
        {
         unsigned nel=Boundary_element_pt[i].size();
         outfile << "Boundary: " << i
                 << " is adjacent to " << nel
                 << " elements" << std::endl;
         // Loop over elements on given boundary
         for (unsigned e=0;e<nel;e++)
          {
           FiniteElement* fe_pt=Boundary_element_pt[i][e];
           outfile << "Boundary element:" <<  fe_pt
                   << " Face index along boundary is "
                   <<  Face_index_at_boundary[i][e] << std::endl;
          }
        }
      }
     // Lookup scheme has now been setup yet
     Lookup_for_elements_next_boundary_is_setup=true;
     // Cleanup temporary vectors
     unsigned n=tmp_vect_pt.size();
     for (unsigned i=0;i<n;i++)
      {
       delete tmp_vect_pt[i];
       }*/
   }
References oomph::Mesh::Boundary_element_pt, e(), Eigen::placeholders::end, oomph::Mesh::Face_index_at_boundary, oomph::Mesh::finite_element_pt(), oomph::Node::get_boundaries_pt(), i, j, oomph::Mesh::Lookup_for_elements_next_boundary_is_setup, n, oomph::Mesh::nboundary(), oomph::Mesh::nelement(), oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::node_pt(), SYCL::sign(), and size.
The documentation for this class was generated from the following files:
brick_mesh.h
brick_mesh.cc