MercuryDPM: Eigen::internal::scalar_boolean_xor_op< Scalar > Struct Template Reference
Eigen::internal::scalar_boolean_xor_op< Scalar > Struct Template Reference
Template functor to compute the xor of two scalars as if they were booleans.
#include <BinaryFunctors.h>
Public Types
using result_type = Scalar
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar operator() (const Scalar &a, const Scalar &b) const
template<typename Packet >
EIGEN_STRONG_INLINE Packet packetOp (const Packet &a, const Packet &b) const
Detailed Description
template<typename Scalar>
struct Eigen::internal::scalar_boolean_xor_op< Scalar >
Template functor to compute the xor of two scalars as if they were booleans.
See also
class CwiseBinaryOp, ArrayBase::operator^
Member Typedef Documentation
result_type
template<typename Scalar > using Eigen::internal::scalar_boolean_xor_op< Scalar >::result_type = Scalar
Member Function Documentation
operator()()
template<typename Scalar > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar Eigen::internal::scalar_boolean_xor_op< Scalar >::operator() (const Scalar & a, const Scalar & b) const inline
{
     return (a != Scalar(0)) != (b != Scalar(0)) ? Scalar(1) : Scalar(0);
   }
References a, and b.
packetOp()
template<typename Scalar > template<typename Packet > EIGEN_STRONG_INLINE Packet Eigen::internal::scalar_boolean_xor_op< Scalar >::packetOp (const Packet & a, const Packet & b) const inline
{
     const Packet cst_one = pset1<Packet>(Scalar(1));
     // xor(a,b) == xor(!a,!b)
     Packet not_a = pcmp_eq(a, pzero(a));
     Packet not_b = pcmp_eq(b, pzero(b));
     Packet a_xor_b = pxor(not_a, not_b);
     return pand(cst_one, a_xor_b);
   }
References a, b, Eigen::internal::pand(), Eigen::internal::pcmp_eq(), Eigen::internal::pxor(), and Eigen::internal::pzero().
The documentation for this struct was generated from the following file:
BinaryFunctors.h