MercuryDPM: Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 1 > Struct Template Reference
Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 1 > Struct Template Reference
#include <InverseImpl.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC void run (const MatrixType &matrix, const typename MatrixType::RealScalar &absDeterminantThreshold, ResultType &result, typename ResultType::Scalar &determinant, bool &invertible)
Member Function Documentation
run()
template<typename MatrixType , typename ResultType > static EIGEN_DEVICE_FUNC void Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 1 >::run (const MatrixType & matrix, const typename MatrixType::RealScalar & absDeterminantThreshold, ResultType & result, typename ResultType::Scalar & determinant, bool & invertible) inline static
{
     using std::abs;
     determinant = matrix.coeff(0, 0);
     invertible = abs(determinant) > absDeterminantThreshold;
     if (invertible) result.coeffRef(0, 0) = typename ResultType::Scalar(1) / determinant;
   }
References abs(), determinant(), and matrix().
The documentation for this struct was generated from the following file:
InverseImpl.h