MercuryDPM: Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device > Struct Template Reference
#include <TensorReverse.h>
Classes
struct BlockIteratorState
Public Types
enum { IsAligned = false , PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess }
typedef TensorReverseOp< ReverseDimensions, ArgType > XprType
typedef XprType::Index Index
typedef DSizes< Index, NumDims > Dimensions
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorIntDivisor< Index > IndexDivisor
typedef internal::TensorBlockDescriptor< NumDims, Index > TensorBlockDesc
typedef internal::TensorBlockScratchAllocator< Device > TensorBlockScratch
typedef TensorEvaluator< const ArgType, Device >::TensorBlock ArgTensorBlock
typedef internal::TensorMaterializedBlock< CoeffReturnType, NumDims, Layout, Index > TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index reverseIndex (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements getResourceRequirements () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock block (TensorBlockDesc &desc, TensorBlockScratch &scratch, bool=false) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC Storage::Type data () const
Static Public Attributes
static constexpr int NumDims = internal::array_size<ReverseDimensions>::value
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Protected Attributes
Dimensions m_dimensions
array< Index, NumDims > m_strides
array< IndexDivisor, NumDims > m_fastStrides
TensorEvaluator< ArgType, Device > m_impl
ReverseDimensions m_reverse
const Device EIGEN_DEVICE_REF m_device
Member Typedef Documentation
ArgTensorBlock
template<typename ReverseDimensions , typename ArgType , typename Device > typedef TensorEvaluator<const ArgType, Device>::TensorBlock Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::ArgTensorBlock
CoeffReturnType
template<typename ReverseDimensions , typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::CoeffReturnType
Dimensions
template<typename ReverseDimensions , typename ArgType , typename Device > typedef DSizes<Index, NumDims> Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::Dimensions
EvaluatorPointerType
template<typename ReverseDimensions , typename ArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::EvaluatorPointerType
Index
template<typename ReverseDimensions , typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::Index
IndexDivisor
template<typename ReverseDimensions , typename ArgType , typename Device > typedef internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::IndexDivisor
PacketReturnType
template<typename ReverseDimensions , typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::PacketReturnType
Scalar
template<typename ReverseDimensions , typename ArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::Scalar
Storage
template<typename ReverseDimensions , typename ArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::Storage
TensorBlock
template<typename ReverseDimensions , typename ArgType , typename Device > typedef internal::TensorMaterializedBlock<CoeffReturnType, NumDims, Layout, Index> Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::TensorBlock
TensorBlockDesc
template<typename ReverseDimensions , typename ArgType , typename Device > typedef internal::TensorBlockDescriptor<NumDims, Index> Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::TensorBlockDesc
TensorBlockScratch
template<typename ReverseDimensions , typename ArgType , typename Device > typedef internal::TensorBlockScratchAllocator<Device> Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::TensorBlockScratch
XprType
template<typename ReverseDimensions , typename ArgType , typename Device > typedef TensorReverseOp<ReverseDimensions, ArgType> Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename ReverseDimensions , typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
        {
     IsAligned = false,
     PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess,
     BlockAccess = NumDims > 0,
     PreferBlockAccess = true,
     CoordAccess = false,  // to be implemented
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename ReverseDimensions , typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_impl(op.expression(), device), m_reverse(op.reverse()), m_device(device) {
     // Reversing a scalar isn't supported yet. It would be a no-op anyway.
     EIGEN_STATIC_ASSERT((NumDims > 0), YOU_MADE_A_PROGRAMMING_MISTAKE);
     // Compute strides
     m_dimensions = m_impl.dimensions();
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       m_strides[0] = 1;
       for (int i = 1; i < NumDims; ++i) {
         m_strides[i] = m_strides[i - 1] * m_dimensions[i - 1];
         if (m_strides[i] > 0) m_fastStrides[i] = IndexDivisor(m_strides[i]);
       }
     } else {
       m_strides[NumDims - 1] = 1;
       for (int i = NumDims - 2; i >= 0; --i) {
         m_strides[i] = m_strides[i + 1] * m_dimensions[i + 1];
         if (m_strides[i] > 0) m_fastStrides[i] = IndexDivisor(m_strides[i]);
       }
     }
   }
References Eigen::ColMajor, EIGEN_STATIC_ASSERT, i, and Eigen::TensorEvaluator< Derived, Device >::Layout.
Member Function Documentation
block()
template<typename ReverseDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::block (TensorBlockDesc & desc, TensorBlockScratch & scratch, bool = false) const inline
{
     // TODO(ezhulenev): If underlying tensor expression supports and prefers
     // block evaluation we must use it. Currently we use coeff and packet
     // access into the underlying tensor expression.
     // static const bool useBlockAccessForArgType =
     //     TensorEvaluator<ArgType, Device>::BlockAccess &&
     //     TensorEvaluator<ArgType, Device>::PreferBlockAccess;
     static const bool isColMajor = static_cast<int>(Layout) == static_cast<int>(ColMajor);
     static const Index inner_dim_idx = isColMajor ? 0 : NumDims - 1;
     const bool inner_dim_reversed = m_reverse[inner_dim_idx];
     // Offset in the output block.
     Index block_offset = 0;
     // Offset in the input Tensor.
     Index input_offset = reverseIndex(desc.offset());
     // Initialize output block iterator state. Dimension in this array are
     // always in inner_most -> outer_most order (col major layout).
     array<BlockIteratorState, NumDims> it;
     for (int i = 0; i < NumDims; ++i) {
       const int dim = isColMajor ? i : NumDims - 1 - i;
       it[i].size = desc.dimension(dim);
       it[i].count = 0;
       it[i].reverse = m_reverse[dim];
       it[i].block_stride = i == 0 ? 1 : (it[i - 1].size * it[i - 1].block_stride);
       it[i].block_span = it[i].block_stride * (it[i].size - 1);
       it[i].input_stride = m_strides[dim];
       it[i].input_span = it[i].input_stride * (it[i].size - 1);
       if (it[i].reverse) {
         it[i].input_stride = -1 * it[i].input_stride;
         it[i].input_span = -1 * it[i].input_span;
       }
     }
     // If multiple inner dimensions have the same reverse flag, check if we can
     // merge them into a single virtual inner dimension.
     int effective_inner_dim = 0;
     for (int i = 1; i < NumDims; ++i) {
       if (it[i].reverse != it[effective_inner_dim].reverse) break;
       if (it[i].block_stride != it[effective_inner_dim].size) break;
       if (it[i].block_stride != numext::abs(it[i].input_stride)) break;
       it[i].size = it[effective_inner_dim].size * it[i].size;
       it[i].block_stride = 1;
       it[i].input_stride = (inner_dim_reversed ? -1 : 1);
       it[i].block_span = it[i].block_stride * (it[i].size - 1);
       it[i].input_span = it[i].input_stride * (it[i].size - 1);
       effective_inner_dim = i;
     }
     eigen_assert(it[effective_inner_dim].block_stride == 1);
     eigen_assert(it[effective_inner_dim].input_stride == (inner_dim_reversed ? -1 : 1));
     const Index inner_dim_size = it[effective_inner_dim].size;
     // Prepare storage for the materialized reverse result.
     const typename TensorBlock::Storage block_storage = TensorBlock::prepareStorage(desc, scratch);
     CoeffReturnType* block_buffer = block_storage.data();
     while (it[NumDims - 1].count < it[NumDims - 1].size) {
       // Copy inner-most dimension data from reversed location in input.
       Index dst = block_offset;
       Index src = input_offset;
       // NOTE(ezhulenev): Adding vectorized path with internal::preverse showed
       // worse results in benchmarks than a simple coefficient loop.
       if (inner_dim_reversed) {
         for (Index i = 0; i < inner_dim_size; ++i) {
           block_buffer[dst] = m_impl.coeff(src);
           ++dst;
           --src;
         }
       } else {
         for (Index i = 0; i < inner_dim_size; ++i) {
           block_buffer[dst] = m_impl.coeff(src);
           ++dst;
           ++src;
         }
       }
       // For the 1d tensor we need to generate only one inner-most dimension.
       if ((NumDims - effective_inner_dim) == 1) break;
       // Update offset.
       for (Index i = effective_inner_dim + 1; i < NumDims; ++i) {
         if (++it[i].count < it[i].size) {
           block_offset += it[i].block_stride;
           input_offset += it[i].input_stride;
           break;
         }
         if (i != NumDims - 1) it[i].count = 0;
         block_offset -= it[i].block_span;
         input_offset -= it[i].input_span;
       }
     }
     return block_storage.AsTensorMaterializedBlock();
   }
References Eigen::numext::abs(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::AsTensorMaterializedBlock(), Eigen::ColMajor, Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::data(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::dimension(), eigen_assert, i, Eigen::TensorEvaluator< Derived, Device >::Layout, Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::offset(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::prepareStorage(), reverse(), and size.
cleanup()
template<typename ReverseDimensions , typename ArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::cleanup () inline
 { m_impl.cleanup(); }
Referenced by framework.Frame::__init__().
coeff()
template<typename ReverseDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::coeff (Index index) const inline
{
     return m_impl.coeff(reverseIndex(index));
   }
costPerCoeff()
template<typename ReverseDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     double compute_cost = NumDims * (2 * TensorOpCost::AddCost<Index>() + 2 * TensorOpCost::MulCost<Index>() +
                                      TensorOpCost::DivCost<Index>());
     for (int i = 0; i < NumDims; ++i) {
       if (m_reverse[i]) {
         compute_cost += 2 * TensorOpCost::AddCost<Index>();
       }
     }
     return m_impl.costPerCoeff(vectorized) + TensorOpCost(0, 0, compute_cost, false /* vectorized */, PacketSize);
   }
References i, and Eigen::TensorEvaluator< Derived, Device >::PacketSize.
data()
template<typename ReverseDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC Storage::Type Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename ReverseDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::dimensions () const inline
 { return m_dimensions; }
evalSubExprsIfNeeded()
template<typename ReverseDimensions , typename ArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
{
     m_impl.evalSubExprsIfNeeded(NULL);
     return true;
   }
getResourceRequirements()
template<typename ReverseDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::getResourceRequirements () const inline
{
     const size_t target_size = m_device.lastLevelCacheSize();
     // Block evaluation reads underlying memory in reverse order, and default
     // cost model does not properly catch this in bytes stored/loaded.
     return internal::TensorBlockResourceRequirements::skewed<Scalar>(target_size).addCostPerCoeff({0, 0, 24});
   }
References Eigen::TensorEvaluator< Derived, Device >::m_device.
packet()
template<typename ReverseDimensions , typename ArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::packet (Index index) const inline
{
     eigen_assert(index + PacketSize - 1 < dimensions().TotalSize());
     // TODO(ndjaitly): write a better packing routine that uses
     // local structure.
     EIGEN_ALIGN_MAX std::remove_const_t<CoeffReturnType> values[PacketSize];
     EIGEN_UNROLL_LOOP
     for (int i = 0; i < PacketSize; ++i) {
       values[i] = coeff(index + i);
     }
     PacketReturnType rslt = internal::pload<PacketReturnType>(values);
     return rslt;
   }
References Eigen::TensorEvaluator< Derived, Device >::coeff(), Eigen::TensorEvaluator< Derived, Device >::dimensions(), EIGEN_ALIGN_MAX, eigen_assert, EIGEN_UNROLL_LOOP, i, and Eigen::TensorEvaluator< Derived, Device >::PacketSize.
reverseIndex()
template<typename ReverseDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::reverseIndex (Index index) const inline
{
     eigen_assert(index < dimensions().TotalSize());
     Index inputIndex = 0;
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       EIGEN_UNROLL_LOOP
       for (int i = NumDims - 1; i > 0; --i) {
         Index idx = index / m_fastStrides[i];
         index -= idx * m_strides[i];
         if (m_reverse[i]) {
           idx = m_dimensions[i] - idx - 1;
         }
         inputIndex += idx * m_strides[i];
       }
       if (m_reverse[0]) {
         inputIndex += (m_dimensions[0] - index - 1);
       } else {
         inputIndex += index;
       }
     } else {
       EIGEN_UNROLL_LOOP
       for (int i = 0; i < NumDims - 1; ++i) {
         Index idx = index / m_fastStrides[i];
         index -= idx * m_strides[i];
         if (m_reverse[i]) {
           idx = m_dimensions[i] - idx - 1;
         }
         inputIndex += idx * m_strides[i];
       }
       if (m_reverse[NumDims - 1]) {
         inputIndex += (m_dimensions[NumDims - 1] - index - 1);
       } else {
         inputIndex += index;
       }
     }
     return inputIndex;
   }
References Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), eigen_assert, EIGEN_UNROLL_LOOP, i, and Eigen::TensorEvaluator< Derived, Device >::Layout.
Member Data Documentation
Layout
template<typename ReverseDimensions , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_device
template<typename ReverseDimensions , typename ArgType , typename Device > const Device EIGEN_DEVICE_REF Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::m_device protected
m_dimensions
template<typename ReverseDimensions , typename ArgType , typename Device > Dimensions Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::m_dimensions protected
m_fastStrides
template<typename ReverseDimensions , typename ArgType , typename Device > array<IndexDivisor, NumDims> Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::m_fastStrides protected
m_impl
template<typename ReverseDimensions , typename ArgType , typename Device > TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::m_impl protected
m_reverse
template<typename ReverseDimensions , typename ArgType , typename Device > ReverseDimensions Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::m_reverse protected
m_strides
template<typename ReverseDimensions , typename ArgType , typename Device > array<Index, NumDims> Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::m_strides protected
NumDims
template<typename ReverseDimensions , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::NumDims = internal::array_size<ReverseDimensions>::value static constexpr
PacketSize
template<typename ReverseDimensions , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorReverse.h