MercuryDPM: SphericalParticleVtkWriter Class Reference
SphericalParticleVtkWriter Class Reference final
#include <SphericalParticleVtkWriter.h>
Public Member Functions
SphericalParticleVtkWriter (ParticleHandler &particleHandler)
~SphericalParticleVtkWriter () override=default
void writeVTK () const override
Writes all particles into a vtk file format (unstructured grid), consisting of particle positions, velocities, radii and type of species (IndSpecies)
std::string getName () const override
Public Member Functions inherited from ParticleVtkWriter
ParticleVtkWriter (ParticleHandler &particleHandler)
virtual ~ParticleVtkWriter ()=default
Public Member Functions inherited from BaseVTKWriter< ParticleHandler >
BaseVTKWriter (ParticleHandler &handler)
BaseVTKWriter (const BaseVTKWriter &other)
unsigned getFileCounter () const
void setFileCounter (unsigned fileCounter)
void setOutputDirectory (const std::string &dir)
const std::string & getOutputDirectory () const
std::string getFileName () const
Private Member Functions
void writeVTKVelocity (std::fstream &file) const
void writeVTKAngularVelocity (std::fstream &file) const
void writeVTKRadius (std::fstream &file) const
void writeVTKId (std::fstream &file) const
Writes the id (unique integer) of the particles to the vtu file.
Additional Inherited Members
Protected Member Functions inherited from ParticleVtkWriter
void writeExtraFields (std::fstream &file) const
void writeVTKIndSpecies (std::fstream &file) const
void writeVTKPositions (std::fstream &file) const
bool particleMustBeWritten (BaseParticle *particle) const
Protected Member Functions inherited from BaseVTKWriter< ParticleHandler >
std::fstream makeVTKFileWithHeader () const
void writeVTKFooterAndClose (std::fstream &file) const
Protected Attributes inherited from BaseVTKWriter< ParticleHandler >
ParticleHandler & handler_
particle handler from which the particles should be written
unsigned int fileCounter
std::string outputDirectory_
Constructor & Destructor Documentation
SphericalParticleVtkWriter()
SphericalParticleVtkWriter::SphericalParticleVtkWriter (ParticleHandler & particleHandler) inline explicit
                                                                           : ParticleVtkWriter(particleHandler)
     {}
~SphericalParticleVtkWriter()
SphericalParticleVtkWriter::~SphericalParticleVtkWriter () override default
Member Function Documentation
getName()
std::string SphericalParticleVtkWriter::getName () const inline override virtual
Implements ParticleVtkWriter.
     {
         return "SphericalParticleVtkWriter";
     }
writeVTK()
void SphericalParticleVtkWriter::writeVTK () const override virtual
Writes all particles into a vtk file format (unstructured grid), consisting of particle positions, velocities, radii and type of species (IndSpecies)
Writes all points ans cells to a file in the VTK format. The filename is hard-coded in this method, and is based on the name of the DPMBase and has a unique counter in it to ensure there are no two files with the same name.
Implements BaseVTKWriter< ParticleHandler >.
 {
     std::fstream file = makeVTKFileWithHeader();
     long numberOfParticlesToWrite = std::count_if(handler_.begin(), handler_.end(),
                                                   [this](BaseParticle* p){return particleMustBeWritten(p);});
     file << "<Piece NumberOfPoints=\"" << numberOfParticlesToWrite
          << "\" NumberOfCells=\"" << 0 << "\">\n";
     writeVTKPositions(file);
     file << "<PointData  Vectors=\"vector\">\n";
     writeVTKVelocity(file);
     writeVTKAngularVelocity(file);
     writeVTKRadius(file);
     writeVTKIndSpecies(file);
     writeExtraFields(file);
     writeVTKId(file);
     file << "</PointData>\n";
     writeVTKFooterAndClose(file);
 }
References BaseHandler< T >::begin(), BaseHandler< T >::end(), BaseVTKWriter< ParticleHandler >::handler_, BaseVTKWriter< ParticleHandler >::makeVTKFileWithHeader(), p, ParticleVtkWriter::writeExtraFields(), writeVTKAngularVelocity(), BaseVTKWriter< ParticleHandler >::writeVTKFooterAndClose(), writeVTKId(), ParticleVtkWriter::writeVTKIndSpecies(), ParticleVtkWriter::writeVTKPositions(), writeVTKRadius(), and writeVTKVelocity().
writeVTKAngularVelocity()
void SphericalParticleVtkWriter::writeVTKAngularVelocity (std::fstream & file) const private
 {
     if (handler_.getDPMBase()->getRotation())
     {
         file << "  <DataArray type=\"Float32\" Name=\"AngularVelocity\" NumberOfComponents=\"3\" format=\"ascii\">\n";
         // Add velocity
         for (const auto& p: handler_) {
 #ifdef MERCURYDPM_USE_MPI
             if (particleMustBeWritten(p))
 #endif
             {
                 file << '\t' << (float)p->getAngularVelocity().X << ' ' << (float)p->getAngularVelocity().Y << ' ' << (float)p->getAngularVelocity().Z << '\n';
             }
         }
         file << "  </DataArray>\n";
     }
 }
References BaseHandler< T >::getDPMBase(), DPMBase::getRotation(), BaseVTKWriter< ParticleHandler >::handler_, p, and ParticleVtkWriter::particleMustBeWritten().
Referenced by writeVTK().
writeVTKId()
void SphericalParticleVtkWriter::writeVTKId (std::fstream & file) const private
Writes the id (unique integer) of the particles to the vtu file.
This enables the tracing of particles through multiple files.
Parameters
[in] file Output filestream.
Note
gmb Maybe Int64 is needed.
 {
     file << "  <DataArray type=\"Int32\" Name=\"Id\" format=\"ascii\">\n";
     // Add id
     for (const auto& p: handler_) {
 #ifdef MERCURYDPM_USE_MPI
         if (particleMustBeWritten(p))
 #endif
         {
             file << '\t' << p->getId() << '\n';
         }
     }
     file << "  </DataArray>\n";
 }
References BaseVTKWriter< ParticleHandler >::handler_, p, and ParticleVtkWriter::particleMustBeWritten().
Referenced by writeVTK().
writeVTKRadius()
void SphericalParticleVtkWriter::writeVTKRadius (std::fstream & file) const private
Notice that we write GrainRadius in the file, since there is a bug in Paraview that defaults to the first scalar-value in lexicographic order. We therefore need a description for the radius which starts with a letter before N.
Parameters
file The filestream to which the radius must be written.
 {
     file << "  <DataArray type=\"Float32\" Name=\"Radius\" format=\"ascii\">\n";
     // Add radius
     for (const auto& p: handler_)
     {
 #ifdef MERCURYDPM_USE_MPI
         if (particleMustBeWritten(p))
 #endif
         {
             file << '\t' << p->getRadius() << '\n';
         }
     }
     file << "  </DataArray>\n";
 }
References BaseVTKWriter< ParticleHandler >::handler_, p, and ParticleVtkWriter::particleMustBeWritten().
Referenced by writeVTK().
writeVTKVelocity()
void SphericalParticleVtkWriter::writeVTKVelocity (std::fstream & file) const private
 {
     file << "  <DataArray type=\"Float32\" Name=\"Velocity\" NumberOfComponents=\"3\" format=\"ascii\">\n";
     // Add velocity
     for (const auto& p: handler_) {
 #ifdef MERCURYDPM_USE_MPI
         if (particleMustBeWritten(p))
 #endif
         {
             file << ' ' << (float) p->getVelocity().X
                  << ' ' << (float) p->getVelocity().Y
                  << ' ' << (float) p->getVelocity().Z << '\n';
         }
     }
     file << "  </DataArray>\n";
 }
References BaseVTKWriter< ParticleHandler >::handler_, p, and ParticleVtkWriter::particleMustBeWritten().
Referenced by writeVTK().
The documentation for this class was generated from the following files:
SphericalParticleVtkWriter.h
SphericalParticleVtkWriter.cc