MercuryDPM: oomph::QuarterCircleSectorMesh< ELEMENT > Class Template Reference
oomph::QuarterCircleSectorMesh< ELEMENT > Class Template Reference
#include <quarter_circle_sector_mesh.template.h>
Public Member Functions
QuarterCircleSectorMesh (GeomObject *wall_pt, const double &xi_lo, const double &fract_mid, const double &xi_hi, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual ~QuarterCircleSectorMesh ()
Destructor:
GeomObject *& wall_pt ()
Access function to GeomObject representing wall.
QuarterCircleSectorDomain * domain_pt ()
Access function to domain.
QuarterCircleSectorDomain::BLSquashFctPt & bl_squash_fct_pt ()
Public Member Functions inherited from oomph::QuadMeshBase
QuadMeshBase ()
Constructor (empty)
QuadMeshBase (const QuadMeshBase &node)=delete
Broken copy constructor.
void operator= (const QuadMeshBase &)=delete
Broken assignment operator.
virtual ~QuadMeshBase ()
Destructor (empty)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Protected Attributes
QuarterCircleSectorDomain * Domain_pt
Pointer to Domain.
GeomObject * Wall_pt
double Xi_lo
Lower limit for the (1D) coordinates along the wall.
double Fract_mid
Fraction along wall where outer ring is to be divided.
double Xi_hi
Upper limit for the (1D) coordinates along the wall.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Detailed Description
template<class ELEMENT>
class oomph::QuarterCircleSectorMesh< ELEMENT >
2D quarter ring mesh class. The domain is specified by the GeomObject that identifies boundary 1.
                     ---___
                    |      ---____
                    |              -   BOUNDARY 1
                    |               /
                    |     [2]      /  |
                    |             /     |
                    | N          /        |
                    | |_ E      /          |
     BOUNDARY 2     |-----------           |
                    |          |    [1]    |
                    |   [0]    |           |  ^
                    |          |           | / \  direction of
                    | N        |    N      |  |   Lagrangian
                    | |_ E     |    |_ E   |  |   coordinate
                    |__________|___________|  |   along wall GeomObject
                         BOUNDARY 0
Within the elements (MacroElements), the local coordinates
are such that the (E)astern direction coincides with the positive
s_0 direction,  while the (N)orther direction coincides with the positive
s_1 direction.
Domain is parametrised by three macro elements as sketched. Nodal positions are determined via macro-element-based representation of the Domain (as a QuarterCircleSectorDomain).
Constructor & Destructor Documentation
QuarterCircleSectorMesh()
template<class ELEMENT > oomph::QuarterCircleSectorMesh< ELEMENT >::QuarterCircleSectorMesh (GeomObject * wall_pt, const double & xi_lo, const double & fract_mid, const double & xi_hi, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass pointer to geometric object that specifies the wall, start and end coordinates on the geometric object, and the fraction along which the dividing line is to be placed, and the timestepper (defaults to (Steady) default timestepper defined in Mesh)
Constructor for deformable 2D Ring mesh class. Pass pointer to geometric object that specifies the wall, start and end coordinates on the geometric object, and the fraction along which the dividing line is to be placed, and the timestepper (defaults to (Steady) default timestepper defined in Mesh). Nodal positions are determined via macro-element-based representation of the Domain (as a QuarterCircleSectorDomain).
     : Wall_pt(wall_pt), Xi_lo(xi_lo), Fract_mid(fract_mid), Xi_hi(xi_hi)
   {
     // Mesh can only be built with 2D Qelements.
     MeshChecker::assert_geometric_element<QElementGeometricBase, ELEMENT>(2);
     // Build macro element-based domain
     Domain_pt = new QuarterCircleSectorDomain(wall_pt, xi_lo, fract_mid, xi_hi);
     // Set the number of boundaries
     set_nboundary(3);
     // We have only bothered to parametrise boundary 1
     Boundary_coordinate_exists[1] = true;
     // Allocate the store for the elements
     Element_pt.resize(3);
     // Create first element
     Element_pt[0] = new ELEMENT;
     // Read out the number of linear points in the element
     unsigned n_p = dynamic_cast<ELEMENT*>(finite_element_pt(0))->nnode_1d();
     // Can now allocate the store for the nodes
     Node_pt.resize(n_p * n_p + (n_p - 1) * n_p + (n_p - 1) * (n_p - 1));
     Vector<double> s(2);
     Vector<double> r(2);
     // Storage for the intrinsic boundary coordinate
     Vector<double> zeta(1);
     // Set up geometrical data
     //------------------------
     // Initialise node counter
     unsigned long node_count = 0;
     // Now assign the topology
     // Boundaries are numbered 0 1 2 from the bottom proceeding anticlockwise
     // FIRST ELEMENT (lower left corner)
     //
     // Set the corner node (on boundaries 0 and 2)
     //-------------------------------------------
     // Create the ll node
     Node_pt[node_count] =
       finite_element_pt(0)->construct_boundary_node(0, time_stepper_pt);
     // Set the pointer from the element to the node
     finite_element_pt(0)->node_pt(0) = Node_pt[node_count];
     // Set the position of the ll node
     s[0] = -1.0;
     s[1] = -1.0;
     Domain_pt->macro_element_pt(0)->macro_map(s, r);
     Node_pt[node_count]->x(0) = r[0];
     Node_pt[node_count]->x(1) = r[1];
     // Add the node to the boundaries
     add_boundary_node(0, Node_pt[node_count]);
     add_boundary_node(2, Node_pt[node_count]);
     // Increment the node number
     node_count++;
     // First row is on boundary 0:
     //---------------------------
     for (unsigned l1 = 1; l1 < n_p; l1++)
     {
       // Local node number
       unsigned jnod_local = l1;
       // Create the node
       Node_pt[node_count] = finite_element_pt(0)->construct_boundary_node(
         jnod_local, time_stepper_pt);
       // Set the pointer from the element to the node
       finite_element_pt(0)->node_pt(jnod_local) = Node_pt[node_count];
       // Set the position of the node
       s[0] = -1.0 + 2.0 * double(l1) / double(n_p - 1);
       s[1] = -1.0;
       Domain_pt->macro_element_pt(0)->macro_map(s, r);
       Node_pt[node_count]->x(0) = r[0];
       Node_pt[node_count]->x(1) = r[1];
       // Add the node to the boundary
       add_boundary_node(0, Node_pt[node_count]);
       // Increment the node number
       node_count++;
     }
     // Loop over the other rows of nodes
     //------------------------------------
     for (unsigned l2 = 1; l2 < n_p; l2++)
     {
       // First node in this row is on boundary 2:
       //-----------------------------------------
       // Local node number
       unsigned jnod_local = n_p * l2;
       // Create the node
       Node_pt[node_count] = finite_element_pt(0)->construct_boundary_node(
         jnod_local, time_stepper_pt);
       // Set the pointer from the element to the node
       finite_element_pt(0)->node_pt(jnod_local) = Node_pt[node_count];
       // Set the position of the node
       s[0] = -1.0;
       s[1] = -1.0 + 2.0 * double(l2) / double(n_p - 1);
       ;
       Domain_pt->macro_element_pt(0)->macro_map(s, r);
       Node_pt[node_count]->x(0) = r[0];
       Node_pt[node_count]->x(1) = r[1];
       // Add the node to the boundary
       add_boundary_node(2, Node_pt[node_count]);
       // Increment the node number
       node_count++;
       // The other nodes are in the interior
       //------------------------------------
       // Loop over the other node columns
       for (unsigned l1 = 1; l1 < n_p; l1++)
       {
         // Local node number
         unsigned jnod_local = l1 + n_p * l2;
         // Create the node
         Node_pt[node_count] =
           finite_element_pt(0)->construct_node(jnod_local, time_stepper_pt);
         // Set the pointer from the element to the node
         finite_element_pt(0)->node_pt(jnod_local) = Node_pt[node_count];
         // Set the position of the node
         s[0] = -1.0 + 2.0 * double(l1) / double(n_p - 1);
         s[1] = -1.0 + 2.0 * double(l2) / double(n_p - 1);
         Domain_pt->macro_element_pt(0)->macro_map(s, r);
         Node_pt[node_count]->x(0) = r[0];
         Node_pt[node_count]->x(1) = r[1];
         // Increment the node number
         node_count++;
       }
     }
     // SECOND ELEMENT (lower right corner)
     //
     // Create element
     Element_pt[1] = new ELEMENT;
     // Loop over the first column (already exists!)
     //---------------------------------------------
     for (unsigned l2 = 0; l2 < n_p; l2++)
     {
       // Node number in existing element
       unsigned jnod_local_old = (n_p - 1) + l2 * n_p;
       // Set the pointer from the element to the node
       finite_element_pt(1)->node_pt(l2 * n_p) =
         finite_element_pt(0)->node_pt(jnod_local_old);
     }
     // Loop over the other node columns (apart from last one)
     //------------------------------------------------------
     for (unsigned l1 = 1; l1 < n_p - 1; l1++)
     {
       // First node is at the bottom (on boundary 0)
       //--------------------------------------------
       // Local node number
       unsigned jnod_local = l1;
       // Create the node
       Node_pt[node_count] = finite_element_pt(1)->construct_boundary_node(
         jnod_local, time_stepper_pt);
       // Set the pointer from the element to the node
       finite_element_pt(1)->node_pt(jnod_local) = Node_pt[node_count];
       // Set the position of the node
       s[0] = -1.0 + 2.0 * double(l1) / double(n_p - 1);
       s[1] = -1.0;
       Domain_pt->macro_element_pt(1)->macro_map(s, r);
       Node_pt[node_count]->x(0) = r[0];
       Node_pt[node_count]->x(1) = r[1];
       // Add the node to the boundary
       add_boundary_node(0, Node_pt[node_count]);
       // Increment the node number
       node_count++;
       // Now loop over the interior nodes in this column
       //-------------------------------------------------
       for (unsigned l2 = 1; l2 < n_p; l2++)
       {
         // Local node number
         unsigned jnod_local = l1 + l2 * n_p;
         // Create the node
         Node_pt[node_count] =
           finite_element_pt(1)->construct_node(jnod_local, time_stepper_pt);
         // Set the pointer from the element to the node
         finite_element_pt(1)->node_pt(jnod_local) = Node_pt[node_count];
         // Set the position of the node
         s[0] = -1.0 + 2.0 * double(l1) / double(n_p - 1);
         s[1] = -1.0 + 2.0 * double(l2) / double(n_p - 1);
         Domain_pt->macro_element_pt(1)->macro_map(s, r);
         Node_pt[node_count]->x(0) = r[0];
         Node_pt[node_count]->x(1) = r[1];
         // Increment the node number
         node_count++;
       }
     }
     // Last column (on boundary 1)
     //----------------------------
     // First node is at the bottom (and hence also on boundary 0)
     //-----------------------------------------------------------
     // Local node number
     unsigned jnod_local = n_p - 1;
     // Create the node
     Node_pt[node_count] = finite_element_pt(1)->construct_boundary_node(
       jnod_local, time_stepper_pt);
     // Set the pointer from the element to the node
     finite_element_pt(1)->node_pt(jnod_local) = Node_pt[node_count];
     // Set the position of the node
     s[0] = 1.0;
     s[1] = -1.0;
     Domain_pt->macro_element_pt(1)->macro_map(s, r);
     Node_pt[node_count]->x(0) = r[0];
     Node_pt[node_count]->x(1) = r[1];
     // Add the node to the boundaries
     add_boundary_node(0, Node_pt[node_count]);
     add_boundary_node(1, Node_pt[node_count]);
     // Set the intrinsic coordinate on the boundary 1
     zeta[0] = Xi_lo + 0.5 * (1.0 + s[1]) * Fract_mid * (Xi_hi - Xi_lo);
     Node_pt[node_count]->set_coordinates_on_boundary(1, zeta);
     // Increment the node number
     node_count++;
     // Now do the remaining nodes in last column (only on boundary 1)
     //---------------------------------------------------------------
     for (unsigned l2 = 1; l2 < n_p; l2++)
     {
       // Local node number
       unsigned jnod_local = (n_p - 1) + l2 * n_p;
       // Create the node
       Node_pt[node_count] = finite_element_pt(1)->construct_boundary_node(
         jnod_local, time_stepper_pt);
       // Set the pointer from the element to the node
       finite_element_pt(1)->node_pt(jnod_local) = Node_pt[node_count];
       // Set the position of the node
       s[0] = 1.0;
       s[1] = -1.0 + 2.0 * double(l2) / double(n_p - 1);
       Domain_pt->macro_element_pt(1)->macro_map(s, r);
       Node_pt[node_count]->x(0) = r[0];
       Node_pt[node_count]->x(1) = r[1];
       // Add the node to the boundary
       add_boundary_node(1, Node_pt[node_count]);
       // Set the intrinsic coordinate on the boundary 1
       zeta[0] = Xi_lo + 0.5 * (1.0 + s[1]) * Fract_mid * (Xi_hi - Xi_lo);
       Node_pt[node_count]->set_coordinates_on_boundary(1, zeta);
       // Increment the node number
       node_count++;
     }
     // THIRD ELEMENT (upper left corner)
     //
     // Create element
     Element_pt[2] = new ELEMENT;
     // Loop over the first row (has already been created via element 0)
     //-----------------------------------------------------------------
     for (unsigned l1 = 0; l1 < n_p; l1++)
     {
       // Node number in existing element
       unsigned jnod_local_old = n_p * (n_p - 1) + l1;
       // Local node number here
       unsigned jnod_local = l1;
       // Set the pointer from the element to the node
       finite_element_pt(2)->node_pt(jnod_local) =
         finite_element_pt(0)->node_pt(jnod_local_old);
     }
     // Loop over the remaining nodes in the last column (has already
     //--------------------------------------------------------------
     // been created via element 1)
     //----------------------------
     for (unsigned l2 = 1; l2 < n_p; l2++)
     {
       // Node number in existing element
       unsigned jnod_local_old = n_p * (n_p - 1) + l2;
       // Local node number here
       unsigned jnod_local = (n_p - 1) + l2 * n_p;
       // Set the pointer from the element to the node
       finite_element_pt(2)->node_pt(jnod_local) =
         finite_element_pt(1)->node_pt(jnod_local_old);
     }
     // Loop over the nodes in rows (apart from last one which is on boundary 1)
     //-------------------------------------------------------------------------
     for (unsigned l2 = 1; l2 < n_p - 1; l2++)
     {
       // First node in this row is on boundary 2:
       //-----------------------------------------
       // Local node number
       unsigned jnod_local = n_p * l2;
       // Create the node
       Node_pt[node_count] = finite_element_pt(2)->construct_boundary_node(
         jnod_local, time_stepper_pt);
       // Set the pointer from the element to the node
       finite_element_pt(2)->node_pt(jnod_local) = Node_pt[node_count];
       // Set the position of the node
       s[0] = -1.0;
       s[1] = -1.0 + 2.0 * double(l2) / double(n_p - 1);
       ;
       Domain_pt->macro_element_pt(2)->macro_map(s, r);
       Node_pt[node_count]->x(0) = r[0];
       Node_pt[node_count]->x(1) = r[1];
       // Add the node to the boundary
       add_boundary_node(2, Node_pt[node_count]);
       // Increment the node number
       node_count++;
       // The other nodes are in the interior
       //------------------------------------
       // Loop over the other node columns
       for (unsigned l1 = 1; l1 < n_p - 1; l1++)
       {
         // Local node number
         unsigned jnod_local = l1 + n_p * l2;
         // Create the node
         Node_pt[node_count] =
           finite_element_pt(2)->construct_node(jnod_local, time_stepper_pt);
         // Set the pointer from the element to the node
         finite_element_pt(2)->node_pt(jnod_local) = Node_pt[node_count];
         // Set the position of the node
         s[0] = -1.0 + 2.0 * double(l1) / double(n_p - 1);
         s[1] = -1.0 + 2.0 * double(l2) / double(n_p - 1);
         Domain_pt->macro_element_pt(2)->macro_map(s, r);
         Node_pt[node_count]->x(0) = r[0];
         Node_pt[node_count]->x(1) = r[1];
         // Increment the node number
         node_count++;
       }
     }
     // Top left corner is on boundaries 1 and 2:
     //------------------------------------------
     // Local node number
     jnod_local = n_p * (n_p - 1);
     // Create the node
     Node_pt[node_count] = finite_element_pt(2)->construct_boundary_node(
       jnod_local, time_stepper_pt);
     // Set the pointer from the element to the node
     finite_element_pt(2)->node_pt(jnod_local) = Node_pt[node_count];
     // Set the position of the node
     s[0] = -1.0;
     s[1] = 1.0;
     Domain_pt->macro_element_pt(2)->macro_map(s, r);
     Node_pt[node_count]->x(0) = r[0];
     Node_pt[node_count]->x(1) = r[1];
     // Add the node to the boundaries
     add_boundary_node(1, Node_pt[node_count]);
     add_boundary_node(2, Node_pt[node_count]);
     // Set the intrinsic coordinate on the boundary 1
     zeta[0] = Xi_hi + 0.5 * (s[0] + 1.0) * (1.0 - Fract_mid) * (Xi_lo - Xi_hi);
     Node_pt[node_count]->set_coordinates_on_boundary(1, zeta);
     // Increment the node number
     node_count++;
     // Rest of top row is on boundary 1 only:
     //---------------------------------------
     for (unsigned l1 = 1; l1 < n_p - 1; l1++)
     {
       // Local node number
       unsigned jnod_local = n_p * (n_p - 1) + l1;
       // Create the node
       Node_pt[node_count] = finite_element_pt(2)->construct_boundary_node(
         jnod_local, time_stepper_pt);
       // Set the pointer from the element to the node
       finite_element_pt(2)->node_pt(jnod_local) = Node_pt[node_count];
       // Set the position of the node
       s[0] = -1.0 + 2.0 * double(l1) / double(n_p - 1);
       s[1] = 1.0;
       Domain_pt->macro_element_pt(2)->macro_map(s, r);
       Node_pt[node_count]->x(0) = r[0];
       Node_pt[node_count]->x(1) = r[1];
       // Add the node to the boundary
       add_boundary_node(1, Node_pt[node_count]);
       // Set the intrinsic coordinate on the boundary 1
       zeta[0] =
         Xi_hi + 0.5 * (s[0] + 1.0) * (1.0 - Fract_mid) * (Xi_lo - Xi_hi);
       Node_pt[node_count]->set_coordinates_on_boundary(1, zeta);
       // Increment the node number
       node_count++;
     }
     // Loop over all elements and set macro element pointer
     // to enable MacroElement-based node update
     unsigned n_element = this->nelement();
     for (unsigned e = 0; e < n_element; e++)
     {
       // Get pointer to full element type
       ELEMENT* el_pt = dynamic_cast<ELEMENT*>(this->element_pt(e));
       // Set pointer to macro element
       el_pt->set_macro_elem_pt(this->Domain_pt->macro_element_pt(e));
     }
     // Setup boundary element lookup schemes
     setup_boundary_element_info();
   }
References oomph::Mesh::add_boundary_node(), oomph::Mesh::Boundary_coordinate_exists, oomph::FiniteElement::construct_boundary_node(), oomph::FiniteElement::construct_node(), oomph::QuarterCircleSectorMesh< ELEMENT >::Domain_pt, e(), oomph::Mesh::Element_pt, oomph::Mesh::element_pt(), oomph::Mesh::finite_element_pt(), oomph::QuarterCircleSectorMesh< ELEMENT >::Fract_mid, oomph::Domain::macro_element_pt(), oomph::MacroElement::macro_map(), oomph::Mesh::nelement(), oomph::FiniteElement::node_pt(), oomph::Mesh::Node_pt, UniformPSDSelfTest::r, s, oomph::Mesh::set_nboundary(), oomph::QuadMeshBase::setup_boundary_element_info(), oomph::QuarterCircleSectorMesh< ELEMENT >::wall_pt(), oomph::QuarterCircleSectorMesh< ELEMENT >::Xi_hi, oomph::QuarterCircleSectorMesh< ELEMENT >::Xi_lo, and Eigen::zeta().
~QuarterCircleSectorMesh()
template<class ELEMENT > virtual oomph::QuarterCircleSectorMesh< ELEMENT >::~QuarterCircleSectorMesh () inline virtual
Destructor:
 {}
Member Function Documentation
bl_squash_fct_pt()
template<class ELEMENT > QuarterCircleSectorDomain::BLSquashFctPt& oomph::QuarterCircleSectorMesh< ELEMENT >::bl_squash_fct_pt () inline
Function pointer for function that squashes the outer two macro elements towards the wall by mapping the input value of the "radial" macro element coordinate to the return value (defined in the underlying Domain object)
     {
       return Domain_pt->bl_squash_fct_pt();
     }
References oomph::QuarterCircleSectorDomain::bl_squash_fct_pt(), and oomph::QuarterCircleSectorMesh< ELEMENT >::Domain_pt.
domain_pt()
template<class ELEMENT > QuarterCircleSectorDomain* oomph::QuarterCircleSectorMesh< ELEMENT >::domain_pt () inline
Access function to domain.
     {
       return Domain_pt;
     }
References oomph::QuarterCircleSectorMesh< ELEMENT >::Domain_pt.
Referenced by oomph::MacroElementNodeUpdateRefineableQuarterCircleSectorMesh< ELEMENT >::setup_macro_element_node_update().
wall_pt()
template<class ELEMENT > GeomObject*& oomph::QuarterCircleSectorMesh< ELEMENT >::wall_pt () inline
Access function to GeomObject representing wall.
     {
       return Wall_pt;
     }
References oomph::QuarterCircleSectorMesh< ELEMENT >::Wall_pt.
Referenced by oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::AlgebraicRefineableQuarterCircleSectorMesh(), and oomph::QuarterCircleSectorMesh< ELEMENT >::QuarterCircleSectorMesh().
Member Data Documentation
Domain_pt
template<class ELEMENT > QuarterCircleSectorDomain* oomph::QuarterCircleSectorMesh< ELEMENT >::Domain_pt protected
Pointer to Domain.
Referenced by oomph::QuarterCircleSectorMesh< ELEMENT >::bl_squash_fct_pt(), oomph::QuarterCircleSectorMesh< ELEMENT >::domain_pt(), and oomph::QuarterCircleSectorMesh< ELEMENT >::QuarterCircleSectorMesh().
Fract_mid
template<class ELEMENT > double oomph::QuarterCircleSectorMesh< ELEMENT >::Fract_mid protected
Fraction along wall where outer ring is to be divided.
Referenced by oomph::QuarterCircleSectorMesh< ELEMENT >::QuarterCircleSectorMesh().
Wall_pt
template<class ELEMENT > GeomObject* oomph::QuarterCircleSectorMesh< ELEMENT >::Wall_pt protected
Pointer to the geometric object that represents the curved wall (mesh boundary 1)
Referenced by oomph::MacroElementNodeUpdateRefineableQuarterCircleSectorMesh< ELEMENT >::setup_macro_element_node_update(), and oomph::QuarterCircleSectorMesh< ELEMENT >::wall_pt().
Xi_hi
template<class ELEMENT > double oomph::QuarterCircleSectorMesh< ELEMENT >::Xi_hi protected
Upper limit for the (1D) coordinates along the wall.
Referenced by oomph::QuarterCircleSectorMesh< ELEMENT >::QuarterCircleSectorMesh().
Xi_lo
template<class ELEMENT > double oomph::QuarterCircleSectorMesh< ELEMENT >::Xi_lo protected
Lower limit for the (1D) coordinates along the wall.
Referenced by oomph::QuarterCircleSectorMesh< ELEMENT >::QuarterCircleSectorMesh().
The documentation for this class was generated from the following files:
quarter_circle_sector_mesh.template.h
quarter_circle_sector_mesh.template.cc