MercuryDPM: Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device > Struct Template Reference
#include <TensorImagePatch.h>
Public Types
enum {
IsAligned = false , PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess , BlockAccess = false , PreferBlockAccess = true ,
CoordAccess = false , RawAccess = false
}
typedef TensorImagePatchOp< Rows, Cols, ArgType > XprType
typedef XprType::Index Index
typedef DSizes< Index, NumDims > Dimensions
typedef std::remove_const_t< typename XprType::Scalar > Scalar
typedef TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device > Self
typedef TensorEvaluator< ArgType, Device > Impl
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorBlockNotImplemented TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EvaluatorPointerType data () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorEvaluator< ArgType, Device > & impl () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rowPaddingTop () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index colPaddingLeft () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index outputRows () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index outputCols () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index userRowStride () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index userColStride () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index userInRowStride () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index userInColStride () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rowInflateStride () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index colInflateStride () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
Static Public Attributes
static constexpr int NumInputDims
static constexpr int NumDims = NumInputDims + 1
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Protected Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packetWithPossibleZero (Index index) const
Protected Attributes
Dimensions m_dimensions
Index m_otherStride
Index m_patchStride
Index m_colStride
Index m_row_strides
Index m_col_strides
Index m_in_row_strides
Index m_in_col_strides
Index m_row_inflate_strides
Index m_col_inflate_strides
Index m_input_rows_eff
Index m_input_cols_eff
Index m_patch_rows_eff
Index m_patch_cols_eff
internal::TensorIntDivisor< Index > m_fastOtherStride
internal::TensorIntDivisor< Index > m_fastPatchStride
internal::TensorIntDivisor< Index > m_fastColStride
internal::TensorIntDivisor< Index > m_fastInflateRowStride
internal::TensorIntDivisor< Index > m_fastInflateColStride
internal::TensorIntDivisor< Index > m_fastInputColsEff
Index m_rowInputStride
Index m_colInputStride
Index m_patchInputStride
Index m_inputDepth
Index m_inputRows
Index m_inputCols
Index m_outputRows
Index m_outputCols
Index m_rowPaddingTop
Index m_colPaddingLeft
internal::TensorIntDivisor< Index > m_fastOutputRows
internal::TensorIntDivisor< Index > m_fastOutputDepth
Scalar m_paddingValue
const Device EIGEN_DEVICE_REF m_device
TensorEvaluator< ArgType, Device > m_impl
Member Typedef Documentation
CoeffReturnType
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::CoeffReturnType
Dimensions
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > typedef DSizes<Index, NumDims> Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::Dimensions
EvaluatorPointerType
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::EvaluatorPointerType
Impl
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > typedef TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::Impl
Index
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::Index
PacketReturnType
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::PacketReturnType
Scalar
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > typedef std::remove_const_t<typename XprType::Scalar> Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::Scalar
Self
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > typedef TensorEvaluator<const TensorImagePatchOp<Rows, Cols, ArgType>, Device> Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::Self
Storage
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::Storage
TensorBlock
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > typedef internal::TensorBlockNotImplemented Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::TensorBlock
XprType
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > typedef TensorImagePatchOp<Rows, Cols, ArgType> Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = false,
     PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess,
     BlockAccess = false,
     PreferBlockAccess = true,
     CoordAccess = false,
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_device(device), m_impl(op.expression(), device) {
     EIGEN_STATIC_ASSERT((NumDims >= 4), YOU_MADE_A_PROGRAMMING_MISTAKE);
     m_paddingValue = op.padding_value();
     const typename TensorEvaluator<ArgType, Device>::Dimensions& input_dims = m_impl.dimensions();
     // Caches a few variables.
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       m_inputDepth = input_dims[0];
       m_inputRows = input_dims[1];
       m_inputCols = input_dims[2];
     } else {
       m_inputDepth = input_dims[NumInputDims - 1];
       m_inputRows = input_dims[NumInputDims - 2];
       m_inputCols = input_dims[NumInputDims - 3];
     }
     m_row_strides = op.row_strides();
     m_col_strides = op.col_strides();
     // Input strides and effective input/patch size
     m_in_row_strides = op.in_row_strides();
     m_in_col_strides = op.in_col_strides();
     m_row_inflate_strides = op.row_inflate_strides();
     m_col_inflate_strides = op.col_inflate_strides();
     // The "effective" input rows and input cols are the input rows and cols
     // after inflating them with zeros.
     // For examples, a 2x3 matrix with row_inflate_strides and
     // col_inflate_strides of 2 comes from:
     //   A B C
     //   D E F
     //
     // to a matrix is 3 x 5:
     //
     //   A . B . C
     //   . . . . .
     //   D . E . F
     m_input_rows_eff = (m_inputRows - 1) * m_row_inflate_strides + 1;
     m_input_cols_eff = (m_inputCols - 1) * m_col_inflate_strides + 1;
     m_patch_rows_eff = op.patch_rows() + (op.patch_rows() - 1) * (m_in_row_strides - 1);
     m_patch_cols_eff = op.patch_cols() + (op.patch_cols() - 1) * (m_in_col_strides - 1);
     if (op.padding_explicit()) {
       m_outputRows = numext::ceil((m_input_rows_eff + op.padding_top() + op.padding_bottom() - m_patch_rows_eff + 1.f) /
                                   static_cast<float>(m_row_strides));
       m_outputCols = numext::ceil((m_input_cols_eff + op.padding_left() + op.padding_right() - m_patch_cols_eff + 1.f) /
                                   static_cast<float>(m_col_strides));
       m_rowPaddingTop = op.padding_top();
       m_colPaddingLeft = op.padding_left();
     } else {
       // Computing padding from the type
       switch (op.padding_type()) {
         case PADDING_VALID:
           m_outputRows = numext::ceil((m_input_rows_eff - m_patch_rows_eff + 1.f) / static_cast<float>(m_row_strides));
           m_outputCols = numext::ceil((m_input_cols_eff - m_patch_cols_eff + 1.f) / static_cast<float>(m_col_strides));
           // Calculate the padding
           m_rowPaddingTop =
               numext::maxi<Index>(0, ((m_outputRows - 1) * m_row_strides + m_patch_rows_eff - m_input_rows_eff) / 2);
           m_colPaddingLeft =
               numext::maxi<Index>(0, ((m_outputCols - 1) * m_col_strides + m_patch_cols_eff - m_input_cols_eff) / 2);
           break;
         case PADDING_SAME:
           m_outputRows = numext::ceil(m_input_rows_eff / static_cast<float>(m_row_strides));
           m_outputCols = numext::ceil(m_input_cols_eff / static_cast<float>(m_col_strides));
           // Calculate the padding
           m_rowPaddingTop = ((m_outputRows - 1) * m_row_strides + m_patch_rows_eff - m_input_rows_eff) / 2;
           m_colPaddingLeft = ((m_outputCols - 1) * m_col_strides + m_patch_cols_eff - m_input_cols_eff) / 2;
           // The padding size calculation for PADDING_SAME has been updated to
           // be consistent with how TensorFlow extracts its paddings.
           m_rowPaddingTop = numext::maxi<Index>(0, m_rowPaddingTop);
           m_colPaddingLeft = numext::maxi<Index>(0, m_colPaddingLeft);
           break;
         default:
           eigen_assert(false && "unexpected padding");
           m_outputCols = 0;  // silence the uninitialised warning;
           m_outputRows = 0;
       }
     }
     eigen_assert(m_outputRows > 0);
     eigen_assert(m_outputCols > 0);
     // Dimensions for result of extraction.
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       // ColMajor
       // 0: depth
       // 1: patch_rows
       // 2: patch_cols
       // 3: number of patches
       // 4 and beyond: anything else (such as batch).
       m_dimensions[0] = input_dims[0];
       m_dimensions[1] = op.patch_rows();
       m_dimensions[2] = op.patch_cols();
       m_dimensions[3] = m_outputRows * m_outputCols;
       for (int i = 4; i < NumDims; ++i) {
         m_dimensions[i] = input_dims[i - 1];
       }
     } else {
       // RowMajor
       // NumDims-1: depth
       // NumDims-2: patch_rows
       // NumDims-3: patch_cols
       // NumDims-4: number of patches
       // NumDims-5 and beyond: anything else (such as batch).
       m_dimensions[NumDims - 1] = input_dims[NumInputDims - 1];
       m_dimensions[NumDims - 2] = op.patch_rows();
       m_dimensions[NumDims - 3] = op.patch_cols();
       m_dimensions[NumDims - 4] = m_outputRows * m_outputCols;
       for (int i = NumDims - 5; i >= 0; --i) {
         m_dimensions[i] = input_dims[i];
       }
     }
     // Strides for moving the patch in various dimensions.
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       m_colStride = m_dimensions[1];
       m_patchStride = m_colStride * m_dimensions[2] * m_dimensions[0];
       m_otherStride = m_patchStride * m_dimensions[3];
     } else {
       m_colStride = m_dimensions[NumDims - 2];
       m_patchStride = m_colStride * m_dimensions[NumDims - 3] * m_dimensions[NumDims - 1];
       m_otherStride = m_patchStride * m_dimensions[NumDims - 4];
     }
     // Strides for navigating through the input tensor.
     m_rowInputStride = m_inputDepth;
     m_colInputStride = m_inputDepth * m_inputRows;
     m_patchInputStride = m_inputDepth * m_inputRows * m_inputCols;
     // Fast representations of different variables.
     m_fastOtherStride = internal::TensorIntDivisor<Index>(m_otherStride);
     m_fastPatchStride = internal::TensorIntDivisor<Index>(m_patchStride);
     m_fastColStride = internal::TensorIntDivisor<Index>(m_colStride);
     m_fastInflateRowStride = internal::TensorIntDivisor<Index>(m_row_inflate_strides);
     m_fastInflateColStride = internal::TensorIntDivisor<Index>(m_col_inflate_strides);
     m_fastInputColsEff = internal::TensorIntDivisor<Index>(m_input_cols_eff);
     // Number of patches in the width dimension.
     m_fastOutputRows = internal::TensorIntDivisor<Index>(m_outputRows);
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       m_fastOutputDepth = internal::TensorIntDivisor<Index>(m_dimensions[0]);
     } else {
       m_fastOutputDepth = internal::TensorIntDivisor<Index>(m_dimensions[NumDims - 1]);
     }
   }
References Eigen::numext::ceil(), Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), eigen_assert, EIGEN_STATIC_ASSERT, i, Eigen::TensorEvaluator< Derived, Device >::Layout, op, Eigen::PADDING_SAME, and Eigen::PADDING_VALID.
Member Function Documentation
cleanup()
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::cleanup () inline
 { m_impl.cleanup(); }
Referenced by framework.Frame::__init__().
coeff()
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::coeff (Index index) const inline
{
     // Patch index corresponding to the passed in index.
     const Index patchIndex = index / m_fastPatchStride;
     // Find the offset of the element wrt the location of the first element.
     const Index patchOffset = (index - patchIndex * m_patchStride) / m_fastOutputDepth;
     // Other ways to index this element.
     const Index otherIndex = (NumDims == 4) ? 0 : index / m_fastOtherStride;
     const Index patch2DIndex = (NumDims == 4) ? patchIndex : (index - otherIndex * m_otherStride) / m_fastPatchStride;
     // Calculate col index in the input original tensor.
     const Index colIndex = patch2DIndex / m_fastOutputRows;
     const Index colOffset = patchOffset / m_fastColStride;
     const Index inputCol = colIndex * m_col_strides + colOffset * m_in_col_strides - m_colPaddingLeft;
     const Index origInputCol =
         (m_col_inflate_strides == 1) ? inputCol : ((inputCol >= 0) ? (inputCol / m_fastInflateColStride) : 0);
     if (inputCol < 0 || inputCol >= m_input_cols_eff ||
         ((m_col_inflate_strides != 1) && (inputCol != origInputCol * m_col_inflate_strides))) {
       return Scalar(m_paddingValue);
     }
     // Calculate row index in the original input tensor.
     const Index rowIndex = patch2DIndex - colIndex * m_outputRows;
     const Index rowOffset = patchOffset - colOffset * m_colStride;
     const Index inputRow = rowIndex * m_row_strides + rowOffset * m_in_row_strides - m_rowPaddingTop;
     const Index origInputRow =
         (m_row_inflate_strides == 1) ? inputRow : ((inputRow >= 0) ? (inputRow / m_fastInflateRowStride) : 0);
     if (inputRow < 0 || inputRow >= m_input_rows_eff ||
         ((m_row_inflate_strides != 1) && (inputRow != origInputRow * m_row_inflate_strides))) {
       return Scalar(m_paddingValue);
     }
     const int depth_index = static_cast<int>(Layout) == static_cast<int>(ColMajor) ? 0 : NumDims - 1;
     const Index depth = index - (index / m_fastOutputDepth) * m_dimensions[depth_index];
     const Index inputIndex =
         depth + origInputRow * m_rowInputStride + origInputCol * m_colInputStride + otherIndex * m_patchInputStride;
     return m_impl.coeff(inputIndex);
   }
References Eigen::ColMajor, and Eigen::TensorEvaluator< Derived, Device >::Layout.
colInflateStride()
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::colInflateStride () const inline
 { return m_col_inflate_strides; }
colPaddingLeft()
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::colPaddingLeft () const inline
 { return m_colPaddingLeft; }
costPerCoeff()
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     // We conservatively estimate the cost for the code path where the computed
     // index is inside the original image and
     // TensorEvaluator<ArgType, Device>::CoordAccess is false.
     const double compute_cost =
         3 * TensorOpCost::DivCost<Index>() + 6 * TensorOpCost::MulCost<Index>() + 8 * TensorOpCost::MulCost<Index>();
     return m_impl.costPerCoeff(vectorized) + TensorOpCost(0, 0, compute_cost, vectorized, PacketSize);
   }
References Eigen::TensorEvaluator< Derived, Device >::PacketSize.
data()
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EvaluatorPointerType Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::dimensions () const inline
 { return m_dimensions; }
evalSubExprsIfNeeded()
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
{
     m_impl.evalSubExprsIfNeeded(NULL);
     return true;
   }
impl()
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorEvaluator<ArgType, Device>& Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::impl () const inline
 { return m_impl; }
outputCols()
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::outputCols () const inline
 { return m_outputCols; }
outputRows()
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::outputRows () const inline
 { return m_outputRows; }
packet()
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::packet (Index index) const inline
{
     eigen_assert(index + PacketSize - 1 < dimensions().TotalSize());
     if (m_in_row_strides != 1 || m_in_col_strides != 1 || m_row_inflate_strides != 1 || m_col_inflate_strides != 1) {
       return packetWithPossibleZero(index);
     }
     const Index indices[2] = {index, index + PacketSize - 1};
     const Index patchIndex = indices[0] / m_fastPatchStride;
     if (patchIndex != indices[1] / m_fastPatchStride) {
       return packetWithPossibleZero(index);
     }
     const Index otherIndex = (NumDims == 4) ? 0 : indices[0] / m_fastOtherStride;
     eigen_assert(otherIndex == indices[1] / m_fastOtherStride);
     // Find the offset of the element wrt the location of the first element.
     const Index patchOffsets[2] = {(indices[0] - patchIndex * m_patchStride) / m_fastOutputDepth,
                                    (indices[1] - patchIndex * m_patchStride) / m_fastOutputDepth};
     const Index patch2DIndex =
         (NumDims == 4) ? patchIndex : (indices[0] - otherIndex * m_otherStride) / m_fastPatchStride;
     eigen_assert(patch2DIndex == (indices[1] - otherIndex * m_otherStride) / m_fastPatchStride);
     const Index colIndex = patch2DIndex / m_fastOutputRows;
     const Index colOffsets[2] = {patchOffsets[0] / m_fastColStride, patchOffsets[1] / m_fastColStride};
     // Calculate col indices in the original input tensor.
     const Index inputCols[2] = {colIndex * m_col_strides + colOffsets[0] - m_colPaddingLeft,
                                 colIndex * m_col_strides + colOffsets[1] - m_colPaddingLeft};
     if (inputCols[1] < 0 || inputCols[0] >= m_inputCols) {
       return internal::pset1<PacketReturnType>(Scalar(m_paddingValue));
     }
     if (inputCols[0] == inputCols[1]) {
       const Index rowIndex = patch2DIndex - colIndex * m_outputRows;
       const Index rowOffsets[2] = {patchOffsets[0] - colOffsets[0] * m_colStride,
                                    patchOffsets[1] - colOffsets[1] * m_colStride};
       eigen_assert(rowOffsets[0] <= rowOffsets[1]);
       // Calculate col indices in the original input tensor.
       const Index inputRows[2] = {rowIndex * m_row_strides + rowOffsets[0] - m_rowPaddingTop,
                                   rowIndex * m_row_strides + rowOffsets[1] - m_rowPaddingTop};
       if (inputRows[1] < 0 || inputRows[0] >= m_inputRows) {
         return internal::pset1<PacketReturnType>(Scalar(m_paddingValue));
       }
       if (inputRows[0] >= 0 && inputRows[1] < m_inputRows) {
         // no padding
         const int depth_index = static_cast<int>(Layout) == static_cast<int>(ColMajor) ? 0 : NumDims - 1;
         const Index depth = index - (index / m_fastOutputDepth) * m_dimensions[depth_index];
         const Index inputIndex =
             depth + inputRows[0] * m_rowInputStride + inputCols[0] * m_colInputStride + otherIndex * m_patchInputStride;
         return m_impl.template packet<Unaligned>(inputIndex);
       }
     }
     return packetWithPossibleZero(index);
   }
References Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), eigen_assert, Eigen::TensorEvaluator< Derived, Device >::Layout, and Eigen::TensorEvaluator< Derived, Device >::PacketSize.
packetWithPossibleZero()
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::packetWithPossibleZero (Index index) const inline protected
{
     EIGEN_ALIGN_MAX std::remove_const_t<CoeffReturnType> values[PacketSize];
     EIGEN_UNROLL_LOOP
     for (int i = 0; i < PacketSize; ++i) {
       values[i] = coeff(index + i);
     }
     PacketReturnType rslt = internal::pload<PacketReturnType>(values);
     return rslt;
   }
References Eigen::TensorEvaluator< Derived, Device >::coeff(), EIGEN_ALIGN_MAX, EIGEN_UNROLL_LOOP, i, and Eigen::TensorEvaluator< Derived, Device >::PacketSize.
rowInflateStride()
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::rowInflateStride () const inline
 { return m_row_inflate_strides; }
rowPaddingTop()
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::rowPaddingTop () const inline
 { return m_rowPaddingTop; }
userColStride()
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::userColStride () const inline
 { return m_col_strides; }
userInColStride()
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::userInColStride () const inline
 { return m_in_col_strides; }
userInRowStride()
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::userInRowStride () const inline
 { return m_in_row_strides; }
userRowStride()
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::userRowStride () const inline
 { return m_row_strides; }
Member Data Documentation
Layout
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_col_inflate_strides
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_col_inflate_strides protected
m_col_strides
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_col_strides protected
m_colInputStride
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_colInputStride protected
m_colPaddingLeft
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_colPaddingLeft protected
m_colStride
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_colStride protected
m_device
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > const Device EIGEN_DEVICE_REF Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_device protected
m_dimensions
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Dimensions Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_dimensions protected
m_fastColStride
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_fastColStride protected
m_fastInflateColStride
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_fastInflateColStride protected
m_fastInflateRowStride
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_fastInflateRowStride protected
m_fastInputColsEff
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_fastInputColsEff protected
m_fastOtherStride
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_fastOtherStride protected
m_fastOutputDepth
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_fastOutputDepth protected
m_fastOutputRows
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_fastOutputRows protected
m_fastPatchStride
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > internal::TensorIntDivisor<Index> Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_fastPatchStride protected
m_impl
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_impl protected
m_in_col_strides
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_in_col_strides protected
m_in_row_strides
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_in_row_strides protected
m_input_cols_eff
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_input_cols_eff protected
m_input_rows_eff
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_input_rows_eff protected
m_inputCols
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_inputCols protected
m_inputDepth
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_inputDepth protected
m_inputRows
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_inputRows protected
m_otherStride
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_otherStride protected
m_outputCols
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_outputCols protected
m_outputRows
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_outputRows protected
m_paddingValue
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Scalar Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_paddingValue protected
m_patch_cols_eff
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_patch_cols_eff protected
m_patch_rows_eff
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_patch_rows_eff protected
m_patchInputStride
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_patchInputStride protected
m_patchStride
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_patchStride protected
m_row_inflate_strides
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_row_inflate_strides protected
m_row_strides
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_row_strides protected
m_rowInputStride
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_rowInputStride protected
m_rowPaddingTop
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::m_rowPaddingTop protected
NumDims
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::NumDims = NumInputDims + 1 static constexpr
NumInputDims
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::NumInputDims static constexpr
Initial value:
=
      internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value
PacketSize
template<DenseIndex Rows, DenseIndex Cols, typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorImagePatch.h