MercuryDPM: locate_zeta_tester_3d.cc File Reference
locate_zeta_tester_3d.cc File Reference
#include "generic.h"
#include "poisson.h"
#include "meshes/eighth_sphere_mesh.h"
#include "locate_zeta_tester.h"
Classes
class EighthSpherePoissonProblem< ELEMENT >
Poisson problem in refineable eighth of a sphere mesh.
Namespaces
TanhSolnForPoisson
Namespace for exact solution for Poisson equation with "sharp step".
Functions
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, double &u)
Exact solution as a scalar.
void TanhSolnForPoisson::get_source (const Vector< double > &x, double &source)
Source function to make it an exact solution.
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Driver for 3D Poisson problem in eighth of a sphere. Solution has a sharp step. If there are any command line arguments, we regard this as a validation run and perform only a single adaptation.
 {
  FiniteElement::Tolerance_for_singular_jacobian = 0.0;
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Number of biased refinements for locate zeta test
  unsigned nrefine_for_locate_zeta_test=10;
  CommandLineArgs::specify_command_line_flag("--nrefine_for_locate_zeta_test",
                                             &nrefine_for_locate_zeta_test);
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Set up the problem with 27-node brick elements, pass pointer to
  // source function
  EighthSpherePoissonProblem<RefineableQPoissonElement<3,3> >
   problem(&TanhSolnForPoisson::get_source);
  // Setup labels for output
   DocInfo doc_info;
  // Output directory
  doc_info.set_directory("RESLT");
  // Step number
  doc_info.number()=0;
  // Check if we're ready to go
  cout << "Self test: " << problem.self_test() << std::endl;
  // Solve the problem
  problem.newton_solve();
  //Output solution
  problem.doc_solution(doc_info);
  //Increment counter for solutions
  doc_info.number()++;
  // Up to four adaptations
  unsigned max_solve=1; // hierher 4;
  for (unsigned isolve=0;isolve<max_solve;isolve++)
   {
    // Adapt problem/mesh
    problem.adapt();
    // Re-solve the problem if the adaptation has changed anything
    if ((problem.mesh_pt()->nrefined()  !=0)||
        (problem.mesh_pt()->nunrefined()!=0))
     {
      problem.newton_solve();
     }
    else
     {
      cout << "Mesh wasn't adapted --> we'll stop here" << std::endl;
      break;
     }
    //Output solution
    problem.doc_solution(doc_info);
    //Increment counter for solutions
    doc_info.number()++;
   }
  // Setup fake error estimator: Boundaries of refiment region
  Vector<double> lower_left(3);
  Vector<double> upper_right(3);
  double box_size=0.7;
  lower_left[0]=2.0;
  lower_left[1]=2.0;
  lower_left[2]=0.1;
  upper_right[0]=lower_left[0]+box_size;
  upper_right[1]=lower_left[1]+box_size;
  upper_right[2]=lower_left[2]+box_size;
  unsigned central_node_number=13;
  // Stop unrefinement and allow for infinite refinement
  problem.mesh_pt()->min_permitted_error()=-1.0;
  problem.mesh_pt()->max_refinement_level()=UINT_MAX;
  // Adapt lots of times
  for (unsigned i=0;i<nrefine_for_locate_zeta_test;i++)
   {
    // Clean up
    delete problem.mesh_pt()->spatial_error_estimator_pt();
    // Make a new error estimator
    problem.mesh_pt()->spatial_error_estimator_pt()=
     new DummyErrorEstimator(problem.mesh_pt(),lower_left,upper_right,
                             central_node_number);
    // Adapt
    problem.adapt();
    // Shrink box
    double shrink_factor=0.6;
    lower_left[0]+=0.5*box_size*(1.0-shrink_factor);
    lower_left[1]+=0.5*box_size*(1.0-shrink_factor);
    lower_left[2]+=0.5*box_size*(1.0-shrink_factor);
    box_size*=shrink_factor;
    upper_right[0]=lower_left[0]+box_size;
    upper_right[1]=lower_left[1]+box_size;
    upper_right[2]=lower_left[2]+box_size;
   }
  //Output the solution
  problem.doc_solution(doc_info);
  // Check it out!
  check_locate_zeta(problem.mesh_pt());
 } // end of main
References check_locate_zeta(), oomph::CommandLineArgs::doc_specified_flags(), TanhSolnForPoisson::get_source(), i, oomph::DocInfo::number(), oomph::CommandLineArgs::parse_and_assign(), problem, oomph::DocInfo::set_directory(), Flag_definition::setup(), and oomph::CommandLineArgs::specify_command_line_flag().