MercuryDPM: bench_move_semantics.cpp File Reference
bench_move_semantics.cpp File Reference
#include "BenchTimer.h"
#include "../test/MovableScalar.h"
#include <Eigen/Core>
#include <iostream>
#include <utility>
Functions
template<typename MatrixType >
void copy_matrix (MatrixType &m)
template<typename MatrixType >
void move_matrix (MatrixType &&m)
template<typename Scalar >
void bench (const std::string &label)
int main ()
Function Documentation
bench()
template<typename Scalar > void bench (const std::string & label)
{
   using MatrixType = Eigen::Matrix<Eigen::MovableScalar<Scalar>, 1, 10>;
   Eigen::BenchTimer t;
   int tries = 10;
   int rep = 1000000;
   MatrixType data = MatrixType::Random().eval();
   MatrixType dest;
   BENCH(t, tries, rep, copy_matrix(data));
   std::cout << label << " copy semantics: " << 1e3 * t.best(Eigen::CPU_TIMER) << " ms" << std::endl;
   BENCH(t, tries, rep, move_matrix(std::move(data)));
   std::cout << label << " move semantics: " << 1e3 * t.best(Eigen::CPU_TIMER) << " ms" << std::endl;
 }
References BENCH, copy_matrix(), Eigen::CPU_TIMER, data, UniformPSDSelfTest::label, move_matrix(), and plotPSD::t.
copy_matrix()
template<typename MatrixType > void copy_matrix (MatrixType & m)
{
   MatrixType tmp(m);
   m = tmp;
 }
References m, and tmp.
Referenced by bench().
main()
int main ()
            {
   bench<float>("float");
   bench<double>("double");
   return 0;
 }
move_matrix()
template<typename MatrixType > void move_matrix (MatrixType && m)
{
   MatrixType tmp(std::move(m));
   m = std::move(tmp);
 }
References m, and tmp.
Referenced by bench().