MercuryDPM: oomph::ElementWithMovingNodes Class Reference
oomph::ElementWithMovingNodes Class Reference
#include <element_with_moving_nodes.h>
Public Types
enum { Shape_derivs_by_chain_rule , Shape_derivs_by_direct_fd , Shape_derivs_by_fastest_method }
Public enumeration to choose method for computing shape derivatives.
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Member Functions
ElementWithMovingNodes ()
Constructor.
ElementWithMovingNodes (const ElementWithMovingNodes &)=delete
Broken copy constructor.
void operator= (const ElementWithMovingNodes &)=delete
Broken assignment operator.
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual ~ElementWithMovingNodes ()
Virtual destructor (clean up and allocated memory)
unsigned ngeom_dof () const
Number of geometric dofs.
int geometric_data_local_eqn (const unsigned &n, const unsigned &i)
void assemble_set_of_all_geometric_data (std::set< Data * > &unique_geom_data_pt)
Return a set of all geometric data associated with the element.
void identify_geometric_data (std::set< Data * > &geometric_data_pt)
bool are_dresidual_dnodal_coordinates_always_evaluated_by_fd () const
Return whether shape derivatives are evaluated by fd.
void enable_always_evaluate_dresidual_dnodal_coordinates_by_fd ()
void disable_always_evaluate_dresidual_dnodal_coordinates_by_fd ()
void evaluate_shape_derivs_by_direct_fd ()
Evaluate shape derivatives by direct finite differencing.
void evaluate_shape_derivs_by_chain_rule (const bool &i_know_what_i_am_doing=false)
void evaluate_shape_derivs_by_fastest_method (const bool &i_know_what_i_am_doing=false)
int & method_for_shape_derivs ()
Access to method (enumerated flag) for determination of shape derivs.
void enable_bypass_fill_in_jacobian_from_geometric_data ()
Bypass the call to fill_in_jacobian_from_geometric_data.
void disable_bypass_fill_in_jacobian_from_geometric_data ()
Do not bypass the call to fill_in_jacobian_from_geometric_data.
bool is_fill_in_jacobian_from_geometric_data_bypassed () const
unsigned ngeom_data () const
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (std::ostream &outfile)
virtual void output (std::ostream &outfile, const unsigned &n_plot)
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output (FILE *file_pt)
virtual void output (FILE *file_pt, const unsigned &n_plot)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Protected Member Functions
virtual void get_dnodal_coordinates_dgeom_dofs (RankThreeTensor< double > &dnodal_coordinates_dgeom_dofs)
void complete_setup_of_dependencies ()
Construct the vector of (unique) geometric data.
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
void fill_in_jacobian_from_geometric_data (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_geometric_data (DenseMatrix< double > &jacobian)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes
Vector< Data * > Geom_data_pt
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Private Attributes
int ** Geometric_data_local_eqn
unsigned Ngeom_dof
bool Bypass_fill_in_jacobian_from_geometric_data
bool Evaluate_dresidual_dnodal_coordinates_by_fd
int Method_for_shape_derivs
Additional Inherited Members
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
/////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////// A policy class that serves to establish the common interfaces for elements that contain moving nodes. This class provides storage for the geometric data that affect the update of all the nodes of the element, i.e. USUALLY all data that are using during a call to the Element's node_update() function. In some cases (e.g. FluidInterfaceEdge elements), node_update() is overloaded to perform an update of the bulk element, in which case the additional bulk geometric data become external data of the element and the function GeneralisedElement::update_in_external_fd(i) is overloaded to also perform the bulk node update. The storage is populated during the assignment of the equation numbers via the complete_setup_of_dependencies() function and then local equations numbers are assigned to these data, accessible via geometric_data_local_eqn(n,i). Finally, a function is provided that calculates the terms in the jacobian matrix by due to these geometric data by finite differences.
Member Enumeration Documentation
anonymous enum
anonymous enum
Public enumeration to choose method for computing shape derivatives.
Enumerator
Shape_derivs_by_chain_rule
Shape_derivs_by_direct_fd
Shape_derivs_by_fastest_method
     {
       Shape_derivs_by_chain_rule,
       Shape_derivs_by_direct_fd,
       Shape_derivs_by_fastest_method
     };
Constructor & Destructor Documentation
ElementWithMovingNodes() [1/2]
oomph::ElementWithMovingNodes::ElementWithMovingNodes () inline
Constructor.
       : Geometric_data_local_eqn(0),
         Bypass_fill_in_jacobian_from_geometric_data(false),
         Evaluate_dresidual_dnodal_coordinates_by_fd(false),
         Method_for_shape_derivs(Shape_derivs_by_direct_fd)
     // hierher: Anything other than the fd-based method is currently broken;
     // at least for refineable elements -- this all needs to be checked
     // VERY carefully again (see instructions in commit log). Until this
     // has all been fixed/re-validated, we've frozen the default assignment
     // (by breaking the functions that change the setting). Ultimately,
     // we should use:
     // Method_for_shape_derivs(Shape_derivs_by_fastest_method)
     {
     }
ElementWithMovingNodes() [2/2]
oomph::ElementWithMovingNodes::ElementWithMovingNodes (const ElementWithMovingNodes &) delete
Broken copy constructor.
~ElementWithMovingNodes()
virtual oomph::ElementWithMovingNodes::~ElementWithMovingNodes () inline virtual
Virtual destructor (clean up and allocated memory)
     {
       if (Geometric_data_local_eqn)
       {
         delete[] Geometric_data_local_eqn[0];
         delete[] Geometric_data_local_eqn;
       }
     }
References Geometric_data_local_eqn.
Member Function Documentation
are_dresidual_dnodal_coordinates_always_evaluated_by_fd()
bool oomph::ElementWithMovingNodes::are_dresidual_dnodal_coordinates_always_evaluated_by_fd () const inline
Return whether shape derivatives are evaluated by fd.
     {
       return Evaluate_dresidual_dnodal_coordinates_by_fd;
     }
References Evaluate_dresidual_dnodal_coordinates_by_fd.
assemble_set_of_all_geometric_data()
void oomph::ElementWithMovingNodes::assemble_set_of_all_geometric_data (std::set< Data * > & unique_geom_data_pt)
Return a set of all geometric data associated with the element.
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////// Return a set of all geometric data associated with the element's node update function
   {
     // First clear the set (just in case)
     unique_geom_data_pt.clear();
     // Get number of nodes
     const unsigned n_node = this->nnode();
     // Loop over all nodes
     for (unsigned n = 0; n < n_node; n++)
     {
       // Cache pointer to the Node
       Node* const nod_pt = this->node_pt(n);
       // Is the node hanging
       const bool node_is_hanging = nod_pt->is_hanging();
       // Default number of master nodes
       unsigned nmaster = 1;
       // Default: Node isn't hanging so it's its own master node
       Node* master_node_pt = nod_pt;
       // Cache the hanging point
       HangInfo* hang_info_pt = 0;
       // Find the number of master nodes if the node is hanging
       if (node_is_hanging)
       {
         hang_info_pt = nod_pt->hanging_pt();
         nmaster = hang_info_pt->nmaster();
       }
       // Loop over all master nodes
       for (unsigned imaster = 0; imaster < nmaster; imaster++)
       {
         // Get the master node
         if (node_is_hanging)
         {
           master_node_pt = hang_info_pt->master_node_pt(imaster);
         }
         // Find the number of data
         const unsigned n_geom_data = master_node_pt->ngeom_data();
         // If there are geometric data add them to the set
         if (n_geom_data > 0)
         {
           // Get vector of geometric data involved in the geometric
           // change of this node
           Data** node_geom_data_pt = master_node_pt->all_geom_data_pt();
           for (unsigned i = 0; i < n_geom_data; i++)
           {
             unique_geom_data_pt.insert(node_geom_data_pt[i]);
           }
         }
         // Find the number of geometric objects
         unsigned n_geom_obj = master_node_pt->ngeom_object();
         // If there are geometric objects, add them to the set
         if (n_geom_obj > 0)
         {
           // Get vector of geometric objects involved in the default
           // update function for this (master) node.
           // Vector is constructed by copy operation.
           GeomObject** geom_object_pt = master_node_pt->all_geom_object_pt();
           // Loop over the geometric objects
           for (unsigned i = 0; i < n_geom_obj; i++)
           {
             // Get the next geometric object
             GeomObject* geom_obj_pt = geom_object_pt[i];
             // Number of items of geometric data that the geometric
             // object depends on
             unsigned n_geom_data = geom_obj_pt->ngeom_data();
             // Loop over geometric data and add to set (use set to ensure
             // that each one is only counted once)
             for (unsigned idata = 0; idata < n_geom_data; idata++)
             {
               unique_geom_data_pt.insert(geom_obj_pt->geom_data_pt(idata));
             }
           }
         } // End of add geom object loop
       }
     }
   }
References oomph::Node::all_geom_data_pt(), oomph::Node::all_geom_object_pt(), oomph::GeomObject::geom_data_pt(), oomph::Node::hanging_pt(), i, oomph::Node::is_hanging(), oomph::HangInfo::master_node_pt(), n, oomph::GeomObject::ngeom_data(), oomph::Node::ngeom_data(), oomph::Node::ngeom_object(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
Referenced by complete_setup_of_dependencies(), oomph::FixedVolumeSpineLineMarangoniFluidInterfaceElement< ELEMENT >::make_bounding_element(), and oomph::SpineUpdateFluidInterfaceElement< EQUATION_CLASS, DERIVATIVE_CLASS, ELEMENT >::make_bounding_element().
assign_all_generic_local_eqn_numbers()
void oomph::ElementWithMovingNodes::assign_all_generic_local_eqn_numbers (const bool & store_local_dof_pt) protected virtual
Assign local equation numbers for the geometric Data in the element If the boolean argument is true then the degrees of freedom are stored in Dof_pt
Assign local equation numbers for the geometric data associated with the element.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >, oomph::ElementWithSpecificMovingNodes< ELEMENT, SpineNode >, oomph::ElementWithSpecificMovingNodes< ELEMENT, PerturbedSpineNode >, oomph::ElementWithSpecificMovingNodes< ELEMENT, AlgebraicNode >, and oomph::ElementWithSpecificMovingNodes< ELEMENT, MacroElementNodeUpdateNode >.
   {
     // Get local number of dofs so far
     unsigned local_eqn_number = this->ndof();
     // Set the number of data
     const unsigned n_geom_data = ngeom_data();
     // Reset number of geometric dofs
     Ngeom_dof = 0;
     // If we have any geometric data
     if (n_geom_data > 0)
     {
       // Work out total number of values involved
       // Initialise from the first object
       unsigned n_total_values = Geom_data_pt[0]->nvalue();
       // Add the values from the other data
       for (unsigned i = 1; i < n_geom_data; i++)
       {
         n_total_values += Geom_data_pt[i]->nvalue();
       }
       // If allocated delete the old storage
       if (Geometric_data_local_eqn)
       {
         delete[] Geometric_data_local_eqn[0];
         delete[] Geometric_data_local_eqn;
       }
       // If there are no values, we are done, null out the storage and
       // return
       if (n_total_values == 0)
       {
         Geometric_data_local_eqn = 0;
         return;
       }
       // Resize the storage for the geometric data local equation numbers
       // Firstly allocate the row pointers
       Geometric_data_local_eqn = new int*[n_geom_data];
       // Now allocate storage for all the equation numbers
       Geometric_data_local_eqn[0] = new int[n_total_values];
       // Initially all local equations are unclassified
       for (unsigned i = 0; i < n_total_values; i++)
       {
         Geometric_data_local_eqn[0][i] = Data::Is_unclassified;
       }
       // Loop over the remaining rows and set their pointers
       for (unsigned i = 1; i < n_geom_data; ++i)
       {
         // Initially set the pointer to the i-th row to the pointer
         // to the i-1th row
         Geometric_data_local_eqn[i] = Geometric_data_local_eqn[i - 1];
         // Now increase the row pointer by the number of values
         // stored at the i-1th geometric data
         Geometric_data_local_eqn[i] += Geom_data_pt[i - 1]->nvalue();
       }
       // A local queue to store the global equation numbers
       std::deque<unsigned long> global_eqn_number_queue;
       // Loop over the node update data
       for (unsigned i = 0; i < n_geom_data; i++)
       {
         // Pointer to geometric Data
         Data* data_pt = Geom_data_pt[i];
         // Loop over values at this Data item
         unsigned n_value = data_pt->nvalue();
         for (unsigned j = 0; j < n_value; j++)
         {
           // Get global equation number
           long eqn_number = data_pt->eqn_number(j);
           // If equation number positive
           if (eqn_number >= 0)
           {
             // Add the global equation number to our queue
             global_eqn_number_queue.push_back(eqn_number);
             // Add pointer to the dof to the queue if required
             if (store_local_dof_pt)
             {
               GeneralisedElement::Dof_pt_deque.push_back(data_pt->value_pt(j));
             }
             // Add to local value
             Geometric_data_local_eqn[i][j] = local_eqn_number;
             local_eqn_number++;
             // Bump up number of geometric dofs
             Ngeom_dof++;
           }
           else
           {
             // Set the local scheme to be pinned
             Geometric_data_local_eqn[i][j] = Data::Is_pinned;
           }
         }
       }
       // Now add our global equations numbers to the internal element storage
       this->add_global_eqn_numbers(global_eqn_number_queue,
                                    GeneralisedElement::Dof_pt_deque);
       // Clear the memory used in the deque
       if (store_local_dof_pt)
       {
         std::deque<double*>().swap(GeneralisedElement::Dof_pt_deque);
       }
     }
   }
References oomph::GeneralisedElement::add_global_eqn_numbers(), oomph::GeneralisedElement::Dof_pt_deque, oomph::Data::eqn_number(), oomph::GeneralisedElement::eqn_number(), Geom_data_pt, Geometric_data_local_eqn, i, oomph::Data::Is_pinned, oomph::Data::Is_unclassified, j, oomph::GeneralisedElement::local_eqn_number(), oomph::GeneralisedElement::ndof(), ngeom_data(), Ngeom_dof, oomph::Data::nvalue(), and oomph::Data::value_pt().
Referenced by oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::assign_all_generic_local_eqn_numbers().
complete_setup_of_dependencies()
void oomph::ElementWithMovingNodes::complete_setup_of_dependencies () protected virtual
Construct the vector of (unique) geometric data.
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::SpineElement< ELEMENT >, oomph::SpineElement< PointElement >, oomph::SpineElement< FaceGeometry< ELEMENT > >, oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >, oomph::ElementWithSpecificMovingNodes< ELEMENT, SpineNode >, oomph::ElementWithSpecificMovingNodes< ELEMENT, PerturbedSpineNode >, oomph::ElementWithSpecificMovingNodes< ELEMENT, AlgebraicNode >, and oomph::ElementWithSpecificMovingNodes< ELEMENT, MacroElementNodeUpdateNode >.
   {
     // This set will hold the pointers to all the unique (geometric) Data that
     // affects the shape of this element
     std::set<Data*> unique_geom_data_pt;
     // Assemble that data
     this->assemble_set_of_all_geometric_data(unique_geom_data_pt);
     // Resize storage for the pointers to the Data items that are
     // involved in the element's node update operation.
     Geom_data_pt.clear();
     // Loop over all the unique remaining Data items involved in the
     // node update operations
     typedef std::set<Data*>::iterator IT;
     for (IT it = unique_geom_data_pt.begin(); it != unique_geom_data_pt.end();
          it++)
     {
       Geom_data_pt.push_back(*it);
     }
   }
References assemble_set_of_all_geometric_data(), and Geom_data_pt.
Referenced by oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::complete_setup_of_dependencies().
describe_local_dofs()
void oomph::ElementWithMovingNodes::describe_local_dofs (std::ostream & out, const std::string & current_string) const virtual
Function to describe the local dofs of the element. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
Function to describe the local dofs of the element[s]. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >, oomph::ElementWithSpecificMovingNodes< ELEMENT, SpineNode >, oomph::ElementWithSpecificMovingNodes< ELEMENT, PerturbedSpineNode >, oomph::ElementWithSpecificMovingNodes< ELEMENT, AlgebraicNode >, and oomph::ElementWithSpecificMovingNodes< ELEMENT, MacroElementNodeUpdateNode >.
   {
     // Call the standard finite element classification.
     FiniteElement::describe_local_dofs(out, current_string);
     // Set the number of data
     const unsigned n_geom_data = ngeom_data();
     // Loop over the node update data
     for (unsigned i = 0; i < n_geom_data; i++)
     {
       // Pointer to geometric Data
       Data* data_pt = Geom_data_pt[i];
       std::stringstream conversion;
       conversion << " of Geometric Data " << i << current_string;
       std::string in(conversion.str());
       data_pt->describe_dofs(out, in);
     }
   }
References oomph::Data::describe_dofs(), oomph::FiniteElement::describe_local_dofs(), Geom_data_pt, i, ngeom_data(), out(), and oomph::Global_string_for_annotation::string().
Referenced by oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::describe_local_dofs().
disable_always_evaluate_dresidual_dnodal_coordinates_by_fd()
void oomph::ElementWithMovingNodes::disable_always_evaluate_dresidual_dnodal_coordinates_by_fd () inline
Insist that shape derivatives are always evaluated using the overloaded version of this function that may have been implemented in a derived class. (The default behaviour will still be finite differences unless the function has actually been overloaded
     {
       Evaluate_dresidual_dnodal_coordinates_by_fd = false;
     }
References Evaluate_dresidual_dnodal_coordinates_by_fd.
Referenced by FSIRingProblem::FSIRingProblem().
disable_bypass_fill_in_jacobian_from_geometric_data()
void oomph::ElementWithMovingNodes::disable_bypass_fill_in_jacobian_from_geometric_data () inline
Do not bypass the call to fill_in_jacobian_from_geometric_data.
     {
       Bypass_fill_in_jacobian_from_geometric_data = false;
     }
References Bypass_fill_in_jacobian_from_geometric_data.
enable_always_evaluate_dresidual_dnodal_coordinates_by_fd()
void oomph::ElementWithMovingNodes::enable_always_evaluate_dresidual_dnodal_coordinates_by_fd () inline
Insist that shape derivatives are always evaluated by fd (using FiniteElement::get_dresidual_dnodal_coordinates())
     {
       Evaluate_dresidual_dnodal_coordinates_by_fd = true;
     }
References Evaluate_dresidual_dnodal_coordinates_by_fd.
Referenced by oomph::RefineableQElement< 3 >::build(), oomph::RefineableQElement< 1 >::build(), oomph::RefineableQElement< 2 >::build(), and FSIRingProblem::FSIRingProblem().
enable_bypass_fill_in_jacobian_from_geometric_data()
void oomph::ElementWithMovingNodes::enable_bypass_fill_in_jacobian_from_geometric_data () inline
Bypass the call to fill_in_jacobian_from_geometric_data.
     {
       Bypass_fill_in_jacobian_from_geometric_data = true;
     }
References Bypass_fill_in_jacobian_from_geometric_data.
Referenced by oomph::RefineableQElement< 3 >::build(), oomph::RefineableQElement< 1 >::build(), and oomph::RefineableQElement< 2 >::build().
evaluate_shape_derivs_by_chain_rule()
void oomph::ElementWithMovingNodes::evaluate_shape_derivs_by_chain_rule (const bool & i_know_what_i_am_doing = false) inline
Evaluate shape derivatives by chain rule. Currently disabled by default because it's broken; can re-enable use by setting optional boolean to true.
     {
       if (!i_know_what_i_am_doing)
       {
         std::ostringstream error_message;
         error_message
           << "Evaluation of shape derivatives by chain rule is currently \n"
           << "disabled because it's broken, at least for refineable \n"
           << "elements. This all needs to be checked again very carefully\n"
           << "following the instructions in the commit log\n"
           << "If you know what you're doing and want to force this "
              "methodology\n"
           << "call this function with the optional boolean set to true.\n";
         throw OomphLibError(
           error_message.str(),
           "ElementWithMovingNodes::evaluate_shape_derivs_by_chain_rule()",
           OOMPH_EXCEPTION_LOCATION);
       }
       Method_for_shape_derivs = Shape_derivs_by_chain_rule;
     }
References Method_for_shape_derivs, OOMPH_EXCEPTION_LOCATION, and Shape_derivs_by_chain_rule.
Referenced by FSIRingProblem::FSIRingProblem().
evaluate_shape_derivs_by_direct_fd()
void oomph::ElementWithMovingNodes::evaluate_shape_derivs_by_direct_fd () inline
Evaluate shape derivatives by direct finite differencing.
     {
       // hierher: Harmless; simply re-sets the current (and currently only
       // legal) default
       Method_for_shape_derivs = Shape_derivs_by_direct_fd;
     }
References Method_for_shape_derivs, and Shape_derivs_by_direct_fd.
Referenced by AirwayReopeningProblem< ELEMENT >::actions_before_newton_convergence_check(), ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_newton_convergence_check(), ThreeDimBethertonProblem< ELEMENT >::actions_before_newton_convergence_check(), and FSIRingProblem::FSIRingProblem().
evaluate_shape_derivs_by_fastest_method()
void oomph::ElementWithMovingNodes::evaluate_shape_derivs_by_fastest_method (const bool & i_know_what_i_am_doing = false) inline
Evaluate shape derivatives by (anticipated) fastest method. Currently disabled by default because it's broken; can re-enable use by setting optional boolean to true.
     {
       if (!i_know_what_i_am_doing)
       {
         std::ostringstream error_message;
         error_message
           << "Evaluation of shape derivatives by fastest method is currently \n"
           << "disabled because it's broken, at least for refineable \n"
           << "elements. This all needs to be checked again very carefully\n"
           << "following the instructions in the commit log\n"
           << "If you know what you're doing and want to force this "
              "methodology\n"
           << "call this function with the optional boolean set to true.\n";
         throw OomphLibError(
           error_message.str(),
           "ElementWithMovingNodes::evaluate_shape_derivs_by_fastest_method()",
           OOMPH_EXCEPTION_LOCATION);
       }
       Method_for_shape_derivs = Shape_derivs_by_fastest_method;
     }
References Method_for_shape_derivs, OOMPH_EXCEPTION_LOCATION, and Shape_derivs_by_fastest_method.
Referenced by FSIRingProblem::FSIRingProblem().
fill_in_jacobian_from_geometric_data() [1/2]
void oomph::ElementWithMovingNodes::fill_in_jacobian_from_geometric_data (DenseMatrix< double > & jacobian) inline protected
Calculate the contributions to the Jacobian matrix from the geometric data. This version computes the residuals vector before calculating the Jacobian terms
     {
       if (!Bypass_fill_in_jacobian_from_geometric_data)
       {
         // Allocate storage for the residuals
         const unsigned n_dof = ndof();
         Vector<double> residuals(n_dof);
         // Get the residuals for the entire element
         get_residuals(residuals);
         // Call the jacobian calculation
         fill_in_jacobian_from_geometric_data(residuals, jacobian);
       }
     }
References Bypass_fill_in_jacobian_from_geometric_data, fill_in_jacobian_from_geometric_data(), oomph::GeneralisedElement::get_residuals(), and oomph::GeneralisedElement::ndof().
fill_in_jacobian_from_geometric_data() [2/2]
void oomph::ElementWithMovingNodes::fill_in_jacobian_from_geometric_data (Vector< double > & residuals, DenseMatrix< double > & jacobian) protected
Calculate the contributions to the Jacobian matrix from the geometric data. This version assumes that the (full) residuals vector has already been calculated and is passed in as the first argument – needed in case the derivatives are computed by FD.
Calculate the node-update–related entries in the Jacobian. The vector passed in residuals has to contain the nonlinear residuals, evaluated for the current values of the unknowns, in case FDing is used to computed the derivatives.
   {
     if (!Bypass_fill_in_jacobian_from_geometric_data)
     {
       // Get number of Data items involved in node update operations
       const unsigned n_geometric_data = ngeom_data();
       // If there is nothing to be done, then leave
       if (n_geometric_data == 0) return;
       // Number of dofs
       const unsigned n_dof = this->ndof();
       // Number of nodes
       unsigned n_nod = this->nnode();
       // If there are no dofs, return
       if (n_nod == 0) return;
       // Get nodal dimension from first node
       const unsigned dim_nod = node_pt(0)->ndim();
       // Number of shape controlling nodes for nonrefineable elements
       unsigned n_shape_controlling_node = nnode();
       // Are we dealing with a refineable element?
       RefineableElement* ref_el_pt = dynamic_cast<RefineableElement*>(this);
       if (ref_el_pt != 0)
       {
         // Adjust number of shape controlling nodes
         n_shape_controlling_node = ref_el_pt->nshape_controlling_nodes();
       }
       // How are we going to evaluate the shape derivs?
       unsigned method = 0;
       if (Method_for_shape_derivs == Shape_derivs_by_direct_fd)
       {
         method = 0;
       }
       else if (Method_for_shape_derivs == Shape_derivs_by_chain_rule)
       {
         method = 1;
       }
       else if (Method_for_shape_derivs == Shape_derivs_by_fastest_method)
       {
         // Direct FD-ing of residuals w.r.t. geometric dofs is likely to be
         // faster if there are fewer geometric dofs than total nodal coordinates
         // (nodes x dim) in element:
         if (Ngeom_dof < (n_shape_controlling_node * dim_nod))
         {
           method = 0;
         }
         else
         {
           method = 1;
         }
       }
       // Choose method
       //===============
       switch (method)
       {
           // Direct FD:
           //-----------
         case 0:
         {
           // Create newres vector
           Vector<double> newres(n_dof);
           // Use the default finite difference step
           const double fd_step = GeneralisedElement::Default_fd_jacobian_step;
           // Integer storage for the local unknown
           int local_unknown = 0;
           // Loop over the Data items that affect the node update operations
           for (unsigned i = 0; i < n_geometric_data; i++)
           {
             // Loop over values
             unsigned n_value = Geom_data_pt[i]->nvalue();
             for (unsigned j = 0; j < n_value; j++)
             {
               local_unknown = geometric_data_local_eqn(i, j);
               // If the value is free
               if (local_unknown >= 0)
               {
                 // Get a pointer to the geometric data value
                 double* value_pt = Geom_data_pt[i]->value_pt(j);
                 // Save the old value
                 double old_var = *value_pt;
                 // Increment the variable
                 *value_pt += fd_step;
                 // Update the whole element (Bit inefficient)
                 this->node_update();
                 // Calculate the new residuals
                 this->get_residuals(newres);
                 // Now do finite differences
                 for (unsigned m = 0; m < n_dof; m++)
                 {
                   // Stick the entry into the Jacobian matrix
                   jacobian(m, local_unknown) =
                     (newres[m] - residuals[m]) / fd_step;
                 }
                 // Reset the variable
                 *value_pt = old_var;
                 // We're relying on the total node update in the next loop
               }
             }
           }
           // Node update the element one final time to get things back to
           // the original state
           this->node_update();
         }
         break;
         // Chain rule
         //-----------
         case 1:
         {
           // Get derivatives of residuals w.r.t. all nodal coordinates
           RankThreeTensor<double> dresidual_dnodal_coordinates(
             n_dof, dim_nod, n_shape_controlling_node, 0.0);
           // Use FD-version in base class?
           if (Evaluate_dresidual_dnodal_coordinates_by_fd)
           {
             if (ref_el_pt != 0)
             {
               ref_el_pt->RefineableElement::get_dresidual_dnodal_coordinates(
                 dresidual_dnodal_coordinates);
             }
             else
             {
               FiniteElement::get_dresidual_dnodal_coordinates(
                 dresidual_dnodal_coordinates);
             }
           }
           // Otherwise use the overloaded analytical version in derived
           // class (if it exists -- if it doesn't this just drops through
           // to the default implementation in FiniteElement).
           else
           {
             this->get_dresidual_dnodal_coordinates(
               dresidual_dnodal_coordinates);
           }
           // Get derivatives of nodal coordinates w.r.t. geometric dofs
           RankThreeTensor<double> dnodal_coordinates_dgeom_dofs(
             n_dof, dim_nod, n_shape_controlling_node, 0.0);
           get_dnodal_coordinates_dgeom_dofs(dnodal_coordinates_dgeom_dofs);
           // Assemble Jacobian via chain rule
           for (unsigned l = 0; l < n_dof; l++)
           {
             // Loop over the Data items that affect the node update operations
             for (unsigned i_data = 0; i_data < n_geometric_data; i_data++)
             {
               // Loop over values
               unsigned n_value = Geom_data_pt[i_data]->nvalue();
               for (unsigned j_val = 0; j_val < n_value; j_val++)
               {
                 int k = geometric_data_local_eqn(i_data, j_val);
                 // If the value is free
                 if (k >= 0)
                 {
                   jacobian(l, k) = 0.0;
                   for (unsigned i = 0; i < dim_nod; i++)
                   {
                     for (unsigned j = 0; j < n_shape_controlling_node; j++)
                     {
                       jacobian(l, k) += dresidual_dnodal_coordinates(l, i, j) *
                                         dnodal_coordinates_dgeom_dofs(k, i, j);
                     }
                   }
                 }
               }
             }
           }
         }
         break;
         default:
           std::ostringstream error_message;
           error_message << "Never get here: method " << method;
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
       }
     }
   }
References Bypass_fill_in_jacobian_from_geometric_data, oomph::GeneralisedElement::Default_fd_jacobian_step, Evaluate_dresidual_dnodal_coordinates_by_fd, Geom_data_pt, geometric_data_local_eqn(), get_dnodal_coordinates_dgeom_dofs(), oomph::FiniteElement::get_dresidual_dnodal_coordinates(), oomph::GeneralisedElement::get_residuals(), i, j, k, m, Method_for_shape_derivs, oomph::Node::ndim(), oomph::GeneralisedElement::ndof(), ngeom_data(), Ngeom_dof, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::node_update(), oomph::RefineableElement::nshape_controlling_nodes(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, Shape_derivs_by_chain_rule, Shape_derivs_by_direct_fd, and Shape_derivs_by_fastest_method.
Referenced by oomph::PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::SpineLineVolumeConstraintBoundingElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::SpineAxisymmetricVolumeConstraintBoundingElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::SpineSurfaceVolumeConstraintBoundingElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::SpineUpdateFluidInterfaceElement< EQUATION_CLASS, DERIVATIVE_CLASS, ELEMENT >::fill_in_contribution_to_jacobian(), oomph::SpinePointFluidInterfaceBoundingElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::SpineLineFluidInterfaceBoundingElement< ELEMENT >::fill_in_contribution_to_jacobian(), fill_in_jacobian_from_geometric_data(), oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::get_jacobian(), and oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::get_jacobian_and_mass_matrix().
geometric_data_local_eqn()
int oomph::ElementWithMovingNodes::geometric_data_local_eqn (const unsigned & n, const unsigned & i) inline
Return the local equation number corresponding to the i-th value at the n-th geometric data object.
     {
 #ifdef RANGE_CHECKING
       unsigned n_data = Geom_data_pt.size();
       if (n >= n_data)
       {
         std::ostringstream error_message;
         error_message << "Range Error:  Data number " << n
                       << " is not in the range (0," << n_data - 1 << ")";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       else
       {
         unsigned n_value = Geom_data_pt[n]->nvalue();
         if (i >= n_value)
         {
           std::ostringstream error_message;
           error_message << "Range Error: value " << i << " at data " << n
                         << " is not in the range (0," << n_value - 1 << ")";
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
       }
 #endif
 #ifdef PARANOID
       // Check that the equations have been allocated
       if (Geometric_data_local_eqn == 0)
       {
         throw OomphLibError(
           "Geometric data local equation numbers have not been allocated",
           OOMPH_CURRENT_FUNCTION,
           OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return Geometric_data_local_eqn[n][i];
     }
References Geom_data_pt, Geometric_data_local_eqn, i, n, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by fill_in_jacobian_from_geometric_data(), get_dnodal_coordinates_dgeom_dofs(), oomph::SpineElement< ELEMENT >::spine_local_eqn(), and oomph::PerturbedSpineElement< ELEMENT >::spine_local_eqn().
get_dnodal_coordinates_dgeom_dofs()
void oomph::ElementWithMovingNodes::get_dnodal_coordinates_dgeom_dofs (RankThreeTensor< double > & dnodal_coordinates_dgeom_dofs) protected virtual
Compute derivatives of the nodal coordinates w.r.t. to the geometric dofs. Default implementation by FD can be overwritten for specific elements. dnodal_coordinates_dgeom_dofs(l,i,j) = dX_{ij} / d s_l
   {
     // Get number of Data items involved in node update operations
     const unsigned n_geometric_data = ngeom_data();
     // If there is nothing to be done, then leave
     if (n_geometric_data == 0)
     {
       return;
     }
     // Number of nodes
     const unsigned n_nod = nnode();
     // If the element has no nodes (why??!!) return straightaway
     if (n_nod == 0) return;
     // Get dimension from first node
     unsigned dim_nod = node_pt(0)->ndim();
     // Number of shape controlling nodes for nonrefineable elements
     unsigned n_shape_controlling_node = n_nod;
     // Are we dealing with a refineable element?
     RefineableElement* ref_el_pt = dynamic_cast<RefineableElement*>(this);
     if (ref_el_pt != 0)
     {
       // Adjust number of shape controlling nodes
       n_shape_controlling_node = ref_el_pt->nshape_controlling_nodes();
     }
     // Current and advanced nodal positions
     DenseMatrix<double> pos(dim_nod, n_shape_controlling_node);
     // Shape controlling nodes
     std::map<Node*, unsigned> local_shape_controlling_node_lookup;
     // Refineable element:
     if (ref_el_pt != 0)
     {
       local_shape_controlling_node_lookup =
         ref_el_pt->shape_controlling_node_lookup();
     }
     // Non-refineable element: the nodes themselves
     else
     {
       unsigned count = 0;
       for (unsigned j = 0; j < n_nod; j++)
       {
         local_shape_controlling_node_lookup[node_pt(j)] = count;
         count++;
       }
     }
     // Loop over all shape-controlling nodes to backup their original position
     for (std::map<Node*, unsigned>::iterator it =
            local_shape_controlling_node_lookup.begin();
          it != local_shape_controlling_node_lookup.end();
          it++)
     {
       // Get node
       Node* nod_pt = it->first;
       // Get its number
       unsigned node_number = it->second;
       // Backup
       for (unsigned i = 0; i < dim_nod; i++)
       {
         pos(i, node_number) = nod_pt->position(i);
       }
     }
     // Integer storage for the local unknown
     int local_unknown = 0;
     // Use the default finite difference step
     const double fd_step = GeneralisedElement::Default_fd_jacobian_step;
     // Loop over the Data items that affect the node update operations
     for (unsigned i = 0; i < n_geometric_data; i++)
     {
       // Loop over values
       unsigned n_value = Geom_data_pt[i]->nvalue();
       for (unsigned j = 0; j < n_value; j++)
       {
         local_unknown = geometric_data_local_eqn(i, j);
         // If the value is free
         if (local_unknown >= 0)
         {
           // Get a pointer to the geometric data value
           double* value_pt = Geom_data_pt[i]->value_pt(j);
           // Save the old value
           double old_var = *value_pt;
           // Increment the variable
           *value_pt += fd_step;
           // Update the whole element
           this->node_update();
           // Loop over all shape-controlling nodes
           for (std::map<Node*, unsigned>::iterator it =
                  local_shape_controlling_node_lookup.begin();
                it != local_shape_controlling_node_lookup.end();
                it++)
           {
             // Get node
             Node* nod_pt = it->first;
             // Get its number
             unsigned node_number = it->second;
             // Get advanced position and FD
             for (unsigned ii = 0; ii < dim_nod; ii++)
             {
               dnodal_coordinates_dgeom_dofs(local_unknown, ii, node_number) =
                 (nod_pt->position(ii) - pos(ii, node_number)) / fd_step;
             }
           }
           // Reset the variable
           *value_pt = old_var;
           // We're relying on the total node update in the next loop
         }
       }
     }
     // Node update the element one final time to get things back to
     // the original state
     this->node_update();
   }
References oomph::GeneralisedElement::Default_fd_jacobian_step, Geom_data_pt, geometric_data_local_eqn(), i, j, oomph::Node::ndim(), ngeom_data(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::node_update(), oomph::RefineableElement::nshape_controlling_nodes(), oomph::Node::position(), and oomph::RefineableElement::shape_controlling_node_lookup().
Referenced by fill_in_jacobian_from_geometric_data().
identify_geometric_data()
void oomph::ElementWithMovingNodes::identify_geometric_data (std::set< Data * > & geometric_data_pt) inline virtual
Specify Data that affects the geometry of the element by adding the element's geometric Data to the set that's passed in. (This functionality is required in FSI problems; set is used to avoid double counting).
Reimplemented from oomph::FiniteElement.
     {
       // Loop over the node update data and add to the set
       const unsigned n_geom_data = Geom_data_pt.size();
       for (unsigned n = 0; n < n_geom_data; n++)
       {
         geometric_data_pt.insert(Geom_data_pt[n]);
       }
     }
References Geom_data_pt, and n.
is_fill_in_jacobian_from_geometric_data_bypassed()
bool oomph::ElementWithMovingNodes::is_fill_in_jacobian_from_geometric_data_bypassed () const inline
Test whether the call to fill_in_jacobian_from_geometric_data is bypassed
     {
       return Bypass_fill_in_jacobian_from_geometric_data;
     }
References Bypass_fill_in_jacobian_from_geometric_data.
method_for_shape_derivs()
int& oomph::ElementWithMovingNodes::method_for_shape_derivs () inline
Access to method (enumerated flag) for determination of shape derivs.
     {
       return Method_for_shape_derivs;
     }
References Method_for_shape_derivs.
Referenced by oomph::RefineableQElement< 3 >::build(), oomph::RefineableQElement< 1 >::build(), and oomph::RefineableQElement< 2 >::build().
ngeom_data()
unsigned oomph::ElementWithMovingNodes::ngeom_data () const inline virtual
Return the number of geometric data upon which the shape of the element depends
Reimplemented from oomph::GeomObject.
     {
       return Geom_data_pt.size();
     }
References Geom_data_pt.
Referenced by assign_all_generic_local_eqn_numbers(), describe_local_dofs(), fill_in_jacobian_from_geometric_data(), get_dnodal_coordinates_dgeom_dofs(), oomph::SpineElement< ELEMENT >::spine_local_eqn(), and oomph::PerturbedSpineElement< ELEMENT >::spine_local_eqn().
ngeom_dof()
unsigned oomph::ElementWithMovingNodes::ngeom_dof () const inline
Number of geometric dofs.
     {
       return Ngeom_dof;
     }
References Ngeom_dof.
operator=()
void oomph::ElementWithMovingNodes::operator= (const ElementWithMovingNodes &) delete
Broken assignment operator.
Member Data Documentation
Bypass_fill_in_jacobian_from_geometric_data
bool oomph::ElementWithMovingNodes::Bypass_fill_in_jacobian_from_geometric_data private
Set flag to true to bypass calculation of Jacobain entries resulting from geometric data.
Referenced by disable_bypass_fill_in_jacobian_from_geometric_data(), enable_bypass_fill_in_jacobian_from_geometric_data(), fill_in_jacobian_from_geometric_data(), and is_fill_in_jacobian_from_geometric_data_bypassed().
Evaluate_dresidual_dnodal_coordinates_by_fd
bool oomph::ElementWithMovingNodes::Evaluate_dresidual_dnodal_coordinates_by_fd private
Boolean to decide if shape derivatives are to be evaluated by fd (using FiniteElement::get_dresidual_dnodal_coordinates()) or analytically, using the overloaded version of this function in this class.
Referenced by are_dresidual_dnodal_coordinates_always_evaluated_by_fd(), disable_always_evaluate_dresidual_dnodal_coordinates_by_fd(), enable_always_evaluate_dresidual_dnodal_coordinates_by_fd(), and fill_in_jacobian_from_geometric_data().
Geom_data_pt
Vector<Data*> oomph::ElementWithMovingNodes::Geom_data_pt protected
Vector that stores pointers to all Data that affect the node update operations, i.e. the variables that can affect the position of the node.
Referenced by assign_all_generic_local_eqn_numbers(), complete_setup_of_dependencies(), describe_local_dofs(), fill_in_jacobian_from_geometric_data(), geometric_data_local_eqn(), get_dnodal_coordinates_dgeom_dofs(), identify_geometric_data(), and ngeom_data().
Geometric_data_local_eqn
int** oomph::ElementWithMovingNodes::Geometric_data_local_eqn private
Array to hold local eqn number information for the geometric Data variables
Referenced by assign_all_generic_local_eqn_numbers(), geometric_data_local_eqn(), and ~ElementWithMovingNodes().
Method_for_shape_derivs
int oomph::ElementWithMovingNodes::Method_for_shape_derivs private
Choose method for evaluation of shape derivatives (this takes one of the values in the enumeration)
Referenced by evaluate_shape_derivs_by_chain_rule(), evaluate_shape_derivs_by_direct_fd(), evaluate_shape_derivs_by_fastest_method(), fill_in_jacobian_from_geometric_data(), and method_for_shape_derivs().
Ngeom_dof
unsigned oomph::ElementWithMovingNodes::Ngeom_dof private
Number of geometric dofs (computed on the fly when equation numbers are set up)
Referenced by assign_all_generic_local_eqn_numbers(), fill_in_jacobian_from_geometric_data(), and ngeom_dof().
The documentation for this class was generated from the following files:
element_with_moving_nodes.h
element_with_moving_nodes.cc