MercuryDPM: SYCL Namespace Reference
SYCL Namespace Reference
Functions
template<typename T >
T abs (T x)
template<>
Eigen::half abs (Eigen::half x)
template<>
float abs (float x)
template<>
double abs (double x)
template<typename T >
T square (T x)
template<typename T >
T cube (T x)
template<typename T >
T inverse (T x)
template<typename T >
T cwiseMax (T x, T y)
template<>
Eigen::half cwiseMax (Eigen::half x, Eigen::half y)
template<typename T >
T cwiseMin (T x, T y)
template<>
Eigen::half cwiseMin (Eigen::half x, Eigen::half y)
template<typename T >
T sqrt (T x)
template<>
Eigen::half sqrt (Eigen::half x)
template<typename T >
T rsqrt (T x)
template<>
Eigen::half rsqrt (Eigen::half x)
template<typename T >
T tanh (T x)
template<>
Eigen::half tanh (Eigen::half x)
template<typename T >
T exp (T x)
template<>
Eigen::half exp (Eigen::half x)
template<typename T >
T expm1 (T x)
template<>
Eigen::half expm1 (Eigen::half x)
template<typename T >
T log (T x)
template<>
Eigen::half log (Eigen::half x)
template<typename T >
T ceil (T x)
template<>
Eigen::half ceil (Eigen::half x)
template<typename T >
T floor (T x)
template<>
Eigen::half floor (Eigen::half x)
template<typename T >
T round (T x)
template<>
Eigen::half round (Eigen::half x)
template<typename T >
T log1p (T x)
template<>
Eigen::half log1p (Eigen::half x)
template<typename T >
T sign (T x)
template<>
Eigen::half sign (Eigen::half x)
template<typename T >
T isnan (T x)
template<>
Eigen::half isnan (Eigen::half x)
template<typename T >
T isfinite (T x)
template<>
Eigen::half isfinite (Eigen::half x)
template<typename T >
T isinf (T x)
template<>
Eigen::half isinf (Eigen::half x)
Function Documentation
abs() [1/4]
template<> double SYCL::abs (double x)
                      {
   return cl::sycl::fabs(x);
 }
References boost::multiprecision::fabs(), and plotDoE::x.
abs() [2/4]
template<> Eigen::half SYCL::abs (Eigen::half x)
{
   return Eigen::half(cl::sycl::fabs(static_cast<cl::sycl::half>(x)));
 }
References boost::multiprecision::fabs(), and plotDoE::x.
abs() [3/4]
template<> float SYCL::abs (float x)
                    {
   return cl::sycl::fabs(x);
 }
References boost::multiprecision::fabs(), and plotDoE::x.
abs() [4/4]
template<typename T > T SYCL::abs (T x)
            {
   return cl::sycl::abs(x);
 }
References abs(), and plotDoE::x.
ceil() [1/2]
template<> Eigen::half SYCL::ceil (Eigen::half x)
{
   return Eigen::half(cl::sycl::ceil(static_cast<cl::sycl::half>(x)));
 }
References plotDoE::x.
Referenced by ceil(), and test_unary_builtins_for_assignement().
ceil() [2/2]
template<typename T > T SYCL::ceil (T x)
             {
   return cl::sycl::ceil(x);
 }
References ceil(), and plotDoE::x.
cube()
template<typename T > T SYCL::cube (T x)
             {
   return x * x * x;
 }
References plotDoE::x.
Referenced by array_complex(), array_real(), and test_unary_builtins_for_assignement().
cwiseMax() [1/2]
template<> Eigen::half SYCL::cwiseMax (Eigen::half x, Eigen::half y)
{
   return Eigen::half(cl::sycl::max(static_cast<cl::sycl::half>(x), static_cast<cl::sycl::half>(y)));
 }
References max, plotDoE::x, and y.
cwiseMax() [2/2]
template<typename T > T SYCL::cwiseMax (T x, T y)
                      {
   return cl::sycl::max(x, y);
 }
References max, plotDoE::x, and y.
Referenced by cwise_min_max().
cwiseMin() [1/2]
template<> Eigen::half SYCL::cwiseMin (Eigen::half x, Eigen::half y)
{
   return Eigen::half(cl::sycl::min(static_cast<cl::sycl::half>(x), static_cast<cl::sycl::half>(y)));
 }
References min, plotDoE::x, and y.
cwiseMin() [2/2]
template<typename T > T SYCL::cwiseMin (T x, T y)
                      {
   return cl::sycl::min(x, y);
 }
References min, plotDoE::x, and y.
Referenced by cwise_min_max().
exp() [1/2]
template<> Eigen::half SYCL::exp (Eigen::half x)
{
   return Eigen::half(cl::sycl::exp(static_cast<cl::sycl::half>(x)));
 }
References plotDoE::x.
Referenced by exp(), and test_unary_builtins_for_assignement().
exp() [2/2]
template<typename T > T SYCL::exp (T x)
            {
   return cl::sycl::exp(x);
 }
References exp(), and plotDoE::x.
expm1() [1/2]
template<> Eigen::half SYCL::expm1 (Eigen::half x)
{
   return Eigen::half(cl::sycl::expm1(static_cast<cl::sycl::half>(x)));
 }
References plotDoE::x.
Referenced by expm1(), and test_unary_builtins_for_assignement().
expm1() [2/2]
template<typename T > T SYCL::expm1 (T x)
              {
   return cl::sycl::expm1(x);
 }
References expm1(), and plotDoE::x.
floor() [1/2]
template<> Eigen::half SYCL::floor (Eigen::half x)
{
   return Eigen::half(cl::sycl::floor(static_cast<cl::sycl::half>(x)));
 }
References plotDoE::x.
Referenced by floor(), and test_unary_builtins_for_assignement().
floor() [2/2]
template<typename T > T SYCL::floor (T x)
              {
   return cl::sycl::floor(x);
 }
References floor(), and plotDoE::x.
inverse()
template<typename T > T SYCL::inverse (T x)
                {
   return T(1) / x;
 }
References plotDoE::x.
isfinite() [1/2]
template<> Eigen::half SYCL::isfinite (Eigen::half x)
{
   return Eigen::half(cl::sycl::isfinite(static_cast<cl::sycl::half>(x)));
 }
References isfinite, and plotDoE::x.
isfinite() [2/2]
template<typename T > T SYCL::isfinite (T x)
                 {
   return cl::sycl::isfinite(x);
 }
References isfinite, and plotDoE::x.
isinf() [1/2]
template<> Eigen::half SYCL::isinf (Eigen::half x)
{
   return Eigen::half(cl::sycl::isinf(static_cast<cl::sycl::half>(x)));
 }
References isinf, and plotDoE::x.
isinf() [2/2]
template<typename T > T SYCL::isinf (T x)
              {
   return cl::sycl::isinf(x);
 }
References isinf, and plotDoE::x.
isnan() [1/2]
template<> Eigen::half SYCL::isnan (Eigen::half x)
{
   return Eigen::half(cl::sycl::isnan(static_cast<cl::sycl::half>(x)));
 }
References isnan, and plotDoE::x.
isnan() [2/2]
template<typename T > T SYCL::isnan (T x)
              {
   return cl::sycl::isnan(x);
 }
References isnan, and plotDoE::x.
log() [1/2]
template<> Eigen::half SYCL::log (Eigen::half x)
{
   return Eigen::half(cl::sycl::log(static_cast<cl::sycl::half>(x)));
 }
References plotDoE::x.
Referenced by log(), and test_unary_builtins_for_assignement().
log() [2/2]
template<typename T > T SYCL::log (T x)
            {
   return cl::sycl::log(x);
 }
References log(), and plotDoE::x.
log1p() [1/2]
template<> Eigen::half SYCL::log1p (Eigen::half x)
{
   return Eigen::half(cl::sycl::log1p(static_cast<cl::sycl::half>(x)));
 }
References plotDoE::x.
Referenced by log1p(), and test_unary_builtins_for_assignement().
log1p() [2/2]
template<typename T > T SYCL::log1p (T x)
              {
   return cl::sycl::log1p(x);
 }
References log1p(), and plotDoE::x.
round() [1/2]
template<> Eigen::half SYCL::round (Eigen::half x)
{
   return Eigen::half(cl::sycl::round(static_cast<cl::sycl::half>(x)));
 }
References plotDoE::x.
Referenced by round(), and test_unary_builtins_for_assignement().
round() [2/2]
template<typename T > T SYCL::round (T x)
              {
   return cl::sycl::round(x);
 }
References round(), and plotDoE::x.
rsqrt() [1/2]
template<> Eigen::half SYCL::rsqrt (Eigen::half x)
{
   return Eigen::half(cl::sycl::rsqrt(static_cast<cl::sycl::half>(x)));
 }
References plotDoE::x.
Referenced by rsqrt(), and test_unary_builtins_for_assignement().
rsqrt() [2/2]
template<typename T > T SYCL::rsqrt (T x)
              {
   return cl::sycl::rsqrt(x);
 }
References rsqrt(), and plotDoE::x.
sign() [1/2]
template<> Eigen::half SYCL::sign (Eigen::half x)
{
   return Eigen::half(cl::sycl::sign(static_cast<cl::sycl::half>(x)));
 }
References plotDoE::x.
Referenced by sign(), and test_unary_builtins_for_assignement().
sign() [2/2]
template<typename T > T SYCL::sign (T x)
             {
   return cl::sycl::sign(x);
 }
References sign(), and plotDoE::x.
Referenced by array_complex(), array_real(), BinaryToFloat(), cholesky(), cholesky_cplx(), cod(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::contact_line_vectors(), oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::TanhProfileConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::DenseLU::factorise(), Eigen::half_impl::float_to_half_rtne(), oomph::FSIWallElement::fluid_load_vector(), PolarNSProblem< ELEMENT >::get_Jacobian_sign(), TwoDDGProblem< ELEMENT >::limit(), oomph::FSIHermiteBeamElement::load_vector(), oomph::FSIDiagHermiteShellElement::load_vector(), oomph::DenseComplexMatrix::ludecompose(), oomph::CRComplexMatrix::ludecompose(), oomph::CCComplexMatrix::ludecompose(), main(), oomph::MinModLimiter::minmod(), oomph::AlgebraicFishMesh< ELEMENT >::node_update_in_body(), oomph::AlgebraicFishMesh< ELEMENT >::node_update_in_fin(), Eigen::internal::scalar_sign_op< Scalar >::operator()(), packetmath(), packetmath_complex(), packetmath_real(), qr_invertible(), Eigen::internal::psign_impl< Packet, std::enable_if_t< NumTraits< typename unpacket_traits< Packet >::type >::IsComplex &&unpacket_traits< Packet >::vectorizable > >::run(), Eigen::internal::psign_impl< Packet, EnableIf >::run(), oomph::BrickMeshBase::setup_boundary_element_info(), oomph::QuadMeshBase::setup_boundary_element_info(), oomph::HermiteQuadMesh< ELEMENT >::setup_boundary_element_info(), test_cwise_real(), Eigen::internal::ldlt_inplace< Lower >::unblocked(), Eigen::internal::ldlt_inplace< Upper >::unblocked(), PeriodicBoundaryHandler::updateParticles(), oomph::PowerLawBerEngRegConstitutiveEquation< DIM >::viscosity(), oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >::viscosity(), oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::viscosity(), oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::viscosity(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity(), oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity(), and oomph::TanhProfileConstitutiveEquation< DIM >::viscosity().
sqrt() [1/2]
template<> Eigen::half SYCL::sqrt (Eigen::half x)
{
   return Eigen::half(cl::sycl::sqrt(static_cast<cl::sycl::half>(x)));
 }
References sqrt(), and plotDoE::x.
sqrt() [2/2]
template<typename T > T SYCL::sqrt (T x)
             {
   return cl::sycl::sqrt(x);
 }
References sqrt(), and plotDoE::x.
square()
template<typename T > T SYCL::square (T x)
               {
   return x * x;
 }
References plotDoE::x.
Referenced by test_unary_builtins_for_assignement().
tanh() [1/2]
template<> Eigen::half SYCL::tanh (Eigen::half x)
{
   return Eigen::half(cl::sycl::tanh(static_cast<cl::sycl::half>(x)));
 }
References plotDoE::x.
Referenced by tanh(), and test_unary_builtins_for_assignement().
tanh() [2/2]
template<typename T > T SYCL::tanh (T x)
             {
   return cl::sycl::tanh(x);
 }
References tanh(), and plotDoE::x.