MercuryDPM: Eigen::internal::lapacke_helpers::BDCSVD_LAPACKE< MatrixType_, Options > Class Template Reference
Eigen::internal::lapacke_helpers::BDCSVD_LAPACKE< MatrixType_, Options > Class Template Reference
#include <BDCSVD_LAPACKE.h>
Public Member Functions
BDCSVD_LAPACKE (SVD &&svd)
void compute_impl_lapacke (const MatrixType &matrix, unsigned int computationOptions)
Public Member Functions inherited from Eigen::BDCSVD< MatrixType_, Options >
BDCSVD ()
Default Constructor.
BDCSVD (Index rows, Index cols)
Default Constructor with memory preallocation.
EIGEN_DEPRECATED BDCSVD (Index rows, Index cols, unsigned int computationOptions)
Default Constructor with memory preallocation.
BDCSVD (const MatrixType &matrix)
Constructor performing the decomposition of given matrix, using the custom options specified with the Options template parameter.
EIGEN_DEPRECATED BDCSVD (const MatrixType &matrix, unsigned int computationOptions)
Constructor performing the decomposition of given matrix using specified options for computing unitaries.
~BDCSVD ()
BDCSVD & compute (const MatrixType &matrix)
Method performing the decomposition of given matrix. Computes Thin/Full unitaries U/V if specified using the Options template parameter or the class constructor.
EIGEN_DEPRECATED BDCSVD & compute (const MatrixType &matrix, unsigned int computationOptions)
Method performing the decomposition of given matrix, as specified by the computationOptions parameter.
void setSwitchSize (int s)
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
Public Member Functions inherited from Eigen::SVDBase< BDCSVD< MatrixType_, Options_ > >
BDCSVD< MatrixType_, Options_ > & derived ()
const BDCSVD< MatrixType_, Options_ > & derived () const
const MatrixUType & matrixU () const
const MatrixVType & matrixV () const
const SingularValuesType & singularValues () const
Index nonzeroSingularValues () const
Index rank () const
BDCSVD< MatrixType_, Options_ > & setThreshold (const RealScalar &threshold)
BDCSVD< MatrixType_, Options_ > & setThreshold (Default_t)
RealScalar threshold () const
bool computeU () const
bool computeV () const
Index rows () const
Index cols () const
Index diagSize () const
EIGEN_DEVICE_FUNC ComputationInfo info () const
Reports whether previous computation was successful.
void _solve_impl (const RhsType &rhs, DstType &dst) const
void _solve_impl_transposed (const RhsType &rhs, DstType &dst) const
Public Member Functions inherited from Eigen::SolverBase< Derived >
SolverBase ()
~SolverBase ()
template<typename Rhs >
const Solve< Derived, Rhs > solve (const MatrixBase< Rhs > &b) const
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
constexpr EIGEN_DEVICE_FUNC Derived & derived ()
constexpr EIGEN_DEVICE_FUNC const Derived & derived () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
constexpr EIGEN_DEVICE_FUNC Derived & derived ()
constexpr EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< Derived, Device > device (Device &device)
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const Derived, Device > device (Device &device) const
Private Types
typedef BDCSVD< MatrixType_, Options > SVD
typedef SVD::MatrixType MatrixType
typedef SVD::Scalar Scalar
typedef SVD::RealScalar RealScalar
Additional Inherited Members
Public Types inherited from Eigen::BDCSVD< MatrixType_, Options >
enum
typedef MatrixType_ MatrixType
typedef Base::Scalar Scalar
typedef Base::RealScalar RealScalar
typedef NumTraits< RealScalar >::Literal Literal
typedef Base::Index Index
typedef Base::MatrixUType MatrixUType
typedef Base::MatrixVType MatrixVType
typedef Base::SingularValuesType SingularValuesType
typedef Matrix< Scalar, Dynamic, Dynamic, ColMajor > MatrixX
typedef Matrix< RealScalar, Dynamic, Dynamic, ColMajor > MatrixXr
typedef Matrix< RealScalar, Dynamic, 1 > VectorType
typedef Array< RealScalar, Dynamic, 1 > ArrayXr
typedef Array< Index, 1, Dynamic > ArrayXi
typedef Ref< ArrayXr > ArrayRef
typedef Ref< ArrayXi > IndicesRef
Public Types inherited from Eigen::SVDBase< BDCSVD< MatrixType_, Options_ > >
enum
typedef internal::traits< BDCSVD< MatrixType_, Options_ > >::MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef NumTraits< typename MatrixType::Scalar >::Real RealScalar
typedef Eigen::internal::traits< SVDBase >::StorageIndex StorageIndex
typedef internal::make_proper_matrix_type< Scalar, RowsAtCompileTime, MatrixUColsAtCompileTime, MatrixOptions, MaxRowsAtCompileTime, MatrixUMaxColsAtCompileTime >::type MatrixUType
typedef internal::make_proper_matrix_type< Scalar, ColsAtCompileTime, MatrixVColsAtCompileTime, MatrixOptions, MaxColsAtCompileTime, MatrixVMaxColsAtCompileTime >::type MatrixVType
typedef internal::plain_diag_type< MatrixType, RealScalar >::type SingularValuesType
Public Types inherited from Eigen::SolverBase< Derived >
enum {
RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime , ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime , SizeAtCompileTime = (internal::size_of_xpr_at_compile_time<Derived>::ret) , MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime , MaxSizeAtCompileTime , IsVectorAtCompileTime , NumDimensions
}
typedef EigenBase< Derived > Base
typedef internal::traits< Derived >::Scalar Scalar
typedef Scalar CoeffReturnType
typedef Transpose< const Derived > ConstTransposeReturnType
typedef std::conditional_t< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, const ConstTransposeReturnType >, const ConstTransposeReturnType > AdjointReturnType
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Attributes inherited from Eigen::BDCSVD< MatrixType_, Options >
int m_numIters
Static Public Attributes inherited from Eigen::SVDBase< BDCSVD< MatrixType_, Options_ > >
static constexpr bool ShouldComputeFullU
static constexpr bool ShouldComputeThinU
static constexpr bool ShouldComputeFullV
static constexpr bool ShouldComputeThinV
Protected Member Functions inherited from Eigen::BDCSVD< MatrixType_, Options >
void allocate (Index rows, Index cols, unsigned int computationOptions)
Protected Member Functions inherited from Eigen::SVDBase< BDCSVD< MatrixType_, Options_ > >
void _check_compute_assertions () const
void _check_solve_assertion (const Rhs &b) const
bool allocate (Index rows, Index cols, unsigned int computationOptions)
SVDBase ()
Default Constructor.
Protected Member Functions inherited from Eigen::SolverBase< Derived >
template<bool Transpose_, typename Rhs >
void _check_solve_assertion (const Rhs &b) const
Protected Attributes inherited from Eigen::BDCSVD< MatrixType_, Options >
MatrixXr m_naiveU
MatrixXr m_naiveV
MatrixXr m_computed
Index m_nRec
ArrayXr m_workspace
ArrayXi m_workspaceI
int m_algoswap
bool m_isTranspose
bool m_compU
bool m_compV
bool m_useQrDecomp
JacobiSVD< MatrixType, ComputationOptions > smallSvd
HouseholderQR< MatrixX > qrDecomp
internal::UpperBidiagonalization< MatrixX > bid
MatrixX copyWorkspace
MatrixX reducedTriangle
Protected Attributes inherited from Eigen::SVDBase< BDCSVD< MatrixType_, Options_ > >
MatrixUType m_matrixU
MatrixVType m_matrixV
SingularValuesType m_singularValues
ComputationInfo m_info
bool m_isInitialized
bool m_isAllocated
bool m_usePrescribedThreshold
bool m_computeFullU
bool m_computeThinU
bool m_computeFullV
bool m_computeThinV
unsigned int m_computationOptions
Index m_nonzeroSingularValues
internal::variable_if_dynamic< Index, RowsAtCompileTime > m_rows
internal::variable_if_dynamic< Index, ColsAtCompileTime > m_cols
internal::variable_if_dynamic< Index, DiagSizeAtCompileTime > m_diagSize
RealScalar m_prescribedThreshold
Detailed Description
template<typename MatrixType_, int Options>
class Eigen::internal::lapacke_helpers::BDCSVD_LAPACKE< MatrixType_, Options >
Specialization for the data types supported by LAPACKe
Member Typedef Documentation
MatrixType
template<typename MatrixType_ , int Options> typedef SVD::MatrixType Eigen::internal::lapacke_helpers::BDCSVD_LAPACKE< MatrixType_, Options >::MatrixType private
RealScalar
template<typename MatrixType_ , int Options> typedef SVD::RealScalar Eigen::internal::lapacke_helpers::BDCSVD_LAPACKE< MatrixType_, Options >::RealScalar private
Scalar
template<typename MatrixType_ , int Options> typedef SVD::Scalar Eigen::internal::lapacke_helpers::BDCSVD_LAPACKE< MatrixType_, Options >::Scalar private
SVD
template<typename MatrixType_ , int Options> typedef BDCSVD<MatrixType_, Options> Eigen::internal::lapacke_helpers::BDCSVD_LAPACKE< MatrixType_, Options >::SVD private
Constructor & Destructor Documentation
BDCSVD_LAPACKE()
template<typename MatrixType_ , int Options> Eigen::internal::lapacke_helpers::BDCSVD_LAPACKE< MatrixType_, Options >::BDCSVD_LAPACKE (SVD && svd) inline
 : SVD(std::move(svd)) {}
Member Function Documentation
compute_impl_lapacke()
template<typename MatrixType_ , int Options> void Eigen::internal::lapacke_helpers::BDCSVD_LAPACKE< MatrixType_, Options >::compute_impl_lapacke (const MatrixType & matrix, unsigned int computationOptions) inline
{
     SVD::allocate(matrix.rows(), matrix.cols(), computationOptions);
     SVD::m_nonzeroSingularValues = SVD::m_diagSize;
     // prepare arguments to ?gesdd
     const lapack_int matrix_order = lapack_storage_of(matrix);
     const char jobz = (SVD::m_computeFullU || SVD::m_computeFullV)   ? 'A'
                       : (SVD::m_computeThinU || SVD::m_computeThinV) ? 'S'
                                                                      : 'N';
     const lapack_int u_cols = (jobz == 'A') ? to_lapack(SVD::rows()) : (jobz == 'S') ? to_lapack(SVD::diagSize()) : 1;
     const lapack_int vt_rows = (jobz == 'A') ? to_lapack(SVD::cols()) : (jobz == 'S') ? to_lapack(SVD::diagSize()) : 1;
     lapack_int ldu, ldvt;
     Scalar *u, *vt, dummy;
     MatrixType localU;
     if (SVD::computeU() && !(SVD::m_computeThinU && SVD::m_computeFullV)) {
       ldu = to_lapack(SVD::m_matrixU.outerStride());
       u = SVD::m_matrixU.data();
     } else if (SVD::computeV()) {
       localU.resize(SVD::rows(), u_cols);
       ldu = to_lapack(localU.outerStride());
       u = localU.data();
     } else {
       ldu = 1;
       u = &dummy;
     }
     MatrixType localV;
     if (SVD::computeU() || SVD::computeV()) {
       localV.resize(vt_rows, SVD::cols());
       ldvt = to_lapack(localV.outerStride());
       vt = localV.data();
     } else {
       ldvt = 1;
       vt = &dummy;
     }
     MatrixType temp;
     temp = matrix;
     // actual call to ?gesdd
     lapack_int info = gesdd(matrix_order, jobz, to_lapack(SVD::rows()), to_lapack(SVD::cols()), to_lapack(temp.data()),
                             to_lapack(temp.outerStride()), (RealScalar*)SVD::m_singularValues.data(), to_lapack(u), ldu,
                             to_lapack(vt), ldvt);
     // Check the result of the LAPACK call
     if (info < 0 || !SVD::m_singularValues.allFinite()) {
       // this includes info == -4 => NaN entry in A
       SVD::m_info = InvalidInput;
     } else if (info > 0) {
       SVD::m_info = NoConvergence;
     } else {
       SVD::m_info = Success;
       if (SVD::m_computeThinU && SVD::m_computeFullV) {
         SVD::m_matrixU = localU.leftCols(SVD::m_matrixU.cols());
       }
       if (SVD::computeV()) {
         SVD::m_matrixV = localV.adjoint().leftCols(SVD::m_matrixV.cols());
       }
     }
     SVD::m_isInitialized = true;
   }
References Eigen::BDCSVD< MatrixType_, Options >::allocate(), Eigen::BDCSVD< MatrixType_, Options >::cols(), Eigen::SVDBase< BDCSVD< MatrixType_, Options_ > >::computeU(), Eigen::SVDBase< BDCSVD< MatrixType_, Options_ > >::computeV(), Eigen::PlainObjectBase< Derived >::data(), Eigen::SVDBase< BDCSVD< MatrixType_, Options_ > >::diagSize(), Eigen::SVDBase< BDCSVD< MatrixType_, Options_ > >::info(), Eigen::InvalidInput, lapack_int, Eigen::internal::lapacke_helpers::lapack_storage_of(), Eigen::SVDBase< BDCSVD< MatrixType_, Options_ > >::m_computeFullU, Eigen::SVDBase< BDCSVD< MatrixType_, Options_ > >::m_computeFullV, Eigen::SVDBase< BDCSVD< MatrixType_, Options_ > >::m_computeThinU, Eigen::SVDBase< BDCSVD< MatrixType_, Options_ > >::m_computeThinV, Eigen::SVDBase< BDCSVD< MatrixType_, Options_ > >::m_diagSize, Eigen::SVDBase< BDCSVD< MatrixType_, Options_ > >::m_info, Eigen::SVDBase< BDCSVD< MatrixType_, Options_ > >::m_isInitialized, Eigen::SVDBase< BDCSVD< MatrixType_, Options_ > >::m_matrixU, Eigen::SVDBase< BDCSVD< MatrixType_, Options_ > >::m_matrixV, Eigen::SVDBase< BDCSVD< MatrixType_, Options_ > >::m_nonzeroSingularValues, Eigen::SVDBase< BDCSVD< MatrixType_, Options_ > >::m_singularValues, matrix(), Eigen::NoConvergence, Eigen::BDCSVD< MatrixType_, Options >::rows(), Eigen::Success, and Eigen::internal::lapacke_helpers::to_lapack().
Referenced by Eigen::internal::lapacke_helpers::BDCSVD_wrapper().
The documentation for this class was generated from the following file:
BDCSVD_LAPACKE.h