MercuryDPM: tree_2d.cc File Reference
tree_2d.cc File Reference
#include <typeinfo>
#include "generic.h"
#include "poisson.h"
#include "meshes/simple_rectangular_quadmesh.h"
Classes
class CompareElementCoordinate< ELEMENT >
class Rotateable< ELEMENT >
class TestRefineableRectangularQuadMesh< ELEMENT >
class TestRefineablePoissonProblem< ELEMENT >
Namespaces
TanhSolnForPoisson
Namespace for exact solution for Poisson equation with "sharp step".
Functions
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForPoisson::get_source (const Vector< double > &x, double &source)
Source function to make it an exact solution.
template<class ELEMENT >
void run_test (const unsigned &i)
int main ()
Driver code for 2D Poisson problem.
Function Documentation
main()
int main ()
Driver code for 2D Poisson problem.
 {
  //Run the test three times for three different types of element
  run_test<Rotateable<RefineableQPoissonElement<2,2> > >(1);
  run_test<Rotateable<RefineableQPoissonElement<2,3> > >(2);
  run_test<Rotateable<RefineableQSpectralPoissonElement<2,4> > >(3);
 }
run_test()
template<class ELEMENT > void run_test (const unsigned & i)
Global function that is used to run the rotation tests for different elements
 {
  char dirname[100];
  sprintf(dirname,"RESLT%i",i);
  // Create label for output
  //------------------------
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory(dirname);
  // Step number
  doc_info.number()=0;
  //Set up the problem
  //------------------
  for(unsigned i=0;i<4;i++)
   {
    //Create the problem with rotation i
    TestRefineablePoissonProblem<ELEMENT>
     problem(i,&TanhSolnForPoisson::get_source);
    //Attach the info to the mesh
    //problem.mesh_pt()->doc_info_pt() = &doc_info;
    // Check if we're ready to go:
    //----------------------------
    cout << "\n\n\nProblem self-test ";
    if (problem.self_test()==0)
     {
      cout << "passed: Problem can be solved." << std::endl;
     }
      else
       {
        throw OomphLibError("Self test failed",
                            OOMPH_CURRENT_FUNCTION,
                            OOMPH_EXCEPTION_LOCATION);
       }
    // Solve the problem, performing up to 3 adaptive refinements
    problem.newton_solve(3);
    //Output the solution
    problem.doc_solution(doc_info);
    doc_info.number()++;
   }
 }
References TanhSolnForPoisson::get_source(), i, oomph::DocInfo::number(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, problem, and oomph::DocInfo::set_directory().