MercuryDPM: Eigen::half_impl::numeric_limits_half_impl< typename > Struct Template Reference
Eigen::half_impl::numeric_limits_half_impl< typename > Struct Template Reference
#include <Half.h>
Static Public Member Functions
static EIGEN_CONSTEXPR Eigen::half() min ()
static EIGEN_CONSTEXPR Eigen::half lowest ()
static EIGEN_CONSTEXPR Eigen::half() max ()
static EIGEN_CONSTEXPR Eigen::half epsilon ()
static EIGEN_CONSTEXPR Eigen::half round_error ()
static EIGEN_CONSTEXPR Eigen::half infinity ()
static EIGEN_CONSTEXPR Eigen::half quiet_NaN ()
static EIGEN_CONSTEXPR Eigen::half signaling_NaN ()
static EIGEN_CONSTEXPR Eigen::half denorm_min ()
Static Public Attributes
static EIGEN_CONSTEXPR const bool is_specialized = true
static EIGEN_CONSTEXPR const bool is_signed = true
static EIGEN_CONSTEXPR const bool is_integer = false
static EIGEN_CONSTEXPR const bool is_exact = false
static EIGEN_CONSTEXPR const bool has_infinity = true
static EIGEN_CONSTEXPR const bool has_quiet_NaN = true
static EIGEN_CONSTEXPR const bool has_signaling_NaN = true
static EIGEN_DISABLE_DEPRECATED_WARNING EIGEN_CONSTEXPR const std::float_denorm_style has_denorm = std::denorm_present
static EIGEN_CONSTEXPR const bool has_denorm_loss = false
static EIGEN_CONSTEXPR const std::float_round_style round_style = std::round_to_nearest
static EIGEN_CONSTEXPR const bool is_iec559 = true
static EIGEN_CONSTEXPR const bool is_bounded = true
static EIGEN_CONSTEXPR const bool is_modulo = false
static EIGEN_CONSTEXPR const int digits = 11
static EIGEN_CONSTEXPR const int digits10
static EIGEN_CONSTEXPR const int max_digits10
static EIGEN_CONSTEXPR const int radix = std::numeric_limits<float>::radix
static EIGEN_CONSTEXPR const int min_exponent = -13
static EIGEN_CONSTEXPR const int min_exponent10 = -4
static EIGEN_CONSTEXPR const int max_exponent = 16
static EIGEN_CONSTEXPR const int max_exponent10 = 4
static EIGEN_CONSTEXPR const bool traps = std::numeric_limits<float>::traps
static EIGEN_CONSTEXPR const bool tinyness_before = std::numeric_limits<float>::tinyness_before
Member Function Documentation
denorm_min()
template<typename = void> static EIGEN_CONSTEXPR Eigen::half Eigen::half_impl::numeric_limits_half_impl< typename >::denorm_min () inline static
 { return Eigen::half_impl::raw_uint16_to_half(0x0001); }
References Eigen::half_impl::raw_uint16_to_half().
epsilon()
template<typename = void> static EIGEN_CONSTEXPR Eigen::half Eigen::half_impl::numeric_limits_half_impl< typename >::epsilon () inline static
 { return Eigen::half_impl::raw_uint16_to_half(0x1400); }
References Eigen::half_impl::raw_uint16_to_half().
infinity()
template<typename = void> static EIGEN_CONSTEXPR Eigen::half Eigen::half_impl::numeric_limits_half_impl< typename >::infinity () inline static
 { return Eigen::half_impl::raw_uint16_to_half(0x7c00); }
References Eigen::half_impl::raw_uint16_to_half().
lowest()
template<typename = void> static EIGEN_CONSTEXPR Eigen::half Eigen::half_impl::numeric_limits_half_impl< typename >::lowest () inline static
 { return Eigen::half_impl::raw_uint16_to_half(0xfbff); }
References Eigen::half_impl::raw_uint16_to_half().
max()
template<typename = void> static EIGEN_CONSTEXPR Eigen::half() Eigen::half_impl::numeric_limits_half_impl< typename >::max () inline static
 { return Eigen::half_impl::raw_uint16_to_half(0x7bff); }
References Eigen::half_impl::raw_uint16_to_half().
min()
template<typename = void> static EIGEN_CONSTEXPR Eigen::half() Eigen::half_impl::numeric_limits_half_impl< typename >::min () inline static
 { return Eigen::half_impl::raw_uint16_to_half(0x0400); }
References Eigen::half_impl::raw_uint16_to_half().
quiet_NaN()
template<typename = void> static EIGEN_CONSTEXPR Eigen::half Eigen::half_impl::numeric_limits_half_impl< typename >::quiet_NaN () inline static
 { return Eigen::half_impl::raw_uint16_to_half(0x7e00); }
References Eigen::half_impl::raw_uint16_to_half().
round_error()
template<typename = void> static EIGEN_CONSTEXPR Eigen::half Eigen::half_impl::numeric_limits_half_impl< typename >::round_error () inline static
 { return Eigen::half_impl::raw_uint16_to_half(0x3800); }
References Eigen::half_impl::raw_uint16_to_half().
signaling_NaN()
template<typename = void> static EIGEN_CONSTEXPR Eigen::half Eigen::half_impl::numeric_limits_half_impl< typename >::signaling_NaN () inline static
 { return Eigen::half_impl::raw_uint16_to_half(0x7d00); }
References Eigen::half_impl::raw_uint16_to_half().
Member Data Documentation
digits
template<typename T > EIGEN_CONSTEXPR const int Eigen::half_impl::numeric_limits_half_impl< T >::digits = 11 static
digits10
template<typename T > EIGEN_CONSTEXPR const int Eigen::half_impl::numeric_limits_half_impl< T >::digits10 static
Initial value:
=
      3
has_denorm
template<typename T > EIGEN_DISABLE_DEPRECATED_WARNING EIGEN_CONSTEXPR const std::float_denorm_style Eigen::half_impl::numeric_limits_half_impl< T >::has_denorm = std::denorm_present static
has_denorm_loss
template<typename T > EIGEN_CONSTEXPR const bool Eigen::half_impl::numeric_limits_half_impl< T >::has_denorm_loss = false static
has_infinity
template<typename T > EIGEN_CONSTEXPR const bool Eigen::half_impl::numeric_limits_half_impl< T >::has_infinity = true static
has_quiet_NaN
template<typename T > EIGEN_CONSTEXPR const bool Eigen::half_impl::numeric_limits_half_impl< T >::has_quiet_NaN = true static
has_signaling_NaN
template<typename T > EIGEN_CONSTEXPR const bool Eigen::half_impl::numeric_limits_half_impl< T >::has_signaling_NaN = true static
is_bounded
template<typename T > EIGEN_CONSTEXPR const bool Eigen::half_impl::numeric_limits_half_impl< T >::is_bounded = true static
is_exact
template<typename T > EIGEN_CONSTEXPR const bool Eigen::half_impl::numeric_limits_half_impl< T >::is_exact = false static
is_iec559
template<typename T > EIGEN_CONSTEXPR const bool Eigen::half_impl::numeric_limits_half_impl< T >::is_iec559 = true static
is_integer
template<typename T > EIGEN_CONSTEXPR const bool Eigen::half_impl::numeric_limits_half_impl< T >::is_integer = false static
is_modulo
template<typename T > EIGEN_CONSTEXPR const bool Eigen::half_impl::numeric_limits_half_impl< T >::is_modulo = false static
is_signed
template<typename T > EIGEN_CONSTEXPR const bool Eigen::half_impl::numeric_limits_half_impl< T >::is_signed = true static
is_specialized
template<typename T > EIGEN_CONSTEXPR const bool Eigen::half_impl::numeric_limits_half_impl< T >::is_specialized = true static
max_digits10
template<typename T > EIGEN_CONSTEXPR const int Eigen::half_impl::numeric_limits_half_impl< T >::max_digits10 static
Initial value:
=
      5
max_exponent
template<typename T > EIGEN_CONSTEXPR const int Eigen::half_impl::numeric_limits_half_impl< T >::max_exponent = 16 static
max_exponent10
template<typename T > EIGEN_CONSTEXPR const int Eigen::half_impl::numeric_limits_half_impl< T >::max_exponent10 = 4 static
min_exponent
template<typename T > EIGEN_CONSTEXPR const int Eigen::half_impl::numeric_limits_half_impl< T >::min_exponent = -13 static
min_exponent10
template<typename T > EIGEN_CONSTEXPR const int Eigen::half_impl::numeric_limits_half_impl< T >::min_exponent10 = -4 static
radix
template<typename T > EIGEN_CONSTEXPR const int Eigen::half_impl::numeric_limits_half_impl< T >::radix = std::numeric_limits<float>::radix static
round_style
template<typename T > EIGEN_CONSTEXPR const std::float_round_style Eigen::half_impl::numeric_limits_half_impl< T >::round_style = std::round_to_nearest static
tinyness_before
template<typename T > EIGEN_CONSTEXPR const bool Eigen::half_impl::numeric_limits_half_impl< T >::tinyness_before = std::numeric_limits<float>::tinyness_before static
traps
template<typename T > EIGEN_CONSTEXPR const bool Eigen::half_impl::numeric_limits_half_impl< T >::traps = std::numeric_limits<float>::traps static
The documentation for this struct was generated from the following file:
Half.h