MercuryDPM: zerosized.cpp File Reference
zerosized.cpp File Reference
#include "main.h"
Functions
template<typename MatrixType >
void zeroReduction (const MatrixType &m)
template<typename MatrixType >
void zeroSizedMatrix ()
template<typename VectorType >
void zeroSizedVector ()
EIGEN_DECLARE_TEST (zerosized)
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (zerosized)
{
   zeroSizedMatrix<Matrix2d>();
   zeroSizedMatrix<Matrix3i>();
   zeroSizedMatrix<Matrix<float, 2, Dynamic> >();
   zeroSizedMatrix<MatrixXf>();
   zeroSizedMatrix<Matrix<float, 0, 0> >();
   zeroSizedMatrix<Matrix<float, Dynamic, 0, 0, 0, 0> >();
   zeroSizedMatrix<Matrix<float, 0, Dynamic, 0, 0, 0> >();
   zeroSizedMatrix<Matrix<float, Dynamic, Dynamic, 0, 0, 0> >();
   zeroSizedMatrix<Matrix<float, 0, 4> >();
   zeroSizedMatrix<Matrix<float, 4, 0> >();
   zeroSizedVector<Vector2d>();
   zeroSizedVector<Vector3i>();
   zeroSizedVector<VectorXf>();
   zeroSizedVector<Matrix<float, 0, 1> >();
   zeroSizedVector<Matrix<float, 1, 0> >();
 }
zeroReduction()
template<typename MatrixType > void zeroReduction (const MatrixType & m)
{
   // Reductions that must hold for zero sized objects
   VERIFY(m.all());
   VERIFY(!m.any());
   VERIFY(m.prod() == 1);
   VERIFY(m.sum() == 0);
   VERIFY(m.norm() == 0);
   VERIFY(m.squaredNorm() == 0);
   VERIFY(m.count() == 0);
   VERIFY(m.allFinite());
   VERIFY(!m.hasNaN());
   VERIFY_RAISES_ASSERT(m.minCoeff());
   VERIFY_RAISES_ASSERT(m.maxCoeff());
   Index i, j;
   VERIFY_RAISES_ASSERT(m.minCoeff(&i, &j));
   VERIFY_RAISES_ASSERT(m.maxCoeff(&i, &j));
   VERIFY_RAISES_ASSERT(m.reshaped().minCoeff(&i));
   VERIFY_RAISES_ASSERT(m.reshaped().maxCoeff(&i));
 }
References i, j, m, VERIFY, and VERIFY_RAISES_ASSERT.
Referenced by zeroSizedMatrix(), and zeroSizedVector().
zeroSizedMatrix()
template<typename MatrixType > void zeroSizedMatrix ()
{
   MatrixType t1;
   typedef typename MatrixType::Scalar Scalar;
   if (MatrixType::SizeAtCompileTime == Dynamic || MatrixType::SizeAtCompileTime == 0) {
     zeroReduction(t1);
     if (MatrixType::RowsAtCompileTime == Dynamic) VERIFY(t1.rows() == 0);
     if (MatrixType::ColsAtCompileTime == Dynamic) VERIFY(t1.cols() == 0);
     if (MatrixType::RowsAtCompileTime == Dynamic && MatrixType::ColsAtCompileTime == Dynamic) {
       MatrixType t2(0, 0);
       VERIFY(t2.rows() == 0);
       VERIFY(t2.cols() == 0);
       zeroReduction(t2);
       VERIFY(t1 == t2);
     }
   }
   if (MatrixType::MaxColsAtCompileTime != 0 && MatrixType::MaxRowsAtCompileTime != 0) {
     Index rows = MatrixType::RowsAtCompileTime == Dynamic ? internal::random<Index>(1, 10)
                                                           : Index(MatrixType::RowsAtCompileTime);
     Index cols = MatrixType::ColsAtCompileTime == Dynamic ? internal::random<Index>(1, 10)
                                                           : Index(MatrixType::ColsAtCompileTime);
     MatrixType m(rows, cols);
     zeroReduction(m.template block<0, MatrixType::ColsAtCompileTime>(0, 0, 0, cols));
     zeroReduction(m.template block<MatrixType::RowsAtCompileTime, 0>(0, 0, rows, 0));
     zeroReduction(m.template block<0, 1>(0, 0));
     zeroReduction(m.template block<1, 0>(0, 0));
     Matrix<Scalar, Dynamic, Dynamic> prod = m.template block<MatrixType::RowsAtCompileTime, 0>(0, 0, rows, 0) *
                                             m.template block<0, MatrixType::ColsAtCompileTime>(0, 0, 0, cols);
     VERIFY(prod.rows() == rows && prod.cols() == cols);
     VERIFY(prod.isZero());
     prod = m.template block<1, 0>(0, 0) * m.template block<0, 1>(0, 0);
     VERIFY(prod.size() == 1);
     VERIFY(prod.isZero());
   }
 }
References cols, Eigen::Dynamic, m, prod(), rows, VERIFY, and zeroReduction().
zeroSizedVector()
template<typename VectorType > void zeroSizedVector ()
{
   VectorType t1;
   if (VectorType::SizeAtCompileTime == Dynamic || VectorType::SizeAtCompileTime == 0) {
     zeroReduction(t1);
     VERIFY(t1.size() == 0);
     VectorType t2(DenseIndex(0));  // DenseIndex disambiguates with 0-the-null-pointer (error with gcc 4.4 and MSVC8)
     VERIFY(t2.size() == 0);
     zeroReduction(t2);
     VERIFY(t1 == t2);
   }
 }
References Eigen::Dynamic, VERIFY, and zeroReduction().