MercuryDPM: oomph::TetEdge Class Reference
oomph::TetEdge Class Reference
Helper class to keep track of edges in tet mesh generation.
#include <gmsh_tet_mesh.template.h>
Public Member Functions
TetEdge (const unsigned &vertex1, const unsigned &vertex2)
unsigned first_vertex_id () const
First vertex id.
unsigned second_vertex_id () const
Second vertex id.
bool is_reversed () const
bool operator== (const TetEdge &tet_edge) const
bool operator< (const TetEdge &tet_edge) const
Private Attributes
std::pair< unsigned, unsigned > Vertex_pair
The vertices (sorted by vertex ids)
bool Reversed
Detailed Description
Helper class to keep track of edges in tet mesh generation.
////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
TetEdge()
oomph::TetEdge::TetEdge (const unsigned & vertex1, const unsigned & vertex2) inline
Constructor: Pass two vertices, identified by their indices Edge "direction" is from lower vertex to higher vertex id so can compare if we're dealing with the same one...
     {
       if (vertex1 > vertex2)
       {
         Reversed = true;
         Vertex_pair = std::make_pair(vertex2, vertex1);
       }
       else if (vertex1 < vertex2)
       {
         Reversed = false;
         Vertex_pair = std::make_pair(vertex1, vertex2);
       }
       else
       {
         throw OomphLibError(
           "Muppet! You can't build an edge from one vertex to the same vertex!",
           OOMPH_CURRENT_FUNCTION,
           OOMPH_EXCEPTION_LOCATION);
       }
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, Reversed, and Vertex_pair.
Member Function Documentation
first_vertex_id()
unsigned oomph::TetEdge::first_vertex_id () const inline
First vertex id.
     {
       return Vertex_pair.first;
     }
References Vertex_pair.
Referenced by operator<(), and operator==().
is_reversed()
bool oomph::TetEdge::is_reversed () const inline
Edge is reversed in the sense that vertex1 actually has a higher id than vertex2 (when specified in the constructor)
     {
       return Reversed;
     }
References Reversed.
Referenced by oomph::GmshTetScaffoldMesh::write_geo_file().
operator<()
bool oomph::TetEdge::operator< (const TetEdge & tet_edge) const inline
Comparison operator. Lexicographic comparison based on vertex ids
     {
       if ((tet_edge.first_vertex_id() == Vertex_pair.first) &&
           (tet_edge.second_vertex_id() == Vertex_pair.second))
       {
         return false;
       }
       else
       {
         if (tet_edge.first_vertex_id() == Vertex_pair.first)
         {
           return (tet_edge.second_vertex_id() < Vertex_pair.second);
         }
         else
         {
           return (tet_edge.first_vertex_id() < Vertex_pair.first);
         }
       }
     }
References first_vertex_id(), second_vertex_id(), and Vertex_pair.
operator==()
bool oomph::TetEdge::operator== (const TetEdge & tet_edge) const inline
Comparison operator: Edges are identical if their sorted (and therefore possibly reversed) vertex ids agree
     {
       return ((tet_edge.first_vertex_id() == Vertex_pair.first) &&
               (tet_edge.second_vertex_id() == Vertex_pair.second));
     }
References first_vertex_id(), second_vertex_id(), and Vertex_pair.
second_vertex_id()
unsigned oomph::TetEdge::second_vertex_id () const inline
Second vertex id.
     {
       return Vertex_pair.second;
     }
References Vertex_pair.
Referenced by operator<(), and operator==().
Member Data Documentation
Reversed
bool oomph::TetEdge::Reversed private
Is it reversed? I.e. is the first input vertex stored after the second one?
Referenced by is_reversed(), and TetEdge().
Vertex_pair
std::pair<unsigned, unsigned> oomph::TetEdge::Vertex_pair private
The vertices (sorted by vertex ids)
Referenced by first_vertex_id(), operator<(), operator==(), second_vertex_id(), and TetEdge().
The documentation for this class was generated from the following file:
gmsh_tet_mesh.template.h