MercuryDPM: fourier_decomposed_acoustic_fsi.cc File Reference
fourier_decomposed_acoustic_fsi.cc File Reference
#include <complex>
#include <cmath>
#include "generic.h"
#include "fourier_decomposed_helmholtz.h"
#include "time_harmonic_fourier_decomposed_linear_elasticity.h"
#include "multi_physics.h"
#include "meshes/annular_mesh.h"
#include "oomph_crbond_bessel.h"
Classes
class CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >
Coated sphere FSI.
Namespaces
Global_Parameters
Namespace for global parameters.
Functions
std::complex< double > Global_Parameters::Nu (std::complex< double >(0.3, 0.0))
Poisson's ratio Nu.
std::complex< double > Global_Parameters::Omega_sq (std::complex< double >(100.0, 0.0))
Non-dim square of frequency for solid – dependent variable!
void Global_Parameters::update_parameter_values ()
Function to update dependent parameter values.
void Global_Parameters::solid_boundary_displacement (const Vector< double > &x, Vector< std::complex< double > > &u)
Displacement field on inner boundary of solid.
int main (int argc, char **argv)
Driver for coated sphere loaded by lineared fluid loading.
Variables
int Global_Parameters::Fourier_wavenumber =0
Define azimuthal Fourier wavenumber.
unsigned Global_Parameters::M =4
Function Documentation
main()
int main (int argc , char ** argv)
Driver for coated sphere loaded by lineared fluid loading.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Output directory
  CommandLineArgs::specify_command_line_flag("--dir",
                                             &Global_Parameters::Directory);
  // Parameter for the Helmholtz equation
  CommandLineArgs::specify_command_line_flag("--k_squared",
                                             &Global_Parameters::K_squared);
  // Initial value of Q
  CommandLineArgs::specify_command_line_flag("--q_initial",
                                             &Global_Parameters::Q);
  // Number of steps in parameter study
  unsigned nstep=2;
  CommandLineArgs::specify_command_line_flag("--nstep",&nstep);
  // Increment in FSI parameter in parameter study
  double q_increment=5.0;
  CommandLineArgs::specify_command_line_flag("--q_increment",&q_increment);
  // Wavenumber "zenith"-variation of imposed displacement of coating
  // on inner boundary
  CommandLineArgs::specify_command_line_flag("--M",
                                             &Global_Parameters::M);
  // Multiplier for number of elements
  CommandLineArgs::specify_command_line_flag("--el_multiplier",
                                             &Global_Parameters::El_multiplier);
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Update dependent parameters values
  Global_Parameters::update_parameter_values();
  // Set up doc info
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory(Global_Parameters::Directory);
  // Set up the problem
  CoatedSphereProblem<QTimeHarmonicFourierDecomposedLinearElasticityElement<3>,
                      QFourierDecomposedHelmholtzElement<3> > problem;
  //Parameter incrementation
  for(unsigned i=0;i<nstep;i++)
   {
    // Solve the problem with Newton's method
    problem.newton_solve();
    // Doc solution
    problem.doc_solution(doc_info);
    // Increment FSI parameter
    Global_Parameters::Q+=q_increment;
    Global_Parameters::update_parameter_values();
   }
 } //end_of_main
References Global_Parameters::Directory, oomph::CommandLineArgs::doc_specified_flags(), Global_Parameters::El_multiplier, i, Global_Parameters::K_squared, Global_Parameters::M, oomph::CommandLineArgs::parse_and_assign(), problem, Global_Parameters::Q, oomph::DocInfo::set_directory(), oomph::CommandLineArgs::setup(), oomph::CommandLineArgs::specify_command_line_flag(), and Global_Parameters::update_parameter_values().