MercuryDPM: oomph::ExplicitTimeSteppableObject Class Reference
oomph::ExplicitTimeSteppableObject Class Reference
#include <explicit_timesteppers.h>
Public Member Functions
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void get_dvaluesdt (DoubleVector &minv_res)
virtual void get_dofs (DoubleVector &dofs) const
Function that gets the values of the dofs in the object.
virtual void get_dofs (const unsigned &t, DoubleVector &dofs) const
Function that gets the history values of the dofs in the object.
virtual void set_dofs (const DoubleVector &dofs)
Function that sets the values of the dofs in the object.
virtual void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Function that adds the values to the dofs.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
virtual void actions_before_explicit_timestep ()
virtual void actions_after_explicit_timestep ()
virtual double & time ()
virtual Time * time_pt () const
Static Private Attributes
static double Dummy_time_value = 0.0
Dummy value of time always set to zero.
Detailed Description
Class for objects than can be advanced in time by an Explicit Timestepper. WARNING: For explicit time stepping to work the object's residual function (as used by get_inverse_mass_matrix_times_residuals(..)) MUST be in the form r = f(t, u) - [timestepper approximation to dudt]! Standard implicit time stepping will work with plenty of residuals that don't fit into this form. Some examples where implicit time stepping will work fine but explicit will fail: 1) The negation of the above formula, this implementation will end up using dudt = - f(u,t). 2) A residual which is implicit or non-linear in dudt, such as r = dudt
u x dudt.
Constructor & Destructor Documentation
ExplicitTimeSteppableObject() [1/2]
oomph::ExplicitTimeSteppableObject::ExplicitTimeSteppableObject () inline
Empty constructor.
 {}
ExplicitTimeSteppableObject() [2/2]
oomph::ExplicitTimeSteppableObject::ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &) delete
Broken copy constructor.
~ExplicitTimeSteppableObject()
virtual oomph::ExplicitTimeSteppableObject::~ExplicitTimeSteppableObject () inline virtual
Empty destructor.
 {}
Member Function Documentation
actions_after_explicit_stage()
virtual void oomph::ExplicitTimeSteppableObject::actions_after_explicit_stage () inline virtual
Empty virtual function that should be overloaded to update any dependent data or boundary conditions that should be advanced after each stage of an explicit time step (Runge-Kutta steps contain multiple stages per time step, most others only contain one).
Reimplemented in oomph::MyProblem, and TwoDDGProblem< ELEMENT >.
 {}
Referenced by SSP_RungeKutta< ORDER >::timestep(), oomph::RungeKutta< ORDER >::timestep(), oomph::LowStorageRungeKutta< ORDER >::timestep(), oomph::Euler::timestep(), and oomph::EBDF3::timestep().
actions_after_explicit_timestep()
virtual void oomph::ExplicitTimeSteppableObject::actions_after_explicit_timestep () inline virtual
Empty virtual function that can be overloaded to do anything needed after an explicit step.
Reimplemented in oomph::Problem, and oomph::MyProblem.
 {}
Referenced by SSP_RungeKutta< ORDER >::timestep(), oomph::RungeKutta< ORDER >::timestep(), oomph::LowStorageRungeKutta< ORDER >::timestep(), oomph::Euler::timestep(), and oomph::EBDF3::timestep().
actions_before_explicit_stage()
virtual void oomph::ExplicitTimeSteppableObject::actions_before_explicit_stage () inline virtual
Empty virtual function to do anything needed before a stage of an explicit time step (Runge-Kutta steps contain multiple stages per time step, most others only contain one).
Reimplemented in oomph::MyProblem.
 {}
Referenced by SSP_RungeKutta< ORDER >::timestep(), oomph::RungeKutta< ORDER >::timestep(), oomph::LowStorageRungeKutta< ORDER >::timestep(), oomph::Euler::timestep(), and oomph::EBDF3::timestep().
actions_before_explicit_timestep()
virtual void oomph::ExplicitTimeSteppableObject::actions_before_explicit_timestep () inline virtual
Empty virtual function that can be overloaded to do anything needed before an explicit step.
Reimplemented in oomph::Problem, and oomph::MyProblem.
 {}
Referenced by SSP_RungeKutta< ORDER >::timestep(), oomph::RungeKutta< ORDER >::timestep(), oomph::LowStorageRungeKutta< ORDER >::timestep(), oomph::Euler::timestep(), and oomph::EBDF3::timestep().
add_to_dofs()
void oomph::ExplicitTimeSteppableObject::add_to_dofs (const double & lambda, const DoubleVector & increment_dofs) virtual
Function that adds the values to the dofs.
Function that adds the lambda multiplied by the increment_dofs vector to the dofs in the object
Reimplemented in oomph::Problem.
   {
     std::ostringstream error_stream;
     error_stream
       << "Empty default function called.\n"
       << "The function must add lambda multiplied by the contents of the\n"
       << "input vector to the degrees of freedom in the object.\n"
       << "Note: It is the responsibility of the object to ensure that the\n"
       << "      the degrees of freedom are in the same order as those \n"
       << "      returned by get_dvaluesdt()\n";
     throw OomphLibError(
       error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
   }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by SSP_RungeKutta< ORDER >::timestep(), oomph::RungeKutta< ORDER >::timestep(), oomph::LowStorageRungeKutta< ORDER >::timestep(), and oomph::Euler::timestep().
get_dofs() [1/2]
void oomph::ExplicitTimeSteppableObject::get_dofs (const unsigned & t, DoubleVector & dofs) const virtual
Function that gets the history values of the dofs in the object.
Function that should get the values of the dofs in the object.
Reimplemented in oomph::Problem.
   {
     std::ostringstream error_stream;
     error_stream
       << "Empty default function called.\n"
       << "The function must return the t'th history values of the degrees of \n"
       << "freedom in the object.\n"
       << "Note: It is the responsibility of the object to set the size\n"
       << "of the vector\n";
     throw OomphLibError(
       error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
   }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
get_dofs() [2/2]
void oomph::ExplicitTimeSteppableObject::get_dofs (DoubleVector & dofs) const virtual
Function that gets the values of the dofs in the object.
Function that should get the values of the dofs in the object.
Reimplemented in oomph::Problem.
   {
     std::ostringstream error_stream;
     error_stream
       << "Empty default function called.\n"
       << "The function must return the current values of the degrees of \n"
       << "freedom in the object.\n"
       << "Note: It is the responsibility of the object to set the size\n"
       << "of the vector\n";
     throw OomphLibError(
       error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
   }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by SSP_RungeKutta< ORDER >::timestep(), oomph::RungeKutta< ORDER >::timestep(), and oomph::EBDF3::timestep().
get_dvaluesdt()
void oomph::ExplicitTimeSteppableObject::get_dvaluesdt (DoubleVector & minv_res) virtual
A single virtual function that returns the residuals vector multiplied by the inverse mass matrix
Reimplemented in oomph::Problem.
   {
     std::ostringstream error_stream;
     error_stream
       << "Empty default function called.\n"
       << "The function must return the solution x of the linear system\n"
       << "                    M x = R\n"
       << "in order for the object to be used by an ExplicitTimeStepper.\n"
       << "NOTE: It is the responsibility of the object to set the size \n"
       << "      of the vector x\n";
     throw OomphLibError(
       error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
   }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by SSP_RungeKutta< ORDER >::timestep(), oomph::RungeKutta< ORDER >::timestep(), oomph::LowStorageRungeKutta< ORDER >::timestep(), oomph::Euler::timestep(), and oomph::EBDF3::timestep().
operator=()
void oomph::ExplicitTimeSteppableObject::operator= (const ExplicitTimeSteppableObject &) delete
Broken assignment operator.
set_dofs()
void oomph::ExplicitTimeSteppableObject::set_dofs (const DoubleVector & dofs) virtual
Function that sets the values of the dofs in the object.
Reimplemented in oomph::Problem.
   {
     std::ostringstream error_stream;
     error_stream
       << "Empty default function called.\n"
       << "The function must set the current values of the degrees of \n"
       << "freedom in the object.\n";
     throw OomphLibError(
       error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
   }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by SSP_RungeKutta< ORDER >::timestep(), oomph::RungeKutta< ORDER >::timestep(), and oomph::EBDF3::timestep().
time()
double & oomph::ExplicitTimeSteppableObject::time () virtual
Broken virtual function that should be overloaded to return access to the local time in the object
Virtual function that should be overloaded to return access to the local time in the object
Reimplemented in oomph::Problem.
   {
     std::ostringstream error_stream;
     error_stream << "Empty default function called.\n"
                  << "The function must return a reference to the local time in "
                     "the object\n";
     throw OomphLibError(
       error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     return Dummy_time_value;
   }
References Dummy_time_value, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by SSP_RungeKutta< ORDER >::timestep(), oomph::RungeKutta< ORDER >::timestep(), oomph::LowStorageRungeKutta< ORDER >::timestep(), oomph::Euler::timestep(), and oomph::EBDF3::timestep().
time_pt()
Time * oomph::ExplicitTimeSteppableObject::time_pt () const virtual
Virtual function that should be overloaded to return a pointer to a Time object.
Reimplemented in oomph::Problem.
   {
     std::ostringstream error_stream;
     error_stream
       << "Empty default function called.\n"
       << "The function must return a pointer to an oomph-lib Time object.\n";
     throw OomphLibError(
       error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     return 0;
   }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::EBDF3::timestep().
Member Data Documentation
Dummy_time_value
double oomph::ExplicitTimeSteppableObject::Dummy_time_value = 0.0 static private
Dummy value of time always set to zero.
Referenced by time().
The documentation for this class was generated from the following files:
explicit_timesteppers.h
explicit_timesteppers.cc