MercuryDPM: oomph::NewMumpsPreconditioner Class Reference
oomph::NewMumpsPreconditioner Class Reference
An interface to allow Mumps to be used as an (exact) Preconditioner.
#include <mumps_solver.h>
Public Member Functions
NewMumpsPreconditioner ()
Constructor.
~NewMumpsPreconditioner ()
Destructor.
NewMumpsPreconditioner (const NewMumpsPreconditioner &)=delete
Broken copy constructor.
void operator= (const NewMumpsPreconditioner &)=delete
Broken assignment operator.
void setup ()
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
void clean_up_memory ()
void enable_doc_time ()
Enable documentation of timings.
void disable_doc_time ()
Disable the documentation of timings.
Public Member Functions inherited from oomph::Preconditioner
Preconditioner ()
Constructor.
Preconditioner (const Preconditioner &)=delete
Broken copy constructor.
void operator= (const Preconditioner &)=delete
Broken assignment operator.
virtual ~Preconditioner ()
Destructor (empty)
virtual void preconditioner_solve_transpose (const DoubleVector &r, DoubleVector &z)
void setup (DoubleMatrixBase *matrix_pt)
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
void enable_silent_preconditioner_setup ()
Set up the block preconditioner quietly!
void disable_silent_preconditioner_setup ()
Be verbose in the block preconditioner setup.
virtual DoubleMatrixBase * matrix_pt () const
Get function for matrix pointer.
virtual void set_matrix_pt (DoubleMatrixBase *matrix_pt)
Set the matrix pointer.
virtual const OomphCommunicator * comm_pt () const
Get function for comm pointer.
virtual void set_comm_pt (const OomphCommunicator *const comm_pt)
Set the communicator pointer.
double setup_time () const
Returns the time to setup the preconditioner.
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> &doftype_coarsen_map_coarse)
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
void build_distribution (const LinearAlgebraDistribution &dist)
Private Attributes
MumpsSolver Solver
the Mumps solver emplyed by this preconditioner
Additional Inherited Members
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
Protected Attributes inherited from oomph::Preconditioner
bool Silent_preconditioner_setup
Boolean to indicate whether or not the build should be done silently.
std::ostream * Stream_pt
Pointer to the output stream – defaults to std::cout.
Detailed Description
An interface to allow Mumps to be used as an (exact) Preconditioner.
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
NewMumpsPreconditioner() [1/2]
oomph::NewMumpsPreconditioner::NewMumpsPreconditioner () inline
Constructor.
 {}
~NewMumpsPreconditioner()
oomph::NewMumpsPreconditioner::~NewMumpsPreconditioner () inline
Destructor.
 {}
NewMumpsPreconditioner() [2/2]
oomph::NewMumpsPreconditioner::NewMumpsPreconditioner (const NewMumpsPreconditioner &) delete
Broken copy constructor.
Member Function Documentation
clean_up_memory()
void oomph::NewMumpsPreconditioner::clean_up_memory () inline virtual
Clean up memory – forward the call to the version in Mumps in its LinearSolver incarnation.
Reimplemented from oomph::Preconditioner.
     {
       Solver.clean_up_memory();
     }
References oomph::MumpsSolver::clean_up_memory(), and Solver.
disable_doc_time()
void oomph::NewMumpsPreconditioner::disable_doc_time () inline
Disable the documentation of timings.
     {
       Solver.disable_doc_time();
     }
References oomph::LinearSolver::disable_doc_time(), and Solver.
enable_doc_time()
void oomph::NewMumpsPreconditioner::enable_doc_time () inline
Enable documentation of timings.
     {
       Solver.enable_doc_time();
     }
References oomph::LinearSolver::enable_doc_time(), and Solver.
operator=()
void oomph::NewMumpsPreconditioner::operator= (const NewMumpsPreconditioner &) delete
Broken assignment operator.
preconditioner_solve()
void oomph::NewMumpsPreconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) inline virtual
Function applies Mumps to vector r for (exact) preconditioning, this requires a call to setup(...) first.
Implements oomph::Preconditioner.
     {
       Solver.resolve(r, z);
     }
References UniformPSDSelfTest::r, oomph::MumpsSolver::resolve(), and Solver.
setup()
void oomph::NewMumpsPreconditioner::setup () inline virtual
Function to set up a preconditioner for the linear system defined by matrix_pt. This function must be called before using preconditioner_solve. Note: matrix_pt must point to an object of class CRDoubleMatrix or CCDoubleMatrix
Implements oomph::Preconditioner.
     {
       oomph_info << "Setting up Mumps (exact) preconditioner" << std::endl;
       DistributableLinearAlgebraObject* dist_matrix_pt =
         dynamic_cast<DistributableLinearAlgebraObject*>(matrix_pt());
       if (dist_matrix_pt != 0)
       {
         LinearAlgebraDistribution dist(dist_matrix_pt->distribution_pt());
         this->build_distribution(dist);
         Solver.factorise(matrix_pt());
       }
       else
       {
         std::ostringstream error_message_stream;
         error_message_stream
           << "NewMumpsPreconditioner can only be applied to matrices derived \n"
           << "DistributableLinearAlgebraObject.\n";
         throw OomphLibError(error_message_stream.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
     }
References oomph::DistributableLinearAlgebraObject::build_distribution(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::MumpsSolver::factorise(), oomph::Preconditioner::matrix_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, and Solver.
Member Data Documentation
Solver
MumpsSolver oomph::NewMumpsPreconditioner::Solver private
the Mumps solver emplyed by this preconditioner
Referenced by clean_up_memory(), disable_doc_time(), enable_doc_time(), preconditioner_solve(), and setup().
The documentation for this class was generated from the following file:
mumps_solver.h