MercuryDPM: Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device > Struct Template Reference
#include <TensorShuffling.h>
Classes
struct PacketLoader
struct PacketLoader< LoadMode, Self, true >
Public Types
enum {
IsAligned = false , PacketAccess = (PacketType<CoeffReturnType, Device>::size > 1) , BlockAccess = TensorEvaluator<ArgType, Device>::RawAccess , PreferBlockAccess = true ,
CoordAccess = false , RawAccess = false
}
typedef TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device > Self
typedef TensorShufflingOp< Shuffle, ArgType > XprType
typedef XprType::Index Index
typedef DSizes< Index, NumDims > Dimensions
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef std::remove_const_t< Scalar > ScalarNoConst
typedef internal::TensorBlockDescriptor< NumDims, Index > TensorBlockDesc
typedef internal::TensorBlockScratchAllocator< Device > TensorBlockScratch
typedef internal::TensorMaterializedBlock< ScalarNoConst, NumDims, Layout, Index > TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements getResourceRequirements () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock block (TensorBlockDesc &desc, TensorBlockScratch &scratch, bool root_of_expr_ast=false) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC Storage::Type data () const
Static Public Attributes
static constexpr int NumDims = internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Protected Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index GetBlockOutputIndex (Index input_index, const DSizes< Index, NumDims > &input_block_strides, const DSizes< Index, NumDims > &output_block_strides, const DSizes< internal::TensorIntDivisor< Index >, NumDims > &fast_input_block_strides) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index srcCoeff (Index index) const
Protected Attributes
Dimensions m_dimensions
bool m_is_identity
array< int, NumDims > m_shuffle
array< Index, NumDims > m_inverseShuffle
array< Index, NumDims > m_outputStrides
array< internal::TensorIntDivisor< Index >, NumDims > m_fastOutputStrides
array< Index, NumDims > m_inputStrides
array< Index, NumDims > m_unshuffledInputStrides
const Device EIGEN_DEVICE_REF m_device
TensorEvaluator< ArgType, Device > m_impl
Member Typedef Documentation
CoeffReturnType
template<typename Shuffle , typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::CoeffReturnType
Dimensions
template<typename Shuffle , typename ArgType , typename Device > typedef DSizes<Index, NumDims> Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::Dimensions
EvaluatorPointerType
template<typename Shuffle , typename ArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::EvaluatorPointerType
Index
template<typename Shuffle , typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::Index
PacketReturnType
template<typename Shuffle , typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::PacketReturnType
Scalar
template<typename Shuffle , typename ArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::Scalar
ScalarNoConst
template<typename Shuffle , typename ArgType , typename Device > typedef std::remove_const_t<Scalar> Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::ScalarNoConst
Self
template<typename Shuffle , typename ArgType , typename Device > typedef TensorEvaluator<const TensorShufflingOp<Shuffle, ArgType>, Device> Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::Self
Storage
template<typename Shuffle , typename ArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::Storage
TensorBlock
template<typename Shuffle , typename ArgType , typename Device > typedef internal::TensorMaterializedBlock<ScalarNoConst, NumDims, Layout, Index> Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::TensorBlock
TensorBlockDesc
template<typename Shuffle , typename ArgType , typename Device > typedef internal::TensorBlockDescriptor<NumDims, Index> Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::TensorBlockDesc
TensorBlockScratch
template<typename Shuffle , typename ArgType , typename Device > typedef internal::TensorBlockScratchAllocator<Device> Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::TensorBlockScratch
XprType
template<typename Shuffle , typename ArgType , typename Device > typedef TensorShufflingOp<Shuffle, ArgType> Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename Shuffle , typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = false,
     PacketAccess = (PacketType<CoeffReturnType, Device>::size > 1),
     BlockAccess = TensorEvaluator<ArgType, Device>::RawAccess,
     PreferBlockAccess = true,
     CoordAccess = false,  // to be implemented
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename Shuffle , typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_device(device), m_impl(op.expression(), device) {
     const typename TensorEvaluator<ArgType, Device>::Dimensions& input_dims = m_impl.dimensions();
     const Shuffle& shuffle = op.shufflePermutation();
     m_is_identity = true;
     for (int i = 0; i < NumDims; ++i) {
       m_shuffle[i] = static_cast<int>(shuffle[i]);
       m_dimensions[i] = input_dims[shuffle[i]];
       m_inverseShuffle[shuffle[i]] = i;
       if (m_is_identity && shuffle[i] != i) {
         m_is_identity = false;
       }
     }
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       m_unshuffledInputStrides[0] = 1;
       m_outputStrides[0] = 1;
       for (int i = 1; i < NumDims; ++i) {
         m_unshuffledInputStrides[i] = m_unshuffledInputStrides[i - 1] * input_dims[i - 1];
         m_outputStrides[i] = m_outputStrides[i - 1] * m_dimensions[i - 1];
         m_fastOutputStrides[i] =
             internal::TensorIntDivisor<Index>(m_outputStrides[i] > 0 ? m_outputStrides[i] : Index(1));
       }
     } else {
       m_unshuffledInputStrides[NumDims - 1] = 1;
       m_outputStrides[NumDims - 1] = 1;
       for (int i = NumDims - 2; i >= 0; --i) {
         m_unshuffledInputStrides[i] = m_unshuffledInputStrides[i + 1] * input_dims[i + 1];
         m_outputStrides[i] = m_outputStrides[i + 1] * m_dimensions[i + 1];
         m_fastOutputStrides[i] =
             internal::TensorIntDivisor<Index>(m_outputStrides[i] > 0 ? m_outputStrides[i] : Index(1));
       }
     }
     for (int i = 0; i < NumDims; ++i) {
       m_inputStrides[i] = m_unshuffledInputStrides[shuffle[i]];
     }
   }
References Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), i, Eigen::TensorEvaluator< Derived, Device >::Layout, op, and Eigen::internal::shuffle().
Member Function Documentation
block()
template<typename Shuffle , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::block (TensorBlockDesc & desc, TensorBlockScratch & scratch, bool root_of_expr_ast = false) const inline
{
     eigen_assert(m_impl.data() != NULL);
     typedef internal::TensorBlockIO<ScalarNoConst, Index, NumDims, Layout> TensorBlockIO;
     typedef typename TensorBlockIO::Dst TensorBlockIODst;
     typedef typename TensorBlockIO::Src TensorBlockIOSrc;
     const typename TensorBlock::Storage block_storage =
         TensorBlock::prepareStorage(desc, scratch, /*allow_strided_storage=*/root_of_expr_ast);
     typename TensorBlockIO::Dimensions input_strides(m_unshuffledInputStrides);
     TensorBlockIOSrc src(input_strides, m_impl.data(), srcCoeff(desc.offset()));
     TensorBlockIODst dst(block_storage.dimensions(), block_storage.strides(), block_storage.data());
     typename TensorBlockIO::DimensionsMap dst_to_src_dim_map(m_shuffle);
     TensorBlockIO::Copy(dst, src, dst_to_src_dim_map);
     return block_storage.AsTensorMaterializedBlock();
   }
References Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::AsTensorMaterializedBlock(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::data(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::dimensions(), eigen_assert, Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::offset(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::prepareStorage(), and Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::strides().
cleanup()
template<typename Shuffle , typename ArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::cleanup () inline
 { m_impl.cleanup(); }
Referenced by framework.Frame::__init__().
coeff()
template<typename Shuffle , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::coeff (Index index) const inline
{
     if (m_is_identity) {
       return m_impl.coeff(index);
     } else {
       return m_impl.coeff(srcCoeff(index));
     }
   }
costPerCoeff()
template<typename Shuffle , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     const double compute_cost = m_is_identity
                                     ? TensorOpCost::AddCost<Index>()
                                     : NumDims * (2 * TensorOpCost::AddCost<Index>() +
                                                  2 * TensorOpCost::MulCost<Index>() + TensorOpCost::DivCost<Index>());
     return m_impl.costPerCoeff(vectorized) +
            TensorOpCost(0, 0, compute_cost, m_is_identity /* vectorized */, PacketSize);
   }
References Eigen::TensorEvaluator< Derived, Device >::PacketSize.
data()
template<typename Shuffle , typename ArgType , typename Device > EIGEN_DEVICE_FUNC Storage::Type Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename Shuffle , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::dimensions () const inline
 { return m_dimensions; }
evalSubExprsIfNeeded()
template<typename Shuffle , typename ArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
{
     m_impl.evalSubExprsIfNeeded(NULL);
     return true;
   }
GetBlockOutputIndex()
template<typename Shuffle , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::GetBlockOutputIndex (Index input_index, const DSizes< Index, NumDims > & input_block_strides, const DSizes< Index, NumDims > & output_block_strides, const DSizes< internal::TensorIntDivisor< Index >, NumDims > & fast_input_block_strides) const inline protected
{
     Index output_index = 0;
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       for (int i = NumDims - 1; i > 0; --i) {
         const Index idx = input_index / fast_input_block_strides[i];
         output_index += idx * output_block_strides[m_inverseShuffle[i]];
         input_index -= idx * input_block_strides[i];
       }
       return output_index + input_index * output_block_strides[m_inverseShuffle[0]];
     } else {
       for (int i = 0; i < NumDims - 1; ++i) {
         const Index idx = input_index / fast_input_block_strides[i];
         output_index += idx * output_block_strides[m_inverseShuffle[i]];
         input_index -= idx * input_block_strides[i];
       }
       return output_index + input_index * output_block_strides[m_inverseShuffle[NumDims - 1]];
     }
   }
References Eigen::ColMajor, i, and Eigen::TensorEvaluator< Derived, Device >::Layout.
getResourceRequirements()
template<typename Shuffle , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::getResourceRequirements () const inline
{
     static const int inner_dim = Layout == static_cast<int>(ColMajor) ? 0 : NumDims - 1;
     const size_t target_size = m_device.firstLevelCacheSize();
     const bool inner_dim_shuffled = m_shuffle[inner_dim] != inner_dim;
     // Shuffled inner dimensions leads to a random memory access, which is not
     // captured by default cost model bytes loaded/stored. We add this cost
     // explicitly. The number of cycles picked based on the benchmarks.
     // TODO(ezhulenev): This number was picked based on a very questionable
     // benchmarks, add benchmarks that are representative of real workloads.
     using BlockRequirements = internal::TensorBlockResourceRequirements;
     if (inner_dim_shuffled) {
       return BlockRequirements::uniform<Scalar>(target_size).addCostPerCoeff({0, 0, NumDims * 28});
     } else {
       return BlockRequirements::skewed<Scalar>(target_size);
     }
   }
References Eigen::internal::TensorBlockResourceRequirements::addCostPerCoeff(), Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::Layout, and Eigen::TensorEvaluator< Derived, Device >::m_device.
packet()
template<typename Shuffle , typename ArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::packet (Index index) const inline
{
     eigen_assert(index + PacketSize - 1 < dimensions().TotalSize());
     return PacketLoader<LoadMode, Self, TensorEvaluator<ArgType, Device>::PacketAccess>::Run(*this, index);
   }
References Eigen::TensorEvaluator< Derived, Device >::dimensions(), eigen_assert, and Eigen::TensorEvaluator< Derived, Device >::PacketSize.
srcCoeff()
template<typename Shuffle , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::srcCoeff (Index index) const inline protected
{
     Index inputIndex = 0;
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       for (int i = NumDims - 1; i > 0; --i) {
         const Index idx = index / m_fastOutputStrides[i];
         inputIndex += idx * m_inputStrides[i];
         index -= idx * m_outputStrides[i];
       }
       return inputIndex + index * m_inputStrides[0];
     } else {
       for (int i = 0; i < NumDims - 1; ++i) {
         const Index idx = index / m_fastOutputStrides[i];
         inputIndex += idx * m_inputStrides[i];
         index -= idx * m_outputStrides[i];
       }
       return inputIndex + index * m_inputStrides[NumDims - 1];
     }
   }
References Eigen::ColMajor, i, and Eigen::TensorEvaluator< Derived, Device >::Layout.
Member Data Documentation
Layout
template<typename Shuffle , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_device
template<typename Shuffle , typename ArgType , typename Device > const Device EIGEN_DEVICE_REF Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::m_device protected
m_dimensions
template<typename Shuffle , typename ArgType , typename Device > Dimensions Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::m_dimensions protected
m_fastOutputStrides
template<typename Shuffle , typename ArgType , typename Device > array<internal::TensorIntDivisor<Index>, NumDims> Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::m_fastOutputStrides protected
m_impl
template<typename Shuffle , typename ArgType , typename Device > TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::m_impl protected
m_inputStrides
template<typename Shuffle , typename ArgType , typename Device > array<Index, NumDims> Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::m_inputStrides protected
m_inverseShuffle
template<typename Shuffle , typename ArgType , typename Device > array<Index, NumDims> Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::m_inverseShuffle protected
m_is_identity
template<typename Shuffle , typename ArgType , typename Device > bool Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::m_is_identity protected
m_outputStrides
template<typename Shuffle , typename ArgType , typename Device > array<Index, NumDims> Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::m_outputStrides protected
m_shuffle
template<typename Shuffle , typename ArgType , typename Device > array<int, NumDims> Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::m_shuffle protected
m_unshuffledInputStrides
template<typename Shuffle , typename ArgType , typename Device > array<Index, NumDims> Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::m_unshuffledInputStrides protected
NumDims
template<typename Shuffle , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::NumDims = internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value static constexpr
PacketSize
template<typename Shuffle , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorShuffling.h