MercuryDPM: oomph::TElement3FaceToBulkCoordinates Namespace Reference
oomph::TElement3FaceToBulkCoordinates Namespace Reference
Functions
void face0 (const Vector< double > &s, Vector< double > &s_bulk)
The translation scheme for the face s0 = 0.
void face1 (const Vector< double > &s, Vector< double > &s_bulk)
The translation scheme for the face s1 = 0.
void face2 (const Vector< double > &s, Vector< double > &s_bulk)
The translation scheme for the face s2 = 0.
void face3 (const Vector< double > &s, Vector< double > &s_bulk)
The translation scheme for the sloping face.
Detailed Description
Namespace for the functions that translate local face coordinates to the coordinates in the bulk element
Function Documentation
face0()
void oomph::TElement3FaceToBulkCoordinates::face0 (const Vector< double > & s, Vector< double > & s_bulk)
The translation scheme for the face s0 = 0.
     {
       s_bulk[0] = 0.0;
       s_bulk[1] = s[0];
       s_bulk[2] = s[1];
     }
References s.
Referenced by oomph::TElement< 3, NNODE_1D >::build_face_element().
face1()
void oomph::TElement3FaceToBulkCoordinates::face1 (const Vector< double > & s, Vector< double > & s_bulk)
The translation scheme for the face s1 = 0.
     {
       s_bulk[0] = s[0];
       s_bulk[1] = 0.0;
       s_bulk[2] = s[1];
     }
References s.
Referenced by oomph::TElement< 3, NNODE_1D >::build_face_element().
face2()
void oomph::TElement3FaceToBulkCoordinates::face2 (const Vector< double > & s, Vector< double > & s_bulk)
The translation scheme for the face s2 = 0.
     {
       s_bulk[0] = s[0];
       s_bulk[1] = s[1];
       s_bulk[2] = 0.0;
     }
References s.
Referenced by oomph::TElement< 3, NNODE_1D >::build_face_element().
face3()
void oomph::TElement3FaceToBulkCoordinates::face3 (const Vector< double > & s, Vector< double > & s_bulk)
The translation scheme for the sloping face.
     {
       s_bulk[0] = 1 - s[0] - s[1];
       s_bulk[1] = s[0];
       s_bulk[2] = s[1];
     }
References s.
Referenced by oomph::TElement< 3, NNODE_1D >::build_face_element().