MercuryDPM: eighth_sphere_poisson.cc File Reference
eighth_sphere_poisson.cc File Reference
#include "generic.h"
#include "poisson.h"
#include "meshes/eighth_sphere_mesh.h"
Classes
class EighthSpherePoissonProblem< ELEMENT >
Poisson problem in refineable eighth of a sphere mesh.
Namespaces
TanhSolnForPoisson
Namespace for exact solution for Poisson equation with "sharp step".
Functions
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, double &u)
Exact solution as a scalar.
void TanhSolnForPoisson::get_source (const Vector< double > &x, double &source)
Source function to make it an exact solution.
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Driver for 3D Poisson problem in eighth of a sphere. Solution has a sharp step. If there are any command line arguments, we regard this as a validation run and perform only a single adaptation.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Set up the problem with 27-node brick elements, pass pointer to
  // source function
  EighthSpherePoissonProblem<RefineableQPoissonElement<3,3> >
   problem(&TanhSolnForPoisson::get_source);
  // Setup labels for output
   DocInfo doc_info;
  // Output directory
  doc_info.set_directory("RESLT");
  // Step number
  doc_info.number()=0;
  // Check if we're ready to go
  cout << "Self test: " << problem.self_test() << std::endl;
  // Solve the problem
  problem.newton_solve();
  //Output solution
  problem.doc_solution(doc_info);
  //Increment counter for solutions
  doc_info.number()++;
  // Now do (up to) three rounds of fully automatic adapation in response to
  // error estimate
  unsigned max_solve;
  if (CommandLineArgs::Argc>1)
   {
    // Validation run: Just one adaptation
    max_solve=1;
    cout << "Only doing one adaptation for validation" << std::endl;
   }
  else
   {
    // Up to four adaptations
    max_solve=4;
   }
  for (unsigned isolve=0;isolve<max_solve;isolve++)
   {
    // Adapt problem/mesh
    problem.adapt();
    // Re-solve the problem if the adaptation has changed anything
    if ((problem.mesh_pt()->nrefined()  !=0)||
        (problem.mesh_pt()->nunrefined()!=0))
     {
      problem.newton_solve();
     }
    else
     {
      cout << "Mesh wasn't adapted --> we'll stop here" << std::endl;
      break;
     }
    //Output solution
    problem.doc_solution(doc_info);
    //Increment counter for solutions
    doc_info.number()++;
   }
 // pause("done");
 } // end of main
References oomph::CommandLineArgs::Argc, TanhSolnForPoisson::get_source(), oomph::DocInfo::number(), problem, oomph::DocInfo::set_directory(), and Flag_definition::setup().