MercuryDPM: Eigen::RealSchur< MatrixType_ > Class Template Reference
Eigen::RealSchur< MatrixType_ > Class Template Reference
Dense linear problems and decompositions » Reference » Eigenvalues_Module
Performs a real Schur decomposition of a square matrix.
#include <RealSchur.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime , ColsAtCompileTime = MatrixType::ColsAtCompileTime , Options = internal::traits<MatrixType>::Options , MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
}
typedef MatrixType_ MatrixType
typedef MatrixType::Scalar Scalar
typedef std::complex< typename NumTraits< Scalar >::Real > ComplexScalar
typedef Eigen::Index Index
typedef Matrix< ComplexScalar, ColsAtCompileTime, 1, Options &~RowMajor, MaxColsAtCompileTime, 1 > EigenvalueType
typedef Matrix< Scalar, ColsAtCompileTime, 1, Options &~RowMajor, MaxColsAtCompileTime, 1 > ColumnVectorType
Public Member Functions
RealSchur (Index size=RowsAtCompileTime==Dynamic ? 1 :RowsAtCompileTime)
Default constructor.
template<typename InputType >
RealSchur (const EigenBase< InputType > &matrix, bool computeU=true)
Constructor; computes real Schur decomposition of given matrix.
const MatrixType & matrixU () const
Returns the orthogonal matrix in the Schur decomposition.
const MatrixType & matrixT () const
Returns the quasi-triangular matrix in the Schur decomposition.
template<typename InputType >
RealSchur & compute (const EigenBase< InputType > &matrix, bool computeU=true)
Computes Schur decomposition of given matrix.
template<typename HessMatrixType , typename OrthMatrixType >
RealSchur & computeFromHessenberg (const HessMatrixType &matrixH, const OrthMatrixType &matrixQ, bool computeU)
Computes Schur decomposition of a Hessenberg matrix H = Z T Z^T.
ComputationInfo info () const
Reports whether previous computation was successful.
RealSchur & setMaxIterations (Index maxIters)
Sets the maximum number of iterations allowed.
Index getMaxIterations ()
Returns the maximum number of iterations.
template<typename InputType >
RealSchur< MatrixType > & compute (const EigenBase< InputType > &matrix, bool computeU)
template<typename HessMatrixType , typename OrthMatrixType >
RealSchur< MatrixType > & computeFromHessenberg (const HessMatrixType &matrixH, const OrthMatrixType &matrixQ, bool computeU)
Static Public Attributes
static const int m_maxIterationsPerRow = 40
Maximum number of iterations per row.
Private Types
typedef Matrix< Scalar, 3, 1 > Vector3s
Private Member Functions
Scalar computeNormOfT ()
Index findSmallSubdiagEntry (Index iu, const Scalar &considerAsZero)
void splitOffTwoRows (Index iu, bool computeU, const Scalar &exshift)
void computeShift (Index iu, Index iter, Scalar &exshift, Vector3s &shiftInfo)
void initFrancisQRStep (Index il, Index iu, const Vector3s &shiftInfo, Index &im, Vector3s &firstHouseholderVector)
void performFrancisQRStep (Index il, Index im, Index iu, bool computeU, const Vector3s &firstHouseholderVector, Scalar *workspace)
Private Attributes
MatrixType m_matT
MatrixType m_matU
ColumnVectorType m_workspaceVector
HessenbergDecomposition< MatrixType > m_hess
ComputationInfo m_info
bool m_isInitialized
bool m_matUisUptodate
Index m_maxIters
Detailed Description
template<typename MatrixType_>
class Eigen::RealSchur< MatrixType_ >
Performs a real Schur decomposition of a square matrix.
\eigenvalues_module
Template Parameters
MatrixType_ the type of the matrix of which we are computing the real Schur decomposition; this is expected to be an instantiation of the Matrix class template.
Given a real square matrix A, this class computes the real Schur decomposition: \(A = U T U^T \) where U is a real orthogonal matrix and T is a real quasi-triangular matrix. An orthogonal matrix is a matrix whose inverse is equal to its transpose, \(U^{-1} = U^T \). A quasi-triangular matrix is a block-triangular matrix whose diagonal consists of 1-by-1 blocks and 2-by-2 blocks with complex eigenvalues. The eigenvalues of the blocks on the diagonal of T are the same as the eigenvalues of the matrix A, and thus the real Schur decomposition is used in EigenSolver to compute the eigendecomposition of a matrix.
Call the function compute() to compute the real Schur decomposition of a given matrix. Alternatively, you can use the RealSchur(const MatrixType&, bool) constructor which computes the real Schur decomposition at construction time. Once the decomposition is computed, you can use the matrixU() and matrixT() functions to retrieve the matrices U and T in the decomposition.
The documentation of RealSchur(const MatrixType&, bool) contains an example of the typical use of this class.
Note
The implementation is adapted from JAMA (public domain). Their code is based on EISPACK.
See also
class ComplexSchur, class EigenSolver, class ComplexEigenSolver
Member Typedef Documentation
ColumnVectorType
template<typename MatrixType_ > typedef Matrix<Scalar, ColsAtCompileTime, 1, Options & ~RowMajor, MaxColsAtCompileTime, 1> Eigen::RealSchur< MatrixType_ >::ColumnVectorType
ComplexScalar
template<typename MatrixType_ > typedef std::complex<typename NumTraits<Scalar>::Real> Eigen::RealSchur< MatrixType_ >::ComplexScalar
EigenvalueType
template<typename MatrixType_ > typedef Matrix<ComplexScalar, ColsAtCompileTime, 1, Options & ~RowMajor, MaxColsAtCompileTime, 1> Eigen::RealSchur< MatrixType_ >::EigenvalueType
Index
template<typename MatrixType_ > typedef Eigen::Index Eigen::RealSchur< MatrixType_ >::Index
Deprecated:
since Eigen 3.3
MatrixType
template<typename MatrixType_ > typedef MatrixType_ Eigen::RealSchur< MatrixType_ >::MatrixType
Scalar
template<typename MatrixType_ > typedef MatrixType::Scalar Eigen::RealSchur< MatrixType_ >::Scalar
Vector3s
template<typename MatrixType_ > typedef Matrix<Scalar, 3, 1> Eigen::RealSchur< MatrixType_ >::Vector3s private
Member Enumeration Documentation
anonymous enum
template<typename MatrixType_ > anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
Options
MaxRowsAtCompileTime
MaxColsAtCompileTime
        {
     RowsAtCompileTime = MatrixType::RowsAtCompileTime,
     ColsAtCompileTime = MatrixType::ColsAtCompileTime,
     Options = internal::traits<MatrixType>::Options,
     MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
     MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
   };
Constructor & Destructor Documentation
RealSchur() [1/2]
template<typename MatrixType_ > Eigen::RealSchur< MatrixType_ >::RealSchur (Index size = RowsAtCompileTime == Dynamic ? 1 : RowsAtCompileTime) inline explicit
Default constructor.
Parameters
[in] size Positive integer, size of the matrix whose Schur decomposition will be computed.
The default constructor is useful in cases in which the user intends to perform decompositions via compute(). The size parameter is only used as a hint. It is not an error to give a wrong size, but it may impair performance.
See also
compute() for an example.
                                                                    : RowsAtCompileTime)
       : m_matT(size, size),
         m_matU(size, size),
         m_workspaceVector(size),
         m_hess(size),
         m_isInitialized(false),
         m_matUisUptodate(false),
         m_maxIters(-1) {}
RealSchur() [2/2]
template<typename MatrixType_ > template<typename InputType > Eigen::RealSchur< MatrixType_ >::RealSchur (const EigenBase< InputType > & matrix, bool computeU = true) inline explicit
Constructor; computes real Schur decomposition of given matrix.
Parameters
[in] matrix Square matrix whose Schur decomposition is to be computed.
[in] computeU If true, both T and U are computed; if false, only T is computed.
This constructor calls compute() to compute the Schur decomposition.
Example:
MatrixXd A = MatrixXd::Random(6, 6);
cout << "Here is a random 6x6 matrix, A:" << endl << A << endl << endl;
RealSchur<MatrixXd> schur(A);
cout << "The orthogonal matrix U is:" << endl << schur.matrixU() << endl;
cout << "The quasi-triangular matrix T is:" << endl << schur.matrixT() << endl << endl;
MatrixXd U = schur.matrixU();
MatrixXd T = schur.matrixT();
cout << "U * T * U^T = " << endl << U * T * U.transpose() << endl;
Output:
       : m_matT(matrix.rows(), matrix.cols()),
         m_matU(matrix.rows(), matrix.cols()),
         m_workspaceVector(matrix.rows()),
         m_hess(matrix.rows()),
         m_isInitialized(false),
         m_matUisUptodate(false),
         m_maxIters(-1) {
     compute(matrix.derived(), computeU);
   }
References Eigen::RealSchur< MatrixType_ >::compute(), and matrix().
Member Function Documentation
compute() [1/2]
template<typename MatrixType_ > template<typename InputType > RealSchur<MatrixType>& Eigen::RealSchur< MatrixType_ >::compute (const EigenBase< InputType > & matrix, bool computeU)
{
   const Scalar considerAsZero = (std::numeric_limits<Scalar>::min)();
   eigen_assert(matrix.cols() == matrix.rows());
   Index maxIters = m_maxIters;
   if (maxIters == -1) maxIters = m_maxIterationsPerRow * matrix.rows();
   Scalar scale = matrix.derived().cwiseAbs().maxCoeff();
   if (scale < considerAsZero) {
     m_matT.setZero(matrix.rows(), matrix.cols());
     if (computeU) m_matU.setIdentity(matrix.rows(), matrix.cols());
     m_info = Success;
     m_isInitialized = true;
     m_matUisUptodate = computeU;
     return *this;
   }
   // Step 1. Reduce to Hessenberg form
   m_hess.compute(matrix.derived() / scale);
   // Step 2. Reduce to real Schur form
   // Note: we copy m_hess.matrixQ() into m_matU here and not in computeFromHessenberg
   //       to be able to pass our working-space buffer for the Householder to Dense evaluation.
   m_workspaceVector.resize(matrix.cols());
   if (computeU) m_hess.matrixQ().evalTo(m_matU, m_workspaceVector);
   computeFromHessenberg(m_hess.matrixH(), m_matU, computeU);
   m_matT *= scale;
   return *this;
 }
References eigen_assert, matrix(), min, and Eigen::Success.
compute() [2/2]
template<typename MatrixType_ > template<typename InputType > RealSchur& Eigen::RealSchur< MatrixType_ >::compute (const EigenBase< InputType > & matrix, bool computeU = true)
Computes Schur decomposition of given matrix.
Parameters
[in] matrix Square matrix whose Schur decomposition is to be computed.
[in] computeU If true, both T and U are computed; if false, only T is computed.
Returns
Reference to *this
The Schur decomposition is computed by first reducing the matrix to Hessenberg form using the class HessenbergDecomposition. The Hessenberg matrix is then reduced to triangular form by performing Francis QR iterations with implicit double shift. The cost of computing the Schur decomposition depends on the number of iterations; as a rough guide, it may be taken to be \(25n^3\) flops if computeU is true and \(10n^3\) flops if computeU is false.
Example:
MatrixXf A = MatrixXf::Random(4, 4);
RealSchur<MatrixXf> schur(4);
schur.compute(A, /* computeU = */ false);
cout << "The matrix T in the decomposition of A is:" << endl << schur.matrixT() << endl;
schur.compute(A.inverse(), /* computeU = */ false);
cout << "The matrix T in the decomposition of A^(-1) is:" << endl << schur.matrixT() << endl;
Output:
See also
compute(const MatrixType&, bool, Index)
Referenced by Eigen::RealSchur< MatrixType_ >::RealSchur(), and schur().
computeFromHessenberg() [1/2]
template<typename MatrixType_ > template<typename HessMatrixType , typename OrthMatrixType > RealSchur& Eigen::RealSchur< MatrixType_ >::computeFromHessenberg (const HessMatrixType & matrixH, const OrthMatrixType & matrixQ, bool computeU)
Computes Schur decomposition of a Hessenberg matrix H = Z T Z^T.
Parameters
[in] matrixH Matrix in Hessenberg form H
[in] matrixQ orthogonal matrix Q that transform a matrix A to H : A = Q H Q^T
computeU Computes the matriX U of the Schur vectors
Returns
Reference to *this
This routine assumes that the matrix is already reduced in Hessenberg form matrixH using either the class HessenbergDecomposition or another mean. It computes the upper quasi-triangular matrix T of the Schur decomposition of H When computeU is true, this routine computes the matrix U such that A = U T U^T = (QZ) T (QZ)^T = Q H Q^T where A is the initial matrix
NOTE Q is referenced if computeU is true; so, if the initial orthogonal matrix is not available, the user should give an identity matrix (Q.setIdentity())
See also
compute(const MatrixType&, bool)
computeFromHessenberg() [2/2]
template<typename MatrixType_ > template<typename HessMatrixType , typename OrthMatrixType > RealSchur<MatrixType>& Eigen::RealSchur< MatrixType_ >::computeFromHessenberg (const HessMatrixType & matrixH, const OrthMatrixType & matrixQ, bool computeU)
{
   using std::abs;
   m_matT = matrixH;
   m_workspaceVector.resize(m_matT.cols());
   if (computeU && !internal::is_same_dense(m_matU, matrixQ)) m_matU = matrixQ;
   Index maxIters = m_maxIters;
   if (maxIters == -1) maxIters = m_maxIterationsPerRow * matrixH.rows();
   Scalar* workspace = &m_workspaceVector.coeffRef(0);
   // The matrix m_matT is divided in three parts.
   // Rows 0,...,il-1 are decoupled from the rest because m_matT(il,il-1) is zero.
   // Rows il,...,iu is the part we are working on (the active window).
   // Rows iu+1,...,end are already brought in triangular form.
   Index iu = m_matT.cols() - 1;
   Index iter = 0;       // iteration count for current eigenvalue
   Index totalIter = 0;  // iteration count for whole matrix
   Scalar exshift(0);    // sum of exceptional shifts
   Scalar norm = computeNormOfT();
   // sub-diagonal entries smaller than considerAsZero will be treated as zero.
   // We use eps^2 to enable more precision in small eigenvalues.
   Scalar considerAsZero =
       numext::maxi<Scalar>(norm * numext::abs2(NumTraits<Scalar>::epsilon()), (std::numeric_limits<Scalar>::min)());
   if (!numext::is_exactly_zero(norm)) {
     while (iu >= 0) {
       Index il = findSmallSubdiagEntry(iu, considerAsZero);
       // Check for convergence
       if (il == iu)  // One root found
       {
         m_matT.coeffRef(iu, iu) = m_matT.coeff(iu, iu) + exshift;
         if (iu > 0) m_matT.coeffRef(iu, iu - 1) = Scalar(0);
         iu--;
         iter = 0;
       } else if (il == iu - 1)  // Two roots found
       {
         splitOffTwoRows(iu, computeU, exshift);
         iu -= 2;
         iter = 0;
       } else  // No convergence yet
       {
         // The firstHouseholderVector vector has to be initialized to something to get rid of a silly GCC warning (-O1
         // -Wall -DNDEBUG )
         Vector3s firstHouseholderVector = Vector3s::Zero(), shiftInfo;
         computeShift(iu, iter, exshift, shiftInfo);
         iter = iter + 1;
         totalIter = totalIter + 1;
         if (totalIter > maxIters) break;
         Index im;
         initFrancisQRStep(il, iu, shiftInfo, im, firstHouseholderVector);
         performFrancisQRStep(il, im, iu, computeU, firstHouseholderVector, workspace);
       }
     }
   }
   if (totalIter <= maxIters)
     m_info = Success;
   else
     m_info = NoConvergence;
   m_isInitialized = true;
   m_matUisUptodate = computeU;
   return *this;
 }
References abs(), Eigen::numext::abs2(), Eigen::numext::is_exactly_zero(), Eigen::internal::is_same_dense(), min, Eigen::NoConvergence, Eigen::Success, and oomph::PseudoSolidHelper::Zero.
computeNormOfT()
template<typename MatrixType > MatrixType::Scalar Eigen::RealSchur< MatrixType >::computeNormOfT inline private
Computes and returns vector L1 norm of T
{
   const Index size = m_matT.cols();
   // FIXME to be efficient the following would requires a triangular reduxion code
   // Scalar norm = m_matT.upper().cwiseAbs().sum()
   //               + m_matT.bottomLeftCorner(size-1,size-1).diagonal().cwiseAbs().sum();
   Scalar norm(0);
   for (Index j = 0; j < size; ++j) norm += m_matT.col(j).segment(0, (std::min)(size, j + 2)).cwiseAbs().sum();
   return norm;
 }
References j, min, and size.
computeShift()
template<typename MatrixType > void Eigen::RealSchur< MatrixType >::computeShift (Index iu, Index iter, Scalar & exshift, Vector3s & shiftInfo) inline private
Form shift in shiftInfo, and update exshift if an exceptional shift is performed.
{
   using std::abs;
   using std::sqrt;
   shiftInfo.coeffRef(0) = m_matT.coeff(iu, iu);
   shiftInfo.coeffRef(1) = m_matT.coeff(iu - 1, iu - 1);
   shiftInfo.coeffRef(2) = m_matT.coeff(iu, iu - 1) * m_matT.coeff(iu - 1, iu);
   // Alternate exceptional shifting strategy every 16 iterations.
   if (iter % 16 == 0) {
     // Wilkinson's original ad hoc shift
     if (iter % 32 != 0) {
       exshift += shiftInfo.coeff(0);
       for (Index i = 0; i <= iu; ++i) m_matT.coeffRef(i, i) -= shiftInfo.coeff(0);
       Scalar s = abs(m_matT.coeff(iu, iu - 1)) + abs(m_matT.coeff(iu - 1, iu - 2));
       shiftInfo.coeffRef(0) = Scalar(0.75) * s;
       shiftInfo.coeffRef(1) = Scalar(0.75) * s;
       shiftInfo.coeffRef(2) = Scalar(-0.4375) * s * s;
     } else {
       // MATLAB's new ad hoc shift
       Scalar s = (shiftInfo.coeff(1) - shiftInfo.coeff(0)) / Scalar(2.0);
       s = s * s + shiftInfo.coeff(2);
       if (s > Scalar(0)) {
         s = sqrt(s);
         if (shiftInfo.coeff(1) < shiftInfo.coeff(0)) s = -s;
         s = s + (shiftInfo.coeff(1) - shiftInfo.coeff(0)) / Scalar(2.0);
         s = shiftInfo.coeff(0) - shiftInfo.coeff(2) / s;
         exshift += s;
         for (Index i = 0; i <= iu; ++i) m_matT.coeffRef(i, i) -= s;
         shiftInfo.setConstant(Scalar(0.964));
       }
     }
   }
 }
References abs(), Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::coeffRef(), i, s, Eigen::PlainObjectBase< Derived >::setConstant(), and sqrt().
findSmallSubdiagEntry()
template<typename MatrixType > Index Eigen::RealSchur< MatrixType >::findSmallSubdiagEntry (Index iu, const Scalar & considerAsZero) inline private
Look for single small sub-diagonal element and returns its index
{
   using std::abs;
   Index res = iu;
   while (res > 0) {
     Scalar s = abs(m_matT.coeff(res - 1, res - 1)) + abs(m_matT.coeff(res, res));
     s = numext::maxi<Scalar>(s * NumTraits<Scalar>::epsilon(), considerAsZero);
     if (abs(m_matT.coeff(res, res - 1)) <= s) break;
     res--;
   }
   return res;
 }
References abs(), res, and s.
getMaxIterations()
template<typename MatrixType_ > Index Eigen::RealSchur< MatrixType_ >::getMaxIterations () inline
Returns the maximum number of iterations.
 { return m_maxIters; }
References Eigen::RealSchur< MatrixType_ >::m_maxIters.
Referenced by Eigen::EigenSolver< MatrixType_ >::getMaxIterations(), and schur().
info()
template<typename MatrixType_ > ComputationInfo Eigen::RealSchur< MatrixType_ >::info () const inline
Reports whether previous computation was successful.
Returns
Success if computation was successful, NoConvergence otherwise.
{
     eigen_assert(m_isInitialized && "RealSchur is not initialized.");
     return m_info;
   }
References eigen_assert, Eigen::RealSchur< MatrixType_ >::m_info, and Eigen::RealSchur< MatrixType_ >::m_isInitialized.
Referenced by schur().
initFrancisQRStep()
template<typename MatrixType > void Eigen::RealSchur< MatrixType >::initFrancisQRStep (Index il, Index iu, const Vector3s & shiftInfo, Index & im, Vector3s & firstHouseholderVector) inline private
Compute index im at which Francis QR step starts and the first Householder vector.
{
   using std::abs;
   Vector3s& v = firstHouseholderVector;  // alias to save typing
   for (im = iu - 2; im >= il; --im) {
     const Scalar Tmm = m_matT.coeff(im, im);
     const Scalar r = shiftInfo.coeff(0) - Tmm;
     const Scalar s = shiftInfo.coeff(1) - Tmm;
     v.coeffRef(0) = (r * s - shiftInfo.coeff(2)) / m_matT.coeff(im + 1, im) + m_matT.coeff(im, im + 1);
     v.coeffRef(1) = m_matT.coeff(im + 1, im + 1) - Tmm - r - s;
     v.coeffRef(2) = m_matT.coeff(im + 2, im + 1);
     if (im == il) {
       break;
     }
     const Scalar lhs = m_matT.coeff(im, im - 1) * (abs(v.coeff(1)) + abs(v.coeff(2)));
     const Scalar rhs = v.coeff(0) * (abs(m_matT.coeff(im - 1, im - 1)) + abs(Tmm) + abs(m_matT.coeff(im + 1, im + 1)));
     if (abs(lhs) < NumTraits<Scalar>::epsilon() * rhs) break;
   }
 }
References abs(), Eigen::PlainObjectBase< Derived >::coeff(), oomph::SarahBL::epsilon, UniformPSDSelfTest::r, s, and v.
matrixT()
template<typename MatrixType_ > const MatrixType& Eigen::RealSchur< MatrixType_ >::matrixT () const inline
Returns the quasi-triangular matrix in the Schur decomposition.
Returns
A const reference to the matrix T.
Precondition
Either the constructor RealSchur(const MatrixType&, bool) or the member function compute(const MatrixType&, bool) has been called before to compute the Schur decomposition of a matrix.
See also
RealSchur(const MatrixType&, bool) for an example
{
     eigen_assert(m_isInitialized && "RealSchur is not initialized.");
     return m_matT;
   }
References eigen_assert, Eigen::RealSchur< MatrixType_ >::m_isInitialized, and Eigen::RealSchur< MatrixType_ >::m_matT.
Referenced by schur(), and Eigen::DGMRES< MatrixType_, Preconditioner_ >::schurValues().
matrixU()
template<typename MatrixType_ > const MatrixType& Eigen::RealSchur< MatrixType_ >::matrixU () const inline
Returns the orthogonal matrix in the Schur decomposition.
Returns
A const reference to the matrix U.
Precondition
Either the constructor RealSchur(const MatrixType&, bool) or the member function compute(const MatrixType&, bool) has been called before to compute the Schur decomposition of a matrix, and computeU was set to true (the default value).
See also
RealSchur(const MatrixType&, bool) for an example
{
     eigen_assert(m_isInitialized && "RealSchur is not initialized.");
     eigen_assert(m_matUisUptodate && "The matrix U has not been computed during the RealSchur decomposition.");
     return m_matU;
   }
References eigen_assert, Eigen::RealSchur< MatrixType_ >::m_isInitialized, Eigen::RealSchur< MatrixType_ >::m_matU, and Eigen::RealSchur< MatrixType_ >::m_matUisUptodate.
Referenced by schur().
performFrancisQRStep()
template<typename MatrixType > void Eigen::RealSchur< MatrixType >::performFrancisQRStep (Index il, Index im, Index iu, bool computeU, const Vector3s & firstHouseholderVector, Scalar * workspace) inline private
Perform a Francis QR step involving rows il:iu and columns im:iu.
{
   eigen_assert(im >= il);
   eigen_assert(im <= iu - 2);
   const Index size = m_matT.cols();
   for (Index k = im; k <= iu - 2; ++k) {
     bool firstIteration = (k == im);
     Vector3s v;
     if (firstIteration)
       v = firstHouseholderVector;
     else
       v = m_matT.template block<3, 1>(k, k - 1);
     Scalar tau, beta;
     Matrix<Scalar, 2, 1> ess;
     v.makeHouseholder(ess, tau, beta);
     if (!numext::is_exactly_zero(beta))  // if v is not zero
     {
       if (firstIteration && k > il)
         m_matT.coeffRef(k, k - 1) = -m_matT.coeff(k, k - 1);
       else if (!firstIteration)
         m_matT.coeffRef(k, k - 1) = beta;
       // These Householder transformations form the O(n^3) part of the algorithm
       m_matT.block(k, k, 3, size - k).applyHouseholderOnTheLeft(ess, tau, workspace);
       m_matT.block(0, k, (std::min)(iu, k + 3) + 1, 3).applyHouseholderOnTheRight(ess, tau, workspace);
       if (computeU) m_matU.block(0, k, size, 3).applyHouseholderOnTheRight(ess, tau, workspace);
     }
   }
   Matrix<Scalar, 2, 1> v = m_matT.template block<2, 1>(iu - 1, iu - 2);
   Scalar tau, beta;
   Matrix<Scalar, 1, 1> ess;
   v.makeHouseholder(ess, tau, beta);
   if (!numext::is_exactly_zero(beta))  // if v is not zero
   {
     m_matT.coeffRef(iu - 1, iu - 2) = beta;
     m_matT.block(iu - 1, iu - 1, 2, size - iu + 1).applyHouseholderOnTheLeft(ess, tau, workspace);
     m_matT.block(0, iu - 1, iu + 1, 2).applyHouseholderOnTheRight(ess, tau, workspace);
     if (computeU) m_matU.block(0, iu - 1, size, 2).applyHouseholderOnTheRight(ess, tau, workspace);
   }
   // clean up pollution due to round-off errors
   for (Index i = im + 2; i <= iu; ++i) {
     m_matT.coeffRef(i, i - 2) = Scalar(0);
     if (i > im + 2) m_matT.coeffRef(i, i - 3) = Scalar(0);
   }
 }
References beta, eigen_assert, calibrate::ess, i, Eigen::numext::is_exactly_zero(), k, min, size, and v.
setMaxIterations()
template<typename MatrixType_ > RealSchur& Eigen::RealSchur< MatrixType_ >::setMaxIterations (Index maxIters) inline
Sets the maximum number of iterations allowed.
If not specified by the user, the maximum number of iterations is m_maxIterationsPerRow times the size of the matrix.
{
     m_maxIters = maxIters;
     return *this;
   }
References Eigen::RealSchur< MatrixType_ >::m_maxIters.
Referenced by schur(), and Eigen::EigenSolver< MatrixType_ >::setMaxIterations().
splitOffTwoRows()
template<typename MatrixType > void Eigen::RealSchur< MatrixType >::splitOffTwoRows (Index iu, bool computeU, const Scalar & exshift) inline private
Update T given that rows iu-1 and iu decouple from the rest.
{
   using std::abs;
   using std::sqrt;
   const Index size = m_matT.cols();
   // The eigenvalues of the 2x2 matrix [a b; c d] are
   // trace +/- sqrt(discr/4) where discr = tr^2 - 4*det, tr = a + d, det = ad - bc
   Scalar p = Scalar(0.5) * (m_matT.coeff(iu - 1, iu - 1) - m_matT.coeff(iu, iu));
   Scalar q = p * p + m_matT.coeff(iu, iu - 1) * m_matT.coeff(iu - 1, iu);  // q = tr^2 / 4 - det = discr/4
   m_matT.coeffRef(iu, iu) += exshift;
   m_matT.coeffRef(iu - 1, iu - 1) += exshift;
   if (q >= Scalar(0))  // Two real eigenvalues
   {
     Scalar z = sqrt(abs(q));
     JacobiRotation<Scalar> rot;
     if (p >= Scalar(0))
       rot.makeGivens(p + z, m_matT.coeff(iu, iu - 1));
     else
       rot.makeGivens(p - z, m_matT.coeff(iu, iu - 1));
     m_matT.rightCols(size - iu + 1).applyOnTheLeft(iu - 1, iu, rot.adjoint());
     m_matT.topRows(iu + 1).applyOnTheRight(iu - 1, iu, rot);
     m_matT.coeffRef(iu, iu - 1) = Scalar(0);
     if (computeU) m_matU.applyOnTheRight(iu - 1, iu, rot);
   }
   if (iu > 1) m_matT.coeffRef(iu - 1, iu - 2) = Scalar(0);
 }
References abs(), p, Eigen::numext::q, rot(), size, and sqrt().
Member Data Documentation
m_hess
template<typename MatrixType_ > HessenbergDecomposition<MatrixType> Eigen::RealSchur< MatrixType_ >::m_hess private
m_info
template<typename MatrixType_ > ComputationInfo Eigen::RealSchur< MatrixType_ >::m_info private
Referenced by Eigen::RealSchur< MatrixType_ >::info().
m_isInitialized
template<typename MatrixType_ > bool Eigen::RealSchur< MatrixType_ >::m_isInitialized private
Referenced by Eigen::RealSchur< MatrixType_ >::info(), Eigen::RealSchur< MatrixType_ >::matrixT(), and Eigen::RealSchur< MatrixType_ >::matrixU().
m_matT
template<typename MatrixType_ > MatrixType Eigen::RealSchur< MatrixType_ >::m_matT private
Referenced by Eigen::RealSchur< MatrixType_ >::matrixT().
m_matU
template<typename MatrixType_ > MatrixType Eigen::RealSchur< MatrixType_ >::m_matU private
Referenced by Eigen::RealSchur< MatrixType_ >::matrixU().
m_matUisUptodate
template<typename MatrixType_ > bool Eigen::RealSchur< MatrixType_ >::m_matUisUptodate private
Referenced by Eigen::RealSchur< MatrixType_ >::matrixU().
m_maxIterationsPerRow
template<typename MatrixType_ > const int Eigen::RealSchur< MatrixType_ >::m_maxIterationsPerRow = 40 static
Maximum number of iterations per row.
If not otherwise specified, the maximum number of iterations is this number times the size of the matrix. It is currently set to 40.
m_maxIters
template<typename MatrixType_ > Index Eigen::RealSchur< MatrixType_ >::m_maxIters private
Referenced by Eigen::RealSchur< MatrixType_ >::getMaxIterations(), and Eigen::RealSchur< MatrixType_ >::setMaxIterations().
m_workspaceVector
template<typename MatrixType_ > ColumnVectorType Eigen::RealSchur< MatrixType_ >::m_workspaceVector private
The documentation for this class was generated from the following file:
RealSchur.h