MercuryDPM: oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations Class Reference
oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations Class Reference
#include <time_harmonic_fourier_decomposed_linear_elasticity_elements.h>
Public Member Functions
TimeHarmonicFourierDecomposedLinearElasticityEquations ()
Constructor.
unsigned required_nvalue (const unsigned &n) const
Number of values required at node n.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void get_strain (const Vector< double > &s, DenseMatrix< std::complex< double >> &strain)
Get strain tensor.
void compute_norm (double &norm)
Compute norm of solution: square of the L2 norm.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact solution: r,z, u_r_real, u_z_real, ..., u_theta_imag.
void output (std::ostream &outfile)
Output: r,z, u_r_real, u_z_real, ..., u_theta_imag.
void output (std::ostream &outfile, const unsigned &n_plot)
Output: r,z, u_r_real, u_z_real, ..., u_theta_imag.
void output (FILE *file_pt)
C-style output: r,z, u_r_real, u_z_real, ..., u_theta_imag.
void output (FILE *file_pt, const unsigned &n_plot)
Output: r,z, u_r_real, u_z_real, ..., u_theta_imag.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Public Member Functions inherited from oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase
virtual std::complex< unsigned > u_index_time_harmonic_fourier_decomposed_linear_elasticity (const unsigned i) const
void interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity (const Vector< double > &s, Vector< std::complex< double >> &disp) const
Compute vector of FE interpolated displacement u at local coordinate s.
std::complex< double > interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity (const Vector< double > &s, const unsigned &i) const
TimeHarmonicFourierDecomposedLinearElasticityEquationsBase ()
const std::complex< double > & omega_sq () const
Access function for square of non-dim frequency.
std::complex< double > *& omega_sq_pt ()
Access function for square of non-dim frequency.
std::complex< double > *& youngs_modulus_pt ()
Return the pointer to Young's modulus.
std::complex< double > youngs_modulus () const
Access function to Young's modulus.
std::complex< double > & nu () const
Access function for Poisson's ratio.
std::complex< double > *& nu_pt ()
Access function for pointer to Poisson's ratio.
int & fourier_wavenumber () const
Access function for Fourier wavenumber.
int *& fourier_wavenumber_pt ()
Access function for pointer to Fourier wavenumber.
BodyForceFctPt & body_force_fct_pt ()
Access function: Pointer to body force function.
BodyForceFctPt body_force_fct_pt () const
Access function: Pointer to body force function (const version)
void body_force (const Vector< double > &x, Vector< std::complex< double >> &b) const
unsigned ndof_types () const
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Private Member Functions
virtual void fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Additional Inherited Members
Public Types inherited from oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase
typedef void(* BodyForceFctPt) (const Vector< double > &x, Vector< std::complex< double >> &b)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes inherited from oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase
std::complex< double > * Omega_sq_pt
Square of nondim frequency.
std::complex< double > * Youngs_modulus_pt
Pointer to the Young's modulus.
std::complex< double > * Nu_pt
Pointer to Poisson's ratio.
int * Fourier_wavenumber_pt
Pointer to Fourier wavenumber.
BodyForceFctPt Body_force_fct_pt
Pointer to body force function.
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Static Protected Attributes inherited from oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase
static std::complex< double > Default_omega_sq_value
Static default value for squared frequency.
static std::complex< double > Default_youngs_modulus_value
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// A class for elements that solve the Fourier decomposed (in cylindrical polars) equations of time-harmonic linear elasticity
Constructor & Destructor Documentation
TimeHarmonicFourierDecomposedLinearElasticityEquations()
oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::TimeHarmonicFourierDecomposedLinearElasticityEquations () inline
Constructor.
 {}
Member Function Documentation
compute_error()
void oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) virtual
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of displacement solution over element
Validate against exact solution Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Reimplemented from oomph::FiniteElement.
   {
     error = 0.0;
     norm = 0.0;
     // Vector of local coordinates
     Vector<double> s(2);
     // Vector for coordinates
     Vector<double> x(2);
     // Set the value of n_intpt
     unsigned n_intpt = this->integral_pt()->nweight();
     outfile << "ZONE" << std::endl;
     // Exact solution Vector (u_r_real, u_z_real, ..., u_theta_imag)
     Vector<double> exact_soln(6);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < 2; i++)
       {
         s[i] = this->integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = this->integral_pt()->weight(ipt);
       // Get jacobian of mapping
       double J = this->J_eulerian(s);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Get x position as Vector
       this->interpolated_x(s, x);
       // Get exact solution at this point
       (*exact_soln_pt)(x, exact_soln);
       // Displacement error
       for (unsigned i = 0; i < 3; i++)
       {
         norm += (exact_soln[i] * exact_soln[i] +
                  exact_soln[i + 3] * exact_soln[i + 3]) *
                 W;
         error +=
           ((exact_soln[i] -
             this
               ->interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity(
                 s, i)
               .real()) *
              (exact_soln[i] -
               this
                 ->interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity(
                   s, i)
                 .real()) +
            (exact_soln[i + 3] -
             this
               ->interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity(
                 s, i)
               .imag()) *
              (exact_soln[i + 3] -
               this
                 ->interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity(
                   s, i)
                 .imag())) *
           W;
       }
       // Output r,z coordinates
       for (unsigned i = 0; i < 2; i++)
       {
         outfile << x[i] << " ";
       }
       // Output ur_error, uz_error, uth_error
       for (unsigned i = 0; i < 3; i++)
       {
         outfile
           << exact_soln[i] -
                this
                  ->interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity(
                    s, i)
                  .real()
           << " ";
       }
       for (unsigned i = 0; i < 3; i++)
       {
         outfile
           << exact_soln[i + 3] -
                this
                  ->interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity(
                    s, i)
                  .imag()
           << " ";
       }
       outfile << std::endl;
     }
   }
References calibrate::error, ProblemParameters::exact_soln(), i, oomph::FiniteElement::integral_pt(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity(), oomph::FiniteElement::interpolated_x(), J, oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::Integral::nweight(), s, w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and plotDoE::x.
compute_norm()
void oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::compute_norm (double & norm) virtual
Compute norm of solution: square of the L2 norm.
Compute norm of the solution.
/////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////
Reimplemented from oomph::GeneralisedElement.
   {
     // Initialise
     norm = 0.0;
     // Vector of local coordinates
     Vector<double> s(2);
     // Vector for coordintes
     Vector<double> x(2);
     // Displacement vector
     Vector<std::complex<double>> disp(3);
     // Find out how many nodes there are in the element
     unsigned n_node = this->nnode();
     Shape psi(n_node);
     // Set the value of n_intpt
     unsigned n_intpt = this->integral_pt()->nweight();
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < 2; i++)
       {
         s[i] = this->integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = this->integral_pt()->weight(ipt);
       // Get jacobian of mapping
       double J = this->J_eulerian(s);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Get FE function value
       this->interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity(
         s, disp);
       // Add to  norm
       for (unsigned ii = 0; ii < 3; ii++)
       {
         norm += (disp[ii].real() * disp[ii].real() +
                  disp[ii].imag() * disp[ii].imag()) *
                 W;
       }
     }
   }
References i, oomph::FiniteElement::integral_pt(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity(), J, oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), s, w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and plotDoE::x.
fill_in_contribution_to_jacobian()
void oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
The jacobian is calculated by finite differences by default, We need only to take finite differences w.r.t. positional variables For this element
Reimplemented from oomph::FiniteElement.
     {
       // Add the contribution to the residuals
       this
         ->fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(
           residuals, jacobian, 1);
     }
fill_in_contribution_to_residuals()
void oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Return the residuals for the equations (the discretised principle of virtual displacements)
Reimplemented from oomph::GeneralisedElement.
     {
       fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(
         residuals, GeneralisedElement::Dummy_matrix, 0);
     }
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity().
fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity()
void oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) private virtual
Private helper function to compute residuals and (if requested via flag) also the Jacobian matrix.
//////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////// Compute the residuals for the Fourier decomposed (in cyl. polars) time harmonic linear elasticity equations in. Flag indicates if we want Jacobian too.
   {
     // Find out how many nodes there are
     unsigned n_node = this->nnode();
 #ifdef PARANOID
     // Find out how many positional dofs there are
     unsigned n_position_type = this->nnodal_position_type();
     if (n_position_type != 1)
     {
       throw OomphLibError("TimeHarmonicFourierDecomposedLinearElasticity is "
                           "not yet implemented for more than one position type",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Find the indices at which the local displacements are stored
     std::complex<unsigned> u_nodal_index[3];
     for (unsigned i = 0; i < 3; i++)
     {
       u_nodal_index[i] =
         this->u_index_time_harmonic_fourier_decomposed_linear_elasticity(i);
     }
     // Get (complex) elastic parameters
     std::complex<double> nu_local = this->nu();
     std::complex<double> youngs_modulus_local = this->youngs_modulus();
     // Obtain Lame parameters from Young's modulus and Poisson's ratio
     std::complex<double> lambda = youngs_modulus_local * nu_local /
                                   (1.0 + nu_local) / (1.0 - 2.0 * nu_local);
     std::complex<double> mu = youngs_modulus_local / 2.0 / (1.0 + nu_local);
     // Fourier wavenumber as double
     double n = double(this->fourier_wavenumber());
     // Square of non-dimensional frequency
     const std::complex<double> omega_sq = this->omega_sq();
     // Set up memory for the shape functions
     Shape psi(n_node);
     // Derivs only w.r.t. r [0] and z [1]
     DShape dpsidx(n_node, 2);
     // Set the value of Nintpt -- the number of integration points
     unsigned n_intpt = this->integral_pt()->nweight();
     // Set the vector to hold the local coordinates in the element
     Vector<double> s(2);
     // Integers to store the local equation numbers
     int local_eqn_real = 0, local_eqn_imag = 0, local_unknown_real = 0,
         local_unknown_imag = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign the values of s
       for (unsigned i = 0; i < 2; ++i)
       {
         s[i] = this->integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = this->integral_pt()->weight(ipt);
       // Call the derivatives of the shape functions (and get Jacobian)
       double J = this->dshape_eulerian_at_knot(ipt, psi, dpsidx);
       // Storage for Eulerian coordinates (r,z; initialised to zero)
       Vector<double> interpolated_x(2, 0.0);
       // Displacements u_r,u_z,u_theta
       Vector<std::complex<double>> interpolated_u(
         3, std::complex<double>(0.0, 0.0));
       // Calculate interpolated values of the derivatives w.r.t.
       // Eulerian coordinates
       DenseMatrix<std::complex<double>> interpolated_dudx(
         3, 2, std::complex<double>(0.0, 0.0));
       // Calculate displacements and derivatives
       for (unsigned l = 0; l < n_node; l++)
       {
         // Calculate the coordinates
         for (unsigned i = 0; i < 2; i++)
         {
           interpolated_x[i] += this->raw_nodal_position(l, i) * psi(l);
         }
         // Get the nodal displacements
         for (unsigned i = 0; i < 3; i++)
         {
           const std::complex<double> u_value = std::complex<double>(
             this->raw_nodal_value(l, u_nodal_index[i].real()),
             this->raw_nodal_value(l, u_nodal_index[i].imag()));
           interpolated_u[i] += u_value * psi(l);
           // Loop over derivative directions
           for (unsigned j = 0; j < 2; j++)
           {
             interpolated_dudx(i, j) += u_value * dpsidx(l, j);
           }
         }
       }
       // Get body force
       Vector<std::complex<double>> b(3);
       this->body_force(interpolated_x, b);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       //=====EQUATIONS OF FOURIER DECOMPOSED TIME HARMONIC LINEAR ELASTICITY
       //========
       // define shorthand notation for regularly-occurring terms
       double r = interpolated_x[0];
       double rsq = pow(r, 2);
       double nsq = pow(n, 2);
       const std::complex<double> I(0.0, 1.0);
       // r component of displacement
       std::complex<double> ur = interpolated_u[0];
       // z component of displacement
       std::complex<double> uz = interpolated_u[1];
       // theta component of displacement
       std::complex<double> uth = interpolated_u[2];
       // derivatives w.r.t. r and z:
       std::complex<double> durdr = interpolated_dudx(0, 0);
       std::complex<double> durdz = interpolated_dudx(0, 1);
       std::complex<double> duzdr = interpolated_dudx(1, 0);
       std::complex<double> duzdz = interpolated_dudx(1, 1);
       std::complex<double> duthdr = interpolated_dudx(2, 0);
       std::complex<double> duthdz = interpolated_dudx(2, 1);
       // storage for (complex) terms required for analytic Jacobian
       std::complex<double> G_r, G_z, G_theta;
       // Loop over the test functions, nodes of the element
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over the displacement components
         for (unsigned a = 0; a < 3; a++)
         {
           // Get the REAL equation number
           local_eqn_real = this->nodal_local_eqn(l, u_nodal_index[a].real());
           /*IF it's not a boundary condition*/
           if (local_eqn_real >= 0)
           {
             // Acceleration and body force
             residuals[local_eqn_real] +=
               (-omega_sq.real() * interpolated_u[a].real() +
                omega_sq.imag() * interpolated_u[a].imag() - b[a].real()) *
               psi(l) * r * W;
             // Three components of the stress divergence term:
             // a=0: r; a=1: z; a=2: theta
             // Real part of r-equation
             if (a == 0)
             {
               residuals[local_eqn_real] +=
                 (mu.real() *
                    (2.0 * durdr.real() * dpsidx(l, 0) +
                     n * psi(l) / r *
                       (n * ur.real() / r + duthdr.imag() - uth.imag() / r) +
                     dpsidx(l, 1) * (durdz.real() + duzdr.real()) +
                     2.0 * psi(l) / pow(r, 2) * (ur.real() - n * uth.imag())) +
                  mu.imag() *
                    (-2.0 * durdr.imag() * dpsidx(l, 0) +
                     n * psi(l) / r *
                       (-n * ur.imag() / r + duthdr.real() - uth.real() / r) -
                     dpsidx(l, 1) * (durdz.imag() + duzdr.imag()) -
                     2.0 * psi(l) / pow(r, 2) * (ur.imag() + n * uth.real())) +
                  lambda.real() *
                    (durdr.real() + ur.real() / r - n / r * uth.imag() +
                     duzdz.real()) *
                    (dpsidx(l, 0) + psi(l) / r) -
                  lambda.imag() *
                    (durdr.imag() + ur.imag() / r + n / r * uth.real() +
                     duzdz.imag()) *
                    (dpsidx(l, 0) + psi(l) / r)) *
                 r * W;
             }
             // Real part of z-equation
             else if (a == 1)
             {
               residuals[local_eqn_real] +=
                 (mu.real() *
                    (dpsidx(l, 0) * (durdz.real() + duzdr.real()) +
                     n * psi(l) / r * (n * uz.real() / r + duthdz.imag()) +
                     2.0 * duzdz.real() * dpsidx(l, 1)) +
                  mu.imag() *
                    (-dpsidx(l, 0) * (durdz.imag() + duzdr.imag()) +
                     n * psi(l) / r * (-n * uz.imag() / r + duthdz.real()) -
                     2.0 * duzdz.imag() * dpsidx(l, 1)) +
                  lambda.real() *
                    (durdr.real() + ur.real() / r - n / r * uth.imag() +
                     duzdz.real()) *
                    dpsidx(l, 1) -
                  lambda.imag() *
                    (durdr.imag() + ur.imag() / r + n / r * uth.real() +
                     duzdz.imag()) *
                    dpsidx(l, 1)) *
                 r * W;
             }
             // Real part of theta-equation
             else if (a == 2)
             {
               residuals[local_eqn_real] +=
                 (mu.real() *
                    ((duthdr.real() - uth.real() / r - n * ur.imag() / r) *
                       (dpsidx(l, 0) - psi(l) / r) +
                     2.0 * n * psi(l) / pow(r, 2) *
                       (n * uth.real() + ur.imag()) +
                     dpsidx(l, 1) * (duthdz.real() - n / r * uz.imag())) +
                  mu.imag() *
                    ((-duthdr.imag() + uth.imag() / r - n * ur.real() / r) *
                       (dpsidx(l, 0) - psi(l) / r) +
                     2.0 * n * psi(l) / pow(r, 2) *
                       (-n * uth.imag() + ur.real()) +
                     dpsidx(l, 1) * (-duthdz.imag() - n / r * uz.real())) +
                  lambda.real() *
                    (durdr.imag() + ur.imag() / r + n / r * uth.real() +
                     duzdz.imag()) *
                    n * psi(l) / r +
                  lambda.imag() *
                    (durdr.real() + ur.real() / r - n / r * uth.imag() +
                     duzdz.real()) *
                    n * psi(l) / r) *
                 r * W;
             }
             // error: a should be 0, 1 or 2
             else
             {
               throw OomphLibError("a should equal 0, 1 or 2",
                                   OOMPH_CURRENT_FUNCTION,
                                   OOMPH_EXCEPTION_LOCATION);
             }
             // Jacobian entries
             if (flag)
             {
               // Loop over the displacement basis functions again
               for (unsigned l2 = 0; l2 < n_node; l2++)
               {
                 // define complex terms used to obtain entries of current row in
                 // the Jacobian:
                 // terms for rows of Jacobian matrix corresponding to r-equation
                 if (a == 0)
                 {
                   G_r = (mu * (2.0 * dpsidx(l2, 0) * dpsidx(l, 0) +
                                (nsq + 2.0) / rsq * psi(l2) * psi(l) +
                                dpsidx(l2, 1) * dpsidx(l, 1)) +
                          lambda * (dpsidx(l2, 0) + psi(l2) / r) *
                            (dpsidx(l, 0) + psi(l) / r) -
                          omega_sq * psi(l2) * psi(l)) *
                         r * W;
                   G_z = (mu * dpsidx(l2, 0) * dpsidx(l, 1) +
                          lambda * dpsidx(l2, 1) * (dpsidx(l, 0) + psi(l) / r)) *
                         r * W;
                   G_theta = (-I * (mu * (n / r * dpsidx(l2, 0) * psi(l) -
                                          3.0 * n / rsq * psi(l2) * psi(l)) -
                                    lambda * n / r * psi(l2) *
                                      (dpsidx(l, 0) + psi(l) / r))) *
                             r * W;
                 }
                 // terms for rows of Jacobian matrix corresponding to z-equation
                 else if (a == 1)
                 {
                   G_r =
                     (mu * dpsidx(l2, 1) * dpsidx(l, 0) +
                      lambda * (dpsidx(l2, 0) + psi(l2) / r) * dpsidx(l, 1)) *
                     r * W;
                   G_z = (mu * (dpsidx(l2, 0) * dpsidx(l, 0) +
                                nsq / rsq * psi(l2) * psi(l) +
                                2.0 * dpsidx(l2, 1) * dpsidx(l, 1)) +
                          lambda * dpsidx(l2, 1) * dpsidx(l, 1) -
                          omega_sq * psi(l2) * psi(l)) *
                         r * W;
                   G_theta = (-I * (mu * n / r * dpsidx(l2, 1) * psi(l) -
                                    lambda * n / r * dpsidx(l, 1) * psi(l2))) *
                             r * W;
                 }
                 // terms for rows of Jacobian matrix corresponding to
                 // theta-equation
                 else if (a == 2)
                 {
                   G_r = (-I * (mu * (-n / r * psi(l2) * dpsidx(l, 0) +
                                      3.0 * n / rsq * psi(l2) * psi(l)) +
                                lambda * n / r * (dpsidx(l2, 0) + psi(l2) / r) *
                                  psi(l))) *
                         r * W;
                   G_z = (-I * (-mu * n / r * psi(l2) * dpsidx(l, 1) +
                                lambda * n / r * dpsidx(l2, 1) * psi(l))) *
                         r * W;
                   G_theta = (mu * ((dpsidx(l2, 0) - psi(l2) / r) *
                                      (dpsidx(l, 0) - psi(l) / r) +
                                    2.0 * nsq / rsq * psi(l2) * psi(l) +
                                    dpsidx(l2, 1) * dpsidx(l, 1)) +
                              lambda * nsq / rsq * psi(l2) * psi(l) -
                              omega_sq * psi(l2) * psi(l)) *
                             r * W;
                 }
                 // Loop over the displacement components
                 for (unsigned c = 0; c < 3; c++)
                 {
                   // Get real and imaginary parts of local unknown
                   local_unknown_real =
                     this->nodal_local_eqn(l2, u_nodal_index[c].real());
                   local_unknown_imag =
                     this->nodal_local_eqn(l2, u_nodal_index[c].imag());
                   // If the real part of the local unknown is not pinned
                   if (local_unknown_real >= 0)
                   {
                     if (c == 0)
                     {
                       jacobian(local_eqn_real, local_unknown_real) +=
                         G_r.real();
                     }
                     else if (c == 1)
                     {
                       jacobian(local_eqn_real, local_unknown_real) +=
                         G_z.real();
                     }
                     else if (c == 2)
                     {
                       jacobian(local_eqn_real, local_unknown_real) +=
                         G_theta.real();
                     }
                   }
                   // If the imaginary part of the local unknown is not pinned
                   if (local_unknown_imag >= 0)
                   {
                     if (c == 0)
                     {
                       jacobian(local_eqn_real, local_unknown_imag) +=
                         -G_r.imag();
                     }
                     else if (c == 1)
                     {
                       jacobian(local_eqn_real, local_unknown_imag) +=
                         -G_z.imag();
                     }
                     else if (c == 2)
                     {
                       jacobian(local_eqn_real, local_unknown_imag) +=
                         -G_theta.imag();
                     }
                   }
                 }
               }
             } // End of jacobian calculation
           } // End of if not boundary condition for real eqn
           // Get the IMAG equation number
           local_eqn_imag = this->nodal_local_eqn(l, u_nodal_index[a].imag());
           /*IF it's not a boundary condition*/
           if (local_eqn_imag >= 0)
           {
             // Acceleration and body force
             residuals[local_eqn_imag] +=
               (-omega_sq.real() * interpolated_u[a].imag() -
                omega_sq.imag() * interpolated_u[a].real() - b[a].imag()) *
               psi(l) * r * W;
             // Three components of the stress divergence term:
             // a=0: r; a=1: z; a=2: theta
             // Imag part of r-equation
             if (a == 0)
             {
               residuals[local_eqn_imag] +=
                 (mu.real() *
                    (2 * durdr.imag() * dpsidx(l, 0) +
                     n * psi(l) / r *
                       (n * ur.imag() / r - duthdr.real() + uth.real() / r) +
                     dpsidx(l, 1) * (durdz.imag() + duzdr.imag()) +
                     2 * psi(l) / pow(r, 2) * (ur.imag() + n * uth.real())) +
                  mu.imag() *
                    (2.0 * durdr.real() * dpsidx(l, 0) +
                     n * psi(l) / r *
                       (n * ur.real() / r + duthdr.imag() - uth.imag() / r) +
                     dpsidx(l, 1) * (durdz.real() + duzdr.real()) +
                     2.0 * psi(l) / pow(r, 2) * (ur.real() - n * uth.imag())) +
                  lambda.real() *
                    (durdr.imag() + ur.imag() / r + n / r * uth.real() +
                     duzdz.imag()) *
                    (dpsidx(l, 0) + psi(l) / r) +
                  lambda.imag() *
                    (durdr.real() + ur.real() / r - n / r * uth.imag() +
                     duzdz.real()) *
                    (dpsidx(l, 0) + psi(l) / r)) *
                 r * W;
             }
             // Imag part of z-equation
             else if (a == 1)
             {
               residuals[local_eqn_imag] +=
                 (mu.real() *
                    (dpsidx(l, 0) * (durdz.imag() + duzdr.imag()) +
                     n * psi(l) / r * (n * uz.imag() / r - duthdz.real()) +
                     2 * duzdz.imag() * dpsidx(l, 1)) +
                  mu.imag() *
                    (dpsidx(l, 0) * (durdz.real() + duzdr.real()) +
                     n * psi(l) / r * (n * uz.real() / r + duthdz.imag()) +
                     2.0 * duzdz.real() * dpsidx(l, 1)) +
                  lambda.real() *
                    (durdr.imag() + ur.imag() / r + n / r * uth.real() +
                     duzdz.imag()) *
                    dpsidx(l, 1) +
                  lambda.imag() *
                    (durdr.real() + ur.real() / r - n / r * uth.imag() +
                     duzdz.real()) *
                    dpsidx(l, 1)) *
                 r * W;
             }
             // Imag part of theta-equation
             else if (a == 2)
             {
               residuals[local_eqn_imag] +=
                 (mu.real() *
                    ((duthdr.imag() - uth.imag() / r + n * ur.real() / r) *
                       (dpsidx(l, 0) - psi(l) / r) +
                     2.0 * n * psi(l) / pow(r, 2.) *
                       (n * uth.imag() - ur.real()) +
                     dpsidx(l, 1) * (duthdz.imag() + n / r * uz.real())) +
                  mu.imag() *
                    ((duthdr.real() - uth.real() / r - n * ur.imag() / r) *
                       (dpsidx(l, 0) - psi(l) / r) +
                     2.0 * n * psi(l) / pow(r, 2) *
                       (n * uth.real() + ur.imag()) +
                     dpsidx(l, 1) * (duthdz.real() - n / r * uz.imag())) +
                  lambda.real() *
                    (-durdr.real() - ur.real() / r + n / r * uth.imag() -
                     duzdz.real()) *
                    n * psi(l) / r +
                  lambda.imag() *
                    (durdr.imag() + ur.imag() / r + n / r * uth.real() +
                     duzdz.imag()) *
                    n * psi(l) / r) *
                 r * W;
             }
             // error: a should be 0, 1 or 2
             else
             {
               throw OomphLibError("a should equal 0, 1 or 2",
                                   OOMPH_CURRENT_FUNCTION,
                                   OOMPH_EXCEPTION_LOCATION);
             }
             // Jacobian entries
             if (flag)
             {
               // Loop over the displacement basis functions again
               for (unsigned l2 = 0; l2 < n_node; l2++)
               {
                 // define complex terms used to obtain entries of current row in
                 // the Jacobian:
                 // terms for rows of Jacobian matrix corresponding to r-equation
                 if (a == 0)
                 {
                   G_r = (mu * (2.0 * dpsidx(l2, 0) * dpsidx(l, 0) +
                                (nsq + 2.0) / rsq * psi(l2) * psi(l) +
                                dpsidx(l2, 1) * dpsidx(l, 1)) +
                          lambda * (dpsidx(l2, 0) + psi(l2) / r) *
                            (dpsidx(l, 0) + psi(l) / r) -
                          omega_sq * psi(l2) * psi(l)) *
                         r * W;
                   G_z = (mu * dpsidx(l2, 0) * dpsidx(l, 1) +
                          lambda * dpsidx(l2, 1) * (dpsidx(l, 0) + psi(l) / r)) *
                         r * W;
                   G_theta = (-I * (mu * (n / r * dpsidx(l2, 0) * psi(l) -
                                          3.0 * n / rsq * psi(l2) * psi(l)) -
                                    lambda * n / r * psi(l2) *
                                      (dpsidx(l, 0) + psi(l) / r))) *
                             r * W;
                 }
                 // terms for rows of Jacobian matrix corresponding to z-equation
                 else if (a == 1)
                 {
                   G_r =
                     (mu * dpsidx(l2, 1) * dpsidx(l, 0) +
                      lambda * (dpsidx(l2, 0) + psi(l2) / r) * dpsidx(l, 1)) *
                     r * W;
                   G_z = (mu * (dpsidx(l2, 0) * dpsidx(l, 0) +
                                nsq / rsq * psi(l2) * psi(l) +
                                2.0 * dpsidx(l2, 1) * dpsidx(l, 1)) +
                          lambda * dpsidx(l2, 1) * dpsidx(l, 1) -
                          omega_sq * psi(l2) * psi(l)) *
                         r * W;
                   G_theta = (-I * (mu * n / r * dpsidx(l2, 1) * psi(l) -
                                    lambda * n / r * dpsidx(l, 1) * psi(l2))) *
                             r * W;
                 }
                 // terms for rows of Jacobian matrix corresponding to
                 // theta-equation
                 else if (a == 2)
                 {
                   G_r = (-I * (mu * (-n / r * psi(l2) * dpsidx(l, 0) +
                                      3.0 * n / rsq * psi(l2) * psi(l)) +
                                lambda * n / r * (dpsidx(l2, 0) + psi(l2) / r) *
                                  psi(l))) *
                         r * W;
                   G_z = (-I * (-mu * n / r * psi(l2) * dpsidx(l, 1) +
                                lambda * n / r * dpsidx(l2, 1) * psi(l))) *
                         r * W;
                   G_theta = (mu * ((dpsidx(l2, 0) - psi(l2) / r) *
                                      (dpsidx(l, 0) - psi(l) / r) +
                                    2.0 * nsq / rsq * psi(l2) * psi(l) +
                                    dpsidx(l2, 1) * dpsidx(l, 1)) +
                              lambda * nsq / rsq * psi(l2) * psi(l) -
                              omega_sq * psi(l2) * psi(l)) *
                             r * W;
                 }
                 // Loop over the displacement components
                 for (unsigned c = 0; c < 3; c++)
                 {
                   // Get real and imaginary parts of local unknown
                   local_unknown_real =
                     this->nodal_local_eqn(l2, u_nodal_index[c].real());
                   local_unknown_imag =
                     this->nodal_local_eqn(l2, u_nodal_index[c].imag());
                   // If the real part of the local unknown is not pinned
                   if (local_unknown_real >= 0)
                   {
                     if (c == 0)
                     {
                       jacobian(local_eqn_imag, local_unknown_real) +=
                         G_r.imag();
                     }
                     else if (c == 1)
                     {
                       jacobian(local_eqn_imag, local_unknown_real) +=
                         G_z.imag();
                     }
                     else if (c == 2)
                     {
                       jacobian(local_eqn_imag, local_unknown_real) +=
                         G_theta.imag();
                     }
                   }
                   // If the imaginary part of the local unknown is not pinned
                   if (local_unknown_imag >= 0)
                   {
                     if (c == 0)
                     {
                       jacobian(local_eqn_imag, local_unknown_imag) +=
                         G_r.real();
                     }
                     else if (c == 1)
                     {
                       jacobian(local_eqn_imag, local_unknown_imag) +=
                         G_z.real();
                     }
                     else if (c == 2)
                     {
                       jacobian(local_eqn_imag, local_unknown_imag) +=
                         G_theta.real();
                     }
                   }
                 }
               }
             } // End of jacobian calculation
           } // End of if not boundary condition for imag eqn
         } // End of loop over coordinate directions
       } // End of loop over shape functions
     } // End of loop over integration points
   }
References a, b, oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::body_force(), calibrate::c, oomph::FiniteElement::dshape_eulerian_at_knot(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::fourier_wavenumber(), i, I, imag(), oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), J, j, oomph::Integral::knot(), lambda, Global_Parameters::mu, n, oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::nu(), oomph::Integral::nweight(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::omega_sq(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, Eigen::bfloat16_impl::pow(), UniformPSDSelfTest::r, oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), s, oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::u_index_time_harmonic_fourier_decomposed_linear_elasticity(), w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::youngs_modulus().
Referenced by fill_in_contribution_to_residuals().
get_strain()
void oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::get_strain (const Vector< double > & s, DenseMatrix< std::complex< double >> & strain)
Get strain tensor.
   {
     // Find out how many nodes there are
     unsigned n_node = this->nnode();
 #ifdef PARANOID
     // Find out how many positional dofs there are
     unsigned n_position_type = this->nnodal_position_type();
     if (n_position_type != 1)
     {
       throw OomphLibError("TimeHarmonicFourierDecomposedLinearElasticity is "
                           "not yet implemented for more than one position type",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Find the indices at which the local displacements are stored
     std::complex<unsigned> u_nodal_index[3];
     for (unsigned i = 0; i < 3; i++)
     {
       u_nodal_index[i] =
         this->u_index_time_harmonic_fourier_decomposed_linear_elasticity(i);
     }
     // Fourier wavenumber as double
     double n = double(this->fourier_wavenumber());
     // Set up memory for the shape functions
     Shape psi(n_node);
     // Derivs only w.r.t. r [0] and z [1]
     DShape dpsidx(n_node, 2);
     // Call the derivatives of the shape functions (ignore Jacobian)
     this->dshape_eulerian(s, psi, dpsidx);
     // Storage for Eulerian coordinates (r,z; initialised to zero)
     Vector<double> interpolated_x(2, 0.0);
     // Displacements u_r,u_z,u_theta
     Vector<std::complex<double>> interpolated_u(3,
                                                 std::complex<double>(0.0, 0.0));
     // Calculate interpolated values of the derivatives w.r.t.
     // Eulerian coordinates
     DenseMatrix<std::complex<double>> interpolated_dudx(
       3, 2, std::complex<double>(0.0, 0.0));
     // Calculate displacements and derivatives
     for (unsigned l = 0; l < n_node; l++)
     {
       // Calculate the coordinates
       for (unsigned i = 0; i < 2; i++)
       {
         interpolated_x[i] += this->nodal_position(l, i) * psi(l);
       }
       // Get the nodal displacements
       for (unsigned i = 0; i < 3; i++)
       {
         const std::complex<double> u_value =
           std::complex<double>(this->nodal_value(l, u_nodal_index[i].real()),
                                this->nodal_value(l, u_nodal_index[i].imag()));
         interpolated_u[i] += u_value * psi(l);
         // Loop over derivative directions
         for (unsigned j = 0; j < 2; j++)
         {
           interpolated_dudx(i, j) += u_value * dpsidx(l, j);
         }
       }
     }
     // define shorthand notation for regularly-occurring terms
     double r = interpolated_x[0];
     const std::complex<double> I(0.0, 1.0);
     // r component of displacement
     std::complex<double> ur = interpolated_u[0];
     // z component of displacement
     std::complex<double> uz = interpolated_u[1];
     // theta component of displacement
     std::complex<double> uth = interpolated_u[2];
     // derivatives w.r.t. r and z:
     std::complex<double> durdr = interpolated_dudx(0, 0);
     std::complex<double> durdz = interpolated_dudx(0, 1);
     std::complex<double> duzdr = interpolated_dudx(1, 0);
     std::complex<double> duzdz = interpolated_dudx(1, 1);
     std::complex<double> duthdr = interpolated_dudx(2, 0);
     std::complex<double> duthdz = interpolated_dudx(2, 1);
     strain(0, 0) = durdr;
     strain(2, 2) = I * double(n) * uth / r + ur / r;
     strain(1, 1) = duzdz;
     strain(0, 2) = 0.5 * (I * double(n) * ur / r - uth / r + duthdr);
     strain(2, 0) = 0.5 * (I * double(n) * ur / r - uth / r + duthdr);
     strain(0, 1) = 0.5 * (durdz + duzdr);
     strain(1, 0) = 0.5 * (durdz + duzdr);
     strain(2, 1) = 0.5 * (duthdz + I * double(n) * uz / r);
     strain(1, 2) = 0.5 * (duthdz + I * double(n) * uz / r);
   }
References oomph::FiniteElement::dshape_eulerian(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::fourier_wavenumber(), i, I, imag(), oomph::FiniteElement::interpolated_x(), j, n, oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, UniformPSDSelfTest::r, and oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::u_index_time_harmonic_fourier_decomposed_linear_elasticity().
Referenced by oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >::get_Z2_flux().
output() [1/4]
void oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output (FILE * file_pt) inline virtual
C-style output: r,z, u_r_real, u_z_real, ..., u_theta_imag.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, and oomph::QTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >.
     {
       unsigned n_plot = 5;
       output(file_pt, n_plot);
     }
References output().
output() [2/4]
void oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output (FILE * file_pt, const unsigned & n_plot) virtual
Output: r,z, u_r_real, u_z_real, ..., u_theta_imag.
C-style output:r,z, u_r_real, u_z_real, ..., u_theta_imag.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, and oomph::QTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >.
   {
     // Vector of local coordinates
     Vector<double> s(2);
     // Tecplot header info
     fprintf(file_pt, "%s", this->tecplot_zone_string(nplot).c_str());
     // Loop over plot points
     unsigned num_plot_points = this->nplot_points(nplot);
     for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       this->get_s_plot(iplot, nplot, s);
       // Coordinates
       for (unsigned i = 0; i < 2; i++)
       {
         fprintf(file_pt, "%g ", this->interpolated_x(s, i));
       }
       // Displacement
       for (unsigned i = 0; i < 3; i++)
       {
         fprintf(
           file_pt,
           "%g ",
           this
             ->interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity(
               s, i)
             .real());
       }
       for (unsigned i = 0; i < 3; i++)
       {
         fprintf(
           file_pt,
           "%g ",
           this
             ->interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity(
               s, i)
             .imag());
       }
     }
     fprintf(file_pt, "\n");
     // Write tecplot footer (e.g. FE connectivity lists)
     this->write_tecplot_zone_footer(file_pt, nplot);
   }
References oomph::FiniteElement::get_s_plot(), i, imag(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [3/4]
void oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output (std::ostream & outfile) inline virtual
Output: r,z, u_r_real, u_z_real, ..., u_theta_imag.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, and oomph::QTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >.
     {
       unsigned n_plot = 5;
       output(outfile, n_plot);
     }
Referenced by output(), oomph::QTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >::output(), and oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >::output().
output() [4/4]
void oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output (std::ostream & outfile, const unsigned & n_plot) virtual
Output: r,z, u_r_real, u_z_real, ..., u_theta_imag.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, and oomph::QTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >.
   {
     // Set output Vector
     Vector<double> s(2);
     Vector<double> x(2);
     Vector<std::complex<double>> u(3);
     // Tecplot header info
     outfile << this->tecplot_zone_string(nplot);
     // Loop over plot points
     unsigned num_plot_points = this->nplot_points(nplot);
     for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       this->get_s_plot(iplot, nplot, s);
       // Get Eulerian coordinates and displacements
       this->interpolated_x(s, x);
       this->interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity(
         s, u);
       // Output the r,z,..
       for (unsigned i = 0; i < 2; i++)
       {
         outfile << x[i] << " ";
       }
       // Output real part of displacement
       for (unsigned i = 0; i < 3; i++)
       {
         outfile << u[i].real() << " ";
       }
       // Output imag part of displacement
       for (unsigned i = 0; i < 3; i++)
       {
         outfile << u[i].imag() << " ";
       }
       outfile << std::endl;
     }
     // Write tecplot footer (e.g. FE connectivity lists)
     this->write_tecplot_zone_footer(outfile, nplot);
   }
References oomph::FiniteElement::get_s_plot(), i, oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), oomph::FiniteElement::write_tecplot_zone_footer(), and plotDoE::x.
output_fct()
void oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) virtual
Output exact solution: r,z, u_r_real, u_z_real, ..., u_theta_imag.
Output exact solution r,z, u_r_real, u_z_real, ..., u_theta_imag.
Reimplemented from oomph::FiniteElement.
   {
     // Vector of local coordinates
     Vector<double> s(2);
     // Vector for coordintes
     Vector<double> x(2);
     // Tecplot header info
     outfile << this->tecplot_zone_string(nplot);
     // Exact solution Vector
     Vector<double> exact_soln(6);
     // Loop over plot points
     unsigned num_plot_points = this->nplot_points(nplot);
     for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       this->get_s_plot(iplot, nplot, s);
       // Get x position as Vector
       this->interpolated_x(s, x);
       // Get exact solution at this point
       (*exact_soln_pt)(x, exact_soln);
       // Output r,z,...,u_exact,...
       for (unsigned i = 0; i < 2; i++)
       {
         outfile << x[i] << " ";
       }
       for (unsigned i = 0; i < 6; i++)
       {
         outfile << exact_soln[i] << " ";
       }
       outfile << std::endl;
     }
     // Write tecplot footer (e.g. FE connectivity lists)
     this->write_tecplot_zone_footer(outfile, nplot);
   }
References ProblemParameters::exact_soln(), oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), oomph::FiniteElement::write_tecplot_zone_footer(), and plotDoE::x.
required_nvalue()
unsigned oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::required_nvalue (const unsigned & n) const inline virtual
Number of values required at node n.
Reimplemented from oomph::FiniteElement.
     {
       return 6;
     }
The documentation for this class was generated from the following files:
time_harmonic_fourier_decomposed_linear_elasticity_elements.h
time_harmonic_fourier_decomposed_linear_elasticity_elements.cc