MercuryDPM: hp_adaptive_driven_cavity.cc File Reference
navier_stokes/hp_adaptive_driven_cavity/hp_adaptive_driven_cavity.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "meshes/simple_rectangular_quadmesh.h"
Classes
class SimpleRefineableRectangularQuadMesh< ELEMENT >
class PRefineableDrivenCavityProblem< ELEMENT >
Namespaces
Global_Physical_Variables
Global variables.
Functions
int main (int argc, char **argv)
Driver for RefineableDrivenCavity test problem.
Function Documentation
main()
int main (int argc , char ** argv)
Driver for RefineableDrivenCavity test problem.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Set output directory
  DocInfo doc_info;
  doc_info.set_directory("RESLT");
  // Solve problem with hp-refineable Crouzeix Raviart elements
  //-----------------------------------------------------------
  // Build problem
  PRefineableDrivenCavityProblem<PRefineableQCrouzeixRaviartElement<2> > problem;
  cout << "\n\n\nProblem self-test ";
  if (problem.self_test()==0)
   {
    cout << "passed: Problem can be solved." << std::endl;
   }
  else
   {
    throw OomphLibError("Self test failed",
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
   }
  if(CommandLineArgs::Argc==1)
   {
    problem.p_adapt();
    problem.newton_solve();
    doc_info.number()=1;
    problem.doc_solution(doc_info);
    problem.adapt();
    problem.newton_solve();
    doc_info.number()=2;
    problem.doc_solution(doc_info);
    problem.p_adapt();
    problem.newton_solve();
    doc_info.number()=3;
    problem.doc_solution(doc_info);
    problem.adapt();
    problem.newton_solve();
    doc_info.number()=4;
    problem.doc_solution(doc_info);
    problem.p_adapt();
    problem.newton_solve();
    doc_info.number()=5;
    problem.doc_solution(doc_info);
    problem.adapt();
    problem.newton_solve();
    doc_info.number()=6;
    problem.doc_solution(doc_info);
    problem.p_adapt();
    problem.newton_solve();
    doc_info.number()=7;
    problem.doc_solution(doc_info);
    problem.adapt();
    problem.newton_solve();
    doc_info.number()=8;
    problem.doc_solution(doc_info);
   }
  // Validation run
  else
   {
    problem.refine_uniformly();
    problem.refine_uniformly();
    problem.newton_solve();
    doc_info.number()=1;
    problem.doc_solution(doc_info);
    problem.p_adapt();
    problem.newton_solve();
    doc_info.number()=2;
    problem.doc_solution(doc_info);
    problem.adapt();
    problem.newton_solve();
    doc_info.number()=3;
    problem.doc_solution(doc_info);
    problem.p_adapt();
    problem.newton_solve();
    doc_info.number()=4;
    problem.doc_solution(doc_info);
   }
    // Count hanging nodes
  //cout << "Hanging nodes:" << endl;
  unsigned num_hang=0;
  for (unsigned n=0; n<problem.mesh_pt()->nnode(); n++)
   {
    if (problem.mesh_pt()->node_pt(n)->is_hanging())
     {
      /*
      cout << "  node " << n << " is hanging... at  ("
           << problem.mesh_pt()->node_pt(n)->x(0) << ", "
           << problem.mesh_pt()->node_pt(n)->x(1) << ")" << endl;
      HangInfo* hang_pt = problem.mesh_pt()->node_pt(n)->hanging_pt();
      cout << "    Nmaster = " << hang_pt->nmaster() << endl;
      double totweight = 0.0;
      for (unsigned nm=0; nm<hang_pt->nmaster(); nm++)
       {
        cout << "    master node:  x = (" << hang_pt->master_node_pt(nm)->x(0)
             << ", " << hang_pt->master_node_pt(nm)->x(1) << ")  w = "
             << hang_pt->master_weight(nm) << endl;
        totweight += hang_pt->master_weight(nm);
       }
      cout << "    Total weights = " << totweight << endl;
      */
      num_hang++;
     }
   }
  cout << "There were "<<num_hang<<" hanging nodes." << endl;
  // Step number
  doc_info.number()=0;
  //Output solution
  problem.doc_solution(doc_info);
 } // end_of_main
References oomph::CommandLineArgs::Argc, n, oomph::DocInfo::number(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, problem, oomph::DocInfo::set_directory(), and Flag_definition::setup().