MercuryDPM: oomph::PressureBasedSolidLSCPreconditioner Class Reference
oomph::PressureBasedSolidLSCPreconditioner Class Reference
#include <solid_preconditioners.h>
Public Member Functions
PressureBasedSolidLSCPreconditioner ()
Constructor - sets defaults for control flags.
~PressureBasedSolidLSCPreconditioner ()
Destructor.
PressureBasedSolidLSCPreconditioner (const PressureBasedSolidLSCPreconditioner &)=delete
Broken copy constructor.
void setup ()
Broken assignment operator.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Apply preconditioner to Vector r.
void set_solid_mesh (Mesh *mesh_pt)
void enable_p_matrix_scaling ()
void disable_p_matrix_scaling ()
bool is_p_matrix_using_scaling () const
void set_p_preconditioner (Preconditioner *new_p_preconditioner_pt)
Function to set a new pressure matrix preconditioner (inexact solver)
void set_p_superlu_preconditioner ()
void set_f_preconditioner (Preconditioner *new_f_preconditioner_pt)
Function to set a new momentum matrix preconditioner (inexact solver)
void set_f_superlu_preconditioner ()
void enable_doc_time ()
Enable documentation of time.
void disable_doc_time ()
Disable documentation of time.
void enable_form_BFBt_product ()
void disable_form_BFBt_product ()
void clean_up_memory ()
Helper function to delete preconditioner data.
Public Member Functions inherited from oomph::BlockPreconditioner< CRDoubleMatrix >
BlockPreconditioner ()
Constructor.
BlockPreconditioner (const BlockPreconditioner &)=delete
Broken copy constructor.
virtual ~BlockPreconditioner ()
Destructor.
void operator= (const BlockPreconditioner &)=delete
Broken assignment operator.
CRDoubleMatrix * matrix_pt () const
void turn_on_recursive_debug_flag ()
void turn_off_recursive_debug_flag ()
void turn_on_debug_flag ()
Toggles on the debug flag.
void turn_off_debug_flag ()
Toggles off the debug flag.
void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> &doftype_coarsen_map_coarse)
virtual void block_setup ()
void block_setup (const Vector< unsigned > &dof_to_block_map)
void get_block (const unsigned &i, const unsigned &j, CRDoubleMatrix &output_matrix, const bool &ignore_replacement_block=false) const
CRDoubleMatrix get_block (const unsigned &i, const unsigned &j, const bool &ignore_replacement_block=false) const
void set_master_matrix_pt (CRDoubleMatrix *in_matrix_pt)
Set the matrix_pt in the upper-most master preconditioner.
void get_block_other_matrix (const unsigned &i, const unsigned &j, CRDoubleMatrix *in_matrix_pt, CRDoubleMatrix &output_matrix)
void get_blocks (DenseMatrix< bool > &required_blocks, DenseMatrix< CRDoubleMatrix * > &block_matrix_pt) const
void get_dof_level_block (const unsigned &i, const unsigned &j, CRDoubleMatrix &output_block, const bool &ignore_replacement_block=false) const
void get_dof_level_block (const unsigned &block_i, const unsigned &block_j, CRDoubleMatrix &output_block, const bool &ignore_replacement_block) const
CRDoubleMatrix get_concatenated_block (const VectorMatrix< BlockSelector > &selected_block)
void get_concatenated_block_vector (const Vector< unsigned > &block_vec_number, const DoubleVector &v, DoubleVector &b)
void return_concatenated_block_vector (const Vector< unsigned > &block_vec_number, const DoubleVector &b, DoubleVector &v) const
Takes concatenated block ordered vector, b, and copies its.
void get_block_vectors (const Vector< unsigned > &block_vec_number, const DoubleVector &v, Vector< DoubleVector > &s) const
void get_block_vectors (const DoubleVector &v, Vector< DoubleVector > &s) const
void return_block_vectors (const Vector< unsigned > &block_vec_number, const Vector< DoubleVector > &s, DoubleVector &v) const
void return_block_vectors (const Vector< DoubleVector > &s, DoubleVector &v) const
void get_block_vector (const unsigned &n, const DoubleVector &v, DoubleVector &b) const
void return_block_vector (const unsigned &n, const DoubleVector &b, DoubleVector &v) const
void get_block_ordered_preconditioner_vector (const DoubleVector &v, DoubleVector &w)
void return_block_ordered_preconditioner_vector (const DoubleVector &w, DoubleVector &v) const
unsigned nblock_types () const
Return the number of block types.
unsigned ndof_types () const
Return the total number of DOF types.
const Mesh * mesh_pt (const unsigned &i) const
unsigned nmesh () const
int block_number (const unsigned &i_dof) const
Return the block number corresponding to a global index i_dof.
int index_in_block (const unsigned &i_dof) const
const LinearAlgebraDistribution * block_distribution_pt (const unsigned &b) const
Access function to the block distributions (const version).
LinearAlgebraDistribution * block_distribution_pt (const unsigned b)
Access function to the block distributions (non-const version).
LinearAlgebraDistribution * dof_block_distribution_pt (const unsigned &b)
Access function to the dof-level block distributions.
const LinearAlgebraDistribution * master_distribution_pt () const
unsigned ndof_types_in_mesh (const unsigned &i) const
bool is_subsidiary_block_preconditioner () const
bool is_master_block_preconditioner () const
void set_block_output_to_files (const std::string &basefilename)
void disable_block_output_to_files ()
Turn off output of blocks (by clearing the basefilename string).
bool block_output_on () const
Test if output of blocks is on or not.
void output_blocks_to_files (const std::string &basefilename, const unsigned &precision=8) const
void post_block_matrix_assembly_partial_clear ()
BlockPreconditioner< CRDoubleMatrix > * master_block_preconditioner_pt () const
Access function to the master block preconditioner pt.
void clear_block_preconditioner_base ()
void document ()
Vector< Vector< unsigned > > doftype_coarsen_map_fine () const
Vector< unsigned > get_fine_grain_dof_types_in (const unsigned &i) const
unsigned nfine_grain_dof_types_in (const unsigned &i) const
MapMatrix< unsigned, CRDoubleMatrix * > replacement_dof_block_pt () const
Access function to the replaced dof-level blocks.
void setup_matrix_vector_product (MatrixVectorProduct *matvec_prod_pt, CRDoubleMatrix *block_pt, const Vector< unsigned > &block_col_indices)
void setup_matrix_vector_product (MatrixVectorProduct *matvec_prod_pt, CRDoubleMatrix *block_pt, const unsigned &block_col_index)
void internal_get_block_ordered_preconditioner_vector (const DoubleVector &v, DoubleVector &w) const
void internal_return_block_ordered_preconditioner_vector (const DoubleVector &w, DoubleVector &v) const
unsigned internal_nblock_types () const
unsigned internal_ndof_types () const
void internal_return_block_vector (const unsigned &n, const DoubleVector &b, DoubleVector &v) const
void internal_get_block_vector (const unsigned &n, const DoubleVector &v, DoubleVector &b) const
void internal_get_block_vectors (const Vector< unsigned > &block_vec_number, const DoubleVector &v, Vector< DoubleVector > &s) const
void internal_get_block_vectors (const DoubleVector &v, Vector< DoubleVector > &s) const
void internal_return_block_vectors (const Vector< unsigned > &block_vec_number, const Vector< DoubleVector > &s, DoubleVector &v) const
void internal_return_block_vectors (const Vector< DoubleVector > &s, DoubleVector &v) const
void internal_get_block (const unsigned &i, const unsigned &j, CRDoubleMatrix &output_block) const
void internal_get_block (const unsigned &block_i, const unsigned &block_j, CRDoubleMatrix &output_block) const
int internal_block_number (const unsigned &i_dof) const
int internal_index_in_block (const unsigned &i_dof) const
const LinearAlgebraDistribution * internal_block_distribution_pt (const unsigned &b) const
Access function to the internal block distributions.
void insert_auxiliary_block_distribution (const Vector< unsigned > &block_vec_number, LinearAlgebraDistribution *dist_pt)
void block_matrix_test (const unsigned &i, const unsigned &j, const CRDoubleMatrix *block_matrix_pt) const
int get_index_of_value (const Vector< myType > &vec, const myType val, const bool sorted=false) const
Public Member Functions inherited from oomph::Preconditioner
Preconditioner ()
Constructor.
Preconditioner (const Preconditioner &)=delete
Broken copy constructor.
void operator= (const Preconditioner &)=delete
Broken assignment operator.
virtual ~Preconditioner ()
Destructor (empty)
virtual void preconditioner_solve_transpose (const DoubleVector &r, DoubleVector &z)
void setup (DoubleMatrixBase *matrix_pt)
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
void enable_silent_preconditioner_setup ()
Set up the block preconditioner quietly!
void disable_silent_preconditioner_setup ()
Be verbose in the block preconditioner setup.
virtual void set_matrix_pt (DoubleMatrixBase *matrix_pt)
Set the matrix pointer.
virtual const OomphCommunicator * comm_pt () const
Get function for comm pointer.
virtual void set_comm_pt (const OomphCommunicator *const comm_pt)
Set the communicator pointer.
double setup_time () const
Returns the time to setup the preconditioner.
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> &doftype_coarsen_map_coarse)
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
void build_distribution (const LinearAlgebraDistribution &dist)
Private Member Functions
CRDoubleMatrix * assemble_mass_matrix_diagonal ()
Private Attributes
Preconditioner * P_preconditioner_pt
Pointer to the 'preconditioner' for the pressure matrix.
Preconditioner * F_preconditioner_pt
Pointer to the 'preconditioner' for the F matrix.
bool Using_default_f_preconditioner
flag indicating whether the default F preconditioner is used
bool Using_default_p_preconditioner
flag indicating whether the default P preconditioner is used
bool Preconditioner_has_been_setup
bool P_matrix_using_scaling
bool F_preconditioner_is_block_preconditioner
bool Doc_time
Set Doc_time to true for outputting results of timings.
MatrixVectorProduct * F_mat_vec_pt
MatrixVectorProduct operator for F if BFBt is not to be formed.
MatrixVectorProduct * QBt_mat_vec_pt
MatrixVectorProduct operator for QBt if BFBt is not to be formed.
MatrixVectorProduct * Bt_mat_vec_pt
MatrixVectorProduct operator for Bt;.
MatrixVectorProduct * E_mat_vec_pt
MatrixVectorProduct operator for E (BFBt) if BFBt is to be formed.
bool Form_BFBt_product
Mesh * Solid_mesh_pt
Additional Inherited Members
Protected Member Functions inherited from oomph::BlockPreconditioner< CRDoubleMatrix >
void set_nmesh (const unsigned &n)
void set_mesh (const unsigned &i, const Mesh *const mesh_pt, const bool &allow_multiple_element_type_in_mesh=false)
void set_replacement_dof_block (const unsigned &block_i, const unsigned &block_j, CRDoubleMatrix *replacement_dof_block_pt)
bool any_mesh_distributed () const
int internal_dof_number (const unsigned &i_dof) const
unsigned internal_index_in_dof (const unsigned &i_dof) const
unsigned internal_block_dimension (const unsigned &b) const
unsigned internal_dof_block_dimension (const unsigned &i) const
unsigned master_nrow () const
unsigned internal_master_dof_number (const unsigned &b) const
const LinearAlgebraDistribution * internal_preconditioner_matrix_distribution_pt () const
const LinearAlgebraDistribution * preconditioner_matrix_distribution_pt () const
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
Protected Attributes inherited from oomph::BlockPreconditioner< CRDoubleMatrix >
MapMatrix< unsigned, CRDoubleMatrix * > Replacement_dof_block_pt
The replacement dof-level blocks.
Vector< LinearAlgebraDistribution * > Block_distribution_pt
The distribution for the blocks.
Vector< Vector< unsigned > > Block_to_dof_map_coarse
Vector< Vector< unsigned > > Block_to_dof_map_fine
Mapping for the block types to the most fine grain dof types.
Vector< Vector< unsigned > > Doftype_coarsen_map_coarse
Vector< Vector< unsigned > > Doftype_coarsen_map_fine
Vector< LinearAlgebraDistribution * > Internal_block_distribution_pt
Storage for the default distribution for each internal block.
Vector< LinearAlgebraDistribution * > Dof_block_distribution_pt
Vector< unsigned > Allow_multiple_element_type_in_mesh
Vector< const Mesh * > Mesh_pt
Vector< unsigned > Ndof_types_in_mesh
unsigned Internal_nblock_types
unsigned Internal_ndof_types
Protected Attributes inherited from oomph::Preconditioner
bool Silent_preconditioner_setup
Boolean to indicate whether or not the build should be done silently.
std::ostream * Stream_pt
Pointer to the output stream – defaults to std::cout.
Detailed Description
The least-squares commutator (LSC; formerly BFBT) preconditioner. It uses blocks corresponding to the displacement/position and pressure unknowns, i.e. there are a total of 2x2 blocks, and all displacement/position components are treated as a single block of unknowns.
Here are the details: An "ideal" preconditioner would solve the saddle point system
\[ \left(\begin{array}{cc} {\bf F} & {\bf G} \\ {\bf D} & {\bf 0} \end{array} \right) \left(\begin{array}{c} {\bf z}_u \\ {\bf z}_p \end{array} \right) = \left(\begin{array}{c} {\bf r}_u \\ {\bf r}_p \end{array} \right) \]
where \({\bf F}\), \({\bf G} \), and \({\bf D}\) are the blocks that arise in the Jacobian of the pressure-based equations of linear and nonlinear elasticity (with dofs in order of displacement/position and pressure). The use of this preconditioner would ensure the convergence of any iterative linear solver in a single iteration but its application is, of course, exactly as expensive as a direct solve. The LSC/BFBT preconditioner replaces the exact Jacobian by a block-triangular approximation
\[ \left(\begin{array}{cc} {\bf F} & {\bf G} \\ {\bf 0} & -{\bf M}_s \end{array} \right) \left(\begin{array}{c} {\bf z}_u \\ {\bf z}_p \end{array} \right) = \left(\begin{array}{c} {\bf r}_u \\ {\bf r}_p \end{array} \right), \]
where \({\bf M}_s\) is an approximation to the pressure Schur-complement \({\bf S} = {\bf D} {\bf F}^{-1}{\bf G}. \) This system can be solved in two steps:
Solve the second row for \({\bf z}_p\) via
\[ {\bf z}_p = - {\bf M}_s^{-1} {\bf r}_p \]
Given \({\bf z}_p \) , solve the first row for \({\bf z}_u\) via
\[ {\bf z}_u = {\bf F}^{-1} \big({\bf r}_u - {\bf G} {\bf z}_p \big) \]
. In the LSC/BFBT preconditioner, the action of the inverse pressure Schur complement
\[ {\bf z}_p = - {\bf M}_s^{-1} {\bf r}_p \]
is approximated by
\[ {\bf z}_p = - \big({\bf D} \widehat{\bf Q}^{-1}{\bf G} \big)^{-1} \big({\bf D} \widehat{\bf Q}^{-1}{\bf F} \widehat{\bf Q}^{-1}{\bf G}\big) \big({\bf D} \widehat{\bf Q}^{-1}{\bf G} \big)^{-1} {\bf r}_p, \]
where \(\widehat{\bf Q} \) is the diagonal of the displacement/position mass matrix. The evaluation of this expression involves two linear solves involving the matrix
\[ {\bf P} = \big({\bf D} \widehat{\bf Q}^{-1}{\bf G} \big) \]
which has the character of a matrix arising from the discretisation of a Poisson problem on the pressure space. We also have to evaluate matrix-vector products with the matrix
\[ {\bf E}={\bf D}\widehat{\bf Q}^{-1}{\bf F}\widehat{\bf Q}^{-1}{\bf G} \]
Details of the theory can be found in "Finite Elements and Fast Iterative Solvers with Applications in Incompressible Fluid Dynamics" by Howard C. Elman, David J. Silvester, and Andrew J. Wathen, published by Oxford University Press, 2006.
In our implementation of the preconditioner, the linear systems can either be solved "exactly", using SuperLU (in its incarnation as an exact preconditioner; this is the default) or by any other Preconditioner (inexact solver) specified via the access functions
PressureBasedSolidLSCPreconditioner::set_f_preconditioner(...)
or
PressureBasedSolidLSCPreconditioner::set_p_preconditioner(...)
Constructor & Destructor Documentation
PressureBasedSolidLSCPreconditioner() [1/2]
oomph::PressureBasedSolidLSCPreconditioner::PressureBasedSolidLSCPreconditioner () inline
Constructor - sets defaults for control flags.
       : BlockPreconditioner<CRDoubleMatrix>()
     {
       // Flag to indicate that the preconditioner has been setup
       // previously -- if setup() is called again, data can
       // be wiped.
       Preconditioner_has_been_setup = false;
       // By default we use SuperLU for both p and f blocks
       Using_default_p_preconditioner = true;
       Using_default_f_preconditioner = true;
       // resize the mesh pt
       // note: meaningless if subsidiary preconditioner
       this->set_nmesh(1);
       Solid_mesh_pt = 0;
       // Set default preconditioners (inexact solvers) -- they are
       // members of this class!
       P_preconditioner_pt = 0;
       F_preconditioner_pt = 0;
       // Flag to determine if mass matrix diagonal Q^{-1}
       // is used for scaling.
       P_matrix_using_scaling = true;
       // set Doc_time to false
       Doc_time = false;
       // null the off diagonal Block matrix pt
       Bt_mat_vec_pt = 0;
       // null the F matrix vector product helper
       F_mat_vec_pt = 0;
       // null the QBt matrix vector product pt
       QBt_mat_vec_pt = 0;
       // null the E matrix vector product helper
       E_mat_vec_pt = 0;
       // by default we do not form the E matrix (BQFQBt)
       Form_BFBt_product = false;
     }
References Bt_mat_vec_pt, Doc_time, E_mat_vec_pt, F_mat_vec_pt, F_preconditioner_pt, Form_BFBt_product, P_matrix_using_scaling, P_preconditioner_pt, Preconditioner_has_been_setup, QBt_mat_vec_pt, oomph::BlockPreconditioner< CRDoubleMatrix >::set_nmesh(), Solid_mesh_pt, Using_default_f_preconditioner, and Using_default_p_preconditioner.
~PressureBasedSolidLSCPreconditioner()
oomph::PressureBasedSolidLSCPreconditioner::~PressureBasedSolidLSCPreconditioner () inline
Destructor.
     {
       clean_up_memory();
     }
References clean_up_memory().
PressureBasedSolidLSCPreconditioner() [2/2]
oomph::PressureBasedSolidLSCPreconditioner::PressureBasedSolidLSCPreconditioner (const PressureBasedSolidLSCPreconditioner &) delete
Broken copy constructor.
Member Function Documentation
assemble_mass_matrix_diagonal()
CRDoubleMatrix * oomph::PressureBasedSolidLSCPreconditioner::assemble_mass_matrix_diagonal () private
Helper function to assemble the diagonal of the mass matrix from the elemental contributions defined in PressureBasedSolidEquations<DIM>::get_mass_matrix_diagonal(...).
Helper function to assemble the diagonal of the mass matrix from the elemental contributions defined in SolidElementWithDiagonalMassMatrix::get_mass_matrix_diagonal(...).
   {
     // determine the rows required by this processor
     unsigned first_row = this->block_distribution_pt(0)->first_row();
     unsigned nrow_local = this->block_distribution_pt(0)->nrow_local();
     unsigned nrow = this->block_distribution_pt(0)->nrow();
     // create storage for the diagonals
     double* m_values = new double[nrow_local];
     for (unsigned i = 0; i < nrow_local; i++)
     {
       m_values[i] = 0;
     }
     // if the problem is distributed
     bool distributed = false;
 #ifdef OOMPH_HAS_MPI
     if (any_mesh_distributed() || this->master_distribution_pt()->distributed())
     {
       distributed = true;
     }
 #endif
     // next we get the diagonal mass matrix data
     if (distributed)
     {
 #ifdef OOMPH_HAS_MPI
       // the number of processors
       unsigned nproc = this->comm_pt()->nproc();
       // and my rank
       unsigned my_rank = this->comm_pt()->my_rank();
       // determine the rows for which we have lookup rows
       // if the problem is NOT distributed then we only classify global equation
       // on this processor to avoid duplication (as every processor holds
       // every element)
       unsigned first_lookup_row = 0;
       unsigned last_lookup_row = 0;
       first_lookup_row = this->master_distribution_pt()->first_row();
       last_lookup_row =
         first_lookup_row + this->master_distribution_pt()->nrow_local() - 1;
       // find number of local elements
       unsigned n_el = Solid_mesh_pt->nelement();
       // the diagonal mass matrix contributions that have been
       // classified and should be sent to another processor
       Vector<double>* classified_contributions_send = new Vector<double>[nproc];
       // the corresponding block indices
       Vector<unsigned>* classified_indices_send = new Vector<unsigned>[nproc];
       // the maitrix contributions that cannot be classified by this processor
       // and therefore must be sent to another for classification
       Vector<double>* unclassified_contributions_send =
         new Vector<double>[nproc];
       // the corresponding global indices that require classification
       Vector<unsigned>* unclassified_indices_send = new Vector<unsigned>[nproc];
       // get the master distribution pt
       const LinearAlgebraDistribution* master_distribution_pt =
         this->master_distribution_pt();
       // get the displacement/position distribution pt
       const LinearAlgebraDistribution* displ_dist_pt =
         this->block_distribution_pt(0);
       // get the contribution for each element
       for (unsigned e = 0; e < n_el; e++)
       {
         // check that the element is not halo d
         if (!Solid_mesh_pt->element_pt(e)->is_halo())
         {
           // find number of degrees of freedom in the element
           // (this is slightly too big because it includes the
           // pressure dofs but this doesn't matter)
           unsigned el_dof = Solid_mesh_pt->element_pt(e)->ndof();
           // allocate local storage for the element's contribution to the
           // mass matrix diagonal
           Vector<double> el_vmm_diagonal(el_dof);
           SolidElementWithDiagonalMassMatrix* cast_el_pt =
             dynamic_cast<SolidElementWithDiagonalMassMatrix*>(
               Solid_mesh_pt->element_pt(e));
           if (cast_el_pt == 0)
           {
 #ifdef PARANOID
             std::ostringstream error_message;
             error_message << "Failed cast to "
                           << "SolidElementWithDiagonalMassMatrix*\n"
                           << "Element is of type: "
                           << typeid(*(Solid_mesh_pt->element_pt(e))).name()
                           << "\n"
                           << typeid(Solid_mesh_pt->element_pt(e)).name()
                           << std::endl;
             OomphLibWarning(error_message.str(),
                             "PressureBasedSolidLSCPreconditioner::assemble_"
                             "mass_matrix_diagonal()",
                             OOMPH_EXCEPTION_LOCATION);
 #endif
           }
           else
           {
             cast_el_pt->get_mass_matrix_diagonal(el_vmm_diagonal);
           }
           // get the contribution for each dof
           for (unsigned i = 0; i < el_dof; i++)
           {
             // Get the equation number
             unsigned eqn_number = Solid_mesh_pt->element_pt(e)->eqn_number(i);
             // if I have lookup information on this processor
             if (eqn_number >= first_lookup_row && eqn_number <= last_lookup_row)
             {
               // bypass non displacement/position DOFs
               if (this->block_number(eqn_number) == 0)
               {
                 // get the index in the block
                 unsigned index = this->index_in_block(eqn_number);
                 // determine which processor requires the block index
                 for (unsigned p = 0; p < nproc; p++)
                 {
                   if (index >= displ_dist_pt->first_row(p) &&
                       (index < (displ_dist_pt->first_row(p) +
                                 displ_dist_pt->nrow_local(p))))
                   {
                     // if it is required by this processor then add the
                     // contribution
                     if (p == my_rank)
                     {
                       m_values[index - first_row] += el_vmm_diagonal[i];
                     }
                     // other wise store it for communication
                     else
                     {
                       classified_contributions_send[p].push_back(
                         el_vmm_diagonal[i]);
                       classified_indices_send[p].push_back(index);
                     }
                   }
                 }
               }
             }
             // if we do not have the lookup information on this processor
             // then we send the mass matrix contribution to a processor
             // which we know does have the lookup information
             // the assumption: the processor for which the master block
             // preconditioner distribution will definitely hold the lookup
             // data for eqn_number (although others may)
             else if (any_mesh_distributed())
             {
               // determine which processor requires the block index
               unsigned p = 0;
               while (!(eqn_number >= master_distribution_pt->first_row(p) &&
                        (eqn_number < (master_distribution_pt->first_row(p) +
                                       master_distribution_pt->nrow_local(p)))))
               {
                 p++;
               }
               // store the data
               unclassified_contributions_send[p].push_back(el_vmm_diagonal[i]);
               unclassified_indices_send[p].push_back(eqn_number);
             }
           }
         }
       }
       // next the unclassified contributions are communicated to
       // processors that can classify them
       // first determine how many unclassified rows are to be sent to
       // each processor
       unsigned* n_unclassified_send = new unsigned[nproc];
       for (unsigned p = 0; p < nproc; p++)
       {
         if (p == my_rank)
         {
           n_unclassified_send[p] = 0;
         }
         else
         {
           n_unclassified_send[p] = unclassified_contributions_send[p].size();
         }
       }
       // then all-to-all number of unclassified to be sent / recv
       unsigned* n_unclassified_recv = new unsigned[nproc];
       MPI_Alltoall(n_unclassified_send,
                    1,
                    MPI_UNSIGNED,
                    n_unclassified_recv,
                    1,
                    MPI_UNSIGNED,
                    this->comm_pt()->mpi_comm());
       // the base displacement for the sends
       MPI_Aint base_displacement;
       MPI_Get_address(m_values, &base_displacement);
       // allocate storage for the data to be recieved
       // and post the sends and recvs
       Vector<double*> unclassified_contributions_recv(nproc);
       Vector<unsigned*> unclassified_indices_recv(nproc);
       Vector<MPI_Request> unclassified_recv_requests;
       Vector<MPI_Request> unclassified_send_requests;
       Vector<unsigned> unclassified_recv_proc;
       for (unsigned p = 0; p < nproc; p++)
       {
         if (p != my_rank)
         {
           // recv
           if (n_unclassified_recv[p] > 0)
           {
             unclassified_contributions_recv[p] =
               new double[n_unclassified_recv[p]];
             unclassified_indices_recv[p] = new unsigned[n_unclassified_recv[p]];
             // data for the struct data type
             MPI_Datatype recv_types[2];
             MPI_Aint recv_displacements[2];
             int recv_sz[2];
             // contributions
             MPI_Type_contiguous(
               n_unclassified_recv[p], MPI_DOUBLE, &recv_types[0]);
             MPI_Type_commit(&recv_types[0]);
             MPI_Get_address(unclassified_contributions_recv[p],
                             &recv_displacements[0]);
             recv_displacements[0] -= base_displacement;
             recv_sz[0] = 1;
             // indices
             MPI_Type_contiguous(
               n_unclassified_recv[p], MPI_UNSIGNED, &recv_types[1]);
             MPI_Type_commit(&recv_types[1]);
             MPI_Get_address(unclassified_indices_recv[p],
                             &recv_displacements[1]);
             recv_displacements[1] -= base_displacement;
             recv_sz[1] = 1;
             // build the final recv type
             MPI_Datatype final_recv_type;
             MPI_Type_create_struct(
               2, recv_sz, recv_displacements, recv_types, &final_recv_type);
             MPI_Type_commit(&final_recv_type);
             // and recv
             MPI_Request req;
             MPI_Irecv(
               m_values, 1, final_recv_type, p, 0, comm_pt()->mpi_comm(), &req);
             unclassified_recv_requests.push_back(req);
             unclassified_recv_proc.push_back(p);
             MPI_Type_free(&recv_types[0]);
             MPI_Type_free(&recv_types[1]);
             MPI_Type_free(&final_recv_type);
           }
           // send
           if (n_unclassified_send[p] > 0)
           {
             // data for the struct data type
             MPI_Datatype send_types[2];
             MPI_Aint send_displacements[2];
             int send_sz[2];
             // contributions
             MPI_Type_contiguous(
               n_unclassified_send[p], MPI_DOUBLE, &send_types[0]);
             MPI_Type_commit(&send_types[0]);
             MPI_Get_address(&unclassified_contributions_send[p][0],
                             &send_displacements[0]);
             send_displacements[0] -= base_displacement;
             send_sz[0] = 1;
             // indices
             MPI_Type_contiguous(
               n_unclassified_send[p], MPI_UNSIGNED, &send_types[1]);
             MPI_Type_commit(&send_types[1]);
             MPI_Get_address(&unclassified_indices_send[p][0],
                             &send_displacements[1]);
             send_displacements[1] -= base_displacement;
             send_sz[1] = 1;
             // build the final send type
             MPI_Datatype final_send_type;
             MPI_Type_create_struct(
               2, send_sz, send_displacements, send_types, &final_send_type);
             MPI_Type_commit(&final_send_type);
             // and send
             MPI_Request req;
             MPI_Isend(
               m_values, 1, final_send_type, p, 0, comm_pt()->mpi_comm(), &req);
             unclassified_send_requests.push_back(req);
             MPI_Type_free(&send_types[0]);
             MPI_Type_free(&send_types[1]);
             MPI_Type_free(&final_send_type);
           }
         }
       }
       // next classify the data as it is received
       unsigned n_unclassified_recv_req = unclassified_recv_requests.size();
       while (n_unclassified_recv_req > 0)
       {
         // get the processor number and remove the completed request
         // for the vector of requests
         int req_num;
         MPI_Waitany(n_unclassified_recv_req,
                     &unclassified_recv_requests[0],
                     &req_num,
                     MPI_STATUS_IGNORE);
         unsigned p = unclassified_recv_proc[req_num];
         unclassified_recv_requests.erase(unclassified_recv_requests.begin() +
                                          req_num);
         unclassified_recv_proc.erase(unclassified_recv_proc.begin() + req_num);
         n_unclassified_recv_req--;
         // next classify the dofs
         // and store them for sending to other processors if required
         unsigned n_recv = n_unclassified_recv[p];
         for (unsigned i = 0; i < n_recv; i++)
         {
           unsigned eqn_number = unclassified_indices_recv[p][i];
           // bypass non displacement/position DOFs
           if (this->block_number(eqn_number) == 0)
           {
             // get the index in the block
             unsigned index = this->index_in_block(eqn_number);
             // determine which processor requires the block index
             for (unsigned pp = 0; pp < nproc; pp++)
             {
               if (index >= displ_dist_pt->first_row(pp) &&
                   (index < (displ_dist_pt->first_row(pp) +
                             displ_dist_pt->nrow_local(pp))))
               {
                 // if it is required by this processor then add the
                 // contribution
                 if (pp == my_rank)
                 {
                   m_values[index - first_row] +=
                     unclassified_contributions_recv[p][i];
                 }
                 // other wise store it for communication
                 else
                 {
                   double v = unclassified_contributions_recv[p][i];
                   classified_contributions_send[pp].push_back(v);
                   classified_indices_send[pp].push_back(index);
                 }
               }
             }
           }
         }
         // clean up
         delete[] unclassified_contributions_recv[p];
         delete[] unclassified_indices_recv[p];
       }
       delete[] n_unclassified_recv;
       // now all indices have been classified
       // next the classified contributions are communicated to
       // processors that require them
       // first determine how many classified rows are to be sent to
       // each processor
       unsigned* n_classified_send = new unsigned[nproc];
       for (unsigned p = 0; p < nproc; p++)
       {
         if (p == my_rank)
         {
           n_classified_send[p] = 0;
         }
         else
         {
           n_classified_send[p] = classified_contributions_send[p].size();
         }
       }
       // then all-to-all com number of classified to be sent / recv
       unsigned* n_classified_recv = new unsigned[nproc];
       MPI_Alltoall(n_classified_send,
                    1,
                    MPI_UNSIGNED,
                    n_classified_recv,
                    1,
                    MPI_UNSIGNED,
                    this->comm_pt()->mpi_comm());
       // allocate storage for the data to be recieved
       // and post the sends and recvs
       Vector<double*> classified_contributions_recv(nproc);
       Vector<unsigned*> classified_indices_recv(nproc);
       Vector<MPI_Request> classified_recv_requests;
       Vector<MPI_Request> classified_send_requests;
       Vector<unsigned> classified_recv_proc;
       for (unsigned p = 0; p < nproc; p++)
       {
         if (p != my_rank)
         {
           // recv
           if (n_classified_recv[p] > 0)
           {
             classified_contributions_recv[p] = new double[n_classified_recv[p]];
             classified_indices_recv[p] = new unsigned[n_classified_recv[p]];
             // data for the struct data type
             MPI_Datatype recv_types[2];
             MPI_Aint recv_displacements[2];
             int recv_sz[2];
             // contributions
             MPI_Type_contiguous(
               n_classified_recv[p], MPI_DOUBLE, &recv_types[0]);
             MPI_Type_commit(&recv_types[0]);
             MPI_Get_address(classified_contributions_recv[p],
                             &recv_displacements[0]);
             recv_displacements[0] -= base_displacement;
             recv_sz[0] = 1;
             // indices
             MPI_Type_contiguous(
               n_classified_recv[p], MPI_UNSIGNED, &recv_types[1]);
             MPI_Type_commit(&recv_types[1]);
             MPI_Get_address(classified_indices_recv[p], &recv_displacements[1]);
             recv_displacements[1] -= base_displacement;
             recv_sz[1] = 1;
             // build the final recv type
             MPI_Datatype final_recv_type;
             MPI_Type_create_struct(
               2, recv_sz, recv_displacements, recv_types, &final_recv_type);
             MPI_Type_commit(&final_recv_type);
             // and recv
             MPI_Request req;
             MPI_Irecv(
               m_values, 1, final_recv_type, p, 0, comm_pt()->mpi_comm(), &req);
             classified_recv_requests.push_back(req);
             classified_recv_proc.push_back(p);
             MPI_Type_free(&recv_types[0]);
             MPI_Type_free(&recv_types[1]);
             MPI_Type_free(&final_recv_type);
           }
           // send
           if (n_classified_send[p] > 0)
           {
             // data for the struct data type
             MPI_Datatype send_types[2];
             MPI_Aint send_displacements[2];
             int send_sz[2];
             // contributions
             MPI_Type_contiguous(
               n_classified_send[p], MPI_DOUBLE, &send_types[0]);
             MPI_Type_commit(&send_types[0]);
             MPI_Get_address(&classified_contributions_send[p][0],
                             &send_displacements[0]);
             send_displacements[0] -= base_displacement;
             send_sz[0] = 1;
             // indices
             MPI_Type_contiguous(
               n_classified_send[p], MPI_UNSIGNED, &send_types[1]);
             MPI_Type_commit(&send_types[1]);
             MPI_Get_address(&classified_indices_send[p][0],
                             &send_displacements[1]);
             send_displacements[1] -= base_displacement;
             send_sz[1] = 1;
             // build the final send type
             MPI_Datatype final_send_type;
             MPI_Type_create_struct(
               2, send_sz, send_displacements, send_types, &final_send_type);
             MPI_Type_commit(&final_send_type);
             // and send
             MPI_Request req;
             MPI_Isend(
               m_values, 1, final_send_type, p, 0, comm_pt()->mpi_comm(), &req);
             classified_send_requests.push_back(req);
             MPI_Type_free(&send_types[0]);
             MPI_Type_free(&send_types[1]);
             MPI_Type_free(&final_send_type);
           }
         }
       }
       // next classify the data as it is received
       unsigned n_classified_recv_req = classified_recv_requests.size();
       while (n_classified_recv_req > 0)
       {
         // get the processor number and remove the completed request
         // for the vector of requests
         int req_num;
         MPI_Waitany(n_classified_recv_req,
                     &classified_recv_requests[0],
                     &req_num,
                     MPI_STATUS_IGNORE);
         unsigned p = classified_recv_proc[req_num];
         classified_recv_requests.erase(classified_recv_requests.begin() +
                                        req_num);
         classified_recv_proc.erase(classified_recv_proc.begin() + req_num);
         n_classified_recv_req--;
         // next classify the dofs
         // and store them for sending to other processors if required
         unsigned n_recv = n_classified_recv[p];
         for (unsigned i = 0; i < n_recv; i++)
         {
           m_values[classified_indices_recv[p][i] - first_row] +=
             classified_contributions_recv[p][i];
         }
         // clean up
         delete[] classified_contributions_recv[p];
         delete[] classified_indices_recv[p];
       }
       // wait for the unclassified sends to complete
       unsigned n_unclassified_send_req = unclassified_send_requests.size();
       if (n_unclassified_send_req > 0)
       {
         MPI_Waitall(n_unclassified_send_req,
                     &unclassified_send_requests[0],
                     MPI_STATUS_IGNORE);
       }
       delete[] unclassified_contributions_send;
       delete[] unclassified_indices_send;
       delete[] n_unclassified_send;
       // wait for the classified sends to complete
       unsigned n_classified_send_req = classified_send_requests.size();
       if (n_classified_send_req > 0)
       {
         MPI_Waitall(n_classified_send_req,
                     &classified_send_requests[0],
                     MPI_STATUS_IGNORE);
       }
       delete[] classified_indices_send;
       delete[] classified_contributions_send;
       delete[] n_classified_recv;
       delete[] n_classified_send;
 #endif
     }
     // or if the problem is not distributed
     else
     {
       // find number of elements
       unsigned n_el = Solid_mesh_pt->nelement();
       // get the contribution for each element
       for (unsigned e = 0; e < n_el; e++)
       {
         // find number of degrees of freedom in the element
         // (this is slightly too big because it includes the
         // pressure dofs but this doesn't matter)
         unsigned el_dof = Solid_mesh_pt->element_pt(e)->ndof();
         // allocate local storage for the element's contribution to the
         //  mass matrix diagonal
         Vector<double> el_vmm_diagonal(el_dof);
         SolidElementWithDiagonalMassMatrix* cast_el_pt =
           dynamic_cast<SolidElementWithDiagonalMassMatrix*>(
             Solid_mesh_pt->element_pt(e));
         if (cast_el_pt == 0)
         {
 #ifdef PARANOID
           // #pragma clang diagnostic push
           // #pragma clang diagnostic ignored
           // "-Wpotentially-evaluated-expression"
           std::ostringstream error_message;
           error_message << "Failed cast to "
                         << "SolidElementWithDiagonalMassMatrix*\n"
                         << "Element is of type: "
                         << typeid(*(Solid_mesh_pt->element_pt(e))).name()
                         << "\n"
                         << typeid(Solid_mesh_pt->element_pt(e)).name()
                         << std::endl;
           OomphLibWarning(error_message.str(),
                           "PressureBasedSolidLSCPreconditioner::assemble_mass_"
                           "matrix_diagonal()",
                           OOMPH_EXCEPTION_LOCATION);
 //#pragma clang diagnostic pop
 #endif
         }
         else
         {
           cast_el_pt->get_mass_matrix_diagonal(el_vmm_diagonal);
         }
         // get the contribution for each dof
         for (unsigned i = 0; i < el_dof; i++)
         {
           // Get the equation number
           unsigned eqn_number = Solid_mesh_pt->element_pt(e)->eqn_number(i);
           // bypass non displacement/position DOFs
           if (this->block_number(eqn_number) == 0)
           {
             // get the index in the block
             unsigned index = this->index_in_block(eqn_number);
             // if it is required on this processor
             if (index >= first_row && index < first_row + nrow_local)
             {
               m_values[index - first_row] += el_vmm_diagonal[i];
             }
           }
         }
       }
     }
     // create column index and row start
     int* m_column_index = new int[nrow_local];
     int* m_row_start = new int[nrow_local + 1];
     for (unsigned i = 0; i < nrow_local; i++)
     {
       m_values[i] = 1 / m_values[i];
       m_column_index[i] = first_row + i;
       m_row_start[i] = i;
     }
     m_row_start[nrow_local] = nrow_local;
     // build the matrix
     CRDoubleMatrix* m_pt = new CRDoubleMatrix(this->block_distribution_pt(0));
     m_pt->build_without_copy(
       nrow, nrow_local, m_values, m_column_index, m_row_start);
     // return the matrix;
     return m_pt;
   }
References oomph::BlockPreconditioner< CRDoubleMatrix >::any_mesh_distributed(), oomph::BlockPreconditioner< CRDoubleMatrix >::block_distribution_pt(), oomph::BlockPreconditioner< CRDoubleMatrix >::block_number(), oomph::CRDoubleMatrix::build_without_copy(), oomph::Preconditioner::comm_pt(), oomph::DistributableLinearAlgebraObject::distributed(), e(), oomph::Mesh::element_pt(), oomph::GeneralisedElement::eqn_number(), oomph::LinearAlgebraDistribution::first_row(), oomph::DistributableLinearAlgebraObject::first_row(), oomph::SolidElementWithDiagonalMassMatrix::get_mass_matrix_diagonal(), i, oomph::BlockPreconditioner< CRDoubleMatrix >::index_in_block(), oomph::BlockPreconditioner< CRDoubleMatrix >::master_distribution_pt(), oomph::OomphCommunicator::my_rank(), plotDoE::name, oomph::GeneralisedElement::ndof(), oomph::Mesh::nelement(), oomph::OomphCommunicator::nproc(), oomph::LinearAlgebraDistribution::nrow(), oomph::DistributableLinearAlgebraObject::nrow(), oomph::LinearAlgebraDistribution::nrow_local(), oomph::DistributableLinearAlgebraObject::nrow_local(), OOMPH_EXCEPTION_LOCATION, p, Solid_mesh_pt, and v.
Referenced by setup().
clean_up_memory()
void oomph::PressureBasedSolidLSCPreconditioner::clean_up_memory () virtual
Helper function to delete preconditioner data.
Reimplemented from oomph::Preconditioner.
   {
     if (Preconditioner_has_been_setup)
     {
       // delete matvecs
       delete Bt_mat_vec_pt;
       Bt_mat_vec_pt = 0;
       if (!Form_BFBt_product)
       {
         delete F_mat_vec_pt;
         F_mat_vec_pt = 0;
         delete QBt_mat_vec_pt;
         QBt_mat_vec_pt = 0;
       }
       else
       {
         delete E_mat_vec_pt;
         E_mat_vec_pt = 0;
       }
       // delete stuff from displacement/position solve
       if (Using_default_f_preconditioner)
       {
         delete F_preconditioner_pt;
         F_preconditioner_pt = 0;
       }
       // delete stuff from Schur complement approx
       if (Using_default_p_preconditioner)
       {
         delete P_preconditioner_pt;
         P_preconditioner_pt = 0;
       }
     }
   }
References Bt_mat_vec_pt, E_mat_vec_pt, F_mat_vec_pt, F_preconditioner_pt, Form_BFBt_product, P_preconditioner_pt, Preconditioner_has_been_setup, QBt_mat_vec_pt, Using_default_f_preconditioner, and Using_default_p_preconditioner.
Referenced by setup(), and ~PressureBasedSolidLSCPreconditioner().
disable_doc_time()
void oomph::PressureBasedSolidLSCPreconditioner::disable_doc_time () inline
Disable documentation of time.
     {
       Doc_time = false;
     }
References Doc_time.
disable_form_BFBt_product()
void oomph::PressureBasedSolidLSCPreconditioner::disable_form_BFBt_product () inline
if this function is called then: in setup(...) : the matrices B, F are assembled and stored (the default behaviour) . in preconditioner_solve(...) : a sequence of matrix vector products with B, F, and Bt is performed. (Note: in this discussion no scaling was considered but B and Bt are replaced with BQ and QBt with scaling)
     {
       Form_BFBt_product = false;
     }
References Form_BFBt_product.
disable_p_matrix_scaling()
void oomph::PressureBasedSolidLSCPreconditioner::disable_p_matrix_scaling () inline
Enable mass matrix diagonal scaling in the Schur complement approximation
     {
       P_matrix_using_scaling = false;
     }
References P_matrix_using_scaling.
enable_doc_time()
void oomph::PressureBasedSolidLSCPreconditioner::enable_doc_time () inline
Enable documentation of time.
     {
       Doc_time = true;
     }
References Doc_time.
enable_form_BFBt_product()
void oomph::PressureBasedSolidLSCPreconditioner::enable_form_BFBt_product () inline
If this function is called then: in setup(...) : BFBt is computed. in preconditioner_solve(...) : a single matrix vector product with BFBt is performed.
     {
       Form_BFBt_product = true;
     }
References Form_BFBt_product.
enable_p_matrix_scaling()
void oomph::PressureBasedSolidLSCPreconditioner::enable_p_matrix_scaling () inline
Enable mass matrix diagonal scaling in the Schur complement approximation
     {
       P_matrix_using_scaling = true;
     }
References P_matrix_using_scaling.
is_p_matrix_using_scaling()
bool oomph::PressureBasedSolidLSCPreconditioner::is_p_matrix_using_scaling () const inline
Return whether the mass matrix is using diagonal scaling or not
     {
       return P_matrix_using_scaling;
     }
References P_matrix_using_scaling.
preconditioner_solve()
void oomph::PressureBasedSolidLSCPreconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) virtual
Apply preconditioner to Vector r.
Apply preconditioner to r.
Implements oomph::Preconditioner.
   {
 #ifdef PARANOID
     if (Preconditioner_has_been_setup == false)
     {
       std::ostringstream error_message;
       error_message << "setup must be called before using preconditioner_solve";
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     if (z.built())
     {
       if (z.nrow() != r.nrow())
       {
         std::ostringstream error_message;
         error_message << "The vectors z and r must have the same number of "
                       << "of global rows";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
     }
 #endif
     double t_start_overall = TimingHelpers::timer();
     double t_start = TimingHelpers::timer();
     double t_end = 0;
     // if z is not setup then give it the same distribution
     if (!z.built())
     {
       z.build(r.distribution_pt(), 0.0);
     }
     // Step 1 - apply approximate Schur inverse to pressure unknowns (block 1)
     // -----------------------------------------------------------------------
     // Working vectors
     DoubleVector temp_vec;
     DoubleVector another_temp_vec;
     // Copy pressure values from residual vector to temp_vec:
     // Loop over all entries in the global vector (this one
     // includes displacement/position and pressure dofs in some random fashion)
     this->get_block_vector(1, r, temp_vec);
     if (Doc_time)
     {
       t_end = TimingHelpers::timer();
       oomph_info << "LSC prec solve: Time for get block vector: "
                  << t_end - t_start << std::endl;
       t_start = TimingHelpers::timer();
     }
     // NOTE: The vector temp_vec now contains the vector r_p.
     // Solve first pressure Poisson system
 #ifdef PARANOID
     // check a solver has been set
     if (P_preconditioner_pt == 0)
     {
       std::ostringstream error_message;
       error_message << "P_preconditioner_pt has not been set.";
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // use some Preconditioner's preconditioner_solve function
     P_preconditioner_pt->preconditioner_solve(temp_vec, another_temp_vec);
     if (Doc_time)
     {
       t_end = TimingHelpers::timer();
       oomph_info << "LSC prec solve: First P solve [nrow="
                  << P_preconditioner_pt->nrow() << "]: " << t_end - t_start
                  << std::endl;
       t_start = TimingHelpers::timer();
     }
     // NOTE: The vector another_temp_vec now contains the vector P^{-1} r_p
     // Multiply another_temp_vec by matrix E and stick the result into temp_vec
     temp_vec.clear();
     if (Form_BFBt_product)
     {
       E_mat_vec_pt->multiply(another_temp_vec, temp_vec);
     }
     else
     {
       QBt_mat_vec_pt->multiply(another_temp_vec, temp_vec);
       another_temp_vec.clear();
       F_mat_vec_pt->multiply(temp_vec, another_temp_vec);
       temp_vec.clear();
       QBt_mat_vec_pt->multiply_transpose(another_temp_vec, temp_vec);
     }
     if (Doc_time)
     {
       t_end = TimingHelpers::timer();
       oomph_info << "LSC prec solve: E matrix vector product: "
                  << t_end - t_start << std::endl;
       t_start = TimingHelpers::timer();
     }
     // NOTE: The vector temp_vec now contains E P^{-1} r_p
     // Solve second pressure Poisson system using preconditioner_solve
     another_temp_vec.clear();
     P_preconditioner_pt->preconditioner_solve(temp_vec, another_temp_vec);
     if (Doc_time)
     {
       t_end = TimingHelpers::timer();
       oomph_info << "LSC prec solve: Second P solve [nrow="
                  << P_preconditioner_pt->nrow() << "]: " << t_end - t_start
                  << std::endl;
       t_start = TimingHelpers::timer();
     }
     // NOTE: The vector another_temp_vec now contains  z_p = P^{-1} E P^{-1} r_p
     //       as required (apart from the sign which we'll fix in the
     //       next step.
     // Now copy another_temp_vec (i.e. z_p) back into the global vector z.
     // Loop over all entries in the global results vector z:
     temp_vec.build(another_temp_vec.distribution_pt(), 0.0);
     temp_vec -= another_temp_vec;
     return_block_vector(1, temp_vec, z);
     // Step 2 - apply preconditioner to displacement/positon unknowns (block 0)
     // ------------------------------------------------------------------------
     // Recall that another_temp_vec (computed above) contains the
     // negative of the solution of the Schur complement systen, -z_p.
     // Multiply by G (stored in Block_matrix_pt(0,1) and store
     // result in temp_vec (vector resizes itself).
     temp_vec.clear();
     Bt_mat_vec_pt->multiply(another_temp_vec, temp_vec);
     if (Doc_time)
     {
       t_end = TimingHelpers::timer();
       oomph_info << "LSC prec solve: G matrix vector product: "
                  << t_end - t_start << std::endl;
       t_start = TimingHelpers::timer();
     }
     // NOTE: temp_vec now contains -G z_p
     // The vector another_temp_vec is no longer needed -- re-use it to store
     // displacement/position quantities:
     another_temp_vec.clear();
     // Loop over all enries in the global vector and find the
     // entries associated with the displacement/position:
     get_block_vector(0, r, another_temp_vec);
     another_temp_vec += temp_vec;
     // NOTE:  The vector another_temp_vec now contains r_u - G z_p
     // Solve momentum system
 #ifdef PARANOID
     // check a solver has been set
     if (F_preconditioner_pt == 0)
     {
       std::ostringstream error_message;
       error_message << "F_preconditioner_pt has not been set.";
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // use some Preconditioner's preconditioner solve
     // and return
     if (F_preconditioner_is_block_preconditioner)
     {
       return_block_vector(0, another_temp_vec, z);
       F_preconditioner_pt->preconditioner_solve(z, z);
     }
     else
     {
       F_preconditioner_pt->preconditioner_solve(another_temp_vec, temp_vec);
       return_block_vector(0, temp_vec, z);
     }
     if (Doc_time)
     {
       t_end = TimingHelpers::timer();
       oomph_info << "LSC prec solve: F solve [nrow="
                  << P_preconditioner_pt->nrow() << "]: " << t_end - t_start
                  << std::endl;
       oomph_info << "LSC prec solve: Overall " << t_end - t_start_overall
                  << std::endl;
     }
   }
References Bt_mat_vec_pt, oomph::DoubleVector::build(), oomph::DoubleVector::built(), oomph::DoubleVector::clear(), oomph::DistributableLinearAlgebraObject::distribution_pt(), Doc_time, E_mat_vec_pt, F_mat_vec_pt, F_preconditioner_is_block_preconditioner, F_preconditioner_pt, Form_BFBt_product, oomph::BlockPreconditioner< CRDoubleMatrix >::get_block_vector(), oomph::MatrixVectorProduct::multiply(), oomph::MatrixVectorProduct::multiply_transpose(), oomph::DistributableLinearAlgebraObject::nrow(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, P_preconditioner_pt, Preconditioner_has_been_setup, oomph::Preconditioner::preconditioner_solve(), QBt_mat_vec_pt, UniformPSDSelfTest::r, oomph::BlockPreconditioner< CRDoubleMatrix >::return_block_vector(), and oomph::TimingHelpers::timer().
set_f_preconditioner()
void oomph::PressureBasedSolidLSCPreconditioner::set_f_preconditioner (Preconditioner * new_f_preconditioner_pt) inline
Function to set a new momentum matrix preconditioner (inexact solver)
     {
       // If the default preconditioner has been used
       // clean it up now...
       if (Using_default_f_preconditioner)
       {
         delete F_preconditioner_pt;
       }
       F_preconditioner_pt = new_f_preconditioner_pt;
       Using_default_f_preconditioner = false;
     }
References F_preconditioner_pt, and Using_default_f_preconditioner.
set_f_superlu_preconditioner()
void oomph::PressureBasedSolidLSCPreconditioner::set_f_superlu_preconditioner () inline
Function to (re-)set momentum matrix preconditioner (inexact solver) to SuperLU
     {
       if (!Using_default_f_preconditioner)
       {
         F_preconditioner_pt = new SuperLUPreconditioner;
         Using_default_f_preconditioner = true;
       }
     }
References F_preconditioner_pt, and Using_default_f_preconditioner.
set_p_preconditioner()
void oomph::PressureBasedSolidLSCPreconditioner::set_p_preconditioner (Preconditioner * new_p_preconditioner_pt) inline
Function to set a new pressure matrix preconditioner (inexact solver)
     {
       // If the default preconditioner has been used
       // clean it up now...
       if (Using_default_p_preconditioner)
       {
         delete P_preconditioner_pt;
       }
       P_preconditioner_pt = new_p_preconditioner_pt;
       Using_default_p_preconditioner = false;
     }
References P_preconditioner_pt, and Using_default_p_preconditioner.
set_p_superlu_preconditioner()
void oomph::PressureBasedSolidLSCPreconditioner::set_p_superlu_preconditioner () inline
Function to (re-)set pressure matrix preconditioner (inexact solver) to SuperLU
     {
       if (!Using_default_p_preconditioner)
       {
         P_preconditioner_pt = new SuperLUPreconditioner;
         Using_default_p_preconditioner = true;
       }
     }
References P_preconditioner_pt, and Using_default_p_preconditioner.
set_solid_mesh()
void oomph::PressureBasedSolidLSCPreconditioner::set_solid_mesh (Mesh * mesh_pt) inline
specify the mesh containing the mesh containing the block-preconditionable solid elements. The dimension of the problem must also be specified.
     {
       Solid_mesh_pt = mesh_pt;
     }
References oomph::BlockPreconditioner< CRDoubleMatrix >::mesh_pt(), and Solid_mesh_pt.
setup()
void oomph::PressureBasedSolidLSCPreconditioner::setup () virtual
Broken assignment operator.
Setup the preconditioner
Setup the least-squares commutator solid preconditioner. This extracts blocks corresponding to the position/displacement and pressure unknowns, creates the matrices actually needed in the application of the preconditioner and deletes what can be deleted... Note that this preconditioner needs a CRDoubleMatrix.
Implements oomph::Preconditioner.
   {
     //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     // NOTE: In the interest of minimising memory usage, several containers
     //       are recycled, therefore their content/meaning changes
     //       throughout this function. The code is carefully annotated
     //       but you'll have to read it line by line!
     //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     // make sure any old data is deleted
     clean_up_memory();
 #ifdef PARANOID
     // paranoid check that the solid mesh pt has been set
     if (Solid_mesh_pt == 0)
     {
       std::ostringstream error_message;
       error_message << "The solid mesh pointer must be set.\n"
                     << "Use method set_solid_mesh(...)";
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // set the mesh
     this->set_mesh(0, Solid_mesh_pt);
     // Get blocks
     // ----------
     // Set up block look up schemes (done automatically in the
     // BlockPreconditioner base class, based on the information
     // provided in the block-preconditionable elements in the problem)
     // this preconditioner has two types of block:
     // type 0: displacement/positions - corresponding to DOFs 0 to n-2
     // type 1: pressure - corresponding to DOF n-1
     double t_block_start = TimingHelpers::timer();
     unsigned ndof_types = 0;
     if (this->is_subsidiary_block_preconditioner())
     {
       ndof_types = this->ndof_types();
     }
     else
     {
       ndof_types = this->ndof_types_in_mesh(0);
     }
     Vector<unsigned> dof_to_block_map(ndof_types);
     dof_to_block_map[ndof_types - 1] = 1;
     this->block_setup(dof_to_block_map);
     double t_block_finish = TimingHelpers::timer();
     double block_setup_time = t_block_finish - t_block_start;
     if (Doc_time)
     {
       oomph_info << "Time for block_setup(...) [sec]: " << block_setup_time
                  << "\n";
     }
     // determine whether the F preconditioner is a block preconditioner (and
     // therefore a subsidiary preconditioner)
     BlockPreconditioner<CRDoubleMatrix>* F_block_preconditioner_pt =
       dynamic_cast<BlockPreconditioner<CRDoubleMatrix>*>(F_preconditioner_pt);
     F_preconditioner_is_block_preconditioner = true;
     if (F_block_preconditioner_pt == 0)
     {
       F_preconditioner_is_block_preconditioner = false;
     }
     // Get B (the divergence block)
     double t_get_B_start = TimingHelpers::timer();
     CRDoubleMatrix* b_pt = new CRDoubleMatrix;
     this->get_block(1, 0, *b_pt);
     double t_get_B_finish = TimingHelpers::timer();
     if (Doc_time)
     {
       double get_B_time = t_get_B_finish - t_get_B_start;
       oomph_info << "Time to get B [sec]: " << get_B_time << "\n";
     }
     // the pointer for f
     CRDoubleMatrix* f_pt = new CRDoubleMatrix;
     // the pointer for the p matrix
     CRDoubleMatrix* p_matrix_pt = new CRDoubleMatrix;
     // the pointer for bt
     CRDoubleMatrix* bt_pt = new CRDoubleMatrix;
     // if BFBt is to be formed
     if (Form_BFBt_product)
     {
       // If using scaling then replace B with Bt
       CRDoubleMatrix* ivmm_pt = 0;
       if (P_matrix_using_scaling)
       {
         // Assemble the ivmm diagonal
         double ivmm_assembly_start_t = TimingHelpers::timer();
         ivmm_pt = assemble_mass_matrix_diagonal();
         double ivmm_assembly_finish_t = TimingHelpers::timer();
         if (Doc_time)
         {
           double ivmm_assembly_time =
             ivmm_assembly_finish_t - ivmm_assembly_start_t;
           oomph_info << "Time to assemble inverse mass matrix [sec]: "
                      << ivmm_assembly_time << "\n";
         }
         // assemble BQ (stored in B)
         double t_BQ_start = TimingHelpers::timer();
         CRDoubleMatrix* temp_matrix_pt = new CRDoubleMatrix;
         b_pt->multiply(*ivmm_pt, *temp_matrix_pt);
         delete b_pt;
         b_pt = 0;
         b_pt = temp_matrix_pt;
         double t_BQ_finish = TimingHelpers::timer();
         if (Doc_time)
         {
           double t_BQ_time = t_BQ_finish - t_BQ_start;
           oomph_info << "Time to generate BQ [sec]: " << t_BQ_time << std::endl;
         }
       }
       // Get Bt
       double t_get_Bt_start = TimingHelpers::timer();
       this->get_block(0, 1, *bt_pt);
       double t_get_Bt_finish = TimingHelpers::timer();
       if (Doc_time)
       {
         double t_get_Bt_time = t_get_Bt_finish - t_get_Bt_start;
         oomph_info << "Time to get Bt [sec]: " << t_get_Bt_time << std::endl;
       }
       // now form the P matrix by multiplying B (which if using scaling will be
       // BQ) with Bt
       double t_P_start = TimingHelpers::timer();
       b_pt->multiply(*bt_pt, *p_matrix_pt);
       double t_P_finish = TimingHelpers::timer();
       if (Doc_time)
       {
         double t_P_time = t_P_finish - t_P_start;
         oomph_info << "Time to generate P matrix [sec]: " << t_P_time
                    << std::endl;
       }
       // Multiply auxiliary matrix by diagonal of mass matrix if
       // required
       if (P_matrix_using_scaling)
       {
         CRDoubleMatrix* temp_matrix_pt = new CRDoubleMatrix;
         double t_QBt_start = TimingHelpers::timer();
         ivmm_pt->multiply(*bt_pt, *temp_matrix_pt);
         delete bt_pt;
         bt_pt = 0;
         bt_pt = temp_matrix_pt;
         double t_QBt_finish = TimingHelpers::timer();
         // Output times
         if (Doc_time)
         {
           double t_QBt_time = t_QBt_finish - t_QBt_start;
           oomph_info << "Time to generate QBt [sec]: " << t_QBt_time
                      << std::endl;
         }
       }
       // Clean up memory
       delete ivmm_pt;
       // get block 0 0
       double t_get_F_start = TimingHelpers::timer();
       this->get_block(0, 0, *f_pt);
       double t_get_F_finish = TimingHelpers::timer();
       if (Doc_time)
       {
         double t_get_F_time = t_get_F_finish - t_get_F_start;
         oomph_info << "Time to get F [sec]: " << t_get_F_time << std::endl;
       }
       // Auxiliary matrix for intermediate results
       double t_aux_matrix_start = TimingHelpers::timer();
       CRDoubleMatrix* aux_matrix_pt = new CRDoubleMatrix;
       f_pt->multiply(*bt_pt, *aux_matrix_pt);
       double t_aux_matrix_finish = TimingHelpers::timer();
       if (Doc_time)
       {
         double t_aux_time = t_aux_matrix_finish - t_aux_matrix_start;
         oomph_info << "Time to generate FQBt [sec]: " << t_aux_time
                    << std::endl;
       }
       // can now delete Bt (or QBt if using scaling)
       delete bt_pt;
       bt_pt = 0;
       // and if F requires a block preconditioner then we can delete F
       if (F_preconditioner_is_block_preconditioner)
       {
         delete f_pt;
       }
       // now form BFBt
       double t_E_matrix_start = TimingHelpers::timer();
       CRDoubleMatrix* e_matrix_pt = new CRDoubleMatrix;
       b_pt->multiply(*aux_matrix_pt, *e_matrix_pt);
       delete aux_matrix_pt;
       delete b_pt;
       double t_E_matrix_finish = TimingHelpers::timer();
       if (Doc_time)
       {
         double t_E_time = t_E_matrix_finish - t_E_matrix_start;
         oomph_info << "Time to generate E (B*(F*Bt)) [sec]: " << t_E_time
                    << std::endl;
       }
       double t_E_matvec_start = TimingHelpers::timer();
       E_mat_vec_pt = new MatrixVectorProduct;
       // E_mat_vec_pt->setup(e_matrix_pt);
       this->setup_matrix_vector_product(E_mat_vec_pt, e_matrix_pt, 1);
       double t_E_matvec_finish = TimingHelpers::timer();
       delete e_matrix_pt;
       if (Doc_time)
       {
         double t_E_time = t_E_matvec_finish - t_E_matvec_start;
         oomph_info << "Time to build E (BFBt) matrix vector operator E [sec]: "
                    << t_E_time << std::endl;
       }
       // and rebuild Bt
       t_get_Bt_start = TimingHelpers::timer();
       bt_pt = new CRDoubleMatrix;
       this->get_block(0, 1, *bt_pt);
       t_get_Bt_finish = TimingHelpers::timer();
       if (Doc_time)
       {
         double t_get_Bt_time = t_get_Bt_finish - t_get_Bt_start;
         oomph_info << "Time to get Bt [sec]: " << t_get_Bt_time << std::endl;
       }
     }
     // otherwise we are not forming BFBt
     else
     {
       // get the inverse mass matrix (Q)
       CRDoubleMatrix* ivmm_pt = 0;
       if (P_matrix_using_scaling)
       {
         double ivmm_assembly_start_t = TimingHelpers::timer();
         ivmm_pt = assemble_mass_matrix_diagonal();
         double ivmm_assembly_finish_t = TimingHelpers::timer();
         if (Doc_time)
         {
           double ivmm_assembly_time =
             ivmm_assembly_finish_t - ivmm_assembly_start_t;
           oomph_info << "Time to assemble Q (inverse diagonal "
                      << "mass matrix) [sec]: " << ivmm_assembly_time << "\n";
         }
       }
       // Get Bt
       double t_get_Bt_start = TimingHelpers::timer();
       this->get_block(0, 1, *bt_pt);
       double t_get_Bt_finish = TimingHelpers::timer();
       if (Doc_time)
       {
         double t_get_Bt_time = t_get_Bt_finish - t_get_Bt_start;
         oomph_info << "Time to get Bt [sec]: " << t_get_Bt_time << std::endl;
       }
       // next QBt
       if (P_matrix_using_scaling)
       {
         double t_QBt_matrix_start = TimingHelpers::timer();
         CRDoubleMatrix* qbt_pt = new CRDoubleMatrix;
         ivmm_pt->multiply(*bt_pt, *qbt_pt);
         delete bt_pt;
         bt_pt = 0;
         bt_pt = qbt_pt;
         double t_QBt_matrix_finish = TimingHelpers::timer();
         if (Doc_time)
         {
           double t_QBt_time = t_QBt_matrix_finish - t_QBt_matrix_start;
           oomph_info << "Time to generate QBt [sec]: " << t_QBt_time
                      << std::endl;
         }
         delete ivmm_pt;
       }
       // form P
       double t_p_matrix_start = TimingHelpers::timer();
       b_pt->multiply(*bt_pt, *p_matrix_pt);
       double t_p_matrix_finish = TimingHelpers::timer();
       if (Doc_time)
       {
         double t_p_time = t_p_matrix_finish - t_p_matrix_start;
         oomph_info << "Time to generate P [sec]: " << t_p_time << std::endl;
       }
       delete b_pt;
       b_pt = 0;
       // build the matvec operator for QBt
       double t_QBt_MV_start = TimingHelpers::timer();
       QBt_mat_vec_pt = new MatrixVectorProduct;
       // QBt_mat_vec_pt->setup(bt_pt);
       this->setup_matrix_vector_product(QBt_mat_vec_pt, bt_pt, 1);
       double t_QBt_MV_finish = TimingHelpers::timer();
       if (Doc_time)
       {
         double t_p_time = t_QBt_MV_finish - t_QBt_MV_start;
         oomph_info << "Time to build QBt matrix vector operator [sec]: "
                    << t_p_time << std::endl;
       }
       delete bt_pt;
       bt_pt = 0;
       // get F
       double t_get_F_start = TimingHelpers::timer();
       this->get_block(0, 0, *f_pt);
       double t_get_F_finish = TimingHelpers::timer();
       if (Doc_time)
       {
         double t_get_F_time = t_get_F_finish - t_get_F_start;
         oomph_info << "Time to get F [sec]: " << t_get_F_time << std::endl;
       }
       // form the matrix vector product helper
       double t_F_MV_start = TimingHelpers::timer();
       F_mat_vec_pt = new MatrixVectorProduct;
       // F_mat_vec_pt->setup(f_pt);
       this->setup_matrix_vector_product(F_mat_vec_pt, f_pt, 0);
       double t_F_MV_finish = TimingHelpers::timer();
       if (Doc_time)
       {
         double t_F_MV_time = t_F_MV_finish - t_F_MV_start;
         oomph_info << "Time to build F Matrix Vector Operator [sec]: "
                    << t_F_MV_time << std::endl;
       }
       // if F is a block preconditioner then we can delete the F matrix
       if (F_preconditioner_is_block_preconditioner)
       {
         delete f_pt;
         f_pt = 0;
       }
       // and rebuild Bt
       t_get_Bt_start = TimingHelpers::timer();
       bt_pt = new CRDoubleMatrix;
       this->get_block(0, 1, *bt_pt);
       t_get_Bt_finish = TimingHelpers::timer();
       if (Doc_time)
       {
         double t_get_Bt_time = t_get_Bt_finish - t_get_Bt_start;
         oomph_info << "Time to get Bt [sec]: " << t_get_Bt_time << std::endl;
       }
     }
     // form the matrix vector operator for Bt
     double t_Bt_MV_start = TimingHelpers::timer();
     Bt_mat_vec_pt = new MatrixVectorProduct;
     // Bt_mat_vec_pt->setup(bt_pt);
     this->setup_matrix_vector_product(Bt_mat_vec_pt, bt_pt, 1);
     double t_Bt_MV_finish = TimingHelpers::timer();
     if (Doc_time)
     {
       double t_Bt_MV_time = t_Bt_MV_finish - t_Bt_MV_start;
       oomph_info << "Time to build Bt Matrix Vector Operator [sec]: "
                  << t_Bt_MV_time << std::endl;
     }
     delete bt_pt;
     bt_pt = 0;
     // if the P preconditioner has not been setup
     if (P_preconditioner_pt == 0)
     {
       P_preconditioner_pt = new SuperLUPreconditioner;
       Using_default_p_preconditioner = true;
     }
     // std::stringstream junk;
     // junk << "p_matrix" << comm_pt()->my_rank()
     //      << ".dat";
     // p_matrix_pt->sparse_indexed_output_with_offset(junk.str());
     // oomph_info << "Done output of " << junk.str() << std::endl;
     // Setup the preconditioner for the Pressure matrix
     double t_p_prec_start = TimingHelpers::timer();
     P_preconditioner_pt->setup(p_matrix_pt);
     delete p_matrix_pt;
     p_matrix_pt = 0;
     p_matrix_pt = 0;
     double t_p_prec_finish = TimingHelpers::timer();
     if (Doc_time)
     {
       double t_p_prec_time = t_p_prec_finish - t_p_prec_start;
       oomph_info << "P sub-preconditioner setup time [sec]: " << t_p_prec_time
                  << "\n";
     }
     // Set up solver for solution of system with momentum matrix
     // ----------------------------------------------------------
     // if the F preconditioner has not been setup
     if (F_preconditioner_pt == 0)
     {
       F_preconditioner_pt = new SuperLUPreconditioner;
       Using_default_f_preconditioner = true;
     }
     // if F is a block preconditioner
     double t_f_prec_start = TimingHelpers::timer();
     if (F_preconditioner_is_block_preconditioner)
     {
       unsigned ndof_types = this->ndof_types();
       ndof_types--;
       Vector<unsigned> dof_map(ndof_types);
       for (unsigned i = 0; i < ndof_types; i++)
       {
         dof_map[i] = i;
       }
       F_block_preconditioner_pt->turn_into_subsidiary_block_preconditioner(
         this, dof_map);
       F_block_preconditioner_pt->setup(matrix_pt());
     }
     // otherwise F is not a block preconditioner
     else
     {
       F_preconditioner_pt->setup(f_pt);
       delete f_pt;
       f_pt = 0;
     }
     double t_f_prec_finish = TimingHelpers::timer();
     if (Doc_time)
     {
       double t_f_prec_time = t_f_prec_finish - t_f_prec_start;
       oomph_info << "F sub-preconditioner setup time [sec]: " << t_f_prec_time
                  << "\n";
     }
     // Remember that the preconditioner has been setup so
     // the stored information can be wiped when we
     // come here next...
     Preconditioner_has_been_setup = true;
   }
References assemble_mass_matrix_diagonal(), oomph::BlockPreconditioner< CRDoubleMatrix >::block_setup(), Bt_mat_vec_pt, clean_up_memory(), Doc_time, E_mat_vec_pt, F_mat_vec_pt, F_preconditioner_is_block_preconditioner, F_preconditioner_pt, Form_BFBt_product, oomph::BlockPreconditioner< CRDoubleMatrix >::get_block(), i, oomph::BlockPreconditioner< CRDoubleMatrix >::is_subsidiary_block_preconditioner(), oomph::BlockPreconditioner< CRDoubleMatrix >::matrix_pt(), oomph::CRDoubleMatrix::multiply(), oomph::BlockPreconditioner< CRDoubleMatrix >::ndof_types(), oomph::BlockPreconditioner< CRDoubleMatrix >::ndof_types_in_mesh(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, P_matrix_using_scaling, P_preconditioner_pt, Preconditioner_has_been_setup, QBt_mat_vec_pt, oomph::BlockPreconditioner< CRDoubleMatrix >::set_mesh(), oomph::Preconditioner::setup(), oomph::BlockPreconditioner< CRDoubleMatrix >::setup_matrix_vector_product(), Solid_mesh_pt, oomph::TimingHelpers::timer(), oomph::BlockPreconditioner< MATRIX >::turn_into_subsidiary_block_preconditioner(), Using_default_f_preconditioner, and Using_default_p_preconditioner.
Member Data Documentation
Bt_mat_vec_pt
MatrixVectorProduct* oomph::PressureBasedSolidLSCPreconditioner::Bt_mat_vec_pt private
MatrixVectorProduct operator for Bt;.
Referenced by clean_up_memory(), preconditioner_solve(), PressureBasedSolidLSCPreconditioner(), and setup().
Doc_time
bool oomph::PressureBasedSolidLSCPreconditioner::Doc_time private
Set Doc_time to true for outputting results of timings.
Referenced by disable_doc_time(), enable_doc_time(), preconditioner_solve(), PressureBasedSolidLSCPreconditioner(), and setup().
E_mat_vec_pt
MatrixVectorProduct* oomph::PressureBasedSolidLSCPreconditioner::E_mat_vec_pt private
MatrixVectorProduct operator for E (BFBt) if BFBt is to be formed.
Referenced by clean_up_memory(), preconditioner_solve(), PressureBasedSolidLSCPreconditioner(), and setup().
F_mat_vec_pt
MatrixVectorProduct* oomph::PressureBasedSolidLSCPreconditioner::F_mat_vec_pt private
MatrixVectorProduct operator for F if BFBt is not to be formed.
Referenced by clean_up_memory(), preconditioner_solve(), PressureBasedSolidLSCPreconditioner(), and setup().
F_preconditioner_is_block_preconditioner
bool oomph::PressureBasedSolidLSCPreconditioner::F_preconditioner_is_block_preconditioner private
Boolean indicating whether the momentum system preconditioner is a block preconditioner
Referenced by preconditioner_solve(), and setup().
F_preconditioner_pt
Preconditioner* oomph::PressureBasedSolidLSCPreconditioner::F_preconditioner_pt private
Pointer to the 'preconditioner' for the F matrix.
Referenced by clean_up_memory(), preconditioner_solve(), PressureBasedSolidLSCPreconditioner(), set_f_preconditioner(), set_f_superlu_preconditioner(), and setup().
Form_BFBt_product
bool oomph::PressureBasedSolidLSCPreconditioner::Form_BFBt_product private
indicates whether BFBt should be formed or the component matrices should be retained. If true then: in setup(...) : BFBt is computed. in preconditioner_solve(...) : a single matrix vector product with BFBt is performed. if false then: in setup(...) : the matrices B, F are assembled and stored. in preconditioner_solve(...) : a sequence of matrix vector products with B, F, and Bt is performed. (Note: in this discussion no scaling was considered but B and Bt are replaced with BQ and QBt with scaling)
Referenced by clean_up_memory(), disable_form_BFBt_product(), enable_form_BFBt_product(), preconditioner_solve(), PressureBasedSolidLSCPreconditioner(), and setup().
P_matrix_using_scaling
bool oomph::PressureBasedSolidLSCPreconditioner::P_matrix_using_scaling private
Control flag is true if mass matrix diagonal scaling is used in the Schur complement approximation
Referenced by disable_p_matrix_scaling(), enable_p_matrix_scaling(), is_p_matrix_using_scaling(), PressureBasedSolidLSCPreconditioner(), and setup().
P_preconditioner_pt
Preconditioner* oomph::PressureBasedSolidLSCPreconditioner::P_preconditioner_pt private
Pointer to the 'preconditioner' for the pressure matrix.
Referenced by clean_up_memory(), preconditioner_solve(), PressureBasedSolidLSCPreconditioner(), set_p_preconditioner(), set_p_superlu_preconditioner(), and setup().
Preconditioner_has_been_setup
bool oomph::PressureBasedSolidLSCPreconditioner::Preconditioner_has_been_setup private
Control flag is true if the preconditioner has been setup (used so we can wipe the data when the preconditioner is called again)
Referenced by clean_up_memory(), preconditioner_solve(), PressureBasedSolidLSCPreconditioner(), and setup().
QBt_mat_vec_pt
MatrixVectorProduct* oomph::PressureBasedSolidLSCPreconditioner::QBt_mat_vec_pt private
MatrixVectorProduct operator for QBt if BFBt is not to be formed.
Referenced by clean_up_memory(), preconditioner_solve(), PressureBasedSolidLSCPreconditioner(), and setup().
Solid_mesh_pt
Mesh* oomph::PressureBasedSolidLSCPreconditioner::Solid_mesh_pt private
the pointer to the mesh of block preconditionable solid elements.
Referenced by assemble_mass_matrix_diagonal(), PressureBasedSolidLSCPreconditioner(), set_solid_mesh(), and setup().
Using_default_f_preconditioner
bool oomph::PressureBasedSolidLSCPreconditioner::Using_default_f_preconditioner private
flag indicating whether the default F preconditioner is used
Referenced by clean_up_memory(), PressureBasedSolidLSCPreconditioner(), set_f_preconditioner(), set_f_superlu_preconditioner(), and setup().
Using_default_p_preconditioner
bool oomph::PressureBasedSolidLSCPreconditioner::Using_default_p_preconditioner private
flag indicating whether the default P preconditioner is used
Referenced by clean_up_memory(), PressureBasedSolidLSCPreconditioner(), set_p_preconditioner(), set_p_superlu_preconditioner(), and setup().
The documentation for this class was generated from the following files:
solid_preconditioners.h
solid_preconditioners.cc