MercuryDPM: Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, Version > Struct Template Reference
Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, Version > Struct Template Reference
#include <TriangularMatrixMatrix.h>
Public Types
enum { SmallPanelWidth = plain_enum_max(Traits::mr, Traits::nr) , IsLower = (Mode & Lower) == Lower , SetDiag = (Mode & (ZeroDiag | UnitDiag)) ? 0 : 1 }
typedef gebp_traits< Scalar, Scalar > Traits
Static Public Member Functions
static EIGEN_DONT_INLINE void run (Index _rows, Index _cols, Index _depth, const Scalar *lhs_, Index lhsStride, const Scalar *rhs_, Index rhsStride, Scalar *res, Index resIncr, Index resStride, const Scalar &alpha, level3_blocking< Scalar, Scalar > &blocking)
Member Typedef Documentation
Traits
template<typename Scalar , typename Index , int Mode, int LhsStorageOrder, bool ConjugateLhs, int RhsStorageOrder, bool ConjugateRhs, int ResInnerStride, int Version> typedef gebp_traits<Scalar, Scalar> Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, Version >::Traits
Member Enumeration Documentation
anonymous enum
template<typename Scalar , typename Index , int Mode, int LhsStorageOrder, bool ConjugateLhs, int RhsStorageOrder, bool ConjugateRhs, int ResInnerStride, int Version> anonymous enum
Enumerator
SmallPanelWidth
IsLower
SetDiag
        {
     SmallPanelWidth = plain_enum_max(Traits::mr, Traits::nr),
     IsLower = (Mode & Lower) == Lower,
     SetDiag = (Mode & (ZeroDiag | UnitDiag)) ? 0 : 1
   };
Member Function Documentation
run()
template<typename Scalar , typename Index , int Mode, int LhsStorageOrder, bool ConjugateLhs, int RhsStorageOrder, bool ConjugateRhs, int ResInnerStride, int Version> EIGEN_DONT_INLINE void Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, Version >::run (Index _rows, Index _cols, Index _depth, const Scalar * lhs_, Index lhsStride, const Scalar * rhs_, Index rhsStride, Scalar * res, Index resIncr, Index resStride, const Scalar & alpha, level3_blocking< Scalar, Scalar > & blocking) static
{
   const Index PacketBytes = packet_traits<Scalar>::size * sizeof(Scalar);
   // strip zeros
   Index diagSize = (std::min)(_cols, _depth);
   Index rows = _rows;
   Index depth = IsLower ? _depth : diagSize;
   Index cols = IsLower ? diagSize : _cols;
   typedef const_blas_data_mapper<Scalar, Index, LhsStorageOrder> LhsMapper;
   typedef const_blas_data_mapper<Scalar, Index, RhsStorageOrder> RhsMapper;
   typedef blas_data_mapper<typename Traits::ResScalar, Index, ColMajor, Unaligned, ResInnerStride> ResMapper;
   LhsMapper lhs(lhs_, lhsStride);
   RhsMapper rhs(rhs_, rhsStride);
   ResMapper res(res_, resStride, resIncr);
   Index kc = blocking.kc();                    // cache block size along the K direction
   Index mc = (std::min)(rows, blocking.mc());  // cache block size along the M direction
   std::size_t sizeA = kc * mc;
   std::size_t sizeB = kc * cols + EIGEN_MAX_ALIGN_BYTES / sizeof(Scalar);
   ei_declare_aligned_stack_constructed_variable(Scalar, blockA, sizeA, blocking.blockA());
   ei_declare_aligned_stack_constructed_variable(Scalar, blockB, sizeB, blocking.blockB());
   Matrix<Scalar, SmallPanelWidth, SmallPanelWidth, RhsStorageOrder> triangularBuffer;
   triangularBuffer.setZero();
   if ((Mode & ZeroDiag) == ZeroDiag)
     triangularBuffer.diagonal().setZero();
   else
     triangularBuffer.diagonal().setOnes();
   gebp_kernel<Scalar, Scalar, Index, ResMapper, Traits::mr, Traits::nr, ConjugateLhs, ConjugateRhs> gebp_kernel;
   gemm_pack_lhs<Scalar, Index, LhsMapper, Traits::mr, Traits::LhsProgress, typename Traits::LhsPacket4Packing,
                 LhsStorageOrder>
       pack_lhs;
   gemm_pack_rhs<Scalar, Index, RhsMapper, Traits::nr, RhsStorageOrder> pack_rhs;
   gemm_pack_rhs<Scalar, Index, RhsMapper, Traits::nr, RhsStorageOrder, false, true> pack_rhs_panel;
   for (Index k2 = IsLower ? 0 : depth; IsLower ? k2 < depth : k2 > 0; IsLower ? k2 += kc : k2 -= kc) {
     Index actual_kc = (std::min)(IsLower ? depth - k2 : k2, kc);
     Index actual_k2 = IsLower ? k2 : k2 - actual_kc;
     // align blocks with the end of the triangular part for trapezoidal rhs
     if (IsLower && (k2 < cols) && (actual_k2 + actual_kc > cols)) {
       actual_kc = cols - k2;
       k2 = actual_k2 + actual_kc - kc;
     }
     // remaining size
     Index rs = IsLower ? (std::min)(cols, actual_k2) : cols - k2;
     // size of the triangular part
     Index ts = (IsLower && actual_k2 >= cols) ? 0 : actual_kc;
     Scalar* geb = blockB + ts * ts;
     geb = geb + internal::first_aligned<PacketBytes>(geb, PacketBytes / sizeof(Scalar));
     pack_rhs(geb, rhs.getSubMapper(actual_k2, IsLower ? 0 : k2), actual_kc, rs);
     // pack the triangular part of the rhs padding the unrolled blocks with zeros
     if (ts > 0) {
       for (Index j2 = 0; j2 < actual_kc; j2 += SmallPanelWidth) {
         Index actualPanelWidth = std::min<Index>(actual_kc - j2, SmallPanelWidth);
         Index actual_j2 = actual_k2 + j2;
         Index panelOffset = IsLower ? j2 + actualPanelWidth : 0;
         Index panelLength = IsLower ? actual_kc - j2 - actualPanelWidth : j2;
         // general part
         pack_rhs_panel(blockB + j2 * actual_kc, rhs.getSubMapper(actual_k2 + panelOffset, actual_j2), panelLength,
                        actualPanelWidth, actual_kc, panelOffset);
         // append the triangular part via a temporary buffer
         for (Index j = 0; j < actualPanelWidth; ++j) {
           if (SetDiag) triangularBuffer.coeffRef(j, j) = rhs(actual_j2 + j, actual_j2 + j);
           for (Index k = IsLower ? j + 1 : 0; IsLower ? k < actualPanelWidth : k < j; ++k)
             triangularBuffer.coeffRef(k, j) = rhs(actual_j2 + k, actual_j2 + j);
         }
         pack_rhs_panel(blockB + j2 * actual_kc, RhsMapper(triangularBuffer.data(), triangularBuffer.outerStride()),
                        actualPanelWidth, actualPanelWidth, actual_kc, j2);
       }
     }
     for (Index i2 = 0; i2 < rows; i2 += mc) {
       const Index actual_mc = (std::min)(mc, rows - i2);
       pack_lhs(blockA, lhs.getSubMapper(i2, actual_k2), actual_kc, actual_mc);
       // triangular kernel
       if (ts > 0) {
         for (Index j2 = 0; j2 < actual_kc; j2 += SmallPanelWidth) {
           Index actualPanelWidth = std::min<Index>(actual_kc - j2, SmallPanelWidth);
           Index panelLength = IsLower ? actual_kc - j2 : j2 + actualPanelWidth;
           Index blockOffset = IsLower ? j2 : 0;
           gebp_kernel(res.getSubMapper(i2, actual_k2 + j2), blockA, blockB + j2 * actual_kc, actual_mc, panelLength,
                       actualPanelWidth, alpha, actual_kc, actual_kc,  // strides
                       blockOffset, blockOffset);                      // offsets
         }
       }
       gebp_kernel(res.getSubMapper(i2, IsLower ? 0 : k2), blockA, geb, actual_mc, actual_kc, rs, alpha, -1, -1, 0, 0);
     }
   }
 }
References alpha, Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::blockA(), Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::blockB(), Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::coeffRef(), cols, Eigen::PlainObjectBase< Derived >::data(), ei_declare_aligned_stack_constructed_variable, EIGEN_MAX_ALIGN_BYTES, j, k, Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::kc(), Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::mc(), min, Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::outerStride(), res, rows, Eigen::PlainObjectBase< Derived >::setOnes(), Eigen::PlainObjectBase< Derived >::setZero(), and Eigen::ZeroDiag.
The documentation for this struct was generated from the following file:
TriangularMatrixMatrix.h