MercuryDPM: SilbertPeriodic Class Reference
SilbertPeriodic Class Reference
#include <GlasPeriodic.h>
Public Member Functions
SilbertPeriodic ()
virtual void createBaseSpecies ()
void set_study (int study_num)
void actionsBeforeTimeStep () override
A virtual function which allows to define operations to be executed before the new time step.
void setupInitialConditions () override
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
void add_flow_particles ()
void create_inflow_particle ()
void set_H (Mdouble new_)
Mdouble get_H ()
void printTime () const override
Displays the current simulation time and the maximum simulation duration.
int getNCreated () const
void increaseNCreated ()
SilbertPeriodic ()
Mdouble getSlidingFrictionCoefficientBottom ()
void setSlidingFrictionCoefficientBottom (Mdouble new_)
virtual void createBaseSpecies ()
void set_study ()
void set_study (int study_num)
void set_study (std::vector< int > study_num)
void actionsBeforeTimeStep () override
A virtual function which allows to define operations to be executed before the new time step.
void setupInitialConditions () override
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
void add_flow_particles ()
void create_inflow_particle ()
void set_H (double new_)
double get_H ()
void printTime () const override
Displays the current simulation time and the maximum simulation duration.
bool readNextArgument (int &i, int argc, char *argv[]) override
Interprets the i^th command-line argument.
int getNCreated () const
void increaseNCreated ()
SilbertPeriodic ()
void fix_hgrid ()
double getSlidingFrictionCoefficientBottom ()
void setSlidingFrictionCoefficientBottom (double new_)
void createBaseSpecies ()
void set_study ()
void set_study (int study_num)
void set_study (vector< int > study_num)
void actionsBeforeTimeStep () override
A virtual function which allows to define operations to be executed before the new time step.
void setupInitialConditions () override
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
void add_flow_particles ()
void create_inflow_particle ()
void set_H (double new_)
double get_H ()
void printTime ()
int readNextArgument (unsigned int &i, unsigned int &argc, char *argv[])
SilbertPeriodic ()
void fix_hgrid ()
Mdouble getSlidingFrictionCoefficientBottom ()
void setSlidingFrictionCoefficientBottom (Mdouble new_)
virtual void createBaseSpecies ()
void set_study ()
void set_study (int study_num)
void set_study (vector< int > study_num)
void actionsBeforeTimeStep () override
A virtual function which allows to define operations to be executed before the new time step.
void setupInitialConditions () override
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
void add_flow_particles ()
void create_inflow_particle ()
void set_H (Mdouble new_)
Mdouble get_H ()
void printTime ()
int readNextArgument (unsigned int &i, unsigned int argc, char *argv[])
SilbertPeriodic ()
Mdouble getSlidingFrictionCoefficientBottom ()
void setSlidingFrictionCoefficientBottom (Mdouble new_)
virtual void createBaseSpecies ()
void set_study ()
void set_study (int study_num)
virtual void actionsBeforeTimeStep () override
A virtual function which allows to define operations to be executed before the new time step.
void setupInitialConditions () override
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
void add_flow_particles ()
void create_inflow_particle ()
void set_H (Mdouble new_)
Mdouble get_H ()
void printTime () const override
Displays the current simulation time and the maximum simulation duration.
bool readNextArgument (int &i, int argc, char *argv[]) override
Interprets the i^th command-line argument.
int getNCreated () const
void increaseNCreated ()
Public Member Functions inherited from Chute
Chute ()
This is the default constructor. All it does is set sensible defaults.
Chute (const DPMBase &other)
Copy constructor, converts an existing DPMBase problem into a Chute problem.
Chute (const MercuryBase &other)
Copy constructor, converts an existing MercuryBase problem into a Chute problem.
Chute (const Mercury3D &other)
Copy constructor, converts an existing Mercury3D problem into a Chute problem.
Chute (const Chute &other)
Default copy constructor.
void constructor ()
This is the actual constructor METHOD; it is called by all constructors above (except the default copy constructor).
bool readNextArgument (int &i, int argc, char *argv[]) override
This method can be used for reading object properties from a string.
void setupSideWalls ()
Creates chute side walls (either solid or periodic)
void makeChutePeriodic ()
This makes the chute periodic in Y.
bool getIsPeriodic () const
Returns whether the chute is periodic in Y.
void setupInitialConditions () override
Creates bottom, side walls and a particle insertion boundary.
void read (std::istream &is, ReadOptions opt=ReadOptions::ReadAll) override
Reads all chute properties from an istream.
void write (std::ostream &os, bool writeAllParticles=true) const override
This function writes the Chute properties to an ostream, and adds the properties of ALL chute particles as well.
void setFixedParticleRadius (Mdouble fixedParticleRadius)
Sets the particle radius of the fixed particles which constitute the (rough) chute bottom.
Mdouble getFixedParticleRadius () const
Returns the particle radius of the fixed particles which constitute the (rough) chute bottom.
void setFixedParticleSpacing (Mdouble fixedParticleSpacing)
Sets the spacing of the fixed particles which constitute the (rough) chute bottom; used in triangular packing only.
Mdouble getFixedParticleSpacing () const
Returns the particle radius of the fixed particles which constitute the (rough) chute bottom; used in triangular packing only.
void setRoughBottomType (RoughBottomType roughBottomType)
Sets the type of rough bottom of the chute.
void setRoughBottomType (std::string roughBottomTypeString)
Sets the type of rough bottom of the chute, using a string with the EXACT enum type as input.
RoughBottomType getRoughBottomType () const
Returns the type of (rough) bottom of the chute.
void setChuteAngle (Mdouble chuteAngle)
Sets gravity vector according to chute angle (in degrees)
void setChuteAngleAndMagnitudeOfGravity (Mdouble chuteAngle, Mdouble gravity)
Sets gravity vector according to chute angle (in degrees)
Mdouble getChuteAngle () const
Returns the chute angle (in radians)
Mdouble getChuteAngleDegrees () const
Returns the chute angle (in degrees)
void setMaxFailed (unsigned int maxFailed)
Sets the number of times a particle will be tried to be added to the insertion boundary.
unsigned int getMaxFailed () const
Returns the number of times a particle will be tried to be added to the insertion boundary.
void setInflowParticleRadius (Mdouble inflowParticleRadius)
Sets the radius of the inflow particles to a single one (i.e. ensures a monodisperse inflow).
void setInflowParticleRadius (Mdouble minInflowParticleRadius, Mdouble maxInflowParticleRadius)
Sets the minimum and maximum radius of the inflow particles.
void setMinInflowParticleRadius (Mdouble minInflowParticleRadius)
sets the minimum radius of inflow particles
void setMaxInflowParticleRadius (Mdouble maxInflowParticleRadius)
Sets the maximum radius of inflow particles.
Mdouble getInflowParticleRadius () const
Returns the average radius of inflow particles.
Mdouble getMinInflowParticleRadius () const
returns the minimum radius of inflow particles
Mdouble getMaxInflowParticleRadius () const
Returns the maximum radius of inflow particles.
void setInflowHeight (Mdouble inflowHeight)
Sets maximum inflow height (Z-direction)
Mdouble getInflowHeight () const
Returns the maximum inflow height (Z-direction)
void setInflowVelocity (Mdouble inflowVelocity)
Sets the average inflow velocity.
Mdouble getInflowVelocity () const
Returns the average inflow velocity.
void setInflowVelocityVariance (Mdouble inflowVelocityVariance)
Sets the inflow velocity variance.
Mdouble getInflowVelocityVariance () const
Returns the inflow velocity variance.
void setChuteWidth (Mdouble chuteWidth)
Sets the chute width (Y-direction)
Mdouble getChuteWidth () const
Returns the chute width (Y-direction)
virtual void setChuteLength (Mdouble chuteLength)
Sets the chute length (X-direction)
Mdouble getChuteLength () const
Returns the chute length (X-direction)
void setInsertionBoundary (InsertionBoundary *insertionBoundary)
Sets the chute insertion boundary.
Public Member Functions inherited from Mercury3D
Mercury3D ()
This is the default constructor. All it does is set sensible defaults.
Mercury3D (const DPMBase &other)
Copy-constructor for creates an Mercury3D problem from an existing MD problem.
Mercury3D (const Mercury3D &other)
Copy-constructor.
void constructor ()
Function that sets the SystemDimension and ParticleDimension to 3.
std::vector< BaseParticle * > hGridFindParticleContacts (const BaseParticle *obj) override
Returns all particles that have a contact with a given particle.
Public Member Functions inherited from MercuryBase
MercuryBase ()
This is the default constructor. It sets sensible defaults.
~MercuryBase () override
This is the default destructor.
MercuryBase (const MercuryBase &mercuryBase)
Copy-constructor.
void constructor ()
This is the actual constructor, it is called do both constructors above.
void hGridActionsBeforeTimeLoop () override
This sets up the broad phase information, has to be done at this stage because it requires the particle size.
void hGridActionsBeforeTimeStep () override
Performs all necessary actions before a time-step, like updating the particles and resetting all the bucket information, etc.
void read (std::istream &is, ReadOptions opt=ReadOptions::ReadAll) override
Reads the MercuryBase from an input stream, for example a restart file.
void write (std::ostream &os, bool writeAllParticles=true) const override
Writes all data into a restart file.
Mdouble getHGridCurrentMaxRelativeDisplacement () const
Returns hGridCurrentMaxRelativeDisplacement_.
Mdouble getHGridTotalCurrentMaxRelativeDisplacement () const
Returns hGridTotalCurrentMaxRelativeDisplacement_.
void setHGridUpdateEachTimeStep (bool updateEachTimeStep)
Sets whether or not the HGrid must be updated every time step.
bool getHGridUpdateEachTimeStep () const final
Gets whether or not the HGrid is updated every time step.
void setHGridMaxLevels (unsigned int HGridMaxLevels)
Sets the maximum number of levels of the HGrid in this MercuryBase.
unsigned int getHGridMaxLevels () const
Gets the maximum number of levels of the HGrid in this MercuryBase.
HGridMethod getHGridMethod () const
Gets whether the HGrid in this MercuryBase is BOTTOMUP or TOPDOWN.
void setHGridMethod (HGridMethod hGridMethod)
Sets the HGridMethod to either BOTTOMUP or TOPDOWN.
HGridDistribution getHGridDistribution () const
Gets how the sizes of the cells of different levels are distributed.
void setHGridDistribution (HGridDistribution hGridDistribution)
Sets how the sizes of the cells of different levels are distributed.
Mdouble getHGridCellOverSizeRatio () const
Gets the ratio of the smallest cell over the smallest particle.
void setHGridCellOverSizeRatio (Mdouble cellOverSizeRatio)
Sets the ratio of the smallest cell over the smallest particle.
bool hGridNeedsRebuilding ()
Gets if the HGrid needs rebuilding before anything else happens.
virtual unsigned int getHGridTargetNumberOfBuckets () const
Gets the desired number of buckets, which is the maximum of the number of particles and 10.
virtual Mdouble getHGridTargetMinInteractionRadius () const
Gets the desired size of the smallest cells of the HGrid.
virtual Mdouble getHGridTargetMaxInteractionRadius () const
Gets the desired size of the largest cells of the HGrid.
bool checkParticleForInteraction (const BaseParticle &P) final
Checks if given BaseParticle has an interaction with a BaseWall or other BaseParticle.
bool checkParticleForInteractionLocal (const BaseParticle &P) final
Checks if the given BaseParticle has an interaction with a BaseWall or other BaseParticles in a local domain.
virtual Mdouble userHGridCellSize (unsigned int level)
Virtual function that enables inheriting classes to implement a function to let the user set the cell size of the HGrid.
void hGridInfo (std::ostream &os=std::cout) const
Writes the info of the HGrid to the screen in a nice format.
Public Member Functions inherited from DPMBase
void constructor ()
A function which initialises the member variables to default values, so that the problem can be solved off the shelf; sets up a basic two dimensional problem which can be solved off the shelf. It is called in the constructor DPMBase().
DPMBase ()
Constructor that calls the "void constructor()".
DPMBase (const DPMBase &other)
Copy constructor type-2.
virtual ~DPMBase ()
virtual destructor
void autoNumber ()
The autoNumber() function calls three functions: setRunNumber(), readRunNumberFromFile() and incrementRunNumberInFile().
std::vector< int > get1DParametersFromRunNumber (int size_x) const
This turns a counter into 1 index, which is a useful feature for performing 1D parameter study. The index run from 1:size_x, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get2DParametersFromRunNumber (int size_x, int size_y) const
This turns a counter into 2 indices which is a very useful feature for performing a 2D study. The indices run from 1:size_x and 1:size_y, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get3DParametersFromRunNumber (int size_x, int size_y, int size_z) const
This turns a counter into 3 indices, which is a useful feature for performing a 3D parameter study. The indices run from 1:size_x, 1:size_y and 1:size_z, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
int launchNewRun (const char *name, bool quick=false)
This launches a code from within this code. Please pass the name of the code to run.
void setRunNumber (int runNumber)
This sets the counter/Run number, overriding the defaults.
int getRunNumber () const
This returns the current value of the counter (runNumber_)
virtual void decompose ()
Sends particles from processorId to the root processor.
void solve ()
The work horse of the code.
void initialiseSolve ()
Beginning of the solve routine, before time stepping.
void finaliseSolve ()
End of the solve routine, after time stepping.
virtual void computeOneTimeStep ()
Performs everything needed for one time step, used in the time-loop of solve().
void checkSettings ()
Checks if the essentials are set properly to go ahead with solving the problem.
void forceWriteOutputFiles ()
Writes output files immediately, even if the current time step was not meant to be written. Also resets the last saved time step.
virtual void writeOutputFiles ()
Writes simulation data to all the main Mercury files: .data, .ene, .fstat, .xballs and .restart (see the Mercury website for more details regarding these files).
void solve (int argc, char *argv[])
The work horse of the code. Can handle flags from the command line.
virtual void writeXBallsScript () const
This writes a script which can be used to load the xballs problem to display the data just generated.
virtual Mdouble getInfo (const BaseParticle &P) const
A virtual function that returns some user-specified information about a particle.
ParticleVtkWriter * getVtkWriter () const
virtual void writeRestartFile ()
Stores all the particle data for current save time step to a "restart" file, which is a file simply intended to store all the information necessary to "restart" a simulation from a given time step (see also MercuryDPM.org for more information on restart files).
void writeDataFile ()
void writeEneFile ()
void writeFStatFile ()
void fillDomainWithParticles (unsigned N=50)
bool readRestartFile (ReadOptions opt=ReadOptions::ReadAll)
Reads all the particle data corresponding to a given, existing . restart file (for more details regarding restart files, refer to the training materials on the MercuryDPM website).Returns true if it is successful, false otherwise.
int readRestartFile (std::string fileName, ReadOptions opt=ReadOptions::ReadAll)
The same as readRestartFile(bool), but also reads all the particle data corresponding to the current saved time step.
virtual BaseWall * readUserDefinedWall (const std::string &type) const
Allows you to read in a wall defined in a Driver directory; see USER/Luca/ScrewFiller.
virtual void readOld (std::istream &is)
Reads all data from a restart file, e.g. domain data and particle data; old version.
bool readDataFile (std::string fileName="", unsigned int format=0)
This allows particle data to be reloaded from data files.
bool readParAndIniFiles (std::string fileName)
Allows the user to read par.ini files (useful to read files produced by the MDCLR simulation code - external to MercuryDPM)
bool readNextDataFile (unsigned int format=0)
Reads the next data file with default format=0. However, one can modify the format based on whether the particle data corresponds to 3D or 2D data- see Visualising data in xballs.
void readNextFStatFile ()
Reads the next fstat file.
bool findNextExistingDataFile (Mdouble tMin, bool verbose=true)
Finds and opens the next data file, if such a file exists.
bool readArguments (int argc, char *argv[])
Can interpret main function input arguments that are passed by the driver codes.
bool checkParticleForInteractionLocalPeriodic (const BaseParticle &P)
void readSpeciesFromDataFile (bool read=true)
void importParticlesAs (ParticleHandler &particleHandler, InteractionHandler &interactionHandler, const ParticleSpecies *species)
Copies particles, interactions assigning species from a local simulation to a global one. Useful for the creation of a cluster.
MERCURYDPM_DEPRECATED File & getDataFile ()
The non const version. Allows one to edit the File::dataFile.
MERCURYDPM_DEPRECATED File & getEneFile ()
The non const version. Allows to edit the File::eneFile.
MERCURYDPM_DEPRECATED File & getFStatFile ()
The non const version. Allows to edit the File::fStatFile.
MERCURYDPM_DEPRECATED File & getRestartFile ()
The non const version. Allows to edit the File::restartFile.
MERCURYDPM_DEPRECATED File & getStatFile ()
The non const version. Allows to edit the File::statFile.
File & getInteractionFile ()
Return a reference to the file InteractionsFile.
MERCURYDPM_DEPRECATED const File & getDataFile () const
The const version. Does not allow for any editing of the File::dataFile.
MERCURYDPM_DEPRECATED const File & getEneFile () const
The const version. Does not allow for any editing of the File::eneFile.
MERCURYDPM_DEPRECATED const File & getFStatFile () const
The const version. Does not allow for any editing of the File::fStatFile.
MERCURYDPM_DEPRECATED const File & getRestartFile () const
The const version. Does not allow for any editing of the File::restartFile.
MERCURYDPM_DEPRECATED const File & getStatFile () const
The const version. Does not allow for any editing of the File::statFile.
const File & getInteractionFile () const
Returns a constant reference to an Interactions file.
const std::string & getName () const
Returns the name of the file. Does not allow to change it though.
void setName (const std::string &name)
Allows to set the name of all the files (ene, data, fstat, restart, stat)
void setName (const char *name)
Calls setName(std::string)
void setSaveCount (unsigned int saveCount)
Sets File::saveCount_ for all files (ene, data, fstat, restart, stat)
void setFileType (FileType fileType)
Sets File::fileType_ for all files (ene, data, fstat, restart, stat)
void setOpenMode (std::fstream::openmode openMode)
Sets File::openMode_ for all files (ene, data, fstat, restart, stat)
void resetFileCounter ()
Resets the file counter for each file i.e. for ene, data, fstat, restart, stat)
void closeFiles ()
Closes all files (ene, data, fstat, restart, stat) that were opened to read or write.
void setVTKOutputDirectory (const std::string &dir)
Sets the output directory of the VTK files.
void setLastSavedTimeStep (unsigned int nextSavedTimeStep)
Sets the next time step for all the files (ene, data, fstat, restart, stat) at which the data is to be written or saved.
Mdouble getTime () const
Returns the current simulation time.
Mdouble getNextTime () const
Returns the current simulation time.
unsigned int getNumberOfTimeSteps () const
Returns the current counter of time-steps, i.e. the number of time-steps that the simulation has undergone so far.
void setTime (Mdouble time)
Sets a new value for the current simulation time.
void setTimeMax (Mdouble newTMax)
Sets a new value for the maximum simulation duration.
Mdouble getTimeMax () const
Returns the maximum simulation duration.
void setLogarithmicSaveCount (Mdouble logarithmicSaveCountBase)
Sets File::logarithmicSaveCount_ for all files (ene, data, fstat, restart, stat)
void setNToWrite (int nToWrite)
set the number of elements to write to the screen
int getNToWrite () const
get the number of elements to write to the
void setRotation (bool rotation)
Sets whether particle rotation is enabled or disabled.
bool getRotation () const
Indicates whether particle rotation is enabled or disabled.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (FileType writeWallsVTK)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (bool)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setInteractionsWriteVTK (bool)
Sets whether interactions are written into a VTK file.
void setParticlesWriteVTK (bool writeParticlesVTK)
Sets whether particles are written in a VTK file.
void setSuperquadricParticlesWriteVTK (bool writeSuperquadricParticlesVTK)
MERCURYDPM_DEPRECATED FileType getWallsWriteVTK () const
Returns whether walls are written in a VTK file.
bool getParticlesWriteVTK () const
Returns whether particles are written in a VTK file.
bool getSuperquadricParticlesWriteVTK () const
Mdouble getXMin () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMin() returns XMin.
Mdouble getXMax () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMax() returns XMax.
Mdouble getYMin () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMin() returns YMin.
Mdouble getYMax () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMax() returns XMax.
Mdouble getZMin () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMin() returns ZMin.
Mdouble getZMax () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMax() returns ZMax.
Mdouble getXCenter () const
Mdouble getYCenter () const
Mdouble getZCenter () const
Vec3D getCenter () const
get center of domain
Vec3D getMin () const
Returns the minimum coordinates of the problem domain.
Vec3D getMax () const
Returns the maximum coordinates of the problem domain.
void setXMin (Mdouble newXMin)
Sets the value of XMin, the lower bound of the problem domain in the x-direction.
void setYMin (Mdouble newYMin)
Sets the value of YMin, the lower bound of the problem domain in the y-direction.
void setZMin (Mdouble newZMin)
Sets the value of ZMin, the lower bound of the problem domain in the z-direction.
void setXMax (Mdouble newXMax)
Sets the value of XMax, the upper bound of the problem domain in the x-direction.
void setYMax (Mdouble newYMax)
Sets the value of YMax, the upper bound of the problem domain in the y-direction.
void setZMax (Mdouble newZMax)
Sets the value of ZMax, the upper bound of the problem domain in the z-direction.
void setMax (const Vec3D &max)
Sets the maximum coordinates of the problem domain.
void setMax (Mdouble, Mdouble, Mdouble)
Sets the maximum coordinates of the problem domain.
void setDomain (const Vec3D &min, const Vec3D &max)
Sets the minimum coordinates of the problem domain.
void setMin (const Vec3D &min)
Sets the minimum coordinates of the problem domain.
void setMin (Mdouble, Mdouble, Mdouble)
Sets the minimum coordinates of the problem domain.
void setTimeStep (Mdouble newDt)
Sets a new value for the simulation time step.
Mdouble getTimeStep () const
Returns the simulation time step.
void setNumberOfOMPThreads (int numberOfOMPThreads)
Sets the number of omp threads.
int getNumberOfOMPThreads () const
Returns the number of omp threads.
void setXBallsColourMode (int newCMode)
Set the xballs output mode.
int getXBallsColourMode () const
Get the xballs colour mode (CMode).
void setXBallsVectorScale (double newVScale)
Set the scale of vectors in xballs.
double getXBallsVectorScale () const
Returns the scale of vectors used in xballs.
void setXBallsAdditionalArguments (std::string newXBArgs)
Set the additional arguments for xballs.
std::string getXBallsAdditionalArguments () const
Returns the additional arguments for xballs.
void setXBallsScale (Mdouble newScale)
Sets the scale of the view (either normal, zoom in or zoom out) to display in xballs. The default is fit to screen.
double getXBallsScale () const
Returns the scale of the view in xballs.
void setGravity (Vec3D newGravity)
Sets a new value for the gravitational acceleration.
Vec3D getGravity () const
Returns the gravitational acceleration.
void setBackgroundDrag (Mdouble backgroundDrag)
Simple access function to turn on a background drag. The force of particleVelocity*drag is applied (note, it allowed to be negative i.e. create energy)
const Mdouble getBackgroundDrag () const
Return the background drag.
void setDimension (unsigned int newDim)
Sets both the system dimensions and the particle dimensionality.
void setSystemDimensions (unsigned int newDim)
Sets the system dimensionality.
unsigned int getSystemDimensions () const
Returns the system dimensionality.
void setParticleDimensions (unsigned int particleDimensions)
Sets the particle dimensionality.
unsigned int getParticleDimensions () const
Returns the particle dimensionality.
std::string getRestartVersion () const
This is to take into account for different Mercury versions. Returns the version of the restart file.
void setRestartVersion (std::string newRV)
Sets restart_version.
bool getRestarted () const
Returns the flag denoting if the simulation was restarted or not.
void setRestarted (bool newRestartedFlag)
Allows to set the flag stating if the simulation is to be restarted or not.
bool getAppend () const
Returns whether the "append" option is on or off.
void setAppend (bool newAppendFlag)
Sets whether the "append" option is on or off.
Mdouble getElasticEnergy () const
Returns the global elastic energy within the system.
Mdouble getKineticEnergy () const
Returns the global kinetic energy stored in the system.
Mdouble getGravitationalEnergy (Vec3D origin={0, 0, 0}) const
Returns the global gravitational potential energy stored relative to a user-defined origin in the system. Note, if no origin is specified the real origin i.e. (0,0,0) is taken.
Mdouble getRotationalEnergy () const
Returns the global rotational energy stored in the system.
Mdouble getTotalEnergy () const
Mdouble getTotalMass () const
JMFT: Return the total mass of the system, excluding fixed particles.
Vec3D getCentreOfMass () const
JMFT: Return the centre of mass of the system, excluding fixed particles.
Vec3D getTotalMomentum () const
JMFT: Return the total momentum of the system, excluding fixed particles.
double getCPUTime ()
double getWallTime ()
virtual void hGridInsertParticle (BaseParticle *obj UNUSED)
virtual void hGridUpdateParticle (BaseParticle *obj UNUSED)
virtual void hGridRemoveParticle (BaseParticle *obj UNUSED)
bool mpiIsInCommunicationZone (BaseParticle *particle)
Checks if the position of the particle is in an mpi communication zone or not.
bool mpiInsertParticleCheck (BaseParticle *P)
Function that checks if the mpi particle should really be inserted by the current domain.
void insertGhostParticle (BaseParticle *P)
This function inserts a particle in the mpi communication boundaries.
void updateGhostGrid (BaseParticle *P)
Checks if the Domain/periodic interaction distance needs to be updated and updates it accordingly.
virtual void gatherContactStatistics (unsigned int index1, int index2, Vec3D Contact, Mdouble delta, Mdouble ctheta, Mdouble fdotn, Mdouble fdott, Vec3D P1_P2_normal_, Vec3D P1_P2_tangential)
//Not unsigned index because of possible wall collisions.
void setNumberOfDomains (std::vector< unsigned > direction)
Sets the number of domains in x-,y- and z-direction. Required for parallel computations.
void splitDomain (DomainSplit domainSplit)
std::vector< unsigned > getNumberOfDomains ()
returns the number of domains
Domain * getCurrentDomain ()
Function that returns a pointer to the domain corresponding to the processor.
void removeOldFiles () const
void setMeanVelocity (Vec3D V_mean_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
void setMeanVelocityAndKineticEnergy (Vec3D V_mean_goal, Mdouble Ek_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
Mdouble getTotalVolume () const
Get the total volume of the cuboid system.
Matrix3D getKineticStress () const
Calculate the kinetic stress tensor in the system averaged over the whole volume.
Matrix3D getStaticStress () const
Calculate the static stress tensor in the system averaged over the whole volume.
Matrix3D getTotalStress () const
Calculate the total stress tensor in the system averaged over the whole volume.
virtual void handleParticleRemoval (unsigned int id)
Handles the removal of particles from the particleHandler.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
void writePythonFileForVTKVisualisation () const
writes .py file for ParaView
void setWritePythonFileForVTKVisualisation (bool forceWritePythonFileForVTKVisualisation)
bool getWritePythonFileForVTKVisualisation () const
WallVTKWriter & getWallVTKWriter ()
Public Attributes
int nCreated_
bool randomiseSpecies
SphericalParticle inflowParticle_
LinearViscoelasticSpecies * species
LinearViscoelasticMixedSpecies * baseSpecies
LinearViscoelasticFrictionSpecies * species
LinearViscoelasticFrictionMixedSpecies * baseSpecies
Public Attributes inherited from DPMBase
SpeciesHandler speciesHandler
A handler to that stores the species type i.e. LinearViscoelasticSpecies, etc.
RNG random
This is a random generator, often used for setting up the initial conditions etc...
ParticleHandler particleHandler
An object of the class ParticleHandler, contains the pointers to all the particles created.
ParticleHandler paoloParticleHandler
Fake particleHandler created by Paolo needed temporary by just Paolo.
WallHandler wallHandler
An object of the class WallHandler. Contains pointers to all the walls created.
BoundaryHandler boundaryHandler
An object of the class BoundaryHandler which concerns insertion and deletion of particles into or from regions.
PeriodicBoundaryHandler periodicBoundaryHandler
Internal handler that deals with periodic boundaries, especially in a parallel build.
DomainHandler domainHandler
An object of the class DomainHandler which deals with parallel code.
InteractionHandler interactionHandler
An object of the class InteractionHandler.
CGHandler cgHandler
Object of the class cgHandler.
File dataFile
An instance of class File to handle in- and output into a .data file.
File fStatFile
An instance of class File to handle in- and output into a .fstat file.
File eneFile
An instance of class File to handle in- and output into a .ene file.
File restartFile
An instance of class File to handle in- and output into a .restart file.
File statFile
An instance of class File to handle in- and output into a .stat file.
File interactionFile
File class to handle in- and output into .interactions file. This file hold information about interactions.
Time clock_
record when the simulation started
Additional Inherited Members
Public Types inherited from DPMBase
enum class ReadOptions : int { ReadAll , ReadNoInteractions , ReadNoParticlesAndInteractions }
enum class DomainSplit {
X , Y , Z , XY ,
XZ , YZ , XYZ
}
Static Public Member Functions inherited from DPMBase
static void incrementRunNumberInFile ()
Increment the run Number (counter value) stored in the file_counter (COUNTER_DONOTDEL) by 1 and store the new value in the counter file.
static int readRunNumberFromFile ()
Read the run number or the counter from the counter file (COUNTER_DONOTDEL)
static bool areInContact (const BaseParticle *pI, const BaseParticle *pJ)
Checks if two particle are in contact or is there any positive overlap.
Protected Member Functions inherited from Chute
void actionsBeforeTimeStep () override
Calls Chute::cleanChute().
void cleanChute ()
Deletes all outflow particles once every 100 time steps.
virtual void createBottom ()
Creates the chute bottom, which can be either flat or one of three flavours of rough.
virtual void addFlowParticlesCompactly ()
Add initial flow particles in a dense packing.
virtual SphericalParticle createFlowParticle ()
void printTime () const override
prints time, max time and number of particles
Protected Member Functions inherited from Mercury3D
void hGridFindContactsWithinTargetCell (int x, int y, int z, unsigned int l)
Finds contacts between particles in the target cell.
void hGridFindContactsWithTargetCell (int x, int y, int z, unsigned int l, BaseParticle *obj)
Finds contacts between the BaseParticle and the target cell.
void computeWallForces (BaseWall *w) override
Compute contacts with a wall.
void hGridFindParticlesWithTargetCell (int x, int y, int z, unsigned int l, BaseParticle *obj, std::vector< BaseParticle * > &list)
Finds particles within target cell and stores them in a list.
void hGridGetInteractingParticleList (BaseParticle *obj, std::vector< BaseParticle * > &list) override
Obtains all neighbour particles of a given object, obtained from the hgrid.
void computeInternalForces (BaseParticle *obj) override
Finds contacts with the BaseParticle; avoids multiple checks.
bool hGridHasContactsInTargetCell (int x, int y, int z, unsigned int l, const BaseParticle *obj) const
Tests if the BaseParticle has contacts with other Particles in the target cell.
bool hGridHasParticleContacts (const BaseParticle *obj) override
Tests if a BaseParticle has any contacts in the HGrid.
void hGridRemoveParticle (BaseParticle *obj) override
Removes a BaseParticle from the HGrid.
void hGridUpdateParticle (BaseParticle *obj) override
Updates the cell (not the level) of a BaseParticle.
Protected Member Functions inherited from MercuryBase
void hGridRebuild ()
This sets up the parameters required for the contact model.
void hGridInsertParticle (BaseParticle *obj) final
Inserts a single Particle to current grid.
void hGridUpdateMove (BaseParticle *iP, Mdouble move) final
Computes the relative displacement of the given BaseParticle and updates the currentMaxRelativeDisplacement_ accordingly.
void hGridActionsBeforeIntegration () override
Resets the currentMaxRelativeDisplacement_ to 0.
void hGridActionsAfterIntegration () override
This function has to be called before integrateBeforeForceComputation.
HGrid * getHGrid ()
Gets the HGrid used by this problem.
const HGrid * getHGrid () const
Gets the HGrid used by this problem, const version.
bool readNextArgument (int &i, int argc, char *argv[]) override
Reads the next command line argument.
Protected Member Functions inherited from DPMBase
virtual void computeAllForces ()
Computes all the forces acting on the particles using the BaseInteractable::setForce() and BaseInteractable::setTorque()
virtual void computeInternalForce (BaseParticle *, BaseParticle *)
Computes the forces between two particles (internal in the sense that the sum over all these forces is zero i.e. fully modelled forces)
virtual void computeExternalForces (BaseParticle *)
Computes the external forces, such as gravity, acting on particles.
virtual void computeForcesDueToWalls (BaseParticle *, BaseWall *)
Computes the forces on the particles due to the walls (normals are outward normals)
virtual void actionsOnRestart ()
A virtual function where the users can add extra code which is executed only when the code is restarted.
virtual void actionsBeforeTimeLoop ()
A virtual function. Allows one to carry out any operations before the start of the time loop.
virtual void computeAdditionalForces ()
A virtual function which allows to define operations to be executed prior to the OMP force collect.
virtual void actionsAfterSolve ()
A virtual function which allows to define operations to be executed after the solve().
virtual void actionsAfterTimeStep ()
A virtual function which allows to define operations to be executed after time step.
void writeVTKFiles () const
virtual void outputXBallsData (std::ostream &os) const
This function writes the location of the walls and particles in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void outputXBallsDataParticle (unsigned int i, unsigned int format, std::ostream &os) const
This function writes out the particle locations into an output stream in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void writeEneHeader (std::ostream &os) const
Writes a header with a certain format for ENE file.
virtual void writeFstatHeader (std::ostream &os) const
Writes a header with a certain format for FStat file.
virtual void writeEneTimeStep (std::ostream &os) const
Write the global kinetic, potential energy, etc. in the system.
virtual void initialiseStatistics ()
virtual void outputStatistics ()
void gatherContactStatistics ()
virtual void processStatistics (bool)
virtual void finishStatistics ()
virtual void integrateBeforeForceComputation ()
Update particles' and walls' positions and velocities before force computation.
virtual void integrateAfterForceComputation ()
Update particles' and walls' positions and velocities after force computation.
virtual void checkInteractionWithBoundaries ()
There are a range of boundaries one could implement depending on ones' problem. This methods checks for interactions between particles and such range of boundaries. See BaseBoundary.h and all the boundaries in the Boundaries folder.
void setFixedParticles (unsigned int n)
Sets a number, n, of particles in the particleHandler as "fixed particles".
virtual bool continueSolve () const
A virtual function for deciding whether to continue the simulation, based on a user-specified criterion.
void outputInteractionDetails () const
Displays the interaction details corresponding to the pointer objects in the interaction handler.
bool isTimeEqualTo (Mdouble time) const
Checks whether the input variable "time" is the current time in the simulation.
void removeDuplicatePeriodicParticles ()
Removes periodic duplicate Particles.
void checkAndDuplicatePeriodicParticles ()
For simulations using periodic boundaries, checks and adds particles when necessary into the particle handler. See DPMBase.cc and PeriodicBoundary.cc for more details.
void performGhostParticleUpdate ()
When the Verlet scheme updates the positions and velocities of particles, ghost particles will need an update as wel. Their status will also be updated accordingly.
void deleteGhostParticles (std::set< BaseParticle * > &particlesToBeDeleted)
void synchroniseParticle (BaseParticle *, unsigned fromProcessor=0)
void performGhostVelocityUpdate ()
updates the final time-step velocity of the ghost particles
void disableSoftStop ()
This prevents the initialisation of the soft stop feature.
void discontinueSolve ()
This discontinues the solve loop after the current time step is finished.
Constructor & Destructor Documentation
SilbertPeriodic() [1/5]
SilbertPeriodic::SilbertPeriodic () inline
                       {
         // Problem parameters
         setName("silbert");
         //time stepping
         setTimeStep(1e-4);
         setTimeMax(2000);
         //output parameters
         setSaveCount(50e4);
         //particle radii
         setInflowParticleRadius(.5);
         setFixedParticleRadius(.5);//getInflowParticleRadius());
         setRoughBottomType(MULTILAYER);
         //particle properties
         baseSpecies = nullptr;
         species = speciesHandler.copyAndAddObject(LinearViscoelasticSpecies());
         species->setDensity(6/constants::pi);
         species->setStiffness(2e5);
         species->setDissipation(25.0);
         inflowParticle_.setSpecies(species);
         //chute properties
         setChuteAngleAndMagnitudeOfGravity(24.0, 1.0);
         setChuteLength(20);
         setChuteWidth(10);
         setInflowVelocity(0);
         set_H(20);
         randomiseSpecies=false;
         nCreated_=0;
         restartFile.setFileType(FileType::MULTIPLE_FILES_PADDED);
         dataFile.setFileType(FileType::ONE_FILE);
         fStatFile.setFileType(FileType::NO_FILE);
         eneFile.setFileType(FileType::ONE_FILE);
     }
References baseSpecies, BaseHandler< T >::copyAndAddObject(), DPMBase::dataFile, e(), DPMBase::eneFile, DPMBase::fStatFile, inflowParticle_, MULTILAYER, MULTIPLE_FILES_PADDED, nCreated_, NO_FILE, ONE_FILE, constants::pi, randomiseSpecies, DPMBase::restartFile, set_H(), Chute::setChuteAngleAndMagnitudeOfGravity(), Chute::setChuteLength(), Chute::setChuteWidth(), ParticleSpecies::setDensity(), LinearViscoelasticNormalSpecies::setDissipation(), File::setFileType(), Chute::setFixedParticleRadius(), Chute::setInflowParticleRadius(), Chute::setInflowVelocity(), DPMBase::setName(), Chute::setRoughBottomType(), DPMBase::setSaveCount(), BaseParticle::setSpecies(), LinearViscoelasticNormalSpecies::setStiffness(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), species, and DPMBase::speciesHandler.
SilbertPeriodic() [2/5]
SilbertPeriodic::SilbertPeriodic () inline
                       {
         // Problem parameters
         setName("silbert");
         //time stepping
         setTimeStep(1e-4);
         setTimeMax(2000);
         //output parameters
         setSaveCount(50e4);
         //particle radii
         setInflowParticleRadius(.5);
         setFixedParticleRadius(.5);//getInflowParticleRadius());
         setRoughBottomType(MULTILAYER);
         //particle properties
         baseSpecies = nullptr;
         species = speciesHandler.copyAndAddObject(LinearViscoelasticFrictionSpecies());
         species->setDensity(6/constants::pi);
         //~ setStiffnessAndRestitutionCoefficient(2e5,0.97,1);
         double tc=5e-3, r=0.97, beta=0.44, mu=0.092, mur=0.042;
         species->setCollisionTimeAndNormalAndTangentialRestitutionCoefficient(tc,r,beta,1.0);// need to consider effective mass
         species->setSlidingFrictionCoefficient(mu);
         species->setRollingFrictionCoefficient(mur);
         //chute properties
         setChuteAngleAndMagnitudeOfGravity(24.0, 1.0);
         setChuteLength(20);
         setChuteWidth(10);
         set_H(20);
         nCreated_=0;
     }
References baseSpecies, beta, BaseHandler< T >::copyAndAddObject(), e(), Global_Parameters::mu, MULTILAYER, plotDoE::mur, nCreated_, constants::pi, UniformPSDSelfTest::r, set_H(), Chute::setChuteAngleAndMagnitudeOfGravity(), Chute::setChuteLength(), Chute::setChuteWidth(), ParticleSpecies::setDensity(), Chute::setFixedParticleRadius(), Chute::setInflowParticleRadius(), DPMBase::setName(), Chute::setRoughBottomType(), DPMBase::setSaveCount(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), species, and DPMBase::speciesHandler.
SilbertPeriodic() [3/5]
SilbertPeriodic::SilbertPeriodic () inline
                       {
         // Problem parameters
         setName("silbert");
         //time stepping
         setTimeStep(1e-4);
         setTimeMax(2000);
         //output parameters
         setSaveCount(50e4);
         //particle radii
         setInflowParticleRadius(.5);
         setFixedParticleRadius(.5);//getInflowParticleRadius());
         setRoughBottomType(MULTILAYER);
         //particle properties
         setDensity(6/pi);
         //~ setStiffnessAndRestitutionCoefficient(2e5,0.97,1);
         double tc=5e-3, r=0.97, beta=0.44, mu=0.092, mur=0.042;
         setCollisionTimeAndNormalAndTangentialRestitutionCoefficient(tc,r,beta,1.0,1.0);
         setSlidingFrictionCoefficient(mu);
         setSlidingFrictionCoefficientr();
         //chute properties
         setChuteAngle(24.0, 1.0);
         setChuteLength(20);
         setChuteWidth(10);
         set_H(20);
     }
References beta, e(), Global_Parameters::mu, MULTILAYER, plotDoE::mur, constants::pi, and UniformPSDSelfTest::r.
SilbertPeriodic() [4/5]
SilbertPeriodic::SilbertPeriodic () inline
                       {
         // Problem parameters
         setName("silbert");
         //time stepping
         setTimeStep(1e-4);
         setTimeMax(2000);
         //output parameters
         setSaveCount(50e4);
         //particle radii
         setInflowParticleRadius(.5);
         setFixedParticleRadius(.5);//getInflowParticleRadius());
         setRoughBottomType(MULTILAYER);
         //particle properties
         setDensity(6/constants::pi);
         setStiffness(2e5);
         setSlidingStiffness(2.0/7.0*getStiffness());
         setDissipation(25.0);
         //setSlidingDissipation(2.0/7.0*getDissipation());
         setSlidingDissipation(getDissipation());
         setSlidingFrictionCoefficient(0.5);
         //chute properties
         setChuteAngle(24.0, 1.0);
         setChuteLength(20);
         setChuteWidth(10);
         set_H(20);
     }
References e(), MULTILAYER, and constants::pi.
SilbertPeriodic() [5/5]
SilbertPeriodic::SilbertPeriodic () inline
                       {
         // Problem parameters
         setName("silbert");
         //time stepping
         setTimeStep(1e-4);
         setTimeMax(2000);
         //output parameters
         setSaveCount(50e4);
         //particle radii
         setInflowParticleRadius(.5);
         setFixedParticleRadius(.5);//getInflowParticleRadius());
         setRoughBottomType(MULTILAYER);
         //particle properties
         baseSpecies = nullptr;
         species = speciesHandler.copyAndAddObject(LinearViscoelasticFrictionSpecies());
         species->setDensity(6/constants::pi);
         species->setStiffness(2e5);
         species->setSlidingStiffness(2.0/7.0* species->getStiffness());
         species->setDissipation(25.0);
         //setSlidingDissipation(2.0/7.0*getDissipation());
         species->setSlidingDissipation(species->getDissipation());
         species->setSlidingFrictionCoefficient(0.5);
         inflowParticle_.setSpecies(species);
         //chute properties
         setChuteAngleAndMagnitudeOfGravity(24.0, 1.0);
         setChuteLength(20);
         setChuteWidth(10);
         setInflowVelocity(0);
         set_H(20);
         randomiseSpecies=false;
         nCreated_=0;
         restartFile.setFileType(FileType::MULTIPLE_FILES_PADDED);
         dataFile.setFileType(FileType::NO_FILE);
         fStatFile.setFileType(FileType::NO_FILE);
         eneFile.setFileType(FileType::ONE_FILE);
     }
References baseSpecies, BaseHandler< T >::copyAndAddObject(), DPMBase::dataFile, e(), DPMBase::eneFile, DPMBase::fStatFile, LinearViscoelasticNormalSpecies::getDissipation(), LinearViscoelasticNormalSpecies::getStiffness(), inflowParticle_, MULTILAYER, MULTIPLE_FILES_PADDED, nCreated_, NO_FILE, ONE_FILE, constants::pi, randomiseSpecies, DPMBase::restartFile, set_H(), Chute::setChuteAngleAndMagnitudeOfGravity(), Chute::setChuteLength(), Chute::setChuteWidth(), ParticleSpecies::setDensity(), LinearViscoelasticNormalSpecies::setDissipation(), File::setFileType(), Chute::setFixedParticleRadius(), Chute::setInflowParticleRadius(), Chute::setInflowVelocity(), DPMBase::setName(), Chute::setRoughBottomType(), DPMBase::setSaveCount(), BaseParticle::setSpecies(), LinearViscoelasticNormalSpecies::setStiffness(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), species, and DPMBase::speciesHandler.
Member Function Documentation
actionsBeforeTimeStep() [1/5]
void SilbertPeriodic::actionsBeforeTimeStep () inline override virtual
A virtual function which allows to define operations to be executed before the new time step.
no implementation but can be overridden in its derived classes.
Reimplemented from DPMBase.
Reimplemented in SilbertHstop.
 { };
actionsBeforeTimeStep() [2/5]
void SilbertPeriodic::actionsBeforeTimeStep () inline override virtual
A virtual function which allows to define operations to be executed before the new time step.
no implementation but can be overridden in its derived classes.
Reimplemented from DPMBase.
Reimplemented in SilbertHstop.
 { };
actionsBeforeTimeStep() [3/5]
void SilbertPeriodic::actionsBeforeTimeStep () inline override virtual
A virtual function which allows to define operations to be executed before the new time step.
no implementation but can be overridden in its derived classes.
Reimplemented from DPMBase.
 { };
actionsBeforeTimeStep() [4/5]
void SilbertPeriodic::actionsBeforeTimeStep () inline override virtual
A virtual function which allows to define operations to be executed before the new time step.
no implementation but can be overridden in its derived classes.
Reimplemented from DPMBase.
 { };
actionsBeforeTimeStep() [5/5]
virtual void SilbertPeriodic::actionsBeforeTimeStep () inline override virtual
A virtual function which allows to define operations to be executed before the new time step.
no implementation but can be overridden in its derived classes.
Reimplemented from DPMBase.
Reimplemented in SilbertHstop.
 { };
add_flow_particles() [1/5]
void SilbertPeriodic::add_flow_particles () inline
     {
         //setHGridNumberOfBucketsToPower(particleHandler.getStorageCapacity());
         hGridActionsBeforeTimeLoop();
         checkAndDuplicatePeriodicParticles();
         hGridActionsBeforeTimeStep();
         unsigned int N=getChuteLength()*getChuteWidth()* getInflowHeight();
         particleHandler.setStorageCapacity(particleHandler.getNumberOfObjects()+1.5*N);
         Mdouble H = getInflowHeight();
         setZMax(1.0*getInflowHeight());
         //uncomment the following line to achieve a high packing fraction
         setInflowHeight(getZMin()+inflowParticle_.getRadius());
         writeRestartFile();
         //try to find new insertable particles
         while (getNCreated()<N){
             create_inflow_particle();
             if (checkParticleForInteraction(inflowParticle_)) {
                 BaseParticle* p = particleHandler.copyAndAddObject(inflowParticle_);
                 //duplicate particle
                 for (BaseBoundary* it : boundaryHandler)
                     it->createPeriodicParticle(p, particleHandler);
                 p = particleHandler.getLastObject();
                 //duplicate duplicate particles (this is a hack which is needed as there are two boundaries, so the doubly periodic images are needed)
                 for (BaseBoundary* it : boundaryHandler)
                     it->createPeriodicParticle(p, particleHandler);
                 //hGridActionsBeforeTimeStep();
                 increaseNCreated();
             } else setInflowHeight(getInflowHeight() + .0001* getMaxInflowParticleRadius());
         }
         for (unsigned int i = particleHandler.getNumberOfObjects(); i >= 1; i--)
         if (particleHandler.getObject(i - 1)->getPeriodicFromParticle() != nullptr)
         {
             while (!particleHandler.getObject(i - 1)->getInteractions().empty())
             {
                 interactionHandler.removeObjectKeepingPeriodics(particleHandler.getObject(i - 1)->getInteractions().front()->getIndex());
             }
             particleHandler.removeObject(i - 1);
         }
         setInflowHeight(H);
         //setHGridNumberOfBucketsToPower();
         write(std::cout,false);
     }
References DPMBase::boundaryHandler, DPMBase::checkAndDuplicatePeriodicParticles(), MercuryBase::checkParticleForInteraction(), BaseHandler< T >::copyAndAddObject(), create_inflow_particle(), Chute::getChuteLength(), Chute::getChuteWidth(), Chute::getInflowHeight(), BaseInteractable::getInteractions(), BaseHandler< T >::getLastObject(), Chute::getMaxInflowParticleRadius(), getNCreated(), ParticleHandler::getNumberOfObjects(), BaseHandler< T >::getObject(), BaseParticle::getPeriodicFromParticle(), BaseParticle::getRadius(), DPMBase::getZMin(), H, MercuryBase::hGridActionsBeforeTimeLoop(), MercuryBase::hGridActionsBeforeTimeStep(), i, increaseNCreated(), inflowParticle_, DPMBase::interactionHandler, N, p, DPMBase::particleHandler, ParticleHandler::removeObject(), InteractionHandler::removeObjectKeepingPeriodics(), Chute::setInflowHeight(), BaseHandler< T >::setStorageCapacity(), DPMBase::setZMax(), Chute::write(), and DPMBase::writeRestartFile().
Referenced by setupInitialConditions().
add_flow_particles() [2/5]
void SilbertPeriodic::add_flow_particles () inline
     {
             //setHGridNumberBucketsToPower(get_Nmax());
                 hGridActionsBeforeTimeLoop();
                 hGridActionsBeforeTimeStep();
                 unsigned int N=particleHandler.getNumberOfObjects()+getChuteLength()*getChuteWidth()*getInflowHeight();
         //set_Nmax(N); // automated in the new version
         double H = getInflowHeight();
         setZMax(1.2*getInflowHeight());
         //writeRestartFile();
         //try to find new insertable particles
         while (particleHandler.getNumberOfObjects()<N){
             create_inflow_particle();
             if (checkParticleForInteraction(inflowParticle_)) {
                 increaseNCreated();
             } else setInflowHeight(getInflowHeight() + .0001* getMaxInflowParticleRadius());
         }
         setInflowHeight(H);
         //setHGridNumberOfBucketsToPower();
         write(std::cout,false);
     }
References MercuryBase::checkParticleForInteraction(), create_inflow_particle(), Chute::getChuteLength(), Chute::getChuteWidth(), Chute::getInflowHeight(), Chute::getMaxInflowParticleRadius(), ParticleHandler::getNumberOfObjects(), H, MercuryBase::hGridActionsBeforeTimeLoop(), MercuryBase::hGridActionsBeforeTimeStep(), increaseNCreated(), inflowParticle_, N, DPMBase::particleHandler, Chute::setInflowHeight(), DPMBase::setZMax(), and Chute::write().
add_flow_particles() [3/5]
void SilbertPeriodic::add_flow_particles () inline
     {
                 set_HGRID_num_buckets_to_power(get_Nmax());
                 hGridActionsBeforeTimeLoop();
                 hGridActionsBeforeTimeStep();
                 unsigned int N=get_N()+getChuteLength()*getChuteWidth()*InflowHeight;
         set_Nmax(N);
         double H = InflowHeight;
         setZMax(1.2*InflowHeight);
         writeRestartFile();
         //try to find new insertable particles
         while (Particles.size()<N){
             create_inflow_particle();
             if (IsInsertable(P0)) {
                 num_created++;
             } else InflowHeight += .0001* MaxInflowParticleRadius;
         }
         InflowHeight = H;
         set_HGRID_num_buckets_to_power();
         write(std::cout,false);
     }
References H, N, Problem_Parameter::P0, and Eigen::TensorSycl::internal::write().
add_flow_particles() [4/5]
void SilbertPeriodic::add_flow_particles () inline
     {
         set_HGRID_num_buckets_to_power(particleHandler.getStorageCapacity());
         hGridActionsBeforeTimeLoop();
         hGridActionsBeforeTimeStep();
         unsigned int N=particleHandler.getNumberOfObjects()+getChuteLength()*getChuteWidth()*InflowHeight;
         particleHandler.set_StorageCapacity(N);
         Mdouble H = InflowHeight;
         setZMax(1.2*InflowHeight);
         writeRestartFile();
         //try to find new insertable particles
         while (particleHandler.getNumberOfObjects()<N){
             create_inflow_particle();
             if (IsInsertable(P0)) {
                 num_created++;
             } else InflowHeight += .0001* MaxInflowParticleRadius;
         }
         InflowHeight = H;
         set_HGRID_num_buckets_to_power();
         write(std::cout,false);
     }
References H, N, Problem_Parameter::P0, and Eigen::TensorSycl::internal::write().
add_flow_particles() [5/5]
void SilbertPeriodic::add_flow_particles () inline
     {
         //setHGridNumberOfBucketsToPower(particleHandler.getStorageCapacity());
         hGridActionsBeforeTimeLoop();
         checkAndDuplicatePeriodicParticles();
         hGridActionsBeforeTimeStep();
         unsigned int N=getChuteLength()*getChuteWidth()* getInflowHeight();
         particleHandler.setStorageCapacity(particleHandler.getNumberOfObjects()+1.5*N);
         Mdouble H = getInflowHeight();
         setZMax(1.0*getInflowHeight());
         //uncomment the following line to achieve a high packing fraction
         setInflowHeight(getZMin()+inflowParticle_.getRadius());
         writeRestartFile();
         //try to find new insertable particles
         while (getNCreated()<N){
             create_inflow_particle();
             if (checkParticleForInteraction(inflowParticle_)) {
                 BaseParticle* p = particleHandler.copyAndAddObject(inflowParticle_);
                 //duplicate particle
                 for (BaseBoundary* it : boundaryHandler)
                     it->createPeriodicParticle(p, particleHandler);
                 p = particleHandler.getLastObject();
                 //duplicate duplicate particles (this is a hack which is needed as there are two boundaries, so the doubly periodic images are needed)
                 for (BaseBoundary* it : boundaryHandler)
                     it->createPeriodicParticle(p, particleHandler);
                 //hGridActionsBeforeTimeStep();
                 increaseNCreated();
             } else setInflowHeight(getInflowHeight() + .0001* getMaxInflowParticleRadius());
         }
         for (unsigned int i = particleHandler.getNumberOfObjects(); i >= 1; i--)
         if (particleHandler.getObject(i - 1)->getPeriodicFromParticle() != nullptr)
         {
             while (particleHandler.getObject(i - 1)->getInteractions().size() > 0)
             {
                 interactionHandler.removeObjectKeepingPeriodics(particleHandler.getObject(i - 1)->getInteractions().front()->getIndex());
             }
             particleHandler.removeObject(i - 1);
         }
         setInflowHeight(H);
         //setHGridNumberOfBucketsToPower();
         write(std::cout,false);
     }
References DPMBase::boundaryHandler, DPMBase::checkAndDuplicatePeriodicParticles(), MercuryBase::checkParticleForInteraction(), BaseHandler< T >::copyAndAddObject(), create_inflow_particle(), Chute::getChuteLength(), Chute::getChuteWidth(), Chute::getInflowHeight(), BaseInteractable::getInteractions(), BaseHandler< T >::getLastObject(), Chute::getMaxInflowParticleRadius(), getNCreated(), ParticleHandler::getNumberOfObjects(), BaseHandler< T >::getObject(), BaseParticle::getPeriodicFromParticle(), BaseParticle::getRadius(), DPMBase::getZMin(), H, MercuryBase::hGridActionsBeforeTimeLoop(), MercuryBase::hGridActionsBeforeTimeStep(), i, increaseNCreated(), inflowParticle_, DPMBase::interactionHandler, N, p, DPMBase::particleHandler, ParticleHandler::removeObject(), InteractionHandler::removeObjectKeepingPeriodics(), Chute::setInflowHeight(), BaseHandler< T >::setStorageCapacity(), DPMBase::setZMax(), Chute::write(), and DPMBase::writeRestartFile().
create_inflow_particle() [1/5]
void SilbertPeriodic::create_inflow_particle () inline
     {
         inflowParticle_.setRadius(random.getRandomNumber(getMinInflowParticleRadius(),getMaxInflowParticleRadius()));
         //inflowParticle_.computeMass();
         //The position components are first stored in a Vec3D, because if you pass them directly into setPosition the compiler is allowed to change the order in which the numbers are generated
         Vec3D position;
         position.X = random.getRandomNumber(getXMin(),getXMax());
         position.Y = random.getRandomNumber(getYMin(),getYMax());
         position.Z = random.getRandomNumber(getZMin()+inflowParticle_.getRadius(),getInflowHeight());
         inflowParticle_.setPosition(position);
         inflowParticle_.setVelocity(Vec3D(getInflowVelocity(),0.0,0.0));
         if (randomiseSpecies)
         {
             const unsigned int indSpecies = floor(
                     random.getRandomNumber(0, speciesHandler.getNumberOfObjects() - 1e-200));
             inflowParticle_.setSpecies(speciesHandler.getObject(indSpecies));
         }
     }
References e(), Eigen::bfloat16_impl::floor(), Chute::getInflowHeight(), Chute::getInflowVelocity(), Chute::getMaxInflowParticleRadius(), Chute::getMinInflowParticleRadius(), BaseHandler< T >::getNumberOfObjects(), BaseHandler< T >::getObject(), BaseParticle::getRadius(), RNG::getRandomNumber(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), DPMBase::getZMin(), inflowParticle_, DPMBase::random, randomiseSpecies, BaseInteractable::setPosition(), BaseParticle::setRadius(), BaseParticle::setSpecies(), BaseInteractable::setVelocity(), DPMBase::speciesHandler, Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by add_flow_particles().
create_inflow_particle() [2/5]
void SilbertPeriodic::create_inflow_particle () inline
     {
         inflowParticle_.setRadius(getMaxInflowParticleRadius());
         //inflowParticle_.computeMass();
         Vec3D position;
         position.X = random.getRandomNumber(getXMin()+2.0*inflowParticle_.getRadius(),getXMax());
         position.Y = random.getRandomNumber(getYMin() + 2.0 * inflowParticle_.getRadius(), getYMax());
         position.Z = random.getRandomNumber(getZMin() + 2.0 * inflowParticle_.getRadius(), getInflowHeight());
         inflowParticle_.setPosition(position);
         inflowParticle_.setVelocity(Vec3D(0.0, 0.0, 0.0));
     }
References Chute::getInflowHeight(), Chute::getMaxInflowParticleRadius(), BaseParticle::getRadius(), RNG::getRandomNumber(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), DPMBase::getZMin(), inflowParticle_, DPMBase::random, BaseInteractable::setPosition(), BaseParticle::setRadius(), BaseInteractable::setVelocity(), Vec3D::X, Vec3D::Y, and Vec3D::Z.
create_inflow_particle() [3/5]
void SilbertPeriodic::create_inflow_particle () inline
     {
         P0.Radius = MaxInflowParticleRadius;
         P0.computeMass(Species);
         P0.Position.X = random(getXMin()+2.0*P0.Radius,getXMax());
         P0.Position.Y = random(getYMin()+2.0*P0.Radius,getYMax());
         P0.Position.Z = random(getZMin()+2.0*P0.Radius,getInflowHeight());
         P0.Velocity = Vec3D(0.0,0.0,0.0);
     }
References Problem_Parameter::P0.
create_inflow_particle() [4/5]
void SilbertPeriodic::create_inflow_particle () inline
     {
         P0.setRadius(random.get_RN(MinInflowParticleRadius,MaxInflowParticleRadius));
         P0.computeMass(Species);
         P0.getPosition().X = random.get_RN(getXMin()+2.0*P0.getRadius(),getXMax());
         P0.getPosition().Y = random.get_RN(getYMin()+2.0*P0.getRadius(),getYMax());
         P0.getPosition().Z = random.get_RN(getZMin()+2.0*P0.getRadius(),getInflowHeight());
         P0.setVelocity(Vec3D(0.0,0.0,0.0));
     }
References Problem_Parameter::P0.
create_inflow_particle() [5/5]
void SilbertPeriodic::create_inflow_particle () inline
     {
         inflowParticle_.setRadius(random.getRandomNumber(getMinInflowParticleRadius(), getMaxInflowParticleRadius()));
         //inflowParticle_.computeMass();
         //The position components are first stored in a Vec3D, because if you pass them directly into setPosition the compiler is allowed to change the order in which the numbers are generated
         Vec3D position;
         position.X = random.getRandomNumber(getXMin(), getXMax());
         position.Y = random.getRandomNumber(getYMin(), getYMax());
         position.Z = random.getRandomNumber(getZMin() + inflowParticle_.getRadius(), getInflowHeight());
         inflowParticle_.setPosition(position);
         inflowParticle_.setVelocity(Vec3D(getInflowVelocity(), 0.0, 0.0));
         if (randomiseSpecies)
         {
             int indSpecies = floor(random.getRandomNumber(0, speciesHandler.getNumberOfObjects() - 1e-200));
             inflowParticle_.setSpecies(speciesHandler.getObject(indSpecies));
         }
     }
References e(), Eigen::bfloat16_impl::floor(), Chute::getInflowHeight(), Chute::getInflowVelocity(), Chute::getMaxInflowParticleRadius(), Chute::getMinInflowParticleRadius(), BaseHandler< T >::getNumberOfObjects(), BaseHandler< T >::getObject(), BaseParticle::getRadius(), RNG::getRandomNumber(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), DPMBase::getZMin(), inflowParticle_, DPMBase::random, randomiseSpecies, BaseInteractable::setPosition(), BaseParticle::setRadius(), BaseParticle::setSpecies(), BaseInteractable::setVelocity(), DPMBase::speciesHandler, Vec3D::X, Vec3D::Y, and Vec3D::Z.
createBaseSpecies() [1/5]
virtual void SilbertPeriodic::createBaseSpecies () inline virtual
{
         //only create once
         static bool created=false;
         if (!created) {
             auto species1 = speciesHandler.copyAndAddObject(species);
             baseSpecies = speciesHandler.getMixedObject(species, species1);
             for (unsigned int i=0; i<particleHandler.getNumberOfObjects(); i++) {
                 if (particleHandler.getObject(i)->isFixed()) particleHandler.getObject(i)->setSpecies(speciesHandler.getObject(1));
             }
         }
     }
References baseSpecies, BaseHandler< T >::copyAndAddObject(), SpeciesHandler::getMixedObject(), ParticleHandler::getNumberOfObjects(), BaseHandler< T >::getObject(), i, BaseParticle::isFixed(), DPMBase::particleHandler, BaseParticle::setSpecies(), species, and DPMBase::speciesHandler.
Referenced by FlowRule::run(), and setSlidingFrictionCoefficientBottom().
createBaseSpecies() [2/5]
virtual void SilbertPeriodic::createBaseSpecies () inline virtual
{
         //only create once
         static bool created=false;
         if (!created) {
             auto species1 = speciesHandler.copyAndAddObject(species);
             baseSpecies = speciesHandler.getMixedObject(species, species1);
             for (unsigned int i=0; i<particleHandler.getNumberOfObjects(); i++) {
                 if (particleHandler.getObject(i)->isFixed()) particleHandler.getObject(i)->setSpecies(speciesHandler.getObject(1));
             }
         }
     }
References baseSpecies, BaseHandler< T >::copyAndAddObject(), SpeciesHandler::getMixedObject(), ParticleHandler::getNumberOfObjects(), BaseHandler< T >::getObject(), i, BaseParticle::isFixed(), DPMBase::particleHandler, BaseParticle::setSpecies(), species, and DPMBase::speciesHandler.
createBaseSpecies() [3/5]
void SilbertPeriodic::createBaseSpecies () inline
{
         //only create once
         static bool created=false;
         if (!created) {
             speciesHandler.copyAndAddObject(speciesHandler.getObject(0));
             created = true;
             for (int i=0; i<get_N(); i++) {
                 if (Particles[i].is_fixed()) Particles[i].indSpecies=1;
             }
         }
     }
References i.
createBaseSpecies() [4/5]
virtual void SilbertPeriodic::createBaseSpecies () inline virtual
{
         //only create once
         static bool created=false;
         if (!created) {
             speciesHandler.copyAndAddObject(speciesHandler.getObject(0));
             created = true;
             for (unsigned int i=0; i<particleHandler.getNumberOfObjects(); i++) {
                 if (particleHandler.getObject(i)->isFixed()) particleHandler.getObject(i)->setSpecies(speciesHandler.getObject(1));
             }
         }
     }
References i.
createBaseSpecies() [5/5]
virtual void SilbertPeriodic::createBaseSpecies () inline virtual
{
         //only create once
         static bool created=false;
         if (!created) {
             auto species1 = speciesHandler.copyAndAddObject(species);
             baseSpecies = speciesHandler.getMixedObject(species, species1);
             for (unsigned int i=0; i<particleHandler.getNumberOfObjects(); i++) {
                 if (particleHandler.getObject(i)->isFixed())
                     particleHandler.getObject(i)->setSpecies(speciesHandler.getObject(1));
             }
         }
     }
References baseSpecies, BaseHandler< T >::copyAndAddObject(), SpeciesHandler::getMixedObject(), ParticleHandler::getNumberOfObjects(), BaseHandler< T >::getObject(), i, BaseParticle::isFixed(), DPMBase::particleHandler, BaseParticle::setSpecies(), species, and DPMBase::speciesHandler.
fix_hgrid() [1/2]
void SilbertPeriodic::fix_hgrid () inline
                      {
         //assume 1-2 levels are optimal (which is the case for mono and bidispersed) and set the cell size to min and max
         // !this is not optimal for polydispersed
         double minCell = 2.*min(getFixedParticleRadius(),getMinInflowParticleRadius());
         double maxCell = 2.*max(getFixedParticleRadius(),getMaxInflowParticleRadius());
         if ((minCell==maxCell)|(minCell==0.)) set_HGRID_max_levels(1);
         else set_HGRID_max_levels(2);
         set_HGRID_cell_to_cell_ratio (1.0000001*maxCell/minCell);
     }
References max, and min.
fix_hgrid() [2/2]
void SilbertPeriodic::fix_hgrid () inline
                      {
         //assume 1-2 levels are optimal (which is the case for mono and bidispersed) and set the cell size to min and max
         // !this is not optimal for polydispersed
         Mdouble minCell = 2.*min(getFixedParticleRadius(),getMinInflowParticleRadius());
         Mdouble maxCell = 2.*max(getFixedParticleRadius(),getMaxInflowParticleRadius());
         if ((minCell==maxCell)|(minCell==0.)) set_HGRID_max_levels(1);
         else set_HGRID_max_levels(2);
         set_HGRID_cell_to_cell_ratio (1.0000001*maxCell/minCell);
     }
References max, and min.
get_H() [1/5]
Mdouble SilbertPeriodic::get_H () inline
     { return getInflowHeight(); }
References Chute::getInflowHeight().
Referenced by SilbertHstop::IsAboveCurve().
get_H() [2/5]
double SilbertPeriodic::get_H () inline
     { return getInflowHeight(); }
References Chute::getInflowHeight().
get_H() [3/5]
double SilbertPeriodic::get_H () inline
 {return InflowHeight;}
get_H() [4/5]
Mdouble SilbertPeriodic::get_H () inline
 {return InflowHeight;}
get_H() [5/5]
Mdouble SilbertPeriodic::get_H () inline
     { return getInflowHeight(); }
References Chute::getInflowHeight().
getNCreated() [1/3]
int SilbertPeriodic::getNCreated () const inline
     {
         return nCreated_;
     }
References nCreated_.
Referenced by add_flow_particles().
getNCreated() [2/3]
int SilbertPeriodic::getNCreated () const inline
     {
         return nCreated_;
     }
References nCreated_.
getNCreated() [3/3]
int SilbertPeriodic::getNCreated () const inline
     {
         return nCreated_;
     }
References nCreated_.
getSlidingFrictionCoefficientBottom() [1/4]
Mdouble SilbertPeriodic::getSlidingFrictionCoefficientBottom () inline
{
         if (baseSpecies!= nullptr)
             return baseSpecies->getSlidingFrictionCoefficient();
         else return species->getSlidingFrictionCoefficient();
     }
References baseSpecies, and species.
Referenced by readNextArgument(), and set_study().
getSlidingFrictionCoefficientBottom() [2/4]
double SilbertPeriodic::getSlidingFrictionCoefficientBottom () inline
{
         if (speciesHandler.getNumberOfObjects()>1) return speciesHandler.getMixedObject(1,0)->getSlidingFrictionCoefficient();
         else return getSlidingFrictionCoefficient();
     }
getSlidingFrictionCoefficientBottom() [3/4]
Mdouble SilbertPeriodic::getSlidingFrictionCoefficientBottom () inline
{
         if (speciesHandler.getNumberOfObjects()>1) return speciesHandler.getMixedObject(1,0)->getSlidingFrictionCoefficient();
         else return getSlidingFrictionCoefficient();
     }
getSlidingFrictionCoefficientBottom() [4/4]
Mdouble SilbertPeriodic::getSlidingFrictionCoefficientBottom () inline
{
         if (baseSpecies!= nullptr)
             return baseSpecies->getSlidingFrictionCoefficient();
         else return species->getSlidingFrictionCoefficient();
     }
References baseSpecies, and species.
increaseNCreated() [1/3]
void SilbertPeriodic::increaseNCreated () inline
     {
         nCreated_++;
     }
References nCreated_.
Referenced by add_flow_particles().
increaseNCreated() [2/3]
void SilbertPeriodic::increaseNCreated () inline
     {
         nCreated_++;
     }
References nCreated_.
increaseNCreated() [3/3]
void SilbertPeriodic::increaseNCreated () inline
     {
         nCreated_++;
     }
References nCreated_.
printTime() [1/5]
void SilbertPeriodic::printTime () inline
                      {
         cout << "t=" << setprecision(3) << left << setw(6) << getTime()
             << ", tmax=" << setprecision(3) << left << setw(6) << getTimeMax()
             << ", N=" << setprecision(3) << left << setw(6) << Particles.size()
             //<< ", time left=" << setprecision(3) << left << setw(6) << timer.getTime2Finish(t)
             //~ << ", finish by " << setprecision(3) << left << setw(6) << timer.getFinishTime(t)
             << ". " << endl;
     }
printTime() [2/5]
void SilbertPeriodic::printTime () inline
                      {
         cout << "t=" << setprecision(3) << left << setw(6) << getTime()
             << ", tmax=" << setprecision(3) << left << setw(6) << getTimeMax()
             << ", N=" << setprecision(3) << left << setw(6) << particleHandler.getNumberOfObjects()
             //<< ", time left=" << setprecision(3) << left << setw(6) << timer.getTime2Finish(t)
             //~ << ", finish by " << setprecision(3) << left << setw(6) << timer.getFinishTime(t)
             << ". " << endl;
     }
printTime() [3/5]
void SilbertPeriodic::printTime () const inline override virtual
Displays the current simulation time and the maximum simulation duration.
Gets and prints the current simulation time (getTime()) and the currently set maximum simulation time (getTimeMax()) .
Reimplemented from DPMBase.
Reimplemented in vibratedBed.
     {
         logger(INFO, "t=%3.6"
                      ", tmax=%3.6"
                      ", N=%3.6"
                      ", theta=3.6",
                getTime(), getTimeMax(), particleHandler.getNumberOfObjects(), getChuteAngleDegrees());
         //<< ", time left=" << setprecision(3) << left << setw(6) << timer.getTime2Finish(t)
         //~ << ", finish by " << setprecision(3) << left << setw(6) << timer.getFinishTime(t)
     }
References Chute::getChuteAngleDegrees(), ParticleHandler::getNumberOfObjects(), DPMBase::getTime(), DPMBase::getTimeMax(), INFO, logger, and DPMBase::particleHandler.
Referenced by SilbertHstop::continueSolve().
printTime() [4/5]
void SilbertPeriodic::printTime () const inline override virtual
Displays the current simulation time and the maximum simulation duration.
Gets and prints the current simulation time (getTime()) and the currently set maximum simulation time (getTimeMax()) .
Reimplemented from DPMBase.
Reimplemented in vibratedBed.
     {
         logger(INFO, "t=%3.6"
                      ", tmax=%3.6"
                      ", N=%3.6",
                getTime(), getTimeMax(), particleHandler.getNumberOfObjects());
         //<< ", time left=" << setprecision(3) << left << setw(6) << timer.getTime2Finish(t)
         //~ << ", finish by " << setprecision(3) << left << setw(6) << timer.getFinishTime(t)
     }
References ParticleHandler::getNumberOfObjects(), DPMBase::getTime(), DPMBase::getTimeMax(), INFO, logger, and DPMBase::particleHandler.
printTime() [5/5]
void SilbertPeriodic::printTime () const inline override virtual
Displays the current simulation time and the maximum simulation duration.
Gets and prints the current simulation time (getTime()) and the currently set maximum simulation time (getTimeMax()) .
Reimplemented from DPMBase.
Reimplemented in vibratedBed.
     {
         logger(INFO, "t=%3.6"
                      ", tmax=%3.6"
                      ", N=%3.6"
                      ", theta=%3.6",
                getTime(), getTimeMax(), particleHandler.getNumberOfObjects(), getChuteAngleDegrees());
         //<< ", time left=" << setprecision(3) << left << setw(6) << timer.getTime2Finish(t)
         //~ << ", finish by " << setprecision(3) << left << setw(6) << timer.getFinishTime(t)
     }
References Chute::getChuteAngleDegrees(), ParticleHandler::getNumberOfObjects(), DPMBase::getTime(), DPMBase::getTimeMax(), INFO, logger, and DPMBase::particleHandler.
readNextArgument() [1/4]
bool SilbertPeriodic::readNextArgument (int & i, int argc, char * argv[]) inline override virtual
Interprets the i^th command-line argument.
Reads, recognises and applies all valid flags passed when starting or restarting a Mercury simulation.
For all of the N = argc (argument count) command line arguments passed when starting/restarting a code (e.g. -tmax, -tmin ...), compares them to the "known" arguments understood by Mercury (note that further recognised arguments can be added in derived classes). If a match is found, the relevant parameter is set to the corresponding value(s) following the flag and true is returned. Otherwise, false is returned.
For instance, if the flag -xmin 0 is passed, the code's second if statement will recognise the flag, convert the subsequent string in argv to a double, and then call the setXMin() function to implement the new value (0) of XMin.
For developers: note the use of strcmp here. This cannot be replaced with a simpler ==, as we are comparing c-style strings (char*), instead of std::string. Thus, == would return equality of the pointers instead of the contents of the string. strcmp returns 0 if the strings are the same, and another number if they are different. This is then implicitly cast to a bool, where 0->false and other numbers will give true. Finally, the !-operator makes sure that the expression in the if-statements are true if the strings are the same, and false otherwise.
Parameters
[in] i the position of the element that will be read, note that the count starts at 1, as element 0 is the name of the executable
[in] argc number of arguments the user has given
[in] *argv[] the command-line arguments the user has given when calling the executable
Returns
true if the argument is successfully read, and false otherwise.
-gravity_ requires three arguments
-restart or -r loads a restart file. By default, it loads <name>.restart. If an argument "arg" is given it loads the file "arg", or "arg".restart (if the ending is not given).
Reimplemented from DPMBase.
     {
         if (!strcmp(argv[i], "-muBottom"))
         {
             setSlidingFrictionCoefficientBottom(atof(argv[i + 1]));
             logger(INFO, "muB=%", getSlidingFrictionCoefficientBottom());
         }
         else return Chute::readNextArgument(i, argc, argv); //if argv[i] is not found, check the commands in Chute
         return true; //returns true if argv[i] is found
     }
References getSlidingFrictionCoefficientBottom(), i, INFO, logger, Chute::readNextArgument(), and setSlidingFrictionCoefficientBottom().
Referenced by FlowRule::readNextArgument().
readNextArgument() [2/4]
bool SilbertPeriodic::readNextArgument (int & i, int argc, char * argv[]) inline override virtual
Interprets the i^th command-line argument.
Reads, recognises and applies all valid flags passed when starting or restarting a Mercury simulation.
For all of the N = argc (argument count) command line arguments passed when starting/restarting a code (e.g. -tmax, -tmin ...), compares them to the "known" arguments understood by Mercury (note that further recognised arguments can be added in derived classes). If a match is found, the relevant parameter is set to the corresponding value(s) following the flag and true is returned. Otherwise, false is returned.
For instance, if the flag -xmin 0 is passed, the code's second if statement will recognise the flag, convert the subsequent string in argv to a double, and then call the setXMin() function to implement the new value (0) of XMin.
For developers: note the use of strcmp here. This cannot be replaced with a simpler ==, as we are comparing c-style strings (char*), instead of std::string. Thus, == would return equality of the pointers instead of the contents of the string. strcmp returns 0 if the strings are the same, and another number if they are different. This is then implicitly cast to a bool, where 0->false and other numbers will give true. Finally, the !-operator makes sure that the expression in the if-statements are true if the strings are the same, and false otherwise.
Parameters
[in] i the position of the element that will be read, note that the count starts at 1, as element 0 is the name of the executable
[in] argc number of arguments the user has given
[in] *argv[] the command-line arguments the user has given when calling the executable
Returns
true if the argument is successfully read, and false otherwise.
-gravity_ requires three arguments
-restart or -r loads a restart file. By default, it loads <name>.restart. If an argument "arg" is given it loads the file "arg", or "arg".restart (if the ending is not given).
Reimplemented from DPMBase.
     {
         if (!strcmp(argv[i], "-muBottom"))
         {
             setSlidingFrictionCoefficientBottom(atof(argv[i + 1]));
             logger(INFO, "muB=%", getSlidingFrictionCoefficientBottom());
         }
         else if (!strcmp(argv[i], "-oldValues"))
         {
             species->setSlidingDissipation(species->getDissipation());
             logger(INFO, "getSlidingDissipation()=%", species->getSlidingDissipation());
         }
         else return Chute::readNextArgument(i, argc, argv); //if argv[i] is not found, check the commands in Chute
         return true; //returns true if argv[i] is found
     }
References LinearViscoelasticNormalSpecies::getDissipation(), getSlidingFrictionCoefficientBottom(), i, INFO, logger, Chute::readNextArgument(), setSlidingFrictionCoefficientBottom(), and species.
readNextArgument() [3/4]
int SilbertPeriodic::readNextArgument (unsigned int & i, unsigned int & argc, char * argv[]) inline
{
         if (!strcmp(argv[i],"-muBottom")) {
             setSlidingFrictionCoefficientBottom(atof(argv[i+1]));
             cout << "muB=" << getSlidingFrictionCoefficientBottom() << endl;
         } else return Chute::readNextArgument(i, argc, argv); //if argv[i] is not found, check the commands in Chute
         return true; //returns true if argv[i] is found
     }
References i, and Chute::readNextArgument().
readNextArgument() [4/4]
int SilbertPeriodic::readNextArgument (unsigned int & i, unsigned int argc, char * argv[]) inline
{
         if (!strcmp(argv[i],"-muBottom")) {
             setSlidingFrictionCoefficientBottom(atof(argv[i+1]));
             cout << "muB=" << getSlidingFrictionCoefficientBottom() << endl;
         } else return Chute::readNextArgument(i, argc, argv); //if argv[i] is not found, check the commands in Chute
         return true; //returns true if argv[i] is found
     }
References i, and Chute::readNextArgument().
set_H() [1/5]
void SilbertPeriodic::set_H (double new_) inline
     {
         setInflowHeight(new_);
         setZMax(getInflowHeight());
     }
References Chute::getInflowHeight(), Chute::setInflowHeight(), and DPMBase::setZMax().
set_H() [2/5]
void SilbertPeriodic::set_H (double new_) inline
 {InflowHeight=new_; setZMax(InflowHeight);}
set_H() [3/5]
void SilbertPeriodic::set_H (Mdouble new_) inline
     {
         setInflowHeight(new_);
         setZMax(getInflowHeight());
     }
References Chute::getInflowHeight(), Chute::setInflowHeight(), and DPMBase::setZMax().
Referenced by SilbertPeriodic().
set_H() [4/5]
void SilbertPeriodic::set_H (Mdouble new_) inline
 {InflowHeight=new_; setZMax(InflowHeight);}
set_H() [5/5]
void SilbertPeriodic::set_H (Mdouble new_) inline
     {
         setInflowHeight(new_);
         setZMax(getInflowHeight());
     }
References Chute::getInflowHeight(), Chute::setInflowHeight(), and DPMBase::setZMax().
set_study() [1/12]
void SilbertPeriodic::set_study () inline
                      {
       std::stringstream name;
         name << "H" << getInflowHeight()
              << "A" << getChuteAngleDegrees()
              << "L" << round(100.*getFixedParticleRadius()*2.)/100.
              << "M" << species->getSlidingFrictionCoefficient()
              << "B" << getSlidingFrictionCoefficientBottom();
         dataFile.setName(name.str().c_str());
         //set_data_filename();
     }
References DPMBase::dataFile, Chute::getChuteAngleDegrees(), Chute::getFixedParticleRadius(), Chute::getInflowHeight(), getSlidingFrictionCoefficientBottom(), plotDoE::name, Eigen::bfloat16_impl::round(), File::setName(), and species.
Referenced by FlowRule::run(), vibratedBed::run(), and set_study().
set_study() [2/12]
void SilbertPeriodic::set_study () inline
                      {
         stringstream name;
         name << "H" << getInflowHeight()
              << "A" << getChuteAngleDegrees()
              << "L" << round(100.*getFixedParticleRadius()*2.)/100.
              << "M" << getSlidingFrictionCoefficient()
              << "B" << getSlidingFrictionCoefficientBottom();
         setName(name.str().c_str());
         set_data_filename();
     }
References plotDoE::name, and Eigen::bfloat16_impl::round().
set_study() [3/12]
void SilbertPeriodic::set_study () inline
                      {
         stringstream name;
         name << "H" << getInflowHeight()
              << "A" << getChuteAngleDegrees()
              << "L" << round(100.*getFixedParticleRadius()*2.)/100.
              << "M" << getSlidingFrictionCoefficient()
              << "B" << getSlidingFrictionCoefficientBottom();
         setName(name.str().c_str());
         set_data_filename();
     }
References plotDoE::name, and Eigen::bfloat16_impl::round().
set_study() [4/12]
void SilbertPeriodic::set_study () inline
                      {
       std::stringstream name;
         name << "H" << getInflowHeight()
              << "A" << getChuteAngleDegrees()
              << "L" << round(100.*getFixedParticleRadius()*2.)/100.
              << "M" << species->getSlidingFrictionCoefficient()
              << "B" << getSlidingFrictionCoefficientBottom();
         setName(name.str().c_str());
         //set_data_filename();
     }
References Chute::getChuteAngleDegrees(), Chute::getFixedParticleRadius(), Chute::getInflowHeight(), getSlidingFrictionCoefficientBottom(), plotDoE::name, Eigen::bfloat16_impl::round(), DPMBase::setName(), and species.
set_study() [5/12]
void SilbertPeriodic::set_study (int study_num) inline
{
         logger(INFO, "using mu=0, r=0.5");
         species->setCollisionTimeAndRestitutionCoefficient
                 (50. * getTimeStep(), 0.5, 1);
         std::stringstream name;
         name << "H" << getInflowHeight()
              << "A" << getChuteAngleDegrees()
              << "L" << round(100. * getFixedParticleRadius() * 2.) / 100.;
         setName(name.str().c_str());
     }
References Chute::getChuteAngleDegrees(), Chute::getFixedParticleRadius(), Chute::getInflowHeight(), DPMBase::getTimeStep(), INFO, logger, plotDoE::name, Eigen::bfloat16_impl::round(), LinearViscoelasticNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), DPMBase::setName(), and species.
set_study() [6/12]
void SilbertPeriodic::set_study (int study_num) inline
{
         //S=0-5: lambda = 0, 3./6., 4./6., 5./6., 1, 2
         //S=6-8: mu = 0, 1, inf
         //S=9-13: mub = 0,1,inf,1/4,1/8
         //S=14-15: mu = 1/4, 1/8
         //S=16-19: lambda = 1./6., 2./6., 1.5, 4
         //S=21-25: mub=1/16,1/32,1/64,1/128,1/1024
         //S=26-28: lambda=1/2, mub=1/16,1/128,1/1024
         //S=29-32: lambda=0, mub=1/16,1/128,1/1024,0
         if (study_num < 6) {
             // set mu_all = 0.5, vary lambda
             double Lambdas[] = {0, 3./6., 4./6., 5./6., 1, 2};
             setFixedParticleRadius(Lambdas[study_num]/2.);
         } else {
             //If study_num is complete quit
             logger(VERBOSE, "Study is complete ");
             exit(0);
         }
         //Note make sure h and a is defined
         set_study();
     }
References logger, set_study(), Chute::setFixedParticleRadius(), and VERBOSE.
set_study() [7/12]
void SilbertPeriodic::set_study (int study_num) inline
{
         //S=0-5: lambda = 0, 3./6., 4./6., 5./6., 1, 2
         //S=6-8: mu = 0, 1, inf
         //S=9-13: mub = 0,1,inf,1/4,1/8
         //S=14-15: mu = 1/4, 1/8
         //S=16-19: lambda = 1./6., 2./6., 1.5, 4
         //S=21-25: mub=1/16,1/32,1/64,1/128,1/1024
         //S=26-28: lambda=1/2, mub=1/16,1/128,1/1024
         //S=29-32: lambda=0, mub=1/16,1/128,1/1024,0
         if (study_num < 6) {
             // set mu_all = 0.5, vary lambda
             double Lambdas[] = {0, 3./6., 4./6., 5./6., 1, 2};
             setFixedParticleRadius(Lambdas[study_num]/2.);
         } else {
             //If study_num is complete quit
             cout << "Study is complete " << endl;
             exit(0);
         }
         //Note make sure h and a is defined
         set_study();
     }
set_study() [8/12]
void SilbertPeriodic::set_study (int study_num) inline
{
         //S=0-5: lambda = 0, 3./6., 4./6., 5./6., 1, 2
         //S=6-8: mu = 0, 1, inf
         //S=9-13: mub = 0,1,inf,1/4,1/8
         //S=14-15: mu = 1/4, 1/8
         //S=16-19: lambda = 1./6., 2./6., 1.5, 4
         //S=21-25: mub=1/16,1/32,1/64,1/128,1/1024
         //S=26-28: lambda=1/2, mub=1/16,1/128,1/1024
         //S=29-32: lambda=0, mub=1/16,1/128,1/1024,0
         if (study_num < 6) {
             // set mu_all = 0.5, vary lambda
             Mdouble Lambdas[] = {0, 3./6., 4./6., 5./6., 1, 2};
             setFixedParticleRadius(Lambdas[study_num]/2.);
             setSlidingFrictionCoefficient(0.5);
         } else if (study_num < 9) { //Case 6,7,8
             // set lambda = 1, vary mu_all
             Mdouble MuAll[] = {0, 1., 1e20};
             setSlidingFrictionCoefficient(MuAll[study_num-6]);
             setFixedParticleRadius(0.5);
         } else if (study_num < 12) { //Case 9,10,11
             // set lambda = 1, mu_all = 0.5, vary mu_bottom
             Mdouble MuBottom[] = {0, 1., 1e20};
             setSlidingFrictionCoefficient(0.5);
             setSlidingFrictionCoefficientBottom(MuBottom[study_num-9]);
             setFixedParticleRadius(0.5);
         } else if (study_num < 14) { //Case 12,13
             // set lambda = 1, mu_all = 0.5, vary mu_bottom
             Mdouble MuBottom[] = {0.25, 0.125};
             setSlidingFrictionCoefficient(0.5);
             setSlidingFrictionCoefficientBottom(MuBottom[study_num-12]);
             setFixedParticleRadius(0.5);
         } else if (study_num < 16) { //Case 14,15
             // set lambda = 1, vary mu_all
             Mdouble MuAll[] = {0.25, 0.125};
             setSlidingFrictionCoefficient(MuAll[study_num-14]);
             setFixedParticleRadius(0.5);
         } else if (study_num < 21) { //Case 16,17,18,19,20
             // set mu_all = 0.5, vary lambda
             Mdouble Lambdas[] = {1./6., 2./6., 1.5, 4, 1./12};
             setFixedParticleRadius(Lambdas[study_num-16]/2.);
             setSlidingFrictionCoefficient(0.5);
         } else if (study_num < 26) { //Case 21 22 23 24 25
             // set lambda = 1, mu_all = 0.5, vary mu_bottom
             Mdouble MuBottom[] = {1./16.,1./32.,1./64.,1./128.,1./1024.};
             setSlidingFrictionCoefficient(0.5);
             setSlidingFrictionCoefficientBottom(MuBottom[study_num-21]);
             setFixedParticleRadius(0.5);
         } else if (study_num < 29) { //Case 26 27 28
             // set lambda = 1/2, mu_all = 0.5, vary mu_bottom
             Mdouble MuBottom[] = {1./16.,1./128.,1./1024.};
             setSlidingFrictionCoefficient(0.5);
             setSlidingFrictionCoefficientBottom(MuBottom[study_num-26]);
             setFixedParticleRadius(0.25);
         } else if (study_num < 33) { //Case 29 30 31 32
             // set lambda = 0, mu_all = 0.5, vary mu_bottom
             Mdouble MuBottom[] = {1./16.,1./128.,1./1024.,0};
             setSlidingFrictionCoefficient(0.5);
             setSlidingFrictionCoefficientBottom(MuBottom[study_num-29]);
             setFixedParticleRadius(0);
         } else if (study_num < 37) { //Case 33-36
             cout << "S" << study_num << endl;
             // set lambda = 1, mu_b = 0.5, vary mu
             Mdouble Mu[] = {1e20,1,1./64,0};
             setSlidingFrictionCoefficient(Mu[study_num-33]);
             setSlidingFrictionCoefficientBottom(0.5);
             setFixedParticleRadius(1);
         } else {
             //If study_num is complete quit
             cout << "Study is complete " << endl;
             exit(0);
         }
         //Note make sure h and a is defined
         set_study();
     }
References Global_Parameters::Mu.
set_study() [9/12]
void SilbertPeriodic::set_study (int study_num) inline
Todo:
Thomas: Hertzian does not appear in the restart file
Todo:
TW: can we switch species from SlidingFriction to Friction only in the case rolling friction is needed?
Todo:
turn on rolling friction only at the wall
{
         //S=0-5: lambda = 0, 3./6., 4./6., 5./6., 1, 2
         //S=6-8: mu = 0, 1, inf
         //S=9-13: mub = 0,1,inf,1/4,1/8
         //S=14-15: mu = 1/4, 1/8
         //S=16-19: lambda = 1./6., 2./6., 1.5, 4
         //S=21-25: mub=1/16,1/32,1/64,1/128,1/1024
         //S=26-28: lambda=1/2, mub=1/16,1/128,1/1024
         //S=29-32: lambda=0, mub=1/16,1/128,1/1024,0
         //Case 37 set getSlidingDissipation()=0
         //Case 38 set eps=0.97
         //Case 39 set hertzian = true
         //Case 40, 41, 42: set Foerster glass, Lorenz steel, Lorenz glassv
         //Case 43, 44, 45, 46: set Silbert, Foerster glass, Lorenz steel, Lorenz glass with rolling friction
       logger(INFO, "Study %", study_num);
         if (study_num < 6) {
             // set mu_all = 0.5, vary lambda
             Mdouble Lambdas[] = {0, 3./6., 4./6., 5./6., 1, 2};
             setFixedParticleRadius(Lambdas[study_num]/2.);
             species->setSlidingFrictionCoefficient(0.5);
         } else if (study_num < 9) { //Case 6,7,8
             // set lambda = 1, vary mu_all
             Mdouble MuAll[] = {0, 1., 1e20};
             species->setSlidingFrictionCoefficient(MuAll[study_num-6]);
             setFixedParticleRadius(0.5);
         } else if (study_num < 12) { //Case 9,10,11
             // set lambda = 1, mu_all = 0.5, vary mu_bottom
             Mdouble MuBottom[] = {0, 1., 1e20};
             species->setSlidingFrictionCoefficient(0.5);
             setSlidingFrictionCoefficientBottom(MuBottom[study_num-9]);
             setFixedParticleRadius(0.5);
         } else if (study_num < 14) { //Case 12,13
             // set lambda = 1, mu_all = 0.5, vary mu_bottom
             Mdouble MuBottom[] = {0.25, 0.125};
             species->setSlidingFrictionCoefficient(0.5);
             setSlidingFrictionCoefficientBottom(MuBottom[study_num-12]);
             setFixedParticleRadius(0.5);
         } else if (study_num < 16) { //Case 14,15
             // set lambda = 1, vary mu_all
             Mdouble MuAll[] = {0.25, 0.125};
             species->setSlidingFrictionCoefficient(MuAll[study_num-14]);
             setFixedParticleRadius(0.5);
         } else if (study_num < 21) { //Case 16,17,18,19,20
             // set mu_all = 0.5, vary lambda
             Mdouble Lambdas[] = {1./6., 2./6., 1.5, 4, 1./12};
             setFixedParticleRadius(Lambdas[study_num-16]/2.);
             species->setSlidingFrictionCoefficient(0.5);
         } else if (study_num < 26) { //Case 21 22 23 24 25
             // set lambda = 1, mu_all = 0.5, vary mu_bottom
             Mdouble MuBottom[] = {1./16.,1./32.,1./64.,1./128.,1./1024.};
             species->setSlidingFrictionCoefficient(0.5);
             setSlidingFrictionCoefficientBottom(MuBottom[study_num-21]);
             setFixedParticleRadius(0.5);
         } else if (study_num < 29) { //Case 26 27 28
             // set lambda = 1/2, mu_all = 0.5, vary mu_bottom
             Mdouble MuBottom[] = {1./16.,1./128.,1./1024.};
             species->setSlidingFrictionCoefficient(0.5);
             setSlidingFrictionCoefficientBottom(MuBottom[study_num-26]);
             setFixedParticleRadius(0.25);
         } else if (study_num < 33) { //Case 29 30 31 32
             // set lambda = 0, mu_all = 0.5, vary mu_bottom
             Mdouble MuBottom[] = {1./16.,1./128.,1./1024.,0};
             species->setSlidingFrictionCoefficient(0.5);
             setSlidingFrictionCoefficientBottom(MuBottom[study_num-29]);
             setFixedParticleRadius(0);
         } else if (study_num < 37) { //Case 33-36
             logger(INFO, "S %", study_num);
             // set lambda = 1, mu_b = 0.5, vary mu
             Mdouble Mu[] = {1e20,1,1./64,0};
             species->setSlidingFrictionCoefficient(Mu[study_num-33]);
             setSlidingFrictionCoefficientBottom(0.5);
             setFixedParticleRadius(1);
         } else if (study_num < 38) { //Case 37
             // set getSlidingDissipation()=0
           species->setSlidingDissipation(0);
         } else if (study_num < 39) { //Case 38
             // set eps=0.97
             Mdouble eps = 0.97;
             species->setStiffnessAndRestitutionCoefficient(species->getStiffness(), eps, 1);
             species->setSlidingDissipation(species->getDissipation());
         } else if (study_num < 40)
         { //Case 39
             // set hertzian = true
             logger(INFO, "Hertzian implementation has been changed");
             exit(-1);
             //set_Hertzian(true);
         } else if (study_num < 43) { //Case 40, 41, 42
             // set Foerster glass, Lorenz steel, Lorenz glass
             Mdouble eps[] = {0.97 , 0.95 , 0.972};
             Mdouble beta[]= {0.44 , 0.32 , 0.25 };
             Mdouble mu[]  = {0.092, 0.099, 0.177};
             species->setSlidingFrictionCoefficient(mu[study_num-40]);
             species->setCollisionTimeAndNormalAndTangentialRestitutionCoefficient
                 (50.*getTimeStep(), eps[study_num-40], beta[study_num-40], 1);
         } else if (study_num < 47) { //Case 43, 44, 45, 46
             // set Silbert, Foerster glass, Lorenz steel, Lorenz glass with rolling friction
             Mdouble eps[] = {0.97 , 0.95 , 0.972};
             Mdouble beta[]= {0.44 , 0.32 , 0.25 };
             Mdouble mu[]  = {0.092, 0.099, 0.177};
             if (study_num!=43) {
               species->setSlidingFrictionCoefficient(mu[study_num-44]);
               species->setCollisionTimeAndNormalAndTangentialRestitutionCoefficient
                     (50.*getTimeStep(), eps[study_num-44], beta[study_num-44], 1);
             }
             species->setRollingStiffness(0.4*species->getStiffness());
             species->setRollingFrictionCoefficient(0.05);
         } else if (study_num < 48) { //Case 47
             // set lambda = 1, mu_all = 0.5, vary mu_half
             Mdouble MuHalf[] = {0};
             species->setSlidingFrictionCoefficient(MuHalf[study_num-47]);
             setSlidingFrictionCoefficientBottom(0.5);
             setFixedParticleRadius(0.5);
             randomiseSpecies = true;
         } else if (study_num < 52) { //Case 48, 49, 50, 51
             // set vary eps
             Mdouble eps[] = {0.001, 0.01, 0.1, 1};
             species->setCollisionTimeAndNormalAndTangentialRestitutionCoefficient
                     (50.*getTimeStep(), eps[study_num-48], eps[study_num-48], 1);
             species->setSlidingFrictionCoefficient(0.0);
         } else if (study_num < 53) { //Case 52
         } else if (study_num < 54) { //Case 53
             logger(INFO, "using mu=0.3, r=0.1");
             species->setSlidingFrictionCoefficient(0.3);
             species->setCollisionTimeAndNormalAndTangentialRestitutionCoefficient
                      (50.*getTimeStep(),0.1,0.1,1);
         } else if (study_num < 55) { //Case 54
             logger(INFO, "using mu=0.3, r=0.88");
             species->setSlidingFrictionCoefficient(0.3);
             species->setCollisionTimeAndNormalAndTangentialRestitutionCoefficient
                      (50.*getTimeStep(),0.88,0.88,1);
         } else
         {
             //If study_num is complete quit
             logger(VERBOSE, "Study is complete ");
             exit(0);
         }
         //Note make sure h and a is defined
         if (study_num < 37 || (study_num>=53&&study_num<=55))
         {
             set_study();
         }
         else
         {
           std::stringstream name;
             name << "S" << study_num;
             dataFile.setName(name.str().c_str());
             //set_data_filename();
         }
     }
References beta, DPMBase::dataFile, CRBond_Bessel::eps, LinearViscoelasticNormalSpecies::getDissipation(), LinearViscoelasticNormalSpecies::getStiffness(), DPMBase::getTimeStep(), INFO, logger, Global_Parameters::Mu, Global_Parameters::mu, plotDoE::name, randomiseSpecies, set_study(), Chute::setFixedParticleRadius(), File::setName(), setSlidingFrictionCoefficientBottom(), LinearViscoelasticNormalSpecies::setStiffnessAndRestitutionCoefficient(), species, and VERBOSE.
set_study() [10/12]
void SilbertPeriodic::set_study (std::vector< int > study_num) inline
{
         double Heights[] = {10, 20, 30, 40};
         double Angles[] = {20, 22, 24, 26, 28, 30, 40, 50, 60};
         setInflowHeight(Heights[study_num[1]-1]);
         setChuteAngle(Angles[study_num[2]-1]);
         set_study(study_num[0]);
     }
References set_study(), Chute::setChuteAngle(), and Chute::setInflowHeight().
set_study() [11/12]
void SilbertPeriodic::set_study (vector< int > study_num) inline
{
         double Heights[] = {10, 20, 30, 40};
         double Angles[] = {20, 22, 24, 26, 28, 30, 40, 50, 60};
         setInflowHeight(Heights[study_num[1]-1]);
         setChuteAngle(Angles[study_num[2]-1]);
         set_study(study_num[0]);
     }
set_study() [12/12]
void SilbertPeriodic::set_study (vector< int > study_num) inline
{
         Mdouble Heights[] = {10, 20, 30, 40};
         Mdouble Angles[] = {20, 22, 24, 26, 28, 30, 40, 50, 60};
         setInflowHeight(Heights[study_num[1]-1]);
         setChuteAngle(Angles[study_num[2]-1]);
         set_study(study_num[0]);
     }
setSlidingFrictionCoefficientBottom() [1/4]
void SilbertPeriodic::setSlidingFrictionCoefficientBottom (double new_) inline
{
         createBaseSpecies();
         speciesHandler.getMixedObject(1, 0)->setSlidingFrictionCoefficient(new_);
     }
setSlidingFrictionCoefficientBottom() [2/4]
void SilbertPeriodic::setSlidingFrictionCoefficientBottom (Mdouble new_) inline
{
         createBaseSpecies();
         baseSpecies->setSlidingFrictionCoefficient(new_);
     }
References baseSpecies, and createBaseSpecies().
Referenced by readNextArgument(), and set_study().
setSlidingFrictionCoefficientBottom() [3/4]
void SilbertPeriodic::setSlidingFrictionCoefficientBottom (Mdouble new_) inline
{
         createBaseSpecies();
         speciesHandler.getMixedObject(1, 0)->setSlidingFrictionCoefficient(new_);
     }
setSlidingFrictionCoefficientBottom() [4/4]
void SilbertPeriodic::setSlidingFrictionCoefficientBottom (Mdouble new_) inline
{
         createBaseSpecies();
         baseSpecies->setSlidingFrictionCoefficient(new_);
     }
References baseSpecies, and createBaseSpecies().
setupInitialConditions() [1/5]
void SilbertPeriodic::setupInitialConditions () inline override virtual
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
A virtual function with no implementation but can be overridden.
Todo:
I (Anthony) wants to change this to be an external function. This has a lot of advantages especially when using copy-constructors. This is a major change and will break other codes, so therefore has to be done carefully.
This sets up the particles initial conditions it is as you expect the user to override this. By default the particles are randomly distributed
todo{I(Dinant) had to clear the WallHandler to prevent it from inserting the same wall twice, why?}
Reimplemented from DPMBase.
{
         //fix_hgrid();
         particleHandler.setStorageCapacity(particleHandler.getNumberOfObjects()+getChuteLength()*getChuteWidth()*getZMax());//why is this line needed?
         createBottom();
         //~ write(std::cout,false);
         //cout << "correct fixed" << endl;
         if (speciesHandler.getNumberOfObjects()>1) {
             for (unsigned int i=0; i<particleHandler.getNumberOfObjects(); i++)
                 if (particleHandler.getObject(i)->isFixed())
                     particleHandler.getObject(i)->setSpecies(speciesHandler.getObject(1));
         }
         wallHandler.clear();
         InfiniteWall w0;
         if (getFixedParticleRadius())
         {
             w0.set(Vec3D(0, 0, -1), Vec3D(0, 0, -3.4 * getMaxInflowParticleRadius()));
         }
         else
         {
             w0.set(Vec3D(0, 0, -1), Vec3D(0, 0, 0));
         }
         wallHandler.copyAndAddObject(w0);
         PeriodicBoundary b0;
         b0.set(Vec3D(1.0, 0.0, 0.0), getXMin(), getXMax());
         boundaryHandler.copyAndAddObject(b0);
         b0.set(Vec3D(0.0, 1.0, 0.0), getYMin(), getYMax());
         boundaryHandler.copyAndAddObject(b0);
         add_flow_particles();
         logger(INFO, "\nStatus before solve:");
 //      std::cout
 //          << "tc=" << getCollisionTime()
 //          << ", eps=" << getRestitutionCoefficient()
 //          << ", vmax=" << getInflowParticle()->calculateMaximumVelocity(getSpecies())
 //          << ", inflowHeight/zMax=" << getInflowHeight()/getZMax()
 //          << std::endl << std::endl;
         //~ timer.set(t,tmax);
         //optimize number of buckets
         logger(INFO, "Nmax %", particleHandler.getStorageCapacity());
         //setHGridNumberOfBucketsToPower(particleHandler.getNumberOfObjects()*1.5);
     }
References add_flow_particles(), DPMBase::boundaryHandler, BaseHandler< T >::clear(), BaseHandler< T >::copyAndAddObject(), Chute::createBottom(), Chute::getChuteLength(), Chute::getChuteWidth(), Chute::getFixedParticleRadius(), Chute::getMaxInflowParticleRadius(), BaseHandler< T >::getNumberOfObjects(), ParticleHandler::getNumberOfObjects(), BaseHandler< T >::getObject(), BaseHandler< T >::getStorageCapacity(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), DPMBase::getZMax(), i, INFO, BaseParticle::isFixed(), logger, DPMBase::particleHandler, PeriodicBoundary::set(), InfiniteWall::set(), BaseParticle::setSpecies(), BaseHandler< T >::setStorageCapacity(), DPMBase::speciesHandler, and DPMBase::wallHandler.
setupInitialConditions() [2/5]
void SilbertPeriodic::setupInitialConditions () inline override virtual
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
A virtual function with no implementation but can be overridden.
Todo:
I (Anthony) wants to change this to be an external function. This has a lot of advantages especially when using copy-constructors. This is a major change and will break other codes, so therefore has to be done carefully.
This sets up the particles initial conditions it is as you expect the user to override this. By default the particles are randomly distributed
Reimplemented from DPMBase.
     {
       //fix_hgrid();
       //set_Nmax(particleHandler.getNumberOfObjects()+getChuteLength()*getChuteWidth()*getZMax());//why is this line needed?
         createBottom();
         //~ write(std::cout,false);
         //cout << "correct fixed" << endl;
         if (speciesHandler.getNumberOfObjects()>1) {
             for (int i=0; i<particleHandler.getNumberOfObjects(); i++)
               if (particleHandler.getObject(i)->isFixed())
                 particleHandler.getObject(i)->setSpecies(speciesHandler.getObject(1));
         }
         //set_NWall(1);
         InfiniteWall w0;
         if (getFixedParticleRadius()) {
             w0.set(Vec3D(0,0,-1), Vec3D(0,0,-3.4* getMaxInflowParticleRadius()));
         } else {
             w0.set(Vec3D(0,0,-1), Vec3D(0,0,0));
         }
         wallHandler.copyAndAddObject(w0);
         PeriodicBoundary b0;//set_NWallPeriodic(2);
         b0.set(Vec3D( 1.0, 0.0, 0.0), getXMin(), getXMax());
             boundaryHandler.copyAndAddObject(b0);
         b0.set(Vec3D( 0.0, 1.0, 0.0), getYMin(), getYMax());
         boundaryHandler.copyAndAddObject(b0);
         add_flow_particles();
 //      std::cout << std::endl << "Status before solve:" << std::endl;
 //      std::cout
 //          << "tc=" << getCollisionTime()
 //          << ", eps=" << getRestitutionCoefficient()
 //        //<< ", vmax=" << getMaximumVelocity()
 //          << ", getInflowHeight()/zmax=" << getInflowHeight()/getZMax()
 //          << std::endl << std::endl;
         //~ timer.set(t,tmax);
         //optimize number of buckets
         //std::cout << "Nmax" << get_Nmax() << std::endl;
         //setHGridNumberOfBucketsToPower(particleHandler.getNumberOfObjects()*1.5);
     }
References add_flow_particles(), DPMBase::boundaryHandler, BaseHandler< T >::copyAndAddObject(), Chute::createBottom(), Chute::getFixedParticleRadius(), Chute::getMaxInflowParticleRadius(), BaseHandler< T >::getNumberOfObjects(), ParticleHandler::getNumberOfObjects(), BaseHandler< T >::getObject(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), i, BaseParticle::isFixed(), DPMBase::particleHandler, PeriodicBoundary::set(), InfiniteWall::set(), BaseParticle::setSpecies(), DPMBase::speciesHandler, and DPMBase::wallHandler.
setupInitialConditions() [3/5]
void SilbertPeriodic::setupInitialConditions () inline override virtual
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
A virtual function with no implementation but can be overridden.
Todo:
I (Anthony) wants to change this to be an external function. This has a lot of advantages especially when using copy-constructors. This is a major change and will break other codes, so therefore has to be done carefully.
This sets up the particles initial conditions it is as you expect the user to override this. By default the particles are randomly distributed
Reimplemented from DPMBase.
     {
         fix_hgrid();
         set_Nmax(get_N()+getChuteLength()*getChuteWidth()*getZMax());//why is this line needed?
         createBottom();
         //~ write(std::cout,false);
         //cout << "correct fixed" << endl;
         if (Species.size()>1) {
             for (int i=0; i<get_N(); i++)
                 if (Particles[i].is_fixed())
                     Particles[i].indSpecies=1;
         }
         set_NWall(1);
         if (getFixedParticleRadius()) {
             wallHandler.getObject(0)->set(Vec3D(0,0,-1), 3.4*MaxInflowParticleRadius);
         } else {
             wallHandler.getObject(0)->set(Vec3D(0,0,-1), 0.);
         }
         set_NWallPeriodic(2);
         WallsPeriodic[0].set(Vec3D( 1.0, 0.0, 0.0), getXMin(), getXMax());
         WallsPeriodic[1].set(Vec3D( 0.0, 1.0, 0.0), getYMin(), getYMax());
         add_flow_particles();
         cout << endl << "Status before solve:" << endl;
         cout
             << "tc=" << getCollisionTime()
             << ", eps=" << getRestitutionCoefficient()
             << ", vmax=" << getMaximumVelocity()
             << ", InflowHeight/zmax=" << getInflowHeight()/getZMax()
             << endl << endl;
         //~ timer.set(t,tmax);
         //optimize number of buckets
         cout << "Nmax" << get_Nmax() << endl;
         set_HGRID_num_buckets_to_power(get_N()*1.5);
     }
References helpers::getMaximumVelocity(), and i.
setupInitialConditions() [4/5]
void SilbertPeriodic::setupInitialConditions () inline override virtual
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
A virtual function with no implementation but can be overridden.
Todo:
I (Anthony) wants to change this to be an external function. This has a lot of advantages especially when using copy-constructors. This is a major change and will break other codes, so therefore has to be done carefully.
This sets up the particles initial conditions it is as you expect the user to override this. By default the particles are randomly distributed
Reimplemented from DPMBase.
     {
         fix_hgrid();
         particleHandler.set_StorageCapacity(particleHandler.getNumberOfObjects()+getChuteLength()*getChuteWidth()*getZMax());//why is this line needed?
         createBottom();
         //~ write(std::cout,false);
         //cout << "correct fixed" << endl;
         if (Species.size()>1) {
             for (unsigned int i=0; i<particleHandler.getNumberOfObjects(); i++)
                 if (particleHandler.getObject(i)->isFixed())
                     particleHandler.getObject(i)->setSpecies(speciesHandler.getObject(1));
         }
         set_NWall(1);
         if (getFixedParticleRadius()) {
             wallHandler.getObject(0)->set(Vec3D(0,0,-1), 3.4*MaxInflowParticleRadius);
         } else {
             wallHandler.getObject(0)->set(Vec3D(0,0,-1), 0.);
         }
         set_NWallPeriodic(2);
         WallsPeriodic[0].set(Vec3D( 1.0, 0.0, 0.0), getXMin(), getXMax());
         WallsPeriodic[1].set(Vec3D( 0.0, 1.0, 0.0), getYMin(), getYMax());
         add_flow_particles();
         cout << endl << "Status before solve:" << endl;
         cout
             << "tc=" << getCollisionTime()
             << ", eps=" << getRestitutionCoefficient()
             << ", vmax=" << getMaximumVelocity()
             << ", InflowHeight/zmax=" << getInflowHeight()/getZMax()
             << endl << endl;
         //~ timer.set(t,tmax);
         //optimize number of buckets
         cout << "Nmax" << particleHandler.getStorageCapacity() << endl;
         set_HGRID_num_buckets_to_power(particleHandler.getNumberOfObjects()*1.5);
     }
References helpers::getMaximumVelocity(), and i.
setupInitialConditions() [5/5]
void SilbertPeriodic::setupInitialConditions () inline override virtual
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
A virtual function with no implementation but can be overridden.
Todo:
I (Anthony) wants to change this to be an external function. This has a lot of advantages especially when using copy-constructors. This is a major change and will break other codes, so therefore has to be done carefully.
This sets up the particles initial conditions it is as you expect the user to override this. By default the particles are randomly distributed
todo{I(Dinant) had to clear the WallHandler to prevent it from inserting the same wall twice, why?}
Reimplemented from DPMBase.
     {
         //fix_hgrid();
         particleHandler.setStorageCapacity(particleHandler.getNumberOfObjects()+getChuteLength()*getChuteWidth()*getZMax());//why is this line needed?
         createBottom();
         //~ write(std::cout,false);
         //cout << "correct fixed" << endl;
         if (speciesHandler.getNumberOfObjects()>1) {
             for (unsigned int i=0; i<particleHandler.getNumberOfObjects(); i++)
                 if (particleHandler.getObject(i)->isFixed())
                     particleHandler.getObject(i)->setSpecies(speciesHandler.getObject(1));
         }
         wallHandler.clear();
         InfiniteWall w0;
         w0.setSpecies(speciesHandler.getObject(0));
         if (getFixedParticleRadius()) {
             w0.set(Vec3D(0,0,-1), Vec3D(0,0,-3.4* getMaxInflowParticleRadius()));
         } else {
             w0.set(Vec3D(0,0,-1), Vec3D(0,0,0));
         }
         wallHandler.copyAndAddObject(w0);
         PeriodicBoundary b0;
         b0.set(Vec3D(1.0, 0.0, 0.0), getXMin(), getXMax());
         boundaryHandler.copyAndAddObject(b0);
         b0.set(Vec3D(0.0, 1.0, 0.0), getYMin(), getYMax());
         boundaryHandler.copyAndAddObject(b0);
         add_flow_particles();
         logger(INFO, "\nStatus before solve:");
 //      std::cout
 //          << "tc=" << getCollisionTime()
 //          << ", eps=" << getRestitutionCoefficient()
 //          << ", vmax=" << getInflowParticle()->calculateMaximumVelocity(getSpecies())
 //          << ", inflowHeight/zMax=" << getInflowHeight()/getZMax()
 //          << std::endl << std::endl;
         //~ timer.set(t,tmax);
         //optimize number of buckets
         logger(INFO, "Nmax %", particleHandler.getStorageCapacity());
         //setHGridNumberOfBucketsToPower(particleHandler.getNumberOfObjects()*1.5);
     }
References add_flow_particles(), DPMBase::boundaryHandler, BaseHandler< T >::clear(), BaseHandler< T >::copyAndAddObject(), Chute::createBottom(), Chute::getChuteLength(), Chute::getChuteWidth(), Chute::getFixedParticleRadius(), Chute::getMaxInflowParticleRadius(), BaseHandler< T >::getNumberOfObjects(), ParticleHandler::getNumberOfObjects(), BaseHandler< T >::getObject(), BaseHandler< T >::getStorageCapacity(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), DPMBase::getZMax(), i, INFO, BaseParticle::isFixed(), logger, DPMBase::particleHandler, PeriodicBoundary::set(), InfiniteWall::set(), BaseParticle::setSpecies(), BaseWall::setSpecies(), BaseHandler< T >::setStorageCapacity(), DPMBase::speciesHandler, and DPMBase::wallHandler.
Member Data Documentation
baseSpecies [1/2]
LinearViscoelasticFrictionMixedSpecies * SilbertPeriodic::baseSpecies
Referenced by createBaseSpecies(), getSlidingFrictionCoefficientBottom(), setSlidingFrictionCoefficientBottom(), and SilbertPeriodic().
baseSpecies [2/2]
LinearViscoelasticFrictionMixedSpecies* SilbertPeriodic::baseSpecies
inflowParticle_
SphericalParticle SilbertPeriodic::inflowParticle_
Referenced by add_flow_particles(), FlowRule::create_inflow_particle(), create_inflow_particle(), and SilbertPeriodic().
nCreated_
int SilbertPeriodic::nCreated_
Referenced by getNCreated(), increaseNCreated(), and SilbertPeriodic().
randomiseSpecies
bool SilbertPeriodic::randomiseSpecies
Referenced by create_inflow_particle(), set_study(), and SilbertPeriodic().
species [1/2]
LinearViscoelasticFrictionSpecies * SilbertPeriodic::species
Referenced by createBaseSpecies(), getSlidingFrictionCoefficientBottom(), readNextArgument(), set_study(), and SilbertPeriodic().
species [2/2]
LinearViscoelasticFrictionSpecies* SilbertPeriodic::species
The documentation for this class was generated from the following files:
flowRuleDiego_HeightAngle.cpp
GlasPeriodic.h
SilbertPeriodic.h