MercuryDPM: Eigen::internal::scalar_inner_product_op< Scalar, Scalar, Conj > Struct Template Reference
Eigen::internal::scalar_inner_product_op< Scalar, Scalar, Conj > Struct Template Reference
#include <InnerProduct.h>
Public Types
using result_type = Scalar
using conj_helper = conditional_conj< Scalar, Conj >
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar coeff (const Scalar &a, const Scalar &b) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar coeff (const Scalar &accum, const Scalar &a, const Scalar &b) const
template<typename Packet >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet packet (const Packet &a, const Packet &b) const
template<typename Packet >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet packet (const Packet &accum, const Packet &a, const Packet &b) const
Static Public Attributes
static constexpr bool PacketAccess = packet_traits<Scalar>::HasMul && packet_traits<Scalar>::HasAdd
Member Typedef Documentation
conj_helper
template<typename Scalar , bool Conj> using Eigen::internal::scalar_inner_product_op< Scalar, Scalar, Conj >::conj_helper = conditional_conj<Scalar, Conj>
result_type
template<typename Scalar , bool Conj> using Eigen::internal::scalar_inner_product_op< Scalar, Scalar, Conj >::result_type = Scalar
Member Function Documentation
coeff() [1/2]
template<typename Scalar , bool Conj> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar Eigen::internal::scalar_inner_product_op< Scalar, Scalar, Conj >::coeff (const Scalar & a, const Scalar & b) const inline
{
     return pmul(conj_helper::coeff(a), b);
   }
References a, b, and Eigen::internal::pmul().
coeff() [2/2]
template<typename Scalar , bool Conj> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar Eigen::internal::scalar_inner_product_op< Scalar, Scalar, Conj >::coeff (const Scalar & accum, const Scalar & a, const Scalar & b) const inline
{
     return pmadd(conj_helper::coeff(a), b, accum);
   }
References a, b, and Eigen::internal::pmadd().
packet() [1/2]
template<typename Scalar , bool Conj> template<typename Packet > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::scalar_inner_product_op< Scalar, Scalar, Conj >::packet (const Packet & a, const Packet & b) const inline
{
     return pmul(conj_helper::packet(a), b);
   }
References a, b, and Eigen::internal::pmul().
packet() [2/2]
template<typename Scalar , bool Conj> template<typename Packet > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::scalar_inner_product_op< Scalar, Scalar, Conj >::packet (const Packet & accum, const Packet & a, const Packet & b) const inline
{
     return pmadd(conj_helper::packet(a), b, accum);
   }
References a, b, and Eigen::internal::pmadd().
Member Data Documentation
PacketAccess
template<typename Scalar , bool Conj> constexpr bool Eigen::internal::scalar_inner_product_op< Scalar, Scalar, Conj >::PacketAccess = packet_traits<Scalar>::HasMul && packet_traits<Scalar>::HasAdd static constexpr
The documentation for this struct was generated from the following file:
InnerProduct.h