MercuryDPM: oomph::JacksHelloWorld Class Reference
oomph::JacksHelloWorld Class Reference
Hello world class – uses object from generic library.
#include <hello_world.h>
Public Member Functions
JacksHelloWorld ()
Constructor.
void say_it_inline ()
Say it inline.
void say_it_external ()
Say it externally.
Private Attributes
DenseMatrix< double > Some_matrix
Private full matrix.
Detailed Description
Hello world class – uses object from generic library.
Constructor & Destructor Documentation
JacksHelloWorld()
oomph::JacksHelloWorld::JacksHelloWorld () inline
Constructor.
   {
    // Fiddle around with the object's private data
    Some_matrix.resize(2);
   }
References oomph::DenseMatrix< T >::resize(), and Some_matrix.
Member Function Documentation
say_it_external()
void oomph::JacksHelloWorld::say_it_external ()
Say it externally.
   {
    oomph_info << "JacksHelloWorld object says: Hello world! "
              << Some_matrix.nrow() << " from a compiled function! "
              << std::endl;
   }
References oomph::DenseMatrix< T >::nrow(), oomph::oomph_info, and Some_matrix.
Referenced by main().
say_it_inline()
void oomph::JacksHelloWorld::say_it_inline () inline
Say it inline.
   {
    oomph_info << "JacksHelloWorld object says: Hello world! "
              << Some_matrix.nrow() << std::endl;
   }
References oomph::DenseMatrix< T >::nrow(), oomph::oomph_info, and Some_matrix.
Referenced by main().
Member Data Documentation
Some_matrix
DenseMatrix<double> oomph::JacksHelloWorld::Some_matrix private
Private full matrix.
Referenced by JacksHelloWorld(), say_it_external(), and say_it_inline().
The documentation for this class was generated from the following files:
hello_world.h
hello_world.cc