MercuryDPM: cxx11_tensor_map.cpp File Reference
cxx11_tensor_map.cpp File Reference
#include "main.h"
#include <Eigen/CXX11/Tensor>
Functions
static void test_0d ()
static void test_1d ()
static void test_2d ()
static void test_3d ()
static void test_from_tensor ()
static int f (const TensorMap< Tensor< int, 3 > > &tensor)
static void test_casting ()
template<typename T >
static const T & add_const (T &value)
static void test_0d_const_tensor ()
static void test_0d_const_tensor_map ()
EIGEN_DECLARE_TEST (cxx11_tensor_map)
Function Documentation
add_const()
template<typename T > static const T& add_const (T & value) static
{
   return value;
 }
References Eigen::value.
Referenced by test_0d_const_tensor().
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (cxx11_tensor_map)
{
   CALL_SUBTEST(test_0d());
   CALL_SUBTEST(test_1d());
   CALL_SUBTEST(test_2d());
   CALL_SUBTEST(test_3d());
   CALL_SUBTEST(test_from_tensor());
   CALL_SUBTEST(test_casting());
   CALL_SUBTEST(test_0d_const_tensor());
   CALL_SUBTEST(test_0d_const_tensor_map());
 }
References CALL_SUBTEST, test_0d(), test_0d_const_tensor(), test_0d_const_tensor_map(), test_1d(), test_2d(), test_3d(), test_casting(), and test_from_tensor().
f()
static int f (const TensorMap< Tensor< int, 3 > > & tensor) static
{
   //  Size<0> empty;
   EIGEN_STATIC_ASSERT((internal::array_size<Sizes<> >::value == 0), YOU_MADE_A_PROGRAMMING_MISTAKE);
   EIGEN_STATIC_ASSERT((internal::array_size<DSizes<int, 0> >::value == 0), YOU_MADE_A_PROGRAMMING_MISTAKE);
   Tensor<int, 0> result = tensor.sum();
   return result();
 }
References EIGEN_STATIC_ASSERT, and Eigen::value.
Referenced by ChangingTOIParticle::actionsAfterTimeStep(), MercuryProblem::actionsAfterTimeStep(), VolumeCoupling::actionsAfterTimeStep(), HeatFluidCoupledSpecies< NormalForceSpecies >::actionsAfterTimeStep(), oomph::DGElement::add_flux_contributions_to_residuals(), SSPorousChannelEquations::add_generic_residual_contribution(), Membrane::adjustVertexParticleSize(), adolc_forward_jacobian(), bench(), CRBond_Bessel::bessikna(), CRBond_Bessel::bessiknb(), CRBond_Bessel::bessikv(), CRBond_Bessel::bessjyna(), CRBond_Bessel::bessjynb(), CRBond_Bessel::bessjyv(), oomph::GmshTetMesh< ELEMENT >::build_from_scaffold(), oomph::CubicTetMeshFacetedSurface::build_it(), oomph::GmshTetMesh< ELEMENT >::build_it(), oomph::TetgenMesh< ELEMENT >::build_tetgenio(), Membrane::buildMesh(), pcast_array< SrcPacket, TgtPacket, 8, 1 >::cast(), DarcyProblem< ELEMENT >::complete_problem_setup(), Eigen::RealQZ< MatrixType_ >::compute(), SCoupling< M, O >::computeSCouplingForcesFromTriangles(), Eigen::StlThreadEnvironment::CreateTask(), Eigen::StlThreadEnvironment::CreateThread(), cwise_ref(), CylinderAndInterfaceDomain::CylinderAndInterfaceDomain(), oomph::Domain::d2macro_element_boundary(), oomph::TopologicallyRectangularDomain::d2macro_element_boundary(), tetgenio::deinitialize(), SSPorousChannelEquations::df_dt(), Eigen::BDCSVD< MatrixType_, Options_ >::divide(), oomph::Domain::dmacro_element_boundary(), oomph::TopologicallyRectangularDomain::dmacro_element_boundary(), DarcyProblem< ELEMENT >::doc_shape_functions(), EIGEN_DECLARE_TEST(), File::File(), oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_residuals_beam(), oomph::KirchhoffLoveShellEquations::fill_in_contribution_to_residuals_shell(), oomph::DarcyEquations< DIM >::fill_in_generic_residual_contribution(), Eigen::RealQZ< MatrixType_ >::findSmallDiagEntry(), Eigen::half_impl::float_to_half_rtne(), ProblemParameters::Fluid_body_force(), oomph::EulerEquations< DIM >::flux(), oomph::ScalarAdvectionEquations< DIM >::flux(), Eigen::ThreadLocal< T, Initialize, Release >::ForEach(), forward_jacobian(), forward_jacobian_cpp11(), gemv_complex_col(), oomph::Problem::get_dvaluesdt(), RachelsAdvectionDiffusion::get_exact_u(), TwoNodePoissonElement::get_residuals(), NurbsSurface::getDistance(), Membrane::getVolume(), Eigen::internal::idrs(), tetgenio::init(), Membrane::initializeEdgeBendingQuantities(), SSPorousChannelEquations::interpolated_f(), TwoDDGProblem< ELEMENT >::limit(), oomph::FullCircleDomain::lin_interpolate(), oomph::TubeDomain::lin_interpolate(), oomph::CylinderWithFlagDomain::linear_interpolate(), oomph::RectangleWithHoleAndAnnularRegionDomain::linear_interpolate(), CylinderAndInterfaceDomain::linear_interpolate(), RectangleWithHoleDomain::linear_interpolate(), oomph::HalfRectangleWithHoleDomain::linear_interpolate(), oomph::RectangleWithHoleDomain::linear_interpolate(), oomph::RectangleWithHoleAndAnnularRegionDomain::macro_element_boundary(), oomph::Domain::macro_element_boundary(), oomph::WarpedCubeDomain::macro_element_boundary(), oomph::AnnularDomain::macro_element_boundary(), oomph::FullCircleDomain::macro_element_boundary(), oomph::QuarterCircleSectorDomain::macro_element_boundary(), oomph::QuarterPipeDomain::macro_element_boundary(), oomph::QuarterTubeDomain::macro_element_boundary(), oomph::TopologicallyRectangularDomain::macro_element_boundary(), oomph::TubeDomain::macro_element_boundary(), oomph::EighthSphereDomain::macro_element_boundary(), RectangleWithHoleDomain::macro_element_boundary(), oomph::HalfRectangleWithHoleDomain::macro_element_boundary(), CylinderAndInterfaceDomain::macro_element_boundary(), oomph::CylinderWithFlagDomain::macro_element_boundary(), oomph::RectangleWithHoleDomain::macro_element_boundary(), main_gemm(), main_gemv(), ProblemParameters::Mass_source(), Eigen::MatrixBase< Derived >::matrixFunction(), CRBond_Bessel::msta1(), CRBond_Bessel::msta2(), Eigen::type2indexpair< f, s >::operator IndexPair< Index >(), Eigen::internal::operator*(), oomph::OomphInfo::operator<<(), oomph::QMacroElement< 2 >::output(), oomph::QMacroElement< 3 >::output(), oomph::DGElement::output_faces(), oomph::QMacroElement< 2 >::output_macro_element_boundaries(), oomph::QMacroElement< 3 >::output_macro_element_boundaries(), Eigen::CoreThreadPoolDevice::parallelFor(), Eigen::CoreThreadPoolDevice::parallelForImpl(), Eigen::internal::pcast(), Eigen::internal::pcast< Packet2d, Packet16c >(), Eigen::internal::pcast< Packet2d, Packet16uc >(), Eigen::internal::pcast< Packet2l, Packet16c >(), Eigen::internal::pcast< Packet2l, Packet16uc >(), Eigen::internal::pcast< Packet2ul, Packet16c >(), Eigen::internal::pcast< Packet2ul, Packet16uc >(), Eigen::internal::pdiv_float_common(), Eigen::internal::pload1< Packet4f >(), Eigen::internal::ploaddup< Packet16bf >(), Eigen::internal::ploaddup< Packet16h >(), GlobalFct::plot_it(), LiquidMigrationMPI2Test::printTime(), Eigen::internal::ptranspose(), Eigen::RealQZ< MatrixType_ >::pushDownZero(), oomph::WarpedCubeDomain::r_B(), oomph::QuarterPipeDomain::r_B(), oomph::QuarterTubeDomain::r_bot_right_B(), oomph::QuarterTubeDomain::r_bot_right_D(), oomph::QuarterCircleSectorDomain::r_bot_right_E(), oomph::QuarterTubeDomain::r_bot_right_F(), oomph::QuarterTubeDomain::r_bot_right_L(), oomph::QuarterCircleSectorDomain::r_bot_right_N(), oomph::QuarterTubeDomain::r_bot_right_R(), oomph::QuarterCircleSectorDomain::r_bot_right_S(), oomph::QuarterTubeDomain::r_bot_right_U(), oomph::QuarterCircleSectorDomain::r_bot_right_W(), oomph::QuarterTubeDomain::r_centr_B(), oomph::EighthSphereDomain::r_centr_B(), oomph::QuarterTubeDomain::r_centr_D(), oomph::EighthSphereDomain::r_centr_D(), oomph::QuarterCircleSectorDomain::r_centr_E(), oomph::QuarterTubeDomain::r_centr_F(), oomph::EighthSphereDomain::r_centr_F(), oomph::QuarterTubeDomain::r_centr_L(), oomph::EighthSphereDomain::r_centr_L(), oomph::QuarterCircleSectorDomain::r_centr_N(), oomph::QuarterTubeDomain::r_centr_R(), oomph::EighthSphereDomain::r_centr_R(), oomph::QuarterCircleSectorDomain::r_centr_S(), oomph::QuarterTubeDomain::r_centr_U(), oomph::EighthSphereDomain::r_centr_U(), oomph::QuarterCircleSectorDomain::r_centr_W(), oomph::WarpedCubeDomain::r_D(), oomph::QuarterPipeDomain::r_D(), oomph::TopologicallyRectangularDomain::r_E(), oomph::WarpedCubeDomain::r_F(), oomph::QuarterPipeDomain::r_F(), oomph::EighthSphereDomain::r_front_B(), oomph::EighthSphereDomain::r_front_D(), oomph::EighthSphereDomain::r_front_F(), oomph::EighthSphereDomain::r_front_L(), oomph::EighthSphereDomain::r_front_R(), oomph::EighthSphereDomain::r_front_U(), oomph::WarpedCubeDomain::r_L(), oomph::QuarterPipeDomain::r_L(), oomph::FishDomain::r_lower_body_E(), oomph::FishDomain::r_lower_body_N(), oomph::FishDomain::r_lower_body_S(), oomph::FishDomain::r_lower_body_W(), oomph::FishDomain::r_lower_fin_E(), oomph::FishDomain::r_lower_fin_N(), oomph::FishDomain::r_lower_fin_S(), oomph::FishDomain::r_lower_fin_W(), oomph::TopologicallyRectangularDomain::r_N(), oomph::WarpedCubeDomain::r_R(), oomph::QuarterPipeDomain::r_R(), oomph::EighthSphereDomain::r_right_B(), oomph::EighthSphereDomain::r_right_D(), oomph::EighthSphereDomain::r_right_F(), oomph::EighthSphereDomain::r_right_L(), oomph::EighthSphereDomain::r_right_R(), oomph::EighthSphereDomain::r_right_U(), oomph::TopologicallyRectangularDomain::r_S(), oomph::QuarterTubeDomain::r_top_left_B(), oomph::QuarterTubeDomain::r_top_left_D(), oomph::QuarterCircleSectorDomain::r_top_left_E(), oomph::QuarterTubeDomain::r_top_left_F(), oomph::QuarterTubeDomain::r_top_left_L(), oomph::QuarterCircleSectorDomain::r_top_left_N(), oomph::QuarterTubeDomain::r_top_left_R(), oomph::QuarterCircleSectorDomain::r_top_left_S(), oomph::QuarterTubeDomain::r_top_left_U(), oomph::QuarterCircleSectorDomain::r_top_left_W(), oomph::WarpedCubeDomain::r_U(), oomph::QuarterPipeDomain::r_U(), oomph::EighthSphereDomain::r_up_B(), oomph::EighthSphereDomain::r_up_D(), oomph::EighthSphereDomain::r_up_F(), oomph::EighthSphereDomain::r_up_L(), oomph::EighthSphereDomain::r_up_R(), oomph::EighthSphereDomain::r_up_U(), oomph::TopologicallyRectangularDomain::r_W(), Membrane::read(), TriangulatedWall::readVTK(), oomph::RefineableQuadMeshWithMovingCylinder< MyRefineableQTaylorHoodElement >::RefineableQuadMeshWithMovingCylinder(), oomph::AugmentedBlockFoldLinearSolver::resolve(), oomph::AugmentedBlockPitchForkLinearSolver::resolve(), Quaternion::rotateInverseInertiaTensor(), Eigen::internal::redux_vec_unroller< Func, Evaluator, Start, 0 >::run(), Eigen::internal::LU_kernel_bmod< 1 >::run(), Membrane::saveAsOFF(), Eigen::seq(), Eigen::type2indexpair< f, s >::set(), TriangulatedWall::set(), AxiPoroProblem< ELEMENT, TIMESTEPPER >::set_boundary_values(), my_problem::set_Frequency(), Camera::setFrame(), Binary::setFrequency(), oomph::DGElement::setup_face_neighbour_info(), oomph::TetMeshFacetedSurface::setup_facet_connectivity_for_tetgen(), oomph::TetgenMesh< ELEMENT >::setup_reverse_lookup_schemes_for_faceted_surface(), RotatingDrum::setVibrationFrequency(), oomph::TetMeshBase::snap_nodes_onto_geometric_objects(), oomph::AugmentedBlockFoldLinearSolver::solve(), oomph::AugmentedBlockPitchForkLinearSolver::solve(), oomph::CG< MATRIX >::solve(), oomph::BiCGStab< MATRIX >::solve(), oomph::GS< MATRIX >::solve(), oomph::GS< CRDoubleMatrix >::solve(), oomph::DampedJacobi< MATRIX >::solve(), oomph::GMRES< MATRIX >::solve(), oomph::AugmentedProblemGMRES::solve(), oomph::HelmholtzGMRESMG< MATRIX >::solve(), oomph::HelmholtzFGMRESMG< MATRIX >::solve(), TestProblem::source(), SphericalTetMeshFacetedSurface::SphericalTetMeshFacetedSurface(), Eigen::RealQZ< MatrixType_ >::step(), WearableTriangulatedWall::storeDebris(), BiharmonicTestFunctions1::surface_load(), BiharmonicTestFunctions2::surface_load(), test_casting(), oomph::TetMeshFacetedClosedSurfaceForRemesh::TetMeshFacetedClosedSurfaceForRemesh(), TriangulatedWall::TriangulatedWall(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::unpin_all(), oomph::RefineableTetgenMesh< ELEMENT >::update_faceted_surface_using_face_mesh(), SCoupling< M, O >::updateTriangleWall(), oomph::TetMeshFacetedSurface::vertex_index_in_tetgen(), oomph::WarpedCubeDomain::warp_it(), WallVTKWriter::write(), Membrane::write(), oomph::GmshTetScaffoldMesh::write_geo_file(), SingleParticle< SpeciesType >::writeEneTimeStep(), ParticleVtkWriter::writeExtraFields(), TriangulatedWall::writeVTK(), InteractionVTKWriter::writeVTKPointData(), and oomph::TetMeshFacetedClosedSurfaceForRemesh::~TetMeshFacetedClosedSurfaceForRemesh().
test_0d()
static void test_0d () static
                       {
   Tensor<int, 0> scalar1;
   Tensor<int, 0, RowMajor> scalar2;
   TensorMap<const Tensor<int, 0> > scalar3(scalar1.data());
   TensorMap<const Tensor<int, 0, RowMajor> > scalar4(scalar2.data());
   scalar1() = 7;
   scalar2() = 13;
   VERIFY_IS_EQUAL(scalar1.rank(), 0);
   VERIFY_IS_EQUAL(scalar1.size(), 1);
   VERIFY_IS_EQUAL(scalar3(), 7);
   VERIFY_IS_EQUAL(scalar4(), 13);
 }
References Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::data(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::rank(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::size(), and VERIFY_IS_EQUAL.
Referenced by EIGEN_DECLARE_TEST().
test_0d_const_tensor()
static void test_0d_const_tensor () static
{
   Tensor<int, 0> scalar1;
   Tensor<int, 0, RowMajor> scalar2;
   TensorMap<const Tensor<int, 0> > scalar3(add_const(scalar1).data());
   TensorMap<const Tensor<int, 0, RowMajor> > scalar4(add_const(scalar2).data());
   scalar1() = 7;
   scalar2() = 13;
   VERIFY_IS_EQUAL(scalar1.rank(), 0);
   VERIFY_IS_EQUAL(scalar1.size(), 1);
   VERIFY_IS_EQUAL(scalar3(), 7);
   VERIFY_IS_EQUAL(scalar4(), 13);
 }
References add_const(), data, Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::rank(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::size(), and VERIFY_IS_EQUAL.
Referenced by EIGEN_DECLARE_TEST().
test_0d_const_tensor_map()
static void test_0d_const_tensor_map () static
{
   Tensor<int, 0> scalar1;
   Tensor<int, 0, RowMajor> scalar2;
   const TensorMap<Tensor<int, 0> > scalar3(scalar1.data());
   const TensorMap<Tensor<int, 0, RowMajor> > scalar4(scalar2.data());
   // Although TensorMap is constant, we still can write to the underlying
   // storage, because we map over non-constant Tensor.
   scalar3() = 7;
   scalar4() = 13;
   VERIFY_IS_EQUAL(scalar1(), 7);
   VERIFY_IS_EQUAL(scalar2(), 13);
   // Pointer to the underlying storage is also non-const.
   scalar3.data()[0] = 8;
   scalar4.data()[0] = 14;
   VERIFY_IS_EQUAL(scalar1(), 8);
   VERIFY_IS_EQUAL(scalar2(), 14);
 }
References Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::data(), Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::data(), and VERIFY_IS_EQUAL.
Referenced by EIGEN_DECLARE_TEST().
test_1d()
static void test_1d () static
                       {
   Tensor<int, 1> vec1(6);
   Tensor<int, 1, RowMajor> vec2(6);
   TensorMap<const Tensor<int, 1> > vec3(vec1.data(), 6);
   TensorMap<const Tensor<int, 1, RowMajor> > vec4(vec2.data(), 6);
   vec1(0) = 4;
   vec2(0) = 0;
   vec1(1) = 8;
   vec2(1) = 1;
   vec1(2) = 15;
   vec2(2) = 2;
   vec1(3) = 16;
   vec2(3) = 3;
   vec1(4) = 23;
   vec2(4) = 4;
   vec1(5) = 42;
   vec2(5) = 5;
   VERIFY_IS_EQUAL(vec1.rank(), 1);
   VERIFY_IS_EQUAL(vec1.size(), 6);
   VERIFY_IS_EQUAL(vec1.dimension(0), 6);
   VERIFY_IS_EQUAL(vec3(0), 4);
   VERIFY_IS_EQUAL(vec3(1), 8);
   VERIFY_IS_EQUAL(vec3(2), 15);
   VERIFY_IS_EQUAL(vec3(3), 16);
   VERIFY_IS_EQUAL(vec3(4), 23);
   VERIFY_IS_EQUAL(vec3(5), 42);
   VERIFY_IS_EQUAL(vec4(0), 0);
   VERIFY_IS_EQUAL(vec4(1), 1);
   VERIFY_IS_EQUAL(vec4(2), 2);
   VERIFY_IS_EQUAL(vec4(3), 3);
   VERIFY_IS_EQUAL(vec4(4), 4);
   VERIFY_IS_EQUAL(vec4(5), 5);
 }
References Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::data(), vec1(), and VERIFY_IS_EQUAL.
Referenced by EIGEN_DECLARE_TEST().
test_2d()
static void test_2d () static
                       {
   Tensor<int, 2> mat1(2, 3);
   Tensor<int, 2, RowMajor> mat2(2, 3);
   mat1(0, 0) = 0;
   mat1(0, 1) = 1;
   mat1(0, 2) = 2;
   mat1(1, 0) = 3;
   mat1(1, 1) = 4;
   mat1(1, 2) = 5;
   mat2(0, 0) = 0;
   mat2(0, 1) = 1;
   mat2(0, 2) = 2;
   mat2(1, 0) = 3;
   mat2(1, 1) = 4;
   mat2(1, 2) = 5;
   TensorMap<const Tensor<int, 2> > mat3(mat1.data(), 2, 3);
   TensorMap<const Tensor<int, 2, RowMajor> > mat4(mat2.data(), 2, 3);
   VERIFY_IS_EQUAL(mat3.rank(), 2);
   VERIFY_IS_EQUAL(mat3.size(), 6);
   VERIFY_IS_EQUAL(mat3.dimension(0), 2);
   VERIFY_IS_EQUAL(mat3.dimension(1), 3);
   VERIFY_IS_EQUAL(mat4.rank(), 2);
   VERIFY_IS_EQUAL(mat4.size(), 6);
   VERIFY_IS_EQUAL(mat4.dimension(0), 2);
   VERIFY_IS_EQUAL(mat4.dimension(1), 3);
   VERIFY_IS_EQUAL(mat3(0, 0), 0);
   VERIFY_IS_EQUAL(mat3(0, 1), 1);
   VERIFY_IS_EQUAL(mat3(0, 2), 2);
   VERIFY_IS_EQUAL(mat3(1, 0), 3);
   VERIFY_IS_EQUAL(mat3(1, 1), 4);
   VERIFY_IS_EQUAL(mat3(1, 2), 5);
   VERIFY_IS_EQUAL(mat4(0, 0), 0);
   VERIFY_IS_EQUAL(mat4(0, 1), 1);
   VERIFY_IS_EQUAL(mat4(0, 2), 2);
   VERIFY_IS_EQUAL(mat4(1, 0), 3);
   VERIFY_IS_EQUAL(mat4(1, 1), 4);
   VERIFY_IS_EQUAL(mat4(1, 2), 5);
 }
References Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::data(), Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::dimension(), mat1(), Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::rank(), Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::size(), and VERIFY_IS_EQUAL.
Referenced by EIGEN_DECLARE_TEST().
test_3d()
static void test_3d () static
                       {
   Tensor<int, 3> mat1(2, 3, 7);
   Tensor<int, 3, RowMajor> mat2(2, 3, 7);
   int val = 0;
   for (int i = 0; i < 2; ++i) {
     for (int j = 0; j < 3; ++j) {
       for (int k = 0; k < 7; ++k) {
         mat1(i, j, k) = val;
         mat2(i, j, k) = val;
         val++;
       }
     }
   }
   TensorMap<const Tensor<int, 3> > mat3(mat1.data(), 2, 3, 7);
   TensorMap<const Tensor<int, 3, RowMajor> > mat4(mat2.data(), 2, 3, 7);
   VERIFY_IS_EQUAL(mat3.rank(), 3);
   VERIFY_IS_EQUAL(mat3.size(), 2 * 3 * 7);
   VERIFY_IS_EQUAL(mat3.dimension(0), 2);
   VERIFY_IS_EQUAL(mat3.dimension(1), 3);
   VERIFY_IS_EQUAL(mat3.dimension(2), 7);
   VERIFY_IS_EQUAL(mat4.rank(), 3);
   VERIFY_IS_EQUAL(mat4.size(), 2 * 3 * 7);
   VERIFY_IS_EQUAL(mat4.dimension(0), 2);
   VERIFY_IS_EQUAL(mat4.dimension(1), 3);
   VERIFY_IS_EQUAL(mat4.dimension(2), 7);
   val = 0;
   for (int i = 0; i < 2; ++i) {
     for (int j = 0; j < 3; ++j) {
       for (int k = 0; k < 7; ++k) {
         VERIFY_IS_EQUAL(mat3(i, j, k), val);
         VERIFY_IS_EQUAL(mat4(i, j, k), val);
         val++;
       }
     }
   }
 }
References Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::data(), Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::dimension(), i, j, k, mat1(), Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::rank(), Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::size(), calibrate::val, and VERIFY_IS_EQUAL.
Referenced by EIGEN_DECLARE_TEST().
test_casting()
static void test_casting () static
{
   Tensor<int, 3> tensor(2, 3, 7);
   int val = 0;
   for (int i = 0; i < 2; ++i) {
     for (int j = 0; j < 3; ++j) {
       for (int k = 0; k < 7; ++k) {
         tensor(i, j, k) = val;
         val++;
       }
     }
   }
   TensorMap<Tensor<int, 3> > map(tensor);
   int sum1 = f(map);
   int sum2 = f(tensor);
   VERIFY_IS_EQUAL(sum1, sum2);
   VERIFY_IS_EQUAL(sum1, 861);
 }
References f(), i, j, k, calibrate::val, and VERIFY_IS_EQUAL.
Referenced by EIGEN_DECLARE_TEST().
test_from_tensor()
static void test_from_tensor () static
{
   Tensor<int, 3> mat1(2, 3, 7);
   Tensor<int, 3, RowMajor> mat2(2, 3, 7);
   int val = 0;
   for (int i = 0; i < 2; ++i) {
     for (int j = 0; j < 3; ++j) {
       for (int k = 0; k < 7; ++k) {
         mat1(i, j, k) = val;
         mat2(i, j, k) = val;
         val++;
       }
     }
   }
   TensorMap<Tensor<int, 3> > mat3(mat1);
   TensorMap<Tensor<int, 3, RowMajor> > mat4(mat2);
   VERIFY_IS_EQUAL(mat3.rank(), 3);
   VERIFY_IS_EQUAL(mat3.size(), 2 * 3 * 7);
   VERIFY_IS_EQUAL(mat3.dimension(0), 2);
   VERIFY_IS_EQUAL(mat3.dimension(1), 3);
   VERIFY_IS_EQUAL(mat3.dimension(2), 7);
   VERIFY_IS_EQUAL(mat4.rank(), 3);
   VERIFY_IS_EQUAL(mat4.size(), 2 * 3 * 7);
   VERIFY_IS_EQUAL(mat4.dimension(0), 2);
   VERIFY_IS_EQUAL(mat4.dimension(1), 3);
   VERIFY_IS_EQUAL(mat4.dimension(2), 7);
   val = 0;
   for (int i = 0; i < 2; ++i) {
     for (int j = 0; j < 3; ++j) {
       for (int k = 0; k < 7; ++k) {
         VERIFY_IS_EQUAL(mat3(i, j, k), val);
         VERIFY_IS_EQUAL(mat4(i, j, k), val);
         val++;
       }
     }
   }
   TensorFixedSize<int, Sizes<2, 3, 7> > mat5;
   val = 0;
   for (int i = 0; i < 2; ++i) {
     for (int j = 0; j < 3; ++j) {
       for (int k = 0; k < 7; ++k) {
         array<ptrdiff_t, 3> coords;
         coords[0] = i;
         coords[1] = j;
         coords[2] = k;
         mat5(coords) = val;
         val++;
       }
     }
   }
   TensorMap<TensorFixedSize<int, Sizes<2, 3, 7> > > mat6(mat5);
   VERIFY_IS_EQUAL(mat6.rank(), 3);
   VERIFY_IS_EQUAL(mat6.size(), 2 * 3 * 7);
   VERIFY_IS_EQUAL(mat6.dimension(0), 2);
   VERIFY_IS_EQUAL(mat6.dimension(1), 3);
   VERIFY_IS_EQUAL(mat6.dimension(2), 7);
   val = 0;
   for (int i = 0; i < 2; ++i) {
     for (int j = 0; j < 3; ++j) {
       for (int k = 0; k < 7; ++k) {
         VERIFY_IS_EQUAL(mat6(i, j, k), val);
         val++;
       }
     }
   }
 }
References Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::dimension(), i, j, k, mat1(), Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::rank(), Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::size(), calibrate::val, and VERIFY_IS_EQUAL.
Referenced by EIGEN_DECLARE_TEST().