MercuryDPM: Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, DirectAccess > Class Template Reference
Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, DirectAccess > Class Template Reference
#include <IndexedView.h>
Public Types
typedef internal::generic_xpr_base< IndexedView< XprType, RowIndices, ColIndices > >::type Base
typedef internal::ref_selector< XprType >::non_const_type MatrixTypeNested
typedef internal::remove_all_t< XprType > NestedExpression
typedef XprType::Scalar Scalar
Public Member Functions
template<typename T0 , typename T1 >
IndexedViewImpl (XprType &xpr, const T0 &rowIndices, const T1 &colIndices)
Index rows () const
Index cols () const
const internal::remove_all_t< XprType > & nestedExpression () const
std::remove_reference_t< XprType > & nestedExpression ()
const RowIndices & rowIndices () const
const ColIndices & colIndices () const
constexpr Scalar & coeffRef (Index rowId, Index colId)
constexpr const Scalar & coeffRef (Index rowId, Index colId) const
Protected Attributes
MatrixTypeNested m_xpr
RowIndices m_rowIndices
ColIndices m_colIndices
Member Typedef Documentation
Base
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind , bool DirectAccess> typedef internal::generic_xpr_base<IndexedView<XprType, RowIndices, ColIndices> >::type Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, DirectAccess >::Base
MatrixTypeNested
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind , bool DirectAccess> typedef internal::ref_selector<XprType>::non_const_type Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, DirectAccess >::MatrixTypeNested
NestedExpression
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind , bool DirectAccess> typedef internal::remove_all_t<XprType> Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, DirectAccess >::NestedExpression
Scalar
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind , bool DirectAccess> typedef XprType::Scalar Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, DirectAccess >::Scalar
Constructor & Destructor Documentation
IndexedViewImpl()
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind , bool DirectAccess> template<typename T0 , typename T1 > Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, DirectAccess >::IndexedViewImpl (XprType & xpr, const T0 & rowIndices, const T1 & colIndices) inline
       : m_xpr(xpr), m_rowIndices(rowIndices), m_colIndices(colIndices) {}
Member Function Documentation
coeffRef() [1/2]
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind , bool DirectAccess> constexpr Scalar& Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, DirectAccess >::coeffRef (Index rowId, Index colId) inline constexpr
{
     return nestedExpression().coeffRef(m_rowIndices[rowId], m_colIndices[colId]);
   }
coeffRef() [2/2]
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind , bool DirectAccess> constexpr const Scalar& Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, DirectAccess >::coeffRef (Index rowId, Index colId) const inline constexpr
{
     return nestedExpression().coeffRef(m_rowIndices[rowId], m_colIndices[colId]);
   }
colIndices()
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind , bool DirectAccess> const ColIndices& Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, DirectAccess >::colIndices () const inline
Returns
a const reference to the object storing/generating the column indices
 { return m_colIndices; }
cols()
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind , bool DirectAccess> Index Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, DirectAccess >::cols () const inline
Returns
number of columns
 { return IndexedViewHelper<ColIndices>::size(m_colIndices); }
References Eigen::internal::IndexedViewHelper< Indices, EnableIf >::size().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
nestedExpression() [1/2]
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind , bool DirectAccess> std::remove_reference_t<XprType>& Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, DirectAccess >::nestedExpression () inline
Returns
the nested expression
 { return m_xpr; }
nestedExpression() [2/2]
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind , bool DirectAccess> const internal::remove_all_t<XprType>& Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, DirectAccess >::nestedExpression () const inline
Returns
the nested expression
 { return m_xpr; }
rowIndices()
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind , bool DirectAccess> const RowIndices& Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, DirectAccess >::rowIndices () const inline
Returns
a const reference to the object storing/generating the row indices
 { return m_rowIndices; }
rows()
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind , bool DirectAccess> Index Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, DirectAccess >::rows () const inline
Returns
number of rows
 { return IndexedViewHelper<RowIndices>::size(m_rowIndices); }
References Eigen::internal::IndexedViewHelper< Indices, EnableIf >::size().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_colIndices
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind , bool DirectAccess> ColIndices Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, DirectAccess >::m_colIndices protected
m_rowIndices
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind , bool DirectAccess> RowIndices Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, DirectAccess >::m_rowIndices protected
m_xpr
template<typename XprType , typename RowIndices , typename ColIndices , typename StorageKind , bool DirectAccess> MatrixTypeNested Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, DirectAccess >::m_xpr protected
The documentation for this class was generated from the following file:
IndexedView.h