MercuryDPM: GlobalPhysicalParameters Namespace Reference
GlobalPhysicalParameters Namespace Reference
Namespace for Womersley problem.
Functions
void get_boundary_values (const Vector< double > &x, Vector< double > &u)
Some "solution" for assignment of boundary values.
void source_function (const Vector< double > &x_vect, double &source)
Zero source function.
void wind_function (const Vector< double > &x, Vector< double > &wind)
Wind.
double prescribed_volume_flux (const double &time)
Prescribed volume flux – must be assigned to Prescribed_volume_flux.
double prescribed_pressure_gradient (const double &time)
Prescribed pressure gradient.
Variables
double Peclet =200.0
Peclet number.
double Alpha =50.0
Parameter for steepness of step in boundary values.
double TanPhi =1.0
Parameter for angle of step in boundary values: 45 degrees.
double Prescribed_volume_flux =0.0
Prescribed volume flux.
double Alpha_sq =10.0
Womersley number.
double L_impedance =7.0
Length of impedance tube.
Detailed Description
Namespace for Womersley problem.
Namespace for global parameters: Unforced problem with boundary values corresponding to a steep tanh step profile oriented at 45 degrees across the domain.
Function Documentation
get_boundary_values()
void GlobalPhysicalParameters::get_boundary_values (const Vector< double > & x, Vector< double > & u)
Some "solution" for assignment of boundary values.
  {
   u[0]=tanh(1.0-Alpha*(TanPhi*x[0]-x[1]));
  }
References Alpha, Eigen::bfloat16_impl::tanh(), TanPhi, and plotDoE::x.
Referenced by SUPGAdvectionDiffusionProblem< ELEMENT >::actions_before_newton_solve().
prescribed_pressure_gradient()
double GlobalPhysicalParameters::prescribed_pressure_gradient (const double & time)
Prescribed pressure gradient.
  {
   return 2.0*cos(2.0*MathematicalConstants::Pi*time);
  }
References cos(), and BiharmonicTestFunctions2::Pi.
Referenced by run_prescribed_pressure_gradient().
prescribed_volume_flux()
double GlobalPhysicalParameters::prescribed_volume_flux (const double & time)
Prescribed volume flux – must be assigned to Prescribed_volume_flux.
  {
   return 2.0*cos(2.0*MathematicalConstants::Pi*time);
  }
References cos(), and BiharmonicTestFunctions2::Pi.
Referenced by run_impedance_tube(), and run_prescribed_flux().
source_function()
void GlobalPhysicalParameters::source_function (const Vector< double > & x_vect, double & source)
Zero source function.
  {
   source=0.0;
  }
References TestProblem::source().
Referenced by main().
wind_function()
void GlobalPhysicalParameters::wind_function (const Vector< double > & x, Vector< double > & wind)
Wind.
  {
   wind[0]=sin(6.0*x[1]);
   wind[1]=cos(6.0*x[0]);
  }
References cos(), sin(), and plotDoE::x.
Referenced by main().
Variable Documentation
Alpha
double GlobalPhysicalParameters::Alpha =50.0
Parameter for steepness of step in boundary values.
Referenced by get_boundary_values().
Alpha_sq
double GlobalPhysicalParameters::Alpha_sq =10.0
Womersley number.
Referenced by run_impedance_tube(), run_navier_stokes_outflow(), run_prescribed_flux(), and run_prescribed_pressure_gradient().
L_impedance
double GlobalPhysicalParameters::L_impedance =7.0
Length of impedance tube.
Referenced by CollapsibleChannelProblem< ELEMENT >::CollapsibleChannelProblem(), run_impedance_tube(), run_navier_stokes_outflow(), CollapsibleChannelProblem< ELEMENT >::setup_outflow_impedance_elements(), and CollapsibleChannelProblem< ELEMENT >::unsteady_run().
Peclet
double GlobalPhysicalParameters::Peclet =200.0
Peclet number.
Referenced by SUPGAdvectionDiffusionProblem< ELEMENT >::SUPGAdvectionDiffusionProblem().
Prescribed_volume_flux
double GlobalPhysicalParameters::Prescribed_volume_flux =0.0
Prescribed volume flux.
Referenced by run_impedance_tube(), run_prescribed_flux(), CollapsibleChannelProblem< ELEMENT >::setup_outflow_flux_control_elements(), and CollapsibleChannelProblem< ELEMENT >::unsteady_run().
TanPhi
double GlobalPhysicalParameters::TanPhi =1.0
Parameter for angle of step in boundary values: 45 degrees.
Referenced by get_boundary_values().