MercuryDPM: oomph::QTaylorHoodSpaceTimeElement< DIM > Class Template Reference
oomph::QTaylorHoodSpaceTimeElement< DIM > Class Template Reference
#include <discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h>
Public Member Functions
QTaylorHoodSpaceTimeElement ()
Constructor, no internal data points.
virtual unsigned required_nvalue (const unsigned &n) const
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void ptest_nst (const Vector< double > &s, Shape &psi) const
Pressure test functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
virtual int p_nodal_index_nst () const
Set the value at which the pressure is stored in the nodes.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
double p_nst (const unsigned &n_p) const
double p_nst (const unsigned &t, const unsigned &n_p) const
unsigned npres_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)
void identify_load_data (std::set< std::pair< Data *, unsigned >> &paired_load_data)
void identify_pressure_data (std::set< std::pair< Data *, unsigned >> &paired_pressure_data)
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
unsigned ndof_types () const
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
QTaylorHoodSpaceTimeElement ()
Constructor, no internal data points.
~QTaylorHoodSpaceTimeElement ()
virtual unsigned required_nvalue (const unsigned &n) const
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void ptest_nst (const Vector< double > &s, Shape &psi) const
Pressure test functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
virtual int p_nodal_index_nst () const
Set the value at which the pressure is stored in the nodes.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
double p_nst (const unsigned &n_p) const
double p_nst (const unsigned &t, const unsigned &n_p) const
unsigned npres_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)
void identify_load_data (std::set< std::pair< Data *, unsigned >> &paired_load_data)
void identify_pressure_data (std::set< std::pair< Data *, unsigned >> &paired_pressure_data)
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
QTaylorHoodSpaceTimeElement ()
Constructor, no internal data points.
virtual unsigned required_nvalue (const unsigned &n) const
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
virtual int p_nodal_index_nst () const
Set the value at which the pressure is stored in the nodes.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
double p_nst (const unsigned &n_p) const
double p_nst (const unsigned &t, const unsigned &n_p) const
unsigned npres_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)
void identify_load_data (std::set< std::pair< Data *, unsigned >> &paired_load_data)
void identify_pressure_data (std::set< std::pair< Data *, unsigned >> &paired_pressure_data)
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void pshape_nst (const Vector< double > &s, Shape &psi) const
2D (in space): Pressure shape functions
void ptest_nst (const Vector< double > &s, Shape &test) const
2D (in space): Pressure shape functions
void pshape_nst (const Vector< double > &s, Shape &psi) const
2D (in space): Pressure shape functions
void ptest_nst (const Vector< double > &s, Shape &test) const
2D (in space): Pressure shape functions
void pshape_nst (const Vector< double > &s, Shape &psi) const
Public Member Functions inherited from oomph::SpaceTimeNavierStokesEquations< DIM >
SpaceTimeNavierStokesEquations ()
void store_strouhal_as_external_data (Data *strouhal_data_pt)
Function that tells us whether the period is stored as external data.
const double & re () const
Reynolds number.
double *& re_pt ()
Pointer to Reynolds number.
bool is_strouhal_stored_as_external_data () const
Are we storing the Strouhal number as external data?
const double & st () const
Strouhal parameter (const. version)
double * st_pt () const
Pointer to Strouhal parameter (const. version)
double *& st_pt ()
Pointer to Strouhal number (can only assign to private member data)
double re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
NavierStokesBodyForceFctPt & body_force_fct_pt ()
Access function for the body-force pointer.
NavierStokesBodyForceFctPt body_force_fct_pt () const
Access function for the body-force pointer. Const version.
NavierStokesSourceFctPt & source_fct_pt ()
Access function for the source-function pointer.
NavierStokesSourceFctPt source_fct_pt () const
Access function for the source-function pointer. Const version.
NavierStokesPressureAdvDiffSourceFctPt & source_fct_for_pressure_adv_diff ()
NavierStokesPressureAdvDiffSourceFctPt source_fct_for_pressure_adv_diff () const
int & pinned_fp_pressure_eqn ()
double u_nst (const unsigned &n, const unsigned &i) const
double u_nst (const unsigned &t, const unsigned &n, const unsigned &i) const
virtual unsigned u_index_nst (const unsigned &i) const
unsigned n_u_nst () const
double get_du_dt (const unsigned &n, const unsigned &i) const
double du_dt_nst (const unsigned &n, const unsigned &i) const
double interpolated_du_dt_nst (const Vector< double > &s, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
double pressure_integral () const
Integral of pressure over element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute the vorticity vector at local coordinate s.
void get_vorticity (const Vector< double > &s, double &vorticity) const
Compute the vorticity vector at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
double d_kin_energy_dt () const
Get integral of time derivative of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j+du_j/dx_i)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction_p, Vector< double > &traction_visc_n, Vector< double > &traction_visc_t)
void get_load (const Vector< double > &s, const Vector< double > &N, Vector< double > &load)
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
std::string scalar_name_paraview (const unsigned &i) const
void full_output (std::ostream &outfile)
void full_output (std::ostream &outfile, const unsigned &n_plot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void output_vorticity (std::ostream &outfile, const unsigned &nplot)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_norm (Vector< double > &norm)
Compute the vector norm of the FEM solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
void fill_in_pressure_advection_diffusion_residuals (Vector< double > &residuals)
void fill_in_pressure_advection_diffusion_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void pin_all_non_pressure_dofs (std::map< Data *, std::vector< int >> &eqn_number_backup)
Pin all non-pressure dofs and backup eqn numbers.
void output_pressure_advection_diffusion_robin_elements (std::ostream &outfile)
void delete_pressure_advection_diffusion_robin_elements ()
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
void interpolated_u_nst (const Vector< double > &s, Vector< double > &velocity) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void dinterpolated_u_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
virtual double interpolated_p_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_p_nst (const unsigned &t, const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s at time level t.
void point_output_data (const Vector< double > &s, Vector< double > &data)
SpaceTimeNavierStokesEquations ()
void store_strouhal_as_external_data (Data *strouhal_data_pt)
Function that tells us whether the period is stored as external data.
const double & re () const
Reynolds number.
double *& re_pt ()
Pointer to Reynolds number.
bool is_strouhal_stored_as_external_data () const
Are we storing the Strouhal number as external data?
const double & st () const
Strouhal parameter (const. version)
double * st_pt () const
Pointer to Strouhal parameter (const. version)
double *& st_pt ()
Pointer to Strouhal number (can only assign to private member data)
double re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
NavierStokesBodyForceFctPt & body_force_fct_pt ()
Access function for the body-force pointer.
NavierStokesBodyForceFctPt body_force_fct_pt () const
Access function for the body-force pointer. Const version.
NavierStokesSourceFctPt & source_fct_pt ()
Access function for the source-function pointer.
NavierStokesSourceFctPt source_fct_pt () const
Access function for the source-function pointer. Const version.
NavierStokesPressureAdvDiffSourceFctPt & source_fct_for_pressure_adv_diff ()
NavierStokesPressureAdvDiffSourceFctPt source_fct_for_pressure_adv_diff () const
int & pinned_fp_pressure_eqn ()
double u_nst (const unsigned &n, const unsigned &i) const
double u_nst (const unsigned &t, const unsigned &n, const unsigned &i) const
virtual unsigned u_index_nst (const unsigned &i) const
unsigned n_u_nst () const
double get_du_dt (const unsigned &n, const unsigned &i) const
double du_dt_nst (const unsigned &n, const unsigned &i) const
double interpolated_du_dt_nst (const Vector< double > &s, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
double pressure_integral () const
Integral of pressure over element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute the vorticity vector at local coordinate s.
void get_vorticity (const Vector< double > &s, double &vorticity) const
Compute the vorticity vector at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
double d_kin_energy_dt () const
Get integral of time derivative of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j+du_j/dx_i)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction_p, Vector< double > &traction_visc_n, Vector< double > &traction_visc_t)
void get_load (const Vector< double > &s, const Vector< double > &N, Vector< double > &load)
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
std::string scalar_name_paraview (const unsigned &i) const
void full_output (std::ostream &outfile)
void full_output (std::ostream &outfile, const unsigned &n_plot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void output_vorticity (std::ostream &outfile, const unsigned &nplot)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_norm (Vector< double > &norm)
Compute the vector norm of the FEM solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
void fill_in_pressure_advection_diffusion_residuals (Vector< double > &residuals)
void fill_in_pressure_advection_diffusion_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void pin_all_non_pressure_dofs (std::map< Data *, std::vector< int >> &eqn_number_backup)
Pin all non-pressure dofs and backup eqn numbers.
void output_pressure_advection_diffusion_robin_elements (std::ostream &outfile)
void delete_pressure_advection_diffusion_robin_elements ()
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
void interpolated_u_nst (const Vector< double > &s, Vector< double > &velocity) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void dinterpolated_u_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
virtual double interpolated_p_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_p_nst (const unsigned &t, const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s at time level t.
void point_output_data (const Vector< double > &s, Vector< double > &data)
SpaceTimeNavierStokesEquations ()
void store_strouhal_as_external_data (Data *strouhal_data_pt)
Function that tells us whether the period is stored as external data.
bool is_reynolds_strouhal_stored_as_external_data () const
Are we storing the Strouhal number as external data?
const double & re () const
Reynolds number.
double *& re_pt ()
Pointer to Reynolds number.
const double & re_st () const
ReSt parameter (const. version)
double * re_st_pt () const
Pointer to Strouhal parameter (const. version)
double *& re_st_pt ()
Pointer to ReSt number (can only assign to private member data)
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
NavierStokesBodyForceFctPt & body_force_fct_pt ()
Access function for the body-force pointer.
NavierStokesBodyForceFctPt body_force_fct_pt () const
Access function for the body-force pointer. Const version.
NavierStokesSourceFctPt & source_fct_pt ()
Access function for the source-function pointer.
NavierStokesSourceFctPt source_fct_pt () const
Access function for the source-function pointer. Const version.
NavierStokesPressureAdvDiffSourceFctPt & source_fct_for_pressure_adv_diff ()
NavierStokesPressureAdvDiffSourceFctPt source_fct_for_pressure_adv_diff () const
int & pinned_fp_pressure_eqn ()
double u_nst (const unsigned &n, const unsigned &i) const
double u_nst (const unsigned &t, const unsigned &n, const unsigned &i) const
virtual unsigned u_index_nst (const unsigned &i) const
unsigned n_u_nst () const
double get_du_dt (const unsigned &n, const unsigned &i) const
double du_dt_nst (const unsigned &n, const unsigned &i) const
double interpolated_du_dt_nst (const Vector< double > &s, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
double pressure_integral () const
Integral of pressure over element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute the vorticity vector at local coordinate s.
void get_vorticity (const Vector< double > &s, double &vorticity) const
Compute the vorticity vector at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
double d_kin_energy_dt () const
Get integral of time derivative of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j+du_j/dx_i)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction_p, Vector< double > &traction_visc_n, Vector< double > &traction_visc_t)
void get_load (const Vector< double > &s, const Vector< double > &N, Vector< double > &load)
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
std::string scalar_name_paraview (const unsigned &i) const
void full_output (std::ostream &outfile)
void full_output (std::ostream &outfile, const unsigned &n_plot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void output_vorticity (std::ostream &outfile, const unsigned &nplot)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_norm (Vector< double > &norm)
Compute the vector norm of the FEM solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
void fill_in_pressure_advection_diffusion_residuals (Vector< double > &residuals)
void fill_in_pressure_advection_diffusion_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void pin_all_non_pressure_dofs (std::map< Data *, std::vector< int >> &eqn_number_backup)
Pin all non-pressure dofs and backup eqn numbers.
void output_pressure_advection_diffusion_robin_elements (std::ostream &outfile)
void delete_pressure_advection_diffusion_robin_elements ()
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
void interpolated_u_nst (const Vector< double > &s, Vector< double > &velocity) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void dinterpolated_u_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
virtual double interpolated_p_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_p_nst (const unsigned &t, const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s at time level t.
void point_output_data (const Vector< double > &s, Vector< double > &data)
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
void get_vorticity (const Vector< double > &s, double &vorticity) const
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
void get_vorticity (const Vector< double > &s, double &vorticity) const
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
void get_vorticity (const Vector< double > &s, double &vorticity) const
Public Member Functions inherited from oomph::FSIFluidElement
FSIFluidElement ()
Constructor.
FSIFluidElement (const FSIFluidElement &)=delete
Broken copy constructor.
void operator= (const FSIFluidElement &)=delete
Broken assignment operator.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (double &norm)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::TemplateFreeSpaceTimeNavierStokesEquationsBase
TemplateFreeSpaceTimeNavierStokesEquationsBase ()
Constructor (empty)
virtual ~TemplateFreeSpaceTimeNavierStokesEquationsBase ()
Virtual destructor (empty)
TemplateFreeSpaceTimeNavierStokesEquationsBase ()
Constructor (empty)
virtual ~TemplateFreeSpaceTimeNavierStokesEquationsBase ()
Virtual destructor (empty)
TemplateFreeSpaceTimeNavierStokesEquationsBase ()
Constructor (empty)
virtual ~TemplateFreeSpaceTimeNavierStokesEquationsBase ()
Virtual destructor (empty)
Public Member Functions inherited from oomph::NavierStokesElementWithDiagonalMassMatrices
NavierStokesElementWithDiagonalMassMatrices ()
Empty constructor.
virtual ~NavierStokesElementWithDiagonalMassMatrices ()
Virtual destructor.
NavierStokesElementWithDiagonalMassMatrices (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken copy constructor.
void operator= (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken assignment operator.
Protected Member Functions
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
double dpshape_eulerian (const Vector< double > &s, Shape &ppsi, DShape &dppsidx) const
double dptest_eulerian (const Vector< double > &s, Shape &ptest, DShape &dptestdx) const
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
double dpshape_eulerian (const Vector< double > &s, Shape &ppsi, DShape &dppsidx) const
double dptest_eulerian (const Vector< double > &s, Shape &ptest, DShape &dptestdx) const
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
const unsigned Pconv [12]
double dpshape_eulerian (const Vector< double > &s, Shape &ppsi, DShape &dppsidx) const
double dptest_eulerian (const Vector< double > &s, Shape &ptest, DShape &dptestdx) const
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
const unsigned Pconv [8]
double dpshape_eulerian (const Vector< double > &s, Shape &ppsi, DShape &dppsidx) const
double dptest_eulerian (const Vector< double > &s, Shape &ptest, DShape &dptestdx) const
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
const unsigned Pconv [8]
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Protected Member Functions inherited from oomph::SpaceTimeNavierStokesEquations< DIM >
virtual void get_body_force_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
virtual void get_body_force_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
virtual double get_source_nst (const double &time, const unsigned &ipt, const Vector< double > &x)
Calculate the source fct at a given time and Eulerian position.
virtual void get_source_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
virtual void fill_in_generic_residual_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, const unsigned &flag)
virtual void fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
virtual void fill_in_generic_dresidual_contribution_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, const unsigned &flag)
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_body_force_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
virtual void get_body_force_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
virtual double get_source_nst (const double &time, const unsigned &ipt, const Vector< double > &x)
Calculate the source fct at a given time and Eulerian position.
virtual void get_source_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
virtual void fill_in_generic_residual_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, const unsigned &flag)
virtual void fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
virtual void fill_in_generic_dresidual_contribution_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, const unsigned &flag)
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_body_force_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
virtual void get_body_force_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
virtual double get_source_nst (const double &time, const unsigned &ipt, const Vector< double > &x)
Calculate the source fct at a given time and Eulerian position.
virtual void get_source_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
virtual void fill_in_generic_residual_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, const unsigned &flag)
virtual void fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
virtual void fill_in_generic_dresidual_contribution_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, const unsigned &flag)
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Static Protected Attributes
static const unsigned Pconv []
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Private Member Functions
const unsigned Initial_Nvalue [27]
const unsigned Initial_Nvalue [27]
const unsigned Initial_Nvalue [27]
Static Private Attributes
static const unsigned Initial_Nvalue []
Static array of ints to hold number of variables at node.
Additional Inherited Members
Public Types inherited from oomph::SpaceTimeNavierStokesEquations< DIM >
typedef void(* NavierStokesBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
typedef double(* NavierStokesSourceFctPt) (const double &time, const Vector< double > &x)
Function pointer to source function fct(t,x) (x is a Vector!)
typedef double(* NavierStokesPressureAdvDiffSourceFctPt) (const Vector< double > &x)
typedef void(* NavierStokesBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
typedef double(* NavierStokesSourceFctPt) (const double &time, const Vector< double > &x)
Function pointer to source function fct(t,x) (x is a Vector!)
typedef double(* NavierStokesPressureAdvDiffSourceFctPt) (const Vector< double > &x)
typedef void(* NavierStokesBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
typedef double(* NavierStokesSourceFctPt) (const double &time, const Vector< double > &x)
Function pointer to source function fct(t,x) (x is a Vector!)
typedef double(* NavierStokesPressureAdvDiffSourceFctPt) (const Vector< double > &x)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Attributes inherited from oomph::SpaceTimeNavierStokesEquations< DIM >
static Vector< double > Gamma
Navier-Stokes equations static data.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Attributes inherited from oomph::SpaceTimeNavierStokesEquations< DIM >
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Re_pt
Pointer to global Reynolds number.
double * St_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
bool Strouhal_is_stored_as_external_data
double * ReInvFr_pt
Vector< double > * G_pt
Pointer to global gravity Vector.
NavierStokesBodyForceFctPt Body_force_fct_pt
Pointer to body force function.
NavierStokesSourceFctPt Source_fct_pt
Pointer to volumetric source function.
NavierStokesPressureAdvDiffSourceFctPt Press_adv_diff_source_fct_pt
bool ALE_is_disabled
Vector< FpPressureAdvDiffRobinBCSpaceTimeElementBase * > Pressure_advection_diffusion_robin_element_pt
int Pinned_fp_pressure_eqn
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (= Womersley)
bool ReynoldsStrouhal_is_stored_as_external_data
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
template<unsigned DIM>
class oomph::QTaylorHoodSpaceTimeElement< DIM >
/////////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////// Taylor-Hood elements are Navier-Stokes elements with quadratic interpolation for velocities and positions and continuous linear pressure interpolation. They can be used within oomph-lib's block-preconditioning framework.
Constructor & Destructor Documentation
QTaylorHoodSpaceTimeElement() [1/3]
template<unsigned DIM> oomph::QTaylorHoodSpaceTimeElement< DIM >::QTaylorHoodSpaceTimeElement () inline
Constructor, no internal data points.
       : QElement<DIM + 1, 3>(), SpaceTimeNavierStokesEquations<DIM>()
     {
     }
QTaylorHoodSpaceTimeElement() [2/3]
template<unsigned DIM> oomph::QTaylorHoodSpaceTimeElement< DIM >::QTaylorHoodSpaceTimeElement () inline
Constructor, no internal data points.
       : QElement<DIM + 1, 3>(), SpaceTimeNavierStokesEquations<DIM>()
     {
     }
~QTaylorHoodSpaceTimeElement()
template<unsigned DIM> oomph::QTaylorHoodSpaceTimeElement< DIM >::~QTaylorHoodSpaceTimeElement () inline
     {
       // Delete the integral pointer
       delete this->integral_pt();
     } // End of ~QTaylorHoodSpaceTimeElement
References oomph::FiniteElement::integral_pt().
QTaylorHoodSpaceTimeElement() [3/3]
template<unsigned DIM> oomph::QTaylorHoodSpaceTimeElement< DIM >::QTaylorHoodSpaceTimeElement () inline
Constructor, no internal data points.
       : QElement<DIM + 1, 3>(), SpaceTimeNavierStokesEquations<DIM>()
     {
     }
Member Function Documentation
build_fp_press_adv_diff_robin_bc_element() [1/3]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::build_fp_press_adv_diff_robin_bc_element (const unsigned & face_index) inline virtual
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
Reimplemented in oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.
     {
       // Create a new Robic BC element and add it to the storage
       this->Pressure_advection_diffusion_robin_element_pt.push_back(
         new FpPressureAdvDiffRobinBCSpaceTimeElement<
           QTaylorHoodSpaceTimeElement<DIM>>(this, face_index));
     } // End of build_fp_press_adv_diff_robin_bc_element
References oomph::SpaceTimeNavierStokesEquations< DIM >::Pressure_advection_diffusion_robin_element_pt.
build_fp_press_adv_diff_robin_bc_element() [2/3]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::build_fp_press_adv_diff_robin_bc_element (const unsigned & face_index) inline virtual
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
Reimplemented in oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.
     {
       // Create a new Robic BC element and add it to the storage
       this->Pressure_advection_diffusion_robin_element_pt.push_back(
         new FpPressureAdvDiffRobinBCSpaceTimeElement<
           QTaylorHoodSpaceTimeElement<DIM>>(this, face_index));
     } // End of build_fp_press_adv_diff_robin_bc_element
References oomph::SpaceTimeNavierStokesEquations< DIM >::Pressure_advection_diffusion_robin_element_pt.
build_fp_press_adv_diff_robin_bc_element() [3/3]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::build_fp_press_adv_diff_robin_bc_element (const unsigned & face_index) inline virtual
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Create a new Robic BC element and add it to the storage
       this->Pressure_advection_diffusion_robin_element_pt.push_back(
         new FpPressureAdvDiffRobinBCSpaceTimeElement<
           QTaylorHoodSpaceTimeElement<DIM>>(this, face_index));
     } // End of build_fp_press_adv_diff_robin_bc_element
References oomph::SpaceTimeNavierStokesEquations< DIM >::Pressure_advection_diffusion_robin_element_pt.
dpshape_and_dptest_eulerian_nst() [1/6]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const inline protected virtual
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
dpshape_and_dptest_eulerian_nst() [2/6]
double oomph::QTaylorHoodSpaceTimeElement< 2 >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const inline protected virtual
2D (in space): Pressure shape and test functions and derivs w.r.t. to Eulerian coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
   {
     // Call the test functions and derivatives
     dptest_eulerian(s, ptest, dptestdx);
     // Call the shape functions and derivatives and the Jacobian of the mapping
     return this->dpshape_eulerian(s, ppsi, dppsidx);
   } // End of dpshape_and_dptest_eulerian_nst
References s.
dpshape_and_dptest_eulerian_nst() [3/6]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const inline protected virtual
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
dpshape_and_dptest_eulerian_nst() [4/6]
double oomph::QTaylorHoodSpaceTimeElement< 2 >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const inline protected virtual
2D (in space): Pressure shape and test functions and derivs w.r.t. to Eulerian coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
   {
     // Call the test functions and derivatives
     dptest_eulerian(s, ptest, dptestdx);
     // Call the shape functions and derivatives and the Jacobian of the mapping
     return this->dpshape_eulerian(s, ppsi, dppsidx);
   } // End of dpshape_and_dptest_eulerian_nst
References s.
dpshape_and_dptest_eulerian_nst() [5/6]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const inline protected virtual
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
dpshape_and_dptest_eulerian_nst() [6/6]
double oomph::QTaylorHoodSpaceTimeElement< 2 >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const inline protected virtual
2D (in space): Pressure shape and test functions and derivs w.r.t. to Eulerian coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
   {
     // Local storage for the shape function (x-direction)
     double psi1[2];
     // Local storage for the shape function (y-direction)
     double psi2[2];
     // Local storage for the shape function (z-direction)
     double psi3[2];
     // Local storage for the shape function derivatives (x-direction)
     double dpsi1[2];
     // Local storage for the test function derivatives (y-direction)
     double dpsi2[2];
     // Local storage for the test function derivatives (z-direction)
     double dpsi3[2];
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[0], psi1);
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[1], psi2);
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[2], psi3);
     // Call the OneDimensional Shape functions
     OneDimLagrange::dshape<2>(s[0], dpsi1);
     // Call the OneDimensional Shape functions
     OneDimLagrange::dshape<2>(s[1], dpsi2);
     // Call the OneDimensional Shape functions
     OneDimLagrange::dshape<2>(s[2], dpsi3);
     //--------------------------------------------------------------------
     // Now let's loop over the nodal points in the element with s1 being
     // the "x" coordinate, s2 being the "y" coordinate and s3 being the
     // "z" coordinate:
     //--------------------------------------------------------------------
     // Loop over the points in the z-direction
     for (unsigned i = 0; i < 2; i++)
     {
       // Loop over the points in the y-direction
       for (unsigned j = 0; j < 2; j++)
       {
         // Loop over the points in the x-direction
         for (unsigned k = 0; k < 2; k++)
         {
           // Multiply the three 1D functions together to get the 3D function
           ppsi[4 * i + 2 * j + k] = psi3[i] * psi2[j] * psi1[k];
           // Multiply the appropriate shape and shape function derivatives
           // together
           dppsidx(4 * i + 2 * j + k, 0) = psi3[i] * psi2[j] * dpsi1[k];
           // Multiply the appropriate shape and shape function derivatives
           // together
           dppsidx(4 * i + 2 * j + k, 1) = psi3[i] * dpsi2[j] * psi1[k];
           // Multiply the appropriate shape and shape function derivatives
           // together
           dppsidx(4 * i + 2 * j + k, 2) = dpsi3[i] * psi2[j] * psi1[k];
         }
       } // for (unsigned j=0;j<2;j++)
     } // for (unsigned i=0;i<2;i++)
     // Allocate space for the shape functions
     Shape psi(27);
     // Allocate space for the local shape function derivatives
     DShape dpsi(27, 3);
     // Get the values of the shape functions and their local derivatives
     dshape_local(s, psi, dpsi);
     // Allocate memory for the inverse 3x3 jacobian
     DenseMatrix<double> inverse_jacobian(3);
     // Now calculate the inverse jacobian
     const double det = local_to_eulerian_mapping(dpsi, inverse_jacobian);
     // Now set the values of the derivatives to be derivatives w.r.t. to
     // the Eulerian coordinates
     transform_derivatives(inverse_jacobian, dppsidx);
     // The test functions are equal to the shape functions
     ptest = ppsi;
     // The test function derivatives are equal to the shape function derivatives
     dptestdx = dppsidx;
     // Return the determinant of the jacobian
     return det;
   } // End of dpshape_and_dptest_eulerian_nst
References oomph::OneDimLagrange::dshape< 2 >(), i, j, k, s, and oomph::OneDimLagrange::shape< 2 >().
dpshape_eulerian() [1/4]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::dpshape_eulerian (const Vector< double > & s, Shape & ppsi, DShape & dppsidx) const inline protected virtual
Pressure shape functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
dpshape_eulerian() [2/4]
double oomph::QTaylorHoodSpaceTimeElement< 2 >::dpshape_eulerian (const Vector< double > & s, Shape & ppsi, DShape & dppsidx) const inline protected virtual
2D (in space): Pressure shape and test functions and derivs w.r.t. to Eulerian coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
   {
     // Local storage for the shape function (x-direction)
     double psi1[2];
     // Local storage for the shape function (y-direction)
     double psi2[2];
     // Local storage for the shape function (t-direction)
     double psi3[3];
     // Local storage for the shape function derivatives (x-direction)
     double dpsi1[2];
     // Local storage for the test function derivatives (y-direction)
     double dpsi2[2];
     // Local storage for the test function derivatives (t-direction)
     double dpsi3[3];
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[0], psi1);
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[1], psi2);
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<3>(s[2], psi3);
     // Call the OneDimensional Shape functions
     OneDimLagrange::dshape<2>(s[0], dpsi1);
     // Call the OneDimensional Shape functions
     OneDimLagrange::dshape<2>(s[1], dpsi2);
     // Call the OneDimensional Shape functions
     OneDimLagrange::dshape<3>(s[2], dpsi3);
     //--------------------------------------------------------------------
     // Now let's loop over the nodal points in the element with s1 being
     // the "x" coordinate, s2 being the "y" coordinate and s3 being the
     // "z" coordinate:
     //--------------------------------------------------------------------
     // Loop over the points in the t-direction
     for (unsigned i = 0; i < 3; i++)
     {
       // Loop over the points in the y-direction
       for (unsigned j = 0; j < 2; j++)
       {
         // Loop over the points in the x-direction
         for (unsigned k = 0; k < 2; k++)
         {
           // Multiply the three 1D functions together to get the 3D function
           ppsi[4 * i + 2 * j + k] = psi3[i] * psi2[j] * psi1[k];
           // Multiply the appropriate shape and shape function derivatives
           // together
           dppsidx(4 * i + 2 * j + k, 0) = psi3[i] * psi2[j] * dpsi1[k];
           // Multiply the appropriate shape and shape function derivatives
           // together
           dppsidx(4 * i + 2 * j + k, 1) = psi3[i] * dpsi2[j] * psi1[k];
           // Multiply the appropriate shape and shape function derivatives
           // together
           dppsidx(4 * i + 2 * j + k, 2) = dpsi3[i] * psi2[j] * psi1[k];
         }
       } // for (unsigned j=0;j<2;j++)
     } // for (unsigned i=0;i<3;i++)
     // Allocate space for the geometrical shape functions
     Shape psi(27);
     // Allocate space for the geometrical shape function derivatives
     DShape dpsi(27, 3);
     // Get the values of the shape functions and their derivatives
     dshape_local(s, psi, dpsi);
     // Allocate memory for the 3x3 inverse jacobian
     DenseMatrix<double> inverse_jacobian(3);
     // Now calculate the inverse jacobian
     const double det = local_to_eulerian_mapping(dpsi, inverse_jacobian);
     // Now set the values of the derivatives to be derivatives w.r.t. to
     // the Eulerian coordinates
     transform_derivatives(inverse_jacobian, dppsidx);
     // Return the determinant of the jacobian
     return det;
   } // End of dpshape_eulerian
References oomph::OneDimLagrange::dshape< 2 >(), oomph::OneDimLagrange::dshape< 3 >(), i, j, k, s, oomph::OneDimLagrange::shape< 2 >(), and oomph::OneDimLagrange::shape< 3 >().
dpshape_eulerian() [3/4]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::dpshape_eulerian (const Vector< double > & s, Shape & ppsi, DShape & dppsidx) const inline protected virtual
Pressure shape functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
dpshape_eulerian() [4/4]
double oomph::QTaylorHoodSpaceTimeElement< 2 >::dpshape_eulerian (const Vector< double > & s, Shape & ppsi, DShape & dppsidx) const inline protected virtual
2D (in space): Pressure shape and test functions and derivs w.r.t. to Eulerian coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
   {
     // Local storage for the shape function (x-direction)
     double psi1[2];
     // Local storage for the shape function (y-direction)
     double psi2[2];
     // Local storage for the shape function (z-direction)
     double psi3[2];
     // Local storage for the shape function derivatives (x-direction)
     double dpsi1[2];
     // Local storage for the test function derivatives (y-direction)
     double dpsi2[2];
     // Local storage for the test function derivatives (z-direction)
     double dpsi3[2];
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[0], psi1);
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[1], psi2);
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[2], psi3);
     // Call the OneDimensional Shape functions
     OneDimLagrange::dshape<2>(s[0], dpsi1);
     // Call the OneDimensional Shape functions
     OneDimLagrange::dshape<2>(s[1], dpsi2);
     // Call the OneDimensional Shape functions
     OneDimLagrange::dshape<2>(s[2], dpsi3);
     //--------------------------------------------------------------------
     // Now let's loop over the nodal points in the element with s1 being
     // the "x" coordinate, s2 being the "y" coordinate and s3 being the
     // "z" coordinate:
     //--------------------------------------------------------------------
     // Loop over the points in the z-direction
     for (unsigned i = 0; i < 2; i++)
     {
       // Loop over the points in the y-direction
       for (unsigned j = 0; j < 2; j++)
       {
         // Loop over the points in the x-direction
         for (unsigned k = 0; k < 2; k++)
         {
           // Multiply the three 1D functions together to get the 3D function
           ppsi[4 * i + 2 * j + k] = psi3[i] * psi2[j] * psi1[k];
           // Multiply the appropriate shape and shape function derivatives
           // together
           dppsidx(4 * i + 2 * j + k, 0) = psi3[i] * psi2[j] * dpsi1[k];
           // Multiply the appropriate shape and shape function derivatives
           // together
           dppsidx(4 * i + 2 * j + k, 1) = psi3[i] * dpsi2[j] * psi1[k];
           // Multiply the appropriate shape and shape function derivatives
           // together
           dppsidx(4 * i + 2 * j + k, 2) = dpsi3[i] * psi2[j] * psi1[k];
         }
       } // for (unsigned j=0;j<2;j++)
     } // for (unsigned i=0;i<2;i++)
     // Allocate space for the geometrical shape functions
     Shape psi(27);
     // Allocate space for the geometrical shape function derivatives
     DShape dpsi(27, 3);
     // Get the values of the shape functions and their derivatives
     dshape_local(s, psi, dpsi);
     // Allocate memory for the 3x3 inverse jacobian
     DenseMatrix<double> inverse_jacobian(3);
     // Now calculate the inverse jacobian
     const double det = local_to_eulerian_mapping(dpsi, inverse_jacobian);
     // Now set the values of the derivatives to be derivatives w.r.t. to
     // the Eulerian coordinates
     transform_derivatives(inverse_jacobian, dppsidx);
     // Return the determinant of the jacobian
     return det;
   } // End of dpshape_eulerian
References oomph::OneDimLagrange::dshape< 2 >(), i, j, k, s, and oomph::OneDimLagrange::shape< 2 >().
dptest_eulerian() [1/4]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::dptest_eulerian (const Vector< double > & s, Shape & ptest, DShape & dptestdx) const inline protected virtual
Pressure test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
dptest_eulerian() [2/4]
double oomph::QTaylorHoodSpaceTimeElement< 2 >::dptest_eulerian (const Vector< double > & s, Shape & ptest, DShape & dptestdx) const inline protected virtual
2D (in space): Pressure shape and test functions and derivs w.r.t. to Eulerian coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
   {
     // Local storage for the shape function (x-direction)
     double test1[2];
     // Local storage for the shape function (y-direction)
     double test2[2];
     // Local storage for the shape function (t-direction)
     double test3[3];
     // Local storage for the shape function derivatives (x-direction)
     double dtest1[2];
     // Local storage for the test function derivatives (y-direction)
     double dtest2[2];
     // Local storage for the test function derivatives (t-direction)
     double dtest3[3];
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[0], test1);
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[1], test2);
     // Call the OneDimensional Shape functions
     OneDimDiscontinuousGalerkin::shape<3>(s[2], test3);
     // Call the OneDimensional Shape functions
     OneDimLagrange::dshape<2>(s[0], dtest1);
     // Call the OneDimensional Shape functions
     OneDimLagrange::dshape<2>(s[1], dtest2);
     // Call the OneDimensional Shape functions
     OneDimDiscontinuousGalerkin::dshape<3>(s[2], dtest3);
     //--------------------------------------------------------------------
     // Now let's loop over the nodal points in the element with s1 being
     // the "x" coordinate, s2 being the "y" coordinate and s3 being the
     // "z" coordinate:
     //--------------------------------------------------------------------
     // Loop over the points in the t-direction
     for (unsigned i = 0; i < 3; i++)
     {
       // Loop over the points in the y-direction
       for (unsigned j = 0; j < 2; j++)
       {
         // Loop over the points in the x-direction
         for (unsigned k = 0; k < 2; k++)
         {
           // Multiply the three 1D functions together to get the 3D function
           ptest[4 * i + 2 * j + k] = test3[i] * test2[j] * test1[k];
           // Multiply the appropriate shape and shape function derivatives
           // together
           dptestdx(4 * i + 2 * j + k, 0) = test3[i] * test2[j] * dtest1[k];
           // Multiply the appropriate shape and shape function derivatives
           // together
           dptestdx(4 * i + 2 * j + k, 1) = test3[i] * dtest2[j] * test1[k];
           // Multiply the appropriate shape and shape function derivatives
           // together
           dptestdx(4 * i + 2 * j + k, 2) = dtest3[i] * test2[j] * test1[k];
         }
       } // for (unsigned j=0;j<2;j++)
     } // for (unsigned i=0;i<3;i++)
     // Allocate space for the geometrical shape functions
     Shape psi(27);
     // Allocate space for the geometrical shape function derivatives
     DShape dpsi(27, 3);
     // Get the values of the shape functions and their derivatives
     dshape_local(s, psi, dpsi);
     // Allocate memory for the 3x3 inverse jacobian
     DenseMatrix<double> inverse_jacobian(3);
     // Now calculate the inverse jacobian
     const double det = local_to_eulerian_mapping(dpsi, inverse_jacobian);
     // Now set the values of the derivatives to be derivatives w.r.t. to
     // the Eulerian coordinates
     transform_derivatives(inverse_jacobian, dptestdx);
     // Return the determinant of the jacobian
     return det;
   } // End of dptest_eulerian
References oomph::OneDimLagrange::dshape< 2 >(), oomph::OneDimLagrange::dshape< 3 >(), i, j, k, s, oomph::OneDimLagrange::shape< 2 >(), oomph::OneDimLagrange::shape< 3 >(), test1(), and test2().
dptest_eulerian() [3/4]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::dptest_eulerian (const Vector< double > & s, Shape & ptest, DShape & dptestdx) const inline protected virtual
Pressure test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
dptest_eulerian() [4/4]
double oomph::QTaylorHoodSpaceTimeElement< 2 >::dptest_eulerian (const Vector< double > & s, Shape & ptest, DShape & dptestdx) const inline protected virtual
2D (in space): Pressure shape and test functions and derivs w.r.t. to Eulerian coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
   {
     // Local storage for the shape function (x-direction)
     double test1[2];
     // Local storage for the shape function (y-direction)
     double test2[2];
     // Local storage for the shape function (z-direction)
     double test3[2];
     // Local storage for the shape function derivatives (x-direction)
     double dtest1[2];
     // Local storage for the test function derivatives (y-direction)
     double dtest2[2];
     // Local storage for the test function derivatives (z-direction)
     double dtest3[2];
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[0], test1);
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[1], test2);
     // Call the OneDimensional Shape functions
     // OneDimLagrange::shape<2>(s[2],test3);
     OneDimDiscontinuousGalerkin::shape<2>(s[2], test3);
     // Call the OneDimensional Shape functions
     OneDimLagrange::dshape<2>(s[0], dtest1);
     // Call the OneDimensional Shape functions
     OneDimLagrange::dshape<2>(s[1], dtest2);
     // Call the OneDimensional Shape functions
     // OneDimLagrange::dshape<2>(s[2],dtest3);
     OneDimDiscontinuousGalerkin::dshape<2>(s[2], dtest3);
     //--------------------------------------------------------------------
     // Now let's loop over the nodal points in the element with s1 being
     // the "x" coordinate, s2 being the "y" coordinate and s3 being the
     // "z" coordinate:
     //--------------------------------------------------------------------
     // Loop over the points in the z-direction
     for (unsigned i = 0; i < 2; i++)
     {
       // Loop over the points in the y-direction
       for (unsigned j = 0; j < 2; j++)
       {
         // Loop over the points in the x-direction
         for (unsigned k = 0; k < 2; k++)
         {
           // Multiply the three 1D functions together to get the 3D function
           ptest[4 * i + 2 * j + k] = test3[i] * test2[j] * test1[k];
           // Multiply the appropriate shape and shape function derivatives
           // together
           dptestdx(4 * i + 2 * j + k, 0) = test3[i] * test2[j] * dtest1[k];
           // Multiply the appropriate shape and shape function derivatives
           // together
           dptestdx(4 * i + 2 * j + k, 1) = test3[i] * dtest2[j] * test1[k];
           // Multiply the appropriate shape and shape function derivatives
           // together
           dptestdx(4 * i + 2 * j + k, 2) = dtest3[i] * test2[j] * test1[k];
         }
       } // for (unsigned j=0;j<2;j++)
     } // for (unsigned i=0;i<2;i++)
     // Allocate space for the geometrical shape functions
     Shape psi(27);
     // Allocate space for the geometrical shape function derivatives
     DShape dpsi(27, 3);
     // Get the values of the shape functions and their derivatives
     dshape_local(s, psi, dpsi);
     // Allocate memory for the 3x3 inverse jacobian
     DenseMatrix<double> inverse_jacobian(3);
     // Now calculate the inverse jacobian
     const double det = local_to_eulerian_mapping(dpsi, inverse_jacobian);
     // Now set the values of the derivatives to be derivatives w.r.t. to
     // the Eulerian coordinates
     transform_derivatives(inverse_jacobian, dptestdx);
     // Return the determinant of the jacobian
     return det;
   } // End of dptest_eulerian
References oomph::OneDimLagrange::dshape< 2 >(), i, j, k, s, oomph::OneDimLagrange::shape< 2 >(), test1(), and test2().
dshape_and_dtest_eulerian_at_knot_nst() [1/9]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const inline protected virtual
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
dshape_and_dtest_eulerian_at_knot_nst() [2/9]
double oomph::QTaylorHoodSpaceTimeElement< 2 >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const inline protected virtual
2D (in space): Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
   {
     // Call the geometrical shape functions and derivatives
     const double J = this->dshape_eulerian_at_knot(
       ipt, psi, dpsidx, djacobian_dX, d_dpsidx_dX);
     // DRAIG: Delete!
     throw OomphLibError("Hasn't been implemented properly yet!",
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
     // Loop over the test functions and derivatives
     for (unsigned i = 0; i < 27; i++)
     {
       // The test functions are the same as the shape functions
       test[i] = psi[i];
       // Loop over the spatial derivatives
       for (unsigned k = 0; k < 3; k++)
       {
         // Set the test function derivatives to the shape function derivatives
         dtestdx(i, k) = dpsidx(i, k);
         // Loop over the dimensions
         for (unsigned p = 0; p < 3; p++)
         {
           // Loop over test functions
           for (unsigned q = 0; q < 27; q++)
           {
             // Set the test function derivatives to the shape function
             // derivatives
             d_dtestdx_dX(p, q, i, k) = d_dpsidx_dX(p, q, i, k);
           }
         } // for (unsigned p=0;p<3;p++)
       } // for (unsigned k=0;k<3;k++)
     } // for (unsigned i=0;i<27;i++)
     // Return the jacobian
     return J;
   } // End of dshape_and_dtest_eulerian_at_knot_nst
References i, J, k, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, p, and Eigen::numext::q.
dshape_and_dtest_eulerian_at_knot_nst() [3/9]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const inline protected virtual
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
dshape_and_dtest_eulerian_at_knot_nst() [4/9]
double oomph::QTaylorHoodSpaceTimeElement< 2 >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const inline protected virtual
2D (in space): Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
   {
     // Call the geometrical shape functions and derivatives
     const double J = this->dshape_eulerian_at_knot(
       ipt, psi, dpsidx, djacobian_dX, d_dpsidx_dX);
     // DRAIG: Delete!
     throw OomphLibError("Hasn't been implemented properly yet!",
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
     // Loop over the test functions and derivatives
     for (unsigned i = 0; i < 27; i++)
     {
       // The test functions are the same as the shape functions
       test[i] = psi[i];
       // Loop over the spatial derivatives
       for (unsigned k = 0; k < 3; k++)
       {
         // Set the test function derivatives to the shape function derivatives
         dtestdx(i, k) = dpsidx(i, k);
         // Loop over the dimensions
         for (unsigned p = 0; p < 3; p++)
         {
           // Loop over test functions
           for (unsigned q = 0; q < 27; q++)
           {
             // Set the test function derivatives to the shape function
             // derivatives
             d_dtestdx_dX(p, q, i, k) = d_dpsidx_dX(p, q, i, k);
           }
         } // for (unsigned p=0;p<3;p++)
       } // for (unsigned k=0;k<3;k++)
     } // for (unsigned i=0;i<27;i++)
     // Return the jacobian
     return J;
   } // End of dshape_and_dtest_eulerian_at_knot_nst
References i, J, k, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, p, and Eigen::numext::q.
dshape_and_dtest_eulerian_at_knot_nst() [5/9]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const inline protected virtual
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
dshape_and_dtest_eulerian_at_knot_nst() [6/9]
double oomph::QTaylorHoodSpaceTimeElement< 2 >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const inline protected virtual
2D (in space): Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
   {
     // Call the geometrical shape functions and derivatives
     const double J = this->dshape_eulerian_at_knot(
       ipt, psi, dpsidx, djacobian_dX, d_dpsidx_dX);
     // Loop over the test functions and derivatives
     for (unsigned i = 0; i < 27; i++)
     {
       // The test functions are the same as the shape functions
       test[i] = psi[i];
       // Loop over the spatial derivatives
       for (unsigned k = 0; k < 3; k++)
       {
         // Set the test function derivatives to the shape function derivatives
         dtestdx(i, k) = dpsidx(i, k);
         // Loop over the dimensions
         for (unsigned p = 0; p < 3; p++)
         {
           // Loop over test functions
           for (unsigned q = 0; q < 27; q++)
           {
             // Set the test function derivatives to the shape function
             // derivatives
             d_dtestdx_dX(p, q, i, k) = d_dpsidx_dX(p, q, i, k);
           }
         } // for (unsigned p=0;p<3;p++)
       } // for (unsigned k=0;k<3;k++)
     } // for (unsigned i=0;i<27;i++)
     // Return the jacobian
     return J;
   } // End of dshape_and_dtest_eulerian_at_knot_nst
References i, J, k, p, and Eigen::numext::q.
dshape_and_dtest_eulerian_at_knot_nst() [7/9]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const inline protected virtual
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
   {
     // Calculate the element dimension
     const unsigned el_dim = DIM + 1;
     // Storage for the local coordinates of the integration point
     Vector<double> s(el_dim, 0.0);
     // Set the local coordinate
     for (unsigned i = 0; i < el_dim; i++)
     {
       // Calculate the i-th local coordinate at the ipt-th knot point
       s[i] = this->integral_pt()->knot(ipt, i);
     }
     // Return the Jacobian of the geometrical shape functions and derivatives
     return dshape_and_dtest_eulerian_nst(s, psi, dpsidx, test, dtestdx);
   } // End of dshape_and_dtest_eulerian_at_knot_nst
References DIM, el_dim, i, and s.
dshape_and_dtest_eulerian_at_knot_nst() [8/9]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const inline protected virtual
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
dshape_and_dtest_eulerian_at_knot_nst() [9/9]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const inline protected virtual
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
dshape_and_dtest_eulerian_nst() [1/3]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const inline protected virtual
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
   {
     //--------------------------
     // Call the shape functions:
     //--------------------------
     // Find the element dimension
     const unsigned el_dim = this->dim();
     // Get the values of the shape functions and their local derivatives,
     // temporarily stored in dpsi
     this->dshape_local(s, psi, dpsidx);
     // Allocate memory for the inverse jacobian
     DenseMatrix<double> inverse_jacobian(el_dim);
     // Now calculate the inverse jacobian
     const double det =
       this->local_to_eulerian_mapping(dpsidx, inverse_jacobian);
     // Now set the values of the derivatives to be dpsidx
     this->transform_derivatives(inverse_jacobian, dpsidx);
     //-------------------------
     // Call the test functions:
     //-------------------------
     // Make sure we're using 3D elements
     if (el_dim != 3)
     {
       // Create an output stream
       std::ostringstream error_message_stream;
       // Create an error message
       error_message_stream << "Need 3D space-time elements for this to work!"
                            << std::endl;
       // Throw the error message
       throw OomphLibError(error_message_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
     //--------start_of_dshape_local--------------------------------------
     // Local storage
     double test_values[3][3];
     double dtest_values[3][3];
     // Index of the total shape function
     unsigned index = 0;
     // Call the 1D shape functions and derivatives
     OneDimLagrange::shape<3>(s[0], test_values[0]);
     OneDimLagrange::shape<3>(s[1], test_values[1]);
     OneDimLagrange::dshape<3>(s[0], dtest_values[0]);
     OneDimLagrange::dshape<3>(s[1], dtest_values[1]);
     // Set the time discretisation
     OneDimDiscontinuousGalerkin::shape<3>(s[2], test_values[2]);
     OneDimDiscontinuousGalerkin::dshape<3>(s[2], dtest_values[2]);
     // Loop over the nodes in the third local coordinate direction
     for (unsigned k = 0; k < 3; k++)
     {
       // Loop over the nodes in the second local coordinate direction
       for (unsigned j = 0; j < 3; j++)
       {
         // Loop over the nodes in the first local coordinate direction
         for (unsigned i = 0; i < 3; i++)
         {
           // Calculate dtest/ds_0
           dtestdx(index, 0) =
             dtest_values[0][i] * test_values[1][j] * test_values[2][k];
           // Calculate dtest/ds_1
           dtestdx(index, 1) =
             test_values[0][i] * dtest_values[1][j] * test_values[2][k];
           // Calculate dtest/ds_2
           dtestdx(index, 2) =
             test_values[0][i] * test_values[1][j] * dtest_values[2][k];
           // Calculate the index-th entry of test
           test[index] =
             test_values[0][i] * test_values[1][j] * test_values[2][k];
           // Increment the index
           index++;
         }
       } // for (unsigned j=0;j<3;j++)
     } // for (unsigned k=0;k<3;k++)
     //--------end_of_dshape_local----------------------------------------
     // Transform derivatives from dtest/ds to dtest/dx
     this->transform_derivatives(inverse_jacobian, dtestdx);
     // Return the determinant value
     return det;
   } // End of dshape_and_dtest_eulerian_nst
References oomph::OneDimLagrange::dshape< 3 >(), oomph::OneDimDiscontinuousGalerkin::dshape< 3 >(), el_dim, i, j, k, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, s, oomph::OneDimLagrange::shape< 3 >(), and oomph::OneDimDiscontinuousGalerkin::shape< 3 >().
dshape_and_dtest_eulerian_nst() [2/3]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const inline protected virtual
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
dshape_and_dtest_eulerian_nst() [3/3]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const inline protected virtual
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
fix_pressure() [1/3]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::fix_pressure (const unsigned & p_dof, const double & p_value) inline virtual
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Pin the pressure dof
       this->node_pt(Pconv[p_dof])->pin(this->p_nodal_index_nst());
       // Now set its value
       this->node_pt(Pconv[p_dof])
         ->set_value(this->p_nodal_index_nst(), p_value);
     } // End of fix_pressure
References oomph::FiniteElement::node_pt(), oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst(), oomph::Data::pin(), and oomph::Data::set_value().
fix_pressure() [2/3]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::fix_pressure (const unsigned & p_dof, const double & p_value) inline virtual
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Pin the pressure dof
       this->node_pt(Pconv[p_dof])->pin(this->p_nodal_index_nst());
       // Now set its value
       this->node_pt(Pconv[p_dof])
         ->set_value(this->p_nodal_index_nst(), p_value);
     } // End of fix_pressure
References oomph::FiniteElement::node_pt(), oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst(), oomph::Data::pin(), and oomph::Data::set_value().
fix_pressure() [3/3]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::fix_pressure (const unsigned & p_dof, const double & p_value) inline virtual
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Pin the pressure dof
       this->node_pt(Pconv[p_dof])->pin(this->p_nodal_index_nst());
       // Now set its value
       this->node_pt(Pconv[p_dof])
         ->set_value(this->p_nodal_index_nst(), p_value);
     } // End of fix_pressure
References oomph::FiniteElement::node_pt(), oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst(), oomph::Data::pin(), and oomph::Data::set_value().
get_dof_numbers_for_unknowns()
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> & dof_lookup_list) const virtual
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the "DOF type" that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Velocity=0; Pressure=1
Create a list of pairs for all unknowns in this element, so the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the "DOF type" that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Reimplemented from oomph::GeneralisedElement.
   {
     // Get the number of nodes in this element
     unsigned n_node = this->nnode();
     // Temporary pair (used to store dof lookup prior to being added to list)
     std::pair<unsigned, unsigned> dof_lookup;
     // Loop over the nodes
     for (unsigned n = 0; n < n_node; n++)
     {
       // Find the number of values at this node
       unsigned n_value = this->required_nvalue(n);
       // Loop over these values
       for (unsigned i_value = 0; i_value < n_value; i_value++)
       {
         // Determine the local eqn number associated with this value
         int local_eqn_number = this->nodal_local_eqn(n, i_value);
         // Ignore pinned values - far away degrees of freedom resulting
         // from hanging nodes can be ignored since these are be dealt
         // with by the element containing their master nodes
         if (local_eqn_number >= 0)
         {
           // Store dof lookup in temporary pair; the global equation number
           // is the first entry in pair
           dof_lookup.first = this->eqn_number(local_eqn_number);
           // Set dof numbers; dof number is the second entry in pair
           // DRAIG: Uncomment whichever one you want to use. Setting
           // all dof numbers to 0 means you don't distinguish between
           // velocity and pressure component; just aggregate everything.
           // In contrast, setting the dof number to i_value means the
           // dofs associated with the first velocity component, second
           // velocity component and the pressure are all separated
           // dof_lookup.second=i_value;
           dof_lookup.second = 0;
           // Add to list
           dof_lookup_list.push_front(dof_lookup);
         }
       } // for (unsigned v=0;v<nv;v++)
     } // for (unsigned n=0;n<n_node;n++)
   } // End of get_dof_numbers_for_unknowns
References n.
identify_load_data() [1/3]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::identify_load_data (std::set< std::pair< Data *, unsigned >> & paired_load_data) virtual
Add to the set paired_load_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Implements oomph::FSIFluidElement.
Reimplemented in oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.
   {
     // Allocate storage for the indices of the velocity components
     unsigned u_index[DIM];
     // Loop over the velocity components
     for (unsigned i = 0; i < DIM; i++)
     {
       // Get the index at which the i-th velocity component is stored
       u_index[i] = this->u_index_nst(i);
     }
     // Get the number of nodes in this element
     unsigned n_node = this->nnode();
     // Loop over the nodes
     for (unsigned n = 0; n < n_node; n++)
     {
       // Loop over the velocity components and add pointer to their data
       // and indices to the vectors
       for (unsigned i = 0; i < DIM; i++)
       {
         // Add in the node and equation number pair
         paired_load_data.insert(std::make_pair(this->node_pt(n), u_index[i]));
       }
     } // for (unsigned n=0;n<n_node;n++)
     // Identify the pressure data
     this->identify_pressure_data(paired_load_data);
   } // End of identify_load_data
References DIM, i, and n.
identify_load_data() [2/3]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::identify_load_data (std::set< std::pair< Data *, unsigned >> & paired_load_data) virtual
Add to the set paired_load_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Implements oomph::FSIFluidElement.
Reimplemented in oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.
identify_load_data() [3/3]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::identify_load_data (std::set< std::pair< Data *, unsigned >> & paired_load_data) virtual
Add to the set paired_load_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Implements oomph::FSIFluidElement.
identify_pressure_data() [1/3]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::identify_pressure_data (std::set< std::pair< Data *, unsigned >> & paired_pressure_data) virtual
Add to the set paired_pressure_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for all pressure values that affect the load computed in the get_load(...) function.
Add to the set paired_pressure_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for pressure values that affect the load computed in the get_load(...) function.,
Implements oomph::FSIFluidElement.
   {
     // Find the index at which the pressure is stored
     unsigned p_index = static_cast<unsigned>(this->p_nodal_index_nst());
     // Get the number of pressure degrees of freedom
     unsigned n_pres = npres_nst();
     // Loop over the pressure data
     for (unsigned l = 0; l < n_pres; l++)
     {
       // The DIM-th entry in each nodal data is the pressure, which affects
       // the traction
       paired_pressure_data.insert(
         std::make_pair(this->node_pt(Pconv[l]), p_index));
     }
   } // End of identify_pressure_data
identify_pressure_data() [2/3]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::identify_pressure_data (std::set< std::pair< Data *, unsigned >> & paired_pressure_data) virtual
Add to the set paired_pressure_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for all pressure values that affect the load computed in the get_load(...) function.
Implements oomph::FSIFluidElement.
identify_pressure_data() [3/3]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::identify_pressure_data (std::set< std::pair< Data *, unsigned >> & paired_pressure_data) virtual
Add to the set paired_pressure_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for all pressure values that affect the load computed in the get_load(...) function.
Implements oomph::FSIFluidElement.
Initial_Nvalue() [1/3]
const unsigned oomph::QTaylorHoodSpaceTimeElement< 2 >::Initial_Nvalue private
//////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Initial_Nvalue() [2/3]
const unsigned oomph::QTaylorHoodSpaceTimeElement< 2 >::Initial_Nvalue private
//////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Initial_Nvalue() [3/3]
const unsigned oomph::QTaylorHoodSpaceTimeElement< 2 >::Initial_Nvalue private
//////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
ndof_types()
template<unsigned DIM> unsigned oomph::QTaylorHoodSpaceTimeElement< DIM >::ndof_types () const inline virtual
Returns the number of "DOF types" that degrees of freedom in this element are sub-divided into: Velocity and pressure.
Reimplemented from oomph::GeneralisedElement.
     {
       // There are DIM velocity components and 1 pressure component
       return DIM + 1;
     } // End of ndof_types
References DIM.
npres_nst() [1/3]
template<unsigned DIM> unsigned oomph::QTaylorHoodSpaceTimeElement< DIM >::npres_nst () const inline virtual
Return number of pressure values.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // There are 3*(2^{DIM}) pressure dofs where DIM is the spatial dimension
       // (remembering that these are space-time elements)
       return 3.0 * static_cast<unsigned>(pow(2.0, static_cast<int>(DIM)));
     } // End of npres_nst
References DIM, and Eigen::bfloat16_impl::pow().
Referenced by oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::identify_load_data(), and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs().
npres_nst() [2/3]
template<unsigned DIM> unsigned oomph::QTaylorHoodSpaceTimeElement< DIM >::npres_nst () const inline virtual
Return number of pressure values.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // There are 2^{DIM+1} pressure dofs where DIM is the spatial dimension
       // (rememebering that these are space-time elements)
       return static_cast<unsigned>(pow(2.0, static_cast<int>(DIM + 1)));
     } // End of npres_nst
References DIM, and Eigen::bfloat16_impl::pow().
npres_nst() [3/3]
template<unsigned DIM> unsigned oomph::QTaylorHoodSpaceTimeElement< DIM >::npres_nst () const inline virtual
Return number of pressure values.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // There are 2^{DIM+1} pressure dofs where DIM is the spatial dimension
       // (rememebering that these are space-time elements)
       return static_cast<unsigned>(pow(2.0, static_cast<int>(DIM + 1)));
     } // End of npres_nst
References DIM, and Eigen::bfloat16_impl::pow().
output() [1/12]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::output (FILE * file_pt) inline virtual
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Call the base class implementation
       SpaceTimeNavierStokesEquations<DIM>::output(file_pt);
     } // End of output
References oomph::SpaceTimeNavierStokesEquations< DIM >::output().
output() [2/12]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::output (FILE * file_pt) inline virtual
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Call the base class implementation
       SpaceTimeNavierStokesEquations<DIM>::output(file_pt);
     } // End of output
References oomph::SpaceTimeNavierStokesEquations< DIM >::output().
output() [3/12]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::output (FILE * file_pt) inline virtual
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Call the base class implementation
       SpaceTimeNavierStokesEquations<DIM>::output(file_pt);
     } // End of output
References oomph::SpaceTimeNavierStokesEquations< DIM >::output().
output() [4/12]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::output (FILE * file_pt, const unsigned & nplot) inline virtual
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Call the base class implementation
       SpaceTimeNavierStokesEquations<DIM>::output(file_pt, nplot);
     } // End of output
References oomph::SpaceTimeNavierStokesEquations< DIM >::output().
output() [5/12]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::output (FILE * file_pt, const unsigned & nplot) inline virtual
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Call the base class implementation
       SpaceTimeNavierStokesEquations<DIM>::output(file_pt, nplot);
     } // End of output
References oomph::SpaceTimeNavierStokesEquations< DIM >::output().
output() [6/12]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::output (FILE * file_pt, const unsigned & nplot) inline virtual
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Call the base class implementation
       SpaceTimeNavierStokesEquations<DIM>::output(file_pt, nplot);
     } // End of output
References oomph::SpaceTimeNavierStokesEquations< DIM >::output().
output() [7/12]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::output (std::ostream & outfile) inline virtual
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Call the base class implementation
       SpaceTimeNavierStokesEquations<DIM>::output(outfile);
     } // End of output
References oomph::SpaceTimeNavierStokesEquations< DIM >::output().
output() [8/12]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::output (std::ostream & outfile) inline virtual
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Call the base class implementation
       SpaceTimeNavierStokesEquations<DIM>::output(outfile);
     } // End of output
References oomph::SpaceTimeNavierStokesEquations< DIM >::output().
output() [9/12]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::output (std::ostream & outfile) inline virtual
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Call the base class implementation
       SpaceTimeNavierStokesEquations<DIM>::output(outfile);
     } // End of output
References oomph::SpaceTimeNavierStokesEquations< DIM >::output().
output() [10/12]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) inline virtual
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Call the base class implementation
       SpaceTimeNavierStokesEquations<DIM>::output(outfile, nplot);
     } // End of output
References oomph::SpaceTimeNavierStokesEquations< DIM >::output().
output() [11/12]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) inline virtual
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Call the base class implementation
       SpaceTimeNavierStokesEquations<DIM>::output(outfile, nplot);
     } // End of output
References oomph::SpaceTimeNavierStokesEquations< DIM >::output().
output() [12/12]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) inline virtual
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Call the base class implementation
       SpaceTimeNavierStokesEquations<DIM>::output(outfile, nplot);
     } // End of output
References oomph::SpaceTimeNavierStokesEquations< DIM >::output().
p_local_eqn() [1/3]
template<unsigned DIM> int oomph::QTaylorHoodSpaceTimeElement< DIM >::p_local_eqn (const unsigned & n) const inline virtual
Return the local equation numbers for the pressure values.
Implements oomph::TemplateFreeSpaceTimeNavierStokesEquationsBase.
     {
       // Get the local equation number associated with the n-th pressure dof
       return this->nodal_local_eqn(Pconv[n], p_nodal_index_nst());
     } // End of p_local_eqn
References n, oomph::FiniteElement::nodal_local_eqn(), and oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst().
p_local_eqn() [2/3]
template<unsigned DIM> int oomph::QTaylorHoodSpaceTimeElement< DIM >::p_local_eqn (const unsigned & n) const inline virtual
Return the local equation numbers for the pressure values.
Implements oomph::TemplateFreeSpaceTimeNavierStokesEquationsBase.
     {
       // Get the local equation number associated with the n-th pressure dof
       return this->nodal_local_eqn(Pconv[n], p_nodal_index_nst());
     } // End of p_local_eqn
References n, oomph::FiniteElement::nodal_local_eqn(), and oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst().
p_local_eqn() [3/3]
template<unsigned DIM> int oomph::QTaylorHoodSpaceTimeElement< DIM >::p_local_eqn (const unsigned & n) const inline virtual
Return the local equation numbers for the pressure values.
Implements oomph::TemplateFreeSpaceTimeNavierStokesEquationsBase.
     {
       // Get the local equation number associated with the n-th pressure dof
       return this->nodal_local_eqn(Pconv[n], p_nodal_index_nst());
     } // End of p_local_eqn
References n, oomph::FiniteElement::nodal_local_eqn(), and oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst().
p_nodal_index_nst() [1/3]
template<unsigned DIM> virtual int oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst () const inline virtual
Set the value at which the pressure is stored in the nodes.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // The pressure is stored straight after the velocity components
       return static_cast<int>(DIM);
     } // End of p_nodal_index_nst
References DIM.
Referenced by oomph::QTaylorHoodSpaceTimeElement< DIM >::fix_pressure(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::further_setup_hanging_nodes(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::identify_load_data(), oomph::QTaylorHoodSpaceTimeElement< DIM >::p_local_eqn(), oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nst(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs(), and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::unpin_elemental_pressure_dofs().
p_nodal_index_nst() [2/3]
template<unsigned DIM> virtual int oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst () const inline virtual
Set the value at which the pressure is stored in the nodes.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // The pressure is stored straight after the velocity components
       return static_cast<int>(DIM);
     } // End of p_nodal_index_nst
References DIM.
p_nodal_index_nst() [3/3]
template<unsigned DIM> virtual int oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst () const inline virtual
Set the value at which the pressure is stored in the nodes.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // The pressure is stored straight after the velocity components
       return static_cast<int>(DIM);
     } // End of p_nodal_index_nst
References DIM.
p_nst() [1/6]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nst (const unsigned & n_p) const inline virtual
Access function for the pressure values at local pressure node n_p (const version)
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Get the nodal value associated with the n_p-th pressure dof
       return this->nodal_value(Pconv[n_p], this->p_nodal_index_nst());
     } // End of p_nst
References oomph::FiniteElement::nodal_value(), and oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst().
p_nst() [2/6]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nst (const unsigned & n_p) const inline virtual
Access function for the pressure values at local pressure node n_p (const version)
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Get the nodal value associated with the n_p-th pressure dof
       return this->nodal_value(Pconv[n_p], this->p_nodal_index_nst());
     } // End of p_nst
References oomph::FiniteElement::nodal_value(), and oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst().
p_nst() [3/6]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nst (const unsigned & n_p) const inline virtual
Access function for the pressure values at local pressure node n_p (const version)
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Get the nodal value associated with the n_p-th pressure dof
       return this->nodal_value(Pconv[n_p], this->p_nodal_index_nst());
     } // End of p_nst
References oomph::FiniteElement::nodal_value(), and oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst().
p_nst() [4/6]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nst (const unsigned & t, const unsigned & n_p) const inline virtual
Access function for the pressure values at local pressure node n_p (const version)
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Return the pressure value of the n_p-th pressure dof at time-level t
       return this->nodal_value(t, Pconv[n_p], this->p_nodal_index_nst());
     } // End of p_nst
References oomph::FiniteElement::nodal_value(), oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst(), and oomph::QTaylorHoodSpaceTimeElement< DIM >::Pconv.
p_nst() [5/6]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nst (const unsigned & t, const unsigned & n_p) const inline virtual
Access function for the pressure values at local pressure node n_p (const version)
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Return the pressure value of the n_p-th pressure dof at time-level t
       return this->nodal_value(t, Pconv[n_p], this->p_nodal_index_nst());
     } // End of p_nst
References oomph::FiniteElement::nodal_value(), oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst(), and oomph::QTaylorHoodSpaceTimeElement< DIM >::Pconv.
p_nst() [6/6]
template<unsigned DIM> double oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nst (const unsigned & t, const unsigned & n_p) const inline virtual
Access function for the pressure values at local pressure node n_p (const version)
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
     {
       // Return the pressure value of the n_p-th pressure dof at time-level t
       return this->nodal_value(t, Pconv[n_p], this->p_nodal_index_nst());
     } // End of p_nst
References oomph::FiniteElement::nodal_value(), oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst(), and oomph::QTaylorHoodSpaceTimeElement< DIM >::Pconv.
Pconv() [1/3]
const unsigned oomph::QTaylorHoodSpaceTimeElement< 2 >::Pconv protected
Pconv() [2/3]
const unsigned oomph::QTaylorHoodSpaceTimeElement< 2 >::Pconv protected
Pconv() [3/3]
const unsigned oomph::QTaylorHoodSpaceTimeElement< 2 >::Pconv protected
pshape_nst() [1/9]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi) const inline virtual
Pressure shape functions at local coordinate s.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
Referenced by oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::interpolating_basis().
pshape_nst() [2/9]
void oomph::QTaylorHoodSpaceTimeElement< 2 >::pshape_nst (const Vector< double > & s, Shape & psi) const inline virtual
2D (in space): Pressure shape functions
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
   {
     // Local storage for the shape function value (in the x-direction)
     double psi1[2];
     // Local storage for the shape function value (in the y-direction)
     double psi2[2];
     // Local storage for the shape function value (in the z-direction)
     double psi3[3];
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[0], psi1);
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[1], psi2);
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<3>(s[2], psi3);
     //--------------------------------------------------------------------
     // Now let's loop over the nodal points in the element with s1 being
     // the "x" coordinate, s2 being the "y" coordinate and s3 being the
     // "z" coordinate:
     //--------------------------------------------------------------------
     // Loop over the points in the t-direction
     for (unsigned i = 0; i < 3; i++)
     {
       // Loop over the points in the y-direction
       for (unsigned j = 0; j < 2; j++)
       {
         // Loop over the points in the x-direction
         for (unsigned k = 0; k < 2; k++)
         {
           // Multiply the three 1D functions together to get the 3D function
           psi[4 * i + 2 * j + k] = psi3[i] * psi2[j] * psi1[k];
         }
       } // for (unsigned j=0;j<2;j++)
     } // for (unsigned i=0;i<3;i++)
   } // End of pshape_nst
References i, j, k, s, oomph::OneDimLagrange::shape< 2 >(), and oomph::OneDimLagrange::shape< 3 >().
pshape_nst() [3/9]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi) const inline virtual
Pressure shape functions at local coordinate s.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
pshape_nst() [4/9]
void oomph::QTaylorHoodSpaceTimeElement< 2 >::pshape_nst (const Vector< double > & s, Shape & psi) const inline virtual
2D (in space): Pressure shape functions
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
   {
     // Local storage for the shape function value (in the x-direction)
     double psi1[2];
     // Local storage for the shape function value (in the y-direction)
     double psi2[2];
     // Local storage for the shape function value (in the z-direction)
     double psi3[2];
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[0], psi1);
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[1], psi2);
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[2], psi3);
     //--------------------------------------------------------------------
     // Now let's loop over the nodal points in the element with s1 being
     // the "x" coordinate, s2 being the "y" coordinate and s3 being the
     // "z" coordinate:
     //--------------------------------------------------------------------
     // Loop over the points in the z-direction
     for (unsigned i = 0; i < 2; i++)
     {
       // Loop over the points in the y-direction
       for (unsigned j = 0; j < 2; j++)
       {
         // Loop over the points in the x-direction
         for (unsigned k = 0; k < 2; k++)
         {
           // Multiply the three 1D functions together to get the 3D function
           psi[4 * i + 2 * j + k] = psi3[i] * psi2[j] * psi1[k];
         }
       } // for (unsigned j=0;j<2;j++)
     } // for (unsigned i=0;i<2;i++)
   } // End of pshape_nst
References i, j, k, s, and oomph::OneDimLagrange::shape< 2 >().
pshape_nst() [5/9]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi) const inline virtual
Pressure shape functions at local coordinate s.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
pshape_nst() [6/9]
void oomph::QTaylorHoodSpaceTimeElement< 2 >::pshape_nst (const Vector< double > & s, Shape & psi) const inline virtual
2D (in space): Pressure shape functions
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
   {
     // Local storage for the shape function value (in the x-direction)
     double psi1[2];
     // Local storage for the shape function value (in the y-direction)
     double psi2[2];
     // Local storage for the shape function value (in the z-direction)
     double psi3[2];
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[0], psi1);
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[1], psi2);
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[2], psi3);
     //--------------------------------------------------------------------
     // Now let's loop over the nodal points in the element with s1 being
     // the "x" coordinate, s2 being the "y" coordinate and s3 being the
     // "z" coordinate:
     //--------------------------------------------------------------------
     // Loop over the points in the z-direction
     for (unsigned i = 0; i < 2; i++)
     {
       // Loop over the points in the y-direction
       for (unsigned j = 0; j < 2; j++)
       {
         // Loop over the points in the x-direction
         for (unsigned k = 0; k < 2; k++)
         {
           // Multiply the three 1D functions together to get the 3D function
           psi[4 * i + 2 * j + k] = psi3[i] * psi2[j] * psi1[k];
         }
       } // for (unsigned j=0;j<2;j++)
     } // for (unsigned i=0;i<2;i++)
   } // End of pshape_nst
References i, j, k, s, and oomph::OneDimLagrange::shape< 2 >().
pshape_nst() [7/9]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const inline virtual
Pressure shape and test functions at local coordinte s.
Pressure shape and test functions.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
   {
     // Call the pressure shape functions
     pshape_nst(s, psi);
     // Call the pressure test functions
     ptest_nst(s, test);
   } // End of pshape_nst
References s.
pshape_nst() [8/9]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const inline virtual
Pressure shape and test functions at local coordinte s.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
pshape_nst() [9/9]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const inline virtual
Pressure shape and test functions at local coordinte s.
Implements oomph::SpaceTimeNavierStokesEquations< DIM >.
ptest_nst() [1/4]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::ptest_nst (const Vector< double > & s, Shape & psi) const inline
Pressure test functions at local coordinate s.
ptest_nst() [2/4]
template<unsigned DIM> void oomph::QTaylorHoodSpaceTimeElement< DIM >::ptest_nst (const Vector< double > & s, Shape & psi) const inline
Pressure test functions at local coordinate s.
ptest_nst() [3/4]
void oomph::QTaylorHoodSpaceTimeElement< 2 >::ptest_nst (const Vector< double > & s, Shape & test) const inline
2D (in space): Pressure shape functions
   {
     // Local storage for the shape function value (in the x-direction)
     double test1[2];
     // Local storage for the shape function value (in the y-direction)
     double test2[2];
     // Local storage for the shape function value (in the z-direction)
     double test3[3];
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[0], test1);
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[1], test2);
     // Call the OneDimensional Shape functions
     OneDimDiscontinuousGalerkin::shape<3>(s[2], test3);
     //--------------------------------------------------------------------
     // Now let's loop over the nodal points in the element with s1 being
     // the "x" coordinate, s2 being the "y" coordinate and s3 being the
     // "z" coordinate:
     //--------------------------------------------------------------------
     // Loop over the points in the z-direction
     for (unsigned i = 0; i < 3; i++)
     {
       // Loop over the points in the y-direction
       for (unsigned j = 0; j < 2; j++)
       {
         // Loop over the points in the x-direction
         for (unsigned k = 0; k < 2; k++)
         {
           // Multiply the three 1D functions together to get the 3D function
           test[4 * i + 2 * j + k] = test3[i] * test2[j] * test1[k];
         }
       } // for (unsigned j=0;j<2;j++)
     } // for (unsigned i=0;i<3;i++)
   } // End of ptest_nst
References i, j, k, s, oomph::OneDimLagrange::shape< 2 >(), oomph::OneDimLagrange::shape< 3 >(), test1(), and test2().
ptest_nst() [4/4]
void oomph::QTaylorHoodSpaceTimeElement< 2 >::ptest_nst (const Vector< double > & s, Shape & test) const inline
2D (in space): Pressure shape functions
   {
     // Local storage for the shape function value (in the x-direction)
     double test1[2];
     // Local storage for the shape function value (in the y-direction)
     double test2[2];
     // Local storage for the shape function value (in the z-direction)
     double test3[2];
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[0], test1);
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<2>(s[1], test2);
     // Call the OneDimensional Shape functions
     OneDimDiscontinuousGalerkin::shape<2>(s[2], test3);
     //--------------------------------------------------------------------
     // Now let's loop over the nodal points in the element with s1 being
     // the "x" coordinate, s2 being the "y" coordinate and s3 being the
     // "z" coordinate:
     //--------------------------------------------------------------------
     // Loop over the points in the z-direction
     for (unsigned i = 0; i < 2; i++)
     {
       // Loop over the points in the y-direction
       for (unsigned j = 0; j < 2; j++)
       {
         // Loop over the points in the x-direction
         for (unsigned k = 0; k < 2; k++)
         {
           // Multiply the three 1D functions together to get the 3D function
           test[4 * i + 2 * j + k] = test3[i] * test2[j] * test1[k];
         }
       } // for (unsigned j=0;j<2;j++)
     } // for (unsigned i=0;i<2;i++)
   } // End of ptest_nst
References i, j, k, s, oomph::OneDimLagrange::shape< 2 >(), test1(), and test2().
required_nvalue() [1/3]
template<unsigned DIM> virtual unsigned oomph::QTaylorHoodSpaceTimeElement< DIM >::required_nvalue (const unsigned & n) const inline virtual
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.
     {
       // Return the appropriate entry from Initial_Nvalue
       return Initial_Nvalue[n];
     } // End of required_nvalue
References oomph::QTaylorHoodSpaceTimeElement< DIM >::Initial_Nvalue, and n.
required_nvalue() [2/3]
template<unsigned DIM> virtual unsigned oomph::QTaylorHoodSpaceTimeElement< DIM >::required_nvalue (const unsigned & n) const inline virtual
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.
     {
       // Return the appropriate entry from Initial_Nvalue
       return Initial_Nvalue[n];
     } // End of required_nvalue
References n.
required_nvalue() [3/3]
template<unsigned DIM> virtual unsigned oomph::QTaylorHoodSpaceTimeElement< DIM >::required_nvalue (const unsigned & n) const inline virtual
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.
     {
       // Return the appropriate entry from Initial_Nvalue
       return Initial_Nvalue[n];
     } // End of required_nvalue
References oomph::QTaylorHoodSpaceTimeElement< DIM >::Initial_Nvalue, and n.
Member Data Documentation
Initial_Nvalue
template<unsigned DIM> static const unsigned oomph::QTaylorHoodSpaceTimeElement< DIM >::Initial_Nvalue static private
Static array of ints to hold number of variables at node.
Referenced by oomph::QTaylorHoodSpaceTimeElement< DIM >::required_nvalue().
Pconv
template<unsigned DIM> static const unsigned oomph::QTaylorHoodSpaceTimeElement< DIM >::Pconv static protected
Static array of ints to hold conversion from pressure node numbers to actual node numbers
Referenced by oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nst(), and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pressure_node_pt().
The documentation for this class was generated from the following files:
discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h
discontinuous_galerkin_spacetime_navier_stokes_elements.h
spacetime_navier_stokes_elements.h
discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc
discontinuous_galerkin_spacetime_navier_stokes_elements.cc
spacetime_navier_stokes_elements.cc