MercuryDPM: oomph::DShape Class Reference
oomph::DShape Class Reference
#include <shape.h>
Public Member Functions
DShape (const unsigned &N, const unsigned &P)
Constructor with two parameters: a single-index shape function.
DShape (const unsigned &N, const unsigned &M, const unsigned &P)
Constructor with three paramters: a two-index shape function.
DShape ()
DShape (const DShape &dshape)=delete
Broken copy constructor.
void operator= (const DShape &dshape)
void operator= (DShape *const &dshape_pt)
~DShape ()
Destructor, clean up the memory allocated by this object.
void resize (const unsigned &N, const unsigned &P, const unsigned &M=1)
double & operator() (const unsigned &i, const unsigned &k)
Overload the round bracket operator for access to the data.
const double & operator() (const unsigned &i, const unsigned &k) const
Overload the round bracket operator (const version)
double & operator() (const unsigned &i, const unsigned &j, const unsigned &k)
Overload the round bracket operator, with 3 indices.
const double & operator() (const unsigned &i, const unsigned &j, const unsigned &k) const
Overload the round bracket operator (const version)
double & raw_direct_access (const unsigned long &i)
const double & raw_direct_access (const unsigned long &i) const
unsigned offset (const unsigned long &i, const unsigned long &j) const
unsigned long nindex1 () const
Return the range of index 1 of the derivatives of the shape functions.
unsigned long nindex2 () const
Return the range of index 2 of the derivatives of the shape functions.
unsigned long nindex3 () const
Return the range of index 3 of the derivatives of the shape functions.
Private Member Functions
void range_check (const unsigned &i, const unsigned &j, const unsigned &k) const
Private function that checks whether the indices are in range.
Private Attributes
double * DPsi
double * Allocated_storage
unsigned Index1
Size of the first index of the shape function.
unsigned Index2
Size of the second index of the shape function.
unsigned Index3
Size of the third index of the shape function.
Detailed Description
A Class for the derivatives of shape functions The class design is essentially the same as Shape, but there is on additional index that is used to indicate the coordinate direction in which the derivative is taken.
Constructor & Destructor Documentation
DShape() [1/4]
oomph::DShape::DShape (const unsigned & N, const unsigned & P) inline
Constructor with two parameters: a single-index shape function.
       : Index1(N), Index2(1), Index3(P)
     {
       Allocated_storage = new double[N * P];
       DPsi = Allocated_storage;
     }
References Allocated_storage, DPsi, N, and Global_Physical_Variables::P.
DShape() [2/4]
oomph::DShape::DShape (const unsigned & N, const unsigned & M, const unsigned & P) inline
Constructor with three paramters: a two-index shape function.
       : Index1(N), Index2(M), Index3(P)
     {
       Allocated_storage = new double[N * M * P];
       DPsi = Allocated_storage;
     }
References Allocated_storage, DPsi, N, and Global_Physical_Variables::P.
DShape() [3/4]
oomph::DShape::DShape () inline
Default constructor - just assigns a null pointers and zero index sizes.
 : DPsi(0), Allocated_storage(0), Index1(0), Index2(0), Index3(0) {}
DShape() [4/4]
oomph::DShape::DShape (const DShape & dshape) delete
Broken copy constructor.
~DShape()
oomph::DShape::~DShape () inline
Destructor, clean up the memory allocated by this object.
     {
       delete[] Allocated_storage;
       Allocated_storage = 0;
     }
References Allocated_storage.
Member Function Documentation
nindex1()
unsigned long oomph::DShape::nindex1 () const inline
Return the range of index 1 of the derivatives of the shape functions.
     {
       return Index1;
     }
References Index1.
Referenced by oomph::ClampedHermiteShellBoundaryConditionElement::dshape_local(), oomph::FiniteElement::transform_derivatives(), oomph::FiniteElement::transform_derivatives_diagonal(), oomph::FiniteElement::transform_second_derivatives_diagonal(), and oomph::FiniteElement::transform_second_derivatives_template().
nindex2()
unsigned long oomph::DShape::nindex2 () const inline
Return the range of index 2 of the derivatives of the shape functions.
     {
       return Index2;
     }
References Index2.
Referenced by oomph::ClampedHermiteShellBoundaryConditionElement::dshape_local(), oomph::FiniteElement::transform_derivatives(), oomph::FiniteElement::transform_derivatives_diagonal(), oomph::FiniteElement::transform_second_derivatives_diagonal(), and oomph::FiniteElement::transform_second_derivatives_template().
nindex3()
unsigned long oomph::DShape::nindex3 () const inline
Return the range of index 3 of the derivatives of the shape functions.
     {
       return Index3;
     }
References Index3.
Referenced by oomph::ClampedHermiteShellBoundaryConditionElement::dshape_local().
offset()
unsigned oomph::DShape::offset (const unsigned long & i, const unsigned long & j) const inline
Caculate the offset in flat-packed C-style, column-major format, required for a given i,j. WARNING: Only for experienced users. Only use this if raw speed is of the essence, as in the solid mechanics problems.
     {
       return (i * Index2 + j) * Index3 + 0;
     }
References i, Index2, Index3, and j.
Referenced by oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::PVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::ScaleCoupledElement< ELEMENT >::fill_in_generic_contribution_to_residuals_pvd(), oomph::VolumeCoupledElement< ELEMENT >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), and oomph::PVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure().
operator()() [1/4]
double& oomph::DShape::operator() (const unsigned & i, const unsigned & j, const unsigned & k) inline
Overload the round bracket operator, with 3 indices.
     {
 #ifdef RANGE_CHECKING
       range_check(i, j, k);
 #endif
       return DPsi[(i * Index2 + j) * Index3 + k];
     }
References DPsi, i, Index2, Index3, j, k, and range_check().
operator()() [2/4]
const double& oomph::DShape::operator() (const unsigned & i, const unsigned & j, const unsigned & k) const inline
Overload the round bracket operator (const version)
     {
 #ifdef RANGE_CHECKING
       range_check(i, j, k);
 #endif
       return DPsi[(i * Index2 + j) * Index3 + k];
     }
References DPsi, i, Index2, Index3, j, k, and range_check().
operator()() [3/4]
double& oomph::DShape::operator() (const unsigned & i, const unsigned & k) inline
Overload the round bracket operator for access to the data.
     {
 #ifdef RANGE_CHECKING
       range_check(i, 0, k);
 #endif
       return DPsi[i * Index2 * Index3 + k];
     }
References DPsi, i, Index2, Index3, k, and range_check().
operator()() [4/4]
const double& oomph::DShape::operator() (const unsigned & i, const unsigned & k) const inline
Overload the round bracket operator (const version)
     {
 #ifdef RANGE_CHECKING
       range_check(i, 0, k);
 #endif
       return DPsi[i * Index2 * Index3 + k];
     }
References DPsi, i, Index2, Index3, k, and range_check().
operator=() [1/2]
void oomph::DShape::operator= (const DShape & dshape) inline
The assignment operator does a shallow copy (resets the pointer to the data)
     {
 #ifdef PARANOID
       // Check the dimensions
       if ((dshape.Index1 != Index1) || (dshape.Index2 != Index2) ||
           (dshape.Index3 != Index3))
       {
         std::ostringstream error_stream;
         error_stream << "Cannot assign DShape object:" << std::endl
                      << "Indices do not match "
                      << "LHS: " << Index1 << " " << Index2 << " " << Index3
                      << ", RHS: " << dshape.Index1 << " " << dshape.Index2
                      << " " << dshape.Index3 << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       DPsi = dshape.DPsi;
     }
References DPsi, oomph::OneDimHermite::dshape(), Index1, Index2, Index3, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
operator=() [2/2]
void oomph::DShape::operator= (DShape *const & dshape_pt) inline
The assignment operator does a shallow copy (resets the pointer to the data)
     {
 #ifdef PARANOID
       // Check the dimensions
       if ((dshape_pt->Index1 != Index1) || (dshape_pt->Index2 != Index2) ||
           (dshape_pt->Index3 != Index3))
       {
         std::ostringstream error_stream;
         error_stream << "Cannot assign Shape object:" << std::endl
                      << "Indices do not match "
                      << "LHS: " << Index1 << " " << Index2 << " " << Index3
                      << ", RHS: " << dshape_pt->Index1 << " "
                      << dshape_pt->Index2 << " " << dshape_pt->Index3
                      << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       DPsi = dshape_pt->DPsi;
     }
References DPsi, Index1, Index2, Index3, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
range_check()
void oomph::DShape::range_check (const unsigned & i, const unsigned & j, const unsigned & k) const inline private
Private function that checks whether the indices are in range.
     {
       // Check the first index
       if ((i >= Index1) || (j >= Index2) || (k >= Index3))
       {
         std::ostringstream error_stream;
         error_stream << "Range Error: ";
         if (i >= Index1)
         {
           error_stream << i << " is not in the range (0," << Index1 - 1 << ")"
                        << std::endl;
         }
         if (j >= Index2)
         {
           error_stream << j << " is not in the range (0," << Index2 - 1 << ")"
                        << std::endl;
         }
         if (k >= Index3)
         {
           error_stream << k << " is not in the range (0," << Index3 - 1 << ")"
                        << std::endl;
         }
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
     }
References i, Index1, Index2, Index3, j, k, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by operator()().
raw_direct_access() [1/2]
double& oomph::DShape::raw_direct_access (const unsigned long & i) inline
Direct access to internal storage of data in flat-packed C-style column-major format. WARNING: Only for experienced users. Only use this if raw speed is of the essence, as in the solid mechanics problems.
     {
       return DPsi[i];
     }
References DPsi, and i.
Referenced by oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::PVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::ScaleCoupledElement< ELEMENT >::fill_in_generic_contribution_to_residuals_pvd(), oomph::VolumeCoupledElement< ELEMENT >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), and oomph::PVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure().
raw_direct_access() [2/2]
const double& oomph::DShape::raw_direct_access (const unsigned long & i) const inline
Direct access to internal storage of data in flat-packed C-style column-major format. WARNING: Only for experienced users. Only use this if raw speed is of the essence, as in the solid mechanics problems.
     {
       return DPsi[i];
     }
References DPsi, and i.
resize()
void oomph::DShape::resize (const unsigned & N, const unsigned & P, const unsigned & M = 1) inline
Change the size of the storage. Note that (for some strange reason) index2 is the "optional" index, to conform with the existing constructor.
     {
       // Clear old storage
       delete[] Allocated_storage;
       Allocated_storage = 0;
       DPsi = 0;
       // Allocate new storage
       Index1 = N;
       Index2 = M;
       Index3 = P;
       Allocated_storage = new double[N * M * P];
       DPsi = Allocated_storage;
     }
References Allocated_storage, DPsi, Index1, Index2, Index3, N, and Global_Physical_Variables::P.
Member Data Documentation
Allocated_storage
double* oomph::DShape::Allocated_storage private
Pointer that addresses the storage allocated by the object on construction. This will be the same as DPsi if the object is not copied.
Referenced by DShape(), resize(), and ~DShape().
DPsi
double* oomph::DShape::DPsi private
Pointer that addresses the storage that will be used to read and set the shape-function derivatives. The values are packed into a flat array of doubles.
Referenced by DShape(), operator()(), operator=(), raw_direct_access(), and resize().
Index1
unsigned oomph::DShape::Index1 private
Size of the first index of the shape function.
Referenced by nindex1(), operator=(), range_check(), and resize().
Index2
unsigned oomph::DShape::Index2 private
Size of the second index of the shape function.
Referenced by nindex2(), offset(), operator()(), operator=(), range_check(), and resize().
Index3
unsigned oomph::DShape::Index3 private
Size of the third index of the shape function.
Referenced by nindex3(), offset(), operator()(), operator=(), range_check(), and resize().
The documentation for this class was generated from the following file:
shape.h