MercuryDPM: ThermalInteraction< NormalForceInteraction > Class Template Reference
ThermalInteraction< NormalForceInteraction > Class Template Reference
#include <ThermalInteraction.h>
Public Types
typedef ThermalSpecies< typename NormalForceInteraction::SpeciesType > SpeciesType
Public Member Functions
ThermalInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
Constructor.
ThermalInteraction ()
Default Constructor.
ThermalInteraction (const ThermalInteraction &p)
Copy constructor.
virtual ~ThermalInteraction ()
Destructor.
void computeNormalForce ()
Computes the normal forces due to linear plastic visco elastic interaction.
Member Typedef Documentation
SpeciesType
template<class NormalForceInteraction > typedef ThermalSpecies<typename NormalForceInteraction::SpeciesType> ThermalInteraction< NormalForceInteraction >::SpeciesType
Constructor & Destructor Documentation
ThermalInteraction() [1/3]
template<class NormalForceInteraction > ThermalInteraction< NormalForceInteraction >::ThermalInteraction (BaseInteractable * P, BaseInteractable * I, unsigned timeStamp)
Constructor.
         : BaseInteraction(P, I, timeStamp), NormalForceInteraction(P, I, timeStamp)
 {}
ThermalInteraction() [2/3]
template<class NormalForceInteraction > ThermalInteraction< NormalForceInteraction >::ThermalInteraction
Default Constructor.
         : BaseInteraction(), NormalForceInteraction()
 {}
ThermalInteraction() [3/3]
template<class NormalForceInteraction > ThermalInteraction< NormalForceInteraction >::ThermalInteraction (const ThermalInteraction< NormalForceInteraction > & p)
Copy constructor.
         : BaseInteraction(p), NormalForceInteraction(p)
 {}
~ThermalInteraction()
template<class NormalForceInteraction > ThermalInteraction< NormalForceInteraction >::~ThermalInteraction virtual
Destructor.
 {}
Member Function Documentation
computeNormalForce()
template<class NormalForceInteraction > void ThermalInteraction< NormalForceInteraction >::computeNormalForce
Computes the normal forces due to linear plastic visco elastic interaction.
Compute temperature change due to heat conduction between particles
 {
     NormalForceInteraction::computeNormalForce();
     Mdouble radius = 2.0 * NormalForceInteraction::getEffectiveRadius();
     Mdouble contactArea = constants::pi * radius * std::max(0.0,NormalForceInteraction::getOverlap());
     const SpeciesType* species = static_cast<const SpeciesType*>(NormalForceInteraction::getBaseSpecies()->getNormalForce());
     ThermalParticle* pParticle = dynamic_cast<ThermalParticle*>(NormalForceInteraction::getP());
     ThermalParticle* iParticle = dynamic_cast<ThermalParticle*>(NormalForceInteraction::getI());
     // if both p and i are particles
     if (pParticle && iParticle)
     {
         /* compute heat transfer rate due to heat conduction, Q=cond*dTemp*area/dist */
         Mdouble heatTransfer = species->getThermalConductivity()
                                * (pParticle->getTemperature() - iParticle->getTemperature())
                                * contactArea / NormalForceInteraction::getDistance();
         /* m*dT = Q/c*dt */
         Mdouble mdT = heatTransfer / species->getHeatCapacity()
             * NormalForceInteraction::getHandler()->getDPMBase()->getTimeStep();
         pParticle->addTemperature(-mdT * pParticle->getInvMass());
         iParticle->addTemperature(mdT * iParticle->getInvMass());
     }
 }
References Thermal< Particle >::addTemperature(), ThermalSpecies< NormalForceSpecies >::getHeatCapacity(), Thermal< Particle >::getTemperature(), ThermalSpecies< NormalForceSpecies >::getThermalConductivity(), max, constants::pi, and UniformPSDSelfTest::radius.
The documentation for this class was generated from the following file:
ThermalInteraction.h