MercuryDPM: Eigen::internal::lapacke_helpers Namespace Reference
Eigen::internal::lapacke_helpers Namespace Reference
Implementation details and helper functions for the lapacke glue code.
Classes
struct rank_update
struct rank_update< Lower >
struct rank_update< Upper >
struct lapacke_llt
struct lapacke_partial_lu
struct translate_type_imp
struct translate_type_imp< float >
struct translate_type_imp< double >
struct translate_type_imp< std::complex< double > >
struct translate_type_imp< std::complex< float > >
struct WrappingHelper
Helper type to facilitate the wrapping of raw LAPACKE functions for different types into a single, overloaded C++ function. This is achieved in combination with \r EIGEN_MAKE_LAPACKE_WRAPPER.
struct lapacke_hqr
class BDCSVD_LAPACKE
Typedefs
template<typename Scalar >
using translated_type = typename translate_type_imp< Scalar >::type
Given an Eigen types, this is defined to be the corresponding, layout-compatible lapack type.
Functions
template<typename Source , typename Target = translated_type<Source>>
EIGEN_ALWAYS_INLINE auto to_lapack (Source value)
template<typename Source , typename Target = translated_type<Source>>
EIGEN_ALWAYS_INLINE auto to_lapack (Source *value)
EIGEN_ALWAYS_INLINE lapack_int to_lapack (Index index)
template<typename Derived >
EIGEN_ALWAYS_INLINE EIGEN_CONSTEXPR lapack_int lapack_storage_of (const EigenBase< Derived > &)
translates storage order of the given Eigen object to the corresponding lapack constant
template<typename DoubleFn , typename SingleFn , typename DoubleCpxFn , typename SingleCpxFn , typename... Args>
EIGEN_ALWAYS_INLINE auto call_wrapper (DoubleFn df, SingleFn sf, DoubleCpxFn dcf, SingleCpxFn scf, Args &&...args)
template<typename MatrixType_ , int Options>
BDCSVD< MatrixType_, Options > & BDCSVD_wrapper (BDCSVD< MatrixType_, Options > &svd, const MatrixType_ &matrix, int computationOptions)
Detailed Description
Implementation details and helper functions for the lapacke glue code.
Typedef Documentation
translated_type
template<typename Scalar > using Eigen::internal::lapacke_helpers::translated_type = typedef typename translate_type_imp<Scalar>::type
Given an Eigen types, this is defined to be the corresponding, layout-compatible lapack type.
Function Documentation
BDCSVD_wrapper()
template<typename MatrixType_ , int Options> BDCSVD<MatrixType_, Options>& Eigen::internal::lapacke_helpers::BDCSVD_wrapper (BDCSVD< MatrixType_, Options > & svd, const MatrixType_ & matrix, int computationOptions)
{
   // we need to move to the wrapper type and back
   BDCSVD_LAPACKE<MatrixType_, Options> tmpSvd(std::move(svd));
   tmpSvd.compute_impl_lapacke(matrix, computationOptions);
   svd = std::move(tmpSvd);
   return svd;
 }
References Eigen::internal::lapacke_helpers::BDCSVD_LAPACKE< MatrixType_, Options >::compute_impl_lapacke(), matrix(), and svd().
call_wrapper()
template<typename DoubleFn , typename SingleFn , typename DoubleCpxFn , typename SingleCpxFn , typename... Args> EIGEN_ALWAYS_INLINE auto Eigen::internal::lapacke_helpers::call_wrapper (DoubleFn df, SingleFn sf, DoubleCpxFn dcf, SingleCpxFn scf, Args &&... args)
Helper function that generates a WrappingHelper object with the given function pointers and invokes its call method, thus selecting one of the overloads.
See also
EIGEN_MAKE_LAPACKE_WRAPPER
{
   WrappingHelper<DoubleFn, SingleFn, DoubleCpxFn, SingleCpxFn> helper{df, sf, dcf, scf};
   return helper.call(std::forward<Args>(args)...);
 }
References compute_granudrum_aor::args, and Eigen::internal::lapacke_helpers::WrappingHelper< DoubleFn, SingleFn, DoubleCpxFn, SingleCpxFn >::call().
lapack_storage_of()
template<typename Derived > EIGEN_ALWAYS_INLINE EIGEN_CONSTEXPR lapack_int Eigen::internal::lapacke_helpers::lapack_storage_of (const EigenBase< Derived > &)
translates storage order of the given Eigen object to the corresponding lapack constant
{
   return Derived::IsRowMajor ? LAPACK_ROW_MAJOR : LAPACK_COL_MAJOR;
 }
References LAPACK_COL_MAJOR, and LAPACK_ROW_MAJOR.
Referenced by Eigen::internal::lapacke_helpers::BDCSVD_LAPACKE< MatrixType_, Options >::compute_impl_lapacke(), Eigen::internal::lapacke_helpers::lapacke_llt< Scalar, Mode >::EIGEN_STATIC_ASSERT(), and Eigen::internal::lapacke_helpers::lapacke_hqr< MatrixQR, HCoeffs >::run().
to_lapack() [1/3]
EIGEN_ALWAYS_INLINE lapack_int Eigen::internal::lapacke_helpers::to_lapack (Index index)
This function converts the Eigen Index to a lapack index, with possible range checks
See also
internal::convert_index
 { return convert_index<lapack_int>(index); }
to_lapack() [2/3]
template<typename Source , typename Target = translated_type<Source>> EIGEN_ALWAYS_INLINE auto Eigen::internal::lapacke_helpers::to_lapack (Source * value)
This function performs conversions for pointer types corresponding to the translations abovce. This is valid because the translations are between layout-compatible types.
{
   return reinterpret_cast<Target *>(value);
 }
References Eigen::Architecture::Target, and Eigen::value.
to_lapack() [3/3]
template<typename Source , typename Target = translated_type<Source>> EIGEN_ALWAYS_INLINE auto Eigen::internal::lapacke_helpers::to_lapack (Source value)
These functions convert their arguments from Eigen to Lapack types This function performs conversion for any of the translations defined above.
{
   return static_cast<Target>(value);
 }
References Eigen::Architecture::Target, and Eigen::value.
Referenced by Eigen::internal::lapacke_helpers::lapacke_partial_lu< Scalar, StorageOrder >::blocked_lu(), Eigen::internal::lapacke_helpers::BDCSVD_LAPACKE< MatrixType_, Options >::compute_impl_lapacke(), Eigen::internal::lapacke_helpers::lapacke_llt< Scalar, Mode >::EIGEN_STATIC_ASSERT(), and Eigen::internal::lapacke_helpers::lapacke_hqr< MatrixQR, HCoeffs >::run().