MercuryDPM: GlobalVariables Namespace Reference
GlobalVariables Namespace Reference
Functions
void activator_inhibitor_reaction (const Vector< double > &C, Vector< double > &R)
void activator_inhibitor_reaction_derivative (const Vector< double > &C, DenseMatrix< double > &dRdC)
Derivative of simple reaction kinetics above.
Variables
Vector< double > Tau (2, 1.0)
The vector of timescales.
Vector< double > D (2, 1.0)
The vector of diffusion coefficients.
double A = -0.1
Bifurcation (loss) parameter.
const double pi = MathematicalConstants::Pi
Function Documentation
activator_inhibitor_reaction()
void GlobalVariables::activator_inhibitor_reaction (const Vector< double > & C, Vector< double > & R)
  {
   //Inhibitor loss is linearly proportional to concentrations of activator
   //and inhibitor
   R[0] = C[0] + C[1] - A;
   //Activator growth is linearly proportional to activator and inhibitor
   //and loss is self-catalysed at a cubic rate
   R[1] = C[1]*C[1]*C[1] - C[1] - C[0];
  }
References A, and R.
Referenced by ActivatorInhibitorProblem< ELEMENT >::ActivatorInhibitorProblem(), RefineableActivatorInhibitorProblem< ELEMENT >::complete_problem_setup(), RefineableActivatorInhibitorProblem< ELEMENT >::RefineableActivatorInhibitorProblem(), and RefineableOneDAdvectionDiffusionReactionProblem< ELEMENT >::RefineableOneDAdvectionDiffusionReactionProblem().
activator_inhibitor_reaction_derivative()
void GlobalVariables::activator_inhibitor_reaction_derivative (const Vector< double > & C, DenseMatrix< double > & dRdC)
Derivative of simple reaction kinetics above.
Derivative of simple reaction kinetics.
  {
   dRdC(0,0) = 1.0; dRdC(0,1) = 1.0;
   dRdC(1,0) = -1.0; dRdC(1,1) = 3.0*C[1]*C[1] - 1.0;
  }
Referenced by ActivatorInhibitorProblem< ELEMENT >::ActivatorInhibitorProblem(), RefineableActivatorInhibitorProblem< ELEMENT >::complete_problem_setup(), RefineableActivatorInhibitorProblem< ELEMENT >::RefineableActivatorInhibitorProblem(), and RefineableOneDAdvectionDiffusionReactionProblem< ELEMENT >::RefineableOneDAdvectionDiffusionReactionProblem().
Variable Documentation
A
double GlobalVariables::A = -0.1
Bifurcation (loss) parameter.
Referenced by activator_inhibitor_reaction(), main(), RefineableOneDAdvectionDiffusionReactionProblem< ELEMENT >::set_initial_condition(), RefineableActivatorInhibitorProblem< ELEMENT >::set_initial_condition(), and ActivatorInhibitorProblem< ELEMENT >::timestep().
D
Vector< double > GlobalVariables::D (2 , 1. 0)
The vector of diffusion coefficients.
Referenced by ActivatorInhibitorProblem< ELEMENT >::ActivatorInhibitorProblem(), RefineableActivatorInhibitorProblem< ELEMENT >::complete_problem_setup(), main(), RefineableActivatorInhibitorProblem< ELEMENT >::RefineableActivatorInhibitorProblem(), and RefineableOneDAdvectionDiffusionReactionProblem< ELEMENT >::RefineableOneDAdvectionDiffusionReactionProblem().
pi
const double GlobalVariables::pi = MathematicalConstants::Pi
Referenced by ActivatorInhibitorProblem< ELEMENT >::timestep().
Tau
Vector< double > GlobalVariables::Tau (2 , 1. 0)
The vector of timescales.
Referenced by ActivatorInhibitorProblem< ELEMENT >::ActivatorInhibitorProblem(), RefineableActivatorInhibitorProblem< ELEMENT >::complete_problem_setup(), main(), RefineableActivatorInhibitorProblem< ELEMENT >::RefineableActivatorInhibitorProblem(), and RefineableOneDAdvectionDiffusionReactionProblem< ELEMENT >::RefineableOneDAdvectionDiffusionReactionProblem().