MercuryDPM: ClusterGenerator Class Reference
ClusterGenerator Class Reference
This class allows the user to create clusters of particles. All particles will be of LinearPlasticViscoelasticSpecies and will have a final overlap defined by the user.
#include <ClusterGenerator.h>
Public Member Functions
ClusterGenerator ()
This constructor initializes all variables to default values. After initialization all values are passed to ClusterDPM with setters.
~ClusterGenerator ()
Default destructor.
void create ()
runs the simulation that creates the cluster.
Public Attributes
BaseCluster clusterProperties
ParticleHandler fakeParticleHandler
Private Attributes
Vec3D position_
Mdouble collisionTimeOverTimeStep_
Ratio between collision time and time step: should be at least 50.
Mdouble sizeDispersityParticle_
Size dispersity of particles: must be between 0 and 1.
int nParticles_
Total number of particles.
unsigned int idCluster_
Total number of particles.
Mdouble clusterSizeSafetyFactor_
safety factor for the initial size of the cluster: this must be greater than 1.
Mdouble velocityDampingModulus_
Value of damping modulus for velocity.
int internalStructureGridLength_
Number of points used for creating internal structure's grid.
Mdouble energyRatioTolerance_
Energy ratio threshold under wich the simulation can be considered static.
bool isCdatOutputOn_
bool used to define whether or not cluster data output must be created.
bool isOverlOutputOn_
bool used to define whether or not overlap data output must be created.
bool isAmatOutputOn_
bool used to define whether or not adjacency matrix output must be created.
bool isIntStrucOutputOn_
bool used to define whether or not cluster internal structure output must be created.
bool isVtkOutputOn_
bool used to define whether or not vtk output must be created.
bool isDataOutputOn_
bool used to define whether or not data output must be created.
bool isRestartOutputOn_
bool used to define whether or not restart output must be created.
bool isFStatOutputOn_
bool used to define whether or not fStat output must be created.
bool isEneOutputOn_
bool used to define whether or not eneOutput output must be created.
bool restartSelfTest_
bool used to define whether or not the restart self test is being computed.
Detailed Description
This class allows the user to create clusters of particles. All particles will be of LinearPlasticViscoelasticSpecies and will have a final overlap defined by the user.
Constructor & Destructor Documentation
ClusterGenerator()
ClusterGenerator::ClusterGenerator ()
This constructor initializes all variables to default values. After initialization all values are passed to ClusterDPM with setters.
This constructor initializes all variables to default values. After initialization all values are passed to ClusterDPM with setters. IMPORTANT: radiusParticle here is not initialized nor passed to ClusterDPM in order to force the user to set it, and same is for the species.
 {
     /*
      * ----------------------------------------------------
      *      Initializing variables to default values
      * ----------------------------------------------------
      */
     //Position
     position_={0,0,0};
     // Time
     collisionTimeOverTimeStep_ = 51;
     // Particles
     sizeDispersityParticle_ = 0.0;
     nParticles_ = 100;
     // Cluster
     clusterSizeSafetyFactor_ = 2.0;
     idCluster_ = 0;
     // Central force
     velocityDampingModulus_ = 0.9;
     // Data analysis
     internalStructureGridLength_ = 300;
     // Energy
     energyRatioTolerance_ = 1.0e-8;
     // File
     isCdatOutputOn_ = true;//true;
     isOverlOutputOn_ = true;//true;
     isAmatOutputOn_ = false;//true;
     isIntStrucOutputOn_ = false; // Computational intensive
     isVtkOutputOn_ = false;
     isDataOutputOn_= true;
     isRestartOutputOn_ = false;//true;
     isFStatOutputOn_ = false;
     isEneOutputOn_ = false;
     // Restart self test
     restartSelfTest_ = false;
     /*
      * ----------------------------------------------------
      *           Passing values to BaseCluster
      * ----------------------------------------------------
      */
     clusterProperties.setCollisionTimeOverTimeStep(collisionTimeOverTimeStep_);
     clusterProperties.setSizeDispersityParticle(sizeDispersityParticle_);
     clusterProperties.setNumberOfParticles(nParticles_);
     clusterProperties.setClusterId(idCluster_);
     clusterProperties.setVelocityDampingModulus(velocityDampingModulus_);
     clusterProperties.setInternalStructureGridLength(internalStructureGridLength_);
     clusterProperties.setEnergyRatioTolerance(energyRatioTolerance_);
     clusterProperties.doCdatOutput(isCdatOutputOn_);
     clusterProperties.doOverlOutput(isOverlOutputOn_);
     clusterProperties.doAmatOutput(isAmatOutputOn_);
     clusterProperties.doIntStrucOutput(isIntStrucOutputOn_);
     clusterProperties.doVtkOutput(isVtkOutputOn_);
     clusterProperties.doRestartOutput(isRestartOutputOn_);
     clusterProperties.doFStatOutput(isFStatOutputOn_);
     clusterProperties.doEneOutput(isEneOutputOn_);
     logger(DEBUG, "ClusterGenerator::ClusterGenerator() finished");
 }
References clusterProperties, clusterSizeSafetyFactor_, collisionTimeOverTimeStep_, DEBUG, BaseCluster::doAmatOutput(), BaseCluster::doCdatOutput(), BaseCluster::doEneOutput(), BaseCluster::doFStatOutput(), BaseCluster::doIntStrucOutput(), BaseCluster::doOverlOutput(), BaseCluster::doRestartOutput(), BaseCluster::doVtkOutput(), energyRatioTolerance_, idCluster_, internalStructureGridLength_, isAmatOutputOn_, isCdatOutputOn_, isDataOutputOn_, isEneOutputOn_, isFStatOutputOn_, isIntStrucOutputOn_, isOverlOutputOn_, isRestartOutputOn_, isVtkOutputOn_, logger, nParticles_, position_, restartSelfTest_, BaseCluster::setClusterId(), BaseCluster::setCollisionTimeOverTimeStep(), BaseCluster::setEnergyRatioTolerance(), BaseCluster::setNumberOfParticles(), BaseCluster::setSizeDispersityParticle(), BaseCluster::setVelocityDampingModulus(), sizeDispersityParticle_, and velocityDampingModulus_.
~ClusterGenerator()
ClusterGenerator::~ClusterGenerator ()
Default destructor.
Default destructor
 {
     logger(DEBUG, "ClusterGenerator::~ClusterGenerator() finished");
 }
References DEBUG, and logger.
Member Function Documentation
create()
void ClusterGenerator::create ()
runs the simulation that creates the cluster.
runs the simulation that creates the cluster.
 {
     clusterProperties.solve();
 }
References clusterProperties, and DPMBase::solve().
Member Data Documentation
clusterProperties
BaseCluster ClusterGenerator::clusterProperties
Referenced by ClusterGenerator(), and create().
clusterSizeSafetyFactor_
Mdouble ClusterGenerator::clusterSizeSafetyFactor_ private
safety factor for the initial size of the cluster: this must be greater than 1.
Referenced by ClusterGenerator().
collisionTimeOverTimeStep_
Mdouble ClusterGenerator::collisionTimeOverTimeStep_ private
Ratio between collision time and time step: should be at least 50.
Referenced by ClusterGenerator().
energyRatioTolerance_
Mdouble ClusterGenerator::energyRatioTolerance_ private
Energy ratio threshold under wich the simulation can be considered static.
Referenced by ClusterGenerator().
fakeParticleHandler
ParticleHandler ClusterGenerator::fakeParticleHandler
idCluster_
unsigned int ClusterGenerator::idCluster_ private
Total number of particles.
Referenced by ClusterGenerator().
internalStructureGridLength_
int ClusterGenerator::internalStructureGridLength_ private
Number of points used for creating internal structure's grid.
Referenced by ClusterGenerator().
isAmatOutputOn_
bool ClusterGenerator::isAmatOutputOn_ private
bool used to define whether or not adjacency matrix output must be created.
Referenced by ClusterGenerator().
isCdatOutputOn_
bool ClusterGenerator::isCdatOutputOn_ private
bool used to define whether or not cluster data output must be created.
Referenced by ClusterGenerator().
isDataOutputOn_
bool ClusterGenerator::isDataOutputOn_ private
bool used to define whether or not data output must be created.
Referenced by ClusterGenerator().
isEneOutputOn_
bool ClusterGenerator::isEneOutputOn_ private
bool used to define whether or not eneOutput output must be created.
Referenced by ClusterGenerator().
isFStatOutputOn_
bool ClusterGenerator::isFStatOutputOn_ private
bool used to define whether or not fStat output must be created.
Referenced by ClusterGenerator().
isIntStrucOutputOn_
bool ClusterGenerator::isIntStrucOutputOn_ private
bool used to define whether or not cluster internal structure output must be created.
Referenced by ClusterGenerator().
isOverlOutputOn_
bool ClusterGenerator::isOverlOutputOn_ private
bool used to define whether or not overlap data output must be created.
Referenced by ClusterGenerator().
isRestartOutputOn_
bool ClusterGenerator::isRestartOutputOn_ private
bool used to define whether or not restart output must be created.
Referenced by ClusterGenerator().
isVtkOutputOn_
bool ClusterGenerator::isVtkOutputOn_ private
bool used to define whether or not vtk output must be created.
Referenced by ClusterGenerator().
nParticles_
int ClusterGenerator::nParticles_ private
Total number of particles.
Referenced by ClusterGenerator().
position_
Vec3D ClusterGenerator::position_ private
Referenced by ClusterGenerator().
restartSelfTest_
bool ClusterGenerator::restartSelfTest_ private
bool used to define whether or not the restart self test is being computed.
Referenced by ClusterGenerator().
sizeDispersityParticle_
Mdouble ClusterGenerator::sizeDispersityParticle_ private
Size dispersity of particles: must be between 0 and 1.
Referenced by ClusterGenerator().
velocityDampingModulus_
Mdouble ClusterGenerator::velocityDampingModulus_ private
Value of damping modulus for velocity.
Referenced by ClusterGenerator().
The documentation for this class was generated from the following files:
ClusterGenerator.h
ClusterGenerator.cc