MercuryDPM: ComputeWallTorque Namespace Reference
ComputeWallTorque Namespace Reference
Functions
def main ()
Function Documentation
main()
def ComputeWallTorque.main ()
 def main():
     # the user gives the base of the restart-file name
     if (len(sys.argv)<3):
         raise(Exception("This code needs at least two arguments, e.g. \n\t./ConvertRestartToData.py name.restart wall_id [wall_id_end]"))
     wall_id_begin = int(sys.argv[2])
     if (len(sys.argv)>3):
         wall_id_end = int(sys.argv[3])
     else:
         wall_id_end = wall_id_begin
     # name data and fstat
     restart_file_name = sys.argv[1]
     data_file_name = restart_file_name.replace(".restart",".data")
     fstat_file_name = restart_file_name.replace(".restart",".fstat")
     # open the in- and output files
     data_file = open(data_file_name, 'w')
     fstat_file = open(fstat_file_name, 'w')
     restart_file = open(restart_file_name)
     print("Reading %s" % restart_file_name)
     restart_file = restart_file.readlines()
     #look for number of particles and interactions, get line with first interaction
     i = 0
     while not restart_file[i].startswith('Walls '): i += 1
     num_walls = int(restart_file[i].split()[1])
     index_walls = i + 1
     index_walls_end = index_walls + num_walls
     wall0 = restart_file[index_walls].split()
     torque_index = wall0.index('torque')
     torque_x = 0;
     torque_y = 0;
     torque_z = 0;
     # Read all walls
     for i in range(index_walls, index_walls_end):
         wall = restart_file[i].split()
         wall_id = int(wall[2])
         if wall_id<=wall_id_end and wall_id>=wall_id_begin:
             torque_x += float(wall[torque_index+1])
             torque_y += float(wall[torque_index+2])
             torque_z += float(wall[torque_index+3])
     print("Torque %r %r %r" % (torque_x,torque_y,torque_z))
References int(), Eigen::internal.print(), and oomph::DoubleVectorHelpers.split().