MercuryDPM: SimpleDrumSuperquadrics Class Reference
SimpleDrumSuperquadrics Class Reference
A drum in xz-direction with centre at the origin with a certain radius. Usable with superquadric particles.
#include <SimpleDrumSuperquadrics.h>
Public Member Functions
SimpleDrumSuperquadrics ()
Default constructor.
SimpleDrumSuperquadrics (const SimpleDrumSuperquadrics &p)
Copy constructor.
~SimpleDrumSuperquadrics () override
Destructor.
SimpleDrumSuperquadrics & operator= (const SimpleDrumSuperquadrics &other)
Copy assignment operator.
SimpleDrumSuperquadrics * copy () const final
Wall copy method. It calls the copy constructor of this Wall, useful for polymorphism.
bool getDistanceAndNormal (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return) const override
Computes the distance from the wall for a given BaseParticle and returns true if there is a collision. If there is a collision, also return the normal vector.
bool getDistanceNormalOverlapSuperquadric (const SuperQuadricParticle &p, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const override
void read (std::istream &is) final
reads wall
void write (std::ostream &os) const final
outputs wall
std::string getName () const final
Returns the name of the object.
void setAxis (Vec3D a)
void setRadius (const Mdouble &radius)
BaseInteraction * getInteractionWithSuperQuad (SuperQuadricParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler) override
Vec3D getFurthestPointSuperQuadric (const Vec3D &normalBodyFixed, const Vec3D &axes, Mdouble eps1, Mdouble eps2) const override
Public Member Functions inherited from BaseWall
BaseWall ()
Default constructor.
BaseWall (const BaseWall &w)
Copy constructor.
~BaseWall () override
Default destructor.
virtual bool getDistanceNormalOverlap (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual void setHandler (WallHandler *handler)
A function which sets the WallHandler for this BaseWall.
WallHandler * getHandler () const
A function which returns the WallHandler that handles this BaseWall.
void setIndSpecies (unsigned int indSpecies) override
Define the species of this wall using the index of the species in the SpeciesHandler in this DPMBase.
void setSpecies (const ParticleSpecies *species)
Defines the species of the current wall.
bool isFixed () const override
void setForceControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity={0, 0, 0})
Slowly adjusts the force on a wall towards a specified goal, by adjusting (prescribing) the velocity of the wall.
virtual bool isLocal (Vec3D &min, Vec3D &max) const
bool getLinePlaneIntersect (Vec3D &intersect, const Vec3D &p0, const Vec3D &p1, const Vec3D &n, const Vec3D &p)
bool isInsideWallVTK (const Vec3D &point, const Vec3D &normal, const Vec3D &position) const
void projectOntoWallVTK (Vec3D &point0, const Vec3D &point1, const Vec3D &normal, const Vec3D &position) const
void intersectVTK (std::vector< Vec3D > &points, Vec3D normal, Vec3D position) const
virtual void writeVTK (VTKContainer &vtk) const
void getVTK (std::vector< Vec3D > &points, std::vector< std::vector< double >> &triangleStrips)
const Vec3D getAxis () const
BaseInteraction * getInteractionWith (BaseParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler) override
Returns the interaction between this wall and a given particle, nullptr if there is no interaction.
virtual void actionsOnRestart ()
No implementation but can be overidden in its derived classes.
virtual void actionsAfterParticleGhostUpdate ()
No implementation but can be overidden in its derived classes.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
virtual void handleParticleRemoval (unsigned int id)
Handles the addition of particles to the particleHandler.
virtual void checkInteractions (InteractionHandler *interactionHandler, unsigned int timeStamp)
Check if all interactions are valid.
bool getVTKVisibility () const
void setVTKVisibility (bool vtkVisibility)
void addRenderedWall (BaseWall *w)
BaseWall * getRenderedWall (size_t i) const
std::vector< BaseWall * > getRenderedWalls () const
void removeRenderedWalls ()
void renderWall (VTKContainer &vtk)
void addParticlesAtWall (unsigned numElements=50)
void setVelocityControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity)
virtual void writeWallDetailsVTK (VTKData &data) const
virtual void computeWear ()
Public Member Functions inherited from BaseInteractable
BaseInteractable ()
Default BaseInteractable constructor.
BaseInteractable (const BaseInteractable &p)
Copy constructor.
~BaseInteractable () override
Destructor, it simply destructs the BaseInteractable and all the objects it contains.
unsigned int getIndSpecies () const
Returns the index of the species associated with the interactable object.
const ParticleSpecies * getSpecies () const
Returns a pointer to the species of this BaseInteractable.
void setSpecies (const ParticleSpecies *species)
Sets the species of this BaseInteractable.
const Vec3D & getForce () const
Returns the force on this BaseInteractable.
const Vec3D & getTorque () const
Returns the torque on this BaseInteractable.
void setForce (const Vec3D &force)
Sets the force on this BaseInteractable.
void setTorque (const Vec3D &torque)
Sets the torque on this BaseInteractable.
void addForce (const Vec3D &addForce)
Adds an amount to the force on this BaseInteractable.
void addTorque (const Vec3D &addTorque)
Adds an amount to the torque on this BaseInteractable.
virtual void resetForceTorque (int numberOfOMPthreads)
void sumForceTorqueOMP ()
const Vec3D & getPosition () const
Returns the position of this BaseInteractable.
const Quaternion & getOrientation () const
Returns the orientation of this BaseInteractable.
virtual void setPosition (const Vec3D &position)
Sets the position of this BaseInteractable.
void setOrientationViaNormal (Vec3D normal)
Sets the orientation of this BaseInteractable by defining the vector that results from the rotation of the (1,0,0) vector.
void setOrientationViaEuler (Vec3D eulerAngle)
Sets the orientation of this BaseInteractable by defining the euler angles.
virtual void setOrientation (const Quaternion &orientation)
Sets the orientation of this BaseInteractable.
virtual void move (const Vec3D &move)
Moves this BaseInteractable by adding an amount to the position.
virtual void rotate (const Vec3D &angularVelocityDt)
Rotates this BaseInteractable.
const std::vector< BaseInteraction * > & getInteractions () const
Returns a list of interactions which belong to this interactable.
void addInteraction (BaseInteraction *I)
Adds an interaction to this BaseInteractable.
bool removeInteraction (BaseInteraction *I)
Removes an interaction from this BaseInteractable.
void copyInteractionsForPeriodicParticles (const BaseInteractable &p)
Copies interactions to this BaseInteractable whenever a periodic copy made.
void setVelocity (const Vec3D &velocity)
set the velocity of the BaseInteractable.
void setAngularVelocity (const Vec3D &angularVelocity)
set the angular velocity of the BaseInteractble.
void addVelocity (const Vec3D &velocity)
adds an increment to the velocity.
void addAngularVelocity (const Vec3D &angularVelocity)
add an increment to the angular velocity.
virtual const Vec3D & getVelocity () const
Returns the velocity of this interactable.
virtual const Vec3D & getAngularVelocity () const
Returns the angular velocity of this interactable.
void setPrescribedPosition (const std::function< Vec3D(double)> &prescribedPosition)
Allows the position of an infinite mass interactable to be prescribed.
void applyPrescribedPosition (double time)
Computes the position from the user defined prescribed position function.
void setPrescribedVelocity (const std::function< Vec3D(double)> &prescribedVelocity)
Allows the velocity of an infinite mass interactable to be prescribed.
void applyPrescribedVelocity (double time)
Computes the velocity from the user defined prescribed velocity function.
void setPrescribedOrientation (const std::function< Quaternion(double)> &prescribedOrientation)
Allows the orientation of the infinite mass interactbale to be prescribed.
void applyPrescribedOrientation (double time)
Computes the orientation from the user defined prescribed orientation function.
void setPrescribedAngularVelocity (const std::function< Vec3D(double)> &prescribedAngularVelocity)
Allows the angular velocity of the infinite mass interactable to be prescribed.
void applyPrescribedAngularVelocity (double time)
Computes the angular velocity from the user defined prescribed angular velocity.
virtual const Vec3D getVelocityAtContact (const Vec3D &contact) const
Returns the velocity at the contact point, use by many force laws.
void integrateBeforeForceComputation (double time, double timeStep)
This is part of integrate routine for objects with infinite mass.
void integrateAfterForceComputation (double time, double timeStep)
This is part of the integration routine for objects with infinite mass.
virtual Mdouble getInvMass () const
virtual Mdouble getCurvature (const Vec3D &labFixedCoordinates) const
virtual bool isFaceContact (const Vec3D &normal) const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
InfiniteWall wall
Mdouble radius_
Additional Inherited Members
Static Public Member Functions inherited from BaseWall
static void addToVTK (const std::vector< Vec3D > &points, VTKContainer &vtk)
Takes the points provided and adds a triangle strip connecting these points to the vtk container.
Detailed Description
A drum in xz-direction with centre at the origin with a certain radius. Usable with superquadric particles.
Notice that this wall contains a mutable infinite wall. This is because for contact-detection we map the infinite wall on a point with the correct distance from the origin, thereby linearising the drum. Since this infinite wall has to change normal and position for every interaction, it must be changeable in the const method getDistanceAndNormal and therefore the infinite wall must be mutable (or volatile, but that is not necessary here).
Todo:
Document
Definitions in source-file
VTK-write function
Test
Constructor & Destructor Documentation
SimpleDrumSuperquadrics() [1/2]
SimpleDrumSuperquadrics::SimpleDrumSuperquadrics ()
Default constructor.
 {
     logger(DEBUG, "SimpleDrumSuperquadrics() finished");
     radius_ = 1;
     wall.set({1,0,0}, {1,0,0});
 }
References DEBUG, logger, radius_, InfiniteWall::set(), and wall.
Referenced by copy().
SimpleDrumSuperquadrics() [2/2]
SimpleDrumSuperquadrics::SimpleDrumSuperquadrics (const SimpleDrumSuperquadrics & other)
Copy constructor.
Parameters
[in] other The AxisymmetricIntersectionOfWalls that must be copied.
         : BaseWall(other)
 {
     wall = other.wall;
     radius_ = other.radius_;
     logger(DEBUG, "AxisymmetricIntersectionOfWalls(const AxisymmetricIntersectionOfWalls &p) finished");
 }
References DEBUG, logger, radius_, and wall.
~SimpleDrumSuperquadrics()
SimpleDrumSuperquadrics::~SimpleDrumSuperquadrics () override
Destructor.
 {
     logger(DEBUG, "SimpleDrumSuperquadricsuadrics() finished.");
 }
References DEBUG, and logger.
Member Function Documentation
copy()
SimpleDrumSuperquadrics * SimpleDrumSuperquadrics::copy () const final virtual
Wall copy method. It calls the copy constructor of this Wall, useful for polymorphism.
Returns
pointer to a IntersectionOfWalls object allocated using new.
Implements BaseWall.
 {
     return new SimpleDrumSuperquadrics(*this);
 }
References SimpleDrumSuperquadrics().
Referenced by operator=().
getDistanceAndNormal()
bool SimpleDrumSuperquadrics::getDistanceAndNormal (const BaseParticle & p, Mdouble & distance, Vec3D & normalReturn) const override virtual
Computes the distance from the wall for a given BaseParticle and returns true if there is a collision. If there is a collision, also return the normal vector.
First, the particle is translated by the vector position_, then the distance normal and tangential to the orientation is computed. This normal and tangential direction is interpreted as the x and z coordinate. With the particle shifted into the XZ plane, the distance and normal is computed, as if the AxisymmetricIntersectionOfWalls would be a simple IntersectionOfWalls. Finally, the object and the normal is rotated back to the original position.
See also AxisymmetricIntersectionOfWalls for details.
Implements BaseWall.
 {
     Vec3D normalDirection = p.getPosition();
     normalDirection.Y = 0;
     normalDirection.normalise();
     wall.set(normalDirection, normalDirection * radius_);
     logger(DEBUG, "setting wall to %, %", normalDirection, normalDirection * radius_);
     logger(DEBUG, "angular velocity of wall: %", getAngularVelocity());
     //determine wall distance, normal and contact in axissymmetric coordinates
     //and transform from axisymmetric coordinates
     return  (wall.getDistanceAndNormal(p, distance, normalReturn));
 }
References DEBUG, BaseInteractable::getAngularVelocity(), InfiniteWall::getDistanceAndNormal(), logger, Vec3D::normalise(), p, radius_, InfiniteWall::set(), wall, and Vec3D::Y.
getDistanceNormalOverlapSuperquadric()
bool SimpleDrumSuperquadrics::getDistanceNormalOverlapSuperquadric (const SuperQuadricParticle & p, Mdouble & distance, Vec3D & normal_return, Mdouble & overlap) const override virtual
Reimplemented from BaseWall.
 {
     Vec3D normalDirection = p.getPosition();
     normalDirection.Y = 0;
     if (normalDirection.getLengthSquared() < 1e-2)
         return false;
     normalDirection.normalise();
     wall.set(normalDirection, normalDirection * radius_);
     logger(DEBUG, "setting wall to [%], [%]", normalDirection, normalDirection * radius_);
     return wall.getDistanceNormalOverlapSuperquadric(p, distance, normal_return, overlap);
 }
References DEBUG, e(), InfiniteWall::getDistanceNormalOverlapSuperquadric(), Vec3D::getLengthSquared(), logger, Vec3D::normalise(), p, radius_, InfiniteWall::set(), wall, and Vec3D::Y.
getFurthestPointSuperQuadric()
Vec3D SimpleDrumSuperquadrics::getFurthestPointSuperQuadric (const Vec3D & normalBodyFixed, const Vec3D & axes, Mdouble eps1, Mdouble eps2) const inline override virtual
Reimplemented from BaseWall.
     {
         return wall.getFurthestPointSuperQuadric(normalBodyFixed, axes, eps1, eps2);
     }
References InfiniteWall::getFurthestPointSuperQuadric(), and wall.
getInteractionWithSuperQuad()
BaseInteraction* SimpleDrumSuperquadrics::getInteractionWithSuperQuad (SuperQuadricParticle * p, unsigned timeStamp, InteractionHandler * interactionHandler) inline override virtual
Todo:
make it work with screw, coil and other weird walls
Reimplemented from BaseWall.
     {
         return wall.getInteractionWithSuperQuad(p, timeStamp, interactionHandler);
     }
References BaseWall::getInteractionWithSuperQuad(), p, and wall.
getName()
std::string SimpleDrumSuperquadrics::getName () const final virtual
Returns the name of the object.
Returns
The string "AxisymmetricIntersectionOfWalls".
Implements BaseObject.
 {
     return "SimpleDrumSuperquadrics";
 }
operator=()
SimpleDrumSuperquadrics & SimpleDrumSuperquadrics::operator= (const SimpleDrumSuperquadrics & other)
Copy assignment operator.
Parameters
[in] other The AxisymmetricIntersectionOfWalls that must be copied.
 {
     if (this == &other)
     {
         return *this;
     }
     else
     {
         return *(other.copy());
     }
 }
References copy().
read()
void SimpleDrumSuperquadrics::read (std::istream & is) final virtual
reads wall
Parameters
[in] is The input stream from which the AxisymmetricIntersectionOfWalls is read, usually a restart file.
Reimplemented from BaseWall.
 {
     BaseWall::read(is);
     wall.read(is);
     is >> radius_;
 }
References radius_, BaseWall::read(), InfiniteWall::read(), and wall.
setAxis()
void SimpleDrumSuperquadrics::setAxis (Vec3D a)
 {
     setOrientationViaNormal(a);
 }
References a, and BaseInteractable::setOrientationViaNormal().
setRadius()
void SimpleDrumSuperquadrics::setRadius (const Mdouble & radius) inline
     {
         radius_ = radius;
         logger(INFO, "setting drum radius to %", radius_);
     }
References INFO, logger, UniformPSDSelfTest::radius, and radius_.
Referenced by MinimalExampleDrum::setupInitialConditions().
write()
void SimpleDrumSuperquadrics::write (std::ostream & os) const final virtual
outputs wall
Parameters
[in] os The output stream where the AxisymmetricIntersectionOfWalls must be written to, usually a restart file.
Reimplemented from BaseWall.
 {
     BaseWall::write(os);
     wall.write(os);
     os << radius_;
 }
References radius_, wall, and BaseWall::write().
Member Data Documentation
radius_
Mdouble SimpleDrumSuperquadrics::radius_ private
Referenced by getDistanceAndNormal(), getDistanceNormalOverlapSuperquadric(), read(), setRadius(), SimpleDrumSuperquadrics(), and write().
wall
InfiniteWall SimpleDrumSuperquadrics::wall mutable private
Referenced by getDistanceAndNormal(), getDistanceNormalOverlapSuperquadric(), getFurthestPointSuperQuadric(), getInteractionWithSuperQuad(), read(), SimpleDrumSuperquadrics(), and write().
The documentation for this class was generated from the following files:
SimpleDrumSuperquadrics.h
SimpleDrumSuperquadrics.cc