MercuryDPM: SuperQuadricParticle Class Reference
SuperQuadricParticle Class Reference final
#include <SuperQuadricParticle.h>
Public Member Functions
SuperQuadricParticle ()
Basic Particle constructor, creates a superquadric with axes (1,1,1) and exponents (2,2), so it creates a sphere with radius 1.
SuperQuadricParticle (const SuperQuadricParticle &p)
Copy constructor, which accepts as input a reference to a Superquadric. It creates a copy of this Particle and all it's information. Usually it is better to use the copy() function for polymorphism.
SuperQuadricParticle (const BaseParticle &p)
Base class copy constructor. Creates a Superquadric particle from a NonSphericalParticle.
~SuperQuadricParticle () override
Destructor, needs to be implemented and checked to see if it is the largest or smallest particle currently in its particleHandler.
SuperQuadricParticle * copy () const override
Copy method. It calls to copy constructor of this superquadric, useful for polymorphism.
void write (std::ostream &os) const override
Write function: write this SuperQuadric to the given output-stream, for example a restart-file.
void read (std::istream &is) override
Read function: read in the information for this superquadric from the given input-stream, for example a restart file.
std::string getName () const override
Returns the name of the class, here "SuperQuadric".
void setAxesAndExponents (const Mdouble &a1, const Mdouble &a2, const Mdouble &a3, const Mdouble &eps1, const Mdouble &eps2)
Set the geometrical properties of the superquadrics, namely the axes-lengths a1, a2 and a3, and the exponents epsilon1 and epsilon2. We use the super-ellipsoid definition stated in Chapter 2 of the book "Segmentation and recovery of superquadrics" by Jaklic et al.
void setAxesAndExponents (const Vec3D &axes, const Mdouble &eps1, const Mdouble &eps2)
Set the geometrical properties of the superquadrics, namely the axes-lengths axes, and the exponents epsilon1 and epsilon2. We use the super-ellipsoid definition stated in Chapter 2 of the book "Segmentation and recovery of superquadrics" by Jaklic et al.
void setAxes (const Mdouble &a1, const Mdouble &a2, const Mdouble &a3)
Set the axes-lengths to a1, a2 and a3 for this superquadric. We use the super-ellipsoid definition stated in Chapter 2 of the book "Segmentation and recovery of superquadrics" by Jaklic et al.
void setAxes (const Vec3D &axes) override
Set the axes-lengths to axes for this superquadric. We use the super-ellipsoid definition stated in Chapter 2 of the book "Segmentation and recovery of superquadrics" by Jaklic et al.
void setExponents (const Mdouble &eps1, const Mdouble &eps2) override
Set the exponents to eps1 and eps2 for this superquadric. We use the super-ellipsoid definition stated in Chapter 2 of the book "Segmentation and recovery of superquadrics" by Jaklic et al.
Vec3D getAxes () const override
Get the axes-lengths of this superquadric. We use the super-ellipsoid definition stated in Chapter 2 of the book "Segmentation and recovery of superquadrics" by Jaklic et al.
Mdouble getExponentEps1 () const override
Get the first exponent of this superquadric. We use the super-ellipsoid definition stated in Chapter 2 of the book "Segmentation and recovery of superquadrics" by Jaklic et al.
Mdouble getExponentEps2 () const override
Get the second exponent of this superquadric. We use the super-ellipsoid definition stated in Chapter 2 of the book "Segmentation and recovery of superquadrics" by Jaklic et al.
Mdouble getVolume () const override
void setInertia () override
Compute and set the inertia-tensor for this superquadric. For internal use only.
void setRadius (const Mdouble radius) override
Sets the particle's radius_ (and adjusts the mass_ accordingly, based on the particle's species)
BaseInteraction * getInteractionWith (BaseParticle *P, unsigned timeStamp, InteractionHandler *interactionHandler) override
Checks if this superquadric is in interaction with the given particle, and if so, returns vector of pointer to the associated BaseInteraction object (else returns empty vector).
Mdouble getCurvature (const LabFixedCoordinates &labFixedCoordinates) const override
Get the mean curvature of this superquadric at the given (lab-fixed) position, see Podlozhyuk et al. (2017) eq (39)
bool isInContactWith (const BaseParticle *p) const override
Get whether or not this superquadric is in contact with the given particle.
SmallVector< 3 > computeShapeGradientLabFixed (const LabFixedCoordinates &labFixedCoordinates) const
Compute and get the gradient of the shape-function at the given (lab-fixed) position.
BaseInteraction * getInteractionWithSuperQuad (SuperQuadricParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler)
Checks if this superquadric is in interaction with the given superquadric, and if so, returns vector of pointer to the associated BaseInteraction object (else returns empty vector).
SmallMatrix< 3, 3 > computeHessianLabFixed (const LabFixedCoordinates &labFixedCoordinates) const
Compute and get the hessian ("second derivative") of the shape-function at the given (lab-fixed) position.
Mdouble computeShape (const LabFixedCoordinates &labFixedCoordinates) const
Compute and get the shape-functiion at the given (lab-fixed) position.
SmallVector< 4 > computeResidualContactDetection (const SmallVector< 4 > &position, const SuperQuadricParticle *p1, const SuperQuadricParticle *p2) const
Objective function for contact detection between the two given superquadrics. See Podlozhyuk et al. (2017) eq (22).
SmallMatrix< 4, 4 > getJacobianOfContactDetectionObjective (const SmallVector< 4 > &contactPoint, const SuperQuadricParticle *p1, const SuperQuadricParticle *p2) const
Compute and return the derivative of functionThatShouldBecomeZeroForContactDetection, both to the position and the Lagrange multiplier, and evaluated at the contact point.
SmallVector< 4 > getInitialGuessForContact (const SuperQuadricParticle *pQuad, BaseInteraction *C) const
Get an initial guess for the contact-point between this particle and the given particle.
Mdouble overlapFromContactPoint (const LabFixedCoordinates &contactPoint, const LabFixedCoordinates &normal) const
Compute the distance between the contact-point and surface of this superquadric particle.
SmallVector< 4 > getContactPoint (const SuperQuadricParticle *p, BaseInteraction *C) const
Compute the contact point between this and the given superquadric particle.
SmallVector< 4 > getContactPointPlanB (const SuperQuadricParticle *pOther, unsigned numberOfSteps) const
If the "normal" procedure fails to find a contact point, use an alternative approach that involves starting with two spheres to compute the interaction, and becoming less and less spherical.
bool computeContactPoint (SmallVector< 4 > &contactPoint, const SuperQuadricParticle *p1, const SuperQuadricParticle *p2) const
Perform the actual Newton-iterations to find the contact point. Note, that it is given back as a parameter.
void writeDebugMessageStep1 (const SuperQuadricParticle *pQuad, const SmallVector< 4 > &contactPointPlanB) const
void writeDebugMessageStep2 (const SuperQuadricParticle *pQuad, const Vec3D &dAxesThis, const Mdouble &dn11, const Mdouble &dn12, const Vec3D &dAxesOther, const Mdouble &dn21, const Mdouble &dn22) const
void writeDebugMessageStep3 (const Vec3D &axesThis, const Mdouble &n11, const Mdouble &n12, const Vec3D &axesOther, const Mdouble &n21, const Mdouble &n22) const
void writeDebugMessageMiddleOfLoop (const SuperQuadricParticle &p1, const SuperQuadricParticle &p2, SmallVector< 4 > &contactPointPlanB, const unsigned int &counter) const
Mdouble getInteractionRadius (const BaseParticle *particle) const
returns the radius plus half the interactionDistance of the mixed species
void computeMass (const ParticleSpecies &s) override
Computes the particle's (inverse) mass and inertia.
Public Member Functions inherited from NonSphericalParticle
NonSphericalParticle ()=default
NonSphericalParticle (const NonSphericalParticle &p)=default
NonSphericalParticle (const BaseParticle &p)
Base class copy constructor. Creates a NonSphericalParticle particle from a BaseParticle.
~NonSphericalParticle () override=default
bool isSphericalParticle () const override
virtual Mdouble getKineticEnergy () const override
virtual Mdouble getRotationalEnergy () const override
Calculates the particle's rotational kinetic energy.
virtual Mdouble getSurfaceArea () const override
Public Member Functions inherited from BaseParticle
BaseParticle ()
Basic Particle constructor, creates an Particle at (0,0,0) with radius, mass and inertia equal to 1.
BaseParticle (const BaseParticle &p)
Particle copy constructor, which accepts as input a reference to a Particle. It creates a copy of this Particle and all it's information. Usually it is better to use the copy() function for polymorphism.
BaseParticle (const ParticleSpecies *s)
~BaseParticle () override
Particle destructor, needs to be implemented and checked if it removes tangential spring information.
void fixParticle ()
Fix Particle function. It fixes a Particle by setting its inverse mass and inertia and velocities to zero.
bool isFixed () const override
Is fixed Particle function. It returns whether a Particle is fixed or not, by checking its inverse Mass.
bool isMPIParticle () const
Indicates if this particle is a ghost in the MPI domain.
void setMPIParticle (bool flag)
Flags the mpi particle status.
bool isInMPIDomain ()
Indicates if the particle is in the communication zone of the mpi domain.
void setInMPIDomain (bool flag)
Flags the status of the particle if wether it is in the communication zone or not.
bool isInPeriodicDomain () const
Indicates if the particle is in the periodic boundary communication zone.
void setInPeriodicDomain (bool flag)
Flags the status of the particle whether it is in the periodic communication zone or not.
bool isPeriodicGhostParticle () const
Indicates if this particle is a ghost in the periodic boundary.
void setPeriodicGhostParticle (bool flag)
Flags the status of the particle to be a ghost in periodic boundary or not.
bool isMaserParticle () const
Indicates if this particle belongs to the maser boundary.
void setMaserParticle (bool flag)
Flags the status of the particle if it belongs to the maser boundary or not.
void setCommunicationComplexity (unsigned complexity)
Set the communication complexity of the particle.
unsigned getCommunicationComplexity ()
Obtains the communication complexity of the particle.
void setPeriodicComplexity (std::vector< int > complexity)
Set the periodic communication complexity of the particle.
void setPeriodicComplexity (int index, int value)
Set the periodic communication complexity of the particle.
const std::vector< int > & getPeriodicComplexity ()
Obtains the periodic communication complexity of the particle.
void setPreviousPeriodicComplexity (std::vector< int > complexity)
Set the previous periodic communication complexity of the paritcle.
const std::vector< int > & getPreviousPeriodicComplexity () const
Sets the previous periodic communication complexity of the particle.
int getPeriodicComplexity (int index)
Gets the periodic communication complexity of a certain boundary.
void unfix ()
Unfix Particle function, which required a reference to the Species vector. It unfixes a Particle by computing the Particles mass and inertia.
virtual void oldRead (std::istream &is)
virtual void setInfo (Mdouble info)
Sets some user-defined information about this object (by default, species ID).
virtual Mdouble getInfo () const
Returns some user-defined information about this object (by default, species ID).
void setTimeStamp (unsigned timeStamp)
unsigned getTimeStamp () const
void printHGrid (std::ostream &os) const
Adds particle's HGrid level and cell coordinates to an ostream.
unsigned int getHGridLevel () const
Returns particle's HGrid level.
BaseParticle * getHGridNextObject () const
Returns pointer to next object in particle's HGrid level & cell.
BaseParticle * getHGridPrevObject () const
Returns pointer to previous object in particle's HGrid level & cell.
int getHGridX () const
Returns particle's HGrid cell X-coordinate.
int getHGridY () const
Returns particle's HGrid cell Y-coordinate.
int getHGridZ () const
Returns particle's HGrid cell Z-coordinate.
MatrixSymmetric3D getInvInertia () const
Returns the inverse of the particle's inertia tensor.
Mdouble getInvMass () const override
Returns the inverse of the particle's mass.
Mdouble getGravitationalEnergy () const
Calculates the particle's gravitational energy.
Mdouble getMass () const
Returns the particle's mass.
Vec3D getMomentum () const
MatrixSymmetric3D getInertia () const
Vec3D getAngularMomentum () const
BaseParticle * getPeriodicFromParticle () const
Returns the 'original' particle this one's a periodic copy of.
Mdouble getRadius () const
Returns the particle's radius.
Mdouble getMaxInteractionRadius () const
Returns the particle's interaction radius, which might be different from radius_ (e.g., when dealing with wet particles)
Mdouble getInteractionDistance (const BaseInteractable *i) const
Returns the interactionDistance_ of the mixed species of this particle and the particle or wall i.
Mdouble getSumOfInteractionRadii (const BaseParticle *particle) const
returns the sum of the radii plus the interactionDistance
Mdouble getWallInteractionRadius (const BaseWall *wall) const
returns the radius plus the interactionDistance
const Vec3D & getPreviousPosition () const
Returns the particle's position in the previous time step.
const Vec3D getDisplacement2 (Mdouble xmin, Mdouble xmax, Mdouble ymin, Mdouble ymax, Mdouble zmin, Mdouble zmax, Mdouble t) const
void setInertia (MatrixSymmetric3D inertia)
Sets the particle's inertia_ (and adjusts invInertia_ accordingly)
void setInverseInertia (MatrixSymmetric3D inverseInertia)
Sets the particle's inertia_ (and adjusts invInertia_ accordingly)
void setInfiniteInertia ()
Sets the particle's inertia_ to 'infinite' (1e20) and its invInertia_ to 0.
void setPeriodicFromParticle (BaseParticle *p)
Assigns the pointer to the 'original' particle this one's a periodic copy of (used in periodic boundary condition implementations).
void setHGridX (const int x)
Sets the particle's HGrid cell X-coordinate.
void setHGridY (const int y)
Sets the particle's HGrid cell Y-coordinate.
void setHGridZ (const int z)
Sets the particle's HGrid cell Z-coordinate.
void setHGridLevel (const unsigned int level)
Sets the particle's HGrid level.
void setHGridNextObject (BaseParticle *p)
Sets the pointer to the next object in the particle's HGrid cell & level.
void setHGridPrevObject (BaseParticle *p)
Sets the pointer to the previous object in the particle's HGrid cell & level.
MERCURYDPM_DEPRECATED void setMass (Mdouble mass)
Sets the particle's mass.
void setMassForP3Statistics (Mdouble mass)
Sets the particle's mass This function should not be used, but is necessary to extend the CG toolbox to non-spherical particles.
void setPreviousPosition (const Vec3D &pos)
Sets the particle's position in the previous time step.
void movePrevious (const Vec3D &posMove)
Adds a vector to the particle's previousPosition_.
void accelerate (const Vec3D &vel)
Increases the particle's velocity_ by the given vector.
void angularAccelerate (const Vec3D &angVel)
Increases the particle's angularVelocity_ by the given vector.
void setHandler (ParticleHandler *handler)
Sets the pointer to the particle's ParticleHandler.
ParticleHandler * getHandler () const
Returns pointer to the particle's ParticleHandler.
virtual void integrateBeforeForceComputation (double time, double timeStep)
First step of Velocity Verlet integration.
virtual void integrateAfterForceComputation (double time, double timeStep)
Second step of Velocity Verlet integration.
unsigned int getParticleDimensions () const
Returns the particle's dimensions (either 2 or 3).
MERCURYDPM_DEPRECATED void setIndSpecies (unsigned int indSpecies) override
virtual void setSpecies (const ParticleSpecies *species)
virtual void actionsBeforeTimeStep ()
virtual unsigned getNumberOfFieldsVTK () const
virtual std::string getTypeVTK (unsigned i) const
virtual std::string getNameVTK (unsigned i) const
virtual std::vector< Mdouble > getFieldVTK (unsigned i) const
virtual void actionsAfterTimeStep ()
const HGridCell & getHGridCell () const
BaseParticle * getClump () const
bool isClump () const
Checks if particle is a clump (container)
bool isPebble () const
Checks if particle is a pebble (belongs to a clump)
virtual Vec3D getCenterOfMass ()
virtual void actionsAfterAddObject ()
Public Member Functions inherited from BaseInteractable
BaseInteractable ()
Default BaseInteractable constructor.
BaseInteractable (const BaseInteractable &p)
Copy constructor.
~BaseInteractable () override
Destructor, it simply destructs the BaseInteractable and all the objects it contains.
unsigned int getIndSpecies () const
Returns the index of the species associated with the interactable object.
const ParticleSpecies * getSpecies () const
Returns a pointer to the species of this BaseInteractable.
void setSpecies (const ParticleSpecies *species)
Sets the species of this BaseInteractable.
const Vec3D & getForce () const
Returns the force on this BaseInteractable.
const Vec3D & getTorque () const
Returns the torque on this BaseInteractable.
void setForce (const Vec3D &force)
Sets the force on this BaseInteractable.
void setTorque (const Vec3D &torque)
Sets the torque on this BaseInteractable.
void addForce (const Vec3D &addForce)
Adds an amount to the force on this BaseInteractable.
void addTorque (const Vec3D &addTorque)
Adds an amount to the torque on this BaseInteractable.
virtual void resetForceTorque (int numberOfOMPthreads)
void sumForceTorqueOMP ()
const Vec3D & getPosition () const
Returns the position of this BaseInteractable.
const Quaternion & getOrientation () const
Returns the orientation of this BaseInteractable.
virtual void setPosition (const Vec3D &position)
Sets the position of this BaseInteractable.
void setOrientationViaNormal (Vec3D normal)
Sets the orientation of this BaseInteractable by defining the vector that results from the rotation of the (1,0,0) vector.
void setOrientationViaEuler (Vec3D eulerAngle)
Sets the orientation of this BaseInteractable by defining the euler angles.
virtual void setOrientation (const Quaternion &orientation)
Sets the orientation of this BaseInteractable.
virtual void move (const Vec3D &move)
Moves this BaseInteractable by adding an amount to the position.
virtual void rotate (const Vec3D &angularVelocityDt)
Rotates this BaseInteractable.
const std::vector< BaseInteraction * > & getInteractions () const
Returns a list of interactions which belong to this interactable.
void addInteraction (BaseInteraction *I)
Adds an interaction to this BaseInteractable.
bool removeInteraction (BaseInteraction *I)
Removes an interaction from this BaseInteractable.
void copyInteractionsForPeriodicParticles (const BaseInteractable &p)
Copies interactions to this BaseInteractable whenever a periodic copy made.
void setVelocity (const Vec3D &velocity)
set the velocity of the BaseInteractable.
void setAngularVelocity (const Vec3D &angularVelocity)
set the angular velocity of the BaseInteractble.
void addVelocity (const Vec3D &velocity)
adds an increment to the velocity.
void addAngularVelocity (const Vec3D &angularVelocity)
add an increment to the angular velocity.
virtual const Vec3D & getVelocity () const
Returns the velocity of this interactable.
virtual const Vec3D & getAngularVelocity () const
Returns the angular velocity of this interactable.
void setPrescribedPosition (const std::function< Vec3D(double)> &prescribedPosition)
Allows the position of an infinite mass interactable to be prescribed.
void applyPrescribedPosition (double time)
Computes the position from the user defined prescribed position function.
void setPrescribedVelocity (const std::function< Vec3D(double)> &prescribedVelocity)
Allows the velocity of an infinite mass interactable to be prescribed.
void applyPrescribedVelocity (double time)
Computes the velocity from the user defined prescribed velocity function.
void setPrescribedOrientation (const std::function< Quaternion(double)> &prescribedOrientation)
Allows the orientation of the infinite mass interactbale to be prescribed.
void applyPrescribedOrientation (double time)
Computes the orientation from the user defined prescribed orientation function.
void setPrescribedAngularVelocity (const std::function< Vec3D(double)> &prescribedAngularVelocity)
Allows the angular velocity of the infinite mass interactable to be prescribed.
void applyPrescribedAngularVelocity (double time)
Computes the angular velocity from the user defined prescribed angular velocity.
virtual const Vec3D getVelocityAtContact (const Vec3D &contact) const
Returns the velocity at the contact point, use by many force laws.
void integrateBeforeForceComputation (double time, double timeStep)
This is part of integrate routine for objects with infinite mass.
void integrateAfterForceComputation (double time, double timeStep)
This is part of the integration routine for objects with infinite mass.
virtual bool isFaceContact (const Vec3D &normal) const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Member Functions
void setBoundingRadius ()
Get the radius of the sphere that fits precisely around the particle.
Private Attributes
Mdouble eps1_
Blockiness parameters.
Mdouble eps2_
Vec3D axes_
Lengths of principal axes (a1, a2, a3).
Additional Inherited Members
Public Attributes inherited from BaseParticle
Mdouble radius_
Mdouble invMass_
Particle radius_.
MatrixSymmetric3D invInertia_
Inverse Particle mass (for computation optimization)
BaseParticle * clumpParticle_
Function that updates necessary quantities of a clump particle after adding a pebble.
bool isPebble_
pointer to a clump particle (for a pebble)
bool isClump_
The particle is pebble.
Constructor & Destructor Documentation
SuperQuadricParticle() [1/3]
SuperQuadricParticle::SuperQuadricParticle ()
Basic Particle constructor, creates a superquadric with axes (1,1,1) and exponents (2,2), so it creates a sphere with radius 1.
calls the default constructor of BaseParticle, and creates an SuperEllipsoid with axes (1,1,1) and exponents (2,2), so it creates a sphere with radius 1.
     : NonSphericalParticle()
 {
     axes_ = Vec3D(1.0, 1.0, 1.0);
     eps1_ = 1.0;
     eps2_ = 1.0;
     logger(DEBUG, "SuperQuadricParticle::SuperQuadricParticle() finished");
 }
References axes_, DEBUG, eps1_, eps2_, and logger.
Referenced by copy(), getInteractionWith(), and isInContactWith().
SuperQuadricParticle() [2/3]
SuperQuadricParticle::SuperQuadricParticle (const SuperQuadricParticle & p)
Copy constructor, which accepts as input a reference to a Superquadric. It creates a copy of this Particle and all it's information. Usually it is better to use the copy() function for polymorphism.
Constructor that copies most of the properties of the given particle. Please note that not everything is copied, for example the position in the HGrid is not determined yet by the end of this constructor. It also does not copy the interactions and the pointer to the handler that handles this particle. Use with care.
Parameters
[in,out] p Reference to the SuperQuad this one should become a copy of.
     : NonSphericalParticle(p)
 {
     axes_ = p.axes_;
     eps1_ = p.eps1_;
     eps2_ = p.eps2_;
 }
References axes_, eps1_, eps2_, and p.
SuperQuadricParticle() [3/3]
SuperQuadricParticle::SuperQuadricParticle (const BaseParticle & p)
Base class copy constructor. Creates a Superquadric particle from a NonSphericalParticle.
     : NonSphericalParticle(p)
 {
     Mdouble radius = p.getRadius();
     axes_ = Vec3D(radius, radius, radius);
     eps1_ = 1.0;
     eps2_ = 1.0;
 }
References axes_, eps1_, eps2_, p, and UniformPSDSelfTest::radius.
~SuperQuadricParticle()
SuperQuadricParticle::~SuperQuadricParticle () override
Destructor, needs to be implemented and checked to see if it is the largest or smallest particle currently in its particleHandler.
Destructor. It asks the ParticleHandler to check if this was the smallest or largest particle and adjust itself accordingly.
 {
     if (getHandler() != nullptr)
     {
         getHandler()->checkExtremaOnDelete(this);
     }
     logger(DEBUG, "SuperQuadricParticle::SuperQuadricParticleParticle() of particle % finished.", getId());
 }
References ParticleHandler::checkExtremaOnDelete(), DEBUG, BaseParticle::getHandler(), BaseObject::getId(), and logger.
Member Function Documentation
computeContactPoint()
bool SuperQuadricParticle::computeContactPoint (SmallVector< 4 > & contactPoint, const SuperQuadricParticle * p1, const SuperQuadricParticle * p2) const
Perform the actual Newton-iterations to find the contact point. Note, that it is given back as a parameter.
Function that actually performs the Newton iterations for contact-detection. We use a Newton-method with adaptive damping, i.e. we start with an undamped Newton iteration, and if we "overshoot" we use a damping-factor that gets halved until there is no overshoot anymore. If the damping-factor gets too small, either plan B is initiated, or if this is already plan B, we give an error. After each iteration, the damping factor is set to 1 again.
Parameters
[in|out] contactPoint The contact point we are looking for. The input is an approximate contact point that is obtained by another method, and we update this point until we reach the defined tolerance.
[in] p1 The first particle of the contact we are looking for
[in] p2 The second particle of the contact we are looking for
Returns
Boolean for whether or not the contact-detection was successful.
 {
     // Damped Newton's method: (dampingFactor 1 is undamped)
     Mdouble dampingFactor = 1;
     int iteration = 1;
     const Mdouble tolerance = 1e-5;
     const unsigned maxIterations = 100;
     logger(VERBOSE, "func to be zero value: % \n",
            computeResidualContactDetection(contactPoint, p1, p2));
     while (computeResidualContactDetection(contactPoint, p1, p2).length() > tolerance && iteration < maxIterations)
     {
         logger(VERBOSE, "Iteration: %\n", iteration);
         SmallMatrix<4, 4> jacobian = getJacobianOfContactDetectionObjective(contactPoint, p1, p2);
         SmallVector<4> func = -computeResidualContactDetection(contactPoint, p1, p2);
         jacobian.solve(func); //note: solve is in place
         SmallVector<4> newPoint = contactPoint + dampingFactor * func;
         const auto residueOld = computeResidualContactDetection(contactPoint, p1, p2);
         const auto residueNew = computeResidualContactDetection(newPoint, p1, p2);
         logger(VERBOSE, "Old value: % (%) new value: % (%)",
                computeResidualContactDetection(contactPoint, p1, p2),
                computeResidualContactDetection(contactPoint, p1, p2).length(),
                computeResidualContactDetection(newPoint, p1, p2),
                computeResidualContactDetection(newPoint, p1, p2).length());
         logger(VERBOSE, "current contact point: %, new contact point: %\n", contactPoint, newPoint);
         logger(VERBOSE, "damping factor: %", dampingFactor);
         if (residueNew.length()
             < residueOld.length())
         {
             contactPoint = newPoint;
             dampingFactor = 1;
         }
         else
         {
             dampingFactor /= 2;
             if (dampingFactor < 1e-10)
             {
                 return false;
             }
         }
         iteration++;
     }
     return (iteration != maxIterations);
 }
References computeResidualContactDetection(), e(), func(), getJacobianOfContactDetectionObjective(), logger, p1, SmallMatrix< numberOfRows, numberOfColumns >::solve(), and VERBOSE.
Referenced by getContactPoint(), and getContactPointPlanB().
computeHessianLabFixed()
SmallMatrix< 3, 3 > SuperQuadricParticle::computeHessianLabFixed (const LabFixedCoordinates & labFixedCoordinates) const
Compute and get the hessian ("second derivative") of the shape-function at the given (lab-fixed) position.
This function computes the Hessian ("second derivative") of the shape function in the body-fixed coordinate system. The expressions are provided in Eq. 15 of the article in Comp. Part. Mech. (2017) 4 : 101-118.
Returns
The hessian of the shape function at the given (lab-fixed) coordinates. Note, that this is the hessian to the lab-fixed coordinates, H_X (F)(X)
Todo:
Come up with good expression for when x = y = 0 and n1 < n2
 {
     SmallMatrix<3, 3> hessian;
     BodyFixedCoordinates bodyFixedCoordinates = labFixedCoordinates - this->getPosition();
     getOrientation().rotateBack(bodyFixedCoordinates);
     const Mdouble n1 = 2.0 / eps1_;
     const Mdouble n2 = 2.0 / eps2_;
     const Mdouble absXoa = std::abs(bodyFixedCoordinates.X / axes_.X);
     const Mdouble absYob = std::abs(bodyFixedCoordinates.Y / axes_.Y);
     const Mdouble absZoc = std::abs(bodyFixedCoordinates.Z / axes_.Z);
     const Mdouble nu = std::pow(absXoa, n2) + std::pow(absYob, n2);
     const Mdouble help1 = std::pow(nu, n1 / n2 - 1.0);
     const Mdouble help2 = std::pow(nu, n1 / n2 - 2.0);
     hessian(0, 0) = n1 * (n2 - 1) / axes_.X / axes_.X * std::pow(absXoa, n2 - 2.0) * help1
                     + ((n1 - n2) * n1 / axes_.X / axes_.X) * std::pow(absXoa, 2. * n2 - 2.0) * help2;
     hessian(1, 1) = n1 * (n2 - 1) / axes_.Y / axes_.Y * std::pow(absYob, n2 - 2.0) * help1
                     + ((n1 - n2) * n1 / axes_.Y / axes_.Y) * std::pow(absYob, 2. * n2 - 2.0) * help2;
     hessian(2, 2) = n1 * (n1 - 1) / axes_.Z / axes_.Z * std::pow(absZoc, n1 - 2.0);
     hessian(1, 0) = n1 * (n1 - n2) / axes_.X / axes_.Y * std::pow(absXoa, n2 - 1.0) * std::pow(absYob, n2 - 1.0) *
                     help2 * mathsFunc::sign(bodyFixedCoordinates.X * bodyFixedCoordinates.Y);
     hessian(0, 1) = hessian(1, 0);
     SmallMatrix<3, 3> A;
     getOrientation().getRotationMatrix(A);
     return A * hessian * (A.transpose());
 }
References abs(), axes_, eps1_, eps2_, BaseInteractable::getOrientation(), BaseInteractable::getPosition(), Quaternion::getRotationMatrix(), Eigen::bfloat16_impl::pow(), Quaternion::rotateBack(), mathsFunc::sign(), Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by getCurvature(), and getJacobianOfContactDetectionObjective().
computeMass()
void SuperQuadricParticle::computeMass (const ParticleSpecies & s) override virtual
Computes the particle's (inverse) mass and inertia.
Reimplemented from BaseParticle.
{
     if (isFixed()) return;
     if (getParticleDimensions()==3) {
         Mdouble volume = getVolume();
         Mdouble help1 = mathsFunc::beta(1.5 * eps2_, 0.5 * eps2_);
         Mdouble help2 = mathsFunc::beta(0.5 * eps1_, 2.0 * eps1_ + 1.0);
         Mdouble help3 = mathsFunc::beta(0.5 * eps2_, 0.5 * eps2_ + 1);
         Mdouble help4 = mathsFunc::beta(1.5 * eps1_, eps1_ + 1.0);
         invMass_ = 1.0 / (volume * s.getDensity());
         invInertia_.XX = 1.0 / (s.getDensity() * (0.5 * axes_.X * axes_.Y * axes_.Z * eps1_ * eps2_) *
                                    (axes_.Y * axes_.Y * help1 * help2
                                     + 4.0 * axes_.Z * axes_.Z * help3 * help4));
         invInertia_.XY = 0.0;
         invInertia_.XZ = 0.0;
         invInertia_.YY = 1.0 / (s.getDensity() * (0.5 * axes_.X * axes_.Y * axes_.Z * eps1_ * eps2_) *
                                    (axes_.X * axes_.X * help1 * help2
                                     + 4.0 * axes_.Z * axes_.Z * help3 * help4));
         invInertia_.YZ = 0.0;
         invInertia_.ZZ = 1.0 / (s.getDensity() * (0.5 * axes_.X * axes_.Y * axes_.Z * eps1_ * eps2_) *
                                    (axes_.X * axes_.X + axes_.Y * axes_.Y) * help1 * help2);
     } else {
         logger(ERROR, "[SuperQuadricParticle::computeMass] SuperQuadricParticle cannot be two-dimensional (yet)");
     }
 };
References axes_, mathsFunc::beta(), eps1_, eps2_, ERROR, BaseParticle::getParticleDimensions(), getVolume(), BaseParticle::invInertia_, BaseParticle::invMass_, BaseParticle::isFixed(), logger, s, Vec3D::X, MatrixSymmetric3D::XX, MatrixSymmetric3D::XY, MatrixSymmetric3D::XZ, Vec3D::Y, MatrixSymmetric3D::YY, MatrixSymmetric3D::YZ, Vec3D::Z, and MatrixSymmetric3D::ZZ.
computeResidualContactDetection()
SmallVector< 4 > SuperQuadricParticle::computeResidualContactDetection (const SmallVector< 4 > & position, const SuperQuadricParticle * p1, const SuperQuadricParticle * p2) const
Objective function for contact detection between the two given superquadrics. See Podlozhyuk et al. (2017) eq (22).
For the contact detection, we formulate the optimisation problem "minimise F1 + F2, s.t. F1 = F2", where F1 and F2 are the shape functions of particles 1 and 2. Define a Lagrange multiplier mu^2, then this is equivalent to solving "Gradient1 + mu^2 Gradient2 = 0, F1 - F2 = 0". The left-hand side of that function is computed in this function. See also Comp. Part. Mech. (2017) 4 : 101-118, equation 22.
Parameters
[in] position Current guess for the contact-point, where the expression above should be evaluated
[in] p1 First particle for which we are looking for a contact with.
[in] p2 Second particle for which we are looking for a contact with.
Returns
Residual of the objective function.
 {
     LabFixedCoordinates labFixedCoordinates;
     labFixedCoordinates.X = position[0];
     labFixedCoordinates.Y = position[1];
     labFixedCoordinates.Z = position[2];
     const Mdouble lagrangeMultiplier = position[3];
     // First compute the gradient of the superquadric shape function and then rotate it to the
     // global frame of reference
     SmallVector<3> gradThis = p1->computeShapeGradientLabFixed(labFixedCoordinates);
     SmallVector<3> gradOther = p2->computeShapeGradientLabFixed(labFixedCoordinates);
     // Eqn. (23) in Podhlozhnyuk et al, Comp. Part. Mech. 2017.
     // where contactPoint[3] = mu
     SmallVector<4> toBecomeZero;
     for (unsigned int i = 0; i < 3; ++i)
     {
         toBecomeZero[i] = gradThis[i] + lagrangeMultiplier * lagrangeMultiplier * gradOther[i];
     }
     toBecomeZero[3] = p1->computeShape(labFixedCoordinates) - p2->computeShape(labFixedCoordinates);
     return toBecomeZero;
 }
References computeShape(), computeShapeGradientLabFixed(), i, p1, Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by computeContactPoint().
computeShape()
Mdouble SuperQuadricParticle::computeShape (const LabFixedCoordinates & labFixedCoordinates) const
Compute and get the shape-functiion at the given (lab-fixed) position.
This function computes the value of the shape function in the lab-fixed coordinate system. The expression is provided in Section 2.3 of the article in Comp. Part. Mech. (2017) 4 : 101-118.
Returns
The value of the shape-function at the given (lab-fixed) coordinates.
 {
     BodyFixedCoordinates bodyFixedCoordinates = labFixedCoordinates - this->getPosition();
     getOrientation().rotateBack(bodyFixedCoordinates);
     const Mdouble n1 = 2. / eps1_;
     const Mdouble n2 = 2. / eps2_;
     return std::pow(std::pow(std::abs(bodyFixedCoordinates.X / axes_.X), n2)
                     + std::pow(std::abs(bodyFixedCoordinates.Y / axes_.Y), n2), n1 / n2)
            + std::pow(std::abs(bodyFixedCoordinates.Z / axes_.Z), n1) - 1.0;
 }
References abs(), axes_, eps1_, eps2_, BaseInteractable::getOrientation(), BaseInteractable::getPosition(), Eigen::bfloat16_impl::pow(), Quaternion::rotateBack(), Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by computeResidualContactDetection(), getInteractionWithSuperQuad(), isInContactWith(), and overlapFromContactPoint().
computeShapeGradientLabFixed()
SmallVector< 3 > SuperQuadricParticle::computeShapeGradientLabFixed (const LabFixedCoordinates & labFixedCoordinates) const
Compute and get the gradient of the shape-function at the given (lab-fixed) position.
This function computes the gradient ("first derivative") of the shape function in the lab-fixed coordinate system. The expressions are provided in Eq. 14 of the article in Comp. Part. Mech. (2017) 4 : 101-118.
Returns
The gradient of the shape function at the given (lab-fixed) coordinates. Note, that this is the gradient to the lab-fixed coordinates, \f nabla_X F(X)
Todo:
Come up with good expression for when x = y = 0 and n1 < n2
 {
     BodyFixedCoordinates bodyFixedCoordinates = labFixedCoordinates - this->getPosition();
     getOrientation().rotateBack(bodyFixedCoordinates);
     const Mdouble n1 = 2. / eps1_;
     const Mdouble n2 = 2. / eps2_;
     const Mdouble absXoa = std::abs(bodyFixedCoordinates.X / axes_.X);
     const Mdouble absYob = std::abs(bodyFixedCoordinates.Y / axes_.Y);
     const Mdouble absZoc = std::abs(bodyFixedCoordinates.Z / axes_.Z);
     const Mdouble nu = std::pow(absXoa, n2) + std::pow(absYob, n2);
     const Mdouble help1 = std::pow(nu, n1 / n2 - 1.0);
     Vec3D gradientBodyFixed = {
             (n1 / axes_.X) * std::pow(absXoa, n2 - 1.0) * help1 * mathsFunc::sign(bodyFixedCoordinates.X),
             (n1 / axes_.Y) * std::pow(absYob, n2 - 1.0) * help1 * mathsFunc::sign(bodyFixedCoordinates.Y),
             (n1 / axes_.Z) * std::pow(absZoc, n1 - 1.0) * mathsFunc::sign(bodyFixedCoordinates.Z)};
     //we get the gradient in terms of the lab-fixed coordinates by \nabla_X F(X) = A \nabla_x f(x).
     getOrientation().rotate(gradientBodyFixed);
     return {gradientBodyFixed.X, gradientBodyFixed.Y, gradientBodyFixed.Z};
 }
References abs(), axes_, eps1_, eps2_, BaseInteractable::getOrientation(), BaseInteractable::getPosition(), Eigen::bfloat16_impl::pow(), Quaternion::rotate(), Quaternion::rotateBack(), mathsFunc::sign(), Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by computeResidualContactDetection(), getCurvature(), getInteractionWithSuperQuad(), getJacobianOfContactDetectionObjective(), and overlapFromContactPoint().
copy()
SuperQuadricParticle * SuperQuadricParticle::copy () const override virtual
Copy method. It calls to copy constructor of this superquadric, useful for polymorphism.
Copy method. Uses copy constructor to create a copy on the heap. Useful for polymorphism.
Returns
pointer to the particle's copy
Implements NonSphericalParticle.
 {
     return new SuperQuadricParticle(*this);
 }
References SuperQuadricParticle().
Referenced by ContactDetectionTester::setupParticles().
getAxes()
Vec3D SuperQuadricParticle::getAxes () const override virtual
Get the axes-lengths of this superquadric. We use the super-ellipsoid definition stated in Chapter 2 of the book "Segmentation and recovery of superquadrics" by Jaklic et al.
Todo:
TW we could remove this function from the BaseParticle and use a dynamic_cast instead
ID Middle-term plan is to template the BaseParticle on shape-type, so that we won't have to cast etc.
Reimplemented from BaseParticle.
 {
     return axes_;
 }
References axes_.
Referenced by getContactPointPlanB(), writeDebugMessageStep1(), and writeDebugMessageStep2().
getContactPoint()
SmallVector< 4 > SuperQuadricParticle::getContactPoint (const SuperQuadricParticle * p, BaseInteraction * C) const
Compute the contact point between this and the given superquadric particle.
Computes the contact point between this and the given superquadric particle. It first gets a first guess for the contact point, and then uses that to compute the real contact-point with Newton-iterations.
Parameters
[in] p the particle with which we want to know the contact point with.
[in] C The contact between this and the give superquadric. Does not contain information of this time-step yet. This contact is used to see if there was an interaction between p and this superquadric in the time-step before, and if so, that contact point can serve as an initial point for contact-detection between the particles.
Returns
A SmallVector of length 4, with the contact point and the lagrange-multiplier needed for Newton's method for finding the contact point.
 {
     //Assuming contact between two spheres
     SmallVector<4> approximateContactPoint = getInitialGuessForContact(p, C);
     if (computeContactPoint(approximateContactPoint, this, p))
     {
         return approximateContactPoint;
     }
     else
     {
         return getContactPointPlanB(p, 4);
     }
 }
References computeContactPoint(), getContactPointPlanB(), getInitialGuessForContact(), and p.
Referenced by getInteractionWithSuperQuad(), and isInContactWith().
getContactPointPlanB()
SmallVector< 4 > SuperQuadricParticle::getContactPointPlanB (const SuperQuadricParticle * pOther, unsigned numberOfSteps) const
If the "normal" procedure fails to find a contact point, use an alternative approach that involves starting with two spheres to compute the interaction, and becoming less and less spherical.
If the "normal" method of finding a contact point diverges, then we start plan B. For this, we approximate the current and given particle by spheres, and move more and more towards the actual shape for the particles in small increments. This way, we have a relatively good starting point for each new optimisation problem, and therefore the chance that our contact-detection algorithm diverges is much smaller. This is based on equations (24) - (27) of Comp. Part. Mech. (2017) 4 : 101-118.
Parameters
[in] pOther Particle we want to know if the contact-point with
Returns
The point where the shape-functions of both particles are minimised.
 {
     logger(VERBOSE, "Number of iterations: %", numberOfSteps);
     // Step 1: Compute contact point for two volume equivalent spheres
     const Mdouble interactionRadiusThis = getInteractionRadius(pOther);
     const Mdouble interactionRadiusOther = pOther->getInteractionRadius(this);
     const Vec3D positionThis = getPosition();
     const Vec3D positionOther = pOther->getPosition();
     //analytical solution for contact point between bounding spheres
     const Vec3D initialPoint = (interactionRadiusOther * positionThis + interactionRadiusThis * positionOther) /
                                (interactionRadiusThis + interactionRadiusOther);
     SmallVector<4> contactPointPlanB;
     // Analytical solution
     contactPointPlanB[0] = initialPoint.X;
     contactPointPlanB[1] = initialPoint.Y;
     contactPointPlanB[2] = initialPoint.Z;
     contactPointPlanB[3] = 1.0; //Need to check.
     writeDebugMessageStep1(pOther, contactPointPlanB);
     //Step 2: Compute the deltas
     const Vec3D dAxesThis = (getAxes() - interactionRadiusThis * Vec3D(1, 1, 1)) / numberOfSteps;
     const Mdouble dn11 = (2.0 / getExponentEps1() - 2.0) / numberOfSteps;
     const Mdouble dn12 = (2.0 / getExponentEps2() - 2.0) / numberOfSteps;
     const Vec3D dAxesOther = (pOther->getAxes() - interactionRadiusOther * Vec3D(1, 1, 1)) / numberOfSteps;
     const Mdouble dn21 = (2.0 / pOther->getExponentEps1() - 2.0) / numberOfSteps;
     const Mdouble dn22 = (2.0 / pOther->getExponentEps2() - 2.0) / numberOfSteps;
     writeDebugMessageStep2(pOther, dAxesThis, dn11, dn12, dAxesOther, dn21, dn22);
     // Create two superquadrics with the above parameters for incrementally computing the contact point
     SuperQuadricParticle p1;
     SuperQuadricParticle p2;
     p1.setPosition(getPosition());
     p2.setPosition(pOther->getPosition());
     p1.setOrientation(getOrientation());
     p2.setOrientation(pOther->getOrientation());
     bool success = true;
     const unsigned maxIterations = 20;
     for (unsigned int counter = 1; counter <= numberOfSteps; ++counter)
     {
         // Step 3: Increment the shape and blockiness parameters
         const Vec3D axesThis = interactionRadiusThis * Vec3D(1, 1, 1) + counter * dAxesThis;
         const Mdouble n11 = 2.0 + counter * dn11;
         const Mdouble n12 = 2.0 + counter * dn12;
         Vec3D axesOther = interactionRadiusOther * Vec3D(1, 1, 1) + counter * dAxesOther;
         const Mdouble n21 = 2.0 + counter * dn21;
         const Mdouble n22 = 2.0 + counter * dn22;
         p1.setAxesAndExponents(axesThis, 2.0 / n11, 2.0 / n12);
         p2.setAxesAndExponents(axesOther, 2.0 / n21, 2.0 / n22);
         writeDebugMessageStep3(axesThis, n11, n12, axesOther, n21, n22);
         writeDebugMessageMiddleOfLoop(p1, p2, contactPointPlanB, counter);
         //compute the contact point of the new particles
         success = computeContactPoint(contactPointPlanB, &p1, &p2);
         if (!success)
         {
             if (numberOfSteps > maxIterations)
             {
                 write(std::cout);
                 pOther->write(std::cout);
                 logger(ERROR, "Plan B fails even with more than 20 intermediate steps");
             }
             return getContactPointPlanB(pOther, 2 * numberOfSteps);
         }
     }
     logger.assert_debug(p1.getAxes().X == getAxes().X, "In getContactPointPlanB, final particle for contact-detection not "
             "the same as original particle");
     logger(VERBOSE, "Plan B contact point: %", contactPointPlanB);
     return contactPointPlanB;
 }
References computeContactPoint(), ERROR, getAxes(), getExponentEps1(), getExponentEps2(), getInteractionRadius(), BaseInteractable::getOrientation(), BaseInteractable::getPosition(), logger, p1, setAxesAndExponents(), BaseInteractable::setOrientation(), BaseInteractable::setPosition(), VERBOSE, write(), writeDebugMessageMiddleOfLoop(), writeDebugMessageStep1(), writeDebugMessageStep2(), writeDebugMessageStep3(), X, Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by getContactPoint().
getCurvature()
Mdouble SuperQuadricParticle::getCurvature (const LabFixedCoordinates & labFixedCoordinates) const override virtual
Get the mean curvature of this superquadric at the given (lab-fixed) position, see Podlozhyuk et al. (2017) eq (39)
Compute the mean curvature, see Comp. Part. Mech. (2017) 4 : 101-118, eq (39)
Parameters
[in] labFixedCoordinates position in lab fixed coordinate system
Returns
mean curvature of particle at labFixedCoordinates
Todo:
Minus sign the wrong way around, check why
Reimplemented from BaseParticle.
 {
     SmallVector<3> gradientVec = computeShapeGradientLabFixed(labFixedCoordinates);
     SmallMatrix<3, 1> gradient = gradientVec;
     SmallMatrix<3, 3> hessian = computeHessianLabFixed(labFixedCoordinates);
     Mdouble helper = ((gradient.transpose() * hessian) * gradient)(0, 0);
     Mdouble gradientLength = gradientVec.length();
     Mdouble helper2 = gradientLength * gradientLength * (hessian(0, 0) + hessian(1, 1) + hessian(2, 2));
     Mdouble denominator = 2 * gradientLength * gradientLength * gradientLength;
     return (helper2 - helper) / denominator;
 }
References computeHessianLabFixed(), computeShapeGradientLabFixed(), SmallVector< numberOfRows >::length(), and SmallMatrix< numberOfRows, numberOfColumns >::transpose().
getExponentEps1()
Mdouble SuperQuadricParticle::getExponentEps1 () const override virtual
Get the first exponent of this superquadric. We use the super-ellipsoid definition stated in Chapter 2 of the book "Segmentation and recovery of superquadrics" by Jaklic et al.
Reimplemented from BaseParticle.
 {
     return eps1_;
 }
References eps1_.
Referenced by getContactPointPlanB(), and writeDebugMessageStep2().
getExponentEps2()
Mdouble SuperQuadricParticle::getExponentEps2 () const override virtual
Get the second exponent of this superquadric. We use the super-ellipsoid definition stated in Chapter 2 of the book "Segmentation and recovery of superquadrics" by Jaklic et al.
Reimplemented from BaseParticle.
 {
     return eps2_;
 }
References eps2_.
Referenced by getContactPointPlanB(), and writeDebugMessageStep2().
getInitialGuessForContact()
SmallVector< 4 > SuperQuadricParticle::getInitialGuessForContact (const SuperQuadricParticle * pQuad, BaseInteraction * C) const
Get an initial guess for the contact-point between this particle and the given particle.
For the contact-detection, we need an initial guess where the contact will be (Newton's method only converges if you start sufficiently close). If there was already a contact during the last time-step, the values of the contact-point of last time-step is taken, otherwise it is taken as the middle between both particle-positions.
Parameters
pQuad other superquadric for which we want to know if there is a contact
C contact between this particle and the given particle
Returns
A guess for the initial contact: contact point X,Y,Z, lagrange multiplier. Note that these are given in the LAB-FIXED coordinates.
 {
     SmallVector<4> approximateContactPoint;
     if (C == nullptr || C->getOverlap() < 1e-15)
     {
         //this is a new interaction
         const LabFixedCoordinates branchVector = pQuad->getPosition() - getPosition();
         //Get the square of the distance between particle i and particle j
         const Mdouble distanceSquared = Vec3D::getLengthSquared(branchVector);
         const Mdouble distance = sqrt(distanceSquared);
         const LabFixedCoordinates normal = (branchVector / distance);
         const Mdouble overlap = getSumOfInteractionRadii(pQuad) - distance;
         const LabFixedCoordinates contactPoint = (pQuad->getPosition() -
                                                   (pQuad->getInteractionRadius(this) - 0.5 * overlap) * normal);
         approximateContactPoint[0] = contactPoint.X;
         approximateContactPoint[1] = contactPoint.Y;
         approximateContactPoint[2] = contactPoint.Z;
         approximateContactPoint[3] = 1;
     }
     else
     {
         //this is an existing interaction
         const LabFixedCoordinates contactPoint = C->getContactPoint();
         const Mdouble multiplier = C->getLagrangeMultiplier();
         approximateContactPoint[0] = contactPoint.X;
         approximateContactPoint[1] = contactPoint.Y;
         approximateContactPoint[2] = contactPoint.Z;
         approximateContactPoint[3] = multiplier;
     }
     return approximateContactPoint;
 }
References e(), getInteractionRadius(), Vec3D::getLengthSquared(), BaseInteractable::getPosition(), BaseParticle::getSumOfInteractionRadii(), Global_Physical_Variables::multiplier(), WallFunction::normal(), sqrt(), Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by getContactPoint().
getInteractionRadius()
Mdouble SuperQuadricParticle::getInteractionRadius (const BaseParticle * particle) const
returns the radius plus half the interactionDistance of the mixed species
 {
     const auto mixedSpecies = getSpecies()->getHandler()->getMixedObject(getSpecies(),particle->getSpecies());
     return getRadius() + 0.5 * mixedSpecies->getInteractionDistance();
 }
References BaseSpecies::getHandler(), SpeciesHandler::getMixedObject(), BaseParticle::getRadius(), and BaseInteractable::getSpecies().
Referenced by getContactPointPlanB(), getInitialGuessForContact(), and writeDebugMessageStep1().
getInteractionWith()
BaseInteraction * SuperQuadricParticle::getInteractionWith (BaseParticle * P, unsigned timeStamp, InteractionHandler * interactionHandler) override virtual
Checks if this superquadric is in interaction with the given particle, and if so, returns vector of pointer to the associated BaseInteraction object (else returns empty vector).
Overwrites BaseInteractable::getInteractionWith. First checks if the bounding radii overlap, and if so, changes the given particle into a superquadric and calls getInteractionWithSuperQuadric to obtain the relevant contact data.
Parameters
p Pointer to the particle we want to get the interaction with, can be any type of particle
timeStamp Time stamp to be assigned to the interaction object (i.e., the current time)
interactionHandler BaseInteraction container from where the interaction is retrieved, and to which it is assigned (if it is a new interaction).
Returns
A vector with size 1 (if there is an interaction) or 0 (if there is no interaction).
Reimplemented from BaseParticle.
 {
     //get the normal (from P away from the contact)
     const LabFixedCoordinates branchVector = p->getPosition() - getPosition();
     //Get the square of the distance between particle i and particle j
     const Mdouble distanceSquared = Vec3D::getLengthSquared(branchVector);
     const Mdouble sumOfInteractionRadii = getMaxInteractionRadius()+p->getMaxInteractionRadius();
     if (distanceSquared < (sumOfInteractionRadii * sumOfInteractionRadii))
     {
         if (p->isSphericalParticle())
         {
             SuperQuadricParticle* pQuad = new SuperQuadricParticle;
             pQuad->setAxes(p->getRadius(), p->getRadius(), p->getRadius());
             BaseInteraction* contacts = getInteractionWithSuperQuad(pQuad, timeStamp, interactionHandler);
             delete pQuad;
             return contacts;
         } else {
             SuperQuadricParticle* pQuad = static_cast<SuperQuadricParticle*>(p);
             return getInteractionWithSuperQuad(pQuad, timeStamp, interactionHandler);
         }
     }
     return nullptr;
 }
References getInteractionWithSuperQuad(), Vec3D::getLengthSquared(), BaseParticle::getMaxInteractionRadius(), BaseInteractable::getPosition(), p, setAxes(), and SuperQuadricParticle().
Referenced by ContactDetectionTester::testEllipsoidsContact(), and ContactDetectionTester::testSpheresContact().
getInteractionWithSuperQuad()
BaseInteraction * SuperQuadricParticle::getInteractionWithSuperQuad (SuperQuadricParticle * p, unsigned timeStamp, InteractionHandler * interactionHandler)
Checks if this superquadric is in interaction with the given superquadric, and if so, returns vector of pointer to the associated BaseInteraction object (else returns empty vector).
Computes all relevant information for the contact between this and a superquadric particle. Returns nullptr if there is no (positive) overlap.
Parameters
[in] p Superquadric particle we want to have the contact-information for
[in] timeStamp Time stamp to be assigned to the interaction object (i.e., the current time)
[in] interactionHandler BaseInteraction container from where the interaction is retrieved, and to which it is assigned (if it is a new interaction).
Returns
A vector of Interaction* with size 1 (if there is an interaction) or 0 (if there is no interaction).
Todo:
: find correct value for 'distance'
 {
     BaseInteraction* const C = interactionHandler->getInteraction(p, this, timeStamp);
     const SmallVector<4> approximateContactPoint = getContactPoint(p, C);
     //set the new contact point:
     LabFixedCoordinates contactPoint;
     contactPoint.X = approximateContactPoint[0];
     contactPoint.Y = approximateContactPoint[1];
     contactPoint.Z = approximateContactPoint[2];
     //if the minimum is positive, there is no contact: return empty vector
     if (computeShape(contactPoint) > -1e-10)
     {
         interactionHandler->removeObject(C->getIndex());
         return nullptr;
     }
     C->setContactPoint(contactPoint);
     C->setLagrangeMultiplier(approximateContactPoint[3]);
     SmallVector<3> gradThis = computeShapeGradientLabFixed(contactPoint).getNormalised();
     LabFixedCoordinates normal;
     normal.X = gradThis[0];
     normal.Y = gradThis[1];
     normal.Z = gradThis[2];
     C->setNormal(normal);
     const Mdouble alphaI = overlapFromContactPoint(contactPoint, normal);
     const Mdouble alphaJ = p->overlapFromContactPoint(contactPoint, -normal);
     C->setOverlap(alphaI + alphaJ);
     C->setDistance((getPosition() - p->getPosition()).getLength() - C->getOverlap());
     return C;
 }
References computeShape(), computeShapeGradientLabFixed(), e(), getContactPoint(), InteractionHandler::getInteraction(), BaseInteractable::getPosition(), WallFunction::normal(), overlapFromContactPoint(), p, BaseHandler< T >::removeObject(), Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by getInteractionWith().
getJacobianOfContactDetectionObjective()
SmallMatrix< 4, 4 > SuperQuadricParticle::getJacobianOfContactDetectionObjective (const SmallVector< 4 > & contactPoint, const SuperQuadricParticle * p1, const SuperQuadricParticle * p2) const
Compute and return the derivative of functionThatShouldBecomeZeroForContactDetection, both to the position and the Lagrange multiplier, and evaluated at the contact point.
Compute and return the derivative of computeResidualContactDetection, both to the position and the Lagrange multiplier, and evaluated at the contact point. This is done in order to use Newton's method on computeResidualContactDetection, which comes from Comp. Part. Mech. (2017) 4 : 101-118.
The result is a 4x4 matrix, with 4 parts: [0,2]x[0,2] (upper-left corner): Hessian1 + mu^2 Hessian2, where Hessian is the "second derivative" of the shape function and mu^2 the Lagrange multiplier. This is the derivative of (22a) to x in Comp. Part. Mech. (2017) 4 : 101-118. [0,2]x[3] (upper-right corner): 2 * mu * Gradient2, where Gradient is the gradient of the shape function and mu is the Lagrange multiplier. This is the derivative of (22a) to mu in Comp. Part. Mech. (2017) 4 : 101-118. [3]x[0,2] (lower-left corner): Gradient1 - Gradient2, where Gradient is the gradient of the shape function. This is the derivative of (22b) to x in Comp. Part. Mech. (2017) 4 : 101-118. [3]x[3] (lower-right corner): 0. This is the derivative of (22b) to mu in Comp. Part. Mech. (2017) 4 : 101-118.
In order to compute these parts, first compute the first and second derivative of the shape function (the gradient and hessian) in the lab-fixed coordinate system for both particles. To do so, we apply the rotation matrix A on the body-fixed first and second derivative of the shape function, which are computed in the functions computeShapeGradientBodyFixed() and computeHessian(). The expressions for the purpose of mapping are provided in Eq. 18 of the article in Comp. Part. Mech. (2017) 4 : 101-118. Then fill in the respective contributions.
Parameters
[in] contactPoint The contact point where this Jacobian should be evaluated
[in] p1 First particle in the contact for which this Jacobian should be evaluated
[in] p2 Second particle in the contact for which this Jacobian should be evaluated
Returns
A 4x4 matrix with the Jacobian of computeResidualContactDetection.
 {
     LabFixedCoordinates labFixedCoordinates;
     labFixedCoordinates.X = contactPoint[0];
     labFixedCoordinates.Y = contactPoint[1];
     labFixedCoordinates.Z = contactPoint[2];
     const Mdouble lagrangeMultiplier = contactPoint[3];
     SmallVector<3> gradThis = p1->computeShapeGradientLabFixed(labFixedCoordinates);
     SmallVector<3> gradOther = p2->computeShapeGradientLabFixed(labFixedCoordinates);
     SmallMatrix<3, 3> hessianThis = p1->computeHessianLabFixed(labFixedCoordinates);
     SmallMatrix<3, 3> hessianOther = p2->computeHessianLabFixed(labFixedCoordinates);
     SmallMatrix<3, 3> upperLeftCorner = hessianThis + lagrangeMultiplier * lagrangeMultiplier * hessianOther;
     SmallMatrix<4, 4> jacobian;
     for (unsigned int i = 0; i < 3; ++i)
     {
         for (unsigned int j = 0; j < 3; ++j)
         {
             jacobian(i, j) = upperLeftCorner(i, j);
         }
         jacobian(i, 3) = 2 * lagrangeMultiplier * gradOther[i];
     }
     for (unsigned int j = 0; j < 3; ++j)
     {
         jacobian(3, j) = gradThis[j] - gradOther[j];
     }
     return jacobian;
 }
References computeHessianLabFixed(), computeShapeGradientLabFixed(), i, j, p1, Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by computeContactPoint().
getName()
std::string SuperQuadricParticle::getName () const override virtual
Returns the name of the class, here "SuperQuadric".
Returns the name of the object; in this case "SuperQuadricParticle".
Returns
The std::string "SuperQuadricParticle".
Implements NonSphericalParticle.
 {
     return "SuperQuadricParticle";
 }
getVolume()
Mdouble SuperQuadricParticle::getVolume () const override virtual
Get the volume of this superquadric.
Returns the volume of the SuperEllipsoid, which is calculated using its principal axis and the exponents. The analytical expressions are taken from Chapter 2 of the book "Segmentation and Recovery of Superquadrics" by Jaklic et al . However, the beta functions that are part of these expressions are approximations, see ExtendedMath.cc
Returns
The actual volume of this superquadric.
Reimplemented from BaseParticle.
 {
     logger.assert_debug(getHandler() != nullptr, "[SuperQuadricParticle::getVolume] no particle handler specified");
     return (2.0 * axes_.X * axes_.Y * axes_.Z * eps1_ * eps2_) * mathsFunc::beta(0.5 * eps1_ + 1.0, eps1_) *
            mathsFunc::beta(0.5 * eps2_, 0.5 * eps2_);
 }
References axes_, mathsFunc::beta(), eps1_, eps2_, BaseParticle::getHandler(), logger, Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by computeMass().
isInContactWith()
bool SuperQuadricParticle::isInContactWith (const BaseParticle * p) const override virtual
Get whether or not this superquadric is in contact with the given particle.
Get whether or not this superquadric is in contact with the given particle: first transform the particle to a superquadric if necessary, then compute the contact-point using the function getContactPoint. If the shape-function at the contact point is negative, then there is a contact with the given particle, and otherwise not
Parameters
[in] p The particle for which we want to know if there is a contact
Returns
True if there is a contact, false otherwise.
Reimplemented from BaseParticle.
 {
     SmallVector<4> approximateContactPoint;
     if (p->isSphericalParticle())
     {
         SuperQuadricParticle* pQuad = new SuperQuadricParticle;
         pQuad->setAxes(p->getRadius(), p->getRadius(), p->getRadius());
         approximateContactPoint = getContactPoint(pQuad, nullptr);
         delete pQuad;
     } else {
         const SuperQuadricParticle* pQuad = static_cast<const SuperQuadricParticle*>(p);
         approximateContactPoint = getContactPoint(pQuad, nullptr);
     }
     //set the new contact point:
     LabFixedCoordinates contactPoint;
     contactPoint.X = approximateContactPoint[0];
     contactPoint.Y = approximateContactPoint[1];
     contactPoint.Z = approximateContactPoint[2];
     //if the minimum is positive, there is no contact: return false
     return (computeShape(contactPoint) < 0);
 }
References computeShape(), getContactPoint(), p, setAxes(), SuperQuadricParticle(), Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by ContactDetectionTester::testEllipsoidsContact().
overlapFromContactPoint()
Mdouble SuperQuadricParticle::overlapFromContactPoint (const LabFixedCoordinates & contactPoint, const LabFixedCoordinates & normal) const
Compute the distance between the contact-point and surface of this superquadric particle.
Compute the distance between the contact-point and surface of this superquadric particle with Newton-iterations. This is the procedure as described by Comp. Part. Mech. (2017) 4 : 101-118, eq 37.
Parameters
[in] contactPoint The contact point between this particle with another BaseInteractable
[in] normal The normal direction of the contact.
Returns
Distance between contact-point and surface of this particle
 {
     Mdouble alphaI = 0;
     LabFixedCoordinates xEdge = contactPoint + alphaI * normal;
     Mdouble dampingCoefficient = 1;
     while (std::abs(computeShape(xEdge)) > 1e-10)
     {
         SmallVector<3> gradientShape = computeShapeGradientLabFixed(xEdge);
         LabFixedCoordinates gradient;
         gradient.X = gradientShape(0);
         gradient.Y = gradientShape(1);
         gradient.Z = gradientShape(2);
         Mdouble newValue = alphaI - dampingCoefficient * computeShape(xEdge) / Vec3D::dot(gradient, normal);
         const LabFixedCoordinates xEdgeNew = contactPoint + newValue * normal;
         if (std::abs(computeShape(xEdgeNew)) < std::abs(computeShape(xEdge)))
         {
             alphaI = newValue;
             xEdge = xEdgeNew;
             dampingCoefficient = 1;
         }
         else
         {
             dampingCoefficient /= 2;
             if (dampingCoefficient < 1e-10)
             {
                 logger(ERROR, "overlap detection does not converge");
             }
         }
     }
     return alphaI;
 }
References abs(), computeShape(), computeShapeGradientLabFixed(), Vec3D::dot(), e(), ERROR, logger, WallFunction::normal(), Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by getInteractionWithSuperQuad().
read()
void SuperQuadricParticle::read (std::istream & is) override virtual
Read function: read in the information for this superquadric from the given input-stream, for example a restart file.
Particle read function, which reads the axes_ and both epsilons from the given input-stream.
Parameters
[in,out] is input stream with particle properties, e.g. a restart-file.
Reimplemented from BaseParticle.
 {
     BaseParticle::read(is);
     std::string dummy;
     is >> dummy >> axes_ >> dummy >> eps1_ >> dummy >> eps2_;
     logger.assert_always(eps1_ < 1 + 1e-10, "epsilon1 should be at most 1");
     logger.assert_always(eps2_ < 1 + 1e-10, "epsilon2 should be at most 1");
 }
References axes_, e(), eps1_, eps2_, logger, BaseParticle::read(), and oomph::Global_string_for_annotation::string().
setAxes() [1/2]
void SuperQuadricParticle::setAxes (const Mdouble & a1, const Mdouble & a2, const Mdouble & a3)
Set the axes-lengths to a1, a2 and a3 for this superquadric. We use the super-ellipsoid definition stated in Chapter 2 of the book "Segmentation and recovery of superquadrics" by Jaklic et al.
 {
     setAxes({a1,a2,a3});
 }
Referenced by getInteractionWith(), isInContactWith(), setAxesAndExponents(), ContactDetectionTester::testEllipsoidsContact(), and ContactDetectionWithWallTester::testEllipsoidsContact().
setAxes() [2/2]
void SuperQuadricParticle::setAxes (const Vec3D & axes) override virtual
Set the axes-lengths to axes for this superquadric. We use the super-ellipsoid definition stated in Chapter 2 of the book "Segmentation and recovery of superquadrics" by Jaklic et al.
Reimplemented from BaseParticle.
 {
     axes_ = axes;
     setBoundingRadius();
     if (getSpecies() != nullptr)
     {
         getSpecies()->computeMass(this);
     }
 }
References axes_, ParticleSpecies::computeMass(), BaseInteractable::getSpecies(), and setBoundingRadius().
setAxesAndExponents() [1/2]
void SuperQuadricParticle::setAxesAndExponents (const Mdouble & a1, const Mdouble & a2, const Mdouble & a3, const Mdouble & eps1, const Mdouble & eps2)
Set the geometrical properties of the superquadrics, namely the axes-lengths a1, a2 and a3, and the exponents epsilon1 and epsilon2. We use the super-ellipsoid definition stated in Chapter 2 of the book "Segmentation and recovery of superquadrics" by Jaklic et al.
 {
     eps1_ = eps1;
     eps2_ = eps2;
     logger.assert_always(eps1_ < 1 + 1e-10, "epsilon1 should be at most 1");
     logger.assert_always(eps2_ < 1 + 1e-10, "epsilon2 should be at most 1");
     setAxes(a1,a2,a3);
 }
References e(), eps1_, eps2_, logger, and setAxes().
Referenced by getContactPointPlanB(), GranularCollapse::setupInitialConditions(), ContactDetectionWithWallTester::setupParticleAndWall(), and ContactDetectionTester::setupParticles().
setAxesAndExponents() [2/2]
void SuperQuadricParticle::setAxesAndExponents (const Vec3D & axes, const Mdouble & eps1, const Mdouble & eps2)
Set the geometrical properties of the superquadrics, namely the axes-lengths axes, and the exponents epsilon1 and epsilon2. We use the super-ellipsoid definition stated in Chapter 2 of the book "Segmentation and recovery of superquadrics" by Jaklic et al.
 {
     eps1_ = eps1;
     eps2_ = eps2;
     logger.assert_always(eps1_ < 1 + 1e-10, "epsilon1 should be at most 1");
     logger.assert_always(eps2_ < 1 + 1e-10, "epsilon2 should be at most 1");
     setAxes(axes);
 }
References e(), eps1_, eps2_, logger, and setAxes().
setBoundingRadius()
void SuperQuadricParticle::setBoundingRadius () private
Get the radius of the sphere that fits precisely around the particle.
Todo:
Currently only implemented for ellipsoids
 {
     if(mathsFunc::isEqual(eps2_,1,std::numeric_limits<Mdouble>::epsilon()) && mathsFunc::isEqual(eps1_,1,std::numeric_limits<Mdouble>::epsilon()))
     {
         BaseParticle::setRadius(std::max(std::max(axes_.Y,axes_.X),axes_.Z));
         return;
     }else
     {
         const Mdouble axesX = std::max(axes_.X, axes_.Y);
         const Mdouble axesY = std::min(axes_.X, axes_.Y);
         Mdouble alpha;
         const Mdouble eps1 = std::min(.96, eps1_);
         const Mdouble eps2 = std::min(.96, eps2_);
         alpha = std::pow(axesY / axesX, 2.0 / (2.0 / eps2 - 2.0));
         const Mdouble help1 = std::pow(alpha, 2.0 / eps2);
         const Mdouble gamma = std::pow(1.0 + help1, eps2 / eps1 - 1.0);
         const Mdouble beta = std::pow(gamma * axes_.Z * axes_.Z / (axesX * axesX), 1.0 / (2.0 / eps1 - 2.0));
         const Mdouble xTilde = std::pow(std::pow(1 + help1, eps2 / eps1) + std::pow(beta, 2.0 / eps1),
                                         -eps1 / 2.0);
         BaseParticle::setRadius(std::sqrt(mathsFunc::square(axesX * xTilde)
                                           + mathsFunc::square(alpha * axesY * xTilde)
                                           + mathsFunc::square(beta * axes_.Z * xTilde)));
     }
 }
References alpha, axes_, beta, eps1_, eps2_, oomph::SarahBL::epsilon, mathsFunc::gamma(), mathsFunc::isEqual(), max, min, Eigen::bfloat16_impl::pow(), BaseParticle::setRadius(), sqrt(), mathsFunc::square(), Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by setAxes(), and setExponents().
setExponents()
void SuperQuadricParticle::setExponents (const Mdouble & eps1, const Mdouble & eps2) override virtual
Set the exponents to eps1 and eps2 for this superquadric. We use the super-ellipsoid definition stated in Chapter 2 of the book "Segmentation and recovery of superquadrics" by Jaklic et al.
Reimplemented from BaseParticle.
 {
     eps1_ = eps1;
     eps2_ = eps2;
     setBoundingRadius();
     logger.assert_always(eps1_ < 1 + 1e-10, "epsilon1 should be at most 1");
     logger.assert_always(eps2_ < 1 + 1e-10, "epsilon2 should be at most 1");
     if (getSpecies() != nullptr)
     {
         getSpecies()->computeMass(this);
     }
 }
References ParticleSpecies::computeMass(), e(), eps1_, eps2_, BaseInteractable::getSpecies(), logger, and setBoundingRadius().
setInertia()
void SuperQuadricParticle::setInertia () override virtual
Compute and set the inertia-tensor for this superquadric. For internal use only.
This function computes the principal moments of inertia for the superellipsoids. Again, the analytical expressions are taken from Chapter 2 (pg. 36) of the book "Segmentation and Recovery of Superquadrics" by by Jaklic et al .
Reimplemented from BaseParticle.
 {
     MatrixSymmetric3D inertia;
     inertia.XX = getSpecies()->getDensity() * (0.5 * axes_.X * axes_.Y * axes_.Z * eps1_ * eps2_) *
                  (axes_.Y * axes_.Y * mathsFunc::beta(1.5 * eps2_, 0.5 * eps2_) *
                   mathsFunc::beta(0.5 * eps1_, 2.0 * eps1_ + 1.0)
                   + 4.0 * axes_.Z * axes_.Z * mathsFunc::beta(0.5 * eps2_, 0.5 * eps2_ + 1) *
                     mathsFunc::beta(1.5 * eps1_, eps1_ + 1.0));
     inertia.YY = getSpecies()->getDensity() * (0.5 * axes_.X * axes_.Y * axes_.Z * eps1_ * eps2_) *
                  (axes_.X * axes_.X * mathsFunc::beta(1.5 * eps2_, 0.5 * eps2_) *
                   mathsFunc::beta(0.5 * eps1_, 2.0 * eps1_ + 1.0)
                   + 4.0 * axes_.Z * axes_.Z * mathsFunc::beta(0.5 * eps2_, 0.5 * eps2_ + 1) *
                     mathsFunc::beta(1.5 * eps1_, eps1_ + 1.0));
     inertia.ZZ = getSpecies()->getDensity() * (0.5 * axes_.X * axes_.Y * axes_.Z * eps1_ * eps2_) *
                  (axes_.X * axes_.X + axes_.Y * axes_.Y) * mathsFunc::beta(1.5 * eps2_, 0.5 * eps2_) *
                  mathsFunc::beta(0.5 * eps1_, 2.0 * eps1_ + 1.0);
     BaseParticle::setInertia(inertia);
 }
References axes_, mathsFunc::beta(), eps1_, eps2_, ParticleSpecies::getDensity(), BaseInteractable::getSpecies(), BaseParticle::setInertia(), Vec3D::X, MatrixSymmetric3D::XX, Vec3D::Y, MatrixSymmetric3D::YY, Vec3D::Z, and MatrixSymmetric3D::ZZ.
Referenced by EllipsoidsBouncingOnWallDemo::setupInitialConditions(), GranularCollapse::setupInitialConditions(), ContactDetectionWithWallTester::setupParticleAndWall(), and ContactDetectionTester::setupParticles().
setRadius()
void SuperQuadricParticle::setRadius (const Mdouble radius) override virtual
Sets the particle's radius_ (and adjusts the mass_ accordingly, based on the particle's species)
Sets the radius of the particle, and from that computes the new mass (using its species) and checks whether it now is either the smallest or biggest particle in its ParticleHandler.
Parameters
[in] radius the new radius
Reimplemented from BaseParticle.
 {
     logger(ERROR,"This function should not be used");
 }
References ERROR, and logger.
write()
void SuperQuadricParticle::write (std::ostream & os) const override virtual
Write function: write this SuperQuadric to the given output-stream, for example a restart-file.
SuperQuadricParticle print method, which accepts an std::ostream as input. It prints human readable SuperQuadricParticle information to the given output-stream.
Parameters
[in,out] os stream to which the info is written, e.g. a restart-file or std::cout.
Reimplemented from BaseParticle.
 {
     BaseParticle::write(os);
     os << " axes " << axes_
        << " exp1 " << eps1_
        << " exp2 " << eps2_;
 }
References axes_, eps1_, eps2_, and BaseParticle::write().
Referenced by getContactPointPlanB().
writeDebugMessageMiddleOfLoop()
void SuperQuadricParticle::writeDebugMessageMiddleOfLoop (const SuperQuadricParticle & p1, const SuperQuadricParticle & p2, SmallVector< 4 > & contactPointPlanB, const unsigned int & counter) const
 {
     logger(VERBOSE, "Position of particle 1 (p1): % \nPosition of particle 2 (p2): % \n",
            p1.getPosition(), p2.getPosition());
     logger(VERBOSE, "Orientation of particle 1 (p1): % \nOrientation of particle 2 (p2): %\n",
            p1.getOrientation(), p2.getOrientation());
     // Step 4: Calculate the contact point for the updated shape parameters
     logger(VERBOSE, "----------------------------------------");
     logger(VERBOSE, "STEP 4: Compute contact point");
     logger(VERBOSE, "----------------------------------------");
     logger(VERBOSE, " ");
     logger(VERBOSE, "Counter: %", counter);
     logger(VERBOSE, " ");
     logger(VERBOSE, "Analytical solution Contact Point: % ", contactPointPlanB);
     logger(VERBOSE, " ");
 }
References BaseInteractable::getOrientation(), BaseInteractable::getPosition(), logger, p1, and VERBOSE.
Referenced by getContactPointPlanB().
writeDebugMessageStep1()
void SuperQuadricParticle::writeDebugMessageStep1 (const SuperQuadricParticle * pQuad, const SmallVector< 4 > & contactPointPlanB) const
 {
     logger(VERBOSE, "---------------------");
     logger(VERBOSE, "STEP 1");
     logger(VERBOSE, "---------------------\n");
     logger(VERBOSE, "Position of particle 1: % ", getPosition());
     logger(VERBOSE, "Position of particle 2 (pQuad): % ", pQuad->getPosition());
     logger(VERBOSE, " ");
     logger(VERBOSE, "Radius of particle 1: % ", getInteractionRadius(pQuad));
     logger(VERBOSE, "Radius of particle 2 (pQuad): % \n", pQuad->getInteractionRadius(this));
     logger(VERBOSE, "Orientation of particle 1: % ", getOrientation());
     logger(VERBOSE, "Orientation of particle 2 (pQuad): % ", pQuad->getOrientation());
     logger(VERBOSE, " ");
     logger(VERBOSE, "Particle 1 axes: %", getAxes());
     logger(VERBOSE, "Particle 2 axes (pQuad): % \n", pQuad->getAxes());
     logger(VERBOSE, "Analytical solution for two equivalent spheres in contact: % \n", contactPointPlanB);
 }
References getAxes(), getInteractionRadius(), BaseInteractable::getOrientation(), BaseInteractable::getPosition(), logger, and VERBOSE.
Referenced by getContactPointPlanB().
writeDebugMessageStep2()
void SuperQuadricParticle::writeDebugMessageStep2 (const SuperQuadricParticle * pQuad, const Vec3D & dAxesThis, const Mdouble & dn11, const Mdouble & dn12, const Vec3D & dAxesOther, const Mdouble & dn21, const Mdouble & dn22) const
 {
     logger(VERBOSE, "---------------------");
     logger(VERBOSE, "STEP 2");
     logger(VERBOSE, "---------------------");
     logger(VERBOSE, " ");
     logger(VERBOSE, "Particle 1 x-scale: %", pQuad->getAxes().X);
     logger(VERBOSE, "Particle 1 y-scale: %", pQuad->getAxes().Y);
     logger(VERBOSE, "Particle 1 z-scale: %", pQuad->getAxes().Z);
     logger(VERBOSE, "Particle 1 n1: %", 2. / pQuad->getExponentEps1());
     logger(VERBOSE, "Particle 1 n2: %", 2. / pQuad->getExponentEps2());
     logger(VERBOSE, " ");
     logger(VERBOSE, "Particle 1 x-scale increment: %", dAxesThis.X);
     logger(VERBOSE, "Particle 1 y-scale increment: %", dAxesThis.Y);
     logger(VERBOSE, "Particle 1 z-scale increment: %", dAxesThis.Z);
     logger(VERBOSE, "Particle 1 n1 increment: %", dn11);
     logger(VERBOSE, "Particle 1 n2 increment: %", dn12);
     logger(VERBOSE, " ");
     logger(VERBOSE, "Particle 2 x-scale: %", getAxes().X);
     logger(VERBOSE, "Particle 2 y-scale: %", getAxes().Y);
     logger(VERBOSE, "Particle 2 z-scale: %", getAxes().Z);
     logger(VERBOSE, "Particle 2 n1: %", 2. / getExponentEps1());
     logger(VERBOSE, "Particle 2 n2: %", 2. / getExponentEps2());
     logger(VERBOSE, " ");
     logger(VERBOSE, "Particle 2 x-scale increment: %", dAxesOther.X);
     logger(VERBOSE, "Particle 2 y-scale increment: %", dAxesOther.Y);
     logger(VERBOSE, "Particle 2 z-scale increment: %", dAxesOther.Z);
     logger(VERBOSE, "Particle 2 n1 increment: %", dn21);
     logger(VERBOSE, "Particle 2 n2 increment: %", dn22);
     logger(VERBOSE, " ");
 }
References getAxes(), getExponentEps1(), getExponentEps2(), logger, VERBOSE, X, Vec3D::X, Y, Vec3D::Y, Z, and Vec3D::Z.
Referenced by getContactPointPlanB().
writeDebugMessageStep3()
void SuperQuadricParticle::writeDebugMessageStep3 (const Vec3D & axesThis, const Mdouble & n11, const Mdouble & n12, const Vec3D & axesOther, const Mdouble & n21, const Mdouble & n22) const
 {
     logger(VERBOSE, "-----------------------------------");
     logger(VERBOSE, "STEP 3: First increment");
     logger(VERBOSE, "-----------------------------------");
     logger(VERBOSE, " ");
     logger(VERBOSE, "Particle 1 x-scale after increment: %", axesThis.X);
     logger(VERBOSE, "Particle 1 y-scale after increment: %", axesThis.Y);
     logger(VERBOSE, "Particle 1 z-scale after increment: %", axesThis.Z);
     logger(VERBOSE, "Particle 1 n1 after increment: %", n11);
     logger(VERBOSE, "Particle 1 n2 after increment: %", n12);
     logger(VERBOSE, " ");
     logger(VERBOSE, "Particle 2 x-scale after increment: %", axesOther.X);
     logger(VERBOSE, "Particle 2 y-scale after increment: %", axesOther.Y);
     logger(VERBOSE, "Particle 2 z-scale after increment: %", axesOther.Z);
     logger(VERBOSE, "Particle 2 n1 after increment: %", n21);
     logger(VERBOSE, "Particle 2 n2 after increment: %", n22);
     logger(VERBOSE, " ");
 }
References logger, VERBOSE, Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by getContactPointPlanB().
Member Data Documentation
axes_
Vec3D SuperQuadricParticle::axes_ private
Lengths of principal axes (a1, a2, a3).
Referenced by computeHessianLabFixed(), computeMass(), computeShape(), computeShapeGradientLabFixed(), getAxes(), getVolume(), read(), setAxes(), setBoundingRadius(), setInertia(), SuperQuadricParticle(), and write().
eps1_
Mdouble SuperQuadricParticle::eps1_ private
Blockiness parameters.
Blockiness parameters should be in the range (0,1], where a sphere or ellipsoid is represented by eps1_ = eps2_ = 1.
Referenced by computeHessianLabFixed(), computeMass(), computeShape(), computeShapeGradientLabFixed(), getExponentEps1(), getVolume(), read(), setAxesAndExponents(), setBoundingRadius(), setExponents(), setInertia(), SuperQuadricParticle(), and write().
eps2_
Mdouble SuperQuadricParticle::eps2_ private
Referenced by computeHessianLabFixed(), computeMass(), computeShape(), computeShapeGradientLabFixed(), getExponentEps2(), getVolume(), read(), setAxesAndExponents(), setBoundingRadius(), setExponents(), setInertia(), SuperQuadricParticle(), and write().
The documentation for this class was generated from the following files:
SuperQuadricParticle.h
SuperQuadricParticle.cc