MercuryDPM: MergeRestartFiles Namespace Reference
MergeRestartFiles Namespace Reference
Variables
simulation_name = sys.argv[1:][0]
string root_filename = simulation_name + '.restart0'
f = open(root_filename, 'r+')
bool found = False
line = f.readline()
tokens = line.split()
nProc = int(tokens[i+1])
string filename = simulation_name + ".restart" + str(i)
list nParticles = []
list nInteractions = []
f_temp = open(filename, 'r')
bool found_particles = False
bool found_interactions = False
nParticlesTotal = sum(nParticles)
nInteractionsTotal = sum(nInteractions)
string filename_new = simulation_name + ".restart"
f_new = open(filename_new,'a')
bool finished = False
bool found_end = False
Variable Documentation
f
MergeRestartFiles.f = open(root_filename, 'r+')
f_new
MergeRestartFiles.f_new = open(filename_new,'a')
f_temp
MergeRestartFiles.f_temp = open(filename, 'r')
filename
string MergeRestartFiles.filename = simulation_name + ".restart" + str(i)
Referenced by MeltContactProblem< ELEMENT >.actions_after_adapt(), ContactProblem< ELEMENT >.actions_after_adapt(), MeltContactProblem< ELEMENT >.actions_before_adapt(), ContactProblem< ELEMENT >.actions_before_adapt(), oomph::RefineableGmshTetMesh< ELEMENT >.adapt(), add_online_info_into_contributors_list(), helpers.addToFile(), VTKCollection.append(), statistics_while_running< T >.appendToFile(), oomph::Multi_domain_functions.aux_setup_multi_domain_interaction(), AxiPoroProblem< ELEMENT, TIMESTEPPER >.AxiPoroProblem(), CantileverProblem< ELEMENT >.CantileverProblem(), FourierDecomposedHelmholtzProblem< ELEMENT >.check_gamma(), check_locate_zeta(), check_marketio(), check_marketio_dense(), check_marketio_vector(), VorticityRecoveryProblem< ELEMENT >.check_smoothed_vorticity(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >.CoatedDiskProblem(), CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >.CoatedSphereProblem(), RectangularDrivenCavityProblem< ELEMENT >.compare_assembly_strategies(), contributors_map_from_churn_output(), BaseStateProblem< BASE_ELEMENT >.create_trace_file(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >.create_trace_file(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >.create_trace_files(), DarcyProblem< ELEMENT >.DarcyProblem(), oomph::DebugHelpers.debug_string(), demo_smoothing_with_linear_elasticity(), demo_smoothing_with_nonlinear_elasticity(), demo_smoothing_with_poisson(), deserialize_benchmarks(), oomph::SolidHelpers.doc_2D_principal_stress(), UnstructuredFluidProblem< ELEMENT >.doc_boundary_coordinates(), DiskShockWaveProblem< ELEMENT, TIMESTEPPER >.doc_displ_and_veloc(), oomph::Z2ErrorEstimator.doc_flux(), oomph::FSI_functions.doc_fsi(), DarcyProblem< ELEMENT >.doc_shape_functions(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >.doc_solid_boundary_coordinates(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >.doc_solid_boundary_coordinates(), RefineableAdvectionDiffusionProblem< ELEMENT >.doc_solution(), SUPGAdvectionDiffusionProblem< ELEMENT >.doc_solution(), AxisymFvKProblem< ELEMENT >.doc_solution(), UnstructuredFvKProblem< ELEMENT >.doc_solution(), RefineableAdvectionDiffusionPipeProblem< ELEMENT >.doc_solution(), ExtrudedMovingCylinderProblem< TWO_D_ELEMENT, THREE_D_ELEMENT >.doc_solution(), MeltContactProblem< ELEMENT >.doc_solution(), SolarRadiationProblem< ELEMENT >.doc_solution(), ContactProblem< ELEMENT >.doc_solution(), UnsteadyHeatMeltProblem< ELEMENT >.doc_solution(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >.doc_solution(), RefineableFishPoissonProblem< ELEMENT >.doc_solution(), GeomObjectAsGeneralisedElementProblem.doc_solution(), NavierStokesProblem< ELEMENT >.doc_solution(), UnstructuredSolidProblem< ELEMENT, MESH >.doc_solution(), PrescribedBoundaryDisplacementProblem< ELEMENT >.doc_solution(), EntryFlowProblem< ELEMENT >.doc_solution(), ConvectionProblem< NST_ELEMENT, AD_ELEMENT >.doc_solution(), RefineableConvectionProblem< NST_ELEMENT, AD_ELEMENT >.doc_solution(), DDConvectionProblem< NST_ELEMENT, AD_ELEMENT >.doc_solution(), RefineableDDConvectionProblem< NST_ELEMENT, AD_ELEMENT >.doc_solution(), ThermalProblem< ELEMENT >.doc_solution(), PMLStructuredCubicHelmholtz< ELEMENT >.doc_solution(), PMLHelmholtzMGProblem< ELEMENT >.doc_solution(), SteadyCurvedTubeProblem< ELEMENT >.doc_solution(), SteadyHelicalProblem< ELEMENT >.doc_solution(), FreeSurfaceRotationProblem< ELEMENT >.doc_solution(), TiltedCavityProblem< ELEMENT >.doc_solution(), SteadyTubeProblem< ELEMENT >.doc_solution(), SolidFreeSurfaceRotationProblem< ELEMENT >.doc_solution(), DiskShockWaveProblem< ELEMENT, TIMESTEPPER >.doc_solution(), AnnularDiskProblem< ELASTICITY_ELEMENT >.doc_solution(), RingWithTRibProblem< ELASTICITY_ELEMENT >.doc_solution(), FlowAroundCylinderProblem< ELEMENT >.doc_solution(), CompressedSquareProblem< ELEMENT >.doc_solution(), UnstructuredImmersedEllipseProblem< ELEMENT >.doc_solution(), AxisymmetricVibratingShellProblem< ELEMENT >.doc_solution(), VibratingShellProblem< ELEMENT >.doc_solution(), UnstructuredPoissonProblem< ELEMENT >.doc_solution(), RefineableUnsteadyHeatProblem< ELEMENT >.doc_solution(), TwoLayerInterfaceProblem< ELEMENT >.doc_solution(), BubbleInChannelProblem< ELEMENT >.doc_solution(), DropInChannelProblem< ELEMENT >.doc_solution(), UnstructuredFluidProblem< ELEMENT >.doc_solution(), FSIRingProblem.doc_solution(), AxiPoroProblem< ELEMENT, TIMESTEPPER >.doc_solution(), DarcyProblem< ELEMENT >.doc_solution(), ComplexHarmonicProblem< ELEMENT, EIGEN_SOLVER >.doc_solution(), HarmonicProblem< ELEMENT, EIGEN_SOLVER >.doc_solution(), OrrSommerfeldProblem< ELEMENT >.doc_solution(), OneDPoissonProblem< ELEMENT >.doc_solution(), TetmeshPoissonProblem< ELEMENT >.doc_solution(), FallingBlockProblem< ELEMENT >.doc_solution(), RisingBubbleProblem< ELEMENT >.doc_solution(), SheetGlueProblem< ELEMENT >.doc_solution(), TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >.doc_solution(), AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >.doc_solution(), CapProblem< ELEMENT >.doc_solution(), PseudoSolidCapProblem< ELEMENT >.doc_solution(), BaseStateProblem< BASE_ELEMENT >.doc_solution(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >.doc_solution(), MeltSpinningProblem< ELEMENT >.doc_solution(), InterfaceProblem< ELEMENT, TIMESTEPPER >.doc_solution(), RotatingCylinderProblem< ELEMENT, TIMESTEPPER >.doc_solution(), ElasticRingProblem< ELEMENT >.doc_solution(), FourierDecomposedHelmholtzProblem< ELEMENT >.doc_solution(), UnsteadyHeatProblem< ELEMENT >.doc_solution(), StefanBoltzmannProblem< ELEMENT >.doc_solution(), HelmholtzPointSourceProblem< ELEMENT >.doc_solution(), ScatteringProblem< ELEMENT >.doc_solution(), AirwayReopeningProblem< ELEMENT >.doc_solution(), CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >.doc_solution(), DeformableFishPoissonProblem< ELEMENT >.doc_solution(), SegregatedFSICollapsibleChannelProblem< ELEMENT >.doc_solution(), OscRingNStProblem< ELEMENT >.doc_solution(), PressureWaveFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >.doc_solution(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >.doc_solution(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >.doc_solution(), PeriodicLoadProblem< ELEMENT >.doc_solution(), RefineablePeriodicLoadProblem< ELEMENT >.doc_solution(), RectangularDrivenCavityProblem< ELEMENT >.doc_solution(), PoissonProblem< ELEMENT >.doc_solution(), MultiPoissonProblem< ELEMENT >.doc_solution(), LinearWaveProblem< ELEMENT, TIMESTEPPER >.doc_solution(), FlowPastBoxProblem< ELEMENT >.doc_solution(), MovingBlockProblem< ELEMENT >.doc_solution(), RefineableDrivenCavityProblem< ELEMENT >.doc_solution(), QuarterCircleDrivenCavityProblem< ELEMENT >.doc_solution(), PRefineableDrivenCavityProblem< ELEMENT >.doc_solution(), RefineableTwoDPoissonProblem< ELEMENT >.doc_solution(), RefineableTwoMeshFluxPoissonProblem< ELEMENT >.doc_solution(), CantileverProblem< ELEMENT >.doc_solution(), RefineableSphereConvectionProblem< ELEMENT >.doc_solution(), AxisymFreeSurfaceNozzleAdvDiffRobinProblem< ELEMENT >.doc_solution(), FluxPoissonMGProblem< ELEMENT, MESH >.doc_solution(), UnitCubePoissonMGProblem< ELEMENT, MESH >.doc_solution(), BrethertonProblem< ELEMENT >.doc_solution(), ChannelWithLeafletProblem< ELEMENT >.doc_solution(), QuarterCircleDrivenCavityProblem2< ELEMENT >.doc_solution(), OscEllipseProblem< ELEMENT, TIMESTEPPER >.doc_solution(), RayleighProblem< ELEMENT, TIMESTEPPER >.doc_solution(), RayleighTractionProblem< ELEMENT, TIMESTEPPER >.doc_solution(), FpTestProblem.doc_solution(), ChannelSpineFlowProblem< ELEMENT >.doc_solution(), SpikedChannelSpineFlowProblem< ELEMENT >.doc_solution(), ThreeDimBethertonProblem< ELEMENT >.doc_solution(), ElasticInterfaceProblem< ELEMENT, TIMESTEPPER >.doc_solution(), TurekNonFSIProblem< ELEMENT >.doc_solution(), RefineablePoissonProblem< ELEMENT >.doc_solution(), PMLFourierDecomposedHelmholtzProblem< ELEMENT >.doc_solution(), PMLProblem< ELEMENT >.doc_solution(), ElasticAnnulusProblem< ELASTICITY_ELEMENT >.doc_solution(), EighthSpherePoissonProblem< ELEMENT >.doc_solution(), FishPoissonProblem< ELEMENT >.doc_solution(), SimpleRefineableFishPoissonProblem< ELEMENT >.doc_solution(), RefineableOneDPoissonProblem< ELEMENT >.doc_solution(), PRefineableOneDPoissonProblem< ELEMENT >.doc_solution(), FluxPoissonProblem< ELEMENT >.doc_solution(), TwoMeshFluxPoissonProblem< ELEMENT >.doc_solution(), PolarNSProblem< ELEMENT >.doc_solution(), oomph::StreamfunctionProblem.doc_solution(), StaticDiskCompressionProblem< ELEMENT >.doc_solution(), DiskOscillationProblem< ELEMENT >.doc_solution(), SimpleShearProblem< ELEMENT >.doc_solution(), ElasticFishProblem< ELEMENT >.doc_solution(), BlockCompressionProblem< ELEMENT >.doc_solution(), EultingSphereProblem< ELEMENT >.doc_solution(), RefineableElutingSphereProblem< ELEMENT >.doc_solution(), TwoMeshFluxSteadyAxisymAdvectionDiffusionProblem< ELEMENT >.doc_solution(), FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >.doc_solution(), ThreeDPoissonProblem< ELEMENT >.doc_solution(), TestPoissonProblem< ELEMENT >.doc_solution(), TestRefineablePoissonProblem< ELEMENT >.doc_solution(), oomph::NonLinearElasticitySmoothMesh< ELEMENT >.doc_solution(), oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >.doc_solution(), VorticityRecoveryProblem< ELEMENT >.doc_solution(), oomph::BiharmonicProblem< DIM >.doc_solution(), oomph::BiharmonicFluidProblem< DIM >.doc_solution(), FSIChannelWithLeafletProblem< ELEMENT >.doc_solution(), FSICollapsibleChannelProblem< ELEMENT >.doc_solution(), FSIDrivenCavityProblem< ELEMENT >.doc_solution(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >.doc_solution(), CollapsibleChannelProblem< ELEMENT >.doc_solution(), ShellProblem< ELEMENT >.doc_solution(), YoungLaplaceProblem< ELEMENT >.doc_solution(), RefineableYoungLaplaceProblem< ELEMENT >.doc_solution(), DrivenCavityProblem< ELEMENT, MESH >.doc_solution(), RefineableSphericalCouetteProblem< ELEMENT >.doc_solution(), RefineableSphericalSpinUpProblem< ELEMENT >.doc_solution(), SphericalSpinUpProblem< ELEMENT >.doc_solution(), oomph::WomersleyProblem< ELEMENT, DIM >.doc_solution(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >.doc_solution(), OscRingNStProblem< ELEMENT >.doc_solution_historic(), FSICollapsibleChannelProblem< ELEMENT >.doc_solution_steady(), SegregatedFSICollapsibleChannelProblem< ELEMENT >.doc_solution_steady(), FSICollapsibleChannelProblem< ELEMENT >.doc_solution_unsteady(), SegregatedFSICollapsibleChannelProblem< ELEMENT >.doc_solution_unsteady(), doc_sparse_node_update(), ElasticCollapsibleChannelMesh< ELEMENT >.ElasticCollapsibleChannelMesh(), ElasticRefineableCollapsibleChannelMesh< ELEMENT >.ElasticRefineableCollapsibleChannelMesh(), EntryFlowProblem< ELEMENT >.EntryFlowProblem(), statistics_while_running< T >.finishStatistics(), FluidTetMesh< ELEMENT >.FluidTetMesh(), FreeSurfaceRotationProblem< ELEMENT >.FreeSurfaceRotationProblem(), GeomObjectAsGeneralisedElementProblem.GeomObjectAsGeneralisedElementProblem(), Eigen.getMarketHeader(), Eigen::MatrixMarketIterator< Scalar >.Getnextvalidmatrix(), GetTestTempFilename(), preprocessed_inputfile_t.import_input_file_range_one_product_size(), oomph::DenseMatrix< T >.indexed_output(), inputfile_t.inputfile_t(), oomph::MGSolver< DIM >.interpolation_self_test(), Eigen.loadMarket(), Eigen.loadMarketDense(), Eigen.loadMarketVector(), main(), main_gemm(), main_gemv(), helpers.more(), MyFluidTetMesh< ELEMENT >.MyFluidTetMesh(), MySolidTetgenMesh< ELEMENT >.MySolidTetgenMesh(), NavierStokesProblem< ELEMENT >.NavierStokesProblem(), helpers.openFile(), oomph::TetMeshFacetedSurface.output(), oomph::Domain.output(), oomph::DoubleMultiVector.output(), oomph::DenseMatrix< T >.output(), oomph::DoubleVector.output(), NonRefineableBinArray.output_bins(), oomph::BlockPreconditioner< MATRIX >.output_blocks_to_files(), output_both_versions(), oomph::DoubleVector.output_local_values(), oomph::DoubleVector.output_local_values_with_offset(), oomph::Domain.output_macro_element_boundaries(), parallel_test(), ElasticBeamProblem.parameter_study(), EulerProblem.parameter_study(), CapProblem< ELEMENT >.parameter_study(), PseudoSolidCapProblem< ELEMENT >.parameter_study(), StaticDiskCompressionProblem< ELEMENT >.parameter_study(), BrethertonProblem< ELEMENT >.parameter_study(), AirwayReopeningProblem< ELEMENT >.parameter_study(), ElasticRingProblem< ELEMENT >.parameter_study(), SphericalSteadyRotationProblem< ELEMENT >.parameter_study(), TwoDDGProblem< ELEMENT >.parameter_study(), AdvectionProblem.parameter_study(), oomph::MGSolver< DIM >.plot(), GlobalFct.plot_it(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >.PseudoElasticCollapsibleChannelProblem(), QFaceTestProblem< ELEMENT >.QFaceTestProblem(), csvReader.read(), helpers.readArrayFromFile(), DPMBase.readNextArgument(), WallHandler.readTriangleWall(), TriangulatedWall.readVTK(), RefineableFishPoissonProblem< ELEMENT >.RefineableFishPoissonProblem(), RefineableUnsteadyHeatProblem< ELEMENT >.RefineableUnsteadyHeatProblem(), DPMBase.removeOldFiles(), RefineableUnsteadyHeatProblem< ELEMENT >.restart(), oomph::MGSolver< DIM >.restriction_self_test(), DeformableFishPoissonProblem< ELEMENT >.run(), DiskShockWaveProblem< ELEMENT, TIMESTEPPER >.run(), DiskOscillationProblem< ELEMENT >.run(), statistics_while_running< T >.run(), DrivenCavityProblem< ELEMENT, MESH >.run(), run_impedance_tube(), ShellProblem< ELEMENT >.run_it(), CompressedSquareProblem< ELEMENT >.run_it(), run_it(), CantileverProblem< ELEMENT >.run_it(), run_navier_stokes_outflow(), run_prescribed_flux(), run_prescribed_pressure_gradient(), saveAsBitmap(), Eigen.saveMarket(), Eigen.saveMarketDense(), Eigen.saveMarketVector(), SolidProblem< ELEMENT_TYPE >.saveSolidMesh(), serialize_benchmarks(), oomph::DocInfo.set_directory(), RefineableOneDAdvectionDiffusionReactionProblem< ELEMENT >.set_initial_condition(), RefineableActivatorInhibitorProblem< ELEMENT >.set_initial_condition(), StefanBoltzmannProblem< ELEMENT >.setup_sb_radiation(), oomph::StefanBoltzmannHelper.setup_stefan_boltzmann_visibility(), ClosedCSCStats.setupInitialConditions(), CSCStats.setupInitialConditions(), SheetGlueProblem< ELEMENT >.SheetGlueProblem(), oomph::TetMeshBase.snap_nodes_onto_geometric_objects(), oomph::TetMeshBase.snap_to_quadratic_surface(), ABCProblem< ELEMENT, TIMESTEPPERT >.solve(), RefineableRotatingCylinderProblem< ELEMENT >.solve(), ComplexHarmonicProblem< ELEMENT, EIGEN_SOLVER >.solve(), HarmonicProblem< ELEMENT, EIGEN_SOLVER >.solve(), ShellProblem< ELEMENT >.solve(), InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >.solve_steady(), RotatingProblem< ELEMENT >.solve_system(), CapProblem< ELEMENT >.solve_system(), TorusProblem< ELEMENT >.solve_system(), UnstructuredTorusProblem< ELEMENT >.solve_system(), solve_with_fully_automatic_adaptation(), solve_with_incremental_adaptation(), solve_with_selected_refinement_pattern(), oomph::Matrix< T, MATRIX_TYPE >.sparse_indexed_output(), oomph::CRDoubleMatrix.sparse_indexed_output_with_offset(), FSICollapsibleChannelProblem< ELEMENT >.steady_run(), SegregatedFSICollapsibleChannelProblem< ELEMENT >.steady_run(), TFaceTestProblem< ELEMENT >.TFaceTestProblem(), ThreeDimBethertonProblem< ELEMENT >.ThreeDimBethertonProblem(), InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >.timestep(), ActivatorInhibitorProblem< ELEMENT >.timestep(), SphericalSpinUpProblem< ELEMENT >.timestep(), transformMercuryToVTK(), TriangleFaceTestProblem< ELEMENT >.TriangleFaceTestProblem(), TriangulatedWall.TriangulatedWall(), ElasticRingProblem< ELEMENT >.unsteady_run(), LinearWaveProblem< ELEMENT, TIMESTEPPER >.unsteady_run(), FSICollapsibleChannelProblem< ELEMENT >.unsteady_run(), SegregatedFSICollapsibleChannelProblem< ELEMENT >.unsteady_run(), InterfaceProblem< ELEMENT, TIMESTEPPER >.unsteady_run(), ElasticInterfaceProblem< ELEMENT, TIMESTEPPER >.unsteady_run(), OscRingNStProblem< ELEMENT >.unsteady_run(), RayleighProblem< ELEMENT, TIMESTEPPER >.unsteady_run(), RayleighTractionProblem< ELEMENT, TIMESTEPPER >.unsteady_run(), CollapsibleChannelProblem< ELEMENT >.unsteady_run(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >.UnstructuredFSIProblem(), UnstructuredFvKProblem< ELEMENT >.UnstructuredFvKProblem(), UnstructuredPoissonProblem< ELEMENT >.UnstructuredPoissonProblem(), UnstructuredSolidProblem< ELEMENT, MESH >.UnstructuredSolidProblem(), oomph::GmshTetScaffoldMesh.write_geo_file(), RefineableUnsteadyHeatProblem< ELEMENT >.write_trace_file_header(), helpers.writeCommandLineToFile(), helpers.writeToFile(), statistics_while_running< T >.writeToFile(), and Screw.writeVTK().
filename_new
string MergeRestartFiles.filename_new = simulation_name + ".restart"
finished
bool MergeRestartFiles.finished = False
Referenced by Eigen::JacobiSVD< MatrixType_, Options_ >.compute_impl(), Eigen::internal::companion< Scalar_, Deg_ >.denseMatrix(), anonymous_namespace{skew_symmetric_matrix3.cpp}.exponentialRotation(), Eigen::internal::unitOrthogonal_selector< Derived, Size >.run(), and test_blocks().
found
bool MergeRestartFiles.found = False
Referenced by ContactProblem< ELEMENT >.complete_problem_setup(), checkIdx.doCheck_(), evalSolverSugarFunction(), oomph::CRDoubleMatrixHelpers.gershgorin_eigenvalue_estimate(), get_options(), Eigen::MatrixMarketIterator< Scalar >.Getnextvalidmatrix(), ChuteWithPeriodicInflow.loadPeriodicBox(), ChuteWithContraction.loadPeriodicBox(), oomph::TetMeshBase.nregion_element(), PolarNSProblem< ELEMENT >.output_streamfunction(), Mercury3DRestart.readNextArgument(), oomph::TetMeshBase.region_element_pt(), statistics_while_running< T >.run(), checkIdx.run(), oomph::PseudoElasticPreconditioner.setup(), oomph::PseudoElasticPreconditionerSubsidiaryPreconditionerOld.setup(), oomph::UnstructuredTwoDMeshGeometryBase.setup_boundary_coordinates(), oomph::HermiteQuadMesh< ELEMENT >.setup_boundary_element_info(), oomph::TetMeshBase.split_elements_in_corners(), statistics_while_running< T >.statistics_while_running(), test_symgroups_dynamic(), test_symgroups_selection(), test_symgroups_static(), oomph::SolarRadiationBase.update_limiting_angles(), Mercury3DRestart.writeOutputFiles(), and ChutePeriodic.writeToLocalFolder().
found_end
bool MergeRestartFiles.found_end = False
found_interactions
bool MergeRestartFiles.found_interactions = False
found_particles
bool MergeRestartFiles.found_particles = False
line
MergeRestartFiles.line = f.readline()
nInteractions
list MergeRestartFiles.nInteractions = []
nInteractionsTotal
MergeRestartFiles.nInteractionsTotal = sum(nInteractions)
nParticles
list MergeRestartFiles.nParticles = []
Referenced by ScaleCoupling< M, O >.computeCouplingForce(), VolumeCoupling.computeCouplingForce(), VolumeCoupling.computeCouplingOnDPM(), VolumeCoupling.computeCouplingOnFEM(), ScaleCoupling< M, O >.computeNodalCouplingForces(), ScaleCoupling< M, O >.computeProjectionMatrix(), MercuryBase.getHGridTargetNumberOfBuckets(), VolumeCoupling.getInvCoupledMassPerTime(), VolumeCoupling.getProjectionAndProjected(), VolumeCoupling.getProjectionMatrix(), ChargedBondedParticleUnitTest.setupInitialConditions(), and Packing.setupInitialConditions().
nParticlesTotal
MergeRestartFiles.nParticlesTotal = sum(nParticles)
nProc
MergeRestartFiles.nProc = int(tokens[i+1])
root_filename
string MergeRestartFiles.root_filename = simulation_name + '.restart0'
simulation_name
MergeRestartFiles.simulation_name = sys.argv[1:][0]
tokens
MergeRestartFiles.tokens = line.split()