MercuryDPM: quaternion_demo.cpp File Reference
quaternion_demo.cpp File Reference
#include "quaternion_demo.h"
#include "icosphere.h"
#include <Eigen/Geometry>
#include <Eigen/QR>
#include <Eigen/LU>
#include <iostream>
#include <QEvent>
#include <QMouseEvent>
#include <QInputDialog>
#include <QGridLayout>
#include <QButtonGroup>
#include <QRadioButton>
#include <QDockWidget>
#include <QPushButton>
#include <QGroupBox>
#include "quaternion_demo.moc"
Classes
class FancySpheres
class EulerAngles< Scalar_ >
Functions
template<typename T >
T lerp (float t, const T &a, const T &b)
template<>
Quaternionf lerp (float t, const Quaternionf &a, const Quaternionf &b)
template<typename OrientationType >
static Frame lerpFrame (float alpha, const Frame &a, const Frame &b)
template<>
EulerAngles< float > lerp (float t, const EulerAngles< float > &a, const EulerAngles< float > &b)
int main (int argc, char *argv[])
Function Documentation
lerp() [1/3]
template<> EulerAngles<float> lerp (float t, const EulerAngles< float > & a, const EulerAngles< float > & b)
{
   EulerAngles<float> res;
   res.coeffs() = lerp(t, a.coeffs(), b.coeffs());
   return res;
 }
References a, b, lerp(), res, and plotPSD::t.
lerp() [2/3]
template<> Quaternionf lerp (float t, const Quaternionf & a, const Quaternionf & b)
{
   return a.slerp(t, b);
 }
References a, b, and plotPSD::t.
lerp() [3/3]
template<typename T > T lerp (float t, const T & a, const T & b)
{
   return a * (1 - t) + b * t;
 }
References a, b, and plotPSD::t.
Referenced by lerp(), and lerpFrame().
lerpFrame()
template<typename OrientationType > static Frame lerpFrame (float alpha, const Frame & a, const Frame & b) inline static
{
   return Frame(lerp(alpha, a.position, b.position),
                Quaternionf(lerp(alpha, OrientationType(a.orientation), OrientationType(b.orientation))));
 }
References a, alpha, b, and lerp().
main()
int main (int argc , char * argv[])
{
   std::cout << "Navigation:\n";
   std::cout << "  left button:           rotate around the target\n";
   std::cout << "  middle button:         zoom\n";
   std::cout << "  left button + ctrl     quake rotate (rotate around camera position)\n";
   std::cout << "  middle button + ctrl   walk (progress along camera's z direction)\n";
   std::cout << "  left button:           pan (translate in the XY camera's plane)\n\n";
   std::cout << "R : move the camera to initial position\n";
   std::cout << "A : start/stop animation\n";
   std::cout << "C : clear the animation\n";
   std::cout << "G : add a key frame\n";
   QApplication app(argc, argv);
   QuaternionDemo demo;
   demo.resize(600, 500);
   demo.show();
   return app.exec();
 }