MercuryDPM: oomph::ElementElementConstraintElement Class Reference
oomph::ElementElementConstraintElement Class Reference
#include <element_element_constraint_elements.h>
Public Member Functions
ElementElementConstraintElement (Vector< FiniteElement * > elem_pt)
Public Member Functions inherited from oomph::ConstraintElement
ConstraintElement (Vector< Data * > &data_pt)
ConstraintElement (Vector< Data * > data_pt)
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
virtual void construct_lagrange_multipliers ()
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual unsigned self_test ()
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Protected Member Functions
FiniteElement * elem_pt (const unsigned &i)
Data * node_pt (const unsigned &e, const unsigned &i)
Data * extern_data_pt (const unsigned &e, const unsigned &i)
Data * intern_data_pt (const unsigned &e, const unsigned &i)
const int node_eqn (const unsigned &e, const unsigned &i, const unsigned &j)
const int extern_data_eqn (const unsigned &e, const unsigned &i, const unsigned &j)
const int intern_data_eqn (const unsigned &e, const unsigned &i, const unsigned &j)
Protected Member Functions inherited from oomph::ConstraintElement
virtual void evaluate_constraint_functions (Vector< double > &error)
Vector< unsigned > get_constrained_data_local_index ()
unsigned get_lagrange_multiplier_index ()
Data * lagrange_multiplier ()
const int lagrange_eqn (const unsigned &i)
Data * ext_data_pt (const unsigned &i)
const int ext_eqn (const unsigned &i, const unsigned &j)
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Private Member Functions
void build (Vector< FiniteElement * > &elem_pt)
Private Attributes
unsigned N_Element
Vector< FiniteElement * > Element_pt
Vector< Vector< unsigned > > Node_Local_Index
Vector< unsigned > N_Node
Vector< Vector< unsigned > > Internal_Data_Local_Index
Vector< unsigned > N_Internal_Data
Vector< Vector< unsigned > > External_Data_Local_Index
Vector< unsigned > N_External_Data
Additional Inherited Members
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Attributes inherited from oomph::ConstraintElement
Vector< unsigned > Constrained_Data_Local_Index
unsigned Num_Constrained_Data
unsigned Lagrange_Multiplier_Index
unsigned Num_Constraints
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Constructor & Destructor Documentation
ElementElementConstraintElement()
oomph::ElementElementConstraintElement::ElementElementConstraintElement (Vector< FiniteElement * > elem_pt) inline
                                                                   :
     ConstraintElement(ElementElementConstraintElementHelper::element_pt_to_data_pt(elem_pt)),
     Element_pt(elem_pt),
     N_Element(elem_pt.size())
   {
    //
    build(elem_pt);
   }
References build(), and elem_pt().
Member Function Documentation
build()
void oomph::ElementElementConstraintElement::build (Vector< FiniteElement * > & elem_pt) private
  {
   // Calculate where the various bits of data are stored in the external data
   // We know how ElementElementConstraintElementHelper orders the data so we just need to match it
   Node_Local_Index.resize(N_Element);
   Internal_Data_Local_Index.resize(N_Element);
   External_Data_Local_Index.resize(N_Element);
   N_Node.resize(N_Element);
   N_Internal_Data.resize(N_Element);
   N_External_Data.resize(N_Element);
   // Get the first index by taking the difference between the total number of external data and the number of constrained data
   unsigned data_index = nexternal_data() - Num_Constrained_Data;
   for(unsigned e=0; e<N_Element; e++)
   {
    const unsigned n_node = Element_pt[e]->nnode();
    Node_Local_Index[e].resize(n_node);
    N_Node[e] = n_node;
    for(unsigned i=0; i<n_node; i++)
    {
     Node_Local_Index[e][i] = data_index++;
    }
    const unsigned n_internal = Element_pt[e]->ninternal_data();
    Internal_Data_Local_Index[e].resize(Element_pt[e]->ninternal_data());
    N_Internal_Data[e] = n_internal;
    for(unsigned i=0; i<n_internal; i++)
    {
     Internal_Data_Local_Index[e][i] = data_index++;
    }
    const unsigned n_external = Element_pt[e]->nexternal_data();
    External_Data_Local_Index[e].resize(Element_pt[e]->nexternal_data());
    N_External_Data[e] = n_external;
    for(unsigned i=0; i<n_external; i++)
    {
     External_Data_Local_Index[e][i] = data_index++;
    }
   }
  }
References e(), Element_pt, External_Data_Local_Index, i, Internal_Data_Local_Index, N_Element, N_External_Data, N_Internal_Data, N_Node, oomph::GeneralisedElement::nexternal_data(), oomph::GeneralisedElement::ninternal_data(), Node_Local_Index, and oomph::ConstraintElement::Num_Constrained_Data.
Referenced by ElementElementConstraintElement().
elem_pt()
FiniteElement* oomph::ElementElementConstraintElement::elem_pt (const unsigned & i) inline protected
   {
   #ifdef RANGE_CHECKING
    if(i>=N_Element)
    {
     throw OomphLibError(std::to_string(i) + " is greater than the number of elements " + std::to_string(N_Element),
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
    }
   #endif
    return Element_pt[i];
   }
References Element_pt, i, N_Element, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::StringConversion::to_string().
Referenced by ElementElementConstraintElement(), and oomph::ElementElementMortaringElement::evaluate_constraint_functions().
extern_data_eqn()
const int oomph::ElementElementConstraintElement::extern_data_eqn (const unsigned & e, const unsigned & i, const unsigned & j) inline protected
   {
    return external_local_eqn(Internal_Data_Local_Index[e][i], j);
   }
References e(), oomph::GeneralisedElement::external_local_eqn(), i, Internal_Data_Local_Index, and j.
extern_data_pt()
Data* oomph::ElementElementConstraintElement::extern_data_pt (const unsigned & e, const unsigned & i) inline protected
   {
    return external_data_pt(Internal_Data_Local_Index[e][i]);
   }
References e(), oomph::GeneralisedElement::external_data_pt(), i, and Internal_Data_Local_Index.
intern_data_eqn()
const int oomph::ElementElementConstraintElement::intern_data_eqn (const unsigned & e, const unsigned & i, const unsigned & j) inline protected
   {
    return external_local_eqn(External_Data_Local_Index[e][i], j);
   }
References e(), External_Data_Local_Index, oomph::GeneralisedElement::external_local_eqn(), i, and j.
intern_data_pt()
Data* oomph::ElementElementConstraintElement::intern_data_pt (const unsigned & e, const unsigned & i) inline protected
   {
    return external_data_pt(External_Data_Local_Index[e][i]);
   }
References e(), External_Data_Local_Index, oomph::GeneralisedElement::external_data_pt(), and i.
node_eqn()
const int oomph::ElementElementConstraintElement::node_eqn (const unsigned & e, const unsigned & i, const unsigned & j) inline protected
   {
    return external_local_eqn(Node_Local_Index[e][i], j);
   }
References e(), oomph::GeneralisedElement::external_local_eqn(), i, j, and Node_Local_Index.
node_pt()
Data* oomph::ElementElementConstraintElement::node_pt (const unsigned & e, const unsigned & i) inline protected
   {
    return external_data_pt(Node_Local_Index[e][i]);
   }
References e(), oomph::GeneralisedElement::external_data_pt(), i, and Node_Local_Index.
Member Data Documentation
Element_pt
Vector<FiniteElement*> oomph::ElementElementConstraintElement::Element_pt private
Referenced by build(), and elem_pt().
External_Data_Local_Index
Vector<Vector<unsigned> > oomph::ElementElementConstraintElement::External_Data_Local_Index private
Referenced by build(), intern_data_eqn(), and intern_data_pt().
Internal_Data_Local_Index
Vector<Vector<unsigned> > oomph::ElementElementConstraintElement::Internal_Data_Local_Index private
Referenced by build(), extern_data_eqn(), and extern_data_pt().
N_Element
unsigned oomph::ElementElementConstraintElement::N_Element private
Referenced by build(), and elem_pt().
N_External_Data
Vector<unsigned> oomph::ElementElementConstraintElement::N_External_Data private
Referenced by build().
N_Internal_Data
Vector<unsigned> oomph::ElementElementConstraintElement::N_Internal_Data private
Referenced by build().
N_Node
Vector<unsigned> oomph::ElementElementConstraintElement::N_Node private
Referenced by build().
Node_Local_Index
Vector<Vector<unsigned> > oomph::ElementElementConstraintElement::Node_Local_Index private
Referenced by build(), node_eqn(), and node_pt().
The documentation for this class was generated from the following files:
element_element_constraint_elements.h
element_element_constraint_elements.cc