MercuryDPM: axisym_displ_based_fvk.cc File Reference
axisym_displ_based_foeppl_von_karman/axisym_displ_based_fvk.cc File Reference
#include <fenv.h>
#include "generic.h"
#include "axisym_displ_based_foeppl_von_karman.h"
#include "meshes/one_d_mesh.h"
Classes
class AxisymFvKProblem< ELEMENT >
Problem class.
Namespaces
AxisymFvKParameters
Namespace for pressure solution.
Functions
void AxisymFvKParameters::pressure_function (const double &r, double &pressure)
Function that computes the pressure at radius r.
void AxisymFvKParameters::get_exact_u (const Vector< double > &r, Vector< double > &u)
Function to get the exact solution for the pure bending model.
int main (int argc, char **argv)
Driver.
Function Documentation
main()
int main (int argc , char ** argv)
Driver.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Choose between pure bending or fvk model
  CommandLineArgs::specify_command_line_flag("--use_linear_eqns");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Number of elements in the mesh
  unsigned n_element=100;
  // Number of steps
  unsigned n_step=10;
  // Pressure increment
  double dp=0.01;
  // Set up the problem:
  AxisymFvKProblem<AxisymFoepplvonKarmanElement<3> > problem(n_element);
  // Set initial value for pressure
  AxisymFvKParameters::Pressure=0.0;
  for (unsigned i=0;i<n_step;i++)
   {
    // Solve the problem
    problem.newton_solve();
    //Output solution
    problem.doc_solution();
    // Increment pressure
    AxisymFvKParameters::Pressure+=dp;
   }
 } // end of main
References oomph::CommandLineArgs::doc_specified_flags(), i, oomph::CommandLineArgs::parse_and_assign(), AxisymFvKParameters::Pressure, problem, Flag_definition::setup(), and oomph::CommandLineArgs::specify_command_line_flag().