MercuryDPM: adaptive_drop_in_channel.cc File Reference
adaptive_drop_in_channel.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "solid.h"
#include "constitutive.h"
#include "fluid_interface.h"
#include "meshes/triangle_mesh.h"
Classes
class oomph::MyCrouzeixRaviartElement
Overload CrouzeixRaviart element to modify output.
class oomph::FaceGeometry< MyCrouzeixRaviartElement >
class oomph::FaceGeometry< FaceGeometry< MyCrouzeixRaviartElement > >
class DropInChannelProblem< ELEMENT >
Problem class to simulate viscous drop propagating along 2D channel.
Namespaces
oomph
DRAIG: Change all instances of (SPATIAL_DIM) to (DIM-1).
Problem_Parameter
Namespace for Problem Parameter.
Functions
int main (int argc, char **argv)
Driver code for moving block problem.
Variables
double Problem_Parameter::Viscosity_ratio = 10.0
Viscosity ratio of the droplet to the surrounding fluid.
Function Documentation
main()
int main (int argc , char ** argv)
Driver code for moving block problem.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Validation?
  CommandLineArgs::specify_command_line_flag("--validation");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Create generalised Hookean constitutive equations
  Problem_Parameter::Constitutive_law_pt =
   new GeneralisedHookean(&Problem_Parameter::Nu);
  // Open trace file
  Problem_Parameter::Trace_file.open("RESLT/trace.dat");
  // Open norm file
  Problem_Parameter::Norm_file.open("RESLT/norm.dat");
  // Create problem in initial configuration
  DropInChannelProblem<Hijacked<ProjectableCrouzeixRaviartElement<
  MyCrouzeixRaviartElement> > > problem;
  // Before starting the time-integration we want to "inflate" it to form
  // a proper circular drop. We do this by setting the inflow to zero
  // and doing a steady solve (with one adaptation)
  Problem_Parameter::Inflow_veloc_magnitude=0.0;
  problem.steady_newton_solve(1);
  //Set the Capillary number to 10 and resolve
  Problem_Parameter::Ca = 10.0;
  problem.steady_newton_solve();
  // If all went well, this should show us a nice circular drop
  // in a stationary fluid
  problem.doc_solution();
  // Switch off volume constraint
  problem.remove_volume_constraint();
  // Initialise timestepper
  double dt=0.025;
  problem.initialise_dt(dt);
  // Perform impulsive start from current state
  problem.assign_initial_values_impulsive();
  // Output initial conditions
  problem.doc_solution();
  // Now switch on the inflow and re-assign the boundary conditions
  // (Call to complete_problem_setup() is a bit expensive given that we
  // we only want to set the inflow velocity but who cares -- it's just
  // a one off.
  Problem_Parameter::Inflow_veloc_magnitude=1.0;
  problem.complete_problem_setup();
  // Solve problem on fixed mesh
  unsigned nstep=6;
  if (CommandLineArgs::command_line_flag_has_been_set("--validation"))
   {
    nstep=2;
    oomph_info << "Remeshing after every second step during validation\n";
   }
  for (unsigned i=0;i<nstep;i++)
   {
    // Solve the problem
    problem.unsteady_newton_solve(dt);
    problem.doc_solution();
   } // done solution on fixed mesh
  // Now do a proper loop, doing nstep timesteps before adapting/remeshing
  // and repeating the lot ncycle times
  unsigned ncycle=1000;
  if (CommandLineArgs::command_line_flag_has_been_set("--validation"))
   {
    ncycle=1;
    oomph_info << "Only doing one cycle during validation\n";
   }
  // Do the cycles
  for(unsigned j=0;j<ncycle;j++)
   {
    // Allow up to one level of refinement for next solve
    unsigned max_adapt=1;
    //Solve problem a few times
    for (unsigned i=0;i<nstep;i++)
     {
      // Solve the problem
      problem.unsteady_newton_solve(dt,max_adapt,false);
      // Build the label for doc and output solution
      std::stringstream label;
      label << "Adaptation " <<j << " Step "<< i;
      problem.doc_solution(label.str());
      // No more refinement for the next nstep steps
      max_adapt=0;
     }
   }
 } //End of main
References Problem_Parameter::Ca, oomph::CommandLineArgs::command_line_flag_has_been_set(), Problem_Parameter::Constitutive_law_pt, oomph::CommandLineArgs::doc_specified_flags(), i, Problem_Parameter::Inflow_veloc_magnitude, j, UniformPSDSelfTest::label, Problem_Parameter::Norm_file, Problem_Parameter::Nu, oomph::oomph_info, oomph::CommandLineArgs::parse_and_assign(), problem, Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), and Problem_Parameter::Trace_file.