MercuryDPM: Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, Side > Struct Template Reference
Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, Side > Struct Template Reference
#include <HouseholderSequence.h>
Public Types
typedef Block< const VectorsType, Dynamic, 1 > EssentialVectorType
typedef HouseholderSequence< VectorsType, CoeffsType, OnTheLeft > HouseholderSequenceType
Static Public Member Functions
static EIGEN_DEVICE_FUNC const EssentialVectorType essentialVector (const HouseholderSequenceType &h, Index k)
Member Typedef Documentation
EssentialVectorType
template<typename VectorsType , typename CoeffsType , int Side> typedef Block<const VectorsType, Dynamic, 1> Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, Side >::EssentialVectorType
HouseholderSequenceType
template<typename VectorsType , typename CoeffsType , int Side> typedef HouseholderSequence<VectorsType, CoeffsType, OnTheLeft> Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, Side >::HouseholderSequenceType
Member Function Documentation
essentialVector()
template<typename VectorsType , typename CoeffsType , int Side> static EIGEN_DEVICE_FUNC const EssentialVectorType Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, Side >::essentialVector (const HouseholderSequenceType & h, Index k) inline static
{
     Index start = k + 1 + h.m_shift;
     return Block<const VectorsType, Dynamic, 1>(h.m_vectors, start, k, h.rows() - start, 1);
   }
References k, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_shift, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_vectors, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::rows(), and oomph::CumulativeTimings::start().
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::essentialVector().
The documentation for this struct was generated from the following file:
HouseholderSequence.h