MercuryDPM: Eigen::internal::scalar_isnan_op< Scalar, true > Struct Template Reference
Eigen::internal::scalar_isnan_op< Scalar, true > Struct Template Reference
#include <UnaryFunctors.h>
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar operator() (const Scalar &a) const
template<typename Packet >
EIGEN_DEVICE_FUNC Packet packetOp (const Packet &a) const
Member Function Documentation
operator()()
template<typename Scalar > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar Eigen::internal::scalar_isnan_op< Scalar, true >::operator() (const Scalar & a) const inline
{
 #if defined(SYCL_DEVICE_ONLY)
     return (numext::isnan(a) ? ptrue(a) : pzero(a));
 #else
     return (numext::isnan EIGEN_NOT_A_MACRO(a) ? ptrue(a) : pzero(a));
 #endif
   }
References a, EIGEN_NOT_A_MACRO, Eigen::numext::isnan(), Eigen::internal::ptrue(), and Eigen::internal::pzero().
packetOp()
template<typename Scalar > template<typename Packet > EIGEN_DEVICE_FUNC Packet Eigen::internal::scalar_isnan_op< Scalar, true >::packetOp (const Packet & a) const inline
{
     return pisnan(a);
   }
References a, and Eigen::internal::pisnan().
The documentation for this struct was generated from the following file:
functors/UnaryFunctors.h