MercuryDPM: Eigen::internal::Assignment< DstXprType, SolveWithGuess< DecType, RhsType, GuessType >, internal::assign_op< Scalar, Scalar >, Dense2Dense > Struct Template Reference
Eigen::internal::Assignment< DstXprType, SolveWithGuess< DecType, RhsType, GuessType >, internal::assign_op< Scalar, Scalar >, Dense2Dense > Struct Template Reference
#include <SolveWithGuess.h>
Public Types
typedef SolveWithGuess< DecType, RhsType, GuessType > SrcXprType
Static Public Member Functions
static void run (DstXprType &dst, const SrcXprType &src, const internal::assign_op< Scalar, Scalar > &)
Member Typedef Documentation
SrcXprType
template<typename DstXprType , typename DecType , typename RhsType , typename GuessType , typename Scalar > typedef SolveWithGuess<DecType, RhsType, GuessType> Eigen::internal::Assignment< DstXprType, SolveWithGuess< DecType, RhsType, GuessType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >::SrcXprType
Member Function Documentation
run()
template<typename DstXprType , typename DecType , typename RhsType , typename GuessType , typename Scalar > static void Eigen::internal::Assignment< DstXprType, SolveWithGuess< DecType, RhsType, GuessType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >::run (DstXprType & dst, const SrcXprType & src, const internal::assign_op< Scalar, Scalar > &) inline static
{
     Index dstRows = src.rows();
     Index dstCols = src.cols();
     if ((dst.rows() != dstRows) || (dst.cols() != dstCols)) dst.resize(dstRows, dstCols);
     dst = src.guess();
     src.dec()._solve_with_guess_impl(src.rhs(), dst /*, src.guess()*/);
   }
References Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::cols(), Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::dec(), Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::guess(), Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::rhs(), and Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::rows().
The documentation for this struct was generated from the following file:
SolveWithGuess.h