MercuryDPM: oomph::RefineableTetMeshBase Class Reference
oomph::RefineableTetMeshBase Class Reference
Base class for refineable tet meshes.
#include <refineable_mesh.h>
Public Member Functions
double & max_element_size ()
Max element size allowed during adaptation.
double & min_element_size ()
Min element size allowed during adaptation.
double & max_permitted_edge_ratio ()
Min edge ratio before remesh gets triggered.
void doc_adaptivity_targets (std::ostream &outfile)
Doc the targets for mesh adaptation.
double compute_volume_target (const Vector< double > &elem_error, Vector< double > &target_volume)
Public Member Functions inherited from oomph::RefineableMeshBase
bool adapt_flag ()
RefineableMeshBase ()
RefineableMeshBase (const RefineableMeshBase &dummy)=delete
Broken copy constructor.
void operator= (const RefineableMeshBase &)=delete
Broken assignment operator.
virtual ~RefineableMeshBase ()
Empty Destructor:
unsigned nrefined ()
Access fct for number of elements that were refined.
unsigned nunrefined ()
Access fct for number of elements that were unrefined.
unsigned & nrefinement_overruled ()
unsigned & max_keep_unrefined ()
ErrorEstimator *& spatial_error_estimator_pt ()
Access to spatial error estimator.
ErrorEstimator * spatial_error_estimator_pt () const
Access to spatial error estimator (const version.
double & min_permitted_error ()
double & max_permitted_error ()
double & min_error ()
double & max_error ()
DocInfo *& doc_info_pt ()
Access fct for pointer to DocInfo.
void enable_adaptation ()
Enable adaptation.
void disable_adaptation ()
Disable adaptation.
void enable_p_adaptation ()
Enable adaptation.
void disable_p_adaptation ()
Disable adaptation.
void enable_additional_synchronisation_of_hanging_nodes ()
Enable additional synchronisation of hanging nodes.
void disable_additional_synchronisation_of_hanging_nodes ()
Disable additional synchronisation of hanging nodes.
bool is_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_p_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_additional_synchronisation_of_hanging_nodes_disabled () const
Return whether additional synchronisation is enabled.
DocInfo doc_info ()
Access fct for DocInfo.
virtual void adapt (const Vector< double > &elemental_error)=0
virtual void p_adapt (const Vector< double > &elemental_error)
virtual void refine_uniformly (DocInfo &doc_info)=0
Refine mesh uniformly and doc process.
virtual void refine_uniformly ()
Refine mesh uniformly.
virtual void p_refine_uniformly (DocInfo &doc_info)
p-refine mesh uniformly and doc process
virtual void p_refine_uniformly ()
p-refine mesh uniformly
virtual unsigned unrefine_uniformly ()=0
void p_unrefine_uniformly (DocInfo &doc_info)
p-unrefine mesh uniformly
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void setup_boundary_element_info ()
virtual void setup_boundary_element_info (std::ostream &outfile)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Public Attributes
double Max_element_size
Max permitted element size.
double Min_element_size
Min permitted element size.
double Max_permitted_edge_ratio
Max edge ratio before remesh gets triggered.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes inherited from oomph::RefineableMeshBase
ErrorEstimator * Spatial_error_estimator_pt
Pointer to spatial error estimator.
double Max_permitted_error
Max. error (i.e. split elements if their error is larger)
double Min_permitted_error
Min. error (i.e. (try to) merge elements if their error is smaller)
double Min_error
Min.actual error.
double Max_error
Max. actual error.
unsigned Nrefined
Stats: Number of elements that were refined.
unsigned Nunrefined
Stats: Number of elements that were unrefined.
bool Adapt_flag
Flag that requests adaptation.
bool P_adapt_flag
Flag that requests p-adaptation.
bool Additional_synchronisation_of_hanging_nodes_not_required
Flag that disables additional synchronisation of hanging nodes.
DocInfo * Doc_info_pt
Pointer to DocInfo.
unsigned Max_keep_unrefined
unsigned Nrefinement_overruled
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Detailed Description
Base class for refineable tet meshes.
///////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
Member Function Documentation
compute_volume_target()
double oomph::RefineableTetMeshBase::compute_volume_target (const Vector< double > & elem_error, Vector< double > & target_volume) inline
Compute target volume based on the elements' error and the error target; return max edge ratio
     {
       double max_edge_ratio = 0.0;
       unsigned count_unrefined = 0;
       unsigned count_refined = 0;
       this->Nrefinement_overruled = 0;
       unsigned nel = this->nelement();
       for (unsigned e = 0; e < nel; e++)
       {
         // Get element
         FiniteElement* el_pt = this->finite_element_pt(e);
         // Calculate the volume of the element
         double volume = el_pt->size();
         // Find the vertex coordinates
         // (vertices are enumerated first)
         double vertex[4][3];
         for (unsigned n = 0; n < 4; ++n)
         {
           for (unsigned i = 0; i < 3; ++i)
           {
             vertex[n][i] = el_pt->node_pt(n)->x(i);
           }
         }
         // Compute the radius of the circumsphere of the tetrahedron
         // Algorithm stolen from tetgen for consistency
         DenseDoubleMatrix A(3);
         for (unsigned i = 0; i < 3; ++i)
         {
           A(0, i) = vertex[1][i] - vertex[0][i];
           A(1, i) = vertex[2][i] - vertex[0][i];
           A(2, i) = vertex[3][i] - vertex[0][i];
         }
         Vector<double> rhs(3);
         // Compute the right hand side vector b (3x1).
         for (unsigned i = 0; i < 3; ++i)
         {
           rhs[i] = 0.0;
           for (unsigned k = 0; k < 3; ++k)
           {
             rhs[i] += A(i, k) * A(i, k);
           }
           rhs[i] *= 0.5;
         }
         // Solve the linear system, in which the rhs is over-written with
         // the solution
         A.solve(rhs);
         // Calculate the circum-radius
         double circum_radius =
           sqrt(rhs[0] * rhs[0] + rhs[1] * rhs[1] + rhs[2] * rhs[2]);
         // Now find the shortest edge length
         Vector<double> edge(3);
         double min_length = DBL_MAX;
         for (unsigned start = 0; start < 4; ++start)
         {
           for (unsigned end = start + 1; end < 4; ++end)
           {
             for (unsigned i = 0; i < 3; ++i)
             {
               edge[i] = vertex[start][i] - vertex[end][i];
             }
             double length =
               sqrt(edge[0] * edge[0] + edge[1] * edge[1] + edge[2] * edge[2]);
             if (length < min_length)
             {
               min_length = length;
             }
           }
         }
         // Now calculate the minimum edge ratio for this element
         double local_max_edge_ratio = circum_radius / min_length;
         if (local_max_edge_ratio > max_edge_ratio)
         {
           max_edge_ratio = local_max_edge_ratio;
         }
         // Mimick refinement in tree-based procedure: Target volumes
         // for elements that exceed permitted error is 1/4 of their
         // current volume, corresponding to a uniform sub-division.
         if (elem_error[e] > this->max_permitted_error())
         {
           target_volume[e] = std::max(volume / 4.0, Min_element_size);
           if (target_volume[e] != Min_element_size)
           {
             count_refined++;
           }
           else
           {
             this->Nrefinement_overruled++;
           }
         }
         else if (elem_error[e] < this->min_permitted_error())
         {
           target_volume[e] = std::min(4.0 * volume, Max_element_size);
           if (target_volume[e] != Max_element_size)
           {
             count_unrefined++;
           }
         }
         else
         {
           // Leave it alone
           target_volume[e] = std::max(volume, Min_element_size);
         }
       } // End of loop over elements
       // Tell everybody
       this->Nrefined = count_refined;
       this->Nunrefined = count_unrefined;
       return max_edge_ratio;
     }
References e(), Eigen::placeholders::end, oomph::Mesh::finite_element_pt(), i, k, max, Max_element_size, oomph::RefineableMeshBase::max_permitted_error(), min, Min_element_size, oomph::RefineableMeshBase::min_permitted_error(), n, oomph::Mesh::nelement(), oomph::FiniteElement::node_pt(), oomph::RefineableMeshBase::Nrefined, oomph::RefineableMeshBase::Nrefinement_overruled, oomph::RefineableMeshBase::Nunrefined, oomph::FiniteElement::size(), sqrt(), oomph::CumulativeTimings::start(), and oomph::Node::x().
doc_adaptivity_targets()
void oomph::RefineableTetMeshBase::doc_adaptivity_targets (std::ostream & outfile) inline virtual
Doc the targets for mesh adaptation.
Reimplemented from oomph::RefineableMeshBase.
     {
       outfile << std::endl;
       outfile << "Targets for mesh adaptation: " << std::endl;
       outfile << "---------------------------- " << std::endl;
       outfile << "Target for max. error: " << Max_permitted_error << std::endl;
       outfile << "Target for min. error: " << Min_permitted_error << std::endl;
       outfile << "Target max edge ratio: " << Max_permitted_edge_ratio
               << std::endl;
       outfile << "Min. allowed element size: " << Min_element_size << std::endl;
       outfile << "Max. allowed element size: " << Max_element_size << std::endl;
       outfile << "Don't unrefine if less than " << Max_keep_unrefined
               << " elements need unrefinement." << std::endl;
       outfile << std::endl;
     }
References Max_element_size, oomph::RefineableMeshBase::Max_keep_unrefined, Max_permitted_edge_ratio, oomph::RefineableMeshBase::Max_permitted_error, Min_element_size, and oomph::RefineableMeshBase::Min_permitted_error.
max_element_size()
double& oomph::RefineableTetMeshBase::max_element_size () inline
Max element size allowed during adaptation.
     {
       return Max_element_size;
     }
References Max_element_size.
max_permitted_edge_ratio()
double& oomph::RefineableTetMeshBase::max_permitted_edge_ratio () inline
Min edge ratio before remesh gets triggered.
     {
       return Max_permitted_edge_ratio;
     }
References Max_permitted_edge_ratio.
min_element_size()
double& oomph::RefineableTetMeshBase::min_element_size () inline
Min element size allowed during adaptation.
     {
       return Min_element_size;
     }
References Min_element_size.
Member Data Documentation
Max_element_size
double oomph::RefineableTetMeshBase::Max_element_size
Max permitted element size.
Referenced by compute_volume_target(), doc_adaptivity_targets(), oomph::RefineableGmshTetMesh< ELEMENT >::initialise_adaptation_data(), and max_element_size().
Max_permitted_edge_ratio
double oomph::RefineableTetMeshBase::Max_permitted_edge_ratio
Max edge ratio before remesh gets triggered.
Referenced by doc_adaptivity_targets(), oomph::RefineableGmshTetMesh< ELEMENT >::initialise_adaptation_data(), and max_permitted_edge_ratio().
Min_element_size
double oomph::RefineableTetMeshBase::Min_element_size
Min permitted element size.
Referenced by compute_volume_target(), doc_adaptivity_targets(), oomph::RefineableGmshTetMesh< ELEMENT >::initialise_adaptation_data(), and min_element_size().
The documentation for this class was generated from the following file:
refineable_mesh.h