MercuryDPM: BallPointStuff< Dim > Struct Template Reference
BallPointStuff< Dim > Struct Template Reference
Public Types
typedef double Scalar
typedef Matrix< double, Dim, 1 > VectorType
typedef Ball< Dim > BallType
typedef AlignedBox< double, Dim > BoxType
Public Member Functions
BallPointStuff ()
BallPointStuff (const VectorType &inP)
bool intersectVolume (const BoxType &r)
bool intersectObject (const BallType &b)
bool intersectVolumeVolume (const BoxType &r1, const BoxType &r2)
bool intersectVolumeObject (const BoxType &r, const BallType &b)
bool intersectObjectVolume (const BallType &b, const BoxType &r)
bool intersectObjectObject (const BallType &b1, const BallType &b2)
bool intersectVolumeObject (const BoxType &r, const VectorType &v)
bool intersectObjectObject (const BallType &b, const VectorType &v)
double minimumOnVolume (const BoxType &r)
double minimumOnObject (const BallType &b)
double minimumOnVolumeVolume (const BoxType &r1, const BoxType &r2)
double minimumOnVolumeObject (const BoxType &r, const BallType &b)
double minimumOnObjectVolume (const BallType &b, const BoxType &r)
double minimumOnObjectObject (const BallType &b1, const BallType &b2)
double minimumOnVolumeObject (const BoxType &r, const VectorType &v)
double minimumOnObjectObject (const BallType &b, const VectorType &v)
Public Attributes
VectorType p
int calls
int count
Member Typedef Documentation
BallType
template<int Dim> typedef Ball<Dim> BallPointStuff< Dim >::BallType
BoxType
template<int Dim> typedef AlignedBox<double, Dim> BallPointStuff< Dim >::BoxType
Scalar
template<int Dim> typedef double BallPointStuff< Dim >::Scalar
VectorType
template<int Dim> typedef Matrix<double, Dim, 1> BallPointStuff< Dim >::VectorType
Constructor & Destructor Documentation
BallPointStuff() [1/2]
template<int Dim> BallPointStuff< Dim >::BallPointStuff () inline
 : calls(0), count(0) {}
BallPointStuff() [2/2]
template<int Dim> BallPointStuff< Dim >::BallPointStuff (const VectorType & inP) inline
 : p(inP), calls(0), count(0) {}
Member Function Documentation
intersectObject()
template<int Dim> bool BallPointStuff< Dim >::intersectObject (const BallType & b) inline
{
     ++calls;
     if ((b.center - p).squaredNorm() < SQR(b.radius)) ++count;
     return false;  // continue
   }
References b, BallPointStuff< Dim >::calls, BallPointStuff< Dim >::count, BallPointStuff< Dim >::p, and SQR().
intersectObjectObject() [1/2]
template<int Dim> bool BallPointStuff< Dim >::intersectObjectObject (const BallType & b, const VectorType & v) inline
{
     ++calls;
     if ((b.center - v).squaredNorm() < SQR(b.radius)) ++count;
     return false;
   }
References b, BallPointStuff< Dim >::calls, BallPointStuff< Dim >::count, SQR(), and v.
intersectObjectObject() [2/2]
template<int Dim> bool BallPointStuff< Dim >::intersectObjectObject (const BallType & b1, const BallType & b2) inline
{
     ++calls;
     if ((b1.center - b2.center).norm() < b1.radius + b2.radius) ++count;
     return false;
   }
References BallPointStuff< Dim >::calls, Ball< Dim >::center, BallPointStuff< Dim >::count, and Ball< Dim >::radius.
Referenced by TreeTest< Dim >::testIntersect2().
intersectObjectVolume()
template<int Dim> bool BallPointStuff< Dim >::intersectObjectVolume (const BallType & b, const BoxType & r) inline
{
     ++calls;
     return r.squaredExteriorDistance(b.center) < SQR(b.radius);
   }
References b, BallPointStuff< Dim >::calls, UniformPSDSelfTest::r, and SQR().
intersectVolume()
template<int Dim> bool BallPointStuff< Dim >::intersectVolume (const BoxType & r) inline
{
     ++calls;
     return r.contains(p);
   }
References BallPointStuff< Dim >::calls, BallPointStuff< Dim >::p, and UniformPSDSelfTest::r.
intersectVolumeObject() [1/2]
template<int Dim> bool BallPointStuff< Dim >::intersectVolumeObject (const BoxType & r, const BallType & b) inline
{
     ++calls;
     return r.squaredExteriorDistance(b.center) < SQR(b.radius);
   }
References b, BallPointStuff< Dim >::calls, UniformPSDSelfTest::r, and SQR().
intersectVolumeObject() [2/2]
template<int Dim> bool BallPointStuff< Dim >::intersectVolumeObject (const BoxType & r, const VectorType & v) inline
{
     ++calls;
     return r.contains(v);
   }
References BallPointStuff< Dim >::calls, UniformPSDSelfTest::r, and v.
intersectVolumeVolume()
template<int Dim> bool BallPointStuff< Dim >::intersectVolumeVolume (const BoxType & r1, const BoxType & r2) inline
{
     ++calls;
     return !(r1.intersection(r2)).isNull();
   }
References BallPointStuff< Dim >::calls, and Eigen::AlignedBox< Scalar_, AmbientDim_ >::intersection().
minimumOnObject()
template<int Dim> double BallPointStuff< Dim >::minimumOnObject (const BallType & b) inline
{
     ++calls;
     return (std::max)(0., (b.center - p).squaredNorm() - SQR(b.radius));
   }
References b, BallPointStuff< Dim >::calls, max, BallPointStuff< Dim >::p, and SQR().
minimumOnObjectObject() [1/2]
template<int Dim> double BallPointStuff< Dim >::minimumOnObjectObject (const BallType & b, const VectorType & v) inline
{
     ++calls;
     return SQR((std::max)(0., (b.center - v).norm() - b.radius));
   }
References b, BallPointStuff< Dim >::calls, max, SQR(), and v.
minimumOnObjectObject() [2/2]
template<int Dim> double BallPointStuff< Dim >::minimumOnObjectObject (const BallType & b1, const BallType & b2) inline
{
     ++calls;
     return SQR((std::max)(0., (b1.center - b2.center).norm() - b1.radius - b2.radius));
   }
References BallPointStuff< Dim >::calls, Ball< Dim >::center, max, Ball< Dim >::radius, and SQR().
Referenced by TreeTest< Dim >::testMinimize2().
minimumOnObjectVolume()
template<int Dim> double BallPointStuff< Dim >::minimumOnObjectVolume (const BallType & b, const BoxType & r) inline
{
     ++calls;
     return SQR((std::max)(0., r.exteriorDistance(b.center) - b.radius));
   }
References b, BallPointStuff< Dim >::calls, max, UniformPSDSelfTest::r, and SQR().
minimumOnVolume()
template<int Dim> double BallPointStuff< Dim >::minimumOnVolume (const BoxType & r) inline
{
     ++calls;
     return r.squaredExteriorDistance(p);
   }
References BallPointStuff< Dim >::calls, BallPointStuff< Dim >::p, and UniformPSDSelfTest::r.
minimumOnVolumeObject() [1/2]
template<int Dim> double BallPointStuff< Dim >::minimumOnVolumeObject (const BoxType & r, const BallType & b) inline
{
     ++calls;
     return SQR((std::max)(0., r.exteriorDistance(b.center) - b.radius));
   }
References b, BallPointStuff< Dim >::calls, max, UniformPSDSelfTest::r, and SQR().
minimumOnVolumeObject() [2/2]
template<int Dim> double BallPointStuff< Dim >::minimumOnVolumeObject (const BoxType & r, const VectorType & v) inline
{
     ++calls;
     return r.squaredExteriorDistance(v);
   }
References BallPointStuff< Dim >::calls, UniformPSDSelfTest::r, and v.
minimumOnVolumeVolume()
template<int Dim> double BallPointStuff< Dim >::minimumOnVolumeVolume (const BoxType & r1, const BoxType & r2) inline
{
     ++calls;
     return r1.squaredExteriorDistance(r2);
   }
References BallPointStuff< Dim >::calls, and Eigen::AlignedBox< Scalar_, AmbientDim_ >::squaredExteriorDistance().
Member Data Documentation
calls
template<int Dim> int BallPointStuff< Dim >::calls
Referenced by BallPointStuff< Dim >::intersectObject(), BallPointStuff< Dim >::intersectObjectObject(), BallPointStuff< Dim >::intersectObjectVolume(), BallPointStuff< Dim >::intersectVolume(), BallPointStuff< Dim >::intersectVolumeObject(), BallPointStuff< Dim >::intersectVolumeVolume(), BallPointStuff< Dim >::minimumOnObject(), BallPointStuff< Dim >::minimumOnObjectObject(), BallPointStuff< Dim >::minimumOnObjectVolume(), BallPointStuff< Dim >::minimumOnVolume(), BallPointStuff< Dim >::minimumOnVolumeObject(), and BallPointStuff< Dim >::minimumOnVolumeVolume().
count
template<int Dim> int BallPointStuff< Dim >::count
Referenced by BallPointStuff< Dim >::intersectObject(), BallPointStuff< Dim >::intersectObjectObject(), TreeTest< Dim >::testIntersect1(), and TreeTest< Dim >::testIntersect2().
p
template<int Dim> VectorType BallPointStuff< Dim >::p
Referenced by BallPointStuff< Dim >::intersectObject(), BallPointStuff< Dim >::intersectVolume(), BallPointStuff< Dim >::minimumOnObject(), and BallPointStuff< Dim >::minimumOnVolume().
The documentation for this struct was generated from the following file:
BVH.cpp