MercuryDPM: 3d_static_cap_elastic.cc File Reference
3d_static_cap_elastic.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "fluid_interface.h"
#include "constitutive.h"
#include "solid.h"
#include "meshes/quarter_tube_mesh.h"
Classes
class AxialSolidQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >
class SolidFreeSurfaceRotationProblem< ELEMENT >
Entry flow problem in quarter tube domain.
Namespaces
Global_Physical_Variables
Global variables.
WallFunction
Functions
void WallFunction::normal (const Vector< double > &x, Vector< double > &normal)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
Driver for 3D entry flow into a quarter tube. If there are any command line arguments, we regard this as a validation run and perform only a single adaptation
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Allow (up to) five rounds of fully automatic adapation in response to
  //-----------------------------------------------------------------------
  // error estimate
  //---------------
  //unsigned max_adapt;
  double max_error_target,min_error_target;
  using namespace Global_Physical_Variables;
  // Set max number of adaptations in black-box Newton solver and
  // error targets for adaptation
  if (CommandLineArgs::Argc==1)
   {
    // Up to five adaptations
    //max_adapt=5;
    // Error targets for adaptive refinement
    max_error_target=0.005;
    min_error_target=0.0005;
   }
  // Validation run: Only one adaptation. Relax error targets
  // to ensure that not all elements are refined so we're getting
  // some hanging nodes.
  else
   {
    // Validation run: Just one round of adaptation
    //max_adapt=1;
    // Error targets for adaptive refinement
    max_error_target=0.02;
    min_error_target=0.002;
   }
  // end max_adapt setup
  unsigned n_angles = 1;
  // Set up doc info
  DocInfo doc_info;
  // Do Taylor-Hood elements
  //------------------------
  {
   // Set output directory
   doc_info.set_directory("RESLT_TH_internal_elastic");
   // Step number
   doc_info.number()=0;
   // Build problem
   SolidFreeSurfaceRotationProblem<
    Hijacked<RefineablePseudoSolidNodeUpdateElement<
    RefineableQTaylorHoodElement<3>,
    RefineableQPVDElement<3,3> > > >
    problem(doc_info,min_error_target,max_error_target,1);
   cout << " Doing Taylor Hood elements (internal hijack) " << std::endl;
   //Hand set the coordinates to the lagrangian coordinates
   //This is required because the refinement gets things a bit wrong
   // (Amazingly) must talk to Matthias about it
   problem.set_positions_from_lagrangian_coordinates();
   // Solve the problem  (DO NOT ADAPT)
   problem.newton_solve();
   // Doc solution after solving
   problem.doc_solution();
   // Increment label for output files
   problem.Doc_info.number()++;
   //Decrease the contact angle
   for(unsigned i=0;i<n_angles;i++)
    {
     Angle -= 0.1;
     problem.newton_solve();
    // Doc solution after solving
    problem.doc_solution();
    // Increment label for output files
    problem.Doc_info.number()++;
    }
  }
  // Do Taylor-Hood elements
  //------------------------
  {
   // Set output directory
   doc_info.set_directory("RESLT_TH_external_elastic");
   // Step number
   doc_info.number()=0;
   // Build problem
   SolidFreeSurfaceRotationProblem<
    Hijacked<RefineablePseudoSolidNodeUpdateElement<
    RefineableQTaylorHoodElement<3>,
    RefineableQPVDElement<3,3> > > >
    problem(doc_info,min_error_target,max_error_target,0);
   cout << " Doing Taylor Hood elements (external hijack) " << std::endl;
   //Hand set the coordinates to the lagrangian coordinates
   //This is required because the refinement gets things a bit wrong
   // (Amazingly) must talk to Matthias about it
   problem.set_positions_from_lagrangian_coordinates();
   // Solve the problem  (DO NOT ADAPT)
   problem.newton_solve();
   // Doc solution after solving
   problem.doc_solution();
   // Increment label for output files
   problem.Doc_info.number()++;
   //Decrease the contact angle
   for(unsigned i=0;i<n_angles;i++)
    {
     Angle -= 0.1;
     problem.newton_solve();
    // Doc solution after solving
    problem.doc_solution();
    // Increment label for output files
    problem.Doc_info.number()++;
    }
  }
  // Do Crouzeix Raviart elements
  //------------------------
  {
   // Set output directory
   doc_info.set_directory("RESLT_CR_internal_elastic");
   // Step number
   doc_info.number()=0;
   // Build problem
   SolidFreeSurfaceRotationProblem<
    Hijacked<RefineablePseudoSolidNodeUpdateElement<
    RefineableQCrouzeixRaviartElement<3>,
    RefineableQPVDElement<3,3> > > >
    problem(doc_info,min_error_target,max_error_target,2);
   cout << " Doing Crouzeix Raviart elements (internal hijack) " << std::endl;
   //Hand set the coordinates to the lagrangian coordinates
   //This is required because the refinement gets things a bit wrong
   // (Amazingly) must talk to Matthias about it
   problem.set_positions_from_lagrangian_coordinates();
   // Solve the problem  (DO NOT ADAPT)
   problem.newton_solve();
   // Doc solution after solving
   problem.doc_solution();
   // Increment label for output files
   problem.Doc_info.number()++;
   //Decrease the contact angle
   for(unsigned i=0;i<n_angles;i++)
    {
     Angle -= 0.1;
     problem.newton_solve();
    // Doc solution after solving
    problem.doc_solution();
    // Increment label for output files
    problem.Doc_info.number()++;
    }
  }
  // Do Taylor-Hood elements
  //------------------------
  {
   // Set output directory
   doc_info.set_directory("RESLT_CR_external_elastic");
   // Step number
   doc_info.number()=0;
   // Build problem
   SolidFreeSurfaceRotationProblem<
    Hijacked<RefineablePseudoSolidNodeUpdateElement<
    RefineableQCrouzeixRaviartElement<3>,
    RefineableQPVDElement<3,3> > > >
    problem(doc_info,min_error_target,max_error_target,0);
   cout << " Doing Crouzeix Raviart elements (external hijack) " << std::endl;
   //Hand set the coordinates to the lagrangian coordinates
   //This is required because the refinement gets things a bit wrong
   // (Amazingly) must talk to Matthias about it
   problem.set_positions_from_lagrangian_coordinates();
   // Solve the problem  (DO NOT ADAPT)
   problem.newton_solve();
   // Doc solution after solving
   problem.doc_solution();
   // Increment label for output files
   problem.Doc_info.number()++;
   //Decrease the contact angle
   for(unsigned i=0;i<n_angles;i++)
    {
     Angle -= 0.1;
     problem.newton_solve();
    // Doc solution after solving
    problem.doc_solution();
    // Increment label for output files
    problem.Doc_info.number()++;
    }
  }
 } // end_of_main
References Global_Physical_Variables::Angle, oomph::CommandLineArgs::Argc, i, oomph::DocInfo::number(), problem, oomph::DocInfo::set_directory(), and Flag_definition::setup().