MercuryDPM: Tutorial_commainit_01b.cpp File Reference
Tutorial_commainit_01b.cpp File Reference
Functions
m row (0)<< 1
m m block (1, 0, 2, 2)<< 4
m m m col (2).tail(2)<< 6
Variables
Matrix3f m
Function Documentation
block()
m m block (1 , 0 , 2 , 2)
Referenced by Eigen::internal::block_evaluator< ArgType, BlockRows, BlockCols, InnerPanel, true >::block_evaluator(), check_tutorial_examples(), PacketBlockSet< Scalar, StorageOrder, n >::comparePacketBlock(), Eigen::internal::convertArrayF32toBF16Col(), Eigen::internal::convertArrayF32toBF16ColVSX(), corners(), create_matrix_ascend_col_row(), Eigen::internal::dhs_cpack< Scalar, DataMapper, Packet, PacketC, StorageOrder, Conjugate, PanelMode, UseLhs >::dhs_cblock(), Eigen::internal::dhs_pack< double, DataMapper, Packet2d, StorageOrder, PanelMode, true >::dhs_copy(), Eigen::internal::dhs_pack< Scalar, DataMapper, Packet, StorageOrder, PanelMode, UseLhs >::dhs_copy(), EIGEN_DECLARE_TEST(), Eigen::internal::kernel_retval< FullPivLU< MatrixType_, PermutationIndex_ > >::evalTo(), Eigen::internal::loadTwoRhsFloat32(), Eigen::internal::matrix_sqrt_quasi_triangular_2x2_diagonal_block(), Eigen::internal::dhs_pack< bfloat16, DataMapper, Packet8bf, StorageOrder, PanelMode, true >::operator()(), Eigen::internal::dhs_pack< bfloat16, DataMapper, Packet8bf, StorageOrder, PanelMode, false >::operator()(), vectorization_logic< Scalar, Enable >::run(), run_bdmp_spec_1(), PacketBlockSet< Scalar, StorageOrder, n >::setPacketBlock(), oomph::Diagonal< MATRIX >::setup(), oomph::SimpleTwoDofOnly< MATRIX >::setup(), oomph::SimpleOneDofOnly< MATRIX >::setup(), oomph::UpperTriangular< MATRIX >::setup(), oomph::TwoPlusThree< MATRIX >::setup(), oomph::TwoPlusThreeUpperTriangular< MATRIX >::setup(), oomph::SimpleBlockDiagonalPreconditioner< MATRIX >::setup(), oomph::BlockDiagonalPreconditioner< MATRIX >::setup(), SkewedInnerBlock(), sparse_block(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::storePacketBlock_helper< SubPacket, Scalar_, n, idx >::store(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::storePacketBlock_helper< SubPacket, std::complex< float >, n, idx >::store(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::storePacketBlock_helper< SubPacket, std::complex< double >, n, idx >::store(), Eigen::internal::PacketBlockManagement< Index, Scalar, Packet, n, idx, StorageOrder >::store(), Eigen::internal::PacketBlockManagement< Index, Scalar, Packet, n, idx, RowMajor >::store(), Eigen::internal::PacketBlockManagement< Index, Scalar, Packet, n, -1, StorageOrder >::store(), Eigen::internal::PacketBlockManagement< Index, Scalar, Packet, n, -1, RowMajor >::store(), Eigen::internal::storeBlock(), Eigen::internal::storeConvertBlockBF16(), Eigen::internal::storeConvertTwoBF16(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::storePacketBlock(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::storePacketBlock(), test_block_io_copy_data_from_source_to_target(), test_block_io_copy_using_reordered_dimensions(), test_block_io_copy_using_reordered_dimensions_do_not_squeeze(), test_block_io_copy_using_reordered_dimensions_squeeze(), test_block_mapper_maps_every_element(), test_skewed_inner_dim_block_shape(), test_uniform_block_shape(), UpdateCoeffSet(), VerifyBlockAssignment(), and VerifyBlockEvaluator().
col()
m m m col (2)
row()
m row (0)
Variable Documentation
m
Matrix3f m