MercuryDPM: mesh_from_inline_triangle.cc File Reference
mesh_from_inline_triangle.cc File Reference
#include <fenv.h>
#include "generic.h"
#include "poisson.h"
#include "meshes/triangle_mesh.h"
Classes
class UnstructuredPoissonProblem< ELEMENT >
Class definition.
Namespaces
TanhSolnForPoisson
Namespace for exact solution for Poisson equation with "sharp step".
Functions
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForPoisson::get_source (const Vector< double > &x, double &source)
Source function to make it an exact solution.
void TanhSolnForPoisson::zero (const Vector< double > &x, Vector< double > &u)
int main (int argc, char **argv)
Driver code for demo of inline triangle mesh generation.
Function Documentation
main()
int main (int argc , char ** argv)
Driver code for demo of inline triangle mesh generation.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Validation?
  CommandLineArgs::specify_command_line_flag("--validation");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Create problem
  UnstructuredPoissonProblem<ProjectablePoissonElement<TPoissonElement<2,3> > >
   problem;
 //  // Solve, adapt and doc manually
 //  unsigned nadapt=4;
 //  for (unsigned i=0;i<nadapt;i++)
 //   {
 //    problem.newton_solve();
 //    std::stringstream comment_stream;
 //    comment_stream << "Solution after " << i << " manual adaptations";
 //    problem.doc_solution(comment_stream.str());
 //    if (i!=(nadapt-1))  problem.adapt();
 //   }
  // Doc the initial mesh
  //=====================
  std::stringstream comment_stream;
  comment_stream << "Initial mesh ";
  problem.doc_solution(comment_stream.str());
  // Loop over orientation of step
  //==============================
  unsigned nstep=5;
  if (CommandLineArgs::command_line_flag_has_been_set("--validation"))
   {
    nstep=2;
   }
  for (unsigned i=0;i<nstep;i++)
   {
    // Solve with spatial adaptation
    //==============================
    unsigned max_adapt=3;
    if (CommandLineArgs::command_line_flag_has_been_set("--validation"))
     {
      max_adapt=1;
     }
    problem.newton_solve(max_adapt);
    // Doc the solution
    //=================
    std::stringstream comment_stream;
    comment_stream << "Solution for tan(phi) = " << TanhSolnForPoisson::TanPhi;
    problem.doc_solution(comment_stream.str());
    // Rotate orientation of solution
    TanhSolnForPoisson::TanPhi+=0.5;
   }
 } //End of main
References oomph::CommandLineArgs::command_line_flag_has_been_set(), oomph::CommandLineArgs::doc_specified_flags(), i, oomph::CommandLineArgs::parse_and_assign(), problem, Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), and TanhSolnForPoisson::TanPhi.