MercuryDPM: Eigen::BiCGSTAB< MatrixType_, Preconditioner_ > Class Template Reference
Eigen::BiCGSTAB< MatrixType_, Preconditioner_ > Class Template Reference
Sparse linear algebra » Reference » IterativeLinearSolvers_Module
A bi conjugate gradient stabilized solver for sparse square problems.
#include <BiCGSTAB.h>
Public Types
typedef MatrixType_ MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef Preconditioner_ Preconditioner
Public Types inherited from Eigen::IterativeSolverBase< BiCGSTAB< MatrixType_, Preconditioner_ > >
enum
typedef internal::traits< BiCGSTAB< MatrixType_, Preconditioner_ > >::MatrixType MatrixType
typedef internal::traits< BiCGSTAB< MatrixType_, Preconditioner_ > >::Preconditioner Preconditioner
typedef MatrixType::Scalar Scalar
typedef MatrixType::StorageIndex StorageIndex
typedef MatrixType::RealScalar RealScalar
Public Member Functions
BiCGSTAB ()
template<typename MatrixDerived >
BiCGSTAB (const EigenBase< MatrixDerived > &A)
~BiCGSTAB ()
template<typename Rhs , typename Dest >
void _solve_vector_with_guess_impl (const Rhs &b, Dest &x) const
Public Member Functions inherited from Eigen::IterativeSolverBase< BiCGSTAB< MatrixType_, Preconditioner_ > >
IterativeSolverBase ()
IterativeSolverBase (const EigenBase< MatrixDerived > &A)
IterativeSolverBase (IterativeSolverBase &&)=default
~IterativeSolverBase ()
BiCGSTAB< MatrixType_, Preconditioner_ > & analyzePattern (const EigenBase< MatrixDerived > &A)
BiCGSTAB< MatrixType_, Preconditioner_ > & factorize (const EigenBase< MatrixDerived > &A)
BiCGSTAB< MatrixType_, Preconditioner_ > & compute (const EigenBase< MatrixDerived > &A)
EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
RealScalar tolerance () const
BiCGSTAB< MatrixType_, Preconditioner_ > & setTolerance (const RealScalar &tolerance)
Preconditioner & preconditioner ()
const Preconditioner & preconditioner () const
Index maxIterations () const
BiCGSTAB< MatrixType_, Preconditioner_ > & setMaxIterations (Index maxIters)
Index iterations () const
RealScalar error () const
const SolveWithGuess< BiCGSTAB< MatrixType_, Preconditioner_ >, Rhs, Guess > solveWithGuess (const MatrixBase< Rhs > &b, const Guess &x0) const
ComputationInfo info () const
void _solve_with_guess_impl (const Rhs &b, SparseMatrixBase< DestDerived > &aDest) const
std::enable_if_t< Rhs::ColsAtCompileTime !=1 &&DestDerived::ColsAtCompileTime !=1 > _solve_with_guess_impl (const Rhs &b, MatrixBase< DestDerived > &aDest) const
std::enable_if_t< Rhs::ColsAtCompileTime==1||DestDerived::ColsAtCompileTime==1 > _solve_with_guess_impl (const Rhs &b, MatrixBase< DestDerived > &dest) const
void _solve_impl (const Rhs &b, Dest &x) const
BiCGSTAB< MatrixType_, Preconditioner_ > & derived ()
const BiCGSTAB< MatrixType_, Preconditioner_ > & derived () const
Public Member Functions inherited from Eigen::SparseSolverBase< Derived >
SparseSolverBase ()
SparseSolverBase (SparseSolverBase &&other)
~SparseSolverBase ()
Derived & derived ()
const Derived & derived () const
template<typename Rhs >
const Solve< Derived, Rhs > solve (const MatrixBase< Rhs > &b) const
template<typename Rhs >
const Solve< Derived, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
template<typename Rhs , typename Dest >
void _solve_impl (const SparseMatrixBase< Rhs > &b, SparseMatrixBase< Dest > &dest) const
Private Types
typedef IterativeSolverBase< BiCGSTAB > Base
Private Member Functions
const ActualMatrixType & matrix () const
Private Attributes
RealScalar m_error
ComputationInfo m_info
Index m_iterations
Additional Inherited Members
Protected Types inherited from Eigen::IterativeSolverBase< BiCGSTAB< MatrixType_, Preconditioner_ > >
typedef SparseSolverBase< BiCGSTAB< MatrixType_, Preconditioner_ > > Base
typedef internal::generic_matrix_wrapper< MatrixType > MatrixWrapper
typedef MatrixWrapper::ActualMatrixType ActualMatrixType
Protected Member Functions inherited from Eigen::IterativeSolverBase< BiCGSTAB< MatrixType_, Preconditioner_ > >
void init ()
const ActualMatrixType & matrix () const
void grab (const InputType &A)
Protected Attributes inherited from Eigen::IterativeSolverBase< BiCGSTAB< MatrixType_, Preconditioner_ > >
MatrixWrapper m_matrixWrapper
Preconditioner m_preconditioner
Index m_maxIterations
RealScalar m_tolerance
RealScalar m_error
Index m_iterations
ComputationInfo m_info
bool m_analysisIsOk
bool m_factorizationIsOk
bool m_isInitialized
Protected Attributes inherited from Eigen::SparseSolverBase< Derived >
bool m_isInitialized
Detailed Description
template<typename MatrixType_, typename Preconditioner_>
class Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >
A bi conjugate gradient stabilized solver for sparse square problems.
This class allows to solve for A.x = b sparse linear problems using a bi conjugate gradient stabilized algorithm. The vectors x and b can be either dense or sparse.
Template Parameters
MatrixType_ the type of the sparse matrix A, can be a dense or a sparse matrix.
Preconditioner_ the type of the preconditioner. Default is DiagonalPreconditioner
\implsparsesolverconcept
The maximal number of iterations and tolerance value can be controlled via the setMaxIterations() and setTolerance() methods. The defaults are the size of the problem for the maximal number of iterations and NumTraits<Scalar>::epsilon() for the tolerance.
The tolerance corresponds to the relative residual error: |Ax-b|/|b|
Performance: when using sparse matrices, best performance is achied for a row-major sparse matrix format. Moreover, in this case multi-threading can be exploited if the user code is compiled with OpenMP enabled. See Eigen and multi-threading for details.
This class can be used as the direct solver classes. Here is a typical usage example:
int n = 10000;
VectorXd x(n), b(n);
SparseMatrix<double> A(n, n);
/* ... fill A and b ... */
BiCGSTAB<SparseMatrix<double> > solver;
solver.compute(A);
x = solver.solve(b);
std::cout << "#iterations:     " << solver.iterations() << std::endl;
std::cout << "estimated error: " << solver.error() << std::endl;
/* ... update b ... */
x = solver.solve(b);  // solve again
By default the iterations start with x=0 as an initial guess of the solution. One can control the start using the solveWithGuess() method.
BiCGSTAB can also be used in a matrix-free context, see the following example .
See also
class SimplicialCholesky, DiagonalPreconditioner, IdentityPreconditioner
Member Typedef Documentation
Base
template<typename MatrixType_ , typename Preconditioner_ > typedef IterativeSolverBase<BiCGSTAB> Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >::Base private
MatrixType
template<typename MatrixType_ , typename Preconditioner_ > typedef MatrixType_ Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >::MatrixType
Preconditioner
template<typename MatrixType_ , typename Preconditioner_ > typedef Preconditioner_ Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >::Preconditioner
RealScalar
template<typename MatrixType_ , typename Preconditioner_ > typedef MatrixType::RealScalar Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >::RealScalar
Scalar
template<typename MatrixType_ , typename Preconditioner_ > typedef MatrixType::Scalar Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >::Scalar
Constructor & Destructor Documentation
BiCGSTAB() [1/2]
template<typename MatrixType_ , typename Preconditioner_ > Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >::BiCGSTAB () inline
Default constructor.
 : Base() {}
BiCGSTAB() [2/2]
template<typename MatrixType_ , typename Preconditioner_ > template<typename MatrixDerived > Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >::BiCGSTAB (const EigenBase< MatrixDerived > & A) inline explicit
Initialize the solver with matrix A for further Ax=b solving.
This constructor is a shortcut for the default constructor followed by a call to compute().
Warning
this class stores a reference to the matrix A as well as some precomputed values that depend on it. Therefore, if A is changed this class becomes invalid. Call compute() to update it with the new matrix A, or modify a copy of A.
 : Base(A.derived()) {}
~BiCGSTAB()
template<typename MatrixType_ , typename Preconditioner_ > Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >::~BiCGSTAB () inline
 {}
Member Function Documentation
_solve_vector_with_guess_impl()
template<typename MatrixType_ , typename Preconditioner_ > template<typename Rhs , typename Dest > void Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl (const Rhs & b, Dest & x) const inline
{
     m_iterations = Base::maxIterations();
     m_error = Base::m_tolerance;
     bool ret = internal::bicgstab(matrix(), b, x, Base::m_preconditioner, m_iterations, m_error);
     m_info = (!ret) ? NumericalIssue : m_error <= Base::m_tolerance ? Success : NoConvergence;
   }
References b, Eigen::internal::bicgstab(), Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >::m_error, Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >::m_info, Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >::m_iterations, Eigen::IterativeSolverBase< Derived >::m_preconditioner, Eigen::IterativeSolverBase< Derived >::m_tolerance, Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >::matrix(), Eigen::IterativeSolverBase< Derived >::maxIterations(), Eigen::NoConvergence, Eigen::NumericalIssue, ret, Eigen::Success, and plotDoE::x.
matrix()
template<typename MatrixType_ , typename Preconditioner_ > const ActualMatrixType& Eigen::IterativeSolverBase< Derived >::matrix inline private
 { return m_matrixWrapper.matrix(); }
Referenced by Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl().
Member Data Documentation
m_error
template<typename MatrixType_ , typename Preconditioner_ > RealScalar Eigen::IterativeSolverBase< Derived >::m_error mutable private
Referenced by Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl().
m_info
template<typename MatrixType_ , typename Preconditioner_ > ComputationInfo Eigen::IterativeSolverBase< Derived >::m_info mutable private
Referenced by Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl().
m_iterations
template<typename MatrixType_ , typename Preconditioner_ > Index Eigen::IterativeSolverBase< Derived >::m_iterations mutable private
Referenced by Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl().
The documentation for this class was generated from the following file:
BiCGSTAB.h