MercuryDPM: circular_boulder_solar_radiation.cc File Reference
circular_boulder_solar_radiation.cc File Reference
#include <fenv.h>
#include "generic.h"
#include "unsteady_heat.h"
#include "solid.h"
#include "contact_elements.h"
#include "heat_transfer_and_melt_elements.h"
#include "temporary_stefan_boltzmann_elements.h"
#include "meshes/triangle_mesh.h"
Classes
class SolarRadiationProblem< ELEMENT >
Problem class.
Namespaces
ProblemParameters
Namespace for exact solution and problem parameters.
ExactSolution
Namespace for exact solution.
Macros
#define ADAPTIVE
Functions
void ProblemParameters::atmospheric_radiation (const double &time, double &solar_flux_magnitude, Vector< double > &solar_flux_unit_vector, double &total_diffuse_radiation)
void ExactSolution::get_exact_u_for_unsteady_heat_validation (const double &t, const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void ExactSolution::get_exact_u_for_unsteady_heat_validation (const double &t, const Vector< double > &x, double &u)
Exact solution as a scalar.
void ExactSolution::get_source_for_unsteady_heat_validation (const double &t, const Vector< double > &x, double &source)
Source function to make it an exact solution.
void ExactSolution::flux_into_bulk (const double &t, const Vector< double > &x, const Vector< double > &n, const double &u, double &flux)
void ExactSolution::prescribed_flux_for_unsteady_heat_validation (const double &t, const Vector< double > &x, const Vector< double > &n, const double &u, double &flux)
double ExactSolution::melting_surface_height (const double &t, const double &x)
Height of melting surface.
int main (int argc, char *argv[])
Driver code.
Variables
double ProblemParameters::Diffuse_radiation =0.4147111183
Diffuse radiation (based on 300 W/m^2)
double ProblemParameters::Direct_radiation =1.382370394
Direct radiation for peak of 1000 W/m^2.
double ProblemParameters::One_day =0.4084910633
One day in our non-dim units.
double ProblemParameters::Alpha_rock =0.001
Nondim thermal inertia for rock.
double ProblemParameters::Beta_rock =10.0
Nondim thermal conductivity for rock.
Macro Definition Documentation
ADAPTIVE
#define ADAPTIVE
Function Documentation
main()
int main (int argc , char * argv[])
Driver code.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
 {
  // hierher
  FiniteElement::Accept_negative_jacobian=true;
  FiniteElement::Tolerance_for_singular_jacobian=0.0;
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Suppress adaptation
  CommandLineArgs::specify_command_line_flag("--no_adapt");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Create generalised Hookean constitutive equations
  ProblemParameters::Constitutive_law_pt =
   new GeneralisedHookean(&ProblemParameters::Nu);
  // Define centre of penetrator
  ProblemParameters::Centre.resize(2);
  ProblemParameters::Centre[0]=0.5;
  ProblemParameters::Centre[1]=ProblemParameters::Y_c_initial;
  // Create penetrator
  ProblemParameters::Penetrator_pt = new
   CircularPenetrator(&ProblemParameters::Centre,
                      ProblemParameters::Radius);
 #ifdef ADAPTIVE
  // Build problem
  SolarRadiationProblem<ProjectableUnsteadyHeatElement<
   PseudoSolidNodeUpdateElement<TUnsteadyHeatElement<2,3>,TPVDElement<2,3> > > >
                     problem;
  #else
  // Build problem
  SolarRadiationProblem<TPVDElement<2,3> > problem;
 #endif
   //Output initial condition
  problem.doc_solution();
  unsigned max_adapt=1;
  if (CommandLineArgs::command_line_flag_has_been_set("--no_adapt"))
   {
    max_adapt=0;
   }
  // Number of parameter increments per period
  unsigned nstep_for_period=100;
  // Parameter variation
  unsigned nperiod=3;
  // Initial timestep
  double dt=1.0/double(nstep_for_period);
  // Initialise timestep -- also sets the weights for all timesteppers
  // in the problem.
  problem.initialise_dt(dt);
  // Set impulsive IC
  problem.assign_initial_values_impulsive(dt);
  while (problem.time_pt()->time()<double(nperiod))
   {
 #ifdef ADAPTIVE
    // Dummy double adaptivity (timestep is always accepted because
    // tolerance is set to huge value; mainly used to automatically
    // re-solve with smaller timestep increment after non-convergence
    double epsilon_t=DBL_MAX;
    bool first=false;
    double next_dt=
     problem.doubly_adaptive_unsteady_newton_solve(dt,epsilon_t,
                                                   max_adapt,first);
    dt = next_dt;
 #else
    // hierher
    abort();
    // Solve
    problem.newton_solve();
 #endif
    //Output solution
    problem.doc_solution();
   }
 } // end of main
References ProblemParameters::Centre, oomph::CommandLineArgs::command_line_flag_has_been_set(), ProblemParameters::Constitutive_law_pt, oomph::CommandLineArgs::doc_specified_flags(), ProblemParameters::Nu, oomph::CommandLineArgs::parse_and_assign(), ProblemParameters::Penetrator_pt, problem, ProblemParameters::Radius, Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), and ProblemParameters::Y_c_initial.