MercuryDPM: Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, Version > Struct Template Reference
Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, Version > Struct Template Reference
#include <TriangularMatrixMatrix.h>
Public Types
enum { SmallPanelWidth = 2 * plain_enum_max(Traits::mr, Traits::nr) , IsLower = (Mode & Lower) == Lower , SetDiag = (Mode & (ZeroDiag | UnitDiag)) ? 0 : 1 }
typedef gebp_traits< Scalar, Scalar > Traits
Static Public Member Functions
static EIGEN_DONT_INLINE void run (Index _rows, Index _cols, Index _depth, const Scalar *lhs_, Index lhsStride, const Scalar *rhs_, Index rhsStride, Scalar *res, Index resIncr, Index resStride, const Scalar &alpha, level3_blocking< Scalar, Scalar > &blocking)
Member Typedef Documentation
Traits
template<typename Scalar , typename Index , int Mode, int LhsStorageOrder, bool ConjugateLhs, int RhsStorageOrder, bool ConjugateRhs, int ResInnerStride, int Version> typedef gebp_traits<Scalar, Scalar> Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, Version >::Traits
Member Enumeration Documentation
anonymous enum
template<typename Scalar , typename Index , int Mode, int LhsStorageOrder, bool ConjugateLhs, int RhsStorageOrder, bool ConjugateRhs, int ResInnerStride, int Version> anonymous enum
Enumerator
SmallPanelWidth
IsLower
SetDiag
        {
     SmallPanelWidth = 2 * plain_enum_max(Traits::mr, Traits::nr),
     IsLower = (Mode & Lower) == Lower,
     SetDiag = (Mode & (ZeroDiag | UnitDiag)) ? 0 : 1
   };
Member Function Documentation
run()
template<typename Scalar , typename Index , int Mode, int LhsStorageOrder, bool ConjugateLhs, int RhsStorageOrder, bool ConjugateRhs, int ResInnerStride, int Version> EIGEN_DONT_INLINE void Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, Version >::run (Index _rows, Index _cols, Index _depth, const Scalar * lhs_, Index lhsStride, const Scalar * rhs_, Index rhsStride, Scalar * res, Index resIncr, Index resStride, const Scalar & alpha, level3_blocking< Scalar, Scalar > & blocking) static
{
   // strip zeros
   Index diagSize = (std::min)(_rows, _depth);
   Index rows = IsLower ? _rows : diagSize;
   Index depth = IsLower ? diagSize : _depth;
   Index cols = _cols;
   typedef const_blas_data_mapper<Scalar, Index, LhsStorageOrder> LhsMapper;
   typedef const_blas_data_mapper<Scalar, Index, RhsStorageOrder> RhsMapper;
   typedef blas_data_mapper<typename Traits::ResScalar, Index, ColMajor, Unaligned, ResInnerStride> ResMapper;
   LhsMapper lhs(lhs_, lhsStride);
   RhsMapper rhs(rhs_, rhsStride);
   ResMapper res(res_, resStride, resIncr);
   Index kc = blocking.kc();                    // cache block size along the K direction
   Index mc = (std::min)(rows, blocking.mc());  // cache block size along the M direction
   // The small panel size must not be larger than blocking size.
   // Usually this should never be the case because SmallPanelWidth^2 is very small
   // compared to L2 cache size, but let's be safe:
   Index panelWidth = (std::min)(Index(SmallPanelWidth), (std::min)(kc, mc));
   std::size_t sizeA = kc * mc;
   std::size_t sizeB = kc * cols;
   ei_declare_aligned_stack_constructed_variable(Scalar, blockA, sizeA, blocking.blockA());
   ei_declare_aligned_stack_constructed_variable(Scalar, blockB, sizeB, blocking.blockB());
   Matrix<Scalar, SmallPanelWidth, SmallPanelWidth, LhsStorageOrder> triangularBuffer;
   triangularBuffer.setZero();
   if ((Mode & ZeroDiag) == ZeroDiag)
     triangularBuffer.diagonal().setZero();
   else
     triangularBuffer.diagonal().setOnes();
   gebp_kernel<Scalar, Scalar, Index, ResMapper, Traits::mr, Traits::nr, ConjugateLhs, ConjugateRhs> gebp_kernel;
   gemm_pack_lhs<Scalar, Index, LhsMapper, Traits::mr, Traits::LhsProgress, typename Traits::LhsPacket4Packing,
                 LhsStorageOrder>
       pack_lhs;
   gemm_pack_rhs<Scalar, Index, RhsMapper, Traits::nr, RhsStorageOrder> pack_rhs;
   for (Index k2 = IsLower ? depth : 0; IsLower ? k2 > 0 : k2 < depth; IsLower ? k2 -= kc : k2 += kc) {
     Index actual_kc = (std::min)(IsLower ? k2 : depth - k2, kc);
     Index actual_k2 = IsLower ? k2 - actual_kc : k2;
     // align blocks with the end of the triangular part for trapezoidal lhs
     if ((!IsLower) && (k2 < rows) && (k2 + actual_kc > rows)) {
       actual_kc = rows - k2;
       k2 = k2 + actual_kc - kc;
     }
     pack_rhs(blockB, rhs.getSubMapper(actual_k2, 0), actual_kc, cols);
     // the selected lhs's panel has to be split in three different parts:
     //  1 - the part which is zero => skip it
     //  2 - the diagonal block => special kernel
     //  3 - the dense panel below (lower case) or above (upper case) the diagonal block => GEPP
     // the block diagonal, if any:
     if (IsLower || actual_k2 < rows) {
       // for each small vertical panels of lhs
       for (Index k1 = 0; k1 < actual_kc; k1 += panelWidth) {
         Index actualPanelWidth = std::min<Index>(actual_kc - k1, panelWidth);
         Index lengthTarget = IsLower ? actual_kc - k1 - actualPanelWidth : k1;
         Index startBlock = actual_k2 + k1;
         Index blockBOffset = k1;
         // => GEBP with the micro triangular block
         // The trick is to pack this micro block while filling the opposite triangular part with zeros.
         // To this end we do an extra triangular copy to a small temporary buffer
         for (Index k = 0; k < actualPanelWidth; ++k) {
           if (SetDiag) triangularBuffer.coeffRef(k, k) = lhs(startBlock + k, startBlock + k);
           for (Index i = IsLower ? k + 1 : 0; IsLower ? i < actualPanelWidth : i < k; ++i)
             triangularBuffer.coeffRef(i, k) = lhs(startBlock + i, startBlock + k);
         }
         pack_lhs(blockA, LhsMapper(triangularBuffer.data(), triangularBuffer.outerStride()), actualPanelWidth,
                  actualPanelWidth);
         gebp_kernel(res.getSubMapper(startBlock, 0), blockA, blockB, actualPanelWidth, actualPanelWidth, cols, alpha,
                     actualPanelWidth, actual_kc, 0, blockBOffset);
         // GEBP with remaining micro panel
         if (lengthTarget > 0) {
           Index startTarget = IsLower ? actual_k2 + k1 + actualPanelWidth : actual_k2;
           pack_lhs(blockA, lhs.getSubMapper(startTarget, startBlock), actualPanelWidth, lengthTarget);
           gebp_kernel(res.getSubMapper(startTarget, 0), blockA, blockB, lengthTarget, actualPanelWidth, cols, alpha,
                       actualPanelWidth, actual_kc, 0, blockBOffset);
         }
       }
     }
     // the part below (lower case) or above (upper case) the diagonal => GEPP
     {
       Index start = IsLower ? k2 : 0;
       Index end = IsLower ? rows : (std::min)(actual_k2, rows);
       for (Index i2 = start; i2 < end; i2 += mc) {
         const Index actual_mc = (std::min)(i2 + mc, end) - i2;
         gemm_pack_lhs<Scalar, Index, LhsMapper, Traits::mr, Traits::LhsProgress, typename Traits::LhsPacket4Packing,
                       LhsStorageOrder, false>()(blockA, lhs.getSubMapper(i2, actual_k2), actual_kc, actual_mc);
         gebp_kernel(res.getSubMapper(i2, 0), blockA, blockB, actual_mc, actual_kc, cols, alpha, -1, -1, 0, 0);
       }
     }
   }
 }
References alpha, Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::blockA(), Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::blockB(), Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::coeffRef(), cols, Eigen::PlainObjectBase< Derived >::data(), ei_declare_aligned_stack_constructed_variable, Eigen::placeholders::end, i, k, Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::kc(), Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::mc(), min, Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::outerStride(), res, rows, Eigen::PlainObjectBase< Derived >::setOnes(), Eigen::PlainObjectBase< Derived >::setZero(), oomph::CumulativeTimings::start(), and Eigen::ZeroDiag.
The documentation for this struct was generated from the following file:
TriangularMatrixMatrix.h