MercuryDPM: AnnoyingScalar.h File Reference
AnnoyingScalar.h File Reference
#include <ostream>
Classes
struct my_exception
class AnnoyingScalar
struct Eigen::NumTraits< AnnoyingScalar >
Namespaces
Eigen
Namespace containing all symbols from the Eigen library.
Eigen::numext
Eigen::internal
Namespace containing low-level routines from the Eigen library.
Functions
AnnoyingScalar real (const AnnoyingScalar &x)
AnnoyingScalar imag (const AnnoyingScalar &)
AnnoyingScalar conj (const AnnoyingScalar &x)
AnnoyingScalar sqrt (const AnnoyingScalar &x)
AnnoyingScalar abs (const AnnoyingScalar &x)
AnnoyingScalar cos (const AnnoyingScalar &x)
AnnoyingScalar sin (const AnnoyingScalar &x)
AnnoyingScalar acos (const AnnoyingScalar &x)
AnnoyingScalar atan2 (const AnnoyingScalar &y, const AnnoyingScalar &x)
std::ostream & operator<< (std::ostream &stream, const AnnoyingScalar &x)
template<>
AnnoyingScalar Eigen::test_precision< AnnoyingScalar > ()
template<>
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE bool() Eigen::numext::isfinite (const AnnoyingScalar &x)
template<>
EIGEN_STRONG_INLINE double Eigen::internal::cast (const AnnoyingScalar &x)
AnnoyingScalar get_test_precision (const AnnoyingScalar &)
AnnoyingScalar test_relative_error (const AnnoyingScalar &a, const AnnoyingScalar &b)
bool test_isApprox (const AnnoyingScalar &a, const AnnoyingScalar &b)
bool test_isMuchSmallerThan (const AnnoyingScalar &a, const AnnoyingScalar &b)
Function Documentation
abs()
AnnoyingScalar abs (const AnnoyingScalar & x)
 { return std::abs(*x.v); }
References plotDoE::x.
Referenced by Eigen::LDLT< MatrixType_, UpLo_ >::_solve_impl_transposed(), Eigen::numext::abs(), SYCL::abs(), Eigen::SparseLU< MatrixType_, OrderingType_ >::absDeterminant(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::absDeterminant(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::absDeterminant(), Eigen::HouseholderQR< MatrixType_ >::absDeterminant(), oomph::IMRByBDF::actions_after_timestep(), SpeciesTest::actionsAfterSolve(), BouncingSuperQuadric::actionsAfterTimeStep(), DrivenParticleClass::actionsAfterTimeStep(), oomph::Problem::adaptive_unsteady_newton_solve(), Domain::addParticlesToLists(), adjoint(), array_complex(), array_generic(), array_real(), array_special_functions(), asum(), aux_evalSolver(), AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::AxialSpineQuarterTubeMesh(), Eigen::internal::companion< Scalar_, Deg_ >::balance(), Eigen::internal::bicgstab(), big_sparse_triplet(), binary_ops_test(), Eigen::internal::blueNorm_impl(), oomph::Problem::calculate_predictions(), Eigen::cauchy_max_bound(), Eigen::cauchy_min_bound(), CRBond_Bessel::cbessik01(), CRBond_Bessel::cbessikna(), CRBond_Bessel::cbessiknb(), CRBond_Bessel::cbessikv(), CRBond_Bessel::cbessjy01(), CRBond_Bessel::cbessjyna(), CRBond_Bessel::cbessjynb(), CRBond_Bessel::cbessjyva(), check_abs(), check_abs< bool >(), check_accuracy(), check_arg(), check_extremity_accuracy(), check_histogram< bool >(), oomph::TimeStepper::check_predicted_values_up_to_date(), check_slerp(), check_sparse_abs_determinant(), check_sparse_inverse(), HGridOptimiser::checkLimit(), Eigen::internal::chkder(), NurbsUtils::close(), cod(), comparisons(), HomogenisationProblem< ELEMENT >::complete_problem_setup(), oomph::ComplexGMRES< MATRIX >::complex_solve_helper(), Eigen::SelfAdjointEigenSolver< MatrixType_ >::compute(), Eigen::EigenSolver< MatrixType_ >::compute(), Eigen::internal::MatrixFunctionAtomic< MatrixType >::compute(), Eigen::GeneralizedEigenSolver< MatrixType_ >::compute(), Eigen::IterScaling< MatrixType_ >::compute(), Eigen::MatrixPowerAtomic< MatrixType >::compute2x2(), Eigen::BDCSVD< MatrixType_, Options_ >::compute_impl(), Eigen::JacobiSVD< MatrixType_, Options_ >::compute_impl(), FrictionInteraction::computeFrictionForce(), Eigen::RealSchur< MatrixType_ >::computeFromHessenberg(), SuperQuadricParticle::computeHessianLabFixed(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::MatrixPower< MatrixType >::computeIntPower(), HertzianBSHPViscoelasticInteraction::computeNormalForce(), HertzianViscoelasticInteraction::computeNormalForce(), LinearPlasticViscoelasticInteraction::computeNormalForce(), LinearViscoelasticInteraction::computeNormalForce(), MeltableInteraction::computeNormalForce(), SinterInteraction::computeNormalForce(), SinterLinInteraction::computeNormalForce(), SPHInteraction::computeNormalForce(), PeriodicBoundaryHandler::computePeriodicComplexity(), SuperQuadricParticle::computeShape(), SuperQuadricParticle::computeShapeGradientLabFixed(), Eigen::ComplexSchur< MatrixType_ >::computeShift(), Eigen::RealSchur< MatrixType_ >::computeShift(), Eigen::BDCSVD< MatrixType_, Options_ >::computeSingVals(), HertzianSinterInteraction::computeSinterForce(), SlidingFrictionInteraction::computeSlidingSpring(), Eigen::BDCSVD< MatrixType_, Options_ >::computeSVDofM(), Multipole::convertMultipoleToLocal(), Eigen::internal::covar(), Eigen::BDCSVD< MatrixType_, Options_ >::deflation(), Eigen::BDCSVD< MatrixType_, Options_ >::deflation43(), Eigen::BDCSVD< MatrixType_, Options_ >::deflation44(), Eigen::NumericalDiff< Functor_, mode >::df(), Eigen::DGMRES< MatrixType_, Preconditioner_ >::dgmresComputeDeflationData(), Eigen::DGMRES< MatrixType_, Preconditioner_ >::dgmresCycle(), Eigen::BDCSVD< MatrixType_, Options_ >::divide(), ContactProblem< ELEMENT >::doc_solution(), TetmeshPoissonProblem< ELEMENT >::doc_solution(), RayleighProblem< ELEMENT, TIMESTEPPER >::doc_solution(), RayleighTractionProblem< ELEMENT, TIMESTEPPER >::doc_solution(), Eigen::EigenSolver< MatrixType_ >::doComputeEigenvectors(), Eigen::internal::dogleg(), EIGEN_CAT(), ElasticQuadFromTriangleMesh< ELEMENT >::ElasticQuadFromTriangleMesh(), evalSolverSugarFunction(), Eigen::internal::kernel_retval< FullPivLU< MatrixType_, PermutationIndex_ > >::evalTo(), Eigen::internal::image_retval< FullPivLU< MatrixType_, PermutationIndex_ > >::evalTo(), oomph::SarahBL::exact_soln(), SarahBL::exact_soln(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::extract_kernel(), Global_parameters::f1_exact(), boost::multiprecision::fabs(), oomph::QElement< 1, NNODE_1D >::face_outer_unit_normal_sign(), Eigen::SparseQR< MatrixType_, OrderingType_ >::factorize(), Eigen::IncompleteLUT< Scalar_, StorageIndex_ >::factorize(), Eigen::internal::fdjac1(), GlobalParameters::find_node_on_centerline(), Eigen::RealQZ< MatrixType_ >::findSmallDiagEntry(), Eigen::RealQZ< MatrixType_ >::findSmallSubdiagEntry(), Eigen::RealSchur< MatrixType_ >::findSmallSubdiagEntry(), FSICollapsibleChannelProblem< ELEMENT >::FSICollapsibleChannelProblem(), oomph::SarahBL::full_exact_soln(), SarahBL::full_exact_soln(), generalized_eigensolver_real(), oomph::ComplexGMRES< MATRIX >::generate_plane_rotation(), oomph::HelmholtzGMRESMG< MATRIX >::generate_plane_rotation(), oomph::StreamfunctionProblem::get_vels(), MeshTriangle::getDistanceNormalOverlapType(), Quaternion::getEuler(), InfiniteWall::getFurthestPointSuperQuadric(), WearableNurbsWall::getVolumeUnderSurface(), WearableNurbsWall::getVolumeUnderSurfaceX(), oomph::ODEProblem::global_temporal_error_norm(), Eigen::internal::gmres(), mathsFunc::goldenSectionSearch(), HGridOptimiser::goldenSectionSearch(), oomph::OcTree::gteq_face_neighbour(), oomph::OcTree::gteq_true_edge_neighbour(), hyperplane(), Eigen::internal::idrstabl(), Eigen::RealSchur< MatrixType_ >::initFrancisQRStep(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::interface_min_max(), oomph::AxisymmetricPoroelasticityEquations::interpolated_div_q(), inverse_for_fixed_size(), inverse_general_4x4(), exp_complex_test_impl< Scalar, Packet, HasExp >::is_exactly_equal(), GlobalParameters::is_in_pinned_region(), mathsFunc::isEqual(), Eigen::internal::AmbiVector< Scalar_, StorageIndex_ >::Iterator::Iterator(), lapackNorm(), Eigen::internal::least_square_conjugate_gradient(), TwoDDGProblem< ELEMENT >::limit(), linearStructure(), lines(), Eigen::internal::lmpar(), Eigen::internal::lmpar2(), Eigen::SparseLU< MatrixType_, OrderingType_ >::logAbsDeterminant(), oomph::DenseComplexMatrix::ludecompose(), RemoveSubnormals::main(), main(), Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::JacobiRotation< Scalar >::makeJacobi(), Eigen::internal::matrix_function_partition_eigenvalues(), Eigen::internal::matrix_log_compute_2x2(), oomph::ComplexMatrixBase::max_residual(), Eigen::LevenbergMarquardt< FunctorType_ >::minimizeOneStep(), Eigen::LevenbergMarquardt< FunctorType_ >::minimizeOptimumStorageOneStep(), mixingtypes(), CRBond_Bessel::msta1(), CRBond_Bessel::msta2(), NodeReordering::node_global_position_comparison(), oomph::NodeOrdering::node_global_position_comparison(), nrm2(), Eigen::internal::omega(), ComplexLess< T >::operator()(), oomph::AbsCmp< T >::operator()(), CompareElementCoordinate< ELEMENT >::operator()(), CompareNodes::operator()(), Eigen::internal::AmbiVector< Scalar_, StorageIndex_ >::Iterator::operator++(), Eigen::AngleAxis< Scalar_ >::operator=(), PolarNSProblem< ELEMENT >::output_streamfunction(), SuperQuadricParticle::overlapFromContactPoint(), packetmath(), packetmath_notcomplex(), packetmath_real(), ElasticBeamProblem::parameter_study(), parametrizedline(), Eigen::PardisoImpl< Derived >::pardisoInit(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::perform_power_method(), Eigen::internal::SparseLUImpl< Scalar, StorageIndex >::pivotL(), planes(), Eigen::internal::psincos_double(), qr(), qr_fixedsize(), qr_invertible(), qr_kahan_matrix(), quaternion(), Eigen::internal::QuickSplit(), Particles2023AnalysisHung::random_forest(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::rank(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank(), Eigen::SVDBase< Derived >::rank(), Eigen::internal::real_2x2_jacobi_svd(), real_qz(), Eigen::PolynomialSolverBase< Scalar_, Deg_ >::realRoots(), realRoots_to_monicPolynomial_test(), RefineablePoissonProblem< ELEMENT >::RefineablePoissonProblem(), rot(), rotg(), check_sqrt_impl< T >::run(), check_rsqrt_impl< T >::run(), Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 2 >::run(), Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 4 >::run(), Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 1 >::run(), Eigen::internal::norm1_default_impl< Scalar, true >::run(), Eigen::internal::norm1_default_impl< Scalar, false >::run(), Eigen::internal::hypot_impl< Scalar >::run(), adjoint_specific< false >::run(), processTriangularMatrix< MatrixType, 0 >::run(), exp_complex_test_impl< Scalar, Packet, HasExp >::run(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::run(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, Options, true >::run(), run_fixed_size_test(), run_test(), scal(), Eigen::PolynomialSolverBase< Scalar_, Deg_ >::selectRealRoot_withRespectToAbsRealPart(), Eigen::PolynomialSolverBase< Scalar_, Deg_ >::selectRealRoot_withRespectToRealPart(), RefineableOneDAdvectionDiffusionReactionProblem< ELEMENT >::set_initial_condition(), RefineableActivatorInhibitorProblem< ELEMENT >::set_initial_condition(), LevelSetWall::setShapeCube(), LevelSetWall::setShapeDiamond(), oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >::setup_algebraic_node_update(), oomph::TetMeshBase::setup_boundary_coordinates(), RotatingDrum::setupInitialConditions(), SegregationPeriodic::setupInitialConditions(), DrumRot::setupInitialConditions(), slerp_legacy(), slerp_legacy_nlerp(), oomph::HelmholtzGMRESMG< MATRIX >::solve_helper(), oomph::HelmholtzFGMRESMG< MATRIX >::solve_helper(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveNumericalDiffOneStep(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveOneStep(), sparse_basic(), sphericalHarmonics::sphericalHarmonics(), Eigen::RealQZ< MatrixType_ >::splitOffTwoRows(), Eigen::RealSchur< MatrixType_ >::splitOffTwoRows(), stable_norm(), Eigen::internal::stable_norm_impl(), Eigen::RealQZ< MatrixType_ >::step(), WearableNurbsWall::storeDebris(), oomph::LinearisedAxisymmetricNavierStokesEquations::strain_rate(), svd_least_square(), RefineablePorousChannelProblem< ELEMENT >::symmetrise_eigenfunction_for_adaptive_pitchfork_tracking(), test_abs(), test_async_multithread_contraction_agrees_with_singlethread(), test_basic_functions(), test_conversion(), test_exponent(), test_fft_non_power_of_2_round_trip(), test_full_contraction(), test_gpu_contractions(), test_gpu_forced_evals(), test_gpu_trancendental(), test_gpu_unary(), test_hypot(), test_isApprox_abs(), test_multithread_contraction_agrees_with_singlethread(), test_sum_accuracy(), test_unary_builtins_for_assignement(), testGeneral(), testMatrixType(), ActivatorInhibitorProblem< ELEMENT >::timestep(), oomph::EBDF3::timestep(), Trackball::track(), transformations(), LocalExpansion::translateLocalExpansion(), Multipole::TranslateMultipoleExpansionTo(), Eigen::internal::unary_evaluator< SparseView< Product< Lhs, Rhs, Options > >, IteratorBased >::unary_evaluator(), Eigen::internal::ldlt_inplace< Lower >::unblocked(), PeriodicBoundaryHandler::updateParticles(), vectorRedux(), and verify_euler().
acos()
AnnoyingScalar acos (const AnnoyingScalar & x)
 { return std::acos(*x.v); }
References plotDoE::x.
Referenced by Eigen::numext::acos(), ChangingTOIParticle::actionsAfterTimeStep(), oomph::VectorHelpers::angle(), array_real(), bounded_acos(), oomph::RefineableTriangleMesh< ELEMENT >::compute_area_target(), BaseCluster::computeInternalStructure(), Funnel::create_inflow_particle(), oomph::DiskWithTorusAroundEdgeTetMeshFacetedSurface::DiskWithTorusAroundEdgeTetMeshFacetedSurface(), GpuHelper::drawVector(), GpuHelper::drawVectorBox(), fft_rmse(), ArcWall::getDistanceAndNormal(), AngledPeriodicBoundary::getOpeningAngle(), Vec3D::getSphericalCoordinates(), main(), MeltContactProblem< ELEMENT >::MeltContactProblem(), packetmath_real(), Eigen::internal::pacos(), BaseCluster::particleInsertionSuccessful(), particleParticleTest(), Eigen::internal::kissfft_impl< Scalar_ >::real_twiddles(), SlidingFrictionSpecies::setCollisionTimeAndNormalAndTangentialRestitutionCoefficientNoDispt(), Eigen::QuaternionBase< Derived >::slerp(), slerp_legacy(), slerp_legacy_nlerp(), FallingBlockProblem< ELEMENT >::snap_onto_sphere(), RisingBubbleProblem< ELEMENT >::snap_onto_sphere(), SolarRadiationProblem< ELEMENT >::SolarRadiationProblem(), Trackball::track(), unary_ops_test(), UniformRandomPDs(), ClumpParticle::updateExtraQuantities(), and wallParticleTest().
atan2()
AnnoyingScalar atan2 (const AnnoyingScalar & y, const AnnoyingScalar & x)
 { return std::atan2(*y.v, *x.v); }
References plotDoE::x, and y.
Referenced by ChangingTOIParticle::actionsAfterTimeStep(), Global_Parameters::analytic_solution1(), Global_Parameters::analytic_solution2(), oomph::ImmersedRigidBodyElement::apply_rigid_body_motion(), array_complex(), array_real(), Eigen::atan2(), oomph::SolarRadiationBase::atmospheric_radiation(), binary_ops_test(), Eigen::EulerSystem< _AlphaAxis, _BetaAxis, _GammaAxis >::CalcEulerAngles_imp(), check_atan2(), FourierDecomposedHelmholtzProblem< ELEMENT >::check_gamma(), CircularPeriodicBoundary::checkBoundaryAfterParticleMoved(), oomph::HelmholtzBCElementBase< ELEMENT >::compute_contribution_to_fourier_components(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::compute_gamma_contribution(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::compute_gamma_contribution(), ScrewsymmetricIntersectionOfWalls::computeDeltaZ(), computeRoots(), CircularPeriodicBoundary::createPeriodicParticle(), oomph::ImmersedRigidBodyElement::dposition_dt(), ProblemParameters::exact_minus_dudr(), Global::exact_solution(), FreeSurfaceRotationProblem< ELEMENT >::FreeSurfaceRotationProblem(), PerturbationSolution::get_azimuthal_angle(), PlanarWave::get_exact_u(), ProblemParameters::get_exact_u(), GlobalParameters::get_exact_u(), GlobalFct::get_residuals(), StokesFlowExactWind::get_wind(), Quaternion::getAngleZ(), Vec3D::getCylindricalCoordinates(), HorizontalScrew::getDistanceAndNormal(), Coil::getDistanceAndNormal(), InfiniteWallWithHole::getDistanceAndNormal(), Screw::getDistanceAndNormalLabCoordinates(), Quaternion::getEuler(), Vec3D::getSphericalCoordinates(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::HelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::global_power_contribution(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_power_contribution(), Global_parameters::grad_f1(), Global_parameters::grad_f2(), Global_Parameters::grad_velocity_singularity1(), Global_Parameters::grad_velocity_singularity2(), WallFunction::normal(), EulerAngles< Scalar_ >::operator=(), Global_parameters::polar(), oomph::WarpedCircularDisk::position(), GlobalParameters::prescribed_incoming_flux(), Global_Parameters::press_load(), Global_Parameters::pressure_load(), Global_Parameters::pressure_singularity1(), Global_Parameters::pressure_singularity2(), RotatingDrumWet::printTime(), oomph::QuarterPipeMesh< ELEMENT >::QuarterPipeMesh(), CircularPeriodicBoundary::rotateParticle(), ClumpParticle::rotatePrincipalDirections(), FlowAroundCylinderProblem< ELEMENT >::set_boundary_conditions(), RefineableRotatingCylinderProblem< ELEMENT >::set_boundary_conditions(), oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::setup_gamma(), oomph::HelmholtzDtNMesh< ELEMENT >::setup_gamma(), FallingBlockProblem< ELEMENT >::snap_onto_sphere(), RisingBubbleProblem< ELEMENT >::snap_onto_sphere(), Global_Parameters::solid_boundary_displacement(), Global_parameters::source_function(), oomph::CircularPenetrator::surface_coordinate(), HeatedCircularPenetratorElement::surface_coordinate(), oomph::HeatedCircularPenetrator::temperature(), HeatedCircularPenetratorElement::temperature(), oomph::SolarRadiationBase::update_limiting_angles(), Global_Parameters::velocity_couette(), Global_Parameters::velocity_singularity1(), Global_Parameters::velocity_singularity2(), and oomph::TwoDAnnularMesh< ELEMENT >::wrap_into_annular_shape().
conj()
AnnoyingScalar conj (const AnnoyingScalar & x)
 { return x; }
References plotDoE::x.
Referenced by Eigen::HessenbergDecomposition< MatrixType_ >::_compute(), Eigen::accurateDot(), Eigen::JacobiRotation< Scalar >::adjoint(), adjoint(), oomph::ComplexGMRES< MATRIX >::apply_plane_rotation(), oomph::HelmholtzGMRESMG< MATRIX >::apply_plane_rotation(), array_complex(), Eigen::internal::triangular_dense_assignment_kernel< UpLo, SelfAdjoint, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignCoeff(), Eigen::internal::conditional_conj< Scalar, true >::coeff(), oomph::ComplexGMRES< MATRIX >::complex_solve_helper(), Eigen::BDCSVD< MatrixType_, Options_ >::deflation44(), determinant(), Eigen::SparseMatrixBase< Derived >::dot(), Eigen::SparseQR_QProduct< SparseQRType, Derived >::evalTo(), Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex >::evalTo(), Eigen::SparseQR< MatrixType_, OrderingType_ >::factorize(), Eigen::IncompleteCholesky< Scalar, UpLo_, OrderingType_ >::factorize(), Eigen::internal::traits< SimplicialLLT< MatrixType_, UpLo_, Ordering_ > >::getSymm(), Eigen::internal::traits< SimplicialLDLT< MatrixType_, UpLo_, Ordering_ > >::getSymm(), Eigen::internal::traits< SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > >::getSymm(), jacobi(), Eigen::internal::llt_rank_update_lower(), Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::MatrixBase< Derived >::makeHouseholder(), Eigen::JacobiRotation< Scalar >::makeJacobi(), Eigen::internal::scalar_conjugate_op< Scalar >::operator()(), Eigen::internal::conj_if< true >::operator()(), Eigen::internal::symm_pack_lhs< Scalar, Index, Pack1, Pack2_dummy, StorageOrder >::operator()(), Eigen::internal::symm_pack_rhs< Scalar, Index, nr, StorageOrder >::operator()(), Eigen::JacobiRotation< Scalar >::operator*(), orthomethods_2(), Eigen::internal::symm_pack_lhs< Scalar, Index, Pack1, Pack2_dummy, StorageOrder >::pack(), packetmath(), Eigen::internal::pconj(), Eigen::internal::permute_symm_to_fullsymm(), Eigen::internal::permute_symm_to_symm(), Eigen::internal::conj_helper< LhsScalar, RhsScalar, true, true >::pmul(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::processDataLineBluestein(), product_extra(), product_selfadjoint(), pset1_realimag(), randMatrixSpecialUnitary(), Eigen::SelfAdjointView< MatrixType_, UpLo >::rankUpdate(), rotg(), Eigen::internal::unitOrthogonal_selector< Derived, Size >::run(), Eigen::internal::unitOrthogonal_selector< Derived, 3 >::run(), Eigen::internal::unitOrthogonal_selector< Derived, 2 >::run(), Eigen::internal::householder_determinant< HCoeffs, Scalar, IsComplex >::run(), Eigen::internal::cross_impl< Derived, OtherDerived, Size >::run(), Eigen::internal::cross_impl< Derived, OtherDerived, 2 >::run(), Eigen::internal::conj_default_impl< Scalar, true >::run(), Eigen::internal::tensor_symmetry_assign_value< Tensor_ >::run(), adjoint_specific< true >::run(), adjoint_specific< false >::run(), Eigen::internal::cross3_impl< Arch, VectorLhs, VectorRhs, Scalar, Vectorizable >::run(), Eigen::internal::selfadjoint_matrix_vector_product< Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, Version >::run(), Eigen::internal::packed_rank2_update_selector< Scalar, Index, UpLo >::run(), Eigen::internal::rank2_update_selector< Scalar, Index, UpLo >::run(), Eigen::internal::selfadjoint_rank2_update_selector< Scalar, Index, UType, VType, Lower >::run(), Eigen::internal::selfadjoint_rank2_update_selector< Scalar, Index, UType, VType, Upper >::run(), Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, Vectorizable >::run(), Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, true >::run(), oomph::HelmholtzGMRESMG< MATRIX >::solve_helper(), oomph::HelmholtzFGMRESMG< MATRIX >::solve_helper(), Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::solveTransposedInPlace(), Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::solveTransposedInPlace(), Eigen::internal::sparse_selfadjoint_time_dense_product(), test_conjugate(), Eigen::JacobiRotation< Scalar >::transpose(), Eigen::internal::tridiagonalization_inplace(), trmm(), Eigen::internal::ldlt_inplace< Lower >::unblocked(), Eigen::internal::ldlt_inplace< Lower >::updateInPlace(), and Eigen::internal::upperbidiagonalization_blocked_helper().
cos()
AnnoyingScalar cos (const AnnoyingScalar & x)
 { return std::cos(*x.v); }
References plotDoE::x.
Referenced by oomph::PseudoBucklingRing::accel(), Jeffery_Solution::acceleration(), MeltContactProblem< ELEMENT >::actions_before_implicit_timestep(), SolarRadiationProblem< ELEMENT >::actions_before_implicit_timestep(), ContactProblem< ELEMENT >::actions_before_implicit_timestep(), FSIDrivenCavityProblem< ELEMENT >::actions_before_implicit_timestep(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_before_implicit_timestep(), UnstructuredFluidProblem< ELEMENT >::actions_before_implicit_timestep(), QuarterCircleDrivenCavityProblem2< ELEMENT >::actions_before_newton_solve(), QuarterCircleDrivenCavityProblem< ELEMENT >::actions_before_newton_solve(), TiltedCavityProblem< ELEMENT >::actions_before_newton_solve(), PolarNSProblem< ELEMENT >::actions_before_solve(), ChangingTOIParticle::actionsAfterTimeStep(), oomph::SphericalNavierStokesEquations::actual_dth(), VerticalMixerAngledBlades::addBlades(), VerticalMixerAngledBlades::addPrettyBlades(), ChuteWithWedge::addWedge(), alignedboxNonIntegralRotatable(), Global_Parameters::analytic_solution1(), Global_Parameters::analytic_solution2(), AngledPeriodicBoundarySecondUnitTest::AngledPeriodicBoundarySecondUnitTest(), AngledPeriodicBoundaryUnitTest::AngledPeriodicBoundaryUnitTest(), angleToVec(), AnnularQuadMesh< ELEMENT >::AnnularQuadMesh(), oomph::AnnularSpineMesh< ELEMENT >::AnnularSpineMesh(), oomph::ImmersedRigidBodyElement::apply_rigid_body_motion(), array_complex(), array_real(), ProblemParameters::atmospheric_radiation(), Global_parameters::b(), CRBond_Bessel::bessjy01a(), CRBond_Bessel::bessjy01b(), CRBond_Bessel::bessjynb(), CRBond_Bessel::bessjyv(), Global_Parameters::blend(), Global_Parameters::body_force(), BiharmonicTestFunctions2::boundary_E(), BiharmonicTestFunctions2::boundary_N(), Global_Parameters::boundary_traction(), oomph::WarpedCircularDisk::boundary_triad(), BiharmonicTestFunctions2::boundary_W(), oomph::ComplexDampedJacobi< MATRIX >::calculate_omega(), CRBond_Bessel::cbessjy01(), CRBond_Bessel::cbessjynb(), CRBond_Bessel::cbessjyva(), HeatedCircularPenetratorElement::centre(), CircularPenetratorElement::centre(), check_atan2(), check_locate_zeta(), exp_complex_test_impl< Scalar, Packet, HasExp >::cis(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::compute_gamma_contribution(), oomph::AxisymmetricPVDEquations::compute_physical_size(), oomph::AxisymmetricPVDEquationsWithPressure::compute_physical_size(), LiquidBridgeWilletInteraction::computeAdhesionForce(), LiquidMigrationLSInteraction::computeAdhesionForce(), LiquidMigrationWilletInteraction::computeAdhesionForce(), BaseCluster::computeInternalStructure(), SinterLinInteraction::computeNormalForce(), computeRoots(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::computeRoots(), oomph::deriv_functions::cos(), Eigen::numext::cos(), Funnel::create_funnel(), SegregationWithHopper::create_inflow_particle(), Funnel::create_inflow_particle(), CircularPeriodicBoundary::createPeriodicParticle(), LevelSetWall::createVTKSphere(), Global_Parameters::d2_u_r_dt2(), Global_Parameters::d2_u_theta_dt2(), Global_Parameters::d2_u_z_dt2(), oomph::Ellipse::d2position(), oomph::EllipticalTube::d2position(), SinusoidalWall::d2position(), InterfaceProblem< ELEMENT, TIMESTEPPER >::deform_free_surface(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::deform_interface(), TwoLayerInterfaceProblem< ELEMENT >::deform_interface(), oomph::deriv_functions::DampedOscillation::derivative(), oomph::deriv_functions::OrderReductionTest::derivative(), oomph::DiskWithTorusAroundEdgeTetMeshFacetedSurface::DiskWithTorusAroundEdgeTetMeshFacetedSurface(), oomph::SarahBL::Diss_sarah(), SarahBL::Diss_sarah(), oomph::SolidHelpers::doc_2D_principal_stress(), StefanBoltzmannProblem< ELEMENT >::doc_solution(), CapProblem< ELEMENT >::doc_solution(), PseudoSolidCapProblem< ELEMENT >::doc_solution(), SinusoidalWall::dposition(), oomph::Ellipse::dposition(), oomph::ImmersedRigidBodyElement::dposition_dt(), oomph::deriv_functions::dsin(), BiharmonicTestFunctions2::dudx_0(), BiharmonicTestFunctions2::dudx_1(), oomph::WarpedCircularDisk::dwdr(), eigen2support(), EIGEN_DECLARE_TEST(), ElasticRingProblem< ELEMENT >::ElasticRingProblem(), TanhSolnForLinearWave::exact_d2udt2(), TanhSolnForLinearWave::exact_dudt(), ProblemParameters::exact_minus_dudr(), Global::exact_solution(), Global_Parameters::exact_solution(), Global_Parameters::exact_solution_th(), TanhSolnForLinearWave::exact_u(), Global_parameters::f2_exact(), oomph::AxisymmetricSolidTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::AxisymmetricPVDEquations::fill_in_contribution_to_residuals_axisym_pvd(), oomph::AxisymmetricPVDEquationsWithPressure::fill_in_generic_residual_contribution_axisym_pvd_with_pressure(), oomph::PointFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::SphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), PerturbationSolution::first_order_veloc_and_pressure(), Global_Physical_Variables::fluid_inflow_boundary_traction(), Global_Physical_Variables::flux(), Global_Parameters::flux(), ExactSolution::flux_into_bulk(), foo(), oomph::Problem_Parameter::free_surface_profile(), FreeSurfaceRotationProblem< ELEMENT >::FreeSurfaceRotationProblem(), Quaternion::fromAxisAndAngle(), TanhSolnForLinearWave::get_exact_gradient(), Global_Physical_Variables::get_exact_u(), SinSolution::get_exact_u(), GlobalParameters::get_exact_u(), ExactSolnForUnsteadyHeat::get_exact_u(), TanhSolnForUnsteadyHeat::get_exact_u(), Global_parameters::get_exact_u(), RachelsAdvectionDiffusion::get_exact_u(), PlanarWave::get_exact_u(), ProblemParameters::get_exact_u(), ExactSolution::get_exact_u_for_unsteady_heat_validation(), GlobalParameters::get_simple_exact_u(), SinSolution::get_source(), TanhSolnForUnsteadyHeat::get_source(), ExactSolution::get_source_for_unsteady_heat_validation(), StokesFlowExactWind::get_wind(), Wind_Function::get_wind(), HorizontalBaseScrew::getDistanceAndNormal(), HorizontalScrew::getDistanceAndNormal(), Coil::getDistanceAndNormal(), InfiniteWallWithHole::getDistanceAndNormal(), SineWall::getDistanceAndNormal(), VChute::getDistanceAndNormal(), Screw::getDistanceAndNormalLabCoordinates(), Vec3D::getFromCylindricalCoordinates(), RNG::getNormalVariate(), vibratedBed::getPrescribedVelocity(), CylinderInsertionBoundary::getRotationMatrixX(), CylinderInsertionBoundary::getRotationMatrixY(), CylinderInsertionBoundary::getRotationMatrixZ(), oomph::Orthpoly::gl_nodes(), oomph::Orthpoly::gll_nodes(), Global_parameters::grad_f1(), Global_parameters::grad_f2(), GlobalParameters::incoming_sb_inside(), GlobalParameters::incoming_sb_outside(), oomph::SarahBL::Kin_energy_sarah(), SarahBL::Kin_energy_sarah(), PerturbationSolution::leading_order_veloc_and_pressure(), LoadFinalOrient(), LoadInitOrient(), oomph::AnnularDomain::macro_element_boundary(), main(), Eigen::internal::kiss_cpx_fft< Scalar_ >::make_twiddles(), GlobalParameters::melt_flux(), MeltContactProblem< ELEMENT >::MeltContactProblem(), ExactSolution::melting_surface_height(), WallFunction::normal(), BiharmonicTestFunctions2::normal_E(), BiharmonicTestFunctions2::normal_N(), BiharmonicTestFunctions2::normal_W(), objectivenessTest(), Eigen::QuaternionBase< Derived >::operator=(), oomph::AxisymmetricPVDEquations::output(), oomph::AxisymDiagHermitePVDElement::output(), oomph::AxisymmetricPVDEquationsWithPressure::output(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::output(), oomph::PolarNavierStokesEquations::output(), oomph::SphericalAdvectionDiffusionEquations::output(), oomph::SphericalNavierStokesEquations::output(), oomph::CircularPenetrator::output(), HeatedCircularPenetratorElement::output(), CircularPenetratorElement::output(), oomph::SolarRadiationBase::output_diffuse_radiation_cone(), oomph::SolarRadiationBase::output_diffuse_radiation_cone_max_angle(), oomph::SolarRadiationBase::output_diffuse_radiation_cone_min_angle(), oomph::PMLHelmholtzEquations< DIM >::output_imag(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output_imag(), oomph::PMLHelmholtzEquations< DIM >::output_imag_fct(), oomph::FourierDecomposedHelmholtzEquations::output_real(), oomph::HelmholtzEquations< DIM >::output_real(), oomph::PMLFourierDecomposedHelmholtzEquations::output_real(), oomph::PMLHelmholtzEquations< DIM >::output_real(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output_real(), oomph::FourierDecomposedHelmholtzEquations::output_real_fct(), oomph::HelmholtzEquations< DIM >::output_real_fct(), oomph::PMLFourierDecomposedHelmholtzEquations::output_real_fct(), oomph::PMLHelmholtzEquations< DIM >::output_real_fct(), oomph::PMLHelmholtzEquations< DIM >::output_total_real(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output_total_real(), oomph::SarahBL::P_sarah(), SarahBL::P_sarah(), packetmath_real(), BaseCluster::particleInsertionSuccessful(), particleParticleTest(), Eigen::internal::pcos(), Global_Physical_Variables::pcos_load(), Global_Parameters::periodic_traction(), PerturbationSolution::polar_to_cartesian_velocity(), Leaflet::position(), OscillatingWall::position(), FilledCircle::position(), GeneralCircle::position(), GeneralEllipse::position(), OscillatingCylinder::position(), oomph::HalfEllipse::position(), MyCurvedCylinder::position(), MyHelicalCylinder::position(), MyEllipse::position(), MyCylinder::position(), MyUnitCircle::position(), UnitCircle::position(), oomph::SimpleCircle::position(), oomph::GeneralCircle::position(), WarpedLine::position(), WarpedPlane::position(), WavyWall::position(), oomph::Ellipse::position(), oomph::Circle::position(), oomph::EllipticalTube::position(), oomph::PseudoBucklingRing::position(), oomph::CircularPenetrator::position_from_zeta(), HeatedCircularPenetratorElement::position_from_zeta(), TanhSolnForSteadyAxisymAdvectionDiffusion::prescribed_alpha_on_fixed_r_boundary(), TanhSolnForSteadyAxisymAdvectionDiffusion::prescribed_beta_on_fixed_r_boundary(), ExactSolution::prescribed_flux_for_unsteady_heat_validation(), ExactSolnForUnsteadyHeat::prescribed_flux_on_fixed_y_boundary(), GlobalParameters::prescribed_flux_on_fixed_y_boundary(), TanhSolnForUnsteadyHeat::prescribed_flux_on_fixed_y_boundary(), GlobalPhysicalParameters::prescribed_pressure_gradient(), GlobalPhysicalParameters::prescribed_volume_flux(), Global_Physical_Variables::press_load(), Global_Parameters::press_load(), Global_Parameters::pressure_singularity1(), Global_Parameters::pressure_singularity2(), oomph::RectangleWithHoleAndAnnularRegionDomain::project_point_on_cylinder_to_annular_boundary(), protectiveWall::protectiveWall(), Eigen::internal::psincos_double(), ExactSolution::rigid_body_rotation_dtheta(), RingWithTRibProblem< ELASTICITY_ELEMENT >::RingWithTRibProblem(), CircularPeriodicBoundary::rotateParticle(), ClumpParticle::rotatePrincipalDirections(), PerturbationSolution::second_order_veloc_and_pressure(), FlowAroundCylinderProblem< ELEMENT >::set_boundary_conditions(), RefineableRotatingCylinderProblem< ELEMENT >::set_boundary_conditions(), BaseStateProblem< BASE_ELEMENT >::set_boundary_conditions(), ChutePeriodic::set_chute_parameters(), Cstatic3D::set_particle_properties(), Slide::set_Walls(), Quaternion::setAngleZ(), Chute::setChuteAngleAndMagnitudeOfGravity(), CurvyChute::setChuteAngleAndMagnitudeOfGravity(), Quaternion::setEuler(), GlobalParameters::setup_dependent_parameters_and_sanity_check(), RefineableDrivenCavityProblem< ELEMENT >::setup_line_plot_points(), RectangularDrivenCavityProblem< ELEMENT >::setup_line_plot_points(), T_protectiveWall::setupInitialConditions(), NozzleDemo::setupInitialConditions(), MinimalExampleDrum::setupInitialConditions(), Cstatic3D::setupInitialConditions(), RotatingDrum::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), DrumRot::setupInitialConditions(), protectiveWall::setupInitialConditions(), DrivenParticleClass::setupInitialConditions(), GlobalParameters::sin_cos_velocity_field(), GlobalParameters::sin_cos_vorticity(), oomph::SlopingQuadMesh< ELEMENT >::SlopingQuadMesh(), FallingBlockProblem< ELEMENT >::snap_onto_sphere(), RisingBubbleProblem< ELEMENT >::snap_onto_sphere(), SolarRadiationProblem< ELEMENT >::SolarRadiationProblem(), Global_Parameters::solid_boundary_displacement(), Global_parameters::source_function(), oomph::PressureAdvectionDiffusionValidation::source_function(), TanhSolnForAdvectionDiffusion::source_function(), TanhSolnForSteadyAxisymAdvectionDiffusion::source_function(), sphericalHarmonics::sphericalHarmonics(), SphericalSpinUpProblem< ELEMENT >::SphericalSpinUpProblem(), GlobalParameters::spine_function(), oomph::AnnularSpineMesh< ELEMENT >::spine_node_update(), Eigen::internal::stem_function_cos(), Eigen::internal::stem_function_sin(), GlobalParameters::step_position(), TanhSolnForUnsteadyHeat::step_position(), BiharmonicTestFunctions2::surface_load(), T_protectiveWall::T_protectiveWall(), oomph::HeatedCircularPenetrator::temperature(), HeatedCircularPenetratorElement::temperature(), test2dRotation(), test_autodiff_hessian(), test_trigonometric_functions(), ActivatorInhibitorProblem< ELEMENT >::timestep(), Eigen::Rotation2D< Scalar_ >::toRotationMatrix(), Eigen::AngleAxis< Scalar_ >::toRotationMatrix(), oomph::SarahBL::Total_Diss_lead_sarah(), SarahBL::Total_Diss_lead_sarah(), oomph::SarahBL::Total_Diss_sarah(), SarahBL::Total_Diss_sarah(), transformations(), TwoDDGMesh< ELEMENT >::TwoDDGMesh(), Global_Parameters::u_r(), oomph::SarahBL::U_sarah(), SarahBL::U_sarah(), Global_Parameters::u_theta(), Global_Parameters::u_z(), unary_ops_test(), UniformRandomPDs(), Eigen::Quaternion< Scalar_, Options_ >::UnitRandom(), InterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run(), ElasticInterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run(), Funnel::update_funnel(), oomph::SarahBL::V_sarah(), SarahBL::V_sarah(), AxisymOscillatingDisk::veloc(), oomph::PseudoBucklingRing::veloc(), Jeffery_Solution::velocity(), OscillatingCylinder::velocity(), Global_Parameters::velocity_couette(), Global_Parameters::velocity_singularity1(), Global_Parameters::velocity_singularity2(), verify_euler(), oomph::WarpedCircularDisk::w(), WallMesh< ELEMENT >::WallMesh(), wallParticleTest(), oomph::WarpedCubeDomain::warp_it(), TanhSolnForAdvectionDiffusion::wind_function(), GlobalPhysicalParameters::wind_function(), RachelsAdvectionDiffusion::wind_function(), TanhSolnForSteadyAxisymAdvectionDiffusion::wind_function(), oomph::PressureAdvectionDiffusionValidation::wind_function(), HorizontalBaseScrew::writeVTK(), HorizontalScrew::writeVTK(), Screw::writeVTK(), ScrewsymmetricIntersectionOfWalls::writeVTK(), AxisymmetricIntersectionOfWalls::writeVTK(), oomph::SarahBL::X_sarah(), SarahBL::X_sarah(), oomph::SarahBL::Y_sarah(), and SarahBL::Y_sarah().
get_test_precision()
AnnoyingScalar get_test_precision (const AnnoyingScalar &)
 { return Eigen::test_precision<AnnoyingScalar>(); }
References Eigen::test_precision< AnnoyingScalar >().
Referenced by product().
imag()
AnnoyingScalar imag (const AnnoyingScalar &)
 { return 0; }
Referenced by array_complex(), array_real(), basicStuffComplex(), CRBond_Bessel::cbessik01(), CRBond_Bessel::cbessiknb(), CRBond_Bessel::cbessikv(), CRBond_Bessel::cbessjy01(), CRBond_Bessel::cbessjyna(), CRBond_Bessel::cbessjynb(), CRBond_Bessel::cbessjyva(), oomph::Hankel_functions_for_helmholtz_problem::CHankel_first(), check_if_equal_or_nans(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::CoatedDiskProblem(), CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::CoatedSphereProblem(), Eigen::internal::complex_rsqrt(), Eigen::internal::complex_sqrt(), Eigen::PolynomialSolver< Scalar_, Deg_ >::compute(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::compute_error(), Eigen::JacobiSVD< MatrixType_, Options_ >::compute_impl(), Eigen::MatrixPowerAtomic< MatrixType >::computeSuperDiag(), Eigen::internal::tensor_symmetry_value_setter< Tensor_, Symmetry_, Flags >::doAssign(), Eigen::EigenSolver< MatrixType_ >::doComputeEigenvectors(), Eigen::EigenSolver< MatrixType_ >::eigenvectors(), Global_Parameters::exact_axisym_potential(), Global_Parameters::exact_axisym_radiated_power(), Eigen::SparseQR< MatrixType_, OrderingType_ >::factorize(), oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals_helmholtz_traction(), oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals_helmholtz_traction(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals_helmholtz_traction(), oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals_time_harmonic_fourier_decomposed_linear_elasticity_traction(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals_time_harmonic_linear_elasticity_traction(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals_time_harmonic_linear_elasticity_traction(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::TimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::FourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz(), oomph::HelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::RefineableHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::PMLHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::RefineablePMLHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::PMLFourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz(), oomph::HelmholtzPointSourceElement< ELEMENT >::fill_in_point_source_contribution_to_residuals(), oomph::PMLHelmholtzPointSourceElement< ELEMENT >::fill_in_point_source_contribution_to_residuals(), oomph::PMLHelmholtzEquations< DIM >::get_dof_numbers_for_unknowns(), GlobalParameters::get_exact_u(), GlobalParameters::get_exact_u_bessel(), oomph::FourierDecomposedHelmholtzEquations::get_flux(), oomph::HelmholtzEquations< DIM >::get_flux(), oomph::PMLFourierDecomposedHelmholtzEquations::get_flux(), oomph::PMLHelmholtzEquations< DIM >::get_flux(), oomph::RefineableHelmholtzEquations< DIM >::get_interpolated_values(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::get_strain(), oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::get_strain(), oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::get_strain(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::HelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::global_power_contribution(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_power_contribution(), householder(), Eigen::internal::isfinite_impl(), Eigen::internal::isinf_impl(), Eigen::internal::isnan_impl(), Eigen::internal::loadQuadToDoublePacket(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadRhs(), oomph::DenseComplexMatrix::ludecompose(), Eigen::MatrixBase< Derived >::makeHouseholder(), Eigen::internal::matrix_log_compute_2x2(), Eigen::internal::squared_norm_functor< Scalar, IsComplex >::operator()(), Eigen::internal::scalar_imag_op< Scalar >::operator()(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output(), oomph::TimeHarmonicLinearElasticityEquations< DIM >::output(), Eigen::internal::Packet1cd::Packet1cd(), Eigen::internal::Packet2cf::Packet2cf(), packetmath_complex(), Eigen::internal::pcplxflip(), Eigen::internal::pgather< std::complex< double >, Packet1cd >(), Eigen::internal::pgather< std::complex< double >, Packet2cd >(), Eigen::internal::pgather< std::complex< float >, Packet1cf >(), Eigen::internal::pgather< std::complex< float >, Packet4cf >(), Eigen::internal::pset1< Packet4cf >(), Eigen::internal::pset1< Packet8cf >(), Eigen::EigenSolver< MatrixType_ >::pseudoEigenvalueMatrix(), Eigen::internal::squared_norm_impl< Derived, Scalar >::run(), Eigen::internal::gemv_dense_selector< OnTheRight, ColMajor, true >::run(), Eigen::internal::trmv_selector< Mode, ColMajor >::run(), Eigen::internal::imag_default_impl< Scalar, true >::run(), Eigen::internal::ScalarPrinter< Scalar, TensorIOFormatNative, std::enable_if_t< NumTraits< Scalar >::IsComplex > >::run(), Eigen::internal::ScalarPrinter< Scalar, TensorIOFormatNumpy, std::enable_if_t< NumTraits< Scalar >::IsComplex > >::run(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, Options, true >::run(), Eigen::internal::bitwise_binary_impl< Scalar, true >::run_and(), Eigen::internal::bitwise_unary_impl< Scalar, true >::run_not(), Eigen::internal::bitwise_binary_impl< Scalar, true >::run_or(), Eigen::internal::bitwise_binary_impl< Scalar, true >::run_xor(), PredPreyProblem< ELEMENT >::solve(), ABCProblem< ELEMENT, TIMESTEPPERT >::solve(), test_fft_complex_input_golden(), test_fft_real_input_golden(), oomph::ComplexGMRES< MATRIX >::update(), oomph::HelmholtzGMRESMG< MATRIX >::update(), and oomph::HelmholtzFGMRESMG< MATRIX >::update().
operator<<()
std::ostream& operator<< (std::ostream & stream, const AnnoyingScalar & x)
{
   stream << (*(x.v));
   return stream;
 }
References plotDoE::x.
real()
AnnoyingScalar real (const AnnoyingScalar & x)
 { return x; }
References plotDoE::x.
sin()
AnnoyingScalar sin (const AnnoyingScalar & x)
 { return std::sin(*x.v); }
References plotDoE::x.
Referenced by AxisymOscillatingDisk::accel(), oomph::PseudoBucklingRing::accel(), Jeffery_Solution::acceleration(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_before_implicit_timestep(), InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::actions_before_implicit_timestep(), RayleighProblem< ELEMENT, TIMESTEPPER >::actions_before_implicit_timestep(), RefineableConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_newton_solve(), QuarterCircleDrivenCavityProblem2< ELEMENT >::actions_before_newton_solve(), QuarterCircleDrivenCavityProblem< ELEMENT >::actions_before_newton_solve(), TiltedCavityProblem< ELEMENT >::actions_before_newton_solve(), PolarNSProblem< ELEMENT >::actions_before_solve(), ChangingTOIParticle::actionsAfterTimeStep(), oomph::SphericalNavierStokesEquations::actual(), oomph::SphericalNavierStokesEquations::actual_dr(), oomph::SphericalNavierStokesEquations::actual_dth(), VerticalMixerAngledBlades::addBlades(), VerticalMixerAngledBlades::addPrettyBlades(), ChuteWithWedge::addWedge(), alignedboxNonIntegralRotatable(), Global_Parameters::analytic_solution1(), Global_Parameters::analytic_solution2(), ExactSolution::analytical_outer_unit_normal(), angleToVec(), AnnularQuadMesh< ELEMENT >::AnnularQuadMesh(), oomph::AnnularSpineMesh< ELEMENT >::AnnularSpineMesh(), oomph::ImmersedRigidBodyElement::apply_rigid_body_motion(), array_complex(), array_real(), ProblemParameters::atmospheric_radiation(), CRBond_Bessel::bessikv(), CRBond_Bessel::bessjy01a(), CRBond_Bessel::bessjy01b(), CRBond_Bessel::bessjynb(), CRBond_Bessel::bessjyv(), Global_Parameters::body_force(), BiharmonicTestFunctions2::boundary_E(), BiharmonicTestFunctions2::boundary_N(), Global_Parameters::boundary_traction(), oomph::WarpedCircularDisk::boundary_triad(), Boundary_Items::boundary_velocity(), BiharmonicTestFunctions2::boundary_W(), oomph::ComplexDampedJacobi< MATRIX >::calculate_omega(), TorqueCalculationElement< ELEMENT >::calculate_torque(), CRBond_Bessel::cbessikv(), CRBond_Bessel::cbessjy01(), CRBond_Bessel::cbessjynb(), CRBond_Bessel::cbessjyva(), HeatedCircularPenetratorElement::centre(), CircularPenetratorElement::centre(), check_atan2(), check_locate_zeta(), exp_complex_test_impl< Scalar, Packet, HasExp >::cis(), ContactProblem< ELEMENT >::complete_problem_setup(), oomph::SphericalNavierStokesEquations::compute_error_e(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::compute_gamma_contribution(), oomph::AxisymmetricPVDEquations::compute_physical_size(), oomph::AxisymmetricPVDEquationsWithPressure::compute_physical_size(), LiquidBridgeBagheriInteraction::computeAdhesionForce(), BaseCluster::computeInternalStructure(), SinterLinInteraction::computeNormalForce(), computeRoots(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::computeRoots(), Funnel::create_funnel(), SegregationWithHopper::create_inflow_particle(), Funnel::create_inflow_particle(), LevelSetWall::createVTKSphere(), SinusoidalWall::d2position(), oomph::Ellipse::d2position(), oomph::EllipticalTube::d2position(), Global_Parameters::d_u_r_dt(), Global_Parameters::d_u_theta_dt(), Global_Parameters::d_u_z_dt(), oomph::deriv_functions::dcos(), oomph::deriv_functions::DampedOscillation::derivative(), oomph::deriv_functions::OrderReductionTest::derivative(), oomph::DiskWithTorusAroundEdgeTetMeshFacetedSurface::DiskWithTorusAroundEdgeTetMeshFacetedSurface(), oomph::SarahBL::Diss_sarah(), SarahBL::Diss_sarah(), oomph::SolidHelpers::doc_2D_principal_stress(), StefanBoltzmannProblem< ELEMENT >::doc_solution(), oomph::Ellipse::dposition(), oomph::ImmersedRigidBodyElement::dposition_dt(), BiharmonicTestFunctions2::dudn_S(), BiharmonicTestFunctions2::dudx_0(), BiharmonicTestFunctions2::dudx_1(), oomph::WarpedCircularDisk::dwdphi(), EIGEN_DECLARE_TEST(), ElasticRingProblem< ELEMENT >::ElasticRingProblem(), TanhSolnForLinearWave::exact_d2udt2(), TanhSolnForLinearWave::exact_dudt(), Global::exact_solution(), Global_Parameters::exact_solution(), Global_Parameters::exact_solution_th(), TanhSolnForLinearWave::exact_u(), oomph::SphericalNavierStokesEquations::extract_velocity(), TwoNodePoissonElement::f(), Global_parameters::f1_exact(), oomph::AxisymmetricSolidTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::AxisymmetricPVDEquations::fill_in_contribution_to_residuals_axisym_pvd(), oomph::AxisymmetricPVDEquationsWithPressure::fill_in_generic_residual_contribution_axisym_pvd_with_pressure(), oomph::PointFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::SphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_spherical_adv_diff_flux(), oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::SphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), PerturbationSolution::first_order_veloc_and_pressure(), ProblemParameters::flux(), ExactSolution::flux_into_bulk(), foo(), FreeSurfaceRotationProblem< ELEMENT >::FreeSurfaceRotationProblem(), Quaternion::fromAxisAndAngle(), CRBond_Bessel::gamma(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::geometric_jacobian(), oomph::RefineableSphericalAdvectionDiffusionEquations::geometric_jacobian(), oomph::RefineableSphericalNavierStokesEquations::geometric_jacobian(), TanhSolnForLinearWave::get_exact_gradient(), Global_Physical_Variables::get_exact_u(), SinSolution::get_exact_u(), ExactSolnForUnsteadyHeat::get_exact_u(), Global_parameters::get_exact_u(), RachelsAdvectionDiffusion::get_exact_u(), FishSolnOneDPoisson::get_exact_u(), GlobalParameters::get_exact_u(), Boundary_Items::get_exact_u_b1(), oomph::SphericalNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), GlobalParameters::get_simple_exact_u(), SinSolution::get_source(), TanhSolnForUnsteadyHeat::get_source(), ExactSolution::get_source_for_unsteady_heat_validation(), StokesFlowExactWind::get_wind(), Wind_Function::get_wind(), HorizontalBaseScrew::getDistanceAndNormal(), HorizontalScrew::getDistanceAndNormal(), Coil::getDistanceAndNormal(), InfiniteWallWithHole::getDistanceAndNormal(), SineWall::getDistanceAndNormal(), VChute::getDistanceAndNormal(), Screw::getDistanceAndNormalLabCoordinates(), Vec3D::getFromCylindricalCoordinates(), RNG::getNormalVariate(), CylinderInsertionBoundary::getRotationMatrixX(), CylinderInsertionBoundary::getRotationMatrixY(), CylinderInsertionBoundary::getRotationMatrixZ(), Global_Parameters::grad_blend(), Global_parameters::grad_f1(), Global_parameters::grad_f2(), Global_Physical_Variables::height(), GlobalParameters::incoming_sb_inside(), GlobalParameters::incoming_sb_outside(), Global::initial_condition(), oomph::SarahBL::Kin_energy_sarah(), SarahBL::Kin_energy_sarah(), PerturbationSolution::leading_order_veloc_and_pressure(), LoadFinalOrient(), LoadInitOrient(), Flag_definition::lower_tip(), oomph::AnnularDomain::macro_element_boundary(), main(), Eigen::internal::kiss_cpx_fft< Scalar_ >::make_twiddles(), Trackball::mapToSphere(), MeltContactProblem< ELEMENT >::MeltContactProblem(), WallFunction::normal(), BiharmonicTestFunctions2::normal_E(), BiharmonicTestFunctions2::normal_N(), BiharmonicTestFunctions2::normal_W(), objectivenessTest(), oomph::deriv_functions::DampedOscillation::operator()(), oomph::deriv_functions::OrderReductionTest::operator()(), Eigen::QuaternionBase< Derived >::operator=(), oomph::Problem_Parameter::oscillation(), oomph::AxisymmetricPVDEquations::output(), oomph::AxisymDiagHermitePVDElement::output(), oomph::AxisymmetricPVDEquationsWithPressure::output(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::output(), oomph::PolarNavierStokesEquations::output(), oomph::SphericalAdvectionDiffusionEquations::output(), oomph::SphericalNavierStokesEquations::output(), oomph::CircularPenetrator::output(), HeatedCircularPenetratorElement::output(), CircularPenetratorElement::output(), oomph::SolarRadiationBase::output_diffuse_radiation_cone(), oomph::SolarRadiationBase::output_diffuse_radiation_cone_max_angle(), oomph::SolarRadiationBase::output_diffuse_radiation_cone_min_angle(), oomph::PMLHelmholtzEquations< DIM >::output_imag(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output_imag(), oomph::PMLHelmholtzEquations< DIM >::output_imag_fct(), oomph::FourierDecomposedHelmholtzEquations::output_real(), oomph::HelmholtzEquations< DIM >::output_real(), oomph::PMLFourierDecomposedHelmholtzEquations::output_real(), oomph::PMLHelmholtzEquations< DIM >::output_real(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output_real(), oomph::FourierDecomposedHelmholtzEquations::output_real_fct(), oomph::HelmholtzEquations< DIM >::output_real_fct(), oomph::PMLFourierDecomposedHelmholtzEquations::output_real_fct(), oomph::PMLHelmholtzEquations< DIM >::output_real_fct(), oomph::PMLHelmholtzEquations< DIM >::output_total_real(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output_total_real(), oomph::SarahBL::P_sarah(), SarahBL::P_sarah(), packetmath_real(), ElasticBeamProblem::parameter_study(), BaseCluster::particleInsertionSuccessful(), Global_Parameters::periodic_traction(), PerturbationSolution::polar_to_cartesian_velocity(), Leaflet::position(), Flag_definition::TopOfFlag::position(), Flag_definition::BottomOfFlag::position(), OscillatingWall::position(), FilledCircle::position(), GeneralCircle::position(), GeneralEllipse::position(), OscillatingCylinder::position(), oomph::HalfEllipse::position(), MyCurvedCylinder::position(), MyHelicalCylinder::position(), MyEllipse::position(), MyCylinder::position(), MyUnitCircle::position(), UnitCircle::position(), AxisymOscillatingDisk::position(), WarpedLine::position(), oomph::SimpleCircle::position(), oomph::GeneralCircle::position(), SinusoidalWall::position(), oomph::Ellipse::position(), oomph::Circle::position(), oomph::EllipticalTube::position(), oomph::PseudoBucklingRing::position(), oomph::CircularPenetrator::position_from_zeta(), HeatedCircularPenetratorElement::position_from_zeta(), ExactSolution::prescribed_flux_for_unsteady_heat_validation(), ExactSolnForUnsteadyHeat::prescribed_flux_on_fixed_y_boundary(), Global_Parameters::pressure_singularity1(), Global_Parameters::pressure_singularity2(), oomph::RectangleWithHoleAndAnnularRegionDomain::project_point_on_cylinder_to_annular_boundary(), protectiveWall::protectiveWall(), Eigen::internal::psin(), Eigen::internal::psincos_double(), WarpedLine::radius(), GlobalParameters::radius(), ExactSolution::rigid_body_rotation(), ExactSolution::rigid_body_rotation_dr(), ExactSolution::rigid_body_rotation_dtheta(), RingWithTRibProblem< ELASTICITY_ELEMENT >::RingWithTRibProblem(), CircularPeriodicBoundary::rotateParticle(), ClumpParticle::rotatePrincipalDirections(), run_navier_stokes_outflow(), ScaleCoupledBeam::ScaleCoupledBeam(), PerturbationSolution::second_order_veloc_and_pressure(), FlowAroundCylinderProblem< ELEMENT >::set_boundary_conditions(), RefineableRotatingCylinderProblem< ELEMENT >::set_boundary_conditions(), RefineableSphericalCouetteProblem< ELEMENT >::set_boundary_conditions(), ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::set_boundary_conditions(), DDConvectionProblem< NST_ELEMENT, AD_ELEMENT >::set_boundary_conditions(), RefineableDDConvectionProblem< NST_ELEMENT, AD_ELEMENT >::set_boundary_conditions(), RefineableSphereConvectionProblem< ELEMENT >::set_boundary_conditions(), ChutePeriodic::set_chute_parameters(), Cstatic3D::set_particle_properties(), oomph::MGSolver< DIM >::set_self_test_vector(), Slide::set_Walls(), Quaternion::setAngleZ(), Chute::setChuteAngleAndMagnitudeOfGravity(), CurvyChute::setChuteAngleAndMagnitudeOfGravity(), Quaternion::setEuler(), RefineableDrivenCavityProblem< ELEMENT >::setup_line_plot_points(), RectangularDrivenCavityProblem< ELEMENT >::setup_line_plot_points(), T_protectiveWall::setupInitialConditions(), NozzleDemo::setupInitialConditions(), Binary::setupInitialConditions(), my_problem::setupInitialConditions(), MinimalExampleDrum::setupInitialConditions(), Cstatic3D::setupInitialConditions(), RotatingDrum::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), DrumRot::setupInitialConditions(), protectiveWall::setupInitialConditions(), DrivenParticleClass::setupInitialConditions(), ExtremeOverlapWithWallsUnitTest::setupInitialConditions(), oomph::deriv_functions::sin(), Eigen::numext::sin(), GlobalParameters::sin_cos_velocity_field(), GlobalParameters::sin_cos_vorticity(), sin_over_x(), Eigen::QuaternionBase< Derived >::slerp(), slerp_gael(), slerp_legacy(), slerp_legacy_nlerp(), oomph::SlopingQuadMesh< ELEMENT >::SlopingQuadMesh(), FallingBlockProblem< ELEMENT >::snap_onto_sphere(), RisingBubbleProblem< ELEMENT >::snap_onto_sphere(), SolarRadiationProblem< ELEMENT >::SolarRadiationProblem(), BiharmonicTestFunctions2::solution(), InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::solve_steady(), Global_parameters::source_function(), FishSolnOneDPoisson::source_function(), oomph::PressureAdvectionDiffusionValidation::source_function(), TanhSolnForAdvectionDiffusion::source_function(), TanhSolnForSteadyAxisymAdvectionDiffusion::source_function(), SphericalSpinUpProblem< ELEMENT >::SphericalSpinUpProblem(), SphericalSteadyRotationProblem< ELEMENT >::SphericalSteadyRotationProblem(), GlobalParameters::spine_function(), oomph::AnnularSpineMesh< ELEMENT >::spine_node_update(), Eigen::internal::stem_function_cos(), Eigen::internal::stem_function_sin(), BiharmonicTestFunctions2::surface_load(), T_protectiveWall::T_protectiveWall(), test2dRotation(), test_autodiff_hessian(), test_trigonometric_functions(), ActivatorInhibitorProblem< ELEMENT >::timestep(), Eigen::Rotation2D< Scalar_ >::toRotationMatrix(), Eigen::AngleAxis< Scalar_ >::toRotationMatrix(), oomph::SarahBL::Total_Diss_lead_sarah(), SarahBL::Total_Diss_lead_sarah(), oomph::SarahBL::Total_Diss_sarah(), SarahBL::Total_Diss_sarah(), TwoDDGMesh< ELEMENT >::TwoDDGMesh(), BiharmonicTestFunctions2::u_E(), BiharmonicTestFunctions2::u_N(), oomph::SarahBL::U_sarah(), SarahBL::U_sarah(), BiharmonicTestFunctions2::u_W(), unary_ops_test(), UniformRandomPDs(), Eigen::Quaternion< Scalar_, Options_ >::UnitRandom(), Funnel::update_funnel(), Flag_definition::upper_tip(), oomph::SarahBL::V_sarah(), SarahBL::V_sarah(), oomph::PseudoBucklingRing::veloc(), Jeffery_Solution::velocity(), Global_Parameters::velocity_couette(), Global_Parameters::velocity_singularity1(), Global_Parameters::velocity_singularity2(), verify_euler(), WallMesh< ELEMENT >::WallMesh(), oomph::WarpedCubeDomain::warp_it(), Wind_fct_pt(), TanhSolnForAdvectionDiffusion::wind_function(), GlobalPhysicalParameters::wind_function(), RachelsAdvectionDiffusion::wind_function(), TanhSolnForSteadyAxisymAdvectionDiffusion::wind_function(), oomph::PressureAdvectionDiffusionValidation::wind_function(), HorizontalBaseScrew::writeVTK(), HorizontalScrew::writeVTK(), Screw::writeVTK(), ScrewsymmetricIntersectionOfWalls::writeVTK(), AxisymmetricIntersectionOfWalls::writeVTK(), oomph::SarahBL::X_sarah(), SarahBL::X_sarah(), oomph::SarahBL::Y_sarah(), and SarahBL::Y_sarah().
sqrt()
AnnoyingScalar sqrt (const AnnoyingScalar & x)
 { return std::sqrt(*x.v); }
References plotDoE::x.
Referenced by __attribute__(), AxisymOscillatingDisk::accel(), ContactProblem< ELEMENT >::actions_before_adapt(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_before_implicit_timestep(), EntryFlowProblem< ELEMENT >::actions_before_newton_solve(), SteadyCurvedTubeProblem< ELEMENT >::actions_before_newton_solve(), SteadyHelicalProblem< ELEMENT >::actions_before_newton_solve(), SteadyTubeProblem< ELEMENT >::actions_before_newton_solve(), Vreman::actionsAfterTimeStep(), SphericalIndenter::actionsAfterTimeStep(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::actual_cos_contact_angle(), STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::add_mesh(), Vreman::add_particles(), ChuteWithHopper::addHopper(), alignedboxNonIntegralRotatable(), MeltableNormalSpecies::analyseTimeScales(), Global_Parameters::analytic_solution1(), Global_Parameters::analytic_solution2(), ExactSolution::analytical_outer_unit_normal(), oomph::VectorHelpers::angle(), AngledPeriodicBoundarySecondUnitTest::AngledPeriodicBoundarySecondUnitTest(), AngledPeriodicBoundaryUnitTest::AngledPeriodicBoundaryUnitTest(), NavierStokesProblem< ELEMENT >::apply_boundary_conditions(), oomph::ImmersedRigidBodyElement::apply_rigid_body_motion(), Membrane::Edge::applyStretchForce(), array_complex(), array_real(), array_special_functions(), oomph::TetMeshBase::assess_mesh_quality(), oomph::ImmersedRigidBodyTriangleMeshPolygon::assign_zeta(), sphericalHarmonics::associatedLegendrePolynomials(), Global_Physical_Variables::axial_pressure_gradient(), AxiPoroProblem< ELEMENT, TIMESTEPPER >::AxiPoroProblem(), Global_Parameters::axisym_coefficient(), Eigen::internal::companion< Scalar_, Deg_ >::balancedR(), Beam::Beam(), CRBond_Bessel::bessik01a(), CRBond_Bessel::bessik01b(), CRBond_Bessel::bessiknb(), CRBond_Bessel::bessikv(), CRBond_Bessel::bessjy01a(), CRBond_Bessel::bessjy01b(), CRBond_Bessel::bessjynb(), CRBond_Bessel::bessjyv(), Eigen::internal::bicgstab(), oomph::BlackBoxFDNewtonSolver::black_box_fd_newton_solve(), Global_Parameters::blend(), Eigen::internal::blueNorm_impl(), Global_Parameters::body_force(), oomph::WarpedCircularDisk::boundary_triad(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::build_mesh(), oomph::BrickFromTetMesh< ELEMENT >::build_mesh(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), Eigen::EulerSystem< _AlphaAxis, _BetaAxis, _GammaAxis >::CalcEulerAngles_imp(), CFDDEMCoupleTest::CalcPhiPAndFz(), oomph::Problem::calculate_continuation_derivatives_fd_helper(), oomph::Problem::calculate_continuation_derivatives_helper(), oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::calculate_cut_off_viscosity(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_cutoff_viscosity(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_cutoff_viscosity(), oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_cutoff_viscosity(), AxisymmetricVibratingShellProblem< ELEMENT >::calculate_error_of_fixed_point_iteration(), VibratingShellProblem< ELEMENT >::calculate_error_of_fixed_point_iteration(), oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_fitting_parameters_of_cubic(), CRBond_Bessel::cbessik01(), CRBond_Bessel::cbessiknb(), CRBond_Bessel::cbessikv(), CRBond_Bessel::cbessjy01(), CRBond_Bessel::cbessjynb(), CRBond_Bessel::cbessjyva(), check_accuracy(), oomph::Mesh::check_for_repeated_nodes(), check_locate_zeta(), VorticityRecoveryProblem< ELEMENT >::check_smoothed_vorticity(), CircularPeriodicBoundary::checkBoundaryAfterParticleMoved(), HeaterBoundary::checkBoundaryAfterParticleMoved(), Eigen::internal::chkder(), cholesky(), oomph::ComplexDampedJacobi< MATRIX >::complex_solve_helper(), oomph::ComplexGMRES< MATRIX >::complex_solve_helper(), Eigen::EigenSolver< MatrixType_ >::compute(), Eigen::GeneralizedEigenSolver< MatrixType_ >::compute(), Eigen::IterScaling< MatrixType_ >::compute(), oomph::RefineableTriangleMesh< ELEMENT >::compute_area_target(), oomph::AxisymmetricPVDEquations::compute_physical_size(), oomph::AxisymmetricPVDEquationsWithPressure::compute_physical_size(), oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::compute_stabilisation_parameter(), oomph::LineDerivatives::compute_surface_derivatives(), oomph::AxisymmetricDerivatives::compute_surface_derivatives(), oomph::SurfaceDerivatives::compute_surface_derivatives(), oomph::RefineableTetgenMesh< ELEMENT >::compute_volume_target(), oomph::RefineableTetMeshBase::compute_volume_target(), LiquidBridgeClassicalWilletInteraction::computeAdhesionForce(), LiquidBridgeWilletInteraction::computeAdhesionForce(), LiquidMigrationWilletInteraction::computeAdhesionForce(), helpers::computeDisptFromCollisionTimeAndRestitutionCoefficientAndTangentialRestitutionCoefficientAndEffectiveMass(), CFDDEMCoupleTest::computeExternalForces(), computeFFc(), FrictionInteraction::computeFrictionForce(), MindlinInteraction::computeFrictionForce(), MindlinRollingTorsionInteraction::computeFrictionForce(), SlidingFrictionInteraction::computeFrictionForce(), ChuteWithPeriodicInflow::computeInternalForces(), Dipole::computeMultipoleExpansion(), HertzianBSHPViscoelasticInteraction::computeNormalForce(), HertzianViscoelasticInteraction::computeNormalForce(), MeltableInteraction::computeNormalForce(), SinterInteraction::computeNormalForce(), ScrewsymmetricIntersectionOfWalls::computeNormalRadialDeltaN(), computeRoots(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::computeRoots(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::computeRoots(), Eigen::ComplexSchur< MatrixType_ >::computeShift(), Eigen::RealSchur< MatrixType_ >::computeShift(), computeSimpleFFc(), Eigen::BDCSVD< MatrixType_, Options_ >::computeSingVals(), HertzianSinterInteraction::computeSinterForce(), sphericalHarmonics::computeSquaredFactorialValues(), HertzianSinterNormalSpecies::computeTimeStep(), LinearPlasticViscoelasticNormalSpecies::computeTimeStep(), LinearViscoelasticNormalSpecies::computeTimeStep(), SinterLinNormalSpecies::computeTimeStep(), SinterNormalSpecies::computeTimeStep(), WearableNurbsWall::computeWear(), WearableTriangleMeshWall::computeWear(), WearableTriangulatedWall::computeWear(), oomph::TriangleMeshCurveSection::connect_final_vertex_to_curviline(), oomph::TriangleMeshCurveSection::connect_final_vertex_to_polyline(), oomph::TriangleMeshCurveSection::connect_initial_vertex_to_curviline(), oomph::TriangleMeshCurveSection::connect_initial_vertex_to_polyline(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::contact_line_vectors(), oomph::FaceElement::continuous_tangent_and_outer_unit_normal(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_enclosed_volume(), oomph::LineVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::StefanBoltzmannRadiationBase::contribution_to_stefan_boltzmann_radiation(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::contribution_to_total_porous_flux(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_total_porous_flux(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_volume_flux(), AxisymmetricIntersectionOfWalls::convertLimits(), HorizontalBaseScrew::convertLimits(), ScrewsymmetricIntersectionOfWalls::convertLimits(), PSD::convertPdfPhiToPdfMeter(), create_fluid_and_solid_surface_mesh_from_fluid_xda_mesh(), SegregationWithHopper::create_inflow_particle(), AngleOfRepose::create_inflow_particle(), Slide::create_rough_wall(), Chute::createBottom(), CircularPeriodicBoundary::createPeriodicParticle(), DarcyProblem< ELEMENT >::DarcyProblem(), Eigen::BDCSVD< MatrixType_, Options_ >::deflation(), Eigen::BDCSVD< MatrixType_, Options_ >::deflation43(), Eigen::BDCSVD< MatrixType_, Options_ >::deflation44(), MeltSpinningProblem< ELEMENT >::deform_free_surface(), AxisymFreeSurfaceNozzleAdvDiffRobinProblem< ELEMENT >::deform_free_surface(), Matrix3D::deviator(), Eigen::NumericalDiff< Functor_, mode >::df(), dif_rmse(), oomph::DiskTetMeshFacetedSurface::DiskTetMeshFacetedSurface(), oomph::DiskWithTorusAroundEdgeTetMeshFacetedSurface::DiskWithTorusAroundEdgeTetMeshFacetedSurface(), oomph::SarahBL::Diss_sarah(), SarahBL::Diss_sarah(), Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::distance(), tetgenmesh::distance(), divacNorm(), Eigen::BDCSVD< MatrixType_, Options_ >::divide(), oomph::OcTree::doc_face_neighbours(), oomph::BinaryTree::doc_neighbours(), oomph::QuadTree::doc_neighbours(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_parameters(), RefineableAdvectionDiffusionProblem< ELEMENT >::doc_solution(), UnstructuredFvKProblem< ELEMENT >::doc_solution(), ExtrudedMovingCylinderProblem< TWO_D_ELEMENT, THREE_D_ELEMENT >::doc_solution(), ContactProblem< ELEMENT >::doc_solution(), StefanBoltzmannProblem< ELEMENT >::doc_solution(), DiskShockWaveProblem< ELEMENT, TIMESTEPPER >::doc_solution(), UnsteadyHeatProblem< ELEMENT >::doc_solution(), UnstructuredImmersedEllipseProblem< ELEMENT >::doc_solution(), AxisymmetricVibratingShellProblem< ELEMENT >::doc_solution(), VibratingShellProblem< ELEMENT >::doc_solution(), UnstructuredPoissonProblem< ELEMENT >::doc_solution(), BubbleInChannelProblem< ELEMENT >::doc_solution(), DropInChannelProblem< ELEMENT >::doc_solution(), UnstructuredFluidProblem< ELEMENT >::doc_solution(), AxiPoroProblem< ELEMENT, TIMESTEPPER >::doc_solution(), DarcyProblem< ELEMENT >::doc_solution(), OneDPoissonProblem< ELEMENT >::doc_solution(), TetmeshPoissonProblem< ELEMENT >::doc_solution(), TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::doc_solution(), AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::doc_solution(), ElasticRingProblem< ELEMENT >::doc_solution(), FourierDecomposedHelmholtzProblem< ELEMENT >::doc_solution(), ScatteringProblem< ELEMENT >::doc_solution(), PeriodicLoadProblem< ELEMENT >::doc_solution(), RefineablePeriodicLoadProblem< ELEMENT >::doc_solution(), PoissonProblem< ELEMENT >::doc_solution(), MultiPoissonProblem< ELEMENT >::doc_solution(), FlowPastBoxProblem< ELEMENT >::doc_solution(), RefineableTwoDPoissonProblem< ELEMENT >::doc_solution(), RefineableTwoMeshFluxPoissonProblem< ELEMENT >::doc_solution(), FluxPoissonMGProblem< ELEMENT, MESH >::doc_solution(), UnitCubePoissonMGProblem< ELEMENT, MESH >::doc_solution(), ThreeDimBethertonProblem< ELEMENT >::doc_solution(), RefineablePoissonProblem< ELEMENT >::doc_solution(), PMLFourierDecomposedHelmholtzProblem< ELEMENT >::doc_solution(), ElasticAnnulusProblem< ELASTICITY_ELEMENT >::doc_solution(), EighthSpherePoissonProblem< ELEMENT >::doc_solution(), RefineableOneDPoissonProblem< ELEMENT >::doc_solution(), PRefineableOneDPoissonProblem< ELEMENT >::doc_solution(), TwoMeshFluxPoissonProblem< ELEMENT >::doc_solution(), StaticDiskCompressionProblem< ELEMENT >::doc_solution(), DiskOscillationProblem< ELEMENT >::doc_solution(), TwoMeshFluxSteadyAxisymAdvectionDiffusionProblem< ELEMENT >::doc_solution(), FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::doc_solution(), oomph::BiharmonicProblem< DIM >::doc_solution(), oomph::BiharmonicFluidProblem< DIM >::doc_solution(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::doc_solution(), oomph::OcTree::doc_true_edge_neighbours(), Eigen::internal::dogleg(), oomph::ImmersedRigidBodyElement::dposition_dt(), RenderingWidget::drawScene(), oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant(), EIGEN_DECLARE_TEST(), Eigen::numext::EIGEN_MATHFUNC_RETVAL(), UnsteadyHeatProblem< ELEMENT >::enforce_time_periodic_boundary_conditions(), EntryFlowProblem< ELEMENT >::EntryFlowProblem(), evalSolverSugarFunction(), Global_Parameters::exact_axisym_potential(), Global_Parameters::exact_axisym_radiated_power(), ProblemParameters::exact_minus_dudr(), MeshDeformation::exact_normal(), oomph::SarahBL::exact_soln(), SarahBL::exact_soln(), Global::exact_solution(), Global_Parameters::exact_u(), Eigen::AlignedBox< Scalar_, AmbientDim_ >::exteriorDistance(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::extract_kernel(), TwoNodePoissonElement::f(), Global_parameters::f1_exact(), Global_parameters::f2_exact(), SingleElement::face_normal(), Eigen::SparseQR< MatrixType_, OrderingType_ >::factorize(), Eigen::IncompleteLUT< Scalar_, StorageIndex_ >::factorize(), Eigen::IncompleteCholesky< Scalar, UpLo_, OrderingType_ >::factorize(), Eigen::SimplicialCholeskyBase< Derived >::factorize_preordered(), Eigen::internal::fdjac1(), fft_rmse(), oomph::AxisymmetricSolidTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::YoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::FSIAxisymmetricLinearElasticityTractionElement< ELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::fill_in_contribution_to_residuals_axisym_fsi_traction(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals_axisym_poroelasticity_face(), oomph::AxisymmetricPVDEquations::fill_in_contribution_to_residuals_axisym_pvd(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals_axisymmetric_linear_elasticity_traction(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_residuals_axisymmetric_nst_traction(), oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_residuals_beam(), oomph::DarcyFaceElement< ELEMENT >::fill_in_contribution_to_residuals_darcy_face(), oomph::PoroelasticityFaceElement< ELEMENT >::fill_in_contribution_to_residuals_darcy_face(), oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals_helmholtz_traction(), oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals_helmholtz_traction(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals_helmholtz_traction(), oomph::LinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals_linear_elasticity_traction(), oomph::KirchhoffLoveShellEquations::fill_in_contribution_to_residuals_shell(), oomph::SolidTractionElement< ELEMENT >::fill_in_contribution_to_residuals_solid_traction(), oomph::NonlinearSurfaceContactElement< ELEMENT >::fill_in_contribution_to_residuals_surface_contact(), oomph::LinearSurfaceContactElement< ELEMENT >::fill_in_contribution_to_residuals_surface_contact(), oomph::HeatedLinearSurfaceContactElement< ELEMENT >::fill_in_contribution_to_residuals_surface_contact(), oomph::SurfaceMeltElement< ELEMENT >::fill_in_contribution_to_residuals_surface_melt(), oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals_time_harmonic_fourier_decomposed_linear_elasticity_traction(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals_time_harmonic_linear_elasticity_traction(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals_time_harmonic_linear_elasticity_traction(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::fill_in_generic_residual_contribution_axisym_poroelastic_fsi(), oomph::AxisymmetricPVDEquationsWithPressure::fill_in_generic_residual_contribution_axisym_pvd_with_pressure(), oomph::BiharmonicFluidBoundaryElement::fill_in_generic_residual_contribution_biharmonic_boundary(), oomph::BiharmonicFluxElement< DIM >::fill_in_generic_residual_contribution_biharmonic_flux(), oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_abc(), oomph::PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement< ELEMENT >::fill_in_generic_residual_contribution_interface(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LineVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::AxisymmetricVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::find_distance_to_free_surface(), statistics_while_running< T >::finishStatistics(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::Flux_interpolation_point(), oomph::TRaviartThomasDarcyElement< ORDER >::Flux_interpolation_point(), oomph::FoldHandler::FoldHandler(), foo(), FreeSurfaceRotationProblem< ELEMENT >::FreeSurfaceRotationProblem(), oomph::SarahBL::full_exact_soln(), SarahBL::full_exact_soln(), oomph::BermudezPMLMappingAndTransformedCoordinate::gamma(), GlobalParameters::TestPMLMapping::gamma(), oomph::BermudezPMLMapping::gamma(), oomph::ContinuousBermudezPMLMapping::gamma(), oomph::TPoroelasticityElement< ORDER >::Gauss_point(), oomph::GMRES< MATRIX >::generate_plane_rotation(), oomph::AugmentedProblemGMRES::generate_plane_rotation(), oomph::GMRESBlockPreconditioner::generate_plane_rotation(), oomph::ComplexGMRES< MATRIX >::generate_plane_rotation(), oomph::HelmholtzGMRESMG< MATRIX >::generate_plane_rotation(), oomph::FiniteElement::get_centre_of_gravity_and_max_radius_in_terms_of_zeta(), oomph::UnstructuredTwoDMeshGeometryBase::get_connected_vertex_number_on_destination_polyline(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::get_div_q_basis_local(), oomph::TRaviartThomasDarcyElement< ORDER >::get_div_q_basis_local(), oomph::TPoroelasticityElement< ORDER >::get_div_q_basis_local(), oomph::Z2ErrorEstimator::get_element_errors(), oomph::KirchhoffLoveShellEquations::get_energy(), oomph::KirchhoffLoveBeamEquations::get_energy(), oomph::MyProblem::get_error_norm(), ExactSoln::get_exact_u(), ExactSolnForUnsteadyHeat::get_exact_u(), RachelsAdvectionDiffusion::get_exact_u(), TanhSolnForPoisson::get_exact_u(), PlanarWave::get_exact_u(), ProblemParameters::get_exact_u(), GlobalParameters::get_exact_u(), FishSolnOneDPoisson::get_exact_u(), GlobalParameters::get_exact_u_bessel(), oomph::KirchhoffLoveShellEquations::get_normal(), oomph::KirchhoffLoveBeamEquations::get_normal(), TestSoln::get_pressure(), oomph::PVDEquationsBase< DIM >::get_principal_stress(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::get_q_basis_local(), oomph::TRaviartThomasDarcyElement< ORDER >::get_q_basis_local(), oomph::TPoroelasticityElement< ORDER >::get_q_basis_local(), PerturbationSolution::get_radial_distance(), GlobalParameters::get_simple_exact_u(), oomph::SegregatableFSIProblem::get_solid_change(), GlobalParameters::get_source(), oomph::KirchhoffLoveShellEquations::get_strain_and_bend(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::get_traction(), oomph::StreamfunctionProblem::get_vels(), StokesFlowExactWind::get_wind(), Quaternion< float >::getAxis(), StatisticsVector< T >::getCGWidth(), SinterNormalSpecies::getCollisionTime(), LinearPlasticViscoelasticNormalSpecies::getCollisionTime(), LinearViscoelasticNormalSpecies::getCollisionTime(), SinterLinNormalSpecies::getCollisionTime(), SPHNormalSpecies::getCollisionTime(), BaseInteraction::getContactRadius(), Vec3D::getCylindricalCoordinates(), Matrix3D::getCylindricalTensorField(), Vec3D::getCylindricalTensorField(), Vec3D::getDistance(), NurbsSurface::getDistance(), HorizontalScrew::getDistanceAndNormal(), ScrewsymmetricIntersectionOfWalls::getDistanceAndNormal(), BasicIntersectionOfWalls::getDistanceAndNormal(), Coil::getDistanceAndNormal(), Combtooth::getDistanceAndNormal(), CylindricalWall::getDistanceAndNormal(), InfiniteWallWithHole::getDistanceAndNormal(), ParabolaChute::getDistanceAndNormal(), SineWall::getDistanceAndNormal(), VChute::getDistanceAndNormal(), IntersectionOfWalls::getDistanceAndNormal(), Screw::getDistanceAndNormalLabCoordinates(), CGCoordinates::RZ::getDistanceSquared(), HertzianViscoelasticInteraction::getElasticEnergy(), HertzianViscoelasticInteraction::getElasticEnergyAtEquilibrium(), SinterInteraction::getFieldVTK(), InfiniteWallWithHole::getHoleDistance(), WallSpecies::getInfo(), SuperQuadricParticle::getInitialGuessForContact(), BaseParticle::getInteractionWith(), Quaternion< float >::getLength(), Vec3D::getLength(), CGCoordinates::R::getLength(), CGCoordinates::XY::getLength(), CGCoordinates::XYZ::getLength(), CGCoordinates::XZ::getLength(), CGCoordinates::YZ::getLength(), helpers::getMaximumVelocity(), LinearViscoelasticNormalSpecies::getMaximumVelocity(), SPHNormalSpecies::getMaximumVelocity(), ChuteWithHopper::getMaximumVelocityInducedByGravity(), InitialConditions< SpeciesType >::getMeanRelativeContactRadius(), Sintering::getMeanRelativeContactRadius(), regimeForceUnitTest::getMeanRelativeContactRadius(), MeltableInteraction::getNeckRadius(), RNG::getNormalVariate(), Vec3D::getRadialCoordinate(), helpers::getRayleighTime(), Membrane::Edge::getSineHalfTheta(), Vec3D::getSphericalCoordinates(), CGFields::StandardFields::getStandardisedParticleSizeMomenta(), Vec3D::getUnitVector(), oomph::Orthpoly::gl_nodes(), oomph::Orthpoly::gll_nodes(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_helmholtz(), AxisymmetricVibratingShellProblem< ELEMENT >::global_temporal_error_norm(), VibratingShellProblem< ELEMENT >::global_temporal_error_norm(), RefineableUnsteadyHeatProblem< ELEMENT >::global_temporal_error_norm(), InterfaceProblem< ELEMENT, TIMESTEPPER >::global_temporal_error_norm(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::global_temporal_error_norm(), UnsteadyHeatProblem< ELEMENT >::global_temporal_error_norm(), oomph::Problem::globally_convergent_line_search(), GluedSolidMesh::glue(), Eigen::internal::gmres(), mathsFunc::goldenSectionSearch(), HGridOptimiser::goldenSectionSearch(), Global_Parameters::grad_blend(), Global_parameters::grad_f1(), Global_parameters::grad_f2(), Global_Parameters::grad_pressure_singularity1(), Global_Parameters::grad_velocity_singularity1(), Global_Parameters::grad_velocity_singularity2(), GranuDrum::GranuDrum(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation(), MercuryBase::hGridActionsAfterIntegration(), HomogenisationProblem< ELEMENT >::HomogenisationProblem(), oomph::HopfHandler::HopfHandler(), mathsFunc::I0_exp(), oomph::BiharmonicFluidProblem< DIM >::impose_fluid_flow_on_edge(), oomph::BiharmonicFluidProblem< DIM >::impose_traction_free_edge(), MyCanyonMesh< ELEMENT, INTERFACE_ELEMENT >::init_spine_height(), MyTipMesh< ELEMENT, INTERFACE_ELEMENT >::init_spine_height(), oomph::BrethertonSpineMesh< ELEMENT, SpineLineFluidInterfaceElement< ELEMENT > >::initial_element_reorder(), oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::integrate_c(), TriangleWall::isInsideTriangle(), CFDDEMCoupleTest::itterateL(), oomph::BiharmonicFluxElement< DIM >::J_eulerian(), oomph::FiniteElement::J_eulerian(), oomph::FaceElement::J_eulerian(), oomph::FiniteElement::J_eulerian_at_knot(), oomph::FaceElement::J_eulerian_at_knot(), oomph::SarahBL::Kin_energy_sarah(), SarahBL::Kin_energy_sarah(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::lagrangian_eulerian_translation_factor(), lapackNorm(), Eigen::internal::least_square_conjugate_gradient(), SmallVector< numberOfRows >::length(), TwoDDGProblem< ELEMENT >::limit(), oomph::BlackBoxFDNewtonSolver::line_search(), Eigen::internal::llt_rank_update_lower(), Eigen::internal::lmpar(), Eigen::internal::lmpar2(), oomph::FiniteElement::locate_zeta(), RefineableBin::locate_zeta(), NonRefineableBinArray::locate_zeta(), Flag_definition::lower_tip(), lpNorm(), oomph::VectorHelpers::magnitude(), main(), Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::MatrixBase< Derived >::makeHouseholder(), Eigen::JacobiRotation< Scalar >::makeJacobi(), Trackball::mapToSphere(), TestProblem::mass_source(), Eigen::internal::matrix_sqrt_quasi_triangular_diagonal(), Eigen::matrix_sqrt_triangular(), oomph::HelmholtzMGPreconditioner< DIM >::maximum_edge_width(), MeltableForceLaw2SelfTest::MeltableForceLaw2SelfTest(), oomph::MeshHelper::merge_spine_meshes(), NonRefineableBinArray::min_distance(), Eigen::LevenbergMarquardt< FunctorType_ >::minimizeOneStep(), Eigen::LevenbergMarquardt< FunctorType_ >::minimizeOptimumStorageOneStep(), Eigen::internal::minimum_degree_ordering(), Eigen::internal::minres(), mixingtypes(), ThreeDimBethertonProblem< ELEMENT >::multiply_aspect_ratio(), oomph::Problem::newton_solve(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_IV(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_V(), Eigen::SparseMatrixBase< Derived >::norm(), oomph::DoubleVector::norm(), oomph::DoubleMultiVector::norm(), Vec3D::normalise(), oomph::DGEulerFaceElement< ELEMENT >::numerical_flux(), SqrtOutputKernel::operator()(), Eigen::MatrixBase< Derived >::operatorNorm(), OscRingNStProblem< ELEMENT >::OscRingNStProblem(), oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::output(), ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement< ELEMENT >::output(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::output(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output(), oomph::HermiteBeamElement::output(), oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output(), output(), oomph::TriangleMesh< FLUID_ELEMENT >::output_boundary_coordinates(), CGFields::StandardFields::outputStandardisedParticleSizeMomenta(), LiquidMigrationMPI2Test::outputXBallsData(), LiquidMigrationSelfTest::outputXBallsData(), oomph::SarahBL::P_sarah(), SarahBL::P_sarah(), packetmath(), packetmath_complex(), HertzianBSHPInteractionTwoParticleElasticCollision::padeCoefficientOfRestitution(), SphericalSteadyRotationProblem< ELEMENT >::parameter_study(), TwoDDGProblem< ELEMENT >::parameter_study(), AdvectionProblem::parameter_study(), ParticleBeam::ParticleBeam(), particleParticleTest(), pblueNorm(), oomph::CircularPenetrator::penetration(), HeatedCircularPenetratorElement::penetration(), CircularPenetratorElement::penetration(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::perform_power_method(), Eigen::BDCSVD< MatrixType_, Options_ >::perturbCol0(), oomph::Legendre_functions_helper::plgndr2(), oomph::PolygonHelper::point_is_in_polygon(), Global_parameters::polar(), Flag_definition::TopOfFlag::position(), Flag_definition::BottomOfFlag::position(), AxisymOscillatingDisk::position(), WarpedLine::position(), oomph::WarpedCircularDisk::position(), Eigen::internal::positive_real_hypot(), oomph::BandedBlockTriangularPreconditioner< MATRIX >::preconditioner_solve(), TanhSolnForSteadyAxisymAdvectionDiffusion::prescribed_alpha_on_fixed_r_boundary(), TanhSolnForSteadyAxisymAdvectionDiffusion::prescribed_beta_on_fixed_r_boundary(), ExactSolution::prescribed_flux_for_unsteady_heat_validation(), ExactSolnForUnsteadyHeat::prescribed_flux_on_fixed_y_boundary(), GlobalParameters::prescribed_incoming_flux(), ExactSoln::prescribed_traction(), Global_Parameters::pressure_couette(), Global_Parameters::pressure_singularity1(), Global_Parameters::pressure_singularity2(), print_elemental_jacobian(), oomph::PseudoBucklingRing::PseudoBucklingRing(), oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::pshape_nst(), oomph::PRefineableQCrouzeixRaviartElement< DIM >::pshape_nst(), QFaceTestProblem< ELEMENT >::QFaceTestProblem(), qr(), qr_fixedsize(), qr_kahan_matrix(), oomph::EighthSphereDomain::r_front_F(), oomph::EighthSphereDomain::r_right_R(), oomph::EighthSphereDomain::r_up_U(), Eigen::internal::real_2x2_jacobi_svd(), oomph::TreeBasedRefineableMeshBase::refine_as_in_reference_mesh(), oomph::RefineableSolidTractionElement< ELEMENT >::refineable_fill_in_contribution_to_residuals_solid_traction(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), relerr(), Eigen::LevenbergMarquardt< FunctorType_ >::resetParameters(), oomph::HelmholtzMGPreconditioner< DIM >::residual_norm(), oomph::NonlinearSurfaceContactElement< ELEMENT >::resulting_contact_force(), oomph::LinearSurfaceContactElement< ELEMENT >::resulting_contact_force(), RisingBubbleProblem< ELEMENT >::RisingBubbleProblem(), CircularPeriodicBoundary::rotateParticle(), ClumpParticle::rotatePrincipalDirections(), RotatingDrumBidisperse::RotatingDrumBidisperse(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), rotg(), check_sqrt_impl< T >::run(), check_sqrt_impl< std::complex< T > >::run(), Eigen::internal::sqrt_impl< Scalar >::run(), Eigen::internal::tridiagonalization_inplace_selector< MatrixType, 3, false >::run(), Eigen::internal::quaternionbase_assign_impl< Other, 3, 3 >::run(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::run(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, Options, true >::run(), run_it(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::scale_basis(), oomph::TRaviartThomasDarcyElement< ORDER >::scale_basis(), oomph::TPoroelasticityElement< ORDER >::scale_basis(), ScaleCoupledBeam::ScaleCoupledBeam(), SingleParticle< SpeciesType >::scaleMass(), InitialConditions< SpeciesType >::scaleMass(), oomph::AlgebraicNode::self_test(), DeletionBoundary::set(), FluxBoundary::set(), ConstantMassFlowMaserBoundary::set(), PeriodicBoundary::set(), SubcriticalMaserBoundary::set(), InfiniteWallWithHole::set(), RefineableRotatingCylinderProblem< ELEMENT >::set_boundary_conditions(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::set_initial_condition(), LinearWaveProblem< ELEMENT, TIMESTEPPER >::set_initial_condition(), AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_initial_conditions(), Vreman::set_symmetric_contraction(), ContractionWithPeriodicInflow::set_symmetric_contraction(), ChuteWithPeriodicInflowAndContraction::set_symmetric_contraction(), ChuteWithContraction::set_symmetric_contraction(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_up_periodic_base_flow(), SuperQuadricParticle::setBoundingRadius(), SlidingFrictionSpecies::setCollisionTimeAndNormalAndTangentialRestitutionCoefficient(), LinearPlasticViscoelasticNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), LinearViscoelasticNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), SinterLinNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), SinterNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), SPHNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), setDistance(), PSD::setDistributionLogNormal(), PSD::setDistributionNormal(), Membrane::setElasticModulusAndThickness(), Eigen::QuaternionBase< Derived >::setFromTwoVectors(), DPMBase::setMeanVelocityAndKineticEnergy(), IntersectionOfWalls::setPointsAndLines(), Calibration::setPSD(), Material::setPSD(), CG< Coordinates, BaseFunction, Fields >::setRadius(), LinearPlasticViscoelasticNormalSpecies::setRestitutionCoefficient(), LinearViscoelasticNormalSpecies::setRestitutionCoefficient(), SinterLinNormalSpecies::setRestitutionCoefficient(), SPHNormalSpecies::setRestitutionCoefficient(), Initialization::setScaleFactor(), vibratedBed::setShakingStrength(), LevelSetWall::setShapeCylinder(), LevelSetWall::setShapeDiamond(), LevelSetWall::setShapeSphere(), SinterLinNormalSpecies::setStiffnessAndRestitutionCoefficient(), SinterNormalSpecies::setStiffnessAndRestitutionCoefficient(), HeaterBoundary::setStrength2D(), HeaterBoundary::setStrength3D(), oomph::TetMeshBase::setup_boundary_coordinates(), oomph::XdaTetMesh< ELEMENT >::setup_boundary_coordinates(), oomph::UnstructuredTwoDMeshGeometryBase::setup_boundary_coordinates(), MortaringHelpers::setup_constraint_elements_at_nodes(), oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::setup_gamma(), oomph::HelmholtzDtNMesh< ELEMENT >::setup_gamma(), oomph::HelmholtzMGPreconditioner< DIM >::setup_mg_structures(), CFDDEMCoupleTest::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), FreeCooling2DinWallsDemo::setupInitialConditions(), FreeCoolingDemoProblem::setupInitialConditions(), MarbleRun::setupInitialConditions(), StressStrainControl::setupInitialConditions(), Cstatic3D::setupInitialConditions(), CGBasicSelfTest::setupInitialConditions(), my_problem_HGRID::setupInitialConditions(), Contact::setupInitialConditions(), Wall::setupInitialConditions(), GranularCollapse::setupInitialConditions(), AngledPeriodicBoundarySecondUnitTest::setupInitialConditions(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), HertzianSinterForceUnitTest::setupInitialConditions(), MovingIntersectionOfWallsUnitTest_Basic::setupInitialConditions(), PlasticForceUnitTest::setupInitialConditions(), my_problem::setupInitialConditions(), SinterForceUnitTest::setupInitialConditions(), BaseCluster::setupInitialConditions(), CoupledBeam::setupOomph(), Siegen::Siegen(), Slide::Slide(), oomph::TetMeshBase::snap_nodes_onto_geometric_objects(), FallingBlockProblem< ELEMENT >::snap_onto_sphere(), RisingBubbleProblem< ELEMENT >::snap_onto_sphere(), oomph::TetMeshBase::snap_to_quadratic_surface(), Global_Parameters::solid_boundary_displacement(), ComplexHarmonicProblem< ELEMENT, EIGEN_SOLVER >::solve(), HarmonicProblem< ELEMENT, EIGEN_SOLVER >::solve(), oomph::GMRES< MATRIX >::solve_helper(), oomph::HelmholtzGMRESMG< MATRIX >::solve_helper(), oomph::HelmholtzFGMRESMG< MATRIX >::solve_helper(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveNumericalDiffOneStep(), solveQuad(), FishSolnOneDPoisson::source_function(), specificTest1(), sphericalHarmonics::sphericalHarmonics(), SphericalSpinUpProblem< ELEMENT >::SphericalSpinUpProblem(), SphericalTetMeshFacetedSurface::SphericalTetMeshFacetedSurface(), MyCanyonMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), MyTipMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_upper(), DPMBase::splitDomain(), Eigen::RealQZ< MatrixType_ >::splitOffTwoRows(), Eigen::RealSchur< MatrixType_ >::splitOffTwoRows(), Global_Physical_Variables::spring_load(), Global_Physical_Variables::spring_load_lower(), Matrix3D::sqrt(), MatrixSymmetric3D::sqrt(), Vec3D::sqrt(), SYCL::sqrt(), Eigen::LevenbergMarquardt< FunctorType_ >::sqrt_epsilon(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::square_of_l2_norm_of_error(), stable_norm(), Eigen::internal::stable_norm_impl(), oomph::LinearisedAxisymmetricNavierStokesEquations::strain_rate(), oomph::LinearisedNavierStokesEquations::strain_rate(), AxisymmetricVibratingShellProblem< ELEMENT >::strainrate_norm(), VibratingShellProblem< ELEMENT >::strainrate_norm(), svd_least_square(), test_array(), test_async_sharded_by_inner_dim_contraction_with_output_kernel(), test_basic_functions(), test_hypot(), test_large_contraction_with_output_kernel(), test_multithread_contraction_with_output_kernel(), test_nnls_known_solution(), test_nnls_random_problem(), Eigen::test_relative_error(), boost::multiprecision::test_relative_error(), test_sharded_by_inner_dim_contraction_with_output_kernel(), test_sum_accuracy(), test_unary_builtins_for_assignement(), ShapeGradientHessianTester::testEllipsoid(), ShapeGradientHessianTester::testSphere(), tetgenbehavior::tetgenbehavior(), TFaceTestProblem< ELEMENT >::TFaceTestProblem(), oomph::ThinLayerBrickOnTetMesh< ELEMENT >::ThinLayerBrickOnTetMesh(), ThreeDimBethertonProblem< ELEMENT >::ThreeDimBethertonProblem(), ActivatorInhibitorProblem< ELEMENT >::timestep(), oomph::SarahBL::Total_Diss_lead_sarah(), SarahBL::Total_Diss_lead_sarah(), oomph::SarahBL::Total_Diss_sarah(), SarahBL::Total_Diss_sarah(), oomph::BermudezPMLMappingAndTransformedCoordinate::transformed_coordinate(), TriangleFaceTestProblem< ELEMENT >::TriangleFaceTestProblem(), oomph::TriangleMeshClosedCurve::TriangleMeshClosedCurve(), oomph::TriangleMeshOpenCurve::TriangleMeshOpenCurve(), oomph::TriangleMeshPolygon::TriangleMeshPolygon(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem(), oomph::VectorHelpers::two_norm(), oomph::YoungLaplaceEquations::two_norm(), oomph::SarahBL::U_sarah(), SarahBL::U_sarah(), unary_ops_test(), Eigen::internal::llt_inplace< Scalar, Lower >::unblocked(), Eigen::Quaternion< Scalar_, Options_ >::UnitRandom(), UnstructuredFvKProblem< ELEMENT >::UnstructuredFvKProblem(), Global_Physical_Variables::update_dependent_parameters(), MindlinInteraction::updateTangentialStiffnessZero(), MeshTriangle::updateVertexAndNormal(), Flag_definition::upper_tip(), oomph::SarahBL::V_sarah(), SarahBL::V_sarah(), AxisymOscillatingDisk::veloc(), Global_Parameters::velocity_couette(), MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::verify_mortared_nodes_coincide(), oomph::PowerLawBerEngRegConstitutiveEquation< DIM >::viscosity(), oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >::viscosity(), oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::viscosity(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity(), oomph::HerschelBulkleyPapRegConstitutiveEquation< DIM >::viscosity(), oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::viscosity(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity(), oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity(), wallParticleTest(), oomph::TwoDAnnularMesh< ELEMENT >::wrap_into_annular_shape(), SingleParticle< SpeciesType >::writeEneTimeStep(), GranuDrum::writeResults(), and RotatingDrumBidisperse::writeResults().
test_isApprox()
bool test_isApprox (const AnnoyingScalar & a, const AnnoyingScalar & b) inline
{
   return internal::isApprox(*a.v, *b.v, test_precision<float>());
 }
References a, b, Eigen::internal::isApprox(), and test_precision< float >().
Referenced by svd_least_square(), and test_sparseqr_scalar().
test_isMuchSmallerThan()
bool test_isMuchSmallerThan (const AnnoyingScalar & a, const AnnoyingScalar & b) inline
{
   return test_isMuchSmallerThan(*a.v, *b.v);
 }
References a, and b.
Referenced by svd_least_square(), and verify_euler().
test_relative_error()
AnnoyingScalar test_relative_error (const AnnoyingScalar & a, const AnnoyingScalar & b)
{
   return test_relative_error(*a.v, *b.v);
 }
References a, and b.
Referenced by verifyIsApprox().