MercuryDPM: VTKUnstructuredGrid< T > Class Template Reference
VTKUnstructuredGrid< T > Class Template Reference
#include <VTKData.h>
Public Member Functions
VTKUnstructuredGrid (std::string filename, const VTKPointDescriptor< T > *descr)
operator bool () const
template<typename C >
void write (const C &container)
Private Attributes
const VTKPointDescriptor< T > * descriptor_
std::ofstream outFile_
Detailed Description
template<typename T>
class VTKUnstructuredGrid< T >
This function writes single output frames. this requires an filename and a descriptor. To actually write it, we need a collection.
Constructor & Destructor Documentation
VTKUnstructuredGrid()
template<typename T > VTKUnstructuredGrid< T >::VTKUnstructuredGrid (std::string filename, const VTKPointDescriptor< T > * descr) inline
Create a new VTK Unstructured grid file.
Parameters
filename The name of the output file
descr The typedescriptor for T
     : descriptor_(descr), outFile_(filename)
   {
   }
Member Function Documentation
operator bool()
template<typename T > VTKUnstructuredGrid< T >::operator bool () const inline
Returns true if this VTK output file is valid and has no errorbits set
   {
     return outFile_.good();
   }
References VTKUnstructuredGrid< T >::outFile_.
write()
template<typename T > template<typename C > void VTKUnstructuredGrid< T >::write (const C & container) inline
Writes out the container C containing T's, which all get written using the information in the descriptor. C should contain the forward iterable traits, as well as a method size() to give the number of elements stored in this container. All STL containers have this property. Yours should too.
   {
     outFile_ <<
       "<?xml version=\"1.0\"?>\n"
        "<VTKFile type=\"UnstructuredGrid\" version=\"0.1\" byte_order=\"LittleEndian\">\n"
        " <UnstructuredGrid>\n"
        "  <Piece NumberOfPoints=\"" << container.size() << "\" NumberOfCells=\"0\">\n"
        "   <Cells>\n"
        "    <DataArray type=\"Int32\" name=\"connectivity\" format=\"ascii\">\n"
        "       0\n"
        "    </DataArray>\n"
        "    <DataArray type=\"Float32\" name=\"offset\" format=\"ascii\">\n"
        "       0\n"
        "    </DataArray>\n"
        "    <DataArray type=\"UInt8\" name=\"types\" format=\"ascii\">\n"
        "       1\n"
        "    </DataArray>\n"
        "   </Cells>\n"
        "   <Points>\n";
     Detail::VTKPointDescriptorEntry<T>* pDescr = descriptor_->positionEntry_;
     outFile_ << "<DataArray type=\"" << pDescr->getTypeName() << "\" "
                 "NumberOfComponents=\"" << pDescr->getNumberOfComponents() << "\" "
                 "format=\"ascii\">\n";
     for (const T& mem : container)
     {
       pDescr->emit(outFile_, mem);
     }
     outFile_ << "\n</DataArray>\n";
     outFile_ <<
       "    </Points>\n"
       "    <PointData>\n";
     for (Detail::VTKPointDescriptorEntry<T>* descr : descriptor_->entries_)
     {
       outFile_ << "<DataArray type=\""    << descr->getTypeName() << "\" "
                   "Name=\""               << descr->getName() << "\" "
                   "NumberOfComponents=\"" << descr->getNumberOfComponents() << "\" "
                   "format=\"ascii\">\n";
       for (const T& mem : container)
       {
         descr->emit(outFile_, mem);
       }
       outFile_ << "\n</DataArray>\n";
     }
     outFile_ <<
       "   </PointData>\n"
       "   <CellData/>\n"
       "  </Piece>\n"
       " </UnstructuredGrid>\n"
       "</VTKFile>\n";
   }
References VTKUnstructuredGrid< T >::descriptor_, Detail::VTKPointDescriptorEntry< T >::emit(), Detail::VTKPointDescriptorEntry< T >::getName(), Detail::VTKPointDescriptorEntry< T >::getNumberOfComponents(), Detail::VTKPointDescriptorEntry< T >::getTypeName(), and VTKUnstructuredGrid< T >::outFile_.
Referenced by transformMercuryToVTK().
Member Data Documentation
descriptor_
template<typename T > const VTKPointDescriptor<T>* VTKUnstructuredGrid< T >::descriptor_ private
Referenced by VTKUnstructuredGrid< T >::write().
outFile_
template<typename T > std::ofstream VTKUnstructuredGrid< T >::outFile_ private
Referenced by VTKUnstructuredGrid< T >::operator bool(), and VTKUnstructuredGrid< T >::write().
The documentation for this class was generated from the following file:
Tools/VTKData.h