MercuryDPM: ReversibleAdhesiveSpecies Class Reference
ReversibleAdhesiveSpecies Class Reference
ReversibleAdhesiveSpecies contains the parameters used to describe a linear reversible short-range force.
#include <ReversibleAdhesiveSpecies.h>
Public Types
typedef ReversibleAdhesiveInteraction InteractionType
The correct Interaction type for this AdhesiveForceSpecies.
Public Member Functions
ReversibleAdhesiveSpecies ()
The default constructor.
ReversibleAdhesiveSpecies (const ReversibleAdhesiveSpecies &s)
The default constructor.
~ReversibleAdhesiveSpecies ()
The default constructor.
void read (std::istream &is)
Reads the species properties from an input stream.
void write (std::ostream &os) const
Writes the species properties to an output stream.
std::string getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
void mix (ReversibleAdhesiveSpecies *S, ReversibleAdhesiveSpecies *T)
creates default values for mixed species
void setInteractionDistance ()
returns the largest separation distance at which adhesive short-range forces can occur.
void setAdhesionStiffness (Mdouble new_k0)
Allows the spring constant to be changed.
Mdouble getAdhesionStiffness () const
Allows the spring constant to be accessed.
void setAdhesionForceMax (Mdouble new_f0)
Allows the spring constant to be changed.
Mdouble getAdhesionForceMax () const
Allows the spring constant to be accessed.
Public Member Functions inherited from BaseForce
BaseSpecies * getBaseSpecies () const
void setBaseSpecies (BaseSpecies *baseSpecies)
Private Attributes
Mdouble adhesionStiffness_
stiffness of linear adhesion force
Mdouble adhesionForceMax_
adhesion force at zero overlap
Detailed Description
ReversibleAdhesiveSpecies contains the parameters used to describe a linear reversible short-range force.
See ReversibleAdhesiveInteraction::computeForce for a description of the force law.
Member Typedef Documentation
InteractionType
typedef ReversibleAdhesiveInteraction ReversibleAdhesiveSpecies::InteractionType
The correct Interaction type for this AdhesiveForceSpecies.
Constructor & Destructor Documentation
ReversibleAdhesiveSpecies() [1/2]
ReversibleAdhesiveSpecies::ReversibleAdhesiveSpecies ()
The default constructor.
 {
     adhesionForceMax_ = 0;
     adhesionStiffness_ = 0;
     //interaction distance not yet determined
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"ReversibleAdhesiveSpecies::ReversibleAdhesiveSpecies() finished"<<std::endl;
 #endif
 }
References adhesionForceMax_, and adhesionStiffness_.
ReversibleAdhesiveSpecies() [2/2]
ReversibleAdhesiveSpecies::ReversibleAdhesiveSpecies (const ReversibleAdhesiveSpecies & s)
The default constructor.
Parameters
[in] s the species that is copied
 {
     adhesionForceMax_ = s.adhesionForceMax_;
     adhesionStiffness_ = s.adhesionStiffness_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"ReversibleAdhesiveSpecies::ReversibleAdhesiveSpecies(const ReversibleAdhesiveSpecies &p) finished"<<std::endl;
 #endif
 }
References adhesionForceMax_, adhesionStiffness_, and s.
~ReversibleAdhesiveSpecies()
ReversibleAdhesiveSpecies::~ReversibleAdhesiveSpecies ()
The default constructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"ReversibleAdhesiveSpecies::~ReversibleAdhesiveSpecies() finished"<<std::endl;
 #endif
 }
Member Function Documentation
getAdhesionForceMax()
Mdouble ReversibleAdhesiveSpecies::getAdhesionForceMax () const
Allows the spring constant to be accessed.
 {
     return adhesionForceMax_;
 }
References adhesionForceMax_.
Referenced by IrreversibleAdhesiveInteraction::computeAdhesionForce(), ReversibleAdhesiveInteraction::computeAdhesionForce(), and IrreversibleAdhesiveInteraction::getElasticEnergy().
getAdhesionStiffness()
Mdouble ReversibleAdhesiveSpecies::getAdhesionStiffness () const
Allows the spring constant to be accessed.
 {
     return adhesionStiffness_;
 }
References adhesionStiffness_.
Referenced by IrreversibleAdhesiveInteraction::computeAdhesionForce(), ReversibleAdhesiveInteraction::computeAdhesionForce(), IrreversibleAdhesiveInteraction::getElasticEnergy(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), and ParticleWallInteraction::setupInitialConditions().
getBaseName()
std::string ReversibleAdhesiveSpecies::getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
Returns
a string containing the name of the species (minus the word "Species")
 {
     return "ReversibleAdhesive";
 }
mix()
void ReversibleAdhesiveSpecies::mix (ReversibleAdhesiveSpecies * S, ReversibleAdhesiveSpecies * T)
creates default values for mixed species
For all parameters we assume that the harmonic mean of the parameters of the original two species is a sensible default.
Parameters
[in] S,T the two species whose properties are mixed to create the new species
 {
     adhesionForceMax_ = BaseSpecies::average(S->getAdhesionForceMax(), T->getAdhesionForceMax());
     adhesionStiffness_ = BaseSpecies::average(S->getAdhesionStiffness(), T->getAdhesionStiffness());
 }
References adhesionForceMax_, adhesionStiffness_, BaseSpecies::average(), and oomph::QuadTreeNames::S.
read()
void ReversibleAdhesiveSpecies::read (std::istream & is)
Reads the species properties from an input stream.
Parameters
[in] is input stream (typically the restart file)
 {
     std::string dummy;
     is >> dummy >> adhesionForceMax_;
     is >> dummy >> adhesionStiffness_;
 }
References adhesionForceMax_, adhesionStiffness_, and oomph::Global_string_for_annotation::string().
setAdhesionForceMax()
void ReversibleAdhesiveSpecies::setAdhesionForceMax (Mdouble new_f0)
Allows the spring constant to be changed.
 {
     logger.assert_debug(adhesionForceMax >= 0,"Error in setAdhesionForceMax");
     adhesionForceMax_ = adhesionForceMax;
     if (adhesionStiffness_!=0) setInteractionDistance();
 }
References adhesionForceMax_, adhesionStiffness_, logger, and setInteractionDistance().
Referenced by ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), and ParticleWallInteraction::setupInitialConditions().
setAdhesionStiffness()
void ReversibleAdhesiveSpecies::setAdhesionStiffness (Mdouble new_k0)
Allows the spring constant to be changed.
 {
     logger.assert_debug(adhesionStiffness >= 0,"Error in setAdhesionStiffness");
     adhesionStiffness_ = adhesionStiffness;
     setInteractionDistance();
 }
References adhesionStiffness_, logger, and setInteractionDistance().
Referenced by ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), and ParticleWallInteraction::setupInitialConditions().
setInteractionDistance()
void ReversibleAdhesiveSpecies::setInteractionDistance () virtual
returns the largest separation distance at which adhesive short-range forces can occur.
Returns
the maximum separation distance below which adhesive forces can occur (needed for contact detection)
Reimplemented from BaseAdhesiveForce.
 {
     logger.assert_debug(adhesionStiffness_ != 0.0,"ReversibleAdhesiveSpecies::getInteractionDistance(): adhesionStiffness cannot be zero");
     getBaseSpecies()->setInteractionDistance(adhesionForceMax_ / adhesionStiffness_);
 }
References adhesionForceMax_, adhesionStiffness_, BaseForce::getBaseSpecies(), logger, and BaseSpecies::setInteractionDistance().
Referenced by setAdhesionForceMax(), and setAdhesionStiffness().
write()
void ReversibleAdhesiveSpecies::write (std::ostream & os) const
Writes the species properties to an output stream.
Parameters
[out] os output stream (typically the restart file)
 {
     os << " adhesionForceMax " << adhesionForceMax_;
     os << " adhesionStiffness " << adhesionStiffness_;
 }
References adhesionForceMax_, and adhesionStiffness_.
Member Data Documentation
adhesionForceMax_
Mdouble ReversibleAdhesiveSpecies::adhesionForceMax_ private
adhesion force at zero overlap
Referenced by getAdhesionForceMax(), mix(), read(), ReversibleAdhesiveSpecies(), setAdhesionForceMax(), setInteractionDistance(), and write().
adhesionStiffness_
Mdouble ReversibleAdhesiveSpecies::adhesionStiffness_ private
stiffness of linear adhesion force
Referenced by getAdhesionStiffness(), mix(), read(), ReversibleAdhesiveSpecies(), setAdhesionForceMax(), setAdhesionStiffness(), setInteractionDistance(), and write().
The documentation for this class was generated from the following files:
ReversibleAdhesiveSpecies.h
ReversibleAdhesiveSpecies.cc