MercuryDPM: Eigen::MatrixBase< Derived > Class Template Reference
Eigen::MatrixBase< Derived > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Base class for all dense matrices, vectors, and expressions.
#include <MatrixBase.h>
Classes
struct ConstSelfAdjointViewReturnType
struct ConstTriangularViewReturnType
struct SelfAdjointViewReturnType
struct TriangularViewReturnType
Public Types
enum { HomogeneousReturnTypeDirection }
enum { SizeMinusOne = SizeAtCompileTime == Dynamic ? Dynamic : SizeAtCompileTime - 1 }
typedef MatrixBase StorageBaseType
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::StorageIndex StorageIndex
typedef internal::traits< Derived >::Scalar Scalar
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef NumTraits< Scalar >::Real RealScalar
typedef DenseBase< Derived > Base
typedef Base::CoeffReturnType CoeffReturnType
typedef Base::ConstTransposeReturnType ConstTransposeReturnType
typedef Base::RowXpr RowXpr
typedef Base::ColXpr ColXpr
typedef Matrix< Scalar, internal::max_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime), internal::max_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime)> SquareMatrixType
typedef Base::PlainObject PlainObject
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, PlainObject > ConstantReturnType
typedef std::conditional_t< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, ConstTransposeReturnType >, ConstTransposeReturnType > AdjointReturnType
typedef Matrix< std::complex< RealScalar >, internal::traits< Derived >::ColsAtCompileTime, 1, ColMajor > EigenvaluesReturnType
typedef CwiseNullaryOp< internal::scalar_identity_op< Scalar >, PlainObject > IdentityReturnType
typedef Block< const CwiseNullaryOp< internal::scalar_identity_op< Scalar >, SquareMatrixType >, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime > BasisReturnType
typedef Diagonal< Derived > DiagonalReturnType
typedef Diagonal< const Derived > ConstDiagonalReturnType
typedef Homogeneous< Derived, HomogeneousReturnTypeDirection > HomogeneousReturnType
typedef Block< const Derived, internal::traits< Derived >::ColsAtCompileTime==1 ? SizeMinusOne :1, internal::traits< Derived >::ColsAtCompileTime==1 ? 1 :SizeMinusOne > ConstStartMinusOne
typedef internal::stem_function< Scalar >::type StemFunction
Public Types inherited from Eigen::DenseBase< Derived >
enum {
RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime , ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime , SizeAtCompileTime = (internal::size_of_xpr_at_compile_time<Derived>::ret) , MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime , MaxSizeAtCompileTime , IsVectorAtCompileTime , NumDimensions ,
Flags = internal::traits<Derived>::Flags , IsRowMajor = int(Flags) & RowMajorBit , InnerSizeAtCompileTime , InnerStrideAtCompileTime = internal::inner_stride_at_compile_time<Derived>::ret ,
OuterStrideAtCompileTime = internal::outer_stride_at_compile_time<Derived>::ret
}
enum { IsPlainObjectBase = 0 }
typedef Eigen::InnerIterator< Derived > InnerIterator
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::StorageIndex StorageIndex
The type used to store indices.
typedef internal::traits< Derived >::Scalar Scalar
typedef Scalar value_type
typedef NumTraits< Scalar >::Real RealScalar
typedef DenseCoeffsBase< Derived, internal::accessors_level< Derived >::value > Base
typedef Base::CoeffReturnType CoeffReturnType
typedef internal::find_best_packet< Scalar, SizeAtCompileTime >::type PacketScalar
typedef Matrix< typename internal::traits< Derived >::Scalar, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime, AutoAlign|(internal::traits< Derived >::Flags &RowMajorBit ? RowMajor :ColMajor), internal::traits< Derived >::MaxRowsAtCompileTime, internal::traits< Derived >::MaxColsAtCompileTime > PlainMatrix
typedef Array< typename internal::traits< Derived >::Scalar, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime, AutoAlign|(internal::traits< Derived >::Flags &RowMajorBit ? RowMajor :ColMajor), internal::traits< Derived >::MaxRowsAtCompileTime, internal::traits< Derived >::MaxColsAtCompileTime > PlainArray
typedef std::conditional_t< internal::is_same< typename internal::traits< Derived >::XprKind, MatrixXpr >::value, PlainMatrix, PlainArray > PlainObject
The plain matrix or array type corresponding to this expression.
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, PlainObject > ConstantReturnType
typedef CwiseNullaryOp< internal::scalar_zero_op< Scalar >, PlainObject > ZeroReturnType
typedef CwiseNullaryOp< internal::linspaced_op< Scalar >, PlainObject > RandomAccessLinSpacedReturnType
typedef CwiseNullaryOp< internal::equalspaced_op< Scalar >, PlainObject > RandomAccessEqualSpacedReturnType
typedef Matrix< typename NumTraits< typename internal::traits< Derived >::Scalar >::Real, internal::traits< Derived >::ColsAtCompileTime, 1 > EigenvaluesReturnType
typedef Transpose< Derived > TransposeReturnType
typedef Transpose< const Derived > ConstTransposeReturnType
typedef internal::add_const_on_value_type_t< typename internal::eval< Derived >::type > EvalReturnType
typedef VectorwiseOp< Derived, Horizontal > RowwiseReturnType
typedef const VectorwiseOp< const Derived, Horizontal > ConstRowwiseReturnType
typedef VectorwiseOp< Derived, Vertical > ColwiseReturnType
typedef const VectorwiseOp< const Derived, Vertical > ConstColwiseReturnType
typedef CwiseNullaryOp< internal::scalar_random_op< Scalar >, PlainObject > RandomReturnType
typedef Reverse< Derived, BothDirections > ReverseReturnType
typedef const Reverse< const Derived, BothDirections > ConstReverseReturnType
typedef std::conditional_t<(Flags &DirectAccessBit)==DirectAccessBit, internal::pointer_based_stl_iterator< Derived >, internal::generic_randaccess_stl_iterator< Derived > > iterator_type
typedef std::conditional_t<(Flags &DirectAccessBit)==DirectAccessBit, internal::pointer_based_stl_iterator< const Derived >, internal::generic_randaccess_stl_iterator< const Derived > > const_iterator_type
typedef std::conditional_t< IsVectorAtCompileTime, iterator_type, void > iterator
typedef std::conditional_t< IsVectorAtCompileTime, const_iterator_type, void > const_iterator
Public Member Functions
EIGEN_DEVICE_FUNC Index diagonalSize () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const MatrixBase &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const ReturnByValue< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator+= (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator-= (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const Product< Derived, OtherDerived > operator* (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const Product< Derived, OtherDerived, LazyProduct > lazyProduct (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
Derived & operator*= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
void applyOnTheLeft (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
void applyOnTheRight (const EigenBase< OtherDerived > &other)
template<typename DiagonalDerived >
EIGEN_DEVICE_FUNC const Product< Derived, DiagonalDerived, LazyProduct > operator* (const DiagonalBase< DiagonalDerived > &diagonal) const
template<typename SkewDerived >
EIGEN_DEVICE_FUNC const Product< Derived, SkewDerived, LazyProduct > operator* (const SkewSymmetricBase< SkewDerived > &skew) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC ScalarBinaryOpTraits< typename internal::traits< Derived >::Scalar, typename internal::traits< OtherDerived >::Scalar >::ReturnType dot (const MatrixBase< OtherDerived > &other) const
EIGEN_DEVICE_FUNC RealScalar squaredNorm () const
EIGEN_DEVICE_FUNC RealScalar norm () const
RealScalar stableNorm () const
RealScalar blueNorm () const
RealScalar hypotNorm () const
EIGEN_DEVICE_FUNC const PlainObject normalized () const
EIGEN_DEVICE_FUNC const PlainObject stableNormalized () const
EIGEN_DEVICE_FUNC void normalize ()
EIGEN_DEVICE_FUNC void stableNormalize ()
EIGEN_DEVICE_FUNC const AdjointReturnType adjoint () const
EIGEN_DEVICE_FUNC void adjointInPlace ()
EIGEN_DEVICE_FUNC DiagonalReturnType diagonal ()
EIGEN_DEVICE_FUNC const ConstDiagonalReturnType diagonal () const
template<int Index>
EIGEN_DEVICE_FUNC Diagonal< Derived, Index > diagonal ()
template<int Index>
EIGEN_DEVICE_FUNC const Diagonal< const Derived, Index > diagonal () const
EIGEN_DEVICE_FUNC Diagonal< Derived, DynamicIndex > diagonal (Index index)
EIGEN_DEVICE_FUNC const Diagonal< const Derived, DynamicIndex > diagonal (Index index) const
template<unsigned int Mode>
EIGEN_DEVICE_FUNC TriangularViewReturnType< Mode >::Type triangularView ()
template<unsigned int Mode>
EIGEN_DEVICE_FUNC ConstTriangularViewReturnType< Mode >::Type triangularView () const
template<unsigned int UpLo>
EIGEN_DEVICE_FUNC SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
template<unsigned int UpLo>
EIGEN_DEVICE_FUNC ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
const SparseView< Derived > sparseView (const Scalar &m_reference=Scalar(0), const typename NumTraits< Scalar >::Real &m_epsilon=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC const DiagonalWrapper< const Derived > asDiagonal () const
const PermutationWrapper< const Derived > asPermutation () const
EIGEN_DEVICE_FUNC const SkewSymmetricWrapper< const Derived > asSkewSymmetric () const
EIGEN_DEVICE_FUNC Derived & setIdentity ()
EIGEN_DEVICE_FUNC Derived & setIdentity (Index rows, Index cols)
Resizes to the given size, and writes the identity expression (not necessarily square) into *this.
EIGEN_DEVICE_FUNC Derived & setUnit (Index i)
Set the coefficients of *this to the i-th unit (basis) vector.
EIGEN_DEVICE_FUNC Derived & setUnit (Index newSize, Index i)
Resizes to the given newSize, and writes the i-th unit (basis) vector into *this.
bool isIdentity (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isDiagonal (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isUpperTriangular (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isLowerTriangular (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isSkewSymmetric (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
bool isOrthogonal (const MatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isUnitary (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool operator== (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool operator!= (const MatrixBase< OtherDerived > &other) const
NoAlias< Derived, Eigen::MatrixBase > EIGEN_DEVICE_FUNC noalias ()
const Derived & forceAlignedAccess () const
Derived & forceAlignedAccess ()
template<bool Enable>
const Derived & forceAlignedAccessIf () const
template<bool Enable>
Derived & forceAlignedAccessIf ()
EIGEN_DEVICE_FUNC Scalar trace () const
template<int p>
EIGEN_DEVICE_FUNC RealScalar lpNorm () const
EIGEN_DEVICE_FUNC MatrixBase< Derived > & matrix ()
EIGEN_DEVICE_FUNC const MatrixBase< Derived > & matrix () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ArrayWrapper< Derived > array ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const ArrayWrapper< const Derived > array () const
template<typename PermutationIndex = DefaultPermutationIndex>
const FullPivLU< PlainObject, PermutationIndex > fullPivLu () const
template<typename PermutationIndex = DefaultPermutationIndex>
const PartialPivLU< PlainObject, PermutationIndex > partialPivLu () const
template<typename PermutationIndex = DefaultPermutationIndex>
const PartialPivLU< PlainObject, PermutationIndex > lu () const
EIGEN_DEVICE_FUNC const Inverse< Derived > inverse () const
template<typename ResultType >
void computeInverseAndDetWithCheck (ResultType &inverse, typename ResultType::Scalar &determinant, bool &invertible, const RealScalar &absDeterminantThreshold=NumTraits< Scalar >::dummy_precision()) const
template<typename ResultType >
void computeInverseWithCheck (ResultType &inverse, bool &invertible, const RealScalar &absDeterminantThreshold=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC Scalar determinant () const
const LLT< PlainObject > llt () const
const LDLT< PlainObject > ldlt () const
const HouseholderQR< PlainObject > householderQr () const
template<typename PermutationIndex = DefaultPermutationIndex>
const ColPivHouseholderQR< PlainObject, PermutationIndex > colPivHouseholderQr () const
template<typename PermutationIndex = DefaultPermutationIndex>
const FullPivHouseholderQR< PlainObject, PermutationIndex > fullPivHouseholderQr () const
template<typename PermutationIndex = DefaultPermutationIndex>
const CompleteOrthogonalDecomposition< PlainObject, PermutationIndex > completeOrthogonalDecomposition () const
EigenvaluesReturnType eigenvalues () const
Computes the eigenvalues of a matrix.
RealScalar operatorNorm () const
Computes the L2 operator norm.
template<int Options = 0>
JacobiSVD< PlainObject, Options > jacobiSvd () const
template<int Options = 0>
EIGEN_DEPRECATED JacobiSVD< PlainObject, Options > jacobiSvd (unsigned int computationOptions) const
template<int Options = 0>
BDCSVD< PlainObject, Options > bdcSvd () const
template<int Options = 0>
EIGEN_DEPRECATED BDCSVD< PlainObject, Options > bdcSvd (unsigned int computationOptions) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC internal::cross_impl< Derived, OtherDerived >::return_type cross (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC PlainObject cross3 (const MatrixBase< OtherDerived > &other) const
EIGEN_DEVICE_FUNC PlainObject unitOrthogonal (void) const
EIGEN_DEPRECATED EIGEN_DEVICE_FUNC Matrix< Scalar, 3, 1 > eulerAngles (Index a0, Index a1, Index a2) const
EIGEN_DEVICE_FUNC Matrix< Scalar, 3, 1 > canonicalEulerAngles (Index a0, Index a1, Index a2) const
EIGEN_DEVICE_FUNC HomogeneousReturnType homogeneous () const
typedef EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE (ConstStartMinusOne, Scalar, quotient) HNormalizedReturnType
EIGEN_DEVICE_FUNC const HNormalizedReturnType hnormalized () const
homogeneous normalization
EIGEN_DEVICE_FUNC void makeHouseholderInPlace (Scalar &tau, RealScalar &beta)
template<typename EssentialPart >
EIGEN_DEVICE_FUNC void makeHouseholder (EssentialPart &essential, Scalar &tau, RealScalar &beta) const
template<typename EssentialPart >
EIGEN_DEVICE_FUNC void applyHouseholderOnTheLeft (const EssentialPart &essential, const Scalar &tau, Scalar *workspace)
template<typename EssentialPart >
EIGEN_DEVICE_FUNC void applyHouseholderOnTheRight (const EssentialPart &essential, const Scalar &tau, Scalar *workspace)
template<typename OtherScalar >
EIGEN_DEVICE_FUNC void applyOnTheLeft (Index p, Index q, const JacobiRotation< OtherScalar > &j)
template<typename OtherScalar >
EIGEN_DEVICE_FUNC void applyOnTheRight (Index p, Index q, const JacobiRotation< OtherScalar > &j)
template<typename OtherDerived >
EIGEN_STRONG_INLINE const SparseMatrixBase< OtherDerived >::template CwiseProductDenseReturnType< Derived >::Type cwiseProduct (const SparseMatrixBase< OtherDerived > &other) const
const MatrixFunctionReturnValue< Derived > matrixFunction (StemFunction f) const
Helper function for the unsupported MatrixFunctions module.
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const ReturnByValue< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ScalarBinaryOpTraits< typename internal::traits< Derived >::Scalar, typename internal::traits< OtherDerived >::Scalar >::ReturnType dot (const MatrixBase< OtherDerived > &other) const
template<int p>
EIGEN_DEVICE_FUNC NumTraits< typename internal::traits< Derived >::Scalar >::Real lpNorm () const
template<bool Enable>
add_const_on_value_type_t< std::conditional_t< Enable, ForceAlignedAccess< Derived >, Derived & > > forceAlignedAccessIf () const
template<bool Enable>
std::conditional_t< Enable, ForceAlignedAccess< Derived >, Derived & > forceAlignedAccessIf ()
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Product< Derived, OtherDerived > operator* (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Product< Derived, OtherDerived, LazyProduct > lazyProduct (const MatrixBase< OtherDerived > &other) const
template<unsigned int UpLo>
EIGEN_DEVICE_FUNC MatrixBase< Derived >::template ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
template<unsigned int UpLo>
EIGEN_DEVICE_FUNC MatrixBase< Derived >::template SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
template<unsigned int Mode>
EIGEN_DEVICE_FUNC MatrixBase< Derived >::template TriangularViewReturnType< Mode >::Type triangularView ()
template<unsigned int Mode>
EIGEN_DEVICE_FUNC MatrixBase< Derived >::template ConstTriangularViewReturnType< Mode >::Type triangularView () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::cross_impl< Derived, OtherDerived >::return_type cross (const MatrixBase< OtherDerived > &other) const
template<typename PermutationIndex >
const FullPivLU< typename MatrixBase< Derived >::PlainObject, PermutationIndex > fullPivLu () const
template<typename PermutationIndex >
const PartialPivLU< typename MatrixBase< Derived >::PlainObject, PermutationIndex > partialPivLu () const
template<typename PermutationIndex >
const PartialPivLU< typename MatrixBase< Derived >::PlainObject, PermutationIndex > lu () const
template<typename PermutationIndexType >
const ColPivHouseholderQR< typename MatrixBase< Derived >::PlainObject, PermutationIndexType > colPivHouseholderQr () const
template<typename PermutationIndex >
const CompleteOrthogonalDecomposition< typename MatrixBase< Derived >::PlainObject, PermutationIndex > completeOrthogonalDecomposition () const
template<typename PermutationIndex >
const FullPivHouseholderQR< typename MatrixBase< Derived >::PlainObject, PermutationIndex > fullPivHouseholderQr () const
template<int Options>
BDCSVD< typename MatrixBase< Derived >::PlainObject, Options > bdcSvd () const
template<int Options>
BDCSVD< typename MatrixBase< Derived >::PlainObject, Options > bdcSvd (unsigned int computationOptions) const
template<int Options>
JacobiSVD< typename MatrixBase< Derived >::PlainObject, Options > jacobiSvd () const
template<int Options>
JacobiSVD< typename MatrixBase< Derived >::PlainObject, Options > jacobiSvd (unsigned int computationOptions) const
Public Member Functions inherited from Eigen::DenseBase< Derived >
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index outerSize () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index innerSize () const
EIGEN_DEVICE_FUNC void resize (Index newSize)
EIGEN_DEVICE_FUNC void resize (Index rows, Index cols)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const EigenBase< OtherDerived > &other)
Copies the generic expression other into *this.
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator+= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator-= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const ReturnByValue< OtherDerived > &func)
template<typename OtherDerived >
EIGEN_DEPRECATED EIGEN_DEVICE_FUNC Derived & lazyAssign (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC CommaInitializer< Derived > operator<< (const Scalar &s)
template<unsigned int Added, unsigned int Removed>
EIGEN_DEPRECATED const Derived & flagged () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC CommaInitializer< Derived > operator<< (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC TransposeReturnType transpose ()
EIGEN_DEVICE_FUNC const ConstTransposeReturnType transpose () const
EIGEN_DEVICE_FUNC void transposeInPlace ()
EIGEN_DEVICE_FUNC void fill (const Scalar &value)
EIGEN_DEVICE_FUNC Derived & setConstant (const Scalar &value)
EIGEN_DEVICE_FUNC Derived & setLinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
EIGEN_DEVICE_FUNC Derived & setLinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
EIGEN_DEVICE_FUNC Derived & setEqualSpaced (Index size, const Scalar &low, const Scalar &step)
EIGEN_DEVICE_FUNC Derived & setEqualSpaced (const Scalar &low, const Scalar &step)
EIGEN_DEVICE_FUNC Derived & setZero ()
EIGEN_DEVICE_FUNC Derived & setOnes ()
EIGEN_DEVICE_FUNC Derived & setRandom ()
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool isApprox (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const RealScalar &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isApproxToConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isZero (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isOnes (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool hasNaN () const
EIGEN_DEVICE_FUNC bool allFinite () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator*= (const Scalar &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator/= (const Scalar &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EvalReturnType eval () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void swap (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void swap (PlainObjectBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC const NestByValue< Derived > nestByValue () const
EIGEN_DEVICE_FUNC const ForceAlignedAccess< Derived > forceAlignedAccess () const
EIGEN_DEVICE_FUNC ForceAlignedAccess< Derived > forceAlignedAccess ()
template<bool Enable>
EIGEN_DEVICE_FUNC const std::conditional_t< Enable, ForceAlignedAccess< Derived >, Derived & > forceAlignedAccessIf () const
template<bool Enable>
EIGEN_DEVICE_FUNC std::conditional_t< Enable, ForceAlignedAccess< Derived >, Derived & > forceAlignedAccessIf ()
EIGEN_DEVICE_FUNC Scalar sum () const
EIGEN_DEVICE_FUNC Scalar mean () const
EIGEN_DEVICE_FUNC Scalar trace () const
EIGEN_DEVICE_FUNC Scalar prod () const
template<int NaNPropagation>
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff () const
template<int NaNPropagation>
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff () const
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff () const
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff () const
template<int NaNPropagation, typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *row, IndexType *col) const
template<int NaNPropagation, typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *row, IndexType *col) const
template<int NaNPropagation, typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *index) const
template<int NaNPropagation, typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *index) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *index) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *index) const
template<typename BinaryOp >
EIGEN_DEVICE_FUNC Scalar redux (const BinaryOp &func) const
template<typename Visitor >
EIGEN_DEVICE_FUNC void visit (Visitor &func) const
const WithFormat< Derived > format (const IOFormat &fmt) const
EIGEN_DEVICE_FUNC CoeffReturnType value () const
EIGEN_DEVICE_FUNC bool all () const
EIGEN_DEVICE_FUNC bool any () const
EIGEN_DEVICE_FUNC Index count () const
EIGEN_DEVICE_FUNC ConstRowwiseReturnType rowwise () const
EIGEN_DEVICE_FUNC RowwiseReturnType rowwise ()
EIGEN_DEVICE_FUNC ConstColwiseReturnType colwise () const
EIGEN_DEVICE_FUNC ColwiseReturnType colwise ()
template<typename ThenDerived , typename ElseDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ThenDerived >::Scalar, typename DenseBase< ElseDerived >::Scalar, Scalar >, ThenDerived, ElseDerived, Derived > select (const DenseBase< ThenDerived > &thenMatrix, const DenseBase< ElseDerived > &elseMatrix) const
template<typename ThenDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ThenDerived >::Scalar, typename DenseBase< ThenDerived >::Scalar, Scalar >, ThenDerived, typename DenseBase< ThenDerived >::ConstantReturnType, Derived > select (const DenseBase< ThenDerived > &thenMatrix, const typename DenseBase< ThenDerived >::Scalar &elseScalar) const
template<typename ElseDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ElseDerived >::Scalar, typename DenseBase< ElseDerived >::Scalar, Scalar >, typename DenseBase< ElseDerived >::ConstantReturnType, ElseDerived, Derived > select (const typename DenseBase< ElseDerived >::Scalar &thenScalar, const DenseBase< ElseDerived > &elseMatrix) const
template<int p>
RealScalar lpNorm () const
template<int RowFactor, int ColFactor>
EIGEN_DEVICE_FUNC const Replicate< Derived, RowFactor, ColFactor > replicate () const
EIGEN_DEVICE_FUNC const Replicate< Derived, Dynamic, Dynamic > replicate (Index rowFactor, Index colFactor) const
EIGEN_DEVICE_FUNC ReverseReturnType reverse ()
EIGEN_DEVICE_FUNC ConstReverseReturnType reverse () const
EIGEN_DEVICE_FUNC void reverseInPlace ()
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
const_iterator end () const
const_iterator cend () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & lazyAssign (const DenseBase< OtherDerived > &other)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (const CustomNullaryOp &func)
template<typename Derived >
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const typename NumTraits< Scalar >::Real &other, const RealScalar &prec) const
template<typename Func >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar redux (const Func &func) const
template<typename ThenDerived , typename ElseDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ThenDerived >::Scalar, typename DenseBase< ElseDerived >::Scalar, typename DenseBase< Derived >::Scalar >, ThenDerived, ElseDerived, Derived > select (const DenseBase< ThenDerived > &thenMatrix, const DenseBase< ElseDerived > &elseMatrix) const
template<typename ThenDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ThenDerived >::Scalar, typename DenseBase< ThenDerived >::Scalar, typename DenseBase< Derived >::Scalar >, ThenDerived, typename DenseBase< ThenDerived >::ConstantReturnType, Derived > select (const DenseBase< ThenDerived > &thenMatrix, const typename DenseBase< ThenDerived >::Scalar &elseScalar) const
template<typename ElseDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ElseDerived >::Scalar, typename DenseBase< ElseDerived >::Scalar, typename DenseBase< Derived >::Scalar >, typename DenseBase< ElseDerived >::ConstantReturnType, ElseDerived, Derived > select (const typename DenseBase< ElseDerived >::Scalar &thenScalar, const DenseBase< ElseDerived > &elseMatrix) const
Static Public Member Functions
static EIGEN_DEVICE_FUNC const IdentityReturnType Identity ()
static EIGEN_DEVICE_FUNC const IdentityReturnType Identity (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const BasisReturnType Unit (Index size, Index i)
static EIGEN_DEVICE_FUNC const BasisReturnType Unit (Index i)
static EIGEN_DEVICE_FUNC const BasisReturnType UnitX ()
static EIGEN_DEVICE_FUNC const BasisReturnType UnitY ()
static EIGEN_DEVICE_FUNC const BasisReturnType UnitZ ()
static EIGEN_DEVICE_FUNC const BasisReturnType UnitW ()
Static Public Member Functions inherited from Eigen::DenseBase< Derived >
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (Index rows, Index cols, const Scalar &value)
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (Index size, const Scalar &value)
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (const Scalar &value)
EIGEN_DEPRECATED static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (Sequential_t, Index size, const Scalar &low, const Scalar &high)
EIGEN_DEPRECATED static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (Sequential_t, const Scalar &low, const Scalar &high)
static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
static EIGEN_DEVICE_FUNC const RandomAccessEqualSpacedReturnType EqualSpaced (Index size, const Scalar &low, const Scalar &step)
static EIGEN_DEVICE_FUNC const RandomAccessEqualSpacedReturnType EqualSpaced (const Scalar &low, const Scalar &step)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (const CustomNullaryOp &func)
static EIGEN_DEVICE_FUNC const ZeroReturnType Zero (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const ZeroReturnType Zero (Index size)
static EIGEN_DEVICE_FUNC const ZeroReturnType Zero ()
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones (Index size)
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones ()
static const RandomReturnType Random (Index rows, Index cols)
static const RandomReturnType Random (Index size)
static const RandomReturnType Random ()
Protected Member Functions
template<typename OtherDerived >
Derived & operator+= (const ArrayBase< OtherDerived > &)
template<typename OtherDerived >
Derived & operator-= (const ArrayBase< OtherDerived > &)
Protected Member Functions inherited from Eigen::DenseBase< Derived >
constexpr EIGEN_DEVICE_FUNC DenseBase ()=default
Private Member Functions
EIGEN_DEVICE_FUNC MatrixBase (int)
EIGEN_DEVICE_FUNC MatrixBase (int, int)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC MatrixBase (const MatrixBase< OtherDerived > &)
Additional Inherited Members
Public Attributes inherited from Eigen::DenseBase< Derived >
EIGEN_DEPRECATED typedef CwiseNullaryOp< internal::linspaced_op< Scalar >, PlainObject > SequentialLinSpacedReturnType
Related Functions inherited from Eigen::DenseBase< Derived >
template<typename Derived >
std::ostream & operator<< (std::ostream &s, const DenseBase< Derived > &m)
Detailed Description
template<typename Derived>
class Eigen::MatrixBase< Derived >
Base class for all dense matrices, vectors, and expressions.
This class is the base that is inherited by all matrix, vector, and related expression types. Most of the Eigen API is contained in this class, and its base classes. Other important classes for the Eigen API are Matrix, and VectorwiseOp.
Note that some methods are defined in other modules such as the LU_Module LU module for all functions related to matrix inversions.
Template Parameters
Derived is the derived type, e.g. a matrix type, or an expression, etc.
When writing a function taking Eigen objects as argument, if you want your function to take as argument any matrix, vector, or expression, just let it take a MatrixBase argument. As an example, here is a function printFirstRow which, given a matrix, vector, or expression x, prints the first row of x.
template<typename Derived>
void printFirstRow(const Eigen::MatrixBase<Derived>& x)
{
  cout << x.row(0) << endl;
}
This class can be extended with the help of the plugin mechanism described on the page Extending MatrixBase (and other classes) by defining the preprocessor symbol EIGEN_MATRIXBASE_PLUGIN.
See also
\blank The class hierarchy
Member Typedef Documentation
AdjointReturnType
template<typename Derived > typedef std::conditional_t<NumTraits<Scalar>::IsComplex, CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>, ConstTransposeReturnType>, ConstTransposeReturnType> Eigen::MatrixBase< Derived >::AdjointReturnType
the return type of MatrixBase::adjoint()
Base
template<typename Derived > typedef DenseBase<Derived> Eigen::MatrixBase< Derived >::Base
BasisReturnType
template<typename Derived > typedef Block<const CwiseNullaryOp<internal::scalar_identity_op<Scalar>, SquareMatrixType>, internal::traits<Derived>::RowsAtCompileTime, internal::traits<Derived>::ColsAtCompileTime> Eigen::MatrixBase< Derived >::BasisReturnType
the return type of unit vectors
CoeffReturnType
template<typename Derived > typedef Base::CoeffReturnType Eigen::MatrixBase< Derived >::CoeffReturnType
ColXpr
template<typename Derived > typedef Base::ColXpr Eigen::MatrixBase< Derived >::ColXpr
ConstantReturnType
template<typename Derived > typedef CwiseNullaryOp<internal::scalar_constant_op<Scalar>, PlainObject> Eigen::MatrixBase< Derived >::ConstantReturnType
Represents a matrix with all coefficients equal to one another
ConstDiagonalReturnType
template<typename Derived > typedef Diagonal<const Derived> Eigen::MatrixBase< Derived >::ConstDiagonalReturnType
ConstStartMinusOne
template<typename Derived > typedef Block<const Derived, internal::traits<Derived>::ColsAtCompileTime == 1 ? SizeMinusOne : 1, internal::traits<Derived>::ColsAtCompileTime == 1 ? 1 : SizeMinusOne> Eigen::MatrixBase< Derived >::ConstStartMinusOne
ConstTransposeReturnType
template<typename Derived > typedef Base::ConstTransposeReturnType Eigen::MatrixBase< Derived >::ConstTransposeReturnType
DiagonalReturnType
template<typename Derived > typedef Diagonal<Derived> Eigen::MatrixBase< Derived >::DiagonalReturnType
EigenvaluesReturnType
template<typename Derived > typedef Matrix<std::complex<RealScalar>, internal::traits<Derived>::ColsAtCompileTime, 1, ColMajor> Eigen::MatrixBase< Derived >::EigenvaluesReturnType
Return type of eigenvalues()
HomogeneousReturnType
template<typename Derived > typedef Homogeneous<Derived, HomogeneousReturnTypeDirection> Eigen::MatrixBase< Derived >::HomogeneousReturnType
IdentityReturnType
template<typename Derived > typedef CwiseNullaryOp<internal::scalar_identity_op<Scalar>, PlainObject> Eigen::MatrixBase< Derived >::IdentityReturnType
the return type of identity
PacketScalar
template<typename Derived > typedef internal::packet_traits<Scalar>::type Eigen::MatrixBase< Derived >::PacketScalar
PlainObject
template<typename Derived > typedef Base::PlainObject Eigen::MatrixBase< Derived >::PlainObject
RealScalar
template<typename Derived > typedef NumTraits<Scalar>::Real Eigen::MatrixBase< Derived >::RealScalar
RowXpr
template<typename Derived > typedef Base::RowXpr Eigen::MatrixBase< Derived >::RowXpr
Scalar
template<typename Derived > typedef internal::traits<Derived>::Scalar Eigen::MatrixBase< Derived >::Scalar
SquareMatrixType
template<typename Derived > typedef Matrix<Scalar, internal::max_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime), internal::max_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime)> Eigen::MatrixBase< Derived >::SquareMatrixType
type of the equivalent square matrix
StemFunction
template<typename Derived > typedef internal::stem_function<Scalar>::type Eigen::MatrixBase< Derived >::StemFunction
StorageBaseType
template<typename Derived > typedef MatrixBase Eigen::MatrixBase< Derived >::StorageBaseType
StorageIndex
template<typename Derived > typedef internal::traits<Derived>::StorageIndex Eigen::MatrixBase< Derived >::StorageIndex
StorageKind
template<typename Derived > typedef internal::traits<Derived>::StorageKind Eigen::MatrixBase< Derived >::StorageKind
Member Enumeration Documentation
anonymous enum
template<typename Derived > anonymous enum
Enumerator
HomogeneousReturnTypeDirection
        {
     HomogeneousReturnTypeDirection =
         ColsAtCompileTime == 1 && RowsAtCompileTime == 1
             ? ((internal::traits<Derived>::Flags & RowMajorBit) == RowMajorBit ? Horizontal : Vertical)
         : ColsAtCompileTime == 1 ? Vertical
                                  : Horizontal
   };
anonymous enum
template<typename Derived > anonymous enum
Enumerator
SizeMinusOne
 { SizeMinusOne = SizeAtCompileTime == Dynamic ? Dynamic : SizeAtCompileTime - 1 };
Constructor & Destructor Documentation
MatrixBase() [1/3]
template<typename Derived > EIGEN_DEVICE_FUNC Eigen::MatrixBase< Derived >::MatrixBase (int) explicit private
MatrixBase() [2/3]
template<typename Derived > EIGEN_DEVICE_FUNC Eigen::MatrixBase< Derived >::MatrixBase (int , int) private
MatrixBase() [3/3]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Eigen::MatrixBase< Derived >::MatrixBase (const MatrixBase< OtherDerived > &) explicit private
Member Function Documentation
adjoint()
template<typename Derived > EIGEN_DEVICE_FUNC const MatrixBase< Derived >::AdjointReturnType Eigen::MatrixBase< Derived >::adjoint inline
Returns
an expression of the adjoint (i.e. conjugate transpose) of *this.
Example:
Matrix2cf m = Matrix2cf::Random();
cout << "Here is the 2x2 complex matrix m:" << endl << m << endl;
cout << "Here is the adjoint of m:" << endl << m.adjoint() << endl;
Output:
Warning
If you want to replace a matrix by its own adjoint, do NOT do this:
m = m.adjoint(); // bug!!! caused by aliasing effect
Instead, use the adjointInPlace() method:
m.adjointInPlace();
which gives Eigen good opportunities for optimization, or alternatively you can also do:
m = m.adjoint().eval();
See also
adjointInPlace(), transpose(), conjugate(), class Transpose, class internal::scalar_conjugate_op
{
   return AdjointReturnType(this->transpose());
 }
adjointInPlace()
template<typename Derived > EIGEN_DEVICE_FUNC void Eigen::MatrixBase< Derived >::adjointInPlace inline
This is the "in place" version of adjoint(): it replaces *this by its own transpose. Thus, doing
m.adjointInPlace();
has the same effect on m as doing
m = m.adjoint().eval();
and is faster and also safer because in the latter line of code, forgetting the eval() results in a bug caused by aliasing.
Notice however that this method is only useful if you want to replace a matrix by its own adjoint. If you just need the adjoint of a matrix, use adjoint().
Note
if the matrix is not square, then *this must be a resizable matrix. This excludes (non-square) fixed-size matrices, block-expressions and maps.
See also
transpose(), adjoint(), transposeInPlace()
{
   derived() = adjoint().eval();
 }
References adjoint().
applyHouseholderOnTheLeft()
template<typename Derived > template<typename EssentialPart > EIGEN_DEVICE_FUNC void Eigen::MatrixBase< Derived >::applyHouseholderOnTheLeft (const EssentialPart & essential, const Scalar & tau, Scalar * workspace)
Apply the elementary reflector H given by \(H = I - tau v v^*\) with \(v^T = [1 essential^T] \) from the left to a vector or matrix.
On input:
Parameters
essential the essential part of the vector v
tau the scaling factor of the Householder transformation
workspace a pointer to working space with at least this->cols() entries
See also
MatrixBase::makeHouseholder(), MatrixBase::makeHouseholderInPlace(), MatrixBase::applyHouseholderOnTheRight()
{
   if (rows() == 1) {
     *this *= Scalar(1) - tau;
   } else if (!numext::is_exactly_zero(tau)) {
     Map<typename internal::plain_row_type<PlainObject>::type> tmp(workspace, cols());
     Block<Derived, EssentialPart::SizeAtCompileTime, Derived::ColsAtCompileTime> bottom(derived(), 1, 0, rows() - 1,
                                                                                         cols());
     tmp.noalias() = essential.adjoint() * bottom;
     tmp += this->row(0);
     this->row(0) -= tau * tmp;
     bottom.noalias() -= tau * essential * tmp;
   }
 }
References cols, Eigen::numext::is_exactly_zero(), row(), rows, and tmp.
applyHouseholderOnTheRight()
template<typename Derived > template<typename EssentialPart > EIGEN_DEVICE_FUNC void Eigen::MatrixBase< Derived >::applyHouseholderOnTheRight (const EssentialPart & essential, const Scalar & tau, Scalar * workspace)
Apply the elementary reflector H given by \(H = I - tau v v^*\) with \(v^T = [1 essential^T] \) from the right to a vector or matrix.
On input:
Parameters
essential the essential part of the vector v
tau the scaling factor of the Householder transformation
workspace a pointer to working space with at least this->rows() entries
See also
MatrixBase::makeHouseholder(), MatrixBase::makeHouseholderInPlace(), MatrixBase::applyHouseholderOnTheLeft()
{
   if (cols() == 1) {
     *this *= Scalar(1) - tau;
   } else if (!numext::is_exactly_zero(tau)) {
     Map<typename internal::plain_col_type<PlainObject>::type> tmp(workspace, rows());
     Block<Derived, Derived::RowsAtCompileTime, EssentialPart::SizeAtCompileTime> right(derived(), 0, 1, rows(),
                                                                                        cols() - 1);
     tmp.noalias() = right * essential;
     tmp += this->col(0);
     this->col(0) -= tau * tmp;
     right.noalias() -= tau * tmp * essential.adjoint();
   }
 }
References col(), cols, Eigen::numext::is_exactly_zero(), rows, and tmp.
applyOnTheLeft() [1/2]
template<typename Derived > template<typename OtherDerived > void Eigen::MatrixBase< Derived >::applyOnTheLeft (const EigenBase< OtherDerived > & other) inline
replaces *this by other * *this.
Example:
Matrix3f A = Matrix3f::Random(3, 3), B;
B << 0, 1, 0, 0, 0, 1, 1, 0, 0;
cout << "At start, A = " << endl << A << endl;
A.applyOnTheLeft(B);
cout << "After applyOnTheLeft, A = " << endl << A << endl;
Output:
          : \verbinclude MatrixBase_applyOnTheLeft.out
  */
 template <typename Derived>
applyOnTheLeft() [2/2]
template<typename Derived > template<typename OtherScalar > EIGEN_DEVICE_FUNC void Eigen::MatrixBase< Derived >::applyOnTheLeft (Index p, Index q, const JacobiRotation< OtherScalar > & j) inline
\jacobi_module Applies the rotation in the plane j to the rows p and q of *this, i.e., it computes B = J * B, with \(B = \left (\begin{array}{cc} \text{*this.row}(p) \\ \text{*this.row}(q) \end{array} \right) \).
See also
class JacobiRotation, MatrixBase::applyOnTheRight(), internal::apply_rotation_in_the_plane()
{
   RowXpr x(this->row(p));
   RowXpr y(this->row(q));
   internal::apply_rotation_in_the_plane(x, y, j);
 }
References Eigen::internal::apply_rotation_in_the_plane(), j, row(), plotDoE::x, and y.
applyOnTheRight() [1/2]
template<typename Derived > template<typename OtherDerived > void Eigen::MatrixBase< Derived >::applyOnTheRight (const EigenBase< OtherDerived > & other) inline
replaces *this by *this * other. It is equivalent to MatrixBase::operator*=().
Example:
Matrix3f A = Matrix3f::Random(3, 3), B;
B << 0, 1, 0, 0, 0, 1, 1, 0, 0;
cout << "At start, A = " << endl << A << endl;
A *= B;
cout << "After A *= B, A = " << endl << A << endl;
A.applyOnTheRight(B);  // equivalent to A *= B
cout << "After applyOnTheRight, A = " << endl << A << endl;
Output:
          : \verbinclude MatrixBase_applyOnTheRight.out
  */
 template <typename Derived>
applyOnTheRight() [2/2]
template<typename Derived > template<typename OtherScalar > EIGEN_DEVICE_FUNC void Eigen::MatrixBase< Derived >::applyOnTheRight (Index p, Index q, const JacobiRotation< OtherScalar > & j) inline
\jacobi_module Applies the rotation in the plane j to the columns p and q of *this, i.e., it computes B = B * J with \(B = \left (\begin{array}{cc} \text{*this.col}(p) & \text{*this.col}(q) \end{array} \right) \).
See also
class JacobiRotation, MatrixBase::applyOnTheLeft(), internal::apply_rotation_in_the_plane()
{
   ColXpr x(this->col(p));
   ColXpr y(this->col(q));
   internal::apply_rotation_in_the_plane(x, y, j.transpose());
 }
References Eigen::internal::apply_rotation_in_the_plane(), col(), j, plotDoE::x, and y.
array() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ArrayWrapper<Derived> Eigen::MatrixBase< Derived >::array () inline
Returns
an Array expression of this matrix
See also
ArrayBase::matrix()
 { return ArrayWrapper<Derived>(derived()); }
array() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const ArrayWrapper<const Derived> Eigen::MatrixBase< Derived >::array () const inline
Returns
a const Array expression of this matrix
See also
ArrayBase::matrix()
{
     return ArrayWrapper<const Derived>(derived());
   }
asDiagonal()
template<typename Derived > EIGEN_DEVICE_FUNC const DiagonalWrapper< const Derived > Eigen::MatrixBase< Derived >::asDiagonal inline
Returns
a pseudo-expression of a diagonal matrix with *this as vector of diagonal coefficients
\only_for_vectors
Example:
cout << Matrix3i(Vector3i(2, 5, 6).asDiagonal()) << endl;
Output:
See also
class DiagonalWrapper, class DiagonalMatrix, diagonal(), isDiagonal()
{
   return DiagonalWrapper<const Derived>(derived());
 }
Referenced by Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >::fromPositionOrientationScale(), Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >::prescale(), Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >::scale(), and Eigen::Scaling().
asPermutation()
template<typename Derived > const PermutationWrapper< const Derived > Eigen::MatrixBase< Derived >::asPermutation
{
   return derived();
 }
asSkewSymmetric()
template<typename Derived > EIGEN_DEVICE_FUNC const SkewSymmetricWrapper< const Derived > Eigen::MatrixBase< Derived >::asSkewSymmetric inline
Returns
a pseudo-expression of a skew symmetric matrix with *this as vector of coefficients
\only_for_vectors
See also
class SkewSymmetricWrapper, class SkewSymmetricMatrix3, vector(), isSkewSymmetric()
{
   return SkewSymmetricWrapper<const Derived>(derived());
 }
bdcSvd() [1/4]
template<typename Derived > template<int Options = 0> BDCSVD<PlainObject, Options> Eigen::MatrixBase< Derived >::bdcSvd () const inline
bdcSvd() [2/4]
template<typename Derived > template<int Options> BDCSVD<typename MatrixBase<Derived>::PlainObject, Options> Eigen::MatrixBase< Derived >::bdcSvd () const
\svd_module
Returns
the singular value decomposition of *this computed by Divide & Conquer algorithm
See also
class BDCSVD
{
   return BDCSVD<PlainObject, Options>(*this);
 }
bdcSvd() [3/4]
template<typename Derived > template<int Options = 0> EIGEN_DEPRECATED BDCSVD<PlainObject, Options> Eigen::MatrixBase< Derived >::bdcSvd (unsigned int computationOptions) const inline
bdcSvd() [4/4]
template<typename Derived > template<int Options> BDCSVD<typename MatrixBase<Derived>::PlainObject, Options> Eigen::MatrixBase< Derived >::bdcSvd (unsigned int computationOptions) const
\svd_module
Returns
the singular value decomposition of *this computed by Divide & Conquer algorithm
See also
class BDCSVD
{
   return BDCSVD<PlainObject, Options>(*this, computationOptions);
 }
blueNorm()
template<typename Derived > NumTraits< typename internal::traits< Derived >::Scalar >::Real Eigen::MatrixBase< Derived >::blueNorm inline
Returns
the l2 norm of *this using the Blue's algorithm. A Portable Fortran Program to Find the Euclidean Norm of a Vector, ACM TOMS, Vol 4, Issue 1, 1978.
For architecture/scalar types without vectorization, this version is much faster than stableNorm(). Otherwise the stableNorm() is faster.
See also
norm(), stableNorm(), hypotNorm()
{
   return internal::blueNorm_impl(*this);
 }
References Eigen::internal::blueNorm_impl().
colPivHouseholderQr() [1/2]
template<typename Derived > template<typename PermutationIndex = DefaultPermutationIndex> const ColPivHouseholderQR<PlainObject, PermutationIndex> Eigen::MatrixBase< Derived >::colPivHouseholderQr () const inline
colPivHouseholderQr() [2/2]
template<typename Derived > template<typename PermutationIndexType > const ColPivHouseholderQR<typename MatrixBase<Derived>::PlainObject, PermutationIndexType> Eigen::MatrixBase< Derived >::colPivHouseholderQr () const
Returns
the column-pivoting Householder QR decomposition of *this.
See also
class ColPivHouseholderQR
{
   return ColPivHouseholderQR<PlainObject, PermutationIndexType>(eval());
 }
References eval().
completeOrthogonalDecomposition() [1/2]
template<typename Derived > template<typename PermutationIndex = DefaultPermutationIndex> const CompleteOrthogonalDecomposition<PlainObject, PermutationIndex> Eigen::MatrixBase< Derived >::completeOrthogonalDecomposition () const inline
completeOrthogonalDecomposition() [2/2]
template<typename Derived > template<typename PermutationIndex > const CompleteOrthogonalDecomposition<typename MatrixBase<Derived>::PlainObject, PermutationIndex> Eigen::MatrixBase< Derived >::completeOrthogonalDecomposition () const
Returns
the complete orthogonal decomposition of *this.
See also
class CompleteOrthogonalDecomposition
{
   return CompleteOrthogonalDecomposition<PlainObject>(eval());
 }
References eval().
computeInverseAndDetWithCheck()
template<typename Derived > template<typename ResultType > void Eigen::MatrixBase< Derived >::computeInverseAndDetWithCheck (ResultType & inverse, typename ResultType::Scalar & determinant, bool & invertible, const RealScalar & absDeterminantThreshold = NumTraits<Scalar>::dummy_precision()) const inline
\lu_module
Computation of matrix inverse and determinant, with invertibility check.
This is only for fixed-size square matrices of size up to 4x4.
Notice that it will trigger a copy of input matrix when trying to do the inverse in place.
Parameters
inverse Reference to the matrix in which to store the inverse.
determinant Reference to the variable in which to store the determinant.
invertible Reference to the bool variable in which to store whether the matrix is invertible.
absDeterminantThreshold Optional parameter controlling the invertibility check. The matrix will be declared invertible if the absolute value of its determinant is greater than this threshold.
Example:
Matrix3d m = Matrix3d::Random();
cout << "Here is the matrix m:" << endl << m << endl;
Matrix3d inverse;
bool invertible;
double determinant;
m.computeInverseAndDetWithCheck(inverse, determinant, invertible);
cout << "Its determinant is " << determinant << endl;
if (invertible) {
  cout << "It is invertible, and its inverse is:" << endl << inverse << endl;
} else {
  cout << "It is not invertible." << endl;
}
Output:
See also
inverse(), computeInverseWithCheck()
{
   // i'd love to put some static assertions there, but SFINAE means that they have no effect...
   eigen_assert(rows() == cols());
   // for 2x2, it's worth giving a chance to avoid evaluating.
   // for larger sizes, evaluating has negligible cost and limits code size.
   typedef std::conditional_t<RowsAtCompileTime == 2,
                              internal::remove_all_t<typename internal::nested_eval<Derived, 2>::type>, PlainObject>
       MatrixType;
   internal::compute_inverse_and_det_with_check<MatrixType, ResultType>::run(derived(), absDeterminantThreshold, inverse,
                                                                             determinant, invertible);
 }
References cols, determinant(), eigen_assert, inverse(), rows, and run().
computeInverseWithCheck()
template<typename Derived > template<typename ResultType > void Eigen::MatrixBase< Derived >::computeInverseWithCheck (ResultType & inverse, bool & invertible, const RealScalar & absDeterminantThreshold = NumTraits<Scalar>::dummy_precision()) const inline
\lu_module
Computation of matrix inverse, with invertibility check.
This is only for fixed-size square matrices of size up to 4x4.
Notice that it will trigger a copy of input matrix when trying to do the inverse in place.
Parameters
inverse Reference to the matrix in which to store the inverse.
invertible Reference to the bool variable in which to store whether the matrix is invertible.
absDeterminantThreshold Optional parameter controlling the invertibility check. The matrix will be declared invertible if the absolute value of its determinant is greater than this threshold.
Example:
Matrix3d m = Matrix3d::Random();
cout << "Here is the matrix m:" << endl << m << endl;
Matrix3d inverse;
bool invertible;
m.computeInverseWithCheck(inverse, invertible);
if (invertible) {
  cout << "It is invertible, and its inverse is:" << endl << inverse << endl;
} else {
  cout << "It is not invertible." << endl;
}
Output:
See also
inverse(), computeInverseAndDetWithCheck()
{
   Scalar determinant;
   // i'd love to put some static assertions there, but SFINAE means that they have no effect...
   eigen_assert(rows() == cols());
   computeInverseAndDetWithCheck(inverse, determinant, invertible, absDeterminantThreshold);
 }
cross()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC internal::cross_impl<Derived, OtherDerived>::return_type Eigen::MatrixBase< Derived >::cross (const MatrixBase< OtherDerived > & other) const inline
cwiseProduct()
template<typename Derived > template<typename OtherDerived > EIGEN_STRONG_INLINE const SparseMatrixBase<OtherDerived>::template CwiseProductDenseReturnType<Derived>::Type Eigen::MatrixBase< Derived >::cwiseProduct (const SparseMatrixBase< OtherDerived > & other) const inline
{
     return other.cwiseProduct(derived());
   }
References Eigen::SparseMatrixBase< Derived >::cwiseProduct().
determinant()
template<typename Derived > EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar Eigen::MatrixBase< Derived >::determinant inline
\lu_module
Returns
the determinant of this matrix
{
   eigen_assert(rows() == cols());
   typedef typename internal::nested_eval<Derived, Base::RowsAtCompileTime>::type Nested;
   return internal::determinant_impl<internal::remove_all_t<Nested>>::run(derived());
 }
References cols, eigen_assert, rows, and Eigen::run().
diagonal() [1/6]
template<typename Derived > EIGEN_DEVICE_FUNC Diagonal< Derived, Index_ > Eigen::MatrixBase< Derived >::diagonal inline
Returns
an expression of the main diagonal of the matrix *this
*this is not required to be square.
Example:
Matrix3i m = Matrix3i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here are the coefficients on the main diagonal of m:" << endl << m.diagonal() << endl;
Output:
See also
class Diagonal
Returns
an expression of the DiagIndex-th sub or super diagonal of the matrix *this
*this is not required to be square.
The template parameter DiagIndex represent a super diagonal if DiagIndex > 0 and a sub diagonal otherwise. DiagIndex == 0 is equivalent to the main diagonal.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here are the coefficients on the 1st super-diagonal and 2nd sub-diagonal of m:" << endl
     << m.diagonal<1>().transpose() << endl
     << m.diagonal<-2>().transpose() << endl;
Output:
See also
MatrixBase::diagonal(), class Diagonal
{
   return DiagonalReturnType(derived());
 }
diagonal() [2/6]
template<typename Derived > template<int Index> EIGEN_DEVICE_FUNC Diagonal<Derived, Index> Eigen::MatrixBase< Derived >::diagonal ()
diagonal() [3/6]
template<typename Derived > EIGEN_DEVICE_FUNC const Diagonal< const Derived, Index_ > Eigen::MatrixBase< Derived >::diagonal inline
This is the const version of diagonal().
This is the const version of diagonal<int>().
           {
   return ConstDiagonalReturnType(derived());
 }
diagonal() [4/6]
template<typename Derived > template<int Index> EIGEN_DEVICE_FUNC const Diagonal<const Derived, Index> Eigen::MatrixBase< Derived >::diagonal () const
diagonal() [5/6]
template<typename Derived > EIGEN_DEVICE_FUNC Diagonal< Derived, DynamicIndex > Eigen::MatrixBase< Derived >::diagonal (Index index) inline
Returns
an expression of the DiagIndex-th sub or super diagonal of the matrix *this
*this is not required to be square.
The template parameter DiagIndex represent a super diagonal if DiagIndex > 0 and a sub diagonal otherwise. DiagIndex == 0 is equivalent to the main diagonal.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here are the coefficients on the 1st super-diagonal and 2nd sub-diagonal of m:" << endl
     << m.diagonal(1).transpose() << endl
     << m.diagonal(-2).transpose() << endl;
Output:
See also
MatrixBase::diagonal(), class Diagonal
{
   return Diagonal<Derived, DynamicIndex>(derived(), index);
 }
diagonal() [6/6]
template<typename Derived > EIGEN_DEVICE_FUNC const Diagonal< const Derived, DynamicIndex > Eigen::MatrixBase< Derived >::diagonal (Index index) const inline
This is the const version of diagonal(Index).
{
   return Diagonal<const Derived, DynamicIndex>(derived(), index);
 }
diagonalSize()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::MatrixBase< Derived >::diagonalSize () const inline
Returns
the size of the main diagonal, which is min(rows(),cols()).
See also
rows(), cols(), SizeAtCompileTime.
 { return (numext::mini)(rows(), cols()); }
References cols, Eigen::numext::mini(), and rows.
dot() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ScalarBinaryOpTraits<typename internal::traits<Derived>::Scalar, typename internal::traits<OtherDerived>::Scalar>::ReturnType Eigen::MatrixBase< Derived >::dot (const MatrixBase< OtherDerived > & other) const
{
   return internal::dot_impl<Derived, OtherDerived>::run(derived(), other.derived());
 }
References Eigen::internal::default_inner_product_impl< Lhs, Rhs, true >::run().
dot() [2/2]
template<typename Derived > template<typename OtherDerived > Eigen::MatrixBase< Derived >::dot (const MatrixBase< OtherDerived > & other) const
Returns
the dot product of *this with other.
\only_for_vectors
Note
If the scalar type is complex numbers, then this function returns the hermitian (sesquilinear) dot product, conjugate-linear in the first variable and linear in the second variable.
See also
squaredNorm(), norm()
EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE()
template<typename Derived > typedef Eigen::MatrixBase< Derived >::EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE (ConstStartMinusOne , Scalar , quotient)
eigenvalues()
template<typename Derived > MatrixBase< Derived >::EigenvaluesReturnType Eigen::MatrixBase< Derived >::eigenvalues inline
Computes the eigenvalues of a matrix.
Returns
Column vector containing the eigenvalues.
\eigenvalues_module This function computes the eigenvalues with the help of the EigenSolver class (for real matrices) or the ComplexEigenSolver class (for complex matrices).
The eigenvalues are repeated according to their algebraic multiplicity, so there are as many eigenvalues as rows in the matrix.
The SelfAdjointView class provides a better algorithm for selfadjoint matrices.
Example:
MatrixXd ones = MatrixXd::Ones(3, 3);
VectorXcd eivals = ones.eigenvalues();
cout << "The eigenvalues of the 3x3 matrix of ones are:" << endl << eivals << endl;
Output:
See also
EigenSolver::eigenvalues(), ComplexEigenSolver::eigenvalues(), SelfAdjointView::eigenvalues()
{
   return internal::eigenvalues_selector<Derived, NumTraits<Scalar>::IsComplex>::run(derived());
 }
References Eigen::run().
forceAlignedAccess() [1/2]
template<typename Derived > ForceAlignedAccess< Derived > Eigen::MatrixBase< Derived >::forceAlignedAccess inline
Returns
an expression of *this with forced aligned access
See also
forceAlignedAccessIf(), class ForceAlignedAccess
 { return derived(); }
forceAlignedAccess() [2/2]
template<typename Derived > const ForceAlignedAccess< Derived > Eigen::MatrixBase< Derived >::forceAlignedAccess inline
Returns
an expression of *this with forced aligned access
See also
forceAlignedAccessIf(),class ForceAlignedAccess
 { return derived(); }
forceAlignedAccessIf() [1/4]
template<typename Derived > template<bool Enable> std::conditional_t<Enable, ForceAlignedAccess<Derived>, Derived&> Eigen::MatrixBase< Derived >::forceAlignedAccessIf () inline
Returns
an expression of *this with forced aligned access if Enable is true.
See also
forceAlignedAccess(), class ForceAlignedAccess
{
   return derived();  // FIXME This should not work but apparently is never used
 }
forceAlignedAccessIf() [2/4]
template<typename Derived > template<bool Enable> Derived& Eigen::MatrixBase< Derived >::forceAlignedAccessIf () inline
{
     return derived();
   }
forceAlignedAccessIf() [3/4]
template<typename Derived > template<bool Enable> add_const_on_value_type_t<std::conditional_t<Enable, ForceAlignedAccess<Derived>, Derived&> > Eigen::MatrixBase< Derived >::forceAlignedAccessIf () const inline
Returns
an expression of *this with forced aligned access if Enable is true.
See also
forceAlignedAccess(), class ForceAlignedAccess
{
   return derived();  // FIXME This should not work but apparently is never used
 }
forceAlignedAccessIf() [4/4]
template<typename Derived > template<bool Enable> const Derived& Eigen::MatrixBase< Derived >::forceAlignedAccessIf () const inline
{
     return derived();
   }
fullPivHouseholderQr() [1/2]
template<typename Derived > template<typename PermutationIndex = DefaultPermutationIndex> const FullPivHouseholderQR<PlainObject, PermutationIndex> Eigen::MatrixBase< Derived >::fullPivHouseholderQr () const inline
fullPivHouseholderQr() [2/2]
template<typename Derived > template<typename PermutationIndex > const FullPivHouseholderQR<typename MatrixBase<Derived>::PlainObject, PermutationIndex> Eigen::MatrixBase< Derived >::fullPivHouseholderQr () const
Returns
the full-pivoting Householder QR decomposition of *this.
See also
class FullPivHouseholderQR
{
   return FullPivHouseholderQR<PlainObject, PermutationIndex>(eval());
 }
References eval().
fullPivLu() [1/2]
template<typename Derived > template<typename PermutationIndex = DefaultPermutationIndex> const FullPivLU<PlainObject, PermutationIndex> Eigen::MatrixBase< Derived >::fullPivLu () const inline
fullPivLu() [2/2]
template<typename Derived > template<typename PermutationIndex > const FullPivLU<typename MatrixBase<Derived>::PlainObject, PermutationIndex> Eigen::MatrixBase< Derived >::fullPivLu () const inline
\lu_module
Returns
the full-pivoting LU decomposition of *this.
See also
class FullPivLU
           {
   return FullPivLU<PlainObject, PermutationIndex>(eval());
 }
References eval().
householderQr()
template<typename Derived > const HouseholderQR< typename MatrixBase< Derived >::PlainObject > Eigen::MatrixBase< Derived >::householderQr inline
Returns
the Householder QR decomposition of *this.
See also
class HouseholderQR
{
   return HouseholderQR<PlainObject>(eval());
 }
References eval().
hypotNorm()
template<typename Derived > NumTraits< typename internal::traits< Derived >::Scalar >::Real Eigen::MatrixBase< Derived >::hypotNorm inline
Returns
the l2 norm of *this avoiding underflow and overflow. This version use a concatenation of hypot() calls, and it is very slow.
See also
norm(), stableNorm()
{
   if (size() == 1)
     return numext::abs(coeff(0, 0));
   else
     return this->cwiseAbs().redux(internal::scalar_hypot_op<RealScalar>());
 }
References Eigen::numext::abs(), and size.
Identity() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< Derived >::IdentityReturnType Eigen::MatrixBase< Derived >::Identity static
Returns
an expression of the identity matrix (not necessarily square).
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variant taking size arguments.
Example:
cout << Matrix<double, 3, 4>::Identity() << endl;
Output:
See also
Identity(Index,Index), setIdentity(), isIdentity()
{
   EIGEN_STATIC_ASSERT_FIXED_SIZE(Derived)
   return MatrixBase<Derived>::NullaryExpr(RowsAtCompileTime, ColsAtCompileTime, internal::scalar_identity_op<Scalar>());
 }
References EIGEN_STATIC_ASSERT_FIXED_SIZE, and Eigen::DenseBase< Derived >::NullaryExpr().
Identity() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< Derived >::IdentityReturnType Eigen::MatrixBase< Derived >::Identity (Index rows, Index cols) static
Returns
an expression of the identity matrix (not necessarily square).
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Identity() should be used instead.
Example:
cout << MatrixXd::Identity(4, 3) << endl;
Output:
See also
Identity(), setIdentity(), isIdentity()
{
   return DenseBase<Derived>::NullaryExpr(rows, cols, internal::scalar_identity_op<Scalar>());
 }
References cols, Eigen::DenseBase< Derived >::NullaryExpr(), and rows.
inverse()
template<typename Derived > EIGEN_DEVICE_FUNC const Inverse< Derived > Eigen::MatrixBase< Derived >::inverse inline
\lu_module
Returns
the matrix inverse of this matrix.
For small fixed sizes up to 4x4, this method uses cofactors. In the general case, this method uses class PartialPivLU.
Note
This matrix must be invertible, otherwise the result is undefined. If you need an invertibility check, do the following:
for fixed sizes up to 4x4, use computeInverseAndDetWithCheck().
for the general case, use class FullPivLU.
Example:
Matrix3d m = Matrix3d::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Its inverse is:" << endl << m.inverse() << endl;
Output:
See also
computeInverseAndDetWithCheck()
{
   EIGEN_STATIC_ASSERT(!NumTraits<Scalar>::IsInteger, THIS_FUNCTION_IS_NOT_FOR_INTEGER_NUMERIC_TYPES)
   eigen_assert(rows() == cols());
   return Inverse<Derived>(derived());
 }
References cols, eigen_assert, EIGEN_STATIC_ASSERT, and rows.
isDiagonal()
template<typename Derived > bool Eigen::MatrixBase< Derived >::isDiagonal (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to a diagonal matrix, within the precision given by prec.
Example:
Matrix3d m = 10000 * Matrix3d::Identity();
m(0, 2) = 1;
cout << "Here's the matrix m:" << endl << m << endl;
cout << "m.isDiagonal() returns: " << m.isDiagonal() << endl;
cout << "m.isDiagonal(1e-3) returns: " << m.isDiagonal(1e-3) << endl;
Output:
See also
asDiagonal()
{
   if (cols() != rows()) return false;
   RealScalar maxAbsOnDiagonal = static_cast<RealScalar>(-1);
   for (Index j = 0; j < cols(); ++j) {
     RealScalar absOnDiagonal = numext::abs(coeff(j, j));
     if (absOnDiagonal > maxAbsOnDiagonal) maxAbsOnDiagonal = absOnDiagonal;
   }
   for (Index j = 0; j < cols(); ++j)
     for (Index i = 0; i < j; ++i) {
       if (!internal::isMuchSmallerThan(coeff(i, j), maxAbsOnDiagonal, prec)) return false;
       if (!internal::isMuchSmallerThan(coeff(j, i), maxAbsOnDiagonal, prec)) return false;
     }
   return true;
 }
References Eigen::numext::abs(), cols, i, Eigen::internal::isMuchSmallerThan(), j, and rows.
isIdentity()
template<typename Derived > bool Eigen::MatrixBase< Derived >::isIdentity (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to the identity matrix (not necessarily square), within the precision given by prec.
Example:
Matrix3d m = Matrix3d::Identity();
m(0, 2) = 1e-4;
cout << "Here's the matrix m:" << endl << m << endl;
cout << "m.isIdentity() returns: " << m.isIdentity() << endl;
cout << "m.isIdentity(1e-3) returns: " << m.isIdentity(1e-3) << endl;
Output:
See also
class CwiseNullaryOp, Identity(), Identity(Index,Index), setIdentity()
{
   typename internal::nested_eval<Derived, 1>::type self(derived());
   for (Index j = 0; j < cols(); ++j) {
     for (Index i = 0; i < rows(); ++i) {
       if (i == j) {
         if (!internal::isApprox(self.coeff(i, j), static_cast<Scalar>(1), prec)) return false;
       } else {
         if (!internal::isMuchSmallerThan(self.coeff(i, j), static_cast<RealScalar>(1), prec)) return false;
       }
     }
   }
   return true;
 }
References cols, i, Eigen::internal::isApprox(), Eigen::internal::isMuchSmallerThan(), j, and rows.
isLowerTriangular()
template<typename Derived > bool Eigen::MatrixBase< Derived >::isLowerTriangular (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to a lower triangular matrix, within the precision given by prec.
See also
isUpperTriangular()
{
   RealScalar maxAbsOnLowerPart = static_cast<RealScalar>(-1);
   for (Index j = 0; j < cols(); ++j)
     for (Index i = j; i < rows(); ++i) {
       RealScalar absValue = numext::abs(coeff(i, j));
       if (absValue > maxAbsOnLowerPart) maxAbsOnLowerPart = absValue;
     }
   RealScalar threshold = maxAbsOnLowerPart * prec;
   for (Index j = 1; j < cols(); ++j) {
     Index maxi = numext::mini(j, rows() - 1);
     for (Index i = 0; i < maxi; ++i)
       if (numext::abs(coeff(i, j)) > threshold) return false;
   }
   return true;
 }
References Eigen::numext::abs(), cols, i, j, Eigen::numext::maxi(), Eigen::numext::mini(), and rows.
isOrthogonal()
template<typename Derived > template<typename OtherDerived > bool Eigen::MatrixBase< Derived >::isOrthogonal (const MatrixBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately orthogonal to other, within the precision given by prec.
Example:
Vector3d v(1, 0, 0);
Vector3d w(1e-4, 0, 1);
cout << "Here's the vector v:" << endl << v << endl;
cout << "Here's the vector w:" << endl << w << endl;
cout << "v.isOrthogonal(w) returns: " << v.isOrthogonal(w) << endl;
cout << "v.isOrthogonal(w,1e-3) returns: " << v.isOrthogonal(w, 1e-3) << endl;
Output:
{
   typename internal::nested_eval<Derived, 2>::type nested(derived());
   typename internal::nested_eval<OtherDerived, 2>::type otherNested(other.derived());
   return numext::abs2(nested.dot(otherNested)) <= prec * prec * nested.squaredNorm() * otherNested.squaredNorm();
 }
References Eigen::numext::abs2().
isSkewSymmetric()
template<typename Derived > bool Eigen::MatrixBase< Derived >::isSkewSymmetric (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to a skew symmetric matrix, within the precision given by prec.
{
   if (cols() != rows()) return false;
   return (this->transpose() + *this).isZero(prec);
 }
References cols, rows, and anonymous_namespace{skew_symmetric_matrix3.cpp}::transpose().
isUnitary()
template<typename Derived > bool Eigen::MatrixBase< Derived >::isUnitary (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately an unitary matrix, within the precision given by prec. In the case where the Scalar type is real numbers, a unitary matrix is an orthogonal matrix, whence the name.
Note
This can be used to check whether a family of vectors forms an orthonormal basis. Indeed, m.isUnitary() returns true if and only if the columns (equivalently, the rows) of m form an orthonormal basis.
Example:
Matrix3d m = Matrix3d::Identity();
m(0, 2) = 1e-4;
cout << "Here's the matrix m:" << endl << m << endl;
cout << "m.isUnitary() returns: " << m.isUnitary() << endl;
cout << "m.isUnitary(1e-3) returns: " << m.isUnitary(1e-3) << endl;
Output:
{
   typename internal::nested_eval<Derived, 1>::type self(derived());
   for (Index i = 0; i < cols(); ++i) {
     if (!internal::isApprox(self.col(i).squaredNorm(), static_cast<RealScalar>(1), prec)) return false;
     for (Index j = 0; j < i; ++j)
       if (!internal::isMuchSmallerThan(self.col(i).dot(self.col(j)), static_cast<Scalar>(1), prec)) return false;
   }
   return true;
 }
References col(), cols, dot(), i, Eigen::internal::isApprox(), Eigen::internal::isMuchSmallerThan(), and j.
isUpperTriangular()
template<typename Derived > bool Eigen::MatrixBase< Derived >::isUpperTriangular (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to an upper triangular matrix, within the precision given by prec.
See also
isLowerTriangular()
{
   RealScalar maxAbsOnUpperPart = static_cast<RealScalar>(-1);
   for (Index j = 0; j < cols(); ++j) {
     Index maxi = numext::mini(j, rows() - 1);
     for (Index i = 0; i <= maxi; ++i) {
       RealScalar absValue = numext::abs(coeff(i, j));
       if (absValue > maxAbsOnUpperPart) maxAbsOnUpperPart = absValue;
     }
   }
   RealScalar threshold = maxAbsOnUpperPart * prec;
   for (Index j = 0; j < cols(); ++j)
     for (Index i = j + 1; i < rows(); ++i)
       if (numext::abs(coeff(i, j)) > threshold) return false;
   return true;
 }
References Eigen::numext::abs(), cols, i, j, Eigen::numext::maxi(), Eigen::numext::mini(), and rows.
jacobiSvd() [1/4]
template<typename Derived > template<int Options = 0> JacobiSVD<PlainObject, Options> Eigen::MatrixBase< Derived >::jacobiSvd () const inline
jacobiSvd() [2/4]
template<typename Derived > template<int Options> JacobiSVD<typename MatrixBase<Derived>::PlainObject, Options> Eigen::MatrixBase< Derived >::jacobiSvd () const
\svd_module
Returns
the singular value decomposition of *this computed by two-sided Jacobi transformations.
See also
class JacobiSVD
{
   return JacobiSVD<PlainObject, Options>(*this);
 }
jacobiSvd() [3/4]
template<typename Derived > template<int Options = 0> EIGEN_DEPRECATED JacobiSVD<PlainObject, Options> Eigen::MatrixBase< Derived >::jacobiSvd (unsigned int computationOptions) const inline
jacobiSvd() [4/4]
template<typename Derived > template<int Options> JacobiSVD<typename MatrixBase<Derived>::PlainObject, Options> Eigen::MatrixBase< Derived >::jacobiSvd (unsigned int computationOptions) const
{
   return JacobiSVD<PlainObject, Options>(*this, computationOptions);
 }
lazyProduct() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Product<Derived, OtherDerived, LazyProduct> Eigen::MatrixBase< Derived >::lazyProduct (const MatrixBase< OtherDerived > & other) const
Returns
an expression of the matrix product of *this and other without implicit evaluation.
The returned product will behave like any other expressions: the coefficients of the product will be computed once at a time as requested. This might be useful in some extremely rare cases when only a small and no coherent fraction of the result's coefficients have to be computed.
Warning
This version of the matrix product can be much much slower. So use it only if you know what you are doing and that you measured a true speed improvement.
See also
operator*(const MatrixBase&)
{
   enum {
     ProductIsValid = Derived::ColsAtCompileTime == Dynamic || OtherDerived::RowsAtCompileTime == Dynamic ||
                      int(Derived::ColsAtCompileTime) == int(OtherDerived::RowsAtCompileTime),
     AreVectors = Derived::IsVectorAtCompileTime && OtherDerived::IsVectorAtCompileTime,
     SameSizes = EIGEN_PREDICATE_SAME_MATRIX_SIZE(Derived, OtherDerived)
   };
   // note to the lost user:
   //    * for a dot product use: v1.dot(v2)
   //    * for a coeff-wise product use: v1.cwiseProduct(v2)
   EIGEN_STATIC_ASSERT(
       ProductIsValid || !(AreVectors && SameSizes),
       INVALID_VECTOR_VECTOR_PRODUCT__IF_YOU_WANTED_A_DOT_OR_COEFF_WISE_PRODUCT_YOU_MUST_USE_THE_EXPLICIT_FUNCTIONS)
   EIGEN_STATIC_ASSERT(ProductIsValid || !(SameSizes && !AreVectors),
                       INVALID_MATRIX_PRODUCT__IF_YOU_WANTED_A_COEFF_WISE_PRODUCT_YOU_MUST_USE_THE_EXPLICIT_FUNCTION)
   EIGEN_STATIC_ASSERT(ProductIsValid || SameSizes, INVALID_MATRIX_PRODUCT)
   return Product<Derived, OtherDerived, LazyProduct>(derived(), other.derived());
 }
References Eigen::Dynamic, EIGEN_PREDICATE_SAME_MATRIX_SIZE, EIGEN_STATIC_ASSERT, and int().
lazyProduct() [2/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC const Product<Derived, OtherDerived, LazyProduct> Eigen::MatrixBase< Derived >::lazyProduct (const MatrixBase< OtherDerived > & other) const
ldlt()
template<typename Derived > const LDLT< typename MatrixBase< Derived >::PlainObject > Eigen::MatrixBase< Derived >::ldlt inline
\cholesky_module
Returns
the Cholesky decomposition with full pivoting without square root of *this
See also
SelfAdjointView::ldlt()
{
   return LDLT<PlainObject>(derived());
 }
References Eigen::SolverBase< LDLT< MatrixType_, UpLo_ > >::derived().
llt()
template<typename Derived > const LLT< typename MatrixBase< Derived >::PlainObject > Eigen::MatrixBase< Derived >::llt inline
\cholesky_module
Returns
the LLT decomposition of *this
See also
SelfAdjointView::llt()
{
   return LLT<PlainObject>(derived());
 }
References Eigen::SolverBase< LLT< MatrixType_, UpLo_ > >::derived().
lpNorm() [1/2]
template<typename Derived > template<int p> EIGEN_DEVICE_FUNC NumTraits<typename internal::traits<Derived>::Scalar>::Real Eigen::MatrixBase< Derived >::lpNorm () const inline
Returns
the coefficient-wise \(\ell^p \) norm of *this, that is, returns the p-th root of the sum of the p-th powers of the absolute values of the coefficients of *this. If p is the special value Eigen::Infinity, this function returns the \(\ell^\infty \) norm, that is the maximum of the absolute values of the coefficients of *this.
In all cases, if *this is empty, then the value 0 is returned.
Note
For matrices, this function does not compute the operator-norm. That is, if *this is a matrix, then its coefficients are interpreted as a 1D vector. Nonetheless, you can easily compute the 1-norm and \(\infty\)-norm matrix operator norms using partial reductions .
See also
norm()
{
   return internal::lpNorm_selector<Derived, p>::run(*this);
 }
References Eigen::internal::lpNorm_selector< Derived, p >::run().
lpNorm() [2/2]
template<typename Derived > template<int p> EIGEN_DEVICE_FUNC RealScalar Eigen::MatrixBase< Derived >::lpNorm () const
lu() [1/2]
template<typename Derived > template<typename PermutationIndex = DefaultPermutationIndex> const PartialPivLU<PlainObject, PermutationIndex> Eigen::MatrixBase< Derived >::lu () const inline
lu() [2/2]
template<typename Derived > template<typename PermutationIndex > const PartialPivLU<typename MatrixBase<Derived>::PlainObject, PermutationIndex> Eigen::MatrixBase< Derived >::lu () const inline
\lu_module
Synonym of partialPivLu().
Returns
the partial-pivoting LU decomposition of *this.
See also
class PartialPivLU
{
   return PartialPivLU<PlainObject, PermutationIndex>(eval());
 }
References eval().
makeHouseholder()
template<typename Derived > template<typename EssentialPart > EIGEN_DEVICE_FUNC void Eigen::MatrixBase< Derived >::makeHouseholder (EssentialPart & essential, Scalar & tau, RealScalar & beta) const
Computes the elementary reflector H such that: \(H *this = [ beta 0 ... 0]^T \) where the transformation H is: \(H = I - tau v v^*\) and the vector v is: \(v^T = [1 essential^T] \)
On output:
Parameters
essential the essential part of the vector v
tau the scaling factor of the Householder transformation
beta the result of H * *this
See also
MatrixBase::makeHouseholderInPlace(), MatrixBase::applyHouseholderOnTheLeft(), MatrixBase::applyHouseholderOnTheRight()
{
   using numext::conj;
   using numext::sqrt;
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(EssentialPart)
   VectorBlock<const Derived, EssentialPart::SizeAtCompileTime> tail(derived(), 1, size() - 1);
   RealScalar tailSqNorm = size() == 1 ? RealScalar(0) : tail.squaredNorm();
   Scalar c0 = coeff(0);
   const RealScalar tol = (std::numeric_limits<RealScalar>::min)();
   if (tailSqNorm <= tol && numext::abs2(numext::imag(c0)) <= tol) {
     tau = RealScalar(0);
     beta = numext::real(c0);
     essential.setZero();
   } else {
     beta = sqrt(numext::abs2(c0) + tailSqNorm);
     if (numext::real(c0) >= RealScalar(0)) beta = -beta;
     essential = tail / (c0 - beta);
     tau = conj((beta - c0) / beta);
   }
 }
References Eigen::numext::abs2(), beta, conj(), Eigen::conj(), EIGEN_STATIC_ASSERT_VECTOR_ONLY, imag(), min, size, sqrt(), and Eigen::numext::sqrt().
makeHouseholderInPlace()
template<typename Derived > EIGEN_DEVICE_FUNC void Eigen::MatrixBase< Derived >::makeHouseholderInPlace (Scalar & tau, RealScalar & beta)
Computes the elementary reflector H such that: \(H *this = [ beta 0 ... 0]^T \) where the transformation H is: \(H = I - tau v v^*\) and the vector v is: \(v^T = [1 essential^T] \)
The essential part of the vector v is stored in *this.
On output:
Parameters
tau the scaling factor of the Householder transformation
beta the result of H * *this
See also
MatrixBase::makeHouseholder(), MatrixBase::applyHouseholderOnTheLeft(), MatrixBase::applyHouseholderOnTheRight()
{
   VectorBlock<Derived, internal::decrement_size<Base::SizeAtCompileTime>::ret> essentialPart(derived(), 1, size() - 1);
   makeHouseholder(essentialPart, tau, beta);
 }
References beta, and size.
matrix() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC MatrixBase<Derived>& Eigen::MatrixBase< Derived >::matrix () inline
 { return *this; }
matrix() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC const MatrixBase<Derived>& Eigen::MatrixBase< Derived >::matrix () const inline
 { return *this; }
matrixFunction()
template<typename Derived > const MatrixFunctionReturnValue< Derived > Eigen::MatrixBase< Derived >::matrixFunction (StemFunction f) const
Helper function for the unsupported MatrixFunctions module.
{
   eigen_assert(rows() == cols());
   return MatrixFunctionReturnValue<Derived>(derived(), f);
 }
References cols, eigen_assert, f(), and rows.
noalias()
template<typename Derived > NoAlias< Derived, MatrixBase > EIGEN_DEVICE_FUNC Eigen::MatrixBase< Derived >::noalias
Returns
a pseudo expression of *this with an operator= assuming no aliasing between *this and the source expression.
More precisely, noalias() allows to bypass the EvalBeforeAssignBit flag. Currently, even though several expressions may alias, only product expressions have this flag. Therefore, noalias() is only useful when the source expression contains a matrix product.
Here are some examples where noalias is useful:
D.noalias()  = A * B;
D.noalias() += A.transpose() * B;
D.noalias() -= 2 * A * B.adjoint();
On the other hand the following example will lead to a wrong result:
A.noalias() = A * B;
because the result matrix A is also an operand of the matrix product. Therefore, there is no alternative than evaluating A * B in a temporary, that is the default behavior when you write:
A = A * B;
See also
class NoAlias
{
   return NoAlias<Derived, Eigen::MatrixBase>(derived());
 }
norm()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE NumTraits< typename internal::traits< Derived >::Scalar >::Real Eigen::MatrixBase< Derived >::norm
Returns
, for vectors, the l2 norm of *this, and for matrices the Frobenius norm. In both cases, it consists in the square root of the sum of the square of all the matrix entries. For vectors, this is also equals to the square root of the dot product of *this with itself.
See also
lpNorm(), dot(), squaredNorm()
{
   return numext::sqrt(squaredNorm());
 }
References Eigen::numext::sqrt().
normalize()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::MatrixBase< Derived >::normalize
Normalizes the vector, i.e. divides it by its own norm.
\only_for_vectors
Warning
If the input vector is too small (i.e., this->norm()==0), then *this is left unchanged.
See also
norm(), normalized()
{
   RealScalar z = squaredNorm();
   // NOTE: after extensive benchmarking, this conditional does not impact performance, at least on recent x86 CPU
   if (z > RealScalar(0)) derived() /= numext::sqrt(z);
 }
References Eigen::numext::sqrt().
normalized()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< Derived >::PlainObject Eigen::MatrixBase< Derived >::normalized
Returns
an expression of the quotient of *this by its own norm.
Warning
If the input vector is too small (i.e., this->norm()==0), then this function returns a copy of the input.
\only_for_vectors
See also
norm(), normalize()
           {
   typedef typename internal::nested_eval<Derived, 2>::type Nested_;
   Nested_ n(derived());
   RealScalar z = n.squaredNorm();
   // NOTE: after extensive benchmarking, this conditional does not impact performance, at least on recent x86 CPU
   if (z > RealScalar(0))
     return n / numext::sqrt(z);
   else
     return n;
 }
References n, and Eigen::numext::sqrt().
operator!=()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC bool Eigen::MatrixBase< Derived >::operator!= (const MatrixBase< OtherDerived > & other) const inline
Returns
true if at least one pair of coefficients of *this and other are not exactly equal to each other.
Warning
When using floating point scalar values you probably should rather use a fuzzy comparison such as isApprox()
See also
isApprox(), operator==
{
     return !(*this == other);
   }
operator*() [1/4]
template<typename Derived > template<typename DiagonalDerived > EIGEN_DEVICE_FUNC const Product< Derived, DiagonalDerived, LazyProduct > Eigen::MatrixBase< Derived >::operator* (const DiagonalBase< DiagonalDerived > & a_diagonal) const inline
Returns
the diagonal matrix product of *this by the diagonal matrix diagonal.
{
   return Product<Derived, DiagonalDerived, LazyProduct>(derived(), a_diagonal.derived());
 }
References Eigen::DiagonalBase< Derived >::derived().
operator*() [2/4]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Product<Derived, OtherDerived> Eigen::MatrixBase< Derived >::operator* (const MatrixBase< OtherDerived > & other) const
Returns
the matrix product of *this and other.
Note
If instead of the matrix product you want the coefficient-wise product, see Cwise::operator*().
See also
lazyProduct(), operator*=(const MatrixBase&), Cwise::operator*()
{
   // A note regarding the function declaration: In MSVC, this function will sometimes
   // not be inlined since DenseStorage is an unwindable object for dynamic
   // matrices and product types are holding a member to store the result.
   // Thus it does not help tagging this function with EIGEN_STRONG_INLINE.
   enum {
     ProductIsValid = Derived::ColsAtCompileTime == Dynamic || OtherDerived::RowsAtCompileTime == Dynamic ||
                      int(Derived::ColsAtCompileTime) == int(OtherDerived::RowsAtCompileTime),
     AreVectors = Derived::IsVectorAtCompileTime && OtherDerived::IsVectorAtCompileTime,
     SameSizes = EIGEN_PREDICATE_SAME_MATRIX_SIZE(Derived, OtherDerived)
   };
   // note to the lost user:
   //    * for a dot product use: v1.dot(v2)
   //    * for a coeff-wise product use: v1.cwiseProduct(v2)
   EIGEN_STATIC_ASSERT(
       ProductIsValid || !(AreVectors && SameSizes),
       INVALID_VECTOR_VECTOR_PRODUCT__IF_YOU_WANTED_A_DOT_OR_COEFF_WISE_PRODUCT_YOU_MUST_USE_THE_EXPLICIT_FUNCTIONS)
   EIGEN_STATIC_ASSERT(ProductIsValid || !(SameSizes && !AreVectors),
                       INVALID_MATRIX_PRODUCT__IF_YOU_WANTED_A_COEFF_WISE_PRODUCT_YOU_MUST_USE_THE_EXPLICIT_FUNCTION)
   EIGEN_STATIC_ASSERT(ProductIsValid || SameSizes, INVALID_MATRIX_PRODUCT)
 #ifdef EIGEN_DEBUG_PRODUCT
   internal::product_type<Derived, OtherDerived>::debug();
 #endif
   return Product<Derived, OtherDerived>(derived(), other.derived());
 }
References Eigen::Dynamic, EIGEN_PREDICATE_SAME_MATRIX_SIZE, EIGEN_STATIC_ASSERT, and int().
operator*() [3/4]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC const Product<Derived, OtherDerived> Eigen::MatrixBase< Derived >::operator* (const MatrixBase< OtherDerived > & other) const
operator*() [4/4]
template<typename Derived > template<typename SkewDerived > EIGEN_DEVICE_FUNC const Product< Derived, SkewDerived, LazyProduct > Eigen::MatrixBase< Derived >::operator* (const SkewSymmetricBase< SkewDerived > & skew) const inline
Returns
the matrix product of *this by the skew symmetric matrix \skew.
{
   return Product<Derived, SkewDerived, LazyProduct>(derived(), skew.derived());
 }
References Eigen::SkewSymmetricBase< Derived >::derived().
operator*=()
template<typename Derived > template<typename OtherDerived > Derived & Eigen::MatrixBase< Derived >::operator*= (const EigenBase< OtherDerived > & other) inline
replaces *this by *this * other.
Returns
a reference to *this
Example:
Matrix3f A = Matrix3f::Random(3, 3), B;
B << 0, 1, 0, 0, 0, 1, 1, 0, 0;
cout << "At start, A = " << endl << A << endl;
A *= B;
cout << "After A *= B, A = " << endl << A << endl;
A.applyOnTheRight(B);  // equivalent to A *= B
cout << "After applyOnTheRight, A = " << endl << A << endl;
Output:
          : \verbinclude MatrixBase_applyOnTheRight.out
  */
 template <typename Derived>
 template <typename OtherDerived>
operator+=() [1/2]
template<typename Derived > template<typename OtherDerived > Derived& Eigen::MatrixBase< Derived >::operator+= (const ArrayBase< OtherDerived > &) inline protected
           :
   // mixing arrays and matrices is not legal
   template <typename OtherDerived>
   Derived& operator+=(const ArrayBase<OtherDerived>&) {
References EIGEN_STATIC_ASSERT.
operator+=() [2/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::MatrixBase< Derived >::operator+= (const MatrixBase< OtherDerived > & other)
replaces *this by *this + other.
Returns
a reference to *this
{
   call_assignment(derived(), other.derived(), internal::add_assign_op<Scalar, typename OtherDerived::Scalar>());
   return derived();
 }
References Eigen::internal::call_assignment().
operator-=() [1/2]
template<typename Derived > template<typename OtherDerived > Derived& Eigen::MatrixBase< Derived >::operator-= (const ArrayBase< OtherDerived > &) inline protected
{
operator-=() [2/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::MatrixBase< Derived >::operator-= (const MatrixBase< OtherDerived > & other)
replaces *this by *this - other.
Returns
a reference to *this
{
   call_assignment(derived(), other.derived(), internal::sub_assign_op<Scalar, typename OtherDerived::Scalar>());
   return derived();
 }
References Eigen::internal::call_assignment().
operator=() [1/6]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::MatrixBase< Derived >::operator= (const DenseBase< OtherDerived > & other)
{
   internal::call_assignment(derived(), other.derived());
   return derived();
 }
References Eigen::internal::call_assignment().
operator=() [2/6]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived& Eigen::MatrixBase< Derived >::operator= (const EigenBase< OtherDerived > & other)
{
   internal::call_assignment(derived(), other.derived());
   return derived();
 }
References Eigen::internal::call_assignment(), and Eigen::EigenBase< Derived >::derived().
operator=() [3/6]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived& Eigen::MatrixBase< Derived >::operator= (const EigenBase< OtherDerived > & other)
operator=() [4/6]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::MatrixBase< Derived >::operator= (const MatrixBase< Derived > & other)
Special case of the template operator=, in order to prevent the compiler from generating a default operator= (issue hit with g++ 4.1)
{
   internal::call_assignment(derived(), other.derived());
   return derived();
 }
References Eigen::internal::call_assignment().
operator=() [5/6]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived& Eigen::MatrixBase< Derived >::operator= (const ReturnByValue< OtherDerived > & other)
{
   other.derived().evalTo(derived());
   return derived();
 }
operator=() [6/6]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived& Eigen::MatrixBase< Derived >::operator= (const ReturnByValue< OtherDerived > & other)
operator==()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC bool Eigen::MatrixBase< Derived >::operator== (const MatrixBase< OtherDerived > & other) const inline
Returns
true if each coefficients of *this and other are all exactly equal.
Warning
When using floating point scalar values you probably should rather use a fuzzy comparison such as isApprox()
See also
isApprox(), operator!=
{
     return (this->rows() == other.rows()) && (this->cols() == other.cols()) && cwiseEqual(other).all();
   }
References cols, and rows.
operatorNorm()
template<typename Derived > MatrixBase< Derived >::RealScalar Eigen::MatrixBase< Derived >::operatorNorm inline
Computes the L2 operator norm.
Returns
Operator norm of the matrix.
\eigenvalues_module This function computes the L2 operator norm of a matrix, which is also known as the spectral norm. The norm of a matrix \(A \) is defined to be
\[ \|A\|_2 = \max_x \frac{\|Ax\|_2}{\|x\|_2} \]
where the maximum is over all vectors and the norm on the right is the Euclidean vector norm. The norm equals the largest singular value, which is the square root of the largest eigenvalue of the positive semi-definite matrix \(A^*A \).
The current implementation uses the eigenvalues of \(A^*A \), as computed by SelfAdjointView::eigenvalues(), to compute the operator norm of a matrix. The SelfAdjointView class provides a better algorithm for selfadjoint matrices.
Example:
MatrixXd ones = MatrixXd::Ones(3, 3);
cout << "The operator norm of the 3x3 matrix of ones is " << ones.operatorNorm() << endl;
Output:
See also
SelfAdjointView::eigenvalues(), SelfAdjointView::operatorNorm()
{
   using std::sqrt;
   typename Derived::PlainObject m_eval(derived());
   // FIXME if it is really guaranteed that the eigenvalues are already sorted,
   // then we don't need to compute a maxCoeff() here, comparing the 1st and last ones is enough.
   return sqrt((m_eval * m_eval.adjoint()).eval().template selfadjointView<Lower>().eigenvalues().maxCoeff());
 }
References sqrt().
partialPivLu() [1/2]
template<typename Derived > template<typename PermutationIndex = DefaultPermutationIndex> const PartialPivLU<PlainObject, PermutationIndex> Eigen::MatrixBase< Derived >::partialPivLu () const inline
partialPivLu() [2/2]
template<typename Derived > template<typename PermutationIndex > const PartialPivLU<typename MatrixBase<Derived>::PlainObject, PermutationIndex> Eigen::MatrixBase< Derived >::partialPivLu () const inline
\lu_module
Returns
the partial-pivoting LU decomposition of *this.
See also
class PartialPivLU
{
   return PartialPivLU<PlainObject, PermutationIndex>(eval());
 }
References eval().
selfadjointView() [1/4]
template<typename Derived > template<unsigned int UpLo> EIGEN_DEVICE_FUNC SelfAdjointViewReturnType<UpLo>::Type Eigen::MatrixBase< Derived >::selfadjointView ()
selfadjointView() [2/4]
template<typename Derived > template<unsigned int UpLo> EIGEN_DEVICE_FUNC MatrixBase<Derived>::template SelfAdjointViewReturnType<UpLo>::Type Eigen::MatrixBase< Derived >::selfadjointView ()
Returns
an expression of a symmetric/self-adjoint view extracted from the upper or lower triangular part of the current matrix
The parameter UpLo can be either Upper or Lower
Example:
Matrix3i m = Matrix3i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the symmetric matrix extracted from the upper part of m:" << endl
     << Matrix3i(m.selfadjointView<Upper>()) << endl;
cout << "Here is the symmetric matrix extracted from the lower part of m:" << endl
     << Matrix3i(m.selfadjointView<Lower>()) << endl;
Output:
See also
class SelfAdjointView
{
   return typename SelfAdjointViewReturnType<UpLo>::Type(derived());
 }
selfadjointView() [3/4]
template<typename Derived > template<unsigned int UpLo> EIGEN_DEVICE_FUNC ConstSelfAdjointViewReturnType<UpLo>::Type Eigen::MatrixBase< Derived >::selfadjointView () const
selfadjointView() [4/4]
template<typename Derived > template<unsigned int UpLo> EIGEN_DEVICE_FUNC MatrixBase<Derived>::template ConstSelfAdjointViewReturnType<UpLo>::Type Eigen::MatrixBase< Derived >::selfadjointView () const
This is the const version of MatrixBase::selfadjointView()
{
   return typename ConstSelfAdjointViewReturnType<UpLo>::Type(derived());
 }
setIdentity() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::MatrixBase< Derived >::setIdentity
Writes the identity expression (not necessarily square) into *this.
Example:
Matrix4i m = Matrix4i::Zero();
m.block<3, 3>(1, 0).setIdentity();
cout << m << endl;
Output:
See also
class CwiseNullaryOp, Identity(), Identity(Index,Index), isIdentity()
{
   return internal::setIdentity_impl<Derived>::run(derived());
 }
References Eigen::internal::setIdentity_impl< Derived, Big >::run().
setIdentity() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::MatrixBase< Derived >::setIdentity (Index rows, Index cols)
Resizes to the given size, and writes the identity expression (not necessarily square) into *this.
Parameters
rows the new number of rows
cols the new number of columns
Example:
MatrixXf m;
m.setIdentity(3, 3);
cout << m << endl;
Output:
See also
MatrixBase::setIdentity(), class CwiseNullaryOp, MatrixBase::Identity()
{
   derived().resize(rows, cols);
   return setIdentity();
 }
References cols, rows, and setIdentity().
setUnit() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::MatrixBase< Derived >::setUnit (Index i)
Set the coefficients of *this to the i-th unit (basis) vector.
Parameters
i index of the unique coefficient to be set to 1
\only_for_vectors
See also
MatrixBase::setIdentity(), class CwiseNullaryOp, MatrixBase::Unit(Index,Index)
{
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived);
   eigen_assert(i < size());
   derived().setZero();
   derived().coeffRef(i) = Scalar(1);
   return derived();
 }
References eigen_assert, EIGEN_STATIC_ASSERT_VECTOR_ONLY, i, and size.
setUnit() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::MatrixBase< Derived >::setUnit (Index newSize, Index i)
Resizes to the given newSize, and writes the i-th unit (basis) vector into *this.
Parameters
newSize the new size of the vector
i index of the unique coefficient to be set to 1
\only_for_vectors
See also
MatrixBase::setIdentity(), class CwiseNullaryOp, MatrixBase::Unit(Index,Index)
{
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived);
   eigen_assert(i < newSize);
   derived().resize(newSize);
   return setUnit(i);
 }
References eigen_assert, EIGEN_STATIC_ASSERT_VECTOR_ONLY, and i.
squaredNorm()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE NumTraits< typename internal::traits< Derived >::Scalar >::Real Eigen::MatrixBase< Derived >::squaredNorm
Returns
, for vectors, the squared l2 norm of *this, and for matrices the squared Frobenius norm. In both cases, it consists in the sum of the square of all the matrix entries. For vectors, this is also equals to the dot product of *this with itself.
See also
dot(), norm(), lpNorm()
{
   return internal::squared_norm_impl<Derived>::run(derived());
 }
References Eigen::internal::squared_norm_impl< Derived, Scalar >::run().
stableNorm()
template<typename Derived > NumTraits< typename internal::traits< Derived >::Scalar >::Real Eigen::MatrixBase< Derived >::stableNorm inline
Returns
the l2 norm of *this avoiding underflow and overflow. This version use a blockwise two passes algorithm: 1 - find the absolute largest coefficient s 2 - compute \(s \Vert \frac{*this}{s} \Vert \) in a standard way
For architecture/scalar types supporting vectorization, this version is faster than blueNorm(). Otherwise the blueNorm() is much faster.
See also
norm(), blueNorm(), hypotNorm()
{
   return internal::stable_norm_impl(derived());
 }
References Eigen::internal::stable_norm_impl().
stableNormalize()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::MatrixBase< Derived >::stableNormalize
Normalizes the vector while avoid underflow and overflow
\only_for_vectors
This method is analogue to the normalize() method, but it reduces the risk of underflow and overflow when computing the norm.
Warning
If the input vector is too small (i.e., this->norm()==0), then *this is left unchanged.
See also
stableNorm(), stableNormalized(), normalize()
{
   RealScalar w = cwiseAbs().maxCoeff();
   RealScalar z = (derived() / w).squaredNorm();
   if (z > RealScalar(0)) derived() /= numext::sqrt(z) * w;
 }
References Eigen::numext::sqrt(), and w.
stableNormalized()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< Derived >::PlainObject Eigen::MatrixBase< Derived >::stableNormalized
Returns
an expression of the quotient of *this by its own norm while avoiding underflow and overflow.
\only_for_vectors
This method is analogue to the normalized() method, but it reduces the risk of underflow and overflow when computing the norm.
Warning
If the input vector is too small (i.e., this->norm()==0), then this function returns a copy of the input.
See also
stableNorm(), stableNormalize(), normalized()
{
   typedef typename internal::nested_eval<Derived, 3>::type Nested_;
   Nested_ n(derived());
   RealScalar w = n.cwiseAbs().maxCoeff();
   RealScalar z = (n / w).squaredNorm();
   if (z > RealScalar(0))
     return n / (numext::sqrt(z) * w);
   else
     return n;
 }
References n, Eigen::numext::sqrt(), and w.
trace()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::MatrixBase< Derived >::trace
Returns
the trace of *this, i.e. the sum of the coefficients on the main diagonal.
*this can be any matrix, not necessarily square.
See also
diagonal(), sum()
{
   return derived().diagonal().sum();
 }
triangularView() [1/4]
template<typename Derived > template<unsigned int Mode> EIGEN_DEVICE_FUNC TriangularViewReturnType<Mode>::Type Eigen::MatrixBase< Derived >::triangularView ()
triangularView() [2/4]
template<typename Derived > template<unsigned int Mode> EIGEN_DEVICE_FUNC MatrixBase<Derived>::template TriangularViewReturnType<Mode>::Type Eigen::MatrixBase< Derived >::triangularView ()
Returns
an expression of a triangular view extracted from the current matrix
The parameter Mode can have the following values: Upper, StrictlyUpper, UnitUpper, Lower, StrictlyLower, UnitLower.
Example:
Matrix3i m = Matrix3i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the upper-triangular matrix extracted from m:" << endl
     << Matrix3i(m.triangularView<Eigen::Upper>()) << endl;
cout << "Here is the strictly-upper-triangular matrix extracted from m:" << endl
     << Matrix3i(m.triangularView<Eigen::StrictlyUpper>()) << endl;
cout << "Here is the unit-lower-triangular matrix extracted from m:" << endl
     << Matrix3i(m.triangularView<Eigen::UnitLower>()) << endl;
// FIXME need to implement output for triangularViews (Bug 885)
Output:
See also
class TriangularView
{
   return typename TriangularViewReturnType<Mode>::Type(derived());
 }
triangularView() [3/4]
template<typename Derived > template<unsigned int Mode> EIGEN_DEVICE_FUNC ConstTriangularViewReturnType<Mode>::Type Eigen::MatrixBase< Derived >::triangularView () const
triangularView() [4/4]
template<typename Derived > template<unsigned int Mode> EIGEN_DEVICE_FUNC MatrixBase<Derived>::template ConstTriangularViewReturnType<Mode>::Type Eigen::MatrixBase< Derived >::triangularView () const
This is the const version of MatrixBase::triangularView()
{
   return typename ConstTriangularViewReturnType<Mode>::Type(derived());
 }
Unit() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< Derived >::BasisReturnType Eigen::MatrixBase< Derived >::Unit (Index i) static
Returns
an expression of the i-th unit (basis) vector.
\only_for_vectors
This variant is for fixed-size vector only.
See also
MatrixBase::Unit(Index,Index), MatrixBase::UnitX(), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
              {
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
   return BasisReturnType(SquareMatrixType::Identity(), i);
 }
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, and i.
Unit() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< Derived >::BasisReturnType Eigen::MatrixBase< Derived >::Unit (Index newSize, Index i) static
Returns
an expression of the i-th unit (basis) vector.
\only_for_vectors
See also
MatrixBase::Unit(Index), MatrixBase::UnitX(), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
{
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
   return BasisReturnType(SquareMatrixType::Identity(newSize, newSize), i);
 }
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, and i.
UnitW()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< Derived >::BasisReturnType Eigen::MatrixBase< Derived >::UnitW static
Returns
an expression of the W axis unit vector (0,0,0,1)
\only_for_vectors
See also
MatrixBase::Unit(Index,Index), MatrixBase::Unit(Index), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
{
   return Derived::Unit(3);
 }
UnitX()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< Derived >::BasisReturnType Eigen::MatrixBase< Derived >::UnitX static
Returns
an expression of the X axis unit vector (1{,0}^*)
\only_for_vectors
See also
MatrixBase::Unit(Index,Index), MatrixBase::Unit(Index), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
{
   return Derived::Unit(0);
 }
UnitY()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< Derived >::BasisReturnType Eigen::MatrixBase< Derived >::UnitY static
Returns
an expression of the Y axis unit vector (0,1{,0}^*)
\only_for_vectors
See also
MatrixBase::Unit(Index,Index), MatrixBase::Unit(Index), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
{
   return Derived::Unit(1);
 }
UnitZ()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< Derived >::BasisReturnType Eigen::MatrixBase< Derived >::UnitZ static
Returns
an expression of the Z axis unit vector (0,0,1{,0}^*)
\only_for_vectors
See also
MatrixBase::Unit(Index,Index), MatrixBase::Unit(Index), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
{
   return Derived::Unit(2);
 }
The documentation for this class was generated from the following files:
MatrixBase.h
LDLT.h
LLT.h
Assign.h
CwiseBinaryOp.h
CwiseNullaryOp.h
Diagonal.h
DiagonalMatrix.h
DiagonalProduct.h
Dot.h
ForceAlignedAccess.h
GeneralProduct.h
NoAlias.h
PermutationMatrix.h
Redux.h
SelfAdjointView.h
SkewSymmetricMatrix3.h
StableNorm.h
Transpose.h
TriangularMatrix.h
MatrixBaseEigenvalues.h
Eigen/src/Geometry/EulerAngles.h
Homogeneous.h
OrthoMethods.h
Householder.h
Jacobi.h
Determinant.h
FullPivLU.h
InverseImpl.h
PartialPivLU.h
ColPivHouseholderQR.h
CompleteOrthogonalDecomposition.h
FullPivHouseholderQR.h
HouseholderQR.h
SparseView.h
BDCSVD.h
JacobiSVD.h
MatrixFunction.h