MercuryDPM: PacketBlockSet< Scalar, StorageOrder, n > Struct Template Reference
PacketBlockSet< Scalar, StorageOrder, n > Struct Template Reference
Public Types
typedef internal::packet_traits< Scalar >::type Packet
Public Member Functions
void setPacketBlock (internal::PacketBlock< Packet, n > &block, Scalar value)
void comparePacketBlock (Scalar *data, int i, int j, int stride, internal::PacketBlock< Packet, n > &block)
Member Typedef Documentation
Packet
template<typename Scalar , int StorageOrder, int n> typedef internal::packet_traits<Scalar>::type PacketBlockSet< Scalar, StorageOrder, n >::Packet
Member Function Documentation
comparePacketBlock()
template<typename Scalar , int StorageOrder, int n> void PacketBlockSet< Scalar, StorageOrder, n >::comparePacketBlock (Scalar * data, int i, int j, int stride, internal::PacketBlock< Packet, n > & block) inline
{
     for (int idx = 0; idx < n; idx++) {
       Packet line = internal::ploadu<Packet>(data + SCATTER(i, j, idx));
       compare<Scalar, Packet>(block.packet[idx], line);
     }
   }
References block(), data, i, j, calibrate::line, n, and SCATTER.
Referenced by run_bdmp_spec_1().
setPacketBlock()
template<typename Scalar , int StorageOrder, int n> void PacketBlockSet< Scalar, StorageOrder, n >::setPacketBlock (internal::PacketBlock< Packet, n > & block, Scalar value) inline
{
     for (int idx = 0; idx < n; idx++) {
       block.packet[idx] = internal::pset1<Packet>(value);
     }
   }
References block(), n, and Eigen::value.
Referenced by run_bdmp_spec_1().
The documentation for this struct was generated from the following file:
blasutil.cpp