MercuryDPM: Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape > Struct Template Reference
Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape > Struct Template Reference
#include <ProductEvaluators.h>
Public Types
enum { StorageOrder = Base::StorageOrder_ }
typedef diagonal_product_evaluator_base< Rhs, typename Lhs::DiagonalVectorType, Product< Lhs, Rhs, LazyProduct >, OnTheLeft > Base
typedef Base::Scalar Scalar
typedef Product< Lhs, Rhs, ProductKind > XprType
typedef XprType::PlainObject PlainObject
typedef Lhs::DiagonalVectorType DiagonalType
Public Types inherited from Eigen::internal::diagonal_product_evaluator_base< Rhs, Lhs::DiagonalVectorType, Product< Lhs, Rhs, LazyProduct >, OnTheLeft >
enum
typedef ScalarBinaryOpTraits< typename MatrixType::Scalar, typename DiagonalType::Scalar >::ReturnType Scalar
Public Types inherited from Eigen::internal::evaluator_base< Product< Lhs, Rhs, LazyProduct > >
enum
typedef traits< Product< Lhs, Rhs, LazyProduct > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC product_evaluator (const XprType &xpr)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar coeff (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index idx) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar coeff (Index idx) const
Public Member Functions inherited from Eigen::internal::diagonal_product_evaluator_base< Rhs, Lhs::DiagonalVectorType, Product< Lhs, Rhs, LazyProduct >, OnTheLeft >
EIGEN_DEVICE_FUNC diagonal_product_evaluator_base (const Rhs &mat, const Lhs::DiagonalVectorType &diag)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar coeff (Index idx) const
Public Member Functions inherited from Eigen::internal::evaluator_base< Product< Lhs, Rhs, LazyProduct > >
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE evaluator_base ()=default
Public Attributes
evaluator< DiagonalType > m_diagImpl
evaluator< MatrixType > m_matImpl
Additional Inherited Members
Protected Member Functions inherited from Eigen::internal::diagonal_product_evaluator_base< Rhs, Lhs::DiagonalVectorType, Product< Lhs, Rhs, LazyProduct >, OnTheLeft >
EIGEN_STRONG_INLINE PacketType packet_impl (Index row, Index col, Index id, internal::true_type) const
EIGEN_STRONG_INLINE PacketType packet_impl (Index row, Index col, Index id, internal::false_type) const
Protected Attributes inherited from Eigen::internal::diagonal_product_evaluator_base< Rhs, Lhs::DiagonalVectorType, Product< Lhs, Rhs, LazyProduct >, OnTheLeft >
evaluator< Lhs::DiagonalVectorType > m_diagImpl
evaluator< Rhs > m_matImpl
Member Typedef Documentation
Base
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> typedef diagonal_product_evaluator_base<Rhs, typename Lhs::DiagonalVectorType, Product<Lhs, Rhs, LazyProduct>, OnTheLeft> Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::Base
DiagonalType
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> typedef Lhs::DiagonalVectorType Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::DiagonalType
PlainObject
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> typedef XprType::PlainObject Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::PlainObject
Scalar
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> typedef Base::Scalar Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::Scalar
XprType
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> typedef Product<Lhs, Rhs, ProductKind> Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::XprType
Member Enumeration Documentation
anonymous enum
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> anonymous enum
Enumerator
StorageOrder
 { StorageOrder = Base::StorageOrder_ };
Constructor & Destructor Documentation
product_evaluator()
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> EIGEN_DEVICE_FUNC Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::product_evaluator (const XprType & xpr) inline explicit
 : Base(xpr.rhs(), xpr.lhs().diagonal()) {}
Member Function Documentation
coeff() [1/2]
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar Eigen::internal::diagonal_product_evaluator_base< MatrixType, DiagonalType, Derived, ProductOrder >::coeff inline
{
     if (AsScalarProduct)
       return m_diagImpl.coeff(0) * m_matImpl.coeff(idx);
     else
       return m_diagImpl.coeff(idx) * m_matImpl.coeff(idx);
   }
coeff() [2/2]
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::coeff (Index row, Index col) const inline
{
     return m_diagImpl.coeff(row) * m_matImpl.coeff(row, col);
   }
References col(), and row().
packet() [1/2]
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::packet (Index idx) const inline
{
     return packet<LoadMode, PacketType>(int(StorageOrder) == ColMajor ? idx : 0,
                                         int(StorageOrder) == ColMajor ? 0 : idx);
   }
References Eigen::ColMajor.
packet() [2/2]
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::packet (Index row, Index col) const inline
{
     // FIXME: NVCC used to complain about the template keyword, but we have to check whether this is still the case.
     // See also similar calls below.
     return this->template packet_impl<LoadMode, PacketType>(
         row, col, row, std::conditional_t<int(StorageOrder) == RowMajor, internal::true_type, internal::false_type>());
   }
References col(), row(), and Eigen::RowMajor.
Member Data Documentation
m_diagImpl
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> evaluator<DiagonalType> Eigen::internal::diagonal_product_evaluator_base< MatrixType, DiagonalType, Derived, ProductOrder >::m_diagImpl
m_matImpl
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> evaluator<MatrixType> Eigen::internal::diagonal_product_evaluator_base< MatrixType, DiagonalType, Derived, ProductOrder >::m_matImpl
The documentation for this struct was generated from the following file:
ProductEvaluators.h