MercuryDPM: Multiparticle_InsertionUnitTest.cpp File Reference
Multiparticle_InsertionUnitTest.cpp File Reference
#include "Mercury3D.h"
#include "Boundaries/FixedClusterInsertionBoundary.h"
#include "Boundaries/PeriodicBoundary.h"
#include "Species/LinearViscoelasticSlidingFrictionBondedSpecies.h"
#include "Walls/InfiniteWall.h"
Classes
class MultiParticlesInsertion
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     logger(INFO,"Inserting multi-particles.");
     MultiParticlesInsertion insertion;
     insertion.setTimeStep(1e-4);
     insertion.setTimeMax(0.5);
     insertion.solve();
     helpers::check(4, insertion.particleHandler.getSize(), 0.1, "Number of particles check");
 //    helpers::check(0, insertion.interactionHandler.getSize(), 0.1, "Number of interactions check");
 }
References helpers::check(), e(), BaseHandler< T >::getSize(), INFO, logger, DPMBase::particleHandler, DPMBase::setTimeMax(), DPMBase::setTimeStep(), and DPMBase::solve().