MercuryDPM: Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device > Struct Template Reference
#include <TensorCustomOp.h>
Public Types
enum {
IsAligned = false , PacketAccess = (PacketType<CoeffReturnType, Device>::size > 1) , BlockAccess = false , PreferBlockAccess = false ,
CoordAccess = false , RawAccess = false
}
typedef TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType > XprType
typedef internal::traits< XprType >::Index Index
typedef DSizes< Index, NumDims > Dimensions
typedef XprType::Scalar Scalar
typedef std::remove_const_t< typename XprType::CoeffReturnType > CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef Eigen::internal::traits< XprType >::PointerType TensorPointerType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorBlockNotImplemented TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType data)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EvaluatorPointerType data () const
Static Public Attributes
static constexpr int NumDims = internal::traits<XprType>::NumDimensions
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int Layout = TensorEvaluator<LhsXprType, Device>::Layout
Protected Member Functions
void evalTo (EvaluatorPointerType data)
Protected Attributes
Dimensions m_dimensions
const XprType m_op
const Device EIGEN_DEVICE_REF m_device
EvaluatorPointerType m_result
Member Typedef Documentation
CoeffReturnType
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > typedef std::remove_const_t<typename XprType::CoeffReturnType> Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::CoeffReturnType
Dimensions
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > typedef DSizes<Index, NumDims> Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::Dimensions
EvaluatorPointerType
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::EvaluatorPointerType
Index
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > typedef internal::traits<XprType>::Index Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::Index
PacketReturnType
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::PacketReturnType
Scalar
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::Scalar
Storage
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::Storage
TensorBlock
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > typedef internal::TensorBlockNotImplemented Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::TensorBlock
TensorPointerType
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > typedef Eigen::internal::traits<XprType>::PointerType Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::TensorPointerType
XprType
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > typedef TensorCustomBinaryOp<CustomBinaryFunc, LhsXprType, RhsXprType> Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = false,
     PacketAccess = (PacketType<CoeffReturnType, Device>::size > 1),
     BlockAccess = false,
     PreferBlockAccess = false,
     CoordAccess = false,  // to be implemented
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_op(op), m_device(device), m_result(NULL) {
     m_dimensions = op.func().dimensions(op.lhsExpression(), op.rhsExpression());
   }
References op.
Member Function Documentation
cleanup()
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::cleanup () inline
{
     if (m_result != NULL) {
       m_device.deallocate_temp(m_result);
       m_result = NULL;
     }
   }
References Eigen::TensorEvaluator< Derived, Device >::m_device.
Referenced by framework.Frame::__init__().
coeff()
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::coeff (Index index) const inline
 { return m_result[index]; }
costPerCoeff()
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::costPerCoeff (bool vectorized) const inline
{
     // TODO(rmlarsen): Extend CustomOp API to return its cost estimate.
     return TensorOpCost(sizeof(CoeffReturnType), 0, 0, vectorized, PacketSize);
   }
References Eigen::TensorEvaluator< Derived, Device >::PacketSize.
data()
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > EIGEN_DEVICE_FUNC EvaluatorPointerType Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::data () const inline
 { return m_result; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::dimensions () const inline
 { return m_dimensions; }
evalSubExprsIfNeeded()
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType data) inline
{
     if (data) {
       evalTo(data);
       return false;
     } else {
       m_result = static_cast<EvaluatorPointerType>(
           m_device.get((CoeffReturnType*)m_device.allocate_temp(dimensions().TotalSize() * sizeof(CoeffReturnType))));
       evalTo(m_result);
       return true;
     }
   }
References Eigen::TensorEvaluator< Derived, Device >::data(), Eigen::TensorEvaluator< Derived, Device >::dimensions(), and Eigen::TensorEvaluator< Derived, Device >::m_device.
evalTo()
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > void Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::evalTo (EvaluatorPointerType data) inline protected
{
     TensorMap<Tensor<CoeffReturnType, NumDims, Layout> > result(m_device.get(data), m_dimensions);
     m_op.func().eval(m_op.lhsExpression(), m_op.rhsExpression(), result, m_device);
   }
References Eigen::TensorEvaluator< Derived, Device >::data(), and Eigen::TensorEvaluator< Derived, Device >::m_device.
packet()
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC PacketReturnType Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::packet (Index index) const inline
{
     return internal::ploadt<PacketReturnType, LoadMode>(m_result + index);
   }
Member Data Documentation
Layout
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::Layout = TensorEvaluator<LhsXprType, Device>::Layout static constexpr
m_device
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > const Device EIGEN_DEVICE_REF Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::m_device protected
m_dimensions
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > Dimensions Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::m_dimensions protected
m_op
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > const XprType Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::m_op protected
m_result
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > EvaluatorPointerType Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::m_result protected
NumDims
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::NumDims = internal::traits<XprType>::NumDimensions static constexpr
PacketSize
template<typename CustomBinaryFunc , typename LhsXprType , typename RhsXprType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorCustomOp.h