MercuryDPM: SimpleSpineMesh< ELEMENT > Class Template Reference
SimpleSpineMesh< ELEMENT > Class Template Reference
Public Types
typedef double(* HeightFctPt) (const double &x)
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Public Member Functions
SimpleSpineMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &h, GeomObject *substrate_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
HeightFctPt & height_fct_pt ()
Access function: Pointer to height function.
double height_fct (const double &x)
void update_spine_heights ()
virtual void spine_node_update (SpineNode *spine_node_pt)
Public Member Functions inherited from oomph::SimpleRectangularQuadMesh< ELEMENT >
SimpleRectangularQuadMesh (const unsigned &Nx, const unsigned &Ny, const double &Lx, const double &Ly, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
const unsigned & nx () const
Access function for number of elements in x directions.
const unsigned & ny () const
Access function for number of elements in y directions.
Public Member Functions inherited from oomph::QuadMeshBase
QuadMeshBase ()
Constructor (empty)
QuadMeshBase (const QuadMeshBase &node)=delete
Broken copy constructor.
void operator= (const QuadMeshBase &)=delete
Broken assignment operator.
virtual ~QuadMeshBase ()
Destructor (empty)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Public Member Functions inherited from oomph::SpineMesh
virtual ~SpineMesh ()
Destructor to clean up the memory allocated to the spines.
Spine *& spine_pt (const unsigned long &i)
Return the i-th spine in the mesh.
const Spine * spine_pt (const unsigned long &i) const
Return the i-th spine in the mesh (const version)
unsigned long nspine () const
Return the number of spines in the mesh.
void add_spine_pt (Spine *const &spine_pt)
Add a spine to the mesh.
SpineNode * node_pt (const unsigned long &n)
Return a pointer to the n-th global SpineNode.
SpineNode * element_node_pt (const unsigned long &e, const unsigned &n)
unsigned long assign_global_spine_eqn_numbers (Vector< double * > &Dof_pt)
Assign spines to Spine_pt vector of element.
void describe_spine_dofs (std::ostream &out, const std::string &current_string) const
void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_spine_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Assign time stepper to spines data.
void set_consistent_pinned_spine_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
bool does_pointer_correspond_to_spine_data (double *const &parameter_pt)
void node_update (const bool &update_all_solid_nodes=false)
void dump (std::ofstream &dump_file) const
Overload the dump function so that the spine data is dumped.
void read (std::ifstream &restart_file)
Overload the read function so that the spine data is also read.
Private Attributes
double Default_height
Default height.
HeightFctPt Height_fct_pt
Pointer to height function.
GeomObject * Substrate_pt
Pointer to GeomObject that specifies the "substrate" (the lower wall)
Additional Inherited Members
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Protected Attributes inherited from oomph::SpineMesh
Vector< Spine * > Spine_pt
A Spine mesh contains a Vector of pointers to spines.
Detailed Description
template<class ELEMENT>
class SimpleSpineMesh< ELEMENT >
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Simple spine mesh class derived from standard 2D mesh. Vertical lines of nodes are located on spines.
Member Typedef Documentation
HeightFctPt
template<class ELEMENT > typedef double(* SimpleSpineMesh< ELEMENT >::HeightFctPt) (const double &x)
Function pointer to function, h(x), that may be used to specify the "height" of the domain, by assigning the function values to the spine heights.
Constructor & Destructor Documentation
SimpleSpineMesh()
template<class ELEMENT > SimpleSpineMesh< ELEMENT >::SimpleSpineMesh (const unsigned & nx, const unsigned & ny, const double & lx, const double & h, GeomObject * substrate_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass number of elements in x-direction, number of elements in y-direction, length in x direction, initial height of mesh, and pointer to timestepper (defaults to Steady timestepper)
Constructor for spine 2D mesh: Pass number of elements in x-direction, number of elements in y-direction, axial length and height of layer, pointer to geometric object that specifies the substrate (the lower wall) and pointer to timestepper (defaults to Static timestepper).
The mesh contains a layer of spine-ified fluid elements (of type ELEMENT; e.g SpineElement<QCrouzeixRaviartElement<2>)
                                                                         :
  SimpleRectangularQuadMesh<ELEMENT>(nx,ny,lx,h,time_stepper_pt),
  Default_height(h), Height_fct_pt(0), Substrate_pt(substrate_pt)
 {
  // We've already called the constructor for the SimpleRectangularQuadMesh
  // which sets up nodal positons/topology etc. Now attach the spine
  // information
  // Allocate memory for the spines and fractions along spines
  // Read out number of linear points in the element
  unsigned np = dynamic_cast<ELEMENT*>(finite_element_pt(0))->nnode_1d();
  // Number of spines
  unsigned nspine = (np-1)*nx+1;
  Spine_pt.reserve(nspine);
  // Set up x-increments between spine origins
  double x_lo=0.0;
  double dx=lx/double(nx);
  //FIRST SPINE
  //-----------
  //Element 0
  //Node 0
  //Assign the new spine with specified height
  Spine* new_spine_pt=new Spine(h);
  Spine_pt.push_back(new_spine_pt);
  // Get pointer to node
  SpineNode* nod_pt=element_node_pt(0,0);
  //Pass the pointer to the spine to the node
  nod_pt->spine_pt() = new_spine_pt;
  //Set the node's fraction along the spine
  nod_pt->fraction() = 0.0;
  // Set the pointer to the mesh that implements the update fct for this node
  nod_pt->spine_mesh_pt() = this;
  // Set update fct id (not really needed here...)
  nod_pt->node_update_fct_id()=0;
  // Create vector that stores additional geometric parameters that
  // are required during the execution of the remesh function:
  // For our remesh function, we need the x-coordinate of the
  // spine origin.
  // Vector with enough storage for one geometic parameter
   Vector<double> parameters(1);
   // Store the x-coordinate in it
   parameters[0]=x_lo;
   // Pass the parameter to the spine
   new_spine_pt->set_geom_parameter(parameters);
   // The remesh function involving this spine only involves
   // a single geometric object: The substrate
   Vector<GeomObject*> geom_object_pt(1);
   geom_object_pt[0] = Substrate_pt;
   // Pass geom object(s) to spine
   new_spine_pt->set_geom_object_pt(geom_object_pt);
  //Loop vertically along the first spine
  //Loop over the elements
  for(unsigned i=0;i<ny;i++)
   {
    //Loop over the vertical nodes, apart from the first
    for(unsigned l1=1;l1<np;l1++)
     {
      // Get pointer to node
      SpineNode* nod_pt=element_node_pt(i*nx,l1*np);
      //Pass the pointer to the spine to the node
      nod_pt->spine_pt() = new_spine_pt;
      //Set the fraction
      nod_pt->fraction()=(double(i)+double(l1)/double(np-1))/double(ny);
      // Pointer to the mesh that implements the update fct
      nod_pt->spine_mesh_pt() = this;
      // Set update fct id (not really needed here)
      nod_pt->node_update_fct_id()=0;
     }
   } // end loop over elements
  //LOOP OVER OTHER SPINES
  //----------------------
  //Now loop over the elements horizontally
  for(unsigned j=0;j<nx;j++)
   {
    //Loop over the nodes in the elements horizontally, ignoring
    //the first column
    unsigned npmax=np;
    for(unsigned l2=1;l2<npmax;l2++)
     {
      //Assign the new spine with specified height
      new_spine_pt=new Spine(h);
      // Add to collection of spines
      Spine_pt.push_back(new_spine_pt);
      // Get the node
      SpineNode* nod_pt=element_node_pt(j,l2);
      //Pass the pointer to the spine to the node
      nod_pt->spine_pt() = new_spine_pt;
      //Set the fraction
      nod_pt->fraction() = 0.0;
      // Pointer to the mesh that implements the update fct
      nod_pt->spine_mesh_pt() = this;
      // Set update fct id (not really needed here)
      nod_pt->node_update_fct_id()=0;
      // Create vector that stores additional geometric parameters that
      // are required during the execution of the remesh function:
      // For our remesh function, we need the x-coordinate of the
      // spine origin.
      // Vector with enough storage for one geometic parameter
      Vector<double> parameters(1);
      // Store the x-coordinate in it
      parameters[0]=x_lo+double(j)*dx + double(l2)*dx/double(np-1);
      // Pass the parameter to the spine
      new_spine_pt->set_geom_parameter(parameters);
      // The remesh function involving this spine only involves
      // a single geometric object: The substrate
      Vector<GeomObject*> geom_object_pt(1);
      geom_object_pt[0] = Substrate_pt;
      // Pass geom object(s) to spine
      new_spine_pt->set_geom_object_pt(geom_object_pt);
      //Loop vertically along the spine
      //Loop over the elements
      for(unsigned i=0;i<ny;i++)
       {
        //Loop over the vertical nodes, apart from the first
        for(unsigned l1=1;l1<np;l1++)
         {
          // Get the node
          SpineNode* nod_pt=element_node_pt(i*nx+j,l1*np+l2);
          //Set the pointer to the spine
          nod_pt->spine_pt() = new_spine_pt;
          //Set the fraction
          nod_pt->fraction()=(double(i)+double(l1)/double(np-1))/double(ny);
          // Pointer to the mesh that implements the update fct
          nod_pt->spine_mesh_pt() = this;
          // Set update fct id (not really needed here)
          nod_pt->node_update_fct_id()=0;
         }
       }
     }
   }
 } // end of constructor
References oomph::SpineMesh::element_node_pt(), oomph::Mesh::finite_element_pt(), oomph::SpineNode::fraction(), i, j, Mesh_Parameters::lx, oomph::SpineNode::node_update_fct_id(), oomph::SpineMesh::nspine(), oomph::SimpleRectangularQuadMesh< ELEMENT >::nx(), oomph::SimpleRectangularQuadMesh< ELEMENT >::ny(), oomph::Spine::set_geom_object_pt(), oomph::Spine::set_geom_parameter(), oomph::SpineNode::spine_mesh_pt(), oomph::SpineNode::spine_pt(), oomph::SpineMesh::Spine_pt, and SimpleSpineMesh< ELEMENT >::Substrate_pt.
Member Function Documentation
height_fct()
template<class ELEMENT > double SimpleSpineMesh< ELEMENT >::height_fct (const double & x) inline
Height function – this is called by update_spine_heights() when spine heights are assigned.
   {
    // Resolve function pointer if non-NULL
    if (Height_fct_pt==0)
     {
      return Default_height;
     }
    else
    {
     return Height_fct_pt(x);
    }
   }
References plotDoE::x.
height_fct_pt()
template<class ELEMENT > HeightFctPt& SimpleSpineMesh< ELEMENT >::height_fct_pt () inline
Access function: Pointer to height function.
   {
    return Height_fct_pt;
   }
spine_node_update()
template<class ELEMENT > virtual void SimpleSpineMesh< ELEMENT >::spine_node_update (SpineNode * spine_node_pt) inline virtual
General node update function implements pure virtual function defined in SpineMesh base class and performs specific node update actions: Nodes are located along vertical "spines" that emanate from the "substrate" (the lower wall) specified by a GeomObject.
Implements oomph::SpineMesh.
   {
    //Get fraction along the spine
    double w = spine_node_pt->fraction();
    // Get height of spine
    double h = spine_node_pt->spine_pt()->height();
    // Get x-position of spine origin (as vector)
    Vector<double> x_spine_origin(1);
    x_spine_origin[0]=spine_node_pt->spine_pt()->geom_parameter(0);
    // Get position vector to substrate (lower wall) for this spine
    Vector<double> spine_base(2);
    spine_node_pt->spine_pt()->geom_object_pt(0)->
     position(x_spine_origin,spine_base);
    //Update the nodal position
    spine_node_pt->x(0) = spine_base[0];
    spine_node_pt->x(1) = spine_base[1]+w*h;
   }
References oomph::SpineNode::fraction(), oomph::Spine::geom_object_pt(), oomph::Spine::geom_parameter(), oomph::Spine::height(), oomph::SpineNode::spine_pt(), w, and oomph::Node::x().
update_spine_heights()
template<class ELEMENT > void SimpleSpineMesh< ELEMENT >::update_spine_heights () inline
Update the spine heights according to the function specified by height_fct_pt().
   {
    unsigned n_spine=nspine();
    for (unsigned i=0;i<n_spine;i++)
     {
      // Zero-th geometric parameter of the spine is the x-coordinate
      // of its basis
      double x=spine_pt(i)->geom_parameter(0);
      // Set spine height
      spine_pt(i)->height()=height_fct(x);
     }
   }
References i, and plotDoE::x.
Member Data Documentation
Default_height
template<class ELEMENT > double SimpleSpineMesh< ELEMENT >::Default_height private
Default height.
Height_fct_pt
template<class ELEMENT > HeightFctPt SimpleSpineMesh< ELEMENT >::Height_fct_pt private
Pointer to height function.
Substrate_pt
template<class ELEMENT > GeomObject* SimpleSpineMesh< ELEMENT >::Substrate_pt private
Pointer to GeomObject that specifies the "substrate" (the lower wall)
Referenced by SimpleSpineMesh< ELEMENT >::SimpleSpineMesh().
The documentation for this class was generated from the following file:
simple_spine_channel.cc