MercuryDPM: IrreversibleAdhesiveInteraction Class Reference
IrreversibleAdhesiveInteraction Class Reference
#include <IrreversibleAdhesiveInteraction.h>
Public Types
typedef IrreversibleAdhesiveSpecies SpeciesType
An alias name for IrreversibleAdhesiveSpecies data type.
Public Types inherited from ReversibleAdhesiveInteraction
typedef ReversibleAdhesiveSpecies SpeciesType
Setting an alias name for ReversibleAdhesiveSpecies.
Public Member Functions
IrreversibleAdhesiveInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
Constructor.
IrreversibleAdhesiveInteraction ()
IrreversibleAdhesiveInteraction (const IrreversibleAdhesiveInteraction &p)
Copy constructor.
~IrreversibleAdhesiveInteraction () override
Destructor.
void computeAdhesionForce ()
Computes the Adhesive force.
void read (std::istream &is) override
Interaction read function, which accepts an std::istream as input.
void write (std::ostream &os) const override
Interaction print function, which accepts an std::ostream as input.
const IrreversibleAdhesiveSpecies * getSpecies () const
Returns a pointer to the adhesive force species IrreversibleAdhesiveSpecies.
std::string getBaseName () const
Returns the name of the interaction, see Interaction.h.
Mdouble getElasticEnergy () const override
Returns the elastic energy stored in the adhesive spring.
bool getWasInContact () const
void setWasInContact (bool wasInContact)
Public Member Functions inherited from ReversibleAdhesiveInteraction
ReversibleAdhesiveInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
Constructor.
ReversibleAdhesiveInteraction ()
ReversibleAdhesiveInteraction (const ReversibleAdhesiveInteraction &p)
Copy constructor.
~ReversibleAdhesiveInteraction () override
Destructor.
void computeAdhesionForce ()
Computes the adhesive forces.
void read (std::istream &is) override
Interaction read function, which accepts an std::istream as input.
void write (std::ostream &os) const override
Interaction print function, which accepts an std::ostream as input.
Mdouble getElasticEnergy () const override
Returns the amount of Elastic energy involved in an interaction. Basically used in case you want to write the elastic energy into an output file.
const ReversibleAdhesiveSpecies * getSpecies () const
Returns a pointer to the adhesive force species ReversibleAdhesiveSpecies.
std::string getBaseName () const
Returns the name of the interaction, see Interaction.h.
Public Member Functions inherited from BaseInteraction
BaseInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
A constructor takes the BaseInteractable objects which are interacting (come into contact) and time the interaction starts.
BaseInteraction ()
BaseInteraction (const BaseInteraction &p)
Copy constructor.
~BaseInteraction () override
The destructor. It removes this interactions from the objects that were interacting, and writes the time to a file when needed.
virtual void actionsOnErase ()
If an interaction needs to do something before it gets erased, add it here. E.g. Liquid bridges rupture at the end of their lifetime, and the liquid bridge volume has to be redistributed. The reason this action is not done in the destructor is that this action should not be taken when erasing ghost interactions.
virtual void computeForce ()
Virtual function that contains the force law between the two objects interacting.
void read (std::istream &is) override
Interaction read function, which accepts an std::istream as input.
void write (std::ostream &os) const override
Interaction print function, which accepts an std::ostream as input.
void writeToFStat (std::ostream &os, Mdouble time) const
Writes forces data to the FStat file.
std::string getName () const override
Virtual function which allows interactions to be named.
void setDistance (Mdouble distance)
Sets the interaction distance between the two interacting objects.
void setNormal (Vec3D normal)
Sets the normal vector between the two interacting objects.
void setOverlap (Mdouble overlap)
Set the overlap between the two interacting object.
void setContactPoint (Vec3D contactPoint)
Set the location of the contact point between the two interacting objects.
void setTimeStamp (unsigned timeStamp)
Updates the time step of the interacting. Note, time steps used to find completed interactions.
void setSpecies (const BaseSpecies *species)
Set the Species of the interaction; note this can either be a Species or MixedSpecies.
void setP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void setI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
void importP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void importI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
Vec3D getIP () const
Vec3D getIC () const
Vec3D getCP () const
void setLagrangeMultiplier (Mdouble multiplier)
Mdouble getLagrangeMultiplier ()
void setHandler (InteractionHandler *handler)
Sets the pointer to the interaction hander which is storing this interaction.
InteractionHandler * getHandler () const
Gets a point to the interaction handlers to which this interaction belongs.
const Vec3D & getForce () const
Gets the current force (vector) between the two interacting objects.
const Vec3D & getTorque () const
Gets the current torque (vector) between the two interacting objects.
const Vec3D & getNormal () const
Gets the normal vector between the two interacting objects.
const Vec3D & getContactPoint () const
Gets constant reference to contact point (vector).
Mdouble getOverlap () const
Returns a Mdouble with the current overlap between the two interacting objects.
Mdouble getOverlapVolume () const
Returns the overlap volume between two interacting objects.
Mdouble getContactRadius () const
Returns a Mdouble with the current contact between the two interacting objects.
void removeFromHandler ()
Removes this interaction from its interaction hander.
void copySwitchPointer (const BaseInteractable *original, BaseInteractable *ghost) const
This copies the interactions of the original particle and replaces the original with the ghost copy.
void gatherContactStatistics ()
BaseInteractable * getP ()
Returns a pointer to first object involved in the interaction (normally a particle).
BaseInteractable * getI ()
Returns a pointer to the second object involved in the interaction (often a wall or a particle).
const BaseInteractable * getP () const
Returns a constant pointer to the first object involved in the interaction.
const BaseInteractable * getI () const
Returns a constant pointer to the second object involved in the interaction.
Mdouble getTimeStamp () const
Returns an Mdouble which is the time stamp of the interaction.
virtual void integrate (Mdouble timeStep)
integrates variables of the interaction which need to be integrate e.g. the tangential overlap.
virtual Mdouble getTangentialOverlap () const
get the length of the current tangential overlap
Mdouble getDistance () const
Returns an Mdouble which is the norm (length) of distance vector.
const Vec3D & getRelativeVelocity () const
Returns a constant reference to a vector of relative velocity.
Mdouble getNormalRelativeVelocity () const
Returns a double which is the norm (length) of the relative velocity vector.
Mdouble getAbsoluteNormalForce () const
Returns the absolute value of the norm (length) of the Normal force vector.
virtual BaseInteraction * copy () const =0
Makes a copy of the interaction and returns a pointer to the copy.
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseWall *I)
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseParticle *I)
unsigned int getMultiContactIdentifier () const
void setMultiContactIdentifier (unsigned int multiContactIdentifier_)
virtual void rotateHistory (Matrix3D &rotationMatrix)
When periodic particles are used, some interactions need certain history properties rotated (e.g. tangential springs). This is the function for that.
virtual void actionsAfterTimeStep ()
virtual unsigned getNumberOfFieldsVTK () const
virtual std::string getTypeVTK (unsigned i) const
virtual std::string getNameVTK (unsigned i) const
virtual std::vector< Mdouble > getFieldVTK (unsigned i) const
void addForce (Vec3D force)
add an force increment to the total force.
void addTorque (Vec3D torque)
add a torque increment to the total torque.
void setForce (Vec3D force)
set total force (this is used by the normal force, tangential forces are added use addForce)
void setTorque (Vec3D torque)
set the total force (this is used by the normal force, tangential torques are added use addTorque)
const BaseSpecies * getBaseSpecies () const
Return a constant point to BaseSpecies of the interaction.
virtual void createMPIType ()
virtual void * createMPIInteractionDataArray (unsigned int numberOfInteractions) const
virtual void deleteMPIInteractionDataArray (void *dataArray)
virtual void getMPIInteraction (void *historyDataArray, unsigned int index) const
copies the history interactions into the data array
virtual void getInteractionDetails (void *interactionDataArray, unsigned int index, unsigned int &identificationP, unsigned int &identificationI, bool &isWallInteraction, unsigned &timeStamp)
virtual void setMPIInteraction (void *interactionDataArray, unsigned int index, bool resetPointers)
void setBasicMPIInteractionValues (int P, int I, unsigned timeStamp, Vec3D force, Vec3D torque, bool isWallInteraction, bool resetPointers)
void setIdentificationP (unsigned int identification)
void setIdentificationI (int identification)
void setWallInteraction (bool flag)
unsigned int getIdentificationP ()
int getIdentificationI ()
bool isWallInteraction ()
virtual bool isBonded () const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
bool wasInContact_
A history parameter to store if the particles were in contact or not. Useful to compute adhesive forces.
Additional Inherited Members
Protected Member Functions inherited from BaseInteraction
virtual const Vec3D getTangentialForce () const
Mdouble getEffectiveRadius () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
Mdouble getEffectiveMass () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
void setRelativeVelocity (Vec3D relativeVelocity)
set the relative velocity of the current of the interactions.
void setNormalRelativeVelocity (Mdouble normalRelativeVelocit)
set the normal component of the relative velocity.
void setAbsoluteNormalForce (Mdouble absoluteNormalForce)
the absolute values of the norm (length) of the normal force
virtual Mdouble getElasticEnergyAtEquilibrium (Mdouble adhesiveForce) const
virtual void reverseHistory ()
When periodic particles some interaction need certain history properties reversing. This is the function for that.
void writeInteraction (std::ostream &os, bool created) const
Writes information about a interaction to the interaction file.
Member Typedef Documentation
SpeciesType
typedef IrreversibleAdhesiveSpecies IrreversibleAdhesiveInteraction::SpeciesType
An alias name for IrreversibleAdhesiveSpecies data type.
Constructor & Destructor Documentation
IrreversibleAdhesiveInteraction() [1/3]
IrreversibleAdhesiveInteraction::IrreversibleAdhesiveInteraction (BaseInteractable * P, BaseInteractable * I, unsigned timeStamp)
Constructor.
Parameters
[in] P
[in] I
[in] timeStamp
         : BaseInteraction(P, I, timeStamp), ReversibleAdhesiveInteraction(P, I, timeStamp)
 {
     wasInContact_ = false;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"IrreversibleAdhesiveInteraction::IrreversibleAdhesiveInteraction() finished"<<std::endl;
 #endif
 }
References wasInContact_.
IrreversibleAdhesiveInteraction() [2/3]
IrreversibleAdhesiveInteraction::IrreversibleAdhesiveInteraction ()
         : BaseInteraction(), ReversibleAdhesiveInteraction()
 {
     wasInContact_ = false;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"IrreversibleAdhesiveInteraction::IrreversibleAdhesiveInteraction() finished"<<std::endl;
 #endif
 }
References wasInContact_.
IrreversibleAdhesiveInteraction() [3/3]
IrreversibleAdhesiveInteraction::IrreversibleAdhesiveInteraction (const IrreversibleAdhesiveInteraction & p)
Copy constructor.
Parameters
[in] p
Todo:
tw check if the parameters are valid when inserting the species into the handler
         : BaseInteraction(p), ReversibleAdhesiveInteraction(p)
 {
     wasInContact_ = p.wasInContact_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"IrreversibleAdhesiveInteraction::IrreversibleAdhesiveInteraction(const IrreversibleAdhesiveInteraction &p finished"<<std::endl;
 #endif
 }
References p, and wasInContact_.
~IrreversibleAdhesiveInteraction()
IrreversibleAdhesiveInteraction::~IrreversibleAdhesiveInteraction () override
Destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"IrreversibleAdhesiveInteraction::~IrreversibleAdhesiveInteraction() finished"<<std::endl;
 #endif
 }
Member Function Documentation
computeAdhesionForce()
void IrreversibleAdhesiveInteraction::computeAdhesionForce ()
Computes the Adhesive force.
Uses the most basic adhesion contact model.
 {
     const IrreversibleAdhesiveSpecies* species = getSpecies();
     if (getOverlap() >= 0)
     {
         wasInContact_ = true;
         addForce(getNormal() * (-species->getAdhesionForceMax()));
     }
     else if (wasInContact_)
     {
         addForce(getNormal() * (-species->getAdhesionStiffness() * getOverlap() - species->getAdhesionForceMax()));
     }
 }
References BaseInteraction::addForce(), ReversibleAdhesiveSpecies::getAdhesionForceMax(), ReversibleAdhesiveSpecies::getAdhesionStiffness(), BaseInteraction::getNormal(), BaseInteraction::getOverlap(), getSpecies(), and wasInContact_.
getBaseName()
std::string IrreversibleAdhesiveInteraction::getBaseName () const
Returns the name of the interaction, see Interaction.h.
Returns
std::string
 {
     return "IrreversibleAdhesive";
 }
getElasticEnergy()
Mdouble IrreversibleAdhesiveInteraction::getElasticEnergy () const override virtual
Returns the elastic energy stored in the adhesive spring.
Elastic (=potential) energy is defined as the energy gained by separating two interactables. As it costs energy to separate adhesive interactables, the elastic energy is negative.
Returns
the elastic energy stored in the adhesive spring.
Reimplemented from BaseInteraction.
 {
     if (!wasInContact_)
         return 0.0;
     else if (getOverlap() <= 0)
         return -0.5 * getSpecies()->getAdhesionStiffness() *
                mathsFunc::square(getOverlap() + getBaseSpecies()->getInteractionDistance());
     else
         return -getSpecies()->getAdhesionForceMax() * getOverlap()
                - 0.5 * getSpecies()->getAdhesionStiffness() * mathsFunc::square(getBaseSpecies()->getInteractionDistance());
 }
References ReversibleAdhesiveSpecies::getAdhesionForceMax(), ReversibleAdhesiveSpecies::getAdhesionStiffness(), BaseInteraction::getBaseSpecies(), BaseInteraction::getOverlap(), getSpecies(), mathsFunc::square(), and wasInContact_.
getSpecies()
const IrreversibleAdhesiveSpecies * IrreversibleAdhesiveInteraction::getSpecies () const
Returns a pointer to the adhesive force species IrreversibleAdhesiveSpecies.
Returns
const pointer of IrreversibleAdhesiveSpecies*
 {
     return static_cast<const IrreversibleAdhesiveSpecies*>(getBaseSpecies()->getAdhesiveForce());
 ;
 }
References BaseSpecies::getAdhesiveForce(), and BaseInteraction::getBaseSpecies().
Referenced by computeAdhesionForce(), and getElasticEnergy().
getWasInContact()
bool IrreversibleAdhesiveInteraction::getWasInContact () const
 {
     return wasInContact_;
 }
References wasInContact_.
read()
void IrreversibleAdhesiveInteraction::read (std::istream & is) override virtual
Interaction read function, which accepts an std::istream as input.
Parameters
[in,out] is
Implements BaseObject.
 {
     std::string dummy;
     is >> dummy >> wasInContact_;
 }
References oomph::Global_string_for_annotation::string(), and wasInContact_.
setWasInContact()
void IrreversibleAdhesiveInteraction::setWasInContact (bool wasInContact)
 {
     wasInContact_ = wasInContact;
 }
References wasInContact_.
write()
void IrreversibleAdhesiveInteraction::write (std::ostream & os) const override virtual
Interaction print function, which accepts an std::ostream as input.
Parameters
[in,out] os
Implements BaseObject.
 {
     os << " wasInContact " << wasInContact_;
 }
References wasInContact_.
Member Data Documentation
wasInContact_
bool IrreversibleAdhesiveInteraction::wasInContact_ private
A history parameter to store if the particles were in contact or not. Useful to compute adhesive forces.
Referenced by computeAdhesionForce(), getElasticEnergy(), getWasInContact(), IrreversibleAdhesiveInteraction(), read(), setWasInContact(), and write().
The documentation for this class was generated from the following files:
IrreversibleAdhesiveInteraction.h
IrreversibleAdhesiveInteraction.cc