MercuryDPM: Eigen::internal::scalar_boolean_select_op< ThenScalar, ElseScalar, ConditionScalar > Struct Template Reference
Eigen::internal::scalar_boolean_select_op< ThenScalar, ElseScalar, ConditionScalar > Struct Template Reference
#include <TernaryFunctors.h>
Public Types
using Scalar = ThenScalar
using result_type = Scalar
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar operator() (const ThenScalar &a, const ElseScalar &b, const ConditionScalar &cond) const
template<typename Packet >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet packetOp (const Packet &a, const Packet &b, const Packet &cond) const
Static Public Attributes
static constexpr bool ThenElseAreSame = is_same<ThenScalar, ElseScalar>::value
Member Typedef Documentation
result_type
template<typename ThenScalar , typename ElseScalar , typename ConditionScalar > using Eigen::internal::scalar_boolean_select_op< ThenScalar, ElseScalar, ConditionScalar >::result_type = Scalar
Scalar
template<typename ThenScalar , typename ElseScalar , typename ConditionScalar > using Eigen::internal::scalar_boolean_select_op< ThenScalar, ElseScalar, ConditionScalar >::Scalar = ThenScalar
Member Function Documentation
operator()()
template<typename ThenScalar , typename ElseScalar , typename ConditionScalar > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar Eigen::internal::scalar_boolean_select_op< ThenScalar, ElseScalar, ConditionScalar >::operator() (const ThenScalar & a, const ElseScalar & b, const ConditionScalar & cond) const inline
{
     return cond == ConditionScalar(0) ? b : a;
   }
References a, and b.
packetOp()
template<typename ThenScalar , typename ElseScalar , typename ConditionScalar > template<typename Packet > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::scalar_boolean_select_op< ThenScalar, ElseScalar, ConditionScalar >::packetOp (const Packet & a, const Packet & b, const Packet & cond) const inline
{
     return pselect(pcmp_eq(cond, pzero(cond)), b, a);
   }
References a, b, Eigen::internal::pcmp_eq(), Eigen::internal::pselect(), and Eigen::internal::pzero().
Member Data Documentation
ThenElseAreSame
template<typename ThenScalar , typename ElseScalar , typename ConditionScalar > constexpr bool Eigen::internal::scalar_boolean_select_op< ThenScalar, ElseScalar, ConditionScalar >::ThenElseAreSame = is_same<ThenScalar, ElseScalar>::value static constexpr
The documentation for this struct was generated from the following file:
TernaryFunctors.h