MercuryDPM: LoggerOutput Class Reference
LoggerOutput Class Reference
Default functions for output generation.
#include <Logger.h>
Public Attributes
std::function< void(std::string, std::string, Flusher)> onFatal
std::function< void(std::string, std::string, Flusher)> onError
std::function< void(std::string, std::string, Flusher)> onWarn
std::function< void(std::string, std::string, Flusher)> onInfo
std::function< void(std::string, std::string, Flusher)> onVerbose
std::function< void(std::string, std::string, Flusher)> onDebug
Detailed Description
Default functions for output generation.
These handlers will be called on generation of the message. The functions are of signature void (std::string module Name, std::string message, Flusher doFlush_);
These functions may not return but call std::exit() instead. They may also throw any exception to allow code to gracefully recover.
Member Data Documentation
onDebug
std::function<void(std::string, std::string, Flusher)> LoggerOutput::onDebug
Referenced by main(), and Logger< L, ASSERTS >::operator()().
onError
std::function<void(std::string, std::string, Flusher)> LoggerOutput::onError
Referenced by Logger< L, ASSERTS >::if(), main(), and Logger< L, ASSERTS >::operator()().
onFatal
std::function<void(std::string, std::string, Flusher)> LoggerOutput::onFatal
Referenced by main(), and Logger< L, ASSERTS >::operator()().
onInfo
std::function<void(std::string, std::string, Flusher)> LoggerOutput::onInfo
Referenced by Logger< L, ASSERTS >::if(), main(), and Logger< L, ASSERTS >::operator()().
onVerbose
std::function<void(std::string, std::string, Flusher)> LoggerOutput::onVerbose
Referenced by Logger< L, ASSERTS >::if(), main(), and Logger< L, ASSERTS >::operator()().
onWarn
std::function<void(std::string, std::string, Flusher)> LoggerOutput::onWarn
Referenced by Logger< L, ASSERTS >::if(), main(), and Logger< L, ASSERTS >::operator()().
The documentation for this class was generated from the following file:
Logger.h