MercuryDPM: Eigen::internal::tridiagonalization_inplace_selector< MatrixType, Size, IsComplex > Struct Template Reference
Eigen::internal::tridiagonalization_inplace_selector< MatrixType, Size, IsComplex > Struct Template Reference
#include <Tridiagonalization.h>
Public Types
typedef Tridiagonalization< MatrixType >::HouseholderSequenceType HouseholderSequenceType
Static Public Member Functions
template<typename DiagonalType , typename SubDiagonalType , typename CoeffVectorType , typename WorkSpaceType >
static EIGEN_DEVICE_FUNC void run (MatrixType &mat, DiagonalType &diag, SubDiagonalType &subdiag, CoeffVectorType &hCoeffs, WorkSpaceType &workspace, bool extractQ)
Detailed Description
template<typename MatrixType, int Size, bool IsComplex>
struct Eigen::internal::tridiagonalization_inplace_selector< MatrixType, Size, IsComplex >
General full tridiagonalization
Member Typedef Documentation
HouseholderSequenceType
template<typename MatrixType , int Size, bool IsComplex> typedef Tridiagonalization<MatrixType>::HouseholderSequenceType Eigen::internal::tridiagonalization_inplace_selector< MatrixType, Size, IsComplex >::HouseholderSequenceType
Member Function Documentation
run()
template<typename MatrixType , int Size, bool IsComplex> template<typename DiagonalType , typename SubDiagonalType , typename CoeffVectorType , typename WorkSpaceType > static EIGEN_DEVICE_FUNC void Eigen::internal::tridiagonalization_inplace_selector< MatrixType, Size, IsComplex >::run (MatrixType & mat, DiagonalType & diag, SubDiagonalType & subdiag, CoeffVectorType & hCoeffs, WorkSpaceType & workspace, bool extractQ) inline static
{
     tridiagonalization_inplace(mat, hCoeffs);
     diag = mat.diagonal().real();
     subdiag = mat.template diagonal<-1>().real();
     if (extractQ) {
       HouseholderSequenceType(mat, hCoeffs.conjugate()).setLength(mat.rows() - 1).setShift(1).evalTo(mat, workspace);
     }
   }
References diag, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::diagonal(), diagonal(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo(), Eigen::real(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::rows(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setLength(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setShift(), and Eigen::internal::tridiagonalization_inplace().
Referenced by Eigen::internal::tridiagonalization_inplace().
The documentation for this struct was generated from the following file:
Tridiagonalization.h