MercuryDPM: Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, DenseShape > Struct Template Reference
Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, DenseShape > Struct Template Reference
#include <ProductEvaluators.h>
Public Types
typedef nested_eval< ExpressionType, 1 >::type MatrixType
typedef remove_all_t< MatrixType > MatrixTypeCleaned
Static Public Member Functions
template<typename Dest , typename PermutationType >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void run (Dest &dst, const PermutationType &perm, const ExpressionType &xpr)
Member Typedef Documentation
MatrixType
template<typename ExpressionType , int Side, bool Transposed> typedef nested_eval<ExpressionType, 1>::type Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, DenseShape >::MatrixType
MatrixTypeCleaned
template<typename ExpressionType , int Side, bool Transposed> typedef remove_all_t<MatrixType> Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, DenseShape >::MatrixTypeCleaned
Member Function Documentation
run()
template<typename ExpressionType , int Side, bool Transposed> template<typename Dest , typename PermutationType > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, DenseShape >::run (Dest & dst, const PermutationType & perm, const ExpressionType & xpr) inline static
{
     MatrixType mat(xpr);
     const Index n = Side == OnTheLeft ? mat.rows() : mat.cols();
     // FIXME we need an is_same for expression that is not sensitive to constness. For instance
     // is_same_xpr<Block<const Matrix>, Block<Matrix> >::value should be true.
     // if(is_same<MatrixTypeCleaned,Dest>::value && extract_data(dst) == extract_data(mat))
     if (is_same_dense(dst, mat)) {
       // apply the permutation inplace
       Matrix<bool, PermutationType::RowsAtCompileTime, 1, 0, PermutationType::MaxRowsAtCompileTime> mask(perm.size());
       mask.fill(false);
       Index r = 0;
       while (r < perm.size()) {
         // search for the next seed
         while (r < perm.size() && mask[r]) r++;
         if (r >= perm.size()) break;
         // we got one, let's follow it until we are back to the seed
         Index k0 = r++;
         Index kPrev = k0;
         mask.coeffRef(k0) = true;
         for (Index k = perm.indices().coeff(k0); k != k0; k = perm.indices().coeff(k)) {
           Block<Dest, Side == OnTheLeft ? 1 : Dest::RowsAtCompileTime,
                 Side == OnTheRight ? 1 : Dest::ColsAtCompileTime>(dst, k)
               .swap(Block < Dest, Side == OnTheLeft ? 1 : Dest::RowsAtCompileTime,
                     Side == OnTheRight
                         ? 1
                         : Dest::ColsAtCompileTime > (dst, ((Side == OnTheLeft) ^ Transposed) ? k0 : kPrev));
           mask.coeffRef(k) = true;
           kPrev = k;
         }
       }
     } else {
       for (Index i = 0; i < n; ++i) {
         Block<Dest, Side == OnTheLeft ? 1 : Dest::RowsAtCompileTime, Side == OnTheRight ? 1 : Dest::ColsAtCompileTime>(
             dst, ((Side == OnTheLeft) ^ Transposed) ? perm.indices().coeff(i) : i)
             =
                 Block < const MatrixTypeCleaned,
             Side == OnTheLeft ? 1 : MatrixTypeCleaned::RowsAtCompileTime,
             Side == OnTheRight ? 1
                                : MatrixTypeCleaned::ColsAtCompileTime >
                                      (mat, ((Side == OnTheRight) ^ Transposed) ? perm.indices().coeff(i) : i);
       }
     }
   }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::coeff(), Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::coeffRef(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::cols(), i, Eigen::internal::is_same_dense(), k, n, Eigen::OnTheLeft, Eigen::OnTheRight, UniformPSDSelfTest::r, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::rows(), and Eigen::internal::swap().
The documentation for this struct was generated from the following file:
ProductEvaluators.h