MercuryDPM: ModalPRefineableQPoissonElement< DIM > Class Template Reference
ModalPRefineableQPoissonElement< DIM > Class Template Reference
Public Types
typedef void(* PoissonSourceFctPt) (const Vector< double > &x, double &f)
Public Types inherited from oomph::PoissonEquations< DIM >
typedef void(* PoissonSourceFctPt) (const Vector< double > &x, double &f)
typedef void(* PoissonSourceFctGradientPt) (const Vector< double > &x, Vector< double > &gradient)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Types inherited from ModalPoissonEquations< DIM >
typedef void(* PoissonSourceFctPt) (const Vector< double > &x, double &f)
typedef void(* PoissonDiffFctPt) (const Vector< double > &x, double &f)
Function pointer to a diffusion function fxt(x,f(x))
Public Member Functions
ModalPRefineableQPoissonElement ()
Constructor, simply call the other constructors.
ModalPRefineableQPoissonElement (const ModalPRefineableQPoissonElement< DIM > &dummy)
Broken copy constructor.
unsigned nnode_1d () const
virtual void further_build ()
Further build: Copy source function pointer from father element.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: 1.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned nrecovery_order ()
void basis (const Vector< double > &s, Shape &basis) const
void dbasis_local (const Vector< double > &s, Shape &basis, DShape &dbasis) const
void d2basis_local (const Vector< double > &s, Shape &basis, DShape &dbasisds, DShape &d2basisds) const
double u (const unsigned &n) const
virtual unsigned nbasis () const
Number of basis functions.
void output (ostream &outfile)
Output with default number of plot points.
void output (ostream &outfile, const unsigned &nplot)
void output_fct (ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_error (ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void compute_energy_error (ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_grad_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
PoissonSourceFctPt & source_fct_pt ()
PoissonSourceFctPt source_fct_pt () const
unsigned self_test ()
Self-test: Return 0 for OK.
virtual double dbasis_eulerian (const Vector< double > &s, Shape &basis, DShape &dbasis) const
virtual double dbasis_eulerian_at_knot (const unsigned &ipt, Shape &basis, DShape &dbasis) const
virtual void dbasis_local_at_knot (const unsigned &ipt, Shape &basis, DShape &dbasisds) const
virtual double dshape_dbasis_and_dtest_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &basis, DShape &dbasisdx, Shape &test, DShape &dtestdx) const
virtual double dshape_dbasis_and_dtest_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &basis, DShape &dbasisdx, Shape &test, DShape &dtestdx) const
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_generic_residual_contribution (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
void assign_additional_local_eqn_numbers ()
Public Member Functions inherited from oomph::QPoissonElement< DIM, 2 >
QPoissonElement ()
QPoissonElement (const QPoissonElement< DIM, NNODE_1D > &dummy)=delete
Broken copy constructor.
void operator= (const QPoissonElement< DIM, NNODE_1D > &)=delete
Broken assignment operator.
unsigned required_nvalue (const unsigned &n) const
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &n_plot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &n_plot)
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Public Member Functions inherited from oomph::PoissonEquations< DIM >
PoissonEquations ()
Constructor (must initialise the Source_fct_pt to null)
PoissonEquations (const PoissonEquations &dummy)=delete
Broken copy constructor.
void operator= (const PoissonEquations &)=delete
Broken assignment operator.
virtual unsigned u_index_poisson () const
void point_output_data (const Vector< double > &s, Vector< double > &data)
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
std::string scalar_name_paraview (const unsigned &i) const
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void compute_norm (double &norm)
Compute norm of solution: square of the L2 norm.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
PoissonSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
PoissonSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
PoissonSourceFctGradientPt & source_fct_gradient_pt ()
Access function: Pointer to gradient of source function.
PoissonSourceFctGradientPt source_fct_gradient_pt () const
Access function: Pointer to gradient source function. Const version.
virtual void get_source_poisson (const unsigned &ipt, const Vector< double > &x, double &source) const
virtual void get_source_gradient_poisson (const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient) const
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux: flux[i] = du/dx_i.
void get_dflux_dnodal_u (const Vector< double > &s, Vector< Vector< double >> &dflux_dnodal_u) const
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual double interpolated_u_poisson (const Vector< double > &s) const
unsigned self_test ()
Self-test: Return 0 for OK.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void disable_ALE ()
virtual void enable_ALE ()
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from RefineableModalPoissonEquations< DIM >
RefineableModalPoissonEquations ()
Constructor, simply call other constructors.
RefineableModalPoissonEquations (const RefineableModalPoissonEquations< DIM > &dummy)
Broken copy constructor.
virtual unsigned u_index_poisson () const
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Standard flux.from Poisson equations.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get error against and norm of exact flux.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Public Member Functions inherited from ModalPoissonEquations< DIM >
ModalPoissonEquations ()
Constructor (must initialise the Source_fct_pt to null)
void output_fct (ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points.
void compute_error (ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
PoissonSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
PoissonSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
virtual void get_source_poisson (const Vector< double > &x, double &source) const
PoissonDiffFctPt & diff_fct_pt ()
Access function: Pointer to diffusivity function.
PoissonDiffFctPt diff_fct_pt () const
Access function: Pointer to source function. Const version.
virtual void get_diff (const Vector< double > &x, double &diff) const
void get_flux (const Vector< double > &s, Vector< double > &flux, unsigned p_order) const
Get flux: flux[i] = du/dx_i.
double interpolated_u (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
virtual unsigned required_nsons () const
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)=0
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void rebuild_from_sons (Mesh *&mesh_pt)=0
virtual void unbuild ()
virtual void deactivate_element ()
virtual bool nodes_built ()
Return true if all the nodes have been built, false if not.
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual Node * interpolating_node_pt (const unsigned &n, const int &value_id)
virtual double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
virtual Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
virtual unsigned ninterpolating_node (const int &value_id)
virtual unsigned ninterpolating_node_1d (const int &value_id)
virtual void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
virtual void check_integrity (double &max_error)=0
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual RefineableElement * root_element_pt ()
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
virtual void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
virtual void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
Pre-build the element.
virtual void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
virtual void further_setup_hanging_nodes ()
void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
unsigned nshape_controlling_nodes ()
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Public Member Functions inherited from oomph::ElementWithZ2ErrorEstimator
ElementWithZ2ErrorEstimator ()
Default empty constructor.
ElementWithZ2ErrorEstimator (const ElementWithZ2ErrorEstimator &)=delete
Broken copy constructor.
void operator= (const ElementWithZ2ErrorEstimator &)=delete
Broken assignment operator.
virtual unsigned ncompound_fluxes ()
virtual void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
virtual void get_Z2_compound_flux_indices (Vector< unsigned > &flux_index)
virtual double geometric_jacobian (const Vector< double > &x)
Public Member Functions inherited from ModalPRefineableQElement< DIM >
ModalPRefineableQElement ()
void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
void pre_build (Mesh *&, Vector< Node * > &)
void further_build ()
void p_refine (const int &inc, Mesh *const &mesh_pt, GeneralisedElement *const &clone_pt)
void shape (const Vector< double > &s, Shape &psi) const
void basis (const Vector< double > &s, Shape &basis) const
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsi) const
void dbasis_local (const Vector< double > &s, Shape &basis, DShape &dbasis) const
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
void d2basis_local (const Vector< double > &s, Shape &basis, DShape &dbasisds, DShape &d2basisds) const
void initial_setup (Tree *const &adopted_father_pt, const unsigned &initial_p_order)
void pre_build (Mesh *&, Vector< Node * > &)
void p_refine (const int &inc, Mesh *const &mesh_pt, GeneralisedElement *const &clone_pt)
Public Member Functions inherited from oomph::PRefineableQElement< DIM, 2 >
PRefineableQElement ()
Empty constuctor.
Additional Inherited Members
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions inherited from oomph::QPoissonElement< DIM, 2 >
double dshape_and_dtest_eulerian_poisson (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_poisson (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_poisson (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Protected Member Functions inherited from oomph::PoissonEquations< DIM >
virtual void fill_in_generic_residual_contribution_poisson (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from ModalPoissonEquations< DIM >
virtual void add_generic_residual_contribution (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Protected Attributes inherited from oomph::PoissonEquations< DIM >
PoissonSourceFctPt Source_fct_pt
Pointer to source function:
PoissonSourceFctGradientPt Source_fct_gradient_pt
Pointer to gradient of source function.
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from ModalPoissonEquations< DIM >
PoissonSourceFctPt Source_fct_pt
Pointer to source function:
PoissonDiffFctPt Diff_fct_pt
Pointer to the diffusivity function.
Vector< int > Local_eqn
Array to hold local eqn numbers: Local_eqn[n] (=-1 for BC)
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number – for plotting/validation purposes.
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Member Typedef Documentation
PoissonSourceFctPt
template<unsigned DIM> typedef void(* ModalPRefineableQPoissonElement< DIM >::PoissonSourceFctPt) (const Vector< double > &x, double &f)
Function pointer to source function fct(x,f(x)) – x is a Vector!
Constructor & Destructor Documentation
ModalPRefineableQPoissonElement() [1/2]
template<unsigned DIM> ModalPRefineableQPoissonElement< DIM >::ModalPRefineableQPoissonElement () inline
Constructor, simply call the other constructors.
                                    :
   RefineableElement(),
   RefineableModalPoissonEquations<DIM>(),
   ModalPRefineableQElement<DIM>(),
   QPoissonElement<DIM,2>()
    {
     // Set integration scheme
     // (To avoid memory leaks in pre-build and p-refine where new integration schemes are created)
     this->set_integration_scheme(new GaussLobattoLegendre<DIM,2>);
    }
ModalPRefineableQPoissonElement() [2/2]
template<unsigned DIM> ModalPRefineableQPoissonElement< DIM >::ModalPRefineableQPoissonElement (const ModalPRefineableQPoissonElement< DIM > & dummy) inline
Broken copy constructor.
   {
    BrokenCopy::broken_copy("ModalPRefineableQPoissonElement");
   }
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
assign_additional_local_eqn_numbers()
template<unsigned DIM> void ModalPRefineableQPoissonElement< DIM >::assign_additional_local_eqn_numbers virtual
Setup the local equation numbering schemes:
                /  local equation number.
Local_eqn[n] = | \ -1 if boundary condition.
Pure version without hanging nodes
Reimplemented from oomph::GeneralisedElement.
 {
  //Resize the equation counters
  this->Local_eqn.resize(this->p_order());
  //Loop over the nodes
  for(unsigned i=0;i<this->nnode_1d();i++)
   {
    //Set the local equation number to be the first value stored at the node
    this->Local_eqn[i] = this->nodal_local_eqn(i,0);
   }
  //Continue over the internal data
  for(unsigned i=this->nnode_1d();i<this->p_order();i++)
   {
    //Set the local equation number to be the ith value of the internal data
    this->Local_eqn[i] = this->internal_local_eqn(0,i-this->nnode_1d());
   }
 }
References i.
basis()
template<unsigned DIM> void ModalPRefineableQPoissonElement< DIM >::basis (const Vector< double > & s, Shape & basis) const inline virtual
Implements ModalPoissonEquations< DIM >.
   {ModalPRefineableQElement<DIM>::basis(s, basis);}
References ModalPRefineableQElement< DIM >::basis(), and s.
compute_energy_error()
template<unsigned DIM> void ModalPRefineableQPoissonElement< DIM >::compute_energy_error (ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_grad_pt, double & error, double & norm) inline
Get error against and norm of exact solution.
   {
    // Initialise
    error=0.0;
    norm=0.0;
    //Vector of local coordinates
    Vector<double> s(DIM);
    // Vector for coordintes
    Vector<double> x(DIM);
    //Set the value of n_intpt
    unsigned n_intpt = this->integral_pt()->nweight();
    // Setup output structure: Conversion is fishy but it's only output...
    unsigned nplot;
    if (DIM==1)
     {
      nplot=n_intpt;
     }
    else
     {
      nplot=unsigned(pow(n_intpt,1.0/double(DIM)));
     }
    // Tecplot header info
    outfile << this->tecplot_zone_string(nplot);
    // Exact solution Vector (here a scalar)
    Vector<double> exact_grad(1);
    //Loop over the integration points
    for(unsigned ipt=0;ipt<n_intpt;ipt++)
     {
      //Assign values of s
      for(unsigned i=0;i<DIM;i++)
       {
        s[i] = this->integral_pt()->knot(ipt,i);
       }
      //Get the integral weight
      double w = this->integral_pt()->weight(ipt);
      // Get jacobian of mapping
      double J=this->J_eulerian(s);
      //Premultiply the weights and the Jacobian
      double W = w*J;
      // Get x position as Vector
      this->interpolated_x(s,x);
      // Get FE du/dx
      Vector<double> dudx_fe(1);
      ModalPoissonEquations<1>::get_flux(s,dudx_fe,this->p_order());
      // Get exact solution at this point
      (*exact_grad_pt)(x,exact_grad);
      //Output x,y,...,error
      for(unsigned i=0;i<DIM;i++)
       {
        outfile << x[i] << " ";
       }
      outfile << exact_grad[0] << " " << exact_grad[0]-dudx_fe[0] << std::endl;
      // Add to error and norm
      norm+=exact_grad[0]*exact_grad[0]*W;
      error+=(exact_grad[0]-dudx_fe[0])*(exact_grad[0]-dudx_fe[0])*W;
     }
   }
References DIM, calibrate::error, ModalPoissonEquations< DIM >::get_flux(), i, J, Eigen::bfloat16_impl::pow(), s, w, oomph::QuadTreeNames::W, and plotDoE::x.
compute_error() [1/2]
template<unsigned DIM> void ModalPRefineableQPoissonElement< DIM >::compute_error (ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) inline
   {RefineableModalPoissonEquations<DIM>::compute_error(outfile,
                     exact_soln_pt, error, norm);}
References ModalPoissonEquations< DIM >::compute_error(), and calibrate::error.
compute_error() [2/2]
template<unsigned DIM> void ModalPRefineableQPoissonElement< DIM >::compute_error (ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) inline
   {RefineableModalPoissonEquations<DIM>::compute_error(outfile,
                     exact_soln_pt, time, error, norm);}
References ModalPoissonEquations< DIM >::compute_error(), and calibrate::error.
d2basis_local()
template<unsigned DIM> void ModalPRefineableQPoissonElement< DIM >::d2basis_local (const Vector< double > & s, Shape & basis, DShape & dbasisds, DShape & d2basisds) const inline
   {ModalPRefineableQElement<DIM>::d2basis_local(s, basis, dbasisds, d2basisds);}
References ModalPRefineableQElement< DIM >::d2basis_local(), and s.
dbasis_eulerian()
template<unsigned DIM> double ModalPRefineableQPoissonElement< DIM >::dbasis_eulerian (const Vector< double > & s, Shape & basis, DShape & dbasis) const virtual
Compute the geometric basis functions and also first derivatives w.r.t. global coordinates at local coordinate s; Returns Jacobian of mapping from global to local coordinates. Most general form of the function, but may be over-loaded, if desired
 {
  //Find the element dimension
  const unsigned el_dim = this->dim();
  //Get the values of the shape functions and their local derivatives
  //Temporarily stored in dpsi
  this->dbasis_local(s,basis,dbasis);
  //Allocate memory for the inverse jacobian
  DenseMatrix<double> inverse_jacobian(el_dim);
  //Now calculate the inverse jacobian
  const double det = this->local_to_eulerian_mapping(dbasis,inverse_jacobian);
  //Now set the values of the derivatives to be dpsidx
  this->transform_derivatives(inverse_jacobian,dbasis);
  //Return the determinant of the jacobian
  return det;
 }
References el_dim, and s.
dbasis_eulerian_at_knot()
template<unsigned DIM> double ModalPRefineableQPoissonElement< DIM >::dbasis_eulerian_at_knot (const unsigned & ipt, Shape & basis, DShape & dbasis) const virtual
Compute the geometric shape functions and also first derivatives w.r.t. global coordinates at integration point ipt. Most general form of function, but may be over-loaded if desired
 {
  //Find the element dimension
  const unsigned el_dim = this->dim();
  //Get the values of the shape function and local derivatives
  //Temporarily store it in dpsi
  this->dbasis_local_at_knot(ipt,basis,dbasis);
  //Allocate memory for the inverse jacobian
  DenseMatrix<double> inverse_jacobian(el_dim);
  //Now calculate the inverse jacobian
  const double det = this->local_to_eulerian_mapping(dbasis,inverse_jacobian);
  //Now set the values of the derivatives to dpsidx
  this->transform_derivatives(inverse_jacobian,dbasis);
  //Return the determinant of the jacobian
  return det;
 }
References el_dim.
dbasis_local()
template<unsigned DIM> void ModalPRefineableQPoissonElement< DIM >::dbasis_local (const Vector< double > & s, Shape & basis, DShape & dbasis) const inline
   {ModalPRefineableQElement<DIM>::dbasis_local(s, basis, dbasis);}
References ModalPRefineableQElement< DIM >::dbasis_local(), and s.
dbasis_local_at_knot()
template<unsigned DIM> virtual void ModalPRefineableQPoissonElement< DIM >::dbasis_local_at_knot (const unsigned & ipt, Shape & basis, DShape & dbasisds) const inline virtual
Return the shape function and its derivatives w.r.t. the local coordinates at the ipt-th integration point.
  {
   //Find the dimension of the element
   const unsigned el_dim = this->dim();
   //Storage for the local coordinates of the integration point
   Vector<double> s(el_dim);
   //Set the local coordinate
   for(unsigned i=0;i<el_dim;i++) {s[i] = this->integral_pt()->knot(ipt,i);}
   //Get the shape function and derivatives
   this->dbasis_local(s,basis,dbasisds);
  }
References el_dim, i, and s.
dshape_dbasis_and_dtest_eulerian()
template<unsigned DIM> virtual double ModalPRefineableQPoissonElement< DIM >::dshape_dbasis_and_dtest_eulerian (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & basis, DShape & dbasisdx, Shape & test, DShape & dtestdx) const inline virtual
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping
Implements ModalPoissonEquations< DIM >.
   {
    //Call the geometrical basis functions and derivatives
    double J = dbasis_eulerian(s,basis,dbasisdx);
    //Loop over the nodes and set the first nodal shapes equal to the basis functions
    for(unsigned i=0;i<this->nnode_1d();i++)
     {
      psi[i] = basis[i];
      dpsidx(i,0) = dbasisdx(i,0);
     }
    //Loop over the test functions and derivatives and set them equal to the
    //basis functions
    for(unsigned i=0;i<this->p_order();i++)
     {
      test[i] = basis[i];
      dtestdx(i,0) = dbasisdx(i,0);
     }
    //Return the jacobian
    return J;
   }
References i, J, and s.
dshape_dbasis_and_dtest_eulerian_at_knot()
template<unsigned DIM> virtual double ModalPRefineableQPoissonElement< DIM >::dshape_dbasis_and_dtest_eulerian_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & basis, DShape & dbasisdx, Shape & test, DShape & dtestdx) const inline virtual
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping
Implements ModalPoissonEquations< DIM >.
  {
   //Call the geometrical shape functions and derivatives
   double J = dbasis_eulerian_at_knot(ipt,basis,dbasisdx);
   Vector<double> s(1);
   s[0] = this->integral_pt()->knot(ipt,0);
   //Loop over the nodes and set the first nodal shapes equal to the basis functions
   for(unsigned i=0;i<this->nnode_1d();i++)
    {
     psi[i] = basis[i];
     dpsidx(i,0) = dbasisdx(i,0);
    }
   //Loop over the test functions and derivatives and set them equal to the
   //basis functions
   for(unsigned i=0;i<this->p_order();i++)
    {
     test[i] = basis[i];
     dtestdx(i,0) = dbasisdx(i,0);
    }
   //Return the jacobian
   return J;
  }
References i, J, and s.
fill_in_contribution_to_jacobian()
template<unsigned DIM> void ModalPRefineableQPoissonElement< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Add the element's contribution to its residual vector and element Jacobian matrix (wrapper)
Reimplemented from ModalPoissonEquations< DIM >.
   {RefineableModalPoissonEquations<DIM>::
       fill_in_contribution_to_jacobian(residuals, jacobian);}
References ModalPoissonEquations< DIM >::fill_in_contribution_to_jacobian().
fill_in_contribution_to_residuals()
template<unsigned DIM> void ModalPRefineableQPoissonElement< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Add the element's contribution to its residual vector (wrapper)
Reimplemented from ModalPoissonEquations< DIM >.
   {RefineableModalPoissonEquations<DIM>::
       fill_in_contribution_to_residuals(residuals);}
References ModalPoissonEquations< DIM >::fill_in_contribution_to_residuals().
fill_in_generic_residual_contribution()
template<unsigned DIM> void ModalPRefineableQPoissonElement< DIM >::fill_in_generic_residual_contribution (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) inline
   {RefineableModalPoissonEquations<DIM>::
       fill_in_generic_residual_contribution(residuals, jacobian, flag);}
References RefineableModalPoissonEquations< DIM >::fill_in_generic_residual_contribution().
further_build()
template<unsigned DIM> void ModalPRefineableQPoissonElement< DIM >::further_build virtual
Further build: Copy source function pointer from father element.
Reimplemented from RefineableModalPoissonEquations< DIM >.
 {
  // Do the ModalPRefineableQElement further build
  ModalPRefineableQElement<DIM>::further_build();
  // Needed to set the source function pointer
  RefineableModalPoissonEquations<DIM>::further_build();
 }
References RefineableModalPoissonEquations< DIM >::further_build(), and ModalPRefineableQElement< DIM >::further_build().
get_dresidual_dnodal_coordinates()
template<unsigned DIM> virtual void ModalPRefineableQPoissonElement< DIM >::get_dresidual_dnodal_coordinates (RankThreeTensor< double > & dresidual_dnodal_coordinates) inline virtual
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}
Compute derivatives of elemental residual vector with respect to nodal coordinates. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij} Overloads the FD-based version in the FE base class.
Reimplemented from RefineableModalPoissonEquations< DIM >.
   {ModalPoissonEquations<DIM>::
       get_dresidual_dnodal_coordinates(dresidual_dnodal_coordinates);}
References oomph::FiniteElement::get_dresidual_dnodal_coordinates().
nbasis()
template<unsigned DIM> virtual unsigned ModalPRefineableQPoissonElement< DIM >::nbasis () const inline virtual
Number of basis functions.
Implements ModalPoissonEquations< DIM >.
   {return this->p_order();}
ncont_interpolated_values()
template<unsigned DIM> unsigned ModalPRefineableQPoissonElement< DIM >::ncont_interpolated_values () const inline virtual
Number of continuously interpolated values: 1.
Implements oomph::RefineableElement.
 {return 1;}
nnode_1d()
template<unsigned DIM> unsigned ModalPRefineableQPoissonElement< DIM >::nnode_1d () const inline virtual
Return the number of nodes along one edge of the element Default is to return zero — must be overloaded by geometric elements
Reimplemented from oomph::FiniteElement.
 {return 2;}
nrecovery_order()
template<unsigned DIM> unsigned ModalPRefineableQPoissonElement< DIM >::nrecovery_order () inline virtual
Order of recovery shape functions for Z2 error estimation:
Same order as shape functions.
Constant recovery order, since recovery order of the first element is used for the whole mesh.
Implements oomph::ElementWithZ2ErrorEstimator.
 {return 3;}
nvertex_node()
template<unsigned DIM> unsigned ModalPRefineableQPoissonElement< DIM >::nvertex_node () const inline virtual
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
   {return QPoissonElement<DIM,2>::nvertex_node();}
output() [1/2]
template<unsigned DIM> void ModalPRefineableQPoissonElement< DIM >::output (ostream & outfile) inline virtual
Output with default number of plot points.
Reimplemented from ModalPoissonEquations< DIM >.
   {RefineableModalPoissonEquations<DIM>::output(outfile);}
References ModalPoissonEquations< DIM >::output().
output() [2/2]
template<unsigned DIM> void ModalPRefineableQPoissonElement< DIM >::output (ostream & outfile, const unsigned & nplot) inline virtual
Output FE representation of soln: x,y,u or x,y,z,u at Nplot^DIM plot points
Reimplemented from ModalPoissonEquations< DIM >.
   {RefineableModalPoissonEquations<DIM>::output(outfile, nplot);}
References ModalPoissonEquations< DIM >::output().
output_fct() [1/2]
template<unsigned DIM> void ModalPRefineableQPoissonElement< DIM >::output_fct (ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) inline virtual
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points (dummy time-dependent version to keep intel compiler happy)
Reimplemented from ModalPoissonEquations< DIM >.
   {RefineableModalPoissonEquations<DIM>::output_fct(outfile, nplot, time,
                          exact_soln_pt);}
References ModalPoissonEquations< DIM >::output_fct().
output_fct() [2/2]
template<unsigned DIM> void ModalPRefineableQPoissonElement< DIM >::output_fct (ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) inline
   {RefineableModalPoissonEquations<DIM>::output_fct(outfile, nplot,
                  exact_soln_pt);}
References ModalPoissonEquations< DIM >::output_fct().
self_test()
template<unsigned DIM> unsigned ModalPRefineableQPoissonElement< DIM >::self_test () inline virtual
Self-test: Return 0 for OK.
Reimplemented from ModalPoissonEquations< DIM >.
  {return RefineableModalPoissonEquations<DIM>::self_test();}
References ModalPoissonEquations< DIM >::self_test().
source_fct_pt() [1/2]
template<unsigned DIM> PoissonSourceFctPt& ModalPRefineableQPoissonElement< DIM >::source_fct_pt () inline
   {return RefineableModalPoissonEquations<DIM>::source_fct_pt();}
References ModalPoissonEquations< DIM >::source_fct_pt().
source_fct_pt() [2/2]
template<unsigned DIM> PoissonSourceFctPt ModalPRefineableQPoissonElement< DIM >::source_fct_pt () const inline
   {return RefineableModalPoissonEquations<DIM>::source_fct_pt();}
References ModalPoissonEquations< DIM >::source_fct_pt().
u()
template<unsigned DIM> double ModalPRefineableQPoissonElement< DIM >::u (const unsigned & n) const inline virtual
Access function: Nodal function value at local node n Uses suitably interpolated value for hanging nodes.
Implements ModalPoissonEquations< DIM >.
   {
    if(n < this->nnode())
     {
      return this->nodal_value(n,0);
     }
    else
     {
      return this->internal_data_pt(0)->value(n-this->nnode());
     }
   }
References n.
vertex_node_pt()
template<unsigned DIM> Node* ModalPRefineableQPoissonElement< DIM >::vertex_node_pt (const unsigned & j) const inline virtual
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
   {return QPoissonElement<DIM,2>::vertex_node_pt(j);}
References j.
The documentation for this class was generated from the following file:
one_d_poisson_hp_adapt.cc