MercuryDPM: DropInChannelProblem< ELEMENT > Class Template Reference
DropInChannelProblem< ELEMENT > Class Template Reference
Problem class to simulate viscous drop propagating along 2D channel.
Public Member Functions
DropInChannelProblem ()
Constructor.
~DropInChannelProblem ()
Destructor.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of free surface elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of free surface elements.
void actions_after_newton_solve ()
Update the after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve.
void complete_problem_setup ()
Set boundary conditions and complete the build of all elements.
void doc_solution (const std::string &comment="")
Doc the solution.
void compute_error_estimate (double &max_err, double &min_err)
Compute the error estimates and assign to elements for plotting.
void remove_volume_constraint ()
Change the boundary conditions to remove the volume constraint.
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Private Types
enum {
Inflow_boundary_id =0 , Upper_wall_boundary_id =1 , Outflow_boundary_id =2 , Bottom_wall_boundary_id =3 ,
First_drop_boundary_id =4 , Second_drop_boundary_id =5
}
Enumeration of channel boundaries.
Private Member Functions
void create_free_surface_elements ()
Create free surface elements.
void delete_free_surface_elements ()
Delete free surface elements.
void create_volume_constraint_elements ()
Create elements that impose volume constraint on the drop.
void delete_volume_constraint_elements ()
Delete volume constraint elements.
Private Attributes
Mesh * Free_surface_mesh_pt
Pointers to mesh of free surface elements.
Mesh * Volume_constraint_mesh_pt
Pointer to mesh containing elements that impose volume constraint.
RefineableSolidTriangleMesh< ELEMENT > * Fluid_mesh_pt
Pointer to Fluid_mesh.
Vector< TriangleMeshPolygon * > Drop_polygon_pt
Vector storing pointer to the drop polygons.
TriangleMeshPolygon * Outer_boundary_polyline_pt
Triangle mesh polygon for outer boundary.
Data * Drop_pressure_data_pt
Pointer to a global drop pressure datum.
VolumeConstraintElement * Vol_constraint_el_pt
Pointer to element that imposes volume constraint for drop.
double Initial_value_for_drop_pressure
Backed up drop pressure between adaptations.
ELEMENT * Hijacked_element_pt
Pointer to hijacked element.
bool Use_volume_constraint
Bool to indicate if volume constraint is applied (only for steady run)
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_convergence_check ()
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_before_implicit_timestep ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual void set_initial_condition ()
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class ELEMENT>
class DropInChannelProblem< ELEMENT >
Problem class to simulate viscous drop propagating along 2D channel.
Member Enumeration Documentation
anonymous enum
template<class ELEMENT > anonymous enum private
Enumeration of channel boundaries.
Enumerator
Inflow_boundary_id
Upper_wall_boundary_id
Outflow_boundary_id
Bottom_wall_boundary_id
First_drop_boundary_id
Second_drop_boundary_id
  {
   Inflow_boundary_id=0,
   Upper_wall_boundary_id=1,
   Outflow_boundary_id=2,
   Bottom_wall_boundary_id=3,
   First_drop_boundary_id=4,
   Second_drop_boundary_id=5
  };
Constructor & Destructor Documentation
DropInChannelProblem()
template<class ELEMENT > DropInChannelProblem< ELEMENT >::DropInChannelProblem
Constructor.
 {
  // Output directory
  Problem_Parameter::Doc_info.set_directory("RESLT");
  // Allocate the timestepper -- this constructs the Problem's
  // time object with a sufficient amount of storage to store the
  // previous timsteps.
  this->add_time_stepper_pt(new BDF<2>);
  // Build the boundary segments for outer boundary, consisting of
  //--------------------------------------------------------------
  // four separate polylines
  //------------------------
  Vector<TriangleMeshCurveSection*> boundary_polyline_pt(4);
  // Each polyline only has two vertices -- provide storage for their
  // coordinates
  Vector<Vector<double> > vertex_coord(2);
  for(unsigned i=0;i<2;i++)
   {
    vertex_coord[i].resize(2);
   }
  // First polyline: Inflow
  vertex_coord[0][0]=0.0;
  vertex_coord[0][1]=0.0;
  vertex_coord[1][0]=0.0;
  vertex_coord[1][1]=1.0;
  // Build the 1st boundary polyline
  boundary_polyline_pt[0] = new TriangleMeshPolyLine(vertex_coord,
                                                    Inflow_boundary_id);
  // Second boundary polyline: Upper wall
  vertex_coord[0][0]=0.0;
  vertex_coord[0][1]=1.0;
  vertex_coord[1][0]=Problem_Parameter::Length;
  vertex_coord[1][1]=1.0;
  // Build the 2nd boundary polyline
  boundary_polyline_pt[1] = new TriangleMeshPolyLine(vertex_coord,
                                                    Upper_wall_boundary_id);
  // Third boundary polyline: Outflow
  vertex_coord[0][0]=Problem_Parameter::Length;
  vertex_coord[0][1]=1.0;
  vertex_coord[1][0]=Problem_Parameter::Length;
  vertex_coord[1][1]=0.0;
  // Build the 3rd boundary polyline
  boundary_polyline_pt[2] = new TriangleMeshPolyLine(vertex_coord,
                                                    Outflow_boundary_id);
  // Fourth boundary polyline: Bottom wall
  vertex_coord[0][0]=Problem_Parameter::Length;
  vertex_coord[0][1]=0.0;
  vertex_coord[1][0]=0.0;
  vertex_coord[1][1]=0.0;
  // Build the 4th boundary polyline
  boundary_polyline_pt[3] = new TriangleMeshPolyLine(vertex_coord,
                                                     Bottom_wall_boundary_id);
  // Create the triangle mesh polygon for outer boundary
  Outer_boundary_polyline_pt = new TriangleMeshPolygon(boundary_polyline_pt);
  // Now define initial shape of drop(s) with polygon
  //---------------------------------------------------
  // We have one drop
  Drop_polygon_pt.resize(1);
  // Place it smack in the middle of the channel
  double x_center = 0.5*Problem_Parameter::Length;
  double y_center = 0.5;
  Ellipse * drop_pt = new Ellipse(Problem_Parameter::Radius,
                                        Problem_Parameter::Radius);
  // Intrinsic coordinate along GeomObject defining the drop
  Vector<double> zeta(1);
  // Position vector to GeomObject defining the drop
  Vector<double> coord(2);
  // Number of points defining drop
  unsigned npoints = 16;
  double unit_zeta = MathematicalConstants::Pi/double(npoints-1);
  // This drop is bounded by two distinct boundaries, each
  // represented by its own polyline
  Vector<TriangleMeshCurveSection*> drop_polyline_pt(2);
  // Vertex coordinates
  Vector<Vector<double> > drop_vertex(npoints);
  // Create points on boundary
  for(unsigned ipoint=0; ipoint<npoints;ipoint++)
   {
    // Resize the vector
    drop_vertex[ipoint].resize(2);
    // Get the coordinates
    zeta[0]=unit_zeta*double(ipoint);
    drop_pt->position(zeta,coord);
    // Shift
    drop_vertex[ipoint][0]=coord[0]+x_center;
    drop_vertex[ipoint][1]=coord[1]+y_center;
   }
  // Build the 1st drop polyline
  drop_polyline_pt[0] = new TriangleMeshPolyLine(drop_vertex,
                                                 First_drop_boundary_id);
  // Second boundary of drop
  for(unsigned ipoint=0; ipoint<npoints;ipoint++)
   {
    // Resize the vector
    drop_vertex[ipoint].resize(2);
    // Get the coordinates
    zeta[0]=(unit_zeta*double(ipoint))+MathematicalConstants::Pi;
    drop_pt->position(zeta,coord);
    // Shift
    drop_vertex[ipoint][0]=coord[0]+x_center;
    drop_vertex[ipoint][1]=coord[1]+y_center;
   }
  // Build the 2nd drop polyline
  drop_polyline_pt[1] = new TriangleMeshPolyLine(drop_vertex,
                                                 Second_drop_boundary_id);
  // Create closed polygon from two polylines
  Drop_polygon_pt[0] = new TriangleMeshPolygon(
          drop_polyline_pt);
  // Now build the mesh, based on the boundaries specified by
  //---------------------------------------------------------
  // polygons just created
  //----------------------
  // Convert to "closed curve" objects
  TriangleMeshClosedCurve* outer_closed_curve_pt=Outer_boundary_polyline_pt;
  unsigned nb=Drop_polygon_pt.size();
  Vector<TriangleMeshClosedCurve*> drop_closed_curve_pt(nb);
  for (unsigned i=0;i<nb;i++)
   {
    drop_closed_curve_pt[i]=Drop_polygon_pt[i];
   }
  // Target area for initial mesh
  double uniform_element_area=0.2;
  // Define coordinates of a point inside the drop
  Vector<double> drop_center(2);
  drop_center[0]=x_center;
  drop_center[1]=y_center;
  // Use the TriangleMeshParameters object for gathering all
  // the necessary arguments for the TriangleMesh object
  TriangleMeshParameters triangle_mesh_parameters(
    outer_closed_curve_pt);
  // Define the holes on the boundary
  triangle_mesh_parameters.internal_closed_curve_pt() =
    drop_closed_curve_pt;
  // Define the maximum element area
  triangle_mesh_parameters.element_area() =
    uniform_element_area;
  // Define the region
  triangle_mesh_parameters.add_region_coordinates(1, drop_center);
  // Create the mesh
  Fluid_mesh_pt =
    new RefineableSolidTriangleMesh<ELEMENT>(
      triangle_mesh_parameters, this->time_stepper_pt());
  // Set error estimator for bulk mesh
  Z2ErrorEstimator* error_estimator_pt=new Z2ErrorEstimator;
  Fluid_mesh_pt->spatial_error_estimator_pt()=error_estimator_pt;
  // Set targets for spatial adaptivity
  Fluid_mesh_pt->max_permitted_error()=0.005;
  Fluid_mesh_pt->min_permitted_error()=0.001;
  Fluid_mesh_pt->max_element_size()=0.2;
  Fluid_mesh_pt->min_element_size()=0.001;
  // Use coarser mesh during validation
  if (CommandLineArgs::command_line_flag_has_been_set("--validation"))
   {
    Fluid_mesh_pt->min_element_size()=0.01;
   }
  // Output boundary and mesh initial mesh for information
  this->Fluid_mesh_pt->output_boundaries("boundaries.dat");
  this->Fluid_mesh_pt->output("mesh.dat");
  // Provide initial value for drop pressure
  Initial_value_for_drop_pressure=Problem_Parameter::Ca/
   Problem_Parameter::Radius;
  // Set boundary condition and complete the build of all elements
  complete_problem_setup();
  // Construct the mesh of elements that impose the volume constraint
  Use_volume_constraint=true;
  Volume_constraint_mesh_pt = new Mesh;
  create_volume_constraint_elements();
  // Construct the mesh of free surface elements
  Free_surface_mesh_pt=new Mesh;
  create_free_surface_elements();
  // Combine meshes
  //---------------
  // Add volume constraint sub mesh
  this->add_sub_mesh(this->Volume_constraint_mesh_pt);
  // Add Fluid_mesh_pt sub meshes
  this->add_sub_mesh(Fluid_mesh_pt);
  // Add Free_surface sub meshes
  this->add_sub_mesh(this->Free_surface_mesh_pt);
  // Build global mesh
  this->build_global_mesh();
  // Setup equation numbering scheme
  cout <<"Number of equations: " << this->assign_eqn_numbers() << std::endl;
 } // end_of_constructor
References oomph::TriangleMeshParameters::add_region_coordinates(), Problem_Parameter::Ca, oomph::CommandLineArgs::command_line_flag_has_been_set(), Problem_Parameter::Doc_info, oomph::TriangleMeshParameters::element_area(), MeshRefinement::error_estimator_pt, i, oomph::TriangleMeshParameters::internal_closed_curve_pt(), Problem_Parameter::Length, nb, BiharmonicTestFunctions2::Pi, oomph::Ellipse::position(), Problem_Parameter::Radius, oomph::DocInfo::set_directory(), and Eigen::zeta().
~DropInChannelProblem()
template<class ELEMENT > DropInChannelProblem< ELEMENT >::~DropInChannelProblem () inline
Destructor.
   {
    // Fluid timestepper
    delete this->time_stepper_pt(0);
    // Kill data associated with outer boundary
    unsigned n=Outer_boundary_polyline_pt->npolyline();
    for (unsigned j=0;j<n;j++)
     {
      delete Outer_boundary_polyline_pt->polyline_pt(j);
     }
    delete Outer_boundary_polyline_pt;
    //Kill data associated with drops
    unsigned n_drop = Drop_polygon_pt.size();
    for(unsigned idrop=0;idrop<n_drop;idrop++)
     {
      unsigned n=Drop_polygon_pt[idrop]->npolyline();
      for (unsigned j=0;j<n;j++)
       {
        delete Drop_polygon_pt[idrop]->polyline_pt(j);
       }
      delete Drop_polygon_pt[idrop];
     }
    // Flush element of free surface elements
    delete_free_surface_elements();
    delete Free_surface_mesh_pt;
    delete_volume_constraint_elements();
    delete Volume_constraint_mesh_pt;
    // Delete error estimator
    delete Fluid_mesh_pt->spatial_error_estimator_pt();
    // Delete fluid mesh
    delete Fluid_mesh_pt;
    // Delete the global pressure drop data
    delete Drop_pressure_data_pt;
    // Kill const eqn
    delete Problem_Parameter::Constitutive_law_pt;
   }
References Problem_Parameter::Constitutive_law_pt, j, and n.
Member Function Documentation
actions_after_adapt()
template<class ELEMENT > void DropInChannelProblem< ELEMENT >::actions_after_adapt () inline virtual
Actions after adapt: Rebuild the mesh of free surface elements.
Reimplemented from oomph::Problem.
   {
    // Create the elements that impose the displacement constraint
    create_free_surface_elements();
    create_volume_constraint_elements();
    // Rebuild the Problem's global mesh from its various sub-meshes
    this->rebuild_global_mesh();
    // Setup the problem again -- remember that fluid mesh has been
    // completely rebuilt and its element's don't have any
    // pointers to Re etc. yet
    complete_problem_setup();
   }// end of actions_after_adapt
actions_after_newton_solve()
template<class ELEMENT > void DropInChannelProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_adapt()
template<class ELEMENT > void DropInChannelProblem< ELEMENT >::actions_before_adapt () inline virtual
Actions before adapt: Wipe the mesh of free surface elements.
Reimplemented from oomph::Problem.
   {
    // Kill the  elements and wipe surface mesh
    delete_free_surface_elements();
    delete_volume_constraint_elements();
    // Rebuild the Problem's global mesh from its various sub-meshes
    this->rebuild_global_mesh();
   }// end of actions_before_adapt
actions_before_newton_solve()
template<class ELEMENT > void DropInChannelProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve.
Reimplemented from oomph::Problem.
   {
    //Reset the Lagrangian coordinates of the nodes to be the current
    //Eulerian coordinates -- this makes the current configuration
    //stress free
    Fluid_mesh_pt->set_lagrangian_nodal_coordinates();
   }
complete_problem_setup()
template<class ELEMENT > void DropInChannelProblem< ELEMENT >::complete_problem_setup
Set boundary conditions and complete the build of all elements.
   {
    // Map to record if a given boundary is on a drop or not
    map<unsigned,bool> is_on_drop_bound;
    // Loop over the drops
    unsigned ndrop=Drop_polygon_pt.size();
    for(unsigned idrop=0;idrop<ndrop;idrop++)
     {
      // Get the vector all boundary IDs associated with the polylines that
      // make up the closed polygon
      Vector<unsigned> drop_bound_id=this->Drop_polygon_pt[idrop]->
       polygon_boundary_id();
      // Get the number of boundary
      unsigned nbound=drop_bound_id.size();
      // Fill in the map
      for(unsigned ibound=0;ibound<nbound;ibound++)
       {
        // This boundary...
        unsigned bound_id=drop_bound_id[ibound];
        // ...is on the drop
        is_on_drop_bound[bound_id]=true;
       }
     }
    // Re-set the boundary conditions for fluid problem: All nodes are
    // free by default -- just pin the ones that have Dirichlet conditions
    // here.
    unsigned nbound=Fluid_mesh_pt->nboundary();
    for(unsigned ibound=0;ibound<nbound;ibound++)
     {
      unsigned num_nod=Fluid_mesh_pt->nboundary_node(ibound);
      for (unsigned inod=0;inod<num_nod;inod++)
       {
        // Get node
        Node* nod_pt=Fluid_mesh_pt->boundary_node_pt(ibound,inod);
        //Pin both velocities on inflow (0) and side boundaries (1 and 3)
        if((ibound==0) || (ibound==1) || (ibound==3))
         {
          nod_pt->pin(0);
          nod_pt->pin(1);
         }
        //If it's the outflow pin only the vertical velocity
        if(ibound==2) {nod_pt->pin(1);}
        // Pin pseudo-solid positions apart from drop boundary which
        // we allow to move
        SolidNode* solid_node_pt = dynamic_cast<SolidNode*>(nod_pt);
        if(is_on_drop_bound[ibound])
         {
          solid_node_pt->unpin_position(0);
          solid_node_pt->unpin_position(1);
         }
        else
         {
          solid_node_pt->pin_position(0);
          solid_node_pt->pin_position(1);
         }
       }
     } // end loop over boundaries
    // Complete the build of all elements so they are fully functional
    // Remember that adaptation for triangle meshes involves a complete
    // regneration of the mesh (rather than splitting as in tree-based
    // meshes where such parameters can be passed down from the father
    // element!)
    unsigned n_element = Fluid_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement to the present element
      ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Fluid_mesh_pt->element_pt(e));
      // Set the Reynolds number
      el_pt->re_pt() = &Problem_Parameter::Re;
      // Set the Womersley number (same as Re since St=1)
      el_pt->re_st_pt() = &Problem_Parameter::Re;
      // Set the constitutive law for pseudo-elastic mesh deformation
      el_pt->constitutive_law_pt()=Problem_Parameter::Constitutive_law_pt;
     }
    //For the elements within the droplet (region 1),
    //set the viscosity ratio
    n_element = Fluid_mesh_pt->nregion_element(1);
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement to the present element
      ELEMENT* el_pt =
       dynamic_cast<ELEMENT*>(Fluid_mesh_pt->region_element_pt(1,e));
      el_pt->viscosity_ratio_pt() = &Problem_Parameter::Viscosity_ratio;
     }
    // Re-apply boundary values on Dirichlet boundary conditions
    // (Boundary conditions are ignored when the solution is transferred
    // from the old to the new mesh by projection; this leads to a slight
    // change in the boundary values (which are, of course, never changed,
    // unlike the actual unknowns for which the projected values only
    // serve as an initial guess)
    // Set velocity and history values of velocity on walls
    nbound=this->Fluid_mesh_pt->nboundary();
    for(unsigned ibound=0;ibound<nbound;++ibound)
     {
      if ((ibound==Upper_wall_boundary_id)||
          (ibound==Bottom_wall_boundary_id)||
          (ibound==Outflow_boundary_id) ||
          (ibound==Inflow_boundary_id))
       {
        // Loop over nodes on this boundary
        unsigned num_nod=this->Fluid_mesh_pt->nboundary_node(ibound);
        for (unsigned inod=0;inod<num_nod;inod++)
         {
          // Get node
          Node* nod_pt=this->Fluid_mesh_pt->boundary_node_pt(ibound,inod);
          // Get number of previous (history) values
          unsigned n_prev=nod_pt->time_stepper_pt()->nprev_values();
          // Velocity is and was zero at all previous times
          for (unsigned t=0;t<=n_prev;t++)
           {
            if (ibound!=Inflow_boundary_id)
             {
              // Parallel outflow
              if (ibound!=Outflow_boundary_id)
               {
                nod_pt->set_value(t,0,0.0);
               }
              nod_pt->set_value(t,1,0.0);
             }
            // Nodes have always been there...
            nod_pt->x(t,0)=nod_pt->x(0,0);
            nod_pt->x(t,1)=nod_pt->x(0,1);
           }
         }
       }
     }
    // Re-assign prescribed inflow velocity at inlet
    unsigned num_nod=this->Fluid_mesh_pt->nboundary_node(Inflow_boundary_id);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      // Get node
      Node* nod_pt=this->Fluid_mesh_pt->boundary_node_pt(Inflow_boundary_id,
                                                         inod);
      //Now set the boundary velocity
      double y = nod_pt->x(1);
      nod_pt->set_value(0,Problem_Parameter::Inflow_veloc_magnitude*y*(1-y));
     }
   }
References Problem_Parameter::Constitutive_law_pt, e(), Problem_Parameter::Inflow_veloc_magnitude, oomph::TimeStepper::nprev_values(), oomph::Data::pin(), oomph::SolidNode::pin_position(), Problem_Parameter::Re, oomph::Data::set_value(), plotPSD::t, oomph::Data::time_stepper_pt(), oomph::SolidNode::unpin_position(), Problem_Parameter::Viscosity_ratio, oomph::Node::x(), and y.
compute_error_estimate()
template<class ELEMENT > void DropInChannelProblem< ELEMENT >::compute_error_estimate (double & max_err, double & min_err)
Compute the error estimates and assign to elements for plotting.
Compute error estimates and assign to elements for plotting.
 {
  // Get error estimator
  ErrorEstimator* err_est_pt=Fluid_mesh_pt->spatial_error_estimator_pt();
  // Get/output error estimates
  unsigned nel=Fluid_mesh_pt->nelement();
  Vector<double> elemental_error(nel);
  // We need a dynamic cast, get_element_errors from the Fluid_mesh_pt
  // Dynamic cast is used because get_element_errors require a Mesh* ans
  // not a SolidMesh*
  Mesh* fluid_mesh_pt=dynamic_cast<Mesh*>(Fluid_mesh_pt);
  err_est_pt->get_element_errors(fluid_mesh_pt,
                                 elemental_error);
  // Set errors for post-processing and find extrema
  max_err=0.0;
  min_err=DBL_MAX;
  for (unsigned e=0;e<nel;e++)
   {
    dynamic_cast<MyCrouzeixRaviartElement*>(Fluid_mesh_pt->element_pt(e))->
     set_error(elemental_error[e]);
    max_err=std::max(max_err,elemental_error[e]);
    min_err=std::min(min_err,elemental_error[e]);
   }
 }
References e(), oomph::ErrorEstimator::get_element_errors(), max, min, and set_error().
create_free_surface_elements()
template<class ELEMENT > void DropInChannelProblem< ELEMENT >::create_free_surface_elements private
Create free surface elements.
Create elements that impose the kinematic and dynamic bcs for the pseudo-solid fluid mesh
 {
  //Loop over the free surface boundaries
  unsigned nb=Fluid_mesh_pt->nboundary();
  for(unsigned b=First_drop_boundary_id;b<nb;b++)
   {
    // Note: region is important
    // How many bulk fluid elements are adjacent to boundary b in region 0?
    unsigned n_element = Fluid_mesh_pt->nboundary_element_in_region(b,0);
    // Loop over the bulk fluid elements adjacent to boundary b?
    for(unsigned e=0;e<n_element;e++)
     {
      // Get pointer to the bulk fluid element that is
      // adjacent to boundary b in region 0
      ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
       Fluid_mesh_pt->boundary_element_in_region_pt(b,0,e));
      //Find the index of the face of element e along boundary b in region 0
      int face_index = Fluid_mesh_pt->face_index_at_boundary_in_region(b,0,e);
      // Create new element
      ElasticLineFluidInterfaceElement<ELEMENT>* el_pt =
       new ElasticLineFluidInterfaceElement<ELEMENT>(
        bulk_elem_pt,face_index);
      // Add it to the mesh
      Free_surface_mesh_pt->add_element_pt(el_pt);
      //Add the appropriate boundary number
      el_pt->set_boundary_number_in_bulk_mesh(b);
      //Specify the capillary number
      el_pt->ca_pt() = &Problem_Parameter::Ca;
     }
   }
 }
References b, Problem_Parameter::Ca, oomph::FluidInterfaceElement::ca_pt(), e(), nb, and oomph::FaceElement::set_boundary_number_in_bulk_mesh().
create_volume_constraint_elements()
template<class ELEMENT > void DropInChannelProblem< ELEMENT >::create_volume_constraint_elements private
Create elements that impose volume constraint on the drop.
 {
  // Do we need it?
  if (!Use_volume_constraint) return;
  // Store pointer to element whose pressure we're trading/hi-jacking:
  // Element 0 in region 1
  Hijacked_element_pt= dynamic_cast<ELEMENT*>(
   Fluid_mesh_pt->region_element_pt(1,0));
  // Set the global pressure data by hijacking one of the pressure values
  // from inside the droplet
  unsigned index_of_traded_pressure=0;
  Drop_pressure_data_pt=Hijacked_element_pt->
   hijack_internal_value(0,index_of_traded_pressure);
  // Build volume constraint element -- pass traded pressure to it
  Vol_constraint_el_pt=
   new VolumeConstraintElement(&Problem_Parameter::Volume,
                               Drop_pressure_data_pt,
                               index_of_traded_pressure);
   //Provide a reasonable initial guess for drop pressure (hydrostatics):
  Drop_pressure_data_pt->set_value(index_of_traded_pressure,
                                     Initial_value_for_drop_pressure);
  // Add volume constraint element to the mesh
  Volume_constraint_mesh_pt->add_element_pt(Vol_constraint_el_pt);
  //Loop over the free surface boundaries
  unsigned nb=Fluid_mesh_pt->nboundary();
  for(unsigned b=First_drop_boundary_id;b<nb;b++)
   {
    // Note region is important
    // How many bulk fluid elements are adjacent to boundary b in region 0?
    unsigned n_element = Fluid_mesh_pt->nboundary_element_in_region(b,0);
    // Loop over the bulk fluid elements adjacent to boundary b?
    for(unsigned e=0;e<n_element;e++)
     {
      // Get pointer to the bulk fluid element that is
      // adjacent to boundary b in region 0?
      ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
       Fluid_mesh_pt->boundary_element_in_region_pt(b,0,e));
      //Find the index of the face of element e along boundary b in region 0
      int face_index = Fluid_mesh_pt->face_index_at_boundary_in_region(b,0,e);
      // Create new element
      ElasticLineVolumeConstraintBoundingElement<ELEMENT>* el_pt =
       new ElasticLineVolumeConstraintBoundingElement<ELEMENT>(
        bulk_elem_pt,face_index);
      //Set the "master" volume constraint element
      el_pt->set_volume_constraint_element(Vol_constraint_el_pt);
      // Add it to the mesh
      Volume_constraint_mesh_pt->add_element_pt(el_pt);
     }
   }
 }
References b, e(), nb, oomph::VolumeConstraintBoundingElement::set_volume_constraint_element(), and Problem_Parameter::Volume.
delete_free_surface_elements()
template<class ELEMENT > void DropInChannelProblem< ELEMENT >::delete_free_surface_elements () inline private
Delete free surface elements.
   {
    // How many surface elements are in the surface mesh
    unsigned n_element = Free_surface_mesh_pt->nelement();
    // Loop over the surface elements
    for(unsigned e=0;e<n_element;e++)
     {
      // Kill surface element
      delete Free_surface_mesh_pt->element_pt(e);
     }
    // Wipe the mesh
    Free_surface_mesh_pt->flush_element_and_node_storage();
   } // end of delete_free_surface_elements
References e().
delete_volume_constraint_elements()
template<class ELEMENT > void DropInChannelProblem< ELEMENT >::delete_volume_constraint_elements () inline private
Delete volume constraint elements.
   {
    if (Volume_constraint_mesh_pt==0) return;
    // Backup
    if (Vol_constraint_el_pt!=0)
     {
      Initial_value_for_drop_pressure=Vol_constraint_el_pt->p_traded();
     }
    // How many surface elements are in the surface mesh
    unsigned n_element = Volume_constraint_mesh_pt->nelement();
    // Loop over all
    unsigned first_el_to_be_killed=0;
    for(unsigned e=first_el_to_be_killed;e<n_element;e++)
     {
      delete Volume_constraint_mesh_pt->element_pt(e);
     }
    // We've just killed the volume constraint element
    Vol_constraint_el_pt=0;
    // Wipe the mesh
    Volume_constraint_mesh_pt->flush_element_and_node_storage();
   } // end of delete_volume_constraint_elements
References e().
doc_solution()
template<class ELEMENT > void DropInChannelProblem< ELEMENT >::doc_solution (const std::string & comment = "")
Doc the solution.
 {
  oomph_info << "Docing step: " << Problem_Parameter::Doc_info.number()
             << std::endl;
  ofstream some_file;
  char filename[100];
  sprintf(filename,"%s/soln%i.dat",
          Problem_Parameter::Doc_info.directory().c_str(),
          Problem_Parameter::Doc_info.number());
  // Number of plot points
  unsigned npts;
  npts=5;
  // Compute errors and assign to each element for plotting
  double max_err;
  double min_err;
  compute_error_estimate(max_err,min_err);
  // Assemble square of L2 norm
  double square_of_l2_norm=0.0;
  unsigned nel=Fluid_mesh_pt->nelement();
  for (unsigned e=0;e<nel;e++)
   {
    square_of_l2_norm+=
     dynamic_cast<ELEMENT*>(this->Fluid_mesh_pt->element_pt(e))->
     square_of_l2_norm();
   }
  Problem_Parameter::Norm_file << sqrt(square_of_l2_norm) << std::endl;
  some_file.open(filename);
  some_file << dynamic_cast<ELEMENT*>(this->Fluid_mesh_pt->element_pt(0))
   ->variable_identifier();
  this->Fluid_mesh_pt->output(some_file,npts);
  some_file << "TEXT X = 25, Y = 78, CS=FRAME T = \"Global Step "
            << Problem_Parameter::Doc_info.number() << "  "
            << comment << "\"\n";
  some_file.close();
  // Output boundaries
  sprintf(filename,"%s/boundaries%i.dat",
          Problem_Parameter::Doc_info.directory().c_str(),
          Problem_Parameter::Doc_info.number());
  some_file.open(filename);
  this->Fluid_mesh_pt->output_boundaries(some_file);
  some_file.close();
  // Get max/min area
  double max_area;
  double min_area;
  Fluid_mesh_pt->max_and_min_element_size(max_area, min_area);
  // Write trace file
  Problem_Parameter::Trace_file
   << this->time_pt()->time() << " "
   << Fluid_mesh_pt->nelement() << " "
   << max_area << " "
   << min_area << " "
   << max_err << " "
   << min_err << " "
   << sqrt(square_of_l2_norm) << " "
   << std::endl;
  // Increment the doc_info number
  Problem_Parameter::Doc_info.number()++;
 }
References Problem_Parameter::Doc_info, e(), MergeRestartFiles::filename, Problem_Parameter::Norm_file, oomph::DocInfo::number(), oomph::oomph_info, sqrt(), square_of_l2_norm(), and Problem_Parameter::Trace_file.
remove_volume_constraint()
template<class ELEMENT > void DropInChannelProblem< ELEMENT >::remove_volume_constraint () inline
Change the boundary conditions to remove the volume constraint.
   {
    // Ignore all volume constraint stuff from here onwards
    Use_volume_constraint=false;
    //Unhijack the data in the internal element
    Hijacked_element_pt->unhijack_all_data();
    //Delete the volume constraint elements
    delete_volume_constraint_elements();
    // Internal pressure is gone -- null it out
    Drop_pressure_data_pt=0;
    // Kill the mesh too
    delete Volume_constraint_mesh_pt;
    Volume_constraint_mesh_pt=0;
    //Remove the sub meshes
    this->flush_sub_meshes();
     // Add Fluid_mesh_pt sub meshes
    this->add_sub_mesh(Fluid_mesh_pt);
     // Add Free_surface sub meshes
    this->add_sub_mesh(this->Free_surface_mesh_pt);
    //Rebuild the global mesh
    this->rebuild_global_mesh();
    //Renumber the equations
    std::cout << "Removed volume constraint to obtain "
              << this->assign_eqn_numbers() << " new equation numbers\n";
   }
Member Data Documentation
Drop_polygon_pt
template<class ELEMENT > Vector<TriangleMeshPolygon*> DropInChannelProblem< ELEMENT >::Drop_polygon_pt private
Vector storing pointer to the drop polygons.
Drop_pressure_data_pt
template<class ELEMENT > Data* DropInChannelProblem< ELEMENT >::Drop_pressure_data_pt private
Pointer to a global drop pressure datum.
Fluid_mesh_pt
template<class ELEMENT > RefineableSolidTriangleMesh<ELEMENT>* DropInChannelProblem< ELEMENT >::Fluid_mesh_pt private
Pointer to Fluid_mesh.
Free_surface_mesh_pt
template<class ELEMENT > Mesh* DropInChannelProblem< ELEMENT >::Free_surface_mesh_pt private
Pointers to mesh of free surface elements.
Hijacked_element_pt
template<class ELEMENT > ELEMENT* DropInChannelProblem< ELEMENT >::Hijacked_element_pt private
Pointer to hijacked element.
Initial_value_for_drop_pressure
template<class ELEMENT > double DropInChannelProblem< ELEMENT >::Initial_value_for_drop_pressure private
Backed up drop pressure between adaptations.
Outer_boundary_polyline_pt
template<class ELEMENT > TriangleMeshPolygon* DropInChannelProblem< ELEMENT >::Outer_boundary_polyline_pt private
Triangle mesh polygon for outer boundary.
Use_volume_constraint
template<class ELEMENT > bool DropInChannelProblem< ELEMENT >::Use_volume_constraint private
Bool to indicate if volume constraint is applied (only for steady run)
Vol_constraint_el_pt
template<class ELEMENT > VolumeConstraintElement* DropInChannelProblem< ELEMENT >::Vol_constraint_el_pt private
Pointer to element that imposes volume constraint for drop.
Volume_constraint_mesh_pt
template<class ELEMENT > Mesh* DropInChannelProblem< ELEMENT >::Volume_constraint_mesh_pt private
Pointer to mesh containing elements that impose volume constraint.
The documentation for this class was generated from the following file:
adaptive_drop_in_channel.cc