MercuryDPM: Eigen::internal::UpperBidiagonalization< MatrixType_ > Class Template Reference
Eigen::internal::UpperBidiagonalization< MatrixType_ > Class Template Reference
#include <UpperBidiagonalization.h>
Public Types
enum { RowsAtCompileTime = MatrixType::RowsAtCompileTime , ColsAtCompileTime = MatrixType::ColsAtCompileTime , ColsAtCompileTimeMinusOne = internal::decrement_size<ColsAtCompileTime>::ret }
typedef MatrixType_ MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef Eigen::Index Index
typedef Matrix< Scalar, 1, ColsAtCompileTime > RowVectorType
typedef Matrix< Scalar, RowsAtCompileTime, 1 > ColVectorType
typedef BandMatrix< RealScalar, ColsAtCompileTime, ColsAtCompileTime, 1, 0, RowMajor > BidiagonalType
typedef Matrix< Scalar, ColsAtCompileTime, 1 > DiagVectorType
typedef Matrix< Scalar, ColsAtCompileTimeMinusOne, 1 > SuperDiagVectorType
typedef HouseholderSequence< const MatrixType, const internal::remove_all_t< typename Diagonal< const MatrixType, 0 >::ConjugateReturnType > > HouseholderUSequenceType
typedef HouseholderSequence< const internal::remove_all_t< typename MatrixType::ConjugateReturnType >, Diagonal< const MatrixType, 1 >, OnTheRight > HouseholderVSequenceType
Public Member Functions
UpperBidiagonalization ()
Default Constructor.
UpperBidiagonalization (const MatrixType &matrix)
UpperBidiagonalization (Index rows, Index cols)
UpperBidiagonalization & compute (const MatrixType &matrix)
UpperBidiagonalization & computeUnblocked (const MatrixType &matrix)
const MatrixType & householder () const
const BidiagonalType & bidiagonal () const
const HouseholderUSequenceType householderU () const
const HouseholderVSequenceType householderV ()
Protected Attributes
MatrixType m_householder
BidiagonalType m_bidiagonal
bool m_isInitialized
Member Typedef Documentation
BidiagonalType
template<typename MatrixType_ > typedef BandMatrix<RealScalar, ColsAtCompileTime, ColsAtCompileTime, 1, 0, RowMajor> Eigen::internal::UpperBidiagonalization< MatrixType_ >::BidiagonalType
ColVectorType
template<typename MatrixType_ > typedef Matrix<Scalar, RowsAtCompileTime, 1> Eigen::internal::UpperBidiagonalization< MatrixType_ >::ColVectorType
DiagVectorType
template<typename MatrixType_ > typedef Matrix<Scalar, ColsAtCompileTime, 1> Eigen::internal::UpperBidiagonalization< MatrixType_ >::DiagVectorType
HouseholderUSequenceType
template<typename MatrixType_ > typedef HouseholderSequence< const MatrixType, const internal::remove_all_t<typename Diagonal<const MatrixType, 0>::ConjugateReturnType> > Eigen::internal::UpperBidiagonalization< MatrixType_ >::HouseholderUSequenceType
HouseholderVSequenceType
template<typename MatrixType_ > typedef HouseholderSequence<const internal::remove_all_t<typename MatrixType::ConjugateReturnType>, Diagonal<const MatrixType, 1>, OnTheRight> Eigen::internal::UpperBidiagonalization< MatrixType_ >::HouseholderVSequenceType
Index
template<typename MatrixType_ > typedef Eigen::Index Eigen::internal::UpperBidiagonalization< MatrixType_ >::Index
Deprecated:
since Eigen 3.3
MatrixType
template<typename MatrixType_ > typedef MatrixType_ Eigen::internal::UpperBidiagonalization< MatrixType_ >::MatrixType
RealScalar
template<typename MatrixType_ > typedef MatrixType::RealScalar Eigen::internal::UpperBidiagonalization< MatrixType_ >::RealScalar
RowVectorType
template<typename MatrixType_ > typedef Matrix<Scalar, 1, ColsAtCompileTime> Eigen::internal::UpperBidiagonalization< MatrixType_ >::RowVectorType
Scalar
template<typename MatrixType_ > typedef MatrixType::Scalar Eigen::internal::UpperBidiagonalization< MatrixType_ >::Scalar
SuperDiagVectorType
template<typename MatrixType_ > typedef Matrix<Scalar, ColsAtCompileTimeMinusOne, 1> Eigen::internal::UpperBidiagonalization< MatrixType_ >::SuperDiagVectorType
Member Enumeration Documentation
anonymous enum
template<typename MatrixType_ > anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
ColsAtCompileTimeMinusOne
        {
     RowsAtCompileTime = MatrixType::RowsAtCompileTime,
     ColsAtCompileTime = MatrixType::ColsAtCompileTime,
     ColsAtCompileTimeMinusOne = internal::decrement_size<ColsAtCompileTime>::ret
   };
Constructor & Destructor Documentation
UpperBidiagonalization() [1/3]
template<typename MatrixType_ > Eigen::internal::UpperBidiagonalization< MatrixType_ >::UpperBidiagonalization () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via Bidiagonalization::compute(const MatrixType&).
 : m_householder(), m_bidiagonal(0, 0), m_isInitialized(false) {}
UpperBidiagonalization() [2/3]
template<typename MatrixType_ > Eigen::internal::UpperBidiagonalization< MatrixType_ >::UpperBidiagonalization (const MatrixType & matrix) inline explicit
       : m_householder(matrix.rows(), matrix.cols()),
         m_bidiagonal(matrix.cols(), matrix.cols()),
         m_isInitialized(false) {
     compute(matrix);
   }
References Eigen::internal::UpperBidiagonalization< MatrixType_ >::compute(), and matrix().
UpperBidiagonalization() [3/3]
template<typename MatrixType_ > Eigen::internal::UpperBidiagonalization< MatrixType_ >::UpperBidiagonalization (Index rows, Index cols) inline
       : m_householder(rows, cols), m_bidiagonal(cols, cols), m_isInitialized(false) {}
Member Function Documentation
bidiagonal()
template<typename MatrixType_ > const BidiagonalType& Eigen::internal::UpperBidiagonalization< MatrixType_ >::bidiagonal () const inline
 { return m_bidiagonal; }
References Eigen::internal::UpperBidiagonalization< MatrixType_ >::m_bidiagonal.
compute()
template<typename MatrixType_ > UpperBidiagonalization< MatrixType_ > & Eigen::internal::UpperBidiagonalization< MatrixType_ >::compute (const MatrixType & matrix)
{
   Index rows = matrix.rows();
   Index cols = matrix.cols();
   EIGEN_ONLY_USED_FOR_DEBUG(rows);
   EIGEN_ONLY_USED_FOR_DEBUG(cols);
   eigen_assert(rows >= cols && "UpperBidiagonalization is only for Arices satisfying rows>=cols.");
   m_householder = matrix;
   upperbidiagonalization_inplace_blocked(m_householder, m_bidiagonal);
   m_isInitialized = true;
   return *this;
 }
References cols, eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, matrix(), rows, and Eigen::internal::upperbidiagonalization_inplace_blocked().
Referenced by Eigen::internal::UpperBidiagonalization< MatrixType_ >::UpperBidiagonalization().
computeUnblocked()
template<typename MatrixType_ > UpperBidiagonalization< MatrixType_ > & Eigen::internal::UpperBidiagonalization< MatrixType_ >::computeUnblocked (const MatrixType & matrix)
{
   Index rows = matrix.rows();
   Index cols = matrix.cols();
   EIGEN_ONLY_USED_FOR_DEBUG(cols);
   eigen_assert(rows >= cols && "UpperBidiagonalization is only for Arices satisfying rows>=cols.");
   m_householder = matrix;
   ColVectorType temp(rows);
   upperbidiagonalization_inplace_unblocked(m_householder, &(m_bidiagonal.template diagonal<0>().coeffRef(0)),
                                            &(m_bidiagonal.template diagonal<1>().coeffRef(0)), temp.data());
   m_isInitialized = true;
   return *this;
 }
References cols, Eigen::PlainObjectBase< Derived >::data(), eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, matrix(), rows, and Eigen::internal::upperbidiagonalization_inplace_unblocked().
householder()
template<typename MatrixType_ > const MatrixType& Eigen::internal::UpperBidiagonalization< MatrixType_ >::householder () const inline
 { return m_householder; }
References Eigen::internal::UpperBidiagonalization< MatrixType_ >::m_householder.
householderU()
template<typename MatrixType_ > const HouseholderUSequenceType Eigen::internal::UpperBidiagonalization< MatrixType_ >::householderU () const inline
{
     eigen_assert(m_isInitialized && "UpperBidiagonalization is not initialized.");
     return HouseholderUSequenceType(m_householder, m_householder.diagonal().conjugate());
   }
References eigen_assert, Eigen::internal::UpperBidiagonalization< MatrixType_ >::m_householder, and Eigen::internal::UpperBidiagonalization< MatrixType_ >::m_isInitialized.
householderV()
template<typename MatrixType_ > const HouseholderVSequenceType Eigen::internal::UpperBidiagonalization< MatrixType_ >::householderV () inline
   {
     eigen_assert(m_isInitialized && "UpperBidiagonalization is not initialized.");
     return HouseholderVSequenceType(m_householder.conjugate(), m_householder.const_derived().template diagonal<1>())
         .setLength(m_householder.cols() - 1)
         .setShift(1);
   }
References eigen_assert, Eigen::internal::UpperBidiagonalization< MatrixType_ >::m_householder, and Eigen::internal::UpperBidiagonalization< MatrixType_ >::m_isInitialized.
Member Data Documentation
m_bidiagonal
template<typename MatrixType_ > BidiagonalType Eigen::internal::UpperBidiagonalization< MatrixType_ >::m_bidiagonal protected
Referenced by Eigen::internal::UpperBidiagonalization< MatrixType_ >::bidiagonal().
m_householder
template<typename MatrixType_ > MatrixType Eigen::internal::UpperBidiagonalization< MatrixType_ >::m_householder protected
Referenced by Eigen::internal::UpperBidiagonalization< MatrixType_ >::householder(), Eigen::internal::UpperBidiagonalization< MatrixType_ >::householderU(), and Eigen::internal::UpperBidiagonalization< MatrixType_ >::householderV().
m_isInitialized
template<typename MatrixType_ > bool Eigen::internal::UpperBidiagonalization< MatrixType_ >::m_isInitialized protected
Referenced by Eigen::internal::UpperBidiagonalization< MatrixType_ >::householderU(), and Eigen::internal::UpperBidiagonalization< MatrixType_ >::householderV().
The documentation for this class was generated from the following file:
UpperBidiagonalization.h