MercuryDPM: CollapsibleChannelProblem< ELEMENT > Class Template Reference
CollapsibleChannelProblem< ELEMENT > Class Template Reference
Problem class.
Public Member Functions
CollapsibleChannelProblem (const unsigned &nup, const unsigned &ncollapsible, const unsigned &ndown, const unsigned &ny, const double &lup, const double &lcollapsible, const double &ldown, const double &ly, const double &amplitude, const double &period)
Constructor for the collapsible channel problem.
~CollapsibleChannelProblem ()
Empty destructor.
RefineableCollapsibleChannelMesh< ELEMENT > * bulk_mesh_pt ()
Access function for the specific mesh.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_implicit_timestep ()
Update the velocity boundary condition on the moving wall.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of prescribed traction elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of prescribed traction elements.
void set_initial_condition ()
Apply initial conditions.
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution.
CollapsibleChannelProblem (const unsigned &nup, const unsigned &ncollapsible, const unsigned &ndown, const unsigned &ny, const double &lup, const double &lcollapsible, const double &ldown, const double &ly, const double &amplitude, const double &period)
~CollapsibleChannelProblem ()
Empty destructor.
MyAlgebraicCollapsibleChannelMesh< ELEMENT > * bulk_mesh_pt ()
Access function for the specific mesh.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_implicit_timestep ()
Update the velocity boundary condition on the moving wall.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of prescribed traction elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of prescribed traction elements.
void set_initial_condition ()
Apply initial conditions.
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution.
CollapsibleChannelProblem (const unsigned &nup, const unsigned &ncollapsible, const unsigned &ndown, const unsigned &ny, const double &lup, const double &lcollapsible, const double &ldown, const double &ly, const double &limpedance, const double &amplitude, const double &period, const unsigned &outflow)
Constructor for the collapsible channel problem.
~CollapsibleChannelProblem ()
Empty destructor.
RefineableCollapsibleChannelMesh< ELEMENT > * bulk_mesh_pt ()
Access function for the fluid bulk mesh.
Mesh *& outflow_impedance_master_mesh_pt ()
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution.
void unsteady_run (string directory_for_data, double nstep, const bool &validation_run=false)
Run unsteady problem.
void refine_elements_based_on_x_coord (const double &x_min, const double &x_max)
void switch_off_wall_oscillations ()
Function to switch off wall oscillations.
Mesh * create_mesh_for_navier_stokes_preconditioner ()
Create a mesh for the NavierStokes Preconditioner.
CollapsibleChannelProblem (const unsigned &nup, const unsigned &ncollapsible, const unsigned &ndown, const unsigned &ny, const double &lup, const double &lcollapsible, const double &ldown, const double &ly, const double &amplitude, const double &period)
~CollapsibleChannelProblem ()
Empty destructor.
RefineableCollapsibleChannelMesh< ELEMENT > * bulk_mesh_pt ()
Access function for the specific mesh.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_newton_convergence_check ()
Update no slip before Newton convergence check.
void actions_before_implicit_timestep ()
Update the velocity boundary condition on the moving wall.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of prescribed traction elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of prescribed traction elements.
void set_initial_condition ()
Apply initial conditions.
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution.
CollapsibleChannelProblem (const unsigned &nup, const unsigned &ncollapsible, const unsigned &ndown, const unsigned &ny, const double &lup, const double &lcollapsible, const double &ldown, const double &ly, const double &limpedance, const double &amplitude, const double &period, const unsigned &outflow)
~CollapsibleChannelProblem ()
Empty destructor.
RefineableCollapsibleChannelMesh< ELEMENT > * bulk_mesh_pt ()
Access function for the fluid bulk mesh.
Mesh *& outflow_impedance_master_mesh_pt ()
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution.
void unsteady_run (string directory_for_data, double nstep, const bool &validation_run=false)
Run unsteady problem.
void refine_elements_based_on_x_coord (const double &x_min, const double &x_max)
void switch_off_wall_oscillations ()
Function to switch off wall oscillations.
Mesh * create_mesh_for_navier_stokes_preconditioner ()
Create a mesh for the NavierStokesSchurComplementPreconditioner.
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Protected Member Functions
void set_poiseuille_outflow ()
Apply Poiseuille flow on outlet.
void set_parallel_outflow ()
Apply parallel flow on outlet.
void actions_before_newton_solve ()
Update the problem specs before solve.
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_implicit_timestep ()
Update the velocity boundary condition on the moving wall.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of prescribed traction elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of prescribed traction elements.
void set_initial_condition ()
Apply initial conditions.
void set_poiseuille_outflow ()
Apply Poiseuille flow on outlet.
void set_parallel_outflow ()
Apply parallel flow on outlet.
void actions_before_newton_solve ()
Update the problem specs before solve.
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_implicit_timestep ()
Update the velocity boundary condition on the moving wall.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of prescribed traction elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of prescribed traction elements.
void set_initial_condition ()
Apply initial conditions.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Private Member Functions
void create_traction_elements (const unsigned &b, Mesh *const &bulk_mesh_pt, Mesh *const &surface_mesh_pt)
Create the traction elements.
void delete_traction_elements (Mesh *const &surface_mesh_pt)
Delete prescribed traction elements from the surface mesh.
void create_traction_elements (const unsigned &b, Mesh *const &bulk_mesh_pt, Mesh *const &surface_mesh_pt)
void delete_traction_elements (Mesh *const &surface_mesh_pt)
Delete prescribed traction elements from the surface mesh.
void delete_outflow_flux_control_elements ()
Delete flux control elements from outflow boundary.
void setup_outflow_flux_control_elements ()
Attach flux control elements to outflow boundary.
void setup_inflow_traction_elements ()
Create the prescribed traction elements on the inflow.
void delete_inflow_traction_elements ()
Delete prescribed traction elements from the surface mesh.
void delete_outflow_impedance_elements ()
Delete impedance elements from outflow boundary.
void setup_outflow_impedance_elements ()
Attach impedance elements to outflow boundary.
void create_traction_elements (const unsigned &b, Mesh *const &bulk_mesh_pt, Mesh *const &surface_mesh_pt)
void delete_traction_elements (Mesh *const &surface_mesh_pt)
Delete prescribed traction elements from the surface mesh.
void create_lagrange_multiplier_elements ()
Create elements that impose the prescribed boundary displacement.
void delete_lagrange_multiplier_elements ()
void delete_outflow_flux_control_elements ()
Delete flux control elements from outflow boundary.
void setup_outflow_flux_control_elements ()
Attach flux control elements to outflow boundary.
void setup_inflow_traction_elements ()
Create the prescribed traction elements on the inflow.
void delete_inflow_traction_elements ()
Delete prescribed traction elements from the surface mesh.
void delete_outflow_impedance_elements ()
void setup_outflow_impedance_elements ()
Private Attributes
unsigned Nup
Number of elements in the x direction in the upstream part of the channel.
unsigned Ncollapsible
unsigned Ndown
Number of elements in the x direction in the downstream part of the channel.
unsigned Ny
Number of elements across the channel.
double Lup
x-length in the upstream part of the channel
double Lcollapsible
x-length in the "collapsible" part of the channel
double Ldown
x-length in the downstream part of the channel
double Ly
Transverse length.
OscillatingWall * Wall_pt
Pointer to the geometric object that parametrises the "collapsible" wall.
RefineableCollapsibleChannelMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the "bulk" mesh.
Mesh * Surface_mesh_pt
Node * Left_node_pt
Pointer to the left control node.
Node * Right_node_pt
Pointer to right control node.
MyAlgebraicCollapsibleChannelMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the "bulk" mesh.
Mesh * Inflow_traction_mesh_pt
Mesh * Outflow_flux_control_master_mesh_pt
Pointer to mesh containing the net flux control element (only!)
Mesh * Outflow_flux_control_sub_mesh_pt
Pointer to mesh of flux control elements at outflow.
WomersleyOutflowImpedanceTube< QWomersleyElement< 1, 3 >, 1 > * Womersley_impedance_tube_pt
Pointer to impendance tube.
Mesh * Outflow_impedance_mesh_pt
Pointer to the impedance mesh.
Mesh * Outflow_impedance_master_mesh_pt
Pointer to the master impedance mesh when using flux control elements.
double L_impedance
Length of optional impedance tube.
double Prescribed_volume_flux
Prescribed volume flux: set to -1 for value consistent with Re.
double Period
Period of oscillation.
double Amplitude
Amplitude of osciallation.
unsigned Outflow_type
unsigned Bulk_mesh_id
Id of the fluid bulk mesh.
ElasticRefineableCollapsibleChannelMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the "bulk" mesh.
SolidMesh * Lagrange_multiplier_mesh_pt
Pointers to meshes of Lagrange multiplier elements.
ConstitutiveLaw * Constitutive_law_pt
Constitutive law used to determine the mesh deformation.
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class ELEMENT>
class CollapsibleChannelProblem< ELEMENT >
Problem class.
Constructor & Destructor Documentation
CollapsibleChannelProblem() [1/5]
template<class ELEMENT > CollapsibleChannelProblem< ELEMENT >::CollapsibleChannelProblem (const unsigned & nup, const unsigned & ncollapsible, const unsigned & ndown, const unsigned & ny, const double & lup, const double & lcollapsible, const double & ldown, const double & ly, const double & amplitude, const double & period)
Constructor for the collapsible channel problem.
Constructor : the arguments are the number of elements, the length of the domain and the amplitude and period of the oscillations
 {
  // Number of elements
  Nup=nup;
  Ncollapsible=ncollapsible;
  Ndown=ndown;
  Ny=ny;
  // Lengths of domain
  Lup=lup;
  Lcollapsible=lcollapsible;
  Ldown=ldown;
  Ly=ly;
  // Overwrite maximum allowed residual to accomodate possibly
  // poor initial guess for solution
  Problem::Max_residuals=10000;
  // Allocate the timestepper -- this constructs the Problem's
  // time object with a sufficient amount of storage to store the
  // previous timsteps.
  add_time_stepper_pt(new BDF<2>);
  // Parameters for wall object
  double height=ly;
  double length=lcollapsible;
  double x_left=lup;
  //Create the geometric object that represents the wall
  Wall_pt=new OscillatingWall(height, x_left, length, amplitude, period,
                              time_pt());
  //Build mesh
  Bulk_mesh_pt = new RefineableCollapsibleChannelMesh<ELEMENT>(
   nup, ncollapsible, ndown, ny,
   lup, lcollapsible, ldown, ly,
   Wall_pt,
   time_stepper_pt());
  // Enable boundary layer squash function?
 #ifdef USE_BL_SQUASH_FCT
  // Set a non-trivial boundary-layer-squash function...
  Bulk_mesh_pt->bl_squash_fct_pt() = &BL_Squash::squash_fct;
  // ... and update the nodal positions accordingly
  Bulk_mesh_pt->node_update();
 #endif
  // end of boundary layer squash function
  // Create "surface mesh" that will contain only the prescribed-traction
  // elements at the inflow. The default constructor just creates the mesh
  // without giving it any elements, nodes, etc.
  Surface_mesh_pt = new Mesh;
  // Create prescribed-traction elements from all elements that are
  // adjacent to boundary 5 (inflow boundary), and add them to the surface mesh.
  create_traction_elements(5,Bulk_mesh_pt,Surface_mesh_pt);
  // Add the two sub meshes to the problem
  add_sub_mesh(Bulk_mesh_pt);
  add_sub_mesh(Surface_mesh_pt);
  // Combine all submeshes added so far into a single Mesh
  build_global_mesh();
  //Set errror estimator  for bulk mesh
  Z2ErrorEstimator* error_estimator_pt=new Z2ErrorEstimator;
  dynamic_cast<RefineableCollapsibleChannelMesh<ELEMENT>*>
   (Bulk_mesh_pt)->spatial_error_estimator_pt()=error_estimator_pt;
  // Loop over the elements to set up element-specific
  // things that cannot be handled by constructor
  unsigned n_element=Bulk_mesh_pt->nelement();
  for(unsigned e=0;e<n_element;e++)
   {
    // Upcast from GeneralisedElement to the present element
    ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e));
    //Set the Reynolds number
    el_pt->re_pt() = &Global_Physical_Variables::Re;
    // Set the Womersley number
    el_pt->re_st_pt() = &Global_Physical_Variables::ReSt;
   } // end loop over bulk elements
   // Loop over the traction elements to pass pointer to prescribed
   // traction function
   unsigned n_el=Surface_mesh_pt->nelement();
   for(unsigned e=0;e<n_el;e++)
    {
     // Upcast from GeneralisedElement to NavierStokes traction element
     NavierStokesTractionElement<ELEMENT> *el_pt =
      dynamic_cast< NavierStokesTractionElement<ELEMENT>*>(
       Surface_mesh_pt->element_pt(e));
     // Set the pointer to the prescribed traction function
     el_pt->traction_fct_pt() = &Global_Physical_Variables::prescribed_traction;
    }  // end loop over applied traction elements
  //Pin the velocity on the boundaries
  //x and y-velocities pinned along boundary 0 (bottom boundary) :
  unsigned ibound=0;
  unsigned num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  for (unsigned inod=0;inod<num_nod;inod++)
   {
    for(unsigned i=0;i<2;i++)
     {
      bulk_mesh_pt()->boundary_node_pt(ibound, inod)->pin(i);
     }
   }
   //x and y-velocities pinned along boundary 2, 3, 4 (top boundaries) :
  for(unsigned ib=2;ib<5;ib++)
   {
    num_nod= bulk_mesh_pt()->nboundary_node(ib);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      for(unsigned i=0;i<2;i++)
       {
        bulk_mesh_pt()->boundary_node_pt(ib, inod)->pin(i);
       }
     }
   }
    //y-velocity pinned along boundary 1 (right boundary):
   ibound=1;
   num_nod= bulk_mesh_pt()->nboundary_node(ibound);
   for (unsigned inod=0;inod<num_nod;inod++)
    {
     bulk_mesh_pt()->boundary_node_pt(ibound, inod)->pin(1);
    }
   //y-velocity pinned along boundary 5 (left boundary):
   ibound=5;
   num_nod= bulk_mesh_pt()->nboundary_node(ibound);
   for (unsigned inod=0;inod<num_nod;inod++)
    {
     bulk_mesh_pt()->boundary_node_pt(ibound, inod)->pin(1);
    }// end of pin_velocity
   //Select control nodes "half way" up the inflow/outflow cross-sections
   //--------------------------------------------------------------------
   // Left boundary
   ibound=5;
   num_nod= bulk_mesh_pt()->nboundary_node(ibound);
   unsigned control_nod=num_nod/2;
   Left_node_pt= bulk_mesh_pt()->boundary_node_pt(ibound, control_nod);
   // Right boundary
   ibound=1;
   num_nod= bulk_mesh_pt()->nboundary_node(ibound);
   control_nod=num_nod/2;
   Right_node_pt= bulk_mesh_pt()->boundary_node_pt(ibound, control_nod);
   // Setup equation numbering scheme
   cout <<"Number of equations: " << assign_eqn_numbers() << std::endl;
 } //end of constructor
References e(), MeshRefinement::error_estimator_pt, Global_Physical_Variables::height(), i, Global_Parameters::Ldown, Global_Parameters::Lup, Mesh_Parameters::ly, Global_Parameters::Ly, Mesh_Parameters::ny, GlobalParameters::Ny, Global_Physical_Variables::prescribed_traction(), Global_Physical_Variables::Re, Global_Physical_Variables::ReSt, BL_Squash::squash_fct(), and oomph::NavierStokesTractionElement< ELEMENT >::traction_fct_pt.
~CollapsibleChannelProblem() [1/5]
template<class ELEMENT > CollapsibleChannelProblem< ELEMENT >::~CollapsibleChannelProblem () inline
Empty destructor.
 {}
CollapsibleChannelProblem() [2/5]
template<class ELEMENT > CollapsibleChannelProblem< ELEMENT >::CollapsibleChannelProblem (const unsigned & nup, const unsigned & ncollapsible, const unsigned & ndown, const unsigned & ny, const double & lup, const double & lcollapsible, const double & ldown, const double & ly, const double & amplitude, const double & period)
Constructor : the arguments are the number of elements, the length of the domain and the amplitude and period of the oscillations
~CollapsibleChannelProblem() [2/5]
template<class ELEMENT > CollapsibleChannelProblem< ELEMENT >::~CollapsibleChannelProblem () inline
Empty destructor.
 {}
CollapsibleChannelProblem() [3/5]
template<class ELEMENT > CollapsibleChannelProblem< ELEMENT >::CollapsibleChannelProblem (const unsigned & nup, const unsigned & ncollapsible, const unsigned & ndown, const unsigned & ny, const double & lup, const double & lcollapsible, const double & ldown, const double & ly, const double & limpedance, const double & amplitude, const double & period, const unsigned & outflow)
Constructor for the collapsible channel problem.
Constructor : the arguments are the number of elements, the length of the domain and the amplitude and period of the oscillations
Default length of optional impedance tube
 {
  // Number of elements
  Nup=nup;
  Ncollapsible=ncollapsible;
  Ndown=ndown;
  Ny=ny;
  // Lengths of domain
  Lup=lup;
  Lcollapsible=lcollapsible;
  Ldown=ldown;
  Ly=ly;
  // Other input data
  Period=period;
  Amplitude=amplitude;
  // Outflow boundary type
  // 0: prescribed flux boundary conditions
  // 1: impedance boundary conditions
  // 2: impedance boundary conditions using flux control elements
  // 3: prescribed outflow
  // Otherwise we have pressure driven flow with zero pressure at outlet
  Outflow_type = outflow;
  L_impedance=limpedance;
  // Overwrite maximum allowed residual to accomodate possibly
  // poor initial guess for solution
  Problem::Max_residuals=100000000;
  // Point optional mesh pointers and other stuff to null
  Inflow_traction_mesh_pt=0;
  Outflow_flux_control_master_mesh_pt=0;
  Outflow_flux_control_sub_mesh_pt=0;
  Outflow_impedance_mesh_pt=0;
  Outflow_impedance_master_mesh_pt=0;
  Womersley_impedance_tube_pt=0;
  // Allocate the timestepper -- this constructs the Problem's
  // time object with a sufficient amount of storage to store the
  // previous timsteps.
  add_time_stepper_pt(new BDF<2>);
  // Parameters for wall object
  double height=ly;
  double length=lcollapsible;
  double x_left=lup;
  //Create the geometric object that represents the wall
  Wall_pt=new OscillatingWall(height, x_left, length, amplitude, period,
                              time_pt());
  //Build mesh
  Bulk_mesh_pt = new RefineableCollapsibleChannelMesh<ELEMENT>(
   nup, ncollapsible, ndown, ny,
   lup, lcollapsible, ldown, ly,
   Wall_pt,
   time_stepper_pt());
  // Enable boundary layer squash function?
 #ifdef USE_BL_SQUASH_FCT
  // Set a non-trivial boundary-layer-squash function...
  Bulk_mesh_pt->bl_squash_fct_pt() = &BL_Squash::squash_fct;
  // ... and update the nodal positions accordingly
  Bulk_mesh_pt->node_update();
 #endif
  // end of boundary layer squash function
  // Add the bulk sub mesh to the problem
  Bulk_mesh_id=add_sub_mesh(Bulk_mesh_pt);
  // Create "surface mesh" that will contain only the prescribed-traction
  // elements at the inflow. The default constructor just creates the mesh
  // without giving it any elements, nodes, etc.
  Inflow_traction_mesh_pt = new Mesh;
  // Create prescribed-traction elements
  setup_inflow_traction_elements();
  // Add the new sub mesh to the problem
  add_sub_mesh(Inflow_traction_mesh_pt);
  if (Outflow_type==0)
   {
    oomph_info << "Flux control flow\n";
    // Create the flux control meshes
    // Construct Outflow_flux_control_master_mesh_pt
    Outflow_flux_control_master_mesh_pt = new Mesh;
    // Construct Outflow_flux_control_sub_mesh_pt
    Outflow_flux_control_sub_mesh_pt = new Mesh;
    // Set up elements for sub meshes
    setup_outflow_flux_control_elements();
    // Add new sub meshes
    add_sub_mesh(Outflow_flux_control_master_mesh_pt);
    add_sub_mesh(Outflow_flux_control_sub_mesh_pt);
   }
  else if (Outflow_type==1)
   {
    oomph_info << "Pressure driven flow with impedance tube of length "
               << L_impedance << "\n";
    if (L_impedance>0.0)
     {
      // Construct the mesh
      Outflow_impedance_mesh_pt = new Mesh;
      // Set up elements and impedance tube
      setup_outflow_impedance_elements();
      // Add new sub meshes
      add_sub_mesh(Outflow_impedance_mesh_pt);
     }
   }
  else if (Outflow_type==2)
   {
    oomph_info << "Pressure driven flow with impedance tube of length "
               << L_impedance << " using flux control elements\n";
    if (L_impedance>0.0)
     {
      // Construct Outflow_flux_control_sub_mesh_pt
      Outflow_flux_control_sub_mesh_pt = new Mesh;
      // Construct Mesh
      Outflow_impedance_master_mesh_pt = new Mesh;
      // Set up elements and impedance tube
      setup_outflow_impedance_elements();
      // Add new sub meshes
      add_sub_mesh(Outflow_flux_control_sub_mesh_pt);
      add_sub_mesh(Outflow_impedance_master_mesh_pt);
     }
   }
  else if (Outflow_type==3)
   {
    oomph_info << "Prescribed outflow\n";
   }
  else
   {
    oomph_info << "Pressure driven flow\n";
   }
  // Combine all submeshes added so far into a single Mesh
  build_global_mesh();
  //Set errror estimator for bulk mesh
  Z2ErrorEstimator* error_estimator_pt=new Z2ErrorEstimator;
  dynamic_cast<RefineableCollapsibleChannelMesh<ELEMENT>*>
   (Bulk_mesh_pt)->spatial_error_estimator_pt()=error_estimator_pt;
  // Loop over the elements to set up element-specific
  // things that cannot be handled by constructor
  unsigned n_element=Bulk_mesh_pt->nelement();
  for(unsigned e=0;e<n_element;e++)
   {
    // Upcast from GeneralisedElement to the present element
    ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e));
    //Set the Reynolds number
    el_pt->re_pt() = &Global_Physical_Variables::Re;
    // Set the Womersley number
    el_pt->re_st_pt() = &Global_Physical_Variables::ReSt;
   } // end loop over bulk elements
  // Pin redudant pressure dofs
  RefineableNavierStokesEquations<2>::
   pin_redundant_nodal_pressures(Bulk_mesh_pt->element_pt());
  // Loop over the traction elements to pass pointer to prescribed
  // traction function
  if (Inflow_traction_mesh_pt!=0)
   {
    unsigned n_el=Inflow_traction_mesh_pt->nelement();
    for(unsigned e=0;e<n_el;e++)
     {
      // Upcast from GeneralisedElement to NavierStokes traction element
      NavierStokesTractionElement<ELEMENT> *el_pt =
       dynamic_cast< NavierStokesTractionElement<ELEMENT>*>(
        Inflow_traction_mesh_pt->element_pt(e));
      // Set the pointer to the prescribed traction function
      el_pt->traction_fct_pt() =
       &Global_Physical_Variables::prescribed_traction;
     }  // end loop over applied traction elements
   }
  //Pin the velocity on the boundaries
  //x and y-velocities pinned along boundary 0 (bottom boundary) :
  unsigned ibound=0;
  unsigned num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  for (unsigned inod=0;inod<num_nod;inod++)
   {
    for(unsigned i=0;i<2;i++)
     {
      bulk_mesh_pt()->boundary_node_pt(ibound, inod)->pin(i);
     }
   }
  //x and y-velocities pinned along boundary 2, 3, 4 (top boundaries) :
  for(unsigned ib=2;ib<5;ib++)
   {
    num_nod= bulk_mesh_pt()->nboundary_node(ib);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      for(unsigned i=0;i<2;i++)
       {
        bulk_mesh_pt()->boundary_node_pt(ib, inod)->pin(i);
       }
     }
   }
  //y-velocity pinned along boundary 1 (right boundary) and also x-velocity for
  //prescribed outflow
  ibound=1;
  num_nod= bulk_mesh_pt()->nboundary_node(ibound);
  for (unsigned inod=0;inod<num_nod;inod++)
   {
    bulk_mesh_pt()->boundary_node_pt(ibound, inod)->pin(1);
    if (Outflow_type==3)
     {
      bulk_mesh_pt()->boundary_node_pt(ibound, inod)->pin(0);
     }
   }
   //y-velocity pinned along boundary 5 (left boundary):
   ibound=5;
   num_nod= bulk_mesh_pt()->nboundary_node(ibound);
   for (unsigned inod=0;inod<num_nod;inod++)
    {
     bulk_mesh_pt()->boundary_node_pt(ibound, inod)->pin(1);
    }// end of pin_velocity
   //Select control nodes "half way" up the inflow/outflow cross-sections
   //--------------------------------------------------------------------
   // Left boundary
   ibound=5;
   num_nod= bulk_mesh_pt()->nboundary_node(ibound);
   unsigned control_nod=num_nod/2;
   Left_node_pt= bulk_mesh_pt()->boundary_node_pt(ibound, control_nod);
   // Right boundary
   ibound=1;
   num_nod= bulk_mesh_pt()->nboundary_node(ibound);
   control_nod=num_nod/2;
   Right_node_pt= bulk_mesh_pt()->boundary_node_pt(ibound, control_nod);
   // Setup equation numbering scheme
   oomph_info <<"Number of equations: " << assign_eqn_numbers() << std::endl;
 } //end of constructor
References GlobalParameters::Amplitude, e(), MeshRefinement::error_estimator_pt, Global_Physical_Variables::height(), i, GlobalPhysicalParameters::L_impedance, Global_Parameters::Ldown, Global_Parameters::Lup, Mesh_Parameters::ly, Global_Parameters::Ly, Mesh_Parameters::ny, GlobalParameters::Ny, oomph::oomph_info, Global_Physical_Variables::Period, Global_Physical_Variables::prescribed_traction(), Global_Physical_Variables::Re, Global_Physical_Variables::ReSt, BL_Squash::squash_fct(), and oomph::NavierStokesTractionElement< ELEMENT >::traction_fct_pt.
~CollapsibleChannelProblem() [3/5]
template<class ELEMENT > CollapsibleChannelProblem< ELEMENT >::~CollapsibleChannelProblem () inline
Empty destructor.
 {}
CollapsibleChannelProblem() [4/5]
template<class ELEMENT > CollapsibleChannelProblem< ELEMENT >::CollapsibleChannelProblem (const unsigned & nup, const unsigned & ncollapsible, const unsigned & ndown, const unsigned & ny, const double & lup, const double & lcollapsible, const double & ldown, const double & ly, const double & amplitude, const double & period)
Constructor : the arguments are the number of elements, the length of the domain and the amplitude and period of the oscillations
~CollapsibleChannelProblem() [4/5]
template<class ELEMENT > CollapsibleChannelProblem< ELEMENT >::~CollapsibleChannelProblem () inline
Empty destructor.
 {}
CollapsibleChannelProblem() [5/5]
template<class ELEMENT > CollapsibleChannelProblem< ELEMENT >::CollapsibleChannelProblem (const unsigned & nup, const unsigned & ncollapsible, const unsigned & ndown, const unsigned & ny, const double & lup, const double & lcollapsible, const double & ldown, const double & ly, const double & limpedance, const double & amplitude, const double & period, const unsigned & outflow)
Constructor : the arguments are the number of elements, the length of the domain and the amplitude and period of the oscillations
~CollapsibleChannelProblem() [5/5]
template<class ELEMENT > CollapsibleChannelProblem< ELEMENT >::~CollapsibleChannelProblem () inline
Empty destructor.
 {}
Member Function Documentation
actions_after_adapt() [1/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_after_adapt virtual
Actions after adapt: Rebuild the mesh of prescribed traction elements.
Reimplemented from oomph::Problem.
 {
  // Create prescribed-flux elements from all elements that are
  // adjacent to boundary 5 and add them to surface mesh
  create_traction_elements(5,Bulk_mesh_pt,Surface_mesh_pt);
  // Rebuild the global mesh
  rebuild_global_mesh();
  // Loop over the traction elements to pass pointer to prescribed traction function
  unsigned n_element=Surface_mesh_pt->nelement();
  for(unsigned e=0;e<n_element;e++)
   {
    // Upcast from GeneralisedElement to NavierStokesTractionElement element
    NavierStokesTractionElement<ELEMENT> *el_pt =
     dynamic_cast<NavierStokesTractionElement<ELEMENT>*>(
      Surface_mesh_pt->element_pt(e));
    // Set the pointer to the prescribed traction function
    el_pt->traction_fct_pt() = &Global_Physical_Variables::prescribed_traction;
   }
 } // end of actions_after_adapt
References e(), Global_Physical_Variables::prescribed_traction(), and oomph::NavierStokesTractionElement< ELEMENT >::traction_fct_pt.
actions_after_adapt() [2/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_after_adapt () virtual
Actions after adapt: Rebuild the mesh of prescribed traction elements.
Reimplemented from oomph::Problem.
actions_after_adapt() [3/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_after_adapt () protected virtual
Actions after adapt: Rebuild the mesh of prescribed traction elements.
Reimplemented from oomph::Problem.
actions_after_adapt() [4/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_after_adapt () virtual
Actions after adapt: Rebuild the mesh of prescribed traction elements.
Reimplemented from oomph::Problem.
actions_after_adapt() [5/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_after_adapt () protected virtual
Actions after adapt: Rebuild the mesh of prescribed traction elements.
Reimplemented from oomph::Problem.
actions_after_newton_solve() [1/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [2/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [3/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_after_newton_solve () inline protected virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [4/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [5/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_after_newton_solve () inline protected virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_adapt() [1/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_before_adapt virtual
Actions before adapt: Wipe the mesh of prescribed traction elements.
Reimplemented from oomph::Problem.
 {
  // Kill the traction elements and wipe surface mesh
  delete_traction_elements(Surface_mesh_pt);
  // Rebuild the global mesh.
  rebuild_global_mesh();
 } // end of actions_before_adapt
actions_before_adapt() [2/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_before_adapt () virtual
Actions before adapt: Wipe the mesh of prescribed traction elements.
Reimplemented from oomph::Problem.
actions_before_adapt() [3/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_before_adapt () protected virtual
Actions before adapt: Wipe the mesh of prescribed traction elements.
Reimplemented from oomph::Problem.
actions_before_adapt() [4/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_before_adapt () virtual
Actions before adapt: Wipe the mesh of prescribed traction elements.
Reimplemented from oomph::Problem.
actions_before_adapt() [5/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_before_adapt () protected virtual
Actions before adapt: Wipe the mesh of prescribed traction elements.
Reimplemented from oomph::Problem.
actions_before_implicit_timestep() [1/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_before_implicit_timestep virtual
Update the velocity boundary condition on the moving wall.
Execute the actions before timestep: Update the velocity boundary condition on the moving wall
Reimplemented from oomph::Problem.
 {
  // Update the domain shape
  bulk_mesh_pt()->node_update();
  // Moving wall: No slip; this implies that the velocity needs
  // to be updated in response to wall motion
  unsigned ibound=3;
  unsigned num_nod=bulk_mesh_pt()->nboundary_node(ibound);
   for (unsigned inod=0;inod<num_nod;inod++)
   {
    // Which node are we dealing with?
    Node* node_pt=bulk_mesh_pt()->boundary_node_pt(ibound,inod);
    // Apply no slip
    FSI_functions::apply_no_slip_on_moving_wall(node_pt);
   }
 } //end of actions_before_implicit_timestep
References oomph::FSI_functions::apply_no_slip_on_moving_wall().
actions_before_implicit_timestep() [2/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_before_implicit_timestep () virtual
Update the velocity boundary condition on the moving wall.
Reimplemented from oomph::Problem.
actions_before_implicit_timestep() [3/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_before_implicit_timestep () protected virtual
Update the velocity boundary condition on the moving wall.
Reimplemented from oomph::Problem.
actions_before_implicit_timestep() [4/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_before_implicit_timestep () virtual
Update the velocity boundary condition on the moving wall.
Reimplemented from oomph::Problem.
actions_before_implicit_timestep() [5/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_before_implicit_timestep () protected virtual
Update the velocity boundary condition on the moving wall.
Reimplemented from oomph::Problem.
actions_before_newton_convergence_check()
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_before_newton_convergence_check () inline virtual
Update no slip before Newton convergence check.
Reimplemented from oomph::Problem.
   {
    // Moving wall: No slip; this implies that the velocity needs
    // to be updated in response to wall motion
    unsigned ibound=3;
    unsigned num_nod=bulk_mesh_pt()->nboundary_node(ibound);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      // Which node are we dealing with?
      Node* node_pt=bulk_mesh_pt()->boundary_node_pt(ibound,inod);
      // Apply no slip
      FSI_functions::apply_no_slip_on_moving_wall(node_pt);
     }
   }
References oomph::FSI_functions::apply_no_slip_on_moving_wall().
actions_before_newton_solve() [1/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_before_newton_solve inline virtual
Update the problem specs before solve (empty)
Update the inflow and outflow boundary conditioner before solve.
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [2/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [3/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_before_newton_solve () protected virtual
Update the problem specs before solve.
Reimplemented from oomph::Problem.
actions_before_newton_solve() [4/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [5/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::actions_before_newton_solve () protected virtual
Update the problem specs before solve.
Reimplemented from oomph::Problem.
bulk_mesh_pt() [1/5]
template<class ELEMENT > RefineableCollapsibleChannelMesh<ELEMENT>* CollapsibleChannelProblem< ELEMENT >::bulk_mesh_pt () inline
Access function for the specific mesh.
   {
    // Upcast from pointer to the Mesh base class to the specific
    // element type that we're using here.
    return dynamic_cast<RefineableCollapsibleChannelMesh<ELEMENT>*>
     (Bulk_mesh_pt);
   } // end of access to bulk mesh
bulk_mesh_pt() [2/5]
template<class ELEMENT > MyAlgebraicCollapsibleChannelMesh<ELEMENT>* CollapsibleChannelProblem< ELEMENT >::bulk_mesh_pt () inline
Access function for the specific mesh.
   {
    // Upcast from pointer to the Mesh base class to the specific
    // element type that we're using here.
    return dynamic_cast<MyAlgebraicCollapsibleChannelMesh<ELEMENT>*>
     (Bulk_mesh_pt);
   } // end of access to bulk mesh
bulk_mesh_pt() [3/5]
template<class ELEMENT > RefineableCollapsibleChannelMesh<ELEMENT>* CollapsibleChannelProblem< ELEMENT >::bulk_mesh_pt () inline
Access function for the fluid bulk mesh.
   {
    // Upcast from pointer to the Mesh base class to the specific
    // element type that we're using here.
    return dynamic_cast<RefineableCollapsibleChannelMesh<ELEMENT>*>
     (Bulk_mesh_pt);
   } // end of access to bulk mesh
bulk_mesh_pt() [4/5]
template<class ELEMENT > RefineableCollapsibleChannelMesh<ELEMENT>* CollapsibleChannelProblem< ELEMENT >::bulk_mesh_pt () inline
Access function for the specific mesh.
   {
    // Upcast from pointer to the Mesh base class to the specific
    // element type that we're using here.
    return dynamic_cast<RefineableCollapsibleChannelMesh<ELEMENT>*>
     (Bulk_mesh_pt);
   } // end of access to bulk mesh
bulk_mesh_pt() [5/5]
template<class ELEMENT > RefineableCollapsibleChannelMesh<ELEMENT>* CollapsibleChannelProblem< ELEMENT >::bulk_mesh_pt () inline
Access function for the fluid bulk mesh.
   {
    // Upcast from pointer to the Mesh base class to the specific
    // element type that we're using here.
    return dynamic_cast<RefineableCollapsibleChannelMesh<ELEMENT>*>
     (Bulk_mesh_pt);
   } // end of access to bulk mesh
create_lagrange_multiplier_elements()
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::create_lagrange_multiplier_elements private
Create elements that impose the prescribed boundary displacement.
Create elements that enforce prescribed boundary motion by Lagrange multiplilers
 {
  // Lagrange multiplier elements are located on boundary 3:
  unsigned b=3;
  // How many bulk elements are adjacent to boundary b?
  unsigned n_element = bulk_mesh_pt()->nboundary_element(b);
  // Loop over the bulk elements adjacent to boundary b?
  for(unsigned e=0;e<n_element;e++)
   {
    // Get pointer to the bulk element that is adjacent to boundary b
    ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
     bulk_mesh_pt()->boundary_element_pt(b,e));
    //Find the index of the face of element e along boundary b
    int face_index = bulk_mesh_pt()->face_index_at_boundary(b,e);
    // Create new element and add to mesh
    Lagrange_multiplier_mesh_pt->add_element_pt(
     new ImposeDisplacementByLagrangeMultiplierElement<ELEMENT>(
      bulk_elem_pt,face_index));
   }
  // Loop over the elements in the Lagrange multiplier element mesh
  // for elements on the top boundary (boundary 3)
  n_element=Lagrange_multiplier_mesh_pt->nelement();
  for(unsigned i=0;i<n_element;i++)
   {
    //Cast to a Lagrange multiplier element
    ImposeDisplacementByLagrangeMultiplierElement<ELEMENT> *el_pt =
     dynamic_cast<ImposeDisplacementByLagrangeMultiplierElement<ELEMENT>*>
     (Lagrange_multiplier_mesh_pt->element_pt(i));
    // Set the GeomObject that defines the boundary shape and
    // specify which bulk boundary it's attached to
    el_pt->set_boundary_shape_geom_object_pt(Wall_pt,b);
    // Loop over the nodes
    unsigned nnod=el_pt->nnode();
    for (unsigned j=0;j<nnod;j++)
     {
      Node* nod_pt = el_pt->node_pt(j);
      // Is the node also on boundary 2 or 4?
      if ((nod_pt->is_on_boundary(2))||(nod_pt->is_on_boundary(4)))
       {
        // How many nodal values were used by the "bulk" element
        // that originally created this node?
        unsigned n_bulk_value=el_pt->nbulk_value(j);
        // The remaining ones are Lagrange multipliers and we pin them.
        unsigned nval=nod_pt->nvalue();
        for (unsigned j=n_bulk_value;j<nval;j++)
         {
          nod_pt->pin(j);
         }
       }
     }
   }
 } // end of create_lagrange_multiplier_elements
References b, oomph::Mesh::boundary_element_pt(), e(), oomph::Mesh::face_index_at_boundary(), i, oomph::Node::is_on_boundary(), j, oomph::Mesh::nboundary_element(), oomph::FaceElement::nbulk_value(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Data::nvalue(), oomph::Data::pin(), and oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt().
create_mesh_for_navier_stokes_preconditioner() [1/2]
template<class ELEMENT > Mesh * CollapsibleChannelProblem< ELEMENT >::create_mesh_for_navier_stokes_preconditioner
Create a mesh for the NavierStokes Preconditioner.
Create a mesh for the NavierStokesSchurComplementPreconditioner.
 {
  //Vector to hold the meshes
  Vector<Mesh*> meshes;
  //Add the bulk mesh
  meshes.push_back(Bulk_mesh_pt);
  // Add the flux control master mesh if it exists
  if (Outflow_flux_control_master_mesh_pt!=0)
   {
    meshes.push_back(Outflow_flux_control_master_mesh_pt);
   }
  // Build "combined" mesh from vector of submeshes
  Mesh* mesh_pt = new Mesh(meshes);
  return mesh_pt;
 }
create_mesh_for_navier_stokes_preconditioner() [2/2]
template<class ELEMENT > Mesh* CollapsibleChannelProblem< ELEMENT >::create_mesh_for_navier_stokes_preconditioner ()
Create a mesh for the NavierStokesSchurComplementPreconditioner.
create_traction_elements() [1/3]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::create_traction_elements (const unsigned & b, Mesh *const & bulk_mesh_pt, Mesh *const & surface_mesh_pt) private
Create the traction elements.
Create the prescribed traction elements on boundary b of the bulk mesh and stick them into the surface mesh.
 {
  // How many bulk elements are adjacent to boundary b?
  unsigned n_element = bulk_mesh_pt->nboundary_element(b);
  // Loop over the bulk elements adjacent to boundary b
  for(unsigned e=0;e<n_element;e++)
   {
    // Get pointer to the bulk element that is adjacent to boundary b
    ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>
     (bulk_mesh_pt->boundary_element_pt(b,e));
    //What is the index of the face of element e that lies along boundary b
    int face_index = bulk_mesh_pt->face_index_at_boundary(b,e);
    // Build the corresponding prescribed-traction element
    NavierStokesTractionElement<ELEMENT>* traction_element_pt =
     new  NavierStokesTractionElement<ELEMENT>(bulk_elem_pt,face_index);
    //Add the prescribed-flux element to the surface mesh
    surface_mesh_pt->add_element_pt(traction_element_pt);
   } //end of loop over bulk elements adjacent to boundary b
 } // end of create_traction_elements
References oomph::Mesh::add_element_pt(), b, oomph::Mesh::boundary_element_pt(), e(), oomph::Mesh::face_index_at_boundary(), and oomph::Mesh::nboundary_element().
create_traction_elements() [2/3]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::create_traction_elements (const unsigned & b, Mesh *const & bulk_mesh_pt, Mesh *const & surface_mesh_pt) private
Create the prescribed traction elements on boundary b of the bulk mesh and stick them into the surface mesh.
create_traction_elements() [3/3]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::create_traction_elements (const unsigned & b, Mesh *const & bulk_mesh_pt, Mesh *const & surface_mesh_pt) private
Create the prescribed traction elements on boundary b of the bulk mesh and stick them into the surface mesh.
delete_inflow_traction_elements() [1/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::delete_inflow_traction_elements private
Delete prescribed traction elements from the surface mesh.
Delete traction elements and wipe the surface mesh.
 {
  // How many surface elements are in the surface mesh
  unsigned n_element = Inflow_traction_mesh_pt->nelement();
  // Loop over the surface elements
  for(unsigned e=0;e<n_element;e++)
   {
    // Kill element
    delete Inflow_traction_mesh_pt->element_pt(e);
   }
  // Wipe the mesh
  Inflow_traction_mesh_pt->flush_element_and_node_storage();
 } // end of delete_traction_elements
References e().
delete_inflow_traction_elements() [2/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::delete_inflow_traction_elements () private
Delete prescribed traction elements from the surface mesh.
delete_lagrange_multiplier_elements()
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::delete_lagrange_multiplier_elements private
Delete elements that enforce prescribed boundary motion by Lagrange multiplilers
Delete elements that impose the prescribed boundary displacement and wipe the associated mesh
 {
  // How many surface elements are in the surface mesh
  unsigned n_element = Lagrange_multiplier_mesh_pt->nelement();
  // Loop over the surface elements
  for(unsigned e=0;e<n_element;e++)
   {
    // Kill surface element
    delete Lagrange_multiplier_mesh_pt->element_pt(e);
   }
  // Wipe the mesh
  Lagrange_multiplier_mesh_pt->flush_element_and_node_storage();
 } // end of delete_lagrange_multiplier_elements
References e().
delete_outflow_flux_control_elements() [1/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::delete_outflow_flux_control_elements private
Delete flux control elements from outflow boundary.
 {
  // Delete the master flux control element
  delete Outflow_flux_control_master_mesh_pt->element_pt(0);
  // Wipe the mesh
  Outflow_flux_control_master_mesh_pt->flush_element_and_node_storage();
  // Loop over all flux control elements at outflow
  unsigned n_bound_el=Outflow_flux_control_sub_mesh_pt->nelement();
  for (unsigned e=0;e<n_bound_el;e++)
   {
    //Delete the element
    delete Outflow_flux_control_sub_mesh_pt->element_pt(e);
   }
  // Wipe the mesh
  Outflow_flux_control_sub_mesh_pt->flush_element_and_node_storage();
 }
References e().
delete_outflow_flux_control_elements() [2/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::delete_outflow_flux_control_elements () private
Delete flux control elements from outflow boundary.
delete_outflow_impedance_elements() [1/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::delete_outflow_impedance_elements private
Delete impedance elements from outflow boundary.
 {
  if (Outflow_type==1)
   {
    // Loop over all elements at outflow
    unsigned n_bound_el=Outflow_impedance_mesh_pt->nelement();
    for (unsigned e=0;e<n_bound_el;e++)
     {
      //Delete the element
      delete Outflow_impedance_mesh_pt->element_pt(e);
     }
    // Wipe the mesh
    Outflow_impedance_mesh_pt->flush_element_and_node_storage();
    // Delete the impedance tube
    delete Womersley_impedance_tube_pt;
    Womersley_impedance_tube_pt=0;
   }
  else
   {
    // Delete the elements in the master mesh
    delete Outflow_impedance_master_mesh_pt->element_pt(0);
    delete Outflow_impedance_master_mesh_pt->element_pt(1);
    // Wipe the mesh
    Outflow_impedance_master_mesh_pt->flush_element_and_node_storage();
    // Loop over all flux control elements at outflow
    unsigned n_bound_el=Outflow_flux_control_sub_mesh_pt->nelement();
    for (unsigned e=0;e<n_bound_el;e++)
     {
      //Delete the element
      delete Outflow_flux_control_sub_mesh_pt->element_pt(e);
     }
    // Wipe the mesh
    Outflow_flux_control_sub_mesh_pt->flush_element_and_node_storage();
    // Delete the impedance tube
    delete Womersley_impedance_tube_pt;
    Womersley_impedance_tube_pt=0;
   }
 }
References e().
delete_outflow_impedance_elements() [2/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::delete_outflow_impedance_elements () private
delete_traction_elements() [1/3]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::delete_traction_elements (Mesh *const & surface_mesh_pt) private
Delete prescribed traction elements from the surface mesh.
Delete traction elements and wipe the surface mesh.
 {
  // How many surface elements are in the surface mesh
  unsigned n_element = surface_mesh_pt->nelement();
  // Loop over the surface elements
  for(unsigned e=0;e<n_element;e++)
   {
    // Kill surface element
    delete surface_mesh_pt->element_pt(e);
   }
  // Wipe the mesh
  surface_mesh_pt->flush_element_and_node_storage();
 } // end of delete_traction_elements
References e(), oomph::Mesh::element_pt(), oomph::Mesh::flush_element_and_node_storage(), and oomph::Mesh::nelement().
delete_traction_elements() [2/3]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::delete_traction_elements (Mesh *const & surface_mesh_pt) private
Delete prescribed traction elements from the surface mesh.
delete_traction_elements() [3/3]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::delete_traction_elements (Mesh *const & surface_mesh_pt) private
Delete prescribed traction elements from the surface mesh.
doc_solution() [1/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution.
 {
  ofstream some_file;
  char filename[100];
  // Number of plot points
  unsigned npts;
  npts=5;
  // Output solution
  sprintf(filename,"%s/soln%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  bulk_mesh_pt()->output(some_file,npts);
  some_file.close();
  // Get the position of the midpoint on the geometric object
  Vector<double> zeta(1);
  zeta[0]=0.5*Lcollapsible;
  Vector<double> wall_point(2);
  Wall_pt->position(zeta,wall_point);
  // Write trace file
  trace_file << time_pt()->time() << " "
             << wall_point[1]  << " "
             << Left_node_pt->value(0) << " "
             << Right_node_pt->value(0) << " "
             << std::endl;
  // Output wall shape
  sprintf(filename,"%s/wall%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  unsigned nplot=100;
  for (unsigned i=0;i<nplot;i++)
   {
    zeta[0]=double(i)/double(nplot-1)*Lcollapsible;
    Wall_pt->position(zeta,wall_point);
    some_file << wall_point[0]  << " "
              << wall_point[1]  << std::endl;
   }
  some_file.close();
 } // end_of_doc_solution
References oomph::DocInfo::directory(), MergeRestartFiles::filename, i, oomph::DocInfo::number(), and Eigen::zeta().
doc_solution() [2/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution.
doc_solution() [3/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution.
doc_solution() [4/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution.
doc_solution() [5/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution.
outflow_impedance_master_mesh_pt() [1/2]
template<class ELEMENT > Mesh* & CollapsibleChannelProblem< ELEMENT >::outflow_impedance_master_mesh_pt () inline
Access function to the pointer to the master impedance mesh which is used when using impedance boundary conditions with flux control elements
   {
    return Outflow_impedance_master_mesh_pt;
   }
outflow_impedance_master_mesh_pt() [2/2]
template<class ELEMENT > Mesh* & CollapsibleChannelProblem< ELEMENT >::outflow_impedance_master_mesh_pt () inline
Access function to the pointer to the master impedance mesh which is used when using impedance boundary conditions with flux control elements
   {
    return Outflow_impedance_master_mesh_pt;
   }
refine_elements_based_on_x_coord() [1/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::refine_elements_based_on_x_coord (const double & x_min, const double & x_max)
Refine any element whoes centre node lies between x coorodinates x_min and x_max
   {
    // Vector to store pointers to elements to be refined
    Vector<RefineableElement*> element_pt;
    // Get elements we want to refine
    unsigned n_el = Bulk_mesh_pt->nelement();
    for (unsigned e=0; e<n_el; e++)
     {
      // Get element
      RefineableElement* el_pt =
       dynamic_cast<RefineableElement*>(Bulk_mesh_pt->element_pt(e));
      // Get x-coord of node at centre
      double x_centre=el_pt->node_pt(4)->x(0);
      // Add to Vector if to be refined
      if ((x_centre>=x_min) && (x_centre<=x_max))
       {
        element_pt.push_back(el_pt);
       }
     }
    // Refine the elements
    oomph_info << "Number of elements to refine between x=" << x_min
               << " & " << x_max << " is "
               << element_pt.size() << "\n";
    refine_selected_elements(Bulk_mesh_id, element_pt);
   }
References e(), oomph::FiniteElement::node_pt(), oomph::oomph_info, and oomph::Node::x().
refine_elements_based_on_x_coord() [2/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::refine_elements_based_on_x_coord (const double & x_min, const double & x_max)
Refine any element whoes centre node lies between x coorodinates x_min and x_max
set_initial_condition() [1/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::set_initial_condition virtual
Apply initial conditions.
Apply initial conditions: Impulsive start from steady Poiseuille.
Apply initial conditions: Impulsive start from steady Poiseuille flow.
Reimplemented from oomph::Problem.
 {
  // Check that timestepper is from the BDF family
  if (time_stepper_pt()->type()!="BDF")
   {
    std::ostringstream error_stream;
    error_stream
     << "Timestepper has to be from the BDF family!\n"
     << "You have specified a timestepper from the "
     << time_stepper_pt()->type() << " family" << std::endl;
    throw OomphLibError(error_stream.str(),
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
   }
  // Update the mesh
  bulk_mesh_pt()->node_update();
  // Loop over the nodes to set initial guess everywhere
  unsigned num_nod = bulk_mesh_pt()->nnode();
  for (unsigned n=0;n<num_nod;n++)
   {
    // Get nodal coordinates
    Vector<double> x(2);
    x[0]=bulk_mesh_pt()->node_pt(n)->x(0);
    x[1]=bulk_mesh_pt()->node_pt(n)->x(1);
    // Assign initial condition: Steady Poiseuille flow
    bulk_mesh_pt()->node_pt(n)->set_value(0,6.0*(x[1]/Ly)*(1.0-(x[1]/Ly)));
    bulk_mesh_pt()->node_pt(n)->set_value(1,0.0);
   }
  // Assign initial values for an impulsive start
  bulk_mesh_pt()->assign_initial_values_impulsive();
 } // end of set_initial_condition
References Global_Parameters::Ly, n, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, compute_granudrum_aor::type, and plotDoE::x.
set_initial_condition() [2/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::set_initial_condition () virtual
Apply initial conditions.
Reimplemented from oomph::Problem.
set_initial_condition() [3/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::set_initial_condition () protected virtual
Apply initial conditions.
Reimplemented from oomph::Problem.
set_initial_condition() [4/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::set_initial_condition () virtual
Apply initial conditions.
Reimplemented from oomph::Problem.
set_initial_condition() [5/5]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::set_initial_condition () protected virtual
Apply initial conditions.
Reimplemented from oomph::Problem.
set_parallel_outflow() [1/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::set_parallel_outflow protected
Apply parallel flow on outlet.
 {
  // Outflow is boundary 1
  unsigned b = 1;
  // Loop over all elements on this boundary
  unsigned n_bound_el=Bulk_mesh_pt->nboundary_element(b);
  for (unsigned e=0;e<n_bound_el;e++)
   {
    // Assign parallel flow
    bulk_mesh_pt()->node_pt(e)->set_value(1,0.0);
   }
 }
References b, and e().
set_parallel_outflow() [2/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::set_parallel_outflow () protected
Apply parallel flow on outlet.
set_poiseuille_outflow() [1/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::set_poiseuille_outflow protected
Apply Poiseuille flow on outlet.
 {
  // Outflow is boundary 1
  unsigned b = 1;
  // Loop over all elements on this boundary
  unsigned n_bound_el=Bulk_mesh_pt->nboundary_element(b);
  for (unsigned e=0;e<n_bound_el;e++)
   {
    // Get nodal coordinates
    Vector<double> x(2);
    x[0]=bulk_mesh_pt()->node_pt(e)->x(0);
    x[1]=bulk_mesh_pt()->node_pt(e)->x(1);
    // Assign Poiseuille flow
    bulk_mesh_pt()->node_pt(e)->set_value(0,6.0*(x[1]/Ly)*(1.0-(x[1]/Ly)));
    bulk_mesh_pt()->node_pt(e)->set_value(1,0.0);
   }
 }
References b, e(), Global_Parameters::Ly, and plotDoE::x.
set_poiseuille_outflow() [2/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::set_poiseuille_outflow () protected
Apply Poiseuille flow on outlet.
setup_inflow_traction_elements() [1/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::setup_inflow_traction_elements private
Create the prescribed traction elements on the inflow.
Create the traction elements.
 {
  // inflow is boundary 5
  unsigned b=5;
  // How many bulk elements are adjacent to boundary b?
  unsigned n_element = Bulk_mesh_pt->nboundary_element(b);
  // Loop over the bulk elements adjacent to boundary b
  for(unsigned e=0;e<n_element;e++)
   {
    // Get pointer to the bulk element that is adjacent to boundary b
    ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>
     (Bulk_mesh_pt->boundary_element_pt(b,e));
    //What is the index of the face of element e that lies along boundary b
    int face_index = Bulk_mesh_pt->face_index_at_boundary(b,e);
    // Build the corresponding prescribed-traction element
    NavierStokesTractionElement<ELEMENT>* traction_element_pt =
     new  NavierStokesTractionElement<ELEMENT>(bulk_elem_pt,face_index);
    //Add the prescribed-flux element to the surface mesh
    Inflow_traction_mesh_pt->add_element_pt(traction_element_pt);
   } //end of loop over bulk elements adjacent to boundary b
 }
References b, and e().
setup_inflow_traction_elements() [2/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::setup_inflow_traction_elements () private
Create the prescribed traction elements on the inflow.
setup_outflow_flux_control_elements() [1/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::setup_outflow_flux_control_elements private
Attach flux control elements to outflow boundary.
 {
  // Attach elements to apply traction on boundary 1
  unsigned b = 1;
  // Loop over all elements on this boundary
  unsigned n_bound_el=Bulk_mesh_pt->nboundary_element(b);
  for (unsigned e=0;e<n_bound_el;e++)
   {
    // Get pointer to bulk element
    ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
     Bulk_mesh_pt->boundary_element_pt(b,e));
    // Get the index of the face of element e along boundary b
    int face_index = Bulk_mesh_pt->face_index_at_boundary(b,e);
    // Build the corresponding flux control element
    NavierStokesFluxControlElement<ELEMENT>* flux_element_pt = new
     NavierStokesFluxControlElement<ELEMENT>(bulk_elem_pt, face_index);
    //Add the new element to its mesh
    Outflow_flux_control_sub_mesh_pt->add_element_pt(flux_element_pt);
   }
  // Build master element
  NetFluxControlElement* flux_control_el_pt = new NetFluxControlElement(
   Outflow_flux_control_sub_mesh_pt,
   &Prescribed_volume_flux);
  // Set the block id for the pressure unknown in this element for the
  // preconditioning, in 2D the Navier-Stokes pressure is in block 2
  flux_control_el_pt->dof_number_for_unknown() = 2;
  // Add NetFluxControlElement to its mesh
  Outflow_flux_control_master_mesh_pt->
   add_element_pt(flux_control_el_pt);
  // Get pointer to the outflow pressure data
  Global_Physical_Variables::Pout_data_pt =
   flux_control_el_pt->pressure_data_pt();
  // Loop over the elements in the sub mesh and pass
  // Global_Physical_Variables::Pout_data_pt to the element
  unsigned n_el = Outflow_flux_control_sub_mesh_pt->nelement();
  for (unsigned e=0; e< n_el; e++)
   {
    // Get pointer to the element
    GeneralisedElement* el_pt =
     Outflow_flux_control_sub_mesh_pt->element_pt(e);
    // Dynamic cast
    dynamic_cast<NavierStokesFluxControlElement<ELEMENT>* >(el_pt)->
     add_pressure_data(Global_Physical_Variables::Pout_data_pt);
   }
 }
References b, oomph::NetFluxControlElement< ELEMENT >::dof_number_for_unknown(), e(), Global_Physical_Variables::Pout_data_pt, GlobalPhysicalParameters::Prescribed_volume_flux, and oomph::NetFluxControlElement< ELEMENT >::pressure_data_pt().
setup_outflow_flux_control_elements() [2/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::setup_outflow_flux_control_elements () private
Attach flux control elements to outflow boundary.
setup_outflow_impedance_elements() [1/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::setup_outflow_impedance_elements private
Attach impedance elements to outflow boundary.
 {
  // Check we are at time t=0, otherwise this function will not work
  // since an ImpedanceTube is contstructed so it's been at steady state
  // for all previous time.
  if (time_stepper_pt()->time()>0.0)
   {
    std::ostringstream error_stream;
    error_stream
     << "Impedance is set up assuming problem has been at rest for all previous "
     << "times, \ndid you mean to set up the impedance elements at time="
     << time_stepper_pt()->time() << " ?\n";
    throw OomphLibError(error_stream.str(),
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
   }
  // Elements apply traction on boundary 1
  unsigned b = 1;
  // Loop over all elements on this boundary
  unsigned n_bound_el=Bulk_mesh_pt->nboundary_element(b);
  if (Outflow_type==1)
   {
    for (unsigned e=0;e<n_bound_el;e++)
     {
      // Get pointer to bulk element
      ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
       Bulk_mesh_pt->boundary_element_pt(b,e));
      // Get the index of the face of element e along boundary b
      int face_index = Bulk_mesh_pt->face_index_at_boundary(b,e);
      // Build the corresponding prescribed traction element
      NavierStokesImpedanceTractionElement
       <ELEMENT,QWomersleyElement<1,3>,1>* traction_element_pt =
       new NavierStokesImpedanceTractionElement
       <ELEMENT,QWomersleyElement<1,3>,1>(bulk_elem_pt,face_index);
      //Add the prescribed traction element to the mesh
      Outflow_impedance_mesh_pt->add_element_pt(traction_element_pt);
     }
    // fixed coord in bulk mesh which is constant at the outflow
    unsigned fixed_coordinate=0;
    // nodal index of velocity component which defines the outflow
    unsigned v_index=0;
    // Build Womersley impedance tube and let it provide the
    // outflow traction to the elements in the Outflow_traction_mesh_pt.
    Womersley_impedance_tube_pt=
     new WomersleyOutflowImpedanceTube<QWomersleyElement<1,3>,1>
     (L_impedance,
      Outflow_impedance_mesh_pt,
      fixed_coordinate,
      v_index);
   }
  else
   {
    // Loop over all elements on this boundary
    unsigned n_bound_el=Bulk_mesh_pt->nboundary_element(b);
    for (unsigned e=0;e<n_bound_el;e++)
     {
      // Get pointer to bulk element
      ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
       Bulk_mesh_pt->boundary_element_pt(b,e));
      // Get the index of the face of element e along boundary b
      int face_index = Bulk_mesh_pt->face_index_at_boundary(b,e);
      // Build the corresponding flux control element
      NavierStokesFluxControlElement<ELEMENT>* flux_element_pt = new
       NavierStokesFluxControlElement<ELEMENT>(bulk_elem_pt, face_index);
      //Add the new element to its mesh
      Outflow_flux_control_sub_mesh_pt->add_element_pt(flux_element_pt);
     }
    // fixed coord in bulk mesh which is constant at the outflow
    unsigned fixed_coordinate=0;
    // nodal index of velocity component which defines the outflow
    unsigned v_index=0;
    // Build Womersley impedance tube and let it provide the
    // outflow traction to the elements in the Outflow_traction_mesh_pt.
    Womersley_impedance_tube_pt=
     new WomersleyOutflowImpedanceTube<QWomersleyElement<1,3>,1>(
      L_impedance,
      Outflow_flux_control_sub_mesh_pt,
      fixed_coordinate,
      v_index);
    // Build the pressure control element and add to the master mesh
    NavierStokesWomersleyPressureControlElement* pressure_control_element
    = new NavierStokesWomersleyPressureControlElement(
     Womersley_impedance_tube_pt);
    Outflow_impedance_master_mesh_pt->add_element_pt(pressure_control_element);
    // Build the flux control master element and add to the master mesh
    NetFluxControlElementForWomersleyPressureControl* flux_control_element
    = new NetFluxControlElementForWomersleyPressureControl
       (Outflow_flux_control_sub_mesh_pt, pressure_control_element);
    Outflow_impedance_master_mesh_pt->add_element_pt(flux_control_element);
   }
 }
References b, e(), GlobalPhysicalParameters::L_impedance, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
setup_outflow_impedance_elements() [2/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::setup_outflow_impedance_elements () private
switch_off_wall_oscillations() [1/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::switch_off_wall_oscillations () inline
Function to switch off wall oscillations.
   {
    Wall_pt->enable_remain_steady_at_maximum_amplitude();
   }
switch_off_wall_oscillations() [2/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::switch_off_wall_oscillations () inline
Function to switch off wall oscillations.
   {
    Wall_pt->enable_remain_steady_at_maximum_amplitude();
   }
unsteady_run() [1/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::unsteady_run (string directory_for_data, double nstep, const bool & validation_run = false)
Run unsteady problem.
 {
  // Set volume flux consistent with Re
  Prescribed_volume_flux = 1.0;
  // Pressure/applied traction on the left boundary: This is consistent with
  // steady Poiseuille flow
  Global_Physical_Variables::P_up=
   12.0*(Lup+Lcollapsible+Ldown+L_impedance);
  DocInfo doc_info;
  doc_info.set_directory(directory_for_data);
  // Open a trace file
  ofstream trace_file;
  char filename[100];
  sprintf(filename,"%s/trace.dat",doc_info.directory().c_str());
  trace_file.open(filename);
  // Number of timesteps per period
  unsigned nsteps_per_period=40;
  //Timestep:
  double dt=Period/double(nsteps_per_period);
  if (validation_run)
   {
    nstep=10;
    dt=0.25;
   }
  oomph_info << "Timestep=" << dt << "\n";
  // Start time
  double t_min=0.0;
  // Initialise timestep and set initial conditions
  time_pt()->time()=t_min;
  initialise_dt(dt);
  set_initial_condition();
  // Output the initial solution
  doc_solution(doc_info, trace_file);
  // Step number
  doc_info.number()++;
  // Set targets for spatial adaptivity
  bulk_mesh_pt()->max_permitted_error()=1.0e-3;
  bulk_mesh_pt()->min_permitted_error()=1.0e-5;
  // Setup impedance tube so its initial conditions
  // correspond to an impulsive start from the current flow rate
  if (Womersley_impedance_tube_pt!=0)
   {
    double q_initial=Womersley_impedance_tube_pt->
     total_volume_flux_into_impedance_tube();
    oomph_info << "q_initial=" << q_initial << "\n";
    Womersley_impedance_tube_pt->setup(&Global_Physical_Variables::ReSt,
                                       dt,
                                       q_initial,
                                       new BDF<2>);
   }
  // Timestepping loop
  for (unsigned istep=0;istep<nstep;istep++)
   {
    oomph_info << "\n\nNewton solve: " << istep << "\n";
    oomph_info << "-----------------\n";
    // Solve the problem
    unsteady_newton_solve(dt);
    // Outpt the solution
    doc_solution(doc_info, trace_file);
    // Step number
    doc_info.number()++;
   }
  trace_file.close();
 }
References oomph::DocInfo::directory(), MergeRestartFiles::filename, GlobalPhysicalParameters::L_impedance, Global_Parameters::Ldown, Global_Parameters::Lup, oomph::DocInfo::number(), oomph::oomph_info, Global_Physical_Variables::P_up, Global_Physical_Variables::Period, GlobalPhysicalParameters::Prescribed_volume_flux, Global_Physical_Variables::ReSt, and oomph::DocInfo::set_directory().
unsteady_run() [2/2]
template<class ELEMENT > void CollapsibleChannelProblem< ELEMENT >::unsteady_run (string directory_for_data, double nstep, const bool & validation_run = false)
Run unsteady problem.
Member Data Documentation
Amplitude
template<class ELEMENT > double CollapsibleChannelProblem< ELEMENT >::Amplitude private
Amplitude of osciallation.
Bulk_mesh_id
template<class ELEMENT > unsigned CollapsibleChannelProblem< ELEMENT >::Bulk_mesh_id private
Id of the fluid bulk mesh.
Bulk_mesh_pt [1/3]
template<class ELEMENT > RefineableCollapsibleChannelMesh< ELEMENT > * CollapsibleChannelProblem< ELEMENT >::Bulk_mesh_pt private
Pointer to the "bulk" mesh.
Bulk_mesh_pt [2/3]
template<class ELEMENT > MyAlgebraicCollapsibleChannelMesh<ELEMENT>* CollapsibleChannelProblem< ELEMENT >::Bulk_mesh_pt private
Pointer to the "bulk" mesh.
Bulk_mesh_pt [3/3]
template<class ELEMENT > ElasticRefineableCollapsibleChannelMesh<ELEMENT>* CollapsibleChannelProblem< ELEMENT >::Bulk_mesh_pt private
Pointer to the "bulk" mesh.
Constitutive_law_pt
template<class ELEMENT > ConstitutiveLaw* CollapsibleChannelProblem< ELEMENT >::Constitutive_law_pt private
Constitutive law used to determine the mesh deformation.
Inflow_traction_mesh_pt
template<class ELEMENT > Mesh * CollapsibleChannelProblem< ELEMENT >::Inflow_traction_mesh_pt private
Pointer to the "surface" mesh that contains the applied traction elements at the inflow
L_impedance
template<class ELEMENT > double CollapsibleChannelProblem< ELEMENT >::L_impedance private
Length of optional impedance tube.
Lagrange_multiplier_mesh_pt
template<class ELEMENT > SolidMesh* CollapsibleChannelProblem< ELEMENT >::Lagrange_multiplier_mesh_pt private
Pointers to meshes of Lagrange multiplier elements.
Lcollapsible
template<class ELEMENT > double CollapsibleChannelProblem< ELEMENT >::Lcollapsible private
x-length in the "collapsible" part of the channel
Ldown
template<class ELEMENT > double CollapsibleChannelProblem< ELEMENT >::Ldown private
x-length in the downstream part of the channel
Left_node_pt
template<class ELEMENT > Node * CollapsibleChannelProblem< ELEMENT >::Left_node_pt private
Pointer to the left control node.
Lup
template<class ELEMENT > double CollapsibleChannelProblem< ELEMENT >::Lup private
x-length in the upstream part of the channel
Ly
template<class ELEMENT > double CollapsibleChannelProblem< ELEMENT >::Ly private
Transverse length.
Ncollapsible
template<class ELEMENT > unsigned CollapsibleChannelProblem< ELEMENT >::Ncollapsible private
Number of elements in the x direction in the "collapsible" part of the channel
Ndown
template<class ELEMENT > unsigned CollapsibleChannelProblem< ELEMENT >::Ndown private
Number of elements in the x direction in the downstream part of the channel.
Nup
template<class ELEMENT > unsigned CollapsibleChannelProblem< ELEMENT >::Nup private
Number of elements in the x direction in the upstream part of the channel.
Ny
template<class ELEMENT > unsigned CollapsibleChannelProblem< ELEMENT >::Ny private
Number of elements across the channel.
Outflow_flux_control_master_mesh_pt
template<class ELEMENT > Mesh * CollapsibleChannelProblem< ELEMENT >::Outflow_flux_control_master_mesh_pt private
Pointer to mesh containing the net flux control element (only!)
Outflow_flux_control_sub_mesh_pt
template<class ELEMENT > Mesh * CollapsibleChannelProblem< ELEMENT >::Outflow_flux_control_sub_mesh_pt private
Pointer to mesh of flux control elements at outflow.
Outflow_impedance_master_mesh_pt
template<class ELEMENT > Mesh * CollapsibleChannelProblem< ELEMENT >::Outflow_impedance_master_mesh_pt private
Pointer to the master impedance mesh when using flux control elements.
Outflow_impedance_mesh_pt
template<class ELEMENT > Mesh * CollapsibleChannelProblem< ELEMENT >::Outflow_impedance_mesh_pt private
Pointer to the impedance mesh.
Outflow_type
template<class ELEMENT > unsigned CollapsibleChannelProblem< ELEMENT >::Outflow_type private
Outflow boundary type: 0: prescribed flux boundary conditions 1: impedance boundary conditions 2: prescribed outflow Otherwise we have pressure driven flow with zero pressure at outlet
Period
template<class ELEMENT > double CollapsibleChannelProblem< ELEMENT >::Period private
Period of oscillation.
Prescribed_volume_flux
template<class ELEMENT > double CollapsibleChannelProblem< ELEMENT >::Prescribed_volume_flux private
Prescribed volume flux: set to -1 for value consistent with Re.
Right_node_pt
template<class ELEMENT > Node * CollapsibleChannelProblem< ELEMENT >::Right_node_pt private
Pointer to right control node.
Surface_mesh_pt
template<class ELEMENT > Mesh * CollapsibleChannelProblem< ELEMENT >::Surface_mesh_pt private
Pointer to the "surface" mesh that contains the applied traction elements
Wall_pt
template<class ELEMENT > OscillatingWall * CollapsibleChannelProblem< ELEMENT >::Wall_pt private
Pointer to the geometric object that parametrises the "collapsible" wall.
Womersley_impedance_tube_pt
template<class ELEMENT > WomersleyOutflowImpedanceTube< QWomersleyElement< 1, 3 >, 1 > * CollapsibleChannelProblem< ELEMENT >::Womersley_impedance_tube_pt private
Pointer to impendance tube.
The documentation for this class was generated from the following files:
collapsible_channel.cc
collapsible_channel_algebraic.cc
flux_control.cc
pseudo_solid_collapsible_channel.cc
one_d_womersley.cc