MercuryDPM: BenchSparseUtil.h File Reference
BenchSparseUtil.h File Reference
#include <Eigen/Sparse>
#include <bench/BenchTimer.h>
#include <set>
#include "gmm/gmm.h"
#include <boost/numeric/mtl/mtl.hpp>
#include <boost/numeric/ublas/vector.hpp>
#include <boost/numeric/ublas/matrix.hpp>
#include <boost/numeric/ublas/io.hpp>
#include <boost/numeric/ublas/triangular.hpp>
#include <boost/numeric/ublas/vector_sparse.hpp>
#include <boost/numeric/ublas/matrix_sparse.hpp>
#include <boost/numeric/ublas/vector_of_vector.hpp>
#include <boost/numeric/ublas/operation.hpp>
Macros
#define SIZE 1024
#define DENSITY 0.01
#define SCALAR double
Typedefs
typedef SCALAR Scalar
typedef Matrix< Scalar, Dynamic, Dynamic > DenseMatrix
typedef Matrix< Scalar, Dynamic, 1 > DenseVector
typedef SparseMatrix< Scalar > EigenSparseMatrix
typedef gmm::csc_matrix< Scalar > GmmSparse
typedef gmm::col_matrix< gmm::wsvector< Scalar > > GmmDynSparse
typedef mtl::compressed2D< Scalar, mtl::matrix::parameters< mtl::tag::col_major > > MtlSparse
typedef mtl::compressed2D< Scalar, mtl::matrix::parameters< mtl::tag::row_major > > MtlSparseRowMajor
typedef boost::numeric::ublas::compressed_matrix< Scalar, boost::numeric::ublas::column_major > UBlasSparse
Functions
void fillMatrix (float density, int rows, int cols, EigenSparseMatrix &dst)
void fillMatrix2 (int nnzPerCol, int rows, int cols, EigenSparseMatrix &dst)
void eiToDense (const EigenSparseMatrix &src, DenseMatrix &dst)
void eiToGmm (const EigenSparseMatrix &src, GmmSparse &dst)
void eiToMtl (const EigenSparseMatrix &src, MtlSparse &dst)
void eiToUblas (const EigenSparseMatrix &src, UBlasSparse &dst)
template<typename EigenType , typename UblasType >
void eiToUblasVec (const EigenType &src, UblasType &dst)
Macro Definition Documentation
DENSITY
#define DENSITY 0.01
SCALAR
#define SCALAR double
SIZE
#define SIZE 1024
Typedef Documentation
DenseMatrix
typedef Matrix<Scalar, Dynamic, Dynamic> DenseMatrix
DenseVector
typedef Matrix<Scalar, Dynamic, 1> DenseVector
EigenSparseMatrix
typedef SparseMatrix<Scalar> EigenSparseMatrix
GmmDynSparse
typedef gmm::col_matrix<gmm::wsvector<Scalar> > GmmDynSparse
GmmSparse
typedef gmm::csc_matrix<Scalar> GmmSparse
MtlSparse
typedef mtl::compressed2D<Scalar, mtl::matrix::parameters<mtl::tag::col_major> > MtlSparse
MtlSparseRowMajor
typedef mtl::compressed2D<Scalar, mtl::matrix::parameters<mtl::tag::row_major> > MtlSparseRowMajor
Scalar
typedef SCALAR Scalar
UBlasSparse
typedef boost::numeric::ublas::compressed_matrix<Scalar, boost::numeric::ublas::column_major> UBlasSparse
Function Documentation
eiToDense()
void eiToDense (const EigenSparseMatrix & src, DenseMatrix & dst)
{
   dst.setZero();
   for (int j = 0; j < src.cols(); ++j)
     for (EigenSparseMatrix::InnerIterator it(src.derived(), j); it; ++it) dst(it.index(), j) = it.value();
 }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::cols(), Eigen::SparseMatrixBase< Derived >::derived(), j, and Eigen::PlainObjectBase< Derived >::setZero().
Referenced by main().
eiToGmm()
void eiToGmm (const EigenSparseMatrix & src, GmmSparse & dst)
{
   GmmDynSparse tmp(src.rows(), src.cols());
   for (int j = 0; j < src.cols(); ++j)
     for (EigenSparseMatrix::InnerIterator it(src.derived(), j); it; ++it) tmp(it.index(), j) = it.value();
   gmm::copy(tmp, dst);
 }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::cols(), copy(), Eigen::SparseMatrixBase< Derived >::derived(), j, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::rows(), and tmp.
Referenced by __attribute__(), and main().
eiToMtl()
void eiToMtl (const EigenSparseMatrix & src, MtlSparse & dst)
{
   mtl::matrix::inserter<MtlSparse> ins(dst);
   for (int j = 0; j < src.cols(); ++j)
     for (EigenSparseMatrix::InnerIterator it(src.derived(), j); it; ++it) ins[it.index()][j] = it.value();
 }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::cols(), Eigen::SparseMatrixBase< Derived >::derived(), and j.
Referenced by main().
eiToUblas()
void eiToUblas (const EigenSparseMatrix & src, UBlasSparse & dst)
{
   dst.resize(src.rows(), src.cols(), false);
   for (int j = 0; j < src.cols(); ++j)
     for (EigenSparseMatrix::InnerIterator it(src.derived(), j); it; ++it) dst(it.index(), j) = it.value();
 }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::cols(), Eigen::SparseMatrixBase< Derived >::derived(), j, and Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::rows().
Referenced by main().
eiToUblasVec()
template<typename EigenType , typename UblasType > void eiToUblasVec (const EigenType & src, UblasType & dst)
{
   dst.resize(src.size());
   for (int j = 0; j < src.size(); ++j) dst[j] = src.coeff(j);
 }
References j.
Referenced by main().
fillMatrix()
void fillMatrix (float density, int rows, int cols, EigenSparseMatrix & dst)
{
   dst.reserve(double(rows) * cols * density);
   for (int j = 0; j < cols; j++) {
     for (int i = 0; i < rows; i++) {
       Scalar v = (internal::random<float>(0, 1) < density) ? internal::random<Scalar>() : 0;
       if (v != 0) dst.insert(i, j) = v;
     }
   }
   dst.finalize();
 }
References cols, UniformPSDSelfTest::density, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::finalize(), i, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insert(), j, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::reserve(), rows, and v.
Referenced by main().
fillMatrix2()
void fillMatrix2 (int nnzPerCol, int rows, int cols, EigenSparseMatrix & dst)
{
   //   std::cout << "alloc " << nnzPerCol*cols << "\n";
   dst.reserve(nnzPerCol * cols);
   for (int j = 0; j < cols; j++) {
     std::set<int> aux;
     for (int i = 0; i < nnzPerCol; i++) {
       int k = internal::random<int>(0, rows - 1);
       while (aux.find(k) != aux.end()) k = internal::random<int>(0, rows - 1);
       aux.insert(k);
       dst.insert(k, j) = internal::random<Scalar>();
     }
   }
   dst.finalize();
 }
References cols, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::finalize(), i, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insert(), j, k, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::reserve(), and rows.
Referenced by main().