MercuryDPM: ParticleBeam.cpp File Reference
ParticleBeam.cpp File Reference
#include "Mercury3D.h"
#include "Species/LinearViscoelasticReversibleAdhesiveSpecies.h"
Classes
class ParticleBeam
A 1D "beam" structure composed of particles.
Functions
int main ()
Function Documentation
main()
int main ()
            {
     ParticleBeam dpm;
     dpm.write(std::cout);
     dpm.solve();
     helpers::writeToFile(dpm.getName()+".gnu","p 'ParticleBeam.data' u 1 ev 101::99");
     return 0;
 }
References DPMBase::getName(), DPMBase::solve(), MercuryBase::write(), and helpers::writeToFile().