MercuryDPM: Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse > Struct Template Reference
Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse > Struct Template Reference
#include <SparseAssign.h>
Public Types
typedef DstXprType::StorageIndex StorageIndex
typedef DstXprType::Scalar Scalar
Static Public Member Functions
template<int Options, typename AssignFunc >
static void run (SparseMatrix< Scalar, Options, StorageIndex > &dst, const SrcXprType &src, const AssignFunc &func)
template<typename DstDerived >
static void run (SparseMatrixBase< DstDerived > &dst, const SrcXprType &src, const internal::assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &)
template<typename DstDerived >
static void run (SparseMatrixBase< DstDerived > &dst, const SrcXprType &src, const internal::add_assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &)
template<typename DstDerived >
static void run (SparseMatrixBase< DstDerived > &dst, const SrcXprType &src, const internal::sub_assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &)
Member Typedef Documentation
Scalar
template<typename DstXprType , typename SrcXprType , typename Functor > typedef DstXprType::Scalar Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::Scalar
StorageIndex
template<typename DstXprType , typename SrcXprType , typename Functor > typedef DstXprType::StorageIndex Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::StorageIndex
Member Function Documentation
run() [1/4]
template<typename DstXprType , typename SrcXprType , typename Functor > template<int Options, typename AssignFunc > static void Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run (SparseMatrix< Scalar, Options, StorageIndex > & dst, const SrcXprType & src, const AssignFunc & func) inline static
{
     dst.assignDiagonal(src.diagonal(), func);
   }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::assignDiagonal().
run() [2/4]
template<typename DstXprType , typename SrcXprType , typename Functor > template<typename DstDerived > static void Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run (SparseMatrixBase< DstDerived > & dst, const SrcXprType & src, const internal::add_assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &) inline static
{
     dst.derived().diagonal() += src.diagonal();
   }
References Eigen::SparseMatrixBase< Derived >::derived().
run() [3/4]
template<typename DstXprType , typename SrcXprType , typename Functor > template<typename DstDerived > static void Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run (SparseMatrixBase< DstDerived > & dst, const SrcXprType & src, const internal::assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &) inline static
{
     dst.derived().diagonal() = src.diagonal();
   }
References Eigen::SparseMatrixBase< Derived >::derived().
run() [4/4]
template<typename DstXprType , typename SrcXprType , typename Functor > template<typename DstDerived > static void Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run (SparseMatrixBase< DstDerived > & dst, const SrcXprType & src, const internal::sub_assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &) inline static
{
     dst.derived().diagonal() -= src.diagonal();
   }
References Eigen::SparseMatrixBase< Derived >::derived().
The documentation for this struct was generated from the following file:
SparseAssign.h