MercuryDPM: oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT > Class Template Reference
oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT > Class Template Reference
Public Member Functions
SpineLineMarangoniSurfactantFluidInterfaceElement (FiniteElement *const &element_pt, const int &face_index)
double bi ()
Return the Biot number.
double ma ()
Return the Marangoni number.
double beta ()
Return the Elasticity number.
double peclet_s ()
Return the surface peclect number.
double peclet_strouhal_s ()
Return the surface peclect strouhal number.
double *& ma_pt ()
Access function for pointer to the Marangoni number.
double *& bi_pt ()
Access function for pointer to the Biot number.
double *& beta_pt ()
Access function for pointer to the Elasticity number.
double *& peclet_s_pt ()
Access function for pointer to the surface Peclet number.
double *& peclet_strouhal_s_pt ()
Access function for pointer to the surface Peclet x Strouhal number.
void output (std::ostream &outfile, const unsigned &n_plot)
SpineLineMarangoniSurfactantFluidInterfaceElement (FiniteElement *const &element_pt, const int &face_index)
double bi ()
Return the Biot number.
double ma ()
Return the Marangoni number.
double beta ()
Return the Elasticity number.
double peclet_s ()
Return the surface peclect number.
double peclet_strouhal_s ()
Return the surface peclect strouhal number.
double d ()
Return the diffusion ratio.
double k ()
Return the reaction ratio.
double *& ma_pt ()
Access function for pointer to the Marangoni number.
double *& bi_pt ()
Access function for pointer to the Biot number.
double *& beta_pt ()
Access function for pointer to the Elasticity number.
double *& peclet_s_pt ()
Access function for pointer to the surface Peclet number.
double *& peclet_strouhal_s_pt ()
Access function for pointer to the surface Peclet x Strouhal number.
double *& d_pt ()
Access function for pointer to the diffusion ratios.
double *& k_pt ()
Access function for pointer to the reaction ratios.
void output (std::ostream &outfile, const unsigned &n_plot)
Public Member Functions inherited from oomph::SpineLineFluidInterfaceElement< ELEMENT >
SpineLineFluidInterfaceElement (FiniteElement *const &element_pt, const int &face_index)
Public Member Functions inherited from oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >
SpineUpdateFluidInterfaceElement (FiniteElement *const &element_pt, const int &face_index, const unsigned &id=0)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Calculate the contribution to the residuals and the jacobian.
void add_additional_residual_contributions_interface (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag, const Shape &psif, const DShape &dpsifds, const DShape &dpsifdS, const DShape &dpsifdS_div, const Vector< double > &s, const Vector< double > &interpolated_x, const Vector< double > &interpolated_n, const double &W, const double &J)
Helper function to calculate the additional contributions These are those filled in by the particular equations.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output the element.
void output (FILE *file_pt)
Overload the C-style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style Output function.
virtual FluidInterfaceBoundingElement * make_bounding_element (const int &face_index)
Public Member Functions inherited from oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >
Hijacked ()
Constructor, call the constructors of the base elements.
Hijacked (FiniteElement *const &element_pt, const int &face_index)
Constructor used for hijacking face elements.
Hijacked (FiniteElement *const &element_pt, const int &face_index, const unsigned &id=0)
Data * hijack_internal_value (const unsigned &n, const unsigned &i, const bool &return_data=true)
Data * hijack_external_value (const unsigned &n, const unsigned &i, const bool &return_data=true)
Data * hijack_nodal_value (const unsigned &n, const unsigned &i, const bool &return_data=true)
Data * hijack_nodal_position_value (const unsigned &n, const unsigned &i, const bool &return_data=true)
Data * hijack_nodal_spine_value (const unsigned &n, const unsigned &i, const bool &return_data=true)
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
void get_residuals (Vector< double > &residuals)
void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Public Member Functions inherited from oomph::SpineElement< FaceGeometry< ELEMENT > >
SpineElement ()
Constructor, call the constructor of the base element.
SpineElement (FiniteElement *const &element_pt, const int &face_index)
Constructor used for spine face elements.
~SpineElement ()
Destructor, clean up the storage allocated to the local equation numbers.
int spine_local_eqn (const unsigned &n)
Public Member Functions inherited from oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
ElementWithSpecificMovingNodes ()
Constructor, call the constructor of the base element.
ElementWithSpecificMovingNodes (FiniteElement *const &element_pt, const int &face_index)
Constructor used for face elements.
~ElementWithSpecificMovingNodes ()
Empty Destructor,.
void describe_local_dofs (std::ostream &out, std::string &curr_str)
Unique final overrider for describe_dofs.
Node * construct_node (const unsigned &n)
Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Overloaded node allocation for unsteady problems.
Node * construct_boundary_node (const unsigned &n)
Overload the node assignment routine to assign boundary nodes.
Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Overloaded boundary node allocation for unsteady problems.
void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Compute the element's residuals vector and jacobian matrix.
Public Member Functions inherited from oomph::ElementWithMovingNodes
ElementWithMovingNodes ()
Constructor.
ElementWithMovingNodes (const ElementWithMovingNodes &)=delete
Broken copy constructor.
void operator= (const ElementWithMovingNodes &)=delete
Broken assignment operator.
virtual ~ElementWithMovingNodes ()
Virtual destructor (clean up and allocated memory)
unsigned ngeom_dof () const
Number of geometric dofs.
int geometric_data_local_eqn (const unsigned &n, const unsigned &i)
void assemble_set_of_all_geometric_data (std::set< Data * > &unique_geom_data_pt)
Return a set of all geometric data associated with the element.
void identify_geometric_data (std::set< Data * > &geometric_data_pt)
bool are_dresidual_dnodal_coordinates_always_evaluated_by_fd () const
Return whether shape derivatives are evaluated by fd.
void enable_always_evaluate_dresidual_dnodal_coordinates_by_fd ()
void disable_always_evaluate_dresidual_dnodal_coordinates_by_fd ()
void evaluate_shape_derivs_by_direct_fd ()
Evaluate shape derivatives by direct finite differencing.
void evaluate_shape_derivs_by_chain_rule (const bool &i_know_what_i_am_doing=false)
void evaluate_shape_derivs_by_fastest_method (const bool &i_know_what_i_am_doing=false)
int & method_for_shape_derivs ()
Access to method (enumerated flag) for determination of shape derivs.
void enable_bypass_fill_in_jacobian_from_geometric_data ()
Bypass the call to fill_in_jacobian_from_geometric_data.
void disable_bypass_fill_in_jacobian_from_geometric_data ()
Do not bypass the call to fill_in_jacobian_from_geometric_data.
bool is_fill_in_jacobian_from_geometric_data_bypassed () const
unsigned ngeom_data () const
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::SpineFiniteElement
SpineFiniteElement ()
Empty constructor.
virtual ~SpineFiniteElement ()
Emtpty virtual destructor.
Public Member Functions inherited from oomph::HijackedElementBase
HijackedElementBase ()
virtual ~HijackedElementBase ()
Destructor, destroy the storage for the equation numbers.
void unhijack_all_data ()
const double & residual_multiplier () const
Return the value of the residual multiplier.
double *& residual_multiplier_pt ()
Return the pointer to the residual multiplier.
Public Member Functions inherited from oomph::FluidInterfaceElement
FluidInterfaceElement ()
Constructor, set the default values of the booleans and pointers (null)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Calculate the residuals by calling the generic residual contribution.
const double & ca () const
The value of the Capillary number.
double *& ca_pt ()
Pointer to the Capillary number.
const double & st () const
The value of the Strouhal number.
double *& st_pt ()
The pointer to the Strouhal number.
double u (const unsigned &j, const unsigned &i)
Return the i-th velocity component at local node j.
double interpolated_u (const Vector< double > &s, const unsigned &i)
Calculate the i-th velocity component at the local coordinate s.
double pext () const
Return the value of the external pressure.
void set_external_pressure_data (Data *external_pressure_data_pt)
void set_external_pressure_data (Data *external_pressure_data_pt, const unsigned &index_of_external_pressure_value)
Public Member Functions inherited from oomph::FaceElement
FaceElement ()
Constructor: Initialise all appropriate member data.
virtual ~FaceElement ()
Empty virtual destructor.
FaceElement (const FaceElement &)=delete
Broken copy constructor.
const unsigned & boundary_number_in_bulk_mesh () const
Broken assignment operator.
void set_boundary_number_in_bulk_mesh (const unsigned &b)
Set function for the boundary number in bulk mesh.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
double J_eulerian (const Vector< double > &s) const
double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
double interpolated_x (const Vector< double > &s, const unsigned &i) const
double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
void interpolated_x (const Vector< double > &s, Vector< double > &x) const
void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
int & normal_sign ()
int normal_sign () const
int & face_index ()
int face_index () const
const Vector< double > * tangent_direction_pt () const
Public access function for the tangent direction pointer.
void set_tangent_direction (Vector< double > *tangent_direction_pt)
Set the tangent direction vector.
void turn_on_warning_for_discontinuous_tangent ()
void turn_off_warning_for_discontinuous_tangent ()
void continuous_tangent_and_outer_unit_normal (const Vector< double > &s, Vector< Vector< double >> &tang_vec, Vector< double > &unit_normal) const
void continuous_tangent_and_outer_unit_normal (const unsigned &ipt, Vector< Vector< double >> &tang_vec, Vector< double > &unit_normal) const
void outer_unit_normal (const Vector< double > &s, Vector< double > &unit_normal) const
Compute outer unit normal at the specified local coordinate.
void outer_unit_normal (const unsigned &ipt, Vector< double > &unit_normal) const
Compute outer unit normal at ipt-th integration point.
FiniteElement *& bulk_element_pt ()
Pointer to higher-dimensional "bulk" element.
FiniteElement * bulk_element_pt () const
Pointer to higher-dimensional "bulk" element (const version)
CoordinateMappingFctPt & face_to_bulk_coordinate_fct_pt ()
CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt () const
BulkCoordinateDerivativesFctPt & bulk_coordinate_derivatives_fct_pt ()
BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt () const
Vector< double > local_coordinate_in_bulk (const Vector< double > &s) const
void get_local_coordinate_in_bulk (const Vector< double > &s, Vector< double > &s_bulk) const
void get_ds_bulk_ds_face (const Vector< double > &s, DenseMatrix< double > &dsbulk_dsface, unsigned &interior_direction) const
unsigned & bulk_position_type (const unsigned &i)
const unsigned & bulk_position_type (const unsigned &i) const
void bulk_node_number_resize (const unsigned &i)
Resize the storage for the bulk node numbers.
unsigned & bulk_node_number (const unsigned &n)
const unsigned & bulk_node_number (const unsigned &n) const
void bulk_position_type_resize (const unsigned &i)
Resize the storage for bulk_position_type to i entries.
unsigned & nbulk_value (const unsigned &n)
unsigned nbulk_value (const unsigned &n) const
void nbulk_value_resize (const unsigned &i)
void resize_nodes (Vector< unsigned > &nadditional_data_values)
void output_zeta (std::ostream &outfile, const unsigned &nplot)
Output boundary coordinate zeta.
Public Member Functions inherited from oomph::LineDerivatives
LineDerivatives ()
Protected Member Functions
double interpolated_T (const Vector< double > &s)
Get the temperature.
double interpolated_C (const Vector< double > &s)
Get the surfactant concentration.
double dcdt_surface (const unsigned &l) const
The time derivative of the surface concentration.
double sigma (const Vector< double > &s)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Calculate the contribution to the jacobian.
void add_additional_residual_contributions_interface (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag, const Shape &psif, const DShape &dpsifds, const DShape &dpsifdS, const DShape &dpsifds_div, const Vector< double > &s, const Vector< double > &interpolated_x, const Vector< double > &interpolated_n, const double &W, const double &J)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
double interpolated_T (const Vector< double > &s)
Get the temperature.
double interpolated_C (const Vector< double > &s)
Get the surfactant concentration.
double dcdt_surface (const unsigned &l) const
The time derivative of the surface concentration.
double sigma (const Vector< double > &s)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Calculate the contribution to the jacobian.
void add_additional_residual_contributions_interface (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag, const Shape &psif, const DShape &dpsifds, const DShape &dpsifdS, const DShape &dpsifds_div, const Vector< double > &s, const Vector< double > &interpolated_x, const Vector< double > &interpolated_n, const double &W, const double &J)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Protected Member Functions inherited from oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >
double compute_surface_derivatives (const Shape &psi, const DShape &dpsids, const DenseMatrix< double > &interpolated_t, const Vector< double > &interpolated_x, DShape &surface_gradient, DShape &surface_divergence)
Protected Member Functions inherited from oomph::ElementWithMovingNodes
virtual void get_dnodal_coordinates_dgeom_dofs (RankThreeTensor< double > &dnodal_coordinates_dgeom_dofs)
void fill_in_jacobian_from_geometric_data (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_geometric_data (DenseMatrix< double > &jacobian)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::HijackedElementBase
void hijack_global_eqn (long *const &global_eqn_pt)
void unhijack_global_eqn (long *const &global_eqn_pt)
Protected Member Functions inherited from oomph::FluidInterfaceElement
int pext_local_eqn ()
virtual void fill_in_generic_residual_contribution_interface (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Protected Member Functions inherited from oomph::FaceElement
void add_additional_values (const Vector< unsigned > &nadditional_values, const unsigned &id)
Protected Member Functions inherited from oomph::LineDerivatives
double compute_surface_derivatives (const Shape &psi, const DShape &dpsids, const DenseMatrix< double > &interpolated_t, const Vector< double > &interpolated_x, DShape &surface_gradient, DShape &surface_divergence)
Fill in the specific surface derivative calculations.
Private Attributes
double * Bi_pt
Pointer to a Biot number.
double * Ma_pt
Pointer to a Marangoni number.
double * Beta_pt
Pointer to an Elasticity number.
double * Peclet_S_pt
Pointer to Surface Peclet number.
double * Peclet_Strouhal_S_pt
Pointer to the surface Peclect Strouhal number.
unsigned T_index
Index at which the temperature is stored at the nodes.
unsigned C_index
double * D_pt
Pointer to the diffusion ratios.
double * K_pt
Pointer to the reaction ratios.
unsigned C_bulk_index
Index at which the bulk concentration is stored at the nodes.
Static Private Attributes
static double Default_Physical_Constant_Value = 1.0
Default value of the physical constants.
Additional Inherited Members
Public Types inherited from oomph::ElementWithMovingNodes
enum { Shape_derivs_by_chain_rule , Shape_derivs_by_direct_fd , Shape_derivs_by_fastest_method }
Public enumeration to choose method for computing shape derivatives.
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Attributes inherited from oomph::ElementWithMovingNodes
Vector< Data * > Geom_data_pt
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::HijackedElementBase
std::set< long * > * Hijacked_global_eqn_number_pt
Vector< int > * Hijacked_local_eqn_number_pt
double * Residual_multiplier_pt
Protected Attributes inherited from oomph::FluidInterfaceElement
Vector< unsigned > U_index_interface
Nodal index at which the i-th velocity component is stored.
int External_data_number_of_external_pressure
Data * Pext_data_pt
Pointer to the Data item that stores the external pressure.
unsigned Index_of_external_pressure_value
Which of the values in Pext_data_pt stores the external pressure.
Protected Attributes inherited from oomph::FaceElement
unsigned Boundary_number_in_bulk_mesh
The boundary number in the bulk mesh to which this element is attached.
FiniteElement * Bulk_element_pt
Pointer to the associated higher-dimensional "bulk" element.
Vector< unsigned > Bulk_node_number
Vector< unsigned > Nbulk_value
Vector< double > * Tangent_direction_pt
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Static Protected Attributes inherited from oomph::HijackedElementBase
static double Default_residual_multiplier = 0.0
Detailed Description
template<class ELEMENT>
class oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >
Spine-based Marangoni surface tension elements that add a linear dependence on temperature and concentration of a surface chemical to the surface tension, which decreases with increasing temperature. In addition, this element adds a flux contribution to the advection-diffusion equation to represent heat loss at the free surface. This introduces the Biot number.
Constructor & Destructor Documentation
SpineLineMarangoniSurfactantFluidInterfaceElement() [1/2]
template<class ELEMENT > oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::SpineLineMarangoniSurfactantFluidInterfaceElement (FiniteElement *const & element_pt, const int & face_index) inline
Constructor that passes the bulk element and face index down to the underlying
                                                           :
   SpineLineFluidInterfaceElement<ELEMENT>
   (element_pt,face_index)
   {
    //Initialise the values
    Bi_pt = &Default_Physical_Constant_Value;
    Ma_pt = &Default_Physical_Constant_Value;
    Beta_pt = &Default_Physical_Constant_Value;
    Peclet_S_pt = &Default_Physical_Constant_Value;
    Peclet_Strouhal_S_pt = &Default_Physical_Constant_Value;
    //Cast the bulk element
    ELEMENT* cast_element_pt = dynamic_cast<ELEMENT*>(element_pt);
    //Now find the index at which the temperature is stored from the
    //advection-diffusion part of the bulk element
    T_index = cast_element_pt->u_index_adv_diff();
    //Add the additional surfactant terms to these surface elements
    //Read out the number of nodes on the face
    //For some reason I need to specify the this pointer here(!)
    unsigned n_node_face = this->nnode();
    //Set the additional data values in the face
    //There is one additional values at each node --- the lagrange multiplier
    Vector<unsigned> additional_data_values(n_node_face);
    for(unsigned i=0;i<n_node_face;i++) additional_data_values[i] = 1;
    //Resize the data arrays accordingly
    this->resize_nodes(additional_data_values);
    //The C_index is the new final value
    //HACK HERE
    C_index = this->node_pt(0)->nvalue()-1;
   }
References oomph::MultiDomainBoussinesqHelper::Default_Physical_Constant_Value, and i.
SpineLineMarangoniSurfactantFluidInterfaceElement() [2/2]
template<class ELEMENT > oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::SpineLineMarangoniSurfactantFluidInterfaceElement (FiniteElement *const & element_pt, const int & face_index) inline
Constructor that passes the bulk element and face index down to the underlying
                                                           :
   SpineLineFluidInterfaceElement<ELEMENT>
   (element_pt,face_index)
   {
    //Initialise the values
    Bi_pt = &Default_Physical_Constant_Value;
    Ma_pt = &Default_Physical_Constant_Value;
    Beta_pt = &Default_Physical_Constant_Value;
    Peclet_S_pt = &Default_Physical_Constant_Value;
    Peclet_Strouhal_S_pt = &Default_Physical_Constant_Value;
    K_pt = &Default_Physical_Constant_Value;
    D_pt = &Default_Physical_Constant_Value;
    //Cast the bulk element
    ELEMENT* cast_element_pt = dynamic_cast<ELEMENT*>(element_pt);
    //Now find the index at which the temperature is stored from the
    //advection-diffusion part of the bulk element
    T_index = cast_element_pt->c_index_adv_diff_react(0);
    //Find the index at which the bulk surfactant concentration is stored
    C_bulk_index = cast_element_pt->c_index_adv_diff_react(1);
    //Add the additional surfactant terms to these surface elements
    //Read out the number of nodes on the face
    //For some reason I need to specify the this pointer here(!)
    unsigned n_node_face = this->nnode();
    //Set the additional data values in the face
    //There is one additional values at each node --- the lagrange multiplier
    Vector<unsigned> additional_data_values(n_node_face);
    for(unsigned i=0;i<n_node_face;i++) additional_data_values[i] = 1;
    //Resize the data arrays accordingly
    this->resize_nodes(additional_data_values);
    //The C_index is the new final value
    //HACK HERE
    C_index = this->node_pt(0)->nvalue()-1;
   }
References oomph::MultiDomainBoussinesqHelper::Default_Physical_Constant_Value, and i.
Member Function Documentation
add_additional_residual_contributions_interface() [1/2]
template<class ELEMENT > void oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::add_additional_residual_contributions_interface (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag, const Shape & psif, const DShape & dpsifds, const DShape & dpsifdS, const DShape & dpsifds_div, const Vector< double > & s, const Vector< double > & interpolated_x, const Vector< double > & interpolated_n, const double & W, const double & J) inline protected virtual
Overload the Helper function to calculate the residuals and jacobian entries. This particular function ensures that the additional entries are calculated inside the integration loop
Reimplemented from oomph::FluidInterfaceElement.
   {
    //Find the index at which the temperature is stored
    unsigned t_index = this->T_index;
    //Find out how many nodes there are
    unsigned n_node = this->nnode();
    //Read out the Bi number
    const double Bi = this->bi();
    //Now calculate the temperature at this point
    //Assuming the same shape functions are used (which they are)
    double T = 0.0;
    for(unsigned l=0;l<n_node;l++)
     {
      T += this->nodal_value(l,t_index)*psif(l);
     }
    //Storage for the local equation numbers and unknowns
    int local_eqn = 0, local_unknown = 0;
    //Now we add the flux term to the appropriate residuals
    for(unsigned l=0;l<n_node;l++)
     {
      //Read out the apprporiate local equation
      local_eqn = this->nodal_local_eqn(l,t_index);
      //If not a boundary condition
      if(local_eqn >= 0)
       {
        residuals[local_eqn] -= (1.0 + Bi*(T-1.0))*psif(l)*W*J;
        //We also need to worry about the jacobian terms
        if(flag)
         {
          //Loop over the nodes again
          for(unsigned l2=0;l2<n_node;l2++)
           {
            //Get the unknown
            local_unknown = this->nodal_local_eqn(l2,t_index);
            //If not a boundary condition
            if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) -= Bi*psif(l2)*psif(l)*W*J;
             }
           }
         }
       }
     } //End of loop over the nodes
    //Surface advection-diffusion equation
     //Find the index at which the temperature is stored
    unsigned c_index = this->C_index;
    Vector<unsigned> u_index = this->U_index_interface;
    //Read out the surface peclect number
    const double Pe_s = this->peclet_s();
    const double PeSt_s = this->peclet_strouhal_s();
    //Now calculate the concentration at this point
    //Assuming the same shape functions are used (which they are)
    double interpolated_C = 0.0;
    double interpolated_dCds = 0.0;
    double dCdt = 0.0;
    //The tangent vector
    const unsigned ndim = this->node_pt(0)->ndim();
    Vector<double> interpolated_tangent(ndim,0.0);
    Vector<double> interpolated_u(ndim,0.0);
    Vector<double> interpolated_duds(ndim,0.0);
    Vector<double> mesh_velocity(ndim,0.0);
    if(ndim != u_index.size())
     {
      throw OomphLibError("Dimension Incompatibility",
                          OOMPH_CURRENT_FUNCTION,
                          OOMPH_EXCEPTION_LOCATION);
     }
    for(unsigned l=0;l<n_node;l++)
     {
      const double psi = psif(l);
      const double dpsi = dpsifds(l,0);
      interpolated_C += this->nodal_value(l,c_index)*psi;
      interpolated_dCds += this->nodal_value(l,c_index)*dpsi;
      dCdt += dcdt_surface(l)*psi;
      for(unsigned i=0;i<ndim;i++)
       {
        interpolated_tangent[i] += this->nodal_position(l,i)*dpsi;
        interpolated_u[i] += this->nodal_value(l,u_index[i])*psi;
        interpolated_duds[i] += this->nodal_value(l,u_index[i])*dpsi;
        mesh_velocity[i] += this->dnodal_position_dt(l,i)*psi;
       }
     }
    double u_tangent = 0.0, t_length = 0.0;
    for(unsigned i=0;i<ndim;i++)
     {
      u_tangent += (interpolated_u[i] - mesh_velocity[i])*interpolated_tangent[i];
      t_length  += interpolated_tangent[i]*interpolated_tangent[i];
     }
    //Now we add the flux term to the appropriate residuals
    for(unsigned l=0;l<n_node;l++)
     {
      //Read out the apprporiate local equation
      local_eqn = this->nodal_local_eqn(l,c_index);
      //If not a boundary condition
      if(local_eqn >= 0)
       {
        //Time derivative term
        residuals[local_eqn] -= PeSt_s*dCdt*psif(l)*W*J;
        //Diffusion term
        residuals[local_eqn] -= interpolated_dCds*dpsifds(l,0)*W/J;
        //Advection term in new formulation
        residuals[local_eqn] -=
         Pe_s*(u_tangent*interpolated_dCds +
               interpolated_C*
               (interpolated_tangent[0]*interpolated_duds[0]
                + interpolated_tangent[1]*interpolated_duds[1]))*psif(l)*W/J;
        //We also need to worry about the jacobian terms
        if(flag)
         {
          //Loop over the nodes again
          for(unsigned l2=0;l2<n_node;l2++)
           {
            //Loop over the velocity components
            for(unsigned i2=0;i2<ndim;i2++)
             {
              //Get the unknown
              local_unknown = this->nodal_local_eqn(l2,u_index[i2]);
              //If not a boundary condition
              if(local_unknown >= 0)
               {
                jacobian(local_eqn,local_unknown)
                 -= Pe_s*interpolated_tangent[i2]*
                 (psif(l2)*interpolated_dCds +
                  interpolated_C*dpsifds(l2,0))*psif(l)*W/J;
               }
             }
           }
         }
       }
     } //End of loop over the nodes
   }
References Global_Physical_Variables::Bi, i, J, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Global_Physical_Variables::Pe_s, and oomph::QuadTreeNames::W.
add_additional_residual_contributions_interface() [2/2]
template<class ELEMENT > void oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::add_additional_residual_contributions_interface (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag, const Shape & psif, const DShape & dpsifds, const DShape & dpsifdS, const DShape & dpsifds_div, const Vector< double > & s, const Vector< double > & interpolated_x, const Vector< double > & interpolated_n, const double & W, const double & J) inline protected virtual
Overload the Helper function to calculate the residuals and jacobian entries. This particular function ensures that the additional entries are calculated inside the integration loop
Reimplemented from oomph::FluidInterfaceElement.
   {
    //Find the index at which the temperature is stored
    unsigned t_index = this->T_index;
    //Find out how many nodes there are
    unsigned n_node = this->nnode();
    //Read out the Bi number
    const double Bi = this->bi();
    //Now calculate the temperature at this point
    //Assuming the same shape functions are used (which they are)
    double T = 0.0;
    for(unsigned l=0;l<n_node;l++)
     {
      T += this->nodal_value(l,t_index)*psif(l);
     }
    //Storage for the local equation numbers and unknowns
    int local_eqn = 0, local_unknown = 0;
    //Now we add the flux term to the appropriate residuals
    for(unsigned l=0;l<n_node;l++)
     {
      //Read out the apprporiate local equation
      local_eqn = this->nodal_local_eqn(l,t_index);
      //If not a boundary condition
      if(local_eqn >= 0)
       {
        residuals[local_eqn] -= (1.0 + Bi*(T-1.0))*psif(l)*W*J;
        //We also need to worry about the jacobian terms
        if(flag)
         {
          //Loop over the nodes again
          for(unsigned l2=0;l2<n_node;l2++)
           {
            //Get the unknown
            local_unknown = this->nodal_local_eqn(l2,t_index);
            //If not a boundary condition
            if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) -= Bi*psif(l2)*psif(l)*W*J;
             }
           }
         }
       }
     } //End of loop over the nodes
    //Bulk flux condition
    //Find the index at which the bulk is stored
    unsigned c_bulk_index = this->C_bulk_index;
    //Find the index at which the surface surfactant
    unsigned c_index = this->C_index;
    //Now calculate the bulk concentration at this point
    //Assuming the same shape functions are used (which they are)
    double C_bulk = 0.0;
    double C = 0.0;
    for(unsigned l=0;l<n_node;l++)
     {
      C_bulk += this->nodal_value(l,c_bulk_index)*psif(l);
      C += this->nodal_value(l,c_index)*psif(l);
     }
    //Get the reaction ratio
    const double K = this->k();
    //The transport between the two layers is given by the flux
    double flux = K*C_bulk - C;
    //Now we add the flux term to the appropriate residuals
    for(unsigned l=0;l<n_node;l++)
     {
      //Read out the apprporiate local equation
      local_eqn = this->nodal_local_eqn(l,c_bulk_index);
      //If not a boundary condition
      if(local_eqn >= 0)
       {
        residuals[local_eqn] -= flux*psif(l)*W*J;
        //We also need to worry about the jacobian terms
        if(flag)
         {
          //Loop over the nodes again
          for(unsigned l2=0;l2<n_node;l2++)
           {
            //Get the unknown
            local_unknown = this->nodal_local_eqn(l2,c_bulk_index);
            //If not a boundary condition
            if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) -= K*psif(l2)*psif(l)*W*J;
             }
            local_unknown = this->nodal_local_eqn(l2,c_index);
            //If not a boundary condition
            if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) += psif(l2)*psif(l)*W*J;
             }
           }
         }
       }
     } //End of loop over the nodes
    //Surface advection-diffusion equation
    //Get the diffusion ratio
    const double D = d();
     //Find the index at which the temperature is stored
    //unsigned c_index = this->C_index;
    Vector<unsigned> u_index = this->U_index_interface;
    //Read out the surface peclect number
    const double Pe_s = this->peclet_s();
    const double PeSt_s = this->peclet_strouhal_s();
    //Now calculate the concentration at this point
    //Assuming the same shape functions are used (which they are)
    double interpolated_C = 0.0;
    double interpolated_dCds = 0.0;
    double dCdt = 0.0;
    //The tangent vector
    const unsigned ndim = this->node_pt(0)->ndim();
    Vector<double> interpolated_tangent(ndim,0.0);
    Vector<double> interpolated_u(ndim,0.0);
    Vector<double> interpolated_duds(ndim,0.0);
    Vector<double> mesh_velocity(ndim,0.0);
    if(ndim != u_index.size())
     {
      throw OomphLibError("Dimension Incompatibility",
                          OOMPH_CURRENT_FUNCTION,
                          OOMPH_EXCEPTION_LOCATION);
     }
    for(unsigned l=0;l<n_node;l++)
     {
      const double psi = psif(l);
      const double dpsi = dpsifds(l,0);
      interpolated_C += this->nodal_value(l,c_index)*psi;
      interpolated_dCds += this->nodal_value(l,c_index)*dpsi;
      dCdt += dcdt_surface(l)*psi;
      for(unsigned i=0;i<ndim;i++)
       {
        interpolated_tangent[i] += this->nodal_position(l,i)*dpsi;
        interpolated_u[i] += this->nodal_value(l,u_index[i])*psi;
        interpolated_duds[i] += this->nodal_value(l,u_index[i])*dpsi;
        mesh_velocity[i] += this->dnodal_position_dt(l,i)*psif(l);
       }
     }
    double u_tangent = 0.0, t_length = 0.0;
    for(unsigned i=0;i<ndim;i++)
     {
      u_tangent +=
       (interpolated_u[i] - mesh_velocity[i])*interpolated_tangent[i];
      t_length  += interpolated_tangent[i]*interpolated_tangent[i];
     }
    //Now we add the flux term to the appropriate residuals
    for(unsigned l=0;l<n_node;l++)
     {
      //Read out the apprporiate local equation
      local_eqn = this->nodal_local_eqn(l,c_index);
      //If not a boundary condition
      if(local_eqn >= 0)
       {
        //Time derivative term
        residuals[local_eqn] -= PeSt_s*dCdt*psif(l)*W*J;
        //Diffusion term
        residuals[local_eqn] -= interpolated_dCds*dpsifds(l,0)*W/J;
        //Advection term in new formulation
        residuals[local_eqn] -=
         Pe_s*(u_tangent*interpolated_dCds +
               interpolated_C*
               (interpolated_tangent[0]*interpolated_duds[0]
                + interpolated_tangent[1]*interpolated_duds[1]))*psif(l)*W/J;
        //Now add the flux term
        residuals[local_eqn] += D*flux*psif(l)*W*J;
        //We also need to worry about the jacobian terms
        if(flag)
         {
          //Loop over the nodes again
          for(unsigned l2=0;l2<n_node;l2++)
           {
            //Loop over the velocity components
            for(unsigned i2=0;i2<ndim;i2++)
             {
              //Get the unknown
              local_unknown = this->nodal_local_eqn(l2,u_index[i2]);
              //If not a boundary condition
              if(local_unknown >= 0)
               {
                jacobian(local_eqn,local_unknown)
                 -= Pe_s*interpolated_tangent[i2]*
                 (psif(l2)*interpolated_dCds +
                  interpolated_C*dpsifds(l2,0))*psif(l)*W/J;
               }
             }
            //Get the unknown
            local_unknown = this->nodal_local_eqn(l2,c_bulk_index);
            //If not a boundary condition
            if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) += D*K*psif(l2)*psif(l)*W*J;
             }
            local_unknown = this->nodal_local_eqn(l2,c_index);
            //If not a boundary condition
            if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) -= D*psif(l2)*psif(l)*W*J;
             }
           }
         }
       }
     } //End of loop over the nodes
   }
References Global_Physical_Variables::Bi, Global_Physical_Variables::D, ProblemParameters::flux(), i, J, k, PlanarWave::K, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Global_Physical_Variables::Pe_s, and oomph::QuadTreeNames::W.
beta() [1/2]
template<class ELEMENT > double oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::beta () inline
Return the Elasticity number.
 {return *Beta_pt;}
beta() [2/2]
template<class ELEMENT > double oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::beta () inline
Return the Elasticity number.
 {return *Beta_pt;}
beta_pt() [1/2]
template<class ELEMENT > double* & oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::beta_pt () inline
Access function for pointer to the Elasticity number.
 {return Beta_pt;}
beta_pt() [2/2]
template<class ELEMENT > double* & oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::beta_pt () inline
Access function for pointer to the Elasticity number.
 {return Beta_pt;}
bi() [1/2]
template<class ELEMENT > double oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::bi () inline
Return the Biot number.
 {return *Bi_pt;}
bi() [2/2]
template<class ELEMENT > double oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::bi () inline
Return the Biot number.
 {return *Bi_pt;}
bi_pt() [1/2]
template<class ELEMENT > double* & oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::bi_pt () inline
Access function for pointer to the Biot number.
 {return Bi_pt;}
bi_pt() [2/2]
template<class ELEMENT > double* & oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::bi_pt () inline
Access function for pointer to the Biot number.
 {return Bi_pt;}
d()
template<class ELEMENT > double oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::d () inline
Return the diffusion ratio.
 {return *D_pt;}
d_pt()
template<class ELEMENT > double* & oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::d_pt () inline
Access function for pointer to the diffusion ratios.
 {return D_pt;}
dcdt_surface() [1/2]
template<class ELEMENT > double oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::dcdt_surface (const unsigned & l) const inline protected
The time derivative of the surface concentration.
   {
    // Get the data's timestepper
    TimeStepper* time_stepper_pt= this->node_pt(l)->time_stepper_pt();
    //Initialise dudt
    double dcdt=0.0;
    //Loop over the timesteps, if there is a non Steady timestepper
    if (time_stepper_pt->type()!="Steady")
     {
      //Find the index at which the variable is stored
      const unsigned c_index = C_index;
      // Number of timsteps (past & present)
      const unsigned n_time = time_stepper_pt->ntstorage();
      for(unsigned t=0;t<n_time;t++)
       {
        dcdt += time_stepper_pt->weight(1,t)*this->nodal_value(t,l,c_index);
       }
     }
    return dcdt;
   }
References oomph::TimeStepper::ntstorage(), plotPSD::t, oomph::TimeStepper::type(), and oomph::TimeStepper::weight().
dcdt_surface() [2/2]
template<class ELEMENT > double oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::dcdt_surface (const unsigned & l) const inline protected
The time derivative of the surface concentration.
   {
    // Get the data's timestepper
    TimeStepper* time_stepper_pt= this->node_pt(l)->time_stepper_pt();
    //Initialise dudt
    double dcdt=0.0;
    //Loop over the timesteps, if there is a non Steady timestepper
    if (time_stepper_pt->type()!="Steady")
     {
      //Find the index at which the variable is stored
      const unsigned c_index = C_index;
      // Number of timsteps (past & present)
      const unsigned n_time = time_stepper_pt->ntstorage();
      for(unsigned t=0;t<n_time;t++)
       {
        dcdt += time_stepper_pt->weight(1,t)*this->nodal_value(t,l,c_index);
       }
     }
    return dcdt;
   }
References oomph::TimeStepper::ntstorage(), plotPSD::t, oomph::TimeStepper::type(), and oomph::TimeStepper::weight().
fill_in_contribution_to_jacobian() [1/2]
template<class ELEMENT > void oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline protected virtual
Calculate the contribution to the jacobian.
Fill in the contribution to the residuals
Reimplemented from oomph::GeneralisedElement.
   {
    //Call the generic routine with the flag set to 1
    this->fill_in_generic_residual_contribution_interface(residuals,jacobian,1);
    {
     //Use finite differences to handle temperature variations
     const unsigned n_node = this->nnode();
     //Find the number of dofs in the element
     const unsigned n_dof = this->ndof();
     //Create newres vector
     Vector<double> newres(n_dof);
     //Integer storage for local unknown
     int local_unknown=0;
     //Use the default finite difference step
     const double fd_step = this->Default_fd_jacobian_step;
     //Loop over the nodes
     for(unsigned n=0;n<n_node;n++)
      {
       //Get the number of values stored at the node
       unsigned t_index = this->T_index;
       //Get the local equation number
       local_unknown = this->nodal_local_eqn(n,t_index);
       //If it's not pinned
       if(local_unknown >= 0)
        {
         //Store a pointer to the nodal data value
         double *value_pt = this->node_pt(n)->value_pt(t_index);
         //Save the old value of the Nodal data
         double old_var = *value_pt;
         //Increment the value of the Nodal data
         *value_pt += fd_step;
         //Calculate the new residuals
         this->get_residuals(newres);
         //Do finite differences
         for(unsigned m=0;m<n_dof;m++)
          {
           double sum = (newres[m] - residuals[m])/fd_step;
           //Stick the entry into the Jacobian matrix
           jacobian(m,local_unknown) = sum;
          }
         //Reset the Nodal data
         *value_pt = old_var;
        }
      }
     //Use finite differences to handle the concentration variations
     //Loop over the nodes again
     for(unsigned n=0;n<n_node;n++)
      {
       //Get the number of values stored at the node
       unsigned c_index = this->C_index;
       //Get the local equation number
       local_unknown = this->nodal_local_eqn(n,c_index);
       //If it's not pinned
       if(local_unknown >= 0)
        {
         //Store a pointer to the nodal data value
         double *value_pt = this->node_pt(n)->value_pt(c_index);
         //Save the old value of the Nodal data
         double old_var = *value_pt;
         //Increment the value of the Nodal data
         *value_pt += fd_step;
         //Calculate the new residuals
         this->get_residuals(newres);
         //Do finite differences
         for(unsigned m=0;m<n_dof;m++)
          {
           double sum = (newres[m] - residuals[m])/fd_step;
           //Stick the entry into the Jacobian matrix
           jacobian(m,local_unknown) = sum;
          }
         //Reset the Nodal data
         *value_pt = old_var;
        }
      }
    }
    //Call the generic routine to handle the spine variables
    SpineElement<FaceGeometry<ELEMENT> >::
     fill_in_jacobian_from_geometric_data(jacobian);
   }
References GlobalFct::get_residuals(), m, and n.
fill_in_contribution_to_jacobian() [2/2]
template<class ELEMENT > void oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline protected virtual
Calculate the contribution to the jacobian.
Fill in the contribution to the residuals
Reimplemented from oomph::GeneralisedElement.
   {
    //Call the generic routine with the flag set to 1
    this->fill_in_generic_residual_contribution_interface(residuals,jacobian,1);
    {
     //Use finite differences to handle temperature variations
     const unsigned n_node = this->nnode();
     //Find the number of dofs in the element
     const unsigned n_dof = this->ndof();
     //Create newres vector
     Vector<double> newres(n_dof);
     //Integer storage for local unknown
     int local_unknown=0;
     //Use the default finite difference step
     const double fd_step = this->Default_fd_jacobian_step;
     //Loop over the nodes
     for(unsigned n=0;n<n_node;n++)
      {
       //Get the number of values stored at the node
       unsigned t_index = this->T_index;
       //Get the local equation number
       local_unknown = this->nodal_local_eqn(n,t_index);
       //If it's not pinned
       if(local_unknown >= 0)
        {
         //Store a pointer to the nodal data value
         double *value_pt = this->node_pt(n)->value_pt(t_index);
         //Save the old value of the Nodal data
         double old_var = *value_pt;
         //Increment the value of the Nodal data
         *value_pt += fd_step;
         //Calculate the new residuals
         this->get_residuals(newres);
         //Do finite differences
         for(unsigned m=0;m<n_dof;m++)
          {
           double sum = (newres[m] - residuals[m])/fd_step;
           //Stick the entry into the Jacobian matrix
           jacobian(m,local_unknown) = sum;
          }
         //Reset the Nodal data
         *value_pt = old_var;
        }
      }
     //Use finite differences to handle the concentration variations
     //Loop over the nodes again
     for(unsigned n=0;n<n_node;n++)
      {
       //Get the number of values stored at the node
       unsigned c_index = this->C_index;
       //Get the local equation number
       local_unknown = this->nodal_local_eqn(n,c_index);
       //If it's not pinned
       if(local_unknown >= 0)
        {
         //Store a pointer to the nodal data value
         double *value_pt = this->node_pt(n)->value_pt(c_index);
         //Save the old value of the Nodal data
         double old_var = *value_pt;
         //Increment the value of the Nodal data
         *value_pt += fd_step;
         //Calculate the new residuals
         this->get_residuals(newres);
         //Do finite differences
         for(unsigned m=0;m<n_dof;m++)
          {
           double sum = (newres[m] - residuals[m])/fd_step;
           //Stick the entry into the Jacobian matrix
           jacobian(m,local_unknown) = sum;
          }
         //Reset the Nodal data
         *value_pt = old_var;
        }
      }
    }
    //Call the generic routine to handle the spine variables
    SpineElement<FaceGeometry<ELEMENT> >::
     fill_in_jacobian_from_geometric_data(jacobian);
   }
References GlobalFct::get_residuals(), m, and n.
fill_in_contribution_to_jacobian_and_mass_matrix() [1/2]
template<class ELEMENT > void oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) inline protected virtual
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix
Reimplemented from oomph::GeneralisedElement.
   {
    //Add the contribution to the jacobian
    this->fill_in_contribution_to_jacobian(residuals,jacobian);
    //No mass matrix terms, but should probably do kinematic bit here
   }
References oomph::fill_in_contribution_to_jacobian().
fill_in_contribution_to_jacobian_and_mass_matrix() [2/2]
template<class ELEMENT > void oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) inline protected virtual
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix
Reimplemented from oomph::GeneralisedElement.
   {
    //Add the contribution to the jacobian
    this->fill_in_contribution_to_jacobian(residuals,jacobian);
    //No mass matrix terms, but should probably do kinematic bit here
   }
References oomph::fill_in_contribution_to_jacobian().
interpolated_C() [1/2]
template<class ELEMENT > double oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::interpolated_C (const Vector< double > & s) inline protected
Get the surfactant concentration.
   {
      //Find number of nodes
    unsigned n_node = this->nnode();
    //Get the nodal index at which the unknown is stored
    const unsigned c_index = C_index;
    //Local shape function
    Shape psi(n_node);
    //Find values of shape function
    this->shape(s,psi);
    //Initialise value of C
    double C = 0.0;
    //Loop over the local nodes and sum
    for(unsigned l=0;l<n_node;l++)
     {
      C += this->nodal_value(l,c_index)*psi(l);
     }
    return(C);
   }
References oomph::OneDimLagrange::shape().
interpolated_C() [2/2]
template<class ELEMENT > double oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::interpolated_C (const Vector< double > & s) inline protected
Get the surfactant concentration.
   {
      //Find number of nodes
    unsigned n_node = this->nnode();
    //Get the nodal index at which the unknown is stored
    const unsigned c_index = C_index;
    //Local shape function
    Shape psi(n_node);
    //Find values of shape function
    this->shape(s,psi);
    //Initialise value of C
    double C = 0.0;
    //Loop over the local nodes and sum
    for(unsigned l=0;l<n_node;l++)
     {
      C += this->nodal_value(l,c_index)*psi(l);
     }
    return(C);
   }
References oomph::OneDimLagrange::shape().
interpolated_T() [1/2]
template<class ELEMENT > double oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::interpolated_T (const Vector< double > & s) inline protected
Get the temperature.
   {
      //Find number of nodes
    unsigned n_node = this->nnode();
    //Get the nodal index at which the unknown is stored
    const unsigned t_index = T_index;
    //Local shape function
    Shape psi(n_node);
    //Find values of shape function
    this->shape(s,psi);
    //Initialise value of t
    double T = 0.0;
    //Loop over the local nodes and sum
    for(unsigned l=0;l<n_node;l++)
     {
      T += this->nodal_value(l,t_index)*psi(l);
     }
    return(T);
   }
References oomph::OneDimLagrange::shape().
interpolated_T() [2/2]
template<class ELEMENT > double oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::interpolated_T (const Vector< double > & s) inline protected
Get the temperature.
   {
      //Find number of nodes
    unsigned n_node = this->nnode();
    //Get the nodal index at which the unknown is stored
    const unsigned t_index = T_index;
    //Local shape function
    Shape psi(n_node);
    //Find values of shape function
    this->shape(s,psi);
    //Initialise value of t
    double T = 0.0;
    //Loop over the local nodes and sum
    for(unsigned l=0;l<n_node;l++)
     {
      T += this->nodal_value(l,t_index)*psi(l);
     }
    return(T);
   }
References oomph::OneDimLagrange::shape().
k()
template<class ELEMENT > double oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::k () inline
Return the reaction ratio.
 {return *K_pt;}
k_pt()
template<class ELEMENT > double* & oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::k_pt () inline
Access function for pointer to the reaction ratios.
 {return K_pt;}
ma() [1/2]
template<class ELEMENT > double oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::ma () inline
Return the Marangoni number.
 {return *Ma_pt;}
ma() [2/2]
template<class ELEMENT > double oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::ma () inline
Return the Marangoni number.
 {return *Ma_pt;}
ma_pt() [1/2]
template<class ELEMENT > double* & oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::ma_pt () inline
Access function for pointer to the Marangoni number.
 {return Ma_pt;}
ma_pt() [2/2]
template<class ELEMENT > double* & oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::ma_pt () inline
Access function for pointer to the Marangoni number.
 {return Ma_pt;}
output() [1/2]
template<class ELEMENT > void oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) inline virtual
Output the element data — pass (some measure of) the number of plot points per element
Reimplemented from oomph::FiniteElement.
 {
  //Set output Vector
  Vector<double> s(1);
  //Tecplot header info
  outfile << "ZONE I=" << n_plot << std::endl;
  //Loop over plot points
  for(unsigned l=0;l<n_plot;l++)
   {
    s[0] = -1.0 + l*2.0/(n_plot-1);
    //Output the x,y,u,v
    for(unsigned i=0;i<2;i++) outfile << this->interpolated_x(s,i) << " ";
    for(unsigned i=0;i<2;i++) outfile << this->interpolated_u(s,i) << " ";
    //Output a dummy pressure
    outfile << 0.0 << " ";
    //Output the temperature
    outfile << interpolated_T(s) << " "
            << interpolated_C(s) << std::endl;
   }
  outfile << std::endl;
 }
References i, and s.
output() [2/2]
template<class ELEMENT > void oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) inline virtual
Output the element data — pass (some measure of) the number of plot points per element
Reimplemented from oomph::FiniteElement.
 {
  //Set output Vector
  Vector<double> s(1);
  //Tecplot header info
  outfile << "ZONE I=" << n_plot << std::endl;
  //Loop over plot points
  for(unsigned l=0;l<n_plot;l++)
   {
    s[0] = -1.0 + l*2.0/(n_plot-1);
    //Output the x,y,u,v
    for(unsigned i=0;i<2;i++) outfile << this->interpolated_x(s,i) << " ";
    for(unsigned i=0;i<2;i++) outfile << this->interpolated_u(s,i) << " ";
    //Output a dummy pressure
    outfile << 0.0 << " ";
    //Output the temperature
    outfile << interpolated_T(s) << " "
            << interpolated_C(s) << std::endl;
   }
  outfile << std::endl;
 }
References i, and s.
peclet_s() [1/2]
template<class ELEMENT > double oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::peclet_s () inline
Return the surface peclect number.
 {return *Peclet_S_pt;}
peclet_s() [2/2]
template<class ELEMENT > double oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::peclet_s () inline
Return the surface peclect number.
 {return *Peclet_S_pt;}
peclet_s_pt() [1/2]
template<class ELEMENT > double* & oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::peclet_s_pt () inline
Access function for pointer to the surface Peclet number.
 {return Peclet_S_pt;}
peclet_s_pt() [2/2]
template<class ELEMENT > double* & oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::peclet_s_pt () inline
Access function for pointer to the surface Peclet number.
 {return Peclet_S_pt;}
peclet_strouhal_s() [1/2]
template<class ELEMENT > double oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::peclet_strouhal_s () inline
Return the surface peclect strouhal number.
 {return *Peclet_Strouhal_S_pt;}
peclet_strouhal_s() [2/2]
template<class ELEMENT > double oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::peclet_strouhal_s () inline
Return the surface peclect strouhal number.
 {return *Peclet_Strouhal_S_pt;}
peclet_strouhal_s_pt() [1/2]
template<class ELEMENT > double* & oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::peclet_strouhal_s_pt () inline
Access function for pointer to the surface Peclet x Strouhal number.
 {return Peclet_Strouhal_S_pt;}
peclet_strouhal_s_pt() [2/2]
template<class ELEMENT > double* & oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::peclet_strouhal_s_pt () inline
Access function for pointer to the surface Peclet x Strouhal number.
 {return Peclet_Strouhal_S_pt;}
sigma() [1/2]
template<class ELEMENT > double oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::sigma (const Vector< double > & s) inline protected virtual
The surface tension function is linear in the temperature with constant of proportionality equal to the Marangoni number.
Reimplemented from oomph::FluidInterfaceElement.
   {
    //Find the number of shape functions
    const unsigned n_node = this->nnode();
    //Now get the shape fuctions at the local coordinate
    Shape psi(n_node);
    this->shape(s,psi);
    //Now interpolate the temperature and surfactant concentration
    double T = 0.0, C=0.0;
    for(unsigned l=0;l<n_node;l++)
     {
      T += this->nodal_value(l,T_index)*psi(l);
      C += this->nodal_value(l,C_index)*psi(l);
     }
    //Get the Marangoni, Capillary and Elasticity numbers
    double Ma = this->ma();
    double Ca = this->ca();
    double Beta = this->beta();
    //Return the variable surface tension
    //The additional multiplication by Ca will cancel with the 1/Ca
    //in the underlying equations
    return (1.0 - Ca*Ma*T - Ca*Beta*(C-1.0));
   }
References beta, Global_Physical_Variables::Beta, Global_Physical_Variables::Ca, oomph::Global_Physical_Variables::Ma, and oomph::OneDimLagrange::shape().
sigma() [2/2]
template<class ELEMENT > double oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::sigma (const Vector< double > & s) inline protected virtual
The surface tension function is linear in the temperature with constant of proportionality equal to the Marangoni number.
Reimplemented from oomph::FluidInterfaceElement.
   {
    //Find the number of shape functions
    const unsigned n_node = this->nnode();
    //Now get the shape fuctions at the local coordinate
    Shape psi(n_node);
    this->shape(s,psi);
    //Now interpolate the temperature and surfactant concentration
    double T = 0.0, C=0.0;
    for(unsigned l=0;l<n_node;l++)
     {
      T += this->nodal_value(l,T_index)*psi(l);
      C += this->nodal_value(l,C_index)*psi(l);
     }
    //Get the Marangoni, Capillary and Elasticity numbers
    double Ma = this->ma();
    double Ca = this->ca();
    double Beta = this->beta();
    //Return the variable surface tension
    //The additional multiplication by Ca will cancel with the 1/Ca
    //in the underlying equations
    return (1.0 - Ca*Ma*T - Ca*Beta*(C-1.0));
   }
References beta, Global::Beta, Global_Physical_Variables::Ca, oomph::Global_Physical_Variables::Ma, and oomph::OneDimLagrange::shape().
Member Data Documentation
Beta_pt
template<class ELEMENT > double * oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::Beta_pt private
Pointer to an Elasticity number.
Bi_pt
template<class ELEMENT > double * oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::Bi_pt private
Pointer to a Biot number.
C_bulk_index
template<class ELEMENT > unsigned oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::C_bulk_index private
Index at which the bulk concentration is stored at the nodes.
C_index
template<class ELEMENT > unsigned oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::C_index private
Index at which the surfactant concentration is stored at the nodes
D_pt
template<class ELEMENT > double* oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::D_pt private
Pointer to the diffusion ratios.
Default_Physical_Constant_Value
template<class ELEMENT > double oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::Default_Physical_Constant_Value = 1.0 static private
Default value of the physical constants.
K_pt
template<class ELEMENT > double* oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::K_pt private
Pointer to the reaction ratios.
Ma_pt
template<class ELEMENT > double * oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::Ma_pt private
Pointer to a Marangoni number.
Peclet_S_pt
template<class ELEMENT > double * oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::Peclet_S_pt private
Pointer to Surface Peclet number.
Peclet_Strouhal_S_pt
template<class ELEMENT > double * oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::Peclet_Strouhal_S_pt private
Pointer to the surface Peclect Strouhal number.
T_index
template<class ELEMENT > unsigned oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::T_index private
Index at which the temperature is stored at the nodes.
The documentation for this class was generated from the following files:
surfactant.cc
soluble_surfactant.cc