MercuryDPM: ChargedBondedInteraction Class Reference
ChargedBondedInteraction Class Reference
#include <ChargedBondedInteraction.h>
Public Types
typedef ChargedBondedSpecies SpeciesType
Setting an alias name for ChargedBondedSpecies.
Public Member Functions
ChargedBondedInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
Constructor.
ChargedBondedInteraction (const ChargedBondedInteraction &p)
Copy constructor.
ChargedBondedInteraction ()
~ChargedBondedInteraction () override
Destructor.
void computeAdhesionForce ()
Computes the adhesive forces.
void read (std::istream &is) override
Interaction read function, which accepts an std::istream as input.
void write (std::ostream &os) const override
Interaction print function, which accepts an std::ostream as input.
Mdouble getElasticEnergy () const override
Returns the amount of Elastic energy involved in an interaction. Basically used in case you want to write the elastic energy into an output file.
const ChargedBondedSpecies * getSpecies () const
Returns a pointer to the adhesive force species ChargedBondedSpecies.
std::string getBaseName () const
Returns the name of the interaction, see Interaction.h.
void bond ()
A pair of functions which can be used to fix or unfix a pair of overlapping particles.
void unbond ()
bool isBonded () const override
Public Member Functions inherited from BaseInteraction
BaseInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
A constructor takes the BaseInteractable objects which are interacting (come into contact) and time the interaction starts.
BaseInteraction ()
BaseInteraction (const BaseInteraction &p)
Copy constructor.
~BaseInteraction () override
The destructor. It removes this interactions from the objects that were interacting, and writes the time to a file when needed.
virtual void actionsOnErase ()
If an interaction needs to do something before it gets erased, add it here. E.g. Liquid bridges rupture at the end of their lifetime, and the liquid bridge volume has to be redistributed. The reason this action is not done in the destructor is that this action should not be taken when erasing ghost interactions.
virtual void computeForce ()
Virtual function that contains the force law between the two objects interacting.
void read (std::istream &is) override
Interaction read function, which accepts an std::istream as input.
void write (std::ostream &os) const override
Interaction print function, which accepts an std::ostream as input.
void writeToFStat (std::ostream &os, Mdouble time) const
Writes forces data to the FStat file.
std::string getName () const override
Virtual function which allows interactions to be named.
void setDistance (Mdouble distance)
Sets the interaction distance between the two interacting objects.
void setNormal (Vec3D normal)
Sets the normal vector between the two interacting objects.
void setOverlap (Mdouble overlap)
Set the overlap between the two interacting object.
void setContactPoint (Vec3D contactPoint)
Set the location of the contact point between the two interacting objects.
void setTimeStamp (unsigned timeStamp)
Updates the time step of the interacting. Note, time steps used to find completed interactions.
void setSpecies (const BaseSpecies *species)
Set the Species of the interaction; note this can either be a Species or MixedSpecies.
void setP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void setI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
void importP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void importI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
Vec3D getIP () const
Vec3D getIC () const
Vec3D getCP () const
void setLagrangeMultiplier (Mdouble multiplier)
Mdouble getLagrangeMultiplier ()
void setHandler (InteractionHandler *handler)
Sets the pointer to the interaction hander which is storing this interaction.
InteractionHandler * getHandler () const
Gets a point to the interaction handlers to which this interaction belongs.
const Vec3D & getForce () const
Gets the current force (vector) between the two interacting objects.
const Vec3D & getTorque () const
Gets the current torque (vector) between the two interacting objects.
const Vec3D & getNormal () const
Gets the normal vector between the two interacting objects.
const Vec3D & getContactPoint () const
Gets constant reference to contact point (vector).
Mdouble getOverlap () const
Returns a Mdouble with the current overlap between the two interacting objects.
Mdouble getOverlapVolume () const
Returns the overlap volume between two interacting objects.
Mdouble getContactRadius () const
Returns a Mdouble with the current contact between the two interacting objects.
void removeFromHandler ()
Removes this interaction from its interaction hander.
void copySwitchPointer (const BaseInteractable *original, BaseInteractable *ghost) const
This copies the interactions of the original particle and replaces the original with the ghost copy.
void gatherContactStatistics ()
BaseInteractable * getP ()
Returns a pointer to first object involved in the interaction (normally a particle).
BaseInteractable * getI ()
Returns a pointer to the second object involved in the interaction (often a wall or a particle).
const BaseInteractable * getP () const
Returns a constant pointer to the first object involved in the interaction.
const BaseInteractable * getI () const
Returns a constant pointer to the second object involved in the interaction.
Mdouble getTimeStamp () const
Returns an Mdouble which is the time stamp of the interaction.
virtual void integrate (Mdouble timeStep)
integrates variables of the interaction which need to be integrate e.g. the tangential overlap.
virtual Mdouble getTangentialOverlap () const
get the length of the current tangential overlap
Mdouble getDistance () const
Returns an Mdouble which is the norm (length) of distance vector.
const Vec3D & getRelativeVelocity () const
Returns a constant reference to a vector of relative velocity.
Mdouble getNormalRelativeVelocity () const
Returns a double which is the norm (length) of the relative velocity vector.
Mdouble getAbsoluteNormalForce () const
Returns the absolute value of the norm (length) of the Normal force vector.
virtual BaseInteraction * copy () const =0
Makes a copy of the interaction and returns a pointer to the copy.
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseWall *I)
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseParticle *I)
unsigned int getMultiContactIdentifier () const
void setMultiContactIdentifier (unsigned int multiContactIdentifier_)
virtual void rotateHistory (Matrix3D &rotationMatrix)
When periodic particles are used, some interactions need certain history properties rotated (e.g. tangential springs). This is the function for that.
virtual void actionsAfterTimeStep ()
virtual unsigned getNumberOfFieldsVTK () const
virtual std::string getTypeVTK (unsigned i) const
virtual std::string getNameVTK (unsigned i) const
virtual std::vector< Mdouble > getFieldVTK (unsigned i) const
void addForce (Vec3D force)
add an force increment to the total force.
void addTorque (Vec3D torque)
add a torque increment to the total torque.
void setForce (Vec3D force)
set total force (this is used by the normal force, tangential forces are added use addForce)
void setTorque (Vec3D torque)
set the total force (this is used by the normal force, tangential torques are added use addTorque)
const BaseSpecies * getBaseSpecies () const
Return a constant point to BaseSpecies of the interaction.
virtual void createMPIType ()
virtual void * createMPIInteractionDataArray (unsigned int numberOfInteractions) const
virtual void deleteMPIInteractionDataArray (void *dataArray)
virtual void getMPIInteraction (void *historyDataArray, unsigned int index) const
copies the history interactions into the data array
virtual void getInteractionDetails (void *interactionDataArray, unsigned int index, unsigned int &identificationP, unsigned int &identificationI, bool &isWallInteraction, unsigned &timeStamp)
virtual void setMPIInteraction (void *interactionDataArray, unsigned int index, bool resetPointers)
void setBasicMPIInteractionValues (int P, int I, unsigned timeStamp, Vec3D force, Vec3D torque, bool isWallInteraction, bool resetPointers)
void setIdentificationP (unsigned int identification)
void setIdentificationI (int identification)
void setWallInteraction (bool flag)
unsigned int getIdentificationP ()
int getIdentificationI ()
bool isWallInteraction ()
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
bool bonded_
A history parameter to store if the particles were in contact or not. Useful to compute adhesive forces. Setting bonded_ to 'true' for a given pair of (overlapping) particles will cause these particles to become fixed together, resulting in larger, composite particles that can be used to model aspherical geometries.
Additional Inherited Members
Protected Member Functions inherited from BaseInteraction
virtual const Vec3D getTangentialForce () const
Mdouble getEffectiveRadius () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
Mdouble getEffectiveMass () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
void setRelativeVelocity (Vec3D relativeVelocity)
set the relative velocity of the current of the interactions.
void setNormalRelativeVelocity (Mdouble normalRelativeVelocit)
set the normal component of the relative velocity.
void setAbsoluteNormalForce (Mdouble absoluteNormalForce)
the absolute values of the norm (length) of the normal force
virtual Mdouble getElasticEnergyAtEquilibrium (Mdouble adhesiveForce) const
virtual void reverseHistory ()
When periodic particles some interaction need certain history properties reversing. This is the function for that.
void writeInteraction (std::ostream &os, bool created) const
Writes information about a interaction to the interaction file.
Member Typedef Documentation
SpeciesType
typedef ChargedBondedSpecies ChargedBondedInteraction::SpeciesType
Setting an alias name for ChargedBondedSpecies.
Constructor & Destructor Documentation
ChargedBondedInteraction() [1/3]
ChargedBondedInteraction::ChargedBondedInteraction (BaseInteractable * P, BaseInteractable * I, unsigned timeStamp)
Constructor.
Todo:
Clean up this file by using the logger instead of cout, //cout, cerr and assert, and by motivating why the commented out code needs to be here.
Complete the documentation of these methods
Parameters
[in] P
[in] I
[in] timeStamp
         : BaseInteraction(P, I, timeStamp)
 {
     //ensuring that, by default, particles are not 'bonded'
     //i.e. they will not unintentionally 'stick' to any overlapping particles!
     bonded_ = false;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"ChargedBondedInteraction::ChargedBondedInteraction() finished"<<std::endl;
 #endif
 }
References bonded_.
ChargedBondedInteraction() [2/3]
ChargedBondedInteraction::ChargedBondedInteraction (const ChargedBondedInteraction & p)
Copy constructor.
Parameters
[in] p
         : BaseInteraction(p)
 {
     //carrying the history parameter over for copied particles to ensure that any bonded particles
     //remain bonded!
     bonded_ = p.bonded_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"ChargedBondedInteraction::ChargedBondedInteraction(const ChargedBondedInteraction &p finished"<<std::endl;
 #endif
 }
References bonded_, and p.
ChargedBondedInteraction() [3/3]
ChargedBondedInteraction::ChargedBondedInteraction ()
Todo:
MX: add to MPI
 {
 #ifdef MERCURYDPM_USE_MPI
     logger(FATAL,"ChargedBondedInteractions are currently not implemented in parallel MercuryDPM");
 #endif
 }
References FATAL, and logger.
~ChargedBondedInteraction()
ChargedBondedInteraction::~ChargedBondedInteraction () override
Destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"ChargedBondedInteraction::ChargedBondedInteractionaction() finished"<<std::endl;
 #endif
 }
Member Function Documentation
bond()
void ChargedBondedInteraction::bond ()
A pair of functions which can be used to fix or unfix a pair of overlapping particles.
Used to set the private variable 'bonded' to true, thus allowing the user to choose to fix a given pair of interacting, overlapping particles together
 {
     bonded_ = true;
 }
References bonded_.
Referenced by ChargedBondedInteractionSelfTest::setupInitialConditions(), and ChargedBondedParticleUnitTest::setupInitialConditions().
computeAdhesionForce()
void ChargedBondedInteraction::computeAdhesionForce ()
Computes the adhesive forces.
TW: I added the vdW force; KW, why was that force not active? Note, this change also shows up in energy
 {
     const ChargedBondedSpecies* species = getSpecies();
     //std::cout << getSpecies()->getCharge() << std::endl;
     //creating local parameters to store the charges of both particles
     //involved in the interaction to allow for quick calculation
     const auto pSpecies = dynamic_cast<const ChargedBondedSpecies*>(getP()->getSpecies());
     const auto iSpecies = dynamic_cast<const ChargedBondedSpecies*>(getI()->getSpecies());
     logger.assert_debug(pSpecies,"No ChargedBondedSpecies");
     logger.assert_debug(iSpecies,"No ChargedBondedSpecies");
     const int pCharge = pSpecies->getCharge();
     const int iCharge = iSpecies->getCharge();
     //similarly, creating local parameters to store the relevant stiffness
     //and max force values
     const Mdouble k = species->getAdhesionStiffness();
     const Mdouble fMax = species->getAdhesionForceMax();
     const Mdouble kWaals = species->getVanDerWaalsStiffness();
     const Mdouble fMaxWaals = species->getVanDerWaalsForceMax();
     const Mdouble rWaals = fMaxWaals / kWaals;
     //First, adding bonded force if applicable
     if (bonded_ && getOverlap() >= 0)
     {
         addForce(getNormal() * (-species->getBondForceMax()
                                 - species->getBondDissipation() * getNormalRelativeVelocity()));
         return;
     }
     //determining which of the three possible cases for force based on charge -
     //repulsive (like charges), attractive (unlike charges) or none (1 or more uncharged) -
     //is relevant for the current combination of particle charges...
     //(Note that the charge set function contains a safety check that means charge can only be
     // +/- 1, i.e. the expressions used below should not produce errors!
     //case 1 - 1 or more particles has no charge, i.e. no EM force between them
     if ((pCharge == 0) or (iCharge == 0))
     {
         //No need to write anything here as nothing needs to be returned!
         //std::cout << "no charge" << std::endl;
     }
         //case 2: unlike charges --> attractive force
     else if (pCharge == -iCharge)
     {
         //std::cout << "dissimilar charge" << std::endl;
         //in the case of particles with opposing charges, simply implements the
         //standard attractive force used for adhesive particle interactions
         if (getOverlap() >= 0)
         {
             addForce(getNormal() * -fMax);
             addForce(getNormal() * -fMaxWaals);
         }
         else if (getOverlap() >= -rWaals)
         {
             addForce(getNormal() * (-kWaals * getOverlap() - fMaxWaals));
             addForce(getNormal() * (-k * getOverlap() - fMax));
         }
         else
         {
             addForce(getNormal() * (-k * getOverlap() - fMax));
         }
     }
         //case 3: like charges --> repulsive force
     else if (pCharge == iCharge)
     {
         //std::cout << "similar charge" << std::endl;
         //in the case of particles with like charges, reverse the direction of the force applied
         //such that particles repel one another
         if (getOverlap() >= 0)
         {
             addForce(getNormal() * +fMax);
             addForce(getNormal() * -fMaxWaals);
         }
         else if (getOverlap() >= -rWaals)
         {
             addForce(getNormal() * (-kWaals * getOverlap() - fMaxWaals));
             addForce(getNormal() * (+k * getOverlap() + fMax));
             //std::cout << "Waals = " << getNormal() * (-kWaals * getOverlap() - fMaxWaals) << std::endl;
         }
         else
         {
             addForce(getNormal() * (+k * getOverlap() + fMax));
         }
     }
         //if none of the above are satisfied, something must have gone very wrong!
     else
     {
         logger(ERROR, "Particle charge has erroneous value");
     }
 }
References BaseInteraction::addForce(), bonded_, ERROR, ChargedBondedSpecies::getAdhesionForceMax(), ChargedBondedSpecies::getAdhesionStiffness(), ChargedBondedSpecies::getBondDissipation(), ChargedBondedSpecies::getBondForceMax(), BaseInteraction::getI(), BaseInteraction::getNormal(), BaseInteraction::getNormalRelativeVelocity(), BaseInteraction::getOverlap(), BaseInteraction::getP(), BaseInteractable::getSpecies(), getSpecies(), ChargedBondedSpecies::getVanDerWaalsForceMax(), ChargedBondedSpecies::getVanDerWaalsStiffness(), k, and logger.
getBaseName()
std::string ChargedBondedInteraction::getBaseName () const
Returns the name of the interaction, see Interaction.h.
Returns
std::string
 {
     return "ChargedBonded";
 }
getElasticEnergy()
Mdouble ChargedBondedInteraction::getElasticEnergy () const override virtual
Returns the amount of Elastic energy involved in an interaction. Basically used in case you want to write the elastic energy into an output file.
Returns the elastic energy stored in the adhesive spring.
Elastic (=potential) energy is defined as the energy gained by separating two interactables. As it costs energy to separate adhesive interactables, the elastic energy is negative.
Returns
the elastic energy stored in the adhesive spring.
Reimplemented from BaseInteraction.
 {
     const ChargedBondedSpecies* species = getSpecies();
     const auto pSpecies = static_cast<const ChargedBondedSpecies*>(getP()->getSpecies()->getAdhesiveForce());
     const auto iSpecies = static_cast<const ChargedBondedSpecies*>(getI()->getSpecies()->getAdhesiveForce());
     logger.assert_debug(pSpecies,"No ChargedBondedSpecies");
     logger.assert_debug(iSpecies,"No ChargedBondedSpecies");
     const int pCharge = pSpecies->getCharge();
     const int iCharge = iSpecies->getCharge();
     const Mdouble k = species->getAdhesionStiffness();
     const Mdouble fMax = species->getAdhesionForceMax();
     const Mdouble r = getBaseSpecies()->getInteractionDistance();
     const Mdouble kWaals = species->getVanDerWaalsStiffness();
     const Mdouble fMaxWaals = species->getVanDerWaalsForceMax();
     const Mdouble rWaals = (fMaxWaals == 0) ? 0 : (fMaxWaals / kWaals);
     //First, adding bonded force if applicable
     if (bonded_ && getOverlap() >= 0)
     {
         //comment to ignore BondForce
         Mdouble elasticEnergyAtEquilibrium = getElasticEnergyAtEquilibrium(species->getBondForceMax());
         return -species->getBondForceMax() * getOverlap() + elasticEnergyAtEquilibrium;
     }
     Mdouble elasticEnergy = 0.0;
     if ((pCharge != 0) && (iCharge != 0))
     {
         if (pCharge == -iCharge)
         {
             if (getOverlap() >= 0)
             {
                 elasticEnergy -= (0.5 * rWaals + getOverlap()) * fMaxWaals
                                  + (0.5 * r + getOverlap()) * fMax;
             }
             else if (getOverlap() >= -rWaals)
             {
                 elasticEnergy -= (0.5 * kWaals * mathsFunc::square(getOverlap() + rWaals)) +
                                  (0.5 * k * mathsFunc::square(getOverlap() + r));
             }
             else
             {
                 elasticEnergy -= (0.5 * k * mathsFunc::square(getOverlap() + r));
             }
         }
             //case 3: like charges --> repulsive force
         else if (pCharge == iCharge)
         {
             if (getOverlap() >= 0)
             {
                 elasticEnergy -= (0.5 * rWaals + getOverlap()) * fMaxWaals
                                  - (0.5 * r + getOverlap()) * fMax;
             }
             else if (getOverlap() >= -rWaals)
             {
                 elasticEnergy -= (0.5 * kWaals * mathsFunc::square(getOverlap() + rWaals)) -
                                  (0.5 * k * mathsFunc::square(getOverlap() + r));
             }
             else
             {
                 elasticEnergy += (0.5 * k * mathsFunc::square(getOverlap() + r));
             }
         }
         else
         {
             logger(ERROR, "Particle charge has erroneous value");
         }
     }
     return elasticEnergy;
 }
References bonded_, ERROR, ChargedBondedSpecies::getAdhesionForceMax(), ChargedBondedSpecies::getAdhesionStiffness(), BaseSpecies::getAdhesiveForce(), BaseInteraction::getBaseSpecies(), ChargedBondedSpecies::getBondForceMax(), BaseInteraction::getElasticEnergyAtEquilibrium(), BaseInteraction::getI(), BaseSpecies::getInteractionDistance(), BaseInteraction::getOverlap(), BaseInteraction::getP(), BaseInteractable::getSpecies(), getSpecies(), ChargedBondedSpecies::getVanDerWaalsForceMax(), ChargedBondedSpecies::getVanDerWaalsStiffness(), k, logger, UniformPSDSelfTest::r, and mathsFunc::square().
getSpecies()
const ChargedBondedSpecies * ChargedBondedInteraction::getSpecies () const
Returns a pointer to the adhesive force species ChargedBondedSpecies.
Returns
a constant pointer to an instance of this class.
 {
     return static_cast<const ChargedBondedSpecies*> (getBaseSpecies()->getAdhesiveForce()); //downcast
 }
References BaseSpecies::getAdhesiveForce(), and BaseInteraction::getBaseSpecies().
Referenced by computeAdhesionForce(), and getElasticEnergy().
isBonded()
bool ChargedBondedInteraction::isBonded () const inline override virtual
Reimplemented from BaseInteraction.
 {return bonded_;}
References bonded_.
read()
void ChargedBondedInteraction::read (std::istream & is) override virtual
Interaction read function, which accepts an std::istream as input.
Parameters
[in] is
Implements BaseObject.
 {
     std::string dummy;
     //logger(INFO,"ChargedBondedSpecies %",dummy);
     is >> dummy >> bonded_;
 }
References bonded_, and oomph::Global_string_for_annotation::string().
unbond()
void ChargedBondedInteraction::unbond ()
Used to set the private variable 'bonded' to false, thus allowing the user to choose to separate (or 'unbond') a given pair of interacting, overlapping particles together which were previously fixed (bonded) together Useful, for example, in implementing breakage mechanisms.
 {
     bonded_ = false;
 }
References bonded_.
write()
void ChargedBondedInteraction::write (std::ostream & os) const override virtual
Interaction print function, which accepts an std::ostream as input.
Parameters
[in] os
Implements BaseObject.
 {
     os << " bonded " << bonded_;
 }
References bonded_.
Member Data Documentation
bonded_
bool ChargedBondedInteraction::bonded_ private
A history parameter to store if the particles were in contact or not. Useful to compute adhesive forces. Setting bonded_ to 'true' for a given pair of (overlapping) particles will cause these particles to become fixed together, resulting in larger, composite particles that can be used to model aspherical geometries.
Referenced by bond(), ChargedBondedInteraction(), computeAdhesionForce(), getElasticEnergy(), isBonded(), read(), unbond(), and write().
The documentation for this class was generated from the following files:
ChargedBondedInteraction.h
ChargedBondedInteraction.cc