MercuryDPM: Eigen::SplineFitting< SplineType > Struct Template Reference
Eigen::SplineFitting< SplineType > Struct Template Reference
Geometry » Reference » Splines_Module
Spline fitting methods.
#include <SplineFitting.h>
Public Types
typedef SplineType::KnotVectorType KnotVectorType
typedef SplineType::ParameterVectorType ParameterVectorType
Static Public Member Functions
template<typename PointArrayType >
static SplineType Interpolate (const PointArrayType &pts, DenseIndex degree)
Fits an interpolating Spline to the given data points.
template<typename PointArrayType >
static SplineType Interpolate (const PointArrayType &pts, DenseIndex degree, const KnotVectorType &knot_parameters)
Fits an interpolating Spline to the given data points.
template<typename PointArrayType , typename IndexArray >
static SplineType InterpolateWithDerivatives (const PointArrayType &points, const PointArrayType &derivatives, const IndexArray &derivativeIndices, const unsigned int degree)
Fits an interpolating spline to the given data points and derivatives.
template<typename PointArrayType , typename IndexArray >
static SplineType InterpolateWithDerivatives (const PointArrayType &points, const PointArrayType &derivatives, const IndexArray &derivativeIndices, const unsigned int degree, const ParameterVectorType &parameters)
Fits an interpolating spline to the given data points and derivatives.
Detailed Description
template<typename SplineType>
struct Eigen::SplineFitting< SplineType >
Spline fitting methods.
Member Typedef Documentation
KnotVectorType
template<typename SplineType > typedef SplineType::KnotVectorType Eigen::SplineFitting< SplineType >::KnotVectorType
ParameterVectorType
template<typename SplineType > typedef SplineType::ParameterVectorType Eigen::SplineFitting< SplineType >::ParameterVectorType
Member Function Documentation
Interpolate() [1/2]
template<typename SplineType > template<typename PointArrayType > SplineType Eigen::SplineFitting< SplineType >::Interpolate (const PointArrayType & pts, DenseIndex degree) static
Fits an interpolating Spline to the given data points.
Parameters
pts The points for which an interpolating spline will be computed.
degree The degree of the interpolating spline.
Returns
A spline interpolating the initially provided points.
{
   KnotVectorType chord_lengths;  // knot parameters
   ChordLengths(pts, chord_lengths);
   return Interpolate(pts, degree, chord_lengths);
 }
References Eigen::ChordLengths(), and constants::degree.
Interpolate() [2/2]
template<typename SplineType > template<typename PointArrayType > SplineType Eigen::SplineFitting< SplineType >::Interpolate (const PointArrayType & pts, DenseIndex degree, const KnotVectorType & knot_parameters) static
Fits an interpolating Spline to the given data points.
Parameters
pts The points for which an interpolating spline will be computed.
degree The degree of the interpolating spline.
knot_parameters The knot parameters for the interpolation.
Returns
A spline interpolating the initially provided points.
{
   typedef typename SplineType::KnotVectorType::Scalar Scalar;
   typedef typename SplineType::ControlPointVectorType ControlPointVectorType;
   typedef Matrix<Scalar, Dynamic, Dynamic> MatrixType;
   KnotVectorType knots;
   KnotAveraging(knot_parameters, degree, knots);
   DenseIndex n = pts.cols();
   MatrixType A = MatrixType::Zero(n, n);
   for (DenseIndex i = 1; i < n - 1; ++i) {
     const DenseIndex span = SplineType::Span(knot_parameters[i], degree, knots);
     // The segment call should somehow be told the spline order at compile time.
     A.row(i).segment(span - degree, degree + 1) = SplineType::BasisFunctions(knot_parameters[i], degree, knots);
   }
   A(0, 0) = 1.0;
   A(n - 1, n - 1) = 1.0;
   HouseholderQR<MatrixType> qr(A);
   // Here, we are creating a temporary due to an Eigen issue.
   ControlPointVectorType ctrls = qr.solve(MatrixType(pts.transpose())).transpose();
   return SplineType(knots, ctrls);
 }
References constants::degree, i, Eigen::KnotAveraging(), n, qr(), and oomph::PseudoSolidHelper::Zero.
InterpolateWithDerivatives() [1/2]
template<typename SplineType > template<typename PointArrayType , typename IndexArray > SplineType Eigen::SplineFitting< SplineType >::InterpolateWithDerivatives (const PointArrayType & points, const PointArrayType & derivatives, const IndexArray & derivativeIndices, const unsigned int degree) static
Fits an interpolating spline to the given data points and derivatives.
Parameters
points The points for which an interpolating spline will be computed.
derivatives The desired derivatives of the interpolating spline at interpolation points.
derivativeIndices An array indicating which point each derivative belongs to. This must be the same size as derivatives.
degree The degree of the interpolating spline.
Returns
A spline interpolating points with derivatives at those points.
See also
Les A. Piegl, Khairan Rajab, Volha Smarodzinana. 2008. Curve interpolation with directional constraints for engineering design. Engineering with Computers
{
   ParameterVectorType parameters;
   ChordLengths(points, parameters);
   return InterpolateWithDerivatives(points, derivatives, derivativeIndices, degree, parameters);
 }
References Eigen::ChordLengths(), and constants::degree.
InterpolateWithDerivatives() [2/2]
template<typename SplineType > template<typename PointArrayType , typename IndexArray > SplineType Eigen::SplineFitting< SplineType >::InterpolateWithDerivatives (const PointArrayType & points, const PointArrayType & derivatives, const IndexArray & derivativeIndices, const unsigned int degree, const ParameterVectorType & parameters) static
Fits an interpolating spline to the given data points and derivatives.
Parameters
points The points for which an interpolating spline will be computed.
derivatives The desired derivatives of the interpolating spline at interpolation points.
derivativeIndices An array indicating which point each derivative belongs to. This must be the same size as derivatives.
degree The degree of the interpolating spline.
parameters The parameters corresponding to the interpolation points.
Returns
A spline interpolating points with derivatives at those points.
See also
Les A. Piegl, Khairan Rajab, Volha Smarodzinana. 2008. Curve interpolation with directional constraints for engineering design. Engineering with Computers
{
   typedef typename SplineType::KnotVectorType::Scalar Scalar;
   typedef typename SplineType::ControlPointVectorType ControlPointVectorType;
   typedef Matrix<Scalar, Dynamic, Dynamic> MatrixType;
   const DenseIndex n = points.cols() + derivatives.cols();
   KnotVectorType knots;
   KnotAveragingWithDerivatives(parameters, degree, derivativeIndices, knots);
   // fill matrix
   MatrixType A = MatrixType::Zero(n, n);
   // Use these dimensions for quicker populating, then transpose for solving.
   MatrixType b(points.rows(), n);
   DenseIndex startRow;
   DenseIndex derivativeStart;
   // End derivatives.
   if (derivativeIndices[0] == 0) {
     A.template block<1, 2>(1, 0) << -1, 1;
     Scalar y = (knots(degree + 1) - knots(0)) / degree;
     b.col(1) = y * derivatives.col(0);
     startRow = 2;
     derivativeStart = 1;
   } else {
     startRow = 1;
     derivativeStart = 0;
   }
   if (derivativeIndices[derivatives.cols() - 1] == points.cols() - 1) {
     A.template block<1, 2>(n - 2, n - 2) << -1, 1;
     Scalar y = (knots(knots.size() - 1) - knots(knots.size() - (degree + 2))) / degree;
     b.col(b.cols() - 2) = y * derivatives.col(derivatives.cols() - 1);
   }
   DenseIndex row = startRow;
   DenseIndex derivativeIndex = derivativeStart;
   for (DenseIndex i = 1; i < parameters.size() - 1; ++i) {
     const DenseIndex span = SplineType::Span(parameters[i], degree, knots);
     if (derivativeIndex < derivativeIndices.size() && derivativeIndices[derivativeIndex] == i) {
       A.block(row, span - degree, 2, degree + 1) =
           SplineType::BasisFunctionDerivatives(parameters[i], 1, degree, knots);
       b.col(row++) = points.col(i);
       b.col(row++) = derivatives.col(derivativeIndex++);
     } else {
       A.row(row).segment(span - degree, degree + 1) = SplineType::BasisFunctions(parameters[i], degree, knots);
       b.col(row++) = points.col(i);
     }
   }
   b.col(0) = points.col(0);
   b.col(b.cols() - 1) = points.col(points.cols() - 1);
   A(0, 0) = 1;
   A(n - 1, n - 1) = 1;
   // Solve
   FullPivLU<MatrixType> lu(A);
   ControlPointVectorType controlPoints = lu.solve(MatrixType(b.transpose())).transpose();
   SplineType spline(knots, controlPoints);
   return spline;
 }
References b, constants::degree, i, Eigen::KnotAveragingWithDerivatives(), lu(), n, row(), y, and oomph::PseudoSolidHelper::Zero.
The documentation for this struct was generated from the following file:
SplineFitting.h