MercuryDPM: Eigen::internal::random_bits_impl< Scalar > Struct Template Reference
Eigen::internal::random_bits_impl< Scalar > Struct Template Reference
#include <RandomImpl.h>
Public Types
using RandomDevice = eigen_random_device
using RandomReturnType = typename RandomDevice::ReturnType
Static Public Member Functions
static EIGEN_DEVICE_FUNC Scalar run (int numRandomBits)
Static Public Attributes
static constexpr int kEntropy = RandomDevice::Entropy
static constexpr int kTotalBits = sizeof(Scalar) * CHAR_BIT
Member Typedef Documentation
RandomDevice
template<typename Scalar > using Eigen::internal::random_bits_impl< Scalar >::RandomDevice = eigen_random_device
RandomReturnType
template<typename Scalar > using Eigen::internal::random_bits_impl< Scalar >::RandomReturnType = typename RandomDevice::ReturnType
Member Function Documentation
run()
template<typename Scalar > static EIGEN_DEVICE_FUNC Scalar Eigen::internal::random_bits_impl< Scalar >::run (int numRandomBits) inline static
{
     eigen_assert((numRandomBits >= 0) && (numRandomBits <= kTotalBits));
     const Scalar mask = Scalar(-1) >> ((kTotalBits - numRandomBits) & (kTotalBits - 1));
     Scalar randomBits = 0;
     for (int shift = 0; shift < numRandomBits; shift += kEntropy) {
       RandomReturnType r = RandomDevice::run();
       randomBits |= static_cast<Scalar>(r) << shift;
     }
     // clear the excess bits
     randomBits &= mask;
     return randomBits;
   }
References eigen_assert, Eigen::internal::random_bits_impl< Scalar >::kEntropy, Eigen::internal::random_bits_impl< Scalar >::kTotalBits, UniformPSDSelfTest::r, and Eigen::internal::eigen_random_device::run().
Referenced by Eigen::internal::getRandomBits().
Member Data Documentation
kEntropy
template<typename Scalar > constexpr int Eigen::internal::random_bits_impl< Scalar >::kEntropy = RandomDevice::Entropy static constexpr
Referenced by Eigen::internal::random_bits_impl< Scalar >::run().
kTotalBits
template<typename Scalar > constexpr int Eigen::internal::random_bits_impl< Scalar >::kTotalBits = sizeof(Scalar) * CHAR_BIT static constexpr
Referenced by Eigen::internal::random_bits_impl< Scalar >::run().
The documentation for this struct was generated from the following file:
RandomImpl.h