MercuryDPM: PossibleContact Class Reference
PossibleContact Class Reference
Class that describes a possible contact between two BaseParticle.
#include <PossibleContact.h>
Public Member Functions
PossibleContact ()
Default constructor, sets all pointers to nullptr.
PossibleContact (BaseParticle *P1, BaseParticle *P2)
Constructor that takes two BaseParticle and sets them to be the BaseParticle associated with this PossibleContact.
PossibleContact (BaseParticle *P1, BaseParticle *P2, PossibleContact *Next)
Constructor that takes two BaseParticle and the next global PossibleContact in the list and constructs a PossibleContact from that.
PossibleContact (BaseParticle *P1, BaseParticle *P2, PossibleContact *Next, PossibleContact *Next1, PossibleContact *Next2)
Constructor that should be used, takes all required information as parameters and sets it in the data-members.
BaseParticle * getP1 ()
Gets a pointer to the first BaseParticle in this PossibleContact.
BaseParticle * getP2 ()
Gets a pointer to the second BaseParticle in this PossibleContact.
BaseParticle * getOtherParticle (BaseParticle *P)
Given one BaseParticle of the interacting pair, this function gets the other.
PossibleContact * getNext ()
Gets the next PossibleContact in the general linked list of PossibleContact.
PossibleContact * getNext (BaseParticle *P)
Gets the next PossibleContact in the linked list of PossibleContact of the given particle.
PossibleContact * getPrevious ()
Gets the previous PossibleContact in the general linked list of PossibleContact.
PossibleContact * getPrevious (BaseParticle *P)
Gets the previous PossibleContact in the linked list of PossibleContact of the given particle.
PossibleContact * getNext1 ()
Gets the next PossibleContact in the linked list of PossibleContact of the first particle in this PossibleContact.
PossibleContact * getPrevious1 ()
Gets the previous PossibleContact in the linked list of PossibleContact of the first particle in this PossibleContact.
PossibleContact * getNext2 ()
Gets the next PossibleContact in the linked list of PossibleContact of the second particle in this PossibleContact.
PossibleContact * getPrevious2 ()
Gets the previous PossibleContact in the linked list of PossibleContact of the second particle in this PossibleContact.
int getIndex ()
Gets the index of this PossibleContact.
void setP1 (BaseParticle *P1)
Sets the first particle in this PossibleContact.
void setP2 (BaseParticle *P2)
Sets the second particle in this PossibleContact.
void setNextPosition (PossibleContact *Next)
Sets the next PossibleContact in the linked list of PossibleContac.
void setNextPosition (BaseParticle *P, PossibleContact *Next)
Sets the next PossibleContact in the linked list of PossibleContact of the given particle.
void setPreviousPosition (PossibleContact *Prev)
Sets the previous PossibleContact in the linked list of PossibleContact of the given particle.
void setPreviousPosition (BaseParticle *P, PossibleContact *Prev)
Sets the previous PossibleContact in the linked list of PossibleContact of the given particle.
void setNextPosition1 (PossibleContact *Next1)
Sets the next PossibleContact in the linked list of PossibleContact of the first particle in this PossibleContact.
void setPreviousPosition1 (PossibleContact *Prev1)
Sets the previous PossibleContact in the linked list of PossibleContact of the first particle in this PossibleContact.
void setNextPosition2 (PossibleContact *Next2)
Sets the next PossibleContact in the linked list of PossibleContact of the second particle in this PossibleContact.
void setPreviousPosition2 (PossibleContact *Prev2)
Sets the previous PossibleContact in the linked list of PossibleContact of the second particle in this PossibleContact.
Private Attributes
int index_
The index of this PossibleContact.
BaseParticle * P1_
A pointer to the first BaseParticle in this PossibleContact.
BaseParticle * P2_
A pointer to the second BaseParticle in this PossibleContact.
PossibleContact * Next_
A pointer to the PossibleContact that comes after this one in the linked list.
PossibleContact * Prev_
A pointer to the PossibleContact that comes before this one in the linked list.
PossibleContact * Next1_
A pointer to the PossibleContact that comes after this one in the linked list associated with the first BaseParticle of this PossibleContact.
PossibleContact * Prev1_
A pointer to the PossibleContact that comes before this one in the linked list associated with the first BaseParticle of this PossibleContact.
PossibleContact * Next2_
A pointer to the PossibleContact that comes after this one in the linked list associated with the second BaseParticle of this PossibleContact.
PossibleContact * Prev2_
A pointer to the PossibleContact that comes before this one in the linked list associated with the second BaseParticle of this PossibleContact.
Friends
std::ostream & operator<< (std::ostream &os, const PossibleContact &o)
Writes the index of this PossibleContact and the indices of the BaseParticle of this PossibleContact to the given ostream.
Detailed Description
Class that describes a possible contact between two BaseParticle.
In this class that describes a possible contact two BaseParticle we save both of these BaseParticle, the index of this PossibleContact and the PossibleContact that comes before and after this one in the linked list, both for the general list and the list for each of the particles.
Todo:
Change the names so that they follow the code guidelines.
Constructor & Destructor Documentation
PossibleContact() [1/4]
PossibleContact::PossibleContact () inline
Default constructor, sets all pointers to nullptr.
     {
         P1_ = nullptr;
         P2_ = nullptr;
         Next_ = nullptr;
         Prev_ = nullptr;
         Next1_ = nullptr;
         Prev1_ = nullptr;
         Next2_ = nullptr;
         Prev2_ = nullptr;
         index_ = 0;
     }
References index_, Next1_, Next2_, Next_, P1_, P2_, Prev1_, Prev2_, and Prev_.
PossibleContact() [2/4]
PossibleContact::PossibleContact (BaseParticle * P1, BaseParticle * P2) inline
Constructor that takes two BaseParticle and sets them to be the BaseParticle associated with this PossibleContact.
Parameters
[in] P1 A pointer to the first BaseParticle in this PossibleContact.
[in] P2 A pointer to the second BaseParticle in this PossibleContact.
     {
         P1_ = P1;
         P2_ = P2;
         Next_ = nullptr;
         Prev_ = nullptr;
         Next1_ = nullptr;
         Prev1_ = nullptr;
         Next2_ = nullptr;
         Prev2_ = nullptr;
         index_ = 0;
     }
References index_, Next1_, Next2_, Next_, P1_, P2_, Prev1_, Prev2_, and Prev_.
PossibleContact() [3/4]
PossibleContact::PossibleContact (BaseParticle * P1, BaseParticle * P2, PossibleContact * Next) inline
Constructor that takes two BaseParticle and the next global PossibleContact in the list and constructs a PossibleContact from that.
Parameters
[in] P1 A pointer to the first BaseParticle in this PossibleContact.
[in] P2 A pointer to the second BaseParticle in this PossibleContact.
[in] Next A pointer to the PossibleContact that comes after this one in the linked list.
     {
         P1_ = P1;
         P2_ = P2;
         Next_ = Next;
         Prev_ = nullptr;
         if (Next != nullptr)
             index_ = Next->getIndex() + 1;
         else
             index_ = 0;
         Next1_ = nullptr;
         Prev1_ = nullptr;
         Next2_ = nullptr;
         Prev2_ = nullptr;
     }
References getIndex(), index_, Next1_, Next2_, Next_, P1_, P2_, Prev1_, Prev2_, and Prev_.
PossibleContact() [4/4]
PossibleContact::PossibleContact (BaseParticle * P1, BaseParticle * P2, PossibleContact * Next, PossibleContact * Next1, PossibleContact * Next2) inline
Constructor that should be used, takes all required information as parameters and sets it in the data-members.
Parameters
[in] P1 A pointer to the first BaseParticle in this PossibleContact.
[in] P2 A pointer to the second BaseParticle in this PossibleContact.
[in] Next A pointer to the PossibleContact that comes after this one in the linked list.
[in] Next1 A pointer to the PossibleContact that comes after this one in the linked list associated with the first BaseParticle of this PossibleContact.
[in] Next2 A pointer to the PossibleContact that comes after this one in the linked list associated with the second BaseParticle of this PossibleContact.
     {
         P1_ = P1;
         P2_ = P2;
         Next_ = Next;
         Next1_ = Next1;
         Next2_ = Next2;
         Prev_ = 0;
         Prev1_ = 0;
         Prev2_ = 0;
         if (Next != nullptr)
             index_ = Next->getIndex() + 1;
         else
             index_ = 0;
     }
References getIndex(), index_, Next1_, Next2_, Next_, P1_, P2_, Prev1_, Prev2_, and Prev_.
Member Function Documentation
getIndex()
int PossibleContact::getIndex () inline
Gets the index of this PossibleContact.
Returns
The index of this PossibleContact.
     {
         return index_;
     }
References index_.
Referenced by PossibleContact(), and PossibleContactList::remove_ParticlePosibleContacts().
getNext() [1/2]
PossibleContact* PossibleContact::getNext () inline
Gets the next PossibleContact in the general linked list of PossibleContact.
Returns
A pointer to the next PossibleContact in the linked list.
     {
         return Next_;
     }
References Next_.
Referenced by PossibleContactList::add_PossibleContact(), DPMBase::computeAllForces(), PossibleContactList::remove_ParticlePosibleContacts(), and PossibleContactList::write().
getNext() [2/2]
PossibleContact* PossibleContact::getNext (BaseParticle * P) inline
Gets the next PossibleContact in the linked list of PossibleContact of the given particle.
Parameters
[in] P A pointer to the BaseParticle for which we want to have the next contact of.
Returns
A pointer to the next PossibleContact in the linked list of PossibleContact of the given particle.
     {
         if (P1_ == P)
             return Next1_;
         else if (P2_ == P)
             return Next2_;
         else
         {
             logger(WARN, "PossibleContact* getNext(Particle* P), no match for %. Possibilities are % and %.",
                    P->getIndex(), P1_->getIndex(), P2_->getIndex());
             return nullptr;
         }
     }
References BaseObject::getIndex(), logger, Next1_, Next2_, Global_Physical_Variables::P, P1_, P2_, and WARN.
getNext1()
PossibleContact* PossibleContact::getNext1 () inline
Gets the next PossibleContact in the linked list of PossibleContact of the first particle in this PossibleContact.
Returns
A pointer to the next PossibleContact in the linked list of PossibleContact of the first particle in this PossibleContact.
     {
         return Next1_;
     }
References Next1_.
Referenced by PossibleContactList::add_PossibleContact().
getNext2()
PossibleContact* PossibleContact::getNext2 () inline
Gets the next PossibleContact in the linked list of PossibleContact of the second particle in this PossibleContact.
Returns
A pointer to the next PossibleContact in the linked list of PossibleContact of the second particle in this PossibleContact.
     {
         return Next2_;
     }
References Next2_.
Referenced by PossibleContactList::add_PossibleContact().
getOtherParticle()
BaseParticle* PossibleContact::getOtherParticle (BaseParticle * P) inline
Given one BaseParticle of the interacting pair, this function gets the other.
Parameters
[in] P A pointer to one of the BaseParticle of this PossibleContact.
Returns
The other BaseParticle of this PossibleContact.
     {
         if (P1_ == P)
             return P2_;
         else if (P2_ == P)
             return P1_;
         else
         {
             logger(WARN, "Particle* getOtherParticle(Particle *P), no match for % posibilities are % and %",
                    P->getIndex(), P1_->getIndex(), P2_->getIndex());
             return nullptr;
         }
     }
References BaseObject::getIndex(), logger, Global_Physical_Variables::P, P1_, P2_, and WARN.
Referenced by PossibleContactList::remove_ParticlePosibleContacts().
getP1()
BaseParticle* PossibleContact::getP1 () inline
Gets a pointer to the first BaseParticle in this PossibleContact.
Returns
A pointer to the first BaseParticle in this PossibleContact.
     {
         return P1_;
     }
References P1_.
Referenced by DPMBase::computeAllForces(), and PossibleContactList::remove_ParticlePosibleContacts().
getP2()
BaseParticle* PossibleContact::getP2 () inline
Gets a pointer to the second BaseParticle in this PossibleContact.
Returns
A pointer to the second BaseParticle in this PossibleContact.
     {
         return P2_;
     }
References P2_.
Referenced by DPMBase::computeAllForces(), and PossibleContactList::remove_ParticlePosibleContacts().
getPrevious() [1/2]
PossibleContact* PossibleContact::getPrevious () inline
Gets the previous PossibleContact in the general linked list of PossibleContact.
Returns
A pointer to the previous PossibleContact in the general linked list of PossibleContact.
     {
         return Prev_;
     }
References Prev_.
Referenced by PossibleContactList::remove_ParticlePosibleContacts().
getPrevious() [2/2]
PossibleContact* PossibleContact::getPrevious (BaseParticle * P) inline
Gets the previous PossibleContact in the linked list of PossibleContact of the given particle.
Parameters
[in] P A pointer to the BaseParticle we want to know the previous PossibleContact for.
Returns
A pointer to the previous PossibleContact in the linked list of PossibleContact of the given particle.
     {
         if (P1_ == P)
             return Prev1_;
         else if (P2_ == P)
             return Prev2_;
         else
         {
             logger(WARN, "PossibleContact* getPrevious(Particle* P), no match for %. Possibilities are % and %.",
                    P->getIndex(), P1_->getIndex(), P2_->getIndex());
             return nullptr;
         }
     }
References BaseObject::getIndex(), logger, Global_Physical_Variables::P, P1_, P2_, Prev1_, Prev2_, and WARN.
getPrevious1()
PossibleContact* PossibleContact::getPrevious1 () inline
Gets the previous PossibleContact in the linked list of PossibleContact of the first particle in this PossibleContact.
Returns
A pointer to the previous PossibleContact in the linked list of PossibleContact of the first particle in this PossibleContact.
     {
         return Prev1_;
     }
References Prev1_.
getPrevious2()
PossibleContact* PossibleContact::getPrevious2 () inline
Gets the previous PossibleContact in the linked list of PossibleContact of the second particle in this PossibleContact.
Returns
A pointer to the previous PossibleContact in the linked list of PossibleContact of the second particle in this PossibleContact.
     {
         return Prev2_;
     }
References Prev2_.
setNextPosition() [1/2]
void PossibleContact::setNextPosition (BaseParticle * P, PossibleContact * Next) inline
Sets the next PossibleContact in the linked list of PossibleContact of the given particle.
Parameters
[in] P A pointer to the BaseParticle for which the next PossibleContact in the linked list must be set for.
[in] Next A pointer to the PossibleContact which is the next PossibleContact for the given BaseParticle.
     {
         if (P1_ == P)
             Next1_ = Next;
         else if (P2_ == P)
             Next2_ = Next;
         else
             logger(WARN,
                    "void setNextPosition(Particle* P,PossibleContact* Next), no match for %. Possibilities are %  and % ",
                    P->getIndex(), P1_->getIndex(), P2_->getIndex());
     }
References BaseObject::getIndex(), logger, Next1_, Next2_, Global_Physical_Variables::P, P1_, P2_, and WARN.
setNextPosition() [2/2]
void PossibleContact::setNextPosition (PossibleContact * Next) inline
Sets the next PossibleContact in the linked list of PossibleContac.
Parameters
[in] Next A pointer to the PossibleContact which is the next PossibleContact in the linked list of PossibleContact
     {
         Next_ = Next;
     }
References Next_.
Referenced by PossibleContactList::remove_ParticlePosibleContacts().
setNextPosition1()
void PossibleContact::setNextPosition1 (PossibleContact * Next1) inline
Sets the next PossibleContact in the linked list of PossibleContact of the first particle in this PossibleContact.
Parameters
[in] Next1 A pointer to the PossibleContact which is the next PossibleContact for the first BaseParticle.
     {
         Next1_ = Next1;
     }
References Next1_.
setNextPosition2()
void PossibleContact::setNextPosition2 (PossibleContact * Next2) inline
Sets the next PossibleContact in the linked list of PossibleContact of the second particle in this PossibleContact.
Parameters
[in] Next2 A pointer to the PossibleContact which is the next PossibleContact for the second BaseParticle.
     {
         Next2_ = Next2;
     }
References Next2_.
setP1()
void PossibleContact::setP1 (BaseParticle * P1) inline
Sets the first particle in this PossibleContact.
Parameters
[in] P1 A pointer to the BaseParticle that must be set as the first BaseParticle.
     {
         P1_ = P1;
     }
References P1_.
setP2()
void PossibleContact::setP2 (BaseParticle * P2) inline
Sets the second particle in this PossibleContact.
Parameters
[in] P2 A pointer to the BaseParticle that must be set as the second BaseParticle.
     {
         P2_ = P2;
     }
References P2_.
setPreviousPosition() [1/2]
void PossibleContact::setPreviousPosition (BaseParticle * P, PossibleContact * Prev) inline
Sets the previous PossibleContact in the linked list of PossibleContact of the given particle.
Parameters
[in] P A pointer to the BaseParticle for which the previous PossibleContact in the linked list must be set for.
[in] Prev A pointer to the PossibleContact which is the previous PossibleContact for the given BaseParticle.
     {
         if (P1_ == P)
             Prev1_ = Prev;
         else if (P2_ == P)
             Prev2_ = Prev;
         else
             logger(WARN,
                    "void setPreviousPosition(Particle* P,PossibleContact* Prev), no match for %. Possibilities are %  and % ",
                    P->getIndex(), P1_->getIndex(), P2_->getIndex());
     }
References BaseObject::getIndex(), logger, Global_Physical_Variables::P, P1_, P2_, Prev1_, Prev2_, and WARN.
setPreviousPosition() [2/2]
void PossibleContact::setPreviousPosition (PossibleContact * Prev) inline
Sets the previous PossibleContact in the linked list of PossibleContact of the given particle.
Parameters
[in] Prev A pointer to the PossibleContact which is the previous PossibleContact in the linked list of PossibleContact
     {
         Prev_ = Prev;
     }
References Prev_.
Referenced by PossibleContactList::add_PossibleContact(), and PossibleContactList::remove_ParticlePosibleContacts().
setPreviousPosition1()
void PossibleContact::setPreviousPosition1 (PossibleContact * Prev1) inline
Sets the previous PossibleContact in the linked list of PossibleContact of the first particle in this PossibleContact.
Parameters
[in] Prev1 A pointer to the PossibleContact which is the previous PossibleContact for the first BaseParticle.
     {
         Prev1_ = Prev1;
     }
References Prev1_.
setPreviousPosition2()
void PossibleContact::setPreviousPosition2 (PossibleContact * Prev2) inline
Sets the previous PossibleContact in the linked list of PossibleContact of the second particle in this PossibleContact.
Parameters
[in] Prev2 A pointer to the PossibleContact which is the previous PossibleContact for the second BaseParticle.
     {
         Prev2_ = Prev2;
     }
References Prev2_.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const PossibleContact & o) friend
Writes the index of this PossibleContact and the indices of the BaseParticle of this PossibleContact to the given ostream.
Parameters
[in,out] os The output stream to which this PossibleContact must be written.
[in] o The PossibleContact that must be written.
Returns
The output stream to which this PossibleContact has been written.
     {
         os << o.index_ << " between (" << o.P1_->getIndex() << "," << o.P2_->getIndex() << ")";
         return os;
     }
Member Data Documentation
index_
int PossibleContact::index_ private
The index of this PossibleContact.
Referenced by getIndex(), and PossibleContact().
Next1_
PossibleContact* PossibleContact::Next1_ private
A pointer to the PossibleContact that comes after this one in the linked list associated with the first BaseParticle of this PossibleContact.
Referenced by getNext(), getNext1(), PossibleContact(), setNextPosition(), and setNextPosition1().
Next2_
PossibleContact* PossibleContact::Next2_ private
A pointer to the PossibleContact that comes after this one in the linked list associated with the second BaseParticle of this PossibleContact.
Referenced by getNext(), getNext2(), PossibleContact(), setNextPosition(), and setNextPosition2().
Next_
PossibleContact* PossibleContact::Next_ private
A pointer to the PossibleContact that comes after this one in the linked list.
Referenced by getNext(), PossibleContact(), and setNextPosition().
P1_
BaseParticle* PossibleContact::P1_ private
A pointer to the first BaseParticle in this PossibleContact.
Referenced by getNext(), getOtherParticle(), getP1(), getPrevious(), PossibleContact(), setNextPosition(), setP1(), and setPreviousPosition().
P2_
BaseParticle* PossibleContact::P2_ private
A pointer to the second BaseParticle in this PossibleContact.
Referenced by getNext(), getOtherParticle(), getP2(), getPrevious(), PossibleContact(), setNextPosition(), setP2(), and setPreviousPosition().
Prev1_
PossibleContact* PossibleContact::Prev1_ private
A pointer to the PossibleContact that comes before this one in the linked list associated with the first BaseParticle of this PossibleContact.
Referenced by getPrevious(), getPrevious1(), PossibleContact(), setPreviousPosition(), and setPreviousPosition1().
Prev2_
PossibleContact* PossibleContact::Prev2_ private
A pointer to the PossibleContact that comes before this one in the linked list associated with the second BaseParticle of this PossibleContact.
Referenced by getPrevious(), getPrevious2(), PossibleContact(), setPreviousPosition(), and setPreviousPosition2().
Prev_
PossibleContact* PossibleContact::Prev_ private
A pointer to the PossibleContact that comes before this one in the linked list.
Referenced by getPrevious(), PossibleContact(), and setPreviousPosition().
The documentation for this class was generated from the following file:
PossibleContact.h