MercuryDPM: AxiPoroProblem< ELEMENT, TIMESTEPPER > Class Template Reference
AxiPoroProblem< ELEMENT, TIMESTEPPER > Class Template Reference
Problem class.
Public Member Functions
AxiPoroProblem ()
Constructor.
void set_boundary_values ()
Set the time-dependent boundary values.
void set_initial_condition ()
Set the initial conditions.
void doc_solution (const unsigned &label)
Doc the solution.
void actions_before_newton_solve ()
Actions before newton solve (empty)
void actions_after_newton_solve ()
Actions after newton solve (empty)
void actions_before_implicit_timestep ()
Actions before implicit timestep – update boundary conditions.
void complete_problem_setup ()
Complete problem setup.
TIMESTEPPER * my_time_stepper_pt ()
Access to timestepper.
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
virtual void actions_before_adapt ()
virtual void actions_after_adapt ()
Actions that are to be performed after a mesh adaptation.
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Private Member Functions
void create_pressure_elements ()
Allocate traction/pressure elements.
Private Attributes
TriangleMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the "bulk" mesh.
Mesh * Surface_mesh_pt
Mesh for traction/pressure elements.
std::ofstream Trace_file
Trace file.
TIMESTEPPER * My_time_stepper_pt
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_convergence_check ()
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class ELEMENT, class TIMESTEPPER>
class AxiPoroProblem< ELEMENT, TIMESTEPPER >
Problem class.
Constructor & Destructor Documentation
AxiPoroProblem()
template<class ELEMENT , class TIMESTEPPER > AxiPoroProblem< ELEMENT, TIMESTEPPER >::AxiPoroProblem
Constructor.
 {
  // Problem is linear
  Problem::Problem_is_nonlinear=false;
  // Allocate the timestepper
  My_time_stepper_pt=new TIMESTEPPER;
  add_time_stepper_pt(My_time_stepper_pt);
  // disable warnings in assign initial data values
  My_time_stepper_pt->disable_warning_in_assign_initial_data_values();
  // Remember it
  ProblemParameters::Internal_time_stepper_pt=My_time_stepper_pt;
  // Solid mesh
  //-----------
  TriangleMeshClosedCurve *outer_boundary_pt=0;
  // Internal boundary to prevent problem with flux B.C.s
  Vector<TriangleMeshOpenCurve*> inner_open_boundary_pt;
  // Temporary storage for coords in required format
  Vector<Vector<double> > temp_coord(2,Vector<double>(2));
  // Bottom small arc
  Circle* outer_boundary_lower_circle_pt=
   new Circle(ProblemParameters::Inner_radius,
              -2.0*ProblemParameters::Domain_radius,
              ProblemParameters::Domain_radius);
  // Large arc
  Circle* outer_boundary_right_circle_pt=
   new Circle(ProblemParameters::Inner_radius,0.0,sqrt(5)*
              ProblemParameters::Domain_radius);
  // Top small arc
  Circle* outer_boundary_upper_circle_pt=
   new Circle(ProblemParameters::Inner_radius,
              2.0*ProblemParameters::Domain_radius,
              ProblemParameters::Domain_radius);
  // Storage for the individual boundary sections
  Vector<TriangleMeshCurveSection*> outer_curvilinear_boundary_pt(4);
  // First bit
  double zeta_start=MathematicalConstants::Pi/2.0;
  double zeta_end=0;
  unsigned nsegment=
   (unsigned)max(
    3.0,
    MathematicalConstants::Pi*ProblemParameters::Domain_radius/
    (2*std::sqrt(ProblemParameters::Element_area)));
  outer_curvilinear_boundary_pt[0]=
   new TriangleMeshCurviLine(outer_boundary_lower_circle_pt, zeta_start,
                             zeta_end, nsegment, 0);
  // Second bit
  zeta_start=-atan(2.0);
  zeta_end=atan(2.0);
  nsegment=
   (unsigned)max(
    3.0,
    (2.0*MathematicalConstants::Pi*sqrt(5.0)*ProblemParameters::Domain_radius*
     (atan(2.0)/MathematicalConstants::Pi))/
    sqrt(ProblemParameters::Element_area));
  outer_curvilinear_boundary_pt[1]=
   new TriangleMeshCurviLine(outer_boundary_right_circle_pt, zeta_start,
                             zeta_end, nsegment, 1);
  // Third bit
  zeta_start=2.0*MathematicalConstants::Pi;
  zeta_end=3.0*MathematicalConstants::Pi/2.0;
  nsegment=
   (unsigned)max(
    3.0,
    MathematicalConstants::Pi*ProblemParameters::Domain_radius
    /(2.0*std::sqrt(ProblemParameters::Element_area)));
  outer_curvilinear_boundary_pt[2]=
   new TriangleMeshCurviLine(outer_boundary_upper_circle_pt, zeta_start,
                             zeta_end, nsegment, 2);
  // Fourth bit
  temp_coord[0][0]=ProblemParameters::Inner_radius;
  temp_coord[0][1]=ProblemParameters::Domain_radius;
  temp_coord[1][0]=ProblemParameters::Inner_radius;
  temp_coord[1][1]=-ProblemParameters::Domain_radius;
  outer_curvilinear_boundary_pt[3]=
   new TriangleMeshPolyLine(temp_coord,3);
  // Make the solid outer boundary
  outer_boundary_pt=
   new TriangleMeshClosedCurve(outer_curvilinear_boundary_pt);
  // Add four internal boundaries emanating from corners to make sure
  // that no elements have faces on two boundaries.
  inner_open_boundary_pt.resize(4);
  // First inner boundary
  temp_coord[0][0]=ProblemParameters::Inner_radius;
  temp_coord[0][1]=-ProblemParameters::Domain_radius;
  temp_coord[1][0]=ProblemParameters::Inner_radius+
   0.25*ProblemParameters::Domain_radius;
  temp_coord[1][1]=-0.75*ProblemParameters::Domain_radius;
  Vector<TriangleMeshCurveSection*> inner_open_polyline1_curve_section_pt(1);
  inner_open_polyline1_curve_section_pt[0]=
   new TriangleMeshPolyLine(temp_coord,4);
  inner_open_polyline1_curve_section_pt[0]->
   connect_initial_vertex_to_curviline(
    dynamic_cast<TriangleMeshCurviLine*>(outer_curvilinear_boundary_pt[0]),
    MathematicalConstants::Pi/2.0);
  inner_open_boundary_pt[0]=
   new TriangleMeshOpenCurve(inner_open_polyline1_curve_section_pt);
  // Second inner boundary
  temp_coord[0][0]=ProblemParameters::Inner_radius+
   ProblemParameters::Domain_radius;
  temp_coord[0][1]=-2.0*ProblemParameters::Domain_radius;
  temp_coord[1][0]=ProblemParameters::Inner_radius+
   1.3*ProblemParameters::Domain_radius;
  temp_coord[1][1]=-1.5*ProblemParameters::Domain_radius;
  TriangleMeshPolyLine *inner_open_polyline2_pt=
   new TriangleMeshPolyLine(temp_coord,5);
  inner_open_polyline2_pt->connect_initial_vertex_to_curviline(
   dynamic_cast<TriangleMeshCurviLine*>(outer_curvilinear_boundary_pt[1]),
   -atan(2.0));
  Vector<TriangleMeshCurveSection*> inner_open_polyline2_curve_section_pt(1);
  inner_open_polyline2_curve_section_pt[0]=inner_open_polyline2_pt;
  inner_open_boundary_pt[1]=
   new TriangleMeshOpenCurve(inner_open_polyline2_curve_section_pt);
  // Third inner boundary
  temp_coord[0][0]=ProblemParameters::Inner_radius+
   ProblemParameters::Domain_radius;
  temp_coord[0][1]=2.0*ProblemParameters::Domain_radius;
  temp_coord[1][0]=ProblemParameters::Inner_radius+
   1.3*ProblemParameters::Domain_radius;
  temp_coord[1][1]=1.5*ProblemParameters::Domain_radius;
  TriangleMeshPolyLine *inner_open_polyline3_pt=
   new TriangleMeshPolyLine(temp_coord,6);
  inner_open_polyline3_pt->connect_initial_vertex_to_curviline(
   dynamic_cast<TriangleMeshCurviLine*>(outer_curvilinear_boundary_pt[1]),
   atan(2.0));
  Vector<TriangleMeshCurveSection*> inner_open_polyline3_curve_section_pt(1);
  inner_open_polyline3_curve_section_pt[0]=inner_open_polyline3_pt;
  inner_open_boundary_pt[2]=
   new TriangleMeshOpenCurve(inner_open_polyline3_curve_section_pt);
  // Fourth inner boundary
  temp_coord[0][0]=ProblemParameters::Inner_radius;
  temp_coord[0][1]=ProblemParameters::Domain_radius;
  temp_coord[1][0]=ProblemParameters::Inner_radius+
   0.25*ProblemParameters::Domain_radius;
  temp_coord[1][1]=0.75*ProblemParameters::Domain_radius;
  Vector<TriangleMeshCurveSection*> inner_open_polyline4_curve_section_pt(1);
  inner_open_polyline4_curve_section_pt[0]=
   new TriangleMeshPolyLine(temp_coord,7);
  inner_open_polyline4_curve_section_pt[0]->connect_initial_vertex_to_polyline(
   dynamic_cast<TriangleMeshPolyLine*>(outer_curvilinear_boundary_pt[3]),
   0);
  inner_open_boundary_pt[3]=
   new TriangleMeshOpenCurve(inner_open_polyline4_curve_section_pt);
  // Use the TriangleMeshParameters object for gathering all
  // the necessary arguments for the TriangleMesh object
  TriangleMeshParameters triangle_mesh_parameters(
   outer_boundary_pt);
  // Set the inner boundaries
  triangle_mesh_parameters.internal_open_curves_pt()=
   inner_open_boundary_pt;
  // Target area for triangle
  triangle_mesh_parameters.element_area() = ProblemParameters::Element_area;
 #ifdef ADAPTIVE
  // Build adaptive "bulk" mesh
  Bulk_mesh_pt=new RefineableTriangleMesh<ELEMENT>(triangle_mesh_parameters,
                                                   time_stepper_pt());
  // Create/set error estimator
  Bulk_mesh_pt->spatial_error_estimator_pt()=new Z2ErrorEstimator;
  // Choose error tolerances
  Bulk_mesh_pt->min_permitted_error()=1.0e-4;
  Bulk_mesh_pt->max_permitted_error()=1.0e-3;
  Bulk_mesh_pt->max_element_size()=ProblemParameters::Element_area;
  Bulk_mesh_pt->min_element_size()=1.0e-20;
  // Actions before projection
  Bulk_mesh_pt->mesh_update_fct_pt()=
   &ProblemParameters::edge_sign_setup<ELEMENT>;
 #else
  // Create the buk mesh
  Bulk_mesh_pt = new TriangleMesh<ELEMENT>(triangle_mesh_parameters,
                                           time_stepper_pt());
 #endif
  // Setup the signs for the fluxes
  ProblemParameters::edge_sign_setup<ELEMENT>(Bulk_mesh_pt);
  // Create the surface mesh
  Surface_mesh_pt = new Mesh;
  // Assign the traction/pressure elements
  create_pressure_elements();
  // Add the submeshes to the global mesh
  add_sub_mesh(Bulk_mesh_pt);
  add_sub_mesh(Surface_mesh_pt);
  // Build the global mesh
  build_global_mesh();
  // Complete the problem set up
  complete_problem_setup();
  // Temporary filename string
  char filename[500];
  // Trace filename
  sprintf(filename,"%s/trace.dat",ProblemParameters::Directory.c_str());
  // Open the trace file
  Trace_file.open(filename);
  // Assign and doc number of eqns
  oomph_info << "Number of equations: " << assign_eqn_numbers() << std::endl;
 } // end of problem constructor
References Eigen::bfloat16_impl::atan(), oomph::TriangleMeshCurveSection::connect_initial_vertex_to_curviline(), ProblemParameters::Directory, ProblemParameters::Domain_radius, ProblemParameters::Element_area, oomph::TriangleMeshParameters::element_area(), MergeRestartFiles::filename, ProblemParameters::Inner_radius, oomph::TriangleMeshParameters::internal_open_curves_pt(), ProblemParameters::Internal_time_stepper_pt, max, oomph::oomph_info, oomph::MathematicalConstants::Pi, oomph::Problem::Problem_is_nonlinear, sqrt(), and oomph::Problem_Parameter::Trace_file.
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT , class TIMESTEPPER > void AxiPoroProblem< ELEMENT, TIMESTEPPER >::actions_after_newton_solve () inline virtual
Actions after newton solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_implicit_timestep()
template<class ELEMENT , class TIMESTEPPER > void AxiPoroProblem< ELEMENT, TIMESTEPPER >::actions_before_implicit_timestep () inline virtual
Actions before implicit timestep – update boundary conditions.
Reimplemented from oomph::Problem.
   {
    set_boundary_values();
   }
actions_before_newton_solve()
template<class ELEMENT , class TIMESTEPPER > void AxiPoroProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_solve () inline virtual
Actions before newton solve (empty)
Reimplemented from oomph::Problem.
 {}
complete_problem_setup()
template<class ELEMENT , class TIMESTEPPER > void AxiPoroProblem< ELEMENT, TIMESTEPPER >::complete_problem_setup
Complete problem setup.
 {
  // Loop over all elements to set parameters
  //-----------------------------------------
  unsigned n_element = Bulk_mesh_pt->nelement();
  for(unsigned e=0;e<n_element;e++)
   {
    ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e));
    el_pt->nu_pt()=&ProblemParameters::Nu;
    el_pt->solid_body_force_fct_pt()=ProblemParameters::Solid_body_force;
    el_pt->fluid_body_force_fct_pt()=ProblemParameters::Fluid_body_force;
    el_pt->mass_source_fct_pt()=ProblemParameters::Mass_source;
    el_pt->lambda_sq_pt()=&ProblemParameters::Lambda_sq;
    el_pt->density_ratio_pt()=&ProblemParameters::Density_ratio;
    el_pt->permeability_pt()=&ProblemParameters::Permeability;
    el_pt->alpha_pt()=&ProblemParameters::Alpha;
    el_pt->porosity_pt()=&ProblemParameters::Porosity;
    // Set the internal q dofs' timestepper to the problem timestepper
    el_pt->set_q_internal_timestepper(time_stepper_pt());
   } // end of loop over elements
  // Pin flux and solid displacement along selected boundaries
  // ----------------------------------------------------------
   std::vector<unsigned> pinned_boundaries;
  // Leave outflow boundary traction free ("do nothing") for "real"
  // run. Pin and apply flux and displacement for validation case
  if(CommandLineArgs::command_line_flag_has_been_set("--validation"))
   {
    pinned_boundaries.push_back(0);
   }
  pinned_boundaries.push_back(1);
  pinned_boundaries.push_back(3);
  unsigned n_boundary=pinned_boundaries.size();
  for(unsigned ibound=0;ibound<n_boundary;ibound++)
   {
    unsigned n_node = Bulk_mesh_pt->nboundary_node(pinned_boundaries[ibound]);
    for(unsigned i=0;i<n_node;i++)
     {
      Node* nod_pt=Bulk_mesh_pt->boundary_node_pt(pinned_boundaries[ibound],i);
      // Pin all of them: i=0: u_r; i=1: u_z. Subsequent entries
      // only exist for midside nodes where the remaining entries
      // represent the Darcy flux at the "flux interpolation points".
      unsigned n_value=nod_pt->nvalue();
      for(unsigned i=0;i<n_value;i++)
       {
        nod_pt->pin(i);
       }
     }
   }
 }
References ProblemParameters::Alpha, oomph::CommandLineArgs::command_line_flag_has_been_set(), ProblemParameters::Density_ratio, e(), ProblemParameters::Fluid_body_force(), i, ProblemParameters::Lambda_sq, ProblemParameters::Mass_source(), ProblemParameters::Nu, oomph::Data::nvalue(), ProblemParameters::Permeability, oomph::Data::pin(), ProblemParameters::Porosity, and ProblemParameters::Solid_body_force().
create_pressure_elements()
template<class ELEMENT , class TIMESTEPPER > void AxiPoroProblem< ELEMENT, TIMESTEPPER >::create_pressure_elements private
Allocate traction/pressure elements.
Make traction elements along the top boundary of the bulk mesh.
 {
  // How many bulk elements are next to boundary 2 (the top boundary)?
  unsigned ibound=2;
  unsigned n_neigh = Bulk_mesh_pt->nboundary_element(ibound);
  // Now loop over bulk elements and create the face elements
  for(unsigned n=0;n<n_neigh;n++)
   {
    // Create the face element
    AxisymmetricPoroelasticityTractionElement<ELEMENT>* pressure_element_pt
     = new AxisymmetricPoroelasticityTractionElement<ELEMENT>
     (Bulk_mesh_pt->boundary_element_pt(ibound,n),
      Bulk_mesh_pt->face_index_at_boundary(ibound,n));
    // Add to mesh
    Surface_mesh_pt->add_element_pt(pressure_element_pt);
    // Set function pointers
    pressure_element_pt->pressure_fct_pt()=&ProblemParameters::boundary_pressure;
    pressure_element_pt->traction_fct_pt()=&ProblemParameters::boundary_traction;
   }
 } // end of assign_traction_elements
References ProblemParameters::boundary_pressure(), ProblemParameters::boundary_traction(), n, oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::pressure_fct_pt, and oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::traction_fct_pt.
doc_solution()
template<class ELEMENT , class TIMESTEPPER > void AxiPoroProblem< ELEMENT, TIMESTEPPER >::doc_solution (const unsigned & label)
Doc the solution.
Write the solution and exact solution to file, and calculate the error.
 {
  oomph_info << "Outputting solution " << label
             << " for time " << time_pt()->time() << std::endl;
  ofstream some_file;
  char filename[100];
  unsigned npts=5;
  sprintf(filename,"%s/soln%i.dat",ProblemParameters::Directory.c_str(),label);
  some_file.open(filename);
  Bulk_mesh_pt->output(some_file,npts);
  some_file.close();
  // Output coarse solution
  //-----------------------
  unsigned npts_coarse=2;
  sprintf(filename,"%s/coarse_soln%i.dat",ProblemParameters::Directory.c_str(),label);
  some_file.open(filename);
  Bulk_mesh_pt->output(some_file,npts_coarse);
  some_file.close();
  // Output boundary condition elements
  //-----------------------------------
  sprintf(filename,"%s/bc_elements%i.dat",ProblemParameters::Directory.c_str(),label);
  some_file.open(filename);
  Surface_mesh_pt->output(some_file,npts);
  some_file.close();
  if(CommandLineArgs::command_line_flag_has_been_set("--validation"))
   {
    // Output exact solution
    //----------------------
    sprintf(filename,"%s/exact_soln%i.dat",ProblemParameters::Directory.c_str(),label);
    some_file.open(filename);
    Bulk_mesh_pt->output_fct(some_file,
                             npts,
                             time(),
                             ProblemParameters::exact_soln);
    some_file.close();
    // Doc error
    //----------
    Vector<double> norm(3,0.0);
    Vector<double> error(3,0.0);
    sprintf(filename,"%s/error%i.dat",ProblemParameters::Directory.c_str(),label);
    some_file.open(filename);
    Bulk_mesh_pt->compute_error(some_file,
                                ProblemParameters::exact_soln,
                                time(),
                                error,norm);
    some_file.close();
    // Doc error norm:
    oomph_info << std::endl;
    oomph_info << "Norm of exact u : " << sqrt(norm[0]) << std::endl;
    oomph_info << "Norm of exact q : " << sqrt(norm[1]) << std::endl;
    oomph_info << "Norm of exact p : " << sqrt(norm[2]) << std::endl
               << std::endl;
    oomph_info << "Norm of u error : " << sqrt(error[0]) << std::endl;
    oomph_info << "Norm of q error : " << sqrt(error[1]) << std::endl;
    oomph_info << "Norm of p error : " << sqrt(error[2]) << std::endl;
    oomph_info << std::endl << std::endl;
    Trace_file << ndof() << " "
               << ProblemParameters::Element_area << " "
               << ProblemParameters::Dt << " "
               << sqrt(error[0]) << " "
               << sqrt(error[1]) << " "
               << sqrt(error[2]) << " "
               << sqrt(norm[0]) << " "
               << sqrt(norm[1]) << " "
               << sqrt(norm[2]) << std::endl;
   }
  else
   {
    Trace_file << time_pt()->time() << " "
               << ProblemParameters::pressure_magnitude(time_pt()->time()) << " "
               << std::endl;
   }
 }
References oomph::CommandLineArgs::command_line_flag_has_been_set(), ProblemParameters::Directory, ProblemParameters::Dt, ProblemParameters::Element_area, calibrate::error, ProblemParameters::exact_soln(), MergeRestartFiles::filename, UniformPSDSelfTest::label, oomph::oomph_info, ProblemParameters::pressure_magnitude(), sqrt(), and oomph::Problem_Parameter::Trace_file.
my_time_stepper_pt()
template<class ELEMENT , class TIMESTEPPER > TIMESTEPPER* AxiPoroProblem< ELEMENT, TIMESTEPPER >::my_time_stepper_pt () inline
Access to timestepper.
   {
    return My_time_stepper_pt;
   }
set_boundary_values()
template<class ELEMENT , class TIMESTEPPER > void AxiPoroProblem< ELEMENT, TIMESTEPPER >::set_boundary_values
Set the time-dependent boundary values.
Set the time dependent boundary values.
 {
  Vector<double> x(2);
  Vector<typename TIMESTEPPER::NodeInitialConditionFctPt>
   value_fct(2);
  Vector<typename TIMESTEPPER::NodeInitialConditionFctPt>
   veloc_fct(2);
  Vector<typename TIMESTEPPER::NodeInitialConditionFctPt>
   accel_fct(2);
  // Assign values for analytical value, veloc and accel:
  value_fct[0]=&ProblemParameters::boundary_displ_0;
  value_fct[1]=&ProblemParameters::boundary_displ_1;
  veloc_fct[0]=&ProblemParameters::boundary_veloc_0;
  veloc_fct[1]=&ProblemParameters::boundary_veloc_1;
  accel_fct[0]=&ProblemParameters::boundary_accel_0;
  accel_fct[1]=&ProblemParameters::boundary_accel_1;
  // Get the nodal index at which values representing edge fluxes
  // at flux interpolation points are stored
  ELEMENT *el_pt=dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(0));
  // How many flux interpolation points do we have?
  unsigned n=el_pt->nedge_flux_interpolation_point();
  // Provide storage; null out the ones we don't need
  Vector<typename TIMESTEPPER::NodeInitialConditionFctPt>
   flux_fct(2+n,0);
  Vector<typename TIMESTEPPER::NodeInitialConditionFctPt>
   flux_ddt_fct(2+n,0);
  Vector<typename TIMESTEPPER::NodeInitialConditionFctPt>
   flux_d2dt2_fct(2+n,0);
  // Where are the flux values stored?
  Vector<unsigned> q_index(n);
  for (unsigned j=0;j<n;j++)
   {
    q_index[j]=el_pt->q_edge_index(j);
    flux_fct[q_index[j]]=&ProblemParameters::zero_fct;
    flux_ddt_fct[q_index[j]]=&ProblemParameters::zero_fct;
    flux_d2dt2_fct[q_index[j]]=&ProblemParameters::zero_fct;
   }
  TIMESTEPPER* timestepper_pt=
   dynamic_cast<TIMESTEPPER*>(time_stepper_pt());
  // Assign current (and history) values for solid displacements as well as
  // ----------------------------------------------------------------------
  // flux along pinned boundaries
  //-----------------------------
  std::vector<unsigned> pinned_boundaries;
  // Leave outer boundary traction free ("do nothing") for "real"
  // run. Pin and apply flux and displacement for validation case
  if(CommandLineArgs::command_line_flag_has_been_set("--validation"))
   {
    pinned_boundaries.push_back(0);
   }
  pinned_boundaries.push_back(1);
  pinned_boundaries.push_back(3);
  unsigned n_boundary=pinned_boundaries.size();
  for(unsigned ibound=0;ibound<n_boundary;ibound++)
   {
    // Assign current (and history) values for solid displacements
    //------------------------------------------------------------
    // (ignores the flux ones)
    //------------------------
    unsigned n_node = Bulk_mesh_pt->nboundary_node(pinned_boundaries[ibound]);
    for(unsigned i=0;i<n_node;i++)
     {
      Node* nod_pt=Bulk_mesh_pt->boundary_node_pt(pinned_boundaries[ibound],i);
      timestepper_pt->assign_initial_data_values(nod_pt,
                                                 value_fct,
                                                 veloc_fct,
                                                 accel_fct);
     }
    // Assign flux
    //------------
    // Coordinate vector
    Vector<double> x(2);
    // Get the number of elements along boundary
    unsigned n_boundary_element=
     Bulk_mesh_pt->nboundary_element(pinned_boundaries[ibound]);
    // Loop over the elements along boundary ibound
    for(unsigned e=0;e<n_boundary_element;e++)
     {
      // Upcast the current element to the actual type
      ELEMENT *el_pt=
       dynamic_cast<ELEMENT*>(Bulk_mesh_pt->
                              boundary_element_pt(pinned_boundaries[ibound],e));
      // Loop over the edges
      for(unsigned edge=0;edge<3;edge++)
       {
        // Get pointer to node that stores the edge flux dofs for this edge
        Node* nod_pt=el_pt->edge_flux_node_pt(edge);
        // Set values for the flux degrees of freedom
        if (nod_pt->is_on_boundary(pinned_boundaries[ibound]))
         {
          // Get face index of face associated with edge
          unsigned f=el_pt->face_index_of_edge(edge);
          // Build a temporary face element from which we'll extract
          // the outer unit normal
          AxisymmetricPoroelasticityTractionElement<ELEMENT>* face_el_pt=
           new AxisymmetricPoroelasticityTractionElement<ELEMENT>(el_pt,f);
          // Loop over the flux interpolation points
          unsigned n_flux_interpolation_points=
           el_pt->nedge_flux_interpolation_point();
          for(unsigned g=0;g<n_flux_interpolation_points;g++)
           {
            // Get the global coords of the flux_interpolation point
            el_pt->edge_flux_interpolation_point_global(edge,g,x);
            // Get the exact solution
            Vector<double> exact_soln(13,0.0);
            ProblemParameters::exact_soln(time(),x,exact_soln);
            // Get unit normal at this flux interpolation point
            Vector<double> s(1);
            el_pt->face_local_coordinate_of_flux_interpolation_point(edge,g,s);
            Vector<double> unit_normal(2);
            face_el_pt->outer_unit_normal(s,unit_normal);
 #ifdef PARANOID
            // Sanity check
            Vector<double> x_face(2);
            face_el_pt->interpolated_x(s,x_face);
            if ((x_face[0]-x[0])*(x_face[0]-x[0])+
                (x_face[1]-x[1])*(x_face[1]-x[1])>1.0e-3)
             {
              std::stringstream error;
              error
               << "Discrepancy in coordinate of flux interpolation point\n"
               << "(computed by bulk and face elements) for edge " << e
               << " and flux int pt " << g << "\n"
               << "Face thinks node is at: "
               << x_face[0] << " " << x_face[1] << "\n"
               << "Bulk thinks node is at: "
               << x[0] << " " << x[1] << "\n";
              throw OomphLibError(
               error.str(),
               OOMPH_CURRENT_FUNCTION,
               OOMPH_EXCEPTION_LOCATION);
             }
 #endif
            if(CommandLineArgs::command_line_flag_has_been_set("--validation"))
             {
              // Set the boundary flux -- only does the current values;
              // should really do the history values, but it's messy...
              nod_pt->set_value(q_index[g],
                                exact_soln[2]*unit_normal[0]+
                                exact_soln[3]*unit_normal[1]);
             }
            else
             {
              // assign zero
              timestepper_pt->assign_initial_data_values(nod_pt,
                                                         flux_fct,
                                                         flux_ddt_fct,
                                                         flux_d2dt2_fct);
             }
           } // End of loop over flux interpolation points
          // Don't need face element on that edge any more
          delete face_el_pt;
         } // End if for edge on required boundary
       } // End of loop over edges
     } // End of loop over boundary elements
   } // End of loop over boundaries
  }
References ProblemParameters::boundary_accel_0(), ProblemParameters::boundary_accel_1(), ProblemParameters::boundary_displ_0(), ProblemParameters::boundary_displ_1(), ProblemParameters::boundary_veloc_0(), ProblemParameters::boundary_veloc_1(), oomph::CommandLineArgs::command_line_flag_has_been_set(), e(), calibrate::error, ProblemParameters::exact_soln(), f(), i, oomph::FaceElement::interpolated_x(), oomph::Node::is_on_boundary(), j, n, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::FaceElement::outer_unit_normal(), s, oomph::Data::set_value(), plotDoE::x, and ProblemParameters::zero_fct().
set_initial_condition()
template<class ELEMENT , class TIMESTEPPER > void AxiPoroProblem< ELEMENT, TIMESTEPPER >::set_initial_condition () inline virtual
Set the initial conditions.
Reimplemented from oomph::Problem.
   {
    if(!CommandLineArgs::command_line_flag_has_been_set("--validation"))
     {
      assign_initial_values_impulsive();
     }
    else
     {
      Vector<typename TIMESTEPPER::NodeInitialConditionFctPt>
       initial_value_fct(2);
      Vector<typename TIMESTEPPER::NodeInitialConditionFctPt>
       initial_veloc_fct(2);
      Vector<typename TIMESTEPPER::NodeInitialConditionFctPt>
       initial_accel_fct(2);
      // Assign values for analytical value, veloc and accel:
      initial_value_fct[0]=&ProblemParameters::boundary_displ_0;
      initial_value_fct[1]=&ProblemParameters::boundary_displ_1;
      initial_veloc_fct[0]=&ProblemParameters::boundary_veloc_0;
      initial_veloc_fct[1]=&ProblemParameters::boundary_veloc_1;
      initial_accel_fct[0]=&ProblemParameters::boundary_accel_0;
      initial_accel_fct[1]=&ProblemParameters::boundary_accel_1;
      TIMESTEPPER* timestepper_pt=dynamic_cast<TIMESTEPPER*>(time_stepper_pt());
      unsigned n_node=Bulk_mesh_pt->nnode();
      for(unsigned n=0;n<n_node;n++)
       {
        Node *nod_pt=Bulk_mesh_pt->node_pt(n);
        timestepper_pt->assign_initial_data_values(nod_pt,
                                                   initial_value_fct,
                                                   initial_veloc_fct,
                                                   initial_accel_fct);
       }
     }
   }
References ProblemParameters::boundary_accel_0(), ProblemParameters::boundary_accel_1(), ProblemParameters::boundary_displ_0(), ProblemParameters::boundary_displ_1(), ProblemParameters::boundary_veloc_0(), ProblemParameters::boundary_veloc_1(), oomph::CommandLineArgs::command_line_flag_has_been_set(), and n.
Member Data Documentation
Bulk_mesh_pt
template<class ELEMENT , class TIMESTEPPER > TriangleMesh<ELEMENT>* AxiPoroProblem< ELEMENT, TIMESTEPPER >::Bulk_mesh_pt private
Pointer to the "bulk" mesh.
My_time_stepper_pt
template<class ELEMENT , class TIMESTEPPER > TIMESTEPPER* AxiPoroProblem< ELEMENT, TIMESTEPPER >::My_time_stepper_pt private
Surface_mesh_pt
template<class ELEMENT , class TIMESTEPPER > Mesh* AxiPoroProblem< ELEMENT, TIMESTEPPER >::Surface_mesh_pt private
Mesh for traction/pressure elements.
Trace_file
template<class ELEMENT , class TIMESTEPPER > std::ofstream AxiPoroProblem< ELEMENT, TIMESTEPPER >::Trace_file private
Trace file.
The documentation for this class was generated from the following file:
unstructured_two_d_curved.cc