MercuryDPM: oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT > Class Template Reference
oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT > Class Template Reference
#include <quarter_circle_sector_mesh.template.h>
Public Member Functions
AlgebraicRefineableQuarterCircleSectorMesh (GeomObject *wall_pt, const double &xi_lo, const double &fract_mid, const double &xi_hi, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
unsigned self_test ()
Run self-test for algebraic mesh – return 0/1 for OK/failure.
void node_update (const bool &update_all_solid_nodes=false)
void algebraic_node_update (const unsigned &t, AlgebraicNode *&node_pt)
void update_node_update (AlgebraicNode *&node_pt)
Public Member Functions inherited from oomph::AlgebraicMesh
AlgebraicMesh ()
AlgebraicMesh (const AlgebraicMesh &)=delete
Broken copy constructor.
~AlgebraicMesh ()
Broken assignment operator.
AlgebraicNode * node_pt (const unsigned long &n)
Return a pointer to the n-th global AlgebraicNode.
unsigned self_test ()
Self test: check consistentency of multiple node updates.
void add_geom_object_list_pt (GeomObject *geom_object_pt)
unsigned ngeom_object_list_pt ()
Return number of geometric objects associated with AlgebraicMesh.
GeomObject * geom_object_list_pt (const unsigned &i)
Access function to the ith GeomObject.
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Public Member Functions inherited from oomph::RefineableQuarterCircleSectorMesh< ELEMENT >
RefineableQuarterCircleSectorMesh (GeomObject *wall_pt, const double &xi_lo, const double &fract_mid, const double &xi_hi, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual ~RefineableQuarterCircleSectorMesh ()
Destructor: Empty.
Public Member Functions inherited from oomph::QuarterCircleSectorMesh< ELEMENT >
QuarterCircleSectorMesh (GeomObject *wall_pt, const double &xi_lo, const double &fract_mid, const double &xi_hi, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual ~QuarterCircleSectorMesh ()
Destructor:
GeomObject *& wall_pt ()
Access function to GeomObject representing wall.
QuarterCircleSectorDomain * domain_pt ()
Access function to domain.
QuarterCircleSectorDomain::BLSquashFctPt & bl_squash_fct_pt ()
Public Member Functions inherited from oomph::QuadMeshBase
QuadMeshBase ()
Constructor (empty)
QuadMeshBase (const QuadMeshBase &node)=delete
Broken copy constructor.
void operator= (const QuadMeshBase &)=delete
Broken assignment operator.
virtual ~QuadMeshBase ()
Destructor (empty)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::RefineableQuadMesh< ELEMENT >
RefineableQuadMesh ()
Constructor: Setup static quadtree data.
RefineableQuadMesh (const RefineableQuadMesh &dummy)=delete
Broken copy constructor.
virtual ~RefineableQuadMesh ()
Broken assignment operator.
virtual void setup_tree_forest ()
void setup_quadtree_forest ()
Public Member Functions inherited from oomph::TreeBasedRefineableMesh< ELEMENT >
TreeBasedRefineableMesh ()
Constructor, call the constructor of the base class.
TreeBasedRefineableMesh (const TreeBasedRefineableMesh &dummy)=delete
Broken copy constructor.
virtual ~TreeBasedRefineableMesh ()
Empty virtual destructor.
Public Member Functions inherited from oomph::TreeBasedRefineableMeshBase
TreeBasedRefineableMeshBase ()
Constructor.
TreeBasedRefineableMeshBase (const TreeBasedRefineableMeshBase &dummy)=delete
Broken copy constructor.
void operator= (const TreeBasedRefineableMeshBase &)=delete
Broken assignment operator.
virtual ~TreeBasedRefineableMeshBase ()
Empty Destructor:
void adapt (const Vector< double > &elemental_error)
void p_adapt (const Vector< double > &elemental_error)
void refine_uniformly (DocInfo &doc_info)
Refine mesh uniformly and doc process.
void refine_uniformly ()
Refine mesh uniformly.
void p_refine_uniformly (DocInfo &doc_info)
p-refine mesh uniformly and doc process
void p_refine_uniformly ()
p-refine mesh uniformly
unsigned unrefine_uniformly ()
void p_unrefine_uniformly (DocInfo &doc_info)
p-unrefine mesh uniformly
TreeForest * forest_pt ()
Return pointer to the Forest represenation of the mesh.
void doc_adaptivity_targets (std::ostream &outfile)
Doc the targets for mesh adaptation.
unsigned & max_refinement_level ()
Access fct for max. permissible refinement level (relative to base mesh)
unsigned & min_refinement_level ()
Access fct for min. permissible refinement level (relative to base mesh)
unsigned & max_p_refinement_level ()
unsigned & min_p_refinement_level ()
virtual void adapt_mesh (DocInfo &doc_info)
virtual void adapt_mesh ()
void p_adapt_mesh (DocInfo &doc_info)
void p_adapt_mesh ()
virtual void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
virtual void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
p-refine mesh by refining the elements identified by their numbers.
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
p-refine mesh by refining the elements identified by their pointers.
virtual void refine_base_mesh_as_in_reference_mesh (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
Refine to same degree as the reference mesh.
virtual bool refine_base_mesh_as_in_reference_mesh_minus_one (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
virtual void refine_as_in_reference_mesh (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
virtual void get_refinement_levels (unsigned &min_refinement_level, unsigned &max_refinement_level)
Get max/min refinement levels in mesh.
virtual void get_elements_at_refinement_level (unsigned &refinement_level, Vector< RefineableElement * > &level_elements)
virtual void get_refinement_pattern (Vector< Vector< unsigned >> &to_be_refined)
void refine_base_mesh (Vector< Vector< unsigned >> &to_be_refined)
Refine base mesh according to specified refinement pattern.
virtual void refine (std::ifstream &restart_file)
Refine mesh according to refinement pattern in restart file.
virtual void dump_refinement (std::ostream &outfile)
Dump refinement pattern to allow for rebuild.
virtual void read_refinement (std::ifstream &restart_file, Vector< Vector< unsigned >> &to_be_refined)
Read refinement pattern to allow for rebuild.
unsigned uniform_refinement_level_when_pruned () const
unsigned & uniform_refinement_level_when_pruned ()
Level to which the mesh was uniformly refined when it was pruned.
Public Member Functions inherited from oomph::RefineableMeshBase
bool adapt_flag ()
RefineableMeshBase ()
RefineableMeshBase (const RefineableMeshBase &dummy)=delete
Broken copy constructor.
void operator= (const RefineableMeshBase &)=delete
Broken assignment operator.
virtual ~RefineableMeshBase ()
Empty Destructor:
unsigned nrefined ()
Access fct for number of elements that were refined.
unsigned nunrefined ()
Access fct for number of elements that were unrefined.
unsigned & nrefinement_overruled ()
unsigned & max_keep_unrefined ()
ErrorEstimator *& spatial_error_estimator_pt ()
Access to spatial error estimator.
ErrorEstimator * spatial_error_estimator_pt () const
Access to spatial error estimator (const version.
double & min_permitted_error ()
double & max_permitted_error ()
double & min_error ()
double & max_error ()
DocInfo *& doc_info_pt ()
Access fct for pointer to DocInfo.
void enable_adaptation ()
Enable adaptation.
void disable_adaptation ()
Disable adaptation.
void enable_p_adaptation ()
Enable adaptation.
void disable_p_adaptation ()
Disable adaptation.
void enable_additional_synchronisation_of_hanging_nodes ()
Enable additional synchronisation of hanging nodes.
void disable_additional_synchronisation_of_hanging_nodes ()
Disable additional synchronisation of hanging nodes.
bool is_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_p_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_additional_synchronisation_of_hanging_nodes_disabled () const
Return whether additional synchronisation is enabled.
DocInfo doc_info ()
Access fct for DocInfo.
void p_unrefine_uniformly (DocInfo &doc_info)
p-unrefine mesh uniformly
Private Types
enum { Central_box , Lower_right_box , Upper_left_box }
Remesh function ids.
Private Member Functions
void node_update_in_central_box (const unsigned &t, AlgebraicNode *&node_pt)
void node_update_in_lower_right_box (const unsigned &t, AlgebraicNode *&node_pt)
void node_update_in_upper_left_box (const unsigned &t, AlgebraicNode *&node_pt)
void setup_algebraic_node_update ()
Setup algebraic update operation for all nodes.
void update_node_update_in_lower_right_box (AlgebraicNode *&node_pt)
Update algebraic update function for nodes in lower right box.
void update_node_update_in_upper_left_box (AlgebraicNode *&node_pt)
Update algebraic update function for nodes in upper left box.
Private Attributes
double Lambda_x
Fractional width of central box.
double Lambda_y
Fractional height of central box.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Member Functions inherited from oomph::TreeBasedRefineableMeshBase
void complete_hanging_nodes (const int &ncont_interpolated_values)
Complete the hanging node scheme recursively.
void complete_hanging_nodes_recursively (Node *&nod_pt, Vector< Node * > &master_nodes, Vector< double > &hang_weights, const int &ival)
Auxiliary routine for recursive hanging node completion.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Protected Attributes inherited from oomph::QuarterCircleSectorMesh< ELEMENT >
QuarterCircleSectorDomain * Domain_pt
Pointer to Domain.
GeomObject * Wall_pt
double Xi_lo
Lower limit for the (1D) coordinates along the wall.
double Fract_mid
Fraction along wall where outer ring is to be divided.
double Xi_hi
Upper limit for the (1D) coordinates along the wall.
Protected Attributes inherited from oomph::TreeBasedRefineableMeshBase
unsigned Uniform_refinement_level_when_pruned
Level to which the mesh was uniformly refined when it was pruned.
unsigned Max_refinement_level
Max. permissible refinement level (relative to base mesh)
unsigned Min_refinement_level
Min. permissible refinement level (relative to base mesh)
unsigned Max_p_refinement_level
Max. permissible p-refinement level (relative to base mesh)
unsigned Min_p_refinement_level
Min. permissible p-refinement level (relative to base mesh)
TreeForest * Forest_pt
Forest representation of the mesh.
Protected Attributes inherited from oomph::RefineableMeshBase
ErrorEstimator * Spatial_error_estimator_pt
Pointer to spatial error estimator.
double Max_permitted_error
Max. error (i.e. split elements if their error is larger)
double Min_permitted_error
Min. error (i.e. (try to) merge elements if their error is smaller)
double Min_error
Min.actual error.
double Max_error
Max. actual error.
unsigned Nrefined
Stats: Number of elements that were refined.
unsigned Nunrefined
Stats: Number of elements that were unrefined.
bool Adapt_flag
Flag that requests adaptation.
bool P_adapt_flag
Flag that requests p-adaptation.
bool Additional_synchronisation_of_hanging_nodes_not_required
Flag that disables additional synchronisation of hanging nodes.
DocInfo * Doc_info_pt
Pointer to DocInfo.
unsigned Max_keep_unrefined
unsigned Nrefinement_overruled
Detailed Description
template<class ELEMENT>
class oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >
Algebraic version of RefineableQuarterCircleSectorMesh
                     ---___
                    |      ---____
                    |              -   BOUNDARY 1
                    |               /
                    |     [2]      /  |
                    |             /     |
                    | N          /        |
                    | |_ E      /          |
     BOUNDARY 2     |-----------           |
                    |          |    [1]    |
                    |   [0]    |           |  ^
                    |          |           | / \  direction of
                    | N        |    N      |  |   Lagrangian
                    | |_ E     |    |_ E   |  |   coordinate
                    |__________|___________|  |   along wall GeomObject
                         BOUNDARY 0
Within the elements (MacroElements), the local coordinates
are such that the (E)astern direction coincides with the positive
s_0 direction,  while the (N)orther direction coincides with the positive
s_1 direction.
Domain is parametrised by three macro elements as sketched. Elements need to be derived from AlgebraicElementBase. In addition to all the refinement procedures available for RefineableQuarterCircleSectorMesh which forms the basis for this mesh, we implement algebraic node update functions for the nodes.
Member Enumeration Documentation
anonymous enum
template<class ELEMENT > anonymous enum private
Remesh function ids.
Enumerator
Central_box
Lower_right_box
Upper_left_box
     {
       Central_box,
       Lower_right_box,
       Upper_left_box
     };
Constructor & Destructor Documentation
AlgebraicRefineableQuarterCircleSectorMesh()
template<class ELEMENT > oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::AlgebraicRefineableQuarterCircleSectorMesh (GeomObject * wall_pt, const double & xi_lo, const double & fract_mid, const double & xi_hi, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Constructor: Pass pointer to geometric object, start and end coordinates on the geometric object and the fraction along which the dividing line is to be placed when updating the nodal positions, and timestepper (defaults to (Steady) default timestepper defined in Mesh). Setup the refineable mesh (by calling the constructor for the underlying RefineableQuarterCircleSectorMesh) and the algebraic update functions for nodes.
       : RefineableQuarterCircleSectorMesh<ELEMENT>(
           wall_pt, xi_lo, fract_mid, xi_hi, time_stepper_pt)
     {
 #ifdef PARANOID
       ELEMENT* el_pt = new ELEMENT;
       if (dynamic_cast<AlgebraicElementBase*>(el_pt) == 0)
       {
         std::ostringstream error_message;
         error_message << "Base class for ELEMENT in "
                       << "AlgebraicRefineableQuarterCircleSectorMesh needs"
                       << "to be of type AlgebraicElement!\n";
         error_message << "Whereas it is: typeid(el_pt).name()"
                       << typeid(el_pt).name() << std::endl;
         std::string function_name =
           " AlgebraicRefineableQuarterCircleSectorMesh::\n";
         function_name += "AlgebraicRefineableQuarterCircleSectorMesh()";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       delete el_pt;
 #endif
       // Add the geometric object to the list associated with this AlgebraicMesh
       AlgebraicMesh::add_geom_object_list_pt(wall_pt);
       // Setup algebraic node update operations
       setup_algebraic_node_update();
     }
References oomph::AlgebraicMesh::add_geom_object_list_pt(), plotDoE::name, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::setup_algebraic_node_update(), oomph::Global_string_for_annotation::string(), and oomph::QuarterCircleSectorMesh< ELEMENT >::wall_pt().
Member Function Documentation
algebraic_node_update()
template<class ELEMENT > void oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::algebraic_node_update (const unsigned & t, AlgebraicNode *& node_pt) inline virtual
Implement the algebraic node update function for a node at time level t (t=0: present; t>0: previous): Update with the node's first (default) update function.
Implements oomph::AlgebraicMesh.
     {
       // Update with the update function for the node's first (default)
       // node update fct
       unsigned id = node_pt->node_update_fct_id();
       switch (id)
       {
         case Central_box:
           // Central box
           node_update_in_central_box(t, node_pt);
           break;
         case Lower_right_box:
           // Lower right box
           node_update_in_lower_right_box(t, node_pt);
           break;
         case Upper_left_box:
           // Upper left box
           node_update_in_upper_left_box(t, node_pt);
           break;
         default:
           std::ostringstream error_message;
           error_message << "The node update fct id is " << id
                         << ", but it should only be one of " << Central_box
                         << ", " << Lower_right_box << " or " << Upper_left_box
                         << std::endl;
           std::string function_name =
             " AlgebraicRefineableQuarterCircleSectorMesh::";
           function_name += "algebraic_node_update()";
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
       }
     }
References oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::Central_box, oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::Lower_right_box, oomph::AlgebraicMesh::node_pt(), oomph::AlgebraicNode::node_update_fct_id(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update_in_central_box(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update_in_lower_right_box(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update_in_upper_left_box(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Global_string_for_annotation::string(), plotPSD::t, and oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::Upper_left_box.
node_update()
template<class ELEMENT > void oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update (const bool & update_all_solid_nodes = false) inline virtual
Resolve mesh update: Update current nodal positions via algebraic node update. [Doesn't make sense to use this mesh with SolidElements anyway, so we buffer the case if update_all_solid_nodes is set to true.]
Reimplemented from oomph::AlgebraicMesh.
     {
 #ifdef PARANOID
       if (update_all_solid_nodes)
       {
         std::string error_message =
           "Doesn't make sense to use an AlgebraicMesh with\n";
         error_message +=
           "SolidElements so specifying update_all_solid_nodes=true\n";
         error_message += "doesn't make sense either\n";
         std::string function_name =
           " AlgebraicRefineableQuarterCircleSectorMesh::";
         function_name += "node_update()";
         throw OomphLibError(
           error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       AlgebraicMesh::node_update();
     }
References oomph::AlgebraicMesh::node_update(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
node_update_in_central_box()
template<class ELEMENT > void oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update_in_central_box (const unsigned & t, AlgebraicNode *& node_pt) private
Algebraic update function for a node that is located in the central box
Algebraic update function: Update in central box according to wall shape at time level t (t=0: present; t>0: previous)
   {
 #ifdef PARANOID
     // We're updating the nodal positions (!) at time level t
     // and determine them by evaluating the wall GeomObject's
     // position at that gime level. I believe this only makes sense
     // if the t-th history value in the positional timestepper
     // actually represents previous values (rather than some
     // generalised quantity). Hence if this function is called with
     // t>nprev_values(), we issue a warning and terminate the execution.
     // It *might* be possible that the code still works correctly
     // even if this condition is violated (e.g. if the GeomObject's
     // position() function returns the appropriate "generalised"
     // position value that is required by the timestepping scheme but it's
     // probably worth flagging this up and forcing the user to manually switch
     // off this warning if he/she is 100% sure that this is kosher.
     if (t > node_pt->position_time_stepper_pt()->nprev_values())
     {
       std::string error_message =
         "Trying to  update the nodal position at a time level\n";
       error_message += "beyond the number of previous values in the nodes'\n";
       error_message += "position timestepper. This seems highly suspect!\n";
       error_message += "If you're sure the code behaves correctly\n";
       error_message += "in your application, remove this warning \n";
       error_message += "or recompile with PARNOID switched off.\n";
       std::string function_name =
         "AlgebraicRefineableQuarterCircleSectorMesh::";
       function_name += "node_update_in_central_box()",
         throw OomphLibError(
           error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Extract references for update in central box by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value(Central_box));
     // Extract geometric objects for update in central box by copy construction
     Vector<GeomObject*> geom_object_pt(
       node_pt->vector_geom_object_pt(Central_box));
     // First reference value: fractional x-position of node inside box
     double rho_x = ref_value[0];
     // Second reference value: fractional y-position of node inside box
     double rho_y = ref_value[1];
     // Wall position in bottom right corner:
     // Pointer to wall element:
     GeomObject* obj_br_pt = geom_object_pt[0];
     // Eulerian dimension
     unsigned n_dim = obj_br_pt->ndim();
     // Local coordinate:
     Vector<double> s_br(1);
     s_br[0] = ref_value[2];
     // Get wall position
     Vector<double> r_br(n_dim);
     obj_br_pt->position(t, s_br, r_br);
     // Wall position in top left corner:
     // Pointer to wall element:
     GeomObject* obj_tl_pt = geom_object_pt[1];
     // Local coordinate:
     Vector<double> s_tl(1);
     s_tl[0] = ref_value[3];
     Vector<double> r_tl(n_dim);
     obj_tl_pt->position(t, s_tl, r_tl);
     // Assign new nodal coordinate
     node_pt->x(t, 0) = r_br[0] * Lambda_x * rho_x;
     node_pt->x(t, 1) = r_tl[1] * Lambda_y * rho_y;
   }
References oomph::GeomObject::ndim(), oomph::TimeStepper::nprev_values(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::GeomObject::position(), oomph::Node::position_time_stepper_pt(), oomph::Global_string_for_annotation::string(), plotPSD::t, oomph::AlgebraicNode::vector_geom_object_pt(), oomph::AlgebraicNode::vector_ref_value(), and oomph::Node::x().
Referenced by oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::algebraic_node_update().
node_update_in_lower_right_box()
template<class ELEMENT > void oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update_in_lower_right_box (const unsigned & t, AlgebraicNode *& node_pt) private
Algebraic update function for a node that is located in the lower right box
Algebraic update function: Update in lower right box according to wall shape at time level t (t=0: present; t>0: previous)
   {
 #ifdef PARANOID
     // We're updating the nodal positions (!) at time level t
     // and determine them by evaluating the wall GeomObject's
     // position at that gime level. I believe this only makes sense
     // if the t-th history value in the positional timestepper
     // actually represents previous values (rather than some
     // generalised quantity). Hence if this function is called with
     // t>nprev_values(), we issue a warning and terminate the execution.
     // It *might* be possible that the code still works correctly
     // even if this condition is violated (e.g. if the GeomObject's
     // position() function returns the appropriate "generalised"
     // position value that is required by the timestepping scheme but it's
     // probably worth flagging this up and forcing the user to manually switch
     // off this warning if he/she is 100% sure that this is kosher.
     if (t > node_pt->position_time_stepper_pt()->nprev_values())
     {
       std::string error_message =
         "Trying to update the nodal position at a time level";
       error_message += "beyond the number of previous values in the nodes'";
       error_message += "position timestepper. This seems highly suspect!";
       error_message += "If you're sure the code behaves correctly";
       error_message += "in your application, remove this warning ";
       error_message += "or recompile with PARNOID switched off.";
       std::string function_name =
         "AlgebraicRefineableQuarterCircleSectorMesh::";
       function_name += "node_update_in_lower_right_box()",
         throw OomphLibError(
           error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Extract references for update in central box by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value(Lower_right_box));
     // Extract geometric objects for update in central box by copy construction
     Vector<GeomObject*> geom_object_pt(
       node_pt->vector_geom_object_pt(Lower_right_box));
     // First reference value: fractional s0-position of node inside box
     double rho_0 = ref_value[0];
     // Second reference value: fractional s1-position of node inside box
     double rho_1 = ref_value[1];
     // Wall position in bottom right corner:
     // Pointer to wall element:
     GeomObject* obj_br_pt = geom_object_pt[0];
     // Eulerian dimension
     unsigned n_dim = obj_br_pt->ndim();
     // Local coordinate:
     Vector<double> s_br(1);
     s_br[0] = ref_value[2];
     // Get wall position
     Vector<double> r_br(n_dim);
     obj_br_pt->position(t, s_br, r_br);
     // Wall position in top left corner:
     // Pointer to wall element:
     GeomObject* obj_tl_pt = geom_object_pt[1];
     // Local coordinate:
     Vector<double> s_tl(1);
     s_tl[0] = ref_value[3];
     Vector<double> r_tl(n_dim);
     obj_tl_pt->position(t, s_tl, r_tl);
     // Position of the corner of the central box
     Vector<double> r_box(n_dim);
     r_box[0] = Lambda_x * r_br[0];
     r_box[1] = Lambda_y * r_tl[1];
     // Position Vector to left end of box
     Vector<double> r_left(n_dim);
     r_left[0] = Lambda_x * r_br[0] + rho_1 * (r_box[0] - Lambda_x * r_br[0]);
     r_left[1] = Lambda_x * r_br[1] + rho_1 * (r_box[1] - Lambda_x * r_br[1]);
     // Wall position
     // Pointer to wall element:
     GeomObject* obj_wall_pt = geom_object_pt[2];
     // Local coordinate:
     Vector<double> s_wall(1);
     s_wall[0] = ref_value[4];
     Vector<double> r_wall(n_dim);
     obj_wall_pt->position(t, s_wall, r_wall);
     // Assign new nodal coordinate
     node_pt->x(t, 0) = r_left[0] + rho_0 * (r_wall[0] - r_left[0]);
     node_pt->x(t, 1) = r_left[1] + rho_0 * (r_wall[1] - r_left[1]);
   }
References oomph::GeomObject::ndim(), oomph::TimeStepper::nprev_values(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::GeomObject::position(), oomph::Node::position_time_stepper_pt(), oomph::Global_string_for_annotation::string(), plotPSD::t, oomph::AlgebraicNode::vector_geom_object_pt(), oomph::AlgebraicNode::vector_ref_value(), and oomph::Node::x().
Referenced by oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::algebraic_node_update().
node_update_in_upper_left_box()
template<class ELEMENT > void oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update_in_upper_left_box (const unsigned & t, AlgebraicNode *& node_pt) private
Algebraic update function for a node that is located in the upper left box
Algebraic update function: Update in upper left box according to wall shape at time level t (t=0: present; t>0: previous)
   {
 #ifdef PARANOID
     // We're updating the nodal positions (!) at time level t
     // and determine them by evaluating the wall GeomObject's
     // position at that gime level. I believe this only makes sense
     // if the t-th history value in the positional timestepper
     // actually represents previous values (rather than some
     // generalised quantity). Hence if this function is called with
     // t>nprev_values(), we issue a warning and terminate the execution.
     // It *might* be possible that the code still works correctly
     // even if this condition is violated (e.g. if the GeomObject's
     // position() function returns the appropriate "generalised"
     // position value that is required by the timestepping scheme but it's
     // probably worth flagging this up and forcing the user to manually switch
     // off this warning if he/she is 100% sure that this is kosher.
     if (t > node_pt->position_time_stepper_pt()->nprev_values())
     {
       std::string error_message =
         "Trying to update the nodal position at a time level";
       error_message += "beyond the number of previous values in the nodes'";
       error_message += "position timestepper. This seems highly suspect!";
       error_message += "If you're sure the code behaves correctly";
       error_message += "in your application, remove this warning ";
       error_message += "or recompile with PARNOID switched off.";
       std::string function_name =
         "AlgebraicRefineableQuarterCircleSectorMesh::";
       function_name += "node_update_in_upper_left_box()";
       throw OomphLibError(
         error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Extract references for update in central box by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value(Upper_left_box));
     // Extract geometric objects for update  in central box by copy construction
     Vector<GeomObject*> geom_object_pt(
       node_pt->vector_geom_object_pt(Upper_left_box));
     // First reference value: fractional s0-position of node inside box
     double rho_0 = ref_value[0];
     // Second  reference value: fractional s1-position of node inside box
     double rho_1 = ref_value[1];
     // Wall position in bottom right corner:
     // Pointer to wall element:
     GeomObject* obj_br_pt = geom_object_pt[0];
     // Eulerian dimension
     unsigned n_dim = obj_br_pt->ndim();
     // Local coordinate:
     Vector<double> s_br(1);
     s_br[0] = ref_value[2];
     // Get wall position
     Vector<double> r_br(n_dim);
     obj_br_pt->position(t, s_br, r_br);
     // Wall position in top left corner:
     // Pointer to wall element:
     GeomObject* obj_tl_pt = node_pt->geom_object_pt(1);
     // Local coordinate:
     Vector<double> s_tl(1);
     s_tl[0] = node_pt->ref_value(3);
     Vector<double> r_tl(n_dim);
     obj_tl_pt->position(t, s_tl, r_tl);
     // Position of the corner of the central box
     Vector<double> r_box(n_dim);
     r_box[0] = Lambda_x * r_br[0];
     r_box[1] = Lambda_y * r_tl[1];
     // Position Vector to top face of central box
     Vector<double> r_top(n_dim);
     r_top[0] = Lambda_y * r_tl[0] + rho_0 * (r_box[0] - Lambda_y * r_tl[0]);
     r_top[1] = Lambda_y * r_tl[1] + rho_0 * (r_box[1] - Lambda_y * r_tl[1]);
     // Wall position
     // Pointer to wall element:
     GeomObject* obj_wall_pt = node_pt->geom_object_pt(2);
     // Local coordinate:
     Vector<double> s_wall(1);
     s_wall[0] = node_pt->ref_value(4);
     Vector<double> r_wall(n_dim);
     obj_wall_pt->position(t, s_wall, r_wall);
     // Assign new nodal coordinate
     node_pt->x(t, 0) = r_top[0] + rho_1 * (r_wall[0] - r_top[0]);
     node_pt->x(t, 1) = r_top[1] + rho_1 * (r_wall[1] - r_top[1]);
   }
References oomph::AlgebraicNode::geom_object_pt(), oomph::GeomObject::ndim(), oomph::TimeStepper::nprev_values(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::GeomObject::position(), oomph::Node::position_time_stepper_pt(), oomph::AlgebraicNode::ref_value(), oomph::Global_string_for_annotation::string(), plotPSD::t, oomph::AlgebraicNode::vector_geom_object_pt(), oomph::AlgebraicNode::vector_ref_value(), and oomph::Node::x().
Referenced by oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::algebraic_node_update().
self_test()
template<class ELEMENT > unsigned oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::self_test () inline
Run self-test for algebraic mesh – return 0/1 for OK/failure.
     {
       return AlgebraicMesh::self_test();
     }
References oomph::AlgebraicMesh::self_test().
setup_algebraic_node_update()
template<class ELEMENT > void oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::setup_algebraic_node_update private
Setup algebraic update operation for all nodes.
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Setup algebraic update operation, based on individual blocks. Mesh is suspended from the ‘wall’ GeomObject pointed to by wall_pt. The lower right corner of the mesh is located at the wall's coordinate xi_lo, the upper left corner at xi_hi; The dividing line between the two blocks at the outer ring is located at the fraction fract_mid between these two coordinates. Node updating strategy:
the shape of the central box remains rectangular; the position of its top right corner is located at a fixed fraction of the width and height of the domain. Nodes in this region are located at fixed horizontal and vertical fractions of the box.
Nodes in the two outer "ring" elements (bottom right and top left) are located on straight lines running from the edges of the central box to the outer wall.
   {
 #ifdef PARANOID
     AlgebraicElementBase* central_box_pt =
       dynamic_cast<AlgebraicElementBase*>(Mesh::element_pt(0));
     if (central_box_pt == 0)
     {
       std::ostringstream error_message;
       error_message
         << "Element in AlgebraicRefineableQuarterCircleSectorMesh must be\n ";
       error_message << "derived from AlgebraicElementBase\n";
       error_message << "but it is of type:  "
                     << typeid(Mesh::element_pt(0)).name() << std::endl;
       std::string function_name =
         "AlgebraicRefineableQuarterCircleSectorMesh::";
       function_name += "setup_algebraic_node_update()";
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Number of nodes in elements
     unsigned nnodes = Mesh::finite_element_pt(0)->nnode();
     // Coordinates of central box
     double x_box = Mesh::finite_element_pt(0)->node_pt(nnodes - 1)->x(0);
     double y_box = Mesh::finite_element_pt(0)->node_pt(nnodes - 1)->x(1);
     // Get wall position in bottom right corner
     Vector<double> r_br(2);
     Vector<double> xi(1);
     xi[0] = QuarterCircleSectorMesh<ELEMENT>::Xi_lo;
     QuarterCircleSectorMesh<ELEMENT>::Wall_pt->position(xi, r_br);
     // Establish fractional width of central box
     Lambda_x = x_box / r_br[0];
     // Find corresponding wall element/local coordinate
     GeomObject* obj_br_pt;
     Vector<double> s_br(1);
     this->Wall_pt->locate_zeta(xi, obj_br_pt, s_br);
     obj_br_pt->position(s_br, r_br);
     // Get wall position in top left corner
     Vector<double> r_tl(2);
     xi[0] = QuarterCircleSectorMesh<ELEMENT>::Xi_hi;
     QuarterCircleSectorMesh<ELEMENT>::Wall_pt->position(xi, r_tl);
     // Establish fractional height of central box
     Lambda_y = y_box / r_tl[1];
     // Find corresponding wall element/local coordinate
     GeomObject* obj_tl_pt;
     Vector<double> s_tl(1);
     this->Wall_pt->locate_zeta(xi, obj_tl_pt, s_tl);
     // Element 0: central box
     //-----------------------
     {
       unsigned ielem = 0;
       FiniteElement* el_pt = Mesh::finite_element_pt(ielem);
       // Loop over all nodes in the element and give them the update
       // info appropriate for the current element
       for (unsigned jnod = 0; jnod < nnodes; jnod++)
       {
         // Nodal coordinates in undeformed mesh
         double x = Mesh::finite_element_pt(ielem)->node_pt(jnod)->x(0);
         double y = Mesh::finite_element_pt(ielem)->node_pt(jnod)->x(1);
         // The update function requires two geometric objects
         Vector<GeomObject*> geom_object_pt(2);
         // The update function requires four parameters:
         Vector<double> ref_value(4);
         // First reference value: fractional x-position inside box
         ref_value[0] = x / x_box;
         // Second reference value: fractional y-position inside box
         ref_value[1] = y / y_box;
         // Wall element at bottom right end of wall mesh:
         geom_object_pt[0] = obj_br_pt;
         // Local coordinate in this wall element (Note:
         // we'll have to recompute this reference
         // when the mesh is refined  as we might fall off the element otherwise)
         ref_value[2] = s_br[0];
         // Wall element at top left end of wall mesh:
         geom_object_pt[1] = obj_tl_pt;
         // Local coordinate in this wall element. Note:
         // we'll have to recompute this reference
         // when the mesh is refined  as we might fall off the element otherwise)
         ref_value[3] = s_tl[0];
         // Setup algebraic update for node: Pass update information
         dynamic_cast<AlgebraicNode*>(el_pt->node_pt(jnod))
           ->add_node_update_info(Central_box, // enumerated ID
                                  this, // mesh
                                  geom_object_pt, // vector of geom objects
                                  ref_value); // vector of ref. values
       }
     }
     // Element 1: Bottom right box
     //----------------------------
     {
       unsigned ielem = 1;
       FiniteElement* el_pt = Mesh::finite_element_pt(ielem);
       // Loop over all nodes in the element and give them the update
       // info appropriate for the current element
       // Double loop over nodes
       unsigned nnod_lin =
         dynamic_cast<ELEMENT*>(Mesh::finite_element_pt(ielem))->nnode_1d();
       for (unsigned i0 = 0; i0 < nnod_lin; i0++)
       {
         // Fraction in the s_0-direction
         double rho_0 = double(i0) / double(nnod_lin - 1);
         for (unsigned i1 = 0; i1 < nnod_lin; i1++)
         {
           // Fraction in the s_1-direction
           double rho_1 = double(i1) / double(nnod_lin - 1);
           // Node number
           unsigned jnod = i0 + i1 * nnod_lin;
           // The update function requires three geometric objects
           Vector<GeomObject*> geom_object_pt(3);
           // The update function requires five parameters:
           Vector<double> ref_value(5);
           // First reference value: fractional s0-position inside box
           ref_value[0] = rho_0;
           // Second reference value: fractional s1-position inside box
           ref_value[1] = rho_1;
           // Wall element at bottom right end of wall mesh:
           geom_object_pt[0] = obj_br_pt;
           // Local coordinate in this wall element. Note:
           // We'll have to recompute this reference
           // when the mesh is refined  as we might fall off the element
           // otherwise
           ref_value[2] = s_br[0];
           // Wall element at top left end of wall mesh:
           geom_object_pt[1] = obj_tl_pt;
           // Local coordinate in this wall element. Note:
           // We'll have to recompute this reference
           // when the mesh is refined  as we might fall off the element
           // otherwise
           ref_value[3] = s_tl[0];
           // Reference point on wall
           Vector<double> xi_wall(1);
           xi_wall[0] = QuarterCircleSectorMesh<ELEMENT>::Xi_lo +
                        rho_1 * QuarterCircleSectorMesh<ELEMENT>::Fract_mid *
                          (QuarterCircleSectorMesh<ELEMENT>::Xi_hi -
                           QuarterCircleSectorMesh<ELEMENT>::Xi_lo);
           // Identify wall element number and local coordinate of
           // reference point on wall
           GeomObject* obj_wall_pt;
           Vector<double> s_wall(1);
           this->Wall_pt->locate_zeta(xi_wall, obj_wall_pt, s_wall);
           // Wall element at that contians reference point:
           geom_object_pt[2] = obj_wall_pt;
           // Local coordinate in this wall element. Note:
           // We'll have to recompute this reference
           // when the mesh is refined  as we might fall off the element
           // otherwise
           ref_value[4] = s_wall[0];
           // Setup algebraic update for node: Pass update information
           dynamic_cast<AlgebraicNode*>(el_pt->node_pt(jnod))
             ->add_node_update_info(Lower_right_box, // enumerated ID
                                    this, // mesh
                                    geom_object_pt, // vector of geom objects
                                    ref_value); // vector of ref. vals
         }
       }
     }
     // Element 2: Top left box
     //---------------------------
     {
       unsigned ielem = 2;
       FiniteElement* el_pt = Mesh::finite_element_pt(ielem);
       // Double loop over nodes
       unsigned nnod_lin =
         dynamic_cast<ELEMENT*>(Mesh::finite_element_pt(ielem))->nnode_1d();
       for (unsigned i0 = 0; i0 < nnod_lin; i0++)
       {
         // Fraction in the s_0-direction
         double rho_0 = double(i0) / double(nnod_lin - 1);
         for (unsigned i1 = 0; i1 < nnod_lin; i1++)
         {
           // Fraction in the s_1-direction
           double rho_1 = double(i1) / double(nnod_lin - 1);
           // Node number
           unsigned jnod = i0 + i1 * nnod_lin;
           // The update function requires three geometric objects
           Vector<GeomObject*> geom_object_pt(3);
           // The update function requires five parameters:
           Vector<double> ref_value(5);
           // First reference value: fractional s0-position inside box
           ref_value[0] = rho_0;
           // Second  reference value: fractional s1-position inside box
           ref_value[1] = rho_1;
           // Wall element at bottom right end of wall mesh:
           geom_object_pt[0] = obj_br_pt;
           // Local coordinate in this wall element. Note:
           // We'll have to recompute this reference
           // when the mesh is refined  as we might fall off the element
           // otherwise
           ref_value[2] = s_br[0];
           // Wall element at top left end of wall mesh:
           geom_object_pt[1] = obj_tl_pt;
           // Local coordinate in this wall element. Note:
           // We'll have to recompute this reference
           // when the mesh is refined  as we might fall off the element
           // otherwise
           ref_value[3] = s_tl[0];
           // Reference point on wall
           Vector<double> xi_wall(1);
           xi_wall[0] = QuarterCircleSectorMesh<ELEMENT>::Xi_hi +
                        rho_0 *
                          (1.0 - QuarterCircleSectorMesh<ELEMENT>::Fract_mid) *
                          (QuarterCircleSectorMesh<ELEMENT>::Xi_lo -
                           QuarterCircleSectorMesh<ELEMENT>::Xi_hi);
           // Identify wall element number and local coordinate of
           // reference point on wall
           GeomObject* obj_wall_pt;
           Vector<double> s_wall(1);
           this->Wall_pt->locate_zeta(xi_wall, obj_wall_pt, s_wall);
           // Wall element at that contians reference point:
           geom_object_pt[2] = obj_wall_pt;
           // Local coordinate in this wall element. Note:
           // We'll have to recompute this reference
           // when the mesh is refined  as we might fall off the element
           // otherwise
           ref_value[4] = s_wall[0];
           // Setup algebraic update for node: Pass update information
           dynamic_cast<AlgebraicNode*>(el_pt->node_pt(jnod))
             ->add_node_update_info(Upper_left_box, // Enumerated ID
                                    this, // mesh
                                    geom_object_pt, // vector of geom objects
                                    ref_value); // vector of ref. vals
         }
       }
     }
   }
References oomph::Mesh::element_pt(), oomph::Mesh::finite_element_pt(), plotDoE::name, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::GeomObject::position(), oomph::Global_string_for_annotation::string(), plotDoE::x, oomph::Node::x(), and y.
Referenced by oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::AlgebraicRefineableQuarterCircleSectorMesh().
update_node_update()
template<class ELEMENT > void oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::update_node_update (AlgebraicNode *& node_pt) inline virtual
Update the node update info for specified algebraic node following any spatial mesh adaptation.
Implements oomph::AlgebraicMesh.
     {
       // Get all node update fct for this node  (resizes internally)
       Vector<int> id;
       node_pt->node_update_fct_id(id);
       // Loop over all update fcts
       unsigned n_update = id.size();
       for (unsigned i = 0; i < n_update; i++)
       {
         switch (id[i])
         {
           case Central_box:
             // Central box: no update
             break;
           case Lower_right_box:
             // Lower right box
             update_node_update_in_lower_right_box(node_pt);
             break;
           case Upper_left_box:
             // Upper left box
             update_node_update_in_upper_left_box(node_pt);
             break;
           default:
             // Never get here....
             std::ostringstream error_message;
             error_message << "Node update fct id is " << id[i]
                           << ", but it should only be one of" << Central_box
                           << ", " << Lower_right_box << " or " << Upper_left_box
                           << std::endl;
             std::string function_name =
               " AlgebraicRefineableQuarterCircleSectorMesh::";
             function_name += "update_node_update()";
             throw OomphLibError(error_message.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
         }
       }
     }
References oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::Central_box, i, oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::Lower_right_box, oomph::AlgebraicMesh::node_pt(), oomph::AlgebraicNode::node_update_fct_id(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Global_string_for_annotation::string(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::update_node_update_in_lower_right_box(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::update_node_update_in_upper_left_box(), and oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::Upper_left_box.
update_node_update_in_lower_right_box()
template<class ELEMENT > void oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::update_node_update_in_lower_right_box (AlgebraicNode *& node_pt) private
Update algebraic update function for nodes in lower right box.
Update algebraic node update function for nodes in lower right box
   {
     // Extract references for update in central box by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value(Lower_right_box));
     // Extract geometric objects for updatein central box by copy construction
     Vector<GeomObject*> geom_object_pt(
       node_pt->vector_geom_object_pt(Lower_right_box));
     // Now remove the update  info to allow overwriting below
     node_pt->kill_node_update_info(Lower_right_box);
     // Fixed reference value: Start coordinate on wall
     double xi_lo = QuarterCircleSectorMesh<ELEMENT>::Xi_lo;
     // Fixed reference value: Fractional position of dividing line
     double fract_mid = QuarterCircleSectorMesh<ELEMENT>::Fract_mid;
     // Fixed reference value: End coordinate on wall
     double xi_hi = QuarterCircleSectorMesh<ELEMENT>::Xi_hi;
     // Second reference value: fractional s1-position of node inside box
     double rho_1 = ref_value[1];
     // Update reference to wall point in bottom right corner
     //------------------------------------------------------
     // Wall position in bottom right corner:
     Vector<double> xi(1);
     xi[0] = xi_lo;
     // Find corresponding wall element/local coordinate
     GeomObject* obj_br_pt;
     Vector<double> s_br(1);
     this->Wall_pt->locate_zeta(xi, obj_br_pt, s_br);
     // Wall element at bottom right end of wall mesh:
     geom_object_pt[0] = obj_br_pt;
     // Local coordinate in this wall element. Note:
     // We'll have to recompute this reference
     // when the mesh is refined  as we might fall off the element otherwise
     ref_value[2] = s_br[0];
     // Update reference to wall point in upper left corner
     //----------------------------------------------------
     // Wall position in top left corner
     xi[0] = xi_hi;
     // Find corresponding wall element/local coordinate
     GeomObject* obj_tl_pt;
     Vector<double> s_tl(1);
     this->Wall_pt->locate_zeta(xi, obj_tl_pt, s_tl);
     // Wall element at top left end of wall mesh:
     geom_object_pt[1] = obj_tl_pt;
     // Local coordinate in this wall element. Note:
     // We'll have to recompute this reference
     // when the mesh is refined  as we might fall off the element otherwise
     ref_value[3] = s_tl[0];
     // Update reference to reference point on wall
     //--------------------------------------------
     // Reference point on wall
     Vector<double> xi_wall(1);
     xi_wall[0] = xi_lo + rho_1 * fract_mid * (xi_hi - xi_lo);
     // Identify wall element number and local coordinate of
     // reference point on wall
     GeomObject* obj_wall_pt;
     Vector<double> s_wall(1);
     this->Wall_pt->locate_zeta(xi_wall, obj_wall_pt, s_wall);
     // Wall element at that contians reference point:
     geom_object_pt[2] = obj_wall_pt;
     // Local coordinate in this wall element. Note:
     // We'll have to recompute this reference
     // when the mesh is refined  as we might fall off the element otherwise
     ref_value[4] = s_wall[0];
     // Setup algebraic update for node: Pass update information
     node_pt->add_node_update_info(Lower_right_box, // Enumerated ID
                                   this, // mesh
                                   geom_object_pt, // vector of geom objects
                                   ref_value); // vector of ref. vals
   }
References oomph::AlgebraicNode::add_node_update_info(), oomph::AlgebraicNode::kill_node_update_info(), oomph::AlgebraicNode::vector_geom_object_pt(), and oomph::AlgebraicNode::vector_ref_value().
Referenced by oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::update_node_update().
update_node_update_in_upper_left_box()
template<class ELEMENT > void oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::update_node_update_in_upper_left_box (AlgebraicNode *& node_pt) private
Update algebraic update function for nodes in upper left box.
Update algebraic node update function for nodes in upper left box
   {
     // Extract references for update in central box by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value(Upper_left_box));
     // Extract geometric objects for update in central box by copy construction
     Vector<GeomObject*> geom_object_pt(
       node_pt->vector_geom_object_pt(Upper_left_box));
     // Now remove the update info to allow overwriting below
     node_pt->kill_node_update_info(Upper_left_box);
     // Fixed reference value: Start coordinate on wall
     double xi_lo = QuarterCircleSectorMesh<ELEMENT>::Xi_lo;
     // Fixed reference value:  Fractional position of dividing line
     double fract_mid = QuarterCircleSectorMesh<ELEMENT>::Fract_mid;
     // Fixed reference value: End coordinate on wall
     double xi_hi = QuarterCircleSectorMesh<ELEMENT>::Xi_hi;
     // First reference value: fractional s0-position of node inside box
     double rho_0 = ref_value[0];
     // Update reference to wall point in bottom right corner
     //------------------------------------------------------
     // Wall position in bottom right corner:
     Vector<double> xi(1);
     xi[0] = xi_lo;
     // Find corresponding wall element/local coordinate
     GeomObject* obj_br_pt;
     Vector<double> s_br(1);
     this->Wall_pt->locate_zeta(xi, obj_br_pt, s_br);
     // Wall element at bottom right end of wall mesh:
     geom_object_pt[0] = obj_br_pt;
     // Local coordinate in this wall element. Note:
     // We'll have to recompute this reference
     // when the mesh is refined  as we might fall off the element otherwise
     ref_value[2] = s_br[0];
     // Update reference to wall point in upper left corner
     //----------------------------------------------------
     // Wall position in top left corner
     xi[0] = xi_hi;
     // Find corresponding wall element/local coordinate
     GeomObject* obj_tl_pt;
     Vector<double> s_tl(1);
     this->Wall_pt->locate_zeta(xi, obj_tl_pt, s_tl);
     // Wall element at top left end of wall mesh:
     geom_object_pt[1] = obj_tl_pt;
     // Local coordinate in this wall element. Note:
     // We'll have to recompute this reference
     // when the mesh is refined  as we might fall off the element otherwise
     ref_value[3] = s_tl[0];
     // Update reference to reference point on wall
     //--------------------------------------------
     // Reference point on wall
     Vector<double> xi_wall(1);
     xi_wall[0] = xi_hi + rho_0 * (1.0 - fract_mid) * (xi_lo - xi_hi);
     // Identify reference point on wall
     GeomObject* obj_wall_pt;
     Vector<double> s_wall(1);
     this->Wall_pt->locate_zeta(xi_wall, obj_wall_pt, s_wall);
     // Wall element at that contians reference point:
     geom_object_pt[2] = obj_wall_pt;
     // Local coordinate in this wall element. Note:
     // We'll have to recompute this reference
     // when the mesh is refined  as we might fall off the element otherwise
     ref_value[4] = s_wall[0];
     // Setup algebraic update for node: Pass update information
     node_pt->add_node_update_info(Upper_left_box, // Enumerated ID
                                   this, // mesh
                                   geom_object_pt, // vector of geom objects
                                   ref_value); // vector of ref. vals
   }
References oomph::AlgebraicNode::add_node_update_info(), oomph::AlgebraicNode::kill_node_update_info(), oomph::AlgebraicNode::vector_geom_object_pt(), and oomph::AlgebraicNode::vector_ref_value().
Referenced by oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::update_node_update().
Member Data Documentation
Lambda_x
template<class ELEMENT > double oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::Lambda_x private
Fractional width of central box.
Lambda_y
template<class ELEMENT > double oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::Lambda_y private
Fractional height of central box.
The documentation for this class was generated from the following files:
quarter_circle_sector_mesh.template.h
quarter_circle_sector_mesh.template.cc