MercuryDPM: two_d_poisson_stored_shape_fcts.cc File Reference
two_d_poisson_stored_shape_fcts.cc File Reference
#include "generic.h"
#include "poisson.h"
#include "meshes/simple_rectangular_quadmesh.h"
Classes
class PoissonProblem< ELEMENT >
Micky mouse Poisson problem.
Namespaces
TanhSolnForPoisson
Namespace for exact solution for Poisson equation with "sharp step".
Functions
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForPoisson::source_function (const Vector< double > &x, double &source)
Source function required to make the solution above an exact solution.
int main (int argc, char *argv[])
Driver code for 2D Poisson problem.
Function Documentation
main()
int main (int argc , char * argv[])
Driver code for 2D Poisson problem.
 {
  // Number of uniform refinements relative to a 2x2 base mesh
  unsigned n_refine;
  // Get number of refinement levels from command line or use default
  if (argc==1)
   {
    n_refine=6; //5
   }
  else if (argc==2)
   {
    n_refine=atoi(argv[1]);
   }
  else
   {
    std::string error_message =
     "Wrong number of input arguments. The options are: \n";
    error_message +=
     "No args: Default number of refinements\n";
    error_message +=
     "One arg: Required number of refinements\n";
    throw OomphLibError(error_message,
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
   }
   cout << sizeof(Shape) << std::endl;
   cout << sizeof(DShape) << std::endl;
  // Create label for output
  //------------------------
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory("RESLT");
  // Step number
  doc_info.number()=0;
  // Set the orientation of the "step" to 45 degrees
  TanhSolnForPoisson::TanPhi=1.0;
  // Initial value for the steepness of the "step"
  TanhSolnForPoisson::Alpha=1.0;
  //Set up the problem with normal Poisson elements
  //-----------------------------------------------
  {
   //  Initialise timers
   clock_t t_start = clock();
   // Create the problem with 2D nine-node elements from the
   // QPoissonElement family. Pass pointer to source function
   // and number of refinements required
   PoissonProblem<QPoissonElement<2,3> >
    problem(&TanhSolnForPoisson::source_function,n_refine);
   // Finish/doc timing
   clock_t t_end = clock();
   double total_time=double(t_end-t_start)/CLOCKS_PER_SEC;
   cout << std::endl;
   cout << "======================================================= " << std::endl;
   cout << "Total time for Problem setup [sec]: " << total_time << std::endl;
   cout << "======================================================= " << std::endl;
   cout << std::endl;
   // Run problem
   problem.run_it(doc_info);
  }
  //Set up the problem with Poisson elements with storable shape fcts
  //-----------------------------------------------------------------
  {
   //  Initialise timers
   clock_t t_start = clock();
   typedef StorableShapeElement<QPoissonElement<2,3> >  ELEMENT;
   // Create the problem with 2D nine-node elements from the
   // QPoissonElement family. Pass pointer to source function
   // and number of refinements required
   PoissonProblem<ELEMENT>
    problem(&TanhSolnForPoisson::source_function,n_refine);
   // Finish/doc timing
   clock_t t_end = clock();
   double total_time=double(t_end-t_start)/CLOCKS_PER_SEC;
   cout << std::endl;
   cout << "================================================================= "
        << std::endl;
   cout << "Total time for Problem setup with storable shape fcts [sec]: "
        << total_time << std::endl;
   cout << "================================================================= "
        << std::endl;
   cout << std::endl;
   // Run problem with nothing stored (the default)
   //----------------------------------------------
   cout << "================================================================= "
        << std::endl;
   cout << "No shape functions actually stored                                "
        << std::endl;
   cout << "================================================================= "
        << std::endl << std::endl;
   problem.run_it(doc_info);
   // Store the derivatives w.r.t. to the Eulerian coordinates
   //-------------------------------------------------------------
   //  Initialise timers
   t_start = clock();
   unsigned nelem=problem.mesh_pt()->nelement();
   for (unsigned e=0;e<nelem;e++)
    {
     dynamic_cast<ELEMENT*>(problem.mesh_pt()->element_pt(e))
      ->pre_compute_dshape_eulerian_at_knots();
    }
   // Finish/doc timing
   t_end = clock();
   total_time=double(t_end-t_start)/CLOCKS_PER_SEC;
   cout << std::endl;
   cout << "================================================================= "
        << std::endl;
   cout << "Total time for pre-calculation of shape functions and derivatives "
        << std::endl;
   cout << total_time << " sec" <<  std::endl;
   cout << "================================================================= "
        << std::endl;
   cout << std::endl;
   //Now run the problem
   problem.run_it(doc_info);
   // Set them all to refer to the first elements
   //-------------------------------------------------------------
   //  Initialise timers
   t_start = clock();
   for (unsigned e=1;e<nelem;e++)
    {
     dynamic_cast<ELEMENT*>(problem.mesh_pt()->element_pt(e))
      ->set_dshape_eulerian_stored_from_element(
       dynamic_cast<ELEMENT*>(problem.mesh_pt()->element_pt(0)));
    }
   // Finish/doc timing
   t_end = clock();
   total_time=double(t_end-t_start)/CLOCKS_PER_SEC;
   cout << std::endl;
   cout << "================================================================= "
        << std::endl;
   cout << "Total time for assignment of shape functions and derivatives from "
        << std::endl << "the first element: " << total_time << " sec" <<  std::endl;
   cout << "================================================================= "
        << std::endl;
   cout << std::endl;
   problem.run_it(doc_info);
  }
 } //end of main
References TanhSolnForPoisson::Alpha, e(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, problem, oomph::DocInfo::set_directory(), TanhSolnForPoisson::source_function(), oomph::Global_string_for_annotation::string(), and TanhSolnForPoisson::TanPhi.