MercuryDPM: Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device > Struct Template Reference
#include <TensorAssign.h>
Public Types
enum {
IsAligned , PacketAccess , BlockAccess , PreferBlockAccess ,
RawAccess = TensorEvaluator<LeftArgType, Device>::RawAccess
}
typedef TensorAssignOp< LeftArgType, RightArgType > XprType
typedef XprType::Index Index
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef TensorEvaluator< RightArgType, Device >::Dimensions Dimensions
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorBlockDescriptor< NumDims, Index > TensorBlockDesc
typedef internal::TensorBlockScratchAllocator< Device > TensorBlockScratch
typedef TensorEvaluator< const RightArgType, Device >::TensorBlock RightTensorBlock
Public Member Functions
TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void evalScalar (Index i) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void evalPacket (Index i) const
EIGEN_DEVICE_FUNC CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements getResourceRequirements () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void evalBlock (TensorBlockDesc &desc, TensorBlockScratch &scratch)
EIGEN_DEVICE_FUNC EvaluatorPointerType data () const
Static Public Attributes
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int NumDims = XprType::NumDims
static constexpr int Layout = TensorEvaluator<LeftArgType, Device>::Layout
Private Attributes
TensorEvaluator< LeftArgType, Device > m_leftImpl
TensorEvaluator< RightArgType, Device > m_rightImpl
Member Typedef Documentation
CoeffReturnType
template<typename LeftArgType , typename RightArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::CoeffReturnType
Dimensions
template<typename LeftArgType , typename RightArgType , typename Device > typedef TensorEvaluator<RightArgType, Device>::Dimensions Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::Dimensions
EvaluatorPointerType
template<typename LeftArgType , typename RightArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::EvaluatorPointerType
Index
template<typename LeftArgType , typename RightArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::Index
PacketReturnType
template<typename LeftArgType , typename RightArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::PacketReturnType
RightTensorBlock
template<typename LeftArgType , typename RightArgType , typename Device > typedef TensorEvaluator<const RightArgType, Device>::TensorBlock Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::RightTensorBlock
Scalar
template<typename LeftArgType , typename RightArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::Scalar
Storage
template<typename LeftArgType , typename RightArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::Storage
TensorBlockDesc
template<typename LeftArgType , typename RightArgType , typename Device > typedef internal::TensorBlockDescriptor<NumDims, Index> Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::TensorBlockDesc
TensorBlockScratch
template<typename LeftArgType , typename RightArgType , typename Device > typedef internal::TensorBlockScratchAllocator<Device> Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::TensorBlockScratch
XprType
template<typename LeftArgType , typename RightArgType , typename Device > typedef TensorAssignOp<LeftArgType, RightArgType> Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename LeftArgType , typename RightArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
RawAccess
        {
     IsAligned =
         int(TensorEvaluator<LeftArgType, Device>::IsAligned) & int(TensorEvaluator<RightArgType, Device>::IsAligned),
     PacketAccess = int(TensorEvaluator<LeftArgType, Device>::PacketAccess) &
                    int(TensorEvaluator<RightArgType, Device>::PacketAccess),
     BlockAccess = int(TensorEvaluator<LeftArgType, Device>::BlockAccess) &
                   int(TensorEvaluator<RightArgType, Device>::BlockAccess),
     PreferBlockAccess = int(TensorEvaluator<LeftArgType, Device>::PreferBlockAccess) |
                         int(TensorEvaluator<RightArgType, Device>::PreferBlockAccess),
     RawAccess = TensorEvaluator<LeftArgType, Device>::RawAccess
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename LeftArgType , typename RightArgType , typename Device > Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_leftImpl(op.lhsExpression(), device), m_rightImpl(op.rhsExpression(), device) {
     EIGEN_STATIC_ASSERT((static_cast<int>(TensorEvaluator<LeftArgType, Device>::Layout) ==
                          static_cast<int>(TensorEvaluator<RightArgType, Device>::Layout)),
                         YOU_MADE_A_PROGRAMMING_MISTAKE);
   }
References EIGEN_STATIC_ASSERT.
Member Function Documentation
cleanup()
template<typename LeftArgType , typename RightArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::cleanup () inline
{
     m_leftImpl.cleanup();
     m_rightImpl.cleanup();
   }
Referenced by framework.Frame::__init__().
coeff()
template<typename LeftArgType , typename RightArgType , typename Device > EIGEN_DEVICE_FUNC CoeffReturnType Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::coeff (Index index) const inline
 { return m_leftImpl.coeff(index); }
costPerCoeff()
template<typename LeftArgType , typename RightArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     // We assume that evalPacket or evalScalar is called to perform the
     // assignment and account for the cost of the write here, but reduce left
     // cost by one load because we are using m_leftImpl.coeffRef.
     TensorOpCost left = m_leftImpl.costPerCoeff(vectorized);
     return m_rightImpl.costPerCoeff(vectorized) +
            TensorOpCost(numext::maxi(0.0, left.bytes_loaded() - sizeof(CoeffReturnType)), left.bytes_stored(),
                         left.compute_cycles()) +
            TensorOpCost(0, sizeof(CoeffReturnType), 0, vectorized, PacketSize);
   }
References Eigen::TensorOpCost::bytes_loaded(), Eigen::TensorOpCost::bytes_stored(), Eigen::TensorOpCost::compute_cycles(), Eigen::numext::maxi(), and Eigen::TensorEvaluator< Derived, Device >::PacketSize.
data()
template<typename LeftArgType , typename RightArgType , typename Device > EIGEN_DEVICE_FUNC EvaluatorPointerType Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::data () const inline
 { return m_leftImpl.data(); }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename LeftArgType , typename RightArgType , typename Device > EIGEN_DEVICE_FUNC const Dimensions& Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::dimensions () const inline
{
     // The dimensions of the lhs and the rhs tensors should be equal to prevent
     // overflows and ensure the result is fully initialized.
     // TODO: use left impl instead if right impl dimensions are known at compile time.
     return m_rightImpl.dimensions();
   }
evalBlock()
template<typename LeftArgType , typename RightArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::evalBlock (TensorBlockDesc & desc, TensorBlockScratch & scratch) inline
{
     if (TensorEvaluator<LeftArgType, Device>::RawAccess && m_leftImpl.data() != NULL) {
       // If destination has raw data access, we pass it as a potential
       // destination for a block descriptor evaluation.
       desc.template AddDestinationBuffer<Layout>(
           /*dst_base=*/m_leftImpl.data() + desc.offset(),
           /*dst_strides=*/internal::strides<Layout>(m_leftImpl.dimensions()));
     }
     RightTensorBlock block = m_rightImpl.block(desc, scratch, /*root_of_expr_ast=*/true);
     // If block was evaluated into a destination, there is no need to do assignment.
     if (block.kind() != internal::TensorBlockKind::kMaterializedInOutput) {
       m_leftImpl.writeBlock(desc, block);
     }
     block.cleanup();
   }
References Eigen::TensorEvaluator< Derived, Device >::block(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::cleanup(), Eigen::TensorEvaluator< Derived, Device >::data(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::kind(), Eigen::internal::kMaterializedInOutput, and Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::offset().
evalPacket()
template<typename LeftArgType , typename RightArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::evalPacket (Index i) const inline
{
     const int LhsStoreMode = TensorEvaluator<LeftArgType, Device>::IsAligned ? Aligned : Unaligned;
     const int RhsLoadMode = TensorEvaluator<RightArgType, Device>::IsAligned ? Aligned : Unaligned;
     m_leftImpl.template writePacket<LhsStoreMode>(i, m_rightImpl.template packet<RhsLoadMode>(i));
   }
References Eigen::Aligned, i, and Eigen::Unaligned.
evalScalar()
template<typename LeftArgType , typename RightArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::evalScalar (Index i) const inline
{
     m_leftImpl.coeffRef(i) = m_rightImpl.coeff(i);
   }
References i.
evalSubExprsIfNeeded()
template<typename LeftArgType , typename RightArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
{
     eigen_assert(dimensions_match(m_leftImpl.dimensions(), m_rightImpl.dimensions()));
     m_leftImpl.evalSubExprsIfNeeded(NULL);
     // If the lhs provides raw access to its storage area (i.e. if m_leftImpl.data() returns a non
     // null value), attempt to evaluate the rhs expression in place. Returns true iff in place
     // evaluation isn't supported and the caller still needs to manually assign the values generated
     // by the rhs to the lhs.
     return m_rightImpl.evalSubExprsIfNeeded(m_leftImpl.data());
   }
References Eigen::dimensions_match(), and eigen_assert.
getResourceRequirements()
template<typename LeftArgType , typename RightArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::getResourceRequirements () const inline
{
     return internal::TensorBlockResourceRequirements::merge(m_leftImpl.getResourceRequirements(),
                                                             m_rightImpl.getResourceRequirements());
   }
References Eigen::internal::TensorBlockResourceRequirements::merge().
packet()
template<typename LeftArgType , typename RightArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC PacketReturnType Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::packet (Index index) const inline
{
     return m_leftImpl.template packet<LoadMode>(index);
   }
Member Data Documentation
Layout
template<typename LeftArgType , typename RightArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::Layout = TensorEvaluator<LeftArgType, Device>::Layout static constexpr
m_leftImpl
template<typename LeftArgType , typename RightArgType , typename Device > TensorEvaluator<LeftArgType, Device> Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::m_leftImpl private
m_rightImpl
template<typename LeftArgType , typename RightArgType , typename Device > TensorEvaluator<RightArgType, Device> Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::m_rightImpl private
NumDims
template<typename LeftArgType , typename RightArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::NumDims = XprType::NumDims static constexpr
PacketSize
template<typename LeftArgType , typename RightArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorAssign.h