MercuryDPM: Eigen::internal::inner_sort_impl< Derived, Comp, IsVector > Struct Template Reference
Eigen::internal::inner_sort_impl< Derived, Comp, IsVector > Struct Template Reference
#include <SparseCompressedBase.h>
Public Types
typedef Derived::Scalar Scalar
typedef Derived::StorageIndex StorageIndex
Static Public Member Functions
static void run (SparseCompressedBase< Derived > &obj, Index begin, Index end)
static Index check (const SparseCompressedBase< Derived > &obj, Index begin, Index end)
Member Typedef Documentation
Scalar
template<typename Derived , class Comp , bool IsVector> typedef Derived::Scalar Eigen::internal::inner_sort_impl< Derived, Comp, IsVector >::Scalar
StorageIndex
template<typename Derived , class Comp , bool IsVector> typedef Derived::StorageIndex Eigen::internal::inner_sort_impl< Derived, Comp, IsVector >::StorageIndex
Member Function Documentation
check()
template<typename Derived , class Comp , bool IsVector> static Index Eigen::internal::inner_sort_impl< Derived, Comp, IsVector >::check (const SparseCompressedBase< Derived > & obj, Index begin, Index end) inline static
{
     const bool is_compressed = obj.isCompressed();
     for (Index outer = begin; outer < end; outer++) {
       Index begin_offset = obj.outerIndexPtr()[outer];
       Index end_offset = is_compressed ? obj.outerIndexPtr()[outer + 1] : (begin_offset + obj.innerNonZeroPtr()[outer]);
       const StorageIndex* begin_it = obj.innerIndexPtr() + begin_offset;
       const StorageIndex* end_it = obj.innerIndexPtr() + end_offset;
       bool is_sorted = std::is_sorted(begin_it, end_it, Comp());
       if (!is_sorted) return outer;
     }
     return end;
   }
References Eigen::placeholders::end, Eigen::SparseCompressedBase< Derived >::innerIndexPtr(), Eigen::SparseCompressedBase< Derived >::innerNonZeroPtr(), is_sorted(), Eigen::SparseCompressedBase< Derived >::isCompressed(), and Eigen::SparseCompressedBase< Derived >::outerIndexPtr().
Referenced by Eigen::SparseCompressedBase< Derived >::innerIndicesAreSorted().
run()
template<typename Derived , class Comp , bool IsVector> static void Eigen::internal::inner_sort_impl< Derived, Comp, IsVector >::run (SparseCompressedBase< Derived > & obj, Index begin, Index end) inline static
{
     const bool is_compressed = obj.isCompressed();
     for (Index outer = begin; outer < end; outer++) {
       Index begin_offset = obj.outerIndexPtr()[outer];
       Index end_offset = is_compressed ? obj.outerIndexPtr()[outer + 1] : (begin_offset + obj.innerNonZeroPtr()[outer]);
       CompressedStorageIterator<Scalar, StorageIndex> begin_it(begin_offset, obj.innerIndexPtr(), obj.valuePtr());
       CompressedStorageIterator<Scalar, StorageIndex> end_it(end_offset, obj.innerIndexPtr(), obj.valuePtr());
       std::sort(begin_it, end_it, Comp());
     }
   }
References Eigen::placeholders::end, Eigen::SparseCompressedBase< Derived >::innerIndexPtr(), Eigen::SparseCompressedBase< Derived >::innerNonZeroPtr(), Eigen::SparseCompressedBase< Derived >::isCompressed(), Eigen::SparseCompressedBase< Derived >::outerIndexPtr(), and Eigen::SparseCompressedBase< Derived >::valuePtr().
Referenced by Eigen::SparseCompressedBase< Derived >::sortInnerIndices().
The documentation for this struct was generated from the following file:
SparseCompressedBase.h