MercuryDPM: CoupledBeam Class Reference
CoupledBeam Class Reference
Public Member Functions
CoupledBeam ()
void setupOomph ()
void setupMercury ()
void actionsBeforeSolve () override
Write header of output file.
void actionsBeforeOomphTimeStep () override
Each time step, compute deflection, elastic, kinetic and gravitational energy, and write to output file.
double getBeamDeflection ()
CoupledBeam ()
void setupOomph ()
void setupMercury ()
void actionsBeforeSolve () override
Write header of output file.
void actionsBeforeOomphTimeStep () override
Each time step, compute deflection, elastic, kinetic and gravitational energy, and write to output file.
double getBeamDeflection ()
CoupledBeam ()
void setupOomph ()
void setupMercury ()
void actionsBeforeSolve () override
Write header of output file.
void actionsBeforeOomphTimeStep () override
Each time step, compute deflection, elastic, kinetic and gravitational energy, and write to output file.
double getBeamDeflection ()
CoupledBeam ()
void setupOomph ()
void setupMercury ()
void actionsBeforeSolve () override
Write header of output file.
void actionsBeforeOomphTimeStep () override
Each time step, compute deflection, elastic, kinetic and gravitational energy, and write to output file.
double getBeamDeflection ()
Public Member Functions inherited from SCoupling< M, O >
SCoupling ()=default
void solveSurfaceCoupling (const unsigned max_adapt=0)
void solveSurfaceCoupling (unsigned nStep, const unsigned max_adapt)
void solveSurfaceCouplingForgiving (unsigned nStep, double timeMaxMin=-constants::inf, const unsigned max_adapt=0)
void solveSurfaceCouplingFixedSolid ()
TriangleWall * createTriangleWall (std::array< Vec3D, 3 > vertex)
void updateTriangleWall (TriangleWall *&wall, std::array< Vec3D, 3 > vertex)
void computeOneTimeStepForSCoupling (const unsigned &nStepsMercury, const unsigned max_adapt=0)
void createDPMWallsFromFiniteElems ()
void updateDPMWallsFromFiniteElems ()
void updateTractionOnFiniteElems ()
bool computeSCouplingForcesFromTriangles (ELEMENT *const elem_pt, const unsigned &nTriangles, unsigned &wallID, Vector< Vector< double > > &nodalCouplingForces)
void getElementBoundingBox (ELEMENT *&elem_pt, Vec3D &min, Vec3D &max)
void getSCoupledElements ()
void coupleBoundary (unsigned b)
void coupleBoundaries (std::vector< unsigned > b)
void disableLogSurfaceCoupling ()
void setSolidFeelsParticles (bool val)
bool getSolidFeelsParticles () const
Public Member Functions inherited from BaseCoupling< M, O >
BaseCoupling ()=default
void setName (std::string name)
std::string getName () const
void removeOldFiles () const
void writeEneTimeStep (std::ostream &os) const override
void writeEneHeader (std::ostream &os) const override
void solveOomph (int max_adapt=0)
void checkResidual ()
void solveMercury (unsigned long nt)
void setCGWidth (const double &width)
double getCGWidth ()
bool useCGMapping ()
CGFunctions::LucyXYZ getCGFunction ()
Public Attributes
std::ofstream out
output file stream
Additional Inherited Members
Public Types inherited from SCoupling< M, O >
typedef O::ELEMENT ELEMENT
Detailed Description
Define a coupled problem
Constructor & Destructor Documentation
CoupledBeam() [1/4]
CoupledBeam::CoupledBeam () inline
                    {
         //set name
         setName("CoupledBeam");
         //remove existing output files
         removeOldFiles();
         // setup steps
         setupOomph();
         setupMercury();
         // setup time
         setTimeMax(200);
         setSaveCount(500);
         logger(INFO,"timeMax: %, nTimeSteps %", getTimeMax(), getTimeMax()/getTimeStep());
         linear_solver_pt()->disable_doc_time();
         //disable_info_in_newton_solve();
         // Solve the  problem
         writeToVTK();
         solveSurfaceCoupling();
         saveSolidMesh();
     }
References INFO, logger, BaseCoupling< M, O >::removeOldFiles(), BaseCoupling< M, O >::setName(), setupMercury(), setupOomph(), and SCoupling< M, O >::solveSurfaceCoupling().
CoupledBeam() [2/4]
CoupledBeam::CoupledBeam () inline
                    {
         //set name
         setName("CoupledBeamRolling");
         //remove existing output files
         removeOldFiles();
         // setup steps
         setupOomph();
         setupMercury();
         // equalise time step
         if (getOomphTimeStep()>getTimeStep()) {
             setOomphTimeStep(getTimeStep());
         } else {
             setTimeStep(getOomphTimeStep());
         }
         // setup time
         setTimeMax(2.22);
         setSaveCount(4);
         logger(INFO,"timeMax: %, nTimeSteps %", getTimeMax(), getTimeMax()/getTimeStep());
         linear_solver_pt()->disable_doc_time();
         //disable_info_in_newton_solve();
         // Solve the  problem
         writeToVTK();
         solveSurfaceCoupling();
         saveSolidMesh();
     }
References INFO, logger, BaseCoupling< M, O >::removeOldFiles(), BaseCoupling< M, O >::setName(), setupMercury(), setupOomph(), and SCoupling< M, O >::solveSurfaceCoupling().
CoupledBeam() [3/4]
CoupledBeam::CoupledBeam () inline
                    {
         //set name
         setName("CoupledBeamRolling2");
         //remove existing output files
         removeOldFiles();
         // setup steps
         setupOomph();
         setupMercury();
         // equalise time step
         if (getOomphTimeStep()>getTimeStep()) {
             setOomphTimeStep(getTimeStep());
         } else {
             setTimeStep(getOomphTimeStep());
         }
         // setup time
         setTimeMax(2.22);
         setSaveCount(4);
         logger(INFO,"timeMax: %, nTimeSteps %", getTimeMax(), getTimeMax()/getTimeStep());
         linear_solver_pt()->disable_doc_time();
         //disable_info_in_newton_solve();
         // Solve the  problem
         writeToVTK();
         solveSurfaceCoupling();
         saveSolidMesh();
     }
References INFO, logger, BaseCoupling< M, O >::removeOldFiles(), BaseCoupling< M, O >::setName(), setupMercury(), setupOomph(), and SCoupling< M, O >::solveSurfaceCoupling().
CoupledBeam() [4/4]
CoupledBeam::CoupledBeam () inline
                    {
         //set name
         setName("CoupledBeamUnitTest");
         //remove existing output files
         removeOldFiles();
         // setup steps
         setupOomph();
         setupMercury();
         // equalise time step
         if (getOomphTimeStep()>getTimeStep()) {
             setOomphTimeStep(getTimeStep());
         } else {
             setTimeStep(getOomphTimeStep());
         }
         // setup time
         setTimeMax(100*getTimeStep());
         setSaveCount(4);
         logger(INFO,"timeMax: %, nTimeSteps %", getTimeMax(), getTimeMax()/getTimeStep());
         linear_solver_pt()->disable_doc_time();
         //disable_info_in_newton_solve();
         // Solve the  problem
         writeToVTK();
         solveSurfaceCoupling();
         saveSolidMesh();
         double velocity = particleHandler.getLastObject()->getVelocity().Z;
         //logger(INFO,"Final particle velocity %", velocity);
         helpers::check(velocity, 0.0495209, 1e-6, "final particle velocity");
     }
References helpers::check(), e(), INFO, logger, BaseCoupling< M, O >::removeOldFiles(), BaseCoupling< M, O >::setName(), setupMercury(), setupOomph(), SCoupling< M, O >::solveSurfaceCoupling(), and Jeffery_Solution::velocity().
Member Function Documentation
actionsBeforeOomphTimeStep() [1/4]
void CoupledBeam::actionsBeforeOomphTimeStep () inline override
Each time step, compute deflection, elastic, kinetic and gravitational energy, and write to output file.
{
         double mass, elasticEnergy, kineticEnergy;
         Vector<double> com(3), linearMomentum(3), angularMomentum(3);
         getMassMomentumEnergy(mass, com, linearMomentum, angularMomentum, elasticEnergy, kineticEnergy);
         static double gravEnergy0 = getOomphGravity()*mass*com[2];
         double gravEnergy = getOomphGravity()*mass*com[2]-gravEnergy0;
         static double gravEnergyParticle0 = getGravitationalEnergy();
         out << getOomphTime()
             << ' ' << getBeamDeflection()
             << ' ' << elasticEnergy
             << ' ' << kineticEnergy
             << ' ' << gravEnergy
             << ' ' << getElasticEnergy()
             << ' ' << getKineticEnergy()
             << ' ' << getGravitationalEnergy()-gravEnergyParticle0;
         for (const auto p: particleHandler) {
             out << ' ' << p->getPosition();
         }
         out << std::endl;
     }
References getBeamDeflection(), out, and p.
actionsBeforeOomphTimeStep() [2/4]
void CoupledBeam::actionsBeforeOomphTimeStep () inline override
Each time step, compute deflection, elastic, kinetic and gravitational energy, and write to output file.
{
         double mass, elasticEnergy, kineticEnergy;
         Vector<double> com(3), linearMomentum(3), angularMomentum(3);
         getMassMomentumEnergy(mass, com, linearMomentum, angularMomentum, elasticEnergy, kineticEnergy);
         static double gravEnergy0 = getOomphGravity()*mass*com[2];
         double gravEnergy = getOomphGravity()*mass*com[2]-gravEnergy0;
         static double gravEnergyParticle0 = getGravitationalEnergy();
         out << getOomphTime()
                 << ' ' << getBeamDeflection()
                 << ' ' << elasticEnergy
                 << ' ' << kineticEnergy
                 << ' ' << gravEnergy
                 << ' ' << getElasticEnergy()
                 << ' ' << getKineticEnergy()
                 << ' ' << getGravitationalEnergy()-gravEnergyParticle0;
         for (const auto p: particleHandler) {
             out << ' ' << p->getPosition();
         }
         out << std::endl;
     }
References getBeamDeflection(), out, and p.
actionsBeforeOomphTimeStep() [3/4]
void CoupledBeam::actionsBeforeOomphTimeStep () inline override
Each time step, compute deflection, elastic, kinetic and gravitational energy, and write to output file.
{
         double mass, elasticEnergy, kineticEnergy;
         Vector<double> com(3), linearMomentum(3), angularMomentum(3);
         getMassMomentumEnergy(mass, com, linearMomentum, angularMomentum, elasticEnergy, kineticEnergy);
         static double gravEnergy0 = getOomphGravity()*mass*com[2];
         double gravEnergy = getOomphGravity()*mass*com[2]-gravEnergy0;
         static double gravEnergyParticle0 = getGravitationalEnergy();
         out << getOomphTime()
                 << ' ' << getBeamDeflection()
                 << ' ' << elasticEnergy
                 << ' ' << kineticEnergy
                 << ' ' << gravEnergy
                 << ' ' << getElasticEnergy()
                 << ' ' << getKineticEnergy()
                 << ' ' << getGravitationalEnergy()-gravEnergyParticle0;
         for (const auto p: particleHandler) {
             out << ' ' << p->getPosition();
         }
         out << std::endl;
     }
References getBeamDeflection(), out, and p.
actionsBeforeOomphTimeStep() [4/4]
void CoupledBeam::actionsBeforeOomphTimeStep () inline override
Each time step, compute deflection, elastic, kinetic and gravitational energy, and write to output file.
{
         double mass, elasticEnergy, kineticEnergy;
         Vector<double> com(3), linearMomentum(3), angularMomentum(3);
         getMassMomentumEnergy(mass, com, linearMomentum, angularMomentum, elasticEnergy, kineticEnergy);
         static double gravEnergy0 = getOomphGravity()*mass*com[2];
         double gravEnergy = getOomphGravity()*mass*com[2]-gravEnergy0;
         static double gravEnergyParticle0 = getGravitationalEnergy();
         out << getOomphTime()
                 << ' ' << getBeamDeflection()
                 << ' ' << elasticEnergy
                 << ' ' << kineticEnergy
                 << ' ' << gravEnergy
                 << ' ' << getElasticEnergy()
                 << ' ' << getKineticEnergy()
                 << ' ' << getGravitationalEnergy()-gravEnergyParticle0
                 << std::endl;
     }
References getBeamDeflection(), and out.
actionsBeforeSolve() [1/4]
void CoupledBeam::actionsBeforeSolve () inline override
Write header of output file.
{
         helpers::writeToFile(
                 getName()+".gnu",
                 "set xlabel 'time'\n"
                 "set ylabel 'kinetic and potential energy'\n"
                 "p 'CoupledBeam.out' u 1:($3+$4) w lp t 'oomph-lib', '' u 1:(($6+$7-6.54498e-07 )) w lp t 'MercuryDPM', '' u 1:($3+$4+$6+$7-6.54498e-07) w lp t 'total'");
         out.open(getName()+".out");
         out << "time deflection elasticEnergy kineticEnergy gravEnergy elasticEnergyInteractions kineticEnergyParticles gravEnergyParticles particlePosition\n";
     }
References BaseCoupling< M, O >::getName(), out, and helpers::writeToFile().
actionsBeforeSolve() [2/4]
void CoupledBeam::actionsBeforeSolve () inline override
Write header of output file.
{
         helpers::writeToFile(
                 getName()+".gnu",
                 "set xlabel 'time'\n"
                 "set ylabel 'kinetic and potential energy'\n"
                 "p 'CoupledBeamRolling.out' u 1:($3+$4+$5) w lp t 'oomph-lib', '' u 1:(($6+$7+$8)) w lp t 'MercuryDPM', '' u 1:($3+$4+$5+$6+$7+$8) w lp t 'total'");
         out.open(getName()+".out");
         out << "time deflection elasticEnergy kineticEnergy gravEnergy elasticEnergyInteractions kineticEnergyParticles gravEnergyParticles particlePosition\n";
     }
References BaseCoupling< M, O >::getName(), out, and helpers::writeToFile().
actionsBeforeSolve() [3/4]
void CoupledBeam::actionsBeforeSolve () inline override
Write header of output file.
{
         helpers::writeToFile(
                 getName()+".gnu",
                 "set xlabel 'time'\n"
                 "set ylabel 'kinetic and potential energy'\n"
                 "p 'CoupledBeamRolling.out' u 1:($3+$4+$5) w lp t 'oomph-lib', '' u 1:(($6+$7+$8)) w lp t 'MercuryDPM', '' u 1:($3+$4+$5+$6+$7+$8) w lp t 'total'");
         out.open(getName()+".out");
         out << "time deflection elasticEnergy kineticEnergy gravEnergy elasticEnergyInteractions kineticEnergyParticles gravEnergyParticles particlePosition\n";
     }
References BaseCoupling< M, O >::getName(), out, and helpers::writeToFile().
actionsBeforeSolve() [4/4]
void CoupledBeam::actionsBeforeSolve () inline override
Write header of output file.
{
         helpers::writeToFile(
                 getName()+".gnu",
                 "set xlabel 'time'\n"
                 "set ylabel 'kinetic and potential energy'\n"
                 "p 'CoupledBeamUnitTest.out' u 1:($3+$4) w lp t 'oomph-lib', '' u 1:(($6+$7-6.54498e-07 )) w lp t 'MercuryDPM', '' u 1:($3+$4+$6+$7-6.54498e-07) w lp t 'total'");
         out.open(getName()+".out");
         out << "time deflection elasticEnergy kineticEnergy gravEnergy elasticEnergyInteractions kineticEnergyParticles gravEnergyParticles\n";
     }
References BaseCoupling< M, O >::getName(), out, and helpers::writeToFile().
getBeamDeflection() [1/4]
double CoupledBeam::getBeamDeflection () inline
Outputs deflection at midpoint
{
         std::array<double,3> min, max;
         getDomainSize(min, max);
         Vector<double> xi(3);
         xi[0] = max[0];
         xi[1] = 0.5*(max[1]+min[1]);
         xi[2] = 0.5*(max[2]+min[2]);
         double deflection = getDeflection(xi,2);
         logger(INFO, "Beam deflection at center (% % %) is %",
                xi[0], xi[1],xi[2], deflection);
         double mass, elasticEnergy, kineticEnergy;
         Vector<double> com(3), linearMomentum(3), angularMomentum(3);
         getMassMomentumEnergy(mass, com, linearMomentum, angularMomentum, elasticEnergy, kineticEnergy);
         logger(INFO, "mass %, linearMomentum %, angularMomentum %, elasticEnergy %, totalEnergy %",
                mass, linearMomentum, angularMomentum, elasticEnergy, elasticEnergy+kineticEnergy);
         return deflection;
     }
References INFO, logger, max, and min.
Referenced by actionsBeforeOomphTimeStep(), and setupOomph().
getBeamDeflection() [2/4]
double CoupledBeam::getBeamDeflection () inline
Outputs deflection at midpoint
{
         std::array<double,3> min, max;
         getDomainSize(min, max);
         Vector<double> xi(3);
         xi[0] = 0.5*(max[0]+min[0]);
         xi[1] = 0.5*(max[1]+min[1]);
         xi[2] = 0.5*(max[2]+min[2]);
         return getDeflection(xi,2);
     }
References max, and min.
getBeamDeflection() [3/4]
double CoupledBeam::getBeamDeflection () inline
Outputs deflection at midpoint
{
         std::array<double,3> min, max;
         getDomainSize(min, max);
         Vector<double> xi(3);
         xi[0] = 0.5*(max[0]+min[0]);
         xi[1] = 0.5*(max[1]+min[1]);
         xi[2] = 0.5*(max[2]+min[2]);
         double deflection = getDeflection(xi,2);
         logger(INFO, "Beam deflection at center (% % %) is %",
                xi[0], xi[1],xi[2], deflection);
         double mass, elasticEnergy, kineticEnergy;
         Vector<double> com(3), linearMomentum(3), angularMomentum(3);
         getMassMomentumEnergy(mass, com, linearMomentum, angularMomentum, elasticEnergy, kineticEnergy);
         logger(INFO, "mass %, linearMomentum %, angularMomentum %, elasticEnergy %, totalEnergy %",
                mass, linearMomentum, angularMomentum, elasticEnergy, elasticEnergy+kineticEnergy);
         return deflection;
     }
References INFO, logger, max, and min.
getBeamDeflection() [4/4]
double CoupledBeam::getBeamDeflection () inline
Outputs deflection at midpoint
{
         std::array<double,3> min, max;
         getDomainSize(min, max);
         Vector<double> xi(3);
         xi[0] = 0.5*(max[0]+min[0]);
         xi[1] = 0.5*(max[1]+min[1]);
         xi[2] = 0.5*(max[2]+min[2]);
         double deflection = getDeflection(xi,2);
         logger(INFO, "Beam deflection at center (% % %) is %",
                xi[0], xi[1],xi[2], deflection);
         double mass, elasticEnergy, kineticEnergy;
         Vector<double> com(3), linearMomentum(3), angularMomentum(3);
         getMassMomentumEnergy(mass, com, linearMomentum, angularMomentum, elasticEnergy, kineticEnergy);
         logger(INFO, "mass %, linearMomentum %, angularMomentum %, elasticEnergy %, totalEnergy %",
                mass, linearMomentum, angularMomentum, elasticEnergy, elasticEnergy+kineticEnergy);
         return deflection;
     }
References INFO, logger, max, and min.
setupMercury() [1/4]
void CoupledBeam::setupMercury () inline
{
         // set domain min, max. Used to getDomainSize
         std::array<double, 3> min, max;
         getDomainSize(min, max);
         // Translating the array into a Vec3D. Mercury works with Vec3D to set the domain
         Vec3D minVec(min);
         Vec3D maxVec(max);
         // set domain in Mercury
         setDomain(minVec, maxVec);
         // add elastic species
         auto species = speciesHandler.copyAndAddObject(LinearViscoelasticSpecies());
         species->setDensity(2e4);
         const double radius = 0.1;
         species->setStiffness(getElasticModulus()*2*radius);
         logger(INFO,"Species: %", *species);
         // add particle
         SphericalParticle p(species);
         p.setRadius(radius);
         const double mass = species->getMassFromRadius(radius);
         double overlap = mass*9.81/species->getStiffness();
         p.setPosition({0.2,0.2,getZMax()+radius-overlap});
         p.setVelocity({0.1,0,0});
         auto particle = particleHandler.copyAndAddObject(p);
         logger(INFO,"Particle: %", *particle);
         p.setPosition({0.2,0.6,getZMax()+radius-overlap});
         particle = particleHandler.copyAndAddObject(p);
         logger(INFO,"Particle: %", *particle);
         // set time step
         double tc = species->getCollisionTime(species->getMassFromRadius(p.getRadius()));
         setTimeStep(0.05*tc);
         // set oomph and mercury time step equal
         setOomphTimeStep(getTimeStep());
         logger(INFO,"Mercury time step %", getTimeStep());
         logger(INFO,"Oomph time step %", getOomphTimeStep());
         // set output file properties
         setParticlesWriteVTK(true);
         wallHandler.setWriteVTK(true);
         setFileType(FileType::NO_FILE);
         restartFile.setFileType(FileType::ONE_FILE);
         restartFile.writeFirstAndLastTimeStep();
         // add gravity
         setGravity({0,0,-9.81});
     }
References INFO, logger, max, min, NO_FILE, ONE_FILE, p, and UniformPSDSelfTest::radius.
Referenced by CoupledBeam().
setupMercury() [2/4]
void CoupledBeam::setupMercury () inline
{
         // set domain min, max. Used to getDomainSize
         std::array<double, 3> min;
         std::array<double, 3> max;
         getDomainSize(min, max);
         // Translating the array into a Vec3D. Mercury works with Vec3D to set the domain
         Vec3D minVec(min);
         Vec3D maxVec(max);
         // set domain in Mercury
         setDomain(minVec, maxVec);
         // add elastic species
         auto species = speciesHandler.copyAndAddObject(LinearViscoelasticSpecies());
         species->setDensity(1000);
         const double radius = 5e-3;
         const double mass = species->getMassFromRadius(radius);
         // stiffness such that k*(0.1*r)=.5*m*v^2
         double velocity = 0.05;
         double stiffness = mass*velocity*velocity/(0.01*radius*radius);
         species->setStiffness(stiffness);
         logger(INFO,"Species: %", *species);
         // add particle
         SphericalParticle p(species);
         p.setRadius(radius);
         double overlap = mass*9.8/species->getStiffness();
         p.setPosition({getXMin()+radius,getYCenter(),getZMax()+p.getRadius()-overlap});
         //p.setPosition({getXCenter(),getYMax()+p.getRadius(),getZCenter()});
         p.setVelocity({velocity,0,0});
         auto particle = particleHandler.copyAndAddObject(p);
         logger(INFO,"Particle: %", *particle);
         // set time step
         double tc = species->getCollisionTime(mass);
         setTimeStep(0.05*tc);
         logger(INFO,"Mercury time step %", getTimeStep());
         // set output file properties
         setParticlesWriteVTK(true);
         wallHandler.setWriteVTK(true);
         setFileType(FileType::NO_FILE);
         restartFile.setFileType(FileType::ONE_FILE);
         restartFile.writeFirstAndLastTimeStep();
         // add gravity
         setGravity({0,0,-9.8});
     }
References e(), INFO, logger, max, min, NO_FILE, ONE_FILE, p, UniformPSDSelfTest::radius, and Jeffery_Solution::velocity().
setupMercury() [3/4]
void CoupledBeam::setupMercury () inline
{
         // set domain min, max. Used to getDomainSize
         std::array<double, 3> min;
         std::array<double, 3> max;
         getDomainSize(min, max);
         // Translating the array into a Vec3D. Mercury works with Vec3D to set the domain
         Vec3D minVec(min);
         Vec3D maxVec(max);
         // set domain in Mercury
         setDomain(minVec, maxVec);
         // add elastic species
         auto species = speciesHandler.copyAndAddObject(LinearViscoelasticSpecies());
         species->setDensity(1000);
         const double radius = 5e-3;
         const double mass = species->getMassFromRadius(radius);
         // stiffness such that k*o=mg
         double stiffness = mass*9.8/(0.2*radius);
         species->setStiffness(stiffness);
         logger(INFO,"Species: %", *species);
         // add particle
         SphericalParticle p(species);
         p.setRadius(radius);
         p.setPosition({getXMin()+radius,getYCenter(),getZMax()+0.8*p.getRadius()});
         //p.setPosition({getXCenter(),getYMax()+p.getRadius(),getZCenter()});
         p.setVelocity({0.05,0,0});
         auto particle = particleHandler.copyAndAddObject(p);
         logger(INFO,"Particle: %", *particle);
         // set time step
         double tc = species->getCollisionTime(mass);
         setTimeStep(0.05*tc);
         logger(INFO,"Mercury time step %", getTimeStep());
         // set output file properties
         setParticlesWriteVTK(true);
         wallHandler.setWriteVTK(true);
         setFileType(FileType::NO_FILE);
         restartFile.setFileType(FileType::ONE_FILE);
         restartFile.writeFirstAndLastTimeStep();
         // add gravity
         setGravity({0,0,-9.8});
     }
References e(), INFO, logger, max, min, NO_FILE, ONE_FILE, p, and UniformPSDSelfTest::radius.
setupMercury() [4/4]
void CoupledBeam::setupMercury () inline
{
         // set domain min, max. Used to getDomainSize
         std::array<double, 3> min;
         std::array<double, 3> max;
         getDomainSize(min, max);
         // Translating the array into a Vec3D. Mercury works with Vec3D to set the domain
         Vec3D minVec(min);
         Vec3D maxVec(max);
         // set domain in Mercury
         setDomain(minVec, maxVec);
         // add elastic species
         auto species = speciesHandler.copyAndAddObject(LinearViscoelasticSpecies());
         species->setDensity(1000);
         const double radius = 5e-3;
         const double mass = species->getMassFromRadius(radius);
         // stiffness such that k*(0.1*r)=.5*m*v^2
         double velocity = 0.05;
         double stiffness = mass*velocity*velocity/(0.01*radius*radius);
         species->setStiffness(stiffness);
         logger(INFO,"Species: %", *species);
         // add particle
         SphericalParticle p(species);
         p.setRadius(radius);
         p.setPosition({getXCenter(),getYCenter(),getZMax()+p.getRadius()});
         //p.setPosition({getXCenter(),getYMax()+p.getRadius(),getZCenter()});
         p.setVelocity({0,0,-velocity});
         auto particle = particleHandler.copyAndAddObject(p);
         logger(INFO,"Particle: %", *particle);
         // set time step
         double tc = species->getCollisionTime(mass);
         setTimeStep(0.02*tc);
         logger(INFO,"Mercury time step %", getTimeStep());
         // set output file properties
         setParticlesWriteVTK(true);
         wallHandler.setWriteVTK(true);
         setFileType(FileType::NO_FILE);
         restartFile.setFileType(FileType::ONE_FILE);
         restartFile.writeFirstAndLastTimeStep();
         // add gravity
         setGravity({0,0,-0});
     }
References e(), INFO, logger, max, min, NO_FILE, ONE_FILE, p, UniformPSDSelfTest::radius, and Jeffery_Solution::velocity().
setupOomph() [1/4]
void CoupledBeam::setupOomph () inline
                       {
         setElasticModulus(100e6);
         setDensity(1309);
         double h = 0.4;
         setSolidCubicMesh(30, 2, 2, 0, 30*h, 0, 2*h, 0, 2*h);
         //pin at xmin and xmax
         pinBoundary(Boundary::X_MIN);
         // solve
         setNewtonSolverTolerance(1e-4);
         prepareForSolve();
         solveSteady();
         getBeamDeflection();
         // couple boundaries
         coupleBoundary(Boundary::Z_MAX);
     }
References SCoupling< M, O >::coupleBoundary(), e(), and getBeamDeflection().
Referenced by CoupledBeam().
setupOomph() [2/4]
void CoupledBeam::setupOomph () inline
                       {
         setElasticModulus(1e6);
         setDensity(2500);
         setSolidCubicMesh(7, 5, 5, 0, 0.16, 0, 0.04, 0, 0.01);
         //pin at xmin and xmax
         pinBoundaries({Boundary::X_MIN, Boundary::X_MAX});
         // set time step
         //set time scale of oscillation
         //https://vlab.amrita.edu/?sub=3&brch=175&sim=1080&cnt=1
         double b = 0.04, d = 0.01, l = 0.08;
         double inertia = b*d*d*d/12;
         double omega = 1.875*1.875*sqrt(getElasticModulus()*inertia/(getDensity()*b*d*std::pow(l,4)));
         double timeScale = 2*constants::pi/omega; //0.06
         setOomphTimeStep(0.04*timeScale);
         logger(INFO,"Oomph time step %", getOomphTimeStep());
         //set dissipation
         //double criticalDissipation = 0.1 * sqrt(elasticModulus_ * density_ / lengthScale); //TW
         //setDissipation(criticalDissipation);
         //logger(INFO,"Adding dissipation %",criticalDissipation);
         //setBodyForceAsGravity();
         setNewtonSolverTolerance(3e-8);
         prepareForSolve();
         solveSteady();
         getBeamDeflection();
         // couple boundaries
         coupleBoundary(Boundary::Z_MAX);
     }
References b, SCoupling< M, O >::coupleBoundary(), e(), getBeamDeflection(), INFO, logger, Eigen::internal::omega(), constants::pi, Eigen::bfloat16_impl::pow(), sqrt(), and Global_Physical_Variables::timeScale.
setupOomph() [3/4]
void CoupledBeam::setupOomph () inline
                       {
         setElasticModulus(1e6);
         setDensity(2500);
         setSolidCubicMesh(7, 5, 5, 0, 0.16, 0, 0.04, 0, 0.01);
         //pin at xmin and xmax
         pinBoundaries({Boundary::X_MIN, Boundary::X_MAX});
         // set time step
         //set time scale of oscillation
         //https://vlab.amrita.edu/?sub=3&brch=175&sim=1080&cnt=1
         double b = 0.04, d = 0.01, l = 0.08;
         double inertia = b*d*d*d/12;
         double omega = 1.875*1.875*sqrt(getElasticModulus()*inertia/(getDensity()*b*d*std::pow(l,4)));
         double timeScale = 2*constants::pi/omega; //0.06
         setOomphTimeStep(0.04*timeScale);
         logger(INFO,"Oomph time step %", getOomphTimeStep());
         //set dissipation
         //double criticalDissipation = 0.1 * sqrt(elasticModulus_ * density_ / lengthScale); //TW
         //setDissipation(criticalDissipation);
         //logger(INFO,"Adding dissipation %",criticalDissipation);
         //setBodyForceAsGravity();
         setNewtonSolverTolerance(3e-8);
         prepareForSolve();
         solveSteady();
         getBeamDeflection();
         // couple boundaries
         coupleBoundary(Boundary::Z_MAX);
     }
References b, SCoupling< M, O >::coupleBoundary(), e(), getBeamDeflection(), INFO, logger, Eigen::internal::omega(), constants::pi, Eigen::bfloat16_impl::pow(), sqrt(), and Global_Physical_Variables::timeScale.
setupOomph() [4/4]
void CoupledBeam::setupOomph () inline
                       {
         setElasticModulus(1e6);
         setDensity(2500);
         setSolidCubicMesh(7, 5, 5, 0, 0.16, 0, 0.04, 0, 0.01);
         //pin at xmin and xmax
         pinBoundaries({Boundary::X_MIN, Boundary::X_MAX});
         // set time step
         //set time scale of oscillation
         //https://vlab.amrita.edu/?sub=3&brch=175&sim=1080&cnt=1
         double b = 0.04, d = 0.01, l = 0.08;
         double inertia = b*d*d*d/12;
         double omega = 1.875*1.875*sqrt(getElasticModulus()*inertia/(getDensity()*b*d*std::pow(l,4)));
         double timeScale = 2*constants::pi/omega; //0.06
         setOomphTimeStep(0.04*timeScale);
         logger(INFO,"Oomph time step %", getOomphTimeStep());
         //set dissipation
         //double criticalDissipation = 0.1 * sqrt(elasticModulus_ * density_ / lengthScale); //TW
         //setDissipation(criticalDissipation);
         //logger(INFO,"Adding dissipation %",criticalDissipation);
         //setBodyForceAsGravity();
         setNewtonSolverTolerance(3e-8);
         prepareForSolve();
         solveSteady();
         getBeamDeflection();
         // couple boundaries
         coupleBoundary(Boundary::Z_MAX);
     }
References b, SCoupling< M, O >::coupleBoundary(), e(), getBeamDeflection(), INFO, logger, Eigen::internal::omega(), constants::pi, Eigen::bfloat16_impl::pow(), sqrt(), and Global_Physical_Variables::timeScale.
Member Data Documentation
out
std::ofstream CoupledBeam::out
output file stream
Referenced by actionsBeforeOomphTimeStep(), and actionsBeforeSolve().
The documentation for this class was generated from the following files:
CoupledBeam.cpp
CoupledBeamRolling.cpp
CoupledBeamRolling2.cpp
CoupledBeamUnitTest.cpp