MercuryDPM: BaseParticle Class Reference
BaseParticle Class Reference abstract
#include <BaseParticle.h>
Public Member Functions
BaseParticle ()
Basic Particle constructor, creates an Particle at (0,0,0) with radius, mass and inertia equal to 1.
BaseParticle (const BaseParticle &p)
Particle copy constructor, which accepts as input a reference to a Particle. It creates a copy of this Particle and all it's information. Usually it is better to use the copy() function for polymorphism.
BaseParticle (const ParticleSpecies *s)
~BaseParticle () override
Particle destructor, needs to be implemented and checked if it removes tangential spring information.
virtual BaseParticle * copy () const =0
Particle copy method. It calls to copy constructor of this Particle, useful for polymorphism.
virtual Mdouble getVolume () const
Get Particle volume function, which required a reference to the Species vector. It returns the volume of the Particle.
void fixParticle ()
Fix Particle function. It fixes a Particle by setting its inverse mass and inertia and velocities to zero.
bool isFixed () const override
Is fixed Particle function. It returns whether a Particle is fixed or not, by checking its inverse Mass.
bool isMPIParticle () const
Indicates if this particle is a ghost in the MPI domain.
void setMPIParticle (bool flag)
Flags the mpi particle status.
bool isInMPIDomain ()
Indicates if the particle is in the communication zone of the mpi domain.
void setInMPIDomain (bool flag)
Flags the status of the particle if wether it is in the communication zone or not.
bool isInPeriodicDomain () const
Indicates if the particle is in the periodic boundary communication zone.
void setInPeriodicDomain (bool flag)
Flags the status of the particle whether it is in the periodic communication zone or not.
bool isPeriodicGhostParticle () const
Indicates if this particle is a ghost in the periodic boundary.
void setPeriodicGhostParticle (bool flag)
Flags the status of the particle to be a ghost in periodic boundary or not.
bool isMaserParticle () const
Indicates if this particle belongs to the maser boundary.
void setMaserParticle (bool flag)
Flags the status of the particle if it belongs to the maser boundary or not.
void setCommunicationComplexity (unsigned complexity)
Set the communication complexity of the particle.
unsigned getCommunicationComplexity ()
Obtains the communication complexity of the particle.
void setPeriodicComplexity (std::vector< int > complexity)
Set the periodic communication complexity of the particle.
void setPeriodicComplexity (int index, int value)
Set the periodic communication complexity of the particle.
const std::vector< int > & getPeriodicComplexity ()
Obtains the periodic communication complexity of the particle.
void setPreviousPeriodicComplexity (std::vector< int > complexity)
Set the previous periodic communication complexity of the paritcle.
const std::vector< int > & getPreviousPeriodicComplexity () const
Sets the previous periodic communication complexity of the particle.
int getPeriodicComplexity (int index)
Gets the periodic communication complexity of a certain boundary.
void unfix ()
Unfix Particle function, which required a reference to the Species vector. It unfixes a Particle by computing the Particles mass and inertia.
void read (std::istream &is) override
Particle read function, which accepts an std::istream as input.
virtual void oldRead (std::istream &is)
void write (std::ostream &os) const override
Particle print function, which accepts an std::ostream as input.
std::string getName () const override
Returns the name of the object.
virtual void setInfo (Mdouble info)
Sets some user-defined information about this object (by default, species ID).
virtual Mdouble getInfo () const
Returns some user-defined information about this object (by default, species ID).
void setTimeStamp (unsigned timeStamp)
unsigned getTimeStamp () const
void printHGrid (std::ostream &os) const
Adds particle's HGrid level and cell coordinates to an ostream.
unsigned int getHGridLevel () const
Returns particle's HGrid level.
BaseParticle * getHGridNextObject () const
Returns pointer to next object in particle's HGrid level & cell.
BaseParticle * getHGridPrevObject () const
Returns pointer to previous object in particle's HGrid level & cell.
int getHGridX () const
Returns particle's HGrid cell X-coordinate.
int getHGridY () const
Returns particle's HGrid cell Y-coordinate.
int getHGridZ () const
Returns particle's HGrid cell Z-coordinate.
MatrixSymmetric3D getInvInertia () const
Returns the inverse of the particle's inertia tensor.
Mdouble getInvMass () const override
Returns the inverse of the particle's mass.
Mdouble getCurvature (const Vec3D &labFixedCoordinates) const override
virtual Mdouble getKineticEnergy () const
Calculates the particle's translational kinetic energy.
virtual Mdouble getRotationalEnergy () const
Calculates the particle's rotational kinetic energy.
Mdouble getGravitationalEnergy () const
Calculates the particle's gravitational energy.
Mdouble getMass () const
Returns the particle's mass.
virtual Mdouble getSurfaceArea () const
Vec3D getMomentum () const
MatrixSymmetric3D getInertia () const
Vec3D getAngularMomentum () const
BaseParticle * getPeriodicFromParticle () const
Returns the 'original' particle this one's a periodic copy of.
Mdouble getRadius () const
Returns the particle's radius.
Mdouble getMaxInteractionRadius () const
Returns the particle's interaction radius, which might be different from radius_ (e.g., when dealing with wet particles)
Mdouble getInteractionDistance (const BaseInteractable *i) const
Returns the interactionDistance_ of the mixed species of this particle and the particle or wall i.
Mdouble getSumOfInteractionRadii (const BaseParticle *particle) const
returns the sum of the radii plus the interactionDistance
Mdouble getWallInteractionRadius (const BaseWall *wall) const
returns the radius plus the interactionDistance
const Vec3D & getPreviousPosition () const
Returns the particle's position in the previous time step.
const Vec3D getDisplacement2 (Mdouble xmin, Mdouble xmax, Mdouble ymin, Mdouble ymax, Mdouble zmin, Mdouble zmax, Mdouble t) const
virtual void setInertia ()
void setInertia (MatrixSymmetric3D inertia)
Sets the particle's inertia_ (and adjusts invInertia_ accordingly)
void setInverseInertia (MatrixSymmetric3D inverseInertia)
Sets the particle's inertia_ (and adjusts invInertia_ accordingly)
void setInfiniteInertia ()
Sets the particle's inertia_ to 'infinite' (1e20) and its invInertia_ to 0.
void setPeriodicFromParticle (BaseParticle *p)
Assigns the pointer to the 'original' particle this one's a periodic copy of (used in periodic boundary condition implementations).
void setHGridX (const int x)
Sets the particle's HGrid cell X-coordinate.
void setHGridY (const int y)
Sets the particle's HGrid cell Y-coordinate.
void setHGridZ (const int z)
Sets the particle's HGrid cell Z-coordinate.
void setHGridLevel (const unsigned int level)
Sets the particle's HGrid level.
void setHGridNextObject (BaseParticle *p)
Sets the pointer to the next object in the particle's HGrid cell & level.
void setHGridPrevObject (BaseParticle *p)
Sets the pointer to the previous object in the particle's HGrid cell & level.
virtual void setRadius (Mdouble radius)
Sets the particle's radius_ (and adjusts the mass_ accordingly, based on the particle's species)
virtual Vec3D getAxes () const
Only ustilised in case of superquadric particles. Had to create a virtual function to allow function access in writeVTK function in the particle handler.
virtual Mdouble getExponentEps1 () const
Only ustilised in case of superquadric particles. Had to create a virtual function to allow function access in writeVTK function in the particle handler.
virtual Mdouble getExponentEps2 () const
Only ustilised in case of superquadric particles. Had to create a virtual function to allow function access in writeVTK function in the particle handler.
virtual void setAxes (const Vec3D &axes)
Only ustilised in case of superquadric particles.
virtual void setExponents (const Mdouble &eps1, const Mdouble &eps2)
Only ustilised in case of superquadric particles.
MERCURYDPM_DEPRECATED void setMass (Mdouble mass)
Sets the particle's mass.
void setMassForP3Statistics (Mdouble mass)
Sets the particle's mass This function should not be used, but is necessary to extend the CG toolbox to non-spherical particles.
void setPreviousPosition (const Vec3D &pos)
Sets the particle's position in the previous time step.
void movePrevious (const Vec3D &posMove)
Adds a vector to the particle's previousPosition_.
void accelerate (const Vec3D &vel)
Increases the particle's velocity_ by the given vector.
void angularAccelerate (const Vec3D &angVel)
Increases the particle's angularVelocity_ by the given vector.
void setHandler (ParticleHandler *handler)
Sets the pointer to the particle's ParticleHandler.
ParticleHandler * getHandler () const
Returns pointer to the particle's ParticleHandler.
BaseInteraction * getInteractionWith (BaseParticle *P, unsigned timeStamp, InteractionHandler *interactionHandler) override
Checks if particle is in interaction with given particle P, and if so, returns vector of pointer to the associated BaseInteraction object (else returns empty vector).
virtual bool isInContactWith (const BaseParticle *P) const
Get whether or not this particle is in contact with the given particle.
virtual void integrateBeforeForceComputation (double time, double timeStep)
First step of Velocity Verlet integration.
virtual void integrateAfterForceComputation (double time, double timeStep)
Second step of Velocity Verlet integration.
unsigned int getParticleDimensions () const
Returns the particle's dimensions (either 2 or 3).
MERCURYDPM_DEPRECATED void setIndSpecies (unsigned int indSpecies) override
virtual void setSpecies (const ParticleSpecies *species)
virtual void actionsBeforeTimeStep ()
virtual unsigned getNumberOfFieldsVTK () const
virtual std::string getTypeVTK (unsigned i) const
virtual std::string getNameVTK (unsigned i) const
virtual std::vector< Mdouble > getFieldVTK (unsigned i) const
virtual void actionsAfterTimeStep ()
virtual bool isSphericalParticle () const =0
const HGridCell & getHGridCell () const
virtual void computeMass (const ParticleSpecies &s)
Computes the particle's (inverse) mass and inertia.
BaseParticle * getClump () const
bool isClump () const
Checks if particle is a clump (container)
bool isPebble () const
Checks if particle is a pebble (belongs to a clump)
virtual Vec3D getCenterOfMass ()
virtual void actionsAfterAddObject ()
Public Member Functions inherited from BaseInteractable
BaseInteractable ()
Default BaseInteractable constructor.
BaseInteractable (const BaseInteractable &p)
Copy constructor.
~BaseInteractable () override
Destructor, it simply destructs the BaseInteractable and all the objects it contains.
unsigned int getIndSpecies () const
Returns the index of the species associated with the interactable object.
const ParticleSpecies * getSpecies () const
Returns a pointer to the species of this BaseInteractable.
void setSpecies (const ParticleSpecies *species)
Sets the species of this BaseInteractable.
const Vec3D & getForce () const
Returns the force on this BaseInteractable.
const Vec3D & getTorque () const
Returns the torque on this BaseInteractable.
void setForce (const Vec3D &force)
Sets the force on this BaseInteractable.
void setTorque (const Vec3D &torque)
Sets the torque on this BaseInteractable.
void addForce (const Vec3D &addForce)
Adds an amount to the force on this BaseInteractable.
void addTorque (const Vec3D &addTorque)
Adds an amount to the torque on this BaseInteractable.
virtual void resetForceTorque (int numberOfOMPthreads)
void sumForceTorqueOMP ()
const Vec3D & getPosition () const
Returns the position of this BaseInteractable.
const Quaternion & getOrientation () const
Returns the orientation of this BaseInteractable.
virtual void setPosition (const Vec3D &position)
Sets the position of this BaseInteractable.
void setOrientationViaNormal (Vec3D normal)
Sets the orientation of this BaseInteractable by defining the vector that results from the rotation of the (1,0,0) vector.
void setOrientationViaEuler (Vec3D eulerAngle)
Sets the orientation of this BaseInteractable by defining the euler angles.
virtual void setOrientation (const Quaternion &orientation)
Sets the orientation of this BaseInteractable.
virtual void move (const Vec3D &move)
Moves this BaseInteractable by adding an amount to the position.
virtual void rotate (const Vec3D &angularVelocityDt)
Rotates this BaseInteractable.
const std::vector< BaseInteraction * > & getInteractions () const
Returns a list of interactions which belong to this interactable.
void addInteraction (BaseInteraction *I)
Adds an interaction to this BaseInteractable.
bool removeInteraction (BaseInteraction *I)
Removes an interaction from this BaseInteractable.
void copyInteractionsForPeriodicParticles (const BaseInteractable &p)
Copies interactions to this BaseInteractable whenever a periodic copy made.
void setVelocity (const Vec3D &velocity)
set the velocity of the BaseInteractable.
void setAngularVelocity (const Vec3D &angularVelocity)
set the angular velocity of the BaseInteractble.
void addVelocity (const Vec3D &velocity)
adds an increment to the velocity.
void addAngularVelocity (const Vec3D &angularVelocity)
add an increment to the angular velocity.
virtual const Vec3D & getVelocity () const
Returns the velocity of this interactable.
virtual const Vec3D & getAngularVelocity () const
Returns the angular velocity of this interactable.
void setPrescribedPosition (const std::function< Vec3D(double)> &prescribedPosition)
Allows the position of an infinite mass interactable to be prescribed.
void applyPrescribedPosition (double time)
Computes the position from the user defined prescribed position function.
void setPrescribedVelocity (const std::function< Vec3D(double)> &prescribedVelocity)
Allows the velocity of an infinite mass interactable to be prescribed.
void applyPrescribedVelocity (double time)
Computes the velocity from the user defined prescribed velocity function.
void setPrescribedOrientation (const std::function< Quaternion(double)> &prescribedOrientation)
Allows the orientation of the infinite mass interactbale to be prescribed.
void applyPrescribedOrientation (double time)
Computes the orientation from the user defined prescribed orientation function.
void setPrescribedAngularVelocity (const std::function< Vec3D(double)> &prescribedAngularVelocity)
Allows the angular velocity of the infinite mass interactable to be prescribed.
void applyPrescribedAngularVelocity (double time)
Computes the angular velocity from the user defined prescribed angular velocity.
virtual const Vec3D getVelocityAtContact (const Vec3D &contact) const
Returns the velocity at the contact point, use by many force laws.
void integrateBeforeForceComputation (double time, double timeStep)
This is part of integrate routine for objects with infinite mass.
void integrateAfterForceComputation (double time, double timeStep)
This is part of the integration routine for objects with infinite mass.
virtual bool isFaceContact (const Vec3D &normal) const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Public Attributes
Mdouble radius_
Mdouble invMass_
Particle radius_.
MatrixSymmetric3D invInertia_
Inverse Particle mass (for computation optimization)
BaseParticle * clumpParticle_
Function that updates necessary quantities of a clump particle after adding a pebble.
bool isPebble_
pointer to a clump particle (for a pebble)
bool isClump_
The particle is pebble.
Private Attributes
ParticleHandler * handler_
Inverse Particle inverse inertia (for computation optimization)
HGridCell hGridCell
BaseParticle * hGridNextObject_
BaseParticle * hGridPrevObject_
Pointer to the next Particle in the same HGrid cell.
BaseParticle * periodicFromParticle_
Pointer to the previous Particle in the same HGrid cell.
bool isMPIParticle_
Pointer to originating Particle.
bool isInMPIDomain_
returns true if the particle acts as an MPI particle instead of a real particle
unsigned communicationComplexity_
returns true if it flagged as being in MPI domain
bool isInPeriodicDomain_
bool isPeriodicGhostParticle_
bool that indicates if a particle is in the periodic domain of any boundary
std::vector< int > previousPeriodicComplexity_
Indicates if the particle is a ghost particle of a periodic particle.
std::vector< int > periodicComplexity_
Indicates the periodic complexity at previous time step.
bool isMaserParticle_
Indicates the periodic complexity at current time step. Used to update periodic status.
Vec3D previousPosition_
Indicates if this particle belongs to the maser boundary or is released into the wide open world.
Mdouble info_
unsigned timeStamp_
Friends
void ParticleSpecies::computeMass (BaseParticle *) const
Particle's position at previous time step.
Detailed Description
Since r3648, BaseParticle is an abstract class. Use SphericalParticle for a 'basic' particle.
Constructor & Destructor Documentation
BaseParticle() [1/3]
BaseParticle::BaseParticle ()
Basic Particle constructor, creates an Particle at (0,0,0) with radius, mass and inertia equal to 1.
default constructor, creates an Particle at (0,0,0) with radius, mass and inertia equal to 1
         : BaseInteractable()
 {
     handler_ = nullptr;
     radius_ = 1.0;
     invMass_ = 1.0;
     invInertia_ = MatrixSymmetric3D(1, 0, 0, 1, 0, 1);
     previousPosition_=getPosition();
     periodicFromParticle_ = nullptr;
     isMPIParticle_ = false;
     isInMPIDomain_ = false;
     isInPeriodicDomain_ = false;
     isPeriodicGhostParticle_ = false;
     isMaserParticle_ = false;
     communicationComplexity_ = 0;
     periodicComplexity_ = std::vector<int>(0);
     previousPeriodicComplexity_ = std::vector<int>(0);
 #ifdef CONTACT_LIST_HGRID
     firstPossibleContact = nullptr;
 #endif
     hGridNextObject_ = nullptr;
     hGridPrevObject_ = nullptr;
     hGridCell.setHGridLevel(99999);
     hGridCell.setHGridX(99999);
     hGridCell.setHGridY(99999);
     hGridCell.setHGridZ(99999);
     info_ = std::numeric_limits<double>::quiet_NaN();
     timeStamp_ = 0;
     isClump_ = false;
     isPebble_ = false;
     logger(DEBUG, "BaseParticle::BaseParticle() finished");
 }
References communicationComplexity_, DEBUG, BaseInteractable::getPosition(), handler_, hGridCell, hGridNextObject_, hGridPrevObject_, info_, invInertia_, invMass_, isClump_, isInMPIDomain_, isInPeriodicDomain_, isMaserParticle_, isMPIParticle_, isPebble_, isPeriodicGhostParticle_, logger, periodicComplexity_, periodicFromParticle_, previousPeriodicComplexity_, previousPosition_, radius_, HGridCell::setHGridLevel(), HGridCell::setHGridX(), HGridCell::setHGridY(), HGridCell::setHGridZ(), and timeStamp_.
BaseParticle() [2/3]
BaseParticle::BaseParticle (const BaseParticle & p)
Particle copy constructor, which accepts as input a reference to a Particle. It creates a copy of this Particle and all it's information. Usually it is better to use the copy() function for polymorphism.
Constructor that copies most of the properties of the given particle. Please note that not everything is copied, for example the position in the HGrid is not determined yet by the end of this constructor. It also does not copy the interactions and the pointer to the handler that handles this particle. Use with care.
Parameters
[in,out] p Reference to the BaseParticle this one should become a copy of.
         : BaseInteractable(p)
 {
     handler_ = nullptr;
     radius_ = p.radius_;
     invMass_ = p.getInvMass();
     invInertia_ = p.getInvInertia();
     previousPosition_ = p.previousPosition_;
     hGridNextObject_ = nullptr;
     hGridPrevObject_ = nullptr;
     hGridCell.setHGridLevel(p.getHGridLevel());
     hGridCell.setHGridX(99999);
     hGridCell.setHGridY(99999);
     hGridCell.setHGridZ(99999);
     periodicFromParticle_ = p.periodicFromParticle_;
     isMPIParticle_ = p.isMPIParticle_;
     isInMPIDomain_ = p.isInMPIDomain_;
     isInPeriodicDomain_ = p.isInPeriodicDomain_;
     isMaserParticle_ = p.isMaserParticle_;
     isPeriodicGhostParticle_ = p.isPeriodicGhostParticle_;
     communicationComplexity_ = p.communicationComplexity_;
     isClump_ = p.isClump();
     isPebble_ = p.isPebble();
     //periodicComplexity_ = p.periodicComplexity_;
     //previousPeriodicComplexity_ = p.previousPeriodicComplexity_;
 #ifdef CONTACT_LIST_HGRID
     firstPossibleContact = nullptr;
 #endif
     info_ = p.info_;
     timeStamp_ = p.timeStamp_;
     logger(DEBUG, "BaseParticle::BaseParticle(BaseParticle &p) finished");
 }
References communicationComplexity_, DEBUG, handler_, hGridCell, hGridNextObject_, hGridPrevObject_, info_, invInertia_, invMass_, isClump_, isInMPIDomain_, isInPeriodicDomain_, isMaserParticle_, isMPIParticle_, isPebble_, isPeriodicGhostParticle_, logger, p, periodicFromParticle_, previousPosition_, radius_, HGridCell::setHGridLevel(), HGridCell::setHGridX(), HGridCell::setHGridY(), HGridCell::setHGridZ(), and timeStamp_.
BaseParticle() [3/3]
BaseParticle::BaseParticle (const ParticleSpecies * s) explicit
         : BaseParticle()
 {
     setSpecies(s);
 #ifdef CONTACT_LIST_HGRID
     firstPossibleContact = nullptr;
 #endif
     logger(DEBUG, "BaseParticle::BaseParticle(BaseSpecies &s) finished");
 }
References DEBUG, logger, s, and setSpecies().
~BaseParticle()
BaseParticle::~BaseParticle () override
Particle destructor, needs to be implemented and checked if it removes tangential spring information.
Destructor. It asks the ParticleHandler to check if this was the smallest or largest particle and adjust itself accordingly.
 {
     if (getHandler() != nullptr)
     {
         getHandler()->checkExtremaOnDelete(this);
         if (isFixed())
             getHandler()->removedFixedParticle();
     }
     logger(DEBUG, "BaseParticle::~BaseParticle() of particle % finished.", getId());
 }
References ParticleHandler::checkExtremaOnDelete(), DEBUG, getHandler(), BaseObject::getId(), isFixed(), logger, and ParticleHandler::removedFixedParticle().
Member Function Documentation
accelerate()
void BaseParticle::accelerate (const Vec3D & vel)
Increases the particle's velocity_ by the given vector.
increases the the particle's velocity_ (BaseInteractable member) by adding the given vector.
Parameters
[in] vel vector to be added to the velocity_
 {
     addVelocity(vel);
 }
References BaseInteractable::addVelocity().
Referenced by integrateAfterForceComputation(), ClumpParticle::integrateAfterForceComputation(), integrateBeforeForceComputation(), ClumpParticle::integrateBeforeForceComputation(), and MovingIntersectionOfWallsUnitTest_MovingReferenceFrame::setupInitialConditions().
actionsAfterAddObject()
virtual void BaseParticle::actionsAfterAddObject () inline virtual
Methods and attributes necessary for clumped particles
Reimplemented in ClumpParticle.
 {}
actionsAfterTimeStep()
virtual void BaseParticle::actionsAfterTimeStep () inline virtual
 {}
actionsBeforeTimeStep()
virtual void BaseParticle::actionsBeforeTimeStep () inline virtual
 {}
angularAccelerate()
void BaseParticle::angularAccelerate (const Vec3D & angVel)
Increases the particle's angularVelocity_ by the given vector.
increases the particle's angularVelocity_ (BaseInteractable member) by adding the given vector.
Parameters
[in] angVel vector to be added to the angularVelocity_
 {
     addAngularVelocity(angVel);
 }
References BaseInteractable::addAngularVelocity().
Referenced by integrateAfterForceComputation(), and integrateBeforeForceComputation().
computeMass()
void BaseParticle::computeMass (const ParticleSpecies & s) virtual
Computes the particle's (inverse) mass and inertia.
Reimplemented in SuperQuadricParticle, and ClumpParticle.
{
     if (isFixed()) return;
     if (getParticleDimensions()==3) {
         invMass_ = 1.0 / (4.0 / 3.0 * constants::pi * getRadius() * getRadius() * getRadius() * s.getDensity());
         invInertia_ = MatrixSymmetric3D(1, 0, 0, 1, 0, 1) / (.4 * getMass() * mathsFunc::square(getRadius()));
     } else {
         invMass_ = 1.0 / (constants::pi * getRadius() * getRadius() * s.getDensity());
         invInertia_ = MatrixSymmetric3D(1, 0, 0, 1, 0, 1) / (.5 * getMass() * mathsFunc::square(getRadius()));
     }
 };
References getMass(), getParticleDimensions(), getRadius(), invInertia_, invMass_, isFixed(), constants::pi, s, and mathsFunc::square().
Referenced by ChuteWithContraction::create_inflow_particle().
copy()
virtual BaseParticle* BaseParticle::copy () const pure virtual
Particle copy method. It calls to copy constructor of this Particle, useful for polymorphism.
Implemented in NonSphericalParticle, SuperQuadricParticle, SphericalParticle, and ClumpParticle.
Referenced by ChuteWithPeriodicInflow::AddContinuingBottom(), PolydisperseInsertionBoundary::addGenerandum(), ContractionWithPeriodicInflow::ContractionWithPeriodicInflow(), CurvyChute::createBottom(), PeriodicBoundary::createGhostParticle(), TimeDependentPeriodicBoundary::createGhostParticle(), ChuteWithPeriodicInflow::ExtendInWidth(), BidisperseCubeInsertionBoundary::generateParticle(), PeriodicBoundaryHandler::processLocalGhostParticles(), DPMBase::readNextDataFile(), CurvyChute::setBasalPrototype(), PolydisperseInsertionBoundary::setGenerandum(), and InsertionBoundary::setParticleToCopy().
fixParticle()
void BaseParticle::fixParticle ()
Fix Particle function. It fixes a Particle by setting its inverse mass and inertia and velocities to zero.
Fixes a BaseParticle by setting its inverse mass and inertia and velocities to zero.
 {
 //    //
 //    Clump f;
 //    f.invInertia2_ = MatrixSymmetric3D(0, 0, 0, 0, 0, 0);
     //
     invMass_ = 0.0;
     invInertia_ = MatrixSymmetric3D(0, 0, 0, 0, 0, 0);
     setVelocity(Vec3D(0.0, 0.0, 0.0));
     setAngularVelocity(Vec3D(0.0, 0.0, 0.0));
     if (getHandler())
         getHandler()->addedFixedParticle();
 }
References ParticleHandler::addedFixedParticle(), getHandler(), invInertia_, invMass_, BaseInteractable::setAngularVelocity(), and BaseInteractable::setVelocity().
Referenced by LawinenBox::LawinenBox(), ParticleBeam::ParticleBeam(), DPMBase::setFixedParticles(), Cstatic2d::setupInitialConditions(), Cstatic3D::setupInitialConditions(), and SphericalIndenter::setupInitialConditions().
getAngularMomentum()
Vec3D BaseParticle::getAngularMomentum () const
 {
     return invInertia_.inverse()*getAngularVelocity() + Vec3D::cross(getPosition(),getVelocity()) / invMass_;
 }
References Vec3D::cross(), BaseInteractable::getAngularVelocity(), BaseInteractable::getPosition(), BaseInteractable::getVelocity(), MatrixSymmetric3D::inverse(), invInertia_, and invMass_.
getAxes()
Vec3D BaseParticle::getAxes () const virtual
Only ustilised in case of superquadric particles. Had to create a virtual function to allow function access in writeVTK function in the particle handler.
Reimplemented in SuperQuadricParticle.
 { return Vec3D(0, 0, 0); }
getCenterOfMass()
virtual Vec3D BaseParticle::getCenterOfMass () inline virtual
 {return Vec3D(0,0,0);}
getClump()
BaseParticle* BaseParticle::getClump () const inline
     {
         return clumpParticle_;
     }
References clumpParticle_.
Referenced by Mercury3Dclump::computeInternalForce().
getCommunicationComplexity()
unsigned BaseParticle::getCommunicationComplexity ()
Obtains the communication complexity of the particle.
 {
     return communicationComplexity_;
 }
References communicationComplexity_.
Referenced by Domain::updateParticles().
getCurvature()
Mdouble BaseParticle::getCurvature (const Vec3D & labFixedCoordinates) const inline override virtual
returns the inverse radius, or curvature, of the surface. This value is zero for walls and gets overridden for particles that have finite radius
Todo:
should be wall-type dependent
Reimplemented from BaseInteractable.
Reimplemented in SuperQuadricParticle.
     { return 1.0/radius_; }
References radius_.
getDisplacement2()
const Vec3D BaseParticle::getDisplacement2 (Mdouble xmin, Mdouble xmax, Mdouble ymin, Mdouble ymax, Mdouble zmin, Mdouble zmax, Mdouble t) const
Todo:
see .cc file. \TWH
Todo:
Rewrite, redefine (TW). Is only used in StatisticsVector.hcc, consider moving to that class.
 {
     Vec3D disp = getPosition() - getPreviousPosition();
     if (xmax > xmin && fabs(disp.X) > .5 * (xmax - xmin))
     {
         if (disp.X > 0)
             disp.X -= xmax - xmin;
         else
             disp.X += xmax - xmin;
     }
     if (ymax > ymin && fabs(disp.Y) > .5 * (ymax - ymin))
     {
         if (disp.Y > 0)
             disp.Y -= ymax - ymin;
         else
             disp.Y += ymax - ymin;
     }
     if (zmax > zmin && fabs(disp.Z) > .5 * (zmax - zmin))
     {
         if (disp.Z > 0)
             disp.Z -= zmax - zmin;
         else
             disp.Z += zmax - zmin;
     }
     disp /= t;
     return disp;
 }
References boost::multiprecision::fabs(), BaseInteractable::getPosition(), getPreviousPosition(), plotPSD::t, Vec3D::X, Vec3D::Y, Vec3D::Z, Global_Parameters::zmax, and Global_Parameters::zmin.
getExponentEps1()
double BaseParticle::getExponentEps1 () const virtual
Only ustilised in case of superquadric particles. Had to create a virtual function to allow function access in writeVTK function in the particle handler.
Reimplemented in SuperQuadricParticle.
 { return 0; }
getExponentEps2()
double BaseParticle::getExponentEps2 () const virtual
Only ustilised in case of superquadric particles. Had to create a virtual function to allow function access in writeVTK function in the particle handler.
Reimplemented in SuperQuadricParticle.
 { return 0; }
getFieldVTK()
std::vector< Mdouble > BaseParticle::getFieldVTK (unsigned i) const virtual
Reimplemented in ClumpParticle.
 {
     return std::vector<Mdouble>();
 }
getGravitationalEnergy()
Mdouble BaseParticle::getGravitationalEnergy () const
Calculates the particle's gravitational energy.
Gravitational energy is the potential energy stored in teh particles position due to the gravity field. This is a relative term, so we need to define what zero energy means: The gravitational energy of a particle is zero when its center of mass is at the origin.
Returns
the particle's gravitational energy
getHandler()
ParticleHandler * BaseParticle::getHandler () const
Returns pointer to the particle's ParticleHandler.
Returns the particle's ParticleHandler
Returns
pointer to the particle's ParticleHandler; null if handler not yet specified
 {
     return handler_;
 }
References handler_.
Referenced by ClumpParticle::actionsAfterAddObject(), HeatFluidCoupledSpecies< NormalForceSpecies >::actionsAfterTimeStep(), fixParticle(), getParticleDimensions(), getPeriodicComplexity(), SuperQuadricParticle::getVolume(), integrateAfterForceComputation(), integrateBeforeForceComputation(), ClumpParticle::integrateBeforeForceComputation(), setHandler(), setPeriodicComplexity(), setRadius(), unfix(), ~BaseParticle(), and SuperQuadricParticle::~SuperQuadricParticle().
getHGridCell()
const HGridCell& BaseParticle::getHGridCell () const inline
     { return hGridCell; }
References hGridCell.
Referenced by Mercury3D::hGridFindContactsWithinTargetCell(), Mercury2D::hGridFindContactsWithinTargetCell(), Mercury3D::hGridFindContactsWithTargetCell(), Mercury2D::hGridFindContactsWithTargetCell(), and Mercury3D::hGridRemoveParticle().
getHGridLevel()
unsigned int BaseParticle::getHGridLevel () const inline
Returns particle's HGrid level.
     { return hGridCell.getHGridLevel(); }
References HGridCell::getHGridLevel(), and hGridCell.
Referenced by Mercury2D::computeInternalForces(), Mercury3D::computeInternalForces(), Mercury2D::hGridGetInteractingParticleList(), Mercury3D::hGridGetInteractingParticleList(), Mercury2D::hGridRemoveParticle(), MercuryBase::hGridUpdateMove(), Mercury2D::hGridUpdateParticle(), and Mercury3D::hGridUpdateParticle().
getHGridNextObject()
BaseParticle* BaseParticle::getHGridNextObject () const inline
Returns pointer to next object in particle's HGrid level & cell.
Returns the next object in the particle's HGrid cell
Returns
pointer to the next object in the particle's HGrid cell
     { return hGridNextObject_; }
References hGridNextObject_.
Referenced by Mercury3D::hGridFindContactsWithinTargetCell(), Mercury2D::hGridFindContactsWithinTargetCell(), Mercury2D::hGridRemoveParticle(), and Mercury3D::hGridRemoveParticle().
getHGridPrevObject()
BaseParticle* BaseParticle::getHGridPrevObject () const inline
Returns pointer to previous object in particle's HGrid level & cell.
Returns the previous object in the particle's HGrid cell
Returns
pointer to the previous object in the particle's HGrid cell
     { return hGridPrevObject_; }
References hGridPrevObject_.
Referenced by Mercury2D::hGridRemoveParticle(), and Mercury3D::hGridRemoveParticle().
getHGridX()
int BaseParticle::getHGridX () const inline
Returns particle's HGrid cell X-coordinate.
Returns
the particle's HGrid cell's X-coordinate
     { return hGridCell.getHGridX(); }
References HGridCell::getHGridX(), and hGridCell.
Referenced by Mercury2D::computeInternalForces(), Mercury3D::computeInternalForces(), Mercury2D::hGridRemoveParticle(), Mercury2D::hGridUpdateParticle(), and Mercury3D::hGridUpdateParticle().
getHGridY()
int BaseParticle::getHGridY () const inline
Returns particle's HGrid cell Y-coordinate.
Returns
the particle's HGrid cell's Y-coordinate
     { return hGridCell.getHGridY(); }
References HGridCell::getHGridY(), and hGridCell.
Referenced by Mercury2D::computeInternalForces(), Mercury3D::computeInternalForces(), Mercury2D::hGridRemoveParticle(), Mercury2D::hGridUpdateParticle(), and Mercury3D::hGridUpdateParticle().
getHGridZ()
int BaseParticle::getHGridZ () const inline
Returns particle's HGrid cell Z-coordinate.
Returns
the particle's HGrid cell's Z-coordinate
     { return hGridCell.getHGridZ(); }
References HGridCell::getHGridZ(), and hGridCell.
Referenced by Mercury3D::computeInternalForces(), and Mercury3D::hGridUpdateParticle().
getInertia()
MatrixSymmetric3D BaseParticle::getInertia () const inline
     { return invInertia_.inverse(); }
References MatrixSymmetric3D::inverse(), and invInertia_.
Referenced by ClumpParticle::angularAccelerateClumpIterative(), getRotationalEnergy(), and ClumpParticle::getRotationalEnergy().
getInfo()
Mdouble BaseParticle::getInfo () const virtual
Returns some user-defined information about this object (by default, species ID).
 {
     if (std::isnan(info_))
         return getSpecies()->getId();
     else
         return info_;
 }
References BaseObject::getId(), BaseInteractable::getSpecies(), info_, and isnan.
getInteractionDistance()
Mdouble BaseParticle::getInteractionDistance (const BaseInteractable * i) const inline
Returns the interactionDistance_ of the mixed species of this particle and the particle or wall i.
     {
         //const auto mixedSpecies = getSpecies()->getHandler()->getMixedObject(getSpecies(),particle->getSpecies());
         //return mixedSpecies->getInteractionDistance();
         return getSpecies()->getMixedSpecies(i->getSpecies())->getInteractionDistance();
     }
References BaseSpecies::getInteractionDistance(), ParticleSpecies::getMixedSpecies(), BaseInteractable::getSpecies(), and i.
Referenced by getSumOfInteractionRadii(), and getWallInteractionRadius().
getInteractionWith()
BaseInteraction * BaseParticle::getInteractionWith (BaseParticle * P, unsigned timeStamp, InteractionHandler * interactionHandler) override virtual
Checks if particle is in interaction with given particle P, and if so, returns vector of pointer to the associated BaseInteraction object (else returns empty vector).
Creates/updates a BaseInteraction object, treating the interaction between this particle and a given one, in case there is an overlap between the two.
Parameters
[in] P particle to check the interaction with
[in] timeStamp time stamp to be assigned to the interaction object (i.e., the current time)
[in,out] interactionHandler BaseInteraction container from where the interaction is retrieved, and to which it is assigned (if it is a new interaction).
Returns
the pointer to the interaction object (if the particles overlap), or 0 (if they don't overlap).
Implements BaseInteractable.
Reimplemented in SuperQuadricParticle.
 {
     //get the normal (from P away from the contact)
     const Vec3D branchVector = P->getPosition() - getPosition();
     //Get the square of the distance between particle i and particle j
     const Mdouble distanceSquared = Vec3D::getLengthSquared(branchVector);
     //const auto species = interactionHandler->getDPMBase()->speciesHandler.getMixedObject(getSpecies(),P->getSpecies());
     const Mdouble sumOfInteractionRadii = getSumOfInteractionRadii(P);
     if (distanceSquared >= sumOfInteractionRadii * sumOfInteractionRadii) {
         return nullptr;
     }
     BaseInteraction* const C = interactionHandler->getInteraction(P, this, timeStamp);
     const Mdouble distance = std::sqrt(distanceSquared);
     C->setNormal(branchVector / distance);
     C->setOverlap(P->getRadius() + getRadius() - distance);
     C->setDistance(distance);
     C->setContactPoint(P->getPosition() - (P->getRadius() - 0.5 * C->getOverlap()) * C->getNormal());
     // The above contact point was chosen historically. It is not clear whether
     // the current implementation or the two lines below are correct or incorrect.
     // If solid arguments for the lines below are presented, it can be rediscussed.
     // If so, also BaseWall::getInteractionWith should be adapted.
     //Mdouble ratio=P->getRadius()/(getRadius()+P->getRadius());
     //C->setContactPoint(P->getPosition() - (P->getRadius() - ratio * C->getOverlap()) * C->getNormal());
     return C;
 }
References InteractionHandler::getInteraction(), Vec3D::getLengthSquared(), BaseInteractable::getPosition(), getRadius(), getSumOfInteractionRadii(), Global_Physical_Variables::P, and sqrt().
Referenced by SphericalSuperQuadricCollision::actionsAfterTimeStep(), ContactDetectionRotatedSpheresTest::actionsAfterTimeStep(), DPMBase::computeInternalForce(), PeriodicBoundaryHandler::processLocalInteractionData(), PeriodicBoundaryHandler::processReceivedInteractionData(), and Domain::processReceivedInteractionData().
getInvInertia()
MatrixSymmetric3D BaseParticle::getInvInertia () const inline
Returns the inverse of the particle's inertia tensor.
Returns
the inverse of the particle's inertia tensor
     { return invInertia_; }
References invInertia_.
Referenced by integrateAfterForceComputation(), and integrateBeforeForceComputation().
getInvMass()
Mdouble BaseParticle::getInvMass () const inline override virtual
Returns the inverse of the particle's mass.
Returns
the inverse of the particle's mass
Reimplemented from BaseInteractable.
     { return invMass_; }
References invMass_.
Referenced by integrateAfterForceComputation(), ClumpParticle::integrateAfterForceComputation(), integrateBeforeForceComputation(), and ClumpParticle::integrateBeforeForceComputation().
getKineticEnergy()
Mdouble BaseParticle::getKineticEnergy () const virtual
Calculates the particle's translational kinetic energy.
Returns
the particle's translational kinetic energy
Calculates the particle's kinetic energy
Returns
the particle's kinetic energy
Reimplemented in NonSphericalParticle, and ClumpParticle.
 {
     if (isFixed())
         return 0.0;
     else
         return 0.5 * getMass() * getVelocity().getLengthSquared();
     //
 }
References Vec3D::getLengthSquared(), getMass(), BaseInteractable::getVelocity(), and isFixed().
Referenced by NonSphericalParticle::getKineticEnergy().
getMass()
Mdouble BaseParticle::getMass () const inline
Returns the particle's mass.
Returns
the mass of the particle
     { return 1.0 / invMass_; }
References invMass_.
Referenced by LawinenBox::actionsBeforeTimeStep(), DPMBase::computeExternalForces(), VolumeCoupling::computeExternalForces(), ChuteWithPeriodicInflow::computeInternalForces(), computeMass(), ScalingTestInitialConditionsRelax::continueSolve(), getKineticEnergy(), LawinenBox::printTime(), free_cooling::setupInitialConditions(), restart::setupInitialConditions(), ParticleParticleCollision::setupInitialConditions(), WallParticleCollision::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), BaseCluster::setupInitialConditions(), and Slide::Slide().
getMaxInteractionRadius()
Mdouble BaseParticle::getMaxInteractionRadius () const inline
Returns the particle's interaction radius, which might be different from radius_ (e.g., when dealing with wet particles)
Calculates the interaction radius of the particle (when it comes to interaction with other particles), including the effect of a possible additional 'interaction distance' besides the 'normal' radius. The interaction radius differs from the radius_, for example, when dealing with wet particles (i.e. particles with an additional liquid layer, which is dealt with in the particle's species).
Returns
the particle's interaction radius for particle-particle interaction
{
         return getRadius() + getSpecies()->getMaxInteractionDistance() * 0.5;
     }
References ParticleSpecies::getMaxInteractionDistance(), getRadius(), and BaseInteractable::getSpecies().
Referenced by InsertionBoundary::checkBoundaryBeforeTimeStep(), Mercury3Dclump::checkClumpForInteractionPeriodic(), ParticleHandler::checkExtrema(), DPMBase::checkParticleForInteractionLocalPeriodic(), Mercury2D::computeInternalForces(), Mercury3D::computeInternalForces(), LeesEdwardsBoundary::createHorizontalPeriodicParticle(), ShearBoxBoundary::createHorizontalPeriodicParticle(), AngledPeriodicBoundary::createPeriodicParticle(), CircularPeriodicBoundary::createPeriodicParticle(), ConstantMassFlowMaserBoundary::createPeriodicParticle(), PeriodicBoundary::createPeriodicParticle(), SubcriticalMaserBoundary::createPeriodicParticle(), SubcriticalMaserBoundaryTEST::createPeriodicParticle(), TimeDependentPeriodicBoundary::createPeriodicParticle(), LeesEdwardsBoundary::createVerticalPeriodicParticle(), ShearBoxBoundary::createVerticalPeriodicParticle(), SuperQuadricParticle::getInteractionWith(), ParticleHandler::getLargestInteractionRadiusLocal(), ParticleHandler::getSmallestInteractionRadiusLocal(), Mercury3D::hGridFindContactsWithTargetCell(), Mercury2D::hGridFindParticleContacts(), Mercury3D::hGridFindParticleContacts(), Mercury2D::hGridGetInteractingParticleList(), Mercury3D::hGridGetInteractingParticleList(), Mercury2D::hGridHasParticleContacts(), Mercury3D::hGridHasParticleContacts(), MercuryBase::hGridNeedsRebuilding(), HGrid::insertParticleToHgrid(), and RotatingDrum::setupInitialConditions().
getMomentum()
Vec3D BaseParticle::getMomentum () const inline
     { return getVelocity() / invMass_; }
References BaseInteractable::getVelocity(), and invMass_.
getName()
std::string BaseParticle::getName () const override virtual
Returns the name of the object.
Returns the name of the object; in this case 'BaseParticle'.
Returns
The object name.
Implements BaseObject.
Reimplemented in NonSphericalParticle, SuperQuadricParticle, SphericalParticle, and ClumpParticle.
 {
     return "BaseParticle";
 }
getNameVTK()
std::string BaseParticle::getNameVTK (unsigned i) const virtual
Reimplemented in ClumpParticle.
 {
     return "";
 }
Referenced by ParticleVtkWriter::writeExtraFields().
getNumberOfFieldsVTK()
unsigned BaseParticle::getNumberOfFieldsVTK () const virtual
Reimplemented in ClumpParticle.
 {
     return 0;
 }
getParticleDimensions()
unsigned int BaseParticle::getParticleDimensions () const
Returns the particle's dimensions (either 2 or 3).
Returns the amount of dimensions of the particle (2 or 3, basically)
Returns
the number of dimension of the particle
 {
     return getHandler()->getDPMBase()->getParticleDimensions();
 }
References BaseHandler< T >::getDPMBase(), getHandler(), and DPMBase::getParticleDimensions().
Referenced by computeMass(), SuperQuadricParticle::computeMass(), and getVolume().
getPeriodicComplexity() [1/2]
const std::vector< int > & BaseParticle::getPeriodicComplexity ()
Obtains the periodic communication complexity of the particle.
Todo:
resolve this hack
 {
     //hack: generally you'd add particles after declaring the boundaries
     //but no official programming guildelines rules have been setup for that
     //So incase that doesnt happen we need to resize this periodicComplexity
     if (periodicComplexity_.empty())
     {
         const unsigned numberOfPeriodicBoundaries = getHandler()->getDPMBase()->periodicBoundaryHandler.getSize();
         if (numberOfPeriodicBoundaries > 0)
         {
             periodicComplexity_.resize(numberOfPeriodicBoundaries, 0);
         }
     }
     return periodicComplexity_;
 }
References BaseHandler< T >::getDPMBase(), getHandler(), BaseHandler< T >::getSize(), DPMBase::periodicBoundaryHandler, and periodicComplexity_.
Referenced by PeriodicBoundaryHandler::findNewParticle(), SubcriticalMaserBoundaryTEST::modifyGhostAfterCreation(), PeriodicBoundaryHandler::processLocalGhostParticles(), PeriodicBoundaryHandler::shiftParticle(), PeriodicBoundaryHandler::updateMaserParticle(), PeriodicBoundaryHandler::updateParticles(), and PeriodicBoundaryHandler::updateParticleStatus().
getPeriodicComplexity() [2/2]
int BaseParticle::getPeriodicComplexity (int index)
Gets the periodic communication complexity of a certain boundary.
Todo:
TW Marnix, this is indeed a hack; you should call a setter every time you add a value to the periodic boundary handler (this function takes 0.5% cpu time in the speedtest)
 {
     //hack: generally you'd add particles after declaring the boundaries
     //but no official programming guildelines rules have been setup for that
     //So incase that doesnt happen we need to resize this periodicComplexity
     if (periodicComplexity_.empty())
     {
         const unsigned numberOfPeriodicBoundaries = getHandler()->getDPMBase()->periodicBoundaryHandler.getSize();
         if (numberOfPeriodicBoundaries > 0)
         {
             periodicComplexity_.resize(numberOfPeriodicBoundaries, 0);
         }
     }
     return periodicComplexity_[index];
 }
References BaseHandler< T >::getDPMBase(), getHandler(), BaseHandler< T >::getSize(), DPMBase::periodicBoundaryHandler, and periodicComplexity_.
getPeriodicFromParticle()
BaseParticle* BaseParticle::getPeriodicFromParticle () const inline
Returns the 'original' particle this one's a periodic copy of.
Returns a pointer to the 'original' particle if the current one is a 'periodic copy' used for a periodic boundary implementation.
Returns
pointer to original particle
     { return periodicFromParticle_; }
References periodicFromParticle_.
Referenced by SilbertPeriodic::add_flow_particles(), ChuteWithPeriodicInflow::Check_and_Duplicate_Periodic_Particle(), DPMBase::computeForcesDueToWalls(), DPMBase::computeInternalForce(), ChuteWithPeriodicInflow::computeInternalForces(), WearableNurbsWall::computeWear(), WearableTriangleMeshWall::computeWear(), WearableTriangulatedWall::computeWear(), PeriodicBoundary::createGhostParticle(), TimeDependentPeriodicBoundary::createGhostParticle(), LeesEdwardsBoundary::createHorizontalPeriodicParticle(), ShearBoxBoundary::createHorizontalPeriodicParticle(), AngledPeriodicBoundary::createPeriodicParticle(), CircularPeriodicBoundary::createPeriodicParticle(), LeesEdwardsBoundary::createVerticalPeriodicParticle(), ShearBoxBoundary::createVerticalPeriodicParticle(), and DPMBase::removeDuplicatePeriodicParticles().
getPreviousPeriodicComplexity()
const std::vector< int > & BaseParticle::getPreviousPeriodicComplexity () const
Sets the previous periodic communication complexity of the particle.
 {
     return previousPeriodicComplexity_;
 }
References previousPeriodicComplexity_.
Referenced by PeriodicBoundaryHandler::updateParticles(), and PeriodicBoundaryHandler::updateParticleStatus().
getPreviousPosition()
const Vec3D& BaseParticle::getPreviousPosition () const inline
Returns the particle's position in the previous time step.
Returns the particle's position in the previous time step.
Returns
(reference to) the previous position of the particle
     { return previousPosition_; }
References previousPosition_.
Referenced by getDisplacement2(), and PeriodicBoundaryHandler::updateParticles().
getRadius()
Mdouble BaseParticle::getRadius () const inline
Returns the particle's radius.
Returns
the particle's radius
     { return radius_; }
References radius_.
Referenced by RotatingDrumBidisperseInitialise::actionsAfterTimeStep(), ConstantMassFlowMaserBoundary::activateMaser(), SilbertPeriodic::add_flow_particles(), statistics_while_running< T >::auto_set_domain(), statistics_while_running< T >::auto_set_z(), FixedClusterInsertionBoundary::checkBoundaryBeforeTimeStep(), InsertionBoundary::checkBoundaryBeforeTimeStep(), RandomClusterInsertionBoundary::checkBoundaryBeforeTimeStep(), Funnel::cleanChute(), CGHandler::computeContactPoints(), ChuteWithPeriodicInflow::computeInternalForces(), computeMass(), Funnel::create_funnel(), LawinenBox::create_inflow_particle(), ChuteWithContraction::create_inflow_particle(), AngleOfRepose::create_inflow_particle(), FlowRule::create_inflow_particle(), SilbertPeriodic::create_inflow_particle(), SegregationWithHopper::create_inflow_particle(), Slide::create_rough_wall(), Chute::createBottom(), CurvyChute::createBottom(), SphericalIndenter::getIndenterHeight(), SuperQuadricParticle::getInteractionRadius(), getInteractionWith(), getMaxInteractionRadius(), MarbleRun::getParticleMass(), ParticleHandler::getPSD(), ParticleParticleCollision::getRelativeVelocity(), WallParticleCollision::getRelativeVelocity(), getSumOfInteractionRadii(), getSurfaceArea(), getWallInteractionRadius(), LawinenBox::LawinenBox(), SphericalIndenter::outputXBallsData(), ChuteWithPeriodicInflow::outputXBallsDataParticlee(), SinterPair::printTime(), FileReader::read(), Slide::set_Walls(), SphericalIndenter::setIndenterHeight(), CFDDEMCoupleTest::setupInitialConditions(), ForceLawsMPI2Test::setupInitialConditions(), MarbleRun::setupInitialConditions(), statistics_while_running< T >::setupInitialConditions(), StressStrainControl::setupInitialConditions(), ParticleCreation::setupInitialConditions(), ParticleParticleCollision::setupInitialConditions(), WallParticleCollision::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), MovingWallTangential::setupInitialConditions(), ChuteBottom::setupInitialConditions(), Slide::Slide(), statistics_while_running< T >::statistics_while_running(), SingleParticle< SpeciesType >::writeEneTimeStep(), and DPMBase::writeFstatHeader().
getRotationalEnergy()
Mdouble BaseParticle::getRotationalEnergy () const virtual
Calculates the particle's rotational kinetic energy.
Returns
the particle's rotational kinetic energy
Reimplemented in NonSphericalParticle, and ClumpParticle.
 {
     if (isFixed())
         return 0.0;
     else
         return 0.5 * Vec3D::dot(getAngularVelocity(), getInertia() * getAngularVelocity());
 }
References Vec3D::dot(), BaseInteractable::getAngularVelocity(), getInertia(), and isFixed().
Referenced by NonSphericalParticle::getRotationalEnergy().
getSumOfInteractionRadii()
Mdouble BaseParticle::getSumOfInteractionRadii (const BaseParticle * particle) const inline
returns the sum of the radii plus the interactionDistance
{
         return getRadius() + particle->getRadius() + getInteractionDistance((const BaseInteractable*)particle);
     }
References getInteractionDistance(), and getRadius().
Referenced by Domain::findNewMPIInteractions(), SuperQuadricParticle::getInitialGuessForContact(), getInteractionWith(), and isInContactWith().
getSurfaceArea()
virtual Mdouble BaseParticle::getSurfaceArea () const inline virtual
Reimplemented in NonSphericalParticle.
     { return 4.0*constants::pi*getRadius()*getRadius(); }
References getRadius(), and constants::pi.
getTimeStamp()
unsigned BaseParticle::getTimeStamp () const
 {
     return timeStamp_;
 }
References timeStamp_.
getTypeVTK()
std::string BaseParticle::getTypeVTK (unsigned i) const virtual
Reimplemented in ClumpParticle.
 {
     return "";
 }
Referenced by ParticleVtkWriter::writeExtraFields().
getVolume()
Mdouble BaseParticle::getVolume () const virtual
Get Particle volume function, which required a reference to the Species vector. It returns the volume of the Particle.
Returns the volume of the BaseParticle, which is calculated using its number of dimensions and radius.
Returns
The actual volume of this BaseParticle.
Reimplemented in SuperQuadricParticle.
 {
     if (handler_ == nullptr)
     {
         logger(ERROR, "[BaseParticle::getVolume] no particle handler specified");
         return 0;
     }
     switch (getParticleDimensions())
     {
         case 3:
             return (4.0 / 3.0 * constants::pi * radius_ * radius_ * radius_);
         case 2:
             return (constants::pi * radius_ * radius_);
         case 1:
             return (2.0 * radius_);
         default:
             logger(ERROR, "[BaseParticle::getVolume] dimension of the particle is not set");
             return 0;
     }
 }
References ERROR, getParticleDimensions(), handler_, logger, constants::pi, and radius_.
Referenced by InsertionBoundary::checkBoundaryBeforeTimeStep(), ScaleCoupling< M, O >::computeProjectionMatrix(), and ExtremeOverlapVolumeUnitTest::setupInitialConditions().
getWallInteractionRadius()
Mdouble BaseParticle::getWallInteractionRadius (const BaseWall * wall) const inline
returns the radius plus the interactionDistance
{
         return getRadius() + getInteractionDistance((const BaseInteractable*)wall);
     }
References getInteractionDistance(), and getRadius().
Referenced by TriangleMeshWall::getDistanceAndNormal().
integrateAfterForceComputation()
void BaseParticle::integrateAfterForceComputation (double time, double timeStep) virtual
Second step of Velocity Verlet integration.
Second step of Velocity Verlet integration (see also http://en.wikipedia.org/wiki/Verlet_integration#Velocity_Verlet).
Parameters
[in] time current time
[in] timeStep current time step
Reimplemented in ClumpParticle.
 {
     if (getInvMass() == 0.0)
     {
         //Updates a baseParticle with a prescribed motion
         BaseInteractable::integrateAfterForceComputation(time, timeStep);
     }
     else
     {
         accelerate(getForce() * getInvMass() * 0.5 * timeStep);
         if (getHandler()->getDPMBase()->getRotation())
         {
             angularAccelerate(
                     getOrientation().rotateInverseInertiaTensor(getInvInertia()) * getTorque() * 0.5 * timeStep);
         }
     }
 }
References accelerate(), angularAccelerate(), BaseInteractable::getForce(), getHandler(), getInvInertia(), getInvMass(), BaseInteractable::getOrientation(), BaseInteractable::getTorque(), and BaseInteractable::integrateAfterForceComputation().
integrateBeforeForceComputation()
void BaseParticle::integrateBeforeForceComputation (double time, double timeStep) virtual
First step of Velocity Verlet integration.
First step of Velocity Verlet integration (see also http://en.wikipedia.org/wiki/Verlet_integration#Velocity_Verlet).
Parameters
[in] time current time
[in] timeStep current time step
Todo:
If the position is described by the user, one should also call BaseInteractable::integrateBeforeForceComputation. To check if it works correctly, remove the p0.fixParticle() line from the DrivenParticleUnitTest
Author
irana
Reimplemented in ClumpParticle.
 {
     if (getInvMass() == 0.0)
     {
         BaseInteractable::integrateBeforeForceComputation(time, timeStep);
     }
     else
     {
         // For periodic particles in parallel the previous position is required
         // also required by FluxBoundary
         setPreviousPosition(getPosition());
         accelerate(getForce() * getInvMass() * 0.5 * timeStep);
         const Vec3D displacement = getVelocity() * timeStep;
         move(displacement);
         DPMBase* const dpm = getHandler()->getDPMBase();
         if (!dpm->getHGridUpdateEachTimeStep())
         {
             dpm->hGridUpdateMove(this, displacement.getLengthSquared());
         }
         if (dpm->getRotation())
         {
             angularAccelerate(
                     getOrientation().rotateInverseInertiaTensor(getInvInertia()) * getTorque() * 0.5 * timeStep);
             //apply to rotation quaternion q: q = normalise(q + \tilde{C}\omega*timeStep) (see Wouter's notes)
             rotate(getAngularVelocity() * timeStep);
         }
     }
 }
References accelerate(), angularAccelerate(), BaseInteractable::getAngularVelocity(), BaseHandler< T >::getDPMBase(), BaseInteractable::getForce(), getHandler(), DPMBase::getHGridUpdateEachTimeStep(), getInvInertia(), getInvMass(), Vec3D::getLengthSquared(), BaseInteractable::getOrientation(), BaseInteractable::getPosition(), DPMBase::getRotation(), BaseInteractable::getTorque(), BaseInteractable::getVelocity(), DPMBase::hGridUpdateMove(), BaseInteractable::integrateBeforeForceComputation(), BaseInteractable::move(), BaseInteractable::rotate(), and setPreviousPosition().
isClump()
bool BaseParticle::isClump () const inline
Checks if particle is a clump (container)
     {
         return isClump_;
     }
References isClump_.
Referenced by ClumpParticle::actionsAfterAddObject(), Mercury3Dclump::checkClumpForInteraction(), Mercury3Dclump::checkClumpForInteractionPeriodic(), Mercury3Dclump::computeForcesDueToWalls(), Mercury3Dclump::computeInternalForce(), and ClumpParticle::computeMass().
isFixed()
bool BaseParticle::isFixed () const inline override virtual
Is fixed Particle function. It returns whether a Particle is fixed or not, by checking its inverse Mass.
Checks whether a BaseParticle is fixed or not, by checking its inverse Mass.
Returns
TRUE if particle is fixed, i.e. if the inverse mass (invMass_) is 0.
Implements BaseInteractable.
     { return (invMass_ == 0.0); }
References invMass_.
Referenced by LawinenBox::actionsBeforeTimeStep(), ChuteWithPeriodicInflow::AddContinuingBottom(), ChuteWithContraction::ChuteWithContraction(), ChuteWithPeriodicInflowAndContinuingBottom::ChuteWithPeriodicInflowAndContinuingBottom(), ChuteWithPeriodicInflowAndContraction::ChuteWithPeriodicInflowAndContraction(), ChuteWithPeriodicInflowAndVariableBottom::ChuteWithPeriodicInflowAndVariableBottom(), DPMBase::computeExternalForces(), VolumeCoupling::computeExternalForces(), DPMBase::computeInternalForce(), ChuteWithPeriodicInflow::computeInternalForces(), computeMass(), ClumpParticle::computeMass(), SuperQuadricParticle::computeMass(), ContractionWithPeriodicInflow::ContractionWithPeriodicInflow(), AngleOfRepose::createBaseSpecies(), SilbertPeriodic::createBaseSpecies(), getKineticEnergy(), ParticleHandler::getNumberOfFixedObjectsLocal(), getRotationalEnergy(), LawinenBox::printTime(), ChuteWithPeriodicInflow::printTime(), CSCWalls::saveWalls(), setMass(), setMassForP3Statistics(), SilbertPeriodic::setupInitialConditions(), and ~BaseParticle().
isInContactWith()
bool BaseParticle::isInContactWith (const BaseParticle * P) const virtual
Get whether or not this particle is in contact with the given particle.
Reimplemented in SuperQuadricParticle.
 {
     if (P->getName() != "Superquadric")
     {
         return Vec3D::getDistanceSquared(getPosition(), P->getPosition()) <
                mathsFunc::square(getSumOfInteractionRadii(P));
     }
     return P->isInContactWith(this);
 }
References Vec3D::getDistanceSquared(), BaseInteractable::getPosition(), getSumOfInteractionRadii(), Global_Physical_Variables::P, and mathsFunc::square().
Referenced by DPMBase::areInContact().
isInMPIDomain()
bool BaseParticle::isInMPIDomain ()
Indicates if the particle is in the communication zone of the mpi domain.
 {
     return isInMPIDomain_;
 }
References isInMPIDomain_.
Referenced by Domain::findNewMPIInteractions(), Domain::findNewMPIParticle(), and PeriodicBoundaryHandler::updateParticleStatus().
isInPeriodicDomain()
bool BaseParticle::isInPeriodicDomain () const
Indicates if the particle is in the periodic boundary communication zone.
 {
     return isInPeriodicDomain_;
 }
References isInPeriodicDomain_.
Referenced by PeriodicBoundaryHandler::checkIfAddNewParticle().
isMaserParticle()
bool BaseParticle::isMaserParticle () const
Indicates if this particle belongs to the maser boundary.
 {
     return isMaserParticle_;
 }
References isMaserParticle_.
Referenced by SubcriticalMaserBoundaryTEST::modifyGhostAfterCreation(), SubcriticalMaserBoundaryTEST::modifyPeriodicComplexity(), and PeriodicBoundaryHandler::updateMaserParticle().
isMPIParticle()
bool BaseParticle::isMPIParticle () const
Indicates if this particle is a ghost in the MPI domain.
 {
     //make mpi-dependent so the compiler can optimise
 #ifdef MERCURYDPM_USE_MPI
     return isMPIParticle_;
 #else
     return false;
 #endif
 }
References isMPIParticle_.
Referenced by InteractionHandler::getLiquidBridgeVolume(), InteractionHandler::getNumberOfLiquidBridges(), DPMBase::outputXBallsData(), ParticleVtkWriter::particleMustBeWritten(), and PeriodicBoundaryHandler::updateParticleStatus().
isPebble()
bool BaseParticle::isPebble () const inline
Checks if particle is a pebble (belongs to a clump)
     {
         return isPebble_;
     }
References isPebble_.
Referenced by ClumpParticle::actionsAfterAddObject(), DPMBase::computeExternalForces(), Mercury3Dclump::computeInternalForce(), ClumpParticle::computeMass(), ClumpParticle::integrateAfterForceComputation(), and ClumpParticle::integrateBeforeForceComputation().
isPeriodicGhostParticle()
bool BaseParticle::isPeriodicGhostParticle () const
Indicates if this particle is a ghost in the periodic boundary.
 {
     return isPeriodicGhostParticle_;
 }
References isPeriodicGhostParticle_.
Referenced by PeriodicBoundaryHandler::checkIfAddNewParticle(), Domain::findNewMPIParticle(), DPMBase::outputXBallsData(), and ParticleVtkWriter::particleMustBeWritten().
isSphericalParticle()
virtual bool BaseParticle::isSphericalParticle () const pure virtual
this flag is used to decide whether to compute orientation, which is not necessary for spherical particles
Todo:
This flag is used badly, and used to determine whether particles are superquadric
Implemented in SphericalParticle, NonSphericalParticle, and ClumpParticle.
movePrevious()
void BaseParticle::movePrevious (const Vec3D & posMove)
Adds a vector to the particle's previousPosition_.
Lets you add a vector to the particle's previousPosition_ vector.
Parameters
[in] posMove the vector to be added to the current previousPosition_ vector.
 {
     previousPosition_ += posMove;
 }
References previousPosition_.
oldRead()
void BaseParticle::oldRead (std::istream & is) virtual
Should NOT BE USED by any user, only used to read old restart files! Is expected to be obsolete by Mercury 2.0. Please use BaseParticle::read() instead.
This is the previously used version of the read function. Now just kept for legacy purposes.
Deprecated:
Should be gone in Mercury 2.0. Use BaseParticle::read() instead.
Todo:
incorporate contact information
 {
     logger(DEBUG, "reading particle old-style");
     static unsigned int id = 0;
     unsigned int indSpecies = 0;
     unsigned int numberOfContacts = 0;
     Vec3D orientation;
     Vec3D position;
     Vec3D velocity;
     Vec3D angularVelocity;
     double invInertiaScalar;
     double dummy = 0;
     is >> position >> velocity >> radius_ >> orientation >> angularVelocity;
     is >> invMass_ >> invInertiaScalar >> numberOfContacts;
     for (unsigned int i = 0; i < 12 * numberOfContacts; ++i)
     {
         is >> dummy;
     }
     is >> indSpecies;
     setPosition(position);
     setVelocity(velocity);
     Quaternion q;
     q.setEuler(orientation);
     setOrientation(q);
     setAngularVelocity(angularVelocity);
     invInertia_.XX = invInertiaScalar;
     invInertia_.YY = invInertiaScalar;
     invInertia_.ZZ = invInertiaScalar;
     BaseInteractable::setIndSpecies(indSpecies);
     setId(id);
     setIndex(id);
     id++;
 }
References DEBUG, i, invInertia_, invMass_, logger, Eigen::numext::q, radius_, BaseInteractable::setAngularVelocity(), BaseObject::setId(), BaseObject::setIndex(), BaseInteractable::setIndSpecies(), BaseInteractable::setOrientation(), BaseInteractable::setPosition(), BaseInteractable::setVelocity(), Jeffery_Solution::velocity(), MatrixSymmetric3D::XX, MatrixSymmetric3D::YY, and MatrixSymmetric3D::ZZ.
printHGrid()
void BaseParticle::printHGrid (std::ostream & os) const
Adds particle's HGrid level and cell coordinates to an ostream.
Adds the particle's HGridLevel_ and HGRid x/y/z positions to an std::ostream.
Parameters
[in,out] os the ostream which has the mentioned properties added.
 {
     os << "Particle( HGRID_Level:" << hGridCell.getHGridLevel()
        << ", HGRID_x:" << hGridCell.getHGridX()
        << ", HGRID_y:" << hGridCell.getHGridY()
        << ", HGRID_z:" << hGridCell.getHGridZ()
        << ")";
 }
References HGridCell::getHGridLevel(), HGridCell::getHGridX(), HGridCell::getHGridY(), HGridCell::getHGridZ(), and hGridCell.
read()
void BaseParticle::read (std::istream & is) override virtual
Particle read function, which accepts an std::istream as input.
Particle read function. Has an std::istream as argument, from which it extracts the radius_, invMass_ and invInertia_, respectively. From these the mass and inertia are deduced. An additional set of properties is read through the call to the parent's method BaseInteractable::read().
Parameters
[in,out] is input stream with particle properties.
Reimplemented from BaseInteractable.
Reimplemented in SuperQuadricParticle, and ClumpParticle.
 {
     BaseInteractable::read(is);
     std::string dummy;
     is >> dummy >> radius_ >> dummy >> invMass_;// >> dummy >> invInertia_;
     helpers::readOptionalVariable(is, "timeStamp", timeStamp_); // Optional, for backwards compatibility.
 }
References invMass_, radius_, BaseInteractable::read(), helpers::readOptionalVariable(), oomph::Global_string_for_annotation::string(), and timeStamp_.
Referenced by ClumpParticle::read(), SuperQuadricParticle::read(), and ParticleHandler::readAndCreateObject().
setAxes()
virtual void BaseParticle::setAxes (const Vec3D & axes) inline virtual
Only ustilised in case of superquadric particles.
Reimplemented in SuperQuadricParticle.
 { }
setCommunicationComplexity()
void BaseParticle::setCommunicationComplexity (unsigned complexity)
Set the communication complexity of the particle.
 {
     communicationComplexity_ = complexity;
 }
References communicationComplexity_.
Referenced by Domain::addParticlesToLists(), and Domain::updateParticles().
setExponents()
virtual void BaseParticle::setExponents (const Mdouble & eps1, const Mdouble & eps2) inline virtual
Only ustilised in case of superquadric particles.
Reimplemented in SuperQuadricParticle.
 {}
setHandler()
void BaseParticle::setHandler (ParticleHandler * handler)
Sets the pointer to the particle's ParticleHandler.
Assigns the particle to a ParticleHandler, and assigns a species to it based on the particles indSpecies_ (BaseInteractable data member).
Parameters
[in] handler pointer to the ParticleHandler
 {
     handler_ = handler;
     setSpecies(getHandler()->getDPMBase()->speciesHandler.getObject(getIndSpecies()));
 }
References getHandler(), BaseInteractable::getIndSpecies(), BaseHandler< T >::getObject(), handler_, and setSpecies().
Referenced by InsertionBoundary::checkBoundaryBeforeTimeStep(), RandomClusterInsertionBoundary::checkBoundaryBeforeTimeStep(), Chute::createBottom(), ParticleHandler::readAndCreateObject(), setSpecies(), SphericalIndenter::setupInitialConditions(), and ChuteBottom::setupInitialConditions().
setHGridLevel()
void BaseParticle::setHGridLevel (const unsigned int level) inline
Sets the particle's HGrid level.
Parameters
[in] level the particle's HGrid level
     { hGridCell.setHGridLevel(level); }
References hGridCell, and HGridCell::setHGridLevel().
Referenced by HGrid::insertParticleToHgrid().
setHGridNextObject()
void BaseParticle::setHGridNextObject (BaseParticle * p) inline
Sets the pointer to the next object in the particle's HGrid cell & level.
Parameters
[in] p pointer to the next object
     { hGridNextObject_ = p; }
References hGridNextObject_, and p.
Referenced by Mercury2D::hGridRemoveParticle(), Mercury3D::hGridRemoveParticle(), Mercury2D::hGridUpdateParticle(), and Mercury3D::hGridUpdateParticle().
setHGridPrevObject()
void BaseParticle::setHGridPrevObject (BaseParticle * p) inline
Sets the pointer to the previous object in the particle's HGrid cell & level.
Parameters
[in] p pointer to the previous object
     { hGridPrevObject_ = p; }
References hGridPrevObject_, and p.
Referenced by Mercury2D::hGridRemoveParticle(), Mercury3D::hGridRemoveParticle(), Mercury2D::hGridUpdateParticle(), and Mercury3D::hGridUpdateParticle().
setHGridX()
void BaseParticle::setHGridX (const int x) inline
Sets the particle's HGrid cell X-coordinate.
Set the x-index of the particle's hGrid cell position
Parameters
[in] x x-index of particle's HGrid cell
     { hGridCell.setHGridX(x); }
References hGridCell, HGridCell::setHGridX(), and plotDoE::x.
Referenced by Mercury2D::hGridUpdateParticle(), and Mercury3D::hGridUpdateParticle().
setHGridY()
void BaseParticle::setHGridY (const int y) inline
Sets the particle's HGrid cell Y-coordinate.
Set the y-index of the particle's hGrid cell position
Parameters
[in] y y-index of particle's HGrid cell
     { hGridCell.setHGridY(y); }
References hGridCell, HGridCell::setHGridY(), and y.
Referenced by Mercury2D::hGridUpdateParticle(), and Mercury3D::hGridUpdateParticle().
setHGridZ()
void BaseParticle::setHGridZ (const int z) inline
Sets the particle's HGrid cell Z-coordinate.
Set the y-index of the particle's hGrid cell position
Parameters
[in] z z-index of particle's HGrid cell
     { hGridCell.setHGridZ(z); }
References hGridCell, and HGridCell::setHGridZ().
Referenced by Mercury3D::hGridUpdateParticle().
setIndSpecies()
void BaseParticle::setIndSpecies (unsigned int indSpecies) override virtual
Deprecated:
Please use setSpecies(const ParticleSpecies*) instead.
Todo:
MX: this index is used in the MPI transmission. This should be "undeprecated"
Set the particle's species and species' index. Logs a warning if no ParticleHandler is assigned.
Parameters
[in] indSpecies The index of the species in the SpeciesHandler.
Todo:
TW do we have to update the species stored in the interactions here?
Reimplemented from BaseInteractable.
 {
     if (handler_ != nullptr)
     {
         //BaseInteractable::setIndSpecies(indSpecies);
         setSpecies(handler_->getDPMBase()->speciesHandler.getObject(indSpecies));
     }
     else
     {
         BaseInteractable::setIndSpecies(indSpecies);
         logger(ERROR, "setIndSpecies called on a particle with no particle handler.\n"
                       "Therefore I can't request the given species from the species handler.\n"
                       " PartID = %", getId());
     }
 }
References ERROR, BaseHandler< T >::getDPMBase(), BaseObject::getId(), BaseHandler< T >::getObject(), handler_, logger, BaseInteractable::setIndSpecies(), setSpecies(), and DPMBase::speciesHandler.
setInertia() [1/2]
void BaseParticle::setInertia () virtual
Reimplemented in SuperQuadricParticle.
 {
 }
Referenced by SuperQuadricParticle::setInertia(), and SlidingSpheresUnitTest::setupInitialConditions().
setInertia() [2/2]
void BaseParticle::setInertia (MatrixSymmetric3D inertia)
Sets the particle's inertia_ (and adjusts invInertia_ accordingly)
Sets the particle's inertia and invInertia_.
Parameters
[in] newInertia the new inertia to be set.
 {
     invInertia_ = MatrixSymmetric3D::inverse(inertia);
 }
References MatrixSymmetric3D::inverse(), and invInertia_.
setInfiniteInertia()
void BaseParticle::setInfiniteInertia ()
Sets the particle's inertia_ to 'infinite' (1e20) and its invInertia_ to 0.
Sets the inertia to 1e20 and the invInertia_ (which is actually used in the calculations) to 0.
 {
     invInertia_.setZero();
 //    Clump* f;
 //    f->invInertia2_.setZero();
 } //> i.e. no rotations
References invInertia_, and MatrixSymmetric3D::setZero().
Referenced by Slide::actionsBeforeTimeLoop().
setInfo()
void BaseParticle::setInfo (Mdouble info) virtual
Sets some user-defined information about this object (by default, species ID).
 {
     info_ = info;
 }
References info, and info_.
setInMPIDomain()
void BaseParticle::setInMPIDomain (bool flag)
Flags the status of the particle if wether it is in the communication zone or not.
 {
     isInMPIDomain_ = flag;
 }
References isInMPIDomain_.
Referenced by PeriodicBoundaryHandler::setMPIFlags(), Domain::updateParticles(), and PeriodicBoundaryHandler::updateParticleStatus().
setInPeriodicDomain()
void BaseParticle::setInPeriodicDomain (bool flag)
Flags the status of the particle whether it is in the periodic communication zone or not.
 {
     isInPeriodicDomain_ = flag;
 }
References isInPeriodicDomain_.
Referenced by PeriodicBoundaryHandler::processLocalGhostParticles(), PeriodicBoundaryHandler::processPeriodicParticles(), PeriodicBoundaryHandler::processReceivedGhostParticleData(), and PeriodicBoundaryHandler::updateParticleStatus().
setInverseInertia()
void BaseParticle::setInverseInertia (MatrixSymmetric3D inverseInertia)
Sets the particle's inertia_ (and adjusts invInertia_ accordingly)
 {
     invInertia_ = inverseInertia;
 }
References invInertia_.
setMaserParticle()
void BaseParticle::setMaserParticle (bool flag)
Flags the status of the particle if it belongs to the maser boundary or not.
 {
     isMaserParticle_ = flag;
 }
References isMaserParticle_.
Referenced by SubcriticalMaserBoundaryTEST::checkBoundaryAfterParticleMoved(), and PeriodicBoundaryHandler::updateMaserParticle().
setMass()
void BaseParticle::setMass (Mdouble mass)
Sets the particle's mass.
Deprecated:
Please do not set the mass yourself, but use ParticleSpecies->computeMass instead. That makes sure
Sets the mass of the particle
Parameters
[in] mass the new particle's mass
 {
     logger(WARN, "WARNING: Do not use particle->setMass, instead use "
                  "particleSpecies->computeMass, since this function can cause "
                  "inconsistencies between the mass, density and radius of this particle!");
     logger.assert_always(mass > 0.0 && !isFixed(),
                          "Error in BaseParticle::setMass, the given mass to be set must be positive.");
     invMass_ = 1.0 / mass;
 }
References invMass_, isFixed(), logger, and WARN.
setMassForP3Statistics()
void BaseParticle::setMassForP3Statistics (Mdouble mass)
Sets the particle's mass This function should not be used, but is necessary to extend the CG toolbox to non-spherical particles.
Sets the mass of the particle
Parameters
[in] mass the new particle's mass
 {
     if (mass > 0.0 && !isFixed())
     {
         invMass_ = 1.0 / mass;
     }
     else
     {
         logger(ERROR, "Error in BaseParticle::setMass, the given mass to be set must be positive.");
     }
 }
References ERROR, invMass_, isFixed(), and logger.
setMPIParticle()
void BaseParticle::setMPIParticle (bool flag)
Flags the mpi particle status.
 {
     isMPIParticle_ = flag;
 }
References isMPIParticle_.
Referenced by PeriodicBoundaryHandler::setMPIFlags(), and Domain::updateParticles().
setPeriodicComplexity() [1/2]
void BaseParticle::setPeriodicComplexity (int index, int value)
Set the periodic communication complexity of the particle.
 {
     //hack: generally you'd add particles after declaring the boundaries
     //but no official programming guildelines rules have been setup for that
     //So incase that doesnt happen we need to resize this periodicComplexity
     if (periodicComplexity_.empty())
     {
         int numberOfPeriodicBoundaries = getHandler()->getDPMBase()->periodicBoundaryHandler.getSize();
         if (numberOfPeriodicBoundaries > 0)
         {
             //First initialisation of the periodic complexity assumes the particle is completely
             //within the real domain
             periodicComplexity_ = std::vector<int>(numberOfPeriodicBoundaries, 2);
         }
     }
     periodicComplexity_[index] = value;
 }
References BaseHandler< T >::getDPMBase(), getHandler(), BaseHandler< T >::getSize(), DPMBase::periodicBoundaryHandler, periodicComplexity_, and Eigen::value.
setPeriodicComplexity() [2/2]
void BaseParticle::setPeriodicComplexity (std::vector< int > complexity)
Set the periodic communication complexity of the particle.
 {
     periodicComplexity_ = complexity;
 }
References periodicComplexity_.
Referenced by PeriodicBoundaryHandler::findNewParticle(), SubcriticalMaserBoundaryTEST::modifyGhostAfterCreation(), PeriodicBoundaryHandler::processLocalGhostParticles(), PeriodicBoundaryHandler::processReceivedGhostParticleData(), and PeriodicBoundaryHandler::updateParticles().
setPeriodicFromParticle()
void BaseParticle::setPeriodicFromParticle (BaseParticle * p) inline
Assigns the pointer to the 'original' particle this one's a periodic copy of (used in periodic boundary condition implementations).
Parameters
[in] p pointer to the 'original' particle this one is a periodic copy of.
     { periodicFromParticle_ = p; };
References p, and periodicFromParticle_.
Referenced by ChuteWithPeriodicInflow::Check_and_Duplicate_Periodic_Particle(), ConstantMassFlowMaserBoundary::createGhostCopy(), SubcriticalMaserBoundary::createGhostCopy(), PeriodicBoundary::createGhostParticle(), TimeDependentPeriodicBoundary::createGhostParticle(), LeesEdwardsBoundary::createHorizontalPeriodicParticle(), ShearBoxBoundary::createHorizontalPeriodicParticle(), AngledPeriodicBoundary::createPeriodicParticle(), CircularPeriodicBoundary::createPeriodicParticle(), LeesEdwardsBoundary::createVerticalPeriodicParticle(), and ShearBoxBoundary::createVerticalPeriodicParticle().
setPeriodicGhostParticle()
void BaseParticle::setPeriodicGhostParticle (bool flag)
Flags the status of the particle to be a ghost in periodic boundary or not.
 {
     isPeriodicGhostParticle_ = flag;
 }
References isPeriodicGhostParticle_.
Referenced by PeriodicBoundary::createGhostParticle(), PeriodicBoundaryHandler::processLocalGhostParticles(), PeriodicBoundaryHandler::processReceivedGhostParticleData(), and PeriodicBoundaryHandler::updateParticleStatus().
setPreviousPeriodicComplexity()
void BaseParticle::setPreviousPeriodicComplexity (std::vector< int > complexity)
Set the previous periodic communication complexity of the paritcle.
 {
     previousPeriodicComplexity_ = complexity;
 }
References previousPeriodicComplexity_.
Referenced by PeriodicBoundaryHandler::updateParticles().
setPreviousPosition()
void BaseParticle::setPreviousPosition (const Vec3D & pos)
Sets the particle's position in the previous time step.
This is used to set the particle's previous position
Parameters
[in] pos the particle's previous position vector.
 {
     previousPosition_ = pos;
 }
References previousPosition_.
Referenced by CircularPeriodicBoundary::checkBoundaryAfterParticleMoved(), integrateBeforeForceComputation(), ClumpParticle::integrateBeforeForceComputation(), Domain::processReceivedBoundaryParticleData(), and PeriodicBoundaryHandler::updateParticles().
setRadius()
void BaseParticle::setRadius (Mdouble radius) virtual
Sets the particle's radius_ (and adjusts the mass_ accordingly, based on the particle's species)
Sets the radius of the particle, and from that computes the new mass (using its species) and checks whether it now is either the smallest or biggest particle in its ParticleHandler.
Parameters
[in] radius the new radius
Reimplemented in SuperQuadricParticle.
 {
     radius_ = radius;
     if (getHandler())
     {
         getSpecies()->computeMass(this);
         getHandler()->checkExtrema(this);
     }
 }
References ParticleHandler::checkExtrema(), ParticleSpecies::computeMass(), getHandler(), BaseInteractable::getSpecies(), UniformPSDSelfTest::radius, and radius_.
Referenced by ClumpParticle::ClumpParticle(), Funnel::create_funnel(), LawinenBox::create_inflow_particle(), ChuteWithContraction::create_inflow_particle(), Funnel::create_inflow_particle(), AngleOfRepose::create_inflow_particle(), FlowRule::create_inflow_particle(), SilbertPeriodic::create_inflow_particle(), SegregationWithHopper::create_inflow_particle(), Chute::createBottom(), CurvyChute::createBottom(), BasicIntersectionOfWalls::getDistanceAndNormal(), BasicUnionOfWalls::getDistanceAndNormal(), TriangleMeshWall::getDistanceAndNormal(), BasicIntersectionOfWalls::getVTK(), BasicUnionOfWalls::getVTK(), main(), regimeForceUnitTest::regimeForceUnitTest(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), SuperQuadricParticle::setBoundingRadius(), MarbleRun::setParticleRadius(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), CFDDEMCoupleTest::setupInitialConditions(), my_problem::setupInitialConditions(), ForceLawsMPI2Test::setupInitialConditions(), TwoByTwoMPIDomainMPI4Test::setupInitialConditions(), ParameterStudy1DDemo::setupInitialConditions(), ParameterStudy2DDemo::setupInitialConditions(), ParameterStudy3DDemo::setupInitialConditions(), StressStrainControl::setupInitialConditions(), Cstatic2d::setupInitialConditions(), Cstatic3D::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), Drum::setupInitialConditions(), HertzSelfTest::setupInitialConditions(), MindlinSelfTest::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), WallParticleCollision::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), SphericalIndenter::setupInitialConditions(), SlidingSpheresUnitTest::setupInitialConditions(), ChargedBondedParticleUnitTest::setupInitialConditions(), HertzianSinterForceUnitTest::setupInitialConditions(), MovingIntersectionOfWallsUnitTest_Basic::setupInitialConditions(), MovingWall::setupInitialConditions(), MultiParticlesInsertion::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), PlasticForceUnitTest::setupInitialConditions(), my_problem_HGRID::setupInitialConditions(), SinterForceUnitTest::setupInitialConditions(), SpeciesTest::setupInitialConditions(), TangentialSpringUnitTest::setupInitialConditions(), ChuteBottom::setupInitialConditions(), and viscoElasticUnitTest::viscoElasticUnitTest().
setSpecies()
void BaseParticle::setSpecies (const ParticleSpecies * species) virtual
In addition to the functionality of BaseInteractable::setSpecies, this function sets the pointer to the particleHandler, which is needed to retrieve species information.
Todo:
TW: this function should also check if the particle is the correct particle for the species type
Sets the particle's species. If this particle does not have a handler yet, this function also assigns the ParticleHandler in the same DPMBase as the SpeciesHandler of the given species as its handler.
Parameters
[in] species pointer to the ParticleSpecies object, to be set as the particle's species.
Todo:
TW should we chaeck here if we have the right kind of species for the right kind of particle?
Todo:
maybe these if statements should throw warnings
 {
     BaseInteractable::setSpecies(species);
     //set pointer to the ParticleHandler handler_, which is needed to retrieve
     //species information
     if (handler_ == nullptr)
     {
         SpeciesHandler* sH = species->getHandler();
         DPMBase* dB = sH->getDPMBase();
         if (dB != nullptr)
         {
             setHandler(&dB->particleHandler);
         }
     }
 }
References BaseHandler< T >::getDPMBase(), BaseSpecies::getHandler(), handler_, DPMBase::particleHandler, setHandler(), and BaseInteractable::setSpecies().
Referenced by ChuteWithPeriodicInflow::AddContinuingBottom(), BaseParticle(), BoundariesSelfTest::BoundariesSelfTest(), ConstantMassFlowMaserBoundary::checkBoundaryAfterParticleMoved(), SubcriticalMaserBoundary::checkBoundaryAfterParticleMoved(), ChuteWithPeriodicInflowAndContinuingBottom::ChuteWithPeriodicInflowAndContinuingBottom(), ChuteWithPeriodicInflowAndContraction::ChuteWithPeriodicInflowAndContraction(), ChuteWithPeriodicInflowAndVariableBottom::ChuteWithPeriodicInflowAndVariableBottom(), ContractionWithPeriodicInflow::ContractionWithPeriodicInflow(), FlowRule::create_inflow_particle(), SilbertPeriodic::create_inflow_particle(), AngleOfRepose::createBaseSpecies(), SilbertPeriodic::createBaseSpecies(), Chute::createBottom(), CurvyChute::createBottom(), FluxBoundarySelfTest::FluxBoundarySelfTest(), BasicIntersectionOfWalls::getDistanceAndNormal(), BasicUnionOfWalls::getDistanceAndNormal(), TriangleMeshWall::getDistanceAndNormal(), BasicIntersectionOfWalls::getVTK(), BasicUnionOfWalls::getVTK(), Hertzian2DUnitTest::Hertzian2DUnitTest(), ChuteWithPeriodicInflow::integrateBeforeForceComputation(), LawinenBox::LawinenBox(), main(), MercuryCGSelfTest::MercuryCGSelfTest(), protectiveWall::protectiveWall(), InsertionBoundary::read(), ParticleHandler::readAndCreateObject(), regimeForceUnitTest::regimeForceUnitTest(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), setHandler(), setIndSpecies(), MeltableParticle::setSpecies(), CFDDEMCoupleTest::setupInitialConditions(), ForceLawsMPI2Test::setupInitialConditions(), TwoByTwoMPIDomainMPI4Test::setupInitialConditions(), SilbertPeriodic::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), Drum::setupInitialConditions(), HertzSelfTest::setupInitialConditions(), MindlinSelfTest::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), SphericalIndenter::setupInitialConditions(), GranularCollapse::setupInitialConditions(), SlidingSpheresUnitTest::setupInitialConditions(), ChargedBondedParticleUnitTest::setupInitialConditions(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), FullRestartTest::setupInitialConditions(), HertzianSinterForceUnitTest::setupInitialConditions(), MultiParticlesInsertion::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), PlasticForceUnitTest::setupInitialConditions(), SinterForceUnitTest::setupInitialConditions(), SpeciesTest::setupInitialConditions(), TangentialSpringUnitTest::setupInitialConditions(), Chute::setupInitialConditions(), ChuteBottom::setupInitialConditions(), ContactDetectionWithWallTester::setupParticleAndWall(), ContactDetectionTester::setupParticles(), SilbertPeriodic::SilbertPeriodic(), T_protectiveWall::T_protectiveWall(), and viscoElasticUnitTest::viscoElasticUnitTest().
setTimeStamp()
void BaseParticle::setTimeStamp (unsigned timeStamp)
 {
     timeStamp_ = timeStamp;
 }
References timeStamp_.
unfix()
void BaseParticle::unfix ()
Unfix Particle function, which required a reference to the Species vector. It unfixes a Particle by computing the Particles mass and inertia.
Unfixes the particle by computing the Particles mass and inertia, using the species and radius.
 {
     invMass_ = 1.0;
     getSpecies()->computeMass(this);
     if (getHandler())
         getHandler()->removedFixedParticle();
 }
References ParticleSpecies::computeMass(), getHandler(), BaseInteractable::getSpecies(), invMass_, and ParticleHandler::removedFixedParticle().
write()
void BaseParticle::write (std::ostream & os) const override virtual
Particle print function, which accepts an std::ostream as input.
BaseParticle print method, which accepts an os std::ostream as input. It prints human readable BaseParticle information to the std::ostream.
Parameters
[in,out] os stream to which the info is written
Reimplemented from BaseInteractable.
Reimplemented in SuperQuadricParticle, and ClumpParticle.
 {
     BaseInteractable::write(os);
     os << " radius " << radius_
        << " invMass " << invMass_
        << " timeStamp " << timeStamp_;
     //invMass_ is a computed value, but needs to be stored to see if a particle is fixed
 }
References invMass_, radius_, timeStamp_, and BaseInteractable::write().
Referenced by ClumpParticle::write(), and SuperQuadricParticle::write().
Friends And Related Function Documentation
ParticleSpecies::computeMass
void ParticleSpecies::computeMass (BaseParticle *) const friend
Particle's position at previous time step.
Since ParticleSpecies is allowed to set the mass of a BaseParticle, it is a friend of this class.
Member Data Documentation
clumpParticle_
BaseParticle* BaseParticle::clumpParticle_
Function that updates necessary quantities of a clump particle after adding a pebble.
Referenced by ClumpParticle::ClumpParticle(), getClump(), and ClumpParticle::setClump().
communicationComplexity_
unsigned BaseParticle::communicationComplexity_ private
returns true if it flagged as being in MPI domain
Referenced by BaseParticle(), getCommunicationComplexity(), and setCommunicationComplexity().
handler_
ParticleHandler* BaseParticle::handler_ private
Inverse Particle inverse inertia (for computation optimization)
Pointer to the particle's ParticleHandler container
Referenced by BaseParticle(), getHandler(), getVolume(), setHandler(), setIndSpecies(), and setSpecies().
hGridCell
HGridCell BaseParticle::hGridCell private
All hGrid-information: the cell (x,y,z,level), and the previous and next particle in this cell compared to this particle
Referenced by BaseParticle(), getHGridCell(), getHGridLevel(), getHGridX(), getHGridY(), getHGridZ(), printHGrid(), setHGridLevel(), setHGridX(), setHGridY(), and setHGridZ().
hGridNextObject_
BaseParticle* BaseParticle::hGridNextObject_ private
Referenced by BaseParticle(), getHGridNextObject(), and setHGridNextObject().
hGridPrevObject_
BaseParticle* BaseParticle::hGridPrevObject_ private
Pointer to the next Particle in the same HGrid cell.
Referenced by BaseParticle(), getHGridPrevObject(), and setHGridPrevObject().
info_
Mdouble BaseParticle::info_ private
Referenced by BaseParticle(), getInfo(), and setInfo().
invInertia_
MatrixSymmetric3D BaseParticle::invInertia_
Inverse Particle mass (for computation optimization)
Referenced by ClumpParticle::angularAccelerateClumpIterative(), BaseParticle(), ClumpParticle::ClumpParticle(), computeMass(), ClumpParticle::computeMass(), SuperQuadricParticle::computeMass(), fixParticle(), getAngularMomentum(), getInertia(), getInvInertia(), oldRead(), ClumpParticle::rotateTensorOfInertia(), setInertia(), setInfiniteInertia(), ClumpParticle::setInitInertia(), and setInverseInertia().
invMass_
Mdouble BaseParticle::invMass_
Particle radius_.
Referenced by BaseParticle(), computeMass(), ClumpParticle::computeMass(), SuperQuadricParticle::computeMass(), fixParticle(), getAngularMomentum(), getInvMass(), getMass(), getMomentum(), isFixed(), oldRead(), read(), ClumpParticle::setClumpMass(), setMass(), setMassForP3Statistics(), unfix(), ClumpParticle::updatePebblesVelPos(), and write().
isClump_
bool BaseParticle::isClump_
The particle is pebble.
Referenced by BaseParticle(), ClumpParticle::ClumpParticle(), ClumpParticle::getKineticEnergy(), ClumpParticle::getRotationalEnergy(), isClump(), and ClumpParticle::setClump().
isInMPIDomain_
bool BaseParticle::isInMPIDomain_ private
returns true if the particle acts as an MPI particle instead of a real particle
Referenced by BaseParticle(), isInMPIDomain(), and setInMPIDomain().
isInPeriodicDomain_
bool BaseParticle::isInPeriodicDomain_ private
Referenced by BaseParticle(), isInPeriodicDomain(), and setInPeriodicDomain().
isMaserParticle_
bool BaseParticle::isMaserParticle_ private
Indicates the periodic complexity at current time step. Used to update periodic status.
Referenced by BaseParticle(), isMaserParticle(), and setMaserParticle().
isMPIParticle_
bool BaseParticle::isMPIParticle_ private
Pointer to originating Particle.
Referenced by BaseParticle(), isMPIParticle(), and setMPIParticle().
isPebble_
bool BaseParticle::isPebble_
pointer to a clump particle (for a pebble)
Referenced by BaseParticle(), ClumpParticle::ClumpParticle(), isPebble(), ClumpParticle::read(), ClumpParticle::setClump(), and ClumpParticle::write().
isPeriodicGhostParticle_
bool BaseParticle::isPeriodicGhostParticle_ private
bool that indicates if a particle is in the periodic domain of any boundary
Referenced by BaseParticle(), isPeriodicGhostParticle(), and setPeriodicGhostParticle().
periodicComplexity_
std::vector<int> BaseParticle::periodicComplexity_ private
Indicates the periodic complexity at previous time step.
Referenced by BaseParticle(), getPeriodicComplexity(), and setPeriodicComplexity().
periodicFromParticle_
BaseParticle* BaseParticle::periodicFromParticle_ private
Pointer to the previous Particle in the same HGrid cell.
Particle attributes
Referenced by BaseParticle(), getPeriodicFromParticle(), and setPeriodicFromParticle().
previousPeriodicComplexity_
std::vector<int> BaseParticle::previousPeriodicComplexity_ private
Indicates if the particle is a ghost particle of a periodic particle.
Referenced by BaseParticle(), getPreviousPeriodicComplexity(), and setPreviousPeriodicComplexity().
previousPosition_
Vec3D BaseParticle::previousPosition_ private
Indicates if this particle belongs to the maser boundary or is released into the wide open world.
Referenced by BaseParticle(), getPreviousPosition(), movePrevious(), and setPreviousPosition().
radius_
Mdouble BaseParticle::radius_
Referenced by BaseParticle(), getCurvature(), getRadius(), getVolume(), oldRead(), read(), setRadius(), and write().
timeStamp_
unsigned BaseParticle::timeStamp_ private
Stores the time stamp the particle was created.
Referenced by BaseParticle(), getTimeStamp(), read(), setTimeStamp(), and write().
The documentation for this class was generated from the following files:
BaseParticle.h
BaseParticle.cc