MercuryDPM: Eigen::internal::generic_k0< T, float > Struct Template Reference
Eigen::internal::generic_k0< T, float > Struct Template Reference
#include <BesselFunctionsImpl.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T run (const T &x)
Member Function Documentation
run()
template<typename T > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T Eigen::internal::generic_k0< T, float >::run (const T & x) inline static
{
     /*  k0f.c
      *  Modified Bessel function, third kind, order zero
      *
      *
      *
      * SYNOPSIS:
      *
      * float x, y, k0f();
      *
      * y = k0f( x );
      *
      *
      *
      * DESCRIPTION:
      *
      * Returns modified Bessel function of the third kind
      * of order zero of the argument.
      *
      * The range is partitioned into the two intervals [0,8] and
      * (8, infinity).  Chebyshev polynomial expansions are employed
      * in each interval.
      *
      *
      *
      * ACCURACY:
      *
      * Tested at 2000 random points between 0 and 8.  Peak absolute
      * error (relative when K0 > 1) was 1.46e-14; rms, 4.26e-15.
      *                      Relative error:
      * arithmetic   domain     # trials      peak         rms
      *    IEEE      0, 30       30000       7.8e-7      8.5e-8
      *
      * ERROR MESSAGES:
      *
      *   message         condition      value returned
      *  K0 domain          x <= 0          MAXNUM
      *
      */
     const float A[] = {1.90451637722020886025E-9f, 2.53479107902614945675E-7f, 2.28621210311945178607E-5f,
                        1.26461541144692592338E-3f, 3.59799365153615016266E-2f, 3.44289899924628486886E-1f,
                        -5.35327393233902768720E-1f};
     const float B[] = {-1.69753450938905987466E-9f, 8.57403401741422608519E-9f,  -4.66048989768794782956E-8f,
                        2.76681363944501510342E-7f,  -1.83175552271911948767E-6f, 1.39498137188764993662E-5f,
                        -1.28495495816278026384E-4f, 1.56988388573005337491E-3f,  -3.14481013119645005427E-2f,
                        2.44030308206595545468E0f};
     const T MAXNUM = pset1<T>(NumTraits<float>::infinity());
     const T two = pset1<T>(2.0);
     T x_le_two = internal::pchebevl<T, 7>::run(pmadd(x, x, pset1<T>(-2.0)), A);
     x_le_two = pmadd(generic_i0<T, float>::run(x), pnegate(plog(pmul(pset1<T>(0.5), x))), x_le_two);
     x_le_two = pselect(pcmp_le(x, pset1<T>(0.0)), MAXNUM, x_le_two);
     T x_gt_two =
         pmul(pmul(pexp(pnegate(x)), internal::pchebevl<T, 10>::run(psub(pdiv(pset1<T>(8.0), x), two), B)), prsqrt(x));
     return pselect(pcmp_le(x, two), x_le_two, x_gt_two);
   }
References Eigen::internal::pcmp_le(), Eigen::internal::pdiv(), Eigen::internal::pexp(), Eigen::internal::plog(), Eigen::internal::pmadd(), Eigen::internal::pmul(), Eigen::internal::pnegate(), Eigen::internal::prsqrt(), Eigen::internal::pselect(), Eigen::internal::psub(), Eigen::internal::pchebevl< Packet, N >::run(), and plotDoE::x.
The documentation for this struct was generated from the following file:
BesselFunctionsImpl.h