MercuryDPM: HopperSelfTest.cpp File Reference
HopperSelfTest.cpp File Reference
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cmath>
#include "Species/LinearViscoelasticSlidingFrictionSpecies.h"
#include "ChuteWithHopper.h"
Functions
int main ()
[CH:headers]
Function Documentation
main()
int main ()
[CH:headers]
[CH:headers] [CH:main]
 {
     //Problem parameters
     ChuteWithHopper problem;
     problem.setName("HopperSelfTest");
     Mdouble tc = 4.0e-4;                // particle collision time
     problem.setTimeStep(0.02 * tc);
     problem.setTimeMax(0.01);
     //Particle properties
     problem.setInflowParticleRadius(0.32e-3, 0.40e-3);
     problem.setFixedParticleRadius(0.36e-3);
     LinearViscoelasticSlidingFrictionSpecies species;
     species.setHandler(&problem.speciesHandler);
     species.setDensity(2400.0);
     Mdouble meanRadius = 0.5 * (problem.getMinInflowParticleRadius() + problem.getMaxInflowParticleRadius());
     Mdouble mass = species.getMassFromRadius(meanRadius);
     species.setCollisionTimeAndRestitutionCoefficient(tc, 0.95, mass);
     species.setSlidingFrictionCoefficient(0.5);
     problem.speciesHandler.copyAndAddObject(species);
     //Chute properties
     problem.setRoughBottomType(MONOLAYER_ORDERED); // try also MONOLAYER_DISORDERED, MULTILAYER or FLAT
     problem.setChuteAngleAndMagnitudeOfGravity(10.0,9.8); // in degrees (relative to horizontal)
     problem.setChuteLength(40.0e-3);
     problem.setChuteWidth(3.2e-3 / 2.0);
     //Hopper properties
     Mdouble ExitHeight = 10.0e-3;
     Mdouble ExitLength = ExitHeight;
     Mdouble hopperAngle_ = 60.0;
     Mdouble hopperLength_ = 4.0 * ExitLength;
 //    Mdouble hopperLowestPoint_ = ExitHeight - ExitLength * std::tan(problem.getChuteAngle());
 //    Mdouble hopperHeight_ = hopperLowestPoint_ + 1.1 * 0.5 * (hopperLength_ + ExitLength) / std::tan(hopperAngle_ * constants::pi / 180.0); // NB: this is not DEDUCED, but SET!!! (BvdH)
     Mdouble hopperHeight_ = 24.1139e-3;
     problem.setHopper(ExitLength, ExitHeight, hopperAngle_, hopperLength_, hopperHeight_);
     // Output properties
     problem.setSaveCount(51);
     //'time step ratio': size of minimum particle over maximum distance travelled
     // by any particle per time step (i.e., should be >> 1 )
     logger(INFO, "time step ratio: %", problem.getTimeStepRatio());
     //solve
     problem.solve();
 }
References ParticleSpecies::getMassFromRadius(), INFO, logger, MONOLAYER_ORDERED, problem, ParticleSpecies::setDensity(), and BaseSpecies::setHandler().