MercuryDPM: HertzianSinterInteraction Class Reference
HertzianSinterInteraction Class Reference
Computes normal forces in case of a linear plastic visco-elastic interaction.
#include <HertzianSinterInteraction.h>
Public Member Functions
HertzianSinterInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
Constructor.
HertzianSinterInteraction (const HertzianSinterInteraction &p)
Copy constructor.
HertzianSinterInteraction ()
~HertzianSinterInteraction () override
Destructor.
void computeSinterForce ()
Creates a copy of an object of this class. (Deep copy)
void computeNormalForce ()
Calls computeSinterForce().
void read (std::istream &is) override
Interaction read function, which accepts an std::istream as input.
void write (std::ostream &os) const override
Interaction write function, which accepts an std::ostream as input.
virtual std::string getBaseName () const
Returns the name of the interaction.
Mdouble getElasticEnergy () const override
Computes and returns the amount of elastic energy stored in the spring.
const HertzianSinterNormalSpecies * getSpecies () const
Mdouble getMaxOverlap () const
void setMaxOverlap (Mdouble)
Mdouble getUnloadingModulus () const
Public Member Functions inherited from BaseInteraction
BaseInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
A constructor takes the BaseInteractable objects which are interacting (come into contact) and time the interaction starts.
BaseInteraction ()
BaseInteraction (const BaseInteraction &p)
Copy constructor.
~BaseInteraction () override
The destructor. It removes this interactions from the objects that were interacting, and writes the time to a file when needed.
virtual void actionsOnErase ()
If an interaction needs to do something before it gets erased, add it here. E.g. Liquid bridges rupture at the end of their lifetime, and the liquid bridge volume has to be redistributed. The reason this action is not done in the destructor is that this action should not be taken when erasing ghost interactions.
virtual void computeForce ()
Virtual function that contains the force law between the two objects interacting.
void writeToFStat (std::ostream &os, Mdouble time) const
Writes forces data to the FStat file.
std::string getName () const override
Virtual function which allows interactions to be named.
void setDistance (Mdouble distance)
Sets the interaction distance between the two interacting objects.
void setNormal (Vec3D normal)
Sets the normal vector between the two interacting objects.
void setOverlap (Mdouble overlap)
Set the overlap between the two interacting object.
void setContactPoint (Vec3D contactPoint)
Set the location of the contact point between the two interacting objects.
void setTimeStamp (unsigned timeStamp)
Updates the time step of the interacting. Note, time steps used to find completed interactions.
void setSpecies (const BaseSpecies *species)
Set the Species of the interaction; note this can either be a Species or MixedSpecies.
void setP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void setI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
void importP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void importI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
Vec3D getIP () const
Vec3D getIC () const
Vec3D getCP () const
void setLagrangeMultiplier (Mdouble multiplier)
Mdouble getLagrangeMultiplier ()
void setHandler (InteractionHandler *handler)
Sets the pointer to the interaction hander which is storing this interaction.
InteractionHandler * getHandler () const
Gets a point to the interaction handlers to which this interaction belongs.
const Vec3D & getForce () const
Gets the current force (vector) between the two interacting objects.
const Vec3D & getTorque () const
Gets the current torque (vector) between the two interacting objects.
const Vec3D & getNormal () const
Gets the normal vector between the two interacting objects.
const Vec3D & getContactPoint () const
Gets constant reference to contact point (vector).
Mdouble getOverlap () const
Returns a Mdouble with the current overlap between the two interacting objects.
Mdouble getOverlapVolume () const
Returns the overlap volume between two interacting objects.
Mdouble getContactRadius () const
Returns a Mdouble with the current contact between the two interacting objects.
void removeFromHandler ()
Removes this interaction from its interaction hander.
void copySwitchPointer (const BaseInteractable *original, BaseInteractable *ghost) const
This copies the interactions of the original particle and replaces the original with the ghost copy.
void gatherContactStatistics ()
BaseInteractable * getP ()
Returns a pointer to first object involved in the interaction (normally a particle).
BaseInteractable * getI ()
Returns a pointer to the second object involved in the interaction (often a wall or a particle).
const BaseInteractable * getP () const
Returns a constant pointer to the first object involved in the interaction.
const BaseInteractable * getI () const
Returns a constant pointer to the second object involved in the interaction.
Mdouble getTimeStamp () const
Returns an Mdouble which is the time stamp of the interaction.
virtual void integrate (Mdouble timeStep)
integrates variables of the interaction which need to be integrate e.g. the tangential overlap.
virtual Mdouble getTangentialOverlap () const
get the length of the current tangential overlap
Mdouble getDistance () const
Returns an Mdouble which is the norm (length) of distance vector.
const Vec3D & getRelativeVelocity () const
Returns a constant reference to a vector of relative velocity.
Mdouble getNormalRelativeVelocity () const
Returns a double which is the norm (length) of the relative velocity vector.
Mdouble getAbsoluteNormalForce () const
Returns the absolute value of the norm (length) of the Normal force vector.
virtual BaseInteraction * copy () const =0
Makes a copy of the interaction and returns a pointer to the copy.
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseWall *I)
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseParticle *I)
unsigned int getMultiContactIdentifier () const
void setMultiContactIdentifier (unsigned int multiContactIdentifier_)
virtual void rotateHistory (Matrix3D &rotationMatrix)
When periodic particles are used, some interactions need certain history properties rotated (e.g. tangential springs). This is the function for that.
virtual void actionsAfterTimeStep ()
virtual unsigned getNumberOfFieldsVTK () const
virtual std::string getTypeVTK (unsigned i) const
virtual std::string getNameVTK (unsigned i) const
virtual std::vector< Mdouble > getFieldVTK (unsigned i) const
void addForce (Vec3D force)
add an force increment to the total force.
void addTorque (Vec3D torque)
add a torque increment to the total torque.
void setForce (Vec3D force)
set total force (this is used by the normal force, tangential forces are added use addForce)
void setTorque (Vec3D torque)
set the total force (this is used by the normal force, tangential torques are added use addTorque)
const BaseSpecies * getBaseSpecies () const
Return a constant point to BaseSpecies of the interaction.
virtual void createMPIType ()
virtual void * createMPIInteractionDataArray (unsigned int numberOfInteractions) const
virtual void deleteMPIInteractionDataArray (void *dataArray)
virtual void getMPIInteraction (void *historyDataArray, unsigned int index) const
copies the history interactions into the data array
virtual void getInteractionDetails (void *interactionDataArray, unsigned int index, unsigned int &identificationP, unsigned int &identificationI, bool &isWallInteraction, unsigned &timeStamp)
virtual void setMPIInteraction (void *interactionDataArray, unsigned int index, bool resetPointers)
void setBasicMPIInteractionValues (int P, int I, unsigned timeStamp, Vec3D force, Vec3D torque, bool isWallInteraction, bool resetPointers)
void setIdentificationP (unsigned int identification)
void setIdentificationI (int identification)
void setWallInteraction (bool flag)
unsigned int getIdentificationP ()
int getIdentificationI ()
bool isWallInteraction ()
virtual bool isBonded () const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
Mdouble maxOverlap_
Additional Inherited Members
Protected Member Functions inherited from BaseInteraction
virtual const Vec3D getTangentialForce () const
Mdouble getEffectiveRadius () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
Mdouble getEffectiveMass () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
void setRelativeVelocity (Vec3D relativeVelocity)
set the relative velocity of the current of the interactions.
void setNormalRelativeVelocity (Mdouble normalRelativeVelocit)
set the normal component of the relative velocity.
void setAbsoluteNormalForce (Mdouble absoluteNormalForce)
the absolute values of the norm (length) of the normal force
virtual Mdouble getElasticEnergyAtEquilibrium (Mdouble adhesiveForce) const
virtual void reverseHistory ()
When periodic particles some interaction need certain history properties reversing. This is the function for that.
void writeInteraction (std::ostream &os, bool created) const
Writes information about a interaction to the interaction file.
Detailed Description
Computes normal forces in case of a linear plastic visco-elastic interaction.
Constructor & Destructor Documentation
HertzianSinterInteraction() [1/3]
HertzianSinterInteraction::HertzianSinterInteraction (BaseInteractable * P, BaseInteractable * I, unsigned timeStamp)
Constructor.
Parameters
[in] P
[in] I
[in] timeStamp
         : BaseInteraction(P, I, timeStamp)
 {
     maxOverlap_ = 0;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"HertzianSinterInteraction::HertzianSinterInteraction() finished"<<std::endl;
 #endif
 }
References maxOverlap_.
HertzianSinterInteraction() [2/3]
HertzianSinterInteraction::HertzianSinterInteraction (const HertzianSinterInteraction & p)
Copy constructor.
Parameters
[in] p
         : BaseInteraction(p)
 {
     maxOverlap_ = p.maxOverlap_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"HertzianSinterInteraction::HertzianSinterInteraction(const HertzianSinterInteraction &p finished"<<std::endl;
 #endif
 }
References maxOverlap_, and p.
HertzianSinterInteraction() [3/3]
HertzianSinterInteraction::HertzianSinterInteraction () default
Todo:
: MX add interaction to mpi
~HertzianSinterInteraction()
HertzianSinterInteraction::~HertzianSinterInteraction () override
Destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"HertzianSinterInteraction::~HertzianSinterInteraction() finished"<<std::endl;
 #endif
 }
Member Function Documentation
computeNormalForce()
void HertzianSinterInteraction::computeNormalForce ()
Calls computeSinterForce().
 {
     computeSinterForce();
 }
References computeSinterForce().
computeSinterForce()
void HertzianSinterInteraction::computeSinterForce ()
Creates a copy of an object of this class. (Deep copy)
Computes the normal forces due to linear plastic visco elastic interaction.
 {
     // Compute the relative velocity vector of particle P w.r.t. I
     setRelativeVelocity(
             getP()->getVelocityAtContact(getContactPoint()) - getI()->getVelocityAtContact(getContactPoint()));
     // Compute the projection of vrel onto the normal (can be negative)
     setNormalRelativeVelocity(Vec3D::dot(getRelativeVelocity(), getNormal()));
     if (getOverlap() > 0) //if contact forces
     {
         const HertzianSinterNormalSpecies* species = getSpecies();
         Mdouble effectiveDiameter = 2.0 * getEffectiveRadius();
         //calculate the overlap above which the max. unloading stiffness becomes active (the 'fluid branch')
         static Mdouble maxFactor = 1
                                    - mathsFunc::square(
                 cbrt((species->getLoadingModulus() + species->getCohesionModulus()) /
                      species->getUnloadingModulusMax()));
         Mdouble deltaStar = species->getPenetrationDepthMax() * effectiveDiameter / maxFactor;
         //increase max overlap if necessary
         if (getOverlap() > getMaxOverlap())
         {
             setMaxOverlap(getOverlap());
             logger(INFO, ",%", getHandler()->getDPMBase()->getTime(), Flusher::NO_FLUSH);
         }
         //limit max overlap if necessary
         if (getMaxOverlap() > deltaStar)
             setMaxOverlap(deltaStar);
         //calculate the unloading modulus
         Mdouble loadingCohesionModulus = species->getLoadingModulus() + species->getCohesionModulus();
         Mdouble unloadingModulus = loadingCohesionModulus
                                    + (species->getUnloadingModulusMax() - loadingCohesionModulus) *
                                      (getMaxOverlap() / deltaStar);
         //calculate the overlap where the force is minimal
         Mdouble factor = 1 - mathsFunc::square(cbrt(loadingCohesionModulus / unloadingModulus));
         Mdouble minOverlap = factor * maxOverlap_;
         //add dissipative force
         Mdouble normalForce = -species->getDissipation() * getNormalRelativeVelocity();
         //compute elastic force
         if (getOverlap() < minOverlap)
         {
             //decrease max overlap if in cohesive range
             logger(INFO, ".%", getHandler()->getDPMBase()->getTime(), Flusher::NO_FLUSH);
             setMaxOverlap(getOverlap() / factor);
         }
         else
         {
             Mdouble contactRadius = sqrt(2.0 * effectiveDiameter * (getOverlap() - minOverlap));
             normalForce += 4. / 3. * unloadingModulus * contactRadius * (getOverlap() - minOverlap);
         }
         setAbsoluteNormalForce(std::abs(normalForce)); //used for the friction force calculations;
         Mdouble contactRadius = sqrt(2.0 * effectiveDiameter * getOverlap());
         normalForce -= 4. / 3. * species->getCohesionModulus() * contactRadius * getOverlap();
         setForce(getNormal() * normalForce);
         setTorque(Vec3D(0.0, 0.0, 0.0));
         //now add the sintering model 'modified Frenkel' of the Pokula paper
         //plasticOverlap_+=species->getSinterRate()*(deltaStar-plasticOverlap_)*getHandler()->getDPMBase()->getTimeStep();
         //x/a=sqrt(2*a*del)/a
         Mdouble x = 1e-10 + sqrt(2.0 * maxOverlap_ / effectiveDiameter);
         //Mdouble x2 = x*x;
         Mdouble dx = 0.5 /
                      x;//+ x*(-0.5 + x2* (0.15625 + x2*(-0.0208333 +x2*(-0.00325521  +x2*(0.000189887 +x2*0.0000542535)))));
         Mdouble doverlap = x * dx * effectiveDiameter;
         //doverlap = 0.5/(factor*factor*plasticOverlap_);
         maxOverlap_ += species->getSinterRate() * doverlap * getHandler()->getDPMBase()->getTimeStep();
     }
     else
     {
         setAbsoluteNormalForce(0.0);
         setForce(Vec3D(0.0, 0.0, 0.0));
         setTorque(Vec3D(0.0, 0.0, 0.0));
     }
 }
References abs(), Eigen::numext::cbrt(), Vec3D::dot(), e(), HertzianSinterNormalSpecies::getCohesionModulus(), BaseInteraction::getContactPoint(), HertzianSinterNormalSpecies::getDissipation(), BaseHandler< T >::getDPMBase(), BaseInteraction::getEffectiveRadius(), BaseInteraction::getHandler(), BaseInteraction::getI(), HertzianSinterNormalSpecies::getLoadingModulus(), getMaxOverlap(), BaseInteraction::getNormal(), BaseInteraction::getNormalRelativeVelocity(), BaseInteraction::getOverlap(), BaseInteraction::getP(), HertzianSinterNormalSpecies::getPenetrationDepthMax(), BaseInteraction::getRelativeVelocity(), HertzianSinterNormalSpecies::getSinterRate(), getSpecies(), DPMBase::getTimeStep(), HertzianSinterNormalSpecies::getUnloadingModulusMax(), INFO, logger, maxOverlap_, NO_FLUSH, BaseInteraction::setAbsoluteNormalForce(), BaseInteraction::setForce(), setMaxOverlap(), BaseInteraction::setNormalRelativeVelocity(), BaseInteraction::setRelativeVelocity(), BaseInteraction::setTorque(), sqrt(), mathsFunc::square(), and plotDoE::x.
Referenced by computeNormalForce().
getBaseName()
std::string HertzianSinterInteraction::getBaseName () const virtual
Returns the name of the interaction.
Returns
std::string
 {
     return "HertzianSinter";
 }
getElasticEnergy()
Mdouble HertzianSinterInteraction::getElasticEnergy () const override virtual
Computes and returns the amount of elastic energy stored in the spring.
Returns
Mdouble
Todo:
TW this is not correct; we should count the return energy
Reimplemented from BaseInteraction.
 {
     if (getOverlap() > 0)
         return 0.5 * (getSpecies()->getLoadingModulus() * mathsFunc::square(getOverlap()));
     else
         return 0.0;
 }
References HertzianSinterNormalSpecies::getLoadingModulus(), BaseInteraction::getOverlap(), getSpecies(), and mathsFunc::square().
getMaxOverlap()
Mdouble HertzianSinterInteraction::getMaxOverlap () const
Returns
Mdouble plasticOverlap_
 {
     return maxOverlap_;
 }
References maxOverlap_.
Referenced by computeSinterForce(), and getUnloadingModulus().
getSpecies()
const HertzianSinterNormalSpecies * HertzianSinterInteraction::getSpecies () const
Returns
const HertzianSinterNormalSpecies*
 {
     return static_cast<const HertzianSinterNormalSpecies*>(getBaseSpecies()->getNormalForce());
 }
References BaseInteraction::getBaseSpecies(), and BaseSpecies::getNormalForce().
Referenced by computeSinterForce(), getElasticEnergy(), and getUnloadingModulus().
getUnloadingModulus()
Mdouble HertzianSinterInteraction::getUnloadingModulus () const
Returns
Mdouble
 {
     const HertzianSinterNormalSpecies* species = getSpecies();
     Mdouble effectiveDiameter = 2.0 * getEffectiveRadius();
     Mdouble deltaMaxFluid = species->getPenetrationDepthMax() * effectiveDiameter /
                             (1.0 - species->getLoadingModulus() / species->getUnloadingModulusMax());
     if (getOverlap() > deltaMaxFluid)
         return species->getUnloadingModulusMax();
     else
         return species->getLoadingModulus() +
                (species->getUnloadingModulusMax() - species->getLoadingModulus()) * getMaxOverlap() / deltaMaxFluid;
 }
References BaseInteraction::getEffectiveRadius(), HertzianSinterNormalSpecies::getLoadingModulus(), getMaxOverlap(), BaseInteraction::getOverlap(), HertzianSinterNormalSpecies::getPenetrationDepthMax(), getSpecies(), and HertzianSinterNormalSpecies::getUnloadingModulusMax().
read()
void HertzianSinterInteraction::read (std::istream & is) override virtual
Interaction read function, which accepts an std::istream as input.
Calls the read function of BaseInteraction().
Parameters
[in,out] is
Reimplemented from BaseInteraction.
 {
     BaseInteraction::read(is);
     std::string dummy;
     is >> dummy >> maxOverlap_;
 }
References maxOverlap_, BaseInteraction::read(), and oomph::Global_string_for_annotation::string().
setMaxOverlap()
void HertzianSinterInteraction::setMaxOverlap (Mdouble maxOverlap)
Parameters
[in] maxOverlap
 {
     maxOverlap_ = maxOverlap;
 }
References maxOverlap_.
Referenced by computeSinterForce().
write()
void HertzianSinterInteraction::write (std::ostream & os) const override virtual
Interaction write function, which accepts an std::ostream as input.
Calls the write function of BaseInteraction().
Parameters
[in,out] os
Reimplemented from BaseInteraction.
 {
     BaseInteraction::write(os);
     os << " maxOverlap " << maxOverlap_;
 }
References maxOverlap_, and BaseInteraction::write().
Member Data Documentation
maxOverlap_
Mdouble HertzianSinterInteraction::maxOverlap_ private
Referenced by computeSinterForce(), getMaxOverlap(), HertzianSinterInteraction(), read(), setMaxOverlap(), and write().
The documentation for this class was generated from the following files:
HertzianSinterInteraction.h
HertzianSinterInteraction.cc