MercuryDPM: MpiDataClass.cc File Reference
MpiDataClass.cc File Reference
#include "MpiDataClass.h"
#include "DPMBase.h"
#include "Particles/LiquidFilmParticle.h"
#include "Particles/SphericalParticle.h"
#include "Particles/SuperQuadricParticle.h"
#include "Logger.h"
Functions
void copyDataFromMPIParticleToParticle (MPIParticle *bP, BaseParticle *p, ParticleHandler *particleHandler)
Copies data from an MPIParticle class to a BaseParticle and sets the particleHandler and species.
MPIParticle copyDataFromParticleToMPIParticle (BaseParticle *p)
Copies data from a NonSphericalParticle to an MPIParticle class and returns this.
MPIParticlePosition copyPositionFrom (BaseParticle *particle)
Copies the position from a particle to an MPIParticlePosition class.
MPIParticleVelocity copyVelocityFrom (BaseParticle *particle)
Copies the velocity from a particle to an MPIParticleVelocity class.
Vec3D getMPISum (Vec3D &val)
double getMPISum (double val)
Function Documentation
copyDataFromMPIParticleToParticle()
void copyDataFromMPIParticleToParticle (MPIParticle * bP, BaseParticle * p, ParticleHandler * particleHandler)
Copies data from an MPIParticle class to a BaseParticle and sets the particleHandler and species.
Copies data from an MPIParticle class to a BaseParticle.
Parameters
[in] bP Pointer to an MPIParticle which contains data for a ghost particle
[in,out] p Pointer to BaseParticle, a ghost particle that will be added to the domain
[in] particleHandler Pointer to the ParticleHandler required for creating a new particle
Todo:
MX: Maybe renamet his function to setParticleSpecies() or something
 {
     //Set the species of the particle, but before we can do that we have to set the handler
     p->setHandler(particleHandler);
     //p->setIndSpecies(bP->indSpecies);
     const ParticleSpecies* species = p->getHandler()->getDPMBase()->speciesHandler.getObject(bP->indSpecies);
     p->setSpecies(species);
     bP->copyDataFromMPIParticleToParticle(p);
 }
References MPISphericalParticle::copyDataFromMPIParticleToParticle(), MPISphericalParticle::indSpecies, and p.
Referenced by ParticleHandler::addGhostObject(), ParticleHandler::addObject(), InsertionBoundary::checkBoundaryBeforeTimeStep(), RandomClusterInsertionBoundary::checkBoundaryBeforeTimeStep(), Domain::processReceivedBoundaryParticleData(), PeriodicBoundaryHandler::processReceivedGhostParticleData(), and DPMBase::synchroniseParticle().
copyDataFromParticleToMPIParticle()
MPIParticle copyDataFromParticleToMPIParticle (BaseParticle * p)
Copies data from a NonSphericalParticle to an MPIParticle class and returns this.
Copies data from a BaseParticle to an MPIParticle class and returns this.
In order to create ghost particles on other processors, data of particles have to be transmitted to other processors. Only the required data is sent. The data is sent in an MPIParticle data class and this function copies the data from a particle into that class.
Parameters
[in] p Pointer to a NonSphericalParticle particle from which data is copied
Returns
MPIParticle class is returned filled with data from BaseParticle p
 {
     MPIParticle bP;
     bP.copyDataFromParticleToMPIParticle(p);
     return bP;
 }
References MPISphericalParticle::copyDataFromParticleToMPIParticle(), and p.
Referenced by RandomClusterInsertionBoundary::checkBoundaryBeforeTimeStep(), Domain::collectBoundaryParticleData(), and PeriodicBoundaryHandler::collectGhostParticleData().
copyPositionFrom()
MPIParticlePosition copyPositionFrom (BaseParticle * particle)
Copies the position from a particle to an MPIParticlePosition class.
Parameters
[in] particle BaseParticle which position is copied
Returns
MPIParticlePosition object containing the position of the particle
 {
     MPIParticlePosition particlePosition;
     particlePosition.id = particle->getId();
     particlePosition.position = particle->getPosition();
     particlePosition.orientation = particle->getOrientation();
     if (std::is_base_of<MPILiquidFilmParticle,MPIParticle>())
         particlePosition.liquidVolume = static_cast<LiquidFilmParticle*>(particle)->getLiquidVolume();
     return particlePosition;
 }
References BaseObject::getId(), BaseInteractable::getOrientation(), BaseInteractable::getPosition(), MPIParticlePosition::id, MPIParticlePosition::liquidVolume, MPIParticlePosition::orientation, and MPIParticlePosition::position.
Referenced by Domain::preparePositionAndVelocityUpdate(), and PeriodicBoundaryHandler::preparePositionAndVelocityUpdate().
copyVelocityFrom()
MPIParticleVelocity copyVelocityFrom (BaseParticle * particle)
Copies the velocity from a particle to an MPIParticleVelocity class.
Parameters
[in] particle BaseParticle which velocity is copied
Returns
MPIParticleVelocityn object containing the velocity of the particle
 {
     MPIParticleVelocity particleVelocity;
     particleVelocity.velocity = particle->getVelocity();
     particleVelocity.angularVelocity = particle->getAngularVelocity();
     return particleVelocity;
 }
References MPIParticleVelocity::angularVelocity, BaseInteractable::getAngularVelocity(), BaseInteractable::getVelocity(), and MPIParticleVelocity::velocity.
Referenced by Domain::preparePositionAndVelocityUpdate(), PeriodicBoundaryHandler::preparePositionAndVelocityUpdate(), and Domain::prepareVelocityUpdate().
getMPISum() [1/2]
double getMPISum (double val)
Sums the values over all processors using MPI_reduce
 {
 #ifdef MERCURYDPM_USE_MPI
     //Sum up over all domains
     double valGlobal = 0.0;
     MPIContainer& communicator = MPIContainer::Instance();
     communicator.allReduce(val, valGlobal, MPI_SUM);
     return valGlobal;
 #else
     return val;
 #endif
 }
References MPIContainer::Instance(), and calibrate::val.
getMPISum() [2/2]
Vec3D getMPISum (Vec3D & val)
Sums the values over all processors using MPI_reduce
 {
 #ifdef MERCURYDPM_USE_MPI
     //Sum up over all domains
     Vec3D valGlobal = {0.0,0.0,0.0};
     MPIContainer& communicator = MPIContainer::Instance();
     communicator.allReduce(val.X, valGlobal.X, MPI_SUM);
     communicator.allReduce(val.Y, valGlobal.Y, MPI_SUM);
     communicator.allReduce(val.Z, valGlobal.Z, MPI_SUM);
     return valGlobal;
 #else
     return val;
 #endif
 }
References MPIContainer::Instance(), calibrate::val, Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by ParticleHandler::getAngularMomentum(), InteractionHandler::getLiquidBridgeVolume(), ParticleHandler::getLiquidFilmVolume(), ParticleHandler::getMomentum(), InteractionHandler::getNumberOfLiquidBridges(), and Membrane::saveVertexPositions().