MercuryDPM: Eigen::TriangularView< MatrixType_, Mode_ > Class Template Reference
Eigen::TriangularView< MatrixType_, Mode_ > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Expression of a triangular part in a matrix.
#include <TriangularMatrix.h>
Public Types
enum { Mode = Mode_ , Flags = internal::traits<TriangularView>::Flags , TransposeMode , IsVectorAtCompileTime = false }
typedef TriangularViewImpl< MatrixType_, Mode_, typename internal::traits< MatrixType_ >::StorageKind > Base
typedef internal::traits< TriangularView >::Scalar Scalar
typedef MatrixType_ MatrixType
typedef internal::traits< TriangularView >::StorageKind StorageKind
typedef internal::traits< TriangularView >::MatrixTypeNestedCleaned NestedExpression
typedef TriangularView< const MatrixConjugateReturnType, Mode > ConjugateReturnType
typedef TriangularView< const typename MatrixType::AdjointReturnType, TransposeMode > AdjointReturnType
typedef TriangularView< typename MatrixType::TransposeReturnType, TransposeMode > TransposeReturnType
typedef TriangularView< const typename MatrixType::ConstTransposeReturnType, TransposeMode > ConstTransposeReturnType
Public Member Functions
EIGEN_DEVICE_FUNC TriangularView (MatrixType &matrix)
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC const NestedExpression & nestedExpression () const
EIGEN_DEVICE_FUNC NestedExpression & nestedExpression ()
EIGEN_DEVICE_FUNC const ConjugateReturnType conjugate () const
template<bool Cond>
EIGEN_DEVICE_FUNC std::conditional_t< Cond, ConjugateReturnType, ConstTriangularView > conjugateIf () const
EIGEN_DEVICE_FUNC const AdjointReturnType adjoint () const
template<class Dummy = int>
EIGEN_DEVICE_FUNC TransposeReturnType transpose (std::enable_if_t< Eigen::internal::is_lvalue< MatrixType >::value, Dummy * >=nullptr)
EIGEN_DEVICE_FUNC const ConstTransposeReturnType transpose () const
template<typename Other >
EIGEN_DEVICE_FUNC const Solve< TriangularView, Other > solve (const MatrixBase< Other > &other) const
EIGEN_DEVICE_FUNC SelfAdjointView< MatrixTypeNestedNonRef, Mode > selfadjointView ()
EIGEN_DEVICE_FUNC const SelfAdjointView< MatrixTypeNestedNonRef, Mode > selfadjointView () const
EIGEN_DEVICE_FUNC Scalar determinant () const
Protected Types
typedef internal::traits< TriangularView >::MatrixTypeNested MatrixTypeNested
typedef internal::traits< TriangularView >::MatrixTypeNestedNonRef MatrixTypeNestedNonRef
typedef internal::remove_all_t< typename MatrixType::ConjugateReturnType > MatrixConjugateReturnType
typedef TriangularView< std::add_const_t< MatrixType >, Mode_ > ConstTriangularView
Protected Attributes
MatrixTypeNested m_matrix
Detailed Description
template<typename MatrixType_, unsigned int Mode_>
class Eigen::TriangularView< MatrixType_, Mode_ >
Expression of a triangular part in a matrix.
Template Parameters
MatrixType the type of the object in which we are taking the triangular part
Mode the kind of triangular matrix expression to construct. Can be Upper, Lower, UnitUpper, UnitLower, StrictlyUpper, or StrictlyLower. This is in fact a bit field; it must have either Upper or Lower, and additionally it may have UnitDiag or ZeroDiag or neither.
This class represents a triangular part of a matrix, not necessarily square. Strictly speaking, for rectangular matrices one should speak of "trapezoid" parts. This class is the return type of MatrixBase::triangularView() and SparseMatrixBase::triangularView(), and most of the time this is the only way it is used.
See also
MatrixBase::triangularView()
Member Typedef Documentation
AdjointReturnType
template<typename MatrixType_ , unsigned int Mode_> typedef TriangularView<const typename MatrixType::AdjointReturnType, TransposeMode> Eigen::TriangularView< MatrixType_, Mode_ >::AdjointReturnType
Base
template<typename MatrixType_ , unsigned int Mode_> typedef TriangularViewImpl<MatrixType_, Mode_, typename internal::traits<MatrixType_>::StorageKind> Eigen::TriangularView< MatrixType_, Mode_ >::Base
ConjugateReturnType
template<typename MatrixType_ , unsigned int Mode_> typedef TriangularView<const MatrixConjugateReturnType, Mode> Eigen::TriangularView< MatrixType_, Mode_ >::ConjugateReturnType
ConstTransposeReturnType
template<typename MatrixType_ , unsigned int Mode_> typedef TriangularView<const typename MatrixType::ConstTransposeReturnType, TransposeMode> Eigen::TriangularView< MatrixType_, Mode_ >::ConstTransposeReturnType
ConstTriangularView
template<typename MatrixType_ , unsigned int Mode_> typedef TriangularView<std::add_const_t<MatrixType>, Mode_> Eigen::TriangularView< MatrixType_, Mode_ >::ConstTriangularView protected
MatrixConjugateReturnType
template<typename MatrixType_ , unsigned int Mode_> typedef internal::remove_all_t<typename MatrixType::ConjugateReturnType> Eigen::TriangularView< MatrixType_, Mode_ >::MatrixConjugateReturnType protected
MatrixType
template<typename MatrixType_ , unsigned int Mode_> typedef MatrixType_ Eigen::TriangularView< MatrixType_, Mode_ >::MatrixType
MatrixTypeNested
template<typename MatrixType_ , unsigned int Mode_> typedef internal::traits<TriangularView>::MatrixTypeNested Eigen::TriangularView< MatrixType_, Mode_ >::MatrixTypeNested protected
MatrixTypeNestedNonRef
template<typename MatrixType_ , unsigned int Mode_> typedef internal::traits<TriangularView>::MatrixTypeNestedNonRef Eigen::TriangularView< MatrixType_, Mode_ >::MatrixTypeNestedNonRef protected
NestedExpression
template<typename MatrixType_ , unsigned int Mode_> typedef internal::traits<TriangularView>::MatrixTypeNestedCleaned Eigen::TriangularView< MatrixType_, Mode_ >::NestedExpression
Scalar
template<typename MatrixType_ , unsigned int Mode_> typedef internal::traits<TriangularView>::Scalar Eigen::TriangularView< MatrixType_, Mode_ >::Scalar
StorageKind
template<typename MatrixType_ , unsigned int Mode_> typedef internal::traits<TriangularView>::StorageKind Eigen::TriangularView< MatrixType_, Mode_ >::StorageKind
TransposeReturnType
template<typename MatrixType_ , unsigned int Mode_> typedef TriangularView<typename MatrixType::TransposeReturnType, TransposeMode> Eigen::TriangularView< MatrixType_, Mode_ >::TransposeReturnType
Member Enumeration Documentation
anonymous enum
template<typename MatrixType_ , unsigned int Mode_> anonymous enum
Enumerator
Mode
Flags
TransposeMode
IsVectorAtCompileTime
        {
     Mode = Mode_,
     Flags = internal::traits<TriangularView>::Flags,
     TransposeMode = (int(Mode) & int(Upper) ? Lower : 0) | (int(Mode) & int(Lower) ? Upper : 0) |
                     (int(Mode) & int(UnitDiag)) | (int(Mode) & int(ZeroDiag)),
     IsVectorAtCompileTime = false
   };
Constructor & Destructor Documentation
TriangularView()
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC Eigen::TriangularView< MatrixType_, Mode_ >::TriangularView (MatrixType & matrix) inline explicit
 : m_matrix(matrix) {}
Member Function Documentation
adjoint()
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC const AdjointReturnType Eigen::TriangularView< MatrixType_, Mode_ >::adjoint () const inline
See also
MatrixBase::adjoint() const
 { return AdjointReturnType(m_matrix.adjoint()); }
References Eigen::TriangularView< MatrixType_, Mode_ >::m_matrix.
Referenced by Eigen::CholmodSimplicialLLT< MatrixType_, UpLo_ >::matrixU(), and Eigen::CholmodSimplicialLDLT< MatrixType_, UpLo_ >::matrixU().
cols()
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::TriangularView< MatrixType_, Mode_ >::cols () const inline
Returns
the number of columns.
See also
rows(), ColsAtCompileTime
 { return m_matrix.cols(); }
References Eigen::TriangularView< MatrixType_, Mode_ >::m_matrix.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
conjugate()
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC const ConjugateReturnType Eigen::TriangularView< MatrixType_, Mode_ >::conjugate (void) const inline
See also
MatrixBase::conjugate() const
{
     return ConjugateReturnType(m_matrix.conjugate());
   }
References Eigen::TriangularView< MatrixType_, Mode_ >::m_matrix.
conjugateIf()
template<typename MatrixType_ , unsigned int Mode_> template<bool Cond> EIGEN_DEVICE_FUNC std::conditional_t<Cond, ConjugateReturnType, ConstTriangularView> Eigen::TriangularView< MatrixType_, Mode_ >::conjugateIf () const inline
Returns
an expression of the complex conjugate of *this if Cond==true, returns *this otherwise.
{
     typedef std::conditional_t<Cond, ConjugateReturnType, ConstTriangularView> ReturnType;
     return ReturnType(m_matrix.template conjugateIf<Cond>());
   }
References Eigen::TriangularView< MatrixType_, Mode_ >::m_matrix.
determinant()
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC Scalar Eigen::TriangularView< MatrixType_, Mode_ >::determinant () const inline
Returns
the determinant of the triangular matrix
See also
MatrixBase::determinant()
{
     if (Mode & UnitDiag)
       return 1;
     else if (Mode & ZeroDiag)
       return 0;
     else
       return m_matrix.diagonal().prod();
   }
References Eigen::TriangularView< MatrixType_, Mode_ >::m_matrix, Eigen::TriangularView< MatrixType_, Mode_ >::Mode, Eigen::UnitDiag, and Eigen::ZeroDiag.
nestedExpression() [1/2]
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC NestedExpression& Eigen::TriangularView< MatrixType_, Mode_ >::nestedExpression () inline
Returns
a reference to the nested expression
 { return m_matrix; }
References Eigen::TriangularView< MatrixType_, Mode_ >::m_matrix.
nestedExpression() [2/2]
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC const NestedExpression& Eigen::TriangularView< MatrixType_, Mode_ >::nestedExpression () const inline
Returns
a const reference to the nested expression
 { return m_matrix; }
References Eigen::TriangularView< MatrixType_, Mode_ >::m_matrix.
Referenced by Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::operator*=(), and Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::operator/=().
rows()
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::TriangularView< MatrixType_, Mode_ >::rows () const inline
Returns
the number of rows.
See also
cols(), RowsAtCompileTime
 { return m_matrix.rows(); }
References Eigen::TriangularView< MatrixType_, Mode_ >::m_matrix.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
selfadjointView() [1/2]
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC SelfAdjointView<MatrixTypeNestedNonRef, Mode> Eigen::TriangularView< MatrixType_, Mode_ >::selfadjointView () inline
Returns
a selfadjoint view of the referenced triangular part which must be either Upper or Lower.
This is a shortcut for
this->nestedExpression().selfadjointView<(*this)::Mode>()
See also
MatrixBase::selfadjointView()
{
     EIGEN_STATIC_ASSERT((Mode & (UnitDiag | ZeroDiag)) == 0, PROGRAMMING_ERROR);
     return SelfAdjointView<MatrixTypeNestedNonRef, Mode>(m_matrix);
   }
References EIGEN_STATIC_ASSERT, Eigen::TriangularView< MatrixType_, Mode_ >::m_matrix, Eigen::TriangularView< MatrixType_, Mode_ >::Mode, Eigen::UnitDiag, and Eigen::ZeroDiag.
selfadjointView() [2/2]
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC const SelfAdjointView<MatrixTypeNestedNonRef, Mode> Eigen::TriangularView< MatrixType_, Mode_ >::selfadjointView () const inline
This is the const version of selfadjointView()
{
     EIGEN_STATIC_ASSERT((Mode & (UnitDiag | ZeroDiag)) == 0, PROGRAMMING_ERROR);
     return SelfAdjointView<MatrixTypeNestedNonRef, Mode>(m_matrix);
   }
solve()
template<typename MatrixType_ , unsigned int Mode_> template<typename Other > EIGEN_DEVICE_FUNC const Solve<TriangularView, Other> Eigen::TriangularView< MatrixType_, Mode_ >::solve (const MatrixBase< Other > & other) const inline
{
     return Solve<TriangularView, Other>(*this, other.derived());
   }
transpose() [1/2]
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC const ConstTransposeReturnType Eigen::TriangularView< MatrixType_, Mode_ >::transpose () const inline
See also
MatrixBase::transpose() const
{
     return ConstTransposeReturnType(m_matrix.transpose());
   }
References Eigen::TriangularView< MatrixType_, Mode_ >::m_matrix.
transpose() [2/2]
template<typename MatrixType_ , unsigned int Mode_> template<class Dummy = int> EIGEN_DEVICE_FUNC TransposeReturnType Eigen::TriangularView< MatrixType_, Mode_ >::transpose (std::enable_if_t< Eigen::internal::is_lvalue< MatrixType >::value, Dummy * > = nullptr) inline
See also
MatrixBase::transpose()
{
     typename MatrixType::TransposeReturnType tmp(m_matrix);
     return TransposeReturnType(tmp);
   }
References Eigen::TriangularView< MatrixType_, Mode_ >::m_matrix, and tmp.
Member Data Documentation
m_matrix
template<typename MatrixType_ , unsigned int Mode_> MatrixTypeNested Eigen::TriangularView< MatrixType_, Mode_ >::m_matrix protected
Referenced by Eigen::TriangularView< MatrixType_, Mode_ >::adjoint(), Eigen::TriangularView< MatrixType_, Mode_ >::cols(), Eigen::TriangularView< MatrixType_, Mode_ >::conjugate(), Eigen::TriangularView< MatrixType_, Mode_ >::conjugateIf(), Eigen::TriangularView< MatrixType_, Mode_ >::determinant(), Eigen::TriangularView< MatrixType_, Mode_ >::nestedExpression(), Eigen::TriangularView< MatrixType_, Mode_ >::rows(), Eigen::TriangularView< MatrixType_, Mode_ >::selfadjointView(), and Eigen::TriangularView< MatrixType_, Mode_ >::transpose().
The documentation for this class was generated from the following file:
TriangularMatrix.h