MercuryDPM: Counter Struct Reference
Counter Struct Reference
Public Member Functions
Counter ()=default
void inc ()
int value ()
Public Attributes
std::thread::id created_by
int counter_value = 0
Constructor & Destructor Documentation
Counter()
Counter::Counter () default
Member Function Documentation
inc()
void Counter::inc () inline
              {
     // Check that mutation happens only in a thread that created this counter.
     VERIFY_IS_EQUAL(std::this_thread::get_id(), created_by);
     counter_value++;
   }
References counter_value, created_by, and VERIFY_IS_EQUAL.
value()
int Counter::value () inline
 { return counter_value; }
References counter_value.
Referenced by test_large_number_of_tasks_no_spill(), test_large_number_of_tasks_with_spill(), test_simple_thread_local(), and test_zero_sized_thread_local().
Member Data Documentation
counter_value
int Counter::counter_value = 0
Referenced by inc(), and value().
created_by
std::thread::id Counter::created_by
Referenced by inc(), and InitCounter::operator()().
The documentation for this struct was generated from the following file:
cxx11_tensor_thread_local.cpp