MercuryDPM: Eigen::internal::lapacke_helpers::lapacke_llt< Scalar, Mode > Struct Template Reference
Eigen::internal::lapacke_helpers::lapacke_llt< Scalar, Mode > Struct Template Reference
#include <LLT_LAPACKE.h>
Public Member Functions
EIGEN_STATIC_ASSERT (((Mode==Lower)||(Mode==Upper)), MODE_MUST_BE_UPPER_OR_LOWER) template< typename MatrixType > static Index blocked(MatrixType &m)
Static Public Member Functions
template<typename MatrixType , typename VectorType >
static Index rankUpdate (MatrixType &mat, const VectorType &vec, const typename MatrixType::RealScalar &sigma)
Member Function Documentation
EIGEN_STATIC_ASSERT()
template<typename Scalar , UpLoType Mode> Eigen::internal::lapacke_helpers::lapacke_llt< Scalar, Mode >::EIGEN_STATIC_ASSERT (((Mode==Lower)||(Mode==Upper)) , MODE_MUST_BE_UPPER_OR_LOWER) & inline
{
     eigen_assert(m.rows() == m.cols());
     if (m.rows() == 0) {
       return -1;
     }
     /* Set up parameters for ?potrf */
     lapack_int size = to_lapack(m.rows());
     lapack_int matrix_order = lapack_storage_of(m);
     constexpr char uplo = Mode == Upper ? 'U' : 'L';
     Scalar *a = &(m.coeffRef(0, 0));
     lapack_int lda = to_lapack(m.outerStride());
     lapack_int info = potrf(matrix_order, uplo, size, to_lapack(a), lda);
     info = (info == 0) ? -1 : info > 0 ? info - 1 : size;
     return info;
   }
References a, eigen_assert, info, lapack_int, Eigen::internal::lapacke_helpers::lapack_storage_of(), lda, m, size, Eigen::internal::lapacke_helpers::to_lapack(), uplo, and Eigen::Upper.
rankUpdate()
template<typename Scalar , UpLoType Mode> template<typename MatrixType , typename VectorType > static Index Eigen::internal::lapacke_helpers::lapacke_llt< Scalar, Mode >::rankUpdate (MatrixType & mat, const VectorType & vec, const typename MatrixType::RealScalar & sigma) inline static
{
     return rank_update<Mode>::run(mat, vec, sigma);
   }
References run(), and calibrate::sigma.
The documentation for this struct was generated from the following file:
LLT_LAPACKE.h