MercuryDPM: HeaterBoundaryTest.cpp File Reference
HeaterBoundaryTest.cpp File Reference
#include <iostream>
#include <Species/LinearViscoelasticSpecies.h>
#include "Mercury3D.h"
#include "Boundaries/HeaterBoundary.h"
#include "Walls/InfiniteWall.h"
#include "MercuryTime.h"
Classes
class HeaterBoundaryTest
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     Time time;
     time.tic();
     HeaterBoundaryTest problem;
     LinearViscoelasticSpecies species;
     species.setDensity(2000);
     species.setDissipation(0.005);
     species.setStiffness(1e3);
     problem.speciesHandler.copyAndAddObject(species);
     problem.setXMax(0.1);
     problem.setYMax(0.1);
     problem.setZMax(0.1);
     problem.N = 1000;
     problem.setName("HeaterBoundaryTest");
     problem.setGravity(Vec3D(0.0, 0.0, 0.0));
     problem.setTimeStep(4e-5);
 //    logger(INFO, "dt / tc = % / % = 1/%",
 //            problem.getTimeStep(), species.getCollisionTime( 2000 * 4./3. * constants::pi * pow(0.002,3)),
 //            1/(problem.getTimeStep() / species.getCollisionTime( 2000 * 4./3. * constants::pi * pow(0.002,3))));
     problem.setSaveCount(25);
     problem.setTimeMax(0.3);
     problem.setSystemDimensions(3);
     problem.setHGridMaxLevels(1);
     problem.setHGridCellOverSizeRatio(1.2);
     problem.setHGridUpdateEachTimeStep(false);
     problem.dataFile.setFileType(FileType::MULTIPLE_FILES);
     problem.solve();
     logger(INFO, "Total time to run this simulation: % s", time.toc());
 }
References e(), INFO, logger, MULTIPLE_FILES, problem, ParticleSpecies::setDensity(), LinearViscoelasticNormalSpecies::setDissipation(), LinearViscoelasticNormalSpecies::setStiffness(), Time::tic(), and Time::toc().