MercuryDPM: direct_solver_test.cc File Reference
linear_solvers/direct_solver_test.cc File Reference
#include "generic.h"
#include "poisson.h"
#include "meshes/one_d_mesh.h"
Classes
class OneDPoissonProblem< ELEMENT >
1D Poisson problem in unit interval.
Namespaces
FishSolnOneDPoisson
Namespace for fish-shaped solution of 1D Poisson equation.
Functions
void FishSolnOneDPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact, fish-shaped solution as a 1D vector.
void FishSolnOneDPoisson::source_function (const Vector< double > &x, double &source)
Source function required to make the fish shape an exact solution.
int main (int argc, char **argv)
Driver for 1D Poisson problem.
Variables
int FishSolnOneDPoisson::Sign =-1
Function Documentation
main()
int main (int argc , char ** argv)
Driver for 1D Poisson problem.
//////////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////////
 {
  //Number of elements
  unsigned n_element=40;
  // global distribution
  // LinearAlgebraDistribution
  //  distributed_dist(problem.communicator_pt(),ndof,true);
  // the doc info
  DocInfo doc_info;
  doc_info.set_directory("RESLT");
  // DenseLU Test
  // MATRIX BASED SOLVE / DenseDoubleMatrix
  {
   oomph_info
    << "///////////////////////////////////////////////////////////////////////"
    << std::endl;
   oomph_info << "TESTING: DenseLU matrix based solve w/ DenseDoubleMatrix"
              << std::endl;
   oomph_info
    << "///////////////////////////////////////////////////////////////////////"
    << std::endl << std::endl;
   OneDPoissonProblem<QPoissonElement<1,4> >
     problem(n_element,FishSolnOneDPoisson::source_function);
   DenseDoubleMatrix A;
   DoubleVector b;
   DoubleVector x;
   DenseLU solver;
   problem.get_jacobian(b,A);
   solver.enable_doc_time();
   solver.solve(&A,b,x);
   x.output("RESLT/DenseLU_DenseDoubleMatrix.dat");
  }
  // PROBLEM BASED SOLVE
  {
   oomph_info
    << "///////////////////////////////////////////////////////////////////////"
    << std::endl;
   oomph_info << "TESTING: DenseLU problem based solve"
              << std::endl;
   oomph_info
    << "///////////////////////////////////////////////////////////////////////"
    << std::endl << std::endl;
   OneDPoissonProblem<QPoissonElement<1,4> >
     problem(n_element,FishSolnOneDPoisson::source_function);
   DoubleVector x;
   DenseLU solver;
   problem.linear_solver_pt() = &solver;
   problem.newton_solve();
   problem.doc_solution(doc_info);
   problem.zero_dofs();
  }
  // FD_LU Test
  // PROBLEM BASED SOLVE
  {
   oomph_info
    << "///////////////////////////////////////////////////////////////////////"
    << std::endl;
   oomph_info << "TESTING: FD_LU problem based solve"
              << std::endl;
   oomph_info
    << "///////////////////////////////////////////////////////////////////////"
    << std::endl << std::endl;
   OneDPoissonProblem<QPoissonElement<1,4> >
     problem(n_element,FishSolnOneDPoisson::source_function);
   FD_LU solver;
   problem.linear_solver_pt() = &solver;
   problem.newton_solve();
   doc_info.number()++;
   problem.doc_solution(doc_info);
   problem.zero_dofs();
  }
  // SuperLU Test
  // MATRIX BASED SOLVE / CRDoubleMatrix (global)
  {
   oomph_info
    << "///////////////////////////////////////////////////////////////////////"
    << std::endl;
   oomph_info << "TESTING: SuperLU matrix based solve w/ global CRDoubleMatrix"
              << std::endl;
   oomph_info
    << "///////////////////////////////////////////////////////////////////////"
    << std::endl << std::endl;
   OneDPoissonProblem<QPoissonElement<1,4> >
     problem(n_element,FishSolnOneDPoisson::source_function);
   unsigned ndof = problem.ndof();
   LinearAlgebraDistribution global_dist(problem.communicator_pt(),ndof,false);
   CRDoubleMatrix A(&global_dist);
   DoubleVector b(&global_dist,0.0);
   DoubleVector x(&global_dist,0.0);
   SuperLUSolver solver;
   problem.get_jacobian(b,A);
   solver.enable_doc_time();
   solver.solve(&A,b,x);
   x.output("RESLT/SuperLU_CRDoubleMatrix.dat");
  }
  // MATRIX BASED SOLVE / CCDoubleMatrix
  {
   oomph_info
    << "///////////////////////////////////////////////////////////////////////"
    << std::endl;
   oomph_info << "TESTING: SuperLU matrix based solve w/ CCDoubleMatrix"
              << std::endl;
   oomph_info
    << "///////////////////////////////////////////////////////////////////////"
    << std::endl << std::endl;
   OneDPoissonProblem<QPoissonElement<1,4> >
     problem(n_element,FishSolnOneDPoisson::source_function);
   CCDoubleMatrix A;
   DoubleVector b;
   DoubleVector x;
   SuperLUSolver solver;
   problem.get_jacobian(b,A);
   solver.enable_doc_time();
   solver.solve(&A,b,x);
   x.output("RESLT/SuperLU_CCDoubleMatrix.dat");
  }
  // PROBLEM BASED SOLVE
  {
   oomph_info
    << "///////////////////////////////////////////////////////////////////////"
    << std::endl;
   oomph_info << "TESTING: SuperLU problem based solve"
              << std::endl;
   oomph_info
    << "///////////////////////////////////////////////////////////////////////"
    << std::endl << std::endl;
   OneDPoissonProblem<QPoissonElement<1,4> >
     problem(n_element,FishSolnOneDPoisson::source_function);
   DoubleVector x;
   SuperLUSolver solver;
   problem.linear_solver_pt() = &solver;
   problem.newton_solve();
   doc_info.number()++;
   problem.doc_solution(doc_info);
   problem.zero_dofs();
  }
 } // end of main
References b, oomph::DocInfo::number(), oomph::oomph_info, problem, oomph::DocInfo::set_directory(), solver, FishSolnOneDPoisson::source_function(), and plotDoE::x.