MercuryDPM: UnitCubePoissonMGProblem< ELEMENT, MESH > Class Template Reference
UnitCubePoissonMGProblem< ELEMENT, MESH > Class Template Reference
Public Member Functions
UnitCubePoissonMGProblem (PoissonEquations< 3 >::PoissonSourceFctPt source_fct_pt)
Constructor: Pass pointer to source function.
~UnitCubePoissonMGProblem ()
Destructor: Empty.
void actions_before_newton_solve ()
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void doc_solution (DocInfo &doc_info)
Document the solution.
UnitCubePoissonMGProblem (PoissonEquations< 3 >::PoissonSourceFctPt source_fct_pt)
Constructor: Pass pointer to source function.
~UnitCubePoissonMGProblem ()
Destructor: Empty.
void actions_before_newton_solve ()
void actions_after_newton_solve ()
Update the problem specs after solve.
void doc_solution ()
Document the solution.
Public Member Functions inherited from oomph::MGProblem
MGProblem ()
Constructor. Initialise pointers to coarser and finer levels.
virtual ~MGProblem ()
Destructor (empty)
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
virtual void actions_before_adapt ()
virtual void actions_after_adapt ()
Actions that are to be performed after a mesh adaptation.
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Private Member Functions
MESH * mesh_pt ()
void set_multigrid_solver ()
Build and set multgrid solver.
TreeBasedRefineableMeshBase * mg_bulk_mesh_pt ()
MGProblem * make_new_problem ()
Return a pointer to a new instance of the same problem.
MESH * mesh_pt ()
void set_multigrid_solver ()
Build and set multgrid solver.
TreeBasedRefineableMeshBase * mg_bulk_mesh_pt ()
MGProblem * make_new_problem ()
Return a pointer to a new instance of the same problem.
Private Attributes
PoissonEquations< 3 >::PoissonSourceFctPt Source_fct_pt
Pointer to source function.
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_convergence_check ()
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_before_implicit_timestep ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual void set_initial_condition ()
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class ELEMENT, class MESH>
class UnitCubePoissonMGProblem< ELEMENT, MESH >
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// 3D Poisson problem in a unit cube with Dirichlet conditions applied on all six faces. The specific type of element and mesh used here is specified via the template parameter.
Constructor & Destructor Documentation
UnitCubePoissonMGProblem() [1/2]
template<class ELEMENT , class MESH > UnitCubePoissonMGProblem< ELEMENT, MESH >::UnitCubePoissonMGProblem (PoissonEquations< 3 >::PoissonSourceFctPt source_fct_pt)
Constructor: Pass pointer to source function.
Constructor for Poisson problem in a unit cube.
  : Source_fct_pt(source_fct_pt)
 {
  // Set up the multigrid solver
  set_multigrid_solver();
  // Set the steepness of the step in the exact tanh solution
  TanhSolnForPoisson::Alpha=50.0;
  // Build the mesh:
  //----------------
  // The number of elements in the x-direction
  unsigned n_x=2;
  // The number of elements in the y-direction
  unsigned n_y=2;
  // The number of elements in the z-direction
  unsigned n_z=2;
  // The length of the mesh in the x-direction
  unsigned l_x=1.0;
  // The length of the mesh in the y-direction
  unsigned l_y=1.0;
  // The length of the mesh in the z-direction
  unsigned l_z=1.0;
  // Create the mesh
  Problem::mesh_pt()=new MESH(n_x,n_y,n_z,l_x,l_y,l_z);
  // Set boundary conditions:
  //-------------------------
  // Find the number of boundaries the mesh possesses
  unsigned n_bound=mesh_pt()->nboundary();
  // Loop over the boundaries of the mesh
  for(unsigned b=0;b<n_bound;b++)
  {
   // Find the number of nodes on the b-th boundary
   unsigned n_node=mesh_pt()->nboundary_node(b);
   // Loop over the boundary nodes
   for (unsigned n=0;n<n_node;n++)
   {
    // All nodes are free by default -- we just need to pin the ones that
    // have Dirichlet conditions here
    mesh_pt()->boundary_node_pt(b,n)->pin(0);
   }
  } // for(unsigned b=0;b<n_bound;b++)
  // Find the number of elements in the mesh
  unsigned n_element=mesh_pt()->nelement();
  // Complete the build of all elements so they are fully functional:
  //-----------------------------------------------------------------
  // Loop over the elements in the mesh and pass in the source function pointer
  for(unsigned i=0;i<n_element;i++)
  {
   // Upcast the element to the type specified by the template parameter
   ELEMENT* el_pt=dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(i));
   // Set the source function pointer
   el_pt->source_fct_pt()=Source_fct_pt;
  }
  // Set up the equation numbering scheme
  assign_eqn_numbers();
 } // End of UnitCubePoissonMGProblem constructor
References TanhSolnForPoisson::Alpha, oomph::Problem::assign_eqn_numbers(), b, i, UnitCubePoissonMGProblem< ELEMENT, MESH >::mesh_pt(), n, UnitCubePoissonMGProblem< ELEMENT, MESH >::set_multigrid_solver(), and UnitCubePoissonMGProblem< ELEMENT, MESH >::Source_fct_pt.
~UnitCubePoissonMGProblem() [1/2]
template<class ELEMENT , class MESH > UnitCubePoissonMGProblem< ELEMENT, MESH >::~UnitCubePoissonMGProblem () inline
Destructor: Empty.
   {
    // Delete the MG solver pointers
    delete linear_solver_pt();
    // Set the pointer to null
    linear_solver_pt()=0;
    // Delete the mesh that was created in the constructor
    delete mesh_pt();
    // Make the associated pointer a null pointer
    Problem::mesh_pt()=0;
   } // End of ~UnitCubePoissonMGProblem
UnitCubePoissonMGProblem() [2/2]
template<class ELEMENT , class MESH > UnitCubePoissonMGProblem< ELEMENT, MESH >::UnitCubePoissonMGProblem (PoissonEquations< 3 >::PoissonSourceFctPt source_fct_pt)
Constructor: Pass pointer to source function.
~UnitCubePoissonMGProblem() [2/2]
template<class ELEMENT , class MESH > UnitCubePoissonMGProblem< ELEMENT, MESH >::~UnitCubePoissonMGProblem () inline
Destructor: Empty.
   {
    // If we're using multigrid as the linear solver
    if (Global_Parameters::Linear_solver_flag==1)
    {
     // Delete the MG solver pointers
     delete linear_solver_pt();
     // Set the pointer to null
     linear_solver_pt()=0;
    }
    // Delete the mesh that was created in the constructor
    delete mesh_pt();
    // Make the associated pointer a null pointer
    Problem::mesh_pt()=0;
   } // End of ~UnitCubePoissonMGProblem
References Global_Parameters::Linear_solver_flag.
Member Function Documentation
actions_after_newton_solve() [1/2]
template<class ELEMENT , class MESH > void UnitCubePoissonMGProblem< ELEMENT, MESH >::actions_after_newton_solve () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [2/2]
template<class ELEMENT , class MESH > void UnitCubePoissonMGProblem< ELEMENT, MESH >::actions_after_newton_solve () inline virtual
Update the problem specs after solve.
Reimplemented from oomph::Problem.
   {
    // Document the solution
    doc_solution();
   }
actions_before_newton_solve() [1/2]
template<class ELEMENT , class MESH > void UnitCubePoissonMGProblem< ELEMENT, MESH >::actions_before_newton_solve virtual
Update the problem specs before solve: Set Dirichlet boundary conditions from exact solution.
Update the problem specs before solve: Reset boundary conditions to the values from the exact solution.
Reimplemented from oomph::Problem.
 {
  // Get the number of boundaries in the mesh
  unsigned num_bound=mesh_pt()->nboundary();
  // Loop over the boundaries
  for(unsigned ibound=0;ibound<num_bound;ibound++)
  {
   // Get the number of nodes on the ibound-th boundary
   unsigned num_nod=mesh_pt()->nboundary_node(ibound);
   // Loop over the nodes on ibound-th boundary
   for (unsigned inod=0;inod<num_nod;inod++)
   {
    // Grab the inod-th node on the ibound-th boundary
    Node* nod_pt=mesh_pt()->boundary_node_pt(ibound,inod);
    // Create a vector to hold the (Eulerian) position of the node
    Vector<double> x(3,0.0);
    // Loop over each coordinate
    for (unsigned k=0;k<3;k++)
    {
     // Store the k-th coordinate of the node in x
     x[k]=nod_pt->x(k);
    }
    // Create a variable to store the solution at this position
    double u=0.0;
    // Calculate the exact solution at this point
    TanhSolnForPoisson::get_exact_u(x,u);
    // Assign the value of the solution at this node
    nod_pt->set_value(0,u);
   }
  } // for(unsigned ibound=0;ibound<num_bound;ibound++)
 } // End of actions_before_newton_solve
References TanhSolnForPoisson::get_exact_u(), k, oomph::Data::set_value(), plotDoE::x, and oomph::Node::x().
actions_before_newton_solve() [2/2]
template<class ELEMENT , class MESH > void UnitCubePoissonMGProblem< ELEMENT, MESH >::actions_before_newton_solve () virtual
Update the problem specs before solve: Set Dirichlet boundary conditions from exact solution.
Reimplemented from oomph::Problem.
doc_solution() [1/2]
template<class ELEMENT , class MESH > void UnitCubePoissonMGProblem< ELEMENT, MESH >::doc_solution
Document the solution.
Doc the solution.
 {
  // Output file stream
  ofstream some_file;
  // Create an array of characters to store the filename
  char filename[100];
  // Number of plot points
  unsigned npts=3;
  // Output solution:
  //-----------------
  // Create the filename
  sprintf(filename,"%s/soln%i.dat",
      Global_Parameters::Doc_info.directory().c_str(),
      Global_Parameters::Doc_info.number());
  // Open a file with the filename given above
  some_file.open(filename);
  // Document the computed solution
  mesh_pt()->output(some_file,npts);
  // Close the file
  some_file.close();
  // Output exact solution:
  //-----------------------
  // Create the filename
  sprintf(filename,"%s/exact_soln%i.dat",
      Global_Parameters::Doc_info.directory().c_str(),
      Global_Parameters::Doc_info.number());
  // Open a file with the filename given above
  some_file.open(filename);
  // Document the exact solution
  mesh_pt()->output_fct(some_file,npts,TanhSolnForPoisson::get_exact_u);
  // Close the file
  some_file.close();
  // Document the error:
  //--------------------
  // Note: this is only calculated over the bulk mesh as we cannot properly
  // deal with two different types of elements
  // Create storage for the L2 norm of the error
  double error=0.0;
  // Create storage for the L2 norm of the solution
  double soln=0.0;
  // Create the filename
  sprintf(filename,"%s/error%i.dat",
      Global_Parameters::Doc_info.directory().c_str(),
      Global_Parameters::Doc_info.number());
  // Open a file with the filename given above
  some_file.open(filename);
  // Compute the error and document it
  mesh_pt()->compute_error(some_file,TanhSolnForPoisson::get_exact_u,error,soln);
  // Close the file
  some_file.close();
  // Output the L2 norm of the error and solution and the relative error:
  //---------------------------------------------------------------------
  oomph_info << "Norm of error    : " << sqrt(error) << std::endl;
  oomph_info << "Norm of solution : " << sqrt(soln) << std::endl;
  oomph_info << "Relative error   : " << sqrt(error)/sqrt(soln) << std::endl;
  // Increment the documentation counter
  Global_Parameters::Doc_info.number()++;
 } // End of doc_solution
References Global_Parameters::Doc_info, calibrate::error, MergeRestartFiles::filename, TanhSolnForPoisson::get_exact_u(), oomph::DocInfo::number(), oomph::oomph_info, and sqrt().
doc_solution() [2/2]
template<class ELEMENT , class MESH > void UnitCubePoissonMGProblem< ELEMENT, MESH >::doc_solution (DocInfo & doc_info)
Document the solution.
Doc the solution.
 {
  // Output file stream
  ofstream some_file;
  // Create an array of characters to store the filename
  char filename[100];
  // Number of plot points
  unsigned npts=3;
  // Output solution:
  //-----------------
  // Create the filename
  sprintf(filename,"%s/soln%i.dat",
      doc_info.directory().c_str(),
      doc_info.number());
  // Open a file with the filename given above
  some_file.open(filename);
  // Document the computed solution
  mesh_pt()->output(some_file,npts);
  // Close the file
  some_file.close();
  // Output exact solution:
  //-----------------------
  // Create the filename
  sprintf(filename,"%s/exact_soln%i.dat",
      doc_info.directory().c_str(),
      doc_info.number());
  // Open a file with the filename given above
  some_file.open(filename);
  // Document the exact solution
  mesh_pt()->output_fct(some_file,npts,TanhSolnForPoisson::get_exact_u);
  // Close the file
  some_file.close();
  // Document the error:
  //--------------------
  // Note: this is only calculated over the bulk mesh as we cannot properly
  // deal with two different types of elements
  // Create storage for the L2 norm of the error
  double error=0.0;
  // Create storage for the L2 norm of the solution
  double soln=0.0;
  // Create the filename
  sprintf(filename,"%s/error%i.dat",
      doc_info.directory().c_str(),
      doc_info.number());
  // Open a file with the filename given above
  some_file.open(filename);
  // Compute the error and document it
  mesh_pt()->compute_error(some_file,TanhSolnForPoisson::get_exact_u,error,soln);
  // Close the file
  some_file.close();
  // Output the L2 norm of the error and solution and the relative error:
  //---------------------------------------------------------------------
  oomph_info << "Norm of error    : " << sqrt(error) << std::endl;
  oomph_info << "Norm of solution : " << sqrt(soln) << std::endl;
  oomph_info << "Relative error   : " << sqrt(error)/sqrt(soln) << std::endl;
  // Increment the documentation counter
  doc_info.number()++;
 } // End of doc_solution
References oomph::DocInfo::directory(), calibrate::error, MergeRestartFiles::filename, TanhSolnForPoisson::get_exact_u(), oomph::DocInfo::number(), oomph::oomph_info, and sqrt().
make_new_problem() [1/2]
template<class ELEMENT , class MESH > MGProblem* UnitCubePoissonMGProblem< ELEMENT, MESH >::make_new_problem () inline private virtual
Return a pointer to a new instance of the same problem.
Implements oomph::MGProblem.
   {
    // Return a pointer to a new object of the UnitCubePoissonMGProblem class
    return new UnitCubePoissonMGProblem<ELEMENT,MESH>
     (&TanhSolnForPoisson::get_source);
   } // End of make_new_problem
References TanhSolnForPoisson::get_source().
make_new_problem() [2/2]
template<class ELEMENT , class MESH > MGProblem* UnitCubePoissonMGProblem< ELEMENT, MESH >::make_new_problem () inline private virtual
Return a pointer to a new instance of the same problem.
Implements oomph::MGProblem.
   {
    // Return a pointer to a new object of the UnitCubePoissonMGProblem class
    return new UnitCubePoissonMGProblem<ELEMENT,MESH>
     (&TanhSolnForPoisson::get_source);
   } // End of make_new_problem
References TanhSolnForPoisson::get_source().
mesh_pt() [1/2]
template<class ELEMENT , class MESH > MESH* UnitCubePoissonMGProblem< ELEMENT, MESH >::mesh_pt () inline private
Overload generic access function to the mesh by one that returns a pointer to the mesh with return type specified by the template parameter
   {
    // Upcast to the appropriate mesh type
    return dynamic_cast<MESH*>(Problem::mesh_pt());
   } // End of mesh_pt
Referenced by UnitCubePoissonMGProblem< ELEMENT, MESH >::UnitCubePoissonMGProblem().
mesh_pt() [2/2]
template<class ELEMENT , class MESH > MESH* UnitCubePoissonMGProblem< ELEMENT, MESH >::mesh_pt () inline private
Overload generic access function to the mesh by one that returns a pointer to the mesh with return type specified by the template parameter
   {
    // Upcast to the appropriate mesh type
    return dynamic_cast<MESH*>(Problem::mesh_pt());
   } // End of mesh_pt
mg_bulk_mesh_pt() [1/2]
template<class ELEMENT , class MESH > TreeBasedRefineableMeshBase* UnitCubePoissonMGProblem< ELEMENT, MESH >::mg_bulk_mesh_pt () inline private virtual
Pointer to the bulk mesh. Overloads the pure virtual function in the abstract base class, MGProblem. Must be refineable to allow the use of refine_base_mesh_as_in_reference_mesh_minus_one() in make_copy()
Implements oomph::MGProblem.
   {
    // Return a handle to the global mesh
    return mesh_pt();
   } // End of mg_bulk_mesh_pt
mg_bulk_mesh_pt() [2/2]
template<class ELEMENT , class MESH > TreeBasedRefineableMeshBase* UnitCubePoissonMGProblem< ELEMENT, MESH >::mg_bulk_mesh_pt () inline private virtual
Pointer to the bulk mesh. Overloads the pure virtual function in the abstract base class, MGProblem. Must be refineable to allow the use of refine_base_mesh_as_in_reference_mesh_minus_one() in make_copy()
Implements oomph::MGProblem.
   {
    // Return a handle to the global mesh
    return mesh_pt();
   } // End of mg_bulk_mesh_pt
set_multigrid_solver() [1/2]
template<class ELEMENT , class MESH > void UnitCubePoissonMGProblem< ELEMENT, MESH >::set_multigrid_solver private
Build and set multgrid solver.
Build and set multigrid solver.
Build and set the multigrid solver.
 {
  // Make an object of the MGSolver class and get the pointer to it
  MGSolver<3>* mg_solver_pt=new MGSolver<3>(this);
  // Switch solver to MG
  linear_solver_pt()=mg_solver_pt;
  // Set the pre-smoother factory function
  mg_solver_pt->set_pre_smoother_factory_function
   (Smoother_Factory_Function_Helper::set_smoother);
  // Set the post-smoother factory function
  mg_solver_pt->set_post_smoother_factory_function
   (Smoother_Factory_Function_Helper::set_smoother);
  // Create a file to record the convergence history
  mg_solver_pt->open_convergence_history_file_stream("RESLT/conv.dat");
 } // End of set_multigrid_solver
References oomph::IterativeLinearSolver::open_convergence_history_file_stream(), oomph::MGSolver< DIM >::set_post_smoother_factory_function(), oomph::MGSolver< DIM >::set_pre_smoother_factory_function(), and Smoother_Factory_Function_Helper::set_smoother().
Referenced by UnitCubePoissonMGProblem< ELEMENT, MESH >::UnitCubePoissonMGProblem().
set_multigrid_solver() [2/2]
template<class ELEMENT , class MESH > void UnitCubePoissonMGProblem< ELEMENT, MESH >::set_multigrid_solver () private
Build and set multgrid solver.
Member Data Documentation
Source_fct_pt
template<class ELEMENT , class MESH > PoissonEquations< 3 >::PoissonSourceFctPt UnitCubePoissonMGProblem< ELEMENT, MESH >::Source_fct_pt private
Pointer to source function.
Referenced by UnitCubePoissonMGProblem< ELEMENT, MESH >::UnitCubePoissonMGProblem().
The documentation for this class was generated from the following files:
unit_cube_poisson.cc
unit_cube_poisson_validate.cc