MercuryDPM: curved_facet_bounded_tetmesh.cc File Reference
curved_facet_bounded_tetmesh.cc File Reference
#include <fenv.h>
#include "generic.h"
#include "poisson.h"
#include "meshes/triangle_mesh.h"
#include "meshes/tetgen_mesh.h"
#include "meshes/refineable_tetgen_mesh.h"
#include "meshes/gmsh_tet_mesh.h"
#include "tetmesh_faceted_surfaces.h"
Classes
class TetmeshPoissonProblem< ELEMENT >
Demo class solves Poisson problem using Gmsh mesh.
Namespaces
Global_Parameters
Namespace for global parameters.
Functions
int main (int argc, char *argv[])
Driver.
Variables
double Global_Parameters::Box_half_width = 1.5
(Half-)width of the box
double Global_Parameters::Box_half_length = 1.0
(Half)height of the box
std::string Global_Parameters::Gmsh_command_line_invocation ="/home/mheil/gmesh/bin/bin/gmsh"
Specify how to call gmsh from the command line.
Function Documentation
main()
int main (int argc , char * argv[])
Driver.
 {
  MPI_Helpers::init(argc,argv);
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // length of downstream region occupied by impedance elements
  CommandLineArgs::specify_command_line_flag("--suppress_bulk_output");
 #ifndef DO_TETGEN
  // Gmsh command line invocation
  CommandLineArgs::specify_command_line_flag
   ("--gmsh_command_line",
    &Global_Parameters::Gmsh_command_line_invocation);
 #endif
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
 #ifndef DO_TETGEN
  // Are you suicidal?
  if (!CommandLineArgs::command_line_flag_has_been_set("--gmsh_command_line"))
   {
    std::string error_msg
     ("You haven't specified how gmsh is invoked on the command line\n");
    error_msg += "on your computer, so I'll use the default\n\n" +
     Global_Parameters::Gmsh_command_line_invocation
     + "\n\nwhich, unless you're mheil, is unlikely to work and I will "
     + "now die...\n";
    throw OomphLibError(error_msg,
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
   }
 #endif
  // Note that this can make tetgen die!
  //feenableexcept(FE_INVALID | FE_DIVBYZERO | FE_OVERFLOW | FE_UNDERFLOW);
  // Shut up prefix
  oomph_info.output_modifier_pt()=&default_output_modifier;
  // Label for output
  DocInfo doc_info;
  // Output directory
  doc_info.set_directory("RESLT");
  // Number of output points per edge
  unsigned nplot=5;
  // Build problem
  TetmeshPoissonProblem<ProjectablePoissonElement<
   TPoissonElement<3,3> > > problem;
  //Output initial guess
  problem.doc_solution(nplot,doc_info);
  doc_info.number()++;
  unsigned max_adapt=1;
  for (unsigned i=0;i<=max_adapt;i++)
   {
    // Solve the bastard!
    problem.newton_solve();
    //Output solution
    problem.doc_solution(nplot,doc_info);
    // oomph_info << "tmp stop\n";
    // exit(0);
    //Increment counter for solutions
    doc_info.number()++;
    if (i!=max_adapt)
     {
      problem.adapt();
     }
   }
 }
References oomph::CommandLineArgs::command_line_flag_has_been_set(), oomph::default_output_modifier, oomph::CommandLineArgs::doc_specified_flags(), Global_Parameters::Gmsh_command_line_invocation, i, oomph::DocInfo::number(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, oomph::OomphInfo::output_modifier_pt(), oomph::CommandLineArgs::parse_and_assign(), problem, oomph::DocInfo::set_directory(), Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), and oomph::Global_string_for_annotation::string().