MercuryDPM: SphereInsertionBoundary Class Reference
SphereInsertionBoundary Class Reference
Inserts particles in a sphere with a given radius, polar and azimuthal radius at a specific origin which is 0 by default.
#include <SphereInsertionBoundary.h>
Public Member Functions
SphereInsertionBoundary ()
Constructor; sets everything to 0.
SphereInsertionBoundary (const SphereInsertionBoundary &other)
Copy constructor with deep copy.
~SphereInsertionBoundary () override
Destructor: default destructor.
SphereInsertionBoundary * copy () const override
Creates a copy on the heap and returns a pointer.
void set (BaseParticle *particleToCopy, unsigned int maxFailed, Mdouble rMin, Mdouble rMax, Mdouble thetaMin=0, Mdouble thetaMax=2.0 *constants::pi, Mdouble phiMin=0, Mdouble phiMax=constants::pi, Vec3D velMin={0, 0, 0}, Vec3D velMax={0, 0, 0})
Sets the properties of the InsertionBoundary for mutliple different particle types.
void set (BaseParticle &particleToCopy, unsigned int maxFailed, Mdouble rMin, Mdouble rMax, Mdouble thetaMin=0, Mdouble thetaMax=2.0 *constants::pi, Mdouble phiMin=0, Mdouble phiMax=constants::pi, Vec3D velMin={0, 0, 0}, Vec3D velMax={0, 0, 0})
void set (std::vector< BaseParticle * > particleToCopy, unsigned int maxFailed, Mdouble rMin, Mdouble rMax, Mdouble thetaMin=0, Mdouble thetaMax=2.0 *constants::pi, Mdouble phiMin=0, Mdouble phiMax=constants::pi, Vec3D velMin={0, 0, 0}, Vec3D velMax={0, 0, 0})
Sets the properties of the InsertionBoundary for a single particle type.
void set (BaseParticle *particleToCopy, unsigned int maxFailed, Mdouble radMin, Mdouble radMax, Mdouble thetaMin, Mdouble thetaMax, Mdouble phiMin, Mdouble phiMax, Vec3D velMin, Vec3D velMax, Mdouble particleRMin, Mdouble particleRMax)
old style set function which assumes a uniform psd.
void set (BaseParticle &particleToCopy, unsigned int maxFailed, Mdouble radMin, Mdouble radMax, Mdouble thetaMin, Mdouble thetaMax, Mdouble phiMin, Mdouble phiMax, Vec3D velMin, Vec3D velMax, Mdouble particleRMin, Mdouble particleRMax)
old style set function which assumes a uniform psd.
void setGeometry (Mdouble rMin, Mdouble rMax, Mdouble thetaMin, Mdouble thetaMax, Mdouble phiMin, Mdouble phiMax)
Sets the geometry (position and orientation) of the SphereInsertionBoundary.
Vec3D getOrigin () const
Returns the origin of the spheres coordinate system.
void shiftBoundary (Vec3D shift) override
shift the origin of the sphere in the cartesian coordinate system
void placeParticle (BaseParticle *p, RNG &random) override
Generates a random position, velocity for the particle p.
void read (std::istream &is) override
reads boundary properties from istream
void write (std::ostream &os) const override
writes boundary properties to ostream
Public Member Functions inherited from InsertionBoundary
InsertionBoundary ()
InsertionBoundary (const InsertionBoundary &other)
Copy constructor (with deep copy)
~InsertionBoundary () override
Destructor: delete the particle that has to be copied at every insertion.
virtual BaseParticle * generateParticle (RNG &random)
Sets the properties of the InsertionBoundary for a single particle type ‍/ virtual void set(BaseParticle* particleToCopy, unsigned int maxFailed, Vec3D velMin, Vec3D velMax, double radMin, double radMax)=0;.
virtual void rotateBoundary (Vec3D angle)
virtual function that rotates the boundary.
void checkBoundaryBeforeTimeStep (DPMBase *md) override
Fills the boundary with particles.
void insertParticles (DPMBase *md)
Fill a certain domain with particles.
unsigned int getNumberOfParticlesInserted () const
Gets the number of particles inserted by the boundary.
Mdouble getMassOfParticlesInserted () const
Gets the mass of particles inserted by the boundary.
Mdouble getVolumeOfParticlesInserted () const
Gets the volume of particles inserted by the boundary.
void reset ()
resets particle property counter variables.
void activate ()
Turns on the InsertionBoundary.
void deactivate ()
Turns off the InsertionBoundary.
bool isActivated ()
Returns whether the InsertionBoundary is activated.
unsigned int getMaxFailed () const
Gets the number of times that the boundary may fail to insert a particle.
void setParticleToCopy (std::vector< BaseParticle * > particleToCopy)
Sets multiple different particles that will be inserted through the insertion boundary.
void setParticleToCopy (BaseParticle *particleToCopy)
Sets the particle that will be inserted through the insertion boundary.
std::vector< BaseParticle * > getParticleToCopy ()
Gets the particles that will be inserted through the insertion boundary.
Mdouble getVolumeFlowRate () const
Gets the volume flow rate of the insertion routine.
void setVolumeFlowRate (Mdouble volumeFlowRate)
Sets the volume flow rate of the insertion routine.
Mdouble getInitialVolume () const
Gets the initialVolume() .
void setInitialVolume (Mdouble initialVolume)
Gets the Volume which should be inserted by the insertion routine.
void setPSD (const PSD psd)
Sets the range of particle radii that may be generated from a user defined PSD.
void setPSD (std::vector< PSD > psd, std::vector< Mdouble > probability)
Sets the ranges of particle radii that may be generated from user defined PSDs.
std::vector< PSD > getPSD ()
Gets the particle size distributions set by the user.
void setVariableVolumeFlowRate (const std::vector< Mdouble > &variableCumulativeVolumeFlowRate, Mdouble samplingInterval)
Sets a variable volume flow rate.
bool insertParticle (Mdouble time)
Checks the inserted total volume and returns if a particle is still allowed to be inserted.
bool getCheckParticleForInteraction () const
Gets the variable that checks if a particle has an interaction.
void setCheckParticleForInteraction (bool checkParticleForInteraction)
Sets the variable that checks if a particle has an interaction.
void setManualInsertion (bool manualInsertion)
Set the flag for a manual PSD insertion routine.
Public Member Functions inherited from BaseBoundary
BaseBoundary ()
default constructor.
BaseBoundary (const BaseBoundary &b)
copy constructor
~BaseBoundary () override
destructor
virtual void createPeriodicParticle (BaseParticle *p UNUSED, ParticleHandler &pH UNUSED)
Creates a periodic particle in case of periodic boundaries in serial build.
virtual void createPeriodicParticles (ParticleHandler &pH UNUSED)
Creates periodic copies of given particle in case of periodic boundaries.
virtual void checkBoundaryAfterParticlesMove (ParticleHandler &pH)
Virtual function that does things to particles, each time step after particles have moved.
virtual void actionsBeforeTimeLoop ()
Virtual function that does something after DPMBase::setupInitialConditions but before the first time step.
virtual void modifyGhostAfterCreation (BaseParticle *particle, int i)
virtual void writeVTK (std::fstream &file)
void setHandler (BoundaryHandler *handler)
Sets the boundary's BoundaryHandler.
BoundaryHandler * getHandler () const
Returns the boundary's BoundaryHandler.
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Protected Attributes
Mdouble thetaMin_
Minimal and maximal azimuth angle in range [0,2*pi] defining the circle of the sphere in which insertion should happen.
Mdouble thetaMax_
Mdouble phiMin_
Minimal and maximal polar angle in range [0,pi] defining the circle of the sphere in which insertion should happen.
Mdouble phiMax_
Mdouble radMin_
Minimal and maximal radius defining the inner and outer circle of the sphere in which insertion should happen.
Mdouble radMax_
Vec3D origin_
origin of the sphere.
Private Member Functions
std::string getName () const override
Returns the name of the object.
Additional Inherited Members
Public Attributes inherited from InsertionBoundary
std::vector< BaseParticle * > particleToCopy_
read Distribution class from file. ‍/ friend std::istream& operator>>(std::istream& is, InsertionBoundary::Distribution& type);
unsigned int maxFailed_
Number of times that the wall may fail to insert a particle.
unsigned int numberOfParticlesInserted_
Number of particles that are already inserted.
Mdouble massInserted_
Total mass of particles inserted.
Mdouble volumeInserted_
Total volume of particles inserted.
bool isActivated_
The InsertionBoundary is activated by default. If the InsertionBoundary is deactivated, then it introduces no particles (useful for trying to maintain a certain insertion rate).
Mdouble volumeFlowRate_
Mdouble initialVolume_
std::vector< Mdouble > variableCumulativeVolumeFlowRate_
Mdouble samplingInterval_
bool checkParticleForInteraction_
Checks if a particle has an interaction with a wall or other particles.
std::vector< PSD > particleSizeDistributionVector_
Defines a particle size distribution as an object of the PSD class; if particleSizeDistributionVector_ is empty, distribution_ is used instead.
Vec3D velMin_
Minimum and maximum velocity of the particles to be inserted.
Vec3D velMax_
bool isManuallyInserting_
A flag to enable a top-down class-by-class manual insertion of a PSD; default is FALSE.
std::vector< Mdouble > probability_
vector of probabilities in range [0,1] which determine the mixing ratio of partice size distributions.
int chosenSpecies_
stores the chosen species for each timestep.
BaseParticle * p0 = nullptr
pointer to the next particle that should be inserted (needs to be stored across time steps).
Detailed Description
Inserts particles in a sphere with a given radius, polar and azimuthal radius at a specific origin which is 0 by default.
Constructor & Destructor Documentation
SphereInsertionBoundary() [1/2]
SphereInsertionBoundary::SphereInsertionBoundary ()
Constructor; sets everything to 0.
Default constructor; sets every data member to 0.
 {
     radMin_ = 0.0;
     radMax_ = 0.0;
     phiMin_ = 0.0;
     phiMax_ = 0.0;
     thetaMin_ = 0.0;
     thetaMax_ = 0.0;
     origin_.setZero();
 }
References origin_, phiMax_, phiMin_, radMax_, radMin_, Vec3D::setZero(), thetaMax_, and thetaMin_.
Referenced by copy().
SphereInsertionBoundary() [2/2]
SphereInsertionBoundary::SphereInsertionBoundary (const SphereInsertionBoundary & other)
Copy constructor with deep copy.
Copy constructor
         : InsertionBoundary(other)
 {
     radMin_ = other.radMin_;
     radMax_ = other.radMax_;
     phiMin_ = other.phiMin_;
     phiMax_ = other.phiMax_;
     thetaMin_ = other.thetaMin_;
     thetaMax_ = other.thetaMax_;
     origin_ = other.origin_;
 }
References origin_, phiMax_, phiMin_, radMax_, radMin_, thetaMax_, and thetaMin_.
~SphereInsertionBoundary()
SphereInsertionBoundary::~SphereInsertionBoundary () override default
Destructor: default destructor.
Destructor. Since there are no pointers in this class, there is no need for any actions here.
Member Function Documentation
copy()
SphereInsertionBoundary * SphereInsertionBoundary::copy () const override virtual
Creates a copy on the heap and returns a pointer.
Copy method; creates a copy on the heap and returns its pointer.
Returns
pointer to the copy on the heap
Implements BaseBoundary.
 {
 #ifdef DEBUG_CONSTRUCTOR
     std::cout << "SphereInsertionBoundary::copy() const finished" << std::endl;
 #endif
     return new SphereInsertionBoundary(*this);
 }
References SphereInsertionBoundary().
getName()
std::string SphereInsertionBoundary::getName () const override private virtual
Returns the name of the object.
Returns the name of the object class
Returns
the object's class' name, i.e. 'SphereInsertionBoundary'
Implements BaseObject.
 {
     return "SphereInsertionBoundary";
 }
getOrigin()
Vec3D SphereInsertionBoundary::getOrigin () const
Returns the origin of the spheres coordinate system.
Returns the origin of the spheres coordinate system
Returns
origin_ the origin of the spheres coordinate system
 {
     return origin_;
 }
References origin_.
Referenced by PSDSelfTest::setupInitialConditions().
placeParticle()
void SphereInsertionBoundary::placeParticle (BaseParticle * p, RNG & random) override virtual
Generates a random position, velocity for the particle p.
places a particle with random position (although within the boundary, of course), velocity and radius and returns its pointer.
Parameters
[in] random Random number generator
Implements InsertionBoundary.
 {
     // create vectors for cartesian position and velocity and cylindrical position
     Vec3D pos, vel, posSpherical;
     // draw random numbers in cartesian coordinates and make sure they are inside the sphere sphere
     do
     {
         pos.X = random.getRandomNumber(-radMax_,radMax_);
         pos.Y = random.getRandomNumber(-radMax_,radMax_);
         pos.Z = random.getRandomNumber(-radMax_,radMax_);
         posSpherical = pos.getSphericalCoordinates();
     }
         // make sure particle stay inside the sphere of our sphere
     while (posSpherical.X > radMax_ ||
            posSpherical.X < radMin_ ||
            posSpherical.Y < phiMin_ ||
            posSpherical.Y >= phiMax_ ||
            posSpherical.Z < thetaMin_||
            posSpherical.Z >= thetaMax_);
     // set the velocity in cartesian coordinates
     vel.X = random.getRandomNumber(velMin_.X, velMax_.X);
     vel.Y = random.getRandomNumber(velMin_.Y, velMax_.Y);
     vel.Z = random.getRandomNumber(velMin_.Z, velMax_.Z);
     p->setPosition(pos + origin_);
     p->setVelocity(vel);
 }
References RNG::getRandomNumber(), Vec3D::getSphericalCoordinates(), origin_, p, phiMax_, phiMin_, radMax_, radMin_, thetaMax_, thetaMin_, InsertionBoundary::velMax_, InsertionBoundary::velMin_, Vec3D::X, Vec3D::Y, and Vec3D::Z.
read()
void SphereInsertionBoundary::read (std::istream & is) override virtual
reads boundary properties from istream
Reads the boundary properties from an istream
Parameters
[in,out] is the istream
Reimplemented from InsertionBoundary.
 {
     InsertionBoundary::read(is);
     std::string dummy;
     is >> dummy >> radMin_
        >> dummy >> radMax_;
     is >> dummy >> phiMin_
        >> dummy >> phiMax_;
     is >> dummy >> thetaMin_
        >> dummy >> thetaMax_;
     is >> dummy >> velMin_
        >> dummy >> velMax_;
     is >> dummy >> origin_;
 }
References origin_, phiMax_, phiMin_, radMax_, radMin_, InsertionBoundary::read(), oomph::Global_string_for_annotation::string(), thetaMax_, thetaMin_, InsertionBoundary::velMax_, and InsertionBoundary::velMin_.
set() [1/5]
void SphereInsertionBoundary::set (BaseParticle & particleToCopy, unsigned int maxFailed, Mdouble radMin, Mdouble radMax, Mdouble thetaMin, Mdouble thetaMax, Mdouble phiMin, Mdouble phiMax, Vec3D velMin, Vec3D velMax, Mdouble particleRMin, Mdouble particleRMax)
old style set function which assumes a uniform psd.
 {
     PSD uniformPSD;
     uniformPSD.setDistributionUniform(particleRMin, particleRMax, 2);
     setPSD(uniformPSD);
     set(particleToCopy, maxFailed, radMin, radMax, thetaMin, thetaMax, phiMin, phiMax, velMin, velMax);
 }
References set(), PSD::setDistributionUniform(), and InsertionBoundary::setPSD().
set() [2/5]
void SphereInsertionBoundary::set (BaseParticle & particleToCopy, unsigned int maxFailed, Mdouble rMin, Mdouble rMax, Mdouble thetaMin = 0, Mdouble thetaMax = 2.0*constants::pi, Mdouble phiMin = 0, Mdouble phiMax = constants::pi, Vec3D velMin = {0, 0, 0}, Vec3D velMax = {0, 0, 0})
 {
     set(&particleToCopy, maxFailed, radMin, radMax, thetaMin, thetaMax, phiMin, phiMax, velMin, velMax);
 }
References set().
set() [3/5]
void SphereInsertionBoundary::set (BaseParticle * particleToCopy, unsigned int maxFailed, Mdouble radMin, Mdouble radMax, Mdouble thetaMin, Mdouble thetaMax, Mdouble phiMin, Mdouble phiMax, Vec3D velMin, Vec3D velMax, Mdouble particleRMin, Mdouble particleRMax)
old style set function which assumes a uniform psd.
old style set function which also assumes a uniform psd. Note if you want a specific PSD do not use but this is quicker for a uniform in size PSD
 {
     PSD uniformPSD;
     uniformPSD.setDistributionUniform(particleRMin, particleRMax, 2);
     setPSD(uniformPSD);
     set(particleToCopy, maxFailed, radMin, radMax, thetaMin, thetaMax, phiMin, phiMax, velMin, velMax);
 }
References set(), PSD::setDistributionUniform(), and InsertionBoundary::setPSD().
set() [4/5]
void SphereInsertionBoundary::set (BaseParticle * particleToCopy, unsigned int maxFailed, Mdouble radMin, Mdouble radMax, Mdouble thetaMin = 0, Mdouble thetaMax = 2.0*constants::pi, Mdouble phiMin = 0, Mdouble phiMax = constants::pi, Vec3D velMin = {0, 0, 0}, Vec3D velMax = {0, 0, 0})
Sets the properties of the InsertionBoundary for mutliple different particle types.
Sets all the properties of the cylindrical insertion boundary.
Parameters
[in] particleToCopy Pointer to the BaseParticle which is used as a basis for the particles to be inserted
[in] maxFailed The maximum number of times the insertion of a particle may be tried and failed before the insertion of particles is considered done NB: this property is used in the parent's InsertionBoundary::checkBoundaryBeforeTimeStep().
[in] radMin minimal radius defining of the sphere boundary
[in] radMax maximal radius of the sphere boundary
[in] phiMin Minimal polar angle of the sphere boundary
[in] phiMax maximal polar angle of the sphere boundary
[in] thetaMin minimal azimuth angle of the sphere boundary
[in] thetaMax maximal azimuth angle of the sphere boundary
[in] velMin Minimum velocity of inserted particles
[in] velMax Maximum velocity of inserted particles
 {
     velMin_ = velMin;
     velMax_ = velMax;
     maxFailed_ = maxFailed;
     setParticleToCopy(particleToCopy);
     setGeometry(radMin, radMax, thetaMin, thetaMax, phiMin, phiMax);
 }
References InsertionBoundary::maxFailed_, setGeometry(), InsertionBoundary::setParticleToCopy(), InsertionBoundary::velMax_, and InsertionBoundary::velMin_.
Referenced by set(), InsertionBoundarySelfTest::setupInitialConditions(), and PSDSelfTest::setupInitialConditions().
set() [5/5]
void SphereInsertionBoundary::set (std::vector< BaseParticle * > particleToCopy, unsigned int maxFailed, Mdouble radMin, Mdouble radMax, Mdouble thetaMin = 0, Mdouble thetaMax = 2.0*constants::pi, Mdouble phiMin = 0, Mdouble phiMax = constants::pi, Vec3D velMin = {0, 0, 0}, Vec3D velMax = {0,0,0})
Sets the properties of the InsertionBoundary for a single particle type.
Sets all the properties of the cylindrical insertion boundary.
Parameters
[in] particleToCopy vector of pointers to the BaseParticles which are used as a basis for the particle types (species) to be inserted
[in] maxFailed The maximum number of times the insertion of a particle may be tried and failed before the insertion of particles is considered done NB: this property is used in the parent's InsertionBoundary::checkBoundaryBeforeTimeStep().
[in] radMin minimal radius defining of the sphere boundary
[in] radMax maximal radius of the sphere boundary
[in] phiMin Minimal polar angle of the sphere boundary
[in] phiMax maximal polar angle of the sphere boundary
[in] thetaMin minimal azimuth angle of the sphere boundary
[in] thetaMax maximal azimuth angle of the sphere boundary
[in] velMin Minimum velocity of inserted particles
[in] velMax Maximum velocity of inserted particles
 {
     velMin_ = velMin;
     velMax_ = velMax;
     maxFailed_ = maxFailed;
     setParticleToCopy(particleToCopy);
     setGeometry(radMin, radMax, thetaMin, thetaMax, phiMin, phiMax);
 }
References InsertionBoundary::maxFailed_, setGeometry(), InsertionBoundary::setParticleToCopy(), InsertionBoundary::velMax_, and InsertionBoundary::velMin_.
setGeometry()
void SphereInsertionBoundary::setGeometry (Mdouble rMin, Mdouble rMax, Mdouble thetaMin, Mdouble thetaMax, Mdouble phiMin, Mdouble phiMax)
Sets the geometry (position and orientation) of the SphereInsertionBoundary.
set the geometry of the Cylindrical insertion boundary by setting the position and orientation.
Parameters
[in] radMin minimal radius defining of the sphere boundary
[in] radMax maximal radius of the sphere boundary
[in] phiMin minimal polar angle of the sphere boundary
[in] phiMax maximal polar angle of the sphere boundary
[in] thetaMin minimal azimuth angle of the sphere boundary
[in] thetaMax maximal azimuth angle of the sphere boundary
 {
     radMin_ = rMin;
     radMax_ = rMax;
     phiMin_ = phiMin;
     phiMax_ = phiMax;
     thetaMin_ = thetaMin;
     thetaMax_ = thetaMax;
 }
References phiMax_, phiMin_, radMax_, radMin_, thetaMax_, and thetaMin_.
Referenced by set().
shiftBoundary()
void SphereInsertionBoundary::shiftBoundary (Vec3D shift) override virtual
shift the origin of the sphere in the cartesian coordinate system
shifts the sphere by a translation vector in the cartesian coordinate system
Parameters
[in] shift translation vector which shifts the sphere by certain X,Y,Z coordinates
Reimplemented from InsertionBoundary.
 {
     origin_ += shift;
 }
References origin_.
Referenced by PSDSelfTest::setupInitialConditions().
write()
void SphereInsertionBoundary::write (std::ostream & os) const override virtual
writes boundary properties to ostream
Writes boundary's properties to an ostream
Parameters
[in] os the ostream
Reimplemented from InsertionBoundary.
 {
     InsertionBoundary::write(os);
     os << " radMin " << radMin_
        << " radMax " << radMax_
        << " phiMin " << phiMin_
        << " phiMax " << phiMax_
        << " thetaMin " << thetaMin_
        << " thetaMax " << thetaMax_
        << " velMin " << velMin_
        << " velMax " << velMax_
        << " origin " << origin_;
 }
References origin_, phiMax_, phiMin_, radMax_, radMin_, thetaMax_, thetaMin_, InsertionBoundary::velMax_, InsertionBoundary::velMin_, and InsertionBoundary::write().
Member Data Documentation
origin_
Vec3D SphereInsertionBoundary::origin_ protected
origin of the sphere.
Referenced by getOrigin(), placeParticle(), read(), shiftBoundary(), SphereInsertionBoundary(), and write().
phiMax_
Mdouble SphereInsertionBoundary::phiMax_ protected
Referenced by placeParticle(), read(), setGeometry(), SphereInsertionBoundary(), and write().
phiMin_
Mdouble SphereInsertionBoundary::phiMin_ protected
Minimal and maximal polar angle in range [0,pi] defining the circle of the sphere in which insertion should happen.
Referenced by placeParticle(), read(), setGeometry(), SphereInsertionBoundary(), and write().
radMax_
Mdouble SphereInsertionBoundary::radMax_ protected
Referenced by placeParticle(), read(), setGeometry(), SphereInsertionBoundary(), and write().
radMin_
Mdouble SphereInsertionBoundary::radMin_ protected
Minimal and maximal radius defining the inner and outer circle of the sphere in which insertion should happen.
Referenced by placeParticle(), read(), setGeometry(), SphereInsertionBoundary(), and write().
thetaMax_
Mdouble SphereInsertionBoundary::thetaMax_ protected
Referenced by placeParticle(), read(), setGeometry(), SphereInsertionBoundary(), and write().
thetaMin_
Mdouble SphereInsertionBoundary::thetaMin_ protected
Minimal and maximal azimuth angle in range [0,2*pi] defining the circle of the sphere in which insertion should happen.
Referenced by placeParticle(), read(), setGeometry(), SphereInsertionBoundary(), and write().
The documentation for this class was generated from the following files:
SphereInsertionBoundary.h
SphereInsertionBoundary.cc