MercuryDPM: oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM > Class Template Reference
oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM > Class Template Reference
Refineable version of Unsteady Heat equations.
#include <refineable_discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h>
Public Member Functions
RefineableSpaceTimeUnsteadyHeatMixedOrderEquations ()
Constructor.
RefineableSpaceTimeUnsteadyHeatMixedOrderEquations (const RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM > &dummy)=delete
Broken copy constructor.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
void further_build ()
Further build: Copy source function pointer from father element.
Public Member Functions inherited from oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >
SpaceTimeUnsteadyHeatMixedOrderEquations ()
SpaceTimeUnsteadyHeatMixedOrderEquations (const SpaceTimeUnsteadyHeatMixedOrderEquations &dummy)=delete
Broken copy constructor.
void disable_ALE ()
void enable_ALE ()
void compute_norm (double &norm)
Compute norm of FE solution.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &nplot)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
virtual void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error and norm against exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Get error and norm against exact solution.
void output_element_paraview (std::ofstream &outfile, const unsigned &nplot)
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
std::string scalar_name_paraview (const unsigned &i) const
SpaceTimeUnsteadyHeatSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
SpaceTimeUnsteadyHeatSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
virtual void get_source_ust_heat (const double &t, const unsigned &ipt, const Vector< double > &x, double &source) const
const double & alpha () const
Alpha parameter (thermal inertia)
double *& alpha_pt ()
Pointer to Alpha parameter (thermal inertia)
const double & beta () const
Beta parameter (thermal conductivity)
double *& beta_pt ()
Pointer to Beta parameter (thermal conductivity)
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux: flux[i]=du/dx_i.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute element residual Vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute element residual Vector and element Jacobian matrix (wrapper)
double interpolated_u_ust_heat (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
virtual unsigned u_index_ust_heat () const
double interpolated_u_ust_heat (const unsigned &t, const Vector< double > &s) const
double du_dt_ust_heat (const unsigned &n) const
double interpolated_du_dt_ust_heat (const Vector< double > &s) const
unsigned self_test ()
Self-test: Return 0 for OK.
virtual double dshape_and_dtest_eulerian_ust_heat (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_ust_heat (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
virtual unsigned required_nsons () const
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)=0
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void rebuild_from_sons (Mesh *&mesh_pt)=0
virtual void unbuild ()
virtual void deactivate_element ()
virtual bool nodes_built ()
Return true if all the nodes have been built, false if not.
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual unsigned ncont_interpolated_values () const =0
virtual Node * interpolating_node_pt (const unsigned &n, const int &value_id)
virtual double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
virtual Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
virtual unsigned ninterpolating_node (const int &value_id)
virtual unsigned ninterpolating_node_1d (const int &value_id)
virtual void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
virtual void check_integrity (double &max_error)=0
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual RefineableElement * root_element_pt ()
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
virtual void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
virtual void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
Pre-build the element.
virtual void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
virtual void further_setup_hanging_nodes ()
void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
unsigned nshape_controlling_nodes ()
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Public Member Functions inherited from oomph::ElementWithZ2ErrorEstimator
ElementWithZ2ErrorEstimator ()
Default empty constructor.
ElementWithZ2ErrorEstimator (const ElementWithZ2ErrorEstimator &)=delete
Broken copy constructor.
void operator= (const ElementWithZ2ErrorEstimator &)=delete
Broken assignment operator.
virtual unsigned ncompound_fluxes ()
virtual void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
virtual void get_Z2_compound_flux_indices (Vector< unsigned > &flux_index)
virtual unsigned nvertex_node () const =0
Number of vertex nodes in the element.
virtual Node * vertex_node_pt (const unsigned &j) const =0
virtual unsigned nrecovery_order ()=0
Order of recovery shape functions.
virtual double geometric_jacobian (const Vector< double > &x)
Private Member Functions
virtual void fill_in_generic_residual_contribution_ust_heat (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Additional Inherited Members
Public Types inherited from oomph::SpaceTimeUnsteadyHeatEquationsBase
typedef void(* SpaceTimeUnsteadyHeatSourceFctPt) (const double &time, const Vector< double > &x, double &u)
typedef void(* SpaceTimeUnsteadyHeatSourceFctPt) (const double &time, const Vector< double > &x, double &u)
typedef void(* SpaceTimeUnsteadyHeatSourceFctPt) (const double &time, const Vector< double > &x, double &u)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions inherited from oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >
virtual void shape_ust_heat (const Vector< double > &s, Shape &psi) const =0
Shape functions w.r.t. to local coords.
virtual void dshape_local_ust_heat (const Vector< double > &s, Shape &psi, DShape &dpsidx) const =0
Shape functions & derivs. w.r.t. to local coords.
virtual void dtest_local_ust_heat (const Vector< double > &s, Shape &test, DShape &dtestdx) const =0
Test functions & derivs. w.r.t. to local coords.
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Protected Attributes inherited from oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >
SpaceTimeUnsteadyHeatSourceFctPt Source_fct_pt
Pointer to source function:
bool ALE_is_disabled
double * Alpha_pt
Pointer to Alpha parameter (thermal inertia)
double * Beta_pt
Pointer to Beta parameter (thermal conductivity)
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number – for plotting/validation purposes.
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Detailed Description
template<unsigned SPATIAL_DIM>
class oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >
Refineable version of Unsteady Heat equations.
Constructor & Destructor Documentation
RefineableSpaceTimeUnsteadyHeatMixedOrderEquations() [1/2]
template<unsigned SPATIAL_DIM> oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations () inline
Constructor.
       : SpaceTimeUnsteadyHeatMixedOrderEquations<SPATIAL_DIM>(),
         RefineableElement(),
         ElementWithZ2ErrorEstimator()
     {
     }
RefineableSpaceTimeUnsteadyHeatMixedOrderEquations() [2/2]
template<unsigned SPATIAL_DIM> oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations (const RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM > & dummy) delete
Broken copy constructor.
Member Function Documentation
fill_in_generic_residual_contribution_ust_heat()
template<unsigned SPATIAL_DIM> void oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) private virtual
Add element's contribution to elemental residual vector and/or Jacobian matrix flag=0: compute residual vector only flag=1: compute both
Add element's contribution to the elemental residual vector and/or Jacobian matrix. flag=0: compute residual vector only flag=1: compute both
Reimplemented from oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >.
   {
     // Find out how many nodes there are in the element
     unsigned n_node = nnode();
     // Find the index at which the unknown is stored
     unsigned u_nodal_index = this->u_index_ust_heat();
     // Set up memory for the shape functions
     Shape psi(n_node);
     // Set up memory for the test functions
     Shape test(n_node);
     // Allocate space for the derivatives of the shape functions
     DShape dpsidx(n_node, SPATIAL_DIM + 1);
     // Allocate space for the derivatives of the test functions
     DShape dtestdx(n_node, SPATIAL_DIM + 1);
     // Set the value of n_intpt
     unsigned n_intpt = integral_pt()->nweight();
     // Storage for the local coordinates
     Vector<double> s(SPATIAL_DIM + 1, 0.0);
     // Get the Alpha parameter
     double alpha_local = this->alpha();
     // Get the Beta parameter
     double beta_local = this->beta();
     // Integer to hold the local equation
     int local_eqn = 0;
     // Integer to hold the local unknowns
     int local_unknown = 0;
     // Local storage for pointer to hang info object
     HangInfo* hang_info_pt = 0;
     // Local storage for pointer to (another) hang info object
     HangInfo* hang_info2_pt = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < SPATIAL_DIM + 1; i++)
       {
         // Calculate the i-th local coordinate
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the shape and test functions
       double J = this->dshape_and_dtest_eulerian_at_knot_ust_heat(
         ipt, psi, dpsidx, test, dtestdx);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Storage for the interpolated time value
       double interpolated_t = 0.0;
       // Storage for the interpolated solution value
       double interpolated_u = 0.0;
       // Storage for the interpolated time-derivative of the solution
       double interpolated_dudt = 0.0;
       // Storage for the spatial coordinates
       Vector<double> interpolated_x(SPATIAL_DIM, 0.0);
       // Storage for the spatial derivatives of the solution
       Vector<double> interpolated_dudx(SPATIAL_DIM + 1, 0.0);
       // Storage for the mesh velocity
       Vector<double> mesh_velocity(SPATIAL_DIM, 0.0);
       //-------------------------------------------------
       // Calculate derivatives and source function value:
       //-------------------------------------------------
       // Loop over the nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Get the nodal value at the l-th node
         double u_value = nodal_value(l, u_nodal_index);
         // Update the interpolated u value
         interpolated_u += u_value * psi(l);
         // Loop over the coordinate directions (both spatial AND time)
         for (unsigned j = 0; j < SPATIAL_DIM; j++)
         {
           // Update the interpolated x value
           interpolated_x[j] += nodal_position(l, j) * psi(l);
           // Update the interpolated du/dx_j value
           interpolated_dudx[j] += u_value * dpsidx(l, j);
         }
         // Update the interpolated time value
         interpolated_t += nodal_position(l, SPATIAL_DIM) * psi(l);
         // Update the interpolated du/dt value
         interpolated_dudt += u_value * dpsidx(l, SPATIAL_DIM);
       } // for (unsigned l=0;l<n_node;l++)
       // If ALE is enabled
       if (!(this->ALE_is_disabled))
       {
         // Loop over the coordinate directions
         for (unsigned j = 0; j < SPATIAL_DIM; j++)
         {
           // Loop over the nodes
           for (unsigned l = 0; l < n_node; l++)
           {
             // Update the mesh velocity
             mesh_velocity[j] += nodal_position(l, j) * dpsidx(l, SPATIAL_DIM);
           }
         } // for (unsigned j=0;j<SPATIAL_DIM;j++)
       } // if (!ALE_is_disabled)
       // Initialise the source term value
       double source = 0.0;
       // Get the interpolated source term value
       this->get_source_ust_heat(interpolated_t, ipt, interpolated_x, source);
       //--------------------------------
       // Assemble residuals and Jacobian
       //--------------------------------
       // Loop over the nodes (or equivalently the test functions)
       for (unsigned l = 0; l < n_node; l++)
       {
         // Storage for the number of master nodes
         unsigned n_master = 1;
         // Storage for the hang weight associated with the shape function
         double hang_weight = 1.0;
         // Check if the node is hanging
         bool is_node_hanging = this->node_pt(l)->is_hanging();
         // If the node is hanging, get the number of master nodes
         if (is_node_hanging)
         {
           // Get the hang info pointer associated with the l-th node in the
           // element
           hang_info_pt = this->node_pt(l)->hanging_pt();
           // Get the number of master nodes associated with the node
           n_master = hang_info_pt->nmaster();
         }
         // If it's not hanging there is just one master node; the node itself
         else
         {
           // Set the number of master nodes to one
           n_master = 1;
         }
         // Loop over the number of master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // Check if the node is hanging
           if (is_node_hanging)
           {
             // Read out the local equation from the master node
             local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                              u_nodal_index);
             // Read out the weight from the master node
             hang_weight = hang_info_pt->master_weight(m);
           }
           // If the node is not hanging
           else
           {
             // The local equation number comes from the node itself
             local_eqn = this->nodal_local_eqn(l, u_nodal_index);
             // The hang weight is one
             hang_weight = 1.0;
           }
           // If the nodal equation is not a boundary condition
           if (local_eqn >= 0)
           {
             // Add source term and time derivative
             residuals[local_eqn] +=
               ((source + alpha_local * interpolated_dudt) * test(l) * W *
                hang_weight);
             // If ALE is enabled
             if (!(this->ALE_is_disabled))
             {
               // Loop over the coordinate directions
               for (unsigned k = 0; k < SPATIAL_DIM; k++)
               {
                 // Add in the mesh velocity contribution
                 residuals[local_eqn] -=
                   (alpha_local * mesh_velocity[k] * interpolated_dudx[k] *
                    test(l) * W * hang_weight);
               }
             } // if (!ALE_is_disabled)
             // Loop over the coordinate directions
             for (unsigned k = 0; k < SPATIAL_DIM; k++)
             {
               // Add in the contribution from the Laplace operator
               residuals[local_eqn] += (beta_local * interpolated_dudx[k] *
                                        dtestdx(l, k) * W * hang_weight);
             }
             //-----------------------
             // Calculate the Jacobian
             //-----------------------
             // If we also need to construct the Jacobian
             if (flag)
             {
               // Storage for the number of master nodes
               unsigned n_master2 = 1;
               // Storage for the hang weight associated with the shape function
               double hang_weight2 = 1.0;
               // Loop over the nodes for the variables
               for (unsigned l2 = 0; l2 < n_node; l2++)
               {
                 // Check if the node is hanging
                 bool is_node2_hanging = this->node_pt(l2)->is_hanging();
                 // If the node is hanging, get the number of master nodes
                 if (is_node2_hanging)
                 {
                   // Get the hang info pointer associated with the l2-th node
                   hang_info2_pt = this->node_pt(l2)->hanging_pt();
                   // Get the number of master nodes associated with the node
                   n_master2 = hang_info2_pt->nmaster();
                 }
                 // If it's not hanging there is just one master node; the node
                 // itself
                 else
                 {
                   // Set the number of master nodes to one
                   n_master2 = 1;
                 }
                 // Loop over the master nodes
                 for (unsigned m2 = 0; m2 < n_master2; m2++)
                 {
                   // Check if the node is hanging
                   if (is_node2_hanging)
                   {
                     // Read out the local equation from the master node
                     local_unknown = this->local_hang_eqn(
                       hang_info2_pt->master_node_pt(m2), u_nodal_index);
                     // Read out the weight from the master node
                     hang_weight2 = hang_info2_pt->master_weight(m2);
                   }
                   // If the node is not hanging
                   else
                   {
                     // The local equation number comes from the node itself
                     local_unknown = this->nodal_local_eqn(l2, u_nodal_index);
                     // The hang weight is one
                     hang_weight2 = 1.0;
                   }
                   // If the unknown is not pinned
                   if (local_unknown >= 0)
                   {
                     // Time-derivative contribution
                     jacobian(local_eqn, local_unknown) +=
                       (alpha_local * test(l) * dpsidx(l2, SPATIAL_DIM) * W *
                        hang_weight * hang_weight2);
                     // Laplace operator contribution
                     for (unsigned k = 0; k < SPATIAL_DIM; k++)
                     {
                       // Add the Laplacian contribution to the elemental
                       // Jacobian
                       jacobian(local_eqn, local_unknown) +=
                         (beta_local * dpsidx(l2, k) * dtestdx(l, k) * W *
                          hang_weight * hang_weight2);
                     }
                     // If ALE is enabled
                     if (!(this->ALE_is_disabled))
                     {
                       // Loop over the spatial coordinates
                       for (unsigned k = 0; k < SPATIAL_DIM; k++)
                       {
                         // Add the ALE contribution to the Jacobian
                         jacobian(local_eqn, local_unknown) -=
                           (alpha_local * mesh_velocity[k] * dpsidx(l2, k) *
                            test(l) * W * hang_weight * hang_weight2);
                       }
                     } // if (!(this->ALE_is_disabled))
                   } // if (local_unknown>=0)
                 } // for (unsigned m2=0;m2<n_master;m2++)
               } // for (unsigned l2=0;l2<n_node;l2++)
             } // if (flag)
           } // if (local_eqn>=0)
         } // for (unsigned m=0;m<n_master;m++)
       } // for (unsigned l=0;l<n_node;l++)
     } // for (unsigned ipt=0;ipt<n_intpt;ipt++)
   } // End of fill_in_generic_residual_contribution_ust_heat
References oomph::ALE_is_disabled, alpha, beta, i, J, j, k, m, m2(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), s, TestProblem::source(), Eigen::test, w, and oomph::QuadTreeNames::W.
further_build()
template<unsigned SPATIAL_DIM> void oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::further_build () inline virtual
Further build: Copy source function pointer from father element.
Reimplemented from oomph::RefineableElement.
     {
       // Get pointer to the father
       RefineableSpaceTimeUnsteadyHeatMixedOrderEquations<SPATIAL_DIM>*
         cast_father_element_pt = dynamic_cast<
           RefineableSpaceTimeUnsteadyHeatMixedOrderEquations<SPATIAL_DIM>*>(
           this->father_element_pt());
       // Get the source function from the parent and store it
       this->Source_fct_pt = cast_father_element_pt->source_fct_pt();
       // Set the ALE status from the father
       this->ALE_is_disabled = cast_father_element_pt->ALE_is_disabled;
     } // End of further_build
References oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::ALE_is_disabled, oomph::RefineableElement::father_element_pt(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::source_fct_pt(), and oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::Source_fct_pt.
get_interpolated_values() [1/2]
template<unsigned SPATIAL_DIM> void oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) inline virtual
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
     {
       // Set the size of the vector u
       values.resize(1);
       // Find the number of nodes
       unsigned n_node = nnode();
       // Find the nodal index at which the unknown is stored
       unsigned u_nodal_index = this->u_index_ust_heat();
       // Local shape function
       Shape psi(n_node);
       // Find values of shape function
       shape(s, psi);
       // Initialise the value of u
       values[0] = 0.0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_node; l++)
       {
         // Update the solution value
         values[0] += this->nodal_value(t, l, u_nodal_index) * psi[l];
       }
     } // End of get_interpolated_values
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::u_index_ust_heat().
get_interpolated_values() [2/2]
template<unsigned SPATIAL_DIM> void oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) inline virtual
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
     {
       // Set the size of the vector u
       values.resize(1);
       // Find the number of nodes
       unsigned n_node = nnode();
       // Find the nodal index at which the unknown is stored
       unsigned u_nodal_index = this->u_index_ust_heat();
       // Local shape function
       Shape psi(n_node);
       // Find values of shape function
       shape(s, psi);
       // Initialise the value of u
       values[0] = 0.0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_node; l++)
       {
         // Update the solution value
         values[0] += this->nodal_value(l, u_nodal_index) * psi[l];
       }
     } // End of get_interpolated_values
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::u_index_ust_heat().
get_Z2_flux()
template<unsigned SPATIAL_DIM> void oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) inline virtual
Get 'flux' for Z2 error recovery: Different to the get_flux function in the base class as we also have to include du/dt as we're doing temporal adaptivity too
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       // Find out how many nodes there are in the element
       unsigned n_node = nnode();
       // Find the index at which the variable is stored
       unsigned u_nodal_index = this->u_index_ust_heat();
       // Set up memory for the shape and test functions
       Shape psi(n_node);
       // Set up memory for the derivatives of the shape and test functions
       DShape dpsidx(n_node, SPATIAL_DIM + 1);
       // Call the derivatives of the shape and test functions
       dshape_eulerian(s, psi, dpsidx);
       // Loop over the entries of the flux vector
       for (unsigned j = 0; j < SPATIAL_DIM + 1; j++)
       {
         // Initialise j-th flux entry to zero
         flux[j] = 0.0;
       }
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over derivative directions
         for (unsigned j = 0; j < SPATIAL_DIM + 1; j++)
         {
           // Update the flux value
           flux[j] += this->nodal_value(l, u_nodal_index) * dpsidx(l, j);
         }
       } // for (unsigned l=0;l<n_node;l++)
     } // End of get_Z2_flux
References oomph::FiniteElement::dshape_eulerian(), ProblemParameters::flux(), j, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, and oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::u_index_ust_heat().
num_Z2_flux_terms()
template<unsigned SPATIAL_DIM> unsigned oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::num_Z2_flux_terms () inline virtual
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       // The flux terms are associated with spatial AND temporal derivatives
       return SPATIAL_DIM + 1;
     } // End of num_Z2_flux_terms
The documentation for this class was generated from the following files:
refineable_discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h
refineable_discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.cc