MercuryDPM: TwoParticleBagheriCollisionSelfTest.cpp File Reference
TwoParticleBagheriCollisionSelfTest.cpp File Reference
#include "Mercury2D.h"
#include "Walls/InfiniteWall.h"
#include "Species/Species.h"
#include "Species/HertzianViscoelasticMindlinLiquidBridgeBagheriSpecies.h"
Classes
class TwoParticleBagheriCollision
In this file two particles are symmetrically placed in a bi-axial box are allowed to jump around under gravity. It tests walls gravity and symmetry.
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     TwoParticleBagheriCollision twoParticleBagheriCollisionProblem;
     twoParticleBagheriCollisionProblem.setName("TwoParticleBagheriCollisionSelfTest");
     HertzianViscoelasticMindlinLiquidBridgeBagheriSpecies species;
     species.setDensity(2000);
     species.setDissipation(0.16);
     species.setSlidingDissipation(0.16);
     Mdouble particleElasticModulus = 5e6; // taking 100 times that of soft material
     Mdouble particlePoissonRatio = 0.35;
     Mdouble particleSlidingFrictionCoefficient = 0.50;
     //Mdouble particleRadius = 0.0011;
     Mdouble particleShearModulus = particleElasticModulus/ 2 /(1+particlePoissonRatio);
     Mdouble particleEffectiveShearModulus = particleShearModulus/(2-particlePoissonRatio);
     Mdouble particleEffectiveElasticModulus = particleElasticModulus/(1-particlePoissonRatio*particlePoissonRatio);
     species.setEffectiveElasticModulus(particleEffectiveElasticModulus/2);
     species.setEffectiveShearModulus(particleEffectiveShearModulus/2);
     species.setSlidingFrictionCoefficient(particleSlidingFrictionCoefficient);
     species.setLiquidBridgeVolume(3e-11);
     species.setContactAngle(0);
     species.setSurfaceTension(0.070);
     Mdouble radius = 0.0005;
     Mdouble rayleighTime = helpers::getRayleighTime(radius,species.getEffectiveShearModulus(), particlePoissonRatio,species.getDensity());
     twoParticleBagheriCollisionProblem.setTimeStep(rayleighTime*0.1);
     twoParticleBagheriCollisionProblem.speciesHandler.copyAndAddObject(species);
     twoParticleBagheriCollisionProblem.setTimeMax(0.25);
     twoParticleBagheriCollisionProblem.setSaveCount(twoParticleBagheriCollisionProblem.getTimeMax()/twoParticleBagheriCollisionProblem.getTimeStep());
     twoParticleBagheriCollisionProblem.fStatFile.setFileType(FileType::MULTIPLE_FILES_PADDED);
     twoParticleBagheriCollisionProblem.solve();
 }
References BaseHandler< T >::copyAndAddObject(), e(), DPMBase::fStatFile, ParticleSpecies::getDensity(), helpers::getRayleighTime(), DPMBase::getTimeMax(), DPMBase::getTimeStep(), MULTIPLE_FILES_PADDED, UniformPSDSelfTest::radius, ParticleSpecies::setDensity(), File::setFileType(), DPMBase::setName(), DPMBase::setSaveCount(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), DPMBase::solve(), and DPMBase::speciesHandler.