MercuryDPM: BaseObject Class Reference
BaseObject Class Reference abstract
It is an abstract base class due to the purely virtual functions declared below. Even if the function is purely virtual, it does not imply that it cannot have a definition. Abstract classes are useful to define a interface.
#include <BaseObject.h>
Public Member Functions
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void read (std::istream &is)=0
virtual void write (std::ostream &os) const =0
A purely virtual function which has an implementation which writes the name and the object id_ to the output stream.
virtual std::string getName () const =0
A purely virtual function.
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
unsigned int index_ = 0
location in BaseHandler::objects_
unsigned int id_ = 0
unique identifier within handler (remains constant even if particle is moved)
unsigned int groupId_ = 0
Identifier of a group within handler.
Friends
std::ostream & operator<< (std::ostream &os, const BaseObject &o)
A purely virtual method with an implementation which reads the index from the stream and assigns it to id_.
std::istream & operator>> (std::istream &is, BaseObject &o)
Operator overloading for reading the data from an input stream into the BAseObject "o"
Detailed Description
It is an abstract base class due to the purely virtual functions declared below. Even if the function is purely virtual, it does not imply that it cannot have a definition. Abstract classes are useful to define a interface.
Constructor & Destructor Documentation
BaseObject() [1/2]
BaseObject::BaseObject () default
Default constructor.
BaseObject() [2/2]
BaseObject::BaseObject (const BaseObject & p) default
Copy constructor, copies all the objects BaseObject contains.
~BaseObject()
virtual BaseObject::~BaseObject () virtual default
virtual destructor
Member Function Documentation
getGroupId()
unsigned BaseObject::getGroupId () const inline
See also
groupId_.
     { return groupId_; }
References groupId_.
Referenced by BaseWall::getInteractionWith(), and MeshTriangle::getInteractionWith().
getId()
unsigned int BaseObject::getId () const inline
Returns the unique identifier of any particular object.
Returns
id number of the current object
     { return id_; }
References id_.
Referenced by ConstantMassFlowMaserBoundary::addParticleToMaser(), SubcriticalMaserBoundary::addParticleToMaser(), MeshTriangle::checkInteractions(), DPMBase::computeInternalForce(), MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::copyFromInteraction(), copyPositionFrom(), PeriodicBoundaryHandler::findNewParticle(), Screw::getDistanceAndNormalLabCoordinates(), BaseInteraction::getEffectiveMass(), BaseInteraction::getEffectiveRadius(), BaseInteraction::getI(), BaseParticle::getInfo(), BaseInteraction::getP(), BaseInteraction::importI(), BaseInteraction::importP(), HGrid::insertParticleToHgrid(), TriangleMeshWall::moveVerticesToMatchVolume(), PeriodicBoundaryHandler::processLocalGhostParticles(), Domain::processReceivedBoundaryParticleData(), Domain::processReceivedInteractionData(), WallHandler::readAndAddObject(), CurvyChute::recreateBottom(), BaseInteraction::setI(), BaseParticle::setIndSpecies(), BaseWall::setIndSpecies(), BaseSpecies::setInteractionDistance(), BaseInteraction::setP(), SphericalIndenter::setupInitialConditions(), PeriodicBoundaryHandler::updateMaserParticle(), PeriodicBoundaryHandler::updateParticles(), Domain::updateParticles(), PeriodicBoundaryHandler::updateParticleStatus(), MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::write(), BaseInteraction::write(), Membrane::write(), MembraneDemo::write(), MembraneSelfTest::write(), BaseInteraction::writeInteraction(), BaseInteractable::~BaseInteractable(), BaseParticle::~BaseParticle(), and SuperQuadricParticle::~SuperQuadricParticle().
getIndex()
unsigned int BaseObject::getIndex () const inline
Returns the index of the object in the handler.
     { return index_; };
References index_.
Referenced by T_protectiveWall::actionsAfterTimeStep(), Chutebelt::actionsAfterTimeStep(), BoundariesSelfTest::actionsAfterTimeStep(), protectiveWall::actionsAfterTimeStep(), PossibleContactList::add_PossibleContact(), BaseWall::addParticlesAtWall(), DeletionBoundary::checkBoundaryAfterParticleMoved(), ScaleCoupling< M, O >::computeCouplingForce(), ChuteWithPeriodicInflow::computeInternalForces(), ScaleCoupling< M, O >::computeProjectionMatrix(), BaseInteraction::gatherContactStatistics(), AxisymmetricIntersectionOfWalls::getDistanceAndNormal(), HorizontalBaseScrew::getDistanceAndNormal(), ScrewsymmetricIntersectionOfWalls::getDistanceAndNormal(), RestrictedWall::getInteractionWith(), TriangleMeshWall::getInteractionWith(), ParticleSpecies::getMixedSpecies(), PossibleContact::getNext(), PossibleContact::getOtherParticle(), PossibleContact::getPrevious(), HGrid::insertParticleToHgrid(), PossibleContactList::remove_ParticlePosibleContacts(), ScaleCoupling< M, O >::CoupledParticle::removeCoupledElement(), BaseInteraction::removeFromHandler(), InteractionHandler::removeObjectKeepingPeriodics(), ScaleCoupling< M, O >::CoupledParticle::setCoupledElement(), ParticleSpecies::setDensity(), ParticleSpecies::setMaxInteractionDistance(), PossibleContact::setNextPosition(), PossibleContact::setPreviousPosition(), BaseInteractable::setSpecies(), SphericalIndenter::setupInitialConditions(), MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::write(), BaseInteraction::writeToFStat(), BaseWall::writeVTK(), and BaseInteractable::~BaseInteractable().
getName()
virtual std::string BaseObject::getName () const pure virtual
A purely virtual function.
Implemented in NonSphericalParticle, WearableTriangulatedWall, WearableTriangleMeshWall, VChute, TriangulatedWall, TriangleWall, TriangleMeshWall, SphericalWall, SineWall, RestrictedWall, ParabolaChute, NurbsWall, MeshTriangle, Membrane, LevelSetWall, IntersectionOfWalls, InfiniteWallWithHole, InfiniteWall, CylindricalWall, Combtooth, Coil, BasicUnionOfWalls, BasicIntersectionOfWalls, ArcWall, SuperQuadricParticle, SphericalParticle, ClumpParticle, BaseParticle, BaseInteraction, Domain, TimeSmoothedCG< Coordinates, BaseFunction, Fields >, TimeAveragedCG< Coordinates, BaseFunction, Fields >, TimeAveragedCG< CGCoordinates::XYZ, BaseFunction, CGFields::StandardFields >, CG< Coordinates, BaseFunction, Fields >, CG< Coordinates, CGFunctions::Lucy, CGFields::StandardFields >, CG< CGCoordinates::O, CGFunctions::Lucy, CGFields::StandardFields >, TimeDependentPeriodicBoundary, SubcriticalMaserBoundaryTEST, SubcriticalMaserBoundary, StressStrainControlBoundary, SphereInsertionBoundary, ShearBoxBoundary, RandomClusterInsertionBoundary, PolydisperseInsertionBoundary, PeriodicBoundary, LeesEdwardsBoundary, HopperInsertionBoundary, HeaterBoundary, FluxBoundary, FixedClusterInsertionBoundary, DropletBoundary, DeletionBoundary, CylinderInsertionBoundary, CubeInsertionBoundary, CubeDeletionBoundary, ConstantMassFlowMaserBoundary, CircularPeriodicBoundary, ChuteInsertionBoundary, BidisperseCubeInsertionBoundary, BaseClusterInsertionBoundary, AngledPeriodicBoundary, WearableNurbsWall, SimpleDrumSuperquadrics, ScrewsymmetricIntersectionOfWalls, Screw, HorizontalScrew, HorizontalBaseScrew, AxisymmetricIntersectionOfWalls, Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >, Species< LinearViscoelasticNormalSpecies >, Species< LinearViscoelasticNormalSpecies, FrictionSpecies >, Species< LinearPlasticViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, Species< LinearViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >, and Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >.
Referenced by commandLineCG(), write(), BaseCG::write(), and BaseWall::writeVTK().
moveInHandler()
void BaseObject::moveInHandler (unsigned int index) virtual
Except that it is virtual, it does the same thing as setIndex() does.
Parameters
[in] index
 {
     index_ = index;
 }
References index_.
read()
void BaseObject::read (std::istream & is) pure virtual
Parameters
[in]
Implemented in BaseBoundary, WearableTriangulatedWall, WearableTriangleMeshWall, WearableNurbsWall, VChute, TriangulatedWall, TriangleWall, TriangleMeshWall, SphericalWall, SineWall, Screw, RestrictedWall, ParabolaChute, NurbsWall, MeshTriangle, Membrane, LevelSetWall, IntersectionOfWalls, InfiniteWallWithHole, InfiniteWall, HorizontalScrew, CylindricalWall, Combtooth, Coil, BasicUnionOfWalls, BasicIntersectionOfWalls, BaseWall, ArcWall, ParticleSpecies, BaseSpecies, SuperQuadricParticle, ClumpParticle, BaseParticle, SPHInteraction, SinterLinInteraction, SinterInteraction, MeltableInteraction, LinearViscoelasticInteraction, LinearPlasticViscoelasticInteraction, HertzianViscoelasticInteraction, HertzianSinterInteraction, HertzianBSHPViscoelasticInteraction, SlidingFrictionInteraction, MindlinRollingTorsionInteraction, MindlinInteraction, FrictionInteraction, EmptyFrictionInteraction, BaseInteraction, SolidifyingLiquidMigrationWilletInteraction, ReversibleAdhesiveInteraction, RegimeSinterInteraction, ParhamiMcMeekingSinterInteraction, LiquidMigrationWilletInteraction, LiquidMigrationLSInteraction, LiquidBridgeWilletInteraction, LiquidBridgeClassicalWilletInteraction, LiquidBridgeBagheriInteraction, JKRAdhesiveInteraction, IrreversibleAdhesiveInteraction, EmptyAdhesiveInteraction, ChargedBondedInteraction, BondedInteraction, Domain, BaseCG, TimeDependentPeriodicBoundary, SubcriticalMaserBoundaryTEST, SubcriticalMaserBoundary, StressStrainControlBoundary, SphereInsertionBoundary, ShearBoxBoundary, PolydisperseInsertionBoundary, PeriodicBoundary, LeesEdwardsBoundary, InsertionBoundary, HopperInsertionBoundary, HeaterBoundary, FluxBoundary, DropletBoundary, DeletionBoundary, CylinderInsertionBoundary, CubeInsertionBoundary, CubeDeletionBoundary, ConstantMassFlowMaserBoundary, CircularPeriodicBoundary, ChuteInsertionBoundary, BidisperseCubeInsertionBoundary, BasePeriodicBoundary, BaseClusterInsertionBoundary, AngledPeriodicBoundary, BaseInteractable, SimpleDrumSuperquadrics, ScrewsymmetricIntersectionOfWalls, HorizontalBaseScrew, AxisymmetricIntersectionOfWalls, Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >, Species< LinearViscoelasticNormalSpecies >, Species< LinearViscoelasticNormalSpecies, FrictionSpecies >, Species< LinearPlasticViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, Species< LinearViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >, and Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >.
 {
     std::string dummy;
     is >> dummy >> id_;
     helpers::readOptionalVariable(is, "groupID", groupId_);
 }
References groupId_, id_, helpers::readOptionalVariable(), and oomph::Global_string_for_annotation::string().
Referenced by BaseInteractable::read(), ParticleSpecies::read(), and BaseBoundary::read().
setGroupId()
void BaseObject::setGroupId (unsigned groupId) inline
See also
groupId_.
     { groupId_ = groupId; }
References groupId_.
Referenced by SCoupling< M, O >::createTriangleWall(), WallHandler::readTriangleWall(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), and RollingOverTriangleWalls::setupInitialConditions().
setId()
void BaseObject::setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
Parameters
[in] id id number of the current object
Todo:
TW: here we should update BaseHandler::nextId_
 {
     id_ = id;
 }
References id_.
Referenced by ConstantMassFlowMaserBoundary::addParticleToMaser(), SubcriticalMaserBoundary::addParticleToMaser(), BaseParticle::oldRead(), MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::read(), WallHandler::readAndAddObject(), SphericalIndenter::setupInitialConditions(), and PeriodicBoundaryHandler::updateMaserParticle().
setIndex()
void BaseObject::setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
Parameters
[in] index index number of the current object
 {
     index_ = index;
 }
References index_.
Referenced by ConstantMassFlowMaserBoundary::addParticleToMaser(), SubcriticalMaserBoundary::addParticleToMaser(), RestrictedWall::getInteractionWith(), BaseParticle::oldRead(), MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::read(), and SphericalIndenter::setupInitialConditions().
write()
void BaseObject::write (std::ostream & os) const pure virtual
A purely virtual function which has an implementation which writes the name and the object id_ to the output stream.
Parameters
[in] os stream object to which data is written
Implemented in BaseBoundary, WearableTriangulatedWall, WearableTriangleMeshWall, WearableNurbsWall, VChute, TriangulatedWall, TriangleWall, TriangleMeshWall, SphericalWall, SineWall, Screw, RestrictedWall, ParabolaChute, NurbsWall, MeshTriangle, Membrane, IntersectionOfWalls, InfiniteWallWithHole, HorizontalScrew, CylindricalWall, Combtooth, Coil, BasicUnionOfWalls, BasicIntersectionOfWalls, BaseWall, ArcWall, ParticleSpecies, BaseSpecies, SuperQuadricParticle, ClumpParticle, BaseParticle, SPHInteraction, SinterLinInteraction, SinterInteraction, MeltableInteraction, LinearViscoelasticInteraction, LinearPlasticViscoelasticInteraction, HertzianViscoelasticInteraction, HertzianSinterInteraction, HertzianBSHPViscoelasticInteraction, SlidingFrictionInteraction, MindlinRollingTorsionInteraction, MindlinInteraction, FrictionInteraction, EmptyFrictionInteraction, BaseInteraction, SolidifyingLiquidMigrationWilletInteraction, ReversibleAdhesiveInteraction, RegimeSinterInteraction, ParhamiMcMeekingSinterInteraction, LiquidMigrationWilletInteraction, LiquidMigrationLSInteraction, LiquidBridgeWilletInteraction, LiquidBridgeClassicalWilletInteraction, LiquidBridgeBagheriInteraction, JKRAdhesiveInteraction, IrreversibleAdhesiveInteraction, EmptyAdhesiveInteraction, ChargedBondedInteraction, BondedInteraction, Domain, TimeSmoothedCG< Coordinates, BaseFunction, Fields >, TimeAveragedCG< Coordinates, BaseFunction, Fields >, TimeAveragedCG< CGCoordinates::XYZ, BaseFunction, CGFields::StandardFields >, CG< Coordinates, BaseFunction, Fields >, CG< Coordinates, CGFunctions::Lucy, CGFields::StandardFields >, CG< CGCoordinates::O, CGFunctions::Lucy, CGFields::StandardFields >, BaseCG, TimeDependentPeriodicBoundary, SubcriticalMaserBoundaryTEST, SubcriticalMaserBoundary, StressStrainControlBoundary, SphereInsertionBoundary, ShearBoxBoundary, PolydisperseInsertionBoundary, PeriodicBoundary, LeesEdwardsBoundary, InsertionBoundary, HopperInsertionBoundary, HeaterBoundary, FluxBoundary, DropletBoundary, DeletionBoundary, CylinderInsertionBoundary, CubeInsertionBoundary, CubeDeletionBoundary, ConstantMassFlowMaserBoundary, CircularPeriodicBoundary, ChuteInsertionBoundary, BidisperseCubeInsertionBoundary, BasePeriodicBoundary, BaseClusterInsertionBoundary, AngledPeriodicBoundary, BaseInteractable, SimpleDrumSuperquadrics, ScrewsymmetricIntersectionOfWalls, HorizontalBaseScrew, AxisymmetricIntersectionOfWalls, Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >, Species< LinearViscoelasticNormalSpecies >, Species< LinearViscoelasticNormalSpecies, FrictionSpecies >, Species< LinearPlasticViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, Species< LinearViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >, and Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >.
 {
     os << getName();
     os << " id " << id_;
     if (groupId_) os << " groupID " << groupId_;
 }
References getName(), groupId_, and id_.
Referenced by BaseInteractable::write(), ParticleSpecies::write(), and BaseBoundary::write().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const BaseObject & o) friend
A purely virtual method with an implementation which reads the index from the stream and assigns it to id_.
Parameters
[in] is
[in,out] os
[in] o
Returns
std::ostream &
 {
     o.write(os);
     return os;
 }
operator>>
std::istream& operator>> (std::istream & is, BaseObject & o) friend
Operator overloading for reading the data from an input stream into the BAseObject "o"
Parameters
[in] o
[in,out] is
Returns
std::istream&
 {
     o.read(is);
     return (is);
 }
Member Data Documentation
groupId_
unsigned int BaseObject::groupId_ = 0 private
Identifier of a group within handler.
Useful to define properties to particle or wall clusters, etc. E.g. one can apply an action to a specific group, visualise a specific group, coarse-grain a specific group, etc.
See also
BaseHandler::nextGroupId_
Referenced by getGroupId(), read(), setGroupId(), and write().
id_
unsigned int BaseObject::id_ = 0 private
unique identifier within handler (remains constant even if particle is moved)
Referenced by getId(), read(), setId(), and write().
index_
unsigned int BaseObject::index_ = 0 private
location in BaseHandler::objects_
Referenced by getIndex(), moveInHandler(), and setIndex().
The documentation for this class was generated from the following files:
BaseObject.h
BaseObject.cc