MercuryDPM: forward_adolc.cpp File Reference
forward_adolc.cpp File Reference
#include "main.h"
#include <Eigen/Dense>
#include <unsupported/Eigen/AdolcForward>
Classes
struct TestFunc1< Scalar_, NX, NY >
Macros
#define NUMBER_DIRECTIONS 16
Functions
template<typename Vector >
EIGEN_DONT_INLINE Vector::Scalar foo (const Vector &p)
template<typename Func >
void adolc_forward_jacobian (const Func &f)
EIGEN_DECLARE_TEST (forward_adolc)
Macro Definition Documentation
NUMBER_DIRECTIONS
#define NUMBER_DIRECTIONS 16
Function Documentation
adolc_forward_jacobian()
template<typename Func > void adolc_forward_jacobian (const Func & f)
{
   typename Func::InputType x = Func::InputType::Random(f.inputs());
   typename Func::ValueType y(f.values()), yref(f.values());
   typename Func::JacobianType j(f.values(), f.inputs()), jref(f.values(), f.inputs());
   jref.setZero();
   yref.setZero();
   f(x, &yref, &jref);
   //     std::cerr << y.transpose() << "\n\n";;
   //     std::cerr << j << "\n\n";;
   j.setZero();
   y.setZero();
   AdolcForwardJacobian<Func> autoj(f);
   autoj(x, &y, &j);
   //     std::cerr << y.transpose() << "\n\n";;
   //     std::cerr << j << "\n\n";;
   VERIFY_IS_APPROX(y, yref);
   VERIFY_IS_APPROX(j, jref);
 }
References f(), j, VERIFY_IS_APPROX, plotDoE::x, and y.
Referenced by EIGEN_DECLARE_TEST().
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (forward_adolc)
{
   adtl::setNumDir(NUMBER_DIRECTIONS);
   for (int i = 0; i < g_repeat; i++) {
     CALL_SUBTEST((adolc_forward_jacobian(TestFunc1<double, 2, 2>())));
     CALL_SUBTEST((adolc_forward_jacobian(TestFunc1<double, 2, 3>())));
     CALL_SUBTEST((adolc_forward_jacobian(TestFunc1<double, 3, 2>())));
     CALL_SUBTEST((adolc_forward_jacobian(TestFunc1<double, 3, 3>())));
     CALL_SUBTEST((adolc_forward_jacobian(TestFunc1<double>(3, 3))));
   }
   {
     // simple instantiation tests
     Matrix<adtl::adouble, 2, 1> x;
     foo(x);
     Matrix<adtl::adouble, Dynamic, Dynamic> A(4, 4);
     ;
     A.selfadjointView<Lower>().eigenvalues();
   }
 }
References adolc_forward_jacobian(), CALL_SUBTEST, foo(), Eigen::g_repeat, i, Eigen::Lower, NUMBER_DIRECTIONS, and plotDoE::x.
foo()
template<typename Vector > EIGEN_DONT_INLINE Vector::Scalar foo (const Vector & p)
{
   typedef typename Vector::Scalar Scalar;
   return (p - Vector(Scalar(-1), Scalar(1.))).norm() + (p.array().sqrt().abs() * p.array().sin()).sum() + p.dot(p);
 }
References p.
Referenced by EIGEN_DECLARE_TEST().