MercuryDPM: oomph::GmshTetScaffoldMesh Class Reference
oomph::GmshTetScaffoldMesh Class Reference
#include <gmsh_tet_mesh.template.h>
Public Member Functions
GmshTetScaffoldMesh (GmshParameters *gmsh_parameters_pt, const bool &use_mesh_grading_from_file)
Public Member Functions inherited from oomph::TetMeshBase
TetMeshBase ()
Constructor.
TetMeshBase (const TetMeshBase &node)=delete
Broken copy constructor.
void operator= (const TetMeshBase &)=delete
Broken assignment operator.
virtual ~TetMeshBase ()
Destructor (empty)
void assess_mesh_quality (std::ofstream &some_file)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, const bool &switch_normal)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, const bool &switch_normal, std::ofstream &outfile)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, std::ofstream &outfile)
unsigned nboundary_element_in_region (const unsigned &b, const unsigned &r) const
Return the number of elements adjacent to boundary b in region r.
FiniteElement * boundary_element_in_region_pt (const unsigned &b, const unsigned &r, const unsigned &e) const
Return pointer to the e-th element adjacent to boundary b in region r.
int face_index_at_boundary_in_region (const unsigned &b, const unsigned &r, const unsigned &e) const
Return face index of the e-th element adjacent to boundary b in region r.
unsigned nregion ()
Return the number of regions specified by attributes.
unsigned nregion_element (const unsigned &r)
Return the number of elements in region r.
double region_attribute (const unsigned &i)
FiniteElement * region_element_pt (const unsigned &r, const unsigned &e)
Return the e-th element in the r-th region.
template<class ELEMENT >
void snap_to_quadratic_surface (const Vector< unsigned > &boundary_id, const std::string &quadratic_surface_file_name, const bool &switch_normal, DocInfo &doc_info)
template<class ELEMENT >
void snap_to_quadratic_surface (const Vector< unsigned > &boundary_id, const std::string &quadratic_surface_file_name, const bool &switch_normal)
void snap_nodes_onto_geometric_objects ()
template<class ELEMENT >
void split_elements_in_corners (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Private Member Functions
void create_mesh_from_msh_file ()
Create mesh from msh file (created internally via disk-based operations)
void write_geo_file (const bool &use_mesh_grading_from_file)
Write geo file for gmsh.
Private Attributes
GmshParameters * Gmsh_parameters_pt
Parameters.
Friends
template<class ELEMENT >
class GmshTetMesh
We're friends with the actual mesh.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::TetMeshBase
static double Tolerance_for_boundary_finding = 1.0e-5
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes inherited from oomph::TetMeshBase
Vector< Vector< FiniteElement * > > Region_element_pt
Vector< double > Region_attribute
Vector< std::map< unsigned, Vector< FiniteElement * > > > Boundary_region_element_pt
Storage for elements adjacent to a boundary in a particular region.
Vector< std::map< unsigned, Vector< int > > > Face_index_region_at_boundary
TetMeshFacetedClosedSurface * Outer_boundary_pt
Faceted surface that defines outer boundaries.
Vector< TetMeshFacetedSurface * > Internal_surface_pt
Vector to faceted surfaces that define internal boundaries.
std::map< unsigned, TetMeshFacetedSurface * > Tet_mesh_faceted_surface_pt
std::map< unsigned, TetMeshFacet * > Tet_mesh_facet_pt
std::map< unsigned, Vector< Vector< double > > > Triangular_facet_vertex_boundary_coordinate
TimeStepper * Time_stepper_pt
Timestepper used to build nodes.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Constructor & Destructor Documentation
GmshTetScaffoldMesh()
oomph::GmshTetScaffoldMesh::GmshTetScaffoldMesh (GmshParameters * gmsh_parameters_pt, const bool & use_mesh_grading_from_file) inline
Build mesh, based on specified parameters. If boolean is set to true, the target element sizes are read from file (used during adaptation; otherwise uniform target size is used).
       : Gmsh_parameters_pt(gmsh_parameters_pt)
     {
       double t_start = TimingHelpers::timer();
       // Create .geo file
       write_geo_file(use_mesh_grading_from_file);
       oomph_info << "Time for writing geo file           : "
                  << TimingHelpers::timer() - t_start << " sec " << std::endl;
       t_start = TimingHelpers::timer();
       // Execute gmsh on command line
       std::string gmsh_command_line_string = "";
       std::string gmsh_onscreen_output_file_name =
         gmsh_parameters_pt->gmsh_onscreen_output_file_name();
       std::ofstream gmsh_on_screen_output_file;
       std::stringstream marker;
       if (gmsh_onscreen_output_file_name != "")
       {
         marker << "\n\n====================================================\n"
                << "          gmsh invocation: "
                << gmsh_parameters_pt->gmsh_onscreen_output_counter()
                << std::endl
                << "====================================================\n\n\n"
                << std::endl;
         gmsh_parameters_pt->gmsh_onscreen_output_counter()++;
         oomph_info << marker.str();
         gmsh_on_screen_output_file.open(gmsh_onscreen_output_file_name.c_str(),
                                         std::ofstream::app);
         gmsh_on_screen_output_file << marker.str();
         gmsh_on_screen_output_file.close();
       }
       gmsh_command_line_string +=
         Gmsh_parameters_pt->gmsh_command_line_invocation() + " " +
         Gmsh_parameters_pt->geo_and_msh_file_stem() + ".geo -3";
       if (gmsh_onscreen_output_file_name != "")
       {
         gmsh_command_line_string += " >> " + gmsh_onscreen_output_file_name;
       }
       // Note return flag isn't particularly well defined but we report it
       // anyway to aid detection of problems...
       int return_flag = system(gmsh_command_line_string.c_str());
       oomph_info << "fyi: return from system command: " << return_flag
                  << std::endl;
       oomph_info << "Time for gmsh system call           : "
                  << TimingHelpers::timer() - t_start << " sec " << std::endl;
       t_start = TimingHelpers::timer();
       // Create the mesh
       create_mesh_from_msh_file();
       oomph_info << "Time for creating mesh from msh file: "
                  << TimingHelpers::timer() - t_start << " sec " << std::endl;
     }
References create_mesh_from_msh_file(), oomph::GmshParameters::geo_and_msh_file_stem(), oomph::GmshParameters::gmsh_command_line_invocation(), oomph::GmshParameters::gmsh_onscreen_output_counter(), oomph::GmshParameters::gmsh_onscreen_output_file_name(), Gmsh_parameters_pt, oomph::oomph_info, oomph::Global_string_for_annotation::string(), oomph::TimingHelpers::timer(), and write_geo_file().
Member Function Documentation
create_mesh_from_msh_file()
void oomph::GmshTetScaffoldMesh::create_mesh_from_msh_file () inline private
Create mesh from msh file (created internally via disk-based operations)
     {
       // Create filename from stem
       std::string mesh_file_name =
         Gmsh_parameters_pt->geo_and_msh_file_stem() + ".msh";
       // Keep around if we ever write a version where name is passed in.
       /*    // Check extension */
       /* #ifdef PARANOID */
       /*    std::string mesh_file_stem= */
       /*     mesh_file_name.substr(0,mesh_file_name.length()-4); */
       /*    std::string test=mesh_file_stem+".msh"; */
       /*    if (test!=mesh_file_name) */
       /*     { */
       /*      std::string error_msg("msh file has wrong extension: "); */
       /*      error_msg += " " + mesh_file_name; */
       /*      throw OomphLibError(error_msg,  */
       /*                          OOMPH_CURRENT_FUNCTION, */
       /*                          OOMPH_EXCEPTION_LOCATION); */
       /*     } */
       /* #endif */
       // Open wide...
       std::ifstream mesh_file(mesh_file_name.c_str(), std::ios_base::in);
 // Check that the file actually opened correctly
 #ifdef PARANOID
       if (!mesh_file.is_open())
       {
         std::string error_msg("Failed to open mesh file: ");
         error_msg += "\"" + mesh_file_name + "\".";
         throw OomphLibError(
           error_msg, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // First line: Must be "$MeshFormat"
       //----------------------------------
       std::string line;
       mesh_file >> line;
       if (line != "$MeshFormat")
       {
         std::string error_msg(
           "First line has to contain the string \"$MeshFormat\"; ");
         error_msg += " yours contains: " + line;
         throw OomphLibError(
           error_msg, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
       // Rest of line
       mesh_file >> line;
       // Nodes
       //------
       // Now keep reading until we find the nodes
       bool keep_going = true;
       while (keep_going)
       {
         std::string line;
         mesh_file >> line;
         if (line == "$Nodes")
         {
           keep_going = false;
         }
       }
       unsigned nnod = 0;
       mesh_file >> nnod;
       std::map<unsigned, Vector<double>> node_coordinate;
       for (unsigned j = 0; j < nnod; j++)
       {
         unsigned node_number = 0;
         mesh_file >> node_number;
         // Read rest of line word by word
         std::string s;
         std::getline(mesh_file, s);
         std::istringstream iss(s);
         std::string sub;
         while (iss >> sub)
         {
           node_coordinate[node_number].push_back(atof(sub.c_str()));
         }
       }
       mesh_file >> line;
       if (line != "$EndNodes")
       {
         std::string error_msg("Line has to contain the string \"$EndNodes\"; ");
         error_msg += " yours contains: " + line;
         throw OomphLibError(
           error_msg, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
       // Rewind
       mesh_file.clear();
       mesh_file.seekg(0);
       mesh_file >> line;
       if (line != "$MeshFormat")
       {
         std::string error_msg(
           "First line has to contain the string \"$MeshFormat\"; ");
         error_msg += " yours contains: " + line;
         throw OomphLibError(
           error_msg, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
       // Rest of line
       mesh_file >> line;
       // Storage for boundaries the nodes are on
       std::map<unsigned, std::set<unsigned>> one_based_boundaries_of_node;
       // Elements
       //---------
       // node number = boundary_node[one_based_bound_id][...]
       std::map<unsigned, std::set<unsigned>> boundary_node;
       // element number = region_element[one_based_region_id][...]
       std::map<unsigned, std::set<unsigned>> region_element;
       // Now keep reading until we find the nodes
       keep_going = true;
       while (keep_going)
       {
         std::string line;
         mesh_file >> line;
         if (line == "$Elements")
         {
           keep_going = false;
         }
       }
       unsigned highest_one_based_boundary_id = 0;
       unsigned n_tet_el = 0;
       unsigned nel = 0;
       mesh_file >> nel;
       std::map<unsigned, Vector<unsigned>> element_node_index;
       for (unsigned e = 0; e < nel; e++)
       {
         // For each element the msh file provides:
         //
         // elm-number elm-type number-of-tags < tag > ... node-number-list
         //
         // By default, the first tag is the number of the physical entity to
         // which the element belongs; the second is the number of the elementary
         // geometrical entity to which the element belongs; the third is the
         // number of mesh partitions to which the element belongs, followed by
         // the partition ids (negative partition ids indicate ghost cells). A
         // zero tag is equivalent to no tag. Gmsh and most codes using the MSH 2
         // format require at least the first two tags (physical and elementary
         // tags).
         unsigned el_number = 0;
         mesh_file >> el_number;
         unsigned el_type = 0;
         mesh_file >> el_type;
         switch (el_type)
         {
           case 1:
             // oomph_info << "Line element" << std::endl;
             break;
           case 2:
             // oomph_info << "Triangle" << std::endl;
             break;
           case 4:
             n_tet_el++;
             // oomph_info << "Tet" << std::endl;
             break;
           case 15:
             // oomph_info << "Point" << std::endl;
             break;
           default:
             std::string error_msg("Can't handle element type: ");
             error_msg += oomph::StringConversion::to_string(el_type);
             throw OomphLibError(
               error_msg, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
         }
         unsigned ntags;
         mesh_file >> ntags;
         // Gmesh produces at least two flags:
         // Physical tag =  what we use as boundary or region IDs.
         int physical_tag = 0;
         mesh_file >> physical_tag;
         // Geometric tag; not something we use
         int geom_tag = 0;
         mesh_file >> geom_tag;
         Vector<int> other_tags;
         for (unsigned i = 2; i < ntags; i++)
         {
           int tag = 0;
           mesh_file >> tag;
           other_tags.push_back(tag);
         }
         // Now read the rest: node numbers
         // https://stackoverflow.com/questions/16991002/getting-a-line-from-a-file-and-then-reading-word-by-word-c
         std::string s;
         std::getline(mesh_file, s);
         std::istringstream iss(s);
         std::string sub;
         Vector<int> other_ints;
         while (iss >> sub)
         {
           other_ints.push_back(atoi(sub.c_str()));
         }
         unsigned n_el_nod = other_ints.size();
         for (unsigned j = 0; j < n_el_nod; j++)
         {
           unsigned node_number = unsigned(other_ints[j]);
           element_node_index[el_number].push_back(node_number);
           // If the element is a triangle, add node to boundary
           // lookup scheme (if tag is not zero, i.e. hasn't been specified)
           if (el_type == 2)
           {
             if (physical_tag != 0)
             {
               boundary_node[unsigned(physical_tag)].insert(node_number);
               one_based_boundaries_of_node[node_number].insert(
                 unsigned(physical_tag));
               if (unsigned(physical_tag) > highest_one_based_boundary_id)
               {
                 highest_one_based_boundary_id = physical_tag;
               }
             }
           }
         }
         // If it's a bulk element (tet) and the physical tag (region id)
         // is not equal to 0 add it to region list
         if (el_type == 4)
         {
           if (physical_tag != 0)
           {
             region_element[unsigned(physical_tag)].insert(n_tet_el);
           }
         }
       }
       mesh_file >> line;
       if (line != "$EndElements")
       {
         std::string error_msg(
           "Line has to contain the string \"$EndElements\"; ");
         error_msg += " yours contains: " + line;
         throw OomphLibError(
           error_msg, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
       // Rewind
       mesh_file.clear();
       mesh_file.seekg(0);
       mesh_file >> line;
       if (line != "$MeshFormat")
       {
         std::string error_msg(
           "First line has to contain the string \"$MeshFormat\"; ");
         error_msg += " yours contains: " + line;
         throw OomphLibError(
           error_msg, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
       // Rest of line
       mesh_file >> line;
       mesh_file.close();
       // Identify elements next to boundaries
       //-------------------------------------
       // Now loop over tet elements and check if three their nodes are
       // on given boundary
       std::map<unsigned, std::set<unsigned>> element_next_to_boundary;
       for (std::map<unsigned, Vector<unsigned>>::iterator it =
              element_node_index.begin();
            it != element_node_index.end();
            it++)
       {
         unsigned el_number = (*it).first;
         unsigned nnod = ((*it).second).size();
         if (nnod == 4)
         {
           std::map<unsigned, unsigned> boundary_node_count;
           for (unsigned j = 0; j < nnod; j++)
           {
             unsigned node_number = ((*it).second)[j];
             std::map<unsigned, std::set<unsigned>>::iterator itt =
               one_based_boundaries_of_node.find(node_number);
             if (itt != one_based_boundaries_of_node.end())
             {
               for (std::set<unsigned>::iterator ittt = (itt->second).begin();
                    ittt != (itt->second).end();
                    ittt++)
               {
                 unsigned one_based_boundary_id = (*ittt);
                 boundary_node_count[one_based_boundary_id]++;
               }
             }
           }
           for (std::map<unsigned, unsigned>::iterator itt =
                  boundary_node_count.begin();
                itt != boundary_node_count.end();
                itt++)
           {
             if ((*itt).second == 3)
             {
               element_next_to_boundary[(*itt).first].insert(el_number);
             }
           }
         }
       }
       this->set_nboundary(highest_one_based_boundary_id);
       // Done reading/processing; now move across
       // ----------------------------------------
       // Translate enumeration
       Vector<unsigned> oomph_lib_node_number(4);
       oomph_lib_node_number[0] = 0;
       oomph_lib_node_number[1] = 3;
       oomph_lib_node_number[2] = 2;
       oomph_lib_node_number[3] = 1;
       // make space to accomodate all this in the actual mesh
       Element_pt.resize(n_tet_el);
       Node_pt.resize(nnod);
       // Existing nodes
       Vector<Node*> existing_node_pt(nnod, 0);
       // Now process the simplex tets only (they have four nodes!)
       unsigned e = 0;
       for (std::map<unsigned, Vector<unsigned>>::iterator it =
              element_node_index.begin();
            it != element_node_index.end();
            it++)
       {
         unsigned el_nnod = (*it).second.size();
         if (el_nnod == 4)
         {
           // Here comes the new element
           TElement<3, 2>* el_pt = new TElement<3, 2>;
           // Store it
           Element_pt[e] = el_pt;
           e++;
           // Make/get nodes
           for (unsigned j = 0; j < el_nnod; j++)
           {
             // Get global, one-based node number
             unsigned node_number = (*it).second[j];
             // Does it already exist?
             if (existing_node_pt[node_number - 1] != 0)
             {
               el_pt->node_pt(oomph_lib_node_number[j]) =
                 existing_node_pt[node_number - 1];
             }
             // Make new node
             else
             {
               Node* nod_pt = 0;
               // Is it on the boundary?
               if (one_based_boundaries_of_node[node_number].size() == 0)
               {
                 // Make normal node
                 nod_pt = el_pt->construct_node(oomph_lib_node_number[j]);
                 Node_pt[node_number - 1] = nod_pt;
                 existing_node_pt[node_number - 1] = nod_pt;
               }
               // Make boundary node
               else
               {
                 nod_pt =
                   el_pt->construct_boundary_node(oomph_lib_node_number[j]);
                 Node_pt[node_number - 1] = nod_pt;
                 existing_node_pt[node_number - 1] = nod_pt;
                 // Add to boundary lookup scheme
                 for (std::set<unsigned>::iterator it =
                        one_based_boundaries_of_node[node_number].begin();
                      it != one_based_boundaries_of_node[node_number].end();
                      it++)
                 {
                   add_boundary_node((*it) - 1, nod_pt);
                 }
               }
               // Assign coordinates of new node
               Vector<double> x(node_coordinate[node_number]);
               for (unsigned i = 0; i < 3; i++)
               {
                 nod_pt->x(i) = x[i];
               }
             }
           }
         } // end for tet element
       } // End of loop over all elements
       // Setup region info. This is ugly because we're using
       // a lookup scheme that was originally designed for tetgen...
       unsigned n_region = region_element.size();
       this->Region_element_pt.resize(n_region);
       this->Region_attribute.resize(n_region);
       unsigned region_count = 0;
       for (std::map<unsigned, std::set<unsigned>>::iterator it =
              region_element.begin();
            it != region_element.end();
            it++)
       {
         this->Region_element_pt[region_count].resize((*it).second.size());
         unsigned one_based_region_id = (*it).first;
         this->Region_attribute[region_count] = one_based_region_id - 1;
         unsigned count = 0;
         for (std::set<unsigned>::iterator itt = (*it).second.begin();
              itt != (*it).second.end();
              itt++)
         {
           unsigned one_based_el_number = (*itt);
           this->Region_element_pt[region_count][count] =
             dynamic_cast<FiniteElement*>(Element_pt[one_based_el_number - 1]);
           count++;
         }
         region_count++;
       }
       // Keep alive for debugging
       bool plot_for_debugging = false;
       if (plot_for_debugging)
       {
         std::ofstream outfile;
         std::string outfile_name;
         std::string mesh_file_stem = "shite";
         // Output element nodes
         //----------------------
         outfile_name = mesh_file_stem + "_element_nodes.dat";
         outfile.open(outfile_name.c_str());
         for (std::map<unsigned, Vector<unsigned>>::iterator it =
                element_node_index.begin();
              it != element_node_index.end();
              it++)
         {
           std::set<unsigned> shite_nodes;
           unsigned el_id = (*it).first;
           std::stringstream tmp_out;
           for (Vector<unsigned>::iterator itt = (*it).second.begin();
                itt != (*it).second.end();
                itt++)
           {
             unsigned node_number = (*itt);
             shite_nodes.insert(node_number);
             Vector<double> x(node_coordinate[node_number]);
             unsigned n = x.size();
             for (unsigned i = 0; i < n; i++)
             {
               tmp_out << x[i] << " ";
             }
             tmp_out << node_number << std::endl;
           }
           std::string prefix = ", N=4, E=1, F=FEPOINT, ET=TETRAHEDRON";
           std::string postfix = "1 2 3 4";
           if ((*it).second.size() == 3)
           {
             prefix = ", N=3, E=1, F=FEPOINT, ET=TRIANGLE";
             postfix = "1 2 3";
           }
           outfile << "ZONE T=\"one-based element id=" << el_id << "\"" << prefix
                   << std::endl;
           outfile << tmp_out.str();
           outfile << postfix << std::endl;
         }
         outfile.close();
         // Output boundary nodes
         //----------------------
         outfile_name = mesh_file_stem + "_boundary_nodes.dat";
         outfile.open(outfile_name.c_str());
         for (std::map<unsigned, std::set<unsigned>>::iterator it =
                boundary_node.begin();
              it != boundary_node.end();
              it++)
         {
           unsigned one_based_boundary_id = (*it).first;
           outfile << "ZONE T=\"one-based boundary id=" << one_based_boundary_id
                   << "\"" << std::endl;
           for (std::set<unsigned>::iterator itt = (*it).second.begin();
                itt != (*it).second.end();
                itt++)
           {
             unsigned node_number = (*itt);
             Vector<double> x(node_coordinate[node_number]);
             unsigned n = x.size();
             for (unsigned i = 0; i < n; i++)
             {
               outfile << x[i] << " ";
             }
             outfile << node_number << std::endl;
           }
         }
         outfile.close();
         // Output elements next to boundaries
         //-----------------------------------
         for (std::map<unsigned, std::set<unsigned>>::iterator it =
                element_next_to_boundary.begin();
              it != element_next_to_boundary.end();
              it++)
         {
           unsigned one_based_boundary_id = (*it).first;
           outfile_name =
             mesh_file_stem + "_elements_next_to_boundary_" +
             oomph::StringConversion::to_string(one_based_boundary_id) + ".dat";
           outfile.open(outfile_name.c_str());
           for (std::set<unsigned>::iterator itt = (*it).second.begin();
                itt != (*it).second.end();
                itt++)
           {
             outfile << "ZONE T=\"one-based boundary " << one_based_boundary_id
                     << "\", N=4, E=1, F=FEPOINT, ET=TETRAHEDRON" << std::endl;
             unsigned el_number = (*itt);
             unsigned nnod = element_node_index[el_number].size();
             for (unsigned j = 0; j < nnod; j++)
             {
               unsigned node_number = element_node_index[el_number][j];
               Vector<double> x(node_coordinate[node_number]);
               unsigned n = x.size();
               for (unsigned i = 0; i < n; i++)
               {
                 outfile << x[i] << " ";
               }
               outfile << std::endl;
             }
             outfile << "1 2 3 4" << std::endl;
           }
           outfile.close();
         }
         // Compute/report total volume for sanity check
         {
           double vol = 0.0;
           unsigned nel = this->nelement();
           for (unsigned e = 0; e < nel; e++)
           {
             vol += this->finite_element_pt(e)->size();
           }
           oomph_info << "Total volume of all elements in scaffold mesh: " << vol
                      << std::endl;
         }
       }
     }
References oomph::Mesh::add_boundary_node(), e(), oomph::Mesh::Element_pt, Eigen::placeholders::end, oomph::Mesh::finite_element_pt(), oomph::GmshParameters::geo_and_msh_file_stem(), Gmsh_parameters_pt, i, j, calibrate::line, n, oomph::Mesh::nelement(), oomph::Mesh::Node_pt, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, oomph::TetMeshBase::Region_attribute, oomph::TetMeshBase::Region_element_pt, s, oomph::Mesh::set_nboundary(), size, oomph::FiniteElement::size(), oomph::Global_string_for_annotation::string(), sub(), oomph::StringConversion::to_string(), plotDoE::x, and oomph::Node::x().
Referenced by GmshTetScaffoldMesh().
write_geo_file()
void oomph::GmshTetScaffoldMesh::write_geo_file (const bool & use_mesh_grading_from_file) inline private
Write geo file for gmsh.
     {
       // Transfer data from parameters
       TetMeshFacetedClosedSurface* outer_boundary_pt =
         Gmsh_parameters_pt->outer_boundary_pt();
       Vector<TetMeshFacetedSurface*> internal_surface_pt =
         Gmsh_parameters_pt->internal_surface_pt();
       double element_volume = Gmsh_parameters_pt->element_volume();
       std::string& target_size_file_name =
         Gmsh_parameters_pt->target_size_file_name();
       // Write gmsh geo file:
       std::string filename =
         Gmsh_parameters_pt->geo_and_msh_file_stem() + ".geo";
       std::ofstream geo_file;
       geo_file.open(filename.c_str());
       geo_file << "// Uniform element size" << std::endl;
       geo_file << "//---------------------" << std::endl;
       geo_file << "lc=" << pow(element_volume, 1.0 / 3.0) << ";" << std::endl;
       geo_file << std::endl;
       // Outer boundary
       //===============
       // Create vertices
       geo_file << "// Outer box" << std::endl;
       geo_file << "//==========" << std::endl;
       geo_file << std::endl;
       geo_file << "// Vertices" << std::endl;
       geo_file << "//---------" << std::endl;
       std::map<TetMeshVertex*, unsigned> vertex_number;
       unsigned nv = outer_boundary_pt->nvertex();
       for (unsigned j = 0; j < nv; j++)
       {
         TetMeshVertex* vertex_pt = outer_boundary_pt->vertex_pt(j);
         vertex_number[vertex_pt] = j;
         geo_file << "Point(" << j + 1 << ")={";
         for (unsigned i = 0; i < 3; i++)
         {
           geo_file << vertex_pt->x(i) << ",";
         }
         geo_file << "lc};" << std::endl;
       }
       // Determine unique edges
       std::set<TetEdge> tet_edge_set;
       unsigned nfacet = outer_boundary_pt->nfacet();
       for (unsigned f = 0; f < nfacet; f++)
       {
         TetMeshFacet* facet_pt = outer_boundary_pt->facet_pt(f);
         unsigned nv = facet_pt->nvertex();
         for (unsigned j = 0; j < nv - 1; j++)
         {
           TetMeshVertex* first_vertex_pt = facet_pt->vertex_pt(j);
           TetMeshVertex* second_vertex_pt = facet_pt->vertex_pt(j + 1);
           TetEdge my_tet_edge(vertex_number[first_vertex_pt] + 1,
                               vertex_number[second_vertex_pt] + 1);
           tet_edge_set.insert(my_tet_edge);
         }
         TetMeshVertex* first_vertex_pt = facet_pt->vertex_pt(nv - 1);
         TetMeshVertex* second_vertex_pt = facet_pt->vertex_pt(0);
         TetEdge my_tet_edge(vertex_number[first_vertex_pt] + 1,
                             vertex_number[second_vertex_pt] + 1);
         tet_edge_set.insert(my_tet_edge);
       }
       geo_file << std::endl;
       geo_file << "// Edge of outer box" << std::endl;
       geo_file << "//------------------" << std::endl;
       unsigned count = 0;
       std::map<TetEdge, unsigned> tet_edge;
       for (std::set<TetEdge>::iterator it = tet_edge_set.begin();
            it != tet_edge_set.end();
            it++)
       {
         tet_edge.insert(std::make_pair((*it), count));
         geo_file << "Line(" << count + 1 << ")={" << (*it).first_vertex_id()
                  << "," << (*it).second_vertex_id() << "};" << std::endl;
         count++;
       }
       geo_file << std::endl;
       geo_file << "// Faces of outer box" << std::endl;
       geo_file << "//-------------------" << std::endl;
       for (unsigned f = 0; f < nfacet; f++)
       {
         geo_file << "Line Loop(" << f + 1 << ")={";
         TetMeshFacet* facet_pt = outer_boundary_pt->facet_pt(f);
         unsigned nv = facet_pt->nvertex();
         for (unsigned j = 0; j < nv - 1; j++)
         {
           TetMeshVertex* first_vertex_pt = facet_pt->vertex_pt(j);
           TetMeshVertex* second_vertex_pt = facet_pt->vertex_pt(j + 1);
           TetEdge my_tet_edge(vertex_number[first_vertex_pt] + 1,
                               vertex_number[second_vertex_pt] + 1);
           std::map<TetEdge, unsigned>::iterator it = tet_edge.find(my_tet_edge);
           if (my_tet_edge.is_reversed())
           {
             geo_file << -int((it->second) + 1) << ",";
           }
           else
           {
             geo_file << ((it->second) + 1) << ",";
           }
         }
         TetMeshVertex* first_vertex_pt = facet_pt->vertex_pt(nv - 1);
         TetMeshVertex* second_vertex_pt = facet_pt->vertex_pt(0);
         TetEdge my_tet_edge(vertex_number[first_vertex_pt] + 1,
                             vertex_number[second_vertex_pt] + 1);
         std::map<TetEdge, unsigned>::iterator it = tet_edge.find(my_tet_edge);
         if (my_tet_edge.is_reversed())
         {
           geo_file << -int((it->second) + 1) << "};" << std::endl;
         }
         else
         {
           geo_file << ((it->second) + 1) << "};" << std::endl;
         }
         geo_file << "Plane Surface(" << f + 1 << ")={" << f + 1 << "};"
                  << std::endl;
       }
       geo_file << std::endl;
       geo_file << "// Define Plane Surfaces bounding the volume" << std::endl;
       geo_file << "//------------------------------------------" << std::endl;
       geo_file << "Surface Loop(1) = {";
       for (unsigned f = 0; f < nfacet - 1; f++)
       {
         geo_file << f + 1 << ",";
       }
       geo_file << nfacet << "};" << std::endl;
       geo_file << std::endl;
       geo_file << "// Define one-based boundary IDs" << std::endl;
       geo_file << "//------------------------------" << std::endl;
       for (unsigned f = 0; f < nfacet; f++)
       {
         unsigned one_based_boundary_id =
           outer_boundary_pt->one_based_facet_boundary_id(f);
         geo_file << "Physical Surface(" << one_based_boundary_id << ") = {"
                  << f + 1 << "};" << std::endl;
       }
       // Offsets before we start adding the various internal volumes/surfaces
       Vector<unsigned> volume_id_to_be_subtracted_off;
       unsigned nvertex_offset = outer_boundary_pt->nvertex();
       unsigned nfacet_offset = outer_boundary_pt->nfacet();
       unsigned nvolume_offset = 1;
       unsigned nline_offset = tet_edge.size();
       // Storage for one-based ids of surfaces to be embedded in
       // main volume
       Vector<unsigned> surfaces_to_be_embedded_in_main_volume;
       std::map<unsigned, Vector<unsigned>>
         surfaces_to_be_embedded_in_specified_one_based_region;
       // Now deal with internal faceted objects
       //=======================================
       unsigned n_internal = internal_surface_pt.size();
       for (unsigned i_internal = 0; i_internal < n_internal; i_internal++)
       {
         // Closed surface?
         TetMeshFacetedClosedSurface* closed_srf_pt =
           dynamic_cast<TetMeshFacetedClosedSurface*>(
             internal_surface_pt[i_internal]);
         bool inner_surface_is_closed = true;
         if (closed_srf_pt == 0)
         {
           inner_surface_is_closed = false;
         }
         // What it says
         unsigned number_of_volumes_created_for_this_internal_object = 0;
         // Create vertices
         geo_file << std::endl;
         geo_file << std::endl;
         geo_file << "// Inner faceted surface " << i_internal << std::endl;
         geo_file << "//==========================" << std::endl;
         geo_file << std::endl;
         geo_file << "// Vertices" << std::endl;
         geo_file << "//---------" << std::endl;
         std::map<TetMeshVertex*, unsigned> vertex_number;
         unsigned nv = internal_surface_pt[i_internal]->nvertex();
         for (unsigned j = 0; j < nv; j++)
         {
           TetMeshVertex* vertex_pt =
             internal_surface_pt[i_internal]->vertex_pt(j);
           vertex_number[vertex_pt] = nvertex_offset + j;
           geo_file << "Point(" << nvertex_offset + j + 1 << ")={";
           for (unsigned i = 0; i < 3; i++)
           {
             geo_file << vertex_pt->x(i) << ",";
           }
           geo_file << "lc};" << std::endl;
         }
         // Determine unique edges
         std::set<TetEdge> tet_edge_set;
         unsigned nfacet = internal_surface_pt[i_internal]->nfacet();
         for (unsigned f = 0; f < nfacet; f++)
         {
           TetMeshFacet* facet_pt = internal_surface_pt[i_internal]->facet_pt(f);
           unsigned nv = facet_pt->nvertex();
           for (unsigned j = 0; j < nv - 1; j++)
           {
             TetMeshVertex* first_vertex_pt = facet_pt->vertex_pt(j);
             TetMeshVertex* second_vertex_pt = facet_pt->vertex_pt(j + 1);
             TetEdge my_tet_edge(vertex_number[first_vertex_pt] + 1,
                                 vertex_number[second_vertex_pt] + 1);
             tet_edge_set.insert(my_tet_edge);
           }
           TetMeshVertex* first_vertex_pt = facet_pt->vertex_pt(nv - 1);
           TetMeshVertex* second_vertex_pt = facet_pt->vertex_pt(0);
           TetEdge my_tet_edge(vertex_number[first_vertex_pt] + 1,
                               vertex_number[second_vertex_pt] + 1);
           tet_edge_set.insert(my_tet_edge);
         }
         geo_file << std::endl;
         geo_file << "// Edge of inner faceted surface" << std::endl;
         geo_file << "//------------------------------" << std::endl;
         unsigned count = 0;
         std::map<TetEdge, unsigned> tet_edge;
         for (std::set<TetEdge>::iterator it = tet_edge_set.begin();
              it != tet_edge_set.end();
              it++)
         {
           tet_edge.insert(std::make_pair((*it), nline_offset + count));
           geo_file << "Line(" << nline_offset + count + 1 << ")={"
                    << (*it).first_vertex_id() << "," << (*it).second_vertex_id()
                    << "};" << std::endl;
           count++;
         }
         geo_file << std::endl;
         geo_file << "// Faces of inner faceted surface" << std::endl;
         geo_file << "//-------------------------------" << std::endl;
         for (unsigned f = 0; f < nfacet; f++)
         {
           geo_file << "Line Loop(" << nfacet_offset + f + 1 << ")={";
           TetMeshFacet* facet_pt = internal_surface_pt[i_internal]->facet_pt(f);
           unsigned nv = facet_pt->nvertex();
           for (unsigned j = 0; j < nv - 1; j++)
           {
             TetMeshVertex* first_vertex_pt = facet_pt->vertex_pt(j);
             TetMeshVertex* second_vertex_pt = facet_pt->vertex_pt(j + 1);
             TetEdge my_tet_edge(vertex_number[first_vertex_pt] + 1,
                                 vertex_number[second_vertex_pt] + 1);
             std::map<TetEdge, unsigned>::iterator it =
               tet_edge.find(my_tet_edge);
             if (my_tet_edge.is_reversed())
             {
               geo_file << -int((it->second) + 1) << ",";
             }
             else
             {
               geo_file << ((it->second) + 1) << ",";
             }
           }
           TetMeshVertex* first_vertex_pt = facet_pt->vertex_pt(nv - 1);
           TetMeshVertex* second_vertex_pt = facet_pt->vertex_pt(0);
           TetEdge my_tet_edge(vertex_number[first_vertex_pt] + 1,
                               vertex_number[second_vertex_pt] + 1);
           std::map<TetEdge, unsigned>::iterator it = tet_edge.find(my_tet_edge);
           if (my_tet_edge.is_reversed())
           {
             geo_file << -int((it->second) + 1) << "};" << std::endl;
           }
           else
           {
             geo_file << ((it->second) + 1) << "};" << std::endl;
           }
           geo_file << "Plane Surface(" << nfacet_offset + f + 1 << ")={"
                    << nfacet_offset + f + 1 << "};" << std::endl;
           // Keep track of plane surfaces that we've created so we
           // can embed them in volume for non-closed surfaces
           bool facet_is_embedded_in_a_volume =
             facet_pt->facet_is_embedded_in_a_specified_region();
           if (facet_is_embedded_in_a_volume)
           {
             unsigned one_based_region_id =
               facet_pt->one_based_region_that_facet_is_embedded_in();
             if (one_based_region_id == 1)
             {
               surfaces_to_be_embedded_in_main_volume.push_back(nfacet_offset +
                                                                f + 1);
             }
             else
             {
               surfaces_to_be_embedded_in_specified_one_based_region
                 [one_based_region_id]
                   .push_back(nfacet_offset + f + 1);
             }
           }
           else
           {
             // By default put all surfaces into main volume
             if (!inner_surface_is_closed)
             {
               surfaces_to_be_embedded_in_main_volume.push_back(nfacet_offset +
                                                                f + 1);
             }
           }
         }
         // Store all region IDs defined by bounding facets
         std::set<unsigned> all_regions_id;
         // region_bounding_facet[r][i] returns the facet id (in gmsh
         // counting) of i-th facet bounding region r
         std::map<unsigned, Vector<unsigned>> region_bounding_facet;
         // outer_bounding_facet[i] returns the facet id (in gmsh
         // counting) that encloses the actual regions and acts as a
         // hole in the main volume (volume 1)
         Vector<unsigned> outer_bounding_facet;
         // Loop pver all facets to figure out which regions are bounded
         // by them
         for (unsigned f = 0; f < nfacet; f++)
         {
           TetMeshFacet* facet_pt = internal_surface_pt[i_internal]->facet_pt(f);
           std::set<unsigned> region_id(
             facet_pt->one_based_adjacent_region_id());
           unsigned nr = region_id.size();
           if (nr == 1) outer_bounding_facet.push_back(nfacet_offset + f + 1);
           if ((nr == 0) && inner_surface_is_closed)
           {
             // Add to list of plane surfaces that don't bound regions so we
             // can embed them in volume for non-closed surfaces
             surfaces_to_be_embedded_in_main_volume.push_back(nfacet_offset + f +
                                                              1);
           }
           for (std::set<unsigned>::iterator it = region_id.begin();
                it != region_id.end();
                it++)
           {
             all_regions_id.insert((*it));
             region_bounding_facet[(*it)].push_back(nfacet_offset + f + 1);
           }
         }
         // Number of regions bounded by facets
         unsigned n_regions_bounded_by_facets = all_regions_id.size();
         // No bounded regions
         if (n_regions_bounded_by_facets == 0)
         {
           if (inner_surface_is_closed)
           {
             std::ostringstream error_message;
             error_message
               << "Something fishy going on! "
               << "Internal faceted surface " << i_internal
               << " is closed but does not bound any regions!\n"
               << "Specify one-based region ID for all facets using\n\n"
               << "   TetMeshFacet::set_one_based_adjacent_region_id(...)\n\n";
             throw OomphLibError(error_message.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
           }
         }
         else
         {
           // Do we need to create a hole in the main volume that contains
           // the multiple sub-volumes/regions?
           unsigned offset_for_extra_hole = 0;
           if (n_regions_bounded_by_facets > 1)
           {
             geo_file << std::endl;
             geo_file << "// Define Plane Surfaces bounding compound volume"
                      << std::endl
                      << "//-----------------------------------------------"
                      << std::endl;
             geo_file << "// that will have to be treated as hole in main volume"
                      << std::endl
                      << "//-----------------------------------------------"
                      << std::endl;
             offset_for_extra_hole = 1;
             geo_file << "Surface Loop(" << nvolume_offset + 1 << ") = {";
             unsigned n = outer_bounding_facet.size();
             for (unsigned f = 0; f < n - 1; f++)
             {
               geo_file << outer_bounding_facet[f] << ",";
             }
             geo_file << outer_bounding_facet[n - 1] << "};" << std::endl;
             // Bump
             number_of_volumes_created_for_this_internal_object++;
           }
           // Need to remove the internal volume from the outer volume
           volume_id_to_be_subtracted_off.push_back(nvolume_offset + 1);
           // Deal with actual regions that fill the hole
           unsigned count = 0;
           for (std::map<unsigned, Vector<unsigned>>::iterator it =
                  region_bounding_facet.begin();
                it != region_bounding_facet.end();
                it++)
           {
             geo_file << std::endl;
             geo_file << "// Define Plane Surfaces bounding the region volume "
                      << (*it).first << std::endl;
             geo_file << "//----------------------------------------------------"
                      << std::endl;
             geo_file << "Surface Loop("
                      << nvolume_offset + 1 + offset_for_extra_hole + count
                      << ") = {";
             unsigned n = (*it).second.size();
             for (unsigned f = 0; f < n - 1; f++)
             {
               geo_file << ((*it).second)[f] << ",";
             }
             geo_file << ((*it).second)[n - 1] << "};" << std::endl;
             geo_file << std::endl;
             geo_file << "// Define volume "
                      << nvolume_offset + 1 + offset_for_extra_hole + count
                      << " as the volume bounded by Surface Loop "
                      << nvolume_offset + 1 + offset_for_extra_hole + count
                      << std::endl;
             geo_file
               << "//--------------------------------------------------------"
               << std::endl;
             geo_file << "Volume("
                      << nvolume_offset + 1 + offset_for_extra_hole + count
                      << ")={"
                      << nvolume_offset + 1 + offset_for_extra_hole + count
                      << "};" << std::endl;
             geo_file << std::endl;
             // Bump
             number_of_volumes_created_for_this_internal_object++;
             // Add as physical (to be meshed) volume if it's not a volume
             bool mesh_the_volume = true;
             if (closed_srf_pt != 0)
             {
               if (closed_srf_pt->faceted_volume_represents_hole_for_gmsh())
               {
                 mesh_the_volume = false;
               }
             }
             if (mesh_the_volume)
             {
               geo_file << "// Define one-based region IDs" << std::endl;
               geo_file << "//----------------------------" << std::endl;
               geo_file << "Physical Volume(" << (*it).first << ")={"
                        << nvolume_offset + 1 + offset_for_extra_hole + count
                        << "};" << std::endl;
               unsigned ns_embedded =
                 surfaces_to_be_embedded_in_specified_one_based_region[(*it)
                                                                         .first]
                   .size();
               if (ns_embedded > 0)
               {
                 geo_file << "// This region has " << ns_embedded
                          << " embedded surfaces\n";
                 geo_file << "Surface{";
                 for (unsigned i = 0; i < ns_embedded - 1; i++)
                 {
                   geo_file
                     << surfaces_to_be_embedded_in_specified_one_based_region
                          [(*it).first][i]
                     << ",";
                 }
                 geo_file
                   << surfaces_to_be_embedded_in_specified_one_based_region
                        [(*it).first][ns_embedded - 1]
                   << "}In Volume {"
                   << nvolume_offset + 1 + offset_for_extra_hole + count << "};"
                   << std::endl;
               }
             }
             count++;
           }
         }
         geo_file << std::endl;
         geo_file << "// Define one-based boundary IDs" << std::endl;
         geo_file << "//------------------------------" << std::endl;
         for (unsigned f = 0; f < nfacet; f++)
         {
           unsigned one_based_boundary_id =
             internal_surface_pt[i_internal]->one_based_facet_boundary_id(f);
           geo_file << "Physical Surface(" << one_based_boundary_id << ") = {"
                    << nfacet_offset + f + 1 << "};" << std::endl;
         }
         // Bump
         nvertex_offset += internal_surface_pt[i_internal]->nvertex();
         nfacet_offset += internal_surface_pt[i_internal]->nfacet();
         nvolume_offset += number_of_volumes_created_for_this_internal_object;
         nline_offset += tet_edge.size();
       }
       // Done with the internal regions; write the actual volume
       // and specify embedded surfaces
       geo_file << std::endl;
       geo_file << "// Define volume 1 as the volume bounded by Surface Loop 1"
                << std::endl;
       geo_file << "//--------------------------------------------------------"
                << std::endl;
       unsigned n = volume_id_to_be_subtracted_off.size();
       if (n > 0)
       {
         geo_file << "// with volume[s]: ";
         for (unsigned i = 0; i < n; i++)
         {
           geo_file << volume_id_to_be_subtracted_off[i] << " ";
         }
         geo_file << "removed." << std::endl;
         geo_file << "//--------------------------------------------------------"
                  << std::endl;
       }
       // Add initial volume
       geo_file << "Volume(1)={1";
       // Remove volumes that has separate IDs
       for (unsigned i = 0; i < n; i++)
       {
         geo_file << "," << volume_id_to_be_subtracted_off[i];
       }
       geo_file << "};" << std::endl;
       geo_file << std::endl;
       geo_file << "// Define one-based region IDs" << std::endl;
       geo_file << "//----------------------------" << std::endl;
       geo_file << "Physical Volume(1"
                << ")={1};" << std::endl;
       // Now embed any surfaces that don't bound volumes
       unsigned ns = surfaces_to_be_embedded_in_main_volume.size();
       if (ns > 0)
       {
         geo_file << std::endl;
         geo_file << "// Embed Plane Surfaces in main volume (volume 1)"
                  << std::endl;
         geo_file << "//-----------------------------------------------"
                  << std::endl;
         geo_file << "Surface{";
         for (unsigned s = 0; s < ns - 1; s++)
         {
           geo_file << surfaces_to_be_embedded_in_main_volume[s] << ",";
         }
         geo_file << surfaces_to_be_embedded_in_main_volume[ns - 1]
                  << "} In Volume{1};" << std::endl;
         geo_file << std::endl;
       }
       // Mesh grading
       {
         if (use_mesh_grading_from_file)
         {
 #ifdef PARANOID
           // Open wide...
           std::ifstream file(target_size_file_name.c_str(), std::ios_base::in);
           // Check that the file actually opened correctly
           if (!file.is_open())
           {
             std::string error_msg("Failed to open target volume file: ");
             error_msg += "\"" + target_size_file_name;
             throw OomphLibError(
               error_msg, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
           }
 #endif
           geo_file << "Field[1]=Structured;" << std::endl;
           geo_file << "Field[1].FileName=\"" << target_size_file_name << "\";"
                    << std::endl;
           geo_file << "Field[1].TextFormat=1;" << std::endl;
           geo_file << "Background Field = 1;" << std::endl;
         }
       }
       // Mesh the bloody thing
       geo_file << std::endl;
       geo_file << "Mesh 3;" << std::endl;
       /* // hierher Christmas attempt at optimisation */
       /* geo_file << std::endl; */
       /* geo_file << "// Attempt at optimisation:
        * http://onelab.info/pipermail/gmsh/2015/010126.html" << std::endl; */
       /* geo_file << "//----------------------------" << std::endl; */
       /* geo_file << "Mesh.Optimize=1;" << std::endl; */
       /* geo_file << "Mesh.OptimizeNetgen=1;" << std::endl; */
       geo_file.close();
     }
References oomph::GmshParameters::element_volume(), f(), oomph::TetMeshFacet::facet_is_embedded_in_a_specified_region(), oomph::TetMeshFacetedSurface::facet_pt(), oomph::TetMeshFacetedClosedSurface::faceted_volume_represents_hole_for_gmsh(), MergeRestartFiles::filename, oomph::GmshParameters::geo_and_msh_file_stem(), Gmsh_parameters_pt, i, int(), oomph::GmshParameters::internal_surface_pt(), oomph::TetEdge::is_reversed(), j, n, oomph::TetMeshFacetedSurface::nfacet(), oomph::TetMeshFacet::nvertex(), oomph::TetMeshFacetedSurface::nvertex(), oomph::TetMeshFacet::one_based_adjacent_region_id(), oomph::TetMeshFacetedSurface::one_based_facet_boundary_id(), oomph::TetMeshFacet::one_based_region_that_facet_is_embedded_in(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::GmshParameters::outer_boundary_pt(), Eigen::bfloat16_impl::pow(), s, oomph::Global_string_for_annotation::string(), oomph::GmshParameters::target_size_file_name(), oomph::TetMeshFacet::vertex_pt(), oomph::TetMeshFacetedSurface::vertex_pt(), and oomph::TetMeshVertex::x().
Referenced by GmshTetScaffoldMesh().
Friends And Related Function Documentation
GmshTetMesh
template<class ELEMENT > friend class GmshTetMesh friend
We're friends with the actual mesh.
Member Data Documentation
Gmsh_parameters_pt
GmshParameters* oomph::GmshTetScaffoldMesh::Gmsh_parameters_pt private
Parameters.
Referenced by create_mesh_from_msh_file(), GmshTetScaffoldMesh(), and write_geo_file().
The documentation for this class was generated from the following file:
gmsh_tet_mesh.template.h