MercuryDPM: ConstSourceForPoisson Namespace Reference
ConstSourceForPoisson Namespace Reference
Namespace for const source term in Poisson equation.
Functions
void get_source (const Vector< double > &x, double &source)
Const source function.
void source_function (const Vector< double > &x, double &source)
Const source function.
Variables
double Strength =1.0
Strength of source function: default value 1.0.
Detailed Description
Namespace for const source term in Poisson equation.
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Function Documentation
get_source()
void ConstSourceForPoisson::get_source (const Vector< double > & x, double & source)
Const source function.
  {
   source = -Strength*(1.0+x[0]*x[1]);
  }
References TestProblem::source(), Strength, and plotDoE::x.
Referenced by DeformableFishPoissonProblem< ELEMENT >::DeformableFishPoissonProblem(), FreeBoundaryPoissonProblem< ELEMENT >::FreeBoundaryPoissonProblem(), RefineableFishPoissonProblem< ELEMENT >::RefineableFishPoissonProblem(), and SimpleRefineableFishPoissonProblem< ELEMENT >::SimpleRefineableFishPoissonProblem().
source_function()
void ConstSourceForPoisson::source_function (const Vector< double > & x, double & source)
Const source function.
  {
   source = Strength;
  }
References TestProblem::source(), and Strength.
Referenced by FishPoissonProblem< ELEMENT >::FishPoissonProblem(), and RefineableFishPoissonProblem< ELEMENT >::RefineableFishPoissonProblem().
Variable Documentation
Strength
double ConstSourceForPoisson::Strength =1.0
Strength of source function: default value 1.0.
Strength of source function: default value -1.0.
Referenced by get_source(), and source_function().