MercuryDPM: SlidingFrictionInteraction Class Reference
SlidingFrictionInteraction Class Reference
Computes the forces corresponding to sliding friction.
#include <SlidingFrictionInteraction.h>
Public Types
typedef SlidingFrictionSpecies SpeciesType
An alias name for SlidingFrictionSpecies data type.
Public Member Functions
SlidingFrictionInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
Constructor.
SlidingFrictionInteraction ()
SlidingFrictionInteraction (const SlidingFrictionInteraction &p)
Copy constructor.
~SlidingFrictionInteraction () override
Destructor.
void computeFrictionForce ()
Computes the tangential force generated due to compression in the sliding spring. Does take into account if the interaction is between particle-particle or particle-wall.
void read (std::istream &is) override
Interaction read function, which accepts an std::istream as input.
void write (std::ostream &os) const override
Interaction write function, which accepts an std::ostream as input.
void integrate (Mdouble timeStep) override
Increments the amount of compression in sliding spring.
Mdouble getElasticEnergy () const override
Returns the amount of elastic energy stored in sliding spring.
Mdouble getTangentialOverlap () const override
Returns the amount of tangential overlap which is needed by BaseInteraction::writeToFstat().
std::string getBaseName () const
Returns the type/name of interaction (sliding friction interaction)
void setSlidingSpring (Vec3D slidingSpring)
Vec3D getSlidingSpring () const
const Vec3D getTangentialForce () const override
Returns the sliding friction force vector.
void addTangentialForce (Vec3D force)
adds an extra tangential force, mainly for the tangential lubrication force from LiquidMigrationLS model.
const SlidingFrictionSpecies * getSpecies () const
Returns a const pointer of type SlidingFrictionSpecies*.
void reverseHistory () override
A useful feature if one wants to return to the initial state of the spring. However, reverse history decrements the current state to the state corresponding to previous time step. Decrements the value of slidingSpring_.
void rotateHistory (Matrix3D &rotationMatrix) override
When periodic particles are used, some interactions need certain history properties rotated (e.g. tangential springs). This is the function for that.
void moveSlidingSpring (Vec3D displacement)
void computeSlidingSpring (const Vec3D &tangentialRelativeVelocity)
void setIsSuperQuadricInteraction (bool isSuperQuadricInteraction)
Public Member Functions inherited from BaseInteraction
BaseInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
A constructor takes the BaseInteractable objects which are interacting (come into contact) and time the interaction starts.
BaseInteraction ()
BaseInteraction (const BaseInteraction &p)
Copy constructor.
~BaseInteraction () override
The destructor. It removes this interactions from the objects that were interacting, and writes the time to a file when needed.
virtual void actionsOnErase ()
If an interaction needs to do something before it gets erased, add it here. E.g. Liquid bridges rupture at the end of their lifetime, and the liquid bridge volume has to be redistributed. The reason this action is not done in the destructor is that this action should not be taken when erasing ghost interactions.
virtual void computeForce ()
Virtual function that contains the force law between the two objects interacting.
void writeToFStat (std::ostream &os, Mdouble time) const
Writes forces data to the FStat file.
std::string getName () const override
Virtual function which allows interactions to be named.
void setDistance (Mdouble distance)
Sets the interaction distance between the two interacting objects.
void setNormal (Vec3D normal)
Sets the normal vector between the two interacting objects.
void setOverlap (Mdouble overlap)
Set the overlap between the two interacting object.
void setContactPoint (Vec3D contactPoint)
Set the location of the contact point between the two interacting objects.
void setTimeStamp (unsigned timeStamp)
Updates the time step of the interacting. Note, time steps used to find completed interactions.
void setSpecies (const BaseSpecies *species)
Set the Species of the interaction; note this can either be a Species or MixedSpecies.
void setP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void setI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
void importP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void importI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
Vec3D getIP () const
Vec3D getIC () const
Vec3D getCP () const
void setLagrangeMultiplier (Mdouble multiplier)
Mdouble getLagrangeMultiplier ()
void setHandler (InteractionHandler *handler)
Sets the pointer to the interaction hander which is storing this interaction.
InteractionHandler * getHandler () const
Gets a point to the interaction handlers to which this interaction belongs.
const Vec3D & getForce () const
Gets the current force (vector) between the two interacting objects.
const Vec3D & getTorque () const
Gets the current torque (vector) between the two interacting objects.
const Vec3D & getNormal () const
Gets the normal vector between the two interacting objects.
const Vec3D & getContactPoint () const
Gets constant reference to contact point (vector).
Mdouble getOverlap () const
Returns a Mdouble with the current overlap between the two interacting objects.
Mdouble getOverlapVolume () const
Returns the overlap volume between two interacting objects.
Mdouble getContactRadius () const
Returns a Mdouble with the current contact between the two interacting objects.
void removeFromHandler ()
Removes this interaction from its interaction hander.
void copySwitchPointer (const BaseInteractable *original, BaseInteractable *ghost) const
This copies the interactions of the original particle and replaces the original with the ghost copy.
void gatherContactStatistics ()
BaseInteractable * getP ()
Returns a pointer to first object involved in the interaction (normally a particle).
BaseInteractable * getI ()
Returns a pointer to the second object involved in the interaction (often a wall or a particle).
const BaseInteractable * getP () const
Returns a constant pointer to the first object involved in the interaction.
const BaseInteractable * getI () const
Returns a constant pointer to the second object involved in the interaction.
Mdouble getTimeStamp () const
Returns an Mdouble which is the time stamp of the interaction.
Mdouble getDistance () const
Returns an Mdouble which is the norm (length) of distance vector.
const Vec3D & getRelativeVelocity () const
Returns a constant reference to a vector of relative velocity.
Mdouble getNormalRelativeVelocity () const
Returns a double which is the norm (length) of the relative velocity vector.
Mdouble getAbsoluteNormalForce () const
Returns the absolute value of the norm (length) of the Normal force vector.
virtual BaseInteraction * copy () const =0
Makes a copy of the interaction and returns a pointer to the copy.
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseWall *I)
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseParticle *I)
unsigned int getMultiContactIdentifier () const
void setMultiContactIdentifier (unsigned int multiContactIdentifier_)
virtual void actionsAfterTimeStep ()
virtual unsigned getNumberOfFieldsVTK () const
virtual std::string getTypeVTK (unsigned i) const
virtual std::string getNameVTK (unsigned i) const
virtual std::vector< Mdouble > getFieldVTK (unsigned i) const
void addForce (Vec3D force)
add an force increment to the total force.
void addTorque (Vec3D torque)
add a torque increment to the total torque.
void setForce (Vec3D force)
set total force (this is used by the normal force, tangential forces are added use addForce)
void setTorque (Vec3D torque)
set the total force (this is used by the normal force, tangential torques are added use addTorque)
const BaseSpecies * getBaseSpecies () const
Return a constant point to BaseSpecies of the interaction.
virtual void createMPIType ()
virtual void * createMPIInteractionDataArray (unsigned int numberOfInteractions) const
virtual void deleteMPIInteractionDataArray (void *dataArray)
virtual void getMPIInteraction (void *historyDataArray, unsigned int index) const
copies the history interactions into the data array
virtual void getInteractionDetails (void *interactionDataArray, unsigned int index, unsigned int &identificationP, unsigned int &identificationI, bool &isWallInteraction, unsigned &timeStamp)
virtual void setMPIInteraction (void *interactionDataArray, unsigned int index, bool resetPointers)
void setBasicMPIInteractionValues (int P, int I, unsigned timeStamp, Vec3D force, Vec3D torque, bool isWallInteraction, bool resetPointers)
void setIdentificationP (unsigned int identification)
void setIdentificationI (int identification)
void setWallInteraction (bool flag)
unsigned int getIdentificationP ()
int getIdentificationI ()
bool isWallInteraction ()
virtual bool isBonded () const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Protected Attributes
Vec3D slidingSpring_
Stores the amount of sliding spring (\(\delta\)) compression from the expression \(f_t=-k*\delta-\nu*relVel\). Set in the member function integrate(), used in computeFrictionForce().
Vec3D slidingSpringVelocity_
Stores the rate at which the sliding spring compressed or relaxed. Set in the member function computeFrictionForce() and used in integrate().
Vec3D tangentialForce_
Computes the tangential force such that \(|f_t|=\mu*|f_n|\). Set and computed in computeFrictionForce().
bool isSuperQuadricInteraction_
Additional Inherited Members
Protected Member Functions inherited from BaseInteraction
Mdouble getEffectiveRadius () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
Mdouble getEffectiveMass () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
void setRelativeVelocity (Vec3D relativeVelocity)
set the relative velocity of the current of the interactions.
void setNormalRelativeVelocity (Mdouble normalRelativeVelocit)
set the normal component of the relative velocity.
void setAbsoluteNormalForce (Mdouble absoluteNormalForce)
the absolute values of the norm (length) of the normal force
virtual Mdouble getElasticEnergyAtEquilibrium (Mdouble adhesiveForce) const
void writeInteraction (std::ostream &os, bool created) const
Writes information about a interaction to the interaction file.
Detailed Description
Computes the forces corresponding to sliding friction.
Member Typedef Documentation
SpeciesType
typedef SlidingFrictionSpecies SlidingFrictionInteraction::SpeciesType
An alias name for SlidingFrictionSpecies data type.
Constructor & Destructor Documentation
SlidingFrictionInteraction() [1/3]
SlidingFrictionInteraction::SlidingFrictionInteraction (BaseInteractable * P, BaseInteractable * I, unsigned timeStamp)
Constructor.
Parameters
[in] P
[in] I
[in] timeStamp
         : BaseInteraction(P, I, timeStamp)
 {
     slidingSpring_.setZero();
     isSuperQuadricInteraction_ = false;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"SlidingFrictionInteraction::SlidingFrictionInteraction() finished"<<std::endl;
 #endif
 }
References isSuperQuadricInteraction_, Vec3D::setZero(), and slidingSpring_.
SlidingFrictionInteraction() [2/3]
SlidingFrictionInteraction::SlidingFrictionInteraction ()
         : BaseInteraction()
 {
     slidingSpring_.setZero();
     isSuperQuadricInteraction_ = false;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"SlidingFrictionInteraction::SlidingFrictionInteraction() finished"<<std::endl;
 #endif
 }
References isSuperQuadricInteraction_, Vec3D::setZero(), and slidingSpring_.
SlidingFrictionInteraction() [3/3]
SlidingFrictionInteraction::SlidingFrictionInteraction (const SlidingFrictionInteraction & p)
Copy constructor.
Parameters
[in] p
         : BaseInteraction(p)
 {
     slidingSpring_ = p.slidingSpring_;
     isSuperQuadricInteraction_ = p.isSuperQuadricInteraction_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"SlidingFrictionInteraction::SlidingFrictionInteraction(const SlidingFrictionInteraction& p) finished"<<std::endl;
 #endif
 }
References isSuperQuadricInteraction_, p, and slidingSpring_.
~SlidingFrictionInteraction()
SlidingFrictionInteraction::~SlidingFrictionInteraction () override
Destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"SlidingFrictionInteraction::~SlidingFrictionInteraction() finished"<<std::endl;
 #endif
 }
Member Function Documentation
addTangentialForce()
void SlidingFrictionInteraction::addTangentialForce (Vec3D force) inline
adds an extra tangential force, mainly for the tangential lubrication force from LiquidMigrationLS model.
{
         tangentialForce_ = Vec3D(0.0,0.0,0.0);
         tangentialForce_ += force;
     }
References tangentialForce_.
Referenced by LiquidMigrationLSInteraction::computeAdhesionForce(), and LiquidMigrationWilletViscousInteraction::computeAdhesionForce().
computeFrictionForce()
void SlidingFrictionInteraction::computeFrictionForce ()
Computes the tangential force generated due to compression in the sliding spring. Does take into account if the interaction is between particle-particle or particle-wall.
 {
     //If tangential forces are absent
     if (getAbsoluteNormalForce() == 0.0) return;
     const SlidingFrictionSpecies* species = getSpecies();//dynamic_cast
     isSuperQuadricInteraction_ = species->getIsSuperquadricSpecies();
     if (species->getSlidingFrictionCoefficient() != 0.0)
     {
         //Compute the tangential component of relativeVelocity_
         // relativeVelocity = [v_p + (r_p-c) x w_p] - [v_i + (r_i-c) x w_i]
         // tangentialRelativeVelocity = relativeVelocity - (relativeVelocity . n) n
         Vec3D tangentialRelativeVelocity = getRelativeVelocity() - getNormal() * getNormalRelativeVelocity();
         if (species->getSlidingStiffness() != 0.0)
         {
             computeSlidingSpring(tangentialRelativeVelocity);
             //Calculate test force acting on P including viscous force
             tangentialForce_ = -species->getSlidingStiffness() * slidingSpring_ -
                                species->getSlidingDissipation() * tangentialRelativeVelocity;
             if (getBaseSpecies()->getNormalForce()->getConstantRestitution()) tangentialForce_ *=2.0*getEffectiveMass();
             //tangential forces are modelled by a spring-damper of elasticity kt and viscosity dispt (sticking),
             //but the force is limited by Coulomb friction (sliding):
             Mdouble tangentialForceSquared = tangentialForce_.getLengthSquared();
             if (tangentialForceSquared <=
                 mathsFunc::square(species->getSlidingFrictionCoefficientStatic() * getAbsoluteNormalForce()))
             {
                 //if sticking (|ft|<=mu*|fn|), apply the force
                 addForce(tangentialForce_);
             }
             else
             {
                 //if sliding, resize the tangential force such that |ft|=mu*|fn|
                 tangentialForce_ *= species->getSlidingFrictionCoefficient() * getAbsoluteNormalForce() /
                                     std::sqrt(tangentialForceSquared);
                 addForce(tangentialForce_);
                 //resize the tangential spring accordingly such ft=-k*delta-nu*relVel
                 slidingSpring_ = -(tangentialForce_ + species->getSlidingDissipation() * tangentialRelativeVelocity) /
                                  species->getSlidingStiffness();
             }
         }
         else //if no spring stiffness is set
         {
 //            if (species->getSlidingDissipation()==0.0)
 //            {
 //                std::cerr << "SlidingFrictionInteraction::getForce(): warning:  both sliding stiffness and dissipation are zero" << std::endl;
 //            }
             Mdouble tangentialRelativeVelocitySquared = tangentialRelativeVelocity.getLengthSquared();
             if (tangentialRelativeVelocitySquared * mathsFunc::square(species->getSlidingDissipation()) <=
                 mathsFunc::square(species->getSlidingFrictionCoefficientStatic() * getAbsoluteNormalForce()))
                 tangentialForce_ = -species->getSlidingDissipation() * tangentialRelativeVelocity;
             else //if sliding, set force to Coulomb limit
                 tangentialForce_ = -(species->getSlidingFrictionCoefficient() * getAbsoluteNormalForce() /
                                      std::sqrt(tangentialRelativeVelocitySquared)) * tangentialRelativeVelocity;
             addForce(tangentialForce_);
         }
     }
     /* And if species->getSlidingFrictionCoefficient() == 0.0, then there is no
      * friction force at all. */
 }
References BaseInteraction::addForce(), computeSlidingSpring(), BaseInteraction::getAbsoluteNormalForce(), BaseInteraction::getBaseSpecies(), BaseInteraction::getEffectiveMass(), SlidingFrictionSpecies::getIsSuperquadricSpecies(), Vec3D::getLengthSquared(), BaseInteraction::getNormal(), BaseInteraction::getNormalRelativeVelocity(), BaseInteraction::getRelativeVelocity(), SlidingFrictionSpecies::getSlidingDissipation(), SlidingFrictionSpecies::getSlidingFrictionCoefficient(), SlidingFrictionSpecies::getSlidingFrictionCoefficientStatic(), SlidingFrictionSpecies::getSlidingStiffness(), getSpecies(), isSuperQuadricInteraction_, slidingSpring_, sqrt(), mathsFunc::square(), and tangentialForce_.
Referenced by FrictionInteraction::computeFrictionForce().
computeSlidingSpring()
void SlidingFrictionInteraction::computeSlidingSpring (const Vec3D & tangentialRelativeVelocity)
 {
     // Calculating the tangential spring using Luding, S. (2008) eq. (17)
     const Mdouble springLength = slidingSpring_.getLength();
     if (springLength > 1e-10)
     {
         slidingSpring_ -= Vec3D::dot(slidingSpring_, getNormal()) * getNormal();
         slidingSpring_ *= springLength / slidingSpring_.getLength();
         // Check length
         logger.assert_debug(std::abs(slidingSpring_.getLength() - springLength) < 1e-10 * springLength, "SlidingFrictionInteraction::computeSlidingSpring: Spring length not the same after rotation (before = %, after = %)", springLength, slidingSpring_.getLength());
         // Check orthogonality
         logger.assert_debug(std::abs(Vec3D::dot(slidingSpring_, getNormal())) < 1e-10 * springLength, "SlidingFrictionInteraction::computeSlidingSpring: sliding spring not perpendicular to normal (after rotation)");
     }
     // integrate(getHandler()->timeStep_);
     slidingSpringVelocity_ = tangentialRelativeVelocity;
     slidingSpring_ += slidingSpringVelocity_ * getHandler()->getDPMBase()->getTimeStep();
 }
References abs(), Vec3D::dot(), e(), BaseHandler< T >::getDPMBase(), BaseInteraction::getHandler(), Vec3D::getLength(), BaseInteraction::getNormal(), DPMBase::getTimeStep(), logger, slidingSpring_, and slidingSpringVelocity_.
Referenced by computeFrictionForce().
getBaseName()
std::string SlidingFrictionInteraction::getBaseName () const
Returns the type/name of interaction (sliding friction interaction)
Returns
std::string
 {
     return "SlidingFriction";
 }
getElasticEnergy()
Mdouble SlidingFrictionInteraction::getElasticEnergy () const override virtual
Returns the amount of elastic energy stored in sliding spring.
Returns
Mdouble
Reimplemented from BaseInteraction.
 {
     if (getBaseSpecies()->getNormalForce()->getConstantRestitution()) {
         return getEffectiveMass() * getSpecies()->getSlidingStiffness() * slidingSpring_.getLengthSquared();
     } else {
         return 0.5 * getSpecies()->getSlidingStiffness() * slidingSpring_.getLengthSquared();
     }
 }
References BaseInteraction::getBaseSpecies(), BaseInteraction::getEffectiveMass(), Vec3D::getLengthSquared(), SlidingFrictionSpecies::getSlidingStiffness(), getSpecies(), and slidingSpring_.
Referenced by FrictionInteraction::getElasticEnergy().
getSlidingSpring()
Vec3D SlidingFrictionInteraction::getSlidingSpring () const
 {
     return slidingSpring_;
 }
References slidingSpring_.
getSpecies()
const SlidingFrictionSpecies * SlidingFrictionInteraction::getSpecies () const
Returns a const pointer of type SlidingFrictionSpecies*.
Returns
const SlidingFrictionSpecies*
 {
     return static_cast<const SlidingFrictionSpecies*>(getBaseSpecies()->getFrictionForce());
 ;
 }
References BaseInteraction::getBaseSpecies(), and BaseSpecies::getFrictionForce().
Referenced by computeFrictionForce(), and getElasticEnergy().
getTangentialForce()
const Vec3D SlidingFrictionInteraction::getTangentialForce () const override virtual
Returns the sliding friction force vector.
Returns
const Vec3D
Reimplemented from BaseInteraction.
 {
     return tangentialForce_;
 }
References tangentialForce_.
getTangentialOverlap()
Mdouble SlidingFrictionInteraction::getTangentialOverlap () const override virtual
Returns the amount of tangential overlap which is needed by BaseInteraction::writeToFstat().
Returns
Mdouble
Todo:
TWnow this should be positive
Reimplemented from BaseInteraction.
 {
     return -slidingSpring_.getLength();
 }
References Vec3D::getLength(), and slidingSpring_.
integrate()
void SlidingFrictionInteraction::integrate (Mdouble timeStep) override virtual
Increments the amount of compression in sliding spring.
Parameters
[in] timeStep the dt
Reimplemented from BaseInteraction.
 {
     slidingSpring_ += slidingSpringVelocity_ * timeStep;
 }
References slidingSpring_, and slidingSpringVelocity_.
Referenced by FrictionInteraction::integrate().
moveSlidingSpring()
void SlidingFrictionInteraction::moveSlidingSpring (Vec3D displacement)
 {
     slidingSpring_ += displacement;
 }
References slidingSpring_.
read()
void SlidingFrictionInteraction::read (std::istream & is) override virtual
Interaction read function, which accepts an std::istream as input.
Parameters
[in,out] is
Reimplemented from BaseInteraction.
 {
     //BaseInteraction::read(is);
     std::string dummy;
     is >> dummy >> slidingSpring_;
 }
References slidingSpring_, and oomph::Global_string_for_annotation::string().
Referenced by FrictionInteraction::read().
reverseHistory()
void SlidingFrictionInteraction::reverseHistory () override virtual
A useful feature if one wants to return to the initial state of the spring. However, reverse history decrements the current state to the state corresponding to previous time step. Decrements the value of slidingSpring_.
Reimplemented from BaseInteraction.
 {
     slidingSpring_ = -slidingSpring_;
     slidingSpringVelocity_ = -slidingSpringVelocity_;
     tangentialForce_ = -tangentialForce_;
 }
References slidingSpring_, slidingSpringVelocity_, and tangentialForce_.
Referenced by FrictionInteraction::reverseHistory().
rotateHistory()
void SlidingFrictionInteraction::rotateHistory (Matrix3D & rotationMatrix) override virtual
When periodic particles are used, some interactions need certain history properties rotated (e.g. tangential springs). This is the function for that.
Todo:
some of these might be unneccesary
Reimplemented from BaseInteraction.
 {
     slidingSpring_ = rotationMatrix * slidingSpring_;
     slidingSpringVelocity_ = rotationMatrix * slidingSpringVelocity_;
     tangentialForce_ = rotationMatrix * tangentialForce_;
 }
References slidingSpring_, slidingSpringVelocity_, and tangentialForce_.
Referenced by FrictionInteraction::rotateHistory().
setIsSuperQuadricInteraction()
void SlidingFrictionInteraction::setIsSuperQuadricInteraction (bool isSuperQuadricInteraction)
 {
     isSuperQuadricInteraction_ = isSuperQuadricInteraction;
 }
References isSuperQuadricInteraction_.
setSlidingSpring()
void SlidingFrictionInteraction::setSlidingSpring (Vec3D slidingSpring)
Bug:
may need to remove the consts
 {
     slidingSpring_ = slidingSpring;
 }
References slidingSpring_.
write()
void SlidingFrictionInteraction::write (std::ostream & os) const override virtual
Interaction write function, which accepts an std::ostream as input.
Parameters
[in,out] os
Reimplemented from BaseInteraction.
 {
     //BaseInteraction::write(os);
     os << " slidingSpring " << slidingSpring_;
 }
References slidingSpring_.
Referenced by FrictionInteraction::write().
Member Data Documentation
isSuperQuadricInteraction_
bool SlidingFrictionInteraction::isSuperQuadricInteraction_ protected
Referenced by computeFrictionForce(), setIsSuperQuadricInteraction(), and SlidingFrictionInteraction().
slidingSpring_
Vec3D SlidingFrictionInteraction::slidingSpring_ protected
Stores the amount of sliding spring (\(\delta\)) compression from the expression \(f_t=-k*\delta-\nu*relVel\). Set in the member function integrate(), used in computeFrictionForce().
Referenced by computeFrictionForce(), computeSlidingSpring(), getElasticEnergy(), getSlidingSpring(), getTangentialOverlap(), integrate(), moveSlidingSpring(), read(), reverseHistory(), rotateHistory(), setSlidingSpring(), SlidingFrictionInteraction(), and write().
slidingSpringVelocity_
Vec3D SlidingFrictionInteraction::slidingSpringVelocity_ protected
Stores the rate at which the sliding spring compressed or relaxed. Set in the member function computeFrictionForce() and used in integrate().
Referenced by computeSlidingSpring(), integrate(), reverseHistory(), and rotateHistory().
tangentialForce_
Vec3D SlidingFrictionInteraction::tangentialForce_ protected
Computes the tangential force such that \(|f_t|=\mu*|f_n|\). Set and computed in computeFrictionForce().
Referenced by addTangentialForce(), computeFrictionForce(), getTangentialForce(), reverseHistory(), and rotateHistory().
The documentation for this class was generated from the following files:
SlidingFrictionInteraction.h
SlidingFrictionInteraction.cc