MercuryDPM: Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType > Class Template Reference
Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Generic expression of a matrix where all coefficients are defined by a functor.
#include <CwiseNullaryOp.h>
Public Types
typedef internal::dense_xpr_base< CwiseNullaryOp >::type Base
Public Member Functions
EIGEN_DEVICE_FUNC CwiseNullaryOp (Index rows, Index cols, const NullaryOp &func=NullaryOp())
EIGEN_DEVICE_FUNC CwiseNullaryOp (Index size, const NullaryOp &func=NullaryOp())
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index rows () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index cols () const
EIGEN_DEVICE_FUNC const NullaryOp & functor () const
Protected Attributes
const internal::variable_if_dynamic< Index, RowsAtCompileTime > m_rows
const internal::variable_if_dynamic< Index, ColsAtCompileTime > m_cols
const NullaryOp m_functor
Detailed Description
template<typename NullaryOp, typename PlainObjectType>
class Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >
Generic expression of a matrix where all coefficients are defined by a functor.
Template Parameters
NullaryOp template functor implementing the operator
PlainObjectType the underlying plain matrix/array type
This class represents an expression of a generic nullary operator. It is the return type of the Ones(), Zero(), Constant(), Identity() and Random() methods, and most of the time this is the only way it is used.
However, if you want to write a function returning such an expression, you will need to use this class.
The functor NullaryOp must expose one of the following method:
operator()() if the procedural generation does not depend on the coefficient entries (e.g., random numbers)
operator()(Index i) if the procedural generation makes sense for vectors only and that it depends on the coefficient index i (e.g., linspace)
operator()(Index i,Index j) if the procedural generation depends on the matrix coordinates i, j (e.g., to generate a checkerboard with 0 and 1)
It is also possible to expose the last two operators if the generation makes sense for matrices but can be optimized for vectors.
See DenseBase::NullaryExpr(Index,const CustomNullaryOp&) for an example binding C++11 random number generators.
A nullary expression can also be used to implement custom sophisticated matrix manipulations that cannot be covered by the existing set of natively supported matrix manipulations. See this page for some examples and additional explanations on the behavior of CwiseNullaryOp.
See also
class CwiseUnaryOp, class CwiseBinaryOp, DenseBase::NullaryExpr
Member Typedef Documentation
Base
template<typename NullaryOp , typename PlainObjectType > typedef internal::dense_xpr_base<CwiseNullaryOp>::type Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::Base
Constructor & Destructor Documentation
CwiseNullaryOp() [1/2]
template<typename NullaryOp , typename PlainObjectType > EIGEN_DEVICE_FUNC Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::CwiseNullaryOp (Index rows, Index cols, const NullaryOp & func = NullaryOp()) inline
       : m_rows(rows), m_cols(cols), m_functor(func) {
     eigen_assert(rows >= 0 && (RowsAtCompileTime == Dynamic || RowsAtCompileTime == rows) && cols >= 0 &&
                  (ColsAtCompileTime == Dynamic || ColsAtCompileTime == cols));
   }
References Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::cols(), Eigen::Dynamic, eigen_assert, and Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::rows().
CwiseNullaryOp() [2/2]
template<typename NullaryOp , typename PlainObjectType > EIGEN_DEVICE_FUNC Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::CwiseNullaryOp (Index size, const NullaryOp & func = NullaryOp()) inline
       : CwiseNullaryOp(RowsAtCompileTime == 1 ? 1 : size, RowsAtCompileTime == 1 ? size : 1, func) {
     EIGEN_STATIC_ASSERT(CwiseNullaryOp::IsVectorAtCompileTime, YOU_TRIED_CALLING_A_VECTOR_METHOD_ON_A_MATRIX);
   }
References EIGEN_STATIC_ASSERT.
Member Function Documentation
cols()
template<typename NullaryOp , typename PlainObjectType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::cols () const inline
 { return m_cols.value(); }
References Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::m_cols, and Eigen::internal::variable_if_dynamic< T, Value >::value().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::CwiseNullaryOp(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
functor()
template<typename NullaryOp , typename PlainObjectType > EIGEN_DEVICE_FUNC const NullaryOp& Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::functor () const inline
Returns
the functor representing the nullary operation
 { return m_functor; }
References Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::m_functor.
rows()
template<typename NullaryOp , typename PlainObjectType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::rows () const inline
 { return m_rows.value(); }
References Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::m_rows, and Eigen::internal::variable_if_dynamic< T, Value >::value().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::CwiseNullaryOp(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_cols
template<typename NullaryOp , typename PlainObjectType > const internal::variable_if_dynamic<Index, ColsAtCompileTime> Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::m_cols protected
Referenced by Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::cols().
m_functor
template<typename NullaryOp , typename PlainObjectType > const NullaryOp Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::m_functor protected
Referenced by Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::functor().
m_rows
template<typename NullaryOp , typename PlainObjectType > const internal::variable_if_dynamic<Index, RowsAtCompileTime> Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::m_rows protected
Referenced by Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::rows().
The documentation for this class was generated from the following file:
CwiseNullaryOp.h