MercuryDPM: Eigen::internal::TridiagonalizationMatrixTReturnType< MatrixType > Struct Template Reference
Eigen::internal::TridiagonalizationMatrixTReturnType< MatrixType > Struct Template Reference
Dense linear problems and decompositions » Reference » Eigenvalues_Module
Expression type for return value of Tridiagonalization::matrixT()
#include <Tridiagonalization.h>
Public Member Functions
TridiagonalizationMatrixTReturnType (const MatrixType &mat)
Constructor.
template<typename ResultType >
void evalTo (ResultType &result) const
EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
Public Member Functions inherited from Eigen::ReturnByValue< TridiagonalizationMatrixTReturnType< MatrixType > >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Protected Attributes
MatrixType::Nested m_matrix
Additional Inherited Members
Public Types inherited from Eigen::ReturnByValue< TridiagonalizationMatrixTReturnType< MatrixType > >
typedef internal::traits< TridiagonalizationMatrixTReturnType< MatrixType > >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Detailed Description
template<typename MatrixType>
struct Eigen::internal::TridiagonalizationMatrixTReturnType< MatrixType >
Expression type for return value of Tridiagonalization::matrixT()
\eigenvalues_module
Template Parameters
MatrixType type of underlying dense matrix
Constructor & Destructor Documentation
TridiagonalizationMatrixTReturnType()
template<typename MatrixType > Eigen::internal::TridiagonalizationMatrixTReturnType< MatrixType >::TridiagonalizationMatrixTReturnType (const MatrixType & mat) inline
Constructor.
Parameters
[in] mat The underlying dense matrix
 : m_matrix(mat) {}
Member Function Documentation
cols()
template<typename MatrixType > EIGEN_CONSTEXPR Index Eigen::internal::TridiagonalizationMatrixTReturnType< MatrixType >::cols () const inline
 { return m_matrix.cols(); }
References Eigen::internal::TridiagonalizationMatrixTReturnType< MatrixType >::m_matrix.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
evalTo()
template<typename MatrixType > template<typename ResultType > void Eigen::internal::TridiagonalizationMatrixTReturnType< MatrixType >::evalTo (ResultType & result) const inline
{
     result.setZero();
     result.template diagonal<1>() = m_matrix.template diagonal<-1>().conjugate();
     result.diagonal() = m_matrix.diagonal();
     result.template diagonal<-1>() = m_matrix.template diagonal<-1>();
   }
References diagonal(), and Eigen::internal::TridiagonalizationMatrixTReturnType< MatrixType >::m_matrix.
rows()
template<typename MatrixType > EIGEN_CONSTEXPR Index Eigen::internal::TridiagonalizationMatrixTReturnType< MatrixType >::rows () const inline
 { return m_matrix.rows(); }
References Eigen::internal::TridiagonalizationMatrixTReturnType< MatrixType >::m_matrix.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_matrix
template<typename MatrixType > MatrixType::Nested Eigen::internal::TridiagonalizationMatrixTReturnType< MatrixType >::m_matrix protected
Referenced by Eigen::internal::TridiagonalizationMatrixTReturnType< MatrixType >::cols(), Eigen::internal::TridiagonalizationMatrixTReturnType< MatrixType >::evalTo(), and Eigen::internal::TridiagonalizationMatrixTReturnType< MatrixType >::rows().
The documentation for this struct was generated from the following file:
Tridiagonalization.h