MercuryDPM: llt.cpp File Reference
llt.cpp File Reference
#include "gemm_common.h"
#include <Eigen/Cholesky>
Functions
EIGEN_DONT_INLINE void llt (const Mat &A, const Mat &B, Mat &C)
int main (int argc, char **argv)
Function Documentation
llt()
EIGEN_DONT_INLINE void llt (const Mat & A, const Mat & B, Mat & C)
{
   C = A;
   C.diagonal().array() += 1000;
   Eigen::internal::llt_inplace<Mat::Scalar, Lower>::blocked(C);
 }
Referenced by bench(), cholesky_verify_assert(), EIGEN_DECLARE_TEST(), and main().
main()
int main (int argc , char ** argv)
 { return main_gemm(argc, argv, llt); }
References llt(), and main_gemm().