MercuryDPM: Eigen::general_product_to_triangular_selector< MatrixType, ProductType, UpLo, true > Struct Template Reference
Eigen::general_product_to_triangular_selector< MatrixType, ProductType, UpLo, true > Struct Template Reference
#include <GeneralMatrixMatrixTriangular.h>
Static Public Member Functions
static void run (MatrixType &mat, const ProductType &prod, const typename MatrixType::Scalar &alpha, bool beta)
Member Function Documentation
run()
template<typename MatrixType , typename ProductType , int UpLo> static void Eigen::general_product_to_triangular_selector< MatrixType, ProductType, UpLo, true >::run (MatrixType & mat, const ProductType & prod, const typename MatrixType::Scalar & alpha, bool beta) inline static
{
     typedef typename MatrixType::Scalar Scalar;
     typedef internal::remove_all_t<typename ProductType::LhsNested> Lhs;
     typedef internal::blas_traits<Lhs> LhsBlasTraits;
     typedef typename LhsBlasTraits::DirectLinearAccessType ActualLhs;
     typedef internal::remove_all_t<ActualLhs> ActualLhs_;
     internal::add_const_on_value_type_t<ActualLhs> actualLhs = LhsBlasTraits::extract(prod.lhs());
     typedef internal::remove_all_t<typename ProductType::RhsNested> Rhs;
     typedef internal::blas_traits<Rhs> RhsBlasTraits;
     typedef typename RhsBlasTraits::DirectLinearAccessType ActualRhs;
     typedef internal::remove_all_t<ActualRhs> ActualRhs_;
     internal::add_const_on_value_type_t<ActualRhs> actualRhs = RhsBlasTraits::extract(prod.rhs());
     Scalar actualAlpha = alpha * LhsBlasTraits::extractScalarFactor(prod.lhs().derived()) *
                          RhsBlasTraits::extractScalarFactor(prod.rhs().derived());
     if (!beta) mat.template triangularView<UpLo>().setZero();
     enum {
       StorageOrder = (internal::traits<MatrixType>::Flags & RowMajorBit) ? RowMajor : ColMajor,
       UseLhsDirectly = ActualLhs_::InnerStrideAtCompileTime == 1,
       UseRhsDirectly = ActualRhs_::InnerStrideAtCompileTime == 1
     };
     internal::gemv_static_vector_if<Scalar, Lhs::SizeAtCompileTime, Lhs::MaxSizeAtCompileTime, !UseLhsDirectly>
         static_lhs;
     ei_declare_aligned_stack_constructed_variable(
         Scalar, actualLhsPtr, actualLhs.size(),
         (UseLhsDirectly ? const_cast<Scalar*>(actualLhs.data()) : static_lhs.data()));
     if (!UseLhsDirectly) Map<typename ActualLhs_::PlainObject>(actualLhsPtr, actualLhs.size()) = actualLhs;
     internal::gemv_static_vector_if<Scalar, Rhs::SizeAtCompileTime, Rhs::MaxSizeAtCompileTime, !UseRhsDirectly>
         static_rhs;
     ei_declare_aligned_stack_constructed_variable(
         Scalar, actualRhsPtr, actualRhs.size(),
         (UseRhsDirectly ? const_cast<Scalar*>(actualRhs.data()) : static_rhs.data()));
     if (!UseRhsDirectly) Map<typename ActualRhs_::PlainObject>(actualRhsPtr, actualRhs.size()) = actualRhs;
     selfadjoint_rank1_update<
         Scalar, Index, StorageOrder, UpLo, LhsBlasTraits::NeedToConjugate && NumTraits<Scalar>::IsComplex,
         RhsBlasTraits::NeedToConjugate && NumTraits<Scalar>::IsComplex>::run(actualLhs.size(), mat.data(),
                                                                              mat.outerStride(), actualLhsPtr,
                                                                              actualRhsPtr, actualAlpha);
   }
References alpha, beta, Eigen::ColMajor, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::data(), ei_declare_aligned_stack_constructed_variable, Eigen::Product< Lhs_, Rhs_, Option >::lhs(), Eigen::internal::Lhs, Eigen::prod(), Eigen::Product< Lhs_, Rhs_, Option >::rhs(), Eigen::internal::Rhs, Eigen::RowMajor, Eigen::RowMajorBit, Eigen::run(), and Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::setZero().
The documentation for this struct was generated from the following file:
GeneralMatrixMatrixTriangular.h