MercuryDPM: Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, isInt > Struct Template Reference
Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, isInt > Struct Template Reference
#include <Visitor.h>
Public Types
using Scalar = typename Derived::Scalar
using Packet = typename packet_traits< Scalar >::type
using Comparator = minmax_compare< Scalar, NaNPropagation, is_min >
Public Types inherited from Eigen::internal::coeff_visitor< Derived >
typedef Derived::Scalar Scalar
Public Member Functions
EIGEN_DEVICE_FUNC void operator() (const Scalar &value, Index i, Index j)
EIGEN_DEVICE_FUNC void packet (const Packet &p, Index i, Index j)
EIGEN_DEVICE_FUNC void initpacket (const Packet &p, Index i, Index j)
Public Member Functions inherited from Eigen::internal::coeff_visitor< Derived >
EIGEN_DEVICE_FUNC coeff_visitor ()
EIGEN_DEVICE_FUNC void init (const Scalar &value, Index i, Index j)
Static Public Attributes
static constexpr Index PacketSize = packet_traits<Scalar>::size
Additional Inherited Members
Public Attributes inherited from Eigen::internal::coeff_visitor< Derived >
Index row
Index col
Scalar res
Member Typedef Documentation
Comparator
template<typename Derived , bool is_min, int NaNPropagation, bool isInt = NumTraits<typename Derived::Scalar>::IsInteger> using Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, isInt >::Comparator = minmax_compare<Scalar, NaNPropagation, is_min>
Packet
template<typename Derived , bool is_min, int NaNPropagation, bool isInt = NumTraits<typename Derived::Scalar>::IsInteger> using Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, isInt >::Packet = typename packet_traits<Scalar>::type
Scalar
template<typename Derived , bool is_min, int NaNPropagation, bool isInt = NumTraits<typename Derived::Scalar>::IsInteger> using Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, isInt >::Scalar = typename Derived::Scalar
Member Function Documentation
initpacket()
template<typename Derived , bool is_min, int NaNPropagation, bool isInt = NumTraits<typename Derived::Scalar>::IsInteger> EIGEN_DEVICE_FUNC void Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, isInt >::initpacket (const Packet & p, Index i, Index j) inline
{
     Scalar value = Comparator::predux(p);
     const Packet range = preverse(plset<Packet>(Scalar(1)));
     Packet mask = pcmp_eq(pset1<Packet>(value), p);
     Index max_idx = PacketSize - static_cast<Index>(predux_max(pand(range, mask)));
     this->res = value;
     this->row = Derived::IsRowMajor ? i : i + max_idx;
     this->col = Derived::IsRowMajor ? j + max_idx : j;
   }
References Eigen::internal::coeff_visitor< Derived >::col, i, j, p, Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, isInt >::PacketSize, Eigen::internal::pand(), Eigen::internal::pcmp_eq(), Eigen::internal::minmax_compare< Scalar, NaNPropagation, is_min >::predux(), Eigen::internal::predux_max(), Eigen::internal::preverse(), Eigen::internal::coeff_visitor< Derived >::res, Eigen::internal::coeff_visitor< Derived >::row, and Eigen::value.
operator()()
template<typename Derived , bool is_min, int NaNPropagation, bool isInt = NumTraits<typename Derived::Scalar>::IsInteger> EIGEN_DEVICE_FUNC void Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, isInt >::operator() (const Scalar & value, Index i, Index j) inline
{
     if (Comparator::compare(value, this->res)) {
       this->res = value;
       this->row = i;
       this->col = j;
     }
   }
References Eigen::internal::coeff_visitor< Derived >::col, Eigen::internal::minmax_compare< Scalar, NaNPropagation, is_min >::compare(), i, j, Eigen::internal::coeff_visitor< Derived >::res, Eigen::internal::coeff_visitor< Derived >::row, and Eigen::value.
packet()
template<typename Derived , bool is_min, int NaNPropagation, bool isInt = NumTraits<typename Derived::Scalar>::IsInteger> EIGEN_DEVICE_FUNC void Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, isInt >::packet (const Packet & p, Index i, Index j) inline
{
     Scalar value = Comparator::predux(p);
     if (Comparator::compare(value, this->res)) {
       const Packet range = preverse(plset<Packet>(Scalar(1)));
       Packet mask = pcmp_eq(pset1<Packet>(value), p);
       Index max_idx = PacketSize - static_cast<Index>(predux_max(pand(range, mask)));
       this->res = value;
       this->row = Derived::IsRowMajor ? i : i + max_idx;
       this->col = Derived::IsRowMajor ? j + max_idx : j;
     }
   }
References p, Eigen::internal::minmax_compare< Scalar, NaNPropagation, is_min >::predux(), and Eigen::value.
Member Data Documentation
PacketSize
template<typename Derived , bool is_min, int NaNPropagation, bool isInt = NumTraits<typename Derived::Scalar>::IsInteger> constexpr Index Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, isInt >::PacketSize = packet_traits<Scalar>::size static constexpr
Referenced by Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, isInt >::initpacket(), Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, false >::initpacket(), Eigen::internal::minmax_coeff_visitor< Derived, is_min, PropagateNumbers, false >::packet(), and Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, false >::packet().
The documentation for this struct was generated from the following file:
Visitor.h