MercuryDPM: oomph::OneDimensionalLegendreDShape< NNODE_1D > Class Template Reference
oomph::OneDimensionalLegendreDShape< NNODE_1D > Class Template Reference
#include <shape.h>
Public Member Functions
OneDimensionalLegendreDShape (const double &s)
Public Member Functions inherited from oomph::Shape
Shape (const unsigned &N)
Constructor for a single-index set of shape functions.
Shape (const unsigned &N, const unsigned &M)
Constructor for a two-index set of shape functions.
Shape (const Shape &shape)=delete
Broken copy constructor.
Shape ()
void operator= (const Shape &shape)
void operator= (Shape *const &shape_pt)
~Shape ()
Destructor, clear up the memory allocated by the object.
void resize (const unsigned &N, const unsigned &M=1)
Change the size of the storage.
double & operator[] (const unsigned &i)
Overload the bracket operator to provide access to values.
const double & operator[] (const unsigned &i) const
Overload the bracket operator (const version)
double & operator() (const unsigned &i)
Overload the round bracket operator to provide access to values.
const double & operator() (const unsigned &i) const
Overload the round bracket operator (const version)
double & operator() (const unsigned &i, const unsigned &j)
Overload the round bracket operator, allowing for two indices.
const double & operator() (const unsigned &i, const unsigned &j) const
unsigned nindex1 () const
Return the range of index 1 of the shape function object.
unsigned nindex2 () const
Return the range of index 2 of the shape function object.
Additional Inherited Members
Protected Member Functions inherited from oomph::Shape
void range_check (const unsigned &i, const unsigned &j) const
Private function that checks whether the index is in range.
Protected Attributes inherited from oomph::Shape
double * Psi
double * Allocated_storage
unsigned Index1
Size of the first index of the shape function.
unsigned Index2
Size of the second index of the shape function.
Constructor & Destructor Documentation
OneDimensionalLegendreDShape()
template<unsigned NNODE_1D> oomph::OneDimensionalLegendreDShape< NNODE_1D >::OneDimensionalLegendreDShape (const double & s) inline
                                                   : Shape(NNODE_1D)
     {
       unsigned p = NNODE_1D - 1;
       Vector<double> z = OneDimensionalLegendreShape<NNODE_1D>::z;
       bool root = false;
       for (unsigned i = 0; i < NNODE_1D; i++)
       {
         unsigned rootnum = 0;
         for (unsigned j = 0; j < NNODE_1D; j++)
         { // Loop over roots to check if
           if (std::fabs(s - z[j]) < 10 * Orthpoly::eps)
           { // s happens to be a root.
             root = true;
             break;
           }
           rootnum += 1;
         }
         if (root == true)
         {
           if (i == rootnum && i == 0)
           {
             (*this)[i] = -(1.0 + p) * p / 4.0;
           }
           else if (i == rootnum && i == p)
           {
             (*this)[i] = (1.0 + p) * p / 4.0;
           }
           else if (i == rootnum)
           {
             (*this)[i] = 0.0;
           }
           else
           {
             (*this)[i] = Orthpoly::legendre(p, z[rootnum]) /
                          Orthpoly::legendre(p, z[i]) / (z[rootnum] - z[i]);
           }
         }
         else
         {
           (*this)[i] =
             ((1 + s * (s - 2 * z[i])) / (s - z[i]) * Orthpoly::dlegendre(p, s) -
              (1 - s * s) * Orthpoly::ddlegendre(p, s)) /
             p / (p + 1.0) / Orthpoly::legendre(p, z[i]) / (s - z[i]);
         }
         root = false;
       }
     }
References oomph::Orthpoly::ddlegendre(), oomph::Orthpoly::dlegendre(), oomph::Orthpoly::eps, boost::multiprecision::fabs(), i, j, oomph::Orthpoly::legendre(), p, s, and oomph::OneDimensionalLegendreShape< NNODE_1D >::z.
The documentation for this class was generated from the following file:
shape.h