MercuryDPM: cylinder.cc File Reference
axisym_linear_elasticity/cylinder/cylinder.cc File Reference
#include <fenv.h>
#include "generic.h"
#include "axisym_linear_elasticity.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >
Namespaces
Global_Parameters
Namespace for global parameters.
Functions
void Global_Parameters::boundary_traction (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result)
The traction function at r=Rmin: (t_r, t_z, t_theta)
void Global_Parameters::body_force (const double &time, const Vector< double > &x, Vector< double > &result)
void Global_Parameters::exact_solution_th (const Vector< double > &x, Vector< double > &u)
double Global_Parameters::u_r (const double &time, const Vector< double > &x)
Calculate the time dependent form of the r-component of displacement.
double Global_Parameters::u_z (const double &time, const Vector< double > &x)
Calculate the time dependent form of the z-component of displacement.
double Global_Parameters::u_theta (const double &time, const Vector< double > &x)
Calculate the time dependent form of the theta-component of displacement.
double Global_Parameters::d_u_r_dt (const double &time, const Vector< double > &x)
Calculate the time dependent form of the r-component of velocity.
double Global_Parameters::d_u_z_dt (const double &time, const Vector< double > &x)
Calculate the time dependent form of the z-component of velocity.
double Global_Parameters::d_u_theta_dt (const double &time, const Vector< double > &x)
Calculate the time dependent form of the theta-component of velocity.
double Global_Parameters::d2_u_r_dt2 (const double &time, const Vector< double > &x)
Calculate the time dependent form of the r-component of acceleration.
double Global_Parameters::d2_u_z_dt2 (const double &time, const Vector< double > &x)
Calculate the time dependent form of the z-component of acceleration.
double Global_Parameters::d2_u_theta_dt2 (const double &time, const Vector< double > &x)
Calculate the time dependent form of the theta-component of acceleration.
void Global_Parameters::exact_solution (const double &time, const Vector< double > &x, Vector< double > &u)
int main (int argc, char *argv[])
Driver code.
Variables
double Global_Parameters::Nu = 0.3
Define Poisson's ratio Nu.
double Global_Parameters::E = 1.0
Define the non-dimensional Young's modulus.
double Global_Parameters::Lambda = E*Nu/(1.0+Nu)/(1.0-2.0*Nu)
Lame parameters.
double Global_Parameters::Mu = E/2.0/(1.0+Nu)
double Global_Parameters::Omega_sq = 0.5
Square of the frequency of the time dependence.
unsigned Global_Parameters::Nr = 5
Number of elements in r-direction.
unsigned Global_Parameters::Nz = 10
Number of elements in z-direction.
double Global_Parameters::Lr = 1.0
Length of domain in r direction.
double Global_Parameters::Lz = 2.0
Length of domain in z-direction.
double Global_Parameters::Rmin = 0.1
Set up min r coordinate.
double Global_Parameters::Zmin = 0.3
Set up min z coordinate.
double Global_Parameters::Rmax = Rmin+Lr
Set up max r coordinate.
double Global_Parameters::Zmax = Zmin+Lz
Set up max z coordinate.
Function Documentation
main()
int main (int argc , char * argv[])
Driver code.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Validation?
  CommandLineArgs::specify_command_line_flag("--validation");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Set up doc info
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory("RESLT");
  // Time dependent problem instance
  AxisymmetricLinearElasticityProblem
   <QAxisymmetricLinearElasticityElement<3>, Newmark<1> > problem;
  // Set the initial time to t=0
  problem.time_pt()->time()=0.0;
  // Set and initialise timestep
  double dt=0;
  // If we're validating, use a larger timestep so that we can do fewer steps
  // before reaching interesting behaviour
  if(CommandLineArgs::command_line_flag_has_been_set("--validation"))
   {
    dt=0.1;
   }
  else // Otherwise use a small timestep
   {
    dt=0.01;
   }
  problem.time_pt()->initialise_dt(dt);
  // Set the initial conditions
  problem.set_initial_conditions();
  // Doc the initial conditions and increment the doc_info number
  problem.doc_solution(doc_info);
  doc_info.number()++;
  // Find the number of timesteps to perform
  unsigned nstep=0;
  // If we're validating, only do a few timesteps; otherwise do a whole period
  if(CommandLineArgs::command_line_flag_has_been_set("--validation"))
   {
    nstep=5;
   }
  else // Otherwise calculate based on timestep
   {
    // Solve for one full period
    double t_max=2*MathematicalConstants::Pi;
    nstep=unsigned(t_max/dt);
   } //end_of_calculate_number_of_timesteps
  // Do the timestepping
  for(unsigned istep=0;istep<nstep;istep++)
   {
    // Solve for this timestep
    problem.unsteady_newton_solve(dt);
    // Doc the solution and increment doc_info number
    problem.doc_solution(doc_info);
    doc_info.number()++;
   }
 } // end_of_main
References oomph::CommandLineArgs::command_line_flag_has_been_set(), oomph::CommandLineArgs::doc_specified_flags(), oomph::DocInfo::number(), oomph::CommandLineArgs::parse_and_assign(), BiharmonicTestFunctions2::Pi, problem, oomph::DocInfo::set_directory(), Flag_definition::setup(), and oomph::CommandLineArgs::specify_command_line_flag().