MercuryDPM: Eigen::COLAMDOrdering< StorageIndex > Class Template Reference
Eigen::COLAMDOrdering< StorageIndex > Class Template Reference
Sparse linear algebra » Reference » OrderingMethods_Module
#include <Ordering.h>
Public Types
typedef PermutationMatrix< Dynamic, Dynamic, StorageIndex > PermutationType
typedef Matrix< StorageIndex, Dynamic, 1 > IndexVector
Public Member Functions
template<typename MatrixType >
void operator() (const MatrixType &mat, PermutationType &perm)
Detailed Description
template<typename StorageIndex>
class Eigen::COLAMDOrdering< StorageIndex >
Template Parameters
StorageIndex The type of indices of the matrix
Functor computing the column approximate minimum degree ordering The matrix should be in column-major and compressed format (see SparseMatrix::makeCompressed()).
Member Typedef Documentation
IndexVector
template<typename StorageIndex > typedef Matrix<StorageIndex, Dynamic, 1> Eigen::COLAMDOrdering< StorageIndex >::IndexVector
PermutationType
template<typename StorageIndex > typedef PermutationMatrix<Dynamic, Dynamic, StorageIndex> Eigen::COLAMDOrdering< StorageIndex >::PermutationType
Member Function Documentation
operator()()
template<typename StorageIndex > template<typename MatrixType > void Eigen::COLAMDOrdering< StorageIndex >::operator() (const MatrixType & mat, PermutationType & perm) inline
Compute the permutation vector perm form the sparse matrix mat
Warning
The input sparse matrix mat must be in compressed mode (see SparseMatrix::makeCompressed()).
{
     eigen_assert(mat.isCompressed() &&
                  "COLAMDOrdering requires a sparse matrix in compressed mode. Call .makeCompressed() before passing it "
                  "to COLAMDOrdering");
     StorageIndex m = StorageIndex(mat.rows());
     StorageIndex n = StorageIndex(mat.cols());
     StorageIndex nnz = StorageIndex(mat.nonZeros());
     // Get the recommended value of Alen to be used by colamd
     StorageIndex Alen = internal::Colamd::recommended(nnz, m, n);
     // Set the default parameters
     double knobs[internal::Colamd::NKnobs];
     StorageIndex stats[internal::Colamd::NStats];
     internal::Colamd::set_defaults(knobs);
     IndexVector p(n + 1), A(Alen);
     for (StorageIndex i = 0; i <= n; i++) p(i) = mat.outerIndexPtr()[i];
     for (StorageIndex i = 0; i < nnz; i++) A(i) = mat.innerIndexPtr()[i];
     // Call Colamd routine to compute the ordering
     StorageIndex info = internal::Colamd::compute_ordering(m, n, Alen, A.data(), p.data(), knobs, stats);
     EIGEN_UNUSED_VARIABLE(info);
     eigen_assert(info && "COLAMD failed ");
     perm.resize(n);
     for (StorageIndex i = 0; i < n; i++) perm.indices()(p(i)) = i;
   }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::cols(), internal::Colamd::compute_ordering(), Eigen::PlainObjectBase< Derived >::data(), eigen_assert, EIGEN_UNUSED_VARIABLE, i, Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::indices(), info, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::innerIndexPtr(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::isCompressed(), m, n, internal::Colamd::NKnobs, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::nonZeros(), internal::Colamd::NStats, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::outerIndexPtr(), p, internal::Colamd::recommended(), Eigen::PermutationBase< Derived >::resize(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::rows(), and internal::Colamd::set_defaults().
The documentation for this class was generated from the following file:
Ordering.h