MercuryDPM: oomph::Legendre_functions_helper Namespace Reference
oomph::Legendre_functions_helper Namespace Reference
Helper namespace for functions required for Helmholtz computations.
Functions
double factorial (const unsigned &l)
Factorial.
double plgndr1 (const unsigned &n, const double &x)
Legendre polynomials depending on one parameter.
double plgndr2 (const unsigned &l, const unsigned &m, const double &x)
Legendre polynomials depending on two parameters.
Detailed Description
Helper namespace for functions required for Helmholtz computations.
Function Documentation
factorial()
double oomph::Legendre_functions_helper::factorial (const unsigned & l)
Factorial.
     {
       if (l == 0) return 1.0;
       return double(l * factorial(l - 1));
     }
Referenced by oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::setup_gamma().
plgndr1()
double oomph::Legendre_functions_helper::plgndr1 (const unsigned & n, const double & x)
Legendre polynomials depending on one parameter.
     {
       unsigned i;
       double pmm, pmm1;
       double pmm2 = 0;
 #ifdef PARANOID
       // Shout if things went wrong
       if (std::fabs(x) > 1.0)
       {
         std::ostringstream error_stream;
         error_stream << "Bad arguments in routine plgndr1: x=" << x
                      << " but should be less than 1 in absolute value.\n";
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Compute pmm : if l=m it's finished
       pmm = 1.0;
       if (n == 0)
       {
         return pmm;
       }
       pmm1 = x * 1.0;
       if (n == 1)
       {
         return pmm1;
       }
       else
       {
         for (i = 2; i <= n; i++)
         {
           pmm2 = (x * (2 * i - 1) * pmm1 - (i - 1) * pmm) / i;
           pmm = pmm1;
           pmm1 = pmm2;
         }
         return pmm2;
       }
     } // end of plgndr1
References boost::multiprecision::fabs(), i, n, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and plotDoE::x.
plgndr2()
double oomph::Legendre_functions_helper::plgndr2 (const unsigned & l, const unsigned & m, const double & x)
Legendre polynomials depending on two parameters.
     {
       unsigned i, ll;
       double fact, pmm, pmmp1, somx2;
       double pll = 0.0;
 #ifdef PARANOID
       // Shout if things went wrong
       if (std::fabs(x) > 1.0)
       {
         std::ostringstream error_stream;
         error_stream << "Bad arguments in routine plgndr2: x=" << x
                      << " but should be less than 1 in absolute value.\n";
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // This one is easy...
       if (m > l)
       {
         return 0.0;
       }
       // Compute pmm : if l=m it's finished
       pmm = 1.0;
       if (m > 0)
       {
         somx2 = sqrt((1.0 - x) * (1.0 + x));
         fact = 1.0;
         for (i = 1; i <= m; i++)
         {
           pmm *= -fact * somx2;
           fact += 2.0;
         }
       }
       if (l == m) return pmm;
       // Compute pmmp1 : if l=m+1 it's finished
       else
       {
         pmmp1 = x * (2 * m + 1) * pmm;
         if (l == (m + 1))
         {
           return pmmp1;
         }
         // Compute pll : if l>m+1 it's finished
         else
         {
           for (ll = m + 2; ll <= l; ll++)
           {
             pll = (x * (2 * ll - 1) * pmmp1 - (ll + m - 1) * pmm) / (ll - m);
             pmm = pmmp1;
             pmmp1 = pll;
           }
           return pll;
         }
       }
     } // end of plgndr2
References boost::multiprecision::fabs(), i, m, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, sqrt(), and plotDoE::x.
Referenced by oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::compute_gamma_contribution(), ProblemParameters::exact_minus_dudr(), PlanarWave::get_exact_u(), ProblemParameters::get_exact_u(), and main().