MercuryDPM: Eigen::TensorStorage< T, FixedDimensions, Options_ > Class Template Reference
Eigen::TensorStorage< T, FixedDimensions, Options_ > Class Template Reference
Stores the data of a tensor.
#include <TensorStorage.h>
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStorage ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T * data ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T * data () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const FixedDimensions dimensions () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DenseIndex size () const
Private Attributes
EIGEN_ALIGN_MAX T m_data [MinSize]
Static Private Attributes
static constexpr std::size_t Size = FixedDimensions::total_size
static constexpr std::size_t MinSize = max_n_1<Size>::size
Detailed Description
template<typename T, typename FixedDimensions, int Options_>
class Eigen::TensorStorage< T, FixedDimensions, Options_ >
Stores the data of a tensor.
This class stores the data of fixed-size, dynamic-size or mixed tensors in a way as compact as possible.
See also
Tensor
Constructor & Destructor Documentation
TensorStorage()
template<typename T , typename FixedDimensions , int Options_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorStorage< T, FixedDimensions, Options_ >::TensorStorage () inline
 {}
Member Function Documentation
data() [1/2]
template<typename T , typename FixedDimensions , int Options_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T* Eigen::TensorStorage< T, FixedDimensions, Options_ >::data () inline
 { return m_data; }
References Eigen::TensorStorage< T, FixedDimensions, Options_ >::m_data.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::coeff(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeff(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::coeffRef(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeffRef(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::data(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::data(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
data() [2/2]
template<typename T , typename FixedDimensions , int Options_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T* Eigen::TensorStorage< T, FixedDimensions, Options_ >::data () const inline
 { return m_data; }
References Eigen::TensorStorage< T, FixedDimensions, Options_ >::m_data.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename T , typename FixedDimensions , int Options_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const FixedDimensions Eigen::TensorStorage< T, FixedDimensions, Options_ >::dimensions () const inline
 { return FixedDimensions(); }
Referenced by Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::checkIndexRange(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::dimension(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::dimension(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::dimensions(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::dimensions(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::linearizedIndex(), and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::linearizedIndex().
size()
template<typename T , typename FixedDimensions , int Options_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DenseIndex Eigen::TensorStorage< T, FixedDimensions, Options_ >::size () const inline
 { return Size; }
References Eigen::TensorStorage< T, FixedDimensions, Options_ >::Size.
Referenced by Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::resize(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::size(), and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::size().
Member Data Documentation
m_data
template<typename T , typename FixedDimensions , int Options_> EIGEN_ALIGN_MAX T Eigen::TensorStorage< T, FixedDimensions, Options_ >::m_data[MinSize] private
Referenced by Eigen::TensorStorage< T, FixedDimensions, Options_ >::data(), Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::data(), Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::operator=(), Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::resize(), Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::swap(), Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::TensorStorage(), and Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::~TensorStorage().
MinSize
template<typename T , typename FixedDimensions , int Options_> constexpr std::size_t Eigen::TensorStorage< T, FixedDimensions, Options_ >::MinSize = max_n_1<Size>::size static constexpr private
Size
template<typename T , typename FixedDimensions , int Options_> constexpr std::size_t Eigen::TensorStorage< T, FixedDimensions, Options_ >::Size = FixedDimensions::total_size static constexpr private
Referenced by Eigen::TensorStorage< T, FixedDimensions, Options_ >::size().
The documentation for this class was generated from the following file:
TensorStorage.h