MercuryDPM: Eigen::SparseLUTransposeView< Conjugate, SparseLUType > Class Template Reference
Eigen::SparseLUTransposeView< Conjugate, SparseLUType > Class Template Reference
#include <SparseLU.h>
Public Types
enum { ColsAtCompileTime = MatrixType::ColsAtCompileTime , MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef SparseLUType::Scalar Scalar
typedef SparseLUType::StorageIndex StorageIndex
typedef SparseLUType::MatrixType MatrixType
typedef SparseLUType::OrderingType OrderingType
Public Member Functions
SparseLUTransposeView ()
SparseLUTransposeView (const SparseLUTransposeView &view)
void setIsInitialized (const bool isInitialized)
void setSparseLU (SparseLUType *sparseLU)
template<typename Rhs , typename Dest >
bool _solve_impl (const MatrixBase< Rhs > &B, MatrixBase< Dest > &X_base) const
Index rows () const
Index cols () const
Public Member Functions inherited from Eigen::SparseSolverBase< SparseLUTransposeView< Conjugate, SparseLUType > >
SparseSolverBase ()
SparseSolverBase (SparseSolverBase &&other)
~SparseSolverBase ()
SparseLUTransposeView< Conjugate, SparseLUType > & derived ()
const SparseLUTransposeView< Conjugate, SparseLUType > & derived () const
const Solve< SparseLUTransposeView< Conjugate, SparseLUType >, Rhs > solve (const MatrixBase< Rhs > &b) const
const Solve< SparseLUTransposeView< Conjugate, SparseLUType >, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
void _solve_impl (const SparseMatrixBase< Rhs > &b, SparseMatrixBase< Dest > &dest) const
Protected Types
typedef SparseSolverBase< SparseLUTransposeView< Conjugate, SparseLUType > > APIBase
Private Member Functions
SparseLUTransposeView & operator= (const SparseLUTransposeView &)
Private Attributes
SparseLUType * m_sparseLU
Additional Inherited Members
Protected Attributes inherited from Eigen::SparseSolverBase< SparseLUTransposeView< Conjugate, SparseLUType > >
bool m_isInitialized
Member Typedef Documentation
APIBase
template<bool Conjugate, class SparseLUType > typedef SparseSolverBase<SparseLUTransposeView<Conjugate, SparseLUType> > Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::APIBase protected
MatrixType
template<bool Conjugate, class SparseLUType > typedef SparseLUType::MatrixType Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::MatrixType
OrderingType
template<bool Conjugate, class SparseLUType > typedef SparseLUType::OrderingType Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::OrderingType
Scalar
template<bool Conjugate, class SparseLUType > typedef SparseLUType::Scalar Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::Scalar
StorageIndex
template<bool Conjugate, class SparseLUType > typedef SparseLUType::StorageIndex Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::StorageIndex
Member Enumeration Documentation
anonymous enum
template<bool Conjugate, class SparseLUType > anonymous enum
Enumerator
ColsAtCompileTime
MaxColsAtCompileTime
 { ColsAtCompileTime = MatrixType::ColsAtCompileTime, MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime };
Constructor & Destructor Documentation
SparseLUTransposeView() [1/2]
template<bool Conjugate, class SparseLUType > Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::SparseLUTransposeView () inline
 : APIBase(), m_sparseLU(NULL) {}
SparseLUTransposeView() [2/2]
template<bool Conjugate, class SparseLUType > Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::SparseLUTransposeView (const SparseLUTransposeView< Conjugate, SparseLUType > & view) inline
                                                            : APIBase() {
     this->m_sparseLU = view.m_sparseLU;
     this->m_isInitialized = view.m_isInitialized;
   }
References Eigen::SparseSolverBase< Derived >::m_isInitialized, Eigen::SparseSolverBase< SparseLUTransposeView< Conjugate, SparseLUType > >::m_isInitialized, and Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::m_sparseLU.
Member Function Documentation
_solve_impl()
template<bool Conjugate, class SparseLUType > template<typename Rhs , typename Dest > bool Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::_solve_impl (const MatrixBase< Rhs > & B, MatrixBase< Dest > & X_base) const inline
{
     Dest& X(X_base.derived());
     eigen_assert(m_sparseLU->info() == Success && "The matrix should be factorized first");
     EIGEN_STATIC_ASSERT((Dest::Flags & RowMajorBit) == 0, THIS_METHOD_IS_ONLY_FOR_COLUMN_MAJOR_MATRICES);
     // this ugly const_cast_derived() helps to detect aliasing when applying the permutations
     for (Index j = 0; j < B.cols(); ++j) {
       X.col(j) = m_sparseLU->colsPermutation() * B.const_cast_derived().col(j);
     }
     // Forward substitution with transposed or adjoint of U
     m_sparseLU->matrixU().template solveTransposedInPlace<Conjugate>(X);
     // Backward substitution with transposed or adjoint of L
     m_sparseLU->matrixL().template solveTransposedInPlace<Conjugate>(X);
     // Permute back the solution
     for (Index j = 0; j < B.cols(); ++j) X.col(j) = m_sparseLU->rowsPermutation().transpose() * X.col(j);
     return true;
   }
References eigen_assert, EIGEN_STATIC_ASSERT, j, Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::m_sparseLU, Eigen::RowMajorBit, Eigen::Success, and X.
cols()
template<bool Conjugate, class SparseLUType > Index Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::cols () const inline
 { return m_sparseLU->cols(); }
References Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::m_sparseLU.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
operator=()
template<bool Conjugate, class SparseLUType > SparseLUTransposeView& Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::operator= (const SparseLUTransposeView< Conjugate, SparseLUType > &) private
rows()
template<bool Conjugate, class SparseLUType > Index Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::rows () const inline
 { return m_sparseLU->rows(); }
References Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::m_sparseLU.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
setIsInitialized()
template<bool Conjugate, class SparseLUType > void Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::setIsInitialized (const bool isInitialized) inline
 { this->m_isInitialized = isInitialized; }
References Eigen::SparseSolverBase< SparseLUTransposeView< Conjugate, SparseLUType > >::m_isInitialized.
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::adjoint(), and Eigen::SparseLU< MatrixType_, OrderingType_ >::transpose().
setSparseLU()
template<bool Conjugate, class SparseLUType > void Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::setSparseLU (SparseLUType * sparseLU) inline
 { m_sparseLU = sparseLU; }
References Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::m_sparseLU.
Referenced by Eigen::SparseLU< MatrixType_, OrderingType_ >::adjoint(), and Eigen::SparseLU< MatrixType_, OrderingType_ >::transpose().
Member Data Documentation
m_sparseLU
template<bool Conjugate, class SparseLUType > SparseLUType* Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::m_sparseLU private
Referenced by Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::_solve_impl(), Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::cols(), Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::rows(), Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::setSparseLU(), and Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::SparseLUTransposeView().
The documentation for this class was generated from the following file:
SparseLU.h