MercuryDPM: pseudo_solid_collapsible_tube_work.cc File Reference
pseudo_solid_collapsible_tube_work.cc File Reference
#include "generic.h"
#include "solid.h"
#include "constitutive.h"
#include "navier_stokes.h"
#include "multi_physics.h"
#include "meshes/simple_cubic_mesh.h"
#include "meshes/quarter_tube_mesh.h"
Classes
class oomph::PseudoElasticBulkElement< ELEMENT >
class oomph::FaceGeometry< PseudoElasticBulkElement< ELEMENT > >
FaceGeometry of wrapped element is the same as the underlying element.
class WallMesh< ELEMENT >
class FluidMesh< ELEMENT >
class PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >
Namespaces
oomph
DRAIG: Change all instances of (SPATIAL_DIM) to (DIM-1).
Global_Parameters
Namespace for global parameters.
Typedefs
typedef PseudoElasticCollapsibleChannelProblem< RefineablePseudoSolidNodeUpdateElement< RefineableQTaylorHoodElement< 3 >, PseudoElasticBulkElement< RefineableQPVDElement< 3, 3 > > >, RefineableQPVDElement< 3, 3 > > PseudoElasticFSIProblem
Functions
void Global_Parameters::press_load (const Vector< double > &xi, const Vector< double > &x, const Vector< double > &N, Vector< double > &load)
Load function for wall.
void set_pseudo_elastic_fsi_solver (PseudoElasticFSIProblem &problem, const unsigned &ps_prec_type)
int main (int argc, char *argv[])
Typedef Documentation
PseudoElasticFSIProblem
typedef PseudoElasticCollapsibleChannelProblem< RefineablePseudoSolidNodeUpdateElement<RefineableQTaylorHoodElement<3>, PseudoElasticBulkElement<RefineableQPVDElement<3,3> > >,RefineableQPVDElement<3,3> > PseudoElasticFSIProblem
Function Documentation
main()
int main (int argc , char * argv[])
Demonstrate how to solve a 3D FSI problem with pseudo-solid node update for the fluid mesh.
 {
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::init(argc,argv,false);
 #endif
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Create generalised Hookean constitutive equations
  Global_Parameters::Constitutive_law_wall_pt =
   new GeneralisedHookean(&Global_Parameters::Nu_wall);
 Global_Parameters::Constitutive_law_pseudo_elastic_pt =
   new GeneralisedHookean(&Global_Parameters::Nu_pseudo_elastic);
  //Set up the problem
  PseudoElasticFSIProblem problem;
  // Doc info
  DocInfo doc_info;
  doc_info.set_directory("RESLT");
  // Doc initial configuration
  problem.doc_solution(doc_info);
  oomph_info << "Before manual refine: doc_info.number()="
             << doc_info.number() << std::endl;
  doc_info.number()++;
  // Do manual non-uniform refinement
  if (CommandLineArgs::Argc!=1)
   {
    problem.adapt();
   }
  // Doc afterwards
  problem.doc_solution(doc_info);
  oomph_info << "After manual refine: doc_info.number()="
             << doc_info.number() << std::endl;
  doc_info.number()++;
  // Setup timestepping
  double dt = Global_Parameters::T/double(Global_Parameters::Nstep_per_period);
  Global_Parameters::Dt=dt;
  problem.initialise_dt(dt);
  problem.set_initial_condition();
  unsigned ps_prec_type = std::atoi(argv[3]);
   // set
  if (CommandLineArgs::Argc>2)
   {
    set_pseudo_elastic_fsi_solver(problem,ps_prec_type);
   }
  // Steady run
  problem.steady_run(doc_info);
  // Unteady run
  problem.unsteady_run(doc_info);
  // // clean up
  // if (CommandLineArgs::Argc>2)
  //  {
  //   IterativeLinearSolver* solver_pt = dynamic_cast<IterativeLinearSolver*>(problem.linear_solver_pt());
  //   delete solver_pt->preconditioner_pt();
  //   delete solver_pt;
  //  }
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::finalize();
 #endif
 } // end_of_main
References oomph::CommandLineArgs::Argc, Global_Parameters::Constitutive_law_pseudo_elastic_pt, Global_Parameters::Constitutive_law_wall_pt, Global_Parameters::Dt, Global_Parameters::Nstep_per_period, Global_Parameters::Nu_pseudo_elastic, Global_Parameters::Nu_wall, oomph::DocInfo::number(), oomph::oomph_info, problem, oomph::DocInfo::set_directory(), set_pseudo_elastic_fsi_solver(), Flag_definition::setup(), and Global_Parameters::T.
set_pseudo_elastic_fsi_solver()
void set_pseudo_elastic_fsi_solver (PseudoElasticFSIProblem & problem, const unsigned & ps_prec_type)
helper method to return GMRES preconditioned with the pseudo-elastic FSI preconditioner. The unsigned ps_prec_type is a flag for the pseudo solid block preconditioner type. 0 - Exact 1 - Block diagonal 2 - Block upper triangular 3 - Block lower triangular
 {
 //setup the solver
 #ifdef OOMPH_HAS_TRILINOS
 TrilinosAztecOOSolver* solver_pt = new
  TrilinosAztecOOSolver;
 solver_pt->solver_type() = TrilinosAztecOOSolver::GMRES;
 #else
  GMRES<CRDoubleMatrix>* solver_pt = new GMRES<CRDoubleMatrix>;
 #endif
  solver_pt->tolerance()=1e-8;
  // preconditioner
  PseudoElasticFSIPreconditioner* prec_pt = new
   PseudoElasticFSIPreconditioner(3, &problem);
  // meshes
  prec_pt->set_fluid_and_pseudo_elastic_mesh_pt(problem.fluid_mesh_pt());
  prec_pt->set_solid_mesh_pt(problem.wall_mesh_pt());
  prec_pt->set_lagrange_multiplier_mesh_pt(
   problem.lagrange_multiplier_mesh_pt());
  // inexact pseudo-solid preconditioning
  // 0 - Exact
  // 1 - Block diagonal
  // 2 - Block upper triangular
  // 3 - Block lower triangular
  if(ps_prec_type == 0)
   {
    prec_pt->pseudo_elastic_preconditioner_pt()->elastic_preconditioner_type()
      = PseudoElasticPreconditioner::Exact_block_preconditioner;
   }
  else if(ps_prec_type == 1)
   {
    prec_pt->pseudo_elastic_preconditioner_pt()->elastic_preconditioner_type()
      = PseudoElasticPreconditioner::Block_diagonal_preconditioner;
   }
  else if(ps_prec_type == 2)
   {
    prec_pt->pseudo_elastic_preconditioner_pt()->elastic_preconditioner_type()
      = PseudoElasticPreconditioner::Block_upper_triangular_preconditioner;
   }
  else if(ps_prec_type == 3)
   {
    prec_pt->pseudo_elastic_preconditioner_pt()->elastic_preconditioner_type()
      = PseudoElasticPreconditioner::Block_lower_triangular_preconditioner;
   }
  else
   {
    pause("I do not know what to do");
   }
 #ifdef OOMPH_HAS_HYPRE
  prec_pt->pseudo_elastic_preconditioner_pt()
   ->set_elastic_subsidiary_preconditioner
   (Pseudo_Elastic_Preconditioner_Subsidiary_Operator_Helper
    ::get_elastic_preconditioner);
 #endif
 #ifdef OOMPH_HAS_TRILINOS
  prec_pt->pseudo_elastic_preconditioner_pt()
   ->set_lagrange_multiplier_subsidiary_preconditioner
   (Pseudo_Elastic_Preconditioner_Subsidiary_Operator_Helper
    ::get_lagrange_multiplier_preconditioner);
 #endif
  // inexact "real" solid preconditioning
  BlockTriangularPreconditioner<CRDoubleMatrix>*
   solid_prec_pt = new BlockTriangularPreconditioner<CRDoubleMatrix>;
  prec_pt->set_solid_preconditioner(solid_prec_pt);
 #ifdef OOMPH_HAS_HYPRE
  solid_prec_pt->set_subsidiary_preconditioner_function
   (Real_Solid_Preconditioner_Helper::get_preconditioner);
 #endif
  // inexact navier stokes preconditioning
   NavierStokesSchurComplementPreconditioner*
   ns_prec_pt = prec_pt->navier_stokes_schur_complement_preconditioner_pt();
  prec_pt->enable_navier_stokes_schur_complement_preconditioner();
  // ns momentum
  BlockDiagonalPreconditioner<CRDoubleMatrix>*
   f_prec_pt = new BlockDiagonalPreconditioner<CRDoubleMatrix>;
 #ifdef OOMPH_HAS_HYPRE
  f_prec_pt->set_subsidiary_preconditioner_function
   (LSC_Preconditioner_Helper::set_hypre_preconditioner);
 #endif
  ns_prec_pt->set_f_preconditioner(f_prec_pt);
 #ifdef OOMPH_HAS_HYPRE
  // ns pressure poisson
  HyprePreconditioner* p_prec_pt = new HyprePreconditioner;
  p_prec_pt->set_amg_iterations(2);
  p_prec_pt->amg_using_simple_smoothing();
  p_prec_pt->amg_simple_smoother() = 3;
  p_prec_pt->hypre_method() = HyprePreconditioner::BoomerAMG;
  p_prec_pt->amg_strength() = 0.25;
  // Use 6 for parallel (Falgout) or 3 (Ruge Stuben)or serial
  p_prec_pt->amg_coarsening() = 6;
  p_prec_pt->disable_doc_time();
  ns_prec_pt->set_p_preconditioner(p_prec_pt);
 #endif
  // hierher end
  // and pass prec to solver and solver to problem
  solver_pt->preconditioner_pt() = prec_pt;
  problem.linear_solver_pt() = solver_pt;
 }
References oomph::HyprePreconditioner::amg_coarsening(), oomph::HyprePreconditioner::amg_simple_smoother(), oomph::HyprePreconditioner::amg_strength(), oomph::HyprePreconditioner::amg_using_simple_smoothing(), oomph::HyprePreconditioner::disable_doc_time(), e(), oomph::PseudoElasticPreconditioner::elastic_preconditioner_type(), oomph::PseudoElasticFSIPreconditioner::enable_navier_stokes_schur_complement_preconditioner(), oomph::HyprePreconditioner::hypre_method(), oomph::PseudoElasticFSIPreconditioner::navier_stokes_schur_complement_preconditioner_pt(), oomph::pause(), oomph::IterativeLinearSolver::preconditioner_pt(), problem, oomph::PseudoElasticFSIPreconditioner::pseudo_elastic_preconditioner_pt(), oomph::HyprePreconditioner::set_amg_iterations(), oomph::PseudoElasticPreconditioner::set_elastic_subsidiary_preconditioner(), oomph::NavierStokesSchurComplementPreconditioner::set_f_preconditioner(), oomph::PseudoElasticFSIPreconditioner::set_fluid_and_pseudo_elastic_mesh_pt(), oomph::PseudoElasticFSIPreconditioner::set_lagrange_multiplier_mesh_pt(), oomph::PseudoElasticPreconditioner::set_lagrange_multiplier_subsidiary_preconditioner(), oomph::NavierStokesSchurComplementPreconditioner::set_p_preconditioner(), oomph::PseudoElasticFSIPreconditioner::set_solid_mesh_pt(), oomph::PseudoElasticFSIPreconditioner::set_solid_preconditioner(), oomph::GeneralPurposeBlockPreconditioner< MATRIX >::set_subsidiary_preconditioner_function(), oomph::TrilinosAztecOOSolver::solver_type(), and oomph::TrilinosAztecOOSolver::tolerance().
Referenced by main().