MercuryDPM: EigenSolver_EigenSolver_MatrixType.cpp File Reference
EigenSolver_EigenSolver_MatrixType.cpp File Reference
Functions
cout<< "Here is a random 6x6 matrix, A:"<< endl<< A<< endl<< endl;EigenSolver< MatrixXd > es (A)
cout<< "Consider the first eigenvalue, lambda = "<< lambda<< endl;VectorXcd v=es.eigenvectors().col(0);cout<< "If v is the corresponding eigenvector, then lambda * v = "<< endl<< lambda *v<< endl;cout<< "... and A * v = "<< endl<< A.cast< complex< double > > () *v<< endl<< endl
Variables
MatrixXd A = MatrixXd::Random(6, 6)
cout<< "The eigenvalues of A are:"<< endl<< es.eigenvalues()<< endl;cout<< "The matrix of eigenvectors, V, is:"<< endl<< es.eigenvectors()<< endl<< endl;complex< double > lambda = es.eigenvalues()[0]
MatrixXcd D = es.eigenvalues().asDiagonal()
MatrixXcd V = es.eigenvectors()
Function Documentation
cout<< "Consider the first eigenvalue, lambda = "<< lambda<< endl;VectorXcd v=es.eigenvectors().col(0);cout<< "If v is the corresponding eigenvector, then lambda * v = "<< endl<< lambda *v<< endl;cout<< "... and A * v = "<< endl<< A.cast< complex< double > >()
cout<< "Consider the first eigenvalue, lambda = "<< lambda<< endl;VectorXcd v=es.eigenvectors().col(0);cout<< "If v is the corresponding eigenvector, then lambda * v = "<< endl<< lambda *v<< endl;cout<< "... and A * v = "<< endl<< A.cast< complex< double > > ()
es()
cout<< "Here is a random 6x6 matrix, A:" << endl << A << endl << endl;EigenSolver<MatrixXd> es (A)
Variable Documentation
A
MatrixXd A = MatrixXd::Random(6, 6)
D
MatrixXcd D = es.eigenvalues().asDiagonal()
lambda
cout<< "The eigenvalues of A are:" << endl << es.eigenvalues() << endl;cout << "The matrix of eigenvectors, V, is:" << endl << es.eigenvectors() << endl << endl;complex<double> lambda = es.eigenvalues()[0]
V
MatrixXcd V = es.eigenvectors()
Referenced by Slide::actionsBeforeTimeStep(), Eigen::internal::apply_block_householder_on_the_left(), LiquidBridgeBagheriInteraction::computeAdhesionForce(), PSD::computeD50(), Eigen::BDCSVD< MatrixType_, Options_ >::computeSingVecs(), Eigen::BDCSVD< MatrixType_, Options_ >::computeSVDofM(), generalized_eigensolver_real(), Eigen::generateRandomMatrixSvs(), BaseInteraction::getOverlapVolume(), Eigen::internal::idrstabl(), Eigen::internal::matrix_exp_compute(), Eigen::internal::matrix_exp_pade13(), Eigen::internal::matrix_exp_pade3(), Eigen::internal::matrix_exp_pade5(), Eigen::internal::matrix_exp_pade7(), Eigen::internal::matrix_exp_pade9(), nullary_internal_logic(), CircularPeriodicBoundary::rotateParticle(), Eigen::internal::matrix_exp_computeUV< MatrixType, float >::run(), Eigen::internal::matrix_exp_computeUV< MatrixType, double >::run(), Eigen::internal::matrix_exp_computeUV< MatrixType, long double >::run(), and MD_demo::setupInitialConditions().