MercuryDPM: LiquidBridgeBagheriInteraction Class Reference
LiquidBridgeBagheriInteraction Class Reference
Defines the liquid bridge Bagheri interaction between two particles or walls.
#include <LiquidBridgeBagheriInteraction.h>
Public Types
typedef LiquidBridgeBagheriSpecies SpeciesType
An alias name for LiquidBridgeBagheriSpecies data type.
Public Member Functions
LiquidBridgeBagheriInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
Constructor.
LiquidBridgeBagheriInteraction ()
LiquidBridgeBagheriInteraction (const LiquidBridgeBagheriInteraction &p)
Copy constructor.
~LiquidBridgeBagheriInteraction () override
Destructor.
void computeAdhesionForce ()
Computes the adhesive forces for liquid bridge Bagheri type of interaction.
void read (std::istream &is) override
Interaction read function, which accepts an std::istream as input.
void write (std::ostream &os) const override
Interaction print function, which accepts an std::ostream as input.
Mdouble getElasticEnergy () const override
Returns the amount of Elastic energy involved in an interaction. Basically used in case you want to write the elastic energy into an output file.
const LiquidBridgeBagheriSpecies * getSpecies () const
Returns a pointer to the adhesive force species LiquidBridgeBagheriSpecies.
std::string getBaseName () const
Returns the name of the interaction, see Interaction.h.
bool getWasInContact () const
void setWasInContact (bool wasInContact)
Public Member Functions inherited from BaseInteraction
BaseInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
A constructor takes the BaseInteractable objects which are interacting (come into contact) and time the interaction starts.
BaseInteraction ()
BaseInteraction (const BaseInteraction &p)
Copy constructor.
~BaseInteraction () override
The destructor. It removes this interactions from the objects that were interacting, and writes the time to a file when needed.
virtual void actionsOnErase ()
If an interaction needs to do something before it gets erased, add it here. E.g. Liquid bridges rupture at the end of their lifetime, and the liquid bridge volume has to be redistributed. The reason this action is not done in the destructor is that this action should not be taken when erasing ghost interactions.
virtual void computeForce ()
Virtual function that contains the force law between the two objects interacting.
void read (std::istream &is) override
Interaction read function, which accepts an std::istream as input.
void write (std::ostream &os) const override
Interaction print function, which accepts an std::ostream as input.
void writeToFStat (std::ostream &os, Mdouble time) const
Writes forces data to the FStat file.
std::string getName () const override
Virtual function which allows interactions to be named.
void setDistance (Mdouble distance)
Sets the interaction distance between the two interacting objects.
void setNormal (Vec3D normal)
Sets the normal vector between the two interacting objects.
void setOverlap (Mdouble overlap)
Set the overlap between the two interacting object.
void setContactPoint (Vec3D contactPoint)
Set the location of the contact point between the two interacting objects.
void setTimeStamp (unsigned timeStamp)
Updates the time step of the interacting. Note, time steps used to find completed interactions.
void setSpecies (const BaseSpecies *species)
Set the Species of the interaction; note this can either be a Species or MixedSpecies.
void setP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void setI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
void importP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void importI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
Vec3D getIP () const
Vec3D getIC () const
Vec3D getCP () const
void setLagrangeMultiplier (Mdouble multiplier)
Mdouble getLagrangeMultiplier ()
void setHandler (InteractionHandler *handler)
Sets the pointer to the interaction hander which is storing this interaction.
InteractionHandler * getHandler () const
Gets a point to the interaction handlers to which this interaction belongs.
const Vec3D & getForce () const
Gets the current force (vector) between the two interacting objects.
const Vec3D & getTorque () const
Gets the current torque (vector) between the two interacting objects.
const Vec3D & getNormal () const
Gets the normal vector between the two interacting objects.
const Vec3D & getContactPoint () const
Gets constant reference to contact point (vector).
Mdouble getOverlap () const
Returns a Mdouble with the current overlap between the two interacting objects.
Mdouble getOverlapVolume () const
Returns the overlap volume between two interacting objects.
Mdouble getContactRadius () const
Returns a Mdouble with the current contact between the two interacting objects.
void removeFromHandler ()
Removes this interaction from its interaction hander.
void copySwitchPointer (const BaseInteractable *original, BaseInteractable *ghost) const
This copies the interactions of the original particle and replaces the original with the ghost copy.
void gatherContactStatistics ()
BaseInteractable * getP ()
Returns a pointer to first object involved in the interaction (normally a particle).
BaseInteractable * getI ()
Returns a pointer to the second object involved in the interaction (often a wall or a particle).
const BaseInteractable * getP () const
Returns a constant pointer to the first object involved in the interaction.
const BaseInteractable * getI () const
Returns a constant pointer to the second object involved in the interaction.
Mdouble getTimeStamp () const
Returns an Mdouble which is the time stamp of the interaction.
virtual void integrate (Mdouble timeStep)
integrates variables of the interaction which need to be integrate e.g. the tangential overlap.
virtual Mdouble getTangentialOverlap () const
get the length of the current tangential overlap
Mdouble getDistance () const
Returns an Mdouble which is the norm (length) of distance vector.
const Vec3D & getRelativeVelocity () const
Returns a constant reference to a vector of relative velocity.
Mdouble getNormalRelativeVelocity () const
Returns a double which is the norm (length) of the relative velocity vector.
Mdouble getAbsoluteNormalForce () const
Returns the absolute value of the norm (length) of the Normal force vector.
virtual BaseInteraction * copy () const =0
Makes a copy of the interaction and returns a pointer to the copy.
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseWall *I)
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseParticle *I)
unsigned int getMultiContactIdentifier () const
void setMultiContactIdentifier (unsigned int multiContactIdentifier_)
virtual void rotateHistory (Matrix3D &rotationMatrix)
When periodic particles are used, some interactions need certain history properties rotated (e.g. tangential springs). This is the function for that.
virtual void actionsAfterTimeStep ()
virtual unsigned getNumberOfFieldsVTK () const
virtual std::string getTypeVTK (unsigned i) const
virtual std::string getNameVTK (unsigned i) const
virtual std::vector< Mdouble > getFieldVTK (unsigned i) const
void addForce (Vec3D force)
add an force increment to the total force.
void addTorque (Vec3D torque)
add a torque increment to the total torque.
void setForce (Vec3D force)
set total force (this is used by the normal force, tangential forces are added use addForce)
void setTorque (Vec3D torque)
set the total force (this is used by the normal force, tangential torques are added use addTorque)
const BaseSpecies * getBaseSpecies () const
Return a constant point to BaseSpecies of the interaction.
virtual void createMPIType ()
virtual void * createMPIInteractionDataArray (unsigned int numberOfInteractions) const
virtual void deleteMPIInteractionDataArray (void *dataArray)
virtual void getMPIInteraction (void *historyDataArray, unsigned int index) const
copies the history interactions into the data array
virtual void getInteractionDetails (void *interactionDataArray, unsigned int index, unsigned int &identificationP, unsigned int &identificationI, bool &isWallInteraction, unsigned &timeStamp)
virtual void setMPIInteraction (void *interactionDataArray, unsigned int index, bool resetPointers)
void setBasicMPIInteractionValues (int P, int I, unsigned timeStamp, Vec3D force, Vec3D torque, bool isWallInteraction, bool resetPointers)
void setIdentificationP (unsigned int identification)
void setIdentificationI (int identification)
void setWallInteraction (bool flag)
unsigned int getIdentificationP ()
int getIdentificationI ()
bool isWallInteraction ()
virtual bool isBonded () const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
bool wasInContact_
A history parameter to store if the particles were in contact or not. Useful to compute adhesive forces.
Additional Inherited Members
Protected Member Functions inherited from BaseInteraction
virtual const Vec3D getTangentialForce () const
Mdouble getEffectiveRadius () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
Mdouble getEffectiveMass () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
void setRelativeVelocity (Vec3D relativeVelocity)
set the relative velocity of the current of the interactions.
void setNormalRelativeVelocity (Mdouble normalRelativeVelocit)
set the normal component of the relative velocity.
void setAbsoluteNormalForce (Mdouble absoluteNormalForce)
the absolute values of the norm (length) of the normal force
virtual Mdouble getElasticEnergyAtEquilibrium (Mdouble adhesiveForce) const
virtual void reverseHistory ()
When periodic particles some interaction need certain history properties reversing. This is the function for that.
void writeInteraction (std::ostream &os, bool created) const
Writes information about a interaction to the interaction file.
Detailed Description
Defines the liquid bridge Bagheri interaction between two particles or walls.
Member Typedef Documentation
SpeciesType
typedef LiquidBridgeBagheriSpecies LiquidBridgeBagheriInteraction::SpeciesType
An alias name for LiquidBridgeBagheriSpecies data type.
Constructor & Destructor Documentation
LiquidBridgeBagheriInteraction() [1/3]
LiquidBridgeBagheriInteraction::LiquidBridgeBagheriInteraction (BaseInteractable * P, BaseInteractable * I, unsigned timeStamp)
Constructor.
Parameters
[in] P
[in] I
[in] timeStamp
         : BaseInteraction(P, I, timeStamp)
 {
     wasInContact_ = false;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"LiquidBridgeBagheriInteraction::LiquidBridgeBagheriInteraction() finished"<<std::endl;
 #endif
 }
References wasInContact_.
LiquidBridgeBagheriInteraction() [2/3]
LiquidBridgeBagheriInteraction::LiquidBridgeBagheriInteraction ()
         : BaseInteraction()
 {
     wasInContact_ = false;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"LiquidBridgeBagheriInteraction::LiquidBridgeBagheriInteraction() finished"<<std::endl;
 #endif
 }
References wasInContact_.
LiquidBridgeBagheriInteraction() [3/3]
LiquidBridgeBagheriInteraction::LiquidBridgeBagheriInteraction (const LiquidBridgeBagheriInteraction & p)
Copy constructor.
Parameters
[in] p
         : BaseInteraction(p)
 {
     wasInContact_ = p.wasInContact_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"LiquidBridgeBagheriInteraction::LiquidBridgeBagheriInteraction(const LiquidBridgeBagheriInteraction &p finished"<<std::endl;
 #endif
 }
References p, and wasInContact_.
~LiquidBridgeBagheriInteraction()
LiquidBridgeBagheriInteraction::~LiquidBridgeBagheriInteraction () override
Destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"LiquidBridgeBagheriInteraction::~LiquidBridgeBagheriInteraction() finished"<<std::endl;
 #endif
 }
Member Function Documentation
computeAdhesionForce()
void LiquidBridgeBagheriInteraction::computeAdhesionForce ()
Computes the adhesive forces for liquid bridge Bagheri type of interaction.
 {
     const LiquidBridgeBagheriSpecies* species = getSpecies();
     // if the liquid bridge volume is zero, there is no liquid bridge and no force
     if (species->getLiquidBridgeVolume() == 0)
     {
         return;
     }
     if (getOverlap() >= 0)
     {
         wasInContact_ = true;
         // The effective radius is calculated as twice the effective radius of the particles, because the harmonic mean is needed. For same size spheres, this should be the radius of the spheres.
         Mdouble effectiveRadius = 2 * getEffectiveRadius();
         Mdouble V = species->getLiquidBridgeVolume()/std::pow(effectiveRadius,3);
         // Only allow volumes which are valid according to https://doi.org/10.1007/s40571-024-00772-5
         logger.assert_debug(V >= 1e-6 && V <= 1e-1, "Liquid bridge volume is out of range for the Bagheri model. V/R^3 = % (It should be in the range [1e-6, 1e-1]).", V);
         // full model according to Eq. 24-26 from Bagheri et al. 2024, CPM
         Mdouble f0 = 2*constants::pi*(1 - 0.3823*std::pow(V,0.2586));
         // std::cout << species->getMeanRadius() << std::endl;
         Mdouble a = 0.4158*std::pow(V,0.2835)+0.6474;
         Mdouble b = -0.2087*std::pow(V,0.3113)+2.267;
         Mdouble ft = (1 - a*std::pow(std::sin(species->getContactAngle()),b))*f0;
         Mdouble force_full_fit = ft;
         Mdouble fdotn = -force_full_fit * effectiveRadius * species->getSurfaceTension();
         addForce(getNormal() * fdotn);
     }
     else if (wasInContact_)
     {
         Mdouble effectiveRadius = 2 * getEffectiveRadius();
         Mdouble V = species->getLiquidBridgeVolume()/std::pow(effectiveRadius,3);
         // Only allow volumes which are valid according to https://doi.org/10.1007/s40571-024-00772-5
         logger.assert_debug(V >= 1e-6 && V <= 1e-1, "Liquid bridge volume is out of range for the Bagheri model. V/R^3 = % (It should be in the range [1e-6, 1e-1]).", V);
         Mdouble S_rupture = (1.0 + species->getContactAngle()*0.5)*(std::pow(V,1.0/3.0)+0.1*std::pow(V,2.0/3.0));
         Mdouble S = -getOverlap()/(effectiveRadius*S_rupture);
         // if the overlap is too large, the liquid bridge is ruptured and no force is applied
         if (S > 1.0)
         {
             wasInContact_ = false;
             return;
         }
         Mdouble log_V = std::log(V);
         // full model according to Eq. 27-30 from Bagheri et al. 2024, CPM
         Mdouble f0 = 2*constants::pi*(1 - 0.3823*std::pow(V,0.2586));
         Mdouble a = 0.4158*std::pow(V,0.2835)+0.6474;
         Mdouble b = -0.2087*std::pow(V,0.3113)+2.267;
         Mdouble ft = (1 - a*std::pow(std::sin(species->getContactAngle()),b))*f0;
         Mdouble a_s = -0.3319*std::pow(V,0.4974) + 0.6717*std::pow(V,0.1995);
         Mdouble b_s = 13.84*std::pow(V,-0.3909) - 12.11*std::pow(V,-0.3945);
         Mdouble a_t_a = -0.007815*std::pow(log_V,2)-0.2105 *log_V -1.426;
         Mdouble b_t_a = -1.78*std::pow(V,0.8351) + 0.6669*std::pow(V,-0.01391);
         Mdouble a_t = a_t_a*std::pow(species->getContactAngle(),3)+b_t_a*species->getContactAngle()+1.0;
         Mdouble force_full_fit = ft*(1+a_s*S)/(1+a_t*b_s*a_s*S+a_t*b_s*std::pow(S,2));
         Mdouble fdotn = -force_full_fit * effectiveRadius * species->getSurfaceTension();
         addForce(getNormal() * fdotn);
     }
 }
References a, BaseInteraction::addForce(), b, e(), LiquidBridgeBagheriSpecies::getContactAngle(), BaseInteraction::getEffectiveRadius(), LiquidBridgeBagheriSpecies::getLiquidBridgeVolume(), BaseInteraction::getNormal(), BaseInteraction::getOverlap(), getSpecies(), LiquidBridgeBagheriSpecies::getSurfaceTension(), Eigen::bfloat16_impl::log(), logger, constants::pi, Eigen::bfloat16_impl::pow(), oomph::QuadTreeNames::S, sin(), V, and wasInContact_.
getBaseName()
std::string LiquidBridgeBagheriInteraction::getBaseName () const
Returns the name of the interaction, see Interaction.h.
Returns
std::string
 {
     return "LiquidBridgeBagheri";
 }
getElasticEnergy()
Mdouble LiquidBridgeBagheriInteraction::getElasticEnergy () const override virtual
Returns the amount of Elastic energy involved in an interaction. Basically used in case you want to write the elastic energy into an output file.
Returns
Mdouble
Todo:
TW
Reimplemented from BaseInteraction.
 {
     return 0.0;
 }
getSpecies()
const LiquidBridgeBagheriSpecies * LiquidBridgeBagheriInteraction::getSpecies () const
Returns a pointer to the adhesive force species LiquidBridgeBagheriSpecies.
Returns
const LiquidBridgeBagheriSpecies*
 {
     return static_cast<const LiquidBridgeBagheriSpecies*>(getBaseSpecies()->getAdhesiveForce());
 }
References BaseSpecies::getAdhesiveForce(), and BaseInteraction::getBaseSpecies().
Referenced by computeAdhesionForce().
getWasInContact()
bool LiquidBridgeBagheriInteraction::getWasInContact () const
 {
     return wasInContact_;
 }
References wasInContact_.
read()
void LiquidBridgeBagheriInteraction::read (std::istream & is) override virtual
Interaction read function, which accepts an std::istream as input.
Parameters
[in,out] is
Implements BaseObject.
 {
     // we read in wasInContact_ like this because an early version did not initialize it.
     std::string dummy;
     is >> dummy >> wasInContact_;
 }
References oomph::Global_string_for_annotation::string(), and wasInContact_.
setWasInContact()
void LiquidBridgeBagheriInteraction::setWasInContact (bool wasInContact)
 {
     wasInContact_ = wasInContact;
 }
References wasInContact_.
write()
void LiquidBridgeBagheriInteraction::write (std::ostream & os) const override virtual
Interaction print function, which accepts an std::ostream as input.
Parameters
[in,out] os
Implements BaseObject.
 {
     os << " wasInContact " << wasInContact_;
 }
References wasInContact_.
Member Data Documentation
wasInContact_
bool LiquidBridgeBagheriInteraction::wasInContact_ private
A history parameter to store if the particles were in contact or not. Useful to compute adhesive forces.
Referenced by computeAdhesionForce(), getWasInContact(), LiquidBridgeBagheriInteraction(), read(), setWasInContact(), and write().
The documentation for this class was generated from the following files:
LiquidBridgeBagheriInteraction.h
LiquidBridgeBagheriInteraction.cc