MercuryDPM: oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper Namespace Reference
oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper Namespace Reference
Namespace for subsidiary preconditioner creation helper functions.
Functions
Preconditioner * get_w_cg_preconditioner ()
Preconditioner * boomer_amg_for_2D_momentum_simple_visc ()
Preconditioner * boomer_amg_for_2D_momentum_stressdiv_visc ()
Preconditioner * boomer_amg_for_3D_momentum ()
Preconditioner * boomer_amg2v22_for_3D_momentum ()
Preconditioner * boomer_amg_for_2D_poisson_problem ()
Preconditioner * boomer_amg_for_3D_poisson_problem ()
Detailed Description
Namespace for subsidiary preconditioner creation helper functions.
Function Documentation
boomer_amg2v22_for_3D_momentum()
Preconditioner * oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg2v22_for_3D_momentum ()
Hypre Boomer AMG setting for the augmented momentum block of a 3D Navier-Stokes problem (for serial code).
     {
 #ifdef OOMPH_HAS_HYPRE
       // Create a new HyprePreconditioner
       HyprePreconditioner* hypre_preconditioner_pt = new HyprePreconditioner;
       // Coarsening strategy
       // 1 = classical RS with no boundary treatment (not recommended in
       // parallel)
       hypre_preconditioner_pt->amg_coarsening() = 1;
       // Strength of dependence = 0.668
       hypre_preconditioner_pt->amg_strength() = 0.8;
       // Set the smoothers
       //   1 = Gauss-Seidel, sequential (very slow in parallel!)
       hypre_preconditioner_pt->amg_simple_smoother() = 1;
       // Set smoother damping (not required, so set to -1)
       hypre_preconditioner_pt->amg_damping() = -1;
       // Set number of cycles to 1xV(2,2)
       hypre_preconditioner_pt->set_amg_iterations(2);
       hypre_preconditioner_pt->amg_smoother_iterations() = 2;
       return hypre_preconditioner_pt;
 #else
       std::ostringstream err_msg;
       err_msg << "hypre preconditioner is not available.\n"
               << "Please install Hypre.\n";
       throw OomphLibError(
         err_msg.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
 #endif
     } // function boomer_amg_for_3D_momentum
References oomph::HyprePreconditioner::amg_coarsening(), oomph::HyprePreconditioner::amg_damping(), oomph::HyprePreconditioner::amg_simple_smoother(), oomph::HyprePreconditioner::amg_smoother_iterations(), oomph::HyprePreconditioner::amg_strength(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::HyprePreconditioner::set_amg_iterations().
boomer_amg_for_2D_momentum_simple_visc()
Preconditioner * oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_2D_momentum_simple_visc ()
Hypre Boomer AMG setting for the augmented momentum block of a 2D Navier-Stokes problem using the simple form of the viscous term (for serial code).
     {
 #ifdef OOMPH_HAS_HYPRE
       // Create a new HyprePreconditioner
       HyprePreconditioner* hypre_preconditioner_pt = new HyprePreconditioner;
       // Coarsening strategy
       // 1 = classical RS with no boundary treatment (not recommended in
       // parallel)
       hypre_preconditioner_pt->amg_coarsening() = 1;
       // Strength of dependence = 0.25
       hypre_preconditioner_pt->amg_strength() = 0.25;
       // Set the smoothers
       //   1 = Gauss-Seidel, sequential (very slow in parallel!)
       hypre_preconditioner_pt->amg_simple_smoother() = 1;
       // Set smoother damping (not required, so set to -1)
       hypre_preconditioner_pt->amg_damping() = -1;
       // Set number of cycles to 1xV(2,2)
       hypre_preconditioner_pt->set_amg_iterations(1);
       hypre_preconditioner_pt->amg_smoother_iterations() = 2;
       return hypre_preconditioner_pt;
 #else
       std::ostringstream err_msg;
       err_msg << "hypre preconditioner is not available.\n"
               << "Please install Hypre.\n";
       throw OomphLibError(
         err_msg.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
 #endif
     } // function boomer_amg_for_2D_momentum_simple_visc
References oomph::HyprePreconditioner::amg_coarsening(), oomph::HyprePreconditioner::amg_damping(), oomph::HyprePreconditioner::amg_simple_smoother(), oomph::HyprePreconditioner::amg_smoother_iterations(), oomph::HyprePreconditioner::amg_strength(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::HyprePreconditioner::set_amg_iterations().
Referenced by TiltedCavityProblem< ELEMENT >::TiltedCavityProblem().
boomer_amg_for_2D_momentum_stressdiv_visc()
Preconditioner * oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_2D_momentum_stressdiv_visc ()
Hypre Boomer AMG setting for the augmented momentum block of a 2D Navier-Stokes problem using the stress divergence form of the viscous term (for serial code).
     {
 #ifdef OOMPH_HAS_HYPRE
       // Create a new HyprePreconditioner
       HyprePreconditioner* hypre_preconditioner_pt = new HyprePreconditioner;
       // Coarsening strategy
       // 1 = classical RS with no boundary treatment (not recommended in
       // parallel)
       hypre_preconditioner_pt->amg_coarsening() = 1;
       // Strength of dependence = 0.668
       hypre_preconditioner_pt->amg_strength() = 0.668;
       // Set the smoothers
       //   1 = Gauss-Seidel, sequential (very slow in parallel!)
       hypre_preconditioner_pt->amg_simple_smoother() = 1;
       // Set smoother damping (not required, so set to -1)
       hypre_preconditioner_pt->amg_damping() = -1;
       // Set number of cycles to 1xV(2,2)
       hypre_preconditioner_pt->set_amg_iterations(1);
       hypre_preconditioner_pt->amg_smoother_iterations() = 2;
       return hypre_preconditioner_pt;
 #else
       std::ostringstream err_msg;
       err_msg << "hypre preconditioner is not available.\n"
               << "Please install Hypre.\n";
       throw OomphLibError(
         err_msg.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
 #endif
     } // function boomer_amg_for_2D_momentum_stressdiv_visc
References oomph::HyprePreconditioner::amg_coarsening(), oomph::HyprePreconditioner::amg_damping(), oomph::HyprePreconditioner::amg_simple_smoother(), oomph::HyprePreconditioner::amg_smoother_iterations(), oomph::HyprePreconditioner::amg_strength(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::HyprePreconditioner::set_amg_iterations().
Referenced by TiltedCavityProblem< ELEMENT >::TiltedCavityProblem().
boomer_amg_for_2D_poisson_problem()
Preconditioner * oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_2D_poisson_problem ()
Hypre Boomer AMG setting for the 2D Poisson problem (for serial code).
     {
 #ifdef OOMPH_HAS_HYPRE
       // Create a new HyprePreconditioner
       HyprePreconditioner* hypre_preconditioner_pt = new HyprePreconditioner;
       // Coarsening strategy
       // 1 = classical RS with no boundary treatment (not recommended in
       // parallel)
       hypre_preconditioner_pt->amg_coarsening() = 1;
       // Strength of dependence = 0.25
       hypre_preconditioner_pt->amg_strength() = 0.25;
       // Set the smoothers
       //   0 = Jacobi
       hypre_preconditioner_pt->amg_simple_smoother() = 0;
       // Set Jacobi damping = 2/3
       hypre_preconditioner_pt->amg_damping() = 0.668;
       // Set number of cycles to 1xV(2,2)
       hypre_preconditioner_pt->set_amg_iterations(2);
       hypre_preconditioner_pt->amg_smoother_iterations() = 1;
       return hypre_preconditioner_pt;
 #else
       std::ostringstream err_msg;
       err_msg << "hypre preconditioner is not available.\n"
               << "Please install Hypre.\n";
       throw OomphLibError(
         err_msg.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
 #endif
     } // function boomer_amg_for_2D_poisson_problem
References oomph::HyprePreconditioner::amg_coarsening(), oomph::HyprePreconditioner::amg_damping(), oomph::HyprePreconditioner::amg_simple_smoother(), oomph::HyprePreconditioner::amg_smoother_iterations(), oomph::HyprePreconditioner::amg_strength(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::HyprePreconditioner::set_amg_iterations().
Referenced by TiltedCavityProblem< ELEMENT >::TiltedCavityProblem().
boomer_amg_for_3D_momentum()
Preconditioner * oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_3D_momentum ()
Hypre Boomer AMG setting for the augmented momentum block of a 3D Navier-Stokes problem (for serial code).
     {
 #ifdef OOMPH_HAS_HYPRE
       // Create a new HyprePreconditioner
       HyprePreconditioner* hypre_preconditioner_pt = new HyprePreconditioner;
       // Coarsening strategy
       // 1 = classical RS with no boundary treatment (not recommended in
       // parallel)
       hypre_preconditioner_pt->amg_coarsening() = 1;
       // Strength of dependence = 0.668
       hypre_preconditioner_pt->amg_strength() = 0.8;
       // Set the smoothers
       //   1 = Gauss-Seidel, sequential (very slow in parallel!)
       hypre_preconditioner_pt->amg_simple_smoother() = 1;
       // Set smoother damping (not required, so set to -1)
       hypre_preconditioner_pt->amg_damping() = -1;
       // Set number of cycles to 1xV(2,2)
       hypre_preconditioner_pt->set_amg_iterations(1);
       hypre_preconditioner_pt->amg_smoother_iterations() = 2;
       return hypre_preconditioner_pt;
 #else
       std::ostringstream err_msg;
       err_msg << "hypre preconditioner is not available.\n"
               << "Please install Hypre.\n";
       throw OomphLibError(
         err_msg.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
 #endif
     } // function boomer_amg_for_3D_momentum
References oomph::HyprePreconditioner::amg_coarsening(), oomph::HyprePreconditioner::amg_damping(), oomph::HyprePreconditioner::amg_simple_smoother(), oomph::HyprePreconditioner::amg_smoother_iterations(), oomph::HyprePreconditioner::amg_strength(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::HyprePreconditioner::set_amg_iterations().
boomer_amg_for_3D_poisson_problem()
Preconditioner * oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_3D_poisson_problem ()
Hypre Boomer AMG setting for the 3D Poisson problem (for serial code).
     {
 #ifdef OOMPH_HAS_HYPRE
       // Create a new HyprePreconditioner
       HyprePreconditioner* hypre_preconditioner_pt = new HyprePreconditioner;
       // Coarsening strategy
       // 1 = classical RS with no boundary treatment (not recommended in
       // parallel)
       hypre_preconditioner_pt->amg_coarsening() = 1;
       // Strength of dependence = 0.7
       hypre_preconditioner_pt->amg_strength() = 0.7;
       // Set the smoothers
       //   0 = Jacobi
       hypre_preconditioner_pt->amg_simple_smoother() = 0;
       // Set smoother damping = 2/3
       hypre_preconditioner_pt->amg_damping() = 0.668;
       // Set number of cycles to 2xV(1,1)
       hypre_preconditioner_pt->set_amg_iterations(2);
       hypre_preconditioner_pt->amg_smoother_iterations() = 1;
       return hypre_preconditioner_pt;
 #else
       std::ostringstream err_msg;
       err_msg << "hypre preconditioner is not available.\n"
               << "Please install Hypre.\n";
       throw OomphLibError(
         err_msg.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
 #endif
     } // function boomer_amg_for_3D_poisson_problem
References oomph::HyprePreconditioner::amg_coarsening(), oomph::HyprePreconditioner::amg_damping(), oomph::HyprePreconditioner::amg_simple_smoother(), oomph::HyprePreconditioner::amg_smoother_iterations(), oomph::HyprePreconditioner::amg_strength(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::HyprePreconditioner::set_amg_iterations().
get_w_cg_preconditioner()
Preconditioner * oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::get_w_cg_preconditioner ()
CG with diagonal preconditioner for W-block subsidiary linear systems.
     {
 #ifdef OOMPH_HAS_TRILINOS
       InnerIterationPreconditioner<TrilinosAztecOOSolver,
                                    MatrixBasedDiagPreconditioner>* prec_pt =
         new InnerIterationPreconditioner<TrilinosAztecOOSolver,
                                          MatrixBasedDiagPreconditioner>;
       // Note: This makes CG a proper "inner iteration" for
       // which GMRES (may) no longer converge. We should really
       // use FGMRES or GMRESR for this. However, here the solver
       // is so good that it'll converge very quickly anyway
       // so there isn't much to be gained by limiting the number
       // of iterations...
       prec_pt->max_iter() = 4;
       prec_pt->solver_pt()->solver_type() = TrilinosAztecOOSolver::CG;
       prec_pt->solver_pt()->disable_doc_time();
       return prec_pt;
 #else
       std::ostringstream err_msg;
       err_msg << "Inner CG preconditioner is unavailable.\n"
               << "Please install Trilinos.\n";
       throw OomphLibError(
         err_msg.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
 #endif
     } // function get_w_cg_preconditioner
References oomph::TrilinosAztecOOSolver::CG, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.