MercuryDPM: oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT > Class Template Reference
oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT > Class Template Reference
#include <temporary_stefan_boltzmann_elements.h>
Public Member Functions
StefanBoltzmannUnsteadyHeatFluxElement (FiniteElement *const &bulk_el_pt, const int &face_index)
StefanBoltzmannUnsteadyHeatFluxElement (const StefanBoltzmannUnsteadyHeatFluxElement &dummy)
Broken copy constructor.
void set_integration_scheme (Integral *const &integral_pt)
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void output_stefan_boltzmann_radiation (std::ostream &outfile)
Public Member Functions inherited from oomph::FaceElement
FaceElement ()
Constructor: Initialise all appropriate member data.
virtual ~FaceElement ()
Empty virtual destructor.
FaceElement (const FaceElement &)=delete
Broken copy constructor.
const unsigned & boundary_number_in_bulk_mesh () const
Broken assignment operator.
void set_boundary_number_in_bulk_mesh (const unsigned &b)
Set function for the boundary number in bulk mesh.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
double J_eulerian (const Vector< double > &s) const
double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
double interpolated_x (const Vector< double > &s, const unsigned &i) const
double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
void interpolated_x (const Vector< double > &s, Vector< double > &x) const
void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
int & normal_sign ()
int normal_sign () const
int & face_index ()
int face_index () const
const Vector< double > * tangent_direction_pt () const
Public access function for the tangent direction pointer.
void set_tangent_direction (Vector< double > *tangent_direction_pt)
Set the tangent direction vector.
void turn_on_warning_for_discontinuous_tangent ()
void turn_off_warning_for_discontinuous_tangent ()
void continuous_tangent_and_outer_unit_normal (const Vector< double > &s, Vector< Vector< double >> &tang_vec, Vector< double > &unit_normal) const
void continuous_tangent_and_outer_unit_normal (const unsigned &ipt, Vector< Vector< double >> &tang_vec, Vector< double > &unit_normal) const
void outer_unit_normal (const Vector< double > &s, Vector< double > &unit_normal) const
Compute outer unit normal at the specified local coordinate.
void outer_unit_normal (const unsigned &ipt, Vector< double > &unit_normal) const
Compute outer unit normal at ipt-th integration point.
FiniteElement *& bulk_element_pt ()
Pointer to higher-dimensional "bulk" element.
FiniteElement * bulk_element_pt () const
Pointer to higher-dimensional "bulk" element (const version)
CoordinateMappingFctPt & face_to_bulk_coordinate_fct_pt ()
CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt () const
BulkCoordinateDerivativesFctPt & bulk_coordinate_derivatives_fct_pt ()
BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt () const
Vector< double > local_coordinate_in_bulk (const Vector< double > &s) const
void get_local_coordinate_in_bulk (const Vector< double > &s, Vector< double > &s_bulk) const
void get_ds_bulk_ds_face (const Vector< double > &s, DenseMatrix< double > &dsbulk_dsface, unsigned &interior_direction) const
unsigned & bulk_position_type (const unsigned &i)
const unsigned & bulk_position_type (const unsigned &i) const
void bulk_node_number_resize (const unsigned &i)
Resize the storage for the bulk node numbers.
unsigned & bulk_node_number (const unsigned &n)
const unsigned & bulk_node_number (const unsigned &n) const
void bulk_position_type_resize (const unsigned &i)
Resize the storage for bulk_position_type to i entries.
unsigned & nbulk_value (const unsigned &n)
unsigned nbulk_value (const unsigned &n) const
void nbulk_value_resize (const unsigned &i)
void resize_nodes (Vector< unsigned > &nadditional_data_values)
void output_zeta (std::ostream &outfile, const unsigned &nplot)
Output boundary coordinate zeta.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::StefanBoltzmannRadiationBase
StefanBoltzmannRadiationBase ()
Constructor.
double *& sigma_pt ()
Pointer to non-dim Stefan Boltzmann constant.
double *& theta_0_pt ()
Pointer to non-dim zero centrigrade offset in Stefan Boltzmann law.
double sigma ()
Non-dim Stefan Boltzmann constant (switched off by default)
double theta_0 ()
double contribution_to_stefan_boltzmann_radiation (const Vector< double > &r_illuminated, const Vector< double > &n_illuminated, const Vector< unsigned > &visible_intpts_in_current_element)
double contribution_to_stefan_boltzmann_radiation (const Vector< double > &r_illuminated, const Vector< double > &n_illuminated, const Vector< unsigned > &visible_intpts_in_current_element, std::ofstream &outfile)
void wipe_stefan_boltzmann_illumination_info ()
Wipe illumination info.
void add_stefan_boltzmann_illumination_info (const unsigned &ipt, StefanBoltzmannRadiationBase *illuminating_el_pt, Vector< unsigned > &illuminating_integration_point_index, const bool &add_solid_position_data=true)
void output_stefan_boltzmann_radiation (std::ostream &outfile)
Output Stefan Boltzmann radiation: x,y,in,out,n_x,n_y.
void output_stefan_boltzmann_radiation_rays (std::ostream &outfile, const unsigned &integration_point=UINT_MAX)
double incoming_stefan_boltzmann_radiation (const unsigned &ipt, const Vector< double > &r_illuminated, const Vector< double > &n_illuminated)
Public Member Functions inherited from oomph::TemplateFreeUnsteadyHeatBaseFaceElement
TemplateFreeUnsteadyHeatBaseFaceElement ()
Constructor.
virtual ~TemplateFreeUnsteadyHeatBaseFaceElement ()
Destrutor.
UnsteadyHeatPrescribedFluxFctPt & flux_fct_pt ()
Access function for the prescribed-flux function pointer.
Public Member Functions inherited from oomph::SolarRadiationBase
SolarRadiationBase ()
Constructor.
void enable_smoothed_sun_shadow (const double &alpha_tanh_smooth_sun_shadow=100.0)
void disable_smoothed_sun_shadow ()
Disable smoothing of shadow.
bool smoothed_sun_shadow_is_enabled ()
Disable smoothing of shadow.
double alpha_tanh_smooth_sun_shadow ()
void update_limiting_angles (const Vector< Node * > &shielding_node_pt)
virtual double atmospheric_radiation (const unsigned &intpt, const double &time, const Vector< double > &x, const Vector< double > &n)
void output_diffuse_radiation_cone (std::ostream &outfile, const double &radius)
Output cone of diffuse radiation for all integration points.
void output_diffuse_radiation_cone_min_angle (std::ostream &outfile, const double &radius)
void output_diffuse_radiation_cone_max_angle (std::ostream &outfile, const double &radius)
void output_limiting_angles (std::ostream &outfile)
Output illumination angles for all integration points.
void output_atmospheric_radiation (std::ostream &outfile)
Output diffuse and direct radiation.
Public Member Functions inherited from oomph::UnsteadyHeatBaseFaceElement< ELEMENT >
UnsteadyHeatBaseFaceElement (FiniteElement *const &bulk_el_pt, const int &face_index)
Constructor.
virtual ~UnsteadyHeatBaseFaceElement ()
Destructor.
void interpolated_u (const Vector< double > &s, double &u)
Temperature at local coordinate s.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element residual vector.
void output (std::ostream &outfile)
Output function.
void output (std::ostream &outfile, const unsigned &n_plot)
void output (FILE *file_pt)
C_style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function.
Protected Member Functions
virtual void get_flux (const unsigned &ipt, const double &time, const Vector< double > &x, const Vector< double > &n, const double &u, double &flux)
Protected Member Functions inherited from oomph::FaceElement
void add_additional_values (const Vector< unsigned > &nadditional_values, const unsigned &id)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::UnsteadyHeatBaseFaceElement< ELEMENT >
double shape_and_test (const Vector< double > &s, Shape &psi, Shape &test) const
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Types inherited from oomph::TemplateFreeUnsteadyHeatBaseFaceElement
typedef void(* UnsteadyHeatPrescribedFluxFctPt) (const double &time, const Vector< double > &x, const Vector< double > &n, const double &u, double &flux)
Public Attributes inherited from oomph::SolarRadiationBase
void(*&)(const double &time, double &solar_flux_magnitude, Vector< double > &solar_flux_unit_vector, double &total_diffuse_radiation) atmospheric_radiation_fct_pt ()
Reference to the atmospheric radiation function pointer.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Attributes inherited from oomph::FaceElement
unsigned Boundary_number_in_bulk_mesh
The boundary number in the bulk mesh to which this element is attached.
FiniteElement * Bulk_element_pt
Pointer to the associated higher-dimensional "bulk" element.
Vector< unsigned > Bulk_node_number
Vector< unsigned > Nbulk_value
Vector< double > * Tangent_direction_pt
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::StefanBoltzmannRadiationBase
double * Sigma_pt
Pointer to non-dim Stefan Boltzmann constant.
double * Theta_0_pt
Pointer to non-dim zero centrigrade offset in Stefan Boltzmann law.
Vector< Vector< std::pair< StefanBoltzmannRadiationBase *, Vector< unsigned > > > > Stefan_boltzmann_illumination_info
Protected Attributes inherited from oomph::TemplateFreeUnsteadyHeatBaseFaceElement
unsigned U_index_ust_heat
Index at which temperature is stored.
unsigned Dim
The spatial dimension of the problem.
UnsteadyHeatPrescribedFluxFctPt Flux_fct_pt
Function pointer to the (global) prescribed-flux function.
Protected Attributes inherited from oomph::SolarRadiationBase
bool Smoothed_sun_shadow
Use tanh profile to smooth solar shadows.
double Alpha_tanh_smooth_sun_shadow
Factor for tanh profile to smooth solar shadows.
Vector< std::pair< double, double > > Diffuse_limit_angles
void(* Atmospheric_radiation_fct_pt)(const double &time, double &solar_flux_magnitude, Vector< double > &solar_flux_unit_vector, double &total_diffuse_radiation)
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<class ELEMENT>
class oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >
////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// A class for elements that allow the imposition of (mutual) Stefan Boltzmann heat flux on the boundaries of UnsteadyHeat elements. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
Constructor & Destructor Documentation
StefanBoltzmannUnsteadyHeatFluxElement() [1/2]
template<class ELEMENT > oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::StefanBoltzmannUnsteadyHeatFluxElement (FiniteElement *const & bulk_el_pt, const int & face_index)
Constructor, takes the pointer to the "bulk" element and the index of the face to be created
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Constructor, takes the pointer to the "bulk" element and the index of the face to be created.
                                                               :
 UnsteadyHeatBaseFaceElement<ELEMENT>(bulk_el_pt,face_index)
 {
 #ifdef PARANOID
     {
      //Check that the element is not a refineable 3d element
      if(bulk_el_pt->dim()==3)
       {
        //Is it refineable
        if(dynamic_cast<RefineableElement*>(bulk_el_pt))
         {
          //Issue a warning
          std::string error_string=
           "This face element will not work correctly if nodes are hanging.\n";
          error_string+="Use the refineable version instead. ";
          OomphLibWarning(error_string,
                          OOMPH_CURRENT_FUNCTION,
                          OOMPH_EXCEPTION_LOCATION);
         }
       }
     }
 #endif
 #ifdef PARANOID
  // Check spatial dimension
  if (Dim!=2)
   {
    //Issue a warning
    throw OomphLibError(
     "This element will almost certainly not work in non-2D problems, though it should be easy enough to upgrade... Volunteers?\n",
     OOMPH_CURRENT_FUNCTION,
     OOMPH_EXCEPTION_LOCATION);
   }
 #endif
 }
References oomph::TemplateFreeUnsteadyHeatBaseFaceElement::Dim, oomph::FiniteElement::dim(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
StefanBoltzmannUnsteadyHeatFluxElement() [2/2]
template<class ELEMENT > oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::StefanBoltzmannUnsteadyHeatFluxElement (const StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT > & dummy) inline
Broken copy constructor.
   {
    BrokenCopy::broken_copy("StefanBoltzmannUnsteadyHeatFluxElement");
   }
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
get_flux()
template<class ELEMENT > virtual void oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::get_flux (const unsigned & ipt, const double & time, const Vector< double > & x, const Vector< double > & n, const double & u, double & flux) inline protected virtual
Overload the function that determines the prescribed flux at a given spatial position, x, the outer unit normal, n, and the continuous time. We also allow an explicit dependendence on the integration point, ipt, and the actual local "temperature", u – just what is needed for this case we have here, where the net flux is determined by the balance between incoming and outgoing Stefan Boltzmann radiation. The dependence on u makes the problem highly nonlinear – Jacobian is currently worked out by finite differencing.
Reimplemented from oomph::TemplateFreeUnsteadyHeatBaseFaceElement.
  {
 #ifdef PARANOID
   // We shouldn't really have an externally imposed flux (cos it's ignored)
   if (Flux_fct_pt != 0)
    {
     //Issue a warning
     OomphLibWarning("Flux_fct_pt is ignored in this element\n",
                     OOMPH_CURRENT_FUNCTION,
                     OOMPH_EXCEPTION_LOCATION);
    }
 #endif
   // Outgoing Stefan Boltzmann radiation in terms of pre-computed
   // local temperature
   double outgoing_sb_radiation=this->sigma()*pow((u+this->theta_0()),4);
   // Incoming Stefan Boltzmann radiation
   double incoming_sb_radiation=incoming_stefan_boltzmann_radiation(ipt,x,n);
   // Atmospheric radiation
   double incoming_atmospheric=atmospheric_radiation(ipt,time,x,n);
   // Net flux
   flux=incoming_sb_radiation-outgoing_sb_radiation+incoming_atmospheric;
  }
References oomph::SolarRadiationBase::atmospheric_radiation(), ProblemParameters::flux(), oomph::TemplateFreeUnsteadyHeatBaseFaceElement::Flux_fct_pt, oomph::StefanBoltzmannRadiationBase::incoming_stefan_boltzmann_radiation(), n, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, Eigen::bfloat16_impl::pow(), oomph::StefanBoltzmannRadiationBase::sigma(), oomph::StefanBoltzmannRadiationBase::theta_0(), and plotDoE::x.
Referenced by oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::output_stefan_boltzmann_radiation().
output_stefan_boltzmann_radiation()
template<class ELEMENT > void oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::output_stefan_boltzmann_radiation (std::ostream & outfile) inline
Generalised output function to include stefan boltzmann information: temperature, total incoming flux, incoming s.b. flux, outgoing s.b. flux, outer unit normal. Note that total incoming flux is simply given by difference between incoming and outgoing radiation since we don't allow any user-specified additional flux (the get_flux(...) function has been overloaded.
  {
   unsigned n_dim = this->nodal_dimension();
   Vector<double> x(n_dim);
   Vector<double> s(n_dim-1);
   Vector<double> unit_normal(n_dim);
   // Get continuous time from timestepper of first node
   double time=node_pt(0)->time_stepper_pt()->time_pt()->time();
   // Number of integration points
   unsigned n_intpt = integral_pt()->nweight();
   outfile << "ZONE\n";
   //Loop over the integration points
   for(unsigned ipt=0;ipt<n_intpt;ipt++)
    {
     // Local coordinate of integration point
     for (unsigned i=0;i<n_dim-1;i++)
      {
       s[i]=integral_pt()->knot(ipt,i);
      }
     // Get Eulerian coordinates
     this->interpolated_x(s,x);
     // Get temperature
     double interpolated_u=0;
     this->interpolated_u(s,interpolated_u);
     // Outer unit normal
     outer_unit_normal(s,unit_normal);
     // Outgoing Stefan Boltzmann radiation
     double outgoing_sb_radiation=
      this->sigma()*pow((interpolated_u+this->theta_0()),4);
     // Incoming Stefan Boltzmann radiation
     double incoming_sb_radiation=incoming_stefan_boltzmann_radiation
      (ipt,x,unit_normal);
     // Get the net incoming flux (should be the difference between
     // the two previous ones!
     double flux=0.0;
     get_flux(ipt,time,x,unit_normal,interpolated_u,flux);
 // hierher paranoidify
 //#ifdef PARANOID
      if (fabs(flux-(incoming_sb_radiation-outgoing_sb_radiation)))
      {
       std::stringstream error_message;
       error_message
        << "Difference between incoming ( " << incoming_sb_radiation
        << " ) and outgoing ( " << outgoing_sb_radiation << " ) is "
        << (incoming_sb_radiation-outgoing_sb_radiation)
        << " but total flux is " << flux << " so difference is "
        << fabs(flux-(incoming_sb_radiation-outgoing_sb_radiation));
       throw OomphLibError(
        error_message.str(),
        OOMPH_CURRENT_FUNCTION,
        OOMPH_EXCEPTION_LOCATION);
      }
 //#endif
     //Output the x,y,..
     for(unsigned i=0;i<n_dim;i++)
      {
       outfile << x[i] << " ";
      }
     // Temperature
     outfile << interpolated_u << " ";
     // Total incoming flux (may include additional contributions)
     outfile << flux << " ";
     // Incoming sb flux
     outfile << incoming_sb_radiation << " ";
     // Outgoing sb flux
     outfile << outgoing_sb_radiation << " ";
     // Outer unit normal
     for(unsigned i=0;i<n_dim;i++)
      {
       outfile << unit_normal[i] << " ";
      }
     outfile << std::endl;
    }
  }
References boost::multiprecision::fabs(), ProblemParameters::flux(), oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::get_flux(), i, oomph::StefanBoltzmannRadiationBase::incoming_stefan_boltzmann_radiation(), oomph::FiniteElement::integral_pt(), oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::interpolated_u(), oomph::FaceElement::interpolated_x(), oomph::Integral::knot(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::FaceElement::outer_unit_normal(), Eigen::bfloat16_impl::pow(), s, oomph::StefanBoltzmannRadiationBase::sigma(), oomph::StefanBoltzmannRadiationBase::theta_0(), oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Data::time_stepper_pt(), and plotDoE::x.
Referenced by StefanBoltzmannProblem< ELEMENT >::doc_solution().
set_integration_scheme()
template<class ELEMENT > void oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::set_integration_scheme (Integral *const & integral_pt) inline virtual
Change integration scheme (overloads underlying version and and resizes lookup schemes introduced in this class.
Reimplemented from oomph::FiniteElement.
  {
   FiniteElement::set_integration_scheme(integral_pt);
   unsigned n_intpt = integral_pt->nweight();
   Stefan_boltzmann_illumination_info.resize(n_intpt);
  }
References oomph::FiniteElement::integral_pt(), oomph::Integral::nweight(), oomph::FiniteElement::set_integration_scheme(), and oomph::StefanBoltzmannRadiationBase::Stefan_boltzmann_illumination_info.
Referenced by StefanBoltzmannProblem< ELEMENT >::create_melt_elements(), StefanBoltzmannProblem< ELEMENT >::create_sb_elements(), and StefanBoltzmannProblem< ELEMENT >::StefanBoltzmannProblem().
zeta_nodal()
template<class ELEMENT > double oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const inline virtual
Specify the value of nodal zeta from the face geometry: The "global" intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Reimplemented from oomph::UnsteadyHeatBaseFaceElement< ELEMENT >.
  {return FaceElement::zeta_nodal(n,k,i);}
References i, k, n, and oomph::FaceElement::zeta_nodal().
The documentation for this class was generated from the following file:
temporary_stefan_boltzmann_elements.h