MercuryDPM: oomph::HalfEllipse Class Reference
oomph::HalfEllipse Class Reference
My own Ellipse class.
#include <half_rectangle_with_hole_mesh.h>
Public Member Functions
HalfEllipse (const double &centre_z, const double &a, const double &b)
Constructor.
~HalfEllipse ()
Destructor (empty)
void position (const Vector< double > &xi, Vector< double > &r) const
Return the position of the Half Ellipse.
double & centre_z ()
Access to z-coordinate of centre.
double & a ()
Access to r-half axis.
double & b ()
Access to z-half axis.
HalfEllipse (const double &centre_z, const double &a, const double &b)
Constructor.
~HalfEllipse ()
Destructor (empty)
void position (const Vector< double > &xi, Vector< double > &r) const
Return the position of the Half Ellipse.
double & centre_z ()
Access to z-coordinate of centre.
double & a ()
Access to r-half axis.
double & b ()
Access to z-half axis.
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual unsigned ngeom_data () const
virtual Data * geom_data_pt (const unsigned &j)
virtual void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Private Attributes
double Centre_z
z-coordinate of centre
double A
r-half axis
double B
z-half axis
Additional Inherited Members
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
My own Ellipse class.
Constructor & Destructor Documentation
HalfEllipse() [1/2]
oomph::HalfEllipse::HalfEllipse (const double & centre_z, const double & a, const double & b) inline
Constructor.
   : GeomObject(1,2), Centre_z(centre_z), A(a), B(b)
   {}
~HalfEllipse() [1/2]
oomph::HalfEllipse::~HalfEllipse () inline
Destructor (empty)
 {}
HalfEllipse() [2/2]
oomph::HalfEllipse::HalfEllipse (const double & centre_z, const double & a, const double & b) inline
Constructor.
   : GeomObject(1,2), Centre_z(centre_z), A(a), B(b)
   {}
~HalfEllipse() [2/2]
oomph::HalfEllipse::~HalfEllipse () inline
Destructor (empty)
 {}
Member Function Documentation
a() [1/2]
double& oomph::HalfEllipse::a () inline
Access to r-half axis.
 {return A;}
a() [2/2]
double& oomph::HalfEllipse::a () inline
Access to r-half axis.
 {return A;}
b() [1/2]
double& oomph::HalfEllipse::b () inline
Access to z-half axis.
 {return B;}
b() [2/2]
double& oomph::HalfEllipse::b () inline
Access to z-half axis.
 {return B;}
centre_z() [1/2]
double& oomph::HalfEllipse::centre_z () inline
Access to z-coordinate of centre.
 {return Centre_z;}
centre_z() [2/2]
double& oomph::HalfEllipse::centre_z () inline
Access to z-coordinate of centre.
 {return Centre_z;}
position() [1/2]
void oomph::HalfEllipse::position (const Vector< double > & xi, Vector< double > & r) const inline virtual
Return the position of the Half Ellipse.
Implements oomph::GeomObject.
   {
    r[0] = A*sin(xi[0]);
    r[1] = Centre_z + B*cos(xi[0]);
   }
References cos(), UniformPSDSelfTest::r, and sin().
position() [2/2]
void oomph::HalfEllipse::position (const Vector< double > & xi, Vector< double > & r) const inline virtual
Return the position of the Half Ellipse.
Implements oomph::GeomObject.
   {
    r[0] = A*sin(xi[0]);
    r[1] = Centre_z + B*cos(xi[0]);
   }
References cos(), UniformPSDSelfTest::r, and sin().
Member Data Documentation
A
double oomph::HalfEllipse::A private
r-half axis
B
double oomph::HalfEllipse::B private
z-half axis
Centre_z
double oomph::HalfEllipse::Centre_z private
z-coordinate of centre
The documentation for this class was generated from the following file:
axisym_heat_sphere/half_rectangle_with_hole_mesh.h