MercuryDPM: loop_on_k< M, N, K > Struct Template Reference
loop_on_k< M, N, K > Struct Template Reference
Static Public Member Functions
static void run ()
Member Function Documentation
run()
template<int M, int N, int K> static void loop_on_k< M, N, K >::run () inline static
                     {
     std::cout << "K=" << K << "\t";
     print_n<N>::run();
     std::cout << "\n";
     loop_on_m<M, N, K>::run();
     std::cout << "\n\n";
     loop_on_k<M, N, K + 1>::run();
   }
References PlanarWave::K, loop_on_m< M, N, K >::run(), and print_n< N >::run().
Referenced by main().
The documentation for this struct was generated from the following file:
product_threshold.cpp