MercuryDPM: TangentialSpringUnitTest.cpp File Reference
TangentialSpringUnitTest.cpp File Reference
#include <iostream>
#include "Species/LinearViscoelasticSlidingFrictionSpecies.h"
#include "DPMBase.h"
#include "Logger.h"
Classes
class TangentialSpringUnitTest
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
 {
     TangentialSpringUnitTest tangentialSpringUnitTestProblem;
     tangentialSpringUnitTestProblem.setName("TangentialSpringUnitTest");
     //set the species properties, with a very large sliding friction coefficient
     auto species = tangentialSpringUnitTestProblem.speciesHandler.copyAndAddObject(
             LinearViscoelasticSlidingFrictionSpecies());
     species->setDensity(6. / constants::pi);
     species->setCollisionTimeAndRestitutionCoefficient(1e-3, .2, 1. / 8);
     species->setSlidingStiffness(species->getStiffness() * 2 / 7);
     species->setSlidingFrictionCoefficient(1e20);
     //set simulation-parameters: time, time step, gravity, output-file properties
     tangentialSpringUnitTestProblem.setTimeStep(2e-5);
     tangentialSpringUnitTestProblem.setFileType(FileType::NO_FILE);
     tangentialSpringUnitTestProblem.setGravity(Vec3D(0, 0, -1));
     tangentialSpringUnitTestProblem.setTimeMax(2.5);
     //solve the system
     tangentialSpringUnitTestProblem.solve(argc, argv);
     //Test if particles have the correct position and velocity
     BaseParticle* p = tangentialSpringUnitTestProblem.particleHandler.getObject(0);
     logger.assert_always(p->getPosition().isEqualTo(Vec3D(0.5, 0.5, 0.25), 1e-7),
                          "First particles is in the wrong position. It is %", p->getPosition());
     logger.assert_always(p->getVelocity().isEqualTo(Vec3D(0.0, 0.0, 0.0), 1e-7),
                          "First particle has the wrong velocity. It is %", p->getVelocity());
     p = tangentialSpringUnitTestProblem.particleHandler.getObject(1);
     Vec3D expectedPosition = Vec3D(0.96152405440385, 0.5, 0.45015310115274);
     logger.assert_always((p->getPosition().isEqualTo(expectedPosition, 1e-7)),
                          "Second particle has the wrong position. It is %g at time % (should be %g)", p->getPosition(),
                          tangentialSpringUnitTestProblem.getTime(), expectedPosition);
     Vec3D expectedVelocity = Vec3D(0.32586989790503, 0, -0.62325101431855);
     logger.assert_always(p->getVelocity().isEqualTo(expectedVelocity, 1e-7),
                          "Second particle has the wrong velocity. It is %g (should be %g)", p->getVelocity(), expectedVelocity);
     Vec3D expectedAngularVelocity = Vec3D(0.0, 2.118966061231, 0.0);
     logger.assert_always(p->getAngularVelocity().isEqualTo(expectedAngularVelocity, 1e-7),
             "Second particles has the wrong angular velocity. It is %g (should be %g)", p->getAngularVelocity(), expectedAngularVelocity);
 }
References BaseHandler< T >::copyAndAddObject(), e(), BaseHandler< T >::getObject(), DPMBase::getTime(), logger, NO_FILE, p, DPMBase::particleHandler, constants::pi, DPMBase::setFileType(), DPMBase::setGravity(), DPMBase::setName(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), DPMBase::solve(), and DPMBase::speciesHandler.