MercuryDPM: CGHandler Class Reference
CGHandler Class Reference
Container that stores all CG objects.
#include <CGHandler.h>
Public Member Functions
CGHandler ()=default
Default constructor, creates an empty CGHandler.
CGHandler (const CGHandler &BH)
Copy constructor, copies the CGHandler and all BaseCGPoint's it contains.
CGHandler & operator= (const CGHandler &rhs)
Assignment operator that copies the pointer to the DPMBase and all objects.
~CGHandler () final=default
Destructor, destructs the CGHandler and all BaseCGPoint's it contains.
void addObject (BaseCG *cg) final
std::string getName () const final
void readAndAddObject (std::istream &is) final
Reads objects into the CGHandler from an istream (currently not implemented).
void write (std::ostream &os) const
Writes objects into the CGHandler to an ostream (currently not implemented).
void initialise ()
Contains the code executed before the first time step.
void evaluate ()
Contains the code executed at each time step.
void finish ()
Contains the code executed after the last time step.
void restart (std::string name)
loads restart file, before evaluateDataFiles is run
void restartAndEvaluateRestartFiles (const std::string &name)
void restartAndEvaluateDataFiles (const std::string &name, bool evaluateFStatFiles=true)
bool evaluateDataFiles (bool evaluateFStatFiles=true)
does the same as StatisticsVector::statistics_from_fstat_and_data: loads a restart file (if existing), then several data files, and fstat files (if existing)
bool evaluateRestartFiles ()
void computeContactPoints ()
Mdouble getTimeMin ()
Mdouble getTimeMax ()
void setInitialFileCounter (unsigned initialFileCounter)
unsigned getInitialFileCounter () const
Mdouble getPreviousEvaluationTime ()
Returns the time of the last read/evaluated time step.
void setPreviousEvaluationTime (Mdouble time)
Sets the time of the last read/evaluated time step to a specified time.
void setPreviousEvaluationTimeToCurrentTime ()
Sets the previous evaluation time to the current time.
void setPreviousPositionToCurrentPosition ()
Sets the previous position for every particle to its current position.
void handlePreviousInformation ()
Sets data from the current time step as data from the previous time step.
Public Member Functions inherited from BaseHandler< BaseCG >
BaseHandler ()
Default BaseHandler constructor, it creates an empty BaseHandler and assigns DPMBase_ to a null pointer.
BaseHandler (const BaseHandler< BaseCG > &BH)
Constructor that copies the objects of the given handler into itself and sets other variables to 0/nullptr.
virtual ~BaseHandler ()
Destructor, it destructs the BaseHandler and all Object it contains.
void copyContentsFromOtherHandler (const BaseHandler< BaseCG > &BH)
Function that copies the contents (vector of pointers, maxObject_, nextId_, DPMBase_) from one handler (container) to the other.
std::enable_if<!std::is_pointer< U >::value, U * >::type copyAndAddObject (const U &object)
Creates a copy of a Object and adds it to the BaseHandler.
std::enable_if< std::is_pointer< U >::value, U >::type copyAndAddObject (const U object)
Creates a copy of a Object and adds it to the BaseHandler.
std::enable_if<!std::is_pointer< U >::value, U * >::type copyAndAddGhostObject (const U &object)
Creates a copy of a Object and adds it to the BaseHandler. This is one locally for inserting mpi particles, they avoid the global check if the particle can actually be inserted, because the mpi domain already knows that is the case.
std::enable_if< std::is_pointer< U >::value, U >::type copyAndAddGhostObject (const U object)
Creates a copy of a Object and adds it to the BaseHandler. This is one locally for inserting mpi particles, they avoid the global check if the particle can actually be inserted, because the mpi domain already knows that is the case.
virtual void addExistingObject (BaseCG *O)
Adds an existing object to the BaseHandler without changing the id of the object.
virtual void addObject (BaseCG *object)
Adds a new Object to the BaseHandler.
virtual void addGhostObject (BaseCG *O)
Adds a new Object to the BaseHandler. called by the to avoid increasing the id.
void removeIf (const std::function< bool(BaseCG *)> cond)
virtual void removeObject (unsigned const int index)
Removes an Object from the BaseHandler.
virtual void removeObjects (std::vector< unsigned int > indices)
void removeLastObject ()
Removes the last Object from the BaseHandler.
virtual void clear ()
Empties the whole BaseHandler by removing all Objects and setting all other variables to 0.
void read (std::istream &is)
Reads all objects from restart data.
BaseCG * getObjectById (const unsigned int id)
Gets a pointer to the Object at the specified index in the BaseHandler.
std::vector< BaseCG * > getObjectsById (const unsigned int id)
Gets a vector of pointers to the objects with the specific id.
BaseCG * getObject (const unsigned int id)
Gets a pointer to the Object at the specified index in the BaseHandler.
const BaseCG * getObject (const unsigned int id) const
Gets a constant pointer to the Object at the specified index in the BaseHandler.
BaseCG * getLastObject ()
Gets a pointer to the last Object in this BaseHandler.
const BaseCG * getLastObject () const
Gets a constant pointer to the last Object in this BaseHandler.
virtual unsigned int getNumberOfObjects () const
Gets the number of real Object in this BaseHandler. (i.e. no mpi or periodic particles)
unsigned int getSize () const
Gets the size of the particleHandler (including mpi and periodic particles)
unsigned int getStorageCapacity () const
Gets the storage capacity of this BaseHandler.
void setStorageCapacity (const unsigned int N)
Sets the storage capacity of this BaseHandler.
void resize (const unsigned int N, const BaseCG &obj)
Resizes the container to contain N elements.
const std::vector< BaseCG * >::const_iterator begin () const
Gets the begin of the const_iterator over all Object in this BaseHandler.
const std::vector< BaseCG * >::iterator begin ()
Gets the begin of the iterator over all BaseBoundary in this BaseHandler.
const std::vector< BaseCG * >::const_iterator end () const
Gets the end of the const_iterator over all BaseBoundary in this BaseHandler.
const std::vector< BaseCG * >::iterator end ()
Gets the end of the iterator over all BaseBoundary in this BaseHandler.
void setDPMBase (DPMBase *DPMBase)
Sets the problem that is solved using this handler.
void setId (BaseCG *object, unsigned int id)
void increaseId ()
unsigned int getNextId ()
void setNextId (unsigned int id)
DPMBase * getDPMBase ()
Gets the problem that is solved using this handler.
DPMBase * getDPMBase () const
Gets the problem that is solved using this handler and does not change the class.
virtual void writeVTK () const
now empty function for writing VTK files.
unsigned getNextGroupId ()
Should be called each time you assign a groupId. Returns the value of nextGroupId_ and increases nextGroupId_ by one.
Public Attributes
unsigned initialFileCounter = 0
Private Attributes
Mdouble previousEvaluationTime_ = 0
Saves the time of the last read/evaluated data/restartFile.
Additional Inherited Members
Protected Attributes inherited from BaseHandler< BaseCG >
std::vector< BaseCG * > objects_
The actual list of Object pointers.
Detailed Description
Container that stores all CG objects.
Todo:
get function that by default can distinguish species, but also density
make tests
change output format
command line arguments
make more readable definitions
read (a) restart, (b) data/fstat files
add speed by using the mesh
introduce standardDev
add 2D support
do we need to store the BaseObject::index_ anymore?
Can Interaction inherit directly from BaseInteraction?
make Files::statFile_, ... public, like the handlers; remove get functions for File's and handlers.
take out dependence on DPMBase::statFile (i.e. the savecount)
TW note, to keep the code working on Windows:
std::exit requires correct header cstdlib,
don't use toString (thanks to Silvia for debugging)
The CGHandler stores all CG objects. Its member functions initialise, evaluate, and finish are called by the DPMBase before, during and after the time loop, respectively, and call the member functions initialise, evaluate, and finish of each CG object.
See also: MercuryCG: Post-processing discrete particle data using the coarse-graining formulation (in development).
Constructor & Destructor Documentation
CGHandler() [1/2]
CGHandler::CGHandler () default
Default constructor, creates an empty CGHandler.
CGHandler() [2/2]
CGHandler::CGHandler (const CGHandler & ch)
Copy constructor, copies the CGHandler and all BaseCGPoint's it contains.
Parameters
[in] ch The CGHandler that has to be copied.
         : BaseHandler(ch)
 {
     setDPMBase(ch.getDPMBase());
     //copyContentsFromOtherHandler(ch);
 }
References BaseHandler< T >::getDPMBase(), and BaseHandler< BaseCG >::setDPMBase().
~CGHandler()
CGHandler::~CGHandler () final default
Destructor, destructs the CGHandler and all BaseCGPoint's it contains.
Member Function Documentation
addObject()
void CGHandler::addObject (BaseCG * cg) final
Parameters
[in] cg A pointer to the CG object that has to be added to the handler.
 {
     //Puts the cg object in the list
     BaseHandler<BaseCG>::addObject(cg);
     //set the CGHandler pointer
     cg->setHandler(this);
 }
References BaseHandler< T >::addObject(), and BaseCG::setHandler().
computeContactPoints()
void CGHandler::computeContactPoints ()
 {
     //recompute contact point (necessary for old restart files)
     for (BaseInteraction* const c : getDPMBase()->interactionHandler)
     {
         if (c->getContactPoint().isNaN())
         {
             const Vec3D& p = c->getP()->getPosition();
             const Vec3D& i = c->getI()->getPosition();
             const BaseParticle* const PParticle = dynamic_cast<BaseParticle*>(c->getP());
             const BaseParticle* const IParticle = dynamic_cast<BaseParticle*>(c->getI());
             if (IParticle != nullptr)
             {
                 const Vec3D branchVector = p - i;
                 const Mdouble distance = branchVector.getLength();
                 c->setNormal(branchVector / distance);
                 c->setOverlap(PParticle->getRadius() + IParticle->getRadius() - distance);
                 c->setDistance(distance);
                 c->setContactPoint(p - (PParticle->getRadius() - 0.5 * c->getOverlap()) * c->getNormal());
             }
             else
             {
                 const InfiniteWall* const IWall = dynamic_cast<InfiniteWall*>(c->getI());
                 if (IWall != nullptr)
                 {
                     const Mdouble dist = Vec3D::dot(i - p, IWall->getNormal());
                     const Mdouble r = dynamic_cast<BaseParticle*>(c->getP())->getRadius();
                     const Vec3D branch = (0.5 * (dist + r)) * IWall->getNormal();
                     c->setNormal(-IWall->getNormal());
                     c->setContactPoint(p + branch);
                 }
                 else
                 {
                     const Vec3D IP = p - i;
                     const Mdouble distance = Vec3D::getLength(IP);
                     c->setNormal(IP / distance);
                     c->setContactPoint(i);
                 }
             }
             //logger(INFO,"c%",c->getContactPoint());
             static bool firstTime = true;
             if (firstTime)
             {
                 cgLogger(WARN,
                          "recomputing contact point, as contact point information is not available\n"
                          "Contact point is placed assuming spherical particles\n"
                          "Complex walls, non-spherical particles, periodic walls can create errors");
                 firstTime = false;
             }
         }
     }
 }
References calibrate::c, cgLogger, Vec3D::dot(), BaseHandler< BaseCG >::getDPMBase(), Vec3D::getLength(), InfiniteWall::getNormal(), BaseParticle::getRadius(), i, p, UniformPSDSelfTest::r, and WARN.
Referenced by evaluateRestartFiles().
evaluate()
void CGHandler::evaluate ()
Contains the code executed at each time step.
 {
     //evaluate all CG objects in the handler
     for (BaseCG* it : *this)
     {
         //if we are below timeMax and the next time step should be written
         if (it->getTimeMin() <= getDPMBase()->getTime() && it->getTimeMax() > getDPMBase()->getTime()
             && it->statFile.saveCurrentTimeStep(getDPMBase()->getNumberOfTimeSteps()))
         {
             //logger(INFO,"evaluate %, nt=%",it->statFile.getName(), getDPMBase()->getNumberOfTimeSteps());
             it->statFile.setLastSavedTimeStep(getDPMBase()->getNumberOfTimeSteps());
             it->evaluate();
         }
     }
     // Remember information from this read
     handlePreviousInformation();
 };
References BaseCG::evaluate(), BaseHandler< BaseCG >::getDPMBase(), BaseCG::getTimeMax(), BaseCG::getTimeMin(), handlePreviousInformation(), File::saveCurrentTimeStep(), File::setLastSavedTimeStep(), and BaseCG::statFile.
Referenced by evaluateDataFiles(), evaluateRestartFiles(), and DPMBase::writeOutputFiles().
evaluateDataFiles()
bool CGHandler::evaluateDataFiles (bool evaluateFStatFiles = true)
does the same as StatisticsVector::statistics_from_fstat_and_data: loads a restart file (if existing), then several data files, and fstat files (if existing)
Todo:
use ignore if time is out of bounds
 {
 #ifdef MERCURYDPM_USE_MPI
     //Make sure that the number of processors is equal to the number of processors used for the run
     MPIContainer& communicator = MPIContainer::Instance();
     std::vector<unsigned> numberOfDomains = this->getDPMBase()->getNumberOfDomains();
     int numberOfRequiredProcessors = numberOfDomains[0]*numberOfDomains[1]*numberOfDomains[2];
     if(!(numberOfRequiredProcessors == communicator.getNumberOfProcessors()))
     {
         if (communicator.getProcessorID() == 0)
         {
             logger(ERROR,"Please re-run the program with % cores",numberOfRequiredProcessors);
         }
         else
         {
             std::exit(-1);
         }
     }
 #endif
     // reset counters so reading begins with the first data/fstat file
     DPMBase* const dpm = getDPMBase();
     //dpm->interactionHandler.clear();
     dpm->dataFile.setCounter(initialFileCounter);
     dpm->fStatFile.setCounter(initialFileCounter);
     initialise();
     // return false if no data file can be read
     if (!dpm->readNextDataFile()) return false;
     //define and check time limits
     const Mdouble timeMin = getTimeMin();
     const Mdouble timeMax = getTimeMax();
     if (dpm->getTime() > timeMax)
     {
         logger(ERROR, "Time stamp of initial data file (%) is beyond the maximum cg time (tMax=%)", dpm->getTime(),
                timeMax);
     }
     else
         while (dpm->getTime() < timeMin)
         {
             // Remember information from this read
             handlePreviousInformation();
             if (evaluateFStatFiles) dpm->readNextFStatFile();
             cgLogger(INFO, "Skipped %, t = %, because time is below tMin = %", dpm->dataFile.getFullName(),
                      dpm->getTime(), timeMin);
             dpm->readNextDataFile();
         }
     // read data file
     do
     {
         if (evaluateFStatFiles) dpm->readNextFStatFile();
         evaluate();
         cgLogger(INFO, "Evaluated %: t=%, Np=%, Nc=%", dpm->dataFile.getFullName()+(evaluateFStatFiles?" and "+dpm->fStatFile.getFullName():""), dpm->getTime(), dpm->particleHandler.getSize(), dpm->interactionHandler.getNumberOfObjects());
     } while (dpm->readNextDataFile() && getDPMBase()->getTime() <= timeMax);
     cgLogger(INFO, "Finished reading from %", dpm->dataFile.getFullName());
     finish();
     dpm->dataFile.close();
     return true;
 }
References cgLogger, File::close(), DPMBase::dataFile, ERROR, evaluate(), finish(), DPMBase::fStatFile, BaseHandler< BaseCG >::getDPMBase(), File::getFullName(), DPMBase::getNumberOfDomains(), BaseHandler< T >::getNumberOfObjects(), MPIContainer::getNumberOfProcessors(), MPIContainer::getProcessorID(), BaseHandler< T >::getSize(), DPMBase::getTime(), getTimeMax(), getTimeMin(), handlePreviousInformation(), INFO, initialFileCounter, initialise(), MPIContainer::Instance(), DPMBase::interactionHandler, logger, DPMBase::particleHandler, DPMBase::readNextDataFile(), DPMBase::readNextFStatFile(), and File::setCounter().
Referenced by commandLineCG(), and restartAndEvaluateDataFiles().
evaluateRestartFiles()
bool CGHandler::evaluateRestartFiles ()
 {
 #ifdef MERCURYDPM_USE_MPI
     //Make sure that the number of processors is equal to the number of processors used for the run
     MPIContainer& communicator = MPIContainer::Instance();
     std::vector<unsigned> numberOfDomains = this->getDPMBase()->getNumberOfDomains();
     int numberOfRequiredProcessors = numberOfDomains[0]*numberOfDomains[1]*numberOfDomains[2];
     if(!(numberOfRequiredProcessors == communicator.getNumberOfProcessors()))
     {
         if (communicator.getProcessorID() == 0)
         {
             logger(ERROR,"Please re-run the program with % cores",numberOfRequiredProcessors);
         }
         else
         {
             std::exit(-1);
         }
     }
 #endif
     // reset counters so reading begins with the first data/fstat file
     DPMBase* const dpm = getDPMBase();
     //define and check time limits
     Mdouble timeMin = getTimeMin();
     Mdouble timeMax = getTimeMax();
     if (getDPMBase()->getTime() > timeMax)
     {
         logger(ERROR, "initial restart file (t=%) is beyond the maximum cg time (tMax=%)", dpm->getTime(), timeMax);
     }
     else
         while (getDPMBase()->getTime() < timeMin)
         {
             // Remember information from this read
             handlePreviousInformation();
             cgLogger(INFO, "Skipped %, t = %, because time is below tMin = %", dpm->restartFile.getFullName(),
                      dpm->getTime(), timeMin);
             //the particle and wall handler is cleared here, because  BaseSpecies doesn't delete particles belonging to it
             dpm->particleHandler.clear();
             dpm->wallHandler.clear();
             dpm->readRestartFile();
         }
     //call initialise to set up mesh, stat files, etc
     initialise();
     // evaluate restart files, starting with the one already read (since interactions where not read)
     while (dpm->readRestartFile() && getDPMBase()->getTime() < timeMax)
     {
         cgLogger(INFO, "Read %, t=%, Np=%, Nc=%", dpm->restartFile.getFullName(), dpm->getTime(),
                  dpm->particleHandler.getSize(), dpm->interactionHandler.getNumberOfObjects());
         //recompute contact point (necessary for old restart files)
         computeContactPoints();
         evaluate();
         //the particle and wall handler is cleared here, because  BaseSpecies doesn't delete particles belonging to it
         dpm->particleHandler.clear();
         dpm->wallHandler.clear();
         //continue if the next restart file can be read and the max time has not been reached
         if (dpm->restartFile.getFileType()==FileType::ONE_FILE) {
             logger(INFO,"Note: the evaluation is based on a single restart file. Please switch output to FileType::MULTIPLE_FILES if you want to coarse grain over multiple time steps");
             break;
         }
     }
     cgLogger(INFO, "Finished reading from %", dpm->restartFile.getFullName());
     finish();
     dpm->dataFile.close();
     return true;
 }
References cgLogger, BaseHandler< T >::clear(), ParticleHandler::clear(), File::close(), computeContactPoints(), DPMBase::dataFile, ERROR, evaluate(), finish(), BaseHandler< BaseCG >::getDPMBase(), File::getFileType(), File::getFullName(), DPMBase::getNumberOfDomains(), BaseHandler< T >::getNumberOfObjects(), MPIContainer::getNumberOfProcessors(), MPIContainer::getProcessorID(), BaseHandler< T >::getSize(), DPMBase::getTime(), getTimeMax(), getTimeMin(), handlePreviousInformation(), INFO, initialise(), MPIContainer::Instance(), DPMBase::interactionHandler, logger, ONE_FILE, DPMBase::particleHandler, DPMBase::readRestartFile(), DPMBase::restartFile, and DPMBase::wallHandler.
Referenced by commandLineCG(), and restartAndEvaluateRestartFiles().
finish()
void CGHandler::finish ()
Contains the code executed after the last time step.
 {
     //enforce that data gets written
     for (BaseCG* it : *this)
     {
         it->statFile.setLastSavedTimeStep(NEVER);
     }
     //evaluate all CG objects in the handler
     //evaluate();
     //finish all CG objects in the handler
     for (BaseCG* it : *this)
         it->finish();
 }
References BaseCG::finish(), NEVER, File::setLastSavedTimeStep(), and BaseCG::statFile.
Referenced by evaluateDataFiles(), evaluateRestartFiles(), and DPMBase::finishStatistics().
getInitialFileCounter()
unsigned CGHandler::getInitialFileCounter () const inline
{
         return initialFileCounter;
     }
References initialFileCounter.
getName()
std::string CGHandler::getName () const final virtual
Returns
a string containing the name.
Implements BaseHandler< BaseCG >.
 {
     return "CGHandler";
 }
getPreviousEvaluationTime()
Mdouble CGHandler::getPreviousEvaluationTime () inline
Returns the time of the last read/evaluated time step.
 { return previousEvaluationTime_; }
References previousEvaluationTime_.
Referenced by CGFields::DisplacementField::setFields().
getTimeMax()
Mdouble CGHandler::getTimeMax ()
 {
     Mdouble time = -constants::inf;
     for (BaseCG* it : *this)
     {
         time = std::max(time, it->getTimeMax());
     }
     return time;
 }
References BaseCG::getTimeMax(), constants::inf, and max.
Referenced by evaluateDataFiles(), and evaluateRestartFiles().
getTimeMin()
Mdouble CGHandler::getTimeMin ()
 {
     Mdouble time = constants::inf;
     for (BaseCG* it : *this)
     {
         time = std::min(time, it->getTimeMin());
     }
     return time;
 }
References BaseCG::getTimeMin(), constants::inf, and min.
Referenced by evaluateDataFiles(), and evaluateRestartFiles().
handlePreviousInformation()
void CGHandler::handlePreviousInformation ()
Sets data from the current time step as data from the previous time step.
This is needed, so that fields like the displacementField, which rely on the previous data, can be calculated.
It calls the functions setPreviousEvaluationTimeToCurrentTime() and setPreviousPositionToCurrentPosition().
 {
     setPreviousEvaluationTimeToCurrentTime();
     setPreviousPositionToCurrentPosition();
 }
References setPreviousEvaluationTimeToCurrentTime(), and setPreviousPositionToCurrentPosition().
Referenced by evaluate(), evaluateDataFiles(), and evaluateRestartFiles().
initialise()
void CGHandler::initialise ()
Contains the code executed before the first time step.
 {
     //initialise all CG objects in the handler
     for (BaseCG* it : *this)
         it->initialise();
 };
References BaseCG::initialise().
Referenced by evaluateDataFiles(), evaluateRestartFiles(), and DPMBase::initialiseStatistics().
operator=()
CGHandler & CGHandler::operator= (const CGHandler & rhs)
Assignment operator that copies the pointer to the DPMBase and all objects.
Parameters
[in] rhs The WallHandler on the right hand side of the assignment.
This is not a copy assignment operator! It only copies the pointer to the DPMBase and the BaseWall in objects_, it sets the other data members to 0 or nullptr.
 {
     if (this != &rhs)
     {
         clear();
         setDPMBase(rhs.getDPMBase());
         copyContentsFromOtherHandler(rhs);
     }
     return *this;
 #ifdef DEBUG_CONSTRUCTOR
     std::cerr << "CGHandler::operator =(const CGHandler&) finished" << std::endl;
 #endif
 }
References BaseHandler< BaseCG >::clear(), BaseHandler< BaseCG >::copyContentsFromOtherHandler(), BaseHandler< T >::getDPMBase(), and BaseHandler< BaseCG >::setDPMBase().
readAndAddObject()
void CGHandler::readAndAddObject (std::istream & is) final virtual
Reads objects into the CGHandler from an istream (currently not implemented).
Implements BaseHandler< BaseCG >.
 {
 }
restart()
void CGHandler::restart (std::string name)
loads restart file, before evaluateDataFiles is run
 {
     DPMBase* dpm = getDPMBase();
     // determines if the variable name contains the name of a restart file, or a problem name
     // (in which case the restart file is assumed to be name.restart)
     std::string::size_type endName = name.find(".restart");
     if (endName == std::string::npos)
     {
         dpm->setName(name);
     }
     else
     {
         dpm->setName(name.substr(0, endName));
         dpm->restartFile.setName(name);
     }
     // read restart file
     cgLogger(INFO, "Reading %", dpm->restartFile.getFullName());
     if (!dpm->readRestartFile(DPMBase::ReadOptions::ReadNoInteractions))
     {
         // if restart file could not be read
         // invent a species if necessary
         if (dpm->speciesHandler.getNumberOfObjects() == 0)
         {
             dpm->speciesHandler.copyAndAddObject(LinearViscoelasticSpecies());
         }
         // read data file
         std::ifstream data(dpm->dataFile.getName());
         if (data.is_open())
         {
             Mdouble N = 0, t = 0;
             Vec3D min, max;
             data >> N >> t >> min >> max;
             data.close();
             dpm->setDomain(min, max);
             logger(INFO, "Reading domain size from %: min %, max % ", dpm->dataFile.getName(), min, max);
         }
         else
         {
             logger(ERROR, "Data file '%' could not be opened", dpm->dataFile.getFullName());
         }
         //what to do if restart file could not be loaded
         cgLogger(WARN, "Restart file could not be read. No density is specified, thus density is assumed to be 1. Provide % file if you want to specify the density.", dpm->restartFile.getName());
     }
     else
     {
         cgLogger(INFO, "Successfully restarted from %, t=%, Np=%, Nc=%", dpm->restartFile.getFullName(), dpm->getTime(),
                  dpm->particleHandler.getSize(), dpm->interactionHandler.getNumberOfObjects());
         dpm->restartFile.decreaseCounter();
     }
 }
References cgLogger, BaseHandler< T >::copyAndAddObject(), data, DPMBase::dataFile, File::decreaseCounter(), ERROR, BaseHandler< BaseCG >::getDPMBase(), File::getFullName(), File::getName(), BaseHandler< T >::getNumberOfObjects(), BaseHandler< T >::getSize(), DPMBase::getTime(), INFO, DPMBase::interactionHandler, logger, max, min, N, plotDoE::name, DPMBase::particleHandler, DPMBase::ReadNoInteractions, DPMBase::readRestartFile(), DPMBase::restartFile, DPMBase::setDomain(), DPMBase::setName(), File::setName(), DPMBase::speciesHandler, plotPSD::t, and WARN.
Referenced by commandLineCG(), restartAndEvaluateDataFiles(), and restartAndEvaluateRestartFiles().
restartAndEvaluateDataFiles()
void CGHandler::restartAndEvaluateDataFiles (const std::string & name, bool evaluateFStatFiles = true)
 {
     restart(name);
     evaluateDataFiles(evaluateFStatFiles);
 }
References evaluateDataFiles(), plotDoE::name, and restart().
Referenced by main().
restartAndEvaluateRestartFiles()
void CGHandler::restartAndEvaluateRestartFiles (const std::string & name)
 {
     restart(name);
     evaluateRestartFiles();
 }
References evaluateRestartFiles(), plotDoE::name, and restart().
Referenced by main().
setInitialFileCounter()
void CGHandler::setInitialFileCounter (unsigned initialFileCounter) inline
{
         this->initialFileCounter = initialFileCounter;
     }
References initialFileCounter.
Referenced by commandLineCG().
setPreviousEvaluationTime()
void CGHandler::setPreviousEvaluationTime (Mdouble time) inline
Sets the time of the last read/evaluated time step to a specified time.
 { previousEvaluationTime_= time; }
References previousEvaluationTime_.
setPreviousEvaluationTimeToCurrentTime()
void CGHandler::setPreviousEvaluationTimeToCurrentTime ()
Sets the previous evaluation time to the current time.
This is needed, so that fields like the displacementField, which rely on the previous evaluation time, can be calculated.
 {
     previousEvaluationTime_ = getDPMBase()->getTime();
 }
References BaseHandler< BaseCG >::getDPMBase(), DPMBase::getTime(), and previousEvaluationTime_.
Referenced by handlePreviousInformation().
setPreviousPositionToCurrentPosition()
void CGHandler::setPreviousPositionToCurrentPosition ()
Sets the previous position for every particle to its current position.
This is needed, so that fields like the displacementField, which rely on the previous particle position, can be calculated.
 {
     for (BaseParticle* p : getDPMBase()->particleHandler)
     {
         p->setPreviousPosition(p->getPosition());
     }
 }
References BaseHandler< BaseCG >::getDPMBase(), and p.
Referenced by handlePreviousInformation().
write()
void CGHandler::write (std::ostream & os) const
Writes objects into the CGHandler to an ostream (currently not implemented).
 {
 }
Member Data Documentation
initialFileCounter
unsigned CGHandler::initialFileCounter = 0
Referenced by evaluateDataFiles(), getInitialFileCounter(), and setInitialFileCounter().
previousEvaluationTime_
Mdouble CGHandler::previousEvaluationTime_ = 0 private
Saves the time of the last read/evaluated data/restartFile.
This counter is used to calculate displacement fields.
Referenced by getPreviousEvaluationTime(), setPreviousEvaluationTime(), and setPreviousEvaluationTimeToCurrentTime().
The documentation for this class was generated from the following files:
CGHandler.h
CGHandler.cc