MercuryDPM: SurfactantProblem< ELEMENT, INTERFACE_ELEMENT > Class Template Reference
SurfactantProblem< ELEMENT, INTERFACE_ELEMENT > Class Template Reference
Public Member Functions
SurfactantProblem (const bool &pin=true)
Constructor. The boolean indicates whether the free surface.
~SurfactantProblem ()
Destructor. Empty.
void unpin_surface ()
Release the free surface so that it can move.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_newton_convergence_check ()
Remember to update the nodes if the surface is not pinned.
void actions_before_implicit_timestep ()
void actions_before_adapt ()
Strip off the interface elements before adapting the bulk mesh.
void actions_after_adapt ()
Rebuild the mesh of interface elements after adapting the bulk mesh.
void create_dependent_position_elements ()
Create the elements that make the position consistent on both sides.
void delete_dependent_position_elements ()
Delete the 1d interface elements.
void create_interface_elements ()
Create the 1d interface elements.
void delete_interface_elements ()
Delete the 1d interface elements.
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void unfix_pressure (const unsigned &e, const unsigned &pdof)
UnFix pressure in element e at pressure dof pdof and set to pvalue.
void deform_interface (const double &epsilon, const unsigned &n_periods)
void doc_solution (std::ofstream &trace)
Doc the solution.
void set_boundary_conditions (const double &time)
Set the boundary conditions.
double global_temporal_error_norm ()
void interface_min_max (double &min, double &max)
double l2_norm_of_height (const double &h0)
void compute_integrated_concentrations (double &surface, double &bulk, double &micelle)
void compute_areas (double &lower_area, double &upper_area)
SurfactantProblem (const bool &pin=true)
Constructor. The boolean indicates whether the free surface.
~SurfactantProblem ()
Destructor. Empty.
void unpin_surface ()
Release the free surface so that it can move.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_newton_convergence_check ()
Remember to update the nodes if the surface is not pinned.
void actions_before_implicit_timestep ()
void actions_before_adapt ()
Strip off the interface elements before adapting the bulk mesh.
void actions_after_adapt ()
Rebuild the mesh of interface elements after adapting the bulk mesh.
void create_slave_position_elements ()
Create the elements that slave the position.
void delete_slave_position_elements ()
Delete the 1d interface elements.
void create_interface_elements ()
Create the 1d interface elements.
void delete_interface_elements ()
Delete the 1d interface elements.
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void unfix_pressure (const unsigned &e, const unsigned &pdof)
UnFix pressure in element e at pressure dof pdof and set to pvalue.
void deform_interface (const double &epsilon, const unsigned &n_periods)
void doc_solution (std::ofstream &trace)
Doc the solution.
void set_boundary_conditions (const double &time)
Set the boundary conditions.
double global_temporal_error_norm ()
void interface_min_max (double &min, double &max)
double l2_norm_of_height (const double &h0)
void compute_integrated_concentrations (double &surface, double &bulk, double &micelle)
void compute_areas (double &lower_area, double &upper_area)
SurfactantProblem (const bool &pin=true)
Constructor. The boolean indicates whether the free surface.
~SurfactantProblem ()
Destructor. Empty.
void unpin_surface ()
Release the free surface so that it can move.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_newton_convergence_check ()
Remember to update the nodes if the surface is not pinned.
void actions_before_implicit_timestep ()
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void unfix_pressure (const unsigned &e, const unsigned &pdof)
UnFix pressure in element e at pressure dof pdof and set to pvalue.
void deform_interface (const double &epsilon, const unsigned &n_periods)
void doc_solution (std::ofstream &trace)
Doc the solution.
void set_boundary_conditions (const double &time)
Set the boundary conditions.
double global_temporal_error_norm ()
void interface_min_max (double &min, double &max)
double l2_norm_of_height (const double &h0)
void compute_integrated_concentrations (double &surface, double &bulk, double &micelle)
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Public Attributes
ElasticRefineableTwoLayerMesh< ELEMENT > * Bulk_mesh_pt
Mesh * Surface_mesh_pt
Storage to the mesh of Surface interface elements.
BackupMeshForProjection< QElement< 1, 3 > > * Backed_up_surface_mesh_pt
Storage for the back up the surface mesh.
Mesh * Point_mesh_pt
Storage to point elements if needed for non-periodic domains.
Mesh * Inlet_traction_mesh_pt
Storage for any traction elements applied to the inlet.
Mesh * Outlet_traction_mesh_pt
Storage for any traction elements applied to the outlet.
Mesh * Dependent_position_mesh_pt
ConstitutiveLaw * Constitutive_law_pt
Pointer to the constitutive law used to determine the mesh deformation.
Mesh * Slave_position_mesh_pt
TwoLayerSpineMesh< ELEMENT > * Bulk_mesh_pt
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Private Attributes
DocInfo Doc_info
DocInfo object.
bool Surface_pinned
Boolean to indicate whether the surface is pinned.
Node * Monitor_node_pt
Node used to monitor the interface height.
unsigned Periodic_index
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual void set_initial_condition ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class ELEMENT, class INTERFACE_ELEMENT>
class SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >
/////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////// 2D surfactant transport problem on rectangular domain, discretised with spine elements. The specific type of element is specified via the template parameter.
Constructor & Destructor Documentation
SurfactantProblem() [1/3]
template<class ELEMENT , class INTERFACE_ELEMENT > SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::SurfactantProblem (const bool & pin = true)
Constructor. The boolean indicates whether the free surface.
Constructor for convection problem.
                                    : Surface_pinned(pin), Periodic_index(50)
 {
  //Allocate an (adaptive) timestepper
   add_time_stepper_pt(new BDF<2>(true));
  //Don't worry if the estimated error is above the tolerance
   Keep_temporal_error_below_tolerance = false;
  // Set output directory
  Doc_info.set_directory("RESLT");
  // # of elements in x-direction (Coarse)
  unsigned n_x=20;//100;
  // # of elements in y-direction
  unsigned n_y1=4;//8;
  unsigned n_y2=4;//8;
  //Domain length in x direction
  double lx = 2.0*Global_Physical_Variables::L;
  // Domain length in y-direction
  double h1=Global_Physical_Variables::H0;
  double h2=1.0 - h1;
  // Build a standard rectangular quadmesh
  Bulk_mesh_pt =
    new ElasticRefineableTwoLayerMesh<ELEMENT>(n_x,n_y1,n_y2,lx,h1,h2,
                                   Control_Parameters::Periodic_BCs,
                                   time_stepper_pt());
  // Create and set the error estimator for spatial adaptivity
  Bulk_mesh_pt->spatial_error_estimator_pt() = new Z2ErrorEstimator;
  // Set the maximum refinement level for the mesh to 4
  Bulk_mesh_pt->max_refinement_level() = 4;
  // Define a constitutive law for the solid equations: generalised Hookean
  Constitutive_law_pt = new GeneralisedHookean(&Global_Physical_Variables::Nu);
  // Complete the build of all elements so they are fully functional
  // Determine number of bulk elements in lower/upper fluids
  const unsigned n_lower = Bulk_mesh_pt->nlower();
  const unsigned n_upper = Bulk_mesh_pt->nupper();
  // Loop over bulk elements in lower fluid
  for(unsigned e=0;e<n_lower;e++)
   {
    // Upcast from GeneralisedElement to the present element
    ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->
                                            lower_layer_element_pt(e));
    // Set the diffusivities number
    el_pt->diff_pt() = &Global_Physical_Variables::D;
    // Set the timescales
    el_pt->tau_pt() =&Global_Physical_Variables::Tau;
    // Set the Reynolds number
    el_pt->re_pt() = &Global_Physical_Variables::Re;
    // Set the Womersley number
    el_pt->re_st_pt() = &Global_Physical_Variables::Re;
    // Set the product of the Reynolds number and the inverse of the
    // Froude number
    el_pt->re_invfr_pt() = &Global_Physical_Variables::ReInvFr;
    // Set the km parameter
    el_pt->km_pt() = &Global_Physical_Variables::K_m;
    // Set the N parameter
    el_pt->n_pt() = &Global_Physical_Variables::N;
    // Set the direction of gravity
    el_pt->g_pt() = &Global_Physical_Variables::Direction_of_gravity;
    // Set the constitutive law
    el_pt->constitutive_law_pt() = this->Constitutive_law_pt;
   } // End of loop over bulk elements in lower fluid
  // Loop over bulk elements in upper fluid
  for(unsigned e=0;e<n_upper;e++)
   {
    // Upcast from GeneralisedElement to the present element
    ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->
                                            upper_layer_element_pt(e));
    // Set the diffusivities number
    el_pt->diff_pt() = &Global_Physical_Variables::D;
    // Set the timescales
    el_pt->tau_pt() =&Global_Physical_Variables::Tau;
    // Set the Reynolds number
    el_pt->re_pt() = &Global_Physical_Variables::Re;
    // Set the Womersley number
    el_pt->re_st_pt() = &Global_Physical_Variables::Re;
    // Set the product of the Reynolds number and the inverse of the
    // Froude number
    el_pt->re_invfr_pt() = &Global_Physical_Variables::ReInvFr;
    // Set the viscosity ratio
    el_pt->viscosity_ratio_pt() = &Global_Physical_Variables::M;
    // Set the density ratio
    el_pt->density_ratio_pt() = &Global_Physical_Variables::R;
    // Set the km parameter
    el_pt->km_pt() = &Global_Physical_Variables::K_m;
    // Set the N parameter
    el_pt->n_pt() = &Global_Physical_Variables::N;
    // Set the direction of gravity
    el_pt->g_pt() = &Global_Physical_Variables::Direction_of_gravity;
    // Set the constitutive law
    el_pt->constitutive_law_pt() = Constitutive_law_pt;
    //Need to pin the values of concentration and micelle up here
    unsigned n_el_node = el_pt->nnode();
    for(unsigned n=0;n<n_el_node;++n)
      {
        el_pt->node_pt(n)->set_value(2,0.0);
        el_pt->node_pt(n)->set_value(3,0.0);
        el_pt->node_pt(n)->pin(2);
        el_pt->node_pt(n)->pin(3);
      }
   } // End of loop over bulk elements in upper fluid
  //Create the surface mesh that will contain the interface elements
  //First create storage, but with no elements or nodes
  Surface_mesh_pt = new Mesh;
  //Make point elements at the end to compensate for
  //the unbalanced line tension terms
  //if we DON'T have periodic boundaryc conditions
  if(!Control_Parameters::Periodic_BCs)
    {
      Point_mesh_pt = new Mesh;
    }
  //Must be done *after* the physical parameters have been set
  //because we are using the viscosity ratio pointer to determine
  //upper or lower elements
  create_interface_elements();
  //Setup the monitor node
   {
     unsigned n_surface_element = Surface_mesh_pt->nelement();
     Monitor_node_pt = Surface_mesh_pt->finite_element_pt(n_surface_element/2)->node_pt(1);
   }
   if(Control_Parameters::Periodic_BCs)
    {
      Dependent_position_mesh_pt = new Mesh;
      //Create the dependent elements that ensure that the positions match
      create_dependent_position_elements();
    }
  // Add the two sub-meshes to the problem
  add_sub_mesh(Bulk_mesh_pt);
  add_sub_mesh(Surface_mesh_pt);
  if(!Control_Parameters::Periodic_BCs)
    {
      add_sub_mesh(Point_mesh_pt);
      add_sub_mesh(Inlet_traction_mesh_pt);
      add_sub_mesh(Outlet_traction_mesh_pt);
    }
  else
    {
      add_sub_mesh(Dependent_position_mesh_pt);
      }
  // Combine all sub-meshes into a single mesh
  build_global_mesh();
  //Pin the positions of all nodes and the Lagrange multipliers if the surface is pinned
  if(Surface_pinned)
   {
    unsigned n_node = Bulk_mesh_pt->nnode();
    for(unsigned n=0;n<n_node;n++)
      {
        SolidNode* nod_pt = Bulk_mesh_pt->node_pt(n);
        nod_pt->pin_position(0);
        nod_pt->pin_position(1);
        //Don't forget to pin the Lagrange multipliers as well
        if(nod_pt->is_on_boundary(4))
      {
        //Lagrange multiplier is always value 5
        unsigned lagrange_multiplier_index = 5;
        nod_pt->pin(lagrange_multiplier_index);
      }
      }
   }
  // Set the boundary conditions for this problem: All nodes are
  // free by default -- only need to pin the ones that have Dirichlet
  // conditions here
  //Loop over the boundaries
  unsigned num_bound = Bulk_mesh_pt->nboundary();
  for(unsigned ibound=0;ibound<num_bound;ibound++)
   {
    //If we are on the side-walls, the concentrations
    //satisfy natural boundary conditions, so we only pin the
    //v-velocity for now if not periodic
     if(!Control_Parameters::Periodic_BCs)
       {
     if((ibound==1) || (ibound==3))
       {
         //Loop over the number of nodes on the boundary
         unsigned num_nod= Bulk_mesh_pt->nboundary_node(ibound);
         for(unsigned inod=0;inod<num_nod;inod++)
           {
                //Cast to a solid node, so that we can impose boundary conditions
                SolidNode* nod_pt = static_cast<SolidNode*>(
                 Bulk_mesh_pt->boundary_node_pt(ibound,inod));
         nod_pt->pin(1);
                 //Also pin the horizontal displacement of the nodes
                 nod_pt->pin_position(0);
         /*if((ibound==4) || (ibound==5))
           {
           Bulk_mesh_pt->boundary_node_pt(ibound,inod)->pin(0);
           }*/
           }
       }
       }
    //If we on the top or bottom wall, velocity is pinned
    //as is the nodal position
    if((ibound==0) || (ibound==2))
     {
       //Loop over the number of nodes on the boundary
       unsigned num_nod= Bulk_mesh_pt->nboundary_node(ibound);
       for(unsigned inod=0;inod<num_nod;inod++)
     {
          SolidNode* nod_pt = static_cast<SolidNode*>(Bulk_mesh_pt->boundary_node_pt(ibound,inod));
       nod_pt->pin(0);
       nod_pt->pin(1);
           nod_pt->pin_position(0);
           nod_pt->pin_position(1);
     }
     }
   }
  //Pin the zero-th pressure dof in element 0 and set its value to
  //zero:
  fix_pressure(0,0,0.0);
   // Loop over the interface elements to set up element-specific
  // things that cannot be handled by the (argument-free!) ELEMENT
  // constructor.
  unsigned n_interface  = Surface_mesh_pt->nelement();
  for(unsigned i=0;i<n_interface;i++)
   {
    // Upcast from GeneralsedElement to the present element
    INTERFACE_ELEMENT *el_pt = dynamic_cast<INTERFACE_ELEMENT*>(
     Surface_mesh_pt->element_pt(i));
    //Need to unpin the values of concentration and micelle on the interface
    unsigned n_el_node = el_pt->nnode();
    for(unsigned n=0;n<n_el_node;++n)
      {
        el_pt->node_pt(n)->unpin(2); //unpin
        el_pt->node_pt(n)->unpin(3); //unpin
        el_pt->node_pt(n)->pin(4); //Pin Lagrange Multiplier initially
      }
   }
  //Pin all bulk concentrations ... to save
  //time and to avoid having to conserve global mass
  unsigned n_node = Bulk_mesh_pt->nnode();
  for(unsigned n=0;n<n_node;++n)
    {
     SolidNode* nod_pt = static_cast<SolidNode*>(Bulk_mesh_pt->node_pt(n));
     //Pin x position
      nod_pt->pin_position(0);
      nod_pt->pin_position(1);
      nod_pt->pin(2);
      nod_pt->pin(3);
      double y = nod_pt->x(1);
      nod_pt->set_value(0,y);
      nod_pt->set_value(1,0.0);
    }
  //We initialise need to pin the lagrange multipliers
  //associated with periodic boundary conditions on the side boundary
  {
    unsigned b=3;
    unsigned n_boundary_node = this->Bulk_mesh_pt->nboundary_node(b);
    for(unsigned n=0;n<n_boundary_node;++n)
      {
        Node* nod_pt = this->Bulk_mesh_pt->boundary_node_pt(b,n);
        if(!(nod_pt->is_on_boundary(0)) &&
       !(nod_pt->is_on_boundary(2)) &&
       !(nod_pt->is_on_boundary(4)))
      {
        //Pin all
        nod_pt->pin(dynamic_cast<BoundaryNodeBase*>(nod_pt)
                ->index_of_first_value_assigned_by_face_element(
                                        Periodic_index));
      }
      }
  }
  //Pin one surface concentration at the surface, if only
  //solving for insoluble surfactant
  //Surface_mesh_pt->finite_element_pt(0)->node_pt(1)->pin(4);
  // Setup equation numbering scheme
  cout <<"Number of equations: " << assign_eqn_numbers() << endl;
 } // end of constructor
References oomph::Problem::add_sub_mesh(), oomph::Problem::add_time_stepper_pt(), oomph::Problem::assign_eqn_numbers(), b, oomph::Problem::build_global_mesh(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Bulk_mesh_pt, SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Constitutive_law_pt, SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::create_dependent_position_elements(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::create_interface_elements(), Global_Physical_Variables::D, SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Dependent_position_mesh_pt, Global_Physical_Variables::Direction_of_gravity, SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Doc_info, e(), oomph::Mesh::element_pt(), oomph::Mesh::finite_element_pt(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::fix_pressure(), oomph::Global_Physical_Variables::H0, i, oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Inlet_traction_mesh_pt, oomph::Node::is_on_boundary(), oomph::Global_Physical_Variables::K_m, oomph::Problem::Keep_temporal_error_below_tolerance, Global_Physical_Variables::L, Mesh_Parameters::lx, oomph::Global_Physical_Variables::M, SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Monitor_node_pt, n, N, oomph::Mesh::nelement(), oomph::FiniteElement::node_pt(), Global_Physical_Variables::Nu, SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Outlet_traction_mesh_pt, oomph::Control_Parameters::Periodic_BCs, SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Periodic_index, oomph::Data::pin(), oomph::SolidNode::pin_position(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Point_mesh_pt, R, Global_Physical_Variables::Re, Global_Physical_Variables::ReInvFr, oomph::DocInfo::set_directory(), oomph::Data::set_value(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Surface_mesh_pt, SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Surface_pinned, Global_Physical_Variables::Tau, oomph::Problem::time_stepper_pt(), oomph::Node::x(), and y.
~SurfactantProblem() [1/3]
template<class ELEMENT , class INTERFACE_ELEMENT > SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::~SurfactantProblem () inline
Destructor. Empty.
 {}
SurfactantProblem() [2/3]
template<class ELEMENT , class INTERFACE_ELEMENT > SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::SurfactantProblem (const bool & pin = true)
Constructor. The boolean indicates whether the free surface.
~SurfactantProblem() [2/3]
template<class ELEMENT , class INTERFACE_ELEMENT > SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::~SurfactantProblem () inline
Destructor. Empty.
 {}
SurfactantProblem() [3/3]
template<class ELEMENT , class INTERFACE_ELEMENT > SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::SurfactantProblem (const bool & pin = true)
Constructor. The boolean indicates whether the free surface.
~SurfactantProblem() [3/3]
template<class ELEMENT , class INTERFACE_ELEMENT > SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::~SurfactantProblem () inline
Destructor. Empty.
 {}
Member Function Documentation
actions_after_adapt() [1/2]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::actions_after_adapt () inline virtual
Rebuild the mesh of interface elements after adapting the bulk mesh.
Reimplemented from oomph::Problem.
   {
     //Need to update the pointers to upper and lower elements
     this->Bulk_mesh_pt->setup_upper_and_lower_elements();
     // Create the interface elements
     this->create_interface_elements();
     //Now we need to make sure that we set up the correct insoluble surfactant
     //concentration
     //We do this by interpolating from the previous mesh
     // Now project from backup of original contact mesh to new one
     Backed_up_surface_mesh_pt->project_onto_new_mesh(
                              Surface_mesh_pt);
     //Now delete the backed up mesh
     delete Backed_up_surface_mesh_pt;
     Backed_up_surface_mesh_pt=0;
     if(Control_Parameters::Periodic_BCs)
       {
     //Create the dependent position elements
     this->create_dependent_position_elements();
       }
     // Rebuild the Problem's global mesh from its various sub-meshes
     this->rebuild_global_mesh();
     // Pin horizontal displacement of all nodes
     const unsigned n_node = Bulk_mesh_pt->nnode();
     for(unsigned n=0;n<n_node;n++) {Bulk_mesh_pt->node_pt(n)->pin_position(0); }
     // Determine number of bulk elements in lower/upper fluids
     const unsigned n_lower = Bulk_mesh_pt->nlower();
     const unsigned n_upper = Bulk_mesh_pt->nupper();
     // Loop over bulk elements in upper fluid
     for(unsigned e=0;e<n_upper;e++)
       {
      // Upcast from GeneralisedElement to the present element
      ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->
                                              upper_layer_element_pt(e));
      //Need to pin the values of concentration and micelle up here
      unsigned n_el_node = el_pt->nnode();
      for(unsigned n=0;n<n_el_node;++n)
        {
      Node* const nod_pt = el_pt->node_pt(n);
      if(nod_pt->is_on_boundary(4) == false)
        {
          //Set all the history values to zero as well
          unsigned nprev_values = nod_pt->time_stepper_pt()->nprev_values();
          for(unsigned t=0;t<=nprev_values;++t)
            {
          nod_pt->set_value(t,2,0.0);
          nod_pt->set_value(t,3,0.0);
            }
          nod_pt->pin(2);
          nod_pt->pin(3);
        }
        }
       } // End of loop over bulk elements in upper fluid
     // Loop over bulk elements in lower fluid and unpin
     for(unsigned e=0;e<n_lower;e++)
       {
     // Upcast from GeneralisedElement to the present element
     ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->
                         lower_layer_element_pt(e));
     //No need to pin the values of concentration and micelle down here
     //But don't unpin if they are hanging
     unsigned n_el_node = el_pt->nnode();
     for(unsigned n=0;n<n_el_node;++n)
       {
         Node* const nod_pt = el_pt->node_pt(n);
         if(!(nod_pt->is_constrained(2))) {nod_pt->unpin(2);}
         if(!(nod_pt->is_constrained(3))) {nod_pt->unpin(3);}
       }
       }
    // Set the boundary conditions for this problem: All nodes are
    // free by default -- only need to pin the ones that have Dirichlet
    // conditions here
    //Loop over the boundaries
    unsigned num_bound = Bulk_mesh_pt->nboundary();
    for(unsigned ibound=0;ibound<num_bound;ibound++)
     {
      //If we are on the side-walls, the concentrations
      //satisfy natural boundary conditions, so we only pin the
      //v-velocity for now if not periodic
      if(!Control_Parameters::Periodic_BCs)
       {
        if((ibound==1) || (ibound==3))
         {
          //Loop over the number of nodes on the boundary
          unsigned num_nod= Bulk_mesh_pt->nboundary_node(ibound);
          for(unsigned inod=0;inod<num_nod;inod++)
           {
            //Cast to a solid node, so that we can impose boundary conditions
            SolidNode* nod_pt = static_cast<SolidNode*>(
             Bulk_mesh_pt->boundary_node_pt(ibound,inod));
            nod_pt->pin(1);
            //Also pin the horizontal displacement of the nodes
            nod_pt->pin_position(0);
           }
         }
       }
      //If we on the top or bottom wall, velocity is pinned
      //as is the nodal position
      if((ibound==0) || (ibound==2))
       {
        //Loop over the number of nodes on the boundary
        unsigned num_nod= Bulk_mesh_pt->nboundary_node(ibound);
        for(unsigned inod=0;inod<num_nod;inod++)
     {
          SolidNode* nod_pt = static_cast<SolidNode*>(Bulk_mesh_pt->boundary_node_pt(ibound,inod));
          nod_pt->pin(0);
          nod_pt->pin(1);
          nod_pt->pin_position(0);
          nod_pt->pin_position(1);
     }
       }
     }
    // Now set the pressure in the first element at 'node' 0 to 0.0
    fix_pressure(0,0,0.0);
    // Reset the boundary conditions
    set_boundary_conditions(this->time_pt()->time());
   }
References e(), oomph::Data::is_constrained(), oomph::Node::is_on_boundary(), n, oomph::TimeStepper::nprev_values(), oomph::Control_Parameters::Periodic_BCs, oomph::Data::pin(), oomph::SolidNode::pin_position(), oomph::Data::set_value(), plotPSD::t, oomph::Data::time_stepper_pt(), and oomph::Data::unpin().
actions_after_adapt() [2/2]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::actions_after_adapt () inline virtual
Rebuild the mesh of interface elements after adapting the bulk mesh.
Reimplemented from oomph::Problem.
   {
     //Need to update the pointers to upper and lower elements
     this->Bulk_mesh_pt->setup_upper_and_lower_elements();
     // Create the interface elements
     this->create_interface_elements();
     //Now we need to make sure that we set up the correct insoluble surfactant
     //concentration
     //We do this by interpolating from the previous mesh
     // Now project from backup of original contact mesh to new one
     Backed_up_surface_mesh_pt->project_onto_new_mesh(
                              Surface_mesh_pt);
     //Now delete the backed up mesh
     delete Backed_up_surface_mesh_pt;
     Backed_up_surface_mesh_pt=0;
     if(Control_Parameters::Periodic_BCs)
       {
     //Create the slave position elements
     this->create_slave_position_elements();
       }
     // Rebuild the Problem's global mesh from its various sub-meshes
     this->rebuild_global_mesh();
     // Pin horizontal displacement of all nodes
     const unsigned n_node = Bulk_mesh_pt->nnode();
     for(unsigned n=0;n<n_node;n++) {Bulk_mesh_pt->node_pt(n)->pin_position(0); }
     // Determine number of bulk elements in lower/upper fluids
     const unsigned n_lower = Bulk_mesh_pt->nlower();
     const unsigned n_upper = Bulk_mesh_pt->nupper();
     // Loop over bulk elements in upper fluid
     for(unsigned e=0;e<n_upper;e++)
       {
      // Upcast from GeneralisedElement to the present element
      ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->
                                              upper_layer_element_pt(e));
      //Need to pin the values of concentration and micelle up here
      unsigned n_el_node = el_pt->nnode();
      for(unsigned n=0;n<n_el_node;++n)
        {
      Node* const nod_pt = el_pt->node_pt(n);
      if(nod_pt->is_on_boundary(4) == false)
        {
          //Set all the history values to zero as well
          unsigned nprev_values = nod_pt->time_stepper_pt()->nprev_values();
          for(unsigned t=0;t<=nprev_values;++t)
            {
          nod_pt->set_value(t,2,0.0);
          nod_pt->set_value(t,3,0.0);
            }
          nod_pt->pin(2);
          nod_pt->pin(3);
        }
        }
       } // End of loop over bulk elements in upper fluid
     // Loop over bulk elements in lower fluid and unpin
     for(unsigned e=0;e<n_lower;e++)
       {
     // Upcast from GeneralisedElement to the present element
     ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->
                         lower_layer_element_pt(e));
     //No need to pin the values of concentration and micelle down here
     //But don't unpin if they are hanging
     unsigned n_el_node = el_pt->nnode();
     for(unsigned n=0;n<n_el_node;++n)
       {
         Node* const nod_pt = el_pt->node_pt(n);
         if(!(nod_pt->is_constrained(2))) {nod_pt->unpin(2);}
         if(!(nod_pt->is_constrained(3))) {nod_pt->pin(3);}
           //{nod_pt->unpin(3);}
       }
       }
    // Set the boundary conditions for this problem: All nodes are
    // free by default -- only need to pin the ones that have Dirichlet
    // conditions here
    //Loop over the boundaries
    unsigned num_bound = Bulk_mesh_pt->nboundary();
    for(unsigned ibound=0;ibound<num_bound;ibound++)
     {
      //If we are on the side-walls, the concentrations
      //satisfy natural boundary conditions, so we only pin the
      //v-velocity for now if not periodic
      if(!Control_Parameters::Periodic_BCs)
       {
        if((ibound==1) || (ibound==3))
         {
          //Loop over the number of nodes on the boundary
          unsigned num_nod= Bulk_mesh_pt->nboundary_node(ibound);
          for(unsigned inod=0;inod<num_nod;inod++)
           {
            //Cast to a solid node, so that we can impose boundary conditions
            SolidNode* nod_pt = static_cast<SolidNode*>(
             Bulk_mesh_pt->boundary_node_pt(ibound,inod));
            nod_pt->pin(1);
            //Also pin the horizontal displacement of the nodes
            nod_pt->pin_position(0);
           }
         }
       }
      //If we on the top or bottom wall, velocity is pinned
      //as is the nodal position
      if((ibound==0) || (ibound==2))
       {
        //Loop over the number of nodes on the boundary
        unsigned num_nod= Bulk_mesh_pt->nboundary_node(ibound);
        for(unsigned inod=0;inod<num_nod;inod++)
     {
          SolidNode* nod_pt = static_cast<SolidNode*>(Bulk_mesh_pt->boundary_node_pt(ibound,inod));
          nod_pt->pin(0);
          nod_pt->pin(1);
          nod_pt->pin_position(0);
          nod_pt->pin_position(1);
     }
       }
     }
    // Now set the pressure in the first element at 'node' 0 to 0.0
    fix_pressure(0,0,0.0);
    // Reset the boundary conditions
    set_boundary_conditions(this->time_pt()->time());
   }
References e(), oomph::Data::is_constrained(), oomph::Node::is_on_boundary(), n, oomph::TimeStepper::nprev_values(), oomph::Control_Parameters::Periodic_BCs, oomph::Data::pin(), oomph::SolidNode::pin_position(), oomph::Data::set_value(), plotPSD::t, oomph::Data::time_stepper_pt(), and oomph::Data::unpin().
actions_after_newton_solve() [1/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [2/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [3/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_adapt() [1/2]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::actions_before_adapt () inline virtual
Strip off the interface elements before adapting the bulk mesh.
Reimplemented from oomph::Problem.
    {
      //Unfix the pressure to avoid double fixing
      this->unfix_pressure(0,0);
      if(Control_Parameters::Periodic_BCs)
        {
      //Delete  the dependent elements and wipe the mesh
      this->delete_dependent_position_elements();
        }
      //Backup the surface mesh
      Backed_up_surface_mesh_pt =
        new BackupMeshForProjection<QElement<1,3> >(Surface_mesh_pt,4,0);
      // Delete the interface elements and wipe the surface mesh
      delete_interface_elements();
      // Rebuild the Problem's global mesh from its various sub-meshes
      rebuild_global_mesh();
    }
References oomph::Control_Parameters::Periodic_BCs.
actions_before_adapt() [2/2]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::actions_before_adapt () inline virtual
Strip off the interface elements before adapting the bulk mesh.
Reimplemented from oomph::Problem.
    {
      //Unfix the pressure to avoid double fixing
      this->unfix_pressure(0,0);
      if(Control_Parameters::Periodic_BCs)
        {
      //Delete  the slave elements and wipe the mesh
      this->delete_slave_position_elements();
        }
      //Backup the surface mesh
      Backed_up_surface_mesh_pt =
        new BackupMeshForProjection<QElement<1,3> >(Surface_mesh_pt,4,0);
      // Delete the interface elements and wipe the surface mesh
      delete_interface_elements();
      // Rebuild the Problem's global mesh from its various sub-meshes
      rebuild_global_mesh();
    }
References oomph::Control_Parameters::Periodic_BCs.
actions_before_implicit_timestep() [1/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::actions_before_implicit_timestep () inline virtual
Actions before the timestep (update the the time-dependent boundary conditions)
Reimplemented from oomph::Problem.
   {
     set_boundary_conditions(time_pt()->time());
     Bulk_mesh_pt->set_lagrangian_nodal_coordinates();
    //Also set lagrange multipliers to zero
     unsigned n_boundary_node = Bulk_mesh_pt->nboundary_node(4);
     for(unsigned n=0;n<n_boundary_node;++n)
       {
     Bulk_mesh_pt->boundary_node_pt(4,n)->set_value(5,0.0);
       }
     //Lagrange multipliers associated with the periodicity constraint
     n_boundary_node = this->Bulk_mesh_pt->nboundary_node(3);
     for(unsigned n=0;n<n_boundary_node;++n)
       {
     Node* nod_pt = Bulk_mesh_pt->boundary_node_pt(3,n);
     if(!(nod_pt->is_on_boundary(0)) &&
        !(nod_pt->is_on_boundary(2)) &&
        !(nod_pt->is_on_boundary(4)))
       {
         unsigned lm_index = dynamic_cast<BoundaryNodeBase*>(nod_pt)
           ->index_of_first_value_assigned_by_face_element(
                                   Periodic_index);
         nod_pt->set_value(lm_index,0.0);
       }
       }
   }
References oomph::Node::is_on_boundary(), n, and oomph::Data::set_value().
actions_before_implicit_timestep() [2/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::actions_before_implicit_timestep () inline virtual
Actions before the timestep (update the the time-dependent boundary conditions)
Reimplemented from oomph::Problem.
   {
     set_boundary_conditions(time_pt()->time());
     Bulk_mesh_pt->set_lagrangian_nodal_coordinates();
    //Also set lagrange multipliers to zero
     unsigned n_boundary_node = Bulk_mesh_pt->nboundary_node(4);
     for(unsigned n=0;n<n_boundary_node;++n)
       {
     Bulk_mesh_pt->boundary_node_pt(4,n)->set_value(5,0.0);
       }
     //Lagrange multipliers associated with the periodicity constraint
     n_boundary_node = this->Bulk_mesh_pt->nboundary_node(3);
     for(unsigned n=0;n<n_boundary_node;++n)
       {
     Node* nod_pt = Bulk_mesh_pt->boundary_node_pt(3,n);
     if(!(nod_pt->is_on_boundary(0)) &&
        !(nod_pt->is_on_boundary(2)) &&
        !(nod_pt->is_on_boundary(4)))
       {
         unsigned lm_index = dynamic_cast<BoundaryNodeBase*>(nod_pt)
           ->index_of_first_value_assigned_by_face_element(
                                   Periodic_index);
         nod_pt->set_value(lm_index,0.0);
       }
       }
   }
References oomph::Node::is_on_boundary(), n, and oomph::Data::set_value().
actions_before_implicit_timestep() [3/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::actions_before_implicit_timestep () inline virtual
Actions before the timestep (update the the time-dependent boundary conditions)
Reimplemented from oomph::Problem.
   {set_boundary_conditions(time_pt()->time());}
actions_before_newton_convergence_check() [1/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::actions_before_newton_convergence_check () inline virtual
Remember to update the nodes if the surface is not pinned.
Reimplemented from oomph::Problem.
 {}
actions_before_newton_convergence_check() [2/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::actions_before_newton_convergence_check () inline virtual
Remember to update the nodes if the surface is not pinned.
Reimplemented from oomph::Problem.
 {}
actions_before_newton_convergence_check() [3/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::actions_before_newton_convergence_check () inline virtual
Remember to update the nodes if the surface is not pinned.
Reimplemented from oomph::Problem.
   {if(!Surface_pinned) {Bulk_mesh_pt->node_update();}}
actions_before_newton_solve() [1/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [2/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [3/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
compute_areas() [1/2]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::compute_areas (double & lower_area, double & upper_area) inline
   {
     // Loop over bulk elements in lower fluid and add each elemental
     // contribution
     const unsigned n_lower = Bulk_mesh_pt->nlower();
     for(unsigned e=0;e<n_lower;e++)
       {
     lower_area += Bulk_mesh_pt->lower_layer_element_pt(e)->size();
       }
     const unsigned n_upper = Bulk_mesh_pt->nupper();
     for(unsigned e=0;e<n_upper;e++)
       {
     upper_area += Bulk_mesh_pt->upper_layer_element_pt(e)->size();
       }
   }
References e(), ElasticRefineableTwoLayerMesh< ELEMENT >::lower_layer_element_pt(), ElasticRefineableTwoLayerMesh< ELEMENT >::nlower(), ElasticRefineableTwoLayerMesh< ELEMENT >::nupper(), oomph::FiniteElement::size(), and ElasticRefineableTwoLayerMesh< ELEMENT >::upper_layer_element_pt().
compute_areas() [2/2]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::compute_areas (double & lower_area, double & upper_area) inline
   {
     // Loop over bulk elements in lower fluid and add each elemental
     // contribution
     const unsigned n_lower = Bulk_mesh_pt->nlower();
     for(unsigned e=0;e<n_lower;e++)
       {
     lower_area += Bulk_mesh_pt->lower_layer_element_pt(e)->size();
       }
     const unsigned n_upper = Bulk_mesh_pt->nupper();
     for(unsigned e=0;e<n_upper;e++)
       {
     upper_area += Bulk_mesh_pt->upper_layer_element_pt(e)->size();
       }
   }
References e(), ElasticRefineableTwoLayerMesh< ELEMENT >::lower_layer_element_pt(), ElasticRefineableTwoLayerMesh< ELEMENT >::nlower(), ElasticRefineableTwoLayerMesh< ELEMENT >::nupper(), oomph::FiniteElement::size(), and ElasticRefineableTwoLayerMesh< ELEMENT >::upper_layer_element_pt().
compute_integrated_concentrations() [1/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::compute_integrated_concentrations (double & surface, double & bulk, double & micelle) inline
Return the total concentrations of the surfactant integrated over the bulk or surface accordingly
   {
    //Initialise to zero
    surface = 0.0;
    //Loop over the interface and add each elemental contribution
    const unsigned n_interface  = Surface_mesh_pt->nelement();
    for(unsigned i=0;i<n_interface;i++)
     {
      // Upcast from GeneralsedElement to the present element
      INTERFACE_ELEMENT *el_pt =
       dynamic_cast<INTERFACE_ELEMENT*>(
        Surface_mesh_pt->element_pt(i));
      surface += el_pt->integrated_C();
     }
    //Initialise to zero
    bulk = 0.0; micelle = 0.0;
    // Loop over bulk elements in lower fluid and add each elemental
    // contribution
    const unsigned n_lower = Bulk_mesh_pt->nlower();
    for(unsigned e=0;e<n_lower;e++)
     {
      // Upcast from GeneralisedElement to the present element
      ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->
                                              lower_layer_element_pt(e));
      double int_M=0.0, int_C=0.0;
      el_pt->integrated_C_and_M(int_C,int_M);
      bulk += int_C;
      micelle += int_M;
     }
   }
References e(), oomph::Mesh::element_pt(), i, oomph::Mesh::nelement(), and ElasticRefineableTwoLayerMesh< ELEMENT >::nlower().
compute_integrated_concentrations() [2/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::compute_integrated_concentrations (double & surface, double & bulk, double & micelle) inline
Return the total concentrations of the surfactant integrated over the bulk or surface accordingly
   {
    //Initialise to zero
    surface = 0.0;
    //Loop over the interface and add each elemental contribution
    const unsigned n_interface  = Surface_mesh_pt->nelement();
    for(unsigned i=0;i<n_interface;i++)
     {
      // Upcast from GeneralsedElement to the present element
      INTERFACE_ELEMENT *el_pt =
       dynamic_cast<INTERFACE_ELEMENT*>(
        Surface_mesh_pt->element_pt(i));
      surface += el_pt->integrated_C();
     }
    //Initialise to zero
    bulk = 0.0; micelle = 0.0;
    // Loop over bulk elements in lower fluid and add each elemental
    // contribution
    const unsigned n_lower = Bulk_mesh_pt->nlower();
    for(unsigned e=0;e<n_lower;e++)
     {
      // Upcast from GeneralisedElement to the present element
      ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->
                                              lower_layer_element_pt(e));
      double int_M=0.0, int_C=0.0;
      el_pt->integrated_C_and_M(int_C,int_M);
      bulk += int_C;
      micelle += int_M;
     }
   }
References e(), oomph::Mesh::element_pt(), i, oomph::Mesh::nelement(), and ElasticRefineableTwoLayerMesh< ELEMENT >::nlower().
compute_integrated_concentrations() [3/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::compute_integrated_concentrations (double & surface, double & bulk, double & micelle) inline
Return the total concentrations of the surfactant integrated over the bulk or surface accordingly
   {
    //Initialise to zero
    surface = 0.0;
    //Loop over the interface and add each elemental contribution
    const unsigned n_interface  = Surface_mesh_pt->nelement();
    for(unsigned i=0;i<n_interface;i++)
     {
      // Upcast from GeneralsedElement to the present element
      INTERFACE_ELEMENT *el_pt =
       dynamic_cast<INTERFACE_ELEMENT*>(
        Surface_mesh_pt->element_pt(i));
      surface += el_pt->integrated_C();
     }
    //Initialise to zero
    bulk = 0.0; micelle = 0.0;
    // Loop over bulk elements in lower fluid and add each elemental
    // contribution
    const unsigned n_lower = Bulk_mesh_pt->nlower();
    for(unsigned e=0;e<n_lower;e++)
     {
      // Upcast from GeneralisedElement to the present element
      ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->
                                              lower_layer_element_pt(e));
      double int_M=0.0, int_C=0.0;
      el_pt->integrated_C_and_M(int_C,int_M);
      bulk += int_C;
      micelle += int_M;
     }
   }
References e(), oomph::Mesh::element_pt(), i, oomph::Mesh::nelement(), and oomph::TwoLayerSpineMesh< ELEMENT >::nlower().
create_dependent_position_elements()
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::create_dependent_position_elements () inline
Create the elements that make the position consistent on both sides.
   {
     //We know that boundary 1 is made periodic from boundary 3
     //We also know that the nodes have already been made
     //periodic so we simply need
     //to create the dependent elements to match the vertical positions
     const unsigned n_boundary_node = this->Bulk_mesh_pt->nboundary_node(1);
     for(unsigned n=0;n<n_boundary_node;++n)
       {
     //Cache the boundary node
     Node* nod_pt = this->Bulk_mesh_pt->boundary_node_pt(1,n);
     //Cache the master node
     Node* master_node_pt = nod_pt->copied_node_pt();
     //If there is no master node, then the node has no
     //counterpart on the other side and is therefore
     //not a degree of freedom and does not need to be
     //made dependent
     if(master_node_pt!=0)
       {
         //Only create dependent for nodes that are not on the interface
         if(!(master_node_pt->is_on_boundary(0)) &&
            !(master_node_pt->is_on_boundary(2)) &&
            !(master_node_pt->is_on_boundary(4)))
           {
         //Create the dependent node with a position ID
         this->Dependent_position_mesh_pt->
           add_element_pt(new DependentPositionPointElement(
                                   master_node_pt,
                                   nod_pt,Periodic_index));
           }
       }
       }
   }
References oomph::Node::copied_node_pt(), oomph::Node::is_on_boundary(), and n.
Referenced by SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::SurfactantProblem().
create_interface_elements() [1/2]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::create_interface_elements () inline
Create the 1d interface elements.
   {
    //In the adaptive formulation the only way that we will know which elements
    //are on the lower or upper side is to use the density ratio
    //Store number of 1d nodes
    const unsigned n_node_1d = Bulk_mesh_pt->finite_element_pt(0)->nnode_1d();
    // Determine number of bulk elements adjacent to interface (boundary 4)
    const unsigned n_element = this->Bulk_mesh_pt->nboundary_element(4);
    // Loop over those elements adjacent to the interface
    for(unsigned e=0;e<n_element;e++)
     {
      // Get pointer to the bulk element that is adjacent to the interface
      ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
       this->Bulk_mesh_pt->boundary_element_pt(4,e));
      // We only want to attach interface elements to the bulk elements
      // which are BELOW the interface, and so we filter out those above by
      // referring to the viscosity_ratio_pt
      if(bulk_elem_pt->viscosity_ratio_pt() !=&Global_Physical_Variables::M)
     {
      // Find index of the face of element e that corresponds to the interface
      const int face_index = this->Bulk_mesh_pt->face_index_at_boundary(4,e);
      // Create the interface element
      INTERFACE_ELEMENT* interface_element_element_pt =
       new INTERFACE_ELEMENT(bulk_elem_pt,face_index);
      // Add the interface element to the surface mesh
      this->Surface_mesh_pt->add_element_pt(interface_element_element_pt);
     }
 //Otherwise it's on the upper side
      else
       {
     //Hijack all nodes of all elements
        unsigned n_max_node = n_node_1d;
        for(unsigned n=0;n<n_max_node;++n)
         {
          (void)bulk_elem_pt->hijack_nodal_value(n,2,false);
          (void)bulk_elem_pt->hijack_nodal_value(n,3,false);
         }
       }
     }
  // --------------------------------------------------------
  // Complete the setup to make the elements fully functional
  // --------------------------------------------------------
  // Determine number of 1D interface elements in mesh
  const unsigned n_interface_element = this->Surface_mesh_pt->nelement();
  // Loop over the interface elements
  for(unsigned e=0;e<n_interface_element;e++)
   {
    // Upcast from GeneralisedElement to the present element
    INTERFACE_ELEMENT* el_pt =
     dynamic_cast<INTERFACE_ELEMENT*>
     (Surface_mesh_pt->element_pt(e));
    // Set the Biot number
    el_pt->bi_pt() = &Global_Physical_Variables::Biot;
    // Set the Marangoni number
    el_pt->ma_pt() =&Global_Physical_Variables::Ma;
    // Set the Ca number
    el_pt->ca_pt() = &Global_Physical_Variables::Ca;
    // Set the surface elasticity number
    el_pt->beta_pt() = &Global_Physical_Variables::Beta_s;
    // Set the surface peclect number
    el_pt->peclet_s_pt() = &Global_Physical_Variables::Pe_s;
    // Set the surface peclect number multiplied by strouhal number
    el_pt->peclet_strouhal_s_pt() = &Global_Physical_Variables::Pe_s;
    // Set the reaction ratio
    el_pt->k_pt() = &Global_Physical_Variables::K_b;
    el_pt->beta_b_pt() = &Global_Physical_Variables::Beta_b;
   } // End of loop over interface elements
   }
References oomph::Global_Physical_Variables::Beta_b, oomph::Global_Physical_Variables::Beta_s, oomph::Global_Physical_Variables::Biot, oomph::Global_Physical_Variables::Ca, e(), oomph::Global_Physical_Variables::K_b, oomph::Global_Physical_Variables::M, oomph::Global_Physical_Variables::Ma, n, and oomph::Global_Physical_Variables::Pe_s.
Referenced by SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::SurfactantProblem().
create_interface_elements() [2/2]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::create_interface_elements () inline
Create the 1d interface elements.
   {
    //In the adaptive formulation the only way that we will know which elements
    //are on the lower or upper side is to use the density ratio
    //Store number of 1d nodes
    const unsigned n_node_1d = Bulk_mesh_pt->finite_element_pt(0)->nnode_1d();
    // Determine number of bulk elements adjacent to interface (boundary 4)
    const unsigned n_element = this->Bulk_mesh_pt->nboundary_element(4);
    // Loop over those elements adjacent to the interface
    for(unsigned e=0;e<n_element;e++)
     {
      // Get pointer to the bulk element that is adjacent to the interface
      ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
       this->Bulk_mesh_pt->boundary_element_pt(4,e));
      // We only want to attach interface elements to the bulk elements
      // which are BELOW the interface, and so we filter out those above by
      // referring to the viscosity_ratio_pt
      if(bulk_elem_pt->viscosity_ratio_pt() !=&Global_Physical_Variables::M)
     {
      // Find index of the face of element e that corresponds to the interface
      const int face_index = this->Bulk_mesh_pt->face_index_at_boundary(4,e);
      // Create the interface element
      INTERFACE_ELEMENT* interface_element_element_pt =
       new INTERFACE_ELEMENT(bulk_elem_pt,face_index);
      // Add the interface element to the surface mesh
      this->Surface_mesh_pt->add_element_pt(interface_element_element_pt);
     }
 //Otherwise it's on the upper side
      else
       {
     //Hijack all nodes of all elements
        unsigned n_max_node = n_node_1d;
        for(unsigned n=0;n<n_max_node;++n)
         {
          (void)bulk_elem_pt->hijack_nodal_value(n,2,false);
          (void)bulk_elem_pt->hijack_nodal_value(n,3,false);
         }
       }
     }
  // --------------------------------------------------------
  // Complete the setup to make the elements fully functional
  // --------------------------------------------------------
  // Determine number of 1D interface elements in mesh
  const unsigned n_interface_element = this->Surface_mesh_pt->nelement();
  // Loop over the interface elements
  for(unsigned e=0;e<n_interface_element;e++)
   {
    // Upcast from GeneralisedElement to the present element
    INTERFACE_ELEMENT* el_pt =
     dynamic_cast<INTERFACE_ELEMENT*>
     (Surface_mesh_pt->element_pt(e));
    // Set the Biot number
    el_pt->bi_pt() = &Global_Physical_Variables::Biot;
    // Set the Marangoni number
    el_pt->ma_pt() =&Global_Physical_Variables::Ma;
    // Set the Ca number
    el_pt->ca_pt() = &Global_Physical_Variables::Ca;
    // Set the surface elasticity number
    el_pt->beta_pt() = &Global_Physical_Variables::Beta_s;
    // Set the surface peclect number
    el_pt->peclet_s_pt() = &Global_Physical_Variables::Pe_s;
    // Set the surface peclect number multiplied by strouhal number
    el_pt->peclet_strouhal_s_pt() = &Global_Physical_Variables::Pe_s;
    // Set the reaction ratio
    el_pt->k_pt() = &Global_Physical_Variables::K_b;
    el_pt->beta_b_pt() = &Global_Physical_Variables::Beta_b;
   } // End of loop over interface elements
   }
References oomph::Global_Physical_Variables::Beta_b, oomph::Global_Physical_Variables::Beta_s, oomph::Global_Physical_Variables::Biot, oomph::Global_Physical_Variables::Ca, e(), oomph::Global_Physical_Variables::K_b, oomph::Global_Physical_Variables::M, oomph::Global_Physical_Variables::Ma, n, and oomph::Global_Physical_Variables::Pe_s.
create_slave_position_elements()
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::create_slave_position_elements () inline
Create the elements that slave the position.
   {
     //We know that boundary 1 is made periodic from boundary 3
     //We also know that the nodes have already been made periodic so we simply need
     //to create the slave elements to match the vertical positions
     const unsigned n_boundary_node = this->Bulk_mesh_pt->nboundary_node(1);
     for(unsigned n=0;n<n_boundary_node;++n)
       {
     //Cache the boundary node
     Node* nod_pt = this->Bulk_mesh_pt->boundary_node_pt(1,n);
     //Cache the master node
     Node* master_node_pt = nod_pt->copied_node_pt();
     //If there is no master node, then the node has no
     //counterpart on the other side and is therefore
     //not a degree of freedom and does not need to be
     //slaved
     if(master_node_pt!=0)
       {
         //Only create slaves for nodes that are not on the interface
         if(!(master_node_pt->is_on_boundary(0)) &&
            !(master_node_pt->is_on_boundary(2)) &&
            !(master_node_pt->is_on_boundary(4)))
           {
         //Create the slave node with a position ID
         this->Slave_position_mesh_pt->
           add_element_pt(new SlavePositionPointElement(master_node_pt,
                                    nod_pt,Periodic_index));
           }
       }
       }
   }
References oomph::Node::copied_node_pt(), oomph::Node::is_on_boundary(), and n.
deform_interface() [1/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::deform_interface (const double & epsilon, const unsigned & n_periods) inline
 {
  // Determine number of nodes in the "bulk" mesh
  const unsigned n_node = Bulk_mesh_pt->nnode();
  // Loop over all nodes in mesh
  for(unsigned n=0;n<n_node;n++)
   {
    // Determine eulerian position of node
    const double current_x_pos = Bulk_mesh_pt->node_pt(n)->x(0);
    const double current_y_pos = Bulk_mesh_pt->node_pt(n)->x(1);
    double y_scale = current_y_pos/Global_Physical_Variables::H0;
    if(current_y_pos > Global_Physical_Variables::H0)
     {
      y_scale = (1.0 - current_y_pos)/(1.0 - Global_Physical_Variables::H0);
     }
    // Determine new vertical position of node, *NEED TO THINK*
    const double new_y_pos = current_y_pos
      + y_scale*epsilon
     *(cos(n_periods*MathematicalConstants::Pi*
           (current_x_pos - Global_Physical_Variables::L)/Global_Physical_Variables::L));
    // Set new position
    Bulk_mesh_pt->node_pt(n)->x(1) = new_y_pos;
   }
 } // End of deform_free_surface
References cos(), oomph::SarahBL::epsilon, oomph::Global_Physical_Variables::H0, oomph::Global_Physical_Variables::L, n, and oomph::MathematicalConstants::Pi.
deform_interface() [2/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::deform_interface (const double & epsilon, const unsigned & n_periods) inline
 {
  // Determine number of nodes in the "bulk" mesh
  const unsigned n_node = Bulk_mesh_pt->nnode();
  // Loop over all nodes in mesh
  for(unsigned n=0;n<n_node;n++)
   {
    // Determine eulerian position of node
    const double current_x_pos = Bulk_mesh_pt->node_pt(n)->x(0);
    const double current_y_pos = Bulk_mesh_pt->node_pt(n)->x(1);
    double y_scale = current_y_pos/Global_Physical_Variables::H0;
    if(current_y_pos > Global_Physical_Variables::H0)
     {
      y_scale = (1.0 - current_y_pos)/(1.0 - Global_Physical_Variables::H0);
     }
    // Determine new vertical position of node, *NEED TO THINK*
    const double new_y_pos = current_y_pos
      + y_scale*epsilon
     *(cos(n_periods*MathematicalConstants::Pi*
           (current_x_pos - Global_Physical_Variables::L)/Global_Physical_Variables::L));
    // Set new position
    Bulk_mesh_pt->node_pt(n)->x(1) = new_y_pos;
   }
 } // End of deform_free_surface
References cos(), oomph::SarahBL::epsilon, oomph::Global_Physical_Variables::H0, oomph::Global_Physical_Variables::L, n, and oomph::MathematicalConstants::Pi.
deform_interface() [3/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::deform_interface (const double & epsilon, const unsigned & n_periods) inline
 {
   // Determine number of spines in mesh
   const unsigned n_spine = Bulk_mesh_pt->nspine();
   // Loop over spines in mesh
   for(unsigned i=0;i<n_spine;i++)
     {
       // Determine x coordinate of spine
       double x_value = Bulk_mesh_pt->boundary_node_pt(0,i)->x(0);
       // Set spine height
       Bulk_mesh_pt->spine_pt(i)->height() =
     Global_Physical_Variables::H0 +
     epsilon*(cos(n_periods*
              MathematicalConstants::Pi*(x_value - Global_Physical_Variables::L)/Global_Physical_Variables::L));
     }
   // Update nodes in bulk mesh
   Bulk_mesh_pt->node_update();
 } // End of deform_free_surface
References cos(), oomph::SarahBL::epsilon, oomph::Global_Physical_Variables::H0, i, oomph::Global_Physical_Variables::L, and oomph::MathematicalConstants::Pi.
delete_dependent_position_elements()
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::delete_dependent_position_elements () inline
Delete the 1d interface elements.
   {
     // Determine number of interface elements
     const unsigned n_dependent_element = Dependent_position_mesh_pt->nelement();
     // Loop over interface elements and delete
     for(unsigned e=0;e<n_dependent_element;e++)
       {
     delete Dependent_position_mesh_pt->element_pt(e);
       }
     // Wipe the mesh
     Dependent_position_mesh_pt->flush_element_and_node_storage();
   }
References e().
delete_interface_elements() [1/2]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::delete_interface_elements () inline
Delete the 1d interface elements.
   {
     // Determine number of interface elements
     const unsigned n_interface_element = Surface_mesh_pt->nelement();
     // Loop over interface elements and delete
     for(unsigned e=0;e<n_interface_element;e++)
       {
     delete Surface_mesh_pt->element_pt(e);
       }
     // Wipe the mesh
     Surface_mesh_pt->flush_element_and_node_storage();
   }
References e().
delete_interface_elements() [2/2]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::delete_interface_elements () inline
Delete the 1d interface elements.
   {
     // Determine number of interface elements
     const unsigned n_interface_element = Surface_mesh_pt->nelement();
     // Loop over interface elements and delete
     for(unsigned e=0;e<n_interface_element;e++)
       {
     delete Surface_mesh_pt->element_pt(e);
       }
     // Wipe the mesh
     Surface_mesh_pt->flush_element_and_node_storage();
   }
References e().
delete_slave_position_elements()
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::delete_slave_position_elements () inline
Delete the 1d interface elements.
   {
     // Determine number of interface elements
     const unsigned n_slave_element = Slave_position_mesh_pt->nelement();
     // Loop over interface elements and delete
     for(unsigned e=0;e<n_slave_element;e++)
       {
     delete Slave_position_mesh_pt->element_pt(e);
       }
     // Wipe the mesh
     Slave_position_mesh_pt->flush_element_and_node_storage();
   }
References e().
doc_solution() [1/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::doc_solution (std::ofstream & trace)
Doc the solution.
 {
  //Declare an output stream and filename
  ofstream some_file;
  char filename[100];
  // Number of plot points: npts x npts
  unsigned npts=5;
  // Output solution
  //-----------------
  sprintf(filename,"%s/soln%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  unsigned n_element = Bulk_mesh_pt->nelement();
  for(unsigned e=0;e<n_element;e++)
   {
    Bulk_mesh_pt->finite_element_pt(e)->output(some_file,npts);
   }
  some_file.close();
  //Output the interface
  sprintf(filename,"%s/int%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  unsigned n_interface  = Surface_mesh_pt->nelement();
  for(unsigned i=0;i<n_interface;i++)
   {
    Surface_mesh_pt->finite_element_pt(i)->output(some_file,npts);
   }
  some_file.close();
  //Let's get the mases
  double surface=0.0, bulk=0.0, micelle=0.0;
  this->compute_integrated_concentrations(surface,bulk,micelle);
  //double upper_area = 0.0, lower_area = 0.0;
  //this->compute_areas(lower_area,upper_area);
  //Compute the max and min
  double max = 0.0; double min = 0.0;
  this->interface_min_max(min,max);
  trace << time_pt()->time() << " "
        << this->Monitor_node_pt->x(1) << " "
        << this->Monitor_node_pt->value(2) << " "
        << this->Monitor_node_pt->value(3) << " "
        << this->Monitor_node_pt->value(4) << " "
        << std::sqrt(this->l2_norm_of_height(Global_Physical_Variables::H0)/(2.0*Global_Physical_Variables::L)) << " "
        << surface << " " << bulk << " " << micelle << " "
        << surface + (bulk + micelle)/(Global_Physical_Variables::Beta_b)
        << " " << min << " " << max << " "
    //<< " " << upper_area << " " << lower_area << " " << upper_area + lower_area
        << std::endl;
  Doc_info.number()++;
 } // end of doc
References oomph::Global_Physical_Variables::Beta_b, oomph::DocInfo::directory(), GlobalParameters::Doc_info, e(), MergeRestartFiles::filename, oomph::Global_Physical_Variables::H0, i, Global_Physical_Variables::L, max, min, oomph::DocInfo::number(), and sqrt().
doc_solution() [2/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::doc_solution (std::ofstream & trace)
Doc the solution.
doc_solution() [3/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::doc_solution (std::ofstream & trace)
Doc the solution.
fix_pressure() [1/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to specific element and fix pressure
    dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e))->
     fix_pressure(pdof,pvalue);
   } // end_of_fix_pressure
References e().
Referenced by SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::SurfactantProblem().
fix_pressure() [2/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to specific element and fix pressure
    dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e))->
     fix_pressure(pdof,pvalue);
   } // end_of_fix_pressure
References e().
fix_pressure() [3/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to specific element and fix pressure
    dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e))->
     fix_pressure(pdof,pvalue);
   } // end_of_fix_pressure
References e().
global_temporal_error_norm() [1/3]
template<class ELEMENT , class INTERFACE_ELEMENT > double SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::global_temporal_error_norm virtual
Function to calculate a global error norm, used in adaptive timestepping to control the change in timestep. Individual errors for each data object can be obtained via the data timestepper's temporal_error_in_value or temporal_error_in_position functions and should be combined to construct a global norm. For example, in fluids problems a suitable norm is usually the weighted sum of the errors in the velocities; for moving mesh problems is it usually better to use the weighted sum of the errors in position.
Reimplemented from oomph::Problem.
 {
  //Temp
  double global_error = 0.0;
  //Find out how many nodes there are in the problem
  unsigned long Nnode = Bulk_mesh_pt->nnode();
  //Loop over the nodes and calculate the errors in the positions
  for(unsigned long i=0;i<Nnode;i++)
   {
    //Find number of dimensions of the node
    unsigned Ndim = Bulk_mesh_pt->node_pt(i)->ndim();
    //Set the position error to zero
    double node_position_error = 0.0;
    //Loop over the dimensions (only need j=1)
    //for(unsigned j=0;j<Ndim;j++)
    unsigned j=1;
    {
      //Get position error
      double error =
       Bulk_mesh_pt->node_pt(i)->position_time_stepper_pt()->
       temporal_error_in_position(Bulk_mesh_pt->node_pt(i),j);
      //Add the square of the individual error to the position error
      node_position_error += error*error;
     }
    //Divide the position error by the number of dimensions
    node_position_error /= Ndim;
    //Now add to the global error
    global_error += node_position_error;
   }
    //Now the global error must be divided by the number of nodes
  global_error /= Nnode;
  //Return the square root of the errr
  return sqrt(global_error);
 }
References calibrate::error, i, j, and sqrt().
global_temporal_error_norm() [2/3]
template<class ELEMENT , class INTERFACE_ELEMENT > double SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::global_temporal_error_norm () virtual
Function to calculate a global error norm, used in adaptive timestepping to control the change in timestep. Individual errors for each data object can be obtained via the data timestepper's temporal_error_in_value or temporal_error_in_position functions and should be combined to construct a global norm. For example, in fluids problems a suitable norm is usually the weighted sum of the errors in the velocities; for moving mesh problems is it usually better to use the weighted sum of the errors in position.
Reimplemented from oomph::Problem.
global_temporal_error_norm() [3/3]
template<class ELEMENT , class INTERFACE_ELEMENT > double SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::global_temporal_error_norm () virtual
Function to calculate a global error norm, used in adaptive timestepping to control the change in timestep. Individual errors for each data object can be obtained via the data timestepper's temporal_error_in_value or temporal_error_in_position functions and should be combined to construct a global norm. For example, in fluids problems a suitable norm is usually the weighted sum of the errors in the velocities; for moving mesh problems is it usually better to use the weighted sum of the errors in position.
Reimplemented from oomph::Problem.
interface_min_max() [1/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::interface_min_max (double & min, double & max) inline
   {
     //Loop over the interface and add each elemental contribution
     const unsigned n_interface  = Surface_mesh_pt->nelement();
     if(n_interface > 0)
       {
     //Set the initial values to the first nodal position
     max = Surface_mesh_pt->finite_element_pt(0)->node_pt(0)->x(1);
     min = max;
     //Loop over all elements and find the max
     for(unsigned i=0;i<n_interface;i++)
       {
         // Upcast from GeneralsedElement to the present element
         INTERFACE_ELEMENT *el_pt =
           dynamic_cast<INTERFACE_ELEMENT*>(
                            Surface_mesh_pt->element_pt(i));
         const unsigned n_node = el_pt->nnode();
         if(n_node != 3)
           {
         std::cout << "Can't do max and min for elements that are not quadratic\n";
         return;
           }
         //Read out the y values from the nodes
         Vector<double> y(3);
         for(unsigned n=0;n<3;++n)
           {
         y[n] = el_pt->node_pt(n)->x(1);
           }
         double local_max = y[0];
         double local_min = y[0];
         //Find maximum and minimum nodes
         for(unsigned n=1;n<3;++n)
           {
         if(y[n] > local_max) {local_max = y[n];}
         if(y[n] < local_min) {local_min = y[n];}
           }
         //If we have a linear case then we are done
         //Check that it's not a degenerate (linear) case
         if(std::abs(y[0] - 2*y[1] + y[2]) > 1.0e-10)
           {
         //Calculate extreme value of the local coordinate based on known
         //quadratic basis functions (This shoudl really be inside the element class)
         Vector<double> extreme_s(1,0.5*(y[0] - y[2])/(y[0] - 2.0*y[1] + y[2]));
         //Find the extreme height if the local coordinate is within the
         //rane of the element
         if(std::abs(extreme_s[0]) <= 1.0)
           {
             double extreme_h = el_pt->interpolated_x(extreme_s,1);
             //Check whether the extreme value is greater than any of the nodes.
             if(extreme_h > local_max) {local_max = extreme_h;}
             if(extreme_h < local_min) {local_min = extreme_h;}
           }
           }
         //Now check whether local max and min are global
         if(local_max > max) {max = local_max;}
         if(local_min < min) {min = local_min;}
       }
       }
   }
References abs(), oomph::Mesh::element_pt(), oomph::Mesh::finite_element_pt(), i, max, min, n, oomph::Mesh::nelement(), oomph::FiniteElement::node_pt(), oomph::Node::x(), and y.
interface_min_max() [2/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::interface_min_max (double & min, double & max) inline
   {
     //Loop over the interface and add each elemental contribution
     const unsigned n_interface  = Surface_mesh_pt->nelement();
     if(n_interface > 0)
       {
     //Set the initial values to the first nodal position
     max = Surface_mesh_pt->finite_element_pt(0)->node_pt(0)->x(1);
     min = max;
     //Loop over all elements and find the max
     for(unsigned i=0;i<n_interface;i++)
       {
         // Upcast from GeneralsedElement to the present element
         INTERFACE_ELEMENT *el_pt =
           dynamic_cast<INTERFACE_ELEMENT*>(
                            Surface_mesh_pt->element_pt(i));
         const unsigned n_node = el_pt->nnode();
         if(n_node != 3)
           {
         std::cout << "Can't do max and min for elements that are not quadratic\n";
         return;
           }
         //Read out the y values from the nodes
         Vector<double> y(3);
         for(unsigned n=0;n<3;++n)
           {
         y[n] = el_pt->node_pt(n)->x(1);
           }
         double local_max = y[0];
         double local_min = y[0];
         //Find maximum and minimum nodes
         for(unsigned n=1;n<3;++n)
           {
         if(y[n] > local_max) {local_max = y[n];}
         if(y[n] < local_min) {local_min = y[n];}
           }
         //If we have a linear case then we are done
         //Check that it's not a degenerate (linear) case
         if(std::abs(y[0] - 2*y[1] + y[2]) > 1.0e-10)
           {
         //Calculate extreme value of the local coordinate based on known
         //quadratic basis functions (This shoudl really be inside the element class)
         Vector<double> extreme_s(1,0.5*(y[0] - y[2])/(y[0] - 2.0*y[1] + y[2]));
         //Find the extreme height if the local coordinate is within the
         //rane of the element
         if(std::abs(extreme_s[0]) <= 1.0)
           {
             double extreme_h = el_pt->interpolated_x(extreme_s,1);
             //Check whether the extreme value is greater than any of the nodes.
             if(extreme_h > local_max) {local_max = extreme_h;}
             if(extreme_h < local_min) {local_min = extreme_h;}
           }
           }
         //Now check whether local max and min are global
         if(local_max > max) {max = local_max;}
         if(local_min < min) {min = local_min;}
       }
       }
   }
References abs(), oomph::Mesh::element_pt(), oomph::Mesh::finite_element_pt(), i, max, min, n, oomph::Mesh::nelement(), oomph::FiniteElement::node_pt(), oomph::Node::x(), and y.
interface_min_max() [3/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::interface_min_max (double & min, double & max) inline
   {
     //Loop over the interface and add each elemental contribution
     const unsigned n_interface  = Surface_mesh_pt->nelement();
     if(n_interface > 0)
       {
     //Set the initial values to the first nodal position
     max = Surface_mesh_pt->finite_element_pt(0)->node_pt(0)->x(1);
     min = max;
     //Loop over all elements and find the max
     for(unsigned i=0;i<n_interface;i++)
       {
         // Upcast from GeneralsedElement to the present element
         INTERFACE_ELEMENT *el_pt =
           dynamic_cast<INTERFACE_ELEMENT*>(
                            Surface_mesh_pt->element_pt(i));
         const unsigned n_node = el_pt->nnode();
         if(n_node != 3)
           {
         std::cout << "Can't do max and min for elements that are not quadratic\n";
         return;
           }
         //Read out the y values from the nodes
         Vector<double> y(3);
         for(unsigned n=0;n<3;++n)
           {
         y[n] = el_pt->node_pt(n)->x(1);
           }
         double local_max = y[0];
         double local_min = y[0];
         //Find maximum and minimum nodes
         for(unsigned n=1;n<3;++n)
           {
         if(y[n] > local_max) {local_max = y[n];}
         if(y[n] < local_min) {local_min = y[n];}
           }
         //If we have a linear case then we are done
         //Check that it's not a degenerate (linear) case
         if(std::abs(y[0] - 2*y[1] + y[2]) > 1.0e-10)
           {
         //Calculate extreme value of the local coordinate based on known
         //quadratic basis functions (This shoudl really be inside the element class)
         Vector<double> extreme_s(1,0.5*(y[0] - y[2])/(y[0] - 2.0*y[1] + y[2]));
         //Find the extreme height if the local coordinate is within the
         //rane of the element
         if(std::abs(extreme_s[0]) <= 1.0)
           {
             double extreme_h = el_pt->interpolated_x(extreme_s,1);
             //Check whether the extreme value is greater than any of the nodes.
             if(extreme_h > local_max) {local_max = extreme_h;}
             if(extreme_h < local_min) {local_min = extreme_h;}
           }
           }
         //Now check whether local max and min are global
         if(local_max > max) {max = local_max;}
         if(local_min < min) {min = local_min;}
       }
       }
   }
References abs(), oomph::Mesh::element_pt(), oomph::Mesh::finite_element_pt(), i, max, min, n, oomph::Mesh::nelement(), oomph::FiniteElement::node_pt(), oomph::Node::x(), and y.
l2_norm_of_height() [1/3]
template<class ELEMENT , class INTERFACE_ELEMENT > double SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::l2_norm_of_height (const double & h0) inline
   {
    double norm = 0.0;
    //Loop over the interface and add each elemental contribution
    const unsigned n_interface  = Surface_mesh_pt->nelement();
    for(unsigned i=0;i<n_interface;i++)
     {
      // Upcast from GeneralsedElement to the present element
      INTERFACE_ELEMENT *el_pt =
       dynamic_cast<INTERFACE_ELEMENT*>(
        Surface_mesh_pt->element_pt(i));
      norm += el_pt->l2_norm_of_height(h0);
     }
    return norm;
   }
References oomph::Mesh::element_pt(), i, and oomph::Mesh::nelement().
l2_norm_of_height() [2/3]
template<class ELEMENT , class INTERFACE_ELEMENT > double SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::l2_norm_of_height (const double & h0) inline
   {
    double norm = 0.0;
    //Loop over the interface and add each elemental contribution
    const unsigned n_interface  = Surface_mesh_pt->nelement();
    for(unsigned i=0;i<n_interface;i++)
     {
      // Upcast from GeneralsedElement to the present element
      INTERFACE_ELEMENT *el_pt =
       dynamic_cast<INTERFACE_ELEMENT*>(
        Surface_mesh_pt->element_pt(i));
      norm += el_pt->l2_norm_of_height(h0);
     }
    return norm;
   }
References oomph::Mesh::element_pt(), i, and oomph::Mesh::nelement().
l2_norm_of_height() [3/3]
template<class ELEMENT , class INTERFACE_ELEMENT > double SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::l2_norm_of_height (const double & h0) inline
   {
    double norm = 0.0;
    //Loop over the interface and add each elemental contribution
    const unsigned n_interface  = Surface_mesh_pt->nelement();
    for(unsigned i=0;i<n_interface;i++)
     {
      // Upcast from GeneralsedElement to the present element
      INTERFACE_ELEMENT *el_pt =
       dynamic_cast<INTERFACE_ELEMENT*>(
        Surface_mesh_pt->element_pt(i));
      norm += el_pt->l2_norm_of_height(h0);
     }
    return norm;
   }
References oomph::Mesh::element_pt(), i, and oomph::Mesh::nelement().
set_boundary_conditions() [1/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::set_boundary_conditions (const double & time)
Set the boundary conditions.
Set the boundary conditions as a function of continuous time
 {
  //Set initial temperature profile
  if(time <= 0.0)
   {
     const double Gamma_init = 0.75;
     const double C_init = Gamma_init/(Global_Physical_Variables::K_b*(1.0-Gamma_init));
     const double M_init = pow(C_init,Global_Physical_Variables::N);
     unsigned n_lower = Bulk_mesh_pt->nlower();//nnode();
     for(unsigned e=0;e<n_lower;e++)
       {
     FiniteElement* el_pt =
       Bulk_mesh_pt->lower_layer_element_pt(e);
     unsigned n_node = el_pt->nnode();
     for(unsigned n=0;n<n_node;n++)
       {
         Node* nod_pt = el_pt->node_pt(n);
         //And in uniformly distributed surfactant
         //Be careful about upper and lower layers
         //If these are not set
         nod_pt->set_value(2,C_init);
         nod_pt->set_value(3,M_init);
         //Set the velocityq
         /*double y = nod_pt->x(1);
           nod_pt->set_value(0,y);
           nod_pt->set_value(1,0.0);*/
       }
       }
    //Set the initial surface concentration to be one
    unsigned n_surface_element = Surface_mesh_pt->nelement();
    for(unsigned e=0;e<n_surface_element;++e)
      {
        unsigned n_el_node = Surface_mesh_pt->finite_element_pt(e)->nnode();
        for(unsigned n=0;n<n_el_node;++n)
      {
        Surface_mesh_pt->finite_element_pt(e)->node_pt(n)->set_value(4,Gamma_init);
      }
      }
   } //End of initial conditions
  // Loop over the boundaries
  unsigned num_bound = Bulk_mesh_pt->nboundary();
  for(unsigned ibound=0;ibound<num_bound;ibound++)
   {
    // Loop over the nodes on boundary
    unsigned num_nod=Bulk_mesh_pt->nboundary_node(ibound);
    for(unsigned inod=0;inod<num_nod;inod++)
     {
      // Get pointer to node
      Node* nod_pt=Bulk_mesh_pt->boundary_node_pt(ibound,inod);
      if(!Control_Parameters::Periodic_BCs)
        {
      //If we are on the side walls we only set the v-velocity.
         if((ibound==1) || (ibound==3))
        {
          nod_pt->set_value(1,0.0);
        }
        }
      //If we are on the top boundary, do not set the velocities
      //(yet)
      if(ibound==2)
        {
      nod_pt->set_value(0,1.0); nod_pt->set_value(1,0.0);
        }
      //If we are on the bottom boundary
      if(ibound==0)
        {
      nod_pt->set_value(0,0.0); nod_pt->set_value(1,0.0);
        }
     }
   }
 } // end_of_set_boundary_conditions
References e(), oomph::Global_Physical_Variables::K_b, n, N, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Control_Parameters::Periodic_BCs, Eigen::ArrayBase< Derived >::pow(), and oomph::Data::set_value().
set_boundary_conditions() [2/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::set_boundary_conditions (const double & time)
Set the boundary conditions.
set_boundary_conditions() [3/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::set_boundary_conditions (const double & time)
Set the boundary conditions.
unfix_pressure() [1/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::unfix_pressure (const unsigned & e, const unsigned & pdof) inline
UnFix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to specific element and fix pressure
    dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e))->
     unfix_pressure(pdof);
   } // end_of_unfix_pressure
References e().
unfix_pressure() [2/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::unfix_pressure (const unsigned & e, const unsigned & pdof) inline
UnFix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to specific element and fix pressure
    dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e))->
     unfix_pressure(pdof);
   } // end_of_unfix_pressure
References e().
unfix_pressure() [3/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::unfix_pressure (const unsigned & e, const unsigned & pdof) inline
UnFix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to specific element and fix pressure
    dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e))->
     unfix_pressure(pdof);
   } // end_of_unfix_pressure
References e().
unpin_surface() [1/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::unpin_surface () inline
Release the free surface so that it can move.
   {
    //Only bother if the surface is pinned
    if(Surface_pinned)
     {
      Surface_pinned = false;
      //Unpin the heights of all nodes not on the boundaries
      unsigned n_node = Bulk_mesh_pt->nnode();
      for(unsigned n=0;n<n_node;n++)
       {
        SolidNode* nod_pt = static_cast<SolidNode*>(Bulk_mesh_pt->node_pt(n));
        if(!(nod_pt->is_on_boundary(0) || nod_pt->is_on_boundary(2)))
         {
          nod_pt->unpin_position(1);
         }
       }
      // Loop over the elements to re-enable ALE
      unsigned n_element = Bulk_mesh_pt->nelement();
      for(unsigned i=0;i<n_element;i++)
       {
        // Upcast from GeneralsedElement to the present element
        ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(i));
        el_pt->enable_ALE();
       }
      //Unpin the interfacial surfactant concentrations and Lagrange multipliers
      unsigned n_interface = Surface_mesh_pt->nelement();
      for(unsigned i=0;i<n_interface;i++)
       {
        FiniteElement *el_pt = Surface_mesh_pt->finite_element_pt(i);
        //Need to unpin the values of surfactant concentration and Lagrange multiplier
        unsigned n_el_node = el_pt->nnode();
        for(unsigned n=0;n<n_el_node;++n)
         {
       Node* nod_pt = el_pt->node_pt(n);
       nod_pt->unpin(4);
       nod_pt->unpin(5);
     }
       }
      //Now unpin the bulk concentrations in the lower region
      const unsigned n_lower = Bulk_mesh_pt->nlower();
       // Loop over bulk elements in lower fluid
       for(unsigned e=0;e<n_lower;e++)
     {
       // Upcast from GeneralisedElement to the present element
       ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->
                           lower_layer_element_pt(e));
       unsigned n_node = el_pt->nnode();
       for(unsigned n=0;n<n_node;++n)
         {
           el_pt->node_pt(n)->unpin(2); //Bulk Concentration
               el_pt->node_pt(n)->unpin(3); //Micelle Concentration
         }
        }
       //We also need to unpin the Lagrange multipliers for periodicity
       //We must not clash with the lagrange multiplier used to drive
       //the interface so we pin that at the left-hand-side
       {
     unsigned b=3;
     unsigned n_boundary_node = this->Bulk_mesh_pt->nboundary_node(b);
     for(unsigned n=0;n<n_boundary_node;++n)
       {
         Node* nod_pt = this->Bulk_mesh_pt->boundary_node_pt(b,n);
         //If we are not on the top or bottom boundary unpin
         if((!(nod_pt->is_on_boundary(0))) &&
            (!(nod_pt->is_on_boundary(2))) &&
                (!(nod_pt->is_on_boundary(4))))
           {
         unsigned lm_index = dynamic_cast<BoundaryNodeBase*>(nod_pt)
           ->index_of_first_value_assigned_by_face_element(
                                   Periodic_index);
         nod_pt->unpin(lm_index);
           }
       }
       }
      //Reassign the equation number
      std::cout << "Surface unpinned to give "
                << assign_eqn_numbers() << " equation numbers\n";
     }
   }
References b, e(), i, oomph::Node::is_on_boundary(), n, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Data::unpin(), and oomph::SolidNode::unpin_position().
unpin_surface() [2/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::unpin_surface () inline
Release the free surface so that it can move.
   {
    //Only bother if the surface is pinned
    if(Surface_pinned)
     {
      Surface_pinned = false;
      //Unpin the heights of all nodes not on the boundaries
      unsigned n_node = Bulk_mesh_pt->nnode();
      for(unsigned n=0;n<n_node;n++)
       {
        SolidNode* nod_pt = static_cast<SolidNode*>(Bulk_mesh_pt->node_pt(n));
        if(!(nod_pt->is_on_boundary(0) || nod_pt->is_on_boundary(2)))
         {
          nod_pt->unpin_position(1);
         }
       }
      // Loop over the elements to re-enable ALE
      unsigned n_element = Bulk_mesh_pt->nelement();
      for(unsigned i=0;i<n_element;i++)
       {
        // Upcast from GeneralsedElement to the present element
        ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(i));
        el_pt->enable_ALE();
       }
      //Unpin the interfacial surfactant concentrations and Lagrange multipliers
      unsigned n_interface = Surface_mesh_pt->nelement();
      for(unsigned i=0;i<n_interface;i++)
       {
        FiniteElement *el_pt = Surface_mesh_pt->finite_element_pt(i);
        //Need to unpin the values of surfactant concentration and Lagrange multiplier
        unsigned n_el_node = el_pt->nnode();
        for(unsigned n=0;n<n_el_node;++n)
         {
       Node* nod_pt = el_pt->node_pt(n);
       nod_pt->unpin(4);
       nod_pt->unpin(5);
     }
       }
      //Now unpin the bulk concentrations in the lower region
      const unsigned n_lower = Bulk_mesh_pt->nlower();
       // Loop over bulk elements in lower fluid
       for(unsigned e=0;e<n_lower;e++)
     {
       // Upcast from GeneralisedElement to the present element
       ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->
                           lower_layer_element_pt(e));
       unsigned n_node = el_pt->nnode();
       for(unsigned n=0;n<n_node;++n)
         {
           el_pt->node_pt(n)->unpin(2); //Bulk Concentration
           el_pt->node_pt(n)->pin(3);
               //el_pt->node_pt(n)->unpin(3); //Micelle Concentration
         }
        }
       //We also need to unpin the Lagrange multipliers for periodicity
       //We must not clash with the lagrange multiplier used to drive
       //the interface so we pin that at the left-hand-side
       {
     unsigned b=3;
     unsigned n_boundary_node = this->Bulk_mesh_pt->nboundary_node(b);
     for(unsigned n=0;n<n_boundary_node;++n)
       {
         Node* nod_pt = this->Bulk_mesh_pt->boundary_node_pt(b,n);
         //If we are not on the top or bottom boundary unpin
         if((!(nod_pt->is_on_boundary(0))) &&
            (!(nod_pt->is_on_boundary(2))) &&
                (!(nod_pt->is_on_boundary(4))))
           {
         unsigned lm_index = dynamic_cast<BoundaryNodeBase*>(nod_pt)
           ->index_of_first_value_assigned_by_face_element(
                                   Periodic_index);
         nod_pt->unpin(lm_index);
           }
       }
       }
      //Reassign the equation number
      std::cout << "Surface unpinned to give "
                << assign_eqn_numbers() << " equation numbers\n";
     }
   }
References b, e(), i, oomph::Node::is_on_boundary(), n, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Data::unpin(), and oomph::SolidNode::unpin_position().
unpin_surface() [3/3]
template<class ELEMENT , class INTERFACE_ELEMENT > void SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::unpin_surface () inline
Release the free surface so that it can move.
   {
    //Only bother if the surface is pinned
    if(Surface_pinned)
     {
      Surface_pinned = false;
      //Unpin the heights of all the spines in the middle
      unsigned n_spine = Bulk_mesh_pt->nspine();
      for(unsigned n=0;n<n_spine;n++)
       {
        Bulk_mesh_pt->spine_pt(n)->spine_height_pt()->unpin(0);
       }
      // Loop over the elements to re-enable ALE
      unsigned n_element = Bulk_mesh_pt->nelement();
      for(unsigned i=0;i<n_element;i++)
       {
        // Upcast from GeneralsedElement to the present element
        ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(i));
        el_pt->enable_ALE();
        //For testing this is where you can pin the pressures
        //unsigned n_internal = el_pt->ninternal_data();
        //for(unsigned i=0;i<n_internal;++i)
        // {
        //  el_pt->internal_data_pt(i)->pin_all();
        // }
       }
      //Pin the velocities
      /*unsigned n_node = Bulk_mesh_pt->nnode();
      for(unsigned n=0;n<n_node;++n)
       {
        Bulk_mesh_pt->node_pt(n)->pin(0);
        Bulk_mesh_pt->node_pt(n)->pin(1);
        }*/
      //Unpin the interfacial surfactant concentrations
      unsigned n_interface = Surface_mesh_pt->nelement();
      for(unsigned i=0;i<n_interface;i++)
       {
        FiniteElement *el_pt = Surface_mesh_pt->finite_element_pt(i);
        //Need to unpin the values of concentration and micelle
        unsigned n_el_node = el_pt->nnode();
        for(unsigned n=0;n<n_el_node;++n)
         {
          el_pt->node_pt(n)->unpin(4);
         }
       }
      //Now unpin the bulk concentrations in the lower region
      const unsigned n_lower = Bulk_mesh_pt->nlower();
       // Loop over bulk elements in lower fluid
       for(unsigned e=0;e<n_lower;e++)
     {
       // Upcast from GeneralisedElement to the present element
       ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->
                           lower_layer_element_pt(e));
       unsigned n_node = el_pt->nnode();
       for(unsigned n=0;n<n_node;++n)
         {
           el_pt->node_pt(n)->unpin(2); //Bulk Concentration
               el_pt->node_pt(n)->unpin(3); //Micelle Concentration
         }
        }
      //Reassign the equation number
      std::cout << "Surface unpinned to give "
                << assign_eqn_numbers() << " equation numbers\n";
     }
   }
References e(), i, n, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::Data::unpin().
Member Data Documentation
Backed_up_surface_mesh_pt
template<class ELEMENT , class INTERFACE_ELEMENT > BackupMeshForProjection< QElement< 1, 3 > > * SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Backed_up_surface_mesh_pt
Storage for the back up the surface mesh.
Bulk_mesh_pt [1/2]
template<class ELEMENT , class INTERFACE_ELEMENT > ElasticRefineableTwoLayerMesh< ELEMENT > * SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Bulk_mesh_pt
Overloaded version of the problem's access function to the mesh. Recasts the pointer to the base Mesh object to the actual mesh type.
Referenced by SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::SurfactantProblem().
Bulk_mesh_pt [2/2]
template<class ELEMENT , class INTERFACE_ELEMENT > TwoLayerSpineMesh<ELEMENT>* SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Bulk_mesh_pt
Overloaded version of the problem's access function to the mesh. Recasts the pointer to the base Mesh object to the actual mesh type.
Constitutive_law_pt
template<class ELEMENT , class INTERFACE_ELEMENT > ConstitutiveLaw * SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Constitutive_law_pt
Pointer to the constitutive law used to determine the mesh deformation.
Referenced by SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::SurfactantProblem().
Dependent_position_mesh_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Mesh* SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Dependent_position_mesh_pt
Storage for elements that constraint the vertical positions of the periodic nodes on the boundaries
Referenced by SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::SurfactantProblem().
Doc_info
template<class ELEMENT , class INTERFACE_ELEMENT > DocInfo SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Doc_info private
DocInfo object.
Referenced by SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::SurfactantProblem().
Inlet_traction_mesh_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Mesh * SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Inlet_traction_mesh_pt
Storage for any traction elements applied to the inlet.
Referenced by SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::SurfactantProblem().
Monitor_node_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Node * SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Monitor_node_pt private
Node used to monitor the interface height.
Referenced by SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::SurfactantProblem().
Outlet_traction_mesh_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Mesh * SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Outlet_traction_mesh_pt
Storage for any traction elements applied to the outlet.
Referenced by SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::SurfactantProblem().
Periodic_index
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Periodic_index private
Integer used to specify the Face ID of the Lagrange multipliers Used to enforce periodicity
Referenced by SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::SurfactantProblem().
Point_mesh_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Mesh * SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Point_mesh_pt
Storage to point elements if needed for non-periodic domains.
Referenced by SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::SurfactantProblem().
Slave_position_mesh_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Mesh* SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Slave_position_mesh_pt
Storage for elements that constraint the vertical positions of the periodic nodes on the boundaries
Surface_mesh_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Mesh * SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Surface_mesh_pt
Storage to the mesh of Surface interface elements.
Referenced by SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::SurfactantProblem().
Surface_pinned
template<class ELEMENT , class INTERFACE_ELEMENT > bool SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::Surface_pinned private
Boolean to indicate whether the surface is pinned.
Referenced by SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::SurfactantProblem().
The documentation for this class was generated from the following files:
refineable_two_layer_soluble_surfactant.cc
refineable_unstructured_two_layer_ss.cc
two_layer_soluble_surfactant.cc