MercuryDPM: DistributionPhiNormalSelfTest.cpp File Reference
DistributionPhiNormalSelfTest.cpp File Reference
#include <random>
#include "Mercury3D.h"
#include "Walls/InfiniteWall.h"
#include <Species/LinearViscoelasticFrictionSpecies.h>
#include "Particles/SphericalParticle.h"
#include "Boundaries/CubeInsertionBoundary.h"
#include "DPMBase.h"
Classes
class DistributionPhiNormalSelfTest
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     DistributionPhiNormalSelfTest st;
     st.setName("DistributionPhiNormalSelfTest");
     st.setMax({0.005, 0.005, 0.005});
     st.setGravity({0.0, 0.0, -9.8});
     st.setD50StandardDeviationAndNumofPSD(0.00025, 0.5, 100);
     st.setFileType(FileType::ONE_FILE);
     st.setParticlesWriteVTK(true);
     st.wallHandler.setWriteVTK(FileType::ONE_FILE);
     st.solve();
     st.particleHandler.saveNumberPSDtoCSV("DistributionPhiNormalSelfTestPSD.csv");
 }
References ONE_FILE, DPMBase::particleHandler, ParticleHandler::saveNumberPSDtoCSV(), DistributionPhiNormalSelfTest::setD50StandardDeviationAndNumofPSD(), DPMBase::setFileType(), DPMBase::setGravity(), DPMBase::setMax(), DPMBase::setName(), DPMBase::setParticlesWriteVTK(), WallHandler::setWriteVTK(), DPMBase::solve(), and DPMBase::wallHandler.