MercuryDPM: Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device > Struct Template Reference
#include <TensorEvaluator.h>
Public Types
enum {
IsAligned = true , PacketAccess = internal::functor_traits<NullaryOp>::PacketAccess , BlockAccess = false , PreferBlockAccess = false ,
CoordAccess = false , RawAccess = false
}
typedef TensorCwiseNullaryOp< NullaryOp, ArgType > XprType
typedef XprType::Index Index
typedef XprType::Scalar Scalar
typedef internal::traits< XprType >::Scalar CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef TensorEvaluator< ArgType, Device >::Dimensions Dimensions
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorBlockNotImplemented TensorBlock
Public Member Functions
EIGEN_DEVICE_FUNC TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EvaluatorPointerType data () const
Static Public Attributes
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Private Attributes
const NullaryOp m_functor
TensorEvaluator< ArgType, Device > m_argImpl
const internal::nullary_wrapper< CoeffReturnType, NullaryOp > m_wrapper
Member Typedef Documentation
CoeffReturnType
template<typename NullaryOp , typename ArgType , typename Device > typedef internal::traits<XprType>::Scalar Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::CoeffReturnType
Dimensions
template<typename NullaryOp , typename ArgType , typename Device > typedef TensorEvaluator<ArgType, Device>::Dimensions Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::Dimensions
EvaluatorPointerType
template<typename NullaryOp , typename ArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::EvaluatorPointerType
Index
template<typename NullaryOp , typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::Index
PacketReturnType
template<typename NullaryOp , typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::PacketReturnType
Scalar
template<typename NullaryOp , typename ArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::Scalar
Storage
template<typename NullaryOp , typename ArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::Storage
TensorBlock
template<typename NullaryOp , typename ArgType , typename Device > typedef internal::TensorBlockNotImplemented Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::TensorBlock
XprType
template<typename NullaryOp , typename ArgType , typename Device > typedef TensorCwiseNullaryOp<NullaryOp, ArgType> Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename NullaryOp , typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = true,
     PacketAccess = internal::functor_traits<NullaryOp>::PacketAccess
 #ifdef EIGEN_USE_SYCL
                    && (PacketType<CoeffReturnType, Device>::size > 1)
 #endif
         ,
     BlockAccess = false,
     PreferBlockAccess = false,
     CoordAccess = false,  // to be implemented
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename NullaryOp , typename ArgType , typename Device > EIGEN_DEVICE_FUNC Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_functor(op.functor()), m_argImpl(op.nestedExpression(), device), m_wrapper() {}
Member Function Documentation
cleanup()
template<typename NullaryOp , typename ArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::cleanup () inline
 {}
Referenced by framework.Frame::__init__().
coeff()
template<typename NullaryOp , typename ArgType , typename Device > EIGEN_DEVICE_FUNC CoeffReturnType Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::coeff (Index index) const inline
 { return m_wrapper(m_functor, index); }
costPerCoeff()
template<typename NullaryOp , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     return TensorOpCost(sizeof(CoeffReturnType), 0, 0, vectorized, PacketType<CoeffReturnType, Device>::size);
   }
data()
template<typename NullaryOp , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EvaluatorPointerType Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename NullaryOp , typename ArgType , typename Device > EIGEN_DEVICE_FUNC const Dimensions& Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::dimensions () const inline
 { return m_argImpl.dimensions(); }
evalSubExprsIfNeeded()
template<typename NullaryOp , typename ArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
 { return true; }
packet()
template<typename NullaryOp , typename ArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::packet (Index index) const inline
{
     return m_wrapper.template packetOp<PacketReturnType, Index>(m_functor, index);
   }
Member Data Documentation
Layout
template<typename NullaryOp , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_argImpl
template<typename NullaryOp , typename ArgType , typename Device > TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::m_argImpl private
m_functor
template<typename NullaryOp , typename ArgType , typename Device > const NullaryOp Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::m_functor private
m_wrapper
template<typename NullaryOp , typename ArgType , typename Device > const internal::nullary_wrapper<CoeffReturnType, NullaryOp> Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::m_wrapper private
PacketSize
template<typename NullaryOp , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorCwiseNullaryOp< NullaryOp, ArgType >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorEvaluator.h