MercuryDPM: Eigen::internal::TensorIntDivisor< T, div_gt_one > Struct Template Reference
Eigen::internal::TensorIntDivisor< T, div_gt_one > Struct Template Reference
#include <TensorIntDiv.h>
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorIntDivisor ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorIntDivisor (const T divider)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T divide (const T numerator) const
Private Types
typedef DividerTraits< T >::type UnsignedType
Private Attributes
UnsignedType multiplier
int32_t shift1
int32_t shift2
Member Typedef Documentation
UnsignedType
template<typename T , bool div_gt_one = false> typedef DividerTraits<T>::type Eigen::internal::TensorIntDivisor< T, div_gt_one >::UnsignedType private
Constructor & Destructor Documentation
TensorIntDivisor() [1/2]
template<typename T , bool div_gt_one = false> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::TensorIntDivisor< T, div_gt_one >::TensorIntDivisor () inline
{
     multiplier = 0;
     shift1 = 0;
     shift2 = 0;
   }
References Eigen::internal::TensorIntDivisor< T, div_gt_one >::multiplier, Eigen::internal::TensorIntDivisor< T, div_gt_one >::shift1, and Eigen::internal::TensorIntDivisor< T, div_gt_one >::shift2.
TensorIntDivisor() [2/2]
template<typename T , bool div_gt_one = false> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::TensorIntDivisor< T, div_gt_one >::TensorIntDivisor (const T divider) inline
{
     const int N = DividerTraits<T>::N;
     eigen_assert(static_cast<typename UnsignedTraits<T>::type>(divider) < NumTraits<UnsignedType>::highest() / 2);
     eigen_assert(divider > 0);
     // fast ln2
     const int leading_zeros = count_leading_zeros(static_cast<UnsignedType>(divider));
     int log_div = N - leading_zeros;
     // if divider is a power of two then log_div is 1 more than it should be.
     if ((static_cast<typename UnsignedTraits<T>::type>(1) << (log_div - 1)) ==
         static_cast<typename UnsignedTraits<T>::type>(divider))
       log_div--;
     multiplier = DividerHelper<N, T>::computeMultiplier(log_div, divider);
     shift1 = log_div > 1 ? 1 : log_div;
     shift2 = log_div > 1 ? log_div - 1 : 0;
   }
References Eigen::internal::DividerHelper< N, T >::computeMultiplier(), Eigen::internal::count_leading_zeros(), eigen_assert, Eigen::internal::TensorIntDivisor< T, div_gt_one >::multiplier, N, Eigen::internal::TensorIntDivisor< T, div_gt_one >::shift1, and Eigen::internal::TensorIntDivisor< T, div_gt_one >::shift2.
Member Function Documentation
divide()
template<typename T , bool div_gt_one = false> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T Eigen::internal::TensorIntDivisor< T, div_gt_one >::divide (const T numerator) const inline
{
     eigen_assert(static_cast<typename UnsignedTraits<T>::type>(numerator) < NumTraits<UnsignedType>::highest() / 2);
     // eigen_assert(numerator >= 0); // this is implicitly asserted by the line above
     UnsignedType t1 = muluh(multiplier, numerator);
     UnsignedType t = (static_cast<UnsignedType>(numerator) - t1) >> shift1;
     return (t1 + t) >> shift2;
   }
References eigen_assert, Eigen::internal::TensorIntDivisor< T, div_gt_one >::multiplier, Eigen::internal::muluh(), Eigen::internal::TensorIntDivisor< T, div_gt_one >::shift1, Eigen::internal::TensorIntDivisor< T, div_gt_one >::shift2, and plotPSD::t.
Referenced by Eigen::internal::operator/(), test_powers_32bit(), test_powers_64bit(), and test_specific().
Member Data Documentation
multiplier
template<typename T , bool div_gt_one = false> UnsignedType Eigen::internal::TensorIntDivisor< T, div_gt_one >::multiplier private
Referenced by Eigen::internal::TensorIntDivisor< T, div_gt_one >::divide(), and Eigen::internal::TensorIntDivisor< T, div_gt_one >::TensorIntDivisor().
shift1
template<typename T , bool div_gt_one = false> int32_t Eigen::internal::TensorIntDivisor< T, div_gt_one >::shift1 private
Referenced by Eigen::internal::TensorIntDivisor< T, div_gt_one >::divide(), and Eigen::internal::TensorIntDivisor< T, div_gt_one >::TensorIntDivisor().
shift2
template<typename T , bool div_gt_one = false> int32_t Eigen::internal::TensorIntDivisor< T, div_gt_one >::shift2 private
Referenced by Eigen::internal::TensorIntDivisor< T, div_gt_one >::divide(), and Eigen::internal::TensorIntDivisor< T, div_gt_one >::TensorIntDivisor().
The documentation for this struct was generated from the following file:
TensorIntDiv.h