MercuryDPM: Eigen::ForceAlignedAccess< ExpressionType > Class Template Reference
Eigen::ForceAlignedAccess< ExpressionType > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Enforce aligned packet loads and stores regardless of what is requested.
#include <ForceAlignedAccess.h>
Public Types
typedef internal::dense_xpr_base< ForceAlignedAccess >::type Base
Public Member Functions
EIGEN_DEVICE_FUNC ForceAlignedAccess (const ExpressionType &matrix)
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index outerStride () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index innerStride () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC const CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC const CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC Scalar & coeffRef (Index index)
template<int LoadMode>
const PacketScalar packet (Index row, Index col) const
template<int LoadMode>
void writePacket (Index row, Index col, const PacketScalar &x)
template<int LoadMode>
const PacketScalar packet (Index index) const
template<int LoadMode>
void writePacket (Index index, const PacketScalar &x)
EIGEN_DEVICE_FUNC operator const ExpressionType & () const
Protected Attributes
const ExpressionType & m_expression
Private Member Functions
ForceAlignedAccess & operator= (const ForceAlignedAccess &)
Detailed Description
template<typename ExpressionType>
class Eigen::ForceAlignedAccess< ExpressionType >
Enforce aligned packet loads and stores regardless of what is requested.
Parameters
ExpressionType the type of the object of which we are forcing aligned packet access
This class is the return type of MatrixBase::forceAlignedAccess() and most of the time this is the only way it is used.
See also
MatrixBase::forceAlignedAccess()
Member Typedef Documentation
Base
template<typename ExpressionType > typedef internal::dense_xpr_base<ForceAlignedAccess>::type Eigen::ForceAlignedAccess< ExpressionType >::Base
Constructor & Destructor Documentation
ForceAlignedAccess()
template<typename ExpressionType > EIGEN_DEVICE_FUNC Eigen::ForceAlignedAccess< ExpressionType >::ForceAlignedAccess (const ExpressionType & matrix) inline explicit
 : m_expression(matrix) {}
Member Function Documentation
coeff() [1/2]
template<typename ExpressionType > EIGEN_DEVICE_FUNC const CoeffReturnType Eigen::ForceAlignedAccess< ExpressionType >::coeff (Index index) const inline
 { return m_expression.coeff(index); }
References Eigen::ForceAlignedAccess< ExpressionType >::m_expression.
coeff() [2/2]
template<typename ExpressionType > EIGEN_DEVICE_FUNC const CoeffReturnType Eigen::ForceAlignedAccess< ExpressionType >::coeff (Index row, Index col) const inline
{
     return m_expression.coeff(row, col);
   }
References col(), Eigen::ForceAlignedAccess< ExpressionType >::m_expression, and row().
coeffRef() [1/2]
template<typename ExpressionType > EIGEN_DEVICE_FUNC Scalar& Eigen::ForceAlignedAccess< ExpressionType >::coeffRef (Index index) inline
 { return m_expression.const_cast_derived().coeffRef(index); }
References Eigen::ForceAlignedAccess< ExpressionType >::m_expression.
coeffRef() [2/2]
template<typename ExpressionType > EIGEN_DEVICE_FUNC Scalar& Eigen::ForceAlignedAccess< ExpressionType >::coeffRef (Index row, Index col) inline
{
     return m_expression.const_cast_derived().coeffRef(row, col);
   }
References col(), Eigen::ForceAlignedAccess< ExpressionType >::m_expression, and row().
cols()
template<typename ExpressionType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::ForceAlignedAccess< ExpressionType >::cols () const inline
 { return m_expression.cols(); }
References Eigen::ForceAlignedAccess< ExpressionType >::m_expression.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
innerStride()
template<typename ExpressionType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::ForceAlignedAccess< ExpressionType >::innerStride () const inline
{
     return m_expression.innerStride();
   }
References Eigen::ForceAlignedAccess< ExpressionType >::m_expression.
operator const ExpressionType &()
template<typename ExpressionType > EIGEN_DEVICE_FUNC Eigen::ForceAlignedAccess< ExpressionType >::operator const ExpressionType & () const inline
 { return m_expression; }
References Eigen::ForceAlignedAccess< ExpressionType >::m_expression.
operator=()
template<typename ExpressionType > ForceAlignedAccess& Eigen::ForceAlignedAccess< ExpressionType >::operator= (const ForceAlignedAccess< ExpressionType > &) private
outerStride()
template<typename ExpressionType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::ForceAlignedAccess< ExpressionType >::outerStride () const inline
{
     return m_expression.outerStride();
   }
References Eigen::ForceAlignedAccess< ExpressionType >::m_expression.
packet() [1/2]
template<typename ExpressionType > template<int LoadMode> const PacketScalar Eigen::ForceAlignedAccess< ExpressionType >::packet (Index index) const inline
{
     return m_expression.template packet<Aligned>(index);
   }
References Eigen::ForceAlignedAccess< ExpressionType >::m_expression.
packet() [2/2]
template<typename ExpressionType > template<int LoadMode> const PacketScalar Eigen::ForceAlignedAccess< ExpressionType >::packet (Index row, Index col) const inline
{
     return m_expression.template packet<Aligned>(row, col);
   }
References col(), Eigen::ForceAlignedAccess< ExpressionType >::m_expression, and row().
rows()
template<typename ExpressionType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::ForceAlignedAccess< ExpressionType >::rows () const inline
 { return m_expression.rows(); }
References Eigen::ForceAlignedAccess< ExpressionType >::m_expression.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
writePacket() [1/2]
template<typename ExpressionType > template<int LoadMode> void Eigen::ForceAlignedAccess< ExpressionType >::writePacket (Index index, const PacketScalar & x) inline
{
     m_expression.const_cast_derived().template writePacket<Aligned>(index, x);
   }
References Eigen::ForceAlignedAccess< ExpressionType >::m_expression, and plotDoE::x.
writePacket() [2/2]
template<typename ExpressionType > template<int LoadMode> void Eigen::ForceAlignedAccess< ExpressionType >::writePacket (Index row, Index col, const PacketScalar & x) inline
{
     m_expression.const_cast_derived().template writePacket<Aligned>(row, col, x);
   }
References col(), Eigen::ForceAlignedAccess< ExpressionType >::m_expression, row(), and plotDoE::x.
Member Data Documentation
m_expression
template<typename ExpressionType > const ExpressionType& Eigen::ForceAlignedAccess< ExpressionType >::m_expression protected
Referenced by Eigen::ForceAlignedAccess< ExpressionType >::coeff(), Eigen::ForceAlignedAccess< ExpressionType >::coeffRef(), Eigen::ForceAlignedAccess< ExpressionType >::cols(), Eigen::ForceAlignedAccess< ExpressionType >::innerStride(), Eigen::ForceAlignedAccess< ExpressionType >::operator const ExpressionType &(), Eigen::ForceAlignedAccess< ExpressionType >::outerStride(), Eigen::ForceAlignedAccess< ExpressionType >::packet(), Eigen::ForceAlignedAccess< ExpressionType >::rows(), and Eigen::ForceAlignedAccess< ExpressionType >::writePacket().
The documentation for this class was generated from the following file:
ForceAlignedAccess.h