MercuryDPM: exceptions.cpp File Reference
exceptions.cpp File Reference
#include "main.h"
#include "AnnoyingScalar.h"
Macros
#define EIGEN_STACK_ALLOCATION_LIMIT 100000000
#define CHECK_MEMLEAK(OP)
Functions
EIGEN_DECLARE_TEST (exceptions)
Macro Definition Documentation
CHECK_MEMLEAK
#define CHECK_MEMLEAK (OP)
Value:
  {                                                                                                                   \
    AnnoyingScalar::countdown = 100;                                                                                  \
    int before = AnnoyingScalar::instances;                                                                           \
    bool exception_thrown = false;                                                                                    \
    try {                                                                                                             \
      OP;                                                                                                             \
    } catch (my_exception) {                                                                                          \
      exception_thrown = true;                                                                                        \
      VERIFY(AnnoyingScalar::instances == before && "memory leak detected in " && EIGEN_MAKESTRING(OP));              \
    }                                                                                                                 \
    VERIFY((AnnoyingScalar::dont_throw) || (exception_thrown && " no exception thrown in " && EIGEN_MAKESTRING(OP))); \
  }
EIGEN_STACK_ALLOCATION_LIMIT
#define EIGEN_STACK_ALLOCATION_LIMIT 100000000
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (exceptions)
{
   typedef Eigen::Matrix<AnnoyingScalar, Dynamic, 1> VectorType;
   typedef Eigen::Matrix<AnnoyingScalar, Dynamic, Dynamic> MatrixType;
   {
     AnnoyingScalar::dont_throw = false;
     int n = 50;
     VectorType v0(n), v1(n);
     MatrixType m0(n, n), m1(n, n), m2(n, n);
     v0.setOnes();
     v1.setOnes();
     m0.setOnes();
     m1.setOnes();
     m2.setOnes();
     CHECK_MEMLEAK(v0 = m0 * m1 * v1);
     CHECK_MEMLEAK(m2 = m0 * m1 * m2);
     CHECK_MEMLEAK((v0 + v1).dot(v0 + v1));
   }
   VERIFY(AnnoyingScalar::instances == 0 && "global memory leak detected in " && EIGEN_MAKESTRING(OP));
 }
References CHECK_MEMLEAK, AnnoyingScalar::dont_throw, dot(), EIGEN_MAKESTRING, AnnoyingScalar::instances, m1, m2(), n, OP, v1(), and VERIFY.