MercuryDPM: AirySavageHutter.cpp File Reference
AirySavageHutter.cpp File Reference
#include <iostream>
#include "ChuteWithHopper.h"
#include "Walls/InfiniteWall.h"
#include "Species/LinearViscoelasticFrictionSpecies.h"
Classes
class AirySavageHutter
This code does the MD of a normal shock into a wall.
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     AirySavageHutter problem;
     // Problem parameters
     problem.setName("AirySavageHutter");
     problem.setTimeStep(1e-4);
     problem.setTimeMax(500.0);
     problem.setHGridMaxLevels(2);
     // Particle properties
     problem.setInflowParticleRadius(0.5);
     problem.setFixedParticleRadius(0.25);
     problem.setRoughBottomType(MULTILAYER);
     LinearViscoelasticFrictionSpecies species;
     species.setDensity(6 / constants::pi);
     species.setStiffness(2e5);
     species.setSlidingStiffness(2.0 / 7.0 * species.getStiffness());
     species.setDissipation(25.0);
     species.setSlidingDissipation(0);
     species.setSlidingFrictionCoefficient(0.5);
     problem.speciesHandler.copyAndAddObject(species);
     // Chute properties
     problem.setChuteAngleAndMagnitudeOfGravity(27.0, 1.0);
     problem.setChuteLength(250);
     problem.setChuteWidth(10);
     problem.setMaxFailed(6);
     problem.makeChutePeriodic();
     //Hopper properties
     Mdouble exitHeight = 10.0;
     Mdouble exitLength = 10.0;
     Mdouble hopperAngle = 45.0;
     Mdouble hopperLength = 2.0 * exitLength;
     Mdouble hopperHeight = hopperLength;
     problem.setHopper(exitLength, exitHeight, hopperAngle, hopperLength, hopperHeight);
     problem.setHopperFillingPercentage(50.0);
     // Xballs tunning
     problem.setXBallsScale(0.012);
     problem.setXBallsAdditionalArguments("-sort -v0 -oh 500 -cmode 4");
     // You really do not need data more often that once a second do not change this number away from this without
     // really good reason.
     problem.setSaveCount(helpers::getSaveCountFromNumberOfSavesAndTimeMaxAndTimeStep(500, problem.getTimeMax(),
                                                                                      problem.getTimeStep()));
     logger(INFO, "time step = %", problem.getTimeStep());
     problem.solve();
 }
References e(), helpers::getSaveCountFromNumberOfSavesAndTimeMaxAndTimeStep(), LinearViscoelasticNormalSpecies::getStiffness(), INFO, logger, MULTILAYER, constants::pi, problem, ParticleSpecies::setDensity(), LinearViscoelasticNormalSpecies::setDissipation(), SlidingFrictionSpecies::setSlidingDissipation(), SlidingFrictionSpecies::setSlidingFrictionCoefficient(), SlidingFrictionSpecies::setSlidingStiffness(), and LinearViscoelasticNormalSpecies::setStiffness().