MercuryDPM: Eigen::internal::scalar_fuzzy_default_impl< Scalar, true, false > Struct Template Reference
Eigen::internal::scalar_fuzzy_default_impl< Scalar, true, false > Struct Template Reference
#include <MathFunctions.h>
Public Types
typedef NumTraits< Scalar >::Real RealScalar
Static Public Member Functions
template<typename OtherScalar >
static EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const Scalar &x, const OtherScalar &y, const RealScalar &prec)
static EIGEN_DEVICE_FUNC bool isApprox (const Scalar &x, const Scalar &y, const RealScalar &prec)
Member Typedef Documentation
RealScalar
template<typename Scalar > typedef NumTraits<Scalar>::Real Eigen::internal::scalar_fuzzy_default_impl< Scalar, true, false >::RealScalar
Member Function Documentation
isApprox()
template<typename Scalar > static EIGEN_DEVICE_FUNC bool Eigen::internal::scalar_fuzzy_default_impl< Scalar, true, false >::isApprox (const Scalar & x, const Scalar & y, const RealScalar & prec) inline static
{
     return numext::abs2(x - y) <= numext::mini(numext::abs2(x), numext::abs2(y)) * prec * prec;
   }
References Eigen::numext::abs2(), Eigen::numext::mini(), plotDoE::x, and Eigen::internal::y.
isMuchSmallerThan()
template<typename Scalar > template<typename OtherScalar > static EIGEN_DEVICE_FUNC bool Eigen::internal::scalar_fuzzy_default_impl< Scalar, true, false >::isMuchSmallerThan (const Scalar & x, const OtherScalar & y, const RealScalar & prec) inline static
{
     return numext::abs2(x) <= numext::abs2(y) * prec * prec;
   }
References Eigen::numext::abs2(), plotDoE::x, and Eigen::internal::y.
The documentation for this struct was generated from the following file:
MathFunctions.h