MercuryDPM: Eigen::PolynomialSolver< Scalar_, Deg_ > Class Template Reference
Eigen::PolynomialSolver< Scalar_, Deg_ > Class Template Reference
A polynomial solver.
#include <PolynomialSolver.h>
Public Types
typedef PolynomialSolverBase< Scalar_, Deg_ > PS_Base
typedef Matrix< Scalar, Deg_, Deg_ > CompanionMatrixType
typedef std::conditional_t< NumTraits< Scalar >::IsComplex, ComplexEigenSolver< CompanionMatrixType >, EigenSolver< CompanionMatrixType > > EigenSolverType
typedef std::conditional_t< NumTraits< Scalar >::IsComplex, Scalar, std::complex< Scalar > > ComplexScalar
Public Types inherited from Eigen::PolynomialSolverBase< Scalar_, Deg_ >
typedef Scalar_ Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef std::complex< RealScalar > RootType
typedef Matrix< RootType, Deg_, 1 > RootsType
typedef DenseIndex Index
Public Member Functions
template<typename OtherPolynomial >
void compute (const OtherPolynomial &poly)
template<typename OtherPolynomial >
PolynomialSolver (const OtherPolynomial &poly)
PolynomialSolver ()
Public Member Functions inherited from Eigen::PolynomialSolverBase< Scalar_, Deg_ >
template<typename OtherPolynomial >
PolynomialSolverBase (const OtherPolynomial &poly)
PolynomialSolverBase ()
const RootsType & roots () const
template<typename Stl_back_insertion_sequence >
void realRoots (Stl_back_insertion_sequence &bi_seq, const RealScalar &absImaginaryThreshold=NumTraits< Scalar >::dummy_precision()) const
const RootType & greatestRoot () const
const RootType & smallestRoot () const
const RealScalar & absGreatestRealRoot (bool &hasArealRoot, const RealScalar &absImaginaryThreshold=NumTraits< Scalar >::dummy_precision()) const
const RealScalar & absSmallestRealRoot (bool &hasArealRoot, const RealScalar &absImaginaryThreshold=NumTraits< Scalar >::dummy_precision()) const
const RealScalar & greatestRealRoot (bool &hasArealRoot, const RealScalar &absImaginaryThreshold=NumTraits< Scalar >::dummy_precision()) const
const RealScalar & smallestRealRoot (bool &hasArealRoot, const RealScalar &absImaginaryThreshold=NumTraits< Scalar >::dummy_precision()) const
Protected Attributes
EigenSolverType m_eigenSolver
RootsType m_roots
Protected Attributes inherited from Eigen::PolynomialSolverBase< Scalar_, Deg_ >
RootsType m_roots
Additional Inherited Members
Protected Member Functions inherited from Eigen::PolynomialSolverBase< Scalar_, Deg_ >
template<typename OtherPolynomial >
void setPolynomial (const OtherPolynomial &poly)
template<typename squaredNormBinaryPredicate >
const RootType & selectComplexRoot_withRespectToNorm (squaredNormBinaryPredicate &pred) const
template<typename squaredRealPartBinaryPredicate >
const RealScalar & selectRealRoot_withRespectToAbsRealPart (squaredRealPartBinaryPredicate &pred, bool &hasArealRoot, const RealScalar &absImaginaryThreshold=NumTraits< Scalar >::dummy_precision()) const
template<typename RealPartBinaryPredicate >
const RealScalar & selectRealRoot_withRespectToRealPart (RealPartBinaryPredicate &pred, bool &hasArealRoot, const RealScalar &absImaginaryThreshold=NumTraits< Scalar >::dummy_precision()) const
Detailed Description
template<typename Scalar_, int Deg_>
class Eigen::PolynomialSolver< Scalar_, Deg_ >
A polynomial solver.
Computes the complex roots of a real polynomial.
Parameters
Scalar_ the scalar type, i.e., the type of the polynomial coefficients
Deg_ the degree of the polynomial, can be a compile time value or Dynamic. Notice that the number of polynomial coefficients is Deg_+1.
This class implements a polynomial solver and provides convenient methods such as
real roots,
greatest, smallest complex roots,
real roots with greatest, smallest absolute real value.
greatest, smallest real roots.
WARNING: this polynomial solver is experimental, part of the unsupported Eigen modules.
Currently a QR algorithm is used to compute the eigenvalues of the companion matrix of the polynomial to compute its roots. This supposes that the complex moduli of the roots are all distinct: e.g. there should be no multiple roots or conjugate roots for instance. With 32bit (float) floating types this problem shows up frequently. However, almost always, correct accuracy is reached even in these cases for 64bit (double) floating types and small polynomial degree (<20).
Member Typedef Documentation
CompanionMatrixType
template<typename Scalar_ , int Deg_> typedef Matrix<Scalar, Deg_, Deg_> Eigen::PolynomialSolver< Scalar_, Deg_ >::CompanionMatrixType
ComplexScalar
template<typename Scalar_ , int Deg_> typedef std::conditional_t<NumTraits<Scalar>::IsComplex, Scalar, std::complex<Scalar> > Eigen::PolynomialSolver< Scalar_, Deg_ >::ComplexScalar
EigenSolverType
template<typename Scalar_ , int Deg_> typedef std::conditional_t<NumTraits<Scalar>::IsComplex, ComplexEigenSolver<CompanionMatrixType>, EigenSolver<CompanionMatrixType> > Eigen::PolynomialSolver< Scalar_, Deg_ >::EigenSolverType
PS_Base
template<typename Scalar_ , int Deg_> typedef PolynomialSolverBase<Scalar_, Deg_> Eigen::PolynomialSolver< Scalar_, Deg_ >::PS_Base
Constructor & Destructor Documentation
PolynomialSolver() [1/2]
template<typename Scalar_ , int Deg_> template<typename OtherPolynomial > Eigen::PolynomialSolver< Scalar_, Deg_ >::PolynomialSolver (const OtherPolynomial & poly) inline
{
     compute(poly);
   }
References Eigen::PolynomialSolver< Scalar_, Deg_ >::compute().
PolynomialSolver() [2/2]
template<typename Scalar_ , int Deg_> Eigen::PolynomialSolver< Scalar_, Deg_ >::PolynomialSolver () inline
 {}
Member Function Documentation
compute()
template<typename Scalar_ , int Deg_> template<typename OtherPolynomial > void Eigen::PolynomialSolver< Scalar_, Deg_ >::compute (const OtherPolynomial & poly) inline
Computes the complex roots of a new polynomial.
{
     eigen_assert(Scalar(0) != poly[poly.size() - 1]);
     eigen_assert(poly.size() > 1);
     if (poly.size() > 2) {
       internal::companion<Scalar, Deg_> companion(poly);
       companion.balance();
       m_eigenSolver.compute(companion.denseMatrix());
       eigen_assert(m_eigenSolver.info() == Eigen::Success);
       m_roots = m_eigenSolver.eigenvalues();
       // cleanup noise in imaginary part of real roots:
       // if the imaginary part is rather small compared to the real part
       // and that cancelling the imaginary part yield a smaller evaluation,
       // then it's safe to keep the real part only.
       RealScalar coarse_prec = RealScalar(std::pow(4, poly.size() + 1)) * NumTraits<RealScalar>::epsilon();
       for (Index i = 0; i < m_roots.size(); ++i) {
         if (internal::isMuchSmallerThan(numext::abs(numext::imag(m_roots[i])), numext::abs(numext::real(m_roots[i])),
                                         coarse_prec)) {
           ComplexScalar as_real_root = ComplexScalar(numext::real(m_roots[i]));
           if (numext::abs(poly_eval(poly, as_real_root)) <= numext::abs(poly_eval(poly, m_roots[i]))) {
             m_roots[i] = as_real_root;
           }
         }
       }
     } else if (poly.size() == 2) {
       m_roots.resize(1);
       m_roots[0] = -poly[0] / poly[1];
     }
   }
References Eigen::numext::abs(), Eigen::internal::companion< Scalar_, Deg_ >::balance(), Eigen::internal::companion< Scalar_, Deg_ >::denseMatrix(), eigen_assert, oomph::SarahBL::epsilon, i, imag(), Eigen::internal::isMuchSmallerThan(), Eigen::PolynomialSolver< Scalar_, Deg_ >::m_eigenSolver, Eigen::PolynomialSolver< Scalar_, Deg_ >::m_roots, Eigen::poly_eval(), Eigen::bfloat16_impl::pow(), Eigen::PlainObjectBase< Derived >::resize(), and Eigen::Success.
Referenced by Eigen::PolynomialSolver< Scalar_, Deg_ >::PolynomialSolver(), and Eigen::PolynomialSolver< Scalar_, 1 >::PolynomialSolver().
Member Data Documentation
m_eigenSolver
template<typename Scalar_ , int Deg_> EigenSolverType Eigen::PolynomialSolver< Scalar_, Deg_ >::m_eigenSolver protected
Referenced by Eigen::PolynomialSolver< Scalar_, Deg_ >::compute().
m_roots
template<typename Scalar_ , int Deg_> RootsType Eigen::PolynomialSolverBase< Scalar_, Deg_ >::m_roots protected
Referenced by Eigen::PolynomialSolver< Scalar_, Deg_ >::compute(), and Eigen::PolynomialSolver< Scalar_, 1 >::compute().
The documentation for this class was generated from the following file:
PolynomialSolver.h