MercuryDPM: oomph::TetMeshBase Class Reference
oomph::TetMeshBase Class Reference
Base class for tet meshes (meshes made of 3D tet elements).
#include <tet_mesh.h>
Public Member Functions
TetMeshBase ()
Constructor.
TetMeshBase (const TetMeshBase &node)=delete
Broken copy constructor.
void operator= (const TetMeshBase &)=delete
Broken assignment operator.
virtual ~TetMeshBase ()
Destructor (empty)
void assess_mesh_quality (std::ofstream &some_file)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, const bool &switch_normal)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, const bool &switch_normal, std::ofstream &outfile)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, std::ofstream &outfile)
unsigned nboundary_element_in_region (const unsigned &b, const unsigned &r) const
Return the number of elements adjacent to boundary b in region r.
FiniteElement * boundary_element_in_region_pt (const unsigned &b, const unsigned &r, const unsigned &e) const
Return pointer to the e-th element adjacent to boundary b in region r.
int face_index_at_boundary_in_region (const unsigned &b, const unsigned &r, const unsigned &e) const
Return face index of the e-th element adjacent to boundary b in region r.
unsigned nregion ()
Return the number of regions specified by attributes.
unsigned nregion_element (const unsigned &r)
Return the number of elements in region r.
double region_attribute (const unsigned &i)
FiniteElement * region_element_pt (const unsigned &r, const unsigned &e)
Return the e-th element in the r-th region.
template<class ELEMENT >
void snap_to_quadratic_surface (const Vector< unsigned > &boundary_id, const std::string &quadratic_surface_file_name, const bool &switch_normal, DocInfo &doc_info)
template<class ELEMENT >
void snap_to_quadratic_surface (const Vector< unsigned > &boundary_id, const std::string &quadratic_surface_file_name, const bool &switch_normal)
void snap_nodes_onto_geometric_objects ()
template<class ELEMENT >
void split_elements_in_corners (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Static Public Attributes
static double Tolerance_for_boundary_finding = 1.0e-5
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Attributes
Vector< Vector< FiniteElement * > > Region_element_pt
Vector< double > Region_attribute
Vector< std::map< unsigned, Vector< FiniteElement * > > > Boundary_region_element_pt
Storage for elements adjacent to a boundary in a particular region.
Vector< std::map< unsigned, Vector< int > > > Face_index_region_at_boundary
TetMeshFacetedClosedSurface * Outer_boundary_pt
Faceted surface that defines outer boundaries.
Vector< TetMeshFacetedSurface * > Internal_surface_pt
Vector to faceted surfaces that define internal boundaries.
std::map< unsigned, TetMeshFacetedSurface * > Tet_mesh_faceted_surface_pt
std::map< unsigned, TetMeshFacet * > Tet_mesh_facet_pt
std::map< unsigned, Vector< Vector< double > > > Triangular_facet_vertex_boundary_coordinate
TimeStepper * Time_stepper_pt
Timestepper used to build nodes.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Detailed Description
Base class for tet meshes (meshes made of 3D tet elements).
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
TetMeshBase() [1/2]
oomph::TetMeshBase::TetMeshBase () inline
Constructor.
 : Outer_boundary_pt(0) {}
TetMeshBase() [2/2]
oomph::TetMeshBase::TetMeshBase (const TetMeshBase & node) delete
Broken copy constructor.
~TetMeshBase()
virtual oomph::TetMeshBase::~TetMeshBase () inline virtual
Destructor (empty)
 {}
Member Function Documentation
assess_mesh_quality()
void oomph::TetMeshBase::assess_mesh_quality (std::ofstream & some_file)
Assess mesh quality: Ratio of max. edge length to min. height, so if it's very large it's BAAAAAD.
   {
     Vector<Vector<double>> edge(6);
     for (unsigned e = 0; e < 6; e++)
     {
       edge[e].resize(3);
     }
     unsigned nel = this->nelement();
     for (unsigned e = 0; e < nel; e++)
     {
       FiniteElement* fe_pt = this->finite_element_pt(e);
       for (unsigned i = 0; i < 3; i++)
       {
         edge[0][i] = fe_pt->node_pt(2)->x(i) - fe_pt->node_pt(1)->x(i);
         edge[1][i] = fe_pt->node_pt(0)->x(i) - fe_pt->node_pt(2)->x(i);
         edge[2][i] = fe_pt->node_pt(1)->x(i) - fe_pt->node_pt(0)->x(i);
         edge[3][i] = fe_pt->node_pt(3)->x(i) - fe_pt->node_pt(0)->x(i);
         edge[4][i] = fe_pt->node_pt(3)->x(i) - fe_pt->node_pt(1)->x(i);
         edge[5][i] = fe_pt->node_pt(3)->x(i) - fe_pt->node_pt(2)->x(i);
       }
       double max_length = 0.0;
       for (unsigned j = 0; j < 6; j++)
       {
         double length = 0.0;
         for (unsigned i = 0; i < 3; i++)
         {
           length += edge[j][i] * edge[j][i];
         }
         length = sqrt(length);
         if (length > max_length) max_length = length;
       }
       double min_height = DBL_MAX;
       for (unsigned j = 0; j < 4; j++)
       {
         Vector<double> normal(3);
         unsigned e0 = 0;
         unsigned e1 = 0;
         unsigned e2 = 0;
         switch (j)
         {
           case 0:
             e0 = 4;
             e1 = 5;
             e2 = 1;
             break;
           case 1:
             e0 = 1;
             e1 = 3;
             e2 = 2;
             break;
           case 2:
             e0 = 3;
             e1 = 4;
             e2 = 1;
             break;
           case 3:
             e0 = 1;
             e1 = 2;
             e2 = 3;
             break;
           default:
             oomph_info << "never get here\n";
             abort();
         }
         normal[0] = edge[e0][1] * edge[e1][2] - edge[e0][2] * edge[e1][1];
         normal[1] = edge[e0][2] * edge[e1][0] - edge[e0][0] * edge[e1][2];
         normal[2] = edge[e0][0] * edge[e1][1] - edge[e0][1] * edge[e1][0];
         double norm =
           normal[0] * normal[0] + normal[1] * normal[1] + normal[2] * normal[2];
         double inv_norm = 1.0 / sqrt(norm);
         normal[0] *= inv_norm;
         normal[1] *= inv_norm;
         normal[2] *= inv_norm;
         double height = fabs(edge[e2][0] * normal[0] + edge[e2][1] * normal[1] +
                              edge[e2][2] * normal[2]);
         if (height < min_height) min_height = height;
       }
       double aspect_ratio = max_length / min_height;
       some_file << "ZONE N=4, E=1, F=FEPOINT, ET=TETRAHEDRON\n";
       for (unsigned j = 0; j < 4; j++)
       {
         for (unsigned i = 0; i < 3; i++)
         {
           some_file << fe_pt->node_pt(j)->x(i) << " ";
         }
         some_file << aspect_ratio << std::endl;
       }
       some_file << "1 2 3 4" << std::endl;
     }
   }
References e(), boost::multiprecision::fabs(), oomph::Mesh::finite_element_pt(), Global_Physical_Variables::height(), i, j, oomph::Mesh::nelement(), oomph::FiniteElement::node_pt(), WallFunction::normal(), oomph::oomph_info, sqrt(), and oomph::Node::x().
boundary_element_in_region_pt()
FiniteElement* oomph::TetMeshBase::boundary_element_in_region_pt (const unsigned & b, const unsigned & r, const unsigned & e) const inline
Return pointer to the e-th element adjacent to boundary b in region r.
     {
       // Use a constant iterator here to keep function "const" overall
       std::map<unsigned, Vector<FiniteElement*>>::const_iterator it =
         Boundary_region_element_pt[b].find(r);
       if (it != Boundary_region_element_pt[b].end())
       {
         return (it->second)[e];
       }
       else
       {
         return 0;
       }
     }
References b, Boundary_region_element_pt, e(), Eigen::placeholders::end, and UniformPSDSelfTest::r.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::adapt(), and oomph::RefineableGmshTetMesh< ELEMENT >::adapt().
face_index_at_boundary_in_region()
int oomph::TetMeshBase::face_index_at_boundary_in_region (const unsigned & b, const unsigned & r, const unsigned & e) const inline
Return face index of the e-th element adjacent to boundary b in region r.
     {
       // Use a constant iterator here to keep function "const" overall
       std::map<unsigned, Vector<int>>::const_iterator it =
         Face_index_region_at_boundary[b].find(r);
       if (it != Face_index_region_at_boundary[b].end())
       {
         return (it->second)[e];
       }
       else
       {
         std::ostringstream error_message;
         error_message << "Face indices not set up for boundary " << b
                       << " in region " << r << "\n";
         error_message << "This probably means that the boundary is not "
                          "adjacent to region\n";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
     }
References b, e(), Eigen::placeholders::end, Face_index_region_at_boundary, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and UniformPSDSelfTest::r.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::adapt(), and oomph::RefineableGmshTetMesh< ELEMENT >::adapt().
nboundary_element_in_region()
unsigned oomph::TetMeshBase::nboundary_element_in_region (const unsigned & b, const unsigned & r) const inline
Return the number of elements adjacent to boundary b in region r.
     {
       // Need to use a constant iterator here to keep the function "const"
       // Return an iterator to the appropriate entry, if we find it
       std::map<unsigned, Vector<FiniteElement*>>::const_iterator it =
         Boundary_region_element_pt[b].find(r);
       if (it != Boundary_region_element_pt[b].end())
       {
         return (it->second).size();
       }
       // Otherwise there are no elements adjacent to boundary b in the region r
       else
       {
         return 0;
       }
     }
References b, Boundary_region_element_pt, Eigen::placeholders::end, and UniformPSDSelfTest::r.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::adapt(), and oomph::RefineableGmshTetMesh< ELEMENT >::adapt().
nregion()
unsigned oomph::TetMeshBase::nregion () inline
Return the number of regions specified by attributes.
     {
       return Region_element_pt.size();
     }
References Region_element_pt.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::adapt(), and oomph::RefineableGmshTetMesh< ELEMENT >::adapt().
nregion_element()
unsigned oomph::TetMeshBase::nregion_element (const unsigned & r) inline
Return the number of elements in region r.
     {
       unsigned entry = 0;
       bool found = false;
       unsigned n = Region_attribute.size();
       for (unsigned i = 0; i < n; i++)
       {
 #ifdef PARANOID
         double diff =
           fabs(Region_attribute[i] -
                static_cast<double>(static_cast<unsigned>(Region_attribute[i])));
         if (diff > 0.0)
         {
           std::ostringstream error_message;
           error_message << "Region attributes should be unsigneds because we \n"
                         << "only use them to set region ids\n";
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         if (static_cast<unsigned>(Region_attribute[i]) == r)
         {
           entry = i;
           found = true;
           break;
         }
       }
       if (found)
       {
         return Region_element_pt[entry].size();
       }
       else
       {
         return 0;
       }
     }
References boost::multiprecision::fabs(), MergeRestartFiles::found, i, n, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, UniformPSDSelfTest::r, Region_attribute, and Region_element_pt.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::adapt(), and oomph::RefineableGmshTetMesh< ELEMENT >::adapt().
operator=()
void oomph::TetMeshBase::operator= (const TetMeshBase &) delete
Broken assignment operator.
region_attribute()
double oomph::TetMeshBase::region_attribute (const unsigned & i) inline
Return the i-th region attribute (here only used as the (assumed to be unsigned) region id
     {
       return Region_attribute[i];
     }
References i, and Region_attribute.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::adapt(), and oomph::RefineableGmshTetMesh< ELEMENT >::adapt().
region_element_pt()
FiniteElement* oomph::TetMeshBase::region_element_pt (const unsigned & r, const unsigned & e) inline
Return the e-th element in the r-th region.
     {
       unsigned entry = 0;
       bool found = false;
       unsigned n = Region_attribute.size();
       for (unsigned i = 0; i < n; i++)
       {
 #ifdef PARANOID
         double diff =
           fabs(Region_attribute[i] -
                static_cast<double>(static_cast<unsigned>(Region_attribute[i])));
         if (diff > 0.0)
         {
           std::ostringstream error_message;
           error_message << "Region attributes should be unsigneds because we \n"
                         << "only use the to set region ids\n";
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         if (static_cast<unsigned>(Region_attribute[i]) == r)
         {
           entry = i;
           found = true;
           break;
         }
       }
       if (found)
       {
         return Region_element_pt[entry][e];
       }
       else
       {
         return 0;
       }
     }
References e(), boost::multiprecision::fabs(), MergeRestartFiles::found, i, n, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, UniformPSDSelfTest::r, Region_attribute, and Region_element_pt.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::adapt(), and oomph::RefineableGmshTetMesh< ELEMENT >::adapt().
setup_boundary_coordinates() [1/4]
template<class ELEMENT > void oomph::TetMeshBase::setup_boundary_coordinates (const unsigned & b) inline
Setup boundary coordinate on boundary b which is assumed to be planar. Boundary coordinates are the x-y coordinates in the plane of that boundary, with the x-axis along the line from the (lexicographically) "lower left" to the "upper right" node. The y axis is obtained by taking the cross-product of the positive x direction with the outer unit normal computed by the face elements (or its negative if switch_normal is set to true). Doc faces in output file (if it's open).
Note 1: Setup of boundary coordinates is not done if the boundary in question turns out to be nonplanar.
Note 2: If a triangular TetMeshFacet is associated with a boundary we also store the boundary coordinates of its vertices. They are needed to interpolated intrinsic coordinates of an associated GeomObject (if any) into the interior.
     {
       // Dummy file
       std::ofstream some_file;
       // Don't switch the normal
       bool switch_normal = false;
       this->setup_boundary_coordinates<ELEMENT>(b, switch_normal, some_file);
     }
References b.
setup_boundary_coordinates() [2/4]
template<class ELEMENT > void oomph::TetMeshBase::setup_boundary_coordinates (const unsigned & b, const bool & switch_normal) inline
Setup boundary coordinate on boundary b which is assumed to be planar. Boundary coordinates are the x-y coordinates in the plane of that boundary, with the x-axis along the line from the (lexicographically) "lower left" to the "upper right" node. The y axis is obtained by taking the cross-product of the positive x direction with the outer unit normal computed by the face elements (or its negative if switch_normal is set to true). Doc faces in output file (if it's open).
Note 1: Setup of boundary coordinates is not done if the boundary in question turns out to be nonplanar.
Note 2: If a triangular TetMeshFacet is associated with a boundary we also store the boundary coordinates of its vertices. They are needed to interpolated intrinsic coordinates of an associated GeomObject (if any) into the interior. Final boolean argument allows switching of the direction of the outer unit normal.
     {
       // Dummy file
       std::ofstream some_file;
       this->setup_boundary_coordinates<ELEMENT>(b, switch_normal, some_file);
     }
References b.
setup_boundary_coordinates() [3/4]
template<class ELEMENT > void oomph::TetMeshBase::setup_boundary_coordinates (const unsigned & b, const bool & switch_normal, std::ofstream & outfile)
Setup boundary coordinate on boundary b which is assumed to be planar. Boundary coordinates are the x-y coordinates in the plane of that boundary, with the x-axis along the line from the (lexicographically) "lower left" to the "upper right" node. The y axis is obtained by taking the cross-product of the positive x direction with the outer unit normal computed by the face elements (or its negative if switch_normal is set to true). Doc faces in output file (if it's open).
Note 1: Setup of boundary coordinates is not done if the boundary in question turns out to be nonplanar.
Note 2: If a triangular TetMeshFacet is associated with a boundary we also store the boundary coordinates of its vertices. They are needed to interpolated intrinsic coordinates of an associated GeomObject (if any) into the interior. Boolean argument allows switching of the direction of the outer unit normal. Output file for doc.
/////////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////// Setup boundary coordinate on boundary b which is assumed to be planar. Boundary coordinates are the x-y coordinates in the plane of that boundary, with the x-axis along the line from the (lexicographically) "lower left" to the "upper right" node. The y axis is obtained by taking the cross-product of the positive x direction with the outer unit normal computed by the face elements (or its negative if switch_normal is set to true). Doc faces in output file (if it's open).
Note 1: Setup of boundary coordinates is not done if the boundary in question turns out to be nonplanar.
Note 2: If a triangular TetMeshFacet is associated with a boundary we also store the boundary coordinates of its vertices. They are needed to interpolated intrinsic coordinates of an associated GeomObject (if any) into the interior.
   {
     Node* lower_left_node_pt = 0;
     Node* upper_right_node_pt = 0;
     // Unit vector connecting lower left and upper right nodes
     Vector<double> b0(3);
     // ...and a vector normal to it
     Vector<double> b1(3);
     // Facet?
     TetMeshFacet* f_pt = 0;
     std::map<unsigned, TetMeshFacet*>::iterator it = Tet_mesh_facet_pt.find(b);
     if (it != Tet_mesh_facet_pt.end())
     {
       f_pt = (*it).second;
     }
     // std::cout << "Debug " << b;  f_pt->output(std::cout);
     // Number of vertices
     unsigned nv = 0;
     if (f_pt != 0)
     {
       nv = f_pt->nvertex();
     }
     // Check for planarity and bail out if nodes are not in the same plane
     bool vertices_are_in_same_plane = true;
     for (unsigned do_for_real = 0; do_for_real < 2; do_for_real++)
     {
       // Temporary storage for face elements
       Vector<FiniteElement*> face_el_pt;
       // Loop over all elements on boundaries
       unsigned nel = this->nboundary_element(b);
       if (nel > 0)
       {
         // Loop over the bulk elements adjacent to boundary b
         for (unsigned e = 0; e < nel; e++)
         {
           // Get pointer to the bulk element that is adjacent to boundary b
           FiniteElement* bulk_elem_pt = this->boundary_element_pt(b, e);
           // Find the index of the face of element e along boundary b
           int face_index = this->face_index_at_boundary(b, e);
           // Create new face element
           face_el_pt.push_back(
             new DummyFaceElement<ELEMENT>(bulk_elem_pt, face_index));
           // Output faces?
           if (outfile.is_open())
           {
             face_el_pt[face_el_pt.size() - 1]->output(outfile);
           }
         }
         // Loop over all nodes to find the lower left and upper right ones
         lower_left_node_pt = this->boundary_node_pt(b, 0);
         upper_right_node_pt = this->boundary_node_pt(b, 0);
         // Loop over all nodes on the boundary
         unsigned nnod = this->nboundary_node(b);
         for (unsigned j = 0; j < nnod; j++)
         {
           // Get node
           Node* nod_pt = this->boundary_node_pt(b, j);
           // Primary criterion for lower left: Does it have a lower
           // z-coordinate?
           if (nod_pt->x(2) < lower_left_node_pt->x(2))
           {
             lower_left_node_pt = nod_pt;
           }
           // ...or is it a draw?
           else if (nod_pt->x(2) == lower_left_node_pt->x(2))
           {
             // If it's a draw: Does it have a lower y-coordinate?
             if (nod_pt->x(1) < lower_left_node_pt->x(1))
             {
               lower_left_node_pt = nod_pt;
             }
             // ...or is it a draw?
             else if (nod_pt->x(1) == lower_left_node_pt->x(1))
             {
               // If it's a draw: Does it have a lower x-coordinate?
               if (nod_pt->x(0) < lower_left_node_pt->x(0))
               {
                 lower_left_node_pt = nod_pt;
               }
             }
           }
           // Primary criterion for upper right: Does it have a higher
           // z-coordinate?
           if (nod_pt->x(2) > upper_right_node_pt->x(2))
           {
             upper_right_node_pt = nod_pt;
           }
           // ...or is it a draw?
           else if (nod_pt->x(2) == upper_right_node_pt->x(2))
           {
             // If it's a draw: Does it have a higher y-coordinate?
             if (nod_pt->x(1) > upper_right_node_pt->x(1))
             {
               upper_right_node_pt = nod_pt;
             }
             // ...or is it a draw?
             else if (nod_pt->x(1) == upper_right_node_pt->x(1))
             {
               // If it's a draw: Does it have a higher x-coordinate?
               if (nod_pt->x(0) > upper_right_node_pt->x(0))
               {
                 upper_right_node_pt = nod_pt;
               }
             }
           }
         }
         // Prepare storage for boundary coordinates
         Vector<double> zeta(2);
         /*std::cout << upper_right_node_pt->x(0) << " "
                   << upper_right_node_pt->x(1) << " "
                   << upper_right_node_pt->x(2) << " L ";
         std::cout << lower_left_node_pt->x(0) << " "
                   << lower_left_node_pt->x(1) << " "
                   << lower_left_node_pt->x(2) << "\n ";*/
         // Unit vector connecting lower left and upper right nodes
         b0[0] = upper_right_node_pt->x(0) - lower_left_node_pt->x(0);
         b0[1] = upper_right_node_pt->x(1) - lower_left_node_pt->x(1);
         b0[2] = upper_right_node_pt->x(2) - lower_left_node_pt->x(2);
         // Normalise
         double inv_length =
           1.0 / sqrt(b0[0] * b0[0] + b0[1] * b0[1] + b0[2] * b0[2]);
         b0[0] *= inv_length;
         b0[1] *= inv_length;
         b0[2] *= inv_length;
         // std::cout << "B0 ";
         // std::cout << b0[0] << " " << b0[1] << " " << b0[2] << "\n";
         // Get (outer) unit normal to first face element
         Vector<double> normal(3);
         Vector<double> s(2, 0.0);
         if (nv != 3)
         {
           dynamic_cast<DummyFaceElement<ELEMENT>*>(face_el_pt[0])
             ->outer_unit_normal(s, normal);
         }
         else
         {
           double t1x = f_pt->vertex_pt(1)->x(0) - f_pt->vertex_pt(0)->x(0);
           double t1y = f_pt->vertex_pt(1)->x(1) - f_pt->vertex_pt(0)->x(1);
           double t1z = f_pt->vertex_pt(1)->x(2) - f_pt->vertex_pt(0)->x(2);
           double t2x = f_pt->vertex_pt(2)->x(0) - f_pt->vertex_pt(0)->x(0);
           double t2y = f_pt->vertex_pt(2)->x(1) - f_pt->vertex_pt(0)->x(1);
           double t2z = f_pt->vertex_pt(2)->x(2) - f_pt->vertex_pt(0)->x(2);
           normal[0] = t1y * t2z - t1z * t2y;
           normal[1] = t1z * t2x - t1x * t2z;
           normal[2] = t1x * t2y - t1y * t2x;
           double inv_length =
             1.0 / sqrt(normal[0] * normal[0] + normal[1] * normal[1] +
                        normal[2] * normal[2]);
           normal[0] *= inv_length;
           normal[1] *= inv_length;
           normal[2] *= inv_length;
         }
         if (switch_normal)
         {
           normal[0] = -normal[0];
           normal[1] = -normal[1];
           normal[2] = -normal[2];
         }
         // std::cout << "Normal ";
         // std::cout << normal[0] << " " << normal[1] << " " << normal[2] <<
         // "\n";
         // Check that all elements have the same normal
         for (unsigned e = 0; e < nel; e++)
         {
           // Get (outer) unit normal to face element
           Vector<double> my_normal(3);
           dynamic_cast<DummyFaceElement<ELEMENT>*>(face_el_pt[e])
             ->outer_unit_normal(s, my_normal);
           // Dot product should be one!
           double dot_prod = normal[0] * my_normal[0] +
                             normal[1] * my_normal[1] + normal[2] * my_normal[2];
           double error = abs(dot_prod) - 1.0;
           if (abs(error) > Tolerance_for_boundary_finding)
           {
             vertices_are_in_same_plane = false;
           }
         }
         // Bail out?
         if (vertices_are_in_same_plane)
         {
           // Cross-product to get second in-plane vector, normal to b0
           b1[0] = b0[1] * normal[2] - b0[2] * normal[1];
           b1[1] = b0[2] * normal[0] - b0[0] * normal[2];
           b1[2] = b0[0] * normal[1] - b0[1] * normal[0];
           // std::cout << "B1 ";
           // std::cout << b1[0] << " " << b1[1] << " " << b1[2] << "\n";
           // Assign boundary coordinates: projection onto the axes
           for (unsigned j = 0; j < nnod; j++)
           {
             // Get node
             Node* nod_pt = this->boundary_node_pt(b, j);
             // Difference vector to lower left corner
             Vector<double> delta(3);
             delta[0] = nod_pt->x(0) - lower_left_node_pt->x(0);
             delta[1] = nod_pt->x(1) - lower_left_node_pt->x(1);
             delta[2] = nod_pt->x(2) - lower_left_node_pt->x(2);
             /*std::cout << j << ": "
                       << nod_pt->x(0) << " " << nod_pt->x(1)
                       << "  " << nod_pt->x(2) << " Delta ";
             std::cout << delta[0] << " " << delta[1] << " " << delta[2] << "\n";
             */
             // Project
             zeta[0] = delta[0] * b0[0] + delta[1] * b0[1] + delta[2] * b0[2];
             zeta[1] = delta[0] * b1[0] + delta[1] * b1[1] + delta[2] * b1[2];
             // Check:
             double error = pow(lower_left_node_pt->x(0) + zeta[0] * b0[0] +
                                  zeta[1] * b1[0] - nod_pt->x(0),
                                2) +
                            pow(lower_left_node_pt->x(1) + zeta[0] * b0[1] +
                                  zeta[1] * b1[1] - nod_pt->x(1),
                                2) +
                            pow(lower_left_node_pt->x(2) + zeta[0] * b0[2] +
                                  zeta[1] * b1[2] - nod_pt->x(2),
                                2);
             if (sqrt(error) > Tolerance_for_boundary_finding)
             {
               std::ostringstream error_message;
               error_message
                 << "Error in projection of boundary coordinates = "
                 << sqrt(error) << " > Tolerance_for_boundary_finding = "
                 << Tolerance_for_boundary_finding << std::endl
                 << "nv = " << nv << std::endl
                 << "Lower left: " << lower_left_node_pt->x(0) << " "
                 << lower_left_node_pt->x(1) << " " << lower_left_node_pt->x(2)
                 << " " << std::endl
                 << "Upper right: " << upper_right_node_pt->x(0) << " "
                 << upper_right_node_pt->x(1) << " " << upper_right_node_pt->x(2)
                 << " " << std::endl
                 << "Nodes: ";
               for (unsigned j = 0; j < nnod; j++)
               {
                 // Get node
                 Node* nod_pt = this->boundary_node_pt(b, j);
                 error_message << nod_pt->x(0) << " " << nod_pt->x(1) << " "
                               << nod_pt->x(2) << " " << std::endl;
               }
               throw OomphLibError(error_message.str(),
                                   OOMPH_CURRENT_FUNCTION,
                                   OOMPH_EXCEPTION_LOCATION);
             }
             // Set boundary coordinate
             if (do_for_real == 1)
             {
               nod_pt->set_coordinates_on_boundary(b, zeta);
             }
           }
         } // End of if vertices are in the same plane
       }
       // Indicate that boundary coordinate has been set up
       if (do_for_real == 1)
       {
         Boundary_coordinate_exists[b] = true;
         // Facet associated with this boundary?
         if (f_pt != 0)
         {
           // Triangular facet: Set coordinates at vertices
           if (nv == 3)
           {
             Triangular_facet_vertex_boundary_coordinate[b].resize(3);
             for (unsigned j = 0; j < 3; j++)
             {
               // Two surface coordinates
               Triangular_facet_vertex_boundary_coordinate[b][j].resize(2);
               // Difference vector to lower left corner
               Vector<double> delta(3);
               delta[0] = f_pt->vertex_pt(j)->x(0) - lower_left_node_pt->x(0);
               delta[1] = f_pt->vertex_pt(j)->x(1) - lower_left_node_pt->x(1);
               delta[2] = f_pt->vertex_pt(j)->x(2) - lower_left_node_pt->x(2);
               // Project
               Vector<double> zeta(2);
               zeta[0] = delta[0] * b0[0] + delta[1] * b0[1] + delta[2] * b0[2];
               zeta[1] = delta[0] * b1[0] + delta[1] * b1[1] + delta[2] * b1[2];
               for (unsigned ii = 0; ii < 2; ii++)
               {
                 Triangular_facet_vertex_boundary_coordinate[b][j][ii] =
                   zeta[ii];
               }
             }
           }
         }
       }
       // Cleanup
       unsigned n = face_el_pt.size();
       for (unsigned e = 0; e < n; e++)
       {
         delete face_el_pt[e];
       }
       // Bail out?
       if (!vertices_are_in_same_plane)
       {
         /* oomph_info << "Vertices on boundary " << b  */
         /*            << " are not in the same plane; bailing out\n"; */
         return;
       }
     }
   }
References abs(), b, oomph::Mesh::Boundary_coordinate_exists, oomph::Mesh::boundary_element_pt(), oomph::Mesh::boundary_node_pt(), MultiOpt::delta, e(), calibrate::error, oomph::Mesh::face_index_at_boundary(), j, n, oomph::Mesh::nboundary_element(), oomph::Mesh::nboundary_node(), WallFunction::normal(), oomph::TetMeshFacet::nvertex(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, Eigen::bfloat16_impl::pow(), s, oomph::Node::set_coordinates_on_boundary(), sqrt(), Tet_mesh_facet_pt, Tolerance_for_boundary_finding, Triangular_facet_vertex_boundary_coordinate, oomph::TetMeshFacet::vertex_pt(), oomph::Node::x(), oomph::TetMeshVertex::x(), and Eigen::zeta().
setup_boundary_coordinates() [4/4]
template<class ELEMENT > void oomph::TetMeshBase::setup_boundary_coordinates (const unsigned & b, std::ofstream & outfile) inline
Setup boundary coordinate on boundary b which is assumed to be planar. Boundary coordinates are the x-y coordinates in the plane of that boundary, with the x-axis along the line from the (lexicographically) "lower left" to the "upper right" node. The y axis is obtained by taking the cross-product of the positive x direction with the outer unit normal computed by the face elements (or its negative if switch_normal is set to true). Doc faces in output file (if it's open).
Note 1: Setup of boundary coordinates is not done if the boundary in question turns out to be nonplanar.
Note 2: If a triangular TetMeshFacet is associated with a boundary we also store the boundary coordinates of its vertices. They are needed to interpolated intrinsic coordinates of an associated GeomObject (if any) into the interior. Output file for doc.
     {
       // Don't switch the normal
       bool switch_normal = false;
       this->setup_boundary_coordinates<ELEMENT>(b, switch_normal, outfile);
     }
References b.
setup_boundary_element_info() [1/2]
void oomph::TetMeshBase::setup_boundary_element_info () inline virtual
Setup lookup schemes which establish which elements are located next to mesh's boundaries (wrapper to suppress doc).
Reimplemented from oomph::Mesh.
     {
       std::ofstream outfile;
       this->setup_boundary_element_info(outfile);
     }
Referenced by split_elements_in_corners().
setup_boundary_element_info() [2/2]
void oomph::TetMeshBase::setup_boundary_element_info (std::ostream & outfile) virtual
Setup lookup schemes which establish which elements are located next to mesh's boundaries. Doc in outfile (if it's open).
Setup lookup schemes which establish which elements are located next to which boundaries (Doc to outfile if it's open).
Reimplemented from oomph::Mesh.
   {
     // Should we document the output here
     bool doc = false;
     if (outfile) doc = true;
     // Number of boundaries
     unsigned nbound = nboundary();
     // Wipe/allocate storage for arrays
     Boundary_element_pt.clear();
     Face_index_at_boundary.clear();
     Boundary_element_pt.resize(nbound);
     Face_index_at_boundary.resize(nbound);
     Lookup_for_elements_next_boundary_is_setup = false;
     // Temporary vector of vectors of pointers to elements on the boundaries:
     // This is a vector to ensure UNIQUE ordering in all processors
     Vector<Vector<FiniteElement*>> vector_of_boundary_element_pt;
     vector_of_boundary_element_pt.resize(nbound);
     // Matrix map for working out the fixed face for elements on boundary
     MapMatrixMixed<unsigned, FiniteElement*, int> face_identifier;
     // Loop over elements
     //-------------------
     unsigned nel = nelement();
     // Get pointer to vector of boundaries that the
     // node lives on
     Vector<std::set<unsigned>*> boundaries_pt(4, 0);
     for (unsigned e = 0; e < nel; e++)
     {
       // Get pointer to element
       FiniteElement* fe_pt = finite_element_pt(e);
       if (doc) outfile << "Element: " << e << " " << fe_pt << std::endl;
       // Only include 3D elements! Some meshes contain interface elements too.
       if (fe_pt->dim() == 3)
       {
         // Loop over the element's nodes and find out which boundaries they're
         // on
         // ----------------------------------------------------------------------
         // We need only loop over the corner nodes
         for (unsigned i = 0; i < 4; i++)
         {
           fe_pt->node_pt(i)->get_boundaries_pt(boundaries_pt[i]);
         }
         // Find the common boundaries of each face
         Vector<std::set<unsigned>> face(4);
         // NOTE: Face indices defined in Telements.h
         // Face 3 connnects points 0, 1 and 2
         if (boundaries_pt[0] && boundaries_pt[1] && boundaries_pt[2])
         {
           std::set<unsigned> aux;
           std::set_intersection(
             boundaries_pt[0]->begin(),
             boundaries_pt[0]->end(),
             boundaries_pt[1]->begin(),
             boundaries_pt[1]->end(),
             std::insert_iterator<std::set<unsigned>>(aux, aux.begin()));
           std::set_intersection(
             aux.begin(),
             aux.end(),
             boundaries_pt[2]->begin(),
             boundaries_pt[2]->end(),
             std::insert_iterator<std::set<unsigned>>(face[3], face[3].begin()));
         }
         // Face 2 connects points 0, 1 and 3
         if (boundaries_pt[0] && boundaries_pt[1] && boundaries_pt[3])
         {
           std::set<unsigned> aux;
           std::set_intersection(
             boundaries_pt[0]->begin(),
             boundaries_pt[0]->end(),
             boundaries_pt[1]->begin(),
             boundaries_pt[1]->end(),
             std::insert_iterator<std::set<unsigned>>(aux, aux.begin()));
           std::set_intersection(
             aux.begin(),
             aux.end(),
             boundaries_pt[3]->begin(),
             boundaries_pt[3]->end(),
             std::insert_iterator<std::set<unsigned>>(face[2], face[2].begin()));
         }
         // Face 1 connects points 0, 2 and 3
         if (boundaries_pt[0] && boundaries_pt[2] && boundaries_pt[3])
         {
           std::set<unsigned> aux;
           std::set_intersection(
             boundaries_pt[0]->begin(),
             boundaries_pt[0]->end(),
             boundaries_pt[2]->begin(),
             boundaries_pt[2]->end(),
             std::insert_iterator<std::set<unsigned>>(aux, aux.begin()));
           std::set_intersection(
             aux.begin(),
             aux.end(),
             boundaries_pt[3]->begin(),
             boundaries_pt[3]->end(),
             std::insert_iterator<std::set<unsigned>>(face[1], face[1].begin()));
         }
         // Face 0 connects points 1, 2 and 3
         if (boundaries_pt[1] && boundaries_pt[2] && boundaries_pt[3])
         {
           std::set<unsigned> aux;
           std::set_intersection(
             boundaries_pt[1]->begin(),
             boundaries_pt[1]->end(),
             boundaries_pt[2]->begin(),
             boundaries_pt[2]->end(),
             std::insert_iterator<std::set<unsigned>>(aux, aux.begin()));
           std::set_intersection(
             aux.begin(),
             aux.end(),
             boundaries_pt[3]->begin(),
             boundaries_pt[3]->end(),
             std::insert_iterator<std::set<unsigned>>(face[0], face[0].begin()));
         }
         // We now know whether any faces lay on the boundaries
         for (unsigned i = 0; i < 4; i++)
         {
           // How many boundaries are there
           unsigned count = 0;
           // The number of the boundary
           int boundary = -1;
           // Loop over all the members of the set and add to the count
           // and set the boundary
           for (std::set<unsigned>::iterator it = face[i].begin();
                it != face[i].end();
                ++it)
           {
             ++count;
             boundary = *it;
           }
           // If we're on more than one boundary, this is weird, so die
           if (count > 1)
           {
             std::ostringstream error_stream;
             fe_pt->output(error_stream);
             error_stream << "Face " << i << " is on " << count
                          << " boundaries.\n";
             error_stream << "This is rather strange.\n";
             error_stream << "Your mesh may be too coarse or your tet mesh\n";
             error_stream << "may be screwed up. I'm skipping the automated\n";
             error_stream << "setup of the elements next to the boundaries\n";
             error_stream << "lookup schemes.\n";
             OomphLibWarning(error_stream.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
           }
           // If we have a boundary then add this to the appropriate set
           if (boundary >= 0)
           {
             // Does the pointer already exits in the vector
             Vector<FiniteElement*>::iterator b_el_it = std::find(
               vector_of_boundary_element_pt[static_cast<unsigned>(boundary)]
                 .begin(),
               vector_of_boundary_element_pt[static_cast<unsigned>(boundary)]
                 .end(),
               fe_pt);
             // Only insert if we have not found it (i.e. got to the end)
             if (b_el_it ==
                 vector_of_boundary_element_pt[static_cast<unsigned>(boundary)]
                   .end())
             {
               vector_of_boundary_element_pt[static_cast<unsigned>(boundary)]
                 .push_back(fe_pt);
             }
             // Also set the fixed face
             face_identifier(static_cast<unsigned>(boundary), fe_pt) = i;
           }
         }
         // Now we set the pointers to the boundary sets to zero
         for (unsigned i = 0; i < 4; i++)
         {
           boundaries_pt[i] = 0;
         }
       }
     }
     // Now copy everything across into permanent arrays
     //-------------------------------------------------
     // Loop over boundaries
     //---------------------
     for (unsigned i = 0; i < nbound; i++)
     {
       // Number of elements on this boundary (currently stored in a set)
       unsigned nel = vector_of_boundary_element_pt[i].size();
       // Allocate storage for the coordinate identifiers
       Face_index_at_boundary[i].resize(nel);
       unsigned e_count = 0;
       typedef Vector<FiniteElement*>::iterator IT;
       for (IT it = vector_of_boundary_element_pt[i].begin();
            it != vector_of_boundary_element_pt[i].end();
            it++)
       {
         // Recover pointer to element
         FiniteElement* fe_pt = *it;
         // Add to permanent storage
         Boundary_element_pt[i].push_back(fe_pt);
         Face_index_at_boundary[i][e_count] = face_identifier(i, fe_pt);
         // Increment counter
         e_count++;
       }
     }
     // Doc?
     //-----
     if (doc)
     {
       // Loop over boundaries
       for (unsigned i = 0; i < nbound; i++)
       {
         unsigned nel = Boundary_element_pt[i].size();
         outfile << "Boundary: " << i << " is adjacent to " << nel << " elements"
                 << std::endl;
         // Loop over elements on given boundary
         for (unsigned e = 0; e < nel; e++)
         {
           FiniteElement* fe_pt = Boundary_element_pt[i][e];
           outfile << "Boundary element:" << fe_pt
                   << " Face index of boundary is "
                   << Face_index_at_boundary[i][e] << std::endl;
         }
       }
     }
     // Lookup scheme has now been setup yet
     Lookup_for_elements_next_boundary_is_setup = true;
   }
References oomph::Mesh::Boundary_element_pt, oomph::FiniteElement::dim(), e(), Eigen::placeholders::end, oomph::Mesh::Face_index_at_boundary, oomph::Mesh::finite_element_pt(), oomph::Node::get_boundaries_pt(), i, oomph::Mesh::Lookup_for_elements_next_boundary_is_setup, oomph::Mesh::nboundary(), oomph::Mesh::nelement(), oomph::FiniteElement::node_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::FiniteElement::output().
snap_nodes_onto_geometric_objects()
void oomph::TetMeshBase::snap_nodes_onto_geometric_objects ()
Move the nodes on boundaries with associated GeomObjects so that they exactly coincide with the geometric object. This requires that the boundary coordinates are set up consistently.
Move the nodes on boundaries with associated Geometric Objects (if any) so that they exactly coincide with the geometric object. This requires that the boundary coordinates are set up consistently
   {
     // Backup in case elements get inverted
     std::map<Node*, Vector<double>> old_nodal_posn;
     std::map<Node*, Vector<double>> new_nodal_posn;
     unsigned nnod = nnode();
     for (unsigned j = 0; j < nnod; j++)
     {
       Node* nod_pt = node_pt(j);
       Vector<double> x(3);
       nod_pt->position(x);
       old_nodal_posn[nod_pt] = x;
     }
     // Loop over all boundaries
     unsigned n_bound = this->nboundary();
     for (unsigned b = 0; b < n_bound; b++)
     {
       bool do_it = true;
       // Accumulate reason for not snapping
       std::stringstream reason;
       reason << "Can't snap nodes on boundary " << b
              << " onto geom object because: \n";
       TetMeshFacetedSurface* faceted_surface_pt = 0;
       std::map<unsigned, TetMeshFacetedSurface*>::iterator it =
         Tet_mesh_faceted_surface_pt.find(b);
       if (it != Tet_mesh_faceted_surface_pt.end())
       {
         faceted_surface_pt = (*it).second;
       }
       // Facet associated with this boundary?
       if (faceted_surface_pt == 0)
       {
         reason << "-- no facets asssociated with boundary\n";
         do_it = false;
       }
       // Get geom object associated with facet
       GeomObject* geom_obj_pt = 0;
       if (do_it)
       {
         geom_obj_pt = faceted_surface_pt->geom_object_with_boundaries_pt();
         if (geom_obj_pt == 0)
         {
           reason << "-- no geom object associated with boundary\n";
           do_it = false;
         }
       }
       // Triangular facet?
       if (Triangular_facet_vertex_boundary_coordinate[b].size() == 0)
       {
         reason << "-- facet has to be triangular and vertex coordinates have\n"
                << "   to have been set up\n";
         do_it = false;
       }
       // We need boundary coordinates!
       if (!Boundary_coordinate_exists[b])
       {
         reason << "-- no boundary coordinates were set up\n";
         do_it = false;
       }
       // Which facet is associated with this boundary?
       unsigned facet_id_of_boundary = 0;
       TetMeshFacet* f_pt = 0;
       if (do_it)
       {
         unsigned nf = faceted_surface_pt->nfacet();
         for (unsigned f = 0; f < nf; f++)
         {
           if ((faceted_surface_pt->one_based_facet_boundary_id(f) - 1) == b)
           {
             facet_id_of_boundary = f;
             break;
           }
         }
         f_pt = faceted_surface_pt->facet_pt(facet_id_of_boundary);
         // Three vertices?
         unsigned nv = f_pt->nvertex();
         if (nv != 3)
         {
           reason << "-- number of facet vertices is " << nv
                  << " rather than 3\n";
           do_it = false;
         }
         // Have we set up zeta coordinates in geometric object?
         if ((f_pt->vertex_pt(0)->zeta_in_geom_object().size() != 2) ||
             (f_pt->vertex_pt(1)->zeta_in_geom_object().size() != 2) ||
             (f_pt->vertex_pt(2)->zeta_in_geom_object().size() != 2))
         {
           reason << "-- no boundary coordinates were set up\n";
           do_it = false;
         }
       }
       // Are we ready to go?
       if (!do_it)
       {
         const bool tell_us_why = false;
         if (tell_us_why)
         {
           oomph_info << reason.str() << std::endl;
         }
       }
       else
       {
         // Setup area coordinantes in triangular facet
         double x1 = Triangular_facet_vertex_boundary_coordinate[b][0][0];
         double y1 = Triangular_facet_vertex_boundary_coordinate[b][0][1];
         double x2 = Triangular_facet_vertex_boundary_coordinate[b][1][0];
         double y2 = Triangular_facet_vertex_boundary_coordinate[b][1][1];
         double x3 = Triangular_facet_vertex_boundary_coordinate[b][2][0];
         double y3 = Triangular_facet_vertex_boundary_coordinate[b][2][1];
         double detT = (y2 - y3) * (x1 - x3) + (x3 - x2) * (y1 - y3);
         // Boundary coordinate (cartesian coordinates inside facet)
         Vector<double> zeta(2);
         // Loop over all nodes on that boundary
         const unsigned n_boundary_node = this->nboundary_node(b);
         for (unsigned n = 0; n < n_boundary_node; ++n)
         {
           // Get the boundary node and coordinates
           Node* const nod_pt = this->boundary_node_pt(b, n);
           nod_pt->get_coordinates_on_boundary(b, zeta);
           // Now we have zeta, the cartesian boundary coordinates
           // in the (assumed to be triangular) boundary facet; let's
           // work out the area coordinates
           // Notation as in
           // https://en.wikipedia.org/wiki/Barycentric_coordinate_system
           double s0 =
             ((y2 - y3) * (zeta[0] - x3) + (x3 - x2) * (zeta[1] - y3)) / detT;
           double s1 =
             ((y3 - y1) * (zeta[0] - x3) + (x1 - x3) * (zeta[1] - y3)) / detT;
           double s2 = 1.0 - s0 - s1;
           Vector<double> zeta_in_geom_obj(2, 0.0);
           Vector<double> position_from_geom_obj(3, 0.0);
           // Vertex zeta coordinates
           Vector<double> zeta_0(2);
           zeta_0 = f_pt->vertex_pt(0)->zeta_in_geom_object();
           Vector<double> zeta_1(2);
           zeta_1 = f_pt->vertex_pt(1)->zeta_in_geom_object();
           Vector<double> zeta_2(2);
           zeta_2 = f_pt->vertex_pt(2)->zeta_in_geom_object();
 #ifdef PARANOID
           // Compute zeta values of the vertices from parametrisation of
           // boundaries
           double tol = 1.0e-12;
           Vector<double> zeta_from_boundary(2);
           Vector<double> zeta_vertex(2);
           for (unsigned v = 0; v < 3; v++)
           {
             zeta_vertex = f_pt->vertex_pt(v)->zeta_in_geom_object();
             for (unsigned alt = 0; alt < 2; alt++)
             {
               switch (v)
               {
                 case 0:
                   if (alt == 0)
                   {
                     faceted_surface_pt->boundary_zeta01(
                       facet_id_of_boundary, 0.0, zeta_from_boundary);
                   }
                   else
                   {
                     faceted_surface_pt->boundary_zeta20(
                       facet_id_of_boundary, 1.0, zeta_from_boundary);
                   }
                   break;
                 case 1:
                   if (alt == 0)
                   {
                     faceted_surface_pt->boundary_zeta01(
                       facet_id_of_boundary, 1.0, zeta_from_boundary);
                   }
                   else
                   {
                     faceted_surface_pt->boundary_zeta12(
                       facet_id_of_boundary, 0.0, zeta_from_boundary);
                   }
                   break;
                 case 2:
                   if (alt == 0)
                   {
                     faceted_surface_pt->boundary_zeta12(
                       facet_id_of_boundary, 1.0, zeta_from_boundary);
                   }
                   else
                   {
                     faceted_surface_pt->boundary_zeta20(
                       facet_id_of_boundary, 0.0, zeta_from_boundary);
                   }
                   break;
               }
               double error =
                 sqrt(pow((zeta_vertex[0] - zeta_from_boundary[0]), 2) +
                      pow((zeta_vertex[1] - zeta_from_boundary[1]), 2));
               if (error > tol)
               {
                 std::ostringstream error_message;
                 error_message
                   << "Error in parametrisation of boundary coordinates \n"
                   << "for vertex " << v << " [alt=" << alt << "] in facet "
                   << facet_id_of_boundary << " : \n"
                   << "zeta_vertex = [ " << zeta_vertex[0] << " "
                   << zeta_vertex[1] << " ] \n"
                   << "zeta_from_boundary      = [ " << zeta_from_boundary[0]
                   << " " << zeta_from_boundary[1] << " ] \n"
                   << std::endl;
                 throw OomphLibError(error_message.str(),
                                     OOMPH_CURRENT_FUNCTION,
                                     OOMPH_EXCEPTION_LOCATION);
               }
             }
           }
 #endif
           // Compute zeta values of the interpolation parameters
           Vector<double> zeta_a(3, 0.0);
           Vector<double> zeta_b(3, 0.0);
           Vector<double> zeta_c(3, 0.0);
           Vector<double> zeta_d(3, 0.0);
           Vector<double> zeta_e(3, 0.0);
           Vector<double> zeta_f(3, 0.0);
           faceted_surface_pt->boundary_zeta01(facet_id_of_boundary, s1, zeta_a);
           faceted_surface_pt->boundary_zeta01(
             facet_id_of_boundary, 1.0 - s0, zeta_d);
           faceted_surface_pt->boundary_zeta12(facet_id_of_boundary, s2, zeta_c);
           faceted_surface_pt->boundary_zeta12(
             facet_id_of_boundary, 1.0 - s1, zeta_f);
           faceted_surface_pt->boundary_zeta20(
             facet_id_of_boundary, 1.0 - s2, zeta_b);
           faceted_surface_pt->boundary_zeta20(facet_id_of_boundary, s0, zeta_e);
           // Transfinite mapping
           zeta_in_geom_obj[0] = s0 * (zeta_a[0] + zeta_b[0] - zeta_0[0]) +
                                 s1 * (zeta_c[0] + zeta_d[0] - zeta_1[0]) +
                                 s2 * (zeta_e[0] + zeta_f[0] - zeta_2[0]);
           zeta_in_geom_obj[1] = s0 * (zeta_a[1] + zeta_b[1] - zeta_0[1]) +
                                 s1 * (zeta_c[1] + zeta_d[1] - zeta_1[1]) +
                                 s2 * (zeta_e[1] + zeta_f[1] - zeta_2[1]);
           unsigned n_tvalues =
             1 + nod_pt->position_time_stepper_pt()->nprev_values();
           for (unsigned t = 0; t < n_tvalues; ++t)
           {
             // Get the position according to the underlying geometric object
             geom_obj_pt->position(t, zeta_in_geom_obj, position_from_geom_obj);
             // Move the node
             for (unsigned i = 0; i < 3; i++)
             {
               nod_pt->x(t, i) = position_from_geom_obj[i];
             }
           }
         }
       }
     }
     // Check if any element is inverted
     bool some_element_is_inverted = false;
     unsigned count = 0;
     unsigned nel = nelement();
     for (unsigned e = 0; e < nel; e++)
     {
       FiniteElement* el_pt = finite_element_pt(e);
       bool passed = true;
       el_pt->check_J_eulerian_at_knots(passed);
       if (!passed)
       {
         some_element_is_inverted = true;
         char filename[100];
         std::ofstream some_file;
         sprintf(filename, "overly_distorted_element%i.dat", count);
         some_file.open(filename);
         unsigned nnod_1d = el_pt->nnode_1d();
         el_pt->output(some_file, nnod_1d);
         some_file.close();
         // Reset to old nodal position
         unsigned nnod = el_pt->nnode();
         for (unsigned j = 0; j < nnod; j++)
         {
           Node* nod_pt = el_pt->node_pt(j);
           Vector<double> x_current(3);
           nod_pt->position(x_current);
           new_nodal_posn[nod_pt] = x_current;
           Vector<double> old_x(old_nodal_posn[nod_pt]);
           for (unsigned i = 0; i < 3; i++)
           {
             nod_pt->x(i) = old_x[i];
           }
         }
         // Plot
         sprintf(filename, "orig_overly_distorted_element%i.dat", count);
         some_file.open(filename);
         el_pt->output(some_file, nnod_1d);
         some_file.close();
         // Reset
         for (unsigned j = 0; j < nnod; j++)
         {
           Node* nod_pt = el_pt->node_pt(j);
           for (unsigned i = 0; i < 3; i++)
           {
             nod_pt->x(i) = new_nodal_posn[nod_pt][i];
           }
         }
         // Bump
         count++;
       }
     }
     if (some_element_is_inverted)
     {
       std::ostringstream error_message;
       error_message
         << "A number of elements, namely: " << count
         << " are inverted after snapping. Their shapes are in "
         << " overly_distorted_element*.dat and "
            "orig_overly_distorted_element*.dat"
         << "Next person to get this error: Please implement a straightforward\n"
         << "variant of one of the functors in src/mesh_smoothing to switch\n"
         << "to harmonic mapping\n"
         << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     else
     {
       oomph_info << "No elements are inverted after snapping. Yay!"
                  << std::endl;
     }
   }
References b, oomph::Mesh::Boundary_coordinate_exists, oomph::Mesh::boundary_node_pt(), oomph::TetMeshFacetedSurface::boundary_zeta01(), oomph::TetMeshFacetedSurface::boundary_zeta12(), oomph::TetMeshFacetedSurface::boundary_zeta20(), oomph::FiniteElement::check_J_eulerian_at_knots(), e(), calibrate::error, f(), oomph::TetMeshFacetedSurface::facet_pt(), MergeRestartFiles::filename, oomph::Mesh::finite_element_pt(), oomph::TetMeshFacetedSurface::geom_object_with_boundaries_pt(), oomph::Node::get_coordinates_on_boundary(), i, j, n, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_node(), oomph::Mesh::nelement(), oomph::TetMeshFacetedSurface::nfacet(), oomph::FiniteElement::nnode(), oomph::Mesh::nnode(), oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::node_pt(), oomph::Mesh::node_pt(), oomph::TimeStepper::nprev_values(), oomph::TetMeshFacet::nvertex(), oomph::TetMeshFacetedSurface::one_based_facet_boundary_id(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, oomph::FiniteElement::output(), oomph::GeomObject::position(), oomph::Node::position(), oomph::Node::position_time_stepper_pt(), Eigen::bfloat16_impl::pow(), size, sqrt(), plotPSD::t, Tet_mesh_faceted_surface_pt, Triangular_facet_vertex_boundary_coordinate, v, oomph::TetMeshFacet::vertex_pt(), plotDoE::x, oomph::Node::x(), Global_parameters::x1(), Global_parameters::x2(), Eigen::zeta(), and oomph::TetMeshVertex::zeta_in_geom_object().
Referenced by oomph::GmshTetMesh< ELEMENT >::build_it(), oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh(), and oomph::TetgenMesh< ELEMENT >::TetgenMesh().
snap_to_quadratic_surface() [1/2]
template<class ELEMENT > void oomph::TetMeshBase::snap_to_quadratic_surface (const Vector< unsigned > & boundary_id, const std::string & quadratic_surface_file_name, const bool & switch_normal) inline
Snap boundaries specified by the IDs listed in boundary_id to a quadratric surface, specified in the file quadratic_surface_file_name. This is usually used with vmtk-based meshes for which oomph-lib's xda to poly conversion code produces the files "quadratic_fsi_boundary.dat" and "quadratic_outer_solid_boundary.dat" which specify the quadratic FSI boundary (for the fluid and the solid) and the quadratic representation of the outer boundary of the solid. When used with these files, the flag switch_normal should be set to true when calling the function for the outer boundary of the solid.
     {
       // Dummy doc info
       DocInfo doc_info;
       doc_info.disable_doc();
       snap_to_quadratic_surface<ELEMENT>(
         boundary_id, quadratic_surface_file_name, switch_normal, doc_info);
     }
References oomph::DocInfo::disable_doc().
snap_to_quadratic_surface() [2/2]
template<class ELEMENT > void oomph::TetMeshBase::snap_to_quadratic_surface (const Vector< unsigned > & boundary_id, const std::string & quadratic_surface_file_name, const bool & switch_normal, DocInfo & doc_info)
Snap boundaries specified by the IDs listed in boundary_id to a quadratric surface, specified in the file quadratic_surface_file_name. This is usually used with vmtk-based meshes for which oomph-lib's xda to poly conversion code produces the files "quadratic_fsi_boundary.dat" and "quadratic_outer_solid_boundary.dat" which specify the quadratic FSI boundary (for the fluid and the solid) and the quadratic representation of the outer boundary of the solid. When used with these files, the flag switch_normal should be set to true when calling the function for the outer boundary of the solid. The DocInfo object can be used to label optional output files. (Uses directory and label).
   {
     // Aux storage for processing input
     char dummy[101];
     // Prepare to doc nodes that couldn't be snapped
     std::ofstream the_file_non_snapped;
     std::string non_snapped_filename =
       "non_snapped_nodes_" + doc_info.label() + ".dat";
     // Read the number of nodes and elements (quadratic facets)
     std::ifstream infile(quadratic_surface_file_name.c_str(),
                          std::ios_base::in);
     unsigned n_node;
     infile >> n_node;
     // Ignore rest of line
     infile.getline(dummy, 100);
     // Number of quadratic facets
     unsigned nel;
     infile >> nel;
     // Ignore rest of line
     infile.getline(dummy, 100);
     // Check that the number of elements matches
     if (nel != boundary_id.size())
     {
       std::ostringstream error_message;
       error_message << "Number of quadratic facets specified in  "
                     << quadratic_surface_file_name << "is: " << nel
                     << "\nThis doesn't match the number of planar boundaries \n"
                     << "specified in boundary_id which is "
                     << boundary_id.size() << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Temporary storage for face elements
     Vector<FreeStandingFaceElement<ELEMENT>*> face_el_pt;
     // Loop over quadratic face elements -- one for each facet
     for (unsigned e = 0; e < nel; e++)
     {
       face_el_pt.push_back(new FreeStandingFaceElement<ELEMENT>);
     }
     // Now build nodes
     unsigned n_dim = 3;
     unsigned n_position_type = 1;
     unsigned initial_n_value = 0;
     Vector<Node*> nod_pt(n_node);
     unsigned node_nmbr;
     std::map<unsigned, unsigned> node_number;
     std::ofstream node_file;
     for (unsigned j = 0; j < n_node; j++)
     {
       nod_pt[j] =
         new BoundaryNode<Node>(n_dim, n_position_type, initial_n_value);
       infile >> nod_pt[j]->x(0);
       infile >> nod_pt[j]->x(1);
       infile >> nod_pt[j]->x(2);
       infile >> node_nmbr;
       node_number[node_nmbr] = j;
     }
     // Now assign nodes to elements -- each element represents
     // distinct boundary; assign enumeration as specified by
     // boundary_id.
     for (unsigned e = 0; e < nel; e++)
     {
       unsigned nnod_el = face_el_pt[e]->nnode();
       unsigned j_global;
       for (unsigned j = 0; j < nnod_el; j++)
       {
         infile >> j_global;
         face_el_pt[e]->node_pt(j) = nod_pt[node_number[j_global]];
         face_el_pt[e]->node_pt(j)->add_to_boundary(boundary_id[e]);
       }
       face_el_pt[e]->set_boundary_number_in_bulk_mesh(boundary_id[e]);
       face_el_pt[e]->set_nodal_dimension(3);
     }
     // Setup boundary coordinates for each facet, using
     // the same strategy as for the simplex boundaries
     // (there's some code duplication here but it doesn't
     // seem worth it to rationlise this as the interface would
     // be pretty clunky).
     for (unsigned e = 0; e < nel; e++)
     {
       Vector<Vector<double>> vertex_boundary_coord(3);
       // Loop over all nodes to find the lower left and upper right ones
       Node* lower_left_node_pt = face_el_pt[e]->node_pt(0);
       Node* upper_right_node_pt = face_el_pt[e]->node_pt(0);
       // Loop over all vertex nodes
       for (unsigned j = 0; j < 3; j++)
       {
         // Get node
         Node* nod_pt = face_el_pt[e]->node_pt(j);
         // Primary criterion for lower left: Does it have a lower z-coordinate?
         if (nod_pt->x(2) < lower_left_node_pt->x(2))
         {
           lower_left_node_pt = nod_pt;
         }
         // ...or is it a draw?
         else if (nod_pt->x(2) == lower_left_node_pt->x(2))
         {
           // If it's a draw: Does it have a lower y-coordinate?
           if (nod_pt->x(1) < lower_left_node_pt->x(1))
           {
             lower_left_node_pt = nod_pt;
           }
           // ...or is it a draw?
           else if (nod_pt->x(1) == lower_left_node_pt->x(1))
           {
             // If it's a draw: Does it have a lower x-coordinate?
             if (nod_pt->x(0) < lower_left_node_pt->x(0))
             {
               lower_left_node_pt = nod_pt;
             }
           }
         }
         // Primary criterion for upper right: Does it have a higher
         // z-coordinate?
         if (nod_pt->x(2) > upper_right_node_pt->x(2))
         {
           upper_right_node_pt = nod_pt;
         }
         // ...or is it a draw?
         else if (nod_pt->x(2) == upper_right_node_pt->x(2))
         {
           // If it's a draw: Does it have a higher y-coordinate?
           if (nod_pt->x(1) > upper_right_node_pt->x(1))
           {
             upper_right_node_pt = nod_pt;
           }
           // ...or is it a draw?
           else if (nod_pt->x(1) == upper_right_node_pt->x(1))
           {
             // If it's a draw: Does it have a higher x-coordinate?
             if (nod_pt->x(0) > upper_right_node_pt->x(0))
             {
               upper_right_node_pt = nod_pt;
             }
           }
         }
       }
       // Prepare storage for boundary coordinates
       Vector<double> zeta(2);
       // Unit vector connecting lower left and upper right nodes
       Vector<double> b0(3);
       b0[0] = upper_right_node_pt->x(0) - lower_left_node_pt->x(0);
       b0[1] = upper_right_node_pt->x(1) - lower_left_node_pt->x(1);
       b0[2] = upper_right_node_pt->x(2) - lower_left_node_pt->x(2);
       // Normalise
       double inv_length =
         1.0 / sqrt(b0[0] * b0[0] + b0[1] * b0[1] + b0[2] * b0[2]);
       b0[0] *= inv_length;
       b0[1] *= inv_length;
       b0[2] *= inv_length;
       // Get (outer) unit normal to face element -- note that
       // with the enumeration chosen in oomph-lib's xda to poly
       // conversion code the sign below is correct for the outer
       // unit normal on the FSI interface.
       Vector<double> tang1(3);
       Vector<double> tang2(3);
       Vector<double> normal(3);
       tang1[0] =
         face_el_pt[e]->node_pt(1)->x(0) - face_el_pt[e]->node_pt(0)->x(0);
       tang1[1] =
         face_el_pt[e]->node_pt(1)->x(1) - face_el_pt[e]->node_pt(0)->x(1);
       tang1[2] =
         face_el_pt[e]->node_pt(1)->x(2) - face_el_pt[e]->node_pt(0)->x(2);
       tang2[0] =
         face_el_pt[e]->node_pt(2)->x(0) - face_el_pt[e]->node_pt(0)->x(0);
       tang2[1] =
         face_el_pt[e]->node_pt(2)->x(1) - face_el_pt[e]->node_pt(0)->x(1);
       tang2[2] =
         face_el_pt[e]->node_pt(2)->x(2) - face_el_pt[e]->node_pt(0)->x(2);
       normal[0] = -(tang1[1] * tang2[2] - tang1[2] * tang2[1]);
       normal[1] = -(tang1[2] * tang2[0] - tang1[0] * tang2[2]);
       normal[2] = -(tang1[0] * tang2[1] - tang1[1] * tang2[0]);
       // Normalise
       inv_length = 1.0 / sqrt(normal[0] * normal[0] + normal[1] * normal[1] +
                               normal[2] * normal[2]);
       normal[0] *= inv_length;
       normal[1] *= inv_length;
       normal[2] *= inv_length;
       // Change direction -- usually for outer boundary of solid
       if (switch_normal)
       {
         normal[0] = -normal[0];
         normal[1] = -normal[1];
         normal[2] = -normal[2];
       }
       // Cross-product to get second in-plane vector, normal to b0
       Vector<double> b1(3);
       b1[0] = b0[1] * normal[2] - b0[2] * normal[1];
       b1[1] = b0[2] * normal[0] - b0[0] * normal[2];
       b1[2] = b0[0] * normal[1] - b0[1] * normal[0];
       // Assign boundary coordinates for vertex nodes: projection onto the axes
       for (unsigned j = 0; j < 3; j++)
       {
         // Get node
         Node* nod_pt = face_el_pt[e]->node_pt(j);
         // Difference vector to lower left corner
         Vector<double> delta(3);
         delta[0] = nod_pt->x(0) - lower_left_node_pt->x(0);
         delta[1] = nod_pt->x(1) - lower_left_node_pt->x(1);
         delta[2] = nod_pt->x(2) - lower_left_node_pt->x(2);
         // Project
         zeta[0] = delta[0] * b0[0] + delta[1] * b0[1] + delta[2] * b0[2];
         zeta[1] = delta[0] * b1[0] + delta[1] * b1[1] + delta[2] * b1[2];
         vertex_boundary_coord[j].resize(2);
         vertex_boundary_coord[j][0] = zeta[0];
         vertex_boundary_coord[j][1] = zeta[1];
 #ifdef PARANOID
         // Check:
         double error = pow(lower_left_node_pt->x(0) + zeta[0] * b0[0] +
                              zeta[1] * b1[0] - nod_pt->x(0),
                            2) +
                        pow(lower_left_node_pt->x(1) + zeta[0] * b0[1] +
                              zeta[1] * b1[1] - nod_pt->x(1),
                            2) +
                        pow(lower_left_node_pt->x(2) + zeta[0] * b0[2] +
                              zeta[1] * b1[2] - nod_pt->x(2),
                            2);
         if (sqrt(error) > Tolerance_for_boundary_finding)
         {
           std::ostringstream error_message;
           error_message
             << "Error in setup of boundary coordinate " << sqrt(error)
             << std::endl
             << "exceeds tolerance specified by the static member data\n"
             << "TetMeshBase::Tolerance_for_boundary_finding = "
             << Tolerance_for_boundary_finding << std::endl
             << "This usually means that the boundary is not planar.\n\n"
             << "You can suppress this error message by recompiling \n"
             << "recompiling without PARANOID or by changing the tolerance.\n";
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         // Set boundary coordinate
         nod_pt->set_coordinates_on_boundary(boundary_id[e], zeta);
       }
       // Assign boundary coordinates of three midside nodes by linear
       // interpolation (corresponding to a flat facet)
       // Node 3 is between 0 and 1
       zeta[0] =
         0.5 * (vertex_boundary_coord[0][0] + vertex_boundary_coord[1][0]);
       zeta[1] =
         0.5 * (vertex_boundary_coord[0][1] + vertex_boundary_coord[1][1]);
       face_el_pt[e]->node_pt(3)->set_coordinates_on_boundary(boundary_id[e],
                                                              zeta);
       // Node 4 is between 1 and 2
       zeta[0] =
         0.5 * (vertex_boundary_coord[1][0] + vertex_boundary_coord[2][0]);
       zeta[1] =
         0.5 * (vertex_boundary_coord[1][1] + vertex_boundary_coord[2][1]);
       face_el_pt[e]->node_pt(4)->set_coordinates_on_boundary(boundary_id[e],
                                                              zeta);
       // Node 5 is between 2 and 0
       zeta[0] =
         0.5 * (vertex_boundary_coord[2][0] + vertex_boundary_coord[0][0]);
       zeta[1] =
         0.5 * (vertex_boundary_coord[2][1] + vertex_boundary_coord[0][1]);
       face_el_pt[e]->node_pt(5)->set_coordinates_on_boundary(boundary_id[e],
                                                              zeta);
     }
     // Loop over elements/facets = boundaries to snap
     bool success = true;
     for (unsigned b = 0; b < nel; b++)
     {
       // Doc boundary coordinates on quadratic patches
       std::ofstream the_file;
       std::ofstream the_file_before;
       std::ofstream the_file_after;
       if (doc_info.is_doc_enabled())
       {
         std::ostringstream filename;
         filename << doc_info.directory() << "/quadratic_coordinates_"
                  << doc_info.label() << b << ".dat";
         the_file.open(filename.str().c_str());
         std::ostringstream filename1;
         filename1 << doc_info.directory() << "/quadratic_nodes_before_"
                   << doc_info.label() << b << ".dat";
         the_file_before.open(filename1.str().c_str());
         std::ostringstream filename2;
         filename2 << doc_info.directory() << "/quadratic_nodes_after_"
                   << doc_info.label() << b << ".dat";
         the_file_after.open(filename2.str().c_str());
       }
       // Cast the element pointer
       FreeStandingFaceElement<ELEMENT>* el_pt = face_el_pt[b];
       // Doc boundary coordinate on quadratic facet representation
       if (doc_info.is_doc_enabled())
       {
         Vector<double> s(2);
         Vector<double> zeta(2);
         Vector<double> x(3);
         unsigned n_plot = 3;
         the_file << el_pt->tecplot_zone_string(n_plot);
         // Loop over plot points
         unsigned num_plot_points = el_pt->nplot_points(n_plot);
         for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
         {
           // Get local coordinates of plot point
           el_pt->get_s_plot(iplot, n_plot, s);
           el_pt->interpolated_zeta(s, zeta);
           el_pt->interpolated_x(s, x);
           for (unsigned i = 0; i < 3; i++)
           {
             the_file << x[i] << " ";
           }
           for (unsigned i = 0; i < 2; i++)
           {
             the_file << zeta[i] << " ";
           }
           the_file << std::endl;
         }
         el_pt->write_tecplot_zone_footer(the_file, n_plot);
         //      std::cout << "Facet " << b << " corresponds to quadratic
         //      boundary "
         //                << boundary_id[b] << " which contains "
         //                << this->nboundary_element(boundary_id[b])
         //                << " element[s] " << std::endl;
       }
       // Loop over bulk elements that are adjacent to quadratic boundary
       Vector<double> boundary_zeta(2);
       Vector<double> quadratic_coordinates(3);
       GeomObject* geom_obj_pt = 0;
       Vector<double> s_geom_obj(2);
       unsigned nel = this->nboundary_element(boundary_id[b]);
       for (unsigned e = 0; e < nel; e++)
       {
         // Get pointer to the bulk element that is adjacent to boundary
         FiniteElement* bulk_elem_pt =
           this->boundary_element_pt(boundary_id[b], e);
         // Loop over nodes
         unsigned nnod = bulk_elem_pt->nnode();
         for (unsigned j = 0; j < nnod; j++)
         {
           Node* nod_pt = bulk_elem_pt->node_pt(j);
           if (nod_pt->is_on_boundary(boundary_id[b]))
           {
             nod_pt->get_coordinates_on_boundary(boundary_id[b], boundary_zeta);
             // Doc it?
             if (doc_info.is_doc_enabled())
             {
               the_file_before << nod_pt->x(0) << " " << nod_pt->x(1) << " "
                               << nod_pt->x(2) << " " << boundary_zeta[0] << " "
                               << boundary_zeta[1] << " " << std::endl;
             }
             // Find local coordinate in quadratic facet
             el_pt->locate_zeta(boundary_zeta, geom_obj_pt, s_geom_obj);
             if (geom_obj_pt != 0)
             {
               geom_obj_pt->position(s_geom_obj, quadratic_coordinates);
               nod_pt->x(0) = quadratic_coordinates[0];
               nod_pt->x(1) = quadratic_coordinates[1];
               nod_pt->x(2) = quadratic_coordinates[2];
             }
             else
             {
               // Get ready to bail out below...
               success = false;
               std::ostringstream error_message;
               error_message
                 << "Warning: Couldn't find GeomObject during snapping to\n"
                 << "quadratic surface for boundary " << boundary_id[b]
                 << ". I'm leaving the node where it was. Will bail out "
                    "later.\n";
               OomphLibWarning(error_message.str(),
                               "TetgenMesh::snap_to_quadratic_surface()",
                               OOMPH_EXCEPTION_LOCATION);
               if (!the_file_non_snapped.is_open())
               {
                 the_file_non_snapped.open(non_snapped_filename.c_str());
               }
               the_file_non_snapped << nod_pt->x(0) << " " << nod_pt->x(1) << " "
                                    << nod_pt->x(2) << " " << boundary_zeta[0]
                                    << " " << boundary_zeta[1] << " "
                                    << std::endl;
             }
             // Doc it?
             if (doc_info.is_doc_enabled())
             {
               the_file_after << nod_pt->x(0) << " " << nod_pt->x(1) << " "
                              << nod_pt->x(2) << " " << boundary_zeta[0] << " "
                              << boundary_zeta[1] << " " << std::endl;
             }
           }
         }
       }
       // Close doc file
       the_file.close();
       the_file_before.close();
       the_file_after.close();
     }
     // Bail out?
     if (!success)
     {
       std::ostringstream error_message;
       error_message
         << "Warning: Couldn't find GeomObject during snapping to\n"
         << "quadratic surface. Bailing out.\n"
         << "Nodes that couldn't be snapped are contained in \n"
         << "file: " << non_snapped_filename << ".\n"
         << "This problem may arise because the switch_normal flag was \n"
         << "set wrongly.\n";
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Close
     if (!the_file_non_snapped.is_open())
     {
       the_file_non_snapped.close();
     }
     // Kill auxiliary FreeStandingFaceElements
     for (unsigned e = 0; e < nel; e++)
     {
       delete face_el_pt[e];
       face_el_pt[e] = 0;
     }
     // Kill boundary nodes
     unsigned nn = nod_pt.size();
     for (unsigned j = 0; j < nn; j++)
     {
       delete nod_pt[j];
     }
   }
References b, oomph::Mesh::boundary_element_pt(), MultiOpt::delta, oomph::DocInfo::directory(), e(), calibrate::error, MergeRestartFiles::filename, oomph::Node::get_coordinates_on_boundary(), i, oomph::DocInfo::is_doc_enabled(), oomph::Node::is_on_boundary(), j, oomph::DocInfo::label(), oomph::Mesh::nboundary_element(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), WallFunction::normal(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::GeomObject::position(), Eigen::bfloat16_impl::pow(), s, oomph::Node::set_coordinates_on_boundary(), sqrt(), oomph::Global_string_for_annotation::string(), Tolerance_for_boundary_finding, plotDoE::x, oomph::Node::x(), and Eigen::zeta().
split_elements_in_corners()
template<class ELEMENT > void oomph::TetMeshBase::split_elements_in_corners (TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Non-Delaunay split elements that have three faces on a boundary into sons. Timestepper species timestepper for new nodes; defaults to to steady timestepper.
Non-delaunay split elements that have three faces on a boundary into sons.
   {
     // Setup boundary lookup scheme if required
     if (!Lookup_for_elements_next_boundary_is_setup)
     {
       setup_boundary_element_info();
     }
     // Find out how many nodes we have along each element edge
     unsigned nnode_1d = finite_element_pt(0)->nnode_1d();
     // Find out the total number of nodes
     unsigned nnode = this->finite_element_pt(0)->nnode();
     // At the moment we're only able to deal with nnode_1d=2 or 3.
     if ((nnode_1d != 2) && (nnode_1d != 3))
     {
       std::ostringstream error_message;
       error_message << "Mesh generation from tetgen currently only works\n";
       error_message << "for nnode_1d = 2 or 3. You're trying to use it\n";
       error_message << "for nnode_1d=" << nnode_1d << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Map to store how many boundaries elements are located on
     std::map<FiniteElement*, unsigned> count;
     // Loop over all boundaries
     unsigned nb = this->nboundary();
     for (unsigned b = 0; b < nb; b++)
     {
       // Loop over elements next to that boundary
       unsigned nel = this->nboundary_element(b);
       for (unsigned e = 0; e < nel; e++)
       {
         // Get pointer to element
         FiniteElement* el_pt = boundary_element_pt(b, e);
         // Bump up counter
         count[el_pt]++;
       }
     }
     // To avoid having to check the map for all elements (which will
     // inflate it to the size of all elements!), move offending elements
     // into set
     std::set<FiniteElement*> elements_to_be_split;
     for (std::map<FiniteElement*, unsigned>::iterator it = count.begin();
          it != count.end();
          it++)
     {
       // Get pointer to element: Key
       FiniteElement* el_pt = it->first;
       // Does it have to be split?
       if (it->second > 2)
       {
         elements_to_be_split.insert(el_pt);
       }
     }
     // Vector for retained or newly built elements
     unsigned nel = this->nelement();
     Vector<FiniteElement*> new_or_retained_el_pt;
     new_or_retained_el_pt.reserve(nel);
     // Map which returns the 4 newly created elements for each old corner
     // element
     std::map<FiniteElement*, Vector<FiniteElement*>>
       old_to_new_corner_element_map;
     // Now loop over all elements
     for (unsigned e = 0; e < nel; e++)
     {
       // Get pointer to element
       FiniteElement* el_pt = this->finite_element_pt(e);
       // Does it have to be split? I.e. is it in the set?
       std::set<FiniteElement*>::iterator it = std::find(
         elements_to_be_split.begin(), elements_to_be_split.end(), el_pt);
       // It's not in the set, so iterator has reached end
       if (it == elements_to_be_split.end())
       {
         // Carry it across
         new_or_retained_el_pt.push_back(el_pt);
       }
       // It's in the set of elements to be split
       else
       {
         // Storage for new nodes -- Note: All new nodes are interior and
         // therefore cannot be boundary nodes!
         Node* node0_pt = 0;
         Node* node1_pt = 0;
         Node* node2_pt = 0;
         Node* node3_pt = 0;
         Node* node4_pt = 0;
         Node* node5_pt = 0;
         Node* node6_pt = 0;
         Node* node7_pt = 0;
         Node* node8_pt = 0;
         Node* node9_pt = 0;
         Node* node10_pt = 0;
         // Create first new element
         FiniteElement* el1_pt = new ELEMENT;
         // Copy existing nodes
         el1_pt->node_pt(0) = el_pt->node_pt(0);
         el1_pt->node_pt(1) = el_pt->node_pt(1);
         el1_pt->node_pt(3) = el_pt->node_pt(3);
         if (nnode_1d == 3)
         {
           el1_pt->node_pt(4) = el_pt->node_pt(4);
           el1_pt->node_pt(6) = el_pt->node_pt(6);
           el1_pt->node_pt(9) = el_pt->node_pt(9);
         }
         // Create new nodes
         // If we have an enriched element then don't need to construct centroid
         // node
         if (nnode == 15)
         {
           node0_pt = el_pt->node_pt(14);
           el1_pt->node_pt(2) = node0_pt;
           node5_pt = el1_pt->construct_node(11, time_stepper_pt);
           node6_pt = el1_pt->construct_node(13, time_stepper_pt);
           node9_pt = el1_pt->construct_node(12, time_stepper_pt);
           // Copy others over
           el1_pt->node_pt(10) = el_pt->node_pt(10);
         }
         // If not enriched we do
         else
         {
           node0_pt = el1_pt->construct_node(2, time_stepper_pt);
         }
         if (nnode_1d == 3)
         {
           node1_pt = el1_pt->construct_boundary_node(5, time_stepper_pt);
           node2_pt = el1_pt->construct_boundary_node(7, time_stepper_pt);
           node4_pt = el1_pt->construct_boundary_node(8, time_stepper_pt);
         }
         // Create second new element
         FiniteElement* el2_pt = new ELEMENT;
         // Copy existing nodes
         el2_pt->node_pt(0) = el_pt->node_pt(0);
         el2_pt->node_pt(1) = el_pt->node_pt(1);
         el2_pt->node_pt(2) = el_pt->node_pt(2);
         if (nnode_1d == 3)
         {
           el2_pt->node_pt(4) = el_pt->node_pt(4);
           el2_pt->node_pt(5) = el_pt->node_pt(5);
           el2_pt->node_pt(7) = el_pt->node_pt(7);
         }
         // Create new node
         if (nnode_1d == 3)
         {
           node3_pt = el2_pt->construct_boundary_node(8, time_stepper_pt);
         }
         // Copy existing new nodes
         el2_pt->node_pt(3) = node0_pt;
         if (nnode_1d == 3)
         {
           el2_pt->node_pt(6) = node1_pt;
           el2_pt->node_pt(9) = node2_pt;
         }
         // Copy and constuct other nodes for enriched elements
         if (nnode == 15)
         {
           el2_pt->node_pt(10) = node5_pt;
           el2_pt->node_pt(11) = el_pt->node_pt(11);
           node8_pt = el2_pt->construct_node(12, time_stepper_pt);
           node10_pt = el2_pt->construct_node(13, time_stepper_pt);
         }
         // Create third new element
         FiniteElement* el3_pt = new ELEMENT;
         // Copy existing nodes
         el3_pt->node_pt(1) = el_pt->node_pt(1);
         el3_pt->node_pt(2) = el_pt->node_pt(2);
         el3_pt->node_pt(3) = el_pt->node_pt(3);
         if (nnode_1d == 3)
         {
           el3_pt->node_pt(7) = el_pt->node_pt(7);
           el3_pt->node_pt(8) = el_pt->node_pt(8);
           el3_pt->node_pt(9) = el_pt->node_pt(9);
         }
         // Copy existing new nodes
         el3_pt->node_pt(0) = node0_pt;
         if (nnode_1d == 3)
         {
           el3_pt->node_pt(4) = node2_pt;
           el3_pt->node_pt(5) = node3_pt;
           el3_pt->node_pt(6) = node4_pt;
         }
         // Copy and constuct other nodes for enriched elements
         if (nnode == 15)
         {
           el3_pt->node_pt(10) = node6_pt;
           el3_pt->node_pt(11) = node10_pt;
           node7_pt = el3_pt->construct_node(12, time_stepper_pt);
           el3_pt->node_pt(13) = el_pt->node_pt(13);
         }
         // Create fourth new element
         FiniteElement* el4_pt = new ELEMENT;
         // Copy existing nodes
         el4_pt->node_pt(0) = el_pt->node_pt(0);
         el4_pt->node_pt(2) = el_pt->node_pt(2);
         el4_pt->node_pt(3) = el_pt->node_pt(3);
         if (nnode_1d == 3)
         {
           el4_pt->node_pt(5) = el_pt->node_pt(5);
           el4_pt->node_pt(6) = el_pt->node_pt(6);
           el4_pt->node_pt(8) = el_pt->node_pt(8);
         }
         // Copy existing new nodes
         el4_pt->node_pt(1) = node0_pt;
         if (nnode_1d == 3)
         {
           el4_pt->node_pt(4) = node1_pt;
           el4_pt->node_pt(7) = node3_pt;
           el4_pt->node_pt(9) = node4_pt;
         }
         // Copy all other nodes
         if (nnode == 15)
         {
           el4_pt->node_pt(10) = node9_pt;
           el4_pt->node_pt(11) = node8_pt;
           el4_pt->node_pt(12) = el_pt->node_pt(12);
           el4_pt->node_pt(13) = node7_pt;
           ;
         }
         // Add new elements and nodes
         new_or_retained_el_pt.push_back(el1_pt);
         new_or_retained_el_pt.push_back(el2_pt);
         new_or_retained_el_pt.push_back(el3_pt);
         new_or_retained_el_pt.push_back(el4_pt);
         // create a vector of the newly created elements
         Vector<FiniteElement*> temp_vec(4);
         temp_vec[0] = el1_pt;
         temp_vec[1] = el2_pt;
         temp_vec[2] = el3_pt;
         temp_vec[3] = el4_pt;
         // add the vector to the map
         old_to_new_corner_element_map.insert(
           std::pair<FiniteElement*, Vector<FiniteElement*>>(el_pt, temp_vec));
         if (nnode != 15)
         {
           this->add_node_pt(node0_pt);
         }
         this->add_node_pt(node1_pt);
         this->add_node_pt(node2_pt);
         this->add_node_pt(node3_pt);
         this->add_node_pt(node4_pt);
         if (nnode == 15)
         {
           this->add_node_pt(node5_pt);
           this->add_node_pt(node6_pt);
           this->add_node_pt(node7_pt);
           this->add_node_pt(node8_pt);
           this->add_node_pt(node9_pt);
         }
         // Set nodal positions
         for (unsigned i = 0; i < 3; i++)
         {
           // Only bother to set centroid if does not already exist
           if (nnode != 15)
           {
             node0_pt->x(i) =
               0.25 * (el_pt->node_pt(0)->x(i) + el_pt->node_pt(1)->x(i) +
                       el_pt->node_pt(2)->x(i) + el_pt->node_pt(3)->x(i));
           }
           if (nnode_1d == 3)
           {
             node1_pt->x(i) = 0.5 * (el_pt->node_pt(0)->x(i) + node0_pt->x(i));
             node2_pt->x(i) = 0.5 * (el_pt->node_pt(1)->x(i) + node0_pt->x(i));
             node3_pt->x(i) = 0.5 * (el_pt->node_pt(2)->x(i) + node0_pt->x(i));
             node4_pt->x(i) = 0.5 * (el_pt->node_pt(3)->x(i) + node0_pt->x(i));
           }
         }
         // Construct the four interior nodes if needed
         // and add to the list
         if (nnode == 15)
         {
           // Set the positions of the newly created mid-face nodes
           // New Node 5 lies in the plane between original nodes 0 1 centroid
           for (unsigned i = 0; i < 3; ++i)
           {
             node5_pt->x(i) =
               (el_pt->node_pt(0)->x(i) + el_pt->node_pt(1)->x(i) +
                el_pt->node_pt(14)->x(i)) /
               3.0;
           }
           // New Node 6 lies in the plane between original nodes 1 3 centroid
           for (unsigned i = 0; i < 3; ++i)
           {
             node6_pt->x(i) =
               (el_pt->node_pt(1)->x(i) + el_pt->node_pt(3)->x(i) +
                el_pt->node_pt(14)->x(i)) /
               3.0;
           }
           // New Node 7 lies in the plane between original nodes 2 3 centroid
           for (unsigned i = 0; i < 3; ++i)
           {
             node7_pt->x(i) =
               (el_pt->node_pt(2)->x(i) + el_pt->node_pt(3)->x(i) +
                el_pt->node_pt(14)->x(i)) /
               3.0;
           }
           // New Node 8 lies in the plane between original nodes 0 2 centroid
           for (unsigned i = 0; i < 3; ++i)
           {
             node8_pt->x(i) =
               (el_pt->node_pt(0)->x(i) + el_pt->node_pt(2)->x(i) +
                el_pt->node_pt(14)->x(i)) /
               3.0;
           }
           // New Node 9 lies in the plane between original nodes 0 3 centroid
           for (unsigned i = 0; i < 3; ++i)
           {
             node9_pt->x(i) =
               (el_pt->node_pt(0)->x(i) + el_pt->node_pt(3)->x(i) +
                el_pt->node_pt(14)->x(i)) /
               3.0;
           }
           // New Node 10 lies in the plane between original nodes 1 2 centroid
           for (unsigned i = 0; i < 3; ++i)
           {
             node10_pt->x(i) =
               (el_pt->node_pt(1)->x(i) + el_pt->node_pt(2)->x(i) +
                el_pt->node_pt(14)->x(i)) /
               3.0;
           }
           // Now create the new centroid nodes
           // First element
           Node* temp_nod_pt = el1_pt->construct_node(14, time_stepper_pt);
           for (unsigned i = 0; i < 3; ++i)
           {
             double av_pos = 0.0;
             for (unsigned j = 0; j < 4; j++)
             {
               av_pos += el1_pt->node_pt(j)->x(i);
             }
             temp_nod_pt->x(i) = 0.25 * av_pos;
           }
           this->add_node_pt(temp_nod_pt);
           // Second element
           temp_nod_pt = el2_pt->construct_node(14, time_stepper_pt);
           for (unsigned i = 0; i < 3; ++i)
           {
             double av_pos = 0.0;
             for (unsigned j = 0; j < 4; j++)
             {
               av_pos += el2_pt->node_pt(j)->x(i);
             }
             temp_nod_pt->x(i) = 0.25 * av_pos;
           }
           this->add_node_pt(temp_nod_pt);
           // Third element
           temp_nod_pt = el3_pt->construct_node(14, time_stepper_pt);
           for (unsigned i = 0; i < 3; ++i)
           {
             double av_pos = 0.0;
             for (unsigned j = 0; j < 4; j++)
             {
               av_pos += el3_pt->node_pt(j)->x(i);
             }
             temp_nod_pt->x(i) = 0.25 * av_pos;
           }
           this->add_node_pt(temp_nod_pt);
           // Fourth element
           temp_nod_pt = el4_pt->construct_node(14, time_stepper_pt);
           for (unsigned i = 0; i < 3; ++i)
           {
             double av_pos = 0.0;
             for (unsigned j = 0; j < 4; j++)
             {
               av_pos += el4_pt->node_pt(j)->x(i);
             }
             temp_nod_pt->x(i) = 0.25 * av_pos;
           }
           this->add_node_pt(temp_nod_pt);
         }
         // Kill the old element
         delete el_pt;
       }
     }
     // Flush element storage
     Element_pt.clear();
     // Copy across
     nel = new_or_retained_el_pt.size();
     Element_pt.resize(nel);
     for (unsigned e = 0; e < nel; e++)
     {
       Element_pt[e] = new_or_retained_el_pt[e];
     }
     // Setup boundary lookup scheme again
     setup_boundary_element_info();
     // -------------------------------------------------------------------------
     // The various boundary/region lookups now need updating to account for the
     // newly added/removed elements. This will be done in two stages:
     // Step 1: Add the new elements to the vector of elements in the same region
     //         as the original corner element, and then delete the originals.
     //         Updating this lookup makes things easier in the following step.
     // Step 2: Regenerate the two more specific lookups: One which gives the
     //         elements on a given boundary in a given region, and the other
     //         which maps elements on a given boundary in a given region to the
     //         element's face index on that boundary.
     //
     // N.B. the lookup Triangular_facet_vertex_boundary_coordinate is setup in
     // the call to setup_boundary_element_info() above so doesn't need
     // additional work.
     // if we have no regions then we have no lookups to update so we're done
     // here
     if (Region_attribute.size() == 0)
     {
       return;
     }
     // if we haven't had to split any corner elements then don't need to fiddle
     // with the lookups
     if (old_to_new_corner_element_map.size() == 0)
     {
       oomph_info << "\nNo corner elements need splitting\n\n";
       return;
     }
     // ------------------------------------------
     // Step 1: update the region element lookup
     // loop over the map of old corner elements which have been split
     for (std::map<FiniteElement*, Vector<FiniteElement*>>::iterator map_it =
            old_to_new_corner_element_map.begin();
          map_it != old_to_new_corner_element_map.end();
          map_it++)
     {
       // extract the old and new elements from the map
       FiniteElement* original_el_pt = map_it->first;
       Vector<FiniteElement*> new_el_pt = map_it->second;
       unsigned original_region_index = 0;
 #ifdef PARANOID
       // flag for paranoia, if for some reason we don't find the original corner
       // element in any of the regions
       bool found = false;
 #endif
       Vector<FiniteElement*>::iterator region_element_it;
       // loop over the regions and look for this original corner element to find
       // out which region it used to be in, so we can add the new elements to
       // the same region.
       for (unsigned region_index = 0; region_index < Region_element_pt.size();
            region_index++)
       {
         // for each region, search the vector of elements in this region for the
         // original corner element
         region_element_it = std::find(Region_element_pt[region_index].begin(),
                                       Region_element_pt[region_index].end(),
                                       original_el_pt);
         // if the iterator hasn't reached the end then we've found it
         if (region_element_it != Region_element_pt[region_index].end())
         {
           // save the region index we're at
           original_region_index = region_index;
 #ifdef PARANOID
           // update the paranoid flag
           found = true;
 #endif
           // regions can't overlap, so once we've found one we're done
           break;
         }
       }
 #ifdef PARANOID
       if (!found)
       {
         std::ostringstream error_message;
         error_message
           << "The corner element being split does not appear to be in any "
           << "region, so something has gone wrong with the region lookup "
              "scheme\n";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Now update the basic region lookup. The iterator will still point to
       // the original corner element in the lookup, so we can delete this easily
       Region_element_pt[original_region_index].erase(region_element_it);
       for (unsigned i = 0; i < 4; i++)
       {
         Region_element_pt[original_region_index].push_back(new_el_pt[i]);
       }
     }
     // ------------------------------------------
     // Step 2: Clear and regenerate lookups
     Face_index_region_at_boundary.clear();
     Boundary_region_element_pt.clear();
     Face_index_region_at_boundary.resize(nboundary());
     Boundary_region_element_pt.resize(nboundary());
     for (unsigned b = 0; b < nboundary(); b++)
     {
       // Loop over elements next to that boundary
       unsigned nel = this->nboundary_element(b);
       for (unsigned e = 0; e < nel; e++)
       {
         FiniteElement* el_pt = boundary_element_pt(b, e);
         // now search for it in each region
         for (unsigned r_index = 0; r_index < Region_attribute.size(); r_index++)
         {
           unsigned region_id = static_cast<unsigned>(Region_attribute[r_index]);
           Vector<FiniteElement*>::iterator it =
             std::find(Region_element_pt[r_index].begin(),
                       Region_element_pt[r_index].end(),
                       el_pt);
           // if we find this element in the current region, then update our
           // lookups
           if (it != Region_element_pt[r_index].end())
           {
             Boundary_region_element_pt[b][region_id].push_back(el_pt);
             unsigned face_index = face_index_at_boundary(b, e);
             Face_index_region_at_boundary[b][region_id].push_back(face_index);
           }
         }
       }
     }
     oomph_info << "\nNumber of outer corner elements split: "
                << old_to_new_corner_element_map.size() << "\n\n";
   } // end split_elements_in_corners()
References oomph::Mesh::add_node_pt(), b, oomph::Mesh::boundary_element_pt(), Boundary_region_element_pt, oomph::FiniteElement::construct_boundary_node(), oomph::FiniteElement::construct_node(), e(), oomph::Mesh::Element_pt, Eigen::placeholders::end, oomph::Mesh::face_index_at_boundary(), Face_index_region_at_boundary, oomph::Mesh::finite_element_pt(), MergeRestartFiles::found, i, j, oomph::Mesh::Lookup_for_elements_next_boundary_is_setup, nb, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::Mesh::nelement(), oomph::FiniteElement::nnode(), oomph::Mesh::nnode(), oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::node_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, Region_attribute, Region_element_pt, setup_boundary_element_info(), and oomph::Node::x().
Member Data Documentation
Boundary_region_element_pt
Vector<std::map<unsigned, Vector<FiniteElement*> > > oomph::TetMeshBase::Boundary_region_element_pt protected
Storage for elements adjacent to a boundary in a particular region.
Referenced by boundary_element_in_region_pt(), oomph::GmshTetMesh< ELEMENT >::build_from_scaffold(), nboundary_element_in_region(), and split_elements_in_corners().
Face_index_region_at_boundary
Vector<std::map<unsigned, Vector<int> > > oomph::TetMeshBase::Face_index_region_at_boundary protected
Storage for the face index adjacent to a boundary in a particular region
Referenced by oomph::GmshTetMesh< ELEMENT >::build_from_scaffold(), face_index_at_boundary_in_region(), and split_elements_in_corners().
Internal_surface_pt
Vector<TetMeshFacetedSurface*> oomph::TetMeshBase::Internal_surface_pt protected
Vector to faceted surfaces that define internal boundaries.
Referenced by oomph::GmshTetMesh< ELEMENT >::build_it(), oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh(), and oomph::TetgenMesh< ELEMENT >::TetgenMesh().
Outer_boundary_pt
TetMeshFacetedClosedSurface* oomph::TetMeshBase::Outer_boundary_pt protected
Faceted surface that defines outer boundaries.
Referenced by oomph::GmshTetMesh< ELEMENT >::build_it(), oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh(), and oomph::TetgenMesh< ELEMENT >::TetgenMesh().
Region_attribute
Vector<double> oomph::TetMeshBase::Region_attribute protected
Vector of attributes associated with the elements in each region NOTE: double is enforced on us by tetgen. We use it as an unsigned to indicate the actual (zero-based) region ID
Referenced by oomph::GmshTetMesh< ELEMENT >::build_from_scaffold(), oomph::GmshTetScaffoldMesh::create_mesh_from_msh_file(), nregion_element(), region_attribute(), region_element_pt(), and split_elements_in_corners().
Region_element_pt
Vector<Vector<FiniteElement*> > oomph::TetMeshBase::Region_element_pt protected
Vectors of vectors of elements in each region (note: this just stores them; the region IDs are contained in Region_attribute!)
Referenced by oomph::GmshTetMesh< ELEMENT >::build_from_scaffold(), oomph::GmshTetScaffoldMesh::create_mesh_from_msh_file(), nregion(), nregion_element(), region_element_pt(), and split_elements_in_corners().
Tet_mesh_facet_pt
std::map<unsigned, TetMeshFacet*> oomph::TetMeshBase::Tet_mesh_facet_pt protected
Reverse lookup scheme: Pointer to facet (if any!) associated with boundary b
Referenced by oomph::GmshTetMesh< ELEMENT >::build_it(), and setup_boundary_coordinates().
Tet_mesh_faceted_surface_pt
std::map<unsigned, TetMeshFacetedSurface*> oomph::TetMeshBase::Tet_mesh_faceted_surface_pt protected
Reverse lookup scheme: Pointer to faceted surface (if any!) associated with boundary b
Referenced by oomph::GmshTetMesh< ELEMENT >::build_it(), and snap_nodes_onto_geometric_objects().
Time_stepper_pt
TimeStepper* oomph::TetMeshBase::Time_stepper_pt protected
Timestepper used to build nodes.
Referenced by oomph::GmshTetMesh< ELEMENT >::build_it(), oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh(), oomph::TetgenMesh< ELEMENT >::set_mesh_level_time_stepper(), and oomph::TetgenMesh< ELEMENT >::TetgenMesh().
Tolerance_for_boundary_finding
double oomph::TetMeshBase::Tolerance_for_boundary_finding = 1.0e-5 static
Global static data that specifies the permitted error in the setup of the boundary coordinates
Referenced by setup_boundary_coordinates(), and snap_to_quadratic_surface().
Triangular_facet_vertex_boundary_coordinate
std::map<unsigned, Vector<Vector<double> > > oomph::TetMeshBase::Triangular_facet_vertex_boundary_coordinate protected
Boundary coordinates of vertices in triangular facets associated with given boundary. Is only set up for triangular facets!
Referenced by setup_boundary_coordinates(), and snap_nodes_onto_geometric_objects().
The documentation for this class was generated from the following files:
tet_mesh.h
tet_mesh.cc