MercuryDPM: Eigen::internal::generic_k1e< T, double > Struct Template Reference
Eigen::internal::generic_k1e< T, double > Struct Template Reference
#include <BesselFunctionsImpl.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T run (const T &x)
Member Function Documentation
run()
template<typename T > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T Eigen::internal::generic_k1e< T, double >::run (const T & x) inline static
{
     /*  k1e.c
      *
      *  Modified Bessel function, third kind, order one,
      *  exponentially scaled
      *
      *
      *
      * SYNOPSIS:
      *
      * double x, y, k1e();
      *
      * y = k1e( x );
      *
      *
      *
      * DESCRIPTION:
      *
      * Returns exponentially scaled modified Bessel function
      * of the third kind of order one of the argument:
      *
      *      k1e(x) = exp(x) * k1(x).
      *
      *
      *
      * ACCURACY:
      *
      *                      Relative error:
      * arithmetic   domain     # trials      peak         rms
      *    IEEE      0, 30       30000       7.8e-16     1.2e-16
      * See k1().
      *
      */
     const double A[] = {-7.02386347938628759343E-18, -2.42744985051936593393E-15, -6.66690169419932900609E-13,
                         -1.41148839263352776110E-10, -2.21338763073472585583E-8,  -2.43340614156596823496E-6,
                         -1.73028895751305206302E-4,  -6.97572385963986435018E-3,  -1.22611180822657148235E-1,
                         -3.53155960776544875667E-1,  1.52530022733894777053E0};
     const double B[] = {-5.75674448366501715755E-18, 1.79405087314755922667E-17,  -5.68946255844285935196E-17,
                         1.83809354436663880070E-16,  -6.05704724837331885336E-16, 2.03870316562433424052E-15,
                         -7.01983709041831346144E-15, 2.47715442448130437068E-14,  -8.97670518232499435011E-14,
                         3.34841966607842919884E-13,  -1.28917396095102890680E-12, 5.13963967348173025100E-12,
                         -2.12996783842756842877E-11, 9.21831518760500529508E-11,  -4.19035475934189648750E-10,
                         2.01504975519703286596E-9,   -1.03457624656780970260E-8,  5.74108412545004946722E-8,
                         -3.50196060308781257119E-7,  2.40648494783721712015E-6,   -1.93619797416608296024E-5,
                         1.95215518471351631108E-4,   -2.85781685962277938680E-3,  1.03923736576817238437E-1,
                         2.72062619048444266945E0};
     const T MAXNUM = pset1<T>(NumTraits<double>::infinity());
     const T two = pset1<T>(2.0);
     T x_le_two = pdiv(internal::pchebevl<T, 11>::run(pmadd(x, x, pset1<T>(-2.0)), A), x);
     x_le_two = pmadd(generic_i1<T, double>::run(x), plog(pmul(pset1<T>(0.5), x)), x_le_two);
     x_le_two = pmul(x_le_two, pexp(x));
     x_le_two = pselect(pcmp_le(x, pset1<T>(0.0)), MAXNUM, x_le_two);
     T x_gt_two = pmul(internal::pchebevl<T, 25>::run(psub(pdiv(pset1<T>(8.0), x), two), B), prsqrt(x));
     return pselect(pcmp_le(x, two), x_le_two, x_gt_two);
   }
References Eigen::internal::pcmp_le(), Eigen::internal::pdiv(), Eigen::internal::pexp(), Eigen::internal::plog(), Eigen::internal::pmadd(), Eigen::internal::pmul(), Eigen::internal::prsqrt(), Eigen::internal::pselect(), Eigen::internal::psub(), and plotDoE::x.
The documentation for this struct was generated from the following file:
BesselFunctionsImpl.h