MercuryDPM: Chute Class Reference
Chute Class Reference
Creates chutes with different bottoms. Inherits from Mercury3D (-> MercuryBase -> DPMBase).
#include <Chute.h>
Public Member Functions
Chute ()
This is the default constructor. All it does is set sensible defaults.
Chute (const DPMBase &other)
Copy constructor, converts an existing DPMBase problem into a Chute problem.
Chute (const MercuryBase &other)
Copy constructor, converts an existing MercuryBase problem into a Chute problem.
Chute (const Mercury3D &other)
Copy constructor, converts an existing Mercury3D problem into a Chute problem.
Chute (const Chute &other)
Default copy constructor.
void constructor ()
This is the actual constructor METHOD; it is called by all constructors above (except the default copy constructor).
bool readNextArgument (int &i, int argc, char *argv[]) override
This method can be used for reading object properties from a string.
void setupSideWalls ()
Creates chute side walls (either solid or periodic)
void makeChutePeriodic ()
This makes the chute periodic in Y.
bool getIsPeriodic () const
Returns whether the chute is periodic in Y.
void setupInitialConditions () override
Creates bottom, side walls and a particle insertion boundary.
void read (std::istream &is, ReadOptions opt=ReadOptions::ReadAll) override
Reads all chute properties from an istream.
void write (std::ostream &os, bool writeAllParticles=true) const override
This function writes the Chute properties to an ostream, and adds the properties of ALL chute particles as well.
void setFixedParticleRadius (Mdouble fixedParticleRadius)
Sets the particle radius of the fixed particles which constitute the (rough) chute bottom.
Mdouble getFixedParticleRadius () const
Returns the particle radius of the fixed particles which constitute the (rough) chute bottom.
void setFixedParticleSpacing (Mdouble fixedParticleSpacing)
Sets the spacing of the fixed particles which constitute the (rough) chute bottom; used in triangular packing only.
Mdouble getFixedParticleSpacing () const
Returns the particle radius of the fixed particles which constitute the (rough) chute bottom; used in triangular packing only.
void setRoughBottomType (RoughBottomType roughBottomType)
Sets the type of rough bottom of the chute.
void setRoughBottomType (std::string roughBottomTypeString)
Sets the type of rough bottom of the chute, using a string with the EXACT enum type as input.
RoughBottomType getRoughBottomType () const
Returns the type of (rough) bottom of the chute.
void setChuteAngle (Mdouble chuteAngle)
Sets gravity vector according to chute angle (in degrees)
void setChuteAngleAndMagnitudeOfGravity (Mdouble chuteAngle, Mdouble gravity)
Sets gravity vector according to chute angle (in degrees)
Mdouble getChuteAngle () const
Returns the chute angle (in radians)
Mdouble getChuteAngleDegrees () const
Returns the chute angle (in degrees)
void setMaxFailed (unsigned int maxFailed)
Sets the number of times a particle will be tried to be added to the insertion boundary.
unsigned int getMaxFailed () const
Returns the number of times a particle will be tried to be added to the insertion boundary.
void setInflowParticleRadius (Mdouble inflowParticleRadius)
Sets the radius of the inflow particles to a single one (i.e. ensures a monodisperse inflow).
void setInflowParticleRadius (Mdouble minInflowParticleRadius, Mdouble maxInflowParticleRadius)
Sets the minimum and maximum radius of the inflow particles.
void setMinInflowParticleRadius (Mdouble minInflowParticleRadius)
sets the minimum radius of inflow particles
void setMaxInflowParticleRadius (Mdouble maxInflowParticleRadius)
Sets the maximum radius of inflow particles.
Mdouble getInflowParticleRadius () const
Returns the average radius of inflow particles.
Mdouble getMinInflowParticleRadius () const
returns the minimum radius of inflow particles
Mdouble getMaxInflowParticleRadius () const
Returns the maximum radius of inflow particles.
void setInflowHeight (Mdouble inflowHeight)
Sets maximum inflow height (Z-direction)
Mdouble getInflowHeight () const
Returns the maximum inflow height (Z-direction)
void setInflowVelocity (Mdouble inflowVelocity)
Sets the average inflow velocity.
Mdouble getInflowVelocity () const
Returns the average inflow velocity.
void setInflowVelocityVariance (Mdouble inflowVelocityVariance)
Sets the inflow velocity variance.
Mdouble getInflowVelocityVariance () const
Returns the inflow velocity variance.
void setChuteWidth (Mdouble chuteWidth)
Sets the chute width (Y-direction)
Mdouble getChuteWidth () const
Returns the chute width (Y-direction)
virtual void setChuteLength (Mdouble chuteLength)
Sets the chute length (X-direction)
Mdouble getChuteLength () const
Returns the chute length (X-direction)
void setInsertionBoundary (InsertionBoundary *insertionBoundary)
Sets the chute insertion boundary.
Public Member Functions inherited from Mercury3D
Mercury3D ()
This is the default constructor. All it does is set sensible defaults.
Mercury3D (const DPMBase &other)
Copy-constructor for creates an Mercury3D problem from an existing MD problem.
Mercury3D (const Mercury3D &other)
Copy-constructor.
void constructor ()
Function that sets the SystemDimension and ParticleDimension to 3.
std::vector< BaseParticle * > hGridFindParticleContacts (const BaseParticle *obj) override
Returns all particles that have a contact with a given particle.
Public Member Functions inherited from MercuryBase
MercuryBase ()
This is the default constructor. It sets sensible defaults.
~MercuryBase () override
This is the default destructor.
MercuryBase (const MercuryBase &mercuryBase)
Copy-constructor.
void constructor ()
This is the actual constructor, it is called do both constructors above.
void hGridActionsBeforeTimeLoop () override
This sets up the broad phase information, has to be done at this stage because it requires the particle size.
void hGridActionsBeforeTimeStep () override
Performs all necessary actions before a time-step, like updating the particles and resetting all the bucket information, etc.
void read (std::istream &is, ReadOptions opt=ReadOptions::ReadAll) override
Reads the MercuryBase from an input stream, for example a restart file.
void write (std::ostream &os, bool writeAllParticles=true) const override
Writes all data into a restart file.
Mdouble getHGridCurrentMaxRelativeDisplacement () const
Returns hGridCurrentMaxRelativeDisplacement_.
Mdouble getHGridTotalCurrentMaxRelativeDisplacement () const
Returns hGridTotalCurrentMaxRelativeDisplacement_.
void setHGridUpdateEachTimeStep (bool updateEachTimeStep)
Sets whether or not the HGrid must be updated every time step.
bool getHGridUpdateEachTimeStep () const final
Gets whether or not the HGrid is updated every time step.
void setHGridMaxLevels (unsigned int HGridMaxLevels)
Sets the maximum number of levels of the HGrid in this MercuryBase.
unsigned int getHGridMaxLevels () const
Gets the maximum number of levels of the HGrid in this MercuryBase.
HGridMethod getHGridMethod () const
Gets whether the HGrid in this MercuryBase is BOTTOMUP or TOPDOWN.
void setHGridMethod (HGridMethod hGridMethod)
Sets the HGridMethod to either BOTTOMUP or TOPDOWN.
HGridDistribution getHGridDistribution () const
Gets how the sizes of the cells of different levels are distributed.
void setHGridDistribution (HGridDistribution hGridDistribution)
Sets how the sizes of the cells of different levels are distributed.
Mdouble getHGridCellOverSizeRatio () const
Gets the ratio of the smallest cell over the smallest particle.
void setHGridCellOverSizeRatio (Mdouble cellOverSizeRatio)
Sets the ratio of the smallest cell over the smallest particle.
bool hGridNeedsRebuilding ()
Gets if the HGrid needs rebuilding before anything else happens.
virtual unsigned int getHGridTargetNumberOfBuckets () const
Gets the desired number of buckets, which is the maximum of the number of particles and 10.
virtual Mdouble getHGridTargetMinInteractionRadius () const
Gets the desired size of the smallest cells of the HGrid.
virtual Mdouble getHGridTargetMaxInteractionRadius () const
Gets the desired size of the largest cells of the HGrid.
bool checkParticleForInteraction (const BaseParticle &P) final
Checks if given BaseParticle has an interaction with a BaseWall or other BaseParticle.
bool checkParticleForInteractionLocal (const BaseParticle &P) final
Checks if the given BaseParticle has an interaction with a BaseWall or other BaseParticles in a local domain.
virtual Mdouble userHGridCellSize (unsigned int level)
Virtual function that enables inheriting classes to implement a function to let the user set the cell size of the HGrid.
void hGridInfo (std::ostream &os=std::cout) const
Writes the info of the HGrid to the screen in a nice format.
Public Member Functions inherited from DPMBase
void constructor ()
A function which initialises the member variables to default values, so that the problem can be solved off the shelf; sets up a basic two dimensional problem which can be solved off the shelf. It is called in the constructor DPMBase().
DPMBase ()
Constructor that calls the "void constructor()".
DPMBase (const DPMBase &other)
Copy constructor type-2.
virtual ~DPMBase ()
virtual destructor
void autoNumber ()
The autoNumber() function calls three functions: setRunNumber(), readRunNumberFromFile() and incrementRunNumberInFile().
std::vector< int > get1DParametersFromRunNumber (int size_x) const
This turns a counter into 1 index, which is a useful feature for performing 1D parameter study. The index run from 1:size_x, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get2DParametersFromRunNumber (int size_x, int size_y) const
This turns a counter into 2 indices which is a very useful feature for performing a 2D study. The indices run from 1:size_x and 1:size_y, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get3DParametersFromRunNumber (int size_x, int size_y, int size_z) const
This turns a counter into 3 indices, which is a useful feature for performing a 3D parameter study. The indices run from 1:size_x, 1:size_y and 1:size_z, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
int launchNewRun (const char *name, bool quick=false)
This launches a code from within this code. Please pass the name of the code to run.
void setRunNumber (int runNumber)
This sets the counter/Run number, overriding the defaults.
int getRunNumber () const
This returns the current value of the counter (runNumber_)
virtual void decompose ()
Sends particles from processorId to the root processor.
void solve ()
The work horse of the code.
void initialiseSolve ()
Beginning of the solve routine, before time stepping.
void finaliseSolve ()
End of the solve routine, after time stepping.
virtual void computeOneTimeStep ()
Performs everything needed for one time step, used in the time-loop of solve().
void checkSettings ()
Checks if the essentials are set properly to go ahead with solving the problem.
void forceWriteOutputFiles ()
Writes output files immediately, even if the current time step was not meant to be written. Also resets the last saved time step.
virtual void writeOutputFiles ()
Writes simulation data to all the main Mercury files: .data, .ene, .fstat, .xballs and .restart (see the Mercury website for more details regarding these files).
void solve (int argc, char *argv[])
The work horse of the code. Can handle flags from the command line.
virtual void writeXBallsScript () const
This writes a script which can be used to load the xballs problem to display the data just generated.
virtual Mdouble getInfo (const BaseParticle &P) const
A virtual function that returns some user-specified information about a particle.
ParticleVtkWriter * getVtkWriter () const
virtual void writeRestartFile ()
Stores all the particle data for current save time step to a "restart" file, which is a file simply intended to store all the information necessary to "restart" a simulation from a given time step (see also MercuryDPM.org for more information on restart files).
void writeDataFile ()
void writeEneFile ()
void writeFStatFile ()
void fillDomainWithParticles (unsigned N=50)
bool readRestartFile (ReadOptions opt=ReadOptions::ReadAll)
Reads all the particle data corresponding to a given, existing . restart file (for more details regarding restart files, refer to the training materials on the MercuryDPM website).Returns true if it is successful, false otherwise.
int readRestartFile (std::string fileName, ReadOptions opt=ReadOptions::ReadAll)
The same as readRestartFile(bool), but also reads all the particle data corresponding to the current saved time step.
virtual BaseWall * readUserDefinedWall (const std::string &type) const
Allows you to read in a wall defined in a Driver directory; see USER/Luca/ScrewFiller.
virtual void readOld (std::istream &is)
Reads all data from a restart file, e.g. domain data and particle data; old version.
bool readDataFile (std::string fileName="", unsigned int format=0)
This allows particle data to be reloaded from data files.
bool readParAndIniFiles (std::string fileName)
Allows the user to read par.ini files (useful to read files produced by the MDCLR simulation code - external to MercuryDPM)
bool readNextDataFile (unsigned int format=0)
Reads the next data file with default format=0. However, one can modify the format based on whether the particle data corresponds to 3D or 2D data- see Visualising data in xballs.
void readNextFStatFile ()
Reads the next fstat file.
bool findNextExistingDataFile (Mdouble tMin, bool verbose=true)
Finds and opens the next data file, if such a file exists.
bool readArguments (int argc, char *argv[])
Can interpret main function input arguments that are passed by the driver codes.
bool checkParticleForInteractionLocalPeriodic (const BaseParticle &P)
void readSpeciesFromDataFile (bool read=true)
void importParticlesAs (ParticleHandler &particleHandler, InteractionHandler &interactionHandler, const ParticleSpecies *species)
Copies particles, interactions assigning species from a local simulation to a global one. Useful for the creation of a cluster.
MERCURYDPM_DEPRECATED File & getDataFile ()
The non const version. Allows one to edit the File::dataFile.
MERCURYDPM_DEPRECATED File & getEneFile ()
The non const version. Allows to edit the File::eneFile.
MERCURYDPM_DEPRECATED File & getFStatFile ()
The non const version. Allows to edit the File::fStatFile.
MERCURYDPM_DEPRECATED File & getRestartFile ()
The non const version. Allows to edit the File::restartFile.
MERCURYDPM_DEPRECATED File & getStatFile ()
The non const version. Allows to edit the File::statFile.
File & getInteractionFile ()
Return a reference to the file InteractionsFile.
MERCURYDPM_DEPRECATED const File & getDataFile () const
The const version. Does not allow for any editing of the File::dataFile.
MERCURYDPM_DEPRECATED const File & getEneFile () const
The const version. Does not allow for any editing of the File::eneFile.
MERCURYDPM_DEPRECATED const File & getFStatFile () const
The const version. Does not allow for any editing of the File::fStatFile.
MERCURYDPM_DEPRECATED const File & getRestartFile () const
The const version. Does not allow for any editing of the File::restartFile.
MERCURYDPM_DEPRECATED const File & getStatFile () const
The const version. Does not allow for any editing of the File::statFile.
const File & getInteractionFile () const
Returns a constant reference to an Interactions file.
const std::string & getName () const
Returns the name of the file. Does not allow to change it though.
void setName (const std::string &name)
Allows to set the name of all the files (ene, data, fstat, restart, stat)
void setName (const char *name)
Calls setName(std::string)
void setSaveCount (unsigned int saveCount)
Sets File::saveCount_ for all files (ene, data, fstat, restart, stat)
void setFileType (FileType fileType)
Sets File::fileType_ for all files (ene, data, fstat, restart, stat)
void setOpenMode (std::fstream::openmode openMode)
Sets File::openMode_ for all files (ene, data, fstat, restart, stat)
void resetFileCounter ()
Resets the file counter for each file i.e. for ene, data, fstat, restart, stat)
void closeFiles ()
Closes all files (ene, data, fstat, restart, stat) that were opened to read or write.
void setVTKOutputDirectory (const std::string &dir)
Sets the output directory of the VTK files.
void setLastSavedTimeStep (unsigned int nextSavedTimeStep)
Sets the next time step for all the files (ene, data, fstat, restart, stat) at which the data is to be written or saved.
Mdouble getTime () const
Returns the current simulation time.
Mdouble getNextTime () const
Returns the current simulation time.
unsigned int getNumberOfTimeSteps () const
Returns the current counter of time-steps, i.e. the number of time-steps that the simulation has undergone so far.
void setTime (Mdouble time)
Sets a new value for the current simulation time.
void setTimeMax (Mdouble newTMax)
Sets a new value for the maximum simulation duration.
Mdouble getTimeMax () const
Returns the maximum simulation duration.
void setLogarithmicSaveCount (Mdouble logarithmicSaveCountBase)
Sets File::logarithmicSaveCount_ for all files (ene, data, fstat, restart, stat)
void setNToWrite (int nToWrite)
set the number of elements to write to the screen
int getNToWrite () const
get the number of elements to write to the
void setRotation (bool rotation)
Sets whether particle rotation is enabled or disabled.
bool getRotation () const
Indicates whether particle rotation is enabled or disabled.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (FileType writeWallsVTK)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (bool)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setInteractionsWriteVTK (bool)
Sets whether interactions are written into a VTK file.
void setParticlesWriteVTK (bool writeParticlesVTK)
Sets whether particles are written in a VTK file.
void setSuperquadricParticlesWriteVTK (bool writeSuperquadricParticlesVTK)
MERCURYDPM_DEPRECATED FileType getWallsWriteVTK () const
Returns whether walls are written in a VTK file.
bool getParticlesWriteVTK () const
Returns whether particles are written in a VTK file.
bool getSuperquadricParticlesWriteVTK () const
Mdouble getXMin () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMin() returns XMin.
Mdouble getXMax () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMax() returns XMax.
Mdouble getYMin () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMin() returns YMin.
Mdouble getYMax () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMax() returns XMax.
Mdouble getZMin () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMin() returns ZMin.
Mdouble getZMax () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMax() returns ZMax.
Mdouble getXCenter () const
Mdouble getYCenter () const
Mdouble getZCenter () const
Vec3D getCenter () const
get center of domain
Vec3D getMin () const
Returns the minimum coordinates of the problem domain.
Vec3D getMax () const
Returns the maximum coordinates of the problem domain.
void setXMin (Mdouble newXMin)
Sets the value of XMin, the lower bound of the problem domain in the x-direction.
void setYMin (Mdouble newYMin)
Sets the value of YMin, the lower bound of the problem domain in the y-direction.
void setZMin (Mdouble newZMin)
Sets the value of ZMin, the lower bound of the problem domain in the z-direction.
void setXMax (Mdouble newXMax)
Sets the value of XMax, the upper bound of the problem domain in the x-direction.
void setYMax (Mdouble newYMax)
Sets the value of YMax, the upper bound of the problem domain in the y-direction.
void setZMax (Mdouble newZMax)
Sets the value of ZMax, the upper bound of the problem domain in the z-direction.
void setMax (const Vec3D &max)
Sets the maximum coordinates of the problem domain.
void setMax (Mdouble, Mdouble, Mdouble)
Sets the maximum coordinates of the problem domain.
void setDomain (const Vec3D &min, const Vec3D &max)
Sets the minimum coordinates of the problem domain.
void setMin (const Vec3D &min)
Sets the minimum coordinates of the problem domain.
void setMin (Mdouble, Mdouble, Mdouble)
Sets the minimum coordinates of the problem domain.
void setTimeStep (Mdouble newDt)
Sets a new value for the simulation time step.
Mdouble getTimeStep () const
Returns the simulation time step.
void setNumberOfOMPThreads (int numberOfOMPThreads)
Sets the number of omp threads.
int getNumberOfOMPThreads () const
Returns the number of omp threads.
void setXBallsColourMode (int newCMode)
Set the xballs output mode.
int getXBallsColourMode () const
Get the xballs colour mode (CMode).
void setXBallsVectorScale (double newVScale)
Set the scale of vectors in xballs.
double getXBallsVectorScale () const
Returns the scale of vectors used in xballs.
void setXBallsAdditionalArguments (std::string newXBArgs)
Set the additional arguments for xballs.
std::string getXBallsAdditionalArguments () const
Returns the additional arguments for xballs.
void setXBallsScale (Mdouble newScale)
Sets the scale of the view (either normal, zoom in or zoom out) to display in xballs. The default is fit to screen.
double getXBallsScale () const
Returns the scale of the view in xballs.
void setGravity (Vec3D newGravity)
Sets a new value for the gravitational acceleration.
Vec3D getGravity () const
Returns the gravitational acceleration.
void setBackgroundDrag (Mdouble backgroundDrag)
Simple access function to turn on a background drag. The force of particleVelocity*drag is applied (note, it allowed to be negative i.e. create energy)
const Mdouble getBackgroundDrag () const
Return the background drag.
void setDimension (unsigned int newDim)
Sets both the system dimensions and the particle dimensionality.
void setSystemDimensions (unsigned int newDim)
Sets the system dimensionality.
unsigned int getSystemDimensions () const
Returns the system dimensionality.
void setParticleDimensions (unsigned int particleDimensions)
Sets the particle dimensionality.
unsigned int getParticleDimensions () const
Returns the particle dimensionality.
std::string getRestartVersion () const
This is to take into account for different Mercury versions. Returns the version of the restart file.
void setRestartVersion (std::string newRV)
Sets restart_version.
bool getRestarted () const
Returns the flag denoting if the simulation was restarted or not.
void setRestarted (bool newRestartedFlag)
Allows to set the flag stating if the simulation is to be restarted or not.
bool getAppend () const
Returns whether the "append" option is on or off.
void setAppend (bool newAppendFlag)
Sets whether the "append" option is on or off.
Mdouble getElasticEnergy () const
Returns the global elastic energy within the system.
Mdouble getKineticEnergy () const
Returns the global kinetic energy stored in the system.
Mdouble getGravitationalEnergy (Vec3D origin={0, 0, 0}) const
Returns the global gravitational potential energy stored relative to a user-defined origin in the system. Note, if no origin is specified the real origin i.e. (0,0,0) is taken.
Mdouble getRotationalEnergy () const
Returns the global rotational energy stored in the system.
Mdouble getTotalEnergy () const
Mdouble getTotalMass () const
JMFT: Return the total mass of the system, excluding fixed particles.
Vec3D getCentreOfMass () const
JMFT: Return the centre of mass of the system, excluding fixed particles.
Vec3D getTotalMomentum () const
JMFT: Return the total momentum of the system, excluding fixed particles.
double getCPUTime ()
double getWallTime ()
virtual void hGridInsertParticle (BaseParticle *obj UNUSED)
virtual void hGridUpdateParticle (BaseParticle *obj UNUSED)
virtual void hGridRemoveParticle (BaseParticle *obj UNUSED)
bool mpiIsInCommunicationZone (BaseParticle *particle)
Checks if the position of the particle is in an mpi communication zone or not.
bool mpiInsertParticleCheck (BaseParticle *P)
Function that checks if the mpi particle should really be inserted by the current domain.
void insertGhostParticle (BaseParticle *P)
This function inserts a particle in the mpi communication boundaries.
void updateGhostGrid (BaseParticle *P)
Checks if the Domain/periodic interaction distance needs to be updated and updates it accordingly.
virtual void gatherContactStatistics (unsigned int index1, int index2, Vec3D Contact, Mdouble delta, Mdouble ctheta, Mdouble fdotn, Mdouble fdott, Vec3D P1_P2_normal_, Vec3D P1_P2_tangential)
//Not unsigned index because of possible wall collisions.
void setNumberOfDomains (std::vector< unsigned > direction)
Sets the number of domains in x-,y- and z-direction. Required for parallel computations.
void splitDomain (DomainSplit domainSplit)
std::vector< unsigned > getNumberOfDomains ()
returns the number of domains
Domain * getCurrentDomain ()
Function that returns a pointer to the domain corresponding to the processor.
void removeOldFiles () const
void setMeanVelocity (Vec3D V_mean_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
void setMeanVelocityAndKineticEnergy (Vec3D V_mean_goal, Mdouble Ek_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
Mdouble getTotalVolume () const
Get the total volume of the cuboid system.
Matrix3D getKineticStress () const
Calculate the kinetic stress tensor in the system averaged over the whole volume.
Matrix3D getStaticStress () const
Calculate the static stress tensor in the system averaged over the whole volume.
Matrix3D getTotalStress () const
Calculate the total stress tensor in the system averaged over the whole volume.
virtual void handleParticleRemoval (unsigned int id)
Handles the removal of particles from the particleHandler.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
void writePythonFileForVTKVisualisation () const
writes .py file for ParaView
void setWritePythonFileForVTKVisualisation (bool forceWritePythonFileForVTKVisualisation)
bool getWritePythonFileForVTKVisualisation () const
WallVTKWriter & getWallVTKWriter ()
Protected Member Functions
void actionsBeforeTimeStep () override
Calls Chute::cleanChute().
void cleanChute ()
Deletes all outflow particles once every 100 time steps.
virtual void createBottom ()
Creates the chute bottom, which can be either flat or one of three flavours of rough.
virtual void addFlowParticlesCompactly ()
Add initial flow particles in a dense packing.
virtual SphericalParticle createFlowParticle ()
void printTime () const override
prints time, max time and number of particles
Protected Member Functions inherited from Mercury3D
void hGridFindContactsWithinTargetCell (int x, int y, int z, unsigned int l)
Finds contacts between particles in the target cell.
void hGridFindContactsWithTargetCell (int x, int y, int z, unsigned int l, BaseParticle *obj)
Finds contacts between the BaseParticle and the target cell.
void computeWallForces (BaseWall *w) override
Compute contacts with a wall.
void hGridFindParticlesWithTargetCell (int x, int y, int z, unsigned int l, BaseParticle *obj, std::vector< BaseParticle * > &list)
Finds particles within target cell and stores them in a list.
void hGridGetInteractingParticleList (BaseParticle *obj, std::vector< BaseParticle * > &list) override
Obtains all neighbour particles of a given object, obtained from the hgrid.
void computeInternalForces (BaseParticle *obj) override
Finds contacts with the BaseParticle; avoids multiple checks.
bool hGridHasContactsInTargetCell (int x, int y, int z, unsigned int l, const BaseParticle *obj) const
Tests if the BaseParticle has contacts with other Particles in the target cell.
bool hGridHasParticleContacts (const BaseParticle *obj) override
Tests if a BaseParticle has any contacts in the HGrid.
void hGridRemoveParticle (BaseParticle *obj) override
Removes a BaseParticle from the HGrid.
void hGridUpdateParticle (BaseParticle *obj) override
Updates the cell (not the level) of a BaseParticle.
Protected Member Functions inherited from MercuryBase
void hGridRebuild ()
This sets up the parameters required for the contact model.
void hGridInsertParticle (BaseParticle *obj) final
Inserts a single Particle to current grid.
void hGridUpdateMove (BaseParticle *iP, Mdouble move) final
Computes the relative displacement of the given BaseParticle and updates the currentMaxRelativeDisplacement_ accordingly.
void hGridActionsBeforeIntegration () override
Resets the currentMaxRelativeDisplacement_ to 0.
void hGridActionsAfterIntegration () override
This function has to be called before integrateBeforeForceComputation.
HGrid * getHGrid ()
Gets the HGrid used by this problem.
const HGrid * getHGrid () const
Gets the HGrid used by this problem, const version.
bool readNextArgument (int &i, int argc, char *argv[]) override
Reads the next command line argument.
Protected Member Functions inherited from DPMBase
virtual void computeAllForces ()
Computes all the forces acting on the particles using the BaseInteractable::setForce() and BaseInteractable::setTorque()
virtual void computeInternalForce (BaseParticle *, BaseParticle *)
Computes the forces between two particles (internal in the sense that the sum over all these forces is zero i.e. fully modelled forces)
virtual void computeExternalForces (BaseParticle *)
Computes the external forces, such as gravity, acting on particles.
virtual void computeForcesDueToWalls (BaseParticle *, BaseWall *)
Computes the forces on the particles due to the walls (normals are outward normals)
virtual void actionsOnRestart ()
A virtual function where the users can add extra code which is executed only when the code is restarted.
virtual void actionsBeforeTimeLoop ()
A virtual function. Allows one to carry out any operations before the start of the time loop.
virtual void computeAdditionalForces ()
A virtual function which allows to define operations to be executed prior to the OMP force collect.
virtual void actionsAfterSolve ()
A virtual function which allows to define operations to be executed after the solve().
virtual void actionsAfterTimeStep ()
A virtual function which allows to define operations to be executed after time step.
void writeVTKFiles () const
virtual void outputXBallsData (std::ostream &os) const
This function writes the location of the walls and particles in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void outputXBallsDataParticle (unsigned int i, unsigned int format, std::ostream &os) const
This function writes out the particle locations into an output stream in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void writeEneHeader (std::ostream &os) const
Writes a header with a certain format for ENE file.
virtual void writeFstatHeader (std::ostream &os) const
Writes a header with a certain format for FStat file.
virtual void writeEneTimeStep (std::ostream &os) const
Write the global kinetic, potential energy, etc. in the system.
virtual void initialiseStatistics ()
virtual void outputStatistics ()
void gatherContactStatistics ()
virtual void processStatistics (bool)
virtual void finishStatistics ()
virtual void integrateBeforeForceComputation ()
Update particles' and walls' positions and velocities before force computation.
virtual void integrateAfterForceComputation ()
Update particles' and walls' positions and velocities after force computation.
virtual void checkInteractionWithBoundaries ()
There are a range of boundaries one could implement depending on ones' problem. This methods checks for interactions between particles and such range of boundaries. See BaseBoundary.h and all the boundaries in the Boundaries folder.
void setFixedParticles (unsigned int n)
Sets a number, n, of particles in the particleHandler as "fixed particles".
virtual bool continueSolve () const
A virtual function for deciding whether to continue the simulation, based on a user-specified criterion.
void outputInteractionDetails () const
Displays the interaction details corresponding to the pointer objects in the interaction handler.
bool isTimeEqualTo (Mdouble time) const
Checks whether the input variable "time" is the current time in the simulation.
void removeDuplicatePeriodicParticles ()
Removes periodic duplicate Particles.
void checkAndDuplicatePeriodicParticles ()
For simulations using periodic boundaries, checks and adds particles when necessary into the particle handler. See DPMBase.cc and PeriodicBoundary.cc for more details.
void performGhostParticleUpdate ()
When the Verlet scheme updates the positions and velocities of particles, ghost particles will need an update as wel. Their status will also be updated accordingly.
void deleteGhostParticles (std::set< BaseParticle * > &particlesToBeDeleted)
void synchroniseParticle (BaseParticle *, unsigned fromProcessor=0)
void performGhostVelocityUpdate ()
updates the final time-step velocity of the ghost particles
void disableSoftStop ()
This prevents the initialisation of the soft stop feature.
void discontinueSolve ()
This discontinues the solve loop after the current time step is finished.
Private Attributes
Mdouble chuteAngle_
chute angle in degrees
Mdouble fixedParticleRadius_
radius of the fixed particles at the bottom
Mdouble fixedParticleSpacing_
spacing of the fixed particles at the bottom (center distance / diameter - 1)
Mdouble minInflowParticleRadius_
minimal radius of inflowing particles
Mdouble maxInflowParticleRadius_
maximal radius of inflowing particles
Mdouble inflowVelocity_
Average inflow velocity in x-direction.
Mdouble inflowVelocityVariance_
Inflow velocity variance in x-direction (in ratio of inflowVelocity_)
Mdouble inflowHeight_
Height of inflow.
RoughBottomType roughBottomType_
Determines the type of rough bottom created (if any). See also the enum RoughBottomType at the beginning of this header file.
unsigned int maxFailed_
indicates how many attempts are made to insert a new particle into the insertion boundary before the boundary is considered filled.
InsertionBoundary * insertionBoundary_
(Pointer to) the Chute's insertion boundary
bool isChutePeriodic_
Determines whether the chute has periodic (TRUE) or solid (FALSE) walls in the Y-direction.
Additional Inherited Members
Public Types inherited from DPMBase
enum class ReadOptions : int { ReadAll , ReadNoInteractions , ReadNoParticlesAndInteractions }
enum class DomainSplit {
X , Y , Z , XY ,
XZ , YZ , XYZ
}
Static Public Member Functions inherited from DPMBase
static void incrementRunNumberInFile ()
Increment the run Number (counter value) stored in the file_counter (COUNTER_DONOTDEL) by 1 and store the new value in the counter file.
static int readRunNumberFromFile ()
Read the run number or the counter from the counter file (COUNTER_DONOTDEL)
static bool areInContact (const BaseParticle *pI, const BaseParticle *pJ)
Checks if two particle are in contact or is there any positive overlap.
Public Attributes inherited from DPMBase
SpeciesHandler speciesHandler
A handler to that stores the species type i.e. LinearViscoelasticSpecies, etc.
RNG random
This is a random generator, often used for setting up the initial conditions etc...
ParticleHandler particleHandler
An object of the class ParticleHandler, contains the pointers to all the particles created.
ParticleHandler paoloParticleHandler
Fake particleHandler created by Paolo needed temporary by just Paolo.
WallHandler wallHandler
An object of the class WallHandler. Contains pointers to all the walls created.
BoundaryHandler boundaryHandler
An object of the class BoundaryHandler which concerns insertion and deletion of particles into or from regions.
PeriodicBoundaryHandler periodicBoundaryHandler
Internal handler that deals with periodic boundaries, especially in a parallel build.
DomainHandler domainHandler
An object of the class DomainHandler which deals with parallel code.
InteractionHandler interactionHandler
An object of the class InteractionHandler.
CGHandler cgHandler
Object of the class cgHandler.
File dataFile
An instance of class File to handle in- and output into a .data file.
File fStatFile
An instance of class File to handle in- and output into a .fstat file.
File eneFile
An instance of class File to handle in- and output into a .ene file.
File restartFile
An instance of class File to handle in- and output into a .restart file.
File statFile
An instance of class File to handle in- and output into a .stat file.
File interactionFile
File class to handle in- and output into .interactions file. This file hold information about interactions.
Time clock_
record when the simulation started
Detailed Description
Creates chutes with different bottoms. Inherits from Mercury3D (-> MercuryBase -> DPMBase).
Chute adds three new effects as compared to a 'normal' Mercury3D object: the gravity direction can be set using the ChuteAngle variable, a (smooth or rough) bottom wall is created by default, and some basic inflow and outflow routines are added.
Constructor & Destructor Documentation
Chute() [1/5]
Chute::Chute ()
This is the default constructor. All it does is set sensible defaults.
Default constructor.
 {
     constructor();
     logger(DEBUG, "[Chute::Chute()] constructor finished");
 }
References constructor(), DEBUG, and logger.
Chute() [2/5]
Chute::Chute (const DPMBase & other) explicit
Copy constructor, converts an existing DPMBase problem into a Chute problem.
Copy constructor with a DPMBase object as an argument. This constructor basically 'upgrades' a DPMBase object to one of the Chute class. NB: The copy constructor of DPMBase has to be called because the link from DPMBase to MercuryBase is virtual.
Parameters
[in] other object of DPMBase class
         : DPMBase(other), Mercury3D(other)
 {
     constructor();
     logger(DEBUG, "[Chute::Chute(const DPMBase& other)] copy constructor finished");
 }
References constructor(), DEBUG, and logger.
Chute() [3/5]
Chute::Chute (const MercuryBase & other) explicit
Copy constructor, converts an existing MercuryBase problem into a Chute problem.
Copy constructor with a MercuryBase object as an argument. This constructor basically 'upgrades' a MercuryBase object to one of the Chute class. NB: The copy constructor of DPMBase has to be called because the link from DPMBase to MercuryBase is virtual.
Parameters
[in] other object of MercuryBase class
         : DPMBase(other), Mercury3D(other)
 {
     constructor();
     logger(DEBUG, "[Chute::Chute(const MercuryBase& other)] copy constructor finished");
 }
References constructor(), DEBUG, and logger.
Chute() [4/5]
Chute::Chute (const Mercury3D & other) explicit
Copy constructor, converts an existing Mercury3D problem into a Chute problem.
Copy constructor with a Mercury3D object as an argument. This constructor basically 'upgrades' a Mercury3D object to one of the Chute class. NB: The copy constructor of DPMBase has to be called because the link from DPMBase to MercuryBase is virtual.
Parameters
[in] other object of DPMBase class
         : DPMBase(other), Mercury3D(other)
 {
     constructor();
     logger(DEBUG, "[Chute::Chute(const Mercury3D& other) copy constructor finished");
 }
References constructor(), DEBUG, and logger.
Chute() [5/5]
Chute::Chute (const Chute & other)
Default copy constructor.
'normal' copy constructor. This is a shallow copy, namely of the insertionBoundary, only the pointer is copied instead of the entire boundary.
Parameters
[in] other Chute object to be copied
Todo:
Check if this should indeed be a shallow copy.
         : DPMBase(other), Mercury3D(other),
           chuteAngle_(other.chuteAngle_),
           fixedParticleRadius_(other.fixedParticleRadius_),
           minInflowParticleRadius_(other.minInflowParticleRadius_),
           maxInflowParticleRadius_(other.maxInflowParticleRadius_),
           inflowVelocity_(other.inflowVelocity_),
           inflowVelocityVariance_(other.inflowVelocityVariance_),
           inflowHeight_(other.inflowHeight_),
           roughBottomType_(other.roughBottomType_),
           maxFailed_(other.maxFailed_),
           insertionBoundary_(other.insertionBoundary_),
           isChutePeriodic_(other.isChutePeriodic_)
 {
     logger(DEBUG, "[Chute::Chute(const Chute& other)] copy constructor finished");
 }
References DEBUG, and logger.
Member Function Documentation
actionsBeforeTimeStep()
void Chute::actionsBeforeTimeStep () override protected virtual
Calls Chute::cleanChute().
Applies all necessary actions before the next time step. In this case, it only calls Chute::cleanChute().
Reimplemented from DPMBase.
Reimplemented in ChuteBottom.
 {
     cleanChute();
 }
References cleanChute().
addFlowParticlesCompactly()
void Chute::addFlowParticlesCompactly () protected virtual
Add initial flow particles in a dense packing.
 {
     unsigned int N = particleHandler.getNumberOfObjects() + getChuteLength() * getChuteWidth() * getInflowHeight() /
                                                             mathsFunc::cubic(2.0*getInflowParticleRadius());
     logger(INFO, "Adding % flowing particles to % bed particles", N-particleHandler.getNumberOfObjects(), particleHandler.getNumberOfObjects());
     particleHandler.setStorageCapacity((N));
     setZMax(1.2 * getInflowHeight());
     while (particleHandler.getSize() < N)
     {
         SphericalParticle p0 = createFlowParticle();
         if (checkParticleForInteraction(p0))
         {
             particleHandler.copyAndAddObject(p0);
         }
         else
         {
             setInflowHeight(getInflowHeight() + .0001 * getMaxInflowParticleRadius());
         }
     }
     logger(DEBUG, "InflowHeight = %", getInflowHeight());
 }
References MercuryBase::checkParticleForInteraction(), BaseHandler< T >::copyAndAddObject(), createFlowParticle(), mathsFunc::cubic(), DEBUG, getChuteLength(), getChuteWidth(), getInflowHeight(), getInflowParticleRadius(), getMaxInflowParticleRadius(), ParticleHandler::getNumberOfObjects(), BaseHandler< T >::getSize(), INFO, logger, N, p0, DPMBase::particleHandler, setInflowHeight(), BaseHandler< T >::setStorageCapacity(), and DPMBase::setZMax().
Referenced by ChutePeriodicDemo::setupInitialConditions(), and SingleParticleSegregation::setupInitialConditions().
cleanChute()
void Chute::cleanChute () protected
Deletes all outflow particles once every 100 time steps.
Removes all particles which are outside the horizontal window, i.e. all particles with an x-direction position greater than xMax_ or smaller than xMin_. The removal operation is performed once every 100 time steps.
 {
     //clean outflow every 100 time steps
     static int count = 0, maxcount = 100; // please note: static variables are only initialised once, and their values
     // are stored even after the method returns. I.e., next time the method is
     // called, the initialisation is ignored and the previously assigned value is used.
     if (count > maxcount)
     {
         // reset counter
         count = 0;
         // check all particles
         for (unsigned int i = 0; i < particleHandler.getNumberOfObjects();)
         {
             // check if particle is outside the problem window
             if (particleHandler.getObject(i)->getPosition().X > getXMax() ||
                 particleHandler.getObject(i)->getPosition().X <
                 getXMin()) //||particleHandler.getObject(i)->Position.Z+particleHandler.getObject(i)->Radius<zMin_)
             {
                 // if so, delete the particle
                 logger(DEBUG, "[Chute::cleanChute()] erased: %", particleHandler.getObject(i));
                 particleHandler.removeObject(i);
             }
             else
             {
                 i++;
             }
         }
     }
     else
     {
         count++;
     }
 }
References DEBUG, ParticleHandler::getNumberOfObjects(), BaseHandler< T >::getObject(), BaseInteractable::getPosition(), DPMBase::getXMax(), DPMBase::getXMin(), i, logger, DPMBase::particleHandler, ParticleHandler::removeObject(), and Vec3D::X.
Referenced by SmoothChute::actionsBeforeTimeStep(), and actionsBeforeTimeStep().
constructor()
void Chute::constructor ()
This is the actual constructor METHOD; it is called by all constructors above (except the default copy constructor).
constructor METHOD, which sets all chute properties to something sensible. This method should be called by all constructors except for the copy constructor that accepts another Chute.
 {
     insertionBoundary_ = nullptr;
     isChutePeriodic_ = false;
     setFixedParticleRadius(0.001);
     setRoughBottomType(MONOLAYER_DISORDERED);
     setChuteAngle(0.0);
     setMaxFailed(1);
     setInflowParticleRadius(0.001);
     setInflowVelocity(0.1);
     setInflowVelocityVariance(0.0);
     setInflowHeight(0.02);
 }
References insertionBoundary_, isChutePeriodic_, MONOLAYER_DISORDERED, setChuteAngle(), setFixedParticleRadius(), setInflowHeight(), setInflowParticleRadius(), setInflowVelocity(), setInflowVelocityVariance(), setMaxFailed(), and setRoughBottomType().
Referenced by Chute().
createBottom()
void Chute::createBottom () protected virtual
Creates the chute bottom, which can be either flat or one of three flavours of rough.
Creates the bottom of the chute; either:
smooth: fixedParticleRadius_ smaller than 1e-12 or roughBottomType_ == FLAT, monolayered:
grid-like: roughBottomType_ == MONOLAYER_ORDERED,
random: roughBottomType_ == MONOLAYER_DISORDERED, or
multilayer: 'else' (roughBottomType_ == MULTILAYER), with by default contains all particles with a center within a depth band of 2.4 (= ChuteBottom::thickness_) * maxInflowParticleRadius_.
Todo:
Does the bottom we always has to be this particle? Maybe add a BaseParticle* argument, and add a default value with particle radius < 1e-12.
Reimplemented in FlowRule, VariableBottom, and VariableBottom.
 {
     // smooth bottom:
     if (fabs(getFixedParticleRadius()) < 1e-12 || roughBottomType_ == FLAT)
     {
         // flat wall as bottom
         logger(INFO, "[Chute::createBottom()] create perfectly flat chute bottom");
         //bottom wall
         InfiniteWall w0;
         w0.setSpecies(speciesHandler.getObject(0));
         w0.set(Vec3D(0.0, 0.0, -1.0), Vec3D(0, 0, getZMin()));
         wallHandler.copyAndAddObject(w0);
     }
     else //rough bottom
     {
         // Define standard fixed particle
         SphericalParticle F0;
         F0.setSpecies(speciesHandler.getObject(0));
         F0.setHandler(&particleHandler);
         F0.setRadius(getFixedParticleRadius());
         F0.setPosition(Vec3D(0.0, 0.0, 0.0));
         F0.setVelocity(Vec3D(0.0, 0.0, 0.0));
         if (roughBottomType_ == MONOLAYER_ORDERED)
         {
             // grid-like fixed-particle bottom
             logger(INFO, "[Chute::createBottom()] create monolayered, ordered rough chute bottom");
             // allowed space for each particle in each direction
             Mdouble dx = 2.0 * F0.getRadius();
             Mdouble dy = 2.0 * F0.getRadius();
             // number of particles that fit in each direction
             unsigned int nx = static_cast<unsigned int>(std::max(1, static_cast<int>(std::floor(
                     (getXMax() - getXMin()) / dx))));
             unsigned int ny = static_cast<unsigned int>(std::max(1, static_cast<int>(std::floor(
                     (getYMax() - getYMin()) / dy))));
             // adjust particle spacing (in case total space available in given direction
             // is not a multiple of 2*F0.getRadius() )
             dx = (getXMax() - getXMin()) / nx;
             dy = (getYMax() - getYMin()) / ny;
             for (unsigned int i = 0; i < nx; i++)
             {
                 for (unsigned int j = 0; j < ny; j++)
                 {
                     // placing of particles on rectangular grid points
                     F0.setPosition(Vec3D(F0.getRadius() + dx * i, F0.getRadius() + dy * j, 0.0));
                     particleHandler.copyAndAddObject(F0);
                 }
             }
             //bottom wall, to make sure no particles will fall through the gaps
             InfiniteWall w0;
             w0.setSpecies(speciesHandler.getObject(0));
             w0.set(Vec3D(0.0, 0.0, -1.0), Vec3D(0, 0, getZMin() - dx)); // todo [?] why zmin-dx?
             wallHandler.copyAndAddObject(w0);
         }
         else if (roughBottomType_ == MONOLAYER_DISORDERED)
         {
             // random fixed-particle bottom
             logger(INFO, "[Chute::createBottom()] create monolayered disordered rough chute bottom");
             Vec3D position;
             position.X = random.getRandomNumber(F0.getRadius(), getXMax() - F0.getRadius());
             position.Y = random.getRandomNumber(getYMin() + F0.getRadius(), getYMax() - F0.getRadius());
             F0.setPosition(position);
             particleHandler.copyAndAddObject(F0);
             hGridActionsBeforeTimeLoop();
             hGridActionsBeforeTimeStep();
             //now add more particles
             int failed = 0;
             while (failed < 500)
             {
                 //The position components are first stored in a Vec3D, because
                 //if you pass them directly into setPosition the compiler is
                 //allowed to change the order in which the numbers are generated
                 position.X = random.getRandomNumber(F0.getRadius(), getXMax() - F0.getRadius());
                 position.Y = random.getRandomNumber(getYMin() + F0.getRadius(), getYMax() - F0.getRadius());
                 F0.setPosition(position);
                 if (checkParticleForInteraction(F0))
                 {
                     particleHandler.copyAndAddObject(F0);
                     failed = 0;
                 }
                 else
                 {
                     failed++;
                 }
             }
             //bottom wall (create after particle creation, as
             //checkParticleForInteraction also checks against walls)
             InfiniteWall w0;
             w0.setSpecies(speciesHandler.getObject(0));
             w0.set(Vec3D(0.0, 0.0, -1.0), Vec3D(0, 0, getZMin() - .5 * F0.getRadius()));
             wallHandler.copyAndAddObject(w0);
         }
         else if (roughBottomType_ == MONOLAYER_TRIANGULAR)
         {
             // fixed-particle bottom with triangular packing (given size and spacing)
             logger(INFO,"[Chute::createBottom()] create monolayered, ordered rough chute bottom with triangular packing");
             // allowed space for each particle in each direction
             Mdouble dx = (1 + getFixedParticleSpacing()) * 2.0 * F0.getRadius();
             Mdouble dy = sqrt(1 + getFixedParticleSpacing()) * 2.0 * F0.getRadius();
             // number of particles that fit in each direction
             unsigned int nx = static_cast<unsigned int>(std::max(1, static_cast<int>(std::floor((getXMax() - getXMin()) / dx)))) + 1;
             unsigned int ny = static_cast<unsigned int>(std::max(1, static_cast<int>(std::floor((getYMax() - getYMin()) / dy)))) + 1;
             Mdouble x1, x2, y1, y2;
             for (unsigned int i = 0; i < nx; i++)
             {
                 for (unsigned int j = 0; j < ny; j++)
                 {
                     x1 = F0.getRadius() + dx * i;
                     x2 = x1 + dx/2;
                     y1 = F0.getRadius() + dy * i;
                     y2 = y1 + dy/2;
                     // placing of particles on triangular grid points
                     if (x1 < getXMax() && y1 < getYMax())
                     {
                         F0.setPosition(Vec3D(x1, y1, 0.0));
                         particleHandler.copyAndAddObject(F0);
                     }
                     if (x2 < getXMax() && y2 < getYMax())
                     {
                         F0.setPosition(Vec3D(x2, y2, 0.0));
                         particleHandler.copyAndAddObject(F0);
                     }
                 }
             }
             //bottom wall, to make sure no particles will fall through the gaps
             InfiniteWall w0;
             w0.setSpecies(speciesHandler.getObject(0));
             w0.set(Vec3D(0.0, 0.0, -1.0), Vec3D(0, 0, -F0.getRadius()));
             wallHandler.copyAndAddObject(w0);
         }
         else //if (roughBottomType_ == MULTILAYER)
         {
             // multilayered particle bottom
             logger(INFO, "[Chute::createBottom()] create multilayered rough chute bottom");
             //'this' points to the current Chute object, the class of which is inherited
             // by the ChuteBottom class. I.e., the bottom is created with the particle
             // properties from the current class.
             // ChuteBottom::makeRoughBottom() creates a randomly filled, multilayered
             // chute bottom.
             ChuteBottom bottom(*this);
             bottom.setInflowParticleRadius(getFixedParticleRadius());
             bottom.makeRoughBottom(*this);
             //bottom wall
             InfiniteWall w0;
             w0.setSpecies(speciesHandler.getObject(0));
             w0.set(Vec3D(0.0, 0.0, -1.0), Vec3D(0, 0, getZMin() - bottom.getThickness()));
             wallHandler.copyAndAddObject(w0);
         }
         //finally, fix particles to the bottom
         for (BaseParticle* const p : particleHandler)
         {
             p->fixParticle();
         }
     }
 }
References MercuryBase::checkParticleForInteraction(), BaseHandler< T >::copyAndAddObject(), e(), boost::multiprecision::fabs(), FLAT, Eigen::bfloat16_impl::floor(), getFixedParticleRadius(), getFixedParticleSpacing(), BaseHandler< T >::getObject(), BaseParticle::getRadius(), RNG::getRandomNumber(), ChuteBottom::getThickness(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), DPMBase::getZMin(), MercuryBase::hGridActionsBeforeTimeLoop(), MercuryBase::hGridActionsBeforeTimeStep(), i, INFO, j, logger, ChuteBottom::makeRoughBottom(), max, MONOLAYER_DISORDERED, MONOLAYER_ORDERED, MONOLAYER_TRIANGULAR, Mesh_Parameters::nx, Mesh_Parameters::ny, p, DPMBase::particleHandler, DPMBase::random, roughBottomType_, InfiniteWall::set(), BaseParticle::setHandler(), setInflowParticleRadius(), BaseInteractable::setPosition(), BaseParticle::setRadius(), BaseParticle::setSpecies(), BaseWall::setSpecies(), BaseInteractable::setVelocity(), DPMBase::speciesHandler, sqrt(), DPMBase::wallHandler, Vec3D::X, Global_parameters::x1(), Global_parameters::x2(), and Vec3D::Y.
Referenced by Funnel::setupInitialConditions(), AngleOfRepose::setupInitialConditions(), SilbertPeriodic::setupInitialConditions(), setupInitialConditions(), ChuteBottom::setupInitialConditions(), and ChuteWithHopper::setupInitialConditions().
createFlowParticle()
SphericalParticle Chute::createFlowParticle () protected virtual
Reimplemented in ChuteWithWedge.
 {
     SphericalParticle p0;
     p0.setSpecies(speciesHandler.getObject(0));
     p0.setRadius(random.getRandomNumber(getMinInflowParticleRadius(), getMaxInflowParticleRadius()));
     p0.setPosition(Vec3D(random.getRandomNumber(getXMin() + p0.getRadius(), getXMax() - p0.getRadius()),
                          random.getRandomNumber(getYMin() + p0.getRadius(), getYMax() - p0.getRadius()),
                          random.getRandomNumber(getZMin() + p0.getRadius() + getFixedParticleRadius(),
                                                 getInflowHeight())));
     p0.setVelocity(Vec3D(0.0, 0.0, 0.0));
     return p0;
 }
References getFixedParticleRadius(), getInflowHeight(), getMaxInflowParticleRadius(), getMinInflowParticleRadius(), BaseHandler< T >::getObject(), RNG::getRandomNumber(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), DPMBase::getZMin(), p0, DPMBase::random, and DPMBase::speciesHandler.
Referenced by addFlowParticlesCompactly().
getChuteAngle()
Mdouble Chute::getChuteAngle () const
Returns the chute angle (in radians)
Returns the chute angle (as compared to the horizontal plane) in RADIANS
Returns
the chute angle in RADIANS
 {
     return chuteAngle_;
 }
References chuteAngle_.
Referenced by ChuteWithHopper::addHopper(), Funnel::create_funnel(), Funnel::create_inflow_particle(), SegregationWithHopper::create_inflow_particle(), ChuteWithHopper::getMaximumVelocityInducedByGravity(), SilbertHstop::IsAboveCurve(), main(), ChuteWithHopper::setHopper(), ChuteWithHopper::setupInitialConditions(), and SilbertHstop::solve_analytic().
getChuteAngleDegrees()
Mdouble Chute::getChuteAngleDegrees () const
Returns the chute angle (in degrees)
Returns the chute angle (as compared to the horizontal plane) in DEGREES
Returns
the chute angle in DEGREES (for writing to the terminal/an output stream)
 {
     return chuteAngle_ * 180.0 / constants::pi;
 }
References chuteAngle_, and constants::pi.
Referenced by LawinenBox::actionsBeforeTimeStep(), LawinenBox::printTime(), SilbertPeriodic::printTime(), vibratedBed::printTime(), LawinenBox::rotateChute(), AngleOfRepose::set_study(), SilbertPeriodic::set_study(), FlowRule::setName(), Funnel::setName_(), SilbertHstop::solve_analytic(), and LawinenBox::writeEneTimeStep().
getChuteLength()
Mdouble Chute::getChuteLength () const
Returns the chute length (X-direction)
Returns the length of the chute. Actually returns xMax_, while xMin_ is assumed to have stayed 0.
Returns
length of the chute
 {
     return getXMax();
 }
References DPMBase::getXMax().
Referenced by SingleParticleSegregation::actionsAfterTimeStep(), ChutePeriodic::add_flow_particles(), SilbertPeriodic::add_flow_particles(), addFlowParticlesCompactly(), SingleParticleSegregation::addIntruderParticle(), Funnel::setName_(), and SilbertPeriodic::setupInitialConditions().
getChuteWidth()
Mdouble Chute::getChuteWidth () const
Returns the chute width (Y-direction)
Returns the width of the chute. Actually returns yMax_, while it assumes yMin_ to have stayed 0.
Returns
width of the chute
 {
     return getYMax();
 }
References DPMBase::getYMax().
Referenced by SingleParticleSegregation::actionsAfterTimeStep(), ChutePeriodic::add_flow_particles(), SilbertPeriodic::add_flow_particles(), addFlowParticlesCompactly(), SingleParticleSegregation::addIntruderParticle(), AngleOfRepose::create_inflow_particle(), ContractionWithPeriodicInflow::set_symmetric_contraction(), ChuteWithPeriodicInflowAndContraction::set_symmetric_contraction(), ChuteWithContraction::set_symmetric_contraction(), Funnel::setName_(), and SilbertPeriodic::setupInitialConditions().
getFixedParticleRadius()
Mdouble Chute::getFixedParticleRadius () const
Returns the particle radius of the fixed particles which constitute the (rough) chute bottom.
Returns the radius of the fixed particles at the bottom (in case of a rough bottom; see also Chute::createBottom()).
Returns
The radius of the fixed particles.
 {
     return fixedParticleRadius_;
 }
References fixedParticleRadius_.
Referenced by Chutebelt::actionsOnRestart(), Funnel::create_funnel(), ChuteWithContraction::create_inflow_particle(), AngleOfRepose::create_inflow_particle(), createBottom(), createFlowParticle(), AngleOfRepose::run(), AngleOfRepose::set_study(), SilbertPeriodic::set_study(), Funnel::setName_(), FlowRule::setPolydispersity(), Cstatic2d::setupInitialConditions(), AngleOfRepose::setupInitialConditions(), SilbertPeriodic::setupInitialConditions(), ChuteBottom::setupInitialConditions(), ChuteWithHopper::setupInitialConditions(), and Funnel::update_funnel().
getFixedParticleSpacing()
Mdouble Chute::getFixedParticleSpacing () const
Returns the particle radius of the fixed particles which constitute the (rough) chute bottom; used in triangular packing only.
Returns the spacing of the fixed particles at the bottom (used in triangular packing only).
Returns
The spacing of the fixed particles.
 {
     return fixedParticleSpacing_;
 }
References fixedParticleSpacing_.
Referenced by createBottom().
getInflowHeight()
Mdouble Chute::getInflowHeight () const
Returns the maximum inflow height (Z-direction)
Returns the maximum height at which particles are introduced into the chute
Returns
the inflowHeight_
 {
     return inflowHeight_;
 }
References inflowHeight_.
Referenced by ChutePeriodic::add_flow_particles(), SilbertPeriodic::add_flow_particles(), addFlowParticlesCompactly(), Funnel::create_funnel(), ChutePeriodic::create_inflow_particle(), Funnel::create_inflow_particle(), FlowRule::create_inflow_particle(), SilbertPeriodic::create_inflow_particle(), createFlowParticle(), AngleOfRepose::get_H(), SilbertPeriodic::get_H(), SilbertPeriodic::set_H(), AngleOfRepose::set_study(), SilbertPeriodic::set_study(), FlowRule::setName(), and SingleParticleSegregation::SingleParticleSegregation().
getInflowParticleRadius()
Mdouble Chute::getInflowParticleRadius () const
Returns the average radius of inflow particles.
Returns the mean of the min. and max. inflow particle radius.
Returns
the mean of the min. and max. inflow particle radius.
 {
     return 0.5 * (minInflowParticleRadius_ + maxInflowParticleRadius_);
 }
References maxInflowParticleRadius_, and minInflowParticleRadius_.
Referenced by AngleOfRepose::actionsBeforeTimeStep(), ChutePeriodic::add_flow_particles(), addFlowParticlesCompactly(), ChutePeriodicDemo::ChutePeriodicDemo(), ChuteBottom::makeRoughBottom(), statistics_while_running< T >::run(), Cstatic2d::set_particle_properties(), Cstatic3D::set_particle_properties(), Funnel::setName_(), ChutePeriodic::setup(), Cstatic2d::setupInitialConditions(), Cstatic3D::setupInitialConditions(), AngleOfRepose::setupInitialConditions(), and ChuteBottom::setupInitialConditions().
getInflowVelocity()
Mdouble Chute::getInflowVelocity () const
Returns the average inflow velocity.
Returns the mean velocity at which the particles enter the chute
Returns
the mean velocity at which the particles enter the chute
 {
     return inflowVelocity_;
 }
References inflowVelocity_.
Referenced by ChuteWithContraction::create_inflow_particle(), Funnel::create_inflow_particle(), and SilbertPeriodic::create_inflow_particle().
getInflowVelocityVariance()
Mdouble Chute::getInflowVelocityVariance () const
Returns the inflow velocity variance.
Returns the variance of the velocities of the inflow particles around the mean
Returns
the variance of the velocities of the inflow particles around the mean (expressed in ratio of the mean, i.e. the inflowVelocity_).
 {
     return inflowVelocityVariance_;
 }
References inflowVelocityVariance_.
Referenced by ChuteWithContraction::create_inflow_particle(), and Funnel::create_inflow_particle().
getIsPeriodic()
bool Chute::getIsPeriodic () const
Returns whether the chute is periodic in Y.
Returns isChutePeriodic_, which is TRUE if the side walls (i.e. the walls in the Y-direction) of the chute are periodic
Returns
Whether or not the Chute is periodic.
 {
     return isChutePeriodic_;
 }
References isChutePeriodic_.
Referenced by Chutebelt::actionsAfterTimeStep(), ChuteWithPeriodicInflow::Check_and_Duplicate_Periodic_Particle(), Funnel::create_walls(), ChuteWithPeriodicInflow::integrateBeforeForceComputation(), and Chutebelt::setupInitialConditions().
getMaxFailed()
unsigned int Chute::getMaxFailed () const
Returns the number of times a particle will be tried to be added to the insertion boundary.
Returns the number of times that the boundary may fail to insert a particle, before the boundary is considered filled.
Returns
The number of times that the boundary may fail to insert a particle
 {
     return maxFailed_;
 }
References maxFailed_.
Referenced by AngleOfRepose::actionsBeforeTimeStep(), and ChuteWithHopper::setupInitialConditions().
getMaxInflowParticleRadius()
Mdouble Chute::getMaxInflowParticleRadius () const
Returns the maximum radius of inflow particles.
Returns the maximum inflow particle radius
Returns
the maximum inflow particle radius
 {
     return maxInflowParticleRadius_;
 }
References maxInflowParticleRadius_.
Referenced by ChutePeriodic::add_flow_particles(), SilbertPeriodic::add_flow_particles(), addFlowParticlesCompactly(), ChuteWithPeriodicInflow::Check_and_Duplicate_Periodic_Particle(), LawinenBox::create_inflow_particle(), ChutePeriodic::create_inflow_particle(), ChuteWithContraction::create_inflow_particle(), Funnel::create_inflow_particle(), AngleOfRepose::create_inflow_particle(), FlowRule::create_inflow_particle(), SilbertPeriodic::create_inflow_particle(), createFlowParticle(), FlowRule::getPolydispersity(), ChuteBottom::makeRoughBottom(), Cstatic2d::set_particle_properties(), Cstatic3D::set_particle_properties(), FlowRule::setPolydispersity(), SilbertPeriodic::setupInitialConditions(), setupInitialConditions(), ChuteBottom::setupInitialConditions(), and ChuteWithHopper::setupInitialConditions().
getMinInflowParticleRadius()
Mdouble Chute::getMinInflowParticleRadius () const
returns the minimum radius of inflow particles
returns the minimum inflow particle radius
Returns
the minimum inflow particle radius
 {
     return minInflowParticleRadius_;
 }
References minInflowParticleRadius_.
Referenced by LawinenBox::create_inflow_particle(), ChutePeriodic::create_inflow_particle(), ChuteWithContraction::create_inflow_particle(), Funnel::create_inflow_particle(), AngleOfRepose::create_inflow_particle(), FlowRule::create_inflow_particle(), SilbertPeriodic::create_inflow_particle(), createFlowParticle(), FlowRule::getPolydispersity(), ChuteWithHopper::getTimeStepRatio(), ChuteBottom::makeRoughBottom(), Cstatic2d::set_particle_properties(), Cstatic3D::set_particle_properties(), FlowRule::setPolydispersity(), setupInitialConditions(), ChuteBottom::setupInitialConditions(), and ChuteWithHopper::setupInitialConditions().
getRoughBottomType()
RoughBottomType Chute::getRoughBottomType () const
Returns the type of (rough) bottom of the chute.
Returns the roughBottomType_, which determines the type of rough bottom of the chute.
Returns
The type of the rough bottom.
 {
     return roughBottomType_;
 }
References roughBottomType_.
makeChutePeriodic()
void Chute::makeChutePeriodic ()
This makes the chute periodic in Y.
Sets the side walls (i.e. the walls in the Y-direction) of the chute to be made periodic
 {
     isChutePeriodic_ = true;
 }
References isChutePeriodic_.
Referenced by ChutePeriodicDemo::ChutePeriodicDemo(), ChutePeriodic::setup(), and SingleParticleSegregation::setupInitialConditions().
printTime()
void Chute::printTime () const override protected virtual
prints time, max time and number of particles
Prints the current simulation time, the maximum simulation time, and the current number of particles in the chute.
Reimplemented from DPMBase.
 {
     logger(INFO, "\rt=%3, tmax=%3, N=%3", getTime(), getTimeMax(), particleHandler.getNumberOfObjects());
 }
References ParticleHandler::getNumberOfObjects(), DPMBase::getTime(), DPMBase::getTimeMax(), INFO, logger, and DPMBase::particleHandler.
read()
void Chute::read (std::istream & is, ReadOptions opt = ReadOptions::ReadAll) override virtual
Reads all chute properties from an istream.
Reads the object properties from an istream, usually a restart file. Note that there are several versions of restart files at the moment, this method determines which version this restart file is by itself.
Parameters
[in,out] is the istream from which is read, usually a restart file.
Reimplemented from DPMBase.
Reimplemented in ChuteWithHopper.
 {
     MercuryBase::read(is, opt);
     //read out the full line first, so if there is an error it does not affect
     //the read of the next line
     std::string line_string;
     std::getline(is, line_string);
     logger(INFO, "Chuteline=%", line_string);
     std::stringstream line;
     line << line_string;
     if (getRestartVersion() != "1") //Other versions..
     {
         std::string dummy;
         unsigned int roughBottomType;
         line >> fixedParticleRadius_
              >> roughBottomType >> chuteAngle_
              >> minInflowParticleRadius_
              >> maxInflowParticleRadius_
              >> maxFailed_
              >> dummy
              >> inflowVelocity_
              >> inflowVelocityVariance_
              >> inflowHeight_;
         setRoughBottomType(static_cast<RoughBottomType>(roughBottomType));
         //if the Chute Angle is given in degrees, move to radians;
         if (chuteAngle_ > 1.0)
         {
             logger(WARN, "Restartfile angle converted into radians from degrees! (% rad -> % deg)", chuteAngle_,
                    chuteAngle_ * constants::pi / 180.);
             chuteAngle_ *= constants::pi / 180.;
         }
     }
     else //Version 1
     {
         std::string dummy;
         unsigned int roughBottomType;
         line >> dummy >> fixedParticleRadius_
              >> dummy >> minInflowParticleRadius_
              >> dummy >> maxInflowParticleRadius_
              >> dummy >> roughBottomType
              >> dummy >> chuteAngle_
              >> dummy >> maxFailed_
              >> dummy >> dummy
              >> dummy >> inflowVelocity_
              >> dummy >> inflowVelocityVariance_
              >> dummy >> inflowHeight_;
         setRoughBottomType(static_cast<RoughBottomType>(roughBottomType));
         //This version always writes radians
     }
 }
References chuteAngle_, fixedParticleRadius_, DPMBase::getRestartVersion(), inflowHeight_, inflowVelocity_, inflowVelocityVariance_, INFO, calibrate::line, logger, maxFailed_, maxInflowParticleRadius_, minInflowParticleRadius_, constants::pi, MercuryBase::read(), setRoughBottomType(), oomph::Global_string_for_annotation::string(), and WARN.
Referenced by Funnel::read(), and ChuteWithHopper::read().
readNextArgument()
bool Chute::readNextArgument (int & i, int argc, char * argv[]) override virtual
This method can be used for reading object properties from a string.
this reads chute parameters from a string. It is used to read command-line arguments. Note that the last else calls the readNextArgument of the parent, Mercury3D.
Parameters
[in] i the index of the input parameter to be read
[in] argc number of input parameters
[in] argv[] pointer to the (first character of the) actual string of input parameters.
Returns
a bool which indicates whether the argument is a valid option.
Reimplemented from DPMBase.
Reimplemented in ChuteWithHopper.
 {
     if (!strcmp(argv[i], "-inflowHeight"))
     {
         setInflowHeight(atof(argv[i + 1]));
         setZMax(atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-inflowVelocity"))
     {
         setInflowVelocity(atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-chuteAngle"))
     {
         setChuteAngle(atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-chuteLength"))
     {
         setChuteLength(atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-chuteWidth"))
     {
         setChuteWidth(atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-fixedParticleRadius"))
     {
         setFixedParticleRadius(atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-max_failed"))
     {
         setMaxFailed(static_cast<unsigned int>(atoi(argv[i + 1])));
     }
     else if (!strcmp(argv[i], "-inflowParticleRadiusRange"))
     {
         setInflowParticleRadius(atof(argv[i + 1]), atof(argv[i + 2]));
         i++;
     }
     else if (!strcmp(argv[i], "-inflowParticleRadius"))
     {
         setInflowParticleRadius(atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-roughBottomType"))
     {
         std::string str(argv[i + 1]);
         setRoughBottomType(str);
     }
 //    else if (!strcmp(argv[i], "-k_eps"))
 //    {
 //        Mdouble Mass = getLightestParticleMass();
 //        //~ Mdouble Mass =  particleHandler.get_LightestParticle()->getMass();
 //        speciesHandler.getObject(0)->setStiffnessAndRestitutionCoefficient(atof(argv[i + 1]), atof(argv[i + 2]), Mass);
 //        std::cout << "reset contact properties of lightest Particle (mass=" << Mass << ") to k=" << speciesHandler.getObject(0)->getStiffness() << " and dissipation_=" << speciesHandler.getObject(0)->getDissipation() << std::endl;
 //        i += 1;
 //    }
 //    else if (!strcmp(argv[i], "-tc_eps"))
 //    {
 //        Mdouble Mass = getLightestParticleMass();
 //        speciesHandler.getObject(0)->setCollisionTimeAndRestitutionCoefficient(atof(argv[i + 1]), atof(argv[i + 2]), Mass);
 //        std::cout << "reset contact properties of lightest Particle (mass=" << Mass << ") to k=" << speciesHandler.getObject(0)->getStiffness() << " and dissipation_=" << speciesHandler.getObject(0)->getDissipation() << std::endl;
 //        i += 1;
 //    }
 //    else if (!strcmp(argv[i], "-tc_eps_beta"))
 //    {
 //        Mdouble Mass = getLightestParticleMass();
 //        FrictionalSpecies* S = dynamic_cast<FrictionalSpecies*>(speciesHandler.getObject(0));
 //        S->setCollisionTimeAndNormalAndTangentialRestitutionCoefficient(atof(argv[i + 1]), atof(argv[i + 2]), atof(argv[i + 3]), Mass);
 //        std::cout << "reset contact properties of lightest Particle (mass=" << Mass << ") to k=" << S->getStiffness() << ", dissipation_=" << S->getDissipation() << ", kt=" << S->getSlidingStiffness() << " and dispt=" << S->getSlidingDissipation() << std::endl;
 //        i += 2;
 //    }
     else
         return Mercury3D::readNextArgument(i, argc, argv); //if argv[i] is not found, check the commands in Mercury3D
     return true; //returns true if argv[i] is found
 }
References i, MercuryBase::readNextArgument(), setChuteAngle(), setChuteLength(), setChuteWidth(), setFixedParticleRadius(), setInflowHeight(), setInflowParticleRadius(), setInflowVelocity(), setMaxFailed(), setRoughBottomType(), DPMBase::setZMax(), compute_granudrum_aor::str, and oomph::Global_string_for_annotation::string().
Referenced by AxisymmetricHopper::readNextArgument(), Funnel::readNextArgument(), SilbertPeriodic::readNextArgument(), ChuteWithHopper::readNextArgument(), and GranularJet::readNextArgument().
setChuteAngle()
void Chute::setChuteAngle (Mdouble chuteAngle)
Sets gravity vector according to chute angle (in degrees)
Sets the angle of the chute as compared to the horizontal (i.e., the normal to gravity). NB: since the X and Z directions are defined to be parallel and normal to the chute bottom respectively, this function effectively sets the GRAVITY angle.
Parameters
[in] chuteAngle the angle of the chute relative to the horizontal plane in DEGREES.
Todo:
would a check on the angle be beneficial to check if it is indeed in degrees?
 {
     // retrieve the magnitude of gravity
     Mdouble gravity = getGravity().getLength();
     if (gravity == 0)
     {
         logger(WARN, "[Chute::setChuteAngle()] zero gravity");
     }
     // reset the gravity vector, with the given angle
     setChuteAngleAndMagnitudeOfGravity(chuteAngle, gravity);
 }
References DPMBase::getGravity(), Vec3D::getLength(), logger, setChuteAngleAndMagnitudeOfGravity(), and WARN.
Referenced by Chutebelt::actionsAfterTimeStep(), LawinenBox::actionsBeforeTimeStep(), constructor(), main(), ChuteBottom::makeRoughBottom(), readNextArgument(), LawinenBox::rotateChute(), FlowRule::run(), vibratedBed::run(), SilbertPeriodic::set_study(), ChutePeriodic::setup(), and SingleParticleSegregation::SingleParticleSegregation().
setChuteAngleAndMagnitudeOfGravity()
void Chute::setChuteAngleAndMagnitudeOfGravity (Mdouble chuteAngle, Mdouble gravity)
Sets gravity vector according to chute angle (in degrees)
Sets the angle of the chute as compared to the horizontal (i.e., the normal to gravity), as well as the magnitude of gravity. NB: since the X and Z directions are defined to be parallel and normal to the chute bottom, respectively, this function effectively sets the GRAVITY angle.
Parameters
[in] chuteAngle the angle of the chute relative to the horizontal plane in DEGREES
[in] gravity magnitude of the gravity vector
 {
     if (chuteAngle >= -90.0 && chuteAngle <= 90.0)
     {
         chuteAngle_ = chuteAngle * constants::pi / 180.0;
         setGravity(Vec3D(sin(chuteAngle_), 0.0, -cos(chuteAngle_)) * gravity);
     }
     else
     {
         logger(WARN, "[Chute::setChuteAngleAndMagnitudeOfGravity()] Chute "
                      "angle must be within [-90,90]");
     }
 }
References chuteAngle_, cos(), logger, constants::pi, DPMBase::setGravity(), sin(), and WARN.
Referenced by AngleOfRepose::AngleOfRepose(), main(), setChuteAngle(), and SilbertPeriodic::SilbertPeriodic().
setChuteLength()
void Chute::setChuteLength (Mdouble chuteLength) virtual
Sets the chute length (X-direction)
Sets the length of the chute. Actually sets xMax_, while xMin_ is assumed to have stayed 0.
Parameters
[in] chuteLength length of the chute
Reimplemented in ChuteWithHopper.
 {
     setXMax(chuteLength);
 }
References DPMBase::setXMax().
Referenced by ChutePeriodicDemo::ChutePeriodicDemo(), main(), readNextArgument(), ChutePeriodic::setup(), SilbertPeriodic::SilbertPeriodic(), and SingleParticleSegregation::SingleParticleSegregation().
setChuteWidth()
void Chute::setChuteWidth (Mdouble chuteWidth)
Sets the chute width (Y-direction)
Sets the width of the chute. Actually sets yMax_, while it assumes yMin_ to have stayed 0.
Parameters
[in] chuteWidth width of the chute
 {
     setYMax(chuteWidth);
 }
References DPMBase::setYMax().
Referenced by AngleOfRepose::AngleOfRepose(), ChutePeriodicDemo::ChutePeriodicDemo(), main(), readNextArgument(), ChutePeriodic::setup(), SilbertPeriodic::SilbertPeriodic(), and SingleParticleSegregation::SingleParticleSegregation().
setFixedParticleRadius()
void Chute::setFixedParticleRadius (Mdouble fixedParticleRadius)
Sets the particle radius of the fixed particles which constitute the (rough) chute bottom.
Sets the radius of the fixed particles at the bottom (in case of a rough bottom; see also Chute::createBottom()).
Parameters
[in] fixedParticleRadius The radius of the fixed particles on the bottom as an MDouble.
 {
     if (fixedParticleRadius >= 0.0)
     {
         fixedParticleRadius_ = fixedParticleRadius;
     }
     else
     {
         logger(WARN, "[Chute::setFixedParticleRadius()] Fixed particle radius "
                      "must be greater than or equal to zero.");
     }
 }
References fixedParticleRadius_, logger, and WARN.
Referenced by AngleOfRepose::AngleOfRepose(), ChutePeriodicDemo::ChutePeriodicDemo(), constructor(), LawinenBox::LawinenBox(), main(), ChuteBottom::makeRoughBottom(), readNextArgument(), Cstatic2d::set_particle_properties(), Cstatic3D::set_particle_properties(), AngleOfRepose::set_study(), SilbertPeriodic::set_study(), FlowRule::setPolydispersity(), ChutePeriodic::setup(), SilbertPeriodic::SilbertPeriodic(), SingleParticleSegregation::SingleParticleSegregation(), and statistics_while_running< T >::statistics_while_running().
setFixedParticleSpacing()
void Chute::setFixedParticleSpacing (Mdouble fixedParticleSpacing)
Sets the spacing of the fixed particles which constitute the (rough) chute bottom; used in triangular packing only.
Sets the spacing of the fixed particles at the bottom (used in triangular packing only), which is defined as: spacing = particle center-center distance / particle diameter - 1 (Jing PRE 2016).
Parameters
[in] fixedParticleSpacing The spacing of the fixed particles on the bottom as an MDouble.
 {
     if (fixedParticleSpacing >= 0.0)
     {
         fixedParticleSpacing_ = fixedParticleSpacing;
     }
     else
     {
         logger(WARN, "[Chute::setFixedParticleSpacing()] Fixed particle spacing "
                      "must be greater than or equal to zero.");
     }
 }
References fixedParticleSpacing_, logger, and WARN.
setInflowHeight()
void Chute::setInflowHeight (Mdouble inflowHeight)
Sets maximum inflow height (Z-direction)
Sets the maximum height in Z-direction at which particles are introduced into the chute.
Parameters
[in] inflowHeight the maximum inflow height to be set
 {
     //if (inflowHeight >= minInflowParticleRadius_ + maxInflowParticleRadius_)
     {
         inflowHeight_ = inflowHeight;
         setZMax(1.2 * inflowHeight_);
     }
 //    else
 //    {
 //        std::cerr << "WARNING : Inflow height not changed to " << inflowHeight << ", value must be greater than or equal to diameter of inflow particle" << std::endl;
 //    }
 }
References inflowHeight_, and DPMBase::setZMax().
Referenced by ChutePeriodic::add_flow_particles(), SilbertPeriodic::add_flow_particles(), addFlowParticlesCompactly(), ChutePeriodicDemo::ChutePeriodicDemo(), constructor(), ChuteBottom::makeRoughBottom(), readNextArgument(), FlowRule::run(), vibratedBed::run(), AngleOfRepose::set_H(), SilbertPeriodic::set_H(), SilbertPeriodic::set_study(), SingleParticleSegregation::SingleParticleSegregation(), and Funnel::update_funnel().
setInflowParticleRadius() [1/2]
void Chute::setInflowParticleRadius (Mdouble inflowParticleRadius)
Sets the radius of the inflow particles to a single one (i.e. ensures a monodisperse inflow).
Sets the radius of particles flowing in at the start of the chute to be constant and the given one (i.e., the minimum and maximum allowed radius are set equal to each other and the argument).
Parameters
[in] inflowParticleRadius the radius of the particles entering the chute
 {
     if (inflowParticleRadius >= 0.0)
     {
         minInflowParticleRadius_ = inflowParticleRadius;
         maxInflowParticleRadius_ = inflowParticleRadius;
     }
     else
     {
         logger(WARN, "[Chute::setInflowParticleRadius(Mdouble)] Inflow "
                      "particle must be greater than or equal to zero");
     }
 }
References logger, maxInflowParticleRadius_, minInflowParticleRadius_, and WARN.
Referenced by AngleOfRepose::AngleOfRepose(), ChutePeriodicDemo::ChutePeriodicDemo(), constructor(), FlowRule::createBottom(), createBottom(), LawinenBox::LawinenBox(), main(), readNextArgument(), Cstatic2d::set_particle_properties(), Cstatic3D::set_particle_properties(), ChutePeriodic::setup(), SilbertPeriodic::SilbertPeriodic(), SingleParticleSegregation::SingleParticleSegregation(), and statistics_while_running< T >::statistics_while_running().
setInflowParticleRadius() [2/2]
void Chute::setInflowParticleRadius (Mdouble minInflowParticleRadius, Mdouble maxInflowParticleRadius)
Sets the minimum and maximum radius of the inflow particles.
Sets the minimum and maximum radius possible of particles entering the chute.
Parameters
[in] minInflowParticleRadius the minimum radius
[in] maxInflowParticleRadius the maximum radius
 {
     if (minInflowParticleRadius >= 0.0)
     {
         minInflowParticleRadius_ = minInflowParticleRadius;
     }
     else
     {
         logger(WARN, "[Chute::setInflowParticleRadius(Mdouble,Mdouble)] Min."
                      "inflow particle radius must be nonnegative");
     }
     if (maxInflowParticleRadius >= minInflowParticleRadius)
     {
         maxInflowParticleRadius_ = maxInflowParticleRadius;
     }
     else
     {
         logger(WARN, "[Chute::setInflowParticleRadius(Mdouble,Mdouble)] Max."
                      " inflow particle radius must be >= min. inflow particle "
                      "radius");
     }
 }
References logger, maxInflowParticleRadius_, minInflowParticleRadius_, and WARN.
setInflowVelocity()
void Chute::setInflowVelocity (Mdouble inflowVelocity)
Sets the average inflow velocity.
Sets the mean velocity at which the particles enter the chute
Parameters
[in] inflowVelocity the mean velocity at which the particles enter the chute
 {
     if (inflowVelocity >= 0.0)
     {
         inflowVelocity_ = inflowVelocity;
     }
     else
     {
         logger(WARN, "[Chute::setInflowVelocity()] Inflow velocity not changed, "
                      "value must be greater than or equal to zero");
     }
 }
References inflowVelocity_, logger, and WARN.
Referenced by ChuteWithContraction::ChuteWithContraction(), constructor(), readNextArgument(), and SilbertPeriodic::SilbertPeriodic().
setInflowVelocityVariance()
void Chute::setInflowVelocityVariance (Mdouble inflowVelocityVariance)
Sets the inflow velocity variance.
Sets the variance of the velocities of the inflow particles around the mean
Parameters
[in] inflowVelocityVariance the variance of the velocities of the inflow particles around the mean (expressed in ratio of the mean, i.e. the inflowVelocity_).
 {
     if (inflowVelocityVariance >= 0.0 && inflowVelocityVariance <= 1.0)
     {
         inflowVelocityVariance_ = inflowVelocityVariance;
     }
     else
     {
         logger(ERROR, "[Chute::setInflowVelocityVariance()] Inflow velocity "
                       "variance not changed, value must be within [0,1]");
         exit(-1);
     }
 }
References ERROR, inflowVelocityVariance_, and logger.
Referenced by constructor().
setInsertionBoundary()
void Chute::setInsertionBoundary (InsertionBoundary * insertionBoundary)
Sets the chute insertion boundary.
Sets the insertion boundary of the chute.
Parameters
[in] insertionBoundary the insertion boundary of the chute
 {
     insertionBoundary_ = insertionBoundary;
 }
References insertionBoundary_.
Referenced by ChuteWithHopper::setupInitialConditions().
setMaxFailed()
void Chute::setMaxFailed (unsigned int maxFailed)
Sets the number of times a particle will be tried to be added to the insertion boundary.
Sets the number of times that the boundary may fail to insert a particle,before the boundary is considered filled.
Parameters
[in] maxFailed The number of times that the boundary may fail to insert a particle
 {
     maxFailed_ = maxFailed;
 }
References maxFailed_.
Referenced by constructor(), readNextArgument(), and ChutePeriodic::setup().
setMaxInflowParticleRadius()
void Chute::setMaxInflowParticleRadius (Mdouble maxInflowParticleRadius)
Sets the maximum radius of inflow particles.
Sets the maximum radius possible of particles entering the chute.
Parameters
[in] maxInflowParticleRadius the maximum radius
 {
     if (maxInflowParticleRadius >= minInflowParticleRadius_)
     {
         maxInflowParticleRadius_ = maxInflowParticleRadius;
     }
     else
     {
         logger(WARN, "[Chute::setMaxInflowParticleRadius()] Max. inflow particle"
                      " radius must be >= min. inflow particle radius");
     }
 }
References logger, maxInflowParticleRadius_, minInflowParticleRadius_, and WARN.
Referenced by FlowRule::setPolydispersity().
setMinInflowParticleRadius()
void Chute::setMinInflowParticleRadius (Mdouble minInflowParticleRadius)
sets the minimum radius of inflow particles
Sets the minimum radius possible of particles entering the chute.
Parameters
[in] minInflowParticleRadius the minimum radius
 {
     if (minInflowParticleRadius <= maxInflowParticleRadius_)
     {
         minInflowParticleRadius_ = minInflowParticleRadius;
     }
     else
     {
         logger(WARN, "[Chute::setMinInflowParticleRadius()] Min. inflow particle"
                      " radius must be <= max. inflow particle radius");
     }
 }
References logger, maxInflowParticleRadius_, minInflowParticleRadius_, and WARN.
Referenced by FlowRule::setPolydispersity().
setRoughBottomType() [1/2]
void Chute::setRoughBottomType (RoughBottomType roughBottomType)
Sets the type of rough bottom of the chute.
Sets the roughBottomType_. Possible choices are defined by the enum RoughBottomType, which is defined in Chute.h:
MONOLAYER_ORDERED: Bottom will be a rectangularly ordered monolayer of particles
MONOLAYER_DISORDERED: Bottom will be a disordered monolayer of particles
MULTILAYER: Bottom will be a multilayer of particles
FLAT: Flat bottom. See also the documentation of Chute::createBottom().
Parameters
[in] roughBottomType The bottom type to be set
 {
     roughBottomType_ = roughBottomType;
 }
References roughBottomType_.
Referenced by AngleOfRepose::AngleOfRepose(), ChutePeriodicDemo::ChutePeriodicDemo(), constructor(), main(), ChuteBottom::makeRoughBottom(), read(), readNextArgument(), ChutePeriodic::setup(), SilbertPeriodic::SilbertPeriodic(), SingleParticleSegregation::SingleParticleSegregation(), SilbertHstop::solve_analytic(), and vibratedBed::vibratedBed().
setRoughBottomType() [2/2]
void Chute::setRoughBottomType (std::string roughBottomTypeString)
Sets the type of rough bottom of the chute, using a string with the EXACT enum type as input.
Same as Chute::setRoughBottomType(RoughBottomType roughBottomType), but takes a string identical to the RoughBottomType as an argument instead.
Todo:
: logger::Fatal seems very strong here, maybe set a default instead?
 {
     if (!roughBottomTypeString.compare("MONOLAYER_ORDERED"))
     {
         roughBottomType_ = MONOLAYER_ORDERED;
     }
     else if (!roughBottomTypeString.compare("MONOLAYER_DISORDERED"))
     {
         roughBottomType_ = MONOLAYER_ORDERED;
     }
     else if (!roughBottomTypeString.compare("MULTILAYER"))
     {
         roughBottomType_ = MONOLAYER_ORDERED;
     }
     else if (roughBottomTypeString == "FLAT")
     {
         roughBottomType_ = FLAT;
     }
     else
     {
         logger(FATAL, "[Chute::setRoughBottomType(std::string)] Invalid "
                       "argument in setRoughBottomType. Given: %",
                roughBottomTypeString);
     }
 }
References FATAL, FLAT, logger, MONOLAYER_ORDERED, and roughBottomType_.
setupInitialConditions()
void Chute::setupInitialConditions () override virtual
Creates bottom, side walls and a particle insertion boundary.
Adds side walls, a bottom and a particle insertion boundary
Reimplemented from DPMBase.
Reimplemented in ChuteWithHopper, and ChuteBottom.
 {
     if (speciesHandler.getNumberOfObjects() == 0)
     {
         logger(FATAL, "[Chute::setupInitialConditions()] Chute % cannot "
                       "complete because no species have been defined.", getName());
     }
     // create the chute's side walls in Y-direction
     // (which are solid if the chute is not periodic)
     setupSideWalls();
     // create a particle of which (altered) copies will fill the chute insertion
     // boundary
     SphericalParticle* particleToInsert = new SphericalParticle;
     // by default, insert particles of species 0
     particleToInsert->setSpecies(speciesHandler.getObject(0));
     if (speciesHandler.getNumberOfObjects() > 0)
     {
         particleToInsert->setSpecies(speciesHandler.getObject(0));
     }
     else
     {
         logger(ERROR, "There is not yet a species defined");
     }
     PSD psd;
     psd.setDistributionUniform(getMinInflowParticleRadius(), getMaxInflowParticleRadius(), 50);
     // set up the insertion boundary and add to handler
     ChuteInsertionBoundary b1;
     b1.set(particleToInsert, maxFailed_, Vec3D(getXMin(), getYMin(), getZMin()),
            Vec3D(getXMax(), getYMax(), getZMax()), fixedParticleRadius_, inflowVelocity_,
            inflowVelocityVariance_);
     b1.setPSD(psd);
     insertionBoundary_ = boundaryHandler.copyAndAddObject(b1);
     //creates the bottom of the chute
     createBottom();
 }
References DPMBase::boundaryHandler, BaseHandler< T >::copyAndAddObject(), createBottom(), ERROR, FATAL, fixedParticleRadius_, getMaxInflowParticleRadius(), getMinInflowParticleRadius(), DPMBase::getName(), BaseHandler< T >::getNumberOfObjects(), BaseHandler< T >::getObject(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), DPMBase::getZMax(), DPMBase::getZMin(), inflowVelocity_, inflowVelocityVariance_, insertionBoundary_, logger, maxFailed_, ChuteInsertionBoundary::set(), PSD::setDistributionUniform(), InsertionBoundary::setPSD(), BaseParticle::setSpecies(), setupSideWalls(), and DPMBase::speciesHandler.
Referenced by ChutePeriodic::setupInitialConditions(), Vreman::setupInitialConditions(), ChutePeriodicDemo::setupInitialConditions(), ChuteWithWedge::setupInitialConditions(), SegregationPeriodic::setupInitialConditions(), Chutebelt::setupInitialConditions(), and SingleParticleSegregation::setupInitialConditions().
setupSideWalls()
void Chute::setupSideWalls ()
Creates chute side walls (either solid or periodic)
Create side walls (i.e., in the Y-direction), which can be either periodic (if isChutePeriodic_ is TRUE), or solid (if isChutePeriodic_ is FALSE).
 {
     // check if walls should be periodic or solid
     if (isChutePeriodic_)
     {
         // create a periodic boundary with walls at yMin_ and yMax_.
         PeriodicBoundary b0;
         b0.set(Vec3D(0.0, 1.0, 0.0), getYMin(), getYMax());
         boundaryHandler.copyAndAddObject(b0);
     }
     else
     {
         // create two infinite solid walls; one at yMin_...
         InfiniteWall w0;
         w0.setSpecies(speciesHandler.getObject(0));
         w0.set(Vec3D(0.0, -1.0, 0.0), Vec3D(0, getYMin(), 0));
         wallHandler.copyAndAddObject(w0);
         // ... and one at yMax_.
         w0.set(Vec3D(0.0, 1.0, 0.0), Vec3D(0, getYMax(), 0));
         wallHandler.copyAndAddObject(w0);
     }
 }
References DPMBase::boundaryHandler, BaseHandler< T >::copyAndAddObject(), BaseHandler< T >::getObject(), DPMBase::getYMax(), DPMBase::getYMin(), isChutePeriodic_, PeriodicBoundary::set(), InfiniteWall::set(), BaseWall::setSpecies(), DPMBase::speciesHandler, and DPMBase::wallHandler.
Referenced by setupInitialConditions(), and ChuteWithHopper::setupInitialConditions().
write()
void Chute::write (std::ostream & os, bool writeAllParticles = true) const override virtual
This function writes the Chute properties to an ostream, and adds the properties of ALL chute particles as well.
Writes object's properties to an ostream, usually a restart file, but it can also for example write to the screen by passing std::cout as the ostream.
Parameters
[in] os the ostream to which the properties have to be written.
[in] writeAllParticles If TRUE, the properties of ALL particles in the particleHandler are written to the ostream. If FALSE, only the properties of the first two particles in the handler are written to the ostream (see DPMBase::write(std::ostream& os, bool writeAllParticles)). The default value is true.
Reimplemented from DPMBase.
Reimplemented in ChuteWithHopper.
 {
     MercuryBase::write(os, writeAllParticles);
     os << "FixedParticleRadius " << fixedParticleRadius_
        << " MinInflowParticleRadius " << minInflowParticleRadius_
        << " MaxInflowParticleRadius " << maxInflowParticleRadius_
        << " RoughBottomType " << roughBottomType_
        << " ChuteAngle " << chuteAngle_
        << " MaxFailed " << maxFailed_
        << " NumCreated " << (insertionBoundary_ ? insertionBoundary_->getNumberOfParticlesInserted() : 0)
        << " InflowVelocity " << inflowVelocity_
        << " InflowVelocityVariance " << inflowVelocityVariance_
        << " InflowHeight " << inflowHeight_ << std::endl;
 }
References chuteAngle_, fixedParticleRadius_, InsertionBoundary::getNumberOfParticlesInserted(), inflowHeight_, inflowVelocity_, inflowVelocityVariance_, insertionBoundary_, maxFailed_, maxInflowParticleRadius_, minInflowParticleRadius_, roughBottomType_, and MercuryBase::write().
Referenced by SilbertPeriodic::add_flow_particles(), ChuteWithPeriodicInflowAndContraction::ChuteWithPeriodicInflowAndContraction(), ContractionWithPeriodicInflow::ContractionWithPeriodicInflow(), main(), ChuteWithContraction::setup_particles_initial_conditions(), ChutePeriodic::setupInitialConditions(), Cstatic2d::setupInitialConditions(), Cstatic3D::setupInitialConditions(), CLiveStatistics< T >::setupInitialConditions(), statistics_while_running< T >::setupInitialConditions(), Funnel::write(), and ChuteWithHopper::write().
Member Data Documentation
chuteAngle_
Mdouble Chute::chuteAngle_ private
chute angle in degrees
Referenced by getChuteAngle(), getChuteAngleDegrees(), read(), setChuteAngleAndMagnitudeOfGravity(), and write().
fixedParticleRadius_
Mdouble Chute::fixedParticleRadius_ private
radius of the fixed particles at the bottom
Referenced by getFixedParticleRadius(), read(), setFixedParticleRadius(), setupInitialConditions(), and write().
fixedParticleSpacing_
Mdouble Chute::fixedParticleSpacing_ private
spacing of the fixed particles at the bottom (center distance / diameter - 1)
Referenced by getFixedParticleSpacing(), and setFixedParticleSpacing().
inflowHeight_
Mdouble Chute::inflowHeight_ private
Height of inflow.
Referenced by getInflowHeight(), read(), setInflowHeight(), and write().
inflowVelocity_
Mdouble Chute::inflowVelocity_ private
Average inflow velocity in x-direction.
Referenced by getInflowVelocity(), read(), setInflowVelocity(), setupInitialConditions(), and write().
inflowVelocityVariance_
Mdouble Chute::inflowVelocityVariance_ private
Inflow velocity variance in x-direction (in ratio of inflowVelocity_)
Referenced by getInflowVelocityVariance(), read(), setInflowVelocityVariance(), setupInitialConditions(), and write().
insertionBoundary_
InsertionBoundary* Chute::insertionBoundary_ private
(Pointer to) the Chute's insertion boundary
Referenced by constructor(), setInsertionBoundary(), setupInitialConditions(), and write().
isChutePeriodic_
bool Chute::isChutePeriodic_ private
Determines whether the chute has periodic (TRUE) or solid (FALSE) walls in the Y-direction.
Referenced by constructor(), getIsPeriodic(), makeChutePeriodic(), and setupSideWalls().
maxFailed_
unsigned int Chute::maxFailed_ private
indicates how many attempts are made to insert a new particle into the insertion boundary before the boundary is considered filled.
Referenced by getMaxFailed(), read(), setMaxFailed(), setupInitialConditions(), and write().
maxInflowParticleRadius_
Mdouble Chute::maxInflowParticleRadius_ private
maximal radius of inflowing particles
Referenced by getInflowParticleRadius(), getMaxInflowParticleRadius(), read(), setInflowParticleRadius(), setMaxInflowParticleRadius(), setMinInflowParticleRadius(), and write().
minInflowParticleRadius_
Mdouble Chute::minInflowParticleRadius_ private
minimal radius of inflowing particles
Referenced by getInflowParticleRadius(), getMinInflowParticleRadius(), read(), setInflowParticleRadius(), setMaxInflowParticleRadius(), setMinInflowParticleRadius(), and write().
roughBottomType_
RoughBottomType Chute::roughBottomType_ private
Determines the type of rough bottom created (if any). See also the enum RoughBottomType at the beginning of this header file.
Referenced by createBottom(), getRoughBottomType(), setRoughBottomType(), and write().
The documentation for this class was generated from the following files:
Chute.h
Chute.cc