MercuryDPM: Eigen::ArrayWrapper< ExpressionType > Class Template Reference
Eigen::ArrayWrapper< ExpressionType > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Expression of a mathematical vector or matrix as an array object.
#include <ArrayWrapper.h>
Public Types
typedef ArrayBase< ArrayWrapper > Base
typedef internal::remove_all_t< ExpressionType > NestedExpression
typedef std::conditional_t< internal::is_lvalue< ExpressionType >::value, Scalar, const Scalar > ScalarWithConstIfNotLvalue
typedef internal::ref_selector< ExpressionType >::non_const_type NestedExpressionType
Public Types inherited from Eigen::ArrayBase< ArrayWrapper< ExpressionType > >
typedef ArrayBase StorageBaseType
typedef ArrayBase Eigen_BaseClassForSpecializationOfGlobalMathFuncImpl
typedef internal::traits< ArrayWrapper< ExpressionType > >::StorageKind StorageKind
typedef internal::traits< ArrayWrapper< ExpressionType > >::Scalar Scalar
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef NumTraits< Scalar >::Real RealScalar
typedef DenseBase< ArrayWrapper< ExpressionType > > Base
typedef Base::CoeffReturnType CoeffReturnType
typedef Base::PlainObject PlainObject
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, PlainObject > ConstantReturnType
Public Types inherited from Eigen::DenseBase< Derived >
enum {
RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime , ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime , SizeAtCompileTime = (internal::size_of_xpr_at_compile_time<Derived>::ret) , MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime , MaxSizeAtCompileTime , IsVectorAtCompileTime , NumDimensions ,
Flags = internal::traits<Derived>::Flags , IsRowMajor = int(Flags) & RowMajorBit , InnerSizeAtCompileTime , InnerStrideAtCompileTime = internal::inner_stride_at_compile_time<Derived>::ret ,
OuterStrideAtCompileTime = internal::outer_stride_at_compile_time<Derived>::ret
}
enum { IsPlainObjectBase = 0 }
typedef Eigen::InnerIterator< Derived > InnerIterator
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::StorageIndex StorageIndex
The type used to store indices.
typedef internal::traits< Derived >::Scalar Scalar
typedef Scalar value_type
typedef NumTraits< Scalar >::Real RealScalar
typedef DenseCoeffsBase< Derived, internal::accessors_level< Derived >::value > Base
typedef Base::CoeffReturnType CoeffReturnType
typedef internal::find_best_packet< Scalar, SizeAtCompileTime >::type PacketScalar
typedef Matrix< typename internal::traits< Derived >::Scalar, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime, AutoAlign|(internal::traits< Derived >::Flags &RowMajorBit ? RowMajor :ColMajor), internal::traits< Derived >::MaxRowsAtCompileTime, internal::traits< Derived >::MaxColsAtCompileTime > PlainMatrix
typedef Array< typename internal::traits< Derived >::Scalar, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime, AutoAlign|(internal::traits< Derived >::Flags &RowMajorBit ? RowMajor :ColMajor), internal::traits< Derived >::MaxRowsAtCompileTime, internal::traits< Derived >::MaxColsAtCompileTime > PlainArray
typedef std::conditional_t< internal::is_same< typename internal::traits< Derived >::XprKind, MatrixXpr >::value, PlainMatrix, PlainArray > PlainObject
The plain matrix or array type corresponding to this expression.
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, PlainObject > ConstantReturnType
typedef CwiseNullaryOp< internal::scalar_zero_op< Scalar >, PlainObject > ZeroReturnType
typedef CwiseNullaryOp< internal::linspaced_op< Scalar >, PlainObject > RandomAccessLinSpacedReturnType
typedef CwiseNullaryOp< internal::equalspaced_op< Scalar >, PlainObject > RandomAccessEqualSpacedReturnType
typedef Matrix< typename NumTraits< typename internal::traits< Derived >::Scalar >::Real, internal::traits< Derived >::ColsAtCompileTime, 1 > EigenvaluesReturnType
typedef Transpose< Derived > TransposeReturnType
typedef Transpose< const Derived > ConstTransposeReturnType
typedef internal::add_const_on_value_type_t< typename internal::eval< Derived >::type > EvalReturnType
typedef VectorwiseOp< Derived, Horizontal > RowwiseReturnType
typedef const VectorwiseOp< const Derived, Horizontal > ConstRowwiseReturnType
typedef VectorwiseOp< Derived, Vertical > ColwiseReturnType
typedef const VectorwiseOp< const Derived, Vertical > ConstColwiseReturnType
typedef CwiseNullaryOp< internal::scalar_random_op< Scalar >, PlainObject > RandomReturnType
typedef Reverse< Derived, BothDirections > ReverseReturnType
typedef const Reverse< const Derived, BothDirections > ConstReverseReturnType
typedef std::conditional_t<(Flags &DirectAccessBit)==DirectAccessBit, internal::pointer_based_stl_iterator< Derived >, internal::generic_randaccess_stl_iterator< Derived > > iterator_type
typedef std::conditional_t<(Flags &DirectAccessBit)==DirectAccessBit, internal::pointer_based_stl_iterator< const Derived >, internal::generic_randaccess_stl_iterator< const Derived > > const_iterator_type
typedef std::conditional_t< IsVectorAtCompileTime, iterator_type, void > iterator
typedef std::conditional_t< IsVectorAtCompileTime, const_iterator_type, void > const_iterator
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ArrayWrapper (ExpressionType &matrix)
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index outerStride () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index innerStride () const EIGEN_NOEXCEPT
constexpr EIGEN_DEVICE_FUNC ScalarWithConstIfNotLvalue * data ()
constexpr EIGEN_DEVICE_FUNC const Scalar * data () const
EIGEN_DEVICE_FUNC const Scalar & coeffRef (Index rowId, Index colId) const
EIGEN_DEVICE_FUNC const Scalar & coeffRef (Index index) const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC const internal::remove_all_t< NestedExpressionType > & nestedExpression () const
EIGEN_DEVICE_FUNC void resize (Index newSize)
EIGEN_DEVICE_FUNC void resize (Index rows, Index cols)
Public Member Functions inherited from Eigen::ArrayBase< ArrayWrapper< ExpressionType > >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ArrayWrapper< ExpressionType > & operator= (const ArrayBase &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ArrayWrapper< ExpressionType > & operator= (const Scalar &value)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ArrayWrapper< ExpressionType > & operator= (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ArrayWrapper< ExpressionType > & operator= (const DenseBase &other)
EIGEN_DEVICE_FUNC ArrayWrapper< ExpressionType > & operator= (const EigenBase< OtherDerived > &other)
Copies the generic expression other into *this.
EIGEN_DEVICE_FUNC ArrayWrapper< ExpressionType > & operator= (const ReturnByValue< OtherDerived > &func)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ArrayWrapper< ExpressionType > & operator+= (const Scalar &scalar)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ArrayWrapper< ExpressionType > & operator+= (const ArrayBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC ArrayWrapper< ExpressionType > & operator+= (const EigenBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ArrayWrapper< ExpressionType > & operator-= (const Scalar &scalar)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ArrayWrapper< ExpressionType > & operator-= (const ArrayBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC ArrayWrapper< ExpressionType > & operator-= (const EigenBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ArrayWrapper< ExpressionType > & operator*= (const ArrayBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ArrayWrapper< ExpressionType > & operator*= (const Scalar &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ArrayWrapper< ExpressionType > & operator/= (const ArrayBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ArrayWrapper< ExpressionType > & operator/= (const Scalar &other)
EIGEN_DEVICE_FUNC ArrayBase< ArrayWrapper< ExpressionType > > & array ()
EIGEN_DEVICE_FUNC const ArrayBase< ArrayWrapper< ExpressionType > > & array () const
EIGEN_DEVICE_FUNC MatrixWrapper< ArrayWrapper< ExpressionType > > matrix ()
EIGEN_DEVICE_FUNC const MatrixWrapper< const ArrayWrapper< ExpressionType > > matrix () const
EIGEN_DEPRECATED EIGEN_DEVICE_FUNC ArrayWrapper< ExpressionType > & lazyAssign (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ArrayWrapper< ExpressionType > & lazyAssign (const DenseBase< OtherDerived > &other)
Public Member Functions inherited from Eigen::DenseBase< Derived >
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index outerSize () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index innerSize () const
EIGEN_DEVICE_FUNC void resize (Index newSize)
EIGEN_DEVICE_FUNC void resize (Index rows, Index cols)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const EigenBase< OtherDerived > &other)
Copies the generic expression other into *this.
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator+= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator-= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const ReturnByValue< OtherDerived > &func)
template<typename OtherDerived >
EIGEN_DEPRECATED EIGEN_DEVICE_FUNC Derived & lazyAssign (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC CommaInitializer< Derived > operator<< (const Scalar &s)
template<unsigned int Added, unsigned int Removed>
EIGEN_DEPRECATED const Derived & flagged () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC CommaInitializer< Derived > operator<< (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC TransposeReturnType transpose ()
EIGEN_DEVICE_FUNC const ConstTransposeReturnType transpose () const
EIGEN_DEVICE_FUNC void transposeInPlace ()
EIGEN_DEVICE_FUNC void fill (const Scalar &value)
EIGEN_DEVICE_FUNC Derived & setConstant (const Scalar &value)
EIGEN_DEVICE_FUNC Derived & setLinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
EIGEN_DEVICE_FUNC Derived & setLinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
EIGEN_DEVICE_FUNC Derived & setEqualSpaced (Index size, const Scalar &low, const Scalar &step)
EIGEN_DEVICE_FUNC Derived & setEqualSpaced (const Scalar &low, const Scalar &step)
EIGEN_DEVICE_FUNC Derived & setZero ()
EIGEN_DEVICE_FUNC Derived & setOnes ()
EIGEN_DEVICE_FUNC Derived & setRandom ()
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool isApprox (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const RealScalar &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isApproxToConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isZero (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isOnes (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool hasNaN () const
EIGEN_DEVICE_FUNC bool allFinite () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator*= (const Scalar &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator/= (const Scalar &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EvalReturnType eval () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void swap (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void swap (PlainObjectBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC const NestByValue< Derived > nestByValue () const
EIGEN_DEVICE_FUNC const ForceAlignedAccess< Derived > forceAlignedAccess () const
EIGEN_DEVICE_FUNC ForceAlignedAccess< Derived > forceAlignedAccess ()
template<bool Enable>
EIGEN_DEVICE_FUNC const std::conditional_t< Enable, ForceAlignedAccess< Derived >, Derived & > forceAlignedAccessIf () const
template<bool Enable>
EIGEN_DEVICE_FUNC std::conditional_t< Enable, ForceAlignedAccess< Derived >, Derived & > forceAlignedAccessIf ()
EIGEN_DEVICE_FUNC Scalar sum () const
EIGEN_DEVICE_FUNC Scalar mean () const
EIGEN_DEVICE_FUNC Scalar trace () const
EIGEN_DEVICE_FUNC Scalar prod () const
template<int NaNPropagation>
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff () const
template<int NaNPropagation>
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff () const
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff () const
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff () const
template<int NaNPropagation, typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *row, IndexType *col) const
template<int NaNPropagation, typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *row, IndexType *col) const
template<int NaNPropagation, typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *index) const
template<int NaNPropagation, typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *index) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *index) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *index) const
template<typename BinaryOp >
EIGEN_DEVICE_FUNC Scalar redux (const BinaryOp &func) const
template<typename Visitor >
EIGEN_DEVICE_FUNC void visit (Visitor &func) const
const WithFormat< Derived > format (const IOFormat &fmt) const
EIGEN_DEVICE_FUNC CoeffReturnType value () const
EIGEN_DEVICE_FUNC bool all () const
EIGEN_DEVICE_FUNC bool any () const
EIGEN_DEVICE_FUNC Index count () const
EIGEN_DEVICE_FUNC ConstRowwiseReturnType rowwise () const
EIGEN_DEVICE_FUNC RowwiseReturnType rowwise ()
EIGEN_DEVICE_FUNC ConstColwiseReturnType colwise () const
EIGEN_DEVICE_FUNC ColwiseReturnType colwise ()
template<typename ThenDerived , typename ElseDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ThenDerived >::Scalar, typename DenseBase< ElseDerived >::Scalar, Scalar >, ThenDerived, ElseDerived, Derived > select (const DenseBase< ThenDerived > &thenMatrix, const DenseBase< ElseDerived > &elseMatrix) const
template<typename ThenDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ThenDerived >::Scalar, typename DenseBase< ThenDerived >::Scalar, Scalar >, ThenDerived, typename DenseBase< ThenDerived >::ConstantReturnType, Derived > select (const DenseBase< ThenDerived > &thenMatrix, const typename DenseBase< ThenDerived >::Scalar &elseScalar) const
template<typename ElseDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ElseDerived >::Scalar, typename DenseBase< ElseDerived >::Scalar, Scalar >, typename DenseBase< ElseDerived >::ConstantReturnType, ElseDerived, Derived > select (const typename DenseBase< ElseDerived >::Scalar &thenScalar, const DenseBase< ElseDerived > &elseMatrix) const
template<int p>
RealScalar lpNorm () const
template<int RowFactor, int ColFactor>
EIGEN_DEVICE_FUNC const Replicate< Derived, RowFactor, ColFactor > replicate () const
EIGEN_DEVICE_FUNC const Replicate< Derived, Dynamic, Dynamic > replicate (Index rowFactor, Index colFactor) const
EIGEN_DEVICE_FUNC ReverseReturnType reverse ()
EIGEN_DEVICE_FUNC ConstReverseReturnType reverse () const
EIGEN_DEVICE_FUNC void reverseInPlace ()
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
const_iterator end () const
const_iterator cend () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & lazyAssign (const DenseBase< OtherDerived > &other)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (const CustomNullaryOp &func)
template<typename Derived >
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const typename NumTraits< Scalar >::Real &other, const RealScalar &prec) const
template<typename Func >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar redux (const Func &func) const
template<typename ThenDerived , typename ElseDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ThenDerived >::Scalar, typename DenseBase< ElseDerived >::Scalar, typename DenseBase< Derived >::Scalar >, ThenDerived, ElseDerived, Derived > select (const DenseBase< ThenDerived > &thenMatrix, const DenseBase< ElseDerived > &elseMatrix) const
template<typename ThenDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ThenDerived >::Scalar, typename DenseBase< ThenDerived >::Scalar, typename DenseBase< Derived >::Scalar >, ThenDerived, typename DenseBase< ThenDerived >::ConstantReturnType, Derived > select (const DenseBase< ThenDerived > &thenMatrix, const typename DenseBase< ThenDerived >::Scalar &elseScalar) const
template<typename ElseDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ElseDerived >::Scalar, typename DenseBase< ElseDerived >::Scalar, typename DenseBase< Derived >::Scalar >, typename DenseBase< ElseDerived >::ConstantReturnType, ElseDerived, Derived > select (const typename DenseBase< ElseDerived >::Scalar &thenScalar, const DenseBase< ElseDerived > &elseMatrix) const
Protected Attributes
NestedExpressionType m_expression
Additional Inherited Members
Static Public Member Functions inherited from Eigen::DenseBase< Derived >
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (Index rows, Index cols, const Scalar &value)
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (Index size, const Scalar &value)
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (const Scalar &value)
EIGEN_DEPRECATED static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (Sequential_t, Index size, const Scalar &low, const Scalar &high)
EIGEN_DEPRECATED static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (Sequential_t, const Scalar &low, const Scalar &high)
static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
static EIGEN_DEVICE_FUNC const RandomAccessEqualSpacedReturnType EqualSpaced (Index size, const Scalar &low, const Scalar &step)
static EIGEN_DEVICE_FUNC const RandomAccessEqualSpacedReturnType EqualSpaced (const Scalar &low, const Scalar &step)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (const CustomNullaryOp &func)
static EIGEN_DEVICE_FUNC const ZeroReturnType Zero (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const ZeroReturnType Zero (Index size)
static EIGEN_DEVICE_FUNC const ZeroReturnType Zero ()
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones (Index size)
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones ()
static const RandomReturnType Random (Index rows, Index cols)
static const RandomReturnType Random (Index size)
static const RandomReturnType Random ()
Public Attributes inherited from Eigen::DenseBase< Derived >
EIGEN_DEPRECATED typedef CwiseNullaryOp< internal::linspaced_op< Scalar >, PlainObject > SequentialLinSpacedReturnType
Protected Member Functions inherited from Eigen::ArrayBase< ArrayWrapper< ExpressionType > >
ArrayWrapper< ExpressionType > & operator+= (const MatrixBase< OtherDerived > &)
ArrayWrapper< ExpressionType > & operator-= (const MatrixBase< OtherDerived > &)
Protected Member Functions inherited from Eigen::DenseBase< Derived >
constexpr EIGEN_DEVICE_FUNC DenseBase ()=default
Related Functions inherited from Eigen::ArrayBase< ArrayWrapper< ExpressionType > >
EIGEN_DEVICE_FUNC const GlobalUnaryPowReturnType< ArrayWrapper< ExpressionType >, ScalarExponent > pow (const Eigen::ArrayBase< ArrayWrapper< ExpressionType > > &x, const ScalarExponent &exponent)
const Eigen::CwiseBinaryOp< Eigen::internal::scalar_pow_op< typename Derived::Scalar, typename ExponentDerived::Scalar >, const ArrayWrapper< ExpressionType >, const ExponentDerived > pow (const Eigen::ArrayBase< ArrayWrapper< ExpressionType > > &x, const Eigen::ArrayBase< ExponentDerived > &exponents)
#define EIGEN_SCALAR_BINARYOP_EXPR_RETURN_TYPE(SCALAR, EXPR, OPNAME)
Related Functions inherited from Eigen::DenseBase< Derived >
template<typename Derived >
std::ostream & operator<< (std::ostream &s, const DenseBase< Derived > &m)
Detailed Description
template<typename ExpressionType>
class Eigen::ArrayWrapper< ExpressionType >
Expression of a mathematical vector or matrix as an array object.
This class is the return type of MatrixBase::array(), and most of the time this is the only way it is use.
See also
MatrixBase::array(), class MatrixWrapper
Member Typedef Documentation
Base
template<typename ExpressionType > typedef ArrayBase<ArrayWrapper> Eigen::ArrayWrapper< ExpressionType >::Base
NestedExpression
template<typename ExpressionType > typedef internal::remove_all_t<ExpressionType> Eigen::ArrayWrapper< ExpressionType >::NestedExpression
NestedExpressionType
template<typename ExpressionType > typedef internal::ref_selector<ExpressionType>::non_const_type Eigen::ArrayWrapper< ExpressionType >::NestedExpressionType
ScalarWithConstIfNotLvalue
template<typename ExpressionType > typedef std::conditional_t<internal::is_lvalue<ExpressionType>::value, Scalar, const Scalar> Eigen::ArrayWrapper< ExpressionType >::ScalarWithConstIfNotLvalue
Constructor & Destructor Documentation
ArrayWrapper()
template<typename ExpressionType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::ArrayWrapper< ExpressionType >::ArrayWrapper (ExpressionType & matrix) inline explicit
 : m_expression(matrix) {}
Member Function Documentation
coeffRef() [1/2]
template<typename ExpressionType > EIGEN_DEVICE_FUNC const Scalar& Eigen::ArrayWrapper< ExpressionType >::coeffRef (Index index) const inline
 { return m_expression.coeffRef(index); }
References Eigen::ArrayWrapper< ExpressionType >::m_expression.
coeffRef() [2/2]
template<typename ExpressionType > EIGEN_DEVICE_FUNC const Scalar& Eigen::ArrayWrapper< ExpressionType >::coeffRef (Index rowId, Index colId) const inline
{
     return m_expression.coeffRef(rowId, colId);
   }
References Eigen::ArrayWrapper< ExpressionType >::m_expression.
cols()
template<typename ExpressionType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::ArrayWrapper< ExpressionType >::cols () const inline
 { return m_expression.cols(); }
References Eigen::ArrayWrapper< ExpressionType >::m_expression.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::ArrayWrapper< ExpressionType >::resize(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
data() [1/2]
template<typename ExpressionType > constexpr EIGEN_DEVICE_FUNC ScalarWithConstIfNotLvalue* Eigen::ArrayWrapper< ExpressionType >::data () inline constexpr
 { return m_expression.data(); }
References Eigen::ArrayWrapper< ExpressionType >::m_expression.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
data() [2/2]
template<typename ExpressionType > constexpr EIGEN_DEVICE_FUNC const Scalar* Eigen::ArrayWrapper< ExpressionType >::data () const inline constexpr
 { return m_expression.data(); }
References Eigen::ArrayWrapper< ExpressionType >::m_expression.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
evalTo()
template<typename ExpressionType > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::ArrayWrapper< ExpressionType >::evalTo (Dest & dst) const inline
{
     dst = m_expression;
   }
References Eigen::ArrayWrapper< ExpressionType >::m_expression.
innerStride()
template<typename ExpressionType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::ArrayWrapper< ExpressionType >::innerStride () const inline
{
     return m_expression.innerStride();
   }
References Eigen::ArrayWrapper< ExpressionType >::m_expression.
nestedExpression()
template<typename ExpressionType > EIGEN_DEVICE_FUNC const internal::remove_all_t<NestedExpressionType>& Eigen::ArrayWrapper< ExpressionType >::nestedExpression () const inline
{
     return m_expression;
   }
References Eigen::ArrayWrapper< ExpressionType >::m_expression.
outerStride()
template<typename ExpressionType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::ArrayWrapper< ExpressionType >::outerStride () const inline
{
     return m_expression.outerStride();
   }
References Eigen::ArrayWrapper< ExpressionType >::m_expression.
resize() [1/2]
template<typename ExpressionType > EIGEN_DEVICE_FUNC void Eigen::ArrayWrapper< ExpressionType >::resize (Index newSize) inline
Forwards the resizing request to the nested expression
See also
DenseBase::resize(Index)
 { m_expression.resize(newSize); }
References Eigen::ArrayWrapper< ExpressionType >::m_expression.
resize() [2/2]
template<typename ExpressionType > EIGEN_DEVICE_FUNC void Eigen::ArrayWrapper< ExpressionType >::resize (Index rows, Index cols) inline
Forwards the resizing request to the nested expression
See also
DenseBase::resize(Index,Index)
 { m_expression.resize(rows, cols); }
References Eigen::ArrayWrapper< ExpressionType >::cols(), Eigen::ArrayWrapper< ExpressionType >::m_expression, and Eigen::ArrayWrapper< ExpressionType >::rows().
rows()
template<typename ExpressionType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::ArrayWrapper< ExpressionType >::rows () const inline
 { return m_expression.rows(); }
References Eigen::ArrayWrapper< ExpressionType >::m_expression.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::ArrayWrapper< ExpressionType >::resize(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_expression
template<typename ExpressionType > NestedExpressionType Eigen::ArrayWrapper< ExpressionType >::m_expression protected
Referenced by Eigen::ArrayWrapper< ExpressionType >::coeffRef(), Eigen::ArrayWrapper< ExpressionType >::cols(), Eigen::ArrayWrapper< ExpressionType >::data(), Eigen::ArrayWrapper< ExpressionType >::evalTo(), Eigen::ArrayWrapper< ExpressionType >::innerStride(), Eigen::ArrayWrapper< ExpressionType >::nestedExpression(), Eigen::ArrayWrapper< ExpressionType >::outerStride(), Eigen::ArrayWrapper< ExpressionType >::resize(), and Eigen::ArrayWrapper< ExpressionType >::rows().
The documentation for this class was generated from the following file:
ArrayWrapper.h