MercuryDPM: ScrewsymmetricIntersectionOfWalls Class Reference
ScrewsymmetricIntersectionOfWalls Class Reference
Use ScrewsymmetricIntersectionOfWalls to define screwsymmetric walls, such as cylinders, cones, etc.
#include <ScrewsymmetricIntersectionOfWalls.h>
Public Member Functions
ScrewsymmetricIntersectionOfWalls ()
Default constructor.
ScrewsymmetricIntersectionOfWalls (const ScrewsymmetricIntersectionOfWalls &p)
Copy constructor.
ScrewsymmetricIntersectionOfWalls (Vec3D position, Vec3D normal, std::vector< normalAndPosition > walls, const ParticleSpecies *species)
Constructor setting values.
~ScrewsymmetricIntersectionOfWalls () override
Destructor.
ScrewsymmetricIntersectionOfWalls & operator= (const ScrewsymmetricIntersectionOfWalls &other)
Copy assignment operator.
ScrewsymmetricIntersectionOfWalls * copy () const final
Wall copy method. It calls the copy constructor of this Wall, useful for polymorphism.
bool getDistanceAndNormal (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return) const final
Computes the distance from the wall for a given BaseParticle and returns true if there is a collision. If there is a collision, also return the normal vector.
void computeNormalRadialDeltaN (const Vec3D &positionLabFrame, Vec3D &normalVector, Vec3D &radialVector, Mdouble &deltaN) const
Mdouble computeDeltaZ (const Vec3D &positionLabFrame, Mdouble h, Mdouble pitch) const
void read (std::istream &is) final
reads wall
void write (std::ostream &os) const final
outputs wall
std::string getName () const final
Returns the name of the object.
void setAxis (Vec3D a)
void convertLimits (Vec3D &min, Vec3D &max) const
void writeVTK (VTKContainer &vtk) const override
void setRightHandedness (bool rightHandedness)
bool getRightHandedness () const
void setPitch (Mdouble pitch)
Mdouble getPitch () const
void setThickness (Mdouble thickness)
Mdouble getThickness () const
void setLength (Mdouble length)
Mdouble getLength () const
Public Member Functions inherited from IntersectionOfWalls
IntersectionOfWalls ()
Default constructor.
IntersectionOfWalls (const IntersectionOfWalls &other)
Copy constructor.
IntersectionOfWalls (const std::vector< normalAndPosition > &walls, const ParticleSpecies *species)
Constructor setting values.
~IntersectionOfWalls () override
Destructor.
IntersectionOfWalls & operator= (const IntersectionOfWalls &other)
void clear ()
Removes all parts of the walls.
void setSpecies (const ParticleSpecies *species)
sets species of subwalls as well
void setHandler (WallHandler *wallHandler) override
A function which sets the WallHandler for this BaseWall.
unsigned int getNumberOfObjects ()
Returns the number of objects.
void addObject (Vec3D normal, Vec3D point)
Adds a wall to the set of infinite walls, given a normal vector pointing into the wall (i.e. out of the simulation domain), going through the point, so that normal*x=normal*point.
void addObject (Quaternion orientation, Vec3D position)
void add3PointObject (Vec3D PointA, Vec3D PointB, Vec3D PointC)
void setPointsAndLines (unsigned int n)
void addTetraSTL (Vec3D PointA, Vec3D PointB, Vec3D PointC, Vec3D WallNormal, Mdouble Thickness, int wallidentifier)
constructs a tetrahedron for an STL file input
void addTetra (const Vec3D &PointA, const Vec3D &PointB, const Vec3D &PointC, Mdouble &Thickness)
constructs a tetrahedron from 3 input coordinates
void addPlate (const Vec3D &PointA, const Vec3D &PointB, const Vec3D &PointC, const Vec3D &WallNormal, const Mdouble &Thickness, int wallidentifier)
MERCURYDPM_DEPRECATED void addObject (Vec3D normal, Mdouble position)
Adds a wall to the set of finite walls, given an normal vector pointing into the wall (i.e. out of the flow domain), to give a plane defined by normal*x=position.
void createOpenPrism (std::vector< Vec3D > points, Vec3D prismAxis)
Creates an open prism which is a polygon between the points, except the first and last point, and extends infinitely in the PrismAxis direction. Note that if you view from inside of your geometry, the shape formed by points has to be convex, otherwise it will not create the wall correctly.
void createPrism (std::vector< Vec3D > points, Vec3D prismAxis)
Creates an open prism which is a polygon between the points and extends infinitely in the PrismAxis direction. Note that if you view from inside of your geometry, the shape formed by points has to be convex, otherwise it will not create the wall correctly.
void createOpenPrism (std::vector< Vec3D > points)
Creates an open prism which is a polygon between the points, except the first and last point, and extends infinitely in the direction perpendicular to the first and second wall. Note that if you view from inside of your geometry, the shape formed by points has to be convex, otherwise it will not create the wall correctly.
void createPrism (std::vector< Vec3D > points)
Creates an open prism which is a polygon between the points and extends infinitely in the direction perpendicular to the first and second wall. Note that if you view from inside of your geometry, the shape formed by points has to be convex, otherwise it will not create the wall correctly.
bool getDistanceAndNormal (const Vec3D &position, Mdouble wallInteractionRadius, Mdouble &distance, Vec3D &normal_return) const
Compute the distance from the wall for a given BaseParticle and return if there is an interaction. If there is an interaction, also return the normal vector.
Public Member Functions inherited from BaseWall
BaseWall ()
Default constructor.
BaseWall (const BaseWall &w)
Copy constructor.
~BaseWall () override
Default destructor.
virtual bool getDistanceNormalOverlap (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual bool getDistanceNormalOverlapSuperquadric (const SuperQuadricParticle &p, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual Vec3D getFurthestPointSuperQuadric (const Vec3D &normalBodyFixed, const Vec3D &axes, Mdouble eps1, Mdouble eps2) const
WallHandler * getHandler () const
A function which returns the WallHandler that handles this BaseWall.
void setIndSpecies (unsigned int indSpecies) override
Define the species of this wall using the index of the species in the SpeciesHandler in this DPMBase.
void setSpecies (const ParticleSpecies *species)
Defines the species of the current wall.
bool isFixed () const override
void setForceControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity={0, 0, 0})
Slowly adjusts the force on a wall towards a specified goal, by adjusting (prescribing) the velocity of the wall.
virtual bool isLocal (Vec3D &min, Vec3D &max) const
bool getLinePlaneIntersect (Vec3D &intersect, const Vec3D &p0, const Vec3D &p1, const Vec3D &n, const Vec3D &p)
bool isInsideWallVTK (const Vec3D &point, const Vec3D &normal, const Vec3D &position) const
void projectOntoWallVTK (Vec3D &point0, const Vec3D &point1, const Vec3D &normal, const Vec3D &position) const
void intersectVTK (std::vector< Vec3D > &points, Vec3D normal, Vec3D position) const
virtual BaseInteraction * getInteractionWithSuperQuad (SuperQuadricParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler)
void getVTK (std::vector< Vec3D > &points, std::vector< std::vector< double >> &triangleStrips)
const Vec3D getAxis () const
BaseInteraction * getInteractionWith (BaseParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler) override
Returns the interaction between this wall and a given particle, nullptr if there is no interaction.
virtual void actionsOnRestart ()
No implementation but can be overidden in its derived classes.
virtual void actionsAfterParticleGhostUpdate ()
No implementation but can be overidden in its derived classes.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
virtual void handleParticleRemoval (unsigned int id)
Handles the addition of particles to the particleHandler.
virtual void checkInteractions (InteractionHandler *interactionHandler, unsigned int timeStamp)
Check if all interactions are valid.
bool getVTKVisibility () const
void setVTKVisibility (bool vtkVisibility)
void addRenderedWall (BaseWall *w)
BaseWall * getRenderedWall (size_t i) const
std::vector< BaseWall * > getRenderedWalls () const
void removeRenderedWalls ()
void renderWall (VTKContainer &vtk)
void addParticlesAtWall (unsigned numElements=50)
void setVelocityControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity)
virtual void writeWallDetailsVTK (VTKData &data) const
virtual void computeWear ()
Public Member Functions inherited from BaseInteractable
BaseInteractable ()
Default BaseInteractable constructor.
BaseInteractable (const BaseInteractable &p)
Copy constructor.
~BaseInteractable () override
Destructor, it simply destructs the BaseInteractable and all the objects it contains.
unsigned int getIndSpecies () const
Returns the index of the species associated with the interactable object.
const ParticleSpecies * getSpecies () const
Returns a pointer to the species of this BaseInteractable.
void setSpecies (const ParticleSpecies *species)
Sets the species of this BaseInteractable.
const Vec3D & getForce () const
Returns the force on this BaseInteractable.
const Vec3D & getTorque () const
Returns the torque on this BaseInteractable.
void setForce (const Vec3D &force)
Sets the force on this BaseInteractable.
void setTorque (const Vec3D &torque)
Sets the torque on this BaseInteractable.
void addForce (const Vec3D &addForce)
Adds an amount to the force on this BaseInteractable.
void addTorque (const Vec3D &addTorque)
Adds an amount to the torque on this BaseInteractable.
virtual void resetForceTorque (int numberOfOMPthreads)
void sumForceTorqueOMP ()
const Vec3D & getPosition () const
Returns the position of this BaseInteractable.
const Quaternion & getOrientation () const
Returns the orientation of this BaseInteractable.
virtual void setPosition (const Vec3D &position)
Sets the position of this BaseInteractable.
void setOrientationViaNormal (Vec3D normal)
Sets the orientation of this BaseInteractable by defining the vector that results from the rotation of the (1,0,0) vector.
void setOrientationViaEuler (Vec3D eulerAngle)
Sets the orientation of this BaseInteractable by defining the euler angles.
virtual void setOrientation (const Quaternion &orientation)
Sets the orientation of this BaseInteractable.
virtual void move (const Vec3D &move)
Moves this BaseInteractable by adding an amount to the position.
virtual void rotate (const Vec3D &angularVelocityDt)
Rotates this BaseInteractable.
const std::vector< BaseInteraction * > & getInteractions () const
Returns a list of interactions which belong to this interactable.
void addInteraction (BaseInteraction *I)
Adds an interaction to this BaseInteractable.
bool removeInteraction (BaseInteraction *I)
Removes an interaction from this BaseInteractable.
void copyInteractionsForPeriodicParticles (const BaseInteractable &p)
Copies interactions to this BaseInteractable whenever a periodic copy made.
void setVelocity (const Vec3D &velocity)
set the velocity of the BaseInteractable.
void setAngularVelocity (const Vec3D &angularVelocity)
set the angular velocity of the BaseInteractble.
void addVelocity (const Vec3D &velocity)
adds an increment to the velocity.
void addAngularVelocity (const Vec3D &angularVelocity)
add an increment to the angular velocity.
virtual const Vec3D & getVelocity () const
Returns the velocity of this interactable.
virtual const Vec3D & getAngularVelocity () const
Returns the angular velocity of this interactable.
void setPrescribedPosition (const std::function< Vec3D(double)> &prescribedPosition)
Allows the position of an infinite mass interactable to be prescribed.
void applyPrescribedPosition (double time)
Computes the position from the user defined prescribed position function.
void setPrescribedVelocity (const std::function< Vec3D(double)> &prescribedVelocity)
Allows the velocity of an infinite mass interactable to be prescribed.
void applyPrescribedVelocity (double time)
Computes the velocity from the user defined prescribed velocity function.
void setPrescribedOrientation (const std::function< Quaternion(double)> &prescribedOrientation)
Allows the orientation of the infinite mass interactbale to be prescribed.
void applyPrescribedOrientation (double time)
Computes the orientation from the user defined prescribed orientation function.
void setPrescribedAngularVelocity (const std::function< Vec3D(double)> &prescribedAngularVelocity)
Allows the angular velocity of the infinite mass interactable to be prescribed.
void applyPrescribedAngularVelocity (double time)
Computes the angular velocity from the user defined prescribed angular velocity.
virtual const Vec3D getVelocityAtContact (const Vec3D &contact) const
Returns the velocity at the contact point, use by many force laws.
void integrateBeforeForceComputation (double time, double timeStep)
This is part of integrate routine for objects with infinite mass.
void integrateAfterForceComputation (double time, double timeStep)
This is part of the integration routine for objects with infinite mass.
virtual Mdouble getInvMass () const
virtual Mdouble getCurvature (const Vec3D &labFixedCoordinates) const
virtual bool isFaceContact (const Vec3D &normal) const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Public Attributes
bool rightHandedness_ = true
The right handedness of the screw, i.e. the direction of the screw-blade.
Private Attributes
Mdouble pitch_ = 1
Mdouble thickness_ = 0
The thickness of the screw blade.
Mdouble length_ = 1
The length of the screw.
Additional Inherited Members
Static Public Member Functions inherited from BaseWall
static void addToVTK (const std::vector< Vec3D > &points, VTKContainer &vtk)
Takes the points provided and adds a triangle strip connecting these points to the vtk container.
Protected Attributes inherited from IntersectionOfWalls
std::vector< InfiniteWall > wallObjects_
The wall "segments"/directions that together make up the finite wall.
std::vector< Vec3D > C_
A vector that stores the intersection point of three different InfiniteWall.
Detailed Description
Use ScrewsymmetricIntersectionOfWalls to define screwsymmetric walls, such as cylinders, cones, etc.
An ScrewsymmetricIntersectionOfWalls is equivalent to an IntersectionOfWalls where the Cartesian coordinate system (x,y,z) is replaced by a cylindrical coordinate system \((\hat{r},\theta,\hat{z})\). The origin and orientation of the cylindrical coordinate system is defined by the position and orientation of the wall, respectively.
In other words, a particle touches an ScrewsymmetricIntersectionOfWalls, if it touches the IntersectionOfWalls object in the \((r,\theta,z)\) coordinate system.
Thus, you need to define:
the position p of the wall, which is also the origin of the cylindrical coordinate system
the orientation o of the wall, which is the \(\hat{z}\) direction of the cylindrical coordinate system
a set of walls in the \((\hat{r},\theta,\hat{z})\) coordinate system, defined by a normal n and position p. Only screwsymmetric objects can be defined, thus the \(\theta \) value of the normals has to be zero.
Example 1
Say you want to define a cylindrical wall as in the left image below. If you define the origin and orientation of the cylindrical coordinate system as *(0,0,0)* and *(0,0,1)*, respectively, then the cylinder is a rectangle in the cylindrical coordinate system. Thus, you need to intersect three walls, with normals and position as indicated in the right figure below.
A cylindric wall that repels particles
The following code defines such a cylinder:
ScrewsymmetricIntersectionOfWalls w;
w.setSpecies(species);
w.setPosition(Vec3D(0,0,0));
w.setOrientation(Vec3D(0,0,1));
//arguments of addObject are normal and position of the intersected walls
w.addObject(Vec3D(-1,0,0), Vec3D(1,0,0));  //Cylindric wall
w.addObject(Vec3D(0,0,1), Vec3D(.5,0,-1)); //Bottom wall
w.addObject(Vec3D(0,0,-1), Vec3D(.5,0,1)); //Top wall
wallHandler.copyAndAddObject(w);
Example 2
Note, one can also define a cylindric casing that can be filled with particles, see image below.
A cylindric casing that can be filled with particles
In this case, you don't have to intersect the walls; instead you need to create three separate walls. A sample code:
ScrewsymmetricIntersectionOfWalls w;
w.setSpecies(species);
w.setPosition(Vec3D(0,0,0));
w.setOrientation(Vec3D(0,0,1));
w.addObject(Vec3D(1,0,0), Vec3D(1,0,0));  //Cylindric wall
wallHandler.copyAndAddObject(w);
InfiniteWall w1;
w1.set(Vec3D(0,0,-1), Vec3D(0,0,-1)); //Bottom wall
wallHandler.copyAndAddObject(w1);
w1.set(Vec3D(0,0,1), Vec3D(0,0,1)); //Top wall
wallHandler.copyAndAddObject(w1);
Example 3
Say you want a cylindrical casing with an outflow at the base. In this case, you need to define three walls:
The outer cylinder of radius R, height H
The flat top wall
A bottom wall which is a outer cylinder of radius r<R, with a flat top wall at z=0
A cylindric casing that can be filled with particles
This can be done as follows:
double R = 2;
double H = 1;
double r = 1;
ScrewsymmetricIntersectionOfWalls w;
w.setSpecies(species);
w.setPosition(Vec3D(0,0,0));
w.setOrientation(Vec3D(0,0,1));
//normal and position of the outer shell in cylindrical coordinates
w.addObject(Vec3D(1,0,0), Vec3D(R,0,0));
wallHandler.copyAndAddObject(w);
InfiniteWall w1;
w1.set(Vec3D(0,0,1), Vec3D(0,0,H)); //Top wall
ScrewsymmetricIntersectionOfWalls w0;
w0.setSpecies(species);
w0.setPosition(Vec3D(0,0,0));
w0.setOrientation(Vec3D(0,0,1));
// bottom wall is an intersection of two walls, an outer cylinder of radius r and a flat top wall at z=0
w0.addObject(Vec3D(1,0,0), Vec3D(r,0,0));
w0.addObject(Vec3D(0,0,1), Vec3D(r,0,0));
wallHandler.copyAndAddObject(w0);
For a demonstration on how to use this class, see Flow through a 3D hourglass/silo.
Constructor & Destructor Documentation
ScrewsymmetricIntersectionOfWalls() [1/3]
ScrewsymmetricIntersectionOfWalls::ScrewsymmetricIntersectionOfWalls ()
Default constructor.
 {
     logger(ERROR, "ScrewsymmetricIntersectionOfWalls() is not yet completely implemented");
     logger(DEBUG, "ScrewsymmetricIntersectionOfWalls() finished");
 }
References DEBUG, ERROR, and logger.
Referenced by copy().
ScrewsymmetricIntersectionOfWalls() [2/3]
ScrewsymmetricIntersectionOfWalls::ScrewsymmetricIntersectionOfWalls (const ScrewsymmetricIntersectionOfWalls & other)
Copy constructor.
Parameters
[in] other The ScrewsymmetricIntersectionOfWalls that must be copied.
         : IntersectionOfWalls(other)
 {
     logger(ERROR, "ScrewsymmetricIntersectionOfWalls() is not yet completely implemented");
     logger(DEBUG, "ScrewsymmetricIntersectionOfWalls(const ScrewsymmetricIntersectionOfWalls &p) finished");
 }
References DEBUG, ERROR, and logger.
ScrewsymmetricIntersectionOfWalls() [3/3]
ScrewsymmetricIntersectionOfWalls::ScrewsymmetricIntersectionOfWalls (Vec3D position, Vec3D normal, std::vector< normalAndPosition > walls, const ParticleSpecies * species)
Constructor setting values.
         : IntersectionOfWalls(walls, species)
 {
     logger(ERROR, "ScrewsymmetricIntersectionOfWalls() is not yet completely implemented");
     setPosition(position);
     setOrientationViaNormal(orientation);
 }
References ERROR, logger, BaseInteractable::setOrientationViaNormal(), and BaseInteractable::setPosition().
~ScrewsymmetricIntersectionOfWalls()
ScrewsymmetricIntersectionOfWalls::~ScrewsymmetricIntersectionOfWalls () override
Destructor.
 {
     logger(DEBUG, "~ScrewsymmetricIntersectionOfWalls() finished.");
 }
References DEBUG, and logger.
Member Function Documentation
computeDeltaZ()
Mdouble ScrewsymmetricIntersectionOfWalls::computeDeltaZ (const Vec3D & positionLabFrame, Mdouble h, Mdouble pitch) const
Auxiliary function that computes the oriented axial distance between the particle's centre and the blade centre
Parameters
[in] positionLabFrame distance between the starting point of the screw, start_, and the particle position (Vec3D)
[in] h The rescaled length of the screw (length_/(2*pi*numberOfTurns_)) (Mdouble > 0)
[in] pitch The pitch length of the screw (length_/numberOfTurns_) (Mdouble > 0)
Returns
oriented axial distance between the particle's centre and the blade centre
 {
     // oriented axial distance between the particle's centre and the blade centre
     Mdouble deltaZ;
     // normal to the blade at the particle position
     if (rightHandedness_) // right-handed thread
     {
         // angular coordinate of the particle
         // IMPORTANT: this angle needs to be defined in the interval [0, +2*pi[ radians!
         Mdouble xi = atan2(positionLabFrame.Y, positionLabFrame.X);
         if (xi < 0.0)
             xi += 2.0 * constants::pi;
         deltaZ = fmod(positionLabFrame.Z - h * (xi + getOrientation().getAxis().Z) -
                       static_cast<int> (positionLabFrame.Z / pitch), pitch);
         logger(DEBUG, "xi: %, deltaZ: %", xi, deltaZ);
     }
     else // left-handed thread
     {
         // angular coordinate of the particle
         // IMPORTANT: this angle needs to be defined in the interval [0, +2*pi[ radians!
         Mdouble xi = atan2(-positionLabFrame.Y, positionLabFrame.X);
         if (xi < 0.0)
             xi += 2.0 * constants::pi;
         xi += 0.5 * constants::pi;
         xi = fmod(xi, 2.0 * constants::pi);
         deltaZ = fmod(positionLabFrame.Z - h * (xi + 0.5 * constants::pi - getOrientation().getAxis().Z) -
                       static_cast<int> (positionLabFrame.Z / pitch), pitch);
         logger(DEBUG, "xi: %, deltaZ: %", xi, deltaZ);
     }
     if (deltaZ > 0.5 * pitch)
     {
         deltaZ -= pitch;
     }
     else if (deltaZ < -0.5 * pitch)
     {
         deltaZ += pitch;
     }
     return deltaZ;
 }
References atan2(), DEBUG, Eigen::bfloat16_impl::fmod(), BaseWall::getAxis(), BaseInteractable::getOrientation(), logger, constants::pi, rightHandedness_, Vec3D::X, Vec3D::Y, Z, and Vec3D::Z.
Referenced by computeNormalRadialDeltaN().
computeNormalRadialDeltaN()
void ScrewsymmetricIntersectionOfWalls::computeNormalRadialDeltaN (const Vec3D & positionLabFrame, Vec3D & normalVector, Vec3D & radialVector, Mdouble & deltaN) const
Computes the normal and radial vector for the screw at the position of the particle. Furthermore, it also computes deltaN, which is component of the particle-blade centre distance normal to the blade surface
Parameters
[in] p particle whose position is used to compute the vectors and distance to the blade
[out] normalVector the vector in (x,y,z)-direction that points perpendicular to the screw blade
[out] radialVector the vector in (x,y)-direction that points outward from shaft to particle
[out] deltaN component of the particle-blade_center distance normal to the blade surface
 {
     // radial position of the particle
     const Mdouble rho = std::sqrt(positionLabFrame.X * positionLabFrame.X
                                   + positionLabFrame.Y * positionLabFrame.Y);
     // The rescaled length of the screw (length_/(2*pi*numberOfTurns_)).
     const Mdouble h = 0.5 * pitch_ / constants::pi;
     // The pitch length of the screw (length_/numberOfTurns_).
     const Mdouble deltaZ = computeDeltaZ(positionLabFrame, h, pitch_);
     // trigonometric functions relative to the particle angle
     const Mdouble cosXi = positionLabFrame.X / rho;
     const Mdouble sinXi = positionLabFrame.Y / rho;
     if (rightHandedness_)
     {
         normalVector.X = h * sinXi;
         normalVector.Y = -h * cosXi;
         normalVector.Z = rho;
     }
     else
     {
         normalVector.X = -h * cosXi;
         normalVector.Y = h * sinXi;
         normalVector.Z = rho;
     }
     // takes the right direction (+/-) of the vector and normalizes
     normalVector *= -deltaZ;
     normalVector /= normalVector.getLength();
     // radial vector at the particle position
     radialVector.X = cosXi;
     radialVector.Y = sinXi;
     radialVector.Z = 0.0;
     // The half-thickness of the screw.
     const Mdouble delta = 0.5 * thickness_;
     // cosine of the helix angle at the particle position
     const Mdouble cosEta = 1.0 / std::sqrt(1.0 + (h * h / rho / rho));
     // component of the particle-blade_center distance normal to the blade surface
     deltaN = fabs(deltaZ) * cosEta - delta;
 }
References computeDeltaZ(), MultiOpt::delta, boost::multiprecision::fabs(), Vec3D::getLength(), constants::pi, pitch_, rightHandedness_, sqrt(), thickness_, Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by getDistanceAndNormal().
convertLimits()
void ScrewsymmetricIntersectionOfWalls::convertLimits (Vec3D & min, Vec3D & max) const
converts XYZ limits into RZ limits, to properly limit the VTK plotting area.
 {
     Quaternion q = getOrientation();
     Vec3D rMin = min - getPosition();
     q.rotateBack(rMin); //set min/max initial values to values of first corner point
     Vec3D rMax = max - getPosition();
     q.rotateBack(rMax); //set min/max initial values to values of first corner point
     Mdouble r = std::sqrt(std::max(rMax.Y * rMax.Y + rMax.Z * rMax.Z, rMin.Y * rMin.Y + rMin.Z * rMin.Z));
     max = Vec3D(r, 0.001, std::max(rMin.X,rMax.X));
     min = Vec3D(0, 0, std::min(rMin.X,rMax.X));
     //std::cout << "r=" << r << std::endl;
 }
References BaseInteractable::getOrientation(), BaseInteractable::getPosition(), max, min, Eigen::numext::q, UniformPSDSelfTest::r, sqrt(), Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by writeVTK().
copy()
ScrewsymmetricIntersectionOfWalls * ScrewsymmetricIntersectionOfWalls::copy () const final virtual
Wall copy method. It calls the copy constructor of this Wall, useful for polymorphism.
Returns
pointer to a IntersectionOfWalls object allocated using new.
Reimplemented from IntersectionOfWalls.
 {
     return new ScrewsymmetricIntersectionOfWalls(*this);
 }
References ScrewsymmetricIntersectionOfWalls().
Referenced by operator=().
getDistanceAndNormal()
bool ScrewsymmetricIntersectionOfWalls::getDistanceAndNormal (const BaseParticle & p, Mdouble & distance, Vec3D & normal_return) const final virtual
Computes the distance from the wall for a given BaseParticle and returns true if there is a collision. If there is a collision, also return the normal vector.
First, the particle is translated by the vector position_, then the distance normal and tangential to the orientation is computed. This normal and tangential direction is interpreted as the x and z coordinate. With the particle shifted into the XZ plane, the distance and normal is computed, as if the ScrewsymmetricIntersectionOfWalls would be a simple IntersectionOfWalls. Finally, the object and the normal is rotated back to the original position.
See also ScrewsymmetricIntersectionOfWalls for details.
Reimplemented from IntersectionOfWalls.
 {
     // squared radial position of the particle
     const Vec3D positionLabFrame = p.getPosition() - getPosition();
     const Mdouble rho2 = positionLabFrame.X * positionLabFrame.X + positionLabFrame.Y * positionLabFrame.Y;
     // should thickness be added here?
     // const Mdouble wallInteractionRadius = p.getWallInteractionRadius(this) + thickness_;
     // if the particle is outside the cylinder containing the screw there is no collision
     if (//rho2 > square(rMax_ + wallInteractionRadius) ||
         positionLabFrame.Z > length_ + p.getWallInteractionRadius(this) ||
         positionLabFrame.Z < -p.getWallInteractionRadius(this))
     {
         return false;
     }
     Vec3D normalVector;
     Vec3D radialVector;
     Mdouble deltaN;
     // positionLabFrame = normalVector + radialVector + axialVector
     computeNormalRadialDeltaN(positionLabFrame, normalVector, radialVector, deltaN);
     // radial position of the particle
     const Mdouble r = std::sqrt(rho2);
     //determine wall distance, normal and contact in axissymmetric coordinates
     //and transform from axisymmetric coordinates
     Vec3D normalRN;
     if (!IntersectionOfWalls::getDistanceAndNormal(Vec3D(r, 0, deltaN), p.getWallInteractionRadius(this), distance, normalRN))
     {
         //if not in contact
         return false;
     }
     else
     {
         //if in contact
         if (r != 0)
             radialVector /= r;
         else //in this case the tangential vector is irrelevant
             logger(WARN, "Warning: Particle % is exactly on the symmetry axis of wall %", p.getIndex(), getIndex());
         //normal_Return = normalVector.Z * deltaN + normalVector.X * r;
         normal_return = normalRN.Z * normalVector + normalRN.X * radialVector;
         normal_return.normalise();
         return true;
     }
 }
References computeNormalRadialDeltaN(), IntersectionOfWalls::getDistanceAndNormal(), BaseObject::getIndex(), BaseInteractable::getPosition(), length_, logger, Vec3D::normalise(), p, UniformPSDSelfTest::r, sqrt(), WARN, Vec3D::X, Vec3D::Y, and Vec3D::Z.
getLength()
Mdouble ScrewsymmetricIntersectionOfWalls::getLength () const inline
 {return length_;}
References length_.
getName()
std::string ScrewsymmetricIntersectionOfWalls::getName () const final virtual
Returns the name of the object.
Returns
The string "ScrewsymmetricIntersectionOfWalls".
Reimplemented from IntersectionOfWalls.
 {
     return "ScrewsymmetricIntersectionOfWalls";
 }
getPitch()
Mdouble ScrewsymmetricIntersectionOfWalls::getPitch () const inline
 {return pitch_;}
References pitch_.
getRightHandedness()
bool ScrewsymmetricIntersectionOfWalls::getRightHandedness () const inline
 {return rightHandedness_;}
References rightHandedness_.
getThickness()
Mdouble ScrewsymmetricIntersectionOfWalls::getThickness () const inline
 {return thickness_;}
References thickness_.
operator=()
ScrewsymmetricIntersectionOfWalls & ScrewsymmetricIntersectionOfWalls::operator= (const ScrewsymmetricIntersectionOfWalls & other)
Copy assignment operator.
Parameters
[in] other The ScrewsymmetricIntersectionOfWalls that must be copied.
 {
     if (this == &other)
     {
         return *this;
     }
     else
     {
         return *(other.copy());
     }
 }
References copy().
read()
void ScrewsymmetricIntersectionOfWalls::read (std::istream & is) final virtual
reads wall
Parameters
[in] is The input stream from which the ScrewsymmetricIntersectionOfWalls is read, usually a restart file.
Reimplemented from IntersectionOfWalls.
 {
     IntersectionOfWalls::read(is);
 }
References IntersectionOfWalls::read().
setAxis()
void ScrewsymmetricIntersectionOfWalls::setAxis (Vec3D a)
 {
     setOrientationViaNormal(a);
 }
References a, and BaseInteractable::setOrientationViaNormal().
setLength()
void ScrewsymmetricIntersectionOfWalls::setLength (Mdouble length) inline
 {length_=length;}
References length_.
setPitch()
void ScrewsymmetricIntersectionOfWalls::setPitch (Mdouble pitch) inline
 {pitch_=pitch;}
References pitch_.
setRightHandedness()
void ScrewsymmetricIntersectionOfWalls::setRightHandedness (bool rightHandedness) inline
 {rightHandedness_=rightHandedness;}
References rightHandedness_.
setThickness()
void ScrewsymmetricIntersectionOfWalls::setThickness (Mdouble thickness) inline
 {thickness_=thickness;}
References thickness_.
write()
void ScrewsymmetricIntersectionOfWalls::write (std::ostream & os) const final virtual
outputs wall
Parameters
[in] os The output stream where the ScrewsymmetricIntersectionOfWalls must be written to, usually a restart file.
Reimplemented from IntersectionOfWalls.
 {
     IntersectionOfWalls::write(os);
 }
References IntersectionOfWalls::write().
writeVTK()
void ScrewsymmetricIntersectionOfWalls::writeVTK (VTKContainer & vtk) const override virtual
adds extra information to the points and triangleStrips vectors needed to plot the wall in vtk format
Parameters
points Coordinates of the vertices of the triangulated surfaces (in the VTK file this is called POINTS)
triangleStrips Indices of three vertices forming one triangulated surface (in the VTK file this is called CELL)
Bug:
once the quaternions are implemented, we can orient these walls properly
Reimplemented from IntersectionOfWalls.
 {
     for (auto wall = wallObjects_.begin(); wall != wallObjects_.end(); wall++)
     {
         //plot each of the intersecting walls
         std::vector<Vec3D> myPoints;
         //first create a slice of non-rotated wall in the xz plane, 0<y<1
         Vec3D min = getHandler()->getDPMBase()->getMin();
         Vec3D max = getHandler()->getDPMBase()->getMax();
         convertLimits(min, max);
         //create the basic slice for the first wall using the InfiniteWall routine
         wall->createVTK(myPoints, min, max);
         //create intersections with the other walls, similar to the IntersectionOfWalls routine
         for (auto other = wallObjects_.begin(); other != wallObjects_.end(); other++)
         {
             if (other != wall)
             {
                 intersectVTK(myPoints, -other->getNormal(), other->getPosition());
             }
         }
         //only keep the y=0 values
         std::vector<Vec3D> rzVec;
         for (auto& p: myPoints)
         {
             if (p.Y == 0)
             {
                 rzVec.push_back(p);
             }
         }
         if (rzVec.empty())
             return;
         //create points on the unit circle
         unsigned nr = 180;
         struct XY
         {
             double X;
             double Y;
         };
         std::vector<XY> xyVec;
         for (unsigned ir = 0; ir < nr; ir++)
         {
             Mdouble angle = 2.0 * constants::pi * ir / nr;
             xyVec.push_back({cos(angle), sin(angle)});
         }
         //now create rings of points on the axisym. shape
         unsigned long nPoints = vtk.points.size();
         Vec3D p;
         //Vec3D o = getOrientation().getAxis();
         for (auto rz : rzVec)
         {
             for (auto xy : xyVec)
             {
                 p = Vec3D(rz.Z, rz.X * xy.X, rz.X * xy.Y);
                 getOrientation().rotate(p);
                 p += getPosition();
                 vtk.points.push_back(p);
             }
         }
         //finally create the connectivity matri to plot shell-like triangle strips.
         unsigned long nz = rzVec.size();
         for (unsigned iz = 0; iz < nz - 1; iz++)
         {
             std::vector<double> cell;
             cell.reserve(2 * nr + 2);
             for (unsigned ir = 0; ir < nr; ir++)
             {
                 cell.push_back(nPoints + ir + iz * nr);
                 cell.push_back(nPoints + ir + (iz + 1) * nr);
             }
             cell.push_back(nPoints + iz * nr);
             cell.push_back(nPoints + (iz + 1) * nr);
             vtk.triangleStrips.push_back(cell);
         }
     }
 }
References Jeffery_Solution::angle(), convertLimits(), cos(), BaseHandler< T >::getDPMBase(), BaseWall::getHandler(), DPMBase::getMax(), DPMBase::getMin(), BaseInteractable::getOrientation(), BaseInteractable::getPosition(), BaseWall::intersectVTK(), max, min, Mesh_Parameters::nz, p, constants::pi, VTKContainer::points, Quaternion::rotate(), sin(), VTKContainer::triangleStrips, IntersectionOfWalls::wallObjects_, X, xy, XY, and Y.
Member Data Documentation
length_
Mdouble ScrewsymmetricIntersectionOfWalls::length_ = 1 private
The length of the screw.
Referenced by getDistanceAndNormal(), getLength(), and setLength().
pitch_
Mdouble ScrewsymmetricIntersectionOfWalls::pitch_ = 1 private
axial length of one rotation
Referenced by computeNormalRadialDeltaN(), getPitch(), and setPitch().
rightHandedness_
bool ScrewsymmetricIntersectionOfWalls::rightHandedness_ = true
The right handedness of the screw, i.e. the direction of the screw-blade.
Referenced by computeDeltaZ(), computeNormalRadialDeltaN(), getRightHandedness(), and setRightHandedness().
thickness_
Mdouble ScrewsymmetricIntersectionOfWalls::thickness_ = 0 private
The thickness of the screw blade.
Referenced by computeNormalRadialDeltaN(), getThickness(), and setThickness().
The documentation for this class was generated from the following files:
ScrewsymmetricIntersectionOfWalls.h
ScrewsymmetricIntersectionOfWalls.cc