MercuryDPM: LLT_example.cpp File Reference
LLT_example.cpp File Reference
Functions
MatrixXd A (3, 3)
A<< 4, -1, 2, -1, 6, 0, 2, 0, 5;cout<< "The matrix A is"<< endl<< A<< endl;LLT< MatrixXd > lltOfA (A)
Variables
MatrixXd L = lltOfA.matrixL()
Function Documentation
A()
MatrixXd A (3 , 3)
lltOfA()
A<< 4, -1, 2, -1, 6, 0, 2, 0, 5;cout << "The matrix A is" << endl << A << endl;LLT<MatrixXd> lltOfA (A)
Variable Documentation
L
MatrixXd L = lltOfA.matrixL()
Referenced by Eigen::internal::bicgstabl(), oomph::RefineableQElement< 1 >::build(), oomph::RefineableQElement< 3 >::check_integrity(), oomph::RefineableQElement< 1 >::check_integrity(), Eigen::internal::cm_factorize_p(), Eigen::internal::cm_factorize_p< SuiteSparse_long >(), Eigen::internal::cm_solve(), Eigen::internal::cm_solve< SuiteSparse_long >(), Eigen::internal::cm_spsolve(), Eigen::internal::cm_spsolve< SuiteSparse_long >(), ComplexHarmonicProblem< ELEMENT, EIGEN_SOLVER >::ComplexHarmonicProblem(), WearableNurbsWall::computeWear(), WearableTriangleMeshWall::computeWear(), WearableTriangulatedWall::computeWear(), oomph::OcTreeForest::construct_up_right_equivalents(), oomph::BinaryTreeRoot::direction_of_neighbour(), oomph::OcTreeRoot::direction_of_neighbour(), oomph::OcTree::doc_face_neighbours(), oomph::BinaryTree::doc_neighbours(), oomph::OcTree::edge_neighbour_is_face_neighbour(), ElasticRefineableQuarterCircleSectorMesh< ELEMENT >::ElasticRefineableQuarterCircleSectorMesh(), ElasticRingProblem< ELEMENT >::ElasticRingProblem(), UnsteadyHeatProblem< ELEMENT >::enforce_time_periodic_boundary_conditions(), mathsFunc::exp(), oomph::OcTree::faces_of_common_edge(), oomph::BinaryTreeForest::find_neighbours(), oomph::OcTreeForest::find_neighbours(), FSIRingProblem::FSIRingProblem(), oomph::RefineableQElement< 3 >::get_face_bcs(), oomph::RefineableSolidQElement< 3 >::get_face_solid_bcs(), oomph::BinaryTree::gteq_edge_neighbour(), oomph::OcTree::gteq_face_neighbour(), HarmonicProblem< ELEMENT, EIGEN_SOLVER >::HarmonicProblem(), Eigen::internal::idrstabl(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::init_matrix(), oomph::RefineableQElement< 3 >::interpolated_zeta_on_face(), mathsFunc::log(), Flag_definition::lower_tip(), oomph::WarpedCubeDomain::macro_element_boundary(), oomph::QuarterPipeDomain::macro_element_boundary(), oomph::QuarterTubeDomain::macro_element_boundary(), oomph::TubeDomain::macro_element_boundary(), oomph::EighthSphereDomain::macro_element_boundary(), main(), Eigen::CholmodSupernodalLLT< MatrixType_, UpLo_ >::matrixL(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::node_created_by_neighbour(), oomph::RefineableQElement< 3 >::node_created_by_neighbour(), oomph::RefineableQElement< 1 >::node_created_by_neighbour(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::node_created_by_son_of_neighbour(), oomph::OcTreeForest::oc_face_neigh_pt(), oomph::RefineableQElement< 3 >::oc_hang_helper(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::oc_hang_helper(), OneDPoissonProblem< ELEMENT >::OneDPoissonProblem(), SSPorousChannelElement::output(), oomph::QExtrudedMacroElement< 3 >::output_macro_element_boundaries(), oomph::QMacroElement< 3 >::output_macro_element_boundaries(), Eigen::internal::SparseLUImpl< Scalar, StorageIndex >::panel_bmod(), Flag_definition::TopOfFlag::position(), Flag_definition::BottomOfFlag::position(), WavyWall::position(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::rebuild_from_sons(), oomph::RefineableQSpectralElement< 3 >::rebuild_from_sons(), oomph::RefineableQSpectralElement< 1 >::rebuild_from_sons(), oomph::OcTree::rotate(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::run(), UnsteadyHeatProblem< ELEMENT >::set_neighbour_periodic_and_up_right_equivalents(), Eigen::BiCGSTABL< MatrixType_, Preconditioner_ >::setL(), Eigen::IDRSTABL< MatrixType_, Preconditioner_ >::setL(), oomph::RefineableQElement< 1 >::setup_father_bounds(), oomph::RefineableQElement< 3 >::setup_hang_for_value(), oomph::RefineableQElement< 3 >::setup_hanging_nodes(), oomph::BinaryTree::setup_static_data(), oomph::OcTree::setup_static_data(), SphericalSpinUpProblem< ELEMENT >::SphericalSpinUpProblem(), test_image_op_sycl(), transform_associativity(), and Flag_definition::upper_tip().