MercuryDPM: two_d_variable_diff_adapt.cc File Reference
two_d_variable_diff_adapt.cc File Reference
#include "generic.h"
#include "advection_diffusion.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class RefineableAdvectionDiffusionProblem< ELEMENT >
Namespaces
RachelsAdvectionDiffusion
Functions
void RachelsAdvectionDiffusion::get_exact_u (const Vector< double > &x, Vector< double > &u)
The asymptotic solution.
void RachelsAdvectionDiffusion::wind_function (const Vector< double > &x, Vector< double > &wind)
Wind (the underlying velocity field)
void RachelsAdvectionDiffusion::swimming (const Vector< double > &x, Vector< double > &swim)
Conserved bit (the swiming velocity)
void RachelsAdvectionDiffusion::diff_function (const Vector< double > &x, DenseMatrix< double > &D)
Diffusivity tensor.
int main ()
Driver code for 2D AdvectionDiffusion problem.
Variables
double RachelsAdvectionDiffusion::Peclet =0.01
Peclet number.
double RachelsAdvectionDiffusion::U = 0.7
Swimming speed.
double RachelsAdvectionDiffusion::D11 = 0.1
double RachelsAdvectionDiffusion::D22 = 0.2
const double RachelsAdvectionDiffusion::pi = MathematicalConstants::Pi
The value of pi.
Function Documentation
main()
int main ()
Driver code for 2D AdvectionDiffusion problem.
 {
  //Set up the problem
  //------------------
  // Create the problem with 2D nine-node refineable elements from the
  // RefineableQuadAdvectionDiffusionElement family. Pass pointer to
  // source and wind function.
  RefineableAdvectionDiffusionProblem<
   RefineableQGeneralisedAdvectionDiffusionElement<2,
   3> > problem(&RachelsAdvectionDiffusion::wind_function,
                &RachelsAdvectionDiffusion::swimming,
                &RachelsAdvectionDiffusion::diff_function);
  // Check if we're ready to go:
  //----------------------------
  cout << "\n\n\nProblem self-test ";
  if (problem.self_test()==0)
   {
    cout << "passed: Problem can be solved." << std::endl;
   }
  else
   {
    throw OomphLibError("Self test failed",
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
   }
  // Solve the problem, performing up to 4 adptive refinements
  problem.newton_solve(4);
  //Output the solution
  problem.doc_solution();
 } // end of main
References RachelsAdvectionDiffusion::diff_function(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, problem, RachelsAdvectionDiffusion::swimming(), and RachelsAdvectionDiffusion::wind_function().