MercuryDPM: Tutorial_Map_using.cpp File Reference
Tutorial_Map_using.cpp File Reference
Typedefs
typedef Matrix< float, 1, Dynamic > MatrixType
typedef Map< MatrixType > MapType
typedef Map< const MatrixType > MapTypeConst
Functions
MatrixType m1 (n_dims)
MatrixType m2 (n_dims)
m1 setRandom ()
MapType m2map (p, m2.size())
MapTypeConst m2mapconst (p, m2.size())
Variables
const int n_dims = 5
float * p = &m2(0)
Typedef Documentation
MapType
typedef Map<MatrixType> MapType
MapTypeConst
typedef Map<const MatrixType> MapTypeConst
MatrixType
typedef Matrix<float, 1, Dynamic> MatrixType
Function Documentation
m1()
MatrixType m1 (n_dims)
m2()
MatrixType m2 (n_dims)
Referenced by adjoint(), areNotApprox(), array_complex(), array_for_matrix(), array_generic(), array_real(), array_special_functions(), basicStuff(), Eigen::internal::kiss_cpx_fft< Scalar_ >::bfly3(), block(), bug1684(), bug1684_job1(), bug1684_job2(), bug1684_job3(), bug_1225(), check_indexed_view(), check_marketio(), check_marketio_dense(), check_solverbase(), cholesky(), comparisons(), ctor_init1(), cwise_ref(), determinant(), diagonal(), diagonalmatrices(), EIGEN_DECLARE_TEST(), oomph::RefineableLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity(), oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::RefineablePolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarStreamfunctionEquations::fill_in_generic_residual_contribution(), oomph::RefineableAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_adv_diff(), oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_generic_residual_contribution_adv_diff_react(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_cons_adv_diff(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc(), oomph::RefineableFpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc(), oomph::RefineableFpPressureAdvDiffRobinBCElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc(), oomph::RefineableHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::RefineablePMLHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::RefineableLinearWaveEquations< DIM >::fill_in_generic_residual_contribution_lin_wave(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineablePoissonEquations< DIM >::fill_in_generic_residual_contribution_poisson(), oomph::RefineablePVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::RefineableUnsteadyHeatEquations< DIM >::fill_in_generic_residual_contribution_ust_heat(), RefineableBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), fixedSizeMatrixConstruction(), householder(), initializerListArrayConstruction(), initializerListMatrixConstruction(), integer_type_tests(), inverse(), inverse_for_fixed_size(), mathsFunc::isEqual(), linearStructure(), linearstructure_overflow(), lu_invertible(), lu_non_invertible(), lu_partial_piv(), main(), Map_MatrixXd_add(), Map_MatrixXd_multiply(), matrixRedux(), MatrixXd_add(), MatrixXd_multiply(), nomalloc(), noncopyable(), plaintype_tests(), product(), product_extra(), product_notemporary(), product_selfadjoint(), qr(), qr_invertible(), randomTest(), ref_matrix(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), replicate(), reverse(), shift_test_impl< ArrayType >::run(), typed_logicals_test_impl< ArrayType >::run(), run_nesting_ops_2(), selfadjoint(), signed_integer_type_tests(), sparse_basic(), sparse_block(), sparse_product(), sparse_product_regression_test(), sparse_solvers(), svd_min_norm(), swap(), symm(), syrk(), test_contraction_of_contraction(), test_cwise_complex(), test_cwise_real(), Eigen::test_isCwiseApprox(), Eigen::test_isMuchSmallerThan(), test_reshape_in_expr(), test_simple(), test_slice_in_expr(), testGeneral(), TreeTest< Dim >::testMinimize1(), TreeTest< Dim >::testMinimize2(), triangular_deprecated(), triangular_rect(), triangular_square(), vectorwiseop_array(), and vectorwiseop_matrix().
m2map()
MapType m2map (p , m2. size())
m2mapconst()
MapTypeConst m2mapconst (p , m2. size())
setRandom()
m1 setRandom ()
Variable Documentation
n_dims
const int n_dims = 5
p
float* p = &m2(0)
Referenced by Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::absDistance(), DPM::actionsAfterSolve(), ClosedCSCRestart::actionsAfterTimeStep(), ClosedCSCRun::actionsAfterTimeStep(), RotatingDrumWet::actionsAfterTimeStep(), CubicCell::actionsAfterTimeStep(), LeesEdwardsDemo::actionsAfterTimeStep(), ShiftingConstantMassFlowMaserBoundarySelfTest::actionsAfterTimeStep(), ShiftingMaserBoundarySelfTest::actionsAfterTimeStep(), TimeDependentPeriodicBoundary3DSelfTest::actionsAfterTimeStep(), TimeDependentPeriodicBoundaryTest::actionsAfterTimeStep(), vibratedBed::actionsAfterTimeStep(), OneParticleHeatingSelfTest::actionsAfterTimeStep(), OneParticleCoolingSelfTest::actionsAfterTimeStep(), SingleParticleSegregation::actionsAfterTimeStep(), DPM::actionsAfterTimeStep(), VolumeCoupling::actionsAfterTimeStep(), HeatFluidCoupledSpecies< NormalForceSpecies >::actionsAfterTimeStep(), CoupledBeam::actionsBeforeOomphTimeStep(), SubcriticalMaserBoundaryTEST::actionsBeforeTimeLoop(), DPM::actionsBeforeTimeStep(), ConstantMassFlowMaserBoundary::activateMaser(), SubcriticalMaserBoundary::activateMaser(), StressStrainControlBoundary::activateStrainRateControl(), Eigen::DynamicSGroup::add(), ChutePeriodic::add_flow_particles(), SilbertPeriodic::add_flow_particles(), ParticleHandler::addGhostObject(), SingleParticleSegregation::addIntruderParticle(), ParticleHandler::addObject(), NautaMixer::addParticles(), NautaMixer::addParticlesAtWall(), BaseWall::addParticlesAtWall(), ConstantMassFlowMaserBoundary::addParticleToMaser(), SubcriticalMaserBoundary::addParticleToMaser(), TriangleMeshWall::addToMesh(), Eigen::internal::all_visitor< Scalar >::all_predux(), Eigen::internal::any_visitor< Scalar >::any_predux(), BaseCluster::applyCentralForce(), oomph::NavierStokesSchurComplementPreconditioner::assemble_inv_press_and_veloc_mass_matrix_diagonal(), oomph::PressureBasedSolidLSCPreconditioner::assemble_mass_matrix_diagonal(), oomph::ImmersedRigidBodyTriangleMeshPolygon::assign_zeta(), BaseCG::BaseCG(), BaseInteractable::BaseInteractable(), BaseInteraction::BaseInteraction(), BaseNormalForce::BaseNormalForce(), BaseParticle::BaseParticle(), Eigen::Spline< Scalar_, Dim_, Degree_ >::BasisFunctionDerivativesImpl(), Eigen::Spline< Scalar_, Dim_, Degree_ >::BasisFunctions(), Eigen::internal::Bf16ToF32(), Eigen::internal::kiss_cpx_fft< Scalar_ >::bfly_generic(), Eigen::internal::bicgstab(), Global_Parameters::blended_pressure_pseudo_singularity_for_couette(), BondedInteraction::BondedInteraction(), ProblemParameters::boundary_traction(), oomph::LinearAlgebraDistribution::build(), oomph::TetgenMesh< ELEMENT >::build_tetgenio(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::calc_colcount(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::calc_lineage(), Eigen::internal::TensorIntDivisor< int32_t, true >::calcMagic(), CFDDEMCoupleTest::CalcPhiPAndFz(), oomph::HomogenisedLinearElasticityEquations< DIM >::calculate_effective_modulus(), oomph::IsotropicStrainEnergyFunctionConstitutiveLaw::calculate_second_piola_kirchhoff_stress(), ChargedBondedInteraction::ChargedBondedInteraction(), mathsFunc::chebyshev(), check_aligned_malloc(), check_aligned_new(), check_aligned_stack_alloc(), check_handmade_aligned_malloc(), check_histogram< bool >(), check_hyperbolic_functions(), LeesEdwardsBoundary::checkBoundaryAfterParticleMoved(), ShearBoxBoundary::checkBoundaryAfterParticleMoved(), ConstantMassFlowMaserBoundary::checkBoundaryAfterParticleMoved(), DeletionBoundary::checkBoundaryAfterParticleMoved(), FluxBoundary::checkBoundaryAfterParticleMoved(), HeaterBoundary::checkBoundaryAfterParticleMoved(), SubcriticalMaserBoundary::checkBoundaryAfterParticleMoved(), SubcriticalMaserBoundaryTEST::checkBoundaryAfterParticleMoved(), AngledPeriodicBoundary::checkBoundaryAfterParticlesMove(), CircularPeriodicBoundary::checkBoundaryAfterParticlesMove(), ConstantMassFlowMaserBoundary::checkBoundaryAfterParticlesMove(), DropletBoundary::checkBoundaryAfterParticlesMove(), FluxBoundary::checkBoundaryAfterParticlesMove(), HeaterBoundary::checkBoundaryAfterParticlesMove(), LeesEdwardsBoundary::checkBoundaryAfterParticlesMove(), PeriodicBoundary::checkBoundaryAfterParticlesMove(), SubcriticalMaserBoundary::checkBoundaryAfterParticlesMove(), SubcriticalMaserBoundaryTEST::checkBoundaryAfterParticlesMove(), TimeDependentPeriodicBoundary::checkBoundaryAfterParticlesMove(), DPMBase::checkParticleForInteraction(), MercuryBase::checkParticleForInteraction(), DPMBase::checkParticleForInteractionLocal(), MercuryBase::checkParticleForInteractionLocal(), DPMBase::checkParticleForInteractionLocalPeriodic(), DPMBase::checkSettings(), oomph::BlockPreconditioner< MATRIX >::clear_block_preconditioner_base(), ClosedCSCRun::ClosedCSCRun(), ConstantMassFlowMaserBoundary::closeMaser(), ClumpParticle::ClumpParticle(), Eigen::internal::evaluator< SparseCompressedBase< Derived > >::coeff(), Eigen::internal::evaluator< SparseCompressedBase< Derived > >::coeffRef(), Eigen::internal::imklfft::complex_cast(), Eigen::EigenSolver< MatrixType_ >::compute(), Eigen::GeneralizedEigenSolver< MatrixType_ >::compute(), Eigen::MatrixPower< MatrixType >::compute(), Eigen::MatrixPowerAtomic< MatrixType >::compute2x2(), oomph::PoissonEquations< 1 >::compute_error(), Eigen::JacobiSVD< MatrixType_, Options_ >::compute_impl(), internal::Colamd::compute_ordering(), DPMBase::computeAllForces(), Mercury3Dclump::computeAllForces(), DPM::computeAllForcesNoHGrid(), CGHandler::computeContactPoints(), ScaleCoupling< M, O >::computeCouplingForce(), VolumeCoupling::computeCouplingForce(), CFDDEMCoupleTest::computeExternalForces(), SphericalIndenter::computeExternalForces(), AngledPeriodicBoundarySecondUnitTest::computeExternalForces(), ScaleCoupling< M, O >::computeExternalForces(), Eigen::MatrixPower< MatrixType >::computeFracPower(), Eigen::MatrixPower< MatrixType >::computeIntPower(), DPM::computeLocalCGHGrid(), DPM::computeLocalVolumeFraction(), DPM::computeLocalVolumeFractionHGrid(), DPM::computeLocalVolumeFractionHGridCompact(), ParticleSpecies::computeMass(), ScaleCoupling< M, O >::computeNodalCouplingForces(), ScaleCoupling< M, O >::computeProjectionMatrix(), sphericalHarmonics::computeSquaredFactorialValues(), Eigen::MatrixPowerAtomic< MatrixType >::computeSuperDiag(), HertzianSinterNormalSpecies::computeTimeStep(), DPMBase::computeWallForces(), Mercury3D::computeWallForces(), VolumeCoupling::computeWeightOnParticles(), oomph::CRDoubleMatrixHelpers::concatenate_without_communication(), Eigen::internal::conjugate_gradient(), Eigen::internal::construct_at(), Eigen::AlignedBox< Scalar_, AmbientDim_ >::contains(), HorizontalBaseScrew::convertLimits(), PSD::convertProbabilityDensityNumberDistributionToProbabilityDensity(), PSD::convertProbabilityDensityToProbabilityDensityNumberDistribution(), convertPSD2ToPSD(), PSDContinuous::convertSubtractiveNumberToVolume(), PSDContinuous::convertSubtractiveVolumeToNumber(), MPISphericalParticle::copyDataFromMPIParticleToParticle(), MPISuperQuadric::copyDataFromMPIParticleToParticle(), MPILiquidFilmParticle::copyDataFromMPIParticleToParticle(), copyDataFromMPIParticleToParticle(), copyDataFromParticleToMPIParticle(), MPISphericalParticle::copyDataFromParticleToMPIParticle(), MPISuperQuadric::copyDataFromParticleToMPIParticle(), MPILiquidFilmParticle::copyDataFromParticleToMPIParticle(), SubcriticalMaserBoundaryTEST::copyExtraParticles(), Eigen::internal::count_visitor< Scalar >::count_redux(), Chute::createBottom(), TriangleMeshWall::createFourPointMesh(), ConstantMassFlowMaserBoundary::createGhostCopy(), SubcriticalMaserBoundary::createGhostCopy(), LeesEdwardsBoundary::createHorizontalPeriodicParticle(), ShearBoxBoundary::createHorizontalPeriodicParticle(), TriangleMeshWall::createParallelogramMesh(), AngledPeriodicBoundary::createPeriodicParticle(), CircularPeriodicBoundary::createPeriodicParticle(), ConstantMassFlowMaserBoundary::createPeriodicParticle(), LeesEdwardsBoundary::createPeriodicParticle(), PeriodicBoundary::createPeriodicParticle(), ShearBoxBoundary::createPeriodicParticle(), SubcriticalMaserBoundary::createPeriodicParticle(), SubcriticalMaserBoundaryTEST::createPeriodicParticle(), TimeDependentPeriodicBoundary::createPeriodicParticle(), LeesEdwardsBoundary::createVerticalPeriodicParticle(), ShearBoxBoundary::createVerticalPeriodicParticle(), InfiniteWall::createVTK(), Eigen::internal::cs_tdfs(), PSD::cutoffAndSqueezeCumulativeDistribution(), PSDContinuous::cutoffAndSqueezeCumulativeNumber(), CylindricalWall::CylindricalWall(), oomph::FiniteElement::d_dshape_eulerian_dnodal_coordinates_templated_helper(), BaseCluster::dampVelocities(), oomph::Orthpoly::ddlegendre(), SubcriticalMaserBoundary::deactivateMaser(), Eigen::aligned_allocator< T >::deallocate(), Domain::debugInformation(), oomph::TetgenMesh< ELEMENT >::deep_copy_of_tetgenio(), Eigen::BDCSVD< MatrixType_, Options_ >::deflation(), tetgenio::deinitialize(), Eigen::derivativesImpl(), Eigen::internal::destroy_at(), oomph::FluxTransportEquations< DIM >::dflux_du(), HGridOptimiser::diffEndExpectedCellsIntegral(), HGridOptimiser::diffHExpectedCellsIntegral(), HGridOptimiser::diffHExpectedCellsIntegralCellNumerator(), HGridOptimiser::diffPdfInt(), HGridOptimiser::diffStartExpectedCellsIntegral(), Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::distance(), oomph::Orthpoly::dlegendre(), ContactProblem< ELEMENT >::doc_solution(), oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::doc_solution(), checkIdx::doCheck_(), Eigen::EigenSolver< MatrixType_ >::doComputeEigenvectors(), DPM::DPM(), oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::dshape_and_dtest_eulerian_and_dnodal_coordinates_at_knot_lin_axi_nst(), oomph::LinearisedAxisymmetricQTaylorHoodElement::dshape_and_dtest_eulerian_and_dnodal_coordinates_at_knot_lin_axi_nst(), oomph::AxisymmetricQCrouzeixRaviartElement::dshape_and_dtest_eulerian_at_knot_axi_nst(), oomph::AxisymmetricQTaylorHoodElement::dshape_and_dtest_eulerian_at_knot_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::dshape_and_dtest_eulerian_at_knot_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement::dshape_and_dtest_eulerian_at_knot_axi_nst(), oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), oomph::QCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), oomph::QTaylorHoodElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), oomph::TCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), oomph::TTaylorHoodElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), oomph::QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), Eigen::internal::eigen_lsx_shuffle_mask(), Eigen::internal::eigen_neon_shuffle_mask(), oomph::Mesh::elemental_dimension(), escape(), Eigen::internal::etree_find(), Eigen::internal::kernel_retval< FullPivLU< MatrixType_, PermutationIndex_ > >::evalTo(), Eigen::internal::image_retval< FullPivLU< MatrixType_, PermutationIndex_ > >::evalTo(), ProblemParameters::exact_minus_dudr(), Global::exact_solution(), HGridOptimiser::expectedCellsIntegral(), HGridOptimiser::expectedCellsIntegralCellNumerator(), Eigen::AlignedBox< Scalar_, AmbientDim_ >::extend(), SubcriticalMaserBoundaryTEST::extendBottom(), Eigen::AlignedBox< Scalar_, AmbientDim_ >::exteriorDistance(), Eigen::internal::F32MaskToBf16Mask(), Eigen::internal::F32ToBf16(), Eigen::SparseQR< MatrixType_, OrderingType_ >::factorize(), Eigen::IncompleteCholesky< Scalar, UpLo_, OrderingType_ >::factorize(), Eigen::internal::kiss_cpx_fft< Scalar_ >::factorize(), Eigen::SimplicialCholeskyBase< Derived >::factorize_preordered(), Eigen::internal::fftw_cast(), oomph::LinearSurfaceContactElement< ELEMENT >::fill_in_contribution_to_residuals_surface_contact(), oomph::HomogenisedLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity(), ABCElement::fill_in_generic_residual_contribution(), DPMBase::fillDomainWithParticles(), Eigen::internal::evaluator< SparseCompressedBase< Derived > >::find(), PeriodicBoundaryHandler::findNewInteractions(), oomph::LinearAlgebraDistribution::first_row(), oomph::DistributableLinearAlgebraObject::first_row(), PeriodicBoundaryHandler::flushParticles(), Domain::flushParticlesFromList(), oomph::EulerEquations< DIM >::flux(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), foo(), FrictionInteraction::FrictionInteraction(), PerturbationSolution::full_soln(), oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::further_build(), oomph::PRefineableQCrouzeixRaviartElement< DIM >::further_build(), PolydisperseInsertionBoundary::generateParticle(), Eigen::internal::generic_atan(), oomph::LinearisedAxisymmetricNavierStokesEquations::get_base_flow_d_dudx_dX(), oomph::BlockPreconditioner< CRDoubleMatrix >::get_block_vectors(), oomph::AxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::NavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineableNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineablePoissonEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::SpaceTimeNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::Problem::get_eigenproblem_matrices(), oomph::Z2ErrorEstimator::get_element_errors(), PlanarWave::get_exact_u(), ProblemParameters::get_exact_u(), oomph::ImmersedRigidBodyTriangleMeshPolygon::get_initial_position(), oomph::SurfaceContactElementBase< ELEMENT >::get_interpolated_lagrange_p(), oomph::SurfaceMeltElement< ELEMENT >::get_interpolated_lagrange_p(), oomph::Problem::get_jacobian(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_reaction_deriv_adv_diff_react(), oomph::Problem::get_residuals(), ParticleHandler::getAngularMomentum(), SphericalIndenter::getBedHeight(), SuperQuadricParticle::getContactPoint(), Matrix3D::getCylindricalTensorField(), Vec3D::getCylindricalTensorField(), ConstantMassFlowMaserBoundary::getDistance(), SubcriticalMaserBoundary::getDistance(), PeriodicBoundary::getDistance(), TimeDependentPeriodicBoundary::getDistance(), Quaternion::getDistance(), ArcWall::getDistanceAndNormal(), AxisymmetricIntersectionOfWalls::getDistanceAndNormal(), HorizontalBaseScrew::getDistanceAndNormal(), HorizontalScrew::getDistanceAndNormal(), NurbsWall::getDistanceAndNormal(), ScrewsymmetricIntersectionOfWalls::getDistanceAndNormal(), BasicIntersectionOfWalls::getDistanceAndNormal(), BasicUnionOfWalls::getDistanceAndNormal(), Coil::getDistanceAndNormal(), Combtooth::getDistanceAndNormal(), InfiniteWall::getDistanceAndNormal(), IntersectionOfWalls::getDistanceAndNormal(), LevelSetWall::getDistanceAndNormal(), MeshTriangle::getDistanceAndNormal(), ParabolaChute::getDistanceAndNormal(), RestrictedWall::getDistanceAndNormal(), SimpleDrumSuperquadrics::getDistanceAndNormal(), SineWall::getDistanceAndNormal(), SphericalWall::getDistanceAndNormal(), TriangleMeshWall::getDistanceAndNormal(), TriangleWall::getDistanceAndNormal(), TriangulatedWall::getDistanceAndNormal(), VChute::getDistanceAndNormal(), TriangulatedWall::Face::getDistanceAndNormal(), InfiniteWall::getDistanceNormalOverlapSuperquadric(), SimpleDrumSuperquadrics::getDistanceNormalOverlapSuperquadric(), MeshTriangle::getDistanceNormalOverlapType(), CGCoordinates::R::getDistanceSquared(), CGCoordinates::RZ::getDistanceSquared(), CGCoordinates::X::getDistanceSquared(), CGCoordinates::XY::getDistanceSquared(), CGCoordinates::XYZ::getDistanceSquared(), CGCoordinates::XZ::getDistanceSquared(), CGCoordinates::Y::getDistanceSquared(), CGCoordinates::YZ::getDistanceSquared(), CGCoordinates::Z::getDistanceSquared(), ParticleHandler::getFastestParticleLocal(), DPMBase::getGravitationalEnergy(), MeltableNormalSpecies::getHeatInput(), ParticleHandler::getHighestPositionComponentParticleLocal(), ParticleHandler::getHighestPositionX(), ParticleHandler::getHighestVelocityComponentParticleLocal(), LeesEdwardsBoundary::getHorizontalDistance(), ShearBoxBoundary::getHorizontalDistance(), DPMBase::getInfo(), SuperQuadricParticle::getInteractionWith(), ArcWall::getInteractionWith(), BaseWall::getInteractionWith(), Combtooth::getInteractionWith(), MeshTriangle::getInteractionWith(), RestrictedWall::getInteractionWith(), SineWall::getInteractionWith(), TriangleMeshWall::getInteractionWith(), TriangulatedWall::getInteractionWith(), VChute::getInteractionWith(), SuperQuadricParticle::getInteractionWithSuperQuad(), SimpleDrumSuperquadrics::getInteractionWithSuperQuad(), DPMBase::getKineticEnergy(), ParticleHandler::getKineticEnergyLocal(), DPMBase::getKineticStress(), ParticleSpecies::getLargestInverseParticleMassLocal(), CGCoordinates::R::getLength(), CGCoordinates::RZ::getLength(), CGCoordinates::X::getLength(), CGCoordinates::XY::getLength(), CGCoordinates::XYZ::getLength(), CGCoordinates::XZ::getLength(), CGCoordinates::Y::getLength(), CGCoordinates::YZ::getLength(), CGCoordinates::Z::getLength(), BaseWall::getLinePlaneIntersect(), LiquidMigrationPeriodicBoundaryInteraction::getLiquidFilmVolume(), ParticleHandler::getLowestPositionComponentParticleLocal(), ParticleHandler::getLowestVelocityComponentParticleLocal(), ParticleHandler::getMassLocal(), ParticleHandler::getMassTimesPositionLocal(), InteractionHandler::getMeanOverlap(), Sintering::getMeanPlasticOverlap(), ParticleHandler::getMomentum(), Domain::getNumberOfTrueMPIParticles(), TriangleMeshWall::getPeriodicCompanions(), TimeDependentPeriodicBoundary::getPlanewiseShift(), ParticleHandler::getPSD(), DPMBase::getRotationalEnergy(), ParticleHandler::getRotationalEnergyLocal(), CGFields::StandardFields::getSquared(), ParticleHandler::getSumRadiusLocal(), LiquidMigrationLSInteraction::getTotalLiquidFilmVolume(), LiquidMigrationWilletInteraction::getTotalLiquidFilmVolume(), LeesEdwardsBoundary::getVerticalDistance(), ShearBoxBoundary::getVerticalDistance(), ParticleHandler::getVolumeLocal(), BasicIntersectionOfWalls::getVTK(), BasicUnionOfWalls::getVTK(), WallHandler::getWriteDetailsVTKAny(), oomph::Orthpoly::gl_nodes(), oomph::Orthpoly::gll_nodes(), oomph::CRDoubleMatrix::global_matrix(), oomph::LinearAlgebraDistribution::global_to_local_row_map(), DPMBase::handleParticleAddition(), Membrane::Edge::handleParticleAddition(), Membrane::handleParticleAddition(), MeshTriangle::handleParticleAddition(), HertzianSinterInteraction::HertzianSinterInteraction(), HertzianSinterNormalSpecies::HertzianSinterNormalSpecies(), HertzianViscoelasticNormalSpecies::HertzianViscoelasticNormalSpecies(), MercuryBase::hGridActionsBeforeTimeStep(), Mercury3D::hGridFindContactsWithTargetCell(), Mercury2D::hGridFindContactsWithTargetCell(), Mercury2D::hGridFindParticleContacts(), Mercury3D::hGridFindParticleContacts(), Mercury3D::hGridFindParticlesWithTargetCell(), Mercury2D::hGridFindParticlesWithTargetCell(), Mercury3D::hGridHasContactsInTargetCell(), Mercury2D::hGridHasContactsInTargetCell(), MercuryBase::hGridInfo(), MercuryBase::hGridRebuild(), oomph::QTaylorHoodElement< 2 >::identify_load_data(), DPMBase::importParticlesAs(), Indenter::Indenter(), InfiniteWallWithHole::InfiniteWallWithHole(), HGrid::info(), tetgenio::init(), internal::Colamd::init_rows_cols(), Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::initAcc(), Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::initAcc(), Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, ConjRhs_, Arch, PacketSize_ >::initAcc(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::initAcc(), InitialConditions< SpeciesType >::InitialConditions(), Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, isInt >::initpacket(), Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, false >::initpacket(), Eigen::internal::all_visitor< Scalar >::initpacket(), Eigen::internal::any_visitor< Scalar >::initpacket(), Eigen::internal::count_visitor< Scalar >::initpacket(), Eigen::SparseVector< Scalar_, Options_, StorageIndex_ >::insert(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertBackByOuterInner(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertBackByOuterInnerUnordered(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertBackUncompressed(), DPMBase::integrateAfterForceComputation(), DPMBase::integrateBeforeForceComputation(), oomph::BlockPreconditioner< MATRIX >::internal_get_block(), oomph::BlockPreconditioner< MATRIX >::internal_get_block_ordered_preconditioner_vector(), oomph::BlockPreconditioner< MATRIX >::internal_get_block_vector(), oomph::BlockPreconditioner< MATRIX >::internal_get_block_vectors(), oomph::BlockPreconditioner< MATRIX >::internal_return_block_ordered_preconditioner_vector(), oomph::BlockPreconditioner< MATRIX >::internal_return_block_vector(), oomph::BlockPreconditioner< MATRIX >::internal_return_block_vectors(), oomph::AxisymmetricNavierStokesEquations::interpolated_d_dudx_dX_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_d_dudx_dX_axi_nst(), OrrSommerfeldEquations< DIM >::interpolated_p(), oomph::AxisymmetricPoroelasticityEquations::interpolated_p(), oomph::DarcyEquations< DIM >::interpolated_p(), oomph::PoroelasticityEquations< DIM >::interpolated_p(), HorizontalMixer::introduceParticlesAtWall(), ContactDetectionIntersectionOfWallsTest::introduceParticlesAtWall(), HorizontalMixer::introduceParticlesInDomain(), HorizontalMixer::introduceSingleParticle(), IrreversibleAdhesiveInteraction::IrreversibleAdhesiveInteraction(), is_number_of_subsets_feasible(), PeriodicBoundary::isClosestToLeftBoundary(), TimeDependentPeriodicBoundary::isClosestToLeftBoundary(), ConstantMassFlowMaserBoundary::isClosestToRightBoundary(), SubcriticalMaserBoundary::isClosestToRightBoundary(), SuperQuadricParticle::isInContactWith(), ConstantMassFlowMaserBoundary::isMaserParticle(), SubcriticalMaserBoundary::isMaserParticle(), ConstantMassFlowMaserBoundary::isNormalParticle(), SubcriticalMaserBoundary::isNormalParticle(), oomph::Orthpoly::jacobi(), jacobi(), LaserOnLayer::LaserOnLayer(), Eigen::internal::least_square_conjugate_gradient(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), oomph::Orthpoly::legendre(), oomph::Orthpoly::legendre_vector(), TwoDDGProblem< ELEMENT >::limit(), LinearPlasticViscoelasticInteraction::LinearPlasticViscoelasticInteraction(), LinearPlasticViscoelasticNormalSpecies::LinearPlasticViscoelasticNormalSpecies(), LinearViscoelasticNormalSpecies::LinearViscoelasticNormalSpecies(), LiquidBridgeBagheriInteraction::LiquidBridgeBagheriInteraction(), LiquidBridgeClassicalWilletInteraction::LiquidBridgeClassicalWilletInteraction(), LiquidBridgeWilletInteraction::LiquidBridgeWilletInteraction(), LiquidFilm< Particle >::LiquidFilm(), LiquidMigrationLSInteraction::LiquidMigrationLSInteraction(), LiquidMigrationWilletInteraction::LiquidMigrationWilletInteraction(), load(), loadingTest(), Eigen::CholmodBase< MatrixType_, UpLo_, Derived >::logDeterminant(), main(), BaseCluster::makeDataAnalysis(), Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::JacobiRotation< Scalar >::makeJacobi(), ChuteBottom::makeRoughBottom(), Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapGpuInputPlaneToTensorInputOffset(), Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapGpuOutputPlaneToTensorOutputOffset(), Eigen::MatrixPowerAtomic< MatrixType >::MatrixPowerAtomic(), matrixRedux(), matrixVisitor(), max_feasible_subset_size(), MercuryCGSelfTest::MercuryCGSelfTest(), MindlinInteraction::MindlinInteraction(), MindlinRollingTorsionInteraction::MindlinRollingTorsionInteraction(), Eigen::internal::minimum_degree_ordering(), Eigen::internal::minres(), TriangleMeshWall::moveVerticesToMatchVolume(), MovingWall::MovingWall(), oomph::Mesh::ndof_types(), next_subset(), oomph::Mesh::nodal_dimension(), normalAndTangentialLoadingTest(), oomph::LinearAlgebraDistribution::nrow_local(), oomph::DistributableLinearAlgebraObject::nrow_local(), objectivenessTest(), oomph::OneDimensionalLegendreDShape< NNODE_1D >::OneDimensionalLegendreDShape(), oomph::OneDimensionalLegendreShape< NNODE_1D >::OneDimensionalLegendreShape(), oomph::OneDLegendreDShapeParam::OneDLegendreDShapeParam(), oomph::OneDLegendreShapeParam::OneDLegendreShapeParam(), Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV3D >::operator()(), Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()(), Eigen::COLAMDOrdering< StorageIndex >::operator()(), Eigen::internal::accurate_log2< float >::operator()(), Eigen::MatrixPower< MatrixType >::operator()(), Eigen::internal::gemm_pack_lhs< Scalar, Index, DataMapper, Pack1, Pack2, Packet, RowMajor, Conjugate, PanelMode >::operator()(), Eigen::Spline< Scalar_, Dim_, Degree_ >::operator()(), CGFields::DisplacementField::operator*(), CGFields::GradVelocityField::operator*(), CGFields::LiquidMigrationFields::operator*(), CGFields::OrientationField::operator*(), CGFields::StandardFields::operator*(), CGFields::StandardFields::operator/=(), oomph::TriangleMesh< ELEMENT >::Point::operator<(), oomph::RankFiveTensor< T >::operator=(), oomph::RankFourTensor< T >::operator=(), oomph::RankThreeTensor< T >::operator=(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::operator=(), internal::Colamd::order_children(), oomph::PoissonEquations< 1 >::output(), CGFields::StandardFields::output(), oomph::DoubleMultiVector::output(), oomph::DoubleVector::output(), oomph::NonlinearSurfaceContactElement< ELEMENT >::output(), oomph::LinearSurfaceContactElement< ELEMENT >::output(), oomph::HeatedLinearSurfaceContactElement< ELEMENT >::output(), oomph::PoissonEquations< 1 >::output_fct(), DPMBase::outputInteractionDetails(), LiquidMigrationSelfTest::outputXBallsData(), Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, isInt >::packet(), Eigen::internal::minmax_coeff_visitor< Derived, is_min, PropagateNumbers, false >::packet(), Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, false >::packet(), Eigen::internal::all_visitor< Scalar >::packet(), Eigen::internal::any_visitor< Scalar >::packet(), Eigen::internal::count_visitor< Scalar >::packet(), Eigen::internal::evaluator< PartialReduxExpr< ArgType, MemberOp, Direction > >::packet(), TrackedVisitor< Derived, Vectorizable >::packet(), Eigen::internal::scalar_logistic_op< float >::packetOp(), Eigen::internal::pacos_float(), ParticleBeam::ParticleBeam(), ParticleInclusion::ParticleInclusion(), ParticleSpecies::ParticleSpecies(), oomph::METIS::partition_mesh(), Eigen::internal::pasin_float(), Eigen::internal::patanh_double(), Eigen::internal::patanh_float(), HGridOptimiser::pdfInt(), HGridOptimiser::pdfIntCell(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::perform_power_method(), PerturbationSolution::perturbation_soln_for_plot(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::pin_p_value(), oomph::TPoroelasticityElement< ORDER >::pin_p_value(), FixedClusterInsertionBoundary::placeParticle(), ChuteInsertionBoundary::placeParticle(), CubeInsertionBoundary::placeParticle(), CylinderInsertionBoundary::placeParticle(), HopperInsertionBoundary::placeParticle(), RandomClusterInsertionBoundary::placeParticle(), SphereInsertionBoundary::placeParticle(), Eigen::internal::ploaddup< Packet16c >(), Eigen::internal::ploaddup< Packet16uc >(), Eigen::internal::ploaddup< Packet8s >(), Eigen::internal::ploaddup< Packet8us >(), Eigen::internal::ploaddup_common(), Eigen::internal::ploadquad< Packet16c >(), Eigen::internal::ploadquad< Packet16uc >(), Eigen::internal::ploadquad< Packet8s >(), Eigen::internal::ploadquad< Packet8us >(), Eigen::internal::plog_impl_float(), polyder(), Eigen::internal::positive_real_hypot(), Eigen::internal::minmax_compare< Scalar, NaNPropagation, is_min >::predux(), Eigen::internal::minmax_compare< Scalar, NaNPropagation, false >::predux(), Eigen::internal::predux< Packet16bf >(), PeriodicBoundaryHandler::preparePositionAndVelocityUpdate(), oomph::EulerEquations< DIM >::pressure(), Global_Parameters::pressure_singularity1(), Global_Parameters::pressure_singularity2(), PSDContinuous::print(), print_stacktrace(), PSD::printPSD(), LiquidMigrationMPI2Test::printTime(), InitialBed::printTime(), LaserOnLayer::printTime(), MeltableForceLaw2SelfTest::printTime(), MeltableForceLawSelfTest::printTime(), ThermalConductionSelfTest::printTime(), LiquidMigrationSelfTest::printTime(), HeatTransferUnitTest::printTime(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::projection(), Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::projection(), Eigen::internal::ptanh< Packet4f >(), Eigen::internal::ptanh_double(), Eigen::internal::ptanh_float(), Eigen::internal::ptranspose(), oomph::EighthSphereDomain::r_front_F(), oomph::EighthSphereDomain::r_right_R(), oomph::EighthSphereDomain::r_up_U(), oomph::LinearAlgebraDistribution::rank_of_global_row(), FileReader::read(), InteractionHandler::read(), TriangleMeshWall::read(), DPMBase::readNextDataFile(), Eigen::internal::real_2x2_jacobi_svd(), oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::rebuild_from_sons(), oomph::PRefineableQCrouzeixRaviartElement< DIM >::rebuild_from_sons(), CurvyChute::recreateBottom(), oomph::DoubleMultiVector::redistribute(), oomph::DoubleVector::redistribute(), oomph::CRDoubleMatrix::redistribute(), Eigen::internal::MeanReducer< T >::reducePacket(), Eigen::internal::SumReducer< T >::reducePacket(), Eigen::internal::MaxReducer< T, NaNPropagation >::reducePacket(), Eigen::internal::MinReducer< T, NaNPropagation >::reducePacket(), Eigen::internal::ProdReducer< T >::reducePacket(), TriangleMeshWall::refineTriangle(), DPMBase::removeOldFiles(), ConstantMassFlowMaserBoundary::removeParticleFromMaser(), SubcriticalMaserBoundary::removeParticleFromMaser(), TriangleMeshWall::removeTriangle(), RisingBubbleProblem< ELEMENT >::RisingBubbleProblem(), Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, true, false, ShortCircuitEvaluation >::run(), Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, true, true, ShortCircuitEvaluation >::run(), Eigen::internal::packetwise_redux_impl< Func, Evaluator, NoUnrolling >::run(), Eigen::internal::StridedLinearBufferCopy< Scalar, IndexType >::Run(), Eigen::internal::lpNorm_selector< Derived, p >::run(), Eigen::internal::patan_reduced< Scalar >::run(), Eigen::internal::ImagePatchCopyOp< Self, true >::Run(), Eigen::internal::generic_j0< T, float >::run(), Eigen::internal::generic_j0< T, double >::run(), Eigen::internal::generic_y0< T, float >::run(), Eigen::internal::generic_y0< T, double >::run(), Eigen::internal::generic_j1< T, float >::run(), Eigen::internal::generic_j1< T, double >::run(), Eigen::internal::generic_y1< T, float >::run(), Eigen::internal::generic_y1< T, double >::run(), Eigen::internal::generic_fast_erf< Scalar >::run(), Eigen::internal::TensorBlockAssignment< Scalar, NumDims, TensorBlockExpr, IndexType >::InnerDimAssign< true, Evaluator >::Run(), Eigen::internal::digamma_impl< Scalar >::run(), Eigen::internal::zeta_impl< Scalar >::run(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, Options, true >::run(), run_bdmp_spec_1(), save(), Membrane::saveAsOFF(), ClosedCSCWalls::saveWalls(), CSCWalls::saveWalls(), PSD::scaleParticleSize(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::scatterPacket(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::scatterPacket(), BaseCG::selectSpecies(), NurbsSurface::set(), TriangleMeshWall::set(), PolarNSProblem< ELEMENT >::set_pext(), Eigen::internal::fftw_plan< double >::set_plan(), Eigen::internal::fftw_plan< float >::set_plan(), Eigen::internal::fftw_plan< long double >::set_plan(), LinearViscoelasticNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), SPHNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), CGFields::DisplacementField::setCylindricalFields(), CGFields::GradVelocityField::setCylindricalFields(), CGFields::LiquidMigrationFields::setCylindricalFields(), CGFields::OrientationField::setCylindricalFields(), CGFields::StandardFields::setCylindricalFields(), PSD::setDistributionLogNormal(), CGFields::DisplacementField::setFields(), CGFields::GradVelocityField::setFields(), CGFields::LiquidMigrationFields::setFields(), CGFields::OrientationField::setFields(), CGFields::StandardFields::setFields(), CGFields::StandardFieldsBinning::setFields(), HGrid::setFirstBaseParticleInBucket(), BaseParticle::setHGridNextObject(), BaseParticle::setHGridPrevObject(), RNG::setLaggedFibonacciGeneratorParameters(), DPMBase::setMeanVelocity(), DPMBase::setMeanVelocityAndKineticEnergy(), BaseParticle::setPeriodicFromParticle(), Camera::setPosition(), BaseCluster::setPosition(), CGHandler::setPreviousPositionToCurrentPosition(), ExtremeOverlapUnitTest::setupInitialConditions(), ExtremeOverlapVolumeUnitTest::setupInitialConditions(), ClosedCSCWalls::setupInitialConditions(), CSCInit::setupInitialConditions(), CSCRun::setupInitialConditions(), CSCWalls::setupInitialConditions(), Drum::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), VerticalMixer::setupInitialConditions(), Chain::setupInitialConditions(), InsertionBoundaryMPI2Test::setupInitialConditions(), CubicCell::setupInitialConditions(), FreeCooling2DinWalls::setupInitialConditions(), FreeCooling2DinWallsDemo::setupInitialConditions(), FreeCooling3DDemoProblem::setupInitialConditions(), FreeCooling3DinWallsDemo::setupInitialConditions(), FreeCoolingDemoProblem::setupInitialConditions(), LeesEdwardsDemo::setupInitialConditions(), TimeDependentPeriodicBoundary3DSelfTest::setupInitialConditions(), TimeDependentPeriodicBoundaryTest::setupInitialConditions(), InitialBed::setupInitialConditions(), OneParticleHeatingSelfTest::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), CubeDeletionBoundarySelfTest::setupInitialConditions(), DeletionBoundarySelfTest::setupInitialConditions(), DistributionPhiNormalSelfTest::setupInitialConditions(), StressStrainControl::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), ParticleCreation::setupInitialConditions(), ChargedBondedInteractionSelfTest::setupInitialConditions(), DPM::setupInitialConditions(), TwoBondedParticleElasticCollision::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), TriangulatedScrewSelfTest::setupInitialConditions(), TriangulatedStepSelfTest::setupInitialConditions(), TriangulatedStepWallSelfTest::setupInitialConditions(), TriangulatedWallSelfTest::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), Wall::setupInitialConditions(), BouncingSuperQuadric::setupInitialConditions(), ShapesDemo::setupInitialConditions(), AngledPeriodicBoundarySecondUnitTest::setupInitialConditions(), AngledPeriodicBoundaryUnitTest::setupInitialConditions(), ArcWallUnitTest::setupInitialConditions(), Packing::setupInitialConditions(), TwoParticles::setupInitialConditions(), ParticleWall::setupInitialConditions(), CreateDataAndFStatFiles::setupInitialConditions(), FreeFall::setupInitialConditions(), MovingIntersectionOfWallsUnitTest_Basic::setupInitialConditions(), MovingWalls::setupInitialConditions(), SeparateFilesSelfTest::setupInitialConditions(), SetDistributionPhiNormalSelfTest::setupInitialConditions(), TangentialSpringEnergyConservationUnitTest::setupInitialConditions(), ScaleCoupledBeam::setupMercury(), CoupledBeam::setupMercury(), CoupledProblem::setupMercury(), CGCoordinates::XYZ::setXYZ(), CGFields::StandardFields::setZero(), TimeDependentPeriodicBoundary::shiftAndBoostParticle(), LeesEdwardsBoundary::shiftHorizontalPosition(), ShearBoxBoundary::shiftHorizontalPosition(), ConstantMassFlowMaserBoundary::shiftPosition(), SubcriticalMaserBoundary::shiftPosition(), PeriodicBoundary::shiftPosition(), LeesEdwardsBoundary::shiftVerticalPosition(), ShearBoxBoundary::shiftVerticalPosition(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::signedDistance(), SinterInteraction::SinterInteraction(), SinterLinInteraction::SinterLinInteraction(), SinterLinNormalSpecies::SinterLinNormalSpecies(), SinterNormalSpecies::SinterNormalSpecies(), SinterPair::SinterPair(), SlidingFrictionInteraction::SlidingFrictionInteraction(), SolidifyingLiquidMigrationWilletInteraction::SolidifyingLiquidMigrationWilletInteraction(), oomph::CG< MATRIX >::solve_helper(), oomph::BiCGStab< MATRIX >::solve_helper(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_two_arrays(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_two_vectors(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_vectors_of_pairs(), sparse_permutations(), sphericalHarmonics::sphericalHarmonics(), SPHNormalSpecies::SPHNormalSpecies(), Eigen::MatrixPower< MatrixType >::split(), Eigen::RealQZ< MatrixType_ >::splitOffTwoRows(), Eigen::RealSchur< MatrixType_ >::splitOffTwoRows(), Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::squaredDistance(), Eigen::AlignedBox< Scalar_, AmbientDim_ >::squaredExteriorDistance(), SteadyHelicalProblem< ELEMENT >::SteadyHelicalProblem(), Eigen::internal::TensorContractionSubMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, inner_dim_reordered, Alignment, MakePointer_ >::storePacket(), Eigen::internal::BlasLinearMapper< Scalar, Index, AlignmentType >::storePacket(), Eigen::internal::BlasLinearMapper< Scalar, Index, AlignmentType, Incr >::storePacket(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::storePacket(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::storePacket(), Eigen::internal::BlasLinearMapper< Scalar, Index, AlignmentType >::storePacketPartial(), Eigen::internal::BlasLinearMapper< Scalar, Index, AlignmentType, Incr >::storePacketPartial(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::storePacketPartial(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::storePacketPartial(), StressStrainControl::StressStrainControl(), FlowFrontChute::stretch(), rapidjson::internal::StrLen(), SuperQuadricParticle::SuperQuadricParticle(), oomph::AxisymmetricPoroelasticityEquations::switch_off_darcy(), DPMBase::synchroniseParticle(), BoundingRadiusTester::test(), InertiaTensorTester::test(), VolumeTest::test(), test_autodiff_scalar(), test_autodiff_vector(), testCGHandler(), ShapeGradientHessianTester::testCushion(), ShapeGradientHessianTester::testEllipsoid(), ShapeGradientHessianTester::testRoundedBeam(), ShapeGradientHessianTester::testSphere(), Thermal< Particle >::Thermal(), oomph::TemplateFreeContactElementBase::traction_fct(), transform_associativity2(), transform_associativity_left(), transform_products(), oomph::TriangleMeshPolygon::TriangleMeshPolygon(), Eigen::internal::trig_reduce_huge(), NurbsSurface::unclampKnots(), HistogramHelper< Scalar, std::enable_if_t< Eigen::NumTraits< Scalar >::IsInteger > >::uniform_bin_probability(), ScaleCoupling< M, O >::updateCoupledElements(), Eigen::IncompleteCholesky< Scalar, UpLo_, OrderingType_ >::updateList(), PeriodicBoundaryHandler::updateParticles(), Domain::updateParticles(), PeriodicBoundaryHandler::updateParticleStatus(), PSD::validateCumulativeDistribution(), Eigen::internal::vec4f_swizzle1(), Eigen::internal::vec4f_swizzle2(), vectorRedux(), WearableTriangulatedWall::WearableTriangulatedWall(), Eigen::internal::kiss_cpx_fft< Scalar_ >::work(), WallVTKWriter::write(), CGFields::StandardFields::write(), ConstantMassFlowMaserBoundary::write(), InsertionBoundary::write(), SubcriticalMaserBoundary::write(), TriangleMeshWall::write(), DPMBase::write(), Silo::writeEneTimeStep(), ParticleVtkWriter::writeExtraFields(), VTKData::writePoints(), Calibration::writePSDToFile(), rapidjson::Writer< Stream, Encoding, Allocator >::WriteString(), rapidjson::Writer< Stream, Encoding, Allocator >::WriteUint(), rapidjson::Writer< Stream, Encoding, Allocator >::WriteUint64(), BoundaryVTKWriter::writeVTK(), SphericalParticleVtkWriter::writeVTK(), BasicUnionOfWalls::writeVTK(), HorizontalBaseScrew::writeVTK(), IntersectionOfWalls::writeVTK(), LevelSetWall::writeVTK(), NurbsWall::writeVTK(), ScrewsymmetricIntersectionOfWalls::writeVTK(), AxisymmetricIntersectionOfWalls::writeVTK(), SphericalParticleVtkWriter::writeVTKAngularVelocity(), VTKData::writeVTKDataFromVtkContainer(), SphericalParticleVtkWriter::writeVTKId(), ParticleVtkWriter::writeVTKIndSpecies(), SuperQuadricParticleVtkWriter::writeVTKOrientation(), InteractionVTKWriter::writeVTKPointData(), InteractionVTKWriter::writeVTKPoints(), WallVTKWriter::writeVTKPoints(), ParticleVtkWriter::writeVTKPositions(), SphericalParticleVtkWriter::writeVTKRadius(), SuperQuadricParticleVtkWriter::writeVTKSuperquadricGeometry(), SphericalParticleVtkWriter::writeVTKVelocity(), NurbsWall::writeWallDetailsVTK(), WearableNurbsWall::writeWallDetailsVTK(), and PolydisperseInsertionBoundary::~PolydisperseInsertionBoundary().