MercuryDPM: two_d_unsteady_heat.cc File Reference
optimisation/disable_ALE/unsteady_heat/two_d_unsteady_heat.cc File Reference
#include "generic.h"
#include "unsteady_heat.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class UnsteadyHeatProblem< ELEMENT >
UnsteadyHeat problem.
Namespaces
ExactSolnForUnsteadyHeat
Namespace for unforced exact solution for UnsteadyHeat equation.
Functions
void ExactSolnForUnsteadyHeat::get_exact_u (const double &time, const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void ExactSolnForUnsteadyHeat::get_exact_u (const double &time, const Vector< double > &x, double &u)
Exact solution as a scalar.
void ExactSolnForUnsteadyHeat::get_source (const double &time, const Vector< double > &x, double &source)
Source function to make it an exact solution.
void run_it (const bool &use_ale)
int main ()
Driver code for unsteady heat equation.
Function Documentation
main()
int main ()
Driver code for unsteady heat equation.
 {
  // Run with ale
  run_it(true);
  // Run without ale
  run_it(false);
 }; // end of main
References run_it().
run_it()
void run_it (const bool & use_ale)
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Run adaptive solution of unsteady heat equation with or without ALE
 {
  // Build problem
  UnsteadyHeatProblem<QUnsteadyHeatElement<2,4> >
   problem(&ExactSolnForUnsteadyHeat::get_source);
  // Switch off ALE?
  if (!use_ale)
   {
    problem.disable_ALE();
   }
  // Setup labels for output
  DocInfo doc_info;
  // Output directory
  if (!use_ale)
   {
    doc_info.set_directory("RESLT");
   }
  else
   {
    doc_info.set_directory("RESLT_ALE");
   }
  // Output number
  doc_info.number()=0;
  // Open a trace file
  ofstream trace_file;
  char filename[100];
  sprintf(filename,"%s/trace.dat",doc_info.directory().c_str());
  trace_file.open(filename);
  trace_file << "VARIABLES=\"time\",\"u<SUB>FE</SUB>\","
             << "\"u<SUB>exact</SUB>\",\"norm of error\",\"norm of solution\""
             << std::endl;
  // Choose simulation interval and timestep
  double t_max=0.1; // 0.5;
  double dt=0.01;
  // Initialise timestep -- also sets the weights for all timesteppers
  // in the problem.
  problem.initialise_dt(dt);
  // Set IC
  problem.set_initial_condition();
  //Output initial condition
  problem.doc_solution(doc_info,trace_file);
  //Increment counter for solutions
  doc_info.number()++;
  // Find number of steps
  unsigned nstep = unsigned(t_max/dt);
  // Initialise timer
  clock_t t_start = clock();
  // Timestepping loop
  for (unsigned istep=0;istep<nstep;istep++)
   {
    // cout << " Timestep " << istep << std::endl;
    // Take timestep
    problem.unsteady_newton_solve(dt);
    //Output solution
    // problem.doc_solution(doc_info,trace_file);
    //Increment counter for solutions
    // doc_info.number()++;
   }
  // Stop timer
  clock_t t_end = clock();
  std::cout << "Total time for solution: "
            << double(t_end-t_start)/CLOCKS_PER_SEC
            << std::endl;
  //Output final solution for check
  problem.doc_solution(doc_info,trace_file);
 }; // end of main
References oomph::DocInfo::directory(), MergeRestartFiles::filename, ExactSolnForUnsteadyHeat::get_source(), oomph::DocInfo::number(), problem, and oomph::DocInfo::set_directory().
Referenced by main().