MercuryDPM: oomph::RefineableQElement< 1 > Class Reference
oomph::RefineableQElement< 1 > Class Reference
#include <refineable_line_element.h>
Public Types
typedef void(RefineableQElement< 1 >::* VoidMemberFctPt) ()
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Member Functions
RefineableQElement ()
Constructor: Pass refinement level (default 0 = root)
RefineableQElement (const RefineableQElement< 1 > &dummy)=delete
Broken copy constructor.
virtual ~RefineableQElement ()
Broken assignment operator.
unsigned required_nsons () const
A refineable line element has two sons.
Node * node_created_by_neighbour (const Vector< double > &s_fraction, bool &is_periodic)
Node * node_created_by_son_of_neighbour (const Vector< double > &s_fraction, bool &is_periodic)
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)
void check_integrity (double &max_error)
void output_corners (std::ostream &outfile, const std::string &colour) const
Print corner nodes, using colour.
BinaryTree * binary_tree_pt ()
Pointer to binary tree representation of this element.
BinaryTree * binary_tree_pt () const
Pointer to binary tree representation of this element (const version)
void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
Line elements have no hanging nodes so this is deliberately left empty.
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void rebuild_from_sons (Mesh *&mesh_pt)=0
virtual void unbuild ()
virtual void deactivate_element ()
virtual bool nodes_built ()
Return true if all the nodes have been built, false if not.
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual unsigned ncont_interpolated_values () const =0
virtual void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
virtual void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)=0
virtual Node * interpolating_node_pt (const unsigned &n, const int &value_id)
virtual double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
virtual Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
virtual unsigned ninterpolating_node (const int &value_id)
virtual unsigned ninterpolating_node_1d (const int &value_id)
virtual void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual RefineableElement * root_element_pt ()
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
virtual void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
virtual void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
Pre-build the element.
virtual void further_build ()
Further build: e.g. deal with interpolation of internal values.
virtual void further_setup_hanging_nodes ()
void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
unsigned nshape_controlling_nodes ()
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (std::ostream &outfile)
virtual void output (std::ostream &outfile, const unsigned &n_plot)
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output (FILE *file_pt)
virtual void output (FILE *file_pt, const unsigned &n_plot)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::LineElementBase
LineElementBase ()
Constructor. Empty.
virtual unsigned nvertex_node () const =0
Number of vertex nodes in the element.
virtual Node * vertex_node_pt (const unsigned &j) const =0
Pointer to the j-th vertex node in the element.
Public Member Functions inherited from oomph::QElementBase
QElementBase ()
Constructor: Initialise pointers to macro element reference coords.
QElementBase (const QElementBase &)=delete
Broken copy constructor.
virtual ~QElementBase ()
Broken assignment operator.
bool local_coord_is_valid (const Vector< double > &s)
Check whether the local coordinate are valid or not.
void move_local_coord_back_into_element (Vector< double > &s) const
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
double & s_macro_ll (const unsigned &i)
double & s_macro_ur (const unsigned &i)
double s_macro_ll (const unsigned &i) const
double s_macro_ur (const unsigned &i) const
void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
unsigned nnode_on_face () const
ElementGeometry::ElementGeometry element_geometry () const
It's a Q element!
Public Member Functions inherited from oomph::QElementGeometricBase
QElementGeometricBase ()
Empty default constructor.
QElementGeometricBase (const QElementGeometricBase &)=delete
Broken copy constructor.
Protected Member Functions
void setup_father_bounds ()
void setup_hang_for_value (const int &value_id)
Line elements have no hanging nodes so this is deliberately left empty.
void binary_hang_helper (const int &value_id, const int &my_edge, std::ofstream &output_hangfile)
Line elements have no hanging nodes so this is deliberately left empty.
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Static Protected Attributes
static std::map< unsigned, DenseMatrix< int > > Father_bound
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Additional Inherited Members
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number – for plotting/validation purposes.
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
Refineable version of QElement<1,NNODE_1D>.
Refinement is performed by binary tree procedures. When the element is subdivided, the geometry of its sons is established by calls to their father's get_x(...) function which refers to:
the father element's geometric FE mapping (this is the default) or
a MacroElement's MacroElement::macro_map (if the pointer to the macro element is non-NULL)
The class provides a generic RefineableQElement<1>::build() function which deals with generic isoparametric QElements in which all values are associated with nodes. The RefineableQElement<1>::further_build() function provides an interface for any element-specific non-generic build operations.
Member Typedef Documentation
VoidMemberFctPt
typedef void(RefineableQElement<1>::* oomph::RefineableQElement< 1 >::VoidMemberFctPt) ()
Shorthand for pointer to an argument-free void member function of the refineable element
Constructor & Destructor Documentation
RefineableQElement() [1/2]
oomph::RefineableQElement< 1 >::RefineableQElement () inline
Constructor: Pass refinement level (default 0 = root)
                          : RefineableElement()
     {
 #ifdef LEAK_CHECK
       LeakCheckNames::RefineableQElement<1> _build += 1;
 #endif
     }
RefineableQElement() [2/2]
oomph::RefineableQElement< 1 >::RefineableQElement (const RefineableQElement< 1 > & dummy) delete
Broken copy constructor.
~RefineableQElement()
virtual oomph::RefineableQElement< 1 >::~RefineableQElement () inline virtual
Broken assignment operator.
Destructor
     {
 #ifdef LEAK_CHECK
       LeakCheckNames::RefineableQElement<1> _build -= 1;
 #endif
     }
Member Function Documentation
binary_hang_helper()
void oomph::RefineableQElement< 1 >::binary_hang_helper (const int & value_id, const int & my_edge, std::ofstream & output_hangfile) inline protected
Line elements have no hanging nodes so this is deliberately left empty.
     {
     }
binary_tree_pt() [1/2]
BinaryTree* oomph::RefineableQElement< 1 >::binary_tree_pt () inline
Pointer to binary tree representation of this element.
     {
       return dynamic_cast<BinaryTree*>(Tree_pt);
     }
binary_tree_pt() [2/2]
BinaryTree* oomph::RefineableQElement< 1 >::binary_tree_pt () const inline
Pointer to binary tree representation of this element (const version)
     {
       return dynamic_cast<BinaryTree*>(Tree_pt);
     }
build()
void oomph::RefineableQElement< 1 >::build (Mesh *& mesh_pt, Vector< Node * > & new_node_pt, bool & was_already_built, std::ofstream & new_nodes_file) virtual
Build the element, i.e. give it nodal positions, apply BCs, etc. Pointers to any new nodes will be returned in new_node_pt. If it is open, the positions of the new nodes will be written to the file stream new_nodes_file.
Build the element by doing the following:
Give it nodal positions (by establishing the pointers to its nodes). In the process create new nodes where required (i.e. if they don't already exist in the father element and have not already been created whilst building new neighbouring elements). Node building involves the following steps:
Get the nodal position from the father element.
Establish the time-history of the newly created nodal point (its coordinates and previous values) consistent with the father's history.
Add the new node to the mesh itself.
Doc newly created nodes in "new_nodes.dat" stored in the directory of the DocInfo object (only if it's open!).
NOTE: Unlike in higher-dimensional elements, in 1D it is impossible for newly-created nodes to be on a mesh boundary, since any boundary nodes must exist in the initial (coarse) mesh. Therefore it is not necessary to add any nodes to the mesh's boundary node storage schemes, and we always create normal "bulk" nodes.
Once the element has a full complement of nodes, excute the element- specific further_build() (empty by default – must be overloaded for specific elements). This deals with any build operations that are not included in the generic process outlined above. For instance, in Crouzeix Raviart elements we need to initialise the internal pressure pressure values in a manner consistent with the pressure distribution in the father element.
Implements oomph::RefineableElement.
Reimplemented in oomph::RefineableSolidQElement< 1 >.
   {
     using namespace BinaryTreeNames;
     // Find the number of nodes along a 1D edge (which is the number of nodes
     // in the element for a 1D element!)
     const unsigned n_node = nnode_1d();
     // Check whether static father_bound needs to be created
     if (Father_bound[n_node].nrow() == 0)
     {
       setup_father_bounds();
     }
     // Pointer to the current element's father (in binary tree impersonation)
     BinaryTree* father_pt =
       dynamic_cast<BinaryTree*>(binary_tree_pt()->father_pt());
     // What type of son is the current element?
     // Ask its binary tree representation...
     const int son_type = Tree_pt->son_type();
     // Has somebody built the current element already?
     // Check this by determining whether or not the first node has been built
     // If this element has not already been built...
     if (!nodes_built())
     {
 #ifdef PARANOID
       if (father_pt == 0)
       {
         std::string error_message =
           "Something fishy here: I have no father and yet \n";
         error_message += "I have no nodes. Who has created me then?!\n";
         throw OomphLibError(
           error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Indicate status
       was_already_built = false;
       // Return pointer to father element
       RefineableQElement<1>* father_el_pt =
         dynamic_cast<RefineableQElement<1>*>(father_pt->object_pt());
       // Timestepper should be the same for all nodes in father element.
       // Use it create timesteppers for new nodes.
       TimeStepper* time_stepper_pt =
         father_el_pt->node_pt(0)->time_stepper_pt();
       // Determine number of history values (including present)
       const unsigned ntstorage = time_stepper_pt->ntstorage();
       // Currently we can't handle the case of generalised coordinates
       // since we haven't established how they should be interpolated.
       // Buffer this case:
       if (father_el_pt->node_pt(0)->nposition_type() != 1)
       {
         throw OomphLibError("Can't handle generalised nodal positions (yet).",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       // Set up vertex coordinates in the father element:
       // ------------------------------------------------
       // Allocate storage for the vertex coordinates s_left and s_right of
       // the current element as viewed by this element's father (i.e. s_left[0]
       // stores the local coordinate within the father element at which the
       // node on the current element's left-hand edge is located. Likewise,
       // s_right[0] stores the local coordinate within the father element at
       // which the node on the current element's right-hand edge is located).
       Vector<double> s_left(1);
       Vector<double> s_right(1);
       // In order to set up the vertex coordinates we need to know which
       // type of son the current element is
       switch (son_type)
       {
         case L:
           s_left[0] = -1.0;
           s_right[0] = 0.0;
           break;
         case R:
           s_left[0] = 0.0;
           s_right[0] = 1.0;
           break;
       }
       // Pass macro element pointer on to sons and set coordinates in
       // macro element
       // hierher why can I see this?
       if (father_el_pt->Macro_elem_pt != 0)
       {
         set_macro_elem_pt(father_el_pt->Macro_elem_pt);
         s_macro_ll(0) =
           father_el_pt->s_macro_ll(0) +
           0.5 * (s_left[0] + 1.0) *
             (father_el_pt->s_macro_ur(0) - father_el_pt->s_macro_ll(0));
         s_macro_ur(0) =
           father_el_pt->s_macro_ll(0) +
           0.5 * (s_right[0] + 1.0) *
             (father_el_pt->s_macro_ur(0) - father_el_pt->s_macro_ll(0));
       }
       // If the father element hasn't been generated yet, we're stuck...
       if (father_el_pt->node_pt(0) == 0)
       {
         throw OomphLibError(
           "Trouble: father_el_pt->node_pt(0)==0\n Can't build son element!\n",
           OOMPH_CURRENT_FUNCTION,
           OOMPH_EXCEPTION_LOCATION);
       }
       // Otherwise, carry on
       else
       {
         // Allocate storage for the location of a node in terms of the local
         // coordinate of the father element
         Vector<double> s_in_father(1);
         // Allocate storage for the fractional position (in the current
         // element) of the node in the direction of s[0]
         Vector<double> s_fraction(1);
         // Loop over all nodes in the element
         for (unsigned n = 0; n < n_node; n++)
         {
           // Get the fractional position (in the current element) of the node
           // in the direction of s[0]
           s_fraction[0] = local_one_d_fraction_of_node(n, 0);
           // Evaluate the local coordinate of the node in the father element
           s_in_father[0] = s_left[0] + (s_right[0] - s_left[0]) * s_fraction[0];
           // Initialise flag: So far, this node hasn't been built or copied yet
           bool node_done = false;
           // Get the pointer to the node in the father (returns NULL if there
           // is no node at this position)
           Node* created_node_pt =
             father_el_pt->get_node_at_local_coordinate(s_in_father);
           // Does this node already exist in father element?
           // -----------------------------------------------
           // If it does...
           if (created_node_pt != 0)
           {
             // ...copy node across
             node_pt(n) = created_node_pt;
             // Make sure that we update the values at the node so that they
             // are consistent with the present representation. This is only
             // needed for mixed interpolation where the value at the father
             // could now become active.
             // Loop over all history values
             for (unsigned t = 0; t < ntstorage; t++)
             {
               // Get values from father element
               // Note: get_interpolated_values() sets Vector size itself
               Vector<double> prev_values;
               father_el_pt->get_interpolated_values(
                 t, s_in_father, prev_values);
               // Find the minimum number of values (either those stored at the
               // node, or those returned by the function)
               unsigned n_val_at_node = created_node_pt->nvalue();
               unsigned n_val_from_function = prev_values.size();
               // Use the ternary conditional operator here
               unsigned n_var = n_val_at_node < n_val_from_function ?
                                  n_val_at_node :
                                  n_val_from_function;
               // Assign the values that we can
               for (unsigned k = 0; k < n_var; k++)
               {
                 created_node_pt->set_value(t, k, prev_values[k]);
               }
             }
             // Indicate that node has been created by copy
             node_done = true;
           }
           // Node does not exist in father element but might already
           // -------------------------------------------------------
           // have been created by neighbouring elements
           // ------------------------------------------
           else
           {
             // Was the node created by one of its neighbours? Whether or not
             // the node lies on an edge can be calculated from the fractional
             // position.
             bool is_periodic = false;
             created_node_pt =
               node_created_by_neighbour(s_fraction, is_periodic);
             // If the node was so created...
             if (created_node_pt != 0)
             {
               // ...assign the pointer
               node_pt(n) = created_node_pt;
               // Indicate that node has been created by copy
               node_done = true;
               // In a 1D mesh there is no way that a periodic node (which must
               // be on a boundary) can exist without being part of the initial
               // (coarse) mesh. Therefore issue an error message if
               // node_created_by_neighbour(...) returns `is_periodic==true'.
 #ifdef PARANOID
               if (is_periodic)
               {
                 std::string error_message =
                   "node_created_by_neighbour returns a node which claims\n";
                 error_message += "to be periodic. In a 1D mesh any periodic "
                                  "nodes must exist\n";
                 error_message += "in the initial (coarse) mesh.";
                 throw OomphLibError(error_message,
                                     OOMPH_CURRENT_FUNCTION,
                                     OOMPH_EXCEPTION_LOCATION);
               }
 #endif
             }
           }
           // Node does not exist in father element or neighbouring element
           // -------------------------------------------------------------
           // If the node has not been built anywhere ---> build it here
           if (!node_done)
           {
             // In a 1D mesh any node which lies on the boundary must exist in
             // the initial (coarse) mesh, so any newly-built nodes cannot be
             // boundary nodes. Therefore we always create a normal "bulk" node.
             // Create node and set the pointer to it from the element
             created_node_pt = construct_node(n, time_stepper_pt);
             // Add to vector of new nodes
             new_node_pt.push_back(created_node_pt);
             // Now we set the position and values at the newly created node.
             // In the first instance use macro element or FE representation
             // to create past and present nodal positions.
             // (THIS STEP SHOULD NOT BE SKIPPED FOR ALGEBRAIC ELEMENTS AS NOT
             // ALL OF THEM NECESSARILY IMPLEMENT NONTRIVIAL NODE UPDATE
             // FUNCTIONS. CALLING THE NODE UPDATE FOR SUCH ELEMENTS/NODES WILL
             // LEAVE THEIR NODAL POSITIONS WHERE THEY WERE (THIS IS APPROPRIATE
             // ONCE THEY HAVE BEEN GIVEN POSITIONS) BUT WILL NOT ASSIGN SENSIBLE
             // INITIAL POSITIONS!)
             // Loop over history values
             for (unsigned t = 0; t < ntstorage; t++)
             {
               // Allocate storage for the previous position of the node
               Vector<double> x_prev(1);
               // Get position from father element -- this uses the macro
               // element representation if appropriate.
               father_el_pt->get_x(t, s_in_father, x_prev);
               // Set the previous position of the new node
               created_node_pt->x(t, 0) = x_prev[0];
               // Allocate storage for the previous values at the node
               // NOTE: the size of this vector is equal to the number of values
               // (e.g. 3 velocity components and 1 pressure, say)
               // associated with each node and NOT the number of history values
               // which the node stores!
               Vector<double> prev_values;
               // Get values from father element
               // Note: get_interpolated_values() sets Vector size itself.
               father_el_pt->get_interpolated_values(
                 t, s_in_father, prev_values);
               // Determine the number of values at the new node
               const unsigned n_value = created_node_pt->nvalue();
               // Loop over all values and set the previous values
               for (unsigned v = 0; v < n_value; v++)
               {
                 created_node_pt->set_value(t, v, prev_values[v]);
               }
             } // End of loop over history values
             // Add new node to mesh
             mesh_pt->add_node_pt(created_node_pt);
           } // End of case where we build the node ourselves
           // Check if the element is an algebraic element
           AlgebraicElementBase* alg_el_pt =
             dynamic_cast<AlgebraicElementBase*>(this);
           // If it is, set up node position (past and present) from algebraic
           // node position (past and present) from algebraic node update
           // node update function. This over-writes previous assingments that
           // were made based on the macro-element/FE representation.
           // NOTE: YES, THIS NEEDS TO BE CALLED REPEATEDLY IF THE NODE IS A
           // MEMBER OF MULTIPLE ELEMENTS: THEY ALL ASSIGN THE SAME NODAL
           // POSITIONS BUT WE NEED TO ADD THE REMESH INFO FOR *ALL* ROOT
           // ELEMENTS!
           if (alg_el_pt != 0)
           {
             // Build algebraic node update info for new node. This sets up
             // the node update data for all node update functions that are
             // shared by all nodes in the father element.
             alg_el_pt->setup_algebraic_node_update(
               node_pt(n), s_in_father, father_el_pt);
           }
           // If we have built the node and we are documenting our progress,
           // write the (hopefully consistent position) to the outputfile
           if ((!node_done) && (new_nodes_file.is_open()))
           {
             new_nodes_file << node_pt(n)->x(0) << std::endl;
           }
         } // End of loop over all nodes in element
         // If the element is a MacroElementNodeUpdateElement, set the update
         // parameters for the current element's nodes -- all this needs is
         // the vector of (pointers to the) geometric objects that affect the
         // MacroElement-based node update. This is the same as that in the
         // father element
         MacroElementNodeUpdateElementBase* father_m_el_pt =
           dynamic_cast<MacroElementNodeUpdateElementBase*>(father_el_pt);
         if (father_m_el_pt != 0)
         {
           // Get Vector of geometric objects from father (construct Vector
           // via copy operation)
           Vector<GeomObject*> geom_object_pt(father_m_el_pt->geom_object_pt());
           // Cast current element to MacroElementNodeUpdateElement:
           MacroElementNodeUpdateElementBase* m_el_pt =
             dynamic_cast<MacroElementNodeUpdateElementBase*>(this);
 #ifdef PARANOID
           if (m_el_pt == 0)
           {
             std::string error_message =
               "Failed to cast to MacroElementNodeUpdateElementBase*\n";
             error_message +=
               "Strange -- if the father is a MacroElementNodeUpdateElement\n";
             error_message += "the son should be too....\n";
             throw OomphLibError(
               error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
           }
 #endif
           // Build update info by passing Vector of geometric objects:
           // This sets the current element to be the update element for all
           // of the element's nodes. This is reversed if the element is
           // ever un-refined in the father element's rebuild_from_sons()
           // function which overwrites this assignment to avoid nasty
           // segmentation faults that occur when a node tries to update
           // itself via an element that no longer exists...
           m_el_pt->set_node_update_info(geom_object_pt);
         }
 #ifdef OOMPH_HAS_MPI
         // Pass on non-halo proc ID
         Non_halo_proc_ID =
           tree_pt()->father_pt()->object_pt()->non_halo_proc_ID();
 #endif
         // Is the new element an ElementWithMovingNodes?
         ElementWithMovingNodes* aux_el_pt =
           dynamic_cast<ElementWithMovingNodes*>(this);
         // Pass down the information re the method for the evaluation
         // of the shape derivatives
         if (aux_el_pt != 0)
         {
           ElementWithMovingNodes* aux_father_el_pt =
             dynamic_cast<ElementWithMovingNodes*>(father_el_pt);
 #ifdef PARANOID
           if (aux_father_el_pt == 0)
           {
             std::string error_message =
               "Failed to cast to ElementWithMovingNodes*\n";
             error_message +=
               "Strange -- if the son is a ElementWithMovingNodes\n";
             error_message += "the father should be too....\n";
             throw OomphLibError(
               error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
           }
 #endif
           // If evaluating the residuals by finite differences in the father
           // continue to do so in the child
           if (aux_father_el_pt
                 ->are_dresidual_dnodal_coordinates_always_evaluated_by_fd())
           {
             aux_el_pt
               ->enable_always_evaluate_dresidual_dnodal_coordinates_by_fd();
           }
           aux_el_pt->method_for_shape_derivs() =
             aux_father_el_pt->method_for_shape_derivs();
           // If bypassing the evaluation of fill_in_jacobian_from_geometric_data
           // continue to do so
           if (aux_father_el_pt
                 ->is_fill_in_jacobian_from_geometric_data_bypassed())
           {
             aux_el_pt->enable_bypass_fill_in_jacobian_from_geometric_data();
           }
         }
         // Now do further build (if any)
         further_build();
       } // Sanity check: Father element has been generated
     } // End of if element has not already been built
     // If element has already been built, say so
     else
     {
       was_already_built = true;
     }
   }
References oomph::Mesh::add_node_pt(), oomph::ElementWithMovingNodes::enable_always_evaluate_dresidual_dnodal_coordinates_by_fd(), oomph::ElementWithMovingNodes::enable_bypass_fill_in_jacobian_from_geometric_data(), oomph::MacroElementNodeUpdateElementBase::geom_object_pt(), oomph::RefineableElement::get_interpolated_values(), oomph::FiniteElement::get_node_at_local_coordinate(), oomph::FiniteElement::get_x(), k, L, oomph::FiniteElement::Macro_elem_pt, oomph::ElementWithMovingNodes::method_for_shape_derivs(), n, oomph::FiniteElement::node_pt(), oomph::Node::nposition_type(), oomph::Data::nvalue(), oomph::Tree::object_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, R, oomph::QElementBase::s_macro_ll(), oomph::QElementBase::s_macro_ur(), oomph::MacroElementNodeUpdateElementBase::set_node_update_info(), oomph::Data::set_value(), oomph::AlgebraicElementBase::setup_algebraic_node_update(), oomph::Tree::son_type(), oomph::Global_string_for_annotation::string(), plotPSD::t, oomph::Data::time_stepper_pt(), v, and oomph::Node::x().
check_integrity()
void oomph::RefineableQElement< 1 >::check_integrity (double & max_error) virtual
Check the integrity of the element: ensure that the position and values are continuous across the element edges.
Check inter-element continuity of
nodal positions
(nodally) interpolated function values
Implements oomph::RefineableElement.
   {
     using namespace BinaryTreeNames;
     // Calculate number of nodes
     const unsigned n_node = nnode_1d();
     // Number of timesteps (including present) for which continuity is
     // to be checked
     const unsigned n_time = 1;
     // Initialise errors
     max_error = 0.0;
     Vector<double> max_error_x(1, 0.0);
     double max_error_val = 0.0;
     // Initialise vector of element edges in the current element
     Vector<int> edge_in_current(2);
     edge_in_current[0] = L;
     edge_in_current[1] = R;
     // Loop over both edges
     for (unsigned edge_counter = 0; edge_counter < 2; edge_counter++)
     {
       // Allocate storage for the fractional position (in the current
       // element) of the node in the direction of s[0]
       Vector<double> s_fraction(1);
       // Allocate storage for the location of a node in terms of the local
       // coordinate of the current element
       Vector<double> s_in_current(1);
       // Allocate storage for the location of a node in terms of the local
       // coordinate of the neighbouring element
       Vector<double> s_in_neighbour(1);
       // Allocate storage for edge in neighbouring element
       int edge_in_neighbour;
       // Allocate storage for difference in size between current and
       // neighbouring element
       int diff_level;
       // Allocate storage for flag indicating if the node is not in the same
       // binary tree
       bool in_neighbouring_tree;
       // Calculate the local coordinate and the local coordinate as viewed
       // from the neighbour
       // Allocate storage for the pointer to the neighbouring element
       // (using its binary tree representation)
       BinaryTree* neighbour_pt;
       // Find pointer to neighbouring element along the edge in question and
       // calculate the local coordinate of the node within that element,
       // s_in_neighbour
       neighbour_pt =
         binary_tree_pt()->gteq_edge_neighbour(edge_in_current[edge_counter],
                                               s_in_neighbour,
                                               edge_in_neighbour,
                                               diff_level,
                                               in_neighbouring_tree);
       // If neighbour exists and has existing nodes
       if ((neighbour_pt != 0) && (neighbour_pt->object_pt()->nodes_built()))
       {
         // Need to exclude periodic nodes from this check.
         // There are only periodic nodes if we are in a neighbouring tree...
         bool is_periodic = false;
         if (in_neighbouring_tree)
         {
           // Is it periodic?
           is_periodic = tree_pt()->root_pt()->is_neighbour_periodic(
             edge_in_current[edge_counter]);
         }
         // Allocate storage for pointer to the local node
         Node* local_node_pt = 0;
         switch (edge_counter)
         {
           case 0:
             // Local fraction of node
             s_fraction[0] = 0.0;
             // Get pointer to local node
             local_node_pt = node_pt(0);
             break;
           case 1:
             // Local fraction of node
             s_fraction[0] = 1.0;
             // Get pointer to local node
             local_node_pt = node_pt(n_node - 1);
             break;
         }
         // Evaluate the local coordinate of the node in the current element
         s_in_current[0] = -1.0 + 2.0 * s_fraction[0];
         // NOTE: We have already calculated the local coordinate of the node
         // in the neighbouring element above when calling gteq_edge_neighbour()
         // Loop over timesteps
         for (unsigned t = 0; t < n_time; t++)
         {
           // Allocate storage for the nodal position in the neighbouring element
           Vector<double> x_in_neighbour(1);
           // Get the nodal position from the neighbouring element
           neighbour_pt->object_pt()->interpolated_x(
             t, s_in_neighbour, x_in_neighbour);
           // Check error only if the node is NOT periodic
           if (is_periodic == false)
           {
             // Find the spatial error
             double err = std::fabs(local_node_pt->x(t, 0) - x_in_neighbour[0]);
             // If it's bigger than our tolerance, say so
             if (err > 1e-9)
             {
               oomph_info << "errx " << err << " " << t << " "
                          << local_node_pt->x(t, 0) << " " << x_in_neighbour[0]
                          << std::endl;
               oomph_info << "at " << local_node_pt->x(0) << std::endl;
             }
             // If it's bigger than the previous max error, it is the
             // new max error!
             if (err > max_error_x[0])
             {
               max_error_x[0] = err;
             }
           }
           // Allocate storage for the nodal values in the neighbouring element
           Vector<double> values_in_neighbour;
           // Get the values from neighbouring element. NOTE: Number of values
           // gets set by routine (because in general we don't know how many
           // interpolated values a certain element has.
           neighbour_pt->object_pt()->get_interpolated_values(
             t, s_in_neighbour, values_in_neighbour);
           // Allocate storage for the nodal values in the current element
           Vector<double> values_in_current;
           // Get the values in current element
           get_interpolated_values(t, s_in_current, values_in_current);
           // Now figure out how many continuously interpolated values there are
           const unsigned num_val =
             neighbour_pt->object_pt()->ncont_interpolated_values();
           // Check error
           for (unsigned ival = 0; ival < num_val; ival++)
           {
             // Find the spatial error
             double err =
               std::fabs(values_in_current[ival] - values_in_neighbour[ival]);
             // If it's bigger than our tolerance, say so
             if (err > 1.0e-10)
             {
               oomph_info << local_node_pt->x(0) << "\n# "
                          << "erru " << err << " " << ival << " "
                          << get_node_number(local_node_pt) << " "
                          << values_in_current[ival] << " "
                          << values_in_neighbour[ival] << std::endl;
             }
             // If it's bigger than the previous max error, it is the
             // new max error!
             if (err > max_error_val)
             {
               max_error_val = err;
             }
           }
         } // End of loop over timesteps
       } // End of if neighbour exists and has existing nodes
     } // End of loop over edges
     // Update max_error if necessary
     max_error = max_error_x[0];
     if (max_error_val > max_error)
     {
       max_error = max_error_val;
     }
     // Output max_error information
     if (max_error > 1e-9)
     {
       oomph_info << "\n#------------------------------------ \n#Max error ";
       oomph_info << max_error_x[0] << " " << max_error_val << std::endl;
       oomph_info << "#------------------------------------ \n " << std::endl;
     }
   }
References e(), boost::multiprecision::fabs(), oomph::RefineableElement::get_interpolated_values(), oomph::BinaryTree::gteq_edge_neighbour(), oomph::FiniteElement::interpolated_x(), L, MeshRefinement::max_error, oomph::RefineableElement::ncont_interpolated_values(), oomph::RefineableElement::nodes_built(), oomph::Tree::object_pt(), oomph::oomph_info, R, plotPSD::t, and oomph::Node::x().
node_created_by_neighbour()
Node * oomph::RefineableQElement< 1 >::node_created_by_neighbour (const Vector< double > & s_fraction, bool & is_periodic)
If a neighbouring element has already created a node at a position corresponding to the local fractional position within the present element, s_fraction, return a pointer to that node. If not, return NULL (0). If the node is on a periodic boundary the flag is_periodic is true, otherwise it will be false.
If a neighbouring element has already created a node at a position corresponding to the local fractional position within the present element, s_fraction, return a pointer to that node. If not, return NULL (0). If the node is periodic the flag is_periodic will be true.
   {
     using namespace BinaryTreeNames;
     // Initialise edge of current element on which node lies
     int edge_in_current = OMEGA;
     // Determine the edge of the current element on which the node lies
     if (s_fraction[0] == 0.0)
     {
       edge_in_current = L;
     }
     if (s_fraction[0] == 1.0)
     {
       edge_in_current = R;
     }
     // If the node does not lie on an edge then there is no neighbour:
     // return NULL
     if (edge_in_current == OMEGA)
     {
       return 0;
     }
     // Allocate storage for edge in neighbouring element
     int edge_in_neighbour;
     // Allocate storage for difference in size between current and
     // neighbouring element
     int diff_level;
     // Allocate storage for local coordinate of node in neighbouring tree
     Vector<double> s_in_neighbour(1);
     // Allocate storage for flag indicating if the node is not in the same
     // binary tree
     bool in_neighbouring_tree;
     // Allocate storage for the pointer to the neighbouring element
     // (using its binary tree representation)
     BinaryTree* neighbour_pt;
     // Find pointer to neighbouring element along the edge in question and
     // calculate the local coordinate of the node within that element
     // s_in_neighbour
     neighbour_pt = binary_tree_pt()->gteq_edge_neighbour(edge_in_current,
                                                          s_in_neighbour,
                                                          edge_in_neighbour,
                                                          diff_level,
                                                          in_neighbouring_tree);
     // If a neighbour exists...
     if (neighbour_pt != 0)
     {
       // ...check whether its nodes have been created yet
       if (neighbour_pt->object_pt()->nodes_built())
       {
         // If they have, find the node in question in the neighbour
         Node* neighbour_node_pt =
           neighbour_pt->object_pt()->get_node_at_local_coordinate(
             s_in_neighbour);
         // If there is no node at this position, there is a problem, since in
         // a 1D element (whose nodes have already been built) there should
         // ALWAYS be a node at each edge of the element.
         if (neighbour_node_pt == 0)
         {
           std::string error_message =
             "Problem: an element claims to have had its nodes built, yet\n";
           error_message += "it is missing (a least) a node at its edge.\n";
           throw OomphLibError(
             error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
         }
         // Otherwise, carry on
         else
         {
           // Now work out whether it's a periodic boundary (this is only
           // (possible if we have moved into a neighbouring tree)
           if (in_neighbouring_tree)
           {
             // Return whether the neighbour is periodic
             is_periodic = binary_tree_pt()->root_pt()->is_neighbour_periodic(
               edge_in_current);
           }
           // Return the pointer to the neighbouring node
           return neighbour_node_pt;
         }
       }
     }
     // Node not found, return null
     return 0;
   }
References oomph::FiniteElement::get_node_at_local_coordinate(), oomph::BinaryTree::gteq_edge_neighbour(), L, oomph::RefineableElement::nodes_built(), oomph::Tree::object_pt(), oomph::BinaryTreeNames::OMEGA, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, R, and oomph::Global_string_for_annotation::string().
node_created_by_son_of_neighbour()
Node* oomph::RefineableQElement< 1 >::node_created_by_son_of_neighbour (const Vector< double > & s_fraction, bool & is_periodic) inline
If a neighbouring element has already created a node at a position corresponding to the local fractional position within the present element, s_fraction, return a pointer to that node. If not, return NULL (0). If the node is on a periodic boundary the flag is_periodic is true, otherwise it will be false.
     {
       // It is impossible for this situation to arise in meshes
       // containing elements of uniform p-order. This is here so
       // that it can be overloaded for p-refineable elements.
       return 0;
     }
output_corners()
void oomph::RefineableQElement< 1 >::output_corners (std::ostream & outfile, const std::string & colour) const
Print corner nodes, using colour.
Print corner nodes, use colour (default "BLACK")
   {
     // Allocate storage for local coordinate s
     Vector<double> s(1);
     // Allocate storage for global coordinate of element vertex
     Vector<double> vertex(1);
     outfile << "ZONE I=2,J=2, C=" << colour << std::endl;
     // Left-hand vertex
     s[0] = -1.0;
     get_x(s, vertex);
     outfile << vertex[0] << " " << Number << std::endl;
     // Right-hand vertex
     s[0] = 1.0;
     get_x(s, vertex);
     outfile << vertex[0] << " " << Number << std::endl;
     outfile << "TEXT  CS = GRID, X = " << vertex[0]
             << ", HU = GRID, H = 0.01, AN = MIDCENTER, T =\"" << Number << "\""
             << std::endl;
   }
References oomph::TecplotNames::colour, oomph::Global_unsigned::Number, and s.
required_nsons()
unsigned oomph::RefineableQElement< 1 >::required_nsons () const inline virtual
A refineable line element has two sons.
Reimplemented from oomph::RefineableElement.
     {
       return 2;
     }
setup_father_bounds()
void oomph::RefineableQElement< 1 >::setup_father_bounds () protected
Setup static matrix for coincidence between son nodal points and father boundaries
Setup static matrix for coincidence between son nodal points and father boundaries:
Father_bound[nnode_1d](nnode_son,son_type) = {L/R/OMEGA}
so that node nnode_son in element of type son_type lies on boundary/ vertex Father_bound[nnode_1d](nnode_son,son_type) in its father element. If the node doesn't lie on a boundary the value is OMEGA.
   {
     using namespace BinaryTreeNames;
     // Find the number of nodes along a 1D edge (which is the number of nodes
     // in the element for a 1D element!)
     const unsigned n_node = nnode_1d();
     // Allocate space for the boundary information
     Father_bound[n_node].resize(n_node, 2);
     // Initialise: By default points are not on the boundary
     for (unsigned n = 0; n < n_node; n++)
     {
       for (unsigned ison = 0; ison < 2; ison++)
       {
         Father_bound[n_node](n, ison) = Tree::OMEGA;
       }
     }
     // Left-hand son:
     // --------------
     // L node (0) is the L node of the parent
     Father_bound[n_node](0, L) = L;
     // Other boundary is in the interior
     // Right-hand son:
     // ---------------
     // R node (n_node-1) is the R node of the parent
     Father_bound[n_node](n_node - 1, R) = R;
     // Other boundary is in the interior
   }
References L, n, oomph::Tree::OMEGA, and R.
setup_hang_for_value()
void oomph::RefineableQElement< 1 >::setup_hang_for_value (const int & value_id) inline protected
Line elements have no hanging nodes so this is deliberately left empty.
 {}
setup_hanging_nodes()
void oomph::RefineableQElement< 1 >::setup_hanging_nodes (Vector< std::ofstream * > & output_stream) inline virtual
Line elements have no hanging nodes so this is deliberately left empty.
Reimplemented from oomph::RefineableElement.
 {}
Member Data Documentation
Father_bound
std::map< unsigned, DenseMatrix< int > > oomph::RefineableQElement< 1 >::Father_bound static protected
Coincidence between son nodal points and father boundaries: Father_bound[node_1d](jnod_son,son_type) = {L/R/OMEGA}
Static matrix for coincidence between son nodal points and father boundaries
The documentation for this class was generated from the following files:
refineable_line_element.h
refineable_line_element.cc