MercuryDPM: Eigen::internal::TensorLazyBaseEvaluator< Dimensions, Scalar > Class Template Reference
Eigen::internal::TensorLazyBaseEvaluator< Dimensions, Scalar > Class Template Reference abstract
#include <TensorRef.h>
Public Member Functions
TensorLazyBaseEvaluator ()
virtual ~TensorLazyBaseEvaluator ()
virtual EIGEN_DEVICE_FUNC const Dimensions & dimensions () const =0
virtual EIGEN_DEVICE_FUNC const Scalar * data () const =0
virtual EIGEN_DEVICE_FUNC const Scalar coeff (DenseIndex index) const =0
virtual EIGEN_DEVICE_FUNC Scalar & coeffRef (DenseIndex index)=0
void incrRefCount ()
void decrRefCount ()
int refCount () const
Private Member Functions
TensorLazyBaseEvaluator (const TensorLazyBaseEvaluator &other)
TensorLazyBaseEvaluator & operator= (const TensorLazyBaseEvaluator &other)
Private Attributes
int m_refcount
Constructor & Destructor Documentation
TensorLazyBaseEvaluator() [1/2]
template<typename Dimensions , typename Scalar > Eigen::internal::TensorLazyBaseEvaluator< Dimensions, Scalar >::TensorLazyBaseEvaluator () inline
 : m_refcount(0) {}
~TensorLazyBaseEvaluator()
template<typename Dimensions , typename Scalar > virtual Eigen::internal::TensorLazyBaseEvaluator< Dimensions, Scalar >::~TensorLazyBaseEvaluator () inline virtual
 {}
TensorLazyBaseEvaluator() [2/2]
template<typename Dimensions , typename Scalar > Eigen::internal::TensorLazyBaseEvaluator< Dimensions, Scalar >::TensorLazyBaseEvaluator (const TensorLazyBaseEvaluator< Dimensions, Scalar > & other) private
Member Function Documentation
coeff()
template<typename Dimensions , typename Scalar > virtual EIGEN_DEVICE_FUNC const Scalar Eigen::internal::TensorLazyBaseEvaluator< Dimensions, Scalar >::coeff (DenseIndex index) const pure virtual
Implemented in Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >.
coeffRef()
template<typename Dimensions , typename Scalar > virtual EIGEN_DEVICE_FUNC Scalar& Eigen::internal::TensorLazyBaseEvaluator< Dimensions, Scalar >::coeffRef (DenseIndex index) pure virtual
Implemented in Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >, and Eigen::internal::TensorLazyEvaluatorWritable< Dimensions, Expr, Device >.
data()
template<typename Dimensions , typename Scalar > virtual EIGEN_DEVICE_FUNC const Scalar* Eigen::internal::TensorLazyBaseEvaluator< Dimensions, Scalar >::data () const pure virtual
Implemented in Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
decrRefCount()
template<typename Dimensions , typename Scalar > void Eigen::internal::TensorLazyBaseEvaluator< Dimensions, Scalar >::decrRefCount () inline
 { --m_refcount; }
References Eigen::internal::TensorLazyBaseEvaluator< Dimensions, Scalar >::m_refcount.
dimensions()
template<typename Dimensions , typename Scalar > virtual EIGEN_DEVICE_FUNC const Dimensions& Eigen::internal::TensorLazyBaseEvaluator< Dimensions, Scalar >::dimensions () const pure virtual
Implemented in Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >.
incrRefCount()
template<typename Dimensions , typename Scalar > void Eigen::internal::TensorLazyBaseEvaluator< Dimensions, Scalar >::incrRefCount () inline
 { ++m_refcount; }
References Eigen::internal::TensorLazyBaseEvaluator< Dimensions, Scalar >::m_refcount.
operator=()
template<typename Dimensions , typename Scalar > TensorLazyBaseEvaluator& Eigen::internal::TensorLazyBaseEvaluator< Dimensions, Scalar >::operator= (const TensorLazyBaseEvaluator< Dimensions, Scalar > & other) private
refCount()
template<typename Dimensions , typename Scalar > int Eigen::internal::TensorLazyBaseEvaluator< Dimensions, Scalar >::refCount () const inline
 { return m_refcount; }
References Eigen::internal::TensorLazyBaseEvaluator< Dimensions, Scalar >::m_refcount.
Member Data Documentation
m_refcount
template<typename Dimensions , typename Scalar > int Eigen::internal::TensorLazyBaseEvaluator< Dimensions, Scalar >::m_refcount private
Referenced by Eigen::internal::TensorLazyBaseEvaluator< Dimensions, Scalar >::decrRefCount(), Eigen::internal::TensorLazyBaseEvaluator< Dimensions, Scalar >::incrRefCount(), and Eigen::internal::TensorLazyBaseEvaluator< Dimensions, Scalar >::refCount().
The documentation for this class was generated from the following file:
TensorRef.h