MercuryDPM: oomph::RefineableQuadMeshWithMovingCylinder< ELEMENT > Class Template Reference
oomph::RefineableQuadMeshWithMovingCylinder< ELEMENT > Class Template Reference
My Mesh.
#include <rectangle_with_moving_cylinder_mesh.template.h>
Public Member Functions
RefineableQuadMeshWithMovingCylinder (GeomObject *cylinder_pt, const double &annular_region_radius, const double &length_of_central_box, const double &x_left, const double &x_right, const double &height, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
~RefineableQuadMeshWithMovingCylinder ()
Public Member Functions inherited from oomph::RefineableQuadMesh< ELEMENT >
RefineableQuadMesh ()
Constructor: Setup static quadtree data.
RefineableQuadMesh (const RefineableQuadMesh &dummy)=delete
Broken copy constructor.
virtual ~RefineableQuadMesh ()
Broken assignment operator.
virtual void setup_tree_forest ()
void setup_quadtree_forest ()
Public Member Functions inherited from oomph::TreeBasedRefineableMesh< ELEMENT >
TreeBasedRefineableMesh ()
Constructor, call the constructor of the base class.
TreeBasedRefineableMesh (const TreeBasedRefineableMesh &dummy)=delete
Broken copy constructor.
virtual ~TreeBasedRefineableMesh ()
Empty virtual destructor.
Public Member Functions inherited from oomph::TreeBasedRefineableMeshBase
TreeBasedRefineableMeshBase ()
Constructor.
TreeBasedRefineableMeshBase (const TreeBasedRefineableMeshBase &dummy)=delete
Broken copy constructor.
void operator= (const TreeBasedRefineableMeshBase &)=delete
Broken assignment operator.
virtual ~TreeBasedRefineableMeshBase ()
Empty Destructor:
void adapt (const Vector< double > &elemental_error)
void p_adapt (const Vector< double > &elemental_error)
void refine_uniformly (DocInfo &doc_info)
Refine mesh uniformly and doc process.
void refine_uniformly ()
Refine mesh uniformly.
void p_refine_uniformly (DocInfo &doc_info)
p-refine mesh uniformly and doc process
void p_refine_uniformly ()
p-refine mesh uniformly
unsigned unrefine_uniformly ()
void p_unrefine_uniformly (DocInfo &doc_info)
p-unrefine mesh uniformly
TreeForest * forest_pt ()
Return pointer to the Forest represenation of the mesh.
void doc_adaptivity_targets (std::ostream &outfile)
Doc the targets for mesh adaptation.
unsigned & max_refinement_level ()
Access fct for max. permissible refinement level (relative to base mesh)
unsigned & min_refinement_level ()
Access fct for min. permissible refinement level (relative to base mesh)
unsigned & max_p_refinement_level ()
unsigned & min_p_refinement_level ()
virtual void adapt_mesh (DocInfo &doc_info)
virtual void adapt_mesh ()
void p_adapt_mesh (DocInfo &doc_info)
void p_adapt_mesh ()
virtual void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
virtual void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
p-refine mesh by refining the elements identified by their numbers.
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
p-refine mesh by refining the elements identified by their pointers.
virtual void refine_base_mesh_as_in_reference_mesh (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
Refine to same degree as the reference mesh.
virtual bool refine_base_mesh_as_in_reference_mesh_minus_one (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
virtual void refine_as_in_reference_mesh (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
virtual void get_refinement_levels (unsigned &min_refinement_level, unsigned &max_refinement_level)
Get max/min refinement levels in mesh.
virtual void get_elements_at_refinement_level (unsigned &refinement_level, Vector< RefineableElement * > &level_elements)
virtual void get_refinement_pattern (Vector< Vector< unsigned >> &to_be_refined)
void refine_base_mesh (Vector< Vector< unsigned >> &to_be_refined)
Refine base mesh according to specified refinement pattern.
virtual void refine (std::ifstream &restart_file)
Refine mesh according to refinement pattern in restart file.
virtual void dump_refinement (std::ostream &outfile)
Dump refinement pattern to allow for rebuild.
virtual void read_refinement (std::ifstream &restart_file, Vector< Vector< unsigned >> &to_be_refined)
Read refinement pattern to allow for rebuild.
unsigned uniform_refinement_level_when_pruned () const
unsigned & uniform_refinement_level_when_pruned ()
Level to which the mesh was uniformly refined when it was pruned.
Public Member Functions inherited from oomph::RefineableMeshBase
bool adapt_flag ()
RefineableMeshBase ()
RefineableMeshBase (const RefineableMeshBase &dummy)=delete
Broken copy constructor.
void operator= (const RefineableMeshBase &)=delete
Broken assignment operator.
virtual ~RefineableMeshBase ()
Empty Destructor:
unsigned nrefined ()
Access fct for number of elements that were refined.
unsigned nunrefined ()
Access fct for number of elements that were unrefined.
unsigned & nrefinement_overruled ()
unsigned & max_keep_unrefined ()
ErrorEstimator *& spatial_error_estimator_pt ()
Access to spatial error estimator.
ErrorEstimator * spatial_error_estimator_pt () const
Access to spatial error estimator (const version.
double & min_permitted_error ()
double & max_permitted_error ()
double & min_error ()
double & max_error ()
DocInfo *& doc_info_pt ()
Access fct for pointer to DocInfo.
void enable_adaptation ()
Enable adaptation.
void disable_adaptation ()
Disable adaptation.
void enable_p_adaptation ()
Enable adaptation.
void disable_p_adaptation ()
Disable adaptation.
void enable_additional_synchronisation_of_hanging_nodes ()
Enable additional synchronisation of hanging nodes.
void disable_additional_synchronisation_of_hanging_nodes ()
Disable additional synchronisation of hanging nodes.
bool is_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_p_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_additional_synchronisation_of_hanging_nodes_disabled () const
Return whether additional synchronisation is enabled.
DocInfo doc_info ()
Access fct for DocInfo.
void p_unrefine_uniformly (DocInfo &doc_info)
p-unrefine mesh uniformly
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Public Member Functions inherited from oomph::QuadMeshBase
QuadMeshBase ()
Constructor (empty)
QuadMeshBase (const QuadMeshBase &node)=delete
Broken copy constructor.
void operator= (const QuadMeshBase &)=delete
Broken assignment operator.
virtual ~QuadMeshBase ()
Destructor (empty)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Private Attributes
RefineableRectangleWithHoleAndAnnularRegionMesh< ELEMENT > * Central_mesh_pt
bool Coarse_problem
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::TreeBasedRefineableMeshBase
void complete_hanging_nodes (const int &ncont_interpolated_values)
Complete the hanging node scheme recursively.
void complete_hanging_nodes_recursively (Node *&nod_pt, Vector< Node * > &master_nodes, Vector< double > &hang_weights, const int &ival)
Auxiliary routine for recursive hanging node completion.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes inherited from oomph::TreeBasedRefineableMeshBase
unsigned Uniform_refinement_level_when_pruned
Level to which the mesh was uniformly refined when it was pruned.
unsigned Max_refinement_level
Max. permissible refinement level (relative to base mesh)
unsigned Min_refinement_level
Min. permissible refinement level (relative to base mesh)
unsigned Max_p_refinement_level
Max. permissible p-refinement level (relative to base mesh)
unsigned Min_p_refinement_level
Min. permissible p-refinement level (relative to base mesh)
TreeForest * Forest_pt
Forest representation of the mesh.
Protected Attributes inherited from oomph::RefineableMeshBase
ErrorEstimator * Spatial_error_estimator_pt
Pointer to spatial error estimator.
double Max_permitted_error
Max. error (i.e. split elements if their error is larger)
double Min_permitted_error
Min. error (i.e. (try to) merge elements if their error is smaller)
double Min_error
Min.actual error.
double Max_error
Max. actual error.
unsigned Nrefined
Stats: Number of elements that were refined.
unsigned Nunrefined
Stats: Number of elements that were unrefined.
bool Adapt_flag
Flag that requests adaptation.
bool P_adapt_flag
Flag that requests p-adaptation.
bool Additional_synchronisation_of_hanging_nodes_not_required
Flag that disables additional synchronisation of hanging nodes.
DocInfo * Doc_info_pt
Pointer to DocInfo.
unsigned Max_keep_unrefined
unsigned Nrefinement_overruled
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Detailed Description
template<class ELEMENT>
class oomph::RefineableQuadMeshWithMovingCylinder< ELEMENT >
My Mesh.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
RefineableQuadMeshWithMovingCylinder()
template<class ELEMENT > oomph::RefineableQuadMeshWithMovingCylinder< ELEMENT >::RefineableQuadMeshWithMovingCylinder (GeomObject * cylinder_pt, const double & annular_region_radius, const double & length_of_central_box, const double & x_left, const double & x_right, const double & height, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor. Pass pointer to geometric object that represents the cylinder; hierher the length and height of the domain. The GeomObject must be parametrised such that \(\zeta \in [0,2\pi]\) sweeps around the circumference in anticlockwise direction. Timestepper defaults to Steady default timestepper.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Constructor. Pass pointer to geometric object that represents the cylinder; hierher the length and height of the domain. The GeomObject must be parametrised such that \(\zeta \in [0,2\pi]\) sweeps around the circumference in anticlockwise direction. Timestepper defaults to Steady default timestepper.
   {
     // Do you want a coarse problem?
     Coarse_problem = false; // true; // hierher
     // Vector for pointers to all the temporary meshes
     Vector<Mesh*> all_temp_mesh_pt;
     // Build central mesh
     Central_mesh_pt =
       new RefineableRectangleWithHoleAndAnnularRegionMesh<ELEMENT>(
         cylinder_pt,
         annular_region_radius,
         length_of_central_box,
         time_stepper_pt);
     // Add this mesh to the list of temproary meshes
     all_temp_mesh_pt.push_back(Central_mesh_pt);
     // Bulk mesh left boundary id
     unsigned int left_boundary_id = 3;
     // Bulk mesh top boundary id
     unsigned int top_boundary_id = 2;
     // Bulk mesh right boundary id
     unsigned int right_boundary_id = 1;
     // Bulk mesh bottom boundary id
     unsigned int bottom_boundary_id = 0;
     // Build the surrounding meshes
     // Right mesh
     double l_right = x_right - 0.5 * length_of_central_box;
     unsigned n_right =
       std::max(unsigned(1), unsigned(l_right / length_of_central_box));
     if (Coarse_problem)
     {
       n_right = 1;
     }
     Mesh* surrounding_right_mesh_pt =
       TwoDimensionalPMLHelper::create_right_pml_mesh<PMLLayerElement<ELEMENT>>(
         Central_mesh_pt, right_boundary_id, n_right, l_right, time_stepper_pt);
     all_temp_mesh_pt.push_back(surrounding_right_mesh_pt);
     // Remove nodes from top and bottom boundaries (0 and 2)
     for (unsigned ibound_rm = 0; ibound_rm <= 2; ibound_rm += 2)
     {
       unsigned num_nod = surrounding_right_mesh_pt->nboundary_node(ibound_rm);
       for (unsigned inod = 0; inod < num_nod; inod++)
       {
         Node* nod_pt =
           surrounding_right_mesh_pt->boundary_node_pt(ibound_rm, inod);
         if (nod_pt->is_on_boundary(ibound_rm))
         {
           nod_pt->remove_from_boundary(ibound_rm);
         }
       }
     }
     // Top mesh
     double l_top = 0.5 * height - 0.5 * length_of_central_box;
     unsigned n_top =
       std::max(unsigned(1), unsigned(l_top / length_of_central_box));
     if (Coarse_problem)
     {
       n_top = 1;
     }
     Mesh* surrounding_top_mesh_pt =
       TwoDimensionalPMLHelper::create_top_pml_mesh<PMLLayerElement<ELEMENT>>(
         Central_mesh_pt, top_boundary_id, n_top, l_top, time_stepper_pt);
     all_temp_mesh_pt.push_back(surrounding_top_mesh_pt);
     // Remove nodes from right and left boundaries (1 and 3)
     for (unsigned ibound_rm = 1; ibound_rm <= 3; ibound_rm += 2)
     {
       unsigned num_nod = surrounding_top_mesh_pt->nboundary_node(ibound_rm);
       for (unsigned inod = 0; inod < num_nod; inod++)
       {
         Node* nod_pt =
           surrounding_top_mesh_pt->boundary_node_pt(ibound_rm, inod);
         if (nod_pt->is_on_boundary(ibound_rm))
         {
           nod_pt->remove_from_boundary(ibound_rm);
         }
       }
     }
     // Left mesh
     double l_left = -0.5 * length_of_central_box - x_left;
     unsigned n_left =
       std::max(unsigned(1), unsigned(l_left / length_of_central_box));
     if (Coarse_problem)
     {
       n_left = 1;
     }
     Mesh* surrounding_left_mesh_pt =
       TwoDimensionalPMLHelper::create_left_pml_mesh<PMLLayerElement<ELEMENT>>(
         Central_mesh_pt, left_boundary_id, n_left, l_left, time_stepper_pt);
     all_temp_mesh_pt.push_back(surrounding_left_mesh_pt);
     // Remove nodes from top and bottom boundaries (0 and 2)
     for (unsigned ibound_rm = 0; ibound_rm <= 2; ibound_rm += 2)
     {
       unsigned num_nod = surrounding_left_mesh_pt->nboundary_node(ibound_rm);
       for (unsigned inod = 0; inod < num_nod; inod++)
       {
         Node* nod_pt =
           surrounding_left_mesh_pt->boundary_node_pt(ibound_rm, inod);
         if (nod_pt->is_on_boundary(ibound_rm))
         {
           nod_pt->remove_from_boundary(ibound_rm);
         }
       }
     }
     // Bottom mesh
     double l_bottom = 0.5 * height - 0.5 * length_of_central_box;
     unsigned n_bottom =
       std::max(unsigned(1), unsigned(l_bottom / length_of_central_box));
     if (Coarse_problem)
     {
       n_bottom = 1;
     }
     Mesh* surrounding_bottom_mesh_pt =
       TwoDimensionalPMLHelper::create_bottom_pml_mesh<PMLLayerElement<ELEMENT>>(
         Central_mesh_pt,
         bottom_boundary_id,
         n_bottom,
         l_bottom,
         time_stepper_pt);
     all_temp_mesh_pt.push_back(surrounding_bottom_mesh_pt);
     // Remove nodes from right and left boundaries (1 and 3)
     for (unsigned ibound_rm = 1; ibound_rm <= 3; ibound_rm += 2)
     {
       unsigned num_nod = surrounding_bottom_mesh_pt->nboundary_node(ibound_rm);
       for (unsigned inod = 0; inod < num_nod; inod++)
       {
         Node* nod_pt =
           surrounding_bottom_mesh_pt->boundary_node_pt(ibound_rm, inod);
         if (nod_pt->is_on_boundary(ibound_rm))
         {
           nod_pt->remove_from_boundary(ibound_rm);
         }
       }
     }
     // Build corner Surrounding meshes
     Mesh* surrounding_top_right_mesh_pt =
       TwoDimensionalPMLHelper::create_top_right_pml_mesh<
         PMLLayerElement<ELEMENT>>(surrounding_right_mesh_pt,
                                   surrounding_top_mesh_pt,
                                   Central_mesh_pt,
                                   right_boundary_id,
                                   time_stepper_pt);
     all_temp_mesh_pt.push_back(surrounding_top_right_mesh_pt);
     Mesh* surrounding_bottom_right_mesh_pt =
       TwoDimensionalPMLHelper::create_bottom_right_pml_mesh<
         PMLLayerElement<ELEMENT>>(surrounding_right_mesh_pt,
                                   surrounding_bottom_mesh_pt,
                                   Central_mesh_pt,
                                   right_boundary_id,
                                   time_stepper_pt);
     all_temp_mesh_pt.push_back(surrounding_bottom_right_mesh_pt);
     Mesh* surrounding_top_left_mesh_pt =
       TwoDimensionalPMLHelper::create_top_left_pml_mesh<
         PMLLayerElement<ELEMENT>>(surrounding_left_mesh_pt,
                                   surrounding_top_mesh_pt,
                                   Central_mesh_pt,
                                   left_boundary_id,
                                   time_stepper_pt);
     all_temp_mesh_pt.push_back(surrounding_top_left_mesh_pt);
     Mesh* surrounding_bottom_left_mesh_pt =
       TwoDimensionalPMLHelper::create_bottom_left_pml_mesh<
         PMLLayerElement<ELEMENT>>(surrounding_left_mesh_pt,
                                   surrounding_bottom_mesh_pt,
                                   Central_mesh_pt,
                                   left_boundary_id,
                                   time_stepper_pt);
     all_temp_mesh_pt.push_back(surrounding_bottom_left_mesh_pt);
     // Copy all elements across
     unsigned n_mesh = all_temp_mesh_pt.size();
     unsigned nel = 0;
     unsigned nnod = 0;
     for (unsigned i = 0; i < n_mesh; i++)
     {
       nel += all_temp_mesh_pt[i]->nelement();
       nnod += all_temp_mesh_pt[i]->nnode();
     }
     this->Element_pt.resize(nel);
     this->Node_pt.resize(nnod);
     unsigned count_el = 0;
     unsigned count_nod = 0;
     for (unsigned i = 0; i < n_mesh; i++)
     {
       unsigned nel = all_temp_mesh_pt[i]->nelement();
       for (unsigned e = 0; e < nel; e++)
       {
         this->Element_pt[count_el] = all_temp_mesh_pt[i]->element_pt(e);
         count_el++;
       }
       unsigned nnod = all_temp_mesh_pt[i]->nnode();
       for (unsigned j = 0; j < nnod; j++)
       {
         this->Node_pt[count_nod] = all_temp_mesh_pt[i]->node_pt(j);
         count_nod++;
       }
     }
     // Remove nodes on outer boundaries (0 to 3) of central mesh
     // from their respective boundaries (otherwise they get added
     // to the mesh boundaries during adaptation)
     for (unsigned b = 0; b < 4; b++)
     {
       unsigned nnod = Central_mesh_pt->nboundary_node(b);
       for (unsigned j = 0; j < nnod; j++)
       {
         Node* nod_pt = Central_mesh_pt->boundary_node_pt(b, j);
         nod_pt->remove_from_boundary(b);
       }
     }
     // Setup boundaries:
     //==================
     this->set_nboundary(5);
     Vector<Mesh*> pml_mesh_pt;
     // Top meshes:
     //------------
     {
       // Upper boundary in top mesh (same number in this mesh)
       unsigned ibound = 2;
       // Loop over relevant meshes
       Vector<Mesh*> all_mesh_pt;
       all_mesh_pt.push_back(surrounding_top_left_mesh_pt);
       all_mesh_pt.push_back(surrounding_top_mesh_pt);
       all_mesh_pt.push_back(surrounding_top_right_mesh_pt);
       unsigned n_mesh = all_mesh_pt.size();
       for (unsigned m = 0; m < n_mesh; m++)
       {
         pml_mesh_pt.push_back(all_mesh_pt[m]);
         unsigned num_nod = all_mesh_pt[m]->nboundary_node(ibound);
         for (unsigned inod = 0; inod < num_nod; inod++)
         {
           Node* nod_pt = all_mesh_pt[m]->boundary_node_pt(ibound, inod);
           this->add_boundary_node(ibound, nod_pt);
         }
       }
     }
     // Left meshes:
     //------------
     {
       // Left boundary (same number in this mesh)
       unsigned ibound = 3;
       pml_mesh_pt.push_back(surrounding_left_mesh_pt);
       // Loop over relevant meshes
       Vector<Mesh*> all_mesh_pt;
       all_mesh_pt.push_back(surrounding_top_left_mesh_pt);
       all_mesh_pt.push_back(surrounding_left_mesh_pt);
       all_mesh_pt.push_back(surrounding_bottom_left_mesh_pt);
       unsigned n_mesh = all_mesh_pt.size();
       for (unsigned m = 0; m < n_mesh; m++)
       {
         unsigned num_nod = all_mesh_pt[m]->nboundary_node(ibound);
         for (unsigned inod = 0; inod < num_nod; inod++)
         {
           Node* nod_pt = all_mesh_pt[m]->boundary_node_pt(ibound, inod);
           this->add_boundary_node(ibound, nod_pt);
         }
       }
     }
     // Bottom meshes:
     //---------------
     {
       // Bottom boundary (same number in this mesh)
       unsigned ibound = 0;
       // Loop over relevant meshes
       Vector<Mesh*> all_mesh_pt;
       all_mesh_pt.push_back(surrounding_bottom_left_mesh_pt);
       all_mesh_pt.push_back(surrounding_bottom_mesh_pt);
       all_mesh_pt.push_back(surrounding_bottom_right_mesh_pt);
       unsigned n_mesh = all_mesh_pt.size();
       for (unsigned m = 0; m < n_mesh; m++)
       {
         pml_mesh_pt.push_back(all_mesh_pt[m]);
         unsigned num_nod = all_mesh_pt[m]->nboundary_node(ibound);
         for (unsigned inod = 0; inod < num_nod; inod++)
         {
           Node* nod_pt = all_mesh_pt[m]->boundary_node_pt(ibound, inod);
           this->add_boundary_node(ibound, nod_pt);
         }
       }
     }
     // Right meshes:
     //--------------
     {
       // Right boundary  (same number in this mesh)
       unsigned ibound = 1;
       pml_mesh_pt.push_back(surrounding_right_mesh_pt);
       // Loop over relevant meshes
       Vector<Mesh*> all_mesh_pt;
       all_mesh_pt.push_back(surrounding_bottom_right_mesh_pt);
       all_mesh_pt.push_back(surrounding_right_mesh_pt);
       all_mesh_pt.push_back(surrounding_top_right_mesh_pt);
       unsigned n_mesh = all_mesh_pt.size();
       for (unsigned m = 0; m < n_mesh; m++)
       {
         unsigned num_nod = all_mesh_pt[m]->nboundary_node(ibound);
         for (unsigned inod = 0; inod < num_nod; inod++)
         {
           Node* nod_pt = all_mesh_pt[m]->boundary_node_pt(ibound, inod);
           this->add_boundary_node(ibound, nod_pt);
         }
       }
     }
     // No slip on boundary of inner mesh
     //----------------------------------
     {
       // Inner boundary
       unsigned ibound = 4;
       // Pin both velocities
       unsigned num_nod = Central_mesh_pt->nboundary_node(ibound);
       for (unsigned inod = 0; inod < num_nod; inod++)
       {
         Node* nod_pt = Central_mesh_pt->boundary_node_pt(ibound, inod);
         this->add_boundary_node(ibound, nod_pt);
       }
     }
     // Setup quadtree forest for mesh refinement
     this->setup_quadtree_forest();
     // Setup boundary element lookup schemes
     this->setup_boundary_element_info();
     // Cleanup. NOTE: Can't delete Central_mesh_pt as it's responsible for
     // deleting Domain_pt but
     unsigned n_pml_mesh = pml_mesh_pt.size();
     for (unsigned j = 0; j < n_pml_mesh; j++)
     {
       pml_mesh_pt[j]->flush_element_and_node_storage();
       delete pml_mesh_pt[j];
       pml_mesh_pt[j] = 0;
     }
     Central_mesh_pt->flush_element_and_node_storage();
   } // End of RefineableQuadMeshWithMovingCylinder
References b, oomph::Mesh::boundary_node_pt(), oomph::TwoDimensionalPMLHelper::create_bottom_left_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_bottom_right_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_top_left_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_top_right_pml_mesh(), e(), Global_Physical_Variables::height(), i, oomph::Node::is_on_boundary(), j, m, max, oomph::Mesh::nboundary_node(), and oomph::Node::remove_from_boundary().
~RefineableQuadMeshWithMovingCylinder()
template<class ELEMENT > oomph::RefineableQuadMeshWithMovingCylinder< ELEMENT >::~RefineableQuadMeshWithMovingCylinder () inline
Destructor: Delete the part of the mesh which has a Domain representation
     {
       // Delete the central mesh
       delete Central_mesh_pt;
       // Make it a null pointer
       Central_mesh_pt = 0;
     } // End of ~RefineableQuadMeshWithMovingCylinder
References oomph::RefineableQuadMeshWithMovingCylinder< ELEMENT >::Central_mesh_pt.
Member Data Documentation
Central_mesh_pt
template<class ELEMENT > RefineableRectangleWithHoleAndAnnularRegionMesh<ELEMENT>* oomph::RefineableQuadMeshWithMovingCylinder< ELEMENT >::Central_mesh_pt private
Pointer to the part of the mesh which has a Domain representation. We have to store it because we can't delete it in the constructor as it would delete the Domain pointer which might be needed after the whole mesh has been constructed (e.g. for the mesh extrusion machinery)...
Referenced by oomph::RefineableQuadMeshWithMovingCylinder< ELEMENT >::~RefineableQuadMeshWithMovingCylinder().
Coarse_problem
template<class ELEMENT > bool oomph::RefineableQuadMeshWithMovingCylinder< ELEMENT >::Coarse_problem private
The documentation for this class was generated from the following files:
rectangle_with_moving_cylinder_mesh.template.h
rectangle_with_moving_cylinder_mesh.template.cc