MercuryDPM: Eigen::TensorSycl::internal::OpDefiner< Op, CoeffReturnType, Index, Vectorizable > Struct Template Reference
Eigen::TensorSycl::internal::OpDefiner< Op, CoeffReturnType, Index, Vectorizable > Struct Template Reference
#include <TensorReductionSycl.h>
Public Types
typedef Vectorise< CoeffReturnType, Eigen::SyclDevice, Vectorizable >::PacketReturnType PacketReturnType
typedef Op type
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE type get_op (Op &op)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType finalise_op (const PacketReturnType &accumulator, const Index &)
Member Typedef Documentation
PacketReturnType
template<typename Op , typename CoeffReturnType , typename Index , bool Vectorizable> typedef Vectorise<CoeffReturnType, Eigen::SyclDevice, Vectorizable>::PacketReturnType Eigen::TensorSycl::internal::OpDefiner< Op, CoeffReturnType, Index, Vectorizable >::PacketReturnType
type
template<typename Op , typename CoeffReturnType , typename Index , bool Vectorizable> typedef Op Eigen::TensorSycl::internal::OpDefiner< Op, CoeffReturnType, Index, Vectorizable >::type
Member Function Documentation
finalise_op()
template<typename Op , typename CoeffReturnType , typename Index , bool Vectorizable> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorSycl::internal::OpDefiner< Op, CoeffReturnType, Index, Vectorizable >::finalise_op (const PacketReturnType & accumulator, const Index &) inline static
{
     return accumulator;
   }
Referenced by Eigen::TensorSycl::internal::FullReductionKernelFunctor< Evaluator, OpType, local_range >::compute_reduction(), Eigen::TensorSycl::internal::GenericNondeterministicReducer< Evaluator, OpType >::operator()(), and Eigen::TensorSycl::internal::PartialReductionKernel< Evaluator, OpType, PannelParameters, rt >::operator()().
get_op()
template<typename Op , typename CoeffReturnType , typename Index , bool Vectorizable> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE type Eigen::TensorSycl::internal::OpDefiner< Op, CoeffReturnType, Index, Vectorizable >::get_op (Op & op) inline static
 { return op; }
References op.
The documentation for this struct was generated from the following file:
TensorReductionSycl.h