MercuryDPM: VerticalMixerAngledBlades.cpp File Reference
VerticalMixerAngledBlades.cpp File Reference
#include "VerticalMixer.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
 {
     std::string name = helpers::readFromCommandLine(argc, argv, "-name", std::string("VerticalMixerAngledBlades"));
     //first, do the real run
     VerticalMixerAngledBlades mixer(argc, argv);
     mixer.setName(name);
     mixer.removeOldFiles();
     // use straight blades
     mixer.bladeAngle_ = helpers::readFromCommandLine(argc, argv, "-bladeAngle", 0.0)*constants::pi;
     mixer.particleNumber_ = helpers::readFromCommandLine(argc, argv, "-particleNumber", 5000);
     mixer.setTimeMax(helpers::readFromCommandLine(argc, argv, "-timeMax", 30.0));
     mixer.setParticlesWriteVTK(true);
     mixer.solve();
     //then create pretty wall data
     VerticalMixerAngledBlades walls(argc, argv);
     walls.setName(name + "PrettyWalls");
     walls.removeOldFiles();
     walls.bladeAngle_ = mixer.bladeAngle_;
     walls.prettyWalls_ = true;
     walls.setTimeMax(mixer.getTimeMax());
     walls.solve();
     //finally, create pretty blade data
     VerticalMixerAngledBlades blades(argc, argv);
     blades.setName(name + "PrettyBlades");
     blades.removeOldFiles();
     blades.bladeAngle_ = mixer.bladeAngle_;
     blades.prettyWalls_ = true;
     blades.haveOuterWalls = false;
     blades.setTimeMax(mixer.getTimeMax());
     blades.solve();
     return 0;
 }
References VerticalMixerAngledBlades::bladeAngle_, DPMBase::getTimeMax(), VerticalMixer::haveOuterWalls, plotDoE::name, VerticalMixer::particleNumber_, constants::pi, VerticalMixer::prettyWalls_, helpers::readFromCommandLine(), DPMBase::removeOldFiles(), DPMBase::setName(), DPMBase::setParticlesWriteVTK(), DPMBase::setTimeMax(), DPMBase::solve(), and oomph::Global_string_for_annotation::string().