MercuryDPM: Eigen::Inverse< XprType > Class Template Reference
Eigen::Inverse< XprType > Class Template Reference
Expression of the inverse of another expression.
#include <Inverse.h>
Public Types
typedef XprType::StorageIndex StorageIndex
typedef XprType::Scalar Scalar
typedef internal::ref_selector< XprType >::type XprTypeNested
typedef internal::remove_all_t< XprTypeNested > XprTypeNestedCleaned
typedef internal::ref_selector< Inverse >::type Nested
typedef internal::remove_all_t< XprType > NestedExpression
Public Types inherited from Eigen::InverseImpl< XprType, internal::traits< XprType >::StorageKind >
typedef internal::generic_xpr_base< Inverse< XprType > >::type Base
typedef XprType::Scalar Scalar
Public Member Functions
EIGEN_DEVICE_FUNC Inverse (const XprType &xpr)
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC const XprTypeNestedCleaned & nestedExpression () const
Protected Attributes
XprTypeNested m_xpr
Detailed Description
template<typename XprType>
class Eigen::Inverse< XprType >
Expression of the inverse of another expression.
Template Parameters
XprType the type of the expression we are taking the inverse
This class represents an abstract expression of A.inverse() and most of the time this is the only way it is used.
Member Typedef Documentation
Nested
template<typename XprType > typedef internal::ref_selector<Inverse>::type Eigen::Inverse< XprType >::Nested
NestedExpression
template<typename XprType > typedef internal::remove_all_t<XprType> Eigen::Inverse< XprType >::NestedExpression
Scalar
template<typename XprType > typedef XprType::Scalar Eigen::Inverse< XprType >::Scalar
StorageIndex
template<typename XprType > typedef XprType::StorageIndex Eigen::Inverse< XprType >::StorageIndex
XprTypeNested
template<typename XprType > typedef internal::ref_selector<XprType>::type Eigen::Inverse< XprType >::XprTypeNested
XprTypeNestedCleaned
template<typename XprType > typedef internal::remove_all_t<XprTypeNested> Eigen::Inverse< XprType >::XprTypeNestedCleaned
Constructor & Destructor Documentation
Inverse()
template<typename XprType > EIGEN_DEVICE_FUNC Eigen::Inverse< XprType >::Inverse (const XprType & xpr) inline explicit
 : m_xpr(xpr) {}
Member Function Documentation
cols()
template<typename XprType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::Inverse< XprType >::cols () const inline
 { return m_xpr.rows(); }
References Eigen::Inverse< XprType >::m_xpr.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::internal::Assignment< DstXprType, Inverse< CompleteOrthogonalDecomposition< MatrixType, PermutationIndex > >, internal::assign_op< typename DstXprType::Scalar, typename CompleteOrthogonalDecomposition< MatrixType, PermutationIndex >::Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Inverse< PartialPivLU< MatrixType, PermutationIndex > >, internal::assign_op< typename DstXprType::Scalar, typename PartialPivLU< MatrixType, PermutationIndex >::Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Inverse< FullPivLU< MatrixType, PermutationIndex > >, internal::assign_op< typename DstXprType::Scalar, typename FullPivLU< MatrixType, PermutationIndex >::Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Inverse< ColPivHouseholderQR< MatrixType, PermutationIndex > >, internal::assign_op< typename DstXprType::Scalar, typename ColPivHouseholderQR< MatrixType, PermutationIndex >::Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Inverse< FullPivHouseholderQR< MatrixType, PermutationIndex > >, internal::assign_op< typename DstXprType::Scalar, typename FullPivHouseholderQR< MatrixType, PermutationIndex >::Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Inverse< XprType >, internal::assign_op< typename DstXprType::Scalar, typename XprType::Scalar >, Dense2Dense >::run(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
nestedExpression()
template<typename XprType > EIGEN_DEVICE_FUNC const XprTypeNestedCleaned& Eigen::Inverse< XprType >::nestedExpression () const inline
 { return m_xpr; }
References Eigen::Inverse< XprType >::m_xpr.
Referenced by Eigen::internal::generic_product_impl< Inverse< Lhs >, Rhs, PermutationShape, MatrixShape, ProductTag >::evalTo(), Eigen::internal::generic_product_impl< Lhs, Inverse< Rhs >, MatrixShape, PermutationShape, ProductTag >::evalTo(), Eigen::internal::Assignment< DstXprType, Inverse< CompleteOrthogonalDecomposition< MatrixType, PermutationIndex > >, internal::assign_op< typename DstXprType::Scalar, typename CompleteOrthogonalDecomposition< MatrixType, PermutationIndex >::Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Inverse< PartialPivLU< MatrixType, PermutationIndex > >, internal::assign_op< typename DstXprType::Scalar, typename PartialPivLU< MatrixType, PermutationIndex >::Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Inverse< FullPivLU< MatrixType, PermutationIndex > >, internal::assign_op< typename DstXprType::Scalar, typename FullPivLU< MatrixType, PermutationIndex >::Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Inverse< ColPivHouseholderQR< MatrixType, PermutationIndex > >, internal::assign_op< typename DstXprType::Scalar, typename ColPivHouseholderQR< MatrixType, PermutationIndex >::Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Inverse< FullPivHouseholderQR< MatrixType, PermutationIndex > >, internal::assign_op< typename DstXprType::Scalar, typename FullPivHouseholderQR< MatrixType, PermutationIndex >::Scalar >, Dense2Dense >::run(), and Eigen::internal::Assignment< DstXprType, Inverse< XprType >, internal::assign_op< typename DstXprType::Scalar, typename XprType::Scalar >, Dense2Dense >::run().
rows()
template<typename XprType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::Inverse< XprType >::rows () const inline
 { return m_xpr.cols(); }
References Eigen::Inverse< XprType >::m_xpr.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::internal::Assignment< DstXprType, Inverse< PartialPivLU< MatrixType, PermutationIndex > >, internal::assign_op< typename DstXprType::Scalar, typename PartialPivLU< MatrixType, PermutationIndex >::Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Inverse< FullPivLU< MatrixType, PermutationIndex > >, internal::assign_op< typename DstXprType::Scalar, typename FullPivLU< MatrixType, PermutationIndex >::Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Inverse< ColPivHouseholderQR< MatrixType, PermutationIndex > >, internal::assign_op< typename DstXprType::Scalar, typename ColPivHouseholderQR< MatrixType, PermutationIndex >::Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Inverse< FullPivHouseholderQR< MatrixType, PermutationIndex > >, internal::assign_op< typename DstXprType::Scalar, typename FullPivHouseholderQR< MatrixType, PermutationIndex >::Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Inverse< XprType >, internal::assign_op< typename DstXprType::Scalar, typename XprType::Scalar >, Dense2Dense >::run(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_xpr
template<typename XprType > XprTypeNested Eigen::Inverse< XprType >::m_xpr protected
Referenced by Eigen::Inverse< XprType >::cols(), Eigen::Inverse< XprType >::nestedExpression(), and Eigen::Inverse< XprType >::rows().
The documentation for this class was generated from the following file:
Inverse.h