MercuryDPM: stdlist_overload.cpp File Reference
stdlist_overload.cpp File Reference
#include "main.h"
#include <Eigen/StdList>
#include <Eigen/Geometry>
Functions
template<class Container , class Position >
Container::iterator get (Container &c, Position position)
template<class Container , class Position , class Value >
void set (Container &c, Position position, const Value &value)
template<typename MatrixType >
void check_stdlist_matrix (const MatrixType &m)
template<typename TransformType >
void check_stdlist_transform (const TransformType &)
template<typename QuaternionType >
void check_stdlist_quaternion (const QuaternionType &)
EIGEN_DECLARE_TEST (stdlist_overload)
Function Documentation
check_stdlist_matrix()
template<typename MatrixType > void check_stdlist_matrix (const MatrixType & m)
{
   Index rows = m.rows();
   Index cols = m.cols();
   MatrixType x = MatrixType::Random(rows, cols), y = MatrixType::Random(rows, cols);
   std::list<MatrixType> v(10, MatrixType::Zero(rows, cols)), w(20, y);
   typename std::list<MatrixType>::iterator itv = get(v, 5);
   typename std::list<MatrixType>::iterator itw = get(w, 6);
   *itv = x;
   *itw = *itv;
   VERIFY_IS_APPROX(*itw, *itv);
   v = w;
   itv = v.begin();
   itw = w.begin();
   for (int i = 0; i < 20; i++) {
     VERIFY_IS_APPROX(*itw, *itv);
     ++itv;
     ++itw;
   }
   v.resize(21);
   set(v, 20, x);
   VERIFY_IS_APPROX(*get(v, 20), x);
   v.resize(22, y);
   VERIFY_IS_APPROX(*get(v, 21), y);
   v.push_back(x);
   VERIFY_IS_APPROX(*get(v, 22), x);
   // do a lot of push_back such that the list gets internally resized
   // (with memory reallocation)
   MatrixType* ref = &(*get(w, 0));
   for (int i = 0; i < 30 || ((ref == &(*get(w, 0))) && i < 300); ++i) v.push_back(*get(w, i % w.size()));
   for (unsigned int i = 23; i < v.size(); ++i) {
     VERIFY((*get(v, i)) == (*get(w, (i - 23) % w.size())));
   }
 }
References cols, get(), i, m, rows, set(), v, VERIFY, VERIFY_IS_APPROX, w, plotDoE::x, y, and oomph::PseudoSolidHelper::Zero.
Referenced by EIGEN_DECLARE_TEST().
check_stdlist_quaternion()
template<typename QuaternionType > void check_stdlist_quaternion (const QuaternionType &)
{
   typedef typename QuaternionType::Coefficients Coefficients;
   QuaternionType x(Coefficients::Random()), y(Coefficients::Random()), qi = QuaternionType::Identity();
   std::list<QuaternionType> v(10, qi), w(20, y);
   typename std::list<QuaternionType>::iterator itv = get(v, 5);
   typename std::list<QuaternionType>::iterator itw = get(w, 6);
   *itv = x;
   *itw = *itv;
   VERIFY_IS_APPROX(*itw, *itv);
   v = w;
   itv = v.begin();
   itw = w.begin();
   for (int i = 0; i < 20; i++) {
     VERIFY_IS_APPROX(*itw, *itv);
     ++itv;
     ++itw;
   }
   v.resize(21, qi);
   set(v, 20, x);
   VERIFY_IS_APPROX(*get(v, 20), x);
   v.resize(22, y);
   VERIFY_IS_APPROX(*get(v, 21), y);
   v.push_back(x);
   VERIFY_IS_APPROX(*get(v, 22), x);
   // do a lot of push_back such that the list gets internally resized
   // (with memory reallocation)
   QuaternionType* ref = &(*get(w, 0));
   for (int i = 0; i < 30 || ((ref == &(*get(w, 0))) && i < 300); ++i) v.push_back(*get(w, i % w.size()));
   for (unsigned int i = 23; i < v.size(); ++i) {
     VERIFY(get(v, i)->coeffs() == get(w, (i - 23) % w.size())->coeffs());
   }
 }
References get(), i, set(), v, VERIFY, VERIFY_IS_APPROX, w, plotDoE::x, and y.
Referenced by EIGEN_DECLARE_TEST().
check_stdlist_transform()
template<typename TransformType > void check_stdlist_transform (const TransformType &)
{
   typedef typename TransformType::MatrixType MatrixType;
   TransformType x(MatrixType::Random()), y(MatrixType::Random()), ti = TransformType::Identity();
   std::list<TransformType> v(10, ti), w(20, y);
   typename std::list<TransformType>::iterator itv = get(v, 5);
   typename std::list<TransformType>::iterator itw = get(w, 6);
   *itv = x;
   *itw = *itv;
   VERIFY_IS_APPROX(*itw, *itv);
   v = w;
   itv = v.begin();
   itw = w.begin();
   for (int i = 0; i < 20; i++) {
     VERIFY_IS_APPROX(*itw, *itv);
     ++itv;
     ++itw;
   }
   v.resize(21, ti);
   set(v, 20, x);
   VERIFY_IS_APPROX(*get(v, 20), x);
   v.resize(22, y);
   VERIFY_IS_APPROX(*get(v, 21), y);
   v.push_back(x);
   VERIFY_IS_APPROX(*get(v, 22), x);
   // do a lot of push_back such that the list gets internally resized
   // (with memory reallocation)
   TransformType* ref = &(*get(w, 0));
   for (int i = 0; i < 30 || ((ref == &(*get(w, 0))) && i < 300); ++i) v.push_back(*get(w, i % w.size()));
   for (unsigned int i = 23; i < v.size(); ++i) {
     VERIFY(get(v, i)->matrix() == get(w, (i - 23) % w.size())->matrix());
   }
 }
References get(), i, matrix(), set(), v, VERIFY, VERIFY_IS_APPROX, w, plotDoE::x, and y.
Referenced by EIGEN_DECLARE_TEST().
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (stdlist_overload)
{
   // some non vectorizable fixed sizes
   CALL_SUBTEST_1(check_stdlist_matrix(Vector2f()));
   CALL_SUBTEST_1(check_stdlist_matrix(Matrix3f()));
   CALL_SUBTEST_2(check_stdlist_matrix(Matrix3d()));
   // some vectorizable fixed sizes
   CALL_SUBTEST_1(check_stdlist_matrix(Matrix2f()));
   CALL_SUBTEST_1(check_stdlist_matrix(Vector4f()));
   CALL_SUBTEST_1(check_stdlist_matrix(Matrix4f()));
   CALL_SUBTEST_2(check_stdlist_matrix(Matrix4d()));
   // some dynamic sizes
   CALL_SUBTEST_3(check_stdlist_matrix(MatrixXd(1, 1)));
   CALL_SUBTEST_3(check_stdlist_matrix(VectorXd(20)));
   CALL_SUBTEST_3(check_stdlist_matrix(RowVectorXf(20)));
   CALL_SUBTEST_3(check_stdlist_matrix(MatrixXcf(10, 10)));
   // some Transform
   CALL_SUBTEST_4(check_stdlist_transform(Affine2f()));  // does not need the specialization (2+1)^2 = 9
   CALL_SUBTEST_4(check_stdlist_transform(Affine3f()));
   CALL_SUBTEST_4(check_stdlist_transform(Affine3d()));
   // some Quaternion
   CALL_SUBTEST_5(check_stdlist_quaternion(Quaternionf()));
   CALL_SUBTEST_5(check_stdlist_quaternion(Quaterniond()));
 }
References CALL_SUBTEST_1, CALL_SUBTEST_2, CALL_SUBTEST_3, CALL_SUBTEST_4, CALL_SUBTEST_5, check_stdlist_matrix(), check_stdlist_quaternion(), and check_stdlist_transform().
get()
template<class Container , class Position > Container::iterator get (Container & c, Position position)
{
   typename Container::iterator it = c.begin();
   std::advance(it, position);
   return it;
 }
References calibrate::c.
Referenced by check_stdlist_matrix(), check_stdlist_quaternion(), check_stdlist_transform(), Eigen::IndexPairList< FirstType, OtherTypes >::operator[](), Eigen::internal::index_statically_eq_impl< IndexList< FirstType, OtherTypes... > >::run(), Eigen::internal::index_statically_eq_impl< const IndexList< FirstType, OtherTypes... > >::run(), Eigen::internal::index_statically_ne_impl< IndexList< FirstType, OtherTypes... > >::run(), Eigen::internal::index_statically_ne_impl< const IndexList< FirstType, OtherTypes... > >::run(), Eigen::internal::index_statically_gt_impl< IndexList< FirstType, OtherTypes... > >::run(), Eigen::internal::index_statically_gt_impl< const IndexList< FirstType, OtherTypes... > >::run(), Eigen::internal::index_statically_lt_impl< IndexList< FirstType, OtherTypes... > >::run(), Eigen::internal::index_statically_lt_impl< const IndexList< FirstType, OtherTypes... > >::run(), and Eigen::internal::run_serialized().
set()
template<class Container , class Position , class Value > void set (Container & c, Position position, const Value & value)
{
   typename Container::iterator it = c.begin();
   std::advance(it, position);
   *it = value;
 }
References calibrate::c, and Eigen::value.
Referenced by HourGlass2D::actionsAfterTimeStep(), HourGlass::actionsAfterTimeStep(), GranularCollapse::actionsAfterTimeStep(), Tutorial11::actionsAfterTimeStep(), oomph::ElementWithExternalElement::assign_external_interaction_data_local_eqn_numbers(), check-makefile-subdirs::check_makefileam(), check_stdlist_matrix(), check_stdlist_quaternion(), check_stdlist_transform(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::DisjointSet::DisjointSet(), Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct >::evalTo(), NurbsSurface::NurbsSurface(), oomph::TriangleMesh< ELEMENT >::output_boundary_coordinates(), oomph::ImmersedRigidBodyElement::set_drag_mesh(), and oomph::OcTree::setup_static_data().