MercuryDPM: Screw Class Reference
Screw Class Reference
This function defines an Archimedes' screw in the z-direction from a (constant) starting point, a (constant) length L, a (constant) radius r, a (constant) number or revelations N and a (constant) rotation speed (rev/s)
#include <Screw.h>
Public Member Functions
Screw ()
Default constructor: make a screw with default parameters.
Screw (const Screw &other)
Copy constructor, copies another Screw.
Screw (Vec3D start, Mdouble l, Mdouble r, Mdouble n, Mdouble omega, Mdouble thickness, ScrewType screwType=ScrewType::doubleHelix)
Constructor in which all parameters of the screw are set.
~Screw () override
Default destructor.
Screw * copy () const final
Copy this screw and return a pointer to the copy.
bool getDistanceAndNormal (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return) const final
Compute the distance from the Screw for a given BaseParticle and return if there is a collision. If there is a collision, also return the normal vector of the interaction point.
bool getDistanceAndNormalLabCoordinates (Vec3D position, Mdouble wallInteractionRadius, Mdouble &distance, Vec3D &normal_return) const
void move_time (Mdouble dt)
Rotate the Screw for a period dt, so that the offset_ changes with omega_*dt.
void rotate (const Vec3D &angularVelocityDt) override
void read (std::istream &is) override
Reads a Screw from an input stream, for example a restart file.
void oldRead (std::istream &is)
Reads a Screw in the old style from an input stream, for example a restart file old style.
void write (std::ostream &os) const override
Writes this Screw to an output stream, for example a restart file.
std::string getName () const final
Returns the name of the object, here the string "Screw".
void writeVTK (VTKContainer &vtk) const override
void writeVTK (std::string filename) const
Public Member Functions inherited from BaseWall
BaseWall ()
Default constructor.
BaseWall (const BaseWall &w)
Copy constructor.
~BaseWall () override
Default destructor.
virtual bool getDistanceNormalOverlap (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual bool getDistanceNormalOverlapSuperquadric (const SuperQuadricParticle &p, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual Vec3D getFurthestPointSuperQuadric (const Vec3D &normalBodyFixed, const Vec3D &axes, Mdouble eps1, Mdouble eps2) const
virtual void setHandler (WallHandler *handler)
A function which sets the WallHandler for this BaseWall.
WallHandler * getHandler () const
A function which returns the WallHandler that handles this BaseWall.
void setIndSpecies (unsigned int indSpecies) override
Define the species of this wall using the index of the species in the SpeciesHandler in this DPMBase.
void setSpecies (const ParticleSpecies *species)
Defines the species of the current wall.
bool isFixed () const override
void setForceControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity={0, 0, 0})
Slowly adjusts the force on a wall towards a specified goal, by adjusting (prescribing) the velocity of the wall.
virtual bool isLocal (Vec3D &min, Vec3D &max) const
bool getLinePlaneIntersect (Vec3D &intersect, const Vec3D &p0, const Vec3D &p1, const Vec3D &n, const Vec3D &p)
bool isInsideWallVTK (const Vec3D &point, const Vec3D &normal, const Vec3D &position) const
void projectOntoWallVTK (Vec3D &point0, const Vec3D &point1, const Vec3D &normal, const Vec3D &position) const
void intersectVTK (std::vector< Vec3D > &points, Vec3D normal, Vec3D position) const
virtual BaseInteraction * getInteractionWithSuperQuad (SuperQuadricParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler)
void getVTK (std::vector< Vec3D > &points, std::vector< std::vector< double >> &triangleStrips)
const Vec3D getAxis () const
BaseInteraction * getInteractionWith (BaseParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler) override
Returns the interaction between this wall and a given particle, nullptr if there is no interaction.
virtual void actionsOnRestart ()
No implementation but can be overidden in its derived classes.
virtual void actionsAfterParticleGhostUpdate ()
No implementation but can be overidden in its derived classes.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
virtual void handleParticleRemoval (unsigned int id)
Handles the addition of particles to the particleHandler.
virtual void checkInteractions (InteractionHandler *interactionHandler, unsigned int timeStamp)
Check if all interactions are valid.
bool getVTKVisibility () const
void setVTKVisibility (bool vtkVisibility)
void addRenderedWall (BaseWall *w)
BaseWall * getRenderedWall (size_t i) const
std::vector< BaseWall * > getRenderedWalls () const
void removeRenderedWalls ()
void renderWall (VTKContainer &vtk)
void addParticlesAtWall (unsigned numElements=50)
void setVelocityControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity)
virtual void writeWallDetailsVTK (VTKData &data) const
virtual void computeWear ()
Public Member Functions inherited from BaseInteractable
BaseInteractable ()
Default BaseInteractable constructor.
BaseInteractable (const BaseInteractable &p)
Copy constructor.
~BaseInteractable () override
Destructor, it simply destructs the BaseInteractable and all the objects it contains.
unsigned int getIndSpecies () const
Returns the index of the species associated with the interactable object.
const ParticleSpecies * getSpecies () const
Returns a pointer to the species of this BaseInteractable.
void setSpecies (const ParticleSpecies *species)
Sets the species of this BaseInteractable.
const Vec3D & getForce () const
Returns the force on this BaseInteractable.
const Vec3D & getTorque () const
Returns the torque on this BaseInteractable.
void setForce (const Vec3D &force)
Sets the force on this BaseInteractable.
void setTorque (const Vec3D &torque)
Sets the torque on this BaseInteractable.
void addForce (const Vec3D &addForce)
Adds an amount to the force on this BaseInteractable.
void addTorque (const Vec3D &addTorque)
Adds an amount to the torque on this BaseInteractable.
virtual void resetForceTorque (int numberOfOMPthreads)
void sumForceTorqueOMP ()
const Vec3D & getPosition () const
Returns the position of this BaseInteractable.
const Quaternion & getOrientation () const
Returns the orientation of this BaseInteractable.
virtual void setPosition (const Vec3D &position)
Sets the position of this BaseInteractable.
void setOrientationViaNormal (Vec3D normal)
Sets the orientation of this BaseInteractable by defining the vector that results from the rotation of the (1,0,0) vector.
void setOrientationViaEuler (Vec3D eulerAngle)
Sets the orientation of this BaseInteractable by defining the euler angles.
virtual void setOrientation (const Quaternion &orientation)
Sets the orientation of this BaseInteractable.
virtual void move (const Vec3D &move)
Moves this BaseInteractable by adding an amount to the position.
const std::vector< BaseInteraction * > & getInteractions () const
Returns a list of interactions which belong to this interactable.
void addInteraction (BaseInteraction *I)
Adds an interaction to this BaseInteractable.
bool removeInteraction (BaseInteraction *I)
Removes an interaction from this BaseInteractable.
void copyInteractionsForPeriodicParticles (const BaseInteractable &p)
Copies interactions to this BaseInteractable whenever a periodic copy made.
void setVelocity (const Vec3D &velocity)
set the velocity of the BaseInteractable.
void setAngularVelocity (const Vec3D &angularVelocity)
set the angular velocity of the BaseInteractble.
void addVelocity (const Vec3D &velocity)
adds an increment to the velocity.
void addAngularVelocity (const Vec3D &angularVelocity)
add an increment to the angular velocity.
virtual const Vec3D & getVelocity () const
Returns the velocity of this interactable.
virtual const Vec3D & getAngularVelocity () const
Returns the angular velocity of this interactable.
void setPrescribedPosition (const std::function< Vec3D(double)> &prescribedPosition)
Allows the position of an infinite mass interactable to be prescribed.
void applyPrescribedPosition (double time)
Computes the position from the user defined prescribed position function.
void setPrescribedVelocity (const std::function< Vec3D(double)> &prescribedVelocity)
Allows the velocity of an infinite mass interactable to be prescribed.
void applyPrescribedVelocity (double time)
Computes the velocity from the user defined prescribed velocity function.
void setPrescribedOrientation (const std::function< Quaternion(double)> &prescribedOrientation)
Allows the orientation of the infinite mass interactbale to be prescribed.
void applyPrescribedOrientation (double time)
Computes the orientation from the user defined prescribed orientation function.
void setPrescribedAngularVelocity (const std::function< Vec3D(double)> &prescribedAngularVelocity)
Allows the angular velocity of the infinite mass interactable to be prescribed.
void applyPrescribedAngularVelocity (double time)
Computes the angular velocity from the user defined prescribed angular velocity.
virtual const Vec3D getVelocityAtContact (const Vec3D &contact) const
Returns the velocity at the contact point, use by many force laws.
void integrateBeforeForceComputation (double time, double timeStep)
This is part of integrate routine for objects with infinite mass.
void integrateAfterForceComputation (double time, double timeStep)
This is part of the integration routine for objects with infinite mass.
virtual Mdouble getInvMass () const
virtual Mdouble getCurvature (const Vec3D &labFixedCoordinates) const
virtual bool isFaceContact (const Vec3D &normal) const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
Vec3D start_
The centre of the lower end of the screw.
Mdouble l_
The length of the Screw.
Mdouble maxR_
The outer radius of the Screw.
Mdouble n_
The number of revelations.
Mdouble omega_
Rotation speed in rev/s.
Mdouble offset_
The angle that describes how much the Screw has turned, going from 0 to 1 for a rotation.
Mdouble thickness_
The thickness of the Screw.
ScrewType screwType_
Single or double helix screw.
Additional Inherited Members
Static Public Member Functions inherited from BaseWall
static void addToVTK (const std::vector< Vec3D > &points, VTKContainer &vtk)
Takes the points provided and adds a triangle strip connecting these points to the vtk container.
Detailed Description
This function defines an Archimedes' screw in the z-direction from a (constant) starting point, a (constant) length L, a (constant) radius r, a (constant) number or revelations N and a (constant) rotation speed (rev/s)
q is a new coordinate going from 0 to 1 and t is the time, x=xs+r*cos(2*pi*(offset+N*q)), y=ys+r*sin(2*pi*(offset+N*q)), z=zs+q*L
Todo:
IFCD: Can these details about class Screw be made more clear? I don't understand them.
Constructor & Destructor Documentation
Screw() [1/3]
Screw::Screw ()
Default constructor: make a screw with default parameters.
Make a Screw which is centered in the origin, has a length of 1, one revelation, a radius of 1, turns with 1 revelation per second, is infinitely thin and starts at its normal initial point.
 {
     start_.setZero();
     l_ = 1.0;
     maxR_ = 1.0;
     n_ = 1.0;
     omega_ = 1.0;
     offset_ = 0.0;
     thickness_ = 0.0;
     screwType_ = ScrewType::doubleHelix;
     setOrientationViaNormal({0, 0, 1});//default screw is in z-direction
     logger(DEBUG, "Screw() constructor finished.");
 }
References DEBUG, doubleHelix, l_, logger, maxR_, n_, offset_, omega_, screwType_, BaseInteractable::setOrientationViaNormal(), Vec3D::setZero(), start_, and thickness_.
Referenced by copy().
Screw() [2/3]
Screw::Screw (const Screw & other)
Copy constructor, copies another Screw.
Parameters
[in] other The Screw that has to be copied.
         : BaseWall(other)
 {
     start_ = other.start_;
     l_ = other.l_;
     maxR_ = other.maxR_;
     n_ = other.n_;
     omega_ = other.omega_;
     thickness_ = other.thickness_;
     offset_ = other.offset_;
     screwType_ = other.screwType_;
     logger(DEBUG, "Screw(const Screw&) copy constructor finished.");
 }
References DEBUG, l_, logger, maxR_, n_, offset_, omega_, screwType_, start_, and thickness_.
Screw() [3/3]
Screw::Screw (Vec3D start, Mdouble l, Mdouble r, Mdouble n, Mdouble omega, Mdouble thickness, ScrewType screwType = ScrewType::doubleHelix)
Constructor in which all parameters of the screw are set.
Parameters
[in] start A Vec3D which denotes the centre of the lower end of the Screw.
[in] l The length of the Screw, must be positive.
[in] r The radius of the Screw, must be positive.
[in] n The number of revelations of the Screw, must be positive.
[in] omega The rotation speed of the Screw in rev/s.
[in] thickness The thickness of the Screw, must be non-negative.
Make a Screw by assigning all input parameters to the data-members of this class, and setting the offset_ to 0.
 {
     start_ = start;
     l_ = l;
     maxR_ = r;
     n_ = n;
     omega_ = omega;
     thickness_ = thickness;
     offset_ = 0.0;
     screwType_ = screwType;
     logger(DEBUG, "Screw(Vec3D, Mdouble, Mdouble, Mdouble, Mdouble, Mdouble) constructor finished.");
 }
References DEBUG, l_, logger, maxR_, n, n_, offset_, Eigen::internal::omega(), omega_, UniformPSDSelfTest::r, screwType_, oomph::CumulativeTimings::start(), start_, and thickness_.
~Screw()
Screw::~Screw () override
Default destructor.
 {
     logger(DEBUG, "~Screw() finished, destroyed the Screw.");
 }
References DEBUG, and logger.
Member Function Documentation
copy()
Screw * Screw::copy () const final virtual
Copy this screw and return a pointer to the copy.
Returns
A pointer to a copy of this Screw.
Implements BaseWall.
 {
     return new Screw(*this);
 }
References Screw().
getDistanceAndNormal()
bool Screw::getDistanceAndNormal (const BaseParticle & P, Mdouble & distance, Vec3D & normal_return) const final virtual
Compute the distance from the Screw for a given BaseParticle and return if there is a collision. If there is a collision, also return the normal vector of the interaction point.
Todo:
do this for all walls
Implements BaseWall.
 {
     //transform coordinates into position-orientation frame
     Vec3D position = P.getPosition() - getPosition();
     getOrientation().rotateBack(position);
     BaseSpecies* s = getHandler()->getDPMBase()->speciesHandler.getMixedObject(P.getSpecies(), getSpecies());
     if (getDistanceAndNormalLabCoordinates(position, P.getRadius() + s->getInteractionDistance(), distance,
                                            normal_return))
     {
         getOrientation().rotate(normal_return);
         return true;
     }
     else
     {
         return false;
     }
 }
References getDistanceAndNormalLabCoordinates(), BaseHandler< T >::getDPMBase(), BaseWall::getHandler(), SpeciesHandler::getMixedObject(), BaseInteractable::getOrientation(), BaseInteractable::getPosition(), BaseInteractable::getSpecies(), Global_Physical_Variables::P, Quaternion::rotate(), Quaternion::rotateBack(), s, and DPMBase::speciesHandler.
getDistanceAndNormalLabCoordinates()
bool Screw::getDistanceAndNormalLabCoordinates (Vec3D position, Mdouble wallInteractionRadius, Mdouble & distance, Vec3D & normal_return) const
Parameters
[in] p BaseParticle we want to calculate the distance and whether it collided of.
[out] distance The distance of the BaseParticle to this wall.
[out] normal_return If there was a collision, the normal vector to this wall will be placed here.
Returns
A boolean which says whether or not there was a collision.
This function computes whether or not there is a collision between a given BaseParticle and this Screw. If there is a collision, this function also computes the distance between the BaseParticle and Screw and the normal of the IntersectionOfWalls at the intersection point.
Todo:
Make this function readable and explain the steps in the details.
 {
     // compute the square of the radial distance (in yz-plane) between particle and screw.
     const Mdouble RSquared = square(position.Y - start_.Y) + square(position.Z - start_.Z);
     const Mdouble X = position.X - start_.X;
     //first do a simple check if particle is within the cylindrical hull of the screw
     if (RSquared > square(maxR_ + wallInteractionRadius + thickness_)
         || X > l_ + wallInteractionRadius + thickness_
         || X < -wallInteractionRadius - thickness_)
     {
         return false;
     }
     //else compute radial distance, and angle in yz-plane
     const Mdouble R = sqrt(RSquared);
     const Mdouble A = atan2(position.Z - start_.Z, position.Y - start_.Y);
     //after subtracting the start position and transforming the particle position from (XYZ) into (XRA)
     //coordinates, we compute the distance to the wall at, located at (r,a,z)=(q*L,r,2*pi*(offset+N*q+k/2)), 0<q<1.
     //To find the contact point we have to minimize (with respect to r and q)
     //distance^2=(x-x0-r*cos(2*pi*(offset+N*q)))^2+(y-y0-r*sin(2*pi*(offset+N*q)))^2+(z-z0-q*L)^2
     //Using polar coordinates (i.e. x-x0=R*cos(A), y-y0=R*sin(A) and Z=z-z0)
     //distance^2=R^2+r^2-2*R*r*cos(A-2*pi*(offset+N*q))+(Z-q*L)^2
     //Assumption: d(distance)/dr=0 at minDistance (should there be also a q-derivative?)
     //Differentiate with respect to r and solve for zero:
     //0=2*r-2*R*cos(A-2*pi*(offset+N*q)
     //r=R*cos(A-2*pi*(offset+N*q))
     //Substitue back
     //distance^2=R^2+R^2*cos^2(A-2*pi*(offset+N*q))-2*R^2*cos^2(A-2*pi*(offset+N*q))+(Z-q*L)^2
     //distance^2=R^2*sin^2(A-2*pi*(offset+N*q))+(Z-q*L)^2
     //So we have to minimize:
     //distance^2=R^2*sin^2(A-2*pi*(offset+N*q))^2 + (Z-q*L)^2 = f(q)
     //f'(q)=(-2*pi*N)*R^2*sin(2*A-4*pi*(offset+N*q)) + 2*L*(Z-q*L)    (D[Sin[x]^2,x]=Sin[2x])
     //f''(q)=(4*pi^2*N^2)*R^2*cos(2*A-4*pi*(offset+N*q)) - 2*L*L
     //For this we use the Euler algoritm
     Mdouble q; //Current guess
     Mdouble dd; //Derivative at current guess
     Mdouble ddd; //Second derivative at current guess
     //Set initial q to the closest position on the screw with the same angle as A
     //The initial guess will be in the minimum of the sin closest to q0
     //Minima of the sin are at
     //A-2*pi*(offset+N*q)=k*pi (k=integer)
     //q=A/(2*pi*N)-k/(2*N)-offset/N (k=integer)
     {
         const Mdouble q0 = X / l_; //assume closest point q0 is at same z-location as the particle
         const Mdouble k = round(A / constants::pi - 2.0 * (offset_ + n_ * q0)); // k: |A-a(q0)-k*pi|=min
         q = A / (2.0 * constants::pi * n_) - k / (2.0 * n_) - offset_ / n_; // q: a(q)=A
     }
     //Now apply Newton's method
     unsigned count = 0;
     const unsigned maxCount = 30;
     do
     {
         Mdouble arg = 2.0 * A - 4.0 * constants::pi * (n_ * q + offset_);
         dd = -2.0 * constants::pi * n_ * RSquared * sin(arg) - 2.0 * l_ * (X - q * l_);
         ddd = 8.0 * constants::sqr_pi * n_ * n_ * RSquared * cos(arg) + 2.0 * l_ * l_;
         q -= dd / ddd;
         if(++count>maxCount) {
             logger(WARN,"Screw % contact detection did not converge (err=%); continuing with approximate contact point",getId(),fabs(dd/ddd));
             break;
         }
     } while (fabs(dd / ddd) > 5e-14);
     //Calculate r
     Mdouble r = R * cos(2.0 * constants::pi * (offset_ + n_ * q) - A);
     //If the particle touches the single screw center
     if (screwType_==ScrewType::singleHelix && r>0) {
         distance = R-thickness_;
         if (distance>wallInteractionRadius) {
             return false;
         } else {
             normal_return = Vec3D(0,-position.Y/R,-position.Z/R);
             return true;
         }
     }
     //Check if the location is actually on the screw:
     //First posibility is that the radius is too large:
     Mdouble distanceSquared = 0;
     if (fabs(r) > maxR_) //Left boundary of the coil
     {
         r = mathsFunc::sign(r) * maxR_;
         distanceSquared = mathsFunc::square(R-maxR_);
         count = 0;
         //This case reduces to the coil problem
         do
         {
             dd = -4.0 * R * r * constants::pi * n_ * sin(A - 2.0 * constants::pi * (n_ * q + offset_)) -
                  2.0 * l_ * (X - q * l_);
             ddd = 8.0 * R * r * constants::sqr_pi * n_ * n_ * cos(A - 2.0 * constants::pi * (n_ * q + offset_)) +
                   2.0 * l_ * l_;
             q -= dd / ddd;
             if(++count>maxCount) {
                 logger(WARN,"Screw % contact detection at left boundary did not converge (err=%); continuing with approximate contact point",getId(),fabs(dd/ddd));
                 break;
             }
         } while (fabs(dd / ddd) > 1e-13);
     }
     //Second possibility is that it occured before the start of after the end
     if (q < 0)
     {
         q = 0;
         r = R * cos(A - 2.0 * constants::pi * (offset_ + q * n_));
         if (fabs(r) > maxR_)
         {
             r = mathsFunc::sign(r) * maxR_;
         }
     }
     else if (q > 1)
     {
         q = 1;
         r = R * cos(A - 2.0 * constants::pi * (offset_ + q * n_));
         if (fabs(r) > maxR_)
         {
             r = mathsFunc::sign(r) * maxR_;
         }
     }
     //compute squared distance between particle and contact point
     distanceSquared += square(X - q * l_) + square(R*sin(A - 2 * constants::pi * (offset_ + n_ * q)));
     //If distance is too large there is no contact
     if (distanceSquared >= square(wallInteractionRadius + thickness_))
     {
         return false;
     }
     //Else
     Vec3D ContactPoint;
     distance = sqrt(distanceSquared) - thickness_;
     ContactPoint.Y = start_.Y + r * cos(2.0 * constants::pi * (offset_ + n_ * q));
     ContactPoint.Z = start_.Z + r * sin(2.0 * constants::pi * (offset_ + n_ * q));
     ContactPoint.X = start_.X + q * l_;
     normal_return = (ContactPoint - position);
     normal_return.normalise();
     return true;
 }
References atan2(), cos(), e(), boost::multiprecision::fabs(), BaseObject::getId(), k, l_, logger, maxR_, n_, Vec3D::normalise(), offset_, constants::pi, Eigen::numext::q, UniformPSDSelfTest::r, R, Eigen::bfloat16_impl::round(), screwType_, mathsFunc::sign(), sin(), singleHelix, constants::sqr_pi, sqrt(), mathsFunc::square(), Eigen::square(), start_, thickness_, WARN, X, Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by getDistanceAndNormal().
getName()
std::string Screw::getName () const final virtual
Returns the name of the object, here the string "Screw".
Returns
The string "Screw".
Implements BaseObject.
 {
     return "Screw";
 }
Referenced by writeVTK().
move_time()
void Screw::move_time (Mdouble dt)
Rotate the Screw for a period dt, so that the offset_ changes with omega_*dt.
Parameters
[in] dt The time for which the Screw has to be turned.
 {
     //offset_ += omega_ * dt;
 }
oldRead()
void Screw::oldRead (std::istream & is)
Reads a Screw in the old style from an input stream, for example a restart file old style.
Parameters
[in,out] is Input stream from which the Screw must be read.
Read the Screw in old style, please note that the thickness is not read in this function, so it has either to be set manually or it is 0.0 from the default constructor.
 {
     std::string dummy;
     is >> dummy >> start_
        >> dummy >> l_
        >> dummy >> maxR_
        >> dummy >> n_
        >> dummy >> omega_
        >> dummy >> offset_;
 }
References l_, maxR_, n_, offset_, omega_, start_, and oomph::Global_string_for_annotation::string().
read()
void Screw::read (std::istream & is) override virtual
Reads a Screw from an input stream, for example a restart file.
Parameters
[in,out] is Input stream from which the Screw must be read.
Reimplemented from BaseWall.
 {
     BaseWall::read(is);
     std::string dummy;
     unsigned screwType;
     is >> dummy >> start_
        >> dummy >> l_
        >> dummy >> maxR_
        >> dummy >> n_
        >> dummy >> omega_
        >> dummy >> thickness_
        >> dummy >> offset_
        >> dummy >> screwType;
     screwType_ = static_cast<ScrewType>(screwType);
 }
References l_, maxR_, n_, offset_, omega_, BaseWall::read(), screwType_, start_, oomph::Global_string_for_annotation::string(), and thickness_.
rotate()
void Screw::rotate (const Vec3D & angularVelocityDt) override virtual
Todo:
the move and rotate functions should only pass the time step, as the velocity can be accessed directly by the object
Parameters
angularVelocityDt
Reimplemented from BaseInteractable.
 {
     BaseInteractable::rotate(angularVelocityDt);
     offset_ += omega_ * getHandler()->getDPMBase()->getTimeStep();
 }
References BaseHandler< T >::getDPMBase(), BaseWall::getHandler(), DPMBase::getTimeStep(), offset_, omega_, and BaseInteractable::rotate().
write()
void Screw::write (std::ostream & os) const override virtual
Writes this Screw to an output stream, for example a restart file.
Parameters
[in,out] os Output stream to which the Screw must be written.
Reimplemented from BaseWall.
 {
     BaseWall::write(os);
     os << " start " << start_
        << " Length " << l_
        << " Radius " << maxR_
        << " Revolutions " << n_
        << " Omega " << omega_
        << " Thickness " << thickness_
        << " Offset " << offset_
        << " ScrewType " << static_cast<unsigned>(screwType_);
 }
References l_, maxR_, n_, offset_, omega_, screwType_, start_, thickness_, and BaseWall::write().
writeVTK() [1/2]
void Screw::writeVTK (std::string filename) const
 {
     VTKContainer vtk;
     writeVTK(vtk);
     std::stringstream file;
     file << "# vtk DataFile Version 2.0\n"
          << getName() << "\n"
                          "ASCII\n"
                          "DATASET UNSTRUCTURED_GRID\n"
                          "POINTS " << vtk.points.size() << " double\n";
     for (const auto& vertex : vtk.points)
         file << vertex << '\n';
     file << "\nCELLS " << vtk.triangleStrips.size() << ' ' << 4 * vtk.triangleStrips.size() << "\n";
     for (const auto& face : vtk.triangleStrips)
         file << "3 " << face[0] << ' ' << face[1] << ' ' << face[2] << '\n';
     file << "\nCELL_TYPES " << vtk.triangleStrips.size() << "\n";
     for (const auto& face UNUSED : vtk.triangleStrips)
         file << "5\n";
     helpers::writeToFile(filename, file.str());
 }
References MergeRestartFiles::filename, getName(), VTKContainer::points, VTKContainer::triangleStrips, UNUSED, helpers::writeToFile(), and writeVTK().
writeVTK() [2/2]
void Screw::writeVTK (VTKContainer & vtk) const override virtual
adds extra information to the points and triangleStrips vectors needed to plot the wall in vtk format
Parameters
points Coordinates of the vertices of the triangulated surfaces (in the VTK file this is called POINTS)
triangleStrips Indices of three vertices forming one triangulated surface (in the VTK file this is called CELL)
Reimplemented from BaseWall.
 {
     //number of points in radial direction (for one side of the screw)
     unsigned nr = 5;
     //number of points in axial direction
     unsigned nz = static_cast<unsigned int>(99 * fabs(n_));
     unsigned long nPoints = vtk.points.size();
     Vec3D contactPoint;
     // either one or two helices
     for (Mdouble offset = offset_; offset<=offset_+(screwType_==ScrewType::doubleHelix?0.5:0); offset+=0.5)
     {
         for (unsigned iz = 0; iz < nz; iz++)
         {
             for (unsigned ir = 0; ir < nr; ir++)
             {
                 double q = (double) iz / nz;
                 double r = (double) ir / (nr - 1) * maxR_;
                 contactPoint.Y = start_.Y - r * cos(2.0 * constants::pi * (offset + n_ * q));
                 contactPoint.Z = start_.Z - r * sin(2.0 * constants::pi * (offset + n_ * q));
                 contactPoint.X = start_.X + q * l_ - thickness_;
                 getOrientation().rotate(contactPoint);
                 contactPoint += getPosition();
                 vtk.points.push_back(contactPoint);
             }
             for (unsigned ir = 0; ir < nr; ir++)
             {
                 double q = (double) iz / nz;
                 double r = (double) (nr - 1 - ir) / (nr - 1) * maxR_;
                 contactPoint.Y = start_.Y - r * cos(2.0 * constants::pi * (offset + n_ * q));
                 contactPoint.Z = start_.Z - r * sin(2.0 * constants::pi * (offset + n_ * q));
                 contactPoint.X = start_.X + q * l_ + thickness_;
                 getOrientation().rotate(contactPoint);
                 contactPoint += getPosition();
                 vtk.points.push_back(contactPoint);
             }
         }
     }
     for (unsigned iz = 0; iz < (screwType_==ScrewType::doubleHelix?2:1)*nz-1; iz++)
     {
         //skip step that would connect the two screw parts
         if (iz==nz-1) ++iz;
         std::vector<double> cell;
         cell.reserve(2 * nr);
         for (unsigned ir = 0; ir < 2*nr; ir++)
         {
             cell.push_back(nPoints + ir + 2*iz * nr);
             cell.push_back(nPoints + ir + 2*(iz + 1) * nr);
         }
         vtk.triangleStrips.push_back(cell);
     }
 }
References cos(), doubleHelix, boost::multiprecision::fabs(), BaseInteractable::getOrientation(), BaseInteractable::getPosition(), l_, maxR_, n_, Mesh_Parameters::nz, offset_, constants::pi, VTKContainer::points, Eigen::numext::q, UniformPSDSelfTest::r, Quaternion::rotate(), screwType_, sin(), start_, thickness_, VTKContainer::triangleStrips, Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by writeVTK().
Member Data Documentation
l_
Mdouble Screw::l_ private
The length of the Screw.
Referenced by getDistanceAndNormalLabCoordinates(), oldRead(), read(), Screw(), write(), and writeVTK().
maxR_
Mdouble Screw::maxR_ private
The outer radius of the Screw.
Referenced by getDistanceAndNormalLabCoordinates(), oldRead(), read(), Screw(), write(), and writeVTK().
n_
Mdouble Screw::n_ private
The number of revelations.
Referenced by getDistanceAndNormalLabCoordinates(), oldRead(), read(), Screw(), write(), and writeVTK().
offset_
Mdouble Screw::offset_ private
The angle that describes how much the Screw has turned, going from 0 to 1 for a rotation.
Referenced by getDistanceAndNormalLabCoordinates(), oldRead(), read(), rotate(), Screw(), write(), and writeVTK().
omega_
Mdouble Screw::omega_ private
Rotation speed in rev/s.
Referenced by oldRead(), read(), rotate(), Screw(), and write().
screwType_
ScrewType Screw::screwType_ private
Single or double helix screw.
Referenced by getDistanceAndNormalLabCoordinates(), read(), Screw(), write(), and writeVTK().
start_
Vec3D Screw::start_ private
The centre of the lower end of the screw.
Referenced by getDistanceAndNormalLabCoordinates(), oldRead(), read(), Screw(), write(), and writeVTK().
thickness_
Mdouble Screw::thickness_ private
The thickness of the Screw.
Referenced by getDistanceAndNormalLabCoordinates(), read(), Screw(), write(), and writeVTK().
The documentation for this class was generated from the following files:
Screw.h
Screw.cc