MercuryDPM: Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ > Class Template Reference
Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ > Class Template Reference
Dense linear problems and decompositions » Reference » QR_Module
Householder rank-revealing QR decomposition of a matrix with column-pivoting.
#include <ColPivHouseholderQR.h>
Public Types
enum { MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime , MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef MatrixType_ MatrixType
typedef SolverBase< ColPivHouseholderQR > Base
typedef PermutationIndex_ PermutationIndex
typedef internal::plain_diag_type< MatrixType >::type HCoeffsType
typedef PermutationMatrix< ColsAtCompileTime, MaxColsAtCompileTime, PermutationIndex > PermutationType
typedef internal::plain_row_type< MatrixType, PermutationIndex >::type IntRowVectorType
typedef internal::plain_row_type< MatrixType >::type RowVectorType
typedef internal::plain_row_type< MatrixType, RealScalar >::type RealRowVectorType
typedef HouseholderSequence< MatrixType, internal::remove_all_t< typename HCoeffsType::ConjugateReturnType > > HouseholderSequenceType
typedef MatrixType::PlainObject PlainObject
Public Types inherited from Eigen::SolverBase< ColPivHouseholderQR< MatrixType_, PermutationIndex_ > >
enum
typedef EigenBase< ColPivHouseholderQR< MatrixType_, PermutationIndex_ > > Base
typedef internal::traits< ColPivHouseholderQR< MatrixType_, PermutationIndex_ > >::Scalar Scalar
typedef Scalar CoeffReturnType
typedef Transpose< const ColPivHouseholderQR< MatrixType_, PermutationIndex_ > > ConstTransposeReturnType
typedef std::conditional_t< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, const ConstTransposeReturnType >, const ConstTransposeReturnType > AdjointReturnType
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
ColPivHouseholderQR ()
Default Constructor.
ColPivHouseholderQR (Index rows, Index cols)
Default Constructor with memory preallocation.
template<typename InputType >
ColPivHouseholderQR (const EigenBase< InputType > &matrix)
Constructs a QR factorization from a given matrix.
template<typename InputType >
ColPivHouseholderQR (EigenBase< InputType > &matrix)
Constructs a QR factorization from a given matrix.
HouseholderSequenceType householderQ () const
HouseholderSequenceType matrixQ () const
const MatrixType & matrixQR () const
const MatrixType & matrixR () const
template<typename InputType >
ColPivHouseholderQR & compute (const EigenBase< InputType > &matrix)
const PermutationType & colsPermutation () const
MatrixType::Scalar determinant () const
MatrixType::RealScalar absDeterminant () const
MatrixType::RealScalar logAbsDeterminant () const
MatrixType::Scalar signDeterminant () const
Index rank () const
Index dimensionOfKernel () const
bool isInjective () const
bool isSurjective () const
bool isInvertible () const
const Inverse< ColPivHouseholderQR > inverse () const
Index rows () const
Index cols () const
const HCoeffsType & hCoeffs () const
ColPivHouseholderQR & setThreshold (const RealScalar &threshold)
ColPivHouseholderQR & setThreshold (Default_t)
RealScalar threshold () const
Index nonzeroPivots () const
RealScalar maxPivot () const
ComputationInfo info () const
Reports whether the QR factorization was successful.
template<typename RhsType , typename DstType >
void _solve_impl (const RhsType &rhs, DstType &dst) const
template<bool Conjugate, typename RhsType , typename DstType >
void _solve_impl_transposed (const RhsType &rhs, DstType &dst) const
template<typename InputType >
ColPivHouseholderQR< MatrixType, PermutationIndex > & compute (const EigenBase< InputType > &matrix)
Public Member Functions inherited from Eigen::SolverBase< ColPivHouseholderQR< MatrixType_, PermutationIndex_ > >
SolverBase ()
~SolverBase ()
const Solve< ColPivHouseholderQR< MatrixType_, PermutationIndex_ >, Rhs > solve (const MatrixBase< Rhs > &b) const
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
constexpr EIGEN_DEVICE_FUNC ColPivHouseholderQR< MatrixType_, PermutationIndex_ > & derived ()
constexpr EIGEN_DEVICE_FUNC const ColPivHouseholderQR< MatrixType_, PermutationIndex_ > & derived () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
constexpr EIGEN_DEVICE_FUNC Derived & derived ()
constexpr EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< Derived, Device > device (Device &device)
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const Derived, Device > device (Device &device) const
Protected Member Functions
void computeInPlace ()
Protected Member Functions inherited from Eigen::SolverBase< ColPivHouseholderQR< MatrixType_, PermutationIndex_ > >
void _check_solve_assertion (const Rhs &b) const
Protected Attributes
MatrixType m_qr
HCoeffsType m_hCoeffs
PermutationType m_colsPermutation
IntRowVectorType m_colsTranspositions
RowVectorType m_temp
RealRowVectorType m_colNormsUpdated
RealRowVectorType m_colNormsDirect
bool m_isInitialized
bool m_usePrescribedThreshold
RealScalar m_prescribedThreshold
RealScalar m_maxpivot
Index m_nonzero_pivots
Index m_det_p
Private Member Functions
void init (Index rows, Index cols)
Friends
class SolverBase< ColPivHouseholderQR >
class CompleteOrthogonalDecomposition< MatrixType, PermutationIndex >
Detailed Description
template<typename MatrixType_, typename PermutationIndex_>
class Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >
Householder rank-revealing QR decomposition of a matrix with column-pivoting.
Template Parameters
MatrixType_ the type of the matrix of which we are computing the QR decomposition
This class performs a rank-revealing QR decomposition of a matrix A into matrices P, Q and R such that
\[ \mathbf{A} \, \mathbf{P} = \mathbf{Q} \, \mathbf{R} \]
by using Householder transformations. Here, P is a permutation matrix, Q a unitary matrix and R an upper triangular matrix.
This decomposition performs column pivoting in order to be rank-revealing and improve numerical stability. It is slower than HouseholderQR, and faster than FullPivHouseholderQR.
This class supports the inplace decomposition mechanism.
See also
MatrixBase::colPivHouseholderQr()
Member Typedef Documentation
Base
template<typename MatrixType_ , typename PermutationIndex_ > typedef SolverBase<ColPivHouseholderQR> Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::Base
HCoeffsType
template<typename MatrixType_ , typename PermutationIndex_ > typedef internal::plain_diag_type<MatrixType>::type Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::HCoeffsType
HouseholderSequenceType
template<typename MatrixType_ , typename PermutationIndex_ > typedef HouseholderSequence<MatrixType, internal::remove_all_t<typename HCoeffsType::ConjugateReturnType> > Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::HouseholderSequenceType
IntRowVectorType
template<typename MatrixType_ , typename PermutationIndex_ > typedef internal::plain_row_type<MatrixType, PermutationIndex>::type Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::IntRowVectorType
MatrixType
template<typename MatrixType_ , typename PermutationIndex_ > typedef MatrixType_ Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::MatrixType
PermutationIndex
template<typename MatrixType_ , typename PermutationIndex_ > typedef PermutationIndex_ Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::PermutationIndex
PermutationType
template<typename MatrixType_ , typename PermutationIndex_ > typedef PermutationMatrix<ColsAtCompileTime, MaxColsAtCompileTime, PermutationIndex> Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::PermutationType
PlainObject
template<typename MatrixType_ , typename PermutationIndex_ > typedef MatrixType::PlainObject Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::PlainObject
RealRowVectorType
template<typename MatrixType_ , typename PermutationIndex_ > typedef internal::plain_row_type<MatrixType, RealScalar>::type Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::RealRowVectorType
RowVectorType
template<typename MatrixType_ , typename PermutationIndex_ > typedef internal::plain_row_type<MatrixType>::type Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::RowVectorType
Member Enumeration Documentation
anonymous enum
template<typename MatrixType_ , typename PermutationIndex_ > anonymous enum
Enumerator
MaxRowsAtCompileTime
MaxColsAtCompileTime
        {
     MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
     MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
   };
Constructor & Destructor Documentation
ColPivHouseholderQR() [1/4]
template<typename MatrixType_ , typename PermutationIndex_ > Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::ColPivHouseholderQR () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via ColPivHouseholderQR::compute(const MatrixType&).
       : m_qr(),
         m_hCoeffs(),
         m_colsPermutation(),
         m_colsTranspositions(),
         m_temp(),
         m_colNormsUpdated(),
         m_colNormsDirect(),
         m_isInitialized(false),
         m_usePrescribedThreshold(false) {}
ColPivHouseholderQR() [2/4]
template<typename MatrixType_ , typename PermutationIndex_ > Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::ColPivHouseholderQR (Index rows, Index cols) inline
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
ColPivHouseholderQR()
 : m_qr(rows, cols) { init(rows, cols); }
References Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::cols(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::init(), and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::rows().
ColPivHouseholderQR() [3/4]
template<typename MatrixType_ , typename PermutationIndex_ > template<typename InputType > Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::ColPivHouseholderQR (const EigenBase< InputType > & matrix) inline explicit
Constructs a QR factorization from a given matrix.
This constructor computes the QR factorization of the matrix matrix by calling the method compute(). It is a short cut for:
ColPivHouseholderQR<MatrixType> qr(matrix.rows(), matrix.cols());
qr.compute(matrix);
See also
compute()
                                                                    : m_qr(matrix.rows(), matrix.cols()) {
     init(matrix.rows(), matrix.cols());
     compute(matrix.derived());
   }
References Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::compute(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::init(), and matrix().
ColPivHouseholderQR() [4/4]
template<typename MatrixType_ , typename PermutationIndex_ > template<typename InputType > Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::ColPivHouseholderQR (EigenBase< InputType > & matrix) inline explicit
Constructs a QR factorization from a given matrix.
This overloaded constructor is provided for inplace decomposition when MatrixType is a Eigen::Ref.
See also
ColPivHouseholderQR(const EigenBase&)
                                                              : m_qr(matrix.derived()) {
     init(matrix.rows(), matrix.cols());
     computeInPlace();
   }
References Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::init(), and matrix().
Member Function Documentation
_solve_impl()
template<typename MatrixType_ , typename PermutationIndex_ > template<typename RhsType , typename DstType > void Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl (const RhsType & rhs, DstType & dst) const
{
   const Index nonzero_pivots = nonzeroPivots();
   if (nonzero_pivots == 0) {
     dst.setZero();
     return;
   }
   typename RhsType::PlainObject c(rhs);
   c.applyOnTheLeft(householderQ().setLength(nonzero_pivots).adjoint());
   m_qr.topLeftCorner(nonzero_pivots, nonzero_pivots)
       .template triangularView<Upper>()
       .solveInPlace(c.topRows(nonzero_pivots));
   for (Index i = 0; i < nonzero_pivots; ++i) dst.row(m_colsPermutation.indices().coeff(i)) = c.row(i);
   for (Index i = nonzero_pivots; i < cols(); ++i) dst.row(m_colsPermutation.indices().coeff(i)).setZero();
 }
References Eigen::SolverBase< ColPivHouseholderQR< MatrixType_, PermutationIndex_ > >::adjoint(), calibrate::c, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::cols(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::householderQ(), i, Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::indices(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_colsPermutation, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::nonzeroPivots(), and setZero().
_solve_impl_transposed()
template<typename MatrixType_ , typename PermutationIndex_ > template<bool Conjugate, typename RhsType , typename DstType > void Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl_transposed (const RhsType & rhs, DstType & dst) const
{
   const Index nonzero_pivots = nonzeroPivots();
   if (nonzero_pivots == 0) {
     dst.setZero();
     return;
   }
   typename RhsType::PlainObject c(m_colsPermutation.transpose() * rhs);
   m_qr.topLeftCorner(nonzero_pivots, nonzero_pivots)
       .template triangularView<Upper>()
       .transpose()
       .template conjugateIf<Conjugate>()
       .solveInPlace(c.topRows(nonzero_pivots));
   dst.topRows(nonzero_pivots) = c.topRows(nonzero_pivots);
   dst.bottomRows(rows() - nonzero_pivots).setZero();
   dst.applyOnTheLeft(householderQ().setLength(nonzero_pivots).template conjugateIf<!Conjugate>());
 }
References calibrate::c, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::householderQ(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_colsPermutation, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::nonzeroPivots(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::rows(), and Eigen::PermutationBase< Derived >::transpose().
absDeterminant()
template<typename MatrixType , typename PermutationIndex > MatrixType::RealScalar Eigen::ColPivHouseholderQR< MatrixType, PermutationIndex >::absDeterminant
Returns
the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow. One way to work around that is to use logAbsDeterminant() instead.
See also
determinant(), logAbsDeterminant(), MatrixBase::determinant()
{
   using std::abs;
   eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
   eigen_assert(m_qr.rows() == m_qr.cols() && "You can't take the determinant of a non-square matrix!");
   return isInjective() ? abs(m_qr.diagonal().prod()) : RealScalar(0);
 }
References abs(), eigen_assert, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInjective(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr.
cols()
template<typename MatrixType_ , typename PermutationIndex_ > Index Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::cols () const inline
 { return m_qr.cols(); }
References Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::ColPivHouseholderQR(), Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::cols(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::dimensionOfKernel(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::init(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInjective(), Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::matrixZ(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
colsPermutation()
template<typename MatrixType_ , typename PermutationIndex_ > const PermutationType& Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::colsPermutation () const inline
Returns
a const reference to the column permutation matrix
{
     eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
     return m_colsPermutation;
   }
References eigen_assert, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_colsPermutation, and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized.
Referenced by Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::colsPermutation(), and Eigen::LevenbergMarquardt< FunctorType_ >::minimizeOptimumStorageOneStep().
compute() [1/2]
template<typename MatrixType_ , typename PermutationIndex_ > template<typename InputType > ColPivHouseholderQR& Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::compute (const EigenBase< InputType > & matrix)
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::ColPivHouseholderQR(), Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::compute(), and ctms_decompositions().
compute() [2/2]
template<typename MatrixType_ , typename PermutationIndex_ > template<typename InputType > ColPivHouseholderQR<MatrixType, PermutationIndex>& Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::compute (const EigenBase< InputType > & matrix)
Performs the QR factorization of the given matrix matrix. The result of the factorization is stored into *this, and a reference to *this is returned.
See also
class ColPivHouseholderQR, ColPivHouseholderQR(const MatrixType&)
{
   m_qr = matrix.derived();
   computeInPlace();
   return *this;
 }
References Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr, and matrix().
computeInPlace()
template<typename MatrixType , typename PermutationIndex > void Eigen::ColPivHouseholderQR< MatrixType, PermutationIndex >::computeInPlace protected
{
   eigen_assert(m_qr.cols() <= NumTraits<PermutationIndex>::highest());
   using std::abs;
   Index rows = m_qr.rows();
   Index cols = m_qr.cols();
   Index size = m_qr.diagonalSize();
   m_hCoeffs.resize(size);
   m_temp.resize(cols);
   m_colsTranspositions.resize(m_qr.cols());
   Index number_of_transpositions = 0;
   m_colNormsUpdated.resize(cols);
   m_colNormsDirect.resize(cols);
   for (Index k = 0; k < cols; ++k) {
     // colNormsDirect(k) caches the most recent directly computed norm of
     // column k.
     m_colNormsDirect.coeffRef(k) = m_qr.col(k).norm();
     m_colNormsUpdated.coeffRef(k) = m_colNormsDirect.coeffRef(k);
   }
   RealScalar threshold_helper =
       numext::abs2<RealScalar>(m_colNormsUpdated.maxCoeff() * NumTraits<RealScalar>::epsilon()) / RealScalar(rows);
   RealScalar norm_downdate_threshold = numext::sqrt(NumTraits<RealScalar>::epsilon());
   m_nonzero_pivots = size;  // the generic case is that in which all pivots are nonzero (invertible case)
   m_maxpivot = RealScalar(0);
   for (Index k = 0; k < size; ++k) {
     // first, we look up in our table m_colNormsUpdated which column has the biggest norm
     Index biggest_col_index;
     RealScalar biggest_col_sq_norm = numext::abs2(m_colNormsUpdated.tail(cols - k).maxCoeff(&biggest_col_index));
     biggest_col_index += k;
     // Track the number of meaningful pivots but do not stop the decomposition to make
     // sure that the initial matrix is properly reproduced. See bug 941.
     if (m_nonzero_pivots == size && biggest_col_sq_norm < threshold_helper * RealScalar(rows - k)) m_nonzero_pivots = k;
     // apply the transposition to the columns
     m_colsTranspositions.coeffRef(k) = static_cast<PermutationIndex>(biggest_col_index);
     if (k != biggest_col_index) {
       m_qr.col(k).swap(m_qr.col(biggest_col_index));
       std::swap(m_colNormsUpdated.coeffRef(k), m_colNormsUpdated.coeffRef(biggest_col_index));
       std::swap(m_colNormsDirect.coeffRef(k), m_colNormsDirect.coeffRef(biggest_col_index));
       ++number_of_transpositions;
     }
     // generate the householder vector, store it below the diagonal
     RealScalar beta;
     m_qr.col(k).tail(rows - k).makeHouseholderInPlace(m_hCoeffs.coeffRef(k), beta);
     // apply the householder transformation to the diagonal coefficient
     m_qr.coeffRef(k, k) = beta;
     // remember the maximum absolute value of diagonal coefficients
     if (abs(beta) > m_maxpivot) m_maxpivot = abs(beta);
     // apply the householder transformation
     m_qr.bottomRightCorner(rows - k, cols - k - 1)
         .applyHouseholderOnTheLeft(m_qr.col(k).tail(rows - k - 1), m_hCoeffs.coeffRef(k), &m_temp.coeffRef(k + 1));
     // update our table of norms of the columns
     for (Index j = k + 1; j < cols; ++j) {
       // The following implements the stable norm downgrade step discussed in
       // http://www.netlib.org/lapack/lawnspdf/lawn176.pdf
       // and used in LAPACK routines xGEQPF and xGEQP3.
       // See lines 278-297 in http://www.netlib.org/lapack/explore-html/dc/df4/sgeqpf_8f_source.html
       if (!numext::is_exactly_zero(m_colNormsUpdated.coeffRef(j))) {
         RealScalar temp = abs(m_qr.coeffRef(k, j)) / m_colNormsUpdated.coeffRef(j);
         temp = (RealScalar(1) + temp) * (RealScalar(1) - temp);
         temp = temp < RealScalar(0) ? RealScalar(0) : temp;
         RealScalar temp2 =
             temp * numext::abs2<RealScalar>(m_colNormsUpdated.coeffRef(j) / m_colNormsDirect.coeffRef(j));
         if (temp2 <= norm_downdate_threshold) {
           // The updated norm has become too inaccurate so re-compute the column
           // norm directly.
           m_colNormsDirect.coeffRef(j) = m_qr.col(j).tail(rows - k - 1).norm();
           m_colNormsUpdated.coeffRef(j) = m_colNormsDirect.coeffRef(j);
         } else {
           m_colNormsUpdated.coeffRef(j) *= numext::sqrt(temp);
         }
       }
     }
   }
   m_colsPermutation.setIdentity(cols);
   for (Index k = 0; k < size /*m_nonzero_pivots*/; ++k)
     m_colsPermutation.applyTranspositionOnTheRight(k, static_cast<Index>(m_colsTranspositions.coeff(k)));
   m_det_p = (number_of_transpositions % 2) ? -1 : 1;
   m_isInitialized = true;
 }
References abs(), Eigen::numext::abs2(), Eigen::PermutationBase< Derived >::applyTranspositionOnTheRight(), beta, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::cols(), eigen_assert, Eigen::numext::is_exactly_zero(), j, k, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_colNormsDirect, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_colNormsUpdated, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_colsPermutation, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_colsTranspositions, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_det_p, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_hCoeffs, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_maxpivot, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_nonzero_pivots, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_temp, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::rows(), Eigen::PermutationBase< Derived >::setIdentity(), Eigen::EigenBase< Derived >::size(), Eigen::numext::sqrt(), and swap().
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::ColPivHouseholderQR(), and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::compute().
determinant()
template<typename MatrixType , typename PermutationIndex > MatrixType::Scalar Eigen::ColPivHouseholderQR< MatrixType, PermutationIndex >::determinant
Returns
the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow. One way to work around that is to use logAbsDeterminant() instead.
See also
absDeterminant(), logAbsDeterminant(), MatrixBase::determinant()
{
   eigen_assert(m_isInitialized && "HouseholderQR is not initialized.");
   eigen_assert(m_qr.rows() == m_qr.cols() && "You can't take the determinant of a non-square matrix!");
   Scalar detQ;
   internal::householder_determinant<HCoeffsType, Scalar, NumTraits<Scalar>::IsComplex>::run(m_hCoeffs, detQ);
   return isInjective() ? (detQ * Scalar(m_det_p)) * m_qr.diagonal().prod() : Scalar(0);
 }
References eigen_assert, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInjective(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_det_p, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_hCoeffs, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr, and Eigen::run().
dimensionOfKernel()
template<typename MatrixType_ , typename PermutationIndex_ > Index Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::dimensionOfKernel () const inline
Returns
the dimension of the kernel of the matrix of which *this is the QR decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
{
     eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
     return cols() - rank();
   }
References Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::cols(), eigen_assert, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank().
Referenced by Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::dimensionOfKernel().
hCoeffs()
template<typename MatrixType_ , typename PermutationIndex_ > const HCoeffsType& Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::hCoeffs () const inline
Returns
a const reference to the vector of Householder coefficients used to represent the factor Q.
For advanced uses only.
 { return m_hCoeffs; }
References Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_hCoeffs.
Referenced by Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::hCoeffs(), and Eigen::LevenbergMarquardt< FunctorType_ >::minimizeOptimumStorageOneStep().
householderQ()
template<typename MatrixType , typename PermutationIndex > ColPivHouseholderQR< MatrixType, PermutationIndex >::HouseholderSequenceType Eigen::ColPivHouseholderQR< MatrixType, PermutationIndex >::householderQ
Returns
the matrix Q as a sequence of householder transformations. You can extract the meaningful part only by using:
qr.householderQ().setLength(qr.nonzeroPivots())
{
   eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
   return HouseholderSequenceType(m_qr, m_hCoeffs.conjugate());
 }
References eigen_assert, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_hCoeffs, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr.
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl_transposed(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::matrixQ(), and Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::matrixQ().
info()
template<typename MatrixType_ , typename PermutationIndex_ > ComputationInfo Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::info () const inline
Reports whether the QR factorization was successful.
Note
This function always returns Success. It is provided for compatibility with other factorization routines.
Returns
Success
{
     eigen_assert(m_isInitialized && "Decomposition is not initialized.");
     return Success;
   }
References eigen_assert, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::Success.
init()
template<typename MatrixType_ , typename PermutationIndex_ > void Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::init (Index rows, Index cols) inline private
{
     Index diag = numext::mini(rows, cols);
     m_hCoeffs.resize(diag);
     m_colsPermutation.resize(cols);
     m_colsTranspositions.resize(cols);
     m_temp.resize(cols);
     m_colNormsUpdated.resize(cols);
     m_colNormsDirect.resize(cols);
     m_isInitialized = false;
     m_usePrescribedThreshold = false;
   }
References Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::cols(), diag, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_colNormsDirect, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_colNormsUpdated, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_colsPermutation, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_colsTranspositions, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_hCoeffs, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_temp, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_usePrescribedThreshold, Eigen::numext::mini(), Eigen::PermutationBase< Derived >::resize(), and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::rows().
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::ColPivHouseholderQR().
inverse()
template<typename MatrixType_ , typename PermutationIndex_ > const Inverse<ColPivHouseholderQR> Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::inverse () const inline
Returns
the inverse of the matrix of which *this is the QR decomposition.
Note
If this matrix is not invertible, the returned matrix has undefined coefficients. Use isInvertible() to first determine whether this matrix is invertible.
{
     eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
     return Inverse<ColPivHouseholderQR>(*this);
   }
References eigen_assert, and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized.
isInjective()
template<typename MatrixType_ , typename PermutationIndex_ > bool Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInjective () const inline
Returns
true if the matrix of which *this is the QR decomposition represents an injective linear map, i.e. has trivial kernel; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
{
     eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
     return rank() == cols();
   }
References Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::cols(), eigen_assert, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank().
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::absDeterminant(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::determinant(), Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::isInjective(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInvertible(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::logAbsDeterminant(), and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::signDeterminant().
isInvertible()
template<typename MatrixType_ , typename PermutationIndex_ > bool Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInvertible () const inline
Returns
true if the matrix of which *this is the QR decomposition is invertible.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
{
     eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
     return isInjective() && isSurjective();
   }
References eigen_assert, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInjective(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::isSurjective(), and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized.
Referenced by Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::isInvertible().
isSurjective()
template<typename MatrixType_ , typename PermutationIndex_ > bool Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::isSurjective () const inline
Returns
true if the matrix of which *this is the QR decomposition represents a surjective linear map; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
{
     eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
     return rank() == rows();
   }
References eigen_assert, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank(), and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::rows().
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInvertible(), and Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::isSurjective().
logAbsDeterminant()
template<typename MatrixType , typename PermutationIndex > MatrixType::RealScalar Eigen::ColPivHouseholderQR< MatrixType, PermutationIndex >::logAbsDeterminant
Returns
the natural log of the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
This method is useful to work around the risk of overflow/underflow that's inherent to determinant computation.
See also
determinant(), absDeterminant(), MatrixBase::determinant()
{
   eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
   eigen_assert(m_qr.rows() == m_qr.cols() && "You can't take the determinant of a non-square matrix!");
   return isInjective() ? m_qr.diagonal().cwiseAbs().array().log().sum() : -NumTraits<RealScalar>::infinity();
 }
References eigen_assert, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInjective(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr.
matrixQ()
template<typename MatrixType_ , typename PermutationIndex_ > HouseholderSequenceType Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::matrixQ () const inline
 { return householderQ(); }
References Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::householderQ().
matrixQR()
template<typename MatrixType_ , typename PermutationIndex_ > const MatrixType& Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::matrixQR () const inline
Returns
a reference to the matrix where the Householder QR decomposition is stored
{
     eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
     return m_qr;
   }
References eigen_assert, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr.
Referenced by Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::matrixQTZ(), Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::matrixT(), and Eigen::LevenbergMarquardt< FunctorType_ >::minimizeOptimumStorageOneStep().
matrixR()
template<typename MatrixType_ , typename PermutationIndex_ > const MatrixType& Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::matrixR () const inline
Returns
a reference to the matrix where the result Householder QR is stored
Warning
The strict lower part of this matrix contains internal values. Only the upper triangular part should be referenced. To get it, use
matrixR().template triangularView<Upper>()
For rank-deficient matrices, use
matrixR().topLeftCorner(rank(), rank()).template triangularView<Upper>()
{
     eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
     return m_qr;
   }
References eigen_assert, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr.
maxPivot()
template<typename MatrixType_ , typename PermutationIndex_ > RealScalar Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::maxPivot () const inline
Returns
the absolute value of the biggest pivot, i.e. the biggest diagonal coefficient of R.
 { return m_maxpivot; }
References Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_maxpivot.
Referenced by Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::maxPivot().
nonzeroPivots()
template<typename MatrixType_ , typename PermutationIndex_ > Index Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::nonzeroPivots () const inline
Returns
the number of nonzero pivots in the QR decomposition. Here nonzero is meant in the exact sense, not in a fuzzy sense. So that notion isn't really intrinsically interesting, but it is still useful when implementing algorithms.
See also
rank()
{
     eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
     return m_nonzero_pivots;
   }
References eigen_assert, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_nonzero_pivots.
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl_transposed(), and Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::nonzeroPivots().
rank()
template<typename MatrixType_ , typename PermutationIndex_ > Index Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank () const inline
Returns
the rank of the matrix of which *this is the QR decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
{
     using std::abs;
     eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
     RealScalar premultiplied_threshold = abs(m_maxpivot) * threshold();
     Index result = 0;
     for (Index i = 0; i < m_nonzero_pivots; ++i) result += (abs(m_qr.coeff(i, i)) > premultiplied_threshold);
     return result;
   }
References abs(), eigen_assert, i, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_maxpivot, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_nonzero_pivots, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr, and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::threshold().
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::dimensionOfKernel(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInjective(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::isSurjective(), Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::rank(), and test_sparseqr_scalar().
rows()
template<typename MatrixType_ , typename PermutationIndex_ > Index Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::rows () const inline
 { return m_qr.rows(); }
References Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl_transposed(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::ColPivHouseholderQR(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::init(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::isSurjective(), Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::rows(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
setThreshold() [1/2]
template<typename MatrixType_ , typename PermutationIndex_ > ColPivHouseholderQR& Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::setThreshold (const RealScalar & threshold) inline
Allows to prescribe a threshold to be used by certain methods, such as rank(), who need to determine when pivots are to be considered nonzero. This is not used for the QR decomposition itself.
When it needs to get the threshold value, Eigen calls threshold(). By default, this uses a formula to automatically determine a reasonable threshold. Once you have called the present method setThreshold(const RealScalar&), your value is used instead.
Parameters
threshold The new value to use as the threshold.
A pivot will be considered nonzero if its absolute value is strictly greater than \(\vert pivot \vert \leqslant threshold \times \vert maxpivot \vert \) where maxpivot is the biggest pivot.
If you want to come back to the default behavior, call setThreshold(Default_t)
{
     m_usePrescribedThreshold = true;
     m_prescribedThreshold = threshold;
     return *this;
   }
References Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_prescribedThreshold, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_usePrescribedThreshold, and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::threshold().
Referenced by Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::setThreshold().
setThreshold() [2/2]
template<typename MatrixType_ , typename PermutationIndex_ > ColPivHouseholderQR& Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::setThreshold (Default_t) inline
Allows to come back to the default behavior, letting Eigen use its default formula for determining the threshold.
You should pass the special object Eigen::Default as parameter here.
qr.setThreshold(Eigen::Default);
See the documentation of setThreshold(const RealScalar&).
{
     m_usePrescribedThreshold = false;
     return *this;
   }
References Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_usePrescribedThreshold.
signDeterminant()
template<typename MatrixType , typename PermutationIndex > MatrixType::Scalar Eigen::ColPivHouseholderQR< MatrixType, PermutationIndex >::signDeterminant
Returns
the sign of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
This method is useful to work around the risk of overflow/underflow that's inherent to determinant computation.
See also
determinant(), absDeterminant(), logAbsDeterminant(), MatrixBase::determinant()
{
   eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
   eigen_assert(m_qr.rows() == m_qr.cols() && "You can't take the determinant of a non-square matrix!");
   Scalar detQ;
   internal::householder_determinant<HCoeffsType, Scalar, NumTraits<Scalar>::IsComplex>::run(m_hCoeffs, detQ);
   return isInjective() ? (detQ * Scalar(m_det_p)) * m_qr.diagonal().array().sign().prod() : Scalar(0);
 }
References eigen_assert, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInjective(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_det_p, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_hCoeffs, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr, and Eigen::run().
threshold()
template<typename MatrixType_ , typename PermutationIndex_ > RealScalar Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::threshold () const inline
Returns the threshold that will be used by certain methods such as rank().
See the documentation of setThreshold(const RealScalar&).
{
     eigen_assert(m_isInitialized || m_usePrescribedThreshold);
     return m_usePrescribedThreshold ? m_prescribedThreshold
                                     // this formula comes from experimenting (see "LU precision tuning" thread on the
                                     // list) and turns out to be identical to Higham's formula used already in LDLt.
                                     : NumTraits<Scalar>::epsilon() * RealScalar(m_qr.diagonalSize());
   }
References eigen_assert, oomph::SarahBL::epsilon, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_prescribedThreshold, Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr, and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_usePrescribedThreshold.
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::setThreshold(), and Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::threshold().
Friends And Related Function Documentation
CompleteOrthogonalDecomposition< MatrixType, PermutationIndex >
template<typename MatrixType_ , typename PermutationIndex_ > friend class CompleteOrthogonalDecomposition< MatrixType, PermutationIndex > friend
SolverBase< ColPivHouseholderQR >
template<typename MatrixType_ , typename PermutationIndex_ > friend class SolverBase< ColPivHouseholderQR > friend
Member Data Documentation
m_colNormsDirect
template<typename MatrixType_ , typename PermutationIndex_ > RealRowVectorType Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_colNormsDirect protected
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::init().
m_colNormsUpdated
template<typename MatrixType_ , typename PermutationIndex_ > RealRowVectorType Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_colNormsUpdated protected
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::init().
m_colsPermutation
template<typename MatrixType_ , typename PermutationIndex_ > PermutationType Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_colsPermutation protected
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl_transposed(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::colsPermutation(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::init().
m_colsTranspositions
template<typename MatrixType_ , typename PermutationIndex_ > IntRowVectorType Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_colsTranspositions protected
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::init().
m_det_p
template<typename MatrixType_ , typename PermutationIndex_ > Index Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_det_p protected
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::determinant(), and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::signDeterminant().
m_hCoeffs
template<typename MatrixType_ , typename PermutationIndex_ > HCoeffsType Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_hCoeffs protected
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::determinant(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::hCoeffs(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::householderQ(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::init(), and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::signDeterminant().
m_isInitialized
template<typename MatrixType_ , typename PermutationIndex_ > bool Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized protected
Referenced by Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::_check_solve_assertion(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::absDeterminant(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::colsPermutation(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::determinant(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::dimensionOfKernel(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::householderQ(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::info(), Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::info(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::init(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::inverse(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInjective(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInvertible(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::isSurjective(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::logAbsDeterminant(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::matrixQR(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::matrixR(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::nonzeroPivots(), Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::pseudoInverse(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::signDeterminant(), and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::threshold().
m_maxpivot
template<typename MatrixType_ , typename PermutationIndex_ > RealScalar Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_maxpivot protected
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::maxPivot(), and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank().
m_nonzero_pivots
template<typename MatrixType_ , typename PermutationIndex_ > Index Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_nonzero_pivots protected
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::nonzeroPivots(), and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank().
m_prescribedThreshold
template<typename MatrixType_ , typename PermutationIndex_ > RealScalar Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_prescribedThreshold protected
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::setThreshold(), and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::threshold().
m_qr
template<typename MatrixType_ , typename PermutationIndex_ > MatrixType Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr protected
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl_transposed(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::absDeterminant(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::cols(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::compute(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::determinant(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::householderQ(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::logAbsDeterminant(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::matrixQR(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::matrixR(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::rows(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::signDeterminant(), and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::threshold().
m_temp
template<typename MatrixType_ , typename PermutationIndex_ > RowVectorType Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_temp protected
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::init().
m_usePrescribedThreshold
template<typename MatrixType_ , typename PermutationIndex_ > bool Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_usePrescribedThreshold protected
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::init(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::setThreshold(), and Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::threshold().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
ColPivHouseholderQR.h