MercuryDPM: geom_obj_with_boundary.cc File Reference
geom_obj_with_boundary.cc File Reference
#include <fenv.h>
#include "generic.h"
Functions
int main (int argc, char *argv[])
Driver.
Function Documentation
main()
int main (int argc , char * argv[])
Driver.
 {
  // Warped disk with specified amplitude and wavenumber for warping
  double epsilon=0.1;
  unsigned n=5;
  WarpedCircularDisk* disk_pt=new WarpedCircularDisk(epsilon,n);
  Vector<double> r(3);
  Vector<double> zeta(2);
  ofstream disk_file;
  disk_file.open("disk.dat");
  unsigned nr=50;
  unsigned nphi=300;
  disk_file << "ZONE I=" << nphi << ", J=" << nr << std::endl;
  for (unsigned i=0;i<nr;i++)
   {
    double radius=double(i)/double(nr-1);
    for (unsigned j=0;j<nphi;j++)
     {
      double phi=double(j)/double(nphi-1)*2.0*MathematicalConstants::Pi;
      zeta[0]=radius*cos(phi);
      zeta[1]=radius*sin(phi);
      disk_pt->position(zeta,r);
      disk_file << r[0] << " "
                << r[1] << " "
                << r[2] << " "
                << zeta[0] <<" "
                << zeta[1] <<" "
                << std::endl;
     }
   }
  disk_file.close();
  ofstream two_d_boundaries_file("two_d_boundaries.dat");
  ofstream three_d_boundaries_file("three_d_boundaries.dat");
  ofstream boundaries_tangent_file("boundaries_tangent.dat");
  ofstream boundaries_normal_file("boundaries_normal.dat");
  ofstream boundaries_binormal_file("boundaries_binormal.dat");
  unsigned nplot=100;
  disk_pt->output_boundaries_and_triads(nplot,
                                        two_d_boundaries_file,
                                        three_d_boundaries_file,
                                        boundaries_tangent_file,
                                        boundaries_normal_file,
                                        boundaries_binormal_file);
  two_d_boundaries_file.close();
  three_d_boundaries_file.close();
  boundaries_tangent_file.close();
  boundaries_normal_file.close();
  boundaries_binormal_file.close();
 }
References cos(), oomph::SarahBL::epsilon, i, j, n, oomph::DiskLikeGeomObjectWithBoundaries::output_boundaries_and_triads(), BiharmonicTestFunctions2::Pi, oomph::WarpedCircularDisk::position(), UniformPSDSelfTest::r, UniformPSDSelfTest::radius, sin(), and Eigen::zeta().