MercuryDPM: oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement Class Reference
oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement Class Reference
#include <refineable_linearised_axisym_navier_stokes_elements.h>
Public Member Functions
RefineableLinearisedAxisymmetricQCrouzeixRaviartElement ()
Constructor:
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: 6 (velocities)
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: Reconstruct pressure from the (merged) sons.
unsigned nrecovery_order ()
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
void further_setup_hanging_nodes ()
void further_build ()
RefineableLinearisedAxisymmetricQCrouzeixRaviartElement ()
Constructor.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: 6 (velocities)
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: Reconstruct pressure from the (merged) sons.
unsigned nrecovery_order ()
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
void further_setup_hanging_nodes ()
void further_build ()
Public Member Functions inherited from oomph::LinearisedAxisymmetricQCrouzeixRaviartElement
LinearisedAxisymmetricQCrouzeixRaviartElement ()
virtual unsigned required_nvalue (const unsigned &n) const
Return number of values (pinned or dofs) required at local node n.
double p_linearised_axi_nst (const unsigned &i_internal, const unsigned &i) const
unsigned npres_linearised_axi_nst () const
void fix_pressure (const unsigned &p_dof, const double &pvalue)
int p_local_eqn (const unsigned &n, const unsigned &i)
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
LinearisedAxisymmetricQCrouzeixRaviartElement ()
virtual unsigned required_nvalue (const unsigned &n) const
Return number of values (pinned or dofs) required at local node n.
double p_lin_axi_nst (const unsigned &i_internal, const unsigned &i) const
unsigned npres_lin_axi_nst () const
void fix_pressure (const unsigned &p_dof, const double &pvalue)
void fix_cosine_component_of_pressure (const unsigned &p_dof, const double &pvalue)
void fix_sine_component_of_pressure (const unsigned &p_dof, const double &pvalue)
int p_local_eqn (const unsigned &n, const unsigned &i)
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
unsigned ndof_types () const
LinearisedAxisymmetricQCrouzeixRaviartElement ()
virtual unsigned required_nvalue (const unsigned &n) const
Return number of values (pinned or dofs) required at local node n.
double p_linearised_axi_nst (const unsigned &i_internal, const unsigned &i) const
unsigned npres_linearised_axi_nst () const
void fix_pressure (const unsigned &p_dof, const double &pvalue)
int p_local_eqn (const unsigned &n, const unsigned &i)
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
unsigned ndof_types () const
Public Member Functions inherited from oomph::LinearisedAxisymmetricNavierStokesEquations
LinearisedAxisymmetricNavierStokesEquations ()
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
const int & azimuthal_mode_number () const
Azimuthal mode number k in e^ik(theta) decomposition.
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
int *& azimuthal_mode_number_pt ()
Pointer to azimuthal mode number k in e^ik(theta) decomposition.
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to the viscosity ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to the density ratio.
virtual unsigned u_index_linearised_axi_nst (const unsigned &i) const
double du_dt_linearised_axi_nst (const unsigned &n, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
virtual int p_index_linearised_axi_nst (const unsigned &i) const
Which nodal value represents the pressure?
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
double interpolated_u_linearised_axi_nst (const Vector< double > &s, const unsigned &i) const
double interpolated_p_linearised_axi_nst (const Vector< double > &s, const unsigned &i) const
virtual void get_base_flow_u (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result) const
LinearisedAxisymmetricNavierStokesEquations ()
const double & re () const
Reynolds number.
double *& re_pt ()
Pointer to Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const double & re_invro () const
Global Reynolds number multiplied by inverse Rossby number.
double *& re_invro_pt ()
Pointer to global Reynolds number multiplied by inverse Rossby number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
const int & azimuthal_mode_number () const
Azimuthal mode number k in e^ik(theta) decomposition.
int *& azimuthal_mode_number_pt ()
Pointer to azimuthal mode number k in e^ik(theta) decomposition.
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to the viscosity ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to the density ratio.
virtual int get_local_eqn_number_corresponding_to_geometric_dofs (const unsigned &n, const unsigned &i)=0
virtual unsigned xhat_index_lin_axi_nst (const unsigned &i) const
virtual unsigned u_index_lin_axi_nst (const unsigned &i) const
double du_dt_lin_axi_nst (const unsigned &n, const unsigned &i) const
double dnodal_position_perturbation_dt_lin_axi_nst (const unsigned &n, const unsigned &i) const
unsigned nexternal_H_data ()
Return the number of external perturbed spine "heights" data.
void disable_ALE ()
void enable_ALE ()
virtual int p_index_lin_axi_nst (const unsigned &i) const
Which nodal value represents the pressure?
void dkin_energy_dt (double &dkin_en_dt, double &kin_en) const
Get integral of kinetic energy over element plus deriv w.r.t. time.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
double interpolated_u_lin_axi_nst (const Vector< double > &s, const unsigned &i) const
double interpolated_p_lin_axi_nst (const Vector< double > &s, const unsigned &i) const
double interpolated_nodal_position_perturbation_lin_axi_nst (const Vector< double > &s, const unsigned &i) const
void assign_additional_local_eqn_numbers ()
Define the local equation numbering schemes.
LinearisedAxisymmetricNavierStokesEquations ()
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
const int & azimuthal_mode_number () const
Azimuthal mode number k in e^ik(theta) decomposition.
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
int *& azimuthal_mode_number_pt ()
Pointer to azimuthal mode number k in e^ik(theta) decomposition.
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to the viscosity ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to the density ratio.
virtual unsigned u_index_linearised_axi_nst (const unsigned &i) const
double du_dt_linearised_axi_nst (const unsigned &n, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
virtual int p_index_linearised_axi_nst (const unsigned &i) const
Which nodal value represents the pressure?
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
double interpolated_u_linearised_axi_nst (const Vector< double > &s, const unsigned &i) const
double interpolated_p_linearised_axi_nst (const Vector< double > &s, const unsigned &i) const
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::RefineableLinearisedAxisymmetricNavierStokesEquations
RefineableLinearisedAxisymmetricNavierStokesEquations ()
Empty Constructor.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
double geometric_jacobian (const Vector< double > &x)
Fill in the geometric Jacobian, which in this case is r.
RefineableLinearisedAxisymmetricNavierStokesEquations ()
Empty Constructor.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
double geometric_jacobian (const Vector< double > &x)
Fill in the geometric Jacobian, which in this case is r.
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void unbuild ()
virtual void deactivate_element ()
virtual bool nodes_built ()
Return true if all the nodes have been built, false if not.
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual Node * interpolating_node_pt (const unsigned &n, const int &value_id)
virtual double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
virtual Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
virtual unsigned ninterpolating_node (const int &value_id)
virtual unsigned ninterpolating_node_1d (const int &value_id)
virtual void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual RefineableElement * root_element_pt ()
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
virtual void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
virtual void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
Pre-build the element.
void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
unsigned nshape_controlling_nodes ()
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Public Member Functions inherited from oomph::ElementWithZ2ErrorEstimator
ElementWithZ2ErrorEstimator ()
Default empty constructor.
ElementWithZ2ErrorEstimator (const ElementWithZ2ErrorEstimator &)=delete
Broken copy constructor.
void operator= (const ElementWithZ2ErrorEstimator &)=delete
Broken assignment operator.
virtual unsigned ncompound_fluxes ()
virtual void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
virtual void get_Z2_compound_flux_indices (Vector< unsigned > &flux_index)
Public Member Functions inherited from oomph::RefineableQElement< 2 >
RefineableQElement ()
Constructor: Pass refinement level (default 0 = root)
RefineableQElement (const RefineableQElement< 2 > &dummy)=delete
Broken copy constructor.
virtual ~RefineableQElement ()
Broken assignment operator.
unsigned required_nsons () const
A refineable quad element has four sons.
virtual Node * node_created_by_neighbour (const Vector< double > &s_fraction, bool &is_periodic)
virtual Node * node_created_by_son_of_neighbour (const Vector< double > &s_fraction, bool &is_periodic)
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)
void check_integrity (double &max_error)
void output_corners (std::ostream &outfile, const std::string &colour) const
Print corner nodes, use colour.
QuadTree * quadtree_pt ()
Pointer to quadtree representation of this element.
QuadTree * quadtree_pt () const
Pointer to quadtree representation of this element.
void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
void get_boundaries (const int &edge, std::set< unsigned > &boundaries) const
void get_bcs (int bound, Vector< int > &bound_cons) const
void interpolated_zeta_on_edge (const unsigned &boundary, const int &edge, const Vector< double > &s, Vector< double > &zeta)
Public Member Functions inherited from oomph::QuadElementBase
QuadElementBase ()
Constructor. Empty.
Public Member Functions inherited from oomph::QElementBase
QElementBase ()
Constructor: Initialise pointers to macro element reference coords.
QElementBase (const QElementBase &)=delete
Broken copy constructor.
virtual ~QElementBase ()
Broken assignment operator.
bool local_coord_is_valid (const Vector< double > &s)
Check whether the local coordinate are valid or not.
void move_local_coord_back_into_element (Vector< double > &s) const
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
double & s_macro_ll (const unsigned &i)
double & s_macro_ur (const unsigned &i)
double s_macro_ll (const unsigned &i) const
double s_macro_ur (const unsigned &i) const
void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
unsigned nnode_on_face () const
ElementGeometry::ElementGeometry element_geometry () const
It's a Q element!
Public Member Functions inherited from oomph::QElementGeometricBase
QElementGeometricBase ()
Empty default constructor.
QElementGeometricBase (const QElementGeometricBase &)=delete
Broken copy constructor.
Private Member Functions
void unpin_elemental_pressure_dofs ()
Unpin all the internal pressure freedoms.
void unpin_elemental_pressure_dofs ()
Unpin all the internal pressure freedoms.
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Types inherited from oomph::RefineableQElement< 2 >
typedef void(RefineableQElement< 2 >::* VoidMemberFctPt) ()
Static Public Member Functions inherited from oomph::RefineableLinearisedAxisymmetricNavierStokesEquations
static void pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > &element_pt)
static void unpin_all_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in Vector.
static void pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > &element_pt)
static void unpin_all_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in Vector.
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Public Attributes inherited from oomph::LinearisedAxisymmetricNavierStokesEquations
void(*&)(const double &time, const Vector< double > &x, Vector< double > &f) base_flow_u_fct_pt ()
Access function for the base flow solution pointer.
void(*&)(const double &time, const Vector< double > &x, DenseMatrix< double > &f) base_flow_dudx_fct_pt ()
void(*&)(const double &time, const Vector< double > &x, Vector< double > &f) base_flow_dudt_fct_pt ()
void(*&)(const double &time, const Vector< double > &x, double &f) base_flow_p_fct_pt ()
Access function for the base flow pressure pointer.
void(*&)(const double &time, const Vector< double > &x, RankFourTensor< double > &f) base_flow_d_dudx_dX_fct_pt ()
void(*&)(const double &time, const Vector< double > &x, Vector< double > &f) body_force_fct_pt ()
Access function for the body-force pointer.
double(*&)(const double &time, const Vector< double > &x) source_fct_pt ()
Access function for the source-function pointer.
void(*&)(const double &time, const Vector< double > &x, DenseMatrix< double > &f) base_flow_duds_fct_pt ()
Static Public Attributes inherited from oomph::LinearisedAxisymmetricNavierStokesEquations
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions inherited from oomph::LinearisedAxisymmetricQCrouzeixRaviartElement
double dshape_and_dtest_eulerian_linearised_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_linearised_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
void pshape_linearised_axi_nst (const Vector< double > &s, Shape &psi) const
Compute the pressure shape functions at local coordinate s.
void pshape_linearised_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Compute the pressure shape and test functions at local coordinate s.
double dshape_and_dtest_eulerian_lin_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_lin_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_and_dnodal_coordinates_at_knot_lin_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
void pshape_lin_axi_nst (const Vector< double > &s, Shape &psi) const
Compute the pressure shape functions at local coordinate s.
void pshape_lin_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Compute the pressure shape and test functions at local coordinate s.
double dshape_and_dtest_eulerian_linearised_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_linearised_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
void pshape_linearised_axi_nst (const Vector< double > &s, Shape &psi) const
Compute the pressure shape functions at local coordinate s.
void pshape_linearised_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Compute the pressure shape and test functions at local coordinate s.
Protected Member Functions inherited from oomph::LinearisedAxisymmetricNavierStokesEquations
virtual void get_base_flow_u (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result) const
virtual void get_base_flow_dudx (const double &time, const unsigned &ipt, const Vector< double > &x, DenseMatrix< double > &result) const
virtual void get_base_flow_dudx (const double &time, const unsigned &ipt, const Vector< double > &x, DenseMatrix< double > &result) const
virtual void get_base_flow_dudt (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result) const
virtual void get_base_flow_p (const double &time, const unsigned &ipt, const Vector< double > &x, double &result) const
virtual void get_base_flow_d_dudx_dX (const double &time, const unsigned &ipt, const Vector< double > &x, RankFourTensor< double > &result) const
void get_body_force_base_flow (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result)
double get_source_base_flow (const double &time, const unsigned &ipt, const Vector< double > &x)
void get_body_force_gradient_base_flow (const double &time, const unsigned &ipt, const Vector< double > &x, DenseMatrix< double > &result)
void get_source_gradient_base_flow (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result)
virtual void get_base_flow_duds (const double &time, const unsigned &ipt, const Vector< double > &x, DenseMatrix< double > &result) const
virtual void fill_in_generic_residual_contribution_lin_axi_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
virtual void get_base_flow_u (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result) const
virtual void get_base_flow_dudx (const double &time, const unsigned &ipt, const Vector< double > &x, DenseMatrix< double > &result) const
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::RefineableLinearisedAxisymmetricNavierStokesEquations
virtual Node * pressure_node_pt (const unsigned &n_p)
virtual void pin_elemental_redundant_nodal_pressure_dofs ()
virtual Node * pressure_node_pt (const unsigned &n_p)
virtual void pin_elemental_redundant_nodal_pressure_dofs ()
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Protected Member Functions inherited from oomph::RefineableQElement< 2 >
void setup_father_bounds ()
void get_edge_bcs (const int &edge, Vector< int > &bound_cons) const
Determine Vector of boundary conditions along edge (N/S/W/E)
void setup_hang_for_value (const int &value_id)
virtual void quad_hang_helper (const int &value_id, const int &my_edge, std::ofstream &output_hangfile)
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Protected Attributes inherited from oomph::LinearisedAxisymmetricQCrouzeixRaviartElement
Vector< unsigned > P_linearised_axi_nst_internal_index
Vector< unsigned > P_lin_axi_nst_internal_index
Protected Attributes inherited from oomph::LinearisedAxisymmetricNavierStokesEquations
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
int * Azimuthal_Mode_Number_pt
Pointer to azimuthal mode number k in e^ik(theta) decomposition.
void(* Base_flow_u_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
Pointer to base flow solution (velocity components) function.
void(* Base_flow_dudx_fct_pt)(const double &time, const Vector< double > &x, DenseMatrix< double > &result)
bool ALE_is_disabled
double * ReInvFr_pt
double * ReInvRo_pt
Vector< double > * G_pt
Pointer to global gravity Vector.
void(* Base_flow_dudt_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
void(* Base_flow_p_fct_pt)(const double &time, const Vector< double > &x, double &result)
Pointer to base flow solution (pressure) function.
void(* Base_flow_d_dudx_dX_fct_pt)(const double &time, const Vector< double > &x, RankFourTensor< double > &result)
void(* Body_force_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
Pointer to (base flow) body force function.
double(* Source_fct_pt)(const double &time, const Vector< double > &x)
Pointer to (base flow) volumetric source function.
void(* Base_flow_duds_fct_pt)(const double &time, const Vector< double > &x, DenseMatrix< double > &result)
Vector< int > External_H_local_eqn
Vector< unsigned > External_node
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number – for plotting/validation purposes.
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Static Protected Attributes inherited from oomph::RefineableQElement< 2 >
static std::map< unsigned, DenseMatrix< int > > Father_bound
Detailed Description
/////////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////// Refineable version of linearised axisymmetric quad Crouzeix Raviart elements (note that unlike the cartesian version this is not scale-able to higher dimensions!)
/////////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////// Refineable version of linearised axisymmetric quadratic Crouzeix-Raviart elements
Constructor & Destructor Documentation
RefineableLinearisedAxisymmetricQCrouzeixRaviartElement() [1/2]
oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement () inline
Constructor:
                                                            :
   RefineableElement(),
   RefineableLinearisedAxisymmetricNavierStokesEquations(),
   RefineableQElement<2>(),
   LinearisedAxisymmetricQCrouzeixRaviartElement() {}
RefineableLinearisedAxisymmetricQCrouzeixRaviartElement() [2/2]
oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement () inline
Constructor.
       : RefineableElement(),
         RefineableLinearisedAxisymmetricNavierStokesEquations(),
         RefineableQElement<2>(),
         LinearisedAxisymmetricQCrouzeixRaviartElement()
     {
     }
Member Function Documentation
further_build() [1/2]
void oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::further_build () inline virtual
Further build for Crouzeix_Raviart interpolates the internal pressure dofs from father element: Make sure pressure values and dp/ds agree between fathers and sons at the midpoints of the son elements.
Reimplemented from oomph::RefineableLinearisedAxisymmetricNavierStokesEquations.
   {
    // Call the generic further build
    RefineableLinearisedAxisymmetricNavierStokesEquations::further_build();
    using namespace QuadTreeNames;
    // What type of son am I? Ask my quadtree representation...
    int son_type=quadtree_pt()->son_type();
    // Pointer to my father (in element impersonation)
    RefineableElement* father_el_pt=
     quadtree_pt()->father_pt()->object_pt();
    Vector<double> s_father(2);
    // Son midpoint is located at the following coordinates in father element:
    // South west son
    if(son_type==SW)
     {
      s_father[0]=-0.5;
      s_father[1]=-0.5;
     }
    // South east son
    else if(son_type==SE)
     {
      s_father[0]= 0.5;
      s_father[1]=-0.5;
     }
    // North east son
    else if(son_type==NE)
     {
      s_father[0]=0.5;
      s_father[1]=0.5;
     }
    // North west son
    else if(son_type==NW)
     {
      s_father[0]=-0.5;
      s_father[1]= 0.5;
     }
    // Pressure values in father element
    // ---------------------------------
    // Find pointer to father element
    RefineableLinearisedAxisymmetricQCrouzeixRaviartElement* cast_father_el_pt=
     dynamic_cast<RefineableLinearisedAxisymmetricQCrouzeixRaviartElement*>
     (father_el_pt);
    // Set up storage for pressure in father element
    Vector<double> press(2,0.0);
    // Loop over pressure components
    for(unsigned i=0;i<2;i++)
     {
      // Get pressure from father element
      press[i]
       = cast_father_el_pt->interpolated_p_linearised_axi_nst(s_father,i);
      // Pressure value gets copied straight into internal dof:
      internal_data_pt(P_linearised_axi_nst_internal_index[i])->
       set_value(0,press[i]);
      // The slopes get copied from father
      internal_data_pt(P_linearised_axi_nst_internal_index[i])->
       set_value(1,0.5*cast_father_el_pt
                 ->internal_data_pt(P_linearised_axi_nst_internal_index[i])
                 ->value(1));
      internal_data_pt(P_linearised_axi_nst_internal_index[i])->
       set_value(2,0.5*cast_father_el_pt
                 ->internal_data_pt(P_linearised_axi_nst_internal_index[i])
                 ->value(2));
     } // End of loop over pressure components
   }
References oomph::Tree::father_pt(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build(), i, oomph::GeneralisedElement::internal_data_pt(), oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_p_linearised_axi_nst(), oomph::QuadTreeNames::NE, oomph::QuadTreeNames::NW, oomph::Tree::object_pt(), oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::P_linearised_axi_nst_internal_index, oomph::RefineableQElement< 2 >::quadtree_pt(), oomph::QuadTreeNames::SE, oomph::Tree::son_type(), oomph::QuadTreeNames::SW, and Eigen::value.
further_build() [2/2]
void oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::further_build () inline virtual
Further build for Crouzeix_Raviart interpolates the internal pressure dofs from father element: Make sure pressure values and dp/ds agree between fathers and sons at the midpoints of the son elements.
Reimplemented from oomph::RefineableLinearisedAxisymmetricNavierStokesEquations.
     {
       // Call the generic further build
       RefineableLinearisedAxisymmetricNavierStokesEquations::further_build();
       using namespace QuadTreeNames;
       // What type of son am I? Ask my quadtree representation...
       int son_type = quadtree_pt()->son_type();
       // Pointer to my father (in element impersonation)
       RefineableElement* father_el_pt = quadtree_pt()->father_pt()->object_pt();
       Vector<double> s_father(2);
       // Son midpoint is located at the following coordinates in father element:
       // South west son
       if (son_type == SW)
       {
         s_father[0] = -0.5;
         s_father[1] = -0.5;
       }
       // South east son
       else if (son_type == SE)
       {
         s_father[0] = 0.5;
         s_father[1] = -0.5;
       }
       // North east son
       else if (son_type == NE)
       {
         s_father[0] = 0.5;
         s_father[1] = 0.5;
       }
       // North west son
       else if (son_type == NW)
       {
         s_father[0] = -0.5;
         s_father[1] = 0.5;
       }
       // Pressure values in father element
       // ---------------------------------
       // Find pointer to father element
       RefineableLinearisedAxisymmetricQCrouzeixRaviartElement*
         cast_father_el_pt = dynamic_cast<
           RefineableLinearisedAxisymmetricQCrouzeixRaviartElement*>(
           father_el_pt);
       // Set up storage for pressure in father element
       Vector<double> press(2, 0.0);
       // Loop over pressure components
       for (unsigned i = 0; i < 2; i++)
       {
         // Get pressure from father element
         press[i] =
           cast_father_el_pt->interpolated_p_linearised_axi_nst(s_father, i);
         // Pressure value gets copied straight into internal dof:
         internal_data_pt(P_linearised_axi_nst_internal_index[i])
           ->set_value(0, press[i]);
         // The slopes get copied from father
         internal_data_pt(P_linearised_axi_nst_internal_index[i])
           ->set_value(
             1,
             0.5 * cast_father_el_pt
                     ->internal_data_pt(P_linearised_axi_nst_internal_index[i])
                     ->value(1));
         internal_data_pt(P_linearised_axi_nst_internal_index[i])
           ->set_value(
             2,
             0.5 * cast_father_el_pt
                     ->internal_data_pt(P_linearised_axi_nst_internal_index[i])
                     ->value(2));
       } // End of loop over pressure components
     }
References oomph::Tree::father_pt(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build(), i, oomph::GeneralisedElement::internal_data_pt(), oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_p_linearised_axi_nst(), oomph::QuadTreeNames::NE, oomph::QuadTreeNames::NW, oomph::Tree::object_pt(), oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::P_linearised_axi_nst_internal_index, oomph::RefineableQElement< 2 >::quadtree_pt(), oomph::QuadTreeNames::SE, oomph::Data::set_value(), oomph::Tree::son_type(), oomph::QuadTreeNames::SW, and Eigen::value.
further_setup_hanging_nodes() [1/2]
void oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::further_setup_hanging_nodes () inline virtual
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty
Implements oomph::RefineableQElement< 2 >.
 {}
further_setup_hanging_nodes() [2/2]
void oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::further_setup_hanging_nodes () inline virtual
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty
Implements oomph::RefineableQElement< 2 >.
 {}
get_interpolated_values() [1/4]
void oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) inline virtual
Get all function values [U^C,U^S,...,P^S] at previous timestep t (t=0: present; t>0: previous timestep).
Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Note: No pressure history is kept, so pressure is always the current value.
Implements oomph::RefineableElement.
  {
   const unsigned DIM=3;
   // Set size of Vector: U^C, U^S, W^C, W^S, V^C, V^S
   values.resize(2*DIM);
   // Initialise to zero
   for(unsigned i=0;i<2*DIM;i++) { values[i]=0.0; }
   // Determine number of nodes in element
   const unsigned n_node = nnode();
   // Shape functions
   Shape psif(n_node);
   shape(s,psif);
   //Calculate velocities: values[0],...
   for(unsigned i=0;i<(2*DIM);i++)
    {
     // Get the local index at which the i-th velocity is stored
     const unsigned u_local_index = u_index_linearised_axi_nst(i);
     for(unsigned l=0;l<n_node;l++)
      {
       values[i] += nodal_value(t,l,u_local_index)*psif[l];
      }
    }
  }
References DIM, i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), plotPSD::t, and oomph::LinearisedAxisymmetricNavierStokesEquations::u_index_linearised_axi_nst().
get_interpolated_values() [2/4]
void oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) inline virtual
Get all function values [U^C,U^S,...,P^S] at previous timestep t (t=0: present; t>0: previous timestep).
Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Note: No pressure history is kept, so pressure is always the current value.
Implements oomph::RefineableElement.
     {
       const unsigned DIM = 3;
       // Set size of Vector: U^C, U^S, W^C, W^S, V^C, V^S
       values.resize(2 * DIM);
       // Initialise to zero
       for (unsigned i = 0; i < 2 * DIM; i++)
       {
         values[i] = 0.0;
       }
       // Determine number of nodes in element
       const unsigned n_node = nnode();
       // Shape functions
       Shape psif(n_node);
       shape(s, psif);
       // Calculate velocities: values[0],...
       for (unsigned i = 0; i < (2 * DIM); i++)
       {
         // Get the local index at which the i-th velocity is stored
         const unsigned u_local_index = u_index_linearised_axi_nst(i);
         for (unsigned l = 0; l < n_node; l++)
         {
           values[i] += nodal_value(t, l, u_local_index) * psif[l];
         }
       }
     }
References DIM, i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), plotPSD::t, and oomph::LinearisedAxisymmetricNavierStokesEquations::u_index_linearised_axi_nst().
get_interpolated_values() [3/4]
void oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::get_interpolated_values (const Vector< double > & s, Vector< double > & values) inline virtual
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
   {
   // Set the velocity dimension of the element
    const unsigned DIM=3;
    // Determine size of values Vector: U^C, U^S, W^C, W^S, V^C, V^S
    const unsigned n_values = 2*DIM;
    // Set size of values Vector and initialise to zero
    values.resize(n_values,0.0);
    // Calculate velocities: values[0],...
    for(unsigned i=0;i<n_values;i++)
     {
      values[i] = interpolated_u_linearised_axi_nst(s,i);
     }
   }
References DIM, i, oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_u_linearised_axi_nst(), and s.
get_interpolated_values() [4/4]
void oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::get_interpolated_values (const Vector< double > & s, Vector< double > & values) inline virtual
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
     {
       // Set the velocity dimension of the element
       const unsigned DIM = 3;
       // Determine size of values Vector: U^C, U^S, W^C, W^S, V^C, V^S
       const unsigned n_values = 2 * DIM;
       // Set size of values Vector and initialise to zero
       values.resize(n_values, 0.0);
       // Calculate velocities: values[0],...
       for (unsigned i = 0; i < n_values; i++)
       {
         values[i] = interpolated_u_linearised_axi_nst(s, i);
       }
     }
References DIM, i, oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_u_linearised_axi_nst(), and s.
ncont_interpolated_values() [1/2]
unsigned oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::ncont_interpolated_values () const inline virtual
Number of continuously interpolated values: 6 (velocities)
Implements oomph::RefineableElement.
 { return 6; }
ncont_interpolated_values() [2/2]
unsigned oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::ncont_interpolated_values () const inline virtual
Number of continuously interpolated values: 6 (velocities)
Implements oomph::RefineableElement.
     {
       return 6;
     }
nrecovery_order() [1/2]
unsigned oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::nrecovery_order () inline virtual
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
   {
    return 2;
   }
nrecovery_order() [2/2]
unsigned oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::nrecovery_order () inline virtual
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       return 2;
     }
nvertex_node() [1/2]
unsigned oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::nvertex_node () const inline virtual
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
  { return LinearisedAxisymmetricQCrouzeixRaviartElement::nvertex_node(); }
References oomph::FiniteElement::nvertex_node().
nvertex_node() [2/2]
unsigned oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::nvertex_node () const inline virtual
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       return LinearisedAxisymmetricQCrouzeixRaviartElement::nvertex_node();
     }
References oomph::FiniteElement::nvertex_node().
rebuild_from_sons() [1/2]
void oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::rebuild_from_sons (Mesh *& mesh_pt) inline virtual
Rebuild from sons: Reconstruct pressure from the (merged) sons.
Implements oomph::RefineableElement.
   {
    using namespace QuadTreeNames;
    // Central pressure value:
    // -----------------------
    // Use average of the sons central pressure values
    // Other options: Take average of the four (discontinuous)
    // pressure values at the father's midpoint]
    Vector<double> av_press(2,0.0);
    // Loop over the sons
    for(unsigned ison=0;ison<4;ison++)
     {
      // Loop over the two pressure components
      for(unsigned i=0;i<2;i++)
       {
        // Add the sons midnode pressure
        av_press[i] += quadtree_pt()->son_pt(ison)->object_pt()->
         internal_data_pt(P_linearised_axi_nst_internal_index[i])->value(0);
       }
     }
    // Use the average
    for(unsigned i=0;i<2;i++)
     {
      internal_data_pt(P_linearised_axi_nst_internal_index[i])
       ->set_value(0,0.25*av_press[i]);
     }
    Vector<double> slope1(2,0.0), slope2(2,0.0);
    // Loop over pressure components
    for(unsigned i=0;i<2;i++)
     {
      // Slope in s_0 direction
      // ----------------------
      // Use average of the 2 FD approximations based on the
      // elements central pressure values
      // [Other options: Take average of the four
      // pressure derivatives]
      slope1[i] = quadtree_pt()->son_pt(SE)->object_pt()->
       internal_data_pt(P_linearised_axi_nst_internal_index[i])->value(0) -
       quadtree_pt()->son_pt(SW)->object_pt()->
       internal_data_pt(P_linearised_axi_nst_internal_index[i])->value(0);
      slope2[i] = quadtree_pt()->son_pt(NE)->object_pt()->
       internal_data_pt(P_linearised_axi_nst_internal_index[i])->value(0) -
       quadtree_pt()->son_pt(NW)->object_pt()->
       internal_data_pt(P_linearised_axi_nst_internal_index[i])->value(0);
      // Use the average
      internal_data_pt(P_linearised_axi_nst_internal_index[i])->
       set_value(1,0.5*(slope1[i]+slope2[i]));
      // Slope in s_1 direction
      // ----------------------
      // Use average of the 2 FD approximations based on the
      // elements central pressure values
      // [Other options: Take average of the four
      // pressure derivatives]
      slope1[i] = quadtree_pt()->son_pt(NE)->object_pt()->
       internal_data_pt(P_linearised_axi_nst_internal_index[i])->value(0) -
       quadtree_pt()->son_pt(SE)->object_pt()->
       internal_data_pt(P_linearised_axi_nst_internal_index[i])->value(0);
      slope2[i] = quadtree_pt()->son_pt(NW)->object_pt()->
       internal_data_pt(P_linearised_axi_nst_internal_index[i])->value(0) -
       quadtree_pt()->son_pt(SW)->object_pt()->
       internal_data_pt(P_linearised_axi_nst_internal_index[i])->value(0);
      // Use the average
      internal_data_pt(P_linearised_axi_nst_internal_index[i])->
       set_value(2,0.5*(slope1[i]+slope2[i]));
     } // End of loop over pressure components
   }
References i, oomph::GeneralisedElement::internal_data_pt(), oomph::QuadTreeNames::NE, oomph::QuadTreeNames::NW, oomph::Tree::object_pt(), oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::P_linearised_axi_nst_internal_index, oomph::RefineableQElement< 2 >::quadtree_pt(), oomph::QuadTreeNames::SE, oomph::Data::set_value(), oomph::Tree::son_pt(), oomph::QuadTreeNames::SW, and oomph::Data::value().
rebuild_from_sons() [2/2]
void oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::rebuild_from_sons (Mesh *& mesh_pt) inline virtual
Rebuild from sons: Reconstruct pressure from the (merged) sons.
Implements oomph::RefineableElement.
     {
       using namespace QuadTreeNames;
       // Central pressure value:
       // -----------------------
       // Use average of the sons central pressure values
       // Other options: Take average of the four (discontinuous)
       // pressure values at the father's midpoint]
       Vector<double> av_press(2, 0.0);
       // Loop over the sons
       for (unsigned ison = 0; ison < 4; ison++)
       {
         // Loop over the two pressure components
         for (unsigned i = 0; i < 2; i++)
         {
           // Add the sons midnode pressure
           av_press[i] +=
             quadtree_pt()
               ->son_pt(ison)
               ->object_pt()
               ->internal_data_pt(P_linearised_axi_nst_internal_index[i])
               ->value(0);
         }
       }
       // Use the average
       for (unsigned i = 0; i < 2; i++)
       {
         internal_data_pt(P_linearised_axi_nst_internal_index[i])
           ->set_value(0, 0.25 * av_press[i]);
       }
       Vector<double> slope1(2, 0.0), slope2(2, 0.0);
       // Loop over pressure components
       for (unsigned i = 0; i < 2; i++)
       {
         // Slope in s_0 direction
         // ----------------------
         // Use average of the 2 FD approximations based on the
         // elements central pressure values
         // [Other options: Take average of the four
         // pressure derivatives]
         slope1[i] = quadtree_pt()
                       ->son_pt(SE)
                       ->object_pt()
                       ->internal_data_pt(P_linearised_axi_nst_internal_index[i])
                       ->value(0) -
                     quadtree_pt()
                       ->son_pt(SW)
                       ->object_pt()
                       ->internal_data_pt(P_linearised_axi_nst_internal_index[i])
                       ->value(0);
         slope2[i] = quadtree_pt()
                       ->son_pt(NE)
                       ->object_pt()
                       ->internal_data_pt(P_linearised_axi_nst_internal_index[i])
                       ->value(0) -
                     quadtree_pt()
                       ->son_pt(NW)
                       ->object_pt()
                       ->internal_data_pt(P_linearised_axi_nst_internal_index[i])
                       ->value(0);
         // Use the average
         internal_data_pt(P_linearised_axi_nst_internal_index[i])
           ->set_value(1, 0.5 * (slope1[i] + slope2[i]));
         // Slope in s_1 direction
         // ----------------------
         // Use average of the 2 FD approximations based on the
         // elements central pressure values
         // [Other options: Take average of the four
         // pressure derivatives]
         slope1[i] = quadtree_pt()
                       ->son_pt(NE)
                       ->object_pt()
                       ->internal_data_pt(P_linearised_axi_nst_internal_index[i])
                       ->value(0) -
                     quadtree_pt()
                       ->son_pt(SE)
                       ->object_pt()
                       ->internal_data_pt(P_linearised_axi_nst_internal_index[i])
                       ->value(0);
         slope2[i] = quadtree_pt()
                       ->son_pt(NW)
                       ->object_pt()
                       ->internal_data_pt(P_linearised_axi_nst_internal_index[i])
                       ->value(0) -
                     quadtree_pt()
                       ->son_pt(SW)
                       ->object_pt()
                       ->internal_data_pt(P_linearised_axi_nst_internal_index[i])
                       ->value(0);
         // Use the average
         internal_data_pt(P_linearised_axi_nst_internal_index[i])
           ->set_value(2, 0.5 * (slope1[i] + slope2[i]));
       } // End of loop over pressure components
     }
References i, oomph::GeneralisedElement::internal_data_pt(), oomph::QuadTreeNames::NE, oomph::QuadTreeNames::NW, oomph::Tree::object_pt(), oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::P_linearised_axi_nst_internal_index, oomph::RefineableQElement< 2 >::quadtree_pt(), oomph::QuadTreeNames::SE, oomph::Data::set_value(), oomph::Tree::son_pt(), oomph::QuadTreeNames::SW, and oomph::Data::value().
unpin_elemental_pressure_dofs() [1/2]
void oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::unpin_elemental_pressure_dofs () inline private virtual
Unpin all the internal pressure freedoms.
Implements oomph::RefineableLinearisedAxisymmetricNavierStokesEquations.
  {
   const unsigned n_pres = this->npres_linearised_axi_nst();
   // Loop over pressure dofs and unpin
   for(unsigned l=0;l<n_pres;l++)
    {
     // There are two pressure components
     for(unsigned i=0;i<2;i++)
      {
       this->internal_data_pt(P_linearised_axi_nst_internal_index[i])->unpin(l);
      }
    }
  }
References i, oomph::GeneralisedElement::internal_data_pt(), oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::npres_linearised_axi_nst(), oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::P_linearised_axi_nst_internal_index, and oomph::Data::unpin().
unpin_elemental_pressure_dofs() [2/2]
void oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::unpin_elemental_pressure_dofs () inline private virtual
Unpin all the internal pressure freedoms.
Implements oomph::RefineableLinearisedAxisymmetricNavierStokesEquations.
     {
       const unsigned n_pres = this->npres_linearised_axi_nst();
       // Loop over pressure dofs and unpin
       for (unsigned l = 0; l < n_pres; l++)
       {
         // There are two pressure components
         for (unsigned i = 0; i < 2; i++)
         {
           this->internal_data_pt(P_linearised_axi_nst_internal_index[i])
             ->unpin(l);
         }
       }
     }
References i, oomph::GeneralisedElement::internal_data_pt(), oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::npres_linearised_axi_nst(), oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::P_linearised_axi_nst_internal_index, and oomph::Data::unpin().
vertex_node_pt() [1/2]
Node* oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::vertex_node_pt (const unsigned & j) const inline virtual
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
   { return LinearisedAxisymmetricQCrouzeixRaviartElement::vertex_node_pt(j); }
References j, and oomph::FiniteElement::vertex_node_pt().
vertex_node_pt() [2/2]
Node* oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::vertex_node_pt (const unsigned & j) const inline virtual
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       return LinearisedAxisymmetricQCrouzeixRaviartElement::vertex_node_pt(j);
     }
References j, and oomph::FiniteElement::vertex_node_pt().
The documentation for this class was generated from the following file:
demo_drivers/axisym_navier_stokes/counter_rotating_disks/refineable_linearised_axisym_navier_stokes_elements.h