MercuryDPM: Opt.cpp File Reference
Opt.cpp File Reference
#include <Mercury3D.h>
#include <Species/Species.h>
#include <Species/LinearViscoelasticSpecies.h>
#include <CMakeDefinitions.h>
#include <cstdio>
#include <iostream>
#include <fstream>
#include <memory>
#include <stdexcept>
#include <string>
#include <array>
#include "Walls/InfiniteWall.h"
#include <cmath>
Classes
class SimpleOpt
Functions
std::string ExecCommand (const char *cmd)
int main (int argc, char *argv[])
Function Documentation
ExecCommand()
std::string ExecCommand (const char * cmd)
{
     std::array<char, 128> buffer;
     std::string result;
     std::unique_ptr<FILE, int(*)(FILE*)> pipe(popen(cmd, "r"), pclose);
     if (!pipe) {
         std::string ret = "Could not run an extra OS command: "; ret.append(cmd);
         throw std::runtime_error(ret);
     }
     while (fgets(buffer.data(), buffer.size(), pipe.get()) != nullptr) {
         result += buffer.data();
     }
     return result;
 }
References int(), ret, and oomph::Global_string_for_annotation::string().
Referenced by main().
main()
int main (int argc , char * argv[])
 {
     // In this simple example we optimize two angular parameters (theta and phi in a standard spherical coord system)
     // to extremize the distance the projectile travels in a given direction
     int NumParams = 2;
     // Get parameters passed through the command line
     std::vector <Mdouble> params(0);
     for (int i = 0; i<NumParams; i++) {
         std::string a;
         Mdouble param = stod(helpers::readFromCommandLine(argc, argv, "-p"+std::to_string(i), a));
         params.push_back(param);
         std::cout<<params[i]<<std::endl;
     }
     // Problem setup
     SimpleOpt problem;
     // Species
     LinearViscoelasticSpecies species;
     species.setDensity(2500.0);
     species.setStiffness(258.5);
     species.setDissipation(0.0);
     problem.speciesHandler.copyAndAddObject(species);
     // Tabletop
     problem.wallHandler.clear();
     InfiniteWall w0;
     w0.setSpecies(problem.speciesHandler.getObject(0));
     w0.set(Vec3D(0.0, 0.0, -1.0), Vec3D(0, 0, problem.getZMin()));
     problem.wallHandler.copyAndAddObject(w0);
     // Projectile
     SphericalParticle p0;
     p0.setSpecies(problem.speciesHandler.getObject(0));
     p0.setRadius(0.05); // sets particle radius
     p0.setPosition(Vec3D(0,0,0));
     p0.setVelocity(Vec3D(0.1 * problem.getXMax(), 0.1 * problem.getYMax(), 0.1 * problem.getZMax())); // sets particle position
     Mdouble VelMag = 4;
     Mdouble theta = params[0]; // Controls the inclination angle of a cannon
     Mdouble phi = params[1];  // Controls azimutal orientation of a cannon
     // Set the initial velocity of the projectile
     p0.setVelocity(Vec3D(VelMag * sin(theta) * cos(phi), VelMag * sin(theta) * sin(phi), VelMag * cos(theta)));
     problem.particleHandler.copyAndAddObject(p0);
     // Time integration and log parameters
     problem.setSaveCount(100);
     problem.dataFile.setFileType(FileType::ONE_FILE);
     problem.restartFile.setFileType(FileType::ONE_FILE);
     problem.fStatFile.setFileType(FileType::NO_FILE);
     problem.eneFile.setFileType(FileType::NO_FILE);
     logger(INFO, "run number: %", problem.dataFile.getCounter());
     problem.setXBallsAdditionalArguments("-solidf -v0");
     problem.setTimeStep(0.005 / 50.0); // (collision time)/50.0
     problem.solve();
     // Paraview data
     std::cout<<ExecCommand("rm -rf paraview_SimpleOpt/")<<std::endl;
     std::cout<<ExecCommand("mkdir paraview_SimpleOpt/")<<std::endl;
     std::cout<<ExecCommand("../../Tools/data2pvd SimpleOpt.data paraview_SimpleOpt/SimpleOpt")<<std::endl;
     // Return the functional via the text file
     std::ofstream funct;  funct.open ("functional.txt");
     Vec3D pos = problem.particleHandler.getLastObject()->getPosition();
     Mdouble fun = 1 / (pos.X * pos.X); // Minimization of this optimizes for the longest projectile travel along X direction
     funct << fun;
     funct.close();
     return 0;
 }
References a, cos(), ExecCommand(), i, INFO, logger, NO_FILE, ONE_FILE, p0, Particles2023AnalysisHung::params, problem, helpers::readFromCommandLine(), InfiniteWall::set(), ParticleSpecies::setDensity(), LinearViscoelasticNormalSpecies::setDissipation(), BaseWall::setSpecies(), LinearViscoelasticNormalSpecies::setStiffness(), sin(), oomph::Global_string_for_annotation::string(), BiharmonicTestFunctions2::theta, oomph::StringConversion::to_string(), and Vec3D::X.