MercuryDPM: vorticity_smoother_validation.cc File Reference
vorticity_smoother_validation.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class VorticityRecoveryProblem< ELEMENT >
Problem class for Anne's MSc problem.
Namespaces
GlobalParameters
Global parameters.
Functions
void GlobalParameters::sin_cos_velocity_field (const Vector< double > &x, Vector< double > &u)
void GlobalParameters::sin_cos_vorticity (const Vector< double > &x, Vector< Vector< double > > &vort_and_derivs)
void GlobalParameters::synthetic_velocity_field (const Vector< double > &x, Vector< double > &veloc)
Synthetic velocity field for validation.
void GlobalParameters::synthetic_vorticity (const Vector< double > &x, Vector< Vector< double > > &vort_and_derivs)
Synthetic vorticity field and derivs for validation.
void GlobalParameters::initial_condition (const Vector< double > &x, Vector< double > &u)
Initial condition for velocity.
int main (int argc, char *argv[])
Driver code for Anne channel problem.
Variables
double GlobalParameters::Length =2.0*MathematicalConstants::Pi
Length of computational domain.
double GlobalParameters::Kinematic_viscosity =1.0
The value of the kinematic viscosity (assumed to be the same everywhere)
Function Documentation
main()
int main (int argc , char * argv[])
Driver code for Anne channel problem.
 {
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::init(argc,argv);
  // Switch off output modifier
  oomph_info.output_modifier_pt()=&default_output_modifier;
  // Switch off oomph_info output for all processors but rank 0
  if (MPI_Helpers::communicator_pt()->my_rank()!=0)
  {
   oomph_info.stream_pt()=&oomph_nullstream;
   OomphLibWarning::set_stream_pt(&oomph_nullstream);
   OomphLibError::set_stream_pt(&oomph_nullstream);
  }
  else
  {
   oomph_info << "\n\n====================================================="
          << "\nNumber of processors: "
          << MPI_Helpers::communicator_pt()->nproc()
          << "\n=====================================================\n\n";
  }
 #endif
  // Create doc info object
  DocInfo doc_info;
  // Set the output directory
  doc_info.set_directory("RESLT");
  // Typedef element
  typedef ProjectableTaylorHoodElement<RefineableQTaylorHoodElement<2> > ELEMENT;
  // Set up problem
  VorticityRecoveryProblem<VorticitySmootherElement<ELEMENT> > problem;
  // Check/document the smoothed vorticity field
  problem.check_smoothed_vorticity(doc_info);
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::finalize();
 #endif
 } // end of main
References oomph::default_output_modifier, oomph::oomph_info, oomph::oomph_nullstream, oomph::OomphInfo::output_modifier_pt(), problem, oomph::DocInfo::set_directory(), and oomph::OomphInfo::stream_pt().