MercuryDPM: RandomClusterInsertionBoundary Class Reference
RandomClusterInsertionBoundary Class Reference
#include <RandomClusterInsertionBoundary.h>
Public Member Functions
RandomClusterInsertionBoundary ()
Constructor: inherits from BaseClusterInsertionBoundary constructor.
RandomClusterInsertionBoundary (const RandomClusterInsertionBoundary &other)
Copy constructor with deep copy.
~RandomClusterInsertionBoundary () override
Destructor: default destructor.
RandomClusterInsertionBoundary * copy () const override
Creates a copy on the heap and returns a pointer.
void set (BaseParticle *particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, Vec3D velMin, Vec3D velMax, Mdouble rMicroParticle)
Sets the properties of the ClusterInsertionBoundary.
void set (BaseParticle &particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, Vec3D velMin, Vec3D velMax, Mdouble rMicroParticle)
void set (BaseParticle *particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, Vec3D velMin, Vec3D velMax, Mdouble rMin, Mdouble rMax, Mdouble rMicroParticle)
old style set function which assumes a uniform psd.
void set (BaseParticle &particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, Vec3D velMin, Vec3D velMax, Mdouble rMin, Mdouble rMax, Mdouble rMicroParticle)
old style set function which assumes a uniform psd.
void set (BaseParticle *particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, unsigned int nParticlesPerCluster, Vec3D velMin, Vec3D velMax)
Sets the properties of the ClusterInsertionBoundary.
void set (BaseParticle &particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, unsigned int nParticlesPerCluster, Vec3D velMin, Vec3D velMax)
void set (BaseParticle *particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, unsigned int nParticlesPerCluster, Vec3D velMin, Vec3D velMax, Mdouble rMin, Mdouble rMax)
old style set function which assumes a uniform psd.
void set (BaseParticle &particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, unsigned int nParticlesPerCluster, Vec3D velMin, Vec3D velMax, Mdouble rMin, Mdouble rMax)
old style set function which assumes a uniform psd.
void setNumberOfParticlesPerCluster (unsigned int nParticlesPeCluster)
sets the number of particles per cluster
void checkBoundaryBeforeTimeStep (DPMBase *md) override
inserts cluster, if no interactions are detected.
void placeParticle (BaseParticle *p, RNG &random) override
sets random position and velocity for the cluster.
Public Member Functions inherited from BaseClusterInsertionBoundary
BaseClusterInsertionBoundary ()
Constructor; sets everything to 0.
BaseClusterInsertionBoundary (const BaseClusterInsertionBoundary &other)
Copy constructor with deep copy.
~BaseClusterInsertionBoundary () override
Destructor: default destructor.
void setRandomised (bool randomised)
this turns off the randomise(): created for UnitTests.
bool getRandomised ()
this returns a bool which indicates if the process is randomised (true) or not (false).
unsigned int getNumberOfClusterInserted ()
this returns the number of cluster inserted.
void setRadiusMicroParticle (Mdouble rMP)
this sets the radius of the micro particle composing the cluster.
void setGeometry (Vec3D posMin, Vec3D posMax)
Sets the geometry (position and velocity distribution) of the ClusterInsertionBoundary.
void setVelocityRange (Vec3D velMin, Vec3D velMax)
Sets the velocity range of the ClusterInsertionBoundary.
void setAdditionalClusterProperties (Mdouble collisionTimeOverTimeStep, Mdouble velocityDampingModulus, Mdouble energyRatioTolerance)
sets additional cluster properties as:
void setOutputClusterProperties (bool doCdatOutput, bool doOverlOutput, bool doAmatOutput, bool doIntStrucOutput, bool doVtkOutput, bool doRestartOutput, bool doFStatOutput, bool doEneOutput)
sets cluster whether or not cluster output files will be created, for example:
void read (std::istream &is) override
reads boundary properties from istream
void write (std::ostream &os) const override
writes boundary properties to ostream
Public Member Functions inherited from InsertionBoundary
InsertionBoundary ()
InsertionBoundary (const InsertionBoundary &other)
Copy constructor (with deep copy)
~InsertionBoundary () override
Destructor: delete the particle that has to be copied at every insertion.
virtual BaseParticle * generateParticle (RNG &random)
Sets the properties of the InsertionBoundary for a single particle type ‍/ virtual void set(BaseParticle* particleToCopy, unsigned int maxFailed, Vec3D velMin, Vec3D velMax, double radMin, double radMax)=0;.
virtual void shiftBoundary (Vec3D shift)
virtual function that shifts the boundary.
virtual void rotateBoundary (Vec3D angle)
virtual function that rotates the boundary.
void insertParticles (DPMBase *md)
Fill a certain domain with particles.
unsigned int getNumberOfParticlesInserted () const
Gets the number of particles inserted by the boundary.
Mdouble getMassOfParticlesInserted () const
Gets the mass of particles inserted by the boundary.
Mdouble getVolumeOfParticlesInserted () const
Gets the volume of particles inserted by the boundary.
void reset ()
resets particle property counter variables.
void activate ()
Turns on the InsertionBoundary.
void deactivate ()
Turns off the InsertionBoundary.
bool isActivated ()
Returns whether the InsertionBoundary is activated.
unsigned int getMaxFailed () const
Gets the number of times that the boundary may fail to insert a particle.
void setParticleToCopy (std::vector< BaseParticle * > particleToCopy)
Sets multiple different particles that will be inserted through the insertion boundary.
void setParticleToCopy (BaseParticle *particleToCopy)
Sets the particle that will be inserted through the insertion boundary.
std::vector< BaseParticle * > getParticleToCopy ()
Gets the particles that will be inserted through the insertion boundary.
void read (std::istream &is) override
Reads the boundary's id_ and maxFailed_.
void write (std::ostream &os) const override
Writes the boundary's id_ and maxFailed_.
Mdouble getVolumeFlowRate () const
Gets the volume flow rate of the insertion routine.
void setVolumeFlowRate (Mdouble volumeFlowRate)
Sets the volume flow rate of the insertion routine.
Mdouble getInitialVolume () const
Gets the initialVolume() .
void setInitialVolume (Mdouble initialVolume)
Gets the Volume which should be inserted by the insertion routine.
void setPSD (const PSD psd)
Sets the range of particle radii that may be generated from a user defined PSD.
void setPSD (std::vector< PSD > psd, std::vector< Mdouble > probability)
Sets the ranges of particle radii that may be generated from user defined PSDs.
std::vector< PSD > getPSD ()
Gets the particle size distributions set by the user.
void setVariableVolumeFlowRate (const std::vector< Mdouble > &variableCumulativeVolumeFlowRate, Mdouble samplingInterval)
Sets a variable volume flow rate.
bool insertParticle (Mdouble time)
Checks the inserted total volume and returns if a particle is still allowed to be inserted.
bool getCheckParticleForInteraction () const
Gets the variable that checks if a particle has an interaction.
void setCheckParticleForInteraction (bool checkParticleForInteraction)
Sets the variable that checks if a particle has an interaction.
void setManualInsertion (bool manualInsertion)
Set the flag for a manual PSD insertion routine.
Public Member Functions inherited from BaseBoundary
BaseBoundary ()
default constructor.
BaseBoundary (const BaseBoundary &b)
copy constructor
~BaseBoundary () override
destructor
virtual void createPeriodicParticle (BaseParticle *p UNUSED, ParticleHandler &pH UNUSED)
Creates a periodic particle in case of periodic boundaries in serial build.
virtual void createPeriodicParticles (ParticleHandler &pH UNUSED)
Creates periodic copies of given particle in case of periodic boundaries.
virtual void checkBoundaryAfterParticlesMove (ParticleHandler &pH)
Virtual function that does things to particles, each time step after particles have moved.
virtual void actionsBeforeTimeLoop ()
Virtual function that does something after DPMBase::setupInitialConditions but before the first time step.
virtual void modifyGhostAfterCreation (BaseParticle *particle, int i)
virtual void writeVTK (std::fstream &file)
void setHandler (BoundaryHandler *handler)
Sets the boundary's BoundaryHandler.
BoundaryHandler * getHandler () const
Returns the boundary's BoundaryHandler.
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Member Functions
std::string getName () const override
Returns the name of the object.
Additional Inherited Members
Public Attributes inherited from InsertionBoundary
std::vector< BaseParticle * > particleToCopy_
read Distribution class from file. ‍/ friend std::istream& operator>>(std::istream& is, InsertionBoundary::Distribution& type);
unsigned int maxFailed_
Number of times that the wall may fail to insert a particle.
unsigned int numberOfParticlesInserted_
Number of particles that are already inserted.
Mdouble massInserted_
Total mass of particles inserted.
Mdouble volumeInserted_
Total volume of particles inserted.
bool isActivated_
The InsertionBoundary is activated by default. If the InsertionBoundary is deactivated, then it introduces no particles (useful for trying to maintain a certain insertion rate).
Mdouble volumeFlowRate_
Mdouble initialVolume_
std::vector< Mdouble > variableCumulativeVolumeFlowRate_
Mdouble samplingInterval_
bool checkParticleForInteraction_
Checks if a particle has an interaction with a wall or other particles.
std::vector< PSD > particleSizeDistributionVector_
Defines a particle size distribution as an object of the PSD class; if particleSizeDistributionVector_ is empty, distribution_ is used instead.
Vec3D velMin_
Minimum and maximum velocity of the particles to be inserted.
Vec3D velMax_
bool isManuallyInserting_
A flag to enable a top-down class-by-class manual insertion of a PSD; default is FALSE.
std::vector< Mdouble > probability_
vector of probabilities in range [0,1] which determine the mixing ratio of partice size distributions.
int chosenSpecies_
stores the chosen species for each timestep.
BaseParticle * p0 = nullptr
pointer to the next particle that should be inserted (needs to be stored across time steps).
Protected Attributes inherited from BaseClusterInsertionBoundary
unsigned int nClusterInserted_
Mdouble radiusParticle_
int nParticles_
LinearPlasticViscoelasticFrictionSpecies * clusterSpecies_
bool isCdatOutputOn_
bool isOverlOutputOn_
bool isAmatOutputOn_
bool isIntStrucOutputOn_
bool isVtkOutputOn_
bool isRestartOutputOn_
bool isFStatOutputOn_
bool isEneOutputOn_
Mdouble sizeDispersityParticle_
Mdouble velocityDampingModulus_
int nInternalStructurePoints_
Mdouble energyRatioTolerance_
Mdouble collisionTimeOverTimeStep_
Vec3D posMin_
Vec3D posMax_
Vec3D velMin_
Vec3D velMax_
bool setRadiusParticleAndNotNumberOfParticles_
std::vector< Vec3D > clusterPositions_
std::vector< Mdouble > clusterRadii_
bool randomised_
Detailed Description
RandomClusterInsertionBoundary This class works exactly like CubeInsertionBoundary class but inserts clusters instead of particles. MPI: It does not work with MPI. One of the reasons is the need to adapt function DPMBase::importParticlesAs(). In particular particles and interaction should be imported as MPIParticle and MPIInteraction. In addition to this, the same should be done inside BaseCluster::actionsAfterSolve() when particles are centred around the desired position.
Constructor & Destructor Documentation
RandomClusterInsertionBoundary() [1/2]
RandomClusterInsertionBoundary::RandomClusterInsertionBoundary ()
Constructor: inherits from BaseClusterInsertionBoundary constructor.
Default constructor: inherits from BaseClusterInsertionBoundary constructor.
                                                                : BaseClusterInsertionBoundary()
 {
     logger(DEBUG, "RandomClusterInsertionBoundary::RandomClusterInsertionBoundary() finished");
 }
References DEBUG, and logger.
Referenced by copy().
RandomClusterInsertionBoundary() [2/2]
RandomClusterInsertionBoundary::RandomClusterInsertionBoundary (const RandomClusterInsertionBoundary & other)
Copy constructor with deep copy.
Copy constructor
         : BaseClusterInsertionBoundary(other) {
     logger(DEBUG, "RandomClusterInsertionBoundary::RandomClusterInsertionBoundary() finished");
 }
References DEBUG, and logger.
~RandomClusterInsertionBoundary()
RandomClusterInsertionBoundary::~RandomClusterInsertionBoundary () override default
Destructor: default destructor.
Default Destructor.
Member Function Documentation
checkBoundaryBeforeTimeStep()
void RandomClusterInsertionBoundary::checkBoundaryBeforeTimeStep (DPMBase * md) override virtual
inserts cluster, if no interactions are detected.
Reimplemented from BaseClusterInsertionBoundary.
 {
     logger(VERBOSE, "In RandomClusterInsertionBoundary::checkBoundaryBeforeTimeStep\n");
     if (!isActivated_)
         return;
     /* Each time step, the InsertionBoundary attempts to fill up a region with
      * clusters.
      *
      * It first calls generateParticle() to get a randomised particle, subject
      * to a specified distribution over sizes and species. (The basic class
      * supports size dispersity only but PolydisperseInsertionBoundary will
      * support species dispersity.)
      * Then it repeatedly calls placeParticle(), which gives the cluster a
      * random location (and possibly velocity) in a specified,
      * geometry-dependent bound. Each time, it checks whether the new cluster
      * would have an interaction with another cluster or a wall.
      *
      * If it manages to do that within maxFailed_ tries, then:
      *   * the new cluster is created and inserted,
      *   * the failure counter is reset, and
      * the processes is repeated with a new generateParticle().
      *
      * Otherwise, the processes terminates for this time step.
      * */
     // Keep count of how many successive times we have failed to place a new
     // particle.
     unsigned int failed = 0;
     while (failed <= maxFailed_ && insertParticle(md->getNextTime())) // 'generating' loop
     {
         /* Generate random *intrinsic* properties for the new particle. */
         logger(VERBOSE, "about to call generateParticle\n");
         auto p0 = generateParticle(md->random);
         logger(VERBOSE, "generated a particle with intrinsics %", p0);
         while (true) // 'placing' loop
         {
             /* Generate extrinsic properties (position and velocity) for this
              * new particle. */
             placeParticle(p0, md->random);
             logger(VERBOSE, "attempting to place particle at %, vel %", p0->getPosition(), p0->getVelocity());
 #ifdef MERCURYDPM_USE_MPI
             /* Communicate the new particle's properties by setHandler (note
              * that this doesn't actually add the particle to the handler). */
             if (NUMBER_OF_PROCESSORS > 1)
             {
                 MPIParticle particle;
                 //  //Every domain generates a particle (to get the species right etc)
                 //Send particle data from root to other processors to sync the particle properties
                 if (PROCESSOR_ID == 0)
                 {
                     particle = copyDataFromParticleToMPIParticle(p0);
                 }
                 MPIContainer::Instance().broadcast(&particle,MercuryMPIType::PARTICLE);
                 //Process the received data
                 if (PROCESSOR_ID != 0)
                 {
                     copyDataFromMPIParticleToParticle(&particle, p0, &(md->particleHandler));
                 }
             }
 #endif
             p0->setHandler(&md->particleHandler);
             /* Check whether the particle has any interactions. */
             if (md->checkParticleForInteraction(*p0))
             {
                 BaseCluster cluster;
                 if(getRandomised())
                     cluster.random.randomise();
                 cluster.setCollisionTimeOverTimeStep(collisionTimeOverTimeStep_);
                 cluster.setVelocityDampingModulus(velocityDampingModulus_);
                 cluster.setNumberOfInternalStructurePoints(nInternalStructurePoints_);
                 cluster.setEnergyRatioTolerance(energyRatioTolerance_);
                 cluster.setSizeDispersityParticle(sizeDispersityParticle_);
                 cluster.doCdatOutput(isCdatOutputOn_);
                 cluster.doOverlOutput(isOverlOutputOn_);
                 cluster.doAmatOutput(isAmatOutputOn_);
                 cluster.doIntStrucOutput(isIntStrucOutputOn_);
                 cluster.doVtkOutput(isVtkOutputOn_);
                 cluster.doRestartOutput(isRestartOutputOn_);
                 cluster.doFStatOutput(isFStatOutputOn_);
                 cluster.doEneOutput(isEneOutputOn_);
                 cluster.setClusterId(md->particleHandler.getNextGroupId());
                 if (setRadiusParticleAndNotNumberOfParticles_)
                     cluster.setRadiusParticle(radiusParticle_);
                 else
                     cluster.setNumberOfParticles(nParticles_);
                 cluster.setRadiusCluster(p0->getRadius());
                 cluster.setPosition(p0->getPosition());
                 cluster.setVelocity(p0->getVelocity());
                 cluster.setParticleSpecies(
                         dynamic_cast<LinearPlasticViscoelasticFrictionSpecies*>(
                                 md->speciesHandler.getObject(p0->getIndSpecies())));
 #ifdef MERCURYDPM_USE_MPI
                 cluster.setNumberOfDomains(md->getNumberOfDomains());
                 cluster.setDomain(md->getMin(), md->getMax());
                 cluster.speciesHandler.copyAndAddObject(md->speciesHandler.getObject(0));
 #endif
                 cluster.solve();
                 md->importParticlesAs( cluster.particleHandler, cluster.interactionHandler, p0->getSpecies() );
                 failed = 0;
                 // Number of cluster inserted
                 ++nClusterInserted_;
                 // Total number of particles inserted
                 numberOfParticlesInserted_ += cluster.particleHandler.getSize();
                 // This is the total mass composed by every single particle (not cluster!) inserted
                 massInserted_ += cluster.particleHandler.getMass();
                 // This is the total volume composed by every single particle (not cluster!) inserted
                 volumeInserted_ += cluster.particleHandler.getVolume();
                 logger(VERBOSE, "successfully placed a particle %, with position: % after % fails.", p0,
                        p0->getPosition(), failed);
                 /* JMFT: The generateParticle() routine allocates memory, so we should
                  * free it here. (Don't worry, the particle will have been copied to the
                  * particleHandler by this point iff we want it.) */
                 delete p0;
                 break; // out of the 'placing' loop
             }
             else
             {
                 failed++;
                 logger(VERBOSE, "failed to place a cluster; have failed % times", failed);
             }
             if (failed > maxFailed_)
             {
                 logger(VERBOSE, "failed too many times; giving up");
                 break; // out of the 'placing' loop (and will leave the 'generating' loop too
             }
         }
         logger(VERBOSE, "failed % times, so breaking out of InsertionBoundary loop for this timestep.", failed);
     }
     // logger(INFO, "volumeInserted_ = %", volumeInserted_);
 }
References MPIContainer::broadcast(), BaseClusterInsertionBoundary::collisionTimeOverTimeStep_, BaseHandler< T >::copyAndAddObject(), copyDataFromMPIParticleToParticle(), copyDataFromParticleToMPIParticle(), BaseCluster::doAmatOutput(), BaseCluster::doCdatOutput(), BaseCluster::doEneOutput(), BaseCluster::doFStatOutput(), BaseCluster::doIntStrucOutput(), BaseCluster::doOverlOutput(), BaseCluster::doRestartOutput(), BaseCluster::doVtkOutput(), BaseClusterInsertionBoundary::energyRatioTolerance_, InsertionBoundary::generateParticle(), BaseInteractable::getIndSpecies(), ParticleHandler::getMass(), BaseInteractable::getPosition(), BaseParticle::getRadius(), BaseClusterInsertionBoundary::getRandomised(), BaseHandler< T >::getSize(), BaseInteractable::getSpecies(), BaseInteractable::getVelocity(), ParticleHandler::getVolume(), InsertionBoundary::insertParticle(), MPIContainer::Instance(), DPMBase::interactionHandler, InsertionBoundary::isActivated_, BaseClusterInsertionBoundary::isAmatOutputOn_, BaseClusterInsertionBoundary::isCdatOutputOn_, BaseClusterInsertionBoundary::isEneOutputOn_, BaseClusterInsertionBoundary::isFStatOutputOn_, BaseClusterInsertionBoundary::isIntStrucOutputOn_, BaseClusterInsertionBoundary::isOverlOutputOn_, BaseClusterInsertionBoundary::isRestartOutputOn_, BaseClusterInsertionBoundary::isVtkOutputOn_, logger, InsertionBoundary::massInserted_, InsertionBoundary::maxFailed_, md, BaseClusterInsertionBoundary::nClusterInserted_, BaseClusterInsertionBoundary::nInternalStructurePoints_, BaseClusterInsertionBoundary::nParticles_, NUMBER_OF_PROCESSORS, InsertionBoundary::numberOfParticlesInserted_, InsertionBoundary::p0, PARTICLE, DPMBase::particleHandler, placeParticle(), PROCESSOR_ID, BaseClusterInsertionBoundary::radiusParticle_, DPMBase::random, RNG::randomise(), BaseCluster::setClusterId(), BaseCluster::setCollisionTimeOverTimeStep(), DPMBase::setDomain(), BaseCluster::setEnergyRatioTolerance(), BaseParticle::setHandler(), DPMBase::setNumberOfDomains(), BaseCluster::setNumberOfInternalStructurePoints(), BaseCluster::setNumberOfParticles(), BaseCluster::setParticleSpecies(), BaseCluster::setPosition(), BaseCluster::setRadiusCluster(), BaseCluster::setRadiusParticle(), BaseClusterInsertionBoundary::setRadiusParticleAndNotNumberOfParticles_, BaseCluster::setSizeDispersityParticle(), BaseCluster::setVelocity(), BaseCluster::setVelocityDampingModulus(), BaseClusterInsertionBoundary::sizeDispersityParticle_, DPMBase::solve(), DPMBase::speciesHandler, BaseClusterInsertionBoundary::velocityDampingModulus_, VERBOSE, and InsertionBoundary::volumeInserted_.
copy()
RandomClusterInsertionBoundary * RandomClusterInsertionBoundary::copy () const override virtual
Creates a copy on the heap and returns a pointer.
Copy method; creates a copy on the heap and returns its pointer.
Returns
pointer to the copy on the heap
Reimplemented from BaseClusterInsertionBoundary.
 {
 #ifdef DEBUG_CONSTRUCTOR
     std::cout << "BaseClusterInsertionBoundary::copy() const finished" << std::endl;
 #endif
     return new RandomClusterInsertionBoundary(*this);
 }
References RandomClusterInsertionBoundary().
getName()
std::string RandomClusterInsertionBoundary::getName () const override private virtual
Returns the name of the object.
Returns the name of the object class
Returns
the object's class' name, i.e. 'ClusterInsertionBoundary'
Reimplemented from BaseClusterInsertionBoundary.
 {
     return "RandomClusterInsertionBoundary";
 }
placeParticle()
void RandomClusterInsertionBoundary::placeParticle (BaseParticle * p, RNG & random) override virtual
sets random position and velocity for the cluster.
this sets position and velocity of the cluster.
Reimplemented from BaseClusterInsertionBoundary.
 {
     if(getRandomised())
         random.randomise();
     Vec3D pos, vel;
     pos.X = random.getRandomNumber(posMin_.X, posMax_.X);
     pos.Y = random.getRandomNumber(posMin_.Y, posMax_.Y);
     pos.Z = random.getRandomNumber(posMin_.Z, posMax_.Z);
     vel.X = random.getRandomNumber(velMin_.X, velMax_.X);
     vel.Y = random.getRandomNumber(velMin_.Y, velMax_.Y);
     vel.Z = random.getRandomNumber(velMin_.Z, velMax_.Z);
     p->setPosition(pos);
     p->setVelocity(vel);
 }
References BaseClusterInsertionBoundary::getRandomised(), RNG::getRandomNumber(), p, BaseClusterInsertionBoundary::posMax_, BaseClusterInsertionBoundary::posMin_, RNG::randomise(), BaseClusterInsertionBoundary::velMax_, BaseClusterInsertionBoundary::velMin_, Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by checkBoundaryBeforeTimeStep().
set() [1/8]
void RandomClusterInsertionBoundary::set (BaseParticle & particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, unsigned int nParticlesPerCluster, Vec3D velMin, Vec3D velMax)
 {
     set(&particleToCopy, maxFailed, posMin, posMax, nParticlesPerCluster, velMin, velMax);
 }
References set().
set() [2/8]
void RandomClusterInsertionBoundary::set (BaseParticle & particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, unsigned int nParticlesPerCluster, Vec3D velMin, Vec3D velMax, Mdouble rMin, Mdouble rMax)
old style set function which assumes a uniform psd.
old style set function which also assumes a uniform psd. Note if you want a specific PSD do not use but this is quicker for a uniform in size PSD
 {
     PSD uniformPSD;
     uniformPSD.setDistributionUniform(rMin, rMax, 2);
     setPSD(uniformPSD);
     set(particleToCopy, maxFailed, posMin, posMax, nParticlesPerCluster, velMin, velMax);
 }
References set(), PSD::setDistributionUniform(), and InsertionBoundary::setPSD().
set() [3/8]
void RandomClusterInsertionBoundary::set (BaseParticle & particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, Vec3D velMin, Vec3D velMax, Mdouble rMicroParticle)
 {
     set(&particleToCopy, maxFailed, posMin, posMax, velMin, velMax, rMicroParticle);
 }
References set().
set() [4/8]
void RandomClusterInsertionBoundary::set (BaseParticle & particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, Vec3D velMin, Vec3D velMax, Mdouble rMin, Mdouble rMax, Mdouble rMicroParticle)
old style set function which assumes a uniform psd.
 {
     PSD uniformPSD;
     uniformPSD.setDistributionUniform(rMin, rMax, 2);
     setPSD(uniformPSD);
     set(particleToCopy, maxFailed, posMin, posMax, velMin, velMax, rMicroParticle);
 }
References set(), PSD::setDistributionUniform(), and InsertionBoundary::setPSD().
set() [5/8]
void RandomClusterInsertionBoundary::set (BaseParticle * particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, unsigned int nParticlesPerCluster, Vec3D velMin, Vec3D velMax)
Sets the properties of the ClusterInsertionBoundary.
Sets all the properties of the cuboidal insertion boundary.
Parameters
[in] particleToCopy Pointer to the BaseParticle which is used as a basis for clusters to be inserted
[in] maxFailed The maximum number of times the insertion of a particle may be tried and failed before the insertion of particles is considered done NB: this property is used in the parent's InsertionBoundary::checkBoundaryBeforeTimeStep().
[in] posMin First defining corner of cuboidal insertion boundary
[in] posMax Second defining corner of cuboidal insertion boundary
[in] nParticlesPerCluster Number of particles composing the cluster.
[in] velMin Minimum velocity of inserted particles
[in] velMax Maximum velocity of inserted particles
Important: this function differs from the class above because gives the possiblity to set the number of particles instead of the radius of the micro particle.
 {
     setParticleToCopy(particleToCopy);
     velMin_ = velMin;
     velMax_ = velMax;
     maxFailed_ = maxFailed;
     setGeometry(posMin, posMax);
     setNumberOfParticlesPerCluster(nParticlesPerCluster);
 }
References InsertionBoundary::maxFailed_, BaseClusterInsertionBoundary::setGeometry(), setNumberOfParticlesPerCluster(), InsertionBoundary::setParticleToCopy(), BaseClusterInsertionBoundary::velMax_, and BaseClusterInsertionBoundary::velMin_.
set() [6/8]
void RandomClusterInsertionBoundary::set (BaseParticle * particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, unsigned int nParticlesPerCluster, Vec3D velMin, Vec3D velMax, Mdouble rMin, Mdouble rMax)
old style set function which assumes a uniform psd.
 {
     PSD uniformPSD;
     uniformPSD.setDistributionUniform(rMin, rMax, 2);
     setPSD(uniformPSD);
     set(particleToCopy, maxFailed, posMin, posMax, nParticlesPerCluster, velMin, velMax);
 }
References set(), PSD::setDistributionUniform(), and InsertionBoundary::setPSD().
set() [7/8]
void RandomClusterInsertionBoundary::set (BaseParticle * particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, Vec3D velMin, Vec3D velMax, Mdouble rMicroParticle)
Sets the properties of the ClusterInsertionBoundary.
Sets all the properties of the cuboidal insertion boundary.
Parameters
[in] particleToCopy Pointer to the BaseParticle which is used as a basis for clusters to be inserted
[in] maxFailed The maximum number of times the insertion of a particle may be tried and failed before the insertion of particles is considered done NB: this property is used in the parent's InsertionBoundary::checkBoundaryBeforeTimeStep().
[in] posMin First defining corner of cuboidal insertion boundary
[in] posMax Second defining corner of cuboidal insertion boundary
[in] velMin Minimum velocity of inserted particles
[in] velMax Maximum velocity of inserted particles
[in] rMicroParticle Radius of the single particle composing the cluster.
 {
     setParticleToCopy(particleToCopy);
     velMin_ = velMin;
     velMax_ = velMax;
     maxFailed_ = maxFailed;
     setGeometry(posMin, posMax);
     setRadiusMicroParticle(rMicroParticle);
 }
References InsertionBoundary::maxFailed_, BaseClusterInsertionBoundary::setGeometry(), InsertionBoundary::setParticleToCopy(), BaseClusterInsertionBoundary::setRadiusMicroParticle(), BaseClusterInsertionBoundary::velMax_, and BaseClusterInsertionBoundary::velMin_.
Referenced by set(), and RandomClusterInsertionBoundarySelfTest::setupInitialConditions().
set() [8/8]
void RandomClusterInsertionBoundary::set (BaseParticle * particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, Vec3D velMin, Vec3D velMax, Mdouble rMin, Mdouble rMax, Mdouble rMicroParticle)
old style set function which assumes a uniform psd.
 {
     PSD uniformPSD;
     uniformPSD.setDistributionUniform(rMin, rMax, 2);
     setPSD(uniformPSD);
     set(particleToCopy, maxFailed, posMin, posMax, velMin, velMax, rMicroParticle);
 }
References set(), PSD::setDistributionUniform(), and InsertionBoundary::setPSD().
setNumberOfParticlesPerCluster()
void RandomClusterInsertionBoundary::setNumberOfParticlesPerCluster (unsigned int nParticlesPeCluster)
sets the number of particles per cluster
 {
     if (nParticlesPeCluster <= 0)
         logger(ERROR, "The number of particles for a single cluster must be greater than zero. nParticlesPeCluster = %",
                nParticlesPeCluster);
     else
     {
         nParticles_ = nParticlesPeCluster;
         setRadiusParticleAndNotNumberOfParticles_ = false;
     }
 }
References ERROR, logger, BaseClusterInsertionBoundary::nParticles_, and BaseClusterInsertionBoundary::setRadiusParticleAndNotNumberOfParticles_.
Referenced by set().
The documentation for this class was generated from the following files:
RandomClusterInsertionBoundary.h
RandomClusterInsertionBoundary.cc