MercuryDPM: Eigen::NestByValue< ExpressionType > Class Template Reference
Eigen::NestByValue< ExpressionType > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Expression which must be nested by value.
#include <NestByValue.h>
Public Types
typedef internal::dense_xpr_base< NestByValue >::type Base
Public Member Functions
EIGEN_DEVICE_FUNC NestByValue (const ExpressionType &matrix)
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC operator const ExpressionType & () const
EIGEN_DEVICE_FUNC const ExpressionType & nestedExpression () const
EIGEN_DEVICE_FUNC std::enable_if< HasDirectAccess, const Scalar * >::type data () const
EIGEN_DEVICE_FUNC std::enable_if< HasDirectAccess, Index >::type innerStride () const
EIGEN_DEVICE_FUNC std::enable_if< HasDirectAccess, Index >::type outerStride () const
Static Public Attributes
static constexpr bool HasDirectAccess = internal::has_direct_access<ExpressionType>::ret
Protected Attributes
const ExpressionType m_expression
Detailed Description
template<typename ExpressionType>
class Eigen::NestByValue< ExpressionType >
Expression which must be nested by value.
Template Parameters
ExpressionType the type of the object of which we are requiring nesting-by-value
This class is the return type of MatrixBase::nestByValue() and most of the time this is the only way it is used.
See also
MatrixBase::nestByValue()
Member Typedef Documentation
Base
template<typename ExpressionType > typedef internal::dense_xpr_base<NestByValue>::type Eigen::NestByValue< ExpressionType >::Base
Constructor & Destructor Documentation
NestByValue()
template<typename ExpressionType > EIGEN_DEVICE_FUNC Eigen::NestByValue< ExpressionType >::NestByValue (const ExpressionType & matrix) inline explicit
 : m_expression(matrix) {}
Member Function Documentation
cols()
template<typename ExpressionType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::NestByValue< ExpressionType >::cols () const inline
 { return m_expression.cols(); }
References Eigen::NestByValue< ExpressionType >::m_expression.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
data()
template<typename ExpressionType > EIGEN_DEVICE_FUNC std::enable_if<HasDirectAccess, const Scalar*>::type Eigen::NestByValue< ExpressionType >::data () const inline
{
     return m_expression.data();
   }
References Eigen::NestByValue< ExpressionType >::m_expression.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
innerStride()
template<typename ExpressionType > EIGEN_DEVICE_FUNC std::enable_if<HasDirectAccess, Index>::type Eigen::NestByValue< ExpressionType >::innerStride () const inline
{
     return m_expression.innerStride();
   }
References Eigen::NestByValue< ExpressionType >::m_expression.
nestedExpression()
template<typename ExpressionType > EIGEN_DEVICE_FUNC const ExpressionType& Eigen::NestByValue< ExpressionType >::nestedExpression () const inline
 { return m_expression; }
References Eigen::NestByValue< ExpressionType >::m_expression.
operator const ExpressionType &()
template<typename ExpressionType > EIGEN_DEVICE_FUNC Eigen::NestByValue< ExpressionType >::operator const ExpressionType & () const inline
 { return m_expression; }
References Eigen::NestByValue< ExpressionType >::m_expression.
outerStride()
template<typename ExpressionType > EIGEN_DEVICE_FUNC std::enable_if<HasDirectAccess, Index>::type Eigen::NestByValue< ExpressionType >::outerStride () const inline
{
     return m_expression.outerStride();
   }
References Eigen::NestByValue< ExpressionType >::m_expression.
rows()
template<typename ExpressionType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::NestByValue< ExpressionType >::rows () const inline
 { return m_expression.rows(); }
References Eigen::NestByValue< ExpressionType >::m_expression.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
HasDirectAccess
template<typename ExpressionType > constexpr bool Eigen::NestByValue< ExpressionType >::HasDirectAccess = internal::has_direct_access<ExpressionType>::ret static constexpr
m_expression
template<typename ExpressionType > const ExpressionType Eigen::NestByValue< ExpressionType >::m_expression protected
Referenced by Eigen::NestByValue< ExpressionType >::cols(), Eigen::NestByValue< ExpressionType >::data(), Eigen::NestByValue< ExpressionType >::innerStride(), Eigen::NestByValue< ExpressionType >::nestedExpression(), Eigen::NestByValue< ExpressionType >::operator const ExpressionType &(), Eigen::NestByValue< ExpressionType >::outerStride(), and Eigen::NestByValue< ExpressionType >::rows().
The documentation for this class was generated from the following file:
NestByValue.h