MercuryDPM: oomph::TriangleMeshParameters Class Reference
oomph::TriangleMeshParameters Class Reference
#include <triangle_mesh.template.h>
Public Member Functions
TriangleMeshParameters (Vector< TriangleMeshClosedCurve * > &outer_boundary_pt)
TriangleMeshParameters (TriangleMeshClosedCurve *outer_boundary_pt)
TriangleMeshParameters ()
virtual ~TriangleMeshParameters ()
Empty destructor.
Vector< TriangleMeshClosedCurve * > outer_boundary_pt () const
Helper function for getting the outer boundary.
Vector< TriangleMeshClosedCurve * > & outer_boundary_pt ()
Helper function for getting access to the outer boundary.
TriangleMeshClosedCurve * outer_boundary_pt (const unsigned &i) const
Helper function for getting the i-th outer boundary.
TriangleMeshClosedCurve *& outer_boundary_pt (const unsigned &i)
Helper function for getting access to the i-th outer boundary.
Vector< TriangleMeshClosedCurve * > internal_closed_curve_pt () const
Helper function for getting the internal closed boundaries.
Vector< TriangleMeshClosedCurve * > & internal_closed_curve_pt ()
Vector< TriangleMeshOpenCurve * > internal_open_curves_pt () const
Helper function for getting the internal open boundaries.
Vector< TriangleMeshOpenCurve * > & internal_open_curves_pt ()
double element_area () const
Helper function for getting the element area.
double & element_area ()
Helper function for getting access to the element area.
Vector< Vector< double > > extra_holes_coordinates () const
Helper function for getting the extra holes.
Vector< Vector< double > > & extra_holes_coordinates ()
Helper function for getting access to the extra holes.
void add_region_coordinates (const unsigned &i, Vector< double > &region_coordinates)
Helper function for getting the extra regions.
std::map< unsigned, Vector< double > > & regions_coordinates ()
Helper function for getting access to the regions coordinates.
void set_target_area_for_region (const unsigned &i, const double &area)
Helper function to specify target area for region.
std::map< unsigned, double > & target_area_for_region ()
Helper function for getting access to the region's target areas.
void enable_use_attributes ()
Helper function for enabling the use of attributes.
void disable_use_attributes ()
Helper function for disabling the use of attributes.
bool is_use_attributes () const
void enable_boundary_refinement ()
Helper function for enabling the use of boundary refinement.
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
void set_communicator_pt (OomphCommunicator *comm_pt)
Function to set communicator (mesh is then assumed to be distributed)
OomphCommunicator * communicator_pt () const
Read-only access fct to communicator (Null if mesh is not distributed)
void disable_boundary_refinement ()
Helper function for disabling the use of boundary refinement.
bool is_boundary_refinement_allowed () const
Helper function for getting the status of boundary refinement.
void enable_internal_boundary_refinement ()
Helper function for enabling the use of boundary refinement.
void disable_internal_boundary_refinement ()
Helper function for disabling the use of boundary refinement.
bool is_internal_boundary_refinement_allowed () const
Helper function for getting the status of boundary refinement.
void enable_automatic_creation_of_vertices_on_boundaries ()
void disable_automatic_creation_of_vertices_on_boundaries ()
bool is_automatic_creation_of_vertices_on_boundaries_allowed ()
Protected Attributes
Vector< TriangleMeshClosedCurve * > Outer_boundary_pt
The outer boundary.
Vector< TriangleMeshClosedCurve * > Internal_closed_curve_pt
Internal closed boundaries.
Vector< TriangleMeshOpenCurve * > Internal_open_curves_pt
Internal boundaries.
double Element_area
The element are when calling triangulate external routine.
Vector< Vector< double > > Extra_holes_coordinates
Store the coordinates for defining extra holes.
std::map< unsigned, Vector< double > > Regions_coordinates
std::map< unsigned, double > Regions_areas
bool Use_attributes
Define the use of attributes (regions)
bool Boundary_refinement
Do not allow refinement of nodes on the boundary.
bool Internal_boundary_refinement
Do not allow refinement of nodes on the internal boundary.
bool Allow_automatic_creation_of_vertices_on_boundaries
OomphCommunicator * Comm_pt
Detailed Description
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Helper object for dealing with the parameters used for the TriangleMesh objects
Constructor & Destructor Documentation
TriangleMeshParameters() [1/3]
oomph::TriangleMeshParameters::TriangleMeshParameters (Vector< TriangleMeshClosedCurve * > & outer_boundary_pt) inline
Constructor: Only takes the outer boundary, all the other parameters are stated with the specific parameters
       : Outer_boundary_pt(outer_boundary_pt),
         Element_area(0.2),
         Use_attributes(false),
         Boundary_refinement(true),
         Internal_boundary_refinement(true),
         Allow_automatic_creation_of_vertices_on_boundaries(true),
         Comm_pt(0)
     {
     }
TriangleMeshParameters() [2/3]
oomph::TriangleMeshParameters::TriangleMeshParameters (TriangleMeshClosedCurve * outer_boundary_pt) inline
Constructor: Only takes the outer boundary, all the other parameters are stated with the specific parameters
       : Element_area(0.2),
         Use_attributes(false),
         Boundary_refinement(true),
         Internal_boundary_refinement(true),
         Allow_automatic_creation_of_vertices_on_boundaries(true),
         Comm_pt(0)
     {
       Outer_boundary_pt.resize(1);
       Outer_boundary_pt[0] = outer_boundary_pt;
     }
References outer_boundary_pt(), and Outer_boundary_pt.
TriangleMeshParameters() [3/3]
oomph::TriangleMeshParameters::TriangleMeshParameters () inline
Constructor: Takes nothing and initializes the other parameters to the default ones
       : Element_area(0.2),
         Use_attributes(false),
         Boundary_refinement(true),
         Internal_boundary_refinement(true),
         Allow_automatic_creation_of_vertices_on_boundaries(true),
         Comm_pt(0)
     {
     }
~TriangleMeshParameters()
virtual oomph::TriangleMeshParameters::~TriangleMeshParameters () inline virtual
Empty destructor.
 {}
Member Function Documentation
add_region_coordinates()
void oomph::TriangleMeshParameters::add_region_coordinates (const unsigned & i, Vector< double > & region_coordinates) inline
Helper function for getting the extra regions.
     {
       // Verify if not using the default region number (zero)
       if (i == 0)
       {
         std::ostringstream error_message;
         error_message
           << "Please use another region id different from zero.\n"
           << "It is internally used as the default region number.\n";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       // First check if the region with the specified id does not already exist
       std::map<unsigned, Vector<double>>::iterator it;
       it = Regions_coordinates.find(i);
       // If it is already a region defined with that id throw an error
       if (it != Regions_coordinates.end())
       {
         std::ostringstream error_message;
         error_message << "The region id (" << i << ") that you are using for"
                       << "defining\n"
                       << "your region is already in use. Use another\n"
                       << "region id and verify that you are not re-using\n"
                       << " previously defined regions ids\n"
                       << std::endl;
         OomphLibWarning(error_message.str(),
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
       }
       // If it does not exist then create the map
       Regions_coordinates[i] = region_coordinates;
       // Automatically set the using of attributes to enable
       enable_use_attributes();
     }
References enable_use_attributes(), i, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and Regions_coordinates.
Referenced by oomph::DiskTetMeshFacetedSurface::DiskTetMeshFacetedSurface(), DropInChannelProblem< ELEMENT >::DropInChannelProblem(), HomogenisationProblem< ELEMENT >::HomogenisationProblem(), MeltContactProblem< ELEMENT >::MeltContactProblem(), RingWithTRibProblem< ELASTICITY_ELEMENT >::RingWithTRibProblem(), SolarRadiationProblem< ELEMENT >::SolarRadiationProblem(), StefanBoltzmannProblem< ELEMENT >::StefanBoltzmannProblem(), TwoLayerInterfaceProblem< ELEMENT >::TwoLayerInterfaceProblem(), and UnstructuredFvKProblem< ELEMENT >::UnstructuredFvKProblem().
communicator_pt()
OomphCommunicator* oomph::TriangleMeshParameters::communicator_pt () const inline
Read-only access fct to communicator (Null if mesh is not distributed)
     {
       return Comm_pt;
     }
References Comm_pt.
disable_automatic_creation_of_vertices_on_boundaries()
void oomph::TriangleMeshParameters::disable_automatic_creation_of_vertices_on_boundaries () inline
Disables the creation of points (by Triangle) on the outer and internal boundaries
     {
       Allow_automatic_creation_of_vertices_on_boundaries = false;
     }
References Allow_automatic_creation_of_vertices_on_boundaries.
disable_boundary_refinement()
void oomph::TriangleMeshParameters::disable_boundary_refinement () inline
Helper function for disabling the use of boundary refinement.
     {
       Boundary_refinement = false;
     }
References Boundary_refinement.
Referenced by HomogenisationProblem< ELEMENT >::HomogenisationProblem().
disable_internal_boundary_refinement()
void oomph::TriangleMeshParameters::disable_internal_boundary_refinement () inline
Helper function for disabling the use of boundary refinement.
     {
       Internal_boundary_refinement = false;
     }
References Internal_boundary_refinement.
disable_use_attributes()
void oomph::TriangleMeshParameters::disable_use_attributes () inline
Helper function for disabling the use of attributes.
     {
       Use_attributes = false;
     }
References Use_attributes.
element_area() [1/2]
double& oomph::TriangleMeshParameters::element_area () inline
Helper function for getting access to the element area.
     {
       return Element_area;
     }
References Element_area.
element_area() [2/2]
double oomph::TriangleMeshParameters::element_area () const inline
Helper function for getting the element area.
     {
       return Element_area;
     }
References Element_area.
Referenced by AxiPoroProblem< ELEMENT, TIMESTEPPER >::AxiPoroProblem(), AxisymmetricVibratingShellProblem< ELEMENT >::AxisymmetricVibratingShellProblem(), BubbleInChannelProblem< ELEMENT >::BubbleInChannelProblem(), ContactProblem< ELEMENT >::ContactProblem(), DarcyProblem< ELEMENT >::DarcyProblem(), oomph::DiskTetMeshFacetedSurface::DiskTetMeshFacetedSurface(), DropInChannelProblem< ELEMENT >::DropInChannelProblem(), ElasticAnnulusProblem< ELASTICITY_ELEMENT >::ElasticAnnulusProblem(), FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::FourierDecomposedTimeHarmonicLinearElasticityProblem(), HomogenisationProblem< ELEMENT >::HomogenisationProblem(), MeltContactProblem< ELEMENT >::MeltContactProblem(), PMLFourierDecomposedHelmholtzProblem< ELEMENT >::PMLFourierDecomposedHelmholtzProblem(), PMLHelmholtzMGProblem< ELEMENT >::PMLHelmholtzMGProblem(), PMLProblem< ELEMENT >::PMLProblem(), PoissonProblem< ELEMENT >::PoissonProblem(), PressureWaveFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::PressureWaveFSIProblem(), RingWithTRibProblem< ELASTICITY_ELEMENT >::RingWithTRibProblem(), SolarRadiationProblem< ELEMENT >::SolarRadiationProblem(), StefanBoltzmannProblem< ELEMENT >::StefanBoltzmannProblem(), TwoLayerInterfaceProblem< ELEMENT >::TwoLayerInterfaceProblem(), UnsteadyHeatMeltProblem< ELEMENT >::UnsteadyHeatMeltProblem(), UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem(), UnstructuredFluidProblem< ELEMENT >::UnstructuredFluidProblem(), UnstructuredFvKProblem< ELEMENT >::UnstructuredFvKProblem(), UnstructuredImmersedEllipseProblem< ELEMENT >::UnstructuredImmersedEllipseProblem(), UnstructuredPoissonProblem< ELEMENT >::UnstructuredPoissonProblem(), UnstructuredSolidProblem< ELEMENT, MESH >::UnstructuredSolidProblem(), UnstructuredTorusProblem< ELEMENT >::UnstructuredTorusProblem(), and VibratingShellProblem< ELEMENT >::VibratingShellProblem().
enable_automatic_creation_of_vertices_on_boundaries()
void oomph::TriangleMeshParameters::enable_automatic_creation_of_vertices_on_boundaries () inline
Enables the creation of points (by Triangle) on the outer and internal boundaries
     {
       Allow_automatic_creation_of_vertices_on_boundaries = true;
     }
References Allow_automatic_creation_of_vertices_on_boundaries.
enable_boundary_refinement()
void oomph::TriangleMeshParameters::enable_boundary_refinement () inline
Helper function for enabling the use of boundary refinement.
     {
       Boundary_refinement = true;
     }
References Boundary_refinement.
Referenced by AxisymmetricVibratingShellProblem< ELEMENT >::AxisymmetricVibratingShellProblem(), and VibratingShellProblem< ELEMENT >::VibratingShellProblem().
enable_internal_boundary_refinement()
void oomph::TriangleMeshParameters::enable_internal_boundary_refinement () inline
Helper function for enabling the use of boundary refinement.
     {
       Internal_boundary_refinement = true;
     }
References Internal_boundary_refinement.
enable_use_attributes()
void oomph::TriangleMeshParameters::enable_use_attributes () inline
Helper function for enabling the use of attributes.
     {
       Use_attributes = true;
     }
References Use_attributes.
Referenced by add_region_coordinates().
extra_holes_coordinates() [1/2]
Vector<Vector<double> >& oomph::TriangleMeshParameters::extra_holes_coordinates () inline
Helper function for getting access to the extra holes.
     {
       return Extra_holes_coordinates;
     }
References Extra_holes_coordinates.
extra_holes_coordinates() [2/2]
Vector<Vector<double> > oomph::TriangleMeshParameters::extra_holes_coordinates () const inline
Helper function for getting the extra holes.
     {
       return Extra_holes_coordinates;
     }
References Extra_holes_coordinates.
internal_closed_curve_pt() [1/2]
Vector<TriangleMeshClosedCurve*>& oomph::TriangleMeshParameters::internal_closed_curve_pt () inline
Helper function for getting access to the internal closed boundaries
     {
       return Internal_closed_curve_pt;
     }
References Internal_closed_curve_pt.
internal_closed_curve_pt() [2/2]
Vector<TriangleMeshClosedCurve*> oomph::TriangleMeshParameters::internal_closed_curve_pt () const inline
Helper function for getting the internal closed boundaries.
     {
       return Internal_closed_curve_pt;
     }
References Internal_closed_curve_pt.
Referenced by BubbleInChannelProblem< ELEMENT >::BubbleInChannelProblem(), oomph::DiskTetMeshFacetedSurface::DiskTetMeshFacetedSurface(), DropInChannelProblem< ELEMENT >::DropInChannelProblem(), ElasticAnnulusProblem< ELASTICITY_ELEMENT >::ElasticAnnulusProblem(), HomogenisationProblem< ELEMENT >::HomogenisationProblem(), PMLHelmholtzMGProblem< ELEMENT >::PMLHelmholtzMGProblem(), PMLProblem< ELEMENT >::PMLProblem(), StefanBoltzmannProblem< ELEMENT >::StefanBoltzmannProblem(), TwoLayerInterfaceProblem< ELEMENT >::TwoLayerInterfaceProblem(), UnstructuredFluidProblem< ELEMENT >::UnstructuredFluidProblem(), UnstructuredFvKProblem< ELEMENT >::UnstructuredFvKProblem(), UnstructuredImmersedEllipseProblem< ELEMENT >::UnstructuredImmersedEllipseProblem(), UnstructuredPoissonProblem< ELEMENT >::UnstructuredPoissonProblem(), and UnstructuredTorusProblem< ELEMENT >::UnstructuredTorusProblem().
internal_open_curves_pt() [1/2]
Vector<TriangleMeshOpenCurve*>& oomph::TriangleMeshParameters::internal_open_curves_pt () inline
Helper function for getting access to the internal open boundaries
     {
       return Internal_open_curves_pt;
     }
References Internal_open_curves_pt.
internal_open_curves_pt() [2/2]
Vector<TriangleMeshOpenCurve*> oomph::TriangleMeshParameters::internal_open_curves_pt () const inline
Helper function for getting the internal open boundaries.
     {
       return Internal_open_curves_pt;
     }
References Internal_open_curves_pt.
Referenced by AxiPoroProblem< ELEMENT, TIMESTEPPER >::AxiPoroProblem(), MeltContactProblem< ELEMENT >::MeltContactProblem(), RingWithTRibProblem< ELASTICITY_ELEMENT >::RingWithTRibProblem(), SolarRadiationProblem< ELEMENT >::SolarRadiationProblem(), TwoLayerInterfaceProblem< ELEMENT >::TwoLayerInterfaceProblem(), and UnstructuredFvKProblem< ELEMENT >::UnstructuredFvKProblem().
is_automatic_creation_of_vertices_on_boundaries_allowed()
bool oomph::TriangleMeshParameters::is_automatic_creation_of_vertices_on_boundaries_allowed () inline
Returns the status of the variable Allow_automatic_creation_of_vertices_on_boundaries
     {
       return Allow_automatic_creation_of_vertices_on_boundaries;
     }
References Allow_automatic_creation_of_vertices_on_boundaries.
is_boundary_refinement_allowed()
bool oomph::TriangleMeshParameters::is_boundary_refinement_allowed () const inline
Helper function for getting the status of boundary refinement.
     {
       return Boundary_refinement;
     }
References Boundary_refinement.
is_internal_boundary_refinement_allowed()
bool oomph::TriangleMeshParameters::is_internal_boundary_refinement_allowed () const inline
Helper function for getting the status of boundary refinement.
     {
       return Internal_boundary_refinement;
     }
References Internal_boundary_refinement.
is_mesh_distributed()
bool oomph::TriangleMeshParameters::is_mesh_distributed () const inline
Boolean to indicate if Mesh has been distributed.
     {
       return (Comm_pt != 0);
     }
References Comm_pt.
is_use_attributes()
bool oomph::TriangleMeshParameters::is_use_attributes () const inline
Helper function for getting the status of use_attributes variable
     {
       return Use_attributes;
     }
References Use_attributes.
outer_boundary_pt() [1/4]
Vector<TriangleMeshClosedCurve*>& oomph::TriangleMeshParameters::outer_boundary_pt () inline
Helper function for getting access to the outer boundary.
     {
       return Outer_boundary_pt;
     }
References Outer_boundary_pt.
outer_boundary_pt() [2/4]
Vector<TriangleMeshClosedCurve*> oomph::TriangleMeshParameters::outer_boundary_pt () const inline
Helper function for getting the outer boundary.
     {
       return Outer_boundary_pt;
     }
References Outer_boundary_pt.
Referenced by TriangleMeshParameters().
outer_boundary_pt() [3/4]
TriangleMeshClosedCurve*& oomph::TriangleMeshParameters::outer_boundary_pt (const unsigned & i) inline
Helper function for getting access to the i-th outer boundary.
     {
       return Outer_boundary_pt[i];
     }
References i, and Outer_boundary_pt.
outer_boundary_pt() [4/4]
TriangleMeshClosedCurve* oomph::TriangleMeshParameters::outer_boundary_pt (const unsigned & i) const inline
Helper function for getting the i-th outer boundary.
     {
       return Outer_boundary_pt[i];
     }
References i, and Outer_boundary_pt.
regions_coordinates()
std::map<unsigned, Vector<double> >& oomph::TriangleMeshParameters::regions_coordinates () inline
Helper function for getting access to the regions coordinates.
     {
       return Regions_coordinates;
     }
References Regions_coordinates.
set_communicator_pt()
void oomph::TriangleMeshParameters::set_communicator_pt (OomphCommunicator * comm_pt) inline
Function to set communicator (mesh is then assumed to be distributed)
     {
       Comm_pt = comm_pt;
     }
References Comm_pt.
set_target_area_for_region()
void oomph::TriangleMeshParameters::set_target_area_for_region (const unsigned & i, const double & area) inline
Helper function to specify target area for region.
     {
       Regions_areas[i] = area;
     }
References i, and Regions_areas.
target_area_for_region()
std::map<unsigned, double>& oomph::TriangleMeshParameters::target_area_for_region () inline
Helper function for getting access to the region's target areas.
     {
       return Regions_areas;
     }
References Regions_areas.
Member Data Documentation
Allow_automatic_creation_of_vertices_on_boundaries
bool oomph::TriangleMeshParameters::Allow_automatic_creation_of_vertices_on_boundaries protected
Allows automatic creation of vertices along boundaries by Triangle
Referenced by disable_automatic_creation_of_vertices_on_boundaries(), enable_automatic_creation_of_vertices_on_boundaries(), and is_automatic_creation_of_vertices_on_boundaries_allowed().
Boundary_refinement
bool oomph::TriangleMeshParameters::Boundary_refinement protected
Do not allow refinement of nodes on the boundary.
Referenced by disable_boundary_refinement(), enable_boundary_refinement(), and is_boundary_refinement_allowed().
Comm_pt
OomphCommunicator* oomph::TriangleMeshParameters::Comm_pt protected
Pointer to communicator – set to NULL if mesh is not distributed Required to pass it to new distributed meshes created at the adaptation stage
Referenced by communicator_pt(), is_mesh_distributed(), and set_communicator_pt().
Element_area
double oomph::TriangleMeshParameters::Element_area protected
The element are when calling triangulate external routine.
Referenced by element_area().
Extra_holes_coordinates
Vector<Vector<double> > oomph::TriangleMeshParameters::Extra_holes_coordinates protected
Store the coordinates for defining extra holes.
Referenced by extra_holes_coordinates().
Internal_boundary_refinement
bool oomph::TriangleMeshParameters::Internal_boundary_refinement protected
Do not allow refinement of nodes on the internal boundary.
Referenced by disable_internal_boundary_refinement(), enable_internal_boundary_refinement(), and is_internal_boundary_refinement_allowed().
Internal_closed_curve_pt
Vector<TriangleMeshClosedCurve*> oomph::TriangleMeshParameters::Internal_closed_curve_pt protected
Internal closed boundaries.
Referenced by internal_closed_curve_pt().
Internal_open_curves_pt
Vector<TriangleMeshOpenCurve*> oomph::TriangleMeshParameters::Internal_open_curves_pt protected
Internal boundaries.
Referenced by internal_open_curves_pt().
Outer_boundary_pt
Vector<TriangleMeshClosedCurve*> oomph::TriangleMeshParameters::Outer_boundary_pt protected
The outer boundary.
Referenced by outer_boundary_pt(), and TriangleMeshParameters().
Regions_areas
std::map<unsigned, double> oomph::TriangleMeshParameters::Regions_areas protected
Target areas for regions; defaults to 0.0 which (luckily) implies "no specific target area" for triangle!
Referenced by set_target_area_for_region(), and target_area_for_region().
Regions_coordinates
std::map<unsigned, Vector<double> > oomph::TriangleMeshParameters::Regions_coordinates protected
Store the coordinates for defining extra regions The key on the map is the region id
Referenced by add_region_coordinates(), and regions_coordinates().
Use_attributes
bool oomph::TriangleMeshParameters::Use_attributes protected
Define the use of attributes (regions)
Referenced by disable_use_attributes(), enable_use_attributes(), and is_use_attributes().
The documentation for this class was generated from the following file:
triangle_mesh.template.h