MercuryDPM: SinterNormalSpecies Class Reference
SinterNormalSpecies Class Reference
SinterNormalSpecies contains the parameters used to describe a plastic-cohesive normal force (Stefan Ludings plastic-cohesive force model).
#include <SinterNormalSpecies.h>
Public Types
typedef SinterInteraction InteractionType
The correct Interaction type for this FrictionForceSpecies.
Public Member Functions
SinterNormalSpecies ()
The default constructor.
SinterNormalSpecies (const SinterNormalSpecies &p)
The default copy constructor.
~SinterNormalSpecies ()
The default destructor.
void read (std::istream &is)
Reads the species properties from an input stream.
void write (std::ostream &os) const
Writes the species properties to an output stream.
std::string getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
void mix (SinterNormalSpecies *S, SinterNormalSpecies *T)
creates default values for mixed species
void setCollisionTimeAndRestitutionCoefficient (Mdouble tc, Mdouble eps, Mdouble mass)
void setStiffnessAndRestitutionCoefficient (Mdouble k_, Mdouble eps, Mdouble mass)
Sets k, disp such that it matches a given tc and eps for a collision of two copies of P.
Mdouble getCollisionTime (Mdouble mass)
Calculates collision time for two copies of a particle of given disp, k, mass.
void setPlasticParameters (Mdouble loadingStiffness, Mdouble unloadingStiffnessMax, Mdouble cohesionStiffness, Mdouble penetrationDepthMax)
Sets all parameters of the linear plastic-viscoelastic normal force at once.
Mdouble getLoadingStiffness () const
Returns the loading stiffness of the linear plastic-viscoelastic normal force.
Mdouble getUnloadingStiffnessMax () const
Returns the maximum unloading stiffness of the linear plastic-viscoelastic normal force.
Mdouble getCohesionStiffness () const
Returns the cohesive stiffness of the linear plastic-viscoelastic normal force.
Mdouble getPenetrationDepthMax () const
Returns the maximum penetration depth of the linear plastic-viscoelastic normal force.
void setLoadingStiffness (Mdouble loadingStiffness)
Sets the loading stiffness of the linear plastic-viscoelastic normal force.
void setUnloadingStiffnessMax (Mdouble unloadingStiffnessMax)
Sets the maximum unloading stiffness of the linear plastic-viscoelastic normal force.
void setCohesionStiffness (Mdouble cohesionStiffness)
Sets the cohesive stiffness of the linear plastic-viscoelastic normal force.
void setPenetrationDepthMax (Mdouble penetrationDepthMax)
Sets the maximum penetration depth of the linear plastic-viscoelastic normal force.
void setDissipation (Mdouble dissipation)
Sets the linear dissipation coefficient of the linear plastic-viscoelastic normal force.
Mdouble getDissipation () const
Allows the normal dissipation to be accessed.
void setSinterAdhesion (Mdouble sinterAdhesion)
Sets sinterAdhesion_.
Mdouble getSinterAdhesion () const
Accesses sinterAdhesion_.
void setInverseSinterViscosity (Mdouble inverseSinterViscosity)
Sets inverseSinterViscosity_.
Mdouble getInverseSinterViscosity () const
Accesses inverseSinterViscosity_.
MERCURYDPM_DEPRECATED void setLoadingStiffnessAndDissipation (helpers::KAndDisp new_)
Allows the spring and dissipation constants to be changed simultaneously.
Mdouble computeTimeStep (Mdouble mass)
Returns the optimal time step to resolve a collision of two particles of a given mass.
void setSinterForceAndTime (Mdouble adhesionForce, Mdouble sinterTime, Mdouble radius)
void setParhamiMcKeeping (Mdouble alpha, Mdouble beta, Mdouble atomicVolume, Mdouble surfaceEnergy, Mdouble thicknessDiffusion, Mdouble activationEnergy, Mdouble temperature)
Sets the sinterAdhesion_ and inverseSinterViscosity_ based on the Parhami-McKeeping parameters.
void setSinterRate (Mdouble sinterRate)
Sets sinterRate_.
void setSinterType (SINTERTYPE sinterType)
Sets sinterRate_.
Mdouble getSinterRate () const
Accesses sinterRate_.
SINTERTYPE getSinterType () const
std::function< double(double temperature)> getTemperatureDependentSinterRate () const
double getTemperatureDependentSinterRate (double temperature) const
void setTemperatureDependentSinterRate (std::function< double(double temperature)> temperatureDependentSinterRate)
void setComplianceZero (Mdouble complianceZero)
Mdouble getComplianceZero () const
void setSurfTension (Mdouble complianceZero)
Mdouble getSurfTension () const
void setConstantC1 (Mdouble constantC1_)
Mdouble getConstantC1 () const
void setSeparationDis (Mdouble separationDis)
Mdouble getSeparationDis () const
Public Member Functions inherited from BaseNormalForce
BaseNormalForce ()
BaseNormalForce (const BaseNormalForce &p)
bool getConstantRestitution () const
void setConstantRestitution (bool constantRestitution)
virtual void actionsAfterTimeStep (BaseParticle *particle) const
Public Member Functions inherited from BaseForce
BaseSpecies * getBaseSpecies () const
void setBaseSpecies (BaseSpecies *baseSpecies)
Private Attributes
Mdouble loadingStiffness_
(normal) spring constant (k_1)
Mdouble unloadingStiffnessMax_
the maximum elastic constant (k_2^max) for plastic deformations
Mdouble cohesionStiffness_
the adhesive spring constant (k^c) for plastic deformations
Mdouble penetrationDepthMax_
the depth (relative to the normalized radius) at which k_2^max is used (phi_f)
Mdouble dissipation_
linear dissipation coefficient
Mdouble sinterAdhesion_
Mdouble inverseSinterViscosity_
Mdouble sinterRate_
Mdouble complianceZero_
Mdouble surfTension_
Mdouble constantC1_
Mdouble separationDis_
SINTERTYPE sinterType_
sinterType options determin how the rate of sintering, d(equilibriumOverlap)/dt is computed PARHAMI_MCKEEPING: sinter rate given by (sinterAdhesion+normalForce)/sinterViscosity CONSTANT_RATE: sinter rate given by sinterRate
std::function< double(double temperature)> temperatureDependentSinterRate_
Detailed Description
SinterNormalSpecies contains the parameters used to describe a plastic-cohesive normal force (Stefan Ludings plastic-cohesive force model).
See SinterNormalInteraction::computeForce for a description of the force law.
Member Typedef Documentation
InteractionType
typedef SinterInteraction SinterNormalSpecies::InteractionType
The correct Interaction type for this FrictionForceSpecies.
Constructor & Destructor Documentation
SinterNormalSpecies() [1/2]
SinterNormalSpecies::SinterNormalSpecies ()
The default constructor.
         : BaseNormalForce()
 {
     sinterType_ = SINTERTYPE::PARHAMI_MCKEEPING;
     loadingStiffness_ = 0.0;
     unloadingStiffnessMax_ = 0.0;
     cohesionStiffness_ = 0.0;
     penetrationDepthMax_ = 0.0;
     dissipation_ = 0.0;
     sinterAdhesion_ = 0.0;
     sinterRate_ = 0.0;
     inverseSinterViscosity_ = 0.0;
     complianceZero_ = 0.0;
     surfTension_ = 0.0;
     constantC1_ = 0.0;
     separationDis_ = 0.0;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"SinterNormalSpecies::SinterNormalSpecies() finished"<<std::endl;
 #endif
 }
References cohesionStiffness_, complianceZero_, constantC1_, dissipation_, inverseSinterViscosity_, loadingStiffness_, PARHAMI_MCKEEPING, penetrationDepthMax_, separationDis_, sinterAdhesion_, sinterRate_, sinterType_, surfTension_, and unloadingStiffnessMax_.
SinterNormalSpecies() [2/2]
SinterNormalSpecies::SinterNormalSpecies (const SinterNormalSpecies & p)
The default copy constructor.
Parameters
[in] the species that is copied
         : BaseNormalForce(p)
 {
     sinterType_ = p.sinterType_;
     loadingStiffness_ = p.loadingStiffness_;
     unloadingStiffnessMax_ = p.unloadingStiffnessMax_;
     cohesionStiffness_ = p.cohesionStiffness_;
     penetrationDepthMax_ = p.penetrationDepthMax_;
     dissipation_ = p.dissipation_;
     sinterAdhesion_ = p.sinterAdhesion_;
     inverseSinterViscosity_ = p.inverseSinterViscosity_;
     sinterRate_ = p.sinterRate_;
     complianceZero_ = p.complianceZero_;
     surfTension_ = p.surfTension_;
     constantC1_ = p.constantC1_;
     separationDis_ = p.separationDis_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"SinterNormalSpecies::SinterNormalSpecies(const SinterNormalSpecies &p) finished"<<std::endl;
 #endif
 }
References cohesionStiffness_, complianceZero_, constantC1_, dissipation_, inverseSinterViscosity_, loadingStiffness_, p, penetrationDepthMax_, separationDis_, sinterAdhesion_, sinterRate_, sinterType_, surfTension_, and unloadingStiffnessMax_.
~SinterNormalSpecies()
SinterNormalSpecies::~SinterNormalSpecies ()
The default destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"SinterNormalSpecies::~SinterNormalSpecies() finished"<<std::endl;
 #endif
 }
Member Function Documentation
computeTimeStep()
Mdouble SinterNormalSpecies::computeTimeStep (Mdouble mass)
Returns the optimal time step to resolve a collision of two particles of a given mass.
Calculates collision time for stiffest spring constant, divides by 50
Parameters
[in] mass the optimal time step is computed to resolve a collision of two particles of this mass.
 {
     if (unloadingStiffnessMax_ / (.5 * mass) < mathsFunc::square(dissipation_ / mass))
     {
         logger(ERROR, "Dissipation too high; max. allowed %", sqrt(2.0 * unloadingStiffnessMax_ * mass));
     }
     return 0.02 * constants::pi /
            std::sqrt(unloadingStiffnessMax_ / (.5 * mass) - mathsFunc::square(dissipation_ / mass));
 }
References dissipation_, ERROR, logger, constants::pi, sqrt(), mathsFunc::square(), and unloadingStiffnessMax_.
getBaseName()
std::string SinterNormalSpecies::getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
Returns
a string containing the name of the species (minus the word "Species")
 {
     return "Sinter";
 }
getCohesionStiffness()
Mdouble SinterNormalSpecies::getCohesionStiffness () const
Returns the cohesive stiffness of the linear plastic-viscoelastic normal force.
Returns
the cohesive stiffness of the linear plastic-viscoelastic normal force.
 {
     return cohesionStiffness_;
 }
References cohesionStiffness_.
Referenced by SinterInteraction::computeNormalForce().
getCollisionTime()
Mdouble SinterNormalSpecies::getCollisionTime (Mdouble mass)
Calculates collision time for two copies of a particle of given disp, k, mass.
 {
     if (mass <= 0)
     {
         logger(ERROR, "Error in getCollisionTime(%) mass is not set or has an unexpected value, (getCollisionTime(%))",
                mass, mass);
     }
     if (loadingStiffness_ <= 0)
     {
         logger(ERROR, "Error in getCollisionTime(%) stiffness=% is not set or has an unexpected value "
                       "(getCollisionTime(%), with stiffness=%)",
                mass, loadingStiffness_, mass, loadingStiffness_);
     }
     if (dissipation_ < 0)
     {
         logger(ERROR, "Error in getCollisionTime(%) dissipation=%"
                       " is not set or has an unexpected value, (getCollisionTime(%), with dissipation=%)",
                mass, dissipation_, mass, dissipation_);
     }
     Mdouble tosqrt = loadingStiffness_ / (.5 * mass) - mathsFunc::square(dissipation_ / mass);
     if (tosqrt <= -1e-8 * loadingStiffness_ / (.5 * mass))
     {
         logger(ERROR, "Error in getCollisionTime(%) values for mass, stiffness and dissipation would lead to an "
                       "overdamped system, (getCollisionTime(%), with stiffness=% and dissipation=%)",
                mass, mass, loadingStiffness_, dissipation_);
     }
     return constants::pi / std::sqrt(tosqrt);
 }
References dissipation_, e(), ERROR, loadingStiffness_, logger, constants::pi, sqrt(), and mathsFunc::square().
getComplianceZero()
Mdouble SinterNormalSpecies::getComplianceZero () const
 {
     return complianceZero_;
 }
References complianceZero_.
Referenced by SinterInteraction::computeNormalForce().
getConstantC1()
Mdouble SinterNormalSpecies::getConstantC1 () const
 {
     return constantC1_;
 }
References constantC1_.
Referenced by SinterInteraction::computeNormalForce().
getDissipation()
Mdouble SinterNormalSpecies::getDissipation () const
Allows the normal dissipation to be accessed.
Returns
the linear dissipation coefficient
 {
     return dissipation_;
 }
References dissipation_.
Referenced by SinterInteraction::computeNormalForce().
getInverseSinterViscosity()
Mdouble SinterNormalSpecies::getInverseSinterViscosity () const
Accesses inverseSinterViscosity_.
Returns
value of inverseSinterViscosity_
 {
     return inverseSinterViscosity_;
 }
References inverseSinterViscosity_.
Referenced by setParhamiMcKeeping(), and setSinterForceAndTime().
getLoadingStiffness()
Mdouble SinterNormalSpecies::getLoadingStiffness () const
Returns the loading stiffness of the linear plastic-viscoelastic normal force.
Returns
the loading stiffness of the linear plastic-viscoelastic normal force.
 {
     return loadingStiffness_;
 }
References loadingStiffness_.
Referenced by SinterInteraction::computeNormalForce(), SinterInteraction::getElasticEnergy(), and SinterInteraction::getUnloadingStiffness().
getPenetrationDepthMax()
Mdouble SinterNormalSpecies::getPenetrationDepthMax () const
Returns the maximum penetration depth of the linear plastic-viscoelastic normal force.
Returns
the maximum penetration depth of the linear plastic-viscoelastic normal force.
 {
     return penetrationDepthMax_;
 }
References penetrationDepthMax_.
Referenced by SinterInteraction::computeNormalForce(), and SinterInteraction::getUnloadingStiffness().
getSeparationDis()
Mdouble SinterNormalSpecies::getSeparationDis () const
 {
     return separationDis_;
 }
References separationDis_.
Referenced by SinterInteraction::computeNormalForce().
getSinterAdhesion()
Mdouble SinterNormalSpecies::getSinterAdhesion () const
Accesses sinterAdhesion_.
Returns
value of sinterAdhesion_
 {
     return sinterAdhesion_;
 }
References sinterAdhesion_.
Referenced by SinterInteraction::computeNormalForce(), setParhamiMcKeeping(), and setSinterForceAndTime().
getSinterRate()
Mdouble SinterNormalSpecies::getSinterRate () const
Accesses sinterRate_.
Returns
value of sinterAdhesion_
 {
     return sinterRate_;
 }
References sinterRate_.
Referenced by SinterInteraction::computeNormalForce().
getSinterType()
SINTERTYPE SinterNormalSpecies::getSinterType () const
 {
     return sinterType_;
 }
References sinterType_.
Referenced by SinterInteraction::computeNormalForce().
getSurfTension()
Mdouble SinterNormalSpecies::getSurfTension () const
 {
     return surfTension_;
 }
References surfTension_.
Referenced by SinterInteraction::computeNormalForce().
getTemperatureDependentSinterRate() [1/2]
std::function< double(double temperature)> SinterNormalSpecies::getTemperatureDependentSinterRate () const
 {
     return temperatureDependentSinterRate_;
 }
References temperatureDependentSinterRate_.
Referenced by SinterInteraction::computeNormalForce().
getTemperatureDependentSinterRate() [2/2]
double SinterNormalSpecies::getTemperatureDependentSinterRate (double temperature) const
 {
     return temperatureDependentSinterRate_(temperature);
 }
References temperatureDependentSinterRate_.
getUnloadingStiffnessMax()
Mdouble SinterNormalSpecies::getUnloadingStiffnessMax () const
Returns the maximum unloading stiffness of the linear plastic-viscoelastic normal force.
Returns
the maximum unloading stiffness of the linear plastic-viscoelastic normal force.
 {
     return unloadingStiffnessMax_;
 }
References unloadingStiffnessMax_.
Referenced by SinterInteraction::computeNormalForce(), and SinterInteraction::getUnloadingStiffness().
mix()
void SinterNormalSpecies::mix (SinterNormalSpecies * S, SinterNormalSpecies * T)
creates default values for mixed species
For all parameters we assume that the harmonic mean of the parameters of the original two species is a sensible default.
Parameters
[in] S,T the two species whose properties are mixed to create the new species
 {
     loadingStiffness_ = BaseSpecies::average(S->getLoadingStiffness(), T->getLoadingStiffness());
     unloadingStiffnessMax_ = BaseSpecies::average(S->getUnloadingStiffnessMax(), T->getUnloadingStiffnessMax());
     cohesionStiffness_ = BaseSpecies::average(S->getCohesionStiffness(), T->getCohesionStiffness());
     penetrationDepthMax_ = BaseSpecies::average(S->getPenetrationDepthMax(), T->getPenetrationDepthMax());
     dissipation_ = BaseSpecies::average(S->getDissipation(), T->getDissipation());
     inverseSinterViscosity_ = BaseSpecies::average(S->getInverseSinterViscosity(), T->getInverseSinterViscosity());
     sinterAdhesion_ = BaseSpecies::average(S->getSinterAdhesion(), T->getSinterAdhesion());
     complianceZero_ = BaseSpecies::average(S->getComplianceZero(), T->getComplianceZero());
     surfTension_ = BaseSpecies::average(S->getSurfTension(), T->getSurfTension());
     constantC1_= BaseSpecies::average(S->getConstantC1(), T->getConstantC1());
     separationDis_ = BaseSpecies::average(S->getSeparationDis(), T->getSeparationDis());
 }
References BaseSpecies::average(), cohesionStiffness_, complianceZero_, constantC1_, dissipation_, inverseSinterViscosity_, loadingStiffness_, penetrationDepthMax_, oomph::QuadTreeNames::S, separationDis_, sinterAdhesion_, surfTension_, and unloadingStiffnessMax_.
read()
void SinterNormalSpecies::read (std::istream & is)
Reads the species properties from an input stream.
Parameters
[in] is input stream (typically the restart file)
 {
     std::string dummy;
     is >> dummy >> loadingStiffness_;
     is >> dummy >> unloadingStiffnessMax_;
     is >> dummy >> cohesionStiffness_;
     is >> dummy >> penetrationDepthMax_;
     is >> dummy >> dissipation_;
     is >> dummy >> sinterAdhesion_;
     is >> dummy >> inverseSinterViscosity_;
     is >> dummy >> sinterRate_;
     is >> dummy >> complianceZero_;
     is >> dummy >> surfTension_;
     is >> dummy >> constantC1_;
     is >> dummy >> separationDis_;
     unsigned type;
     is >> dummy >> type;
     sinterType_ = (SINTERTYPE) type;
 }
References cohesionStiffness_, complianceZero_, constantC1_, dissipation_, inverseSinterViscosity_, loadingStiffness_, penetrationDepthMax_, separationDis_, sinterAdhesion_, sinterRate_, sinterType_, oomph::Global_string_for_annotation::string(), surfTension_, compute_granudrum_aor::type, and unloadingStiffnessMax_.
setCohesionStiffness()
void SinterNormalSpecies::setCohesionStiffness (Mdouble cohesionStiffness)
Sets the cohesive stiffness of the linear plastic-viscoelastic normal force.
Parameters
[in] cohesionStiffness the cohesive stiffness of the linear plastic-viscoelastic normal force.
 {
     cohesionStiffness_ = cohesionStiffness;
 }
References cohesionStiffness_.
Referenced by setPlasticParameters().
setCollisionTimeAndRestitutionCoefficient()
void SinterNormalSpecies::setCollisionTimeAndRestitutionCoefficient (Mdouble tc, Mdouble eps, Mdouble mass)
Set k, disp such that is matches a given tc and eps for a collision of two different masses. Recall the resitution constant is a function of k, disp and the mass of each particle in the collision See also setCollisionTimeAndRestitutionCoefficient(Mdouble tc, Mdouble eps, Mdouble mass)
Sets k, disp such that it matches a given tc and eps for a collision of two copies of equal mass m
Parameters
[in] tc collision time
[in] eps restitution coefficient
[in] mass effective particle mass, \(\frac{2}{1/m1+1/m2}\)
Todo:
TW: check that the masses are described correctly here (m_eff or m_p?))
 {
     if (eps == 0.0)
     {
         loadingStiffness_ = .5 * mass * mathsFunc::square(constants::pi / tc);
         dissipation_ = std::sqrt(2.0 * mass * loadingStiffness_);
     }
     else
     {
         dissipation_ = -mass / tc * std::log(eps);
         loadingStiffness_ =
                 .5 * mass * (mathsFunc::square(constants::pi / tc) + mathsFunc::square(dissipation_ / mass));
     }
     unloadingStiffnessMax_ = loadingStiffness_;
 }
References dissipation_, CRBond_Bessel::eps, loadingStiffness_, Eigen::bfloat16_impl::log(), constants::pi, sqrt(), mathsFunc::square(), and unloadingStiffnessMax_.
setComplianceZero()
void SinterNormalSpecies::setComplianceZero (Mdouble complianceZero)
 {
     if (complianceZero < 0)
     {
         logger(ERROR, "complianceZero(%) argument should be non-negative!", complianceZero);
     }
     complianceZero_ = complianceZero;
 }
References complianceZero_, ERROR, and logger.
setConstantC1()
void SinterNormalSpecies::setConstantC1 (Mdouble constantC1_)
 {
     if (complianceOne < 0)
     {
         logger(ERROR, "ComplianceOne(%) argument should be non-negative!", complianceOne);
     }
     constantC1_ = complianceOne;
 }
References constantC1_, ERROR, and logger.
setDissipation()
void SinterNormalSpecies::setDissipation (Mdouble dissipation)
Sets the linear dissipation coefficient of the linear plastic-viscoelastic normal force.
should be non-negative
Parameters
[in] dissipation the linear dissipation coefficient of the linear plastic-viscoelastic normal force.
 {
     if (dissipation < 0)
     {
         logger(ERROR, "setDissipation(%) argument should be non-negative!", dissipation);
     }
     dissipation_ = dissipation;
 }
References dissipation_, ERROR, and logger.
Referenced by setLoadingStiffnessAndDissipation().
setInverseSinterViscosity()
void SinterNormalSpecies::setInverseSinterViscosity (Mdouble inverseSinterViscosity)
Sets inverseSinterViscosity_.
should be non-negative
Parameters
[in] the linear dissipation coefficient of the linear plastic-viscoelastic normal force.
 {
     //assertOrDie(inverseSinterViscosity < 0, "inverseSinterViscosity should be non-negative!");
     if (inverseSinterViscosity < 0)
     {
         logger(ERROR, "setInverseSinterViscosity(%) argument should be non-negative!", inverseSinterViscosity);
     }
     setSinterType(SINTERTYPE::PARHAMI_MCKEEPING);
     inverseSinterViscosity_ = inverseSinterViscosity;
 }
References ERROR, inverseSinterViscosity_, logger, PARHAMI_MCKEEPING, and setSinterType().
Referenced by setParhamiMcKeeping(), and setSinterForceAndTime().
setLoadingStiffness()
void SinterNormalSpecies::setLoadingStiffness (Mdouble loadingStiffness)
Sets the loading stiffness of the linear plastic-viscoelastic normal force.
Parameters
[in] loadingStiffness the loading stiffness of the linear plastic-viscoelastic normal force.
 {
     loadingStiffness_ = loadingStiffness;
 }
References loadingStiffness_.
Referenced by setLoadingStiffnessAndDissipation(), and setPlasticParameters().
setLoadingStiffnessAndDissipation()
void SinterNormalSpecies::setLoadingStiffnessAndDissipation (helpers::KAndDisp new_)
Allows the spring and dissipation constants to be changed simultaneously.
Parameters
[in] new_ a helper struct containing both the loading stiffness and the disssipation coefficient.
 {
     setLoadingStiffness(new_.k);
     setDissipation(new_.disp);
 }
References helpers::KAndDisp::disp, helpers::KAndDisp::k, setDissipation(), and setLoadingStiffness().
setParhamiMcKeeping()
void SinterNormalSpecies::setParhamiMcKeeping (Mdouble alpha, Mdouble beta, Mdouble atomicVolume, Mdouble surfaceEnergy, Mdouble thicknessDiffusion, Mdouble activationEnergy, Mdouble temperature)
Sets the sinterAdhesion_ and inverseSinterViscosity_ based on the Parhami-McKeeping parameters.
should be non-negative
Parameters
[in] the linear dissipation coefficient of the linear plastic-viscoelastic normal force.
 {
     setSinterType(SINTERTYPE::PARHAMI_MCKEEPING);
     const Mdouble boltzmannConstant /*k_B*/ = 1.38064852e-23;
     const Mdouble gasConstant /*R_g*/ = 8.314459848;
     const Mdouble thicknessDiffusionVacancy /*DB*/ =
             thicknessDiffusion * exp(-activationEnergy / gasConstant / temperature);
     const Mdouble diffusionParameter /*DeltaB*/ =
             atomicVolume / boltzmannConstant / temperature * thicknessDiffusionVacancy;
     setInverseSinterViscosity(constants::pi / (2.0 * beta * diffusionParameter));
     setSinterAdhesion(alpha / beta * constants::pi * surfaceEnergy);
     logger(INFO,
            "Set sintering parameters: the adhesion force f_a=%*r, the rate of change of the plastic overlap is d(delta0)/dt=f_ep/(%*a^4)",
            getSinterAdhesion(),
            getInverseSinterViscosity());
 }
References alpha, beta, Eigen::bfloat16_impl::exp(), getInverseSinterViscosity(), getSinterAdhesion(), INFO, logger, PARHAMI_MCKEEPING, constants::pi, setInverseSinterViscosity(), setSinterAdhesion(), and setSinterType().
setPenetrationDepthMax()
void SinterNormalSpecies::setPenetrationDepthMax (Mdouble penetrationDepthMax)
Sets the maximum penetration depth of the linear plastic-viscoelastic normal force.
Parameters
[in] penetrationDepthMax the maximum penetration depth of the linear plastic-viscoelastic normal force.
 {
     penetrationDepthMax_ = penetrationDepthMax;
 }
References penetrationDepthMax_.
Referenced by setPlasticParameters().
setPlasticParameters()
void SinterNormalSpecies::setPlasticParameters (Mdouble loadingStiffness, Mdouble unloadingStiffnessMax, Mdouble cohesionStiffness, Mdouble penetrationDepthMax)
Sets all parameters of the linear plastic-viscoelastic normal force at once.
Parameters
[in] loadingStiffness the loading stiffness of the linear plastic-viscoelastic normal force.
[in] unloadingStiffnessMax the maximum unloading stiffness of the linear plastic-viscoelastic normal force.
[in] cohesionStiffness the cohesive stiffness of the linear plastic-viscoelastic normal force.
[in] penetrationDepthMax the maximum penetration depth of the linear plastic-viscoelastic normal force.
 {
     if (loadingStiffness <= 0 || unloadingStiffnessMax < loadingStiffness || cohesionStiffness < 0 ||
         penetrationDepthMax < 0)
     {
         logger(ERROR, "arguments of setPlasticParameters do not make sense");
     }
     setLoadingStiffness(loadingStiffness);
     setUnloadingStiffnessMax(unloadingStiffnessMax);
     setCohesionStiffness(cohesionStiffness);
     setPenetrationDepthMax(penetrationDepthMax);
 }
References ERROR, logger, setCohesionStiffness(), setLoadingStiffness(), setPenetrationDepthMax(), and setUnloadingStiffnessMax().
setSeparationDis()
void SinterNormalSpecies::setSeparationDis (Mdouble separationDis)
 {
     if (separationDis < 0)
     {
         logger(ERROR, "SeparationDis(%) argument should be non-negative!", separationDis);
     }
     separationDis_ = separationDis;
 }
References ERROR, logger, and separationDis_.
setSinterAdhesion()
void SinterNormalSpecies::setSinterAdhesion (Mdouble sinterAdhesion)
Sets sinterAdhesion_.
should be non-negative
Parameters
[in] sinterAdhesion_
 {
     if (sinterAdhesion < 0)
     {
         logger(ERROR, "setSinterAdhesion(%) argument should be non-negative!", sinterAdhesion);
     }
     sinterAdhesion_ = sinterAdhesion;
 }
References ERROR, logger, and sinterAdhesion_.
Referenced by setParhamiMcKeeping(), and setSinterForceAndTime().
setSinterForceAndTime()
void SinterNormalSpecies::setSinterForceAndTime (Mdouble adhesionForce, Mdouble sinterTime, Mdouble radius)
Todo:
fix
 {
     sinterType_ = SINTERTYPE::PARHAMI_MCKEEPING;
     setSinterAdhesion(adhesionForce / radius);
     setInverseSinterViscosity(1.0 / (93.75 * adhesionForce * sinterTime / std::pow(radius, 5)));
     logger(INFO, "Set sintering parameters: adhesion force f_a=%*r,  sinter viscosity is nu = contactRadius^4/%",
            getSinterAdhesion(), getInverseSinterViscosity());
 }
References getInverseSinterViscosity(), getSinterAdhesion(), INFO, logger, PARHAMI_MCKEEPING, Eigen::bfloat16_impl::pow(), UniformPSDSelfTest::radius, setInverseSinterViscosity(), setSinterAdhesion(), and sinterType_.
setSinterRate()
void SinterNormalSpecies::setSinterRate (Mdouble sinterRate)
Sets sinterRate_.
should be non-negative
Parameters
[in] sinterAdhesion_
 {
     if (sinterRate < 0)
     {
         logger(ERROR, "setSinterRate(%) argument should be non-negative!", sinterRate);
     }
     sinterRate_ = sinterRate;
 }
References ERROR, logger, and sinterRate_.
setSinterType()
void SinterNormalSpecies::setSinterType (SINTERTYPE sinterType)
Sets sinterRate_.
should be non-negative
Parameters
[in] sinterAdhesion_
 {
     sinterType_ = sinterType;
     if (sinterType_ == SINTERTYPE::CONSTANT_RATE)
         logger(INFO, "Sintertype set to CONSTANT_RATE");
     else if (sinterType_ == SINTERTYPE::PARHAMI_MCKEEPING)
         logger(INFO, "Sintertype set to PARHAMI_MCKEEPING");
     else if (sinterType_ == SINTERTYPE::TEMPERATURE_DEPENDENT_FRENKEL)
         logger(INFO, "Sintertype set to TEMPERATURE_DEPENDENT_FRENKEL");
     else if (sinterType_ == SINTERTYPE::REGIME_SINTERING)
         logger(INFO, "Sintertype set to REGIME_SINTERING");
     else
         logger(ERROR, "Sintertype not understood");
 }
References CONSTANT_RATE, ERROR, INFO, logger, PARHAMI_MCKEEPING, REGIME_SINTERING, sinterType_, and TEMPERATURE_DEPENDENT_FRENKEL.
Referenced by setInverseSinterViscosity(), and setParhamiMcKeeping().
setStiffnessAndRestitutionCoefficient()
void SinterNormalSpecies::setStiffnessAndRestitutionCoefficient (Mdouble stiffness, Mdouble eps, Mdouble mass)
Sets k, disp such that it matches a given tc and eps for a collision of two copies of P.
Sets k, disp such that it matches a given tc and eps for a collision of two copies of P
Parameters
[in] stiffness stiffness
[in] eps restitution coefficient
[in] mass effective particle mass, \(\frac{2}{1/m1+1/m2}\)
 {
     loadingStiffness_ = stiffness;
     if (eps == 0.0)
     {
         dissipation_ = std::sqrt(2.0 * mass * stiffness);
     }
     else
     {
         dissipation_ =
                 -std::sqrt(2.0 * mass * stiffness / (constants::sqr_pi + mathsFunc::square(log(eps)))) * log(eps);
     }
     unloadingStiffnessMax_ = loadingStiffness_;
 }
References dissipation_, CRBond_Bessel::eps, loadingStiffness_, Eigen::bfloat16_impl::log(), constants::sqr_pi, sqrt(), mathsFunc::square(), and unloadingStiffnessMax_.
setSurfTension()
void SinterNormalSpecies::setSurfTension (Mdouble complianceZero)
 {
     if (surfTension < 0)
     {
         logger(ERROR, "SurfTension(%) argument should be non-negative!", surfTension);
     }
     surfTension_ = surfTension;
 }
References ERROR, logger, and surfTension_.
setTemperatureDependentSinterRate()
void SinterNormalSpecies::setTemperatureDependentSinterRate (std::function< double(double temperature)> temperatureDependentSinterRate)
 {
     temperatureDependentSinterRate_ = temperatureDependentSinterRate;
 }
References temperatureDependentSinterRate_.
setUnloadingStiffnessMax()
void SinterNormalSpecies::setUnloadingStiffnessMax (Mdouble unloadingStiffnessMax)
Sets the maximum unloading stiffness of the linear plastic-viscoelastic normal force.
Parameters
[in] unloadingStiffnessMax the maximum unloading stiffness of the linear plastic-viscoelastic normal force.
 {
     unloadingStiffnessMax_ = unloadingStiffnessMax;
 }
References unloadingStiffnessMax_.
Referenced by setPlasticParameters().
write()
void SinterNormalSpecies::write (std::ostream & os) const
Writes the species properties to an output stream.
Parameters
[out] output stream (typically the restart file)
 {
     os << " loadingStiffness " << loadingStiffness_;
     os << " maxUnloadingStiffness " << unloadingStiffnessMax_;
     os << " cohesionStiffness " << cohesionStiffness_;
     os << " maxPenetration " << penetrationDepthMax_;
     os << " dissipation " << dissipation_;
     os << " sinterAdhesion " << sinterAdhesion_;
     os << " inverseSinterViscosity " << inverseSinterViscosity_;
     os << " sinterRate " << sinterRate_;
     os << " complianceZero " << complianceZero_;
     os << " surfTension " << surfTension_;
     os << " constantC1 " << constantC1_;
     os << " separationDis " << separationDis_;
     os << " sinterType " << (unsigned) sinterType_;
 }
References cohesionStiffness_, complianceZero_, constantC1_, dissipation_, inverseSinterViscosity_, loadingStiffness_, penetrationDepthMax_, separationDis_, sinterAdhesion_, sinterRate_, sinterType_, surfTension_, and unloadingStiffnessMax_.
Member Data Documentation
cohesionStiffness_
Mdouble SinterNormalSpecies::cohesionStiffness_ private
the adhesive spring constant (k^c) for plastic deformations
Referenced by getCohesionStiffness(), mix(), read(), setCohesionStiffness(), SinterNormalSpecies(), and write().
complianceZero_
Mdouble SinterNormalSpecies::complianceZero_ private
Compliance 0, C_0, corresponds to the inverse of stiffness at the instantaneous time.
Referenced by getComplianceZero(), mix(), read(), setComplianceZero(), SinterNormalSpecies(), and write().
constantC1_
Mdouble SinterNormalSpecies::constantC1_ private
Material constant
Referenced by getConstantC1(), mix(), read(), setConstantC1(), SinterNormalSpecies(), and write().
dissipation_
Mdouble SinterNormalSpecies::dissipation_ private
linear dissipation coefficient
Referenced by computeTimeStep(), getCollisionTime(), getDissipation(), mix(), read(), setCollisionTimeAndRestitutionCoefficient(), setDissipation(), setStiffnessAndRestitutionCoefficient(), SinterNormalSpecies(), and write().
inverseSinterViscosity_
Mdouble SinterNormalSpecies::inverseSinterViscosity_ private
Determines sinter viscosity nu = contactRadius^4/inverseSinterViscosity_ in sinter rate: d(delta0)/dt = (fa+fep)/nu
Referenced by getInverseSinterViscosity(), mix(), read(), setInverseSinterViscosity(), SinterNormalSpecies(), and write().
loadingStiffness_
Mdouble SinterNormalSpecies::loadingStiffness_ private
(normal) spring constant (k_1)
Referenced by getCollisionTime(), getLoadingStiffness(), mix(), read(), setCollisionTimeAndRestitutionCoefficient(), setLoadingStiffness(), setStiffnessAndRestitutionCoefficient(), SinterNormalSpecies(), and write().
penetrationDepthMax_
Mdouble SinterNormalSpecies::penetrationDepthMax_ private
the depth (relative to the normalized radius) at which k_2^max is used (phi_f)
Referenced by getPenetrationDepthMax(), mix(), read(), setPenetrationDepthMax(), SinterNormalSpecies(), and write().
separationDis_
Mdouble SinterNormalSpecies::separationDis_ private
Separation distance comes from the fracture theory.
Referenced by getSeparationDis(), mix(), read(), setSeparationDis(), SinterNormalSpecies(), and write().
sinterAdhesion_
Mdouble SinterNormalSpecies::sinterAdhesion_ private
Determines sinter adhesion force fa=sinterAdhesion_*radius in sinter rate: d(delta0)/dt = (fa+fep)/nu
Referenced by getSinterAdhesion(), mix(), read(), setSinterAdhesion(), SinterNormalSpecies(), and write().
sinterRate_
Mdouble SinterNormalSpecies::sinterRate_ private
Determines sinter rate: d(delta0)/dt = (fa+fep)/nu
Referenced by getSinterRate(), read(), setSinterRate(), SinterNormalSpecies(), and write().
sinterType_
SINTERTYPE SinterNormalSpecies::sinterType_ private
sinterType options determin how the rate of sintering, d(equilibriumOverlap)/dt is computed PARHAMI_MCKEEPING: sinter rate given by (sinterAdhesion+normalForce)/sinterViscosity CONSTANT_RATE: sinter rate given by sinterRate
Referenced by getSinterType(), read(), setSinterForceAndTime(), setSinterType(), SinterNormalSpecies(), and write().
surfTension_
Mdouble SinterNormalSpecies::surfTension_ private
Material constant
Referenced by getSurfTension(), mix(), read(), setSurfTension(), SinterNormalSpecies(), and write().
temperatureDependentSinterRate_
std::function<double(double temperature)> SinterNormalSpecies::temperatureDependentSinterRate_ private
Initial value:
= [this](
            double temperature) { return sinterRate_; }
Referenced by getTemperatureDependentSinterRate(), and setTemperatureDependentSinterRate().
unloadingStiffnessMax_
Mdouble SinterNormalSpecies::unloadingStiffnessMax_ private
the maximum elastic constant (k_2^max) for plastic deformations
Referenced by computeTimeStep(), getUnloadingStiffnessMax(), mix(), read(), setCollisionTimeAndRestitutionCoefficient(), setStiffnessAndRestitutionCoefficient(), setUnloadingStiffnessMax(), SinterNormalSpecies(), and write().
The documentation for this class was generated from the following files:
SinterNormalSpecies.h
SinterNormalSpecies.cc