MercuryDPM: oomph::IdentityPreconditioner Class Reference
oomph::IdentityPreconditioner Class Reference
The Identity Preconditioner.
#include <preconditioner.h>
Public Member Functions
IdentityPreconditioner ()
IdentityPreconditioner (const IdentityPreconditioner &)=delete
Broken copy constructor.
void operator= (const IdentityPreconditioner &)=delete
Broken assignment operator.
virtual ~IdentityPreconditioner ()
Destructor (empty)
virtual void setup ()
setup method - just sets the distribution
virtual void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
void preconditioner_solve_transpose (const DoubleVector &r, DoubleVector &z)
Public Member Functions inherited from oomph::Preconditioner
Preconditioner ()
Constructor.
Preconditioner (const Preconditioner &)=delete
Broken copy constructor.
void operator= (const Preconditioner &)=delete
Broken assignment operator.
virtual ~Preconditioner ()
Destructor (empty)
void setup (DoubleMatrixBase *matrix_pt)
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
void enable_silent_preconditioner_setup ()
Set up the block preconditioner quietly!
void disable_silent_preconditioner_setup ()
Be verbose in the block preconditioner setup.
virtual void clean_up_memory ()
Clean up memory (empty). Generic interface function.
virtual DoubleMatrixBase * matrix_pt () const
Get function for matrix pointer.
virtual void set_matrix_pt (DoubleMatrixBase *matrix_pt)
Set the matrix pointer.
virtual const OomphCommunicator * comm_pt () const
Get function for comm pointer.
virtual void set_comm_pt (const OomphCommunicator *const comm_pt)
Set the communicator pointer.
double setup_time () const
Returns the time to setup the preconditioner.
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> &doftype_coarsen_map_coarse)
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
void build_distribution (const LinearAlgebraDistribution &dist)
Additional Inherited Members
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
Protected Attributes inherited from oomph::Preconditioner
bool Silent_preconditioner_setup
Boolean to indicate whether or not the build should be done silently.
std::ostream * Stream_pt
Pointer to the output stream – defaults to std::cout.
Detailed Description
The Identity Preconditioner.
Constructor & Destructor Documentation
IdentityPreconditioner() [1/2]
oomph::IdentityPreconditioner::IdentityPreconditioner () inline
 {}
IdentityPreconditioner() [2/2]
oomph::IdentityPreconditioner::IdentityPreconditioner (const IdentityPreconditioner &) delete
Broken copy constructor.
~IdentityPreconditioner()
virtual oomph::IdentityPreconditioner::~IdentityPreconditioner () inline virtual
Destructor (empty)
 {}
Member Function Documentation
operator=()
void oomph::IdentityPreconditioner::operator= (const IdentityPreconditioner &) delete
Broken assignment operator.
preconditioner_solve()
virtual void oomph::IdentityPreconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) inline virtual
Apply the preconditioner. This method should apply the preconditioner operator to the vector r and return the vector z.
Implements oomph::Preconditioner.
     {
 #ifdef PARANOID
       if (*r.distribution_pt() != *this->distribution_pt())
       {
         std::ostringstream error_message_stream;
         error_message_stream
           << "The r vector must have the same distribution as the "
              "preconditioner. "
           << "(this is the same as the matrix passed to setup())";
         throw OomphLibError(error_message_stream.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       if (z.built())
       {
         if (*z.distribution_pt() != *this->distribution_pt())
         {
           std::ostringstream error_message_stream;
           error_message_stream
             << "The z vector distribution has been setup; it must have the "
             << "same distribution as the r vector (and preconditioner).";
           throw OomphLibError(error_message_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
       }
 #endif
       // apply
       z = r;
     }
References oomph::DoubleVector::built(), oomph::DistributableLinearAlgebraObject::distribution_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and UniformPSDSelfTest::r.
Referenced by preconditioner_solve_transpose().
preconditioner_solve_transpose()
void oomph::IdentityPreconditioner::preconditioner_solve_transpose (const DoubleVector & r, DoubleVector & z) inline virtual
Apply the preconditioner. This method should apply the preconditioner operator to the vector r and return the vector z.
Reimplemented from oomph::Preconditioner.
     {
       // Applying the preconditioner to the transposed system is exactly the
       // same as applying the preconditioner to the original system
       preconditioner_solve(r, z);
     }
References preconditioner_solve(), and UniformPSDSelfTest::r.
setup()
virtual void oomph::IdentityPreconditioner::setup () inline virtual
setup method - just sets the distribution
Implements oomph::Preconditioner.
     {
       // first attempt to cast to DistributableLinearAlgebraObject
       DistributableLinearAlgebraObject* dist_matrix_pt =
         dynamic_cast<DistributableLinearAlgebraObject*>(matrix_pt());
       // if it is a distributable matrix
       if (dist_matrix_pt != 0)
       {
         // store the distribution
         this->build_distribution(dist_matrix_pt->distribution_pt());
       }
       // else it is not a distributable matrix
       else
       {
         // # of rows in the matrix
         unsigned n_row = matrix_pt()->nrow();
         LinearAlgebraDistribution dist(comm_pt(), n_row, false);
         this->build_distribution(dist);
       }
     }
References oomph::DistributableLinearAlgebraObject::build_distribution(), oomph::Preconditioner::comm_pt(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::Preconditioner::matrix_pt(), and oomph::DoubleMatrixBase::nrow().
The documentation for this class was generated from the following file:
preconditioner.h