MercuryDPM: oomph::TwoLayerPerturbedSpineMesh< ELEMENT > Class Template Reference
oomph::TwoLayerPerturbedSpineMesh< ELEMENT > Class Template Reference
#include <two_layer_perturbed_spine_mesh.template.h>
Public Member Functions
TwoLayerPerturbedSpineMesh (const unsigned &nx, const unsigned &ny1, const unsigned &ny2, const double &lx, const double &h1, const double &h2, SpineMesh *&base_mesh_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
TwoLayerPerturbedSpineMesh (const unsigned &nx, const unsigned &ny1, const unsigned &ny2, const double &lx, const double &h1, const double &h2, const bool &periodic_in_x, SpineMesh *&base_mesh_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
TwoLayerPerturbedSpineMesh (const unsigned &nx, const unsigned &ny1, const unsigned &ny2, const double &lx, const double &h1, const double &h2, const bool &periodic_in_x, const bool &build_mesh, SpineMesh *&base_mesh_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
void element_reorder ()
FiniteElement *& upper_layer_element_pt (const unsigned long &i)
Access functions for pointers to elements in upper layer.
FiniteElement *& lower_layer_element_pt (const unsigned long &i)
Access functions for pointers to elements in lower layer.
unsigned long nupper () const
Number of elements in upper layer.
unsigned long nlower () const
Number of elements in top layer.
void perturbed_spine_node_update (PerturbedSpineNode *spine_node_pt)
const unsigned & ny1 () const
Access function for number of elements in lower layer.
const unsigned & ny2 () const
Access function for number of elements in upper layer.
const void set_perturbation_to_nodal_positions_indices (const unsigned &cosine_index, const unsigned &sine_index)
Public Member Functions inherited from oomph::RectangularQuadMesh< ELEMENT >
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &xmin, const double &xmax, const double &ymin, const double &ymax, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly, const bool &periodic_in_x, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &xmin, const double &xmax, const double &ymin, const double &ymax, const bool &periodic_in_x, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
const unsigned & nx () const
Return number of elements in x direction.
const unsigned & ny () const
Return number of elements in y direction.
const double x_min () const
Return the minimum value of x coordinate.
const double x_max () const
Return the maximum value of x coordinate.
const double y_min () const
Return the minimum value of y coordinate.
const double y_max () const
Return the maximum value of y coordinate.
Public Member Functions inherited from oomph::QuadMeshBase
QuadMeshBase ()
Constructor (empty)
QuadMeshBase (const QuadMeshBase &node)=delete
Broken copy constructor.
void operator= (const QuadMeshBase &)=delete
Broken assignment operator.
virtual ~QuadMeshBase ()
Destructor (empty)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Public Member Functions inherited from oomph::PerturbedSpineMesh
virtual ~PerturbedSpineMesh ()
Destructor to clean up the memory allocated to the perturbed spines.
PerturbedSpine *const & perturbed_spine_pt (const unsigned long &i) const
Return the i-th perturbed spine in the mesh.
unsigned long nspine () const
Return the number of perturbed spines in the mesh.
void add_perturbed_spine_pt (PerturbedSpine *const &spine_pt)
Add a perturbed spine to the mesh.
PerturbedSpineNode * node_pt (const unsigned long &n)
Return a pointer to the n-th global PerturbedSpineNode.
PerturbedSpineNode * element_node_pt (const unsigned long &e, const unsigned &n)
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign equation numbers for perturbed spines.
void node_update (const bool &update_all_solid_nodes=false)
void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Overload the dump function so that the spine data is dumped.
void read (std::ifstream &restart_file)
Overload the read function so that the spine data is also read.
Protected Member Functions
double x_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode)
double y_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode)
void spine_node_update_lower (PerturbedSpineNode *spine_node_pt)
Update function for the lower part of the domain.
void spine_node_update_upper (PerturbedSpineNode *spine_node_pt)
Update function for the upper part of the domain.
virtual void build_two_layer_mesh (TimeStepper *time_stepper_pt)
Protected Member Functions inherited from oomph::RectangularQuadMesh< ELEMENT >
void build_mesh (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Generic mesh construction function: contains all the hard work.
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &xmin, const double &xmax, const double &ymin, const double &ymax, const bool &periodic_in_x, const bool &build, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes
unsigned Ny1
Number of elements in lower layer.
unsigned Ny2
Number of elements in upper layer.
double H1
Height of the lower layer.
double H2
Height of the upper layer.
SpineMesh * Base_mesh_pt
Pointer to corresponding mesh of base state problem.
int YC_index
int YS_index
Vector< FiniteElement * > Lower_layer_element_pt
Vector of pointers to element in the lower layer.
Vector< FiniteElement * > Upper_layer_element_pt
Vector of pointers to element in the upper layer.
Protected Attributes inherited from oomph::RectangularQuadMesh< ELEMENT >
unsigned Nx
Nx: number of elements in x-direction.
unsigned Ny
Ny: number of elements in y-direction.
unsigned Np
Np: number of (linear) points in the element.
double Xmin
Minimum value of x coordinate.
double Xmax
Maximum value of x coordinate.
double Ymin
Minimum value of y coordinate.
double Ymax
Maximum value of y coordinate.
bool Xperiodic
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Protected Attributes inherited from oomph::PerturbedSpineMesh
Vector< PerturbedSpine * > PerturbedSpine_pt
A PerturbedSpine mesh contains a Vector of pointers to perturbed spines.
Static Private Attributes
static int Perturbation_to_nodal_position_indices_not_set_up
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Detailed Description
template<class ELEMENT>
class oomph::TwoLayerPerturbedSpineMesh< ELEMENT >
Two-layer spine mesh class derived from standard 2D mesh. The mesh contains two layers of spinified fluid elements (of type ELEMENT; e.g PerturbedSpineElement<QCrouzeixRaviartElement<2>) and an intermediate interface layer of corresponding PerturbedSpine interface elements, of type INTERFACE_ELEMENT, e.g. PerturbedSpineLineFluidInterfaceElement<ELEMENT> for 2D planar problems.
Constructor & Destructor Documentation
TwoLayerPerturbedSpineMesh() [1/3]
template<class ELEMENT > oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::TwoLayerPerturbedSpineMesh (const unsigned & nx, const unsigned & ny1, const unsigned & ny2, const double & lx, const double & h1, const double & h2, SpineMesh *& base_mesh_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass in:
number of elements in x-direction
number of elements in y-direction in bottom layer
number of elements in y-direction in top layer
axial length
height of bottom layer
height of top layer
pointer to the base mesh (where we compute the base flow)
pointer to timestepper (defaults to Steady timestepper)
Constructor for 2D perturbed spine mesh: Pass in:
number of elements in x-direction
number of elements in y-direction in bottom layer
number of elements in y-direction in top layer
axial length
height of bottom layer
height of top layer
pointer to the base mesh (where we compute the base flow)
pointer to timestepper (defaults to Steady timestepper)
The mesh contains two layers of elements (of type ELEMENT; e.g PerturbedSpineElement<QCrouzeixRaviartElement<2>) and an interfacial layer of corresponding PerturbedSpine interface elements of type INTERFACE_ELEMENT, e.g. PerturbedSpineLineFluidInterfaceElement<ELEMENT> for 2D planar problems.
We set YC_index and YS_index, which store the indices at which the cosine and sine parts (respectively) of the perturbation to the nodal y-position are stored in the bulk element, to a "magic" number which indicates that the indices have not been set up yet.
                                                           :
   RectangularQuadMesh<ELEMENT>(nx,ny1+ny2,0.0,lx,0.0,h1+h2,false,false,
                                time_stepper_pt),
   Base_mesh_pt(base_mesh_pt),
   YC_index(Perturbation_to_nodal_position_indices_not_set_up),
   YS_index(Perturbation_to_nodal_position_indices_not_set_up)
  {
   // We've called the "generic" constructor for the RectangularQuadMesh
   // which doesn't do much...
   // Now set up the parameters that characterise the mesh geometry
   // then call the build function
   // Number of elements in bottom and top layers
   Ny1 = ny1;
   Ny2 = ny2;
   // Set height of upper and lower layers
   H1 = h1;
   H2 = h2;
   // Now build the mesh:
   build_two_layer_mesh(time_stepper_pt);
  }
TwoLayerPerturbedSpineMesh() [2/3]
template<class ELEMENT > oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::TwoLayerPerturbedSpineMesh (const unsigned & nx, const unsigned & ny1, const unsigned & ny2, const double & lx, const double & h1, const double & h2, const bool & periodic_in_x, SpineMesh *& base_mesh_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass in:
number of elements in x-direction
number of elements in y-direction in bottom layer
number of elements in y-direction in top layer
axial length
height of bottom layer
height of top layer
boolean flag to make the mesh periodic in the x-direction
pointer to the base mesh (where we compute the base flow)
pointer to timestepper (defaults to Steady timestepper)
Constructor for 2D perturbed spine mesh: Pass in:
number of elements in x-direction
number of elements in y-direction in bottom layer
number of elements in y-direction in top layer
axial length
height of bottom layer
height of top layer
boolean flag to make the mesh periodic in the x-direction
pointer to the base mesh (where we compute the base flow)
pointer to timestepper (defaults to Steady timestepper)
The mesh contains two layers of elements (of type ELEMENT; e.g PerturbedSpineElement<QCrouzeixRaviartElement<2>) and an interfacial layer of corresponding PerturbedSpine interface elements of type INTERFACE_ELEMENT, e.g. PerturbedSpineLineFluidInterfaceElement<ELEMENT> for 2D planar problems.
We set YC_index and YS_index, which store the indices at which the cosine and sine parts (respectively) of the perturbation to the nodal y-position are stored in the bulk element, to a "magic" number which indicates that the indices have not been set up yet.
                                                           :
   RectangularQuadMesh<ELEMENT >(nx,ny1+ny2,0.0,lx,0.0,h1+h2,
                                 periodic_in_x,false,time_stepper_pt),
   Base_mesh_pt(base_mesh_pt),
   YC_index(Perturbation_to_nodal_position_indices_not_set_up),
   YS_index(Perturbation_to_nodal_position_indices_not_set_up)
  {
   // We've called the "generic" constructor for the RectangularQuadMesh
   // which doesn't do much...
   // Now set up the parameters that characterise the mesh geometry
   // then call the constructor
   // Number of elements in bottom and top layers
   Ny1 = ny1;
   Ny2 = ny2;
   // Set height of upper and lower layers
   H1 = h1;
   H2 = h2;
   // Now build the mesh:
   build_two_layer_mesh(time_stepper_pt);
  }
References oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::build_two_layer_mesh(), oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::H1, oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::H2, oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::ny1(), oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::Ny1, oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::ny2(), and oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::Ny2.
TwoLayerPerturbedSpineMesh() [3/3]
template<class ELEMENT > oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::TwoLayerPerturbedSpineMesh (const unsigned & nx, const unsigned & ny1, const unsigned & ny2, const double & lx, const double & h1, const double & h2, const bool & periodic_in_x, const bool & build_mesh, SpineMesh *& base_mesh_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass in:
number of elements in x-direction
number of elements in y-direction in bottom layer
number of elements in y-direction in top layer
axial length
height of bottom layer
height of top layer
boolean flag to make the mesh periodic in the x-direction
boolean flag to specify whether or not to call the "build_two_layer_mesh" function
pointer to the base mesh (where we compute the base flow)
pointer to timestepper (defaults to Steady timestepper)
Constructor for 2D perturbed spine mesh: Pass in:
number of elements in x-direction
number of elements in y-direction in bottom layer
number of elements in y-direction in top layer
axial length
height of bottom layer
height of top layer
boolean flag to make the mesh periodic in the x-direction
boolean flag to specify whether or not to call the "build_two_layer_mesh" function
pointer to the base mesh (where we compute the base flow)
pointer to timestepper (defaults to Steady timestepper)
The mesh contains two layers of elements (of type ELEMENT; e.g PerturbedSpineElement<QCrouzeixRaviartElement<2>) and an interfacial layer of corresponding PerturbedSpine interface elements of type INTERFACE_ELEMENT, e.g. PerturbedSpineLineFluidInterfaceElement<ELEMENT> for 2D planar problems.
We set YC_index and YS_index, which store the indices at which the cosine and sine parts (respectively) of the perturbation to the nodal y-position are stored in the bulk element, to a "magic" number which indicates that the indices have not been set up yet.
                                                           :
   RectangularQuadMesh<ELEMENT >(nx,ny1+ny2,0.0,lx,0.0,h1+h2,
                                 periodic_in_x,false,time_stepper_pt),
   Base_mesh_pt(base_mesh_pt),
   YC_index(Perturbation_to_nodal_position_indices_not_set_up),
   YS_index(Perturbation_to_nodal_position_indices_not_set_up)
  {
   // We've called the "generic" constructor for the RectangularQuadMesh
   // which doesn't do much...
   // Now set up the parameters that characterise the mesh geometry
   // then call the constructor
   // Number of elements in bottom and top layers
   Ny1 = ny1;
   Ny2 = ny2;
   // Set height of upper and lower layers
   H1 = h1;
   H2 = h2;
   // Only build the mesh here if build_mesh=true
   // This is useful when calling this constructor from a derived class
   // (such as PatrickAxisym2x6TwoLayerPerturbedSpineMesh) where the mesh
   // building needs to be called from *its* constructor and this constructor
   // is only used to pass arguments to the RectangularQuadMesh constructor.
   if(build_mesh) { build_two_layer_mesh(time_stepper_pt); }
 }
References oomph::RectangularQuadMesh< ELEMENT >::build_mesh(), oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::build_two_layer_mesh(), oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::H1, oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::H2, oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::ny1(), oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::Ny1, oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::ny2(), and oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::Ny2.
Member Function Documentation
build_two_layer_mesh()
template<class ELEMENT > void oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::build_two_layer_mesh (TimeStepper * time_stepper_pt) protected virtual
Helper function to actually build the two-layer spine mesh (called from various constructors)
Helper function that actually builds the two-layer spine mesh based on the parameters set in the various constructors
  {
   // Build the underlying quad mesh:
   RectangularQuadMesh<ELEMENT >::build_mesh(time_stepper_pt);
   // Set up the pointers to elements in the upper and lower fluid
   // ------------------------------------------------------------
   // Calculate numbers of nodes in upper and lower regions
   const unsigned long n_lower = this->Nx*Ny1;
   const unsigned long n_upper = this->Nx*Ny2;
   // Loop over lower elements and push back
   Lower_layer_element_pt.reserve(n_lower);
   for(unsigned e=0;e<n_lower;e++)
    {
     Lower_layer_element_pt.push_back(this->finite_element_pt(e));
    }
   // Loop over upper elements and push back
   Upper_layer_element_pt.reserve(n_upper);
   for(unsigned e=n_lower;e<(n_lower+n_upper);e++)
    {
     Upper_layer_element_pt.push_back(this->finite_element_pt(e));
    }
   // Allocate memory for the spines and fractions along spines
   // ---------------------------------------------------------
   // Read out number of linear points in the element
   const unsigned n_p =
    dynamic_cast<ELEMENT*>(finite_element_pt(0))->nnode_1d();
   // Allocate store for the spines:
   if(this->Xperiodic) { PerturbedSpine_pt.reserve((n_p-1)*this->Nx); }
   else { PerturbedSpine_pt.reserve((n_p-1)*this->Nx+1); }
   // FIRST SPINE
   // -----------
   // Element 0
   // Node 0
   // Create a perturbed spine and pass it a pointer to the corresponding
   // base spine
   PerturbedSpine* new_perturbed_spine_pt =
    new PerturbedSpine(time_stepper_pt,Base_mesh_pt->spine_pt(0));
   PerturbedSpine_pt.push_back(new_perturbed_spine_pt);
   // Get pointer to node
   PerturbedSpineNode* nod_pt = element_node_pt(0,0);
   // Set the pointer to the spine
   nod_pt->perturbed_spine_pt() = new_perturbed_spine_pt;
   // Set the fraction
   nod_pt->fraction() = 0.0;
   // Pointer to the mesh that implements the update fct
   nod_pt->spine_mesh_pt() = this;
   // ID of update function within this mesh: 0 = lower; 1 = upper
   nod_pt->node_update_fct_id() = 0;
   // Pass the spine a pointer to this node
   new_perturbed_spine_pt->node_at_bottom_of_spine_pt() = nod_pt;
   // Loop vertically along the spine
   // Loop over the elements in fluid 1
   for(unsigned long i=0;i<Ny1;i++)
    {
     // Loop over the vertical nodes, apart from the first
     for(unsigned l1=1;l1<n_p;l1++)
      {
       // Get pointer to node
       PerturbedSpineNode* nod_pt=element_node_pt(i*this->Nx,l1*n_p);
       // Set the pointer to the spine
       nod_pt->perturbed_spine_pt() = new_perturbed_spine_pt;
       // Set the fraction
       nod_pt->fraction() = (nod_pt->x(1)-this->Ymin)/(H1);
       // Pointer to the mesh that implements the update fct
       nod_pt->spine_mesh_pt() = this;
       // ID of update function within this mesh: 0 = lower; 1 = upper
       nod_pt->node_update_fct_id() = 0;
      }
    }
   // Loop over the elements in fluid 2
   for(unsigned long i=0;i<Ny2;i++)
    {
     // Loop over vertical nodes, apart from the first
     for(unsigned l1=1;l1<n_p;l1++)
      {
       // Get pointer to node
       PerturbedSpineNode* nod_pt=element_node_pt((Ny1+i)*this->Nx,l1*n_p);
       //Set the pointer to the spine
       nod_pt->perturbed_spine_pt() = new_perturbed_spine_pt;
       //Set the fraction
       nod_pt->fraction() =(nod_pt->x(1)-(this->Ymin+H1))/(H2);
       // Pointer to the mesh that implements the update fct
       nod_pt->spine_mesh_pt() = this;
       // ID of update function within this mesh: 0 = lower; 1 = upper
       nod_pt->node_update_fct_id() = 1;
       // Pass the spine a pointer to the "top" node
       if(i==(Ny2-1) && l1==(n_p-1))
        {
         new_perturbed_spine_pt->node_at_top_of_spine_pt() = nod_pt;
        }
      }
    }
   //LOOP OVER OTHER SPINES
   //----------------------
   //Now loop over the elements horizontally
   for(unsigned long j=0;j<this->Nx;j++)
    {
     //Loop over the nodes in the elements horizontally, ignoring
     //the first column
     // Last spine needs special treatment in x-periodic meshes:
     unsigned n_pmax=n_p;
     if ((this->Xperiodic)&&(j==this->Nx-1)) n_pmax=n_p-1;
     for(unsigned l2=1;l2<n_pmax;l2++)
      {
       // Create a perturbed spine and pass it a pointer to the
       // corresponding base spine
       new_perturbed_spine_pt =
        new PerturbedSpine(time_stepper_pt,
                           Base_mesh_pt->spine_pt(((n_pmax-1)*j)+l2));
       PerturbedSpine_pt.push_back(new_perturbed_spine_pt);
       // Get pointer to node
       PerturbedSpineNode* nod_pt=element_node_pt(j,l2);
       //Set the pointer to the spine
       nod_pt->perturbed_spine_pt() = new_perturbed_spine_pt;
       //Set the fraction
       nod_pt->fraction() = 0.0;
       // Pointer to the mesh that implements the update fct
       nod_pt->spine_mesh_pt() = this;
       // ID of update function within this mesh: 0 = lower; 1 = upper
       nod_pt->node_update_fct_id() = 0;
      // Pass the spine a pointer to this node
      new_perturbed_spine_pt->node_at_bottom_of_spine_pt() = nod_pt;
      //Loop vertically along the spine
      //Loop over the elements in fluid 1
      for(unsigned long i=0;i<Ny1;i++)
       {
        //Loop over the vertical nodes, apart from the first
        for(unsigned l1=1;l1<n_p;l1++)
         {
          // Get pointer to node
          PerturbedSpineNode* nod_pt=element_node_pt(i*this->Nx+j,l1*n_p+l2);
          //Set the pointer to the spine
          nod_pt->perturbed_spine_pt() = new_perturbed_spine_pt;
          //Set the fraction
          nod_pt->fraction() = (nod_pt->x(1)-this->Ymin)/H1;
          // Pointer to the mesh that implements the update fct
          nod_pt->spine_mesh_pt() = this;
          // ID of update function within this mesh: 0 = lower; 1 = upper
          nod_pt->node_update_fct_id() = 0;
         }
       }
      //Loop over the elements in fluid 2
      for(unsigned long i=0;i<Ny2;i++)
       {
        //Loop over vertical nodes, apart from the first
        for(unsigned l1=1;l1<n_p;l1++)
         {
          // Get pointer to node
          PerturbedSpineNode* nod_pt=element_node_pt((Ny1+i)*this->Nx+j,l1*n_p+l2);
          //Set the pointer to the spine
          nod_pt->perturbed_spine_pt() = new_perturbed_spine_pt;
          //Set the fraction
          nod_pt->fraction() = (nod_pt->x(1)-(this->Ymin+H1))/H2;
          // Pointer to the mesh that implements the update fct
          nod_pt->spine_mesh_pt() = this;
          // ID of update function within this mesh: 0 = lower; 1 = upper
          nod_pt->node_update_fct_id() = 1;
          // Pass the spine a pointer to the "top" node
          if(i==(Ny2-1) && l1==(n_p-1))
           {
            new_perturbed_spine_pt->node_at_top_of_spine_pt() = nod_pt;
           }
         }
       }
     }
   }
  // Last spine needs special treatment for periodic meshes
  // because it's the same as the first one...
  if (this->Xperiodic)
   {
    // Last spine is the same as first one...
    PerturbedSpine* final_perturbed_spine_pt=PerturbedSpine_pt[0];
    // Get pointer to node
    PerturbedSpineNode* nod_pt=element_node_pt((this->Nx-1),(n_p-1));
    //Set the pointer to the spine
    nod_pt->perturbed_spine_pt() = final_perturbed_spine_pt;
    //Set the fraction to be the same as for the nodes on the first row
    nod_pt->fraction() = element_node_pt(0,0)->fraction();
    // Pointer to the mesh that implements the update fct
    nod_pt->spine_mesh_pt() = element_node_pt(0,0)->spine_mesh_pt();
    // ID of update function within this mesh: 0 = lower; 1 = upper
    nod_pt->node_update_fct_id() = element_node_pt(0,0)->node_update_fct_id();
    //Now loop vertically along the spine
    for(unsigned i=0;i<(Ny1+Ny2);i++)
     {
      //Loop over the vertical nodes, apart from the first
      for(unsigned l1=1;l1<n_p;l1++)
       {
        // Get pointer to node
        PerturbedSpineNode* nod_pt =
         element_node_pt(i*this->Nx+(this->Nx-1),l1*n_p+(n_p-1));
        //Set the pointer to the spine
        nod_pt->perturbed_spine_pt() = final_perturbed_spine_pt;
        //Set the fraction to be the same as in first row
        nod_pt->fraction() = element_node_pt(i*this->Nx,l1*n_p)->fraction();
        // ID of update function within this mesh: 0 = lower; 1 = upper
        nod_pt->node_update_fct_id() =
         element_node_pt(i*this->Nx,l1*n_p)->node_update_fct_id();
        // Pointer to the mesh that implements the update fct
        nod_pt->spine_mesh_pt() = element_node_pt(i*this->Nx,l1*n_p)
         ->spine_mesh_pt();
       }
     }
   }
 }
References oomph::RectangularQuadMesh< ELEMENT >::build_mesh(), e(), and GlobalParameters::Nx.
Referenced by oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::TwoLayerPerturbedSpineMesh().
element_reorder()
template<class ELEMENT > void oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::element_reorder virtual
Reorder the elements so we loop over them vertically first (advantageous in "wide" domains if a frontal solver is used).
Reorder the elements, so we loop over them vertically first (advantageous in "wide" domains if a frontal solver is used).
Reimplemented from oomph::RectangularQuadMesh< ELEMENT >.
 {
  unsigned Nx = this->Nx;
  //Find out how many elements there are
  unsigned long Nelement = nelement();
  //Find out how many fluid elements there are
  unsigned long Nfluid = Nx*(Ny1+Ny2);
  //Create a dummy array of elements
  Vector<FiniteElement *> dummy;
  //Loop over the elements in horizontal order
  for(unsigned long j=0;j<Nx;j++)
   {
    //Loop over the elements in lower layer vertically
    for(unsigned long i=0;i<Ny1;i++)
     {
      //Push back onto the new stack
      dummy.push_back(finite_element_pt(Nx*i + j));
     }
    //Push back the line element onto the stack
    dummy.push_back(finite_element_pt(Nfluid+j));
    //Loop over the elements in upper layer vertically
    for(unsigned long i=Ny1;i<(Ny1+Ny2);i++)
     {
      //Push back onto the new stack
      dummy.push_back(finite_element_pt(Nx*i + j));
     }
   }
  //Now copy the reordered elements into the element_pt
  for(unsigned long e=0;e<Nelement;e++)
   {
    Element_pt[e] = dummy[e];
   }
 }
References e(), i, j, and GlobalParameters::Nx.
lower_layer_element_pt()
template<class ELEMENT > FiniteElement* & oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::lower_layer_element_pt (const unsigned long & i) inline
Access functions for pointers to elements in lower layer.
   { return Lower_layer_element_pt[i]; }
References i, and oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::Lower_layer_element_pt.
Referenced by PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem().
nlower()
template<class ELEMENT > unsigned long oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::nlower () const inline
Number of elements in top layer.
 { return Lower_layer_element_pt.size(); }
References oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::Lower_layer_element_pt.
Referenced by PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem().
nupper()
template<class ELEMENT > unsigned long oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::nupper () const inline
Number of elements in upper layer.
 { return Upper_layer_element_pt.size(); }
References oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::Upper_layer_element_pt.
Referenced by PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem().
ny1()
template<class ELEMENT > const unsigned& oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::ny1 () const inline
Access function for number of elements in lower layer.
 { return Ny1; }
References oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::Ny1.
Referenced by oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::TwoLayerPerturbedSpineMesh().
ny2()
template<class ELEMENT > const unsigned& oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::ny2 () const inline
Access function for number of elements in upper layer.
 { return Ny2; }
References oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::Ny2.
Referenced by oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::TwoLayerPerturbedSpineMesh().
perturbed_spine_node_update()
template<class ELEMENT > void oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::perturbed_spine_node_update (PerturbedSpineNode * spine_node_pt) inline virtual
General node update function implements pure virtual function defined in PerturbedSpineMesh base class and performs specific update actions, depending on the node update fct id stored for each node. This function sets the nodal positions to be the same as in the base state problem through the perturbed spine's pointer to its corresponding base spine. Additionally this function updates the perturbations to the nodal positions, which are stored as (pinned) values at the nodes.
Implements oomph::PerturbedSpineMesh.
  {
   unsigned id=spine_node_pt->node_update_fct_id();
   switch(id)
    {
    case 0:
     spine_node_update_lower(spine_node_pt);
     break;
    case 1:
     spine_node_update_upper(spine_node_pt);
     break;
    default:
     std::ostringstream error_message;
     error_message << "Unknown id passed to perturbed_spine_node_update " << id
                   << std::endl;
     throw OomphLibError(error_message.str(),
                         "TwoLayerPerturbedSpineMesh::perturbed_spine_node_update()",
                         OOMPH_EXCEPTION_LOCATION);
    }
  }
References oomph::PerturbedSpineNode::node_update_fct_id(), OOMPH_EXCEPTION_LOCATION, oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::spine_node_update_lower(), and oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::spine_node_update_upper().
set_perturbation_to_nodal_positions_indices()
template<class ELEMENT > const void oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::set_perturbation_to_nodal_positions_indices (const unsigned & cosine_index, const unsigned & sine_index) inline
Set up the internal data YC_index and YS_index, which store the indices at which the perturbations to the nodal y-position are stored in the bulk element
  {
   YC_index = cosine_index;
   YS_index = sine_index;
  }
References oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::YC_index, and oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::YS_index.
Referenced by PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem().
spine_node_update_lower()
template<class ELEMENT > void oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::spine_node_update_lower (PerturbedSpineNode * spine_node_pt) inline protected
Update function for the lower part of the domain.
   {
    // Get fraction along the spine
    const double w = spine_node_pt->fraction();
    // Get base spine height
    const double h =
     spine_node_pt->perturbed_spine_pt()->base_spine_pt()->height();
    // Set the nodal y-position
    spine_node_pt->x(1) = this->Ymin + w*h;
    // Get perturbed spine height (cosine and sine parts)
    const double HC = spine_node_pt->perturbed_spine_pt()->height(0);
    const double HS = spine_node_pt->perturbed_spine_pt()->height(1);
    // Set the perturbation (cosine and sine parts) to the nodal
    // y-position. Note that YC_index and YS_index are the indices at
    // which the perturbations to the nodal y-position are stored in
    // the bulk elements
    if(YC_index>=0)
     {
      spine_node_pt->set_value(YC_index,w*HC);
     }
    else
     {
      std::ostringstream error_message;
      error_message << "The cosine part of the perturbation to the nodal\n"
                    << "y-position has not been set up." << std::endl;
      throw OomphLibError(
       error_message.str(),
       "TwoLayerPerturbedSpineMesh::spine_node_update_lower(...)",
       OOMPH_EXCEPTION_LOCATION);
     }
    if(YS_index>=0)
     {
      spine_node_pt->set_value(YS_index,w*HS);
     }
    else
     {
      std::ostringstream error_message;
      error_message << "The sine part of the perturbation to the nodal\n"
                    << "y-position has not been set up." << std::endl;
      throw OomphLibError(
       error_message.str(),
       "TwoLayerPerturbedSpineMesh::spine_node_update_lower(...)",
       OOMPH_EXCEPTION_LOCATION);
     }
   }
References oomph::PerturbedSpine::base_spine_pt(), oomph::PerturbedSpineNode::fraction(), oomph::Spine::height(), oomph::PerturbedSpine::height(), OOMPH_EXCEPTION_LOCATION, oomph::PerturbedSpineNode::perturbed_spine_pt(), oomph::Data::set_value(), w, oomph::Node::x(), oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::YC_index, oomph::RectangularQuadMesh< ELEMENT >::Ymin, and oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::YS_index.
Referenced by oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::perturbed_spine_node_update().
spine_node_update_upper()
template<class ELEMENT > void oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::spine_node_update_upper (PerturbedSpineNode * spine_node_pt) inline protected
Update function for the upper part of the domain.
   {
    // Get fraction along the spine
    const double w = spine_node_pt->fraction();
    // Get base spine height
    const double h =
     spine_node_pt->perturbed_spine_pt()->base_spine_pt()->height();
    // Set the nodal y-position
    spine_node_pt->x(1) = (this->Ymin + h) + w*(this->Ymax - (this->Ymin+h));
    // Get perturbed spine height (cosine and sine parts)
    const double HC = spine_node_pt->perturbed_spine_pt()->height(0);
    const double HS = spine_node_pt->perturbed_spine_pt()->height(1);
    // Set the perturbation (cosine and sine parts) to the nodal
    // y-position. Note that YC_index and YS_index are the indices at
    // which the perturbations to the nodal y-position are stored in
    // the bulk elements
    if(YC_index>=0)
     {
      // To see analysis of why this is okay, see the pdf file
      // "perturbed_node_update_procedure.pdf" (emailed to myself)
      spine_node_pt->set_value(YC_index,HC*(1.0-w));
     }
    else
     {
      std::ostringstream error_message;
      error_message << "The cosine part of the perturbation to the nodal\n"
                    << "y-position has not been set up." << std::endl;
      throw OomphLibError(
       error_message.str(),
       "TwoLayerPerturbedSpineMesh::spine_node_update_upper(...)",
       OOMPH_EXCEPTION_LOCATION);
     }
    if(YS_index>=0)
     {
      // To see analysis of why this is okay, see the pdf file
      // "perturbed_node_update_procedure.pdf" (emailed to myself)
      spine_node_pt->set_value(YS_index,HS*(1.0-w));
     }
    else
     {
      std::ostringstream error_message;
      error_message << "The sine part of the perturbation to the nodal\n"
                    << "y-position has not been set up." << std::endl;
      throw OomphLibError(
       error_message.str(),
       "TwoLayerPerturbedSpineMesh::spine_node_update_upper(...)",
       OOMPH_EXCEPTION_LOCATION);
     }
   }
References oomph::PerturbedSpine::base_spine_pt(), oomph::PerturbedSpineNode::fraction(), oomph::Spine::height(), oomph::PerturbedSpine::height(), OOMPH_EXCEPTION_LOCATION, oomph::PerturbedSpineNode::perturbed_spine_pt(), oomph::Data::set_value(), w, oomph::Node::x(), oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::YC_index, oomph::RectangularQuadMesh< ELEMENT >::Ymax, oomph::RectangularQuadMesh< ELEMENT >::Ymin, and oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::YS_index.
Referenced by oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::perturbed_spine_node_update().
upper_layer_element_pt()
template<class ELEMENT > FiniteElement* & oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::upper_layer_element_pt (const unsigned long & i) inline
Access functions for pointers to elements in upper layer.
   { return Upper_layer_element_pt[i]; }
References i, and oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::Upper_layer_element_pt.
Referenced by PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem().
x_spacing_function()
template<class ELEMENT > double oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::x_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode) protected virtual
The spacing function for the x co-ordinates with two regions.
The spacing function for the x co-ordinate, which is the same as the default function.
Reimplemented from oomph::RectangularQuadMesh< ELEMENT >.
  {
   // Calculate the values of equal increments in nodal values
   double xstep = (this->Xmax-this->Xmin)/((this->Np-1)*this->Nx);
   // Return the appropriate value
   return (this->Xmin + xstep*((this->Np-1)*xelement + xnode));
  }
References GlobalParameters::Nx.
y_spacing_function()
template<class ELEMENT > double oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::y_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode) protected virtual
The spacing function for the y co-ordinates with three regions in each fluid.
The spacing function for the y co-ordinates, which splits the region into two regions (1 and 2), according to the heights H1 and H2, with Ny1 and Ny2 elements respectively.
Reimplemented from oomph::RectangularQuadMesh< ELEMENT >.
  {
   // Set up some spacing parameters
   // The lower region a starts at Ymin
   double Ymin = RectangularQuadMesh<ELEMENT >::Ymin;
   // The upper region a ends at Ymax
   double Ymax = RectangularQuadMesh<ELEMENT >::Ymax;
   // Number of nodes per element
   unsigned n_p = RectangularQuadMesh<ELEMENT >::Np;
   // The lower region starts at Ymin
   double y1init = Ymin;
   // The upper region starts at H1 - Ymin
   double y2init = H1 - Ymin;
   // Calculate the space between each node in each region, assuming
   // uniform spacing
   // Lower region has a length (H1-Ymin)
   double y1step = (H1-Ymin)/((n_p-1)*Ny1);
   // Upper region has a length (Ymax-H1)
   double y2step = (Ymax-H1)/((n_p-1)*Ny2);
   // Now return the actual node position (different in the two regions)
   if(yelement < Ny1)
    {
     return (y1init + y1step*((n_p-1)*yelement + ynode));
    }
   else
    {
     return (y2init + y2step*((n_p-1)*(yelement-Ny1) + ynode));
    }
  }
Member Data Documentation
Base_mesh_pt
template<class ELEMENT > SpineMesh* oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::Base_mesh_pt protected
Pointer to corresponding mesh of base state problem.
H1
template<class ELEMENT > double oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::H1 protected
Height of the lower layer.
Referenced by oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::TwoLayerPerturbedSpineMesh().
H2
template<class ELEMENT > double oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::H2 protected
Height of the upper layer.
Referenced by oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::TwoLayerPerturbedSpineMesh().
Lower_layer_element_pt
template<class ELEMENT > Vector<FiniteElement *> oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::Lower_layer_element_pt protected
Vector of pointers to element in the lower layer.
Referenced by oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::lower_layer_element_pt(), and oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::nlower().
Ny1
template<class ELEMENT > unsigned oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::Ny1 protected
Number of elements in lower layer.
Referenced by oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::ny1(), and oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::TwoLayerPerturbedSpineMesh().
Ny2
template<class ELEMENT > unsigned oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::Ny2 protected
Number of elements in upper layer.
Referenced by oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::ny2(), and oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::TwoLayerPerturbedSpineMesh().
Perturbation_to_nodal_position_indices_not_set_up
template<class ELEMENT > int oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::Perturbation_to_nodal_position_indices_not_set_up static private
Static "magic" number that indicates that the indices at which the perturbations to the nodal y-positions are stored have not been set up
Upper_layer_element_pt
template<class ELEMENT > Vector<FiniteElement *> oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::Upper_layer_element_pt protected
Vector of pointers to element in the upper layer.
Referenced by oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::nupper(), and oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::upper_layer_element_pt().
YC_index
template<class ELEMENT > int oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::YC_index protected
Index at which the cosine part of the perturbation to the nodal y-position is stored in the bulk element. The mesh needs to know this so that the value of the nodal position perturbation can be updated during the "perturbed spine node update" procedure
Referenced by oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::set_perturbation_to_nodal_positions_indices(), oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::spine_node_update_lower(), and oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::spine_node_update_upper().
YS_index
template<class ELEMENT > int oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::YS_index protected
Index at which the sine part of the perturbation to the nodal y-position is stored in the bulk element. The mesh needs to know this so that the value of the nodal position perturbation can be updated during the "perturbed spine node update" procedure
Referenced by oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::set_perturbation_to_nodal_positions_indices(), oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::spine_node_update_lower(), and oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::spine_node_update_upper().
The documentation for this class was generated from the following files:
two_layer_perturbed_spine_mesh.template.h
two_layer_perturbed_spine_mesh.template.cc