MercuryDPM: Detail Namespace Reference
Detail Namespace Reference
Classes
class VTKPointDescriptorEntry
class VTKPointDescriptorEntryImpl
Functions
template<typename V >
std::enable_if< std::is_floating_point< V >::value, std::string >::type toVTKDataType ()
template<typename V >
std::enable_if< std::is_integral< V >::value &&std::is_unsigned< V >::value, std::string >::type toVTKDataType ()
template<typename V >
std::enable_if< std::is_integral< V >::value &&std::is_signed< V >::value, std::string >::type toVTKDataType ()
template<typename V >
std::enable_if< std::is_array< V >::value, std::string >::type toVTKDataType ()
template<typename V >
V round (V in)
template<>
double round (double in)
template<typename T , typename V >
std::enable_if< std::is_array< V >::value||std::is_pointer< V >::value, void >::type emitProxy (std::ostream &out, const T &t, std::size_t nComponents, V T::*member)
This function actually writes the correct datatype to ostream.
template<typename T , typename V >
std::enable_if<!(std::is_array< V >::value||std::is_pointer< V >::value), void >::type emitProxy (std::ostream &out, const T &t, std::size_t nComponents, V T::*member)
Function Documentation
emitProxy() [1/2]
template<typename T , typename V > std::enable_if<std::is_array<V>::value || std::is_pointer<V>::value, void>::type Detail::emitProxy (std::ostream & out, const T & t, std::size_t nComponents, V T::* member)
This function actually writes the correct datatype to ostream.
   {
     for (std::size_t i = 0; i < nComponents; i++)
     {
       out << round((t.*member)[i]) << " ";
     }
   }
References i, out(), round(), and plotPSD::t.
Referenced by Detail::VTKPointDescriptorEntryImpl< T, V >::emit().
emitProxy() [2/2]
template<typename T , typename V > std::enable_if<!(std::is_array<V>::value || std::is_pointer<V>::value), void>::type Detail::emitProxy (std::ostream & out, const T & t, std::size_t nComponents, V T::* member)
   {
     out << round(t.*member) << " ";
   }
References out(), round(), and plotPSD::t.
round() [1/2]
template<> double Detail::round (double in)
{
       //logger.assert_debug(fabs(in)>1e-33 or fabs(in)==0, "Detected underflow: corrected double value % to 0", in);
       logger.assert_debug(std::isfinite(in), "Detected nans!");
       return (fabs(in)<1e-33)?0.0:in;
   }
References e(), boost::multiprecision::fabs(), isfinite, and logger.
round() [2/2]
template<typename V > V Detail::round (V in)
                 {
       return in;
   }
Referenced by emitProxy().
toVTKDataType() [1/4]
template<typename V > std::enable_if<std::is_floating_point<V>::value, std::string>::type Detail::toVTKDataType ()
This function returns the correct VTK data type based on the template argument
   {
     return "Float32";
   }
toVTKDataType() [2/4]
template<typename V > std::enable_if<std::is_integral<V>::value && std::is_unsigned<V>::value, std::string>::type Detail::toVTKDataType ()
   {
     return "UInt32";
   }
toVTKDataType() [3/4]
template<typename V > std::enable_if<std::is_integral<V>::value && std::is_signed<V>::value, std::string>::type Detail::toVTKDataType ()
   {
     return "Int32";
   }
toVTKDataType() [4/4]
template<typename V > std::enable_if<std::is_array<V>::value, std::string>::type Detail::toVTKDataType ()
   {
     return toVTKDataType< typename std::remove_extent<V>::type >();
   }
References compute_granudrum_aor::type.