MercuryDPM: MPISphericalParticle Class Reference
MPISphericalParticle Class Reference
#include <MpiDataClass.h>
Public Member Functions
void copyDataFromMPIParticleToParticle (BaseParticle *p)
Copies data from a BaseParticle to an MPIParticle class and returns this.
void copyDataFromParticleToMPIParticle (BaseParticle *p)
Static Public Member Functions
static BaseParticle * newParticle ()
Public Attributes
unsigned int id
unsigned int indSpecies
unsigned int HGridLevel
Mdouble radius
Vec3D position
Vec3D angularVelocity
Vec3D velocity
Quaternion orientation
unsigned communicationComplexity
bool isMaser
bool isFixed
Member Function Documentation
copyDataFromMPIParticleToParticle()
void MPISphericalParticle::copyDataFromMPIParticleToParticle (BaseParticle * p)
Copies data from a BaseParticle to an MPIParticle class and returns this.
In order to create ghost particles on other processors, data of particles have to be transmitted to other processors. Only the required data is sent. The data is sent in an MPIParticle data class and this function copies the data from a particle into that class.
Parameters
[in] p Pointer to a base particle from which data is copied
Returns
MPIParticle class is returned filled with data from BaseParticle p
Copies data from an MPIParticle class to a BaseParticle
When processors recieve data of ghost particles they have to add, they recieve them in the MPIParticle class. This function turns the MPIParticle class back into a BaseParticle and initialises hGrid values to "default"
Parameters
[in] bP Pointer to an MPIParticle which contains data for a ghost particle
[in,out] p Pointer to BaseParticle, a ghost particle that will be added to the domain
 {
     //Set important quantities
     p->setId(id);
     p->setRadius(radius);
     p->setPosition(position);
     p->setAngularVelocity(angularVelocity);
     p->setVelocity(velocity);
     p->setOrientation(orientation);
     p->setCommunicationComplexity(communicationComplexity);
     //Set HGrid values
     p->setHGridNextObject(nullptr);
     p->setHGridPrevObject(nullptr);
     p->setHGridX(99999);
     p->setHGridY(99999);
     p->setHGridZ(99999);
     p->setHGridLevel(HGridLevel);
     //This is not a periodic particle
     p->setPeriodicFromParticle(nullptr);
     p->setInPeriodicDomain(false);
     //Fix maser if it is maser
     p->setMaserParticle(isMaser);
     //Fixed particles need to be fixed again
     if (isFixed)
     {
         p->fixParticle();
     }
 }
References angularVelocity, communicationComplexity, HGridLevel, isFixed, isMaser, orientation, p, position, radius, and velocity.
Referenced by MPISuperQuadric::copyDataFromMPIParticleToParticle(), MPILiquidFilmParticle::copyDataFromMPIParticleToParticle(), and copyDataFromMPIParticleToParticle().
copyDataFromParticleToMPIParticle()
void MPISphericalParticle::copyDataFromParticleToMPIParticle (BaseParticle * p)
{
     id = p->getId();
     indSpecies = p->getIndSpecies();
     radius = p->getRadius();
     position = p->getPosition();
     angularVelocity = p->getAngularVelocity();
     velocity = p->getVelocity();
     orientation = p->getOrientation();
     HGridLevel = p->getHGridLevel();
     communicationComplexity = p->getCommunicationComplexity();
     isMaser = p->isMaserParticle();
     isFixed = p->isFixed();
 }
References angularVelocity, communicationComplexity, HGridLevel, indSpecies, isFixed, isMaser, orientation, p, position, radius, and velocity.
Referenced by ParticleHandler::addGhostObject(), ParticleHandler::addObject(), InsertionBoundary::checkBoundaryBeforeTimeStep(), copyDataFromParticleToMPIParticle(), MPISuperQuadric::copyDataFromParticleToMPIParticle(), MPILiquidFilmParticle::copyDataFromParticleToMPIParticle(), and DPMBase::synchroniseParticle().
newParticle()
BaseParticle * MPISphericalParticle::newParticle () static
{
     return new SphericalParticle;
 }
Referenced by Domain::processReceivedBoundaryParticleData(), and PeriodicBoundaryHandler::processReceivedGhostParticleData().
Member Data Documentation
angularVelocity
Vec3D MPISphericalParticle::angularVelocity
Referenced by copyDataFromMPIParticleToParticle(), and copyDataFromParticleToMPIParticle().
communicationComplexity
unsigned MPISphericalParticle::communicationComplexity
Referenced by copyDataFromMPIParticleToParticle(), and copyDataFromParticleToMPIParticle().
HGridLevel
unsigned int MPISphericalParticle::HGridLevel
Referenced by copyDataFromMPIParticleToParticle(), and copyDataFromParticleToMPIParticle().
id
unsigned int MPISphericalParticle::id
indSpecies
unsigned int MPISphericalParticle::indSpecies
Referenced by copyDataFromMPIParticleToParticle(), and copyDataFromParticleToMPIParticle().
isFixed
bool MPISphericalParticle::isFixed
Referenced by copyDataFromMPIParticleToParticle(), and copyDataFromParticleToMPIParticle().
isMaser
bool MPISphericalParticle::isMaser
Referenced by copyDataFromMPIParticleToParticle(), and copyDataFromParticleToMPIParticle().
orientation
Quaternion MPISphericalParticle::orientation
Referenced by copyDataFromMPIParticleToParticle(), and copyDataFromParticleToMPIParticle().
position
Vec3D MPISphericalParticle::position
Referenced by copyDataFromMPIParticleToParticle(), and copyDataFromParticleToMPIParticle().
radius
Mdouble MPISphericalParticle::radius
Referenced by copyDataFromMPIParticleToParticle(), and copyDataFromParticleToMPIParticle().
velocity
Vec3D MPISphericalParticle::velocity
Referenced by copyDataFromMPIParticleToParticle(), and copyDataFromParticleToMPIParticle().
The documentation for this class was generated from the following files:
MpiDataClass.h
MpiDataClass.cc