MercuryDPM: Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device > Struct Template Reference
#include <TensorEvaluator.h>
Public Types
enum {
IsAligned = TensorEvaluator<ArgType, Device>::IsAligned , PacketAccess , BlockAccess = TensorEvaluator<ArgType, Device>::BlockAccess , PreferBlockAccess = TensorEvaluator<ArgType, Device>::PreferBlockAccess ,
CoordAccess = false , RawAccess = false
}
typedef TensorCwiseUnaryOp< UnaryOp, ArgType > XprType
typedef XprType::Index Index
typedef XprType::Scalar Scalar
typedef std::remove_const_t< Scalar > ScalarNoConst
typedef internal::traits< XprType >::Scalar CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef TensorEvaluator< ArgType, Device >::Dimensions Dimensions
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorBlockDescriptor< NumDims, Index > TensorBlockDesc
typedef internal::TensorBlockScratchAllocator< Device > TensorBlockScratch
typedef TensorEvaluator< const ArgType, Device >::TensorBlock ArgTensorBlock
typedef internal::TensorCwiseUnaryBlock< UnaryOp, ArgTensorBlock > TensorBlock
Public Member Functions
EIGEN_DEVICE_FUNC TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements getResourceRequirements () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock block (TensorBlockDesc &desc, TensorBlockScratch &scratch, bool=false) const
EIGEN_DEVICE_FUNC EvaluatorPointerType data () const
Static Public Attributes
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int NumDims = internal::array_size<Dimensions>::value
Private Attributes
const Device EIGEN_DEVICE_REF m_device
const UnaryOp m_functor
TensorEvaluator< ArgType, Device > m_argImpl
Member Typedef Documentation
ArgTensorBlock
template<typename UnaryOp , typename ArgType , typename Device > typedef TensorEvaluator<const ArgType, Device>::TensorBlock Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::ArgTensorBlock
CoeffReturnType
template<typename UnaryOp , typename ArgType , typename Device > typedef internal::traits<XprType>::Scalar Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::CoeffReturnType
Dimensions
template<typename UnaryOp , typename ArgType , typename Device > typedef TensorEvaluator<ArgType, Device>::Dimensions Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::Dimensions
EvaluatorPointerType
template<typename UnaryOp , typename ArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::EvaluatorPointerType
Index
template<typename UnaryOp , typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::Index
PacketReturnType
template<typename UnaryOp , typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::PacketReturnType
Scalar
template<typename UnaryOp , typename ArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::Scalar
ScalarNoConst
template<typename UnaryOp , typename ArgType , typename Device > typedef std::remove_const_t<Scalar> Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::ScalarNoConst
Storage
template<typename UnaryOp , typename ArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::Storage
TensorBlock
template<typename UnaryOp , typename ArgType , typename Device > typedef internal::TensorCwiseUnaryBlock<UnaryOp, ArgTensorBlock> Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::TensorBlock
TensorBlockDesc
template<typename UnaryOp , typename ArgType , typename Device > typedef internal::TensorBlockDescriptor<NumDims, Index> Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::TensorBlockDesc
TensorBlockScratch
template<typename UnaryOp , typename ArgType , typename Device > typedef internal::TensorBlockScratchAllocator<Device> Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::TensorBlockScratch
XprType
template<typename UnaryOp , typename ArgType , typename Device > typedef TensorCwiseUnaryOp<UnaryOp, ArgType> Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename UnaryOp , typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = TensorEvaluator<ArgType, Device>::IsAligned,
     PacketAccess =
         int(TensorEvaluator<ArgType, Device>::PacketAccess) & int(internal::functor_traits<UnaryOp>::PacketAccess),
     BlockAccess = TensorEvaluator<ArgType, Device>::BlockAccess,
     PreferBlockAccess = TensorEvaluator<ArgType, Device>::PreferBlockAccess,
     CoordAccess = false,  // to be implemented
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename UnaryOp , typename ArgType , typename Device > EIGEN_DEVICE_FUNC Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_device(device), m_functor(op.functor()), m_argImpl(op.nestedExpression(), device) {}
Member Function Documentation
block()
template<typename UnaryOp , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::block (TensorBlockDesc & desc, TensorBlockScratch & scratch, bool = false) const inline
{
     return TensorBlock(m_argImpl.block(desc, scratch), m_functor);
   }
cleanup()
template<typename UnaryOp , typename ArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::cleanup () inline
 { m_argImpl.cleanup(); }
Referenced by framework.Frame::__init__().
coeff()
template<typename UnaryOp , typename ArgType , typename Device > EIGEN_DEVICE_FUNC CoeffReturnType Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::coeff (Index index) const inline
 { return m_functor(m_argImpl.coeff(index)); }
costPerCoeff()
template<typename UnaryOp , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     const double functor_cost = internal::functor_traits<UnaryOp>::Cost;
     return m_argImpl.costPerCoeff(vectorized) + TensorOpCost(0, 0, functor_cost, vectorized, PacketSize);
   }
References Eigen::TensorEvaluator< Derived, Device >::PacketSize.
data()
template<typename UnaryOp , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EvaluatorPointerType Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename UnaryOp , typename ArgType , typename Device > EIGEN_DEVICE_FUNC const Dimensions& Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::dimensions () const inline
 { return m_argImpl.dimensions(); }
evalSubExprsIfNeeded()
template<typename UnaryOp , typename ArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
{
     m_argImpl.evalSubExprsIfNeeded(NULL);
     return true;
   }
getResourceRequirements()
template<typename UnaryOp , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::getResourceRequirements () const inline
{
     static const double functor_cost = internal::functor_traits<UnaryOp>::Cost;
     return m_argImpl.getResourceRequirements().addCostPerCoeff({0, 0, functor_cost / PacketSize});
   }
References Eigen::TensorEvaluator< Derived, Device >::PacketSize.
packet()
template<typename UnaryOp , typename ArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::packet (Index index) const inline
{
     return m_functor.packetOp(m_argImpl.template packet<LoadMode>(index));
   }
Member Data Documentation
Layout
template<typename UnaryOp , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_argImpl
template<typename UnaryOp , typename ArgType , typename Device > TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::m_argImpl private
m_device
template<typename UnaryOp , typename ArgType , typename Device > const Device EIGEN_DEVICE_REF Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::m_device private
m_functor
template<typename UnaryOp , typename ArgType , typename Device > const UnaryOp Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::m_functor private
NumDims
template<typename UnaryOp , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::NumDims = internal::array_size<Dimensions>::value static constexpr
PacketSize
template<typename UnaryOp , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorEvaluator.h