MercuryDPM: HGridCell Class Reference
HGridCell Class Reference
#include <HGridCell.h>
Public Member Functions
HGridCell ()
bool equals (int x, int y, int z, unsigned int level) const
Checks if the given (x,y,z,level) is the same as the ones in this cell.
bool equals (int x, int y, unsigned int level) const
Checks if the given (x,y,z,level) is the same as the ones in this cell, 2D version.
bool operator== (const HGridCell &other) const
Checks if the given cell is the same as the given cell.
int getHGridX () const
void setHGridX (int HGridX)
int getHGridY () const
void setHGridY (int HGridY)
int getHGridZ () const
void setHGridZ (int HGridZ)
unsigned int getHGridLevel () const
void setHGridLevel (unsigned int HGridLevel)
Private Attributes
int hGridX_
Cell position in the grid.
int hGridY_
int hGridZ_
unsigned int hGridLevel_
HGrid-level of the particle containing this cell.
Detailed Description
Contains the hGrid-information for a certain particle: x,y,z and level of the particle containing this. Note, that each particle contains a HGridCell. All methods are inline for speed reasons: they are called VERY often, so we do need performance here.
Constructor & Destructor Documentation
HGridCell()
HGridCell::HGridCell () inline
                 : hGridX_(0), hGridY_(0), hGridZ_(0), hGridLevel_(0)
     {}
Member Function Documentation
equals() [1/2]
bool HGridCell::equals (int x, int y, int z, unsigned int level) const inline
Checks if the given (x,y,z,level) is the same as the ones in this cell.
     {
         return (x == hGridX_ && y == hGridY_ && z == hGridZ_ && level == hGridLevel_);
     }
References hGridLevel_, hGridX_, hGridY_, hGridZ_, plotDoE::x, and y.
Referenced by Mercury3D::hGridFindContactsWithTargetCell(), Mercury2D::hGridFindContactsWithTargetCell(), and operator==().
equals() [2/2]
bool HGridCell::equals (int x, int y, unsigned int level) const inline
Checks if the given (x,y,z,level) is the same as the ones in this cell, 2D version.
     {
         return (x == hGridX_ && y == hGridY_ && level == hGridLevel_);
     }
References hGridLevel_, hGridX_, hGridY_, plotDoE::x, and y.
getHGridLevel()
unsigned int HGridCell::getHGridLevel () const inline
     {
         return hGridLevel_;
     }
References hGridLevel_.
Referenced by HGrid::computeHashBucketIndex(), BaseParticle::getHGridLevel(), and BaseParticle::printHGrid().
getHGridX()
int HGridCell::getHGridX () const inline
     {
         return hGridX_;
     }
References hGridX_.
Referenced by HGrid::computeHashBucketIndex(), BaseParticle::getHGridX(), and BaseParticle::printHGrid().
getHGridY()
int HGridCell::getHGridY () const inline
     {
         return hGridY_;
     }
References hGridY_.
Referenced by HGrid::computeHashBucketIndex(), BaseParticle::getHGridY(), and BaseParticle::printHGrid().
getHGridZ()
int HGridCell::getHGridZ () const inline
     {
         return hGridZ_;
     }
References hGridZ_.
Referenced by HGrid::computeHashBucketIndex(), BaseParticle::getHGridZ(), and BaseParticle::printHGrid().
operator==()
bool HGridCell::operator== (const HGridCell & other) const inline
Checks if the given cell is the same as the given cell.
     {
         return equals(other.hGridX_, other.hGridY_, other.hGridZ_, other.hGridLevel_);
     }
References equals(), hGridLevel_, hGridX_, hGridY_, and hGridZ_.
setHGridLevel()
void HGridCell::setHGridLevel (unsigned int HGridLevel) inline
     {
         hGridLevel_ = HGridLevel;
     }
References hGridLevel_.
Referenced by BaseParticle::BaseParticle(), and BaseParticle::setHGridLevel().
setHGridX()
void HGridCell::setHGridX (int HGridX) inline
     {
         hGridX_ = HGridX;
     }
References hGridX_.
Referenced by BaseParticle::BaseParticle(), and BaseParticle::setHGridX().
setHGridY()
void HGridCell::setHGridY (int HGridY) inline
     {
         hGridY_ = HGridY;
     }
References hGridY_.
Referenced by BaseParticle::BaseParticle(), and BaseParticle::setHGridY().
setHGridZ()
void HGridCell::setHGridZ (int HGridZ) inline
     {
         hGridZ_ = HGridZ;
     }
References hGridZ_.
Referenced by BaseParticle::BaseParticle(), and BaseParticle::setHGridZ().
Member Data Documentation
hGridLevel_
unsigned int HGridCell::hGridLevel_ private
HGrid-level of the particle containing this cell.
Referenced by equals(), getHGridLevel(), operator==(), and setHGridLevel().
hGridX_
int HGridCell::hGridX_ private
Cell position in the grid.
Referenced by equals(), getHGridX(), operator==(), and setHGridX().
hGridY_
int HGridCell::hGridY_ private
Referenced by equals(), getHGridY(), operator==(), and setHGridY().
hGridZ_
int HGridCell::hGridZ_ private
Referenced by equals(), getHGridZ(), operator==(), and setHGridZ().
The documentation for this class was generated from the following file:
HGridCell.h