MercuryDPM: Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ > Struct Template Reference
Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ > Struct Template Reference
#include <CoherentPadOp.h>
Public Types
typedef internal::generic_xpr_base< CoherentPadOp< XprType, SizeAtCompileTime_ > >::type Base
using XprNested = typename traits< CoherentPadOp >::XprNested
using XprNested_ = typename traits< CoherentPadOp >::XprNested_
using NestedExpression = XprNested_
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoherentPadOp ()=delete
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoherentPadOp (const CoherentPadOp &)=default
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoherentPadOp (CoherentPadOp &&other)=default
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoherentPadOp (const XprType &xpr, Index size)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const XprNested_ & nestedExpression () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index size () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rows () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index cols () const
Private Attributes
XprNested xpr_
const internal::variable_if_dynamic< Index, SizeAtCompileTime > size_
Member Typedef Documentation
Base
template<typename XprType , int SizeAtCompileTime_> typedef internal::generic_xpr_base<CoherentPadOp<XprType, SizeAtCompileTime_> >::type Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::Base
NestedExpression
template<typename XprType , int SizeAtCompileTime_> using Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::NestedExpression = XprNested_
XprNested
template<typename XprType , int SizeAtCompileTime_> using Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::XprNested = typename traits<CoherentPadOp>::XprNested
XprNested_
template<typename XprType , int SizeAtCompileTime_> using Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::XprNested_ = typename traits<CoherentPadOp>::XprNested_
Constructor & Destructor Documentation
CoherentPadOp() [1/4]
template<typename XprType , int SizeAtCompileTime_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::CoherentPadOp () delete
CoherentPadOp() [2/4]
template<typename XprType , int SizeAtCompileTime_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::CoherentPadOp (const CoherentPadOp< XprType, SizeAtCompileTime_ > &) default
CoherentPadOp() [3/4]
template<typename XprType , int SizeAtCompileTime_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::CoherentPadOp (CoherentPadOp< XprType, SizeAtCompileTime_ > && other) default
CoherentPadOp() [4/4]
template<typename XprType , int SizeAtCompileTime_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::CoherentPadOp (const XprType & xpr, Index size) inline
                                                                                       : xpr_(xpr), size_(size) {
     static_assert(XprNested_::IsVectorAtCompileTime, "input type must be a vector");
   }
Member Function Documentation
cols()
template<typename XprType , int SizeAtCompileTime_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::cols () const inline
{
     return traits<CoherentPadOp>::IsRowMajor ? size() : Index(1);
   }
References Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::size().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
nestedExpression()
template<typename XprType , int SizeAtCompileTime_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const XprNested_& Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::nestedExpression () const inline
 { return xpr_; }
References Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::xpr_.
rows()
template<typename XprType , int SizeAtCompileTime_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::rows () const inline
{
     return traits<CoherentPadOp>::IsRowMajor ? Index(1) : size();
   }
References Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::size().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
size()
template<typename XprType , int SizeAtCompileTime_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::size () const inline
 { return size_.value(); }
References Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::size_, and Eigen::internal::variable_if_dynamic< T, Value >::value().
Referenced by Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::cols(), and Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::rows().
Member Data Documentation
size_
template<typename XprType , int SizeAtCompileTime_> const internal::variable_if_dynamic<Index, SizeAtCompileTime> Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::size_ private
Referenced by Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::size().
xpr_
template<typename XprType , int SizeAtCompileTime_> XprNested Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::xpr_ private
Referenced by Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::nestedExpression().
The documentation for this struct was generated from the following file:
CoherentPadOp.h