MercuryDPM: VibratingShellProblem< ELEMENT > Class Template Reference
VibratingShellProblem< ELEMENT > Class Template Reference
Problem class to simulate the settling of a viscous drop.
Public Member Functions
VibratingShellProblem ()
Constructor.
~VibratingShellProblem ()
Destructor.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of free surface elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of free surface elements.
void actions_after_newton_solve ()
Update the after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve.
void actions_before_newton_convergence_check ()
Allow inverted elements during Newton iteration.
void actions_after_newton_convergence_check ()
Don't allow inverted elements in general.
void complete_problem_setup ()
Set boundary conditions and complete the build of all elements.
void doc_solution (const std::string &comment="")
Doc the solution.
void compute_error_estimate (double &max_err, double &min_err)
Compute the error estimates and assign to elements for plotting.
double global_temporal_error_norm ()
Error norm to determine the next time step.
double & next_dt ()
Access the next suggested timestep.
double height_central_node ()
Get the height at the centre node.
void update_latest_fixed_point_iteration_guess_for_strain_rate_for_all_elements ()
Update latest guess for strain rate.
void enable_fixed_point_iteration_for_strain_rate_for_all_elements ()
void disable_fixed_point_iteration_for_strain_rate_for_all_elements ()
Disable use of fixed point iteration.
void enable_aitken_extrapolation_for_all_elements ()
Enable use of Aitken extrapolation for all elements.
void disable_aitken_extrapolation_for_all_elements ()
Disable use of Aitken extrapolation.
void set_nprev_for_extrapolation_of_strain_rate_for_all_elements (const unsigned &nprev)
double calculate_error_of_fixed_point_iteration ()
get the error of the fixed point iteration
double strainrate_norm ()
void dump_it (ofstream &dump_file)
Dump problem data to allow for later restart.
void restart ()
Restart.
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Private Types
enum { Internal_boundary1_id =0 , Free_surface_boundary_id =1 , Symmetry_line_id =2 , Shell_wall_boundary_id =3 }
Enumeration of boundaries.
Private Member Functions
void create_free_surface_elements ()
Create free surface elements.
void delete_free_surface_elements ()
Delete free surface elements.
Private Attributes
Node * Central_node_on_free_surface_pt
Pointer to free surface node on symmetry line.
double Next_dt
Mesh * Free_surface_mesh_pt
Pointers to mesh of free surface elements.
RefineableSolidTriangleMesh< ELEMENT > * Fluid_mesh_pt
Pointer to Fluid_mesh.
Data * External_pressure_data_pt
Pointer to a global external pressure datum.
TriangleMeshClosedCurve * Outer_boundary_polyline_pt
Triangle mesh polygon for outer boundary.
Vector< TriangleMeshOpenCurve * > Internal_open_boundary_pt
double Pext
External pressure.
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_before_implicit_timestep ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual void set_initial_condition ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class ELEMENT>
class VibratingShellProblem< ELEMENT >
Problem class to simulate the settling of a viscous drop.
//////////////////////////////////////////////////////// //////////////////////////////////////////////////////// ////////////////////////////////////////////////////////
Member Enumeration Documentation
anonymous enum
template<class ELEMENT > anonymous enum private
Enumeration of boundaries.
Enumerator
Internal_boundary1_id
Free_surface_boundary_id
Symmetry_line_id
Shell_wall_boundary_id
  {
   Internal_boundary1_id=0,
   Free_surface_boundary_id=1,
   Symmetry_line_id=2,
   Shell_wall_boundary_id=3
  };
Constructor & Destructor Documentation
VibratingShellProblem()
template<class ELEMENT > VibratingShellProblem< ELEMENT >::VibratingShellProblem
Constructor.
Get pointer to the free surface node
Get the node's boundary coordinate
Get the node's coordinate in the spline representation
Get pointer to the free surface node
Get the node's r-coordinate
Set external pressure to zero
 {
  Always_take_one_newton_step = true;
  Minimum_dt_but_still_proceed=Problem_Parameter::Dt_min;
  Max_residuals=10.0;
  Max_newton_iterations=25;
  //enable_globally_convergent_newton_method();
  // Allocate the timestepper -- this constructs the Problem's
  // time object with a sufficient amount of storage to store the
  // previous timsteps.
  switch (Problem_Parameter::BDF_type)
   {
   case 1:
    this->add_time_stepper_pt(new BDF<1>(true));
    oomph_info << "Using BDF1\n";
    break;
   case 2:
    this->add_time_stepper_pt(new BDF<2>(true));
    oomph_info << "Using BDF2\n";
    break;
   case 4:
    this->add_time_stepper_pt(new BDF<4>(true));
    oomph_info << "Using BDF4\n";
    break;
   default:
    oomph_info << "Wrong BDF type: " << Problem_Parameter::BDF_type
               << std::endl;
    break;
   }
   // Build the boundary segments for outer boundary, consisting of
  //--------------------------------------------------------------
  // 2 separate polylines
  //------------------------
  Vector<TriangleMeshCurveSection*> boundary_curve_section_pt(3);
  Vector<TriangleMeshPolyLine*> internal_polyline_pt(2);
  // Each polyline only has two vertices -- provide storage for their
  // coordinates
  Vector<Vector<double> > vertex_coord;
  Ellipse* Shell_wall_pt = new Ellipse(Problem_Parameter::Shell_radius,
                                       Problem_Parameter::Shell_radius);
  double zeta_start=0.0;
  double zeta_end=MathematicalConstants::Pi/2.0;
  // number of points along the shell wall
  unsigned npoints_wall=80;
  // get the increment in boundary coordinate
  double unit_zeta = (zeta_end-zeta_start)/double(npoints_wall-1);
  // resize the vector storing the vertices
  vertex_coord.resize(npoints_wall);
  // boundary coordinate
  Vector<double> zeta(1,0.0);
  // coordinates of point on the boundary
  Vector<double> coord(2,0.0);
  // Create points on boundary
  for(unsigned ipoint=0; ipoint<npoints_wall;ipoint++)
   {
    // Get the coordinates
    zeta[0]=zeta_start+unit_zeta*double(ipoint);
    Shell_wall_pt->position(zeta,coord);
    // resize vertex coordinate
    vertex_coord[ipoint].resize(2);
    // Shift
    vertex_coord[ipoint][0]=coord[0];
    //std::cout<<vertex_coord[ipoint][0]<< " ";
    vertex_coord[ipoint][1]=coord[1];
    //std::cout<<vertex_coord[ipoint][1]<< std::endl;
   }
  boundary_curve_section_pt[0]=
   new TriangleMeshPolyLine(vertex_coord, Shell_wall_boundary_id);
  ofstream file;
  file.open((Problem_Parameter::Directory+"/boundary_section0.dat").c_str());
  boundary_curve_section_pt[0]->output(file);
  file.close();
  // Resize the vertex coordinates vector
  vertex_coord.resize(2);
  for(unsigned i=0;i<2;i++)
   {
    vertex_coord[i].resize(2);
   }
  // Build the symmetry polyline
  vertex_coord[0][0]=0.0;
  vertex_coord[0][1]=Problem_Parameter::Shell_radius;
  vertex_coord[1][0]=0.0;
  vertex_coord[1][1]=Problem_Parameter::free_surface_profile(0.0); // obacht
  boundary_curve_section_pt[1]= new TriangleMeshPolyLine(vertex_coord,
                                                         Symmetry_line_id);
  file.open((Problem_Parameter::Directory+"/boundary_section1.dat").c_str());
  boundary_curve_section_pt[1]->output(file);
  file.close();
  // number of points along the shell wall
  unsigned npoints_fs=80;
  // get the increment in boundary coordinate
  double increment = 1.0/double(npoints_fs-1);
  // resize the vector storing the vertices
  vertex_coord.resize(npoints_fs);
  // Create points on boundary
  for(unsigned ipoint=0; ipoint<npoints_fs;ipoint++)
   {
    // resize vertex coordinate
    vertex_coord[ipoint].resize(2);
    if(ipoint==0)
     {
      vertex_coord[ipoint][0]=0.0;
      //std::cout<<vertex_coord[ipoint][0]<< " ";
      vertex_coord[ipoint][1]=
       Problem_Parameter::free_surface_profile(0.0); // obacht
      //std::cout<<vertex_coord[ipoint][1]<< std::endl;
      continue;
     }
    else if(ipoint==npoints_fs-1)
     {
      vertex_coord[ipoint][0]=Problem_Parameter::Shell_radius;
      //std::cout<<vertex_coord[ipoint][0]<< " ";
      vertex_coord[ipoint][1]=0.0;
      //std::cout<<vertex_coord[ipoint][1]<< std::endl;
      continue;
     }
    // Get the coordinates
    coord[0]=double(ipoint)*increment;
    coord[1]=Problem_Parameter::free_surface_profile(coord[0]);
    //-1.0*(-0.05*tanh(10.0*coord[0]-7.5)+0.05); // obacht
    // Shift
    vertex_coord[ipoint][0]=coord[0];
    //std::cout<<vertex_coord[ipoint][0]<< " ";
    vertex_coord[ipoint][1]=coord[1];
    //std::cout<<vertex_coord[ipoint][1]<< std::endl;
   }
  // Build the boundary polyline
  boundary_curve_section_pt[2]=
   new TriangleMeshPolyLine(vertex_coord, Free_surface_boundary_id);
  file.open((Problem_Parameter::Directory+"/boundary_section2.dat").c_str());
  boundary_curve_section_pt[2]->output(file);
  file.close();
  // Create the triangle mesh polygon for outer boundary
  Outer_boundary_polyline_pt =
   new TriangleMeshClosedCurve(boundary_curve_section_pt);
  // Use the TriangleMeshParameters object for gathering all
  // the necessary arguments for the TriangleMesh object
  TriangleMeshParameters triangle_mesh_parameters(
    Outer_boundary_polyline_pt);
  // Define the maximum element areas
  triangle_mesh_parameters.element_area() =
   Problem_Parameter::Uniform_element_area;
  // enable the boundary refinement
  triangle_mesh_parameters.enable_boundary_refinement();
  // Create the mesh
  Fluid_mesh_pt =
    new RefineableSolidTriangleMesh<ELEMENT>(
     triangle_mesh_parameters,this->time_stepper_pt());
  // Increase number of bins to reduce bias/drift in area targets
  Fluid_mesh_pt->nbin_x_for_area_transfer()=500;
  Fluid_mesh_pt->nbin_y_for_area_transfer()=500;
 // Fluid_mesh_pt->output((Problem_Parameter::Directory+"/Mesh_before_snapping.dat").c_str());
  //----------------------------------------------------------------
  // Snap nodes manually onto the curved boundary
  //----------------------------------------------------------------
  // loop over the nodes on the wall boundary
  unsigned n_boundary_node = Fluid_mesh_pt->
   nboundary_node(Shell_wall_boundary_id);
  for(unsigned n=0;n<n_boundary_node;n++)
   {
    Node* nod_pt = Fluid_mesh_pt->boundary_node_pt(Shell_wall_boundary_id,n);
    Vector<double> zeta(1);
    nod_pt->get_coordinates_on_boundary(Shell_wall_boundary_id, zeta);
    Vector<double> new_x(2,0.0);
    // updating zeta
    zeta[0]=zeta_start+zeta[0]*(zeta_end-zeta_start);
    Shell_wall_pt->position(zeta,new_x);
    nod_pt->x(0) = new_x[0];
    nod_pt->x(1) = new_x[1];
   }
  n_boundary_node=Fluid_mesh_pt->nboundary_node(Free_surface_boundary_id);
  for(unsigned n=0;n<n_boundary_node;n++)
   {
    Node* nod_pt = Fluid_mesh_pt->boundary_node_pt(Free_surface_boundary_id,n);
    if(nod_pt->is_on_boundary(Shell_wall_boundary_id) ||
       nod_pt->is_on_boundary(Symmetry_line_id))
     {
      continue;
     }
    double r=nod_pt->x(0);
    // calculate node's z-coordinate
    double new_z=Problem_Parameter::free_surface_profile(r); // obacht
    // move node
    nod_pt->x(1) = new_z;
   }
  //-----------------------------------------------------------------
  //   End of snapping
  //-----------------------------------------------------------------
  //Fluid_mesh_pt->output((Problem_Parameter::Directory+"/Mesh_after_snapping.dat").c_str());
  Fluid_mesh_pt->output_boundaries((Problem_Parameter::Directory+"/boundaries.dat").c_str());
  // Set error estimator for bulk mesh
  Z2ErrorEstimator* error_estimator_pt=new Z2ErrorEstimator;
  Fluid_mesh_pt->spatial_error_estimator_pt()=error_estimator_pt;
  // Set targets for spatial adaptivity
  Fluid_mesh_pt->max_permitted_error()=5.0e-3; // was 0.005; 0.0005
  Fluid_mesh_pt->min_permitted_error()=1.0e-3; // was 0.001; 0.0001
  Fluid_mesh_pt->max_element_size()=Problem_Parameter::Uniform_element_area;
  Fluid_mesh_pt->min_element_size()=1.0e-5; // was 0.001 or 0.00001
  Pext=0.0;
  //Create a Data object whose single value stores the
  //external pressure
  External_pressure_data_pt = new Data(1);
  // Set external pressure
  External_pressure_data_pt->set_value(0,Pext);
  // The external pressure is pinned -- the external pressure
  // sets the pressure throughout the domain -- we do not have
  // the liberty to fix another pressure value!
  External_pressure_data_pt->pin(0);
  // Construct the mesh of free surface elements
  Free_surface_mesh_pt=new Mesh;
  create_free_surface_elements();
  // Set boundary condition and complete the build of all bulk elements
  complete_problem_setup();
  // Combine meshes
  //---------------
  // Add Fluid_mesh_pt sub meshes
  this->add_sub_mesh(Fluid_mesh_pt);
  // Add Free_surface sub meshes
  this->add_sub_mesh(this->Free_surface_mesh_pt);
  // Build global mesh
  this->build_global_mesh();
  // Set lagrangian coordinates for pseudo-solid
  Fluid_mesh_pt->set_lagrangian_nodal_coordinates();
  // Use mumps
  //linear_solver_pt()=new MumpsSolver;
  // Setup equation numbering scheme
  cout <<"Number of equations: " << this->assign_eqn_numbers() << std::endl;
 } // end_of_constructor
References oomph::Problem_Parameter::BDF_type, AxisymFvKParameters::Directory, oomph::Problem_Parameter::Dt_min, oomph::TriangleMeshParameters::element_area(), oomph::TriangleMeshParameters::enable_boundary_refinement(), MeshRefinement::error_estimator_pt, oomph::Problem_Parameter::free_surface_profile(), oomph::Node::get_coordinates_on_boundary(), i, oomph::Node::is_on_boundary(), oomph::Locate_zeta_helpers::Max_newton_iterations, n, oomph::oomph_info, Global_Physical_Variables::Pext, BiharmonicTestFunctions2::Pi, oomph::Ellipse::position(), UniformPSDSelfTest::r, oomph::Problem_Parameter::Shell_radius, oomph::Problem_Parameter::Uniform_element_area, oomph::Node::x(), and Eigen::zeta().
~VibratingShellProblem()
template<class ELEMENT > VibratingShellProblem< ELEMENT >::~VibratingShellProblem
Destructor.
 {
   // Fluid timestepper
   delete this->time_stepper_pt(0);
   // Kill data associated with outer boundary
   unsigned n=Outer_boundary_polyline_pt->ncurve_section();
   for (unsigned j=0;j<n;j++)
    {
     delete Outer_boundary_polyline_pt->curve_section_pt(j);
    }
   delete Outer_boundary_polyline_pt;
   // Flush element of free surface elements
   delete_free_surface_elements();
   delete Free_surface_mesh_pt;
   // Delete error estimator
   delete Fluid_mesh_pt->spatial_error_estimator_pt();
   // Delete fluid mesh
   delete Fluid_mesh_pt;
   // Delete pressure data
   delete External_pressure_data_pt;
   // Kill const eqn
   delete Problem_Parameter::Constitutive_law_pt;
   delete Problem_Parameter::Const_eqn_pt;
 } // end_of_destructor
References oomph::Problem_Parameter::Const_eqn_pt, Problem_Parameter::Constitutive_law_pt, j, and n.
Member Function Documentation
actions_after_adapt()
template<class ELEMENT > void VibratingShellProblem< ELEMENT >::actions_after_adapt () inline virtual
Actions after adapt: Rebuild the mesh of free surface elements.
Reimplemented from oomph::Problem.
   {
    // Create the elements that impose the displacement constraint
    create_free_surface_elements();
    // Rebuild the Problem's global mesh from its various sub-meshes
    this->rebuild_global_mesh();
    // Setup the problem again -- remember that fluid mesh has been
    // completely rebuilt and its element's don't have any
    // pointers to Re etc. yet
    complete_problem_setup();
   }// end of actions_after_adapt
actions_after_newton_convergence_check()
template<class ELEMENT > void VibratingShellProblem< ELEMENT >::actions_after_newton_convergence_check () inline
Don't allow inverted elements in general.
   {
    unsigned n_element = Fluid_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement to the present element
      ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Fluid_mesh_pt->element_pt(e));
      el_pt->Accept_negative_jacobian=false;
     }
   }
References e().
actions_after_newton_solve()
template<class ELEMENT > void VibratingShellProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_adapt()
template<class ELEMENT > void VibratingShellProblem< ELEMENT >::actions_before_adapt () inline virtual
Actions before adapt: Wipe the mesh of free surface elements.
Reimplemented from oomph::Problem.
   {
    // Kill the  elements and wipe surface mesh
    delete_free_surface_elements();
    // Rebuild the Problem's global mesh from its various sub-meshes
    this->rebuild_global_mesh();
   }// end of actions_before_adapt
actions_before_newton_convergence_check()
template<class ELEMENT > void VibratingShellProblem< ELEMENT >::actions_before_newton_convergence_check () inline virtual
Allow inverted elements during Newton iteration.
Reimplemented from oomph::Problem.
   {
    unsigned n_element = Fluid_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement to the present element
      ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Fluid_mesh_pt->element_pt(e));
      // accept negative jacobian in solution process
      el_pt->Accept_negative_jacobian=true;
     }
   }
References e().
actions_before_newton_solve()
template<class ELEMENT > void VibratingShellProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve.
Reimplemented from oomph::Problem.
   {
    //Reset the Lagrangian coordinates of the nodes to be the current
    //Eulerian coordinates -- this makes the current configuration
    //stress free
    Fluid_mesh_pt->set_lagrangian_nodal_coordinates();
   }
calculate_error_of_fixed_point_iteration()
template<class ELEMENT > double VibratingShellProblem< ELEMENT >::calculate_error_of_fixed_point_iteration () inline
get the error of the fixed point iteration
   {
    // Get elemental max/min/norms
    double norm_squared=0.0;
    double latest_guess_norm_squared=0.0;
    double error_norm_squared=0.0;
    unsigned nel=Fluid_mesh_pt->nelement();
    for (unsigned e=0;e<nel;e++)
     {
      // Get element
      ELEMENT* el_pt=dynamic_cast<ELEMENT*>(
       Fluid_mesh_pt->element_pt(e));
      // Get norms of invariant
      double el_norm_squared=0.0;
      double el_latest_guess_norm_squared=0.0;
      double el_error_norm_squared=0.0;
      el_pt->square_of_norm_of_fixed_point(
       el_norm_squared,
       el_latest_guess_norm_squared,
       el_error_norm_squared);
      // Add it...
      norm_squared+=el_norm_squared;
      latest_guess_norm_squared+=el_latest_guess_norm_squared;
      error_norm_squared+=el_error_norm_squared;
     }
    oomph_info << "Norm of current strain rate invariant: "
               << sqrt(norm_squared) << std::endl;
    oomph_info << "Norm of latest fixed point iteration guess for "
               << "strain rate invariant: "
               << sqrt(latest_guess_norm_squared) << std::endl;
    oomph_info << "Norm of error in fixed point iteration "
               << "strain rate invariant: "
               << sqrt(error_norm_squared) << " equivalent to " ;
    if (sqrt(norm_squared)!=0.0)
     {
      oomph_info << sqrt(error_norm_squared)/sqrt(norm_squared)*100.0 << " %";
     }
    oomph_info << std::endl;
    if (sqrt(norm_squared)!=0.0)
     {
      return sqrt(error_norm_squared)/sqrt(norm_squared)*100.0;
     }
    else
     {
      return 0.0;
     }
   }
References e(), oomph::oomph_info, and sqrt().
complete_problem_setup()
template<class ELEMENT > void VibratingShellProblem< ELEMENT >::complete_problem_setup
Set boundary conditions and complete the build of all elements.
Set up the problem: apply BC and make bulk elements fully functional.
Get pointer to the free surface node
 {
  // Re-set the boundary conditions for fluid problem: All nodes are
  // free by default -- just pin the ones that have Dirichlet conditions
  // here.
  unsigned nbound=Fluid_mesh_pt->nboundary();
  for(unsigned ibound=0;ibound<nbound;ibound++)
   {
    unsigned num_nod=Fluid_mesh_pt->nboundary_node(ibound);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      // Get node
      Node* nod_pt=Fluid_mesh_pt->boundary_node_pt(ibound,inod);
      //Pin both velocities at the shell wall boundary
      if(ibound==Shell_wall_boundary_id)
       {
        nod_pt->pin(0);
        nod_pt->pin(1);
       }
      // pin horizontal velocity at symmetry boundary
      if(ibound==Symmetry_line_id)
       {
        nod_pt->pin(0);
       }
      // pin Lagrange multiplier at the intersection of the shell wall
      // boundary and the free surface
      if( (nod_pt->is_on_boundary(Shell_wall_boundary_id)) &&
          (nod_pt->is_on_boundary(Free_surface_boundary_id)) )
       {
        // Get the number of values at this node
        unsigned n_value=nod_pt->nvalue();
        // check that it is the corner node with 4 values
        // (u,v,p,delta)
        if(n_value != 4)
         {
          oomph_info <<" Here!\n";
          abort();
         }
        nod_pt->pin(n_value-1);
       }
      // Pin pseudo-solid positions apart from free surface boundary which
      // we allow to move
      SolidNode* solid_node_pt = dynamic_cast<SolidNode*>(nod_pt);
      if(ibound==Shell_wall_boundary_id)
       {
        solid_node_pt->pin_position(0);
        solid_node_pt->pin_position(1);
       }
      else if(ibound==Symmetry_line_id)
       {
        solid_node_pt->pin_position(0);
       }
     }
   } // end loop over boundaries
  // Complete the build of all elements so they are fully functional
  // Remember that adaptation for triangle meshes involves a complete
  // regneration of the mesh (rather than splitting as in tree-based
  // meshes where such parameters can be passed down from the father
  // element!)
  unsigned n_element = Fluid_mesh_pt->nelement();
  for(unsigned e=0;e<n_element;e++)
   {
    // Upcast from GeneralisedElement to the present element
    ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Fluid_mesh_pt->element_pt(e));
    // Modify the tolerance for when the mapping is considered singular
    el_pt->Tolerance_for_singular_jacobian=1.0e-26;
    // Set the Reynolds number
    el_pt->re_pt() = &Problem_Parameter::Re;
    // Set the Womersley number
    el_pt->re_st_pt() = &Problem_Parameter::Re_St;
    // Set the body force
    el_pt->GeneralisedNewtonianNavierStokesEquations<2>::body_force_fct_pt() =
     &Problem_Parameter::oscillation;
    // Set the product of Reynolds number and inverse Froude number
    el_pt->re_invfr_pt() = &Problem_Parameter::ReInvFr;
    // Set the constitutive law for pseudo-elastic mesh deformation
    el_pt->constitutive_law_pt()=Problem_Parameter::Constitutive_law_pt;
    // Assign Constitutive equation
    el_pt->constitutive_eqn_pt() = Problem_Parameter::Const_eqn_pt;
    // Use extrapolated strain rate when determining viscosity
    el_pt->use_extrapolated_strainrate_to_compute_second_invariant();
   } // end of functional elements
  // Setup extrapolation
  set_nprev_for_extrapolation_of_strain_rate_for_all_elements(
   Problem_Parameter::Nprev_for_extrapolation_of_strain_rate);
  // Re-apply boundary values on Dirichlet boundary conditions
  // (Boundary conditions are ignored when the solution is transferred
  // from the old to the new mesh by projection; this leads to a slight
  // change in the boundary values (which are, of course, never changed,
  // unlike the actual unknowns for which the projected values only
  // serve as an initial guess)
  // Set velocity and history values of velocity on walls
  nbound=this->Fluid_mesh_pt->nboundary();
  for(unsigned ibound=0;ibound<nbound;++ibound)
   {
    if( (ibound==Shell_wall_boundary_id) ||
        (ibound==Symmetry_line_id) )
     {
      // Loop over nodes on this boundary
      unsigned num_nod=this->Fluid_mesh_pt->nboundary_node(ibound);
      for (unsigned inod=0;inod<num_nod;inod++)
       {
        // Get node
        Node* nod_pt=this->Fluid_mesh_pt->boundary_node_pt(ibound,inod);
        // Get number of previous (history) values
        unsigned n_prev=nod_pt->time_stepper_pt()->nprev_values();
        // Velocity is and was zero at all previous times
        for (unsigned t=0;t<=n_prev;t++)
         {
          if(ibound==Shell_wall_boundary_id)
           {
            nod_pt->set_value(t,1,0.0);
            nod_pt->set_value(t,0,0.0);
           }
          else
           {
            nod_pt->set_value(t,0,0.0);
           }
          // Move nodes on symmetry line exactly onto r=0 (for all times)
          if(ibound==Symmetry_line_id)
           {
            nod_pt->x(t,0)=0.0;
           }
         }
       }
     }
   }
  // Update pointer to central node
  oomph_info << "Updating central node" << std::endl;
  Central_node_on_free_surface_pt=0;
  const unsigned n_boundary_node = Fluid_mesh_pt->
   nboundary_node(Free_surface_boundary_id);
  for(unsigned n=0;n<n_boundary_node;n++)
   {
    Node* nod_pt = Fluid_mesh_pt->boundary_node_pt(Free_surface_boundary_id,n);
    // Is this the one?
    if (nod_pt->is_on_boundary(Symmetry_line_id))
     {
      if (Central_node_on_free_surface_pt!=0)
       {
        oomph_info << "Odd -- more than one free surface node on sym line?\n";
        abort();
       }
      Central_node_on_free_surface_pt=nod_pt;
     }
   }
  if (Central_node_on_free_surface_pt==0)
   {
    oomph_info << "Odd -- not found the free surface node on sym line...\n";
    abort();
   }
  else
   {
    oomph_info << "Updated central node" << std::endl;
    oomph_info << "Central node now at: "
               << Central_node_on_free_surface_pt->x(0) << " "
               << Central_node_on_free_surface_pt->x(1) << " "
               << std::endl;
   }
 } // end of complete_problem_setup
References oomph::Problem_Parameter::Const_eqn_pt, Problem_Parameter::Constitutive_law_pt, e(), oomph::Node::is_on_boundary(), n, oomph::Problem_Parameter::Nprev_for_extrapolation_of_strain_rate, oomph::TimeStepper::nprev_values(), oomph::Data::nvalue(), oomph::oomph_info, oomph::Problem_Parameter::oscillation(), oomph::Data::pin(), oomph::SolidNode::pin_position(), Problem_Parameter::Re, oomph::Problem_Parameter::Re_St, Problem_Parameter::ReInvFr, oomph::Data::set_value(), plotPSD::t, oomph::Data::time_stepper_pt(), and oomph::Node::x().
compute_error_estimate()
template<class ELEMENT > void VibratingShellProblem< ELEMENT >::compute_error_estimate (double & max_err, double & min_err)
Compute the error estimates and assign to elements for plotting.
Compute error estimates and assign to elements for plotting.
 {
  // Get error estimator
  ErrorEstimator* err_est_pt=Fluid_mesh_pt->spatial_error_estimator_pt();
  // Get/output error estimates
  unsigned nel=Fluid_mesh_pt->nelement();
  Vector<double> elemental_error(nel);
  // We need a dynamic cast, get_element_errors from the Fluid_mesh_pt
  // Dynamic cast is used because get_element_errors require a Mesh* ans
  // not a SolidMesh*
  Mesh* fluid_mesh_pt=dynamic_cast<Mesh*>(Fluid_mesh_pt);
  err_est_pt->get_element_errors(fluid_mesh_pt,
                                 elemental_error);
  // Set errors for post-processing and find extrema
  max_err=0.0;
  min_err=DBL_MAX;
  for (unsigned e=0;e<nel;e++)
   {
    dynamic_cast<MyTaylorHoodElement*>(Fluid_mesh_pt->element_pt(e))->
     set_error(elemental_error[e]);
    max_err=std::max(max_err,elemental_error[e]);
    min_err=std::min(min_err,elemental_error[e]);
   }
 }
References e(), oomph::ErrorEstimator::get_element_errors(), max, min, and set_error().
create_free_surface_elements()
template<class ELEMENT > void VibratingShellProblem< ELEMENT >::create_free_surface_elements private
Create free surface elements.
Create elements that impose the kinematic and dynamic bcs for the pseudo-solid fluid mesh
 {
  // How many bulk fluid elements are adjacent to boundary b?
  unsigned n_element =
   Fluid_mesh_pt->nboundary_element(Free_surface_boundary_id);
  // Loop over the bulk fluid elements adjacent to boundary b?
  for(unsigned e=0;e<n_element;e++)
   {
    // Get pointer to the bulk fluid element that is
    // adjacent to boundary b
    ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
     Fluid_mesh_pt->boundary_element_pt(Free_surface_boundary_id,e));
    //Find the index of the face of element e along boundary b
    int face_index =
     Fluid_mesh_pt->face_index_at_boundary(Free_surface_boundary_id,e);
    // Create new element
    ElasticLineFluidInterfaceElement<ELEMENT>* el_pt =
     new ElasticLineFluidInterfaceElement<ELEMENT>(
      bulk_elem_pt,face_index);
    // Add it to the mesh
    Free_surface_mesh_pt->add_element_pt(el_pt);
    //Add the appropriate boundary number
    el_pt->set_boundary_number_in_bulk_mesh(Free_surface_boundary_id);
    //Specify the capillary number
    el_pt->ca_pt() = &Problem_Parameter::Ca;
    //Specify the Strouhal number
    el_pt->st_pt() = &Problem_Parameter::St;
    // Specify the bubble pressure (pointer to Data object and
    // index of value within that Data object that corresponds
    // to the traded pressure
    el_pt->set_external_pressure_data(External_pressure_data_pt);
   }
 } // end of create_free_surface_elements
References Problem_Parameter::Ca, oomph::FluidInterfaceElement::ca_pt(), e(), oomph::FaceElement::set_boundary_number_in_bulk_mesh(), oomph::FluidInterfaceElement::set_external_pressure_data(), Problem_Parameter::St, and oomph::FluidInterfaceElement::st_pt().
delete_free_surface_elements()
template<class ELEMENT > void VibratingShellProblem< ELEMENT >::delete_free_surface_elements () inline private
Delete free surface elements.
   {
    // How many surface elements are in the surface mesh
    unsigned n_element = Free_surface_mesh_pt->nelement();
    // Loop over the surface elements
    for(unsigned e=0;e<n_element;e++)
     {
      // Kill surface element
      delete Free_surface_mesh_pt->element_pt(e);
     }
    // Wipe the mesh
    Free_surface_mesh_pt->flush_element_and_node_storage();
   } // end of delete_free_surface_elements
References e().
disable_aitken_extrapolation_for_all_elements()
template<class ELEMENT > void VibratingShellProblem< ELEMENT >::disable_aitken_extrapolation_for_all_elements () inline
Disable use of Aitken extrapolation.
   {
    unsigned n_element = Fluid_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement to the present element
      ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Fluid_mesh_pt->element_pt(e));
      el_pt->disable_aitken_extrapolation();
     }
   }
References e().
disable_fixed_point_iteration_for_strain_rate_for_all_elements()
template<class ELEMENT > void VibratingShellProblem< ELEMENT >::disable_fixed_point_iteration_for_strain_rate_for_all_elements () inline
Disable use of fixed point iteration.
    {
     unsigned n_element = Fluid_mesh_pt->nelement();
     for(unsigned e=0;e<n_element;e++)
      {
       // Upcast from GeneralisedElement to the present element
       ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Fluid_mesh_pt->element_pt(e));
       el_pt->disable_fixed_point_iteration_for_strain_rate();
      }
    }
References e().
doc_solution()
template<class ELEMENT > void VibratingShellProblem< ELEMENT >::doc_solution (const std::string & comment = "")
Doc the solution.
 {
  ofstream some_file;
  char filename[1000];
  oomph_info << "Docing trace step: "
             << Problem_Parameter::Doc_info_trace.number() << std::endl;
  // Compute errors and assign to each element for plotting
  double max_err=0.0;
  double min_err=0.0;
  compute_error_estimate(max_err,min_err);
  // Write restart file
  if ( !CommandLineArgs::command_line_flag_has_been_set
      ("--suppress_restart_files") &&
      !CommandLineArgs::command_line_flag_has_been_set
      ("--validation") )
   {
    sprintf(filename,"%s/restart%i.dat",
            Problem_Parameter::Doc_info_soln.directory().c_str(),
            Problem_Parameter::Doc_info_soln.number());
    ofstream dump_file;
    dump_file.open(filename);
    dump_file.precision(20);
    dump_it(dump_file);
    dump_file.close();
   }
  // Get body force
  Vector<double> body_force(2,0.0);
  Vector<double> x(2,0.0);
  Problem_Parameter::oscillation(this->time_pt()->time(),x,body_force);
  // only output the actual solution when it's the right time
  // hierher if(this->time_pt()->time() >= double(Count_doc)*Dt_doc)
   {
    oomph_info << "Docing soln step: "
             << Problem_Parameter::Doc_info_soln.number() << std::endl;
    // Number of plot points
    unsigned npts=5;
    // Actual solution
    sprintf(filename,"%s/soln%i.dat",
            Problem_Parameter::Doc_info_soln.directory().c_str(),
            Problem_Parameter::Doc_info_soln.number());
    some_file.open(filename);
    some_file << dynamic_cast<ELEMENT*>(this->Fluid_mesh_pt->element_pt(0))
     ->variable_identifier();
    this->Fluid_mesh_pt->output(some_file,npts);
    some_file.close();
    // Actual solution on the free surface
    sprintf(filename,"%s/free_surface_soln%i.dat",
            Problem_Parameter::Doc_info_soln.directory().c_str(),
            Problem_Parameter::Doc_info_soln.number());
    some_file.open(filename);
    unsigned nel=Free_surface_mesh_pt->nelement();
    for (unsigned e=0;e<nel;e++)
     {
      dynamic_cast<ElasticLineFluidInterfaceElement<ELEMENT>*>(
       Free_surface_mesh_pt->element_pt(e))->output(some_file,npts);
     }
    some_file.close();
    // Output free surface
    sprintf(filename,"%s/free_surface%i.dat",
            Problem_Parameter::Doc_info_soln.directory().c_str(),
            Problem_Parameter::Doc_info_soln.number());
    some_file.open(filename);
    unsigned num_nod=Fluid_mesh_pt->nboundary_node(Free_surface_boundary_id);
    if (num_nod>0)
     {
      for (unsigned inod=0;inod<num_nod;inod++)
       {
        Fluid_mesh_pt->boundary_node_pt(Free_surface_boundary_id, inod)
         ->output(some_file);
       }
     }
    some_file.close();
    // Coarse solution (mesh)
    unsigned npts_coarse=2;
    sprintf(filename,"%s/coarse_soln%i.dat",
            Problem_Parameter::Doc_info_soln.directory().c_str(),
            Problem_Parameter::Doc_info_soln.number());
    some_file.open(filename);
    some_file << dynamic_cast<ELEMENT*>(this->Fluid_mesh_pt->element_pt(0))
     ->variable_identifier();
    this->Fluid_mesh_pt->output(some_file,npts_coarse);
    some_file.close();
    // Doc body force
    sprintf(filename,"%s/body_force%i.dat",
            Problem_Parameter::Doc_info_soln.directory().c_str(),
            Problem_Parameter::Doc_info_soln.number());
    some_file.open(filename);
    some_file << "-0.5 0.0 0.0 "
              << body_force[0] << " "
              << body_force[1] << " "
              << std::endl;
    some_file.close();
    // Increment the doc_info number
    Problem_Parameter::Doc_info_soln.number()++;
   }
  // Assemble square of L2 norm
  double square_of_l2_norm=0.0;
  unsigned nel=Fluid_mesh_pt->nelement();
  for (unsigned e=0;e<nel;e++)
   {
    square_of_l2_norm+=
     dynamic_cast<ELEMENT*>(this->Fluid_mesh_pt->element_pt(e))->
     square_of_l2_norm();
   }
  Problem_Parameter::Norm_file << sqrt(square_of_l2_norm) << std::endl;
  // Output boundaries
  sprintf(filename,"%s/boundaries%i.dat",
          Problem_Parameter::Doc_info_soln.directory().c_str(),
          Problem_Parameter::Doc_info_soln.number());
  some_file.open(filename);
  this->Fluid_mesh_pt->output_boundaries(some_file);
  some_file.close();
  // Get max/min area
  double max_area=0.0;
  double min_area=0.0;
  Fluid_mesh_pt->max_and_min_element_size(max_area, min_area);
  // Compute current volume and error in extrapolation from fluid elements
  double current_vol=0.0;
  double norm_squared=0.0;
  double visc_norm_squared=0.0;
  double extrapolated_norm_squared=0.0;
  double error_norm_squared=0.0;
  double min_invariant=DBL_MAX;
  double max_invariant=-DBL_MAX;
  double min_viscosity=DBL_MAX;
  double max_viscosity=-DBL_MAX;
  for (unsigned e=0;e<nel;e++)
   {
    // Get element
    ELEMENT* el_pt=dynamic_cast<ELEMENT*>(
     Fluid_mesh_pt->element_pt(e));
    // Add to physical size (actual volume) -- not implemented
    //current_vol+=el_pt->compute_physical_size();
    // Check size (in computational coordinates
    double size=el_pt->size();
    // Get norms of invariant
    double el_norm_squared=0.0;
    double el_extrapolated_norm_squared=0.0;
    double el_error_norm_squared=0.0;
    double test_size=0.0;
    test_size=el_pt->square_of_norm_of_strain_invariant(
     el_norm_squared,
     el_extrapolated_norm_squared,
     el_error_norm_squared);
    if (std::fabs(test_size-size)>1.0e-10)
     {
      oomph_info << "Trouble: "
                 << test_size << " "
                 << size << std::endl;
     }
    // Get norms of viscosity
    double el_visc_norm_squared=0.0;
    double el_visc_extrapolated_norm_squared=0.0;
    double el_visc_error_norm_squared=0.0;
    el_pt->square_of_norm_of_viscosity(
     el_visc_norm_squared,
     el_visc_extrapolated_norm_squared,
     el_visc_error_norm_squared);
    // Add it...
    norm_squared+=el_norm_squared;
    visc_norm_squared+=el_visc_norm_squared;
    extrapolated_norm_squared+=el_extrapolated_norm_squared;
    error_norm_squared+=el_error_norm_squared;
    // Get viscosity extrema
    double el_min_invariant=0.0;
    double el_max_invariant=0.0;
    double el_min_viscosity=0.0;
    double el_max_viscosity=0.0;
    el_pt->max_and_min_invariant_and_viscosity(el_min_invariant,
                                               el_max_invariant,
                                               el_min_viscosity,
                                               el_max_viscosity);
    // Update overall extrema
    min_invariant=std::min(min_invariant,el_min_invariant);
    max_invariant=std::max(max_invariant,el_max_invariant);
    min_viscosity=std::min(min_viscosity,el_min_viscosity);
    max_viscosity=std::max(max_viscosity,el_max_viscosity);
   }
  oomph_info << "Norm of strain rate invariant: "
             << sqrt(norm_squared) << std::endl;
  oomph_info << "Norm of extrapolated strain rate invariant: "
             << sqrt(extrapolated_norm_squared) << std::endl;
  oomph_info << "Norm of error in extrapolated strain rate invariant: "
             << sqrt(error_norm_squared) << " equivalent to " ;
  if (sqrt(norm_squared)!=0.0)
   {
    oomph_info << sqrt(error_norm_squared)/sqrt(norm_squared)*100.0 << " %";
   }
  oomph_info << std::endl;
  oomph_info << "min_invariant = " << min_invariant << "\n"
             << "max_invariant = " << max_invariant << "\n"
             << "min_viscosity = " << min_viscosity << "\n"
             << "max_viscosity = " << max_viscosity
             << std::endl;
  // Write trace file
  Problem_Parameter::Trace_file
   << this->time_pt()->time() << " "  // 1
   << Central_node_on_free_surface_pt->x(1) << " " // 2
   << body_force[1] << " " // 3
   << current_vol << " " // 4
   << Fluid_mesh_pt->nelement() << " " // 5
   << max_area << " " // 6
   << min_area << " " // 7
   << max_err << " " // spatial error 8
   << min_err << " " // spatial error 9
   << sqrt(norm_squared) << " "  // strain invariant 10
   << sqrt(extrapolated_norm_squared) << " "  // strain invariant 11
   << sqrt(error_norm_squared) << " " // strain invariant  12
   << min_invariant << " " // 13
   << max_invariant << " " // 14
   << min_viscosity << " " // 15
   << max_viscosity << " " // 16
   << max_viscosity << " " // 17
   << this->time_pt()->dt() << " " // 18
   << global_temporal_error_norm() << " " // temporal error measure 19
   << Problem_Parameter::Doc_info_trace.number() << " "  // 20
   << std::endl;
  // Increment the doc_info number
  Problem_Parameter::Doc_info_trace.number()++;
 } // end_of_doc_full_solution
References Global_Parameters::body_force(), oomph::CommandLineArgs::command_line_flag_has_been_set(), oomph::Problem_Parameter::Doc_info_soln, oomph::Problem_Parameter::Doc_info_trace, e(), boost::multiprecision::fabs(), MergeRestartFiles::filename, max, min, Problem_Parameter::Norm_file, oomph::DocInfo::number(), oomph::oomph_info, oomph::Problem_Parameter::oscillation(), output(), size, sqrt(), square_of_l2_norm(), Problem_Parameter::Trace_file, and plotDoE::x.
dump_it()
template<class ELEMENT > void VibratingShellProblem< ELEMENT >::dump_it (ofstream & dump_file) inline
Dump problem data to allow for later restart.
   {
    // Write doc numbers
    dump_file << Problem_Parameter::Doc_info_trace.number()
              << " # current doc number for trace" << std::endl;
    dump_file << Problem_Parameter::Doc_info_soln.number()
              << " # current doc number for soln" << std::endl;
    // Next timestep (required for restart from temporally adaptive
    // run
    dump_file << Next_dt << " # next timestep " << std::endl;
    // Dump the refinement pattern and the generic problem data
    Problem::dump(dump_file);
   }
References oomph::Problem_Parameter::Doc_info_soln, oomph::Problem_Parameter::Doc_info_trace, and oomph::DocInfo::number().
enable_aitken_extrapolation_for_all_elements()
template<class ELEMENT > void VibratingShellProblem< ELEMENT >::enable_aitken_extrapolation_for_all_elements () inline
Enable use of Aitken extrapolation for all elements.
   {
    unsigned n_element = Fluid_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement to the present element
      ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Fluid_mesh_pt->element_pt(e));
      el_pt->enable_aitken_extrapolation();
    }
   }
References e().
enable_fixed_point_iteration_for_strain_rate_for_all_elements()
template<class ELEMENT > void VibratingShellProblem< ELEMENT >::enable_fixed_point_iteration_for_strain_rate_for_all_elements () inline
Enable use of fixed point iteration for all elements
   {
    unsigned n_element = Fluid_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement to the present element
      ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Fluid_mesh_pt->element_pt(e));
      el_pt->enable_fixed_point_iteration_for_strain_rate();
    }
   }
References e().
global_temporal_error_norm()
template<class ELEMENT > double VibratingShellProblem< ELEMENT >::global_temporal_error_norm virtual
Error norm to determine the next time step.
Calculate the global temporal error norm.
Reimplemented from oomph::Problem.
 {
  //oomph_info << "hierher bypassed global temporal error norm\n";
  //return 0.0;
  // Initialise
  double global_error = 0.0;
  //Find out how many nodes there are in the problem
  const unsigned n_node = Fluid_mesh_pt->nnode();
  oomph_info << "in here with node = " << n_node << std::endl;
  //Loop over the nodes and calculate the errors in the positions
  for(unsigned n=0;n<n_node;n++)
   {
    //Find number of dimensions of the node
    const unsigned n_dim = Fluid_mesh_pt->node_pt(n)->ndim();
    //Set the position error to zero
    double node_position_error = 0.0;
    //Loop over the dimensions
    for(unsigned i=0;i<n_dim;i++)
     {
      //Get position error
      double error =
       Fluid_mesh_pt->node_pt(n)->position_time_stepper_pt()->
       temporal_error_in_position(Fluid_mesh_pt->node_pt(n),i);
      //Add the square of the individual error to the position error
      node_position_error += error*error;
     }
    //Divide the position error by the number of dimensions
    node_position_error /= n_dim;
   //Now add to the global error
    global_error += node_position_error;
   }
  //Now the global error must be divided by the number of nodes
  global_error /= n_node;
  oomph_info << "done global error = " << global_error << std::endl;
  //Return the square root of the errr
  return sqrt(global_error);
 }
References calibrate::error, i, n, oomph::oomph_info, and sqrt().
height_central_node()
template<class ELEMENT > double VibratingShellProblem< ELEMENT >::height_central_node () inline
Get the height at the centre node.
   {
    return Central_node_on_free_surface_pt->x(1);
   }
next_dt()
template<class ELEMENT > double& VibratingShellProblem< ELEMENT >::next_dt () inline
Access the next suggested timestep.
 {return Next_dt;}
restart()
template<class ELEMENT > void VibratingShellProblem< ELEMENT >::restart () inline
Restart.
   {
    // Pointer to restart file
    ifstream* restart_file_pt=0;
    // Open restart file from stem
    restart_file_pt=new ifstream(Problem_Parameter::Restart_file.c_str(),
                                 ios_base::in);
    if (restart_file_pt!=0)
     {
      oomph_info << "Have opened "
                 << Problem_Parameter::Restart_file.c_str()
                 << " for restart. " << std::endl;
     }
    else
     {
      std::ostringstream error_stream;
      error_stream
       << "ERROR while trying to open "
       << Problem_Parameter::Restart_file.c_str()
       << " for restart." << std::endl;
      throw OomphLibError(
       error_stream.str(),
       "restart()",
       OOMPH_EXCEPTION_LOCATION);
     }
    // Read restart data:
    //-------------------
    if (restart_file_pt!=0)
     {
      // Doc number for trace
      //---------------------
      // Read line up to termination sign
      string input_string;
      getline(*restart_file_pt,input_string,'#');
      // Ignore rest of line
      restart_file_pt->ignore(80,'\n');
      // Doc number
      Problem_Parameter::Doc_info_trace.number()=unsigned(atoi(input_string.c_str()));
      // Doc number for solution
      //---------------------
      // Read line up to termination sign
      getline(*restart_file_pt,input_string,'#');
      // Ignore rest of line
      restart_file_pt->ignore(80,'\n');
      // Doc number
      Problem_Parameter::Doc_info_soln.number()=unsigned(atoi(input_string.c_str()));
      // Next timestep (required for restart from temporally adaptive run
      //-----------------------------------------------------------------
      // Read line up to termination sign
      getline(*restart_file_pt,input_string,'#');
      // Ignore rest of line
      restart_file_pt->ignore(80,'\n');
      // Next timestep
      Next_dt=double(atof(input_string.c_str()));
      // Refine the mesh and read in the generic problem data
      Problem::read(*restart_file_pt);
     }
   }
References oomph::Problem_Parameter::Doc_info_soln, oomph::Problem_Parameter::Doc_info_trace, oomph::DocInfo::number(), OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, Eigen::TensorSycl::internal::read(), and oomph::Problem_Parameter::Restart_file.
set_nprev_for_extrapolation_of_strain_rate_for_all_elements()
template<class ELEMENT > void VibratingShellProblem< ELEMENT >::set_nprev_for_extrapolation_of_strain_rate_for_all_elements (const unsigned & nprev) inline
   {
    unsigned n_element = Fluid_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement to the present element
      ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Fluid_mesh_pt->element_pt(e));
      // Use extrapolated strain rate when determining viscosity?
      if (!CommandLineArgs::command_line_flag_has_been_set
          ("--use_current_strainrate_for_viscosity"))
       {
        el_pt->use_extrapolated_strainrate_to_compute_second_invariant();
        // Set extrapolation order
        el_pt->nprev_for_extrapolation_of_strain_rate()=nprev;
       }
      else
       {
        el_pt->use_current_strainrate_to_compute_second_invariant();
       }
     }
   }
References oomph::CommandLineArgs::command_line_flag_has_been_set(), and e().
strainrate_norm()
template<class ELEMENT > double VibratingShellProblem< ELEMENT >::strainrate_norm () inline
   {
    // Compute current volume and error in extrapolation from fluid elements
    double norm_squared=0.0;
    double extrapolated_norm_squared=0.0;
    double error_norm_squared=0.0;
    unsigned nel=Fluid_mesh_pt->nelement();
    for (unsigned e=0;e<nel;e++)
     {
      // Get element
      ELEMENT* el_pt=dynamic_cast<ELEMENT*>(
       Fluid_mesh_pt->element_pt(e));
      // Get norms of invariant
      double el_norm_squared=0.0;
      double el_extrapolated_norm_squared=0.0;
      double el_error_norm_squared=0.0;
      double test_size=0.0;
      test_size=el_pt->square_of_norm_of_strain_invariant(
       el_norm_squared,
       el_extrapolated_norm_squared,
       el_error_norm_squared);
      // Add it...
      norm_squared+=el_norm_squared;
      extrapolated_norm_squared+=el_extrapolated_norm_squared;
      error_norm_squared+=el_error_norm_squared;
     }
    return sqrt(norm_squared);
   }
References e(), and sqrt().
update_latest_fixed_point_iteration_guess_for_strain_rate_for_all_elements()
template<class ELEMENT > void VibratingShellProblem< ELEMENT >::update_latest_fixed_point_iteration_guess_for_strain_rate_for_all_elements () inline
Update latest guess for strain rate.
   {
    unsigned n_element = Fluid_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement to the present element
      ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Fluid_mesh_pt->element_pt(e));
      el_pt->update_latest_fixed_point_iteration_guess_for_strain_rate();
     }
   }
References e().
Member Data Documentation
Central_node_on_free_surface_pt
template<class ELEMENT > Node* VibratingShellProblem< ELEMENT >::Central_node_on_free_surface_pt private
Pointer to free surface node on symmetry line.
External_pressure_data_pt
template<class ELEMENT > Data* VibratingShellProblem< ELEMENT >::External_pressure_data_pt private
Pointer to a global external pressure datum.
Fluid_mesh_pt
template<class ELEMENT > RefineableSolidTriangleMesh<ELEMENT>* VibratingShellProblem< ELEMENT >::Fluid_mesh_pt private
Pointer to Fluid_mesh.
Free_surface_mesh_pt
template<class ELEMENT > Mesh* VibratingShellProblem< ELEMENT >::Free_surface_mesh_pt private
Pointers to mesh of free surface elements.
Internal_open_boundary_pt
template<class ELEMENT > Vector<TriangleMeshOpenCurve* > VibratingShellProblem< ELEMENT >::Internal_open_boundary_pt private
Next_dt
template<class ELEMENT > double VibratingShellProblem< ELEMENT >::Next_dt private
Suggestion for the next timestep (allows it to be written to or read from a restart file)
Outer_boundary_polyline_pt
template<class ELEMENT > TriangleMeshClosedCurve* VibratingShellProblem< ELEMENT >::Outer_boundary_polyline_pt private
Triangle mesh polygon for outer boundary.
Pext
template<class ELEMENT > double VibratingShellProblem< ELEMENT >::Pext private
External pressure.
The documentation for this class was generated from the following file:
vibrating_shell_non_newtonian.cc