MercuryDPM: oomph::TriangleMeshCurviLine Class Reference
oomph::TriangleMeshCurviLine Class Reference
#include <unstructured_two_d_mesh_geometry_base.h>
Public Member Functions
TriangleMeshCurviLine (GeomObject *geom_object_pt, const double &zeta_start, const double &zeta_end, const unsigned &nsegment, const unsigned &boundary_id, const bool &space_vertices_evenly_in_arclength=true, const unsigned &boundary_chunk=0)
virtual ~TriangleMeshCurviLine ()
Empty Destuctor.
GeomObject * geom_object_pt ()
Pointer to GeomObject that represents this part of the boundary.
double zeta_start ()
Start coordinate in terms of the GeomObject's intrinsic coordinate.
double zeta_end ()
End coordinate in terms of the GeomObject's intrinsic coordinate.
unsigned nsegment () const
unsigned & nsegment ()
unsigned boundary_id () const
Boundary ID.
unsigned boundary_chunk () const
void output (std::ostream &outfile, const unsigned &n_sample=50)
Output curvilinear boundary at n_sample (default: 50) points.
bool space_vertices_evenly_in_arclength () const
unsigned nvertex () const
Number of vertices.
void initial_vertex_coordinate (Vector< double > &vertex)
Get first vertex coordinates.
void final_vertex_coordinate (Vector< double > &vertex)
Get last vertex coordinates.
bool are_there_connection_points ()
Does the vector for storing connections has elements?
Vector< double > * connection_points_pt ()
Returns the connection points vector.
void add_connection_point (const double &z_value, const double &tol=1.0e-12)
Public Member Functions inherited from oomph::TriangleMeshCurveSection
TriangleMeshCurveSection ()
Empty constructor. Initialises the curve section as non connected.
virtual ~TriangleMeshCurveSection ()
Empty destructor.
void enable_refinement_tolerance (const double &tolerance=0.08)
void set_refinement_tolerance (const double &tolerance)
double refinement_tolerance ()
void disable_refinement_tolerance ()
Disable refinement of curve section.
void enable_unrefinement_tolerance (const double &tolerance=0.04)
void set_unrefinement_tolerance (const double &tolerance)
double unrefinement_tolerance ()
void disable_unrefinement_tolerance ()
Disable unrefinement of curve sections.
void set_maximum_length (const double &maximum_length)
void disable_use_maximum_length ()
double maximum_length ()
Gets access to the maximum length variable.
void connect_initial_vertex_to_polyline (TriangleMeshPolyLine *polyline_pt, const unsigned &vertex_number, const double &tolerance_for_connection=1.0e-14)
void connect_final_vertex_to_polyline (TriangleMeshPolyLine *polyline_pt, const unsigned &vertex_number, const double &tolerance_for_connection=1.0e-14)
void connect_initial_vertex_to_curviline (TriangleMeshCurviLine *curviline_pt, const double &s_value, const double &tolerance_for_connection=1.0e-14)
void connect_final_vertex_to_curviline (TriangleMeshCurviLine *curviline_pt, const double &s_value, const double &tolerance_for_connection=1.0e-14)
bool is_initial_vertex_connected () const
Test whether initial vertex is connected or not.
void set_initial_vertex_connected ()
Sets the initial vertex as connected.
void unset_initial_vertex_connected ()
Sets the initial vertex as non connected.
void suspend_initial_vertex_connected ()
void resume_initial_vertex_connected ()
bool is_final_vertex_connected () const
Test whether final vertex is connected or not.
void set_final_vertex_connected ()
Sets the final vertex as connected.
void unset_final_vertex_connected ()
Sets the final vertex as non connected.
void suspend_final_vertex_connected ()
void resume_final_vertex_connected ()
unsigned initial_vertex_connected_bnd_id () const
Gets the id to which the initial end is connected.
unsigned & initial_vertex_connected_bnd_id ()
Sets the id to which the initial end is connected.
unsigned initial_vertex_connected_n_vertex () const
Gets the vertex number to which the initial end is connected.
unsigned & initial_vertex_connected_n_vertex ()
Sets the vertex number to which the initial end is connected.
unsigned initial_vertex_connected_n_chunk () const
Gets the boundary chunk to which the initial end is connected.
unsigned & initial_vertex_connected_n_chunk ()
Sets the boundary chunk to which the initial end is connected.
unsigned final_vertex_connected_bnd_id () const
Gets the id to which the final end is connected.
unsigned & final_vertex_connected_bnd_id ()
Sets the id to which the final end is connected.
unsigned final_vertex_connected_n_vertex () const
Sets the vertex number to which the final end is connected.
unsigned & final_vertex_connected_n_vertex ()
Gets the vertex number to which the final end is connected.
unsigned final_vertex_connected_n_chunk () const
Gets the boundary chunk to which the final end is connected.
unsigned & final_vertex_connected_n_chunk ()
Sets the boundary chunk to which the final end is connected.
bool is_initial_vertex_connected_to_curviline () const
Test whether the initial vertex is connected to a curviline.
void set_initial_vertex_connected_to_curviline ()
Sets the initial vertex as connected to a curviline.
void unset_initial_vertex_connected_to_curviline ()
Sets the initial vertex as non connected to a curviline.
bool is_final_vertex_connected_to_curviline () const
Test whether the final vertex is connected to a curviline.
void set_final_vertex_connected_to_curviline ()
Sets the final vertex as connected to a curviline.
void unset_final_vertex_connected_to_curviline ()
Sets the final vertex as non connected to a curviline.
double initial_s_connection_value () const
Gets the s value to which the initial end is connected.
double & initial_s_connection_value ()
Sets the s value to which the initial end is connected.
double final_s_connection_value () const
Gets the s value to which the final end is connected.
double & final_s_connection_value ()
Sets the s value to which the final end is connected.
double tolerance_for_s_connection () const
double & tolerance_for_s_connection ()
Private Attributes
GeomObject * Geom_object_pt
Pointer to GeomObject that represents this part of the boundary.
double Zeta_start
Start coordinate in terms of the GeomObject's intrinsic coordinate.
double Zeta_end
End coordinate in terms of the GeomObject's intrinsic coordinate.
unsigned Nsegment
unsigned Boundary_id
Boundary ID.
bool Space_vertices_evenly_in_arclength
unsigned Boundary_chunk
Vector< double > Connection_points_pt
Additional Inherited Members
Protected Attributes inherited from oomph::TriangleMeshCurveSection
bool Initial_vertex_connected
bool Final_vertex_connected
bool Initial_vertex_connected_suspended
bool Final_vertex_connected_suspended
unsigned Initial_vertex_connected_bnd_id
Stores the id to which the initial end is connected.
unsigned Initial_vertex_connected_n_vertex
unsigned Initial_vertex_connected_n_chunk
unsigned Final_vertex_connected_bnd_id
Stores the id to which the initial end is connected.
unsigned Final_vertex_connected_n_vertex
unsigned Final_vertex_connected_n_chunk
bool Initial_vertex_connected_to_curviline
States if the initial vertex is connected to a curviline.
bool Final_vertex_connected_to_curviline
States if the final vertex is connected to a curviline.
double Initial_s_connection_value
double Final_s_connection_value
double Tolerance_for_s_connection
Tolerance used for connecting the ends to a curviline.
Detailed Description
Class definining a curvilinear triangle mesh boundary in terms of a GeomObject. Curvlinear equivalent of PolyLine.
Constructor & Destructor Documentation
TriangleMeshCurviLine()
oomph::TriangleMeshCurviLine::TriangleMeshCurviLine (GeomObject * geom_object_pt, const double & zeta_start, const double & zeta_end, const unsigned & nsegment, const unsigned & boundary_id, const bool & space_vertices_evenly_in_arclength = true, const unsigned & boundary_chunk = 0) inline
Constructor: Specify GeomObject, the start and end coordinates of the relevant boundary in terms of the GeomObject's intrinsic coordinate, the number of (initially straight-line) segments that this GeomObject is to be split up into, and the boundary ID. The final optional boolean argument specifies if vertices in polygonhal represenation are spaced (approximately) evenly in arclength along the GeomObject [true, default] or in equal increments in zeta. This is the curvlinear equivalent of PolyLine.
       : TriangleMeshCurveSection(),
         Geom_object_pt(geom_object_pt),
         Zeta_start(zeta_start),
         Zeta_end(zeta_end),
         Nsegment(nsegment),
         Boundary_id(boundary_id),
         Space_vertices_evenly_in_arclength(space_vertices_evenly_in_arclength),
         Boundary_chunk(boundary_chunk)
     {
     }
~TriangleMeshCurviLine()
virtual oomph::TriangleMeshCurviLine::~TriangleMeshCurviLine () inline virtual
Empty Destuctor.
 {}
Member Function Documentation
add_connection_point()
void oomph::TriangleMeshCurviLine::add_connection_point (const double & z_value, const double & tol = 1.0e-12) inline
Add the connection point (z_value) to the connection points that receive the curviline
     {
       // If we are trying to connect to the initial or final
       // point then it is not necessary to add this point
       // to the list since it will explicitly be created when
       // transforming the curviline to polyline
       if (std::fabs(z_value - Zeta_start) < tol ||
           std::fabs(z_value - Zeta_end) < tol)
       {
         return;
       }
       // We need to deal with repeated connection points,
       // if the connection point is already in the list then
       // we will not add it!!!
       // Search for repeated elements
       unsigned n_size = Connection_points_pt.size();
       for (unsigned i = 0; i < n_size; i++)
       {
         if (fabs(z_value - Connection_points_pt[i]) < tol)
         {
           return;
         }
       }
       // Only add the connection point if it is not the
       // initial or final zeta value and it is not already on the
       // list
       Connection_points_pt.push_back(z_value);
     }
References Connection_points_pt, boost::multiprecision::fabs(), i, Zeta_end, and Zeta_start.
Referenced by oomph::TriangleMeshCurveSection::connect_final_vertex_to_curviline(), and oomph::TriangleMeshCurveSection::connect_initial_vertex_to_curviline().
are_there_connection_points()
bool oomph::TriangleMeshCurviLine::are_there_connection_points () inline
Does the vector for storing connections has elements?
     {
       return !Connection_points_pt.empty();
     }
References Connection_points_pt.
boundary_chunk()
unsigned oomph::TriangleMeshCurviLine::boundary_chunk () const inline virtual
Boundary chunk (Used when a boundary is represented by more than one polyline
Implements oomph::TriangleMeshCurveSection.
     {
       return Boundary_chunk;
     }
References Boundary_chunk.
Referenced by oomph::TriangleMeshCurveSection::connect_final_vertex_to_curviline(), and oomph::TriangleMeshCurveSection::connect_initial_vertex_to_curviline().
boundary_id()
unsigned oomph::TriangleMeshCurviLine::boundary_id () const inline virtual
Boundary ID.
Implements oomph::TriangleMeshCurveSection.
     {
       return Boundary_id;
     }
References Boundary_id.
Referenced by oomph::TriangleMeshCurveSection::connect_final_vertex_to_curviline(), and oomph::TriangleMeshCurveSection::connect_initial_vertex_to_curviline().
connection_points_pt()
Vector<double>* oomph::TriangleMeshCurviLine::connection_points_pt () inline
Returns the connection points vector.
     {
       return &Connection_points_pt;
     }
References Connection_points_pt.
final_vertex_coordinate()
void oomph::TriangleMeshCurviLine::final_vertex_coordinate (Vector< double > & vertex) inline virtual
Get last vertex coordinates.
Implements oomph::TriangleMeshCurveSection.
     {
       Vector<double> z(1);
       z[0] = Zeta_end;
       Geom_object_pt->position(z, vertex);
     }
References Geom_object_pt, oomph::GeomObject::position(), and Zeta_end.
geom_object_pt()
GeomObject* oomph::TriangleMeshCurviLine::geom_object_pt () inline
Pointer to GeomObject that represents this part of the boundary.
     {
       return Geom_object_pt;
     }
References Geom_object_pt.
Referenced by oomph::TriangleMeshCurveSection::connect_final_vertex_to_curviline(), and oomph::TriangleMeshCurveSection::connect_initial_vertex_to_curviline().
initial_vertex_coordinate()
void oomph::TriangleMeshCurviLine::initial_vertex_coordinate (Vector< double > & vertex) inline virtual
Get first vertex coordinates.
Implements oomph::TriangleMeshCurveSection.
     {
       Vector<double> z(1);
       z[0] = Zeta_start;
       Geom_object_pt->position(z, vertex);
     }
References Geom_object_pt, oomph::GeomObject::position(), and Zeta_start.
nsegment() [1/2]
unsigned& oomph::TriangleMeshCurviLine::nsegment () inline
Number of (initially straight-line) segments that this part of the boundary is to be represented by. This version allows the change of the number of segments
     {
       return Nsegment;
     }
References Nsegment.
nsegment() [2/2]
unsigned oomph::TriangleMeshCurviLine::nsegment () const inline virtual
Number of (initially straight-line) segments that this part of the boundary is to be represented by
Implements oomph::TriangleMeshCurveSection.
     {
       return Nsegment;
     }
References Nsegment.
nvertex()
unsigned oomph::TriangleMeshCurviLine::nvertex () const inline virtual
Number of vertices.
Implements oomph::TriangleMeshCurveSection.
     {
       return 2;
     }
output()
void oomph::TriangleMeshCurviLine::output (std::ostream & outfile, const unsigned & n_sample = 50) inline virtual
Output curvilinear boundary at n_sample (default: 50) points.
Implements oomph::TriangleMeshCurveSection.
     {
       outfile << "ZONE T=\"Boundary " << Boundary_id << "\"\n";
       Vector<double> zeta(1);
       Vector<double> r(2);
       for (unsigned i = 0; i < n_sample; i++)
       {
         zeta[0] = Zeta_start +
                   (Zeta_end - Zeta_start) * double(i) / double(n_sample - 1);
         Geom_object_pt->position(zeta, r);
         outfile << r[0] << " " << r[1] << std::endl;
       }
     }
References Boundary_id, Geom_object_pt, i, oomph::GeomObject::position(), UniformPSDSelfTest::r, Eigen::zeta(), Zeta_end, and Zeta_start.
space_vertices_evenly_in_arclength()
bool oomph::TriangleMeshCurviLine::space_vertices_evenly_in_arclength () const inline
Boolean to indicate if vertices in polygonal representation of the Curvline are spaced (approximately) evenly in arclength along the GeomObject [true] or in equal increments in zeta [false]
     {
       return Space_vertices_evenly_in_arclength;
     }
References Space_vertices_evenly_in_arclength.
zeta_end()
double oomph::TriangleMeshCurviLine::zeta_end () inline
End coordinate in terms of the GeomObject's intrinsic coordinate.
     {
       return Zeta_end;
     }
References Zeta_end.
Referenced by oomph::TriangleMeshCurveSection::connect_final_vertex_to_curviline(), and oomph::TriangleMeshCurveSection::connect_initial_vertex_to_curviline().
zeta_start()
double oomph::TriangleMeshCurviLine::zeta_start () inline
Start coordinate in terms of the GeomObject's intrinsic coordinate.
     {
       return Zeta_start;
     }
References Zeta_start.
Referenced by oomph::TriangleMeshCurveSection::connect_final_vertex_to_curviline(), and oomph::TriangleMeshCurveSection::connect_initial_vertex_to_curviline().
Member Data Documentation
Boundary_chunk
unsigned oomph::TriangleMeshCurviLine::Boundary_chunk private
Boundary chunk (Used when a boundary is represented by more than one polyline
Referenced by boundary_chunk().
Boundary_id
unsigned oomph::TriangleMeshCurviLine::Boundary_id private
Boundary ID.
Referenced by boundary_id(), and output().
Connection_points_pt
Vector<double> oomph::TriangleMeshCurviLine::Connection_points_pt private
Stores the information for connections received on the curviline. Used when converting to polyline
Referenced by add_connection_point(), are_there_connection_points(), and connection_points_pt().
Geom_object_pt
GeomObject* oomph::TriangleMeshCurviLine::Geom_object_pt private
Pointer to GeomObject that represents this part of the boundary.
Referenced by final_vertex_coordinate(), geom_object_pt(), initial_vertex_coordinate(), and output().
Nsegment
unsigned oomph::TriangleMeshCurviLine::Nsegment private
Number of (initially straight-line) segments that this part of the boundary is to be represented by
Referenced by nsegment().
Space_vertices_evenly_in_arclength
bool oomph::TriangleMeshCurviLine::Space_vertices_evenly_in_arclength private
Boolean to indicate if vertices in polygonal representation of the Curviline are spaced (approximately) evenly in arclength along the GeomObject [true] or in equal increments in zeta [false]
Referenced by space_vertices_evenly_in_arclength().
Zeta_end
double oomph::TriangleMeshCurviLine::Zeta_end private
End coordinate in terms of the GeomObject's intrinsic coordinate.
Referenced by add_connection_point(), final_vertex_coordinate(), output(), and zeta_end().
Zeta_start
double oomph::TriangleMeshCurviLine::Zeta_start private
Start coordinate in terms of the GeomObject's intrinsic coordinate.
Referenced by add_connection_point(), initial_vertex_coordinate(), output(), and zeta_start().
The documentation for this class was generated from the following file:
unstructured_two_d_mesh_geometry_base.h