MercuryDPM: Eigen::internal::TensorBlockDescriptor< NumDims, IndexType > Class Template Reference
Eigen::internal::TensorBlockDescriptor< NumDims, IndexType > Class Template Reference
#include <TensorBlock.h>
Classes
class DestinationBuffer
Public Types
typedef DSizes< IndexType, NumDims > Dimensions
Public Member Functions
TensorBlockDescriptor (const IndexType offset, const Dimensions &dimensions, const DestinationBuffer &destination)
TensorBlockDescriptor (const IndexType offset, const Dimensions &dimensions)
IndexType offset () const
const Dimensions & dimensions () const
IndexType dimension (int index) const
IndexType size () const
const DestinationBuffer & destination () const
template<int Layout, typename Scalar >
void AddDestinationBuffer (Scalar *dst_base, const Dimensions &dst_strides)
template<int Layout, typename Scalar , typename DstStridesIndexType >
void AddDestinationBuffer (Scalar *dst_base, const DSizes< DstStridesIndexType, NumDims > &dst_strides)
TensorBlockDescriptor & DropDestinationBuffer ()
bool HasDestinationBuffer () const
TensorBlockDescriptor WithOffset (IndexType offset) const
Private Attributes
const IndexType m_offset
const Dimensions m_dimensions
DestinationBuffer m_destination
Member Typedef Documentation
Dimensions
template<int NumDims, typename IndexType = Eigen::Index> typedef DSizes<IndexType, NumDims> Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::Dimensions
Constructor & Destructor Documentation
TensorBlockDescriptor() [1/2]
template<int NumDims, typename IndexType = Eigen::Index> Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::TensorBlockDescriptor (const IndexType offset, const Dimensions & dimensions, const DestinationBuffer & destination) inline
       : m_offset(offset), m_dimensions(dimensions), m_destination(destination) {}
Referenced by Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::WithOffset().
TensorBlockDescriptor() [2/2]
template<int NumDims, typename IndexType = Eigen::Index> Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::TensorBlockDescriptor (const IndexType offset, const Dimensions & dimensions) inline
       : m_offset(offset), m_dimensions(dimensions), m_destination(DestinationBuffer()) {}
Member Function Documentation
AddDestinationBuffer() [1/2]
template<int NumDims, typename IndexType = Eigen::Index> template<int Layout, typename Scalar > void Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::AddDestinationBuffer (Scalar * dst_base, const Dimensions & dst_strides) inline
{
     eigen_assert(dst_base != NULL);
     m_destination = DestinationBuffer::template make<Layout>(*this, dst_base, dst_strides);
   }
References eigen_assert, and Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::m_destination.
AddDestinationBuffer() [2/2]
template<int NumDims, typename IndexType = Eigen::Index> template<int Layout, typename Scalar , typename DstStridesIndexType > void Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::AddDestinationBuffer (Scalar * dst_base, const DSizes< DstStridesIndexType, NumDims > & dst_strides) inline
{
     // DSizes constructor will do index type promotion if it's safe.
     AddDestinationBuffer<Layout>(dst_base, Dimensions(dst_strides));
   }
destination()
template<int NumDims, typename IndexType = Eigen::Index> const DestinationBuffer& Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::destination () const inline
 { return m_destination; }
References Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::m_destination.
Referenced by Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::block(), and Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::prepareStorage().
dimension()
template<int NumDims, typename IndexType = Eigen::Index> IndexType Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::dimension (int index) const inline
 { return m_dimensions[index]; }
References Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::m_dimensions.
Referenced by Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::block(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::materialize(), VerifyBlockEvaluator(), Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::writeBlock(), and Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::writeBlock().
dimensions()
template<int NumDims, typename IndexType = Eigen::Index> const Dimensions& Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::dimensions () const inline
 { return m_dimensions; }
References Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::m_dimensions.
Referenced by Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::blockBroadcastingParams(), Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::evalBlock(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::DestinationBuffer::kind(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::materialize(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::prepareStorage(), VerifyBlockAssignment(), VerifyBlockEvaluator(), Eigen::TensorEvaluator< Derived, Device >::writeBlock(), Eigen::TensorEvaluator< TensorReshapingOp< NewDimensions, ArgType >, Device >::writeBlock(), and Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::writeBlock().
DropDestinationBuffer()
template<int NumDims, typename IndexType = Eigen::Index> TensorBlockDescriptor& Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::DropDestinationBuffer () inline
{
     m_destination.m_data = NULL;
     m_destination.m_kind = DestinationBuffer::kEmpty;
     return *this;
   }
References Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::DestinationBuffer::kEmpty, Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::DestinationBuffer::m_data, Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::m_destination, and Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::DestinationBuffer::m_kind.
Referenced by Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::block(), and Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::prepareStorage().
HasDestinationBuffer()
template<int NumDims, typename IndexType = Eigen::Index> bool Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::HasDestinationBuffer () const inline
 { return m_destination.kind() != DestinationBuffer::kEmpty; }
References Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::DestinationBuffer::kEmpty, Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::DestinationBuffer::kind(), and Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::m_destination.
Referenced by Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::block(), and Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::block().
offset()
template<int NumDims, typename IndexType = Eigen::Index> IndexType Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::offset () const inline
 { return m_offset; }
References Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::m_offset.
Referenced by Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::evalBlock(), Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::evalBlock(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::materialize(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::WithOffset(), Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::writeBlock(), Eigen::TensorEvaluator< Derived, Device >::writeBlock(), Eigen::TensorEvaluator< TensorReshapingOp< NewDimensions, ArgType >, Device >::writeBlock(), Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::writeBlock(), and Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::writeBlock().
size()
template<int NumDims, typename IndexType = Eigen::Index> IndexType Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::size () const inline
 { return array_prod<IndexType>(m_dimensions); }
References Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::m_dimensions.
Referenced by Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::block(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::prepareStorage(), and Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::writeBlock().
WithOffset()
template<int NumDims, typename IndexType = Eigen::Index> TensorBlockDescriptor Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::WithOffset (IndexType offset) const inline
{
     return TensorBlockDescriptor(offset, m_dimensions, m_destination);
   }
References Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::m_destination, Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::m_dimensions, Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::offset(), and Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::TensorBlockDescriptor().
Referenced by Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::block(), and Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::writeBlock().
Member Data Documentation
m_destination
template<int NumDims, typename IndexType = Eigen::Index> DestinationBuffer Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::m_destination private
Referenced by Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::AddDestinationBuffer(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::destination(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::DropDestinationBuffer(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::HasDestinationBuffer(), and Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::WithOffset().
m_dimensions
template<int NumDims, typename IndexType = Eigen::Index> const Dimensions Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::m_dimensions private
Referenced by Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::dimension(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::dimensions(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::size(), and Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::WithOffset().
m_offset
template<int NumDims, typename IndexType = Eigen::Index> const IndexType Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::m_offset private
Referenced by Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::offset().
The documentation for this class was generated from the following file:
TensorBlock.h