MercuryDPM: Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape > Struct Template Reference
Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape > Struct Template Reference
#include <ProductEvaluators.h>
Public Types
enum {
RowsAtCompileTime = LhsNestedCleaned::RowsAtCompileTime , ColsAtCompileTime = RhsNestedCleaned::ColsAtCompileTime , InnerSize = min_size_prefer_fixed(LhsNestedCleaned::ColsAtCompileTime, RhsNestedCleaned::RowsAtCompileTime) , MaxRowsAtCompileTime = LhsNestedCleaned::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = RhsNestedCleaned::MaxColsAtCompileTime
}
enum { LhsCoeffReadCost = LhsEtorType::CoeffReadCost , RhsCoeffReadCost = RhsEtorType::CoeffReadCost , CoeffReadCost }
typedef Product< Lhs, Rhs, LazyProduct > XprType
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef internal::nested_eval< Lhs, Rhs::ColsAtCompileTime >::type LhsNested
typedef internal::nested_eval< Rhs, Lhs::RowsAtCompileTime >::type RhsNested
typedef internal::remove_all_t< LhsNested > LhsNestedCleaned
typedef internal::remove_all_t< RhsNested > RhsNestedCleaned
typedef evaluator< LhsNestedCleaned > LhsEtorType
typedef evaluator< RhsNestedCleaned > RhsEtorType
typedef find_best_packet< Scalar, RowsAtCompileTime >::type LhsVecPacketType
typedef find_best_packet< Scalar, ColsAtCompileTime >::type RhsVecPacketType
Public Types inherited from Eigen::internal::evaluator_base< Product< Lhs, Rhs, LazyProduct > >
enum
typedef traits< Product< Lhs, Rhs, LazyProduct > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE product_evaluator (const XprType &xpr)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CoeffReturnType coeff (Index index) const
template<int LoadMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const PacketType packet (Index index) const
Public Member Functions inherited from Eigen::internal::evaluator_base< Product< Lhs, Rhs, LazyProduct > >
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE evaluator_base ()=default
Protected Attributes
add_const_on_value_type_t< LhsNested > m_lhs
add_const_on_value_type_t< RhsNested > m_rhs
LhsEtorType m_lhsImpl
RhsEtorType m_rhsImpl
Index m_innerDim
Member Typedef Documentation
CoeffReturnType
template<typename Lhs , typename Rhs , int ProductTag> typedef XprType::CoeffReturnType Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::CoeffReturnType
LhsEtorType
template<typename Lhs , typename Rhs , int ProductTag> typedef evaluator<LhsNestedCleaned> Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::LhsEtorType
LhsNested
template<typename Lhs , typename Rhs , int ProductTag> typedef internal::nested_eval<Lhs, Rhs::ColsAtCompileTime>::type Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::LhsNested
LhsNestedCleaned
template<typename Lhs , typename Rhs , int ProductTag> typedef internal::remove_all_t<LhsNested> Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::LhsNestedCleaned
LhsVecPacketType
template<typename Lhs , typename Rhs , int ProductTag> typedef find_best_packet<Scalar, RowsAtCompileTime>::type Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::LhsVecPacketType
RhsEtorType
template<typename Lhs , typename Rhs , int ProductTag> typedef evaluator<RhsNestedCleaned> Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::RhsEtorType
RhsNested
template<typename Lhs , typename Rhs , int ProductTag> typedef internal::nested_eval<Rhs, Lhs::RowsAtCompileTime>::type Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::RhsNested
RhsNestedCleaned
template<typename Lhs , typename Rhs , int ProductTag> typedef internal::remove_all_t<RhsNested> Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::RhsNestedCleaned
RhsVecPacketType
template<typename Lhs , typename Rhs , int ProductTag> typedef find_best_packet<Scalar, ColsAtCompileTime>::type Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::RhsVecPacketType
Scalar
template<typename Lhs , typename Rhs , int ProductTag> typedef XprType::Scalar Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::Scalar
XprType
template<typename Lhs , typename Rhs , int ProductTag> typedef Product<Lhs, Rhs, LazyProduct> Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::XprType
Member Enumeration Documentation
anonymous enum
template<typename Lhs , typename Rhs , int ProductTag> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
InnerSize
MaxRowsAtCompileTime
MaxColsAtCompileTime
        {
     RowsAtCompileTime = LhsNestedCleaned::RowsAtCompileTime,
     ColsAtCompileTime = RhsNestedCleaned::ColsAtCompileTime,
     InnerSize = min_size_prefer_fixed(LhsNestedCleaned::ColsAtCompileTime, RhsNestedCleaned::RowsAtCompileTime),
     MaxRowsAtCompileTime = LhsNestedCleaned::MaxRowsAtCompileTime,
     MaxColsAtCompileTime = RhsNestedCleaned::MaxColsAtCompileTime
   };
anonymous enum
template<typename Lhs , typename Rhs , int ProductTag> anonymous enum
Enumerator
LhsCoeffReadCost
RhsCoeffReadCost
CoeffReadCost
        {
     LhsCoeffReadCost = LhsEtorType::CoeffReadCost,
     RhsCoeffReadCost = RhsEtorType::CoeffReadCost,
     CoeffReadCost = InnerSize == 0 ? NumTraits<Scalar>::ReadCost
                     : InnerSize == Dynamic
                         ? HugeCost
                         : InnerSize * (NumTraits<Scalar>::MulCost + int(LhsCoeffReadCost) + int(RhsCoeffReadCost)) +
                               (InnerSize - 1) * NumTraits<Scalar>::AddCost,
     Unroll = CoeffReadCost <= EIGEN_UNROLLING_LIMIT,
     LhsFlags = LhsEtorType::Flags,
     RhsFlags = RhsEtorType::Flags,
     LhsRowMajor = LhsFlags & RowMajorBit,
     RhsRowMajor = RhsFlags & RowMajorBit,
     LhsVecPacketSize = unpacket_traits<LhsVecPacketType>::size,
     RhsVecPacketSize = unpacket_traits<RhsVecPacketType>::size,
     // Here, we don't care about alignment larger than the usable packet size.
     LhsAlignment =
         plain_enum_min(LhsEtorType::Alignment, LhsVecPacketSize* int(sizeof(typename LhsNestedCleaned::Scalar))),
     RhsAlignment =
         plain_enum_min(RhsEtorType::Alignment, RhsVecPacketSize* int(sizeof(typename RhsNestedCleaned::Scalar))),
     SameType = is_same<typename LhsNestedCleaned::Scalar, typename RhsNestedCleaned::Scalar>::value,
     CanVectorizeRhs = bool(RhsRowMajor) && (RhsFlags & PacketAccessBit) && (ColsAtCompileTime != 1),
     CanVectorizeLhs = (!LhsRowMajor) && (LhsFlags & PacketAccessBit) && (RowsAtCompileTime != 1),
     EvalToRowMajor = (MaxRowsAtCompileTime == 1 && MaxColsAtCompileTime != 1) ? 1
                      : (MaxColsAtCompileTime == 1 && MaxRowsAtCompileTime != 1)
                          ? 0
                          : (bool(RhsRowMajor) && !CanVectorizeLhs),
     Flags = ((int(LhsFlags) | int(RhsFlags)) & HereditaryBits & ~RowMajorBit) |
             (EvalToRowMajor ? RowMajorBit : 0)
             // TODO enable vectorization for mixed types
             | (SameType && (CanVectorizeLhs || CanVectorizeRhs) ? PacketAccessBit : 0) |
             (XprType::IsVectorAtCompileTime ? LinearAccessBit : 0),
     LhsOuterStrideBytes =
         int(LhsNestedCleaned::OuterStrideAtCompileTime) * int(sizeof(typename LhsNestedCleaned::Scalar)),
     RhsOuterStrideBytes =
         int(RhsNestedCleaned::OuterStrideAtCompileTime) * int(sizeof(typename RhsNestedCleaned::Scalar)),
     Alignment = bool(CanVectorizeLhs)
                     ? (LhsOuterStrideBytes <= 0 || (int(LhsOuterStrideBytes) % plain_enum_max(1, LhsAlignment)) != 0
                            ? 0
                            : LhsAlignment)
                 : bool(CanVectorizeRhs)
                     ? (RhsOuterStrideBytes <= 0 || (int(RhsOuterStrideBytes) % plain_enum_max(1, RhsAlignment)) != 0
                            ? 0
                            : RhsAlignment)
                     : 0,
     /* CanVectorizeInner deserves special explanation. It does not affect the product flags. It is not used outside
      * of Product. If the Product itself is not a packet-access expression, there is still a chance that the inner
      * loop of the product might be vectorized. This is the meaning of CanVectorizeInner. Since it doesn't affect
      * the Flags, it is safe to make this value depend on ActualPacketAccessBit, that doesn't affect the ABI.
      */
     CanVectorizeInner = SameType && LhsRowMajor && (!RhsRowMajor) &&
                         (int(LhsFlags) & int(RhsFlags) & ActualPacketAccessBit) &&
                         (int(InnerSize) % packet_traits<Scalar>::size == 0)
   };
Constructor & Destructor Documentation
product_evaluator()
template<typename Lhs , typename Rhs , int ProductTag> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::product_evaluator (const XprType & xpr) inline explicit
       : m_lhs(xpr.lhs()),
         m_rhs(xpr.rhs()),
         m_lhsImpl(m_lhs),  // FIXME the creation of the evaluator objects should result in a no-op, but check that!
         m_rhsImpl(m_rhs),  //       Moreover, they are only useful for the packet path, so we could completely disable
                            //       them when not needed, or perhaps declare them on the fly on the packet method... We
                            //       have experiment to check what's best.
         m_innerDim(xpr.lhs().cols()) {
     EIGEN_INTERNAL_CHECK_COST_VALUE(NumTraits<Scalar>::MulCost);
     EIGEN_INTERNAL_CHECK_COST_VALUE(NumTraits<Scalar>::AddCost);
     EIGEN_INTERNAL_CHECK_COST_VALUE(CoeffReadCost);
 #if 0
     std::cerr << "LhsOuterStrideBytes=  " << LhsOuterStrideBytes << "\n";
     std::cerr << "RhsOuterStrideBytes=  " << RhsOuterStrideBytes << "\n";
     std::cerr << "LhsAlignment=         " << LhsAlignment << "\n";
     std::cerr << "RhsAlignment=         " << RhsAlignment << "\n";
     std::cerr << "CanVectorizeLhs=      " << CanVectorizeLhs << "\n";
     std::cerr << "CanVectorizeRhs=      " << CanVectorizeRhs << "\n";
     std::cerr << "CanVectorizeInner=    " << CanVectorizeInner << "\n";
     std::cerr << "EvalToRowMajor=       " << EvalToRowMajor << "\n";
     std::cerr << "Alignment=            " << Alignment << "\n";
     std::cerr << "Flags=                " << Flags << "\n";
 #endif
   }
References EIGEN_INTERNAL_CHECK_COST_VALUE.
Member Function Documentation
coeff() [1/2]
template<typename Lhs , typename Rhs , int ProductTag> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CoeffReturnType Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::coeff (Index index) const inline
{
     const Index row = (RowsAtCompileTime == 1 || MaxRowsAtCompileTime == 1) ? 0 : index;
     const Index col = (RowsAtCompileTime == 1 || MaxRowsAtCompileTime == 1) ? index : 0;
     return (m_lhs.row(row).transpose().cwiseProduct(m_rhs.col(col))).sum();
   }
References col(), and row().
coeff() [2/2]
template<typename Lhs , typename Rhs , int ProductTag> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CoeffReturnType Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::coeff (Index row, Index col) const inline
{
     return (m_lhs.row(row).transpose().cwiseProduct(m_rhs.col(col))).sum();
   }
References col(), and row().
packet() [1/2]
template<typename Lhs , typename Rhs , int ProductTag> template<int LoadMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const PacketType Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::packet (Index index) const inline
{
     const Index row = (RowsAtCompileTime == 1 || MaxRowsAtCompileTime == 1) ? 0 : index;
     const Index col = (RowsAtCompileTime == 1 || MaxRowsAtCompileTime == 1) ? index : 0;
     return packet<LoadMode, PacketType>(row, col);
   }
References col(), and row().
packet() [2/2]
template<typename Lhs , typename Rhs , int ProductTag> template<int LoadMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const PacketType Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::packet (Index row, Index col) const inline
{
     PacketType res;
     typedef etor_product_packet_impl<bool(int(Flags) & RowMajorBit) ? RowMajor : ColMajor,
                                      Unroll ? int(InnerSize) : Dynamic, LhsEtorType, RhsEtorType, PacketType, LoadMode>
         PacketImpl;
     PacketImpl::run(row, col, m_lhsImpl, m_rhsImpl, m_innerDim, res);
     return res;
   }
References col(), Eigen::ColMajor, Eigen::Dynamic, int(), res, row(), Eigen::RowMajor, Eigen::RowMajorBit, and run().
Member Data Documentation
m_innerDim
template<typename Lhs , typename Rhs , int ProductTag> Index Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::m_innerDim protected
m_lhs
template<typename Lhs , typename Rhs , int ProductTag> add_const_on_value_type_t<LhsNested> Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::m_lhs protected
m_lhsImpl
template<typename Lhs , typename Rhs , int ProductTag> LhsEtorType Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::m_lhsImpl protected
m_rhs
template<typename Lhs , typename Rhs , int ProductTag> add_const_on_value_type_t<RhsNested> Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::m_rhs protected
m_rhsImpl
template<typename Lhs , typename Rhs , int ProductTag> RhsEtorType Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::m_rhsImpl protected
The documentation for this struct was generated from the following file:
ProductEvaluators.h