MercuryDPM: Eigen::internal::SingleRange< ValueAtCompileTime > Class Template Reference
Eigen::internal::SingleRange< ValueAtCompileTime > Class Template Reference
#include <IndexedViewHelper.h>
Public Member Functions
constexpr SingleRange (Index v) noexcept
constexpr Index operator[] (Index) const noexcept
constexpr Index first () const noexcept
constexpr Index size () const noexcept
constexpr Index incr () const noexcept
Static Public Attributes
static constexpr Index FirstAtCompileTime = ValueAtCompileTime
static constexpr Index SizeAtCompileTime = Index(1)
static constexpr Index IncrAtCompileTime = Index(1)
Private Attributes
variable_if_dynamicindex< Index, int(ValueAtCompileTime)> value_
Constructor & Destructor Documentation
SingleRange()
template<Index ValueAtCompileTime> constexpr Eigen::internal::SingleRange< ValueAtCompileTime >::SingleRange (Index v) inline constexpr noexcept
 : value_(v) {}
Member Function Documentation
first()
template<Index ValueAtCompileTime> constexpr Index Eigen::internal::SingleRange< ValueAtCompileTime >::first () const inline constexpr noexcept
 { return value_.value(); }
References Eigen::internal::variable_if_dynamicindex< T, Value >::value(), and Eigen::internal::SingleRange< ValueAtCompileTime >::value_.
Referenced by Eigen::internal::IndexedViewHelper< SingleRange< ValueAtCompileTime >, void >::first(), and Eigen::internal::SingleRange< ValueAtCompileTime >::operator[]().
incr()
template<Index ValueAtCompileTime> constexpr Index Eigen::internal::SingleRange< ValueAtCompileTime >::incr () const inline constexpr noexcept
 { return IncrAtCompileTime; }
References Eigen::internal::SingleRange< ValueAtCompileTime >::IncrAtCompileTime.
operator[]()
template<Index ValueAtCompileTime> constexpr Index Eigen::internal::SingleRange< ValueAtCompileTime >::operator[] (Index) const inline constexpr noexcept
 { return first(); }
References Eigen::internal::SingleRange< ValueAtCompileTime >::first().
size()
template<Index ValueAtCompileTime> constexpr Index Eigen::internal::SingleRange< ValueAtCompileTime >::size () const inline constexpr noexcept
 { return SizeAtCompileTime; }
References Eigen::internal::SingleRange< ValueAtCompileTime >::SizeAtCompileTime.
Member Data Documentation
FirstAtCompileTime
template<Index ValueAtCompileTime> constexpr Index Eigen::internal::SingleRange< ValueAtCompileTime >::FirstAtCompileTime = ValueAtCompileTime static constexpr
IncrAtCompileTime
template<Index ValueAtCompileTime> constexpr Index Eigen::internal::SingleRange< ValueAtCompileTime >::IncrAtCompileTime = Index(1) static constexpr
Referenced by Eigen::internal::SingleRange< ValueAtCompileTime >::incr().
SizeAtCompileTime
template<Index ValueAtCompileTime> constexpr Index Eigen::internal::SingleRange< ValueAtCompileTime >::SizeAtCompileTime = Index(1) static constexpr
Referenced by Eigen::internal::SingleRange< ValueAtCompileTime >::size().
value_
template<Index ValueAtCompileTime> variable_if_dynamicindex<Index, int(ValueAtCompileTime)> Eigen::internal::SingleRange< ValueAtCompileTime >::value_ private
Referenced by Eigen::internal::SingleRange< ValueAtCompileTime >::first().
The documentation for this class was generated from the following file:
IndexedViewHelper.h