MercuryDPM: MarbleRun.cpp File Reference
MarbleRun.cpp File Reference
#include <iostream>
#include <Species/LinearViscoelasticFrictionSpecies.h>
#include <Walls/TriangleWall.h>
#include "Mercury3D.h"
#include "Walls/InfiniteWall.h"
Classes
class MarbleRun
Functions
int main ()
Function Documentation
main()
int main ()
            {
     // Set up a problem of type MarbleRun
     MarbleRun dpm;
     // Set name of output files
     dpm.setName("MarbleRunConcept");
     // Set name of output files
     dpm.loadSTLFile("MarbleRun_Concept_STL_DwarshuisScholten.STL");
     // Set physical particle properties
     dpm.setParticlePosition(Vec3D(0.03,1,0.4)); // (0.03,1,0.9)
     dpm.setParticleRadius(0.01);
     // Set material particle properties
     dpm.setParticleDensity(1000);
     // Set contact properties
     dpm.setSlidingFrictionCoefficient(0.5);
     dpm.setRollingFrictionCoefficient(1e-2); // (1e-4)
     dpm.setTorsionFrictionCoefficient(0.0);
     dpm.setRestitutionCoefficient(0.5);
     // set gravity direction
     dpm.setGravity(Vec3D(0,-9.8,0));
     // Set simulation time
     dpm.setTimeMax(10.0);
     // start the solver
     dpm.solve();
 }
References e(), MarbleRun::loadSTLFile(), DPMBase::setGravity(), DPMBase::setName(), MarbleRun::setParticleDensity(), MarbleRun::setParticlePosition(), MarbleRun::setParticleRadius(), MarbleRun::setRestitutionCoefficient(), MarbleRun::setRollingFrictionCoefficient(), MarbleRun::setSlidingFrictionCoefficient(), DPMBase::setTimeMax(), MarbleRun::setTorsionFrictionCoefficient(), and DPMBase::solve().