MercuryDPM: linearised_fsi_pulsewave.cc File Reference
linearised_fsi_pulsewave.cc File Reference
#include "generic.h"
#include "axisym_navier_stokes.h"
#include "axisym_linear_elasticity.h"
#include "meshes/triangle_mesh.h"
Classes
class PressureWaveFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >
Problem class.
Namespaces
Global_Physical_Variables
Global variables.
Macros
#define DO_FSI
Functions
void Global_Physical_Variables::outside_solid_boundary_traction (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result)
Traction applied to the outside of the solid mesh.
void Global_Physical_Variables::fluid_inflow_boundary_traction (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result)
Inflow traction applied to the fluid mesh.
void Global_Physical_Variables::validation_solid_fsi_boundary_traction (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result)
Traction applied to the solid mesh at fsi interface (for validation only)
void Global_Physical_Variables::validation_fluid_fsi_boundary_traction (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result)
void Global_Physical_Variables::pulse_wave_solution (const double &time, const Vector< double > &x, Vector< double > &soln)
"Exact" solution for propagating pulse wave
void Global_Physical_Variables::update_dependent_parameters ()
Helper function to update dependent parameters.
void Global_Physical_Variables::doc_dependent_parameters ()
Doc dependent parameters.
int main (int argc, char **argv)
Variables
bool Global_Physical_Variables::Pin_fluid_on_fsi =false
For validation only.
double Global_Physical_Variables::Wo = 0.0
double Global_Physical_Variables::Inner_radius =0.5
Inner radius of tube.
double Global_Physical_Variables::Outer_radius =1.0
Outer radius of tube.
double Global_Physical_Variables::P_inlet_const =Length*4.0/(Inner_radius*Inner_radius)
Constant inlet pressure (for steady Poiseuille flow)
double Global_Physical_Variables::T_cos =0.0
double Global_Physical_Variables::P_outside_scale =0.0
double Global_Physical_Variables::P_wall =1.0
Constant wall pressure for validation.
double Global_Physical_Variables::Tau =2.0/Inner_radius
Shear stress (for steady Poiseuille flow)
double Global_Physical_Variables::Wavespeed =0.0
Storage for Moens Korteweg wavespeed – dependent parameter!
double Global_Physical_Variables::Pressure_wavespeed =0.0
Storage for pressure wavespeed in solid – dependent parameter!
Macro Definition Documentation
DO_FSI
#define DO_FSI
Function Documentation
main()
int main (int argc , char ** argv)
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Validation run?
  CommandLineArgs::specify_command_line_flag("--validation");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Create doc info object
  DocInfo doc_info;
  doc_info.set_directory("RESLT");
  // Create problem
  PressureWaveFSIProblem<AxisymmetricTTaylorHoodElement,
                         TAxisymmetricLinearElasticityElement<3> > problem;
  // Update dependent problem parameters
  Global_Physical_Variables::update_dependent_parameters();
  // Doc dependent parameters
   Global_Physical_Variables::doc_dependent_parameters();
  // Setup timestep based on Moens Korteweg velocity
  //------------------------------------------------
  // Desired number of timesteps for pressure wave to propagate
  // along tube
  unsigned nt=100;
  // Choose timestep
  double dt=Global_Physical_Variables::St*
   (Global_Physical_Variables::Length/double(nt))/
   Global_Physical_Variables::Wavespeed;
  oomph_info << "Timestep: " << dt << std::endl;
  // // Choose ramp-up over 30 timesteps
  // unsigned nramp=30;
  // Global_Physical_Variables::T_cos=double(nramp)*dt;
  //Set an impulsive start from rest
  problem.assign_initial_values_impulsive(dt);
  // Output initial condition
  problem.doc_solution(doc_info);
  // Do timestepping loop
  unsigned nstep=500;
  if (CommandLineArgs::command_line_flag_has_been_set("--validation"))
   {
    nstep=3;
   }
  for(unsigned n=0;n<nstep;n++)
   {
    //Solve the problem
    problem.unsteady_newton_solve(dt);
    // Output
    problem.doc_solution(doc_info);
    if (Global_Physical_Variables::Pin_fluid_on_fsi)
     {
      Global_Physical_Variables::P_inlet_const*=1.1;
      oomph_info << "incrementing P_inlet_const to "
                 <<  Global_Physical_Variables::P_inlet_const << std::endl;
     }
   }
 }
References oomph::CommandLineArgs::command_line_flag_has_been_set(), Global_Physical_Variables::doc_dependent_parameters(), oomph::CommandLineArgs::doc_specified_flags(), Global_Physical_Variables::Length, n, oomph::oomph_info, Global_Physical_Variables::P_inlet_const, oomph::CommandLineArgs::parse_and_assign(), Global_Physical_Variables::Pin_fluid_on_fsi, problem, oomph::DocInfo::set_directory(), Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), Global_Physical_Variables::St, Global_Physical_Variables::update_dependent_parameters(), and Global_Physical_Variables::Wavespeed.