MercuryDPM: Eigen::internal::CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, true > Class Template Reference
Eigen::internal::CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, true > Class Template Reference
#include <CwiseUnaryView.h>
Public Types
typedef CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, false > Base
typedef CwiseUnaryView< ViewOp, MatrixType, StrideType > Derived
Public Types inherited from Eigen::internal::CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, false >
typedef CwiseUnaryView< ViewOp, MatrixType, StrideType > Derived
typedef dense_xpr_base< CwiseUnaryView< ViewOp, MatrixType, StrideType > >::type Base
Public Member Functions
EIGEN_DEVICE_FUNC Scalar * data ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
Public Member Functions inherited from Eigen::internal::CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, false >
EIGEN_DEVICE_FUNC const Scalar * data () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index innerStride () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index outerStride () const
Additional Inherited Members
Protected Member Functions inherited from Eigen::internal::CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, false >
EIGEN_DEVICE_FUNC const Scalar & coeffRef (Index index) const
EIGEN_DEVICE_FUNC const Scalar & coeffRef (Index row, Index col) const
Member Typedef Documentation
Base
template<typename ViewOp , typename MatrixType , typename StrideType > typedef CwiseUnaryViewImpl<ViewOp, MatrixType, StrideType, Dense, false> Eigen::internal::CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, true >::Base
Derived
template<typename ViewOp , typename MatrixType , typename StrideType > typedef CwiseUnaryView<ViewOp, MatrixType, StrideType> Eigen::internal::CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, true >::Derived
Member Function Documentation
coeffRef() [1/2]
template<typename ViewOp , typename MatrixType , typename StrideType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, true >::coeffRef (Index index) inline
{
     return internal::evaluator<Derived>(derived()).coeffRef(index);
   }
coeffRef() [2/2]
template<typename ViewOp , typename MatrixType , typename StrideType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, true >::coeffRef (Index row, Index col) inline
{
     return internal::evaluator<Derived>(derived()).coeffRef(row, col);
   }
References col(), and row().
data()
template<typename ViewOp , typename MatrixType , typename StrideType > EIGEN_DEVICE_FUNC Scalar* Eigen::internal::CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, true >::data () inline
 { return &(this->coeffRef(0)); }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
The documentation for this class was generated from the following file:
CwiseUnaryView.h