MercuryDPM: Eigen::MatrixComplexPowerReturnValue< Derived > Class Template Reference
Eigen::MatrixComplexPowerReturnValue< Derived > Class Template Reference
Proxy for the matrix power of some matrix (expression).
#include <MatrixPower.h>
Public Types
typedef Derived::PlainObject PlainObject
typedef std::complex< typename Derived::RealScalar > ComplexScalar
Public Types inherited from Eigen::ReturnByValue< MatrixComplexPowerReturnValue< Derived > >
typedef internal::traits< MatrixComplexPowerReturnValue< Derived > >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Public Member Functions
MatrixComplexPowerReturnValue (const Derived &A, const ComplexScalar &p)
Constructor.
template<typename ResultType >
void evalTo (ResultType &result) const
Compute the matrix power.
Index rows () const
Index cols () const
Public Member Functions inherited from Eigen::ReturnByValue< MatrixComplexPowerReturnValue< Derived > >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Private Attributes
const Derived & m_A
const ComplexScalar m_p
Detailed Description
template<typename Derived>
class Eigen::MatrixComplexPowerReturnValue< Derived >
Proxy for the matrix power of some matrix (expression).
Template Parameters
Derived type of the base, a matrix (expression).
This class holds the arguments to the matrix power until it is assigned or evaluated for some other reason (so the argument should not be changed in the meantime). It is the return type of MatrixBase::pow() and related functions and most of the time this is the only way it is used.
Member Typedef Documentation
ComplexScalar
template<typename Derived > typedef std::complex<typename Derived::RealScalar> Eigen::MatrixComplexPowerReturnValue< Derived >::ComplexScalar
PlainObject
template<typename Derived > typedef Derived::PlainObject Eigen::MatrixComplexPowerReturnValue< Derived >::PlainObject
Constructor & Destructor Documentation
MatrixComplexPowerReturnValue()
template<typename Derived > Eigen::MatrixComplexPowerReturnValue< Derived >::MatrixComplexPowerReturnValue (const Derived & A, const ComplexScalar & p) inline
Constructor.
Parameters
[in] A Matrix (expression), the base of the matrix power.
[in] p complex scalar, the exponent of the matrix power.
 : m_A(A), m_p(p) {}
Member Function Documentation
cols()
template<typename Derived > Index Eigen::MatrixComplexPowerReturnValue< Derived >::cols () const inline
 { return m_A.cols(); }
References Eigen::MatrixComplexPowerReturnValue< Derived >::m_A.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
evalTo()
template<typename Derived > template<typename ResultType > void Eigen::MatrixComplexPowerReturnValue< Derived >::evalTo (ResultType & result) const inline
Compute the matrix power.
Because p is complex, \(A^p \) is simply evaluated as \(\exp(p \log(A)) \).
Parameters
[out] result \(A^p \) where A and p are as in the constructor.
{
     result = (m_p * m_A.log()).exp();
   }
References Eigen::bfloat16_impl::exp(), Eigen::MatrixComplexPowerReturnValue< Derived >::m_A, and Eigen::MatrixComplexPowerReturnValue< Derived >::m_p.
rows()
template<typename Derived > Index Eigen::MatrixComplexPowerReturnValue< Derived >::rows () const inline
 { return m_A.rows(); }
References Eigen::MatrixComplexPowerReturnValue< Derived >::m_A.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_A
template<typename Derived > const Derived& Eigen::MatrixComplexPowerReturnValue< Derived >::m_A private
Referenced by Eigen::MatrixComplexPowerReturnValue< Derived >::cols(), Eigen::MatrixComplexPowerReturnValue< Derived >::evalTo(), and Eigen::MatrixComplexPowerReturnValue< Derived >::rows().
m_p
template<typename Derived > const ComplexScalar Eigen::MatrixComplexPowerReturnValue< Derived >::m_p private
Referenced by Eigen::MatrixComplexPowerReturnValue< Derived >::evalTo().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
MatrixPower.h