MercuryDPM: FreeFallInteractionSelfTest.cpp File Reference
FreeFallInteractionSelfTest.cpp File Reference
#include "Mercury2D.h"
#include "Walls/InfiniteWall.h"
#include <iostream>
#include <Species/LinearViscoelasticSpecies.h>
Classes
class FreeFallInteractionSelfTest
This case does a single elastic particle falling on an infinite plane. The k is chosen so that the maximum overlap with the wall is around 2% of the partcles dimater; whereas, the time is taken to ensure 50 steps with a collision.
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
Start off my solving the default problem
 {
     logger(INFO, "Single particle bouncing vertically on the bottom plate");
     FreeFallInteractionSelfTest freeFallInteractionSelfTestProblem;
     auto species = new LinearViscoelasticSpecies;
     freeFallInteractionSelfTestProblem.speciesHandler.addObject(species);
     species->setDensity(2000.0);
     freeFallInteractionSelfTestProblem.setParticleDimensions(3);
     species->setStiffness(8000000.0);
     freeFallInteractionSelfTestProblem.setName("FreeFallInteractionSelfTest");
     freeFallInteractionSelfTestProblem.setSaveCount(500);
     freeFallInteractionSelfTestProblem.fStatFile.setFileType(FileType::NO_FILE);
     freeFallInteractionSelfTestProblem.getInteractionFile().setFileType(FileType::ONE_FILE);
     freeFallInteractionSelfTestProblem.setTimeStep(1e-6);
     freeFallInteractionSelfTestProblem.setYMax(0.1);
     freeFallInteractionSelfTestProblem.setXMax(0.01);
     freeFallInteractionSelfTestProblem.solve(argc, argv);
 }
References SpeciesHandler::addObject(), e(), DPMBase::fStatFile, DPMBase::getInteractionFile(), INFO, logger, NO_FILE, ONE_FILE, File::setFileType(), DPMBase::setName(), DPMBase::setParticleDimensions(), DPMBase::setSaveCount(), DPMBase::setTimeStep(), DPMBase::setXMax(), DPMBase::setYMax(), DPMBase::solve(), and DPMBase::speciesHandler.