MercuryDPM: SlidingFrictionSpecies Class Reference
SlidingFrictionSpecies Class Reference
SlidingFrictionSpecies contains the parameters used to describe sliding friction.
#include <SlidingFrictionSpecies.h>
Public Types
typedef SlidingFrictionInteraction InteractionType
The correct Interaction type for this FrictionForceSpecies.
Public Member Functions
SlidingFrictionSpecies ()
The default constructor.
SlidingFrictionSpecies (const SlidingFrictionSpecies &s)
The default copy constructor.
~SlidingFrictionSpecies ()
The default destructor.
void read (std::istream &is)
Reads the species properties from an input stream.
void write (std::ostream &os) const
Writes the species properties to an output stream.
virtual std::string getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
void setSlidingStiffness (Mdouble new_kt)
Allows the spring constant to be changed.
Mdouble getSlidingStiffness () const
Allows the spring constant to be accessed.
void setSlidingDissipation (Mdouble new_dispt)
Allows the tangential viscosity to be changed.
Mdouble getSlidingDissipation () const
Allows the tangential viscosity to be accessed.
void setSlidingFrictionCoefficient (Mdouble new_mu)
Allows the (dynamic) Coulomb friction coefficient to be changed; also sets mu_s by default.
Mdouble getSlidingFrictionCoefficient () const
Allows the (dynamic) Coulomb friction coefficient to be accessed.
void setSlidingFrictionCoefficientStatic (Mdouble new_mu)
Allows the static Coulomb friction coefficient to be changed.
Mdouble getSlidingFrictionCoefficientStatic () const
Allows the static Coulomb friction coefficient to be accessed.
bool getUseAngularDOFs () const override
Returns true if torques have to be calculated.
void mix (SlidingFrictionSpecies *S, SlidingFrictionSpecies *T)
creates default values for mixed species
void setCollisionTimeAndNormalAndTangentialRestitutionCoefficient (Mdouble tc, Mdouble eps, Mdouble beta, Mdouble mass)
Sets k, disp, kt, dispt such that it matches a given tc and eps for a collision of two particles of masses m0,m1.
void setCollisionTimeAndNormalAndTangentialRestitutionCoefficientNoDispt (Mdouble tc, Mdouble eps, Mdouble beta, Mdouble mass)
Sets k, disp, kt (with dispt=0) such that it matches a given tc and eps for a collision of two particles of mass m.
void setIsSuperquadricSpecies (bool isSuperquadricSpecies)
bool getIsSuperquadricSpecies () const
Public Member Functions inherited from BaseForce
BaseSpecies * getBaseSpecies () const
void setBaseSpecies (BaseSpecies *baseSpecies)
Private Attributes
Mdouble slidingStiffness_
tangential stiffness.
Mdouble slidingDissipation_
tangential dissipation coefficient.
Mdouble slidingFrictionCoefficient_
(dynamic) Coulomb friction coefficient
Mdouble slidingFrictionCoefficientStatic_
static Coulomb friction coefficient (by default set equal to mu)
bool isSuperquadricSpecies_
Detailed Description
SlidingFrictionSpecies contains the parameters used to describe sliding friction.
See SlidingFrictionInteraction::computeForce for a description of the force law.
Member Typedef Documentation
InteractionType
typedef SlidingFrictionInteraction SlidingFrictionSpecies::InteractionType
The correct Interaction type for this FrictionForceSpecies.
Constructor & Destructor Documentation
SlidingFrictionSpecies() [1/2]
SlidingFrictionSpecies::SlidingFrictionSpecies ()
The default constructor.
 {
     slidingStiffness_ = 0;
     slidingDissipation_ = 0;
     slidingFrictionCoefficient_ = 0;
     slidingFrictionCoefficientStatic_ = 0;
     isSuperquadricSpecies_ = false;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"SlidingFrictionSpecies::SlidingFrictionSpecies() finished"<<std::endl;
 #endif
 }
References isSuperquadricSpecies_, slidingDissipation_, slidingFrictionCoefficient_, slidingFrictionCoefficientStatic_, and slidingStiffness_.
SlidingFrictionSpecies() [2/2]
SlidingFrictionSpecies::SlidingFrictionSpecies (const SlidingFrictionSpecies & s)
The default copy constructor.
Parameters
[in] s the species that is copied
 {
     slidingStiffness_ = s.slidingStiffness_;
     slidingDissipation_ = s.slidingDissipation_;
     slidingFrictionCoefficient_ = s.slidingFrictionCoefficient_;
     slidingFrictionCoefficientStatic_ = s.slidingFrictionCoefficientStatic_;
     isSuperquadricSpecies_ = s.isSuperquadricSpecies_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"SlidingFrictionSpecies::SlidingFrictionSpecies(const SlidingFrictionSpecies &p) finished"<<std::endl;
 #endif
 }
References isSuperquadricSpecies_, s, slidingDissipation_, slidingFrictionCoefficient_, slidingFrictionCoefficientStatic_, and slidingStiffness_.
~SlidingFrictionSpecies()
SlidingFrictionSpecies::~SlidingFrictionSpecies ()
The default destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"SlidingFrictionSpecies::~SlidingFrictionSpecies() finished"<<std::endl;
 #endif
 }
Member Function Documentation
getBaseName()
std::string SlidingFrictionSpecies::getBaseName () const virtual
Used in Species::getName to obtain a unique name for each Species.
Returns
a string containing the name of the species (minus the word "Species")
Reimplemented in FrictionSpecies.
 {
     return "SlidingFriction";
 }
getIsSuperquadricSpecies()
bool SlidingFrictionSpecies::getIsSuperquadricSpecies () const
 {
     return isSuperquadricSpecies_;
 }
References isSuperquadricSpecies_.
Referenced by SlidingFrictionInteraction::computeFrictionForce().
getSlidingDissipation()
Mdouble SlidingFrictionSpecies::getSlidingDissipation () const
Allows the tangential viscosity to be accessed.
 {
     return slidingDissipation_;
 }
References slidingDissipation_.
Referenced by SlidingFrictionInteraction::computeFrictionForce(), and Slide::create_rough_wall().
getSlidingFrictionCoefficient()
Mdouble SlidingFrictionSpecies::getSlidingFrictionCoefficient () const
Allows the (dynamic) Coulomb friction coefficient to be accessed.
 {
     return slidingFrictionCoefficient_;
 }
References slidingFrictionCoefficient_.
Referenced by Slide::actionsBeforeTimeStep(), SlidingFrictionInteraction::computeFrictionForce(), and RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise().
getSlidingFrictionCoefficientStatic()
Mdouble SlidingFrictionSpecies::getSlidingFrictionCoefficientStatic () const
Allows the static Coulomb friction coefficient to be accessed.
 {
     return slidingFrictionCoefficientStatic_;
 }
References slidingFrictionCoefficientStatic_.
Referenced by SlidingFrictionInteraction::computeFrictionForce().
getSlidingStiffness()
Mdouble SlidingFrictionSpecies::getSlidingStiffness () const
Allows the spring constant to be accessed.
 {
     return slidingStiffness_;
 }
References slidingStiffness_.
Referenced by SlidingFrictionInteraction::computeFrictionForce(), Slide::create_rough_wall(), SlidingFrictionInteraction::getElasticEnergy(), and setCollisionTimeAndNormalAndTangentialRestitutionCoefficient().
getUseAngularDOFs()
bool SlidingFrictionSpecies::getUseAngularDOFs () const override virtual
Returns true if torques have to be calculated.
Returns true for any FrictionForceSpecies except EmptyFrictionSpecies, because for spherical particles, torques are only caused by tangential forces. See SpeciesHandler::useAngularDOFs for more details
Returns
true
Implements BaseFrictionForce.
Reimplemented in Species< LinearViscoelasticNormalSpecies, FrictionSpecies >, Species< LinearPlasticViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, and Species< LinearViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >.
 {
     return true;
 }
mix()
void SlidingFrictionSpecies::mix (SlidingFrictionSpecies * S, SlidingFrictionSpecies * T)
creates default values for mixed species
For all parameters we assume that the harmonic mean of the parameters of the original two species is a sensible default.
Parameters
[in] SFrictional the first species whose properties are mixed to create the new species
[in] TFrictional the second species whose properties are mixed to create the new species
 {
     slidingStiffness_ = BaseSpecies::average(S->getSlidingStiffness(), T->getSlidingStiffness());
     slidingDissipation_ = BaseSpecies::average(S->getSlidingDissipation(), T->getSlidingDissipation());
     slidingFrictionCoefficient_ = BaseSpecies::average(S->getSlidingFrictionCoefficient(),
                                           T->getSlidingFrictionCoefficient());
     slidingFrictionCoefficientStatic_ = BaseSpecies::average(S->getSlidingFrictionCoefficientStatic(),
                                                 T->getSlidingFrictionCoefficientStatic());
 }
References BaseSpecies::average(), oomph::QuadTreeNames::S, slidingDissipation_, slidingFrictionCoefficient_, slidingFrictionCoefficientStatic_, and slidingStiffness_.
Referenced by FrictionSpecies::mix().
read()
void SlidingFrictionSpecies::read (std::istream & is)
Reads the species properties from an input stream.
Parameters
[in] is input stream (typically the restart file)
 {
     //BaseSpecies::read(is);
     std::string dummy;
     is >> dummy >> slidingStiffness_;
     is >> dummy >> slidingDissipation_;
     is >> dummy >> slidingFrictionCoefficient_;
     is >> dummy >> slidingFrictionCoefficientStatic_;
 }
References slidingDissipation_, slidingFrictionCoefficient_, slidingFrictionCoefficientStatic_, slidingStiffness_, and oomph::Global_string_for_annotation::string().
Referenced by FrictionSpecies::read().
setCollisionTimeAndNormalAndTangentialRestitutionCoefficient()
void SlidingFrictionSpecies::setCollisionTimeAndNormalAndTangentialRestitutionCoefficient (Mdouble tc, Mdouble eps, Mdouble beta, Mdouble mass)
Sets k, disp, kt, dispt such that it matches a given tc and eps for a collision of two particles of masses m0,m1.
 {
     Mdouble stiffness;
     //the dynamic cast is needed to check if the normal force species is LinearViscoelasticSpecies; otherwise this function cannot be used
     LinearViscoelasticNormalSpecies* species = dynamic_cast<LinearViscoelasticNormalSpecies*>(this);
     if (species != nullptr)
     {
         species->setCollisionTimeAndRestitutionCoefficient(tc, eps, mass);
         stiffness = species->getStiffness();
     }
     else
     {
         LinearPlasticViscoelasticNormalSpecies* species2 = dynamic_cast<LinearPlasticViscoelasticNormalSpecies*>(this);
         if (species2 != nullptr)
         {
             species2->setDissipation(-mass / tc * std::log(eps));
             species2->setLoadingStiffness(.5 * mass * (mathsFunc::square(constants::pi / tc) +
                                                        mathsFunc::square(species2->getDissipation()) / mass));
             stiffness = species2->getLoadingStiffness();
         }
         else
         {
             logger(ERROR,
                    "SlidingFrictionSpecies::setCollisionTimeAndNormalAndTangentialRestitutionCoefficient only works for "
                    "LinearViscoelasticSlidingFrictionSpecies or LinearPlasticViscoelasticSlidingFrictionSpecies");
         }
     }
     // from: N. G. Deen et. al. https://doi.org/10.1016/j.ces.2006.08.014
     // eq. 43 and 30
     setSlidingStiffness(2.0 / 7.0 * stiffness * (mathsFunc::square(constants::pi) + mathsFunc::square(log(beta))) /
                         (mathsFunc::square(constants::pi) + mathsFunc::square(log(eps))));
     if (beta != 0.0)
         setSlidingDissipation(-2 * log(beta) * sqrt(1.0 / 7.0 * mass * getSlidingStiffness() /
                                                     (mathsFunc::square(constants::pi) + mathsFunc::square(log(beta)))));
     else
         setSlidingDissipation(2. * sqrt(1.0 / 7.0 * mass * getSlidingStiffness()));
 }
References beta, CRBond_Bessel::eps, ERROR, LinearPlasticViscoelasticNormalSpecies::getDissipation(), LinearPlasticViscoelasticNormalSpecies::getLoadingStiffness(), getSlidingStiffness(), LinearViscoelasticNormalSpecies::getStiffness(), Eigen::bfloat16_impl::log(), logger, constants::pi, LinearViscoelasticNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), LinearPlasticViscoelasticNormalSpecies::setDissipation(), LinearPlasticViscoelasticNormalSpecies::setLoadingStiffness(), setSlidingDissipation(), setSlidingStiffness(), sqrt(), and mathsFunc::square().
Referenced by Siegen::Siegen().
setCollisionTimeAndNormalAndTangentialRestitutionCoefficientNoDispt()
void SlidingFrictionSpecies::setCollisionTimeAndNormalAndTangentialRestitutionCoefficientNoDispt (Mdouble tc, Mdouble eps, Mdouble beta, Mdouble mass)
Sets k, disp, kt (with dispt=0) such that it matches a given tc and eps for a collision of two particles of mass m.
Sets k, disp, kt, dispt such that it matches a given tc and eps for a collision of two particles of masses m0,m1.
 {
     //the dynamic cast is needed to check if the normal force species is LinearViscoelasticSpecies; otherwise this function cannot be used
     LinearViscoelasticNormalSpecies* species = dynamic_cast<LinearViscoelasticNormalSpecies*>(this);
     if (species == nullptr)
     {
         logger(ERROR, "SlidingFrictionSpecies::setCollisionTimeAndNormalAndTangentialRestitutionCoefficient only "
                       "works for LinearViscoelasticSlidingFrictionSpecies");
     }
     species->setCollisionTimeAndRestitutionCoefficient(tc, eps, mass);
     // from: V. Becker et. al. https://doi.org/10.1103/PhysRevE.77.011304
     // eq. 56
     setSlidingStiffness(2.0 / 7.0 * species->getStiffness() * mathsFunc::square(acos(-beta) / constants::pi));
     setSlidingDissipation(0);
 }
References acos(), beta, CRBond_Bessel::eps, ERROR, LinearViscoelasticNormalSpecies::getStiffness(), logger, constants::pi, LinearViscoelasticNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), setSlidingDissipation(), setSlidingStiffness(), and mathsFunc::square().
setIsSuperquadricSpecies()
void SlidingFrictionSpecies::setIsSuperquadricSpecies (bool isSuperquadricSpecies)
 {
     SlidingFrictionSpecies::isSuperquadricSpecies_ = isSuperquadricSpecies;
 }
References isSuperquadricSpecies_.
setSlidingDissipation()
void SlidingFrictionSpecies::setSlidingDissipation (Mdouble new_dispt)
Allows the tangential viscosity to be changed.
 {
     if (new_dispt >= 0)
         slidingDissipation_ = new_dispt;
     else
     {
         logger(ERROR, "Error in setSlidingDissipation");
     }
 }
References ERROR, logger, and slidingDissipation_.
Referenced by BoundariesSelfTest::BoundariesSelfTest(), ChutePeriodicDemo::ChutePeriodicDemo(), ChuteWithWedge::ChuteWithWedge(), Slide::create_rough_wall(), ParameterStudy1DDemo::createSpecies(), ParameterStudy2DDemo::createSpecies(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), main(), MinimalExampleDrum::MinimalExampleDrum(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), setCollisionTimeAndNormalAndTangentialRestitutionCoefficient(), setCollisionTimeAndNormalAndTangentialRestitutionCoefficientNoDispt(), GranularJet::setSilbert(), ChutePeriodic::setup(), Drum::setupInitialConditions(), MarbleRun::setupInitialConditions(), and Siegen::Siegen().
setSlidingFrictionCoefficient()
void SlidingFrictionSpecies::setSlidingFrictionCoefficient (Mdouble new_mu)
Allows the (dynamic) Coulomb friction coefficient to be changed; also sets mu_s by default.
 {
     if (new_mu >= 0)
     {
         slidingFrictionCoefficient_ = new_mu;
         slidingFrictionCoefficientStatic_ = slidingFrictionCoefficient_;
     }
     else
     {
         logger(ERROR, "Error in setSlidingFrictionCoefficient");
     }
 }
References ERROR, logger, slidingFrictionCoefficient_, and slidingFrictionCoefficientStatic_.
Referenced by Slide::actionsBeforeTimeStep(), BoundariesSelfTest::BoundariesSelfTest(), ChutePeriodicDemo::ChutePeriodicDemo(), ChuteWithWedge::ChuteWithWedge(), ParameterStudy1DDemo::createSpecies(), ParameterStudy2DDemo::createSpecies(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), main(), ChuteBottom::makeRoughBottom(), MinimalExampleDrum::MinimalExampleDrum(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), GranularJet::setSilbert(), MarbleRun::setSlidingFrictionCoefficient(), ChutePeriodic::setup(), Drum::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), and Siegen::Siegen().
setSlidingFrictionCoefficientStatic()
void SlidingFrictionSpecies::setSlidingFrictionCoefficientStatic (Mdouble new_mu)
Allows the static Coulomb friction coefficient to be changed.
Allows the static Coulomb friction coefficient to be changed; also sets mu_s by default.
 {
     if (new_mu >= 0)
     {
         slidingFrictionCoefficientStatic_ = new_mu;
     }
     else
     {
         logger(ERROR, "Error in setSlidingFrictionCoefficientStatic");
     }
 }
References ERROR, logger, and slidingFrictionCoefficientStatic_.
setSlidingStiffness()
void SlidingFrictionSpecies::setSlidingStiffness (Mdouble new_kt)
Allows the spring constant to be changed.
 {
     if (new_kt >= 0)
     {
         slidingStiffness_ = new_kt;
     }
     else
     {
         logger(ERROR, "Error in setSlidingStiffness");
     }
 }
References ERROR, logger, and slidingStiffness_.
Referenced by BoundariesSelfTest::BoundariesSelfTest(), ChutePeriodicDemo::ChutePeriodicDemo(), ChuteWithWedge::ChuteWithWedge(), Slide::create_rough_wall(), ParameterStudy1DDemo::createSpecies(), ParameterStudy2DDemo::createSpecies(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), main(), MinimalExampleDrum::MinimalExampleDrum(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), setCollisionTimeAndNormalAndTangentialRestitutionCoefficient(), setCollisionTimeAndNormalAndTangentialRestitutionCoefficientNoDispt(), GranularJet::setSilbert(), ChutePeriodic::setup(), Drum::setupInitialConditions(), MarbleRun::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), and PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions().
write()
void SlidingFrictionSpecies::write (std::ostream & os) const
Writes the species properties to an output stream.
Parameters
[out] os output stream (typically the restart file)
 {
     //BaseSpecies::write(os);
     os << " slidingStiffness " << slidingStiffness_;
     os << " slidingDissipation " << slidingDissipation_;
     os << " slidingFrictionCoefficient " << slidingFrictionCoefficient_;
     os << " slidingFrictionCoefficientStatic " << slidingFrictionCoefficientStatic_;
 }
References slidingDissipation_, slidingFrictionCoefficient_, slidingFrictionCoefficientStatic_, and slidingStiffness_.
Referenced by FrictionSpecies::write().
Member Data Documentation
isSuperquadricSpecies_
bool SlidingFrictionSpecies::isSuperquadricSpecies_ private
Referenced by getIsSuperquadricSpecies(), setIsSuperquadricSpecies(), and SlidingFrictionSpecies().
slidingDissipation_
Mdouble SlidingFrictionSpecies::slidingDissipation_ private
tangential dissipation coefficient.
Typically set to 2/7 of the normal force dissipation, as both the tangential and the normal spring have the same restitution coefficients (if the tangential and normal stiffnesses also have a ratio of 2/7). should always satisfy \(4*dispt*dt<mass, dispt \approx disp\), otherwise the restitution is zero and the particles stick.
Referenced by getSlidingDissipation(), mix(), read(), setSlidingDissipation(), SlidingFrictionSpecies(), and write().
slidingFrictionCoefficient_
Mdouble SlidingFrictionSpecies::slidingFrictionCoefficient_ private
(dynamic) Coulomb friction coefficient
Referenced by getSlidingFrictionCoefficient(), mix(), read(), setSlidingFrictionCoefficient(), SlidingFrictionSpecies(), and write().
slidingFrictionCoefficientStatic_
Mdouble SlidingFrictionSpecies::slidingFrictionCoefficientStatic_ private
static Coulomb friction coefficient (by default set equal to mu)
Referenced by getSlidingFrictionCoefficientStatic(), mix(), read(), setSlidingFrictionCoefficient(), setSlidingFrictionCoefficientStatic(), SlidingFrictionSpecies(), and write().
slidingStiffness_
Mdouble SlidingFrictionSpecies::slidingStiffness_ private
tangential stiffness.
Typically set to 2/7 of the stiffness of the normal force, as
both the tangential and the normal spring have the same oscillation
frequency (and thus require the same timeStep)in this case.
Referenced by getSlidingStiffness(), mix(), read(), setSlidingStiffness(), SlidingFrictionSpecies(), and write().
The documentation for this class was generated from the following files:
SlidingFrictionSpecies.h
SlidingFrictionSpecies.cc