MercuryDPM: elastic_gas_with_gravity.cpp File Reference
elastic_gas_with_gravity.cpp File Reference
#include <iostream>
#include <Species/LinearViscoelasticFrictionSpecies.h>
#include "DPMBase.h"
#include "Mercury2D.h"
#include "StatisticsVector.h"
Classes
class my_problem
todo{This code is not working as is wanted}
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
Start off my solving the default problem
 {
     my_problem problem;
     problem.setName("free_cooling");
     //Stefan problem
     //problem.set_dissipation(0.0);
 //  species->setStiffness(1e5);
 //  problem.setTimeStep(4e-5);
 //  problem.setSaveCount(250000);
 //  problem.setTimeMax(10);
     //Vits problem
     auto species = problem.speciesHandler.copyAndAddObject(LinearViscoelasticFrictionSpecies());
     species->setDissipation(0.0);
     species->setStiffness(1e6);
     species->setDensity(2000);
     problem.setTimeStep(4e-5);
     problem.setTimeMax(12e-5);
     //problem.set_HGRID_max_levels(1);
     //problem.set_HGRID_num_buckets(1e5);
     problem.setGravity(Vec3D(0.0,0.0,1.0));
     problem.setSaveCount(1e5);
     problem.write(std::cout,false);
     problem.solve();
     problem.write(std::cout,false);
     problem.writeRestartFile();
     //StatisticsVector problemstats(problem.getName(), 100, 100, 0, 0.05, Gaussian);
     StatisticsVector<XY> problemstats;
     problemstats.setName(problem.getName());
     problemstats.setNX(100);
         problemstats.setNY(100);
         problemstats.setNZ(0);
         problemstats.setCGWidth(0.05);
         problemstats.setCGShape(Gaussian);
     problemstats.statistics_from_fstat_and_data();
 /*  cout << endl << "v=" << problem2.getMaximumVelocity_of_smallest_particle() << endl;
     cout << "tc=" << problem2.getCollisionTime_for_smallest_particle() << endl;
     cout << "eps=" << problem2.getRestitutionCoefficient_for_smallest_particle() << endl;*/
 }
References e(), Gaussian, problem, StatisticsVector< T >::setCGShape(), StatisticsVector< T >::setCGWidth(), DPMBase::setName(), StatisticsVector< T >::setNX(), StatisticsVector< T >::setNY(), StatisticsVector< T >::setNZ(), and StatisticsVector< T >::statistics_from_fstat_and_data().