MercuryDPM: oomph::RefineableQPVDElementWithContinuousPressure< DIM > Class Template Reference
oomph::RefineableQPVDElementWithContinuousPressure< DIM > Class Template Reference
#include <refineable_solid_elements.h>
Public Member Functions
RefineableQPVDElementWithContinuousPressure ()
Constructor:
unsigned required_nvalue (const unsigned &n) const
unsigned ncont_interpolated_values () const
Number of continuously interpolated values (1) solid pressure.
void rebuild_from_sons (Mesh *&mesh_pt)
Empty rebuild from sons, empty.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
OK, interpolate the solid pressures.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
OK get the time-dependent verion.
void unpin_elemental_solid_pressure_dofs ()
Unpin all pressure dofs.
void pin_elemental_redundant_nodal_solid_pressures ()
Pin the redundant solid pressure.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned nrecovery_order ()
Node * interpolating_node_pt (const unsigned &n, const int &value_id)
double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
unsigned ninterpolating_node_1d (const int &value_id)
unsigned ninterpolating_node (const int &value_id)
void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
void further_setup_hanging_nodes ()
Node * solid_pressure_node_pt (const unsigned &l)
Public Member Functions inherited from oomph::QPVDElementWithContinuousPressure< DIM >
QPVDElementWithContinuousPressure ()
Constructor.
int solid_p_nodal_index () const
Set the value at which the solid pressure is stored in the nodes.
double solid_p (const unsigned &l)
void set_solid_p (const unsigned &l, const double &p_value)
Set the l-th solid pressure value to p_value.
unsigned npres_solid () const
Return number of pressure values.
void fix_solid_pressure (const unsigned &l, const double &pvalue)
Fix the pressure dof l to be the value pvalue.
void output (std::ostream &outfile)
Generic FiniteElement output function.
void output (std::ostream &outfile, const unsigned &n_plot)
PVDEquationsWithPressure output function.
void output (FILE *file_pt)
C-style generic FiniteElement output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style PVDEquationsWithPressure output function.
Public Member Functions inherited from oomph::PVDEquationsWithPressure< DIM >
PVDEquationsWithPressure ()
Constructor, by default the element is NOT incompressible.
void get_stress (const Vector< double > &s, DenseMatrix< double > &sigma)
bool is_incompressible () const
Return whether the material is incompressible.
void set_incompressible ()
Set the material to be incompressible.
void set_compressible ()
Set the material to be compressible.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
double interpolated_solid_p (const Vector< double > &s)
Return the interpolated_solid_pressure.
void extended_output (std::ostream &outfile, const unsigned &n_plot)
Output: x,y,[z],xi0,xi1,[xi2],gamma strain and stress components.
void get_mass_matrix_diagonal (Vector< double > &mass_diag)
unsigned ndof_types () const
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::PVDEquationsBase< DIM >
PVDEquationsBase ()
ConstitutiveLaw *& constitutive_law_pt ()
Return the constitutive law pointer.
const double & lambda_sq () const
Access function for timescale ratio (nondim density)
double *& lambda_sq_pt ()
Access function for pointer to timescale ratio (nondim density)
IsotropicGrowthFctPt & isotropic_growth_fct_pt ()
Access function: Pointer to isotropic growth function.
PrestressFctPt & prestress_fct_pt ()
Access function: Pointer to pre-stress function.
IsotropicGrowthFctPt isotropic_growth_fct_pt () const
Access function: Pointer to isotropic growth function (const version)
BodyForceFctPt & body_force_fct_pt ()
Access function: Pointer to body force function.
BodyForceFctPt body_force_fct_pt () const
Access function: Pointer to body force function (const version)
void enable_inertia ()
Switch on solid inertia.
void disable_inertia ()
Switch off solid inertia.
bool is_inertia_enabled () const
Access function to flag that switches inertia on/off (const version)
void get_strain (const Vector< double > &s, DenseMatrix< double > &strain) const
Return the strain tensor.
void get_energy (double &pot_en, double &kin_en)
Get potential (strain) and kinetic energy.
void get_deformed_covariant_basis_vectors (const Vector< double > &s, DenseMatrix< double > &def_covariant_basis)
void get_principal_stress (const Vector< double > &s, DenseMatrix< double > &principal_stress_vector, Vector< double > &principal_stress)
virtual void get_isotropic_growth (const unsigned &ipt, const Vector< double > &s, const Vector< double > &xi, double &gamma) const
void body_force (const Vector< double > &xi, Vector< double > &b) const
void enable_evaluate_jacobian_by_fd ()
Set Jacobian to be evaluated by FD? Else: Analytically.
void disable_evaluate_jacobian_by_fd ()
Set Jacobian to be evaluated analytically Else: by FD.
bool is_jacobian_evaluated_by_fd () const
Return the flag indicating whether the jacobian is evaluated by fd.
double prestress (const unsigned &i, const unsigned &j, const Vector< double > xi)
Public Member Functions inherited from oomph::SolidFiniteElement
void set_lagrangian_dimension (const unsigned &lagrangian_dimension)
virtual bool has_internal_solid_data ()
SolidFiniteElement ()
Constructor: Set defaults.
virtual ~SolidFiniteElement ()
Destructor to clean up any allocated memory.
SolidFiniteElement (const SolidFiniteElement &)=delete
Broken copy constructor.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_x_and_xi (const Vector< double > &s, Vector< double > &x_fe, Vector< double > &x, Vector< double > &xi_fe, Vector< double > &xi) const
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt, MacroElement *undeformed_macro_elem_pt)
void set_undeformed_macro_elem_pt (MacroElement *undeformed_macro_elem_pt)
MacroElement * undeformed_macro_elem_pt ()
Access function to pointer to "undeformed" macro element.
double dshape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi) const
virtual double dshape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi) const
double d2shape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
virtual double d2shape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
unsigned lagrangian_dimension () const
unsigned nnodal_lagrangian_type () const
Node * construct_node (const unsigned &n)
Construct the local node n and return a pointer to it.
Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Node * construct_boundary_node (const unsigned &n)
Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
double raw_lagrangian_position (const unsigned &n, const unsigned &i) const
double raw_lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double lagrangian_position (const unsigned &n, const unsigned &i) const
Return i-th Lagrangian coordinate at local node n.
double lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
virtual double interpolated_xi (const Vector< double > &s, const unsigned &i) const
virtual void interpolated_xi (const Vector< double > &s, Vector< double > &xi) const
virtual void interpolated_dxids (const Vector< double > &s, DenseMatrix< double > &dxids) const
virtual void J_lagrangian (const Vector< double > &s) const
virtual double J_lagrangian_at_knot (const unsigned &ipt) const
SolidInitialCondition *& solid_ic_pt ()
Pointer to object that describes the initial condition.
void enable_solve_for_consistent_newmark_accel ()
void disable_solve_for_consistent_newmark_accel ()
Set to reset the problem being solved to be the standard problem.
MultiplierFctPt & multiplier_fct_pt ()
MultiplierFctPt multiplier_fct_pt () const
virtual void get_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_for_newmark_accel (DenseMatrix< double > &jacobian)
void compute_norm (double &el_norm)
int position_local_eqn (const unsigned &n, const unsigned &k, const unsigned &j) const
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void disable_ALE ()
virtual void enable_ALE ()
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::SolidElementWithDiagonalMassMatrix
SolidElementWithDiagonalMassMatrix ()
Empty constructor.
virtual ~SolidElementWithDiagonalMassMatrix ()
Virtual destructor.
SolidElementWithDiagonalMassMatrix (const SolidElementWithDiagonalMassMatrix &)=delete
Broken copy constructor.
void operator= (const SolidElementWithDiagonalMassMatrix &)=delete
Broken assignment operator.
Public Member Functions inherited from oomph::RefineablePVDEquationsWithPressure< DIM >
RefineablePVDEquationsWithPressure ()
Constructor:
void fill_in_generic_residual_contribution_pvd_with_pressure (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, const unsigned &flag)
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
in strain tensor.
void further_build ()
Pass the generic stuff down to the sons.
void get_mass_matrix_diagonal (Vector< double > &mass_diag)
Public Member Functions inherited from oomph::RefineableSolidElement
RefineableSolidElement ()
Constructor.
virtual ~RefineableSolidElement ()
Virtual Destructor, delete any allocated storage.
void assign_solid_local_eqn_numbers (const bool &store_local_dof_pt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void identify_geometric_data (std::set< Data * > &geometric_data_pt)
void fill_in_jacobian_from_solid_position_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
bool is_undeformed_macro_element_used_for_new_lagrangian_coords () const
void enable_use_of_undeformed_macro_element_for_new_lagrangian_coords ()
void disable_use_of_undeformed_macro_element_for_new_lagrangian_coords ()
DenseMatrix< int > & local_position_hang_eqn (Node *const &node_pt)
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
virtual unsigned required_nsons () const
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)=0
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void unbuild ()
virtual void deactivate_element ()
virtual bool nodes_built ()
Return true if all the nodes have been built, false if not.
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual void check_integrity (double &max_error)=0
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual RefineableElement * root_element_pt ()
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
virtual void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
virtual void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
Pre-build the element.
virtual void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
unsigned nshape_controlling_nodes ()
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Public Member Functions inherited from oomph::ElementWithZ2ErrorEstimator
ElementWithZ2ErrorEstimator ()
Default empty constructor.
ElementWithZ2ErrorEstimator (const ElementWithZ2ErrorEstimator &)=delete
Broken copy constructor.
void operator= (const ElementWithZ2ErrorEstimator &)=delete
Broken assignment operator.
virtual unsigned ncompound_fluxes ()
virtual void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
virtual void get_Z2_compound_flux_indices (Vector< unsigned > &flux_index)
virtual double geometric_jacobian (const Vector< double > &x)
Public Member Functions inherited from oomph::RefineableSolidQElement< DIM >
RefineableSolidQElement ()
Empty constuctor.
Additional Inherited Members
Public Types inherited from oomph::PVDEquationsBase< DIM >
typedef void(* IsotropicGrowthFctPt) (const Vector< double > &xi, double &gamma)
typedef double(* PrestressFctPt) (const unsigned &i, const unsigned &j, const Vector< double > &xi)
typedef void(* BodyForceFctPt) (const double &t, const Vector< double > &xi, Vector< double > &b)
Public Types inherited from oomph::SolidFiniteElement
typedef double(* MultiplierFctPt) (const Vector< double > &xi)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Member Functions inherited from oomph::PVDEquationsBase< DIM >
static void pin_redundant_nodal_solid_pressures (const Vector< GeneralisedElement * > &element_pt)
static void unpin_all_solid_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in vector.
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions inherited from oomph::QPVDElementWithContinuousPressure< DIM >
int solid_p_local_eqn (const unsigned &i) const
void solid_pshape (const Vector< double > &s, Shape &psi) const
Return the pressure shape functions.
const unsigned Pconv [4]
Conversion from pressure dof to Node number at which pressure is stored.
const unsigned Pconv [8]
Conversion from pressure dof to Node number at which pressure is stored.
void solid_pshape (const Vector< double > &s, Shape &psi) const
void solid_pshape (const Vector< double > &s, Shape &psi) const
Protected Member Functions inherited from oomph::PVDEquationsWithPressure< DIM >
void get_stress (const DenseMatrix< double > &g, const DenseMatrix< double > &G, DenseMatrix< double > &sigma_dev, DenseMatrix< double > &Gcontra, double &gen_dil, double &inv_kappa)
void get_d_stress_dG_upper (const DenseMatrix< double > &g, const DenseMatrix< double > &G, const DenseMatrix< double > &sigma, const double &gen_dil, const double &inv_kappa, const double &interpolated_solid_p, RankFourTensor< double > &d_sigma_dG, DenseMatrix< double > &d_gen_dil_dG)
void solid_pshape_at_knot (const unsigned &ipt, Shape &psi) const
Return the stored solid shape functions at the knots.
void get_stress (const DenseMatrix< double > &g, const DenseMatrix< double > &G, DenseMatrix< double > &sigma_dev, DenseMatrix< double > &Gcontra, double &detG)
void get_d_stress_dG_upper (const DenseMatrix< double > &g, const DenseMatrix< double > &G, const DenseMatrix< double > &sigma, const double &detG, const double &interpolated_solid_p, RankFourTensor< double > &d_sigma_dG, DenseMatrix< double > &d_detG_dG)
Protected Member Functions inherited from oomph::SolidFiniteElement
void fill_in_generic_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
void set_nnodal_lagrangian_type (const unsigned &nlagrangian_type)
virtual double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
void describe_solid_local_dofs (std::ostream &out, const std::string &current_string) const
Classifies dofs locally for solid specific aspects.
void fill_in_jacobian_from_solid_position_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_solid_position_fd ()
virtual void reset_after_solid_position_fd ()
virtual void update_in_solid_position_fd (const unsigned &i)
virtual void reset_in_solid_position_fd (const unsigned &i)
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::RefineableSolidElement
void assemble_local_to_lagrangian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_lagrangian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
double local_to_lagrangian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Protected Attributes inherited from oomph::PVDEquationsWithPressure< DIM >
bool Incompressible
Boolean to determine whether the solid is incompressible or not.
Protected Attributes inherited from oomph::PVDEquationsBase< DIM >
IsotropicGrowthFctPt Isotropic_growth_fct_pt
Pointer to isotropic growth function.
PrestressFctPt Prestress_fct_pt
Pointer to prestress function.
ConstitutiveLaw * Constitutive_law_pt
Pointer to the constitutive law.
double * Lambda_sq_pt
Timescale ratio (non-dim. density)
bool Unsteady
Flag that switches inertia on/off.
BodyForceFctPt Body_force_fct_pt
Pointer to body force function.
bool Evaluate_jacobian_by_fd
Use FD to evaluate Jacobian.
Protected Attributes inherited from oomph::SolidFiniteElement
MacroElement * Undeformed_macro_elem_pt
Pointer to the element's "undeformed" macro element (NULL by default)
SolidInitialCondition * Solid_ic_pt
Pointer to object that specifies the initial condition.
bool Solve_for_consistent_newmark_accel_flag
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::RefineableSolidElement
bool Use_undeformed_macro_element_for_new_lagrangian_coords
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number – for plotting/validation purposes.
Static Protected Attributes inherited from oomph::QPVDElementWithContinuousPressure< DIM >
static const unsigned Pconv []
Static Protected Attributes inherited from oomph::PVDEquationsBase< DIM >
static double Default_lambda_sq_value = 1.0
Static default value for timescale ratio (1.0 – for natural scaling)
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Detailed Description
template<unsigned DIM>
class oomph::RefineableQPVDElementWithContinuousPressure< DIM >
Class for refineable solid mechanics elements in near-incompressible/ incompressible formulation, so a pressure is included! These elements include a continuously interpolated pressure a la Taylor Hood/
Constructor & Destructor Documentation
RefineableQPVDElementWithContinuousPressure()
template<unsigned DIM> oomph::RefineableQPVDElementWithContinuousPressure< DIM >::RefineableQPVDElementWithContinuousPressure () inline
Constructor:
       : QPVDElementWithContinuousPressure<DIM>(),
         RefineableElement(),
         RefineableSolidElement(),
         RefineablePVDEquationsWithPressure<DIM>(),
         RefineableSolidQElement<DIM>()
     {
     }
Member Function Documentation
further_setup_hanging_nodes()
template<unsigned DIM> void oomph::RefineableQPVDElementWithContinuousPressure< DIM >::further_setup_hanging_nodes () inline virtual
Perform additional hanging node procedures for variables that are not interpolated by all nodes.
Reimplemented from oomph::RefineableElement.
     {
       this->setup_hang_for_value(this->solid_p_nodal_index());
     }
References oomph::QPVDElementWithContinuousPressure< DIM >::solid_p_nodal_index().
get_interpolated_values() [1/2]
template<unsigned DIM> void oomph::RefineableQPVDElementWithContinuousPressure< DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) inline virtual
OK get the time-dependent verion.
Reimplemented from oomph::RefineablePVDEquationsWithPressure< DIM >.
     {
       // There is only one solid pressure, initialise to zero
       values.resize(1);
       // The solid pressure does not depend on time!
       values[0] = this->interpolated_solid_p(s);
     }
References oomph::PVDEquationsWithPressure< DIM >::interpolated_solid_p().
get_interpolated_values() [2/2]
template<unsigned DIM> void oomph::RefineableQPVDElementWithContinuousPressure< DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) inline virtual
OK, interpolate the solid pressures.
Reimplemented from oomph::RefineablePVDEquationsWithPressure< DIM >.
     {
       // There is only one solid pressure, initialise to zero
       values.resize(1);
       // Get the interpolated value
       values[0] = this->interpolated_solid_p(s);
     }
References oomph::PVDEquationsWithPressure< DIM >::interpolated_solid_p().
get_interpolating_node_at_local_coordinate()
template<unsigned DIM> Node* oomph::RefineableQPVDElementWithContinuousPressure< DIM >::get_interpolating_node_at_local_coordinate (const Vector< double > & s, const int & value_id) inline virtual
The velocity nodes are the same as the geometric nodes. The pressure nodes must be calculated by using the same methods as the geometric nodes, but by recalling that there are only two pressure nodes per edge.
Construct the general pressure index from the components.
Reimplemented from oomph::RefineableElement.
     {
 #ifdef PARANOID
       RefineableElement::check_value_id(1, value_id);
 #endif
       // If we are calculating solid pressure nodes
       if (value_id == 0)
       {
         // Storage for the index of the pressure node
         unsigned total_index = 0;
         // The number of nodes along each 1d edge is 2.
         unsigned NNODE_1D = 2;
         // Storage for the index along each boundary
         Vector<int> index(DIM);
         // Loop over the coordinates
         for (unsigned i = 0; i < DIM; i++)
         {
           // If we are at the lower limit, the index is zero
           if (s[i] == -1.0)
           {
             index[i] = 0;
           }
           // If we are at the upper limit, the index is the number of nodes
           // minus 1
           else if (s[i] == 1.0)
           {
             index[i] = NNODE_1D - 1;
           }
           // Otherwise, we have to calculate the index in general
           else
           {
             // For uniformly spaced nodes the 0th node number would be
             double float_index = 0.5 * (1.0 + s[i]) * (NNODE_1D - 1);
             index[i] = int(float_index);
             // What is the excess. This should be safe because the
             // taking the integer part rounds down
             double excess = float_index - index[i];
             // If the excess is bigger than our tolerance there is no node,
             // return null
             if ((excess > FiniteElement::Node_location_tolerance) &&
                 ((1.0 - excess) > FiniteElement::Node_location_tolerance))
             {
               return 0;
             }
           }
           total_index +=
             index[i] * static_cast<unsigned>(pow(static_cast<float>(NNODE_1D),
                                                  static_cast<int>(i)));
         }
         // If we've got here we have a node, so let's return a pointer to it
         return this->solid_pressure_node_pt(total_index);
       }
       // Otherwise velocity nodes are the same as pressure nodes
       else
       {
         return this->get_node_at_local_coordinate(s);
       }
     }
References oomph::RefineableElement::check_value_id(), DIM, oomph::FiniteElement::get_node_at_local_coordinate(), i, int(), oomph::FiniteElement::Node_location_tolerance, Eigen::bfloat16_impl::pow(), s, and oomph::RefineableQPVDElementWithContinuousPressure< DIM >::solid_pressure_node_pt().
interpolating_basis()
template<unsigned DIM> void oomph::RefineableQPVDElementWithContinuousPressure< DIM >::interpolating_basis (const Vector< double > & s, Shape & psi, const int & value_id) const inline virtual
The basis interpolating the pressure is given by pshape(). / The basis interpolating the velocity is shape().
Reimplemented from oomph::RefineableElement.
     {
 #ifdef PARANOID
       RefineableElement::check_value_id(1, value_id);
 #endif
       if (value_id == 0)
       {
         return this->solid_pshape(s, psi);
       }
       else
       {
         return this->shape(s, psi);
       }
     }
References oomph::RefineableElement::check_value_id(), oomph::FiniteElement::shape(), and oomph::QPVDElementWithContinuousPressure< DIM >::solid_pshape().
interpolating_node_pt()
template<unsigned DIM> Node* oomph::RefineableQPVDElementWithContinuousPressure< DIM >::interpolating_node_pt (const unsigned & n, const int & value_id) inline virtual
The pressure "nodes" are a subset of the nodes, so when value_id==0, the n-th pressure node is returned.
Reimplemented from oomph::RefineableElement.
     {
 #ifdef PARANOID
       RefineableElement::check_value_id(1, value_id);
 #endif
       // If we are at the value return the solid pressure node
       if (value_id == 0)
       {
         return this->solid_pressure_node_pt(n);
       }
       // Otherwise return the nodal values
       else
       {
         return this->node_pt(n);
       }
     }
References oomph::RefineableElement::check_value_id(), oomph::FiniteElement::node_pt(), and oomph::RefineableQPVDElementWithContinuousPressure< DIM >::solid_pressure_node_pt().
local_one_d_fraction_of_interpolating_node()
template<unsigned DIM> double oomph::RefineableQPVDElementWithContinuousPressure< DIM >::local_one_d_fraction_of_interpolating_node (const unsigned & n1d, const unsigned & i, const int & value_id) inline virtual
The pressure nodes are the corner nodes, so when value_id==0, the fraction is the same as the 1d node number, 0 or 1.
Reimplemented from oomph::RefineableElement.
     {
 #ifdef PARANOID
       RefineableElement::check_value_id(1, value_id);
 #endif
       // If it's the only value, we have the pressure
       if (value_id == 0)
       {
         // The pressure nodes are just located on the boundaries at 0 or 1
         return double(n1d);
       }
       // Otherwise we have the geometric nodes
       else
       {
         return this->local_one_d_fraction_of_node(n1d, i);
       }
     }
References oomph::RefineableElement::check_value_id(), i, and oomph::FiniteElement::local_one_d_fraction_of_node().
ncont_interpolated_values()
template<unsigned DIM> unsigned oomph::RefineableQPVDElementWithContinuousPressure< DIM >::ncont_interpolated_values () const inline virtual
Number of continuously interpolated values (1) solid pressure.
Reimplemented from oomph::RefineablePVDEquationsWithPressure< DIM >.
     {
       return 1;
     }
ninterpolating_node()
template<unsigned DIM> unsigned oomph::RefineableQPVDElementWithContinuousPressure< DIM >::ninterpolating_node (const int & value_id) inline virtual
The number of pressure nodes is 2^DIM. The number of velocity nodes is the same as the number of geometric nodes.
Reimplemented from oomph::RefineableElement.
     {
 #ifdef PARANOID
       RefineableElement::check_value_id(1, value_id);
 #endif
       if (value_id == 0)
       {
         return static_cast<unsigned>(pow(2.0, static_cast<int>(DIM)));
       }
       else
       {
         return this->nnode();
       }
     }
References oomph::RefineableElement::check_value_id(), DIM, oomph::FiniteElement::nnode(), and Eigen::bfloat16_impl::pow().
ninterpolating_node_1d()
template<unsigned DIM> unsigned oomph::RefineableQPVDElementWithContinuousPressure< DIM >::ninterpolating_node_1d (const int & value_id) inline virtual
The number of 1d pressure nodes is 2, otherwise we have the positional nodes
Reimplemented from oomph::RefineableElement.
     {
 #ifdef PARANOID
       RefineableElement::check_value_id(1, value_id);
 #endif
       if (value_id == 0)
       {
         return 2;
       }
       else
       {
         return this->nnode_1d();
       }
     }
References oomph::RefineableElement::check_value_id(), and oomph::FiniteElement::nnode_1d().
nrecovery_order()
template<unsigned DIM> unsigned oomph::RefineableQPVDElementWithContinuousPressure< DIM >::nrecovery_order () inline virtual
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       return 2;
     } // NNODE_1D-1;}
nvertex_node()
template<unsigned DIM> unsigned oomph::RefineableQPVDElementWithContinuousPressure< DIM >::nvertex_node () const inline virtual
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       return QPVDElementWithContinuousPressure<DIM>::nvertex_node();
     }
References oomph::FiniteElement::nvertex_node().
pin_elemental_redundant_nodal_solid_pressures()
template<unsigned DIM> void oomph::RefineableQPVDElementWithContinuousPressure< DIM >::pin_elemental_redundant_nodal_solid_pressures () inline virtual
Pin the redundant solid pressure.
Reimplemented from oomph::PVDEquationsBase< DIM >.
     {
       // Find the index of the solid pressure
       int solid_p_index = this->solid_p_nodal_index();
       // Let's pin all pressure nodes
       unsigned n_node = this->nnode();
       for (unsigned l = 0; l < n_node; l++)
       {
         // Pin the solid pressure
         this->node_pt(l)->pin(solid_p_index);
       }
       // Now loop over the pressure nodes and unpin the solid pressures
       unsigned n_solid_pres = this->npres_solid();
       // Loop over these nodes and unpin the solid pressures
       for (unsigned l = 0; l < n_solid_pres; l++)
       {
         Node* nod_pt = this->solid_pressure_node_pt(l);
         if (!nod_pt->is_hanging(solid_p_index))
         {
           nod_pt->unpin(solid_p_index);
         }
       }
     }
References oomph::Node::is_hanging(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::QPVDElementWithContinuousPressure< DIM >::npres_solid(), oomph::Data::pin(), oomph::QPVDElementWithContinuousPressure< DIM >::solid_p_nodal_index(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::solid_pressure_node_pt(), and oomph::Data::unpin().
rebuild_from_sons()
template<unsigned DIM> void oomph::RefineableQPVDElementWithContinuousPressure< DIM >::rebuild_from_sons (Mesh *& mesh_pt) inline virtual
Empty rebuild from sons, empty.
Implements oomph::RefineableElement.
 {}
required_nvalue()
template<unsigned DIM> unsigned oomph::RefineableQPVDElementWithContinuousPressure< DIM >::required_nvalue (const unsigned & n) const inline virtual
Overload the number of additional solid dofs at each node, we shall always assign 1, otherwise it's a real pain
Reimplemented from oomph::QPVDElementWithContinuousPressure< DIM >.
     {
       return 1;
     }
solid_pressure_node_pt()
template<unsigned DIM> Node* oomph::RefineableQPVDElementWithContinuousPressure< DIM >::solid_pressure_node_pt (const unsigned & l) inline virtual
Reimplemented from oomph::RefineablePVDEquationsWithPressure< DIM >.
     {
       return this->node_pt(this->Pconv[l]);
     }
References oomph::FiniteElement::node_pt(), and oomph::QPVDElementWithContinuousPressure< DIM >::Pconv.
Referenced by oomph::RefineableQPVDElementWithContinuousPressure< DIM >::get_interpolating_node_at_local_coordinate(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::interpolating_node_pt(), and oomph::RefineableQPVDElementWithContinuousPressure< DIM >::pin_elemental_redundant_nodal_solid_pressures().
unpin_elemental_solid_pressure_dofs()
template<unsigned DIM> void oomph::RefineableQPVDElementWithContinuousPressure< DIM >::unpin_elemental_solid_pressure_dofs () inline virtual
Unpin all pressure dofs.
Implements oomph::PVDEquationsBase< DIM >.
     {
       // find the index at which the pressure is stored
       int solid_p_index = this->solid_p_nodal_index();
       unsigned n_node = this->nnode();
       // loop over nodes
       for (unsigned n = 0; n < n_node; n++)
       {
         this->node_pt(n)->unpin(solid_p_index);
       }
     }
References n, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::QPVDElementWithContinuousPressure< DIM >::solid_p_nodal_index(), and oomph::Data::unpin().
vertex_node_pt()
template<unsigned DIM> Node* oomph::RefineableQPVDElementWithContinuousPressure< DIM >::vertex_node_pt (const unsigned & j) const inline virtual
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       return QPVDElementWithContinuousPressure<DIM>::vertex_node_pt(j);
     }
References j, and oomph::FiniteElement::vertex_node_pt().
The documentation for this class was generated from the following file:
refineable_solid_elements.h