MercuryDPM: Eigen::internal::minmax_coeff_visitor< Derived, is_min, PropagateNumbers, false > Struct Template Reference
Eigen::internal::minmax_coeff_visitor< Derived, is_min, PropagateNumbers, false > Struct Template Reference
#include <Visitor.h>
Public Types
typedef Derived::Scalar Scalar
using Packet = typename packet_traits< Scalar >::type
using Comparator = minmax_compare< Scalar, PropagateNumbers, is_min >
Public Types inherited from Eigen::internal::coeff_visitor< Derived >
typedef Derived::Scalar Scalar
Public Member Functions
EIGEN_DEVICE_FUNC void operator() (const Scalar &value, Index i, Index j)
EIGEN_DEVICE_FUNC void packet (const Packet &p, Index i, Index j)
EIGEN_DEVICE_FUNC void initpacket (const Packet &p, Index i, Index j)
Public Member Functions inherited from Eigen::internal::coeff_visitor< Derived >
EIGEN_DEVICE_FUNC coeff_visitor ()
EIGEN_DEVICE_FUNC void init (const Scalar &value, Index i, Index j)
Additional Inherited Members
Public Attributes inherited from Eigen::internal::coeff_visitor< Derived >
Index row
Index col
Scalar res
Member Typedef Documentation
Comparator
template<typename Derived , bool is_min> using Eigen::internal::minmax_coeff_visitor< Derived, is_min, PropagateNumbers, false >::Comparator = minmax_compare<Scalar, PropagateNumbers, is_min>
Packet
template<typename Derived , bool is_min> using Eigen::internal::minmax_coeff_visitor< Derived, is_min, PropagateNumbers, false >::Packet = typename packet_traits<Scalar>::type
Scalar
template<typename Derived , bool is_min> typedef Derived::Scalar Eigen::internal::minmax_coeff_visitor< Derived, is_min, PropagateNumbers, false >::Scalar
Member Function Documentation
initpacket()
template<typename Derived , bool is_min> EIGEN_DEVICE_FUNC void Eigen::internal::minmax_coeff_visitor< Derived, is_min, PropagateNumbers, false >::initpacket (const Packet & p, Index i, Index j) inline
{
     const Index PacketSize = packet_traits<Scalar>::size;
     Scalar value = Comparator::predux(p);
     if ((numext::isnan)(value)) {
       this->res = value;
       this->row = 0;
       this->col = 0;
       return;
     }
     const Packet range = preverse(plset<Packet>(Scalar(1)));
     /* mask will be zero for NaNs, so they will be ignored. */
     Packet mask = pcmp_eq(pset1<Packet>(value), p);
     Index max_idx = PacketSize - static_cast<Index>(predux_max(pand(range, mask)));
     this->res = value;
     this->row = Derived::IsRowMajor ? i : i + max_idx;
     this->col = Derived::IsRowMajor ? j + max_idx : j;
   }
operator()()
template<typename Derived , bool is_min> EIGEN_DEVICE_FUNC void Eigen::internal::minmax_coeff_visitor< Derived, is_min, PropagateNumbers, false >::operator() (const Scalar & value, Index i, Index j) inline
{
     if ((!(numext::isnan)(value) && (numext::isnan)(this->res)) || Comparator::compare(value, this->res)) {
       this->res = value;
       this->row = i;
       this->col = j;
     }
   }
References Eigen::internal::minmax_compare< Scalar, NaNPropagation, is_min >::compare(), Eigen::numext::isnan(), Eigen::internal::coeff_visitor< Derived >::res, and Eigen::value.
packet()
template<typename Derived , bool is_min> EIGEN_DEVICE_FUNC void Eigen::internal::minmax_coeff_visitor< Derived, is_min, PropagateNumbers, false >::packet (const Packet & p, Index i, Index j) inline
{
     const Index PacketSize = packet_traits<Scalar>::size;
     Scalar value = Comparator::predux(p);
     if ((!(numext::isnan)(value) && (numext::isnan)(this->res)) || Comparator::compare(value, this->res)) {
       const Packet range = preverse(plset<Packet>(Scalar(1)));
       /* mask will be zero for NaNs, so they will be ignored. */
       Packet mask = pcmp_eq(pset1<Packet>(value), p);
       Index max_idx = PacketSize - static_cast<Index>(predux_max(pand(range, mask)));
       this->res = value;
       this->row = Derived::IsRowMajor ? i : i + max_idx;
       this->col = Derived::IsRowMajor ? j + max_idx : j;
     }
   }
References Eigen::internal::coeff_visitor< Derived >::col, Eigen::internal::minmax_compare< Scalar, NaNPropagation, is_min >::compare(), i, Eigen::numext::isnan(), j, p, Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, isInt >::PacketSize, Eigen::internal::pand(), Eigen::internal::pcmp_eq(), Eigen::internal::minmax_compare< Scalar, NaNPropagation, is_min >::predux(), Eigen::internal::predux_max(), Eigen::internal::preverse(), Eigen::internal::coeff_visitor< Derived >::res, Eigen::internal::coeff_visitor< Derived >::row, and Eigen::value.
The documentation for this struct was generated from the following file:
Visitor.h