MercuryDPM: unstructured_fourier_decomposed_acoustic_fsi.cc File Reference
unstructured_fourier_decomposed_acoustic_fsi.cc File Reference
#include <complex>
#include <cmath>
#include "generic.h"
#include "fourier_decomposed_helmholtz.h"
#include "time_harmonic_fourier_decomposed_linear_elasticity.h"
#include "multi_physics.h"
#include "meshes/annular_mesh.h"
#include "meshes/triangle_mesh.h"
#include "oomph_crbond_bessel.h"
Classes
class MyStraightLine
Straight 1D line in 2D space.
class CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >
Coated sphere FSI.
Namespaces
Global_Parameters
Namespace for global parameters.
Functions
std::complex< double > Global_Parameters::Nu (std::complex< double >(0.3, 0.0))
Poisson's ratio Nu.
Vector< std::complex< double > > Global_Parameters::E (2, std::complex< double >(1.0, 0.0))
Define the non-dimensional Young's modulus.
Vector< std::complex< double > > Global_Parameters::Omega_sq (2, std::complex< double >(100.0, 0.0))
Non-dim square of frequency for solid – dependent variable!
Vector< double > Global_Parameters::Density_ratio (2, 1.0)
Density ratio: solid to fluid.
void Global_Parameters::update_parameter_values ()
Function to update dependent parameter values.
void Global_Parameters::pressure_load (const Vector< double > &x, const Vector< double > &n, Vector< std::complex< double > > &traction)
Pressure load (real and imag part)
int main (int argc, char **argv)
Driver for coated sphere loaded by lineared fluid loading.
Function Documentation
main()
int main (int argc , char ** argv)
Driver for coated sphere loaded by lineared fluid loading.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Output directory
  CommandLineArgs::specify_command_line_flag("--dir",
                                             &Global_Parameters::Directory);
  // Parameter controlling the sharpness of the pressure load
  CommandLineArgs::specify_command_line_flag("--alpha",
                                             &Global_Parameters::Alpha);
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Set values for parameter values
  Global_Parameters::Q=5.0;
  Global_Parameters::Density_ratio[0]=0.1;
  Global_Parameters::Density_ratio[1]=0.1;
  Global_Parameters::update_parameter_values();
  // Update dependent parameters values
  Global_Parameters::update_parameter_values();
  // Set up doc info
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory(Global_Parameters::Directory);
 #ifdef ADAPTIVE
  // Set up the problem
  CoatedSphereProblem<
   ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement
   <TTimeHarmonicFourierDecomposedLinearElasticityElement<3> >,
   ProjectableFourierDecomposedHelmholtzElement
   <TFourierDecomposedHelmholtzElement<3> > > problem;
 #else
  // Set up the problem
  CoatedSphereProblem<TTimeHarmonicFourierDecomposedLinearElasticityElement<3>,
                      TFourierDecomposedHelmholtzElement<3> > problem;
 #endif
  //Parameter incrementation
  unsigned nstep=3;
  for(unsigned i=0;i<nstep;i++)
   {
 #ifdef ADAPTIVE
    // Solve the problem with Newton's method, allowing
    // up to max_adapt mesh adaptations after every solve.
    unsigned max_adapt=3;
    problem.newton_solve(max_adapt);
 #else
    // Solve the problem with Newton's method
    problem.newton_solve();
 #endif
    // Doc solution
    problem.doc_solution(doc_info);
    // Make rib a lot heavier but keep its stiffness
    if (i==0)
     {
      Global_Parameters::E[1]=1.0;
      Global_Parameters::Density_ratio[1]=10.0;
      Global_Parameters::update_parameter_values();
     }
    // Make rib very soft and inertia-less
    if (i==1)
     {
      Global_Parameters::E[1]=1.0e-16;
      Global_Parameters::Density_ratio[1]=0.0;
      Global_Parameters::update_parameter_values();
     }
   }
 } //end_of_main
References Global_Parameters::Alpha, Global_Parameters::Density_ratio, Global_Parameters::Directory, oomph::CommandLineArgs::doc_specified_flags(), Global_Parameters::E, i, oomph::CommandLineArgs::parse_and_assign(), problem, Global_Parameters::Q, oomph::DocInfo::set_directory(), oomph::CommandLineArgs::setup(), oomph::CommandLineArgs::specify_command_line_flag(), and Global_Parameters::update_parameter_values().