MercuryDPM: level1_real_impl.h File Reference
level1_real_impl.h File Reference
#include "common.h"
Functions
RealScalar EIGEN_BLAS_FUNC_NAME() asum (int *n, Scalar *px, int *incx)
int EIGEN_CAT (i, EIGEN_BLAS_FUNC_NAME(amax))(int *n
if incx make_vector (x, *n).cwiseAbs().maxCoeff(&ret)
else make_vector (x, *n, std::abs(*incx)).cwiseAbs().maxCoeff(&ret)
return int (ret)+1
int EIGEN_CAT (i, EIGEN_BLAS_FUNC_NAME(amin))(int *n
Scalar EIGEN_BLAS_FUNC_NAME() dot (int *n, Scalar *px, int *incx, Scalar *py, int *incy)
Scalar EIGEN_BLAS_FUNC_NAME() nrm2 (int *n, Scalar *px, int *incx)
EIGEN_BLAS_FUNC() rot (int *n, Scalar *px, int *incx, Scalar *py, int *incy, Scalar *pc, Scalar *ps)
Variables
int Scalar * px
int Scalar int * incx
Scalar * x = reinterpret_cast<Scalar *>(px)
Eigen::DenseIndex ret
Function Documentation
asum()
RealScalar EIGEN_BLAS_FUNC_NAME() asum (int * n, Scalar * px, int * incx)
{
   //   std::cerr << "_asum " << *n << " " << *incx << "\n";
   Scalar *x = reinterpret_cast<Scalar *>(px);
   if (*n <= 0) return 0;
   if (*incx == 1)
     return make_vector(x, *n).cwiseAbs().sum();
   else
     return make_vector(x, *n, std::abs(*incx)).cwiseAbs().sum();
 }
References abs(), incx, make_vector(), n, px, and x.
dot()
Scalar EIGEN_BLAS_FUNC_NAME() dot (int * n, Scalar * px, int * incx, Scalar * py, int * incy)
{
   //   std::cerr << "_dot " << *n << " " << *incx << " " << *incy << "\n";
   if (*n <= 0) return 0;
   Scalar *x = reinterpret_cast<Scalar *>(px);
   Scalar *y = reinterpret_cast<Scalar *>(py);
   if (*incx == 1 && *incy == 1)
     return (make_vector(x, *n).cwiseProduct(make_vector(y, *n))).sum();
   else if (*incx > 0 && *incy > 0)
     return (make_vector(x, *n, *incx).cwiseProduct(make_vector(y, *n, *incy))).sum();
   else if (*incx < 0 && *incy > 0)
     return (make_vector(x, *n, -*incx).reverse().cwiseProduct(make_vector(y, *n, *incy))).sum();
   else if (*incx > 0 && *incy < 0)
     return (make_vector(x, *n, *incx).cwiseProduct(make_vector(y, *n, -*incy).reverse())).sum();
   else if (*incx < 0 && *incy < 0)
     return (make_vector(x, *n, -*incx).reverse().cwiseProduct(make_vector(y, *n, -*incy).reverse())).sum();
   else
     return 0;
 }
References incx, incy, make_vector(), n, px, py, x, and y.
Referenced by oomph::FixedVolumeSpineLineMarangoniFluidInterfaceElement< ELEMENT >::add_additional_residual_contributions_interface(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_enclosed_volume(), oomph::LineVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_volume_flux(), DataFiles::DataFiles(), EIGEN_DECLARE_TEST(), oomph::PointFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LineVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::AxisymmetricVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::SurfaceVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), smc.smc::getLikelihood(), Eigen::MatrixBase< Derived >::isUnitary(), smc.smc::recursiveBayesian(), adjoint_specific< true >::run(), adjoint_specific< false >::run(), Eigen::QuaternionBase< Derived >::slerp(), and Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::squaredDistance().
EIGEN_CAT() [1/2]
int EIGEN_CAT (i , EIGEN_BLAS_FUNC_NAME(amax))
References n.
EIGEN_CAT() [2/2]
int EIGEN_CAT (i , EIGEN_BLAS_FUNC_NAME(amin))
References abs(), incx, int(), make_vector(), n, px, ret, and x.
int()
return int (ret)
Referenced by EIGEN_CAT().
make_vector() [1/2]
if incx make_vector (x , * n) &
Referenced by asum(), dot(), EIGEN_CAT(), nrm2(), and rot().
make_vector() [2/2]
else make_vector (x , * n, std::abs * incx) &
nrm2()
Scalar EIGEN_BLAS_FUNC_NAME() nrm2 (int * n, Scalar * px, int * incx)
{
   //   std::cerr << "_nrm2 " << *n << " " << *incx << "\n";
   if (*n <= 0) return 0;
   Scalar *x = reinterpret_cast<Scalar *>(px);
   if (*incx == 1)
     return make_vector(x, *n).stableNorm();
   else
     return make_vector(x, *n, std::abs(*incx)).stableNorm();
 }
References abs(), incx, make_vector(), n, px, and x.
rot()
EIGEN_BLAS_FUNC() rot (int * n, Scalar * px, int * incx, Scalar * py, int * incy, Scalar * pc, Scalar * ps)
{
   //   std::cerr << "_rot " << *n << " " << *incx << " " << *incy << "\n";
   if (*n <= 0) return;
   Scalar *x = reinterpret_cast<Scalar *>(px);
   Scalar *y = reinterpret_cast<Scalar *>(py);
   Scalar c = *reinterpret_cast<Scalar *>(pc);
   Scalar s = *reinterpret_cast<Scalar *>(ps);
   StridedVectorType vx(make_vector(x, *n, std::abs(*incx)));
   StridedVectorType vy(make_vector(y, *n, std::abs(*incy)));
   Eigen::Reverse<StridedVectorType> rvx(vx);
   Eigen::Reverse<StridedVectorType> rvy(vy);
   if (*incx < 0 && *incy > 0)
     Eigen::internal::apply_rotation_in_the_plane(rvx, vy, Eigen::JacobiRotation<Scalar>(c, s));
   else if (*incx > 0 && *incy < 0)
     Eigen::internal::apply_rotation_in_the_plane(vx, rvy, Eigen::JacobiRotation<Scalar>(c, s));
   else
     Eigen::internal::apply_rotation_in_the_plane(vx, vy, Eigen::JacobiRotation<Scalar>(c, s));
 }
References abs(), Eigen::internal::apply_rotation_in_the_plane(), calibrate::c, incx, incy, make_vector(), n, pc, ps, px, py, rvx(), rvy(), s, vx(), vy(), x, and y.
Referenced by alignedboxNonIntegralRotatable(), alignedboxRotatable(), oomph::SolidHelpers::doc_2D_principal_stress(), Eigen::EulerAngles< Scalar_, _System >::EulerAngles(), hyperplane(), Eigen::MatrixPower< MatrixType >::initialize(), jacobi(), openglsupport_test_loop(), Eigen::EulerAngles< Scalar_, _System >::operator=(), parametrizedline(), Eigen::ComplexSchur< MatrixType_ >::reduceToTriangularForm(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, Options, true >::run(), Eigen::RealSchur< MatrixType_ >::splitOffTwoRows(), and Eigen::internal::tridiagonal_qr_step().
Variable Documentation
incx
int Scalar int* incx
Initial value:
{
  if (*n <= 0) return 0
Referenced by asum(), dot(), EIGEN_CAT(), nrm2(), and rot().
px
int Scalar* px
Referenced by asum(), dot(), EIGEN_CAT(), nrm2(), and rot().
ret
Eigen::DenseIndex ret
Referenced by EIGEN_CAT().
x
Scalar* x = reinterpret_cast<Scalar *>(px)
Referenced by asum(), dot(), EIGEN_CAT(), nrm2(), and rot().