MercuryDPM: quatmul.cpp File Reference
quatmul.cpp File Reference
#include <iostream>
#include <Eigen/Core>
#include <Eigen/Geometry>
#include <bench/BenchTimer.h>
Functions
template<typename Quat >
EIGEN_DONT_INLINE void quatmul_default (const Quat &a, const Quat &b, Quat &c)
template<typename Quat >
EIGEN_DONT_INLINE void quatmul_novec (const Quat &a, const Quat &b, Quat &c)
template<typename Quat >
void bench (const std::string &label)
int main ()
Function Documentation
bench()
template<typename Quat > void bench (const std::string & label)
{
   int tries = 10;
   int rep = 1000000;
   BenchTimer t;
   Quat a(4, 1, 2, 3);
   Quat b(2, 3, 4, 5);
   Quat c;
   std::cout.precision(3);
   BENCH(t, tries, rep, quatmul_default(a, b, c));
   std::cout << label << " default " << 1e3 * t.best(CPU_TIMER) << "ms  \t" << 1e-6 * double(rep) / (t.best(CPU_TIMER))
             << " M mul/s\n";
   BENCH(t, tries, rep, quatmul_novec(a, b, c));
   std::cout << label << " novec   " << 1e3 * t.best(CPU_TIMER) << "ms  \t" << 1e-6 * double(rep) / (t.best(CPU_TIMER))
             << " M mul/s\n";
 }
References a, b, BENCH, calibrate::c, Eigen::CPU_TIMER, e(), UniformPSDSelfTest::label, quatmul_default(), quatmul_novec(), and plotPSD::t.
main()
int main ()
            {
   bench<Quaternionf>("float ");
   bench<Quaterniond>("double");
   return 0;
 }
quatmul_default()
template<typename Quat > EIGEN_DONT_INLINE void quatmul_default (const Quat & a, const Quat & b, Quat & c)
{
   c = a * b;
 }
References a, b, and calibrate::c.
Referenced by bench().
quatmul_novec()
template<typename Quat > EIGEN_DONT_INLINE void quatmul_novec (const Quat & a, const Quat & b, Quat & c)
{
   c = internal::quat_product<0, Quat, Quat, typename Quat::Scalar, Aligned>::run(a, b);
 }
References a, b, calibrate::c, and Eigen::internal::quat_product< Arch, Derived1, Derived2, Scalar >::run().
Referenced by bench().