MercuryDPM: static3d.cpp File Reference
static3d.cpp File Reference
#include "Chute.h"
#include "StatisticsVector.h"
#include <iostream>
#include <Species/LinearViscoelasticSlidingFrictionSpecies.h>
Classes
class Cstatic3D
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
Start off my solving the default problem
 {
     Cstatic3D static3d;
     static3d.setName("static3d");
     static3d.set_particle_properties();
     static3d.setSaveCount(12000);
     static3d.setTimeMax(1);
     static3d.solve();
     //~ static3d.write(cout,true);
 }
References Cstatic3D::set_particle_properties(), DPMBase::setName(), DPMBase::setSaveCount(), DPMBase::setTimeMax(), and DPMBase::solve().