MercuryDPM: TwoDDGMesh< ELEMENT > Class Template Reference
TwoDDGMesh< ELEMENT > Class Template Reference
Public Member Functions
TwoDDGMesh (const unsigned &Nx, const unsigned &Ny, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
void neighbour_finder (FiniteElement *const &bulk_element_pt, const int &face_index, const Vector< double > &s_bulk, FaceElement *&face_element_pt, Vector< double > &s_face)
TwoDDGMesh (const unsigned &Nx, const unsigned &Ny, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
void neighbour_finder (FiniteElement *const &bulk_element_pt, const int &face_index, const Vector< double > &s_bulk, FaceElement *&face_element_pt, Vector< double > &s_face)
TwoDDGMesh (const unsigned &n_x, const unsigned &n_y, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
void neighbour_finder (FiniteElement *const &bulk_element_pt, const int &face_index, const Vector< double > &s_bulk, FaceElement *&face_element_pt, Vector< double > &s_face)
TwoDDGMesh (const unsigned &Nx, const unsigned &Ny, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
void neighbour_finder (FiniteElement *const &bulk_element_pt, const int &face_index, const Vector< double > &s_bulk, FaceElement *&face_element_pt, Vector< double > &s_face)
TwoDDGMesh (const unsigned &Nx, const unsigned &Ny, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
void neighbour_finder (FiniteElement *const &bulk_element_pt, const int &face_index, const Vector< double > &s_bulk, FaceElement *&face_element_pt, Vector< double > &s_face)
Public Member Functions inherited from oomph::DGMesh
DGMesh ()
virtual ~DGMesh ()
void setup_face_neighbour_info (const bool &add_face_data_as_external=false)
void limit_slopes (SlopeLimiter *const &slope_limiter_pt)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void setup_boundary_element_info ()
virtual void setup_boundary_element_info (std::ostream &outfile)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Private Attributes
std::map< std::pair< FiniteElement *, unsigned >, FiniteElement * > Neighbour_map
std::map< std::pair< FiniteElement *, int >, FiniteElement * > Neighbour_map
std::map< std::pair< FiniteElement *, int >, FaceElement * > Face_element_pt
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::DGMesh
static double FaceTolerance = 1.0e-10
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Constructor & Destructor Documentation
TwoDDGMesh() [1/5]
template<class ELEMENT > TwoDDGMesh< ELEMENT >::TwoDDGMesh (const unsigned & Nx, const unsigned & Ny, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
   {
    Vector<double> s_fraction;
    //Lengths of the mesh
    double Lx = 1.0;
    double Ly = 1.0;
    double llx = -0.5;
    double lly = -0.5;
    //Work out the length of each element in the x and y directions
    //(Assuming uniform spacing)
    double el_length[2] = {Lx/(double)Nx, Ly/(double)Ny};
    //loop over the elements in x
    for(unsigned ex=0;ex<Nx;ex++)
     {
      //loop over the element in y
      for(unsigned ey=0;ey<Ny;ey++)
       {
        //Create a new DG element
        ELEMENT* local_element_pt = new ELEMENT;
        //Construct nodes and faces
        local_element_pt->construct_nodes_and_faces(this,time_stepper_pt);
        //Find the number of nodes
        unsigned n_node = local_element_pt->nnode();
        //Find the lower left corner of the element
        double ll_corner[2] = {llx + ex*el_length[0],lly + ey*el_length[1]};
        //For each of the nodes set the position
        for(unsigned n=0;n<n_node;n++)
         {
          //Get pointer to the node
          Node* nod_pt = local_element_pt->node_pt(n);
          //Get the relative position in local coordinates
          local_element_pt->local_fraction_of_node(n,s_fraction);
          //Loop over the coordinates and set the position
          for(unsigned i=0;i<2;i++)
           {
            nod_pt->x(i) = ll_corner[i] + el_length[i]*s_fraction[i];
           }
          //Now set the value
          nod_pt->set_value(0,1.0);
          //Add each node to the node list
          Node_pt.push_back(nod_pt);
         }
        //Now add the element to the list
        Element_pt.push_back(local_element_pt);
       }
     }
    //Now loop over all the elements and set up the neighbour map
    for(unsigned ex=0;ex<Nx;ex++)
     {
      for(unsigned ey=0;ey<Ny;ey++)
       {
        //Get pointer to the element
        unsigned element_index = ex*Ny + ey;
        FiniteElement* local_el_pt = finite_element_pt(element_index);
        //Storage for indices of neighbours
        unsigned index[4];
        //North neighbour (just one up)
        if(ey < (Ny-1)) {index[0] = element_index + 1;}
        //If at top, return index at bottom (periodic conditions)
        else {index[0] = ex*Ny;}
        //East neighbour (just one across)
        if(ex < (Nx-1)) {index[1] = element_index + Ny;}
        //If at side return index at other side (periodic conditions)
        else {index[1] = ey;}
        //South neighbour
        if(ey > 0) {index[2] = element_index - 1;}
        else {index[2] = element_index + Ny-1;}
        //West neighbour
        if(ex > 0) {index[3] = element_index - Ny;}
        else {index[3] = element_index + (Nx-1)*Ny;}
        //Now store the details in the mape
        for(unsigned i=0;i<4;i++)
         {
          Neighbour_map[std::make_pair(local_el_pt,i)] =
           finite_element_pt(index[i]);
         }
       }
     }
    //Setup the connections between the neighbouring faces
    this->setup_face_neighbour_info();
   }
References i, Global_Parameters::Lx, Global_Parameters::Ly, n, GlobalParameters::Nx, GlobalParameters::Ny, oomph::Data::set_value(), and oomph::Node::x().
TwoDDGMesh() [2/5]
template<class ELEMENT > TwoDDGMesh< ELEMENT >::TwoDDGMesh (const unsigned & Nx, const unsigned & Ny, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
   {
    Vector<double> s_fraction;
    //Lengths of the mesh
    double R_min = 1.0;
    double R_max = 4.0;
    const double pi = MathematicalConstants::Pi;
    //Work out the length of each element in the x and y directions
    //(Assuming uniform spacing)
    double el_length[2] = {(R_max-R_min)/(double)Nx, (2.0*pi)/(double)Ny};
    //Vector of booleans for boundary information
    std::vector<bool> boundary_info;
    //loop over the elements in x
    for(unsigned ex=0;ex<Nx;ex++)
     {
      //loop over the element in y
      for(unsigned ey=0;ey<Ny;ey++)
       {
        //Create a new DG element
        ELEMENT* local_element_pt = new ELEMENT;
        //Find the number of nodes
        const unsigned n_node = local_element_pt->nnode();
        //Have we constructed
        bool constructed = false;
        //If we are on a boundary
        if(ex==0)
         {
          const unsigned n_p  = local_element_pt->nnode_1d();
          boundary_info.resize(n_node);
          for(unsigned n=0;n<n_node;n++) {boundary_info[n] = false;}
          //The left hand side is on a boundary
          for(unsigned n=0;n<n_p;n++)
           {
            boundary_info[n*n_p] = true;
           }
          //Lower left
          if(ey==0)
           {
           for(unsigned n=1;n<n_p;n++) {boundary_info[n] = true;}
           }
          //Upper left
          if(ey==Ny-1)
           {
            for(unsigned n=1;n<n_p;n++) {boundary_info[n_p*(n_p-1) + n] = true;}
           }
          //Now construct
          local_element_pt->construct_boundary_nodes_and_faces(
           this, boundary_info, time_stepper_pt);
          constructed = true;
         }
        //Right boundary
        else if(ex==Nx-1)
         {
          const unsigned n_p  = local_element_pt->nnode_1d();
          boundary_info.resize(n_node);
          for(unsigned n=0;n<n_node;n++) {boundary_info[n] = false;}
          //The right-hand side is on a boundary
          for(unsigned n=0;n<n_p;n++)
           {
            boundary_info[n_p-1 + n*n_p] = true;
           }
          //Lower right
          if(ey==0)
           {
           for(unsigned n=0;n<n_p-1;n++) {boundary_info[n] = true;}
           }
          //Upper right
          if(ey==Ny-1)
           {
            for(unsigned n=0;n<n_p-1;n++)
             {boundary_info[n_p*(n_p-1) + n] = true;}
           }
          //Now construct
          local_element_pt->construct_boundary_nodes_and_faces(
           this, boundary_info, time_stepper_pt);
          constructed = true;
         }
        //Otherwise it's in the middle
        else
         {
          //If on the bottom or top
          if((ey==0) || (ey==Ny-1))
           {
            const unsigned n_p  = local_element_pt->nnode_1d();
            boundary_info.resize(n_node);
            for(unsigned n=0;n<n_node;n++) {boundary_info[n] = false;}
            //If the bottom
            if(ey==0)
             {
              for(unsigned n=0;n<n_p;n++)
               {
                boundary_info[n] = true;
               }
             }
            //If on the top
            if(ey==Ny-1)
             {
              for(unsigned n=0;n<n_p;n++)
               {boundary_info[n_p*(n_p-1) + n] = true;}
             }
            //Now construct
            local_element_pt->construct_boundary_nodes_and_faces(
             this, boundary_info, time_stepper_pt);
            constructed = true;
           }
         }
        //If we haven't already constructed
        if(!constructed)
         {
          //Construct nodes and faces
          local_element_pt->construct_nodes_and_faces(this,time_stepper_pt);
         }
        //Find the lower left corner of the element
        double ll_corner[2] = {R_min + ex*el_length[0],ey*el_length[1]};
        //For each of the nodes set the position
        for(unsigned n=0;n<n_node;n++)
         {
          //Get pointer to the node
          Node* nod_pt = local_element_pt->node_pt(n);
          //Get the relative position in local coordinates
          local_element_pt->local_fraction_of_node(n,s_fraction);
          //Loop over the coordinates and set the position
          double r = ll_corner[0] + el_length[0]*s_fraction[0];
          double theta = ll_corner[1] + el_length[1]*s_fraction[1];
          nod_pt->x(0) = r*cos(theta);
          nod_pt->x(1) = r*sin(theta);
          //Add each node to the node list
          Node_pt.push_back(nod_pt);
         }
        //Now add the element to the list
        Element_pt.push_back(local_element_pt);
       }
     }
    //Set up the boundary nodes
    this->set_nboundary(2);
    //Now let's add the boundary nodes
    //Left-hand and right-hand sides
    for(unsigned e=0;e<Ny;e++)
     {
      //Left
      FiniteElement* elem_pt = this->finite_element_pt(e);
      unsigned n_p = elem_pt->nnode_1d();
      for(unsigned n=0;n<n_p;n++)
       {
        this->add_boundary_node(0,elem_pt->node_pt(n_p*n));
       }
      //Right
      elem_pt = this->finite_element_pt(Ny*(Nx-1)+e);
      n_p = elem_pt->nnode_1d();
      for(unsigned n=0;n<n_p;n++)
       {
        this->add_boundary_node(1,elem_pt->node_pt(n_p-1 + n_p*n));
       }
     }
    //Now loop over all the elements and set up the neighbour map
    for(unsigned ex=0;ex<Nx;ex++)
     {
      for(unsigned ey=0;ey<Ny;ey++)
       {
        //Get pointer to the element
        unsigned element_index = ex*Ny + ey;
        FiniteElement* local_el_pt = finite_element_pt(element_index);
        //Storage for indices of neighbours
        unsigned index[4];
        //North neighbour (just one up)
        if(ey < (Ny-1)) {index[0] = element_index + 1;}
        //If at top, return index at bottom (periodic conditions)
        else {index[0] = ex*Ny;}
        //East neighbour (just one across)
        if(ex < (Nx-1)) {index[1] = element_index + Ny;}
        //If at side return index at other side (periodic conditions)
        else {index[1] = ey;}
        //South neighbour
        if(ey > 0) {index[2] = element_index - 1;}
        else {index[2] = element_index + Ny-1;}
        //West neighbour
        if(ex > 0) {index[3] = element_index - Ny;}
        else {index[3] = element_index + (Nx-1)*Ny;}
        //Now store the details in the mape
        for(unsigned i=0;i<4;i++)
         {
          Neighbour_map[std::make_pair(local_el_pt,i)] =
           finite_element_pt(index[i]);
         }
       }
     }
    //Now set up the neighbour information
    /*const unsigned n_element = this->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      dynamic_cast<ELEMENT*>(this->element_pt(e))->setup_face_neighbour_info();
      }*/
    this->setup_face_neighbour_info();
   }
References cos(), e(), i, n, oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::node_pt(), GlobalParameters::Nx, GlobalParameters::Ny, constants::pi, oomph::MathematicalConstants::Pi, UniformPSDSelfTest::r, sin(), BiharmonicTestFunctions2::theta, and oomph::Node::x().
TwoDDGMesh() [3/5]
template<class ELEMENT > TwoDDGMesh< ELEMENT >::TwoDDGMesh (const unsigned & n_x, const unsigned & n_y, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
   {
    Vector<double> s_fraction;
    //Lengths of the mesh
    double Lx = 2.4;
    double Ly = 0.8;
    unsigned Nx = 4*n_x, Ny = 4*n_y;
    //Work out the length of each element in the x and y directions
    //(Assuming uniform spacing)
    //Create the flow bit
    double el_length[2] = {Lx/(double)Nx, Ly/(double)Ny};
    //Vector of booleans for boundary information
    std::vector<bool> boundary_info;
    unsigned Nx1 = n_x;
    unsigned Ny1 = 5*n_y;
    double llx1 = 0.0;
    double lly1 = 0.0;
    //loop over the elements in x
    for(unsigned ex=0;ex<Nx1;ex++)
     {
      //loop over the element in y
      for(unsigned ey=0;ey<Ny1;ey++)
       {
        //Create a new DG element
        ELEMENT* local_element_pt = new ELEMENT;
        //Find the number of nodes
        const unsigned n_node = local_element_pt->nnode();
        //Have we constructed
        bool constructed = false;
        //Left boundary
        if(ex==0)
         {
          const unsigned n_p  = local_element_pt->nnode_1d();
          boundary_info.resize(n_node);
          for(unsigned n=0;n<n_node;n++) {boundary_info[n] = false;}
          //The left hand side is on a boundary
          for(unsigned n=0;n<n_p;n++)
           {
            boundary_info[n*n_p] = true;
           }
          //Lower left
          if(ey==0)
           {
            for(unsigned n=1;n<n_p;n++) {boundary_info[n] = true;}
           }
          //Upper left
          if(ey==Ny1-1)
           {
            for(unsigned n=1;n<n_p;n++) {boundary_info[n_p*(n_p-1) + n] = true;}
           }
          //Now construct
          local_element_pt->construct_boundary_nodes_and_faces(
           this, boundary_info, time_stepper_pt);
          constructed = true;
         }
        //Right boundary
        else if(ex==Nx1-1)
         {
          const unsigned n_p  = local_element_pt->nnode_1d();
          boundary_info.resize(n_node);
          for(unsigned n=0;n<n_node;n++) {boundary_info[n] = false;}
          //Bottom right
          if(ey==0)
           {
            //The bottom is a boundary
            for(unsigned n=0;n<n_p-1;n++) {boundary_info[n] = true;}
           }
          //The right-hand side is on a boundary in the early bit
          //of the step
          if(ey < n_y)
           {
            for(unsigned n=0;n<n_p;n++)
             {
              boundary_info[n_p-1 + n*n_p] = true;
             }
           }
          //If top right
          if(ey==Ny1-1)
           {
            //The top is a boundary
            for(unsigned n=0;n<n_p;n++)
             {boundary_info[n_p*(n_p-1) + n] = true;}
           }
          local_element_pt->construct_boundary_nodes_and_faces(
             this, boundary_info, time_stepper_pt);
          constructed = true;
         }
        //Otherwise it's in the middle
        else
         {
          //If on the bottom or top
          if((ey==0) || (ey==Ny1-1))
           {
            const unsigned n_p  = local_element_pt->nnode_1d();
            boundary_info.resize(n_node);
            for(unsigned n=0;n<n_node;n++) {boundary_info[n] = false;}
            //If the bottom
            if(ey==0)
             {
              for(unsigned n=0;n<n_p;n++)
               {
                boundary_info[n] = true;
               }
             }
            //If on the top
            if(ey==Ny1-1)
             {
              for(unsigned n=0;n<n_p;n++)
               {boundary_info[n_p*(n_p-1) + n] = true;}
             }
            //Now construct
            local_element_pt->construct_boundary_nodes_and_faces(
             this, boundary_info, time_stepper_pt);
            constructed = true;
           }
         }
        //If we haven't already constructed
        if(!constructed)
         {
          //Construct nodes and faces
          local_element_pt->construct_nodes_and_faces(this,time_stepper_pt);
         }
        //Find the lower left corner of the element
        double ll_corner[2] = {llx1 + ex*el_length[0],lly1 + ey*el_length[1]};
        //For each of the nodes set the position
        for(unsigned n=0;n<n_node;n++)
         {
          //Get pointer to the node
          Node* nod_pt = local_element_pt->node_pt(n);
          //Get the relative position in local coordinates
          local_element_pt->local_fraction_of_node(n,s_fraction);
          //Loop over the coordinates and set the position
          for(unsigned i=0;i<2;i++)
           {
            nod_pt->x(i) = ll_corner[i] + el_length[i]*s_fraction[i];
           }
          //Add each node to the node list
          Node_pt.push_back(nod_pt);
         }
        //Now add the element to the list
        Element_pt.push_back(local_element_pt);
       }
     }
    //Now do the main bit of the mesh
    double llx = 0.6;
    double lly = 0.2;
    //loop over the elements in x
    for(unsigned ex=0;ex<Nx;ex++)
     {
      //loop over the element in y
      for(unsigned ey=0;ey<Ny;ey++)
       {
        //Create a new DG element
        ELEMENT* local_element_pt = new ELEMENT;
        //Find the number of nodes
        const unsigned n_node = local_element_pt->nnode();
        //Have we constructed
        bool constructed = false;
        //Right boundary
        if(ex==Nx-1)
         {
          const unsigned n_p  = local_element_pt->nnode_1d();
          boundary_info.resize(n_node);
          for(unsigned n=0;n<n_node;n++) {boundary_info[n] = false;}
          //The right-hand side is on a boundary
          for(unsigned n=0;n<n_p;n++)
           {
            boundary_info[n_p-1 + n*n_p] = true;
           }
          //Lower right
          if(ey==0)
           {
           for(unsigned n=0;n<n_p-1;n++) {boundary_info[n] = true;}
           }
          //Upper right
          if(ey==Ny-1)
           {
            for(unsigned n=0;n<n_p-1;n++)
             {boundary_info[n_p*(n_p-1) + n] = true;}
           }
          //Now construct
          local_element_pt->construct_boundary_nodes_and_faces(
           this, boundary_info, time_stepper_pt);
          constructed = true;
         }
        //Otherwise it's in the middle
        else
         {
          //If on the bottom or top
          if((ey==0) || (ey==Ny-1))
           {
            const unsigned n_p  = local_element_pt->nnode_1d();
            boundary_info.resize(n_node);
            for(unsigned n=0;n<n_node;n++) {boundary_info[n] = false;}
            //If the bottom
            if(ey==0)
             {
              for(unsigned n=0;n<n_p;n++)
               {
                boundary_info[n] = true;
               }
             }
            //If on the top
            if(ey==Ny-1)
             {
              for(unsigned n=0;n<n_p;n++)
               {boundary_info[n_p*(n_p-1) + n] = true;}
             }
            //Now construct
            local_element_pt->construct_boundary_nodes_and_faces(
             this, boundary_info, time_stepper_pt);
            constructed = true;
           }
         }
        //If we haven't already constructed
        if(!constructed)
         {
          //Construct nodes and faces
          local_element_pt->construct_nodes_and_faces(this,time_stepper_pt);
         }
        //Find the lower left corner of the element
        double ll_corner[2] = {llx + ex*el_length[0],lly + ey*el_length[1]};
        //For each of the nodes set the position
        for(unsigned n=0;n<n_node;n++)
         {
          //Get pointer to the node
          Node* nod_pt = local_element_pt->node_pt(n);
          //Get the relative position in local coordinates
          local_element_pt->local_fraction_of_node(n,s_fraction);
          //Loop over the coordinates and set the position
          for(unsigned i=0;i<2;i++)
           {
            nod_pt->x(i) = ll_corner[i] + el_length[i]*s_fraction[i];
           }
          //Add each node to the node list
          Node_pt.push_back(nod_pt);
         }
        //Now add the element to the list
        Element_pt.push_back(local_element_pt);
       }
     }
  //Set up the boundary nodes
  this->set_nboundary(4);
  //Now let's add the boundary nodes
  //Left-hand side
  for(unsigned e=0;e<Ny1;e++)
   {
    FiniteElement* const elem_pt = this->finite_element_pt(e);
    unsigned n_p = elem_pt->nnode_1d();
    for(unsigned n=0;n<n_p;n++)
     {
      this->add_boundary_node(3,elem_pt->node_pt(n_p*n));
     }
   }
  //Right hand side
  for(unsigned e=0;e<Ny;e++)
   {
    FiniteElement* const elem_pt =
     this->finite_element_pt(Ny1*Nx1 + Ny*(Nx-1)+e);
    unsigned n_p = elem_pt->nnode_1d();
    for(unsigned n=0;n<n_p;n++)
     {
      this->add_boundary_node(1,elem_pt->node_pt(n_p-1 + n_p*n));
     }
   }
  //Top
   {
    //First bit
    for(unsigned e=0;e<Nx1;e++)
     {
      FiniteElement* const elem_pt = this->finite_element_pt(Ny1-1 + Ny1*e);
      unsigned n_p = elem_pt->nnode_1d();
      for(unsigned n=0;n<n_p;n++)
       {
        this->add_boundary_node(2,elem_pt->node_pt((n_p-1)*n_p + n));
       }
      //Now add the reflecting element for the north face
      Face_element_pt[std::make_pair(elem_pt,0)] =
       new DGEulerFaceReflectionElement<ELEMENT>(elem_pt,2);
     }
    //Second bit
    for(unsigned e=0;e<Nx;e++)
     {
      FiniteElement* const elem_pt =
       this->finite_element_pt(Nx1*Ny1 + Ny-1 + Ny*e);
      unsigned n_p = elem_pt->nnode_1d();
      for(unsigned n=0;n<n_p;n++)
       {
        this->add_boundary_node(2,elem_pt->node_pt((n_p-1)*n_p + n));
       }
      //Now add the reflecting element for the north face
      Face_element_pt[std::make_pair(elem_pt,0)] =
       new DGEulerFaceReflectionElement<ELEMENT>(elem_pt,2);
     }
   }
  //Bottom
   {
    //First bit
    for(unsigned e=0;e<Nx1;e++)
     {
      //Bottom
      FiniteElement* const elem_pt = this->finite_element_pt(Ny1*e);
      unsigned n_p = elem_pt->nnode_1d();
      for(unsigned n=0;n<n_p;n++)
       {
        this->add_boundary_node(0,elem_pt->node_pt(n));
       }
       //Now add the reflecting element for the south face
      Face_element_pt[std::make_pair(elem_pt,2)] =
       new DGEulerFaceReflectionElement<ELEMENT>(elem_pt,-2);
     }
    //Add the right-hand of the lower elements
    for(unsigned e=0;e<n_y;e++)
     {
      FiniteElement* const elem_pt = this->finite_element_pt(Ny1*(Nx1-1) + e);
      unsigned n_p = elem_pt->nnode_1d();
      for(unsigned n=0;n<n_p;n++)
       {
        this->add_boundary_node(0,elem_pt->node_pt(n_p-1 + n_p*n));
       }
        //Now add the reflecting element for the east face
      Face_element_pt[std::make_pair(elem_pt,1)] =
       new DGEulerFaceReflectionElement<ELEMENT>(elem_pt,1);
     }
    //Second bit
    for(unsigned e=0;e<Nx;e++)
     {
      //Bottom
      FiniteElement* const elem_pt =
       this->finite_element_pt(Nx1*Ny1  + Ny*e);
      unsigned n_p = elem_pt->nnode_1d();
      for(unsigned n=0;n<n_p;n++)
       {
        this->add_boundary_node(0,elem_pt->node_pt(n));
       }
       //Now add the reflecting element for the south face
      Face_element_pt[std::make_pair(elem_pt,2)] =
       new DGEulerFaceReflectionElement<ELEMENT>(elem_pt,-2);
     }
   }
   /* for(unsigned b=0;b<4;b++)
     {
      std::cout << "Boundary : " << b << "\n";
      unsigned nbound = this->nboundary_node(b);
      for(unsigned n=0;n<nbound;n++)
       {
        std::cout << "( " << this->boundary_node_pt(b,n)->x(0) << ", "
                  << this->boundary_node_pt(b,n)->x(1) << ")\n";
       }
       }*/
   //How many faces have we constructed
   std::cout << Face_element_pt.size() << "\n";
    //Now loop over all the elements and set up the neighbour map
   for(unsigned ex=0;ex<Nx;ex++)
    {
     for(unsigned ey=0;ey<Ny;ey++)
      {
       //Get pointer to the element
       unsigned element_index = Nx1*Ny1  + ex*Ny + ey;
       FiniteElement* local_el_pt = finite_element_pt(element_index);
       //Storage for indices of neighbours
       int index[4];
       //North neighbour (just one up)
       if(ey < (Ny-1)) {index[0] = element_index + 1;}
       //If at top (no neighbour)
       else {index[0] = -1;}
        //East neighbour (just one across)
        if(ex < (Nx-1)) {index[1] = element_index + Ny;}
        //If at side (no neighbour)
        else {index[1] = -1;}
        //South neighbour
        if(ey > 0) {index[2] = element_index - 1;}
        else {index[2] = -1;}
        //West neighbour
        /*if(ex > 0)*/ {index[3] = element_index - Ny;}
        //else {index[3] = -1;}
        //Now store the details in the mape
        for(unsigned i=0;i<4;i++)
         {
           if(index[i] != -1)
            {
             Neighbour_map[std::make_pair(local_el_pt,i)] =
              finite_element_pt(index[i]);
            }
         }
       }
     }
   //Now sort out the maps for the first bit
   for(unsigned ex=0;ex<Nx1;ex++)
    {
     for(unsigned ey=0;ey<Ny1;ey++)
      {
       //Get pointer to the element
       unsigned element_index = ex*Ny1 + ey;
       FiniteElement* local_el_pt = finite_element_pt(element_index);
       //Storage for indices of neighbours
       int index[4];
       //North neighbour (just one up)
       if(ey < (Ny1-1)) {index[0] = element_index + 1;}
       //If at top (no neighbour)
       else {index[0] = -1;}
        //East neighbour (just one across)
        if(ex < (Nx1-1)) {index[1] = element_index + Ny1;}
        //If at side (no neighbour)
        else
         {
          if(ey >= n_y) {index[1] = element_index + Ny;}
          else {index[1] = -1;}
         }
        //South neighbour
        if(ey > 0) {index[2] = element_index - 1;}
        else {index[2] = -1;}
        //West neighbour
        if(ex > 0) {index[3] = element_index - Ny1;}
        else {index[3] = -1;}
        //Now store the details in the mape
        for(unsigned i=0;i<4;i++)
         {
          if(index[i] != -1)
           {
            Neighbour_map[std::make_pair(local_el_pt,i)] =
             finite_element_pt(index[i]);
           }
         }
       }
     }
  //Now set up the neighbour information
  /*const unsigned n_element = this->nelement();
  for(unsigned e=0;e<n_element;e++)
   {
    dynamic_cast<ELEMENT*>(this->element_pt(e))->setup_face_neighbour_info();
    }*/
   this->setup_face_neighbour_info();
 }
References e(), i, Global_Parameters::Lx, Global_Parameters::Ly, n, oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::node_pt(), GlobalParameters::Nx, GlobalParameters::Ny, and oomph::Node::x().
TwoDDGMesh() [4/5]
template<class ELEMENT > TwoDDGMesh< ELEMENT >::TwoDDGMesh (const unsigned & Nx, const unsigned & Ny, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
   {
    Vector<double> s_fraction;
    //Lengths of the mesh
    double Lx = 1.0;
    double Ly = 1.0;
    double llx = -0.5;
    double lly = 0.0;
    //Angle (in degrees of ramp)
    double theta = 10.0;
    const double pi = MathematicalConstants::Pi;
    //Work out the length of each element in the x and y directions
    //(Assuming uniform spacing)
    double el_length[2] = {Lx/(double)Nx, Ly/(double)Ny};
    //Vector of booleans for boundary information
    std::vector<bool> boundary_info;
    //loop over the elements in x
    for(unsigned ex=0;ex<Nx;ex++)
     {
      //loop over the element in y
      for(unsigned ey=0;ey<Ny;ey++)
       {
        //Create a new DG element
        ELEMENT* local_element_pt = new ELEMENT;
        //Find the number of nodes
        const unsigned n_node = local_element_pt->nnode();
        //Have we constructed
        bool constructed = false;
        //If we are on a boundary
        if(ex==0)
         {
          const unsigned n_p  = local_element_pt->nnode_1d();
          boundary_info.resize(n_node);
          for(unsigned n=0;n<n_node;n++) {boundary_info[n] = false;}
          //The left hand side is on a boundary
          for(unsigned n=0;n<n_p;n++)
           {
            boundary_info[n*n_p] = true;
           }
          //Lower left
          if(ey==0)
           {
           for(unsigned n=1;n<n_p;n++) {boundary_info[n] = true;}
           }
          //Upper left
          if(ey==Ny-1)
           {
            for(unsigned n=1;n<n_p;n++) {boundary_info[n_p*(n_p-1) + n] = true;}
           }
          //Now construct
          local_element_pt->construct_boundary_nodes_and_faces(
           this, boundary_info, time_stepper_pt);
          constructed = true;
         }
        //Right boundary
        else if(ex==Nx-1)
         {
          const unsigned n_p  = local_element_pt->nnode_1d();
          boundary_info.resize(n_node);
          for(unsigned n=0;n<n_node;n++) {boundary_info[n] = false;}
          //The right-hand side is on a boundary
          for(unsigned n=0;n<n_p;n++)
           {
            boundary_info[n_p-1 + n*n_p] = true;
           }
          //Lower right
          if(ey==0)
           {
           for(unsigned n=0;n<n_p-1;n++) {boundary_info[n] = true;}
           }
          //Upper right
          if(ey==Ny-1)
           {
            for(unsigned n=0;n<n_p-1;n++)
             {boundary_info[n_p*(n_p-1) + n] = true;}
           }
          //Now construct
          local_element_pt->construct_boundary_nodes_and_faces(
           this, boundary_info, time_stepper_pt);
          constructed = true;
         }
        //Otherwise it's in the middle
        else
         {
          //If on the bottom or top
          if((ey==0) || (ey==Ny-1))
           {
            const unsigned n_p  = local_element_pt->nnode_1d();
            boundary_info.resize(n_node);
            for(unsigned n=0;n<n_node;n++) {boundary_info[n] = false;}
            //If the bottom
            if(ey==0)
             {
              for(unsigned n=0;n<n_p;n++)
               {
                boundary_info[n] = true;
               }
             }
            //If on the top
            if(ey==Ny-1)
             {
              for(unsigned n=0;n<n_p;n++)
               {boundary_info[n_p*(n_p-1) + n] = true;}
             }
            //Now construct
            local_element_pt->construct_boundary_nodes_and_faces(
             this, boundary_info, time_stepper_pt);
            constructed = true;
           }
         }
        //If we haven't already constructed
        if(!constructed)
         {
          //Construct nodes and faces
          local_element_pt->construct_nodes_and_faces(this,time_stepper_pt);
         }
        //Find the lower left corner of the element
        double ll_corner[2] = {llx + ex*el_length[0],lly + ey*el_length[1]};
        //For each of the nodes set the position
        for(unsigned n=0;n<n_node;n++)
         {
          //Get pointer to the node
          Node* nod_pt = local_element_pt->node_pt(n);
          //Get the relative position in local coordinates
          local_element_pt->local_fraction_of_node(n,s_fraction);
          //Loop over the coordinates and set the position
          for(unsigned i=0;i<2;i++)
           {
            nod_pt->x(i) = ll_corner[i] + el_length[i]*s_fraction[i];
           }
          //Add the ramp part
          if(nod_pt->x(0) >= 0.0)
           {
            //Work out position of ramp
            double y_min = nod_pt->x(0)*tan(theta*pi/180.0);
            //Now rescale the height
            double frac = nod_pt->x(1)*(Ly-y_min)/Ly;
            //And add it
            nod_pt->x(1) = y_min + frac;
           }
          //Add each node to the node list
          Node_pt.push_back(nod_pt);
         }
        //Now add the element to the list
        Element_pt.push_back(local_element_pt);
       }
     }
    //Set up the boundary nodes
    this->set_nboundary(4);
    //Now let's add the boundary nodes
    //Left-hand and right-hand sides
    for(unsigned e=0;e<Ny;e++)
     {
      //Left
      FiniteElement* elem_pt = this->finite_element_pt(e);
      unsigned n_p = elem_pt->nnode_1d();
      for(unsigned n=0;n<n_p;n++)
       {
        this->add_boundary_node(3,elem_pt->node_pt(n_p*n));
       }
      //Right
      elem_pt = this->finite_element_pt(Ny*(Nx-1)+e);
      n_p = elem_pt->nnode_1d();
      for(unsigned n=0;n<n_p;n++)
       {
        this->add_boundary_node(1,elem_pt->node_pt(n_p-1 + n_p*n));
       }
     }
    //Top and bottom
    for(unsigned e=0;e<Nx;e++)
     {
      //Bottom
      FiniteElement* elem_pt = this->finite_element_pt(Ny*e);
      unsigned n_p = elem_pt->nnode_1d();
      for(unsigned n=0;n<n_p;n++)
       {
        this->add_boundary_node(0,elem_pt->node_pt(n));
       }
      //Now add the reflecting element for the south face
      Face_element_pt[std::make_pair(elem_pt,2)] =
       new DGEulerFaceReflectionElement<ELEMENT>(elem_pt,-2);
      //Top
      elem_pt = this->finite_element_pt(Ny-1 + Ny*e);
      n_p = elem_pt->nnode_1d();
      for(unsigned n=0;n<n_p;n++)
       {
        this->add_boundary_node(2,elem_pt->node_pt((n_p-1)*n_p + n));
       }
     }
    //Now loop over all the elements and set up the neighbour map
    for(unsigned ex=0;ex<Nx;ex++)
     {
      for(unsigned ey=0;ey<Ny;ey++)
       {
        //Get pointer to the element
        unsigned element_index = ex*Ny + ey;
        FiniteElement* local_el_pt = finite_element_pt(element_index);
        //Storage for indices of neighbours
        int index[4];
        //North neighbour (just one up)
        if(ey < (Ny-1)) {index[0] = element_index + 1;}
        //If at top, no neighbour
        else {index[0] = -1;}
        //East neighbour (just one across)
        if(ex < (Nx-1)) {index[1] = element_index + Ny;}
        //If at side no neighbour
        else {index[1] = -1;}
        //South neighbour
        if(ey > 0) {index[2] = element_index - 1;}
        else {index[2] = -1;}
        //West neighbour
        if(ex > 0) {index[3] = element_index - Ny;}
        else {index[3] = -1;}
        //Now store the details in the mape
        for(unsigned i=0;i<4;i++)
         {
          if(index[i]!=-1)
           {
            Neighbour_map[std::make_pair(local_el_pt,i)] =
             finite_element_pt(index[i]);
           }
         }
        }
     }
    //Now set up the neighbour information
    /*const unsigned n_element = this->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      dynamic_cast<ELEMENT*>(this->element_pt(e))->setup_face_neighbour_info();
      }*/
    this->setup_face_neighbour_info();
   }
References e(), i, Global_Parameters::Lx, Global_Parameters::Ly, n, oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::node_pt(), GlobalParameters::Nx, GlobalParameters::Ny, constants::pi, oomph::MathematicalConstants::Pi, Eigen::bfloat16_impl::tan(), BiharmonicTestFunctions2::theta, and oomph::Node::x().
TwoDDGMesh() [5/5]
template<class ELEMENT > TwoDDGMesh< ELEMENT >::TwoDDGMesh (const unsigned & Nx, const unsigned & Ny, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
   {
    Vector<double> s_fraction;
    //Lengths of the mesh
    double Lx = 10.0;
    double Ly = 10.0;
    double llx = -5.0;
    double lly = -5.0;
    //Work out the length of each element in the x and y directions
    //(Assuming uniform spacing)
    double el_length[2] = {Lx/(double)Nx, Ly/(double)Ny};
    //Vector of booleans for boundary information
    std::vector<bool> boundary_info;
    //loop over the elements in x
    for(unsigned ex=0;ex<Nx;ex++)
     {
      //loop over the element in y
      for(unsigned ey=0;ey<Ny;ey++)
       {
        //Create a new DG element
        ELEMENT* local_element_pt = new ELEMENT;
        //Find the number of nodes
        const unsigned n_node = local_element_pt->nnode();
        //Have we constructed
        bool constructed = false;
        //If we are on a boundary
        if(ex==0)
         {
          const unsigned n_p  = local_element_pt->nnode_1d();
          boundary_info.resize(n_node);
          for(unsigned n=0;n<n_node;n++) {boundary_info[n] = false;}
          //The left hand side is on a boundary
          for(unsigned n=0;n<n_p;n++)
           {
            boundary_info[n*n_p] = true;
           }
          //Lower left
          if(ey==0)
           {
           for(unsigned n=1;n<n_p;n++) {boundary_info[n] = true;}
           }
          //Upper left
          if(ey==Ny-1)
           {
            for(unsigned n=1;n<n_p;n++) {boundary_info[n_p*(n_p-1) + n] = true;}
           }
          //Now construct
          local_element_pt->construct_boundary_nodes_and_faces(
           this, boundary_info, time_stepper_pt);
          constructed = true;
         }
        //Right boundary
        else if(ex==Nx-1)
         {
          const unsigned n_p  = local_element_pt->nnode_1d();
          boundary_info.resize(n_node);
          for(unsigned n=0;n<n_node;n++) {boundary_info[n] = false;}
          //The right-hand side is on a boundary
          for(unsigned n=0;n<n_p;n++)
           {
            boundary_info[n_p-1 + n*n_p] = true;
           }
          //Lower right
          if(ey==0)
           {
           for(unsigned n=0;n<n_p-1;n++) {boundary_info[n] = true;}
           }
          //Upper right
          if(ey==Ny-1)
           {
            for(unsigned n=0;n<n_p-1;n++)
             {boundary_info[n_p*(n_p-1) + n] = true;}
           }
          //Now construct
          local_element_pt->construct_boundary_nodes_and_faces(
           this, boundary_info, time_stepper_pt);
          constructed = true;
         }
        //Otherwise it's in the middle
        else
         {
          //If on the bottom or top
          if((ey==0) || (ey==Ny-1))
           {
            const unsigned n_p  = local_element_pt->nnode_1d();
            boundary_info.resize(n_node);
            for(unsigned n=0;n<n_node;n++) {boundary_info[n] = false;}
            //If the bottom
            if(ey==0)
             {
              for(unsigned n=0;n<n_p;n++)
               {
                boundary_info[n] = true;
               }
             }
            //If on the top
            if(ey==Ny-1)
             {
              for(unsigned n=0;n<n_p;n++)
               {boundary_info[n_p*(n_p-1) + n] = true;}
             }
            //Now construct
            local_element_pt->construct_boundary_nodes_and_faces(
             this, boundary_info, time_stepper_pt);
            constructed = true;
           }
         }
        //If we haven't already constructed
        if(!constructed)
         {
          //Construct nodes and faces
          local_element_pt->construct_nodes_and_faces(this,time_stepper_pt);
         }
        //Find the lower left corner of the element
        double ll_corner[2] = {llx + ex*el_length[0],lly + ey*el_length[1]};
        //For each of the nodes set the position
        for(unsigned n=0;n<n_node;n++)
         {
          //Get pointer to the node
          Node* nod_pt = local_element_pt->node_pt(n);
          //Get the relative position in local coordinates
          local_element_pt->local_fraction_of_node(n,s_fraction);
          //Loop over the coordinates and set the position
          for(unsigned i=0;i<2;i++)
           {
            nod_pt->x(i) = ll_corner[i] + el_length[i]*s_fraction[i];
           }
          //Now set the value
          nod_pt->set_value(0,1.0);
          //Add each node to the node list
          Node_pt.push_back(nod_pt);
         }
        //Now add the element to the list
        Element_pt.push_back(local_element_pt);
       }
     }
    //Set up the boundary nodes
    this->set_nboundary(4);
    //Now let's add the boundary nodes
    //Left-hand and right-hand sides
    for(unsigned e=0;e<Ny;e++)
     {
      //Left
      FiniteElement* elem_pt = this->finite_element_pt(e);
      unsigned n_p = elem_pt->nnode_1d();
      for(unsigned n=0;n<n_p;n++)
       {
        this->add_boundary_node(3,elem_pt->node_pt(n_p*n));
       }
      //Right
      elem_pt = this->finite_element_pt(Ny*(Nx-1)+e);
      n_p = elem_pt->nnode_1d();
      for(unsigned n=0;n<n_p;n++)
       {
        this->add_boundary_node(1,elem_pt->node_pt(n_p-1 + n_p*n));
       }
     }
    //Top and bottom
    for(unsigned e=0;e<Nx;e++)
     {
      //Bottom
      FiniteElement* elem_pt = this->finite_element_pt(Ny*e);
      unsigned n_p = elem_pt->nnode_1d();
      for(unsigned n=0;n<n_p;n++)
       {
        this->add_boundary_node(0,elem_pt->node_pt(n));
       }
      //Top
      elem_pt = this->finite_element_pt(Ny-1 + Ny*e);
      n_p = elem_pt->nnode_1d();
      for(unsigned n=0;n<n_p;n++)
       {
        this->add_boundary_node(2,elem_pt->node_pt((n_p-1)*n_p + n));
       }
     }
    //Now loop over all the elements and set up the neighbour map
    for(unsigned ex=0;ex<Nx;ex++)
     {
      for(unsigned ey=0;ey<Ny;ey++)
       {
        //Get pointer to the element
        unsigned element_index = ex*Ny + ey;
        FiniteElement* local_el_pt = finite_element_pt(element_index);
        //Storage for indices of neighbours
        unsigned index[4];
        //North neighbour (just one up)
        if(ey < (Ny-1)) {index[0] = element_index + 1;}
        //If at top, return index at bottom (periodic conditions)
        else {index[0] = ex*Ny;}
        //East neighbour (just one across)
        if(ex < (Nx-1)) {index[1] = element_index + Ny;}
        //If at side return index at other side (periodic conditions)
        else {index[1] = ey;}
        //South neighbour
        if(ey > 0) {index[2] = element_index - 1;}
        else {index[2] = element_index + Ny-1;}
        //West neighbour
        if(ex > 0) {index[3] = element_index - Ny;}
        else {index[3] = element_index + (Nx-1)*Ny;}
        //Now store the details in the mape
        for(unsigned i=0;i<4;i++)
         {
          Neighbour_map[std::make_pair(local_el_pt,i)] =
           finite_element_pt(index[i]);
         }
       }
     }
    //Now set up the neighbour information
    this->setup_face_neighbour_info();
   }
References e(), i, Global_Parameters::Lx, Global_Parameters::Ly, n, oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::node_pt(), GlobalParameters::Nx, GlobalParameters::Ny, oomph::Data::set_value(), and oomph::Node::x().
Member Function Documentation
neighbour_finder() [1/5]
template<class ELEMENT > void TwoDDGMesh< ELEMENT >::neighbour_finder (FiniteElement *const & bulk_element_pt, const int & face_index, const Vector< double > & s_bulk, FaceElement *& face_element_pt, Vector< double > & s_face) inline virtual
Reimplemented from oomph::DGMesh.
   {
    //We have a single face coordinate of size 1
    s_face.resize(1);
    //Now things differ depending upon which face we are located
    switch(face_index)
     {
      //North face
     case 2:
      //The neighbouring face element is the south face of the neighbour
      face_element_pt =
       dynamic_cast<ELEMENT*>(
        Neighbour_map[std::make_pair(bulk_element_pt,0)])->
       face_element_pt(2);
      //Then set the face coordinate
      s_face[0] = s_bulk[0];
      break;
      //East face
     case 1:
      //The neighbouring face element is the west faec of the neighbour
      face_element_pt =
       dynamic_cast<ELEMENT*>(
        Neighbour_map[std::make_pair(bulk_element_pt,1)])->
       face_element_pt(3);
      //Then set the face coordinate
      s_face[0] = s_bulk[1];
      break;
      //South face
     case -2:
      //the neighbouring face element is the north face of the neighbour
      face_element_pt =
       dynamic_cast<ELEMENT*>(
        Neighbour_map[std::make_pair(bulk_element_pt,2)])
       ->face_element_pt(0);
      //Then set the face coordiante
      s_face[0] = s_bulk[0];
      break;
      //West face
     case -1:
      //The neighbouring face element is the east face of the neighbour
      face_element_pt =
       dynamic_cast<ELEMENT*>
       (Neighbour_map[std::make_pair(bulk_element_pt,3)])->
       face_element_pt(1);
      s_face[0] = s_bulk[1];
      break;
     default:
    throw OomphLibError("Coordinate is on no face or not on a unique face",
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
    break;
  }
   }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
neighbour_finder() [2/5]
template<class ELEMENT > void TwoDDGMesh< ELEMENT >::neighbour_finder (FiniteElement *const & bulk_element_pt, const int & face_index, const Vector< double > & s_bulk, FaceElement *& face_element_pt, Vector< double > & s_face) inline virtual
Reimplemented from oomph::DGMesh.
   {
    //We have a single face coordinate of size 1
    s_face.resize(1);
    //Now things differ depending upon which face we are located
    switch(face_index)
     {
      //North face
     case 2:
      //The neighbouring face element is the south face of the neighbour
      face_element_pt =
       dynamic_cast<ELEMENT*>(
        Neighbour_map[std::make_pair(bulk_element_pt,0)])->
       face_element_pt(2);
      //Then set the face coordinate
      s_face[0] = s_bulk[0];
      break;
      //East face
     case 1:
      //The neighbouring face element is the west faec of the neighbour
      face_element_pt =
       dynamic_cast<ELEMENT*>(
        Neighbour_map[std::make_pair(bulk_element_pt,1)])->
       face_element_pt(3);
      //Then set the face coordinate
      s_face[0] = s_bulk[1];
      break;
      //South face
     case -2:
      //the neighbouring face element is the north face of the neighbour
      face_element_pt =
       dynamic_cast<ELEMENT*>(
        Neighbour_map[std::make_pair(bulk_element_pt,2)])
       ->face_element_pt(0);
      //Then set the face coordiante
      s_face[0] = s_bulk[0];
      break;
      //West face
     case -1:
      //The neighbouring face element is the east face of the neighbour
      face_element_pt =
       dynamic_cast<ELEMENT*>
       (Neighbour_map[std::make_pair(bulk_element_pt,3)])->
       face_element_pt(1);
      s_face[0] = s_bulk[1];
      break;
     default:
    throw OomphLibError("Coordinate is on no face or not on a unique face",
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
    break;
  }
   }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
neighbour_finder() [3/5]
template<class ELEMENT > void TwoDDGMesh< ELEMENT >::neighbour_finder (FiniteElement *const & bulk_element_pt, const int & face_index, const Vector< double > & s_bulk, FaceElement *& face_element_pt, Vector< double > & s_face) inline virtual
Reimplemented from oomph::DGMesh.
   {
    //We have a single face coordinate of size 1
    s_face.resize(1);
    ELEMENT* elem_pt=0;
    //Now things differ depending upon which face we are located
    switch(face_index)
     {
      //North face
     case 2:
      //Get the neighbour
      elem_pt = dynamic_cast<ELEMENT*>(
       Neighbour_map[std::make_pair(bulk_element_pt,0)]);
      if(elem_pt!=0)
       {
        //The neighbouring face element is the south face of the neighbour
        face_element_pt = elem_pt->face_element_pt(2);
       }
      //Otherwise we build in the face reflection element
      else
       {
        /*face_element_pt = new DGEulerFaceReflectionElement<ELEMENT>(
         bulk_element_pt,2);
         Face_element_pt.push_back(face_element_pt);*/
        //dynamic_cast<ELEMENT*>(bulk_element_pt)->face_element_pt(0);
        face_element_pt = Face_element_pt[std::make_pair(bulk_element_pt,0)];
        if(face_element_pt==0)
         {
          throw OomphLibError("Something wrong",
                              OOMPH_CURRENT_FUNCTION,
                              OOMPH_EXCEPTION_LOCATION);
         }
       }
      //Then set the face coordinate
      s_face[0] = s_bulk[0];
      break;
      //East face
     case 1:
       //Get the neighbour
      elem_pt = dynamic_cast<ELEMENT*>(
       Neighbour_map[std::make_pair(bulk_element_pt,1)]);
      //The neighbouring face element is the west faec of the neighbour
      if(elem_pt!=0)
       {
        face_element_pt = elem_pt->face_element_pt(3);
       }
      else
       {
        ELEMENT* cast_bulk_element_pt = dynamic_cast<ELEMENT*>(bulk_element_pt);
        //If we're on the outlet set the face to be the face
        if(cast_bulk_element_pt->face_element_pt(1)->node_pt(0)->
           is_on_boundary(1))
         {
          //std::cout << cast_bulk_element_pt->face_element_pt(1)->node_pt(0)->x(0) << " "
          //          << cast_bulk_element_pt->face_element_pt(1)->node_pt(0)->x(1) << "\n ";
          face_element_pt =
           dynamic_cast<ELEMENT*>(bulk_element_pt)->face_element_pt(1);
         }
        //Otherwise we must be on the corner
        else
         {
          //face_element_pt = new DGEulerFaceReflectionElement<ELEMENT>(
          // bulk_element_pt,1);
          //Face_element_pt.push_back(face_element_pt);
          face_element_pt = Face_element_pt[std::make_pair(bulk_element_pt,1)];
          if(face_element_pt==0)
           {
            throw OomphLibError("Something wrong",
                                OOMPH_CURRENT_FUNCTION,
                                OOMPH_EXCEPTION_LOCATION);
           }
         }
       }
      //Then set the face coordinate
      s_face[0] = s_bulk[1];
      break;
      //South face
     case -2:
       //Get the neighbour
      elem_pt = dynamic_cast<ELEMENT*>(
       Neighbour_map[std::make_pair(bulk_element_pt,2)]);
      //the neighbouring face element is the north face of the neighbour
      if(elem_pt!=0)
       {
        face_element_pt = elem_pt->face_element_pt(0);
       }
      else
       {
        //Build in the face reflection element
        //face_element_pt = new DGEulerFaceReflectionElement<ELEMENT>(
        // bulk_element_pt,-2);
        //Face_element_pt.push_back(face_element_pt);
        //face_element_pt =
        // dynamic_cast<ELEMENT*>(bulk_element_pt)->face_element_pt(2);
        face_element_pt = Face_element_pt[std::make_pair(bulk_element_pt,2)];
         if(face_element_pt==0)
         {
          throw OomphLibError("Something wrong",
                              OOMPH_CURRENT_FUNCTION,
                              OOMPH_EXCEPTION_LOCATION);
         }
       }
      //Then set the face coordiante
      s_face[0] = s_bulk[0];
      break;
      //West face
     case -1:
       //Get the neighbour
      elem_pt = dynamic_cast<ELEMENT*>(
       Neighbour_map[std::make_pair(bulk_element_pt,3)]);
      //The neighbouring face element is the east face of the neighbour
      if(elem_pt!=0)
       {
        face_element_pt = elem_pt->face_element_pt(1);
       }
      else
       {
        face_element_pt =
         dynamic_cast<ELEMENT*>(bulk_element_pt)->face_element_pt(3);
       }
      s_face[0] = s_bulk[1];
      break;
     default:
    throw OomphLibError("Coordinate is on no face or not on a unique face",
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
    break;
  }
   }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
neighbour_finder() [4/5]
template<class ELEMENT > void TwoDDGMesh< ELEMENT >::neighbour_finder (FiniteElement *const & bulk_element_pt, const int & face_index, const Vector< double > & s_bulk, FaceElement *& face_element_pt, Vector< double > & s_face) inline virtual
Reimplemented from oomph::DGMesh.
   {
    //We have a single face coordinate of size 1
    s_face.resize(1);
    ELEMENT* elem_pt = 0;
    //Now things differ depending upon which face we are located
    switch(face_index)
     {
      //North face
     case 2:
      //Get the neighbour
      elem_pt =  dynamic_cast<ELEMENT*>(
       Neighbour_map[std::make_pair(bulk_element_pt,0)]);
      if(elem_pt!=0)
       {
        //The neighbouring face element is the south face of the neighbour
        face_element_pt = elem_pt->face_element_pt(2);
       }
      //Otherwise free outflow
      else
       {
        face_element_pt =
         dynamic_cast<ELEMENT*>(bulk_element_pt)->face_element_pt(0);
       }
        //Then set the face coordinate
        s_face[0] = s_bulk[0];
        break;
      //East face
     case 1:
      //Get the neighbour
      elem_pt =
       dynamic_cast<ELEMENT*>(
        Neighbour_map[std::make_pair(bulk_element_pt,1)]);
      if(elem_pt!=0)
       {
        face_element_pt = elem_pt->face_element_pt(3);
       }
      else
       {
        face_element_pt =
         dynamic_cast<ELEMENT*>(bulk_element_pt)->face_element_pt(1);
       }
      //Then set the face coordinate
      s_face[0] = s_bulk[1];
      break;
      //South face
     case -2:
      //Get the neighbour
      elem_pt =
       dynamic_cast<ELEMENT*>(
        Neighbour_map[std::make_pair(bulk_element_pt,2)]);
      if(elem_pt!=0)
       {
        face_element_pt = elem_pt->face_element_pt(0);
       }
      //Otherwise use reflection element
      else
       {
        face_element_pt = Face_element_pt[std::make_pair(bulk_element_pt,2)];
        if(face_element_pt==0)
         {
          throw OomphLibError("Something wrong",
                              OOMPH_CURRENT_FUNCTION,
                              OOMPH_EXCEPTION_LOCATION);
                              }
       }
      //Then set the face coordiante
      s_face[0] = s_bulk[0];
      break;
      //West face
     case -1:
      //Get the neighbour
      elem_pt  =
       dynamic_cast<ELEMENT*>
       (Neighbour_map[std::make_pair(bulk_element_pt,3)]);
      if(elem_pt!=0)
       {
        face_element_pt = elem_pt->face_element_pt(1);
       }
      else
       {
        face_element_pt = dynamic_cast<ELEMENT*>(bulk_element_pt)
         ->face_element_pt(3);
       }
      s_face[0] = s_bulk[1];
      break;
     default:
    throw OomphLibError("Coordinate is on no face or not on a unique face",
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
    break;
     }
   }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
neighbour_finder() [5/5]
template<class ELEMENT > void TwoDDGMesh< ELEMENT >::neighbour_finder (FiniteElement *const & bulk_element_pt, const int & face_index, const Vector< double > & s_bulk, FaceElement *& face_element_pt, Vector< double > & s_face) inline virtual
Reimplemented from oomph::DGMesh.
   {
    //We have a single face coordinate of size 1
    s_face.resize(1);
    //Now things differ depending upon which face we are located
    switch(face_index)
     {
      //North face
     case 2:
      //The neighbouring face element is the south face of the neighbour
      face_element_pt =
       dynamic_cast<ELEMENT*>(
        Neighbour_map[std::make_pair(bulk_element_pt,0)])->
       face_element_pt(2);
      //Then set the face coordinate
      s_face[0] = s_bulk[0];
      break;
      //East face
     case 1:
      //The neighbouring face element is the west faec of the neighbour
      face_element_pt =
       dynamic_cast<ELEMENT*>(
        Neighbour_map[std::make_pair(bulk_element_pt,1)])->
       face_element_pt(3);
      //Then set the face coordinate
      s_face[0] = s_bulk[1];
      break;
      //South face
     case -2:
      //the neighbouring face element is the north face of the neighbour
      face_element_pt =
       dynamic_cast<ELEMENT*>(
        Neighbour_map[std::make_pair(bulk_element_pt,2)])
       ->face_element_pt(0);
      //Then set the face coordiante
      s_face[0] = s_bulk[0];
      break;
      //West face
     case -1:
      //The neighbouring face element is the east face of the neighbour
      face_element_pt =
       dynamic_cast<ELEMENT*>
       (Neighbour_map[std::make_pair(bulk_element_pt,3)])->
       face_element_pt(1);
      s_face[0] = s_bulk[1];
      break;
     default:
    throw OomphLibError("Coordinate is on no face or not on a unique face",
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
    break;
  }
   }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Member Data Documentation
Face_element_pt
template<class ELEMENT > std::map< std::pair< FiniteElement *, int >, FaceElement * > TwoDDGMesh< ELEMENT >::Face_element_pt private
Neighbour_map [1/2]
template<class ELEMENT > std::map< std::pair< FiniteElement *, unsigned >, FiniteElement * > TwoDDGMesh< ELEMENT >::Neighbour_map private
Neighbour_map [2/2]
template<class ELEMENT > std::map<std::pair<FiniteElement*,int>,FiniteElement*> TwoDDGMesh< ELEMENT >::Neighbour_map private
The documentation for this class was generated from the following files:
two_d_advection.cc
couette.cc
ff_step.cc
ramp.cc
two_d_euler.cc