MercuryDPM: oomph::DistributableLinearAlgebraObject Class Reference
oomph::DistributableLinearAlgebraObject Class Reference
#include <linear_algebra_distribution.h>
Public Member Functions
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
void build_distribution (const LinearAlgebraDistribution &dist)
Protected Member Functions
void clear_distribution ()
Private Attributes
LinearAlgebraDistribution * Distribution_pt
the LinearAlgebraDistribution object
Detailed Description
Base class for any linear algebra object that is distributable. Just contains storage for the LinearAlgebraDistribution object and access functions
Constructor & Destructor Documentation
DistributableLinearAlgebraObject() [1/2]
oomph::DistributableLinearAlgebraObject::DistributableLinearAlgebraObject () inline
Default constructor - create a distribution.
     {
       Distribution_pt = new LinearAlgebraDistribution;
     }
References Distribution_pt.
DistributableLinearAlgebraObject() [2/2]
oomph::DistributableLinearAlgebraObject::DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject & matrix) delete
Broken copy constructor.
~DistributableLinearAlgebraObject()
virtual oomph::DistributableLinearAlgebraObject::~DistributableLinearAlgebraObject () inline virtual
Destructor.
     {
       delete Distribution_pt;
     }
References Distribution_pt.
Member Function Documentation
build_distribution() [1/2]
void oomph::DistributableLinearAlgebraObject::build_distribution (const LinearAlgebraDistribution & dist) inline
setup the distribution of this distributable linear algebra object
     {
       Distribution_pt->build(dist);
     }
References oomph::LinearAlgebraDistribution::build(), and Distribution_pt.
build_distribution() [2/2]
void oomph::DistributableLinearAlgebraObject::build_distribution (const LinearAlgebraDistribution *const dist_pt) inline
setup the distribution of this distributable linear algebra object
     {
       Distribution_pt->build(dist_pt);
     }
References oomph::LinearAlgebraDistribution::build(), and Distribution_pt.
Referenced by oomph::DoubleVector::build(), oomph::CRDoubleMatrix::build(), oomph::DoubleMultiVector::build(), oomph::CRDoubleMatrix::CRDoubleMatrix(), oomph::MumpsSolver::factorise(), oomph::DoubleMultiVector::redistribute(), oomph::DoubleVector::redistribute(), oomph::AugmentedBlockPitchForkLinearSolver::resolve(), oomph::DoubleVector::set_external_values(), oomph::MatrixBasedDiagPreconditioner::setup(), oomph::ILUZeroPreconditioner< CCDoubleMatrix >::setup(), oomph::ILUZeroPreconditioner< CRDoubleMatrix >::setup(), oomph::InnerIterationPreconditioner< SOLVER, PRECONDITIONER >::setup(), oomph::HyprePreconditioner::setup(), oomph::NewMumpsPreconditioner::setup(), oomph::IdentityPreconditioner::setup(), oomph::SuperLUPreconditioner::setup(), oomph::TrilinosPreconditionerBase::setup(), oomph::MatrixVectorProduct::setup(), oomph::DoubleMultiVector::shallow_build(), oomph::DenseLU::solve(), oomph::MumpsSolver::solve(), oomph::HypreSolver::solve(), oomph::CG< MATRIX >::solve(), oomph::BiCGStab< MATRIX >::solve(), oomph::GS< MATRIX >::solve(), oomph::DampedJacobi< MATRIX >::solve(), oomph::GMRES< MATRIX >::solve(), oomph::AugmentedBlockFoldLinearSolver::solve(), oomph::BlockPitchForkLinearSolver::solve(), oomph::AugmentedBlockPitchForkLinearSolver::solve(), oomph::BlockHopfLinearSolver::solve(), oomph::HSL_MA42::solve(), oomph::GS< CRDoubleMatrix >::solve(), oomph::AugmentedProblemGMRES::solve(), oomph::SuperLUSolver::solve(), oomph::HelmholtzGMRESMG< MATRIX >::solve(), oomph::HelmholtzFGMRESMG< MATRIX >::solve(), oomph::TrilinosAztecOOSolver::solve(), oomph::ARPACK::solve_eigenproblem(), oomph::LAPACK_QZ::solve_eigenproblem(), oomph::BlockHopfLinearSolver::solve_for_two_rhs(), oomph::SuperLUSolver::solve_transpose(), and oomph::TrilinosAztecOOSolver::solver_setup().
clear_distribution()
void oomph::DistributableLinearAlgebraObject::clear_distribution () inline protected
clear the distribution of this distributable linear algebra object
     {
       Distribution_pt->clear();
     }
References oomph::LinearAlgebraDistribution::clear(), and Distribution_pt.
Referenced by oomph::DenseLU::clean_up_memory(), oomph::SuperLUSolver::clean_up_memory(), oomph::DoubleMultiVector::clear(), oomph::DoubleVector::clear(), oomph::CRDoubleMatrix::clear(), and oomph::BlockPreconditioner< MATRIX >::clear_block_preconditioner_base().
distributed()
bool oomph::DistributableLinearAlgebraObject::distributed () const inline
distribution is serial or distributed
     {
       return Distribution_pt->distributed();
     }
References oomph::LinearAlgebraDistribution::distributed(), and Distribution_pt.
Referenced by oomph::NavierStokesSchurComplementPreconditioner::assemble_inv_press_and_veloc_mass_matrix_diagonal(), oomph::PressureBasedSolidLSCPreconditioner::assemble_mass_matrix_diagonal(), oomph::HelmholtzSmoother::check_validity_of_solve_helper_inputs(), oomph::Smoother::check_validity_of_solve_helper_inputs(), oomph::CRDoubleMatrixHelpers::concatenate(), oomph::DoubleVectorHelpers::concatenate(), oomph::DoubleVectorHelpers::concatenate_without_communication(), oomph::CRDoubleMatrixHelpers::concatenate_without_communication(), oomph::TrilinosEpetraHelpers::copy_to_oomphlib_vector(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_matrix(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_matrix_for_aztecoo(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_vector(), oomph::HypreHelpers::create_HYPRE_Matrix(), oomph::HypreHelpers::create_HYPRE_Vector(), oomph::DoubleMultiVector::dot(), oomph::DoubleVector::dot(), oomph::CRDoubleMatrix::entries_are_sorted(), oomph::MumpsSolver::factorise(), oomph::SuperLUSolver::factorise_serial(), oomph::CRDoubleMatrix::get_matrix_transpose(), oomph::CRDoubleMatrix::global_matrix(), oomph::DoubleVectorWithHaloEntries::global_value(), oomph::CRDoubleMatrix::inf_norm(), main(), oomph::DoubleVector::max(), oomph::CRDoubleMatrix::multiply(), oomph::DenseDoubleMatrix::multiply(), oomph::CCDoubleMatrix::multiply(), oomph::CRDoubleMatrix::multiply_transpose(), oomph::DenseDoubleMatrix::multiply_transpose(), oomph::CCDoubleMatrix::multiply_transpose(), oomph::DoubleVector::norm(), oomph::DoubleMultiVector::norm(), oomph::DoubleMultiVector::output(), oomph::DoubleVector::output(), oomph::ILUZeroPreconditioner< CCDoubleMatrix >::preconditioner_solve(), oomph::ILUZeroPreconditioner< CRDoubleMatrix >::preconditioner_solve(), oomph::DoubleMultiVector::redistribute(), oomph::DoubleVector::redistribute(), oomph::CRDoubleMatrix::redistribute(), oomph::AugmentedBlockFoldLinearSolver::resolve(), oomph::ILUZeroPreconditioner< CRDoubleMatrix >::setup(), oomph::AugmentedBlockFoldLinearSolver::solve(), oomph::AugmentedBlockPitchForkLinearSolver::solve(), oomph::BlockHopfLinearSolver::solve(), oomph::FD_LU::solve(), oomph::BlockHopfLinearSolver::solve_for_two_rhs(), oomph::AugmentedProblemGMRES::solve_helper(), oomph::CRDoubleMatrix::sort_entries(), oomph::DoubleVectorHelpers::split(), oomph::DoubleVectorHelpers::split_without_communication(), oomph::DoubleVectorWithHaloEntries::sum_all_halo_and_haloed_values(), and oomph::DoubleVectorWithHaloEntries::synchronise().
distribution_built()
bool oomph::DistributableLinearAlgebraObject::distribution_built () const inline
if the communicator_pt is null then the distribution is not setup then false is returned, otherwise return true
     {
       return Distribution_pt->built();
     }
References oomph::LinearAlgebraDistribution::built(), and Distribution_pt.
Referenced by oomph::MumpsSolver::backsub(), oomph::DoubleMultiVector::build(), oomph::DoubleVector::build(), oomph::Problem::get_eigenproblem_matrices(), oomph::Problem::get_jacobian(), oomph::CRDoubleMatrix::inf_norm(), oomph::CRDoubleMatrix::multiply(), oomph::DoubleVector::operator*=(), oomph::DoubleMultiVector::operator*=(), oomph::DoubleVector::operator-=(), oomph::DoubleMultiVector::operator-=(), oomph::DoubleVector::set_external_values(), oomph::DoubleMultiVector::shallow_build(), and oomph::DenseLU::solve().
distribution_pt()
LinearAlgebraDistribution* oomph::DistributableLinearAlgebraObject::distribution_pt () const inline
access to the LinearAlgebraDistribution
     {
       return Distribution_pt;
     }
References Distribution_pt.
Referenced by oomph::CRDoubleMatrix::add(), oomph::AugmentedProblemGMRES::apply_schur_complement_preconditioner(), oomph::OomphLibPreconditionerEpetraOperator::ApplyInverse(), oomph::AugmentedProblemGMRES::augmented_matrix_multiply(), oomph::MumpsSolver::backsub(), oomph::SuperLUSolver::backsub_serial(), oomph::SuperLUSolver::backsub_transpose_serial(), oomph::DoubleMultiVector::build(), oomph::DoubleVector::build(), oomph::HelmholtzSmoother::check_validity_of_solve_helper_inputs(), oomph::Smoother::check_validity_of_solve_helper_inputs(), oomph::SuperLUSolver::clean_up_memory(), oomph::HelmholtzGMRESMG< MATRIX >::complex_matrix_multiplication(), oomph::HelmholtzSmoother::complex_matrix_multiplication(), oomph::CRDoubleMatrixHelpers::concatenate(), oomph::DoubleVectorHelpers::concatenate(), oomph::DoubleVectorHelpers::concatenate_without_communication(), oomph::CRDoubleMatrixHelpers::concatenate_without_communication(), oomph::TrilinosEpetraHelpers::copy_to_oomphlib_vector(), oomph::CRDoubleMatrix::CRDoubleMatrix(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_matrix(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_matrix_for_aztecoo(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_vector(), oomph::TrilinosEpetraHelpers::create_epetra_vector_view_data(), oomph::HypreHelpers::create_HYPRE_Matrix(), oomph::HypreHelpers::create_HYPRE_Vector(), oomph::CRDoubleMatrixHelpers::deep_copy(), oomph::DoubleMultiVector::dot(), oomph::DoubleVector::dot(), oomph::DoubleMultiVector::DoubleMultiVector(), oomph::SuperLUSolver::factorise(), oomph::MumpsSolver::factorise(), oomph::BlockPreconditioner< MATRIX >::get_concatenated_block(), oomph::Problem::get_eigenproblem_matrices(), oomph::Problem::get_jacobian(), oomph::CRDoubleMatrix::get_matrix_transpose(), oomph::Problem::get_residuals(), oomph::CRDoubleMatrix::global_matrix(), oomph::HypreInterface::hypre_matrix_setup(), oomph::HypreInterface::hypre_solve(), oomph::CRDoubleMatrix::inf_norm(), oomph::BlockPreconditioner< MATRIX >::internal_dof_number(), oomph::BlockPreconditioner< MATRIX >::internal_get_block(), oomph::BlockPreconditioner< MATRIX >::internal_index_in_dof(), oomph::BlockPreconditioner< MATRIX >::internal_preconditioner_matrix_distribution_pt(), oomph::CRDoubleMatrix::lubksub(), main(), oomph::BlockPreconditioner< MATRIX >::master_distribution_pt(), oomph::DoubleVector::max(), oomph::TrilinosEpetraHelpers::multiply(), oomph::CRDoubleMatrix::multiply(), oomph::DenseDoubleMatrix::multiply(), oomph::CCDoubleMatrix::multiply(), oomph::MatrixVectorProduct::multiply(), oomph::CRDoubleMatrix::multiply_transpose(), oomph::DenseDoubleMatrix::multiply_transpose(), oomph::CCDoubleMatrix::multiply_transpose(), oomph::MatrixVectorProduct::multiply_transpose(), oomph::DoubleVector::norm(), oomph::DoubleMultiVector::norm(), oomph::OomphLibPreconditionerEpetraOperator::OomphLibPreconditionerEpetraOperator(), oomph::DoubleMultiVector::operator+=(), oomph::DoubleMultiVector::operator-=(), oomph::DoubleMultiVector::output(), oomph::DoubleVector::output(), oomph::PitchForkHandler::PitchForkHandler(), oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >::preconditioner_solve(), oomph::TwoPlusOneUpperTriangularPreconditioner< MATRIX >::preconditioner_solve(), oomph::TwoPlusThreeUpperTriangularWithTwoLevelSubsidiary< MATRIX >::preconditioner_solve(), oomph::TwoPlusThreeUpperTriangularWithReplace< MATRIX >::preconditioner_solve(), oomph::CoarseTwoPlusTwoPlusOne< MATRIX >::preconditioner_solve(), oomph::OnePlusFourWithTwoCoarse< MATRIX >::preconditioner_solve(), oomph::MatrixBasedDiagPreconditioner::preconditioner_solve(), oomph::MatrixBasedLumpedPreconditioner< MATRIX >::preconditioner_solve(), oomph::ILUZeroPreconditioner< CCDoubleMatrix >::preconditioner_solve(), oomph::ILUZeroPreconditioner< CRDoubleMatrix >::preconditioner_solve(), oomph::HyprePreconditioner::preconditioner_solve(), oomph::IdentityPreconditioner::preconditioner_solve(), oomph::TrilinosPreconditionerBase::preconditioner_solve(), oomph::LagrangeEnforcedFlowPreconditioner::preconditioner_solve(), oomph::NavierStokesSchurComplementPreconditioner::preconditioner_solve(), oomph::PressureBasedSolidLSCPreconditioner::preconditioner_solve(), oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::preconditioner_solve(), oomph::GMRESBlockPreconditioner::preconditioner_solve(), oomph::DoubleMultiVector::redistribute(), oomph::DoubleVector::redistribute(), oomph::CRDoubleMatrix::redistribute(), oomph::AugmentedBlockFoldLinearSolver::resolve(), oomph::BlockPitchForkLinearSolver::resolve(), oomph::AugmentedBlockPitchForkLinearSolver::resolve(), oomph::HSL_MA42::resolve(), oomph::MumpsSolver::resolve(), oomph::HypreSolver::resolve(), oomph::TrilinosAztecOOSolver::resolve(), run_it(), oomph::MatrixBasedLumpedPreconditioner< MATRIX >::setup(), oomph::MatrixBasedDiagPreconditioner::setup(), oomph::ILUZeroPreconditioner< CRDoubleMatrix >::setup(), oomph::InnerIterationPreconditioner< SOLVER, PRECONDITIONER >::setup(), oomph::HyprePreconditioner::setup(), oomph::NewMumpsPreconditioner::setup(), oomph::IdentityPreconditioner::setup(), oomph::SuperLUPreconditioner::setup(), oomph::TrilinosPreconditionerBase::setup(), oomph::LagrangeEnforcedFlowPreconditioner::setup(), oomph::MatrixVectorProduct::setup(), oomph::Preconditioner::setup(), oomph::DoubleMultiVector::setup_doublevector_representation(), oomph::DoubleMultiVector::shallow_build(), oomph::DenseLU::solve(), oomph::MumpsSolver::solve(), oomph::HypreSolver::solve(), oomph::GS< MATRIX >::solve(), oomph::DampedJacobi< MATRIX >::solve(), oomph::AugmentedBlockFoldLinearSolver::solve(), oomph::BlockPitchForkLinearSolver::solve(), oomph::AugmentedBlockPitchForkLinearSolver::solve(), oomph::BlockHopfLinearSolver::solve(), oomph::CG< MATRIX >::solve(), oomph::BiCGStab< MATRIX >::solve(), oomph::GS< CRDoubleMatrix >::solve(), oomph::GMRES< MATRIX >::solve(), oomph::AugmentedProblemGMRES::solve(), oomph::SuperLUSolver::solve(), oomph::HelmholtzGMRESMG< MATRIX >::solve(), oomph::HelmholtzFGMRESMG< MATRIX >::solve(), oomph::TrilinosAztecOOSolver::solve(), oomph::ARPACK::solve_eigenproblem(), oomph::LAPACK_QZ::solve_eigenproblem(), oomph::BlockHopfLinearSolver::solve_for_two_rhs(), oomph::CG< MATRIX >::solve_helper(), oomph::BiCGStab< MATRIX >::solve_helper(), oomph::GS< CRDoubleMatrix >::solve_helper(), oomph::GMRES< MATRIX >::solve_helper(), oomph::AugmentedProblemGMRES::solve_helper(), oomph::HelmholtzGMRESMG< MATRIX >::solve_helper(), oomph::HelmholtzFGMRESMG< MATRIX >::solve_helper(), oomph::SuperLUSolver::solve_transpose(), oomph::TrilinosAztecOOSolver::solver_setup(), oomph::CRDoubleMatrix::sparse_indexed_output_with_offset(), oomph::DoubleVectorHelpers::split(), oomph::DoubleVectorHelpers::split_without_communication(), oomph::LowStorageRungeKutta< ORDER >::timestep(), oomph::GMRESBlockPreconditioner::update(), oomph::HelmholtzGMRESMG< MATRIX >::update(), and oomph::HelmholtzFGMRESMG< MATRIX >::update().
first_row() [1/2]
unsigned oomph::DistributableLinearAlgebraObject::first_row () const inline
access function for the first row on this processor
     {
       return Distribution_pt->first_row();
     }
References Distribution_pt, and oomph::LinearAlgebraDistribution::first_row().
Referenced by oomph::PressureBasedSolidLSCPreconditioner::assemble_mass_matrix_diagonal(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_matrix_for_aztecoo(), oomph::CRDoubleMatrix::diagonal_entries(), oomph::MumpsSolver::factorise(), oomph::CRDoubleMatrix::global_matrix(), oomph::DoubleVectorWithHaloEntries::global_value(), oomph::DoubleVector::initialise(), oomph::BlockPreconditioner< MATRIX >::internal_dof_number(), oomph::BlockPreconditioner< MATRIX >::internal_index_in_dof(), main(), oomph::TrilinosEpetraHelpers::multiply(), oomph::DoubleMultiVector::output(), oomph::DoubleVector::output(), oomph::DoubleVector::output_local_values_with_offset(), oomph::DoubleMultiVector::redistribute(), oomph::DoubleVector::redistribute(), oomph::CRDoubleMatrix::redistribute(), oomph::MatrixBasedDiagPreconditioner::setup(), oomph::PseudoElasticPreconditionerSubsidiaryPreconditionerOld::setup(), oomph::CRDoubleMatrix::sparse_indexed_output_with_offset(), and oomph::DoubleVectorHelpers::split().
first_row() [2/2]
unsigned oomph::DistributableLinearAlgebraObject::first_row (const unsigned & p) const inline
access function for the first row on this processor
     {
       return Distribution_pt->first_row(p);
     }
References Distribution_pt, oomph::LinearAlgebraDistribution::first_row(), and p.
nrow()
unsigned oomph::DistributableLinearAlgebraObject::nrow () const inline
access function to the number of global rows.
     {
       return Distribution_pt->nrow();
     }
References Distribution_pt, and oomph::LinearAlgebraDistribution::nrow().
Referenced by oomph::IMRByBDF::actions_after_timestep(), oomph::Problem::add_eigenvector_to_dofs(), oomph::PressureBasedSolidLSCPreconditioner::assemble_mass_matrix_diagonal(), oomph::Problem::assign_eigenvector_to_dofs(), oomph::DenseLU::backsub(), oomph::SuperLUSolver::backsub_serial(), oomph::SuperLUSolver::backsub_transpose_serial(), oomph::HelmholtzSmoother::check_validity_of_solve_helper_inputs(), oomph::Smoother::check_validity_of_solve_helper_inputs(), oomph::ComplexGMRES< MATRIX >::complex_smoother_setup(), oomph::DoubleVectorHelpers::concatenate(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_vector(), Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::GetVecLength(), oomph::MGSolver< DIM >::interpolation_matrix_set(), oomph::HelmholtzMGPreconditioner< DIM >::interpolation_matrix_set(), main(), oomph::DoubleVector::max(), oomph::DenseDoubleMatrix::multiply(), oomph::CCDoubleMatrix::multiply(), oomph::DenseDoubleMatrix::multiply_transpose(), oomph::CCDoubleMatrix::multiply_transpose(), oomph::CRDoubleMatrix::nrow(), oomph::DoubleMultiVector::output(), oomph::DoubleVector::output(), oomph::LagrangeEnforcedFlowPreconditioner::preconditioner_solve(), oomph::NavierStokesSchurComplementPreconditioner::preconditioner_solve(), oomph::PressureBasedSolidLSCPreconditioner::preconditioner_solve(), oomph::MGPreconditioner< DIM >::preconditioner_solve(), oomph::DoubleMultiVector::redistribute(), oomph::DoubleVector::redistribute(), oomph::HSL_MA42::resolve(), oomph::SuperLUSolver::resolve(), oomph::TrilinosAztecOOSolver::resolve(), oomph::SuperLUSolver::resolve_transpose(), oomph::Problem::set_dofs(), oomph::InnerIterationPreconditioner< SOLVER, PRECONDITIONER >::setup(), oomph::HyprePreconditioner::setup(), oomph::TrilinosPreconditionerBase::setup(), oomph::DenseLU::solve(), oomph::SuperLUSolver::solve(), oomph::MumpsSolver::solve(), oomph::TrilinosAztecOOSolver::solve(), oomph::CG< MATRIX >::solve_helper(), oomph::BiCGStab< MATRIX >::solve_helper(), oomph::GS< MATRIX >::solve_helper(), oomph::GS< CRDoubleMatrix >::solve_helper(), oomph::DampedJacobi< MATRIX >::solve_helper(), oomph::GMRES< MATRIX >::solve_helper(), oomph::AugmentedProblemGMRES::solve_helper(), oomph::HelmholtzGMRESMG< MATRIX >::solve_helper(), oomph::HelmholtzFGMRESMG< MATRIX >::solve_helper(), oomph::SuperLUSolver::solve_transpose(), oomph::DoubleVectorHelpers::split(), SSP_RungeKutta< ORDER >::timestep(), and oomph::LowStorageRungeKutta< ORDER >::timestep().
nrow_local() [1/2]
unsigned oomph::DistributableLinearAlgebraObject::nrow_local () const inline
access function for the num of local rows on this processor.
     {
       return Distribution_pt->nrow_local();
     }
References Distribution_pt, and oomph::LinearAlgebraDistribution::nrow_local().
Referenced by oomph::CRDoubleMatrix::add(), oomph::Problem::add_eigenvector_to_dofs(), oomph::PressureBasedSolidLSCPreconditioner::assemble_mass_matrix_diagonal(), oomph::Problem::assign_eigenvector_to_dofs(), oomph::DoubleMultiVector::build(), oomph::DoubleVector::build(), oomph::CRDoubleMatrix::build(), oomph::CRDoubleMatrix::build_without_copy(), oomph::TrilinosEpetraHelpers::copy_to_oomphlib_vector(), oomph::CRDoubleMatrix::CRDoubleMatrix(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_matrix_for_aztecoo(), oomph::CRDoubleMatrixHelpers::deep_copy(), oomph::CRDoubleMatrix::diagonal_entries(), oomph::DoubleMultiVector::dot(), oomph::DoubleVector::dot(), oomph::DoubleMultiVector::DoubleMultiVector(), oomph::Problem::get_derivative_wrt_global_parameter(), oomph::CRDoubleMatrix::global_matrix(), oomph::DoubleVectorWithHaloEntries::global_value(), oomph::CRDoubleMatrix::inf_norm(), oomph::DoubleMultiVector::initialise(), oomph::DoubleVector::initialise(), oomph::BlockPreconditioner< MATRIX >::internal_dof_number(), oomph::BlockPreconditioner< MATRIX >::internal_index_in_dof(), oomph::PseudoElasticPreconditioner::lagrange_multiplier_preconditioner_solve(), oomph::PseudoElasticPreconditionerOld::lagrange_multiplier_preconditioner_solve(), main(), oomph::CRDoubleMatrix::matrix_reduction(), oomph::DoubleVector::max(), oomph::TrilinosEpetraHelpers::multiply(), Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvRandom(), Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvScale(), oomph::DoubleVector::norm(), oomph::DoubleMultiVector::norm(), oomph::DoubleMultiVector::operator()(), oomph::DoubleVector::operator*=(), oomph::DoubleMultiVector::operator*=(), oomph::DoubleVector::operator+=(), oomph::DoubleMultiVector::operator+=(), oomph::DoubleVector::operator-=(), oomph::DoubleMultiVector::operator-=(), oomph::DoubleMultiVector::operator==(), oomph::DoubleVector::operator==(), oomph::DoubleVector::operator[](), oomph::DoubleMultiVector::output(), oomph::DoubleVector::output(), oomph::DoubleVector::output_local_values(), oomph::DoubleVector::output_local_values_with_offset(), oomph::MatrixBasedDiagPreconditioner::preconditioner_solve(), oomph::LagrangeEnforcedFlowPreconditioner::preconditioner_solve(), oomph::DoubleMultiVector::redistribute(), oomph::DoubleVector::redistribute(), oomph::CRDoubleMatrix::redistribute(), oomph::DoubleMatrixBase::residual(), oomph::BlockPitchForkLinearSolver::resolve(), Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::SetBlock(), oomph::MatrixBasedLumpedPreconditioner< MATRIX >::setup(), oomph::MatrixBasedDiagPreconditioner::setup(), oomph::HyprePreconditioner::setup(), oomph::PseudoElasticPreconditionerSubsidiaryPreconditionerOld::setup(), oomph::ANASAZI::solve_eigenproblem(), oomph::CRDoubleMatrix::sparse_indexed_output_with_offset(), and oomph::DoubleVectorHelpers::split().
nrow_local() [2/2]
unsigned oomph::DistributableLinearAlgebraObject::nrow_local (const unsigned & p) const inline
access function for the num of local rows on this processor.
     {
       return Distribution_pt->nrow_local(p);
     }
References Distribution_pt, oomph::LinearAlgebraDistribution::nrow_local(), and p.
operator=()
void oomph::DistributableLinearAlgebraObject::operator= (const DistributableLinearAlgebraObject &) delete
Broken assignment operator.
Member Data Documentation
Distribution_pt
LinearAlgebraDistribution* oomph::DistributableLinearAlgebraObject::Distribution_pt private
the LinearAlgebraDistribution object
Referenced by build_distribution(), clear_distribution(), DistributableLinearAlgebraObject(), distributed(), distribution_built(), distribution_pt(), first_row(), nrow(), nrow_local(), and ~DistributableLinearAlgebraObject().
The documentation for this class was generated from the following file:
linear_algebra_distribution.h