MercuryDPM: Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device > Struct Template Reference
#include <TensorChipping.h>
Public Types
enum {
IsAligned = false , PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess , BlockAccess = TensorEvaluator<ArgType, Device>::RawAccess , Layout = TensorEvaluator<ArgType, Device>::Layout ,
RawAccess = false
}
typedef TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device > Base
typedef TensorChippingOp< DimId, ArgType > XprType
typedef XprType::Index Index
typedef DSizes< Index, NumDims > Dimensions
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef internal::TensorBlockDescriptor< NumDims, Index > TensorBlockDesc
Public Types inherited from Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >
enum {
IsAligned = false , PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess , BlockAccess = TensorEvaluator<ArgType, Device>::BlockAccess , IsOuterChipping = (Layout == ColMajor && DimId == NumInputDims - 1) || (Layout == RowMajor && DimId == 0) ,
IsInnerChipping = (Layout == ColMajor && DimId == 0) || (Layout == RowMajor && DimId == NumInputDims - 1) , PreferBlockAccess = TensorEvaluator<ArgType, Device>::PreferBlockAccess || !IsOuterChipping , CoordAccess = false , RawAccess = false
}
typedef TensorChippingOp< DimId, ArgType > XprType
typedef XprType::Index Index
typedef DSizes< Index, NumDims > Dimensions
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef std::remove_const_t< Scalar > ScalarNoConst
typedef internal::TensorBlockDescriptor< NumDims, Index > TensorBlockDesc
typedef internal::TensorBlockScratchAllocator< Device > TensorBlockScratch
typedef internal::TensorBlockDescriptor< NumInputDims, Index > ArgTensorBlockDesc
typedef TensorEvaluator< const ArgType, Device >::TensorBlock ArgTensorBlock
typedef internal::TensorMaterializedBlock< ScalarNoConst, NumDims, Layout, Index > TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType & coeffRef (Index index) const
template<int StoreMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void writePacket (Index index, const PacketReturnType &x) const
template<typename TensorBlock >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void writeBlock (const TensorBlockDesc &desc, const TensorBlock &block)
Public Member Functions inherited from Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements getResourceRequirements () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock block (TensorBlockDesc &desc, TensorBlockScratch &scratch, bool root_of_expr_ast=false) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Storage::Type data () const
Static Public Attributes
static constexpr int NumInputDims
static constexpr int NumDims = NumInputDims - 1
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
Static Public Attributes inherited from Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >
static constexpr int NumInputDims
static constexpr int NumDims = NumInputDims - 1
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Additional Inherited Members
Protected Member Functions inherited from Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index srcCoeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool isInnerChipping () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool isOuterChipping () const
Protected Attributes inherited from Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >
Dimensions m_dimensions
Index m_stride
Index m_inputOffset
Index m_inputStride
TensorEvaluator< ArgType, Device > m_impl
const internal::DimensionId< DimId > m_dim
const Device EIGEN_DEVICE_REF m_device
bool m_isEffectivelyInnerChipping
bool m_isEffectivelyOuterChipping
Member Typedef Documentation
Base
template<DenseIndex DimId, typename ArgType , typename Device > typedef TensorEvaluator<const TensorChippingOp<DimId, ArgType>, Device> Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::Base
CoeffReturnType
template<DenseIndex DimId, typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::CoeffReturnType
Dimensions
template<DenseIndex DimId, typename ArgType , typename Device > typedef DSizes<Index, NumDims> Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::Dimensions
Index
template<DenseIndex DimId, typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::Index
PacketReturnType
template<DenseIndex DimId, typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::PacketReturnType
Scalar
template<DenseIndex DimId, typename ArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::Scalar
TensorBlockDesc
template<DenseIndex DimId, typename ArgType , typename Device > typedef internal::TensorBlockDescriptor<NumDims, Index> Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::TensorBlockDesc
XprType
template<DenseIndex DimId, typename ArgType , typename Device > typedef TensorChippingOp<DimId, ArgType> Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<DenseIndex DimId, typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
Layout
RawAccess
        {
     IsAligned = false,
     PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess,
     BlockAccess = TensorEvaluator<ArgType, Device>::RawAccess,
     Layout = TensorEvaluator<ArgType, Device>::Layout,
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<DenseIndex DimId, typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
 : Base(op, device) {}
Member Function Documentation
coeffRef()
template<DenseIndex DimId, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType& Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::coeffRef (Index index) const inline
{
     return this->m_impl.coeffRef(this->srcCoeff(index));
   }
writeBlock()
template<DenseIndex DimId, typename ArgType , typename Device > template<typename TensorBlock > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::writeBlock (const TensorBlockDesc & desc, const TensorBlock & block) inline
{
     eigen_assert(this->m_impl.data() != NULL);
     const Index chip_dim = this->m_dim.actualDim();
     DSizes<Index, NumInputDims> input_block_dims;
     for (int i = 0; i < NumInputDims; ++i) {
       input_block_dims[i] = i < chip_dim ? desc.dimension(i) : i > chip_dim ? desc.dimension(i - 1) : 1;
     }
     typedef TensorReshapingOp<const DSizes<Index, NumInputDims>, const typename TensorBlock::XprType> TensorBlockExpr;
     typedef internal::TensorBlockAssignment<Scalar, NumInputDims, TensorBlockExpr, Index> TensorBlockAssign;
     TensorBlockAssign::Run(
         TensorBlockAssign::target(input_block_dims, internal::strides<Layout>(this->m_impl.dimensions()),
                                   this->m_impl.data(), this->srcCoeff(desc.offset())),
         block.expr().reshape(input_block_dims));
   }
References Eigen::TensorEvaluator< Derived, Device >::block(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::dimension(), eigen_assert, Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::expr(), i, Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::offset(), and Eigen::TensorBase< Derived, AccessLevel >::reshape().
writePacket()
template<DenseIndex DimId, typename ArgType , typename Device > template<int StoreMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::writePacket (Index index, const PacketReturnType & x) const inline
{
     if (this->isInnerChipping()) {
       // m_stride is equal to 1, so let's avoid the integer division.
       eigen_assert(this->m_stride == 1);
       EIGEN_ALIGN_MAX std::remove_const_t<CoeffReturnType> values[PacketSize];
       internal::pstore<CoeffReturnType, PacketReturnType>(values, x);
       Index inputIndex = index * this->m_inputStride + this->m_inputOffset;
       EIGEN_UNROLL_LOOP
       for (int i = 0; i < PacketSize; ++i) {
         this->m_impl.coeffRef(inputIndex) = values[i];
         inputIndex += this->m_inputStride;
       }
     } else if (this->isOuterChipping()) {
       // m_stride is always greater than index, so let's avoid the integer division.
       eigen_assert(this->m_stride > index);
       this->m_impl.template writePacket<StoreMode>(index + this->m_inputOffset, x);
     } else {
       const Index idx = index / this->m_stride;
       const Index rem = index - idx * this->m_stride;
       if (rem + PacketSize <= this->m_stride) {
         const Index inputIndex = idx * this->m_inputStride + this->m_inputOffset + rem;
         this->m_impl.template writePacket<StoreMode>(inputIndex, x);
       } else {
         // Cross stride boundary. Fallback to slow path.
         EIGEN_ALIGN_MAX std::remove_const_t<CoeffReturnType> values[PacketSize];
         internal::pstore<CoeffReturnType, PacketReturnType>(values, x);
         EIGEN_UNROLL_LOOP
         for (int i = 0; i < PacketSize; ++i) {
           this->coeffRef(index) = values[i];
           ++index;
         }
       }
     }
   }
References Eigen::TensorEvaluator< Derived, Device >::coeffRef(), EIGEN_ALIGN_MAX, eigen_assert, EIGEN_UNROLL_LOOP, i, Eigen::TensorEvaluator< Derived, Device >::PacketSize, and plotDoE::x.
Member Data Documentation
NumDims
template<DenseIndex DimId, typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::NumDims = NumInputDims - 1 static constexpr
NumInputDims
template<DenseIndex DimId, typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::NumInputDims static constexpr
Initial value:
=
      internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value
PacketSize
template<DenseIndex DimId, typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorChipping.h