MercuryDPM: Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType > Class Template Reference
Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Expression of a coefficient wise version of the C++ ternary operator ?:
#include <Select.h>
Public Types
typedef internal::dense_xpr_base< Select >::type Base
Public Member Functions
EIGEN_DEVICE_FUNC Select (const ConditionMatrixType &a_conditionMatrix, const ThenMatrixType &a_thenMatrix, const ElseMatrixType &a_elseMatrix)
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC const Scalar coeff (Index i, Index j) const
EIGEN_DEVICE_FUNC const Scalar coeff (Index i) const
EIGEN_DEVICE_FUNC const ConditionMatrixType & conditionMatrix () const
EIGEN_DEVICE_FUNC const ThenMatrixType & thenMatrix () const
EIGEN_DEVICE_FUNC const ElseMatrixType & elseMatrix () const
Protected Attributes
ConditionMatrixType::Nested m_condition
ThenMatrixType::Nested m_then
ElseMatrixType::Nested m_else
Detailed Description
template<typename ConditionMatrixType, typename ThenMatrixType, typename ElseMatrixType>
class Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >
Expression of a coefficient wise version of the C++ ternary operator ?:
Template Parameters
ConditionMatrixType the type of the condition expression which must be a boolean matrix
ThenMatrixType the type of the then expression
ElseMatrixType the type of the else expression
This class represents an expression of a coefficient wise version of the C++ ternary operator ?:. It is the return type of DenseBase::select() and most of the time this is the only way it is used.
See also
DenseBase::select(const DenseBase<ThenDerived>&, const DenseBase<ElseDerived>&) const
Member Typedef Documentation
Base
template<typename ConditionMatrixType , typename ThenMatrixType , typename ElseMatrixType > typedef internal::dense_xpr_base<Select>::type Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::Base
Constructor & Destructor Documentation
Select()
template<typename ConditionMatrixType , typename ThenMatrixType , typename ElseMatrixType > EIGEN_DEVICE_FUNC Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::Select (const ConditionMatrixType & a_conditionMatrix, const ThenMatrixType & a_thenMatrix, const ElseMatrixType & a_elseMatrix) inline
       : m_condition(a_conditionMatrix), m_then(a_thenMatrix), m_else(a_elseMatrix) {
     eigen_assert(m_condition.rows() == m_then.rows() && m_condition.rows() == m_else.rows());
     eigen_assert(m_condition.cols() == m_then.cols() && m_condition.cols() == m_else.cols());
   }
References eigen_assert, Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::m_condition, Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::m_else, and Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::m_then.
Member Function Documentation
coeff() [1/2]
template<typename ConditionMatrixType , typename ThenMatrixType , typename ElseMatrixType > EIGEN_DEVICE_FUNC const Scalar Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::coeff (Index i) const inline
{
     if (m_condition.coeff(i))
       return m_then.coeff(i);
     else
       return m_else.coeff(i);
   }
References i, Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::m_condition, Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::m_else, and Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::m_then.
coeff() [2/2]
template<typename ConditionMatrixType , typename ThenMatrixType , typename ElseMatrixType > EIGEN_DEVICE_FUNC const Scalar Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::coeff (Index i, Index j) const inline
{
     if (m_condition.coeff(i, j))
       return m_then.coeff(i, j);
     else
       return m_else.coeff(i, j);
   }
References i, j, Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::m_condition, Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::m_else, and Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::m_then.
cols()
template<typename ConditionMatrixType , typename ThenMatrixType , typename ElseMatrixType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::cols () const inline
 { return m_condition.cols(); }
References Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::m_condition.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
conditionMatrix()
template<typename ConditionMatrixType , typename ThenMatrixType , typename ElseMatrixType > EIGEN_DEVICE_FUNC const ConditionMatrixType& Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::conditionMatrix () const inline
 { return m_condition; }
References Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::m_condition.
elseMatrix()
template<typename ConditionMatrixType , typename ThenMatrixType , typename ElseMatrixType > EIGEN_DEVICE_FUNC const ElseMatrixType& Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::elseMatrix () const inline
 { return m_else; }
References Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::m_else.
rows()
template<typename ConditionMatrixType , typename ThenMatrixType , typename ElseMatrixType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::rows () const inline
 { return m_condition.rows(); }
References Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::m_condition.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
thenMatrix()
template<typename ConditionMatrixType , typename ThenMatrixType , typename ElseMatrixType > EIGEN_DEVICE_FUNC const ThenMatrixType& Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::thenMatrix () const inline
 { return m_then; }
References Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::m_then.
Member Data Documentation
m_condition
template<typename ConditionMatrixType , typename ThenMatrixType , typename ElseMatrixType > ConditionMatrixType::Nested Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::m_condition protected
Referenced by Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::coeff(), Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::cols(), Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::conditionMatrix(), Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::rows(), and Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::Select().
m_else
template<typename ConditionMatrixType , typename ThenMatrixType , typename ElseMatrixType > ElseMatrixType::Nested Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::m_else protected
Referenced by Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::coeff(), Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::elseMatrix(), and Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::Select().
m_then
template<typename ConditionMatrixType , typename ThenMatrixType , typename ElseMatrixType > ThenMatrixType::Nested Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::m_then protected
Referenced by Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::coeff(), Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::Select(), and Eigen::Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType >::thenMatrix().
The documentation for this class was generated from the following file:
Select.h