MercuryDPM: CGFields::OrientationField Class Reference
CGFields::OrientationField Class Reference
Contains the computed field values, like density, momentum and stress.
#include <OrientationField.h>
Public Member Functions
OrientationField ()
OrientationField (const OrientationField &other)=default
~OrientationField ()=default
void write (std::ostream &os) const
Writes class content into an output stream, typically a stat file.
void output (std::ostream &os) const
Writes human-readable class content into an output stream, typically a stat file.
void setZero ()
Sets all fields to zero.
OrientationField getSquared () const
Returns the square of all field values (to calculate standard deviation).
OrientationField & operator= (const OrientationField &P)
Copies all field values.
OrientationField & operator+= (const OrientationField &P)
Adds the field values on the RHS to the LHS of the equation.
OrientationField & operator-= (const OrientationField &P)
Subtracts the field values on the RHS from the LHS of the equation.
OrientationField & operator/= (Mdouble a)
Divides the field values on the LHS by the RHS of the equation.
OrientationField operator* (Mdouble a) const
Multiplies the field values on the left of the '*' by the scalar value on the right of the '*' and returns the answer.
void addParticleStatistics (Mdouble phi, const OrientationField &currentInteraction)
This function should be called from within a loop over all particles to compute all the fields that are defined as a sum over all particles (e.g. density, momentum).
void setFields (const BaseParticle &p)
void setCylindricalFields (const BaseParticle &p)
MatrixSymmetric3D getOrientation () const
void setFields (const BaseInteraction &c, IntegralType type)
void setCylindricalFields (const BaseInteraction &c, IntegralType type)
void addParticleDifferentialStatistics (Vec3D &dphi, const OrientationField &currentInteraction)
void addInteractionStatistics (Mdouble psi, const OrientationField &currentInteraction)
void addContactPointStatistics (Mdouble phi, const OrientationField &currentInteraction)
Public Member Functions inherited from CGFields::BaseFields
void setCG (BaseCG *cg)
BaseCG * getCG ()
Static Public Member Functions
static void writeNames (std::ostream &os, unsigned countVariables)
static bool evaluateFixedParticles ()
static bool doInteractionStatistics ()
static bool isDifferentialField ()
Private Attributes
MatrixSymmetric3D orientation_
Additional Inherited Members
Protected Attributes inherited from CGFields::BaseFields
BaseCG * cg_ = nullptr
Stores a pointer to the baseCG instance to get e.g. the handler and time information.
Detailed Description
Contains the computed field values, like density, momentum and stress.
CGPoints inherits from this class; CGPoints::evaluate adds to the values of these variables.
Todo:
These are currently the only fields that are computed. However, this class is destined to be extended to contain additional information such as fabric, energy, local angular momentum. Also, a simpler version is planned, where only particle statistics are evaluated (density and momentum).
Constructor & Destructor Documentation
OrientationField() [1/2]
CGFields::OrientationField::OrientationField ()
     {
         setZero();
         logger(DEBUG, "OrientationField::OrientationField() finished");
     }
References DEBUG, logger, and setZero().
OrientationField() [2/2]
CGFields::OrientationField::OrientationField (const OrientationField & other) default
~OrientationField()
CGFields::OrientationField::~OrientationField () default
Member Function Documentation
addContactPointStatistics()
void CGFields::OrientationField::addContactPointStatistics (Mdouble phi, const OrientationField & currentInteraction) inline
         {}
addInteractionStatistics()
void CGFields::OrientationField::addInteractionStatistics (Mdouble psi, const OrientationField & currentInteraction) inline
         {}
addParticleDifferentialStatistics()
void CGFields::OrientationField::addParticleDifferentialStatistics (Vec3D & dphi, const OrientationField & currentInteraction) inline
         {}
addParticleStatistics()
void CGFields::OrientationField::addParticleStatistics (Mdouble phi, const OrientationField & currentInteraction)
This function should be called from within a loop over all particles to compute all the fields that are defined as a sum over all particles (e.g. density, momentum).
     {
         orientation_ += currentInteraction.getOrientation() * phi;
     }
References getOrientation(), and orientation_.
doInteractionStatistics()
static bool CGFields::OrientationField::doInteractionStatistics () inline static
         {
             return false;
         }
evaluateFixedParticles()
static bool CGFields::OrientationField::evaluateFixedParticles () inline static
         {
             return false;
         }
getOrientation()
MatrixSymmetric3D CGFields::OrientationField::getOrientation () const inline
         {
             return orientation_;
         }
References orientation_.
Referenced by addParticleStatistics().
getSquared()
OrientationField CGFields::OrientationField::getSquared () const
Returns the square of all field values (to calculate standard deviation).
     {
         OrientationField orientationField;
         orientationField.orientation_ = MatrixSymmetric3D::square(orientation_);
         return orientationField;
     }
References orientation_, and MatrixSymmetric3D::square().
isDifferentialField()
static bool CGFields::OrientationField::isDifferentialField () inline static
A bool that determines if the derivative of the CG function has to be computed
         {
             return false;
         }
operator*()
OrientationField CGFields::OrientationField::operator* (Mdouble a) const
Multiplies the field values on the left of the '*' by the scalar value on the right of the '*' and returns the answer.
     {
         OrientationField p;
         p.orientation_ = orientation_ * a;
         return p;
     }
References a, orientation_, and p.
operator+=()
OrientationField & CGFields::OrientationField::operator+= (const OrientationField & P)
Adds the field values on the RHS to the LHS of the equation.
     {
         orientation_ += P.orientation_;
         return *this;
     }
References orientation_, and Global_Physical_Variables::P.
operator-=()
OrientationField & CGFields::OrientationField::operator-= (const OrientationField & P)
Subtracts the field values on the RHS from the LHS of the equation.
     {
         orientation_ -= P.orientation_;
         return *this;
     }
References orientation_, and Global_Physical_Variables::P.
operator/=()
OrientationField & CGFields::OrientationField::operator/= (Mdouble a)
Divides the field values on the LHS by the RHS of the equation.
     {
         orientation_ /= a;
         return *this;
     }
References a, and orientation_.
operator=()
OrientationField & CGFields::OrientationField::operator= (const OrientationField & P) default
Copies all field values.
output()
void CGFields::OrientationField::output (std::ostream & os) const
Writes human-readable class content into an output stream, typically a stat file.
     {
         os << "Orientation " << orientation_;
     }
References orientation_.
setCylindricalFields() [1/2]
void CGFields::OrientationField::setCylindricalFields (const BaseInteraction & c, IntegralType type) inline
         {}
setCylindricalFields() [2/2]
void CGFields::OrientationField::setCylindricalFields (const BaseParticle & p)
     {
         setFields(p);
     }
References p, and setFields().
setFields() [1/2]
void CGFields::OrientationField::setFields (const BaseInteraction & c, IntegralType type) inline
         {}
setFields() [2/2]
void CGFields::OrientationField::setFields (const BaseParticle & p)
     {
         Vec3D orientation = p.getOrientation().getAxis();
         orientation_.XX = orientation.X * orientation.X;
         orientation_.XY = orientation.X * orientation.Y;
         orientation_.YY = orientation.Y * orientation.Y;
         orientation_.XZ = orientation.X * orientation.Z;
         orientation_.YZ = orientation.Y * orientation.Z;
         orientation_.ZZ = orientation.Z * orientation.Z;
         logger(DEBUG, "orientation: %", orientation_);
     }
References DEBUG, logger, orientation_, p, Vec3D::X, MatrixSymmetric3D::XX, MatrixSymmetric3D::XY, MatrixSymmetric3D::XZ, Vec3D::Y, MatrixSymmetric3D::YY, MatrixSymmetric3D::YZ, Vec3D::Z, and MatrixSymmetric3D::ZZ.
Referenced by setCylindricalFields().
setZero()
void CGFields::OrientationField::setZero ()
Sets all fields to zero.
     {
         orientation_.setZero();
     }
References orientation_, and MatrixSymmetric3D::setZero().
Referenced by OrientationField().
write()
void CGFields::OrientationField::write (std::ostream & os) const
Writes class content into an output stream, typically a stat file.
     {
         os << orientation_;
     }
References orientation_.
writeNames()
void CGFields::OrientationField::writeNames (std::ostream & os, unsigned countVariables) static
     {
         os << countVariables + 1 << ":Orientation "; //orientation
     }
Member Data Documentation
orientation_
MatrixSymmetric3D CGFields::OrientationField::orientation_ private
Referenced by addParticleStatistics(), getOrientation(), getSquared(), operator*(), operator+=(), operator-=(), operator/=(), output(), setFields(), setZero(), and write().
The documentation for this class was generated from the following files:
OrientationField.h
OrientationField.cc