MercuryDPM: Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ > Class Template Reference
Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ > Class Template Reference
#include <TensorContractionMapper.h>
Public Types
enum { DirectOffsets = CoeffLoader<Tensor, Tensor::RawAccess, MakePointer_>::DirectOffsets }
Public Member Functions
EIGEN_DEVICE_FUNC SimpleTensorContractionMapper (const Tensor &tensor, const nocontract_t &nocontract_strides, const nocontract_t &ij_strides, const contract_t &contract_strides, const contract_t &k_strides)
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void offsetBuffer (typename Tensor::Index offset)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void prefetch (Index)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar operator() (Index row) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar operator() (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index computeIndex (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE IndexPair< Index > computeIndexPair (Index row, Index col, const Index distance) const
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Index firstAligned (Index size) const
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Index stride () const
const CoeffLoader< Tensor, Tensor::RawAccess, MakePointer_ > & tensor () const
const nocontract_t & nocontract_strides () const
const nocontract_t & ij_strides () const
const contract_t & contract_strides () const
const contract_t & k_strides () const
Protected Attributes
CoeffLoader< Tensor, Tensor::RawAccess, MakePointer_ > m_tensor
const nocontract_t m_nocontract_strides
const nocontract_t m_ij_strides
const contract_t m_contract_strides
const contract_t m_k_strides
Member Enumeration Documentation
anonymous enum
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, int Alignment, template< class > class MakePointer_ = MakePointer> anonymous enum
Enumerator
DirectOffsets
 { DirectOffsets = CoeffLoader<Tensor, Tensor::RawAccess, MakePointer_>::DirectOffsets };
Constructor & Destructor Documentation
SimpleTensorContractionMapper()
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, int Alignment, template< class > class MakePointer_ = MakePointer> EIGEN_DEVICE_FUNC Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::SimpleTensorContractionMapper (const Tensor & tensor, const nocontract_t & nocontract_strides, const nocontract_t & ij_strides, const contract_t & contract_strides, const contract_t & k_strides) inline
       : m_tensor(tensor),
         m_nocontract_strides(nocontract_strides),
         m_ij_strides(ij_strides),
         m_contract_strides(contract_strides),
         m_k_strides(k_strides) {}
Member Function Documentation
computeIndex()
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, int Alignment, template< class > class MakePointer_ = MakePointer> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::computeIndex (Index row, Index col) const inline
{
     const bool left = (side == Lhs);
     EIGEN_UNUSED_VARIABLE(left);  // annoying bug in g++8.1: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85963
     Index nocontract_val = left ? row : col;
     Index linidx = 0;
     EIGEN_UNROLL_LOOP
     for (int i = static_cast<int>(array_size<nocontract_t>::value) - 1; i > 0; i--) {
       const Index idx = nocontract_val / m_ij_strides[i];
       linidx += idx * m_nocontract_strides[i];
       nocontract_val -= idx * m_ij_strides[i];
     }
     if (array_size<typename Tensor::Dimensions>::value > array_size<contract_t>::value) {
       if (side == Lhs && inner_dim_contiguous) {
         eigen_assert(m_nocontract_strides[0] == 1);
         linidx += nocontract_val;
       } else {
         linidx += nocontract_val * m_nocontract_strides[0];
       }
     }
     Index contract_val = left ? col : row;
     if (array_size<contract_t>::value > 0) {
       EIGEN_UNROLL_LOOP
       for (int i = static_cast<int>(array_size<contract_t>::value) - 1; i > 0; i--) {
         const Index idx = contract_val / m_k_strides[i];
         linidx += idx * m_contract_strides[i];
         contract_val -= idx * m_k_strides[i];
       }
       if (side == Rhs && inner_dim_contiguous) {
         eigen_assert(m_contract_strides[0] == 1);
         linidx += contract_val;
       } else {
         linidx += contract_val * m_contract_strides[0];
       }
     }
     return linidx;
   }
References col(), eigen_assert, EIGEN_UNROLL_LOOP, EIGEN_UNUSED_VARIABLE, i, Eigen::internal::Lhs, Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_contract_strides, Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_ij_strides, Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_k_strides, Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_nocontract_strides, Eigen::internal::Rhs, row(), and side.
Referenced by Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::operator()().
computeIndexPair()
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, int Alignment, template< class > class MakePointer_ = MakePointer> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE IndexPair<Index> Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::computeIndexPair (Index row, Index col, const Index distance) const inline
{
     const bool left = (side == Lhs);
     EIGEN_UNUSED_VARIABLE(left);  // annoying bug in g++8.1: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85963
     Index nocontract_val[2] = {left ? row : col, left ? row + distance : col};
     Index linidx[2] = {0, 0};
     if (array_size<typename Tensor::Dimensions>::value > array_size<contract_t>::value) {
       EIGEN_UNROLL_LOOP
       for (int i = static_cast<int>(array_size<nocontract_t>::value) - 1; i > 0; i--) {
         const Index idx0 = nocontract_val[0] / m_ij_strides[i];
         const Index idx1 = nocontract_val[1] / m_ij_strides[i];
         linidx[0] += idx0 * m_nocontract_strides[i];
         linidx[1] += idx1 * m_nocontract_strides[i];
         nocontract_val[0] -= idx0 * m_ij_strides[i];
         nocontract_val[1] -= idx1 * m_ij_strides[i];
       }
       if (side == Lhs && inner_dim_contiguous) {
         eigen_assert(m_nocontract_strides[0] == 1);
         linidx[0] += nocontract_val[0];
         linidx[1] += nocontract_val[1];
       } else {
         linidx[0] += nocontract_val[0] * m_nocontract_strides[0];
         linidx[1] += nocontract_val[1] * m_nocontract_strides[0];
       }
     }
     Index contract_val[2] = {left ? col : row, left ? col : row + distance};
     if (array_size<contract_t>::value > 0) {
       EIGEN_UNROLL_LOOP
       for (int i = static_cast<int>(array_size<contract_t>::value) - 1; i > 0; i--) {
         const Index idx0 = contract_val[0] / m_k_strides[i];
         const Index idx1 = contract_val[1] / m_k_strides[i];
         linidx[0] += idx0 * m_contract_strides[i];
         linidx[1] += idx1 * m_contract_strides[i];
         contract_val[0] -= idx0 * m_k_strides[i];
         contract_val[1] -= idx1 * m_k_strides[i];
       }
       if (side == Rhs && inner_dim_contiguous) {
         eigen_assert(m_contract_strides[0] == 1);
         linidx[0] += contract_val[0];
         linidx[1] += contract_val[1];
       } else {
         linidx[0] += contract_val[0] * m_contract_strides[0];
         linidx[1] += contract_val[1] * m_contract_strides[0];
       }
     }
     return IndexPair<Index>(linidx[0], linidx[1]);
   }
References col(), eigen_assert, EIGEN_UNROLL_LOOP, EIGEN_UNUSED_VARIABLE, i, Eigen::internal::Lhs, Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_contract_strides, Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_ij_strides, Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_k_strides, Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_nocontract_strides, Eigen::internal::Rhs, row(), and side.
contract_strides()
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, int Alignment, template< class > class MakePointer_ = MakePointer> const contract_t& Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::contract_strides () const inline
 { return m_contract_strides; }
References Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_contract_strides.
firstAligned()
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, int Alignment, template< class > class MakePointer_ = MakePointer> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Index Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::firstAligned (Index size) const inline
{
     // Only claim alignment when we can compute the actual stride (ie when we're
     // dealing with the lhs with inner_dim_contiguous. This is because the
     // matrix-vector product relies on the stride when dealing with aligned inputs.
     return (Alignment == Aligned) && (side == Lhs) && inner_dim_contiguous ? 0 : size;
   }
References Eigen::Aligned, Eigen::internal::Lhs, side, and size.
ij_strides()
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, int Alignment, template< class > class MakePointer_ = MakePointer> const nocontract_t& Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::ij_strides () const inline
 { return m_ij_strides; }
References Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_ij_strides.
k_strides()
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, int Alignment, template< class > class MakePointer_ = MakePointer> const contract_t& Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::k_strides () const inline
 { return m_k_strides; }
References Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_k_strides.
nocontract_strides()
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, int Alignment, template< class > class MakePointer_ = MakePointer> const nocontract_t& Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::nocontract_strides () const inline
 { return m_nocontract_strides; }
References Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_nocontract_strides.
offsetBuffer()
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, int Alignment, template< class > class MakePointer_ = MakePointer> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::offsetBuffer (typename Tensor::Index offset) inline
{
     m_tensor.offsetBuffer(offset);
   }
References Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_tensor.
Referenced by Eigen::internal::TensorContractionSubMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, inner_dim_reordered, Alignment, MakePointer_ >::TensorContractionSubMapper().
operator()() [1/2]
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, int Alignment, template< class > class MakePointer_ = MakePointer> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::operator() (Index row) const inline
{
     // column major assumption
     return operator()(row, 0);
   }
References row().
operator()() [2/2]
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, int Alignment, template< class > class MakePointer_ = MakePointer> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::operator() (Index row, Index col) const inline
{
     return m_tensor.coeff(computeIndex(row, col));
   }
References col(), Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::computeIndex(), Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_tensor, and row().
prefetch()
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, int Alignment, template< class > class MakePointer_ = MakePointer> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::prefetch (Index) inline
 {}
stride()
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, int Alignment, template< class > class MakePointer_ = MakePointer> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Index Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::stride () const inline
{
     return ((side == Lhs) && inner_dim_contiguous && array_size<contract_t>::value > 0) ? m_contract_strides[0] : 1;
   }
References Eigen::internal::Lhs, Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_contract_strides, and side.
Referenced by Eigen::internal::TensorContractionSubMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, inner_dim_reordered, Alignment, MakePointer_ >::stride(), and Eigen::internal::TensorContractionSubMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, inner_dim_reordered, Alignment, MakePointer_ >::TensorContractionSubMapper().
tensor()
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, int Alignment, template< class > class MakePointer_ = MakePointer> const CoeffLoader<Tensor, Tensor::RawAccess, MakePointer_>& Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::tensor () const inline
 { return m_tensor; }
References Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_tensor.
Member Data Documentation
m_contract_strides
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, int Alignment, template< class > class MakePointer_ = MakePointer> const contract_t Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_contract_strides protected
Referenced by Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::computeIndex(), Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::computeIndexPair(), Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::contract_strides(), and Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::stride().
m_ij_strides
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, int Alignment, template< class > class MakePointer_ = MakePointer> const nocontract_t Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_ij_strides protected
Referenced by Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::computeIndex(), Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::computeIndexPair(), and Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::ij_strides().
m_k_strides
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, int Alignment, template< class > class MakePointer_ = MakePointer> const contract_t Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_k_strides protected
Referenced by Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::computeIndex(), Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::computeIndexPair(), and Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::k_strides().
m_nocontract_strides
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, int Alignment, template< class > class MakePointer_ = MakePointer> const nocontract_t Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_nocontract_strides protected
Referenced by Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::computeIndex(), Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::computeIndexPair(), and Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::nocontract_strides().
m_tensor
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, int Alignment, template< class > class MakePointer_ = MakePointer> CoeffLoader<Tensor, Tensor::RawAccess, MakePointer_> Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_tensor protected
Referenced by Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::offsetBuffer(), Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::operator()(), and Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::tensor().
The documentation for this class was generated from the following file:
TensorContractionMapper.h