MercuryDPM: oomph::deriv_functions::OrderReductionTest Class Reference
oomph::deriv_functions::OrderReductionTest Class Reference
Another stiff solution: Atkinson pg. 158, also example 8.2 pg 129.
#include <ode_example_functions.h>
Public Member Functions
OrderReductionTest ()
Constructor.
virtual ~OrderReductionTest ()
Virtual destructor.
Vector< double > operator() (const double &t, const Vector< double > &x) const
Function call.
Vector< double > derivative (const double &t, const Vector< double > &x, const Vector< double > &u) const
Derivative call.
Public Member Functions inherited from oomph::SolutionFunctorBase
virtual ~SolutionFunctorBase ()
Virtual destructor.
virtual void jacobian (const double &t, const Vector< double > &x, const Vector< double > &u, DenseMatrix< double > &jacobian) const
virtual bool have_jacobian () const
Is a jacobian function implemented?
virtual void initialise_from_problem (const Problem *problem_pt)
Overload to grab data from the problem.
Public Attributes
double Lambda
Additional Inherited Members
Public Types inherited from oomph::SolutionFunctorBase
typedef double(* TimeSpaceToDoubleFctPt) (const double &t, const Vector< double > &x)
General function of space and time which returns a double.
typedef Vector< double >(* TimeSpaceToDoubleVectFctPt) (const double &t, const Vector< double > &x)
General function of space and time which returns a vector of doubles.
typedef Vector< double >(* TimeSpaceValueToDoubleVectFctPt) (const double &t, const Vector< double > &x, const Vector< double > &u)
Detailed Description
Another stiff solution: Atkinson pg. 158, also example 8.2 pg 129.
Constructor & Destructor Documentation
OrderReductionTest()
oomph::deriv_functions::OrderReductionTest::OrderReductionTest () inline
Constructor.
    {
     Lambda = -100;
    }
References Global_Parameters::Lambda.
~OrderReductionTest()
virtual oomph::deriv_functions::OrderReductionTest::~OrderReductionTest () inline virtual
Virtual destructor.
 {}
Member Function Documentation
derivative()
Vector<double> oomph::deriv_functions::OrderReductionTest::derivative (const double & t, const Vector< double > & x, const Vector< double > & u) const inline virtual
Derivative call.
Implements oomph::SolutionFunctorBase.
    {
     Vector<double> deriv(1, 0.0);
     deriv[0] = Lambda*u[0] - Lambda*std::sin(t) + std::cos(t);
     return deriv;
    }
References cos(), Global_Parameters::Lambda, sin(), and plotPSD::t.
operator()()
Vector<double> oomph::deriv_functions::OrderReductionTest::operator() (const double & t, const Vector< double > & x) const inline virtual
Function call.
Implements oomph::SolutionFunctorBase.
    {
     Vector<double> values(1);
     values[0] = std::sin(t);
     return values;
    }
References sin(), and plotPSD::t.
Member Data Documentation
Lambda
double oomph::deriv_functions::OrderReductionTest::Lambda
The documentation for this class was generated from the following file:
ode_example_functions.h