MercuryDPM: CGStandardDeviationUnitTest.cpp File Reference
CGStandardDeviationUnitTest.cpp File Reference
#include <Walls/InfiniteWall.h>
#include <CG/Functions/Linear.h>
#include "Mercury3D.h"
#include "CG/CG.h"
#include "Species/LinearViscoelasticSpecies.h"
Functions
int main ()
Function Documentation
main()
int main ()
 {
     logger(INFO," Checking setting the standard deviation of cg functions");
     {
         CG<CGCoordinates::X, CGFunctions::Heaviside> X;
         X.setStandardDeviation(1);
         helpers::check(X.getFunction().getCutoff(),constants::sqrt_3,1e-11, "Cutoff of 1D Heaviside with unit variance");
         CG<CGCoordinates::XY, CGFunctions::Heaviside> XY;
         XY.setStandardDeviation(1);
         helpers::check(XY.getFunction().getCutoff(),constants::sqrt_2,1e-11, "Cutoff of 2D Heaviside with unit variance");
         CG<CGCoordinates::XYZ, CGFunctions::Heaviside> XYZ;
         XYZ.setStandardDeviation(1);
         helpers::check(XYZ.getFunction().getCutoff(),sqrt(5./3.),1e-11, "Cutoff of 3D Heaviside with unit variance");
     }
     {
         CG<CGCoordinates::X, CGFunctions::Lucy> X;
         X.setStandardDeviation(1);
         helpers::check(X.getFunction().getCutoff(),sqrt(10.5),1e-11, "Cutoff of 1D Lucy with unit variance");
         CG<CGCoordinates::XY, CGFunctions::Lucy> XY;
         XY.setStandardDeviation(1);
         helpers::check(XY.getFunction().getCutoff(),sqrt(5.6),1e-11, "Cutoff of 2D Lucy with unit variance");
         CG<CGCoordinates::XYZ, CGFunctions::Lucy> XYZ;
         XYZ.setStandardDeviation(1);
         helpers::check(XYZ.getFunction().getCutoff(),2,1e-11, "Cutoff of 3D Lucy with unit variance");
     }
     {
         CG<CGCoordinates::X,CGFunctions::Gauss> X;
         X.setStandardDeviation(1);
         helpers::check(X.getFunction().getCutoff(),3,1e-11, "Cutoff of 1D Gauss with unit variance");
         CG<CGCoordinates::XY,CGFunctions::Gauss> XY;
         XY.setStandardDeviation(1);
         helpers::check(XY.getFunction().getCutoff(),3/sqrt(2),1e-11, "Cutoff of 2D Gauss with unit variance");
         CG<CGCoordinates::XYZ,CGFunctions::Gauss> XYZ;
         XYZ.setStandardDeviation(1);
         helpers::check(XYZ.getFunction().getCutoff(),3/sqrt(3),1e-11, "Cutoff of 3D Gauss with unit variance");
     }
     {
         CG<CGCoordinates::X, CGFunctions::Heaviside> X;
         X.setRadius(1);
         helpers::check(X.getFunction().getCutoff(),constants::sqrt_3*sqrt(.2),1e-11, "Cutoff of 1D Heaviside with unit radius-equivalent");
         CG<CGCoordinates::XY, CGFunctions::Heaviside> XY;
         XY.setRadius(1);
         helpers::check(XY.getFunction().getCutoff(),constants::sqrt_2*sqrt(.4),1e-11, "Cutoff of 2D Heaviside with unit radius-equivalent");
         CG<CGCoordinates::XYZ, CGFunctions::Heaviside> XYZ;
         XYZ.setRadius(1);
         helpers::check(XYZ.getFunction().getCutoff(),sqrt(5./3.)*sqrt(.6),1e-11, "Cutoff of 3D Heaviside with unit radius-equivalent");
     }
     {
         CG<CGCoordinates::X, CGFunctions::Linear> X;
         X.setRadius(1);
         helpers::check(X.getFunction().getCutoff(),sqrt(6)*sqrt(.2),1e-11, "Cutoff of 1D Linear with unit radius-equivalent");
         CG<CGCoordinates::XY, CGFunctions::Linear> XY;
         XY.setRadius(1);
         helpers::check(XY.getFunction().getCutoff(),sqrt(10./3)*sqrt(.4),1e-11, "Cutoff of 2D Linear with unit radius-equivalent");
         CG<CGCoordinates::XYZ, CGFunctions::Linear> XYZ;
         XYZ.setRadius(1);
         helpers::check(XYZ.getFunction().getCutoff(),sqrt(5./2)*sqrt(.6),1e-11, "Cutoff of 3D Linear with unit radius-equivalent");
     }
     {
         CG<CGCoordinates::X, CGFunctions::Lucy> X;
         X.setRadius(1);
         helpers::check(X.getFunction().getCutoff(),sqrt(10.5)*sqrt(.2),1e-11, "Cutoff of 1D Lucy with unit radius-equivalent");
         CG<CGCoordinates::XY, CGFunctions::Lucy> XY;
         XY.setRadius(1);
         helpers::check(XY.getFunction().getCutoff(),sqrt(5.6)*sqrt(.4),1e-11, "Cutoff of 2D Lucy with unit radius-equivalent");
         CG<CGCoordinates::XYZ, CGFunctions::Lucy> XYZ;
         XYZ.setRadius(1);
         helpers::check(XYZ.getFunction().getCutoff(),2*sqrt(.6),1e-11, "Cutoff of 3D Lucy with unit radius-equivalent");
     }
     {
         CG<CGCoordinates::X,CGFunctions::Gauss> X;
         X.setRadius(1);
         helpers::check(X.getFunction().getCutoff(),3*sqrt(.2),1e-11, "Cutoff of 1D Gauss with unit radius-equivalent");
         CG<CGCoordinates::XY,CGFunctions::Gauss> XY;
         XY.setRadius(1);
         helpers::check(XY.getFunction().getCutoff(),3/sqrt(2)*sqrt(.4),1e-11, "Cutoff of 2D Gauss with unit radius-equivalent");
         CG<CGCoordinates::XYZ,CGFunctions::Gauss> XYZ;
         XYZ.setRadius(1);
         helpers::check(XYZ.getFunction().getCutoff(),3/sqrt(3)*sqrt(.6),1e-11, "Cutoff of 3D Gauss with unit radius-equivalent");
     }
     return 0;
 }
References helpers::check(), e(), INFO, logger, sqrt(), constants::sqrt_2, constants::sqrt_3, X, XY, and XYZ.