MercuryDPM: oomph::SolutionFunctorBase Class Reference
oomph::SolutionFunctorBase Class Reference abstract
#include <oomph_utilities.h>
Public Types
typedef double(* TimeSpaceToDoubleFctPt) (const double &t, const Vector< double > &x)
General function of space and time which returns a double.
typedef Vector< double >(* TimeSpaceToDoubleVectFctPt) (const double &t, const Vector< double > &x)
General function of space and time which returns a vector of doubles.
typedef Vector< double >(* TimeSpaceValueToDoubleVectFctPt) (const double &t, const Vector< double > &x, const Vector< double > &u)
Public Member Functions
virtual ~SolutionFunctorBase ()
Virtual destructor.
virtual Vector< double > operator() (const double &t, const Vector< double > &x) const =0
Call the function.
virtual Vector< double > derivative (const double &t, const Vector< double > &x, const Vector< double > &u) const =0
Call the derivative function.
virtual void jacobian (const double &t, const Vector< double > &x, const Vector< double > &u, DenseMatrix< double > &jacobian) const
virtual bool have_jacobian () const
Is a jacobian function implemented?
virtual void initialise_from_problem (const Problem *problem_pt)
Overload to grab data from the problem.
Detailed Description
Function base class for exact solutions/initial conditions/boundary conditions. This is needed so that we can have solutions that depend on problem parameters with resorting to global variables.
Member Typedef Documentation
TimeSpaceToDoubleFctPt
typedef double(* oomph::SolutionFunctorBase::TimeSpaceToDoubleFctPt) (const double &t, const Vector< double > &x)
General function of space and time which returns a double.
TimeSpaceToDoubleVectFctPt
typedef Vector<double>(* oomph::SolutionFunctorBase::TimeSpaceToDoubleVectFctPt) (const double &t, const Vector< double > &x)
General function of space and time which returns a vector of doubles.
TimeSpaceValueToDoubleVectFctPt
typedef Vector<double>(* oomph::SolutionFunctorBase::TimeSpaceValueToDoubleVectFctPt) (const double &t, const Vector< double > &x, const Vector< double > &u)
General function of time, space and a value vector which returns a vector of doubles.
Constructor & Destructor Documentation
~SolutionFunctorBase()
virtual oomph::SolutionFunctorBase::~SolutionFunctorBase () inline virtual
Virtual destructor.
 {}
Member Function Documentation
derivative()
virtual Vector<double> oomph::SolutionFunctorBase::derivative (const double & t, const Vector< double > & x, const Vector< double > & u) const pure virtual
Call the derivative function.
Implemented in oomph::SolutionFunctor, oomph::deriv_functions::OrderReductionTest, oomph::deriv_functions::SimpleStiffTest, and oomph::deriv_functions::DampedOscillation.
Referenced by oomph::ODEElement::derivative_function().
have_jacobian()
virtual bool oomph::SolutionFunctorBase::have_jacobian () const inline virtual
Is a jacobian function implemented?
     {
       return false;
     }
Referenced by oomph::IMRODEElement::fill_in_contribution_to_jacobian(), and oomph::ODEElement::fill_in_contribution_to_jacobian().
initialise_from_problem()
virtual void oomph::SolutionFunctorBase::initialise_from_problem (const Problem * problem_pt) inline virtual
Overload to grab data from the problem.
 {}
jacobian()
virtual void oomph::SolutionFunctorBase::jacobian (const double & t, const Vector< double > & x, const Vector< double > & u, DenseMatrix< double > & jacobian) const inline virtual
The derivatives of the derivative function with respect to u (note that this is not quite the jacobian of the residuals for an ODE problem defined by this solution: you also need the time derivative part there). Broken virtual function because not often needed.
     {
       std::string err = "No Jacobian function implemented";
       throw OomphLibError(
         err, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
Referenced by oomph::IMRODEElement::fill_in_contribution_to_jacobian(), and oomph::ODEElement::fill_in_contribution_to_jacobian().
operator()()
virtual Vector<double> oomph::SolutionFunctorBase::operator() (const double & t, const Vector< double > & x) const pure virtual
Call the function.
Implemented in oomph::SolutionFunctor, oomph::deriv_functions::OrderReductionTest, oomph::deriv_functions::SimpleStiffTest, and oomph::deriv_functions::DampedOscillation.
The documentation for this class was generated from the following file:
oomph_utilities.h