MercuryDPM: Eigen::Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType > Class Template Reference
Eigen::Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType > Class Template Reference
Sparse linear algebra » Reference » SparseCore_Module
A sparse vector expression referencing an existing sparse vector expression.
#include <SparseRef.h>
Public Types
typedef internal::SparseRefBase< Ref > Base
Public Types inherited from Eigen::internal::SparseRefBase< Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType > >
typedef SparseMapBase< Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType > > Base
Public Member Functions
template<int OtherOptions>
Ref (SparseVector< MatScalar, OtherOptions, MatIndex > &expr)
template<typename Derived >
Ref (const SparseCompressedBase< Derived > &expr)
Public Member Functions inherited from Eigen::internal::SparseRefBase< Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType > >
SparseRefBase ()
Private Types
typedef SparseVector< MatScalar, MatOptions, MatIndex > PlainObjectType
typedef internal::traits< Ref > Traits
Private Member Functions
template<int OtherOptions>
Ref (const SparseVector< MatScalar, OtherOptions, MatIndex > &expr)
Additional Inherited Members
Protected Member Functions inherited from Eigen::internal::SparseRefBase< Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType > >
void construct (Expression &expr)
Detailed Description
template<typename MatScalar, int MatOptions, typename MatIndex, int Options, typename StrideType>
class Eigen::Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >
A sparse vector expression referencing an existing sparse vector expression.
Template Parameters
SparseVectorType the equivalent sparse vector type of the referenced data, it must be a template instance of class SparseVector.
See also
class Ref
Member Typedef Documentation
Base
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > typedef internal::SparseRefBase<Ref> Eigen::Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Base
PlainObjectType
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > typedef SparseVector<MatScalar, MatOptions, MatIndex> Eigen::Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::PlainObjectType private
Traits
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > typedef internal::traits<Ref> Eigen::Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Traits private
Constructor & Destructor Documentation
Ref() [1/3]
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > template<int OtherOptions> Eigen::Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref (const SparseVector< MatScalar, OtherOptions, MatIndex > & expr) inline private
Ref() [2/3]
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > template<int OtherOptions> Eigen::Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref (SparseVector< MatScalar, OtherOptions, MatIndex > & expr) inline
{
     EIGEN_STATIC_ASSERT(
         bool(Traits::template match<SparseVector<MatScalar, OtherOptions, MatIndex>>::MatchAtCompileTime),
         STORAGE_LAYOUT_DOES_NOT_MATCH);
     Base::construct(expr.derived());
   }
References Eigen::RefBase< Derived >::construct(), Eigen::SparseMatrixBase< Derived >::derived(), EIGEN_STATIC_ASSERT, and match().
Ref() [3/3]
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > template<typename Derived > Eigen::Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref (const SparseCompressedBase< Derived > & expr) inline
   {
     EIGEN_STATIC_ASSERT(bool(internal::is_lvalue<Derived>::value), THIS_EXPRESSION_IS_NOT_A_LVALUE__IT_IS_READ_ONLY);
     EIGEN_STATIC_ASSERT(bool(Traits::template match<Derived>::MatchAtCompileTime), STORAGE_LAYOUT_DOES_NOT_MATCH);
     Base::construct(expr.const_cast_derived());
   }
References Eigen::SparseMatrixBase< Derived >::const_cast_derived(), Eigen::RefBase< Derived >::construct(), and EIGEN_STATIC_ASSERT.
The documentation for this class was generated from the following file:
SparseRef.h