MercuryDPM: prescribed_displ_lagr_mult.cc File Reference
mpi/distribution/prescribed_displ_lagr_mult/prescribed_displ_lagr_mult.cc File Reference
#include "generic.h"
#include "solid.h"
#include "constitutive.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class FiniteElementComp
class WarpedLine
Warped line in 2D space.
class PrescribedBoundaryDisplacementProblem< ELEMENT >
Namespaces
Global_Physical_Variables
Global variables.
Functions
int main (int argc, char *argv[])
Driver code.
Variables
WarpedLine Global_Physical_Variables::Boundary_geom_object (0.0)
GeomObject specifying the shape of the boundary: Initially it's flat.
Function Documentation
main()
int main (int argc , char * argv[])
Driver code.
 {
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::init(argc,argv);
 #endif
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Validation run?
  CommandLineArgs::specify_command_line_flag("--validation");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  //Set up the problem
  PrescribedBoundaryDisplacementProblem<RefineableQPVDElement<2,3> > problem;
  // Validation run
  if (CommandLineArgs::command_line_flag_has_been_set("--validation"))
   {
    // Fake but repeatable load balancing for self-test
    problem.set_default_partition_in_load_balance();
   }
 #ifdef OOMPH_HAS_MPI
  // Distribute the problem
  DocInfo mesh_doc_info;
  mesh_doc_info.set_directory("RESLT");
  mesh_doc_info.number()=38;
  std::ifstream input_file;
  std::ofstream output_file;
  char filename[100];
  unsigned n_partition=problem.mesh_pt()->nelement();
  // Get the partition from file
  Vector<unsigned> element_partition(n_partition);
  sprintf(filename,"presc_displ_lagr_mult_partition.dat");
  input_file.open(filename);
  std::string input_string;
  for (unsigned e=0;e<n_partition;e++)
   {
    getline(input_file,input_string,'\n');
    element_partition[e]=atoi(input_string.c_str());
   }
  // Distribute and check halo schemes
  bool report_stats=false;
  problem.distribute(element_partition,mesh_doc_info,report_stats);
  problem.check_halo_schemes(mesh_doc_info);
 #endif
  // Doc initial domain shape
  problem.doc_solution();
  // Max. number of adaptations per solve
  unsigned max_adapt=1;
  //Parameter incrementation
  unsigned nstep=2;
  for(unsigned i=0;i<nstep;i++)
   {
    // Increment imposed boundary displacement
    Global_Physical_Variables::Boundary_geom_object.ampl()+=0.1;
    // Solve the problem with Newton's method, allowing
    // up to max_adapt mesh adaptations after every solve.
    problem.newton_solve(max_adapt);
    // Doc solution
    problem.doc_solution();
    // For maximum stability: Reset the current nodal positions to be
    // the "stress-free" ones -- this assignment means that the
    // parameter study no longer corresponds to a physical experiment
    // but is what we'd do if we wanted to use the solid solve
    // to update a fluid mesh in an FSI problem, say.
    problem.solid_mesh_pt()->set_lagrangian_nodal_coordinates();
   }
  oomph_info << "Load balancing \n";
  // Load balance and re-solve without further adaptation
  problem.load_balance();
  problem.newton_solve();
  // Doc solution
  problem.doc_solution();
  // Increment imposed boundary displacement yet again...
  Global_Physical_Variables::Boundary_geom_object.ampl()+=0.1;
  // ...and re-solve for a final time
  problem.newton_solve();
  // Doc solution
  problem.doc_solution();
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::finalize();
 #endif
 } //end of main
References WarpedLine::ampl(), Global_Physical_Variables::Boundary_geom_object, oomph::CommandLineArgs::command_line_flag_has_been_set(), oomph::CommandLineArgs::doc_specified_flags(), e(), MergeRestartFiles::filename, i, oomph::DocInfo::number(), oomph::oomph_info, oomph::CommandLineArgs::parse_and_assign(), problem, oomph::DocInfo::set_directory(), Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), and oomph::Global_string_for_annotation::string().