MercuryDPM: oomph::ErrorEstimator Class Reference
oomph::ErrorEstimator Class Reference abstract
Base class for spatial error estimators.
#include <error_estimator.h>
Public Member Functions
ErrorEstimator ()
Default empty constructor.
ErrorEstimator (const ErrorEstimator &)=delete
Broken copy constructor.
void operator= (const ErrorEstimator &)=delete
Broken assignment operator.
virtual ~ErrorEstimator ()
Empty virtual destructor.
void get_element_errors (Mesh *&mesh_pt, Vector< double > &elemental_error)
virtual void get_element_errors (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)=0
Detailed Description
Base class for spatial error estimators.
Constructor & Destructor Documentation
ErrorEstimator() [1/2]
oomph::ErrorEstimator::ErrorEstimator () inline
Default empty constructor.
 {}
ErrorEstimator() [2/2]
oomph::ErrorEstimator::ErrorEstimator (const ErrorEstimator &) delete
Broken copy constructor.
~ErrorEstimator()
virtual oomph::ErrorEstimator::~ErrorEstimator () inline virtual
Empty virtual destructor.
 {}
Member Function Documentation
get_element_errors() [1/2]
void oomph::ErrorEstimator::get_element_errors (Mesh *& mesh_pt, Vector< double > & elemental_error) inline
Compute the elemental error-measures for a given mesh and store them in a vector.
     {
       // Create dummy doc info object and switch off output
       DocInfo doc_info;
       doc_info.disable_doc();
       // Forward call to version with doc.
       get_element_errors(mesh_pt, elemental_error, doc_info);
     }
References oomph::DocInfo::disable_doc().
Referenced by AxisymmetricVibratingShellProblem< ELEMENT >::compute_error_estimate(), VibratingShellProblem< ELEMENT >::compute_error_estimate(), TwoLayerInterfaceProblem< ELEMENT >::compute_error_estimate(), UnstructuredFluidProblem< ELEMENT >::compute_error_estimate(), BubbleInChannelProblem< ELEMENT >::compute_error_estimate(), DropInChannelProblem< ELEMENT >::compute_error_estimate(), and oomph::METIS::partition_mesh().
get_element_errors() [2/2]
virtual void oomph::ErrorEstimator::get_element_errors (Mesh *& mesh_pt, Vector< double > & elemental_error, DocInfo & doc_info) pure virtual
Compute the elemental error measures for a given mesh and store them in a vector. Doc errors etc.
Implemented in oomph::DummyErrorEstimator, and oomph::Z2ErrorEstimator.
operator=()
void oomph::ErrorEstimator::operator= (const ErrorEstimator &) delete
Broken assignment operator.
The documentation for this class was generated from the following file:
error_estimator.h