MercuryDPM: cxx11_tensor_lvalue.cpp File Reference
cxx11_tensor_lvalue.cpp File Reference
#include "main.h"
#include <Eigen/CXX11/Tensor>
Functions
static void test_compound_assignment ()
EIGEN_DECLARE_TEST (cxx11_tensor_lvalue)
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (cxx11_tensor_lvalue)
 { CALL_SUBTEST(test_compound_assignment()); }
References CALL_SUBTEST, and test_compound_assignment().
test_compound_assignment()
static void test_compound_assignment () static
{
   Tensor<float, 3> mat1(2, 3, 7);
   Tensor<float, 3> mat2(2, 3, 7);
   Tensor<float, 3> mat3(2, 3, 7);
   mat1.setRandom();
   mat2.setRandom();
   mat3 = mat1;
   mat3 += mat2;
   for (int i = 0; i < 2; ++i) {
     for (int j = 0; j < 3; ++j) {
       for (int k = 0; k < 7; ++k) {
         VERIFY_IS_APPROX(mat3(i, j, k), mat1(i, j, k) + mat2(i, j, k));
       }
     }
   }
 }
References i, j, k, mat1(), Eigen::TensorBase< Derived, AccessLevel >::setRandom(), and VERIFY_IS_APPROX.
Referenced by EIGEN_DECLARE_TEST().