MercuryDPM: falling_jet.cc File Reference
falling_jet.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "fluid_interface.h"
#include "solid.h"
#include "constitutive.h"
#include "meshes/quarter_tube_mesh.h"
Classes
class ElasticQuarterTubeMesh< ELEMENT >
Simple quarter tube mesh upgraded to become a solid mesh.
class EntryFlowProblem< ELEMENT >
Entry flow problem in quarter tube domain.
Namespaces
Global_Physical_Variables
Global variables.
Functions
int main (int argc, char *argv[])
Variables
Vector< double > Global_Physical_Variables::G (3) = 1.0
Direction of gravity.
Function Documentation
main()
int main (int argc , char * argv[])
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Driver for 3D entry flow into a quarter tube. If there are any command line arguments, we regard this as a validation run and perform only a single adaptation
 {
  //Set the gravity direction
  Global_Physical_Variables::G[0] = 0.0;
  Global_Physical_Variables::G[1] = 0.0;
  Global_Physical_Variables::G[2] = -1.0;
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Allow (up to) five rounds of fully automatic adapation in response to
  //-----------------------------------------------------------------------
  // error estimate
  //---------------
  //unsigned max_adapt;
  double max_error_target,min_error_target;
  // Set max number of adaptations in black-box Newton solver and
  // error targets for adaptation
  if (CommandLineArgs::Argc==1)
   {
    // Up to five adaptations
    //max_adapt=5;
    // Error targets for adaptive refinement
    max_error_target=0.005;
    min_error_target=0.0005;
   }
  // Validation run: Only one adaptation. Relax error targets
  // to ensure that not all elements are refined so we're getting
  // some hanging nodes.
  else
   {
    // Validation run: Just one round of adaptation
    //max_adapt=1;
    // Error targets for adaptive refinement
    max_error_target=0.02;
    min_error_target=0.002;
   }
  // end max_adapt setup
  // Set up doc info
  DocInfo doc_info;
  // Do Taylor-Hood elements
  //------------------------
  {
   // Set output directory
   doc_info.set_directory("RESLT_TH");
   // Step number
   doc_info.number()=0;
   // Build problem
   EntryFlowProblem<
    RefineablePseudoSolidNodeUpdateElement<
    RefineableQTaylorHoodElement<3>,
    RefineableQPVDElement<3,3> > >
    problem(doc_info,min_error_target,max_error_target);
   cout << " Doing Taylor-Hood elements " << std::endl;
   // Doc solution before solving
   problem.doc_solution();
   // Solve the problem
   for(unsigned i=0;i<2;i++)
    {
     problem.newton_solve();//max_adapt);
     Global_Physical_Variables::St += 0.5;
    }
 }
  // Do Crouzeix-Raviart elements
  //-----------------------------
  {
   // Set output directory
   doc_info.set_directory("RESLT_CR");
   // Step number
   doc_info.number()=0;
   //Reset the Stokes number to zero
   Global_Physical_Variables::St = 0.0;
   // Build problem
   EntryFlowProblem<
    RefineablePseudoSolidNodeUpdateElement<
    RefineableQCrouzeixRaviartElement<3>,
    RefineableQPVDElement<3,3> > >
    problem(doc_info,min_error_target,max_error_target);
   cout << " Doing Crouzeix-Raviart elements " << std::endl;
   // Doc solution before solving
   problem.doc_solution();
   // Solve the problem
   for(unsigned i=0;i<2;i++)
    {
     problem.newton_solve();//max_adapt);
     Global_Physical_Variables::St += 0.5;
    }
   }
 } // end_of_main
References oomph::CommandLineArgs::Argc, Global_Physical_Variables::G, i, oomph::DocInfo::number(), problem, oomph::DocInfo::set_directory(), Flag_definition::setup(), and Global_Physical_Variables::St.