MercuryDPM: FlatPlate Class Reference
FlatPlate Class Reference
Flat plate in x-y plane.
Public Member Functions
FlatPlate ()
Constructor:
FlatPlate (const FlatPlate &node)
Broken copy constructor.
void operator= (const FlatPlate &)
Broken assignment operator.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
Position vector (dummy unsteady version returns steady version)
virtual unsigned ngeom_data () const
How many items of Data does the shape of the object depend on?
void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Position Vector and 1st and 2nd derivs w.r.t. zeta.
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual Data * geom_data_pt (const unsigned &j)
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Additional Inherited Members
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
Flat plate in x-y plane.
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
FlatPlate() [1/2]
FlatPlate::FlatPlate () inline
Constructor:
 :  GeomObject(2,3) {}
FlatPlate() [2/2]
FlatPlate::FlatPlate (const FlatPlate & node) inline
Broken copy constructor.
   {
    BrokenCopy::broken_copy("FlatPlate");
   }
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
d2position()
void FlatPlate::d2position (const Vector< double > & zeta, Vector< double > & r, DenseMatrix< double > & drdzeta, RankThreeTensor< double > & ddrdzeta) const inline virtual
Position Vector and 1st and 2nd derivs w.r.t. zeta.
Reimplemented from oomph::GeomObject.
   {
    //Flat plate
    r[0] = zeta[0];
    r[1] = zeta[1];
    r[2] = 0.0;
    //Do the zeta0 derivatives
    drdzeta(0,0) = 1.0;
    drdzeta(0,1) = 0.0;
    drdzeta(0,2) = 0.0;
    //Do the zeta 1 derivatives
    drdzeta(1,0) = 0.0;
    drdzeta(1,1) = 1.0;
    drdzeta(1,2) = 0.0;
    //Now let's do the second derivatives
    ddrdzeta(0,0,0) = 0.0;
    ddrdzeta(0,0,1) = 0.0;
    ddrdzeta(0,0,2) = 0.0;
    ddrdzeta(1,1,0) = 0.0;
    ddrdzeta(1,1,1) = 0.0;
    ddrdzeta(1,1,2) = 0.0;
    //Mixed derivatives
    ddrdzeta(0,1,0) = 0.0;
    ddrdzeta(0,1,1) = 0.0;
    ddrdzeta(0,1,2) = 0.0;
   }
References UniformPSDSelfTest::r, and Eigen::zeta().
ngeom_data()
virtual unsigned FlatPlate::ngeom_data () const inline virtual
How many items of Data does the shape of the object depend on?
Reimplemented from oomph::GeomObject.
   {
    return 0;
   }
operator=()
void FlatPlate::operator= (const FlatPlate &) inline
Broken assignment operator.
   {
    BrokenCopy::broken_assign("FlatPlate");
   }
References oomph::BrokenCopy::broken_assign().
position() [1/2]
void FlatPlate::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector (dummy unsteady version returns steady version)
Reimplemented from oomph::GeomObject.
   {
    position(zeta,r);
   }
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [2/2]
void FlatPlate::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector.
Implements oomph::GeomObject.
   {
    r[0]=zeta[0];
    r[1]=zeta[1];
    r[2]=0.0;
   }
References UniformPSDSelfTest::r, and Eigen::zeta().
The documentation for this class was generated from the following file:
plate.cc