MercuryDPM: flow_past_oscillating_cylinder.cc File Reference
flow_past_oscillating_cylinder.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "meshes/rectangle_with_moving_cylinder_mesh.h"
#include <limits>
Classes
class oomph::MyRefineableQTaylorHoodElement
Overloaded element that allows projection of use as PML element.
class oomph::PMLLayerElement< MyRefineableQTaylorHoodElement >
Policy class defining the elements to be used in the PML layers. Same!
class oomph::FaceGeometry< MyRefineableQTaylorHoodElement >
class OscillatingCylinder
Oscillating cylinder class.
class FlowAroundCylinderProblem< ELEMENT >
Flow around a cylinder in rectangular domain.
Namespaces
oomph
DRAIG: Change all instances of (SPATIAL_DIM) to (DIM-1).
GlobalParameters
Global parameters.
Functions
double GlobalParameters::calculate_strouhal_number (const double &re)
void GlobalParameters::update_simulation_parameters ()
void GlobalParameters::doc_navier_stokes_parameters ()
Document the value of the Reynolds number and Womersley number.
void GlobalParameters::doc_maximum_central_box_deformation ()
Document the maximum deformation inside the central box.
double GlobalParameters::round (const double &d)
---------------------------------------—DOCUMENTATION HELPERS---—
int main (int argc, char **argv)
Driver.
Variables
double GlobalParameters::Period_ratio =1.0
The ratio T_e/T_s.
double GlobalParameters::Re_target =20.0
Reynolds number for unsteady run.
double GlobalParameters::St =1.0
The default Strouhal number (overloaded with input value if given)
double GlobalParameters::ReSt =Re*St
The Womersley number.
unsigned GlobalParameters::N_period_unsteady =1
------------------------------------—NAVIER-STOKES PARAMETERS---—
unsigned GlobalParameters::N_step_per_period_unsteady =100
Number of timesteps per period for unsteady run.
double GlobalParameters::Height =20.0
Height of domain.
double GlobalParameters::X_left =-10.0
X-coordinate of upstream end of domain.
double GlobalParameters::X_right =40.0
X-coordinate of downstream end of domain.
double GlobalParameters::Length_of_central_box =10.0
Side-length of the square box in the mesh surrounding the cylinder.
unsigned GlobalParameters::N_plot_point =2
-------------------------------------------—DOMAIN PROPERTIES---—
Function Documentation
main()
int main (int argc , char ** argv)
Driver.
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
 {
 #ifdef OOMPH_HAS_MPI
   // Initialise MPI
   MPI_Helpers::init(argc,argv);
   // Switch off output modifier
   oomph_info.output_modifier_pt()=&default_output_modifier;
   // Switch off oomph_info output for all processors but rank 0
   if (MPI_Helpers::communicator_pt()->my_rank()!=0)
   {
     oomph_info.stream_pt()=&oomph_nullstream;
     OomphLibWarning::set_stream_pt(&oomph_nullstream);
     OomphLibError::set_stream_pt(&oomph_nullstream);
   }
   else
   {
     oomph_info << "\n\n====================================================\n"
                << "Number of processors: "
                << MPI_Helpers::communicator_pt()->nproc()
                << "\n====================================================\n"
                << std::endl;
   }
 #endif
   // Start the timer
   double timer_s=TimingHelpers::timer();
   // Generic update function that calls all the appropriate update functions
   GlobalParameters::update_simulation_parameters();
   // Output directory
   GlobalParameters::Doc_info.set_directory("RESLT");
   // Build the problem
   FlowAroundCylinderProblem<MyRefineableQTaylorHoodElement> problem;
   // Refine the problem a couple of times
   for (unsigned i=0; i<GlobalParameters::N_uniform_refinement_before_solve; i++)
   {
     // Refine uniformly
     problem.refine_uniformly();
   }
   // Number of steps to increment the Reynolds number to the target value
   unsigned n_re_step=1;
   // Calculate the increment required to get to the Reynolds number
   double re_increment=GlobalParameters::Re_target/n_re_step;
   //-----------------------------
   // Crank up the Reynolds number
   //-----------------------------
   // Loop over the Reynolds increments
   for (unsigned i=0; i<n_re_step+1; i++)
   {
     // Calculate the Reynolds number
     GlobalParameters::Re=double(i)*re_increment;
     // Update the Womersley number
     GlobalParameters::update_simulation_parameters();
     // Output the current N.St. parameter values
     GlobalParameters::doc_navier_stokes_parameters();
     // Solve the problem
     problem.newton_solve();
   }
   // Document the solution
   problem.doc_solution();
   //------------------------------
   // Start the unsteady simulation
   //------------------------------
   // Run the simulation
   problem.unsteady_simulation();
   // Document the solution
   problem.doc_solution(true);
   // Tell the user we're done and how long the whole thing took
   oomph_info << "\nUnsteady simulation complete!"
              << "\nTotal time for full simulation [sec]: "
              << TimingHelpers::timer()-timer_s << "\n" << std::endl;
 }
References oomph::default_output_modifier, GlobalParameters::Doc_info, GlobalParameters::doc_navier_stokes_parameters(), i, GlobalParameters::N_uniform_refinement_before_solve, oomph::oomph_info, oomph::oomph_nullstream, oomph::OomphInfo::output_modifier_pt(), problem, GlobalParameters::Re, GlobalParameters::Re_target, oomph::DocInfo::set_directory(), oomph::OomphInfo::stream_pt(), and GlobalParameters::update_simulation_parameters().