MercuryDPM: Eigen::internal::last_row_process_16_packets< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs, 16 > Struct Template Reference
Eigen::internal::last_row_process_16_packets< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs, 16 > Struct Template Reference
#include <GeneralBlockPanelKernel.h>
Public Types
typedef gebp_traits< LhsScalar, RhsScalar, ConjugateLhs, ConjugateRhs, Architecture::Target > Traits
typedef gebp_traits< RhsScalar, LhsScalar, ConjugateRhs, ConjugateLhs, Architecture::Target > SwappedTraits
typedef Traits::ResScalar ResScalar
typedef SwappedTraits::LhsPacket SLhsPacket
typedef SwappedTraits::RhsPacket SRhsPacket
typedef SwappedTraits::ResPacket SResPacket
typedef SwappedTraits::AccPacket SAccPacket
Public Member Functions
EIGEN_STRONG_INLINE void operator() (const DataMapper &res, SwappedTraits &straits, const LhsScalar *blA, const RhsScalar *blB, Index depth, const Index endk, Index i, Index j2, ResScalar alpha, SAccPacket &C0)
Member Typedef Documentation
ResScalar
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef Traits::ResScalar Eigen::internal::last_row_process_16_packets< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs, 16 >::ResScalar
SAccPacket
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef SwappedTraits::AccPacket Eigen::internal::last_row_process_16_packets< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs, 16 >::SAccPacket
SLhsPacket
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef SwappedTraits::LhsPacket Eigen::internal::last_row_process_16_packets< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs, 16 >::SLhsPacket
SResPacket
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef SwappedTraits::ResPacket Eigen::internal::last_row_process_16_packets< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs, 16 >::SResPacket
SRhsPacket
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef SwappedTraits::RhsPacket Eigen::internal::last_row_process_16_packets< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs, 16 >::SRhsPacket
SwappedTraits
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef gebp_traits<RhsScalar, LhsScalar, ConjugateRhs, ConjugateLhs, Architecture::Target> Eigen::internal::last_row_process_16_packets< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs, 16 >::SwappedTraits
Traits
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef gebp_traits<LhsScalar, RhsScalar, ConjugateLhs, ConjugateRhs, Architecture::Target> Eigen::internal::last_row_process_16_packets< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs, 16 >::Traits
Member Function Documentation
operator()()
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> EIGEN_STRONG_INLINE void Eigen::internal::last_row_process_16_packets< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs, 16 >::operator() (const DataMapper & res, SwappedTraits & straits, const LhsScalar * blA, const RhsScalar * blB, Index depth, const Index endk, Index i, Index j2, ResScalar alpha, SAccPacket & C0) inline
{
     typedef typename unpacket_traits<typename unpacket_traits<SResPacket>::half>::half SResPacketQuarter;
     typedef typename unpacket_traits<typename unpacket_traits<SLhsPacket>::half>::half SLhsPacketQuarter;
     typedef typename unpacket_traits<typename unpacket_traits<SRhsPacket>::half>::half SRhsPacketQuarter;
     typedef typename unpacket_traits<typename unpacket_traits<SAccPacket>::half>::half SAccPacketQuarter;
     SResPacketQuarter R = res.template gatherPacket<SResPacketQuarter>(i, j2);
     SResPacketQuarter alphav = pset1<SResPacketQuarter>(alpha);
     if (depth - endk > 0) {
       // We have to handle the last row(s) of the rhs, which
       // correspond to a half-packet
       SAccPacketQuarter c0 = predux_half_dowto4(predux_half_dowto4(C0));
       for (Index kk = endk; kk < depth; kk++) {
         SLhsPacketQuarter a0;
         SRhsPacketQuarter b0;
         straits.loadLhsUnaligned(blB, a0);
         straits.loadRhs(blA, b0);
         straits.madd(a0, b0, c0, b0, fix<0>);
         blB += SwappedTraits::LhsProgress / 4;
         blA += 1;
       }
       straits.acc(c0, alphav, R);
     } else {
       straits.acc(predux_half_dowto4(predux_half_dowto4(C0)), alphav, R);
     }
     res.scatterPacket(i, j2, R);
   }
References Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::acc(), alpha, i, Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::LhsProgress, Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadLhsUnaligned(), Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadRhs(), Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::madd(), Eigen::internal::predux_half_dowto4(), R, and res.
The documentation for this struct was generated from the following file:
products/GeneralBlockPanelKernel.h