MercuryDPM: check_signbit_impl< T > Struct Template Reference
check_signbit_impl< T > Struct Template Reference
Static Public Member Functions
static void run ()
Member Function Documentation
run()
template<typename T > static void check_signbit_impl< T >::run () inline static
                     {
     T true_mask;
     std::memset(static_cast<void*>(&true_mask), 0xff, sizeof(T));
     T false_mask;
     std::memset(static_cast<void*>(&false_mask), 0x00, sizeof(T));
     std::vector<T> negative_values;
     std::vector<T> non_negative_values;
     if (NumTraits<T>::IsInteger) {
       negative_values = {static_cast<T>(-1), static_cast<T>(NumTraits<T>::lowest())};
       non_negative_values = {static_cast<T>(0), static_cast<T>(1), static_cast<T>(NumTraits<T>::highest())};
     } else {
       // does not have sign bit
       const T pos_zero = static_cast<T>(0.0);
       const T pos_one = static_cast<T>(1.0);
       const T pos_inf = std::numeric_limits<T>::infinity();
       const T pos_nan = std::numeric_limits<T>::quiet_NaN();
       // has sign bit
       const T neg_zero = numext::negate(pos_zero);
       const T neg_one = numext::negate(pos_one);
       const T neg_inf = numext::negate(pos_inf);
       const T neg_nan = numext::negate(pos_nan);
       negative_values = {neg_zero, neg_one, neg_inf, neg_nan};
       non_negative_values = {pos_zero, pos_one, pos_inf, pos_nan};
     }
     auto check_all = [](auto values, auto expected) {
       bool all_pass = true;
       for (T val : values) {
         const T numext_val = numext::signbit(val);
         bool not_same = internal::predux_any(internal::bitwise_helper<T>::bitwise_xor(expected, numext_val));
         all_pass = all_pass && !not_same;
         if (not_same) std::cout << "signbit(" << val << ") = " << numext_val << " != " << expected << std::endl;
       }
       return all_pass;
     };
     bool check_all_pass = check_all(non_negative_values, false_mask);
     check_all_pass = check_all_pass && check_all(negative_values, (NumTraits<T>::IsSigned ? true_mask : false_mask));
     VERIFY(check_all_pass);
   }
References Eigen::test::negate(), Eigen::internal::predux_any(), Eigen::numext::signbit(), calibrate::val, and VERIFY.
Referenced by check_signbit().
The documentation for this struct was generated from the following file:
numext.cpp