MercuryDPM: ScaleCoupledBeam Class Reference
ScaleCoupledBeam Class Reference
Public Member Functions
ScaleCoupledBeam ()
void setupOomph ()
void setupMercury ()
void actionsBeforeSolve () override
Write header of output file.
void actionsAfterSolve () override
Write header of output file.
void actionsBeforeOomphTimeStep () override
Each time step, compute deflection, elastic, kinetic and gravitational energy, and write to output file.
double getBeamDeflection () const
Computes beam deflection.
ScaleCoupledBeam ()
void setupOomph ()
void setupMercury ()
void actionsBeforeSolve () override
Write header of output file.
void actionsAfterSolve () override
Write header of output file.
void actionsBeforeOomphTimeStep () override
Each time step, compute deflection, elastic, kinetic and gravitational energy, and write to output file.
double getBeamDeflection () const
Computes beam deflection.
Public Member Functions inherited from ScaleCoupling< M, O >
const std::vector< CoupledElement > & getCoupledElements ()
get coupled element
const std::vector< CoupledParticle > & getCoupledParticles ()
get coupled particle
void setPenalty (double penalty)
Sets penalty parameter.
void setCouplingWeight (const std::function< double(double x, double y, double z)> &couplingWeight)
Sets weight function (determines which nodes/el_pts are in coupling zone)
void solveScaleCoupling ()
Computes nStep, the ratio of FEM and DEM time steps, then calls solveSurfaceCoupling(nStep)
Public Member Functions inherited from BaseCoupling< M, O >
BaseCoupling ()=default
void setName (std::string name)
std::string getName () const
void removeOldFiles () const
void writeEneTimeStep (std::ostream &os) const override
void writeEneHeader (std::ostream &os) const override
void solveOomph (int max_adapt=0)
void checkResidual ()
void solveMercury (unsigned long nt)
void setCGWidth (const double &width)
double getCGWidth ()
bool useCGMapping ()
CGFunctions::LucyXYZ getCGFunction ()
Public Attributes
std::ofstream out
output file stream
std::ofstream outFile
output file stream
Private Attributes
double length = 20.0
double distance = 0.4
double bulkDensity = 1309
double elasticModulus = 1e8
double overlapLength = 10.0*distance
double penalty = 8e9
double velocity = 1e-1
Detailed Description
Define a coupled problem
Constructor & Destructor Documentation
ScaleCoupledBeam() [1/2]
ScaleCoupledBeam::ScaleCoupledBeam () inline
{
         //set name
         setName("ScaleCoupledBeam");
         //remove existing output files
         removeOldFiles();
         // setup steps
         setupOomph();
         setupMercury(); //sets timeMax
         // set weight function
         auto couplingWeight = [this] (double x,double y,double z) {
             if (x<0.5*(length-overlapLength)) {
                 // DEM region
                 return 1.0;
             } else if (x>0.5*(length+overlapLength)) {
                 // FEM region
                 return 0.0;
             } else {
                 // coupled region
                 //return (0.5*(length+overlapLength)-x)/overlapLength;
                 double unit = (0.5*(length+overlapLength)-x)/overlapLength;
                 return 0.5+0.4*std::sin(constants::pi*(unit-0.5));
             }
         };
         setCouplingWeight(couplingWeight);
         setPenalty(penalty);
         // setup time
         double waveSpeed = sqrt(elasticModulus/bulkDensity);
         double propagationTime = length/waveSpeed;
         setTimeMax(1.25*propagationTime);
         setOomphTimeStep(getTimeStep());
         //setOomphTimeStep(propagationTime/100.0);
         setSaveCount(getTimeMax()/getTimeStep()/100.0);
         logger(INFO,"TimeMax: %, nTimeSteps %", getTimeMax(), getTimeMax()/getTimeStep());
         // solve
         writeToVTK();
         solveScaleCoupling();
         saveSolidMesh();
     }
References bulkDensity, elasticModulus, INFO, length, logger, overlapLength, penalty, constants::pi, BaseCoupling< M, O >::removeOldFiles(), ScaleCoupling< M, O >::setCouplingWeight(), BaseCoupling< M, O >::setName(), ScaleCoupling< M, O >::setPenalty(), setupMercury(), setupOomph(), sin(), ScaleCoupling< M, O >::solveScaleCoupling(), sqrt(), plotDoE::x, and y.
ScaleCoupledBeam() [2/2]
ScaleCoupledBeam::ScaleCoupledBeam () inline
{
         //set name
         setName("ScaleCoupledBeamUnitTest");
         //remove existing output files
         removeOldFiles();
         // setup steps
         setupOomph();
         setupMercury(); //sets timeMax
         // set weight function
         auto couplingWeight = [this] (double x,double y,double z) {
             if (x<0.5*(length-overlapLength)) {
                 // DEM region
                 return 1.0;
             } else if (x>0.5*(length+overlapLength)) {
                 // FEM region
                 return 0.0;
             } else {
                 // coupled region
                 //return (0.5*(length+overlapLength)-x)/overlapLength;
                 double unit = (0.5*(length+overlapLength)-x)/overlapLength;
                 return 0.5+0.4*std::sin(constants::pi*(unit-0.5));
             }
         };
         setCouplingWeight(couplingWeight);
         setPenalty(penalty);
         // setup time
         setTimeMax(2.0*getTimeStep()); // different to ScaleCoupledBeam
         setOomphTimeStep(getTimeStep());
         setSaveCount(getTimeMax()/getTimeStep()/100.0);
         logger(INFO,"TimeMax: %, nTimeSteps %", getTimeMax(), getTimeMax()/getTimeStep());
         // solve
         writeToVTK();
         solveScaleCoupling();
         saveSolidMesh();
     }
References INFO, length, logger, overlapLength, penalty, constants::pi, BaseCoupling< M, O >::removeOldFiles(), ScaleCoupling< M, O >::setCouplingWeight(), BaseCoupling< M, O >::setName(), ScaleCoupling< M, O >::setPenalty(), setupMercury(), setupOomph(), sin(), ScaleCoupling< M, O >::solveScaleCoupling(), plotDoE::x, and y.
Member Function Documentation
actionsAfterSolve() [1/2]
void ScaleCoupledBeam::actionsAfterSolve () inline override
Write header of output file.
{
         out.close();
     }
References out.
actionsAfterSolve() [2/2]
void ScaleCoupledBeam::actionsAfterSolve () inline override
Write header of output file.
{
         outFile.close();
         // checking errors
         Vec3D couplingForce = getCoupledParticles().back().couplingForce;
         helpers::check(couplingForce.X,-15917,0.1,"Coupling force");
     }
References helpers::check(), ScaleCoupling< M, O >::getCoupledParticles(), outFile, and Vec3D::X.
actionsBeforeOomphTimeStep() [1/2]
void ScaleCoupledBeam::actionsBeforeOomphTimeStep () inline override
Each time step, compute deflection, elastic, kinetic and gravitational energy, and write to output file.
{
         double mass, elasticEnergy, kineticEnergy;
         Vector<double> com(3), linearMomentum(3), angularMomentum(3);
         getMassMomentumEnergy(mass, com, linearMomentum, angularMomentum, elasticEnergy, kineticEnergy);
         static double comZ0 = com[2];
         double gravEnergy = 9.8*mass*(com[2]-comZ0);
         out << getOomphTime() << ' ' << getBeamDeflection() << ' ' << elasticEnergy << ' ' << kineticEnergy << ' ' << gravEnergy << std::endl;
         std::cout << getOomphTime() << ' ' << getBeamDeflection() << ' ' << elasticEnergy << ' ' << kineticEnergy << ' ' << gravEnergy << '\n';
     }
References getBeamDeflection(), and out.
actionsBeforeOomphTimeStep() [2/2]
void ScaleCoupledBeam::actionsBeforeOomphTimeStep () inline override
Each time step, compute deflection, elastic, kinetic and gravitational energy, and write to output file.
{
         double mass, elasticEnergy, kineticEnergy;
         Vector<double> com(3), linearMomentum(3), angularMomentum(3);
         getMassMomentumEnergy(mass, com, linearMomentum, angularMomentum, elasticEnergy, kineticEnergy);
         static double comZ0 = com[2];
         double gravEnergy = 9.8*mass*(com[2]-comZ0);
         outFile << getOomphTime() << ' ' << getBeamDeflection() << ' ' << elasticEnergy << ' ' << kineticEnergy << ' ' << gravEnergy << std::endl;
         std::cout << getOomphTime() << ' ' << getBeamDeflection() << ' ' << elasticEnergy << ' ' << kineticEnergy << ' ' << gravEnergy << '\n';
     }
References getBeamDeflection(), and outFile.
actionsBeforeSolve() [1/2]
void ScaleCoupledBeam::actionsBeforeSolve () inline override
Write header of output file.
{
         helpers::writeToFile(getName()+".gnu", "set key autotitle columnheader\n"
                                                "p 'SolidBeamUnsteady.out' u 1:3 w l, '' u 1:4 w l, '' u 1:5 w l, '' u 1:($3+$4+$5) t 'totalEnergy' w l");
         out.open(getName()+".out");
         out << "time deflection elasticEnergy kineticEnergy gravEnergy\n";
     }
References BaseCoupling< M, O >::getName(), out, and helpers::writeToFile().
actionsBeforeSolve() [2/2]
void ScaleCoupledBeam::actionsBeforeSolve () inline override
Write header of output file.
{
         helpers::writeToFile(getName()+".gnu", "set key autotitle columnheader\n"
                                                "p 'SolidBeamUnsteady.out' u 1:3 w l, '' u 1:4 w l, '' u 1:5 w l, '' u 1:($3+$4+$5) t 'totalEnergy' w l");
         outFile.open(getName()+".out");
         outFile << "time deflection elasticEnergy kineticEnergy gravEnergy\n";
     }
References BaseCoupling< M, O >::getName(), outFile, and helpers::writeToFile().
getBeamDeflection() [1/2]
double ScaleCoupledBeam::getBeamDeflection () const inline
Computes beam deflection.
{
         std::array<double, 3> min, max;
         getDomainSize(min, max);
         Vector<double> xi(3);
         xi[0] = max[0];
         xi[1] = 0.5 * (max[1] + min[1]);
         xi[2] = 0.5 * (max[2] + min[2]);
         return getDeflection(xi, 2);
     }
References max, and min.
Referenced by actionsBeforeOomphTimeStep().
getBeamDeflection() [2/2]
double ScaleCoupledBeam::getBeamDeflection () const inline
Computes beam deflection.
{
         std::array<double, 3> min, max;
         getDomainSize(min, max);
         Vector<double> xi(3);
         xi[0] = max[0];
         xi[1] = 0.5 * (max[1] + min[1]);
         xi[2] = 0.5 * (max[2] + min[2]);
         return getDeflection(xi, 2);
     }
References max, and min.
setupMercury() [1/2]
void ScaleCoupledBeam::setupMercury () inline
     {
         // positive overlap means adhesive forces
         double overlap = 0.0*distance; //overlap between particles
         double radius = 0.5*(distance+overlap); // particle radius
         double particleDensity = bulkDensity*mathsFunc::cubic(distance) / (constants::pi/6.0*mathsFunc::cubic(2.0*radius));
         double stiffness = elasticModulus*distance; // particle stiffness
         setDomain(Vec3D(-radius,-radius,0),Vec3D(radius,radius,0.5*(length+overlapLength)));
         setParticlesWriteVTK(true);
         auto species = speciesHandler.copyAndAddObject(LinearViscoelasticReversibleAdhesiveSpecies());
         species->setDensity(particleDensity);
         species->setStiffness(stiffness);
         species->setAdhesionStiffness(stiffness);
         species->setAdhesionForceMax(stiffness*overlap);
         SphericalParticle p(species);
         p.setRadius(radius);
         //p.setVelocity(Vec3D(1,0,0));
         double dx = distance;
         auto n = (unsigned)(0.5*(length+overlapLength)/dx);
         for (int i = 0; i<n; ++i) {
             for (int j = 0; j<2; ++j) {
                 for (int k = 0; k<2; ++k) {
                     p.setPosition(Vec3D(1+2*i, j==0?-1:1, k==0?-1:1)*0.5*distance);
                     particleHandler.copyAndAddObject(p);
                     if (i==0) {
                         particleHandler.getLastObject()->setVelocity(Vec3D(velocity,0,0));
                         //particleHandler.getLastObject()->fixParticle();
                         //particleHandler.getLastObject()->setPrescribedVelocity(velocityAtBoundary);
                     }
                 }
             }
         }
         setTimeStep(0.5*species->computeTimeStep(p.getMass()));
     }
References bulkDensity, mathsFunc::cubic(), distance, elasticModulus, i, j, k, length, n, overlapLength, p, constants::pi, UniformPSDSelfTest::radius, and velocity.
Referenced by ScaleCoupledBeam().
setupMercury() [2/2]
void ScaleCoupledBeam::setupMercury () inline
     {
         // positive overlap means adhesive forces
         double overlap = 0.0*distance; //overlap between particles
         double radius = 0.5*(distance+overlap); // particle radius
         double particleDensity = bulkDensity*mathsFunc::cubic(distance) / (constants::pi/6.0*mathsFunc::cubic(2.0*radius));
         double stiffness = elasticModulus*distance; // particle stiffness
         setDomain(Vec3D(-radius,-radius,0),Vec3D(radius,radius,0.5*(length+overlapLength)));
         setParticlesWriteVTK(true);
         auto species = speciesHandler.copyAndAddObject(LinearViscoelasticReversibleAdhesiveSpecies());
         species->setDensity(particleDensity);
         species->setStiffness(stiffness);
         species->setAdhesionStiffness(stiffness);
         species->setAdhesionForceMax(stiffness*overlap);
         SphericalParticle p(species);
         p.setRadius(radius);
         p.setVelocity(Vec3D(1,0,0)); // different to ScaleCoupledBeam
         double dx = distance;
         auto n = (unsigned)(0.5*(length+overlapLength)/dx);
         for (int i = 0; i<n; ++i) {
             for (int j = 0; j<2; ++j) {
                 for (int k = 0; k<2; ++k) {
                     p.setPosition(Vec3D(1+2*i, j==0?-1:1, k==0?-1:1)*0.5*distance);
                     particleHandler.copyAndAddObject(p);  // different to ScaleCoupledBeam
                 }
             }
         }
         setTimeStep(0.5*species->computeTimeStep(p.getMass()));
     }
References bulkDensity, mathsFunc::cubic(), distance, elasticModulus, i, j, k, length, n, overlapLength, p, constants::pi, and UniformPSDSelfTest::radius.
setupOomph() [1/2]
void ScaleCoupledBeam::setupOomph () inline
                       {
         setElasticModulus(elasticModulus);
         setDensity(bulkDensity);
         setSolidCubicMesh(round(0.5*(length+overlapLength)/distance), 2, 2,
                           0.5*(length-overlapLength), length, -distance, distance, -distance, distance);
         //pinBoundaries({Beam::Boundary::X_MIN});
         setNewtonSolverTolerance(1e-2);
         prepareForSolve();
         linear_solver_pt()->disable_doc_time();
         //disable_info_in_newton_solve();
     }
References bulkDensity, distance, e(), elasticModulus, length, overlapLength, and Eigen::bfloat16_impl::round().
Referenced by ScaleCoupledBeam().
setupOomph() [2/2]
void ScaleCoupledBeam::setupOomph () inline
                       {
         setElasticModulus(elasticModulus);
         setDensity(bulkDensity);
         setSolidCubicMesh(round(0.5*(length+overlapLength)/distance), 2, 2,
                           0.5*(length-overlapLength), length, -distance, distance, -distance, distance);
         //pinBoundaries({Beam::Boundary::X_MIN});
         setNewtonSolverTolerance(1e-2);
         prepareForSolve();
         linear_solver_pt()->disable_doc_time();
         //disable_info_in_newton_solve();
     }
References bulkDensity, distance, e(), elasticModulus, length, overlapLength, and Eigen::bfloat16_impl::round().
Member Data Documentation
bulkDensity
double ScaleCoupledBeam::bulkDensity = 1309 private
Referenced by ScaleCoupledBeam(), setupMercury(), and setupOomph().
distance
double ScaleCoupledBeam::distance = 0.4 private
Referenced by setupMercury(), and setupOomph().
elasticModulus
double ScaleCoupledBeam::elasticModulus = 1e8 private
Referenced by ScaleCoupledBeam(), setupMercury(), and setupOomph().
length
double ScaleCoupledBeam::length = 20.0 private
Referenced by ScaleCoupledBeam(), setupMercury(), and setupOomph().
out
std::ofstream ScaleCoupledBeam::out
output file stream
Referenced by actionsAfterSolve(), actionsBeforeOomphTimeStep(), and actionsBeforeSolve().
outFile
std::ofstream ScaleCoupledBeam::outFile
output file stream
Referenced by actionsAfterSolve(), actionsBeforeOomphTimeStep(), and actionsBeforeSolve().
overlapLength
double ScaleCoupledBeam::overlapLength = 10.0*distance private
Referenced by ScaleCoupledBeam(), setupMercury(), and setupOomph().
penalty
double ScaleCoupledBeam::penalty = 8e9 private
Referenced by ScaleCoupledBeam().
velocity
double ScaleCoupledBeam::velocity = 1e-1 private
Referenced by setupMercury().
The documentation for this class was generated from the following files:
ScaleCoupledBeam.cpp
ScaleCoupledBeamUnitTest.cpp