MercuryDPM: Eigen::Spline< Scalar_, Dim_, Degree_ > Class Template Reference
Eigen::Spline< Scalar_, Dim_, Degree_ > Class Template Reference
Geometry » Reference » Splines_Module
A class representing multi-dimensional spline curves.
#include <Spline.h>
Public Types
enum { Dimension = Dim_ }
enum { Degree = Degree_ }
typedef Scalar_ Scalar
typedef SplineTraits< Spline >::PointType PointType
The point type the spline is representing.
typedef SplineTraits< Spline >::KnotVectorType KnotVectorType
The data type used to store knot vectors.
typedef SplineTraits< Spline >::ParameterVectorType ParameterVectorType
The data type used to store parameter vectors.
typedef SplineTraits< Spline >::BasisVectorType BasisVectorType
The data type used to store non-zero basis functions.
typedef SplineTraits< Spline >::BasisDerivativeType BasisDerivativeType
The data type used to store the values of the basis function derivatives.
typedef SplineTraits< Spline >::ControlPointVectorType ControlPointVectorType
The data type representing the spline's control points.
Public Member Functions
Spline ()
Creates a (constant) zero spline. For Splines with dynamic degree, the resulting degree will be 0.
template<typename OtherVectorType , typename OtherArrayType >
Spline (const OtherVectorType &knots, const OtherArrayType &ctrls)
Creates a spline from a knot vector and control points.
template<int OtherDegree>
Spline (const Spline< Scalar, Dimension, OtherDegree > &spline)
Copy constructor for splines.
const KnotVectorType & knots () const
Returns the knots of the underlying spline.
const ControlPointVectorType & ctrls () const
Returns the ctrls of the underlying spline.
PointType operator() (Scalar u) const
Returns the spline value at a given site \(u\).
SplineTraits< Spline >::DerivativeType derivatives (Scalar u, DenseIndex order) const
Evaluation of spline derivatives of up-to given order.
template<int DerivativeOrder>
SplineTraits< Spline, DerivativeOrder >::DerivativeType derivatives (Scalar u, DenseIndex order=DerivativeOrder) const
Evaluation of spline derivatives of up-to given order.
SplineTraits< Spline >::BasisVectorType basisFunctions (Scalar u) const
Computes the non-zero basis functions at the given site.
SplineTraits< Spline >::BasisDerivativeType basisFunctionDerivatives (Scalar u, DenseIndex order) const
Computes the non-zero spline basis function derivatives up to given order.
template<int DerivativeOrder>
SplineTraits< Spline, DerivativeOrder >::BasisDerivativeType basisFunctionDerivatives (Scalar u, DenseIndex order=DerivativeOrder) const
Computes the non-zero spline basis function derivatives up to given order.
DenseIndex degree () const
Returns the spline degree.
DenseIndex span (Scalar u) const
Returns the span within the knot vector in which u is falling.
Static Public Member Functions
static DenseIndex Span (typename SplineTraits< Spline >::Scalar u, DenseIndex degree, const typename SplineTraits< Spline >::KnotVectorType &knots)
Computes the span within the provided knot vector in which u is falling.
static BasisVectorType BasisFunctions (Scalar u, DenseIndex degree, const KnotVectorType &knots)
Returns the spline's non-zero basis functions.
static BasisDerivativeType BasisFunctionDerivatives (const Scalar u, const DenseIndex order, const DenseIndex degree, const KnotVectorType &knots)
Computes the non-zero spline basis function derivatives up to given order.
Static Private Member Functions
template<typename DerivativeType >
static void BasisFunctionDerivativesImpl (const typename Spline< Scalar_, Dim_, Degree_ >::Scalar u, const DenseIndex order, const DenseIndex p, const typename Spline< Scalar_, Dim_, Degree_ >::KnotVectorType &U, DerivativeType &N_)
Private Attributes
KnotVectorType m_knots
ControlPointVectorType m_ctrls
Detailed Description
template<typename Scalar_, int Dim_, int Degree_>
class Eigen::Spline< Scalar_, Dim_, Degree_ >
A class representing multi-dimensional spline curves.
The class represents B-splines with non-uniform knot vectors. Each control point of the B-spline is associated with a basis function
\begin{align*} C(u) & = \sum_{i=0}^{n}N_{i,p}(u)P_i \end{align*}
Template Parameters
Scalar_ The underlying data type (typically float or double)
Dim_ The curve dimension (e.g. 2 or 3)
Degree_ Per default set to Dynamic; could be set to the actual desired degree for optimization purposes (would result in stack allocation of several temporary variables).
Member Typedef Documentation
BasisDerivativeType
template<typename Scalar_ , int Dim_, int Degree_> typedef SplineTraits<Spline>::BasisDerivativeType Eigen::Spline< Scalar_, Dim_, Degree_ >::BasisDerivativeType
The data type used to store the values of the basis function derivatives.
BasisVectorType
template<typename Scalar_ , int Dim_, int Degree_> typedef SplineTraits<Spline>::BasisVectorType Eigen::Spline< Scalar_, Dim_, Degree_ >::BasisVectorType
The data type used to store non-zero basis functions.
ControlPointVectorType
template<typename Scalar_ , int Dim_, int Degree_> typedef SplineTraits<Spline>::ControlPointVectorType Eigen::Spline< Scalar_, Dim_, Degree_ >::ControlPointVectorType
The data type representing the spline's control points.
KnotVectorType
template<typename Scalar_ , int Dim_, int Degree_> typedef SplineTraits<Spline>::KnotVectorType Eigen::Spline< Scalar_, Dim_, Degree_ >::KnotVectorType
The data type used to store knot vectors.
ParameterVectorType
template<typename Scalar_ , int Dim_, int Degree_> typedef SplineTraits<Spline>::ParameterVectorType Eigen::Spline< Scalar_, Dim_, Degree_ >::ParameterVectorType
The data type used to store parameter vectors.
PointType
template<typename Scalar_ , int Dim_, int Degree_> typedef SplineTraits<Spline>::PointType Eigen::Spline< Scalar_, Dim_, Degree_ >::PointType
The point type the spline is representing.
Scalar
template<typename Scalar_ , int Dim_, int Degree_> typedef Scalar_ Eigen::Spline< Scalar_, Dim_, Degree_ >::Scalar
The spline curve's scalar type.
Member Enumeration Documentation
anonymous enum
template<typename Scalar_ , int Dim_, int Degree_> anonymous enum
Enumerator
Dimension
The spline curve's dimension.
 { Dimension = Dim_  };
anonymous enum
template<typename Scalar_ , int Dim_, int Degree_> anonymous enum
Enumerator
Degree
The spline curve's degree.
 { Degree = Degree_  };
Constructor & Destructor Documentation
Spline() [1/3]
template<typename Scalar_ , int Dim_, int Degree_> Eigen::Spline< Scalar_, Dim_, Degree_ >::Spline () inline
Creates a (constant) zero spline. For Splines with dynamic degree, the resulting degree will be 0.
       : m_knots(1, (Degree == Dynamic ? 2 : 2 * Degree + 2)),
         m_ctrls(ControlPointVectorType::Zero(Dimension, (Degree == Dynamic ? 1 : Degree + 1))) {
     // in theory this code can go to the initializer list but it will get pretty
     // much unreadable ...
     enum { MinDegree = (Degree == Dynamic ? 0 : Degree) };
     m_knots.template segment<MinDegree + 1>(0) = Array<Scalar, 1, MinDegree + 1>::Zero();
     m_knots.template segment<MinDegree + 1>(MinDegree + 1) = Array<Scalar, 1, MinDegree + 1>::Ones();
   }
References Eigen::Spline< Scalar_, Dim_, Degree_ >::Degree, Eigen::Dynamic, Eigen::Spline< Scalar_, Dim_, Degree_ >::m_knots, and oomph::PseudoSolidHelper::Zero.
Spline() [2/3]
template<typename Scalar_ , int Dim_, int Degree_> template<typename OtherVectorType , typename OtherArrayType > Eigen::Spline< Scalar_, Dim_, Degree_ >::Spline (const OtherVectorType & knots, const OtherArrayType & ctrls) inline
Creates a spline from a knot vector and control points.
Parameters
knots The spline's knot vector.
ctrls The spline's control point vector.
 : m_knots(knots), m_ctrls(ctrls) {}
Spline() [3/3]
template<typename Scalar_ , int Dim_, int Degree_> template<int OtherDegree> Eigen::Spline< Scalar_, Dim_, Degree_ >::Spline (const Spline< Scalar, Dimension, OtherDegree > & spline) inline
Copy constructor for splines.
Parameters
spline The input spline.
 : m_knots(spline.knots()), m_ctrls(spline.ctrls()) {}
Member Function Documentation
BasisFunctionDerivatives()
template<typename Scalar_ , int Dim_, int Degree_> SplineTraits< Spline< Scalar_, Dim_, Degree_ > >::BasisDerivativeType Eigen::Spline< Scalar_, Dim_, Degree_ >::BasisFunctionDerivatives (const Scalar u, const DenseIndex order, const DenseIndex degree, const KnotVectorType & knots) static
Computes the non-zero spline basis function derivatives up to given order.
The function computes
\begin{align*} \frac{d^i}{du^i} N_{i,p}(u), \hdots, \frac{d^i}{du^i} N_{i+p+1,p}(u) \end{align*}
with i ranging from 0 up to the specified order.
Parameters
u Parameter \(u \in [0;1]\) at which the non-zero basis function derivatives are computed.
order The order up to which the basis function derivatives are computes.
degree The degree of the underlying spline
knots The underlying spline's knot vector.
{
   typename SplineTraits<Spline>::BasisDerivativeType der;
   BasisFunctionDerivativesImpl(u, order, degree, knots, der);
   return der;
 }
References constants::degree.
basisFunctionDerivatives() [1/2]
template<typename Scalar_ , int Dim_, int Degree_> SplineTraits< Spline< Scalar_, Dim_, Degree_ >, DerivativeOrder >::BasisDerivativeType Eigen::Spline< Scalar_, Dim_, Degree_ >::basisFunctionDerivatives (Scalar u, DenseIndex order) const
Computes the non-zero spline basis function derivatives up to given order.
The function computes
\begin{align*} \frac{d^i}{du^i} N_{i,p}(u), \hdots, \frac{d^i}{du^i} N_{i+p+1,p}(u) \end{align*}
with i ranging from 0 up to the specified order.
Parameters
u Parameter \(u \in [0;1]\) at which the non-zero basis function derivatives are computed.
order The order up to which the basis function derivatives are computes.
{
   typename SplineTraits<Spline<Scalar_, Dim_, Degree_> >::BasisDerivativeType der;
   BasisFunctionDerivativesImpl(u, order, degree(), knots(), der);
   return der;
 }
References constants::degree.
basisFunctionDerivatives() [2/2]
template<typename Scalar_ , int Dim_, int Degree_> template<int DerivativeOrder> SplineTraits<Spline, DerivativeOrder>::BasisDerivativeType Eigen::Spline< Scalar_, Dim_, Degree_ >::basisFunctionDerivatives (Scalar u, DenseIndex order = DerivativeOrder) const
Computes the non-zero spline basis function derivatives up to given order.
The function computes
\begin{align*} \frac{d^i}{du^i} N_{i,p}(u), \hdots, \frac{d^i}{du^i} N_{i+p+1,p}(u) \end{align*}
with i ranging from 0 up to the specified order.
Parameters
u Parameter \(u \in [0;1]\) at which the non-zero basis function derivatives are computed.
order The order up to which the basis function derivatives are computes. Using the template version of this function is more efficieent since temporary objects are allocated on the stack whenever this is possible.
BasisFunctionDerivativesImpl()
template<typename Scalar_ , int Dim_, int Degree_> template<typename DerivativeType > void Eigen::Spline< Scalar_, Dim_, Degree_ >::BasisFunctionDerivativesImpl (const typename Spline< Scalar_, Dim_, Degree_ >::Scalar u, const DenseIndex order, const DenseIndex p, const typename Spline< Scalar_, Dim_, Degree_ >::KnotVectorType & U, DerivativeType & N_) static private
{
   typedef Spline<Scalar_, Dim_, Degree_> SplineType;
   enum { Order = SplineTraits<SplineType>::OrderAtCompileTime };
   const DenseIndex span = SplineType::Span(u, p, U);
   const DenseIndex n = (std::min)(p, order);
   N_.resize(n + 1, p + 1);
   BasisVectorType left = BasisVectorType::Zero(p + 1);
   BasisVectorType right = BasisVectorType::Zero(p + 1);
   Matrix<Scalar, Order, Order> ndu(p + 1, p + 1);
   Scalar saved, temp;  // FIXME These were double instead of Scalar. Was there a reason for that?
   ndu(0, 0) = 1.0;
   DenseIndex j;
   for (j = 1; j <= p; ++j) {
     left[j] = u - U[span + 1 - j];
     right[j] = U[span + j] - u;
     saved = 0.0;
     for (DenseIndex r = 0; r < j; ++r) {
       /* Lower triangle */
       ndu(j, r) = right[r + 1] + left[j - r];
       temp = ndu(r, j - 1) / ndu(j, r);
       /* Upper triangle */
       ndu(r, j) = static_cast<Scalar>(saved + right[r + 1] * temp);
       saved = left[j - r] * temp;
     }
     ndu(j, j) = static_cast<Scalar>(saved);
   }
   for (j = p; j >= 0; --j) N_(0, j) = ndu(j, p);
   // Compute the derivatives
   DerivativeType a(n + 1, p + 1);
   DenseIndex r = 0;
   for (; r <= p; ++r) {
     DenseIndex s1, s2;
     s1 = 0;
     s2 = 1;  // alternate rows in array a
     a(0, 0) = 1.0;
     // Compute the k-th derivative
     for (DenseIndex k = 1; k <= static_cast<DenseIndex>(n); ++k) {
       Scalar d = 0.0;
       DenseIndex rk, pk, j1, j2;
       rk = r - k;
       pk = p - k;
       if (r >= k) {
         a(s2, 0) = a(s1, 0) / ndu(pk + 1, rk);
         d = a(s2, 0) * ndu(rk, pk);
       }
       if (rk >= -1)
         j1 = 1;
       else
         j1 = -rk;
       if (r - 1 <= pk)
         j2 = k - 1;
       else
         j2 = p - r;
       for (j = j1; j <= j2; ++j) {
         a(s2, j) = (a(s1, j) - a(s1, j - 1)) / ndu(pk + 1, rk + j);
         d += a(s2, j) * ndu(rk + j, pk);
       }
       if (r <= pk) {
         a(s2, k) = -a(s1, k - 1) / ndu(pk + 1, r);
         d += a(s2, k) * ndu(r, pk);
       }
       N_(k, r) = static_cast<Scalar>(d);
       j = s1;
       s1 = s2;
       s2 = j;  // Switch rows
     }
   }
   /* Multiply through by the correct factors */
   /* (Eq. [2.9])                             */
   r = p;
   for (DenseIndex k = 1; k <= static_cast<DenseIndex>(n); ++k) {
     for (j = p; j >= 0; --j) N_(k, j) *= r;
     r *= p - k;
   }
 }
References a, j, k, min, n, p, UniformPSDSelfTest::r, RachelsAdvectionDiffusion::U, and oomph::PseudoSolidHelper::Zero.
basisFunctions()
template<typename Scalar_ , int Dim_, int Degree_> SplineTraits< Spline< Scalar_, Dim_, Degree_ > >::BasisVectorType Eigen::Spline< Scalar_, Dim_, Degree_ >::basisFunctions (Scalar u) const
Computes the non-zero basis functions at the given site.
Splines have local support and a point from their image is defined by exactly \(p+1\) control points \(P_i\) where \(p\) is the spline degree.
This function computes the \(p+1\) non-zero basis function values for a given parameter value \(u\). It returns
\begin{align*} N_{i,p}(u), \hdots, N_{i+p+1,p}(u) \end{align*}
Parameters
u Parameter \(u \in [0;1]\) at which the non-zero basis functions are computed.
                     {
   return Spline::BasisFunctions(u, degree(), knots());
 }
References Eigen::Spline< Scalar_, Dim_, Degree_ >::BasisFunctions(), and constants::degree.
BasisFunctions()
template<typename Scalar_ , int Dim_, int Degree_> Spline< Scalar_, Dim_, Degree_ >::BasisVectorType Eigen::Spline< Scalar_, Dim_, Degree_ >::BasisFunctions (Scalar u, DenseIndex degree, const KnotVectorType & knots) static
Returns the spline's non-zero basis functions.
The function computes and returns
\begin{align*} N_{i,p}(u), \hdots, N_{i+p+1,p}(u) \end{align*}
Parameters
u The site at which the basis functions are computed.
degree The degree of the underlying spline.
knots The underlying spline's knot vector.
{
   const DenseIndex p = degree;
   const DenseIndex i = Spline::Span(u, degree, knots);
   const KnotVectorType& U = knots;
   BasisVectorType left(p + 1);
   left(0) = Scalar(0);
   BasisVectorType right(p + 1);
   right(0) = Scalar(0);
   VectorBlock<BasisVectorType, Degree>(left, 1, p) =
       u - VectorBlock<const KnotVectorType, Degree>(U, i + 1 - p, p).reverse();
   VectorBlock<BasisVectorType, Degree>(right, 1, p) = VectorBlock<const KnotVectorType, Degree>(U, i + 1, p) - u;
   BasisVectorType N(1, p + 1);
   N(0) = Scalar(1);
   for (DenseIndex j = 1; j <= p; ++j) {
     Scalar saved = Scalar(0);
     for (DenseIndex r = 0; r < j; r++) {
       const Scalar tmp = N(r) / (right(r + 1) + left(j - r));
       N[r] = saved + right(r + 1) * tmp;
       saved = left(j - r) * tmp;
     }
     N(j) = saved;
   }
   return N;
 }
References constants::degree, i, j, N, p, UniformPSDSelfTest::r, Eigen::Spline< Scalar_, Dim_, Degree_ >::Span(), tmp, and RachelsAdvectionDiffusion::U.
Referenced by Eigen::Spline< Scalar_, Dim_, Degree_ >::basisFunctions().
ctrls()
template<typename Scalar_ , int Dim_, int Degree_> const ControlPointVectorType& Eigen::Spline< Scalar_, Dim_, Degree_ >::ctrls () const inline
Returns the ctrls of the underlying spline.
 { return m_ctrls; }
References Eigen::Spline< Scalar_, Dim_, Degree_ >::m_ctrls.
degree()
template<typename Scalar_ , int Dim_, int Degree_> DenseIndex Eigen::Spline< Scalar_, Dim_, Degree_ >::degree
Returns the spline degree.
{
   if (Degree_ == Dynamic)
     return m_knots.size() - m_ctrls.cols() - 1;
   else
     return Degree_;
 }
References Eigen::Dynamic.
derivatives() [1/2]
template<typename Scalar_ , int Dim_, int Degree_> SplineTraits< Spline< Scalar_, Dim_, Degree_ >, DerivativeOrder >::DerivativeType Eigen::Spline< Scalar_, Dim_, Degree_ >::derivatives (Scalar u, DenseIndex order) const
Evaluation of spline derivatives of up-to given order.
The function returns
\begin{align*} \frac{d^i}{du^i}C(u) & = \sum_{i=0}^{n} \frac{d^i}{du^i} N_{i,p}(u)P_i \end{align*}
for i ranging between 0 and order.
Parameters
u Parameter \(u \in [0;1]\) at which the spline derivative is evaluated.
order The order up to which the derivatives are computed.
{
   typename SplineTraits<Spline>::DerivativeType res;
   derivativesImpl(*this, u, order, res);
   return res;
 }
References Eigen::derivativesImpl(), and res.
Referenced by check_global_interpolation_with_derivatives2d().
derivatives() [2/2]
template<typename Scalar_ , int Dim_, int Degree_> template<int DerivativeOrder> SplineTraits<Spline, DerivativeOrder>::DerivativeType Eigen::Spline< Scalar_, Dim_, Degree_ >::derivatives (Scalar u, DenseIndex order = DerivativeOrder) const
Evaluation of spline derivatives of up-to given order.
The function returns
\begin{align*} \frac{d^i}{du^i}C(u) & = \sum_{i=0}^{n} \frac{d^i}{du^i} N_{i,p}(u)P_i \end{align*}
for i ranging between 0 and order.
Parameters
u Parameter \(u \in [0;1]\) at which the spline derivative is evaluated.
order The order up to which the derivatives are computed. Using the template version of this function is more efficieent since temporary objects are allocated on the stack whenever this is possible.
knots()
template<typename Scalar_ , int Dim_, int Degree_> const KnotVectorType& Eigen::Spline< Scalar_, Dim_, Degree_ >::knots () const inline
Returns the knots of the underlying spline.
 { return m_knots; }
References Eigen::Spline< Scalar_, Dim_, Degree_ >::m_knots.
Referenced by eval_spline3d_onbrks().
operator()()
template<typename Scalar_ , int Dim_, int Degree_> Spline< Scalar_, Dim_, Degree_ >::PointType Eigen::Spline< Scalar_, Dim_, Degree_ >::operator() (Scalar u) const
Returns the spline value at a given site \(u\).
The function returns
\begin{align*} C(u) & = \sum_{i=0}^{n}N_{i,p}P_i \end{align*}
Parameters
u Parameter \(u \in [0;1]\) at which the spline is evaluated.
Returns
The spline value at the given location \(u\).
{
   enum { Order = SplineTraits<Spline>::OrderAtCompileTime };
   const DenseIndex span = this->span(u);
   const DenseIndex p = degree();
   const BasisVectorType basis_funcs = basisFunctions(u);
   const Replicate<BasisVectorType, Dimension, 1> ctrl_weights(basis_funcs);
   const Block<const ControlPointVectorType, Dimension, Order> ctrl_pts(ctrls(), 0, span - p, Dimension, p + 1);
   return (ctrl_weights * ctrl_pts).rowwise().sum();
 }
References constants::degree, and p.
span()
template<typename Scalar_ , int Dim_, int Degree_> DenseIndex Eigen::Spline< Scalar_, Dim_, Degree_ >::span (Scalar u) const
Returns the span within the knot vector in which u is falling.
Parameters
u The site for which the span is determined.
{
   return Spline::Span(u, degree(), knots());
 }
References constants::degree, and Eigen::Spline< Scalar_, Dim_, Degree_ >::Span().
Span()
template<typename Scalar_ , int Dim_, int Degree_> DenseIndex Eigen::Spline< Scalar_, Dim_, Degree_ >::Span (typename SplineTraits< Spline< Scalar_, Dim_, Degree_ > >::Scalar u, DenseIndex degree, const typename SplineTraits< Spline< Scalar_, Dim_, Degree_ > >::KnotVectorType & knots) static
Computes the span within the provided knot vector in which u is falling.
{
   // Piegl & Tiller, "The NURBS Book", A2.1 (p. 68)
   if (u <= knots(0)) return degree;
   const Scalar* pos = std::upper_bound(knots.data() + degree - 1, knots.data() + knots.size() - degree - 1, u);
   return static_cast<DenseIndex>(std::distance(knots.data(), pos) - 1);
 }
References constants::degree.
Referenced by Eigen::Spline< Scalar_, Dim_, Degree_ >::BasisFunctions(), and Eigen::Spline< Scalar_, Dim_, Degree_ >::span().
Member Data Documentation
m_ctrls
template<typename Scalar_ , int Dim_, int Degree_> ControlPointVectorType Eigen::Spline< Scalar_, Dim_, Degree_ >::m_ctrls private
Control points.
Referenced by Eigen::Spline< Scalar_, Dim_, Degree_ >::ctrls().
m_knots
template<typename Scalar_ , int Dim_, int Degree_> KnotVectorType Eigen::Spline< Scalar_, Dim_, Degree_ >::m_knots private
Knot vector.
Referenced by Eigen::Spline< Scalar_, Dim_, Degree_ >::knots(), and Eigen::Spline< Scalar_, Dim_, Degree_ >::Spline().
The documentation for this class was generated from the following file:
Spline.h