MercuryDPM: two_d_poisson_flux_bc_adapt.cc File Reference
mpi/distribution/two_d_poisson_flux_bc_adapt/two_d_poisson_flux_bc_adapt.cc File Reference
#include "generic.h"
#include "poisson.h"
#include "meshes/simple_rectangular_quadmesh.h"
Classes
class SimpleRefineableRectangularQuadMesh< ELEMENT >
class RefineableTwoMeshFluxPoissonProblem< ELEMENT >
Namespaces
TanhSolnForPoisson
Namespace for exact solution for Poisson equation with "sharp step".
Functions
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForPoisson::source_function (const Vector< double > &x, double &source)
Source function required to make the solution above an exact solution.
void TanhSolnForPoisson::prescribed_flux_on_fixed_x_boundary (const Vector< double > &x, double &flux)
Flux required by the exact solution on a boundary on which x is fixed.
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
Demonstrate how to solve 2D Poisson problem with flux boundary conditions, using two meshes.
 {
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::init(argc,argv);
 #endif
  // Switch off output modifier
  oomph_info.output_modifier_pt() = &default_output_modifier;
  // Define processor-labeled output file for all on-screen stuff
  std::ofstream output_stream;
  char filename[100];
  sprintf(filename,"RESLT/OUTPUT.%i",MPI_Helpers::communicator_pt()->my_rank());
  output_stream.open(filename);
  oomph_info.stream_pt() = &output_stream;
  OomphLibWarning::set_stream_pt(&output_stream);
  OomphLibError::set_stream_pt(&output_stream);
  //Set up the problem with 2D nine-node elements from the
  //QPoissonElement family. Pass pointer to source function.
  RefineableTwoMeshFluxPoissonProblem<RefineableQPoissonElement<2,3> >
   problem(&TanhSolnForPoisson::source_function);
 #ifdef OOMPH_HAS_MPI
  // Number of elements for which we specify the partition: all of them!
  unsigned n_el=problem.mesh_pt()->nelement();
  //Get the partition from file
  Vector<unsigned> element_partition(n_el);
  std::ifstream input_file;
  sprintf(filename,"two_d_poisson_flux_partition.dat");
  input_file.open(filename);
  std::string input_string;
  for (unsigned e=0;e<n_el;e++)
   {
    getline(input_file,input_string,'\n');
    element_partition[e]=atoi(input_string.c_str());
   }
  // Output directory for documentation of partitioning
  DocInfo mesh_doc_info;
  mesh_doc_info.set_directory("RESLT_MESH");
  // Distribute the problem
  bool report_stats=false;
  problem.distribute(element_partition,mesh_doc_info,report_stats);
  // Optionally check and document the halo schemes
  problem.check_halo_schemes(mesh_doc_info);
 #endif
  // Create label for output
  //------------------------
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory("RESLT");
  // Step number
  doc_info.number()=0;
  // Check if we're ready to go:
  //----------------------------
  cout << "\n\n\nProblem self-test ";
  if (problem.self_test()==0)
   {
    cout << "passed: Problem can be solved." << std::endl;
   }
  else
   {
    throw OomphLibError("Self test failed",
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
   }
  // Set the orientation of the "step" to 45 degrees
  TanhSolnForPoisson::TanPhi=1.0;
  // Initial value for the steepness of the "step"
  TanhSolnForPoisson::Alpha=1.0;
  // Do a couple of solutions for different forcing functions
  //---------------------------------------------------------
  unsigned nstep=4;
  for (unsigned istep=0;istep<nstep;istep++)
   {
    // Increase the steepness of the step:
    TanhSolnForPoisson::Alpha+=2.0;
    cout << "\n\nSolving for TanhSolnForPoisson::Alpha="
         << TanhSolnForPoisson::Alpha << std::endl << std::endl;
    // Solve the problem
    problem.newton_solve(3);
    //Output solution
    problem.doc_solution(doc_info);
    //Increment counter for solutions
    doc_info.number()++;
   }
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::finalize();
 #endif
 } //end of main
References TanhSolnForPoisson::Alpha, oomph::default_output_modifier, e(), MergeRestartFiles::filename, oomph::DocInfo::number(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, oomph::OomphInfo::output_modifier_pt(), problem, oomph::DocInfo::set_directory(), TanhSolnForPoisson::source_function(), oomph::OomphInfo::stream_pt(), oomph::Global_string_for_annotation::string(), and TanhSolnForPoisson::TanPhi.