MercuryDPM: oomph::NetFluxControlElement< ELEMENT > Class Template Reference
oomph::NetFluxControlElement< ELEMENT > Class Template Reference
#include <flux_control_elements_bk.h>
Public Member Functions
NetFluxControlElement (Mesh *flux_control_mesh_pt, double *prescribed_outflow_value_pt)
~NetFluxControlElement ()
Empty Destructor - Data gets deleted automatically.
NetFluxControlElement (const NetFluxControlElement &)
Broken copy constructor.
Data * pressure_data_pt () const
void fill_in_contribution_to_residuals (Vector< double > &residuals)
NetFluxControlElement (Mesh *flux_control_mesh_pt, double *prescribed_flux_value_pt)
~NetFluxControlElement ()
Empty Destructor - Data gets deleted automatically.
NetFluxControlElement (const NetFluxControlElement &dummy)=delete
Broken copy constructor.
unsigned dim () const
Broken assignment operator.
Data * pressure_data_pt () const
void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
unsigned ndof_types () const
unsigned & dof_number_for_unknown ()
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual unsigned self_test ()
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
Protected Member Functions
void fill_in_generic_residual_contribution_flux_control (Vector< double > &residuals)
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Private Attributes
Data * Pressure_data_pt
Mesh * Flux_control_mesh_pt
double * Prescribed_outflow_value_pt
Pointer to the value that stores the prescribed outflow.
double * Prescribed_flux_value_pt
Pointer to the value that stores the prescribed flux.
unsigned Dof_number_for_unknown
unsigned Dim
spatial dim of NS system
Additional Inherited Members
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<class ELEMENT>
class oomph::NetFluxControlElement< ELEMENT >
A class for the elements that applies a net fluid flux across a boundary by the imposition of an applied traction to the Navier–Stokes equations
/////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////// A class for an element that controls the net fluid flux across a boundary by the imposition of an unknown applied pressure to the Navier-Stokes equations. This element is used with a mesh of NavierStokesFluxControlElement elements which are attached to the boundary. Note: fill_in_contribution_to_jacobian() does not calculate Jacobian contributions for this element as they are calculated by NavierStokesFluxControlElement::fill_in_contribution_to_jacobian(...)
Constructor & Destructor Documentation
NetFluxControlElement() [1/4]
template<class ELEMENT > oomph::NetFluxControlElement< ELEMENT >::NetFluxControlElement (Mesh * flux_control_mesh_pt, double * prescribed_outflow_value_pt) inline
Constructor, which takes a mesh of the face elements which will impose the pressure to control the flux
                                                             :
   Flux_control_mesh_pt(flux_control_mesh_pt),
   Prescribed_outflow_value_pt(prescribed_outflow_value_pt)
   {
    // Construct Pressure_data_pt
    Pressure_data_pt = new Data(1);
    // Add the new Data to internal Data for this element
    add_internal_data(Pressure_data_pt);
    // pin pressure data
    // Pressure_data_pt->pin(0);
    // Loop over elements in the Flux_control_mesh to add
    // Data from the elements in the flux control
    // mesh to the external data for this element
    unsigned n_el =  Flux_control_mesh_pt->nelement();
    for (unsigned e=0; e<n_el; e++)
     {
      // Get pointer to the element
      FiniteElement * f_el_pt =
       Flux_control_mesh_pt->finite_element_pt(e);
      // Loop over the nodes
      unsigned n_node = f_el_pt->nnode();
      for(unsigned n=0;n<n_node;n++)
       {
        add_external_data(f_el_pt->node_pt(n));
       }
     }
   }
References oomph::GeneralisedElement::add_external_data(), oomph::GeneralisedElement::add_internal_data(), e(), oomph::Mesh::finite_element_pt(), oomph::NetFluxControlElement< ELEMENT >::Flux_control_mesh_pt, n, oomph::Mesh::nelement(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::NetFluxControlElement< ELEMENT >::Pressure_data_pt.
~NetFluxControlElement() [1/2]
template<class ELEMENT > oomph::NetFluxControlElement< ELEMENT >::~NetFluxControlElement () inline
Empty Destructor - Data gets deleted automatically.
 {}
NetFluxControlElement() [2/4]
template<class ELEMENT > oomph::NetFluxControlElement< ELEMENT >::NetFluxControlElement (const NetFluxControlElement< ELEMENT > &) inline
Broken copy constructor.
   {
    BrokenCopy::broken_copy("NetFluxControlElement");
   }
References oomph::BrokenCopy::broken_copy().
NetFluxControlElement() [3/4]
template<class ELEMENT > oomph::NetFluxControlElement< ELEMENT >::NetFluxControlElement (Mesh * flux_control_mesh_pt, double * prescribed_flux_value_pt) inline
Constructor takes a mesh of TemplateFreeNavierStokesFluxControlElementBase elements that impose the pressure to control the flux, plus a pointer to the double which contains the desired flux value
       : Flux_control_mesh_pt(flux_control_mesh_pt),
         Prescribed_flux_value_pt(prescribed_flux_value_pt)
     {
       // Construct Pressure_data_pt
       Pressure_data_pt = new Data(1);
       // Add the new Data to internal Data for this element
       add_internal_data(Pressure_data_pt);
       // There's no need to add the external data for this element since
       // this elements Jacobian contributions are calculated by the
       // NavierStokesFluxControlElements
       // Loop over elements in the Flux_control_mesh to add this element's
       // Data to the external Data in the elements in the flux control mesh
       unsigned n_el = Flux_control_mesh_pt->nelement();
       for (unsigned e = 0; e < n_el; e++)
       {
         // Get pointer to the element
         GeneralisedElement* el_pt = Flux_control_mesh_pt->element_pt(e);
         // Perform cast to TemplateFreeNavierStokesFluxControlElementBase
         // pointer
         TemplateFreeNavierStokesFluxControlElementBase* flux_el_pt =
           dynamic_cast<TemplateFreeNavierStokesFluxControlElementBase*>(el_pt);
         flux_el_pt->add_pressure_data(Pressure_data_pt);
       }
       // Default value for Dof_number_for_unknown, indiating that it's
       // uninitialised
       Dof_number_for_unknown = UINT_MAX;
     }
References oomph::GeneralisedElement::add_internal_data(), oomph::TemplateFreeNavierStokesFluxControlElementBase::add_pressure_data(), oomph::NetFluxControlElement< ELEMENT >::Dof_number_for_unknown, e(), oomph::Mesh::element_pt(), oomph::NetFluxControlElement< ELEMENT >::Flux_control_mesh_pt, oomph::Mesh::nelement(), and oomph::NetFluxControlElement< ELEMENT >::Pressure_data_pt.
~NetFluxControlElement() [2/2]
template<class ELEMENT > oomph::NetFluxControlElement< ELEMENT >::~NetFluxControlElement () inline
Empty Destructor - Data gets deleted automatically.
 {}
NetFluxControlElement() [4/4]
template<class ELEMENT > oomph::NetFluxControlElement< ELEMENT >::NetFluxControlElement (const NetFluxControlElement< ELEMENT > & dummy) delete
Broken copy constructor.
Member Function Documentation
dim()
template<class ELEMENT > unsigned oomph::NetFluxControlElement< ELEMENT >::dim () const inline
Broken assignment operator.
Spatial dimension of the problem
     {
       return Dim;
     }
References oomph::NetFluxControlElement< ELEMENT >::Dim.
dof_number_for_unknown()
template<class ELEMENT > unsigned& oomph::NetFluxControlElement< ELEMENT >::dof_number_for_unknown () inline
Function to set / get the nodal value of the "DOF type" to which the degree of freedom in this element (the pressure that enforces the required volume flux!) is added to. This should be set to the Navier-Stokes pressure DOF type (usually the dimension of the problem, for example, in 3D, the DOF types for single-physics Navier-Stokes elements are usually labelled 0, 1, 2, 3 for u, v and w velocities and pressure respectively. It is important to note that this is dimension dependent, so should not be hard coded in!! In particularly, this should not simply be set to the dimension of the problem if there is further splitting of the velocity DOF types) if this element is added to a fluid mesh containing Navier-Stokes elements.
     {
       return Dof_number_for_unknown;
     }
References oomph::NetFluxControlElement< ELEMENT >::Dof_number_for_unknown.
Referenced by CollapsibleChannelProblem< ELEMENT >::setup_outflow_flux_control_elements().
fill_in_contribution_to_jacobian()
template<class ELEMENT > void oomph::NetFluxControlElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
This function returns the residuals, but adds nothing to the Jacobian as this element's Jacobian contributions are calculated by the NavierStokesFluxControlElements which impose the traction used to control the flux.
Reimplemented from oomph::GeneralisedElement.
     {
       // Call the generic routine
       fill_in_generic_residual_contribution_flux_control(residuals);
     }
References oomph::NetFluxControlElement< ELEMENT >::fill_in_generic_residual_contribution_flux_control().
fill_in_contribution_to_residuals() [1/2]
template<class ELEMENT > void oomph::NetFluxControlElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Add the element's contribution to its residual vector: The flow constraint. [Note: Jacobian is computed automatically by finite-differencing]
Reimplemented from oomph::GeneralisedElement.
  {
   // Initialise volume flux
   double volume_flux  = 0.0;
   // Loop over elements in Flux_control_mesh_pt and calculate flux
   unsigned n_el = Flux_control_mesh_pt->nelement();
   for (unsigned e=0; e<n_el; e++)
    {
     // Get a pointer to the element
     GeneralisedElement* el_pt = Flux_control_mesh_pt->element_pt(e);
     // Cast to NavierStokesFluxControlElement
     NavierStokesFluxControlElement<ELEMENT>* flux_control_el_pt =
      dynamic_cast<NavierStokesFluxControlElement<ELEMENT>* >(el_pt);
     // Add the elemental volume flux
     volume_flux += flux_control_el_pt->get_volume_flux();
    }
   residuals[0] = volume_flux - *Prescribed_outflow_value_pt;
  }
References e(), oomph::Mesh::element_pt(), oomph::NetFluxControlElement< ELEMENT >::Flux_control_mesh_pt, oomph::NavierStokesFluxControlElement< ELEMENT >::get_volume_flux(), oomph::Mesh::nelement(), and oomph::NetFluxControlElement< ELEMENT >::Prescribed_outflow_value_pt.
fill_in_contribution_to_residuals() [2/2]
template<class ELEMENT > void oomph::NetFluxControlElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Add the element's contribution to its residual vector: i.e. the flux constraint.
Reimplemented from oomph::GeneralisedElement.
     {
       // Call the generic routine
       fill_in_generic_residual_contribution_flux_control(residuals);
     }
References oomph::NetFluxControlElement< ELEMENT >::fill_in_generic_residual_contribution_flux_control().
fill_in_generic_residual_contribution_flux_control()
template<class ELEMENT > void oomph::NetFluxControlElement< ELEMENT >::fill_in_generic_residual_contribution_flux_control (Vector< double > & residuals) inline protected
This function returns the residuals for the flux control master element.
     {
       // Initialise volume flux
       double volume_flux = 0.0;
       // Loop over elements in Flux_control_mesh_pt and calculate flux
       unsigned n_el = Flux_control_mesh_pt->nelement();
       for (unsigned e = 0; e < n_el; e++)
       {
         // Get a pointer to the element
         GeneralisedElement* el_pt = Flux_control_mesh_pt->element_pt(e);
         // Cast to NavierStokesFluxControlElement
         TemplateFreeNavierStokesFluxControlElementBase* flux_control_el_pt = 0;
         flux_control_el_pt =
           dynamic_cast<TemplateFreeNavierStokesFluxControlElementBase*>(el_pt);
 #ifdef PARANOID
         if (flux_control_el_pt == 0)
         {
           throw OomphLibError("Element must be used with a mesh of "
                               "NavierStokesFluxControlElements",
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         // Add the elemental volume flux
         volume_flux += flux_control_el_pt->get_volume_flux();
       }
       residuals[0] += *Prescribed_flux_value_pt - volume_flux;
     }
References e(), oomph::Mesh::element_pt(), oomph::NetFluxControlElement< ELEMENT >::Flux_control_mesh_pt, oomph::TemplateFreeNavierStokesFluxControlElementBase::get_volume_flux(), oomph::Mesh::nelement(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::NetFluxControlElement< ELEMENT >::Prescribed_flux_value_pt.
Referenced by oomph::NetFluxControlElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::NetFluxControlElement< ELEMENT >::fill_in_contribution_to_residuals().
get_dof_numbers_for_unknowns()
template<class ELEMENT > void oomph::NetFluxControlElement< ELEMENT >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> & dof_lookup_list) const inline virtual
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the "DOF type" that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) The single degree of freedom is given the DOF type number of Dof_number_for_unknown since it's expected this unknown is added to the Navier-Stokes pressure DOF block (it is also assumed that the user has set the Dof_number_for_unknown variable to the velocity DOF type using the function dof_number_for_unknown()).
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::NetFluxControlElementForWomersleyPressureControl.
     {
 #ifdef PARANOID
       if (Dof_number_for_unknown == UINT_MAX)
       {
         std::ostringstream error_message;
         error_message << "Dof_number_for_unknown hasn't been set yet!\n"
                       << "Please do so using the dof_number_for_unknown()\n"
                       << "access function\n";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // pair to store dof lookup prior to being added to list
       std::pair<unsigned, unsigned> dof_lookup;
       dof_lookup.first = this->eqn_number(0);
       dof_lookup.second = Dof_number_for_unknown;
       // add to list
       dof_lookup_list.push_front(dof_lookup);
     }
References oomph::NetFluxControlElement< ELEMENT >::Dof_number_for_unknown, oomph::GeneralisedElement::eqn_number(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
ndof_types()
template<class ELEMENT > unsigned oomph::NetFluxControlElement< ELEMENT >::ndof_types () const inline virtual
The number of "DOF types" that degrees of freedom in this element are sub-divided into - it's set to Dof_number_for_unknown+1 because it's expected this element is added to a fluid mesh containing navier stokes elements
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::NetFluxControlElementForWomersleyPressureControl.
     {
 #ifdef PARANOID
       if (Dof_number_for_unknown == UINT_MAX)
       {
         std::ostringstream error_message;
         error_message << "Dof_number_for_unknown hasn't been set yet!\n"
                       << "Please do so using the dof_number_for_unknown()\n"
                       << "access function\n";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return Dof_number_for_unknown + 1;
     }
References oomph::NetFluxControlElement< ELEMENT >::Dof_number_for_unknown, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
pressure_data_pt() [1/2]
template<class ELEMENT > Data* oomph::NetFluxControlElement< ELEMENT >::pressure_data_pt () const inline
Function return pointer to the Data object whose single value is the pressure applied by the elements in Flux_control_mesh_pt
 {return Pressure_data_pt;}
References oomph::NetFluxControlElement< ELEMENT >::Pressure_data_pt.
Referenced by UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_parallel_flow_lagrange_elements(), oomph::NetFluxControlElementForWomersleyPressureControl::NetFluxControlElementForWomersleyPressureControl(), and CollapsibleChannelProblem< ELEMENT >::setup_outflow_flux_control_elements().
pressure_data_pt() [2/2]
template<class ELEMENT > Data* oomph::NetFluxControlElement< ELEMENT >::pressure_data_pt () const inline
Function to return a pointer to the Data object whose single value is the pressure applied by the NavierStokesFluxControlElement elements
     {
       return Pressure_data_pt;
     }
References oomph::NetFluxControlElement< ELEMENT >::Pressure_data_pt.
Member Data Documentation
Dim
template<class ELEMENT > unsigned oomph::NetFluxControlElement< ELEMENT >::Dim private
spatial dim of NS system
Referenced by oomph::NetFluxControlElement< ELEMENT >::dim().
Dof_number_for_unknown
template<class ELEMENT > unsigned oomph::NetFluxControlElement< ELEMENT >::Dof_number_for_unknown private
The id number of the "DOF type" to which the degree of freedom in this element is added to. This should be set to the number id of the Navier-Stokes pressure DOF block (which is dimension dependent!) if this element is added to a fluid mesh containing navier stokes elements
Referenced by oomph::NetFluxControlElement< ELEMENT >::dof_number_for_unknown(), oomph::NetFluxControlElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::NetFluxControlElement< ELEMENT >::ndof_types(), and oomph::NetFluxControlElement< ELEMENT >::NetFluxControlElement().
Flux_control_mesh_pt
template<class ELEMENT > Mesh * oomph::NetFluxControlElement< ELEMENT >::Flux_control_mesh_pt private
Mesh of elements which impose a pressure which controls the net flux
Mesh of elements which impose the pressure which controls the net flux
Referenced by oomph::NetFluxControlElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::NetFluxControlElement< ELEMENT >::fill_in_generic_residual_contribution_flux_control(), and oomph::NetFluxControlElement< ELEMENT >::NetFluxControlElement().
Prescribed_flux_value_pt
template<class ELEMENT > double* oomph::NetFluxControlElement< ELEMENT >::Prescribed_flux_value_pt private
Pointer to the value that stores the prescribed flux.
Referenced by oomph::NetFluxControlElement< ELEMENT >::fill_in_generic_residual_contribution_flux_control().
Prescribed_outflow_value_pt
template<class ELEMENT > double* oomph::NetFluxControlElement< ELEMENT >::Prescribed_outflow_value_pt private
Pointer to the value that stores the prescribed outflow.
Referenced by oomph::NetFluxControlElement< ELEMENT >::fill_in_contribution_to_residuals().
Pressure_data_pt
template<class ELEMENT > Data * oomph::NetFluxControlElement< ELEMENT >::Pressure_data_pt private
The number of "blocks" that degrees of freedom in this element are sub-divided into
IMPORTANT: This is not even the correct function name! Because this appears to be untested (it will break if tested!), I will comment this out. Please re-implement if required in the future. The correct function signature is: unsigned ndof_types() const Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the "block" that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Pressure=1 since we expect to add this unknown to the pressure block
IMPORTANT: This is not even the correct function name I have no self tests for this, because it appears to be not tested, I will comment this out, the correct function signature is: void get_dof_numbers_for_unknowns(std::list<std::pair<unsigned long, unsigned> >& block_lookup_list) const Data object whose single value is the pressure applied by the elements in the Flux_control_mesh_pt
Data object whose single value is the pressure applied by the elements in the Flux_control_mesh_pt
Referenced by oomph::NetFluxControlElement< ELEMENT >::NetFluxControlElement(), and oomph::NetFluxControlElement< ELEMENT >::pressure_data_pt().
The documentation for this class was generated from the following files:
flux_control_elements_bk.h
navier_stokes_flux_control_elements.h