MercuryDPM: Eigen::selfadjoint_product_selector< MatrixType, OtherType, UpLo, false > Struct Template Reference
Eigen::selfadjoint_product_selector< MatrixType, OtherType, UpLo, false > Struct Template Reference
#include <SelfadjointProduct.h>
Static Public Member Functions
static void run (MatrixType &mat, const OtherType &other, const typename MatrixType::Scalar &alpha)
Member Function Documentation
run()
template<typename MatrixType , typename OtherType , int UpLo> static void Eigen::selfadjoint_product_selector< MatrixType, OtherType, UpLo, false >::run (MatrixType & mat, const OtherType & other, const typename MatrixType::Scalar & alpha) inline static
{
     typedef typename MatrixType::Scalar Scalar;
     typedef internal::blas_traits<OtherType> OtherBlasTraits;
     typedef typename OtherBlasTraits::DirectLinearAccessType ActualOtherType;
     typedef internal::remove_all_t<ActualOtherType> ActualOtherType_;
     internal::add_const_on_value_type_t<ActualOtherType> actualOther = OtherBlasTraits::extract(other.derived());
     Scalar actualAlpha = alpha * OtherBlasTraits::extractScalarFactor(other.derived());
     enum {
       IsRowMajor = (internal::traits<MatrixType>::Flags & RowMajorBit) ? 1 : 0,
       OtherIsRowMajor = ActualOtherType_::Flags & RowMajorBit ? 1 : 0
     };
     Index size = mat.cols();
     Index depth = actualOther.cols();
     typedef internal::gemm_blocking_space<IsRowMajor ? RowMajor : ColMajor, Scalar, Scalar,
                                           MatrixType::MaxColsAtCompileTime, MatrixType::MaxColsAtCompileTime,
                                           ActualOtherType_::MaxColsAtCompileTime>
         BlockingType;
     BlockingType blocking(size, size, depth, 1, false);
     internal::general_matrix_matrix_triangular_product<
         Index, Scalar, OtherIsRowMajor ? RowMajor : ColMajor,
         OtherBlasTraits::NeedToConjugate && NumTraits<Scalar>::IsComplex, Scalar, OtherIsRowMajor ? ColMajor : RowMajor,
         (!OtherBlasTraits::NeedToConjugate) && NumTraits<Scalar>::IsComplex, IsRowMajor ? RowMajor : ColMajor,
         MatrixType::InnerStrideAtCompileTime, UpLo>::run(size, depth, actualOther.data(), actualOther.outerStride(),
                                                          actualOther.data(), actualOther.outerStride(), mat.data(),
                                                          mat.innerStride(), mat.outerStride(), actualAlpha, blocking);
   }
References alpha, Eigen::ColMajor, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::cols(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::data(), Eigen::RowMajor, Eigen::RowMajorBit, Eigen::run(), and size.
The documentation for this struct was generated from the following file:
SelfadjointProduct.h