MercuryDPM: elastic_two_layer_interface_axisym.cc File Reference
elastic_two_layer_interface_axisym.cc File Reference
#include "generic.h"
#include "axisym_navier_stokes.h"
#include "navier_stokes.h"
#include "fluid_interface.h"
#include "constitutive.h"
#include "solid.h"
#include "oomph_crbond_bessel.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class ElasticRefineableTwoLayerMesh< ELEMENT >
class InterfaceProblem< ELEMENT, TIMESTEPPER >
Single axisymmetric fluid interface problem in rectangular domain.
Namespaces
Global_Physical_Variables
Global variables.
Functions
int main (int argc, char *argv[])
Driver code for axisymmetric two fluid interface problem.
Variables
double Global_Physical_Variables::St = 1.0
Strouhal number.
double Global_Physical_Variables::Viscosity_Ratio = 0.1
double Global_Physical_Variables::Density_Ratio = 0.5
Vector< double > Global_Physical_Variables::G (3) = 1.0
Direction of gravity.
Function Documentation
main()
int main (int argc , char * argv[])
Driver code for axisymmetric two fluid interface problem.
/////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
Maximum time
Duration of timestep
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // -----------------------------------------------------------------
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // -----------------------------------------------------------------
  // Are we performing a validation run?
  CommandLineArgs::specify_command_line_flag("--validation");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Check that definition of Womersley number is consistent with those
  // of the Reynolds and Strouhal numbers
  if(Global_Physical_Variables::ReSt !=
     Global_Physical_Variables::Re*Global_Physical_Variables::St)
   {
    std::ostringstream error_stream;
    error_stream << "Definition of Global_Physical_Variables::ReSt is "
                 << "inconsistant with those\n"
                 << "of Global_Physical_Variables::Re and "
                 << "Global_Physical_Variables::St." << std::endl;
    throw OomphLibError(error_stream.str(),
                        OOMPH_CURRENT_FUNCTION,OOMPH_EXCEPTION_LOCATION);
   }
  double t_max = 1.2;
  const double dt = 0.005;
  // If we are doing validation run, use smaller number of timesteps
  if(CommandLineArgs::command_line_flag_has_been_set("--validation"))
   {
    t_max = 0.01;
   }
  // Set direction of gravity (vertically downwards)
  Global_Physical_Variables::G[0] = 0.0;
  Global_Physical_Variables::G[1] = -1.0;
  Global_Physical_Variables::G[2] = 0.0;
  // Set up the elastic test problem with AxisymmetricQCrouzeixRaviartElements,
  // using the BDF<2> timestepper
  InterfaceProblem<RefineablePseudoSolidNodeUpdateElement<
  RefineableAxisymmetricQCrouzeixRaviartElement,
   RefineableQPVDElement<2,3> >,BDF<2> > problem;
  // Run the unsteady simulation
  problem.unsteady_run(t_max,dt);
 } // End of main
References oomph::CommandLineArgs::command_line_flag_has_been_set(), oomph::CommandLineArgs::doc_specified_flags(), Global_Physical_Variables::G, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::CommandLineArgs::parse_and_assign(), problem, Global_Physical_Variables::Re, Global_Physical_Variables::ReSt, Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), and Global_Physical_Variables::St.