MercuryDPM: Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true > Class Template Reference
Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true > Class Template Reference
#include <JacobiSVD.h>
Public Types
enum { WorkspaceSize = internal::traits<SVDType>::MatrixUColsAtCompileTime , MaxWorkspaceSize = internal::traits<SVDType>::MatrixUMaxColsAtCompileTime }
typedef MatrixType::Scalar Scalar
typedef JacobiSVD< MatrixType, Options > SVDType
typedef Matrix< Scalar, 1, WorkspaceSize, RowMajor, 1, MaxWorkspaceSize > WorkspaceType
Public Member Functions
void allocate (const SVDType &svd)
template<typename Xpr >
bool run (SVDType &svd, const Xpr &matrix)
Private Types
typedef ColPivHouseholderQR< MatrixType > QRType
Private Attributes
QRType m_qr
WorkspaceType m_workspace
Member Typedef Documentation
QRType
template<typename MatrixType , int Options> typedef ColPivHouseholderQR<MatrixType> Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::QRType private
Scalar
template<typename MatrixType , int Options> typedef MatrixType::Scalar Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::Scalar
SVDType
template<typename MatrixType , int Options> typedef JacobiSVD<MatrixType, Options> Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::SVDType
WorkspaceType
template<typename MatrixType , int Options> typedef Matrix<Scalar, 1, WorkspaceSize, RowMajor, 1, MaxWorkspaceSize> Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::WorkspaceType
Member Enumeration Documentation
anonymous enum
template<typename MatrixType , int Options> anonymous enum
Enumerator
WorkspaceSize
MaxWorkspaceSize
        {
     WorkspaceSize = internal::traits<SVDType>::MatrixUColsAtCompileTime,
     MaxWorkspaceSize = internal::traits<SVDType>::MatrixUMaxColsAtCompileTime
   };
Member Function Documentation
allocate()
template<typename MatrixType , int Options> void Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate (const SVDType & svd) inline
{
     if (svd.rows() != m_qr.rows() || svd.cols() != m_qr.cols()) {
       internal::destroy_at(&m_qr);
       internal::construct_at(&m_qr, svd.rows(), svd.cols());
     }
     if (svd.m_computeFullU)
       m_workspace.resize(svd.rows());
     else if (svd.m_computeThinU)
       m_workspace.resize(svd.cols());
   }
References Eigen::internal::construct_at(), Eigen::internal::destroy_at(), and svd().
run()
template<typename MatrixType , int Options> template<typename Xpr > bool Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run (SVDType & svd, const Xpr & matrix) inline
{
     if (matrix.rows() > matrix.cols()) {
       m_qr.compute(matrix);
       svd.m_workMatrix = m_qr.matrixQR().block(0, 0, matrix.cols(), matrix.cols()).template triangularView<Upper>();
       if (svd.m_computeFullU)
         m_qr.householderQ().evalTo(svd.m_matrixU, m_workspace);
       else if (svd.m_computeThinU) {
         svd.m_matrixU.setIdentity(matrix.rows(), matrix.cols());
         m_qr.householderQ().applyThisOnTheLeft(svd.m_matrixU, m_workspace);
       }
       if (svd.computeV()) svd.m_matrixV = m_qr.colsPermutation();
       return true;
     }
     return false;
   }
References matrix(), and svd().
Member Data Documentation
m_qr
template<typename MatrixType , int Options> QRType Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::m_qr private
m_workspace
template<typename MatrixType , int Options> WorkspaceType Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::m_workspace private
The documentation for this class was generated from the following file:
JacobiSVD.h