MercuryDPM: SolidifyingLiquidMigrationWilletSpecies Class Reference
SolidifyingLiquidMigrationWilletSpecies Class Reference
SolidifyingLiquidMigrationWilletSpecies contains the parameters used to describe a linear irreversible short-range force.
#include <SolidifyingLiquidMigrationWilletSpecies.h>
Public Types
typedef SolidifyingLiquidMigrationWilletInteraction InteractionType
The correct Interaction type for this AdhesiveForceSpecies.
Public Types inherited from LiquidMigrationWilletSpecies
typedef LiquidMigrationWilletInteraction InteractionType
The correct Interaction type for this AdhesiveForceSpecies.
Public Member Functions
SolidifyingLiquidMigrationWilletSpecies ()
The default constructor.
SolidifyingLiquidMigrationWilletSpecies (const SolidifyingLiquidMigrationWilletSpecies &s)
The default copy constructor.
~SolidifyingLiquidMigrationWilletSpecies ()
The default destructor.
void read (std::istream &is)
Reads the species properties from an input stream.
void write (std::ostream &os) const
Writes the species properties to an output stream.
std::string getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
void mix (SolidifyingLiquidMigrationWilletSpecies *S, SolidifyingLiquidMigrationWilletSpecies *T)
creates default values for mixed species
void setBondDissipation (Mdouble bondDissipation)
Mdouble getBondDissipation () const
void setBondForceMax (Mdouble bondForceMax)
Mdouble getBondForceMax () const
void setSolidFraction (Mdouble solidFraction)
Mdouble getSolidFraction () const
Public Member Functions inherited from LiquidMigrationWilletSpecies
LiquidMigrationWilletSpecies ()
The default constructor.
LiquidMigrationWilletSpecies (const LiquidMigrationWilletSpecies &s)
The default copy constructor.
~LiquidMigrationWilletSpecies ()
The default destructor.
void read (std::istream &is)
Reads the species properties from an input stream.
void write (std::ostream &os) const
Writes the species properties to an output stream.
std::string getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
void mix (LiquidMigrationWilletSpecies *S, LiquidMigrationWilletSpecies *T)
creates default values for mixed species
void setInteractionDistance ()
returns the largest separation distance at which adhesive short-range forces can occur.
void setLiquidBridgeVolumeMax (Mdouble liquidBridgeVolume)
used to set the Volume of the liquid bridge.
Mdouble getLiquidBridgeVolumeMax () const
used to access the Volume of the liquid bridge.
void setLiquidBridgeVolumeMin (Mdouble)
used to set the Volume of the liquid bridge.
Mdouble getLiquidBridgeVolumeMin () const
used to access the Volume of the liquid bridge.
void setDistributionCoefficient (Mdouble distributionCoefficient)
used to set the distribution coefficient of the liquid.
Mdouble getDistributionCoefficient () const
used to access the surface tension of the liquid.
void setSurfaceTension (Mdouble surfaceTension)
used to set the surface tension of the liquid.
Mdouble getSurfaceTension () const
used to access the surface tension of the liquid.
void setContactAngle (Mdouble contactAngle)
used to set the contact angle between particle and liquid bridge surface (in radians)
Mdouble getContactAngle () const
used to access the contact angle between particle and liquid bridge surface.
Public Member Functions inherited from BaseForce
BaseSpecies * getBaseSpecies () const
void setBaseSpecies (BaseSpecies *baseSpecies)
Private Attributes
Mdouble bondDissipation_
dissipation in bond
Mdouble bondForceMax_
adhesion force at zero overlap
Mdouble solidFraction_
Different from bondInteraction:
Detailed Description
SolidifyingLiquidMigrationWilletSpecies contains the parameters used to describe a linear irreversible short-range force.
See SolidifyingLiquidMigrationWilletInteraction::computeForce for a description of the force law.
Member Typedef Documentation
InteractionType
typedef SolidifyingLiquidMigrationWilletInteraction SolidifyingLiquidMigrationWilletSpecies::InteractionType
The correct Interaction type for this AdhesiveForceSpecies.
Constructor & Destructor Documentation
SolidifyingLiquidMigrationWilletSpecies() [1/2]
SolidifyingLiquidMigrationWilletSpecies::SolidifyingLiquidMigrationWilletSpecies ()
The default constructor.
Default constructor for gluable species. Sets default values for all relevant parameters. Note: if the stiffness of particles is left as zero, no force will be felt during interaction with other particles
Parameters
[in] s the species that is copied
 {
     bondForceMax_ = 0;
     bondDissipation_ = 0;
     solidFraction_ = 0;
 }
References bondDissipation_, bondForceMax_, and solidFraction_.
SolidifyingLiquidMigrationWilletSpecies() [2/2]
SolidifyingLiquidMigrationWilletSpecies::SolidifyingLiquidMigrationWilletSpecies (const SolidifyingLiquidMigrationWilletSpecies & s)
The default copy constructor.
Parameters
[in] the species that is copied
                                                                                                                                  : LiquidMigrationWilletSpecies(s)
 {
     bondForceMax_ = s.bondForceMax_;
     bondDissipation_ = s.bondDissipation_;
     solidFraction_ = s.solidFraction_;
 }
References bondDissipation_, bondForceMax_, s, and solidFraction_.
~SolidifyingLiquidMigrationWilletSpecies()
SolidifyingLiquidMigrationWilletSpecies::~SolidifyingLiquidMigrationWilletSpecies ()
The default destructor.
 {
 }
Member Function Documentation
getBaseName()
std::string SolidifyingLiquidMigrationWilletSpecies::getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
Returns
a string containing the name of the species (minus the word "Species")
 {
     return "Solidifying" + LiquidMigrationWilletSpecies::getBaseName();
 }
References LiquidMigrationWilletSpecies::getBaseName().
getBondDissipation()
Mdouble SolidifyingLiquidMigrationWilletSpecies::getBondDissipation () const inline
{
         return bondDissipation_;
     }
References bondDissipation_.
getBondForceMax()
Mdouble SolidifyingLiquidMigrationWilletSpecies::getBondForceMax () const inline
{
         return bondForceMax_;
     }
References bondForceMax_.
Referenced by SolidifyingLiquidMigrationWilletInteraction::bond(), and SolidifyingLiquidMigrationWilletInteraction::getElasticEnergy().
getSolidFraction()
Mdouble SolidifyingLiquidMigrationWilletSpecies::getSolidFraction () const inline
{
         return solidFraction_;
     }
References solidFraction_.
Referenced by SolidifyingLiquidMigrationWilletInteraction::addLiquidBridgeVolume(), and SolidifyingLiquidMigrationWilletInteraction::setLiquidBridgeVolume().
mix()
void SolidifyingLiquidMigrationWilletSpecies::mix (SolidifyingLiquidMigrationWilletSpecies * S, SolidifyingLiquidMigrationWilletSpecies * T)
creates default values for mixed species
For all parameters we assume that the harmonic mean of the parameters of the original two species is a sensible default.
Parameters
[in] S,T the two species whose properties are mixed to create the new species
 {
     LiquidMigrationWilletSpecies::mix(S,T);
     bondForceMax_ = BaseSpecies::average(S->getBondForceMax(), T->getBondForceMax());
     bondDissipation_ = BaseSpecies::average(S->getBondDissipation(), T->getBondDissipation());
 }
References BaseSpecies::average(), bondDissipation_, bondForceMax_, LiquidMigrationWilletSpecies::mix(), and oomph::QuadTreeNames::S.
read()
void SolidifyingLiquidMigrationWilletSpecies::read (std::istream & is)
Reads the species properties from an input stream.
Parameters
[in] is input stream (typically the restart file)
 {
     LiquidMigrationWilletSpecies::read(is);
     std::string dummy;
     is >> dummy >> bondForceMax_;
     is >> dummy >> bondDissipation_;
     is >> dummy >> solidFraction_;
 }
References bondDissipation_, bondForceMax_, LiquidMigrationWilletSpecies::read(), solidFraction_, and oomph::Global_string_for_annotation::string().
setBondDissipation()
void SolidifyingLiquidMigrationWilletSpecies::setBondDissipation (Mdouble bondDissipation) inline
{
         logger.assert_debug(bondDissipation >= 0, "Error in setBondDissipation");
         bondDissipation_ = bondDissipation;
     }
References bondDissipation_, and logger.
setBondForceMax()
void SolidifyingLiquidMigrationWilletSpecies::setBondForceMax (Mdouble bondForceMax) inline
{
         logger.assert_debug(bondForceMax >= 0, "Error in setBondForceMax");
         bondForceMax_ = bondForceMax;
     }
References bondForceMax_, and logger.
setSolidFraction()
void SolidifyingLiquidMigrationWilletSpecies::setSolidFraction (Mdouble solidFraction) inline
{
         logger.assert_debug(solidFraction >= 0, "Error in setBondForceMax");
         solidFraction_ = solidFraction;
     }
References logger, and solidFraction_.
write()
void SolidifyingLiquidMigrationWilletSpecies::write (std::ostream & os) const
Writes the species properties to an output stream.
Parameters
[out] os output stream (typically the restart file)
 {
     LiquidMigrationWilletSpecies::write(os);
     os << " bondForceMax " << bondForceMax_;
     os << " bondDissipation " << bondDissipation_;
     os << " solidFraction " << solidFraction_;
 }
References bondDissipation_, bondForceMax_, solidFraction_, and LiquidMigrationWilletSpecies::write().
Member Data Documentation
bondDissipation_
Mdouble SolidifyingLiquidMigrationWilletSpecies::bondDissipation_ private
dissipation in bond
Referenced by getBondDissipation(), mix(), read(), setBondDissipation(), SolidifyingLiquidMigrationWilletSpecies(), and write().
bondForceMax_
Mdouble SolidifyingLiquidMigrationWilletSpecies::bondForceMax_ private
adhesion force at zero overlap
Referenced by getBondForceMax(), mix(), read(), setBondForceMax(), SolidifyingLiquidMigrationWilletSpecies(), and write().
solidFraction_
Mdouble SolidifyingLiquidMigrationWilletSpecies::solidFraction_ private
Different from bondInteraction:
Referenced by getSolidFraction(), read(), setSolidFraction(), SolidifyingLiquidMigrationWilletSpecies(), and write().
The documentation for this class was generated from the following files:
SolidifyingLiquidMigrationWilletSpecies.h
SolidifyingLiquidMigrationWilletSpecies.cc