MercuryDPM: CompareNodeCoordinatesX Class Reference
CompareNodeCoordinatesX Class Reference
Public Member Functions
int operator() (Node *const &node1_pt, Node *const &node2_pt)
The actual comparison operator.
int operator() (Node *const &node1_pt, Node *const &node2_pt)
The actual comparison operator.
Detailed Description
//////////////////////////////////////////////////////// //////////////////////////////////////////////////////// ////////////////////////////////////////////////////////
Member Function Documentation
operator()() [1/2]
int CompareNodeCoordinatesX::operator() (Node *const & node1_pt, Node *const & node2_pt) inline
The actual comparison operator.
   {
    unsigned n_dim = node1_pt->ndim();
    if(n_dim != node2_pt->ndim())
     {
      throw OomphLibError("Can't compare two nodes of different dimension",
                          OOMPH_CURRENT_FUNCTION,
                          OOMPH_EXCEPTION_LOCATION);
     }
    //Make sure to handle the finite precision problems
    return node1_pt->x(0) < node2_pt->x(0);
   }
References oomph::Node::ndim(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Node::x().
operator()() [2/2]
int CompareNodeCoordinatesX::operator() (Node *const & node1_pt, Node *const & node2_pt) inline
The actual comparison operator.
   {
    unsigned n_dim = node1_pt->ndim();
    if(n_dim != node2_pt->ndim())
     {
      throw OomphLibError("Can't compare two nodes of different dimension",
                          OOMPH_CURRENT_FUNCTION,
                          OOMPH_EXCEPTION_LOCATION);
     }
    //Make sure to handle the finite precision problems
    return node1_pt->x(0) < node2_pt->x(0);
   }
References oomph::Node::ndim(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Node::x().
The documentation for this class was generated from the following files:
two_dim.cc
two_dim_hex.cc