MercuryDPM: oomph::QuarterCircleSectorDomain Class Reference
oomph::QuarterCircleSectorDomain Class Reference
#include <quarter_circle_sector_domain.h>
Public Types
typedef double(* BLSquashFctPt) (const double &s)
Public Member Functions
QuarterCircleSectorDomain (GeomObject *boundary_geom_object_pt, const double &xi_lo, const double &fract_mid, const double &xi_hi)
QuarterCircleSectorDomain (const QuarterCircleSectorDomain &)=delete
Broken copy constructor.
void operator= (const QuarterCircleSectorDomain &)=delete
Broken assignment operator.
~QuarterCircleSectorDomain ()
Destructor: empty; cleanup done in base class.
BLSquashFctPt & bl_squash_fct_pt ()
double s_squashed (const double &s)
void macro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
Public Member Functions inherited from oomph::Domain
Domain ()
Constructor.
Domain (const Domain &)=delete
Broken copy constructor.
void operator= (const Domain &)=delete
Broken assignment operator.
virtual ~Domain ()
MacroElement * macro_element_pt (const unsigned &i)
Access to i-th macro element.
unsigned nmacro_element ()
Number of macro elements in domain.
void output (const std::string &filename, const unsigned &nplot)
Output macro elements.
void output (std::ostream &outfile, const unsigned &nplot)
Output macro elements.
virtual void macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void output_macro_element_boundaries (const std::string &filename, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
void output_macro_element_boundaries (std::ostream &outfile, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
virtual void dmacro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void dmacro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void dmacro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void d2macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
Private Member Functions
void r_top_left_N (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of top left macro element zeta \(\in [-1,1] \).
void r_top_left_W (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of top left macro element zeta \(\in [-1,1] \).
void r_top_left_S (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of top left macro element zeta \(\in [-1,1] \).
void r_top_left_E (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of top left macro element zeta \(\in [-1,1] \).
void r_bot_right_N (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of bottom right macro element zeta \(\in [-1,1] \).
void r_bot_right_W (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of bottom right macro element zeta \(\in [-1,1] \).
void r_bot_right_S (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of bottom right macro element zeta \(\in [-1,1] \).
void r_bot_right_E (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of bottom right macro element zeta \(\in [-1,1] \).
void r_centr_N (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of central box macro element zeta \(\in [-1,1] \).
void r_centr_E (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of central box macro element zeta \(\in [-1,1] \).
void r_centr_S (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of central box macro element zeta \(\in [-1,1] \).
void r_centr_W (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of central box macro element zeta \(\in [-1,1] \).
Static Private Member Functions
static double default_BL_squash_fct (const double &s)
Private Attributes
double Xi_lo
Lower limit for the (1D) coordinates along the wall.
double Fract_mid
Fraction along wall where outer ring is to be divided.
double Xi_hi
Upper limit for the (1D) coordinates along the wall.
GeomObject * Wall_pt
Pointer to geometric object that represents the curved wall.
BLSquashFctPt BL_squash_fct_pt
Additional Inherited Members
Protected Attributes inherited from oomph::Domain
Vector< MacroElement * > Macro_element_pt
Vector of pointers to macro elements.
Detailed Description
Circular sector as domain. Domain is bounded by curved boundary which is represented by a GeomObject. Domain is parametrised by three macro elements.
Member Typedef Documentation
BLSquashFctPt
typedef double(* oomph::QuarterCircleSectorDomain::BLSquashFctPt) (const double &s)
Typedef for function pointer for function that squashes the outer two macro elements towards the wall by mapping the input value of the "radial" macro element coordinate to the return value
Constructor & Destructor Documentation
QuarterCircleSectorDomain() [1/2]
oomph::QuarterCircleSectorDomain::QuarterCircleSectorDomain (GeomObject * boundary_geom_object_pt, const double & xi_lo, const double & fract_mid, const double & xi_hi) inline
Constructor: Pass boundary object and start and end coordinates and fraction along boundary object where outer ring is divided.
       : Xi_lo(xi_lo),
         Fract_mid(fract_mid),
         Xi_hi(xi_hi),
         Wall_pt(boundary_geom_object_pt),
         BL_squash_fct_pt(&default_BL_squash_fct)
     {
       // There are three macro elements
       unsigned nmacro = 3;
       // Resize
       Macro_element_pt.resize(nmacro);
       // Create macro elements
       for (unsigned i = 0; i < nmacro; i++)
       {
         Macro_element_pt[i] = new QMacroElement<2>(this, i);
       }
     }
References i, and oomph::Domain::Macro_element_pt.
QuarterCircleSectorDomain() [2/2]
oomph::QuarterCircleSectorDomain::QuarterCircleSectorDomain (const QuarterCircleSectorDomain &) delete
Broken copy constructor.
~QuarterCircleSectorDomain()
oomph::QuarterCircleSectorDomain::~QuarterCircleSectorDomain () inline
Destructor: empty; cleanup done in base class.
 {}
Member Function Documentation
bl_squash_fct_pt()
BLSquashFctPt& oomph::QuarterCircleSectorDomain::bl_squash_fct_pt () inline
Function pointer for function that squashes the outer two macro elements towards the wall by mapping the input value of the "radial" macro element coordinate to the return value
     {
       return BL_squash_fct_pt;
     }
References BL_squash_fct_pt.
Referenced by oomph::QuarterCircleSectorMesh< ELEMENT >::bl_squash_fct_pt().
default_BL_squash_fct()
static double oomph::QuarterCircleSectorDomain::default_BL_squash_fct (const double & s) inline static private
Default for function that squashes the outer two macro elements towards the wall by mapping the input value of the "radial" macro element coordinate to the return value: Identity.
     {
       return s;
     }
References s.
macro_element_boundary()
void oomph::QuarterCircleSectorDomain::macro_element_boundary (const unsigned & t, const unsigned & imacro, const unsigned & idirect, const Vector< double > & s, Vector< double > & f) virtual
Vector representation of the i_macro-th macro element boundary i_direct (N/S/W/E) at time level t (t=0: present; t>0: previous): f(s). Note that the local coordinate s is a 1D Vector rather than a scalar – this is unavoidable because this function implements the pure virtual function in the Domain base class.
////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// Vector representation of the imacro-th macro element boundary idirect (N/S/W/E) at time level t (t=0: present; t>0: previous): f(s)
Implements oomph::Domain.
   {
 #ifdef WARN_ABOUT_SUBTLY_CHANGED_OOMPH_INTERFACES
     // Warn about time argument being moved to the front
     OomphLibWarning(
       "Order of function arguments has changed between versions 0.8 and 0.85",
       "QuarterCircleSectorDomain::macro_element_boundary(...)",
       OOMPH_EXCEPTION_LOCATION);
 #endif
     // Which macro element?
     // --------------------
     switch (imacro)
     {
       using namespace QuadTreeNames;
         // Macro element 0: Central box
       case 0:
         // Which direction?
         if (idirect == N)
         {
           r_centr_N(t, s, f);
         }
         else if (idirect == S)
         {
           r_centr_S(t, s, f);
         }
         else if (idirect == W)
         {
           r_centr_W(t, s, f);
         }
         else if (idirect == E)
         {
           r_centr_E(t, s, f);
         }
         else
         {
           std::ostringstream error_stream;
           error_stream << "idirect is " << idirect << " not one of N, S, E, W"
                        << std::endl;
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
         break;
         // Macro element 1: Bottom right
       case 1:
         // Which direction?
         if (idirect == N)
         {
           r_bot_right_N(t, s, f);
         }
         else if (idirect == S)
         {
           r_bot_right_S(t, s, f);
         }
         else if (idirect == W)
         {
           r_bot_right_W(t, s, f);
         }
         else if (idirect == E)
         {
           r_bot_right_E(t, s, f);
         }
         else
         {
           std::ostringstream error_stream;
           error_stream << "idirect is " << idirect << " not one of N, S, E, W"
                        << std::endl;
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
         break;
         // Macro element 2:Top left
       case 2:
         // Which direction?
         if (idirect == N)
         {
           r_top_left_N(t, s, f);
         }
         else if (idirect == S)
         {
           r_top_left_S(t, s, f);
         }
         else if (idirect == W)
         {
           r_top_left_W(t, s, f);
         }
         else if (idirect == E)
         {
           r_top_left_E(t, s, f);
         }
         else
         {
           std::ostringstream error_stream;
           error_stream << "idirect is " << idirect << " not one of N, S, E, W"
                        << std::endl;
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
         break;
       default:
         // Error
         std::ostringstream error_stream;
         error_stream << "Wrong imacro " << imacro << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
   }
References Global_Physical_Variables::E, f(), N, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, r_bot_right_E(), r_bot_right_N(), r_bot_right_S(), r_bot_right_W(), r_centr_E(), r_centr_N(), r_centr_S(), r_centr_W(), r_top_left_E(), r_top_left_N(), r_top_left_S(), r_top_left_W(), s, oomph::QuadTreeNames::S, plotPSD::t, and oomph::QuadTreeNames::W.
operator=()
void oomph::QuarterCircleSectorDomain::operator= (const QuarterCircleSectorDomain &) delete
Broken assignment operator.
r_bot_right_E()
void oomph::QuarterCircleSectorDomain::r_bot_right_E (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of bottom right macro element zeta \(\in [-1,1] \).
Eastern edge of bottom right macro element.
   {
     Vector<double> x(1);
     // Coordinate along wall
     x[0] = Xi_lo + (Fract_mid * (Xi_hi - Xi_lo) - Xi_lo) * (s[0] + 1.0) * 0.5;
     Wall_pt->position(t, x, f);
   }
References f(), Fract_mid, oomph::GeomObject::position(), s, plotPSD::t, Wall_pt, plotDoE::x, Xi_hi, and Xi_lo.
Referenced by macro_element_boundary().
r_bot_right_N()
void oomph::QuarterCircleSectorDomain::r_bot_right_N (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of bottom right macro element zeta \(\in [-1,1] \).
Northern edge of bottom right macro element.
   {
     r_top_left_E(t, s, f);
   }
References f(), r_top_left_E(), s, and plotPSD::t.
Referenced by macro_element_boundary().
r_bot_right_S()
void oomph::QuarterCircleSectorDomain::r_bot_right_S (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of bottom right macro element zeta \(\in [-1,1] \).
Southern edge of bottom right macro element.
   {
     Vector<double> x(1);
     // Bottom right corner
     Vector<double> r_bot(2);
     x[0] = Xi_lo;
     Wall_pt->position(t, x, r_bot);
     f[0] = 0.5 * r_bot[0] * (1.0 + s_squashed(0.5 * (s[0] + 1.0)));
     f[1] = 0.0;
   }
References f(), oomph::GeomObject::position(), s, s_squashed(), plotPSD::t, Wall_pt, plotDoE::x, and Xi_lo.
Referenced by macro_element_boundary().
r_bot_right_W()
void oomph::QuarterCircleSectorDomain::r_bot_right_W (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of bottom right macro element zeta \(\in [-1,1] \).
Western edge of bottom right macro element.
   {
     Vector<double> x(1);
     // Top left corner
     Vector<double> r_top(2);
     x[0] = Xi_hi;
     Wall_pt->position(t, x, r_top);
     // Bottom right corner
     Vector<double> r_bot(2);
     x[0] = Xi_lo;
     Wall_pt->position(t, x, r_bot);
     f[0] = 0.5 * r_bot[0];
     f[1] = 0.5 * r_top[1] * 0.5 * (s[0] + 1.0);
   }
References f(), oomph::GeomObject::position(), s, plotPSD::t, Wall_pt, plotDoE::x, Xi_hi, and Xi_lo.
Referenced by macro_element_boundary(), and r_centr_E().
r_centr_E()
void oomph::QuarterCircleSectorDomain::r_centr_E (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of central box macro element zeta \(\in [-1,1] \).
Eastern edge of central box.
   {
     r_bot_right_W(t, s, f);
   }
References f(), r_bot_right_W(), s, and plotPSD::t.
Referenced by macro_element_boundary().
r_centr_N()
void oomph::QuarterCircleSectorDomain::r_centr_N (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of central box macro element zeta \(\in [-1,1] \).
Northern edge of central box.
   {
     r_top_left_S(t, s, f);
   }
References f(), r_top_left_S(), s, and plotPSD::t.
Referenced by macro_element_boundary().
r_centr_S()
void oomph::QuarterCircleSectorDomain::r_centr_S (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of central box macro element zeta \(\in [-1,1] \).
Southern edge of central box.
   {
     Vector<double> x(1);
     // Bottom right corner
     Vector<double> r_bot(2);
     x[0] = Xi_lo;
     Wall_pt->position(t, x, r_bot);
     f[0] = 0.5 * r_bot[0] * 0.5 * (s[0] + 1.0);
     f[1] = 0.0;
   }
References f(), oomph::GeomObject::position(), s, plotPSD::t, Wall_pt, plotDoE::x, and Xi_lo.
Referenced by macro_element_boundary().
r_centr_W()
void oomph::QuarterCircleSectorDomain::r_centr_W (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of central box macro element zeta \(\in [-1,1] \).
Western edge of central box.
   {
     Vector<double> x(1);
     // Top left corner
     Vector<double> r_top(2);
     x[0] = Xi_hi;
     Wall_pt->position(t, x, r_top);
     f[0] = 0.0;
     f[1] = 0.5 * r_top[1] * 0.5 * (s[0] + 1.0);
   }
References f(), oomph::GeomObject::position(), s, plotPSD::t, Wall_pt, plotDoE::x, and Xi_hi.
Referenced by macro_element_boundary().
r_top_left_E()
void oomph::QuarterCircleSectorDomain::r_top_left_E (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of top left macro element zeta \(\in [-1,1] \).
Eastern edge of top left macro element \(s \in [-1,1] \).
   {
     Vector<double> x(1);
     // Top left corner
     Vector<double> r_top(2);
     x[0] = Xi_hi;
     Wall_pt->position(t, x, r_top);
     // Bottom right corner
     Vector<double> r_bot(2);
     x[0] = Xi_lo;
     Wall_pt->position(t, x, r_bot);
     // Halfway along wall
     Vector<double> r_half(2);
     x[0] = Xi_lo + Fract_mid * (Xi_hi - Xi_lo);
     Wall_pt->position(t, x, r_half);
     f[0] = 0.5 * (r_bot[0] + s_squashed(0.5 * (s[0] + 1.0)) *
                                (2.0 * r_half[0] - r_bot[0]));
     f[1] = 0.5 * (r_top[1] + s_squashed(0.5 * (s[0] + 1.0)) *
                                (2.0 * r_half[1] - r_top[1]));
   }
References f(), Fract_mid, oomph::GeomObject::position(), s, s_squashed(), plotPSD::t, Wall_pt, plotDoE::x, Xi_hi, and Xi_lo.
Referenced by macro_element_boundary(), and r_bot_right_N().
r_top_left_N()
void oomph::QuarterCircleSectorDomain::r_top_left_N (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of top left macro element zeta \(\in [-1,1] \).
Northern edge of top left macro element \(s \in [-1,1] \).
   {
     Vector<double> x(1);
     // Coordinate along wall
     x[0] = Xi_hi + (Fract_mid * (Xi_hi - Xi_lo) - Xi_hi) * 0.5 * (s[0] + 1.0);
     Wall_pt->position(t, x, f);
   }
References f(), Fract_mid, oomph::GeomObject::position(), s, plotPSD::t, Wall_pt, plotDoE::x, Xi_hi, and Xi_lo.
Referenced by macro_element_boundary().
r_top_left_S()
void oomph::QuarterCircleSectorDomain::r_top_left_S (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of top left macro element zeta \(\in [-1,1] \).
Southern edge of top left macro element \(s \in [-1,1] \).
   {
     Vector<double> x(1);
     // Top left corner
     Vector<double> r_top(2);
     x[0] = Xi_hi;
     Wall_pt->position(t, x, r_top);
     // Bottom right corner
     Vector<double> r_bot(2);
     x[0] = 0.0;
     Wall_pt->position(t, x, r_bot);
     f[0] = 0.5 * r_bot[0] * 0.5 * (s[0] + 1.0);
     f[1] = 0.5 * r_top[1];
   }
References f(), oomph::GeomObject::position(), s, plotPSD::t, Wall_pt, plotDoE::x, and Xi_hi.
Referenced by macro_element_boundary(), and r_centr_N().
r_top_left_W()
void oomph::QuarterCircleSectorDomain::r_top_left_W (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of top left macro element zeta \(\in [-1,1] \).
Western edge of top left macro element \(s \in [-1,1] \).
   {
     Vector<double> x(1);
     // Top left corner
     Vector<double> r_top(2);
     x[0] = Xi_hi;
     Wall_pt->position(t, x, r_top);
     f[0] = 0.0;
     f[1] = 0.5 * r_top[1] * (1.0 + s_squashed(0.5 * (s[0] + 1.0)));
   }
References f(), oomph::GeomObject::position(), s, s_squashed(), plotPSD::t, Wall_pt, plotDoE::x, and Xi_hi.
Referenced by macro_element_boundary().
s_squashed()
double oomph::QuarterCircleSectorDomain::s_squashed (const double & s) inline
Function that squashes the outer two macro elements towards the wall by mapping the input value of the "radial" macro element coordinate to the return value
     {
       return BL_squash_fct_pt(s);
     }
References BL_squash_fct_pt, and s.
Referenced by r_bot_right_S(), r_top_left_E(), and r_top_left_W().
Member Data Documentation
BL_squash_fct_pt
BLSquashFctPt oomph::QuarterCircleSectorDomain::BL_squash_fct_pt private
Function pointer for function that squashes the outer two macro elements towards the wall by mapping the input value of the "radial" macro element coordinate to the return value
Referenced by bl_squash_fct_pt(), and s_squashed().
Fract_mid
double oomph::QuarterCircleSectorDomain::Fract_mid private
Fraction along wall where outer ring is to be divided.
Referenced by r_bot_right_E(), r_top_left_E(), and r_top_left_N().
Wall_pt
GeomObject* oomph::QuarterCircleSectorDomain::Wall_pt private
Pointer to geometric object that represents the curved wall.
Referenced by r_bot_right_E(), r_bot_right_S(), r_bot_right_W(), r_centr_S(), r_centr_W(), r_top_left_E(), r_top_left_N(), r_top_left_S(), and r_top_left_W().
Xi_hi
double oomph::QuarterCircleSectorDomain::Xi_hi private
Upper limit for the (1D) coordinates along the wall.
Referenced by r_bot_right_E(), r_bot_right_W(), r_centr_W(), r_top_left_E(), r_top_left_N(), r_top_left_S(), and r_top_left_W().
Xi_lo
double oomph::QuarterCircleSectorDomain::Xi_lo private
Lower limit for the (1D) coordinates along the wall.
Referenced by r_bot_right_E(), r_bot_right_S(), r_bot_right_W(), r_centr_S(), r_top_left_E(), and r_top_left_N().
The documentation for this class was generated from the following file:
quarter_circle_sector_domain.h