MercuryDPM: SPHInteraction Class Reference
SPHInteraction Class Reference
Enables the use of SPH particles within MercuryDPM.
#include <SPHInteraction.h>
Public Types
typedef SPHNormalSpecies SpeciesType
An alias for SPHNormalSpecies.
Public Member Functions
SPHInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
Constructor.
SPHInteraction ()
SPHInteraction (const SPHInteraction &p)
Copy constructor.
~SPHInteraction () override
Destructor.
void computeNormalForce ()
Creates a copy of an object of this class. (Deep copy)
void read (std::istream &is) override
Interaction read function, which accepts an std::istream as input.
void write (std::ostream &os) const override
Interaction write function, which accepts an std::ostream as input.
std::string getBaseName () const
Returns the type/name of interaction (linear visco-elastic interaction).
Mdouble getElasticEnergy () const override
Returns the amount of energy stored in the spring due to head on collision.
const SPHNormalSpecies * getSpecies () const
Returns a const pointer of type LinearViscoelasticNormalSpecies*.
void copyHistoryInteraction ()
Mdouble getElasticEnergyAtEquilibrium (Mdouble adhesiveForce) const override
Public Member Functions inherited from BaseInteraction
BaseInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
A constructor takes the BaseInteractable objects which are interacting (come into contact) and time the interaction starts.
BaseInteraction ()
BaseInteraction (const BaseInteraction &p)
Copy constructor.
~BaseInteraction () override
The destructor. It removes this interactions from the objects that were interacting, and writes the time to a file when needed.
virtual void actionsOnErase ()
If an interaction needs to do something before it gets erased, add it here. E.g. Liquid bridges rupture at the end of their lifetime, and the liquid bridge volume has to be redistributed. The reason this action is not done in the destructor is that this action should not be taken when erasing ghost interactions.
virtual void computeForce ()
Virtual function that contains the force law between the two objects interacting.
void writeToFStat (std::ostream &os, Mdouble time) const
Writes forces data to the FStat file.
std::string getName () const override
Virtual function which allows interactions to be named.
void setDistance (Mdouble distance)
Sets the interaction distance between the two interacting objects.
void setNormal (Vec3D normal)
Sets the normal vector between the two interacting objects.
void setOverlap (Mdouble overlap)
Set the overlap between the two interacting object.
void setContactPoint (Vec3D contactPoint)
Set the location of the contact point between the two interacting objects.
void setTimeStamp (unsigned timeStamp)
Updates the time step of the interacting. Note, time steps used to find completed interactions.
void setSpecies (const BaseSpecies *species)
Set the Species of the interaction; note this can either be a Species or MixedSpecies.
void setP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void setI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
void importP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void importI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
Vec3D getIP () const
Vec3D getIC () const
Vec3D getCP () const
void setLagrangeMultiplier (Mdouble multiplier)
Mdouble getLagrangeMultiplier ()
void setHandler (InteractionHandler *handler)
Sets the pointer to the interaction hander which is storing this interaction.
InteractionHandler * getHandler () const
Gets a point to the interaction handlers to which this interaction belongs.
const Vec3D & getForce () const
Gets the current force (vector) between the two interacting objects.
const Vec3D & getTorque () const
Gets the current torque (vector) between the two interacting objects.
const Vec3D & getNormal () const
Gets the normal vector between the two interacting objects.
const Vec3D & getContactPoint () const
Gets constant reference to contact point (vector).
Mdouble getOverlap () const
Returns a Mdouble with the current overlap between the two interacting objects.
Mdouble getOverlapVolume () const
Returns the overlap volume between two interacting objects.
Mdouble getContactRadius () const
Returns a Mdouble with the current contact between the two interacting objects.
void removeFromHandler ()
Removes this interaction from its interaction hander.
void copySwitchPointer (const BaseInteractable *original, BaseInteractable *ghost) const
This copies the interactions of the original particle and replaces the original with the ghost copy.
void gatherContactStatistics ()
BaseInteractable * getP ()
Returns a pointer to first object involved in the interaction (normally a particle).
BaseInteractable * getI ()
Returns a pointer to the second object involved in the interaction (often a wall or a particle).
const BaseInteractable * getP () const
Returns a constant pointer to the first object involved in the interaction.
const BaseInteractable * getI () const
Returns a constant pointer to the second object involved in the interaction.
Mdouble getTimeStamp () const
Returns an Mdouble which is the time stamp of the interaction.
virtual void integrate (Mdouble timeStep)
integrates variables of the interaction which need to be integrate e.g. the tangential overlap.
virtual Mdouble getTangentialOverlap () const
get the length of the current tangential overlap
Mdouble getDistance () const
Returns an Mdouble which is the norm (length) of distance vector.
const Vec3D & getRelativeVelocity () const
Returns a constant reference to a vector of relative velocity.
Mdouble getNormalRelativeVelocity () const
Returns a double which is the norm (length) of the relative velocity vector.
Mdouble getAbsoluteNormalForce () const
Returns the absolute value of the norm (length) of the Normal force vector.
virtual BaseInteraction * copy () const =0
Makes a copy of the interaction and returns a pointer to the copy.
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseWall *I)
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseParticle *I)
unsigned int getMultiContactIdentifier () const
void setMultiContactIdentifier (unsigned int multiContactIdentifier_)
virtual void rotateHistory (Matrix3D &rotationMatrix)
When periodic particles are used, some interactions need certain history properties rotated (e.g. tangential springs). This is the function for that.
virtual void actionsAfterTimeStep ()
virtual unsigned getNumberOfFieldsVTK () const
virtual std::string getTypeVTK (unsigned i) const
virtual std::string getNameVTK (unsigned i) const
virtual std::vector< Mdouble > getFieldVTK (unsigned i) const
void addForce (Vec3D force)
add an force increment to the total force.
void addTorque (Vec3D torque)
add a torque increment to the total torque.
void setForce (Vec3D force)
set total force (this is used by the normal force, tangential forces are added use addForce)
void setTorque (Vec3D torque)
set the total force (this is used by the normal force, tangential torques are added use addTorque)
const BaseSpecies * getBaseSpecies () const
Return a constant point to BaseSpecies of the interaction.
virtual void createMPIType ()
virtual void * createMPIInteractionDataArray (unsigned int numberOfInteractions) const
virtual void deleteMPIInteractionDataArray (void *dataArray)
virtual void getMPIInteraction (void *historyDataArray, unsigned int index) const
copies the history interactions into the data array
virtual void getInteractionDetails (void *interactionDataArray, unsigned int index, unsigned int &identificationP, unsigned int &identificationI, bool &isWallInteraction, unsigned &timeStamp)
virtual void setMPIInteraction (void *interactionDataArray, unsigned int index, bool resetPointers)
void setBasicMPIInteractionValues (int P, int I, unsigned timeStamp, Vec3D force, Vec3D torque, bool isWallInteraction, bool resetPointers)
void setIdentificationP (unsigned int identification)
void setIdentificationI (int identification)
void setWallInteraction (bool flag)
unsigned int getIdentificationP ()
int getIdentificationI ()
bool isWallInteraction ()
virtual bool isBonded () const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Additional Inherited Members
Protected Member Functions inherited from BaseInteraction
virtual const Vec3D getTangentialForce () const
Mdouble getEffectiveRadius () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
Mdouble getEffectiveMass () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
void setRelativeVelocity (Vec3D relativeVelocity)
set the relative velocity of the current of the interactions.
void setNormalRelativeVelocity (Mdouble normalRelativeVelocit)
set the normal component of the relative velocity.
void setAbsoluteNormalForce (Mdouble absoluteNormalForce)
the absolute values of the norm (length) of the normal force
virtual void reverseHistory ()
When periodic particles some interaction need certain history properties reversing. This is the function for that.
void writeInteraction (std::ostream &os, bool created) const
Writes information about a interaction to the interaction file.
Detailed Description
Enables the use of SPH particles within MercuryDPM.
Member Typedef Documentation
SpeciesType
typedef SPHNormalSpecies SPHInteraction::SpeciesType
An alias for SPHNormalSpecies.
Constructor & Destructor Documentation
SPHInteraction() [1/3]
SPHInteraction::SPHInteraction (BaseInteractable * P, BaseInteractable * I, unsigned timeStamp)
Constructor.
Parameters
[in] P
[in] I
[in] timeStamp
         : BaseInteraction(P, I, timeStamp)
 {
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"LinearViscoelasticInteraction::LinearViscoelasticInteraction() finished"<<std::endl;
 #endif
 }
SPHInteraction() [2/3]
SPHInteraction::SPHInteraction ()
         : BaseInteraction()
 {
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"LinearViscoelasticInteraction::LinearViscoelasticInteraction() finished"<<std::endl;
 #endif
 }
SPHInteraction() [3/3]
SPHInteraction::SPHInteraction (const SPHInteraction & p)
Copy constructor.
Parameters
[in] p
         : BaseInteraction(p)
 {
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"LinearViscoelasticInteraction::LinearViscoelasticInteraction(const LinearViscoelasticInteraction& p) finished"<<std::endl;
 #endif
 }
~SPHInteraction()
SPHInteraction::~SPHInteraction () override
Destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"LinearViscoelasticInteraction::~LinearViscoelasticInteraction() finished"<<std::endl;
 #endif
 }
Member Function Documentation
computeNormalForce()
void SPHInteraction::computeNormalForce ()
Creates a copy of an object of this class. (Deep copy)
Computes the normal force caused due to normal collision between particles or particle-wall.
This is where the actually force law goes. In the case of SPH we are going to create an CG Point to evaluate the fields we need.
 {
     //Need add CGPoint object here
     // Compute the relative velocity vector of particle P w.r.t. I
     setRelativeVelocity(
             getP()->getVelocityAtContact(getContactPoint()) - getI()->getVelocityAtContact(getContactPoint()));
     // Compute the projection of vrel onto the normal (can be negative)
     setNormalRelativeVelocity(Vec3D::dot(getRelativeVelocity(), getNormal()));
     if (getOverlap() > 0) //if contact forces
     {
         const SPHNormalSpecies* species = getSpecies();
         Mdouble normalForce =
                 species->getStiffness() * getOverlap() - species->getDissipation() * getNormalRelativeVelocity();
         setAbsoluteNormalForce(std::abs(normalForce)); //used for further corce calculations;
         setForce(getNormal() * normalForce);
         setTorque(Vec3D(0.0, 0.0, 0.0));
     }
     else
     {
         setAbsoluteNormalForce(0.0);
         setForce(Vec3D(0.0, 0.0, 0.0));
         setTorque(Vec3D(0.0, 0.0, 0.0));
     }
 }
References abs(), Vec3D::dot(), BaseInteraction::getContactPoint(), SPHNormalSpecies::getDissipation(), BaseInteraction::getI(), BaseInteraction::getNormal(), BaseInteraction::getNormalRelativeVelocity(), BaseInteraction::getOverlap(), BaseInteraction::getP(), BaseInteraction::getRelativeVelocity(), getSpecies(), SPHNormalSpecies::getStiffness(), BaseInteraction::setAbsoluteNormalForce(), BaseInteraction::setForce(), BaseInteraction::setNormalRelativeVelocity(), BaseInteraction::setRelativeVelocity(), and BaseInteraction::setTorque().
copyHistoryInteraction()
void SPHInteraction::copyHistoryInteraction ()
getBaseName()
std::string SPHInteraction::getBaseName () const
Returns the type/name of interaction (linear visco-elastic interaction).
Returns
std::string
 {
     return "LinearViscoelastic";
 }
getElasticEnergy()
Mdouble SPHInteraction::getElasticEnergy () const override virtual
Returns the amount of energy stored in the spring due to head on collision.
Returns
Mdouble
Reimplemented from BaseInteraction.
 {
     if (getOverlap() > 0)
         return 0.5 * (getSpecies()->getStiffness() * mathsFunc::square(getOverlap()));
     else
         return 0.0;
 }
References BaseInteraction::getOverlap(), getSpecies(), SPHNormalSpecies::getStiffness(), and mathsFunc::square().
getElasticEnergyAtEquilibrium()
Mdouble SPHInteraction::getElasticEnergyAtEquilibrium (Mdouble adhesiveForce) const override virtual
Reimplemented from BaseInteraction.
 {
     double equilibriumOverlap = adhesiveForce / getSpecies()->getStiffness();
     return 0.5 * adhesiveForce * equilibriumOverlap;
 }
References getSpecies(), and SPHNormalSpecies::getStiffness().
getSpecies()
const SPHNormalSpecies * SPHInteraction::getSpecies () const
Returns a const pointer of type LinearViscoelasticNormalSpecies*.
Returns
const LinearViscoelasticNormalSpecies*
Todo:
you can remove this by adding the species to the Interaction instead of the base interaction
 {
     return static_cast<const SPHNormalSpecies*>(getBaseSpecies()->getNormalForce());
 }
References BaseInteraction::getBaseSpecies(), and BaseSpecies::getNormalForce().
Referenced by computeNormalForce(), getElasticEnergy(), and getElasticEnergyAtEquilibrium().
read()
void SPHInteraction::read (std::istream & is) override virtual
Interaction read function, which accepts an std::istream as input.
Calls the BaseInteraction() read function.
Parameters
[in,out] is
Reimplemented from BaseInteraction.
 {
     BaseInteraction::read(is);
 }
References BaseInteraction::read().
write()
void SPHInteraction::write (std::ostream & os) const override virtual
Interaction write function, which accepts an std::ostream as input.
Calls the BaseInteraction() write function.
Parameters
[in,out] os
Reimplemented from BaseInteraction.
 {
     BaseInteraction::write(os);
 }
References BaseInteraction::write().
The documentation for this class was generated from the following files:
SPHInteraction.h
SPHInteraction.cc