MercuryDPM: SphericalWall Class Reference
SphericalWall Class Reference
A infinite wall fills the half-space {point: (position_-point)*normal_<=0}.
#include <SphericalWall.h>
Public Member Functions
SphericalWall ()
Default constructor, the normal is infinitely long.
SphericalWall (const SphericalWall &w)
Copy constructor, copy the given wall.
SphericalWall (Mdouble radius, const ParticleSpecies *species)
Constructor setting values.
~SphericalWall () override
Default destructor.
SphericalWall * copy () const override
Wall copy method. It calls the copy constructor of this Wall, useful for polymorphism.
void setRadius (Mdouble radius)
Defines a spherical wall with radius r.
Mdouble getDistance (const Vec3D &otherPosition) const
Returns the distance of the wall to the particle.
Mdouble getRadius () const
Returns the distance of the wall to the particle.
bool getDistanceAndNormal (const BaseParticle &p, Mdouble &distance, Vec3D &normal_return) const override
Compute the distance from the wall for a given BaseParticle and return if there is a collision. If there is a collision, also return the normal vector.
void read (std::istream &is) override
Reads SphericalWall from a restart file.
void write (std::ostream &os) const override
Writes the SphericalWall to an output stream, usually a restart file.
std::string getName () const override
Returns the name of the object, in this case the string "SphericalWall".
Public Member Functions inherited from BaseWall
BaseWall ()
Default constructor.
BaseWall (const BaseWall &w)
Copy constructor.
~BaseWall () override
Default destructor.
virtual bool getDistanceNormalOverlap (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual bool getDistanceNormalOverlapSuperquadric (const SuperQuadricParticle &p, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual Vec3D getFurthestPointSuperQuadric (const Vec3D &normalBodyFixed, const Vec3D &axes, Mdouble eps1, Mdouble eps2) const
virtual void setHandler (WallHandler *handler)
A function which sets the WallHandler for this BaseWall.
WallHandler * getHandler () const
A function which returns the WallHandler that handles this BaseWall.
void setIndSpecies (unsigned int indSpecies) override
Define the species of this wall using the index of the species in the SpeciesHandler in this DPMBase.
void setSpecies (const ParticleSpecies *species)
Defines the species of the current wall.
bool isFixed () const override
void setForceControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity={0, 0, 0})
Slowly adjusts the force on a wall towards a specified goal, by adjusting (prescribing) the velocity of the wall.
virtual bool isLocal (Vec3D &min, Vec3D &max) const
bool getLinePlaneIntersect (Vec3D &intersect, const Vec3D &p0, const Vec3D &p1, const Vec3D &n, const Vec3D &p)
bool isInsideWallVTK (const Vec3D &point, const Vec3D &normal, const Vec3D &position) const
void projectOntoWallVTK (Vec3D &point0, const Vec3D &point1, const Vec3D &normal, const Vec3D &position) const
void intersectVTK (std::vector< Vec3D > &points, Vec3D normal, Vec3D position) const
virtual BaseInteraction * getInteractionWithSuperQuad (SuperQuadricParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler)
virtual void writeVTK (VTKContainer &vtk) const
void getVTK (std::vector< Vec3D > &points, std::vector< std::vector< double >> &triangleStrips)
const Vec3D getAxis () const
BaseInteraction * getInteractionWith (BaseParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler) override
Returns the interaction between this wall and a given particle, nullptr if there is no interaction.
virtual void actionsOnRestart ()
No implementation but can be overidden in its derived classes.
virtual void actionsAfterParticleGhostUpdate ()
No implementation but can be overidden in its derived classes.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
virtual void handleParticleRemoval (unsigned int id)
Handles the addition of particles to the particleHandler.
virtual void checkInteractions (InteractionHandler *interactionHandler, unsigned int timeStamp)
Check if all interactions are valid.
bool getVTKVisibility () const
void setVTKVisibility (bool vtkVisibility)
void addRenderedWall (BaseWall *w)
BaseWall * getRenderedWall (size_t i) const
std::vector< BaseWall * > getRenderedWalls () const
void removeRenderedWalls ()
void renderWall (VTKContainer &vtk)
void addParticlesAtWall (unsigned numElements=50)
void setVelocityControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity)
virtual void writeWallDetailsVTK (VTKData &data) const
virtual void computeWear ()
Public Member Functions inherited from BaseInteractable
BaseInteractable ()
Default BaseInteractable constructor.
BaseInteractable (const BaseInteractable &p)
Copy constructor.
~BaseInteractable () override
Destructor, it simply destructs the BaseInteractable and all the objects it contains.
unsigned int getIndSpecies () const
Returns the index of the species associated with the interactable object.
const ParticleSpecies * getSpecies () const
Returns a pointer to the species of this BaseInteractable.
void setSpecies (const ParticleSpecies *species)
Sets the species of this BaseInteractable.
const Vec3D & getForce () const
Returns the force on this BaseInteractable.
const Vec3D & getTorque () const
Returns the torque on this BaseInteractable.
void setForce (const Vec3D &force)
Sets the force on this BaseInteractable.
void setTorque (const Vec3D &torque)
Sets the torque on this BaseInteractable.
void addForce (const Vec3D &addForce)
Adds an amount to the force on this BaseInteractable.
void addTorque (const Vec3D &addTorque)
Adds an amount to the torque on this BaseInteractable.
virtual void resetForceTorque (int numberOfOMPthreads)
void sumForceTorqueOMP ()
const Vec3D & getPosition () const
Returns the position of this BaseInteractable.
const Quaternion & getOrientation () const
Returns the orientation of this BaseInteractable.
virtual void setPosition (const Vec3D &position)
Sets the position of this BaseInteractable.
void setOrientationViaNormal (Vec3D normal)
Sets the orientation of this BaseInteractable by defining the vector that results from the rotation of the (1,0,0) vector.
void setOrientationViaEuler (Vec3D eulerAngle)
Sets the orientation of this BaseInteractable by defining the euler angles.
virtual void setOrientation (const Quaternion &orientation)
Sets the orientation of this BaseInteractable.
virtual void move (const Vec3D &move)
Moves this BaseInteractable by adding an amount to the position.
virtual void rotate (const Vec3D &angularVelocityDt)
Rotates this BaseInteractable.
const std::vector< BaseInteraction * > & getInteractions () const
Returns a list of interactions which belong to this interactable.
void addInteraction (BaseInteraction *I)
Adds an interaction to this BaseInteractable.
bool removeInteraction (BaseInteraction *I)
Removes an interaction from this BaseInteractable.
void copyInteractionsForPeriodicParticles (const BaseInteractable &p)
Copies interactions to this BaseInteractable whenever a periodic copy made.
void setVelocity (const Vec3D &velocity)
set the velocity of the BaseInteractable.
void setAngularVelocity (const Vec3D &angularVelocity)
set the angular velocity of the BaseInteractble.
void addVelocity (const Vec3D &velocity)
adds an increment to the velocity.
void addAngularVelocity (const Vec3D &angularVelocity)
add an increment to the angular velocity.
virtual const Vec3D & getVelocity () const
Returns the velocity of this interactable.
virtual const Vec3D & getAngularVelocity () const
Returns the angular velocity of this interactable.
void setPrescribedPosition (const std::function< Vec3D(double)> &prescribedPosition)
Allows the position of an infinite mass interactable to be prescribed.
void applyPrescribedPosition (double time)
Computes the position from the user defined prescribed position function.
void setPrescribedVelocity (const std::function< Vec3D(double)> &prescribedVelocity)
Allows the velocity of an infinite mass interactable to be prescribed.
void applyPrescribedVelocity (double time)
Computes the velocity from the user defined prescribed velocity function.
void setPrescribedOrientation (const std::function< Quaternion(double)> &prescribedOrientation)
Allows the orientation of the infinite mass interactbale to be prescribed.
void applyPrescribedOrientation (double time)
Computes the orientation from the user defined prescribed orientation function.
void setPrescribedAngularVelocity (const std::function< Vec3D(double)> &prescribedAngularVelocity)
Allows the angular velocity of the infinite mass interactable to be prescribed.
void applyPrescribedAngularVelocity (double time)
Computes the angular velocity from the user defined prescribed angular velocity.
virtual const Vec3D getVelocityAtContact (const Vec3D &contact) const
Returns the velocity at the contact point, use by many force laws.
void integrateBeforeForceComputation (double time, double timeStep)
This is part of integrate routine for objects with infinite mass.
void integrateAfterForceComputation (double time, double timeStep)
This is part of the integration routine for objects with infinite mass.
virtual Mdouble getInvMass () const
virtual Mdouble getCurvature (const Vec3D &labFixedCoordinates) const
virtual bool isFaceContact (const Vec3D &normal) const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
Mdouble radius_
Additional Inherited Members
Static Public Member Functions inherited from BaseWall
static void addToVTK (const std::vector< Vec3D > &points, VTKContainer &vtk)
Takes the points provided and adds a triangle strip connecting these points to the vtk container.
Detailed Description
A infinite wall fills the half-space {point: (position_-point)*normal_<=0}.
This is a class defining walls. It defines the interaction of regular walls and periodic walls with particles as defined in Particle Modifications:
Thus, the surface of the wall is a plane through position position_ with normal_ the outward unit normal vector of the wall (pointing away from the particles, into the wall). Please note that this wall is infinite and straight.
A particle touches an infinite wall if (position_-point)*normal_<=radius.
Constructor & Destructor Documentation
SphericalWall() [1/3]
SphericalWall::SphericalWall ()
Default constructor, the normal is infinitely long.
 {
     radius_ = std::numeric_limits<double>::quiet_NaN();
     logger(DEBUG, "SphericalWall::SphericalWall ) finished");
 }
References DEBUG, logger, and radius_.
Referenced by copy().
SphericalWall() [2/3]
SphericalWall::SphericalWall (const SphericalWall & w)
Copy constructor, copy the given wall.
Parameters
[in] w SphericalWall that has to be copied.
First copy the attributes of the BaseWall, then copy the ones that are specific for the SphericalWall.
         : BaseWall(w)
 {
     radius_ = w.radius_;
     logger(DEBUG, "SphericalWall::SphericalWall(const SphericalWall &p) finished");
 }
References DEBUG, logger, radius_, and w.
SphericalWall() [3/3]
SphericalWall::SphericalWall (Mdouble radius, const ParticleSpecies * species)
Constructor setting values.
 {
     setRadius(radius);
 }
References UniformPSDSelfTest::radius, and setRadius().
~SphericalWall()
SphericalWall::~SphericalWall () override
Default destructor.
 {
     logger(DEBUG, "SphericalWall::~SphericalWall finished");
 }
References DEBUG, and logger.
Member Function Documentation
copy()
SphericalWall * SphericalWall::copy () const override virtual
Wall copy method. It calls the copy constructor of this Wall, useful for polymorphism.
Wall copy method. It calls the copy constructor of this Wall, useful for polymorphism
Implements BaseWall.
 {
     return new SphericalWall(*this);
 }
References SphericalWall().
getDistance()
Mdouble SphericalWall::getDistance (const Vec3D & otherPosition) const
Returns the distance of the wall to the particle.
Parameters
[in] otherPosition The position to which the distance must be computed to.
Returns
The distance of the wall to the particle.
 {
     return Vec3D::getLength(getPosition() - otherPosition);
 }
References Vec3D::getLength(), and BaseInteractable::getPosition().
getDistanceAndNormal()
bool SphericalWall::getDistanceAndNormal (const BaseParticle & p, Mdouble & distance, Vec3D & normal_return) const override virtual
Compute the distance from the wall for a given BaseParticle and return if there is a collision. If there is a collision, also return the normal vector.
Parameters
[in] p BaseParticle for which the distance to the wall must be computed.
[out] distance Distance between the particle and the wall.
[out] normal_return The normal of this wall, will only be set if there is a collision.
Returns
A boolean value for whether or not there is a collision.
First the distance is checked. If there is no collision, this function will return false and give the distance. If there is a collision, the function will return true and give the distance and the normal vector of this wall. Since this function should be called before calculating any Particle-Wall interactions, it can also be used to set the normal vector in case of curved walls.
Implements BaseWall.
 {
     normal_return = p.getPosition() - getPosition();
     distance = Vec3D::getLength(normal_return) - radius_;
     if (distance >= p.getWallInteractionRadius(this))
         return false;
     normal_return /= distance + radius_;
     //logger(WARN,"p% q% q% q% q%", getPosition(), p.getPosition(), normal_return, distance, p.getWallInteractionRadius(this));
     return true;
 }
References Vec3D::getLength(), BaseInteractable::getPosition(), p, and radius_.
getName()
std::string SphericalWall::getName () const override virtual
Returns the name of the object, in this case the string "SphericalWall".
Returns
The string "SphericalWall", which is the name of this class.
Implements BaseObject.
 {
     return "SphericalWall";
 }
getRadius()
Mdouble SphericalWall::getRadius () const
Returns the distance of the wall to the particle.
Returns
The radius of the wall .
 {
     return radius_;
 }
References radius_.
read()
void SphericalWall::read (std::istream & is) override virtual
Reads SphericalWall from a restart file.
Parameters
[in] is The input stream from which the SphericalWall is read.
Reimplemented from BaseWall.
 {
     BaseWall::read(is);
     std::string dummy;
     is >> dummy >> radius_;
 }
References radius_, BaseWall::read(), and oomph::Global_string_for_annotation::string().
setRadius()
void SphericalWall::setRadius (Mdouble radius)
Defines a spherical wall with radius r.
 {
     logger.assert_debug(radius >= 0, "radius=% cannot be negative", radius);
     radius_ = radius;
 }
References logger, UniformPSDSelfTest::radius, and radius_.
Referenced by SphericalWall().
write()
void SphericalWall::write (std::ostream & os) const override virtual
Writes the SphericalWall to an output stream, usually a restart file.
Parameters
[in] os The output stream the SphericalWall is written to.
Reimplemented from BaseWall.
 {
     BaseWall::write(os);
     os << " radius " << radius_;
 }
References radius_, and BaseWall::write().
Member Data Documentation
radius_
Mdouble SphericalWall::radius_ private
This is the factor used to rescale the normal given by the user to a unit vector. It is only used by the deprecated function move(Mdouble).
Referenced by getDistanceAndNormal(), getRadius(), read(), setRadius(), SphericalWall(), and write().
The documentation for this class was generated from the following files:
SphericalWall.h
SphericalWall.cc