MercuryDPM: pow_helper< Exponent, ExpIsInteger > Struct Template Reference
pow_helper< Exponent, ExpIsInteger > Struct Template Reference
Static Public Member Functions
static bool is_integer_impl (const Exponent &exp)
static bool is_odd_impl (const Exponent &exp)
Member Function Documentation
is_integer_impl()
template<typename Exponent , bool ExpIsInteger = NumTraits<Exponent>::IsInteger> static bool pow_helper< Exponent, ExpIsInteger >::is_integer_impl (const Exponent & exp) inline static
 { return (numext::isfinite)(exp) && exp == numext::floor(exp); }
References Eigen::bfloat16_impl::exp(), Eigen::bfloat16_impl::floor(), and isfinite.
Referenced by is_integer().
is_odd_impl()
template<typename Exponent , bool ExpIsInteger = NumTraits<Exponent>::IsInteger> static bool pow_helper< Exponent, ExpIsInteger >::is_odd_impl (const Exponent & exp) inline static
{
     Exponent exp_div_2 = exp / Exponent(2);
     Exponent floor_exp_div_2 = numext::floor(exp_div_2);
     return exp_div_2 != floor_exp_div_2;
   }
References Eigen::bfloat16_impl::exp(), and Eigen::bfloat16_impl::floor().
Referenced by is_odd().
The documentation for this struct was generated from the following file:
array_cwise.cpp