MercuryDPM: oomph::RectangleWithHoleAndAnnularRegionDomain Class Reference
oomph::RectangleWithHoleAndAnnularRegionDomain Class Reference
#include <rectangle_with_moving_cylinder_mesh.template.h>
Public Member Functions
RectangleWithHoleAndAnnularRegionDomain (GeomObject *cylinder_pt, const double &annular_region_radius, const double &length)
~RectangleWithHoleAndAnnularRegionDomain ()
Destructor: Empty; macro elements are deleted in base class destructor.
void project_point_on_cylinder_to_annular_boundary (const unsigned &time, const Vector< double > &xi, Vector< double > &r)
Rectangular domain with circular whole.
void project_point_on_cylinder_to_annular_boundary (const double &time, const Vector< double > &xi, Vector< double > &r)
void linear_interpolate (const Vector< double > &left, const Vector< double > &right, const double &s, Vector< double > &f)
void macro_element_boundary (const double &time, const unsigned &m, const unsigned &direction, const Vector< double > &s, Vector< double > &f)
void macro_element_boundary (const unsigned &time, const unsigned &m, const unsigned &direction, const Vector< double > &s, Vector< double > &f)
Public Member Functions inherited from oomph::Domain
Domain ()
Constructor.
Domain (const Domain &)=delete
Broken copy constructor.
void operator= (const Domain &)=delete
Broken assignment operator.
virtual ~Domain ()
MacroElement * macro_element_pt (const unsigned &i)
Access to i-th macro element.
unsigned nmacro_element ()
Number of macro elements in domain.
void output (const std::string &filename, const unsigned &nplot)
Output macro elements.
void output (std::ostream &outfile, const unsigned &nplot)
Output macro elements.
void macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void output_macro_element_boundaries (const std::string &filename, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
void output_macro_element_boundaries (std::ostream &outfile, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
virtual void dmacro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void dmacro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void dmacro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void d2macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
Private Attributes
Vector< double > Lower_left
Lower left corner of rectangle.
Vector< double > Lower_right
Lower right corner of rectangle.
Vector< double > Lower_mid_left
Where the "radial" line from circle meets lower boundary on left.
Vector< double > Lower_mid_right
Where the "radial" line from circle meets lower boundary on right.
Vector< double > Upper_left
Upper left corner of rectangle.
Vector< double > Upper_right
Upper right corner of rectangle.
Vector< double > Upper_mid_left
Where the "radial" line from circle meets upper boundary on left.
Vector< double > Upper_mid_right
Where the "radial" line from circle meets upper boundary on right.
GeomObject * Cylinder_pt
Pointer to geometric object that represents the central cylinder.
double Annular_region_radius
Additional Inherited Members
Protected Attributes inherited from oomph::Domain
Vector< MacroElement * > Macro_element_pt
Vector of pointers to macro elements.
Detailed Description
Rectangular domain with circular whole DRAIG: This looks like a redefinition of the RectangleWithHoleAndAnnularRegionDomain in src/meshes but it creates 8 macro-elements instead of 4 macro-elements and creates an annular region around the cylinder. It's probably a good idea to rename this class to avoid ambiguity and a name clash...
Constructor & Destructor Documentation
RectangleWithHoleAndAnnularRegionDomain()
oomph::RectangleWithHoleAndAnnularRegionDomain::RectangleWithHoleAndAnnularRegionDomain (GeomObject * cylinder_pt, const double & annular_region_radius, const double & length) inline
Constructor. Pass pointer to geometric object that represents the cylinder, the length of the (square) domain. The GeomObject must be parametrised such that \(\zeta \in [0,2\pi]\) sweeps around the circumference in anticlockwise direction.
       : Cylinder_pt(cylinder_pt), Annular_region_radius(annular_region_radius)
     {
       // Vertices of rectangle
       Lower_left.resize(2);
       Lower_left[0] = -0.5 * length;
       Lower_left[1] = -0.5 * length;
       Upper_left.resize(2);
       Upper_left[0] = -0.5 * length;
       Upper_left[1] = 0.5 * length;
       Lower_right.resize(2);
       Lower_right[0] = 0.5 * length;
       Lower_right[1] = -0.5 * length;
       Upper_right.resize(2);
       Upper_right[0] = 0.5 * length;
       Upper_right[1] = 0.5 * length;
       // Coordinates of points where the "radial" lines from central
       // cylinder meet the upper and lower boundaries
       Lower_mid_left.resize(2);
       Lower_mid_left[0] = -0.5 * length;
       Lower_mid_left[1] = -0.5 * length;
       Upper_mid_left.resize(2);
       Upper_mid_left[0] = -0.5 * length;
       Upper_mid_left[1] = 0.5 * length;
       Lower_mid_right.resize(2);
       Lower_mid_right[0] = 0.5 * length;
       Lower_mid_right[1] = -0.5 * length;
       Upper_mid_right.resize(2);
       Upper_mid_right[0] = 0.5 * length;
       Upper_mid_right[1] = 0.5 * length;
       // The number of macro elements
       unsigned n_macro_element = 8;
       // There are four macro elements
       Macro_element_pt.resize(n_macro_element);
       // Build the 2D macro elements
       for (unsigned i = 0; i < n_macro_element; i++)
       {
         // Create the i-th macro element
         Macro_element_pt[i] = new QMacroElement<2>(this, i);
       }
     } // End of RectangleWithHoleAndAnnularRegionDomain
References i, Lower_left, Lower_mid_left, Lower_mid_right, Lower_right, oomph::Domain::Macro_element_pt, Upper_left, Upper_mid_left, Upper_mid_right, and Upper_right.
Referenced by oomph::RectangleWithHoleAndAnnularRegionMesh< ELEMENT >::RectangleWithHoleAndAnnularRegionMesh().
~RectangleWithHoleAndAnnularRegionDomain()
oomph::RectangleWithHoleAndAnnularRegionDomain::~RectangleWithHoleAndAnnularRegionDomain () inline
Destructor: Empty; macro elements are deleted in base class destructor.
 {}
Member Function Documentation
linear_interpolate()
void oomph::RectangleWithHoleAndAnnularRegionDomain::linear_interpolate (const Vector< double > & left, const Vector< double > & right, const double & s, Vector< double > & f) inline
Helper function to interpolate linearly between the "right" and "left" points; \(s \in [-1,1] \)
     {
       // Loop over the coordinates
       for (unsigned i = 0; i < 2; i++)
       {
         // Get the linear interpolation of the two points
         f[i] = left[i] + (right[i] - left[i]) * 0.5 * (s + 1.0);
       }
     } // End of linear_interpolate
References f(), i, and s.
Referenced by macro_element_boundary(), and oomph::RefineableQuadMeshWithMovingCylinder< MyRefineableQTaylorHoodElement >::RefineableQuadMeshWithMovingCylinder().
macro_element_boundary() [1/2]
void oomph::RectangleWithHoleAndAnnularRegionDomain::macro_element_boundary (const double & time, const unsigned & m, const unsigned & direction, const Vector< double > & s, Vector< double > & f) virtual
Parametrisation of macro element boundaries: f(s) is the position vector to macro-element m's boundary in the specified direction [N/S/E/W] at the specified discrete time level (time=0: present; time>0: previous)
Reimplemented from oomph::Domain.
   {
 #ifdef WARN_ABOUT_SUBTLY_CHANGED_OOMPH_INTERFACES
     // Create warning about time argument being moved to the front
     std::string error_message_string =
       "Order of function arguments has changed ";
     // Finish the string off
     error_message_string += "between versions 0.8 and 0.85";
     // Output a warning
     OomphLibWarning(
       error_message_string, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
 #endif
     // Lagrangian coordinate along surface of cylinder
     Vector<double> xi(1, 0.0);
     // Point on circle
     Vector<double> point_on_circle(2, 0.0);
     // Point on the outer boundary of the annular region
     Vector<double> point_on_annular_ring(2, 0.0);
     // Use the QuadTree enumeration for face directions
     using namespace QuadTreeNames;
     // Switch on the macro element
     switch (m)
     {
       // Macro element 0 is immediately to the left of the cylinder, outside
       // the inner annular region
       case 0:
         // Switch on the direction
         switch (direction)
         {
           case N:
             xi[0] = 3.0 * atan(1.0);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(Upper_mid_left, point_on_annular_ring, s[0], f);
             break;
           case S:
             xi[0] = -3.0 * atan(1.0);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(Lower_mid_left, point_on_annular_ring, s[0], f);
             break;
           case W:
             linear_interpolate(Lower_mid_left, Upper_mid_left, s[0], f);
             break;
           case E:
             xi[0] = 5.0 * atan(1.0) - 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             project_point_on_cylinder_to_annular_boundary(time, xi, f);
             break;
           default:
             std::ostringstream error_stream;
             error_stream << "Direction is incorrect: " << direction
                          << std::endl;
             throw OomphLibError(error_stream.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
         }
         break;
       // Macro element 1 is immediately above the cylinder, outside
       // the inner annular region
       case 1:
         switch (direction)
         {
           case N:
             linear_interpolate(Upper_mid_left, Upper_mid_right, s[0], f);
             break;
           case S:
             xi[0] = 3.0 * atan(1.0) - 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             project_point_on_cylinder_to_annular_boundary(time, xi, f);
             break;
           case W:
             xi[0] = 3.0 * atan(1.0);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_annular_ring, Upper_mid_left, s[0], f);
             break;
           case E:
             xi[0] = 1.0 * atan(1.0);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_annular_ring, Upper_mid_right, s[0], f);
             break;
           default:
             std::ostringstream error_stream;
             error_stream << "Direction is incorrect:  " << direction
                          << std::endl;
             throw OomphLibError(error_stream.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
         }
         break;
       // Macro element 2 is immediately to the right of the cylinder, outside
       // the inner annular region
       case 2:
         switch (direction)
         {
           case N:
             xi[0] = 1.0 * atan(1.0);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_annular_ring, Upper_mid_right, s[0], f);
             break;
           case S:
             xi[0] = -1.0 * atan(1.0);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_annular_ring, Lower_mid_right, s[0], f);
             break;
           case W:
             xi[0] = -atan(1.0) + 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             project_point_on_cylinder_to_annular_boundary(time, xi, f);
             break;
           case E:
             linear_interpolate(Lower_mid_right, Upper_mid_right, s[0], f);
             break;
           default:
             std::ostringstream error_stream;
             error_stream << "Direction is incorrect:  " << direction
                          << std::endl;
             throw OomphLibError(error_stream.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
         }
         break;
       // Macro element 3 is immediately below cylinder, outside
       // the inner annular region
       case 3:
         switch (direction)
         {
           case N:
             xi[0] = -3.0 * atan(1.0) + 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             project_point_on_cylinder_to_annular_boundary(time, xi, f);
             break;
           case S:
             linear_interpolate(Lower_mid_left, Lower_mid_right, s[0], f);
             break;
           case W:
             xi[0] = -3.0 * atan(1.0);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(Lower_mid_left, point_on_annular_ring, s[0], f);
             break;
           case E:
             xi[0] = -1.0 * atan(1.0);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(Lower_mid_right, point_on_annular_ring, s[0], f);
             break;
           default:
             std::ostringstream error_stream;
             error_stream << "Direction is incorrect: " << direction
                          << std::endl;
             throw OomphLibError(error_stream.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
         }
         break;
       // Macro element 4, is immediately to the left of the cylinder
       // lying in the inner annular region
       case 4:
         // Switch on the face of the m-th macro element
         switch (direction)
         {
           case N:
             xi[0] = 3.0 * atan(1.0);
             Cylinder_pt->position(time, xi, point_on_circle);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_annular_ring, point_on_circle, s[0], f);
             break;
           case S:
             xi[0] = -3.0 * atan(1.0);
             Cylinder_pt->position(time, xi, point_on_circle);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_annular_ring, point_on_circle, s[0], f);
             break;
           case W:
             xi[0] = 5.0 * atan(1.0) - 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             project_point_on_cylinder_to_annular_boundary(time, xi, f);
             break;
           case E:
             xi[0] = 5.0 * atan(1.0) - 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             Cylinder_pt->position(time, xi, f);
             break;
           default:
             std::ostringstream error_stream;
             error_stream << "Direction is incorrect: " << direction
                          << std::endl;
             throw OomphLibError(error_stream.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
         }
         break;
       // Macro element 5, is immediately above the cylinder in the
       // inner annular region
       case 5:
         switch (direction)
         {
           case N:
             xi[0] = 3.0 * atan(1.0) - 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             project_point_on_cylinder_to_annular_boundary(time, xi, f);
             break;
           case S:
             xi[0] = 3.0 * atan(1.0) - 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             Cylinder_pt->position(time, xi, f);
             break;
           case W:
             xi[0] = 3.0 * atan(1.0);
             Cylinder_pt->position(time, xi, point_on_circle);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_circle, point_on_annular_ring, s[0], f);
             break;
           case E:
             xi[0] = 1.0 * atan(1.0);
             Cylinder_pt->position(time, xi, point_on_circle);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_circle, point_on_annular_ring, s[0], f);
             break;
           default:
             std::ostringstream error_stream;
             error_stream << "Direction is incorrect: " << direction
                          << std::endl;
             throw OomphLibError(error_stream.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
         }
         break;
       // Macro element 6, is immediately to the right of the cylinder
       // lying in the inner annular region
       case 6:
         switch (direction)
         {
           case N:
             xi[0] = 1.0 * atan(1.0);
             Cylinder_pt->position(time, xi, point_on_circle);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_circle, point_on_annular_ring, s[0], f);
             break;
           case S:
             xi[0] = -1.0 * atan(1.0);
             Cylinder_pt->position(time, xi, point_on_circle);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_circle, point_on_annular_ring, s[0], f);
             break;
           case W:
             xi[0] = -atan(1.0) + 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             Cylinder_pt->position(time, xi, f);
             break;
           case E:
             xi[0] = -atan(1.0) + 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             project_point_on_cylinder_to_annular_boundary(time, xi, f);
             break;
           default:
             std::ostringstream error_stream;
             error_stream << "Direction is incorrect: " << direction
                          << std::endl;
             throw OomphLibError(error_stream.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
         }
         break;
       // Macro element 7, is immediately below the cylinder in the
       // inner annular region
       case 7:
         switch (direction)
         {
           case N:
             xi[0] = -3.0 * atan(1.0) + 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             Cylinder_pt->position(time, xi, f);
             break;
           case S:
             xi[0] = -3.0 * atan(1.0) + 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             project_point_on_cylinder_to_annular_boundary(time, xi, f);
             break;
           case W:
             xi[0] = -3.0 * atan(1.0);
             Cylinder_pt->position(time, xi, point_on_circle);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_annular_ring, point_on_circle, s[0], f);
             break;
           case E:
             xi[0] = -1.0 * atan(1.0);
             Cylinder_pt->position(time, xi, point_on_circle);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_annular_ring, point_on_circle, s[0], f);
             break;
           default:
             std::ostringstream error_stream;
             error_stream << "Direction is incorrect: " << direction
                          << std::endl;
             throw OomphLibError(error_stream.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
         }
         break;
       default:
         std::ostringstream error_stream;
         error_stream << "Wrong macro element number" << m << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
   } // End of macro_element_boundary
References Eigen::bfloat16_impl::atan(), Global_Physical_Variables::E, f(), linear_interpolate(), Lower_mid_left, Lower_mid_right, m, N, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, project_point_on_cylinder_to_annular_boundary(), s, oomph::QuadTreeNames::S, oomph::Global_string_for_annotation::string(), Upper_mid_left, Upper_mid_right, and oomph::QuadTreeNames::W.
macro_element_boundary() [2/2]
void oomph::RectangleWithHoleAndAnnularRegionDomain::macro_element_boundary (const unsigned & time, const unsigned & m, const unsigned & direction, const Vector< double > & s, Vector< double > & f) virtual
Parametrisation of macro element boundaries: f(s) is the position vector to macro-element m's boundary in the specified direction [N/S/E/W] at the specified discrete time level (time=0: present; time>0: previous)
Implements oomph::Domain.
   {
 #ifdef WARN_ABOUT_SUBTLY_CHANGED_OOMPH_INTERFACES
     // Warn about time argument being moved to the front
     OomphLibWarning(
       "Order of function arguments has changed between versions 0.8 and 0.85",
       "RectangleWithHoleAndAnnularRegionDomain::macro_element_boundary(...)",
       OOMPH_EXCEPTION_LOCATION);
 #endif
     // Lagrangian coordinate along surface of cylinder
     Vector<double> xi(1, 0.0);
     // Point on circle
     Vector<double> point_on_circle(2, 0.0);
     // Point on the outer boundary of the annular region
     Vector<double> point_on_annular_ring(2, 0.0);
     // Use the QuadTree enumeration for face directions
     using namespace QuadTreeNames;
     // Switch on the macro element
     switch (m)
     {
       // Macro element 0 is immediately to the left of the cylinder, outside
       // the inner annular region
       case 0:
         // Switch on the direction
         switch (direction)
         {
           case N:
             xi[0] = 3.0 * atan(1.0);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(Upper_mid_left, point_on_annular_ring, s[0], f);
             break;
           case S:
             xi[0] = -3.0 * atan(1.0);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(Lower_mid_left, point_on_annular_ring, s[0], f);
             break;
           case W:
             linear_interpolate(Lower_mid_left, Upper_mid_left, s[0], f);
             break;
           case E:
             xi[0] = 5.0 * atan(1.0) - 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             project_point_on_cylinder_to_annular_boundary(time, xi, f);
             break;
           default:
             std::ostringstream error_stream;
             error_stream << "Direction is incorrect: " << direction
                          << std::endl;
             throw OomphLibError(error_stream.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
         }
         break;
       // Macro element 1 is immediately above the cylinder, outside
       // the inner annular region
       case 1:
         switch (direction)
         {
           case N:
             linear_interpolate(Upper_mid_left, Upper_mid_right, s[0], f);
             break;
           case S:
             xi[0] = 3.0 * atan(1.0) - 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             project_point_on_cylinder_to_annular_boundary(time, xi, f);
             break;
           case W:
             xi[0] = 3.0 * atan(1.0);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_annular_ring, Upper_mid_left, s[0], f);
             break;
           case E:
             xi[0] = 1.0 * atan(1.0);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_annular_ring, Upper_mid_right, s[0], f);
             break;
           default:
             std::ostringstream error_stream;
             error_stream << "Direction is incorrect:  " << direction
                          << std::endl;
             throw OomphLibError(error_stream.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
         }
         break;
       // Macro element 2 is immediately to the right of the cylinder, outside
       // the inner annular region
       case 2:
         switch (direction)
         {
           case N:
             xi[0] = 1.0 * atan(1.0);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_annular_ring, Upper_mid_right, s[0], f);
             break;
           case S:
             xi[0] = -1.0 * atan(1.0);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_annular_ring, Lower_mid_right, s[0], f);
             break;
           case W:
             xi[0] = -atan(1.0) + 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             project_point_on_cylinder_to_annular_boundary(time, xi, f);
             break;
           case E:
             linear_interpolate(Lower_mid_right, Upper_mid_right, s[0], f);
             break;
           default:
             std::ostringstream error_stream;
             error_stream << "Direction is incorrect:  " << direction
                          << std::endl;
             throw OomphLibError(error_stream.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
         }
         break;
       // Macro element 3 is immediately below cylinder, outside
       // the inner annular region
       case 3:
         switch (direction)
         {
           case N:
             xi[0] = -3.0 * atan(1.0) + 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             project_point_on_cylinder_to_annular_boundary(time, xi, f);
             break;
           case S:
             linear_interpolate(Lower_mid_left, Lower_mid_right, s[0], f);
             break;
           case W:
             xi[0] = -3.0 * atan(1.0);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(Lower_mid_left, point_on_annular_ring, s[0], f);
             break;
           case E:
             xi[0] = -1.0 * atan(1.0);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(Lower_mid_right, point_on_annular_ring, s[0], f);
             break;
           default:
             std::ostringstream error_stream;
             error_stream << "Direction is incorrect: " << direction
                          << std::endl;
             throw OomphLibError(error_stream.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
         }
         break;
       // Macro element 4, is immediately to the left of the cylinder
       // lying in the inner annular region
       case 4:
         // Switch on the face of the m-th macro element
         switch (direction)
         {
           case N:
             xi[0] = 3.0 * atan(1.0);
             Cylinder_pt->position(time, xi, point_on_circle);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_annular_ring, point_on_circle, s[0], f);
             break;
           case S:
             xi[0] = -3.0 * atan(1.0);
             Cylinder_pt->position(time, xi, point_on_circle);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_annular_ring, point_on_circle, s[0], f);
             break;
           case W:
             xi[0] = 5.0 * atan(1.0) - 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             project_point_on_cylinder_to_annular_boundary(time, xi, f);
             break;
           case E:
             xi[0] = 5.0 * atan(1.0) - 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             Cylinder_pt->position(time, xi, f);
             break;
           default:
             std::ostringstream error_stream;
             error_stream << "Direction is incorrect: " << direction
                          << std::endl;
             throw OomphLibError(error_stream.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
         }
         break;
       // Macro element 5, is immediately above the cylinder in the
       // inner annular region
       case 5:
         switch (direction)
         {
           case N:
             xi[0] = 3.0 * atan(1.0) - 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             project_point_on_cylinder_to_annular_boundary(time, xi, f);
             break;
           case S:
             xi[0] = 3.0 * atan(1.0) - 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             Cylinder_pt->position(time, xi, f);
             break;
           case W:
             xi[0] = 3.0 * atan(1.0);
             Cylinder_pt->position(time, xi, point_on_circle);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_circle, point_on_annular_ring, s[0], f);
             break;
           case E:
             xi[0] = 1.0 * atan(1.0);
             Cylinder_pt->position(time, xi, point_on_circle);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_circle, point_on_annular_ring, s[0], f);
             break;
           default:
             std::ostringstream error_stream;
             error_stream << "Direction is incorrect: " << direction
                          << std::endl;
             throw OomphLibError(error_stream.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
         }
         break;
       // Macro element 6, is immediately to the right of the cylinder
       // lying in the inner annular region
       case 6:
         switch (direction)
         {
           case N:
             xi[0] = 1.0 * atan(1.0);
             Cylinder_pt->position(time, xi, point_on_circle);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_circle, point_on_annular_ring, s[0], f);
             break;
           case S:
             xi[0] = -1.0 * atan(1.0);
             Cylinder_pt->position(time, xi, point_on_circle);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_circle, point_on_annular_ring, s[0], f);
             break;
           case W:
             xi[0] = -atan(1.0) + 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             Cylinder_pt->position(time, xi, f);
             break;
           case E:
             xi[0] = -atan(1.0) + 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             project_point_on_cylinder_to_annular_boundary(time, xi, f);
             break;
           default:
             std::ostringstream error_stream;
             error_stream << "Direction is incorrect: " << direction
                          << std::endl;
             throw OomphLibError(error_stream.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
         }
         break;
       // Macro element 7, is immediately below the cylinder in the
       // inner annular region
       case 7:
         switch (direction)
         {
           case N:
             xi[0] = -3.0 * atan(1.0) + 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             Cylinder_pt->position(time, xi, f);
             break;
           case S:
             xi[0] = -3.0 * atan(1.0) + 2.0 * atan(1.0) * 0.5 * (1.0 + s[0]);
             project_point_on_cylinder_to_annular_boundary(time, xi, f);
             break;
           case W:
             xi[0] = -3.0 * atan(1.0);
             Cylinder_pt->position(time, xi, point_on_circle);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_annular_ring, point_on_circle, s[0], f);
             break;
           case E:
             xi[0] = -1.0 * atan(1.0);
             Cylinder_pt->position(time, xi, point_on_circle);
             project_point_on_cylinder_to_annular_boundary(
               time, xi, point_on_annular_ring);
             linear_interpolate(point_on_annular_ring, point_on_circle, s[0], f);
             break;
           default:
             std::ostringstream error_stream;
             error_stream << "Direction is incorrect: " << direction
                          << std::endl;
             throw OomphLibError(error_stream.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
         }
         break;
       default:
         std::ostringstream error_stream;
         error_stream << "Wrong macro element number" << m << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
   } // End of macro_element_boundary
References Eigen::bfloat16_impl::atan(), Cylinder_pt, Global_Physical_Variables::E, f(), linear_interpolate(), Lower_mid_left, Lower_mid_right, m, N, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::GeomObject::position(), project_point_on_cylinder_to_annular_boundary(), s, oomph::QuadTreeNames::S, Upper_mid_left, Upper_mid_right, and oomph::QuadTreeNames::W.
project_point_on_cylinder_to_annular_boundary() [1/2]
void oomph::RectangleWithHoleAndAnnularRegionDomain::project_point_on_cylinder_to_annular_boundary (const double & time, const Vector< double > & xi, Vector< double > & r)
Helper function that, given the Lagrangian coordinate, xi, (associated with a point on the cylinder), returns the corresponding point on the outer boundary of the annular region (where the inner boundary is prescribed by the boundary of the cylinder)
   {
     // Lagrangian coordinate corresponds to theta=pi on the circle
     Vector<double> xi_left(1, 4.0 * atan(1.0));
     // Point on circle corresponding to theta=pi
     Vector<double> point_left(2, 0.0);
     // Get the position of the point on the circle
     Cylinder_pt->position(time, xi_left, point_left);
     // Lagrangian coordinate corresponds to theta=0 on the circle
     Vector<double> xi_right(1, 0.0);
     // Point on circle corresponding to theta=0
     Vector<double> point_right(2, 0.0);
     // Get the position of the point on the circle
     Cylinder_pt->position(time, xi_right, point_right);
     // Storage for the coordinates of the centre
     Vector<double> point_centre(2, 0.0);
     // Loop over the coordinates
     for (unsigned i = 0; i < 2; i++)
     {
       // Calculate the i-th coordinate of the central point
       point_centre[i] = 0.5 * (point_left[i] + point_right[i]);
     }
     // Calculate the x-coordinate of the projectd point
     r[0] = point_centre[0] + Annular_region_radius * cos(xi[0]);
     // Calculate the y-coordinate of the projectd point
     r[1] = point_centre[1] + Annular_region_radius * sin(xi[0]);
   } // End of project_point_on_cylinder_to_annular_boundary
References Annular_region_radius, Eigen::bfloat16_impl::atan(), cos(), Cylinder_pt, i, oomph::GeomObject::position(), UniformPSDSelfTest::r, and sin().
project_point_on_cylinder_to_annular_boundary() [2/2]
void oomph::RectangleWithHoleAndAnnularRegionDomain::project_point_on_cylinder_to_annular_boundary (const unsigned & time, const Vector< double > & xi, Vector< double > & r)
Rectangular domain with circular whole.
Helper function that, given the Lagrangian coordinate, xi, (associated with a point on the cylinder), returns the corresponding point on the outer boundary of the annular region (where the inner boundary is prescribed by the boundary of the cylinder)
   {
     // Lagrangian coordinate corresponds to theta=pi on the circle
     Vector<double> xi_left(1, 4.0 * atan(1.0));
     // Point on circle corresponding to theta=pi
     Vector<double> point_left(2, 0.0);
     // Get the position of the point on the circle
     Cylinder_pt->position(time, xi_left, point_left);
     // Lagrangian coordinate corresponds to theta=0 on the circle
     Vector<double> xi_right(1, 0.0);
     // Point on circle corresponding to theta=0
     Vector<double> point_right(2, 0.0);
     // Get the position of the point on the circle
     Cylinder_pt->position(time, xi_right, point_right);
     // Storage for the coordinates of the centre
     Vector<double> point_centre(2, 0.0);
     // Loop over the coordinates
     for (unsigned i = 0; i < 2; i++)
     {
       // Calculate the i-th coordinate of the central point
       point_centre[i] = 0.5 * (point_left[i] + point_right[i]);
     }
     // Calculate the x-coordinate of the projectd point
     r[0] = point_centre[0] + Annular_region_radius * cos(xi[0]);
     // Calculate the y-coordinate of the projectd point
     r[1] = point_centre[1] + Annular_region_radius * sin(xi[0]);
   } // End of project_point_on_cylinder_to_annular_boundary
References Annular_region_radius, Eigen::bfloat16_impl::atan(), cos(), Cylinder_pt, i, oomph::GeomObject::position(), UniformPSDSelfTest::r, and sin().
Referenced by macro_element_boundary(), and oomph::RefineableQuadMeshWithMovingCylinder< MyRefineableQTaylorHoodElement >::RefineableQuadMeshWithMovingCylinder().
Member Data Documentation
Annular_region_radius
double oomph::RectangleWithHoleAndAnnularRegionDomain::Annular_region_radius private
The radius of the outer boundary of the annular region whose inner boundary is described by Cylinder_pt and outer boundary is a circle with radius lying between half the length of the bounding box and the radius cylinder
Referenced by project_point_on_cylinder_to_annular_boundary().
Cylinder_pt
GeomObject* oomph::RectangleWithHoleAndAnnularRegionDomain::Cylinder_pt private
Pointer to geometric object that represents the central cylinder.
Referenced by macro_element_boundary(), project_point_on_cylinder_to_annular_boundary(), and oomph::RefineableQuadMeshWithMovingCylinder< MyRefineableQTaylorHoodElement >::RefineableQuadMeshWithMovingCylinder().
Lower_left
Vector<double> oomph::RectangleWithHoleAndAnnularRegionDomain::Lower_left private
Lower left corner of rectangle.
Referenced by RectangleWithHoleAndAnnularRegionDomain().
Lower_mid_left
Vector<double> oomph::RectangleWithHoleAndAnnularRegionDomain::Lower_mid_left private
Where the "radial" line from circle meets lower boundary on left.
Referenced by macro_element_boundary(), and RectangleWithHoleAndAnnularRegionDomain().
Lower_mid_right
Vector<double> oomph::RectangleWithHoleAndAnnularRegionDomain::Lower_mid_right private
Where the "radial" line from circle meets lower boundary on right.
Referenced by macro_element_boundary(), and RectangleWithHoleAndAnnularRegionDomain().
Lower_right
Vector<double> oomph::RectangleWithHoleAndAnnularRegionDomain::Lower_right private
Lower right corner of rectangle.
Referenced by RectangleWithHoleAndAnnularRegionDomain().
Upper_left
Vector<double> oomph::RectangleWithHoleAndAnnularRegionDomain::Upper_left private
Upper left corner of rectangle.
Referenced by RectangleWithHoleAndAnnularRegionDomain().
Upper_mid_left
Vector<double> oomph::RectangleWithHoleAndAnnularRegionDomain::Upper_mid_left private
Where the "radial" line from circle meets upper boundary on left.
Referenced by macro_element_boundary(), and RectangleWithHoleAndAnnularRegionDomain().
Upper_mid_right
Vector<double> oomph::RectangleWithHoleAndAnnularRegionDomain::Upper_mid_right private
Where the "radial" line from circle meets upper boundary on right.
Referenced by macro_element_boundary(), and RectangleWithHoleAndAnnularRegionDomain().
Upper_right
Vector<double> oomph::RectangleWithHoleAndAnnularRegionDomain::Upper_right private
Upper right corner of rectangle.
Referenced by RectangleWithHoleAndAnnularRegionDomain().
The documentation for this class was generated from the following files:
rectangle_with_moving_cylinder_mesh.template.h
rectangle_with_moving_cylinder_mesh.template.cc