MercuryDPM: oomph::OneDimLagrange Namespace Reference
oomph::OneDimLagrange Namespace Reference
Functions
template<unsigned NNODE_1D>
void shape (const double &s, double *Psi)
template<unsigned NNODE_1D>
void dshape (const double &s, double *DPsi)
template<unsigned NNODE_1D>
void d2shape (const double &s, double *DPsi)
template<>
void shape< 2 > (const double &s, double *Psi)
1D shape functions specialised to linear order (2 Nodes)
template<>
void dshape< 2 > (const double &s, double *DPsi)
Derivatives of 1D shape functions specialised to linear order (2 Nodes)
template<>
void d2shape< 2 > (const double &s, double *DPsi)
template<>
void shape< 3 > (const double &s, double *Psi)
1D shape functions specialised to quadratic order (3 Nodes)
template<>
void dshape< 3 > (const double &s, double *DPsi)
template<>
void d2shape< 3 > (const double &s, double *DPsi)
template<>
void shape< 4 > (const double &s, double *Psi)
1D shape functions specialised to cubic order (4 Nodes)
template<>
void dshape< 4 > (const double &s, double *DPsi)
Derivatives of 1D shape functions specialised to cubic order (4 Nodes)
template<>
void d2shape< 4 > (const double &s, double *DPsi)
Function Documentation
d2shape()
template<unsigned NNODE_1D> void oomph::OneDimLagrange::d2shape (const double & s, double * DPsi)
Definition for second derivatives of 1D Lagrange shape functions. The value of all the shape function derivatives at the local coordinate s are returned in the array DPsi.
     {
       std::ostringstream error_stream;
       error_stream << "One dimensional Lagrange shape function "
                    << "second derivatives "
                    << "have not been defined "
                    << "for " << NNODE_1D << " nodes." << std::endl;
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
d2shape< 2 >()
template<> void oomph::OneDimLagrange::d2shape< 2 > (const double & s, double * DPsi) inline
Second Derivatives of 1D shape functions, specialised to linear order (2 Nodes)
     {
       DPsi[0] = 0.0;
       DPsi[1] = 0.0;
     }
d2shape< 3 >()
template<> void oomph::OneDimLagrange::d2shape< 3 > (const double & s, double * DPsi) inline
Second Derivatives of 1D shape functions, specialised to quadratic order (3 Nodes)
     {
       DPsi[0] = 1.0;
       DPsi[1] = -2.0;
       DPsi[2] = 1.0;
     }
d2shape< 4 >()
template<> void oomph::OneDimLagrange::d2shape< 4 > (const double & s, double * DPsi) inline
Second Derivatives of 1D shape functions specialised to cubic order (4 Nodes)
     {
       // Output from Maple (modified by ALH, CHECK IT)
       double t1 = 2.0 * s;
       double t2 = 0.16875E1 * t1;
       double t5 = 0.50625E1 * t1;
       DPsi[0] = -t2 + 0.1125E1;
       DPsi[1] = t5 - 0.1125E1;
       DPsi[2] = -t5 - 0.1125E1;
       DPsi[3] = t2 + 0.1125E1;
     }
References s.
dshape()
template<unsigned NNODE_1D> void oomph::OneDimLagrange::dshape (const double & s, double * DPsi)
Definition for derivatives of 1D Lagrange shape functions. The value of all the shape function derivatives at the local coordinate s are returned in the array DPsi.
     {
       std::ostringstream error_stream;
       error_stream << "One dimensional Lagrange shape function derivatives "
                    << "have not been defined "
                    << "for " << NNODE_1D << " nodes." << std::endl;
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
dshape< 2 >()
template<> void oomph::OneDimLagrange::dshape< 2 > (const double & s, double * DPsi) inline
Derivatives of 1D shape functions specialised to linear order (2 Nodes)
     {
       DPsi[0] = -0.5;
       DPsi[1] = 0.5;
     }
Referenced by oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::dpshape_and_dptest_eulerian_nst(), oomph::QTaylorHoodElement< DIM >::dpshape_and_dptest_eulerian_nst(), oomph::QTaylorHoodSpaceTimeElement< DIM >::dpshape_and_dptest_eulerian_nst(), oomph::QTaylorHoodSpaceTimeElement< DIM >::dpshape_eulerian(), oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::dpshape_eulerian(), oomph::QTaylorHoodSpaceTimeElement< DIM >::dptest_eulerian(), and oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::dptest_eulerian().
dshape< 3 >()
template<> void oomph::OneDimLagrange::dshape< 3 > (const double & s, double * DPsi) inline
Derivatives of 1D shape functions specialised to quadratic order (3 Nodes)
     {
       DPsi[0] = s - 0.5;
       DPsi[1] = -2.0 * s;
       DPsi[2] = s + 0.5;
     }
References s.
Referenced by oomph::QTaylorHoodSpaceTimeElement< DIM >::dpshape_eulerian(), oomph::QTaylorHoodSpaceTimeElement< DIM >::dptest_eulerian(), oomph::QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_nst(), oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::dshape_local_u_nst(), and oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::dtest_local_u_nst().
dshape< 4 >()
template<> void oomph::OneDimLagrange::dshape< 4 > (const double & s, double * DPsi) inline
Derivatives of 1D shape functions specialised to cubic order (4 Nodes)
     {
       // Output from Maple
       double t1 = s * s;
       double t2 = 0.16875E1 * t1;
       double t3 = 0.1125E1 * s;
       double t5 = 0.50625E1 * t1;
       DPsi[0] = -t2 + t3 + 0.625E-1;
       DPsi[1] = t5 - t3 - 0.16875E1;
       DPsi[2] = -t5 - t3 + 0.16875E1;
       DPsi[3] = t2 + t3 - 0.625E-1;
     }
References s.
shape()
template<unsigned NNODE_1D> void oomph::OneDimLagrange::shape (const double & s, double * Psi)
Definition for 1D Lagrange shape functions. The value of all the shape functions at the local coordinate s are returned in the array Psi.
     {
       std::ostringstream error_stream;
       error_stream << "One dimensional Lagrange shape functions "
                    << "have not been defined "
                    << "for " << NNODE_1D << " nodes." << std::endl;
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by TwoNodeGeometricElement::dshape_local(), oomph::TElementShape< 1, 2 >::dshape_local(), oomph::TElementShape< 1, 3 >::dshape_local(), oomph::TElementShape< 1, 4 >::dshape_local(), oomph::TElementShape< 2, 2 >::dshape_local(), oomph::TElementShape< 2, 3 >::dshape_local(), oomph::TElementShape< 2, 4 >::dshape_local(), oomph::TBubbleEnrichedElementShape< 2, 3 >::dshape_local(), oomph::TElementShape< 3, 2 >::dshape_local(), oomph::TElementShape< 3, 3 >::dshape_local(), oomph::TBubbleEnrichedElementShape< 3, 3 >::dshape_local(), oomph::HelmholtzPointSourceElement< ELEMENT >::fill_in_point_source_contribution_to_residuals(), oomph::PMLHelmholtzPointSourceElement< ELEMENT >::fill_in_point_source_contribution_to_residuals(), oomph::ProjectableLinearHeatAndElasticityElement< LINEAR_HEAT_AND_ELAST_ELEMENT >::get_field(), oomph::ProjectableTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::get_field(), oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::get_field(), SpineGravityTractionElement< ELEMENT >::get_flux(), oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::get_interpolated_mortared_status(), oomph::VorticitySmootherElement< ELEMENT >::get_interpolated_values(), RefineableModalPoissonEquations< DIM >::get_interpolated_values(), VolumeCoupling::getProjectionMatrix(), oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::interpolated_C(), oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::interpolated_C(), ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement< ELEMENT >::interpolated_C_bulk(), SSPorousChannelEquations::interpolated_f(), oomph::NavierStokesElementWithSingularity< BASIC_NAVIER_STOKES_ELEMENT >::interpolated_p_nst(), oomph::DummyBrickElement::interpolated_s_tet(), oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::interpolated_T(), ComplexHarmonicEquations::interpolated_u(), HarmonicEquations::interpolated_u(), OrrSommerfeldEquations< DIM >::interpolated_u(), oomph::interpolated_u_cons_axisym_adv_diff(), oomph::FluxTransportEquations< DIM >::interpolated_u_flux_transport(), oomph::NavierStokesElementWithSingularity< BASIC_NAVIER_STOKES_ELEMENT >::interpolated_u_nst(), oomph::NavierStokesElementWithSingularity< BASIC_NAVIER_STOKES_ELEMENT >::interpolated_u_nst_fe_only(), PoissonElementWithSingularity< BASIC_POISSON_ELEMENT >::interpolated_u_poisson(), PoissonElementWithSingularity< BASIC_POISSON_ELEMENT >::interpolated_u_poisson_fe_only(), ComplexHarmonicEquations::interpolated_w(), oomph::RefineableQElement< 2 >::interpolated_zeta_on_edge(), oomph::RefineableQElement< 3 >::interpolated_zeta_on_face(), DistanceWrapper< ELEMENT >::output(), oomph::QSpectralElement< 1, NNODE_1D >::output(), oomph::VolumeCoupledElement< ELEMENT >::output(), oomph::VorticitySmootherElement< ELEMENT >::output(), oomph::PoroelasticityEquations< DIM >::output(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::output_veloc(), oomph::NavierStokesEquations< DIM >::output_veloc(), oomph::HeatedPenetratorFluxElement< ELEMENT >::penetrator_temperature(), oomph::TElement< 1, NNODE_1D >::shape(), oomph::TElement< 2, NNODE_1D >::shape(), oomph::TElement< 3, NNODE_1D >::shape(), oomph::TBubbleEnrichedElement< DIM, 3 >::shape(), oomph::ClampedHermiteShellBoundaryConditionElement::shape(), oomph::HeatedPenetratorFluxElement< ELEMENT >::shape_and_test(), oomph::SurfaceContactElementBase< ELEMENT >::shape_p(), oomph::SpineLineMarangoniFluidInterfaceElement< ELEMENT >::sigma(), oomph::FixedVolumeSpineLineMarangoniFluidInterfaceElement< ELEMENT >::sigma(), oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::sigma(), oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::sigma(), and oomph::VorticitySmootherElement< ELEMENT >::vorticity_and_its_derivs().
shape< 2 >()
template<> void oomph::OneDimLagrange::shape< 2 > (const double & s, double * Psi) inline
1D shape functions specialised to linear order (2 Nodes)
     {
       Psi[0] = 0.5 * (1.0 - s);
       Psi[1] = 0.5 * (1.0 + s);
     }
References s.
Referenced by oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::dpshape_and_dptest_eulerian_nst(), oomph::QTaylorHoodElement< DIM >::dpshape_and_dptest_eulerian_nst(), oomph::QTaylorHoodSpaceTimeElement< DIM >::dpshape_and_dptest_eulerian_nst(), oomph::QTaylorHoodSpaceTimeElement< DIM >::dpshape_eulerian(), oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::dpshape_eulerian(), oomph::QTaylorHoodSpaceTimeElement< DIM >::dptest_eulerian(), oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::dptest_eulerian(), oomph::AxisymmetricQTaylorHoodElement::pshape_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement::pshape_axi_nst(), oomph::LinearisedAxisymmetricQTaylorHoodElement::pshape_lin_axi_nst(), oomph::LinearisedAxisymmetricQTaylorHoodElement::pshape_linearised_axi_nst(), oomph::LinearisedQTaylorHoodElement::pshape_linearised_nst(), oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::pshape_nst(), oomph::QTaylorHoodElement< DIM >::pshape_nst(), oomph::QTaylorHoodSpaceTimeElement< DIM >::pshape_nst(), oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::pshape_nst(), oomph::PolarTaylorHoodElement::pshape_pnst(), oomph::QSphericalTaylorHoodElement::pshape_spherical_nst(), oomph::QTaylorHoodSpaceTimeElement< DIM >::ptest_nst(), oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::ptest_nst(), and oomph::QPVDElementWithContinuousPressure< DIM >::solid_pshape().
shape< 3 >()
template<> void oomph::OneDimLagrange::shape< 3 > (const double & s, double * Psi) inline
1D shape functions specialised to quadratic order (3 Nodes)
     {
       Psi[0] = 0.5 * s * (s - 1.0);
       Psi[1] = 1.0 - s * s;
       Psi[2] = 0.5 * s * (s + 1.0);
     }
References s.
Referenced by oomph::QTaylorHoodSpaceTimeElement< DIM >::dpshape_eulerian(), oomph::QTaylorHoodSpaceTimeElement< DIM >::dptest_eulerian(), oomph::QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_nst(), oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::dshape_local_u_nst(), oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::dtest_local_u_nst(), oomph::QTaylorHoodSpaceTimeElement< DIM >::pshape_nst(), oomph::QTaylorHoodSpaceTimeElement< DIM >::ptest_nst(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::shape_and_test_at_knot(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::shape_and_test_at_knot(), and oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::shape_u_nst().
shape< 4 >()
template<> void oomph::OneDimLagrange::shape< 4 > (const double & s, double * Psi) inline
1D shape functions specialised to cubic order (4 Nodes)
     {
       // Output from Maple
       double t1 = s * s;
       double t2 = t1 * s;
       double t3 = 0.5625 * t2;
       double t4 = 0.5625 * t1;
       double t5 = 0.625E-1 * s;
       double t7 = 0.16875E1 * t2;
       double t8 = 0.16875E1 * s;
       Psi[0] = -t3 + t4 + t5 - 0.625E-1;
       Psi[1] = t7 - t4 - t8 + 0.5625;
       Psi[2] = -t7 - t4 + t8 + 0.5625;
       Psi[3] = t3 + t4 - t5 - 0.625E-1;
     }
References s.