MercuryDPM: Tutorial_AdvancedInitialization_ThreeWays.cpp File Reference
Tutorial_AdvancedInitialization_ThreeWays.cpp File Reference
Functions
MatrixXd mat1 (size, size)
mat1 topLeftCorner (size/2, size/2)
mat1 topRightCorner (size/2, size/2)
mat1 bottomLeftCorner (size/2, size/2)
mat1 bottomRightCorner (size/2, size/2)
Variables
const int size = 6
Function Documentation
bottomLeftCorner()
mat1 bottomLeftCorner (size/ 2, size/ 2)
Referenced by corners().
bottomRightCorner()
mat1 bottomRightCorner (size/ 2, size/ 2)
Referenced by corners().
mat1()
MatrixXd mat1 (size , size)
Referenced by Eigen::IncompleteLUT< Scalar_, StorageIndex_ >::analyzePattern(), EIGEN_DECLARE_TEST(), Eigen::internal::is_same_dense(), oomph::OcTree::mult_mat_mat(), product_large_regressions(), ref_vector(), oomph::OcTree::rotate(), test_2d(), test_3d(), test_array(), test_assign(), test_compound_assignment(), test_consistency(), test_const_inputs(), test_constants(), test_equality(), test_evals(), test_expr(), test_from_tensor(), test_functors(), test_multidims(), test_orderings(), test_out_of_order_contraction(), test_plus(), test_plus_equal(), test_select(), test_simple(), test_tensor_product(), and test_type_casting().
topLeftCorner()
mat1 topLeftCorner (size/ 2, size/ 2)
topRightCorner()
mat1 topRightCorner (size/ 2, size/ 2)
Referenced by corners().
Variable Documentation
size
const int size = 6