MercuryDPM: conjugate_gradient.cpp File Reference
conjugate_gradient.cpp File Reference
#include "sparse_solver.h"
#include <Eigen/IterativeLinearSolvers>
Functions
template<typename T , typename I_ >
void test_conjugate_gradient_T ()
EIGEN_DECLARE_TEST (conjugate_gradient)
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (conjugate_gradient)
{
   CALL_SUBTEST_1((test_conjugate_gradient_T<double, int>()));
   CALL_SUBTEST_2((test_conjugate_gradient_T<std::complex<double>, int>()));
   CALL_SUBTEST_3((test_conjugate_gradient_T<double, long int>()));
 }
References CALL_SUBTEST_1, CALL_SUBTEST_2, CALL_SUBTEST_3, and test_conjugate_gradient_T().
test_conjugate_gradient_T()
template<typename T , typename I_ > void test_conjugate_gradient_T ()
{
   typedef SparseMatrix<T, 0, I_> SparseMatrixType;
   ConjugateGradient<SparseMatrixType, Lower> cg_colmajor_lower_diag;
   ConjugateGradient<SparseMatrixType, Upper> cg_colmajor_upper_diag;
   ConjugateGradient<SparseMatrixType, Lower | Upper> cg_colmajor_loup_diag;
   ConjugateGradient<SparseMatrixType, Lower, IdentityPreconditioner> cg_colmajor_lower_I;
   ConjugateGradient<SparseMatrixType, Upper, IdentityPreconditioner> cg_colmajor_upper_I;
   CALL_SUBTEST(check_sparse_spd_solving(cg_colmajor_lower_diag));
   CALL_SUBTEST(check_sparse_spd_solving(cg_colmajor_upper_diag));
   CALL_SUBTEST(check_sparse_spd_solving(cg_colmajor_loup_diag));
   CALL_SUBTEST(check_sparse_spd_solving(cg_colmajor_lower_I));
   CALL_SUBTEST(check_sparse_spd_solving(cg_colmajor_upper_I));
 }
References CALL_SUBTEST, and check_sparse_spd_solving().
Referenced by EIGEN_DECLARE_TEST().