MercuryDPM: Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, UpLo, Version > Struct Template Reference
Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, UpLo, Version > Struct Template Reference
#include <GeneralMatrixMatrixTriangular.h>
Public Types
typedef ScalarBinaryOpTraits< LhsScalar, RhsScalar >::ReturnType ResScalar
Static Public Member Functions
static EIGEN_STRONG_INLINE void run (Index size, Index depth, const LhsScalar *lhs_, Index lhsStride, const RhsScalar *rhs_, Index rhsStride, ResScalar *res_, Index resIncr, Index resStride, const ResScalar &alpha, level3_blocking< LhsScalar, RhsScalar > &blocking)
Member Typedef Documentation
ResScalar
template<typename Index , typename LhsScalar , int LhsStorageOrder, bool ConjugateLhs, typename RhsScalar , int RhsStorageOrder, bool ConjugateRhs, int ResInnerStride, int UpLo, int Version> typedef ScalarBinaryOpTraits<LhsScalar, RhsScalar>::ReturnType Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, UpLo, Version >::ResScalar
Member Function Documentation
run()
template<typename Index , typename LhsScalar , int LhsStorageOrder, bool ConjugateLhs, typename RhsScalar , int RhsStorageOrder, bool ConjugateRhs, int ResInnerStride, int UpLo, int Version> static EIGEN_STRONG_INLINE void Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, UpLo, Version >::run (Index size, Index depth, const LhsScalar * lhs_, Index lhsStride, const RhsScalar * rhs_, Index rhsStride, ResScalar * res_, Index resIncr, Index resStride, const ResScalar & alpha, level3_blocking< LhsScalar, RhsScalar > & blocking) inline static
{
     if (size == 0) {
       return;
     }
     typedef gebp_traits<LhsScalar, RhsScalar> Traits;
     typedef const_blas_data_mapper<LhsScalar, Index, LhsStorageOrder> LhsMapper;
     typedef const_blas_data_mapper<RhsScalar, Index, RhsStorageOrder> RhsMapper;
     typedef blas_data_mapper<typename Traits::ResScalar, Index, ColMajor, Unaligned, ResInnerStride> ResMapper;
     LhsMapper lhs(lhs_, lhsStride);
     RhsMapper rhs(rhs_, rhsStride);
     ResMapper res(res_, resStride, resIncr);
     Index kc = blocking.kc();
     // Ensure that mc >= nr and <= size
     Index mc = (std::min)(size, (std::max)(static_cast<decltype(blocking.mc())>(Traits::nr), blocking.mc()));
     // !!! mc must be a multiple of nr
     if (mc > Traits::nr) {
       using UnsignedIndex = typename make_unsigned<Index>::type;
       mc = (UnsignedIndex(mc) / Traits::nr) * Traits::nr;
     }
     std::size_t sizeA = kc * mc;
     std::size_t sizeB = kc * size;
     ei_declare_aligned_stack_constructed_variable(LhsScalar, blockA, sizeA, blocking.blockA());
     ei_declare_aligned_stack_constructed_variable(RhsScalar, blockB, sizeB, blocking.blockB());
     gemm_pack_lhs<LhsScalar, Index, LhsMapper, Traits::mr, Traits::LhsProgress, typename Traits::LhsPacket4Packing,
                   LhsStorageOrder>
         pack_lhs;
     gemm_pack_rhs<RhsScalar, Index, RhsMapper, Traits::nr, RhsStorageOrder> pack_rhs;
     gebp_kernel<LhsScalar, RhsScalar, Index, ResMapper, Traits::mr, Traits::nr, ConjugateLhs, ConjugateRhs> gebp;
     tribb_kernel<LhsScalar, RhsScalar, Index, Traits::mr, Traits::nr, ConjugateLhs, ConjugateRhs, ResInnerStride, UpLo>
         sybb;
     for (Index k2 = 0; k2 < depth; k2 += kc) {
       const Index actual_kc = (std::min)(k2 + kc, depth) - k2;
       // note that the actual rhs is the transpose/adjoint of mat
       pack_rhs(blockB, rhs.getSubMapper(k2, 0), actual_kc, size);
       for (Index i2 = 0; i2 < size; i2 += mc) {
         const Index actual_mc = (std::min)(i2 + mc, size) - i2;
         pack_lhs(blockA, lhs.getSubMapper(i2, k2), actual_kc, actual_mc);
         // the selected actual_mc * size panel of res is split into three different part:
         //  1 - before the diagonal => processed with gebp or skipped
         //  2 - the actual_mc x actual_mc symmetric block => processed with a special kernel
         //  3 - after the diagonal => processed with gebp or skipped
         if (UpLo == Lower)
           gebp(res.getSubMapper(i2, 0), blockA, blockB, actual_mc, actual_kc, (std::min)(size, i2), alpha, -1, -1, 0,
                0);
         sybb(res_ + resStride * i2 + resIncr * i2, resIncr, resStride, blockA, blockB + actual_kc * i2, actual_mc,
              actual_kc, alpha);
         if (UpLo == Upper) {
           Index j2 = i2 + actual_mc;
           gebp(res.getSubMapper(i2, j2), blockA, blockB + actual_kc * j2, actual_mc, actual_kc,
                (std::max)(Index(0), size - j2), alpha, -1, -1, 0, 0);
         }
       }
     }
   }
References alpha, Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::blockA(), Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::blockB(), ei_declare_aligned_stack_constructed_variable, Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::kc(), Eigen::Lower, max, Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::mc(), min, res, size, compute_granudrum_aor::type, and Eigen::Upper.
The documentation for this struct was generated from the following file:
GeneralMatrixMatrixTriangular.h