MercuryDPM: oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM > Class Template Reference
oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM > Class Template Reference
#include <generalised_newtonian_constitutive_models.h>
Public Member Functions
SiskoTanMilRegWithBlendingConstitutiveEquation (double *alpha_pt, double *flow_index_pt, double *critical_second_invariant_pt)
"Cutoff regularised" Sisko constitutive equation
double calculate_cutoff_viscosity ()
double calculate_viscosity_offset_at_zero_shear (double &cut_off_viscosity)
double calculate_zero_shear_viscosity ()
Function that calculates the viscosity at zero I2.
void report_cut_off_values (double &cut_off_invariant, double &cut_off_viscosity, double &zero_shear_viscosity)
Report cutoff values.
void calculate_fitting_parameters_of_cubic (double &a, double &b)
double viscosity (const double &second_invariant_of_rate_of_strain_tensor)
Viscosity ratio as a fct of strain rate invariant.
double dviscosity_dinvariant (const double &second_invariant_of_rate_of_strain_tensor)
Deriv of viscosity w.r.t. strain rate invariant.
Public Member Functions inherited from oomph::GeneralisedNewtonianConstitutiveEquation< DIM >
GeneralisedNewtonianConstitutiveEquation ()
Empty constructor.
virtual ~GeneralisedNewtonianConstitutiveEquation ()
Empty virtual destructor.
Private Attributes
double * Alpha_pt
pre-factor alpha
double * Flow_index_pt
power law index n
double * Critical_second_invariant_pt
Detailed Description
template<unsigned DIM>
class oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >
A GeneralisedNewtonianConstitutiveEquation class defining a Sisko fluid using Tanner and Milthorpe's (1983) regularisation with a smooth transition using a cubic (for n < 1)
Constructor & Destructor Documentation
SiskoTanMilRegWithBlendingConstitutiveEquation()
template<unsigned DIM> oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::SiskoTanMilRegWithBlendingConstitutiveEquation (double * alpha_pt, double * flow_index_pt, double * critical_second_invariant_pt) inline
"Cutoff regularised" Sisko constitutive equation
get the cutoff viscosity
get the zero shear viscosity
       : GeneralisedNewtonianConstitutiveEquation<DIM>(),
         Alpha_pt(alpha_pt),
         Flow_index_pt(flow_index_pt),
         Critical_second_invariant_pt(critical_second_invariant_pt)
     {
       double cut_off_viscosity = calculate_cutoff_viscosity();
       double zero_shear_viscosity = calculate_zero_shear_viscosity();
       oomph_info << "SiskoTanMilRegWithBlendingConstitutiveEquation: "
                  << " zero shear viscosity = " << zero_shear_viscosity
                  << std::endl;
       oomph_info << "SiskoTanMilRegWithBlendingConstitutiveEquation: "
                  << " cut off viscosity = " << cut_off_viscosity << std::endl;
       oomph_info << "                                              "
                  << " cutoff invariant = " << *Critical_second_invariant_pt
                  << std::endl;
     }
References oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_cutoff_viscosity(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_zero_shear_viscosity(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::Critical_second_invariant_pt, and oomph::oomph_info.
Member Function Documentation
calculate_cutoff_viscosity()
template<unsigned DIM> double oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_cutoff_viscosity () inline
Function that calculates the viscosity at the cutoff invariant Note: this is NOT the viscosity at zero I2
     {
       // Calculate the Newtonian cutoff viscosity from the constitutive
       // equation and the cutoff value of the second invariant
       return 1.0 +
              (*Alpha_pt) * pow((2.0 * sqrt((*Critical_second_invariant_pt))),
                                *Flow_index_pt - 1.0);
     }
References oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::Critical_second_invariant_pt, oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::Flow_index_pt, Eigen::bfloat16_impl::pow(), and sqrt().
Referenced by oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_fitting_parameters_of_cubic(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_zero_shear_viscosity(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::report_cut_off_values(), and oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::SiskoTanMilRegWithBlendingConstitutiveEquation().
calculate_fitting_parameters_of_cubic()
template<unsigned DIM> void oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_fitting_parameters_of_cubic (double & a, double & b) inline
     {
       // get the viscosity at the cutoff invariant
       double Cut_off_viscosity = calculate_cutoff_viscosity();
       // calculate the offset at zero shear
       double epsilon =
         calculate_viscosity_offset_at_zero_shear(Cut_off_viscosity);
       a =
         1.0 /
         (4.0 * pow((*Critical_second_invariant_pt), 3.0) *
          pow((*Critical_second_invariant_pt), 5.0 / 2.0)) *
         (8.0 * (Cut_off_viscosity + epsilon - 1.0) *
            pow((*Critical_second_invariant_pt), 5.0 / 2.0) +
          pow(2.0, (*Flow_index_pt)) * ((*Flow_index_pt) - 1.0) * (*Alpha_pt) *
            pow((*Critical_second_invariant_pt), 2.0) *
            pow((*Critical_second_invariant_pt), (*Flow_index_pt) / 2.0) -
          pow(2.0, (*Flow_index_pt) + 2.0) * (*Alpha_pt) *
            pow((*Critical_second_invariant_pt), (*Flow_index_pt) / 2.0 + 2.0));
       b =
         1.0 /
         (4.0 * pow((*Critical_second_invariant_pt), 2.0) *
          pow((*Critical_second_invariant_pt), 5.0 / 2.0)) *
         (-12.0 * (Cut_off_viscosity + epsilon - 1.0) *
            pow((*Critical_second_invariant_pt), 5.0 / 2.0) -
          pow(2.0, (*Flow_index_pt)) * ((*Flow_index_pt) - 1.0) * (*Alpha_pt) *
            pow((*Critical_second_invariant_pt), 2.0) *
            pow((*Critical_second_invariant_pt), (*Flow_index_pt) / 2.0) +
          3.0 * pow(2.0, (*Flow_index_pt) + 1.0) * (*Alpha_pt) *
            pow((*Critical_second_invariant_pt), (*Flow_index_pt) / 2.0 + 2.0));
     }
References a, oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::Alpha_pt, b, oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_cutoff_viscosity(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_viscosity_offset_at_zero_shear(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::Critical_second_invariant_pt, oomph::SarahBL::epsilon, oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::Flow_index_pt, and Eigen::bfloat16_impl::pow().
Referenced by oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant(), and oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity().
calculate_viscosity_offset_at_zero_shear()
template<unsigned DIM> double oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_viscosity_offset_at_zero_shear (double & cut_off_viscosity) inline
Offset by how much the zero shear rate viscosity lies above the viscosity at I2_cutoff Hard-coded to a value that ensures a smooth transition
     {
       return cut_off_viscosity / 5.0;
     }
Referenced by oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_fitting_parameters_of_cubic(), and oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_zero_shear_viscosity().
calculate_zero_shear_viscosity()
template<unsigned DIM> double oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_zero_shear_viscosity () inline
Function that calculates the viscosity at zero I2.
Offset by how much the zero shear rate viscosity lies above the viscosity at I2_cutoff
     {
       // get the viscosity at the cutoff point
       double cut_off_viscosity = calculate_cutoff_viscosity();
       double epsilon =
         calculate_viscosity_offset_at_zero_shear(cut_off_viscosity);
       return cut_off_viscosity + epsilon;
     }
References oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_cutoff_viscosity(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_viscosity_offset_at_zero_shear(), and oomph::SarahBL::epsilon.
Referenced by oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::report_cut_off_values(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::SiskoTanMilRegWithBlendingConstitutiveEquation(), and oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity().
dviscosity_dinvariant()
template<unsigned DIM> double oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant (const double & second_invariant_of_rate_of_strain_tensor) inline virtual
Deriv of viscosity w.r.t. strain rate invariant.
Implements oomph::GeneralisedNewtonianConstitutiveEquation< DIM >.
     {
       // Get the parameters of the cubic
       double a;
       double b;
       calculate_fitting_parameters_of_cubic(a, b);
       // Pre-multiply the second invariant with +/-1 depending on whether it's
       // positive or not
       double sign = -1.0;
       if (second_invariant_of_rate_of_strain_tensor >= 0.0)
       {
         sign = 1.0;
       }
       if (sign * second_invariant_of_rate_of_strain_tensor <
           (*Critical_second_invariant_pt))
       {
         return sign * 3.0 * a *
                  pow(sign * second_invariant_of_rate_of_strain_tensor, 2.0) +
                2.0 * b * second_invariant_of_rate_of_strain_tensor;
       }
       else
       {
         return (*Alpha_pt) * pow(2.0, (*Flow_index_pt) - 2.0) *
                ((*Flow_index_pt) - 1.0) *
                second_invariant_of_rate_of_strain_tensor *
                pow(sign * second_invariant_of_rate_of_strain_tensor,
                    ((*Flow_index_pt) - 1.0) / 2.0 - 2.0);
       }
     }
References a, oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::Alpha_pt, b, oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_fitting_parameters_of_cubic(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::Critical_second_invariant_pt, oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::Flow_index_pt, Eigen::bfloat16_impl::pow(), and SYCL::sign().
report_cut_off_values()
template<unsigned DIM> void oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::report_cut_off_values (double & cut_off_invariant, double & cut_off_viscosity, double & zero_shear_viscosity) inline
Report cutoff values.
     {
       cut_off_invariant = *Critical_second_invariant_pt;
       cut_off_viscosity = calculate_cutoff_viscosity();
       zero_shear_viscosity = calculate_zero_shear_viscosity();
     }
References oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_cutoff_viscosity(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_zero_shear_viscosity(), and oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::Critical_second_invariant_pt.
viscosity()
template<unsigned DIM> double oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity (const double & second_invariant_of_rate_of_strain_tensor) inline virtual
Viscosity ratio as a fct of strain rate invariant.
Implements oomph::GeneralisedNewtonianConstitutiveEquation< DIM >.
     {
       // Get the parameters of the cubic
       double a;
       double b;
       calculate_fitting_parameters_of_cubic(a, b);
       double zero_shear_viscosity = calculate_zero_shear_viscosity();
       // Pre-multiply the second invariant with +/-1 depending on whether it's
       // positive or not
       double sign = -1.0;
       if (second_invariant_of_rate_of_strain_tensor >= 0.0)
       {
         sign = 1.0;
       }
       // if the second invariant is below the cutoff we have a constant,
       // Newtonian viscosity
       if (sign * second_invariant_of_rate_of_strain_tensor <
           (*Critical_second_invariant_pt))
       {
         return a * pow(sign * second_invariant_of_rate_of_strain_tensor, 3.0) +
                b * pow(sign * second_invariant_of_rate_of_strain_tensor, 2.0) +
                zero_shear_viscosity;
       }
       else
       {
         // Calculate the square root of the absolute value of the
         // second invariant of the rate of strain tensor
         double measure_of_rate_of_strain =
           sqrt(sign * second_invariant_of_rate_of_strain_tensor);
         return 1.0 + (*Alpha_pt) * pow((2.0 * measure_of_rate_of_strain),
                                        *Flow_index_pt - 1.0);
       }
     }
References a, b, oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_fitting_parameters_of_cubic(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_zero_shear_viscosity(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::Critical_second_invariant_pt, oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::Flow_index_pt, Eigen::bfloat16_impl::pow(), SYCL::sign(), and sqrt().
Member Data Documentation
Alpha_pt
template<unsigned DIM> double* oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::Alpha_pt private
pre-factor alpha
Referenced by oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_fitting_parameters_of_cubic(), and oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant().
Critical_second_invariant_pt
template<unsigned DIM> double* oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::Critical_second_invariant_pt private
value of the second invariant below which we have constant (Newtonian) viscosity – assumed to be always positive
Referenced by oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_cutoff_viscosity(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_fitting_parameters_of_cubic(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::report_cut_off_values(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::SiskoTanMilRegWithBlendingConstitutiveEquation(), and oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity().
Flow_index_pt
template<unsigned DIM> double* oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::Flow_index_pt private
power law index n
Referenced by oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_cutoff_viscosity(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_fitting_parameters_of_cubic(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant(), and oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity().
The documentation for this class was generated from the following file:
generalised_newtonian_constitutive_models.h