MercuryDPM: refineable_two_layer_interface.cc File Reference
refineable_two_layer_interface.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "solid.h"
#include "constitutive.h"
#include "fluid_interface.h"
#include "meshes/triangle_mesh.h"
Classes
class oomph::MyCrouzeixRaviartElement
Overload CrouzeixRaviart element to modify output.
class oomph::FaceGeometry< MyCrouzeixRaviartElement >
class oomph::FaceGeometry< FaceGeometry< MyCrouzeixRaviartElement > >
class TwoLayerInterfaceProblem< ELEMENT >
Problem class to simulate viscous drop propagating along 2D channel.
Namespaces
oomph
DRAIG: Change all instances of (SPATIAL_DIM) to (DIM-1).
Problem_Parameter
Namespace for Problem Parameter.
Functions
int main (int argc, char **argv)
Driver code for moving block problem.
Variables
DocInfo Problem_Parameter::Doc_info
Doc info.
double Problem_Parameter::ReSt = 5.0
Womersley number (Reynolds x Strouhal)
double Problem_Parameter::ReInvFr = 5.0
Product of Reynolds number and inverse of Froude number.
double Problem_Parameter::Viscosity_Ratio = 0.1
double Problem_Parameter::Density_Ratio = 0.5
double Problem_Parameter::Ca = 0.01
Capillary number.
Vector< double > Problem_Parameter::G (2)
Direction of gravity.
double Problem_Parameter::Length = 1.0
Length of the channel.
double Problem_Parameter::Height = 2.0
double Problem_Parameter::Interface_Height = 0.5
ofstream Problem_Parameter::Trace_file
Trace file.
ofstream Problem_Parameter::Norm_file
Function Documentation
main()
int main (int argc , char ** argv)
Driver code for moving block problem.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Validation?
  CommandLineArgs::specify_command_line_flag("--validation");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Create generalised Hookean constitutive equations
  Problem_Parameter::Constitutive_law_pt =
   new GeneralisedHookean(&Problem_Parameter::Nu);
  Problem_Parameter::G[0] = 0.0;
  Problem_Parameter::G[1] = -1.0;
  // Create problem in initial configuration
  TwoLayerInterfaceProblem<Hijacked<ProjectableCrouzeixRaviartElement<
  MyCrouzeixRaviartElement> > > problem;
  // Set value of epsilon
  const double epsilon = 0.1;
  // Set number of periods for cosine term
  const unsigned n_periods = 1;
  const double dt = 0.0025;
  double t_max = 0.6;
  // Deform the mesh/free surface
  problem.deform_interface(epsilon,n_periods);
  // Open trace file
  char filename[100];
  sprintf(filename,"%s/trace.dat",Problem_Parameter::Doc_info.directory().c_str());
  Problem_Parameter::Trace_file.open(filename);
  // Initialise trace file
  Problem_Parameter::Trace_file << "time, interface height" << std::endl;
  // Initialise timestep
  problem.initialise_dt(dt);
  // Set initial condition
  problem.set_initial_condition();
  // Maximum number of spatial adaptations per timestep
  unsigned max_adapt = 2;
  // Doc initial solution
  problem.doc_solution();
  // Determine number of timesteps
  const unsigned n_timestep = unsigned(t_max/dt);
  // Are we on the first timestep? At this point, yes!
  bool first_timestep = true;
  // Timestepping loop
  for(unsigned t=1;t<=n_timestep;t++)
   {
    // Output current timestep to screen
    cout << "\nTimestep " << t << " of " << n_timestep << std::endl;
    // Take one fixed timestep with spatial adaptivity
    problem.unsteady_newton_solve(dt,max_adapt,first_timestep);
    // No longer on first timestep, so set first_timestep flag to false
    first_timestep = false;
    // Reset maximum number of adaptations for all future timesteps
    max_adapt = 1;
    // Doc solution
    problem.doc_solution();
   } // End of timestepping loop
 } //End of main
References Problem_Parameter::Constitutive_law_pt, Problem_Parameter::Doc_info, oomph::CommandLineArgs::doc_specified_flags(), oomph::SarahBL::epsilon, MergeRestartFiles::filename, Problem_Parameter::G, Problem_Parameter::Nu, oomph::CommandLineArgs::parse_and_assign(), problem, Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), plotPSD::t, and Problem_Parameter::Trace_file.