MercuryDPM: rapidjson::FileStream Class Reference
rapidjson::FileStream Class Reference
Wrapper of C file stream for input or output.
#include <filestream.h>
Public Types
typedef char Ch
Character type. Only support char.
Public Member Functions
FileStream (FILE *fp)
char Peek () const
char Take ()
size_t Tell () const
void Put (char c)
char * PutBegin ()
size_t PutEnd (char *)
Private Member Functions
void Read ()
Private Attributes
FILE * fp_
char current_
size_t count_
Detailed Description
Wrapper of C file stream for input or output.
This simple wrapper does not check the validity of the stream.
Member Typedef Documentation
Ch
typedef char rapidjson::FileStream::Ch
Character type. Only support char.
Constructor & Destructor Documentation
FileStream()
rapidjson::FileStream::FileStream (FILE * fp) inline
 : fp_(fp), count_(0) { Read(); }
References Read().
Member Function Documentation
Peek()
char rapidjson::FileStream::Peek () const inline
 { return current_; }
References current_.
Put()
void rapidjson::FileStream::Put (char c) inline
 { fputc(c, fp_); }
References calibrate::c, and fp_.
PutBegin()
char* rapidjson::FileStream::PutBegin () inline
 { return 0; }
PutEnd()
size_t rapidjson::FileStream::PutEnd (char *) inline
 { return 0; }
Read()
void rapidjson::FileStream::Read () inline private
                 {
         RAPIDJSON_ASSERT(fp_ != 0);
         int c = fgetc(fp_);
         if (c != EOF) {
             current_ = (char)c;
             count_++;
         }
         else
             current_ = '\0';
     }
References calibrate::c, count_, current_, fp_, and RAPIDJSON_ASSERT.
Referenced by FileStream(), and Take().
Take()
char rapidjson::FileStream::Take () inline
 { char c = current_; Read(); return c; }
References calibrate::c, current_, and Read().
Tell()
size_t rapidjson::FileStream::Tell () const inline
 { return count_; }
References count_.
Member Data Documentation
count_
size_t rapidjson::FileStream::count_ private
Referenced by Read(), and Tell().
current_
char rapidjson::FileStream::current_ private
Referenced by Peek(), Read(), and Take().
fp_
FILE* rapidjson::FileStream::fp_ private
Referenced by Put(), and Read().
The documentation for this class was generated from the following file:
filestream.h