MercuryDPM: Eigen::MaxSizeVector< T > Class Template Reference
Eigen::MaxSizeVector< T > Class Template Reference
The MaxSizeVector class.
#include <MaxSizeVector.h>
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE MaxSizeVector (size_t n)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE MaxSizeVector (size_t n, const T &init)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ~MaxSizeVector ()
void resize (size_t n)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void push_back (const T &t)
template<class X >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void emplace_back (const X &x)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T & operator[] (size_t i) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T & operator[] (size_t i)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T & back ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T & back () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void pop_back ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE size_t size () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool empty () const
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE T * data ()
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE const T * data () const
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE T * begin ()
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE T * end ()
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE const T * begin () const
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE const T * end () const
Private Attributes
size_t reserve_
size_t size_
T * data_
Static Private Attributes
static const size_t alignment = internal::plain_enum_max(EIGEN_ALIGNOF(T), sizeof(void*))
Detailed Description
template<typename T>
class Eigen::MaxSizeVector< T >
The MaxSizeVector class.
The MaxSizeVector provides a subset of std::vector functionality.
The goal is to provide basic std::vector operations when using std::vector is not an option (e.g. on GPU or when compiling using FMA/AVX, as this can cause either compilation failures or illegal instruction failures).
Beware: The constructors are not API compatible with these of std::vector.
Constructor & Destructor Documentation
MaxSizeVector() [1/2]
template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::MaxSizeVector< T >::MaxSizeVector (size_t n) inline explicit
       : reserve_(n), size_(0), data_(static_cast<T*>(internal::handmade_aligned_malloc(n * sizeof(T), alignment))) {}
MaxSizeVector() [2/2]
template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::MaxSizeVector< T >::MaxSizeVector (size_t n, const T & init) inline
       : reserve_(n), size_(n), data_(static_cast<T*>(internal::handmade_aligned_malloc(n * sizeof(T), alignment))) {
     size_t i = 0;
     EIGEN_TRY {
       for (; i < size_; ++i) {
         new (&data_[i]) T(init);
       }
     }
     EIGEN_CATCH(...) {
       // Construction failed, destruct in reverse order:
       for (; (i + 1) > 0; --i) {
         data_[i - 1].~T();
       }
       internal::handmade_aligned_free(data_);
       EIGEN_THROW;
     }
   }
References Eigen::MaxSizeVector< T >::data_, EIGEN_CATCH, EIGEN_THROW, EIGEN_TRY, Eigen::internal::handmade_aligned_free(), i, and Eigen::MaxSizeVector< T >::size_.
~MaxSizeVector()
template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::MaxSizeVector< T >::~MaxSizeVector () inline
{
     for (size_t i = size_; i > 0; --i) {
       data_[i - 1].~T();
     }
     internal::handmade_aligned_free(data_);
   }
References Eigen::MaxSizeVector< T >::data_, Eigen::internal::handmade_aligned_free(), i, and Eigen::MaxSizeVector< T >::size_.
Member Function Documentation
back() [1/2]
template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T& Eigen::MaxSizeVector< T >::back () inline
{
     eigen_assert(size_ > 0);
     return data_[size_ - 1];
   }
References Eigen::MaxSizeVector< T >::data_, eigen_assert, and Eigen::MaxSizeVector< T >::size_.
back() [2/2]
template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T& Eigen::MaxSizeVector< T >::back () const inline
{
     eigen_assert(size_ > 0);
     return data_[size_ - 1];
   }
References Eigen::MaxSizeVector< T >::data_, eigen_assert, and Eigen::MaxSizeVector< T >::size_.
begin() [1/2]
template<typename T > EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE T* Eigen::MaxSizeVector< T >::begin () inline constexpr
 { return data_; }
References Eigen::MaxSizeVector< T >::data_.
begin() [2/2]
template<typename T > EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE const T* Eigen::MaxSizeVector< T >::begin () const inline constexpr
 { return data_; }
References Eigen::MaxSizeVector< T >::data_.
data() [1/2]
template<typename T > EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE T* Eigen::MaxSizeVector< T >::data () inline constexpr
 { return data_; }
References Eigen::MaxSizeVector< T >::data_.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
data() [2/2]
template<typename T > EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE const T* Eigen::MaxSizeVector< T >::data () const inline constexpr
 { return data_; }
References Eigen::MaxSizeVector< T >::data_.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
emplace_back()
template<typename T > template<class X > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::MaxSizeVector< T >::emplace_back (const X & x) inline
{
     eigen_assert(size_ < reserve_);
     new (&data_[size_++]) T(x);
   }
References Eigen::MaxSizeVector< T >::data_, eigen_assert, Eigen::MaxSizeVector< T >::reserve_, Eigen::MaxSizeVector< T >::size_, and plotDoE::x.
empty()
template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool Eigen::MaxSizeVector< T >::empty () const inline
 { return size_ == 0; }
References Eigen::MaxSizeVector< T >::size_.
end() [1/2]
template<typename T > EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE T* Eigen::MaxSizeVector< T >::end () inline constexpr
 { return data_ + size_; }
References Eigen::MaxSizeVector< T >::data_, and Eigen::MaxSizeVector< T >::size_.
end() [2/2]
template<typename T > EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE const T* Eigen::MaxSizeVector< T >::end () const inline constexpr
 { return data_ + size_; }
References Eigen::MaxSizeVector< T >::data_, and Eigen::MaxSizeVector< T >::size_.
operator[]() [1/2]
template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T& Eigen::MaxSizeVector< T >::operator[] (size_t i) inline
{
     eigen_assert(i < size_);
     return data_[i];
   }
References Eigen::MaxSizeVector< T >::data_, eigen_assert, i, and Eigen::MaxSizeVector< T >::size_.
operator[]() [2/2]
template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T& Eigen::MaxSizeVector< T >::operator[] (size_t i) const inline
{
     eigen_assert(i < size_);
     return data_[i];
   }
References Eigen::MaxSizeVector< T >::data_, eigen_assert, i, and Eigen::MaxSizeVector< T >::size_.
pop_back()
template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::MaxSizeVector< T >::pop_back () inline
{
     eigen_assert(size_ > 0);
     data_[--size_].~T();
   }
References Eigen::MaxSizeVector< T >::data_, eigen_assert, and Eigen::MaxSizeVector< T >::size_.
push_back()
template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::MaxSizeVector< T >::push_back (const T & t) inline
{
     eigen_assert(size_ < reserve_);
     new (&data_[size_++]) T(t);
   }
References Eigen::MaxSizeVector< T >::data_, eigen_assert, Eigen::MaxSizeVector< T >::reserve_, Eigen::MaxSizeVector< T >::size_, and plotPSD::t.
Referenced by Eigen::ThreadPoolTempl< Environment >::ComputeCoprimes().
resize()
template<typename T > void Eigen::MaxSizeVector< T >::resize (size_t n) inline
{
     eigen_assert(n <= reserve_);
     for (; size_ < n; ++size_) {
       new (&data_[size_]) T;
     }
     for (; size_ > n; --size_) {
       data_[size_ - 1].~T();
     }
     eigen_assert(size_ == n);
   }
References Eigen::MaxSizeVector< T >::data_, eigen_assert, n, Eigen::MaxSizeVector< T >::reserve_, and Eigen::MaxSizeVector< T >::size_.
Referenced by test_basic_eventcount(), and test_stress_eventcount().
size()
template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE size_t Eigen::MaxSizeVector< T >::size () const inline
 { return size_; }
References Eigen::MaxSizeVector< T >::size_.
Referenced by Eigen::EventCount::EventCount().
Member Data Documentation
alignment
template<typename T > const size_t Eigen::MaxSizeVector< T >::alignment = internal::plain_enum_max(EIGEN_ALIGNOF(T), sizeof(void*)) static private
data_
template<typename T > T* Eigen::MaxSizeVector< T >::data_ private
Referenced by Eigen::MaxSizeVector< T >::back(), Eigen::MaxSizeVector< T >::begin(), Eigen::MaxSizeVector< T >::data(), Eigen::MaxSizeVector< T >::emplace_back(), Eigen::MaxSizeVector< T >::end(), Eigen::MaxSizeVector< T >::MaxSizeVector(), Eigen::MaxSizeVector< T >::operator[](), Eigen::MaxSizeVector< T >::pop_back(), Eigen::MaxSizeVector< T >::push_back(), Eigen::MaxSizeVector< T >::resize(), and Eigen::MaxSizeVector< T >::~MaxSizeVector().
reserve_
template<typename T > size_t Eigen::MaxSizeVector< T >::reserve_ private
Referenced by Eigen::MaxSizeVector< T >::emplace_back(), Eigen::MaxSizeVector< T >::push_back(), and Eigen::MaxSizeVector< T >::resize().
size_
template<typename T > size_t Eigen::MaxSizeVector< T >::size_ private
Referenced by Eigen::MaxSizeVector< T >::back(), Eigen::MaxSizeVector< T >::emplace_back(), Eigen::MaxSizeVector< T >::empty(), Eigen::MaxSizeVector< T >::end(), Eigen::MaxSizeVector< T >::MaxSizeVector(), Eigen::MaxSizeVector< T >::operator[](), Eigen::MaxSizeVector< T >::pop_back(), Eigen::MaxSizeVector< T >::push_back(), Eigen::MaxSizeVector< T >::resize(), Eigen::MaxSizeVector< T >::size(), and Eigen::MaxSizeVector< T >::~MaxSizeVector().
The documentation for this class was generated from the following file:
MaxSizeVector.h