MercuryDPM: oomph::DummyBrickElement Class Reference
oomph::DummyBrickElement Class Reference
#include <brick_mesh.h>
Public Member Functions
DummyBrickElement ()
Constructor:
DummyBrickElement (const DummyBrickElement &dummy)=delete
Broken copy constructor.
unsigned required_nvalue (const unsigned &n) const
Broken assignment operator.
void interpolated_s_tet (const Vector< double > &s, Vector< double > &s_tet) const
void output (std::ostream &outfile, const unsigned &nplot=5)
Output interpolated tet local coordinates.
Detailed Description
//////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////// Dummy QElement to interpolate local coordinates – used in construction of brickified tet mesh.
Constructor & Destructor Documentation
DummyBrickElement() [1/2]
oomph::DummyBrickElement::DummyBrickElement () inline
Constructor:
 : QElement<3, 2>() {}
DummyBrickElement() [2/2]
oomph::DummyBrickElement::DummyBrickElement (const DummyBrickElement & dummy) delete
Broken copy constructor.
Member Function Documentation
interpolated_s_tet()
void oomph::DummyBrickElement::interpolated_s_tet (const Vector< double > & s, Vector< double > & s_tet) const inline
Compute vector of FE interpolated local coordinate in tet, s_tet, evaluated at local coordinate s in current element.
     {
       // Find number of nodes
       unsigned n_node = nnode();
       // Local shape function
       Shape psi(n_node);
       // Find values of shape function
       shape(s, psi);
       for (unsigned i = 0; i < 3; i++)
       {
         // Initialise value of u
         s_tet[i] = 0.0;
         // Loop over the local nodes and sum
         for (unsigned l = 0; l < n_node; l++)
         {
           s_tet[i] += nodal_value(l, i) * psi[l];
         }
       }
     }
References i, s, and oomph::OneDimLagrange::shape().
Referenced by output().
output()
void oomph::DummyBrickElement::output (std::ostream & outfile, const unsigned & nplot = 5) inline
Output interpolated tet local coordinates.
     {
       // Vector of local coordinates
       Vector<double> s(3);
       Vector<double> s_tet(3);
       // Tecplot header info
       outfile << tecplot_zone_string(nplot);
       // Loop over plot points
       unsigned num_plot_points = nplot_points(nplot);
       for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
       {
         // Get local coordinates of plot point
         get_s_plot(iplot, nplot, s);
         // Local coordinates in tet
         interpolated_s_tet(s, s_tet);
         // Coordinates
         for (unsigned i = 0; i < 3; i++)
         {
           outfile << interpolated_x(s, i) << " ";
         }
         // Local coordinates in tet
         for (unsigned i = 0; i < 3; i++)
         {
           outfile << s_tet[i] << " ";
         }
         outfile << std::endl;
       }
       outfile << std::endl;
       // Write tecplot footer (e.g. FE connectivity lists)
       write_tecplot_zone_footer(outfile, nplot);
     }
References i, interpolated_s_tet(), and s.
required_nvalue()
unsigned oomph::DummyBrickElement::required_nvalue (const unsigned & n) const inline
Broken assignment operator.
Required # of ‘values’ (pinned or dofs) at node n
     {
       return 3;
     }
The documentation for this class was generated from the following file:
brick_mesh.h