MercuryDPM: rapidjson::GenericDocument< Encoding, Allocator > Class Template Reference
rapidjson::GenericDocument< Encoding, Allocator > Class Template Reference
A document for parsing JSON text as DOM.
#include <document.h>
Public Types
typedef Encoding::Ch Ch
Character type derived from Encoding.
typedef GenericValue< Encoding, Allocator > ValueType
Value type of the document.
typedef Allocator AllocatorType
Allocator type from template parameter.
Public Types inherited from rapidjson::GenericValue< Encoding, MemoryPoolAllocator<> >
typedef Encoding EncodingType
Encoding type from template parameter.
typedef MemoryPoolAllocator<> AllocatorType
Allocator type from template parameter.
typedef Encoding::Ch Ch
Character type derived from Encoding.
typedef Member * MemberIterator
Member iterator for iterating in object.
typedef const Member * ConstMemberIterator
Constant member iterator for iterating in object.
typedef GenericValue * ValueIterator
Value iterator for iterating in array.
typedef const GenericValue * ConstValueIterator
Constant value iterator for iterating in array.
Public Member Functions
GenericDocument (Allocator *allocator=0, size_t stackCapacity=kDefaultStackCapacity)
Constructor.
template<unsigned parseFlags, typename Stream >
GenericDocument & ParseStream (Stream &stream)
Parse JSON text from an input stream.
template<unsigned parseFlags>
GenericDocument & ParseInsitu (Ch *str)
Parse JSON text from a mutable string.
template<unsigned parseFlags>
GenericDocument & Parse (const Ch *str)
Parse JSON text from a read-only string.
bool HasParseError () const
Whether a parse error was occured in the last parsing.
const char * GetParseError () const
Get the message of parsing error.
size_t GetErrorOffset () const
Get the offset in character of the parsing error.
Allocator & GetAllocator ()
Get the allocator of this document.
size_t GetStackCapacity () const
Get the capacity of stack in bytes.
Public Member Functions inherited from rapidjson::GenericValue< Encoding, MemoryPoolAllocator<> >
GenericValue & operator= (GenericValue &rhs)
Assignment with move semantics.
GenericValue & operator= (T value)
Assignment with primitive types.
Type GetType () const
bool IsNull_ () const
bool IsFalse () const
bool IsTrue () const
bool IsBool_ () const
bool IsObject () const
bool IsArray () const
bool IsNumber () const
bool IsInt () const
bool IsUint () const
bool IsInt64 () const
bool IsUint64 () const
bool IsDouble () const
bool IsString () const
GenericValue & SetNull_ ()
bool GetBool_ () const
GenericValue & SetBool_ (bool b)
GenericValue & SetObject ()
Set this value as an empty object.
GenericValue & operator[] (const Ch *name)
Get the value associated with the object's name.
const GenericValue & operator[] (const Ch *name) const
ConstMemberIterator MemberBegin () const
Member iterators.
MemberIterator MemberBegin ()
ConstMemberIterator MemberEnd () const
MemberIterator MemberEnd ()
bool HasMember (const Ch *name) const
Check whether a member exists in the object.
GenericValue & AddMember (GenericValue &name, GenericValue &value, MemoryPoolAllocator<> &allocator)
Add a member (name-value pair) to the object.
GenericValue & AddMember (const Ch *name, MemoryPoolAllocator<> &nameAllocator, GenericValue &value, MemoryPoolAllocator<> &allocator)
GenericValue & AddMember (const Ch *name, GenericValue &value, MemoryPoolAllocator<> &allocator)
GenericValue & AddMember (const Ch *name, T value, MemoryPoolAllocator<> &allocator)
bool RemoveMember (const Ch *name)
Remove a member in object by its name.
GenericValue & operator[] (SizeType index)
Get an element from array by index.
const GenericValue & operator[] (SizeType index) const
GenericValue & SetArray ()
Set this value as an empty array.
SizeType Size () const
Get the number of elements in array.
SizeType Capacity () const
Get the capacity of array.
bool Empty () const
Check whether the array is empty.
void Clear ()
Remove all elements in the array.
ValueIterator Begin ()
Element iterator.
ConstValueIterator Begin () const
ValueIterator End ()
ConstValueIterator End () const
GenericValue & Reserve (SizeType newCapacity, MemoryPoolAllocator<> &allocator)
Request the array to have enough capacity to store elements.
GenericValue & PushBack (GenericValue &value, MemoryPoolAllocator<> &allocator)
Append a value at the end of the array.
GenericValue & PushBack (T value, MemoryPoolAllocator<> &allocator)
GenericValue & PopBack ()
Remove the last element in the array.
int GetInt () const
unsigned GetUint () const
int64_t GetInt64 () const
uint64_t GetUint64 () const
double GetDouble () const
GenericValue & SetInt (int i)
GenericValue & SetUint (unsigned u)
GenericValue & SetInt64 (int64_t i64)
GenericValue & SetUint64 (uint64_t u64)
GenericValue & SetDouble (double d)
const Ch * GetString () const
SizeType GetStringLength () const
Get the length of string.
GenericValue & SetString (const Ch *s, SizeType length)
Set this value as a string without copying source string.
GenericValue & SetString (const Ch *s)
Set this value as a string without copying source string.
GenericValue & SetString (const Ch *s, SizeType length, MemoryPoolAllocator<> &allocator)
Set this value as a string by copying from source string.
GenericValue & SetString (const Ch *s, MemoryPoolAllocator<> &allocator)
Set this value as a string by copying from source string.
const GenericValue & Accept (Handler &handler) const
Generate events of this value to a Handler.
GenericValue ()
Default constructor creates a null value.
GenericValue (Type type)
Constructor with JSON value type.
GenericValue (bool b)
Constructor for boolean value.
GenericValue (int i)
Constructor for int value.
GenericValue (unsigned u)
Constructor for unsigned value.
GenericValue (int64_t i64)
Constructor for int64_t value.
GenericValue (uint64_t u64)
Constructor for uint64_t value.
GenericValue (double d)
Constructor for double value.
GenericValue (const Ch *s, SizeType length)
Constructor for constant string (i.e. do not make a copy of string)
GenericValue (const Ch *s)
Constructor for constant string (i.e. do not make a copy of string)
GenericValue (const Ch *s, SizeType length, MemoryPoolAllocator<> &allocator)
Constructor for copy-string (i.e. do make a copy of string)
GenericValue (const Ch *s, MemoryPoolAllocator<> &allocator)
Constructor for copy-string (i.e. do make a copy of string)
~GenericValue ()
Destructor.
Private Member Functions
GenericDocument & operator= (const GenericDocument &)
void Null_ ()
void Bool_ (bool b)
void Int (int i)
void Uint (unsigned i)
void Int64 (int64_t i)
void Uint64 (uint64_t i)
void Double (double d)
void String (const Ch *str, SizeType length, bool copy)
void StartObject ()
void EndObject (SizeType memberCount)
void StartArray ()
void EndArray (SizeType elementCount)
void ClearStack ()
Private Attributes
internal::Stack< Allocator > stack_
const char * parseError_
size_t errorOffset_
Static Private Attributes
static const size_t kDefaultStackCapacity = 1024
Friends
class GenericReader< Encoding, Allocator >
Detailed Description
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>>
class rapidjson::GenericDocument< Encoding, Allocator >
A document for parsing JSON text as DOM.
Template Parameters
Encoding encoding for both parsing and string storage.
Alloactor allocator for allocating memory for the DOM, and the stack during parsing.
Member Typedef Documentation
AllocatorType
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef Allocator rapidjson::GenericDocument< Encoding, Allocator >::AllocatorType
Allocator type from template parameter.
Ch
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef Encoding::Ch rapidjson::GenericDocument< Encoding, Allocator >::Ch
Character type derived from Encoding.
ValueType
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef GenericValue<Encoding, Allocator> rapidjson::GenericDocument< Encoding, Allocator >::ValueType
Value type of the document.
Constructor & Destructor Documentation
GenericDocument()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericDocument< Encoding, Allocator >::GenericDocument (Allocator * allocator = 0, size_t stackCapacity = kDefaultStackCapacity) inline
Constructor.
Parameters
allocator Optional allocator for allocating stack memory.
stackCapacity Initial capacity of stack in bytes.
 : stack_(allocator, stackCapacity), parseError_(0), errorOffset_(0) {}
Member Function Documentation
Bool_()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void rapidjson::GenericDocument< Encoding, Allocator >::Bool_ (bool b) inline private
 { new (stack_.template Push<ValueType>()) ValueType(b); }
References b, and rapidjson::GenericDocument< Encoding, Allocator >::stack_.
ClearStack()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void rapidjson::GenericDocument< Encoding, Allocator >::ClearStack () inline private
                       {
         if (Allocator::kNeedFree)
             while (stack_.GetSize() > 0)    // Here assumes all elements in stack array are GenericValue (Member is actually 2 GenericValue objects)
                 (stack_.template Pop<ValueType>(1))->~ValueType();
         else
             stack_.Clear();
     }
References rapidjson::GenericDocument< Encoding, Allocator >::stack_.
Referenced by rapidjson::GenericDocument< Encoding, Allocator >::ParseStream().
Double()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void rapidjson::GenericDocument< Encoding, Allocator >::Double (double d) inline private
 { new (stack_.template Push<ValueType>()) ValueType(d); }
References rapidjson::GenericDocument< Encoding, Allocator >::stack_.
EndArray()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void rapidjson::GenericDocument< Encoding, Allocator >::EndArray (SizeType elementCount) inline private
{
         ValueType* elements = stack_.template Pop<ValueType>(elementCount);
         stack_.template Top<ValueType>()->SetArrayRaw(elements, elementCount, GetAllocator());
     }
References rapidjson::GenericDocument< Encoding, Allocator >::GetAllocator(), and rapidjson::GenericDocument< Encoding, Allocator >::stack_.
EndObject()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void rapidjson::GenericDocument< Encoding, Allocator >::EndObject (SizeType memberCount) inline private
{
         typename ValueType::Member* members = stack_.template Pop<typename ValueType::Member>(memberCount);
         stack_.template Top<ValueType>()->SetObjectRaw(members, (SizeType)memberCount, GetAllocator());
     }
References rapidjson::GenericDocument< Encoding, Allocator >::GetAllocator(), and rapidjson::GenericDocument< Encoding, Allocator >::stack_.
GetAllocator()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> Allocator& rapidjson::GenericDocument< Encoding, Allocator >::GetAllocator () inline
Get the allocator of this document.
 {   return stack_.GetAllocator(); }
References rapidjson::GenericDocument< Encoding, Allocator >::stack_.
Referenced by rapidjson::GenericDocument< Encoding, Allocator >::EndArray(), rapidjson::GenericDocument< Encoding, Allocator >::EndObject(), and rapidjson::GenericDocument< Encoding, Allocator >::String().
GetErrorOffset()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> size_t rapidjson::GenericDocument< Encoding, Allocator >::GetErrorOffset () const inline
Get the offset in character of the parsing error.
 { return errorOffset_; }
References rapidjson::GenericDocument< Encoding, Allocator >::errorOffset_.
GetParseError()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> const char* rapidjson::GenericDocument< Encoding, Allocator >::GetParseError () const inline
Get the message of parsing error.
 { return parseError_; }
References rapidjson::GenericDocument< Encoding, Allocator >::parseError_.
GetStackCapacity()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> size_t rapidjson::GenericDocument< Encoding, Allocator >::GetStackCapacity () const inline
Get the capacity of stack in bytes.
 { return stack_.GetCapacity(); }
References rapidjson::GenericDocument< Encoding, Allocator >::stack_.
HasParseError()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericDocument< Encoding, Allocator >::HasParseError () const inline
Whether a parse error was occured in the last parsing.
 { return parseError_ != 0; }
References rapidjson::GenericDocument< Encoding, Allocator >::parseError_.
Int()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void rapidjson::GenericDocument< Encoding, Allocator >::Int (int i) inline private
 { new (stack_.template Push<ValueType>()) ValueType(i); }
References i, and rapidjson::GenericDocument< Encoding, Allocator >::stack_.
Int64()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void rapidjson::GenericDocument< Encoding, Allocator >::Int64 (int64_t i) inline private
 { new (stack_.template Push<ValueType>()) ValueType(i); }
References i, and rapidjson::GenericDocument< Encoding, Allocator >::stack_.
Null_()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void rapidjson::GenericDocument< Encoding, Allocator >::Null_ () inline private
 { new (stack_.template Push<ValueType>()) ValueType(); }
References rapidjson::GenericDocument< Encoding, Allocator >::stack_.
operator=()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericDocument& rapidjson::GenericDocument< Encoding, Allocator >::operator= (const GenericDocument< Encoding, Allocator > &) private
Parse()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> template<unsigned parseFlags> GenericDocument& rapidjson::GenericDocument< Encoding, Allocator >::Parse (const Ch * str) inline
Parse JSON text from a read-only string.
Template Parameters
parseFlags Combination of ParseFlag (must not contain kParseInsituFlag).
Parameters
str Read-only zero-terminated string to be parsed.
{
         RAPIDJSON_ASSERT(!(parseFlags & kParseInsituFlag));
         GenericStringStream<Encoding> s(str);
         return ParseStream<parseFlags>(s);
     }
References rapidjson::kParseInsituFlag, RAPIDJSON_ASSERT, s, and compute_granudrum_aor::str.
ParseInsitu()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> template<unsigned parseFlags> GenericDocument& rapidjson::GenericDocument< Encoding, Allocator >::ParseInsitu (Ch * str) inline
Parse JSON text from a mutable string.
Template Parameters
parseFlags Combination of ParseFlag.
Parameters
str Mutable zero-terminated string to be parsed.
Returns
The document itself for fluent API.
{
         GenericInsituStringStream<Encoding> s(str);
         return ParseStream<parseFlags | kParseInsituFlag>(s);
     }
References s, and compute_granudrum_aor::str.
ParseStream()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> template<unsigned parseFlags, typename Stream > GenericDocument& rapidjson::GenericDocument< Encoding, Allocator >::ParseStream (Stream & stream) inline
Parse JSON text from an input stream.
Template Parameters
parseFlags Combination of ParseFlag.
Parameters
stream Input stream to be parsed.
Returns
The document itself for fluent API.
{
         ValueType::SetNull_(); // Remove existing root if exist
         GenericReader<Encoding, Allocator> reader;
         if (reader.template Parse<parseFlags>(stream, *this)) {
             RAPIDJSON_ASSERT(stack_.GetSize() == sizeof(ValueType)); // Got one and only one root object
             this->RawAssign(*stack_.template Pop<ValueType>(1));    // Add this-> to prevent issue 13.
             parseError_ = 0;
             errorOffset_ = 0;
         }
         else {
             parseError_ = reader.GetParseError();
             errorOffset_ = reader.GetErrorOffset();
             ClearStack();
         }
         return *this;
     }
References rapidjson::GenericDocument< Encoding, Allocator >::ClearStack(), rapidjson::GenericDocument< Encoding, Allocator >::errorOffset_, rapidjson::GenericReader< Encoding, Allocator >::GetErrorOffset(), rapidjson::GenericReader< Encoding, Allocator >::GetParseError(), rapidjson::GenericDocument< Encoding, Allocator >::parseError_, RAPIDJSON_ASSERT, rapidjson::GenericValue< Encoding, MemoryPoolAllocator<> >::RawAssign(), rapidjson::GenericValue< Encoding, Allocator >::SetNull_(), and rapidjson::GenericDocument< Encoding, Allocator >::stack_.
StartArray()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void rapidjson::GenericDocument< Encoding, Allocator >::StartArray () inline private
 { new (stack_.template Push<ValueType>()) ValueType(kArrayType); }
References rapidjson::kArrayType, and rapidjson::GenericDocument< Encoding, Allocator >::stack_.
StartObject()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void rapidjson::GenericDocument< Encoding, Allocator >::StartObject () inline private
 { new (stack_.template Push<ValueType>()) ValueType(kObjectType); }
References rapidjson::kObjectType, and rapidjson::GenericDocument< Encoding, Allocator >::stack_.
String()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void rapidjson::GenericDocument< Encoding, Allocator >::String (const Ch * str, SizeType length, bool copy) inline private
{
         if (copy)
             new (stack_.template Push<ValueType>()) ValueType(str, length, GetAllocator());
         else
             new (stack_.template Push<ValueType>()) ValueType(str, length);
     }
References copy(), rapidjson::GenericDocument< Encoding, Allocator >::GetAllocator(), rapidjson::GenericDocument< Encoding, Allocator >::stack_, and compute_granudrum_aor::str.
Uint()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void rapidjson::GenericDocument< Encoding, Allocator >::Uint (unsigned i) inline private
 { new (stack_.template Push<ValueType>()) ValueType(i); }
References i, and rapidjson::GenericDocument< Encoding, Allocator >::stack_.
Uint64()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void rapidjson::GenericDocument< Encoding, Allocator >::Uint64 (uint64_t i) inline private
 { new (stack_.template Push<ValueType>()) ValueType(i); }
References i, and rapidjson::GenericDocument< Encoding, Allocator >::stack_.
Friends And Related Function Documentation
GenericReader< Encoding, Allocator >
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> friend class GenericReader< Encoding, Allocator > friend
Member Data Documentation
errorOffset_
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> size_t rapidjson::GenericDocument< Encoding, Allocator >::errorOffset_ private
Referenced by rapidjson::GenericDocument< Encoding, Allocator >::GetErrorOffset(), and rapidjson::GenericDocument< Encoding, Allocator >::ParseStream().
kDefaultStackCapacity
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> const size_t rapidjson::GenericDocument< Encoding, Allocator >::kDefaultStackCapacity = 1024 static private
parseError_
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> const char* rapidjson::GenericDocument< Encoding, Allocator >::parseError_ private
Referenced by rapidjson::GenericDocument< Encoding, Allocator >::GetParseError(), rapidjson::GenericDocument< Encoding, Allocator >::HasParseError(), and rapidjson::GenericDocument< Encoding, Allocator >::ParseStream().
stack_
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> internal::Stack<Allocator> rapidjson::GenericDocument< Encoding, Allocator >::stack_ private
Referenced by rapidjson::GenericDocument< Encoding, Allocator >::Bool_(), rapidjson::GenericDocument< Encoding, Allocator >::ClearStack(), rapidjson::GenericDocument< Encoding, Allocator >::Double(), rapidjson::GenericDocument< Encoding, Allocator >::EndArray(), rapidjson::GenericDocument< Encoding, Allocator >::EndObject(), rapidjson::GenericDocument< Encoding, Allocator >::GetAllocator(), rapidjson::GenericDocument< Encoding, Allocator >::GetStackCapacity(), rapidjson::GenericDocument< Encoding, Allocator >::Int(), rapidjson::GenericDocument< Encoding, Allocator >::Int64(), rapidjson::GenericDocument< Encoding, Allocator >::Null_(), rapidjson::GenericDocument< Encoding, Allocator >::ParseStream(), rapidjson::GenericDocument< Encoding, Allocator >::StartArray(), rapidjson::GenericDocument< Encoding, Allocator >::StartObject(), rapidjson::GenericDocument< Encoding, Allocator >::String(), rapidjson::GenericDocument< Encoding, Allocator >::Uint(), and rapidjson::GenericDocument< Encoding, Allocator >::Uint64().
The documentation for this class was generated from the following file:
document.h