MercuryDPM: unstructured_two_d_solid.cc File Reference
meshing/quad_from_triangle_mesh/unstructured_two_d_solid.cc File Reference
#include "generic.h"
#include "solid.h"
#include "constitutive.h"
#include "meshes/quad_from_triangle_mesh.h"
Classes
class ElasticQuadFromTriangleMesh< ELEMENT >
Triangle-based mesh upgraded to become a solid mesh.
class UnstructuredSolidProblem< ELEMENT, MESH >
Unstructured solid problem.
Namespaces
Global_Physical_Variables
Global variables.
Functions
void Global_Physical_Variables::gravity (const double &time, const Vector< double > &xi, Vector< double > &b)
Non-dimensional gravity as body force.
void Global_Physical_Variables::constant_pressure (const Vector< double > &xi, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction)
Constant pressure load.
int main (int argc, char **argv)
Demonstrate how to solve an unstructured solid problem.
Variables
double Global_Physical_Variables::Gravity =0.0
Non-dim gravity.
Function Documentation
main()
int main (int argc , char ** argv)
Demonstrate how to solve an unstructured solid problem.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define case to be run
  unsigned i_case=0;
  CommandLineArgs::specify_command_line_flag("--case",&i_case);
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Create generalised Hookean constitutive equations
  Global_Physical_Variables::Constitutive_law_pt=
   new GeneralisedHookean(&Global_Physical_Variables::Nu);
  if (i_case==0)
  {
   std::cout << "Running with pure displacement formulation\n";
   // Typedef the element
   typedef QPVDElement<2,3> ELEMENT;
   // Set up the problem
   UnstructuredSolidProblem<ELEMENT> problem;
   // Output initial configuration
   problem.doc_solution();
   // Parameter study
   Global_Physical_Variables::Gravity=2.0e-4;
   Global_Physical_Variables::P=0.0;
   double pressure_increment=-1.0e-4;
   unsigned nstep=2; // 10;
   for (unsigned istep=0;istep<nstep;istep++)
   {
    // Solve the problem
    problem.newton_solve();
    // Output solution
    problem.doc_solution();
    // Bump up suction
    Global_Physical_Variables::P+=pressure_increment;
   }
  } // end_displacement_formulation
  else if (i_case==1)
   // Displacement/pressure formulation
  {
   std::cout << "Running with pressure/displacement formulation\n";
   // Typedef the element
   typedef QPVDElementWithContinuousPressure<2> ELEMENT;
   // Set up the problem
   UnstructuredSolidProblem<ELEMENT> problem;
   // Output initial configuration
   problem.doc_solution();
   // Parameter study
   Global_Physical_Variables::Gravity=2.0e-4;
   Global_Physical_Variables::P=0.0;
   double pressure_increment=-1.0e-4;
   unsigned nstep=2;
   for (unsigned istep=0;istep<nstep;istep++)
   {
    // Solve the problem
    problem.newton_solve();
    // Output solution
    problem.doc_solution();
    // Bump up suction
    Global_Physical_Variables::P+=pressure_increment;
   }
  }
  else if (i_case==2)
   // Displacement/pressure formulation enforcing incompressibility
  {
   std::cout << "Running with pressure/displacement "
         << "formulation (incompressible) \n";
   // Typedef the element
   typedef QPVDElementWithContinuousPressure<2> ELEMENT;
   // Set up the problem
   UnstructuredSolidProblem<ELEMENT> problem;
   // Output initial configuration
   problem.doc_solution();
   // Loop over all elements and set incompressibility flag
   {
    const unsigned n_element = problem.mesh_pt()->nelement();
    for(unsigned e=0;e<n_element;e++)
    {
     //Cast the element to the equation base of our 2D elastiticy elements
     PVDEquationsWithPressure<2> *cast_el_pt =
      dynamic_cast<PVDEquationsWithPressure<2>*>(
       problem.mesh_pt()->element_pt(e));
     //If the cast was successful, it's a bulk element,
     //so set the incompressibilty flag
     if(cast_el_pt)
     {
      cast_el_pt->set_incompressible();
     }
    }
   }
   // Output initial configuration
   problem.doc_solution();
   // Parameter study
   Global_Physical_Variables::Gravity=2.0e-4;
   Global_Physical_Variables::P=0.0;
   double pressure_increment=-1.0e-4;
   unsigned nstep=2;
   for (unsigned istep=0;istep<nstep;istep++)
   {
    // Solve the problem
    problem.newton_solve();
    //Output solution
    problem.doc_solution();
    // Bump up suction
    Global_Physical_Variables::P+=pressure_increment;
   }
  }
 } // end main
References Global_Physical_Variables::Constitutive_law_pt, oomph::CommandLineArgs::doc_specified_flags(), e(), Global_Physical_Variables::Gravity, Global_Physical_Variables::Nu, Global_Physical_Variables::P, oomph::CommandLineArgs::parse_and_assign(), problem, oomph::PVDEquationsWithPressure< DIM >::set_incompressible(), Flag_definition::setup(), and oomph::CommandLineArgs::specify_command_line_flag().