MercuryDPM: rapidjson::GenericValue< Encoding, Allocator > Class Template Reference
rapidjson::GenericValue< Encoding, Allocator > Class Template Reference
Represents a JSON value. Use Value for UTF8 encoding and default allocator.
#include <document.h>
Classes
struct Array
union Data
struct Member
Name-value pair in an object.
union Number
struct Object
struct String
Public Types
typedef Encoding EncodingType
Encoding type from template parameter.
typedef Allocator AllocatorType
Allocator type from template parameter.
typedef Encoding::Ch Ch
Character type derived from Encoding.
typedef Member * MemberIterator
Member iterator for iterating in object.
typedef const Member * ConstMemberIterator
Constant member iterator for iterating in object.
typedef GenericValue * ValueIterator
Value iterator for iterating in array.
typedef const GenericValue * ConstValueIterator
Constant value iterator for iterating in array.
Public Member Functions
Assignment operators
GenericValue & operator= (GenericValue &rhs)
Assignment with move semantics.
template<typename T >
GenericValue & operator= (T value)
Assignment with primitive types.
Type
Type GetType () const
bool IsNull_ () const
bool IsFalse () const
bool IsTrue () const
bool IsBool_ () const
bool IsObject () const
bool IsArray () const
bool IsNumber () const
bool IsInt () const
bool IsUint () const
bool IsInt64 () const
bool IsUint64 () const
bool IsDouble () const
bool IsString () const
Null_
GenericValue & SetNull_ ()
Bool_
bool GetBool_ () const
GenericValue & SetBool_ (bool b)
Object
GenericValue & SetObject ()
Set this value as an empty object.
GenericValue & operator[] (const Ch *name)
Get the value associated with the object's name.
const GenericValue & operator[] (const Ch *name) const
ConstMemberIterator MemberBegin () const
Member iterators.
ConstMemberIterator MemberEnd () const
MemberIterator MemberBegin ()
MemberIterator MemberEnd ()
bool HasMember (const Ch *name) const
Check whether a member exists in the object.
GenericValue & AddMember (GenericValue &name, GenericValue &value, Allocator &allocator)
Add a member (name-value pair) to the object.
GenericValue & AddMember (const Ch *name, Allocator &nameAllocator, GenericValue &value, Allocator &allocator)
GenericValue & AddMember (const Ch *name, GenericValue &value, Allocator &allocator)
template<typename T >
GenericValue & AddMember (const Ch *name, T value, Allocator &allocator)
bool RemoveMember (const Ch *name)
Remove a member in object by its name.
Array
GenericValue & SetArray ()
Set this value as an empty array.
SizeType Size () const
Get the number of elements in array.
SizeType Capacity () const
Get the capacity of array.
bool Empty () const
Check whether the array is empty.
void Clear ()
Remove all elements in the array.
GenericValue & operator[] (SizeType index)
Get an element from array by index.
const GenericValue & operator[] (SizeType index) const
ValueIterator Begin ()
Element iterator.
ValueIterator End ()
ConstValueIterator Begin () const
ConstValueIterator End () const
GenericValue & Reserve (SizeType newCapacity, Allocator &allocator)
Request the array to have enough capacity to store elements.
GenericValue & PushBack (GenericValue &value, Allocator &allocator)
Append a value at the end of the array.
template<typename T >
GenericValue & PushBack (T value, Allocator &allocator)
GenericValue & PopBack ()
Remove the last element in the array.
Number
int GetInt () const
unsigned GetUint () const
int64_t GetInt64 () const
uint64_t GetUint64 () const
double GetDouble () const
GenericValue & SetInt (int i)
GenericValue & SetUint (unsigned u)
GenericValue & SetInt64 (int64_t i64)
GenericValue & SetUint64 (uint64_t u64)
GenericValue & SetDouble (double d)
String
enum {
kBool_Flag = 0x100 , kNumberFlag = 0x200 , kIntFlag = 0x400 , kUintFlag = 0x800 ,
kInt64Flag = 0x1000 , kUint64Flag = 0x2000 , kDoubleFlag = 0x4000 , kStringFlag = 0x100000 ,
kCopyFlag = 0x200000 , kNull_Flag = kNull_Type , kTrueFlag = kTrueType | kBool_Flag , kFalseFlag = kFalseType | kBool_Flag ,
kNumberIntFlag = kNumberType | kNumberFlag | kIntFlag | kInt64Flag , kNumberUintFlag = kNumberType | kNumberFlag | kUintFlag | kUint64Flag | kInt64Flag , kNumberInt64Flag = kNumberType | kNumberFlag | kInt64Flag , kNumberUint64Flag = kNumberType | kNumberFlag | kUint64Flag ,
kNumberDoubleFlag = kNumberType | kNumberFlag | kDoubleFlag , kConstStringFlag = kStringType | kStringFlag , kCopyStringFlag = kStringType | kStringFlag | kCopyFlag , kObjectFlag = kObjectType ,
kArrayFlag = kArrayType , kTypeMask = 0xFF
}
template<typename , typename >
class GenericDocument
static const SizeType kDefaultArrayCapacity = 16
static const SizeType kDefaultObjectCapacity = 16
Data data_
unsigned flags_
const Ch * GetString () const
SizeType GetStringLength () const
Get the length of string.
GenericValue & SetString (const Ch *s, SizeType length)
Set this value as a string without copying source string.
GenericValue & SetString (const Ch *s)
Set this value as a string without copying source string.
GenericValue & SetString (const Ch *s, SizeType length, Allocator &allocator)
Set this value as a string by copying from source string.
GenericValue & SetString (const Ch *s, Allocator &allocator)
Set this value as a string by copying from source string.
template<typename Handler >
const GenericValue & Accept (Handler &handler) const
Generate events of this value to a Handler.
Member * FindMember (const Ch *name)
Find member by name.
const Member * FindMember (const Ch *name) const
void SetArrayRaw (GenericValue *values, SizeType count, Allocator &alloctaor)
void SetObjectRaw (Member *members, SizeType count, Allocator &alloctaor)
Initialize this value as object with initial data, without calling destructor.
void SetStringRaw (const Ch *s, SizeType length)
Initialize this value as constant string, without calling destructor.
void SetStringRaw (const Ch *s, SizeType length, Allocator &allocator)
Initialize this value as copy string with initial data, without calling destructor.
void RawAssign (GenericValue &rhs)
Assignment without calling destructor.
Constructors and destructor.
GenericValue ()
Default constructor creates a null value.
GenericValue (Type type)
Constructor with JSON value type.
GenericValue (bool b)
Constructor for boolean value.
GenericValue (int i)
Constructor for int value.
GenericValue (unsigned u)
Constructor for unsigned value.
GenericValue (int64_t i64)
Constructor for int64_t value.
GenericValue (uint64_t u64)
Constructor for uint64_t value.
GenericValue (double d)
Constructor for double value.
GenericValue (const Ch *s, SizeType length)
Constructor for constant string (i.e. do not make a copy of string)
GenericValue (const Ch *s)
Constructor for constant string (i.e. do not make a copy of string)
GenericValue (const Ch *s, SizeType length, Allocator &allocator)
Constructor for copy-string (i.e. do make a copy of string)
GenericValue (const Ch *s, Allocator &allocator)
Constructor for copy-string (i.e. do make a copy of string)
~GenericValue ()
Destructor.
GenericValue (const GenericValue &rhs)
Copy constructor is not permitted.
Detailed Description
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>>
class rapidjson::GenericValue< Encoding, Allocator >
Represents a JSON value. Use Value for UTF8 encoding and default allocator.
A JSON value can be one of 7 types. This class is a variant type supporting these types.
Use the Value if UTF8 and default allocator
Template Parameters
Encoding Encoding of the value. (Even non-string values need to have the same encoding in a document)
Allocator Allocator type for allocating memory of object, array and string.
Member Typedef Documentation
AllocatorType
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef Allocator rapidjson::GenericValue< Encoding, Allocator >::AllocatorType
Allocator type from template parameter.
Ch
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef Encoding::Ch rapidjson::GenericValue< Encoding, Allocator >::Ch
Character type derived from Encoding.
ConstMemberIterator
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef const Member* rapidjson::GenericValue< Encoding, Allocator >::ConstMemberIterator
Constant member iterator for iterating in object.
ConstValueIterator
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef const GenericValue* rapidjson::GenericValue< Encoding, Allocator >::ConstValueIterator
Constant value iterator for iterating in array.
EncodingType
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef Encoding rapidjson::GenericValue< Encoding, Allocator >::EncodingType
Encoding type from template parameter.
MemberIterator
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef Member* rapidjson::GenericValue< Encoding, Allocator >::MemberIterator
Member iterator for iterating in object.
ValueIterator
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef GenericValue* rapidjson::GenericValue< Encoding, Allocator >::ValueIterator
Value iterator for iterating in array.
Member Enumeration Documentation
anonymous enum
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> anonymous enum private
Enumerator
kBool_Flag
kNumberFlag
kIntFlag
kUintFlag
kInt64Flag
kUint64Flag
kDoubleFlag
kStringFlag
kCopyFlag
kNull_Flag
kTrueFlag
kFalseFlag
kNumberIntFlag
kNumberUintFlag
kNumberInt64Flag
kNumberUint64Flag
kNumberDoubleFlag
kConstStringFlag
kCopyStringFlag
kObjectFlag
kArrayFlag
kTypeMask
          {
         kBool_Flag = 0x100,
         kNumberFlag = 0x200,
         kIntFlag = 0x400,
         kUintFlag = 0x800,
         kInt64Flag = 0x1000,
         kUint64Flag = 0x2000,
         kDoubleFlag = 0x4000,
         kStringFlag = 0x100000,
         kCopyFlag = 0x200000,
         // Initial flags of different types.
         kNull_Flag = kNull_Type,
         kTrueFlag = kTrueType | kBool_Flag,
         kFalseFlag = kFalseType | kBool_Flag,
         kNumberIntFlag = kNumberType | kNumberFlag | kIntFlag | kInt64Flag,
         kNumberUintFlag = kNumberType | kNumberFlag | kUintFlag | kUint64Flag | kInt64Flag,
         kNumberInt64Flag = kNumberType | kNumberFlag | kInt64Flag,
         kNumberUint64Flag = kNumberType | kNumberFlag | kUint64Flag,
         kNumberDoubleFlag = kNumberType | kNumberFlag | kDoubleFlag,
         kConstStringFlag = kStringType | kStringFlag,
         kCopyStringFlag = kStringType | kStringFlag | kCopyFlag,
         kObjectFlag = kObjectType,
         kArrayFlag = kArrayType,
         kTypeMask = 0xFF    // bitwise-and with mask of 0xFF can be optimized by compiler
     };
Constructor & Destructor Documentation
GenericValue() [1/13]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue () inline
Default constructor creates a null value.
 : flags_(kNull_Flag) {}
Referenced by rapidjson::GenericValue< Encoding, Allocator >::operator=(), rapidjson::GenericValue< Encoding, Allocator >::Reserve(), rapidjson::GenericValue< Encoding, Allocator >::SetArray(), rapidjson::GenericValue< Encoding, Allocator >::SetBool_(), rapidjson::GenericValue< Encoding, Allocator >::SetDouble(), rapidjson::GenericValue< Encoding, Allocator >::SetInt(), rapidjson::GenericValue< Encoding, Allocator >::SetInt64(), rapidjson::GenericValue< Encoding, Allocator >::SetNull_(), rapidjson::GenericValue< Encoding, Allocator >::SetObject(), rapidjson::GenericValue< Encoding, Allocator >::SetUint(), and rapidjson::GenericValue< Encoding, Allocator >::SetUint64().
GenericValue() [2/13]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (const GenericValue< Encoding, Allocator > & rhs) private
Copy constructor is not permitted.
GenericValue() [3/13]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (Type type) inline
Constructor with JSON value type.
This creates a Value of specified type with default content.
Parameters
type Type of the value.
Note
Default content for number is zero.
{
         static const unsigned defaultFlags[7] = {
             kNull_Flag, kFalseFlag, kTrueFlag, kObjectFlag, kArrayFlag, kConstStringFlag,
             kNumberFlag | kIntFlag | kUintFlag | kInt64Flag | kUint64Flag | kDoubleFlag
         };
         RAPIDJSON_ASSERT(type <= kNumberType);
         flags_ = defaultFlags[type];
         memset(&data_, 0, sizeof(data_));
     }
References rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::flags_, rapidjson::GenericValue< Encoding, Allocator >::kArrayFlag, rapidjson::GenericValue< Encoding, Allocator >::kConstStringFlag, rapidjson::GenericValue< Encoding, Allocator >::kDoubleFlag, rapidjson::GenericValue< Encoding, Allocator >::kFalseFlag, rapidjson::GenericValue< Encoding, Allocator >::kInt64Flag, rapidjson::GenericValue< Encoding, Allocator >::kIntFlag, rapidjson::GenericValue< Encoding, Allocator >::kNull_Flag, rapidjson::GenericValue< Encoding, Allocator >::kNumberFlag, rapidjson::kNumberType, rapidjson::GenericValue< Encoding, Allocator >::kObjectFlag, rapidjson::GenericValue< Encoding, Allocator >::kTrueFlag, rapidjson::GenericValue< Encoding, Allocator >::kUint64Flag, rapidjson::GenericValue< Encoding, Allocator >::kUintFlag, RAPIDJSON_ASSERT, and compute_granudrum_aor::type.
GenericValue() [4/13]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (bool b) inline
Constructor for boolean value.
 : flags_(b ? kTrueFlag : kFalseFlag) {}
GenericValue() [5/13]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (int i) inline
Constructor for int value.
                         : flags_(kNumberIntFlag) {
         data_.n.i64 = i;
         if (i >= 0)
             flags_ |= kUintFlag | kUint64Flag;
     }
References rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::flags_, i, rapidjson::GenericValue< Encoding, Allocator >::Number::i64, rapidjson::GenericValue< Encoding, Allocator >::kUint64Flag, rapidjson::GenericValue< Encoding, Allocator >::kUintFlag, and rapidjson::GenericValue< Encoding, Allocator >::Data::n.
GenericValue() [6/13]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (unsigned u) inline
Constructor for unsigned value.
                              : flags_(kNumberUintFlag) {
         data_.n.u64 = u;
         if (!(u & 0x80000000))
             flags_ |= kIntFlag | kInt64Flag;
     }
References rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::flags_, rapidjson::GenericValue< Encoding, Allocator >::kInt64Flag, rapidjson::GenericValue< Encoding, Allocator >::kIntFlag, rapidjson::GenericValue< Encoding, Allocator >::Data::n, and rapidjson::GenericValue< Encoding, Allocator >::Number::u64.
GenericValue() [7/13]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (int64_t i64) inline
Constructor for int64_t value.
                               : flags_(kNumberInt64Flag) {
         data_.n.i64 = i64;
         if (i64 >= 0) {
             flags_ |= kNumberUint64Flag;
             if (!(i64 & 0xFFFFFFFF00000000LL))
                 flags_ |= kUintFlag;
             if (!(i64 & 0xFFFFFFFF80000000LL))
                 flags_ |= kIntFlag;
         }
         else if (i64 >= -2147483648LL)
             flags_ |= kIntFlag;
     }
References rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::flags_, rapidjson::GenericValue< Encoding, Allocator >::Number::i64, rapidjson::GenericValue< Encoding, Allocator >::kIntFlag, rapidjson::GenericValue< Encoding, Allocator >::kNumberUint64Flag, rapidjson::GenericValue< Encoding, Allocator >::kUintFlag, and rapidjson::GenericValue< Encoding, Allocator >::Data::n.
GenericValue() [8/13]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (uint64_t u64) inline
Constructor for uint64_t value.
                                : flags_(kNumberUint64Flag) {
         data_.n.u64 = u64;
         if (!(u64 & 0x8000000000000000ULL))
             flags_ |= kInt64Flag;
         if (!(u64 & 0xFFFFFFFF00000000ULL))
             flags_ |= kUintFlag;
         if (!(u64 & 0xFFFFFFFF80000000ULL))
             flags_ |= kIntFlag;
     }
References rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::flags_, rapidjson::GenericValue< Encoding, Allocator >::kInt64Flag, rapidjson::GenericValue< Encoding, Allocator >::kIntFlag, rapidjson::GenericValue< Encoding, Allocator >::kUintFlag, rapidjson::GenericValue< Encoding, Allocator >::Data::n, and rapidjson::GenericValue< Encoding, Allocator >::Number::u64.
GenericValue() [9/13]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (double d) inline
Constructor for double value.
 : flags_(kNumberDoubleFlag) { data_.n.d = d; }
References rapidjson::GenericValue< Encoding, Allocator >::Number::d, rapidjson::GenericValue< Encoding, Allocator >::data_, and rapidjson::GenericValue< Encoding, Allocator >::Data::n.
GenericValue() [10/13]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (const Ch * s, SizeType length) inline
Constructor for constant string (i.e. do not make a copy of string)
{
         RAPIDJSON_ASSERT(s != NULL);
         flags_ = kConstStringFlag;
         data_.s.str = s;
         data_.s.length = length;
     }
References rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::flags_, rapidjson::GenericValue< Encoding, Allocator >::kConstStringFlag, rapidjson::GenericValue< Encoding, Allocator >::String::length, RAPIDJSON_ASSERT, rapidjson::GenericValue< Encoding, Allocator >::Data::s, s, and rapidjson::GenericValue< Encoding, Allocator >::String::str.
GenericValue() [11/13]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (const Ch * s) inline
Constructor for constant string (i.e. do not make a copy of string)
 { SetStringRaw(s, internal::StrLen(s)); }
References s, rapidjson::GenericValue< Encoding, Allocator >::SetStringRaw(), and rapidjson::internal::StrLen().
GenericValue() [12/13]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (const Ch * s, SizeType length, Allocator & allocator) inline
Constructor for copy-string (i.e. do make a copy of string)
 { SetStringRaw(s, length, allocator); }
References s, and rapidjson::GenericValue< Encoding, Allocator >::SetStringRaw().
GenericValue() [13/13]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (const Ch * s, Allocator & allocator) inline
Constructor for copy-string (i.e. do make a copy of string)
 { SetStringRaw(s, internal::StrLen(s), allocator); }
References s, rapidjson::GenericValue< Encoding, Allocator >::SetStringRaw(), and rapidjson::internal::StrLen().
~GenericValue()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> rapidjson::GenericValue< Encoding, Allocator >::~GenericValue () inline
Destructor.
Need to destruct elements of array, members of object, or copy-string.
                     {
         if (Allocator::kNeedFree) { // Shortcut by Allocator's trait
             switch(flags_) {
             case kArrayFlag:
                 for (GenericValue* v = data_.a.elements; v != data_.a.elements + data_.a.size; ++v)
                     v->~GenericValue();
                 Allocator::Free(data_.a.elements);
                 break;
             case kObjectFlag:
                 for (Member* m = data_.o.members; m != data_.o.members + data_.o.size; ++m) {
                     m->name.~GenericValue();
                     m->value.~GenericValue();
                 }
                 Allocator::Free(data_.o.members);
                 break;
             case kCopyStringFlag:
                 Allocator::Free(const_cast<Ch*>(data_.s.str));
                 break;
             }
         }
     }
References rapidjson::GenericValue< Encoding, Allocator >::Data::a, rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::Array::elements, rapidjson::GenericValue< Encoding, Allocator >::flags_, rapidjson::GenericValue< Encoding, Allocator >::kArrayFlag, rapidjson::GenericValue< Encoding, Allocator >::kCopyStringFlag, rapidjson::GenericValue< Encoding, Allocator >::kObjectFlag, m, rapidjson::GenericValue< Encoding, Allocator >::Object::members, rapidjson::GenericValue< Encoding, Allocator >::Data::o, rapidjson::GenericValue< Encoding, Allocator >::Data::s, rapidjson::GenericValue< Encoding, Allocator >::Object::size, rapidjson::GenericValue< Encoding, Allocator >::Array::size, rapidjson::GenericValue< Encoding, Allocator >::String::str, and v.
Referenced by rapidjson::GenericValue< Encoding, Allocator >::operator=(), rapidjson::GenericValue< Encoding, Allocator >::SetArray(), rapidjson::GenericValue< Encoding, Allocator >::SetBool_(), rapidjson::GenericValue< Encoding, Allocator >::SetDouble(), rapidjson::GenericValue< Encoding, Allocator >::SetInt(), rapidjson::GenericValue< Encoding, Allocator >::SetInt64(), rapidjson::GenericValue< Encoding, Allocator >::SetNull_(), rapidjson::GenericValue< Encoding, Allocator >::SetObject(), rapidjson::GenericValue< Encoding, Allocator >::SetString(), rapidjson::GenericValue< Encoding, Allocator >::SetUint(), and rapidjson::GenericValue< Encoding, Allocator >::SetUint64().
Member Function Documentation
Accept()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> template<typename Handler > const GenericValue& rapidjson::GenericValue< Encoding, Allocator >::Accept (Handler & handler) const inline
Generate events of this value to a Handler.
This function adopts the GoF visitor pattern. Typical usage is to output this JSON value as JSON text via Writer, which is a Handler. It can also be used to deep clone this value via GenericDocument, which is also a Handler.
Template Parameters
Handler type of handler.
Parameters
handler An object implementing concept Handler.
{
         switch(GetType()) {
         case kNull_Type:        handler.Null_(); break;
         case kFalseType:    handler.Bool_(false); break;
         case kTrueType:     handler.Bool_(true); break;
         case kObjectType:
             handler.StartObject();
             for (Member* m = data_.o.members; m != data_.o.members + data_.o.size; ++m) {
                 handler.String(m->name.data_.s.str, m->name.data_.s.length, false);
                 m->value.Accept(handler);
             }
             handler.EndObject(data_.o.size);
             break;
         case kArrayType:
             handler.StartArray();
             for (GenericValue* v = data_.a.elements; v != data_.a.elements + data_.a.size; ++v)
                 v->Accept(handler);
             handler.EndArray(data_.a.size);
             break;
         case kStringType:
             handler.String(data_.s.str, data_.s.length, false);
             break;
         case kNumberType:
             if (IsInt())            handler.Int(data_.n.i.i);
             else if (IsUint())      handler.Uint(data_.n.u.u);
             else if (IsInt64())     handler.Int64(data_.n.i64);
             else if (IsUint64())    handler.Uint64(data_.n.u64);
             else                    handler.Double(data_.n.d);
             break;
         }
         return *this;
     }
References rapidjson::GenericValue< Encoding, Allocator >::Data::a, rapidjson::GenericValue< Encoding, Allocator >::Number::d, rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::Array::elements, rapidjson::GenericValue< Encoding, Allocator >::GetType(), rapidjson::GenericValue< Encoding, Allocator >::Number::I::i, rapidjson::GenericValue< Encoding, Allocator >::Number::i, rapidjson::GenericValue< Encoding, Allocator >::Number::i64, rapidjson::GenericValue< Encoding, Allocator >::IsInt(), rapidjson::GenericValue< Encoding, Allocator >::IsInt64(), rapidjson::GenericValue< Encoding, Allocator >::IsUint(), rapidjson::GenericValue< Encoding, Allocator >::IsUint64(), rapidjson::kArrayType, rapidjson::kFalseType, rapidjson::kNull_Type, rapidjson::kNumberType, rapidjson::kObjectType, rapidjson::kStringType, rapidjson::kTrueType, rapidjson::GenericValue< Encoding, Allocator >::String::length, m, rapidjson::GenericValue< Encoding, Allocator >::Object::members, rapidjson::GenericValue< Encoding, Allocator >::Data::n, rapidjson::GenericValue< Encoding, Allocator >::Data::o, rapidjson::GenericValue< Encoding, Allocator >::Data::s, rapidjson::GenericValue< Encoding, Allocator >::Object::size, rapidjson::GenericValue< Encoding, Allocator >::Array::size, rapidjson::GenericValue< Encoding, Allocator >::String::str, rapidjson::GenericValue< Encoding, Allocator >::Number::U::u, rapidjson::GenericValue< Encoding, Allocator >::Number::u, rapidjson::GenericValue< Encoding, Allocator >::Number::u64, and v.
AddMember() [1/4]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::AddMember (const Ch * name, Allocator & nameAllocator, GenericValue< Encoding, Allocator > & value, Allocator & allocator) inline
{
         GenericValue n(name, internal::StrLen(name), nameAllocator);
         return AddMember(n, value, allocator);
     }
References rapidjson::GenericValue< Encoding, Allocator >::AddMember(), n, plotDoE::name, rapidjson::internal::StrLen(), and Eigen::value.
AddMember() [2/4]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::AddMember (const Ch * name, GenericValue< Encoding, Allocator > & value, Allocator & allocator) inline
{
         GenericValue n(name, internal::StrLen(name));
         return AddMember(n, value, allocator);
     }
References rapidjson::GenericValue< Encoding, Allocator >::AddMember(), n, plotDoE::name, rapidjson::internal::StrLen(), and Eigen::value.
AddMember() [3/4]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> template<typename T > GenericValue& rapidjson::GenericValue< Encoding, Allocator >::AddMember (const Ch * name, T value, Allocator & allocator) inline
{
         GenericValue n(name, internal::StrLen(name));
         GenericValue v(value);
         return AddMember(n, v, allocator);
     }
References rapidjson::GenericValue< Encoding, Allocator >::AddMember(), n, plotDoE::name, rapidjson::internal::StrLen(), v, and Eigen::value.
AddMember() [4/4]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::AddMember (GenericValue< Encoding, Allocator > & name, GenericValue< Encoding, Allocator > & value, Allocator & allocator) inline
Add a member (name-value pair) to the object.
Parameters
name A string value as name of member.
value Value of any type.
allocator Allocator for reallocating memory.
Returns
The value itself for fluent API.
Note
The ownership of name and value will be transfered to this object if success.
{
         RAPIDJSON_ASSERT(IsObject());
         RAPIDJSON_ASSERT(name.IsString());
         Object& o = data_.o;
         if (o.size >= o.capacity) {
             if (o.capacity == 0) {
                 o.capacity = kDefaultObjectCapacity;
                 o.members = (Member*)allocator.Malloc(o.capacity * sizeof(Member));
             }
             else {
                 SizeType oldCapacity = o.capacity;
                 o.capacity *= 2;
                 o.members = (Member*)allocator.Realloc(o.members, oldCapacity * sizeof(Member), o.capacity * sizeof(Member));
             }
         }
         o.members[o.size].name.RawAssign(name);
         o.members[o.size].value.RawAssign(value);
         o.size++;
         return *this;
     }
References rapidjson::GenericValue< Encoding, Allocator >::Object::capacity, rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::IsObject(), rapidjson::GenericValue< Encoding, Allocator >::kDefaultObjectCapacity, rapidjson::GenericValue< Encoding, Allocator >::Object::members, plotDoE::name, rapidjson::GenericValue< Encoding, Allocator >::Member::name, rapidjson::GenericValue< Encoding, Allocator >::Data::o, RAPIDJSON_ASSERT, rapidjson::GenericValue< Encoding, Allocator >::Object::size, rapidjson::GenericValue< Encoding, Allocator >::Member::value, and Eigen::value.
Referenced by rapidjson::GenericValue< Encoding, Allocator >::AddMember().
Begin() [1/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> ValueIterator rapidjson::GenericValue< Encoding, Allocator >::Begin () inline
Element iterator.
 { RAPIDJSON_ASSERT(IsArray()); return data_.a.elements; }
References rapidjson::GenericValue< Encoding, Allocator >::Data::a, rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::Array::elements, rapidjson::GenericValue< Encoding, Allocator >::IsArray(), and RAPIDJSON_ASSERT.
Referenced by rapidjson::GenericValue< Encoding, Allocator >::Begin().
Begin() [2/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> ConstValueIterator rapidjson::GenericValue< Encoding, Allocator >::Begin () const inline
 { return const_cast<GenericValue&>(*this).Begin(); }
References rapidjson::GenericValue< Encoding, Allocator >::Begin().
Capacity()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> SizeType rapidjson::GenericValue< Encoding, Allocator >::Capacity () const inline
Get the capacity of array.
 { RAPIDJSON_ASSERT(IsArray()); return data_.a.capacity; }
References rapidjson::GenericValue< Encoding, Allocator >::Data::a, rapidjson::GenericValue< Encoding, Allocator >::Array::capacity, rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::IsArray(), and RAPIDJSON_ASSERT.
Clear()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void rapidjson::GenericValue< Encoding, Allocator >::Clear () inline
Remove all elements in the array.
This function do not deallocate memory in the array, i.e. the capacity is unchanged.
                  {
         RAPIDJSON_ASSERT(IsArray());
         for (SizeType i = 0; i < data_.a.size; ++i)
             data_.a.elements[i].~GenericValue();
         data_.a.size = 0;
     }
References rapidjson::GenericValue< Encoding, Allocator >::Data::a, rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::Array::elements, i, rapidjson::GenericValue< Encoding, Allocator >::IsArray(), RAPIDJSON_ASSERT, and rapidjson::GenericValue< Encoding, Allocator >::Array::size.
Empty()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::Empty () const inline
Check whether the array is empty.
 { RAPIDJSON_ASSERT(IsArray()); return data_.a.size == 0; }
References rapidjson::GenericValue< Encoding, Allocator >::Data::a, rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::IsArray(), RAPIDJSON_ASSERT, and rapidjson::GenericValue< Encoding, Allocator >::Array::size.
Referenced by rapidjson::GenericValue< Encoding, Allocator >::PopBack().
End() [1/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> ValueIterator rapidjson::GenericValue< Encoding, Allocator >::End () inline
 { RAPIDJSON_ASSERT(IsArray()); return data_.a.elements + data_.a.size; }
References rapidjson::GenericValue< Encoding, Allocator >::Data::a, rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::Array::elements, rapidjson::GenericValue< Encoding, Allocator >::IsArray(), RAPIDJSON_ASSERT, and rapidjson::GenericValue< Encoding, Allocator >::Array::size.
Referenced by rapidjson::GenericValue< Encoding, Allocator >::End().
End() [2/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> ConstValueIterator rapidjson::GenericValue< Encoding, Allocator >::End () const inline
 { return const_cast<GenericValue&>(*this).End(); }
References rapidjson::GenericValue< Encoding, Allocator >::End().
FindMember() [1/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> Member* rapidjson::GenericValue< Encoding, Allocator >::FindMember (const Ch * name) inline private
Find member by name.
{
         RAPIDJSON_ASSERT(name);
         RAPIDJSON_ASSERT(IsObject());
         SizeType length = internal::StrLen(name);
         Object& o = data_.o;
         for (Member* member = o.members; member != data_.o.members + data_.o.size; ++member)
             if (length == member->name.data_.s.length && memcmp(member->name.data_.s.str, name, length * sizeof(Ch)) == 0)
                 return member;
         return 0;
     }
References rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::IsObject(), rapidjson::GenericValue< Encoding, Allocator >::Object::members, plotDoE::name, rapidjson::GenericValue< Encoding, Allocator >::Data::o, RAPIDJSON_ASSERT, rapidjson::GenericValue< Encoding, Allocator >::Object::size, and rapidjson::internal::StrLen().
Referenced by rapidjson::GenericValue< Encoding, Allocator >::FindMember(), rapidjson::GenericValue< Encoding, Allocator >::HasMember(), rapidjson::GenericValue< Encoding, Allocator >::operator[](), and rapidjson::GenericValue< Encoding, Allocator >::RemoveMember().
FindMember() [2/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> const Member* rapidjson::GenericValue< Encoding, Allocator >::FindMember (const Ch * name) const inline private
 { return const_cast<GenericValue&>(*this).FindMember(name); }
References rapidjson::GenericValue< Encoding, Allocator >::FindMember(), and plotDoE::name.
GetBool_()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::GetBool_ () const inline
 { RAPIDJSON_ASSERT(IsBool_()); return flags_ == kTrueFlag; }
References rapidjson::GenericValue< Encoding, Allocator >::flags_, rapidjson::GenericValue< Encoding, Allocator >::IsBool_(), rapidjson::GenericValue< Encoding, Allocator >::kTrueFlag, and RAPIDJSON_ASSERT.
GetDouble()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> double rapidjson::GenericValue< Encoding, Allocator >::GetDouble () const inline
{
         RAPIDJSON_ASSERT(IsNumber());
         if ((flags_ & kDoubleFlag) != 0)                return data_.n.d;   // exact type, no conversion.
         if ((flags_ & kIntFlag) != 0)                   return data_.n.i.i; // int -> double
         if ((flags_ & kUintFlag) != 0)                  return data_.n.u.u; // unsigned -> double
         if ((flags_ & kInt64Flag) != 0)                 return (double)data_.n.i64; // int64_t -> double (may lose precision)
         RAPIDJSON_ASSERT((flags_ & kUint64Flag) != 0);  return (double)data_.n.u64; // uint64_t -> double (may lose precision)
     }
References rapidjson::GenericValue< Encoding, Allocator >::Number::d, rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::flags_, rapidjson::GenericValue< Encoding, Allocator >::Number::I::i, rapidjson::GenericValue< Encoding, Allocator >::Number::i, rapidjson::GenericValue< Encoding, Allocator >::Number::i64, rapidjson::GenericValue< Encoding, Allocator >::IsNumber(), rapidjson::GenericValue< Encoding, Allocator >::kDoubleFlag, rapidjson::GenericValue< Encoding, Allocator >::kInt64Flag, rapidjson::GenericValue< Encoding, Allocator >::kIntFlag, rapidjson::GenericValue< Encoding, Allocator >::kUint64Flag, rapidjson::GenericValue< Encoding, Allocator >::kUintFlag, rapidjson::GenericValue< Encoding, Allocator >::Data::n, RAPIDJSON_ASSERT, rapidjson::GenericValue< Encoding, Allocator >::Number::U::u, rapidjson::GenericValue< Encoding, Allocator >::Number::u, and rapidjson::GenericValue< Encoding, Allocator >::Number::u64.
GetInt()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> int rapidjson::GenericValue< Encoding, Allocator >::GetInt () const inline
 { RAPIDJSON_ASSERT(flags_ & kIntFlag);   return data_.n.i.i;   }
References rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::flags_, rapidjson::GenericValue< Encoding, Allocator >::Number::I::i, rapidjson::GenericValue< Encoding, Allocator >::Number::i, rapidjson::GenericValue< Encoding, Allocator >::kIntFlag, rapidjson::GenericValue< Encoding, Allocator >::Data::n, and RAPIDJSON_ASSERT.
GetInt64()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> int64_t rapidjson::GenericValue< Encoding, Allocator >::GetInt64 () const inline
 { RAPIDJSON_ASSERT(flags_ & kInt64Flag); return data_.n.i64; }
References rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::flags_, rapidjson::GenericValue< Encoding, Allocator >::Number::i64, rapidjson::GenericValue< Encoding, Allocator >::kInt64Flag, rapidjson::GenericValue< Encoding, Allocator >::Data::n, and RAPIDJSON_ASSERT.
GetString()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> const Ch* rapidjson::GenericValue< Encoding, Allocator >::GetString () const inline
 { RAPIDJSON_ASSERT(IsString()); return data_.s.str; }
References rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::IsString(), RAPIDJSON_ASSERT, rapidjson::GenericValue< Encoding, Allocator >::Data::s, and rapidjson::GenericValue< Encoding, Allocator >::String::str.
GetStringLength()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> SizeType rapidjson::GenericValue< Encoding, Allocator >::GetStringLength () const inline
Get the length of string.
Since rapidjson permits "\u0000" in the json string, strlen(v.GetString()) may not equal to v.GetStringLength().
 { RAPIDJSON_ASSERT(IsString()); return data_.s.length; }
References rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::IsString(), rapidjson::GenericValue< Encoding, Allocator >::String::length, RAPIDJSON_ASSERT, and rapidjson::GenericValue< Encoding, Allocator >::Data::s.
GetType()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> Type rapidjson::GenericValue< Encoding, Allocator >::GetType () const inline
 { return static_cast<Type>(flags_ & kTypeMask); }
References rapidjson::GenericValue< Encoding, Allocator >::flags_, and rapidjson::GenericValue< Encoding, Allocator >::kTypeMask.
Referenced by rapidjson::GenericValue< Encoding, Allocator >::Accept().
GetUint()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> unsigned rapidjson::GenericValue< Encoding, Allocator >::GetUint () const inline
 { RAPIDJSON_ASSERT(flags_ & kUintFlag);  return data_.n.u.u;   }
References rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::flags_, rapidjson::GenericValue< Encoding, Allocator >::kUintFlag, rapidjson::GenericValue< Encoding, Allocator >::Data::n, RAPIDJSON_ASSERT, rapidjson::GenericValue< Encoding, Allocator >::Number::U::u, and rapidjson::GenericValue< Encoding, Allocator >::Number::u.
GetUint64()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> uint64_t rapidjson::GenericValue< Encoding, Allocator >::GetUint64 () const inline
 { RAPIDJSON_ASSERT(flags_ & kUint64Flag); return data_.n.u64; }
References rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::flags_, rapidjson::GenericValue< Encoding, Allocator >::kUint64Flag, rapidjson::GenericValue< Encoding, Allocator >::Data::n, RAPIDJSON_ASSERT, and rapidjson::GenericValue< Encoding, Allocator >::Number::u64.
HasMember()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::HasMember (const Ch * name) const inline
Check whether a member exists in the object.
 { return FindMember(name) != 0; }
References rapidjson::GenericValue< Encoding, Allocator >::FindMember(), and plotDoE::name.
IsArray()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsArray () const inline
 { return flags_ == kArrayFlag; }
References rapidjson::GenericValue< Encoding, Allocator >::flags_, and rapidjson::GenericValue< Encoding, Allocator >::kArrayFlag.
Referenced by rapidjson::GenericValue< Encoding, Allocator >::Begin(), rapidjson::GenericValue< Encoding, Allocator >::Capacity(), rapidjson::GenericValue< Encoding, Allocator >::Clear(), rapidjson::GenericValue< Encoding, Allocator >::Empty(), rapidjson::GenericValue< Encoding, Allocator >::End(), rapidjson::GenericValue< Encoding, Allocator >::operator[](), rapidjson::GenericValue< Encoding, Allocator >::PopBack(), rapidjson::GenericValue< Encoding, Allocator >::PushBack(), rapidjson::GenericValue< Encoding, Allocator >::Reserve(), and rapidjson::GenericValue< Encoding, Allocator >::Size().
IsBool_()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsBool_ () const inline
 { return (flags_ & kBool_Flag) != 0; }
References rapidjson::GenericValue< Encoding, Allocator >::flags_, and rapidjson::GenericValue< Encoding, Allocator >::kBool_Flag.
Referenced by rapidjson::GenericValue< Encoding, Allocator >::GetBool_().
IsDouble()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsDouble () const inline
 { return (flags_ & kDoubleFlag) != 0; }
References rapidjson::GenericValue< Encoding, Allocator >::flags_, and rapidjson::GenericValue< Encoding, Allocator >::kDoubleFlag.
IsFalse()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsFalse () const inline
 { return flags_ == kFalseFlag; }
References rapidjson::GenericValue< Encoding, Allocator >::flags_, and rapidjson::GenericValue< Encoding, Allocator >::kFalseFlag.
IsInt()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsInt () const inline
 { return (flags_ & kIntFlag) != 0; }
References rapidjson::GenericValue< Encoding, Allocator >::flags_, and rapidjson::GenericValue< Encoding, Allocator >::kIntFlag.
Referenced by rapidjson::GenericValue< Encoding, Allocator >::Accept().
IsInt64()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsInt64 () const inline
 { return (flags_ & kInt64Flag) != 0; }
References rapidjson::GenericValue< Encoding, Allocator >::flags_, and rapidjson::GenericValue< Encoding, Allocator >::kInt64Flag.
Referenced by rapidjson::GenericValue< Encoding, Allocator >::Accept().
IsNull_()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsNull_ () const inline
 { return flags_ == kNull_Flag; }
References rapidjson::GenericValue< Encoding, Allocator >::flags_, and rapidjson::GenericValue< Encoding, Allocator >::kNull_Flag.
IsNumber()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsNumber () const inline
 { return (flags_ & kNumberFlag) != 0; }
References rapidjson::GenericValue< Encoding, Allocator >::flags_, and rapidjson::GenericValue< Encoding, Allocator >::kNumberFlag.
Referenced by rapidjson::GenericValue< Encoding, Allocator >::GetDouble().
IsObject()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsObject () const inline
 { return flags_ == kObjectFlag; }
References rapidjson::GenericValue< Encoding, Allocator >::flags_, and rapidjson::GenericValue< Encoding, Allocator >::kObjectFlag.
Referenced by rapidjson::GenericValue< Encoding, Allocator >::AddMember(), rapidjson::GenericValue< Encoding, Allocator >::FindMember(), rapidjson::GenericValue< Encoding, Allocator >::MemberBegin(), rapidjson::GenericValue< Encoding, Allocator >::MemberEnd(), and rapidjson::GenericValue< Encoding, Allocator >::RemoveMember().
IsString()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsString () const inline
 { return (flags_ & kStringFlag) != 0; }
References rapidjson::GenericValue< Encoding, Allocator >::flags_, and rapidjson::GenericValue< Encoding, Allocator >::kStringFlag.
Referenced by rapidjson::GenericValue< Encoding, Allocator >::GetString(), and rapidjson::GenericValue< Encoding, Allocator >::GetStringLength().
IsTrue()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsTrue () const inline
 { return flags_ == kTrueFlag; }
References rapidjson::GenericValue< Encoding, Allocator >::flags_, and rapidjson::GenericValue< Encoding, Allocator >::kTrueFlag.
IsUint()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsUint () const inline
 { return (flags_ & kUintFlag) != 0; }
References rapidjson::GenericValue< Encoding, Allocator >::flags_, and rapidjson::GenericValue< Encoding, Allocator >::kUintFlag.
Referenced by rapidjson::GenericValue< Encoding, Allocator >::Accept().
IsUint64()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::IsUint64 () const inline
 { return (flags_ & kUint64Flag) != 0; }
References rapidjson::GenericValue< Encoding, Allocator >::flags_, and rapidjson::GenericValue< Encoding, Allocator >::kUint64Flag.
Referenced by rapidjson::GenericValue< Encoding, Allocator >::Accept().
MemberBegin() [1/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> MemberIterator rapidjson::GenericValue< Encoding, Allocator >::MemberBegin () inline
 { RAPIDJSON_ASSERT(IsObject()); return data_.o.members; }
References rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::IsObject(), rapidjson::GenericValue< Encoding, Allocator >::Object::members, rapidjson::GenericValue< Encoding, Allocator >::Data::o, and RAPIDJSON_ASSERT.
MemberBegin() [2/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> ConstMemberIterator rapidjson::GenericValue< Encoding, Allocator >::MemberBegin () const inline
Member iterators.
 { RAPIDJSON_ASSERT(IsObject()); return data_.o.members; }
References rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::IsObject(), rapidjson::GenericValue< Encoding, Allocator >::Object::members, rapidjson::GenericValue< Encoding, Allocator >::Data::o, and RAPIDJSON_ASSERT.
MemberEnd() [1/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> MemberIterator rapidjson::GenericValue< Encoding, Allocator >::MemberEnd () inline
 { RAPIDJSON_ASSERT(IsObject()); return data_.o.members + data_.o.size; }
References rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::IsObject(), rapidjson::GenericValue< Encoding, Allocator >::Object::members, rapidjson::GenericValue< Encoding, Allocator >::Data::o, RAPIDJSON_ASSERT, and rapidjson::GenericValue< Encoding, Allocator >::Object::size.
MemberEnd() [2/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> ConstMemberIterator rapidjson::GenericValue< Encoding, Allocator >::MemberEnd () const inline
 { RAPIDJSON_ASSERT(IsObject()); return data_.o.members + data_.o.size; }
References rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::IsObject(), rapidjson::GenericValue< Encoding, Allocator >::Object::members, rapidjson::GenericValue< Encoding, Allocator >::Data::o, RAPIDJSON_ASSERT, and rapidjson::GenericValue< Encoding, Allocator >::Object::size.
operator=() [1/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::operator= (GenericValue< Encoding, Allocator > & rhs) inline
Assignment with move semantics.
Parameters
rhs Source of the assignment. It will become a null value after assignment.
{
         RAPIDJSON_ASSERT(this != &rhs);
         this->~GenericValue();
         memcpy(this, &rhs, sizeof(GenericValue));
         rhs.flags_ = kNull_Flag;
         return *this;
     }
References rapidjson::GenericValue< Encoding, Allocator >::flags_, rapidjson::GenericValue< Encoding, Allocator >::kNull_Flag, RAPIDJSON_ASSERT, and rapidjson::GenericValue< Encoding, Allocator >::~GenericValue().
operator=() [2/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> template<typename T > GenericValue& rapidjson::GenericValue< Encoding, Allocator >::operator= (T value) inline
Assignment with primitive types.
Template Parameters
T Either Type, int, unsigned, int64_t, uint64_t, const Ch*
Parameters
value The value to be assigned.
{
         this->~GenericValue();
         new (this) GenericValue(value);
         return *this;
     }
References rapidjson::GenericValue< Encoding, Allocator >::GenericValue(), and rapidjson::GenericValue< Encoding, Allocator >::~GenericValue().
operator[]() [1/4]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::operator[] (const Ch * name) inline
Get the value associated with the object's name.
{
         if (Member* member = FindMember(name))
             return member->value;
         else {
             static GenericValue Null_Value;
             return Null_Value;
         }
     }
References rapidjson::GenericValue< Encoding, Allocator >::FindMember(), and plotDoE::name.
operator[]() [2/4]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> const GenericValue& rapidjson::GenericValue< Encoding, Allocator >::operator[] (const Ch * name) const inline
 { return const_cast<GenericValue&>(*this)[name]; }
References plotDoE::name.
operator[]() [3/4]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::operator[] (SizeType index) inline
Get an element from array by index.
Parameters
index Zero-based index of element.
Note
Value a(kArrayType);
a.PushBack(123);
int x = a[0].GetInt();              // Error: operator[ is ambiguous, as 0 also mean a null pointer of const char* type.
int y = a[SizeType(0)].GetInt();    // Cast to SizeType will work.
int z = a[0u].GetInt();             // This works too.
{
         RAPIDJSON_ASSERT(IsArray());
         RAPIDJSON_ASSERT(index < data_.a.size);
         return data_.a.elements[index];
     }
References rapidjson::GenericValue< Encoding, Allocator >::Data::a, rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::Array::elements, rapidjson::GenericValue< Encoding, Allocator >::IsArray(), RAPIDJSON_ASSERT, and rapidjson::GenericValue< Encoding, Allocator >::Array::size.
operator[]() [4/4]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> const GenericValue& rapidjson::GenericValue< Encoding, Allocator >::operator[] (SizeType index) const inline
 { return const_cast<GenericValue&>(*this)[index]; }
PopBack()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::PopBack () inline
Remove the last element in the array.
{
         RAPIDJSON_ASSERT(IsArray());
         RAPIDJSON_ASSERT(!Empty());
         data_.a.elements[--data_.a.size].~GenericValue();
         return *this;
     }
References rapidjson::GenericValue< Encoding, Allocator >::Data::a, rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::Array::elements, rapidjson::GenericValue< Encoding, Allocator >::Empty(), rapidjson::GenericValue< Encoding, Allocator >::IsArray(), RAPIDJSON_ASSERT, and rapidjson::GenericValue< Encoding, Allocator >::Array::size.
PushBack() [1/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::PushBack (GenericValue< Encoding, Allocator > & value, Allocator & allocator) inline
Append a value at the end of the array.
Parameters
value The value to be appended.
allocator The allocator for allocating memory. It must be the same one use previously.
Returns
The value itself for fluent API.
Note
The ownership of the value will be transfered to this object if success.
If the number of elements to be appended is known, calls Reserve() once first may be more efficient.
{
         RAPIDJSON_ASSERT(IsArray());
         if (data_.a.size >= data_.a.capacity)
             Reserve(data_.a.capacity == 0 ? kDefaultArrayCapacity : data_.a.capacity * 2, allocator);
         data_.a.elements[data_.a.size++].RawAssign(value);
         return *this;
     }
References rapidjson::GenericValue< Encoding, Allocator >::Data::a, rapidjson::GenericValue< Encoding, Allocator >::Array::capacity, rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::Array::elements, rapidjson::GenericValue< Encoding, Allocator >::IsArray(), rapidjson::GenericValue< Encoding, Allocator >::kDefaultArrayCapacity, RAPIDJSON_ASSERT, rapidjson::GenericValue< Encoding, Allocator >::Reserve(), rapidjson::GenericValue< Encoding, Allocator >::Array::size, and Eigen::value.
Referenced by rapidjson::GenericValue< Encoding, Allocator >::PushBack().
PushBack() [2/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> template<typename T > GenericValue& rapidjson::GenericValue< Encoding, Allocator >::PushBack (T value, Allocator & allocator) inline
{
         GenericValue v(value);
         return PushBack(v, allocator);
     }
References rapidjson::GenericValue< Encoding, Allocator >::PushBack(), v, and Eigen::value.
RawAssign()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void rapidjson::GenericValue< Encoding, Allocator >::RawAssign (GenericValue< Encoding, Allocator > & rhs) inline private
Assignment without calling destructor.
{
         memcpy(this, &rhs, sizeof(GenericValue));
         rhs.flags_ = kNull_Flag;
     }
References rapidjson::GenericValue< Encoding, Allocator >::flags_, and rapidjson::GenericValue< Encoding, Allocator >::kNull_Flag.
RemoveMember()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> bool rapidjson::GenericValue< Encoding, Allocator >::RemoveMember (const Ch * name) inline
Remove a member in object by its name.
Parameters
name Name of member to be removed.
Returns
Whether the member existed.
Note
Removing member is implemented by moving the last member. So the ordering of members is changed.
{
         RAPIDJSON_ASSERT(IsObject());
         if (Member* m = FindMember(name)) {
             RAPIDJSON_ASSERT(data_.o.size > 0);
             RAPIDJSON_ASSERT(data_.o.members != 0);
             Member* last = data_.o.members + (data_.o.size - 1);
             if (data_.o.size > 1 && m != last) {
                 // Move the last one to this place
                 m->name = last->name;
                 m->value = last->value;
             }
             else {
                 // Only one left, just destroy
                 m->name.~GenericValue();
                 m->value.~GenericValue();
             }
             --data_.o.size;
             return true;
         }
         return false;
     }
References rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::FindMember(), rapidjson::GenericValue< Encoding, Allocator >::IsObject(), Eigen::placeholders::last, m, rapidjson::GenericValue< Encoding, Allocator >::Object::members, plotDoE::name, rapidjson::GenericValue< Encoding, Allocator >::Data::o, RAPIDJSON_ASSERT, and rapidjson::GenericValue< Encoding, Allocator >::Object::size.
Reserve()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::Reserve (SizeType newCapacity, Allocator & allocator) inline
Request the array to have enough capacity to store elements.
Parameters
newCapacity The capacity that the array at least need to have.
allocator The allocator for allocating memory. It must be the same one use previously.
Returns
The value itself for fluent API.
{
         RAPIDJSON_ASSERT(IsArray());
         if (newCapacity > data_.a.capacity) {
             data_.a.elements = (GenericValue*)allocator.Realloc(data_.a.elements, data_.a.capacity * sizeof(GenericValue), newCapacity * sizeof(GenericValue));
             data_.a.capacity = newCapacity;
         }
         return *this;
     }
References rapidjson::GenericValue< Encoding, Allocator >::Data::a, rapidjson::GenericValue< Encoding, Allocator >::Array::capacity, rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::Array::elements, rapidjson::GenericValue< Encoding, Allocator >::GenericValue(), rapidjson::GenericValue< Encoding, Allocator >::IsArray(), and RAPIDJSON_ASSERT.
Referenced by rapidjson::GenericValue< Encoding, Allocator >::PushBack().
SetArray()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetArray () inline
Set this value as an empty array.
 {   this->~GenericValue(); new (this) GenericValue(kArrayType); return *this; }
References rapidjson::GenericValue< Encoding, Allocator >::GenericValue(), rapidjson::kArrayType, and rapidjson::GenericValue< Encoding, Allocator >::~GenericValue().
SetArrayRaw()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void rapidjson::GenericValue< Encoding, Allocator >::SetArrayRaw (GenericValue< Encoding, Allocator > * values, SizeType count, Allocator & alloctaor) inline private
{
         flags_ = kArrayFlag;
         data_.a.elements = (GenericValue*)alloctaor.Malloc(count * sizeof(GenericValue));
         memcpy(data_.a.elements, values, count * sizeof(GenericValue));
         data_.a.size = data_.a.capacity = count;
     }
References rapidjson::GenericValue< Encoding, Allocator >::Data::a, rapidjson::GenericValue< Encoding, Allocator >::Array::capacity, rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::Array::elements, rapidjson::GenericValue< Encoding, Allocator >::flags_, rapidjson::GenericValue< Encoding, Allocator >::kArrayFlag, and rapidjson::GenericValue< Encoding, Allocator >::Array::size.
SetBool_()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetBool_ (bool b) inline
 { this->~GenericValue(); new (this) GenericValue(b); return *this; }
References rapidjson::GenericValue< Encoding, Allocator >::GenericValue(), and rapidjson::GenericValue< Encoding, Allocator >::~GenericValue().
SetDouble()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetDouble (double d) inline
 { this->~GenericValue(); new (this) GenericValue(d);    return *this; }
References rapidjson::GenericValue< Encoding, Allocator >::GenericValue(), and rapidjson::GenericValue< Encoding, Allocator >::~GenericValue().
SetInt()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetInt (int i) inline
 { this->~GenericValue(); new (this) GenericValue(i);    return *this; }
References rapidjson::GenericValue< Encoding, Allocator >::GenericValue(), and rapidjson::GenericValue< Encoding, Allocator >::~GenericValue().
SetInt64()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetInt64 (int64_t i64) inline
 { this->~GenericValue(); new (this) GenericValue(i64);  return *this; }
References rapidjson::GenericValue< Encoding, Allocator >::GenericValue(), and rapidjson::GenericValue< Encoding, Allocator >::~GenericValue().
SetNull_()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetNull_ () inline
 { this->~GenericValue(); new (this) GenericValue(); return *this; }
References rapidjson::GenericValue< Encoding, Allocator >::GenericValue(), and rapidjson::GenericValue< Encoding, Allocator >::~GenericValue().
Referenced by rapidjson::GenericDocument< Encoding, Allocator >::ParseStream().
SetObject()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetObject () inline
Set this value as an empty object.
 { this->~GenericValue(); new (this) GenericValue(kObjectType); return *this; }
References rapidjson::GenericValue< Encoding, Allocator >::GenericValue(), rapidjson::kObjectType, and rapidjson::GenericValue< Encoding, Allocator >::~GenericValue().
SetObjectRaw()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void rapidjson::GenericValue< Encoding, Allocator >::SetObjectRaw (Member * members, SizeType count, Allocator & alloctaor) inline private
Initialize this value as object with initial data, without calling destructor.
{
         flags_ = kObjectFlag;
         data_.o.members = (Member*)alloctaor.Malloc(count * sizeof(Member));
         memcpy(data_.o.members, members, count * sizeof(Member));
         data_.o.size = data_.o.capacity = count;
     }
References rapidjson::GenericValue< Encoding, Allocator >::Object::capacity, rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::flags_, rapidjson::GenericValue< Encoding, Allocator >::kObjectFlag, rapidjson::GenericValue< Encoding, Allocator >::Object::members, rapidjson::GenericValue< Encoding, Allocator >::Data::o, and rapidjson::GenericValue< Encoding, Allocator >::Object::size.
SetString() [1/4]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetString (const Ch * s) inline
Set this value as a string without copying source string.
Parameters
s source string pointer.
Returns
The value itself for fluent API.
 { return SetString(s, internal::StrLen(s)); }
References s, rapidjson::GenericValue< Encoding, Allocator >::SetString(), and rapidjson::internal::StrLen().
Referenced by rapidjson::GenericValue< Encoding, Allocator >::SetString().
SetString() [2/4]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetString (const Ch * s, Allocator & allocator) inline
Set this value as a string by copying from source string.
Parameters
s source string.
allocator Allocator for allocating copied buffer. Commonly use document.GetAllocator().
Returns
The value itself for fluent API.
 {   SetString(s, internal::StrLen(s), allocator); return *this; }
References s, rapidjson::GenericValue< Encoding, Allocator >::SetString(), and rapidjson::internal::StrLen().
Referenced by rapidjson::GenericValue< Encoding, Allocator >::SetString().
SetString() [3/4]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetString (const Ch * s, SizeType length) inline
Set this value as a string without copying source string.
This version has better performance with supplied length, and also support string containing null character.
Parameters
s source string pointer.
length The length of source string, excluding the trailing null terminator.
Returns
The value itself for fluent API.
 { this->~GenericValue(); SetStringRaw(s, length); return *this; }
References rapidjson::GenericValue< Encoding, Allocator >::SetStringRaw(), and rapidjson::GenericValue< Encoding, Allocator >::~GenericValue().
SetString() [4/4]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetString (const Ch * s, SizeType length, Allocator & allocator) inline
Set this value as a string by copying from source string.
This version has better performance with supplied length, and also support string containing null character.
Parameters
s source string.
length The length of source string, excluding the trailing null terminator.
allocator Allocator for allocating copied buffer. Commonly use document.GetAllocator().
Returns
The value itself for fluent API.
 { this->~GenericValue(); SetStringRaw(s, length, allocator); return *this; }
References rapidjson::GenericValue< Encoding, Allocator >::SetStringRaw(), and rapidjson::GenericValue< Encoding, Allocator >::~GenericValue().
SetStringRaw() [1/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void rapidjson::GenericValue< Encoding, Allocator >::SetStringRaw (const Ch * s, SizeType length) inline private
Initialize this value as constant string, without calling destructor.
{
         RAPIDJSON_ASSERT(s != NULL);
         flags_ = kConstStringFlag;
         data_.s.str = s;
         data_.s.length = length;
     }
References rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::flags_, rapidjson::GenericValue< Encoding, Allocator >::kConstStringFlag, rapidjson::GenericValue< Encoding, Allocator >::String::length, RAPIDJSON_ASSERT, rapidjson::GenericValue< Encoding, Allocator >::Data::s, s, and rapidjson::GenericValue< Encoding, Allocator >::String::str.
Referenced by rapidjson::GenericValue< Encoding, Allocator >::GenericValue(), and rapidjson::GenericValue< Encoding, Allocator >::SetString().
SetStringRaw() [2/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void rapidjson::GenericValue< Encoding, Allocator >::SetStringRaw (const Ch * s, SizeType length, Allocator & allocator) inline private
Initialize this value as copy string with initial data, without calling destructor.
{
         RAPIDJSON_ASSERT(s != NULL);
         flags_ = kCopyStringFlag;
         data_.s.str = (Ch *)allocator.Malloc((length + 1) * sizeof(Ch));
         data_.s.length = length;
         memcpy(const_cast<Ch*>(data_.s.str), s, length * sizeof(Ch));
         const_cast<Ch*>(data_.s.str)[length] = '\0';
     }
References rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::flags_, rapidjson::GenericValue< Encoding, Allocator >::kCopyStringFlag, rapidjson::GenericValue< Encoding, Allocator >::String::length, RAPIDJSON_ASSERT, rapidjson::GenericValue< Encoding, Allocator >::Data::s, s, and rapidjson::GenericValue< Encoding, Allocator >::String::str.
SetUint()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetUint (unsigned u) inline
 { this->~GenericValue(); new (this) GenericValue(u);    return *this; }
References rapidjson::GenericValue< Encoding, Allocator >::GenericValue(), and rapidjson::GenericValue< Encoding, Allocator >::~GenericValue().
SetUint64()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue& rapidjson::GenericValue< Encoding, Allocator >::SetUint64 (uint64_t u64) inline
 { this->~GenericValue(); new (this) GenericValue(u64);  return *this; }
References rapidjson::GenericValue< Encoding, Allocator >::GenericValue(), and rapidjson::GenericValue< Encoding, Allocator >::~GenericValue().
Size()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> SizeType rapidjson::GenericValue< Encoding, Allocator >::Size () const inline
Get the number of elements in array.
 { RAPIDJSON_ASSERT(IsArray()); return data_.a.size; }
References rapidjson::GenericValue< Encoding, Allocator >::Data::a, rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::IsArray(), RAPIDJSON_ASSERT, and rapidjson::GenericValue< Encoding, Allocator >::Array::size.
Friends And Related Function Documentation
GenericDocument
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> template<typename , typename > friend class GenericDocument friend
Member Data Documentation
data_
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> Data rapidjson::GenericValue< Encoding, Allocator >::data_ private
Referenced by rapidjson::GenericValue< Encoding, Allocator >::Accept(), rapidjson::GenericValue< Encoding, Allocator >::AddMember(), rapidjson::GenericValue< Encoding, Allocator >::Begin(), rapidjson::GenericValue< Encoding, Allocator >::Capacity(), rapidjson::GenericValue< Encoding, Allocator >::Clear(), rapidjson::GenericValue< Encoding, Allocator >::Empty(), rapidjson::GenericValue< Encoding, Allocator >::End(), rapidjson::GenericValue< Encoding, Allocator >::FindMember(), rapidjson::GenericValue< Encoding, Allocator >::GenericValue(), rapidjson::GenericValue< Encoding, Allocator >::GetDouble(), rapidjson::GenericValue< Encoding, Allocator >::GetInt(), rapidjson::GenericValue< Encoding, Allocator >::GetInt64(), rapidjson::GenericValue< Encoding, Allocator >::GetString(), rapidjson::GenericValue< Encoding, Allocator >::GetStringLength(), rapidjson::GenericValue< Encoding, Allocator >::GetUint(), rapidjson::GenericValue< Encoding, Allocator >::GetUint64(), rapidjson::GenericValue< Encoding, Allocator >::MemberBegin(), rapidjson::GenericValue< Encoding, Allocator >::MemberEnd(), rapidjson::GenericValue< Encoding, Allocator >::operator[](), rapidjson::GenericValue< Encoding, Allocator >::PopBack(), rapidjson::GenericValue< Encoding, Allocator >::PushBack(), rapidjson::GenericValue< Encoding, Allocator >::RemoveMember(), rapidjson::GenericValue< Encoding, Allocator >::Reserve(), rapidjson::GenericValue< Encoding, Allocator >::SetArrayRaw(), rapidjson::GenericValue< Encoding, Allocator >::SetObjectRaw(), rapidjson::GenericValue< Encoding, Allocator >::SetStringRaw(), rapidjson::GenericValue< Encoding, Allocator >::Size(), and rapidjson::GenericValue< Encoding, Allocator >::~GenericValue().
flags_
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> unsigned rapidjson::GenericValue< Encoding, Allocator >::flags_ private
Referenced by rapidjson::GenericValue< Encoding, Allocator >::GenericValue(), rapidjson::GenericValue< Encoding, Allocator >::GetBool_(), rapidjson::GenericValue< Encoding, Allocator >::GetDouble(), rapidjson::GenericValue< Encoding, Allocator >::GetInt(), rapidjson::GenericValue< Encoding, Allocator >::GetInt64(), rapidjson::GenericValue< Encoding, Allocator >::GetType(), rapidjson::GenericValue< Encoding, Allocator >::GetUint(), rapidjson::GenericValue< Encoding, Allocator >::GetUint64(), rapidjson::GenericValue< Encoding, Allocator >::IsArray(), rapidjson::GenericValue< Encoding, Allocator >::IsBool_(), rapidjson::GenericValue< Encoding, Allocator >::IsDouble(), rapidjson::GenericValue< Encoding, Allocator >::IsFalse(), rapidjson::GenericValue< Encoding, Allocator >::IsInt(), rapidjson::GenericValue< Encoding, Allocator >::IsInt64(), rapidjson::GenericValue< Encoding, Allocator >::IsNull_(), rapidjson::GenericValue< Encoding, Allocator >::IsNumber(), rapidjson::GenericValue< Encoding, Allocator >::IsObject(), rapidjson::GenericValue< Encoding, Allocator >::IsString(), rapidjson::GenericValue< Encoding, Allocator >::IsTrue(), rapidjson::GenericValue< Encoding, Allocator >::IsUint(), rapidjson::GenericValue< Encoding, Allocator >::IsUint64(), rapidjson::GenericValue< Encoding, Allocator >::operator=(), rapidjson::GenericValue< Encoding, Allocator >::RawAssign(), rapidjson::GenericValue< Encoding, Allocator >::SetArrayRaw(), rapidjson::GenericValue< Encoding, Allocator >::SetObjectRaw(), rapidjson::GenericValue< Encoding, Allocator >::SetStringRaw(), and rapidjson::GenericValue< Encoding, Allocator >::~GenericValue().
kDefaultArrayCapacity
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> const SizeType rapidjson::GenericValue< Encoding, Allocator >::kDefaultArrayCapacity = 16 static private
Referenced by rapidjson::GenericValue< Encoding, Allocator >::PushBack().
kDefaultObjectCapacity
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> const SizeType rapidjson::GenericValue< Encoding, Allocator >::kDefaultObjectCapacity = 16 static private
Referenced by rapidjson::GenericValue< Encoding, Allocator >::AddMember().
The documentation for this class was generated from the following file:
document.h