MercuryDPM: CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT > Class Template Reference
CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT > Class Template Reference
#include <comb_tip_spine_mesh.h>
Public Member Functions
CombTipSpineMesh (const unsigned int &nel, const double &alpha, const double &length, const double &height, const double &radius, const unsigned &flag, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
FiniteElement *& interface_element_pt (const unsigned long &i)
Access functions for pointers to interface elements.
unsigned long ninterface_element () const
Number of elements on interface.
FiniteElement *& bulk_element_pt (const unsigned long &i)
Access functions for pointers to elements in bulk.
unsigned long nbulk () const
Number of elements in bulk.
void flush_spine_element_and_node_storage ()
virtual void spine_node_update (SpineNode *spine_node_pt)
Public Member Functions inherited from oomph::SpineMesh
virtual ~SpineMesh ()
Destructor to clean up the memory allocated to the spines.
Spine *& spine_pt (const unsigned long &i)
Return the i-th spine in the mesh.
const Spine * spine_pt (const unsigned long &i) const
Return the i-th spine in the mesh (const version)
unsigned long nspine () const
Return the number of spines in the mesh.
void add_spine_pt (Spine *const &spine_pt)
Add a spine to the mesh.
SpineNode * node_pt (const unsigned long &n)
Return a pointer to the n-th global SpineNode.
SpineNode * element_node_pt (const unsigned long &e, const unsigned &n)
unsigned long assign_global_spine_eqn_numbers (Vector< double * > &Dof_pt)
Assign spines to Spine_pt vector of element.
void describe_spine_dofs (std::ostream &out, const std::string &current_string) const
void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_spine_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Assign time stepper to spines data.
void set_consistent_pinned_spine_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
bool does_pointer_correspond_to_spine_data (double *const &parameter_pt)
void node_update (const bool &update_all_solid_nodes=false)
void dump (std::ofstream &dump_file) const
Overload the dump function so that the spine data is dumped.
void read (std::ifstream &restart_file)
Overload the read function so that the spine data is also read.
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void setup_boundary_element_info ()
virtual void setup_boundary_element_info (std::ostream &outfile)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Protected Member Functions
void rotate_90_zeq1_xeq0 (SpineMesh *rot_mesh_pt)
void rotate_90_zeq1_yeq0 (SpineMesh *rot_mesh_pt)
virtual void build_single_layer_mesh (TimeStepper *time_stepper_pt)
void add_side_spinemesh (unsigned int bound1, MyTipMesh< ELEMENT, INTERFACE_ELEMENT > *addmesh_pt, int *addmesh_map_boundary, int total_boundaries, unsigned flag)
void change_boundaries (Mesh *pt_mesh, unsigned int oldbound, unsigned int newbound, unsigned int total_boundaries)
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes
unsigned int Nel
double Alpha
Aspect ratio, lengt, heighth and radius.
double Length
double Height
double Radius
unsigned Flag
double Xax
Axis of Symmetry.
double Yax
double Zax
Vector< FiniteElement * > Bulk_element_pt
Vector of pointers to element in the fluid layer.
Vector< FiniteElement * > Interface_element_pt
Vector of pointers to interface elements.
Protected Attributes inherited from oomph::SpineMesh
Vector< Spine * > Spine_pt
A Spine mesh contains a Vector of pointers to spines.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Detailed Description
template<class ELEMENT, class INTERFACE_ELEMENT>
class CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >
Single-layer spine mesh class derived from standard cubic 3D mesh. The mesh contains a layer of spinified fluid elements (of type ELEMENT; e.g SpineElement<CrozierRaviartElement<2>) of type INTERFACE_ELEMENT, e.g. SpineSurfaceNavierStokesInterfaceElement<ELEMENT> for 3D planar problems.
This mesh has been carefully desihned so that the numeration of the nodes on the boundaries 0 and 5 (bottom and top) coincides with the numeration of the spines
Constructor & Destructor Documentation
CombTipSpineMesh()
template<class ELEMENT , class INTERFACE_ELEMENT > CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::CombTipSpineMesh (const unsigned int & nel, const double & alpha, const double & length, const double & height, const double & radius, const unsigned & flag, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass number of elements in x-direction, number of The composed mesh is too complicated for giving xmin,xmax etc.. Nevertheless we keep nx, ny, nz making reference
Constructor for spine 3D mesh:
The mesh contains a layer of spinified fluid elements (of type ELEMENT; e.g SpineElement<CrozierRaviartElement<2>)
                                                                                                                  :
  Nel(nel), Alpha(alpha), Length(length), Height(height), Radius(radius), Flag(flag)
 {
  // We've called the "generic" constructor for the RectangularQuadMesh
  // which doesn't do much...
  // Now set up the parameters that characterise the mesh geometry
  // then call the constructor
  // Periodic?
 //  MySimpleCubicQuadMesh<ELEMENT >::Xperiodic = false;
  // Now build the mesh:
  build_single_layer_mesh(time_stepper_pt);
 }
References CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh().
Member Function Documentation
add_side_spinemesh()
template<class ELEMENT , class INTERFACE_ELEMENT > void CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::add_side_spinemesh (unsigned int bound1, MyTipMesh< ELEMENT, INTERFACE_ELEMENT > * addmesh_pt, int * addmesh_map_boundary, int total_boundaries, unsigned flag) protected
 {
  //Call the generic function
  MeshHelper::merge_spine_meshes(this,bound1,addmesh_pt,addmesh_map_boundary,
                                 total_boundaries,spine_flag);
 // add the bulk elements to the mesh
   for(unsigned i = 0; i< addmesh_pt->nbulk(); i++)
   {
     this->Bulk_element_pt.push_back(addmesh_pt->bulk_element_pt(i));
   }
    // add the interface elements to the mesh
 for(unsigned i = 0; i< addmesh_pt->ninterface_element(); i++)
   {
     this->Interface_element_pt.push_back(addmesh_pt->interface_element_pt(i));
   }
 }
References MyTipMesh< ELEMENT, INTERFACE_ELEMENT >::bulk_element_pt(), i, MyTipMesh< ELEMENT, INTERFACE_ELEMENT >::interface_element_pt(), oomph::MeshHelper::merge_spine_meshes(), MyTipMesh< ELEMENT, INTERFACE_ELEMENT >::nbulk(), and MyTipMesh< ELEMENT, INTERFACE_ELEMENT >::ninterface_element().
build_single_layer_mesh()
template<class ELEMENT , class INTERFACE_ELEMENT > void CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh (TimeStepper * time_stepper_pt) protected virtual
Helper function to actually build the single-layer spine mesh (called from various constructors)
Helper function that actually builds the single-layer spine mesh based on the parameters set in the various constructors
 {
 // Axis pf simmetry
  Xax = 0.0;
  Yax = 0.0;
  Zax = 1.0;
  unsigned n_x = Nel;
  unsigned n_y = Nel;
  unsigned n_z = Nel;
  // Build the first canion mesh:
 MyTipMesh<ELEMENT,INTERFACE_ELEMENT >* mesh1_pt = new MyTipMesh<ELEMENT,INTERFACE_ELEMENT > (n_x,n_y,n_z,0.0,1.0,-1.0,0.0,0.0,1.0,Radius,0,time_stepper_pt);
  mesh1_pt->node_update();
  //mesh1_pt->output("tip1.dat");
 // We copy this mesh to our problem mesh
 // add the nodes to the mesh
 //we reasign the spine_nodes to point to the ptoblem mesh
  for(unsigned i = 0; i< mesh1_pt->nnode(); i++)
   {
    //Set spine update flag equal to Flag for the nodes of this function
     mesh1_pt->node_pt(i)->node_update_fct_id() = Flag;
     mesh1_pt->node_pt(i)->spine_mesh_pt() = this;
     this->add_node_pt(mesh1_pt->node_pt(i));
   }
    // add the bulk elements to the mesh
  for(unsigned i = 0; i< mesh1_pt->nbulk(); i++)
   {
     Bulk_element_pt.push_back(mesh1_pt->bulk_element_pt(i));
   }
    // add the interface elements to the mesh
 for(unsigned i = 0; i< mesh1_pt->ninterface_element(); i++)
   {
     Interface_element_pt.push_back(mesh1_pt->interface_element_pt(i));
   }
 // add all the elements to the mesh
 for(unsigned i = 0; i< mesh1_pt->nelement(); i++)
   {
     Element_pt.push_back(mesh1_pt->element_pt(i));
   }
    // add the spines  to the mesh
 for(unsigned i = 0; i< mesh1_pt->nspine(); i++)
   {
     Spine_pt.push_back(mesh1_pt->spine_pt(i));
   }
 //add the boundaries
  set_nboundary( mesh1_pt->nboundary());
 for(unsigned b =0; b< mesh1_pt->nboundary(); b++)
   {
    for(unsigned i = 0; i<mesh1_pt->nboundary_node(b); i++)
     {
      // We remove the node from the old boundary mesh ( This is not necessary and it is mainly wrotten for avoiding the warning message)
      Node* node_pt =  mesh1_pt->boundary_node_pt(b,i );
      node_pt->remove_from_boundary(b);
      this->add_boundary_node( b , node_pt);
     }
   }
 //We create a second mesh
  MyTipMesh<ELEMENT,INTERFACE_ELEMENT >* mesh2_pt = new MyTipMesh<ELEMENT,INTERFACE_ELEMENT > (n_x,n_y,n_z,0.0,1.0,-1.0,0.0,0.0,1.0,Radius,1,time_stepper_pt);
  //mesh2_pt->output("tip2.dat");
 //Resignation pointer for the boundary conditions of the second mesh
   int addmesh_map_boundary[6];
   for(unsigned int i =0;i<6;i++)
    {
     addmesh_map_boundary[i] = i;
    }
    addmesh_map_boundary[2] = 6;
    addmesh_map_boundary[0] = 2;
    addmesh_map_boundary[4] = -1;
   add_side_spinemesh(2, mesh2_pt ,addmesh_map_boundary, 7,Flag);
 //  cout<<"After adding 2 the mesh has "<<nbulk()<<" bulk elements"<<endl;
 //We create a third mesh
  MyTipMesh<ELEMENT,INTERFACE_ELEMENT >* mesh3_pt = new MyTipMesh<ELEMENT,INTERFACE_ELEMENT > (n_x,n_y,n_z,0.0,1.0,-1.0,0.0,0.0,1.0,Radius,2,time_stepper_pt);
  //mesh3_pt->output("tip3.dat");
  change_boundaries( mesh3_pt,2,3,6);
  //std::cout<<"After change the boundary 2 have "
  //        <<mesh3_pt->nboundary_node(2)<<" nodes"<<std::endl;
 //Resignation pointer for the boundary conditions of the third mesh
   for(unsigned int i =0;i<6;i++)
    {
     addmesh_map_boundary[i] = i;
    }
    addmesh_map_boundary[1] = 7;
    addmesh_map_boundary[0] = 1;
    addmesh_map_boundary[3] = -1;
   add_side_spinemesh(1, mesh3_pt ,addmesh_map_boundary, 8,Flag);
 // cout<<"After adding 3 the mesh has "<<nbulk()<<" bulk elements"<<endl;
 //We create a fourth  mesh
  MyTipMesh<ELEMENT,INTERFACE_ELEMENT >* mesh4_pt = new MyTipMesh<ELEMENT,INTERFACE_ELEMENT > (n_x,n_y,n_z,0.0,1.0,-1.0,0.0,0.0,1.0,Radius,0,time_stepper_pt);
 // We miror the mesh twice
   rotate_90_zeq1_xeq0(mesh4_pt);
   // mesh4_pt->output("tip4.dat");
 //Resignation pointer for the boundary conditions of the fifth mesh
   for(unsigned int i =0;i<6;i++)
    {
     addmesh_map_boundary[i] = i;
    }
  addmesh_map_boundary[0] = 2;
    addmesh_map_boundary[1] =7 ;
    addmesh_map_boundary[2] = 6;
   addmesh_map_boundary[4] = -1;
 //cout<<"Before adding 4 the mesh has "<<nnode()<<" nodes "<<endl;
  add_side_spinemesh(6, mesh4_pt ,addmesh_map_boundary, 8,Flag);
 //cout<<"After adding 4 the mesh has "<<nnode()<<" nodes "<<endl;
 //We create a fourth mesh
   MyTipMesh<ELEMENT,INTERFACE_ELEMENT >* mesh5_pt = new MyTipMesh<ELEMENT,INTERFACE_ELEMENT > (n_x,n_y,n_z,0.0,1.0,-1.0,0.0,0.0,1.0,Radius,0,time_stepper_pt);
 // We miror the mesh twice
    rotate_90_zeq1_yeq0(mesh5_pt);
    //mesh5_pt->output("tip5.dat");
   change_boundaries( mesh5_pt,2,3,6);
 //Resignation pointer for the boundary conditions of the fourth mesh
   for(unsigned int i =0;i<6;i++)
    {
     addmesh_map_boundary[i] = i;
    }
  addmesh_map_boundary[0] = 1;
    addmesh_map_boundary[1] = 6;
   addmesh_map_boundary[3] = -1;
 // Add to the general mesh
  add_side_spinemesh(7, mesh5_pt ,addmesh_map_boundary, 8,Flag);
 // cout<<"After adding 5 in  the tip mesh the boundary 1 has"<<this->nboundary_node(1)<<"nodes"<<endl;
 // cout<<"After adding 5 the mesh has "<<nbulk()<<" bulk elements"<<endl;
 // We create the last mesh
  MyTipMesh<ELEMENT,INTERFACE_ELEMENT >* mesh6_pt = new MyTipMesh<ELEMENT,INTERFACE_ELEMENT > (n_x,n_y,n_z,0.0,1.0,-1.0,0.0,0.0,1.0,Radius,1,time_stepper_pt);
    rotate_90_zeq1_xeq0(mesh6_pt);
    // mesh6_pt->output("tip6.dat");
  change_boundaries( mesh6_pt,4,1,6);
   for(unsigned int i =0;i<6;i++)
    {
     addmesh_map_boundary[i] = i;
    }
    addmesh_map_boundary[0] = 6;
    addmesh_map_boundary[1] = -1;
    addmesh_map_boundary[2] = 4;
 // Add to the general mesh
   add_side_spinemesh(6, mesh6_pt ,addmesh_map_boundary, 7,Flag);
   std::cout<<"The tip mesh consists of  "
            <<nbulk()<<" bulk elements and "<<ninterface_element()
            << " interface elements."<<std::endl;
 // At the end we destroy the block meshes in two steps
 // 1. We disconect the meshesh from the nodes and elements (if not we delete them at the time we delete the meshes)
   mesh1_pt->flush_spine_element_and_node_storage();
   mesh2_pt->flush_spine_element_and_node_storage();
   mesh3_pt->flush_spine_element_and_node_storage();
   mesh4_pt->flush_spine_element_and_node_storage();
   mesh5_pt->flush_spine_element_and_node_storage();
   mesh6_pt->flush_spine_element_and_node_storage();
 //2. Simply delete (this function can give a segmentation fault error when there are spines still attached to the old update functions written in the constructor)
   delete mesh1_pt;
   delete mesh2_pt;
   delete mesh3_pt;
   delete mesh4_pt;
   delete mesh5_pt;
   delete mesh6_pt;
 // until now we have just worked with a square channel
 // introduce the aspect ratio and different lenght (there is a factor 2 becasue 1 = halve height= b/2)
   int ncount;
   ncount = this->nnode();
   for(int i = 0; i< ncount; i++)
    {
      Node* node_pt =  this->node_pt(i);
      node_pt->x(0) =  node_pt->x(0) * Alpha/2;
      node_pt->x(1) =  node_pt->x(1) * Length;
      node_pt->x(2) =   node_pt->x(2) * Height/2;
    }
 // Update also the origin of the spines
  unsigned long nspines = this->nspine();
  for(unsigned long i = 0; i<nspines;i++)
     {
       Spine* spine_pt = this->spine_pt(i);
       double x_spine = spine_pt->geom_parameter(0);
       double y_spine = spine_pt->geom_parameter(1);
       double z_spine = spine_pt->geom_parameter(2);
       spine_pt->geom_parameter(0) = x_spine *Alpha/2.0;
       spine_pt->geom_parameter(1) = y_spine * Length;
       spine_pt->geom_parameter(2) = z_spine * Height/2.0;
     }
 // Update the axis of simmetry
   Zax = Zax *  Height/2.0;
 // Update the spines heigth according to the new geometry
   ncount = this->nboundary_node(5);
   for(int i = 0; i< ncount; i++)
    {
      SpineNode* spine_node_pt =  dynamic_cast<SpineNode*>(this->boundary_node_pt(5,i));
      Spine* spine_pt = spine_node_pt->spine_pt();
       double x_spine = spine_pt->geom_parameter(0);
       double y_spine = spine_pt->geom_parameter(1);
       double z_spine = spine_pt->geom_parameter(2);
       double  dorg = sqrt( (spine_node_pt->x(0) -  x_spine )*(spine_node_pt->x(0) -  x_spine )+
                  (spine_node_pt->x(1) -  y_spine)*(spine_node_pt->x(1) -  y_spine)+
                (spine_node_pt->x(2) -  z_spine)*(spine_node_pt->x(2) -  z_spine) );
      spine_node_pt->h() = dorg;
    }
 }
References TanhSolnForAdvectionDiffusion::Alpha, b, oomph::Mesh::boundary_node_pt(), MyTipMesh< ELEMENT, INTERFACE_ELEMENT >::bulk_element_pt(), oomph::Mesh::element_pt(), oomph::PressureAdvectionDiffusionValidation::Flag, MyTipMesh< ELEMENT, INTERFACE_ELEMENT >::flush_spine_element_and_node_storage(), oomph::Spine::geom_parameter(), oomph::SpineNode::h(), GlobalParameters::Height, i, MyTipMesh< ELEMENT, INTERFACE_ELEMENT >::interface_element_pt(), Global_Physical_Variables::Length, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_node(), MyTipMesh< ELEMENT, INTERFACE_ELEMENT >::nbulk(), oomph::Mesh::nelement(), MyTipMesh< ELEMENT, INTERFACE_ELEMENT >::ninterface_element(), oomph::Mesh::nnode(), oomph::SpineMesh::node_pt(), oomph::SpineMesh::node_update(), oomph::SpineNode::node_update_fct_id(), oomph::SpineMesh::nspine(), Global_Physical_Variables::Radius, oomph::Node::remove_from_boundary(), oomph::SpineNode::spine_mesh_pt(), oomph::SpineNode::spine_pt(), oomph::SpineMesh::spine_pt(), sqrt(), and oomph::Node::x().
Referenced by CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::CombTipSpineMesh().
bulk_element_pt()
template<class ELEMENT , class INTERFACE_ELEMENT > FiniteElement* & CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::bulk_element_pt (const unsigned long & i) inline
Access functions for pointers to elements in bulk.
   {return Bulk_element_pt[i];}
References i.
Referenced by STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::add_side_spinemesh().
change_boundaries()
template<class ELEMENT , class INTERFACE_ELEMENT > void CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::change_boundaries (Mesh * pt_mesh, unsigned int oldbound, unsigned int newbound, unsigned int total_boundaries) protected
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
 {
  for(unsigned int i = 0; i<pt_mesh->nboundary_node(oldbound);i++)
   {
    if( !(pt_mesh->boundary_node_pt(oldbound,i)->is_on_boundary(newbound)) )     //Do not add the nodes which were before on the boundary
      pt_mesh->add_boundary_node(newbound, pt_mesh->boundary_node_pt(oldbound,i) );
   }
    pt_mesh->remove_boundary_nodes(oldbound);
    pt_mesh->set_nboundary(total_boundaries);
 }
References oomph::Mesh::add_boundary_node(), oomph::Mesh::boundary_node_pt(), i, oomph::Node::is_on_boundary(), oomph::Mesh::nboundary_node(), oomph::Mesh::remove_boundary_nodes(), and oomph::Mesh::set_nboundary().
flush_spine_element_and_node_storage()
template<class ELEMENT , class INTERFACE_ELEMENT > void CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::flush_spine_element_and_node_storage () inline
   {
     //Clear vectors of pointers to the nodes and elements
     Node_pt.clear();
     Bulk_element_pt.clear();
     Interface_element_pt.clear();
     Element_pt.clear();
     Spine_pt.clear();
   }
Referenced by STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh().
interface_element_pt()
template<class ELEMENT , class INTERFACE_ELEMENT > FiniteElement* & CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::interface_element_pt (const unsigned long & i) inline
Access functions for pointers to interface elements.
   {return Interface_element_pt[i];}
References i.
Referenced by STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::add_side_spinemesh().
nbulk()
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned long CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::nbulk () const inline
Number of elements in bulk.
 {return Bulk_element_pt.size();}
Referenced by STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::add_side_spinemesh().
ninterface_element()
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned long CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::ninterface_element () const inline
Number of elements on interface.
 {return Interface_element_pt.size();}
Referenced by STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::add_side_spinemesh().
rotate_90_zeq1_xeq0()
template<class ELEMENT , class INTERFACE_ELEMENT > void CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::rotate_90_zeq1_xeq0 (SpineMesh * rot_mesh_pt) inline protected
   {
    unsigned long nnode = rot_mesh_pt->nnode();
    for(unsigned long i = 0; i<nnode;i++)
     {
       Node* node_pt = rot_mesh_pt->node_pt(i);
       double x_node = node_pt->x(0);
       double z_node = node_pt->x(2);
       node_pt->x(0) = 1.0 - z_node;
       node_pt->x(2) = 1.0 + x_node;
     }
 // We rotate as well the geometric parameters which were originally set as the coordinate of the node at the origin of the spine
  unsigned long nspines = rot_mesh_pt->nspine();
   for(unsigned long i = 0; i<nspines;i++)
     {
       Spine* spine_pt = rot_mesh_pt->spine_pt(i);
       double x_spine = spine_pt->geom_parameter(0);
       double z_spine = spine_pt->geom_parameter(2);
       spine_pt->geom_parameter(0) = 1.0 - z_spine;
       spine_pt->geom_parameter(2) = 1.0 + x_spine;
     }
    //we update again the nodes
     rot_mesh_pt->node_update();
   }
References oomph::Spine::geom_parameter(), i, oomph::Mesh::nnode(), oomph::SpineMesh::node_pt(), oomph::SpineMesh::node_update(), oomph::SpineMesh::nspine(), oomph::SpineMesh::spine_pt(), and oomph::Node::x().
rotate_90_zeq1_yeq0()
template<class ELEMENT , class INTERFACE_ELEMENT > void CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::rotate_90_zeq1_yeq0 (SpineMesh * rot_mesh_pt) inline protected
   {
    unsigned long nnode = rot_mesh_pt->nnode();
    for(unsigned long i = 0; i<nnode;i++)
     {
       Node* node_pt = rot_mesh_pt->node_pt(i);
       double y_node = node_pt->x(1);
       double z_node = node_pt->x(2);
       node_pt->x(1) =  -1.0 + z_node;
       node_pt->x(2) = 1.0 - y_node;
     }
   // We rotate as well the geometric parameters which were originally set as the coordinate of the node at the origin of the spine
  unsigned long nspines = rot_mesh_pt->nspine();
  for(unsigned long i = 0; i<nspines;i++)
     {
       Spine* spine_pt = rot_mesh_pt->spine_pt(i);
       double y_spine = spine_pt->geom_parameter(1);
       double z_spine = spine_pt->geom_parameter(2);
       spine_pt->geom_parameter(1) = -1.0 + z_spine;
       spine_pt->geom_parameter(2) = 1.0 - y_spine;
     }
    //we update again the nodes
     rot_mesh_pt->node_update();
   }
References oomph::Spine::geom_parameter(), i, oomph::Mesh::nnode(), oomph::SpineMesh::node_pt(), oomph::SpineMesh::node_update(), oomph::SpineMesh::nspine(), oomph::SpineMesh::spine_pt(), and oomph::Node::x().
spine_node_update()
template<class ELEMENT , class INTERFACE_ELEMENT > virtual void CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update (SpineNode * spine_node_pt) inline virtual
General node update function implements pure virtual function defined in SpineMesh base class and performs specific node update actions: along vertical spines
Implements oomph::SpineMesh.
   {
  //Get fraction along the spine
    double W = spine_node_pt->fraction();
    //Get spine height
    double H = spine_node_pt->h();
    //Get the position of the node at the origin
    // SpineNode* origin_pt = dynamic_cast<SpineNode*>(spine_node_pt->spine_pt()->geom_data_pt(0));
    Vector<double> origin_pt(3);
    origin_pt[0] = spine_node_pt->spine_pt()->geom_parameter(0);
    origin_pt[1] = spine_node_pt->spine_pt()->geom_parameter(1);
    origin_pt[2] = spine_node_pt->spine_pt()->geom_parameter(2);
    //set scale norm vector
    double norm = sqrt( (Xax -  origin_pt[0] ) *  (Xax -  origin_pt[0] )+ (Yax -  origin_pt[1] ) *  (Yax -  origin_pt[1] ) +
                        (Zax -  origin_pt[2] ) *  (Zax -  origin_pt[2])  );
    //Set the x coordinate
    spine_node_pt->x(0) = origin_pt[0] + H*W* (Xax -  origin_pt[0] )/norm;
    //Set the y coordinate
    spine_node_pt->x(1) = origin_pt[1] + H*W* (Yax -  origin_pt[1] )/norm;
    //Set the value of z
    spine_node_pt->x(2) = origin_pt[2] + H*W* (Zax -  origin_pt[2] )/norm;
   }
References oomph::SpineNode::fraction(), oomph::Spine::geom_parameter(), H, oomph::SpineNode::h(), oomph::SpineNode::spine_pt(), sqrt(), oomph::QuadTreeNames::W, and oomph::Node::x().
Member Data Documentation
Alpha
template<class ELEMENT , class INTERFACE_ELEMENT > double CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Alpha protected
Aspect ratio, lengt, heighth and radius.
Bulk_element_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Vector<FiniteElement *> CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Bulk_element_pt protected
Vector of pointers to element in the fluid layer.
Flag
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Flag protected
Height
template<class ELEMENT , class INTERFACE_ELEMENT > double CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Height protected
Interface_element_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Vector<FiniteElement *> CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Interface_element_pt protected
Vector of pointers to interface elements.
Length
template<class ELEMENT , class INTERFACE_ELEMENT > double CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Length protected
Nel
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned int CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Nel protected
Radius
template<class ELEMENT , class INTERFACE_ELEMENT > double CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Radius protected
Xax
template<class ELEMENT , class INTERFACE_ELEMENT > double CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Xax protected
Axis of Symmetry.
Yax
template<class ELEMENT , class INTERFACE_ELEMENT > double CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Yax protected
Zax
template<class ELEMENT , class INTERFACE_ELEMENT > double CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Zax protected
The documentation for this class was generated from the following file:
comb_tip_spine_mesh.h