MercuryDPM: Eigen::BlockVectorView< BlockSparseMatrixT, VectorType > Class Template Reference
Eigen::BlockVectorView< BlockSparseMatrixT, VectorType > Class Template Reference
#include <BlockSparseMatrix.h>
Public Types
enum { BlockSize = BlockSparseMatrixT::BlockSize , ColsAtCompileTime = VectorType::ColsAtCompileTime , RowsAtCompileTime = VectorType::RowsAtCompileTime , Flags = VectorType::Flags }
typedef Ref< const Matrix< typename BlockSparseMatrixT::Scalar,(RowsAtCompileTime==1) ? 1 :BlockSize,(ColsAtCompileTime==1) ? 1 :BlockSize > > Scalar
typedef BlockSparseMatrixT::Index Index
Public Member Functions
BlockVectorView (const BlockSparseMatrixT &spblockmat, const VectorType &vec)
Index cols () const
Index size () const
Scalar coeff (Index bi) const
Scalar coeff (Index bi, Index j) const
Protected Attributes
const BlockSparseMatrixT & m_spblockmat
const VectorType & m_vec
Member Typedef Documentation
Index
template<typename BlockSparseMatrixT , typename VectorType > typedef BlockSparseMatrixT::Index Eigen::BlockVectorView< BlockSparseMatrixT, VectorType >::Index
Scalar
template<typename BlockSparseMatrixT , typename VectorType > typedef Ref<const Matrix<typename BlockSparseMatrixT::Scalar, (RowsAtCompileTime == 1) ? 1 : BlockSize, (ColsAtCompileTime == 1) ? 1 : BlockSize> > Eigen::BlockVectorView< BlockSparseMatrixT, VectorType >::Scalar
Member Enumeration Documentation
anonymous enum
template<typename BlockSparseMatrixT , typename VectorType > anonymous enum
Enumerator
BlockSize
ColsAtCompileTime
RowsAtCompileTime
Flags
        {
     BlockSize = BlockSparseMatrixT::BlockSize,
     ColsAtCompileTime = VectorType::ColsAtCompileTime,
     RowsAtCompileTime = VectorType::RowsAtCompileTime,
     Flags = VectorType::Flags
   };
Constructor & Destructor Documentation
BlockVectorView()
template<typename BlockSparseMatrixT , typename VectorType > Eigen::BlockVectorView< BlockSparseMatrixT, VectorType >::BlockVectorView (const BlockSparseMatrixT & spblockmat, const VectorType & vec) inline
 : m_spblockmat(spblockmat), m_vec(vec) {}
Member Function Documentation
coeff() [1/2]
template<typename BlockSparseMatrixT , typename VectorType > Scalar Eigen::BlockVectorView< BlockSparseMatrixT, VectorType >::coeff (Index bi) const inline
{
     Index startRow = m_spblockmat.blockRowsIndex(bi);
     Index rowSize = m_spblockmat.blockRowsIndex(bi + 1) - startRow;
     return m_vec.middleRows(startRow, rowSize);
   }
References Eigen::BlockVectorView< BlockSparseMatrixT, VectorType >::m_spblockmat, and Eigen::BlockVectorView< BlockSparseMatrixT, VectorType >::m_vec.
coeff() [2/2]
template<typename BlockSparseMatrixT , typename VectorType > Scalar Eigen::BlockVectorView< BlockSparseMatrixT, VectorType >::coeff (Index bi, Index j) const inline
{
     Index startRow = m_spblockmat.blockRowsIndex(bi);
     Index rowSize = m_spblockmat.blockRowsIndex(bi + 1) - startRow;
     return m_vec.block(startRow, j, rowSize, 1);
   }
References j, Eigen::BlockVectorView< BlockSparseMatrixT, VectorType >::m_spblockmat, and Eigen::BlockVectorView< BlockSparseMatrixT, VectorType >::m_vec.
cols()
template<typename BlockSparseMatrixT , typename VectorType > Index Eigen::BlockVectorView< BlockSparseMatrixT, VectorType >::cols () const inline
 { return m_vec.cols(); }
References Eigen::BlockVectorView< BlockSparseMatrixT, VectorType >::m_vec.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
size()
template<typename BlockSparseMatrixT , typename VectorType > Index Eigen::BlockVectorView< BlockSparseMatrixT, VectorType >::size () const inline
 { return m_spblockmat.blockRows(); }
References Eigen::BlockVectorView< BlockSparseMatrixT, VectorType >::m_spblockmat.
Member Data Documentation
m_spblockmat
template<typename BlockSparseMatrixT , typename VectorType > const BlockSparseMatrixT& Eigen::BlockVectorView< BlockSparseMatrixT, VectorType >::m_spblockmat protected
Referenced by Eigen::BlockVectorView< BlockSparseMatrixT, VectorType >::coeff(), and Eigen::BlockVectorView< BlockSparseMatrixT, VectorType >::size().
m_vec
template<typename BlockSparseMatrixT , typename VectorType > const VectorType& Eigen::BlockVectorView< BlockSparseMatrixT, VectorType >::m_vec protected
Referenced by Eigen::BlockVectorView< BlockSparseMatrixT, VectorType >::coeff(), and Eigen::BlockVectorView< BlockSparseMatrixT, VectorType >::cols().
The documentation for this class was generated from the following file:
BlockSparseMatrix.h