MercuryDPM: DensitySizeSeg_Belt_WarreJan_25_75.cpp File Reference
DensitySizeSeg_Belt_WarreJan_25_75.cpp File Reference
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cmath>
#include "Chute.h"
#include "Boundaries/PeriodicBoundary.h"
#include "Walls/InfiniteWall.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <Species/LinearViscoelasticFrictionSpecies.h>
Classes
class SegregationPeriodic
This class does segregation problems in a periodic chute.
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
Todo:
TW:should be lightest particle, but computeMass has to be automated first
 {
     SegregationPeriodic problem;
     //problem.setParticlesWriteVTK(true);
     if (argc < 5)
     {
         logger(ERROR,"Wrong amount of command line inputs; Use ./fileName -sr ... -dr ...");
     }
     Mdouble sizeRatio = helpers::readFromCommandLine(argc,argv,"-sr",1.0);
     Mdouble densityRatio = helpers::readFromCommandLine(argc,argv,"-dr",1.0);
     problem.setSizeRatio(sizeRatio);
     problem.setDensityRatio(densityRatio);
     std::stringstream dirNameBase;
     std::string directoryName = "Segregation_";
     dirNameBase << directoryName << "sizeRatio_" << problem.getSizeRatio() << "_densityRatio_" << problem.getDensityRatio();
     std::stringstream fileNameStream;
     std::string nameBase = "Segregation_";
     fileNameStream << nameBase << "sizeRatio_" << problem.getSizeRatio() << "_densityRatio_" << problem.getDensityRatio();
     std::stringstream saveTo;
     saveTo << dirNameBase.str() << "/" << fileNameStream.str();
     std::stringstream com;
     com << "mkdir " << dirNameBase.str();
     int status = system(com.str().c_str());
     problem.setName(saveTo.str());
     // Problem parameters, name tmax and two types of particles
     //This should be set to 100 for full problems.
     problem.setTimeMax(1);
     //problem.speciesHandler.copyAndAddObject(problem.speciesHandler.getObject(0));
     //problem.speciesHandler.copyAndAddObject(problem.speciesHandler.getObject(0));
     // Chute properties
     problem.setFixedParticleRadius(0.5);
     problem.setRoughBottomType(MULTILAYER);
     problem.setChuteAngleAndMagnitudeOfGravity(26.0, 1.0);
     problem.setChuteLength(20);
     problem.setChuteWidth(10);
     problem.setZMax(70);
     problem.setMaxFailed(6);
     problem.makeChutePeriodic();
     //solve
     //std::cout << "Maximum allowed speed of particles: " << problem.particleHandler.getSmallestParticle()->calculateMaximumVelocity() << std::endl; // speed allowed before particles move through each other!
     problem.setTimeStep(5.e-3 / 50.0);//initially it was auto-set
     //This is based on the fact in general you get too much data, so prob at worst you want to turn it into a 20 at 60fps (which is its self overkill)
     problem.setSaveCount(helpers::getSaveCountFromNumberOfSavesAndTimeMaxAndTimeStep(20*60, problem.getTimeMax(), problem.getTimeStep()));
     //problem.setSaveCount(helpers::getSaveCountFromNumberOfSavesAndTimeMaxAndTimeStep(20*60,getTimeMax(),getTimeStep()));
     //problem.setSaveCount(1);
     logger(INFO, "dt=%", problem.getTimeStep());
     //problem.autoNumber();
     //This set to colouring based of size and small vectors
     problem.setXBallsColourMode(7);
     problem.setXBallsVectorScale(1);
     problem.setXBallsAdditionalArguments("-v0 -solidf");
     //solves the problems
     problem.solve();
     //Make sure the restart data is upto date at the end
     problem.writeRestartFile();
 }
References ERROR, helpers::getSaveCountFromNumberOfSavesAndTimeMaxAndTimeStep(), INFO, logger, MULTILAYER, problem, helpers::readFromCommandLine(), and oomph::Global_string_for_annotation::string().