MercuryDPM: Eigen::internal::blas_traits< XprType > Struct Template Reference
Eigen::internal::blas_traits< XprType > Struct Template Reference
#include <BlasUtil.h>
Public Types
enum {
IsComplex = NumTraits<Scalar>::IsComplex , IsTransposed = false , NeedToConjugate = false , HasUsableDirectAccess ,
HasScalarFactor = false
}
typedef traits< XprType >::Scalar Scalar
typedef const XprType & ExtractType
typedef XprType ExtractType_
typedef std::conditional_t< bool(HasUsableDirectAccess), ExtractType, typename ExtractType_::PlainObject > DirectLinearAccessType
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_DEVICE_FUNC ExtractType extract (const XprType &x)
static EIGEN_DEVICE_FUNC EIGEN_DEVICE_FUNC const Scalar extractScalarFactor (const XprType &)
Member Typedef Documentation
DirectLinearAccessType
template<typename XprType > typedef std::conditional_t<bool(HasUsableDirectAccess), ExtractType, typename ExtractType_::PlainObject> Eigen::internal::blas_traits< XprType >::DirectLinearAccessType
ExtractType
template<typename XprType > typedef const XprType& Eigen::internal::blas_traits< XprType >::ExtractType
ExtractType_
template<typename XprType > typedef XprType Eigen::internal::blas_traits< XprType >::ExtractType_
Scalar
template<typename XprType > typedef traits<XprType>::Scalar Eigen::internal::blas_traits< XprType >::Scalar
Member Enumeration Documentation
anonymous enum
template<typename XprType > anonymous enum
Enumerator
IsComplex
IsTransposed
NeedToConjugate
HasUsableDirectAccess
HasScalarFactor
        {
     IsComplex = NumTraits<Scalar>::IsComplex,
     IsTransposed = false,
     NeedToConjugate = false,
     HasUsableDirectAccess =
         ((int(XprType::Flags) & DirectAccessBit) &&
          (bool(XprType::IsVectorAtCompileTime) || int(inner_stride_at_compile_time<XprType>::ret) == 1))
             ? 1
             : 0,
     HasScalarFactor = false
   };
Member Function Documentation
extract()
template<typename XprType > static EIGEN_DEVICE_FUNC EIGEN_DEVICE_FUNC ExtractType Eigen::internal::blas_traits< XprType >::extract (const XprType & x) inline static
 { return x; }
References plotDoE::x.
Referenced by Eigen::internal::extract_data_selector< T, HasUsableDirectAccess >::run().
extractScalarFactor()
template<typename XprType > static EIGEN_DEVICE_FUNC EIGEN_DEVICE_FUNC const Scalar Eigen::internal::blas_traits< XprType >::extractScalarFactor (const XprType &) inline static
{
     return Scalar(1);
   }
Referenced by Eigen::internal::combine_scalar_factors_impl< ResScalar, Lhs, Rhs >::run(), and Eigen::internal::combine_scalar_factors_impl< bool, Lhs, Rhs >::run().
The documentation for this struct was generated from the following file:
BlasUtil.h