MercuryDPM: Eigen::internal::accurate_log2< float > Struct Reference
Eigen::internal::accurate_log2< float > Struct Reference
#include <GenericPacketMathFunctions.h>
Public Member Functions
template<typename Packet >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void operator() (const Packet &z, Packet &log2_x_hi, Packet &log2_x_lo)
Member Function Documentation
operator()()
template<typename Packet > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::accurate_log2< float >::operator() (const Packet & z, Packet & log2_x_hi, Packet & log2_x_lo) inline
{
     // Split the two lowest order constant coefficient into double-word representation.
     constexpr double kC0 = 1.442695041742110273474963832995854318141937255859375e+00;
     constexpr float kC0_hi = static_cast<float>(kC0);
     constexpr float kC0_lo = static_cast<float>(kC0 - static_cast<double>(kC0_hi));
     const Packet c0_hi = pset1<Packet>(kC0_hi);
     const Packet c0_lo = pset1<Packet>(kC0_lo);
     constexpr double kC1 = -7.2134751588268664068692714863573201000690460205078125e-01;
     constexpr float kC1_hi = static_cast<float>(kC1);
     constexpr float kC1_lo = static_cast<float>(kC1 - static_cast<double>(kC1_hi));
     const Packet c1_hi = pset1<Packet>(kC1_hi);
     const Packet c1_lo = pset1<Packet>(kC1_lo);
     constexpr float c[] = {
         9.7010828554630279541015625e-02,  -1.6896486282348632812500000e-01, 1.7200836539268493652343750e-01,
         -1.7892272770404815673828125e-01, 2.0505344867706298828125000e-01,  -2.4046677350997924804687500e-01,
         2.8857553005218505859375000e-01,  -3.6067414283752441406250000e-01, 4.8089790344238281250000000e-01};
     // Evaluate the higher order terms in the polynomial using
     // standard arithmetic.
     const Packet one = pset1<Packet>(1.0f);
     const Packet x = psub(z, one);
     Packet p = ppolevl<Packet, 8>::run(x, c);
     // Evaluate the final two step in Horner's rule using double-word
     // arithmetic.
     Packet p_hi, p_lo;
     twoprod(x, p, p_hi, p_lo);
     fast_twosum(c1_hi, c1_lo, p_hi, p_lo, p_hi, p_lo);
     twoprod(p_hi, p_lo, x, p_hi, p_lo);
     fast_twosum(c0_hi, c0_lo, p_hi, p_lo, p_hi, p_lo);
     // Multiply by x to recover log2(z).
     twoprod(p_hi, p_lo, x, log2_x_hi, log2_x_lo);
   }
References calibrate::c, Eigen::internal::fast_twosum(), p, Eigen::internal::psub(), Eigen::internal::ppolevl< Packet, N >::run(), Eigen::internal::twoprod(), and plotDoE::x.
The documentation for this struct was generated from the following file:
GenericPacketMathFunctions.h