MercuryDPM: SinterBed1SelfTest.cpp File Reference
SinterBed1SelfTest.cpp File Reference
#include "Mercury3D.h"
#include <Species/SinterFrictionSpecies.h>
#include <Walls/InfiniteWall.h>
#include <Walls/AxisymmetricIntersectionOfWalls.h>
#include <iomanip>
#include <cassert>
Classes
class Sintering
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     Sintering s;
     s.setSaveCount(100);
     s.fStatFile.setSaveCount(300);
     Mdouble sinterRate = readFromFile("in","sinterRate",0.25*0.25*mathsFunc::square(0.3));
     s.species->setSinterRate(sinterRate);
     Mdouble sinterTime = readFromFile("in","sinterTime",24);
     s.setTimeMax(sinterTime);
     s.restartFile.setSaveCount(s.getTimeMax()/s.getTimeStep()/5.0+1.0);
     s.fStatFile.setFileType(FileType::ONE_FILE);
     s.restartFile.setFileType(FileType::MULTIPLE_FILES); // so we can restart from different times
     writeToFile("SinterBed1.gnu",
                           "set xlabel 't'\n"
                           "set ylabel 'x/d'\n"
                           "p '"+s.getName()+".ene' u 1:2 w lp, 0.075*x**0.5\n"
     );
     writeToFile("SinterBed1b.gnu",
                           "set xlabel 't'\n"
                           "set ylabel 'x/d'\n"
                           "p '" + s.getName() + ".fstat' u 1:(sqrt($7/" +
                                   toString(2.0 * s.particleHandler.getMeanRadius()) + ")), 0.3*x**0.5\n"
     );
     s.species->setSinterType(SINTERTYPE::CONSTANT_RATE);
     s.solve();
     logger(INFO, "Run with ./SinterBed1 >out; the execute 'gnuplot SinterBed1.gnu' to view output");
     //if I add friction (10,1), it creates ruptures
     return 0;
 }
References CONSTANT_RATE, INFO, logger, MULTIPLE_FILES, ONE_FILE, helpers::readFromFile(), s, mathsFunc::square(), helpers::toString(), and helpers::writeToFile().