MercuryDPM: Eigen::SparseMatrixBase< Derived > Class Template Reference
Eigen::SparseMatrixBase< Derived > Class Template Reference
Sparse linear algebra » Reference » SparseCore_Module
Base class of any sparse matrices or sparse expressions.
#include <SparseMatrixBase.h>
Classes
struct ConstSelfAdjointViewReturnType
struct CwiseProductDenseReturnType
struct SelfAdjointViewReturnType
Public Types
enum {
RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime , ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime , SizeAtCompileTime = (internal::size_of_xpr_at_compile_time<Derived>::ret) , MaxRowsAtCompileTime = RowsAtCompileTime ,
MaxColsAtCompileTime = ColsAtCompileTime , MaxSizeAtCompileTime = internal::size_at_compile_time(MaxRowsAtCompileTime, MaxColsAtCompileTime) , IsVectorAtCompileTime = RowsAtCompileTime == 1 || ColsAtCompileTime == 1 , NumDimensions ,
Flags = internal::traits<Derived>::Flags , IsRowMajor = Flags & RowMajorBit ? 1 : 0 , InnerSizeAtCompileTime , HasDirectAccess_ = (int(Flags) & DirectAccessBit) ? 1 : 0
}
typedef internal::traits< Derived >::Scalar Scalar
typedef Scalar value_type
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::StorageIndex StorageIndex
typedef internal::add_const_on_value_type_if_arithmetic< typename internal::packet_traits< Scalar >::type >::type PacketReturnType
typedef SparseMatrixBase StorageBaseType
typedef Matrix< StorageIndex, Dynamic, 1 > IndexVector
typedef Matrix< Scalar, Dynamic, 1 > ScalarVector
typedef std::conditional_t< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, Eigen::Transpose< const Derived > >, Transpose< const Derived > > AdjointReturnType
typedef Transpose< Derived > TransposeReturnType
typedef Transpose< const Derived > ConstTransposeReturnType
typedef SparseMatrix< Scalar, Flags &RowMajorBit ? RowMajor :ColMajor, StorageIndex > PlainObject
typedef NumTraits< Scalar >::Real RealScalar
typedef std::conditional_t< HasDirectAccess_, const Scalar &, Scalar > CoeffReturnType
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, Matrix< Scalar, Dynamic, Dynamic > > ConstantReturnType
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime > DenseMatrixType
typedef Matrix< Scalar, internal::max_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime), internal::max_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime)> SquareMatrixType
typedef EigenBase< Derived > Base
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
template<typename OtherDerived >
Derived & operator= (const EigenBase< OtherDerived > &other)
const Derived & derived () const
Derived & derived ()
Derived & const_cast_derived () const
Index rows () const
Index cols () const
Index size () const
bool isVector () const
Index outerSize () const
Index innerSize () const
bool isRValue () const
Derived & markAsRValue ()
SparseMatrixBase ()
template<typename OtherDerived >
Derived & operator= (const ReturnByValue< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator= (const SparseMatrixBase< OtherDerived > &other)
Derived & operator= (const Derived &other)
template<typename OtherDerived >
Derived & operator+= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator-= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator+= (const DiagonalBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator-= (const DiagonalBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator+= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator-= (const EigenBase< OtherDerived > &other)
Derived & operator*= (const Scalar &other)
Derived & operator/= (const Scalar &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE const CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const Product< Derived, OtherDerived > operator* (const DiagonalBase< OtherDerived > &other) const
template<typename OtherDerived >
const Product< Derived, OtherDerived, AliasFreeProduct > operator* (const SparseMatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const Product< Derived, OtherDerived > operator* (const MatrixBase< OtherDerived > &other) const
SparseSymmetricPermutationProduct< Derived, Upper|Lower > twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > &perm) const
template<typename OtherDerived >
Derived & operator*= (const SparseMatrixBase< OtherDerived > &other)
template<int Mode>
const TriangularView< const Derived, Mode > triangularView () const
template<unsigned int UpLo>
ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
template<unsigned int UpLo>
SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
template<typename OtherDerived >
Scalar dot (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
RealScalar squaredNorm () const
RealScalar norm () const
RealScalar blueNorm () const
TransposeReturnType transpose ()
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
DenseMatrixType toDense () const
template<typename OtherDerived >
bool isApprox (const SparseMatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
bool isApprox (const MatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
const internal::eval< Derived >::type eval () const
Scalar sum () const
const SparseView< Derived > pruned (const Scalar &reference=Scalar(0), const RealScalar &epsilon=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & operator-= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & operator+= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE const SparseMatrixBase< Derived >::template CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
internal::traits< Derived >::Scalar dot (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
internal::traits< Derived >::Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
template<unsigned int UpLo>
SparseMatrixBase< Derived >::template ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
template<unsigned int UpLo>
SparseMatrixBase< Derived >::template SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
Public Member Functions inherited from Eigen::EigenBase< Derived >
constexpr EIGEN_DEVICE_FUNC Derived & derived ()
constexpr EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< Derived, Device > device (Device &device)
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const Derived, Device > device (Device &device) const
Protected Member Functions
template<typename OtherDerived >
Derived & assign (const OtherDerived &other)
template<typename OtherDerived >
void assignGeneric (const OtherDerived &other)
Static Protected Member Functions
static StorageIndex convert_index (const Index idx)
Protected Attributes
bool m_isRValue
Private Member Functions
template<typename Dest >
void evalTo (Dest &) const
Friends
std::ostream & operator<< (std::ostream &s, const SparseMatrixBase &m)
template<typename OtherDerived >
const Product< OtherDerived, Derived > operator* (const DiagonalBase< OtherDerived > &lhs, const SparseMatrixBase &rhs)
template<typename OtherDerived >
const Product< OtherDerived, Derived > operator* (const MatrixBase< OtherDerived > &lhs, const SparseMatrixBase &rhs)
Detailed Description
template<typename Derived>
class Eigen::SparseMatrixBase< Derived >
Base class of any sparse matrices or sparse expressions.
Template Parameters
Derived is the derived type, e.g. a sparse matrix type, or an expression, etc.
This class can be extended with the help of the plugin mechanism described on the page Extending MatrixBase (and other classes) by defining the preprocessor symbol EIGEN_SPARSEMATRIXBASE_PLUGIN.
Member Typedef Documentation
AdjointReturnType
template<typename Derived > typedef std::conditional_t<NumTraits<Scalar>::IsComplex, CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>, Eigen::Transpose<const Derived> >, Transpose<const Derived> > Eigen::SparseMatrixBase< Derived >::AdjointReturnType
the return type of MatrixBase::adjoint()
Base
template<typename Derived > typedef EigenBase<Derived> Eigen::SparseMatrixBase< Derived >::Base
CoeffReturnType
template<typename Derived > typedef std::conditional_t<HasDirectAccess_, const Scalar&, Scalar> Eigen::SparseMatrixBase< Derived >::CoeffReturnType
the return type of coeff()
ConstantReturnType
template<typename Derived > typedef CwiseNullaryOp<internal::scalar_constant_op<Scalar>, Matrix<Scalar, Dynamic, Dynamic> > Eigen::SparseMatrixBase< Derived >::ConstantReturnType
Represents a matrix with all coefficients equal to one another
ConstTransposeReturnType
template<typename Derived > typedef Transpose<const Derived> Eigen::SparseMatrixBase< Derived >::ConstTransposeReturnType
DenseMatrixType
template<typename Derived > typedef Matrix<Scalar, RowsAtCompileTime, ColsAtCompileTime> Eigen::SparseMatrixBase< Derived >::DenseMatrixType
type of the equivalent dense matrix
IndexVector
template<typename Derived > typedef Matrix<StorageIndex, Dynamic, 1> Eigen::SparseMatrixBase< Derived >::IndexVector
PacketReturnType
template<typename Derived > typedef internal::add_const_on_value_type_if_arithmetic<typename internal::packet_traits<Scalar>::type>::type Eigen::SparseMatrixBase< Derived >::PacketReturnType
PacketScalar
template<typename Derived > typedef internal::packet_traits<Scalar>::type Eigen::SparseMatrixBase< Derived >::PacketScalar
PlainObject
template<typename Derived > typedef SparseMatrix<Scalar, Flags & RowMajorBit ? RowMajor : ColMajor, StorageIndex> Eigen::SparseMatrixBase< Derived >::PlainObject
RealScalar
template<typename Derived > typedef NumTraits<Scalar>::Real Eigen::SparseMatrixBase< Derived >::RealScalar
This is the "real scalar" type; if the Scalar type is already real numbers (e.g. int, float or double) then RealScalar is just the same as Scalar. If Scalar is std::complex<T> then RealScalar is T.
See also
class NumTraits
Scalar
template<typename Derived > typedef internal::traits<Derived>::Scalar Eigen::SparseMatrixBase< Derived >::Scalar
ScalarVector
template<typename Derived > typedef Matrix<Scalar, Dynamic, 1> Eigen::SparseMatrixBase< Derived >::ScalarVector
SquareMatrixType
template<typename Derived > typedef Matrix<Scalar, internal::max_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime), internal::max_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime)> Eigen::SparseMatrixBase< Derived >::SquareMatrixType
type of the equivalent square matrix
StorageBaseType
template<typename Derived > typedef SparseMatrixBase Eigen::SparseMatrixBase< Derived >::StorageBaseType
StorageIndex
template<typename Derived > typedef internal::traits<Derived>::StorageIndex Eigen::SparseMatrixBase< Derived >::StorageIndex
The integer type used to store indices within a SparseMatrix. For a SparseMatrix<Scalar,Options,IndexType> it an alias of the third template parameter IndexType.
StorageKind
template<typename Derived > typedef internal::traits<Derived>::StorageKind Eigen::SparseMatrixBase< Derived >::StorageKind
TransposeReturnType
template<typename Derived > typedef Transpose<Derived> Eigen::SparseMatrixBase< Derived >::TransposeReturnType
value_type
template<typename Derived > typedef Scalar Eigen::SparseMatrixBase< Derived >::value_type
The numeric type of the expression' coefficients, e.g. float, double, int or std::complex<float>, etc.
It is an alias for the Scalar type
Member Enumeration Documentation
anonymous enum
template<typename Derived > anonymous enum
Enumerator
RowsAtCompileTime
The number of rows at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), ColsAtCompileTime, SizeAtCompileTime
ColsAtCompileTime
The number of columns at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), RowsAtCompileTime, SizeAtCompileTime
SizeAtCompileTime
This is equal to the number of coefficients, i.e. the number of rows times the number of columns, or to Dynamic if this is not known at compile-time.
See also
RowsAtCompileTime, ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
MaxSizeAtCompileTime
IsVectorAtCompileTime
This is set to true if either the number of rows or the number of columns is known at compile-time to be equal to 1. Indeed, in that case, we are dealing with a column-vector (if there is only one column) or with a row-vector (if there is only one row).
NumDimensions
This value is equal to Tensor::NumDimensions, i.e. 0 for scalars, 1 for vectors, and 2 for matrices.
Flags
This stores expression Flags flags which may or may not be inherited by new expressions constructed from this one. See the list of flags.
IsRowMajor
InnerSizeAtCompileTime
HasDirectAccess_
        {
     RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime,
     ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime,
     SizeAtCompileTime = (internal::size_of_xpr_at_compile_time<Derived>::ret),
     MaxRowsAtCompileTime = RowsAtCompileTime,
     MaxColsAtCompileTime = ColsAtCompileTime,
     MaxSizeAtCompileTime = internal::size_at_compile_time(MaxRowsAtCompileTime, MaxColsAtCompileTime),
     IsVectorAtCompileTime = RowsAtCompileTime == 1 || ColsAtCompileTime == 1,
     NumDimensions = int(MaxSizeAtCompileTime) == 1 ? 0
                     : bool(IsVectorAtCompileTime)  ? 1
                                                    : 2,
     Flags = internal::traits<Derived>::Flags,
     IsRowMajor = Flags & RowMajorBit ? 1 : 0,
     InnerSizeAtCompileTime = int(IsVectorAtCompileTime) ? int(SizeAtCompileTime)
                              : int(IsRowMajor)          ? int(ColsAtCompileTime)
                                                         : int(RowsAtCompileTime),
 #ifndef EIGEN_PARSED_BY_DOXYGEN
     HasDirectAccess_ = (int(Flags) & DirectAccessBit) ? 1 : 0  // workaround sunCC
 #endif
   };
Constructor & Destructor Documentation
SparseMatrixBase()
template<typename Derived > Eigen::SparseMatrixBase< Derived >::SparseMatrixBase () inline
                      : m_isRValue(false) { /* TODO check flags */
   }
Member Function Documentation
adjoint()
template<typename Derived > const AdjointReturnType Eigen::SparseMatrixBase< Derived >::adjoint () const inline
 { return AdjointReturnType(transpose()); }
References Eigen::SparseMatrixBase< Derived >::transpose().
Referenced by Eigen::IncompleteCholesky< Scalar, UpLo_, OrderingType_ >::_solve_impl(), Eigen::internal::least_square_conjugate_gradient(), Eigen::SparseSelfAdjointView< MatrixType, Mode_ >::rankUpdate(), trmm(), and Eigen::internal::upperbidiagonalization_inplace_unblocked().
assign()
template<typename Derived > template<typename OtherDerived > Derived& Eigen::SparseMatrixBase< Derived >::assign (const OtherDerived & other) inline protected
assignGeneric()
template<typename Derived > template<typename OtherDerived > void Eigen::SparseMatrixBase< Derived >::assignGeneric (const OtherDerived & other) inline protected
blueNorm()
template<typename Derived > NumTraits< typename internal::traits< Derived >::Scalar >::Real Eigen::SparseMatrixBase< Derived >::blueNorm inline
           {
   return internal::blueNorm_impl(*this);
 }
References Eigen::internal::blueNorm_impl().
cols()
template<typename Derived > Index Eigen::SparseMatrixBase< Derived >::cols () const inline
Returns
the number of columns.
See also
rows()
 { return derived().cols(); }
References Eigen::SparseMatrixBase< Derived >::derived().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::SparseMatrixBase< Derived >::innerSize(), Eigen::SparseMatrixBase< Derived >::isVector(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::operator=(), Eigen::SparseMatrixBase< Derived >::outerSize(), Eigen::SparseMatrixBase< Derived >::size(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
const_cast_derived()
template<typename Derived > Derived& Eigen::SparseMatrixBase< Derived >::const_cast_derived () const inline
 { return *static_cast<Derived*>(const_cast<SparseMatrixBase*>(this)); }
Referenced by Eigen::internal::evaluator< SparseVector< Scalar_, Options_, Index_ > >::operator SparseVectorType &(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::operator=(), Eigen::SparseVector< Scalar_, Options_, StorageIndex_ >::operator=(), Eigen::Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), and Eigen::viewAsCholmod().
convert_index()
template<typename Derived > static StorageIndex Eigen::SparseMatrixBase< Derived >::convert_index (const Index idx) inline static protected
 { return internal::convert_index<StorageIndex>(idx); }
cwiseProduct() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_STRONG_INLINE const SparseMatrixBase<Derived>::template CwiseProductDenseReturnType<OtherDerived>::Type Eigen::SparseMatrixBase< Derived >::cwiseProduct (const MatrixBase< OtherDerived > & other) const
{
   return typename CwiseProductDenseReturnType<OtherDerived>::Type(derived(), other.derived());
 }
cwiseProduct() [2/2]
template<typename Derived > template<typename OtherDerived > EIGEN_STRONG_INLINE const CwiseProductDenseReturnType<OtherDerived>::Type Eigen::SparseMatrixBase< Derived >::cwiseProduct (const MatrixBase< OtherDerived > & other) const
Referenced by Eigen::MatrixBase< Derived >::cwiseProduct().
derived() [1/2]
template<typename Derived > Derived& Eigen::SparseMatrixBase< Derived >::derived () inline
 { return *static_cast<Derived*>(this); }
derived() [2/2]
template<typename Derived > const Derived& Eigen::SparseMatrixBase< Derived >::derived () const inline
 { return *static_cast<const Derived*>(this); }
Referenced by Eigen::SparseSolverBase< Derived >::_solve_impl(), Eigen::CholmodBase< MatrixType_, UpLo_, Derived >::_solve_impl(), Eigen::IterativeSolverBase< Derived >::_solve_with_guess_impl(), Eigen::accurateDot(), Eigen::SparseMatrixBase< Derived >::cols(), Eigen::SparseMatrixBase< Derived >::dot(), eiToDense(), eiToGmm(), eiToMtl(), eiToUblas(), Eigen::SparseMatrixBase< Derived >::eval(), Eigen::internal::generic_matrix_wrapper< MatrixType, false >::grab(), Eigen::SparseCompressedBase< Derived >::innerIndexPtr(), Eigen::SparseCompressedBase< Derived >::innerIndicesAreSorted(), Eigen::SparseCompressedBase< Derived >::innerNonZeroPtr(), Eigen::SparseCompressedBase< Derived >::innerNonZeros(), Eigen::SparseMatrixBase< Derived >::isApprox(), main(), Eigen::SluMatrix::Map(), Eigen::SparseMatrixBase< Derived >::markAsRValue(), Eigen::SparseCompressedBase< Derived >::nonZeros(), Eigen::SparseMatrixBase< Derived >::operator*(), Eigen::SparseSelfAdjointView< MatrixType, Mode_ >::operator*(), Eigen::SparseMatrixBase< Derived >::operator+=(), Eigen::SparseMatrixBase< Derived >::operator-=(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::operator=(), Eigen::SparseMatrixBase< Derived >::operator=(), Eigen::SparseVector< Scalar_, Options_, StorageIndex_ >::operator=(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::operator=(), Eigen::SparseCompressedBase< Derived >::outerIndexPtr(), Eigen::internal::permute_symm_to_fullsymm(), Eigen::internal::permute_symm_to_symm(), Eigen::Ref< const SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::SparseMatrixBase< Derived >::rows(), Eigen::internal::visit_impl< Derived, Visitor, ShortCircuitEvaulation >::run(), Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run(), Eigen::SparseCompressedBase< Derived >::sortInnerIndices(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::SparseMatrix(), Eigen::SparseVector< Scalar_, Options_, StorageIndex_ >::SparseVector(), Eigen::SparseMatrixBase< Derived >::toDense(), Eigen::SparseMatrixBase< Derived >::transpose(), Eigen::SparseMatrixBase< Derived >::twistedBy(), Eigen::SparseCompressedBase< Derived >::valuePtr(), and Eigen::viewAsCholmod().
dot() [1/4]
template<typename Derived > template<typename OtherDerived > internal::traits<Derived>::Scalar Eigen::SparseMatrixBase< Derived >::dot (const MatrixBase< OtherDerived > & other) const inline
{
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(OtherDerived)
   EIGEN_STATIC_ASSERT_SAME_VECTOR_SIZE(Derived, OtherDerived)
   EIGEN_STATIC_ASSERT(
       (internal::is_same<Scalar, typename OtherDerived::Scalar>::value),
       YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY)
   eigen_assert(size() == other.size());
   eigen_assert(other.size() > 0 && "you are using a non initialized vector");
   internal::evaluator<Derived> thisEval(derived());
   typename internal::evaluator<Derived>::InnerIterator i(thisEval, 0);
   // Two accumulators, which breaks the dependency chain on the accumulator
   // and allows more instruction-level parallelism in the following loop.
   Scalar res1(0);
   Scalar res2(0);
   for (; i; ++i) {
     res1 += numext::conj(i.value()) * other.coeff(i.index());
     ++i;
     if (i) {
       res2 += numext::conj(i.value()) * other.coeff(i.index());
     }
   }
   return res1 + res2;
 }
References conj(), eigen_assert, EIGEN_STATIC_ASSERT, EIGEN_STATIC_ASSERT_SAME_VECTOR_SIZE, EIGEN_STATIC_ASSERT_VECTOR_ONLY, i, and size.
dot() [2/4]
template<typename Derived > template<typename OtherDerived > Scalar Eigen::SparseMatrixBase< Derived >::dot (const MatrixBase< OtherDerived > & other) const
dot() [3/4]
template<typename Derived > template<typename OtherDerived > internal::traits<Derived>::Scalar Eigen::SparseMatrixBase< Derived >::dot (const SparseMatrixBase< OtherDerived > & other) const inline
{
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(OtherDerived)
   EIGEN_STATIC_ASSERT_SAME_VECTOR_SIZE(Derived, OtherDerived)
   EIGEN_STATIC_ASSERT(
       (internal::is_same<Scalar, typename OtherDerived::Scalar>::value),
       YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY)
   eigen_assert(size() == other.size());
   internal::evaluator<Derived> thisEval(derived());
   typename internal::evaluator<Derived>::InnerIterator i(thisEval, 0);
   internal::evaluator<OtherDerived> otherEval(other.derived());
   typename internal::evaluator<OtherDerived>::InnerIterator j(otherEval, 0);
   Scalar res(0);
   while (i && j) {
     if (i.index() == j.index()) {
       res += numext::conj(i.value()) * j.value();
       ++i;
       ++j;
     } else if (i.index() < j.index())
       ++i;
     else
       ++j;
   }
   return res;
 }
References conj(), Eigen::SparseMatrixBase< Derived >::derived(), eigen_assert, EIGEN_STATIC_ASSERT, EIGEN_STATIC_ASSERT_SAME_VECTOR_SIZE, EIGEN_STATIC_ASSERT_VECTOR_ONLY, i, j, res, size, and Eigen::SparseMatrixBase< Derived >::size().
dot() [4/4]
template<typename Derived > template<typename OtherDerived > Scalar Eigen::SparseMatrixBase< Derived >::dot (const SparseMatrixBase< OtherDerived > & other) const
eval()
template<typename Derived > const internal::eval<Derived>::type Eigen::SparseMatrixBase< Derived >::eval () const inline
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
{
     return typename internal::eval<Derived>::type(derived());
   }
References Eigen::SparseMatrixBase< Derived >::derived(), and compute_granudrum_aor::type.
evalTo()
template<typename Derived > template<typename Dest > void Eigen::SparseMatrixBase< Derived >::evalTo (Dest &) const private
innerSize()
template<typename Derived > Index Eigen::SparseMatrixBase< Derived >::innerSize () const inline
Returns
the size of the inner dimension according to the storage order, i.e., the number of rows for a columns major matrix, and the number of cols otherwise
 { return (int(Flags) & RowMajorBit) ? this->cols() : this->rows(); }
References Eigen::SparseMatrixBase< Derived >::cols(), Eigen::RowMajorBit, and Eigen::SparseMatrixBase< Derived >::rows().
isApprox() [1/2]
template<typename Derived > template<typename OtherDerived > bool Eigen::SparseMatrixBase< Derived >::isApprox (const MatrixBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inline
{
     return toDense().isApprox(other, prec);
   }
References Eigen::SparseMatrixBase< Derived >::toDense().
isApprox() [2/2]
template<typename Derived > template<typename OtherDerived > bool Eigen::SparseMatrixBase< Derived >::isApprox (const SparseMatrixBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
{
   const typename internal::nested_eval<Derived, 2, PlainObject>::type actualA(derived());
   std::conditional_t<bool(IsRowMajor) == bool(OtherDerived::IsRowMajor),
                      const typename internal::nested_eval<OtherDerived, 2, PlainObject>::type, const PlainObject>
       actualB(other.derived());
   return (actualA - actualB).squaredNorm() <= prec * prec * numext::mini(actualA.squaredNorm(), actualB.squaredNorm());
 }
References Eigen::SparseMatrixBase< Derived >::derived(), and Eigen::numext::mini().
Referenced by test_random_setter().
isRValue()
template<typename Derived > bool Eigen::SparseMatrixBase< Derived >::isRValue () const inline
 { return m_isRValue; }
References Eigen::SparseMatrixBase< Derived >::m_isRValue.
Referenced by Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::operator=(), and Eigen::SparseVector< Scalar_, Options_, StorageIndex_ >::operator=().
isVector()
template<typename Derived > bool Eigen::SparseMatrixBase< Derived >::isVector () const inline
Returns
true if either the number of rows or the number of columns is equal to 1. In other words, this function returns
rows()==1 || cols()==1
See also
rows(), cols(), IsVectorAtCompileTime.
 { return rows() == 1 || cols() == 1; }
References Eigen::SparseMatrixBase< Derived >::cols(), and Eigen::SparseMatrixBase< Derived >::rows().
markAsRValue()
template<typename Derived > Derived& Eigen::SparseMatrixBase< Derived >::markAsRValue () inline
{
     m_isRValue = true;
     return derived();
   }
References Eigen::SparseMatrixBase< Derived >::derived(), and Eigen::SparseMatrixBase< Derived >::m_isRValue.
norm()
template<typename Derived > NumTraits< typename internal::traits< Derived >::Scalar >::Real Eigen::SparseMatrixBase< Derived >::norm inline
{
   using std::sqrt;
   return sqrt(squaredNorm());
 }
References sqrt().
Referenced by Eigen::SPQR< MatrixType_ >::compute(), and Eigen::MatrixMarketIterator< Scalar >::matrix().
operator*() [1/3]
template<typename Derived > template<typename OtherDerived > const Product<Derived, OtherDerived> Eigen::SparseMatrixBase< Derived >::operator* (const DiagonalBase< OtherDerived > & other) const inline
{
     return Product<Derived, OtherDerived>(derived(), other.derived());
   }
References Eigen::DiagonalBase< Derived >::derived(), and Eigen::SparseMatrixBase< Derived >::derived().
operator*() [2/3]
template<typename Derived > template<typename OtherDerived > const Product<Derived, OtherDerived> Eigen::SparseMatrixBase< Derived >::operator* (const MatrixBase< OtherDerived > & other) const inline
{
     return Product<Derived, OtherDerived>(derived(), other.derived());
   }
References Eigen::SparseMatrixBase< Derived >::derived().
operator*() [3/3]
template<typename Derived > template<typename OtherDerived > const Product< Derived, OtherDerived, AliasFreeProduct > Eigen::SparseMatrixBase< Derived >::operator* (const SparseMatrixBase< OtherDerived > & other) const inline
Returns
an expression of the product of two sparse matrices. By default a conservative product preserving the symbolic non zeros is performed. The automatic pruning of the small values can be achieved by calling the pruned() function in which case a totally different product algorithm is employed:
C = (A*B).pruned();             // suppress numerical zeros (exact)
C = (A*B).pruned(ref);
C = (A*B).pruned(ref,epsilon);
where ref is a meaningful non zero reference value.
{
   return Product<Derived, OtherDerived, AliasFreeProduct>(derived(), other.derived());
 }
References Eigen::SparseMatrixBase< Derived >::derived().
operator*=() [1/2]
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::SparseMatrixBase< Derived >::operator*= (const Scalar & other)
{
   typedef typename internal::evaluator<Derived>::InnerIterator EvalIterator;
   internal::evaluator<Derived> thisEval(derived());
   for (Index j = 0; j < outerSize(); ++j)
     for (EvalIterator i(thisEval, j); i; ++i) i.valueRef() *= other;
   return derived();
 }
References i, and j.
operator*=() [2/2]
template<typename Derived > template<typename OtherDerived > Derived& Eigen::SparseMatrixBase< Derived >::operator*= (const SparseMatrixBase< OtherDerived > & other)
operator+=() [1/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator+= (const DiagonalBase< OtherDerived > & other)
{
   call_assignment_no_alias(derived(), other.derived(),
                            internal::add_assign_op<Scalar, typename OtherDerived::Scalar>());
   return derived();
 }
References Eigen::internal::call_assignment_no_alias(), and Eigen::DiagonalBase< Derived >::derived().
operator+=() [2/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator+= (const EigenBase< OtherDerived > & other)
{
   call_assignment(derived(), other.derived(), internal::add_assign_op<Scalar, typename OtherDerived::Scalar>());
   return derived();
 }
References Eigen::internal::call_assignment(), and Eigen::EigenBase< Derived >::derived().
operator+=() [3/4]
template<typename Derived > template<typename OtherDerived > EIGEN_STRONG_INLINE Derived& Eigen::SparseMatrixBase< Derived >::operator+= (const SparseMatrixBase< OtherDerived > & other)
{
   return derived() = derived() + other.derived();
 }
References Eigen::SparseMatrixBase< Derived >::derived().
operator+=() [4/4]
template<typename Derived > template<typename OtherDerived > Derived& Eigen::SparseMatrixBase< Derived >::operator+= (const SparseMatrixBase< OtherDerived > & other)
operator-=() [1/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator-= (const DiagonalBase< OtherDerived > & other)
{
   call_assignment_no_alias(derived(), other.derived(),
                            internal::sub_assign_op<Scalar, typename OtherDerived::Scalar>());
   return derived();
 }
References Eigen::internal::call_assignment_no_alias(), and Eigen::DiagonalBase< Derived >::derived().
operator-=() [2/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator-= (const EigenBase< OtherDerived > & other)
{
   call_assignment(derived(), other.derived(), internal::assign_op<Scalar, typename OtherDerived::Scalar>());
   return derived();
 }
References Eigen::internal::call_assignment(), and Eigen::EigenBase< Derived >::derived().
operator-=() [3/4]
template<typename Derived > template<typename OtherDerived > EIGEN_STRONG_INLINE Derived& Eigen::SparseMatrixBase< Derived >::operator-= (const SparseMatrixBase< OtherDerived > & other)
{
   return derived() = derived() - other.derived();
 }
References Eigen::SparseMatrixBase< Derived >::derived().
operator-=() [4/4]
template<typename Derived > template<typename OtherDerived > Derived& Eigen::SparseMatrixBase< Derived >::operator-= (const SparseMatrixBase< OtherDerived > & other)
operator/=()
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::SparseMatrixBase< Derived >::operator/= (const Scalar & other)
{
   typedef typename internal::evaluator<Derived>::InnerIterator EvalIterator;
   internal::evaluator<Derived> thisEval(derived());
   for (Index j = 0; j < outerSize(); ++j)
     for (EvalIterator i(thisEval, j); i; ++i) i.valueRef() /= other;
   return derived();
 }
References i, and j.
operator=() [1/4]
template<typename Derived > Derived & Eigen::SparseMatrixBase< Derived >::operator= (const Derived & other) inline
{
   internal::call_assignment_no_alias(derived(), other.derived());
   return derived();
 }
References Eigen::internal::call_assignment_no_alias().
operator=() [2/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator= (const EigenBase< OtherDerived > & other)
{
   internal::call_assignment_no_alias(derived(), other.derived());
   return derived();
 }
References Eigen::internal::call_assignment_no_alias(), and Eigen::EigenBase< Derived >::derived().
operator=() [3/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator= (const ReturnByValue< OtherDerived > & other)
{
   // TODO use the evaluator mechanism
   other.evalTo(derived());
   return derived();
 }
References Eigen::ReturnByValue< Derived >::evalTo().
operator=() [4/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator= (const SparseMatrixBase< OtherDerived > & other) inline
{
   // by default sparse evaluation do not alias, so we can safely bypass the generic call_assignment routine
   internal::Assignment<Derived, OtherDerived, internal::assign_op<Scalar, typename OtherDerived::Scalar>>::run(
       derived(), other.derived(), internal::assign_op<Scalar, typename OtherDerived::Scalar>());
   return derived();
 }
References Eigen::SparseMatrixBase< Derived >::derived(), and Eigen::run().
outerSize()
template<typename Derived > Index Eigen::SparseMatrixBase< Derived >::outerSize () const inline
Returns
the size of the storage major dimension, i.e., the number of columns for a columns major matrix, and the number of rows otherwise
 { return (int(Flags) & RowMajorBit) ? this->rows() : this->cols(); }
References Eigen::SparseMatrixBase< Derived >::cols(), Eigen::RowMajorBit, and Eigen::SparseMatrixBase< Derived >::rows().
Referenced by Eigen::SparseCompressedBase< Derived >::innerIndicesAreSorted(), Eigen::SparseCompressedBase< Derived >::innerNonZeros(), Eigen::SparseCompressedBase< Derived >::nonZeros(), and Eigen::SparseCompressedBase< Derived >::sortInnerIndices().
pruned()
template<typename Derived > const SparseView< Derived > Eigen::SparseMatrixBase< Derived >::pruned (const Scalar & reference = Scalar(0), const RealScalar & epsilon = NumTraits<Scalar>::dummy_precision()) const inline
Returns
an expression of *this with values smaller than reference * epsilon removed.
This method is typically used in conjunction with the product of two sparse matrices to automatically prune the smallest values as follows:
C = (A*B).pruned();             // suppress numerical zeros (exact)
C = (A*B).pruned(ref);
C = (A*B).pruned(ref,epsilon);
where ref is a meaningful non zero reference value.
{
   return SparseView<Derived>(derived(), reference, epsilon);
 }
References oomph::SarahBL::epsilon.
rows()
template<typename Derived > Index Eigen::SparseMatrixBase< Derived >::rows () const inline
Returns
the number of rows.
See also
cols()
 { return derived().rows(); }
References Eigen::SparseMatrixBase< Derived >::derived().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::SparseMatrixBase< Derived >::innerSize(), Eigen::SparseMatrixBase< Derived >::isVector(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::operator=(), Eigen::SparseMatrixBase< Derived >::outerSize(), Eigen::SparseMatrixBase< Derived >::size(), Eigen::SparseQR< MatrixType_, OrderingType_ >::solve(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
selfadjointView() [1/4]
template<typename Derived > template<unsigned int UpLo> SelfAdjointViewReturnType<UpLo>::Type Eigen::SparseMatrixBase< Derived >::selfadjointView () inline
selfadjointView() [2/4]
template<typename Derived > template<unsigned int UpLo> SparseMatrixBase<Derived>::template SelfAdjointViewReturnType<UpLo>::Type Eigen::SparseMatrixBase< Derived >::selfadjointView ()
{
   return SparseSelfAdjointView<Derived, UpLo>(derived());
 }
selfadjointView() [3/4]
template<typename Derived > template<unsigned int UpLo> ConstSelfAdjointViewReturnType<UpLo>::Type Eigen::SparseMatrixBase< Derived >::selfadjointView () const inline
Referenced by main().
selfadjointView() [4/4]
template<typename Derived > template<unsigned int UpLo> SparseMatrixBase<Derived>::template ConstSelfAdjointViewReturnType<UpLo>::Type Eigen::SparseMatrixBase< Derived >::selfadjointView () const
{
   return SparseSelfAdjointView<const Derived, UpLo>(derived());
 }
size()
template<typename Derived > Index Eigen::SparseMatrixBase< Derived >::size () const inline
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols().
 { return rows() * cols(); }
References Eigen::SparseMatrixBase< Derived >::cols(), and Eigen::SparseMatrixBase< Derived >::rows().
Referenced by Eigen::SparseMatrixBase< Derived >::dot(), EIGEN_DECLARE_TEST(), Eigen::loadMarketDense(), Eigen::SluMatrix::Map(), Eigen::SparseVector< Scalar_, Options_, StorageIndex_ >::operator=(), Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, false, true, ShortCircuitEvaluation >::run(), and Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, true, true, ShortCircuitEvaluation >::run().
squaredNorm()
template<typename Derived > NumTraits< typename internal::traits< Derived >::Scalar >::Real Eigen::SparseMatrixBase< Derived >::squaredNorm inline
           {
   return numext::real((*this).cwiseAbs2().sum());
 }
Referenced by Eigen::LeastSquareDiagonalPreconditioner< Scalar_ >::factorize().
sum()
template<typename Derived > internal::traits< Derived >::Scalar Eigen::SparseMatrixBase< Derived >::sum
{
   eigen_assert(rows() > 0 && cols() > 0 && "you are using a non initialized matrix");
   Scalar res(0);
   internal::evaluator<Derived> thisEval(derived());
   for (Index j = 0; j < outerSize(); ++j)
     for (typename internal::evaluator<Derived>::InnerIterator iter(thisEval, j); iter; ++iter) res += iter.value();
   return res;
 }
References cols, eigen_assert, j, res, and rows.
toDense()
template<typename Derived > DenseMatrixType Eigen::SparseMatrixBase< Derived >::toDense () const inline
 { return DenseMatrixType(derived()); }
References Eigen::SparseMatrixBase< Derived >::derived().
Referenced by Eigen::SparseMatrixBase< Derived >::isApprox().
transpose() [1/2]
template<typename Derived > TransposeReturnType Eigen::SparseMatrixBase< Derived >::transpose () inline
 { return TransposeReturnType(derived()); }
References Eigen::SparseMatrixBase< Derived >::derived().
Referenced by Eigen::SparseMatrixBase< Derived >::adjoint(), Eigen::IncompleteLUT< Scalar_, StorageIndex_ >::analyzePattern(), call_ref(), GlMatrixHelper< true, Flags_ >::loadMatrix(), main(), GlMatrixHelper< true, Flags_ >::multMatrix(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::transform(), and trmm().
transpose() [2/2]
template<typename Derived > const ConstTransposeReturnType Eigen::SparseMatrixBase< Derived >::transpose () const inline
 { return ConstTransposeReturnType(derived()); }
References Eigen::SparseMatrixBase< Derived >::derived().
triangularView()
template<typename Derived > template<int Mode> const TriangularView< const Derived, Mode > Eigen::SparseMatrixBase< Derived >::triangularView inline
{
   return TriangularView<const Derived, Mode>(derived());
 }
twistedBy()
template<typename Derived > SparseSymmetricPermutationProduct<Derived, Upper | Lower> Eigen::SparseMatrixBase< Derived >::twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > & perm) const inline
Returns
an expression of P H P^-1 where H is the matrix represented by *this
{
     return SparseSymmetricPermutationProduct<Derived, Upper | Lower>(derived(), perm);
   }
References Eigen::SparseMatrixBase< Derived >::derived().
Referenced by Eigen::IncompleteLUT< Scalar_, StorageIndex_ >::factorize(), Eigen::IncompleteCholesky< Scalar, UpLo_, OrderingType_ >::factorize(), and sparse_permutations().
Friends And Related Function Documentation
operator* [1/2]
template<typename Derived > template<typename OtherDerived > const Product<OtherDerived, Derived> operator* (const DiagonalBase< OtherDerived > & lhs, const SparseMatrixBase< Derived > & rhs) friend
{
     return Product<OtherDerived, Derived>(lhs.derived(), rhs.derived());
   }
operator* [2/2]
template<typename Derived > template<typename OtherDerived > const Product<OtherDerived, Derived> operator* (const MatrixBase< OtherDerived > & lhs, const SparseMatrixBase< Derived > & rhs) friend
{
     return Product<OtherDerived, Derived>(lhs.derived(), rhs.derived());
   }
operator<<
template<typename Derived > std::ostream& operator<< (std::ostream & s, const SparseMatrixBase< Derived > & m) friend
{
     typedef typename Derived::Nested Nested;
     typedef internal::remove_all_t<Nested> NestedCleaned;
     if (Flags & RowMajorBit) {
       Nested nm(m.derived());
       internal::evaluator<NestedCleaned> thisEval(nm);
       for (Index row = 0; row < nm.outerSize(); ++row) {
         Index col = 0;
         for (typename internal::evaluator<NestedCleaned>::InnerIterator it(thisEval, row); it; ++it) {
           for (; col < it.index(); ++col) s << "0 ";
           s << it.value() << " ";
           ++col;
         }
         for (; col < m.cols(); ++col) s << "0 ";
         s << std::endl;
       }
     } else {
       Nested nm(m.derived());
       internal::evaluator<NestedCleaned> thisEval(nm);
       if (m.cols() == 1) {
         Index row = 0;
         for (typename internal::evaluator<NestedCleaned>::InnerIterator it(thisEval, 0); it; ++it) {
           for (; row < it.index(); ++row) s << "0" << std::endl;
           s << it.value() << std::endl;
           ++row;
         }
         for (; row < m.rows(); ++row) s << "0" << std::endl;
       } else {
         SparseMatrix<Scalar, RowMajorBit, StorageIndex> trans = m;
         s << static_cast<const SparseMatrixBase<SparseMatrix<Scalar, RowMajorBit, StorageIndex> >&>(trans);
       }
     }
     return s;
   }
Member Data Documentation
m_isRValue
template<typename Derived > bool Eigen::SparseMatrixBase< Derived >::m_isRValue protected
Referenced by Eigen::SparseMatrixBase< Derived >::isRValue(), and Eigen::SparseMatrixBase< Derived >::markAsRValue().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
SparseMatrixBase.h
SparseAssign.h
SparseCwiseBinaryOp.h
SparseCwiseUnaryOp.h
SparseDot.h
SparseFuzzy.h
SparseProduct.h
SparseRedux.h
SparseSelfAdjointView.h
SparseTriangularView.h
SparseView.h