MercuryDPM: oomph::QuarterPipeDomain Class Reference
oomph::QuarterPipeDomain Class Reference
Domain representing a quarter pipe.
#include <quarter_pipe_domain.h>
Public Types
typedef double(* AxialSpacingFctPt) (const double &xi)
Public Member Functions
QuarterPipeDomain (const unsigned &ntheta, const unsigned &nr, const unsigned &nz, const double &rmin, const double &rmax, const double &length)
QuarterPipeDomain (const QuarterPipeDomain &)=delete
Broken copy constructor.
void operator= (const QuarterPipeDomain &)=delete
Broken assignment operator.
~QuarterPipeDomain ()
Destructor:
AxialSpacingFctPt & axial_spacing_fct_pt ()
double axial_spacing_fct (const double &xi)
void macro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
Public Member Functions inherited from oomph::Domain
Domain ()
Constructor.
Domain (const Domain &)=delete
Broken copy constructor.
void operator= (const Domain &)=delete
Broken assignment operator.
virtual ~Domain ()
MacroElement * macro_element_pt (const unsigned &i)
Access to i-th macro element.
unsigned nmacro_element ()
Number of macro elements in domain.
void output (const std::string &filename, const unsigned &nplot)
Output macro elements.
void output (std::ostream &outfile, const unsigned &nplot)
Output macro elements.
virtual void macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void output_macro_element_boundaries (const std::string &filename, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
void output_macro_element_boundaries (std::ostream &outfile, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
virtual void dmacro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void dmacro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void dmacro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void d2macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
Private Member Functions
void r_U (const unsigned &t, const Vector< double > &zeta, Vector< double > &f, const double &rmin, const double &rmax, const double &thetamin, const double &thetamax, const double &zmin, const double &zmax)
Boundary of macro element zeta \(\in [-1,1]x[-1,1] \).
void r_L (const unsigned &t, const Vector< double > &zeta, Vector< double > &f, const double &rmin, const double &rmax, const double &thetamin, const double &thetamax, const double &zmin, const double &zmax)
Boundary of macro element zeta \(\in [-1,1]x[-1,1] \).
void r_D (const unsigned &t, const Vector< double > &zeta, Vector< double > &f, const double &rmin, const double &rmax, const double &thetamin, const double &thetamax, const double &zmin, const double &zmax)
Boundary of macro element zeta \(\in [-1,1]x[-1,1] \).
void r_R (const unsigned &t, const Vector< double > &zeta, Vector< double > &f, const double &rmin, const double &rmax, const double &thetamin, const double &thetamax, const double &zmin, const double &zmax)
Boundary of macro element zeta \(\in [-1,1]x[-1,1] \).
void r_F (const unsigned &t, const Vector< double > &zeta, Vector< double > &f, const double &rmin, const double &rmax, const double &thetamin, const double &thetamax, const double &zmin, const double &zmax)
Boundary of macro element zeta \(\in [-1,1]x[-1,1] \).
void r_B (const unsigned &t, const Vector< double > &zeta, Vector< double > &f, const double &rmin, const double &rmax, const double &thetamin, const double &thetamax, const double &zmin, const double &zmax)
Boundary of macro element zeta \(\in [-1,1]x[-1,1] \).
Static Private Member Functions
static double default_axial_spacing_fct (const double &xi)
Private Attributes
unsigned Ntheta
Number of elements azimuthal direction.
unsigned Nr
Number of elements radial direction.
unsigned Nz
Number of elements axial direction.
double Rmin
Inner radius.
double Rmax
Outer radius.
double Length
Length.
GeomObject * Outer_boundary_cross_section_pt
GeomObject * Inner_boundary_cross_section_pt
AxialSpacingFctPt Axial_spacing_fct_pt
Additional Inherited Members
Protected Attributes inherited from oomph::Domain
Vector< MacroElement * > Macro_element_pt
Vector of pointers to macro elements.
Detailed Description
Domain representing a quarter pipe.
Member Typedef Documentation
AxialSpacingFctPt
typedef double(* oomph::QuarterPipeDomain::AxialSpacingFctPt) (const double &xi)
Typedef for function pointer for function that implements axial spacing of macro elements
Constructor & Destructor Documentation
QuarterPipeDomain() [1/2]
oomph::QuarterPipeDomain::QuarterPipeDomain (const unsigned & ntheta, const unsigned & nr, const unsigned & nz, const double & rmin, const double & rmax, const double & length) inline
Constructor: Pass number of elements in various directions, the inner and outer radius and the length of the tube
       : Ntheta(ntheta),
         Nr(nr),
         Nz(nz),
         Rmin(rmin),
         Rmax(rmax),
         Length(length),
         Axial_spacing_fct_pt(&default_axial_spacing_fct)
     {
       // Number of macroelements
       unsigned nmacro = nr * ntheta * nz;
       // Resize
       Macro_element_pt.resize(nmacro);
       // Create macro elements
       for (unsigned i = 0; i < nmacro; i++)
       {
         Macro_element_pt[i] = new QMacroElement<3>(this, i);
       }
       // Make geom object representing the outer and inner boundaries of
       // the cross section
       Inner_boundary_cross_section_pt = new Ellipse(rmin, rmin);
       Outer_boundary_cross_section_pt = new Ellipse(rmax, rmax);
     }
References i, Inner_boundary_cross_section_pt, oomph::Domain::Macro_element_pt, Mesh_Parameters::nz, Outer_boundary_cross_section_pt, Global_Parameters::rmax, and Global_Parameters::rmin.
QuarterPipeDomain() [2/2]
oomph::QuarterPipeDomain::QuarterPipeDomain (const QuarterPipeDomain &) delete
Broken copy constructor.
~QuarterPipeDomain()
oomph::QuarterPipeDomain::~QuarterPipeDomain () inline
Destructor:
     {
       // Note: macro elements are cleaned up in base class...
       delete Outer_boundary_cross_section_pt;
       delete Inner_boundary_cross_section_pt;
     }
References Inner_boundary_cross_section_pt, and Outer_boundary_cross_section_pt.
Member Function Documentation
axial_spacing_fct()
double oomph::QuarterPipeDomain::axial_spacing_fct (const double & xi) inline
Function that implements axial spacing of macro elements
     {
       return Axial_spacing_fct_pt(xi);
     }
References Axial_spacing_fct_pt.
Referenced by macro_element_boundary().
axial_spacing_fct_pt()
AxialSpacingFctPt& oomph::QuarterPipeDomain::axial_spacing_fct_pt () inline
Function pointer for function that implements axial spacing of macro elements
     {
       return Axial_spacing_fct_pt;
     }
References Axial_spacing_fct_pt.
default_axial_spacing_fct()
static double oomph::QuarterPipeDomain::default_axial_spacing_fct (const double & xi) inline static private
Default for function that implements axial spacing of macro elements
     {
       return xi;
     }
macro_element_boundary()
void oomph::QuarterPipeDomain::macro_element_boundary (const unsigned & t, const unsigned & imacro, const unsigned & idirect, const Vector< double > & s, Vector< double > & f) virtual
Vector representation of the i_macro-th macro element boundary i_direct (U/D/L/R/F/B) at time level t (t=0: present; t>0: previous): f(s).
Vector representation of the imacro-th macro element boundary idirect (U/D/L/R/F/B) at time level t: f(s)
Implements oomph::Domain.
   {
     using namespace OcTreeNames;
     const double pi = MathematicalConstants::Pi;
     // Match the elements number with the position
     unsigned num_z = imacro / (Nr * Ntheta);
     unsigned num_y = (imacro % (Nr * Ntheta)) / Ntheta;
     unsigned num_x = imacro % Ntheta;
     // Define the extreme coordinates
     // radial direction
     double rmin = Rmin + (Rmax - Rmin) * double(num_y) / double(Nr);
     double rmax = Rmin + (Rmax - Rmin) * double(num_y + 1) / double(Nr);
     // theta direction
     double thetamin = (pi / 2.0) * (1.0 - double(num_x + 1) / double(Ntheta));
     double thetamax = (pi / 2.0) * (1.0 - double(num_x) / double(Ntheta));
     // zdirection (tube)
     double zmin = double(num_z) * Length / double(Nz);
     double zmax = double(num_z + 1) * Length / double(Nz);
     // Which direction?
     if (idirect == U)
     {
       r_U(t, s, f, rmin, rmax, thetamin, thetamax, zmin, zmax);
     }
     else if (idirect == D)
     {
       r_D(t, s, f, rmin, rmax, thetamin, thetamax, zmin, zmax);
     }
     else if (idirect == L)
     {
       r_L(t, s, f, rmin, rmax, thetamin, thetamax, zmin, zmax);
     }
     else if (idirect == R)
     {
       r_R(t, s, f, rmin, rmax, thetamin, thetamax, zmin, zmax);
     }
     else if (idirect == F)
     {
       r_F(t, s, f, rmin, rmax, thetamin, thetamax, zmin, zmax);
     }
     else if (idirect == B)
     {
       r_B(t, s, f, rmin, rmax, thetamin, thetamax, zmin, zmax);
     }
     else
     {
       std::ostringstream error_stream;
       error_stream << "idirect is " << idirect << " not one of U, D, L, R, F, B"
                    << std::endl;
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Now redistribute points in the axial direction
     double z_frac = f[2] / Length;
     f[2] = Length * axial_spacing_fct(z_frac);
   }
References axial_spacing_fct(), D, f(), oomph::OcTreeNames::F, L, Length, Nr, Ntheta, Nz, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, constants::pi, oomph::MathematicalConstants::Pi, R, r_B(), r_D(), r_F(), r_L(), r_R(), r_U(), Global_Parameters::rmax, Rmax, Global_Parameters::rmin, Rmin, s, plotPSD::t, RachelsAdvectionDiffusion::U, Global_Parameters::zmax, and Global_Parameters::zmin.
operator=()
void oomph::QuarterPipeDomain::operator= (const QuarterPipeDomain &) delete
Broken assignment operator.
r_B()
void oomph::QuarterPipeDomain::r_B (const unsigned & t, const Vector< double > & zeta, Vector< double > & f, const double & rmin, const double & rmax, const double & thetamin, const double & thetamax, const double & zmin, const double & zmax) private
Boundary of macro element zeta \(\in [-1,1]x[-1,1] \).
Back face of a macro element \(s \in [-1,1]*[-1,1] \).
   {
     Vector<double> x(1);
     x[0] = thetamax + (0.5 * (s[0] + 1.0)) * (thetamin - thetamax);
     // Point on outer wall
     Vector<double> r_outer(2);
     Outer_boundary_cross_section_pt->position(t, x, r_outer);
     // Point on inner wall
     Vector<double> r_inner(2);
     Inner_boundary_cross_section_pt->position(t, x, r_inner);
     // Get layer
     double rad = rmin + (0.5 * (s[1] + 1.0)) * (rmax - rmin);
     for (unsigned i = 0; i < 2; i++)
     {
       f[i] =
         r_inner[i] + (r_outer[i] - r_inner[i]) * (rad - Rmin) / (Rmax - Rmin);
     }
     f[2] = zmin;
   }
References f(), i, Inner_boundary_cross_section_pt, Outer_boundary_cross_section_pt, oomph::GeomObject::position(), Global_Parameters::rmax, Rmax, Global_Parameters::rmin, Rmin, s, plotPSD::t, plotDoE::x, and Global_Parameters::zmin.
Referenced by macro_element_boundary().
r_D()
void oomph::QuarterPipeDomain::r_D (const unsigned & t, const Vector< double > & zeta, Vector< double > & f, const double & rmin, const double & rmax, const double & thetamin, const double & thetamax, const double & zmin, const double & zmax) private
Boundary of macro element zeta \(\in [-1,1]x[-1,1] \).
Left face of a macro element \(s \in [-1,1]*[-1,1] \).
   {
     Vector<double> x(1);
     x[0] = thetamax + (0.5 * (s[0] + 1.0)) * (thetamin - thetamax);
     // Point on outer wall
     Vector<double> r_outer(2);
     Outer_boundary_cross_section_pt->position(t, x, r_outer);
     // Point on inner wall
     Vector<double> r_inner(2);
     Inner_boundary_cross_section_pt->position(t, x, r_inner);
     // Get layer
     for (unsigned i = 0; i < 2; i++)
     {
       f[i] =
         r_inner[i] + (r_outer[i] - r_inner[i]) * (rmin - Rmin) / (Rmax - Rmin);
     }
     f[2] = zmin + (zmax - zmin) * (0.5 * (s[1] + 1.0));
   }
References f(), i, Inner_boundary_cross_section_pt, Outer_boundary_cross_section_pt, oomph::GeomObject::position(), Rmax, Global_Parameters::rmin, Rmin, s, plotPSD::t, plotDoE::x, Global_Parameters::zmax, and Global_Parameters::zmin.
Referenced by macro_element_boundary().
r_F()
void oomph::QuarterPipeDomain::r_F (const unsigned & t, const Vector< double > & zeta, Vector< double > & f, const double & rmin, const double & rmax, const double & thetamin, const double & thetamax, const double & zmin, const double & zmax) private
Boundary of macro element zeta \(\in [-1,1]x[-1,1] \).
Front face of a macro element \(s \in [-1,1]*[-1,1] \).
   {
     Vector<double> x(1);
     x[0] = thetamax + (0.5 * (s[0] + 1.0)) * (thetamin - thetamax);
     // Point on outer wall
     Vector<double> r_outer(2);
     Outer_boundary_cross_section_pt->position(t, x, r_outer);
     // Point on inner wall
     Vector<double> r_inner(2);
     Inner_boundary_cross_section_pt->position(t, x, r_inner);
     // Get layer
     double rad = rmin + (0.5 * (s[1] + 1.0)) * (rmax - rmin);
     for (unsigned i = 0; i < 2; i++)
     {
       f[i] =
         r_inner[i] + (r_outer[i] - r_inner[i]) * (rad - Rmin) / (Rmax - Rmin);
     }
     f[2] = zmax;
   }
References f(), i, Inner_boundary_cross_section_pt, Outer_boundary_cross_section_pt, oomph::GeomObject::position(), Global_Parameters::rmax, Rmax, Global_Parameters::rmin, Rmin, s, plotPSD::t, plotDoE::x, and Global_Parameters::zmax.
Referenced by macro_element_boundary().
r_L()
void oomph::QuarterPipeDomain::r_L (const unsigned & t, const Vector< double > & zeta, Vector< double > & f, const double & rmin, const double & rmax, const double & thetamin, const double & thetamax, const double & zmin, const double & zmax) private
Boundary of macro element zeta \(\in [-1,1]x[-1,1] \).
Left face of a macro element \(s \in [-1,1]*[-1,1] \).
   {
     Vector<double> x(1);
     x[0] = thetamax;
     // Point on outer wall
     Vector<double> r_outer(2);
     Outer_boundary_cross_section_pt->position(t, x, r_outer);
     // Point on inner wall
     Vector<double> r_inner(2);
     Inner_boundary_cross_section_pt->position(t, x, r_inner);
     // Get layer boundaries
     Vector<double> r_top(2);
     Vector<double> r_bot(2);
     for (unsigned i = 0; i < 2; i++)
     {
       r_top[i] =
         r_inner[i] + (r_outer[i] - r_inner[i]) * (rmax - Rmin) / (Rmax - Rmin);
       r_bot[i] =
         r_inner[i] + (r_outer[i] - r_inner[i]) * (rmin - Rmin) / (Rmax - Rmin);
     }
     // Compute coordinates
     f[0] = r_bot[0] + (0.5 * (s[0] + 1.0)) * (r_top[0] - r_bot[0]);
     f[1] = r_bot[1] + (0.5 * (s[0] + 1.0)) * (r_top[1] - r_bot[1]);
     f[2] = zmin + (zmax - zmin) * (0.5 * (s[1] + 1.0));
   }
References f(), i, Inner_boundary_cross_section_pt, Outer_boundary_cross_section_pt, oomph::GeomObject::position(), Global_Parameters::rmax, Rmax, Global_Parameters::rmin, Rmin, s, plotPSD::t, plotDoE::x, Global_Parameters::zmax, and Global_Parameters::zmin.
Referenced by macro_element_boundary().
r_R()
void oomph::QuarterPipeDomain::r_R (const unsigned & t, const Vector< double > & zeta, Vector< double > & f, const double & rmin, const double & rmax, const double & thetamin, const double & thetamax, const double & zmin, const double & zmax) private
Boundary of macro element zeta \(\in [-1,1]x[-1,1] \).
Right face of a macro element \(s \in [-1,1]*[-1,1] \).
   {
     Vector<double> x(1);
     x[0] = thetamin;
     // Point on outer wall
     Vector<double> r_outer(2);
     Outer_boundary_cross_section_pt->position(t, x, r_outer);
     // Point on inner wall
     Vector<double> r_inner(2);
     Inner_boundary_cross_section_pt->position(t, x, r_inner);
     // Get layer boundaries
     Vector<double> r_top(2);
     Vector<double> r_bot(2);
     for (unsigned i = 0; i < 2; i++)
     {
       r_top[i] =
         r_inner[i] + (r_outer[i] - r_inner[i]) * (rmax - Rmin) / (Rmax - Rmin);
       r_bot[i] =
         r_inner[i] + (r_outer[i] - r_inner[i]) * (rmin - Rmin) / (Rmax - Rmin);
     }
     // Compute coordinates
     f[0] = r_bot[0] + (0.5 * (s[0] + 1.0)) * (r_top[0] - r_bot[0]);
     f[1] = r_bot[1] + (0.5 * (s[0] + 1.0)) * (r_top[1] - r_bot[1]);
     f[2] = zmin + (zmax - zmin) * (0.5 * (s[1] + 1.0));
   }
References f(), i, Inner_boundary_cross_section_pt, Outer_boundary_cross_section_pt, oomph::GeomObject::position(), Global_Parameters::rmax, Rmax, Global_Parameters::rmin, Rmin, s, plotPSD::t, plotDoE::x, Global_Parameters::zmax, and Global_Parameters::zmin.
Referenced by macro_element_boundary().
r_U()
void oomph::QuarterPipeDomain::r_U (const unsigned & t, const Vector< double > & zeta, Vector< double > & f, const double & rmin, const double & rmax, const double & thetamin, const double & thetamax, const double & zmin, const double & zmax) private
Boundary of macro element zeta \(\in [-1,1]x[-1,1] \).
Right face of a macro element \(s \in [-1,1]*[-1,1] \).
   {
     Vector<double> x(1);
     x[0] = thetamax + (0.5 * (s[0] + 1.0)) * (thetamin - thetamax);
     // Point on outer wall
     Vector<double> r_outer(2);
     Outer_boundary_cross_section_pt->position(t, x, r_outer);
     // Point on inner wall
     Vector<double> r_inner(2);
     Inner_boundary_cross_section_pt->position(t, x, r_inner);
     // Get layer
     for (unsigned i = 0; i < 2; i++)
     {
       f[i] =
         r_inner[i] + (r_outer[i] - r_inner[i]) * (rmax - Rmin) / (Rmax - Rmin);
     }
     f[2] = zmin + (zmax - zmin) * (0.5 * (s[1] + 1.0));
   }
References f(), i, Inner_boundary_cross_section_pt, Outer_boundary_cross_section_pt, oomph::GeomObject::position(), Global_Parameters::rmax, Rmax, Rmin, s, plotPSD::t, plotDoE::x, Global_Parameters::zmax, and Global_Parameters::zmin.
Referenced by macro_element_boundary().
Member Data Documentation
Axial_spacing_fct_pt
AxialSpacingFctPt oomph::QuarterPipeDomain::Axial_spacing_fct_pt private
Function pointer for function that implements axial spacing of macro elements
Referenced by axial_spacing_fct(), and axial_spacing_fct_pt().
Inner_boundary_cross_section_pt
GeomObject* oomph::QuarterPipeDomain::Inner_boundary_cross_section_pt private
Geom object representing the inner boundary of the cross section
Referenced by QuarterPipeDomain(), r_B(), r_D(), r_F(), r_L(), r_R(), r_U(), and ~QuarterPipeDomain().
Length
double oomph::QuarterPipeDomain::Length private
Length.
Referenced by macro_element_boundary().
Nr
unsigned oomph::QuarterPipeDomain::Nr private
Number of elements radial direction.
Referenced by macro_element_boundary().
Ntheta
unsigned oomph::QuarterPipeDomain::Ntheta private
Number of elements azimuthal direction.
Referenced by macro_element_boundary().
Nz
unsigned oomph::QuarterPipeDomain::Nz private
Number of elements axial direction.
Referenced by macro_element_boundary().
Outer_boundary_cross_section_pt
GeomObject* oomph::QuarterPipeDomain::Outer_boundary_cross_section_pt private
Geom object representing the outer boundary of the cross section
Referenced by QuarterPipeDomain(), r_B(), r_D(), r_F(), r_L(), r_R(), r_U(), and ~QuarterPipeDomain().
Rmax
double oomph::QuarterPipeDomain::Rmax private
Outer radius.
Referenced by macro_element_boundary(), r_B(), r_D(), r_F(), r_L(), r_R(), and r_U().
Rmin
double oomph::QuarterPipeDomain::Rmin private
Inner radius.
Referenced by macro_element_boundary(), r_B(), r_D(), r_F(), r_L(), r_R(), and r_U().
The documentation for this class was generated from the following file:
quarter_pipe_domain.h