MercuryDPM: oomph::QuarterTubeDomain Class Reference
oomph::QuarterTubeDomain Class Reference
#include <quarter_tube_domain.h>
Public Types
typedef double(* BLSquashFctPt) (const double &s)
typedef double(* AxialSpacingFctPt) (const double &xi)
Public Member Functions
QuarterTubeDomain (GeomObject *boundary_geom_object_pt, const Vector< double > &xi_lo, const double &fract_mid, const Vector< double > &xi_hi, const unsigned &nlayer)
QuarterTubeDomain (const QuarterTubeDomain &)=delete
Broken copy constructor.
void operator= (const QuarterTubeDomain &)=delete
Broken assignment operator.
~QuarterTubeDomain ()
Destructor: empty; cleanup done in base class.
BLSquashFctPt & bl_squash_fct_pt ()
double s_squashed (const double &s)
AxialSpacingFctPt & axial_spacing_fct_pt ()
double axial_spacing_fct (const double &xi)
void macro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
Public Member Functions inherited from oomph::Domain
Domain ()
Constructor.
Domain (const Domain &)=delete
Broken copy constructor.
void operator= (const Domain &)=delete
Broken assignment operator.
virtual ~Domain ()
MacroElement * macro_element_pt (const unsigned &i)
Access to i-th macro element.
unsigned nmacro_element ()
Number of macro elements in domain.
void output (const std::string &filename, const unsigned &nplot)
Output macro elements.
void output (std::ostream &outfile, const unsigned &nplot)
Output macro elements.
virtual void macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void output_macro_element_boundaries (const std::string &filename, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
void output_macro_element_boundaries (std::ostream &outfile, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
virtual void dmacro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void dmacro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void dmacro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void d2macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
Private Member Functions
void r_centr_L (const unsigned &t, const Vector< double > &zeta, const unsigned &i_layer, Vector< double > &f)
void r_centr_R (const unsigned &t, const Vector< double > &zeta, const unsigned &i_layer, Vector< double > &f)
void r_centr_D (const unsigned &t, const Vector< double > &zeta, const unsigned &i_layer, Vector< double > &f)
void r_centr_U (const unsigned &t, const Vector< double > &zeta, const unsigned &i_layer, Vector< double > &f)
void r_centr_B (const unsigned &t, const Vector< double > &zeta, const unsigned &i_layer, Vector< double > &f)
void r_centr_F (const unsigned &t, const Vector< double > &zeta, const unsigned &i_layer, Vector< double > &f)
void r_bot_right_L (const unsigned &t, const Vector< double > &zeta, const unsigned &i_layer, Vector< double > &f)
void r_bot_right_R (const unsigned &t, const Vector< double > &zeta, const unsigned &i_layer, Vector< double > &f)
void r_bot_right_D (const unsigned &t, const Vector< double > &zeta, const unsigned &i_layer, Vector< double > &f)
void r_bot_right_U (const unsigned &t, const Vector< double > &zeta, const unsigned &i_layer, Vector< double > &f)
void r_bot_right_B (const unsigned &t, const Vector< double > &zeta, const unsigned &i_layer, Vector< double > &f)
void r_bot_right_F (const unsigned &t, const Vector< double > &zeta, const unsigned &i_layer, Vector< double > &f)
void r_top_left_L (const unsigned &t, const Vector< double > &zeta, const unsigned &i_layer, Vector< double > &f)
void r_top_left_R (const unsigned &t, const Vector< double > &zeta, const unsigned &i_layer, Vector< double > &f)
void r_top_left_D (const unsigned &t, const Vector< double > &zeta, const unsigned &i_layer, Vector< double > &f)
void r_top_left_U (const unsigned &t, const Vector< double > &zeta, const unsigned &i_layer, Vector< double > &f)
void r_top_left_B (const unsigned &t, const Vector< double > &zeta, const unsigned &i_layer, Vector< double > &f)
void r_top_left_F (const unsigned &t, const Vector< double > &zeta, const unsigned &i_layer, Vector< double > &f)
Static Private Member Functions
static double default_BL_squash_fct (const double &s)
static double default_axial_spacing_fct (const double &xi)
Private Attributes
Vector< double > Xi_lo
Lower limit for the coordinates along the wall.
double Fract_mid
Fraction along wall where outer ring is to be divided.
Vector< double > Xi_hi
Upper limit for the coordinates along the wall.
unsigned Nlayer
Number of layers.
GeomObject * Wall_pt
Pointer to geometric object that represents the curved wall.
BLSquashFctPt BL_squash_fct_pt
AxialSpacingFctPt Axial_spacing_fct_pt
Additional Inherited Members
Protected Attributes inherited from oomph::Domain
Vector< MacroElement * > Macro_element_pt
Vector of pointers to macro elements.
Detailed Description
Quarter tube as domain. Domain is bounded by curved boundary which is represented by a GeomObject. Domain is parametrised by three macro elements in each of the nlayer slices
Member Typedef Documentation
AxialSpacingFctPt
typedef double(* oomph::QuarterTubeDomain::AxialSpacingFctPt) (const double &xi)
Typedef for function pointer for function that implements axial spacing of macro elements
BLSquashFctPt
typedef double(* oomph::QuarterTubeDomain::BLSquashFctPt) (const double &s)
Typedef for function pointer for function that squashes the outer two macro elements towards the wall by mapping the input value of the "radial" macro element coordinate to the return value
Constructor & Destructor Documentation
QuarterTubeDomain() [1/2]
oomph::QuarterTubeDomain::QuarterTubeDomain (GeomObject * boundary_geom_object_pt, const Vector< double > & xi_lo, const double & fract_mid, const Vector< double > & xi_hi, const unsigned & nlayer) inline
Constructor: Pass boundary object and start and end coordinates and fraction along boundary object where outer ring is divided. We form nlayer axial slices.
       : Xi_lo(xi_lo),
         Fract_mid(fract_mid),
         Xi_hi(xi_hi),
         Nlayer(nlayer),
         Wall_pt(boundary_geom_object_pt),
         BL_squash_fct_pt(&default_BL_squash_fct),
         Axial_spacing_fct_pt(&default_axial_spacing_fct)
     {
       // There are three macro elements
       unsigned nmacro = 3 * nlayer;
       // Resize
       Macro_element_pt.resize(nmacro);
       // Create macro elements
       for (unsigned i = 0; i < nmacro; i++)
       {
         Macro_element_pt[i] = new QMacroElement<3>(this, i);
       }
     }
References i, and oomph::Domain::Macro_element_pt.
QuarterTubeDomain() [2/2]
oomph::QuarterTubeDomain::QuarterTubeDomain (const QuarterTubeDomain &) delete
Broken copy constructor.
~QuarterTubeDomain()
oomph::QuarterTubeDomain::~QuarterTubeDomain () inline
Destructor: empty; cleanup done in base class.
 {}
Member Function Documentation
axial_spacing_fct()
double oomph::QuarterTubeDomain::axial_spacing_fct (const double & xi) inline
Function that implements axial spacing of macro elements
     {
       return Axial_spacing_fct_pt(xi);
     }
References Axial_spacing_fct_pt.
Referenced by r_bot_right_B(), r_bot_right_D(), r_bot_right_F(), r_bot_right_R(), r_bot_right_U(), r_centr_B(), r_centr_D(), r_centr_F(), r_centr_L(), r_centr_R(), r_centr_U(), r_top_left_B(), r_top_left_F(), r_top_left_L(), and r_top_left_U().
axial_spacing_fct_pt()
AxialSpacingFctPt& oomph::QuarterTubeDomain::axial_spacing_fct_pt () inline
Function pointer for function that implements axial spacing of macro elements
     {
       return Axial_spacing_fct_pt;
     }
References Axial_spacing_fct_pt.
Referenced by oomph::QuarterTubeMesh< ELEMENT >::axial_spacing_fct_pt(), and oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::axial_spacing_fct_pt().
bl_squash_fct_pt()
BLSquashFctPt& oomph::QuarterTubeDomain::bl_squash_fct_pt () inline
Function pointer for function that squashes the outer two macro elements towards the wall by mapping the input value of the "radial" macro element coordinate to the return value
     {
       return BL_squash_fct_pt;
     }
References BL_squash_fct_pt.
Referenced by oomph::QuarterTubeMesh< ELEMENT >::bl_squash_fct_pt().
default_axial_spacing_fct()
static double oomph::QuarterTubeDomain::default_axial_spacing_fct (const double & xi) inline static private
Default for function that implements axial spacing of macro elements
     {
       return xi;
     }
default_BL_squash_fct()
static double oomph::QuarterTubeDomain::default_BL_squash_fct (const double & s) inline static private
Default for function that squashes the outer two macro elements towards the wall by mapping the input value of the "radial" macro element coordinate to the return value: Identity.
     {
       return s;
     }
References s.
macro_element_boundary()
void oomph::QuarterTubeDomain::macro_element_boundary (const unsigned & t, const unsigned & imacro, const unsigned & idirect, const Vector< double > & s, Vector< double > & f) virtual
Vector representation of the i_macro-th macro element boundary i_direct (L/R/D/U/B/F) at time level t (t=0: present; t>0: previous): f(s).
////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// Vector representation of the imacro-th macro element boundary idirect (L/R/D/U/B/F) at time level t (t=0: present; t>0: previous): f(s)
Implements oomph::Domain.
   {
     using namespace OcTreeNames;
 #ifdef WARN_ABOUT_SUBTLY_CHANGED_OOMPH_INTERFACES
     // Warn about time argument being moved to the front
     OomphLibWarning(
       "Order of function arguments has changed between versions 0.8 and 0.85",
       "QuarterTubeDomain::macro_element_boundary(...)",
       OOMPH_EXCEPTION_LOCATION);
 #endif
     unsigned ilayer = unsigned(imacro / 3);
     // Which macro element?
     // --------------------
     switch (imacro % 3)
     {
         // Macro element 0: Central box
       case 0:
         // Which direction?
         if (idirect == L)
         {
           r_centr_L(t, s, ilayer, f);
         }
         else if (idirect == R)
         {
           r_centr_R(t, s, ilayer, f);
         }
         else if (idirect == D)
         {
           r_centr_D(t, s, ilayer, f);
         }
         else if (idirect == U)
         {
           r_centr_U(t, s, ilayer, f);
         }
         else if (idirect == B)
         {
           r_centr_B(t, s, ilayer, f);
         }
         else if (idirect == F)
         {
           r_centr_F(t, s, ilayer, f);
         }
         else
         {
           std::ostringstream error_stream;
           error_stream << "idirect is " << idirect
                        << " not one of L, R, D, U, B, F" << std::endl;
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
         break;
         // Macro element 1: Bottom right
       case 1:
         // Which direction?
         if (idirect == L)
         {
           r_bot_right_L(t, s, ilayer, f);
         }
         else if (idirect == R)
         {
           r_bot_right_R(t, s, ilayer, f);
         }
         else if (idirect == D)
         {
           r_bot_right_D(t, s, ilayer, f);
         }
         else if (idirect == U)
         {
           r_bot_right_U(t, s, ilayer, f);
         }
         else if (idirect == B)
         {
           r_bot_right_B(t, s, ilayer, f);
         }
         else if (idirect == F)
         {
           r_bot_right_F(t, s, ilayer, f);
         }
         else
         {
           std::ostringstream error_stream;
           error_stream << "idirect is " << idirect
                        << " not one of L, R, D, U, B, F" << std::endl;
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
         break;
       // Macro element 2:Top left
       case 2:
         // Which direction?
         if (idirect == L)
         {
           r_top_left_L(t, s, ilayer, f);
         }
         else if (idirect == R)
         {
           r_top_left_R(t, s, ilayer, f);
         }
         else if (idirect == D)
         {
           r_top_left_D(t, s, ilayer, f);
         }
         else if (idirect == U)
         {
           r_top_left_U(t, s, ilayer, f);
         }
         else if (idirect == B)
         {
           r_top_left_B(t, s, ilayer, f);
         }
         else if (idirect == F)
         {
           r_top_left_F(t, s, ilayer, f);
         }
         else
         {
           std::ostringstream error_stream;
           error_stream << "idirect is " << idirect
                        << " not one of L, R, D, U, B, F" << std::endl;
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
         break;
       default:
         // Error
         std::ostringstream error_stream;
         error_stream << "Wrong imacro " << imacro << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
   }
References D, f(), oomph::OcTreeNames::F, L, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, R, r_bot_right_B(), r_bot_right_D(), r_bot_right_F(), r_bot_right_L(), r_bot_right_R(), r_bot_right_U(), r_centr_B(), r_centr_D(), r_centr_F(), r_centr_L(), r_centr_R(), r_centr_U(), r_top_left_B(), r_top_left_D(), r_top_left_F(), r_top_left_L(), r_top_left_R(), r_top_left_U(), s, plotPSD::t, and RachelsAdvectionDiffusion::U.
operator=()
void oomph::QuarterTubeDomain::operator= (const QuarterTubeDomain &) delete
Broken assignment operator.
r_bot_right_B()
void oomph::QuarterTubeDomain::r_bot_right_B (const unsigned & t, const Vector< double > & zeta, const unsigned & i_layer, Vector< double > & f) private
Boundary of bottom right box macro element in layer i_layer zeta \(\in [-1,1]^2 \)
   {
     // Wall coordinates
     Vector<double> x(2);
     x[0] = Xi_lo[0] + (Xi_hi[0] - Xi_lo[0]) *
                         axial_spacing_fct(double(i_layer) / double(Nlayer));
     x[1] = Xi_lo[1] + Fract_mid * (Xi_hi[1] - Xi_lo[1]) * 0.5 * (1.0 + zeta[1]);
     // Get position vector to wall
     Vector<double> r_wall(3);
     Wall_pt->position(t, x, r_wall);
     // Get position vector on central box
     Vector<double> zeta_central(2);
     Vector<double> r_central(3);
     zeta_central[0] = zeta[1];
     zeta_central[1] = -1.0;
     r_centr_R(t, zeta_central, i_layer, r_central);
     // Straight line across
     f[0] = r_central[0] +
            (r_wall[0] - r_central[0]) * s_squashed(0.5 * (1.0 + zeta[0]));
     f[1] = r_central[1] +
            (r_wall[1] - r_central[1]) * s_squashed(0.5 * (1.0 + zeta[0]));
     f[2] = r_central[2] +
            (r_wall[2] - r_central[2]) * s_squashed(0.5 * (1.0 + zeta[0]));
   }
References axial_spacing_fct(), f(), Fract_mid, Nlayer, oomph::GeomObject::position(), r_centr_R(), s_squashed(), plotPSD::t, Wall_pt, plotDoE::x, Xi_hi, Xi_lo, and Eigen::zeta().
Referenced by macro_element_boundary().
r_bot_right_D()
void oomph::QuarterTubeDomain::r_bot_right_D (const unsigned & t, const Vector< double > & zeta, const unsigned & i_layer, Vector< double > & f) private
Boundary of bottom right box macro element in layer i_layer zeta \(\in [-1,1]^2 \)
   {
     // Wall coordinates along bottom edge of wall
     Vector<double> x(2);
     x[0] =
       Xi_lo[0] + (Xi_hi[0] - Xi_lo[0]) *
                    axial_spacing_fct((0.5 * (1.0 + zeta[1]) + double(i_layer)) /
                                      double(Nlayer));
     x[1] = Xi_lo[1];
     // Get position vector to bottom edge of wall
     Vector<double> r_bottom(3);
     Wall_pt->position(t, x, r_bottom);
     // Scale it down to half the width
     f[0] = 0.5 * r_bottom[0] * (1.0 + s_squashed(0.5 * (1.0 + zeta[0])));
     f[1] = r_bottom[1];
     // Warp it:
     double rho = s_squashed(0.5 * (1.0 + zeta[0]));
     f[2] = x[0] + rho * (r_bottom[2] - x[0]);
     // f[2]=r_bottom[2];
   }
References axial_spacing_fct(), f(), Nlayer, oomph::GeomObject::position(), s_squashed(), plotPSD::t, Wall_pt, plotDoE::x, Xi_hi, Xi_lo, and Eigen::zeta().
Referenced by macro_element_boundary().
r_bot_right_F()
void oomph::QuarterTubeDomain::r_bot_right_F (const unsigned & t, const Vector< double > & zeta, const unsigned & i_layer, Vector< double > & f) private
Boundary of bottom right box macro element in layer i_layer zeta \(\in [-1,1]^2 \)
   {
     // Wall coordinates
     Vector<double> x(2);
     x[0] = Xi_lo[0] + (Xi_hi[0] - Xi_lo[0]) *
                         axial_spacing_fct(double(1 + i_layer) / double(Nlayer));
     x[1] = Xi_lo[1] + Fract_mid * (Xi_hi[1] - Xi_lo[1]) * 0.5 * (1.0 + zeta[1]);
     // Get position vector to wall
     Vector<double> r_wall(3);
     Wall_pt->position(t, x, r_wall);
     // Get position vector on central box
     Vector<double> zeta_central(2);
     Vector<double> r_central(3);
     zeta_central[0] = zeta[1];
     zeta_central[1] = 1.0;
     r_centr_R(t, zeta_central, i_layer, r_central);
     // Straight line across
     f[0] = r_central[0] +
            (r_wall[0] - r_central[0]) * s_squashed(0.5 * (1.0 + zeta[0]));
     f[1] = r_central[1] +
            (r_wall[1] - r_central[1]) * s_squashed(0.5 * (1.0 + zeta[0]));
     f[2] = r_central[2] +
            (r_wall[2] - r_central[2]) * s_squashed(0.5 * (1.0 + zeta[0]));
   }
References axial_spacing_fct(), f(), Fract_mid, Nlayer, oomph::GeomObject::position(), r_centr_R(), s_squashed(), plotPSD::t, Wall_pt, plotDoE::x, Xi_hi, Xi_lo, and Eigen::zeta().
Referenced by macro_element_boundary().
r_bot_right_L()
void oomph::QuarterTubeDomain::r_bot_right_L (const unsigned & t, const Vector< double > & zeta, const unsigned & i_layer, Vector< double > & f) private
Boundary of bottom right box macro element in layer i_layer zeta \(\in [-1,1]^2 \)
   {
     r_centr_R(t, zeta, i_layer, f);
   }
References f(), r_centr_R(), plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_bot_right_R()
void oomph::QuarterTubeDomain::r_bot_right_R (const unsigned & t, const Vector< double > & zeta, const unsigned & i_layer, Vector< double > & f) private
Boundary of bottom right box macro element in layer i_layer zeta \(\in [-1,1]^2 \)
   {
     // Wall coordinates
     Vector<double> x(2);
     x[0] =
       Xi_lo[0] + (Xi_hi[0] - Xi_lo[0]) *
                    axial_spacing_fct((0.5 * (1.0 + zeta[1]) + double(i_layer)) /
                                      double(Nlayer));
     x[1] = Xi_lo[1] + Fract_mid * (Xi_hi[1] - Xi_lo[1]) * 0.5 * (1.0 + zeta[0]);
     // Get position vector on wall
     Wall_pt->position(t, x, f);
   }
References axial_spacing_fct(), f(), Fract_mid, Nlayer, oomph::GeomObject::position(), plotPSD::t, Wall_pt, plotDoE::x, Xi_hi, Xi_lo, and Eigen::zeta().
Referenced by macro_element_boundary().
r_bot_right_U()
void oomph::QuarterTubeDomain::r_bot_right_U (const unsigned & t, const Vector< double > & zeta, const unsigned & i_layer, Vector< double > & f) private
Boundary of bottom right box macro element in layer i_layer zeta \(\in [-1,1]^2 \)
   {
     // Wall coordinates of dividing line
     Vector<double> x(2);
     x[0] =
       Xi_lo[0] + (Xi_hi[0] - Xi_lo[0]) *
                    axial_spacing_fct((0.5 * (1.0 + zeta[1]) + double(i_layer)) /
                                      double(Nlayer));
     x[1] = Xi_lo[1] + Fract_mid * (Xi_hi[1] - Xi_lo[1]);
     // Get position vector on dividing line
     Vector<double> r_div(3);
     Wall_pt->position(t, x, r_div);
     // Position vector to corner of central box
     Vector<double> zeta_central(2);
     Vector<double> r_central(3);
     zeta_central[0] = 1.0;
     zeta_central[1] = zeta[1];
     r_centr_R(t, zeta_central, i_layer, r_central);
     // Straight line across
     f[0] = r_central[0] +
            (r_div[0] - r_central[0]) * s_squashed(0.5 * (1.0 + zeta[0]));
     f[1] = r_central[1] +
            (r_div[1] - r_central[1]) * s_squashed(0.5 * (1.0 + zeta[0]));
     f[2] = r_central[2] +
            (r_div[2] - r_central[2]) * s_squashed(0.5 * (1.0 + zeta[0]));
   }
References axial_spacing_fct(), f(), Fract_mid, Nlayer, oomph::GeomObject::position(), r_centr_R(), s_squashed(), plotPSD::t, Wall_pt, plotDoE::x, Xi_hi, Xi_lo, and Eigen::zeta().
Referenced by macro_element_boundary(), and r_top_left_R().
r_centr_B()
void oomph::QuarterTubeDomain::r_centr_B (const unsigned & t, const Vector< double > & zeta, const unsigned & i_layer, Vector< double > & f) private
Boundary of central box macro element in layer i_layer zeta \(\in [-1,1]^2 \)
   {
     // Wall coordinates along bottom edge of wall
     Vector<double> x(2);
     x[0] = Xi_lo[0] + (Xi_hi[0] - Xi_lo[0]) *
                         axial_spacing_fct(double(i_layer) / double(Nlayer));
     x[1] = Xi_lo[1];
     // Get position vector to bottom edge of wall
     Vector<double> r_bottom(3);
     Wall_pt->position(t, x, r_bottom);
     // Wall coordinates along top edge of wall
     x[0] = Xi_lo[0] + (Xi_hi[0] - Xi_lo[0]) *
                         axial_spacing_fct(double(i_layer) / double(Nlayer));
     x[1] = Xi_hi[1];
     // Get position vector to top edge of wall
     Vector<double> r_top(3);
     Wall_pt->position(t, x, r_top);
     // Map it
     f[0] = r_bottom[0] * 0.25 * (1.0 + zeta[0]);
     f[1] = r_top[1] * 0.25 * (1.0 + zeta[1]);
     // Warp it:
     double rho = 0.0; // 0.25*(1.0+zeta[1]);
     f[2] = x[0] + rho * (r_top[2] - x[0]);
     // f[2]=r_top[2];
   }
References axial_spacing_fct(), f(), Nlayer, oomph::GeomObject::position(), plotPSD::t, Wall_pt, plotDoE::x, Xi_hi, Xi_lo, and Eigen::zeta().
Referenced by macro_element_boundary().
r_centr_D()
void oomph::QuarterTubeDomain::r_centr_D (const unsigned & t, const Vector< double > & zeta, const unsigned & i_layer, Vector< double > & f) private
Boundary of central box macro element in layer i_layer zeta \(\in [-1,1]^2 \)
   {
     // Wall coordinates along bottom edge of wall
     Vector<double> x(2);
     x[0] =
       Xi_lo[0] + (Xi_hi[0] - Xi_lo[0]) *
                    axial_spacing_fct((0.5 * (1.0 + zeta[1]) + double(i_layer)) /
                                      double(Nlayer));
     x[1] = Xi_lo[1];
     // Get position vector to bottom edge of wall
     Vector<double> r_bottom(3);
     Wall_pt->position(t, x, r_bottom);
     // Scale it down to half the width
     f[0] = r_bottom[0] * 0.25 * (1.0 + zeta[0]);
     f[1] = r_bottom[1];
     // Warp it:
     double rho = 0.0; // 0.25*(1.0+zeta[0]);
     f[2] = x[0] + rho * (r_bottom[2] - x[0]);
     // f[2]=r_bottom[2];
   }
References axial_spacing_fct(), f(), Nlayer, oomph::GeomObject::position(), plotPSD::t, Wall_pt, plotDoE::x, Xi_hi, Xi_lo, and Eigen::zeta().
Referenced by macro_element_boundary().
r_centr_F()
void oomph::QuarterTubeDomain::r_centr_F (const unsigned & t, const Vector< double > & zeta, const unsigned & i_layer, Vector< double > & f) private
Boundary of central box macro element in layer i_layer zeta \(\in [-1,1]^2 \)
   {
     // Wall coordinates along bottom edge of wall
     Vector<double> x(2);
     x[0] = Xi_lo[0] + (Xi_hi[0] - Xi_lo[0]) *
                         axial_spacing_fct(double(1 + i_layer) / double(Nlayer));
     x[1] = Xi_lo[1];
     // Get position vector to bottom edge of wall
     Vector<double> r_bottom(3);
     Wall_pt->position(t, x, r_bottom);
     // Wall coordinates along top edge of wall
     x[0] = Xi_lo[0] + (Xi_hi[0] - Xi_lo[0]) *
                         axial_spacing_fct(double(1 + i_layer) / double(Nlayer));
     x[1] = Xi_hi[1];
     // Get position vector to top edge of wall
     Vector<double> r_top(3);
     Wall_pt->position(t, x, r_top);
     // Map it
     f[0] = r_bottom[0] * 0.25 * (1.0 + zeta[0]);
     f[1] = r_top[1] * 0.25 * (1.0 + zeta[1]);
     // Warp it:
     double rho = 0.0; // 0.25*(1.0+zeta[1]);
     f[2] = x[0] + rho * (r_top[2] - x[0]);
     // f[2]=r_top[2];
   }
References axial_spacing_fct(), f(), Nlayer, oomph::GeomObject::position(), plotPSD::t, Wall_pt, plotDoE::x, Xi_hi, Xi_lo, and Eigen::zeta().
Referenced by macro_element_boundary().
r_centr_L()
void oomph::QuarterTubeDomain::r_centr_L (const unsigned & t, const Vector< double > & zeta, const unsigned & i_layer, Vector< double > & f) private
Boundary of central box macro element in layer i_layer zeta \(\in [-1,1]^2 \)
   {
     // Wall coordinates along top edge of wall
     Vector<double> x(2);
     x[0] =
       Xi_lo[0] + (Xi_hi[0] - Xi_lo[0]) *
                    axial_spacing_fct((0.5 * (1.0 + zeta[1]) + double(i_layer)) /
                                      double(Nlayer));
     x[1] = Xi_hi[1];
     // Get position vector to upper edge of wall
     Vector<double> r_top(3);
     Wall_pt->position(t, x, r_top);
     // Scale it down to half the height
     f[0] = r_top[0];
     f[1] = r_top[1] * 0.25 * (1.0 + zeta[0]);
     // Warp it:
     double rho = 0.0; // 0.25*(1.0+zeta[0]);
     f[2] = x[0] + rho * (r_top[2] - x[0]);
     // f[2]=r_top[2];
   }
References axial_spacing_fct(), f(), Nlayer, oomph::GeomObject::position(), plotPSD::t, Wall_pt, plotDoE::x, Xi_hi, Xi_lo, and Eigen::zeta().
Referenced by macro_element_boundary().
r_centr_R()
void oomph::QuarterTubeDomain::r_centr_R (const unsigned & t, const Vector< double > & zeta, const unsigned & i_layer, Vector< double > & f) private
Boundary of central box macro element in layer i_layer zeta \(\in [-1,1]^2 \)
   {
     // Note the repetition in the calculation, there is some scope
     // for optimisation
     // Wall coordinates along top edge of wall
     Vector<double> x(2);
     x[0] =
       Xi_lo[0] + (Xi_hi[0] - Xi_lo[0]) *
                    axial_spacing_fct((0.5 * (1.0 + zeta[1]) + double(i_layer)) /
                                      double(Nlayer));
     x[1] = Xi_hi[1];
     // Get position vector to upper edge of wall
     Vector<double> r_top(3);
     Wall_pt->position(t, x, r_top);
     // Wall coordinates along bottom edge of wall
     x[0] =
       Xi_lo[0] + (Xi_hi[0] - Xi_lo[0]) *
                    axial_spacing_fct((0.5 * (1.0 + zeta[1]) + double(i_layer)) /
                                      double(Nlayer));
     x[1] = Xi_lo[1];
     // Get position vector to bottom edge of wall
     Vector<double> r_bottom(3);
     Wall_pt->position(t, x, r_bottom);
     // Scale it down to half the height, halfway across width
     f[0] = 0.5 * r_bottom[0];
     f[1] = r_top[1] * 0.25 * (1.0 + zeta[0]);
     // Warp it:
     double rho = 0.0; // 0.25*(1.0+zeta[0]);
     f[2] = x[0] + rho * (r_top[2] - x[0]);
     // f[2]=r_top[2];
   }
References axial_spacing_fct(), f(), Nlayer, oomph::GeomObject::position(), plotPSD::t, Wall_pt, plotDoE::x, Xi_hi, Xi_lo, and Eigen::zeta().
Referenced by macro_element_boundary(), r_bot_right_B(), r_bot_right_F(), r_bot_right_L(), and r_bot_right_U().
r_centr_U()
void oomph::QuarterTubeDomain::r_centr_U (const unsigned & t, const Vector< double > & zeta, const unsigned & i_layer, Vector< double > & f) private
Boundary of central box macro element in layer i_layer zeta \(\in [-1,1]^2 \)
   {
     // Wall coordinates along top edge of wall
     Vector<double> x(2);
     x[0] =
       Xi_lo[0] + (Xi_hi[0] - Xi_lo[0]) *
                    axial_spacing_fct((0.5 * (1.0 + zeta[1]) + double(i_layer)) /
                                      double(Nlayer));
     x[1] = Xi_hi[1];
     // Get position vector to upper edge of wall
     Vector<double> r_top(3);
     Wall_pt->position(t, x, r_top);
     // Wall coordinates along bottom edge of wall
     x[0] =
       Xi_lo[0] + (Xi_hi[0] - Xi_lo[0]) *
                    axial_spacing_fct((0.5 * (1.0 + zeta[1]) + double(i_layer)) /
                                      double(Nlayer));
     x[1] = Xi_lo[1];
     // Get position vector to bottom edge of wall
     Vector<double> r_bottom(3);
     Wall_pt->position(t, x, r_bottom);
     // Scale it down to half the width
     f[0] = r_bottom[0] * 0.25 * (1.0 + zeta[0]);
     f[1] = 0.5 * r_top[1];
     // Warp it:
     double rho = 0.0; // 0.25*(1.0+zeta[0]);
     f[2] = x[0] + rho * (r_bottom[2] - x[0]);
     // f[2]=r_bottom[2];
   }
References axial_spacing_fct(), f(), Nlayer, oomph::GeomObject::position(), plotPSD::t, Wall_pt, plotDoE::x, Xi_hi, Xi_lo, and Eigen::zeta().
Referenced by macro_element_boundary(), r_top_left_B(), r_top_left_D(), and r_top_left_F().
r_top_left_B()
void oomph::QuarterTubeDomain::r_top_left_B (const unsigned & t, const Vector< double > & zeta, const unsigned & i_layer, Vector< double > & f) private
Boundary of top left box macro element in layer i_layer zeta \(\in [-1,1]^2 \)
   {
     // Wall coordinates
     Vector<double> x(2);
     x[0] = Xi_lo[0] + (Xi_hi[0] - Xi_lo[0]) *
                         axial_spacing_fct(double(i_layer) / double(Nlayer));
     x[1] = Xi_hi[1] +
            (Xi_lo[1] - Xi_hi[1]) * (1.0 - Fract_mid) * 0.5 * (1.0 + zeta[0]);
     // Get position vector to wall
     Vector<double> r_wall(3);
     Wall_pt->position(t, x, r_wall);
     // Get position vector on central box
     Vector<double> zeta_central(2);
     Vector<double> r_central(3);
     zeta_central[0] = zeta[0];
     zeta_central[1] = -1.0;
     r_centr_U(t, zeta_central, i_layer, r_central);
     // Straight line across
     f[0] = r_central[0] +
            (r_wall[0] - r_central[0]) * s_squashed(0.5 * (1.0 + zeta[1]));
     f[1] = r_central[1] +
            (r_wall[1] - r_central[1]) * s_squashed(0.5 * (1.0 + zeta[1]));
     f[2] = r_central[2] +
            (r_wall[2] - r_central[2]) * s_squashed(0.5 * (1.0 + zeta[1]));
   }
References axial_spacing_fct(), f(), Fract_mid, Nlayer, oomph::GeomObject::position(), r_centr_U(), s_squashed(), plotPSD::t, Wall_pt, plotDoE::x, Xi_hi, Xi_lo, and Eigen::zeta().
Referenced by macro_element_boundary().
r_top_left_D()
void oomph::QuarterTubeDomain::r_top_left_D (const unsigned & t, const Vector< double > & zeta, const unsigned & i_layer, Vector< double > & f) private
Boundary of top left box macro element in layer i_layer zeta \(\in [-1,1]^2 \)
   {
     r_centr_U(t, zeta, i_layer, f);
   }
References f(), r_centr_U(), plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_top_left_F()
void oomph::QuarterTubeDomain::r_top_left_F (const unsigned & t, const Vector< double > & zeta, const unsigned & i_layer, Vector< double > & f) private
Boundary of top left box macro element in layer i_layer zeta \(\in [-1,1]^2 \)
   {
     // Wall coordinates
     Vector<double> x(2);
     x[0] = Xi_lo[0] + (Xi_hi[0] - Xi_lo[0]) *
                         axial_spacing_fct(double(1 + i_layer) / double(Nlayer));
     x[1] = Xi_hi[1] +
            (Xi_lo[1] - Xi_hi[1]) * (1.0 - Fract_mid) * 0.5 * (1.0 + zeta[0]);
     // Get position vector to wall
     Vector<double> r_wall(3);
     Wall_pt->position(t, x, r_wall);
     // Get position vector on central box
     Vector<double> zeta_central(2);
     Vector<double> r_central(3);
     zeta_central[0] = zeta[0];
     zeta_central[1] = 1.0;
     r_centr_U(t, zeta_central, i_layer, r_central);
     // Straight line across
     f[0] = r_central[0] +
            (r_wall[0] - r_central[0]) * s_squashed(0.5 * (1.0 + zeta[1]));
     f[1] = r_central[1] +
            (r_wall[1] - r_central[1]) * s_squashed(0.5 * (1.0 + zeta[1]));
     f[2] = r_central[2] +
            (r_wall[2] - r_central[2]) * s_squashed(0.5 * (1.0 + zeta[1]));
   }
References axial_spacing_fct(), f(), Fract_mid, Nlayer, oomph::GeomObject::position(), r_centr_U(), s_squashed(), plotPSD::t, Wall_pt, plotDoE::x, Xi_hi, Xi_lo, and Eigen::zeta().
Referenced by macro_element_boundary().
r_top_left_L()
void oomph::QuarterTubeDomain::r_top_left_L (const unsigned & t, const Vector< double > & zeta, const unsigned & i_layer, Vector< double > & f) private
Boundary of top left box macro element in layer i_layer zeta \(\in [-1,1]^2 \)
   {
     // Wall coordinates along top edge of wall
     Vector<double> x(2);
     x[0] =
       Xi_lo[0] + (Xi_hi[0] - Xi_lo[0]) *
                    axial_spacing_fct((0.5 * (1.0 + zeta[1]) + double(i_layer)) /
                                      double(Nlayer));
     x[1] = Xi_hi[1];
     // Get position vector to upper edge of wall
     Vector<double> r_top(3);
     Wall_pt->position(t, x, r_top);
     // Scale it down to half the height
     f[0] = r_top[0];
     f[1] = 0.5 * r_top[1] * (1.0 + s_squashed(0.5 * (1.0 + zeta[0])));
     // Warp it:
     double rho = s_squashed(0.5 * (1.0 + zeta[0]));
     f[2] = x[0] + rho * (r_top[2] - x[0]);
     // f[2]=r_top[2];
   }
References axial_spacing_fct(), f(), Nlayer, oomph::GeomObject::position(), s_squashed(), plotPSD::t, Wall_pt, plotDoE::x, Xi_hi, Xi_lo, and Eigen::zeta().
Referenced by macro_element_boundary().
r_top_left_R()
void oomph::QuarterTubeDomain::r_top_left_R (const unsigned & t, const Vector< double > & zeta, const unsigned & i_layer, Vector< double > & f) private
Boundary of top left box macro element in layer i_layer zeta \(\in [-1,1]^2 \)
   {
     // Swap coordinates
     Vector<double> zeta_br(2);
     zeta_br[0] = zeta[0];
     zeta_br[1] = zeta[1];
     r_bot_right_U(t, zeta_br, i_layer, f);
   }
References f(), r_bot_right_U(), plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_top_left_U()
void oomph::QuarterTubeDomain::r_top_left_U (const unsigned & t, const Vector< double > & zeta, const unsigned & i_layer, Vector< double > & f) private
Boundary of top left box macro element in layer i_layer zeta \(\in [-1,1]^2 \)
   {
     // Wall coordinates
     Vector<double> x(2);
     x[0] =
       Xi_lo[0] + (Xi_hi[0] - Xi_lo[0]) *
                    axial_spacing_fct((0.5 * (1.0 + zeta[1]) + double(i_layer)) /
                                      double(Nlayer));
     x[1] = Xi_hi[1] +
            (Xi_lo[1] - Xi_hi[1]) * (1 - Fract_mid) * 0.5 * (1.0 + zeta[0]);
     // Get position vector on wall
     Wall_pt->position(t, x, f);
   }
References axial_spacing_fct(), f(), Fract_mid, Nlayer, oomph::GeomObject::position(), plotPSD::t, Wall_pt, plotDoE::x, Xi_hi, Xi_lo, and Eigen::zeta().
Referenced by macro_element_boundary().
s_squashed()
double oomph::QuarterTubeDomain::s_squashed (const double & s) inline
Function that squashes the outer two macro elements towards the wall by mapping the input value of the "radial" macro element coordinate to the return value.
     {
       return BL_squash_fct_pt(s);
     }
References BL_squash_fct_pt, and s.
Referenced by r_bot_right_B(), r_bot_right_D(), r_bot_right_F(), r_bot_right_U(), r_top_left_B(), r_top_left_F(), and r_top_left_L().
Member Data Documentation
Axial_spacing_fct_pt
AxialSpacingFctPt oomph::QuarterTubeDomain::Axial_spacing_fct_pt private
Function pointer for function that implements axial spacing of macro elements
Referenced by axial_spacing_fct(), and axial_spacing_fct_pt().
BL_squash_fct_pt
BLSquashFctPt oomph::QuarterTubeDomain::BL_squash_fct_pt private
Function pointer for function that squashes the outer two macro elements towards the wall by mapping the input value of the "radial" macro element coordinate to the return value
Referenced by bl_squash_fct_pt(), and s_squashed().
Fract_mid
double oomph::QuarterTubeDomain::Fract_mid private
Fraction along wall where outer ring is to be divided.
Referenced by r_bot_right_B(), r_bot_right_F(), r_bot_right_R(), r_bot_right_U(), r_top_left_B(), r_top_left_F(), and r_top_left_U().
Nlayer
unsigned oomph::QuarterTubeDomain::Nlayer private
Number of layers.
Referenced by r_bot_right_B(), r_bot_right_D(), r_bot_right_F(), r_bot_right_R(), r_bot_right_U(), r_centr_B(), r_centr_D(), r_centr_F(), r_centr_L(), r_centr_R(), r_centr_U(), r_top_left_B(), r_top_left_F(), r_top_left_L(), and r_top_left_U().
Wall_pt
GeomObject* oomph::QuarterTubeDomain::Wall_pt private
Pointer to geometric object that represents the curved wall.
Referenced by r_bot_right_B(), r_bot_right_D(), r_bot_right_F(), r_bot_right_R(), r_bot_right_U(), r_centr_B(), r_centr_D(), r_centr_F(), r_centr_L(), r_centr_R(), r_centr_U(), r_top_left_B(), r_top_left_F(), r_top_left_L(), and r_top_left_U().
Xi_hi
Vector<double> oomph::QuarterTubeDomain::Xi_hi private
Upper limit for the coordinates along the wall.
Referenced by r_bot_right_B(), r_bot_right_D(), r_bot_right_F(), r_bot_right_R(), r_bot_right_U(), r_centr_B(), r_centr_D(), r_centr_F(), r_centr_L(), r_centr_R(), r_centr_U(), r_top_left_B(), r_top_left_F(), r_top_left_L(), and r_top_left_U().
Xi_lo
Vector<double> oomph::QuarterTubeDomain::Xi_lo private
Lower limit for the coordinates along the wall.
Referenced by r_bot_right_B(), r_bot_right_D(), r_bot_right_F(), r_bot_right_R(), r_bot_right_U(), r_centr_B(), r_centr_D(), r_centr_F(), r_centr_L(), r_centr_R(), r_centr_U(), r_top_left_B(), r_top_left_F(), r_top_left_L(), and r_top_left_U().
The documentation for this class was generated from the following file:
quarter_tube_domain.h