MercuryDPM: Eigen::Reverse< MatrixType, Direction > Class Template Reference
Eigen::Reverse< MatrixType, Direction > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Expression of the reverse of a vector or matrix.
#include <Reverse.h>
Public Types
typedef internal::dense_xpr_base< Reverse >::type Base
typedef internal::remove_all_t< MatrixType > NestedExpression
Public Member Functions
EIGEN_DEVICE_FUNC Reverse (const MatrixType &matrix)
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC Index innerStride () const
EIGEN_DEVICE_FUNC const internal::remove_all_t< typename MatrixType::Nested > & nestedExpression () const
Protected Types
enum {
PacketSize = internal::packet_traits<Scalar>::size , IsColMajor = !IsRowMajor , ReverseRow = (Direction == Vertical) || (Direction == BothDirections) , ReverseCol = (Direction == Horizontal) || (Direction == BothDirections) ,
OffsetRow = ReverseRow && IsColMajor ? PacketSize : 1 , OffsetCol = ReverseCol && IsRowMajor ? PacketSize : 1 , ReversePacket
}
typedef internal::reverse_packet_cond< PacketScalar, ReversePacket > reverse_packet
Protected Attributes
MatrixType::Nested m_matrix
Detailed Description
template<typename MatrixType, int Direction>
class Eigen::Reverse< MatrixType, Direction >
Expression of the reverse of a vector or matrix.
Template Parameters
MatrixType the type of the object of which we are taking the reverse
Direction defines the direction of the reverse operation, can be Vertical, Horizontal, or BothDirections
This class represents an expression of the reverse of a vector. It is the return type of MatrixBase::reverse() and VectorwiseOp::reverse() and most of the time this is the only way it is used.
See also
MatrixBase::reverse(), VectorwiseOp::reverse()
Member Typedef Documentation
Base
template<typename MatrixType , int Direction> typedef internal::dense_xpr_base<Reverse>::type Eigen::Reverse< MatrixType, Direction >::Base
NestedExpression
template<typename MatrixType , int Direction> typedef internal::remove_all_t<MatrixType> Eigen::Reverse< MatrixType, Direction >::NestedExpression
reverse_packet
template<typename MatrixType , int Direction> typedef internal::reverse_packet_cond<PacketScalar, ReversePacket> Eigen::Reverse< MatrixType, Direction >::reverse_packet protected
Member Enumeration Documentation
anonymous enum
template<typename MatrixType , int Direction> anonymous enum protected
Enumerator
PacketSize
IsColMajor
ReverseRow
ReverseCol
OffsetRow
OffsetCol
ReversePacket
        {
     PacketSize = internal::packet_traits<Scalar>::size,
     IsColMajor = !IsRowMajor,
     ReverseRow = (Direction == Vertical) || (Direction == BothDirections),
     ReverseCol = (Direction == Horizontal) || (Direction == BothDirections),
     OffsetRow = ReverseRow && IsColMajor ? PacketSize : 1,
     OffsetCol = ReverseCol && IsRowMajor ? PacketSize : 1,
     ReversePacket = (Direction == BothDirections) || ((Direction == Vertical) && IsColMajor) ||
                     ((Direction == Horizontal) && IsRowMajor)
   };
Constructor & Destructor Documentation
Reverse()
template<typename MatrixType , int Direction> EIGEN_DEVICE_FUNC Eigen::Reverse< MatrixType, Direction >::Reverse (const MatrixType & matrix) inline explicit
 : m_matrix(matrix) {}
Member Function Documentation
cols()
template<typename MatrixType , int Direction> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::Reverse< MatrixType, Direction >::cols () const inline
 { return m_matrix.cols(); }
References Eigen::Reverse< MatrixType, Direction >::m_matrix.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
innerStride()
template<typename MatrixType , int Direction> EIGEN_DEVICE_FUNC Index Eigen::Reverse< MatrixType, Direction >::innerStride () const inline
 { return -m_matrix.innerStride(); }
References Eigen::Reverse< MatrixType, Direction >::m_matrix.
nestedExpression()
template<typename MatrixType , int Direction> EIGEN_DEVICE_FUNC const internal::remove_all_t<typename MatrixType::Nested>& Eigen::Reverse< MatrixType, Direction >::nestedExpression () const inline
{
     return m_matrix;
   }
References Eigen::Reverse< MatrixType, Direction >::m_matrix.
rows()
template<typename MatrixType , int Direction> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::Reverse< MatrixType, Direction >::rows () const inline
 { return m_matrix.rows(); }
References Eigen::Reverse< MatrixType, Direction >::m_matrix.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_matrix
template<typename MatrixType , int Direction> MatrixType::Nested Eigen::Reverse< MatrixType, Direction >::m_matrix protected
Referenced by Eigen::Reverse< MatrixType, Direction >::cols(), Eigen::Reverse< MatrixType, Direction >::innerStride(), Eigen::Reverse< MatrixType, Direction >::nestedExpression(), and Eigen::Reverse< MatrixType, Direction >::rows().
The documentation for this class was generated from the following file:
Reverse.h