MercuryDPM: Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, false, true, ShortCircuitEvaluation > Struct Template Reference
Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, false, true, ShortCircuitEvaluation > Struct Template Reference
#include <Visitor.h>
Public Types
using short_circuit = short_circuit_eval_impl< Visitor, ShortCircuitEvaluation >
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void run (const Derived &mat, Visitor &visitor)
Member Typedef Documentation
short_circuit
template<typename Visitor , typename Derived , bool ShortCircuitEvaluation> using Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, false, true, ShortCircuitEvaluation >::short_circuit = short_circuit_eval_impl<Visitor, ShortCircuitEvaluation>
Member Function Documentation
run()
template<typename Visitor , typename Derived , bool ShortCircuitEvaluation> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, false, true, ShortCircuitEvaluation >::run (const Derived & mat, Visitor & visitor) inline static
{
     const Index size = mat.size();
     if (size == 0) return;
     visitor.init(mat.coeff(0), 0);
     if EIGEN_PREDICT_FALSE (short_circuit::run(visitor)) return;
     for (Index k = 1; k < size; k++) {
       visitor(mat.coeff(k), k);
       if EIGEN_PREDICT_FALSE (short_circuit::run(visitor)) return;
     }
   }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::coeff(), EIGEN_PREDICT_FALSE, k, run(), size, and Eigen::SparseMatrixBase< Derived >::size().
The documentation for this struct was generated from the following file:
Visitor.h