MercuryDPM: PSDContinuous Struct Reference
PSDContinuous Struct Reference
#include <PSDContinuous.h>
Public Member Functions
bool operator< (const double probability) const
Static Public Member Functions
static void print (std::vector< PSDContinuous > &psd)
static void validateCumulativeDistribution (std::vector< PSDContinuous > &psd)
static std::vector< PSDContinuous > createPSDFromRadiiAndProbabilities (const std::vector< double > &radius, const std::vector< double > &probability)
static void convertSubtractiveToCumulative (std::vector< PSDContinuous > &psd)
static void convertCumulativeToSubtractive (std::vector< PSDContinuous > &psd)
static void convertSubtractiveVolumeToNumber (std::vector< PSDContinuous > &psd)
static void convertCumulativeVolumeToNumber (std::vector< PSDContinuous > &psd)
static void interpolateCSD (std::vector< PSDContinuous > &psd, unsigned n)
static std::vector< PSDContinuous > getCumulativeNumberFromVolume (std::vector< PSDContinuous > psd)
static std::vector< PSDContinuous > cutoffCumulativeNumber (std::vector< PSDContinuous > psd, double quantileMin, double quantileMax, double minPolydispersity=0.1)
static std::vector< PSDContinuous > cutoffAndSqueezeCumulativeNumber (std::vector< PSDContinuous > psd, double quantileMin, double quantileMax, double squeeze, double minPolydispersity=0.1)
static void convertSubtractiveNumberToVolume (std::vector< PSDContinuous > &psd)
static void convertCumulativeNumberToVolume (std::vector< PSDContinuous > &psd)
static double getD0 (const std::vector< PSDContinuous > &psd)
static double getD10 (const std::vector< PSDContinuous > &psd)
static double getD50 (const std::vector< PSDContinuous > &psd)
static double getD90 (const std::vector< PSDContinuous > &psd)
static double getD100 (const std::vector< PSDContinuous > &psd)
static double getQuantile (std::vector< PSDContinuous > psd, double quantile)
static double getVolumetricMean (std::vector< PSDContinuous > psd)
Public Attributes
double radius
double probability
Friends
std::ostream & operator<< (std::ostream &os, const PSDContinuous &psd)
Writes to output stream.
std::istream & operator>> (std::istream &is, PSDContinuous &psd)
Reads from input stream.
Detailed Description
Stores a radius and a cumulative number density: To be used as a vector, std::vector<PSDContinuous> psd
Cumulative number density: nc_i is the number fraction of particles whose radius is less than r_i. It requires vc_0=0, vc_end=1. This variable is used as psd in MercuryDPM, as it can be interpreted as the probability that a particle's radius is is less than r_i: p(r<r_i) = nc_i.
Cumulative volume density: vc_i is the volume fraction of particles whose radius is less than r_i. It requires vc_0=0, vc_end=1
Subtractive volume density: v_i is the volume fraction of particles whose radius is between r_i-1 and r_i. It requires v_0=0, sum(v_i)=1
Sieve data: s_i is the volume fraction of particles whose radius is between r_i and r_i+1. It requires sum(s_i)=1. Property: s_i = v_i-1
Todo:
Make an object storing a vector of these values.
Member Function Documentation
convertCumulativeNumberToVolume()
void PSDContinuous::convertCumulativeNumberToVolume (std::vector< PSDContinuous > & psd) static
{
     convertCumulativeToSubtractive(psd);
     convertSubtractiveNumberToVolume(psd);
     convertSubtractiveToCumulative(psd);
 }
References convertCumulativeToSubtractive(), convertSubtractiveNumberToVolume(), and convertSubtractiveToCumulative().
Referenced by cutoffAndSqueezeCumulativeNumber(), cutoffCumulativeNumber(), and getQuantile().
convertCumulativeToSubtractive()
void PSDContinuous::convertCumulativeToSubtractive (std::vector< PSDContinuous > & psd) static
{
     //subtract cumulative probabilities
     //double v = psd[1].probability - psd[0].probability;
     double vcOld=0, vc;
     for (auto it=psd.begin(); it!=psd.end(); ++it) {
         vc = it->probability;
         it->probability -= vcOld;
         vcOld = vc;
     }
 }
Referenced by convertCumulativeNumberToVolume(), convertCumulativeVolumeToNumber(), and getVolumetricMean().
convertCumulativeVolumeToNumber()
void PSDContinuous::convertCumulativeVolumeToNumber (std::vector< PSDContinuous > & psd) static
{
     convertCumulativeToSubtractive(psd);
     convertSubtractiveVolumeToNumber(psd);
     convertSubtractiveToCumulative(psd);
 }
References convertCumulativeToSubtractive(), convertSubtractiveToCumulative(), and convertSubtractiveVolumeToNumber().
Referenced by cutoffAndSqueezeCumulativeNumber(), cutoffCumulativeNumber(), and getCumulativeNumberFromVolume().
convertSubtractiveNumberToVolume()
void PSDContinuous::convertSubtractiveNumberToVolume (std::vector< PSDContinuous > & psd) static
Todo:
should this be:
{
     logger.assert_always(psd[0].probability==0,"psd has to start with zero");
     //subtract cumulative probabilities
     double sum=0;
     for (auto it=psd.begin()+1; it!=psd.end(); ++it) {
         //const Mdouble R = it->radius;
         //const Mdouble r = (it - 1)->radius;
         //it->probability *= R*R*R*R-r*r*r*r;
         it->probability *= 0.25 * (square(it->radius) + square((it - 1)->radius)) * (it->radius + (it - 1)->radius);
         sum += it->probability;
     }
     for (auto& p : psd) {
         p.probability /= sum;
     }
 }
References logger, p, probability, radius, and Eigen::square().
Referenced by convertCumulativeNumberToVolume().
convertSubtractiveToCumulative()
void PSDContinuous::convertSubtractiveToCumulative (std::vector< PSDContinuous > & psd) static
{
     //add up probabilities
     for (auto it=psd.begin()+1; it!=psd.end(); ++it) {
         it->probability = std::min(1.0, it->probability + (it-1)->probability);
     }
     //check whether cumulative distribution adds up to one
     logger.assert_debug(fabs(psd.back().probability-1)<1e-12,"cumulative distribution needs to add up to one");
     //remove rounding errors
     psd.back().probability=1;
 }
References e(), boost::multiprecision::fabs(), logger, and min.
Referenced by convertCumulativeNumberToVolume(), and convertCumulativeVolumeToNumber().
convertSubtractiveVolumeToNumber()
void PSDContinuous::convertSubtractiveVolumeToNumber (std::vector< PSDContinuous > & psd) static
Todo:
should this be:
{
     logger.assert_always(psd[0].probability==0,"psd has to start with zero");
     //subtract cumulative probabilities
     double sum=0;
     for (auto it=psd.begin()+1; it!=psd.end(); ++it) {
         //         const Mdouble R = it->radius;
         //        const Mdouble r = (it - 1)->radius;
         //        it->probability = R==r ? 0 : it->probability/(R*R*R*R-r*r*r*r);
         it->probability /= 0.25*(square(it->radius)+square((it-1)->radius))*(it->radius+(it-1)->radius);
         sum += it->probability;
     }
     for (auto& p : psd) {
         p.probability /= sum;
     }
 }
References logger, p, probability, radius, and Eigen::square().
Referenced by convertCumulativeVolumeToNumber().
createPSDFromRadiiAndProbabilities()
std::vector< PSDContinuous > PSDContinuous::createPSDFromRadiiAndProbabilities (const std::vector< double > & radius, const std::vector< double > & probability) static
{
     logger.assert_always(radius.size()==probability.size(),"Number of radius and probability values don't match");
     std::vector<PSDContinuous> psd;
 //    psd.reserve(radius.size());
 //    for (int i = 0; i < radius.size(); ++i) {
 //        psd.push_back({radius[i],probability[i]});
 //    }
     psd.reserve(radius.size()+1);
     psd.push_back({radius.front(),0});
     for (int i = 1; i < radius.size(); ++i) {
         psd.push_back({radius[i],probability[i-1]});
     }
     psd.push_back({radius.back(),probability.back()});
     return psd;
 }
References i, logger, probability, and radius.
cutoffAndSqueezeCumulativeNumber()
static std::vector<PSDContinuous> PSDContinuous::cutoffAndSqueezeCumulativeNumber (std::vector< PSDContinuous > psd, double quantileMin, double quantileMax, double squeeze, double minPolydispersity = 0.1) inline static
{
         double r50 = 0.5*PSDContinuous::getD50(psd);
         //cut off
         psd = cutoffCumulativeNumber (psd, quantileMin, quantileMax, minPolydispersity);
         //convert to volume psd
         convertCumulativeNumberToVolume(psd);
         //squeeze psd
         for (auto& p : psd) {
             p.radius = r50+(p.radius-r50)*squeeze;
         }
         //convert to number psd
         convertCumulativeVolumeToNumber(psd);
         return psd;
     }
References convertCumulativeNumberToVolume(), convertCumulativeVolumeToNumber(), cutoffCumulativeNumber(), getD50(), and p.
cutoffCumulativeNumber()
static std::vector<PSDContinuous> PSDContinuous::cutoffCumulativeNumber (std::vector< PSDContinuous > psd, double quantileMin, double quantileMax, double minPolydispersity = 0.1) inline static
{
         double radiusMin = getQuantile(psd,quantileMin);
         double radiusMax = getQuantile(psd,quantileMax);
         //to get a minimum polydispersity at the base
         double radiusMinCut = std::min(radiusMin*(1+minPolydispersity),radiusMax);
         //convert to volume psd
         convertCumulativeNumberToVolume(psd);
         //cut off min
         while (psd.front().radius<=radiusMinCut) psd.erase(psd.begin());
         psd.insert(psd.begin(),PSDContinuous{radiusMinCut,quantileMin});
         psd.insert(psd.begin(),PSDContinuous{radiusMin,0});
         //cut off max
         while (psd.back().radius>=radiusMax) psd.pop_back();
         psd.push_back(PSDContinuous{radiusMax,quantileMax});
         psd.push_back(PSDContinuous{radiusMax,1});
         //convert to number psd
         convertCumulativeVolumeToNumber(psd);
         return psd;
     }
References convertCumulativeNumberToVolume(), convertCumulativeVolumeToNumber(), getQuantile(), and min.
Referenced by cutoffAndSqueezeCumulativeNumber().
getCumulativeNumberFromVolume()
static std::vector<PSDContinuous> PSDContinuous::getCumulativeNumberFromVolume (std::vector< PSDContinuous > psd) inline static
{
         convertCumulativeVolumeToNumber (psd);
         return psd;
     }
References convertCumulativeVolumeToNumber().
getD0()
static double PSDContinuous::getD0 (const std::vector< PSDContinuous > & psd) inline static
{
         return 2.0*getQuantile(psd,0.0);
     }
References getQuantile().
getD10()
static double PSDContinuous::getD10 (const std::vector< PSDContinuous > & psd) inline static
{
         return 2.0*getQuantile(psd,0.1);
     }
References getQuantile().
getD100()
static double PSDContinuous::getD100 (const std::vector< PSDContinuous > & psd) inline static
{
         return 2.0*getQuantile(psd,1.0);
     }
References getQuantile().
getD50()
static double PSDContinuous::getD50 (const std::vector< PSDContinuous > & psd) inline static
{
         return 2.0*getQuantile(psd,0.5);
     }
References getQuantile().
Referenced by cutoffAndSqueezeCumulativeNumber().
getD90()
static double PSDContinuous::getD90 (const std::vector< PSDContinuous > & psd) inline static
{
         return 2.0*getQuantile(psd,0.9);
     }
References getQuantile().
getQuantile()
double PSDContinuous::getQuantile (std::vector< PSDContinuous > psd, double quantile) static
{
     logger.assert_always(quantile<=1 && quantile>=0,"quantile is not between 0 and 1");
     convertCumulativeNumberToVolume(psd);
     auto high = std::lower_bound(psd.begin(),psd.end(),quantile);
     auto low = std::max(psd.begin(),high-1);
     if (high->probability==low->probability)
         return high->radius;
     else
         return low->radius + (high->radius-low->radius)*(quantile-low->probability)/(high->probability-low->probability);
 }
References convertCumulativeNumberToVolume(), logger, and max.
Referenced by cutoffCumulativeNumber(), getD0(), getD10(), getD100(), getD50(), and getD90().
getVolumetricMean()
double PSDContinuous::getVolumetricMean (std::vector< PSDContinuous > psd) static
{
     convertCumulativeToSubtractive(psd);
     double mean =0;
     for (auto it=psd.begin()+1; it!=psd.end(); ++it)
         mean += it->probability * 0.5*(cubic(it->radius)+cubic((it-1)->radius));
     mean = pow(mean,1./3.);
     return mean;
 }
References convertCumulativeToSubtractive(), mathsFunc::cubic(), Eigen::bfloat16_impl::pow(), and radius.
interpolateCSD()
void PSDContinuous::interpolateCSD (std::vector< PSDContinuous > & psd, unsigned n) static
{
     std::vector<PSDContinuous> psd2;
     for (int i = 0; i < psd.size()-1; ++i) {
         const double r0 = psd[i].radius;
         const double dr = psd[i+1].radius-psd[i].radius;
         const double p0 = psd[i].probability;
         const double dp = psd[i+1].probability-psd[i].probability;
         for (double j = 0; j < n; ++j) {
             psd2.push_back({r0+j/n*dr,p0+j/n*dp});
         }
     }
     psd2.push_back(psd.back());
     psd = psd2;
 }
References i, j, n, and p0.
operator<()
bool PSDContinuous::operator< (const double probability) const inline
required to use std::lower_bound for finding when the probability is higher than a certain value std::vector<PSDContinuous> psd; double probability; std::lower_bound(psd.begin(),psd.end(),probability);
Parameters
probability
Returns
     {
         return this->probability < probability;
     }
References probability.
print()
void PSDContinuous::print (std::vector< PSDContinuous > & psd) static
{
     if (psd.front().radius>1e-1) {
         for (const auto p : psd) {
             std::cout << p.radius << "m\t" << p.probability * 100 << "\%\n";
         }
     } else if (psd.front().radius>1e-4) {
         for (const auto p : psd) {
             std::cout << p.radius * 1000 << "mm\t" << p.probability * 100 << "\%\n";
         }
     } else {
         for (const auto p : psd) {
             std::cout << p.radius * 1e6 << "um\t" << p.probability * 100 << "\%\n";
         }
     }
 }
References e(), and p.
validateCumulativeDistribution()
void PSDContinuous::validateCumulativeDistribution (std::vector< PSDContinuous > & psd) static
{
     logger.assert_always(psd.size()>0,"psd vector is empty");
     //check whether the distribution is cumulative
     for (auto it=psd.begin()+1; it!=psd.end(); ++it) {
         logger.assert_always(it->probability >= (it-1)->probability,"psd is not cumulative");
     }
     //psd needs to start with a probability of zero
     if (psd[0].probability!=0) {
 //        logger(INFO,"adding a zero at teh beginning of the psd");
         psd.insert(psd.begin(),{psd[0].radius,0});
     }
     //psd needs to end with a probability of one
     if (psd.back().probability<1) {
         logger(INFO,"adding a one at the end of the psd");
         psd.push_back({psd.back().radius,1});
     }
 }
References INFO, logger, probability, and radius.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const PSDContinuous & psd) friend
Writes to output stream.
{
         os << psd.radius << ' ' << psd.probability;
         return os;
     }
operator>>
std::istream& operator>> (std::istream & is, PSDContinuous & psd) friend
Reads from input stream.
{
         is >> psd.radius >> psd.probability;
         return is;
     }
Member Data Documentation
probability
double PSDContinuous::probability
Referenced by convertSubtractiveNumberToVolume(), convertSubtractiveVolumeToNumber(), createPSDFromRadiiAndProbabilities(), operator<(), and validateCumulativeDistribution().
radius
double PSDContinuous::radius
Referenced by convertSubtractiveNumberToVolume(), convertSubtractiveVolumeToNumber(), createPSDFromRadiiAndProbabilities(), getVolumetricMean(), and validateCumulativeDistribution().
The documentation for this struct was generated from the following files:
PSDContinuous.h
PSDContinuous.cc