MercuryDPM: oomph::RankThreeTensor< T > Class Template Reference
oomph::RankThreeTensor< T > Class Template Reference
A Rank 3 Tensor class.
#include <matrices.h>
Public Member Functions
RankThreeTensor ()
Empty constructor.
RankThreeTensor (const RankThreeTensor &source_tensor)
Copy constructor: Deep copy.
RankThreeTensor & operator= (const RankThreeTensor &source_tensor)
Copy assignement.
RankThreeTensor (const unsigned long &n)
One parameter constructor produces a cubic nxnxn tensor.
RankThreeTensor (const unsigned long &n_index1, const unsigned long &n_index2, const unsigned long &n_index3)
Three parameter constructor, general non-square tensor.
RankThreeTensor (const unsigned long &n_index1, const unsigned long &n_index2, const unsigned long &n_index3, const T &initial_val)
Three parameter constructor, general non-square tensor.
virtual ~RankThreeTensor ()
Destructor: delete the pointers.
void resize (const unsigned long &n)
Resize to a square nxnxn tensor.
void resize (const unsigned long &n_index1, const unsigned long &n_index2, const unsigned long &n_index3)
Resize to a general tensor.
void resize (const unsigned long &n_index1, const unsigned long &n_index2, const unsigned long &n_index3, const T &initial_value)
Resize to a general tensor.
void initialise (const T &val)
Initialise all values in the tensor to val.
unsigned long nindex1 () const
Return the range of index 1 of the tensor.
unsigned long nindex2 () const
Return the range of index 2 of the tensor.
unsigned long nindex3 () const
Return the range of index 3 of the tensor.
T & operator() (const unsigned long &i, const unsigned long &j, const unsigned long &k)
Overload the round brackets to give access as a(i,j,k)
T operator() (const unsigned long &i, const unsigned long &j, const unsigned long &k) const
Overload a const version for read-only access as a(i,j,k)
Private Member Functions
void range_check (const unsigned long &i, const unsigned long &j, const unsigned long &k) const
Private Attributes
T * Tensordata
Private internal representation as pointer to data.
unsigned N
1st Tensor dimension
unsigned M
2nd Tensor dimension
unsigned P
3rd Tensor dimension
Detailed Description
template<class T>
class oomph::RankThreeTensor< T >
A Rank 3 Tensor class.
////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
RankThreeTensor() [1/5]
template<class T > oomph::RankThreeTensor< T >::RankThreeTensor () inline
Empty constructor.
 : Tensordata(0), N(0), M(0), P(0) {}
RankThreeTensor() [2/5]
template<class T > oomph::RankThreeTensor< T >::RankThreeTensor (const RankThreeTensor< T > & source_tensor) inline
Copy constructor: Deep copy.
     {
       // Set row and column lengths
       N = source_tensor.nindex1();
       M = source_tensor.nindex2();
       P = source_tensor.nindex3();
       // Assign space for the data
       Tensordata = new T[N * M * P];
       // Copy the data across from the other matrix
       for (unsigned i = 0; i < N; i++)
       {
         for (unsigned j = 0; j < M; j++)
         {
           for (unsigned k = 0; k < P; k++)
           {
             Tensordata[P * (M * i + j) + k] = source_tensor(i, j, k);
           }
         }
       }
     }
References i, j, k, oomph::RankThreeTensor< T >::M, oomph::RankThreeTensor< T >::N, oomph::RankThreeTensor< T >::nindex1(), oomph::RankThreeTensor< T >::nindex2(), oomph::RankThreeTensor< T >::nindex3(), oomph::RankThreeTensor< T >::P, and oomph::RankThreeTensor< T >::Tensordata.
RankThreeTensor() [3/5]
template<class T > oomph::RankThreeTensor< T >::RankThreeTensor (const unsigned long & n) inline
One parameter constructor produces a cubic nxnxn tensor.
     {
       // Set row and column lengths
       N = n;
       M = n;
       P = n;
       // Assign space for the n rows
       Tensordata = new T[N * M * P];
       // Initialise to zero if required
 #ifdef OOMPH_INITIALISE_DENSE_MATRICES
       initialise(T(0));
 #endif
     }
References oomph::RankThreeTensor< T >::initialise(), n, oomph::RankThreeTensor< T >::N, oomph::RankThreeTensor< T >::P, and oomph::RankThreeTensor< T >::Tensordata.
RankThreeTensor() [4/5]
template<class T > oomph::RankThreeTensor< T >::RankThreeTensor (const unsigned long & n_index1, const unsigned long & n_index2, const unsigned long & n_index3) inline
Three parameter constructor, general non-square tensor.
     {
       // Set row and column lengths
       N = n_index1;
       M = n_index2;
       P = n_index3;
       // Assign space for the n rows
       Tensordata = new T[N * M * P];
       // Initialise to zero if required
 #ifdef OOMPH_INITIALISE_DENSE_MATRICES
       initialise(T(0));
 #endif
     }
References oomph::RankThreeTensor< T >::initialise(), oomph::RankThreeTensor< T >::N, oomph::RankThreeTensor< T >::P, and oomph::RankThreeTensor< T >::Tensordata.
RankThreeTensor() [5/5]
template<class T > oomph::RankThreeTensor< T >::RankThreeTensor (const unsigned long & n_index1, const unsigned long & n_index2, const unsigned long & n_index3, const T & initial_val) inline
Three parameter constructor, general non-square tensor.
     {
       // Set row and column lengths
       N = n_index1;
       M = n_index2;
       P = n_index3;
       // Assign space for the n rows
       Tensordata = new T[N * M * P];
       // Initialise to the initial value
       initialise(initial_val);
     }
References oomph::RankThreeTensor< T >::initialise(), oomph::RankThreeTensor< T >::N, oomph::RankThreeTensor< T >::P, and oomph::RankThreeTensor< T >::Tensordata.
~RankThreeTensor()
template<class T > virtual oomph::RankThreeTensor< T >::~RankThreeTensor () inline virtual
Destructor: delete the pointers.
     {
       delete[] Tensordata;
       Tensordata = 0;
     }
References oomph::RankThreeTensor< T >::Tensordata.
Member Function Documentation
initialise()
template<class T > void oomph::RankThreeTensor< T >::initialise (const T & val) inline
Initialise all values in the tensor to val.
     {
       for (unsigned long i = 0; i < (N * M * P); ++i)
       {
         Tensordata[i] = val;
       }
     }
References i, oomph::RankThreeTensor< T >::N, oomph::RankThreeTensor< T >::P, oomph::RankThreeTensor< T >::Tensordata, and calibrate::val.
Referenced by oomph::ScalarAdvectionEquations< DIM >::dflux_du(), oomph::RankThreeTensor< T >::RankThreeTensor(), and oomph::RankThreeTensor< T >::resize().
nindex1()
template<class T > unsigned long oomph::RankThreeTensor< T >::nindex1 () const inline
Return the range of index 1 of the tensor.
     {
       return N;
     }
References oomph::RankThreeTensor< T >::N.
Referenced by oomph::RankThreeTensor< T >::operator=(), and oomph::RankThreeTensor< T >::RankThreeTensor().
nindex2()
template<class T > unsigned long oomph::RankThreeTensor< T >::nindex2 () const inline
Return the range of index 2 of the tensor.
     {
       return M;
     }
References oomph::RankThreeTensor< T >::M.
Referenced by oomph::RankThreeTensor< T >::operator=(), and oomph::RankThreeTensor< T >::RankThreeTensor().
nindex3()
template<class T > unsigned long oomph::RankThreeTensor< T >::nindex3 () const inline
Return the range of index 3 of the tensor.
     {
       return P;
     }
References oomph::RankThreeTensor< T >::P.
Referenced by oomph::RankThreeTensor< T >::operator=(), and oomph::RankThreeTensor< T >::RankThreeTensor().
operator()() [1/2]
template<class T > T& oomph::RankThreeTensor< T >::operator() (const unsigned long & i, const unsigned long & j, const unsigned long & k) inline
Overload the round brackets to give access as a(i,j,k)
     {
 #ifdef RANGE_CHECKING
       this->range_check(i, j, k);
 #endif
       return Tensordata[P * (M * i + j) + k];
     }
References i, j, k, oomph::RankThreeTensor< T >::P, oomph::RankThreeTensor< T >::range_check(), and oomph::RankThreeTensor< T >::Tensordata.
operator()() [2/2]
template<class T > T oomph::RankThreeTensor< T >::operator() (const unsigned long & i, const unsigned long & j, const unsigned long & k) const inline
Overload a const version for read-only access as a(i,j,k)
     {
 #ifdef RANGE_CHECKING
       this->range_check(i, j, k);
 #endif
       return Tensordata[P * (M * i + j) + k];
     }
References i, j, k, oomph::RankThreeTensor< T >::P, oomph::RankThreeTensor< T >::range_check(), and oomph::RankThreeTensor< T >::Tensordata.
operator=()
template<class T > RankThreeTensor& oomph::RankThreeTensor< T >::operator= (const RankThreeTensor< T > & source_tensor) inline
Copy assignement.
     {
       // Don't create a new matrix if the assignement is the identity
       if (this != &source_tensor)
       {
         // Check row and column length
         unsigned long n = source_tensor.nindex1();
         unsigned long m = source_tensor.nindex2();
         unsigned long p = source_tensor.nindex3();
         // Resie the tensor to be the same size as the old tensor
         if ((N != n) || (M != m) || (P != p))
         {
           resize(n, m, p);
         }
         // Copy entries across from the other matrix
         for (unsigned long i = 0; i < N; i++)
         {
           for (unsigned long j = 0; j < M; j++)
           {
             for (unsigned long k = 0; k < P; k++)
             {
               (*this)(i, j, k) = source_tensor(i, j, k);
             }
           }
         }
       }
       // Return reference to object itself (i.e. de-reference this pointer)
       return *this;
     }
References i, j, k, m, oomph::RankThreeTensor< T >::M, n, oomph::RankThreeTensor< T >::N, oomph::RankThreeTensor< T >::nindex1(), oomph::RankThreeTensor< T >::nindex2(), oomph::RankThreeTensor< T >::nindex3(), p, oomph::RankThreeTensor< T >::P, and oomph::RankThreeTensor< T >::resize().
range_check()
template<class T > void oomph::RankThreeTensor< T >::range_check (const unsigned long & i, const unsigned long & j, const unsigned long & k) const inline private
Range check to catch when an index is out of bounds, if so, it issues a warning message and dies by throwing an OomphLibError
     {
       if (i >= N)
       {
         std::ostringstream error_message;
         error_message << "Range Error: i=" << i << " is not in the range (0,"
                       << N - 1 << ")." << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       else if (j >= M)
       {
         std::ostringstream error_message;
         error_message << "Range Error: j=" << j << " is not in the range (0,"
                       << M - 1 << ")." << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       else if (k >= P)
       {
         std::ostringstream error_message;
         error_message << "Range Error: k=" << k << " is not in the range (0,"
                       << P - 1 << ")." << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
     }
References i, j, k, oomph::RankThreeTensor< T >::N, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::RankThreeTensor< T >::P.
Referenced by oomph::RankThreeTensor< T >::operator()().
resize() [1/3]
template<class T > void oomph::RankThreeTensor< T >::resize (const unsigned long & n) inline
Resize to a square nxnxn tensor.
     {
       resize(n, n, n);
     }
References n.
Referenced by oomph::RankThreeTensor< T >::operator=().
resize() [2/3]
template<class T > void oomph::RankThreeTensor< T >::resize (const unsigned long & n_index1, const unsigned long & n_index2, const unsigned long & n_index3) inline
Resize to a general tensor.
     {
       // If the sizes have not changed do nothing
       if ((n_index1 == N) && (n_index2 == M) && (n_index3 == P))
       {
         return;
       }
       // Store old sizes
       unsigned long n_old = N, m_old = M, p_old = P;
       // Reassign the sizes
       N = n_index1;
       M = n_index2;
       P = n_index3;
       // Store triple pointer to old matrix data
       T* temp_tensor = Tensordata;
       // Re-create Tensordata in new size
       Tensordata = new T[N * M * P];
 #ifdef OOMPH_INITIALISE_DENSE_MATRICES
       initialise(T(0));
 #endif
       // Transfer values
       unsigned long n_copy, m_copy, p_copy;
       n_copy = std::min(n_old, n_index1);
       m_copy = std::min(m_old, n_index2);
       p_copy = std::min(p_old, n_index3);
       // If matrix has values, transfer them to new matrix
       // Loop over rows
       for (unsigned long i = 0; i < n_copy; i++)
       {
         // Loop over columns
         for (unsigned long j = 0; j < m_copy; j++)
         {
           // Loop over columns
           for (unsigned long k = 0; k < p_copy; k++)
           {
             // Transfer values from temp_tensor
             Tensordata[M * P * i + P * j + k] =
               temp_tensor[m_old * p_old * i + p_old * j + k];
           }
         }
       }
       // Now kill storage for old tensor
       delete[] temp_tensor;
     }
References i, oomph::RankThreeTensor< T >::initialise(), j, k, oomph::RankThreeTensor< T >::M, min, oomph::RankThreeTensor< T >::N, oomph::RankThreeTensor< T >::P, and oomph::RankThreeTensor< T >::Tensordata.
resize() [3/3]
template<class T > void oomph::RankThreeTensor< T >::resize (const unsigned long & n_index1, const unsigned long & n_index2, const unsigned long & n_index3, const T & initial_value) inline
Resize to a general tensor.
     {
       // If the sizes have not changed do nothing
       if ((n_index1 == N) && (n_index2 == M) && (n_index3 == P))
       {
         return;
       }
       // Store old sizes
       unsigned long n_old = N, m_old = M, p_old = P;
       // Reassign the sizes
       N = n_index1;
       M = n_index2;
       P = n_index3;
       // Store triple pointer to old matrix data
       T* temp_tensor = Tensordata;
       // Re-create Tensordata in new size
       Tensordata = new T[N * M * P];
       // Initialise the newly allocated storage
       initialise(initial_value);
       // Transfer values
       unsigned long n_copy, m_copy, p_copy;
       n_copy = std::min(n_old, n_index1);
       m_copy = std::min(m_old, n_index2);
       p_copy = std::min(p_old, n_index3);
       // If matrix has values, transfer them to new matrix
       // Loop over rows
       for (unsigned long i = 0; i < n_copy; i++)
       {
         // Loop over columns
         for (unsigned long j = 0; j < m_copy; j++)
         {
           // Loop over columns
           for (unsigned long k = 0; k < p_copy; k++)
           {
             // Transfer values from temp_tensor
             Tensordata[M * P * i + P * j + k] =
               temp_tensor[m_old * p_old * i + p_old * j + k];
           }
         }
       }
       // Now kill storage for old tensor
       delete[] temp_tensor;
     }
References i, oomph::RankThreeTensor< T >::initialise(), j, k, oomph::RankThreeTensor< T >::M, min, oomph::RankThreeTensor< T >::N, oomph::RankThreeTensor< T >::P, and oomph::RankThreeTensor< T >::Tensordata.
Member Data Documentation
M
template<class T > unsigned oomph::RankThreeTensor< T >::M private
2nd Tensor dimension
Referenced by oomph::RankThreeTensor< T >::nindex2(), oomph::RankThreeTensor< T >::operator=(), oomph::RankThreeTensor< T >::RankThreeTensor(), and oomph::RankThreeTensor< T >::resize().
N
template<class T > unsigned oomph::RankThreeTensor< T >::N private
1st Tensor dimension
Referenced by oomph::RankThreeTensor< T >::initialise(), oomph::RankThreeTensor< T >::nindex1(), oomph::RankThreeTensor< T >::operator=(), oomph::RankThreeTensor< T >::range_check(), oomph::RankThreeTensor< T >::RankThreeTensor(), and oomph::RankThreeTensor< T >::resize().
P
template<class T > unsigned oomph::RankThreeTensor< T >::P private
3rd Tensor dimension
Referenced by oomph::RankThreeTensor< T >::initialise(), oomph::RankThreeTensor< T >::nindex3(), oomph::RankThreeTensor< T >::operator()(), oomph::RankThreeTensor< T >::operator=(), oomph::RankThreeTensor< T >::range_check(), oomph::RankThreeTensor< T >::RankThreeTensor(), and oomph::RankThreeTensor< T >::resize().
Tensordata
template<class T > T* oomph::RankThreeTensor< T >::Tensordata private
Private internal representation as pointer to data.
Referenced by oomph::RankThreeTensor< T >::initialise(), oomph::RankThreeTensor< T >::operator()(), oomph::RankThreeTensor< T >::RankThreeTensor(), oomph::RankThreeTensor< T >::resize(), and oomph::RankThreeTensor< T >::~RankThreeTensor().
The documentation for this class was generated from the following file:
matrices.h