MercuryDPM: Eigen::internal::generic_j1< T, float > Struct Template Reference
Eigen::internal::generic_j1< T, float > Struct Template Reference
#include <BesselFunctionsImpl.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T run (const T &x)
Member Function Documentation
run()
template<typename T > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T Eigen::internal::generic_j1< T, float >::run (const T & x) inline static
{
     /* j1f.c
      *  Bessel function of order one
      *
      *
      *
      * SYNOPSIS:
      *
      * float x, y, j1f();
      *
      * y = j1f( x );
      *
      *
      *
      * DESCRIPTION:
      *
      * Returns Bessel function of order one of the argument.
      *
      * The domain is divided into the intervals [0, 2] and
      * (2, infinity). In the first interval a polynomial approximation
      *        2
      * (w - r  ) x P(w)
      *       1
      *                     2
      * is used, where w = x  and r is the first zero of the function.
      *
      * In the second interval, the modulus and phase are approximated
      * by polynomials of the form Modulus(x) = sqrt(1/x) Q(1/x)
      * and Phase(x) = x + 1/x R(1/x^2) - 3pi/4.  The function is
      *
      *   j0(x) = Modulus(x) cos( Phase(x) ).
      *
      *
      *
      * ACCURACY:
      *
      *                      Absolute error:
      * arithmetic   domain      # trials      peak       rms
      *    IEEE      0,  2       100000       1.2e-7     2.5e-8
      *    IEEE      2, 32       100000       2.0e-7     5.3e-8
      *
      *
      */
     const float JP[] = {-4.878788132172128E-009f, 6.009061827883699E-007f, -4.541343896997497E-005f,
                         1.937383947804541E-003f, -3.405537384615824E-002f};
     const float MO1[] = {6.913942741265801E-002f,  -2.284801500053359E-001f, 3.138238455499697E-001f,
                          -2.102302420403875E-001f, 5.435364690523026E-003f,  1.493389585089498E-001f,
                          4.976029650847191E-006f,  7.978845453073848E-001f};
     const float PH1[] = {-4.497014141919556E+001f, 5.073465654089319E+001f,  -2.485774108720340E+001f,
                          7.222973196770240E+000f,  -1.544842782180211E+000f, 3.503787691653334E-001f,
                          -1.637986776941202E-001f, 3.749989509080821E-001f};
     const T Z1 = pset1<T>(1.46819706421238932572E1f);
     const T NEG_THPIO4F = pset1<T>(-2.35619449019234492885f); /* -3*pi/4 */
     T y = pabs(x);
     T z = pmul(y, y);
     T y_le_two = pmul(psub(z, Z1), pmul(x, internal::ppolevl<T, 4>::run(z, JP)));
     T q = pdiv(pset1<T>(1.0f), y);
     T w = prsqrt(y);
     T p = pmul(w, internal::ppolevl<T, 7>::run(q, MO1));
     w = pmul(q, q);
     T yn = pmadd(q, internal::ppolevl<T, 7>::run(w, PH1), NEG_THPIO4F);
     T y_gt_two = pmul(p, pcos(padd(yn, y)));
     // j1 is an odd function. This implementation differs from cephes to
     // take this fact in to account. Cephes returns -j1(x) for y > 2 range.
     y_gt_two = pselect(pcmp_lt(x, pset1<T>(0.0f)), pnegate(y_gt_two), y_gt_two);
     return pselect(pcmp_le(y, pset1<T>(2.0f)), y_le_two, y_gt_two);
   }
References p, Eigen::internal::pabs(), Eigen::internal::padd(), Eigen::internal::pcmp_le(), Eigen::internal::pcmp_lt(), Eigen::internal::pcos(), Eigen::internal::pdiv(), Eigen::internal::pmadd(), Eigen::internal::pmul(), Eigen::internal::pnegate(), Eigen::internal::prsqrt(), Eigen::internal::pselect(), Eigen::internal::psub(), Eigen::numext::q, w, plotDoE::x, and Eigen::internal::y.
The documentation for this struct was generated from the following file:
BesselFunctionsImpl.h