MercuryDPM: ExtremeOverlapWithWallsUnitTest.cpp File Reference
ExtremeOverlapWithWallsUnitTest.cpp File Reference
#include "DPMBase.h"
#include "Walls/InfiniteWall.h"
#include <iostream>
#include <Species/LinearViscoelasticSpecies.h>
#include <Logger.h>
Classes
class ExtremeOverlapWithWallsUnitTest
Compresses 2 particles (vertically) until they have an extreme overlap.
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
Start off my solving the default problem
 {
     ExtremeOverlapWithWallsUnitTest OverlapProblem;
     auto species = OverlapProblem.speciesHandler.copyAndAddObject(LinearViscoelasticSpecies());
     species->setDensity(2000);
     species->setStiffness(1e5);
     species->setDissipation(1e-2);
     OverlapProblem.setName("ExtremeOverlapWithWallsUnitTest");
     OverlapProblem.setFileType(FileType::NO_FILE);
     OverlapProblem.dataFile.setFileType(FileType::ONE_FILE);
     //OverlapProblem.wallHandler.setWriteVTK(true);
     //OverlapProblem.setParticlesWriteVTK(true);
     OverlapProblem.setSaveCount(1000);
     OverlapProblem.setDimension(3);
     OverlapProblem.setTimeStep(1e-7);
     OverlapProblem.setTimeMax(0.01);
     // OverlapProblem.dataFile.getFstream().precision(10);
     OverlapProblem.solve(argc,argv);
     Vec3D position = OverlapProblem.particleHandler.getObject(0)->getPosition();
     helpers::check(position,Vec3D(0.00402345, 0, 0), 1e-8,"First particle position");
     position = OverlapProblem.particleHandler.getObject(1)->getPosition();
     helpers::check(position,Vec3D(0.00901182, 0, 0), 1e-8,"Second particle position");
     return 0;
 }
References helpers::check(), BaseHandler< T >::copyAndAddObject(), DPMBase::dataFile, e(), BaseHandler< T >::getObject(), BaseInteractable::getPosition(), NO_FILE, ONE_FILE, DPMBase::particleHandler, DPMBase::setDimension(), DPMBase::setFileType(), File::setFileType(), DPMBase::setName(), DPMBase::setSaveCount(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), DPMBase::solve(), and DPMBase::speciesHandler.