MercuryDPM: Eigen::internal::conj_helper< LhsType, RhsType, ConjLhs, ConjRhs > Struct Template Reference
Eigen::internal::conj_helper< LhsType, RhsType, ConjLhs, ConjRhs > Struct Template Reference
#include <ConjHelper.h>
Public Types
typedef ScalarBinaryOpTraits< LhsType, RhsType >::ReturnType ResultType
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ResultType pmadd (const LhsType &x, const RhsType &y, const ResultType &c) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ResultType pmul (const LhsType &x, const RhsType &y) const
Member Typedef Documentation
ResultType
template<typename LhsType , typename RhsType , bool ConjLhs, bool ConjRhs> typedef ScalarBinaryOpTraits<LhsType, RhsType>::ReturnType Eigen::internal::conj_helper< LhsType, RhsType, ConjLhs, ConjRhs >::ResultType
Member Function Documentation
pmadd()
template<typename LhsType , typename RhsType , bool ConjLhs, bool ConjRhs> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ResultType Eigen::internal::conj_helper< LhsType, RhsType, ConjLhs, ConjRhs >::pmadd (const LhsType & x, const RhsType & y, const ResultType & c) const inline
{
     return this->pmul(x, y) + c;
   }
References calibrate::c, Eigen::internal::conj_helper< LhsType, RhsType, ConjLhs, ConjRhs >::pmul(), and Eigen::internal::y.
Referenced by Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::acc(), Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, ConjRhs_, Arch, PacketSize_ >::acc(), Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::madd(), Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::run(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::run(), and Eigen::internal::selfadjoint_matrix_vector_product< Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, Version >::run().
pmul()
template<typename LhsType , typename RhsType , bool ConjLhs, bool ConjRhs> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ResultType Eigen::internal::conj_helper< LhsType, RhsType, ConjLhs, ConjRhs >::pmul (const LhsType & x, const RhsType & y) const inline
{
     return conj_if<ConjLhs>()(x) * conj_if<ConjRhs>()(y);
   }
References plotDoE::x, and Eigen::internal::y.
Referenced by Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::madd(), Eigen::internal::scalar_conj_product_op< LhsScalar, RhsScalar >::operator()(), Eigen::internal::scalar_conj_product_op< LhsScalar, RhsScalar >::packetOp(), Eigen::internal::conj_helper< LhsScalar, RhsScalar, true, true >::pmadd(), Eigen::internal::conj_helper< LhsType, RhsType, ConjLhs, ConjRhs >::pmadd(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::run(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::run(), Eigen::internal::selfadjoint_matrix_vector_product< Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, Version >::run(), and Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, true >::run().
The documentation for this struct was generated from the following file:
ConjHelper.h