MercuryDPM: oomph::ChannelWithLeafletDomain Class Reference
oomph::ChannelWithLeafletDomain Class Reference
#include <channel_with_leaflet_domain.h>
Public Member Functions
ChannelWithLeafletDomain (GeomObject *leaflet_pt, const double &lleft, const double &lright, const double &hleaflet, const double &htot, const unsigned &nleft, const unsigned &nright, const unsigned &ny1, const unsigned &ny2)
~ChannelWithLeafletDomain ()
Destructor: Empty; cleanup done in base class.
double htot ()
Total height of domain (width of channel)
double hleaflet ()
Height of leaflet.
double lleft ()
Length of domain to the left of leaflet.
double lright ()
Length of domain to the right of leaflet.
GeomObject *& leaflet_pt ()
Pointer to the wall.
void macro_element_boundary (const unsigned &t, const unsigned &imacro, const unsigned &idirect, const Vector< double > &zeta, Vector< double > &r)
Parametrisation of macro element boundaries.
Public Member Functions inherited from oomph::Domain
Domain ()
Constructor.
Domain (const Domain &)=delete
Broken copy constructor.
void operator= (const Domain &)=delete
Broken assignment operator.
virtual ~Domain ()
MacroElement * macro_element_pt (const unsigned &i)
Access to i-th macro element.
unsigned nmacro_element ()
Number of macro elements in domain.
void output (const std::string &filename, const unsigned &nplot)
Output macro elements.
void output (std::ostream &outfile, const unsigned &nplot)
Output macro elements.
virtual void macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void output_macro_element_boundaries (const std::string &filename, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
void output_macro_element_boundaries (std::ostream &outfile, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
virtual void dmacro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void dmacro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void dmacro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void d2macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
Protected Member Functions
void macro_bound_I_N (const unsigned &t, const Vector< double > &zeta, Vector< double > &r, const unsigned &i, const unsigned &j)
Helper function.
void macro_bound_I_S (const unsigned &t, const Vector< double > &zeta, Vector< double > &r, const unsigned &i, const unsigned &j)
Helper function.
void macro_bound_I_W (const unsigned &t, const Vector< double > &zeta, Vector< double > &r, const unsigned &i, const unsigned &j)
Helper function.
void macro_bound_I_E (const unsigned &t, const Vector< double > &zeta, Vector< double > &r, const unsigned &i, const unsigned &j)
Helper function.
void macro_bound_II_N (const unsigned &t, const Vector< double > &zeta, Vector< double > &r, const unsigned &i, const unsigned &j)
Helper function.
void macro_bound_II_S (const unsigned &t, const Vector< double > &zeta, Vector< double > &r, const unsigned &i, const unsigned &j)
Helper function.
void macro_bound_II_W (const unsigned &t, const Vector< double > &zeta, Vector< double > &r, const unsigned &i, const unsigned &j)
Helper function.
void macro_bound_II_E (const unsigned &t, const Vector< double > &zeta, Vector< double > &r, const unsigned &i, const unsigned &j)
Helper function.
void macro_bound_III_N (const unsigned &t, const Vector< double > &zeta, Vector< double > &r, const unsigned &i, const unsigned &j)
Helper function.
void macro_bound_III_S (const unsigned &t, const Vector< double > &zeta, Vector< double > &r, const unsigned &i, const unsigned &j)
Helper function.
void macro_bound_III_W (const unsigned &t, const Vector< double > &zeta, Vector< double > &r, const unsigned &i, const unsigned &j)
Helper function.
void macro_bound_III_E (const unsigned &t, const Vector< double > &zeta, Vector< double > &r, const unsigned &i, const unsigned &j)
Helper function.
void macro_bound_IV_N (const unsigned &t, const Vector< double > &zeta, Vector< double > &r, const unsigned &i, const unsigned &j)
Helper function.
void macro_bound_IV_S (const unsigned &t, const Vector< double > &zeta, Vector< double > &r, const unsigned &i, const unsigned &j)
Helper function.
void macro_bound_IV_W (const unsigned &t, const Vector< double > &zeta, Vector< double > &r, const unsigned &i, const unsigned &j)
Helper function.
void macro_bound_IV_E (const unsigned &t, const Vector< double > &zeta, Vector< double > &r, const unsigned &i, const unsigned &j)
Helper function.
void slanted_bound_up (const unsigned &t, const Vector< double > &zeta, Vector< double > &r)
Helper function.
Protected Attributes
double Lright
Length of the domain to the right of the leaflet.
double Lleft
Length of the domain to the left of the leaflet.
double Hleaflet
Lagrangian coordinate at end of leaflet.
double Htot
Total width of the channel.
unsigned Nright
Number of macro element columnns to the right of the leaflet.
unsigned Nleft
Number of macro element columns to the left of the leaflet.
unsigned Ny1
Number of macro element rows up to the end of the leaflet.
unsigned Ny2
Number of macro element rows above the leaflet.
double X_0
GeomObject * Leaflet_pt
Pointer to leaflet.
Protected Attributes inherited from oomph::Domain
Vector< MacroElement * > Macro_element_pt
Vector of pointers to macro elements.
Detailed Description
Rectangular domain with a leaflet blocking the lower half
Constructor & Destructor Documentation
ChannelWithLeafletDomain()
oomph::ChannelWithLeafletDomain::ChannelWithLeafletDomain (GeomObject * leaflet_pt, const double & lleft, const double & lright, const double & hleaflet, const double & htot, const unsigned & nleft, const unsigned & nright, const unsigned & ny1, const unsigned & ny2) inline
Constructor: Pass pointer to GeomObject that represents the leaflet, the length of the domain to left and right of the leaflet, the height of the leaflet and the overall height of the channel, the number of element columns to the left and right of the leaflet, the number of rows of elements from the bottom of the channel to the end of the leaflet, the number of rows of elements above the end of the leaflet.
     {
       // Copy assignments into private storage
       Lleft = lleft;
       Lright = lright;
       Hleaflet = hleaflet;
       Htot = htot;
       Nleft = nleft;
       Nright = nright;
       Ny1 = ny1;
       Ny2 = ny2;
       Leaflet_pt = leaflet_pt;
       // Store origin of leaflet for fast reference
       Vector<double> zeta(1);
       zeta[0] = 0.0;
       Vector<double> r(2);
       Leaflet_pt->position(zeta, r);
       X_0 = r[0];
       // Number of macro elements
       unsigned nmacro = (Ny1 + Ny2) * (Nleft + Nright);
       Macro_element_pt.resize(nmacro);
       // Build the 2D macro elements
       for (unsigned i = 0; i < nmacro; i++)
       {
         Macro_element_pt[i] = new QMacroElement<2>(this, i);
       }
     }
References hleaflet(), Hleaflet, htot(), Htot, i, leaflet_pt(), Leaflet_pt, lleft(), Lleft, lright(), Lright, oomph::Domain::Macro_element_pt, Nleft, Nright, Ny1, Ny2, oomph::GeomObject::position(), UniformPSDSelfTest::r, X_0, and Eigen::zeta().
~ChannelWithLeafletDomain()
oomph::ChannelWithLeafletDomain::~ChannelWithLeafletDomain () inline
Destructor: Empty; cleanup done in base class.
 {}
Member Function Documentation
hleaflet()
double oomph::ChannelWithLeafletDomain::hleaflet () inline
Height of leaflet.
     {
       return Hleaflet;
     }
References Hleaflet.
Referenced by ChannelWithLeafletDomain().
htot()
double oomph::ChannelWithLeafletDomain::htot () inline
Total height of domain (width of channel)
     {
       return Htot;
     }
References Htot.
Referenced by ChannelWithLeafletDomain().
leaflet_pt()
GeomObject*& oomph::ChannelWithLeafletDomain::leaflet_pt () inline
Pointer to the wall.
     {
       return Leaflet_pt;
     };
References Leaflet_pt.
Referenced by ChannelWithLeafletDomain().
lleft()
double oomph::ChannelWithLeafletDomain::lleft () inline
Length of domain to the left of leaflet.
     {
       return Lleft;
     }
References Lleft.
Referenced by ChannelWithLeafletDomain().
lright()
double oomph::ChannelWithLeafletDomain::lright () inline
Length of domain to the right of leaflet.
     {
       return Lright;
     }
References Lright.
Referenced by ChannelWithLeafletDomain().
macro_bound_I_E()
void oomph::ChannelWithLeafletDomain::macro_bound_I_E (const unsigned & t, const Vector< double > & zeta, Vector< double > & r, const unsigned & i, const unsigned & j) protected
Helper function.
Helper function for eastern boundary in lower left region.
////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
Final expression of r
   {
     // Find x,y on the wall corresponding to the position of the macro element
     // xi_wall varies from xi0 to xi1 on the wall
     double xi0, xi1;
     xi0 = double(i) * Hleaflet / double(Ny1);
     xi1 = double(i + 1) * Hleaflet / double(Ny1);
     Vector<double> xi_wall(1);
     xi_wall[0] = xi0 + (1.0 + zeta[0]) / 2.0 * (xi1 - xi0);
     Vector<double> r_wall(2);
     Leaflet_pt->position(t, xi_wall, r_wall);
     // Find x,y on a vertical line corresponding
     // to the position of the macro element
     // the vertical line goes from y0 to y1
     double y0, y1;
     y0 = double(i) * Hleaflet / double(Ny1);
     y1 = double(i + 1) * Hleaflet / double(Ny1);
     Vector<double> r_vert(2);
     r_vert[0] = -Lleft + X_0;
     r_vert[1] = y0 + (1.0 + zeta[0]) / 2.0 * (y1 - y0);
     // Parameter with value 0 in -Lleft and value 1 on the wall.
     double s = double(j + 1) / double(Nleft);
     r[0] = r_vert[0] + s * (r_wall[0] - r_vert[0]);
     r[1] = r_vert[1] + s * (r_wall[1] - r_vert[1]);
   }
References Hleaflet, i, j, Leaflet_pt, Lleft, Nleft, Ny1, oomph::GeomObject::position(), UniformPSDSelfTest::r, s, plotPSD::t, X_0, and Eigen::zeta().
Referenced by macro_bound_I_N(), macro_bound_I_S(), and macro_element_boundary().
macro_bound_I_N()
void oomph::ChannelWithLeafletDomain::macro_bound_I_N (const unsigned & t, const Vector< double > & zeta, Vector< double > & r, const unsigned & i, const unsigned & j) protected
Helper function.
Helper function for northern boundary in lower left region.
   {
     // Find the coordinates of the two corners of the north boundary
     Vector<double> xi(1);
     Vector<double> r_left(2);
     Vector<double> r_right(2);
     xi[0] = 1;
     macro_bound_I_W(t, xi, r_left, i, j);
     macro_bound_I_E(t, xi, r_right, i, j);
     // Connect those two points with a straight line
     r[0] = r_left[0] + (1.0 + zeta[0]) / 2.0 * (r_right[0] - r_left[0]);
     r[1] = r_left[1] + (1.0 + zeta[0]) / 2.0 * (r_right[1] - r_left[1]);
   }
References i, j, macro_bound_I_E(), macro_bound_I_W(), UniformPSDSelfTest::r, plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
macro_bound_I_S()
void oomph::ChannelWithLeafletDomain::macro_bound_I_S (const unsigned & t, const Vector< double > & zeta, Vector< double > & r, const unsigned & i, const unsigned & j) protected
Helper function.
Helper function for southern boundary in lower left region.
Find the coordinates of the two corners of the south boundary
   {
     Vector<double> xi(1);
     Vector<double> r_left(2);
     Vector<double> r_right(2);
     xi[0] = -1.0;
     macro_bound_I_W(t, xi, r_left, i, j);
     macro_bound_I_E(t, xi, r_right, i, j);
     // Connect those two points with a straight line
     r[0] = r_left[0] + (1.0 + zeta[0]) / 2.0 * (r_right[0] - r_left[0]);
     r[1] = r_left[1] + (1.0 + zeta[0]) / 2.0 * (r_right[1] - r_left[1]);
   }
References i, j, macro_bound_I_E(), macro_bound_I_W(), UniformPSDSelfTest::r, plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
macro_bound_I_W()
void oomph::ChannelWithLeafletDomain::macro_bound_I_W (const unsigned & t, const Vector< double > & zeta, Vector< double > & r, const unsigned & i, const unsigned & j) protected
Helper function.
Helper function for western boundary in lower left region.
Final expression of r
   {
     // Find x,y on the wall corresponding to the position of the macro element
     // xi_wall varies from xi0 to xi1 on the wall
     double xi0, xi1;
     xi0 = double(i) * Hleaflet / double(Ny1);
     xi1 = double(i + 1) * Hleaflet / double(Ny1);
     Vector<double> xi_wall(1);
     xi_wall[0] = xi0 + (1.0 + zeta[0]) / 2.0 * (xi1 - xi0);
     Vector<double> r_wall(2);
     Leaflet_pt->position(t, xi_wall, r_wall);
     // Find x,y on a vertical line corresponding
     // to the position of the macro element
     // the vertical line goes from y0 to y1
     double y0, y1;
     y0 = double(i) * Hleaflet / double(Ny1);
     y1 = double(i + 1) * Hleaflet / double(Ny1);
     Vector<double> r_vert(2);
     r_vert[0] = -Lleft + X_0;
     r_vert[1] = y0 + (1.0 + zeta[0]) / 2.0 * (y1 - y0);
     // Parameter with value 0 in -Lleft and value 1 on the wall.
     double s = double(j) / double(Nleft);
     r[0] = r_vert[0] + s * (r_wall[0] - r_vert[0]);
     r[1] = r_vert[1] + s * (r_wall[1] - r_vert[1]);
   }
References Hleaflet, i, j, Leaflet_pt, Lleft, Nleft, Ny1, oomph::GeomObject::position(), UniformPSDSelfTest::r, s, plotPSD::t, X_0, and Eigen::zeta().
Referenced by macro_bound_I_N(), macro_bound_I_S(), and macro_element_boundary().
macro_bound_II_E()
void oomph::ChannelWithLeafletDomain::macro_bound_II_E (const unsigned & t, const Vector< double > & zeta, Vector< double > & r, const unsigned & i, const unsigned & j) protected
Helper function.
Helper function for eastern boundary in lower right region.
////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
Final expression of r
   {
     // Find x,y on the wall corresponding to the position of the macro element
     // xi_wall varies from xi0 to xi1 on the wall
     double xi0, xi1;
     xi0 = double(i) * Hleaflet / double(Ny1);
     xi1 = double(i + 1) * Hleaflet / double(Ny1);
     Vector<double> xi_wall(1);
     xi_wall[0] = xi0 + (1.0 + zeta[0]) / 2.0 * (xi1 - xi0);
     Vector<double> r_wall(2);
     Leaflet_pt->position(t, xi_wall, r_wall);
     // Find x,y on a vertical line corresponding
     // to the position of the macro element
     // the vertical line goes from y0 to y1
     double y0, y1;
     y0 = double(i) * Hleaflet / double(Ny1);
     y1 = double(i + 1) * Hleaflet / double(Ny1);
     Vector<double> r_vert(2);
     r_vert[0] = Lright + X_0;
     r_vert[1] = y0 + (1.0 + zeta[0]) / 2.0 * (y1 - y0);
     // Parameter with value 0 in Lright and value 1 on the wall.
     double s = double(Nright - j - 1) / double(Nright); /***Change****/
     r[0] = r_vert[0] + s * (r_wall[0] - r_vert[0]);
     r[1] = r_vert[1] + s * (r_wall[1] - r_vert[1]);
   }
References Hleaflet, i, j, Leaflet_pt, Lright, Nright, Ny1, oomph::GeomObject::position(), UniformPSDSelfTest::r, s, plotPSD::t, X_0, and Eigen::zeta().
Referenced by macro_bound_II_N(), macro_bound_II_S(), and macro_element_boundary().
macro_bound_II_N()
void oomph::ChannelWithLeafletDomain::macro_bound_II_N (const unsigned & t, const Vector< double > & zeta, Vector< double > & r, const unsigned & i, const unsigned & j) protected
Helper function.
Helper function for northern boundary in lower right region.
   {
     // Find the coordinates of the two corners of the north boundary
     Vector<double> xi(1);
     Vector<double> r_left(2);
     Vector<double> r_right(2);
     xi[0] = 1;
     macro_bound_II_W(t, xi, r_left, i, j);
     macro_bound_II_E(t, xi, r_right, i, j);
     // Connect those two points with a straight line
     r[0] = r_left[0] + (1.0 + zeta[0]) / 2.0 * (r_right[0] - r_left[0]);
     r[1] = r_left[1] + (1.0 + zeta[0]) / 2.0 * (r_right[1] - r_left[1]);
   }
References i, j, macro_bound_II_E(), macro_bound_II_W(), UniformPSDSelfTest::r, plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
macro_bound_II_S()
void oomph::ChannelWithLeafletDomain::macro_bound_II_S (const unsigned & t, const Vector< double > & zeta, Vector< double > & r, const unsigned & i, const unsigned & j) protected
Helper function.
Helper function for southern boundary in lower right region.
   {
     // Find the coordinates of the two corners of the south boundary
     Vector<double> xi(1);
     Vector<double> r_left(2);
     Vector<double> r_right(2);
     xi[0] = -1.0;
     macro_bound_II_W(t, xi, r_left, i, j);
     macro_bound_II_E(t, xi, r_right, i, j);
     // Connect those two points with a straight line
     r[0] = r_left[0] + (1.0 + zeta[0]) / 2.0 * (r_right[0] - r_left[0]);
     r[1] = r_left[1] + (1.0 + zeta[0]) / 2.0 * (r_right[1] - r_left[1]);
   }
References i, j, macro_bound_II_E(), macro_bound_II_W(), UniformPSDSelfTest::r, plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
macro_bound_II_W()
void oomph::ChannelWithLeafletDomain::macro_bound_II_W (const unsigned & t, const Vector< double > & zeta, Vector< double > & r, const unsigned & i, const unsigned & j) protected
Helper function.
Helper function for western boundary in lower right region.
   {
     // Abscissa of the origin of the boudary east
     // Find x,y on the wall corresponding to the position of the macro element
     // xi_wall varies from xi0 to xi1 on the wall
     double xi0, xi1;
     xi0 = double(i) * Hleaflet / double(Ny1);
     xi1 = double(i + 1) * Hleaflet / double(Ny1);
     Vector<double> xi_wall(1);
     xi_wall[0] = xi0 + (1.0 + zeta[0]) / 2.0 * (xi1 - xi0);
     Vector<double> r_wall(2);
     Leaflet_pt->position(t, xi_wall, r_wall);
     // Find x,y on a vertical line corresponding
     // to the position of the macro element
     // the vertical line goes from y0 to y1
     double y0, y1;
     y0 = double(i) * Hleaflet / double(Ny1);
     y1 = double(i + 1) * Hleaflet / double(Ny1);
     Vector<double> r_vert(2);
     r_vert[0] = Lright + X_0;
     r_vert[1] = y0 + (1.0 + zeta[0]) / 2.0 * (y1 - y0);
     // Parameter with value 0 in -Lleft and value 1 on the wall.
     double s = double(Nright - j) / double(Nright); /***Change****/
     // Final expression of r
     r[0] = r_vert[0] + s * (r_wall[0] - r_vert[0]);
     r[1] = r_vert[1] + s * (r_wall[1] - r_vert[1]);
   }
References Hleaflet, i, j, Leaflet_pt, Lright, Nright, Ny1, oomph::GeomObject::position(), UniformPSDSelfTest::r, s, plotPSD::t, X_0, and Eigen::zeta().
Referenced by macro_bound_II_N(), macro_bound_II_S(), and macro_element_boundary().
macro_bound_III_E()
void oomph::ChannelWithLeafletDomain::macro_bound_III_E (const unsigned & t, const Vector< double > & zeta, Vector< double > & r, const unsigned & i, const unsigned & j) protected
Helper function.
Helper function for eastern boundary in upper left region.
Final expression of r
   {
     // Find x,y on the slanted straight line (SSL) corresponding to
     // the position of the macro element
     // xi_line varies from xi0 to xi1 on the SSL
     double xi0, xi1;
     xi0 = double(i) / double(Ny2);
     xi1 = double(i + 1) / double(Ny2);
     Vector<double> xi_line(1);
     xi_line[0] = xi0 + (1.0 + zeta[0]) / 2.0 * (xi1 - xi0);
     Vector<double> r_line(2);
     slanted_bound_up(t, xi_line, r_line);
     // Find x,y on a vertical line corresponding
     // to the position of the macro element
     // the vertical line goes from y0 to y1
     double y0, y1;
     y0 = double(i) * (Htot - Hleaflet) / double(Ny2) + Hleaflet;
     y1 = double(i + 1) * (Htot - Hleaflet) / double(Ny2) + Hleaflet;
     ;
     Vector<double> r_vert(2);
     r_vert[0] = -Lleft + X_0;
     r_vert[1] = y0 + (1.0 + zeta[0]) / 2.0 * (y1 - y0);
     // Parameter with value 0 in Lright and value 1 on the wall.
     double s = double(j + 1) / double(Nleft); /***Change****/
     r[0] = r_vert[0] + s * (r_line[0] - r_vert[0]);
     r[1] = r_vert[1] + s * (r_line[1] - r_vert[1]);
   }
References Hleaflet, Htot, i, j, Lleft, Nleft, Ny2, UniformPSDSelfTest::r, s, slanted_bound_up(), plotPSD::t, X_0, and Eigen::zeta().
Referenced by macro_bound_III_N(), macro_bound_III_S(), and macro_element_boundary().
macro_bound_III_N()
void oomph::ChannelWithLeafletDomain::macro_bound_III_N (const unsigned & t, const Vector< double > & zeta, Vector< double > & r, const unsigned & i, const unsigned & j) protected
Helper function.
Helper function for northern boundary in upper left region.
   {
     // Find the coordinates of the two corners of the north boundary
     Vector<double> xi(1);
     Vector<double> r_left(2);
     Vector<double> r_right(2);
     xi[0] = 1;
     macro_bound_III_W(t, xi, r_left, i, j);
     macro_bound_III_E(t, xi, r_right, i, j);
     // Connect those two points with a straight line
     r[0] = r_left[0] + (1.0 + zeta[0]) / 2.0 * (r_right[0] - r_left[0]);
     r[1] = r_left[1] + (1.0 + zeta[0]) / 2.0 * (r_right[1] - r_left[1]);
   }
References i, j, macro_bound_III_E(), macro_bound_III_W(), UniformPSDSelfTest::r, plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
macro_bound_III_S()
void oomph::ChannelWithLeafletDomain::macro_bound_III_S (const unsigned & t, const Vector< double > & zeta, Vector< double > & r, const unsigned & i, const unsigned & j) protected
Helper function.
Helper function for southern boundary in upper left region.
   {
     // Find the coordinates of the two corners of the south boundary
     Vector<double> xi(1);
     Vector<double> r_left(2);
     Vector<double> r_right(2);
     xi[0] = -1;
     macro_bound_III_W(t, xi, r_left, i, j);
     macro_bound_III_E(t, xi, r_right, i, j);
     // Connect those two points with a straight line
     r[0] = r_left[0] + (1.0 + zeta[0]) / 2.0 * (r_right[0] - r_left[0]);
     r[1] = r_left[1] + (1.0 + zeta[0]) / 2.0 * (r_right[1] - r_left[1]);
   }
References i, j, macro_bound_III_E(), macro_bound_III_W(), UniformPSDSelfTest::r, plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
macro_bound_III_W()
void oomph::ChannelWithLeafletDomain::macro_bound_III_W (const unsigned & t, const Vector< double > & zeta, Vector< double > & r, const unsigned & i, const unsigned & j) protected
Helper function.
Helper function for western boundary in upper left region.
   {
     // Find x,y on the slanted straight line (SSL) corresponding to
     // the position of the macro element
     // xi_line varies from xi0 to xi1 on the SSL
     double xi0, xi1;
     xi0 = double(i) / double(Ny2);
     xi1 = double(i + 1) / double(Ny2);
     Vector<double> xi_line(1);
     xi_line[0] = xi0 + (1.0 + zeta[0]) / 2.0 * (xi1 - xi0);
     Vector<double> r_line(2);
     slanted_bound_up(t, xi_line, r_line);
     // Find x,y on a vertical line corresponding
     // to the position of the macro element
     // the vertical line goes from y0 to y1
     double y0, y1;
     y0 = double(i) * (Htot - Hleaflet) / double(Ny2) + Hleaflet;
     y1 = double(i + 1) * (Htot - Hleaflet) / double(Ny2) + Hleaflet;
     ;
     Vector<double> r_vert(2);
     r_vert[0] = -Lleft + X_0;
     r_vert[1] = y0 + (1.0 + zeta[0]) / 2.0 * (y1 - y0);
     // Parameter with value 0 in Lright and value 1 on the wall.
     double s = double(j) / double(Nleft); /***Change****/
     // Final expression of r
     r[0] = r_vert[0] + s * (r_line[0] - r_vert[0]);
     r[1] = r_vert[1] + s * (r_line[1] - r_vert[1]);
   }
References Hleaflet, Htot, i, j, Lleft, Nleft, Ny2, UniformPSDSelfTest::r, s, slanted_bound_up(), plotPSD::t, X_0, and Eigen::zeta().
Referenced by macro_bound_III_N(), macro_bound_III_S(), and macro_element_boundary().
macro_bound_IV_E()
void oomph::ChannelWithLeafletDomain::macro_bound_IV_E (const unsigned & t, const Vector< double > & zeta, Vector< double > & r, const unsigned & i, const unsigned & j) protected
Helper function.
Helper function for eastern boundary in upper right region.
////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
   {
     // Find x,y on the slanted straight line (SSL) corresponding to
     // the position of the macro element
     // xi_line varies from xi0 to xi1 on the SSL
     double xi0, xi1;
     xi0 = double(i) / double(Ny2);
     xi1 = double(i + 1) / double(Ny2);
     Vector<double> xi_line(1);
     xi_line[0] = xi0 + (1.0 + zeta[0]) / 2.0 * (xi1 - xi0);
     Vector<double> r_line(2);
     slanted_bound_up(t, xi_line, r_line);
     // Find x,y on a vertical line corresponding
     // to the position of the macro element
     // the vertical line goes from y0 to y1
     double y0, y1;
     y0 = double(i) * (Htot - Hleaflet) / double(Ny2) + Hleaflet;
     y1 = double(i + 1) * (Htot - Hleaflet) / double(Ny2) + Hleaflet;
     ;
     Vector<double> r_vert(2);
     r_vert[0] = Lright + X_0;
     r_vert[1] = y0 + (1.0 + zeta[0]) / 2.0 * (y1 - y0);
     // Parameter with value 0 in Lright and value 1 on the wall.
     double s = double(Nright - j - 1) / double(Nright); /***Change****/
     // Final expression of r
     r[0] = r_vert[0] + s * (r_line[0] - r_vert[0]);
     r[1] = r_vert[1] + s * (r_line[1] - r_vert[1]);
   }
References Hleaflet, Htot, i, j, Lright, Nright, Ny2, UniformPSDSelfTest::r, s, slanted_bound_up(), plotPSD::t, X_0, and Eigen::zeta().
Referenced by macro_bound_IV_N(), macro_bound_IV_S(), and macro_element_boundary().
macro_bound_IV_N()
void oomph::ChannelWithLeafletDomain::macro_bound_IV_N (const unsigned & t, const Vector< double > & zeta, Vector< double > & r, const unsigned & i, const unsigned & j) protected
Helper function.
Helper function for northern boundary in upper right region.
   {
     // Find the coordinates of the two corners of the north boundary
     Vector<double> xi(1);
     Vector<double> r_left(2);
     Vector<double> r_right(2);
     xi[0] = 1;
     macro_bound_IV_W(t, xi, r_left, i, j);
     macro_bound_IV_E(t, xi, r_right, i, j);
     // Connect those two points with a straight line
     r[0] = r_left[0] + (1.0 + zeta[0]) / 2.0 * (r_right[0] - r_left[0]);
     r[1] = r_left[1] + (1.0 + zeta[0]) / 2.0 * (r_right[1] - r_left[1]);
   }
References i, j, macro_bound_IV_E(), macro_bound_IV_W(), UniformPSDSelfTest::r, plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
macro_bound_IV_S()
void oomph::ChannelWithLeafletDomain::macro_bound_IV_S (const unsigned & t, const Vector< double > & zeta, Vector< double > & r, const unsigned & i, const unsigned & j) protected
Helper function.
Helper function for southern boundary in upper right region.
   {
     // Find the coordinates of the two corners of the south boundary
     Vector<double> xi(1);
     Vector<double> r_left(2);
     Vector<double> r_right(2);
     xi[0] = -1;
     macro_bound_IV_W(t, xi, r_left, i, j);
     macro_bound_IV_E(t, xi, r_right, i, j);
     // Connect those two points with a straight line
     r[0] = r_left[0] + (1.0 + zeta[0]) / 2.0 * (r_right[0] - r_left[0]);
     r[1] = r_left[1] + (1.0 + zeta[0]) / 2.0 * (r_right[1] - r_left[1]);
   }
References i, j, macro_bound_IV_E(), macro_bound_IV_W(), UniformPSDSelfTest::r, plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
macro_bound_IV_W()
void oomph::ChannelWithLeafletDomain::macro_bound_IV_W (const unsigned & t, const Vector< double > & zeta, Vector< double > & r, const unsigned & i, const unsigned & j) protected
Helper function.
Helper function for western boundary in upper right region.
   {
     // Find x,y on the slanted straight line (SSL) corresponding to
     // the position of the macro element
     // xi_line varies from xi0 to xi1 on the SSL
     double xi0, xi1;
     xi0 = double(i) / double(Ny2);
     xi1 = double(i + 1) / double(Ny2);
     Vector<double> xi_line(1);
     xi_line[0] = xi0 + (1.0 + zeta[0]) / 2.0 * (xi1 - xi0);
     Vector<double> r_line(2);
     slanted_bound_up(t, xi_line, r_line);
     // Find x,y on a vertical line corresponding
     // to the position of the macro element
     // The vertical line goes from y0 to y1
     double y0, y1;
     y0 = double(i) * (Htot - Hleaflet) / double(Ny2) + Hleaflet;
     y1 = double(i + 1) * (Htot - Hleaflet) / double(Ny2) + Hleaflet;
     ;
     Vector<double> r_vert(2);
     r_vert[0] = Lright + X_0;
     r_vert[1] = y0 + (1.0 + zeta[0]) / 2.0 * (y1 - y0);
     // Parameter with value 0 in Lright and value 1 on the wall.
     double s = double(Nright - j) / double(Nright); /***Change****/
     // Final expression of r
     r[0] = r_vert[0] + s * (r_line[0] - r_vert[0]);
     r[1] = r_vert[1] + s * (r_line[1] - r_vert[1]);
   }
References Hleaflet, Htot, i, j, Lright, Nright, Ny2, UniformPSDSelfTest::r, s, slanted_bound_up(), plotPSD::t, X_0, and Eigen::zeta().
Referenced by macro_bound_IV_N(), macro_bound_IV_S(), and macro_element_boundary().
macro_element_boundary()
void oomph::ChannelWithLeafletDomain::macro_element_boundary (const unsigned & t, const unsigned & imacro, const unsigned & idirect, const Vector< double > & zeta, Vector< double > & r) virtual
Parametrisation of macro element boundaries.
Implements oomph::Domain.
   {
 #ifdef WARN_ABOUT_SUBTLY_CHANGED_OOMPH_INTERFACES
     // Warn about time argument being moved to the front
     OomphLibWarning(
       "Order of function arguments has changed between versions 0.8 and 0.85",
       "ChannelWithLeafletDomain::macro_element_boundary(...)",
       OOMPH_EXCEPTION_LOCATION);
 #endif
     using namespace QuadTreeNames;
     // Number of the line and of the colum in the whole domain
     // Beware : iline starts on zero
     unsigned iline = int(floor(double(imacro) / double(Nleft + Nright)));
     unsigned icol = imacro % (Nright + Nleft);
     // Number of the line and of the colum in the part considered
     unsigned i, j;
     // Left low part of the domain : Part I
     //------------------------------------
     if ((iline < Ny1) && (icol < Nleft))
     {
       i = iline;
       j = icol;
       switch (idirect)
       {
         case N:
           macro_bound_I_N(t, zeta, r, i, j);
           break;
         case S:
           macro_bound_I_S(t, zeta, r, i, j);
           break;
         case W:
           macro_bound_I_W(t, zeta, r, i, j);
           break;
         case E:
           macro_bound_I_E(t, zeta, r, i, j);
           break;
       }
     }
     // Right low part of the domain : Part II
     //--------------------------------------
     else if ((iline < Ny1) && (icol >= Nleft))
     {
       i = iline;
       j = icol - Nleft;
       switch (idirect)
       {
         case N:
           macro_bound_II_N(t, zeta, r, i, j);
           break;
         case S:
           macro_bound_II_S(t, zeta, r, i, j);
           break;
         case W:
           macro_bound_II_W(t, zeta, r, i, j);
           break;
         case E:
           macro_bound_II_E(t, zeta, r, i, j);
           break;
       }
     }
     // Left upper part of the domain : Part III
     //----------------------------------------
     else if ((iline >= Ny1) && (icol < Nleft))
     {
       i = iline - Ny1;
       j = icol;
       switch (idirect)
       {
         case N:
           macro_bound_III_N(t, zeta, r, i, j);
           break;
         case S:
           macro_bound_III_S(t, zeta, r, i, j);
           break;
         case W:
           macro_bound_III_W(t, zeta, r, i, j);
           break;
         case E:
           macro_bound_III_E(t, zeta, r, i, j);
           break;
       }
     }
     // Right upper part of the domain : Part IV
     //-----------------------------------------
     else if ((iline >= Ny1) && (icol >= Nleft))
     {
       i = iline - Ny1;
       j = icol - Nleft;
       switch (idirect)
       {
         case N:
           macro_bound_IV_N(t, zeta, r, i, j);
           break;
         case S:
           macro_bound_IV_S(t, zeta, r, i, j);
           break;
         case W:
           macro_bound_IV_W(t, zeta, r, i, j);
           break;
         case E:
           macro_bound_IV_E(t, zeta, r, i, j);
           break;
       }
     }
   }
References Global_Physical_Variables::E, Eigen::bfloat16_impl::floor(), i, int(), j, macro_bound_I_E(), macro_bound_I_N(), macro_bound_I_S(), macro_bound_I_W(), macro_bound_II_E(), macro_bound_II_N(), macro_bound_II_S(), macro_bound_II_W(), macro_bound_III_E(), macro_bound_III_N(), macro_bound_III_S(), macro_bound_III_W(), macro_bound_IV_E(), macro_bound_IV_N(), macro_bound_IV_S(), macro_bound_IV_W(), N, Nleft, Nright, Ny1, OOMPH_EXCEPTION_LOCATION, UniformPSDSelfTest::r, oomph::QuadTreeNames::S, plotPSD::t, oomph::QuadTreeNames::W, and Eigen::zeta().
slanted_bound_up()
void oomph::ChannelWithLeafletDomain::slanted_bound_up (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) protected
Helper function.
////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// Describe the line between the boundary north of the domain (at x=X_0) and the top of the wall, when zeta goes from 0 to 1.
   {
     // Coordinates of the point on the boundary beetween the upper
     // and the lower part, in the same column, at the east.
     Vector<double> xi(1);
     xi[0] = Hleaflet;
     Vector<double> r_join(2);
     Leaflet_pt->position(t, xi, r_join);
     r[0] = r_join[0] + zeta[0] * (X_0 - r_join[0]);
     r[1] = r_join[1] + zeta[0] * (Htot - r_join[1]);
   }
References Hleaflet, Htot, Leaflet_pt, oomph::GeomObject::position(), UniformPSDSelfTest::r, plotPSD::t, X_0, and Eigen::zeta().
Referenced by macro_bound_III_E(), macro_bound_III_W(), macro_bound_IV_E(), and macro_bound_IV_W().
Member Data Documentation
Hleaflet
double oomph::ChannelWithLeafletDomain::Hleaflet protected
Lagrangian coordinate at end of leaflet.
Referenced by ChannelWithLeafletDomain(), hleaflet(), macro_bound_I_E(), macro_bound_I_W(), macro_bound_II_E(), macro_bound_II_W(), macro_bound_III_E(), macro_bound_III_W(), macro_bound_IV_E(), macro_bound_IV_W(), and slanted_bound_up().
Htot
double oomph::ChannelWithLeafletDomain::Htot protected
Total width of the channel.
Referenced by ChannelWithLeafletDomain(), htot(), macro_bound_III_E(), macro_bound_III_W(), macro_bound_IV_E(), macro_bound_IV_W(), and slanted_bound_up().
Leaflet_pt
GeomObject* oomph::ChannelWithLeafletDomain::Leaflet_pt protected
Pointer to leaflet.
Referenced by ChannelWithLeafletDomain(), leaflet_pt(), macro_bound_I_E(), macro_bound_I_W(), macro_bound_II_E(), macro_bound_II_W(), and slanted_bound_up().
Lleft
double oomph::ChannelWithLeafletDomain::Lleft protected
Length of the domain to the left of the leaflet.
Referenced by ChannelWithLeafletDomain(), lleft(), macro_bound_I_E(), macro_bound_I_W(), macro_bound_III_E(), and macro_bound_III_W().
Lright
double oomph::ChannelWithLeafletDomain::Lright protected
Length of the domain to the right of the leaflet.
Referenced by ChannelWithLeafletDomain(), lright(), macro_bound_II_E(), macro_bound_II_W(), macro_bound_IV_E(), and macro_bound_IV_W().
Nleft
unsigned oomph::ChannelWithLeafletDomain::Nleft protected
Number of macro element columns to the left of the leaflet.
Referenced by ChannelWithLeafletDomain(), macro_bound_I_E(), macro_bound_I_W(), macro_bound_III_E(), macro_bound_III_W(), and macro_element_boundary().
Nright
unsigned oomph::ChannelWithLeafletDomain::Nright protected
Number of macro element columnns to the right of the leaflet.
Referenced by ChannelWithLeafletDomain(), macro_bound_II_E(), macro_bound_II_W(), macro_bound_IV_E(), macro_bound_IV_W(), and macro_element_boundary().
Ny1
unsigned oomph::ChannelWithLeafletDomain::Ny1 protected
Number of macro element rows up to the end of the leaflet.
Referenced by ChannelWithLeafletDomain(), macro_bound_I_E(), macro_bound_I_W(), macro_bound_II_E(), macro_bound_II_W(), and macro_element_boundary().
Ny2
unsigned oomph::ChannelWithLeafletDomain::Ny2 protected
Number of macro element rows above the leaflet.
Referenced by ChannelWithLeafletDomain(), macro_bound_III_E(), macro_bound_III_W(), macro_bound_IV_E(), and macro_bound_IV_W().
X_0
double oomph::ChannelWithLeafletDomain::X_0 protected
Center of the domain : origin of the leaflet, extracted from GeomObject and stored for fast access.
Referenced by ChannelWithLeafletDomain(), macro_bound_I_E(), macro_bound_I_W(), macro_bound_II_E(), macro_bound_II_W(), macro_bound_III_E(), macro_bound_III_W(), macro_bound_IV_E(), macro_bound_IV_W(), and slanted_bound_up().
The documentation for this class was generated from the following file:
channel_with_leaflet_domain.h