MercuryDPM: stefan_boltzmann.cc File Reference
stefan_boltzmann.cc File Reference
#include <fenv.h>
#include "math.h"
#include <complex>
#include "generic.h"
#include "unsteady_heat.h"
#include "heat_transfer_and_melt_elements.h"
#include "temporary_stefan_boltzmann_elements.h"
#include "meshes/triangle_mesh.h"
Classes
class MyIntegral
class StefanBoltzmannProblem< ELEMENT >
Problem class.
Namespaces
GlobalParameters
Global parameters.
Functions
void GlobalParameters::get_source (const double &time, const Vector< double > &x, double &source)
Source function.
void GlobalParameters::get_exact_u (const double &time, const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
int main (int argc, char **argv)
Solve 2D problem.
Variables
string GlobalParameters::Directory ="RESLT"
Output directory.
unsigned GlobalParameters::Nintpt =10
Number of integration points for new integration scheme (if used)
double GlobalParameters::Sigma = 1.0e-2
Non-dim Stefan Boltzmann constant.
double GlobalParameters::Theta_0 =1.0
Zero degrees Celsius offset in Stefan Boltzmann law.
double GlobalParameters::Alpha0 =1.0
Thermal inertia in inner region.
double GlobalParameters::Alpha1 =1.0
Thermal inertia in outer annular region.
double GlobalParameters::Beta0 =0.05
Thermal conductivity in inner region.
double GlobalParameters::Beta1 =1.5
Thermal conductivity in outer annular region.
double GlobalParameters::Target_area =0.05
Target element size.
double GlobalParameters::Radius_innermost =0.5
Radius of inner circle.
double GlobalParameters::Radius_inner =1.0
Inner radius of annular region.
double GlobalParameters::Radius_outer =1.5
Outer radius of annular region.
double GlobalParameters::U0 = 0.8288627710
Temperature on boundary of inner circle.
double GlobalParameters::S0 =0.1
Strength of source function in inner region.
double GlobalParameters::S1 =1.0
Strength of source function in outer region.
Function Documentation
main()
int main (int argc , char ** argv)
Solve 2D problem.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Number of integration points for new integration scheme.
  // Use normal Gauss rule if not specified.
  CommandLineArgs::specify_command_line_flag("--nintpt",
                                             &GlobalParameters::Nintpt);
  // Output directory
  CommandLineArgs::specify_command_line_flag("--dir",
                                             &GlobalParameters::Directory);
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Create label for output
  //------------------------
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory(GlobalParameters::Directory);
  // hierher refinement loop
  for (unsigned i=0;i<1;i++)
   {
    oomph_info << "Building/solving for  GlobalParameters::Target_area = "
               << GlobalParameters::Target_area << std::endl;
    // Set up the problem with 2D six-node elements
    StefanBoltzmannProblem<TUnsteadyHeatElement<2,3> >  problem;
    // Initialise timestep -- also sets the weights for all timesteppers
    // in the problem.
    double dt=0.01;
    problem.initialise_dt(dt);
    problem.assign_initial_values_impulsive();
    // Steady solve only
    {
     // Do steady solve
     problem.steady_newton_solve();
     //Output solution
     problem.doc_solution(doc_info);
     exit(0);
    }
    //Output initial condition
    problem.doc_solution(doc_info);
    //Increment counter for solutions
    doc_info.number()++;
    // Timestepping loop
    unsigned nstep = 20;
    for (unsigned istep=0;istep<nstep;istep++)
     {
      cout << " Timestep " << istep << std::endl;
      // Take timestep
      problem.unsteady_newton_solve(dt);
      //Output solution
      problem.doc_solution(doc_info);
      //Increment counter for solutions
      doc_info.number()++;
     }
    // Adjust
    GlobalParameters::Target_area/=4.0;
   }
 } //end of main
References GlobalParameters::Directory, oomph::CommandLineArgs::doc_specified_flags(), i, GlobalParameters::Nintpt, oomph::DocInfo::number(), oomph::oomph_info, oomph::CommandLineArgs::parse_and_assign(), problem, oomph::DocInfo::set_directory(), oomph::CommandLineArgs::setup(), oomph::CommandLineArgs::specify_command_line_flag(), and GlobalParameters::Target_area.