MercuryDPM: oomph::Time Class Reference
oomph::Time Class Reference
#include <timesteppers.h>
Public Member Functions
Time ()
Time (const unsigned &ndt)
Time (const Time &)=delete
Broken copy constructor.
void operator= (const Time &)=delete
Broken assignment operator.
void resize (const unsigned &n_dt)
void initialise_dt (const double &dt_)
Set all timesteps to the same value, dt.
void initialise_dt (const Vector< double > &dt_)
~Time ()
Destructor: empty.
double & time ()
Return the current value of the continuous time.
unsigned ndt () const
Return the number of timesteps stored.
double & dt (const unsigned &t=0)
double dt (const unsigned &t=0) const
double time (const unsigned &t=0) const
void shift_dt ()
Private Attributes
double Continuous_time
Pointer to the value of the continuous time.
Vector< double > Dt
Vector that stores the values of the current and previous timesteps.
Detailed Description
Class to keep track of discrete/continous time. It is essential to have a single Time object when using multiple time-stepping schemes; e.g., in fluid-structure interaction problems, it is common to use different schemes for the fluid and solid domains. Storage is allocated for the current value of the (continuous) time and a limited history of previous timesteps. The number of previous timesteps must be equal to the number required by the "highest order" scheme.
Constructor & Destructor Documentation
Time() [1/3]
oomph::Time::Time () inline
Constructor: Do not allocate any storage for previous timesteps, but set the initial value of the time to zero
 : Continuous_time(0.0) {}
Time() [2/3]
oomph::Time::Time (const unsigned & ndt) inline
Constructor: Pass the number of timesteps to be stored and set the initial value of time to zero.
                               : Continuous_time(0.0)
     {
       // Allocate memory for the timestep storage and initialise values to one
       // to avoid division by zero.
       Dt.resize(ndt, 1.0);
     }
References Dt, and ndt().
Time() [3/3]
oomph::Time::Time (const Time &) delete
Broken copy constructor.
~Time()
oomph::Time::~Time () inline
Destructor: empty.
 {}
Member Function Documentation
dt() [1/2]
double& oomph::Time::dt (const unsigned & t = 0) inline
Return the value of the t-th stored timestep (t=0: present; t>0: previous).
     {
       return Dt[t];
     }
References Dt, and plotPSD::t.
Referenced by oomph::IMRByBDF::actions_after_timestep(), oomph::IMRByBDF::actions_before_timestep(), oomph::Problem::adaptive_unsteady_newton_solve(), oomph::Problem::calculate_predictions(), oomph::Problem::copy(), oomph::Problem::doubly_adaptive_unsteady_newton_solve_helper(), oomph::Problem::dump(), oomph::Problem::explicit_timestep(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::extrapolated_strain_rate(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::extrapolated_strain_rate(), oomph::PseudoBucklingRing::position(), oomph::TR::set_error_weights(), oomph::SelfStartingBDF2::set_error_weights_bdf2(), oomph::NewmarkBDF< NSTEPS >::set_newmark_veloc_weights(), oomph::BDF< NSTEPS >::set_predictor_weights(), oomph::TR::set_predictor_weights(), oomph::SelfStartingBDF2::set_predictor_weights_bdf2(), oomph::IMR::set_weights(), oomph::IMRByBDF::set_weights(), oomph::BDF< NSTEPS >::set_weights(), oomph::TR::set_weights(), oomph::SelfStartingBDF2::set_weights_bdf1(), oomph::SelfStartingBDF2::set_weights_bdf2(), oomph::TR::shift_time_values(), oomph::EBDF3::timestep(), oomph::Problem::unsteady_newton_solve(), and oomph::SegregatableFSIProblem::unsteady_segregated_solve().
dt() [2/2]
double oomph::Time::dt (const unsigned & t = 0) const inline
Return the value of the t-th stored timestep (t=0: present; t>0: previous), const version.
     {
       return Dt[t];
     }
References Dt, and plotPSD::t.
initialise_dt() [1/2]
void oomph::Time::initialise_dt (const double & dt_) inline
Set all timesteps to the same value, dt.
     {
       unsigned ndt = Dt.size();
       Dt.assign(ndt, dt_);
     }
References Dt, and ndt().
Referenced by oomph::Problem::initialise_dt().
initialise_dt() [2/2]
void oomph::Time::initialise_dt (const Vector< double > & dt_) inline
Set the value of the timesteps to be equal to the values passed in a vector
     {
       // Assign the values from the vector dt_, but preserve the size of Dt and
       // any Dt[i] s.t. i > dt_.size() (which is why we can't just use
       // assignment operator).
       unsigned n_dt = dt_.size();
       for (unsigned i = 0; i < n_dt; i++)
       {
         Dt[i] = dt_[i];
       }
     }
References Dt, and i.
ndt()
unsigned oomph::Time::ndt () const inline
Return the number of timesteps stored.
     {
       return Dt.size();
     }
References Dt.
Referenced by oomph::Problem::add_time_stepper_pt(), oomph::Problem::copy(), oomph::Problem::dump(), initialise_dt(), Time(), and time().
operator=()
void oomph::Time::operator= (const Time &) delete
Broken assignment operator.
resize()
void oomph::Time::resize (const unsigned & n_dt) inline
Resize the vector holding the number of previous timesteps and initialise the new values to zero.
     {
       Dt.resize(n_dt, 0.0);
     }
References Dt.
Referenced by oomph::Problem::add_time_stepper_pt(), oomph::Problem::copy(), and oomph::Problem::read().
shift_dt()
void oomph::Time::shift_dt () inline
Update all stored values of dt by shifting each value along the array. This function must be called before starting to solve at a new time level.
     {
       unsigned n_dt = Dt.size();
       // Return straight away if there are no stored timesteps
       if (n_dt == 0)
       {
         return;
       }
       // Start from the end of the array and shift every entry back by one
       for (unsigned i = (n_dt - 1); i > 0; i--)
       {
         Dt[i] = Dt[i - 1];
       }
     }
References Dt, and i.
Referenced by oomph::Problem::shift_time_values().
time() [1/2]
double& oomph::Time::time () inline
Return the current value of the continuous time.
     {
       return Continuous_time;
     }
References Continuous_time.
Referenced by AxisymOscillatingDisk::accel(), oomph::PseudoBucklingRing::accel(), oomph::IMRByBDF::actions_after_timestep(), oomph::IMRByBDF::actions_before_timestep(), oomph::Problem::adaptive_unsteady_newton_solve(), oomph::SelfStartingBDF2::assign_initial_data_values(), oomph::PeriodicOrbitTimeDiscretisation::assign_initial_data_values(), oomph::LinearElasticityEquationsBase< DIM >::body_force(), oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::body_force(), oomph::PVDEquationsBase< DIM >::body_force(), oomph::TimeStepper::check_predicted_values_up_to_date(), oomph::Problem::copy(), oomph::Problem::doubly_adaptive_unsteady_newton_solve_helper(), oomph::Problem::dump(), oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), oomph::AxisymmetricPoroelasticityEquations::fill_in_generic_residual_contribution(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::PeriodicOrbitEquations::fill_in_generic_residual_contribution_orbit(), oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::SphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::AxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_wind_adv_diff_react(), oomph::ODEProblem::my_set_initial_condition(), oomph::PeriodicOrbitEquations::orbit_output(), oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::output(), oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >::output(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::output(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::output(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::output(), oomph::SolarRadiationBase::output_atmospheric_radiation(), oomph::SurfaceMeltElement< ELEMENT >::output_melt(), oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::output_stefan_boltzmann_radiation(), OscillatingCylinder::position(), Leaflet::position(), Flag_definition::TopOfFlag::position(), Flag_definition::BottomOfFlag::position(), Flag_definition::TipOfFlag::position(), OscillatingWall::position(), MyEllipse::position(), AxisymOscillatingDisk::position(), oomph::PseudoBucklingRing::position(), oomph::Problem::read(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::scalar_value_paraview(), oomph::SolidICProblem::set_newmark_initial_condition_consistently(), oomph::SolidICProblem::set_newmark_initial_condition_directly(), oomph::SolidICProblem::set_static_initial_condition(), oomph::Problem::time(), oomph::PeriodicOrbitEquations::time(), oomph::IMRODEElement::time_interpolate_time(), oomph::TemplateFreeContactElementBase::traction_fct(), oomph::Problem::unsteady_newton_solve(), oomph::SegregatableFSIProblem::unsteady_segregated_solve(), AxisymOscillatingDisk::veloc(), and oomph::PseudoBucklingRing::veloc().
time() [2/2]
double oomph::Time::time (const unsigned & t = 0) const inline
Return the value of the continuous time at the t-th previous time level (t=0: current; t>0 previous).
     {
 #ifdef PARANOID
       if (t > ndt())
       {
         using namespace StringConversion;
         std::string error_msg = "Timestep " + to_string(t) + " out of range!";
         throw OomphLibError(
           error_msg, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Load the current value of the time
       double time_local = Continuous_time;
       // Loop over the t previous timesteps and subtract each dt
       for (unsigned i = 0; i < t; i++)
       {
         time_local -= Dt[i];
       }
       return time_local;
     }
References Continuous_time, Dt, i, ndt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Global_string_for_annotation::string(), plotPSD::t, and oomph::StringConversion::to_string().
Member Data Documentation
Continuous_time
double oomph::Time::Continuous_time private
Pointer to the value of the continuous time.
Referenced by time().
Dt
Vector<double> oomph::Time::Dt private
Vector that stores the values of the current and previous timesteps.
Referenced by dt(), initialise_dt(), ndt(), resize(), shift_dt(), Time(), and time().
The documentation for this class was generated from the following file:
timesteppers.h