MercuryDPM: oomph::RefineableLinearisedAxisymmetricNavierStokesEquations Class Reference
oomph::RefineableLinearisedAxisymmetricNavierStokesEquations Class Reference abstract
#include <refineable_linearised_axisym_navier_stokes_elements.h>
Public Member Functions
RefineableLinearisedAxisymmetricNavierStokesEquations ()
Empty Constructor.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
double geometric_jacobian (const Vector< double > &x)
Fill in the geometric Jacobian, which in this case is r.
void further_build ()
Further build: pass the pointers down to the sons.
RefineableLinearisedAxisymmetricNavierStokesEquations ()
Empty Constructor.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
double geometric_jacobian (const Vector< double > &x)
Fill in the geometric Jacobian, which in this case is r.
void further_build ()
Further build: pass the pointers down to the sons.
Public Member Functions inherited from oomph::LinearisedAxisymmetricNavierStokesEquations
LinearisedAxisymmetricNavierStokesEquations ()
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
const int & azimuthal_mode_number () const
Azimuthal mode number k in e^ik(theta) decomposition.
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
int *& azimuthal_mode_number_pt ()
Pointer to azimuthal mode number k in e^ik(theta) decomposition.
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to the viscosity ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to the density ratio.
virtual unsigned npres_linearised_axi_nst () const =0
virtual unsigned u_index_linearised_axi_nst (const unsigned &i) const
double du_dt_linearised_axi_nst (const unsigned &n, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
virtual double p_linearised_axi_nst (const unsigned &n_p, const unsigned &i) const =0
virtual int p_index_linearised_axi_nst (const unsigned &i) const
Which nodal value represents the pressure?
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &nplot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
double interpolated_u_linearised_axi_nst (const Vector< double > &s, const unsigned &i) const
double interpolated_p_linearised_axi_nst (const Vector< double > &s, const unsigned &i) const
virtual void get_base_flow_u (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result) const
LinearisedAxisymmetricNavierStokesEquations ()
const double & re () const
Reynolds number.
double *& re_pt ()
Pointer to Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const double & re_invro () const
Global Reynolds number multiplied by inverse Rossby number.
double *& re_invro_pt ()
Pointer to global Reynolds number multiplied by inverse Rossby number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
const int & azimuthal_mode_number () const
Azimuthal mode number k in e^ik(theta) decomposition.
int *& azimuthal_mode_number_pt ()
Pointer to azimuthal mode number k in e^ik(theta) decomposition.
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to the viscosity ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to the density ratio.
virtual int get_local_eqn_number_corresponding_to_geometric_dofs (const unsigned &n, const unsigned &i)=0
virtual unsigned npres_lin_axi_nst () const =0
virtual unsigned xhat_index_lin_axi_nst (const unsigned &i) const
virtual unsigned u_index_lin_axi_nst (const unsigned &i) const
double du_dt_lin_axi_nst (const unsigned &n, const unsigned &i) const
double dnodal_position_perturbation_dt_lin_axi_nst (const unsigned &n, const unsigned &i) const
unsigned nexternal_H_data ()
Return the number of external perturbed spine "heights" data.
void disable_ALE ()
void enable_ALE ()
virtual double p_lin_axi_nst (const unsigned &n_p, const unsigned &i) const =0
virtual int p_index_lin_axi_nst (const unsigned &i) const
Which nodal value represents the pressure?
void dkin_energy_dt (double &dkin_en_dt, double &kin_en) const
Get integral of kinetic energy over element plus deriv w.r.t. time.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &nplot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
double interpolated_u_lin_axi_nst (const Vector< double > &s, const unsigned &i) const
double interpolated_p_lin_axi_nst (const Vector< double > &s, const unsigned &i) const
double interpolated_nodal_position_perturbation_lin_axi_nst (const Vector< double > &s, const unsigned &i) const
void assign_additional_local_eqn_numbers ()
Define the local equation numbering schemes.
LinearisedAxisymmetricNavierStokesEquations ()
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
const int & azimuthal_mode_number () const
Azimuthal mode number k in e^ik(theta) decomposition.
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
int *& azimuthal_mode_number_pt ()
Pointer to azimuthal mode number k in e^ik(theta) decomposition.
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to the viscosity ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to the density ratio.
virtual unsigned npres_linearised_axi_nst () const =0
virtual unsigned u_index_linearised_axi_nst (const unsigned &i) const
double du_dt_linearised_axi_nst (const unsigned &n, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
virtual double p_linearised_axi_nst (const unsigned &n_p, const unsigned &i) const =0
virtual int p_index_linearised_axi_nst (const unsigned &i) const
Which nodal value represents the pressure?
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &nplot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
double interpolated_u_linearised_axi_nst (const Vector< double > &s, const unsigned &i) const
double interpolated_p_linearised_axi_nst (const Vector< double > &s, const unsigned &i) const
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
virtual unsigned required_nsons () const
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)=0
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void rebuild_from_sons (Mesh *&mesh_pt)=0
virtual void unbuild ()
virtual void deactivate_element ()
virtual bool nodes_built ()
Return true if all the nodes have been built, false if not.
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual unsigned ncont_interpolated_values () const =0
virtual void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
virtual void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)=0
virtual Node * interpolating_node_pt (const unsigned &n, const int &value_id)
virtual double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
virtual Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
virtual unsigned ninterpolating_node (const int &value_id)
virtual unsigned ninterpolating_node_1d (const int &value_id)
virtual void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
virtual void check_integrity (double &max_error)=0
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual RefineableElement * root_element_pt ()
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
virtual void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
virtual void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
Pre-build the element.
virtual void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
virtual void further_setup_hanging_nodes ()
void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
unsigned nshape_controlling_nodes ()
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Public Member Functions inherited from oomph::ElementWithZ2ErrorEstimator
ElementWithZ2ErrorEstimator ()
Default empty constructor.
ElementWithZ2ErrorEstimator (const ElementWithZ2ErrorEstimator &)=delete
Broken copy constructor.
void operator= (const ElementWithZ2ErrorEstimator &)=delete
Broken assignment operator.
virtual unsigned ncompound_fluxes ()
virtual void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
virtual void get_Z2_compound_flux_indices (Vector< unsigned > &flux_index)
virtual unsigned nvertex_node () const =0
Number of vertex nodes in the element.
virtual Node * vertex_node_pt (const unsigned &j) const =0
virtual unsigned nrecovery_order ()=0
Order of recovery shape functions.
Static Public Member Functions
static void pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > &element_pt)
static void unpin_all_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in Vector.
static void pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > &element_pt)
static void unpin_all_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in Vector.
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Protected Member Functions
virtual Node * pressure_node_pt (const unsigned &n_p)
virtual void unpin_elemental_pressure_dofs ()=0
Unpin all pressure dofs in the element.
virtual void pin_elemental_redundant_nodal_pressure_dofs ()
virtual Node * pressure_node_pt (const unsigned &n_p)
virtual void unpin_elemental_pressure_dofs ()=0
Unpin all pressure dofs in the element.
virtual void pin_elemental_redundant_nodal_pressure_dofs ()
Protected Member Functions inherited from oomph::LinearisedAxisymmetricNavierStokesEquations
virtual int p_local_eqn (const unsigned &n, const unsigned &i)=0
virtual double dshape_and_dtest_eulerian_linearised_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_linearised_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual void pshape_linearised_axi_nst (const Vector< double > &s, Shape &psi) const =0
Compute the pressure shape functions at local coordinate s.
virtual void pshape_linearised_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const =0
Compute the pressure shape and test functions at local coordinate s.
virtual void get_base_flow_u (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result) const
virtual void get_base_flow_dudx (const double &time, const unsigned &ipt, const Vector< double > &x, DenseMatrix< double > &result) const
virtual int p_local_eqn (const unsigned &n, const unsigned &i)=0
virtual double dshape_and_dtest_eulerian_lin_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_lin_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_and_dnodal_coordinates_at_knot_lin_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const =0
virtual void pshape_lin_axi_nst (const Vector< double > &s, Shape &psi) const =0
Compute the pressure shape functions at local coordinate s.
virtual void pshape_lin_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const =0
Compute the pressure shape and test functions at local coordinate s.
virtual void get_base_flow_dudx (const double &time, const unsigned &ipt, const Vector< double > &x, DenseMatrix< double > &result) const
virtual void get_base_flow_dudt (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result) const
virtual void get_base_flow_p (const double &time, const unsigned &ipt, const Vector< double > &x, double &result) const
virtual void get_base_flow_d_dudx_dX (const double &time, const unsigned &ipt, const Vector< double > &x, RankFourTensor< double > &result) const
void get_body_force_base_flow (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result)
double get_source_base_flow (const double &time, const unsigned &ipt, const Vector< double > &x)
void get_body_force_gradient_base_flow (const double &time, const unsigned &ipt, const Vector< double > &x, DenseMatrix< double > &result)
void get_source_gradient_base_flow (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result)
virtual void get_base_flow_duds (const double &time, const unsigned &ipt, const Vector< double > &x, DenseMatrix< double > &result) const
virtual void fill_in_generic_residual_contribution_lin_axi_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
virtual int p_local_eqn (const unsigned &n, const unsigned &i)=0
virtual double dshape_and_dtest_eulerian_linearised_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_linearised_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual void pshape_linearised_axi_nst (const Vector< double > &s, Shape &psi) const =0
Compute the pressure shape functions at local coordinate s.
virtual void pshape_linearised_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const =0
Compute the pressure shape and test functions at local coordinate s.
virtual void get_base_flow_u (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result) const
virtual void get_base_flow_dudx (const double &time, const unsigned &ipt, const Vector< double > &x, DenseMatrix< double > &result) const
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Private Member Functions
void fill_in_generic_residual_contribution_linearised_axi_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
void fill_in_generic_residual_contribution_linearised_axi_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Attributes inherited from oomph::LinearisedAxisymmetricNavierStokesEquations
void(*&)(const double &time, const Vector< double > &x, Vector< double > &f) base_flow_u_fct_pt ()
Access function for the base flow solution pointer.
void(*&)(const double &time, const Vector< double > &x, DenseMatrix< double > &f) base_flow_dudx_fct_pt ()
void(*&)(const double &time, const Vector< double > &x, Vector< double > &f) base_flow_dudt_fct_pt ()
void(*&)(const double &time, const Vector< double > &x, double &f) base_flow_p_fct_pt ()
Access function for the base flow pressure pointer.
void(*&)(const double &time, const Vector< double > &x, RankFourTensor< double > &f) base_flow_d_dudx_dX_fct_pt ()
void(*&)(const double &time, const Vector< double > &x, Vector< double > &f) body_force_fct_pt ()
Access function for the body-force pointer.
double(*&)(const double &time, const Vector< double > &x) source_fct_pt ()
Access function for the source-function pointer.
void(*&)(const double &time, const Vector< double > &x, DenseMatrix< double > &f) base_flow_duds_fct_pt ()
Static Public Attributes inherited from oomph::LinearisedAxisymmetricNavierStokesEquations
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Protected Attributes inherited from oomph::LinearisedAxisymmetricNavierStokesEquations
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
int * Azimuthal_Mode_Number_pt
Pointer to azimuthal mode number k in e^ik(theta) decomposition.
void(* Base_flow_u_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
Pointer to base flow solution (velocity components) function.
void(* Base_flow_dudx_fct_pt)(const double &time, const Vector< double > &x, DenseMatrix< double > &result)
bool ALE_is_disabled
double * ReInvFr_pt
double * ReInvRo_pt
Vector< double > * G_pt
Pointer to global gravity Vector.
void(* Base_flow_dudt_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
void(* Base_flow_p_fct_pt)(const double &time, const Vector< double > &x, double &result)
Pointer to base flow solution (pressure) function.
void(* Base_flow_d_dudx_dX_fct_pt)(const double &time, const Vector< double > &x, RankFourTensor< double > &result)
void(* Body_force_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
Pointer to (base flow) body force function.
double(* Source_fct_pt)(const double &time, const Vector< double > &x)
Pointer to (base flow) volumetric source function.
void(* Base_flow_duds_fct_pt)(const double &time, const Vector< double > &x, DenseMatrix< double > &result)
Vector< int > External_H_local_eqn
Vector< unsigned > External_node
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number – for plotting/validation purposes.
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Detailed Description
Refineable version of the linearised axisymmetric Navier–Stokes equations
Constructor & Destructor Documentation
RefineableLinearisedAxisymmetricNavierStokesEquations() [1/2]
oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::RefineableLinearisedAxisymmetricNavierStokesEquations () inline
Empty Constructor.
                                                          :
   LinearisedAxisymmetricNavierStokesEquations(),
   RefineableElement(),
   ElementWithZ2ErrorEstimator() {}
RefineableLinearisedAxisymmetricNavierStokesEquations() [2/2]
oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::RefineableLinearisedAxisymmetricNavierStokesEquations () inline
Empty Constructor.
       : LinearisedAxisymmetricNavierStokesEquations(),
         RefineableElement(),
         ElementWithZ2ErrorEstimator()
     {
     }
Member Function Documentation
fill_in_generic_residual_contribution_linearised_axi_nst() [1/2]
void oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) private virtual
Add element's contribution to the elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector
Add element's contribution to the elemental residual vector and/or Jacobian matrix. flag=1: compute both flag=0: compute only residual vector
Compute the residuals for the refineable linearised axisymmetric Navier–Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented from oomph::LinearisedAxisymmetricNavierStokesEquations.
  {
   // The dimension is actually two
 //  const unsigned DIM=2;
   // Determine number of nodes in the element
   const unsigned n_node = nnode();
   // Get continuous time from timestepper of first node
   double time=node_pt(0)->time_stepper_pt()->time_pt()->time();
   // Determine how many pressure values there are associated with
   // a single pressure component
   const unsigned n_pres = npres_linearised_axi_nst();
   // Get the nodal indices at which the velocity is stored
   unsigned u_nodal_index[6];
   for(unsigned i=0;i<6;++i)
    {
     u_nodal_index[i] = u_index_linearised_axi_nst(i);
    }
   // Which nodal values represent the two pressure components?
   // (Negative if pressure is not based on nodal interpolation).
   Vector<int> p_index(2);
   for(unsigned i=0;i<2;i++)
    {
     p_index[i] = this->p_index_linearised_axi_nst(i);
    }
   // Local array of booleans that are true if the l-th pressure value is
   // hanging (avoid repeated virtual function calls)
   bool pressure_dof_is_hanging[n_pres];
   // Loop over two pressure components
 //  for(unsigned i=0;i<2;i++)
 //   {
     // If the pressure is stored at a node
     if(p_index[0] >= 0)
      {
       // Read out whether the pressure is hanging
       for(unsigned l=0;l<n_pres;++l)
        {
         pressure_dof_is_hanging[l] =
          pressure_node_pt(l)->is_hanging(p_index[0]);
        }
      }
     // Otherwise the pressure is not stored at a node and so cannot hang
     else
      {
       for(unsigned l=0;l<n_pres;++l)
        { pressure_dof_is_hanging[l] = false; }
      }
 //   } // End of loop over pressure components
   // Set up memory for the shape and test functions
   // Note that there are two dimensions, r and z, in this problem
   Shape psif(n_node), testf(n_node);
   DShape dpsifdx(n_node,2), dtestfdx(n_node,2);
   // Set up memory for the pressure shape and test functions
   Shape psip(n_pres), testp(n_pres);
   // Determine number of integration points
   const unsigned n_intpt = integral_pt()->nweight();
   // Set up memory for the vector to hold local coordinates (two dimensions)
   Vector<double> s(2);
   // Get physical variables from the element
   // (Reynolds number must be multiplied by the density ratio)
   const double scaled_re = re()*density_ratio();
   const double scaled_re_st = re_st()*density_ratio();
   const double visc_ratio = viscosity_ratio();
   const int k = azimuthal_mode_number();
   // Integers used to store the local equation and unknown numbers
   int local_eqn = 0, local_unknown = 0;
   // Local storage for pointers to hang info objects
   HangInfo *hang_info_pt=0, *hang_info2_pt=0;
   // Loop over the integration points
   for(unsigned ipt=0;ipt<n_intpt;ipt++)
    {
     // Assign values of the local coordinates s
     for(unsigned i=0;i<2;i++) { s[i] = integral_pt()->knot(ipt,i); }
     // Get the integral weight
     const double w = integral_pt()->weight(ipt);
     // Calculate the fluid shape and test functions, and their derivatives
     // w.r.t. the global coordinates
     const double J =
      dshape_and_dtest_eulerian_at_knot_linearised_axi_nst(ipt,psif,dpsifdx,
                                                           testf,dtestfdx);
     // Calculate the pressure shape and test functions
     pshape_linearised_axi_nst(s,psip,testp);
     // Premultiply the weights and the Jacobian of the mapping between
     // local and global coordinates
     const double W = w*J;
     // Allocate storage for the position and the derivative of the
     // mesh positions w.r.t. time
     Vector<double> interpolated_x(2,0.0);
     Vector<double> mesh_velocity(2,0.0);
     // Allocate storage for the velocity components (six of these)
     // and their derivatives w.r.t. time
     Vector<double> interpolated_u(6,0.0);
     Vector<double> dudt(6,0.0);
     // Allocate storage for the pressure components (two of these)
     Vector<double> interpolated_p(2,0.0);
     // Allocate storage for the derivatives of the velocity components
     // w.r.t. global coordinates (r and z)
     DenseMatrix<double> interpolated_dudx(6,2,0.0);
     // Calculate pressure at the integration point
     // -------------------------------------------
     // Loop over pressure degrees of freedom (associated with a single
     // pressure component) in the element
     for(unsigned l=0;l<n_pres;l++)
      {
       // Cache the shape function
       const double psip_ = psip(l);
       // Loop over the two pressure components
       for(unsigned i=0;i<2;i++)
        {
         // Get the value
         const double p_value = this->p_linearised_axi_nst(l,i);
         // Add contribution
         interpolated_p[i] += p_value*psip_;
        }
      } // End of loop over the pressure degrees of freedom in the element
     // Calculate velocities and their derivatives at the integration point
     // -------------------------------------------------------------------
     // Loop over the element's nodes
     for(unsigned l=0;l<n_node;l++)
      {
       // Cache the shape function
       const double psif_ = psif(l);
       // Loop over the two coordinate directions
       for(unsigned i=0;i<2;i++)
        {
         interpolated_x[i] += this->nodal_position(l,i)*psif_;
        }
       // Loop over the six velocity components
       for(unsigned i=0;i<6;i++)
        {
         // Get the value
         const double u_value = this->nodal_value(l,u_nodal_index[i]);
         // Add contribution
         interpolated_u[i] += u_value*psif_;
         // Add contribution to dudt
         dudt[i] += du_dt_linearised_axi_nst(l,i)*psif_;
         // Loop over two coordinate directions (for derivatives)
         for(unsigned j=0;j<2;j++)
          {
           interpolated_dudx(i,j) += u_value*dpsifdx(l,j);
          }
        }
      } // End of loop over the element's nodes
     // Get the mesh velocity if ALE is enabled
     if(!ALE_is_disabled)
      {
       // Loop over the element's nodes
       for(unsigned l=0;l<n_node;l++)
        {
         // Loop over the two coordinate directions
         for(unsigned i=0;i<2;i++)
          {
           mesh_velocity[i] += this->dnodal_position_dt(l,i)*psif(l);
          }
        }
      }
     // Get velocities and their derivatives from base flow problem
     // -----------------------------------------------------------
     // Allocate storage for the velocity components of the base state
     // solution (initialise to zero)
     Vector<double> base_flow_u(3,0.0);
     // Get the user-defined base state solution velocity components
     get_base_flow_u(time,ipt,interpolated_x,base_flow_u);
     // Allocate storage for the derivatives of the base state solution's
     // velocity components w.r.t. global coordinate (r and z)
     // N.B. the derivatives of the base flow components w.r.t. the
     // azimuthal coordinate direction (theta) are always zero since the
     // base flow is axisymmetric
     DenseMatrix<double> base_flow_dudx(3,2,0.0);
     // Get the derivatives of the user-defined base state solution
     // velocity components w.r.t. global coordinates
     get_base_flow_dudx(time,ipt,interpolated_x,base_flow_dudx);
     // Cache base flow velocities and their derivatives
     const double interpolated_ur = base_flow_u[0];
     const double interpolated_uz = base_flow_u[1];
     const double interpolated_utheta = base_flow_u[2];
     const double interpolated_durdr = base_flow_dudx(0,0);
     const double interpolated_durdz = base_flow_dudx(0,1);
     const double interpolated_duzdr = base_flow_dudx(1,0);
     const double interpolated_duzdz = base_flow_dudx(1,1);
     const double interpolated_duthetadr = base_flow_dudx(2,0);
     const double interpolated_duthetadz = base_flow_dudx(2,1);
     // Cache r-component of position
     const double r = interpolated_x[0];
     // Cache unknowns
     const double interpolated_UC = interpolated_u[0];
     const double interpolated_US = interpolated_u[1];
     const double interpolated_WC = interpolated_u[2];
     const double interpolated_WS = interpolated_u[3];
     const double interpolated_VC = interpolated_u[4];
     const double interpolated_VS = interpolated_u[5];
     const double interpolated_PC = interpolated_p[0];
     const double interpolated_PS = interpolated_p[1];
     // Cache derivatives of the unknowns
     const double interpolated_dUCdr = interpolated_dudx(0,0);
     const double interpolated_dUCdz = interpolated_dudx(0,1);
     const double interpolated_dUSdr = interpolated_dudx(1,0);
     const double interpolated_dUSdz = interpolated_dudx(1,1);
     const double interpolated_dWCdr = interpolated_dudx(2,0);
     const double interpolated_dWCdz = interpolated_dudx(2,1);
     const double interpolated_dWSdr = interpolated_dudx(3,0);
     const double interpolated_dWSdz = interpolated_dudx(3,1);
     const double interpolated_dVCdr = interpolated_dudx(4,0);
     const double interpolated_dVCdz = interpolated_dudx(4,1);
     const double interpolated_dVSdr = interpolated_dudx(5,0);
     const double interpolated_dVSdz = interpolated_dudx(5,1);
     // ==================
     // MOMENTUM EQUATIONS
     // ==================
     // Number of master nodes
     unsigned n_master = 1;
     // Storage for the weight of the shape function
     double hang_weight = 1.0;
     // Loop over the nodes for the test functions/equations
     for(unsigned l=0;l<n_node;l++)
      {
       // Cache test functions and their derivatives
       const double testf_ = testf(l);
       const double dtestfdr = dtestfdx(l,0);
       const double dtestfdz = dtestfdx(l,1);
       // Local boolean that indicates the hanging status of the node
       bool is_node_hanging = node_pt(l)->is_hanging();
       // If the node is hanging
       if(is_node_hanging)
        {
         // Get the hanging pointer
         hang_info_pt = node_pt(l)->hanging_pt();
         // Read out number of master nodes from hanging data
         n_master = hang_info_pt->nmaster();
        }
       // Otherwise the node is its own master
       else
        {
         n_master = 1;
        }
       // Loop over the master nodes
       for(unsigned m=0;m<n_master;m++)
        {
         // Loop over velocity components for equations
         for(unsigned i=0;i<6;i++)
          {
           // Get the equation number
           // -----------------------
           // If the node is hanging
           if(is_node_hanging)
            {
             // Get the equation number from the master node
             local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                              u_nodal_index[i]);
             // Get the hang weight from the master node
             hang_weight = hang_info_pt->master_weight(m);
            }
           // If the node is not hanging
           else
            {
             // Local equation number
             local_eqn = this->nodal_local_eqn(l,u_nodal_index[i]);
             // Node contributes with full weight
             hang_weight = 1.0;
            }
           // If it's not a boundary condition...
           if(local_eqn>= 0)
            {
             // initialise for residual calculation
             double sum = 0.0;
             switch(i)
              {
               // ---------------------------------------------
               // FIRST (RADIAL) MOMENTUM EQUATION: COSINE PART
               // ---------------------------------------------
              case 0:
               // Pressure gradient term
               sum += interpolated_PC*(testf_ + r*dtestfdr)*W*hang_weight;
               // Stress tensor terms
               sum -= visc_ratio*
                r*(1.0+Gamma[0])*interpolated_dUCdr*dtestfdr*W*hang_weight;
               sum -= visc_ratio*r*
                (interpolated_dUCdz + Gamma[0]*interpolated_dWCdr)
                *dtestfdz*W*hang_weight;
               sum += visc_ratio*(
                (k*Gamma[0]*interpolated_dVSdr)
                - (k*(2.0+Gamma[0])*interpolated_VS/r)
                - ((1.0+Gamma[0]+(k*k))*interpolated_UC/r))
                *testf_*W*hang_weight;
               // Inertial terms (du/dt)
               sum -= scaled_re_st*r*dudt[0]*testf_*W*hang_weight;
               // Inertial terms (convective)
               sum -=
                scaled_re*(r*interpolated_ur*interpolated_dUCdr
                           + r*interpolated_durdr*interpolated_UC
                           + k*interpolated_utheta*interpolated_US
                           - 2*interpolated_utheta*interpolated_VC
                           + r*interpolated_uz*interpolated_dUCdz
                           + r*interpolated_durdz*interpolated_WC)
                *testf_*W*hang_weight;
               // Mesh velocity terms
               if(!ALE_is_disabled)
                {
                 for(unsigned j=0;j<2;j++)
                  {
                   sum +=
                    scaled_re_st*r*mesh_velocity[j]
                    *interpolated_dudx(0,j)*testf_*W*hang_weight;
                  }
                }
               break;
 //asd
               // --------------------------------------------
               // SECOND (RADIAL) MOMENTUM EQUATION: SINE PART
               // --------------------------------------------
              case 1:
               // Pressure gradient term
               sum += interpolated_PS*(testf_ + r*dtestfdr)*W*hang_weight;
               // Stress tensor terms
               sum -= visc_ratio*
                r*(1.0+Gamma[0])*interpolated_dUSdr*dtestfdr*W*hang_weight;
               sum -= visc_ratio*r*
                (interpolated_dUSdz + Gamma[0]*interpolated_dWSdr)*
                dtestfdz*W*hang_weight;
               sum -= visc_ratio*(
                (k*Gamma[0]*interpolated_dVCdr)
                - (k*(2.0+Gamma[0])*interpolated_VC/r)
                + ((1.0+Gamma[0]+(k*k))*interpolated_US/r))*testf_*W*hang_weight;
               // Inertial terms (du/dt)
               sum -= scaled_re_st*r*dudt[1]*testf_*W*hang_weight;
               // Inertial terms (convective)
               sum -=
                scaled_re*(r*interpolated_ur*interpolated_dUSdr
                           + r*interpolated_durdr*interpolated_US
                           - k*interpolated_utheta*interpolated_UC
                           - 2*interpolated_utheta*interpolated_VS
                           + r*interpolated_uz*interpolated_dUSdz
                           + r*interpolated_durdz*interpolated_WS)*testf_*W*hang_weight;
               // Mesh velocity terms
               if(!ALE_is_disabled)
                {
                 for(unsigned j=0;j<2;j++)
                  {
                   sum +=
                    scaled_re_st*r*mesh_velocity[j]
                    *interpolated_dudx(1,j)*testf_*W*hang_weight;
                  }
                }
               break;
               // --------------------------------------------
               // THIRD (AXIAL) MOMENTUM EQUATION: COSINE PART
               // --------------------------------------------
              case 2:
               // Pressure gradient term
               sum  += r*interpolated_PC*dtestfdz*W*hang_weight;
               // Stress tensor terms
               sum -= visc_ratio*r*
                (interpolated_dWCdr + Gamma[1]*interpolated_dUCdz)
                *dtestfdr*W*hang_weight;
               sum -= visc_ratio*r*
                (1.0 + Gamma[1])*interpolated_dWCdz*dtestfdz*W*hang_weight;
               sum += visc_ratio*k*
                (Gamma[1]*interpolated_dVSdz - k*interpolated_WC/r)*testf_*W*hang_weight;
               // Inertial terms (du/dt)
               sum -= scaled_re_st*r*dudt[2]*testf_*W*hang_weight;
               // Inertial terms (convective)
               sum -=
                scaled_re*(r*interpolated_ur*interpolated_dWCdr
                           + r*interpolated_duzdr*interpolated_UC
                           + k*interpolated_utheta*interpolated_WS
                           + r*interpolated_uz*interpolated_dWCdz
                           + r*interpolated_duzdz*interpolated_WC)*testf_*W*hang_weight;
               // Mesh velocity terms
               if(!ALE_is_disabled)
                {
                 for(unsigned j=0;j<2;j++)
                  {
                   sum +=
                    scaled_re_st*r*mesh_velocity[j]
                    *interpolated_dudx(2,j)*testf_*W*hang_weight;
                  }
                }
               break;
               // -------------------------------------------
               // FOURTH (AXIAL) MOMENTUM EQUATION: SINE PART
               // -------------------------------------------
              case 3:
               // Pressure gradient term
               sum  += r*interpolated_PS*dtestfdz*W*hang_weight;
               // Stress tensor terms
               sum -= visc_ratio*r*
                (interpolated_dWSdr + Gamma[1]*interpolated_dUSdz)
                *dtestfdr*W*hang_weight;
               sum -= visc_ratio*r*
                (1.0+Gamma[1])*interpolated_dWSdz*dtestfdz*W*hang_weight;
               sum -= visc_ratio*k*
                (Gamma[1]*interpolated_dVCdz + k*interpolated_WS/r)*testf_*W*hang_weight;
               // Inertial terms (du/dt)
               sum -= scaled_re_st*r*dudt[3]*testf_*W*hang_weight;
               // Inertial terms (convective)
               sum -=
                scaled_re*(r*interpolated_ur*interpolated_dWSdr
                           + r*interpolated_duzdr*interpolated_US
                           - k*interpolated_utheta*interpolated_WC
                           + r*interpolated_uz*interpolated_dWSdz
                           + r*interpolated_duzdz*interpolated_WS)*testf_*W*hang_weight;
               // Mesh velocity terms
               if(!ALE_is_disabled)
                {
                 for(unsigned j=0;j<2;j++)
                  {
                   sum +=
                    scaled_re_st*r*mesh_velocity[j]
                    *interpolated_dudx(3,j)*testf_*W*hang_weight;
                  }
                }
               break;
               // ------------------------------------------------
               // FIFTH (AZIMUTHAL) MOMENTUM EQUATION: COSINE PART
               // ------------------------------------------------
              case 4:
               // Pressure gradient term
               sum -= k*interpolated_PS*testf_*W*hang_weight;
               // Stress tensor terms
               sum += visc_ratio*
                (-r*interpolated_dVCdr
                 - k*Gamma[0]*interpolated_US
                 + Gamma[0]*interpolated_VC)*dtestfdr*W*hang_weight;
               sum -= visc_ratio*
                (k*Gamma[0]*interpolated_WS + r*interpolated_dVCdz)*dtestfdz*W*hang_weight;
               sum += visc_ratio*
                (Gamma[0]*interpolated_dVCdr
                 + k*(2.0+Gamma[0])*interpolated_US/r
                 - (1.0+(k*k)+(k*k*Gamma[0]))*interpolated_VC/r)*testf_*W*hang_weight;
               // Inertial terms (du/dt)
               sum -= scaled_re_st*r*dudt[4]*testf_*W*hang_weight;
               // Inertial terms (convective)
               sum -=
                scaled_re*(r*interpolated_ur*interpolated_dVCdr
                           + r*interpolated_duthetadr*interpolated_UC
                           + k*interpolated_utheta*interpolated_VS
                           + interpolated_utheta*interpolated_UC
                           + interpolated_ur*interpolated_VC
                           + r*interpolated_uz*interpolated_dVCdz
                           + r*interpolated_duthetadz*interpolated_WC)*testf_*W*hang_weight;
               // Mesh velocity terms
               if(!ALE_is_disabled)
                {
                 for(unsigned j=0;j<2;j++)
                  {
                   sum +=
                    scaled_re_st*r*mesh_velocity[j]
                    *interpolated_dudx(4,j)*testf_*W*hang_weight;
                  }
                }
               break;
               // ----------------------------------------------
               // SIXTH (AZIMUTHAL) MOMENTUM EQUATION: SINE PART
               // ----------------------------------------------
              case 5:
               // Pressure gradient term
               sum += k*interpolated_PC*testf_*W*hang_weight;
               // Stress tensor terms
               sum += visc_ratio*
                (-r*interpolated_dVSdr
                 + k*Gamma[0]*interpolated_UC
                 + Gamma[0]*interpolated_VS)*dtestfdr*W*hang_weight;
               sum += visc_ratio*
                (k*Gamma[0]*interpolated_WC - r*interpolated_dVSdz)*dtestfdz*W*hang_weight;
               sum += visc_ratio*
                (Gamma[0]*interpolated_dVSdr
                 - k*(2.0+Gamma[0])*interpolated_UC/r
                 - (1.0+(k*k)+(k*k*Gamma[0]))*interpolated_VS/r)*testf_*W*hang_weight;
               // Inertial terms (du/dt)
               sum -= scaled_re_st*r*dudt[5]*testf_*W*hang_weight;
               // Inertial terms (convective)
               sum -=
                scaled_re*(r*interpolated_ur*interpolated_dVSdr
                           + r*interpolated_duthetadr*interpolated_US
                           - k*interpolated_utheta*interpolated_VC
                           + interpolated_utheta*interpolated_US
                           + interpolated_ur*interpolated_VS
                           + r*interpolated_uz*interpolated_dVSdz
                           + r*interpolated_duthetadz*interpolated_WS)*testf_*W*hang_weight;
               // Mesh velocity terms
               if(!ALE_is_disabled)
                {
                 for(unsigned j=0;j<2;j++)
                  {
                   sum +=
                    scaled_re_st*r*mesh_velocity[j]
                    *interpolated_dudx(5,j)*testf_*W*hang_weight;
                  }
                }
               break;
              } // End of switch statement for momentum equations
             // Add contribution to elemental residual vector
             residuals[local_eqn] += sum;
             // ======================
             // Calculate the Jacobian
             // ======================
             if(flag)
              {
               // Number of master nodes
               unsigned n_master2 = 1;
               // Storage for the weight of the shape function
               double hang_weight2 = 1.0;
               // Loop over the velocity nodes for columns
               for(unsigned l2=0;l2<n_node;l2++)
                {
                 // Cache velocity shape functions and their derivatives
                 const double psif_ = psif[l2];
                 const double dpsifdr = dpsifdx(l2,0);
                 const double dpsifdz = dpsifdx(l2,1);
                 // Local boolean that indicates the hanging status of the node
                 bool is_node2_hanging = node_pt(l2)->is_hanging();
                 // If the node is hanging
                 if(is_node2_hanging)
                  {
                   // Get the hanging pointer
                   hang_info2_pt = node_pt(l2)->hanging_pt();
                   // Read out number of master nodes from hanging data
                   n_master2 = hang_info2_pt->nmaster();
                  }
                 // Otherwise the node is its own master
                 else
                  {
                   n_master2 = 1;
                  }
                 // Loop over the master nodes
                 for(unsigned m2=0;m2<n_master2;m2++)
                  {
                   // Loop over the velocity components
                   for(unsigned i2=0;i2<6;i2++)
                    {
                     // Get the number of the unknown
                     // -----------------------------
                     // If the node is hanging
                     if(is_node2_hanging)
                      {
                       // Get the equation number from the master node
                       local_unknown =
                        this->local_hang_eqn(hang_info2_pt->master_node_pt(m2),
                                             u_nodal_index[i2]);
                       // Get the hang weight from the master node
                       hang_weight2 = hang_info2_pt->master_weight(m2);
                      }
                     // If the node is not hanging
                     else
                      {
                       // Local equation number
                       local_unknown =
                        this->nodal_local_eqn(l2,u_nodal_index[i2]);
                       // Node contributes with full weight
                       hang_weight2 = 1.0;
                      }
                     // If the unknown is not pinned
                     if(local_unknown >= 0)
                      {
                       // Different results for i and i2
                       switch(i)
{
                         // ---------------------------------------------
                         // FIRST (RADIAL) MOMENTUM EQUATION: COSINE PART
                         // ---------------------------------------------
                        case 0:
                         switch(i2)
{
                           // Radial velocity component (cosine part) U_k^C
                          case 0:
                           // Add the mass matrix entries
                           if(flag==2)
{
                             mass_matrix(local_eqn,local_unknown) +=
                              scaled_re_st*r*psif_*testf_*W*hang_weight*hang_weight2
                              *hang_weight*hang_weight2;
                            }
                           // Add contributions to the Jacobian matrix
                           // Stress tensor terms
                           jacobian(local_eqn,local_unknown)
                            -= visc_ratio*r*(1.0+Gamma[0])*dpsifdr*dtestfdr*W*hang_weight*hang_weight2;
                           jacobian(local_eqn,local_unknown)
                            -= visc_ratio*r*dpsifdz*dtestfdz*W*hang_weight*hang_weight2;
                           jacobian(local_eqn,local_unknown)
                            -= visc_ratio*(1.0+Gamma[0]+(k*k))*psif_*testf_*W*hang_weight*hang_weight2/r;
                           // Inertial terms (du/dt)
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re_st*r*node_pt(l2)->time_stepper_pt()->weight(1,0)*
                            psif_*testf_*W*hang_weight*hang_weight2;
                           // Inertial terms (convective)
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re*r*(psif_*interpolated_durdr
                                         + interpolated_ur*dpsifdr
                                         + interpolated_uz*dpsifdz)*testf_*W*hang_weight*hang_weight2;
                           // Mesh velocity terms
                           if(!ALE_is_disabled)
{
                             for(unsigned j=0;j<2;j++)
{
                               jacobian(local_eqn,local_unknown) +=
                                scaled_re_st*r*mesh_velocity[j]
                                *dpsifdx(l2,j)*testf_*W*hang_weight*hang_weight2;
                              }
                            }
                           break;
                           // Radial velocity component (sine part) U_k^S
                          case 1:
                           // Convective term
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re*k*interpolated_utheta*psif_*testf_*W*hang_weight*hang_weight2;
                           break;
                           // Axial velocity component (cosine part) W_k^C
                          case 2:
                           // Stress tensor term
                           jacobian(local_eqn,local_unknown) -=
                            visc_ratio*Gamma[0]*r*dpsifdr*dtestfdz*W*hang_weight*hang_weight2;
                           // Convective term
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re*r*interpolated_durdz*psif_*testf_*W*hang_weight*hang_weight2;
                           break;
                           // Axial velocity component (sine part) W_k^S
                           // has no contribution
                          case 3:
                           break;
                           // Azimuthal velocity component (cosine part) V_k^C
                          case 4:
                           // Convective term
                           jacobian(local_eqn,local_unknown) +=
                            scaled_re*2*interpolated_utheta*psif_*testf_*W*hang_weight*hang_weight2;
                           break;
                           // Azimuthal velocity component (sine part) V_k^S
                          case 5:
                           // Stress tensor term
                           jacobian(local_eqn,local_unknown) += visc_ratio*(
                            (Gamma[0]*k*dpsifdr) - (k*(2.0+Gamma[0])*psif_/r))*testf_*W*hang_weight*hang_weight2;
                           break;
                          } // End of first (radial) momentum equation
                         break;
                         // --------------------------------------------
                         // SECOND (RADIAL) MOMENTUM EQUATION: SINE PART
                         // --------------------------------------------
                        case 1:
                         switch(i2)
{
                           // Radial velocity component (cosine part) U_k^C
                          case 0:
                           // Convective term
                           jacobian(local_eqn,local_unknown) +=
                            scaled_re*k*interpolated_utheta*psif_*testf_*W*hang_weight*hang_weight2;
                           break;
                           // Radial velocity component (sine part) U_k^S
                          case 1:
                           // Add the mass matrix entries
                           if(flag==2)
{
                             mass_matrix(local_eqn,local_unknown) +=
                              scaled_re_st*r*psif_*testf_*W*hang_weight*hang_weight2;
                            }
                           // Add contributions to the Jacobian matrix
                           // Stress tensor terms
                           jacobian(local_eqn,local_unknown)
                            -= visc_ratio*r*(1.0+Gamma[0])*dpsifdr*dtestfdr*W*hang_weight*hang_weight2;
                           jacobian(local_eqn,local_unknown)
                            -= visc_ratio*r*dpsifdz*dtestfdz*W*hang_weight*hang_weight2;
                           jacobian(local_eqn,local_unknown)
                            -= visc_ratio*(1.0+Gamma[0]+(k*k))*psif_*testf_*W*hang_weight*hang_weight2/r;
                           // Inertial terms (du/dt)
                           jacobian(local_eqn,local_unknown)
                            -= scaled_re_st*r*node_pt(l2)->time_stepper_pt()->weight(1,0)*
                            psif_*testf_*W*hang_weight*hang_weight2;
                           // Inertial terms (convective)
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re*r*(psif_*interpolated_durdr
                                         + interpolated_ur*dpsifdr
                                         + interpolated_uz*dpsifdz)*testf_*W*hang_weight*hang_weight2;
                           // Mesh velocity terms
                           if(!ALE_is_disabled)
{
                             for(unsigned j=0;j<2;j++)
{
                               jacobian(local_eqn,local_unknown) +=
                                scaled_re_st*r*mesh_velocity[j]
                                *dpsifdx(l2,j)*testf_*W*hang_weight*hang_weight2;
                              }
                            }
                           break;
                           // Axial velocity component (cosine part) W_k^C
                           // has no contribution
                          case 2:
                           break;
                           // Axial velocity component (sine part) W_k^S
                          case 3:
                           // Stress tensor term
                           jacobian(local_eqn,local_unknown) -=
                            visc_ratio*Gamma[0]*r*dpsifdr*dtestfdz*W*hang_weight*hang_weight2;
                           // Convective term
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re*r*interpolated_durdz*psif_*testf_*W*hang_weight*hang_weight2;
                           break;
                           // Azimuthal velocity component (cosine part) V_k^C
                          case 4:
                           // Stress tensor terms
                           jacobian(local_eqn,local_unknown) -= visc_ratio*(
                            (Gamma[0]*k*dpsifdr)
                            - (k*(2.0+Gamma[0])*psif_/r))*testf_*W*hang_weight*hang_weight2;
                           break;
                           // Azimuthal velocity component (sine part) V_k^S
                          case 5:
                           // Convective term
                           jacobian(local_eqn,local_unknown) +=
                            scaled_re*2*interpolated_utheta*psif_*testf_*W*hang_weight*hang_weight2;
                           break;
                          } // End of second (radial) momentum equation
                         break;
                         // --------------------------------------------
                         // THIRD (AXIAL) MOMENTUM EQUATION: COSINE PART
                         // --------------------------------------------
                        case 2:
                         switch(i2)
{
                           // Radial velocity component (cosine part) U_k^C
                          case 0:
                           // Stress tensor term
                           jacobian(local_eqn,local_unknown) -=
                            visc_ratio*r*Gamma[1]*dpsifdz*dtestfdr*W*hang_weight*hang_weight2;
                           // Convective term
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re*r*psif_*interpolated_duzdr*testf_*W*hang_weight*hang_weight2;
                           break;
                           // Radial velocity component (sine part) U_k^S
                           // has no contribution
                          case 1:
                           break;
                           // Axial velocity component (cosine part) W_k^C
                          case 2:
                           // Add the mass matrix entries
                           if(flag==2)
{
                             mass_matrix(local_eqn,local_unknown) +=
                              scaled_re_st*r*psif_*testf_*W*hang_weight*hang_weight2;
                            }
                           // Add contributions to the Jacobian matrix
                           // Stress tensor terms
                           jacobian(local_eqn,local_unknown) -=
                            visc_ratio*r*dpsifdr*dtestfdr*W*hang_weight*hang_weight2;
                           jacobian(local_eqn,local_unknown) -=
                            visc_ratio*r*(1.0+Gamma[1])*dpsifdz*dtestfdz*W*hang_weight*hang_weight2;
                           jacobian(local_eqn,local_unknown) -=
                            visc_ratio*k*k*psif_*testf_*W*hang_weight*hang_weight2/r;
                           // Inertial terms (du/dt)
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re_st*r*node_pt(l2)->time_stepper_pt()->weight(1,0)*
                            psif_*testf_*W*hang_weight*hang_weight2;
                           // Inertial terms (convective)
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re*r*(interpolated_ur*dpsifdr
                                         + psif_*interpolated_duzdz
                                         + interpolated_uz*dpsifdz)*testf_*W*hang_weight*hang_weight2;
                           // Mesh velocity terms
                           if(!ALE_is_disabled)
{
                             for(unsigned j=0;j<2;j++)
{
                               jacobian(local_eqn,local_unknown) +=
                                scaled_re_st*r*mesh_velocity[j]
                                *dpsifdx(l2,j)*testf_*W*hang_weight*hang_weight2;
                              }
                            }
                           break;
                           // Axial velocity component (sine part) W_k^S
                          case 3:
                           // Convective term
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re*k*interpolated_utheta*psif_*testf_*W*hang_weight*hang_weight2;
                           break;
                           // Azimuthal velocity component (cosine part) V_k^C
                           // has no contribution
                          case 4:
                           break;
                           // Azimuthal velocity component (sine part) V_k^S
                          case 5:
                           // Stress tensor term
                           jacobian(local_eqn,local_unknown) +=
                            visc_ratio*Gamma[1]*k*dpsifdz*testf_*W*hang_weight*hang_weight2;
                           break;
                          } // End of third (axial) momentum equation
                         break;
                         // -------------------------------------------
                         // FOURTH (AXIAL) MOMENTUM EQUATION: SINE PART
                         // -------------------------------------------
                        case 3:
                         switch(i2)
{
                           // Radial velocity component (cosine part) U_k^C
                           // has no contribution
                          case 0:
                           break;
                           // Radial velocity component (sine part) U_k^S
                          case 1:
                           // Stress tensor term
                           jacobian(local_eqn,local_unknown) -=
                            visc_ratio*r*Gamma[1]*dpsifdz*dtestfdr*W*hang_weight*hang_weight2;
                           // Convective term
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re*r*psif_*interpolated_duzdr*testf_*W*hang_weight*hang_weight2;
                           break;
                           // Axial velocity component (cosine part) W_k^S
                          case 2:
                           // Convective term
                           jacobian(local_eqn,local_unknown) +=
                            scaled_re*k*interpolated_utheta*psif_*testf_*W*hang_weight*hang_weight2;
                           break;
                           // Axial velocity component (sine part) W_k^S
                          case 3:
                           // Add the mass matrix entries
                           if(flag==2)
{
                             mass_matrix(local_eqn,local_unknown) +=
                              scaled_re_st*r*psif_*testf_*W*hang_weight*hang_weight2;
                            }
                           // Add contributions to the Jacobian matrix
                           // Stress tensor terms
                           jacobian(local_eqn,local_unknown) -=
                            visc_ratio*r*dpsifdr*dtestfdr*W*hang_weight*hang_weight2;
                           jacobian(local_eqn,local_unknown) -=
                            visc_ratio*r*(1.0+Gamma[1])*dpsifdz*dtestfdz*W*hang_weight*hang_weight2;
                           jacobian(local_eqn,local_unknown) -=
                            visc_ratio*k*k*psif_*testf_*W*hang_weight*hang_weight2/r;
                           // Inertial terms (du/dt)
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re_st*r*node_pt(l2)->time_stepper_pt()->weight(1,0)*
                            psif_*testf_*W*hang_weight*hang_weight2;
                           // Inertial terms (convective)
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re*r*(interpolated_ur*dpsifdr
                                         + psif_*interpolated_duzdz
                                         + interpolated_uz*dpsifdz)*testf_*W*hang_weight*hang_weight2;
                           // Mesh velocity terms
                           if(!ALE_is_disabled)
{
                             for(unsigned j=0;j<2;j++)
{
                               jacobian(local_eqn,local_unknown) +=
                                scaled_re_st*r*mesh_velocity[j]
                                *dpsifdx(l2,j)*testf_*W*hang_weight*hang_weight2;
                              }
                            }
                           break;
                           // Azimuthal velocity component (cosine part) V_k^C
                          case 4:
                           // Stress tensor term
                           jacobian(local_eqn,local_unknown) -=
                            visc_ratio*Gamma[1]*k*dpsifdz*testf_*W*hang_weight*hang_weight2;
                           break;
                           // Azimuthal velocity component (sine part) V_k^S
                           // has no contribution
                          case 5:
                           break;
                          } // End of fourth (axial) momentum equation
                         break;
                         // ------------------------------------------------
                         // FIFTH (AZIMUTHAL) MOMENTUM EQUATION: COSINE PART
                         // ------------------------------------------------
                        case 4:
                         switch(i2)
{
                           // Radial velocity component (cosine part) U_k^C
                          case 0:
                           // Convective terms
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re*(r*interpolated_duthetadr
                                       + interpolated_utheta)*psif_*testf_*W*hang_weight*hang_weight2;
                           break;
                           // Radial velocity component (sine part) U_k^S
                          case 1:
                           // Stress tensor terms
                           jacobian(local_eqn,local_unknown) += visc_ratio*k*psif_*(
                            ((2.0+Gamma[0])*testf_/r) - (Gamma[0]*dtestfdr))*W*hang_weight*hang_weight2;
                           break;
                           // Axial velocity component (cosine part) W_k^C
                          case 2:
                           // Convective term
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re*r*psif_*interpolated_duthetadz*testf_*W*hang_weight*hang_weight2;
                           break;
                           // Axial velocity component (sine part) W_k^S
                          case 3:
                           // Stress tensor term
                           jacobian(local_eqn,local_unknown) -=
                            visc_ratio*k*Gamma[0]*psif_*dtestfdz*W*hang_weight*hang_weight2;
                           break;
                           // Azimuthal velocity component (cosine part) V_k^C
                          case 4:
                           // Add the mass matrix entries
                           if(flag==2)
{
                             mass_matrix(local_eqn,local_unknown) +=
                              scaled_re_st*r*psif_*testf_*W*hang_weight*hang_weight2;
                            }
                           // Add contributions to the Jacobian matrix
                           // Stress tensor terms
                           jacobian(local_eqn,local_unknown) +=
                            visc_ratio*(Gamma[0]*psif_ - r*dpsifdr)*dtestfdr*W*hang_weight*hang_weight2;
                           jacobian(local_eqn,local_unknown) -=
                            visc_ratio*r*dpsifdz*dtestfdz*W*hang_weight*hang_weight2;
                           jacobian(local_eqn,local_unknown) +=
                            visc_ratio*(Gamma[0]*dpsifdr
                                        - (1.0+(k*k)+(k*k*Gamma[0]))*psif_/r)*testf_*W*hang_weight*hang_weight2;
                           // Inertial terms (du/dt)
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re_st*r*node_pt(l2)->time_stepper_pt()->weight(1,0)*
                            psif_*testf_*W*hang_weight*hang_weight2;
                           // Inertial terms (convective)
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re*(r*interpolated_ur*dpsifdr
                                       + interpolated_ur*psif_
                                       + r*interpolated_uz*dpsifdz)*testf_*W*hang_weight*hang_weight2;
                           // Mesh velocity terms
                           if(!ALE_is_disabled)
{
                             for(unsigned j=0;j<2;j++)
{
                               jacobian(local_eqn,local_unknown) +=
                                scaled_re_st*r*mesh_velocity[j]
                                *dpsifdx(l2,j)*testf_*W*hang_weight*hang_weight2;
                              }
                            }
                           break;
                           // Azimuthal velocity component (sine part) V_k^S
                          case 5:
                           // Convective term
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re*k*interpolated_utheta*psif_*testf_*W*hang_weight*hang_weight2;
                           break;
                          } // End of fifth (azimuthal) momentum equation
                         break;
                         // ----------------------------------------------
                         // SIXTH (AZIMUTHAL) MOMENTUM EQUATION: SINE PART
                         // ----------------------------------------------
                        case 5:
                         switch(i2)
{
                           // Radial velocity component (cosine part) U_k^C
                          case 0:
                           // Stress tensor terms
                           jacobian(local_eqn,local_unknown) += visc_ratio*k*psif_*(
                            (Gamma[0]*dtestfdr) - ((2.0+Gamma[0])*testf_/r))*W*hang_weight*hang_weight2;
                           break;
                           // Radial velocity component (sine part) U_k^S
                          case 1:
                           // Convective terms
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re*(r*interpolated_duthetadr
                                       + interpolated_utheta)*psif_*testf_*W*hang_weight*hang_weight2;
                           break;
                           // Axial velocity component (cosine part) W_k^C
                          case 2:
                           // Stress tensor term
                           jacobian(local_eqn,local_unknown) +=
                            visc_ratio*k*Gamma[0]*psif_*dtestfdz*W*hang_weight*hang_weight2;
                           break;
                           // Axial velocity component (sine part) W_k^S
                          case 3:
                           // Convective term
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re*r*psif_*interpolated_duthetadz*testf_*W*hang_weight*hang_weight2;
                           break;
                           // Azimuthal velocity component (cosine part) V_k^C
                          case 4:
                           // Convective term
                           jacobian(local_eqn,local_unknown) +=
                            scaled_re*k*interpolated_utheta*psif_*testf_*W*hang_weight*hang_weight2;
                           break;
                           // Azimuthal velocity component (sine part) V_k^S
                          case 5:
                           // Add the mass matrix entries
                           if(flag==2)
{
                             mass_matrix(local_eqn,local_unknown) +=
                              scaled_re_st*r*psif_*testf_*W*hang_weight*hang_weight2;
                            }
                           // Add contributions to the Jacobian matrix
                           // Stress tensor terms
                           jacobian(local_eqn,local_unknown) +=
                            visc_ratio*(Gamma[0]*psif_ - r*dpsifdr)*dtestfdr*W*hang_weight*hang_weight2;
                           jacobian(local_eqn,local_unknown) -=
                            visc_ratio*r*dpsifdz*dtestfdz*W*hang_weight*hang_weight2;
                           jacobian(local_eqn,local_unknown) +=
                            visc_ratio*(Gamma[0]*dpsifdr
                                        - (1.0+(k*k)+(k*k*Gamma[0]))*psif_/r)*testf_*W*hang_weight*hang_weight2;
                           // Inertial terms (du/dt)
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re_st*r*node_pt(l2)->time_stepper_pt()->weight(1,0)*
                            psif_*testf_*W*hang_weight*hang_weight2;
                           // Convective terms
                           jacobian(local_eqn,local_unknown) -=
                            scaled_re*(r*interpolated_ur*dpsifdr
                                       + interpolated_ur*psif_
                                       + r*interpolated_uz*dpsifdz)*testf_*W*hang_weight*hang_weight2;
                           // Mesh velocity terms
                           if(!ALE_is_disabled)
{
                             for(unsigned j=0;j<2;j++)
{
                               jacobian(local_eqn,local_unknown) +=
                                scaled_re_st*r*mesh_velocity[j]
                                *dpsifdx(l2,j)*testf_*W*hang_weight*hang_weight2;
                              }
                            }
                           break;
                          } // End of sixth (azimuthal) momentum equation
                         break;
                        }
                      } // End of if not boundary condition statement
                    } // End of loop over velocity components
                  } // End of loop over master (m2) nodes
                } // End of loop over the velocity nodes (l2)
               // Loop over the pressure shape functions
               for(unsigned l2=0;l2<n_pres;l2++)
                {
                 // If the pressure dof is hanging
                 if(pressure_dof_is_hanging[l2])
                  {
                   // Pressure dof is hanging so it must be nodal-based
                   hang_info2_pt =
                    pressure_node_pt(l2)->hanging_pt(p_index[0]);
                   // Get the number of master nodes from the pressure node
                   n_master2 = hang_info2_pt->nmaster();
                  }
                 // Otherwise the node is its own master
                 else
                  {
                   n_master2 = 1;
                  }
                 // Loop over the master nodes
                 for(unsigned m2=0;m2<n_master2;m2++)
                  {
                   // Loop over the two pressure components
                   for(unsigned i2=0;i2<2;i2++)
                    {
                     // Get the number of the unknown
                     // -----------------------------
                     // If the pressure dof is hanging
                     if(pressure_dof_is_hanging[l2])
                      {
                       // Get the unknown from the node
                       local_unknown =
                        local_hang_eqn(hang_info2_pt->master_node_pt(m2),
                                       p_index[i2]);
                       // Get the weight from the hanging object
                       hang_weight2 = hang_info2_pt->master_weight(m2);
                      }
                     else
                      {
                       local_unknown = p_local_eqn(l2,i2);
                       hang_weight2 = 1.0;
                      }
                     // If the unknown is not pinned
                     if(local_unknown >= 0)
                      {
                       // Add in contributions to momentum equations
                       switch(i)
{
                         // ---------------------------------------------
                         // FIRST (RADIAL) MOMENTUM EQUATION: COSINE PART
                         // ---------------------------------------------
                        case 0:
                         switch(i2)
{
                           // Cosine part P_k^C
                          case 0:
                           jacobian(local_eqn,local_unknown) +=
                            psip[l2]*(testf_ + r*dtestfdr)*W*hang_weight*hang_weight2;
                           break;
                           // Sine part P_k^S has no contribution
                          case 1:
                           break;
                          } // End of first (radial) momentum equation
                         break;
                         // --------------------------------------------
                         // SECOND (RADIAL) MOMENTUM EQUATION: SINE PART
                         // --------------------------------------------
                        case 1:
                         switch(i2)
{
                           // Cosine part P_k^C has no contribution
                          case 0:
                           break;
                           // Sine part P_k^S
                          case 1:
                           jacobian(local_eqn,local_unknown)
                            += psip[l2]*(testf_ + r*dtestfdr)*W*hang_weight*hang_weight2;
                           break;
                          } // End of second (radial) momentum equation
                         break;
                         // --------------------------------------------
                         // THIRD (AXIAL) MOMENTUM EQUATION: COSINE PART
                         // --------------------------------------------
                        case 2:
                         switch(i2)
{
                           // Cosine part P_k^C
                          case 0:
                           jacobian(local_eqn,local_unknown) +=
                            r*psip[l2]*dtestfdz*W*hang_weight*hang_weight2;
                           break;
                           // Sine part P_k^S has no contribution
                          case 1:
                           break;
                          } // End of third (axial) momentum equation
                         break;
                         // -------------------------------------------
                         // FOURTH (AXIAL) MOMENTUM EQUATION: SINE PART
                         // -------------------------------------------
                        case 3:
                         switch(i2)
{
                           // Cosine part P_k^C has no contribution
                          case 0:
                           break;
                           // Sine part P_k^S
                          case 1:
                           jacobian(local_eqn,local_unknown) +=
                            r*psip[l2]*dtestfdz*W*hang_weight*hang_weight2;
                           break;
                          } // End of fourth (axial) momentum equation
                         break;
                         // ------------------------------------------------
                         // FIFTH (AZIMUTHAL) MOMENTUM EQUATION: COSINE PART
                         // ------------------------------------------------
                        case 4:
                         switch(i2)
{
                           // Cosine part P_k^C has no contribution
                          case 0:
                           break;
                           // Sine part P_k^S
                          case 1:
                           jacobian(local_eqn,local_unknown) -=
                            k*psip[l2]*testf_*W*hang_weight*hang_weight2;
                           break;
                          } // End of fifth (azimuthal) momentum equation
                         break;
                         // ----------------------------------------------
                         // SIXTH (AZIMUTHAL) MOMENTUM EQUATION: SINE PART
                         // ----------------------------------------------
                        case 5:
                         switch(i2)
{
                           // Cosine part P_k^C
                          case 0:
                           jacobian(local_eqn,local_unknown) +=
                            k*psip[l2]*testf_*W*hang_weight*hang_weight2;
                           break;
                           // Sine part P_k^S has no contribution
                          case 1:
                           break;
                          } // End of sixth (azimuthal) momentum equation
                        } // End of add in contributions to different equations
                      } // End of if unknown is not pinned statement
                    } // End of loop over pressure components
                  } // End of loop over master (m2) nodes
                } // End of loop over pressure "nodes"
              }// End of Jacobian calculation
            } // End of if not boundary condition statement
          } // End of loop over velocity components
        } // End of loop over master (m) nodes
      } // End of loop over nodes
     // ====================
     // CONTINUITY EQUATIONS
     // ====================
     // Loop over the pressure shape functions
     for(unsigned l=0;l<n_pres;l++)
      {
       // Cache test function
       const double testp_ = testp[l];
       // If the pressure dof is hanging
       if(pressure_dof_is_hanging[l])
        {
         // Pressure dof is hanging so it must be nodal-based
         hang_info_pt = pressure_node_pt(l)->hanging_pt(p_index[0]);
         //Get the number of master nodes from the pressure node
         n_master = hang_info_pt->nmaster();
        }
       // Otherwise the node is its own master
       else
        {
         n_master = 1;
        }
       // Loop over the master nodes
       for(unsigned m=0;m<n_master;m++)
        {
         // Loop over the two pressure components
         for(unsigned i=0;i<2;i++)
          {
           // Get the equation number
           // -----------------------
           // If the pressure dof is hanging
           if(pressure_dof_is_hanging[l])
            {
             // Get the equation number from the master node
             local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                              p_index[i]);
             // Get the hang weight from the master node
             hang_weight = hang_info_pt->master_weight(m);
            }
           else
            {
             // Local equation number
             local_eqn = this->p_local_eqn(l,i);
             // Node contributes with full weight
             hang_weight = 1.0;
            }
           // If it's not a boundary condition...
           if(local_eqn >= 0)
            {
             switch(i)
              {
               // --------------------------------------
               // FIRST CONTINUITY EQUATION: COSINE PART
               // --------------------------------------
              case 0:
               // Gradient terms
               residuals[local_eqn] +=
                (interpolated_UC + r*interpolated_dUCdr
                 + k*interpolated_VS + r*interpolated_dWCdz)*testp_*W*hang_weight;
               break;
               // -------------------------------------
               // SECOND CONTINUITY EQUATION: SINE PART
               // -------------------------------------
              case 1:
               // Gradient terms
               residuals[local_eqn] +=
                (interpolated_US + r*interpolated_dUSdr
                 - k*interpolated_VC + r*interpolated_dWSdz)*testp_*W*hang_weight;
               break;
              }
             // ======================
             // Calculate the Jacobian
             // ======================
             if(flag)
              {
               // Number of master nodes
               unsigned n_master2 = 1;
               // Storage for the weight of the shape function
               double hang_weight2 = 1.0;
               // Loop over the velocity nodes for columns
               for(unsigned l2=0;l2<n_node;l2++)
                {
                 // Cache velocity shape functions and their derivatives
                 const double psif_ = psif[l2];
                 const double dpsifdr = dpsifdx(l2,0);
                 const double dpsifdz = dpsifdx(l2,1);
                 // Local boolean to indicate whether the node is hanging
                 bool is_node2_hanging = node_pt(l2)->is_hanging();
                 // If the node is hanging
                 if(is_node2_hanging)
                  {
                   // Get the hanging pointer
                   hang_info2_pt = node_pt(l2)->hanging_pt();
                   // Read out number of master nodes from hanging data
                   n_master2 = hang_info2_pt->nmaster();
                  }
                 // Otherwise the node is its own master
                 else
                  {
                   n_master2 = 1;
                  }
                 // Loop over the master nodes
                 for(unsigned m2=0;m2<n_master2;m2++)
                  {
                   // Loop over the velocity components
                   for(unsigned i2=0;i2<6;i2++)
                    {
                     // Get the number of the unknown
                     // -----------------------------
                     // If the node is hanging
                     if(is_node2_hanging)
                      {
                       // Get the equation number from the master node
                       local_unknown =
                        local_hang_eqn(hang_info2_pt->master_node_pt(m2),
                                       u_nodal_index[i2]);
                       // Get the hang weight from the master node
                       hang_weight2 = hang_info2_pt->master_weight(m2);
                      }
                     // If the node is not hanging
                     else
                      {
                       // Local equation number
                       local_unknown =
                        this->nodal_local_eqn(l2,u_nodal_index[i2]);
                       // Node contributes with full weight
                       hang_weight2 = 1.0;
                      }
                     // If the unknown is not pinned
                     if(local_unknown >= 0)
                      {
                       // Different results for i and i2
                       switch(i)
{
                         // --------------------------------------
                         // FIRST CONTINUITY EQUATION: COSINE PART
                         // --------------------------------------
                        case 0:
                         switch(i2)
{
                           // Radial velocity component (cosine part) U_k^C
                          case 0:
                           jacobian(local_eqn,local_unknown) +=
                            (psif_ + r*dpsifdr)*testp_*W*hang_weight*hang_weight2;
                           break;
                           // Radial velocity component (sine part) U_k^S
                           // has no contribution
                          case 1:
                           break;
                           // Axial velocity component (cosine part) W_k^C
                          case 2:
                           jacobian(local_eqn,local_unknown) +=
                            r*dpsifdz*testp_*W*hang_weight*hang_weight2;
                           break;
                           // Axial velocity component (sine part) W_k^S
                           // has no contribution
                          case 3:
                           break;
                           // Azimuthal velocity component (cosine part) V_k^C
                           // has no contribution
                          case 4:
                           break;
                           // Azimuthal velocity component (sine part) V_k^S
                          case 5:
                           jacobian(local_eqn,local_unknown) +=
                            k*psif_*testp_*W*hang_weight*hang_weight2;
                           break;
                          } // End of first continuity equation
                         break;
                         // -------------------------------------
                         // SECOND CONTINUITY EQUATION: SINE PART
                         // -------------------------------------
                        case 1:
                         switch(i2)
{
                           // Radial velocity component (cosine part) U_k^C
                           // has no contribution
                          case 0:
                           break;
                           // Radial velocity component (sine part) U_k^S
                          case 1:
                           jacobian(local_eqn,local_unknown) +=
                            (psif_ + r*dpsifdr)*testp_*W*hang_weight*hang_weight2;
                           break;
                           // Axial velocity component (cosine part) W_k^C
                           // has no contribution
                          case 2:
                           break;
                           // Axial velocity component (sine part) W_k^S
                          case 3:
                           jacobian(local_eqn,local_unknown) +=
                            r*dpsifdz*testp_*W*hang_weight*hang_weight2;
                           break;
                           // Azimuthal velocity component (cosine part) V_k^C
                          case 4:
                           jacobian(local_eqn,local_unknown) -=
                            k*psif_*testp_*W*hang_weight*hang_weight2;
                           break;
                           // Azimuthal velocity component (sine part) V_k^S
                           // has no contribution
                          case 5:
                           break;
                          } // End of second continuity equation
                         break;
                        }
                      } // End of if unknown is not pinned statement
                    } // End of loop over velocity components
                  } // End of loop over master (m2) nodes
                } // End of loop over velocity nodes
               // Real and imaginary pressure components, P_k^C and P_k^S,
               // have no contribution to Jacobian
              } // End of Jacobian calculation
            } // End of if not boundary condition statement
          } // End of loop over the two pressure components
        } // End of loop over master nodes
      } // End of loop over pressure nodes
    } // End of loop over integration points
  } // End of fill_in_generic_residual_contribution_linearised_axi_nst(...)
References oomph::LinearisedAxisymmetricNavierStokesEquations::ALE_is_disabled, oomph::LinearisedAxisymmetricNavierStokesEquations::azimuthal_mode_number(), oomph::LinearisedAxisymmetricNavierStokesEquations::density_ratio(), oomph::FiniteElement::dnodal_position_dt(), oomph::LinearisedAxisymmetricNavierStokesEquations::dshape_and_dtest_eulerian_at_knot_linearised_axi_nst(), oomph::LinearisedAxisymmetricNavierStokesEquations::du_dt_linearised_axi_nst(), oomph::LinearisedAxisymmetricNavierStokesEquations::Gamma, oomph::LinearisedAxisymmetricNavierStokesEquations::get_base_flow_dudx(), oomph::LinearisedAxisymmetricNavierStokesEquations::get_base_flow_u(), oomph::Node::hanging_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::Node::is_hanging(), J, j, k, oomph::Integral::knot(), oomph::RefineableElement::local_hang_eqn(), m, m2(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::LinearisedAxisymmetricNavierStokesEquations::npres_linearised_axi_nst(), oomph::Integral::nweight(), oomph::LinearisedAxisymmetricNavierStokesEquations::p_index_linearised_axi_nst(), oomph::LinearisedAxisymmetricNavierStokesEquations::p_linearised_axi_nst(), oomph::LinearisedAxisymmetricNavierStokesEquations::p_local_eqn(), pressure_node_pt(), oomph::LinearisedAxisymmetricNavierStokesEquations::pshape_linearised_axi_nst(), UniformPSDSelfTest::r, oomph::LinearisedAxisymmetricNavierStokesEquations::re(), oomph::LinearisedAxisymmetricNavierStokesEquations::re_st(), s, oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Data::time_stepper_pt(), oomph::LinearisedAxisymmetricNavierStokesEquations::u_index_linearised_axi_nst(), oomph::LinearisedAxisymmetricNavierStokesEquations::viscosity_ratio(), w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and oomph::TimeStepper::weight().
fill_in_generic_residual_contribution_linearised_axi_nst() [2/2]
void oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) private virtual
Add element's contribution to the elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector
Reimplemented from oomph::LinearisedAxisymmetricNavierStokesEquations.
further_build() [1/2]
void oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build () inline virtual
Further build: pass the pointers down to the sons.
Reimplemented from oomph::RefineableElement.
Reimplemented in oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement, and oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement.
   {
    // Find the father element
    RefineableLinearisedAxisymmetricNavierStokesEquations*
     cast_father_element_pt
     = dynamic_cast<RefineableLinearisedAxisymmetricNavierStokesEquations*>
     (this->father_element_pt());
    // Set the viscosity ratio pointer
    this->Viscosity_Ratio_pt = cast_father_element_pt->viscosity_ratio_pt();
    // Set the density ratio pointer
    this->Density_Ratio_pt = cast_father_element_pt->density_ratio_pt();
    // Set pointer to global Reynolds number
    this->Re_pt = cast_father_element_pt->re_pt();
    // Set pointer to global Reynolds number x Strouhal number (=Womersley)
    this->ReSt_pt = cast_father_element_pt->re_st_pt();
    // Set pointer to azimuthal mode number
    this->Azimuthal_Mode_Number_pt =
     cast_father_element_pt->azimuthal_mode_number_pt();
    // Set pointer to global Reynolds number x inverse Froude number
 //   this->ReInvFr_pt = cast_father_element_pt->re_invfr_pt();
    //Set pointer to the global Reynolds number x inverse Rossby number
 //   this->ReInvRo_pt = cast_father_element_pt->re_invro_pt();
    //Set pointer to global gravity Vector
 //   this->G_pt = cast_father_element_pt->g_pt();
    //Set pointer to body force function
 //   this->Body_force_fct_pt = cast_father_element_pt->body_force_fct_pt();
    //Set pointer to volumetric source function
 //   this->Source_fct_pt = cast_father_element_pt->source_fct_pt();
    // Set the ALE_is_disabled flag
    this->ALE_is_disabled = cast_father_element_pt->ALE_is_disabled;
   }
References oomph::LinearisedAxisymmetricNavierStokesEquations::ALE_is_disabled, oomph::LinearisedAxisymmetricNavierStokesEquations::Azimuthal_Mode_Number_pt, oomph::LinearisedAxisymmetricNavierStokesEquations::azimuthal_mode_number_pt(), oomph::LinearisedAxisymmetricNavierStokesEquations::Density_Ratio_pt, oomph::LinearisedAxisymmetricNavierStokesEquations::density_ratio_pt(), oomph::RefineableElement::father_element_pt(), oomph::LinearisedAxisymmetricNavierStokesEquations::Re_pt, oomph::LinearisedAxisymmetricNavierStokesEquations::re_pt(), oomph::LinearisedAxisymmetricNavierStokesEquations::re_st_pt(), oomph::LinearisedAxisymmetricNavierStokesEquations::ReSt_pt, oomph::LinearisedAxisymmetricNavierStokesEquations::Viscosity_Ratio_pt, and oomph::LinearisedAxisymmetricNavierStokesEquations::viscosity_ratio_pt().
Referenced by oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::further_build().
further_build() [2/2]
void oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build () inline virtual
Further build: pass the pointers down to the sons.
Reimplemented from oomph::RefineableElement.
Reimplemented in oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement.
     {
       // Find the father element
       RefineableLinearisedAxisymmetricNavierStokesEquations*
         cast_father_element_pt =
           dynamic_cast<RefineableLinearisedAxisymmetricNavierStokesEquations*>(
             this->father_element_pt());
       // Set the viscosity ratio pointer
       this->Viscosity_Ratio_pt = cast_father_element_pt->viscosity_ratio_pt();
       // Set the density ratio pointer
       this->Density_Ratio_pt = cast_father_element_pt->density_ratio_pt();
       // Set pointer to global Reynolds number
       this->Re_pt = cast_father_element_pt->re_pt();
       // Set pointer to global Reynolds number x Strouhal number (=Womersley)
       this->ReSt_pt = cast_father_element_pt->re_st_pt();
       // Set pointer to azimuthal mode number
       this->Azimuthal_Mode_Number_pt =
         cast_father_element_pt->azimuthal_mode_number_pt();
       // Set the ALE_is_disabled flag
       this->ALE_is_disabled = cast_father_element_pt->ALE_is_disabled;
     }
References oomph::LinearisedAxisymmetricNavierStokesEquations::ALE_is_disabled, oomph::LinearisedAxisymmetricNavierStokesEquations::Azimuthal_Mode_Number_pt, oomph::LinearisedAxisymmetricNavierStokesEquations::Density_Ratio_pt, oomph::RefineableElement::father_element_pt(), oomph::LinearisedAxisymmetricNavierStokesEquations::Re_pt, oomph::LinearisedAxisymmetricNavierStokesEquations::ReSt_pt, and oomph::LinearisedAxisymmetricNavierStokesEquations::Viscosity_Ratio_pt.
geometric_jacobian() [1/2]
double oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::geometric_jacobian (const Vector< double > & x) inline virtual
Fill in the geometric Jacobian, which in this case is r.
Reimplemented from oomph::ElementWithZ2ErrorEstimator.
 { return x[0]; }
References plotDoE::x.
geometric_jacobian() [2/2]
double oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::geometric_jacobian (const Vector< double > & x) inline virtual
Fill in the geometric Jacobian, which in this case is r.
Reimplemented from oomph::ElementWithZ2ErrorEstimator.
     {
       return x[0];
     }
References plotDoE::x.
get_Z2_flux() [1/2]
void oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) inline virtual
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
   {
    // Specify the number of velocity dimensions
    unsigned DIM=3;
 #ifdef PARANOID
    unsigned num_entries=DIM+((DIM*DIM)-DIM)/2;
    if (flux.size()!=num_entries)
     {
      std::ostringstream error_message;
      error_message << "The flux vector has the wrong number of entries, "
                    << flux.size() << ", whereas it should be "
                    << num_entries << std::endl;
      throw OomphLibError(
       error_message.str(),
       OOMPH_CURRENT_FUNCTION,
       OOMPH_EXCEPTION_LOCATION);
     }
 #endif
    // Get strain rate matrix
    DenseMatrix<double> strainrate(DIM);
    this->strain_rate(s,strainrate);
    // Pack into flux Vector
    unsigned icount=0;
    // Start with diagonal terms
    for(unsigned i=0;i<DIM;i++)
     {
      flux[icount]=strainrate(i,i);
      icount++;
     }
    // Off diagonals row by row
    for(unsigned i=0;i<DIM;i++)
     {
      for(unsigned j=i+1;j<DIM;j++)
       {
        flux[icount]=strainrate(i,j);
        icount++;
       }
     }
   }
References DIM, ProblemParameters::flux(), i, j, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::LinearisedAxisymmetricNavierStokesEquations::strain_rate().
get_Z2_flux() [2/2]
void oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) inline virtual
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       // Specify the number of velocity dimensions
       unsigned DIM = 3;
 #ifdef PARANOID
       unsigned num_entries = DIM + ((DIM * DIM) - DIM) / 2;
       if (flux.size() != num_entries)
       {
         std::ostringstream error_message;
         error_message << "The flux vector has the wrong number of entries, "
                       << flux.size() << ", whereas it should be " << num_entries
                       << std::endl;
         throw OomphLibError(error_message.str(),
                             "RefineableLinearisedAxisymmetricNavierStokesEquati"
                             "ons::get_Z2_flux()",
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Get strain rate matrix
       DenseMatrix<double> strainrate(DIM);
       this->strain_rate(s, strainrate);
       // Pack into flux Vector
       unsigned icount = 0;
       // Start with diagonal terms
       for (unsigned i = 0; i < DIM; i++)
       {
         flux[icount] = strainrate(i, i);
         icount++;
       }
       // Off diagonals row by row
       for (unsigned i = 0; i < DIM; i++)
       {
         for (unsigned j = i + 1; j < DIM; j++)
         {
           flux[icount] = strainrate(i, j);
           icount++;
         }
       }
     }
References DIM, ProblemParameters::flux(), i, j, OOMPH_EXCEPTION_LOCATION, and oomph::LinearisedAxisymmetricNavierStokesEquations::strain_rate().
num_Z2_flux_terms() [1/2]
unsigned oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::num_Z2_flux_terms () inline virtual
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
   {
    // 3 diagonal strain rates, 3 off diagonal
    return 6;
   }
num_Z2_flux_terms() [2/2]
unsigned oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::num_Z2_flux_terms () inline virtual
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       // 3 diagonal strain rates, 3 off diagonal
       return 6;
     }
pin_elemental_redundant_nodal_pressure_dofs() [1/2]
virtual void oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::pin_elemental_redundant_nodal_pressure_dofs () inline protected virtual
Pin unused nodal pressure dofs (empty by default, because by default pressure dofs are not associated with nodes)
Reimplemented in oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement, and oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement.
 {}
Referenced by pin_redundant_nodal_pressures().
pin_elemental_redundant_nodal_pressure_dofs() [2/2]
virtual void oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::pin_elemental_redundant_nodal_pressure_dofs () inline protected virtual
Pin unused nodal pressure dofs (empty by default, because by default pressure dofs are not associated with nodes)
Reimplemented in oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement, and oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement.
 {}
pin_redundant_nodal_pressures() [1/2]
static void oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > & element_pt) inline static
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function
RefineableLinearisedAxisymmetricNavierStokesEquations:: pin_all_nodal_pressure_dofs()
which is empty by default and should be implemented for elements with nodal pressure degrees of freedom
(e.g. for refineable Taylor-Hood.)
   {
    // Loop over all elements to brutally pin all nodal pressure degrees of
    // freedom
    const unsigned n_element=element_pt.size();
    for(unsigned e=0;e<n_element;e++)
     {
      dynamic_cast<RefineableLinearisedAxisymmetricNavierStokesEquations*>
       (element_pt[e])->pin_elemental_redundant_nodal_pressure_dofs();
     }
   }
References e(), and pin_elemental_redundant_nodal_pressure_dofs().
pin_redundant_nodal_pressures() [2/2]
static void oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > & element_pt) inline static
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function
RefineableLinearisedAxisymmetricNavierStokesEquations:: pin_all_nodal_pressure_dofs()
which is empty by default and should be implemented for elements with nodal pressure degrees of freedom (e.g. for refineable Taylor-Hood.)
     {
       // Loop over all elements to brutally pin all nodal pressure degrees of
       // freedom
       const unsigned n_element = element_pt.size();
       for (unsigned e = 0; e < n_element; e++)
       {
         dynamic_cast<RefineableLinearisedAxisymmetricNavierStokesEquations*>(
           element_pt[e])
           ->pin_elemental_redundant_nodal_pressure_dofs();
       }
     }
References e(), and pin_elemental_redundant_nodal_pressure_dofs().
pressure_node_pt() [1/2]
virtual Node* oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::pressure_node_pt (const unsigned & n_p) inline protected virtual
Pointer to n_p-th pressure node (Default: NULL, indicating that pressure is not based on nodal interpolation).
Reimplemented in oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement, and oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement.
 {return NULL;}
Referenced by fill_in_generic_residual_contribution_linearised_axi_nst().
pressure_node_pt() [2/2]
virtual Node* oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::pressure_node_pt (const unsigned & n_p) inline protected virtual
Pointer to n_p-th pressure node (Default: NULL, indicating that pressure is not based on nodal interpolation).
Reimplemented in oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement, and oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement.
     {
       return NULL;
     }
unpin_all_pressure_dofs() [1/2]
static void oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::unpin_all_pressure_dofs (const Vector< GeneralisedElement * > & element_pt) inline static
Unpin all pressure dofs in elements listed in Vector.
   {
    // Loop over all elements to brutally unpin all nodal pressure degrees of
    // freedom and internal pressure degrees of freedom
    const unsigned n_element = element_pt.size();
    for(unsigned e=0;e<n_element;e++)
     {
      dynamic_cast<RefineableLinearisedAxisymmetricNavierStokesEquations*>
       (element_pt[e])->unpin_elemental_pressure_dofs();
     }
   }
References e(), and unpin_elemental_pressure_dofs().
unpin_all_pressure_dofs() [2/2]
static void oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::unpin_all_pressure_dofs (const Vector< GeneralisedElement * > & element_pt) inline static
Unpin all pressure dofs in elements listed in Vector.
     {
       // Loop over all elements to brutally unpin all nodal pressure degrees of
       // freedom and internal pressure degrees of freedom
       const unsigned n_element = element_pt.size();
       for (unsigned e = 0; e < n_element; e++)
       {
         dynamic_cast<RefineableLinearisedAxisymmetricNavierStokesEquations*>(
           element_pt[e])
           ->unpin_elemental_pressure_dofs();
       }
     }
References e(), and unpin_elemental_pressure_dofs().
unpin_elemental_pressure_dofs() [1/2]
virtual void oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::unpin_elemental_pressure_dofs () protected pure virtual
Unpin all pressure dofs in the element.
Implemented in oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement, oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement, oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement, and oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement.
Referenced by unpin_all_pressure_dofs().
unpin_elemental_pressure_dofs() [2/2]
virtual void oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::unpin_elemental_pressure_dofs () protected pure virtual
Unpin all pressure dofs in the element.
Implemented in oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement, oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement, oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement, and oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement.
The documentation for this class was generated from the following files:
demo_drivers/axisym_navier_stokes/counter_rotating_disks/refineable_linearised_axisym_navier_stokes_elements.h
demo_drivers/axisym_navier_stokes/counter_rotating_disks/refineable_linearised_axisym_navier_stokes_elements.cc