MercuryDPM: TemplateKeyword_simple.cpp File Reference
TemplateKeyword_simple.cpp File Reference
#include <Eigen/Dense>
#include <iostream>
Functions
void copyUpperTriangularPart (MatrixXf &dst, const MatrixXf &src)
int main ()
Function Documentation
copyUpperTriangularPart()
void copyUpperTriangularPart (MatrixXf & dst, const MatrixXf & src)
{
   dst.triangularView<Eigen::Upper>() = src.triangularView<Eigen::Upper>();
 }
References Eigen::Upper.
Referenced by main().
main()
int main ()
            {
   MatrixXf m1 = MatrixXf::Ones(4, 4);
   MatrixXf m2 = MatrixXf::Random(4, 4);
   std::cout << "m2 before copy:" << std::endl;
   std::cout << m2 << std::endl << std::endl;
   copyUpperTriangularPart(m2, m1);
   std::cout << "m2 after copy:" << std::endl;
   std::cout << m2 << std::endl << std::endl;
 }
References copyUpperTriangularPart(), m1, and m2().