MercuryDPM: Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice > Struct Template Reference
Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice > Struct Template Reference
#include <TensorConvolutionSycl.h>
Public Types
enum {
IsAligned , PacketAccess = false , BlockAccess = false , PreferBlockAccess = false ,
CoordAccess = false , RawAccess = false
}
typedef TensorConvolutionOp< Indices, InputArgType, KernelArgType > XprType
typedef XprType::Index Index
typedef DSizes< Index, NumDims > Dimensions
typedef TensorEvaluator< KernelArgType, Eigen::SyclDevice >::Dimensions KernelDimensions
typedef const Eigen::SyclDevice Device
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Eigen::SyclDevice >::type PacketReturnType
typedef InputArgType::Scalar Scalar
typedef StorageMemory< CoeffReturnType, Eigen::SyclDevice > Storage
typedef Storage::Type EvaluatorPointerType
typedef StorageMemory< const CoeffReturnType, Eigen::SyclDevice > KernelStorage
typedef internal::TensorBlockNotImplemented TensorBlock
Public Member Functions
TensorEvaluator (const XprType &op, const Eigen::SyclDevice &device)
EIGEN_DEVICE_FUNC const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType data)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Device & device () const
used by sycl in order to build the sycl buffer
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EvaluatorPointerType data () const
used by sycl in order to build the sycl buffer
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void preloadKernel ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void executeEval (EvaluatorPointerType data) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (const Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
Static Public Attributes
static constexpr int NumDims
static constexpr int NumKernelDims = internal::array_size<Indices>::value
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int Layout = TensorEvaluator<InputArgType, Eigen::SyclDevice>::Layout
Private Member Functions
TensorEvaluator & operator= (const TensorEvaluator &)
Private Attributes
TensorEvaluator< InputArgType, Eigen::SyclDevice > m_inputImpl
KernelArgType m_kernelArg
TensorEvaluator< KernelArgType, Eigen::SyclDevice > m_kernelImpl
Indices m_indices
Dimensions m_dimensions
EvaluatorPointerType m_buf
KernelStorage::Type m_kernel
bool m_local_kernel
const Eigen::SyclDevice EIGEN_DEVICE_REF m_device
Member Typedef Documentation
CoeffReturnType
template<typename Indices , typename InputArgType , typename KernelArgType > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::CoeffReturnType
Device
template<typename Indices , typename InputArgType , typename KernelArgType > typedef const Eigen::SyclDevice Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::Device
Dimensions
template<typename Indices , typename InputArgType , typename KernelArgType > typedef DSizes<Index, NumDims> Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::Dimensions
EvaluatorPointerType
template<typename Indices , typename InputArgType , typename KernelArgType > typedef Storage::Type Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::EvaluatorPointerType
Index
template<typename Indices , typename InputArgType , typename KernelArgType > typedef XprType::Index Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::Index
KernelDimensions
template<typename Indices , typename InputArgType , typename KernelArgType > typedef TensorEvaluator<KernelArgType, Eigen::SyclDevice>::Dimensions Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::KernelDimensions
KernelStorage
template<typename Indices , typename InputArgType , typename KernelArgType > typedef StorageMemory<const CoeffReturnType, Eigen::SyclDevice> Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::KernelStorage
PacketReturnType
template<typename Indices , typename InputArgType , typename KernelArgType > typedef PacketType<CoeffReturnType, Eigen::SyclDevice>::type Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::PacketReturnType
Scalar
template<typename Indices , typename InputArgType , typename KernelArgType > typedef InputArgType::Scalar Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::Scalar
Storage
template<typename Indices , typename InputArgType , typename KernelArgType > typedef StorageMemory<CoeffReturnType, Eigen::SyclDevice> Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::Storage
TensorBlock
template<typename Indices , typename InputArgType , typename KernelArgType > typedef internal::TensorBlockNotImplemented Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::TensorBlock
XprType
template<typename Indices , typename InputArgType , typename KernelArgType > typedef TensorConvolutionOp<Indices, InputArgType, KernelArgType> Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::XprType
Member Enumeration Documentation
anonymous enum
template<typename Indices , typename InputArgType , typename KernelArgType > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = TensorEvaluator<InputArgType, Eigen::SyclDevice>::IsAligned &
                 TensorEvaluator<KernelArgType, Eigen::SyclDevice>::IsAligned,
     PacketAccess = false,
     BlockAccess = false,
     PreferBlockAccess = false,
     CoordAccess = false,  // to be implemented
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename Indices , typename InputArgType , typename KernelArgType > Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::TensorEvaluator (const XprType & op, const Eigen::SyclDevice & device) inline
       : m_inputImpl(op.inputExpression(), device),
         m_kernelArg(op.kernelExpression()),
         m_kernelImpl(op.kernelExpression(), device),
         m_indices(op.indices()),
         m_buf(NULL),
         m_kernel(NULL),
         m_local_kernel(false),
         m_device(device) {
     EIGEN_STATIC_ASSERT((static_cast<int>(TensorEvaluator<InputArgType, Eigen::SyclDevice>::Layout) ==
                          static_cast<int>(TensorEvaluator<KernelArgType, Eigen::SyclDevice>::Layout)),
                         YOU_MADE_A_PROGRAMMING_MISTAKE);
     const typename TensorEvaluator<InputArgType, Eigen::SyclDevice>::Dimensions &input_dims = m_inputImpl.dimensions();
     const typename TensorEvaluator<KernelArgType, Eigen::SyclDevice>::Dimensions &kernel_dims =
         m_kernelImpl.dimensions();
     m_dimensions = m_inputImpl.dimensions();
     for (int i = 0; i < NumKernelDims; ++i) {
       const Index index = op.indices()[i];
       const Index input_dim = input_dims[index];
       const Index kernel_dim = kernel_dims[i];
       const Index result_dim = input_dim - kernel_dim + 1;
       m_dimensions[index] = result_dim;
     }
   }
References Eigen::TensorEvaluator< Derived, Device >::dimensions(), EIGEN_STATIC_ASSERT, i, and op.
Member Function Documentation
cleanup()
template<typename Indices , typename InputArgType , typename KernelArgType > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::cleanup () inline
{
     m_inputImpl.cleanup();
     if (m_buf) {
       m_device.deallocate_temp(m_buf);
       m_buf = NULL;
     }
     if (m_local_kernel) {
       m_device.deallocate_temp(m_kernel);
       m_local_kernel = false;
     }
     m_kernel = NULL;
   }
References Eigen::TensorEvaluator< Derived, Device >::m_device.
Referenced by framework.Frame::__init__().
coeff()
template<typename Indices , typename InputArgType , typename KernelArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::coeff (Index index) const inline
{
     eigen_assert(m_buf != NULL);
     eigen_assert(index < m_dimensions.TotalSize());
     return m_buf[index];
   }
References eigen_assert.
costPerCoeff()
template<typename Indices , typename InputArgType , typename KernelArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::costPerCoeff (bool vectorized) const inline
{
     // TODO(rmlarsen): FIXME: For now, this is just a copy of the CPU cost
     // model.
     const double kernel_size = m_kernelImpl.dimensions().TotalSize();
     // We ignore the use of fused multiply-add.
     const double convolve_compute_cost = TensorOpCost::AddCost<Scalar>() + TensorOpCost::MulCost<Scalar>();
     const double firstIndex_compute_cost =
         NumDims *
         (2 * TensorOpCost::AddCost<Index>() + 2 * TensorOpCost::MulCost<Index>() + TensorOpCost::DivCost<Index>());
     return TensorOpCost(0, 0, firstIndex_compute_cost, vectorized, PacketSize) +
            kernel_size * (m_inputImpl.costPerCoeff(vectorized) + m_kernelImpl.costPerCoeff(vectorized) +
                           TensorOpCost(0, 0, convolve_compute_cost, vectorized, PacketSize));
   }
References Eigen::TensorEvaluator< Derived, Device >::PacketSize.
data()
template<typename Indices , typename InputArgType , typename KernelArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EvaluatorPointerType Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::data () const inline
used by sycl in order to build the sycl buffer
 { return m_buf; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
device()
template<typename Indices , typename InputArgType , typename KernelArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Device& Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::device () const inline
used by sycl in order to build the sycl buffer
 { return m_device; }
References Eigen::TensorEvaluator< Derived, Device >::m_device.
dimensions()
template<typename Indices , typename InputArgType , typename KernelArgType > EIGEN_DEVICE_FUNC const Dimensions& Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::dimensions () const inline
 { return m_dimensions; }
evalSubExprsIfNeeded()
template<typename Indices , typename InputArgType , typename KernelArgType > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::evalSubExprsIfNeeded (EvaluatorPointerType data) inline
{
     preloadKernel();
     m_inputImpl.evalSubExprsIfNeeded(NULL);
     if (data) {
       executeEval(data);
       return false;
     } else {
       m_buf = (EvaluatorPointerType)m_device.get(
           (Scalar *)m_device.allocate_temp(dimensions().TotalSize() * sizeof(Scalar)));
       executeEval(m_buf);
       return true;
     }
   }
References Eigen::TensorEvaluator< Derived, Device >::data(), Eigen::TensorEvaluator< Derived, Device >::dimensions(), and Eigen::TensorEvaluator< Derived, Device >::m_device.
executeEval()
template<typename Indices , typename InputArgType , typename KernelArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::executeEval (EvaluatorPointerType data) const inline
{
     typedef TensorEvaluator<InputArgType, Eigen::SyclDevice> InputEvaluator;
     typedef typename InputEvaluator::Dimensions InputDims;
     switch (NumKernelDims) {
       case 1: {
         const size_t numX = dimensions()[m_indices[0]];
         const size_t numP = dimensions().TotalSize() / numX;
         const auto input_dim = std::array<size_t, 2>{numX, numP};
         auto global_range = cl::sycl::range<2>{1, 1};
         auto local_range = cl::sycl::range<2>{1, 1};
         const size_t kernel_size = m_kernelImpl.dimensions().TotalSize();
         m_device.parallel_for_setup(input_dim, global_range, local_range);
         const size_t local_memory_size = (local_range[0] + kernel_size - 1) * (local_range[1]);
         gpu_assert(static_cast<unsigned long>(local_memory_size) <= m_device.sharedMemPerBlock());
         const array<Index, 1> indices{{m_indices[0]}};
         const array<Index, 1> kernel_dims{{m_kernelImpl.dimensions()[0]}};
         internal::IndexMapper<Index, InputDims, 1, Layout> indexMapper(m_inputImpl.dimensions(), kernel_dims, indices);
         typedef EigenConvolutionKernel<InputEvaluator, CoeffReturnType, Scalar, Index, InputDims,
                                        typename KernelStorage::Type, EvaluatorPointerType, convolution_type::CONV1D>
             ConvKernel;
         m_device
             .template binary_kernel_launcher<CoeffReturnType, ConvKernel>(
                 m_inputImpl, m_kernel, data, cl::sycl::nd_range<2>(global_range, local_range), local_memory_size,
                 indexMapper, kernel_size, cl::sycl::range<2>(input_dim[0], input_dim[1]))
             .wait();
         break;
       }
       case 2: {
         auto kernel_index = std::array<size_t, 2>{static_cast<int>(Layout) == static_cast<int>(ColMajor) ? 0 : 1,
                                                   static_cast<int>(Layout) == static_cast<int>(ColMajor) ? 1 : 0};
         auto kernel_size = cl::sycl::range<2>{(size_t)m_kernelImpl.dimensions()[kernel_index[0]],
                                               (size_t)m_kernelImpl.dimensions()[kernel_index[1]]};
         const size_t numX = dimensions()[m_indices[kernel_index[0]]];
         const size_t numY = dimensions()[m_indices[kernel_index[1]]];
         const size_t numP = dimensions().TotalSize() / (numX * numY);
         auto input_dim = std::array<size_t, 3>{numX, numY, numP};
         auto global_range = cl::sycl::range<3>{1, 1, 1};
         auto local_range = cl::sycl::range<3>{1, 1, 1};
         m_device.parallel_for_setup(input_dim, global_range, local_range);
         const size_t local_memory_size =
             (local_range[0] + kernel_size[0] - 1) * (local_range[1] + kernel_size[1] - 1) * local_range[2];
         gpu_assert(static_cast<unsigned long>(local_memory_size) <= m_device.sharedMemPerBlock());
         const array<Index, 2> indices{{m_indices[kernel_index[0]], m_indices[kernel_index[1]]}};
         const array<Index, 2> kernel_dims{
             {m_kernelImpl.dimensions()[kernel_index[0]], m_kernelImpl.dimensions()[kernel_index[1]]}};
         internal::IndexMapper<Index, InputDims, 2, Layout> indexMapper(m_inputImpl.dimensions(), kernel_dims, indices);
         typedef EigenConvolutionKernel<InputEvaluator, CoeffReturnType, Scalar, Index, InputDims,
                                        typename KernelStorage::Type, EvaluatorPointerType, convolution_type::CONV2D>
             ConvKernel;
         m_device
             .template binary_kernel_launcher<CoeffReturnType, ConvKernel>(
                 m_inputImpl, m_kernel, data, cl::sycl::nd_range<3>(global_range, local_range), local_memory_size,
                 indexMapper, kernel_size, cl::sycl::range<3>{input_dim[0], input_dim[1], input_dim[2]})
             .wait();
         break;
       }
       case 3: {
         auto kernel_index = std::array<size_t, 3>{static_cast<int>(Layout) == static_cast<int>(ColMajor) ? 0 : 2,
                                                   static_cast<int>(Layout) == static_cast<int>(ColMajor) ? 1 : 1,
                                                   static_cast<int>(Layout) == static_cast<int>(ColMajor) ? 2 : 0};
         auto kernel_size = cl::sycl::range<3>{(size_t)m_kernelImpl.dimensions()[kernel_index[0]],
                                               (size_t)m_kernelImpl.dimensions()[kernel_index[1]],
                                               (size_t)m_kernelImpl.dimensions()[kernel_index[2]]};
         const size_t numX = dimensions()[m_indices[kernel_index[0]]];
         const size_t numY = dimensions()[m_indices[kernel_index[1]]];
         const size_t numZ = dimensions()[m_indices[kernel_index[2]]];
         auto input_dim = std::array<size_t, 3>{numX, numY, numZ};
         const size_t numP = dimensions().TotalSize() / (numX * numY * numZ);
         const array<Index, 3> indices{
             {m_indices[kernel_index[0]], m_indices[kernel_index[1]], m_indices[kernel_index[2]]}};
         const array<Index, 3> kernel_dims{{m_kernelImpl.dimensions()[kernel_index[0]],
                                            m_kernelImpl.dimensions()[kernel_index[1]],
                                            m_kernelImpl.dimensions()[kernel_index[2]]}};
         internal::IndexMapper<Index, InputDims, 3, Layout> indexMapper(m_inputImpl.dimensions(), kernel_dims, indices);
         auto global_range = cl::sycl::range<3>{1, 1, 1};
         auto local_range = cl::sycl::range<3>{1, 1, 1};
         m_device.parallel_for_setup(input_dim, global_range, local_range);
         auto local_memory_range = (local_range + kernel_size - 1);
         const size_t local_memory_size = local_memory_range[0] * local_memory_range[1] * local_memory_range[2];
         gpu_assert(static_cast<unsigned long>(local_memory_size) <= m_device.sharedMemPerBlock());
         typedef EigenConvolutionKernel<InputEvaluator, CoeffReturnType, Scalar, Index, InputDims,
                                        typename KernelStorage::Type, EvaluatorPointerType, convolution_type::CONV3D>
             ConvKernel;
         m_device
             .template binary_kernel_launcher<CoeffReturnType, ConvKernel>(
                 m_inputImpl, m_kernel, data, cl::sycl::nd_range<3>(global_range, local_range), local_memory_size,
                 indexMapper, kernel_size, cl::sycl::range<3>(input_dim[0], input_dim[1], input_dim[2]), numP)
             .wait();
         break;
       }
       default: {
         EIGEN_STATIC_ASSERT((NumKernelDims >= 1 && NumKernelDims <= 3),
                             THIS_METHOD_IS_ONLY_FOR_OBJECTS_OF_A_SPECIFIC_SIZE);
       }
     }
   }
References Eigen::ColMajor, Eigen::CONV1D, Eigen::CONV2D, Eigen::CONV3D, Eigen::TensorEvaluator< Derived, Device >::data(), Eigen::TensorEvaluator< Derived, Device >::dimensions(), EIGEN_STATIC_ASSERT, Eigen::TensorEvaluator< Derived, Device >::Layout, and Eigen::TensorEvaluator< Derived, Device >::m_device.
operator=()
template<typename Indices , typename InputArgType , typename KernelArgType > TensorEvaluator& Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::operator= (const TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice > &) private
packet()
template<typename Indices , typename InputArgType , typename KernelArgType > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::packet (const Index index) const inline
{
     eigen_assert(m_buf != NULL);
     eigen_assert(index < m_dimensions.TotalSize());
     return internal::ploadt<PacketReturnType, LoadMode>(m_buf + index);
   }
References eigen_assert.
preloadKernel()
template<typename Indices , typename InputArgType , typename KernelArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::preloadKernel () inline
{
     // Don't make a local copy of the kernel unless we have to (i.e. it's an
     // expression that needs to be evaluated)
     typename KernelStorage::Type in_place = m_kernelImpl.data();
     if (in_place) {
       m_kernel = in_place;
       m_local_kernel = false;
     } else {
       ptrdiff_t kernel_sz = m_kernelImpl.dimensions().TotalSize() * sizeof(Scalar);
       EvaluatorPointerType local = (EvaluatorPointerType)m_device.get((Scalar *)m_device.allocate_temp(kernel_sz));
       typedef TensorEvalToOp<const KernelArgType> EvalTo;
       EvalTo evalToTmp(m_device.get(local), m_kernelArg);
       const bool PacketAccess = internal::IsVectorizable<Eigen::SyclDevice, KernelArgType>::value;
       internal::TensorExecutor<const EvalTo, Eigen::SyclDevice, PacketAccess>::run(evalToTmp, m_device);
       m_kernel = local;
       m_local_kernel = true;
     }
   }
References fix_broken_doxygen_formulae::in_place, Eigen::TensorEvaluator< Derived, Device >::m_device, Eigen::TensorEvaluator< Derived, Device >::PacketAccess, and Eigen::internal::TensorExecutor< Expression, Device, Vectorizable, Tiling >::run().
Member Data Documentation
Layout
template<typename Indices , typename InputArgType , typename KernelArgType > constexpr int Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::Layout = TensorEvaluator<InputArgType, Eigen::SyclDevice>::Layout static constexpr
m_buf
template<typename Indices , typename InputArgType , typename KernelArgType > EvaluatorPointerType Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::m_buf private
m_device
template<typename Indices , typename InputArgType , typename KernelArgType > const Eigen::SyclDevice EIGEN_DEVICE_REF Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::m_device private
m_dimensions
template<typename Indices , typename InputArgType , typename KernelArgType > Dimensions Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::m_dimensions private
m_indices
template<typename Indices , typename InputArgType , typename KernelArgType > Indices Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::m_indices private
m_inputImpl
template<typename Indices , typename InputArgType , typename KernelArgType > TensorEvaluator<InputArgType, Eigen::SyclDevice> Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::m_inputImpl private
m_kernel
template<typename Indices , typename InputArgType , typename KernelArgType > KernelStorage::Type Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::m_kernel private
m_kernelArg
template<typename Indices , typename InputArgType , typename KernelArgType > KernelArgType Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::m_kernelArg private
m_kernelImpl
template<typename Indices , typename InputArgType , typename KernelArgType > TensorEvaluator<KernelArgType, Eigen::SyclDevice> Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::m_kernelImpl private
m_local_kernel
template<typename Indices , typename InputArgType , typename KernelArgType > bool Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::m_local_kernel private
NumDims
template<typename Indices , typename InputArgType , typename KernelArgType > constexpr int Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::NumDims static constexpr
Initial value:
=
      internal::array_size<typename TensorEvaluator<InputArgType, Eigen::SyclDevice>::Dimensions>::value
NumKernelDims
template<typename Indices , typename InputArgType , typename KernelArgType > constexpr int Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::NumKernelDims = internal::array_size<Indices>::value static constexpr
PacketSize
template<typename Indices , typename InputArgType , typename KernelArgType > constexpr int Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorConvolutionSycl.h