MercuryDPM: RefineableQAxisymAdvectionDiffusionBoussinesqElement Class Reference
RefineableQAxisymAdvectionDiffusionBoussinesqElement Class Reference
#include <multi_domain_axisym_boussinesq_elements.h>
Public Member Functions
RefineableQAxisymAdvectionDiffusionBoussinesqElement ()
Constructor: call the underlying constructors.
void output (ostream &outfile, const unsigned &nplot)
void output (ostream &outfile)
Overload the standard output function with the broken default.
void output (FILE *file_pt)
C-style output function: Broken default.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: Broken default.
void get_wind_axi_adv_diff (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &wind) const
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual vector and the Jacobian matrix.
void identify_all_field_data_for_external_interaction (Vector< std::set< FiniteElement * > > const &external_elements_pt, std::set< std::pair< Data *, unsigned > > &paired_interaction_data)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void get_dwind_axi_adv_diff_dexternal_element_data (const unsigned &ipt, const unsigned &i, Vector< double > &result, Vector< unsigned > &global_eqn_number)
void fill_in_off_diagonal_block_analytic (Vector< double > &residuals, DenseMatrix< double > &jacobian)
RefineableQAxisymAdvectionDiffusionBoussinesqElement ()
Constructor: call the underlying constructors.
void output (ostream &outfile, const unsigned &nplot)
void output (ostream &outfile)
Overload the standard output function with the broken default.
void output (FILE *file_pt)
C-style output function: Broken default.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: Broken default.
void get_wind_axi_adv_diff (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &wind) const
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual vector and the Jacobian matrix.
void identify_all_field_data_for_external_interaction (Vector< std::set< FiniteElement * > > const &external_elements_pt, std::set< std::pair< Data *, unsigned > > &paired_interaction_data)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void get_dwind_axi_adv_diff_dexternal_element_data (const unsigned &ipt, const unsigned &i, Vector< double > &result, Vector< unsigned > &global_eqn_number)
void fill_in_off_diagonal_block_analytic (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Public Member Functions inherited from oomph::RefineableQAxisymAdvectionDiffusionElement< 3 >
RefineableQAxisymAdvectionDiffusionElement ()
Empty Constructor:
RefineableQAxisymAdvectionDiffusionElement (const RefineableQAxisymAdvectionDiffusionElement< NNODE_1D > &dummy)=delete
Broken copy constructor.
unsigned ncont_interpolated_values () const
Broken assignment operator.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: empty.
unsigned nrecovery_order ()
void further_setup_hanging_nodes ()
Public Member Functions inherited from oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >
QAxisymAdvectionDiffusionElement ()
QAxisymAdvectionDiffusionElement (const QAxisymAdvectionDiffusionElement< NNODE_1D > &dummy)=delete
Broken copy constructor.
unsigned required_nvalue (const unsigned &n) const
Broken assignment operator.
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &n_plot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &n_plot)
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Public Member Functions inherited from oomph::QElement< 2, NNODE_1D >
QElement ()
Constructor.
QElement (const QElement &)=delete
Broken copy constructor.
void shape (const Vector< double > &s, Shape &psi) const
Broken assignment operator.
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Derivatives of shape functions for specific QElement<2,..>
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double s_min () const
Min. value of local coordinate.
double s_max () const
Max. value of local coordinate.
void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
Get local coordinates of node j in the element; vector sets its own size.
void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
Get the local fraction of node j in the element.
double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
Node * get_node_at_local_coordinate (const Vector< double > &s) const
Get the node at the specified local coordinate.
unsigned nnode_1d () const
Number of nodes along each element edge.
unsigned nplot_points_paraview (const unsigned &nplot) const
unsigned nsub_elements_paraview (const unsigned &nplot) const
void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
void output (std::ostream &outfile)
Output.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at n_plot points.
void output (FILE *file_pt)
C-style output.
void output (FILE *file_pt, const unsigned &n_plot)
C_style output at n_plot points.
void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &use_equally_spaced_interior_sample_points=false) const
std::string tecplot_zone_string (const unsigned &nplot) const
unsigned nplot_points (const unsigned &nplot) const
unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::QuadElementBase
QuadElementBase ()
Constructor. Empty.
Public Member Functions inherited from oomph::QElementBase
QElementBase ()
Constructor: Initialise pointers to macro element reference coords.
QElementBase (const QElementBase &)=delete
Broken copy constructor.
virtual ~QElementBase ()
Broken assignment operator.
bool local_coord_is_valid (const Vector< double > &s)
Check whether the local coordinate are valid or not.
void move_local_coord_back_into_element (Vector< double > &s) const
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
double & s_macro_ll (const unsigned &i)
double & s_macro_ur (const unsigned &i)
double s_macro_ll (const unsigned &i) const
double s_macro_ur (const unsigned &i) const
void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
unsigned nnode_on_face () const
ElementGeometry::ElementGeometry element_geometry () const
It's a Q element!
Public Member Functions inherited from oomph::QElementGeometricBase
QElementGeometricBase ()
Empty default constructor.
QElementGeometricBase (const QElementGeometricBase &)=delete
Broken copy constructor.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::AxisymAdvectionDiffusionEquations
AxisymAdvectionDiffusionEquations ()
AxisymAdvectionDiffusionEquations (const AxisymAdvectionDiffusionEquations &dummy)=delete
Broken copy constructor.
virtual unsigned u_index_axi_adv_diff () const
Broken assignment operator.
double du_dt_axi_adv_diff (const unsigned &n) const
void disable_ALE ()
void enable_ALE ()
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
std::string scalar_name_paraview (const unsigned &i) const
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
AxisymAdvectionDiffusionSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
AxisymAdvectionDiffusionSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
AxisymAdvectionDiffusionWindFctPt & wind_fct_pt ()
Access function: Pointer to wind function.
AxisymAdvectionDiffusionWindFctPt wind_fct_pt () const
Access function: Pointer to wind function. Const version.
const double & pe () const
Peclet number.
double *& pe_pt ()
Pointer to Peclet number.
const double & pe_st () const
Peclet number multiplied by Strouhal number.
double *& pe_st_pt ()
Pointer to Peclet number multipled by Strouha number.
const double & d () const
Peclet number multiplied by Strouhal number.
double *& d_pt ()
Pointer to Peclet number multipled by Strouha number.
virtual void get_source_axi_adv_diff (const unsigned &ipt, const Vector< double > &x, double &source) const
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux: [du/dr,du/dz].
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
double interpolated_u_axi_adv_diff (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
virtual void dinterpolated_u_axi_adv_diff_ddata (const Vector< double > &s, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
unsigned self_test ()
Self-test: Return 0 for OK.
Public Member Functions inherited from oomph::RefineableAxisymAdvectionDiffusionEquations
RefineableAxisymAdvectionDiffusionEquations ()
Empty Constructor.
RefineableAxisymAdvectionDiffusionEquations (const RefineableAxisymAdvectionDiffusionEquations &dummy)=delete
Broken copy constructor.
unsigned num_Z2_flux_terms ()
Broken assignment operator.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
double geometric_jacobian (const Vector< double > &x)
Fill in the geometric Jacobian, which in this case is r.
void further_build ()
Further build: Copy source function pointer from father element.
void dinterpolated_u_adv_diff_ddata (const Vector< double > &s, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void unbuild ()
virtual void deactivate_element ()
virtual bool nodes_built ()
Return true if all the nodes have been built, false if not.
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual Node * interpolating_node_pt (const unsigned &n, const int &value_id)
virtual double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
virtual Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
virtual unsigned ninterpolating_node (const int &value_id)
virtual unsigned ninterpolating_node_1d (const int &value_id)
virtual void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual RefineableElement * root_element_pt ()
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
virtual void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
virtual void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
Pre-build the element.
void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
unsigned nshape_controlling_nodes ()
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Public Member Functions inherited from oomph::ElementWithZ2ErrorEstimator
ElementWithZ2ErrorEstimator ()
Default empty constructor.
ElementWithZ2ErrorEstimator (const ElementWithZ2ErrorEstimator &)=delete
Broken copy constructor.
void operator= (const ElementWithZ2ErrorEstimator &)=delete
Broken assignment operator.
virtual unsigned ncompound_fluxes ()
virtual void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
virtual void get_Z2_compound_flux_indices (Vector< unsigned > &flux_index)
Public Member Functions inherited from oomph::RefineableQElement< 2 >
RefineableQElement ()
Constructor: Pass refinement level (default 0 = root)
RefineableQElement (const RefineableQElement< 2 > &dummy)=delete
Broken copy constructor.
virtual ~RefineableQElement ()
Broken assignment operator.
unsigned required_nsons () const
A refineable quad element has four sons.
virtual Node * node_created_by_neighbour (const Vector< double > &s_fraction, bool &is_periodic)
virtual Node * node_created_by_son_of_neighbour (const Vector< double > &s_fraction, bool &is_periodic)
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)
void check_integrity (double &max_error)
void output_corners (std::ostream &outfile, const std::string &colour) const
Print corner nodes, use colour.
QuadTree * quadtree_pt ()
Pointer to quadtree representation of this element.
QuadTree * quadtree_pt () const
Pointer to quadtree representation of this element.
void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
void get_boundaries (const int &edge, std::set< unsigned > &boundaries) const
void get_bcs (int bound, Vector< int > &bound_cons) const
void interpolated_zeta_on_edge (const unsigned &boundary, const int &edge, const Vector< double > &s, Vector< double > &zeta)
Public Member Functions inherited from oomph::ElementWithExternalElement
ElementWithExternalElement ()
virtual ~ElementWithExternalElement ()
The destructor, clean up any allocated memory.
ElementWithExternalElement (const ElementWithExternalElement &)=delete
Broken copy constructor.
void operator= (const ElementWithExternalElement &)=delete
Broken assignment operator.
bool storage_has_been_allocated () const
Helper function to check if storage has actually been allocated.
FiniteElement *& external_element_pt (const unsigned &interaction_index, const unsigned &ipt)
FiniteElement *const & external_element_pt (const unsigned &interaction_index, const unsigned &ipt) const
Access function to source element, const version.
Vector< double > & external_element_local_coord (const unsigned &interaction_index, const unsigned &ipt)
Vector< double > const & external_element_local_coord (const unsigned &interaction_index, const unsigned &ipt) const
Access function to get source element's coords, const version.
void output_external_elements (std::ostream &outfile, const unsigned &interaction_index)
void initialise_external_element_storage ()
void flush_all_external_element_storage ()
Flush the storage for external elements.
void set_ninteraction (const unsigned &n_interaction)
unsigned ninteraction () const
Return the number of interactions in the element.
virtual void identify_all_field_data_for_external_interaction (Vector< std::set< FiniteElement * >> const &external_elements_pt, std::set< std::pair< Data *, unsigned >> &paired_interaction_data)
virtual void identify_all_geometric_data_for_external_interaction (Vector< std::set< FiniteElement * >> const &external_elements_pt, std::set< Data * > &external_geometric_data_pt)
unsigned nexternal_interaction_field_data () const
Vector< Data * > external_interaction_field_data_pt () const
unsigned nexternal_interaction_geometric_data () const
bool add_external_geometric_data ()
Are we including external geometric data in the element's Jacobian.
bool add_external_interaction_data ()
Are we including external data in the element's Jacobian.
Vector< Data * > external_interaction_geometric_data_pt () const
void ignore_external_geometric_data ()
void ignore_external_interaction_data ()
void include_external_geometric_data ()
void include_external_interaction_data ()
bool external_geometric_data_is_included () const
void describe_local_dofs (std::ostream &out, const std::string &curr_string) const
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Types inherited from oomph::AxisymAdvectionDiffusionEquations
typedef void(* AxisymAdvectionDiffusionSourceFctPt) (const Vector< double > &x, double &f)
typedef void(* AxisymAdvectionDiffusionWindFctPt) (const Vector< double > &x, Vector< double > &wind)
Public Types inherited from oomph::RefineableQElement< 2 >
typedef void(RefineableQElement< 2 >::* VoidMemberFctPt) ()
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions inherited from oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >
double dshape_and_dtest_eulerian_axi_adv_diff (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_axi_adv_diff (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::RefineableAxisymAdvectionDiffusionEquations
void fill_in_generic_residual_contribution_axi_adv_diff (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Protected Member Functions inherited from oomph::RefineableQElement< 2 >
void setup_father_bounds ()
void get_edge_bcs (const int &edge, Vector< int > &bound_cons) const
Determine Vector of boundary conditions along edge (N/S/W/E)
void setup_hang_for_value (const int &value_id)
virtual void quad_hang_helper (const int &value_id, const int &my_edge, std::ofstream &output_hangfile)
Protected Member Functions inherited from oomph::ElementWithExternalElement
void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
void assign_external_interaction_data_local_eqn_numbers (const bool &store_local_dof_pt)
void fill_in_jacobian_from_external_interaction_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_by_fd (DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_field_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_field_by_fd (DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_geometric_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_geometric_by_fd (DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void update_before_external_interaction_field_fd ()
virtual void reset_after_external_interaction_field_fd ()
virtual void update_in_external_interaction_field_fd (const unsigned &i)
virtual void reset_in_external_interaction_field_fd (const unsigned &i)
virtual void update_before_external_interaction_geometric_fd ()
virtual void reset_after_external_interaction_geometric_fd ()
virtual void update_in_external_interaction_geometric_fd (const unsigned &i)
virtual void reset_in_external_interaction_geometric_fd (const unsigned &i)
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::AxisymAdvectionDiffusionEquations
double * Pe_pt
Pointer to global Peclet number.
double * PeSt_pt
Pointer to global Peclet number multiplied by Strouhal number.
double * D_pt
Pointer to global Diffusion parameter.
AxisymAdvectionDiffusionSourceFctPt Source_fct_pt
Pointer to source function:
AxisymAdvectionDiffusionWindFctPt Wind_fct_pt
Pointer to wind function:
bool ALE_is_disabled
Boolean flag to indicate whether AlE formulation is disable.
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number – for plotting/validation purposes.
Protected Attributes inherited from oomph::ElementWithExternalElement
bool Add_external_interaction_data
Boolean flag to indicate whether to include the external data.
bool Add_external_geometric_data
Boolean flag to indicate whether to include the external geometric data.
Data ** External_interaction_field_data_pt
Data ** External_interaction_geometric_data_pt
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Static Protected Attributes inherited from oomph::RefineableQElement< 2 >
static std::map< unsigned, DenseMatrix< int > > Father_bound
Detailed Description
//////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////// Build an AdvectionDiffusionElement that inherits from ElementWithExternalElement so that it can "communicate" with the a NavierStokesElement that provides its wind.
Constructor & Destructor Documentation
RefineableQAxisymAdvectionDiffusionBoussinesqElement() [1/2]
RefineableQAxisymAdvectionDiffusionBoussinesqElement::RefineableQAxisymAdvectionDiffusionBoussinesqElement () inline
Constructor: call the underlying constructors.
                                                         :
   RefineableQAxisymAdvectionDiffusionElement<3>(), ElementWithExternalElement()
   {
    //There is one interaction
    this->set_ninteraction(1);
   }
RefineableQAxisymAdvectionDiffusionBoussinesqElement() [2/2]
RefineableQAxisymAdvectionDiffusionBoussinesqElement::RefineableQAxisymAdvectionDiffusionBoussinesqElement () inline
Constructor: call the underlying constructors.
                                                         :
   RefineableQAxisymAdvectionDiffusionElement<3>(), ElementWithExternalElement()
   {
    //There is one interaction
    this->set_ninteraction(1);
   }
Member Function Documentation
fill_in_contribution_to_jacobian() [1/2]
void RefineableQAxisymAdvectionDiffusionBoussinesqElement::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Compute the element's residual vector and the Jacobian matrix.
Reimplemented from oomph::GeneralisedElement.
   {
    //Get the contribution from the basic Navier--Stokes element
    RefineableQAxisymAdvectionDiffusionElement<3>::
     fill_in_contribution_to_jacobian(residuals,jacobian);
 #ifdef USE_FD_FOR_DERIVATIVES_WRT_EXTERNAL_DATA
    //Get the off-diagonal terms by finite differencing
    this->fill_in_jacobian_from_external_interaction_by_fd(residuals,jacobian);
 #else
    //Get the off-diagonal terms analytically
    this->fill_in_off_diagonal_block_analytic(residuals,jacobian);
 #endif
   }
References oomph::AxisymAdvectionDiffusionEquations::fill_in_contribution_to_jacobian().
fill_in_contribution_to_jacobian() [2/2]
void RefineableQAxisymAdvectionDiffusionBoussinesqElement::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Compute the element's residual vector and the Jacobian matrix.
Reimplemented from oomph::GeneralisedElement.
   {
    //Get the contribution from the basic Navier--Stokes element
    RefineableQAxisymAdvectionDiffusionElement<3>::
     fill_in_contribution_to_jacobian(residuals,jacobian);
 #ifdef USE_FD_FOR_DERIVATIVES_WRT_EXTERNAL_DATA
    //Get the off-diagonal terms by finite differencing
    this->fill_in_jacobian_from_external_interaction_by_fd(residuals,jacobian);
 #else
    //Get the off-diagonal terms analytically
    this->fill_in_off_diagonal_block_analytic(residuals,jacobian);
 #endif
   }
References oomph::AxisymAdvectionDiffusionEquations::fill_in_contribution_to_jacobian().
fill_in_contribution_to_jacobian_and_mass_matrix() [1/2]
void RefineableQAxisymAdvectionDiffusionBoussinesqElement::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) inline virtual
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix
Reimplemented from oomph::GeneralisedElement.
   {
    //Call the standard (Broken) function
    //which will prevent these elements from being used
    //in eigenproblems until replaced.
    FiniteElement::fill_in_contribution_to_jacobian_and_mass_matrix(
      residuals,jacobian,mass_matrix);
   }
References oomph::GeneralisedElement::fill_in_contribution_to_jacobian_and_mass_matrix().
fill_in_contribution_to_jacobian_and_mass_matrix() [2/2]
void RefineableQAxisymAdvectionDiffusionBoussinesqElement::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) inline virtual
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix
Reimplemented from oomph::GeneralisedElement.
   {
    //Call the standard (Broken) function
    //which will prevent these elements from being used
    //in eigenproblems until replaced.
    FiniteElement::fill_in_contribution_to_jacobian_and_mass_matrix(
      residuals,jacobian,mass_matrix);
   }
References oomph::GeneralisedElement::fill_in_contribution_to_jacobian_and_mass_matrix().
fill_in_off_diagonal_block_analytic() [1/2]
void RefineableQAxisymAdvectionDiffusionBoussinesqElement::fill_in_off_diagonal_block_analytic (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline
Compute the contribution of the external degrees of freedom (velocities) on the advection-diffusion equations
   {
    //Local storage for the index in the nodes at which the temperature
    //is stored
    const unsigned u_nodal_axi_adv_diff = this->u_index_axi_adv_diff();
    //Find out how many nodes there are
    const unsigned n_node = this->nnode();
    //Set up memory for the shape and test functions and their derivatives
    Shape psi(n_node), test(n_node);
    DShape dpsidx(n_node,2), dtestdx(n_node,2);
    //Number of integration points
    const unsigned n_intpt = this->integral_pt()->nweight();
    //Integers to store the local equations and unknowns
    int local_eqn=0, local_unknown=0;
    // Local storage for pointers to hang_info objects
    HangInfo *hang_info_pt=0;
    //Get the peclet number
    const double peclet = this->pe();
    //Loop over the integration points
    for(unsigned ipt=0;ipt<n_intpt;ipt++)
     {
      //Get the integral weight
      double w = this->integral_pt()->weight(ipt);
      //Call the derivatives of the shape and test functions
      double J =
       this->dshape_and_dtest_eulerian_at_knot_axi_adv_diff(ipt,psi,dpsidx,
                                                            test,dtestdx);
      //Premultiply the weights and the Jacobian
      double W = w*J;
      //Calculate local values of the derivatives of the solution
      Vector<double> interpolated_dudx(2,0.0);
      //Calculate the radius
      double r = 0.0;
      // Loop over nodes
      for(unsigned l=0;l<n_node;l++)
       {
        //Position
        r += this->nodal_position(l,0)*psi(l);
        // Loop over directions
        for(unsigned j=0;j<2;j++)
         {
          interpolated_dudx[j] +=
           this->nodal_value(l,u_nodal_axi_adv_diff)*dpsidx(l,j);
         }
       }
      //Get the derivatives of the wind wrt the unknowns
      //of the external element
      Vector<double> dwind_dexternal_element_data;
      //Vector of global equation number corresponding to the external
      //element's data
      Vector<unsigned> global_eqn_number_of_external_element_data;
      //Loop over the wind directions
      for(unsigned i2=0;i2<2;i2++)
       {
        //Get the appropriate derivatives
        this->get_dwind_axi_adv_diff_dexternal_element_data(
         ipt,i2,dwind_dexternal_element_data,
         global_eqn_number_of_external_element_data);
        //Find out how many external data there are
        const unsigned n_external_element_data =
         global_eqn_number_of_external_element_data.size();
        //Loop over the test functions
        for(unsigned l=0;l<n_node;l++)
         {
          //Assemble the contributions of the velocities to
          //the advection-diffusion equations
          unsigned n_master = 1;
          double hang_weight = 1.0;
          //Local bool (is the node hanging)
          bool is_node_hanging = this->node_pt(l)->is_hanging();
          //If the node is hanging, get the number of master nodes
          if(is_node_hanging)
           {
            hang_info_pt = this->node_pt(l)->hanging_pt();
            n_master = hang_info_pt->nmaster();
           }
          //Otherwise there is just one master node, the node itself
          else
           {
            n_master = 1;
           }
          //Loop over the master nodes
          for(unsigned m=0;m<n_master;m++)
           {
            //If the node is hanging get weight from master node
            if(is_node_hanging)
             {
              //Get the hang weight from the master node
              hang_weight = hang_info_pt->master_weight(m);
             }
            else
             {
              // Node contributes with full weight
              hang_weight = 1.0;
             }
            //Get the equation number
            if(is_node_hanging)
             {
              //Get the equation number from the master node
              local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                               u_nodal_axi_adv_diff);
             }
            else
             {
              // Local equation number
              local_eqn = this->nodal_local_eqn(l,u_nodal_axi_adv_diff);
             }
            if(local_eqn >= 0)
             {
              //Loop over the external data
              for(unsigned l2=0;l2<n_external_element_data;l2++)
               {
                //Find the local equation number corresponding to the global
                //unknown
                local_unknown =
                 this->local_eqn_number(
                  global_eqn_number_of_external_element_data[l2]);
                if(local_unknown >= 0)
                 {
                  //Add contribution to jacobian matrix
                  jacobian(local_eqn,local_unknown)
                   -= peclet*dwind_dexternal_element_data[l2]*
                   interpolated_dudx[i2]*test(l)*hang_weight*r*W;
                 }
               }
             }
           }
         }
       }
     }
   }
References J, j, m, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::pe(), UniformPSDSelfTest::r, Eigen::test, w, and oomph::QuadTreeNames::W.
fill_in_off_diagonal_block_analytic() [2/2]
void RefineableQAxisymAdvectionDiffusionBoussinesqElement::fill_in_off_diagonal_block_analytic (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline
Compute the contribution of the external degrees of freedom (velocities) on the advection-diffusion equations
   {
    //Local storage for the index in the nodes at which the temperature
    //is stored
    const unsigned u_nodal_axi_adv_diff = this->u_index_axi_adv_diff();
    //Find out how many nodes there are
    const unsigned n_node = this->nnode();
    //Set up memory for the shape and test functions and their derivatives
    Shape psi(n_node), test(n_node);
    DShape dpsidx(n_node,2), dtestdx(n_node,2);
    //Number of integration points
    const unsigned n_intpt = this->integral_pt()->nweight();
    //Integers to store the local equations and unknowns
    int local_eqn=0, local_unknown=0;
    // Local storage for pointers to hang_info objects
    HangInfo *hang_info_pt=0;
    //Get the peclet number
    const double peclet = this->pe();
    //Loop over the integration points
    for(unsigned ipt=0;ipt<n_intpt;ipt++)
     {
      //Get the integral weight
      double w = this->integral_pt()->weight(ipt);
      //Call the derivatives of the shape and test functions
      double J =
       this->dshape_and_dtest_eulerian_at_knot_axi_adv_diff(ipt,psi,dpsidx,
                                                            test,dtestdx);
      //Premultiply the weights and the Jacobian
      double W = w*J;
      //Calculate local values of the derivatives of the solution
      Vector<double> interpolated_dudx(2,0.0);
      //Calculate the radius
      double r = 0.0;
      // Loop over nodes
      for(unsigned l=0;l<n_node;l++)
       {
        //Position
        r += this->nodal_position(l,0)*psi(l);
        // Loop over directions
        for(unsigned j=0;j<2;j++)
         {
          interpolated_dudx[j] +=
           this->nodal_value(l,u_nodal_axi_adv_diff)*dpsidx(l,j);
         }
       }
      //Get the derivatives of the wind wrt the unknowns
      //of the external element
      Vector<double> dwind_dexternal_element_data;
      //Vector of global equation number corresponding to the external
      //element's data
      Vector<unsigned> global_eqn_number_of_external_element_data;
      //Loop over the wind directions
      for(unsigned i2=0;i2<2;i2++)
       {
        //Get the appropriate derivatives
        this->get_dwind_axi_adv_diff_dexternal_element_data(
         ipt,i2,dwind_dexternal_element_data,
         global_eqn_number_of_external_element_data);
        //Find out how many external data there are
        const unsigned n_external_element_data =
         global_eqn_number_of_external_element_data.size();
        //Loop over the test functions
        for(unsigned l=0;l<n_node;l++)
         {
          //Assemble the contributions of the velocities to
          //the advection-diffusion equations
          unsigned n_master = 1;
          double hang_weight = 1.0;
          //Local bool (is the node hanging)
          bool is_node_hanging = this->node_pt(l)->is_hanging();
          //If the node is hanging, get the number of master nodes
          if(is_node_hanging)
           {
            hang_info_pt = this->node_pt(l)->hanging_pt();
            n_master = hang_info_pt->nmaster();
           }
          //Otherwise there is just one master node, the node itself
          else
           {
            n_master = 1;
           }
          //Loop over the master nodes
          for(unsigned m=0;m<n_master;m++)
           {
            //If the node is hanging get weight from master node
            if(is_node_hanging)
             {
              //Get the hang weight from the master node
              hang_weight = hang_info_pt->master_weight(m);
             }
            else
             {
              // Node contributes with full weight
              hang_weight = 1.0;
             }
            //Get the equation number
            if(is_node_hanging)
             {
              //Get the equation number from the master node
              local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                               u_nodal_axi_adv_diff);
             }
            else
             {
              // Local equation number
              local_eqn = this->nodal_local_eqn(l,u_nodal_axi_adv_diff);
             }
            if(local_eqn >= 0)
             {
              //Loop over the external data
              for(unsigned l2=0;l2<n_external_element_data;l2++)
               {
                //Find the local equation number corresponding to the global
                //unknown
                local_unknown =
                 this->local_eqn_number(
                  global_eqn_number_of_external_element_data[l2]);
                if(local_unknown >= 0)
                 {
                  //Add contribution to jacobian matrix
                  jacobian(local_eqn,local_unknown)
                   -= peclet*dwind_dexternal_element_data[l2]*
                   interpolated_dudx[i2]*test(l)*hang_weight*r*W;
                 }
               }
             }
           }
         }
       }
     }
   }
References J, j, m, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::pe(), UniformPSDSelfTest::r, Eigen::test, w, and oomph::QuadTreeNames::W.
get_dwind_axi_adv_diff_dexternal_element_data() [1/2]
void RefineableQAxisymAdvectionDiffusionBoussinesqElement::get_dwind_axi_adv_diff_dexternal_element_data (const unsigned & ipt, const unsigned & i, Vector< double > & result, Vector< unsigned > & global_eqn_number) inline
Fill in the derivatives of the wind with respect to the external unknowns
  {
   // The interaction index is 0 in this case
   unsigned interaction=0;
   // Dynamic cast "other" element to correct type
   RefineableQAxisymCrouzeixRaviartBoussinesqElement* source_el_pt=
    dynamic_cast<RefineableQAxisymCrouzeixRaviartBoussinesqElement*>
    (external_element_pt(interaction,ipt));
   // Get the external element's derivatives of the velocity with respect
   // to the data. The wind is just the Navier--Stokes velocity, so this
   // is all that's required
   source_el_pt->dinterpolated_u_axi_nst_ddata(
    external_element_local_coord(interaction,ipt),i,result,
    global_eqn_number);
  }
References oomph::RefineableAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), and i.
get_dwind_axi_adv_diff_dexternal_element_data() [2/2]
void RefineableQAxisymAdvectionDiffusionBoussinesqElement::get_dwind_axi_adv_diff_dexternal_element_data (const unsigned & ipt, const unsigned & i, Vector< double > & result, Vector< unsigned > & global_eqn_number) inline
Fill in the derivatives of the wind with respect to the external unknowns
  {
   // The interaction index is 0 in this case
   unsigned interaction=0;
   // Dynamic cast "other" element to correct type
   RefineableQAxisymCrouzeixRaviartBoussinesqElement* source_el_pt=
    dynamic_cast<RefineableQAxisymCrouzeixRaviartBoussinesqElement*>
    (external_element_pt(interaction,ipt));
   // Get the external element's derivatives of the velocity with respect
   // to the data. The wind is just the Navier--Stokes velocity, so this
   // is all that's required
   source_el_pt->dinterpolated_u_axi_nst_ddata(
    external_element_local_coord(interaction,ipt),i,result,
    global_eqn_number);
  }
References oomph::RefineableAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), and i.
get_wind_axi_adv_diff() [1/2]
void RefineableQAxisymAdvectionDiffusionBoussinesqElement::get_wind_axi_adv_diff (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & wind) const inline virtual
Overload the wind function in the advection-diffusion equations. This provides the coupling from the Navier–Stokes equations to the advection-diffusion equations because the wind is the fluid velocity, obtained from the "external" element
Reimplemented from oomph::AxisymAdvectionDiffusionEquations.
  {
   // There is only one interaction
   unsigned interaction=0;
   // Dynamic cast "external" element to Navier Stokes element
   AxisymmetricNavierStokesEquations* nst_el_pt=
    dynamic_cast<AxisymmetricNavierStokesEquations*>
    (external_element_pt(interaction,ipt));
   //Wind is given by the velocity in the Navier Stokes element
   nst_el_pt->interpolated_u_axi_nst
    (external_element_local_coord(interaction,ipt),wind);
  }  //end of get_wind_adv_diff
References oomph::AxisymmetricNavierStokesEquations::interpolated_u_axi_nst().
get_wind_axi_adv_diff() [2/2]
void RefineableQAxisymAdvectionDiffusionBoussinesqElement::get_wind_axi_adv_diff (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & wind) const inline virtual
Overload the wind function in the advection-diffusion equations. This provides the coupling from the Navier–Stokes equations to the advection-diffusion equations because the wind is the fluid velocity, obtained from the "external" element
Reimplemented from oomph::AxisymAdvectionDiffusionEquations.
  {
   // There is only one interaction
   unsigned interaction=0;
   // Dynamic cast "external" element to Navier Stokes element
   AxisymmetricNavierStokesEquations* nst_el_pt=
    dynamic_cast<AxisymmetricNavierStokesEquations*>
    (external_element_pt(interaction,ipt));
   //Wind is given by the velocity in the Navier Stokes element
   nst_el_pt->interpolated_u_axi_nst
    (external_element_local_coord(interaction,ipt),wind);
  }  //end of get_wind_adv_diff
References oomph::AxisymmetricNavierStokesEquations::interpolated_u_axi_nst().
identify_all_field_data_for_external_interaction() [1/2]
void RefineableQAxisymAdvectionDiffusionBoussinesqElement::identify_all_field_data_for_external_interaction (Vector< std::set< FiniteElement * > > const & external_elements_pt, std::set< std::pair< Data *, unsigned > > & paired_interaction_data)
Overload the function that must return all field data involved in the interaction with the external (Navier Stokes) element. Only the velocity dofs in the Navier Stokes element affect the interaction with the current element.
//////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// Overload the function that must return all field data involved in the interaction with the external (Navier Stokes) element. Only the velocity dofs in the Navier Stokes element affect the interaction with the current element.
 {
  //There's only one interaction
  const unsigned interaction = 0;
  // Loop over each Navier Stokes element in the set of external elements that
  // affect the current element
  for(std::set<FiniteElement*>::iterator it=
       external_elements_pt[interaction].begin();
      it != external_elements_pt[interaction].end(); it++)
   {
    //Cast the external element to a fluid element
    AxisymmetricNavierStokesEquations* external_fluid_el_pt =
     dynamic_cast<AxisymmetricNavierStokesEquations*>(*it);
    // Loop over the nodes
    unsigned nnod=external_fluid_el_pt->nnode();
    for (unsigned j=0;j<nnod;j++)
     {
      // Pointer to node (in its incarnation as Data)
      Data* veloc_data_pt=external_fluid_el_pt->node_pt(j);
      // Get all velocity dofs
      for (unsigned i=0;i<3;i++)
       {
        // Which value corresponds to the i-th velocity?
        unsigned val=external_fluid_el_pt->u_index_axi_nst(i);
        // Turn pointer to Data and index of value into pair
        // and add to the set
        paired_interaction_data.insert(std::make_pair(veloc_data_pt,val));
       }
     }
   }
 } // done
References i, j, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::AxisymmetricNavierStokesEquations::u_index_axi_nst(), and calibrate::val.
identify_all_field_data_for_external_interaction() [2/2]
void RefineableQAxisymAdvectionDiffusionBoussinesqElement::identify_all_field_data_for_external_interaction (Vector< std::set< FiniteElement * > > const & external_elements_pt, std::set< std::pair< Data *, unsigned > > & paired_interaction_data)
Overload the function that must return all field data involved in the interaction with the external (Navier Stokes) element. Only the velocity dofs in the Navier Stokes element affect the interaction with the current element.
output() [1/8]
void RefineableQAxisymAdvectionDiffusionBoussinesqElement::output (FILE * file_pt) inline virtual
C-style output function: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output(file_pt);}
References oomph::FiniteElement::output().
output() [2/8]
void RefineableQAxisymAdvectionDiffusionBoussinesqElement::output (FILE * file_pt) inline virtual
C-style output function: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output(file_pt);}
References oomph::FiniteElement::output().
output() [3/8]
void RefineableQAxisymAdvectionDiffusionBoussinesqElement::output (FILE * file_pt, const unsigned & n_plot) inline virtual
C-style output function: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output(file_pt,n_plot);}
References oomph::FiniteElement::output().
output() [4/8]
void RefineableQAxisymAdvectionDiffusionBoussinesqElement::output (FILE * file_pt, const unsigned & n_plot) inline virtual
C-style output function: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output(file_pt,n_plot);}
References oomph::FiniteElement::output().
output() [5/8]
void RefineableQAxisymAdvectionDiffusionBoussinesqElement::output (ostream & outfile) inline virtual
Overload the standard output function with the broken default.
Reimplemented from oomph::FiniteElement.
 {FiniteElement::output(outfile);}
References oomph::FiniteElement::output().
output() [6/8]
void RefineableQAxisymAdvectionDiffusionBoussinesqElement::output (ostream & outfile) inline virtual
Overload the standard output function with the broken default.
Reimplemented from oomph::FiniteElement.
 {FiniteElement::output(outfile);}
References oomph::FiniteElement::output().
output() [7/8]
void RefineableQAxisymAdvectionDiffusionBoussinesqElement::output (ostream & outfile, const unsigned & nplot) inline virtual
Output function: Output x, y, theta at Nplot^DIM plot points
Reimplemented from oomph::FiniteElement.
   {
    //vector of local coordinates
    Vector<double> s(2);
    // Tecplot header info
    outfile << this->tecplot_zone_string(nplot);
    // Loop over plot points
    unsigned num_plot_points=this->nplot_points(nplot);
    for (unsigned iplot=0;iplot<num_plot_points;iplot++)
     {
      // Get local coordinates of plot point
      this->get_s_plot(iplot,nplot,s);
      // Output the position of the plot point
      for(unsigned i=0;i<2;i++)
       {outfile << this->interpolated_x(s,i) << " ";}
      // Output the temperature (the advected variable) at the plot point
      outfile << this->interpolated_u_axi_adv_diff(s) << std::endl;
     }
    outfile << std::endl;
    // Write tecplot footer (e.g. FE connectivity lists)
    this->write_tecplot_zone_footer(outfile,nplot);
   } //End of output function
References i, and s.
output() [8/8]
void RefineableQAxisymAdvectionDiffusionBoussinesqElement::output (ostream & outfile, const unsigned & nplot) inline virtual
Output function: Output x, y, theta at Nplot^DIM plot points
Reimplemented from oomph::FiniteElement.
   {
    //vector of local coordinates
    Vector<double> s(2);
    // Tecplot header info
    outfile << this->tecplot_zone_string(nplot);
    // Loop over plot points
    unsigned num_plot_points=this->nplot_points(nplot);
    for (unsigned iplot=0;iplot<num_plot_points;iplot++)
     {
      // Get local coordinates of plot point
      this->get_s_plot(iplot,nplot,s);
      // Output the position of the plot point
      for(unsigned i=0;i<2;i++)
       {outfile << this->interpolated_x(s,i) << " ";}
      // Output the temperature (the advected variable) at the plot point
      outfile << this->interpolated_u_axi_adv_diff(s) << std::endl;
     }
    outfile << std::endl;
    // Write tecplot footer (e.g. FE connectivity lists)
    this->write_tecplot_zone_footer(outfile,nplot);
   } //End of output function
References i, and s.
The documentation for this class was generated from the following file:
axisym_heat_sphere/multi_domain_axisym_boussinesq_elements.h