MercuryDPM: Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixMatrix > Struct Template Reference
Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixMatrix > Struct Template Reference
#include <Product.h>
Public Types
using Derived = Product< Lhs, Rhs, Option >
using LhsScalar = typename traits< Lhs >::Scalar
using LhsTransposeType = typename DenseBase< Lhs >::ConstTransposeReturnType
using LhsConjugateTransposeType = CwiseUnaryOp< scalar_conjugate_op< LhsScalar >, LhsTransposeType >
using LhsAdjointType = std::conditional_t< NumTraits< LhsScalar >::IsComplex, LhsConjugateTransposeType, LhsTransposeType >
using RhsScalar = typename traits< Rhs >::Scalar
using RhsTransposeType = typename DenseBase< Rhs >::ConstTransposeReturnType
using RhsConjugateTransposeType = CwiseUnaryOp< scalar_conjugate_op< RhsScalar >, RhsTransposeType >
using RhsAdjointType = std::conditional_t< NumTraits< RhsScalar >::IsComplex, RhsConjugateTransposeType, RhsTransposeType >
using TransposeType = Product< RhsTransposeType, LhsTransposeType, Option >
using AdjointType = Product< RhsAdjointType, LhsAdjointType, Option >
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TransposeType run_transpose (const Derived &derived)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE AdjointType run_adjoint (const Derived &derived)
Member Typedef Documentation
AdjointType
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixMatrix >::AdjointType = Product<RhsAdjointType, LhsAdjointType, Option>
Derived
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixMatrix >::Derived = Product<Lhs, Rhs, Option>
LhsAdjointType
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixMatrix >::LhsAdjointType = std::conditional_t<NumTraits<LhsScalar>::IsComplex, LhsConjugateTransposeType, LhsTransposeType>
LhsConjugateTransposeType
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixMatrix >::LhsConjugateTransposeType = CwiseUnaryOp<scalar_conjugate_op<LhsScalar>, LhsTransposeType>
LhsScalar
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixMatrix >::LhsScalar = typename traits<Lhs>::Scalar
LhsTransposeType
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixMatrix >::LhsTransposeType = typename DenseBase<Lhs>::ConstTransposeReturnType
RhsAdjointType
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixMatrix >::RhsAdjointType = std::conditional_t<NumTraits<RhsScalar>::IsComplex, RhsConjugateTransposeType, RhsTransposeType>
RhsConjugateTransposeType
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixMatrix >::RhsConjugateTransposeType = CwiseUnaryOp<scalar_conjugate_op<RhsScalar>, RhsTransposeType>
RhsScalar
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixMatrix >::RhsScalar = typename traits<Rhs>::Scalar
RhsTransposeType
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixMatrix >::RhsTransposeType = typename DenseBase<Rhs>::ConstTransposeReturnType
TransposeType
template<typename Lhs , typename Rhs , int Option> using Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixMatrix >::TransposeType = Product<RhsTransposeType, LhsTransposeType, Option>
Member Function Documentation
run_adjoint()
template<typename Lhs , typename Rhs , int Option> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE AdjointType Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixMatrix >::run_adjoint (const Derived & derived) inline static
{
     return AdjointType(RhsAdjointType(RhsTransposeType(derived.rhs())),
                        LhsAdjointType(LhsTransposeType(derived.lhs())));
   }
References Eigen::Product< Lhs_, Rhs_, Option >::lhs(), and Eigen::Product< Lhs_, Rhs_, Option >::rhs().
run_transpose()
template<typename Lhs , typename Rhs , int Option> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TransposeType Eigen::internal::product_transpose_helper< Lhs, Rhs, Option, TransposeProductEnum::MatrixMatrix >::run_transpose (const Derived & derived) inline static
{
     return TransposeType(RhsTransposeType(derived.rhs()), LhsTransposeType(derived.lhs()));
   }
References Eigen::Product< Lhs_, Rhs_, Option >::lhs(), and Eigen::Product< Lhs_, Rhs_, Option >::rhs().
The documentation for this struct was generated from the following file:
Product.h