MercuryDPM: mesh_from_inline_triangle_internal_boundaries_extra.cc File Reference
mesh_from_inline_triangle_internal_boundaries_extra.cc File Reference
#include "generic.h"
#include "poisson.h"
#include "meshes/triangle_mesh.h"
Classes
class PoissonProblem< ELEMENT >
Micky mouse Poisson problem.
Namespaces
TanhSolnForPoisson
Namespace for exact solution for Poisson equation with "sharp step".
Functions
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, double &u)
Exact solution as a scalar.
void TanhSolnForPoisson::get_source (const Vector< double > &x, double &source)
Source function to make it an exact solution.
int main (int argc, char *argv[])
Demonstrate how to solve Poisson problem.
Function Documentation
main()
int main (int argc , char * argv[])
Demonstrate how to solve Poisson problem.
 {
   // Store command line arguments
   CommandLineArgs::setup(argc,argv);
   // Label for output
   DocInfo doc_info;
   // Output directory
   doc_info.set_directory("RESLT");
   // Do the problem with cubic elements
   //-----------------------------------
   {
     cout << std::endl << "Cubic elements" << std::endl;
     cout <<         "==============" << std::endl << std::endl;
     //Set up the problem
     PoissonProblem<TPoissonElement<2,4> >
     problem(&TanhSolnForPoisson::get_source);
     // Solve the problem
     problem.newton_solve();
     //Output solution
     problem.doc_solution(doc_info);
     //Increment counter for solutions
     doc_info.number()++;
   }
   // Do the problem with quadratic elements
   //---------------------------------------
   {
     cout << std::endl  << "Quadratic elements" << std::endl;
     cout <<               "===================" << std::endl << std::endl;
     //Set up the problem
     PoissonProblem<TPoissonElement<2,3> >
     problem(&TanhSolnForPoisson::get_source);
     // Solve the problem
     problem.newton_solve();
     //Output solution
     problem.doc_solution(doc_info);
     //Increment counter for solutions
     doc_info.number()++;
   }
   // Do the problem with linear elements
   //------------------------------------
   {
     cout << std::endl << "Linear elements" << std::endl;
     cout <<              "===============" << std::endl << std::endl;
     //Set up the problem
     PoissonProblem<TPoissonElement<2,2> >
     problem(&TanhSolnForPoisson::get_source);
     // Solve the problem
     problem.newton_solve();
     //Output solution
     problem.doc_solution(doc_info);
     //Increment counter for solutions
     doc_info.number()++;
   }
 }
References TanhSolnForPoisson::get_source(), oomph::DocInfo::number(), problem, oomph::DocInfo::set_directory(), and Flag_definition::setup().