MercuryDPM: oomph::OomphLibPreconditionerEpetraOperator Class Reference
oomph::OomphLibPreconditionerEpetraOperator Class Reference
#include <trilinos_solver.h>
Public Member Functions
OomphLibPreconditionerEpetraOperator (Preconditioner *preconditioner_pt, bool use_epetra_values=false)
~OomphLibPreconditionerEpetraOperator ()
OomphLibPreconditionerEpetraOperator (const OomphLibPreconditionerEpetraOperator &)=delete
Broken copy constructor.
void operator= (const OomphLibPreconditionerEpetraOperator &)=delete
Broken assignment operator.
int SetUseTranspose (bool UseTranspose)
Broken Epetra_Operator member - SetUseTranspose.
int Apply (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Broken Epetra_Operator member - Apply.
int ApplyInverse (const Epetra_MultiVector &epetra_r, Epetra_MultiVector &epetra_z) const
double NormInf () const
Broken Epetra_Operator member - NormInf.
const char * Label () const
Epetra_Operator::Label - returns a string describing the operator.
bool UseTranspose () const
Broken Epetra_Operator member - UseTranspose.
bool HasNormInf () const
Broken Epetra_Operator member - HasNormInf.
const Epetra_Comm & Comm () const
Returns the Epetra MPI_Comm object.
const Epetra_Map & OperatorDomainMap () const
Epetra_Operator member - OperatorDomainMap.
const Epetra_Map & OperatorRangeMap () const
Epetra_Operator member - OperatorRangeMap.
Private Attributes
Preconditioner * Oomph_lib_preconditioner_pt
A pointer to the oomph-lib preconditioner.
Epetra_SerialComm Operator_comm
An Epetra Serial Comm object.
bool Use_epetra_values
Epetra_Map * Operator_map_pt
std::string Preconditioner_label
a label for the preconditioner (for Epetra_Operator::Label())
Detailed Description
An Epetra_Operator class for oomph-lib preconditioners. A helper class for TrilinosOomphLibPreconditioner to allow an oomph-lib preconditioner (i.e. one derived from Preconditioner) to be used with a trilinos solver (TrilinosAztecOOSolver)
Constructor & Destructor Documentation
OomphLibPreconditionerEpetraOperator() [1/2]
oomph::OomphLibPreconditionerEpetraOperator::OomphLibPreconditionerEpetraOperator (Preconditioner * preconditioner_pt, bool use_epetra_values = false) inline
Constructor - takes the pointer to the oomph-lib preconditioner and the distribution of the preconditioner Note: the oomph-lib preconditioner must be setup. If use_eptra_values is true then the epetra vector values is used within the vectors passed to the oomph-lib preconditioner. If this is true none of the vector rebuild methods can be called.
       : Operator_comm(
           preconditioner_pt->distribution_pt()->communicator_pt()->mpi_comm()),
         Use_epetra_values(use_epetra_values)
 #else
       : Operator_comm(), Use_epetra_values(use_epetra_values)
 #endif
     {
       // set the ooomph-lib preconditioner
       Oomph_lib_preconditioner_pt = preconditioner_pt;
       // set the preconditioner label
       Preconditioner_label = "oomph-lib Preconditioner";
       // setup the Epetra_map
       Operator_map_pt = TrilinosEpetraHelpers::create_epetra_map(
         Oomph_lib_preconditioner_pt->distribution_pt());
     }
References oomph::TrilinosEpetraHelpers::create_epetra_map(), oomph::DistributableLinearAlgebraObject::distribution_pt(), Oomph_lib_preconditioner_pt, Operator_map_pt, and Preconditioner_label.
~OomphLibPreconditionerEpetraOperator()
oomph::OomphLibPreconditionerEpetraOperator::~OomphLibPreconditionerEpetraOperator () inline
Destructor - deletes the Epetra_map and My_global_rows vector (if MPI)
     {
       delete Operator_map_pt;
       Operator_map_pt = 0;
     }
References Operator_map_pt.
OomphLibPreconditionerEpetraOperator() [2/2]
oomph::OomphLibPreconditionerEpetraOperator::OomphLibPreconditionerEpetraOperator (const OomphLibPreconditionerEpetraOperator &) delete
Broken copy constructor.
Member Function Documentation
Apply()
int oomph::OomphLibPreconditionerEpetraOperator::Apply (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const inline
Broken Epetra_Operator member - Apply.
     {
       std::ostringstream error_message;
       error_message << "Apply() is a pure virtual Epetra_Operator member"
                     << "that is not required for a Preconditioner" << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
ApplyInverse()
int oomph::OomphLibPreconditionerEpetraOperator::ApplyInverse (const Epetra_MultiVector & epetra_r, Epetra_MultiVector & epetra_z) const inline
applies the oomph-lib preconditioner. Converts the Epetra vector applys the preconditioner by calling the oomph-lib preconditioner's preconditioner_solve functionality. NOTE : the oomph-lib preconditioner is setup prior to being passed to this class
     {
       // the oomph-lib vector for r
       DoubleVector oomph_r;
       // copy the Epetra_MultiVector r into an oomph-lib vector
       double** r_pt;
       epetra_r.ExtractView(&r_pt);
       if (Use_epetra_values)
       {
         oomph_r.set_external_values(
           Oomph_lib_preconditioner_pt->distribution_pt(), *r_pt, false);
       }
       else
       {
         oomph_r.build(Oomph_lib_preconditioner_pt->distribution_pt(), 0.0);
         unsigned nrow_local =
           Oomph_lib_preconditioner_pt->distribution_pt()->nrow_local();
         for (unsigned i = 0; i < nrow_local; i++)
         {
           oomph_r[i] = r_pt[0][i];
         }
       }
       // oomph-lib vector for Y
       DoubleVector oomph_z;
       if (Use_epetra_values)
       {
         double** z_pt;
         epetra_z.ExtractView(&z_pt);
         DoubleVector oomph_z;
         oomph_z.set_external_values(
           Oomph_lib_preconditioner_pt->distribution_pt(), *z_pt, false);
       }
       else
       {
         oomph_z.build(Oomph_lib_preconditioner_pt->distribution_pt(), 0.0);
       }
       // apply the preconditioner
       Oomph_lib_preconditioner_pt->preconditioner_solve(oomph_r, oomph_z);
       // if not using external data copy the oomph-lib vector oomph_Y back to Y
       if (!Use_epetra_values)
       {
         unsigned nrow_local =
           Oomph_lib_preconditioner_pt->distribution_pt()->nrow_local();
         for (unsigned i = 0; i < nrow_local; i++)
         {
           epetra_z.ReplaceMyValue(i, 0, oomph_z[i]);
         }
       }
       // return 0 to indicate success
       return 0;
     }
References oomph::DoubleVector::build(), oomph::DistributableLinearAlgebraObject::distribution_pt(), i, oomph::LinearAlgebraDistribution::nrow_local(), Oomph_lib_preconditioner_pt, oomph::Preconditioner::preconditioner_solve(), oomph::DoubleVector::set_external_values(), and Use_epetra_values.
Comm()
const Epetra_Comm& oomph::OomphLibPreconditionerEpetraOperator::Comm () const inline
Returns the Epetra MPI_Comm object.
     {
       return Operator_comm;
     }
References Operator_comm.
HasNormInf()
bool oomph::OomphLibPreconditionerEpetraOperator::HasNormInf () const inline
Broken Epetra_Operator member - HasNormInf.
     {
       std::ostringstream error_message;
       error_message << "HasNormInf() is a pure virtual Epetra_Operator member "
                     << "that is not required for a Preconditioner" << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Label()
const char* oomph::OomphLibPreconditionerEpetraOperator::Label () const inline
Epetra_Operator::Label - returns a string describing the operator.
     {
       return Preconditioner_label.c_str();
     }
References Preconditioner_label.
NormInf()
double oomph::OomphLibPreconditionerEpetraOperator::NormInf () const inline
Broken Epetra_Operator member - NormInf.
     {
       std::ostringstream error_message;
       error_message << "NormInf() is a pure virtual Epetra_Operator member"
                     << "that is not required for a Preconditioner" << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
operator=()
void oomph::OomphLibPreconditionerEpetraOperator::operator= (const OomphLibPreconditionerEpetraOperator &) delete
Broken assignment operator.
OperatorDomainMap()
const Epetra_Map& oomph::OomphLibPreconditionerEpetraOperator::OperatorDomainMap () const inline
Epetra_Operator member - OperatorDomainMap.
     {
       return *Operator_map_pt;
     }
References Operator_map_pt.
OperatorRangeMap()
const Epetra_Map& oomph::OomphLibPreconditionerEpetraOperator::OperatorRangeMap () const inline
Epetra_Operator member - OperatorRangeMap.
     {
       return *Operator_map_pt;
     }
References Operator_map_pt.
SetUseTranspose()
int oomph::OomphLibPreconditionerEpetraOperator::SetUseTranspose (bool UseTranspose) inline
Broken Epetra_Operator member - SetUseTranspose.
     {
       std::ostringstream error_message;
       error_message << "SetUseTranspose() is a pure virtual Epetra_Operator "
                     << "member that is not required for a Preconditioner"
                     << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
UseTranspose()
bool oomph::OomphLibPreconditionerEpetraOperator::UseTranspose () const inline
Broken Epetra_Operator member - UseTranspose.
     {
       std::ostringstream error_message;
       error_message
         << "UseTranspose() is a pure virtual Epetra_Operator member "
         << "that is not required for a Preconditioner" << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Member Data Documentation
Oomph_lib_preconditioner_pt
Preconditioner* oomph::OomphLibPreconditionerEpetraOperator::Oomph_lib_preconditioner_pt private
A pointer to the oomph-lib preconditioner.
Referenced by ApplyInverse(), and OomphLibPreconditionerEpetraOperator().
Operator_comm
Epetra_SerialComm oomph::OomphLibPreconditionerEpetraOperator::Operator_comm private
An Epetra Serial Comm object.
Referenced by Comm().
Operator_map_pt
Epetra_Map* oomph::OomphLibPreconditionerEpetraOperator::Operator_map_pt private
A pointer to an Epetra_Map object - describes distribution of the preconditioner, in this instance it is primarily used to prescribe the distribution of the residual and solution vector
Referenced by OomphLibPreconditionerEpetraOperator(), OperatorDomainMap(), OperatorRangeMap(), and ~OomphLibPreconditionerEpetraOperator().
Preconditioner_label
std::string oomph::OomphLibPreconditionerEpetraOperator::Preconditioner_label private
a label for the preconditioner (for Epetra_Operator::Label())
Referenced by Label(), and OomphLibPreconditionerEpetraOperator().
Use_epetra_values
bool oomph::OomphLibPreconditionerEpetraOperator::Use_epetra_values private
Use the epetra data within the vectors passed to the oomph-lib preconditioner. If this is true none of the vector rebuild methods can be called.
Referenced by ApplyInverse().
The documentation for this class was generated from the following file:
trilinos_solver.h