MercuryDPM: Eigen::internal::psign_impl< Packet, std::enable_if_t< NumTraits< typename unpacket_traits< Packet >::type >::IsComplex &&unpacket_traits< Packet >::vectorizable > > Struct Template Reference
Eigen::internal::psign_impl< Packet, std::enable_if_t< NumTraits< typename unpacket_traits< Packet >::type >::IsComplex &&unpacket_traits< Packet >::vectorizable > > Struct Template Reference
#include <GenericPacketMathFunctions.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC Packet run (const Packet &a)
Member Function Documentation
run()
template<typename Packet > static EIGEN_DEVICE_FUNC Packet Eigen::internal::psign_impl< Packet, std::enable_if_t< NumTraits< typename unpacket_traits< Packet >::type >::IsComplex &&unpacket_traits< Packet >::vectorizable > >::run (const Packet & a) inline static
{
     typedef typename unpacket_traits<Packet>::type Scalar;
     typedef typename Scalar::value_type RealScalar;
     typedef typename unpacket_traits<Packet>::as_real RealPacket;
     // Step 1. Compute (for each element z = x + i*y in a)
     //     l = abs(z) = sqrt(x^2 + y^2).
     // To avoid over- and underflow, we use the stable formula for each hypotenuse
     //    l = (zmin == 0 ? zmax : zmax * sqrt(1 + (zmin/zmax)**2)),
     // where zmax = max(|x|, |y|), zmin = min(|x|, |y|),
     RealPacket a_abs = pabs(a.v);
     RealPacket a_abs_flip = pcplxflip(Packet(a_abs)).v;
     RealPacket a_max = pmax(a_abs, a_abs_flip);
     RealPacket a_min = pmin(a_abs, a_abs_flip);
     RealPacket a_min_zero_mask = pcmp_eq(a_min, pzero(a_min));
     RealPacket a_max_zero_mask = pcmp_eq(a_max, pzero(a_max));
     RealPacket r = pdiv(a_min, a_max);
     const RealPacket cst_one = pset1<RealPacket>(RealScalar(1));
     RealPacket l = pmul(a_max, psqrt(padd(cst_one, pmul(r, r))));  // [l0, l0, l1, l1]
     // Set l to a_max if a_min is zero, since the roundtrip sqrt(a_max^2) may be
     // lossy.
     l = pselect(a_min_zero_mask, a_max, l);
     // Step 2 compute a / abs(a).
     RealPacket sign_as_real = pandnot(pdiv(a.v, l), a_max_zero_mask);
     Packet sign;
     sign.v = sign_as_real;
     return sign;
   }
References a, Eigen::internal::pabs(), Eigen::internal::padd(), Eigen::internal::pandnot(), Eigen::internal::pcmp_eq(), Eigen::internal::pcplxflip(), Eigen::internal::pdiv(), Eigen::internal::pmax(), Eigen::internal::pmin(), Eigen::internal::pmul(), Eigen::internal::pselect(), Eigen::internal::psqrt(), Eigen::internal::pzero(), UniformPSDSelfTest::r, SYCL::sign(), and Eigen::internal::Packet2cf::v.
The documentation for this struct was generated from the following file:
GenericPacketMathFunctions.h