MercuryDPM: klu_support.cpp File Reference
klu_support.cpp File Reference
#include "sparse_solver.h"
#include <Eigen/KLUSupport>
Macros
#define EIGEN_NO_DEBUG_SMALL_PRODUCT_BLOCKS
Functions
template<typename T >
void test_klu_support_T ()
EIGEN_DECLARE_TEST (klu_support)
Macro Definition Documentation
EIGEN_NO_DEBUG_SMALL_PRODUCT_BLOCKS
#define EIGEN_NO_DEBUG_SMALL_PRODUCT_BLOCKS
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (klu_support)
{
   CALL_SUBTEST_1(test_klu_support_T<double>());
   CALL_SUBTEST_2(test_klu_support_T<std::complex<double> >());
 }
References CALL_SUBTEST_1, CALL_SUBTEST_2, and test_klu_support_T().
test_klu_support_T()
template<typename T > void test_klu_support_T ()
{
   KLU<SparseMatrix<T, ColMajor> > klu_colmajor;
   KLU<SparseMatrix<T, RowMajor> > klu_rowmajor;
   check_sparse_square_solving(klu_colmajor);
   check_sparse_square_solving(klu_rowmajor);
   // check_sparse_square_determinant(umfpack_colmajor);
   // check_sparse_square_determinant(umfpack_rowmajor);
 }
References check_sparse_square_solving().
Referenced by EIGEN_DECLARE_TEST().