MercuryDPM: plotDoE Namespace Reference
plotDoE Namespace Reference
Variables
float rc0 = 0.5
float mus0 = 0.5
float mur0 = 0.1
float bo0 = 0.0
list rc = ["0.3", "0.5", "0.8"]
list mus = ["0", "0.5", "1"]
list mur = ["0", "0.1", "0.5"]
list bo = ["0.0", "1", "5", "25"]
fig = plt.figure(figsize=(26 / 2.54, 14 / 2.54))
fontsize
int sMax = 500
list alim = [20, 80]
list dlim = [10, 90]
int splot = 1
list x = [float(b) for b in rc]
aor = np.zeros(len(rc))
daor = np.zeros(len(rc))
shear = np.zeros([len(rc), 4])
string name = "CalibrationHeap_%s_%s_%s_%s.txt" % (rc[i], mus0, mur0, bo0)
ax = fig.add_subplot(3, 4, splot)
Variable Documentation
alim
list plotDoE.alim = [20, 80]
aor
plotDoE.aor = np.zeros(len(rc))
ax
plotDoE.ax = fig.add_subplot(3, 4, splot)
Referenced by Eigen::internal.blueNorm_impl(), oomph::RefineableTriangleMesh< ELEMENT >.compute_area_target(), GpuHelper.drawVector(), GpuHelper.drawVectorBox(), lapackNorm(), Eigen::AutoDiffJacobian< Functor >.operator()(), pblueNorm(), Eigen::internal::igammac_cf_impl< Scalar, mode >.run(), Eigen::internal::igamma_series_impl< Scalar, mode >.run(), and test_autodiff_scalar().
bo
list plotDoE.bo = ["0.0", "1", "5", "25"]
Referenced by oomph::SimpleCubicTetMesh< ELEMENT >.build_from_scaffold(), Eigen::internal::gemm_class< Scalar, is_unit_inc >.compute(), Eigen::internal::gemm_class< Scalar, is_unit_inc >.compute_kern(), Eigen::internal::gemm_class< Scalar, is_unit_inc >.innerkernel(), Eigen::internal::gemm_class< Scalar, is_unit_inc >.innerkernel_1pow(), Eigen::internal::gemm_class< Scalar, is_unit_inc >.innerkernel_1uk(), Eigen::internal::gemm_class< Scalar, is_unit_inc >.kloop(), Eigen::internal::gemm_class< Scalar, is_unit_inc >.mloop(), and Eigen::internal::gemm_class< Scalar, is_unit_inc >.nloop().
bo0
float plotDoE.bo0 = 0.0
daor
plotDoE.daor = np.zeros(len(rc))
dlim
list plotDoE.dlim = [10, 90]
fig
plotDoE.fig = plt.figure(figsize=(26 / 2.54, 14 / 2.54))
fontsize
plotDoE.fontsize
mur
list plotDoE.mur = ["0", "0.1", "0.5"]
Referenced by Slide.actionsBeforeTimeStep(), and SilbertPeriodic.SilbertPeriodic().
mur0
float plotDoE.mur0 = 0.1
mus
list plotDoE.mus = ["0", "0.5", "1"]
Referenced by Slide.actionsBeforeTimeStep(), Eigen::BDCSVD< MatrixType_, Options_ >.computeSingVals(), Eigen::BDCSVD< MatrixType_, Options_ >.computeSingVecs(), Eigen::BDCSVD< MatrixType_, Options_ >.computeSVDofM(), and Eigen::BDCSVD< MatrixType_, Options_ >.perturbCol0().
mus0
float plotDoE.mus0 = 0.5
name
string plotDoE.name = "CalibrationHeap_%s_%s_%s_%s.txt" % (rc[i], mus0, mur0, bo0)
Referenced by rapidjson::GenericValue< Encoding, Allocator >.AddMember(), VTKPointDescriptor< T >.addProperty(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >.AlgebraicRefineableQuarterCircleSectorMesh(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >.AlgebraicRefineableQuarterTubeMesh(), oomph::PressureBasedSolidLSCPreconditioner.assemble_mass_matrix_diagonal(), oomph::MeshChecker.assert_geometric_element(), oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >.BackupMeshForProjection(), testing::Benchmark.Benchmark(), binary_op_test(), oomph::SolidMesh.boundary_node_pt(), CFile.CFile(), check_sparse_solving(), check_sparse_solving_real_cases(), check_sparse_spd_solving(), check_sparse_square_solving(), DeletionBoundary.checkBoundaryAfterParticleMoved(), commandLineCG(), contributors_map_from_churn_output(), DataFiles.DataFiles(), oomph::Mesh.describe_dofs(), oomph::Mesh.describe_local_dofs(), doEigen(), EIGEN_DECLARE_TEST(), oomph::PerturbedSpineMesh.element_node_pt(), oomph::SpineMesh.element_node_pt(), FileReader.FileReader(), finalizeBenchmark(), rapidjson::GenericValue< Encoding, Allocator >.FindMember(), oomph::TypeNames.get_type_name(), BaseVTKWriter< H >.getFileName(), CFile.getName(), rapidjson::GenericValue< Encoding, Allocator >.HasMember(), HstopCurve(), DPMBase.initialiseSolve(), helpers.isNext(), lastname(), DPMBase.launchNewRun(), load(), loadingTest(), helpers.lookAhead(), oomph::MacroElementNodeUpdateChannelWithLeafletMesh< ELEMENT >.MacroElementNodeUpdateChannelWithLeafletMesh(), oomph::MacroElementNodeUpdateCollapsibleChannelMesh< ELEMENT >.MacroElementNodeUpdateCollapsibleChannelMesh(), oomph::MacroElementNodeUpdateRefineableFishMesh< ELEMENT >.MacroElementNodeUpdateRefineableFishMesh(), oomph::MacroElementNodeUpdateRefineableQuarterCircleSectorMesh< ELEMENT >.MacroElementNodeUpdateRefineableQuarterCircleSectorMesh(), oomph::MacroElementNodeUpdateRefineableQuarterTubeMesh< ELEMENT >.MacroElementNodeUpdateRefineableQuarterTubeMesh(), main(), MovingWalls.MovingWalls(), oomph::Mesh.ndof_types(), oomph::PerturbedSpineMesh.node_pt(), oomph::AlgebraicMesh.node_pt(), oomph::SolidMesh.node_pt(), oomph::SpineMesh.node_pt(), oomph::PerturbedSpineMesh.node_update(), oomph::MacroElementNodeUpdateMesh.node_update(), oomph::SpineMesh.node_update(), normalAndTangentialLoadingTest(), objectivenessTest(), contributor.operator<(), rapidjson::GenericValue< Encoding, Allocator >.operator[](), packetmath(), PointIsAboveCurve(), helpers.readOptionalVariable(), testing::Benchmark.Register(), rapidjson::GenericValue< Encoding, Allocator >.RemoveMember(), CGHandler.restart(), CGHandler.restartAndEvaluateDataFiles(), CGHandler.restartAndEvaluateRestartFiles(), statistics_while_running< T >.run(), AngleOfRepose.run(), oomph::ContinuationStorageScheme.set_consistent_pinned_positions(), oomph::ContinuationStorageScheme.set_consistent_pinned_values(), AngleOfRepose.set_study(), SilbertPeriodic.set_study(), FlowRule.setName(), FlowRule.setname(), DPMBase.setName(), File.setName(), SolidProblem< ELEMENT_TYPE >.setName(), BaseCoupling< M, O >.setName(), Funnel.setName_(), oomph::AlgebraicFishMesh< ELEMENT >.setup_algebraic_node_update(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >.setup_algebraic_node_update(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >.setup_algebraic_node_update(), oomph::MacroElementNodeUpdateRefineableQuarterCircleSectorMesh< ELEMENT >.setup_macro_element_node_update(), oomph::MacroElementNodeUpdateRefineableQuarterTubeMesh< ELEMENT >.setup_macro_element_node_update(), BaseCluster.setupInitialConditions(), statistics_while_running< T >.statistics_while_running(), StatisticsVector< T >.StatisticsVector(), type_name(), unary_op_test(), WallVTKWriter.write(), writeHelpers(), VTKData.writePointData(), ChutePeriodic.writeToLocalFolder(), and SolidProblem< ELEMENT_TYPE >.writeToVTK().
rc
list plotDoE.rc = ["0.3", "0.5", "0.8"]
Referenced by HeatedCircularPenetratorElement.centre(), CircularPenetratorElement.centre(), and main().
rc0
float plotDoE.rc0 = 0.5
shear
plotDoE.shear = np.zeros([len(rc), 4])
Referenced by oomph::SphericalNavierStokesEquations.compute_shear_stress(), and oomph::SphericalNavierStokesEquations.extract_velocity().
sMax
int plotDoE.sMax = 500
splot
int plotDoE.splot = 1
x
list plotDoE.x = [float(b) for b in rc]
Examples
/home/plath/mercurydpm2/mercurydpm/Eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
Referenced by Eigen::internal.__UNPACK_TYPE__(), Eigen::KLU< MatrixType_ >._solve_impl(), Eigen::PardisoImpl< Derived >._solve_impl(), Eigen::UmfPackLU< MatrixType_ >._solve_impl(), Eigen::AccelerateImpl< MatrixType_, UpLo_, Solver_, EnforceSquare_ >._solve_impl(), Eigen::SuperLU< MatrixType_ >._solve_impl(), Eigen::PastixBase< Derived >._solve_impl(), Eigen::DiagonalPreconditioner< Scalar_ >._solve_impl(), Eigen::IncompleteCholesky< Scalar, UpLo_, OrderingType_ >._solve_impl(), Eigen::IncompleteLUT< Scalar_, StorageIndex_ >._solve_impl(), Eigen::IterativeSolverBase< Derived >._solve_impl(), Eigen::IncompleteLU< Scalar_ >._solve_impl(), Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >._solve_vector_with_guess_impl(), Eigen::ConjugateGradient< MatrixType_, UpLo_, Preconditioner_ >._solve_vector_with_guess_impl(), Eigen::LeastSquaresConjugateGradient< MatrixType_, Preconditioner_ >._solve_vector_with_guess_impl(), Eigen::BiCGSTABL< MatrixType_, Preconditioner_ >._solve_vector_with_guess_impl(), Eigen::DGMRES< MatrixType_, Preconditioner_ >._solve_vector_with_guess_impl(), Eigen::GMRES< MatrixType_, Preconditioner_ >._solve_vector_with_guess_impl(), Eigen::IDRS< MatrixType_, Preconditioner_ >._solve_vector_with_guess_impl(), Eigen::IDRSTABL< MatrixType_, Preconditioner_ >._solve_vector_with_guess_impl(), Eigen::MINRES< MatrixType_, UpLo_, Preconditioner_ >._solve_vector_with_guess_impl(), abs(), Eigen::bfloat16_impl.abs(), Eigen::numext.abs(), SYCL.abs(), Eigen::internal.absolute_split(), acos(), Eigen::numext.acos(), Eigen::numext.acosh(), RefineableDrivenCavityProblem< ELEMENT >.actions_after_adapt(), QuarterCircleDrivenCavityProblem< ELEMENT >.actions_after_adapt(), PRefineableDrivenCavityProblem< ELEMENT >.actions_after_adapt(), RefineableConvectionProblem< NST_ELEMENT, AD_ELEMENT >.actions_after_adapt(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >.actions_after_distribute(), StefanBoltzmannProblem< ELEMENT >.actions_before_implicit_timestep(), UnsteadyHeatProblem< ELEMENT >.actions_before_implicit_timestep(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >.actions_before_implicit_timestep(), LinearWaveProblem< ELEMENT, TIMESTEPPER >.actions_before_implicit_timestep(), RefineableUnsteadyHeatProblem< ELEMENT >.actions_before_implicit_timestep(), SphericalSpinUpProblem< ELEMENT >.actions_before_implicit_timestep(), BrethertonProblem< ELEMENT >.actions_before_newton_convergence_check(), RefineableAdvectionDiffusionProblem< ELEMENT >.actions_before_newton_solve(), TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >.actions_before_newton_solve(), SUPGAdvectionDiffusionProblem< ELEMENT >.actions_before_newton_solve(), OneDPoissonProblem< ELEMENT >.actions_before_newton_solve(), PoissonProblem< ELEMENT >.actions_before_newton_solve(), MultiPoissonProblem< ELEMENT >.actions_before_newton_solve(), RefineableTwoDPoissonProblem< ELEMENT >.actions_before_newton_solve(), EntryFlowProblem< ELEMENT >.actions_before_newton_solve(), RefineableTwoMeshFluxPoissonProblem< ELEMENT >.actions_before_newton_solve(), RefineableConvectionProblem< NST_ELEMENT, AD_ELEMENT >.actions_before_newton_solve(), FluxPoissonMGProblem< ELEMENT, MESH >.actions_before_newton_solve(), UnitCubePoissonMGProblem< ELEMENT, MESH >.actions_before_newton_solve(), QuarterCircleDrivenCavityProblem2< ELEMENT >.actions_before_newton_solve(), SteadyCurvedTubeProblem< ELEMENT >.actions_before_newton_solve(), SteadyHelicalProblem< ELEMENT >.actions_before_newton_solve(), QuarterCircleDrivenCavityProblem< ELEMENT >.actions_before_newton_solve(), FpTestProblem.actions_before_newton_solve(), SteadyTubeProblem< ELEMENT >.actions_before_newton_solve(), FallingBlockProblem< ELEMENT >.actions_before_newton_solve(), RefineablePoissonProblem< ELEMENT >.actions_before_newton_solve(), EighthSpherePoissonProblem< ELEMENT >.actions_before_newton_solve(), RefineableOneDPoissonProblem< ELEMENT >.actions_before_newton_solve(), PRefineableOneDPoissonProblem< ELEMENT >.actions_before_newton_solve(), FluxPoissonProblem< ELEMENT >.actions_before_newton_solve(), TwoMeshFluxPoissonProblem< ELEMENT >.actions_before_newton_solve(), ThreeDPoissonProblem< ELEMENT >.actions_before_newton_solve(), TestPoissonProblem< ELEMENT >.actions_before_newton_solve(), TestRefineablePoissonProblem< ELEMENT >.actions_before_newton_solve(), oomph::StreamfunctionProblem.actions_before_solve(), LawinenBox.actionsBeforeTimeStep(), DPM.actionsBeforeTimeStep(), oomph::SphericalNavierStokesEquations.actual(), my_functor.actual_df(), oomph::SphericalNavierStokesEquations.actual_dr(), oomph::SphericalNavierStokesEquations.actual_dth(), oomph::RefineableGmshTetMesh< ELEMENT >.adapt(), oomph::TreeBasedRefineableMeshBase.adapt_mesh(), Eigen::internal.addResults(), adolc_forward_jacobian(), Eigen::internal::TensorContractionBlockMemAllocator< LhsScalar, RhsScalar >.allocateSlices(), Global_Parameters.analytic_solution1(), Global_Parameters.analytic_solution2(), ExactSolution.analytical_outer_unit_normal(), AnnularDiskProblem< ELASTICITY_ELEMENT >.AnnularDiskProblem(), oomph::ProblemBasedShiftInvertOperator.apply(), Anasazi::OperatorTraits< double, oomph::DoubleMultiVector, oomph::DoubleMultiVectorOperator >.Apply(), ExtrudedMovingCylinderProblem< TWO_D_ELEMENT, THREE_D_ELEMENT >.apply_boundary_conditions(), UnstructuredFvKProblem< ELEMENT >.apply_boundary_conditions(), TetmeshPoissonProblem< ELEMENT >.apply_boundary_conditions(), UnstructuredPoissonProblem< ELEMENT >.apply_boundary_conditions(), PoissonProblem< ELEMENT >.apply_boundary_conditions(), PMLStructuredCubicHelmholtz< ELEMENT >.apply_boundary_conditions(), PMLHelmholtzMGProblem< ELEMENT >.apply_boundary_conditions(), VorticityRecoveryProblem< ELEMENT >.apply_boundary_conditions(), TwoDDGProblem< ELEMENT >.apply_boundary_conditions(), TwoDDGProblem< ELEMENT >.apply_initial_conditions(), Eigen::internal.apply_rotation_in_the_plane(), Eigen::MatrixBase< Derived >.applyOnTheLeft(), Eigen::MatrixBase< Derived >.applyOnTheRight(), Eigen::Array< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >.Array(), array_bessel_functions(), array_reverse_extra(), array_special_functions(), Eigen::numext.asin(), Eigen::numext.asinh(), oomph::Newmark< NSTEPS >.assign_initial_data_values(), VorticityRecoveryProblem< ELEMENT >.assign_synthetic_veloc_field(), oomph::StreamfunctionProblem.assign_velocities(), sphericalHarmonics.associatedLegendrePolynomials(), Eigen::numext.atan(), atan2(), Eigen::numext.atan2(), Eigen::numext.atanh(), oomph::SolarRadiationBase.atmospheric_radiation(), oomph::AugmentedProblemGMRES.augmented_matrix_multiply(), oomph::Multi_domain_functions.aux_setup_multi_domain_interaction(), Global_Physical_Variables.axial_pressure_gradient(), AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >.AxialSpineQuarterTubeMesh(), SmallMatrix< numberOfRows, numberOfColumns >.axpy(), SmallVector< numberOfRows >.axpy(), basic_tuple_test(), basicStuff(), Eigen.bessel_i0(), Eigen.bessel_i0e(), Eigen.bessel_i1(), Eigen.bessel_i1e(), Eigen.bessel_j0(), Eigen.bessel_j1(), Eigen.bessel_k0(), Eigen.bessel_k0e(), Eigen.bessel_k1(), Eigen.bessel_k1e(), Eigen.bessel_y0(), Eigen.bessel_y1(), Global_Parameters.BesselJ(), Global_Parameters.BesselY(), CRBond_Bessel.bessik01a(), CRBond_Bessel.bessik01b(), CRBond_Bessel.bessikna(), CRBond_Bessel.bessiknb(), CRBond_Bessel.bessikv(), CRBond_Bessel.bessjy01a(), CRBond_Bessel.bessjy01b(), CRBond_Bessel.bessjyna(), CRBond_Bessel.bessjynb(), CRBond_Bessel.bessjyv(), Eigen.betainc(), Eigen::internal.bicgstab(), Eigen::internal.bicgstabl(), binary_ops_test(), Eigen::test.bits(), Global_Parameters.blend(), Global_Parameters.blended_grad_velocity_pseudo_singularity_for_couette(), Global_Parameters.blended_pressure_pseudo_singularity_for_couette(), Global_Parameters.blended_velocity_pseudo_singularity_for_couette(), oomph::AxisymmetricLinearElasticityEquationsBase.body_force(), Global_Parameters.body_force(), ProblemParameters.body_force(), oomph::LinearElasticityEquationsBase< DIM >.body_force(), oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >.body_force(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase.body_force(), oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >.body_force(), typed_logicals_test_impl< ArrayType >.bool_to_scalar(), ProblemParameters.boundary_accel_0(), ProblemParameters.boundary_accel_1(), ProblemParameters.boundary_d2fluxdt2_0(), ProblemParameters.boundary_d2fluxdt2_1(), ProblemParameters.boundary_dfluxdt_0(), ProblemParameters.boundary_dfluxdt_1(), ProblemParameters.boundary_displ_0(), ProblemParameters.boundary_displ_1(), ProblemParameters.boundary_flux_0(), ProblemParameters.boundary_flux_1(), ProblemParameters.boundary_pressure(), TestProblem.boundary_pressure(), Global_Parameters.boundary_traction(), ProblemParameters.boundary_traction(), ProblemParameters.boundary_veloc_0(), ProblemParameters.boundary_veloc_1(), Boundary_Items.boundary_velocity(), bug1213_1(), bug_1622(), bug_817(), oomph::RefineableQElement< 3 >.build(), oomph::RefineableSolidQElement< 3 >.build(), oomph::RefineableQElement< 2 >.build(), oomph::RefineableSolidQElement< 2 >.build(), oomph::QuadFromTriangleMesh< ELEMENT >.build_from_scaffold(), oomph::CircularCylindricalShellMesh< ELEMENT >.build_mesh(), oomph::FishMesh< ELEMENT >.build_mesh(), oomph::BrickFromTetMesh< ELEMENT >.build_mesh(), calc_indices(), oomph::RefineableSolidCubicMesh< ELEMENT >.calculate_boundary_coordinate_of_node(), DragNusseltCalculationElement< ELEMENT >.calculate_drag_nusselt(), TorqueCalculationElement< ELEMENT >.calculate_torque(), call_solver(), Eigen::internal.cast(), Eigen::numext.cbrt(), SYCL.ceil(), oomph::Hankel_functions_for_helmholtz_problem.CHankel_first(), mathsFunc.chebyshev(), check_abs(), check_abs< bool >(), check_all_in_range(), check_arg(), check_atan2(), FourierDecomposedHelmholtzProblem< ELEMENT >.check_gamma(), check_histogram(), check_in_range(), oomph::RefineableQElement< 3 >.check_integrity(), check_qtvector_matrix(), check_qtvector_quaternion(), check_qtvector_transform(), check_sparse_solving(), check_sparse_solving_real_cases(), check_stddeque_matrix(), check_stddeque_quaternion(), check_stddeque_transform(), check_stdlist_matrix(), check_stdlist_quaternion(), check_stdlist_transform(), check_stdvector_matrix(), check_stdvector_quaternion(), check_stdvector_transform(), check_symbolic_index(), oomph.checked_dynamic_cast(), oomph.checked_static_cast(), VolumeCoupling.checkParticlesInFiniteElems(), mathsFunc.chi_squared(), mathsFunc.chi_squared_prob(), Eigen::internal.chkder(), exp_complex_test_impl< Scalar, Packet, HasExp >.cis(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >.CoatedDiskProblem(), CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >.CoatedSphereProblem(), UnstructuredFvKProblem< ELEMENT >.complete_problem_setup(), DarcyProblem< ELEMENT >.complete_problem_setup(), HomogenisationProblem< ELEMENT >.complete_problem_setup(), oomph::HelmholtzGMRESMG< MATRIX >.complex_matrix_multiplication(), oomph::HelmholtzSmoother.complex_matrix_multiplication(), Eigen::internal.complex_rsqrt(), Eigen::internal.complex_sqrt(), oomph::PMLFourierDecomposedHelmholtzEquations.compute_complex_r(), ModalPRefineableQPoissonElement< DIM >.compute_energy_error(), oomph::PRefineableQLinearElasticityElement< DIM >.compute_energy_error(), oomph::PRefineableQPoissonElement< DIM >.compute_energy_error(), ModalPoissonEquations< DIM >.compute_error(), MyTaylorHoodElement.compute_error(), oomph::NavierStokesElementWithSingularity< BASIC_NAVIER_STOKES_ELEMENT >.compute_error(), oomph::MultiPoissonEquations< DIM, NFIELDS >.compute_error(), PoissonElementWithSingularity< BASIC_POISSON_ELEMENT >.compute_error(), Rotateable< ELEMENT >.compute_error(), oomph::AdvectionDiffusionEquations< DIM >.compute_error(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >.compute_error(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.compute_error(), oomph::AxisymAdvectionDiffusionEquations.compute_error(), oomph::AxisymmetricLinearElasticityEquations.compute_error(), oomph::BiharmonicEquations< DIM >.compute_error(), oomph::DisplacementBasedFoepplvonKarmanEquations.compute_error(), oomph::FoepplvonKarmanEquations.compute_error(), oomph::FourierDecomposedHelmholtzEquations.compute_error(), oomph::HelmholtzEquations< DIM >.compute_error(), oomph::LinearElasticityEquations< DIM >.compute_error(), oomph::LinearWaveEquations< DIM >.compute_error(), oomph::PMLFourierDecomposedHelmholtzEquations.compute_error(), oomph::PMLHelmholtzEquations< DIM >.compute_error(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >.compute_error(), oomph::PoissonEquations< DIM >.compute_error(), oomph::SphericalAdvectionDiffusionEquations.compute_error(), oomph::SteadyAxisymAdvectionDiffusionEquations.compute_error(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations.compute_error(), oomph::UnsteadyHeatEquations< DIM >.compute_error(), oomph::WomersleyEquations< DIM >.compute_error(), oomph::YoungLaplaceEquations.compute_error(), oomph::AxisymmetricPoroelasticityEquations.compute_error(), oomph::DarcyEquations< DIM >.compute_error(), oomph::PoroelasticityEquations< DIM >.compute_error(), oomph::AxisymmetricNavierStokesEquations.compute_error(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.compute_error(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.compute_error(), oomph::NavierStokesEquations< DIM >.compute_error(), oomph::PolarNavierStokesEquations.compute_error(), oomph::SpaceTimeNavierStokesEquations< DIM >.compute_error(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >.compute_error(), oomph::SphericalNavierStokesEquations.compute_error(), oomph::SphericalNavierStokesEquations.compute_error_e(), oomph::RefineablePoissonEquations< DIM >.compute_exact_Z2_error(), oomph::SolidFiniteElement.compute_norm(), oomph::FourierDecomposedHelmholtzEquations.compute_norm(), oomph::PMLFourierDecomposedHelmholtzEquations.compute_norm(), oomph::PMLHelmholtzEquations< DIM >.compute_norm(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >.compute_norm(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.compute_norm(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >.compute_norm(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations.compute_norm(), oomph::TimeHarmonicLinearElasticityEquations< DIM >.compute_norm(), oomph::UnsteadyHeatEquations< DIM >.compute_norm(), oomph::AxisymmetricNavierStokesEquations.compute_physical_size(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.compute_physical_size(), oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >.compute_pml_coefficients(), oomph::PMLFourierDecomposedHelmholtzEquations.compute_pml_coefficients(), oomph::PMLHelmholtzEquations< DIM >.compute_pml_coefficients(), oomph::SphericalNavierStokesEquations.compute_shear_stress(), oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >.compute_stabilisation_parameter(), HGrid.computeHashBucketIndex(), Mercury2D.computeInternalForces(), Mercury3D.computeInternalForces(), DPM.computeLocalCGHGrid(), DPM.computeLocalVolumeFractionHGrid(), Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >.computeRotationScaling(), Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >.computeScalingRotation(), SCoupling< M, O >.computeSCouplingForcesFromTriangles(), HertzianSinterInteraction.computeSinterForce(), Mercury3D.computeWallForces(), VolumeCoupling.computeWeightOnParticles(), conj(), Eigen.conj(), Eigen::internal.conjugate_gradient(), Eigen::internal.conservative_sparse_sparse_product_impl(), ContactProblem< ELEMENT >.ContactProblem(), contraction_batch(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >.contribution_to_total_porous_flux(), HorizontalBaseScrew.convertLimits(), copy(), copy_back(), cos(), Eigen::numext.cos(), mathsFunc.cos(), Eigen::numext.cosh(), ChuteWithContraction.create_inflow_particle(), StefanBoltzmannProblem< ELEMENT >.create_melt_elements(), oomph::GmshTetScaffoldMesh.create_mesh_from_msh_file(), SCoupling< M, O >.createDPMWallsFromFiniteElems(), csr_sum_duplicates(), ctms_decompositions(), SYCL.cube(), SYCL.cwiseMax(), SYCL.cwiseMin(), Global_Parameters.d2_u_r_dt2(), Global_Parameters.d2_u_theta_dt2(), Global_Parameters.d2_u_z_dt2(), Global_Parameters.d_u_r_dt(), Global_Parameters.d_u_theta_dt(), Global_Parameters.d_u_z_dt(), oomph::Orthpoly.ddlegendre(), MeshDeformation.deform_mesh(), oomph::SolutionFunctor.derivative(), determinant(), Eigen::NumericalDiff< Functor_, mode >.df(), chwirut2_functor.df(), hahn1_functor.df(), MGH09_functor.df(), thurber_functor.df(), hybrj_functor.df(), lmder_functor.df(), lmstr_functor.df(), oomph::ScalarAdvectionEquations< DIM >.dflux_du(), Eigen::DGMRES< MatrixType_, Preconditioner_ >.dgmres(), Eigen::DGMRES< MatrixType_, Preconditioner_ >.dgmresApplyDeflation(), Eigen::DGMRES< MatrixType_, Preconditioner_ >.dgmresCycle(), HGridOptimiser.diffPdfInt(), oomph::DiskWithTorusAroundEdgeTetMeshFacetedSurface.DiskWithTorusAroundEdgeTetMeshFacetedSurface(), Eigen.divup(), oomph::Orthpoly.dlegendre(), oomph::SolidHelpers.doc_2D_principal_stress(), UnstructuredFluidProblem< ELEMENT >.doc_boundary_coordinates(), oomph::Mesh.doc_boundary_coordinates(), DiskShockWaveProblem< ELEMENT, TIMESTEPPER >.doc_displ_and_veloc(), oomph::OcTree.doc_face_neighbours(), oomph::Z2ErrorEstimator.doc_flux(), oomph::FSI_functions.doc_fsi(), oomph::BinaryTree.doc_neighbours(), oomph::QuadTree.doc_neighbours(), DarcyProblem< ELEMENT >.doc_shape_functions(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >.doc_solid_boundary_coordinates(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >.doc_solid_boundary_coordinates(), UnstructuredFvKProblem< ELEMENT >.doc_solution(), MeltContactProblem< ELEMENT >.doc_solution(), ContactProblem< ELEMENT >.doc_solution(), UnsteadyHeatMeltProblem< ELEMENT >.doc_solution(), StefanBoltzmannProblem< ELEMENT >.doc_solution(), PMLStructuredCubicHelmholtz< ELEMENT >.doc_solution(), DiskShockWaveProblem< ELEMENT, TIMESTEPPER >.doc_solution(), CompressedSquareProblem< ELEMENT >.doc_solution(), AxisymmetricVibratingShellProblem< ELEMENT >.doc_solution(), VibratingShellProblem< ELEMENT >.doc_solution(), RefineableUnsteadyHeatProblem< ELEMENT >.doc_solution(), PressureWaveFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >.doc_solution(), CantileverProblem< ELEMENT >.doc_solution(), RayleighProblem< ELEMENT, TIMESTEPPER >.doc_solution(), RayleighTractionProblem< ELEMENT, TIMESTEPPER >.doc_solution(), StaticDiskCompressionProblem< ELEMENT >.doc_solution(), DiskOscillationProblem< ELEMENT >.doc_solution(), SimpleShearProblem< ELEMENT >.doc_solution(), oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >.doc_solution(), FSIChannelWithLeafletProblem< ELEMENT >.doc_solution(), oomph::OcTree.doc_true_edge_neighbours(), Eigen::EigenSolver< MatrixType_ >.doComputeEigenvectors(), doEigen(), Eigen::internal.dogleg(), dont_over_optimize(), oomph::NavierStokesSurfacePowerElement< ELEMENT >.drag_force(), dsdot(), BiharmonicTestFunctions2.dudn_E(), BiharmonicTestFunctions2.dudn_N(), BiharmonicTestFunctions1.dudn_NE(), BiharmonicTestFunctions2.dudn_S(), BiharmonicTestFunctions2.dudn_W(), BiharmonicTestFunctions2.dudx_0(), BiharmonicTestFunctions2.dudx_1(), oomph::DummyErrorEstimator.DummyErrorEstimator(), oomph::TAxisymmetricPoroelasticityElement< ORDER >.edge_flux_interpolation_point_global(), oomph::TRaviartThomasDarcyElement< ORDER >.edge_flux_interpolation_point_global(), oomph::TPoroelasticityElement< ORDER >.edge_gauss_point_global(), EIGEN_DECLARE_TEST(), Eigen::internal.EIGEN_MATHFUNC_RETVAL(), Eigen::numext.EIGEN_MATHFUNC_RETVAL(), Eigen::internal.eigen_pastix(), ElasticQuadFromTriangleMesh< ELEMENT >.el_compute_norm(), Eigen::MaxSizeVector< T >.emplace_back(), PMLStructuredCubicHelmholtz< ELEMENT >.enable_pmls(), EntryFlowProblem< ELEMENT >.EntryFlowProblem(), Eigen::numext.equal_strict(), HGridCell.equals(), typed_logicals_test_impl< ArrayType >.eval_bool_and(), typed_logicals_test_impl< ArrayType >.eval_bool_not(), typed_logicals_test_impl< ArrayType >.eval_bool_or(), typed_logicals_test_impl< ArrayType >.eval_bool_xor(), Global_Parameters.exact_axisym_potential(), Global_Parameters.exact_couette(), TanhSolnForLinearWave.exact_d2udt2(), TanhSolnForLinearWave.exact_dudt(), ProblemParameters.exact_minus_dudr(), MeshDeformation.exact_normal(), oomph::YoungLaplaceEquations.exact_position(), ProblemParameters.exact_soln(), oomph::SarahBL.exact_soln(), SarahBL.exact_soln(), TestProblem.exact_soln(), oomph::MyProblem.exact_solution(), Global.exact_solution(), Global_Parameters.exact_solution(), Global_Parameters.exact_solution_th(), TanhSolnForLinearWave.exact_u(), Global_Parameters.exact_u(), Eigen::numext.exp(), SYCL.exp(), Eigen::numext.exp2(), expfn(), Eigen::internal::std_fallback.expm1(), SYCL.expm1(), oomph::PVDEquations< DIM >.extended_output(), oomph::PVDEquationsWithPressure< DIM >.extended_output(), Eigen::internal::blas_traits< XprType >.extract(), Eigen::internal::blas_traits< CwiseUnaryOp< scalar_conjugate_op< Scalar >, NestedXpr > >.extract(), Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain >, NestedXpr > >.extract(), Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, NestedXpr, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain > > >.extract(), Eigen::internal::blas_traits< CwiseUnaryOp< scalar_opposite_op< Scalar >, NestedXpr > >.extract(), Eigen::internal::blas_traits< Transpose< NestedXpr > >.extract(), Eigen::internal.extract128(), Eigen::internal.extract256(), Eigen::internal.extract2Packet16h(), oomph::SphericalNavierStokesEquations.extract_velocity(), Eigen::internal::blas_traits< CwiseUnaryOp< scalar_conjugate_op< Scalar >, NestedXpr > >.extractScalarFactor(), Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain >, NestedXpr > >.extractScalarFactor(), Eigen::internal::blas_traits< CwiseBinaryOp< scalar_product_op< Scalar >, NestedXpr, const CwiseNullaryOp< scalar_constant_op< Scalar >, Plain > > >.extractScalarFactor(), Eigen::internal::blas_traits< CwiseUnaryOp< scalar_opposite_op< Scalar >, NestedXpr > >.extractScalarFactor(), Eigen::internal::blas_traits< Transpose< NestedXpr > >.extractScalarFactor(), TwoNodePoissonElement.f(), SingleElement.face_normal(), Eigen::internal.fast_twosum(), fcn_chkder(), Eigen::internal.fdjac1(), fft_rmse(), NonRefineableBinArray.fill_bin_by_diffusion(), oomph::NonlinearSurfaceContactElement< ELEMENT >.fill_in_contribution_to_residuals_surface_contact(), oomph::LinearSurfaceContactElement< ELEMENT >.fill_in_contribution_to_residuals_surface_contact(), oomph::HeatedLinearSurfaceContactElement< ELEMENT >.fill_in_contribution_to_residuals_surface_contact(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >.fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >.fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::NavierStokesEquations< 2 >.fill_in_generic_dresidual_contribution_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >.fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::PointFluidInterfaceBoundingElement.fill_in_generic_residual_contribution_interface_boundary(), oomph::LineFluidInterfaceBoundingElement.fill_in_generic_residual_contribution_interface_boundary(), GlobalParameters.find_node_on_centerline(), PerturbationSolution.first_order_perturbation_for_plot(), SYCL.floor(), oomph::AxisymmetricPoroelasticityEquations.fluid_body_force(), ProblemParameters.Fluid_body_force(), oomph::ScalarAdvectionEquations< DIM >.flux(), BiharmonicTestFunctions1.flux0_NE(), BiharmonicTestFunctions1.flux1_NE(), ExactSolution.flux_into_bulk(), oomph::FoldHandler.FoldHandler(), foo(), for(), oomph::PoroelasticityEquations< DIM >.force_fluid(), oomph::PoroelasticityEquations< DIM >.force_solid(), forward_jacobian(), forward_jacobian_cpp11(), FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >.FourierDecomposedTimeHarmonicLinearElasticityProblem(), FreeSurfaceRotationProblem< ELEMENT >.FreeSurfaceRotationProblem(), FSICollapsibleChannelProblem< ELEMENT >.FSICollapsibleChannelProblem(), oomph::SarahBL.full_exact_soln(), SarahBL.full_exact_soln(), PerturbationSolution.full_soln(), oomph::FullCircleMesh< ELEMENT >.FullCircleMesh(), CRBond_Bessel.gamma(), Eigen::internal::unary_pow.gen_pow(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >.generic_actions_after(), Eigen::internal.generic_atan(), Eigen::internal.generic_exp2(), Eigen::internal.generic_expm1(), Eigen::internal.generic_log1p(), Eigen::internal.generic_pow(), Eigen::internal.generic_pow_impl(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations.geometric_jacobian(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement.geometric_jacobian(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement.geometric_jacobian(), oomph::RefineableAxisymAdvectionDiffusionEquations.geometric_jacobian(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations.geometric_jacobian(), oomph::RefineableAxisymmetricNavierStokesEquations.geometric_jacobian(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations.geometric_jacobian(), oomph::RefineableSphericalAdvectionDiffusionEquations.geometric_jacobian(), oomph::RefineableSphericalNavierStokesEquations.geometric_jacobian(), oomph::FoepplvonKarmanEquations.get_airy_forcing_fvk(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >.get_alpha(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >.get_alpha(), PerturbationSolution.get_azimuthal_angle(), oomph::LinearisedAxisymmetricNavierStokesEquations.get_base_flow_d_dudx_dX(), oomph::LinearisedAxisymmetricNavierStokesEquations.get_base_flow_duds(), oomph::LinearisedAxisymmetricNavierStokesEquations.get_base_flow_dudt(), oomph::LinearisedAxisymmetricNavierStokesEquations.get_base_flow_dudx(), oomph::LinearisedNavierStokesEquations.get_base_flow_dudx(), oomph::LinearisedAxisymmetricNavierStokesEquations.get_base_flow_p(), oomph::LinearisedAxisymmetricNavierStokesEquations.get_base_flow_u(), oomph::LinearisedNavierStokesEquations.get_base_flow_u(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >.get_beta(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >.get_beta(), oomph::PolarNavierStokesEquations.get_body_force(), oomph::AxisymmetricNavierStokesEquations.get_body_force_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.get_body_force_axi_nst(), oomph::LinearisedAxisymmetricNavierStokesEquations.get_body_force_base_flow(), oomph::AxisymmetricNavierStokesEquations.get_body_force_gradient_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.get_body_force_gradient_axi_nst(), oomph::LinearisedAxisymmetricNavierStokesEquations.get_body_force_gradient_base_flow(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.get_body_force_gradient_nst(), oomph::NavierStokesEquations< DIM >.get_body_force_gradient_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >.get_body_force_gradient_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >.get_body_force_gradient_nst(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.get_body_force_nst(), oomph::NavierStokesEquations< DIM >.get_body_force_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >.get_body_force_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >.get_body_force_nst(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement.get_body_force_spherical_nst(), oomph::SphericalNavierStokesEquations.get_body_force_spherical_nst(), GlobalPhysicalParameters.get_boundary_values(), get_compact_vector(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >.get_conserved_wind_cons_adv_diff(), oomph.get_conserved_wind_cons_axisym_adv_diff(), ModalPoissonEquations< DIM >.get_diff(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >.get_diff_cons_adv_diff(), oomph.get_diff_cons_axisym_adv_diff(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >.get_drag_and_torque(), oomph::Z2ErrorEstimator.get_element_errors(), oomph::DummyErrorEstimator.get_element_errors(), oomph::MyProblem.get_error_norm(), TanhSolnForLinearWave.get_exact_gradient(), TanhSolnForPoisson.get_exact_gradient(), ArcTanSolnForPoisson.get_exact_gradient(), Global_Physical_Variables.get_exact_u(), ExactSoln.get_exact_u(), SinSolution.get_exact_u(), ExactSolnForUnsteadyHeat.get_exact_u(), TanhSolnForLinearWave.get_exact_u(), TanhSolnForUnsteadyHeat.get_exact_u(), TanhSolnForAdvectionDiffusion.get_exact_u(), RachelsAdvectionDiffusion.get_exact_u(), TanhSolnForPoisson.get_exact_u(), PlanarWave.get_exact_u(), ProblemParameters.get_exact_u(), GlobalParameters.get_exact_u(), FishSolnOneDPoisson.get_exact_u(), TanhSolnForMultiPoisson.get_exact_u(), SolnForPoisson.get_exact_u(), ArcTanSolnForPoisson.get_exact_u(), TanhSolnForSteadyAxisymAdvectionDiffusion.get_exact_u(), oomph::PressureAdvectionDiffusionValidation.get_exact_u(), Boundary_Items.get_exact_u_b1(), GlobalParameters.get_exact_u_bessel(), ExactSolution.get_exact_u_for_unsteady_heat_validation(), oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >.get_flux(), oomph::LinearWaveFluxElement< ELEMENT >.get_flux(), oomph::UnsteadyHeatFluxElement< ELEMENT >.get_flux(), oomph::TemplateFreeUnsteadyHeatBaseFaceElement.get_flux(), oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >.get_flux(), oomph::AdvectionDiffusionFluxElement< ELEMENT >.get_flux(), oomph::PoissonFluxElement< ELEMENT >.get_flux(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >.get_flux(), oomph::HelmholtzFluxElement< ELEMENT >.get_flux(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >.get_flux(), oomph::PMLHelmholtzFluxElement< ELEMENT >.get_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >.get_kinetic_energy_flux(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >.get_pressure(), oomph::DarcyFaceElement< ELEMENT >.get_pressure(), oomph::PoroelasticityFaceElement< ELEMENT >.get_pressure(), TestSoln.get_pressure(), oomph::DisplacementBasedFoepplvonKarmanEquations.get_pressure_fvk(), oomph::FoepplvonKarmanEquations.get_pressure_fvk(), PerturbationSolution.get_radial_distance(), oomph::NavierStokesSurfacePowerElement< ELEMENT >.get_rate_of_traction_work(), oomph::NavierStokesSurfacePowerElement< ELEMENT >.get_rate_of_traction_work_components(), oomph::Z2ErrorEstimator.get_recovered_flux_in_patch(), oomph::VorticitySmoother< ELEMENT >.get_recovered_vorticity_in_patch(), Eigen::internal.get_runtime_value(), GlobalParameters.get_simple_exact_u(), SinSolution.get_source(), TanhSolnForUnsteadyHeat.get_source(), oomph::BiharmonicEquations< DIM >.get_source(), TanhSolnForPoisson.get_source(), ConstSourceForPoisson.get_source(), ArcTanSolnForPoisson.get_source(), GlobalParameters.get_source(), oomph::AdvectionDiffusionEquations< DIM >.get_source_adv_diff(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.get_source_adv_diff_react(), oomph::AxisymAdvectionDiffusionEquations.get_source_axi_adv_diff(), oomph::SteadyAxisymAdvectionDiffusionEquations.get_source_axisym_adv_diff(), oomph::LinearisedAxisymmetricNavierStokesEquations.get_source_base_flow(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >.get_source_cons_adv_diff(), oomph.get_source_cons_axisym_adv_diff(), oomph::AxisymmetricNavierStokesEquations.get_source_fct(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.get_source_fct(), oomph::PolarNavierStokesEquations.get_source_fct(), oomph::AxisymmetricNavierStokesEquations.get_source_fct_gradient(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.get_source_fct_gradient(), ExactSolution.get_source_for_unsteady_heat_validation(), oomph::FourierDecomposedHelmholtzEquations.get_source_fourier_decomposed_helmholtz(), oomph::LinearisedAxisymmetricNavierStokesEquations.get_source_gradient_base_flow(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.get_source_gradient_nst(), oomph::NavierStokesEquations< DIM >.get_source_gradient_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >.get_source_gradient_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >.get_source_gradient_nst(), oomph::PoissonEquations< DIM >.get_source_gradient_poisson(), oomph::HelmholtzEquations< DIM >.get_source_helmholtz(), oomph::PMLHelmholtzEquations< DIM >.get_source_helmholtz(), oomph::LinearWaveEquations< DIM >.get_source_lin_wave(), oomph::MultiPoissonEquations< DIM, NFIELDS >.get_source_multi_poisson(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.get_source_nst(), oomph::NavierStokesEquations< DIM >.get_source_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >.get_source_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >.get_source_nst(), oomph::PMLFourierDecomposedHelmholtzEquations.get_source_pml_fourier_decomposed_helmholtz(), oomph::PoissonEquations< DIM >.get_source_poisson(), ModalPoissonEquations< DIM >.get_source_poisson(), oomph::SphericalAdvectionDiffusionEquations.get_source_spherical_adv_diff(), oomph::SphericalNavierStokesEquations.get_source_spherical_nst(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.get_source_ust_heat(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >.get_source_ust_heat(), oomph::UnsteadyHeatEquations< DIM >.get_source_ust_heat(), oomph::YoungLaplaceEquations.get_spine(), oomph::YoungLaplaceEquations.get_spine_base(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >.get_traction(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >.get_traction(), oomph::LinearElasticityTractionElement< ELEMENT >.get_traction(), oomph::PoroelasticityFaceElement< ELEMENT >.get_traction(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >.get_traction(), oomph::NavierStokesTractionElement< ELEMENT >.get_traction(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >.get_traction(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >.get_traction(), oomph::AxisymmetricSolidTractionElement< ELEMENT >.get_traction(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >.get_traction(), oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElement< ELEMENT >.get_traction(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >.get_traction(), oomph::SolidTractionElement< ELEMENT >.get_traction(), oomph::DisplacementBasedFoepplvonKarmanEquations.get_traction_fvk(), oomph::StreamfunctionProblem.get_vels(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >.get_volume_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >.get_volume_flux(), StokesFlowExactWind.get_wind(), Wind_Function.get_wind(), oomph::AdvectionDiffusionEquations< DIM >.get_wind_adv_diff(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.get_wind_adv_diff_react(), oomph::AxisymAdvectionDiffusionEquations.get_wind_axi_adv_diff(), oomph::SteadyAxisymAdvectionDiffusionEquations.get_wind_axisym_adv_diff(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >.get_wind_cons_adv_diff(), oomph.get_wind_cons_axisym_adv_diff(), oomph::ScalarAdvectionEquations< DIM >.get_wind_scalar_adv(), oomph::SphericalAdvectionDiffusionEquations.get_wind_spherical_adv_diff(), oomph::FiniteElement.get_x(), SolidProblem< ELEMENT_TYPE >.get_x(), oomph::QSolidElementBase.get_x_and_xi(), oomph::QElementBase.get_x_from_macro_element(), PSD.getAreaDx(), SolidProblem< ELEMENT_TYPE >.getDeflection(), Eigen::SimplicialCholeskyBase< Derived >.getDiag(), Eigen::internal::traits< SimplicialLLT< MatrixType_, UpLo_, Ordering_ > >.getDiag(), Eigen::internal::traits< SimplicialLDLT< MatrixType_, UpLo_, Ordering_ > >.getDiag(), Eigen::internal::traits< SimplicialNonHermitianLLT< MatrixType_, UpLo_, Ordering_ > >.getDiag(), Eigen::internal::traits< SimplicialNonHermitianLDLT< MatrixType_, UpLo_, Ordering_ > >.getDiag(), Eigen::internal::traits< SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > >.getDiag(), LevelSetWall.getDistanceAndNormalLabCoordinates(), PSD.getLengthDx(), SolidProblem< ELEMENT_TYPE >.getMassMomentumEnergy(), PSD.getNumberDx(), VolumeCoupling.getProjectionMatrix(), Eigen::SimplicialCholeskyBase< Derived >.getSymm(), Eigen::internal::traits< SimplicialLLT< MatrixType_, UpLo_, Ordering_ > >.getSymm(), Eigen::internal::traits< SimplicialLDLT< MatrixType_, UpLo_, Ordering_ > >.getSymm(), Eigen::internal::traits< SimplicialNonHermitianLLT< MatrixType_, UpLo_, Ordering_ > >.getSymm(), Eigen::internal::traits< SimplicialNonHermitianLDLT< MatrixType_, UpLo_, Ordering_ > >.getSymm(), Eigen::internal::traits< SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > >.getSymm(), PSD.getVolumeDx(), oomph::Orthpoly.gl_nodes(), oomph::Orthpoly.gll_nodes(), oomph::PMLHelmholtzPowerElement< ELEMENT >.global_flux_contribution(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >.global_flux_contribution_from_helmholtz(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >.global_flux_contribution_from_solid(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >.global_power_contribution(), oomph::HelmholtzBCElementBase< ELEMENT >.global_power_contribution(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >.global_power_contribution(), oomph::PMLHelmholtzPowerElement< ELEMENT >.global_power_contribution(), Eigen::internal.gmres(), mathsFunc.goldenSectionSearch(), HGridOptimiser.goldenSectionSearch(), Global_Parameters.grad_blend(), Global_parameters.grad_f1(), Global_parameters.grad_f2(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >.grad_p_bar(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >.grad_pressure_singular_function(), Global_Parameters.grad_pressure_singularity1(), PoissonElementWithSingularity< BASIC_POISSON_ELEMENT >.grad_singular_function(), SingularPoissonSolutionElement< WRAPPED_POISSON_ELEMENT >.grad_singular_function(), oomph::NavierStokesElementWithSingularity< BASIC_NAVIER_STOKES_ELEMENT >.grad_u_bar(), PoissonElementWithSingularity< BASIC_POISSON_ELEMENT >.grad_u_bar(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >.grad_u_bar(), SingularPoissonSolutionElement< WRAPPED_POISSON_ELEMENT >.grad_u_bar(), Global_Parameters.grad_velocity_pseudo_singularity_for_couette(), oomph::NavierStokesElementWithSingularity< BASIC_NAVIER_STOKES_ELEMENT >.grad_velocity_singular_function(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >.grad_velocity_singular_function(), Global_Parameters.grad_velocity_singularity1(), Global_Parameters.grad_velocity_singularity2(), Eigen::internal::unary_pow.handle_negative_exponent(), Eigen::internal::unary_pow.handle_nonint_nonint_errors(), Global_Parameters.Hankel_first(), oomph::Hankel_functions_for_helmholtz_problem.Hankel_first(), Global_Parameters.HankelH1(), Global_Physical_Variables.height(), SimpleSpineMesh< ELEMENT >.height_fct(), Mercury3D.hGridFindContactsWithinTargetCell(), Mercury2D.hGridFindContactsWithinTargetCell(), Mercury3D.hGridFindContactsWithTargetCell(), Mercury2D.hGridFindContactsWithTargetCell(), Mercury2D.hGridFindParticleContacts(), Mercury3D.hGridFindParticleContacts(), Mercury3D.hGridFindParticlesWithTargetCell(), Mercury2D.hGridFindParticlesWithTargetCell(), Mercury2D.hGridGetInteractingParticleList(), Mercury3D.hGridGetInteractingParticleList(), Mercury3D.hGridHasContactsInTargetCell(), Mercury2D.hGridHasContactsInTargetCell(), Mercury2D.hGridHasParticleContacts(), Mercury3D.hGridHasParticleContacts(), Mercury2D.hGridUpdateParticle(), Mercury3D.hGridUpdateParticle(), oomph::HopfHandler.HopfHandler(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >.hybrd1(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >.hybrj1(), Global_Physical_Variables.hydrostatic_pressure(), Global_Physical_Variables.hydrostatic_pressure_inlet(), oomph::Global_Physical_Variables.hydrostatic_pressure_inlet_lower(), oomph::Global_Physical_Variables.hydrostatic_pressure_inlet_upper(), Global_Physical_Variables.hydrostatic_pressure_outlet(), oomph::Global_Physical_Variables.hydrostatic_pressure_outlet_lower(), oomph::Global_Physical_Variables.hydrostatic_pressure_outlet_upper(), mathsFunc.I0(), mathsFunc.I0_exp(), Eigen::internal.idrs(), Eigen::internal.idrstabl(), Eigen.igamma(), Eigen.igamma_der_a(), Eigen.igammac(), Eigen::internal.index_list_size(), Global_Physical_Variables.inflow(), Global.initial_condition(), GlobalParameters.initial_condition(), DenseLM< Scalar >.initPoints(), sparseGaussianTest< Scalar >.initPoints(), inplace(), Eigen::internal::unary_pow.int_pow(), oomph::FiniteElement.integrate_fct(), DistanceWrapper< ELEMENT >.interpolate_distance_to_ext_element_to_nodes(), oomph::NavierStokesElementWithSingularity< BASIC_NAVIER_STOKES_ELEMENT >.interpolated_p_nst(), oomph::NavierStokesElementWithSingularity< BASIC_NAVIER_STOKES_ELEMENT >.interpolated_u_nst(), PoissonElementWithSingularity< BASIC_POISSON_ELEMENT >.interpolated_u_poisson(), oomph::FiniteElement.interpolated_x(), oomph::FaceElement.interpolated_x(), oomph::RefineableQElement< 3 >.interpolated_zeta_on_face(), SYCL.inverse(), inverse_zerosized(), Eigen::numext.is_exactly_one(), Eigen::numext.is_exactly_zero(), GlobalParameters.is_in_pinned_region(), Eigen::internal::scalar_fuzzy_impl< bool >.isApprox(), Eigen::internal::scalar_fuzzy_default_impl< Scalar, false, true >.isApprox(), Eigen::internal::scalar_fuzzy_default_impl< Scalar, false, false >.isApprox(), Eigen::internal::scalar_fuzzy_default_impl< Scalar, true, false >.isApprox(), Eigen::internal.isApprox(), Eigen::internal::scalar_fuzzy_impl< bool >.isApproxOrLessThan(), Eigen::internal::scalar_fuzzy_default_impl< Scalar, false, true >.isApproxOrLessThan(), Eigen::internal::scalar_fuzzy_default_impl< Scalar, false, false >.isApproxOrLessThan(), Eigen::internal.isApproxOrLessThan(), SYCL.isfinite(), Eigen::internal.isfinite_impl(), SYCL.isinf(), Eigen::internal.isinf_impl(), Eigen::internal::scalar_fuzzy_impl< bool >.isMuchSmallerThan(), Eigen::internal::scalar_fuzzy_default_impl< Scalar, false, false >.isMuchSmallerThan(), Eigen::internal::scalar_fuzzy_default_impl< Scalar, true, false >.isMuchSmallerThan(), Eigen::internal.isMuchSmallerThan(), Eigen::internal::scalar_fuzzy_default_impl< Scalar, false, true >.isMuchSmallerThan(), SYCL.isnan(), Eigen::internal.isnan_impl(), Eigen.isNotNaN(), Eigen.isPlusInf(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >.isPowerOfTwo(), oomph::Orthpoly.jacobi(), Eigen::internal.KLoop(), kv_pair_less(), oomph::PseudoElasticPreconditioner.lagrange_multiplier_preconditioner_solve(), oomph::PseudoElasticPreconditionerOld.lagrange_multiplier_preconditioner_solve(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >.lagrangian_eulerian_translation_factor(), Eigen::internal.least_square_conjugate_gradient(), oomph::Orthpoly.legendre(), oomph::Orthpoly.legendre_vector(), SmallVector< numberOfRows >.length(), TwoDDGProblem< ELEMENT >.limit(), oomph::MinModLimiter.limit(), oomph::BlackBoxFDNewtonSolver.line_search(), helpers.linspace(), Eigen::internal.llt_rank_update_lower(), Eigen::LevenbergMarquardt< FunctorType_ >.lmder1(), Eigen::LevenbergMarquardt< FunctorType_ >.lmdif1(), Eigen::internal.lmpar(), Eigen::internal.lmpar2(), Eigen::internal.lmqrsolv(), Eigen::LevenbergMarquardt< FunctorType_ >.lmstr1(), oomph::KirchhoffLoveShellEquations.load_rate_of_work(), oomph::KirchhoffLoveBeamEquations.load_vector(), oomph::FSIHermiteBeamElement.load_vector(), oomph::KirchhoffLoveShellEquations.load_vector(), oomph::FSIDiagHermiteShellElement.load_vector(), oomph::KirchhoffLoveShellEquations.load_vector_for_rate_of_work_computation(), oomph::FSIDiagHermiteShellElement.load_vector_for_rate_of_work_computation(), SolidProblem< ELEMENT_TYPE >.loadSolidMesh(), Eigen::numext.log(), SYCL.log(), Eigen::internal::std_fallback.log1p(), SYCL.log1p(), log2(), log2_pot(), Eigen::CholmodBase< MatrixType_, UpLo_, Derived >.logDeterminant(), oomph::ExtrudedDomain.macro_element_boundary(), main(), Eigen::internal.MakeCoherentCwiseBinaryOp(), Eigen::JacobiRotation< Scalar >.makeJacobi(), Trackball.mapToSphere(), oomph::AxisymmetricPoroelasticityEquations.mass_source(), oomph::PoroelasticityEquations< DIM >.mass_source(), oomph::DarcyEquations< DIM >.mass_source(), TestProblem.mass_source(), Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >.Matrix(), Eigen.max(), oomph::DoubleMatrixBase.max_residual(), oomph::ComplexMatrixBase.max_residual(), Eigen::internal.MaybeCoherentPad(), ExactSolution.melting_surface_height(), MercuryCGSelfTest.MercuryCGSelfTest(), Eigen.min(), Eigen::LevenbergMarquardt< FunctorType_ >.minimize(), Eigen::LevenbergMarquardt< FunctorType_ >.minimizeInit(), Eigen::LevenbergMarquardt< FunctorType_ >.minimizeOneStep(), Eigen::LevenbergMarquardt< FunctorType_ >.minimizeOptimumStorage(), Eigen::LevenbergMarquardt< FunctorType_ >.minimizeOptimumStorageInit(), Eigen::LevenbergMarquardt< FunctorType_ >.minimizeOptimumStorageOneStep(), Eigen::internal.minres(), DenseLM< Scalar >.model(), sparseGaussianTest< Scalar >.model(), MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >.MortaringValidationProblem(), CRBond_Bessel.msta1(), CRBond_Bessel.msta2(), oomph::CRDoubleMatrix.multiply(), oomph::DenseDoubleMatrix.multiply(), oomph::CCDoubleMatrix.multiply(), oomph::SumOfMatrices.multiply(), oomph::MatrixVectorProduct.multiply(), oomph::DenseComplexMatrix.multiply(), oomph::CRComplexMatrix.multiply(), oomph::CCComplexMatrix.multiply(), oomph::CRDoubleMatrix.multiply_transpose(), oomph::DenseDoubleMatrix.multiply_transpose(), oomph::CCDoubleMatrix.multiply_transpose(), oomph::MatrixVectorProduct.multiply_transpose(), oomph::DenseComplexMatrix.multiply_transpose(), oomph::CRComplexMatrix.multiply_transpose(), oomph::CCComplexMatrix.multiply_transpose(), Quaternion.multiplyQuaternions(), oomph::MyProblem.my_set_initial_condition(), Eigen::test.negate(), oomph::AlgebraicMesh.node_update(), oomph::DoubleVector.norm(), WallFunction.normal(), Eigen::numext.not_equal_strict(), Eigen.operator!=(), ComplexLess< T >.operator()(), oomph::SolutionFunctor.operator()(), Eigen::internal::scalar_logistic_op< float >.operator()(), Eigen::AutoDiffJacobian< Functor >.operator()(), TestFunc1< Scalar_, NX, NY >.operator()(), Eigen::internal::accurate_log2< Scalar >.operator()(), Eigen::internal::accurate_log2< double >.operator()(), Eigen::internal::accurate_log2< float >.operator()(), Eigen::internal::MatrixExponentialScalingOp< RealScalar >.operator()(), Eigen::internal::scalar_igamma_op< Scalar >.operator()(), Eigen::internal::scalar_igamma_der_a_op< Scalar >.operator()(), Eigen::internal::scalar_igammac_op< Scalar >.operator()(), Eigen::internal::scalar_polygamma_op< Scalar >.operator()(), CwiseClampOp< Scalar >.operator()(), Eigen::internal::scalar_clamp_op< Scalar >.operator()(), Eigen::internal::scalar_bessel_i0_op< Scalar >.operator()(), Eigen::internal::scalar_bessel_i0e_op< Scalar >.operator()(), Eigen::internal::scalar_bessel_i1_op< Scalar >.operator()(), Eigen::internal::scalar_bessel_i1e_op< Scalar >.operator()(), Eigen::internal::scalar_bessel_j0_op< Scalar >.operator()(), Eigen::internal::scalar_bessel_y0_op< Scalar >.operator()(), Eigen::internal::scalar_bessel_j1_op< Scalar >.operator()(), Eigen::internal::scalar_bessel_y1_op< Scalar >.operator()(), Eigen::internal::scalar_bessel_k0_op< Scalar >.operator()(), Eigen::internal::scalar_bessel_k0e_op< Scalar >.operator()(), Eigen::internal::scalar_bessel_k1_op< Scalar >.operator()(), Eigen::internal::scalar_bessel_k1e_op< Scalar >.operator()(), Eigen::internal::scalar_betainc_op< Scalar >.operator()(), Eigen::internal::scalar_zeta_op< Scalar >.operator()(), Eigen::internal::scalar_hypot_op< Scalar, Scalar >.operator()(), Eigen::internal::scalar_atan2_op< LhsScalar, RhsScalar >.operator()(), ComplexGreater< T >.operator()(), Eigen::internal::conj_if< true >.operator()(), Eigen::internal::conj_if< false >.operator()(), Eigen::internal::scalar_logistic_op_impl< T, EnableIf >.operator()(), Eigen::internal::scalar_logistic_op_impl< T, std::enable_if_t< NumTraits< T >::IsComplex > >.operator()(), oomph::AbsCmp< T >.operator()(), chwirut2_functor.operator()(), hahn1_functor.operator()(), MGH09_functor.operator()(), thurber_functor.operator()(), hybrj_functor.operator()(), lmstr_functor.operator()(), lmder_functor.operator()(), lmdif_functor.operator()(), hybrd_functor.operator()(), my_functor.operator()(), ElementCmp.operator()(), MatrixReplacement.operator*(), Eigen::bfloat16_impl.operator-(), oomph::TriangleMesh< ELEMENT >::Point.operator<(), operator<<(), Eigen.operator==(), oomph::QExtrudedMacroElement< 3 >.output(), oomph::QMacroElement< 2 >.output(), oomph::QMacroElement< 3 >.output(), oomph::QHermiteElement< DIM >.output(), SSPorousChannelElement.output(), DistanceWrapper< ELEMENT >.output(), oomph::SCoupledElement< ELEMENT >.output(), oomph::NonlinearSurfaceContactElement< ELEMENT >.output(), oomph::LinearSurfaceContactElement< ELEMENT >.output(), oomph::UnsteadyHeatBaseFaceElement< ELEMENT >.output(), oomph::HeatedLinearSurfaceContactElement< ELEMENT >.output(), oomph::HomogenisedLinearElasticityEquations< DIM >.output(), oomph::MySolidElement< ELEMENT >.output(), oomph::AxisymmetricLinearElasticityEquations.output(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >.output(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >.output(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >.output(), oomph::DisplacementBasedFoepplvonKarmanEquations.output(), oomph::LinearElasticityEquations< DIM >.output(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >.output(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >.output(), oomph::PVDEquations< DIM >.output(), oomph::PVDEquationsWithPressure< DIM >.output(), oomph::SolidTractionElement< ELEMENT >.output(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >.output(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >.output(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations.output(), oomph::TimeHarmonicLinearElasticityEquations< DIM >.output(), oomph::VolumeCoupledElement< ELEMENT >.output(), oomph::TLinearHeatAndElasticityElement< DIM, NNODE_1D >.output(), oomph::HeatedPenetratorFluxElement< ELEMENT >.output(), oomph::THomogenisedLinearElasticityElement< DIM, NNODE_1D >.output(), oomph::NavierStokesElementWithSingularity< BASIC_NAVIER_STOKES_ELEMENT >.output(), PoissonElementWithSingularity< BASIC_POISSON_ELEMENT >.output(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >.output(), oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >.output(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.output(), oomph::AxisymAdvectionDiffusionEquations.output(), oomph::VorticitySmootherElement< ELEMENT >.output(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >.output(), oomph::PoissonFluxElement< ELEMENT >.output(), oomph::SphericalAdvectionDiffusionEquations.output(), oomph::SteadyAxisymAdvectionDiffusionEquations.output(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >.output(), oomph::VorticitySmootherElement< ELEMENT >.output_analytical_veloc_and_vorticity(), oomph::SolarRadiationBase.output_atmospheric_radiation(), oomph::SolarRadiationBase.output_diffuse_radiation_cone(), oomph::SolarRadiationBase.output_diffuse_radiation_cone_max_angle(), oomph::SolarRadiationBase.output_diffuse_radiation_cone_min_angle(), oomph::ElementWithExternalElement.output_external_elements(), ModalPoissonEquations< DIM >.output_fct(), oomph::MultiPoissonEquations< DIM, NFIELDS >.output_fct(), oomph::DisplacementBasedFoepplvonKarmanEquations.output_fct(), oomph::FoepplvonKarmanEquations.output_fct(), oomph::FourierDecomposedHelmholtzEquations.output_fct(), oomph::HelmholtzEquations< DIM >.output_fct(), oomph::PMLFourierDecomposedHelmholtzEquations.output_fct(), oomph::PMLHelmholtzEquations< DIM >.output_fct(), oomph::PoissonEquations< DIM >.output_fct(), oomph::YoungLaplaceEquations.output_fct(), Rotateable< ELEMENT >.output_fct(), oomph::AdvectionDiffusionEquations< DIM >.output_fct(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >.output_fct(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.output_fct(), oomph::AxisymAdvectionDiffusionEquations.output_fct(), oomph::AxisymmetricLinearElasticityEquations.output_fct(), oomph::AxisymmetricNavierStokesEquations.output_fct(), oomph::AxisymmetricPoroelasticityEquations.output_fct(), oomph::BiharmonicEquations< DIM >.output_fct(), oomph::DarcyEquations< DIM >.output_fct(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.output_fct(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.output_fct(), oomph::LinearElasticityEquations< DIM >.output_fct(), oomph::LinearWaveEquations< DIM >.output_fct(), oomph::NavierStokesEquations< DIM >.output_fct(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >.output_fct(), oomph::PolarNavierStokesEquations.output_fct(), oomph::PoroelasticityEquations< DIM >.output_fct(), oomph::SpaceTimeNavierStokesEquations< DIM >.output_fct(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >.output_fct(), oomph::SphericalAdvectionDiffusionEquations.output_fct(), oomph::SphericalNavierStokesEquations.output_fct(), oomph::SteadyAxisymAdvectionDiffusionEquations.output_fct(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations.output_fct(), oomph::TimeHarmonicLinearElasticityEquations< DIM >.output_fct(), oomph::UnsteadyHeatEquations< DIM >.output_fct(), oomph::WomersleyEquations< DIM >.output_fct(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >.output_imag(), oomph::PMLHelmholtzEquations< DIM >.output_imag_fct(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >.output_integration_points(), oomph::SolarRadiationBase.output_limiting_angles(), oomph::QExtrudedMacroElement< 3 >.output_macro_element_boundaries(), oomph::SurfaceMeltElement< ELEMENT >.output_melt(), oomph::FiniteElement.output_paraview(), oomph::NavierStokesEquations< DIM >.output_pressure_advection_diffusion_robin_elements(), oomph::SpaceTimeNavierStokesEquations< DIM >.output_pressure_advection_diffusion_robin_elements(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >.output_pressure_advection_diffusion_robin_elements(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >.output_real(), oomph::FourierDecomposedHelmholtzEquations.output_real_fct(), oomph::HelmholtzEquations< DIM >.output_real_fct(), oomph::PMLFourierDecomposedHelmholtzEquations.output_real_fct(), oomph::PMLHelmholtzEquations< DIM >.output_real_fct(), oomph::VorticitySmootherElement< ELEMENT >.output_smoothed_vorticity(), oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >.output_stefan_boltzmann_radiation(), oomph::PMLHelmholtzEquations< DIM >.output_total_real(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >.output_total_real(), oomph::TreeBasedRefineableMeshBase.p_adapt_mesh(), oomph::NavierStokesElementWithSingularity< BASIC_NAVIER_STOKES_ELEMENT >.p_bar(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >.p_bar(), packetmath_complex(), Eigen::internal::scalar_logistic_op< float >.packetOp(), Eigen::internal::scalar_igamma_op< Scalar >.packetOp(), Eigen::internal::scalar_igamma_der_a_op< Scalar >.packetOp(), Eigen::internal::scalar_igammac_op< Scalar >.packetOp(), Eigen::internal::scalar_polygamma_op< Scalar >.packetOp(), Eigen::internal::scalar_tanh_op< Scalar >.packetOp(), Eigen::internal::scalar_atanh_op< Scalar >.packetOp(), Eigen::internal::scalar_logistic_op_impl< T, EnableIf >.packetOp(), Eigen::internal::scalar_clamp_op< Scalar >.packetOp(), Eigen::internal::scalar_bessel_i0_op< Scalar >.packetOp(), Eigen::internal::scalar_bessel_i0e_op< Scalar >.packetOp(), Eigen::internal::scalar_bessel_i1_op< Scalar >.packetOp(), Eigen::internal::scalar_bessel_i1e_op< Scalar >.packetOp(), Eigen::internal::scalar_bessel_j0_op< Scalar >.packetOp(), Eigen::internal::scalar_bessel_y0_op< Scalar >.packetOp(), Eigen::internal::scalar_bessel_j1_op< Scalar >.packetOp(), Eigen::internal::scalar_bessel_y1_op< Scalar >.packetOp(), Eigen::internal::scalar_bessel_k0_op< Scalar >.packetOp(), Eigen::internal::scalar_bessel_k0e_op< Scalar >.packetOp(), Eigen::internal::scalar_bessel_k1_op< Scalar >.packetOp(), Eigen::internal::scalar_bessel_k1e_op< Scalar >.packetOp(), Eigen::internal::scalar_erf_op< Scalar >.packetOp(), Eigen::internal::scalar_betainc_op< Scalar >.packetOp(), Eigen::internal::scalar_zeta_op< Scalar >.packetOp(), Eigen::internal::scalar_atan2_op< LhsScalar, RhsScalar >.packetOp(), Eigen::internal::maybe_coherent_pad_helper< DerivativeType, OtherDerivativeType, std::enable_if_t< enum_ge_not_dynamic(DerivativeType::SizeAtCompileTime, OtherDerivativeType::SizeAtCompileTime)> >.pad(), Eigen::internal::maybe_coherent_pad_helper< DerivativeType, OtherDerivativeType, EnableIf >.pad(), Eigen::internal.pasin_float(), Eigen::internal.patan2(), Eigen::internal.patanh_double(), Eigen::internal.patanh_float(), Eigen::internal.pbessel_i0(), Eigen::internal.pbessel_i0e(), Eigen::internal.pbessel_i1(), Eigen::internal.pbessel_i1e(), Eigen::internal.pbessel_j0(), Eigen::internal.pbessel_j1(), Eigen::internal.pbessel_k0(), Eigen::internal.pbessel_k0e(), Eigen::internal.pbessel_k1(), Eigen::internal.pbessel_k1e(), Eigen::internal.pbessel_y0(), Eigen::internal.pbessel_y1(), Eigen::internal.pbetainc(), Eigen::internal::conj_if< true >.pconj(), Eigen::internal::conj_if< false >.pconj(), Eigen::internal.pcos< Packet4f >(), Eigen::internal.pcos< PacketXf >(), Eigen::internal.pcos_double(), Eigen::internal.pcos_float(), Eigen::internal.pcplxflip(), Eigen::internal.pcplxflip< Packet2cd >(), Eigen::internal.pcplxflip< Packet2cf >(), Eigen::internal.pcplxflip< Packet4cd >(), Eigen::internal.pcplxflip< Packet4cf >(), Eigen::internal.pcplxflip< Packet8cf >(), Eigen::internal.pdiv_complex(), oomph::CircularPenetrator.penetration(), oomph::SurfaceContactElementBase< ELEMENT >.penetration(), HeatedCircularPenetratorElement.penetration(), CircularPenetratorElement.penetration(), Global_Parameters.periodic_traction(), PeriodicLoadProblem< ELEMENT >.PeriodicLoadProblem(), PerturbationSolution.perturbation_soln_for_plot(), exp_complex_test_impl< Scalar, Packet, HasExp >.pexp1(), Eigen::internal.pexp< Packet2d >(), Eigen::internal.pexp< Packet4f >(), Eigen::internal.pexp< PacketXf >(), Eigen::internal.pexp_complex(), Eigen::internal.pexp_double(), Eigen::internal.pexp_float(), Eigen::internal.pfirst< Packet16b >(), Eigen::internal.pfirst< Packet1cf >(), Eigen::internal.pfirst< Packet4f >(), Eigen::internal.pfirst< Packet4i >(), Eigen::internal.pfirst< Packet8l >(), Eigen::internal.pgather< Eigen::half, Packet16h >(), Eigen::internal.pgather< Eigen::half, Packet32h >(), Eigen::internal.phypot_complex(), Eigen::internal.pigamma(), Eigen::internal.pigamma_der_a(), Eigen::internal.pigammac(), oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >.pin_all_non_pressure_dofs(), RefineableDrivenCavityProblem< ELEMENT >.pin_only_pressure_at_origin(), Eigen::PlainObjectBase< Derived >.PlainObjectBase(), PlateProblem< ELEMENT >.PlateProblem(), oomph::Legendre_functions_helper.plgndr1(), oomph::Legendre_functions_helper.plgndr2(), Eigen::internal.plog< Packet4f >(), Eigen::internal.plog< PacketXf >(), Eigen::internal.plog_complex(), Eigen::internal.plog_impl_double(), Eigen::internal.plog_impl_float(), PlanarWave.plot(), GlobalFct.plot_it(), Eigen::internal::conj_helper< Packet, Packet, ConjLhs, ConjRhs >.pmadd(), Eigen::internal::conj_helper< Packet, Packet, true, true >.pmadd(), oomph::PMLQuadMeshBase< ELEMENT >.pml_locate_zeta(), Eigen::internal::conj_helper< LhsScalar, RhsScalar, true, true >.pmul(), Eigen::internal::conj_helper< LhsType, RhsType, ConjLhs, ConjRhs >.pmul(), Eigen::internal::conj_helper< Packet, Packet, ConjLhs, ConjRhs >.pmul(), Eigen::internal::conj_helper< Packet, Packet, true, true >.pmul(), Eigen.poly_eval(), Eigen.poly_eval_horner(), Eigen.polygamma(), oomph::YoungLaplaceEquations.position(), oomph::NodeElementSolidOnlyMortaringElement.position_in_element(), Eigen::internal.positive_real_hypot(), Eigen::ArrayBase< Derived >.pow(), Eigen::internal.ppolygamma(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >.pre_build(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >.pre_build(), oomph::ILUZeroPreconditioner< CCDoubleMatrix >.preconditioner_solve(), oomph::PseudoElasticFSIPreconditioner.preconditioner_solve(), oomph::PseudoElasticPreconditionerSubsidiaryPreconditionerOld.preconditioner_solve(), oomph::PseudoElasticPreconditionerSubsidiaryBlockPreconditionerOld.preconditioner_solve(), Eigen::internal.predux< Packet16f >(), Eigen::internal.predux_any(), ExactSolution.prescribed_flux_for_unsteady_heat_validation(), TanhSolnForAdvectionDiffusion.prescribed_flux_on_fixed_x_boundary(), TanhSolnForPoisson.prescribed_flux_on_fixed_x_boundary(), SolnForPoisson.prescribed_flux_on_fixed_x_boundary(), ExactSolnForUnsteadyHeat.prescribed_flux_on_fixed_y_boundary(), TanhSolnForLinearWave.prescribed_flux_on_fixed_y_boundary(), GlobalParameters.prescribed_flux_on_fixed_y_boundary(), TanhSolnForUnsteadyHeat.prescribed_flux_on_fixed_y_boundary(), GlobalParameters.prescribed_incoming_flux(), ExactSoln.prescribed_traction(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >.pressure(), oomph::DarcyFaceElement< ELEMENT >.pressure(), oomph::PoroelasticityFaceElement< ELEMENT >.pressure(), Global_Parameters.pressure_couette(), Global_Parameters.pressure_load(), Global_Parameters.pressure_pseudo_singularity_for_couette(), oomph::NavierStokesElementWithSingularity< BASIC_NAVIER_STOKES_ELEMENT >.pressure_singular_function(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >.pressure_singular_function(), Global_Parameters.pressure_singularity1(), Global_Parameters.pressure_singularity2(), PressureWaveFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >.PressureWaveFSIProblem(), product(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >.project(), promote(), Eigen::internal.prsqrt< Packet2d >(), Eigen::internal.prsqrt< Packet4f >(), Eigen::internal.psin< Packet4f >(), Eigen::internal.psin< PacketXf >(), Eigen::internal.psin_double(), Eigen::internal.psin_float(), Eigen::internal.psincos_double(), Eigen::internal.psincos_float(), Eigen::internal.psincos_inner_msa_float(), Eigen::internal.psqrt(), Eigen::internal.psqrt< Packet16b >(), Eigen::internal.psqrt< Packet16f >(), Eigen::internal.psqrt< Packet2d >(), Eigen::internal.psqrt< Packet4f >(), Eigen::internal.psqrt< Packet8d >(), Eigen::internal.ptanh< Packet4f >(), Eigen::internal.ptanh< PacketXf >(), Eigen::internal.ptanh_double(), Eigen::internal.ptanh_float(), Global_Physical_Variables.pulse_wave_solution(), Eigen::internal.pzeta(), QFaceTestProblem< ELEMENT >.QFaceTestProblem(), qr(), qr_fixedsize(), qr_kahan_matrix(), Eigen::internal.qrsolv(), helpers.qSortCompare(), oomph::QuarterPipeMesh< ELEMENT >.QuarterPipeMesh(), oomph::QuarterTubeMesh< ELEMENT >.QuarterTubeMesh(), oomph::QuarterPipeDomain.r_B(), oomph::QuarterTubeDomain.r_bot_right_B(), oomph::QuarterTubeDomain.r_bot_right_D(), oomph::QuarterCircleSectorDomain.r_bot_right_E(), oomph::QuarterTubeDomain.r_bot_right_F(), oomph::QuarterTubeDomain.r_bot_right_R(), oomph::QuarterCircleSectorDomain.r_bot_right_S(), oomph::QuarterTubeDomain.r_bot_right_U(), oomph::QuarterCircleSectorDomain.r_bot_right_W(), oomph::QuarterTubeDomain.r_centr_B(), oomph::QuarterTubeDomain.r_centr_D(), oomph::QuarterTubeDomain.r_centr_F(), oomph::QuarterTubeDomain.r_centr_L(), oomph::QuarterTubeDomain.r_centr_R(), oomph::QuarterCircleSectorDomain.r_centr_S(), oomph::QuarterTubeDomain.r_centr_U(), oomph::QuarterCircleSectorDomain.r_centr_W(), oomph::QuarterPipeDomain.r_D(), oomph::CollapsibleChannelDomain.r_E_collapsible(), oomph::CollapsibleChannelDomain.r_E_straight(), oomph::QuarterPipeDomain.r_F(), oomph::QuarterPipeDomain.r_L(), oomph::CollapsibleChannelDomain.r_N_collapsible(), oomph::CollapsibleChannelDomain.r_N_straight(), oomph::QuarterPipeDomain.r_R(), oomph::CollapsibleChannelDomain.r_S_collapsible(), oomph::CollapsibleChannelDomain.r_S_straight(), oomph::QuarterTubeDomain.r_top_left_B(), oomph::QuarterCircleSectorDomain.r_top_left_E(), oomph::QuarterTubeDomain.r_top_left_F(), oomph::QuarterTubeDomain.r_top_left_L(), oomph::QuarterCircleSectorDomain.r_top_left_N(), oomph::QuarterCircleSectorDomain.r_top_left_S(), oomph::QuarterTubeDomain.r_top_left_U(), oomph::QuarterCircleSectorDomain.r_top_left_W(), oomph::QuarterPipeDomain.r_U(), oomph::FishDomain.r_upper_body_E(), oomph::FishDomain.r_upper_body_N(), oomph::FishDomain.r_upper_body_S(), oomph::FishDomain.r_upper_body_W(), oomph::FishDomain.r_upper_fin_N(), oomph::FishDomain.r_upper_fin_S(), oomph::FishDomain.r_upper_fin_W(), oomph::CollapsibleChannelDomain.r_W_collapsible(), oomph::CollapsibleChannelDomain.r_W_straight(), ramp(), Eigen::internal.RandomToTypeNormal(), Eigen::half_impl.raw_uint16_to_half(), real(), Eigen.real(), BrethertonElement< ELEMENT >.reassign_inflow(), oomph::VorticitySmoother< ELEMENT >.recover_vorticity(), CustomReducer< InT, OutT >.reduce(), REF_FREXP(), REF_LDEXP(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >.refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >.refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), RefineablePeriodicLoadProblem< ELEMENT >.RefineablePeriodicLoadProblem(), oomph::RefineableSolidCubicMesh< ELEMENT >.RefineableSolidCubicMesh(), MandelbrotThread.render(), oomph::DGFaceElement.report_info(), oomph::CRComplexMatrix.residual(), oomph::CCComplexMatrix.residual(), oomph::DenseComplexMatrix.residual(), resizeLikeTest(), oomph::HSL_MA42.resolve(), reverse(), ExactSolution.rigid_body_rotation(), ExactSolution.rigid_body_rotation_dr(), ExactSolution.rigid_body_rotation_dtheta(), SYCL.round(), Eigen::numext.rsqrt(), SYCL.rsqrt(), check_sqrt_impl< T >.run(), check_sqrt_impl< std::complex< T > >.run(), check_rsqrt_impl< T >.run(), check_rsqrt_impl< std::complex< T > >.run(), Eigen::internal::pardiso_run_selector< IndexType >.run(), Eigen::internal::pardiso_run_selector< long long int >.run(), typed_logicals_test_impl< ArrayType >.run(), Eigen::internal::random_impl< bfloat16 >.run(), Eigen::internal::random_impl< bool >.run(), Eigen::internal::isMuchSmallerThan_object_selector< Derived, OtherDerived, true >.run(), Eigen::internal::isApprox_selector< Derived, OtherDerived, true >.run(), Eigen::internal::isApprox_selector< Derived, OtherDerived, is_integer >.run(), Eigen::internal::isMuchSmallerThan_object_selector< Derived, OtherDerived, is_integer >.run(), Eigen::internal::isMuchSmallerThan_scalar_selector< Derived, true >.run(), Eigen::internal::isMuchSmallerThan_scalar_selector< Derived, is_integer >.run(), Eigen::internal::get_factor< From, To >.run(), Eigen::internal::random_impl< half >.run(), Eigen::internal::cast_impl< OldType, NewType, EnableIf >.run(), Eigen::internal::cast_impl< OldType, bool >.run(), Eigen::internal::cast_impl< OldType, NewType, typename std::enable_if_t<!NumTraits< OldType >::IsComplex &&NumTraits< NewType >::IsComplex > >.run(), Eigen::internal::generic_reciprocal_newton_step< Packet, Steps >.run(), Eigen::internal::patan_reduced< Scalar >.run(), Eigen::internal::unary_pow::reciprocate< Packet, ScalarExponent, false >.run(), Eigen::internal::unary_pow::reciprocate< Packet, ScalarExponent, ReciprocateIfExponentIsNegative >.run(), Eigen::internal::unary_pow_impl< Packet, ScalarExponent, false, false, ExponentIsSigned >.run(), Eigen::internal::unary_pow_impl< Packet, ScalarExponent, false, true, ExponentIsSigned >.run(), Eigen::internal::unary_pow_impl< Packet, ScalarExponent, true, true, true >.run(), Eigen::internal::unary_pow_impl< Packet, ScalarExponent, true, true, false >.run(), Eigen::internal::ppolevl< Packet, N >.run(), Eigen::internal::ppolevl< Packet, 0 >.run(), Eigen::internal::reverse_packet_cond< PacketType, ReversePacket >.run(), Eigen::internal::reverse_packet_cond< PacketType, false >.run(), Eigen::internal::cast_impl< Real, NewType >.run(), Eigen::internal::cast_impl< Real, std::complex< Real > >.run(), Eigen::internal::real_default_impl< Scalar, IsComplex >.run(), Eigen::internal::real_default_impl< Scalar, true >.run(), Eigen::internal::imag_default_impl< Scalar, true >.run(), Eigen::internal::conj_default_impl< Scalar, IsComplex >.run(), Eigen::internal::conj_default_impl< Scalar, true >.run(), Eigen::internal::abs2_impl_default< Scalar, IsComplex >.run(), Eigen::internal::abs2_impl_default< Scalar, true >.run(), Eigen::internal::abs2_impl< Scalar >.run(), Eigen::internal::sqrt_impl< Scalar >.run(), Eigen::internal::norm1_default_impl< Scalar, true >.run(), Eigen::internal::norm1_default_impl< Scalar, false >.run(), Eigen::internal::arg_default_impl< Scalar, true >.run(), Eigen::internal::arg_default_impl< Scalar, false >.run(), Eigen::internal::expm1_impl< Scalar >.run(), Eigen::internal::log_impl< Scalar >.run(), Eigen::internal::log1p_impl< Scalar >.run(), Eigen::numext::signbit_impl< Scalar, false, true >.run(), Eigen::numext::signbit_impl< Scalar, true, true >.run(), Eigen::internal::get_factor< Scalar, typename NumTraits< Scalar >::Real >.run(), Eigen::internal::hypot_impl< Scalar >.run(), Eigen::internal::random_int_impl< Scalar, false, true >.run(), Eigen::internal::random_int_impl< Scalar, true, true >.run(), Eigen::internal::random_default_impl< Scalar, false, false >.run(), Eigen::internal::random_default_impl< Scalar, true, false >.run(), Eigen::internal::pow_impl< ScalarX, ScalarY, IsInteger >.run(), Eigen::internal::log1p_impl< std::complex< RealScalar > >.run(), Eigen::internal::expm1_impl< std::complex< RealScalar > >.run(), Eigen::internal::sqrt_impl< std::complex< T > >.run(), Eigen::internal::rsqrt_impl< std::complex< T > >.run(), Eigen::internal::rsqrt_impl< T >.run(), Eigen::internal::generic_i0e< T, float >.run(), Eigen::internal::generic_i0e< T, double >.run(), Eigen::internal::generic_i0< T, ScalarType >.run(), Eigen::internal::generic_i1e< T, float >.run(), Eigen::internal::generic_i1e< T, double >.run(), Eigen::internal::generic_i1< T, ScalarType >.run(), Eigen::internal::generic_k0e< T, float >.run(), Eigen::internal::generic_k0e< T, double >.run(), Eigen::internal::generic_k0< T, float >.run(), Eigen::internal::generic_k0< T, double >.run(), Eigen::internal::generic_k1e< T, float >.run(), Eigen::internal::generic_k1e< T, double >.run(), Eigen::internal::generic_k1< T, float >.run(), Eigen::internal::generic_k1< T, double >.run(), Eigen::internal::generic_j0< T, float >.run(), Eigen::internal::generic_j0< T, double >.run(), Eigen::internal::generic_y0< T, float >.run(), Eigen::internal::generic_y0< T, double >.run(), Eigen::internal::generic_j1< T, float >.run(), Eigen::internal::generic_j1< T, double >.run(), Eigen::internal::generic_y1< T, float >.run(), Eigen::internal::generic_y1< T, double >.run(), Eigen::internal::bessel_i0e_impl< T >.run(), Eigen::internal::bessel_i0_impl< T >.run(), Eigen::internal::bessel_i1e_impl< T >.run(), Eigen::internal::bessel_i1_impl< T >.run(), Eigen::internal::bessel_k0e_impl< T >.run(), Eigen::internal::bessel_k0_impl< T >.run(), Eigen::internal::bessel_k1e_impl< T >.run(), Eigen::internal::bessel_k1_impl< T >.run(), Eigen::internal::bessel_j0_impl< T >.run(), Eigen::internal::bessel_y0_impl< T >.run(), Eigen::internal::bessel_j1_impl< T >.run(), Eigen::internal::bessel_y1_impl< T >.run(), Eigen::internal::take_matrix_for_product< Transform< Scalar, Dim, Mode, Options > >.run(), Eigen::internal::take_matrix_for_product< Transform< Scalar, Dim, Projective, Options > >.run(), Eigen::internal::take_matrix_for_product< MatrixOrTransformType >.run(), Eigen::numext::equal_strict_impl< X, Y, XIsInteger, XIsSigned, YIsInteger, YIsSigned >.run(), Eigen::numext::equal_strict_impl< X, Y, true, true, true, false >.run(), Eigen::internal::maybe_raise_div_by_zero< Packet, IsInteger >.run(), Eigen::internal::maybe_raise_div_by_zero< Packet, true >.run(), Eigen::internal::pchebevl< Packet, N >.run(), Eigen::internal::real_ref_impl< Scalar >.run(), Eigen::internal::imag_ref_default_impl< Scalar, IsComplex >.run(), exp_complex_test_impl< Scalar, Packet, HasExp >.run(), Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, Vectorizable >.run(), Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, true >.run(), Eigen::internal::pow_impl< ScalarX, ScalarY, true >.run(), Eigen::internal::nearest_integer_packetop_impl< Packet, false, false >.run_ceil(), Eigen::internal::nearest_integer_packetop_impl< Packet, false, true >.run_ceil(), Eigen::internal::nearest_integer_packetop_impl< Packet, IsScalar, IsInteger >.run_ceil(), Eigen::internal::nearest_integer_packetop_impl< Packet, false, false >.run_floor(), Eigen::internal::nearest_integer_packetop_impl< Packet, false, true >.run_floor(), Eigen::internal::nearest_integer_packetop_impl< Packet, IsScalar, IsInteger >.run_floor(), run_navier_stokes_outflow(), Eigen::internal::nearest_integer_packetop_impl< Packet, false, false >.run_rint(), Eigen::internal::nearest_integer_packetop_impl< Packet, false, true >.run_rint(), Eigen::internal::nearest_integer_packetop_impl< Packet, IsScalar, IsInteger >.run_rint(), Eigen::internal::nearest_integer_packetop_impl< Packet, false, false >.run_round(), Eigen::internal::nearest_integer_packetop_impl< Packet, false, true >.run_round(), Eigen::internal::nearest_integer_packetop_impl< Packet, IsScalar, IsInteger >.run_round(), Eigen::internal::nearest_integer_packetop_impl< Packet, false, false >.run_trunc(), Eigen::internal::nearest_integer_packetop_impl< Packet, false, true >.run_trunc(), Eigen::internal::nearest_integer_packetop_impl< Packet, IsScalar, IsInteger >.run_trunc(), saveAsBitmap(), ClosedCSCWalls.saveWalls(), CSCWalls.saveWalls(), scal(), TanhSolnForMultiPoisson.scalar_soln(), TanhSolnForMultiPoisson.scalar_source(), typed_logicals_test_impl< ArrayType >.scalar_to_bool(), oomph::PMLHelmholtzEquations< DIM >.scalar_value_fct_paraview(), oomph::PoissonEquations< DIM >.scalar_value_fct_paraview(), oomph::AdvectionDiffusionEquations< DIM >.scalar_value_paraview(), oomph::AxisymAdvectionDiffusionEquations.scalar_value_paraview(), ScaleCoupledBeam.ScaleCoupledBeam(), oomph::CircularCylindricalShellMesh< ELEMENT >.scaled_x(), sdot(), PerturbationSolution.second_order_perturbation_for_plot(), AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >.set_boundary_conditions(), FlowAroundCylinderProblem< ELEMENT >.set_boundary_conditions(), RefineableRotatingCylinderProblem< ELEMENT >.set_boundary_conditions(), RefineableSphericalCouetteProblem< ELEMENT >.set_boundary_conditions(), RefineableSphericalSpinUpProblem< ELEMENT >.set_boundary_conditions(), SphericalSpinUpProblem< ELEMENT >.set_boundary_conditions(), ConvectionProblem< NST_ELEMENT, AD_ELEMENT >.set_boundary_conditions(), DDConvectionProblem< NST_ELEMENT, AD_ELEMENT >.set_boundary_conditions(), RefineableDDConvectionProblem< NST_ELEMENT, AD_ELEMENT >.set_boundary_conditions(), AxiPoroProblem< ELEMENT, TIMESTEPPER >.set_boundary_values(), Funnel.set_funO(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >.set_initial_condition(), UnsteadyHeatProblem< ELEMENT >.set_initial_condition(), FSICollapsibleChannelProblem< ELEMENT >.set_initial_condition(), FSIDrivenCavityProblem< ELEMENT >.set_initial_condition(), OscRingNStProblem< ELEMENT >.set_initial_condition(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >.set_initial_condition(), LinearWaveProblem< ELEMENT, TIMESTEPPER >.set_initial_condition(), RefineableUnsteadyHeatProblem< ELEMENT >.set_initial_condition(), CollapsibleChannelProblem< ELEMENT >.set_initial_condition(), OscEllipseProblem< ELEMENT, TIMESTEPPER >.set_initial_condition(), RayleighProblem< ELEMENT, TIMESTEPPER >.set_initial_condition(), RayleighTractionProblem< ELEMENT, TIMESTEPPER >.set_initial_condition(), RefineableOneDAdvectionDiffusionReactionProblem< ELEMENT >.set_initial_condition(), RefineableActivatorInhibitorProblem< ELEMENT >.set_initial_condition(), AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >.set_initial_conditions(), AdvectionProblem.set_initial_conditions(), CollapsibleChannelProblem< ELEMENT >.set_poiseuille_outflow(), SetBenchmarkFlopsProcessed(), BaseParticle.setHGridX(), ConsistencyInitialParticleWallOverlapUnitTest.setInitPos0(), ConsistencyInitialParticleWallOverlapUnitTest.setInitPos1(), setinnerrand_eigen(), setrand_eigen_compact(), setrand_eigen_dynamic(), setrand_eigen_gnu_hash(), setrand_eigen_google_dense(), setrand_eigen_google_sparse(), setrand_eigen_sumeq(), setrand_scipy(), setrand_ublas_genvec(), setrand_ublas_mapped(), CGCoordinates::RZ.setRZ(), oomph::InnerIterationPreconditioner< SOLVER, PRECONDITIONER >.setup(), oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >.setup_algebraic_node_update(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >.setup_algebraic_node_update(), oomph::AlgebraicCollapsibleChannelMesh< ELEMENT >.setup_algebraic_node_update(), oomph::AlgebraicFSIDrivenCavityMesh< ELEMENT >.setup_algebraic_node_update(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >.setup_algebraic_node_update(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >.setup_algebraic_node_update(), oomph::Multi_domain_functions.setup_bulk_elements_adjacent_to_face_mesh(), MortaringHelpers.setup_constraint_elements_at_nodes(), oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >.setup_gamma(), oomph::HelmholtzDtNMesh< ELEMENT >.setup_gamma(), CFDDEMCoupleTest.setupInitialConditions(), Binary.setupInitialConditions(), my_problem.setupInitialConditions(), FreeCooling2DinWallsDemo.setupInitialConditions(), FreeCooling3DDemoProblem.setupInitialConditions(), FreeCooling3DinWallsDemo.setupInitialConditions(), FreeCoolingDemoProblem.setupInitialConditions(), HeaterBoundaryTest.setupInitialConditions(), HourGlass2D.setupInitialConditions(), InitialBed.setupInitialConditions(), my_problem_HGRID.setupInitialConditions(), GetDistanceAndNormalForTriangleWalls.setupInitialConditions(), RollingOverTriangleWalls.setupInitialConditions(), TriangulatedStepWallSelfTest.setupInitialConditions(), RotatingDrum.setupInitialConditions(), CoupledProblem.setupMercury(), CGCoordinates::X.setX(), CGCoordinates::XY.setXY(), CGCoordinates::XZ.setXZ(), oomph::Z2ErrorEstimator.shape_rec(), oomph::VorticitySmoother< ELEMENT >.shape_rec(), SheetGlueProblem< ELEMENT >.SheetGlueProblem(), ShellProblem< ELEMENT >.ShellProblem(), SYCL.sign(), Eigen::numext.signbit(), signbit_test(), sin(), Eigen::numext.sin(), mathsFunc.sin(), GlobalParameters.sin_cos_velocity_field(), GlobalParameters.sin_cos_vorticity(), sin_over_x(), PoissonElementWithSingularity< BASIC_POISSON_ELEMENT >.singular_function(), SingularPoissonSolutionElement< WRAPPED_POISSON_ELEMENT >.singular_function(), Eigen::numext.sinh(), oomph::SlopingQuadMesh< ELEMENT >.SlopingQuadMesh(), oomph::TetMeshBase.snap_nodes_onto_geometric_objects(), FallingBlockProblem< ELEMENT >.snap_onto_sphere(), RisingBubbleProblem< ELEMENT >.snap_onto_sphere(), oomph::TetMeshBase.snap_to_quadratic_surface(), ProblemParameters.Solid_body_force(), oomph::AxisymmetricPoroelasticityEquations.solid_body_force(), Global_Parameters.solid_boundary_displacement(), BiharmonicTestFunctions1.solution(), BiharmonicTestFunctions2.solution(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >.solve(), oomph::ARPACK.solve_eigenproblem(), oomph::CG< MATRIX >.solve_helper(), oomph::BiCGStab< MATRIX >.solve_helper(), oomph::GS< MATRIX >.solve_helper(), oomph::GS< CRDoubleMatrix >.solve_helper(), oomph::DampedJacobi< MATRIX >.solve_helper(), solve_with_guess(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >.solveInit(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >.solveNumericalDiff(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >.solveNumericalDiffInit(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >.solveNumericalDiffOneStep(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >.solveOneStep(), oomph::DarcyEquations< DIM >.source(), TestProblem.source(), Global_parameters.source_function(), FishSolnOneDPoisson.source_function(), TanhSolnForPoisson.source_function(), SolnForPoisson.source_function(), TanhSolnForMultiPoisson.source_function(), oomph::PressureAdvectionDiffusionValidation.source_function(), TanhSolnForAdvectionDiffusion.source_function(), sparse_basic(), sparse_extra(), sparse_product(), Eigen::internal.sparse_sparse_product_with_pruning_impl(), Eigen::internal.sparse_sparse_to_dense_product_impl(), special_value_pairs(), GlobalParameters.spine_base_function(), GlobalParameters.spine_function(), Global_Physical_Variables.spring_load(), Global_Physical_Variables.spring_load_lower(), SQR(), sqrt(), SYCL.sqrt(), Eigen::numext.sqrt< bool >(), SYCL.square(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >.square_of_l2_norm_of_error(), StefanBoltzmannProblem< ELEMENT >.StefanBoltzmannProblem(), Eigen::internal.stem_function_cos(), Eigen::internal.stem_function_cosh(), Eigen::internal.stem_function_exp(), Eigen::internal.stem_function_sin(), Eigen::internal.stem_function_sinh(), Eigen::RealQZ< MatrixType_ >.step(), Eigen::test::packet_helper< Cond, Packet >.store(), Eigen::test::packet_helper< false, Packet >.store(), Eigen::internal.storeResults(), oomph::Refineable_r_mesh< ELEMENT >.stretch_mesh(), oomph::CircularPenetrator.surface_coordinate(), HeatedCircularPenetratorElement.surface_coordinate(), BiharmonicTestFunctions1.surface_load(), BiharmonicTestFunctions2.surface_load(), svd_least_square(), swap(), Global_Physical_Variables.swimming(), RefineablePorousChannelProblem< ELEMENT >.symmetrise_eigenfunction_for_adaptive_pitchfork_tracking(), GlobalParameters.synthetic_velocity_field(), GlobalParameters.synthetic_vorticity(), Eigen::numext.tan(), mathsFunc.tan(), Eigen::numext.tanh(), SYCL.tanh(), TanhSolnForAdvectionDiffusion.tanh_profile(), oomph::HeatedCircularPenetrator.temperature(), HeatedCircularPenetratorElement.temperature(), Eigen::internal::TensorUInt128< HIGH, LOW >.TensorUInt128(), terminatetetgen(), test_accelerate_ldlt(), test_accelerate_llt(), test_accelerate_qr(), test_aliasing(), test_arithmetic(), test_autodiff_hessian(), test_central(), test_cwise_complex(), test_cwise_real(), test_denseLM_T(), test_entire_volume_patch(), test_entire_volume_patch_sycl(), test_exponent(), test_forward(), test_move(), test_mutable_unaryview(), test_nnls_handles_0x0_matrix(), test_nnls_handles_dependent_columns(), test_nnls_handles_Mx0_matrix(), test_nnls_handles_wide_matrix(), test_nnls_handles_zero_rhs(), test_nnls_known_1(), test_nnls_known_2(), test_nnls_known_3(), test_nnls_known_4(), test_nnls_known_5(), test_nnls_known_solution(), test_nnls_random_problem(), test_nnls_repeated_calls_to_compute_and_solve(), test_nnls_returns_NoConvergence_when_maxIterations_is_too_low(), test_nnls_special_case_solves_in_n_iterations(), test_nnls_with_half_precision(), test_random_setter(), test_simple_patch(), test_simple_patch_sycl(), test_sparseLM_T(), test_sparseqr_scalar(), test_spqr_scalar(), test_stl_iterators(), test_unaryview_solve(), testChkder(), testGeneral(), testHybrd(), testHybrd1(), testHybrj(), testHybrj1(), testLmder(), testLmder1(), testLmdif(), testLmdif1(), testLmstr(), testLmstr1(), testLogThenExp(), testNistBennett5(), testNistBoxBOD(), testNistChwirut2(), testNistEckerle4(), testNistHahn1(), testNistLanczos1(), testNistMGH09(), testNistMGH10(), testNistMGH17(), testNistMisra1a(), testNistMisra1d(), testNistRat42(), testNistRat43(), testNistThurber(), TFaceTestProblem< ELEMENT >.TFaceTestProblem(), oomph::ThinLayerBrickOnTetMesh< ELEMENT >.ThinLayerBrickOnTetMesh(), Eigen::QuaternionBase< Derived >.toRotationMatrix(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >.traction(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >.traction(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >.traction(), oomph::LinearElasticityTractionElement< ELEMENT >.traction(), oomph::PoroelasticityFaceElement< ELEMENT >.traction(), oomph::SolidTractionElement< ELEMENT >.traction(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >.traction(), oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElement< ELEMENT >.traction(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >.traction(), oomph::TemplateFreeContactElementBase.traction_fct(), TriangleFaceTestProblem< ELEMENT >.TriangleFaceTestProblem(), Eigen::internal.tridiagonal_qr_step(), Eigen::internal.trig_reduce_medium_double(), Eigen::internal.trig_reduce_small_double(), oomph::TubeMesh< ELEMENT >.TubeMesh(), TwoDDGProblem< ELEMENT >.TwoDDGProblem(), Eigen::internal.twoprod(), Eigen::internal.twoprod_low(), oomph::NavierStokesElementWithSingularity< BASIC_NAVIER_STOKES_ELEMENT >.u_bar(), PoissonElementWithSingularity< BASIC_POISSON_ELEMENT >.u_bar(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >.u_bar(), SingularPoissonSolutionElement< WRAPPED_POISSON_ELEMENT >.u_bar(), BiharmonicTestFunctions1.u_NE(), Global_Parameters.u_r(), Global_Parameters.u_theta(), Global_Parameters.u_z(), Eigen::internal::llt_inplace< Scalar, Lower >.unblocked(), oomph::GMRESBlockPreconditioner.update(), oomph::GMRES< MATRIX >.update(), oomph::AugmentedProblemGMRES.update(), oomph::ComplexGMRES< MATRIX >.update(), oomph::HelmholtzGMRESMG< MATRIX >.update(), oomph::HelmholtzFGMRESMG< MATRIX >.update(), oomph::SolarRadiationBase.update_limiting_angles(), SimpleSpineMesh< ELEMENT >.update_spine_heights(), ScaleCoupling< M, O >.updateCoupledElements(), SCoupling< M, O >.updateDPMWallsFromFiniteElems(), Global_Physical_Variables.validation_fluid_fsi_boundary_traction(), Global_Parameters.velocity_couette(), Global_Parameters.velocity_pseudo_singularity_for_couette(), oomph::NavierStokesElementWithSingularity< BASIC_NAVIER_STOKES_ELEMENT >.velocity_singular_function(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >.velocity_singular_function(), Global_Parameters.velocity_singularity1(), Global_Parameters.velocity_singularity2(), Eigen::internal.veltkamp_splitting(), verify_component_wise(), verify_nnls_optimality(), oomph::VorticitySmootherElement< ELEMENT >.vorticity_error_squared(), oomph::KirchhoffLoveBeamEquations.wall_profile(), oomph::FluidInterfaceBoundingElement.wall_unit_normal(), oomph::WarpedCubeDomain.warp_it(), TanhSolnForAdvectionDiffusion.wind_function(), GlobalPhysicalParameters.wind_function(), RachelsAdvectionDiffusion.wind_function(), Global_Physical_Variables.wind_function(), TanhSolnForSteadyAxisymAdvectionDiffusion.wind_function(), oomph::PressureAdvectionDiffusionValidation.wind_function(), Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >.writePacket(), Eigen::TensorEvaluator< TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >.writePacket(), Eigen::TensorEvaluator< Derived, Device >.writePacket(), Eigen::TensorEvaluator< TensorLayoutSwapOp< ArgType >, Device >.writePacket(), Eigen::TensorEvaluator< TensorReshapingOp< NewDimensions, ArgType >, Device >.writePacket(), Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >.writePacket(), Eigen::TensorEvaluator< TensorReverseOp< ReverseDimensions, ArgType >, Device >.writePacket(), Eigen::TensorEvaluator< TensorRollOp< RollDimensions, ArgType >, Device >.writePacket(), Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >.writePacket(), Eigen::TensorEvaluator< TensorStridingOp< Strides, ArgType >, Device >.writePacket(), Eigen::ForceAlignedAccess< ExpressionType >.writePacket(), Eigen::internal::evaluator< PlainObjectBase< Derived > >.writePacket(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >.writePacket(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >.writePacket(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >.writePacket(), Eigen::internal::evaluator_wrapper_base< XprType >.writePacket(), Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >.writePacket(), SolidProblem< ELEMENT_TYPE >.writeToVTK(), Eigen.zeta(), oomph::RefineableSolidCubicMesh< ELEMENT >.zeta_linear(), oomph::HeatedLinearSurfaceContactElement< ELEMENT >.zeta_nodal(), and oomph::HeatedPenetratorFluxElement< ELEMENT >.zeta_nodal().