MercuryDPM: ParallelUnitTestMPI.cpp File Reference
ParallelUnitTestMPI.cpp File Reference
#include "Mercury3D.h"
#include <iostream>
#include "Species/LinearViscoelasticFrictionSpecies.h"
#include <cstdlib>
Classes
class MpiPeriodicBoundaryUnitTest
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
 {
     //Create the problem
     MpiPeriodicBoundaryUnitTest problem;
     problem.setName("ParallelUnitTestMPI");
     //Create a species
     LinearViscoelasticFrictionSpecies* species = problem.speciesHandler.copyAndAddObject(LinearViscoelasticFrictionSpecies());
     species->setDensity(1.0);
     //Set domain accordingly (domain boundaries are not walls!)
     problem.setXMin(-10.0);
     problem.setXMax(10.0);
     problem.setYMin(-10.0);
     problem.setYMax(10.0);
     problem.setZMin(-10.0);
     problem.setZMax(10.0);
     //specify particle properties
     species->setDensity(6.0/constants::pi);
     //specify body forces
     problem.setGravity(Vec3D(0.0, 0.0, 0.0));
     //Set the number of domains for parallel decomposition
     problem.setNumberOfDomains({2,2,2});
     //specify contact properties
     //normal forces
     species->setStiffness(1e5);
     species->setDissipation(0.63);
     //tangential (sliding) forces
     species->setSlidingFrictionCoefficient(0.5);
     species->setSlidingStiffness(1.2e4);
     species->setSlidingDissipation(0.16);
     //tangential (rolling) torques
     species->setRollingFrictionCoefficient(0.2);
     species->setRollingStiffness(1.2e4);
     species->setRollingDissipation(6.3e-2);
     //normal (torsion/spin) torques
     species->setTorsionFrictionCoefficient(0.1);
     species->setTorsionStiffness(1.2e4);
     species->setSlidingDissipation(6.3e-2);
     //set other simulation parameters
     //Mdouble MinParticleMass = species->getDensity()*4.0 / 3.0 * constants::pi ;
     //Mdouble tc = species->getCollisionTime(MinParticleMass);
     problem.setTimeStep(0.1);
     problem.setTimeMax(60.0);//run until 3.0 to see full simulation
     problem.setSaveCount(1); //used to be 500
     //Set output to paraview
     problem.setParticlesWriteVTK(true);
     problem.solve(argc, argv);
     return 0;
 }
References constants::pi, problem, ParticleSpecies::setDensity(), LinearViscoelasticNormalSpecies::setDissipation(), FrictionSpecies::setRollingDissipation(), FrictionSpecies::setRollingFrictionCoefficient(), FrictionSpecies::setRollingStiffness(), SlidingFrictionSpecies::setSlidingDissipation(), SlidingFrictionSpecies::setSlidingFrictionCoefficient(), SlidingFrictionSpecies::setSlidingStiffness(), LinearViscoelasticNormalSpecies::setStiffness(), FrictionSpecies::setTorsionFrictionCoefficient(), and FrictionSpecies::setTorsionStiffness().