MercuryDPM: Eigen::TensorRef< PlainObjectType > Class Template Reference
Eigen::TensorRef< PlainObjectType > Class Template Reference
A reference to a tensor expression The expression will be evaluated lazily (as much as possible).
#include <TensorRef.h>
Public Types
enum {
IsAligned = false , PacketAccess = false , BlockAccess = false , PreferBlockAccess = false ,
CoordAccess = false , RawAccess = false
}
typedef TensorRef< PlainObjectType > Self
typedef PlainObjectType::Base Base
typedef Eigen::internal::nested< Self >::type Nested
typedef internal::traits< PlainObjectType >::StorageKind StorageKind
typedef internal::traits< PlainObjectType >::Index Index
typedef internal::traits< PlainObjectType >::Scalar Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef Base::CoeffReturnType CoeffReturnType
typedef Scalar * PointerType
typedef PointerType PointerArgType
typedef PlainObjectType::Dimensions Dimensions
typedef internal::TensorBlockNotImplemented TensorBlock
Public Types inherited from Eigen::TensorBase< TensorRef< PlainObjectType > >
typedef TensorBase< TensorRef< PlainObjectType >, ReadOnlyAccessors > Base
typedef internal::traits< TensorRef< PlainObjectType > > DerivedTraits
typedef DerivedTraits::Scalar Scalar
typedef DerivedTraits::Index Index
typedef Scalar CoeffReturnType
Public Member Functions
EIGEN_STRONG_INLINE TensorRef ()
template<typename Expression >
EIGEN_STRONG_INLINE TensorRef (const Expression &expr)
template<typename Expression >
EIGEN_STRONG_INLINE TensorRef & operator= (const Expression &expr)
~TensorRef ()
TensorRef (const TensorRef &other)
TensorRef & operator= (const TensorRef &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rank () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index dimension (Index n) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index size () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar * data () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar operator() (Index index) const
template<typename... IndexTypes>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar operator() (Index firstIndex, IndexTypes... otherIndices) const
template<typename... IndexTypes>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index firstIndex, IndexTypes... otherIndices)
template<std::size_t NumIndices>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar coeff (const array< Index, NumIndices > &indices) const
template<std::size_t NumIndices>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (const array< Index, NumIndices > &indices)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
Public Member Functions inherited from Eigen::TensorBase< TensorRef< PlainObjectType > >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorRef< PlainObjectType > & setZero ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorRef< PlainObjectType > & setConstant (const Scalar &val)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorRef< PlainObjectType > & setRandom ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorRef< PlainObjectType > & setRandom ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorRef< PlainObjectType > & setValues (const typename internal::Initializer< TensorRef< PlainObjectType >, NumDimensions >::InitList &vals)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorRef< PlainObjectType > & operator+= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorRef< PlainObjectType > & operator-= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorRef< PlainObjectType > & operator*= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorRef< PlainObjectType > & operator/= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorLayoutSwapOp< const TensorRef< PlainObjectType > > swap_layout () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorLayoutSwapOp< TensorRef< PlainObjectType > > swap_layout ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorConcatenationOp< const Axis, const TensorRef< PlainObjectType >, const OtherDerived > concatenate (const OtherDerived &other, const Axis &axis) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorConcatenationOp< const Axis, TensorRef< PlainObjectType >, OtherDerived > concatenate (const OtherDerived &other, const Axis &axis)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReshapingOp< const NewDimensions, const TensorRef< PlainObjectType > > reshape (const NewDimensions &newDimensions) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorReshapingOp< const NewDimensions, TensorRef< PlainObjectType > > reshape (const NewDimensions &newDimensions)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorSlicingOp< const StartIndices, const Sizes, const TensorRef< PlainObjectType > > slice (const StartIndices &startIndices, const Sizes &sizes) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorSlicingOp< const StartIndices, const Sizes, TensorRef< PlainObjectType > > slice (const StartIndices &startIndices, const Sizes &sizes)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorStridingSlicingOp< const StartIndices, const StopIndices, const Strides, const TensorRef< PlainObjectType > > stridedSlice (const StartIndices &startIndices, const StopIndices &stopIndices, const Strides &strides) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingSlicingOp< const StartIndices, const StopIndices, const Strides, TensorRef< PlainObjectType > > stridedSlice (const StartIndices &startIndices, const StopIndices &stopIndices, const Strides &strides)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorChippingOp< DimId, const TensorRef< PlainObjectType > > chip (const Index offset) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorChippingOp< DimId, TensorRef< PlainObjectType > > chip (const Index offset)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorChippingOp< Dynamic, const TensorRef< PlainObjectType > > chip (const Index offset, const Index dim) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorChippingOp< Dynamic, TensorRef< PlainObjectType > > chip (const Index offset, const Index dim)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReverseOp< const ReverseDimensions, const TensorRef< PlainObjectType > > reverse (const ReverseDimensions &rev) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorReverseOp< const ReverseDimensions, TensorRef< PlainObjectType > > reverse (const ReverseDimensions &rev)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorRollOp< const Rolls, const TensorRef< PlainObjectType > > roll (const Rolls &roll) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorRollOp< const Rolls, TensorRef< PlainObjectType > > roll (const Rolls &roll)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorShufflingOp< const Shuffle, const TensorRef< PlainObjectType > > shuffle (const Shuffle &shfl) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorShufflingOp< const Shuffle, TensorRef< PlainObjectType > > shuffle (const Shuffle &shfl)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorStridingOp< const Strides, const TensorRef< PlainObjectType > > stride (const Strides &strides) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingOp< const Strides, TensorRef< PlainObjectType > > stride (const Strides &strides)
TensorDevice< TensorRef< PlainObjectType >, DeviceType > device (const DeviceType &dev)
TensorAsyncDevice< TensorRef< PlainObjectType >, DeviceType, DoneCallback > device (const DeviceType &dev, DoneCallback done)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorRef< PlainObjectType > & derived ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorRef< PlainObjectType > & derived () const
Static Public Attributes
static constexpr Index NumIndices = PlainObjectType::NumIndices
static constexpr int Layout = PlainObjectType::Layout
Static Public Attributes inherited from Eigen::TensorBase< TensorRef< PlainObjectType > >
static constexpr int NumDimensions
Private Member Functions
EIGEN_STRONG_INLINE void unrefEvaluator ()
Private Attributes
internal::TensorLazyBaseEvaluator< Dimensions, Scalar > * m_evaluator
Additional Inherited Members
Protected Member Functions inherited from Eigen::TensorBase< TensorRef< PlainObjectType > >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorRef< PlainObjectType > & operator= (const OtherDerived &other)
Detailed Description
template<typename PlainObjectType>
class Eigen::TensorRef< PlainObjectType >
A reference to a tensor expression The expression will be evaluated lazily (as much as possible).
Member Typedef Documentation
Base
template<typename PlainObjectType > typedef PlainObjectType::Base Eigen::TensorRef< PlainObjectType >::Base
CoeffReturnType
template<typename PlainObjectType > typedef Base::CoeffReturnType Eigen::TensorRef< PlainObjectType >::CoeffReturnType
Dimensions
template<typename PlainObjectType > typedef PlainObjectType::Dimensions Eigen::TensorRef< PlainObjectType >::Dimensions
Index
template<typename PlainObjectType > typedef internal::traits<PlainObjectType>::Index Eigen::TensorRef< PlainObjectType >::Index
Nested
template<typename PlainObjectType > typedef Eigen::internal::nested<Self>::type Eigen::TensorRef< PlainObjectType >::Nested
PointerArgType
template<typename PlainObjectType > typedef PointerType Eigen::TensorRef< PlainObjectType >::PointerArgType
PointerType
template<typename PlainObjectType > typedef Scalar* Eigen::TensorRef< PlainObjectType >::PointerType
RealScalar
template<typename PlainObjectType > typedef NumTraits<Scalar>::Real Eigen::TensorRef< PlainObjectType >::RealScalar
Scalar
template<typename PlainObjectType > typedef internal::traits<PlainObjectType>::Scalar Eigen::TensorRef< PlainObjectType >::Scalar
Self
template<typename PlainObjectType > typedef TensorRef<PlainObjectType> Eigen::TensorRef< PlainObjectType >::Self
StorageKind
template<typename PlainObjectType > typedef internal::traits<PlainObjectType>::StorageKind Eigen::TensorRef< PlainObjectType >::StorageKind
TensorBlock
template<typename PlainObjectType > typedef internal::TensorBlockNotImplemented Eigen::TensorRef< PlainObjectType >::TensorBlock
Member Enumeration Documentation
anonymous enum
template<typename PlainObjectType > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = false,
     PacketAccess = false,
     BlockAccess = false,
     PreferBlockAccess = false,
     CoordAccess = false,  // to be implemented
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorRef() [1/3]
template<typename PlainObjectType > EIGEN_STRONG_INLINE Eigen::TensorRef< PlainObjectType >::TensorRef () inline
 : m_evaluator(NULL) {}
TensorRef() [2/3]
template<typename PlainObjectType > template<typename Expression > EIGEN_STRONG_INLINE Eigen::TensorRef< PlainObjectType >::TensorRef (const Expression & expr) inline
       : m_evaluator(new internal::TensorLazyEvaluator<Dimensions, Expression, DefaultDevice>(expr, DefaultDevice())) {
     m_evaluator->incrRefCount();
   }
References Eigen::TensorRef< PlainObjectType >::m_evaluator.
~TensorRef()
template<typename PlainObjectType > Eigen::TensorRef< PlainObjectType >::~TensorRef () inline
 { unrefEvaluator(); }
References Eigen::TensorRef< PlainObjectType >::unrefEvaluator().
TensorRef() [3/3]
template<typename PlainObjectType > Eigen::TensorRef< PlainObjectType >::TensorRef (const TensorRef< PlainObjectType > & other) inline
                                     : TensorBase<TensorRef<PlainObjectType> >(other), m_evaluator(other.m_evaluator) {
     eigen_assert(m_evaluator->refCount() > 0);
     m_evaluator->incrRefCount();
   }
References eigen_assert, and Eigen::TensorRef< PlainObjectType >::m_evaluator.
Member Function Documentation
coeff() [1/2]
template<typename PlainObjectType > template<std::size_t NumIndices> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar Eigen::TensorRef< PlainObjectType >::coeff (const array< Index, NumIndices > & indices) const inline
{
     const Dimensions& dims = this->dimensions();
     Index index = 0;
     if (PlainObjectType::Options & RowMajor) {
       index += indices[0];
       for (size_t i = 1; i < NumIndices; ++i) {
         index = index * dims[i] + indices[i];
       }
     } else {
       index += indices[NumIndices - 1];
       for (int i = NumIndices - 2; i >= 0; --i) {
         index = index * dims[i] + indices[i];
       }
     }
     return m_evaluator->coeff(index);
   }
References Eigen::TensorRef< PlainObjectType >::dimensions(), i, Eigen::TensorRef< PlainObjectType >::m_evaluator, Eigen::TensorRef< PlainObjectType >::NumIndices, and Eigen::RowMajor.
Referenced by Eigen::TensorRef< PlainObjectType >::operator()().
coeff() [2/2]
template<typename PlainObjectType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar Eigen::TensorRef< PlainObjectType >::coeff (Index index) const inline
 { return m_evaluator->coeff(index); }
References Eigen::TensorRef< PlainObjectType >::m_evaluator.
coeffRef() [1/3]
template<typename PlainObjectType > template<std::size_t NumIndices> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::TensorRef< PlainObjectType >::coeffRef (const array< Index, NumIndices > & indices) inline
{
     const Dimensions& dims = this->dimensions();
     Index index = 0;
     if (PlainObjectType::Options & RowMajor) {
       index += indices[0];
       for (size_t i = 1; i < NumIndices; ++i) {
         index = index * dims[i] + indices[i];
       }
     } else {
       index += indices[NumIndices - 1];
       for (int i = NumIndices - 2; i >= 0; --i) {
         index = index * dims[i] + indices[i];
       }
     }
     return m_evaluator->coeffRef(index);
   }
References Eigen::TensorRef< PlainObjectType >::dimensions(), i, Eigen::TensorRef< PlainObjectType >::m_evaluator, Eigen::TensorRef< PlainObjectType >::NumIndices, and Eigen::RowMajor.
coeffRef() [2/3]
template<typename PlainObjectType > template<typename... IndexTypes> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::TensorRef< PlainObjectType >::coeffRef (Index firstIndex, IndexTypes... otherIndices) inline
{
     const std::size_t num_indices = (sizeof...(otherIndices) + 1);
     const array<Index, num_indices> indices{{firstIndex, otherIndices...}};
     return coeffRef(indices);
   }
Referenced by test_coeff_ref(), and test_simple_lvalue_ref().
coeffRef() [3/3]
template<typename PlainObjectType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::TensorRef< PlainObjectType >::coeffRef (Index index) inline
 { return m_evaluator->coeffRef(index); }
References Eigen::TensorRef< PlainObjectType >::m_evaluator.
data()
template<typename PlainObjectType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar* Eigen::TensorRef< PlainObjectType >::data () const inline
 { return m_evaluator->data(); }
References Eigen::TensorRef< PlainObjectType >::m_evaluator.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), test_multiple_dims(), test_ref_of_ref(), test_simple_lvalue_ref(), test_simple_rvalue_ref(), test_slice(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimension()
template<typename PlainObjectType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorRef< PlainObjectType >::dimension (Index n) const inline
 { return m_evaluator->dimensions()[n]; }
References Eigen::TensorRef< PlainObjectType >::m_evaluator, and n.
Referenced by test_multiple_dims(), and test_ref_of_ref().
dimensions()
template<typename PlainObjectType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorRef< PlainObjectType >::dimensions () const inline
 { return m_evaluator->dimensions(); }
References Eigen::TensorRef< PlainObjectType >::m_evaluator.
Referenced by Eigen::TensorRef< PlainObjectType >::coeff(), and Eigen::TensorRef< PlainObjectType >::coeffRef().
operator()() [1/2]
template<typename PlainObjectType > template<typename... IndexTypes> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar Eigen::TensorRef< PlainObjectType >::operator() (Index firstIndex, IndexTypes... otherIndices) const inline
{
     const std::size_t num_indices = (sizeof...(otherIndices) + 1);
     const array<Index, num_indices> indices{{firstIndex, otherIndices...}};
     return coeff(indices);
   }
References Eigen::TensorRef< PlainObjectType >::coeff().
operator()() [2/2]
template<typename PlainObjectType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar Eigen::TensorRef< PlainObjectType >::operator() (Index index) const inline
 { return m_evaluator->coeff(index); }
References Eigen::TensorRef< PlainObjectType >::m_evaluator.
operator=() [1/2]
template<typename PlainObjectType > template<typename Expression > EIGEN_STRONG_INLINE TensorRef& Eigen::TensorRef< PlainObjectType >::operator= (const Expression & expr) inline
{
     unrefEvaluator();
     m_evaluator = new internal::TensorLazyEvaluator<Dimensions, Expression, DefaultDevice>(expr, DefaultDevice());
     m_evaluator->incrRefCount();
     return *this;
   }
References Eigen::TensorRef< PlainObjectType >::m_evaluator, and Eigen::TensorRef< PlainObjectType >::unrefEvaluator().
operator=() [2/2]
template<typename PlainObjectType > TensorRef& Eigen::TensorRef< PlainObjectType >::operator= (const TensorRef< PlainObjectType > & other) inline
{
     if (this != &other) {
       unrefEvaluator();
       m_evaluator = other.m_evaluator;
       eigen_assert(m_evaluator->refCount() > 0);
       m_evaluator->incrRefCount();
     }
     return *this;
   }
References eigen_assert, Eigen::TensorRef< PlainObjectType >::m_evaluator, and Eigen::TensorRef< PlainObjectType >::unrefEvaluator().
rank()
template<typename PlainObjectType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorRef< PlainObjectType >::rank () const inline
 { return m_evaluator->dimensions().size(); }
References Eigen::TensorRef< PlainObjectType >::m_evaluator.
size()
template<typename PlainObjectType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorRef< PlainObjectType >::size () const inline
 { return m_evaluator->dimensions().TotalSize(); }
References Eigen::TensorRef< PlainObjectType >::m_evaluator.
unrefEvaluator()
template<typename PlainObjectType > EIGEN_STRONG_INLINE void Eigen::TensorRef< PlainObjectType >::unrefEvaluator () inline private
{
     if (m_evaluator) {
       m_evaluator->decrRefCount();
       if (m_evaluator->refCount() == 0) {
         delete m_evaluator;
       }
     }
   }
References Eigen::TensorRef< PlainObjectType >::m_evaluator.
Referenced by Eigen::TensorRef< PlainObjectType >::operator=(), and Eigen::TensorRef< PlainObjectType >::~TensorRef().
Member Data Documentation
Layout
template<typename PlainObjectType > constexpr int Eigen::TensorRef< PlainObjectType >::Layout = PlainObjectType::Layout static constexpr
m_evaluator
template<typename PlainObjectType > internal::TensorLazyBaseEvaluator<Dimensions, Scalar>* Eigen::TensorRef< PlainObjectType >::m_evaluator private
Referenced by Eigen::TensorRef< PlainObjectType >::coeff(), Eigen::TensorRef< PlainObjectType >::coeffRef(), Eigen::TensorRef< PlainObjectType >::data(), Eigen::TensorRef< PlainObjectType >::dimension(), Eigen::TensorRef< PlainObjectType >::dimensions(), Eigen::TensorRef< PlainObjectType >::operator()(), Eigen::TensorRef< PlainObjectType >::operator=(), Eigen::TensorRef< PlainObjectType >::rank(), Eigen::TensorRef< PlainObjectType >::size(), Eigen::TensorRef< PlainObjectType >::TensorRef(), and Eigen::TensorRef< PlainObjectType >::unrefEvaluator().
NumIndices
template<typename PlainObjectType > constexpr Index Eigen::TensorRef< PlainObjectType >::NumIndices = PlainObjectType::NumIndices static constexpr
Referenced by Eigen::TensorRef< PlainObjectType >::coeff(), and Eigen::TensorRef< PlainObjectType >::coeffRef().
The documentation for this class was generated from the following files:
TensorForwardDeclarations.h
TensorRef.h