MercuryDPM: Eigen::internal::lapacke_helpers::lapacke_hqr< MatrixQR, HCoeffs > Struct Template Reference
Eigen::internal::lapacke_helpers::lapacke_hqr< MatrixQR, HCoeffs > Struct Template Reference
#include <HouseholderQR_LAPACKE.h>
Static Public Member Functions
static void run (MatrixQR &mat, HCoeffs &hCoeffs, Index=32, typename MatrixQR::Scalar *=0)
Member Function Documentation
run()
template<typename MatrixQR , typename HCoeffs > static void Eigen::internal::lapacke_helpers::lapacke_hqr< MatrixQR, HCoeffs >::run (MatrixQR & mat, HCoeffs & hCoeffs, Index = 32, typename MatrixQR::Scalar * = 0) inline static
{
     lapack_int m = to_lapack(mat.rows());
     lapack_int n = to_lapack(mat.cols());
     lapack_int lda = to_lapack(mat.outerStride());
     lapack_int matrix_order = lapack_storage_of(mat);
     geqrf(matrix_order, m, n, to_lapack(mat.data()), lda, to_lapack(hCoeffs.data()));
     hCoeffs.adjointInPlace();
   }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::cols(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::data(), lapack_int, Eigen::internal::lapacke_helpers::lapack_storage_of(), lda, m, n, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::rows(), and Eigen::internal::lapacke_helpers::to_lapack().
The documentation for this struct was generated from the following file:
HouseholderQR_LAPACKE.h