MercuryDPM: Eigen::SparseCompressedBase< Derived >::InnerIterator Class Reference
Eigen::SparseCompressedBase< Derived >::InnerIterator Class Reference
#include <SparseCompressedBase.h>
Public Member Functions
InnerIterator ()
InnerIterator (const InnerIterator &other)
InnerIterator & operator= (const InnerIterator &other)
InnerIterator (const SparseCompressedBase &mat, Index outer)
InnerIterator (const SparseCompressedBase &mat)
InnerIterator (const internal::CompressedStorage< Scalar, StorageIndex > &data)
InnerIterator & operator++ ()
InnerIterator & operator+= (Index i)
InnerIterator operator+ (Index i)
const Scalar & value () const
Scalar & valueRef ()
StorageIndex index () const
Index outer () const
Index row () const
Index col () const
operator bool () const
Protected Types
typedef internal::variable_if_dynamic< Index, Derived::IsVectorAtCompileTime ? 0 :Dynamic > OuterType
Protected Attributes
const Scalar * m_values
const StorageIndex * m_indices
const OuterType m_outer
Index m_id
Index m_end
Private Member Functions
template<typename T >
InnerIterator (const SparseMatrixBase< T > &, Index outer)
Member Typedef Documentation
OuterType
template<typename Derived > typedef internal::variable_if_dynamic<Index, Derived::IsVectorAtCompileTime ? 0 : Dynamic> Eigen::SparseCompressedBase< Derived >::InnerIterator::OuterType protected
Constructor & Destructor Documentation
InnerIterator() [1/6]
template<typename Derived > Eigen::SparseCompressedBase< Derived >::InnerIterator::InnerIterator () inline
 : m_values(0), m_indices(0), m_outer(0), m_id(0), m_end(0) {}
InnerIterator() [2/6]
template<typename Derived > Eigen::SparseCompressedBase< Derived >::InnerIterator::InnerIterator (const InnerIterator & other) inline
       : m_values(other.m_values),
         m_indices(other.m_indices),
         m_outer(other.m_outer),
         m_id(other.m_id),
         m_end(other.m_end) {}
InnerIterator() [3/6]
template<typename Derived > Eigen::SparseCompressedBase< Derived >::InnerIterator::InnerIterator (const SparseCompressedBase & mat, Index outer) inline
       : m_values(mat.valuePtr()), m_indices(mat.innerIndexPtr()), m_outer(outer) {
     if (Derived::IsVectorAtCompileTime && mat.outerIndexPtr() == 0) {
       m_id = 0;
       m_end = mat.nonZeros();
     } else {
       m_id = mat.outerIndexPtr()[outer];
       if (mat.isCompressed())
         m_end = mat.outerIndexPtr()[outer + 1];
       else
         m_end = m_id + mat.innerNonZeroPtr()[outer];
     }
   }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::innerNonZeroPtr(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::isCompressed(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::nonZeros(), and Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::outerIndexPtr().
InnerIterator() [4/6]
template<typename Derived > Eigen::SparseCompressedBase< Derived >::InnerIterator::InnerIterator (const SparseCompressedBase & mat) inline explicit
                                                           : InnerIterator(mat, Index(0)) {
     EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived);
   }
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
InnerIterator() [5/6]
template<typename Derived > Eigen::SparseCompressedBase< Derived >::InnerIterator::InnerIterator (const internal::CompressedStorage< Scalar, StorageIndex > & data) inline explicit
       : m_values(data.valuePtr()), m_indices(data.indexPtr()), m_outer(0), m_id(0), m_end(data.size()) {
     EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived);
   }
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
InnerIterator() [6/6]
template<typename Derived > template<typename T > Eigen::SparseCompressedBase< Derived >::InnerIterator::InnerIterator (const SparseMatrixBase< T > & , Index outer) private
Member Function Documentation
col()
template<typename Derived > Index Eigen::SparseCompressedBase< Derived >::InnerIterator::col () const inline
 { return IsRowMajor ? index() : m_outer.value(); }
References Eigen::SparseCompressedBase< Derived >::IsRowMajor.
index()
template<typename Derived > StorageIndex Eigen::SparseCompressedBase< Derived >::InnerIterator::index () const inline
 { return m_indices[m_id]; }
operator bool()
template<typename Derived > Eigen::SparseCompressedBase< Derived >::InnerIterator::operator bool () const inline
 { return (m_id < m_end); }
operator+()
template<typename Derived > InnerIterator Eigen::SparseCompressedBase< Derived >::InnerIterator::operator+ (Index i) inline
{
     InnerIterator result = *this;
     result += i;
     return result;
   }
References i.
operator++()
template<typename Derived > InnerIterator& Eigen::SparseCompressedBase< Derived >::InnerIterator::operator++ () inline
{
     m_id++;
     return *this;
   }
operator+=()
template<typename Derived > InnerIterator& Eigen::SparseCompressedBase< Derived >::InnerIterator::operator+= (Index i) inline
{
     m_id += i;
     return *this;
   }
References i.
operator=()
template<typename Derived > InnerIterator& Eigen::SparseCompressedBase< Derived >::InnerIterator::operator= (const InnerIterator & other) inline
{
     m_values = other.m_values;
     m_indices = other.m_indices;
     const_cast<OuterType&>(m_outer).setValue(other.m_outer.value());
     m_id = other.m_id;
     m_end = other.m_end;
     return *this;
   }
References Eigen::SparseCompressedBase< Derived >::InnerIterator::m_end, Eigen::SparseCompressedBase< Derived >::InnerIterator::m_id, Eigen::SparseCompressedBase< Derived >::InnerIterator::m_indices, Eigen::SparseCompressedBase< Derived >::InnerIterator::m_outer, Eigen::SparseCompressedBase< Derived >::InnerIterator::m_values, and Eigen::internal::variable_if_dynamic< T, Value >::value().
outer()
template<typename Derived > Index Eigen::SparseCompressedBase< Derived >::InnerIterator::outer () const inline
 { return m_outer.value(); }
row()
template<typename Derived > Index Eigen::SparseCompressedBase< Derived >::InnerIterator::row () const inline
 { return IsRowMajor ? m_outer.value() : index(); }
References Eigen::SparseCompressedBase< Derived >::IsRowMajor.
value()
template<typename Derived > const Scalar& Eigen::SparseCompressedBase< Derived >::InnerIterator::value () const inline
 { return m_values[m_id]; }
valueRef()
template<typename Derived > Scalar& Eigen::SparseCompressedBase< Derived >::InnerIterator::valueRef () inline
 { return const_cast<Scalar&>(m_values[m_id]); }
Member Data Documentation
m_end
template<typename Derived > Index Eigen::SparseCompressedBase< Derived >::InnerIterator::m_end protected
Referenced by Eigen::SparseCompressedBase< Derived >::InnerIterator::operator=().
m_id
template<typename Derived > Index Eigen::SparseCompressedBase< Derived >::InnerIterator::m_id protected
Referenced by Eigen::SparseCompressedBase< Derived >::InnerIterator::operator=().
m_indices
template<typename Derived > const StorageIndex* Eigen::SparseCompressedBase< Derived >::InnerIterator::m_indices protected
Referenced by Eigen::SparseCompressedBase< Derived >::InnerIterator::operator=().
m_outer
template<typename Derived > const OuterType Eigen::SparseCompressedBase< Derived >::InnerIterator::m_outer protected
Referenced by Eigen::SparseCompressedBase< Derived >::InnerIterator::operator=().
m_values
template<typename Derived > const Scalar* Eigen::SparseCompressedBase< Derived >::InnerIterator::m_values protected
Referenced by Eigen::SparseCompressedBase< Derived >::InnerIterator::operator=().
The documentation for this class was generated from the following file:
SparseCompressedBase.h