MercuryDPM: jacks_own_code.cc File Reference
jacks_own_code.cc File Reference
#include "generic.h"
#include "jack_cool.h"
#include "poisson.h"
#include "meshes/one_d_mesh.h"
Classes
class OneDPoissonProblem< ELEMENT >
1D Poisson problem in unit interval.
Namespaces
FishSolnOneDPoisson
Namespace for fish-shaped solution of 1D Poisson equation.
Functions
void FishSolnOneDPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact, fish-shaped solution as a 1D vector.
void FishSolnOneDPoisson::source_function (const Vector< double > &x, double &source)
Source function required to make the fish shape an exact solution.
int main ()
Driver for 1D Poisson problem.
Function Documentation
main()
int main ()
Driver for 1D Poisson problem.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
 {
  // Set up the problem:
  // Solve a 1D Poisson problem using a source function that generates
  // a fish shaped exact solution
  unsigned n_element=40; //Number of elements
  OneDPoissonProblem<QPoissonElement<1,4> > //Element type as template parameter
   problem(n_element,FishSolnOneDPoisson::source_function);
  // Check whether the problem can be solved
  cout << "\n\n\nProblem self-test ";
  if (problem.self_test()==0)
   {
    cout << "passed: Problem can be solved." << std::endl;
   }
  else
   {
    throw OomphLibError("failed!",
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
   }
  // Set the sign of the source function:
  cout << "\n\n\nSolving with negative sign:\n" << std::endl;
  FishSolnOneDPoisson::Sign=-1;
  // Solve the problem with this Sign
  problem.newton_solve();
  //Output solution for this case (label output files with "0")
  problem.doc_solution(0);
  // Change the sign of the source function:
  cout << "\n\n\nSolving with positive sign:\n" << std::endl;
  FishSolnOneDPoisson::Sign=1;
  // Re-solve the problem with this Sign (boundary conditions get
  // updated automatically when Problem::actions_before_newton_solve() is
  // called.
  problem.newton_solve();
  //Output solution for this case (label output files with "1")
  problem.doc_solution(1);
  // And now on to the exciting bit: We're building Jack's very own
  // hello world object!
  JacksHelloWorld hello_world;
  // Say something, using an inlined member function defined in the header file
  hello_world.say_it_inline();
  // Say something, using a precompiled member function defined in the *.cc file
  hello_world.say_it_external();
  cout << std::endl << std::endl;
 } // end of main
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, problem, oomph::JacksHelloWorld::say_it_external(), oomph::JacksHelloWorld::say_it_inline(), FishSolnOneDPoisson::Sign, and FishSolnOneDPoisson::source_function().