MercuryDPM: oomph::KirchhoffLoveBeamEquations Class Reference
oomph::KirchhoffLoveBeamEquations Class Reference
#include <beam_elements.h>
Public Member Functions
KirchhoffLoveBeamEquations ()
virtual void load_vector (const unsigned &intpt, const Vector< double > &xi, const Vector< double > &x, const Vector< double > &N, Vector< double > &load)
void wall_profile (const Vector< double > &xi, const Vector< double > &x, double &h_ratio)
const double & h () const
Return the non-dimensional wall thickness.
const double & lambda_sq () const
Return the timescale ratio (non-dimensional density)
const double & sigma0 () const
Return the axial prestress.
double *& sigma0_pt ()
Return a pointer to axial prestress.
double *& h_pt ()
Return a pointer to non-dim. wall thickness.
double *& lambda_sq_pt ()
Return a pointer to timescale ratio (nondim density)
GeomObject *& undeformed_beam_pt ()
void get_normal (const Vector< double > &s, Vector< double > &N)
Get normal vector on wall.
void get_normal (const Vector< double > &s, Vector< double > &r, Vector< double > &N)
Get position vector to and normal vector on wall.
void get_non_unit_tangent (const Vector< double > &s, Vector< double > &r, Vector< double > &drds)
Get position vector to and non-unit tangent vector on wall: dr/ds.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_contribution_to_residuals_beam (Vector< double > &residuals)
virtual void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Get FE jacobian and residuals (Jacobian done by finite differences)
void get_energy (double &pot_en, double &kin_en)
Get potential (strain) and kinetic energy of the element.
void get_energy (double &stretch, double &bend, double &kin_en)
Public Member Functions inherited from oomph::SolidFiniteElement
void set_lagrangian_dimension (const unsigned &lagrangian_dimension)
virtual bool has_internal_solid_data ()
SolidFiniteElement ()
Constructor: Set defaults.
virtual ~SolidFiniteElement ()
Destructor to clean up any allocated memory.
SolidFiniteElement (const SolidFiniteElement &)=delete
Broken copy constructor.
unsigned ngeom_data () const
Broken assignment operator.
Data * geom_data_pt (const unsigned &j)
void identify_geometric_data (std::set< Data * > &geometric_data_pt)
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_x_and_xi (const Vector< double > &s, Vector< double > &x_fe, Vector< double > &x, Vector< double > &xi_fe, Vector< double > &xi) const
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt, MacroElement *undeformed_macro_elem_pt)
void set_undeformed_macro_elem_pt (MacroElement *undeformed_macro_elem_pt)
MacroElement * undeformed_macro_elem_pt ()
Access function to pointer to "undeformed" macro element.
double dshape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi) const
virtual double dshape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi) const
double d2shape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
virtual double d2shape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
unsigned lagrangian_dimension () const
unsigned nnodal_lagrangian_type () const
Node * construct_node (const unsigned &n)
Construct the local node n and return a pointer to it.
Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Node * construct_boundary_node (const unsigned &n)
Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
double raw_lagrangian_position (const unsigned &n, const unsigned &i) const
double raw_lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double lagrangian_position (const unsigned &n, const unsigned &i) const
Return i-th Lagrangian coordinate at local node n.
double lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
virtual double interpolated_xi (const Vector< double > &s, const unsigned &i) const
virtual void interpolated_xi (const Vector< double > &s, Vector< double > &xi) const
virtual void interpolated_dxids (const Vector< double > &s, DenseMatrix< double > &dxids) const
virtual void J_lagrangian (const Vector< double > &s) const
virtual double J_lagrangian_at_knot (const unsigned &ipt) const
SolidInitialCondition *& solid_ic_pt ()
Pointer to object that describes the initial condition.
void enable_solve_for_consistent_newmark_accel ()
void disable_solve_for_consistent_newmark_accel ()
Set to reset the problem being solved to be the standard problem.
MultiplierFctPt & multiplier_fct_pt ()
MultiplierFctPt multiplier_fct_pt () const
virtual void get_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_for_newmark_accel (DenseMatrix< double > &jacobian)
void compute_norm (double &el_norm)
int position_local_eqn (const unsigned &n, const unsigned &k, const unsigned &j) const
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (std::ostream &outfile)
virtual void output (std::ostream &outfile, const unsigned &n_plot)
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output (FILE *file_pt)
virtual void output (FILE *file_pt, const unsigned &n_plot)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Attributes
void(*&)(const Vector< double > &xi, const Vector< double > &x, const Vector< double > &N, Vector< double > &load) load_vector_fct_pt ()
Reference to the load vector function pointer.
void(*&)(const Vector< double > &xi, const Vector< double > &x, double &h_ratio) wall_profile_fct_pt ()
Reference to the wall thickness ratio profile function pointer.
Static Protected Member Functions
static void Zero_traction_fct (const Vector< double > &xi, const Vector< double > &x, const Vector< double > &N, Vector< double > &load)
Default load function (zero traction)
static void Unit_profile_fct (const Vector< double > &xi, const Vector< double > &x, double &h_ratio)
Default profile function (constant thickness 'h_0')
Protected Attributes
void(* Load_vector_fct_pt)(const Vector< double > &xi, const Vector< double > &x, const Vector< double > &N, Vector< double > &load)
void(* Wall_profile_fct_pt)(const Vector< double > &xi, const Vector< double > &x, double &h_ratio)
GeomObject * Undeformed_beam_pt
Protected Attributes inherited from oomph::SolidFiniteElement
MacroElement * Undeformed_macro_elem_pt
Pointer to the element's "undeformed" macro element (NULL by default)
SolidInitialCondition * Solid_ic_pt
Pointer to object that specifies the initial condition.
bool Solve_for_consistent_newmark_accel_flag
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Private Attributes
double * Sigma0_pt
Pointer to axial prestress.
double * H_pt
Pointer to wall thickness.
double * Lambda_sq_pt
Pointer to Timescale ratio (non-dim. density)
Static Private Attributes
static double Default_sigma0_value = 0.0
Static default value for 2nd Piola Kirchhoff prestress.
static double Default_lambda_sq_value = 1.0
Static default value for timescale ratio (1.0 – for natural scaling)
static double Default_h_value = 0.05
Static default value for non-dim wall thickness.
Additional Inherited Members
Public Types inherited from oomph::SolidFiniteElement
typedef double(* MultiplierFctPt) (const Vector< double > &xi)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions inherited from oomph::SolidFiniteElement
void fill_in_generic_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
void set_nnodal_lagrangian_type (const unsigned &nlagrangian_type)
virtual double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_lagrangian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void assign_solid_local_eqn_numbers (const bool &store_local_dof)
Assign local equation numbers for the solid equations in the element.
void describe_solid_local_dofs (std::ostream &out, const std::string &current_string) const
Classifies dofs locally for solid specific aspects.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void fill_in_jacobian_from_solid_position_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_solid_position_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_solid_position_fd ()
virtual void reset_after_solid_position_fd ()
virtual void update_in_solid_position_fd (const unsigned &i)
virtual void reset_in_solid_position_fd (const unsigned &i)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
A class for elements that solve the equations of Kirchhoff-Love large-displacement (but linearly-elastic) thin-beam theory.
The variational principle has the form
\[ \int_0^{L} \left[ (\sigma_0 + \gamma) \ \delta \gamma + \frac{1}{12} \left(\frac{h}{R_0}\right)^2 \kappa \ \delta \kappa - \left(\left(\frac{R_0}{h}\right) {\bf f} - \Lambda^2 \frac{\partial^2 {\bf R}_w}{\partial t^2} \right) \cdot \delta {\bf R}_w \right] \ d\xi = 0, \]
where all lengths have been non-dimensionalised w.r.t. \(R_0 \). The strain and and bending "tensors" \(\gamma\) and \(\kappa\) are computed relative to the shape of the beam's undeformed shape which is specified as a GeomObject.
Time is scaled on the timescale \(T\) and
\[ \Lambda = \frac{a}{T} \sqrt{\frac{\rho}{E_{eff}}}, \]
the ratio of the timescale used in the non-dimensionalisation of the equations to the natural timescale of the wall oscillations (in the wall's in-plane mode). \(\Lambda^2 \) can be interpreted as the non-dimensional wall density, therefore \(\Lambda=0\) corresponds to the case without wall inertia.
Note that:
the load vector \({\bf f} \) is scaled on the effective elastic modulus \(E_{eff}=E/(1-\nu^2)\) (rather than the bending stiffness). Rescale the result yourself if you prefer another non-dimensionalisation (the current version yields the the most compact maths).
Poisson's ratio does not appear explicitly since it only occurs in combination with Young's modulus \(E\).
Default values:
the 2nd Piola Kirchhoff pre-stress \(\sigma_0 \) is zero.
the wall thickness \(h/R_0\) is 1/20.
the timescale ratio \(\Lambda^2\) is 1.
the traction vector \(f \) evaluates to zero.
Need to specify:
the undeformed wall shape (as a GeomObject).
The governing equations can be switched from the principle of virtual displacements to a system of equations that forces the beam to deform into a shape specified by a SolidInitialCondition object. If SolidFiniteElement::solid_ic_pt()!=0 we solve the the equations
\[ \int_0^{L} \left(\frac{\partial^i {\bf R}_{IC}}{\partial t^i} - {\bf R}_w \right) \psi_{jk} \ d\xi = 0, \]
where \(\partial^i {\bf R}_{IC}/\partial t^i\) is implemented by the SolidInitialCondition object, pointed to by SolidFiniteElement::shell_ic_pt().
Constructor & Destructor Documentation
KirchhoffLoveBeamEquations()
oomph::KirchhoffLoveBeamEquations::KirchhoffLoveBeamEquations () inline
Constructor. Set default values for all physical parameters and zero traction.
                                  : Undeformed_beam_pt(0)
     {
       // Set physical parameter pointers to the default values
       Sigma0_pt = &Default_sigma0_value;
       Lambda_sq_pt = &Default_lambda_sq_value;
       // The reference thickness 'h_0'
       H_pt = &Default_h_value;
       // Zero traction
       Load_vector_fct_pt = &Zero_traction_fct;
       // Unit thickness profile
       Wall_profile_fct_pt = &Unit_profile_fct;
     }
References Default_h_value, Default_lambda_sq_value, Default_sigma0_value, H_pt, Lambda_sq_pt, Load_vector_fct_pt, Sigma0_pt, Unit_profile_fct(), Wall_profile_fct_pt, and Zero_traction_fct().
Member Function Documentation
fill_in_contribution_to_jacobian()
void oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) virtual
Get FE jacobian and residuals (Jacobian done by finite differences)
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::FSIHermiteBeamElement.
   {
     // Call the element's residuals vector
     fill_in_contribution_to_residuals_beam(residuals);
     // Solve for the consistent acceleration in Newmark scheme?
     if (Solve_for_consistent_newmark_accel_flag)
     {
       SolidFiniteElement::fill_in_jacobian_for_newmark_accel(jacobian);
       return;
     }
     // Allocate storage for the full residuals of the element
     unsigned n_dof = ndof();
     Vector<double> full_residuals(n_dof);
     // Call the full residuals
     get_residuals(full_residuals);
     // Get the solid entries in the jacobian using finite differences
     SolidFiniteElement::fill_in_jacobian_from_solid_position_by_fd(
       full_residuals, jacobian);
     // Get the entries from the external data, usually load terms
     SolidFiniteElement::fill_in_jacobian_from_external_by_fd(full_residuals,
                                                              jacobian);
   }
References fill_in_contribution_to_residuals_beam(), oomph::SolidFiniteElement::fill_in_jacobian_for_newmark_accel(), oomph::GeneralisedElement::fill_in_jacobian_from_external_by_fd(), oomph::SolidFiniteElement::fill_in_jacobian_from_solid_position_by_fd(), oomph::GeneralisedElement::get_residuals(), oomph::GeneralisedElement::ndof(), and oomph::SolidFiniteElement::Solve_for_consistent_newmark_accel_flag.
Referenced by oomph::FSIHermiteBeamElement::fill_in_contribution_to_jacobian().
fill_in_contribution_to_residuals()
void oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Return the residuals for the equations of Kirchhoff-Love beam theory with linear constitutive equations; if Solid_ic_pt!=0, we assign residuals which force the assignement of an initial shape/ veloc/accel to the dofs. This overloads the standard interface.
Reimplemented from oomph::GeneralisedElement.
     {
       fill_in_contribution_to_residuals_beam(residuals);
     }
References fill_in_contribution_to_residuals_beam().
fill_in_contribution_to_residuals_beam()
void oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_residuals_beam (Vector< double > & residuals)
Return the residuals for the equations of Kirchhoff-Love beam theory with linear constitutive equations; if Solid_ic_pt!=0, we assign residuals which force the assignement of an initial shape/ veloc/accel to the dofs.
   {
     // Set up the initial conditions, if an IC pointer has been set
     if (Solid_ic_pt != 0)
     {
       fill_in_residuals_for_solid_ic(residuals);
       return;
     }
     // Set the dimension of the global coordinates
     const unsigned n_dim = Undeformed_beam_pt->ndim();
     // Set the number of lagrangian coordinates
     const unsigned n_lagrangian = Undeformed_beam_pt->nlagrangian();
     // Find out how many nodes there are
     const unsigned n_node = nnode();
     // Find out how many positional dofs there are
     const unsigned n_position_type = nnodal_position_type();
     // Integer to store the local equation number
     int local_eqn = 0;
     // Setup memory for accelerations
     Vector<double> accel(2);
     // Set up memory for the shape functions:
     // # of nodes, # of positional dofs
     Shape psi(n_node, n_position_type);
     // # of nodes, # of positional dofs, # of lagrangian coords (for deriv)
     DShape dpsidxi(n_node, n_position_type, n_lagrangian);
     // # of nodes, # of positional dofs, # of derivs)
     DShape d2psidxi(n_node, n_position_type, n_lagrangian);
     // Set # of integration points
     const unsigned n_intpt = integral_pt()->nweight();
     // Get Physical Variables from Element
     // Thickness h_0/R, axial prestress, timescale ratio (density)
     const double HoR_0 = h(); // i.e. refers to reference thickness 'h_0'
     const double sigma_0 = sigma0();
     const double Lambda_sq = lambda_sq();
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the shape functions w.r.t. Lagrangian coords
       double J = d2shape_lagrangian_at_knot(ipt, psi, dpsidxi, d2psidxi);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Calculate local values of lagrangian position and
       // the derivative of global position wrt lagrangian coordinates
       Vector<double> interpolated_xi(n_lagrangian, 0.0),
         interpolated_x(n_dim, 0.0);
       DenseMatrix<double> interpolated_A(n_lagrangian, n_dim);
       DenseMatrix<double> interpolated_dAdxi(n_lagrangian, n_dim);
       // Initialise to zero
       // Loop over coordinate directions/components of Vector
       for (unsigned i = 0; i < n_dim; i++)
       {
         // Initialise acclerations
         accel[i] = 0.0;
         // Loop over derivatives/base Vectors (just one here)
         for (unsigned j = 0; j < n_lagrangian; j++)
         {
           interpolated_A(j, i) = 0.0;
         }
         // Loop over derivatives of base Vector (just one here)
         for (unsigned j = 0; j < n_lagrangian; j++)
         {
           interpolated_dAdxi(j, i) = 0.0;
         }
       }
       // Calculate displacements, accelerations and spatial derivatives
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over positional dofs
         for (unsigned k = 0; k < n_position_type; k++)
         {
           // Loop over Lagrangian coordinate directions [xi_gen[] are the
           // the *gen*eralised Lagrangian coordinates: node, type, direction]
           for (unsigned i = 0; i < n_lagrangian; i++)
           {
             interpolated_xi[i] +=
               raw_lagrangian_position_gen(l, k, i) * psi(l, k);
           }
           // Loop over components of the deformed position Vector
           for (unsigned i = 0; i < n_dim; i++)
           {
             interpolated_x[i] += raw_nodal_position_gen(l, k, i) * psi(l, k);
             accel[i] += raw_dnodal_position_gen_dt(2, l, k, i) * psi(l, k);
             // Loop over derivative directions (just one here)
             for (unsigned j = 0; j < n_lagrangian; j++)
             {
               interpolated_A(j, i) +=
                 raw_nodal_position_gen(l, k, i) * dpsidxi(l, k, j);
             }
             // Loop over the second derivative directions (just one here)
             for (unsigned j = 0; j < n_lagrangian; j++)
             {
               interpolated_dAdxi(j, i) +=
                 raw_nodal_position_gen(l, k, i) * d2psidxi(l, k, j);
             }
           }
         }
       }
       // Setup position Vector and derivatives of undeformed config
       Vector<double> R(n_dim);
       DenseMatrix<double> a(n_lagrangian, n_dim);
       RankThreeTensor<double> dadxi(n_lagrangian, n_lagrangian, n_dim);
       // Get the undeformed geometry
       Undeformed_beam_pt->d2position(interpolated_xi, R, a, dadxi);
       // Declare and calculate the undeformed and deformed metric tensor
       // and the strain tensor (these are just scalars)
       double amet = 0.0, Amet = 0.0;
       // Now calculate the dot product
       for (unsigned k = 0; k < n_dim; k++)
       {
         amet += a(0, k) * a(0, k);
         Amet += interpolated_A(0, k) * interpolated_A(0, k);
       }
       double gamma = 0.5 * (Amet - amet);
       // Calculate the contravariant metric tensors
       double adet = amet; // double aup = 1.0/amet;
       double Adet = Amet; // double Aup = 1.0/Amet;
       // Calculate the unit normal Vectors
       Vector<double> n(2);
       Vector<double> N(2);
       n[0] = -a(0, 1) / sqrt(adet);
       n[1] = a(0, 0) / sqrt(adet);
       N[0] = -interpolated_A(0, 1) / sqrt(Adet);
       N[1] = interpolated_A(0, 0) / sqrt(Adet);
       // Square root of deformed determinant
       double sqrt_Adet = sqrt(Adet);
       // Calculate the curvature tensors
       double b = n[0] * dadxi(0, 0, 0) + n[1] * dadxi(0, 0, 1);
       double B =
         N[0] * interpolated_dAdxi(0, 0) + N[1] * interpolated_dAdxi(0, 1);
       // Set up the change of curvature tensor
       double kappa = b - B;
       // Define the load Vector
       Vector<double> f(n_dim);
       // Get load Vector
       load_vector(ipt, interpolated_xi, interpolated_x, N, f);
       // Define the wall thickness ratio profile
       double h_ratio = 0;
       // Get wall thickness ratio profile
       wall_profile(interpolated_xi, interpolated_x, h_ratio);
       // Thickness h/R
       double HoR = HoR_0 * h_ratio;
       // Allocate storage for variations of normal Vector
       double normal_var[n_dim][n_dim];
       // Geometrically nonlinear beam equations from
       //--------------------------------------------
       // principle of virtual displacements
       //-----------------------------------
       // Loop over the number of nodes
       for (unsigned n = 0; n < n_node; n++)
       {
         // Loop over the type of degree of freedom
         for (unsigned k = 0; k < n_position_type; k++)
         {
           // Setup components of variation of normal Vector:
           // ...(variation w.r.t. direction, component)
           normal_var[0][0] = interpolated_A(0, 0) * interpolated_A(0, 1) *
                              dpsidxi(n, k, 0) /
                              (sqrt_Adet * sqrt_Adet * sqrt_Adet);
           normal_var[1][0] =
             (interpolated_A(0, 1) * interpolated_A(0, 1) / Adet - 1.0) *
             dpsidxi(n, k, 0) / (sqrt_Adet);
           normal_var[0][1] =
             (1.0 - interpolated_A(0, 0) * interpolated_A(0, 0) / Adet) *
             dpsidxi(n, k, 0) / (sqrt_Adet);
           normal_var[1][1] = -interpolated_A(0, 0) * interpolated_A(0, 1) *
                              dpsidxi(n, k, 0) /
                              (sqrt_Adet * sqrt_Adet * sqrt_Adet);
           // Loop over the coordinate directions
           for (unsigned i = 0; i < n_dim; i++)
           {
             // Find the equation number
             local_eqn = position_local_eqn(n, k, i);
             // If it's not a boundary condition
             if (local_eqn >= 0)
             {
               // Premultiply by thickness profile
               // External forcing
               residuals[local_eqn] -=
                 h_ratio * (1.0 / HoR) * f[i] * psi(n, k) * W * sqrt(Adet);
               residuals[local_eqn] +=
                 h_ratio * Lambda_sq * accel[i] * psi(n, k) * W * sqrt(adet);
               // Membrane term with axial prestress
               residuals[local_eqn] += h_ratio * (sigma_0 + gamma) *
                                       interpolated_A(0, i) * dpsidxi(n, k, 0) *
                                       W * sqrt(adet);
               // Bending term: Minus sign because \delta \kappa = - \delta B
               residuals[local_eqn] -=
                 h_ratio * (1.0 / 12.0) * HoR * HoR * kappa *
                 (N[i] * d2psidxi(n, k, 0) +
                  normal_var[i][0] * interpolated_dAdxi(0, 0) +
                  normal_var[i][1] * interpolated_dAdxi(0, 1)) *
                 W * sqrt(adet);
             }
           }
         }
       }
     } // End of loop over the integration points
   }
References a, b, oomph::GeomObject::d2position(), oomph::SolidFiniteElement::d2shape_lagrangian_at_knot(), f(), oomph::SolidFiniteElement::fill_in_residuals_for_solid_ic(), mathsFunc::gamma(), h(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::SolidFiniteElement::interpolated_xi(), J, j, k, Global_Physical_Variables::Lambda_sq, lambda_sq(), load_vector(), n, N, oomph::GeomObject::ndim(), oomph::GeomObject::nlagrangian(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), oomph::SolidFiniteElement::position_local_eqn(), R, oomph::FiniteElement::raw_dnodal_position_gen_dt(), oomph::SolidFiniteElement::raw_lagrangian_position_gen(), oomph::FiniteElement::raw_nodal_position_gen(), sigma0(), oomph::SolidFiniteElement::Solid_ic_pt, sqrt(), Undeformed_beam_pt, w, oomph::QuadTreeNames::W, wall_profile(), and oomph::Integral::weight().
Referenced by fill_in_contribution_to_jacobian(), and fill_in_contribution_to_residuals().
get_energy() [1/2]
void oomph::KirchhoffLoveBeamEquations::get_energy (double & pot_en, double & kin_en)
Get potential (strain) and kinetic energy of the element.
Compute the potential (strain) and kinetic energy of the element (wrapper function).
   {
     // Initialise
     double stretch = 0.0;
     double bend = 0.0;
     kin_en = 0.0;
     // Compute energy
     get_energy(stretch, bend, kin_en);
     // Sum components of potential energy
     pot_en = stretch + bend;
   }
get_energy() [2/2]
void oomph::KirchhoffLoveBeamEquations::get_energy (double & stretch, double & bend, double & kin_en)
Get the potential energy due to stretching and bending and the kinetic energy of the element
Compute the potential (strain) and kinetic energy of the element, breaking down the potential energy into stretching and bending components.
   {
     // Initialise
     stretch = 0.0;
     bend = 0.0;
     kin_en = 0.0;
     // Set the dimension of the global coordinates
     unsigned n_dim = Undeformed_beam_pt->ndim();
     // Set the number of lagrangian coordinates
     unsigned n_lagrangian = Undeformed_beam_pt->nlagrangian();
     // Find out how many nodes there are
     unsigned n_node = nnode();
     // Find out how many positional dofs there are
     unsigned n_position_dofs = nnodal_position_type();
     // Setup memory for veloc
     Vector<double> veloc(2);
     // Set up memory for the shape functions:
     // # of nodes, # of positional dofs
     Shape psi(n_node, n_position_dofs);
     // # of nodes, # of positional dofs, # of lagrangian coords (for deriv)
     DShape dpsidxi(n_node, n_position_dofs, n_lagrangian);
     // # of nodes, # of positional dofs, # of derivs)
     DShape d2psidxi(n_node, n_position_dofs, n_lagrangian);
     // Set # of integration points
     unsigned n_intpt = integral_pt()->nweight();
     // Get Physical Variables from Element
     // Thickness h_0/R, axial prestress, timescale ratio (density)
     double HoR_0 = h(); // i.e. refers to reference thickness 'h_0'
     double sigma_0 = sigma0();
     double Lambda_sq = lambda_sq();
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the shape functions w.r.t. Lagrangian coords
       double J = d2shape_lagrangian_at_knot(ipt, psi, dpsidxi, d2psidxi);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Calculate local values of lagrangian position and
       // the derivative of global position wrt lagrangian coordinates
       Vector<double> interpolated_xi(n_lagrangian, 0.0),
         interpolated_x(n_dim, 0.0);
       DenseMatrix<double> interpolated_A(n_lagrangian, n_dim);
       DenseMatrix<double> interpolated_dAdxi(n_lagrangian, n_dim);
       // Initialise to zero
       // Loop over coordinate directions/components of Vector
       for (unsigned i = 0; i < n_dim; i++)
       {
         // Initialise veloc
         veloc[i] = 0.0;
         // Loop over derivatives/base Vectors (just one here)
         for (unsigned j = 0; j < n_lagrangian; j++)
         {
           interpolated_A(j, i) = 0.0;
         }
         // Loop over derivatives of base Vector (just one here)
         for (unsigned j = 0; j < n_lagrangian; j++)
         {
           interpolated_dAdxi(j, i) = 0.0;
         }
       }
       // Calculate displacements, accelerations and spatial derivatives
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over positional dofs
         for (unsigned k = 0; k < n_position_dofs; k++)
         {
           // Loop over Lagrangian coordinate directions [xi_gen[] are the
           // the *gen*eralised Lagrangian coordinates: node, type, direction]
           for (unsigned i = 0; i < n_lagrangian; i++)
           {
             interpolated_xi[i] +=
               raw_lagrangian_position_gen(l, k, i) * psi(l, k);
           }
           // Loop over components of the deformed position Vector
           for (unsigned i = 0; i < n_dim; i++)
           {
             // Need this for wall thickness ratio profile
             interpolated_x[i] += raw_nodal_position_gen(l, k, i) * psi(l, k);
             veloc[i] += raw_dnodal_position_gen_dt(1, l, k, i) * psi(l, k);
             // Loop over derivative directions (just one here)
             for (unsigned j = 0; j < n_lagrangian; j++)
             {
               interpolated_A(j, i) +=
                 raw_nodal_position_gen(l, k, i) * dpsidxi(l, k, j);
             }
             // Loop over the second derivative directions (just one here)
             for (unsigned j = 0; j < n_lagrangian; j++)
             {
               interpolated_dAdxi(j, i) +=
                 raw_nodal_position_gen(l, k, i) * d2psidxi(l, k, j);
             }
           }
         }
       }
       // Get square of veloc
       double veloc_sq = 0;
       for (unsigned i = 0; i < n_dim; i++)
       {
         veloc_sq += veloc[i] * veloc[i];
       }
       // Setup position Vector and derivatives of undeformed config
       Vector<double> R(n_dim);
       DenseMatrix<double> a(n_lagrangian, n_dim);
       RankThreeTensor<double> dadxi(n_lagrangian, n_lagrangian, n_dim);
       // Get the undeformed geometry
       Undeformed_beam_pt->d2position(interpolated_xi, R, a, dadxi);
       // Declare and calculate the undeformed and deformed metric tensor
       // and the strain tensor (these are 1d tensors, i.e. scalars)
       double amet = 0.0, Amet = 0.0;
       // Work out metric and strain tensors
       // Now calculate the dot product
       for (unsigned k = 0; k < n_dim; k++)
       {
         amet += a(0, k) * a(0, k);
         Amet += interpolated_A(0, k) * interpolated_A(0, k);
       }
       // Calculate strain tensor
       double gamma = 0.5 * (Amet - amet);
       // Calculate the contravariant metric tensors
       double adet = amet; // aup = 1.0/amet;
       double Adet = Amet; // Aup = 1.0/Amet;
       // Calculate the unit normal Vectors
       Vector<double> n(2);
       Vector<double> N(2);
       n[0] = -a(0, 1) / sqrt(adet);
       n[1] = a(0, 0) / sqrt(adet);
       N[0] = -interpolated_A(0, 1) / sqrt(Adet);
       N[1] = interpolated_A(0, 0) / sqrt(Adet);
       // Calculate the curvature tensors
       double b = n[0] * dadxi(0, 0, 0) + n[1] * dadxi(0, 0, 1);
       double B =
         N[0] * interpolated_dAdxi(0, 0) + N[1] * interpolated_dAdxi(0, 1);
       // Set up the change of curvature tensor
       double kappa = b - B;
       // Define the wall thickness ratio profile
       double h_ratio = 0;
       // Get wall thickness ratio profile
       wall_profile(interpolated_xi, interpolated_x, h_ratio);
       // Thickness h/R
       double HoR = HoR_0 * h_ratio;
       // Add contributions
       stretch +=
         h_ratio * 0.5 * (gamma + sigma_0) * (gamma + sigma_0) * W * sqrt(adet);
       bend += h_ratio * 0.5 * (1.0 / 12.0) * HoR * HoR * kappa * kappa * W *
               sqrt(adet);
       kin_en += h_ratio * 0.5 * Lambda_sq * veloc_sq * W * sqrt(adet);
     } // End of loop over the integration points
   }
References a, b, oomph::GeomObject::d2position(), oomph::SolidFiniteElement::d2shape_lagrangian_at_knot(), mathsFunc::gamma(), h(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::SolidFiniteElement::interpolated_xi(), J, j, k, Global_Physical_Variables::Lambda_sq, lambda_sq(), n, N, oomph::GeomObject::ndim(), oomph::GeomObject::nlagrangian(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), R, oomph::FiniteElement::raw_dnodal_position_gen_dt(), oomph::SolidFiniteElement::raw_lagrangian_position_gen(), oomph::FiniteElement::raw_nodal_position_gen(), sigma0(), sqrt(), Undeformed_beam_pt, w, oomph::QuadTreeNames::W, wall_profile(), and oomph::Integral::weight().
get_non_unit_tangent()
void oomph::KirchhoffLoveBeamEquations::get_non_unit_tangent (const Vector< double > & s, Vector< double > & r, Vector< double > & drds)
Get position vector to and non-unit tangent vector on wall: dr/ds.
Get position vector to and non-unit tangent vector on wall: dr/ds
   {
 #ifdef PARANOID
     if (drds.size() != 2)
     {
       std::ostringstream error_message;
       error_message << "Tangent vector should have dimension 2, not"
                     << drds.size() << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     if (r.size() != 2)
     {
       std::ostringstream error_message;
       error_message << "Position vector should have dimension 2, not"
                     << r.size() << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     if (s.size() != 1)
     {
       std::ostringstream error_message;
       error_message << "Local coordinate should have dimension 1, not"
                     << s.size() << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Set the dimension of the global coordinates
     unsigned n_dim = Undeformed_beam_pt->ndim();
     // Set the number of lagrangian coordinates
     unsigned n_lagrangian = Undeformed_beam_pt->nlagrangian();
     // Find out how many nodes there are
     unsigned n_node = nnode();
     // Find out how many positional dofs there are
     unsigned n_position_type = nnodal_position_type();
     // Set up memory for the shape functions:
     // # of nodes, # of positional dofs
     Shape psi(n_node, n_position_type);
     // # of nodes, # of positional dofs, # of lagrangian coords (for deriv)
     DShape dpsids(n_node, n_position_type, n_lagrangian);
     // Call the derivatives of the shape functions w.r.t. local coords
     dshape_local(s, psi, dpsids);
     // Initialise to zero
     // Loop over coordinate directions/components of Vector
     for (unsigned i = 0; i < n_dim; i++)
     {
       r[i] = 0.0;
       drds[i] = 0.0;
     }
     // Loop over directions
     for (unsigned i = 0; i < n_dim; i++)
     {
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over positional dofs
         for (unsigned k = 0; k < n_position_type; k++)
         {
           r[i] += raw_nodal_position_gen(l, k, i) * psi(l, k);
           // deriv w.r.t. to zero-th (and only) local coordiate
           drds[i] += raw_nodal_position_gen(l, k, i) * dpsids(l, k, 0);
         }
       }
     }
   }
References oomph::FiniteElement::dshape_local(), i, k, oomph::GeomObject::ndim(), oomph::GeomObject::nlagrangian(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, UniformPSDSelfTest::r, oomph::FiniteElement::raw_nodal_position_gen(), s, and Undeformed_beam_pt.
Referenced by oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::fill_in_contribution_to_residuals().
get_normal() [1/2]
void oomph::KirchhoffLoveBeamEquations::get_normal (const Vector< double > & s, Vector< double > & N) inline
Get normal vector on wall.
     {
       Vector<double> r(2);
       get_normal(s, r, N);
     }
References N, UniformPSDSelfTest::r, and s.
Referenced by FSIChannelWithLeafletProblem< ELEMENT >::doc_solution(), and oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::fill_in_contribution_to_residuals().
get_normal() [2/2]
void oomph::KirchhoffLoveBeamEquations::get_normal (const Vector< double > & s, Vector< double > & r, Vector< double > & N)
Get position vector to and normal vector on wall.
   {
 #ifdef PARANOID
     if (N.size() != 2)
     {
       std::ostringstream error_message;
       error_message << "Normal vector should have dimension 2, not" << N.size()
                     << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     if (r.size() != 2)
     {
       std::ostringstream error_message;
       error_message << "Position vector should have dimension 2, not"
                     << r.size() << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     if (s.size() != 1)
     {
       std::ostringstream error_message;
       error_message << "Local coordinate should have dimension 1, not"
                     << s.size() << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Set the dimension of the global coordinates
     unsigned n_dim = Undeformed_beam_pt->ndim();
     // Set the number of lagrangian coordinates
     unsigned n_lagrangian = Undeformed_beam_pt->nlagrangian();
     // Find out how many nodes there are
     unsigned n_node = nnode();
     // Find out how many positional dofs there are
     unsigned n_position_type = nnodal_position_type();
     // Set up memory for the shape functions:
     // # of nodes, # of positional dofs
     Shape psi(n_node, n_position_type);
     // # of nodes, # of positional dofs, # of lagrangian coords (for deriv)
     DShape dpsidxi(n_node, n_position_type, n_lagrangian);
     // Call the derivatives of the shape functions w.r.t. Lagrangian coords
     dshape_lagrangian(s, psi, dpsidxi);
     // Base Vector
     DenseMatrix<double> interpolated_A(n_lagrangian, n_dim);
     // Initialise to zero
     // Loop over coordinate directions/components of Vector
     for (unsigned i = 0; i < n_dim; i++)
     {
       r[i] = 0.0;
       // Loop over derivatives/base Vectors (just one here)
       for (unsigned j = 0; j < n_lagrangian; j++)
       {
         interpolated_A(j, i) = 0.0;
       }
     }
     // Loop over directions
     for (unsigned i = 0; i < n_dim; i++)
     {
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over positional dofs
         for (unsigned k = 0; k < n_position_type; k++)
         {
           r[i] += raw_nodal_position_gen(l, k, i) * psi(l, k);
           // Loop over derivative directions (just one here)
           for (unsigned j = 0; j < n_lagrangian; j++)
           {
             interpolated_A(j, i) +=
               raw_nodal_position_gen(l, k, i) * dpsidxi(l, k, j);
           }
         }
       }
     }
     // Calculate the length of the normal vector
     double length = pow(interpolated_A(0, 0), 2) + pow(interpolated_A(0, 1), 2);
     // Calculate the normal
     N[0] = -interpolated_A(0, 1) / sqrt(length);
     N[1] = interpolated_A(0, 0) / sqrt(length);
   }
References oomph::SolidFiniteElement::dshape_lagrangian(), i, j, k, N, oomph::GeomObject::ndim(), oomph::GeomObject::nlagrangian(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, Eigen::bfloat16_impl::pow(), UniformPSDSelfTest::r, oomph::FiniteElement::raw_nodal_position_gen(), s, sqrt(), and Undeformed_beam_pt.
h()
const double& oomph::KirchhoffLoveBeamEquations::h () const inline
Return the non-dimensional wall thickness.
     {
       return *H_pt;
     }
References H_pt.
Referenced by fill_in_contribution_to_residuals_beam(), and get_energy().
h_pt()
double*& oomph::KirchhoffLoveBeamEquations::h_pt () inline
Return a pointer to non-dim. wall thickness.
     {
       return H_pt;
     }
References H_pt.
Referenced by AirwayReopeningProblem< ELEMENT >::AirwayReopeningProblem(), ElasticBeamProblem::ElasticBeamProblem(), FSIChannelWithLeafletProblem< ELEMENT >::FSIChannelWithLeafletProblem(), FSICollapsibleChannelProblem< ELEMENT >::FSICollapsibleChannelProblem(), FSIDrivenCavityProblem< ELEMENT >::FSIDrivenCavityProblem(), and FSIRingProblem::FSIRingProblem().
lambda_sq()
const double& oomph::KirchhoffLoveBeamEquations::lambda_sq () const inline
Return the timescale ratio (non-dimensional density)
     {
       return *Lambda_sq_pt;
     }
References Lambda_sq_pt.
Referenced by fill_in_contribution_to_residuals_beam(), and get_energy().
lambda_sq_pt()
double*& oomph::KirchhoffLoveBeamEquations::lambda_sq_pt () inline
Return a pointer to timescale ratio (nondim density)
     {
       return Lambda_sq_pt;
     }
References Lambda_sq_pt.
Referenced by FSIChannelWithLeafletProblem< ELEMENT >::FSIChannelWithLeafletProblem(), FSIDrivenCavityProblem< ELEMENT >::FSIDrivenCavityProblem(), and FSIRingProblem::FSIRingProblem().
load_vector()
virtual void oomph::KirchhoffLoveBeamEquations::load_vector (const unsigned & intpt, const Vector< double > & xi, const Vector< double > & x, const Vector< double > & N, Vector< double > & load) inline virtual
Get the load vector: Pass number of integration point (dummy), Lagr. and Eulerian coordinate and normal vector and return the load vector (not all of the input arguments will be required for all specific load functions but the list should cover all cases). This function is virtual so it can be overloaded for FSI.
Reimplemented in oomph::FSIHermiteBeamElement.
     {
       Load_vector_fct_pt(xi, x, N, load);
     }
References load(), Load_vector_fct_pt, N, and plotDoE::x.
Referenced by fill_in_contribution_to_residuals_beam().
sigma0()
const double& oomph::KirchhoffLoveBeamEquations::sigma0 () const inline
Return the axial prestress.
     {
       return *Sigma0_pt;
     }
References Sigma0_pt.
Referenced by fill_in_contribution_to_residuals_beam(), and get_energy().
sigma0_pt()
double*& oomph::KirchhoffLoveBeamEquations::sigma0_pt () inline
Return a pointer to axial prestress.
     {
       return Sigma0_pt;
     }
References Sigma0_pt.
Referenced by AirwayReopeningProblem< ELEMENT >::AirwayReopeningProblem(), ElasticBeamProblem::ElasticBeamProblem(), and FSICollapsibleChannelProblem< ELEMENT >::FSICollapsibleChannelProblem().
undeformed_beam_pt()
GeomObject*& oomph::KirchhoffLoveBeamEquations::undeformed_beam_pt () inline
Return a Pointer to geometric object that specifies the beam's undeformed geometry
     {
       return Undeformed_beam_pt;
     }
References Undeformed_beam_pt.
Referenced by AirwayReopeningProblem< ELEMENT >::AirwayReopeningProblem(), ElasticBeamProblem::ElasticBeamProblem(), ElasticRefineableQuarterCircleSectorMesh< ELEMENT >::ElasticRefineableQuarterCircleSectorMesh(), FSIChannelWithLeafletProblem< ELEMENT >::FSIChannelWithLeafletProblem(), FSICollapsibleChannelProblem< ELEMENT >::FSICollapsibleChannelProblem(), FSIDrivenCavityProblem< ELEMENT >::FSIDrivenCavityProblem(), and FSIRingProblem::FSIRingProblem().
Unit_profile_fct()
void oomph::KirchhoffLoveBeamEquations::Unit_profile_fct (const Vector< double > & xi, const Vector< double > & x, double & h_ratio) static protected
Default profile function (constant thickness 'h_0')
Default wall profile function (constant thickness h_0)
   {
     h_ratio = 1.0;
   }
Referenced by KirchhoffLoveBeamEquations().
wall_profile()
void oomph::KirchhoffLoveBeamEquations::wall_profile (const Vector< double > & xi, const Vector< double > & x, double & h_ratio) inline
Get the wall profile: Pass Lagrangian & Eulerian coordinate and return the wall profile (not all of the input arguments will be required for all specific thickness functions but the list should cover all cases).
     {
       Wall_profile_fct_pt(xi, x, h_ratio);
     }
References Wall_profile_fct_pt, and plotDoE::x.
Referenced by fill_in_contribution_to_residuals_beam(), and get_energy().
Zero_traction_fct()
void oomph::KirchhoffLoveBeamEquations::Zero_traction_fct (const Vector< double > & xi, const Vector< double > & x, const Vector< double > & N, Vector< double > & load) static protected
Default load function (zero traction)
   {
     unsigned n_dim = load.size();
     for (unsigned i = 0; i < n_dim; i++)
     {
       load[i] = 0.0;
     }
   }
References i, and load().
Referenced by KirchhoffLoveBeamEquations().
Member Data Documentation
Default_h_value
double oomph::KirchhoffLoveBeamEquations::Default_h_value = 0.05 static private
Static default value for non-dim wall thickness.
Static default value for non-dim wall thickness (1/20)
Referenced by KirchhoffLoveBeamEquations().
Default_lambda_sq_value
double oomph::KirchhoffLoveBeamEquations::Default_lambda_sq_value = 1.0 static private
Static default value for timescale ratio (1.0 – for natural scaling)
Static default value for timescale ratio (1.0 for natural scaling)
Referenced by KirchhoffLoveBeamEquations().
Default_sigma0_value
double oomph::KirchhoffLoveBeamEquations::Default_sigma0_value = 0.0 static private
Static default value for 2nd Piola Kirchhoff prestress.
Static default value for 2nd Piola Kirchhoff prestress (zero)
Referenced by KirchhoffLoveBeamEquations().
H_pt
double* oomph::KirchhoffLoveBeamEquations::H_pt private
Pointer to wall thickness.
Referenced by h(), h_pt(), and KirchhoffLoveBeamEquations().
Lambda_sq_pt
double* oomph::KirchhoffLoveBeamEquations::Lambda_sq_pt private
Pointer to Timescale ratio (non-dim. density)
Referenced by KirchhoffLoveBeamEquations(), lambda_sq(), and lambda_sq_pt().
load_vector_fct_pt
void(*&)(const Vector<double>& xi, const Vector<double>& x, const Vector<double>& N, Vector<double>& load) oomph::KirchhoffLoveBeamEquations::load_vector_fct_pt() inline
Reference to the load vector function pointer.
     {
       return Load_vector_fct_pt;
     }
Referenced by AirwayReopeningProblem< ELEMENT >::AirwayReopeningProblem(), ElasticBeamProblem::ElasticBeamProblem(), FSICollapsibleChannelProblem< ELEMENT >::FSICollapsibleChannelProblem(), and FSIRingProblem::FSIRingProblem().
Load_vector_fct_pt
void(* oomph::KirchhoffLoveBeamEquations::Load_vector_fct_pt) (const Vector< double > &xi, const Vector< double > &x, const Vector< double > &N, Vector< double > &load) protected
Pointer to load vector function: Its arguments are: Lagrangian coordinate, Eulerian coordinate, normal vector and load vector itself (not all of the input arguments will be required for all specific load functions but the list should cover all cases)
Referenced by KirchhoffLoveBeamEquations(), load_vector(), and oomph::FSIHermiteBeamElement::load_vector().
Sigma0_pt
double* oomph::KirchhoffLoveBeamEquations::Sigma0_pt private
Pointer to axial prestress.
Referenced by KirchhoffLoveBeamEquations(), sigma0(), and sigma0_pt().
Undeformed_beam_pt
GeomObject* oomph::KirchhoffLoveBeamEquations::Undeformed_beam_pt protected
Pointer to the GeomObject that specifies the beam's undeformed midplane
Referenced by oomph::FSIHermiteBeamElement::dposition_dlagrangian_at_local_coordinate(), fill_in_contribution_to_residuals_beam(), get_energy(), get_non_unit_tangent(), get_normal(), oomph::HermiteBeamElement::output(), and undeformed_beam_pt().
wall_profile_fct_pt
void(*&)(const Vector<double>& xi, const Vector<double>& x, double& h_ratio) oomph::KirchhoffLoveBeamEquations::wall_profile_fct_pt() inline
Reference to the wall thickness ratio profile function pointer.
     {
       return Wall_profile_fct_pt;
     }
Wall_profile_fct_pt
void(* oomph::KirchhoffLoveBeamEquations::Wall_profile_fct_pt) (const Vector< double > &xi, const Vector< double > &x, double &h_ratio) protected
Pointer to wall profile function: Its arguments are: Lagrangian coordinate, Eulerian coordinate, and profile itself (not all of the input arguments will be required for all specific profile functions but the list should cover all cases)
Referenced by KirchhoffLoveBeamEquations(), and wall_profile().
The documentation for this class was generated from the following files:
beam_elements.h
beam_elements.cc