MercuryDPM: Eigen::AutoDiffVector< ValueType, JacobianType > Class Template Reference
Eigen::AutoDiffVector< ValueType, JacobianType > Class Template Reference
#include <AutoDiffVector.h>
Public Types
typedef internal::traits< ValueType >::Scalar BaseScalar
typedef AutoDiffScalar< Matrix< BaseScalar, JacobianType::RowsAtCompileTime, 1 > > ActiveScalar
typedef ActiveScalar Scalar
typedef AutoDiffScalar< typename JacobianType::ColXpr > CoeffType
typedef JacobianType::Index Index
Public Member Functions
AutoDiffVector ()
AutoDiffVector (const ValueType &values)
CoeffType operator[] (Index i)
const CoeffType operator[] (Index i) const
CoeffType operator() (Index i)
const CoeffType operator() (Index i) const
CoeffType coeffRef (Index i)
const CoeffType coeffRef (Index i) const
Index size () const
Scalar sum () const
AutoDiffVector (const ValueType &values, const JacobianType &jac)
template<typename OtherValueType , typename OtherJacobianType >
AutoDiffVector (const AutoDiffVector< OtherValueType, OtherJacobianType > &other)
AutoDiffVector (const AutoDiffVector &other)
template<typename OtherValueType , typename OtherJacobianType >
AutoDiffVector & operator= (const AutoDiffVector< OtherValueType, OtherJacobianType > &other)
AutoDiffVector & operator= (const AutoDiffVector &other)
const ValueType & values () const
ValueType & values ()
const JacobianType & jacobian () const
JacobianType & jacobian ()
template<typename OtherValueType , typename OtherJacobianType >
const AutoDiffVector< typename MakeCwiseBinaryOp< internal::scalar_sum_op< BaseScalar >, ValueType, OtherValueType >::Type, typename MakeCwiseBinaryOp< internal::scalar_sum_op< BaseScalar >, JacobianType, OtherJacobianType >::Type > operator+ (const AutoDiffVector< OtherValueType, OtherJacobianType > &other) const
template<typename OtherValueType , typename OtherJacobianType >
AutoDiffVector & operator+= (const AutoDiffVector< OtherValueType, OtherJacobianType > &other)
template<typename OtherValueType , typename OtherJacobianType >
const AutoDiffVector< typename MakeCwiseBinaryOp< internal::scalar_difference_op< Scalar >, ValueType, OtherValueType >::Type, typename MakeCwiseBinaryOp< internal::scalar_difference_op< Scalar >, JacobianType, OtherJacobianType >::Type > operator- (const AutoDiffVector< OtherValueType, OtherJacobianType > &other) const
template<typename OtherValueType , typename OtherJacobianType >
AutoDiffVector & operator-= (const AutoDiffVector< OtherValueType, OtherJacobianType > &other)
const AutoDiffVector< typename MakeCwiseUnaryOp< internal::scalar_opposite_op< Scalar >, ValueType >::Type, typename MakeCwiseUnaryOp< internal::scalar_opposite_op< Scalar >, JacobianType >::Type > operator- () const
const AutoDiffVector< typename MakeCwiseUnaryOp< internal::scalar_multiple_op< Scalar >, ValueType >::Type, typename MakeCwiseUnaryOp< internal::scalar_multiple_op< Scalar >, JacobianType >::Type > operator* (const BaseScalar &other) const
AutoDiffVector & operator*= (const Scalar &other)
template<typename OtherValueType , typename OtherJacobianType >
AutoDiffVector & operator*= (const AutoDiffVector< OtherValueType, OtherJacobianType > &other)
Protected Attributes
ValueType m_values
JacobianType m_jacobian
Friends
const AutoDiffVector< typename MakeCwiseUnaryOp< internal::scalar_multiple_op< Scalar >, ValueType >::Type, typename MakeCwiseUnaryOp< internal::scalar_multiple_op< Scalar >, JacobianType >::Type > operator* (const Scalar &other, const AutoDiffVector &v)
Member Typedef Documentation
ActiveScalar
template<typename ValueType , typename JacobianType > typedef AutoDiffScalar<Matrix<BaseScalar, JacobianType::RowsAtCompileTime, 1> > Eigen::AutoDiffVector< ValueType, JacobianType >::ActiveScalar
BaseScalar
template<typename ValueType , typename JacobianType > typedef internal::traits<ValueType>::Scalar Eigen::AutoDiffVector< ValueType, JacobianType >::BaseScalar
CoeffType
template<typename ValueType , typename JacobianType > typedef AutoDiffScalar<typename JacobianType::ColXpr> Eigen::AutoDiffVector< ValueType, JacobianType >::CoeffType
Index
template<typename ValueType , typename JacobianType > typedef JacobianType::Index Eigen::AutoDiffVector< ValueType, JacobianType >::Index
Scalar
template<typename ValueType , typename JacobianType > typedef ActiveScalar Eigen::AutoDiffVector< ValueType, JacobianType >::Scalar
Constructor & Destructor Documentation
AutoDiffVector() [1/5]
template<typename ValueType , typename JacobianType > Eigen::AutoDiffVector< ValueType, JacobianType >::AutoDiffVector () inline
 {}
AutoDiffVector() [2/5]
template<typename ValueType , typename JacobianType > Eigen::AutoDiffVector< ValueType, JacobianType >::AutoDiffVector (const ValueType & values) inline
 : m_values(values) { m_jacobian.setZero(); }
References Eigen::AutoDiffVector< ValueType, JacobianType >::m_jacobian.
AutoDiffVector() [3/5]
template<typename ValueType , typename JacobianType > Eigen::AutoDiffVector< ValueType, JacobianType >::AutoDiffVector (const ValueType & values, const JacobianType & jac) inline
 : m_values(values), m_jacobian(jac) {}
AutoDiffVector() [4/5]
template<typename ValueType , typename JacobianType > template<typename OtherValueType , typename OtherJacobianType > Eigen::AutoDiffVector< ValueType, JacobianType >::AutoDiffVector (const AutoDiffVector< OtherValueType, OtherJacobianType > & other) inline
       : m_values(other.values()), m_jacobian(other.jacobian()) {}
AutoDiffVector() [5/5]
template<typename ValueType , typename JacobianType > Eigen::AutoDiffVector< ValueType, JacobianType >::AutoDiffVector (const AutoDiffVector< ValueType, JacobianType > & other) inline
 : m_values(other.values()), m_jacobian(other.jacobian()) {}
Member Function Documentation
coeffRef() [1/2]
template<typename ValueType , typename JacobianType > CoeffType Eigen::AutoDiffVector< ValueType, JacobianType >::coeffRef (Index i) inline
 { return CoeffType(m_values[i], m_jacobian.col(i)); }
References i, Eigen::AutoDiffVector< ValueType, JacobianType >::m_jacobian, and Eigen::AutoDiffVector< ValueType, JacobianType >::m_values.
coeffRef() [2/2]
template<typename ValueType , typename JacobianType > const CoeffType Eigen::AutoDiffVector< ValueType, JacobianType >::coeffRef (Index i) const inline
 { return CoeffType(m_values[i], m_jacobian.col(i)); }
References i, Eigen::AutoDiffVector< ValueType, JacobianType >::m_jacobian, and Eigen::AutoDiffVector< ValueType, JacobianType >::m_values.
jacobian() [1/2]
template<typename ValueType , typename JacobianType > JacobianType& Eigen::AutoDiffVector< ValueType, JacobianType >::jacobian () inline
 { return m_jacobian; }
References Eigen::AutoDiffVector< ValueType, JacobianType >::m_jacobian.
jacobian() [2/2]
template<typename ValueType , typename JacobianType > const JacobianType& Eigen::AutoDiffVector< ValueType, JacobianType >::jacobian () const inline
 { return m_jacobian; }
References Eigen::AutoDiffVector< ValueType, JacobianType >::m_jacobian.
Referenced by Eigen::AutoDiffVector< ValueType, JacobianType >::operator+(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator+=(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator-(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator-=(), and Eigen::AutoDiffVector< ValueType, JacobianType >::operator=().
operator()() [1/2]
template<typename ValueType , typename JacobianType > CoeffType Eigen::AutoDiffVector< ValueType, JacobianType >::operator() (Index i) inline
 { return CoeffType(m_values[i], m_jacobian.col(i)); }
References i, Eigen::AutoDiffVector< ValueType, JacobianType >::m_jacobian, and Eigen::AutoDiffVector< ValueType, JacobianType >::m_values.
operator()() [2/2]
template<typename ValueType , typename JacobianType > const CoeffType Eigen::AutoDiffVector< ValueType, JacobianType >::operator() (Index i) const inline
 { return CoeffType(m_values[i], m_jacobian.col(i)); }
References i, Eigen::AutoDiffVector< ValueType, JacobianType >::m_jacobian, and Eigen::AutoDiffVector< ValueType, JacobianType >::m_values.
operator*()
template<typename ValueType , typename JacobianType > const AutoDiffVector<typename MakeCwiseUnaryOp<internal::scalar_multiple_op<Scalar>, ValueType>::Type, typename MakeCwiseUnaryOp<internal::scalar_multiple_op<Scalar>, JacobianType>::Type> Eigen::AutoDiffVector< ValueType, JacobianType >::operator* (const BaseScalar & other) const inline
{
     return AutoDiffVector<typename MakeCwiseUnaryOp<internal::scalar_multiple_op<Scalar>, ValueType>::Type,
                           typename MakeCwiseUnaryOp<internal::scalar_multiple_op<Scalar>, JacobianType>::Type>(
         m_values * other, m_jacobian * other);
   }
References Eigen::AutoDiffVector< ValueType, JacobianType >::m_jacobian, and Eigen::AutoDiffVector< ValueType, JacobianType >::m_values.
operator*=() [1/2]
template<typename ValueType , typename JacobianType > template<typename OtherValueType , typename OtherJacobianType > AutoDiffVector& Eigen::AutoDiffVector< ValueType, JacobianType >::operator*= (const AutoDiffVector< OtherValueType, OtherJacobianType > & other) inline
{
     *this = *this * other;
     return *this;
   }
operator*=() [2/2]
template<typename ValueType , typename JacobianType > AutoDiffVector& Eigen::AutoDiffVector< ValueType, JacobianType >::operator*= (const Scalar & other) inline
{
     m_values *= other;
     m_jacobian *= other;
     return *this;
   }
References Eigen::AutoDiffVector< ValueType, JacobianType >::m_jacobian, and Eigen::AutoDiffVector< ValueType, JacobianType >::m_values.
operator+()
template<typename ValueType , typename JacobianType > template<typename OtherValueType , typename OtherJacobianType > const AutoDiffVector< typename MakeCwiseBinaryOp<internal::scalar_sum_op<BaseScalar>, ValueType, OtherValueType>::Type, typename MakeCwiseBinaryOp<internal::scalar_sum_op<BaseScalar>, JacobianType, OtherJacobianType>::Type> Eigen::AutoDiffVector< ValueType, JacobianType >::operator+ (const AutoDiffVector< OtherValueType, OtherJacobianType > & other) const inline
{
     return AutoDiffVector<
         typename MakeCwiseBinaryOp<internal::scalar_sum_op<BaseScalar>, ValueType, OtherValueType>::Type,
         typename MakeCwiseBinaryOp<internal::scalar_sum_op<BaseScalar>, JacobianType, OtherJacobianType>::Type>(
         m_values + other.values(), m_jacobian + other.jacobian());
   }
References Eigen::AutoDiffVector< ValueType, JacobianType >::jacobian(), Eigen::AutoDiffVector< ValueType, JacobianType >::m_jacobian, Eigen::AutoDiffVector< ValueType, JacobianType >::m_values, and Eigen::AutoDiffVector< ValueType, JacobianType >::values().
operator+=()
template<typename ValueType , typename JacobianType > template<typename OtherValueType , typename OtherJacobianType > AutoDiffVector& Eigen::AutoDiffVector< ValueType, JacobianType >::operator+= (const AutoDiffVector< OtherValueType, OtherJacobianType > & other) inline
{
     m_values += other.values();
     m_jacobian += other.jacobian();
     return *this;
   }
References Eigen::AutoDiffVector< ValueType, JacobianType >::jacobian(), Eigen::AutoDiffVector< ValueType, JacobianType >::m_jacobian, Eigen::AutoDiffVector< ValueType, JacobianType >::m_values, and Eigen::AutoDiffVector< ValueType, JacobianType >::values().
operator-() [1/2]
template<typename ValueType , typename JacobianType > const AutoDiffVector<typename MakeCwiseUnaryOp<internal::scalar_opposite_op<Scalar>, ValueType>::Type, typename MakeCwiseUnaryOp<internal::scalar_opposite_op<Scalar>, JacobianType>::Type> Eigen::AutoDiffVector< ValueType, JacobianType >::operator- (void) const inline
                     {
     return AutoDiffVector<typename MakeCwiseUnaryOp<internal::scalar_opposite_op<Scalar>, ValueType>::Type,
                           typename MakeCwiseUnaryOp<internal::scalar_opposite_op<Scalar>, JacobianType>::Type>(
         -m_values, -m_jacobian);
   }
References Eigen::AutoDiffVector< ValueType, JacobianType >::m_jacobian, and Eigen::AutoDiffVector< ValueType, JacobianType >::m_values.
operator-() [2/2]
template<typename ValueType , typename JacobianType > template<typename OtherValueType , typename OtherJacobianType > const AutoDiffVector< typename MakeCwiseBinaryOp<internal::scalar_difference_op<Scalar>, ValueType, OtherValueType>::Type, typename MakeCwiseBinaryOp<internal::scalar_difference_op<Scalar>, JacobianType, OtherJacobianType>::Type> Eigen::AutoDiffVector< ValueType, JacobianType >::operator- (const AutoDiffVector< OtherValueType, OtherJacobianType > & other) const inline
{
     return AutoDiffVector<
         typename MakeCwiseBinaryOp<internal::scalar_difference_op<Scalar>, ValueType, OtherValueType>::Type,
         typename MakeCwiseBinaryOp<internal::scalar_difference_op<Scalar>, JacobianType, OtherJacobianType>::Type>(
         m_values - other.values(), m_jacobian - other.jacobian());
   }
References Eigen::AutoDiffVector< ValueType, JacobianType >::jacobian(), Eigen::AutoDiffVector< ValueType, JacobianType >::m_jacobian, Eigen::AutoDiffVector< ValueType, JacobianType >::m_values, and Eigen::AutoDiffVector< ValueType, JacobianType >::values().
operator-=()
template<typename ValueType , typename JacobianType > template<typename OtherValueType , typename OtherJacobianType > AutoDiffVector& Eigen::AutoDiffVector< ValueType, JacobianType >::operator-= (const AutoDiffVector< OtherValueType, OtherJacobianType > & other) inline
{
     m_values -= other.values();
     m_jacobian -= other.jacobian();
     return *this;
   }
References Eigen::AutoDiffVector< ValueType, JacobianType >::jacobian(), Eigen::AutoDiffVector< ValueType, JacobianType >::m_jacobian, Eigen::AutoDiffVector< ValueType, JacobianType >::m_values, and Eigen::AutoDiffVector< ValueType, JacobianType >::values().
operator=() [1/2]
template<typename ValueType , typename JacobianType > AutoDiffVector& Eigen::AutoDiffVector< ValueType, JacobianType >::operator= (const AutoDiffVector< ValueType, JacobianType > & other) inline
{
     m_values = other.values();
     m_jacobian = other.jacobian();
     return *this;
   }
References Eigen::AutoDiffVector< ValueType, JacobianType >::jacobian(), Eigen::AutoDiffVector< ValueType, JacobianType >::m_jacobian, Eigen::AutoDiffVector< ValueType, JacobianType >::m_values, and Eigen::AutoDiffVector< ValueType, JacobianType >::values().
operator=() [2/2]
template<typename ValueType , typename JacobianType > template<typename OtherValueType , typename OtherJacobianType > AutoDiffVector& Eigen::AutoDiffVector< ValueType, JacobianType >::operator= (const AutoDiffVector< OtherValueType, OtherJacobianType > & other) inline
{
     m_values = other.values();
     m_jacobian = other.jacobian();
     return *this;
   }
References Eigen::AutoDiffVector< ValueType, JacobianType >::jacobian(), Eigen::AutoDiffVector< ValueType, JacobianType >::m_jacobian, Eigen::AutoDiffVector< ValueType, JacobianType >::m_values, and Eigen::AutoDiffVector< ValueType, JacobianType >::values().
operator[]() [1/2]
template<typename ValueType , typename JacobianType > CoeffType Eigen::AutoDiffVector< ValueType, JacobianType >::operator[] (Index i) inline
 { return CoeffType(m_values[i], m_jacobian.col(i)); }
References i, Eigen::AutoDiffVector< ValueType, JacobianType >::m_jacobian, and Eigen::AutoDiffVector< ValueType, JacobianType >::m_values.
operator[]() [2/2]
template<typename ValueType , typename JacobianType > const CoeffType Eigen::AutoDiffVector< ValueType, JacobianType >::operator[] (Index i) const inline
 { return CoeffType(m_values[i], m_jacobian.col(i)); }
References i, Eigen::AutoDiffVector< ValueType, JacobianType >::m_jacobian, and Eigen::AutoDiffVector< ValueType, JacobianType >::m_values.
size()
template<typename ValueType , typename JacobianType > Index Eigen::AutoDiffVector< ValueType, JacobianType >::size () const inline
 { return m_values.size(); }
References Eigen::AutoDiffVector< ValueType, JacobianType >::m_values.
sum()
template<typename ValueType , typename JacobianType > Scalar Eigen::AutoDiffVector< ValueType, JacobianType >::sum () const inline
                      { /*std::cerr << "sum \n\n";*/ /*std::cerr << m_jacobian.rowwise().sum() << "\n\n";*/
     return Scalar(m_values.sum(), m_jacobian.rowwise().sum());
   }
References Eigen::AutoDiffVector< ValueType, JacobianType >::m_jacobian, and Eigen::AutoDiffVector< ValueType, JacobianType >::m_values.
values() [1/2]
template<typename ValueType , typename JacobianType > ValueType& Eigen::AutoDiffVector< ValueType, JacobianType >::values () inline
 { return m_values; }
References Eigen::AutoDiffVector< ValueType, JacobianType >::m_values.
values() [2/2]
template<typename ValueType , typename JacobianType > const ValueType& Eigen::AutoDiffVector< ValueType, JacobianType >::values () const inline
 { return m_values; }
References Eigen::AutoDiffVector< ValueType, JacobianType >::m_values.
Referenced by Eigen::AutoDiffVector< ValueType, JacobianType >::operator+(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator+=(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator-(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator-=(), and Eigen::AutoDiffVector< ValueType, JacobianType >::operator=().
Friends And Related Function Documentation
operator*
template<typename ValueType , typename JacobianType > const AutoDiffVector< typename MakeCwiseUnaryOp<internal::scalar_multiple_op<Scalar>, ValueType>::Type, typename MakeCwiseUnaryOp<internal::scalar_multiple_op<Scalar>, JacobianType>::Type> operator* (const Scalar & other, const AutoDiffVector< ValueType, JacobianType > & v) friend
{
     return AutoDiffVector<typename MakeCwiseUnaryOp<internal::scalar_multiple_op<Scalar>, ValueType>::Type,
                           typename MakeCwiseUnaryOp<internal::scalar_multiple_op<Scalar>, JacobianType>::Type>(
         v.values() * other, v.jacobian() * other);
   }
Member Data Documentation
m_jacobian
template<typename ValueType , typename JacobianType > JacobianType Eigen::AutoDiffVector< ValueType, JacobianType >::m_jacobian protected
Referenced by Eigen::AutoDiffVector< ValueType, JacobianType >::AutoDiffVector(), Eigen::AutoDiffVector< ValueType, JacobianType >::coeffRef(), Eigen::AutoDiffVector< ValueType, JacobianType >::jacobian(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator()(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator*(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator*=(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator+(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator+=(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator-(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator-=(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator=(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator[](), and Eigen::AutoDiffVector< ValueType, JacobianType >::sum().
m_values
template<typename ValueType , typename JacobianType > ValueType Eigen::AutoDiffVector< ValueType, JacobianType >::m_values protected
Referenced by Eigen::AutoDiffVector< ValueType, JacobianType >::coeffRef(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator()(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator*(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator*=(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator+(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator+=(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator-(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator-=(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator=(), Eigen::AutoDiffVector< ValueType, JacobianType >::operator[](), Eigen::AutoDiffVector< ValueType, JacobianType >::size(), Eigen::AutoDiffVector< ValueType, JacobianType >::sum(), and Eigen::AutoDiffVector< ValueType, JacobianType >::values().
The documentation for this class was generated from the following file:
AutoDiffVector.h