MercuryDPM: TwoLayerInterfaceProblem< ELEMENT > Class Template Reference
TwoLayerInterfaceProblem< ELEMENT > Class Template Reference
Problem class to simulate viscous drop propagating along 2D channel.
Public Member Functions
TwoLayerInterfaceProblem ()
Constructor.
~TwoLayerInterfaceProblem ()
Destructor.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of free surface elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of free surface elements.
void actions_after_newton_solve ()
Update the after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve.
void complete_problem_setup ()
Set boundary conditions and complete the build of all elements.
void doc_solution (const std::string &comment="")
Doc the solution.
void compute_error_estimate (double &max_err, double &min_err)
Compute the error estimates and assign to elements for plotting.
void set_initial_condition ()
Set the initial conditions.
void deform_interface (const double &epsilon, const unsigned &n_periods)
Function to deform the interface.
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Private Types
enum {
Inflow_boundary_id =0 , Upper_wall_boundary_id =1 , Outflow_boundary_id =2 , Bottom_wall_boundary_id =3 ,
Interface_boundary_id =4
}
Enumeration of channel boundaries.
Private Member Functions
void create_free_surface_elements ()
Create free surface elements.
void delete_free_surface_elements ()
Delete free surface elements.
Private Attributes
Mesh * Free_surface_mesh_pt
Pointers to mesh of free surface elements.
RefineableSolidTriangleMesh< ELEMENT > * Fluid_mesh_pt
Pointer to Fluid_mesh.
Vector< TriangleMeshPolygon * > Drop_polygon_pt
Vector storing pointer to the drop polygons.
TriangleMeshPolygon * Outer_boundary_polyline_pt
Triangle mesh polygon for outer boundary.
Data * Drop_pressure_data_pt
Pointer to a global drop pressure datum.
double Initial_value_for_drop_pressure
Backed up drop pressure between adaptations.
ELEMENT * Hijacked_element_pt
Pointer to hijacked element.
bool Use_volume_constraint
Bool to indicate if volume constraint is applied (only for steady run)
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_convergence_check ()
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_before_implicit_timestep ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class ELEMENT>
class TwoLayerInterfaceProblem< ELEMENT >
Problem class to simulate viscous drop propagating along 2D channel.
Member Enumeration Documentation
anonymous enum
template<class ELEMENT > anonymous enum private
Enumeration of channel boundaries.
Enumerator
Inflow_boundary_id
Upper_wall_boundary_id
Outflow_boundary_id
Bottom_wall_boundary_id
Interface_boundary_id
  {
   Inflow_boundary_id=0,
   Upper_wall_boundary_id=1,
   Outflow_boundary_id=2,
   Bottom_wall_boundary_id=3,
   Interface_boundary_id=4,
  };
Constructor & Destructor Documentation
TwoLayerInterfaceProblem()
template<class ELEMENT > TwoLayerInterfaceProblem< ELEMENT >::TwoLayerInterfaceProblem
Constructor.
 {
  // Output directory
  Problem_Parameter::Doc_info.set_directory("RESLT");
  // Allocate the timestepper -- this constructs the Problem's
  // time object with a sufficient amount of storage to store the
  // previous timsteps.
  this->add_time_stepper_pt(new BDF<2>);
  // Build the boundary segments for outer boundary, consisting of
  //--------------------------------------------------------------
  // four separate polylines
  //------------------------
  Vector<TriangleMeshCurveSection*> boundary_polyline_pt(4);
  // Each polyline only has three vertices -- provide storage for their
  // coordinates
  Vector<Vector<double> > vertex_coord(3);
  for(unsigned i=0;i<3;i++)
   {
    vertex_coord[i].resize(2);
   }
  const double H = Problem_Parameter::Height;
  const double h = Problem_Parameter::Interface_Height*H;
  // First polyline: Inflow
  vertex_coord[0][0]=0.0;
  vertex_coord[0][1]=0.0;
  vertex_coord[1][0]=0.0;
  vertex_coord[1][1]= h;
  vertex_coord[2][0]=0.0;
  vertex_coord[2][1]= H;
  // Build the 1st boundary polyline
  boundary_polyline_pt[0] = new TriangleMeshPolyLine(vertex_coord,
                                                    Inflow_boundary_id);
  // Second boundary polyline: Upper wall
  vertex_coord[0][0]=0.0;
  vertex_coord[0][1]=H;
  vertex_coord[1][0]=0.5*Problem_Parameter::Length;
  vertex_coord[1][1]=H;
  vertex_coord[2][0]=Problem_Parameter::Length;
  vertex_coord[2][1]=H;
  // Build the 2nd boundary polyline
  boundary_polyline_pt[1] = new TriangleMeshPolyLine(vertex_coord,
                                                    Upper_wall_boundary_id);
  // Third boundary polyline: Outflow
  vertex_coord[0][0]=Problem_Parameter::Length;
  vertex_coord[0][1]=H;
  vertex_coord[1][0]=Problem_Parameter::Length;
  vertex_coord[1][1]=h;
  vertex_coord[2][0]=Problem_Parameter::Length;
  vertex_coord[2][1]=0.0;
  // Build the 3rd boundary polyline
  boundary_polyline_pt[2] = new TriangleMeshPolyLine(vertex_coord,
                                                    Outflow_boundary_id);
  // Fourth boundary polyline: Bottom wall
  vertex_coord[0][0]=Problem_Parameter::Length;
  vertex_coord[0][1]=0.0;
  vertex_coord[1][0]=0.5*Problem_Parameter::Length;
  vertex_coord[1][1]=0.0;
  vertex_coord[2][0]=0.0;
  vertex_coord[2][1]=0.0;
  // Build the 4th boundary polyline
  boundary_polyline_pt[3] = new TriangleMeshPolyLine(vertex_coord,
                                                     Bottom_wall_boundary_id);
  // Create the triangle mesh polygon for outer boundary
  Outer_boundary_polyline_pt = new TriangleMeshPolygon(boundary_polyline_pt);
  //Here we need to put the dividing internal line in
  Vector<TriangleMeshOpenCurve *> interface_pt(1);
  //Set the vertex coordinates
  vertex_coord[0][0]=0.0;
  vertex_coord[0][1]=h;
  vertex_coord[1][0]=0.5*Problem_Parameter::Length;
  vertex_coord[1][1]=h;
  vertex_coord[2][0]=Problem_Parameter::Length;
  vertex_coord[2][1]=h;
 //Create the internal line
   TriangleMeshPolyLine* interface_polyline_pt =
    new TriangleMeshPolyLine(vertex_coord,
                             Interface_boundary_id);
   // Do the connection with the destination boundary, in this case
   // the connection is done with the inflow boundary
   interface_polyline_pt->connect_initial_vertex_to_polyline(
    dynamic_cast<TriangleMeshPolyLine*>(boundary_polyline_pt[0]),1);
   // Do the connection with the destination boundary, in this case
   // the connection is done with the outflow boundary
   interface_polyline_pt->connect_final_vertex_to_polyline(
    dynamic_cast<TriangleMeshPolyLine*>(boundary_polyline_pt[2]),1);
   Vector<TriangleMeshCurveSection*> interface_curve_pt(1);
   interface_curve_pt[0] = interface_polyline_pt;
   interface_pt[0] = new TriangleMeshOpenCurve(interface_curve_pt);
  // Now build the mesh, based on the boundaries specified by
  //---------------------------------------------------------
  // polygons just created
  //----------------------
  // Convert to "closed curve" objects
  TriangleMeshClosedCurve* outer_closed_curve_pt=Outer_boundary_polyline_pt;
  unsigned n_internal_closed_boundaries = 0;
  Vector<TriangleMeshClosedCurve *>
   inner_boundaries_pt(n_internal_closed_boundaries);
  // Target area for initial mesh
  double uniform_element_area=0.01;
  // Use the TriangleMeshParameter object for gathering all
  // the necessary arguments for the TriangleMesh object
  TriangleMeshParameters triangle_mesh_parameters(
    outer_closed_curve_pt);
  //Define the inner boundaries
  triangle_mesh_parameters.internal_closed_curve_pt() = inner_boundaries_pt;
  // Define the holes on the boundary
  triangle_mesh_parameters.internal_open_curves_pt() = interface_pt;
  // Define the maximum element area
  triangle_mesh_parameters.element_area() =
    uniform_element_area;
  Vector<double> lower_region(2);
  lower_region[0] = 0.5*Problem_Parameter::Length;
  lower_region[1] = 0.5*Problem_Parameter::Interface_Height;
  // Define the region
  triangle_mesh_parameters.add_region_coordinates(1, lower_region);
  // Create the mesh
  Fluid_mesh_pt =
    new RefineableSolidTriangleMesh<ELEMENT>(
      triangle_mesh_parameters, this->time_stepper_pt());
  // Set error estimator for bulk mesh
  Z2ErrorEstimator* error_estimator_pt=new Z2ErrorEstimator;
  Fluid_mesh_pt->spatial_error_estimator_pt()=error_estimator_pt;
  // Set targets for spatial adaptivity
  Fluid_mesh_pt->max_permitted_error()=0.005;
  Fluid_mesh_pt->min_permitted_error()=0.001;
  Fluid_mesh_pt->max_element_size()=0.2;
  Fluid_mesh_pt->min_element_size()=0.001;
  // Use coarser mesh during validation
  if (CommandLineArgs::command_line_flag_has_been_set("--validation"))
   {
    Fluid_mesh_pt->min_element_size()=0.01;
   }
  // Output boundary and mesh initial mesh for information
  this->Fluid_mesh_pt->output_boundaries("boundaries.dat");
  this->Fluid_mesh_pt->output("mesh.dat");
  // Set boundary condition and complete the build of all elements
  complete_problem_setup();
  // Construct the mesh of free surface elements
  Free_surface_mesh_pt=new Mesh;
  create_free_surface_elements();
  // Combine meshes
  //---------------
  // Add Fluid_mesh_pt sub meshes
  this->add_sub_mesh(Fluid_mesh_pt);
  // Add Free_surface sub meshes
  this->add_sub_mesh(this->Free_surface_mesh_pt);
  // Build global mesh
  this->build_global_mesh();
  // Setup equation numbering scheme
  cout <<"Number of equations: " << this->assign_eqn_numbers() << std::endl;
 } // end_of_constructor
References oomph::TriangleMeshParameters::add_region_coordinates(), oomph::CommandLineArgs::command_line_flag_has_been_set(), oomph::TriangleMeshCurveSection::connect_final_vertex_to_polyline(), oomph::TriangleMeshCurveSection::connect_initial_vertex_to_polyline(), Problem_Parameter::Doc_info, oomph::TriangleMeshParameters::element_area(), MeshRefinement::error_estimator_pt, H, Problem_Parameter::Height, i, Problem_Parameter::Interface_Height, oomph::TriangleMeshParameters::internal_closed_curve_pt(), oomph::TriangleMeshParameters::internal_open_curves_pt(), Problem_Parameter::Length, and oomph::DocInfo::set_directory().
~TwoLayerInterfaceProblem()
template<class ELEMENT > TwoLayerInterfaceProblem< ELEMENT >::~TwoLayerInterfaceProblem () inline
Destructor.
   {
    // Fluid timestepper
    delete this->time_stepper_pt(0);
    // Kill data associated with outer boundary
    unsigned n=Outer_boundary_polyline_pt->npolyline();
    for (unsigned j=0;j<n;j++)
     {
      delete Outer_boundary_polyline_pt->polyline_pt(j);
     }
    delete Outer_boundary_polyline_pt;
    // Flush element of free surface elements
    delete_free_surface_elements();
    delete Free_surface_mesh_pt;
    // Delete error estimator
    delete Fluid_mesh_pt->spatial_error_estimator_pt();
    // Delete fluid mesh
    delete Fluid_mesh_pt;
    // Delete the global pressure drop data
    delete Drop_pressure_data_pt;
    // Kill const eqn
    delete Problem_Parameter::Constitutive_law_pt;
   }
References Problem_Parameter::Constitutive_law_pt, j, and n.
Member Function Documentation
actions_after_adapt()
template<class ELEMENT > void TwoLayerInterfaceProblem< ELEMENT >::actions_after_adapt () inline virtual
Actions after adapt: Rebuild the mesh of free surface elements.
Reimplemented from oomph::Problem.
   {
    // Create the elements that impose the displacement constraint
    create_free_surface_elements();
    // Rebuild the Problem's global mesh from its various sub-meshes
    this->rebuild_global_mesh();
    // Setup the problem again -- remember that fluid mesh has been
    // completely rebuilt and its element's don't have any
    // pointers to Re etc. yet
    complete_problem_setup();
   }// end of actions_after_adapt
actions_after_newton_solve()
template<class ELEMENT > void TwoLayerInterfaceProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_adapt()
template<class ELEMENT > void TwoLayerInterfaceProblem< ELEMENT >::actions_before_adapt () inline virtual
Actions before adapt: Wipe the mesh of free surface elements.
Reimplemented from oomph::Problem.
   {
    // Kill the  elements and wipe surface mesh
    delete_free_surface_elements();
    // Rebuild the Problem's global mesh from its various sub-meshes
    this->rebuild_global_mesh();
   }// end of actions_before_adapt
actions_before_newton_solve()
template<class ELEMENT > void TwoLayerInterfaceProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve.
Reimplemented from oomph::Problem.
   {
    //Reset the Lagrangian coordinates of the nodes to be the current
    //Eulerian coordinates -- this makes the current configuration
    //stress free
    Fluid_mesh_pt->set_lagrangian_nodal_coordinates();
   }
complete_problem_setup()
template<class ELEMENT > void TwoLayerInterfaceProblem< ELEMENT >::complete_problem_setup
Set boundary conditions and complete the build of all elements.
   {
    // Re-set the boundary conditions for fluid problem: All nodes are
    // free by default -- just pin the ones that have Dirichlet conditions
    // here.
    unsigned nbound=Fluid_mesh_pt->nboundary();
    for(unsigned ibound=0;ibound<nbound;ibound++)
     {
      unsigned num_nod=Fluid_mesh_pt->nboundary_node(ibound);
      for (unsigned inod=0;inod<num_nod;inod++)
       {
        // Get node
        Node* nod_pt=Fluid_mesh_pt->boundary_node_pt(ibound,inod);
        //Pin both velocities on side boundaries (1 and 3)
        if((ibound==1) || (ibound==3))
         {
          nod_pt->pin(0);
          nod_pt->pin(1);
         }
        //If it's the inflow or outflow pin only the horizontal velocity
        if((ibound==0) || (ibound==2)) {nod_pt->pin(0);}
        // Pin horizontal pseudo-solid positions
        SolidNode* solid_node_pt = dynamic_cast<SolidNode*>(nod_pt);
        solid_node_pt->pin_position(0);
        //Pin the vertical position on the upper and lower walls
        if((ibound==1) || (ibound==3))
         {
          solid_node_pt->pin_position(1);
         }
        else
         {
          solid_node_pt->unpin_position(1);
         }
       } //End of loop over nodes
     } // end loop over boundaries
    // Complete the build of all elements so they are fully functional
    // Remember that adaptation for triangle meshes involves a complete
    // regneration of the mesh (rather than splitting as in tree-based
    // meshes where such parameters can be passed down from the father
    // element!)
    unsigned n_element = Fluid_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement to the present element
      ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Fluid_mesh_pt->element_pt(e));
      // Set the Reynolds number
      el_pt->re_pt() = &Problem_Parameter::Re;
      // Set the Womersley number (same as Re since St=1)
      el_pt->re_st_pt() = &Problem_Parameter::ReSt;
      // Set the product of the Reynolds number and the inverse of the
      // Froude number
      el_pt->re_invfr_pt() = &Problem_Parameter::ReInvFr;
      // Set the direction of gravity
      el_pt->g_pt() = &Problem_Parameter::G;
      // Set the constitutive law for pseudo-elastic mesh deformation
      el_pt->constitutive_law_pt()=Problem_Parameter::Constitutive_law_pt;
     }
    //For the elements in the upper region (region 0),
    //set the viscosity ratio
    n_element = Fluid_mesh_pt->nregion_element(1);
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement to the present element
      ELEMENT* el_pt =
       dynamic_cast<ELEMENT*>(Fluid_mesh_pt->region_element_pt(1,e));
      el_pt->viscosity_ratio_pt() = &Problem_Parameter::Viscosity_Ratio;
      el_pt->density_ratio_pt() = &Problem_Parameter::Density_Ratio;
     }
    // Re-apply boundary values on Dirichlet boundary conditions
    // (Boundary conditions are ignored when the solution is transferred
    // from the old to the new mesh by projection; this leads to a slight
    // change in the boundary values (which are, of course, never changed,
    // unlike the actual unknowns for which the projected values only
    // serve as an initial guess)
    // Set velocity and history values of velocity on walls
    nbound=this->Fluid_mesh_pt->nboundary();
    for(unsigned ibound=0;ibound<nbound;++ibound)
     {
      // Loop over nodes on this boundary
      unsigned num_nod=this->Fluid_mesh_pt->nboundary_node(ibound);
      for (unsigned inod=0;inod<num_nod;inod++)
       {
        // Get node
        Node* nod_pt=this->Fluid_mesh_pt->boundary_node_pt(ibound,inod);
        // Get number of previous (history) values
        unsigned n_prev=nod_pt->time_stepper_pt()->nprev_values();
        //If we are on the upper or lower walls
        // Velocity is and was zero at all previous times
        if((ibound==1) || (ibound==3))
         {
          //Loop over time history values
          for (unsigned t=0;t<=n_prev;t++)
           {
            nod_pt->set_value(t,0,0.0);
            nod_pt->set_value(t,1,0.0);
            // Nodes have always been there...
            nod_pt->x(t,0)=nod_pt->x(0,0);
            nod_pt->x(t,1)=nod_pt->x(0,1);
           }
         }
        //If we are on the side wals there is no horizontal velocity or
        //change in horizontal position
        if((ibound==0) || (ibound==2))
         {
          for (unsigned t=0;t<=n_prev;t++)
           {
            nod_pt->set_value(t,0,0.0);
            // Nodes have always been there...
            nod_pt->x(t,0)=nod_pt->x(0,0);
           }
         }
        //But there is a change in vertical position!
       }
     } //End of loop over boundaries
    fix_pressure(0,0,0.0);
   }
References Problem_Parameter::Constitutive_law_pt, Problem_Parameter::Density_Ratio, e(), Problem_Parameter::G, oomph::TimeStepper::nprev_values(), oomph::Data::pin(), oomph::SolidNode::pin_position(), Problem_Parameter::Re, Problem_Parameter::ReInvFr, Problem_Parameter::ReSt, oomph::Data::set_value(), plotPSD::t, oomph::Data::time_stepper_pt(), oomph::SolidNode::unpin_position(), Problem_Parameter::Viscosity_Ratio, and oomph::Node::x().
compute_error_estimate()
template<class ELEMENT > void TwoLayerInterfaceProblem< ELEMENT >::compute_error_estimate (double & max_err, double & min_err)
Compute the error estimates and assign to elements for plotting.
Compute error estimates and assign to elements for plotting.
 {
  // Get error estimator
  ErrorEstimator* err_est_pt=Fluid_mesh_pt->spatial_error_estimator_pt();
  // Get/output error estimates
  unsigned nel=Fluid_mesh_pt->nelement();
  Vector<double> elemental_error(nel);
  // We need a dynamic cast, get_element_errors from the Fluid_mesh_pt
  // Dynamic cast is used because get_element_errors require a Mesh* ans
  // not a SolidMesh*
  Mesh* fluid_mesh_pt=dynamic_cast<Mesh*>(Fluid_mesh_pt);
  err_est_pt->get_element_errors(fluid_mesh_pt,
                                 elemental_error);
  // Set errors for post-processing and find extrema
  max_err=0.0;
  min_err=DBL_MAX;
  for (unsigned e=0;e<nel;e++)
   {
    dynamic_cast<MyCrouzeixRaviartElement*>(Fluid_mesh_pt->element_pt(e))->
     set_error(elemental_error[e]);
    max_err=std::max(max_err,elemental_error[e]);
    min_err=std::min(min_err,elemental_error[e]);
   }
 }
References e(), oomph::ErrorEstimator::get_element_errors(), max, min, and set_error().
create_free_surface_elements()
template<class ELEMENT > void TwoLayerInterfaceProblem< ELEMENT >::create_free_surface_elements private
Create free surface elements.
Create elements that impose the kinematic and dynamic bcs for the pseudo-solid fluid mesh
 {
  //Loop over the free surface boundaries
  unsigned nb=Fluid_mesh_pt->nboundary();
  for(unsigned b=4;b<nb;b++)
   {
    // Note: region is important
    // How many bulk fluid elements are adjacent to boundary b in region 0?
    unsigned n_element = Fluid_mesh_pt->nboundary_element_in_region(b,0);
    // Loop over the bulk fluid elements adjacent to boundary b?
    for(unsigned e=0;e<n_element;e++)
     {
      // Get pointer to the bulk fluid element that is
      // adjacent to boundary b in region 0
      ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
       Fluid_mesh_pt->boundary_element_in_region_pt(b,0,e));
      //Find the index of the face of element e along boundary b in region 0
      int face_index = Fluid_mesh_pt->face_index_at_boundary_in_region(b,0,e);
      // Create new element
      ElasticLineFluidInterfaceElement<ELEMENT>* el_pt =
       new ElasticLineFluidInterfaceElement<ELEMENT>(
        bulk_elem_pt,face_index);
      // Add it to the mesh
      Free_surface_mesh_pt->add_element_pt(el_pt);
      //Add the appropriate boundary number
      el_pt->set_boundary_number_in_bulk_mesh(b);
      //Specify the Strouhal number
      el_pt->st_pt() = &Problem_Parameter::St;
      //Specify the capillary number
      el_pt->ca_pt() = &Problem_Parameter::Ca;
     }
   }
 }
References b, Problem_Parameter::Ca, oomph::FluidInterfaceElement::ca_pt(), e(), nb, oomph::FaceElement::set_boundary_number_in_bulk_mesh(), Problem_Parameter::St, and oomph::FluidInterfaceElement::st_pt().
deform_interface()
template<class ELEMENT > void TwoLayerInterfaceProblem< ELEMENT >::deform_interface (const double & epsilon, const unsigned & n_periods) inline
Function to deform the interface.
   {
    // Determine number of nodes in the "bulk" mesh
    const unsigned n_node = Fluid_mesh_pt->nnode();
  // Loop over all nodes in mesh
  for(unsigned n=0;n<n_node;n++)
   {
    // Determine eulerian position of node
    const double current_x_pos = Fluid_mesh_pt->node_pt(n)->x(0);
    const double current_y_pos = Fluid_mesh_pt->node_pt(n)->x(1);
    // Determine new vertical position of node
    const double new_y_pos = current_y_pos
     + (1.0-fabs(1.0-current_y_pos))*epsilon
     *(cos(2.0*n_periods*MathematicalConstants::Pi*current_x_pos/Problem_Parameter::Length));
    // Set new position
    Fluid_mesh_pt->node_pt(n)->x(1) = new_y_pos;
   }
 } // End of deform_interface
References cos(), oomph::SarahBL::epsilon, boost::multiprecision::fabs(), Problem_Parameter::Length, n, and BiharmonicTestFunctions2::Pi.
delete_free_surface_elements()
template<class ELEMENT > void TwoLayerInterfaceProblem< ELEMENT >::delete_free_surface_elements () inline private
Delete free surface elements.
   {
    // How many surface elements are in the surface mesh
    unsigned n_element = Free_surface_mesh_pt->nelement();
    // Loop over the surface elements
    for(unsigned e=0;e<n_element;e++)
     {
      // Kill surface element
      delete Free_surface_mesh_pt->element_pt(e);
     }
    // Wipe the mesh
    Free_surface_mesh_pt->flush_element_and_node_storage();
   } // end of delete_free_surface_elements
References e().
doc_solution()
template<class ELEMENT > void TwoLayerInterfaceProblem< ELEMENT >::doc_solution (const std::string & comment = "")
Doc the solution.
 {
  // Output the time
  cout << "Time is now " << time_pt()->time() << std::endl;
  double min_x_coordinate = 2.0;
  unsigned min_boundary_node = 0;
  //Find the left-most node on the boundary
  unsigned n_bound = Fluid_mesh_pt->nboundary_node(4);
  for(unsigned n=0;n<n_bound;++n)
   {
    Node* nod_pt = Fluid_mesh_pt->boundary_node_pt(4,n);
    if(nod_pt->x(0) < min_x_coordinate)
     {
      min_x_coordinate = nod_pt->x(0);
      min_boundary_node = n;
     }
   }
  // Document time and vertical position of left hand side of interface
  // in trace file
  Problem_Parameter::Trace_file
   << time_pt()->time() << " "
   << Fluid_mesh_pt->boundary_node_pt(4,min_boundary_node)->x(1) << std::endl;
  ofstream some_file;
  char filename[100];
  // Set number of plot points (in each coordinate direction)
  const unsigned npts = 5;
  // Open solution output file
  sprintf(filename,"%s/soln%i.dat",
          Problem_Parameter::Doc_info.directory().c_str(),
          Problem_Parameter::Doc_info.number());
  some_file.open(filename);
  // Output solution to file
  Fluid_mesh_pt->output(some_file,npts);
  // Close solution output file
  some_file.close();
  // Open interface solution output file
  sprintf(filename,"%s/interface_soln%i.dat",
          Problem_Parameter::Doc_info.directory().c_str(),
          Problem_Parameter::Doc_info.number());
  some_file.open(filename);
  // Output solution to file
  Free_surface_mesh_pt->output(some_file,npts);
  // Close solution output file
  some_file.close();
  // Increment the doc_info number
  Problem_Parameter::Doc_info.number()++;
 }
References Problem_Parameter::Doc_info, MergeRestartFiles::filename, n, oomph::DocInfo::number(), Problem_Parameter::Trace_file, and oomph::Node::x().
fix_pressure()
template<class ELEMENT > void TwoLayerInterfaceProblem< ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    // Fix the pressure at that element
    dynamic_cast<ELEMENT*>(Fluid_mesh_pt->element_pt(e))->
                           fix_pressure(pdof,pvalue);
   }
References e().
set_initial_condition()
template<class ELEMENT > void TwoLayerInterfaceProblem< ELEMENT >::set_initial_condition () inline virtual
Set the initial conditions.
Reimplemented from oomph::Problem.
 {
  // Determine number of nodes in mesh
  const unsigned n_node = Fluid_mesh_pt->nnode();
  // Loop over all nodes in mesh
  for(unsigned n=0;n<n_node;n++)
   {
    // Loop over the two velocity components
    for(unsigned i=0;i<2;i++)
     {
      // Set velocity component i of node n to zero
      Fluid_mesh_pt->node_pt(n)->set_value(i,0.0);
     }
   }
  // Initialise the previous velocity values for timestepping
  // corresponding to an impulsive start
  assign_initial_values_impulsive();
 } // End of set_initial_condition
References i, and n.
Member Data Documentation
Drop_polygon_pt
template<class ELEMENT > Vector<TriangleMeshPolygon*> TwoLayerInterfaceProblem< ELEMENT >::Drop_polygon_pt private
Vector storing pointer to the drop polygons.
Drop_pressure_data_pt
template<class ELEMENT > Data* TwoLayerInterfaceProblem< ELEMENT >::Drop_pressure_data_pt private
Pointer to a global drop pressure datum.
Fluid_mesh_pt
template<class ELEMENT > RefineableSolidTriangleMesh<ELEMENT>* TwoLayerInterfaceProblem< ELEMENT >::Fluid_mesh_pt private
Pointer to Fluid_mesh.
Free_surface_mesh_pt
template<class ELEMENT > Mesh* TwoLayerInterfaceProblem< ELEMENT >::Free_surface_mesh_pt private
Pointers to mesh of free surface elements.
Hijacked_element_pt
template<class ELEMENT > ELEMENT* TwoLayerInterfaceProblem< ELEMENT >::Hijacked_element_pt private
Pointer to hijacked element.
Initial_value_for_drop_pressure
template<class ELEMENT > double TwoLayerInterfaceProblem< ELEMENT >::Initial_value_for_drop_pressure private
Backed up drop pressure between adaptations.
Outer_boundary_polyline_pt
template<class ELEMENT > TriangleMeshPolygon* TwoLayerInterfaceProblem< ELEMENT >::Outer_boundary_polyline_pt private
Triangle mesh polygon for outer boundary.
Use_volume_constraint
template<class ELEMENT > bool TwoLayerInterfaceProblem< ELEMENT >::Use_volume_constraint private
Bool to indicate if volume constraint is applied (only for steady run)
The documentation for this class was generated from the following file:
refineable_two_layer_interface.cc