MercuryDPM: oomph::TriangleMesh< ELEMENT > Class Template Reference
oomph::TriangleMesh< ELEMENT > Class Template Reference
#include <triangle_mesh.template.h>
Classes
struct Point
Public Member Functions
TriangleMesh ()
Empty constructor.
TriangleMesh (const std::string &node_file_name, const std::string &element_file_name, const std::string &poly_file_name, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &allow_automatic_creation_of_vertices_on_boundaries=true)
Constructor with the input files.
void output_boundary_coordinates (const unsigned &b, std::ostream &outfile)
Public Member Functions inherited from oomph::TriangleMeshBase
TriangleMeshBase ()
Constructor.
TriangleMeshBase (const TriangleMeshBase &node)=delete
Broken copy constructor.
virtual ~TriangleMeshBase ()
Broken assignment operator.
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
virtual void load_balance (const Vector< unsigned > &target_domain_for_local_non_halo_element)
Virtual function to perform the load balance rutines.
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
Public Member Functions inherited from oomph::UnstructuredTwoDMeshGeometryBase
UnstructuredTwoDMeshGeometryBase ()
Empty constructor.
UnstructuredTwoDMeshGeometryBase (const UnstructuredTwoDMeshGeometryBase &dummy)=delete
Broken copy constructor.
void operator= (const UnstructuredTwoDMeshGeometryBase &)=delete
Broken assignment operator.
~UnstructuredTwoDMeshGeometryBase ()
Empty destructor.
unsigned nregion ()
Return the number of regions specified by attributes.
unsigned nregion_element (const unsigned &i)
Return the number of elements in the i-th region.
FiniteElement * region_element_pt (const unsigned &i, const unsigned &e)
Return the e-th element in the i-th region.
unsigned nregion_attribute ()
Return the number of attributes used in the mesh.
double region_attribute (const unsigned &i)
Return the attribute associated with region i.
GeomObject * boundary_geom_object_pt (const unsigned &b)
std::map< unsigned, GeomObject * > & boundary_geom_object_pt ()
Return direct access to the geometric object storage.
std::map< unsigned, Vector< double > > & boundary_coordinate_limits ()
Vector< double > & boundary_coordinate_limits (const unsigned &b)
unsigned nboundary_element_in_region (const unsigned &b, const unsigned &r) const
Return the number of elements adjacent to boundary b in region r.
FiniteElement * boundary_element_in_region_pt (const unsigned &b, const unsigned &r, const unsigned &e) const
Return pointer to the e-th element adjacent to boundary b in region r.
int face_index_at_boundary_in_region (const unsigned &b, const unsigned &r, const unsigned &e) const
Return face index of the e-th element adjacent to boundary b in region r.
TriangleMeshPolyLine * boundary_polyline_pt (const unsigned &b)
std::map< unsigned, std::set< Node * > > & nodes_on_boundary_pt ()
const bool get_connected_vertex_number_on_destination_polyline (TriangleMeshPolyLine *dst_polyline_pt, Vector< double > &vertex_coordinates, unsigned &vertex_number)
void check_contiguousness_on_polylines_helper (Vector< TriangleMeshPolyLine * > &polylines_pt, unsigned &index)
void check_contiguousness_on_polylines_helper (Vector< TriangleMeshPolyLine * > &polylines_pt, unsigned &index_halo_start, unsigned &index_halo_end)
bool is_point_inside_polygon_helper (Vector< Vector< double >> polygon_vertices, Vector< double > point)
Helper function that checks if a given point is inside a polygon.
void enable_automatic_creation_of_vertices_on_boundaries ()
void disable_automatic_creation_of_vertices_on_boundaries ()
bool is_automatic_creation_of_vertices_on_boundaries_allowed ()
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, std::ofstream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Protected Member Functions
TriangleMesh (const TriangleMesh &dummy)=delete
Broken copy constructor.
void operator= (const TriangleMesh &)=delete
Broken assignment operator.
virtual ~TriangleMesh ()
Destructor.
void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Vector< unsigned > oomph_vertex_nodes_id ()
void build_from_scaffold (TimeStepper *time_stepper_pt, const bool &use_attributes)
Build mesh from scaffold.
Protected Member Functions inherited from oomph::UnstructuredTwoDMeshGeometryBase
void snap_nodes_onto_geometric_objects ()
void copy_connection_information (TriangleMeshCurveSection *input_curve_pt, TriangleMeshCurveSection *output_curve_pt)
void copy_connection_information_to_sub_polylines (TriangleMeshCurveSection *input_curve_pt, TriangleMeshCurveSection *output_curve_pt)
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes
TimeStepper * Time_stepper_pt
Timestepper used to build elements.
bool Use_attributes
std::map< unsigned, double > Regions_areas
TriangleScaffoldMesh * Tmp_mesh_pt
Temporary scaffold mesh.
Vector< unsigned > Oomph_vertex_nodes_id
Protected Attributes inherited from oomph::UnstructuredTwoDMeshGeometryBase
bool Allow_automatic_creation_of_vertices_on_boundaries
std::map< unsigned, Vector< FiniteElement * > > Region_element_pt
Vector< double > Region_attribute
Vector of attributes associated with the elements in each region.
std::map< unsigned, GeomObject * > Boundary_geom_object_pt
Storage for the geometric objects associated with any boundaries.
std::map< unsigned, Vector< double > > Boundary_coordinate_limits
Vector< TriangleMeshPolygon * > Outer_boundary_pt
Polygon that defines outer boundaries.
Vector< TriangleMeshPolygon * > Internal_polygon_pt
Vector of polygons that define internal polygons.
Vector< TriangleMeshOpenCurve * > Internal_open_curve_pt
Vector of open polylines that define internal curves.
Vector< Vector< double > > Extra_holes_coordinates
Storage for extra coordinates for holes.
std::map< unsigned, Vector< double > > Regions_coordinates
std::map< unsigned, TriangleMeshCurveSection * > Boundary_curve_section_pt
Vector< std::map< unsigned, Vector< FiniteElement * > > > Boundary_region_element_pt
Storage for elements adjacent to a boundary in a particular region.
Vector< std::map< unsigned, Vector< int > > > Face_index_region_at_boundary
Storage for the face index adjacent to a boundary in a particular region.
std::map< unsigned, Vector< std::pair< double, double > > > Polygonal_vertex_arclength_info
std::map< unsigned, std::set< Node * > > Nodes_on_boundary_pt
std::set< TriangleMeshCurveSection * > Free_curve_section_pt
std::set< TriangleMeshPolygon * > Free_polygon_pt
std::set< TriangleMeshOpenCurve * > Free_open_curve_pt
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Private Types
typedef double coord_t
typedef double coord2_t
Private Member Functions
coord2_t cross (const Point &O, const Point &A, const Point &B)
std::vector< Point > convex_hull (std::vector< Point > P)
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::UnstructuredTwoDMeshGeometryBase
static bool Suppress_warning_about_regions_and_boundaries
Public static flag to suppress warning; defaults to false.
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Detailed Description
template<class ELEMENT>
class oomph::TriangleMesh< ELEMENT >
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Triangle mesh build with the help of the scaffold mesh coming from the triangle mesh generator Triangle. http://www.cs.cmu.edu/~quake/triangle.html
Member Typedef Documentation
coord2_t
template<class ELEMENT > typedef double oomph::TriangleMesh< ELEMENT >::coord2_t private
coord_t
template<class ELEMENT > typedef double oomph::TriangleMesh< ELEMENT >::coord_t private
Constructor & Destructor Documentation
TriangleMesh() [1/3]
template<class ELEMENT > oomph::TriangleMesh< ELEMENT >::TriangleMesh () inline
Empty constructor.
     {
 #ifdef OOMPH_HAS_TRIANGLE_LIB
       // Using this constructor no Triangulateio object is built
       Triangulateio_exists = false;
       // By default allow the automatic creation of vertices along the
       // boundaries by Triangle
       this->Allow_automatic_creation_of_vertices_on_boundaries = true;
 #ifdef OOMPH_HAS_MPI
       // Initialize the flag to indicate this is the first time to
       // compute the holes left by the halo elements
       First_time_compute_holes_left_by_halo_elements = true;
 #endif // #ifdef OOMPH_HAS_MPI
 #endif
       // Mesh can only be built with 2D Telements.
       MeshChecker::assert_geometric_element<TElementGeometricBase, ELEMENT>(2);
     }
References oomph::UnstructuredTwoDMeshGeometryBase::Allow_automatic_creation_of_vertices_on_boundaries.
TriangleMesh() [2/3]
template<class ELEMENT > oomph::TriangleMesh< ELEMENT >::TriangleMesh (const std::string & node_file_name, const std::string & element_file_name, const std::string & poly_file_name, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & allow_automatic_creation_of_vertices_on_boundaries = true) inline
Constructor with the input files.
     {
       // Mesh can only be built with 2D Telements.
       MeshChecker::assert_geometric_element<TElementGeometricBase, ELEMENT>(2);
       // Initialize the value for allowing creation of points on boundaries
       this->Allow_automatic_creation_of_vertices_on_boundaries =
         allow_automatic_creation_of_vertices_on_boundaries;
 #ifdef OOMPH_HAS_MPI
       // Initialize the flag to indicate this is the first time to
       // compute the holes left by the halo elements
       First_time_compute_holes_left_by_halo_elements = true;
 #endif // #ifdef OOMPH_HAS_MPI
       // Store Timestepper used to build elements
       Time_stepper_pt = time_stepper_pt;
       // Check if we should use attributes. This is set to true if the .poly
       // file specifies regions
       bool should_use_attributes = false;
 #ifdef OOMPH_HAS_TRIANGLE_LIB
       // Using this constructor build the triangulatio
       TriangleHelper::create_triangulateio_from_polyfiles(
         node_file_name,
         element_file_name,
         poly_file_name,
         Triangulateio,
         should_use_attributes);
       // Record that the triangulateio object has been created
       Triangulateio_exists = true;
 #endif
       // Store the attributes
       Use_attributes = should_use_attributes;
       // Build scaffold
       this->Tmp_mesh_pt = new TriangleScaffoldMesh(
         node_file_name, element_file_name, poly_file_name);
       // Convert mesh from scaffold to actual mesh
       build_from_scaffold(time_stepper_pt, should_use_attributes);
       // kill the scaffold
       delete this->Tmp_mesh_pt;
       this->Tmp_mesh_pt = 0;
       // Setup boundary coordinates for boundaries
       unsigned nb = nboundary();
       for (unsigned b = 0; b < nb; b++)
       {
         this->template setup_boundary_coordinates<ELEMENT>(b);
       }
     }
References oomph::UnstructuredTwoDMeshGeometryBase::Allow_automatic_creation_of_vertices_on_boundaries, b, oomph::TriangleMesh< ELEMENT >::build_from_scaffold(), nb, oomph::Mesh::nboundary(), oomph::TriangleMesh< ELEMENT >::Time_stepper_pt, oomph::TriangleMesh< ELEMENT >::Tmp_mesh_pt, and oomph::TriangleMesh< ELEMENT >::Use_attributes.
TriangleMesh() [3/3]
template<class ELEMENT > oomph::TriangleMesh< ELEMENT >::TriangleMesh (const TriangleMesh< ELEMENT > & dummy) protected delete
Broken copy constructor.
~TriangleMesh()
template<class ELEMENT > virtual oomph::TriangleMesh< ELEMENT >::~TriangleMesh () inline protected virtual
Destructor.
     {
 #ifdef OOMPH_HAS_TRIANGLE_LIB
       if (Triangulateio_exists)
       {
         TriangleHelper::clear_triangulateio(Triangulateio);
       }
       std::set<TriangleMeshCurveSection*>::iterator it_polyline;
       for (it_polyline = Free_curve_section_pt.begin();
            it_polyline != Free_curve_section_pt.end();
            it_polyline++)
       {
         delete (*it_polyline);
       }
       std::set<TriangleMeshPolygon*>::iterator it_polygon;
       for (it_polygon = Free_polygon_pt.begin();
            it_polygon != Free_polygon_pt.end();
            it_polygon++)
       {
         delete (*it_polygon);
       }
       std::set<TriangleMeshOpenCurve*>::iterator it_open_polyline;
       for (it_open_polyline = Free_open_curve_pt.begin();
            it_open_polyline != Free_open_curve_pt.end();
            it_open_polyline++)
       {
         delete (*it_open_polyline);
       }
 #endif
     }
References oomph::UnstructuredTwoDMeshGeometryBase::Free_curve_section_pt, oomph::UnstructuredTwoDMeshGeometryBase::Free_open_curve_pt, and oomph::UnstructuredTwoDMeshGeometryBase::Free_polygon_pt.
Member Function Documentation
build_from_scaffold()
template<class ELEMENT > void TriangleMesh::build_from_scaffold (TimeStepper * time_stepper_pt, const bool & use_attributes) protected
Build mesh from scaffold.
Build with the help of the scaffold mesh coming from the triangle mesh generator Triangle.
   {
     // Mesh can only be built with 2D Telements.
     MeshChecker::assert_geometric_element<TElementGeometricBase, ELEMENT>(2);
     // Create space for elements
     unsigned nelem = Tmp_mesh_pt->nelement();
     Element_pt.resize(nelem);
     // Create space for nodes
     unsigned nnode_scaffold = Tmp_mesh_pt->nnode();
     // Create a map storing the node_id of the mesh used to update the
     // node position in the update_triangulateio function
     std::map<Node*, unsigned> old_global_number;
     // Store the TriangulateIO node id
     for (unsigned inod = 0; inod < nnode_scaffold; inod++)
     {
       Node* old_node_pt = Tmp_mesh_pt->node_pt(inod);
       old_global_number[old_node_pt] = inod;
     }
     // Initialize the old node id vector
     Oomph_vertex_nodes_id.resize(nnode_scaffold);
     // Create space for nodes
     Node_pt.resize(nnode_scaffold, 0);
     // Set number of boundaries
     unsigned nbound = Tmp_mesh_pt->nboundary();
     // Resize the boundary information
     set_nboundary(nbound);
     Boundary_element_pt.resize(nbound);
     Face_index_at_boundary.resize(nbound);
     // If we have different regions, then resize the region
     // information
     if (use_attributes)
     {
       Boundary_region_element_pt.resize(nbound);
       Face_index_region_at_boundary.resize(nbound);
     }
     // Loop over elements in scaffold mesh, visit their nodes
     for (unsigned e = 0; e < nelem; e++)
     {
       Element_pt[e] = new ELEMENT;
     }
     // Number of nodes per element from the scaffold mesh
     unsigned nnod_el = Tmp_mesh_pt->finite_element_pt(0)->nnode();
     // Setup map to check the (pseudo-)global node number
     // Nodes whose number is zero haven't been copied across
     // into the mesh yet.
     std::map<Node*, unsigned> global_number;
     unsigned global_count = 0;
     // Map of Element attribute pairs
     std::map<double, Vector<FiniteElement*>> element_attribute_map;
     // If we're using attributes
     if (use_attributes)
     {
       // If we're using attributes then we need attribute 0 which will
       // be associated with region 0
       element_attribute_map[0].resize(0);
     }
     // Loop over elements in scaffold mesh, visit their nodes
     for (unsigned e = 0; e < nelem; e++)
     {
       // Loop over all nodes in element
       for (unsigned j = 0; j < nnod_el; j++)
       {
         // Pointer to node in the scaffold mesh
         Node* scaffold_node_pt = Tmp_mesh_pt->finite_element_pt(e)->node_pt(j);
         // Get the (pseudo-)global node number in scaffold mesh
         // (It's zero [=default] if not visited this one yet)
         unsigned j_global = global_number[scaffold_node_pt];
         // Haven't done this one yet
         if (j_global == 0)
         {
           // Find and store the node_id in the old nodes map
           Oomph_vertex_nodes_id[global_count] =
             old_global_number[scaffold_node_pt];
           // Get pointer to set of mesh boundaries that this
           // scaffold node occupies; NULL if the node is not on any boundary
           std::set<unsigned>* boundaries_pt;
           scaffold_node_pt->get_boundaries_pt(boundaries_pt);
           // Storage for the new node
           Node* new_node_pt = 0;
           // Is it on boundaries
           if (boundaries_pt != 0)
           {
             // Create new boundary node
             new_node_pt =
               finite_element_pt(e)->construct_boundary_node(j, time_stepper_pt);
             // Add to boundaries
             for (std::set<unsigned>::iterator it = boundaries_pt->begin();
                  it != boundaries_pt->end();
                  ++it)
             {
               add_boundary_node(*it, new_node_pt);
             }
           }
           // Build normal node
           else
           {
             // Create new normal node
             new_node_pt =
               finite_element_pt(e)->construct_node(j, time_stepper_pt);
           }
           // Give it a number (not necessarily the global node
           // number in the scaffold mesh -- we just need something
           // to keep track...)
           global_count++;
           global_number[scaffold_node_pt] = global_count;
           // Copy new node, created using the NEW element's construct_node
           // function into global storage, using the same global
           // node number that we've just associated with the
           // corresponding node in the scaffold mesh
           Node_pt[global_count - 1] = new_node_pt;
           // Assign coordinates
           for (unsigned i = 0; i < finite_element_pt(e)->dim(); i++)
           {
             new_node_pt->x(i) = scaffold_node_pt->x(i);
           }
         }
         // This one has already been done: Copy accross
         else
         {
           finite_element_pt(e)->node_pt(j) = Node_pt[j_global - 1];
         }
       }
       // If we're using attributes
       if (use_attributes)
       {
         element_attribute_map[Tmp_mesh_pt->element_attribute(e)].push_back(
           finite_element_pt(e));
       }
     }
     // Now let's construct lists
     // Find the number of attributes
     if (use_attributes)
     {
       unsigned n_attribute = element_attribute_map.size();
       // There are n_attribute different regions
       this->Region_attribute.resize(n_attribute);
       // Copy the vectors in the map over to our internal storage
       unsigned count = 0;
       for (std::map<double, Vector<FiniteElement*>>::iterator it =
              element_attribute_map.begin();
            it != element_attribute_map.end();
            ++it)
       {
         this->Region_attribute[count] = it->first;
         Region_element_pt[static_cast<unsigned>(Region_attribute[count])] =
           it->second;
         ++count;
       }
     }
     // At this point we've created all the elements and
     // created their vertex nodes. Now we need to create
     // the additional (midside and internal) nodes!
     unsigned boundary_id = 0;
     // Get number of nodes along element edge and dimension of element (2)
     // from first element
     unsigned n_node_1d = finite_element_pt(0)->nnode_1d();
     unsigned dim = finite_element_pt(0)->dim();
     // Storage for the local coordinate of the new node
     Vector<double> s(dim);
     // Get number of nodes in the element from first element
     unsigned n_node = finite_element_pt(0)->nnode();
     // Storage for each global edge of the mesh
     unsigned n_global_edge = Tmp_mesh_pt->nglobal_edge();
     Vector<Vector<Node*>> nodes_on_global_edge(n_global_edge);
     // Loop over elements
     for (unsigned e = 0; e < nelem; e++)
     {
       // Cache pointers to the elements
       FiniteElement* const elem_pt = finite_element_pt(e);
       FiniteElement* const tmp_elem_pt = Tmp_mesh_pt->finite_element_pt(e);
       // The number of edge nodes is  3*(nnode_1d-1)
       unsigned n_edge_node = 3 * (n_node_1d - 1);
       // If there are any more nodes, these are internal and can be
       // constructed and added directly to the mesh
       for (unsigned n = n_edge_node; n < n_node; ++n)
       {
         // Create new node (it can never be a boundary node)
         Node* new_node_pt = elem_pt->construct_node(n, time_stepper_pt);
         // What are the node's local coordinates?
         elem_pt->local_coordinate_of_node(n, s);
         // Find the coordinates of the new node from the existing
         // and fully-functional element in the scaffold mesh
         for (unsigned i = 0; i < dim; i++)
         {
           new_node_pt->x(i) = tmp_elem_pt->interpolated_x(s, i);
         }
         // Add the node to the mesh's global look-up scheme
         Node_pt.push_back(new_node_pt);
       }
       // Now loop over the mid-side edge nodes
       // Start from node number 3
       unsigned n = 3;
       // Loop over edges
       for (unsigned j = 0; j < 3; j++)
       {
         // Find the boundary id of the edge
         boundary_id = Tmp_mesh_pt->edge_boundary(e, j);
         // Find the global edge index
         unsigned edge_index = Tmp_mesh_pt->edge_index(e, j);
         // If the nodes on the edge have not been allocated, construct them
         if (nodes_on_global_edge[edge_index].size() == 0)
         {
           // Loop over the nodes on the edge excluding the ends
           for (unsigned j2 = 0; j2 < n_node_1d - 2; ++j2)
           {
             // Storage for the new node
             Node* new_node_pt = 0;
             // If the edge is on a boundary, construct a boundary node
             if (boundary_id > 0)
             {
               new_node_pt =
                 elem_pt->construct_boundary_node(n, time_stepper_pt);
               // Add it to the boundary
               this->add_boundary_node(boundary_id - 1, new_node_pt);
             }
             // Otherwise construct a normal node
             else
             {
               new_node_pt = elem_pt->construct_node(n, time_stepper_pt);
             }
             // What are the node's local coordinates?
             elem_pt->local_coordinate_of_node(n, s);
             // Find the coordinates of the new node from the existing
             // and fully-functional element in the scaffold mesh
             for (unsigned i = 0; i < dim; i++)
             {
               new_node_pt->x(i) = tmp_elem_pt->interpolated_x(s, i);
             }
             // Add to the global node list
             Node_pt.push_back(new_node_pt);
             // Add to the edge index
             nodes_on_global_edge[edge_index].push_back(new_node_pt);
             // Increment the node number
             ++n;
           }
         }
         // Otherwise just set the pointers
         // using the fact that the next time the edge is visited
         // the nodes must be arranged in the other order because all
         // triangles have the same orientation
         else
         {
           // Loop over the nodes on the edge excluding the ends
           for (unsigned j2 = 0; j2 < n_node_1d - 2; ++j2)
           {
             // Set the local node from the edge but indexed the other
             // way around
             elem_pt->node_pt(n) =
               nodes_on_global_edge[edge_index][n_node_1d - 3 - j2];
             ++n;
           }
         }
         // Set the elements adjacent to the boundary from the
         // boundary id information
         if (boundary_id > 0)
         {
           Boundary_element_pt[boundary_id - 1].push_back(elem_pt);
           // Need to put a shift in here because of an inconsistent naming
           // convention between triangle and face elements
           Face_index_at_boundary[boundary_id - 1].push_back((j + 2) % 3);
           // If using regions set up the boundary information
           if (use_attributes)
           {
             unsigned tmp_region =
               static_cast<unsigned>(Tmp_mesh_pt->element_attribute(e));
             // Element adjacent to boundary
             Boundary_region_element_pt[boundary_id - 1][tmp_region].push_back(
               elem_pt);
             // Need to put a shift in here because of an inconsistent naming
             // convention between triangle and face elements
             Face_index_region_at_boundary[boundary_id - 1][tmp_region]
               .push_back((j + 2) % 3);
           }
         }
       } // end of loop over edges
     } // end of loop over elements
     // Lookup scheme has now been setup
     Lookup_for_elements_next_boundary_is_setup = true;
   }
References oomph::FiniteElement::construct_boundary_node(), oomph::FiniteElement::construct_node(), e(), oomph::Node::get_boundaries_pt(), i, oomph::FiniteElement::interpolated_x(), j, oomph::FiniteElement::local_coordinate_of_node(), n, oomph::FiniteElement::node_pt(), oomph::Node::resize(), s, size, and oomph::Node::x().
Referenced by oomph::TriangleMesh< ELEMENT >::TriangleMesh().
convex_hull()
template<class ELEMENT > std::vector<Point> oomph::TriangleMesh< ELEMENT >::convex_hull (std::vector< Point > P) inline private
Returns a list of points on the convex hull in counter-clockwise order. Note: the last point in the returned list is the same as the first one.
     {
       int n = P.size(), k = 0;
       std::vector<Point> H(2 * n);
       // Sort points lexicographically
       std::sort(P.begin(), P.end());
       // Build lower hull
       for (int i = 0; i < n; ++i)
       {
         while (k >= 2 && cross(H[k - 2], H[k - 1], P[i]) <= 0) k--;
         H[k++] = P[i];
       }
       // Build upper hull
       for (int i = n - 2, t = k + 1; i >= 0; i--)
       {
         while (k >= t && cross(H[k - 2], H[k - 1], P[i]) <= 0) k--;
         H[k++] = P[i];
       }
       H.resize(k);
       return H;
     }
References oomph::TriangleMesh< ELEMENT >::cross(), H, i, k, n, Global_Physical_Variables::P, and plotPSD::t.
cross()
template<class ELEMENT > coord2_t oomph::TriangleMesh< ELEMENT >::cross (const Point & O, const Point & A, const Point & B) inline private
2D cross product of OA and OB vectors, i.e. z-component of their 3D cross product. Returns a positive value, if OAB makes a counter-clockwise turn, negative for clockwise turn, and zero if the points are collinear.
     {
       return (A.x - O.x) * (B.y - O.y) - (A.y - O.y) * (B.x - O.x);
     }
Referenced by oomph::TriangleMesh< ELEMENT >::convex_hull().
oomph_vertex_nodes_id()
template<class ELEMENT > Vector<unsigned> oomph::TriangleMesh< ELEMENT >::oomph_vertex_nodes_id () inline protected
Return the vector that contains the oomph-lib node number for all vertex nodes in the TriangulateIO representation of the mesh
     {
       return Oomph_vertex_nodes_id;
     }
References oomph::TriangleMesh< ELEMENT >::Oomph_vertex_nodes_id.
operator=()
template<class ELEMENT > void oomph::TriangleMesh< ELEMENT >::operator= (const TriangleMesh< ELEMENT > &) protected delete
Broken assignment operator.
output_boundary_coordinates()
template<class ELEMENT > void TriangleMesh::output_boundary_coordinates (const unsigned & b, std::ostream & outfile)
Output the nodes on the boundary and their respective boundary coordinates(into separate tecplot zones)
   {
     // First get all the elements adjacent to the given boundary, then
     // the face elements and extract the nodes on the boundaries using
     // the face elements. We can not use the data structure
     // Boundary_node_pt since the multi_domain functions add nodes there
     // without assigning the required boundary coordinate
     // Store the nodes in a set so we do not have repeated nodes
     std::set<Node*> boundary_nodes_pt;
     const unsigned n_boundary_ele = this->nboundary_element(b);
     for (unsigned e = 0; e < n_boundary_ele; e++)
     {
       // Get the boundary bulk element
       FiniteElement* bulk_ele_pt = this->boundary_element_pt(b, e);
 #ifdef OOMPH_HAS_MPI
       // Only work with nonhalo elements if the mesh is distributed
       if (!bulk_ele_pt->is_halo())
       {
 #endif
         // Get the face index
         int face_index = this->face_index_at_boundary(b, e);
         // Create the face element
         FiniteElement* face_ele_pt =
           new DummyFaceElement<ELEMENT>(bulk_ele_pt, face_index);
         // Get the number of nodes on the face element
         const unsigned n_nodes = face_ele_pt->nnode();
         for (unsigned i = 0; i < n_nodes; i++)
         {
           // Get the nodes in the face elements
           Node* tmp_node_pt = face_ele_pt->node_pt(i);
           // Add the nodes to the set of boundary nodes
           boundary_nodes_pt.insert(tmp_node_pt);
         } // for (i < n_nodes)
         // Free the memory allocated for the face element
         delete face_ele_pt;
         face_ele_pt = 0;
 #ifdef OOMPH_HAS_MPI
       } // if (!bulk_ele_pt->is_halo())
 #endif
     } // for (e < n_boundary_ele)
     outfile << "ZONE T=\"Boundary nodes" << b << "\"\n";
     // Set to store the boundary nodes in order
     std::set<Vector<double>> set_node_coord;
     // Loop over the nodes on the boundary and store them in the set
     for (std::set<Node*>::iterator it = boundary_nodes_pt.begin();
          it != boundary_nodes_pt.end();
          it++)
     {
       Node* inode_pt = (*it);
       // Get the node coordinates
       const unsigned n_dim = inode_pt->ndim();
       Vector<double> node_coord(n_dim + 1);
       // Get the boundary coordinate
       Vector<double> zeta(1);
       inode_pt->get_coordinates_on_boundary(b, zeta);
       node_coord[0] = zeta[0];
       for (unsigned j = 0; j < n_dim; j++)
       {
         node_coord[j + 1] = inode_pt->x(j);
       }
       set_node_coord.insert(node_coord);
     }
     for (std::set<Vector<double>>::iterator it = set_node_coord.begin();
          it != set_node_coord.end();
          it++)
     {
       // Get the node coordinates
       Vector<double> node_coord = (*it);
       // Output the node coordinates
       const unsigned n_dim = node_coord.size() - 1;
       for (unsigned j = 0; j < n_dim; j++)
       {
         outfile << node_coord[j + 1] << " ";
       }
       // ... add an extra coordinate to avoid error with tecplot
       outfile << "0.0" << std::endl;
     }
     // ... loop again to plot the bound coordinates
     outfile << "ZONE T=\"Boundary coordinates " << b << "\"\n";
     for (std::set<Vector<double>>::iterator it = set_node_coord.begin();
          it != set_node_coord.end();
          it++)
     {
       // Get the node coordinates
       Vector<double> node_coord = (*it);
       // Output the node coordinates
       const unsigned n_dim = node_coord.size() - 1;
       for (unsigned j = 0; j < n_dim; j++)
       {
         outfile << node_coord[j + 1] << " ";
       }
       // Output the boundary coordinate
       outfile << node_coord[0] << std::endl;
     }
   }
References b, e(), oomph::Node::get_coordinates_on_boundary(), i, j, oomph::Node::ndim(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), set(), oomph::Node::x(), and Eigen::zeta().
set_mesh_level_time_stepper()
template<class ELEMENT > void oomph::TriangleMesh< ELEMENT >::set_mesh_level_time_stepper (TimeStepper *const & time_stepper_pt, const bool & preserve_existing_data) inline protected virtual
Overload set_mesh_level_time_stepper so that the stored time stepper now corresponds to the new timestepper
Reimplemented from oomph::Mesh.
     {
       this->Time_stepper_pt = time_stepper_pt;
     }
References oomph::TriangleMesh< ELEMENT >::Time_stepper_pt.
Member Data Documentation
Oomph_vertex_nodes_id
template<class ELEMENT > Vector<unsigned> oomph::TriangleMesh< ELEMENT >::Oomph_vertex_nodes_id protected
Vector storing oomph-lib node number for all vertex nodes in the TriangulateIO representation of the mesh
Referenced by oomph::TriangleMesh< ELEMENT >::oomph_vertex_nodes_id().
Regions_areas
template<class ELEMENT > std::map<unsigned, double> oomph::TriangleMesh< ELEMENT >::Regions_areas protected
Target areas for regions; defaults to 0.0 which (luckily) implies "no specific target area" for triangle!
Time_stepper_pt
template<class ELEMENT > TimeStepper* oomph::TriangleMesh< ELEMENT >::Time_stepper_pt protected
Timestepper used to build elements.
Referenced by oomph::TriangleMesh< ELEMENT >::set_mesh_level_time_stepper(), and oomph::TriangleMesh< ELEMENT >::TriangleMesh().
Tmp_mesh_pt
template<class ELEMENT > TriangleScaffoldMesh* oomph::TriangleMesh< ELEMENT >::Tmp_mesh_pt protected
Temporary scaffold mesh.
Referenced by oomph::TriangleMesh< ELEMENT >::TriangleMesh().
Use_attributes
template<class ELEMENT > bool oomph::TriangleMesh< ELEMENT >::Use_attributes protected
Boolean flag to indicate whether to use attributes or not (required for multidomain meshes)
Referenced by oomph::TriangleMesh< ELEMENT >::TriangleMesh().
The documentation for this class was generated from the following files:
triangle_mesh.template.h
triangle_mesh.template.cc