MercuryDPM: oomph::MatrixBasedDiagPreconditioner Class Reference
oomph::MatrixBasedDiagPreconditioner Class Reference
Matrix-based diagonal preconditioner.
#include <general_purpose_preconditioners.h>
Public Member Functions
MatrixBasedDiagPreconditioner ()
Constructor (empty)
~MatrixBasedDiagPreconditioner ()
Destructor (empty)
MatrixBasedDiagPreconditioner (const MatrixBasedDiagPreconditioner &)=delete
Broken copy constructor.
void operator= (const MatrixBasedDiagPreconditioner &)=delete
Broken assignment operator.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Apply preconditioner to z, i.e. z=D^-1.
void setup ()
Public Member Functions inherited from oomph::Preconditioner
Preconditioner ()
Constructor.
Preconditioner (const Preconditioner &)=delete
Broken copy constructor.
void operator= (const Preconditioner &)=delete
Broken assignment operator.
virtual ~Preconditioner ()
Destructor (empty)
virtual void preconditioner_solve_transpose (const DoubleVector &r, DoubleVector &z)
void setup (DoubleMatrixBase *matrix_pt)
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
void enable_silent_preconditioner_setup ()
Set up the block preconditioner quietly!
void disable_silent_preconditioner_setup ()
Be verbose in the block preconditioner setup.
virtual void clean_up_memory ()
Clean up memory (empty). Generic interface function.
virtual DoubleMatrixBase * matrix_pt () const
Get function for matrix pointer.
virtual void set_matrix_pt (DoubleMatrixBase *matrix_pt)
Set the matrix pointer.
virtual const OomphCommunicator * comm_pt () const
Get function for comm pointer.
virtual void set_comm_pt (const OomphCommunicator *const comm_pt)
Set the communicator pointer.
double setup_time () const
Returns the time to setup the preconditioner.
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> &doftype_coarsen_map_coarse)
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
void build_distribution (const LinearAlgebraDistribution &dist)
Private Attributes
Vector< double > Inv_diag
Vector of inverse diagonal entries.
Additional Inherited Members
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
Protected Attributes inherited from oomph::Preconditioner
bool Silent_preconditioner_setup
Boolean to indicate whether or not the build should be done silently.
std::ostream * Stream_pt
Pointer to the output stream – defaults to std::cout.
Detailed Description
Matrix-based diagonal preconditioner.
Constructor & Destructor Documentation
MatrixBasedDiagPreconditioner() [1/2]
oomph::MatrixBasedDiagPreconditioner::MatrixBasedDiagPreconditioner () inline
Constructor (empty)
 {};
~MatrixBasedDiagPreconditioner()
oomph::MatrixBasedDiagPreconditioner::~MatrixBasedDiagPreconditioner () inline
Destructor (empty)
 {};
MatrixBasedDiagPreconditioner() [2/2]
oomph::MatrixBasedDiagPreconditioner::MatrixBasedDiagPreconditioner (const MatrixBasedDiagPreconditioner &) delete
Broken copy constructor.
Member Function Documentation
operator=()
void oomph::MatrixBasedDiagPreconditioner::operator= (const MatrixBasedDiagPreconditioner &) delete
Broken assignment operator.
preconditioner_solve()
void oomph::MatrixBasedDiagPreconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) virtual
Apply preconditioner to z, i.e. z=D^-1.
Apply preconditioner: Multiply r by the inverse of the diagonal.
Implements oomph::Preconditioner.
   {
 #ifdef PARANOID
     if (*r.distribution_pt() != *this->distribution_pt())
     {
       std::ostringstream error_message_stream;
       error_message_stream
         << "The r vector must have the same distribution as the "
            "preconditioner. "
         << "(this is the same as the matrix passed to setup())";
       throw OomphLibError(error_message_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
     if (z.built())
     {
       if (*z.distribution_pt() != *this->distribution_pt())
       {
         std::ostringstream error_message_stream;
         error_message_stream
           << "The z vector distribution has been setup; it must have the "
           << "same distribution as the r vector (and preconditioner).";
         throw OomphLibError(error_message_stream.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
     }
 #endif
     // if z has not been setup then rebuild it
     if (!z.built())
     {
       z.build(this->distribution_pt(), 0.0);
     }
     // apply the preconditioner
     const double* r_values = r.values_pt();
     double* z_values = z.values_pt();
     unsigned nrow_local = this->nrow_local();
     for (unsigned i = 0; i < nrow_local; i++)
     {
       z_values[i] = Inv_diag[i] * r_values[i];
     }
   }
References oomph::DoubleVector::build(), oomph::DoubleVector::built(), oomph::DistributableLinearAlgebraObject::distribution_pt(), i, Inv_diag, oomph::DistributableLinearAlgebraObject::nrow_local(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, UniformPSDSelfTest::r, and oomph::DoubleVector::values_pt().
setup()
void oomph::MatrixBasedDiagPreconditioner::setup () virtual
Setup the preconditioner (store diagonal) from the fully assembled matrix.
Setup diagonal preconditioner: Store the inverse of the diagonal entries from the fully assembled matrix.
Implements oomph::Preconditioner.
   {
     // first attempt to cast to DistributableLinearAlgebraObject
     DistributableLinearAlgebraObject* dist_matrix_pt =
       dynamic_cast<DistributableLinearAlgebraObject*>(matrix_pt());
     // if it is a distributable matrix
     if (dist_matrix_pt != 0)
     {
       // cache the number of first_rows and nrow_local
       unsigned nrow_local = dist_matrix_pt->nrow_local();
       unsigned first_row = dist_matrix_pt->first_row();
       // resize the inverse diagonal storage
       Inv_diag.resize(nrow_local);
       // Extract the diagonal entries
       for (unsigned i = 0; i < nrow_local; i++)
       {
         unsigned index = i + first_row;
 #ifdef PARANOID
         if ((*matrix_pt())(i, index) == 0.0)
         {
           throw OomphLibError(
             "Zero diagonal in matrix --> Cannot use diagonal preconditioner.",
             OOMPH_CURRENT_FUNCTION,
             OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         Inv_diag[i] = 1.0 / (*matrix_pt())(i, index);
       }
       // store the distribution
       this->build_distribution(dist_matrix_pt->distribution_pt());
     }
     // else it is not a distributable matrix
     else
     {
       // # of rows in the matrix
       unsigned n_row = matrix_pt()->nrow();
       // Resize the Inv_diag vector to accommodate the # of
       // diagonal entries
       Inv_diag.resize(n_row);
       // Extract the diagonal entries
       for (unsigned i = 0; i < n_row; i++)
       {
 #ifdef PARANOID
         if ((*matrix_pt())(i, i) == 0.0)
         {
           throw OomphLibError(
             "Zero diagonal in matrix --> Cannot use diagonal preconditioner.",
             OOMPH_CURRENT_FUNCTION,
             OOMPH_EXCEPTION_LOCATION);
         }
         else
 #endif
         {
           Inv_diag[i] = 1.0 / (*matrix_pt())(i, i);
         }
       }
       // create the distribution
       LinearAlgebraDistribution dist(comm_pt(), n_row, false);
       this->build_distribution(dist);
     }
   }
References oomph::DistributableLinearAlgebraObject::build_distribution(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::DistributableLinearAlgebraObject::first_row(), i, Inv_diag, oomph::Preconditioner::matrix_pt(), oomph::DoubleMatrixBase::nrow(), oomph::DistributableLinearAlgebraObject::nrow_local(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Member Data Documentation
Inv_diag
Vector<double> oomph::MatrixBasedDiagPreconditioner::Inv_diag private
Vector of inverse diagonal entries.
Referenced by preconditioner_solve(), and setup().
The documentation for this class was generated from the following files:
general_purpose_preconditioners.h
general_purpose_preconditioners.cc