MercuryDPM: Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ > Class Template Reference
Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ > Class Template Reference
A tensor expression mapping an existing array of data.
#include <TensorMap.h>
Public Types
enum { IsAligned = ((int(Options_) & Aligned) == Aligned) , CoordAccess = true , RawAccess = true }
typedef TensorMap< PlainObjectType, Options_, MakePointer_ > Self
typedef TensorBase< TensorMap< PlainObjectType, Options_, MakePointer_ > > Base
typedef Eigen::internal::nested< Self >::type Nested
typedef internal::traits< PlainObjectType >::StorageKind StorageKind
typedef internal::traits< PlainObjectType >::Index Index
typedef internal::traits< PlainObjectType >::Scalar Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef PlainObjectType::Base::CoeffReturnType CoeffReturnType
typedef MakePointer_< Scalar >::Type PointerType
typedef MakePointer_< Scalar >::ConstType PointerConstType
typedef std::conditional_t< bool(internal::is_lvalue< PlainObjectType >::value), PointerType, PointerConstType > StoragePointerType
typedef std::conditional_t< bool(internal::is_lvalue< PlainObjectType >::value), Scalar &, const Scalar & > StorageRefType
typedef PlainObjectType::Dimensions Dimensions
Public Types inherited from Eigen::TensorBase< TensorMap< PlainObjectType, Options_, MakePointer_ > >
typedef TensorBase< TensorMap< PlainObjectType, Options_, MakePointer_ >, ReadOnlyAccessors > Base
typedef internal::traits< TensorMap< PlainObjectType, Options_, MakePointer_ > > DerivedTraits
typedef DerivedTraits::Scalar Scalar
typedef DerivedTraits::Index Index
typedef Scalar CoeffReturnType
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap (StoragePointerType dataPtr)
template<typename... IndexTypes>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap (StoragePointerType dataPtr, Index firstDimension, IndexTypes... otherDimensions)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap (StoragePointerType dataPtr, const array< Index, NumIndices > &dimensions)
template<typename Dimensions >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap (StoragePointerType dataPtr, const Dimensions &dimensions)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap (PlainObjectType &tensor)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rank () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index dimension (Index n) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index size () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE StoragePointerType data ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE StoragePointerType data () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE StorageRefType operator() (const array< Index, NumIndices > &indices) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE StorageRefType operator() () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE StorageRefType operator() (Index index) const
template<typename... IndexTypes>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE StorageRefType operator() (Index firstIndex, Index secondIndex, IndexTypes... otherIndices) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE StorageRefType operator() (const array< Index, NumIndices > &indices)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE StorageRefType operator() ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE StorageRefType operator() (Index index)
template<typename... IndexTypes>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE StorageRefType operator() (Index firstIndex, Index secondIndex, IndexTypes... otherIndices)
Public Member Functions inherited from Eigen::TensorBase< TensorMap< PlainObjectType, Options_, MakePointer_ > >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap< PlainObjectType, Options_, MakePointer_ > & setZero ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap< PlainObjectType, Options_, MakePointer_ > & setConstant (const Scalar &val)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap< PlainObjectType, Options_, MakePointer_ > & setRandom ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap< PlainObjectType, Options_, MakePointer_ > & setRandom ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap< PlainObjectType, Options_, MakePointer_ > & setValues (const typename internal::Initializer< TensorMap< PlainObjectType, Options_, MakePointer_ >, NumDimensions >::InitList &vals)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap< PlainObjectType, Options_, MakePointer_ > & operator+= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap< PlainObjectType, Options_, MakePointer_ > & operator-= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap< PlainObjectType, Options_, MakePointer_ > & operator*= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap< PlainObjectType, Options_, MakePointer_ > & operator/= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorLayoutSwapOp< const TensorMap< PlainObjectType, Options_, MakePointer_ > > swap_layout () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorLayoutSwapOp< TensorMap< PlainObjectType, Options_, MakePointer_ > > swap_layout ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorConcatenationOp< const Axis, const TensorMap< PlainObjectType, Options_, MakePointer_ >, const OtherDerived > concatenate (const OtherDerived &other, const Axis &axis) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorConcatenationOp< const Axis, TensorMap< PlainObjectType, Options_, MakePointer_ >, OtherDerived > concatenate (const OtherDerived &other, const Axis &axis)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReshapingOp< const NewDimensions, const TensorMap< PlainObjectType, Options_, MakePointer_ > > reshape (const NewDimensions &newDimensions) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorReshapingOp< const NewDimensions, TensorMap< PlainObjectType, Options_, MakePointer_ > > reshape (const NewDimensions &newDimensions)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorSlicingOp< const StartIndices, const Sizes, const TensorMap< PlainObjectType, Options_, MakePointer_ > > slice (const StartIndices &startIndices, const Sizes &sizes) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorSlicingOp< const StartIndices, const Sizes, TensorMap< PlainObjectType, Options_, MakePointer_ > > slice (const StartIndices &startIndices, const Sizes &sizes)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorStridingSlicingOp< const StartIndices, const StopIndices, const Strides, const TensorMap< PlainObjectType, Options_, MakePointer_ > > stridedSlice (const StartIndices &startIndices, const StopIndices &stopIndices, const Strides &strides) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingSlicingOp< const StartIndices, const StopIndices, const Strides, TensorMap< PlainObjectType, Options_, MakePointer_ > > stridedSlice (const StartIndices &startIndices, const StopIndices &stopIndices, const Strides &strides)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorChippingOp< DimId, const TensorMap< PlainObjectType, Options_, MakePointer_ > > chip (const Index offset) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorChippingOp< DimId, TensorMap< PlainObjectType, Options_, MakePointer_ > > chip (const Index offset)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorChippingOp< Dynamic, const TensorMap< PlainObjectType, Options_, MakePointer_ > > chip (const Index offset, const Index dim) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorChippingOp< Dynamic, TensorMap< PlainObjectType, Options_, MakePointer_ > > chip (const Index offset, const Index dim)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReverseOp< const ReverseDimensions, const TensorMap< PlainObjectType, Options_, MakePointer_ > > reverse (const ReverseDimensions &rev) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorReverseOp< const ReverseDimensions, TensorMap< PlainObjectType, Options_, MakePointer_ > > reverse (const ReverseDimensions &rev)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorRollOp< const Rolls, const TensorMap< PlainObjectType, Options_, MakePointer_ > > roll (const Rolls &roll) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorRollOp< const Rolls, TensorMap< PlainObjectType, Options_, MakePointer_ > > roll (const Rolls &roll)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorShufflingOp< const Shuffle, const TensorMap< PlainObjectType, Options_, MakePointer_ > > shuffle (const Shuffle &shfl) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorShufflingOp< const Shuffle, TensorMap< PlainObjectType, Options_, MakePointer_ > > shuffle (const Shuffle &shfl)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorStridingOp< const Strides, const TensorMap< PlainObjectType, Options_, MakePointer_ > > stride (const Strides &strides) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingOp< const Strides, TensorMap< PlainObjectType, Options_, MakePointer_ > > stride (const Strides &strides)
TensorDevice< TensorMap< PlainObjectType, Options_, MakePointer_ >, DeviceType > device (const DeviceType &dev)
TensorAsyncDevice< TensorMap< PlainObjectType, Options_, MakePointer_ >, DeviceType, DoneCallback > device (const DeviceType &dev, DoneCallback done)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap< PlainObjectType, Options_, MakePointer_ > & derived ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorMap< PlainObjectType, Options_, MakePointer_ > & derived () const
Static Public Attributes
static constexpr int Options = Options_
static constexpr Index NumIndices = PlainObjectType::NumIndices
static constexpr int Layout = PlainObjectType::Layout
Static Public Attributes inherited from Eigen::TensorBase< TensorMap< PlainObjectType, Options_, MakePointer_ > >
static constexpr int NumDimensions
Private Attributes
StoragePointerType m_data
Dimensions m_dimensions
Additional Inherited Members
Protected Member Functions inherited from Eigen::TensorBase< TensorMap< PlainObjectType, Options_, MakePointer_ > >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorMap< PlainObjectType, Options_, MakePointer_ > & operator= (const OtherDerived &other)
Detailed Description
template<typename PlainObjectType, int Options_, template< class > class MakePointer_>
class Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >
A tensor expression mapping an existing array of data.
template <class> class MakePointer_ is added to convert the host pointer to the device pointer. It is added due to the fact that for our device compiler T* is not allowed. If we wanted to use the same Evaluator functions we have to convert that type to our pointer T. This is done through our MakePointer_ class. By default the Type in the MakePointer_<T> is T* . Therefore, by adding the default value, we managed to convert the type and it does not break any existing code as its default value is T*.
Member Typedef Documentation
Base
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> typedef TensorBase<TensorMap<PlainObjectType, Options_, MakePointer_> > Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::Base
CoeffReturnType
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> typedef PlainObjectType::Base::CoeffReturnType Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::CoeffReturnType
Dimensions
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> typedef PlainObjectType::Dimensions Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::Dimensions
Index
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> typedef internal::traits<PlainObjectType>::Index Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::Index
Nested
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> typedef Eigen::internal::nested<Self>::type Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::Nested
PointerConstType
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> typedef MakePointer_<Scalar>::ConstType Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::PointerConstType
PointerType
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> typedef MakePointer_<Scalar>::Type Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::PointerType
RealScalar
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> typedef NumTraits<Scalar>::Real Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::RealScalar
Scalar
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> typedef internal::traits<PlainObjectType>::Scalar Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::Scalar
Self
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> typedef TensorMap<PlainObjectType, Options_, MakePointer_> Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::Self
StorageKind
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> typedef internal::traits<PlainObjectType>::StorageKind Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::StorageKind
StoragePointerType
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> typedef std::conditional_t<bool(internal::is_lvalue<PlainObjectType>::value), PointerType, PointerConstType > Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::StoragePointerType
StorageRefType
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> typedef std::conditional_t<bool(internal::is_lvalue<PlainObjectType>::value), Scalar&, const Scalar&> Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::StorageRefType
Member Enumeration Documentation
anonymous enum
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> anonymous enum
Enumerator
IsAligned
CoordAccess
RawAccess
 { IsAligned = ((int(Options_) & Aligned) == Aligned), CoordAccess = true, RawAccess = true };
Constructor & Destructor Documentation
TensorMap() [1/5]
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::TensorMap (StoragePointerType dataPtr) inline
                                                                               : m_data(dataPtr), m_dimensions() {
     // The number of dimensions used to construct a tensor must be equal to the rank of the tensor.
     EIGEN_STATIC_ASSERT((0 == NumIndices || NumIndices == Dynamic), YOU_MADE_A_PROGRAMMING_MISTAKE)
   }
References Eigen::Dynamic, EIGEN_STATIC_ASSERT, and Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::NumIndices.
TensorMap() [2/5]
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> template<typename... IndexTypes> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::TensorMap (StoragePointerType dataPtr, Index firstDimension, IndexTypes... otherDimensions) inline
       : m_data(dataPtr), m_dimensions(firstDimension, otherDimensions...) {
     // The number of dimensions used to construct a tensor must be equal to the rank of the tensor.
     EIGEN_STATIC_ASSERT((sizeof...(otherDimensions) + 1 == NumIndices || NumIndices == Dynamic),
                         YOU_MADE_A_PROGRAMMING_MISTAKE)
   }
References Eigen::Dynamic, EIGEN_STATIC_ASSERT, and Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::NumIndices.
TensorMap() [3/5]
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::TensorMap (StoragePointerType dataPtr, const array< Index, NumIndices > & dimensions) inline
       : m_data(dataPtr), m_dimensions(dimensions) {}
TensorMap() [4/5]
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> template<typename Dimensions > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::TensorMap (StoragePointerType dataPtr, const Dimensions & dimensions) inline
       : m_data(dataPtr), m_dimensions(dimensions) {}
TensorMap() [5/5]
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::TensorMap (PlainObjectType & tensor) inline
       : m_data(tensor.data()), m_dimensions(tensor.dimensions()) {}
Member Function Documentation
data() [1/2]
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE StoragePointerType Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::data () inline
 { return m_data; }
References Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::m_data.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), test_0d_const_tensor_map(), test_full_reductions_mean_with_odd_offset_sycl(), test_last_dim_reductions_max_with_offset_sycl(), test_same_type(), test_slice_in_expr(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
data() [2/2]
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE StoragePointerType Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::data () const inline
 { return m_data; }
References Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::m_data.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimension()
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::dimension (Index n) const inline
 { return m_dimensions[n]; }
References Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::m_dimensions, and n.
Referenced by test_2d(), test_3d(), and test_from_tensor().
dimensions()
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::dimensions () const inline
 { return m_dimensions; }
References Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::m_dimensions.
operator()() [1/8]
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE StorageRefType Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() () inline
{
     EIGEN_STATIC_ASSERT(NumIndices == 0, YOU_MADE_A_PROGRAMMING_MISTAKE)
     return m_data[0];
   }
References EIGEN_STATIC_ASSERT, Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::m_data, and Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::NumIndices.
operator()() [2/8]
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE StorageRefType Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() () const inline
{
     EIGEN_STATIC_ASSERT(NumIndices == 0, YOU_MADE_A_PROGRAMMING_MISTAKE)
     return m_data[0];
   }
References EIGEN_STATIC_ASSERT, Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::m_data, and Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::NumIndices.
operator()() [3/8]
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE StorageRefType Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() (const array< Index, NumIndices > & indices) inline
{
     //      eigen_assert(checkIndexRange(indices));
     if (PlainObjectType::Options & RowMajor) {
       const Index index = m_dimensions.IndexOfRowMajor(indices);
       return m_data[index];
     } else {
       const Index index = m_dimensions.IndexOfColMajor(indices);
       return m_data[index];
     }
   }
References Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::m_data, Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::m_dimensions, and Eigen::RowMajor.
operator()() [4/8]
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE StorageRefType Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() (const array< Index, NumIndices > & indices) const inline
{
     //      eigen_assert(checkIndexRange(indices));
     if (PlainObjectType::Options & RowMajor) {
       const Index index = m_dimensions.IndexOfRowMajor(indices);
       return m_data[index];
     } else {
       const Index index = m_dimensions.IndexOfColMajor(indices);
       return m_data[index];
     }
   }
References Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::m_data, Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::m_dimensions, and Eigen::RowMajor.
operator()() [5/8]
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> template<typename... IndexTypes> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE StorageRefType Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() (Index firstIndex, Index secondIndex, IndexTypes... otherIndices) inline
{
     static_assert(sizeof...(otherIndices) + 2 == NumIndices || NumIndices == Dynamic,
                   "Number of indices used to access a tensor coefficient must be equal to the rank of the tensor.");
     eigen_assert(internal::all((Eigen::NumTraits<Index>::highest() >= otherIndices)...));
     const std::size_t NumDims = sizeof...(otherIndices) + 2;
     if (PlainObjectType::Options & RowMajor) {
       const Index index =
           m_dimensions.IndexOfRowMajor(array<Index, NumDims>{{firstIndex, secondIndex, otherIndices...}});
       return m_data[index];
     } else {
       const Index index =
           m_dimensions.IndexOfColMajor(array<Index, NumDims>{{firstIndex, secondIndex, otherIndices...}});
       return m_data[index];
     }
   }
References Eigen::internal::all(), Eigen::Dynamic, eigen_assert, Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::m_data, Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::m_dimensions, Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::NumIndices, and Eigen::RowMajor.
operator()() [6/8]
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> template<typename... IndexTypes> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE StorageRefType Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() (Index firstIndex, Index secondIndex, IndexTypes... otherIndices) const inline
{
     EIGEN_STATIC_ASSERT(sizeof...(otherIndices) + 2 == NumIndices, YOU_MADE_A_PROGRAMMING_MISTAKE)
     eigen_assert(internal::all((Eigen::NumTraits<Index>::highest() >= otherIndices)...));
     if (PlainObjectType::Options & RowMajor) {
       const Index index =
           m_dimensions.IndexOfRowMajor(array<Index, NumIndices>{{firstIndex, secondIndex, otherIndices...}});
       return m_data[index];
     } else {
       const Index index =
           m_dimensions.IndexOfColMajor(array<Index, NumIndices>{{firstIndex, secondIndex, otherIndices...}});
       return m_data[index];
     }
   }
References Eigen::internal::all(), eigen_assert, EIGEN_STATIC_ASSERT, Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::m_data, Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::m_dimensions, Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::NumIndices, and Eigen::RowMajor.
operator()() [7/8]
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE StorageRefType Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() (Index index) inline
{
     eigen_internal_assert(index >= 0 && index < size());
     return m_data[index];
   }
References eigen_internal_assert, Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::m_data, and Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::size().
operator()() [8/8]
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE StorageRefType Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator() (Index index) const inline
{
     eigen_internal_assert(index >= 0 && index < size());
     return m_data[index];
   }
References eigen_internal_assert, Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::m_data, and Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::size().
rank()
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::rank () const inline
 { return m_dimensions.rank(); }
References Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::m_dimensions.
Referenced by test_2d(), test_3d(), and test_from_tensor().
size()
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::size () const inline
 { return m_dimensions.TotalSize(); }
References Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::m_dimensions.
Referenced by Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator()(), test_2d(), test_3d(), and test_from_tensor().
Member Data Documentation
Layout
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> constexpr int Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::Layout = PlainObjectType::Layout static constexpr
m_data
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> StoragePointerType Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::m_data private
Referenced by Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::data(), and Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator()().
m_dimensions
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> Dimensions Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::m_dimensions private
Referenced by Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::dimension(), Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::dimensions(), Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator()(), Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::rank(), and Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::size().
NumIndices
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> constexpr Index Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::NumIndices = PlainObjectType::NumIndices static constexpr
Referenced by Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::operator()(), and Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::TensorMap().
Options
template<typename PlainObjectType , int Options_, template< class > class MakePointer_> constexpr int Eigen::TensorMap< PlainObjectType, Options_, MakePointer_ >::Options = Options_ static constexpr
The documentation for this class was generated from the following files:
TensorForwardDeclarations.h
TensorMap.h