MercuryDPM: LinearViscoelasticNormalSpecies Class Reference
LinearViscoelasticNormalSpecies Class Reference
LinearViscoelasticNormalSpecies contains the parameters used to describe a linear elastic-dissipative normal force.
#include <LinearViscoelasticNormalSpecies.h>
Public Types
typedef LinearViscoelasticInteraction InteractionType
The correct Interaction type for this FrictionForceSpecies.
Public Member Functions
LinearViscoelasticNormalSpecies ()
The default constructor.
LinearViscoelasticNormalSpecies (const LinearViscoelasticNormalSpecies &p)
The default copy constructor.
~LinearViscoelasticNormalSpecies ()
The default destructor.
void read (std::istream &is)
Reads the species properties from an input stream.
void write (std::ostream &os) const
Writes the species properties to an output stream.
std::string getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
Mdouble getMaximumVelocity (Mdouble radius, Mdouble mass) const
Calculates the maximum velocity allowed for a collision of two copies of P (for higher velocities particles could pass through each other)
void setStiffnessAndRestitutionCoefficient (Mdouble k_, Mdouble eps, Mdouble mass)
Sets k, disp such that it matches a given tc and eps for a collision of two copies of P.
void setRestitutionCoefficient (double eps, Mdouble mass)
Sets disp to obtain a restitution coefficient eps for a collision of two particles of mass m.
void setCollisionTimeAndRestitutionCoefficient (Mdouble tc, Mdouble eps, BaseParticle *p)
Sets k, disp such that it matches a given tc and eps for a collision of two copies of particle p.
void setCollisionTimeAndRestitutionCoefficient (Mdouble tc, Mdouble eps, Mdouble mass)
Sets k, disp such that it matches a given tc and eps for a collision of two copies of equal mass m.
void setCollisionTimeAndRestitutionCoefficient (Mdouble collisionTime, Mdouble restitutionCoefficient, Mdouble mass1, Mdouble mass2)
Mdouble getCollisionTime (Mdouble mass) const
Calculates collision time for two copies of a particle of given disp, k, mass.
Mdouble getRestitutionCoefficient (Mdouble mass) const
Calculates restitution coefficient for two copies of given disp, k, mass.
void mix (LinearViscoelasticNormalSpecies *SBase, LinearViscoelasticNormalSpecies *TBase)
creates default values for mixed species
void setStiffness (Mdouble new_k)
Allows the spring constant to be changed.
Mdouble getStiffness () const
Allows the spring constant to be accessed.
void setDissipation (Mdouble dissipation)
Allows the normal dissipation to be changed.
Mdouble getDissipation () const
Allows the normal dissipation to be accessed.
MERCURYDPM_DEPRECATED void setStiffnessAndDissipation (helpers::KAndDisp new_)
Allows the spring and dissipation constants to be changed simultaneously.
Mdouble computeTimeStep (Mdouble mass)
Public Member Functions inherited from BaseNormalForce
BaseNormalForce ()
BaseNormalForce (const BaseNormalForce &p)
bool getConstantRestitution () const
void setConstantRestitution (bool constantRestitution)
virtual void actionsAfterTimeStep (BaseParticle *particle) const
Public Member Functions inherited from BaseForce
BaseSpecies * getBaseSpecies () const
void setBaseSpecies (BaseSpecies *baseSpecies)
Private Attributes
Mdouble stiffness_
(normal) spring constant
Mdouble dissipation_
(normal) viscosity
Detailed Description
LinearViscoelasticNormalSpecies contains the parameters used to describe a linear elastic-dissipative normal force.
See LinearViscoelasticNormalInteraction::computeForce for a description of the force law.
Member Typedef Documentation
InteractionType
typedef LinearViscoelasticInteraction LinearViscoelasticNormalSpecies::InteractionType
The correct Interaction type for this FrictionForceSpecies.
Constructor & Destructor Documentation
LinearViscoelasticNormalSpecies() [1/2]
LinearViscoelasticNormalSpecies::LinearViscoelasticNormalSpecies ()
The default constructor.
         : BaseNormalForce()
 {
     stiffness_ = 0.0;
     dissipation_ = 0.0;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"LinearViscoelasticNormalSpecies::LinearViscoelasticNormalSpecies() finished"<<std::endl;
 #endif
 }
References dissipation_, and stiffness_.
LinearViscoelasticNormalSpecies() [2/2]
LinearViscoelasticNormalSpecies::LinearViscoelasticNormalSpecies (const LinearViscoelasticNormalSpecies & p)
The default copy constructor.
Parameters
[in] the species that is copied
         : BaseNormalForce(p)
 {
     stiffness_ = p.stiffness_;
     dissipation_ = p.dissipation_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"LinearViscoelasticNormalSpecies::LinearViscoelasticNormalSpecies(const LinearViscoelasticNormalSpecies &p) finished"<<std::endl;
 #endif
 }
References dissipation_, p, and stiffness_.
~LinearViscoelasticNormalSpecies()
LinearViscoelasticNormalSpecies::~LinearViscoelasticNormalSpecies ()
The default destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"LinearViscoelasticNormalSpecies::~LinearViscoelasticNormalSpecies() finished"<<std::endl;
 #endif
 }
Member Function Documentation
computeTimeStep()
Mdouble LinearViscoelasticNormalSpecies::computeTimeStep (Mdouble mass) inline
     {
         return 0.02 * constants::pi /
                std::sqrt(stiffness_ / (.5 * mass) - mathsFunc::square(dissipation_ / mass));
     }
References dissipation_, constants::pi, sqrt(), mathsFunc::square(), and stiffness_.
getBaseName()
std::string LinearViscoelasticNormalSpecies::getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
Returns
a string containing the name of the species (minus the word "Species")
 {
     return "LinearViscoelastic";
 }
getCollisionTime()
Mdouble LinearViscoelasticNormalSpecies::getCollisionTime (Mdouble mass) const
Calculates collision time for two copies of a particle of given disp, k, mass.
Calculates collision time for two copies of a particle of given disp, k, mass
Parameters
[in] mass mass of a typical particle
 {
     if (getConstantRestitution()) mass = 1;
     if (mass <= 0)
     {
         logger(ERROR, "Warning in getCollisionTime(%) mass is not set or has an unexpected value, "
                       "(getCollisionTime(%)", mass, mass);
     }
     if (stiffness_ <= 0)
     {
         logger(ERROR, "Error in getCollisionTime(%) stiffness=% is not set or has an unexpected value "
                       "(getCollisionTime(%), with stiffness=%)",
                mass, stiffness_, mass, stiffness_);
     }
     if (dissipation_ < 0)
     {
         logger(ERROR, "Error in getCollisionTime(%) dissipation=% is not set or has an unexpected value "
                       "(getCollisionTime(%), with dissipation=%)",
                mass, dissipation_, mass, dissipation_);
     }
     Mdouble tosqrt = stiffness_ / (.5 * mass) - mathsFunc::square(dissipation_ / mass);
     if (tosqrt <= 0)
     {
         logger(ERROR, "Warning in getCollisionTime(%) values for mass, stiffness and dissipation would lead to an "
                       "overdamped system, (getCollisionTime(%), with stiffness=% and dissipation=%",
                mass, mass, stiffness_, dissipation_);
     }
     return constants::pi / std::sqrt(tosqrt);
 }
References dissipation_, ERROR, BaseNormalForce::getConstantRestitution(), logger, constants::pi, sqrt(), mathsFunc::square(), and stiffness_.
Referenced by RotatingDrumBidisperseInitialise::actionsAfterTimeStep(), getRestitutionCoefficient(), main(), MaserRepeatedOutInMPI2Test::MaserRepeatedOutInMPI2Test(), ParticleCreation::ParticleCreation(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), ShiftingConstantMassFlowMaserBoundarySelfTest::setupInitialConditions(), ShiftingMaserBoundarySelfTest::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), SubcriticalMaserBoundarySelfTest::setupInitialConditions(), EllipsoidsBouncingOnWallDemo::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), SphericalSuperQuadricCollision::setupInitialConditions(), VisualisationTest::setupInitialConditions(), Packing::setupInitialConditions(), Siegen::Siegen(), SubcriticalMaserBoundaryTESTMPI2Test::SubcriticalMaserBoundaryTESTMPI2Test(), and viscoElasticUnitTest::viscoElasticUnitTest().
getDissipation()
Mdouble LinearViscoelasticNormalSpecies::getDissipation () const
Allows the normal dissipation to be accessed.
 {
     return dissipation_;
 }
References dissipation_.
Referenced by BoundariesSelfTest::BoundariesSelfTest(), ChutePeriodicDemo::ChutePeriodicDemo(), ChuteWithWedge::ChuteWithWedge(), LinearViscoelasticInteraction::computeNormalForce(), Slide::create_rough_wall(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), main(), MinimalExampleDrum::MinimalExampleDrum(), SilbertPeriodic::readNextArgument(), SilbertPeriodic::set_study(), setCollisionTimeAndRestitutionCoefficient(), GranularJet::setSilbert(), ChutePeriodic::setup(), MarbleRun::setupInitialConditions(), Siegen::Siegen(), and SilbertPeriodic::SilbertPeriodic().
getMaximumVelocity()
Mdouble LinearViscoelasticNormalSpecies::getMaximumVelocity (Mdouble radius, Mdouble mass) const
Calculates the maximum velocity allowed for a collision of two copies of P (for higher velocities particles could pass through each other)
 {
     return radius * std::sqrt(stiffness_ / (.5 * mass));
 }
References UniformPSDSelfTest::radius, sqrt(), and stiffness_.
Referenced by main().
getRestitutionCoefficient()
Mdouble LinearViscoelasticNormalSpecies::getRestitutionCoefficient (Mdouble mass) const
Calculates restitution coefficient for two copies of given disp, k, mass.
 {
     if (getConstantRestitution()) mass = 1;
     return std::exp(-dissipation_ / mass * getCollisionTime(mass));
 }
References dissipation_, Eigen::bfloat16_impl::exp(), getCollisionTime(), and BaseNormalForce::getConstantRestitution().
Referenced by main(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), CubicCell::setupInitialConditions(), and SubcriticalMaserBoundaryTESTMPI2Test::SubcriticalMaserBoundaryTESTMPI2Test().
getStiffness()
Mdouble LinearViscoelasticNormalSpecies::getStiffness () const
Allows the spring constant to be accessed.
 {
     return stiffness_;
 }
References stiffness_.
Referenced by RotatingDrumBidisperseInitialise::actionsAfterTimeStep(), BoundariesSelfTest::BoundariesSelfTest(), ChutePeriodicDemo::ChutePeriodicDemo(), ChuteWithWedge::ChuteWithWedge(), LinearViscoelasticInteraction::computeNormalForce(), Slide::create_rough_wall(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), LinearViscoelasticInteraction::getElasticEnergy(), LinearViscoelasticInteraction::getElasticEnergyAtEquilibrium(), main(), MinimalExampleDrum::MinimalExampleDrum(), SilbertPeriodic::set_study(), SlidingFrictionSpecies::setCollisionTimeAndNormalAndTangentialRestitutionCoefficient(), SlidingFrictionSpecies::setCollisionTimeAndNormalAndTangentialRestitutionCoefficientNoDispt(), setCollisionTimeAndRestitutionCoefficient(), setRestitutionCoefficient(), GranularJet::setSilbert(), ChutePeriodic::setup(), MarbleRun::setupInitialConditions(), Siegen::Siegen(), and SilbertPeriodic::SilbertPeriodic().
mix()
void LinearViscoelasticNormalSpecies::mix (LinearViscoelasticNormalSpecies * SBase, LinearViscoelasticNormalSpecies * TBase)
creates default values for mixed species
For all parameters we assume that the harmonic mean of the parameters of the original two species is a sensible default.
Parameters
[in] S,T the two species whose properties are mixed to create the new species
 {
     stiffness_ = BaseSpecies::average(S->getStiffness(), T->getStiffness());
     dissipation_ = BaseSpecies::average(S->getDissipation(), T->getDissipation());
 }
References BaseSpecies::average(), dissipation_, oomph::QuadTreeNames::S, and stiffness_.
read()
void LinearViscoelasticNormalSpecies::read (std::istream & is)
Reads the species properties from an input stream.
Parameters
[in] input stream (typically the restart file)
 {
     std::string dummy;
     is >> dummy >> stiffness_
        >> dummy >> dissipation_;
 }
References dissipation_, stiffness_, and oomph::Global_string_for_annotation::string().
setCollisionTimeAndRestitutionCoefficient() [1/3]
void LinearViscoelasticNormalSpecies::setCollisionTimeAndRestitutionCoefficient (Mdouble collisionTime, Mdouble restitutionCoefficient, Mdouble mass1, Mdouble mass2)
Set k, disp such that is matches a given tc and eps for a collision of two different masses. Recall the resitution constant is a function of k, disp and the mass of each particle in the collision See also setCollisionTimeAndRestitutionCoefficient(Mdouble tc, Mdouble eps, Mdouble mass)
Set k, disp such that is matches a given tc and eps for a collision of two different masses. Recall the resitution constant is a function of k, disp and the mass of each particle in the collision See also setCollisionTimeAndRestitutionCoefficient(Mdouble tc, Mdouble eps, Mdouble mass)
Parameters
[in] collision time
 {
     Mdouble reduced_mass = mass1 * mass2 / (mass1 + mass2);
     setCollisionTimeAndRestitutionCoefficient(collisionTime, restitutionCoefficient, 2.0 * reduced_mass);
 }
References setCollisionTimeAndRestitutionCoefficient().
setCollisionTimeAndRestitutionCoefficient() [2/3]
void LinearViscoelasticNormalSpecies::setCollisionTimeAndRestitutionCoefficient (Mdouble tc, Mdouble eps, BaseParticle * p)
Sets k, disp such that it matches a given tc and eps for a collision of two copies of particle p.
 {
     Mdouble mass = p->getSpecies()->getDensity() * p->getVolume();
     setCollisionTimeAndRestitutionCoefficient(tc, eps, mass);
 }
References CRBond_Bessel::eps, and p.
Referenced by BouncingSuperQuadric::BouncingSuperQuadric(), BoundariesSelfTest::BoundariesSelfTest(), CGDisplacementFieldUnitTest::CGDisplacementFieldUnitTest(), CGExactOverlapUnitTest::CGExactOverlapUnitTest(), CGForceDensityUnitTest::CGForceDensityUnitTest(), ChutePeriodicDemo::ChutePeriodicDemo(), ChuteWithWedge::ChuteWithWedge(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundaryPrescribedDistanceUnitTest::FluxBoundaryPrescribedDistanceUnitTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), FluxBoundaryUnitTest::FluxBoundaryUnitTest(), main(), MaserRepeatedOutInMPI2Test::MaserRepeatedOutInMPI2Test(), MinimalExampleDrum::MinimalExampleDrum(), SilbertPeriodic::set_study(), SlidingFrictionSpecies::setCollisionTimeAndNormalAndTangentialRestitutionCoefficient(), SlidingFrictionSpecies::setCollisionTimeAndNormalAndTangentialRestitutionCoefficientNoDispt(), setCollisionTimeAndRestitutionCoefficient(), ChutePeriodic::setup(), MarbleRun::setupInitialConditions(), ShiftingConstantMassFlowMaserBoundarySelfTest::setupInitialConditions(), ShiftingMaserBoundarySelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), Packing::setupInitialConditions(), MovingIntersectionOfWallsUnitTest_Basic::setupInitialConditions(), WallSpecies::setupInitialConditions(), and SubcriticalMaserBoundaryTESTMPI2Test::SubcriticalMaserBoundaryTESTMPI2Test().
setCollisionTimeAndRestitutionCoefficient() [3/3]
void LinearViscoelasticNormalSpecies::setCollisionTimeAndRestitutionCoefficient (Mdouble tc, Mdouble eps, Mdouble mass)
Sets k, disp such that it matches a given tc and eps for a collision of two copies of equal mass m.
Sets k, disp such that it matches a given tc and eps for a collision of two copies of equal mass m
Parameters
[in] tc collision time
[in] eps restitution coefficient
[in] mass harmonic average particle mass, \(\frac{2}{1/m1+1/m2}\)
 {
     logger.assert_always(tc>0, "collision time has to be positive");
     logger.assert_always(eps>=0 && eps<=1, "restitution has to be in [0,1]");
     logger.assert_always(mass>0, "mass has to be positive");
     if (getConstantRestitution()) mass = 1;
     if (eps == 0.0)
     {
         stiffness_ = .5 * mass * mathsFunc::square(constants::pi / tc);
         dissipation_ = std::sqrt(2.0 * mass * stiffness_);
     }
     else
     {
         dissipation_ = -mass / tc * mathsFunc::log(eps);
         stiffness_ = .5 * mass * (mathsFunc::square(constants::pi / tc)
                                   + mathsFunc::square(dissipation_ / mass));
     }
     logger(INFO,
            "setCollisionTimeAndRestitutionCoefficient: set stiffness to % and dissipation to % to obtain a collision time of % and a restitution coefficient of % for two particles of mass %",
            getStiffness(), getDissipation(), tc, eps, mass);
 }
References dissipation_, CRBond_Bessel::eps, BaseNormalForce::getConstantRestitution(), getDissipation(), getStiffness(), INFO, mathsFunc::log(), logger, constants::pi, sqrt(), mathsFunc::square(), and stiffness_.
setDissipation()
void LinearViscoelasticNormalSpecies::setDissipation (Mdouble dissipation)
Allows the normal dissipation to be changed.
 {
     if (dissipation >= 0)
     {
         dissipation_ = dissipation;
     }
     else
     {
         logger(ERROR, "Error in setDissipation(%)", dissipation);
     }
 }
References dissipation_, ERROR, and logger.
Referenced by FreeCooling2DinWallsDemo::actionsAfterTimeStep(), FreeCooling3DDemoProblem::actionsAfterTimeStep(), FreeCooling3DinWallsDemo::actionsAfterTimeStep(), FreeCoolingDemoProblem::actionsAfterTimeStep(), Slide::create_rough_wall(), ParameterStudy1DDemo::createSpecies(), ParameterStudy2DDemo::createSpecies(), InsertionBoundaryMPI2Test::InsertionBoundaryMPI2Test(), main(), ParticleInclusion::ParticleInclusion(), protectiveWall::protectiveWall(), SpeciesHandler::readOldObject(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), GranularJet::setSilbert(), setStiffnessAndDissipation(), Drum::setupInitialConditions(), CubicCell::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), SubcriticalMaserBoundarySelfTest::setupInitialConditions(), EllipsoidsBouncingOnWallDemo::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), SphericalSuperQuadricCollision::setupInitialConditions(), VisualisationTest::setupInitialConditions(), ContactDetectionWithWallTester::setupParticleAndWall(), ContactDetectionTester::setupParticles(), SilbertPeriodic::SilbertPeriodic(), and T_protectiveWall::T_protectiveWall().
setRestitutionCoefficient()
void LinearViscoelasticNormalSpecies::setRestitutionCoefficient (double eps, Mdouble mass)
Sets disp to obtain a restitution coefficient eps for a collision of two particles of mass m.
Sets k, disp such that it matches a given tc and eps for a collision of two copies of P
Parameters
[in] stiffness stiffness
[in] eps restitution coefficient
[in] mass effective particle mass, \(\frac{2}{1/m1+1/m2}\)
 {
     if (getConstantRestitution()) mass = 1;
     if (eps == 0.0) {
         dissipation_ = std::sqrt(2.0 * mass * getStiffness());
     } else {
         const Mdouble logEps = log(eps);
         dissipation_ = -std::sqrt(2.0 * mass * getStiffness()
                                   / (constants::sqr_pi + mathsFunc::square(logEps))) * logEps;
     }
 }
References dissipation_, CRBond_Bessel::eps, BaseNormalForce::getConstantRestitution(), getStiffness(), Eigen::bfloat16_impl::log(), constants::sqr_pi, sqrt(), and mathsFunc::square().
Referenced by setStiffnessAndRestitutionCoefficient().
setStiffness()
void LinearViscoelasticNormalSpecies::setStiffness (Mdouble new_k)
Allows the spring constant to be changed.
 {
     if (new_k >= 0)
         stiffness_ = new_k;
     else
     {
         logger(ERROR, "setStiffness(%) argument has to be non-negative!", new_k);
     }
 }
References ERROR, logger, and stiffness_.
Referenced by RotatingDrumBidisperseInitialise::actionsAfterTimeStep(), Slide::create_rough_wall(), ParameterStudy1DDemo::createSpecies(), ParameterStudy2DDemo::createSpecies(), InsertionBoundaryMPI2Test::InsertionBoundaryMPI2Test(), InsertionBoundarySelfTest::InsertionBoundarySelfTest(), main(), ParticleInclusion::ParticleInclusion(), protectiveWall::protectiveWall(), SpeciesHandler::readOldObject(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), GranularJet::setSilbert(), setStiffnessAndDissipation(), Drum::setupInitialConditions(), CubicCell::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), DistributionSelfTest::setupInitialConditions(), DistributionToPSDSelfTest::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), MultiplePSDSelfTest::setupInitialConditions(), PSDManualInsertionSelfTest::setupInitialConditions(), SubcriticalMaserBoundarySelfTest::setupInitialConditions(), EllipsoidsBouncingOnWallDemo::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), SphericalSuperQuadricCollision::setupInitialConditions(), VisualisationTest::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), SeparateFilesSelfTest::setupInitialConditions(), ContactDetectionWithWallTester::setupParticleAndWall(), ContactDetectionTester::setupParticles(), SilbertPeriodic::SilbertPeriodic(), and T_protectiveWall::T_protectiveWall().
setStiffnessAndDissipation()
void LinearViscoelasticNormalSpecies::setStiffnessAndDissipation (helpers::KAndDisp new_)
Allows the spring and dissipation constants to be changed simultaneously.
 {
     setStiffness(new_.k);
     setDissipation(new_.disp);
 }
References helpers::KAndDisp::disp, helpers::KAndDisp::k, setDissipation(), and setStiffness().
setStiffnessAndRestitutionCoefficient()
void LinearViscoelasticNormalSpecies::setStiffnessAndRestitutionCoefficient (Mdouble stiffness, Mdouble eps, Mdouble mass)
Sets k, disp such that it matches a given tc and eps for a collision of two copies of P.
Sets k, disp such that it matches a given tc and eps for a collision of two copies of P
Parameters
[in] stiffness stiffness
[in] eps restitution coefficient
[in] harmonic mean of particle masses, \(\frac{2}{1/m1+1/m2}\)
 {
     if (getConstantRestitution()) mass = 1;
     stiffness_ = stiffness;
     setRestitutionCoefficient(eps, mass);
 }
References CRBond_Bessel::eps, BaseNormalForce::getConstantRestitution(), setRestitutionCoefficient(), and stiffness_.
Referenced by main(), ParticleCreation::ParticleCreation(), SilbertPeriodic::set_study(), Packing::setupInitialConditions(), Siegen::Siegen(), StressStrainControl::StressStrainControl(), and viscoElasticUnitTest::viscoElasticUnitTest().
write()
void LinearViscoelasticNormalSpecies::write (std::ostream & os) const
Writes the species properties to an output stream.
Parameters
[out] output stream (typically the restart file)
 {
     os << " stiffness " << stiffness_
        << " dissipation " << dissipation_;
 }
References dissipation_, and stiffness_.
Member Data Documentation
dissipation_
Mdouble LinearViscoelasticNormalSpecies::dissipation_ private
(normal) viscosity
Referenced by computeTimeStep(), getCollisionTime(), getDissipation(), getRestitutionCoefficient(), LinearViscoelasticNormalSpecies(), mix(), read(), setCollisionTimeAndRestitutionCoefficient(), setDissipation(), setRestitutionCoefficient(), and write().
stiffness_
Mdouble LinearViscoelasticNormalSpecies::stiffness_ private
(normal) spring constant
Referenced by computeTimeStep(), getCollisionTime(), getMaximumVelocity(), getStiffness(), LinearViscoelasticNormalSpecies(), mix(), read(), setCollisionTimeAndRestitutionCoefficient(), setStiffness(), setStiffnessAndRestitutionCoefficient(), and write().
The documentation for this class was generated from the following files:
LinearViscoelasticNormalSpecies.h
LinearViscoelasticNormalSpecies.cc