MercuryDPM: Eigen::internal::any_visitor< Scalar > Struct Template Reference
Eigen::internal::any_visitor< Scalar > Struct Template Reference
#include <Visitor.h>
Public Types
using result_type = bool
using Packet = typename packet_traits< Scalar >::type
Public Member Functions
EIGEN_DEVICE_FUNC void init (const Scalar &value, Index, Index)
EIGEN_DEVICE_FUNC void init (const Scalar &value, Index)
EIGEN_DEVICE_FUNC bool any_predux (const Packet &p) const
EIGEN_DEVICE_FUNC void initpacket (const Packet &p, Index, Index)
EIGEN_DEVICE_FUNC void initpacket (const Packet &p, Index)
EIGEN_DEVICE_FUNC void operator() (const Scalar &value, Index, Index)
EIGEN_DEVICE_FUNC void operator() (const Scalar &value, Index)
EIGEN_DEVICE_FUNC void packet (const Packet &p, Index, Index)
EIGEN_DEVICE_FUNC void packet (const Packet &p, Index)
EIGEN_DEVICE_FUNC bool done () const
Public Attributes
bool res = false
Member Typedef Documentation
Packet
template<typename Scalar > using Eigen::internal::any_visitor< Scalar >::Packet = typename packet_traits<Scalar>::type
result_type
template<typename Scalar > using Eigen::internal::any_visitor< Scalar >::result_type = bool
Member Function Documentation
any_predux()
template<typename Scalar > EIGEN_DEVICE_FUNC bool Eigen::internal::any_visitor< Scalar >::any_predux (const Packet & p) const inline
{
     return predux_any(pandnot(ptrue(p), pcmp_eq(p, pzero(p))));
   }
References p, Eigen::internal::pandnot(), Eigen::internal::pcmp_eq(), Eigen::internal::predux_any(), Eigen::internal::ptrue(), and Eigen::internal::pzero().
Referenced by Eigen::internal::any_visitor< Scalar >::initpacket(), and Eigen::internal::any_visitor< Scalar >::packet().
done()
template<typename Scalar > EIGEN_DEVICE_FUNC bool Eigen::internal::any_visitor< Scalar >::done () const inline
 { return res; }
References Eigen::internal::any_visitor< Scalar >::res.
init() [1/2]
template<typename Scalar > EIGEN_DEVICE_FUNC void Eigen::internal::any_visitor< Scalar >::init (const Scalar & value, Index) inline
 { res = (value != Scalar(0)); }
References Eigen::internal::any_visitor< Scalar >::res, and Eigen::value.
init() [2/2]
template<typename Scalar > EIGEN_DEVICE_FUNC void Eigen::internal::any_visitor< Scalar >::init (const Scalar & value, Index , Index) inline
 { res = (value != Scalar(0)); }
References Eigen::internal::any_visitor< Scalar >::res, and Eigen::value.
initpacket() [1/2]
template<typename Scalar > EIGEN_DEVICE_FUNC void Eigen::internal::any_visitor< Scalar >::initpacket (const Packet & p, Index) inline
 { res = any_predux(p); }
References Eigen::internal::any_visitor< Scalar >::any_predux(), p, and Eigen::internal::any_visitor< Scalar >::res.
initpacket() [2/2]
template<typename Scalar > EIGEN_DEVICE_FUNC void Eigen::internal::any_visitor< Scalar >::initpacket (const Packet & p, Index , Index) inline
 { res = any_predux(p); }
References Eigen::internal::any_visitor< Scalar >::any_predux(), p, and Eigen::internal::any_visitor< Scalar >::res.
operator()() [1/2]
template<typename Scalar > EIGEN_DEVICE_FUNC void Eigen::internal::any_visitor< Scalar >::operator() (const Scalar & value, Index) inline
 { res = res || (value != Scalar(0)); }
References Eigen::internal::any_visitor< Scalar >::res, and Eigen::value.
operator()() [2/2]
template<typename Scalar > EIGEN_DEVICE_FUNC void Eigen::internal::any_visitor< Scalar >::operator() (const Scalar & value, Index , Index) inline
 { res = res || (value != Scalar(0)); }
References Eigen::internal::any_visitor< Scalar >::res, and Eigen::value.
packet() [1/2]
template<typename Scalar > EIGEN_DEVICE_FUNC void Eigen::internal::any_visitor< Scalar >::packet (const Packet & p, Index) inline
 { res = res || any_predux(p); }
References Eigen::internal::any_visitor< Scalar >::any_predux(), p, and Eigen::internal::any_visitor< Scalar >::res.
packet() [2/2]
template<typename Scalar > EIGEN_DEVICE_FUNC void Eigen::internal::any_visitor< Scalar >::packet (const Packet & p, Index , Index) inline
 { res = res || any_predux(p); }
References Eigen::internal::any_visitor< Scalar >::any_predux(), p, and Eigen::internal::any_visitor< Scalar >::res.
Member Data Documentation
res
template<typename Scalar > bool Eigen::internal::any_visitor< Scalar >::res = false
Referenced by Eigen::internal::any_visitor< Scalar >::done(), Eigen::internal::any_visitor< Scalar >::init(), Eigen::internal::any_visitor< Scalar >::initpacket(), Eigen::internal::any_visitor< Scalar >::operator()(), and Eigen::internal::any_visitor< Scalar >::packet().
The documentation for this struct was generated from the following file:
Visitor.h