MercuryDPM: Eigen::internal::gemv_static_vector_if< Scalar, Size, Dynamic, true > Struct Template Reference
Eigen::internal::gemv_static_vector_if< Scalar, Size, Dynamic, true > Struct Template Reference
#include <GeneralProduct.h>
Public Member Functions
EIGEN_STRONG_INLINE constexpr EIGEN_DEVICE_FUNC Scalar * data ()
Member Function Documentation
data()
template<typename Scalar , int Size> EIGEN_STRONG_INLINE constexpr EIGEN_DEVICE_FUNC Scalar* Eigen::internal::gemv_static_vector_if< Scalar, Size, Dynamic, true >::data () inline constexpr
 { return 0; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
The documentation for this struct was generated from the following file:
GeneralProduct.h