MercuryDPM: check-makefile-subdirs Namespace Reference
check-makefile-subdirs Namespace Reference
Classes
class Colours
Functions
def highlight (string)
def recursive_find_makefile_ams (base_dirs)
def list_subdirs_with_makefile_ams (base_dir)
def check_makefileam (direc)
def main ()
Variables
COLOURS = Colours()
Function Documentation
check_makefileam()
def check-makefile-subdirs.check_makefileam (direc)
Compare subdirs variable in makefile in direc with actual sub
directories of direc containing a makefile.am (i.e. which can be built).
 def check_makefileam(direc):
     """Compare subdirs variable in makefile in direc with actual sub
     directories of direc containing a makefile.am (i.e. which can be built).
     """
     # Extract the subdirs variable from the Makefile if one exists
     try:
         subdirs_var_string = str(variable_from_makefile("SUBDIRS",
                                                     pjoin(direc, "Makefile")))
     except NoMakefileError:
         print("Makefile not found in", direc)
         subdirs_var_string = ""
     subdirs_var = set(subdirs_var_string.split())
     # Check which subdirs really contain makefile.am s
     subdirs_actual = set(list_subdirs_with_makefile_ams(direc))
     # If theres a difference then report it
     if subdirs_var!= subdirs_actual:
         print("Not the same in:", highlight(direc))
         var_takeout_actual = subdirs_var - subdirs_actual
         print("In makefile SUBDIRS variable but not a sub-directory containing a makefile:\n",
                list(var_takeout_actual))
         actual_takeout_var = subdirs_actual - subdirs_var
         print("Sub-directories containing a makefile but not in SUBDIRS variable:\n",
               list(actual_takeout_var))
         print("\n\n")
         return False
     else:
         return True
References highlight(), list_subdirs_with_makefile_ams(), Eigen::internal.print(), set(), compute_granudrum_aor.str, and parallel_self_test.variable_from_makefile().
highlight()
def check-makefile-subdirs.highlight (string)
 def highlight(string):
     return COLOURS.Header + string + COLOURS.Endc
Referenced by check_makefileam().
list_subdirs_with_makefile_ams()
def check-makefile-subdirs.list_subdirs_with_makefile_ams (base_dir)
Get a list of the sub directories of base_dir which contain a file
called Makefile.am
 def list_subdirs_with_makefile_ams(base_dir):
     """Get a list of the sub directories of base_dir which contain a file
     called Makefile.am
     """
     sub_dirs = []
     for f in glob.glob(pjoin(base_dir, "*", "Makefile.am")):
         d = os.path.dirname(f)
         rel_d = os.path.relpath(d, base_dir)
         sub_dirs.append(rel_d)
     return sub_dirs
Referenced by check_makefileam().
main()
def check-makefile-subdirs.main ()
Compare subdirs variable in makefiles found recursively from the given
root directory with actual sub directories of their directory
containing a makefile.am (i.e. which can be built).
 def main():
     """Compare subdirs variable in makefiles found recursively from the given
     root directory with actual sub directories of their directory
     containing a makefile.am (i.e. which can be built).
     """
     # Parse arguments
     # ============================================================
     parser = argparse.ArgumentParser(description=main.__doc__,
     # Don't mess up my formating in the help message
     formatter_class=argparse.RawDescriptionHelpFormatter)
     parser.add_argument('--oomph-root', '-C', action = "store")
     parser.add_argument('--no-colour', action='store_true',
                         help='Disable colours in output.')
     args = parser.parse_args()
     if args.no_colour:
         COLOURS.disable()
     # Attempt to get the oomph-lib root dir from a Makefile in the current
     # directory.
     if args.oomph_root is None:
         args.oomph_root = parallel_self_test.get_oomph_root()
     # Create list of folders to check
     makefile_ams_to_check = recursive_find_makefile_ams([args.oomph_root])
     # Folders where it is not expected to be true due to various tricks
     skiplist = [pjoin(args.oomph_root, "external_src"),
                 pjoin(args.oomph_root, "external_distributions"),
                 pjoin(args.oomph_root, "demo_drivers", "eigenproblems"),
                 pjoin(args.oomph_root, "demo_drivers", "mpi"),
                 ]
     print("Skipping directories:", skiplist, "\n")
     # Loop over directories and check the makefileams
     successes = map(check_makefileam,
                     [r for r in makefile_ams_to_check if r not in skiplist])
     # Return 0 if all ok, 1 otherwise
     if all(successes):
         return 0
     else:
         return 1
References Eigen::placeholders.all, parallel_self_test.get_oomph_root(), Eigen::internal.print(), and recursive_find_makefile_ams().
recursive_find_makefile_ams()
def check-makefile-subdirs.recursive_find_makefile_ams (base_dirs)
Construct a list of directories to check in by searching for Makefile.am s.
 def recursive_find_makefile_ams(base_dirs):
     """Construct a list of directories to check in by searching for Makefile.am s."""
     sub_dirs = []
     for base in base_dirs:
         for root, dirs, files in os.walk(base):
             if 'Makefile.am' in files:
                 sub_dirs.append(root)
     return sub_dirs
Referenced by main().
Variable Documentation
COLOURS
check-makefile-subdirs.COLOURS = Colours()