MercuryDPM: Eigen::internal::Assignment< DstXprType, Homogeneous< ArgType, Horizontal >, internal::assign_op< Scalar, typename ArgType::Scalar >, Dense2Dense > Struct Template Reference
Eigen::internal::Assignment< DstXprType, Homogeneous< ArgType, Horizontal >, internal::assign_op< Scalar, typename ArgType::Scalar >, Dense2Dense > Struct Template Reference
#include <Homogeneous.h>
Public Types
typedef Homogeneous< ArgType, Horizontal > SrcXprType
Static Public Member Functions
static EIGEN_DEVICE_FUNC void run (DstXprType &dst, const SrcXprType &src, const internal::assign_op< Scalar, typename ArgType::Scalar > &)
Member Typedef Documentation
SrcXprType
template<typename DstXprType , typename ArgType , typename Scalar > typedef Homogeneous<ArgType, Horizontal> Eigen::internal::Assignment< DstXprType, Homogeneous< ArgType, Horizontal >, internal::assign_op< Scalar, typename ArgType::Scalar >, Dense2Dense >::SrcXprType
Member Function Documentation
run()
template<typename DstXprType , typename ArgType , typename Scalar > static EIGEN_DEVICE_FUNC void Eigen::internal::Assignment< DstXprType, Homogeneous< ArgType, Horizontal >, internal::assign_op< Scalar, typename ArgType::Scalar >, Dense2Dense >::run (DstXprType & dst, const SrcXprType & src, const internal::assign_op< Scalar, typename ArgType::Scalar > &) inline static
{
     Index dstRows = src.rows();
     Index dstCols = src.cols();
     if ((dst.rows() != dstRows) || (dst.cols() != dstCols)) dst.resize(dstRows, dstCols);
     dst.template leftCols<ArgType::ColsAtCompileTime>(src.nestedExpression().cols()) = src.nestedExpression();
     dst.col(dst.cols() - 1).setOnes();
   }
References Eigen::Homogeneous< MatrixType, Direction_ >::cols(), Eigen::Homogeneous< MatrixType, Direction_ >::nestedExpression(), and Eigen::Homogeneous< MatrixType, Direction_ >::rows().
The documentation for this struct was generated from the following file:
Homogeneous.h