MercuryDPM: class_FullPivLU.cpp File Reference
class_FullPivLU.cpp File Reference
Typedefs
typedef Matrix< double, 5, 3 > Matrix5x3
typedef Matrix< double, 5, 5 > Matrix5x5
Functions
cout<< "Here is the matrix m:"<< endl<< m<< endl;Eigen::FullPivLU< Matrix5x3 > lu (m)
cout<< "Here is, up to permutations, its LU decomposition matrix:"<< endl<< lu.matrixLU()<< endl;cout<< "Here is the L part:"<< endl;Matrix5x5 l=Matrix5x5::Identity();l.block< 5, 3 > (0, 0).triangularView< StrictlyLower >()
cout<< l<< endl;cout<< "Here is the U part:"<< endl;Matrix5x3 u=lu.matrixLU().triangularView< Upper > ()
Variables
Matrix5x3 m = Matrix5x3::Random()
Typedef Documentation
Matrix5x3
typedef Matrix<double, 5, 3> Matrix5x3
Matrix5x5
typedef Matrix<double, 5, 5> Matrix5x5
Function Documentation
cout<< "Here is, up to permutations, its LU decomposition matrix:"<< endl<< lu.matrixLU()<< endl;cout<< "Here is the L part:"<< endl;Matrix5x5 l=Matrix5x5::Identity();l.block< 5, 3 >()
cout<< "Here is, up to permutations, its LU decomposition matrix:"<< endl<< lu.matrixLU()<< endl;cout<< "Here is the L part:"<< endl;Matrix5x5 l=Matrix5x5::Identity();l.block< 5, 3 > (0 , 0)
cout<< l<< endl;cout<< "Here is the U part:"<< endl;Matrix5x3 u=lu.matrixLU().triangularView< Upper >()
cout<< l<< endl;cout<< "Here is the U part:"<< endl;Matrix5x3 u=lu.matrixLU().triangularView< Upper > ()
lu()
cout<< "Here is the matrix m:" << endl << m << endl;Eigen::FullPivLU<Matrix5x3> lu (m)
Referenced by bench(), Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex, SizeAtCompileTime >::blocked_lu(), doEigen(), Eigen::SplineFitting< SplineType >::InterpolateWithDerivatives(), lu_invertible(), lu_non_invertible(), lu_verify_assert(), main(), Eigen::internal::partial_lu_inplace(), and Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex, SizeAtCompileTime >::unblocked_lu().
Variable Documentation
m
Matrix5x3 m = Matrix5x3::Random()