MercuryDPM: Eigen::HouseholderQR< MatrixType_ > Class Template Reference
Eigen::HouseholderQR< MatrixType_ > Class Template Reference
Dense linear problems and decompositions » Reference » QR_Module
Householder QR decomposition of a matrix.
#include <HouseholderQR.h>
Public Types
enum { MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime , MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef MatrixType_ MatrixType
typedef SolverBase< HouseholderQR > Base
typedef Matrix< Scalar, RowsAtCompileTime, RowsAtCompileTime,(MatrixType::Flags &RowMajorBit) ? RowMajor :ColMajor, MaxRowsAtCompileTime, MaxRowsAtCompileTime > MatrixQType
typedef internal::plain_diag_type< MatrixType >::type HCoeffsType
typedef internal::plain_row_type< MatrixType >::type RowVectorType
typedef HouseholderSequence< MatrixType, internal::remove_all_t< typename HCoeffsType::ConjugateReturnType > > HouseholderSequenceType
Public Types inherited from Eigen::SolverBase< HouseholderQR< MatrixType_ > >
enum
typedef EigenBase< HouseholderQR< MatrixType_ > > Base
typedef internal::traits< HouseholderQR< MatrixType_ > >::Scalar Scalar
typedef Scalar CoeffReturnType
typedef Transpose< const HouseholderQR< MatrixType_ > > ConstTransposeReturnType
typedef std::conditional_t< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, const ConstTransposeReturnType >, const ConstTransposeReturnType > AdjointReturnType
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
HouseholderQR ()
Default Constructor.
HouseholderQR (Index rows, Index cols)
Default Constructor with memory preallocation.
template<typename InputType >
HouseholderQR (const EigenBase< InputType > &matrix)
Constructs a QR factorization from a given matrix.
template<typename InputType >
HouseholderQR (EigenBase< InputType > &matrix)
Constructs a QR factorization from a given matrix.
HouseholderSequenceType householderQ () const
const MatrixType & matrixQR () const
template<typename InputType >
HouseholderQR & compute (const EigenBase< InputType > &matrix)
MatrixType::Scalar determinant () const
MatrixType::RealScalar absDeterminant () const
MatrixType::RealScalar logAbsDeterminant () const
MatrixType::Scalar signDeterminant () const
Index rows () const
Index cols () const
const HCoeffsType & hCoeffs () const
template<typename RhsType , typename DstType >
void _solve_impl (const RhsType &rhs, DstType &dst) const
template<bool Conjugate, typename RhsType , typename DstType >
void _solve_impl_transposed (const RhsType &rhs, DstType &dst) const
Public Member Functions inherited from Eigen::SolverBase< HouseholderQR< MatrixType_ > >
SolverBase ()
~SolverBase ()
const Solve< HouseholderQR< MatrixType_ >, Rhs > solve (const MatrixBase< Rhs > &b) const
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
constexpr EIGEN_DEVICE_FUNC HouseholderQR< MatrixType_ > & derived ()
constexpr EIGEN_DEVICE_FUNC const HouseholderQR< MatrixType_ > & derived () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
constexpr EIGEN_DEVICE_FUNC Derived & derived ()
constexpr EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< Derived, Device > device (Device &device)
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const Derived, Device > device (Device &device) const
Protected Member Functions
void computeInPlace ()
Protected Member Functions inherited from Eigen::SolverBase< HouseholderQR< MatrixType_ > >
void _check_solve_assertion (const Rhs &b) const
Protected Attributes
MatrixType m_qr
HCoeffsType m_hCoeffs
RowVectorType m_temp
bool m_isInitialized
Friends
class SolverBase< HouseholderQR >
Detailed Description
template<typename MatrixType_>
class Eigen::HouseholderQR< MatrixType_ >
Householder QR decomposition of a matrix.
Template Parameters
MatrixType_ the type of the matrix of which we are computing the QR decomposition
This class performs a QR decomposition of a matrix A into matrices Q and R such that
\[ \mathbf{A} = \mathbf{Q} \, \mathbf{R} \]
by using Householder transformations. Here, Q a unitary matrix and R an upper triangular matrix. The result is stored in a compact way compatible with LAPACK.
Note that no pivoting is performed. This is not a rank-revealing decomposition. If you want that feature, use FullPivHouseholderQR or ColPivHouseholderQR instead.
This Householder QR decomposition is faster, but less numerically stable and less feature-full than FullPivHouseholderQR or ColPivHouseholderQR.
This class supports the inplace decomposition mechanism.
See also
MatrixBase::householderQr()
Member Typedef Documentation
Base
template<typename MatrixType_ > typedef SolverBase<HouseholderQR> Eigen::HouseholderQR< MatrixType_ >::Base
HCoeffsType
template<typename MatrixType_ > typedef internal::plain_diag_type<MatrixType>::type Eigen::HouseholderQR< MatrixType_ >::HCoeffsType
HouseholderSequenceType
template<typename MatrixType_ > typedef HouseholderSequence<MatrixType, internal::remove_all_t<typename HCoeffsType::ConjugateReturnType> > Eigen::HouseholderQR< MatrixType_ >::HouseholderSequenceType
MatrixQType
template<typename MatrixType_ > typedef Matrix<Scalar, RowsAtCompileTime, RowsAtCompileTime, (MatrixType::Flags & RowMajorBit) ? RowMajor : ColMajor, MaxRowsAtCompileTime, MaxRowsAtCompileTime> Eigen::HouseholderQR< MatrixType_ >::MatrixQType
MatrixType
template<typename MatrixType_ > typedef MatrixType_ Eigen::HouseholderQR< MatrixType_ >::MatrixType
RowVectorType
template<typename MatrixType_ > typedef internal::plain_row_type<MatrixType>::type Eigen::HouseholderQR< MatrixType_ >::RowVectorType
Member Enumeration Documentation
anonymous enum
template<typename MatrixType_ > anonymous enum
Enumerator
MaxRowsAtCompileTime
MaxColsAtCompileTime
        {
     MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
     MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
   };
Constructor & Destructor Documentation
HouseholderQR() [1/4]
template<typename MatrixType_ > Eigen::HouseholderQR< MatrixType_ >::HouseholderQR () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via HouseholderQR::compute(const MatrixType&).
 : m_qr(), m_hCoeffs(), m_temp(), m_isInitialized(false) {}
HouseholderQR() [2/4]
template<typename MatrixType_ > Eigen::HouseholderQR< MatrixType_ >::HouseholderQR (Index rows, Index cols) inline
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
HouseholderQR()
       : m_qr(rows, cols), m_hCoeffs((std::min)(rows, cols)), m_temp(cols), m_isInitialized(false) {}
HouseholderQR() [3/4]
template<typename MatrixType_ > template<typename InputType > Eigen::HouseholderQR< MatrixType_ >::HouseholderQR (const EigenBase< InputType > & matrix) inline explicit
Constructs a QR factorization from a given matrix.
This constructor computes the QR factorization of the matrix matrix by calling the method compute(). It is a short cut for:
HouseholderQR<MatrixType> qr(matrix.rows(), matrix.cols());
qr.compute(matrix);
See also
compute()
       : m_qr(matrix.rows(), matrix.cols()),
         m_hCoeffs((std::min)(matrix.rows(), matrix.cols())),
         m_temp(matrix.cols()),
         m_isInitialized(false) {
     compute(matrix.derived());
   }
References Eigen::HouseholderQR< MatrixType_ >::compute(), and matrix().
HouseholderQR() [4/4]
template<typename MatrixType_ > template<typename InputType > Eigen::HouseholderQR< MatrixType_ >::HouseholderQR (EigenBase< InputType > & matrix) inline explicit
Constructs a QR factorization from a given matrix.
This overloaded constructor is provided for inplace decomposition when MatrixType is a Eigen::Ref.
See also
HouseholderQR(const EigenBase&)
       : m_qr(matrix.derived()),
         m_hCoeffs((std::min)(matrix.rows(), matrix.cols())),
         m_temp(matrix.cols()),
         m_isInitialized(false) {
     computeInPlace();
   }
References Eigen::HouseholderQR< MatrixType_ >::computeInPlace().
Member Function Documentation
_solve_impl()
template<typename MatrixType_ > template<typename RhsType , typename DstType > void Eigen::HouseholderQR< MatrixType_ >::_solve_impl (const RhsType & rhs, DstType & dst) const
{
   const Index rank = (std::min)(rows(), cols());
   typename RhsType::PlainObject c(rhs);
   c.applyOnTheLeft(householderQ().setLength(rank).adjoint());
   m_qr.topLeftCorner(rank, rank).template triangularView<Upper>().solveInPlace(c.topRows(rank));
   dst.topRows(rank) = c.topRows(rank);
   dst.bottomRows(cols() - rank).setZero();
 }
References Eigen::SolverBase< HouseholderQR< MatrixType_ > >::adjoint(), calibrate::c, Eigen::HouseholderQR< MatrixType_ >::cols(), Eigen::HouseholderQR< MatrixType_ >::householderQ(), Eigen::HouseholderQR< MatrixType_ >::m_qr, min, and Eigen::HouseholderQR< MatrixType_ >::rows().
_solve_impl_transposed()
template<typename MatrixType_ > template<bool Conjugate, typename RhsType , typename DstType > void Eigen::HouseholderQR< MatrixType_ >::_solve_impl_transposed (const RhsType & rhs, DstType & dst) const
{
   const Index rank = (std::min)(rows(), cols());
   typename RhsType::PlainObject c(rhs);
   m_qr.topLeftCorner(rank, rank)
       .template triangularView<Upper>()
       .transpose()
       .template conjugateIf<Conjugate>()
       .solveInPlace(c.topRows(rank));
   dst.topRows(rank) = c.topRows(rank);
   dst.bottomRows(rows() - rank).setZero();
   dst.applyOnTheLeft(householderQ().setLength(rank).template conjugateIf<!Conjugate>());
 }
References calibrate::c, Eigen::HouseholderQR< MatrixType_ >::cols(), Eigen::HouseholderQR< MatrixType_ >::householderQ(), Eigen::HouseholderQR< MatrixType_ >::m_qr, min, and Eigen::HouseholderQR< MatrixType_ >::rows().
absDeterminant()
template<typename MatrixType > MatrixType::RealScalar Eigen::HouseholderQR< MatrixType >::absDeterminant
Returns
the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow. One way to work around that is to use logAbsDeterminant() instead. Also, do not rely on the determinant being exactly zero for testing singularity or rank-deficiency.
See also
determinant(), logAbsDeterminant(), MatrixBase::determinant()
{
   using std::abs;
   eigen_assert(m_isInitialized && "HouseholderQR is not initialized.");
   eigen_assert(m_qr.rows() == m_qr.cols() && "You can't take the determinant of a non-square matrix!");
   return abs(m_qr.diagonal().prod());
 }
References abs(), eigen_assert, Eigen::HouseholderQR< MatrixType_ >::m_isInitialized, and Eigen::HouseholderQR< MatrixType_ >::m_qr.
cols()
template<typename MatrixType_ > Index Eigen::HouseholderQR< MatrixType_ >::cols () const inline
 { return m_qr.cols(); }
References Eigen::HouseholderQR< MatrixType_ >::m_qr.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), Eigen::HouseholderQR< MatrixType_ >::_solve_impl(), Eigen::HouseholderQR< MatrixType_ >::_solve_impl_transposed(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::HouseholderQR< MatrixType_ >::computeInPlace(), Eigen::internal::householder_qr_inplace_unblocked(), Eigen::internal::householder_qr_inplace_blocked< MatrixQR, HCoeffs, MatrixQRScalar, InnerStrideIsOne >::run(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
compute()
template<typename MatrixType_ > template<typename InputType > HouseholderQR& Eigen::HouseholderQR< MatrixType_ >::compute (const EigenBase< InputType > & matrix) inline
{
     m_qr = matrix.derived();
     computeInPlace();
     return *this;
   }
References Eigen::HouseholderQR< MatrixType_ >::computeInPlace(), Eigen::HouseholderQR< MatrixType_ >::m_qr, and matrix().
Referenced by ctms_decompositions(), and Eigen::HouseholderQR< MatrixType_ >::HouseholderQR().
computeInPlace()
template<typename MatrixType > void Eigen::HouseholderQR< MatrixType >::computeInPlace protected
Performs the QR factorization of the given matrix matrix. The result of the factorization is stored into *this, and a reference to *this is returned.
See also
class HouseholderQR, HouseholderQR(const MatrixType&)
{
   Index rows = m_qr.rows();
   Index cols = m_qr.cols();
   Index size = (std::min)(rows, cols);
   m_hCoeffs.resize(size);
   m_temp.resize(cols);
   internal::householder_qr_inplace_blocked<MatrixType, HCoeffsType>::run(m_qr, m_hCoeffs, 48, m_temp.data());
   m_isInitialized = true;
 }
References Eigen::HouseholderQR< MatrixType_ >::cols(), Eigen::HouseholderQR< MatrixType_ >::m_hCoeffs, Eigen::HouseholderQR< MatrixType_ >::m_isInitialized, Eigen::HouseholderQR< MatrixType_ >::m_qr, Eigen::HouseholderQR< MatrixType_ >::m_temp, min, Eigen::HouseholderQR< MatrixType_ >::rows(), Eigen::internal::householder_qr_inplace_blocked< MatrixQR, HCoeffs, MatrixQRScalar, InnerStrideIsOne >::run(), and Eigen::EigenBase< Derived >::size().
Referenced by Eigen::HouseholderQR< MatrixType_ >::compute(), and Eigen::HouseholderQR< MatrixType_ >::HouseholderQR().
determinant()
template<typename MatrixType > MatrixType::Scalar Eigen::HouseholderQR< MatrixType >::determinant
Returns
the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow. One way to work around that is to use logAbsDeterminant() instead. Also, do not rely on the determinant being exactly zero for testing singularity or rank-deficiency.
See also
absDeterminant(), logAbsDeterminant(), MatrixBase::determinant()
{
   eigen_assert(m_isInitialized && "HouseholderQR is not initialized.");
   eigen_assert(m_qr.rows() == m_qr.cols() && "You can't take the determinant of a non-square matrix!");
   Scalar detQ;
   internal::householder_determinant<HCoeffsType, Scalar, NumTraits<Scalar>::IsComplex>::run(m_hCoeffs, detQ);
   return m_qr.diagonal().prod() * detQ;
 }
References eigen_assert, Eigen::HouseholderQR< MatrixType_ >::m_hCoeffs, Eigen::HouseholderQR< MatrixType_ >::m_isInitialized, Eigen::HouseholderQR< MatrixType_ >::m_qr, and Eigen::run().
hCoeffs()
template<typename MatrixType_ > const HCoeffsType& Eigen::HouseholderQR< MatrixType_ >::hCoeffs () const inline
Returns
a const reference to the vector of Householder coefficients used to represent the factor Q.
For advanced uses only.
 { return m_hCoeffs; }
References Eigen::HouseholderQR< MatrixType_ >::m_hCoeffs.
Referenced by Eigen::internal::householder_qr_inplace_unblocked(), Eigen::internal::householder_qr_inplace_update(), Eigen::internal::householder_determinant< HCoeffs, Scalar, IsComplex >::run(), Eigen::internal::householder_determinant< HCoeffs, Scalar, false >::run(), and Eigen::internal::householder_qr_inplace_blocked< MatrixQR, HCoeffs, MatrixQRScalar, InnerStrideIsOne >::run().
householderQ()
template<typename MatrixType_ > HouseholderSequenceType Eigen::HouseholderQR< MatrixType_ >::householderQ (void) const inline
This method returns an expression of the unitary matrix Q as a sequence of Householder transformations.
The returned expression can directly be used to perform matrix products. It can also be assigned to a dense Matrix object. Here is an example showing how to recover the full or thin matrix Q, as well as how to perform matrix products using operator*:
Example:
MatrixXf A(MatrixXf::Random(5, 3)), thinQ(MatrixXf::Identity(5, 3)), Q;
A.setRandom();
HouseholderQR<MatrixXf> qr(A);
Q = qr.householderQ();
thinQ = qr.householderQ() * thinQ;
std::cout << "The complete unitary matrix Q is:\n" << Q << "\n\n";
std::cout << "The thin matrix Q is:\n" << thinQ << "\n\n";
Output:
{
     eigen_assert(m_isInitialized && "HouseholderQR is not initialized.");
     return HouseholderSequenceType(m_qr, m_hCoeffs.conjugate());
   }
References eigen_assert, Eigen::HouseholderQR< MatrixType_ >::m_hCoeffs, Eigen::HouseholderQR< MatrixType_ >::m_isInitialized, and Eigen::HouseholderQR< MatrixType_ >::m_qr.
Referenced by Eigen::HouseholderQR< MatrixType_ >::_solve_impl(), Eigen::HouseholderQR< MatrixType_ >::_solve_impl_transposed(), Eigen::createRandomPIMatrixOfRank(), Eigen::RealQZ< MatrixType_ >::hessenbergTriangular(), qr(), randomMatrixWithRealEivals(), randomMatrixWithImagEivals< MatrixType, 0 >::run(), randomMatrixWithImagEivals< MatrixType, 1 >::run(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveNumericalDiffOneStep(), and Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveOneStep().
logAbsDeterminant()
template<typename MatrixType > MatrixType::RealScalar Eigen::HouseholderQR< MatrixType >::logAbsDeterminant
Returns
the natural log of the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
This method is useful to work around the risk of overflow/underflow that's inherent to determinant computation.
Warning
Do not rely on the determinant being exactly zero for testing singularity or rank-deficiency.
See also
determinant(), absDeterminant(), MatrixBase::determinant()
{
   eigen_assert(m_isInitialized && "HouseholderQR is not initialized.");
   eigen_assert(m_qr.rows() == m_qr.cols() && "You can't take the determinant of a non-square matrix!");
   return m_qr.diagonal().cwiseAbs().array().log().sum();
 }
References eigen_assert, Eigen::HouseholderQR< MatrixType_ >::m_isInitialized, and Eigen::HouseholderQR< MatrixType_ >::m_qr.
matrixQR()
template<typename MatrixType_ > const MatrixType& Eigen::HouseholderQR< MatrixType_ >::matrixQR () const inline
Returns
a reference to the matrix where the Householder QR decomposition is stored in a LAPACK-compatible way.
{
     eigen_assert(m_isInitialized && "HouseholderQR is not initialized.");
     return m_qr;
   }
References eigen_assert, Eigen::HouseholderQR< MatrixType_ >::m_isInitialized, and Eigen::HouseholderQR< MatrixType_ >::m_qr.
Referenced by Eigen::RealQZ< MatrixType_ >::hessenbergTriangular(), qr(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveNumericalDiffOneStep(), and Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveOneStep().
rows()
template<typename MatrixType_ > Index Eigen::HouseholderQR< MatrixType_ >::rows () const inline
 { return m_qr.rows(); }
References Eigen::HouseholderQR< MatrixType_ >::m_qr.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), Eigen::HouseholderQR< MatrixType_ >::_solve_impl(), Eigen::HouseholderQR< MatrixType_ >::_solve_impl_transposed(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::HouseholderQR< MatrixType_ >::computeInPlace(), Eigen::internal::householder_qr_inplace_unblocked(), Eigen::internal::householder_qr_inplace_update(), Eigen::internal::householder_qr_inplace_blocked< MatrixQR, HCoeffs, MatrixQRScalar, InnerStrideIsOne >::run(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
signDeterminant()
template<typename MatrixType > MatrixType::Scalar Eigen::HouseholderQR< MatrixType >::signDeterminant
Returns
the sign of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
This method is useful to work around the risk of overflow/underflow that's inherent to determinant computation.
Warning
Do not rely on the determinant being exactly zero for testing singularity or rank-deficiency.
See also
determinant(), absDeterminant(), MatrixBase::determinant()
{
   eigen_assert(m_isInitialized && "HouseholderQR is not initialized.");
   eigen_assert(m_qr.rows() == m_qr.cols() && "You can't take the determinant of a non-square matrix!");
   Scalar detQ;
   internal::householder_determinant<HCoeffsType, Scalar, NumTraits<Scalar>::IsComplex>::run(m_hCoeffs, detQ);
   return detQ * m_qr.diagonal().array().sign().prod();
 }
References eigen_assert, Eigen::HouseholderQR< MatrixType_ >::m_hCoeffs, Eigen::HouseholderQR< MatrixType_ >::m_isInitialized, Eigen::HouseholderQR< MatrixType_ >::m_qr, and Eigen::run().
Friends And Related Function Documentation
SolverBase< HouseholderQR >
template<typename MatrixType_ > friend class SolverBase< HouseholderQR > friend
Member Data Documentation
m_hCoeffs
template<typename MatrixType_ > HCoeffsType Eigen::HouseholderQR< MatrixType_ >::m_hCoeffs protected
Referenced by Eigen::HouseholderQR< MatrixType_ >::computeInPlace(), Eigen::HouseholderQR< MatrixType_ >::determinant(), Eigen::HouseholderQR< MatrixType_ >::hCoeffs(), Eigen::HouseholderQR< MatrixType_ >::householderQ(), and Eigen::HouseholderQR< MatrixType_ >::signDeterminant().
m_isInitialized
template<typename MatrixType_ > bool Eigen::HouseholderQR< MatrixType_ >::m_isInitialized protected
Referenced by Eigen::HouseholderQR< MatrixType_ >::absDeterminant(), Eigen::HouseholderQR< MatrixType_ >::computeInPlace(), Eigen::HouseholderQR< MatrixType_ >::determinant(), Eigen::HouseholderQR< MatrixType_ >::householderQ(), Eigen::HouseholderQR< MatrixType_ >::logAbsDeterminant(), Eigen::HouseholderQR< MatrixType_ >::matrixQR(), and Eigen::HouseholderQR< MatrixType_ >::signDeterminant().
m_qr
template<typename MatrixType_ > MatrixType Eigen::HouseholderQR< MatrixType_ >::m_qr protected
Referenced by Eigen::HouseholderQR< MatrixType_ >::_solve_impl(), Eigen::HouseholderQR< MatrixType_ >::_solve_impl_transposed(), Eigen::HouseholderQR< MatrixType_ >::absDeterminant(), Eigen::HouseholderQR< MatrixType_ >::cols(), Eigen::HouseholderQR< MatrixType_ >::compute(), Eigen::HouseholderQR< MatrixType_ >::computeInPlace(), Eigen::HouseholderQR< MatrixType_ >::determinant(), Eigen::HouseholderQR< MatrixType_ >::householderQ(), Eigen::HouseholderQR< MatrixType_ >::logAbsDeterminant(), Eigen::HouseholderQR< MatrixType_ >::matrixQR(), Eigen::HouseholderQR< MatrixType_ >::rows(), and Eigen::HouseholderQR< MatrixType_ >::signDeterminant().
m_temp
template<typename MatrixType_ > RowVectorType Eigen::HouseholderQR< MatrixType_ >::m_temp protected
Referenced by Eigen::HouseholderQR< MatrixType_ >::computeInPlace().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
HouseholderQR.h