MercuryDPM: oomph::VectorHelpers Namespace Reference
oomph::VectorHelpers Namespace Reference
Namespace for helper functions for Vector<double>
Functions
double two_norm (const Vector< double > &a)
Vector< double > vector_diff (const Vector< double > &a, const Vector< double > &b)
void check_lengths_match (const Vector< double > &a, const Vector< double > &b)
Check the lengths if two Vectors are the same length.
double dot (const Vector< double > &a, const Vector< double > &b)
double magnitude (const Vector< double > &a)
Get the magnitude of a vector.
double angle (const Vector< double > &a, const Vector< double > &b)
Get the angle between two vector.
void cross (const Vector< double > &A, const Vector< double > &B, Vector< double > &C)
Vector< double > cross (const Vector< double > &A, const Vector< double > &B)
Detailed Description
Namespace for helper functions for Vector<double>
Function Documentation
angle()
double oomph::VectorHelpers::angle (const Vector< double > & a, const Vector< double > & b) inline
Get the angle between two vector.
     {
       // Notice that we use one square root operation by avoiding the
       // call to magnitude(...)
       return std::acos(dot(a, b) / std::sqrt(dot(a, a) * dot(b, b)));
     }
References a, acos(), b, dot(), and sqrt().
Referenced by oomph::FaceElement::continuous_tangent_and_outer_unit_normal().
check_lengths_match()
void oomph::VectorHelpers::check_lengths_match (const Vector< double > & a, const Vector< double > & b) inline
Check the lengths if two Vectors are the same length.
     {
 #ifdef PARANOID
       if (a.size() != b.size())
       {
         std::ostringstream err;
         err << "Vectors must be the same length."
             << "len(a) = " << a.size() << ", "
             << "len(b) = " << b.size() << ".";
         throw OomphLibError(
           err.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
     }
References a, b, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by dot(), and vector_diff().
cross() [1/2]
Vector<double> oomph::VectorHelpers::cross (const Vector< double > & A, const Vector< double > & B) inline
Cross product using "proper" output (move semantics means this is ok This calls the other cross(...) function.
     {
       Vector<double> output(3, 0.0);
       cross(A, B, output);
       return output;
     }
References cross(), and oomph::output().
cross() [2/2]
void oomph::VectorHelpers::cross (const Vector< double > & A, const Vector< double > & B, Vector< double > & C) inline
Cross product using "proper" output (move semantics means this is ok nowadays).
     {
 #ifdef PARANOID
       if ((A.size() != 3) || (B.size() != 3) || (C.size() != 3))
       {
         std::ostringstream err;
         err << "Cross product only defined for vectors of length 3.\n"
             << "len(a) = " << A.size() << ", "
             << "len(b) = " << B.size() << ", "
             << "len(c) = " << C.size() << ".";
         throw OomphLibError(
           err.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       C[0] = A[1] * B[2] - A[2] * B[1];
       C[1] = A[2] * B[0] - A[0] * B[2];
       C[2] = A[0] * B[1] - A[1] * B[0];
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by ChuteWithPeriodicInflow::computeInternalForces(), oomph::FaceElement::continuous_tangent_and_outer_unit_normal(), cross(), oomph::SCoupledElement< ELEMENT >::get_momentum_and_energy(), oomph::VolumeCoupledElement< ELEMENT >::get_momentum_and_energy(), SolidProblem< ELEMENT_TYPE >::getMassMomentumEnergy(), and oomph::FaceElement::outer_unit_normal().
dot()
double oomph::VectorHelpers::dot (const Vector< double > & a, const Vector< double > & b) inline
Probably not always best/fastest because not optimised for dimension but useful...
     {
       check_lengths_match(a, b);
       double temp = 0;
       for (unsigned i = 0, ni = a.size(); i < ni; i++)
       {
         temp += a[i] * b[i];
       }
       return temp;
     }
References a, b, check_lengths_match(), and i.
Referenced by angle(), oomph::FaceElement::continuous_tangent_and_outer_unit_normal(), magnitude(), and two_norm().
magnitude()
double oomph::VectorHelpers::magnitude (const Vector< double > & a) inline
Get the magnitude of a vector.
     {
       return (std::sqrt(dot(a, a)));
     }
References a, dot(), and sqrt().
Referenced by Global_Parameters::body_force(), oomph::FaceElement::continuous_tangent_and_outer_unit_normal(), oomph::FaceElement::outer_unit_normal(), Global_Parameters::pressure_load(), oomph::HelmholtzPointSourceElement< ELEMENT >::setup(), oomph::PMLHelmholtzPointSourceElement< ELEMENT >::setup(), HelmholtzPointSourceProblem< ELEMENT >::setup_point_source(), and Global_Parameters::velocity_couette().
two_norm()
double oomph::VectorHelpers::two_norm (const Vector< double > & a) inline
   {
    return std::sqrt(dot(a,a));
   }
References a, dot(), and sqrt().
Referenced by oomph::YoungLaplaceContactAngleElement< ELEMENT >::actual_cos_contact_angle(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::fill_in_contribution_to_residuals(), and oomph::ODEProblem::get_error_norm().
vector_diff()
Vector<double> oomph::VectorHelpers::vector_diff (const Vector< double > & a, const Vector< double > & b) inline
   {
    check_lengths_match(a,b);
    unsigned ni = a.size();
    Vector<double> diff(ni, 0.0);
    for(unsigned i=0; i<ni; i++) {diff[i] = a[i] - b[i];}
    return diff;
   }
References a, b, check_lengths_match(), and i.
Referenced by oomph::ODEProblem::get_error_norm().