MercuryDPM: Eigen::placeholders Namespace Reference
Eigen::placeholders Namespace Reference
Typedefs
typedef symbolic::SymbolExpr< internal::symbolic_last_tag > last_t
typedef symbolic::AddExpr< symbolic::SymbolExpr< internal::symbolic_last_tag >, symbolic::ValueExpr< Eigen::internal::FixedInt< 1 > > > lastp1_t
typedef Eigen::internal::all_t all_t
Functions
template<typename SizeType , typename IncrType >
auto lastN (SizeType size, IncrType incr) -> decltype(seqN(Eigen::placeholders::last -(size - fix< 1 >()) *incr, size, incr))
template<typename SizeType >
auto lastN (SizeType size) -> decltype(seqN(Eigen::placeholders::last+fix< 1 >() - size, size))
Variables
static constexpr const last_t last
static constexpr lastp1_t lastp1 = lastp1_t{}
static constexpr lastp1_t end = lastp1
static constexpr Eigen::internal::all_t all
Typedef Documentation
all_t
typedef Eigen::internal::all_t Eigen::placeholders::all_t
last_t
typedef symbolic::SymbolExpr<internal::symbolic_last_tag> Eigen::placeholders::last_t
lastp1_t
typedef symbolic::AddExpr<symbolic::SymbolExpr<internal::symbolic_last_tag>, symbolic::ValueExpr<Eigen::internal::FixedInt<1> > > Eigen::placeholders::lastp1_t
Function Documentation
lastN() [1/2]
template<typename SizeType > auto Eigen::placeholders::lastN (SizeType size) -> decltype(seqN(Eigen::placeholders::last + fix<1>() - size, size))
\cpp11
Returns
a symbolic ArithmeticSequence representing the last size elements with a unit increment.
It is a shortcut for:
seq(last+fix<1>-size, last)
See also
lastN(SizeType,IncrType, seqN(FirstType,SizeType), seq(FirstType,LastType)
{
   return seqN(Eigen::placeholders::last + fix<1>() - size, size);
 }
References last, Eigen::seqN(), and size.
lastN() [2/2]
template<typename SizeType , typename IncrType > auto Eigen::placeholders::lastN (SizeType size, IncrType incr) -> decltype(seqN(Eigen::placeholders::last - (size - fix<1>()) * incr, size, incr))
\cpp11
Returns
a symbolic ArithmeticSequence representing the last size elements with increment incr.
It is a shortcut for:
seqN(last-(size-fix<1>)*incr, size, incr)
See also
lastN(SizeType), seqN(FirstType,SizeType), seq(FirstType,LastType,IncrType)
{
   return seqN(Eigen::placeholders::last - (size - fix<1>()) * incr, size, incr);
 }
References last, Eigen::seqN(), and size.
Referenced by check_indexed_view(), and check_tutorial_examples().