MercuryDPM: Eigen::internal::triangular_solver_selector< Lhs, Rhs, Side, Mode, NoUnrolling, 1 > Struct Template Reference
Eigen::internal::triangular_solver_selector< Lhs, Rhs, Side, Mode, NoUnrolling, 1 > Struct Template Reference
#include <SolveTriangular.h>
Public Types
typedef Lhs::Scalar LhsScalar
typedef Rhs::Scalar RhsScalar
typedef blas_traits< Lhs > LhsProductTraits
typedef LhsProductTraits::ExtractType ActualLhsType
typedef Map< Matrix< RhsScalar, Dynamic, 1 >, Aligned > MappedRhs
Static Public Member Functions
static EIGEN_DEVICE_FUNC void run (const Lhs &lhs, Rhs &rhs)
Member Typedef Documentation
ActualLhsType
template<typename Lhs , typename Rhs , int Side, int Mode> typedef LhsProductTraits::ExtractType Eigen::internal::triangular_solver_selector< Lhs, Rhs, Side, Mode, NoUnrolling, 1 >::ActualLhsType
LhsProductTraits
template<typename Lhs , typename Rhs , int Side, int Mode> typedef blas_traits<Lhs> Eigen::internal::triangular_solver_selector< Lhs, Rhs, Side, Mode, NoUnrolling, 1 >::LhsProductTraits
LhsScalar
template<typename Lhs , typename Rhs , int Side, int Mode> typedef Lhs::Scalar Eigen::internal::triangular_solver_selector< Lhs, Rhs, Side, Mode, NoUnrolling, 1 >::LhsScalar
MappedRhs
template<typename Lhs , typename Rhs , int Side, int Mode> typedef Map<Matrix<RhsScalar, Dynamic, 1>, Aligned> Eigen::internal::triangular_solver_selector< Lhs, Rhs, Side, Mode, NoUnrolling, 1 >::MappedRhs
RhsScalar
template<typename Lhs , typename Rhs , int Side, int Mode> typedef Rhs::Scalar Eigen::internal::triangular_solver_selector< Lhs, Rhs, Side, Mode, NoUnrolling, 1 >::RhsScalar
Member Function Documentation
run()
template<typename Lhs , typename Rhs , int Side, int Mode> static EIGEN_DEVICE_FUNC void Eigen::internal::triangular_solver_selector< Lhs, Rhs, Side, Mode, NoUnrolling, 1 >::run (const Lhs & lhs, Rhs & rhs) inline static
{
     ActualLhsType actualLhs = LhsProductTraits::extract(lhs);
     // FIXME find a way to allow an inner stride if packet_traits<Scalar>::size==1
     bool useRhsDirectly = Rhs::InnerStrideAtCompileTime == 1 || rhs.innerStride() == 1;
     ei_declare_aligned_stack_constructed_variable(RhsScalar, actualRhs, rhs.size(), (useRhsDirectly ? rhs.data() : 0));
     if (!useRhsDirectly) MappedRhs(actualRhs, rhs.size()) = rhs;
     triangular_solve_vector<LhsScalar, RhsScalar, Index, Side, Mode, LhsProductTraits::NeedToConjugate,
                             (int(Lhs::Flags) & RowMajorBit) ? RowMajor : ColMajor>::run(actualLhs.cols(),
                                                                                         actualLhs.data(),
                                                                                         actualLhs.outerStride(),
                                                                                         actualRhs);
     if (!useRhsDirectly) rhs = MappedRhs(actualRhs, rhs.size());
   }
References Eigen::ColMajor, Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::cols(), ei_declare_aligned_stack_constructed_variable, int(), Eigen::RowMajor, Eigen::RowMajorBit, and Eigen::run().
The documentation for this struct was generated from the following file:
SolveTriangular.h