MercuryDPM: TriangleWallSelfTest.cpp File Reference
TriangleWallSelfTest.cpp File Reference
#include "Mercury3D.h"
#include "Walls/TriangleWall.h"
#include "Species/LinearViscoelasticSpecies.h"
#include "Logger.h"
Functions
int main ()
Function Documentation
main()
int main ()
             {
     Mercury3D dpm;
     dpm.setTimeMax(1);
     dpm.setName("TriangleWallSelfTest");
     dpm.setDomain({0,0,0},{1,1,1});
     dpm.setGravity({0,0,0});
     LinearViscoelasticSpecies species;
     species.setDensity(constants::pi/6.0);
     Mdouble d = .1;
     species.setCollisionTimeAndRestitutionCoefficient(0.5,1.0,d*d*d);
     auto s = dpm.speciesHandler.copyAndAddObject(species);
     dpm.setTimeStep(0.01);
     SphericalParticle particle;
     particle.setSpecies(s);
     particle.setRadius(0.5*d);
     particle.setVelocity({0,0,-.1});
 //    particle.setPosition({0,0,.5*d});
 //    dpm.particleHandler.copyAndAddObject(particle);
     for (Mdouble x=-d/8; x<1+d; x+=d+d/22) {
         for (Mdouble y=-d/8; y<1+d-x; y+=d+d/22) {
             particle.setPosition(Vec3D(x, y, .5*d));
             dpm.particleHandler.copyAndAddObject(particle);
         }
     }
     TriangleWall wall;
     Vec3D A = {0,0,0};
     Vec3D B = {1,0,0};
     Vec3D C = {0,1,0};
     wall.setSpecies(s);
     wall.setVertices(A,B,C);
     dpm.wallHandler.copyAndAddObject(wall);
     dpm.setParticlesWriteVTK(true);
     dpm.wallHandler.setWriteVTK(FileType::ONE_FILE);
     dpm.solve();
 }
References BaseHandler< T >::copyAndAddObject(), ONE_FILE, DPMBase::particleHandler, constants::pi, s, LinearViscoelasticNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), ParticleSpecies::setDensity(), DPMBase::setDomain(), DPMBase::setGravity(), DPMBase::setName(), DPMBase::setParticlesWriteVTK(), BaseInteractable::setPosition(), BaseParticle::setRadius(), BaseParticle::setSpecies(), BaseWall::setSpecies(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), BaseInteractable::setVelocity(), TriangleWall::setVertices(), WallHandler::setWriteVTK(), DPMBase::solve(), DPMBase::speciesHandler, DPMBase::wallHandler, plotDoE::x, and y.