MercuryDPM: Eigen::TranspositionsBase< Derived > Class Template Reference
Eigen::TranspositionsBase< Derived > Class Template Reference
#include <Transpositions.h>
Public Types
typedef Traits::IndicesType IndicesType
typedef IndicesType::Scalar StorageIndex
typedef Eigen::Index Index
Public Member Functions
EIGEN_DEVICE_FUNC Derived & derived ()
EIGEN_DEVICE_FUNC const Derived & derived () const
template<typename OtherDerived >
Derived & operator= (const TranspositionsBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC Index size () const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC const StorageIndex & coeff (Index i) const
StorageIndex & coeffRef (Index i)
const StorageIndex & operator() (Index i) const
StorageIndex & operator() (Index i)
const StorageIndex & operator[] (Index i) const
StorageIndex & operator[] (Index i)
EIGEN_DEVICE_FUNC const IndicesType & indices () const
EIGEN_DEVICE_FUNC IndicesType & indices ()
void resize (Index newSize)
void setIdentity ()
Transpose< TranspositionsBase > inverse () const
Transpose< TranspositionsBase > transpose () const
Private Types
typedef internal::traits< Derived > Traits
Member Typedef Documentation
Index
template<typename Derived > typedef Eigen::Index Eigen::TranspositionsBase< Derived >::Index
Deprecated:
since Eigen 3.3
IndicesType
template<typename Derived > typedef Traits::IndicesType Eigen::TranspositionsBase< Derived >::IndicesType
StorageIndex
template<typename Derived > typedef IndicesType::Scalar Eigen::TranspositionsBase< Derived >::StorageIndex
Traits
template<typename Derived > typedef internal::traits<Derived> Eigen::TranspositionsBase< Derived >::Traits private
Member Function Documentation
coeff()
template<typename Derived > EIGEN_DEVICE_FUNC const StorageIndex& Eigen::TranspositionsBase< Derived >::coeff (Index i) const inline
Direct access to the underlying index vector
 { return indices().coeff(i); }
References i, and Eigen::TranspositionsBase< Derived >::indices().
Referenced by Eigen::PermutationBase< Derived >::operator=().
coeffRef()
template<typename Derived > StorageIndex& Eigen::TranspositionsBase< Derived >::coeffRef (Index i) inline
Direct access to the underlying index vector
 { return indices().coeffRef(i); }
References i, and Eigen::TranspositionsBase< Derived >::indices().
Referenced by Eigen::LDLT< MatrixType_, UpLo_ >::rankUpdate(), and Eigen::TranspositionsBase< Derived >::setIdentity().
cols()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::TranspositionsBase< Derived >::cols () const inline
Returns
the number of columns of the equivalent permutation matrix
 { return indices().size(); }
References Eigen::TranspositionsBase< Derived >::indices().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
derived() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC Derived& Eigen::TranspositionsBase< Derived >::derived () inline
 { return *static_cast<Derived*>(this); }
Referenced by Eigen::TranspositionsBase< Derived >::indices(), Eigen::TranspositionsBase< Derived >::inverse(), Eigen::operator*(), Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::operator=(), Eigen::Map< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >, PacketAccess_ >::operator=(), Eigen::TranspositionsBase< Derived >::operator=(), and Eigen::TranspositionsBase< Derived >::transpose().
derived() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC const Derived& Eigen::TranspositionsBase< Derived >::derived () const inline
 { return *static_cast<const Derived*>(this); }
indices() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC IndicesType& Eigen::TranspositionsBase< Derived >::indices () inline
Returns
a reference to the stored array representing the transpositions.
 { return derived().indices(); }
References Eigen::TranspositionsBase< Derived >::derived().
indices() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC const IndicesType& Eigen::TranspositionsBase< Derived >::indices () const inline
const version of indices().
 { return derived().indices(); }
References Eigen::TranspositionsBase< Derived >::derived().
Referenced by Eigen::TranspositionsBase< Derived >::coeff(), Eigen::TranspositionsBase< Derived >::coeffRef(), Eigen::TranspositionsBase< Derived >::cols(), Eigen::TranspositionsBase< Derived >::operator()(), Eigen::TranspositionsBase< Derived >::operator=(), Eigen::TranspositionsBase< Derived >::operator[](), Eigen::TranspositionsBase< Derived >::resize(), Eigen::TranspositionsBase< Derived >::rows(), Eigen::TranspositionsBase< Derived >::setIdentity(), and Eigen::TranspositionsBase< Derived >::size().
inverse()
template<typename Derived > Transpose<TranspositionsBase> Eigen::TranspositionsBase< Derived >::inverse () const inline
Returns
the inverse transformation
 { return Transpose<TranspositionsBase>(derived()); }
References Eigen::TranspositionsBase< Derived >::derived().
operator()() [1/2]
template<typename Derived > StorageIndex& Eigen::TranspositionsBase< Derived >::operator() (Index i) inline
Direct access to the underlying index vector
 { return indices()(i); }
References i, and Eigen::TranspositionsBase< Derived >::indices().
operator()() [2/2]
template<typename Derived > const StorageIndex& Eigen::TranspositionsBase< Derived >::operator() (Index i) const inline
Direct access to the underlying index vector
 { return indices()(i); }
References i, and Eigen::TranspositionsBase< Derived >::indices().
operator=()
template<typename Derived > template<typename OtherDerived > Derived& Eigen::TranspositionsBase< Derived >::operator= (const TranspositionsBase< OtherDerived > & other) inline
Copies the other transpositions into *this
{
     indices() = other.indices();
     return derived();
   }
References Eigen::TranspositionsBase< Derived >::derived(), and Eigen::TranspositionsBase< Derived >::indices().
Referenced by Eigen::Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::operator=(), and Eigen::TranspositionsWrapper< IndicesType_ >::operator=().
operator[]() [1/2]
template<typename Derived > StorageIndex& Eigen::TranspositionsBase< Derived >::operator[] (Index i) inline
Direct access to the underlying index vector
 { return indices()(i); }
References i, and Eigen::TranspositionsBase< Derived >::indices().
operator[]() [2/2]
template<typename Derived > const StorageIndex& Eigen::TranspositionsBase< Derived >::operator[] (Index i) const inline
Direct access to the underlying index vector
 { return indices()(i); }
References i, and Eigen::TranspositionsBase< Derived >::indices().
resize()
template<typename Derived > void Eigen::TranspositionsBase< Derived >::resize (Index newSize) inline
Resizes to given size.
 { indices().resize(newSize); }
References Eigen::TranspositionsBase< Derived >::indices().
Referenced by Eigen::LDLT< MatrixType_, UpLo_ >::compute(), and Eigen::LDLT< MatrixType_, UpLo_ >::rankUpdate().
rows()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::TranspositionsBase< Derived >::rows () const inline
Returns
the number of rows of the equivalent permutation matrix
 { return indices().size(); }
References Eigen::TranspositionsBase< Derived >::indices().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
setIdentity()
template<typename Derived > void Eigen::TranspositionsBase< Derived >::setIdentity () inline
Sets *this to represents an identity transformation
                      {
     for (StorageIndex i = 0; i < indices().size(); ++i) coeffRef(i) = i;
   }
References Eigen::TranspositionsBase< Derived >::coeffRef(), i, and Eigen::TranspositionsBase< Derived >::indices().
size()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::TranspositionsBase< Derived >::size () const inline
Returns
the number of transpositions
 { return indices().size(); }
References Eigen::TranspositionsBase< Derived >::indices().
Referenced by Eigen::PermutationBase< Derived >::operator=().
transpose()
template<typename Derived > Transpose<TranspositionsBase> Eigen::TranspositionsBase< Derived >::transpose () const inline
Returns
the transpose transformation
 { return Transpose<TranspositionsBase>(derived()); }
References Eigen::TranspositionsBase< Derived >::derived().
Referenced by Eigen::LDLT< MatrixType_, UpLo_ >::_solve_impl_transposed(), and Eigen::LDLT< MatrixType_, UpLo_ >::reconstructedMatrix().
The documentation for this class was generated from the following file:
Transpositions.h