MercuryDPM: unstructured_two_d_circle.cc File Reference
unstructured_two_d_circle.cc File Reference
#include "generic.h"
#include "darcy.h"
#include "meshes/triangle_mesh.h"
Classes
class DarcyProblem< ELEMENT >
Darcy problem.
Namespaces
TestProblem
Namespace for exact solution and problem parameters.
Functions
void TestProblem::source (const Vector< double > &x, Vector< double > &f)
Source function.
void TestProblem::mass_source (const Vector< double > &x, double &m)
Mass source.
void TestProblem::boundary_pressure (const double &time, const Vector< double > &x, const Vector< double > &n, double &result)
Pressure around the boundary of the domain.
void TestProblem::exact_soln (const Vector< double > &x, Vector< double > &soln)
Exact solution: q1,q2,div_q,p.
template<class ELEMENT >
void TestProblem::edge_sign_setup (Mesh *mesh_pt)
int main (int argc, char **argv)
Driver code for Darcy test problem.
Variables
bool TestProblem::Use_point_source_solution =false
double TestProblem::Mass_source_strength =1000.0
Mass source strength.
double TestProblem::Mass_source_decay_exponent =50.0
Mass source strength.
double TestProblem::Element_area =0.01
Target element area for Triangle.
std::string TestProblem::Directory ="RESLT"
The directory in which the solution is output.
Function Documentation
main()
int main (int argc , char ** argv)
Driver code for Darcy test problem.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Output directory
  CommandLineArgs::specify_command_line_flag("--dir",
                                             &TestProblem::Directory);
  // Specify target element area
  CommandLineArgs::specify_command_line_flag("--element_area",
                                             &TestProblem::Element_area);
 // Use "point" mass source
  CommandLineArgs::specify_command_line_flag("--point_mass_source");
 // Doc shape functions etc then quit
  CommandLineArgs::specify_command_line_flag("--doc_shape_functions");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Doc the shape functions -- use smaller target area
  if (CommandLineArgs::command_line_flag_has_been_set("--doc_shape_functions"))
   {
    oomph_info << "Overwriting element area for doc of shape functions\n";
    TestProblem::Element_area=0.1;
   }
  // Use point mass source?
  if (CommandLineArgs::command_line_flag_has_been_set("--point_mass_source"))
   {
    oomph_info << "Using point mass source\n";
    TestProblem::Use_point_source_solution=true;
   }
 #ifdef ADAPTIVE
  // Create problem
  DarcyProblem<ProjectableDarcyElement<TRaviartThomasDarcyElement<1> > > problem;
 #else
  // Create problem
  DarcyProblem<TRaviartThomasDarcyElement<1> > problem;
 #endif
  // Output initial guess for solution
  problem.doc_solution(0);
  // Doc the shape functions
  if (CommandLineArgs::command_line_flag_has_been_set("--doc_shape_functions"))
   {
    problem.doc_shape_functions();
    exit(0);
   }
 #ifdef ADAPTIVE
  // Max. number of adaptations
  unsigned max_adapt=1;
  if (TestProblem::Use_point_source_solution)
   {
    max_adapt=3;
   }
  // Solve the problem with the adaptive Newton's method, allowing
  // up to max_adapt mesh adaptations after every solve.
  problem.newton_solve(max_adapt);
 #else
  // Solve
  problem.newton_solve();
 #endif
  // Doc result
  problem.doc_solution(1);
  return 0;
 }
References oomph::CommandLineArgs::command_line_flag_has_been_set(), TestProblem::Directory, oomph::CommandLineArgs::doc_specified_flags(), TestProblem::Element_area, oomph::oomph_info, oomph::CommandLineArgs::parse_and_assign(), problem, oomph::CommandLineArgs::setup(), oomph::CommandLineArgs::specify_command_line_flag(), and TestProblem::Use_point_source_solution.