MercuryDPM: WearableTriangleMeshWall Class Reference
WearableTriangleMeshWall Class Reference
#include <WearableTriangleMeshWall.h>
Public Member Functions
WearableTriangleMeshWall ()=default
Default constructor.
WearableTriangleMeshWall (const std::vector< Vec3D > &points, const std::vector< std::array< unsigned, 3 >> &cells, const ParticleSpecies *species=nullptr)
Constructor creating triangles.
WearableTriangleMeshWall (const Vec3D &P0, const Vec3D &P1, const Vec3D &P, Mdouble resolutionU, Mdouble resolutionV, const ParticleSpecies *species=nullptr, bool periodicInU=false, bool periodicInV=false)
Constructor creating parallelogram shaped mesh with a given resolution in u- and v-direction.
WearableTriangleMeshWall (const WearableTriangleMeshWall &other)
Copy constructor.
~WearableTriangleMeshWall ()=default
Destructor.
WearableTriangleMeshWall & operator= (const WearableTriangleMeshWall &other)
Copy assignment operator.
WearableTriangleMeshWall * copy () const override
Wall copy method.
void read (std::istream &is) override
Reads a WearableTriangleMeshWall from an input stream, for example a restart file.
void write (std::ostream &os) const override
Writes a WearableTriangleMeshWall to an output stream, for example a restart file.
std::string getName () const override
Returns the name of the object.
void computeWear () override
void setWearCoefficient (Mdouble wearCoefficient)
void setHardness (Mdouble hardness)
void setWearAcceleration (Mdouble wearAcceleration)
Public Member Functions inherited from TriangleMeshWall
TriangleMeshWall ()=default
Default constructor.
TriangleMeshWall (const TriangleMeshWall &other)
Copy constructor.
TriangleMeshWall (const std::vector< Vec3D > &points, const std::vector< std::array< unsigned, 3 >> &cells, const ParticleSpecies *species=nullptr)
Constructor creating triangles.
TriangleMeshWall (const Vec3D &P0, const Vec3D &P1, const Vec3D &P, Mdouble resolutionU, Mdouble resolutionV, const ParticleSpecies *species=nullptr, bool periodicInU=false, bool periodicInV=false)
Constructor creating parallelogram shaped mesh with a given resolution in u- and v-direction.
~TriangleMeshWall () override=default
Destructor.
TriangleMeshWall & operator= (const TriangleMeshWall &other)
Copy assignment operator.
void set (const std::vector< Vec3D > &points, const std::vector< std::array< unsigned, 3 >> &cells)
Set function creating triangles.
bool getDistanceAndNormal (const BaseParticle &p, Mdouble &distance, Vec3D &normal_return) const override
Checks if a collision is happening with any of the TriangleWalls. NOTE: this does not handle actual interactions, but can only be used to know IF one (of possible many) interaction occurs.
BaseInteraction * getInteractionWith (BaseParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler) override
Gets the interaction between a given BaseParticle and all TriangleWalls in this mesh at a given time. In case of multiple contacts, chooses the one with greatest overlap.
void resetForceTorque (int numberOfOMPthreads) override
void writeVTK (VTKContainer &vtk) const override
void setSpecies (const ParticleSpecies *species)
void moveVertex (unsigned index, const Vec3D &dP)
Updates a vertex by a given change in position.
void removeTriangle (unsigned index, bool removeFreeVertex=true)
Removes a single triangle from the mesh.
void refineTriangle (unsigned index, unsigned numberOfTimes=1)
Makes a really basic refinement by adding a vertex in the middle of the triangle to create 3 new ones. Note: Multiple refinements will definitely NOT create a nice mesh.
void setPeriodicCompanions (const std::vector< std::pair< unsigned, unsigned >> &periodicCompanions)
Sets the vector with pairs of indices of vertices which lie on a periodic boundary and are each others 'companion'. E.g. when moving one vertex, the other is also moved the same amount. A vertex can have multiple companions (when lying on multiple periodic boundaries) and those should be in the vector as multiple pairs.
void moveVerticesToMatchVolume (std::vector< Vec3D > displacements, Mdouble targetVolume, int maxNumRecursiveCalls=15)
Moves all vertices by given displacements and corrects to match the change in volume with the target volume. The final displacements will be proportional to the initial ones, but their actual values will have change.
Mdouble getVolumeTetrahedron (const Vec3D &a, const Vec3D &b, const Vec3D &c, const Vec3D &d)
Calculates the volume of a tetrahedron formed by 4 vertices.
void addToMesh (TriangleMeshWall mesh)
Adds a mesh to this mesh. When vertices share a position, only the one in the current mesh is kept and both meshes are then "connected" at that point.
void createParallelogramMesh (const Vec3D &P0, const Vec3D &P1, const Vec3D &P2, Mdouble resolutionU, Mdouble resolutionV, bool periodicInU=false, bool periodicInV=false)
Creates a parallelogram shaped mesh with a given resolution in u- and v-direction.
void createFourPointMesh (const Vec3D &P0, const Vec3D &P1, const Vec3D &P2, const Vec3D &P3, int numSegmentsU, int numSegmentsV)
Creates mesh consisting of four points, with linearly interpolated segments. The points therefore don't necessarily have to lie in plane.
bool isLocal (Vec3D &min, Vec3D &max) const override
void setPosition (const Vec3D &position) override
Sets the position of this BaseInteractable.
void setOrientation (const Quaternion &orientation) override
Sets the orientation of this BaseInteractable.
void move (const Vec3D &move) override
Moves this BaseInteractable by adding an amount to the position.
void rotate (const Vec3D &angularVelocity) override
Rotates this BaseInteractable.
Public Member Functions inherited from BaseWall
BaseWall ()
Default constructor.
BaseWall (const BaseWall &w)
Copy constructor.
~BaseWall () override
Default destructor.
virtual bool getDistanceNormalOverlap (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual bool getDistanceNormalOverlapSuperquadric (const SuperQuadricParticle &p, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual Vec3D getFurthestPointSuperQuadric (const Vec3D &normalBodyFixed, const Vec3D &axes, Mdouble eps1, Mdouble eps2) const
virtual void setHandler (WallHandler *handler)
A function which sets the WallHandler for this BaseWall.
WallHandler * getHandler () const
A function which returns the WallHandler that handles this BaseWall.
void setIndSpecies (unsigned int indSpecies) override
Define the species of this wall using the index of the species in the SpeciesHandler in this DPMBase.
void setSpecies (const ParticleSpecies *species)
Defines the species of the current wall.
bool isFixed () const override
void setForceControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity={0, 0, 0})
Slowly adjusts the force on a wall towards a specified goal, by adjusting (prescribing) the velocity of the wall.
bool getLinePlaneIntersect (Vec3D &intersect, const Vec3D &p0, const Vec3D &p1, const Vec3D &n, const Vec3D &p)
bool isInsideWallVTK (const Vec3D &point, const Vec3D &normal, const Vec3D &position) const
void projectOntoWallVTK (Vec3D &point0, const Vec3D &point1, const Vec3D &normal, const Vec3D &position) const
void intersectVTK (std::vector< Vec3D > &points, Vec3D normal, Vec3D position) const
virtual BaseInteraction * getInteractionWithSuperQuad (SuperQuadricParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler)
void getVTK (std::vector< Vec3D > &points, std::vector< std::vector< double >> &triangleStrips)
const Vec3D getAxis () const
virtual void actionsOnRestart ()
No implementation but can be overidden in its derived classes.
virtual void actionsAfterParticleGhostUpdate ()
No implementation but can be overidden in its derived classes.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
virtual void handleParticleRemoval (unsigned int id)
Handles the addition of particles to the particleHandler.
virtual void checkInteractions (InteractionHandler *interactionHandler, unsigned int timeStamp)
Check if all interactions are valid.
bool getVTKVisibility () const
void setVTKVisibility (bool vtkVisibility)
void addRenderedWall (BaseWall *w)
BaseWall * getRenderedWall (size_t i) const
std::vector< BaseWall * > getRenderedWalls () const
void removeRenderedWalls ()
void renderWall (VTKContainer &vtk)
void addParticlesAtWall (unsigned numElements=50)
void setVelocityControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity)
virtual void writeWallDetailsVTK (VTKData &data) const
Public Member Functions inherited from BaseInteractable
BaseInteractable ()
Default BaseInteractable constructor.
BaseInteractable (const BaseInteractable &p)
Copy constructor.
~BaseInteractable () override
Destructor, it simply destructs the BaseInteractable and all the objects it contains.
unsigned int getIndSpecies () const
Returns the index of the species associated with the interactable object.
const ParticleSpecies * getSpecies () const
Returns a pointer to the species of this BaseInteractable.
void setSpecies (const ParticleSpecies *species)
Sets the species of this BaseInteractable.
const Vec3D & getForce () const
Returns the force on this BaseInteractable.
const Vec3D & getTorque () const
Returns the torque on this BaseInteractable.
void setForce (const Vec3D &force)
Sets the force on this BaseInteractable.
void setTorque (const Vec3D &torque)
Sets the torque on this BaseInteractable.
void addForce (const Vec3D &addForce)
Adds an amount to the force on this BaseInteractable.
void addTorque (const Vec3D &addTorque)
Adds an amount to the torque on this BaseInteractable.
void sumForceTorqueOMP ()
const Vec3D & getPosition () const
Returns the position of this BaseInteractable.
const Quaternion & getOrientation () const
Returns the orientation of this BaseInteractable.
void setOrientationViaNormal (Vec3D normal)
Sets the orientation of this BaseInteractable by defining the vector that results from the rotation of the (1,0,0) vector.
void setOrientationViaEuler (Vec3D eulerAngle)
Sets the orientation of this BaseInteractable by defining the euler angles.
const std::vector< BaseInteraction * > & getInteractions () const
Returns a list of interactions which belong to this interactable.
void addInteraction (BaseInteraction *I)
Adds an interaction to this BaseInteractable.
bool removeInteraction (BaseInteraction *I)
Removes an interaction from this BaseInteractable.
void copyInteractionsForPeriodicParticles (const BaseInteractable &p)
Copies interactions to this BaseInteractable whenever a periodic copy made.
void setVelocity (const Vec3D &velocity)
set the velocity of the BaseInteractable.
void setAngularVelocity (const Vec3D &angularVelocity)
set the angular velocity of the BaseInteractble.
void addVelocity (const Vec3D &velocity)
adds an increment to the velocity.
void addAngularVelocity (const Vec3D &angularVelocity)
add an increment to the angular velocity.
virtual const Vec3D & getVelocity () const
Returns the velocity of this interactable.
virtual const Vec3D & getAngularVelocity () const
Returns the angular velocity of this interactable.
void setPrescribedPosition (const std::function< Vec3D(double)> &prescribedPosition)
Allows the position of an infinite mass interactable to be prescribed.
void applyPrescribedPosition (double time)
Computes the position from the user defined prescribed position function.
void setPrescribedVelocity (const std::function< Vec3D(double)> &prescribedVelocity)
Allows the velocity of an infinite mass interactable to be prescribed.
void applyPrescribedVelocity (double time)
Computes the velocity from the user defined prescribed velocity function.
void setPrescribedOrientation (const std::function< Quaternion(double)> &prescribedOrientation)
Allows the orientation of the infinite mass interactbale to be prescribed.
void applyPrescribedOrientation (double time)
Computes the orientation from the user defined prescribed orientation function.
void setPrescribedAngularVelocity (const std::function< Vec3D(double)> &prescribedAngularVelocity)
Allows the angular velocity of the infinite mass interactable to be prescribed.
void applyPrescribedAngularVelocity (double time)
Computes the angular velocity from the user defined prescribed angular velocity.
virtual const Vec3D getVelocityAtContact (const Vec3D &contact) const
Returns the velocity at the contact point, use by many force laws.
void integrateBeforeForceComputation (double time, double timeStep)
This is part of integrate routine for objects with infinite mass.
void integrateAfterForceComputation (double time, double timeStep)
This is part of the integration routine for objects with infinite mass.
virtual Mdouble getInvMass () const
virtual Mdouble getCurvature (const Vec3D &labFixedCoordinates) const
virtual bool isFaceContact (const Vec3D &normal) const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Member Functions
void storeDebris (const Triangle &triangle, const Vec3D &position, const Vec3D &debris, std::vector< Vec3D > &debrisContainer)
Proportionally assigns the debris located at a certain position on a triangle to the triangle vertices.
Private Attributes
Mdouble wearCoefficient_
Dimensionless wear coefficient.
Mdouble hardness_
Hardness.
Mdouble wearAcceleration_
Accelerates the wear process, to reduce simulation time needed to get results.
Additional Inherited Members
Static Public Member Functions inherited from BaseWall
static void addToVTK (const std::vector< Vec3D > &points, VTKContainer &vtk)
Takes the points provided and adds a triangle strip connecting these points to the vtk container.
Protected Attributes inherited from TriangleMeshWall
std::vector< Triangle > triangles_
std::vector< Vertex > vertices_
Constructor & Destructor Documentation
WearableTriangleMeshWall() [1/4]
WearableTriangleMeshWall::WearableTriangleMeshWall () default
Default constructor.
Referenced by copy().
WearableTriangleMeshWall() [2/4]
WearableTriangleMeshWall::WearableTriangleMeshWall (const std::vector< Vec3D > & points, const std::vector< std::array< unsigned, 3 >> & cells, const ParticleSpecies * species = nullptr)
Constructor creating triangles.
Parameters
points Vector of vertices
cells Vector of cells, each cell holds three indices to the points vector
species
                                                    : TriangleMeshWall(points, cells, species)
 {
 }
WearableTriangleMeshWall() [3/4]
WearableTriangleMeshWall::WearableTriangleMeshWall (const Vec3D & P0, const Vec3D & P1, const Vec3D & P, Mdouble resolutionU, Mdouble resolutionV, const ParticleSpecies * species = nullptr, bool periodicInU = false, bool periodicInV = false)
Constructor creating parallelogram shaped mesh with a given resolution in u- and v-direction.
Parameters
P0,P1,P2 The three points, in clockwise order, forming the parallelogram (fourth point is implied).
resolutionU Maximum length of a segment in u-direction.
resolutionV Maximum length of a segment in v-direction.
species
periodicInU Whether or not the first and last column of vertices lie in a periodic boundary and should be set as periodic companions.
periodicInV Whether or not the first and last row of vertices lie in a periodic boundary and should be set as periodic companions.
                                                                                        :
                                                    TriangleMeshWall(P0, P1, P2, resolutionU, resolutionV, species, periodicInU, periodicInV)
 {
 }
WearableTriangleMeshWall() [4/4]
WearableTriangleMeshWall::WearableTriangleMeshWall (const WearableTriangleMeshWall & other)
Copy constructor.
Parameters
other The WearableTriangleMeshWall that must be copied.
                                                                                         : TriangleMeshWall(other)
 {
     wearCoefficient_ = other.wearCoefficient_;
     hardness_ = other.hardness_;
     wearAcceleration_ = other.wearAcceleration_;
 }
References hardness_, wearAcceleration_, and wearCoefficient_.
~WearableTriangleMeshWall()
WearableTriangleMeshWall::~WearableTriangleMeshWall () default
Destructor.
Member Function Documentation
computeWear()
void WearableTriangleMeshWall::computeWear () override virtual
Reimplemented from BaseWall.
 {
     // Archard wear model, from https://en.wikipedia.org/wiki/Archard_equation
     // Q = KWL/H
     // Q is the total volume of wear debris produced
     // K is a dimensionless constant (typically mild wear 1e-8, severe wear 1e-2)
     // W is the total normal load
     // L is the sliding distance
     // H is the hardness of the softest contacting surfaces
     // Initialize debris vector with all zero Vec3Ds.
     std::vector<Vec3D> debrisContainer(vertices_.size(), Vec3D(0.0, 0.0, 0.0));
     Mdouble totalDebris = 0.0;
     for (auto& t : triangles_)
     {
         for (BaseInteraction* interaction : t.wall.getInteractions())
         {
             // Ignore old interactions and interactions from periodic particles.
             if (interaction->getTimeStamp() <= getHandler()->getDPMBase()->getNumberOfTimeSteps() ||
                 static_cast<BaseParticle*>(interaction->getP())->getPeriodicFromParticle() != nullptr)
                 continue;
             const Mdouble W = interaction->getAbsoluteNormalForce();
             // Pythagoras to get tangential magnitude from the normal magnitude and the relative velocity vector.
             const Mdouble tangentialRelativeVelocity = std::sqrt(interaction->getRelativeVelocity().getLengthSquared() -
                     interaction->getNormalRelativeVelocity() * interaction->getNormalRelativeVelocity());
             const Mdouble L = tangentialRelativeVelocity * getHandler()->getDPMBase()->getTimeStep();
             const Mdouble Q = wearAcceleration_ * wearCoefficient_ * W * L / hardness_;
             totalDebris += Q;
             // The contact point in normal direction is halfway the overlap. However, to properly store the debris the
             // position exactly on the wall should be used.
             Vec3D contactPointOnWall = interaction->getContactPoint() + 0.5 * interaction->getOverlap() * interaction->getNormal();
             // Debris is removed in the direction of the interaction normal (rotated back to lab frame).
             storeDebris(t, getOrientation().rotateBack(contactPointOnWall - getPosition()), getOrientation().rotateBack(interaction->getNormal()) * -Q, debrisContainer);
         }
     }
     moveVerticesToMatchVolume(debrisContainer, totalDebris);
 }
References BaseHandler< T >::getDPMBase(), BaseWall::getHandler(), BaseInteractable::getOrientation(), BaseParticle::getPeriodicFromParticle(), BaseInteractable::getPosition(), DPMBase::getTimeStep(), hardness_, L, TriangleMeshWall::moveVerticesToMatchVolume(), Q, sqrt(), storeDebris(), plotPSD::t, TriangleMeshWall::triangles_, TriangleMeshWall::vertices_, oomph::QuadTreeNames::W, wearAcceleration_, and wearCoefficient_.
copy()
WearableTriangleMeshWall * WearableTriangleMeshWall::copy () const override virtual
Wall copy method.
Returns
Pointer to the copy.
Reimplemented from TriangleMeshWall.
 {
     return new WearableTriangleMeshWall(*this);
 }
References WearableTriangleMeshWall().
Referenced by operator=().
getName()
std::string WearableTriangleMeshWall::getName () const override virtual
Returns the name of the object.
Returns
"WearableTriangleMeshWall"
Reimplemented from TriangleMeshWall.
 {
     return "WearableTriangleMeshWall";
 }
operator=()
WearableTriangleMeshWall & WearableTriangleMeshWall::operator= (const WearableTriangleMeshWall & other)
Copy assignment operator.
Parameters
other The WearableTriangleMeshWall that must be copied.
Returns
 {
     if (this == &other)
     {
         return *this;
     }
     return *(other.copy());
 }
References copy().
read()
void WearableTriangleMeshWall::read (std::istream & is) override virtual
Reads a WearableTriangleMeshWall from an input stream, for example a restart file.
Reimplemented from TriangleMeshWall.
 {
     TriangleMeshWall::read(is);
     std::string dummy;
     is >> dummy >> wearCoefficient_ >> dummy >> hardness_ >> dummy >> wearAcceleration_;
 }
References hardness_, TriangleMeshWall::read(), oomph::Global_string_for_annotation::string(), wearAcceleration_, and wearCoefficient_.
setHardness()
void WearableTriangleMeshWall::setHardness (Mdouble hardness)
Parameters
hardness Hardness of the wall.
 {
     hardness_ = hardness;
 }
References hardness_.
setWearAcceleration()
void WearableTriangleMeshWall::setWearAcceleration (Mdouble wearAcceleration)
Parameters
wearAcceleration Value to accelerate the wear process with, to reduce simulation time needed to get results.
 {
     wearAcceleration_ = wearAcceleration;
 }
References wearAcceleration_.
setWearCoefficient()
void WearableTriangleMeshWall::setWearCoefficient (Mdouble wearCoefficient)
Parameters
wearCoefficient Non-dimensionless wear constant.
 {
     wearCoefficient_ = wearCoefficient;
 }
References wearCoefficient_.
storeDebris()
void WearableTriangleMeshWall::storeDebris (const Triangle & triangle, const Vec3D & position, const Vec3D & debris, std::vector< Vec3D > & debrisContainer) private
Proportionally assigns the debris located at a certain position on a triangle to the triangle vertices.
Parameters
triangle Triangle on which the point lies.
position Point of debris.
debris The debris, which has a direction, i.e. the vector length is be the actual debris volume.
debrisContainer Vector storing the debris for all vertices (index wise related).
 {
     const unsigned index0 = triangle.vertexIndices[0];
     const unsigned index1 = triangle.vertexIndices[1];
     const unsigned index2 = triangle.vertexIndices[2];
 //    // Assign 1/3 to each vertex
 //    debrisContainer[index0] += debris / 3.0;
 //    debrisContainer[index1] += debris / 3.0;
 //    debrisContainer[index2] += debris / 3.0;
 //    // Distance from contact point to each vertex
 //    const Mdouble distanceSquared0 = Vec3D::getLengthSquared(vertices_[index0].position - position);
 //    const Mdouble distanceSquared1 = Vec3D::getLengthSquared(vertices_[index1].position - position);
 //    const Mdouble distanceSquared2 = Vec3D::getLengthSquared(vertices_[index2].position - position);
 //
 //    // Assign to closest vertex
 //    const unsigned indexFinal = distanceSquared0 < distanceSquared1 ?
 //            (distanceSquared0 < distanceSquared2 ? index0 : index2) :
 //            (distanceSquared1 < distanceSquared2 ? index1 : index2);
 //    debrisContainer[indexFinal] += debris;
     // Barycentric interpolation
     // Get vertices positions and shift by debris position.
     const Vec3D v0 = vertices_[index0].position - position;
     const Vec3D v1 = vertices_[index1].position - position;
     const Vec3D v2 = vertices_[index2].position - position;
     // Area of each section, and total area.
     // When the debris position does not lie perfectly in plane, the sum of the area of the sections differs from the
     // area of the triangle itself. It is therefore better to use the sum, even though still a small error in the
     // fractions remain, depending on how far off plane the position is.
     Mdouble A0 = 0.5 * Vec3D::cross(v0, v1).getLength();
     Mdouble A1 = 0.5 * Vec3D::cross(v1, v2).getLength();
     Mdouble A2 = 0.5 * Vec3D::cross(v2, v0).getLength();
     Mdouble A = A0 + A1 + A2;
     // Fraction of debris is equal to the  area opposite to vertex divided by total area.
     debrisContainer[index0] += debris * A1 / A;
     debrisContainer[index1] += debris * A2 / A;
     debrisContainer[index2] += debris * A0 / A;
 }
References Vec3D::cross(), Vec3D::getLength(), v1(), v2(), TriangleMeshWall::Triangle::vertexIndices, and TriangleMeshWall::vertices_.
Referenced by computeWear().
write()
void WearableTriangleMeshWall::write (std::ostream & os) const override virtual
Writes a WearableTriangleMeshWall to an output stream, for example a restart file.
Reimplemented from TriangleMeshWall.
 {
     TriangleMeshWall::write(os);
     os << " wearCoefficient " << wearCoefficient_ << " hardness " << hardness_ << " wearAcceleration " << wearAcceleration_;
 }
References hardness_, wearAcceleration_, wearCoefficient_, and TriangleMeshWall::write().
Member Data Documentation
hardness_
Mdouble WearableTriangleMeshWall::hardness_ private
Hardness.
Referenced by computeWear(), read(), setHardness(), WearableTriangleMeshWall(), and write().
wearAcceleration_
Mdouble WearableTriangleMeshWall::wearAcceleration_ private
Accelerates the wear process, to reduce simulation time needed to get results.
Referenced by computeWear(), read(), setWearAcceleration(), WearableTriangleMeshWall(), and write().
wearCoefficient_
Mdouble WearableTriangleMeshWall::wearCoefficient_ private
Dimensionless wear coefficient.
Referenced by computeWear(), read(), setWearCoefficient(), WearableTriangleMeshWall(), and write().
The documentation for this class was generated from the following files:
WearableTriangleMeshWall.h
WearableTriangleMeshWall.cc