MercuryDPM: WearableNurbsWall Class Reference
WearableNurbsWall Class Reference
#include <WearableNurbsWall.h>
Public Member Functions
WearableNurbsWall ()
Default constructor: make a wall with default parameters.
WearableNurbsWall (const WearableNurbsWall &other)
Copy constructor, copies another wall.
WearableNurbsWall (const NurbsSurface &nurbsSurface)
Constructor in which all parameters of the wall are set.
~WearableNurbsWall ()
Default destructor.
WearableNurbsWall (Mdouble lengthU, Mdouble lengthV, Mdouble resolutionU, Mdouble resolutionV, bool periodicU=false, bool periodicV=false)
void set (Mdouble lengthU, Mdouble lengthV, Mdouble resolutionU, Mdouble resolutionV, bool periodicU=false, bool periodicV=false)
void read (std::istream &is) override
Reads this wall from an input stream, for example a restart file.
void write (std::ostream &os) const override
Writes this wall to an output stream, for example a restart file.
std::string getName () const final
Returns the name of the object, here the string "WearableNurbsWall".
WearableNurbsWall * copy () const final
Copy this wall and return a pointer to the copy.
void computeWear () override
void writeWallDetailsVTK (VTKData &data) const override
Mdouble getVolumeUnderSurface (const std::vector< Mdouble > &knotsU, const std::vector< Mdouble > &knotsV, const std::vector< std::vector< Vec3D >> &controlPoints, const std::vector< std::vector< Mdouble >> &weights) const
Mdouble getVolumeUnderSurfaceX (const std::vector< Mdouble > &knotsU, const std::vector< Mdouble > &knotsV, const std::vector< std::vector< Vec3D >> &controlPoints, const std::vector< std::vector< Mdouble >> &weights) const
void moveControlPoint (unsigned idxU, unsigned idxV, Vec3D dP)
Mdouble getVolumeUnderSurface ()
Public Member Functions inherited from NurbsWall
NurbsWall ()
Default constructor: make a wall with default parameters.
NurbsWall (const NurbsWall &other)
Copy constructor, copies another wall.
NurbsWall (const NurbsSurface &nurbsSurface)
Constructor in which all parameters of the wall are set.
~NurbsWall ()
Default destructor.
void set (const NurbsSurface &nurbsSurface)
Defines a wall, given a NurbsSurface.
bool getDistanceAndNormal (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return) const final
Compute the distance from the Screw for a given BaseParticle and return if there is a collision. If there is a collision, also return the normal vector of the interaction point.
void writeVTK (VTKContainer &vtk) const override
Public Member Functions inherited from BaseWall
BaseWall ()
Default constructor.
BaseWall (const BaseWall &w)
Copy constructor.
~BaseWall () override
Default destructor.
virtual bool getDistanceNormalOverlap (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual bool getDistanceNormalOverlapSuperquadric (const SuperQuadricParticle &p, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual Vec3D getFurthestPointSuperQuadric (const Vec3D &normalBodyFixed, const Vec3D &axes, Mdouble eps1, Mdouble eps2) const
virtual void setHandler (WallHandler *handler)
A function which sets the WallHandler for this BaseWall.
WallHandler * getHandler () const
A function which returns the WallHandler that handles this BaseWall.
void setIndSpecies (unsigned int indSpecies) override
Define the species of this wall using the index of the species in the SpeciesHandler in this DPMBase.
void setSpecies (const ParticleSpecies *species)
Defines the species of the current wall.
bool isFixed () const override
void setForceControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity={0, 0, 0})
Slowly adjusts the force on a wall towards a specified goal, by adjusting (prescribing) the velocity of the wall.
virtual bool isLocal (Vec3D &min, Vec3D &max) const
bool getLinePlaneIntersect (Vec3D &intersect, const Vec3D &p0, const Vec3D &p1, const Vec3D &n, const Vec3D &p)
bool isInsideWallVTK (const Vec3D &point, const Vec3D &normal, const Vec3D &position) const
void projectOntoWallVTK (Vec3D &point0, const Vec3D &point1, const Vec3D &normal, const Vec3D &position) const
void intersectVTK (std::vector< Vec3D > &points, Vec3D normal, Vec3D position) const
virtual BaseInteraction * getInteractionWithSuperQuad (SuperQuadricParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler)
void getVTK (std::vector< Vec3D > &points, std::vector< std::vector< double >> &triangleStrips)
const Vec3D getAxis () const
BaseInteraction * getInteractionWith (BaseParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler) override
Returns the interaction between this wall and a given particle, nullptr if there is no interaction.
virtual void actionsOnRestart ()
No implementation but can be overidden in its derived classes.
virtual void actionsAfterParticleGhostUpdate ()
No implementation but can be overidden in its derived classes.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
virtual void handleParticleRemoval (unsigned int id)
Handles the addition of particles to the particleHandler.
virtual void checkInteractions (InteractionHandler *interactionHandler, unsigned int timeStamp)
Check if all interactions are valid.
bool getVTKVisibility () const
void setVTKVisibility (bool vtkVisibility)
void addRenderedWall (BaseWall *w)
BaseWall * getRenderedWall (size_t i) const
std::vector< BaseWall * > getRenderedWalls () const
void removeRenderedWalls ()
void renderWall (VTKContainer &vtk)
void addParticlesAtWall (unsigned numElements=50)
void setVelocityControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity)
Public Member Functions inherited from BaseInteractable
BaseInteractable ()
Default BaseInteractable constructor.
BaseInteractable (const BaseInteractable &p)
Copy constructor.
~BaseInteractable () override
Destructor, it simply destructs the BaseInteractable and all the objects it contains.
unsigned int getIndSpecies () const
Returns the index of the species associated with the interactable object.
const ParticleSpecies * getSpecies () const
Returns a pointer to the species of this BaseInteractable.
void setSpecies (const ParticleSpecies *species)
Sets the species of this BaseInteractable.
const Vec3D & getForce () const
Returns the force on this BaseInteractable.
const Vec3D & getTorque () const
Returns the torque on this BaseInteractable.
void setForce (const Vec3D &force)
Sets the force on this BaseInteractable.
void setTorque (const Vec3D &torque)
Sets the torque on this BaseInteractable.
void addForce (const Vec3D &addForce)
Adds an amount to the force on this BaseInteractable.
void addTorque (const Vec3D &addTorque)
Adds an amount to the torque on this BaseInteractable.
virtual void resetForceTorque (int numberOfOMPthreads)
void sumForceTorqueOMP ()
const Vec3D & getPosition () const
Returns the position of this BaseInteractable.
const Quaternion & getOrientation () const
Returns the orientation of this BaseInteractable.
virtual void setPosition (const Vec3D &position)
Sets the position of this BaseInteractable.
void setOrientationViaNormal (Vec3D normal)
Sets the orientation of this BaseInteractable by defining the vector that results from the rotation of the (1,0,0) vector.
void setOrientationViaEuler (Vec3D eulerAngle)
Sets the orientation of this BaseInteractable by defining the euler angles.
virtual void setOrientation (const Quaternion &orientation)
Sets the orientation of this BaseInteractable.
virtual void move (const Vec3D &move)
Moves this BaseInteractable by adding an amount to the position.
virtual void rotate (const Vec3D &angularVelocityDt)
Rotates this BaseInteractable.
const std::vector< BaseInteraction * > & getInteractions () const
Returns a list of interactions which belong to this interactable.
void addInteraction (BaseInteraction *I)
Adds an interaction to this BaseInteractable.
bool removeInteraction (BaseInteraction *I)
Removes an interaction from this BaseInteractable.
void copyInteractionsForPeriodicParticles (const BaseInteractable &p)
Copies interactions to this BaseInteractable whenever a periodic copy made.
void setVelocity (const Vec3D &velocity)
set the velocity of the BaseInteractable.
void setAngularVelocity (const Vec3D &angularVelocity)
set the angular velocity of the BaseInteractble.
void addVelocity (const Vec3D &velocity)
adds an increment to the velocity.
void addAngularVelocity (const Vec3D &angularVelocity)
add an increment to the angular velocity.
virtual const Vec3D & getVelocity () const
Returns the velocity of this interactable.
virtual const Vec3D & getAngularVelocity () const
Returns the angular velocity of this interactable.
void setPrescribedPosition (const std::function< Vec3D(double)> &prescribedPosition)
Allows the position of an infinite mass interactable to be prescribed.
void applyPrescribedPosition (double time)
Computes the position from the user defined prescribed position function.
void setPrescribedVelocity (const std::function< Vec3D(double)> &prescribedVelocity)
Allows the velocity of an infinite mass interactable to be prescribed.
void applyPrescribedVelocity (double time)
Computes the velocity from the user defined prescribed velocity function.
void setPrescribedOrientation (const std::function< Quaternion(double)> &prescribedOrientation)
Allows the orientation of the infinite mass interactbale to be prescribed.
void applyPrescribedOrientation (double time)
Computes the orientation from the user defined prescribed orientation function.
void setPrescribedAngularVelocity (const std::function< Vec3D(double)> &prescribedAngularVelocity)
Allows the angular velocity of the infinite mass interactable to be prescribed.
void applyPrescribedAngularVelocity (double time)
Computes the angular velocity from the user defined prescribed angular velocity.
virtual const Vec3D getVelocityAtContact (const Vec3D &contact) const
Returns the velocity at the contact point, use by many force laws.
void integrateBeforeForceComputation (double time, double timeStep)
This is part of integrate routine for objects with infinite mass.
void integrateAfterForceComputation (double time, double timeStep)
This is part of the integration routine for objects with infinite mass.
virtual Mdouble getInvMass () const
virtual Mdouble getCurvature (const Vec3D &labFixedCoordinates) const
virtual bool isFaceContact (const Vec3D &normal) const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Member Functions
void storeDebris (Vec3D P, const Mdouble debris)
void processDebris ()
Private Attributes
std::vector< std::vector< Mdouble > > localDebris_
Additional Inherited Members
Static Public Member Functions inherited from BaseWall
static void addToVTK (const std::vector< Vec3D > &points, VTKContainer &vtk)
Takes the points provided and adds a triangle strip connecting these points to the vtk container.
Protected Attributes inherited from NurbsWall
NurbsSurface nurbsSurface_
Constructor & Destructor Documentation
WearableNurbsWall() [1/4]
WearableNurbsWall::WearableNurbsWall ()
Default constructor: make a wall with default parameters.
 {
     logger(DEBUG, "WearableNurbsWall() constructor finished.");
 }
References DEBUG, and logger.
Referenced by copy().
WearableNurbsWall() [2/4]
WearableNurbsWall::WearableNurbsWall (const WearableNurbsWall & other)
Copy constructor, copies another wall.
Parameters
[in] other The WearableNurbsWall that has to be copied.
         : NurbsWall(other)
 {
     localDebris_ = other.localDebris_;
     logger(DEBUG, "WearableNurbsWall(const WearableNurbsWall&) copy constructor finished.");
 }
References DEBUG, localDebris_, and logger.
WearableNurbsWall() [3/4]
WearableNurbsWall::WearableNurbsWall (const NurbsSurface & nurbsSurface)
Constructor in which all parameters of the wall are set.
Parameters
nurbsSurface The NURBS surface which defines the shape of the wall
         : NurbsWall(nurbsSurface)
 {
     logger(DEBUG, "WearableNurbsWall(const NurbsSurface&) constructor finished.");
 }
References DEBUG, and logger.
~WearableNurbsWall()
WearableNurbsWall::~WearableNurbsWall ()
Default destructor.
 {
     logger(DEBUG, "~WearableNurbsWall() finished, destroyed the wall.");
 }
References DEBUG, and logger.
WearableNurbsWall() [4/4]
WearableNurbsWall::WearableNurbsWall (Mdouble lengthU, Mdouble lengthV, Mdouble resolutionU, Mdouble resolutionV, bool periodicU = false, bool periodicV = false)
 {
     set(lengthU, lengthV, resolutionU, resolutionV, periodicU, periodicV);
 }
References set().
Member Function Documentation
computeWear()
void WearableNurbsWall::computeWear () override virtual
Reimplemented from BaseWall.
 {
     // From https://en.wikipedia.org/wiki/Archard_equation
     // Q = KWL/H
     // Q is the total volume of wear debris produced
     // K is a dimensionless constant (typically mild wear 1e-8, severe wear 1e-2)
     // W is the total normal load
     // L is the sliding distance
     // H is the hardness of the softest contacting surfaces
     const Mdouble dt = getHandler()->getDPMBase()->getTimeStep();
     for (BaseInteraction* interaction : getInteractions())
     {
         // Ignore interactions from periodic particles. (Although it seems Q evaluates to 0 anyway (absolute normal force equals 0), but just to be sure)
         if (static_cast<BaseParticle*>(interaction->getP())->getPeriodicFromParticle() != nullptr)
             continue;
         Mdouble K = 1.0e-6; // For testing only, should be set by user
         Mdouble W = interaction->getAbsoluteNormalForce();
         // Pythagoras to get tangential magnitude from vector and normal magnitude
         Mdouble tangentialRelativeVelocity = std::sqrt(interaction->getRelativeVelocity().getLengthSquared() -
                 interaction->getNormalRelativeVelocity() * interaction->getNormalRelativeVelocity());
         Mdouble L = tangentialRelativeVelocity * dt;
         Mdouble H = 1.0; // For testing only, should be set by user
         Mdouble Q = K * W * L / H;
         storeDebris(interaction->getContactPoint(), Q);
     }
 //    if (!getInteractions().empty() && getHandler()->getDPMBase()->getNumberOfTimeSteps() % 100 == 0)
 //    {
 //        processDebris();
 //        // Reset debris
 //        for (auto& d0 : localDebris_)
 //            for (auto& d : d0)
 //                d = 0.0;
 //    }
 }
References BaseHandler< T >::getDPMBase(), BaseWall::getHandler(), BaseInteractable::getInteractions(), BaseParticle::getPeriodicFromParticle(), DPMBase::getTimeStep(), H, PlanarWave::K, L, Q, sqrt(), storeDebris(), and oomph::QuadTreeNames::W.
copy()
WearableNurbsWall * WearableNurbsWall::copy () const final virtual
Copy this wall and return a pointer to the copy.
Reimplemented from NurbsWall.
 {
     return new WearableNurbsWall(*this);
 }
References WearableNurbsWall().
getName()
std::string WearableNurbsWall::getName () const final virtual
Returns the name of the object, here the string "WearableNurbsWall".
Reimplemented from NurbsWall.
 {
     return "WearableNurbsWall";
 }
getVolumeUnderSurface() [1/2]
Mdouble WearableNurbsWall::getVolumeUnderSurface () inline
     {
         return getVolumeUnderSurface(nurbsSurface_.getKnotsU(), nurbsSurface_.getKnotsV(), nurbsSurface_.getControlPoints(), nurbsSurface_.getWeights());
     }
References NurbsSurface::getControlPoints(), NurbsSurface::getKnotsU(), NurbsSurface::getKnotsV(), NurbsSurface::getWeights(), and NurbsWall::nurbsSurface_.
Referenced by processDebris().
getVolumeUnderSurface() [2/2]
Mdouble WearableNurbsWall::getVolumeUnderSurface (const std::vector< Mdouble > & knotsU, const std::vector< Mdouble > & knotsV, const std::vector< std::vector< Vec3D >> & controlPoints, const std::vector< std::vector< Mdouble >> & weights) const
 {
     // times 10 is arbitrary number for more accuracy.
     const int numU = knotsU.size() * 10; // Was 10 lately a lot for many test simulations
     const int numV = knotsV.size() * 10;
     const int degreeU = knotsU.size() - controlPoints.size() - 1;
     const int degreeV = knotsV.size() - controlPoints[0].size() - 1;
     const Mdouble lbU = knotsU[degreeU];
     const Mdouble ubU = knotsU[knotsU.size() - degreeU - 1];
     const Mdouble lbV = knotsV[degreeV];
     const Mdouble ubV = knotsV[knotsV.size() - degreeV - 1];
     Mdouble volume = 0.0;
     for (int i = 0; i < numU; i++)
     {
         for (int j = 0; j < numV; j++)
         {
             const Mdouble u0 = lbU + (ubU - lbU) * static_cast<Mdouble>(i)   / static_cast<Mdouble>(numU);
             const Mdouble u1 = lbU + (ubU - lbU) * static_cast<Mdouble>(i+1) / static_cast<Mdouble>(numU);
             const Mdouble v0 = lbV + (ubV - lbV) * static_cast<Mdouble>(j)   / static_cast<Mdouble>(numV);
             const Mdouble v1 = lbV + (ubV - lbV) * static_cast<Mdouble>(j+1) / static_cast<Mdouble>(numV);
             const Vec3D p1 = NurbsUtils::evaluate(u0, v0, knotsU, knotsV, controlPoints, weights); // Bottom left
             const Vec3D p2 = NurbsUtils::evaluate(u0, v1, knotsU, knotsV, controlPoints, weights); // Top left
             const Vec3D p3 = NurbsUtils::evaluate(u1, v0, knotsU, knotsV, controlPoints, weights); // Bottom right
             const Vec3D p4 = NurbsUtils::evaluate(u1, v1, knotsU, knotsV, controlPoints, weights); // Top right
             const Mdouble projectedArea1 = 0.5 * (p1.X * p3.Y - p3.X * p1.Y + p2.X * p1.Y - p1.X * p2.Y + p3.X * p2.Y - p2.X * p3.Y);
             const Mdouble projectedArea2 = 0.5 * (p4.X * p3.Y - p3.X * p4.Y + p2.X * p4.Y - p4.X * p2.Y + p3.X * p2.Y - p2.X * p3.Y);
             const Mdouble averageHeight1 = (p1.Z + p2.Z + p3.Z) / 3.0;
             const Mdouble averageHeight2 = (p4.Z + p2.Z + p3.Z) / 3.0;
             // Area can be negative (depending on order of points considered), and z is always negative assuming only
             // downward movement of control points, therefore take absolute value.
             const Mdouble volume1 = std::abs(averageHeight1 * projectedArea1);
             const Mdouble volume2 = std::abs(averageHeight2 * projectedArea2);
             volume += volume1 + volume2;
         }
     }
     return volume;
 }
References abs(), NurbsUtils::evaluate(), i, j, p1, v1(), calibrate::weights, Vec3D::X, Vec3D::Y, and Vec3D::Z.
getVolumeUnderSurfaceX()
Mdouble WearableNurbsWall::getVolumeUnderSurfaceX (const std::vector< Mdouble > & knotsU, const std::vector< Mdouble > & knotsV, const std::vector< std::vector< Vec3D >> & controlPoints, const std::vector< std::vector< Mdouble >> & weights) const
 {
     // times 10 is arbitrary number for more accuracy.
     const int numU = knotsU.size() * 10; // Was 10 lately a lot for many test simulations
     const int numV = knotsV.size() * 10;
     const int degreeU = knotsU.size() - controlPoints.size() - 1;
     const int degreeV = knotsV.size() - controlPoints[0].size() - 1;
     const Mdouble lbU = knotsU[degreeU];
     const Mdouble ubU = knotsU[knotsU.size() - degreeU - 1];
     const Mdouble lbV = knotsV[degreeV];
     const Mdouble ubV = knotsV[knotsV.size() - degreeV - 1];
     Mdouble volume = 0.0;
     for (int i = 0; i < numU; i++)
     {
         for (int j = 0; j < numV; j++)
         {
             const Mdouble u0 = lbU + (ubU - lbU) * static_cast<Mdouble>(i)   / static_cast<Mdouble>(numU);
             const Mdouble u1 = lbU + (ubU - lbU) * static_cast<Mdouble>(i+1) / static_cast<Mdouble>(numU);
             const Mdouble v0 = lbV + (ubV - lbV) * static_cast<Mdouble>(j)   / static_cast<Mdouble>(numV);
             const Mdouble v1 = lbV + (ubV - lbV) * static_cast<Mdouble>(j+1) / static_cast<Mdouble>(numV);
             const Vec3D p1 = NurbsUtils::evaluate(u0, v0, knotsU, knotsV, controlPoints, weights); // Bottom left
             const Vec3D p2 = NurbsUtils::evaluate(u0, v1, knotsU, knotsV, controlPoints, weights); // Top left
             const Vec3D p3 = NurbsUtils::evaluate(u1, v0, knotsU, knotsV, controlPoints, weights); // Bottom right
             const Vec3D p4 = NurbsUtils::evaluate(u1, v1, knotsU, knotsV, controlPoints, weights); // Top right
             // Only place with differences, x and z interchanged
             const Mdouble projectedArea1 = 0.5 * (p1.Z * p3.Y - p3.Z * p1.Y + p2.Z * p1.Y - p1.Z * p2.Y + p3.Z * p2.Y - p2.Z * p3.Y);
             const Mdouble projectedArea2 = 0.5 * (p4.Z * p3.Y - p3.Z * p4.Y + p2.Z * p4.Y - p4.Z * p2.Y + p3.Z * p2.Y - p2.Z * p3.Y);
             const Mdouble averageHeight1 = (p1.X + p2.X + p3.X) / 3.0;
             const Mdouble averageHeight2 = (p4.X + p2.X + p3.X) / 3.0;
             // Area can be negative (depending on order of points considered), and z is always negative assuming only
             // downward movement of control points, therefore take absolute value.
             const Mdouble volume1 = std::abs(averageHeight1 * projectedArea1);
             const Mdouble volume2 = std::abs(averageHeight2 * projectedArea2);
             volume += volume1 + volume2;
         }
     }
     return volume;
 }
References abs(), NurbsUtils::evaluate(), i, j, p1, v1(), calibrate::weights, Vec3D::X, Vec3D::Y, and Vec3D::Z.
moveControlPoint()
void WearableNurbsWall::moveControlPoint (unsigned idxU, unsigned idxV, Vec3D dP) inline
     {
         nurbsSurface_.moveControlPoint(idxU, idxV, dP, false);
     }
References NurbsSurface::moveControlPoint(), and NurbsWall::nurbsSurface_.
processDebris()
void WearableNurbsWall::processDebris () private
 {
     std::vector<std::vector<Vec3D>> controlPoints = nurbsSurface_.getControlPoints();
     Mdouble totalDebris = 0.0;
     const int numU = controlPoints.size();
     const int numV = controlPoints[0].size();
     for (int i = 0; i < numU; i++)
     {
         for (int j = 0; j < numV; j++)
         {
             controlPoints[i][j].Z = -localDebris_[i][j];
             totalDebris += localDebris_[i][j];
         }
     }
     const Mdouble volumeChange = getVolumeUnderSurface(nurbsSurface_.getKnotsU(), nurbsSurface_.getKnotsV(), controlPoints, nurbsSurface_.getWeights());
     const Mdouble ratio = totalDebris / volumeChange;
     for (int i = 0; i < numU; i++)
     {
         for (int j = 0; j < numV; j++)
         {
             nurbsSurface_.moveControlPoint(i, j, Vec3D(0.0, 0.0, -localDebris_[i][j] * ratio), true);
         }
     }
 }
References NurbsSurface::getControlPoints(), NurbsSurface::getKnotsU(), NurbsSurface::getKnotsV(), getVolumeUnderSurface(), NurbsSurface::getWeights(), i, j, localDebris_, NurbsSurface::moveControlPoint(), and NurbsWall::nurbsSurface_.
read()
void WearableNurbsWall::read (std::istream & is) override virtual
Reads this wall from an input stream, for example a restart file.
Parameters
[in,out] is Input stream from which the wall must be read.
Reimplemented from NurbsWall.
 {
     NurbsWall::read(is);
     std::string dummy;
     is >> dummy;
     unsigned int nu, nv;
     is >> dummy >> nu;
     is >> dummy >> nv;
     std::vector<std::vector<Mdouble>> localDebris;
     localDebris.resize(nu);
     for (auto& d0 : localDebris)
     {
         d0.resize(nv);
         for (auto& d : d0) is >> d;
     }
     localDebris_ = localDebris;
 }
References localDebris_, NurbsWall::read(), and oomph::Global_string_for_annotation::string().
set()
void WearableNurbsWall::set (Mdouble lengthU, Mdouble lengthV, Mdouble resolutionU, Mdouble resolutionV, bool periodicU = false, bool periodicV = false)
 {
     std::vector<std::vector<Vec3D>> controlPoints;
     std::vector<std::vector<Mdouble>> weights;
     int numU = static_cast<int>(lengthU / resolutionU);
     if (lengthU / numU > resolutionU)
     {
         numU++;
         resolutionU = lengthU / numU;
     }
     int numV = static_cast<int>(lengthV / resolutionV);
     if (lengthV / numV > resolutionV)
     {
         numV++;
         resolutionV = lengthV / numV;
     }
     for (int i = 0; i <= numU; i++)
     {
         std::vector<Vec3D> tempControlPoints;
         std::vector<Mdouble> tempWeights;
         for (int j = 0; j <= numV; j++)
         {
             tempControlPoints.push_back(Vec3D(i * resolutionU, j * resolutionV, 0.0));
             tempWeights.push_back(1.0);
         }
         controlPoints.push_back(tempControlPoints);
         weights.push_back(tempWeights);
     }
     // Make periodic when asked for, only clamp when not periodic.
     // Making periodic will unclamp it when needed, but better to start of unclamped already otherwise
     // warning messages are given to the user.
     NurbsSurface ns(controlPoints, weights, 3, 3, !periodicU, !periodicU, !periodicV, !periodicV);
     if (periodicU)
         ns.makePeriodicContinuousInU();
     if (periodicV)
         ns.makePeriodicContinuousInV();
     nurbsSurface_ = ns;
     // Initialize local debris with zeros
     const int sizeU = nurbsSurface_.getControlPoints().size();
     const int sizeV = nurbsSurface_.getControlPoints()[0].size();
     for (int i = 0; i < sizeU; i++)
     {
         std::vector<Mdouble> temp(sizeV, 0.0);
         localDebris_.push_back(temp);
     }
 }
References NurbsSurface::getControlPoints(), i, j, localDebris_, NurbsSurface::makePeriodicContinuousInU(), NurbsSurface::makePeriodicContinuousInV(), NurbsWall::nurbsSurface_, and calibrate::weights.
Referenced by WearableNurbsWall().
storeDebris()
void WearableNurbsWall::storeDebris (Vec3D P, const Mdouble debris) private
 {
     // Rotate global point back to local coordinate system.
     P -= getPosition();
     getOrientation().rotateBack(P);
     // Snap the position to the closest grid point. Assuming the control points only ever move in z-direction, so the
     // x- and y-position don't change, and it was created with a given resolution in u and v.
     const std::vector<std::vector<Vec3D>>& controlPoints = nurbsSurface_.getControlPoints();
     const Mdouble resU = std::abs(controlPoints[1][0].X - controlPoints[0][0].X);
     const Mdouble resV = std::abs(controlPoints[0][1].Y - controlPoints[0][0].Y);
     // --- Add to closest grid point -----------------------------------------------------------------------------------
     auto indexU = static_cast<const unsigned>(std::round((P.X - controlPoints[0][0].X) / resU));
     auto indexV = static_cast<const unsigned>(std::round((P.Y - controlPoints[0][0].Y) / resV));
     localDebris_[indexU][indexV] += debris;
     // --- Add to 4 closest grid points, weighted by distance ----------------------------------------------------------
 //    const Mdouble pU = (P.X - controlPoints[0][0].X) / resU;
 //    const Mdouble pV = (P.Y - controlPoints[0][0].Y) / resV;
 //
 //    // Left and right distance in u and v
 //    const Mdouble pUL = pU - std::floor(pU);
 //    const Mdouble pVL = pV - std::floor(pV);
 //    const Mdouble pUR = 1.0 - pUL;
 //    const Mdouble pVR = 1.0 - pVL;
 //
 //    // Power parameter
 //    const Mdouble p = 1.0;
 //
 //    // Normalizing "length" in u and v
 //    const Mdouble lU = std::pow(pUL, p) + std::pow(pUR, p);
 //    const Mdouble lV = std::pow(pVL, p) + std::pow(pVR, p);
 //
 //    // Weights for left and right in u and v
 //    const Mdouble wUL = 1.0 - std::pow(pUL, p) / lU;
 //    const Mdouble wUR = 1.0 - std::pow(pUR, p) / lU;
 //    const Mdouble wVL = 1.0 - std::pow(pVL, p) / lV;
 //    const Mdouble wVR = 1.0 - std::pow(pVR, p) / lV;
 //
 //    const unsigned firstIndexU = std::floor(pU);
 //    const unsigned firstIndexV = std::floor(pV);
 //    localDebris_[firstIndexU    ][firstIndexV    ] += debris * wUL * wVL;
 //    localDebris_[firstIndexU    ][firstIndexV + 1] += debris * wUL * wVR;
 //    localDebris_[firstIndexU + 1][firstIndexV    ] += debris * wUR * wVL;
 //    localDebris_[firstIndexU + 1][firstIndexV + 1] += debris * wUR * wVR;
 }
References abs(), NurbsSurface::getControlPoints(), BaseInteractable::getOrientation(), BaseInteractable::getPosition(), localDebris_, NurbsWall::nurbsSurface_, Global_Physical_Variables::P, Quaternion::rotateBack(), Eigen::bfloat16_impl::round(), X, and Y.
Referenced by computeWear().
write()
void WearableNurbsWall::write (std::ostream & os) const override virtual
Writes this wall to an output stream, for example a restart file.
Parameters
[in,out] os Output stream to which the wall must be written.
Reimplemented from NurbsWall.
 {
     NurbsWall::write(os);
     os << " Debris ";
     os << "nu " << localDebris_.size() << ' ';
     os << "nv " << localDebris_[0].size() << ' ';
     for (const auto& d0 : localDebris_) for (const auto d : d0) os << d << ' ';
 }
References localDebris_, and NurbsWall::write().
writeWallDetailsVTK()
void WearableNurbsWall::writeWallDetailsVTK (VTKData & data) const override virtual
Reimplemented from NurbsWall.
 {
     // Visualised as a flat surface, which can be coloured according to the debris at each point.
     // The points are simply the control points with the z-position set to 0.
     const std::vector<std::vector<Vec3D>>& points = nurbsSurface_.getControlPoints();
     // Reserve memory for number of points and cells about to be added
     const unsigned np = points.size() * points[0].size();
     const unsigned nc = (points.size() - 1) * (points[0].size() - 1);
     data.reservePoints(np, { "Debris" });
     data.reserveCells(nc);
     // Number of points in v-direction
     size_t nv = points[0].size();
     // Point index offset, the point indices have to be offset by the number of points already present at the start (from previously added data)
     size_t pio = data.getPoints().size();
     for (int i = 0; i < points.size(); i++)
     {
         for (int j = 0; j < points[i].size(); j++)
         {
             Vec3D p = points[i][j];
             p.Z = 0;
             getOrientation().rotate(p);
             p += getPosition();
             data.addToPoints(p);
             data.addToPointData("Debris", localDebris_[i][j]);
             if (i > 0 && j > 0)
             {
                 // Basic 2D/1D mapping for indexing: nv * i + j (+ point index offset)
                 // 4 points to form a rectangle: point, point to the left, point down, point to the left and down
                 data.addToConnectivity({ nv*i+j+pio, nv*(i-1)+j+pio, nv*i+j-1+pio, nv*(i-1)+j-1+pio });
                 data.addToTypes(8);
             }
         }
     }
 }
References data, NurbsSurface::getControlPoints(), BaseInteractable::getOrientation(), BaseInteractable::getPosition(), i, j, localDebris_, NurbsWall::nurbsSurface_, p, Quaternion::rotate(), and size.
Member Data Documentation
localDebris_
std::vector<std::vector<Mdouble> > WearableNurbsWall::localDebris_ private
Referenced by processDebris(), read(), set(), storeDebris(), WearableNurbsWall(), write(), and writeWallDetailsVTK().
The documentation for this class was generated from the following files:
WearableNurbsWall.h
WearableNurbsWall.cc