MercuryDPM: oomph::MatrixVectorProduct Class Reference
oomph::MatrixVectorProduct Class Reference
#include <matrix_vector_product.h>
Public Member Functions
MatrixVectorProduct ()
Constructor.
MatrixVectorProduct (const MatrixVectorProduct &)=delete
Broken copy constructor.
void operator= (const MatrixVectorProduct &)=delete
Broken assignment operator.
~MatrixVectorProduct ()
Destructor.
void clean_up_memory ()
clear the memory
void setup (CRDoubleMatrix *matrix_pt, const LinearAlgebraDistribution *col_dist_pt=0)
void multiply (const DoubleVector &x, DoubleVector &y) const
void multiply_transpose (const DoubleVector &x, DoubleVector &y) const
const unsigned & ncol () const
Access function to the number of columns.
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
void build_distribution (const LinearAlgebraDistribution &dist)
Private Attributes
bool Using_trilinos
CRDoubleMatrix * Oomph_matrix_pt
an oomph-lib matrix
LinearAlgebraDistribution * Column_distribution_pt
unsigned Ncol
number of columns of the matrix
Additional Inherited Members
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
Detailed Description
Matrix vector product helper class - primarily a wrapper to Trilinos's Epetra matrix vector product methods. This allows the epetra matrix to be assembled once and the matrix vector product to be performed many times.
Constructor & Destructor Documentation
MatrixVectorProduct() [1/2]
oomph::MatrixVectorProduct::MatrixVectorProduct () inline
Constructor.
     {
       // null pointers
 #ifdef OOMPH_HAS_TRILINOS
       Epetra_matrix_pt = 0;
 #endif
       Oomph_matrix_pt = 0;
       Column_distribution_pt = 0;
     }
References Column_distribution_pt, and Oomph_matrix_pt.
MatrixVectorProduct() [2/2]
oomph::MatrixVectorProduct::MatrixVectorProduct (const MatrixVectorProduct &) delete
Broken copy constructor.
~MatrixVectorProduct()
oomph::MatrixVectorProduct::~MatrixVectorProduct () inline
Destructor.
     {
       this->clean_up_memory();
     }
References clean_up_memory().
Member Function Documentation
clean_up_memory()
void oomph::MatrixVectorProduct::clean_up_memory () inline
clear the memory
     {
 #ifdef OOMPH_HAS_TRILINOS
       delete Epetra_matrix_pt;
       Epetra_matrix_pt = 0;
 #endif
       delete Oomph_matrix_pt;
       Oomph_matrix_pt = 0;
       delete Column_distribution_pt;
       Column_distribution_pt = 0;
     }
References Column_distribution_pt, and Oomph_matrix_pt.
Referenced by oomph::PseudoElasticFSIPreconditioner::clean_up_memory(), setup(), and ~MatrixVectorProduct().
multiply()
void oomph::MatrixVectorProduct::multiply (const DoubleVector & x, DoubleVector & y) const
Apply the operator to the vector x and return the result in the vector y
   {
 #ifdef PARANOID
     // check that the distribution of x is setup
     if (!x.built())
     {
       std::ostringstream error_message_stream;
       error_message_stream << "The distribution of the vector x must be setup";
       throw OomphLibError(error_message_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
     // Check to see if the distribution of the matrix column is the same as the
     // distribution of the vector to be operated on.
     if (*this->Column_distribution_pt != *x.distribution_pt())
     {
       std::ostringstream error_message_stream;
       error_message_stream
         << "The distribution of the x Vector is not the same as"
         << " the column distribution.";
       throw OomphLibError(error_message_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
     // if y is setup then it should have the same distribution as
     // the matrix used to set this up.
     if (y.built())
     {
       if (!(*y.distribution_pt() == *this->distribution_pt()))
       {
         std::ostringstream error_message_stream;
         error_message_stream
           << "The y vector is setup and therefore must have the same "
           << "distribution as the matrix used to set up the "
              "MatrixVectorProduct";
         throw OomphLibError(error_message_stream.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
     }
 #endif
     // if y is not setup then setup the distribution
     if (!y.built())
     {
       // Resize and initialize the solution vector
       y.build(this->distribution_pt(), 0.0);
     }
     // apply the operator
     if (Using_trilinos)
     {
 #ifdef OOMPH_HAS_TRILINOS
       trilinos_multiply_helper(x, y);
 #endif
     }
     else
     {
       Oomph_matrix_pt->multiply(x, y);
     }
   }
References Column_distribution_pt, oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::CRDoubleMatrix::multiply(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, Oomph_matrix_pt, Using_trilinos, plotDoE::x, and y.
Referenced by oomph::FSIPreconditioner::preconditioner_solve(), oomph::PseudoElasticFSIPreconditioner::preconditioner_solve(), oomph::PressureBasedSolidLSCPreconditioner::preconditioner_solve(), and oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::preconditioner_solve().
multiply_transpose()
void oomph::MatrixVectorProduct::multiply_transpose (const DoubleVector & x, DoubleVector & y) const
Apply the transpose of the operator to the vector x and return the result in the vector y
   {
 #ifdef PARANOID
     // check that the distribution of x is setup
     if (!x.built())
     {
       std::ostringstream error_message_stream;
       error_message_stream << "The distribution of the vector x must be setup";
       throw OomphLibError(error_message_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
     // Check to see if x.size() = ncol()
     if (*this->distribution_pt() != *x.distribution_pt())
     {
       std::ostringstream error_message_stream;
       error_message_stream
         << "This class assumes that the y vector has a uniform "
         << "distributed distribution.";
       throw OomphLibError(error_message_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
     // if y is setup then it should have the same distribution as x
     if (y.built())
     {
       if (!(*y.distribution_pt() == *this->Column_distribution_pt))
       {
         std::ostringstream error_message_stream;
         error_message_stream
           << "The y vector is setup and therefore must have the same "
           << "distribution as the vector x";
         throw OomphLibError(error_message_stream.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
     }
 #endif
     // if y is not setup then setup the distribution
     if (!y.built())
     {
       // Resize and initialize the solution vector
       y.build(this->Column_distribution_pt, 0.0);
     }
     // apply the transpose operator
     if (Using_trilinos)
     {
 #ifdef OOMPH_HAS_TRILINOS
       trilinos_multiply_transpose_helper(x, y);
 #endif
     }
     else
     {
       Oomph_matrix_pt->multiply_transpose(x, y);
     }
   }
References Column_distribution_pt, oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::CRDoubleMatrix::multiply_transpose(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, Oomph_matrix_pt, Using_trilinos, plotDoE::x, and y.
Referenced by oomph::PressureBasedSolidLSCPreconditioner::preconditioner_solve(), and oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::preconditioner_solve().
ncol()
const unsigned& oomph::MatrixVectorProduct::ncol () const inline
Access function to the number of columns.
     {
       return Ncol;
     }
References Ncol.
operator=()
void oomph::MatrixVectorProduct::operator= (const MatrixVectorProduct &) delete
Broken assignment operator.
setup()
void oomph::MatrixVectorProduct::setup (CRDoubleMatrix * matrix_pt, const LinearAlgebraDistribution * col_dist_pt = 0)
Setup the matrix vector product operator. WARNING: This class is wrapper to Trilinos Epetra matrix vector multiply methods, if Trilinos is not installed then this class will function as expected, but there will be no computational speed gain. By default the Epetra_CrsMatrix::multiply(...) are employed. The optional argument col_dist_pt is the distribution of: x if using multiply(...) or y if using multiply_transpose(...) where this is A x = y. By default, this is assumed to the uniformly distributed based on matrix_pt->ncol().
   {
     // clean memory
     this->clean_up_memory();
     // (re)build distribution_pt
     this->build_distribution(matrix_pt->distribution_pt());
     // store the number of columns
     Ncol = matrix_pt->ncol();
     // determine whether we are using trilinos
     Using_trilinos = false;
 #ifdef OOMPH_HAS_TRILINOS
 #ifdef OOMPH_HAS_MPI
     if (MPI_Helpers::mpi_has_been_initialised())
     {
       Using_trilinos = true;
     }
 #else
     Using_trilinos = true;
 #endif
 #endif
     // create the column distribution map, if a distribution is not provided,
     // create a uniformly distributed based on matrix_pt->ncol().
     // Otherwise, use the provided distribution.
     if (col_dist_pt == 0)
     {
       Column_distribution_pt = new LinearAlgebraDistribution(
         matrix_pt->distribution_pt()->communicator_pt(),
         matrix_pt->ncol(),
         matrix_pt->distribution_pt()->distributed());
     }
     else
     {
       Column_distribution_pt = new LinearAlgebraDistribution(col_dist_pt);
     }
     // setup the operator
     if (Using_trilinos)
     {
 #ifdef OOMPH_HAS_TRILINOS
       double t_start = TimingHelpers::timer();
       Epetra_matrix_pt =
         TrilinosEpetraHelpers::create_distributed_epetra_matrix(
           matrix_pt, Column_distribution_pt);
       double t_end = TimingHelpers::timer();
       oomph_info << "Time to build epetra matrix [sec] : " << t_end - t_start
                  << std::endl;
 #endif
     }
     else
     {
       double t_start = TimingHelpers::timer();
       Oomph_matrix_pt = new CRDoubleMatrix(*matrix_pt);
       double t_end = TimingHelpers::timer();
       oomph_info << "Time to copy CRDoubleMatrix [sec] : " << t_end - t_start
                  << std::endl;
     }
   }
References oomph::DistributableLinearAlgebraObject::build_distribution(), clean_up_memory(), Column_distribution_pt, oomph::LinearAlgebraDistribution::communicator_pt(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_matrix(), oomph::LinearAlgebraDistribution::distributed(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::MPI_Helpers::mpi_has_been_initialised(), oomph::CRDoubleMatrix::ncol(), Ncol, oomph::oomph_info, Oomph_matrix_pt, oomph::TimingHelpers::timer(), and Using_trilinos.
Referenced by oomph::BlockPreconditioner< MATRIX >::setup_matrix_vector_product().
Member Data Documentation
Column_distribution_pt
LinearAlgebraDistribution* oomph::MatrixVectorProduct::Column_distribution_pt private
The distribution of: x if using multiply(...) or y if using multiply_transpose(...) where this is A x = y.
Referenced by clean_up_memory(), MatrixVectorProduct(), multiply(), multiply_transpose(), and setup().
Ncol
unsigned oomph::MatrixVectorProduct::Ncol private
number of columns of the matrix
Referenced by ncol(), and setup().
Oomph_matrix_pt
CRDoubleMatrix* oomph::MatrixVectorProduct::Oomph_matrix_pt private
an oomph-lib matrix
Referenced by clean_up_memory(), MatrixVectorProduct(), multiply(), multiply_transpose(), and setup().
Using_trilinos
bool oomph::MatrixVectorProduct::Using_trilinos private
boolean indicating whether we are using trilinos to perform matvec
Referenced by multiply(), multiply_transpose(), and setup().
The documentation for this class was generated from the following files:
matrix_vector_product.h
matrix_vector_product.cc