MercuryDPM: Eigen::internal::block_evaluator< ArgType, BlockRows, BlockCols, InnerPanel, true > Struct Template Reference
Eigen::internal::block_evaluator< ArgType, BlockRows, BlockCols, InnerPanel, true > Struct Template Reference
#include <CoreEvaluators.h>
Public Types
typedef Block< ArgType, BlockRows, BlockCols, InnerPanel > XprType
typedef XprType::Scalar Scalar
Public Types inherited from Eigen::internal::mapbase_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, Block< ArgType, BlockRows, BlockCols, InnerPanel >::PlainObject >
enum
typedef Block< ArgType, BlockRows, BlockCols, InnerPanel > XprType
typedef XprType::PointerType PointerType
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
Public Types inherited from Eigen::internal::evaluator_base< Block< ArgType, BlockRows, BlockCols, InnerPanel > >
enum
typedef traits< Block< ArgType, BlockRows, BlockCols, InnerPanel > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE block_evaluator (const XprType &block)
Public Member Functions inherited from Eigen::internal::mapbase_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, Block< ArgType, BlockRows, BlockCols, InnerPanel >::PlainObject >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE mapbase_evaluator (const XprType &map)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void writePacket (Index row, Index col, const PacketType &x)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void writePacket (Index index, const PacketType &x)
Public Member Functions inherited from Eigen::internal::evaluator_base< Block< ArgType, BlockRows, BlockCols, InnerPanel > >
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE evaluator_base ()=default
Additional Inherited Members
Protected Member Functions inherited from Eigen::internal::mapbase_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, Block< ArgType, BlockRows, BlockCols, InnerPanel >::PlainObject >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index rowStride () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index colStride () const EIGEN_NOEXCEPT
Protected Attributes inherited from Eigen::internal::mapbase_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, Block< ArgType, BlockRows, BlockCols, InnerPanel >::PlainObject >
PointerType m_data
const internal::variable_if_dynamic< Index, XprType::InnerStrideAtCompileTime > m_innerStride
const internal::variable_if_dynamic< Index, XprType::OuterStrideAtCompileTime > m_outerStride
Member Typedef Documentation
Scalar
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> typedef XprType::Scalar Eigen::internal::block_evaluator< ArgType, BlockRows, BlockCols, InnerPanel, true >::Scalar
XprType
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> typedef Block<ArgType, BlockRows, BlockCols, InnerPanel> Eigen::internal::block_evaluator< ArgType, BlockRows, BlockCols, InnerPanel, true >::XprType
Constructor & Destructor Documentation
block_evaluator()
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::block_evaluator< ArgType, BlockRows, BlockCols, InnerPanel, true >::block_evaluator (const XprType & block) inline explicit
       : mapbase_evaluator<XprType, typename XprType::PlainObject>(block) {
     eigen_internal_assert((internal::is_constant_evaluated() ||
                            (std::uintptr_t(block.data()) % plain_enum_max(1, evaluator<XprType>::Alignment)) == 0) &&
                           "data is not aligned");
   }
References block(), eigen_internal_assert, Eigen::internal::is_constant_evaluated(), and Eigen::internal::plain_enum_max().
The documentation for this struct was generated from the following file:
CoreEvaluators.h