MercuryDPM: Eigen::JacobiRotation< Scalar > Class Template Reference
Eigen::JacobiRotation< Scalar > Class Template Reference
Dense matrix and array manipulation » Reference » Jacobi_Module
Rotation given by a cosine-sine pair.
#include <Jacobi.h>
Public Types
typedef NumTraits< Scalar >::Real RealScalar
Public Member Functions
EIGEN_DEVICE_FUNC JacobiRotation ()
EIGEN_DEVICE_FUNC JacobiRotation (const Scalar &c, const Scalar &s)
EIGEN_DEVICE_FUNC Scalar & c ()
EIGEN_DEVICE_FUNC Scalar c () const
EIGEN_DEVICE_FUNC Scalar & s ()
EIGEN_DEVICE_FUNC Scalar s () const
EIGEN_DEVICE_FUNC JacobiRotation operator* (const JacobiRotation &other)
EIGEN_DEVICE_FUNC JacobiRotation transpose () const
EIGEN_DEVICE_FUNC JacobiRotation adjoint () const
template<typename Derived >
EIGEN_DEVICE_FUNC bool makeJacobi (const MatrixBase< Derived > &, Index p, Index q)
EIGEN_DEVICE_FUNC bool makeJacobi (const RealScalar &x, const Scalar &y, const RealScalar &z)
EIGEN_DEVICE_FUNC void makeGivens (const Scalar &p, const Scalar &q, Scalar *r=0)
Protected Member Functions
EIGEN_DEVICE_FUNC void makeGivens (const Scalar &p, const Scalar &q, Scalar *r, internal::true_type)
EIGEN_DEVICE_FUNC void makeGivens (const Scalar &p, const Scalar &q, Scalar *r, internal::false_type)
Protected Attributes
Scalar m_c
Scalar m_s
Detailed Description
template<typename Scalar>
class Eigen::JacobiRotation< Scalar >
Rotation given by a cosine-sine pair.
\jacobi_module
This class represents a Jacobi or Givens rotation. This is a 2D rotation in the plane J of angle \(\theta \) defined by its cosine c and sine s as follow: \(J = \left (\begin{array}{cc} c & \overline s \\ -s & \overline c \end{array} \right) \)
You can apply the respective counter-clockwise rotation to a column vector v by applying its adjoint on the left: \(v = J^* v \) that translates to the following Eigen code:
v.applyOnTheLeft(J.adjoint());
See also
MatrixBase::applyOnTheLeft(), MatrixBase::applyOnTheRight()
Member Typedef Documentation
RealScalar
template<typename Scalar > typedef NumTraits<Scalar>::Real Eigen::JacobiRotation< Scalar >::RealScalar
Constructor & Destructor Documentation
JacobiRotation() [1/2]
template<typename Scalar > EIGEN_DEVICE_FUNC Eigen::JacobiRotation< Scalar >::JacobiRotation () inline
Default constructor without any initialization.
 {}
Referenced by Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::JacobiRotation< Scalar >::operator*(), and Eigen::JacobiRotation< Scalar >::transpose().
JacobiRotation() [2/2]
template<typename Scalar > EIGEN_DEVICE_FUNC Eigen::JacobiRotation< Scalar >::JacobiRotation (const Scalar & c, const Scalar & s) inline
Construct a planar rotation from a cosine-sine pair (c, s).
 : m_c(c), m_s(s) {}
Member Function Documentation
adjoint()
template<typename Scalar > EIGEN_DEVICE_FUNC JacobiRotation Eigen::JacobiRotation< Scalar >::adjoint () const inline
Returns the adjoint transformation
{
     using numext::conj;
     return JacobiRotation(conj(m_c), -m_s);
   }
References conj(), Eigen::conj(), Eigen::JacobiRotation< Scalar >::JacobiRotation(), Eigen::JacobiRotation< Scalar >::m_c, and Eigen::JacobiRotation< Scalar >::m_s.
Referenced by Eigen::internal::matrix_function_permute_schur().
c() [1/2]
template<typename Scalar > EIGEN_DEVICE_FUNC Scalar& Eigen::JacobiRotation< Scalar >::c () inline
 { return m_c; }
References Eigen::JacobiRotation< Scalar >::m_c.
Referenced by Eigen::internal::lmqrsolv(), Eigen::internal::qrsolv(), Eigen::internal::r1updt(), and Eigen::internal::real_2x2_jacobi_svd().
c() [2/2]
template<typename Scalar > EIGEN_DEVICE_FUNC Scalar Eigen::JacobiRotation< Scalar >::c () const inline
 { return m_c; }
References Eigen::JacobiRotation< Scalar >::m_c.
makeGivens() [1/3]
template<typename Scalar > EIGEN_DEVICE_FUNC void Eigen::JacobiRotation< Scalar >::makeGivens (const Scalar & p, const Scalar & q, Scalar * r, internal::false_type) protected
{
   using std::abs;
   using std::sqrt;
   if (numext::is_exactly_zero(q)) {
     m_c = p < Scalar(0) ? Scalar(-1) : Scalar(1);
     m_s = Scalar(0);
     if (r) *r = abs(p);
   } else if (numext::is_exactly_zero(p)) {
     m_c = Scalar(0);
     m_s = q < Scalar(0) ? Scalar(1) : Scalar(-1);
     if (r) *r = abs(q);
   } else if (abs(p) > abs(q)) {
     Scalar t = q / p;
     Scalar u = sqrt(Scalar(1) + numext::abs2(t));
     if (p < Scalar(0)) u = -u;
     m_c = Scalar(1) / u;
     m_s = -t * m_c;
     if (r) *r = p * u;
   } else {
     Scalar t = p / q;
     Scalar u = sqrt(Scalar(1) + numext::abs2(t));
     if (q < Scalar(0)) u = -u;
     m_s = -Scalar(1) / u;
     m_c = -t * m_s;
     if (r) *r = q * u;
   }
 }
References abs(), Eigen::numext::abs2(), Eigen::numext::is_exactly_zero(), p, Eigen::numext::q, UniformPSDSelfTest::r, sqrt(), and plotPSD::t.
makeGivens() [2/3]
template<typename Scalar > EIGEN_DEVICE_FUNC void Eigen::JacobiRotation< Scalar >::makeGivens (const Scalar & p, const Scalar & q, Scalar * r, internal::true_type) protected
{
   using numext::conj;
   using std::abs;
   using std::sqrt;
   if (q == Scalar(0)) {
     m_c = numext::real(p) < 0 ? Scalar(-1) : Scalar(1);
     m_s = 0;
     if (r) *r = m_c * p;
   } else if (p == Scalar(0)) {
     m_c = 0;
     m_s = -q / abs(q);
     if (r) *r = abs(q);
   } else {
     RealScalar p1 = numext::norm1(p);
     RealScalar q1 = numext::norm1(q);
     if (p1 >= q1) {
       Scalar ps = p / p1;
       RealScalar p2 = numext::abs2(ps);
       Scalar qs = q / p1;
       RealScalar q2 = numext::abs2(qs);
       RealScalar u = sqrt(RealScalar(1) + q2 / p2);
       if (numext::real(p) < RealScalar(0)) u = -u;
       m_c = Scalar(1) / u;
       m_s = -qs * conj(ps) * (m_c / p2);
       if (r) *r = p * u;
     } else {
       Scalar ps = p / q1;
       RealScalar p2 = numext::abs2(ps);
       Scalar qs = q / q1;
       RealScalar q2 = numext::abs2(qs);
       RealScalar u = q1 * sqrt(p2 + q2);
       if (numext::real(p) < RealScalar(0)) u = -u;
       p1 = abs(p);
       ps = p / p1;
       m_c = p1 / u;
       m_s = -conj(ps) * (q / u);
       if (r) *r = ps * u;
     }
   }
 }
References abs(), Eigen::numext::abs2(), conj(), Eigen::conj(), p, p1, ps, Eigen::numext::q, UniformPSDSelfTest::r, and sqrt().
makeGivens() [3/3]
template<typename Scalar > EIGEN_DEVICE_FUNC void Eigen::JacobiRotation< Scalar >::makeGivens (const Scalar & p, const Scalar & q, Scalar * r = 0)
Makes *this as a Givens rotation G such that applying \(G^* \) to the left of the vector \(V = \left (\begin{array}{c} p \\ q \end{array} \right)\) yields: \(G^* V = \left (\begin{array}{c} r \\ 0 \end{array} \right)\).
The value of r is returned if r is not null (the default is null). Also note that G is built such that the cosine is always real.
Example:
Vector2f v = Vector2f::Random();
JacobiRotation<float> G;
G.makeGivens(v.x(), v.y());
cout << "Here is the vector v:" << endl << v << endl;
v.applyOnTheLeft(0, 1, G.adjoint());
cout << "Here is the vector J' * v:" << endl << v << endl;
Output:
This function implements the continuous Givens rotation generation algorithm found in Anderson (2000), Discontinuous Plane Rotations and the Symmetric Eigenvalue Problem. LAPACK Working Note 150, University of Tennessee, UT-CS-00-454, December 4, 2000.
See also
MatrixBase::applyOnTheLeft(), MatrixBase::applyOnTheRight()
{
   makeGivens(p, q, r, std::conditional_t<NumTraits<Scalar>::IsComplex, internal::true_type, internal::false_type>());
 }
References makeGivens(), p, Eigen::numext::q, and UniformPSDSelfTest::r.
Referenced by Eigen::internal::llt_rank_update_lower(), Eigen::internal::lmqrsolv(), Eigen::internal::matrix_function_permute_schur(), Eigen::internal::qrsolv(), and Eigen::internal::r1updt().
makeJacobi() [1/2]
template<typename Scalar > template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::JacobiRotation< Scalar >::makeJacobi (const MatrixBase< Derived > & m, Index p, Index q) inline
Makes *this as a Jacobi rotation J such that applying J on both the right and left sides of the 2x2 selfadjoint matrix \(B = \left (\begin{array}{cc} \text{this}_{pp} & \text{this}_{pq} \\ (\text{this}_{pq})^* & \text{this}_{qq} \end{array} \right)\) yields a diagonal matrix \(A = J^* B J \)
Example:
Matrix2f m = Matrix2f::Random();
m = (m + m.adjoint()).eval();
JacobiRotation<float> J;
J.makeJacobi(m, 0, 1);
cout << "Here is the matrix m:" << endl << m << endl;
m.applyOnTheLeft(0, 1, J.adjoint());
m.applyOnTheRight(0, 1, J);
cout << "Here is the matrix J' * m * J:" << endl << m << endl;
Output:
See also
JacobiRotation::makeJacobi(RealScalar, Scalar, RealScalar), MatrixBase::applyOnTheLeft(), MatrixBase::applyOnTheRight()
{
   return makeJacobi(numext::real(m.coeff(p, p)), m.coeff(p, q), numext::real(m.coeff(q, q)));
 }
References m, makeJacobi(), p, and Eigen::numext::q.
Referenced by Eigen::internal::real_2x2_jacobi_svd().
makeJacobi() [2/2]
template<typename Scalar > EIGEN_DEVICE_FUNC bool Eigen::JacobiRotation< Scalar >::makeJacobi (const RealScalar & x, const Scalar & y, const RealScalar & z)
Makes *this as a Jacobi rotation J such that applying J on both the right and left sides of the selfadjoint 2x2 matrix \(B = \left (\begin{array}{cc} x & y \\ \overline y & z \end{array} \right)\) yields a diagonal matrix \(A = J^* B J \)
See also
MatrixBase::makeJacobi(const MatrixBase<Derived>&, Index, Index), MatrixBase::applyOnTheLeft(), MatrixBase::applyOnTheRight()
{
   using std::abs;
   using std::sqrt;
   RealScalar deno = RealScalar(2) * abs(y);
   if (deno < (std::numeric_limits<RealScalar>::min)()) {
     m_c = Scalar(1);
     m_s = Scalar(0);
     return false;
   } else {
     RealScalar tau = (x - z) / deno;
     RealScalar w = sqrt(numext::abs2(tau) + RealScalar(1));
     RealScalar t;
     if (tau > RealScalar(0)) {
       t = RealScalar(1) / (tau + w);
     } else {
       t = RealScalar(1) / (tau - w);
     }
     RealScalar sign_t = t > RealScalar(0) ? RealScalar(1) : RealScalar(-1);
     RealScalar n = RealScalar(1) / sqrt(numext::abs2(t) + RealScalar(1));
     m_s = -sign_t * (numext::conj(y) / abs(y)) * abs(t) * n;
     m_c = n;
     return true;
   }
 }
References abs(), Eigen::numext::abs2(), conj(), min, n, sqrt(), plotPSD::t, w, plotDoE::x, and y.
operator*()
template<typename Scalar > EIGEN_DEVICE_FUNC JacobiRotation Eigen::JacobiRotation< Scalar >::operator* (const JacobiRotation< Scalar > & other) inline
Concatenates two planar rotation
{
     using numext::conj;
     return JacobiRotation(m_c * other.m_c - conj(m_s) * other.m_s,
                           conj(m_c * conj(other.m_s) + conj(m_s) * conj(other.m_c)));
   }
References conj(), Eigen::conj(), Eigen::JacobiRotation< Scalar >::JacobiRotation(), Eigen::JacobiRotation< Scalar >::m_c, and Eigen::JacobiRotation< Scalar >::m_s.
s() [1/2]
template<typename Scalar > EIGEN_DEVICE_FUNC Scalar& Eigen::JacobiRotation< Scalar >::s () inline
 { return m_s; }
References Eigen::JacobiRotation< Scalar >::m_s.
Referenced by Eigen::internal::lmqrsolv(), Eigen::internal::qrsolv(), Eigen::internal::r1updt(), and Eigen::internal::real_2x2_jacobi_svd().
s() [2/2]
template<typename Scalar > EIGEN_DEVICE_FUNC Scalar Eigen::JacobiRotation< Scalar >::s () const inline
 { return m_s; }
References Eigen::JacobiRotation< Scalar >::m_s.
transpose()
template<typename Scalar > EIGEN_DEVICE_FUNC JacobiRotation Eigen::JacobiRotation< Scalar >::transpose () const inline
Returns the transposed transformation
{
     using numext::conj;
     return JacobiRotation(m_c, -conj(m_s));
   }
References conj(), Eigen::conj(), Eigen::JacobiRotation< Scalar >::JacobiRotation(), Eigen::JacobiRotation< Scalar >::m_c, and Eigen::JacobiRotation< Scalar >::m_s.
Referenced by Eigen::RealQZ< MatrixType_ >::compute(), Eigen::JacobiSVD< MatrixType_, Options_ >::compute_impl(), and Eigen::internal::real_2x2_jacobi_svd().
Member Data Documentation
m_c
template<typename Scalar > Scalar Eigen::JacobiRotation< Scalar >::m_c protected
Referenced by Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::JacobiRotation< Scalar >::c(), Eigen::JacobiRotation< Scalar >::operator*(), and Eigen::JacobiRotation< Scalar >::transpose().
m_s
template<typename Scalar > Scalar Eigen::JacobiRotation< Scalar >::m_s protected
Referenced by Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::JacobiRotation< Scalar >::operator*(), Eigen::JacobiRotation< Scalar >::s(), and Eigen::JacobiRotation< Scalar >::transpose().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
Jacobi.h