MercuryDPM: LLT_solve.cpp File Reference
LLT_solve.cpp File Reference
Typedefs
typedef Matrix< float, Dynamic, 2 > DataMatrix
Variables
DataMatrix samples = DataMatrix::Random(12, 2)
VectorXf elevations = 2 * samples.col(0) + 3 * samples.col(1) + VectorXf::Random(12) * 0.1
Matrix< float, 2, 1 > xy = (samples.adjoint() * samples).llt().solve((samples.adjoint() * elevations))
Typedef Documentation
DataMatrix
typedef Matrix<float, Dynamic, 2> DataMatrix
Variable Documentation
elevations
VectorXf elevations = 2 * samples.col(0) + 3 * samples.col(1) + VectorXf::Random(12) * 0.1
samples
DataMatrix samples = DataMatrix::Random(12, 2)
Referenced by svd_fill_random().
xy
Matrix<float, 2, 1> xy = (samples.adjoint() * samples).llt().solve((samples.adjoint() * elevations))
Referenced by Matrix3D::Matrix3D(), MatrixSymmetric3D::MatrixSymmetric3D(), Eigen::internal::twoprod_low(), HorizontalBaseScrew::writeVTK(), ScrewsymmetricIntersectionOfWalls::writeVTK(), and AxisymmetricIntersectionOfWalls::writeVTK().