MercuryDPM: typed_logicals_test_impl< ArrayType > Struct Template Reference
typed_logicals_test_impl< ArrayType > Struct Template Reference
Public Types
using Scalar = typename ArrayType::Scalar
Static Public Member Functions
static bool scalar_to_bool (const Scalar &x)
static Scalar bool_to_scalar (bool x)
static Scalar eval_bool_and (const Scalar &x, const Scalar &y)
static Scalar eval_bool_or (const Scalar &x, const Scalar &y)
static Scalar eval_bool_xor (const Scalar &x, const Scalar &y)
static Scalar eval_bool_not (const Scalar &x)
static void run (const ArrayType &m)
Member Typedef Documentation
Scalar
template<typename ArrayType > using typed_logicals_test_impl< ArrayType >::Scalar = typename ArrayType::Scalar
Member Function Documentation
bool_to_scalar()
template<typename ArrayType > static Scalar typed_logicals_test_impl< ArrayType >::bool_to_scalar (bool x) inline static
 { return x ? Scalar(1) : Scalar(0); }
References plotDoE::x.
Referenced by typed_logicals_test_impl< ArrayType >::eval_bool_and(), typed_logicals_test_impl< ArrayType >::eval_bool_not(), typed_logicals_test_impl< ArrayType >::eval_bool_or(), and typed_logicals_test_impl< ArrayType >::eval_bool_xor().
eval_bool_and()
template<typename ArrayType > static Scalar typed_logicals_test_impl< ArrayType >::eval_bool_and (const Scalar & x, const Scalar & y) inline static
{
     return bool_to_scalar(scalar_to_bool(x) && scalar_to_bool(y));
   }
References typed_logicals_test_impl< ArrayType >::bool_to_scalar(), typed_logicals_test_impl< ArrayType >::scalar_to_bool(), plotDoE::x, and y.
Referenced by typed_logicals_test_impl< ArrayType >::run().
eval_bool_not()
template<typename ArrayType > static Scalar typed_logicals_test_impl< ArrayType >::eval_bool_not (const Scalar & x) inline static
 { return bool_to_scalar(!scalar_to_bool(x)); }
References typed_logicals_test_impl< ArrayType >::bool_to_scalar(), typed_logicals_test_impl< ArrayType >::scalar_to_bool(), and plotDoE::x.
Referenced by typed_logicals_test_impl< ArrayType >::run().
eval_bool_or()
template<typename ArrayType > static Scalar typed_logicals_test_impl< ArrayType >::eval_bool_or (const Scalar & x, const Scalar & y) inline static
{
     return bool_to_scalar(scalar_to_bool(x) || scalar_to_bool(y));
   }
References typed_logicals_test_impl< ArrayType >::bool_to_scalar(), typed_logicals_test_impl< ArrayType >::scalar_to_bool(), plotDoE::x, and y.
Referenced by typed_logicals_test_impl< ArrayType >::run().
eval_bool_xor()
template<typename ArrayType > static Scalar typed_logicals_test_impl< ArrayType >::eval_bool_xor (const Scalar & x, const Scalar & y) inline static
{
     return bool_to_scalar(scalar_to_bool(x) != scalar_to_bool(y));
   }
References typed_logicals_test_impl< ArrayType >::bool_to_scalar(), typed_logicals_test_impl< ArrayType >::scalar_to_bool(), plotDoE::x, and y.
Referenced by typed_logicals_test_impl< ArrayType >::run().
run()
template<typename ArrayType > static void typed_logicals_test_impl< ArrayType >::run (const ArrayType & m) inline static
{
     Index rows = m.rows();
     Index cols = m.cols();
     ArrayType m1(rows, cols), m2(rows, cols), m3(rows, cols), m4(rows, cols);
     m1.setRandom();
     m2.setRandom();
     m1 *= ArrayX<bool>::Random(rows, cols).cast<Scalar>();
     m2 *= ArrayX<bool>::Random(rows, cols).cast<Scalar>();
     // test boolean and
     m3 = m1 && m2;
     m4 = m1.binaryExpr(m2, [](const Scalar& x, const Scalar& y) { return eval_bool_and(x, y); });
     VERIFY_IS_CWISE_EQUAL(m3, m4);
     for (const Scalar& val : m3) VERIFY(val == Scalar(0) || val == Scalar(1));
     // test boolean or
     m3 = m1 || m2;
     m4 = m1.binaryExpr(m2, [](const Scalar& x, const Scalar& y) { return eval_bool_or(x, y); });
     VERIFY_IS_CWISE_EQUAL(m3, m4);
     for (const Scalar& val : m3) VERIFY(val == Scalar(0) || val == Scalar(1));
     // test boolean xor
     m3 = m1.binaryExpr(m2, internal::scalar_boolean_xor_op<Scalar>());
     m4 = m1.binaryExpr(m2, [](const Scalar& x, const Scalar& y) { return eval_bool_xor(x, y); });
     VERIFY_IS_CWISE_EQUAL(m3, m4);
     for (const Scalar& val : m3) VERIFY(val == Scalar(0) || val == Scalar(1));
     // test boolean not
     m3 = !m1;
     m4 = m1.unaryExpr([](const Scalar& x) { return eval_bool_not(x); });
     VERIFY_IS_CWISE_EQUAL(m3, m4);
     for (const Scalar& val : m3) VERIFY(val == Scalar(0) || val == Scalar(1));
     // test something more complicated
     m3 = m1 && m2;
     m4 = !(!m1 || !m2);
     VERIFY_IS_CWISE_EQUAL(m3, m4);
     m3 = m1.binaryExpr(m2, internal::scalar_boolean_xor_op<Scalar>());
     m4 = (!m1).binaryExpr((!m2), internal::scalar_boolean_xor_op<Scalar>());
     VERIFY_IS_CWISE_EQUAL(m3, m4);
     const size_t bytes = size_t(rows) * size_t(cols) * sizeof(Scalar);
     std::vector<uint8_t> m1_buffer(bytes), m2_buffer(bytes), m3_buffer(bytes), m4_buffer(bytes);
     std::memcpy(m1_buffer.data(), m1.data(), bytes);
     std::memcpy(m2_buffer.data(), m2.data(), bytes);
     // test bitwise and
     m3 = m1 & m2;
     std::memcpy(m3_buffer.data(), m3.data(), bytes);
     for (size_t i = 0; i < bytes; i++) VERIFY_IS_EQUAL(m3_buffer[i], uint8_t(m1_buffer[i] & m2_buffer[i]));
     // test bitwise or
     m3 = m1 | m2;
     std::memcpy(m3_buffer.data(), m3.data(), bytes);
     for (size_t i = 0; i < bytes; i++) VERIFY_IS_EQUAL(m3_buffer[i], uint8_t(m1_buffer[i] | m2_buffer[i]));
     // test bitwise xor
     m3 = m1 ^ m2;
     std::memcpy(m3_buffer.data(), m3.data(), bytes);
     for (size_t i = 0; i < bytes; i++) VERIFY_IS_EQUAL(m3_buffer[i], uint8_t(m1_buffer[i] ^ m2_buffer[i]));
     // test bitwise not
     m3 = ~m1;
     std::memcpy(m3_buffer.data(), m3.data(), bytes);
     for (size_t i = 0; i < bytes; i++) VERIFY_IS_EQUAL(m3_buffer[i], uint8_t(~m1_buffer[i]));
     // test something more complicated
     m3 = m1 & m2;
     m4 = ~(~m1 | ~m2);
     std::memcpy(m3_buffer.data(), m3.data(), bytes);
     std::memcpy(m4_buffer.data(), m4.data(), bytes);
     for (size_t i = 0; i < bytes; i++) VERIFY_IS_EQUAL(m3_buffer[i], m4_buffer[i]);
     m3 = m1 ^ m2;
     m4 = (~m1) ^ (~m2);
     std::memcpy(m3_buffer.data(), m3.data(), bytes);
     std::memcpy(m4_buffer.data(), m4.data(), bytes);
     for (size_t i = 0; i < bytes; i++) VERIFY_IS_EQUAL(m3_buffer[i], m4_buffer[i]);
   }
References cols, typed_logicals_test_impl< ArrayType >::eval_bool_and(), typed_logicals_test_impl< ArrayType >::eval_bool_not(), typed_logicals_test_impl< ArrayType >::eval_bool_or(), typed_logicals_test_impl< ArrayType >::eval_bool_xor(), i, m, m1, m2(), rows, calibrate::val, VERIFY, VERIFY_IS_CWISE_EQUAL, VERIFY_IS_EQUAL, plotDoE::x, and y.
Referenced by typed_logicals_test().
scalar_to_bool()
template<typename ArrayType > static bool typed_logicals_test_impl< ArrayType >::scalar_to_bool (const Scalar & x) inline static
 { return x != Scalar(0); }
References plotDoE::x.
Referenced by typed_logicals_test_impl< ArrayType >::eval_bool_and(), typed_logicals_test_impl< ArrayType >::eval_bool_not(), typed_logicals_test_impl< ArrayType >::eval_bool_or(), and typed_logicals_test_impl< ArrayType >::eval_bool_xor().
The documentation for this struct was generated from the following file:
array_cwise.cpp