MercuryDPM: rat43_functor Struct Reference
rat43_functor Struct Reference
Public Member Functions
rat43_functor (void)
int operator() (const VectorXd &b, VectorXd &fvec)
int df (const VectorXd &b, MatrixXd &fjac)
rat43_functor (void)
int operator() (const VectorXd &b, VectorXd &fvec)
int df (const VectorXd &b, MatrixXd &fjac)
Public Member Functions inherited from Eigen::DenseFunctor< double >
DenseFunctor ()
DenseFunctor (int inputs, int values)
int inputs () const
int values () const
Public Member Functions inherited from Functor< double >
Functor ()
Functor (int inputs, int values)
Functor ()
Functor (int inputs_, int values_)
int inputs () const
int inputs () const
int values () const
int values () const
Static Public Attributes
static const double x [15] = {1., 2., 3., 4., 5., 6., 7., 8., 9., 10., 11., 12., 13., 14., 15.}
static const double y [15]
Additional Inherited Members
Public Types inherited from Eigen::DenseFunctor< double >
enum
typedef double Scalar
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
typedef ColPivHouseholderQR< JacobianType > QRSolver
Public Types inherited from Functor< double >
enum
enum
typedef double Scalar
typedef double Scalar
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
Public Attributes inherited from Eigen::DenseFunctor< double >
const int m_inputs
const int m_values
Public Attributes inherited from Functor< double >
const int m_inputs
int m_inputs
const int m_values
int m_values
Constructor & Destructor Documentation
rat43_functor() [1/2]
rat43_functor::rat43_functor (void) inline
 : DenseFunctor<double>(4, 15) {}
rat43_functor() [2/2]
rat43_functor::rat43_functor (void) inline
 : Functor<double>(4, 15) {}
Member Function Documentation
df() [1/2]
int rat43_functor::df (const VectorXd & b, MatrixXd & fjac) inline
{
     assert(b.size() == 4);
     assert(fjac.rows() == 15);
     assert(fjac.cols() == 4);
     for (int i = 0; i < 15; i++) {
       double e = exp(b[1] - b[2] * x[i]);
       double power = -1. / b[3];
       fjac(i, 0) = pow(1. + e, power);
       fjac(i, 1) = power * b[0] * e * pow(1. + e, power - 1.);
       fjac(i, 2) = -power * b[0] * e * x[i] * pow(1. + e, power - 1.);
       fjac(i, 3) = b[0] * power * power * log(1. + e) * pow(1. + e, power);
     }
     return 0;
   }
References assert, b, e(), Eigen::bfloat16_impl::exp(), i, Eigen::bfloat16_impl::log(), Eigen::bfloat16_impl::pow(), and x.
df() [2/2]
int rat43_functor::df (const VectorXd & b, MatrixXd & fjac) inline
{
     assert(b.size() == 4);
     assert(fjac.rows() == 15);
     assert(fjac.cols() == 4);
     for (int i = 0; i < 15; i++) {
       double e = exp(b[1] - b[2] * x[i]);
       double power = -1. / b[3];
       fjac(i, 0) = pow(1. + e, power);
       fjac(i, 1) = power * b[0] * e * pow(1. + e, power - 1.);
       fjac(i, 2) = -power * b[0] * e * x[i] * pow(1. + e, power - 1.);
       fjac(i, 3) = b[0] * power * power * log(1. + e) * pow(1. + e, power);
     }
     return 0;
   }
References assert, b, e(), Eigen::bfloat16_impl::exp(), i, Eigen::bfloat16_impl::log(), Eigen::bfloat16_impl::pow(), and x.
operator()() [1/2]
int rat43_functor::operator() (const VectorXd & b, VectorXd & fvec) inline
{
     assert(b.size() == 4);
     assert(fvec.size() == 15);
     for (int i = 0; i < 15; i++) fvec[i] = b[0] * pow(1. + exp(b[1] - b[2] * x[i]), -1. / b[3]) - y[i];
     return 0;
   }
References assert, b, Eigen::bfloat16_impl::exp(), i, Eigen::bfloat16_impl::pow(), x, and y.
operator()() [2/2]
int rat43_functor::operator() (const VectorXd & b, VectorXd & fvec) inline
{
     assert(b.size() == 4);
     assert(fvec.size() == 15);
     for (int i = 0; i < 15; i++) fvec[i] = b[0] * pow(1. + exp(b[1] - b[2] * x[i]), -1. / b[3]) - y[i];
     return 0;
   }
References assert, b, Eigen::bfloat16_impl::exp(), i, Eigen::bfloat16_impl::pow(), x, and y.
Member Data Documentation
x
const double rat43_functor::x = {1., 2., 3., 4., 5., 6., 7., 8., 9., 10., 11., 12., 13., 14., 15.} static
Referenced by df(), and operator()().
y
const double rat43_functor::y static
Initial value:
= {16.08,  33.83,  65.80,  97.20,  191.55, 326.20, 386.87, 520.53,
                                     590.03, 651.92, 724.93, 699.56, 689.96, 637.56, 717.41}
Referenced by operator()().
The documentation for this struct was generated from the following files:
levenberg_marquardt.cpp
NonLinearOptimization.cpp