MercuryDPM: oomph::DocInfo Class Reference
oomph::DocInfo Class Reference
#include <oomph_utilities.h>
Public Member Functions
DocInfo ()
DocInfo (const std::string &directory)
Constructor with specific directory.
std::string directory () const
Output directory.
void set_directory (const std::string &directory)
void enable_doc ()
Enable documentation.
void disable_doc ()
Disable documentation.
bool is_doc_enabled () const
Are we documenting?
unsigned & number ()
Number used (e.g.) for labeling output files.
unsigned number () const
Number used (e.g.) for labeling output files. Const version.
std::string number_as_string () const
Get number as a string (useful to completely avoid C-strings).
std::string & label ()
String used (e.g.) for labeling output files.
std::string label () const
String used (e.g.) for labeling output files. Const version.
void enable_error_if_directory_does_not_exist ()
Call to throw an error if directory does not exist.
void disable_error_if_directory_does_not_exist ()
Call to issue a warning if the directory does not exists.
Private Attributes
std::string Directory
Directory name.
bool Doc_flag
Doc or don't?
unsigned Number
Number to label output file, say.
std::string Label
String to label output file, say.
bool Directory_must_exist
Detailed Description
Information for documentation of results: Directory and file number to enable output in the form RESLT/filename11.dat, say. Documentation can be switched on and off.
Constructor & Destructor Documentation
DocInfo() [1/2]
oomph::DocInfo::DocInfo () inline
Constructor. Default settings: Current directory, step ‘0’, label="", full documentation enabled and output directory is required to exist when set_directory() is called.
       : Directory("."),
         Doc_flag(true),
         Number(0),
         Label(""),
         Directory_must_exist(true)
     {
     }
DocInfo() [2/2]
oomph::DocInfo::DocInfo (const std::string & directory) inline
Constructor with specific directory.
       : Directory(directory),
         Doc_flag(true),
         Number(0),
         Label(""),
         Directory_must_exist(true)
     {
     }
Member Function Documentation
directory()
std::string oomph::DocInfo::directory () const inline
Output directory.
     {
       return Directory;
     }
References AxisymFvKParameters::Directory.
Referenced by PreconditionedFSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_convergence_check(), oomph::TreeBasedRefineableMeshBase::adapt_mesh(), CantileverProblem< ELEMENT >::CantileverProblem(), oomph::BinaryTreeForest::check_all_neighbours(), oomph::OcTreeForest::check_all_neighbours(), oomph::QuadTreeForest::check_all_neighbours(), FourierDecomposedHelmholtzProblem< ELEMENT >::check_gamma(), VorticityRecoveryProblem< ELEMENT >::check_smoothed_vorticity(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::CoatedDiskProblem(), BaseStateProblem< BASE_ELEMENT >::create_trace_file(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::create_trace_file(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::create_trace_files(), demo_smoothing_with_linear_elasticity(), demo_smoothing_with_nonlinear_elasticity(), demo_smoothing_with_poisson(), oomph::SolidHelpers::doc_2D_principal_stress(), DiskShockWaveProblem< ELEMENT, TIMESTEPPER >::doc_displ_and_veloc(), oomph::Z2ErrorEstimator::doc_flux(), oomph::FSI_functions::doc_fsi(), RefineableAdvectionDiffusionProblem< ELEMENT >::doc_solution(), SUPGAdvectionDiffusionProblem< ELEMENT >::doc_solution(), RefineableAdvectionDiffusionPipeProblem< ELEMENT >::doc_solution(), MeltContactProblem< ELEMENT >::doc_solution(), SolarRadiationProblem< ELEMENT >::doc_solution(), ContactProblem< ELEMENT >::doc_solution(), UnsteadyHeatMeltProblem< ELEMENT >::doc_solution(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::doc_solution(), RefineableFishPoissonProblem< ELEMENT >::doc_solution(), GeomObjectAsGeneralisedElementProblem::doc_solution(), NavierStokesProblem< ELEMENT >::doc_solution(), UnstructuredSolidProblem< ELEMENT, MESH >::doc_solution(), PrescribedBoundaryDisplacementProblem< ELEMENT >::doc_solution(), EntryFlowProblem< ELEMENT >::doc_solution(), ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::doc_solution(), RefineableConvectionProblem< NST_ELEMENT, AD_ELEMENT >::doc_solution(), DDConvectionProblem< NST_ELEMENT, AD_ELEMENT >::doc_solution(), RefineableDDConvectionProblem< NST_ELEMENT, AD_ELEMENT >::doc_solution(), ThermalProblem< ELEMENT >::doc_solution(), SteadyCurvedTubeProblem< ELEMENT >::doc_solution(), SteadyHelicalProblem< ELEMENT >::doc_solution(), FreeSurfaceRotationProblem< ELEMENT >::doc_solution(), SteadyTubeProblem< ELEMENT >::doc_solution(), SolidFreeSurfaceRotationProblem< ELEMENT >::doc_solution(), DiskShockWaveProblem< ELEMENT, TIMESTEPPER >::doc_solution(), AnnularDiskProblem< ELASTICITY_ELEMENT >::doc_solution(), RingWithTRibProblem< ELASTICITY_ELEMENT >::doc_solution(), CompressedSquareProblem< ELEMENT >::doc_solution(), UnstructuredImmersedEllipseProblem< ELEMENT >::doc_solution(), RefineableUnsteadyHeatProblem< ELEMENT >::doc_solution(), FSIRingProblem::doc_solution(), TetmeshPoissonProblem< ELEMENT >::doc_solution(), FallingBlockProblem< ELEMENT >::doc_solution(), RisingBubbleProblem< ELEMENT >::doc_solution(), OneDPoissonProblem< ELEMENT >::doc_solution(), SheetGlueProblem< ELEMENT >::doc_solution(), TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::doc_solution(), AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::doc_solution(), CapProblem< ELEMENT >::doc_solution(), PseudoSolidCapProblem< ELEMENT >::doc_solution(), BaseStateProblem< BASE_ELEMENT >::doc_solution(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::doc_solution(), MeltSpinningProblem< ELEMENT >::doc_solution(), InterfaceProblem< ELEMENT, TIMESTEPPER >::doc_solution(), RotatingCylinderProblem< ELEMENT, TIMESTEPPER >::doc_solution(), ElasticRingProblem< ELEMENT >::doc_solution(), FourierDecomposedHelmholtzProblem< ELEMENT >::doc_solution(), UnsteadyHeatProblem< ELEMENT >::doc_solution(), StefanBoltzmannProblem< ELEMENT >::doc_solution(), HelmholtzPointSourceProblem< ELEMENT >::doc_solution(), ScatteringProblem< ELEMENT >::doc_solution(), AirwayReopeningProblem< ELEMENT >::doc_solution(), CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::doc_solution(), DeformableFishPoissonProblem< ELEMENT >::doc_solution(), SegregatedFSICollapsibleChannelProblem< ELEMENT >::doc_solution(), OscRingNStProblem< ELEMENT >::doc_solution(), PressureWaveFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution(), PeriodicLoadProblem< ELEMENT >::doc_solution(), RefineablePeriodicLoadProblem< ELEMENT >::doc_solution(), RectangularDrivenCavityProblem< ELEMENT >::doc_solution(), PoissonProblem< ELEMENT >::doc_solution(), MultiPoissonProblem< ELEMENT >::doc_solution(), LinearWaveProblem< ELEMENT, TIMESTEPPER >::doc_solution(), FlowPastBoxProblem< ELEMENT >::doc_solution(), MovingBlockProblem< ELEMENT >::doc_solution(), RefineableDrivenCavityProblem< ELEMENT >::doc_solution(), QuarterCircleDrivenCavityProblem< ELEMENT >::doc_solution(), PRefineableDrivenCavityProblem< ELEMENT >::doc_solution(), RefineableTwoDPoissonProblem< ELEMENT >::doc_solution(), RefineableTwoMeshFluxPoissonProblem< ELEMENT >::doc_solution(), CantileverProblem< ELEMENT >::doc_solution(), RefineableSphereConvectionProblem< ELEMENT >::doc_solution(), AxisymFreeSurfaceNozzleAdvDiffRobinProblem< ELEMENT >::doc_solution(), FluxPoissonMGProblem< ELEMENT, MESH >::doc_solution(), UnitCubePoissonMGProblem< ELEMENT, MESH >::doc_solution(), BrethertonProblem< ELEMENT >::doc_solution(), ChannelWithLeafletProblem< ELEMENT >::doc_solution(), QuarterCircleDrivenCavityProblem2< ELEMENT >::doc_solution(), OscEllipseProblem< ELEMENT, TIMESTEPPER >::doc_solution(), RayleighProblem< ELEMENT, TIMESTEPPER >::doc_solution(), RayleighTractionProblem< ELEMENT, TIMESTEPPER >::doc_solution(), FpTestProblem::doc_solution(), ChannelSpineFlowProblem< ELEMENT >::doc_solution(), SpikedChannelSpineFlowProblem< ELEMENT >::doc_solution(), ThreeDimBethertonProblem< ELEMENT >::doc_solution(), ElasticInterfaceProblem< ELEMENT, TIMESTEPPER >::doc_solution(), TurekNonFSIProblem< ELEMENT >::doc_solution(), UnstructuredFluidProblem< ELEMENT >::doc_solution(), RefineablePoissonProblem< ELEMENT >::doc_solution(), PMLFourierDecomposedHelmholtzProblem< ELEMENT >::doc_solution(), PMLProblem< ELEMENT >::doc_solution(), ElasticAnnulusProblem< ELASTICITY_ELEMENT >::doc_solution(), EighthSpherePoissonProblem< ELEMENT >::doc_solution(), FishPoissonProblem< ELEMENT >::doc_solution(), SimpleRefineableFishPoissonProblem< ELEMENT >::doc_solution(), RefineableOneDPoissonProblem< ELEMENT >::doc_solution(), PRefineableOneDPoissonProblem< ELEMENT >::doc_solution(), FluxPoissonProblem< ELEMENT >::doc_solution(), TwoMeshFluxPoissonProblem< ELEMENT >::doc_solution(), PolarNSProblem< ELEMENT >::doc_solution(), oomph::StreamfunctionProblem::doc_solution(), StaticDiskCompressionProblem< ELEMENT >::doc_solution(), DiskOscillationProblem< ELEMENT >::doc_solution(), SimpleShearProblem< ELEMENT >::doc_solution(), ElasticFishProblem< ELEMENT >::doc_solution(), BlockCompressionProblem< ELEMENT >::doc_solution(), EultingSphereProblem< ELEMENT >::doc_solution(), RefineableElutingSphereProblem< ELEMENT >::doc_solution(), TwoMeshFluxSteadyAxisymAdvectionDiffusionProblem< ELEMENT >::doc_solution(), FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::doc_solution(), ThreeDPoissonProblem< ELEMENT >::doc_solution(), TestPoissonProblem< ELEMENT >::doc_solution(), TestRefineablePoissonProblem< ELEMENT >::doc_solution(), oomph::NonLinearElasticitySmoothMesh< ELEMENT >::doc_solution(), oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::doc_solution(), VorticityRecoveryProblem< ELEMENT >::doc_solution(), oomph::BiharmonicProblem< DIM >::doc_solution(), oomph::BiharmonicFluidProblem< DIM >::doc_solution(), FSIChannelWithLeafletProblem< ELEMENT >::doc_solution(), FSICollapsibleChannelProblem< ELEMENT >::doc_solution(), FSIDrivenCavityProblem< ELEMENT >::doc_solution(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution(), CollapsibleChannelProblem< ELEMENT >::doc_solution(), ShellProblem< ELEMENT >::doc_solution(), YoungLaplaceProblem< ELEMENT >::doc_solution(), RefineableYoungLaplaceProblem< ELEMENT >::doc_solution(), DrivenCavityProblem< ELEMENT, MESH >::doc_solution(), RefineableSphericalCouetteProblem< ELEMENT >::doc_solution(), RefineableSphericalSpinUpProblem< ELEMENT >::doc_solution(), SphericalSpinUpProblem< ELEMENT >::doc_solution(), oomph::WomersleyProblem< ELEMENT, DIM >::doc_solution(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::doc_solution(), OscRingNStProblem< ELEMENT >::doc_solution_historic(), SegregatedFSICollapsibleChannelProblem< ELEMENT >::doc_solution_steady(), SegregatedFSICollapsibleChannelProblem< ELEMENT >::doc_solution_unsteady(), doc_sparse_node_update(), ElasticCollapsibleChannelMesh< ELEMENT >::ElasticCollapsibleChannelMesh(), ElasticRefineableCollapsibleChannelMesh< ELEMENT >::ElasticRefineableCollapsibleChannelMesh(), GeomObjectAsGeneralisedElementProblem::GeomObjectAsGeneralisedElementProblem(), main(), oomph::OcTreeForest::open_hanging_node_files(), oomph::QuadTreeForest::open_hanging_node_files(), output_both_versions(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::RefineableMeshBase::p_refine_uniformly(), parallel_test(), CapProblem< ELEMENT >::parameter_study(), PseudoSolidCapProblem< ELEMENT >::parameter_study(), StaticDiskCompressionProblem< ELEMENT >::parameter_study(), BrethertonProblem< ELEMENT >::parameter_study(), AirwayReopeningProblem< ELEMENT >::parameter_study(), ElasticRingProblem< ELEMENT >::parameter_study(), oomph::RefineableMeshBase::refine_uniformly(), oomph::RefineableQuadFromTriangleMesh< ELEMENT >::refine_uniformly(), RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem(), DeformableFishPoissonProblem< ELEMENT >::run(), DiskShockWaveProblem< ELEMENT, TIMESTEPPER >::run(), DiskOscillationProblem< ELEMENT >::run(), DrivenCavityProblem< ELEMENT, MESH >::run(), run_impedance_tube(), ShellProblem< ELEMENT >::run_it(), CompressedSquareProblem< ELEMENT >::run_it(), run_it(), CantileverProblem< ELEMENT >::run_it(), run_navier_stokes_outflow(), run_prescribed_flux(), run_prescribed_pressure_gradient(), StefanBoltzmannProblem< ELEMENT >::setup_sb_radiation(), oomph::TetMeshBase::snap_to_quadratic_surface(), ShellProblem< ELEMENT >::solve(), SegregatedFSICollapsibleChannelProblem< ELEMENT >::steady_run(), SphericalSpinUpProblem< ELEMENT >::timestep(), ElasticRingProblem< ELEMENT >::unsteady_run(), LinearWaveProblem< ELEMENT, TIMESTEPPER >::unsteady_run(), SegregatedFSICollapsibleChannelProblem< ELEMENT >::unsteady_run(), InterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run(), ElasticInterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run(), OscRingNStProblem< ELEMENT >::unsteady_run(), RayleighProblem< ELEMENT, TIMESTEPPER >::unsteady_run(), RayleighTractionProblem< ELEMENT, TIMESTEPPER >::unsteady_run(), CollapsibleChannelProblem< ELEMENT >::unsteady_run(), UnstructuredSolidProblem< ELEMENT, MESH >::UnstructuredSolidProblem(), and RefineableUnsteadyHeatProblem< ELEMENT >::write_trace_file_header().
disable_doc()
void oomph::DocInfo::disable_doc () inline
Disable documentation.
     {
       Doc_flag = false;
     }
Referenced by oomph::TreeBasedRefineableMeshBase::adapt(), oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::Problem::doc_errors(), FSIRingProblem::doc_solution(), FSIRingProblem::dynamic_run(), oomph::ErrorEstimator::get_element_errors(), oomph::Z2ErrorEstimator::get_element_errors(), main(), oomph::NonLinearElasticitySmoothMesh< ELEMENT >::operator()(), oomph::TreeBasedRefineableMeshBase::p_adapt(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::RefineableMeshBase::p_refine_uniformly(), oomph::Problem::p_refine_uniformly(), oomph::Problem::p_refine_uniformly_and_prune(), parallel_test(), oomph::Problem::read(), oomph::VorticitySmoother< ELEMENT >::recover_vorticity(), oomph::RefineableMeshBase::refine_uniformly(), oomph::RefineableQuadFromTriangleMesh< ELEMENT >::refine_uniformly(), oomph::Problem::refine_uniformly(), oomph::Problem::refine_uniformly_and_prune(), oomph::Problem::self_test(), oomph::TetMeshBase::snap_to_quadratic_surface(), and OscRingNStProblem< ELEMENT >::unsteady_run().
disable_error_if_directory_does_not_exist()
void oomph::DocInfo::disable_error_if_directory_does_not_exist () inline
Call to issue a warning if the directory does not exists.
     {
       Directory_must_exist = false;
     }
enable_doc()
void oomph::DocInfo::enable_doc () inline
Enable documentation.
     {
       Doc_flag = true;
     }
Referenced by FSIRingProblem::doc_solution(), TestPoissonProblem< ELEMENT >::doc_solution(), and OscRingNStProblem< ELEMENT >::unsteady_run().
enable_error_if_directory_does_not_exist()
void oomph::DocInfo::enable_error_if_directory_does_not_exist () inline
Call to throw an error if directory does not exist.
     {
       Directory_must_exist = true;
     }
is_doc_enabled()
bool oomph::DocInfo::is_doc_enabled () const inline
Are we documenting?
     {
       return Doc_flag;
     }
Referenced by oomph::TreeBasedRefineableMeshBase::adapt(), oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::BinaryTreeForest::check_all_neighbours(), oomph::OcTreeForest::check_all_neighbours(), oomph::QuadTreeForest::check_all_neighbours(), oomph::TreeForest::close_hanging_node_files(), oomph::Problem::doc_errors(), FSIRingProblem::doc_solution(), oomph::NonLinearElasticitySmoothMesh< ELEMENT >::doc_solution(), oomph::Z2ErrorEstimator::get_element_errors(), oomph::DummyErrorEstimator::get_element_errors(), oomph::OcTreeForest::open_hanging_node_files(), oomph::QuadTreeForest::open_hanging_node_files(), oomph::TreeBasedRefineableMeshBase::p_adapt(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::TetMeshBase::snap_to_quadratic_surface(), SegregatedFSICollapsibleChannelProblem< ELEMENT >::steady_run(), and SegregatedFSICollapsibleChannelProblem< ELEMENT >::unsteady_run().
label() [1/2]
std::string& oomph::DocInfo::label () inline
String used (e.g.) for labeling output files.
     {
       return Label;
     }
Referenced by RefineableConvectionProblem< NST_ELEMENT, AD_ELEMENT >::doc_solution(), RefineableFishPoissonProblem< ELEMENT >::doc_solution(), oomph::BiharmonicFluidProblem< DIM >::doc_solution(), oomph::TetMeshBase::snap_to_quadratic_surface(), and solve_with_incremental_adaptation().
label() [2/2]
std::string oomph::DocInfo::label () const inline
String used (e.g.) for labeling output files. Const version.
     {
       return Label;
     }
number() [1/2]
unsigned& oomph::DocInfo::number () inline
Number used (e.g.) for labeling output files.
     {
       return Number;
     }
References oomph::Global_unsigned::Number.
Referenced by NavierStokesProblem< ELEMENT >::actions_after_newton_solve(), EntryFlowProblem< ELEMENT >::actions_after_newton_solve(), FreeSurfaceRotationProblem< ELEMENT >::actions_after_newton_solve(), RefineableAdvectionDiffusionProblem< ELEMENT >::actions_before_adapt(), RefineableAdvectionDiffusionPipeProblem< ELEMENT >::actions_before_adapt(), PreconditionedFSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_convergence_check(), oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::BinaryTreeForest::check_all_neighbours(), oomph::OcTreeForest::check_all_neighbours(), oomph::QuadTreeForest::check_all_neighbours(), FourierDecomposedHelmholtzProblem< ELEMENT >::check_gamma(), ContactProblem< ELEMENT >::ContactProblem(), oomph::SolidHelpers::doc_2D_principal_stress(), DiskShockWaveProblem< ELEMENT, TIMESTEPPER >::doc_displ_and_veloc(), oomph::Z2ErrorEstimator::doc_flux(), oomph::FSI_functions::doc_fsi(), RefineableAdvectionDiffusionProblem< ELEMENT >::doc_solution(), SUPGAdvectionDiffusionProblem< ELEMENT >::doc_solution(), AxisymFvKProblem< ELEMENT >::doc_solution(), UnstructuredFvKProblem< ELEMENT >::doc_solution(), RefineableAdvectionDiffusionPipeProblem< ELEMENT >::doc_solution(), ExtrudedMovingCylinderProblem< TWO_D_ELEMENT, THREE_D_ELEMENT >::doc_solution(), MeltContactProblem< ELEMENT >::doc_solution(), SolarRadiationProblem< ELEMENT >::doc_solution(), ContactProblem< ELEMENT >::doc_solution(), UnsteadyHeatMeltProblem< ELEMENT >::doc_solution(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::doc_solution(), RefineableFishPoissonProblem< ELEMENT >::doc_solution(), GeomObjectAsGeneralisedElementProblem::doc_solution(), NavierStokesProblem< ELEMENT >::doc_solution(), UnstructuredSolidProblem< ELEMENT, MESH >::doc_solution(), PrescribedBoundaryDisplacementProblem< ELEMENT >::doc_solution(), EntryFlowProblem< ELEMENT >::doc_solution(), ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::doc_solution(), RefineableConvectionProblem< NST_ELEMENT, AD_ELEMENT >::doc_solution(), DDConvectionProblem< NST_ELEMENT, AD_ELEMENT >::doc_solution(), RefineableDDConvectionProblem< NST_ELEMENT, AD_ELEMENT >::doc_solution(), ThermalProblem< ELEMENT >::doc_solution(), PMLStructuredCubicHelmholtz< ELEMENT >::doc_solution(), PMLHelmholtzMGProblem< ELEMENT >::doc_solution(), FreeSurfaceRotationProblem< ELEMENT >::doc_solution(), SolidFreeSurfaceRotationProblem< ELEMENT >::doc_solution(), DiskShockWaveProblem< ELEMENT, TIMESTEPPER >::doc_solution(), AnnularDiskProblem< ELASTICITY_ELEMENT >::doc_solution(), RingWithTRibProblem< ELASTICITY_ELEMENT >::doc_solution(), FlowAroundCylinderProblem< ELEMENT >::doc_solution(), CompressedSquareProblem< ELEMENT >::doc_solution(), UnstructuredImmersedEllipseProblem< ELEMENT >::doc_solution(), AxisymmetricVibratingShellProblem< ELEMENT >::doc_solution(), VibratingShellProblem< ELEMENT >::doc_solution(), UnstructuredPoissonProblem< ELEMENT >::doc_solution(), RefineableUnsteadyHeatProblem< ELEMENT >::doc_solution(), TwoLayerInterfaceProblem< ELEMENT >::doc_solution(), BubbleInChannelProblem< ELEMENT >::doc_solution(), DropInChannelProblem< ELEMENT >::doc_solution(), UnstructuredFluidProblem< ELEMENT >::doc_solution(), FSIRingProblem::doc_solution(), TetmeshPoissonProblem< ELEMENT >::doc_solution(), FallingBlockProblem< ELEMENT >::doc_solution(), RisingBubbleProblem< ELEMENT >::doc_solution(), OneDPoissonProblem< ELEMENT >::doc_solution(), SheetGlueProblem< ELEMENT >::doc_solution(), TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::doc_solution(), AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::doc_solution(), CapProblem< ELEMENT >::doc_solution(), PseudoSolidCapProblem< ELEMENT >::doc_solution(), BaseStateProblem< BASE_ELEMENT >::doc_solution(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::doc_solution(), MeltSpinningProblem< ELEMENT >::doc_solution(), InterfaceProblem< ELEMENT, TIMESTEPPER >::doc_solution(), RotatingCylinderProblem< ELEMENT, TIMESTEPPER >::doc_solution(), ElasticRingProblem< ELEMENT >::doc_solution(), FourierDecomposedHelmholtzProblem< ELEMENT >::doc_solution(), UnsteadyHeatProblem< ELEMENT >::doc_solution(), StefanBoltzmannProblem< ELEMENT >::doc_solution(), HelmholtzPointSourceProblem< ELEMENT >::doc_solution(), ScatteringProblem< ELEMENT >::doc_solution(), AirwayReopeningProblem< ELEMENT >::doc_solution(), CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::doc_solution(), DeformableFishPoissonProblem< ELEMENT >::doc_solution(), SegregatedFSICollapsibleChannelProblem< ELEMENT >::doc_solution(), OscRingNStProblem< ELEMENT >::doc_solution(), PressureWaveFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution(), RectangularDrivenCavityProblem< ELEMENT >::doc_solution(), PoissonProblem< ELEMENT >::doc_solution(), MultiPoissonProblem< ELEMENT >::doc_solution(), LinearWaveProblem< ELEMENT, TIMESTEPPER >::doc_solution(), FlowPastBoxProblem< ELEMENT >::doc_solution(), MovingBlockProblem< ELEMENT >::doc_solution(), RefineableDrivenCavityProblem< ELEMENT >::doc_solution(), QuarterCircleDrivenCavityProblem< ELEMENT >::doc_solution(), PRefineableDrivenCavityProblem< ELEMENT >::doc_solution(), RefineableTwoDPoissonProblem< ELEMENT >::doc_solution(), RefineableTwoMeshFluxPoissonProblem< ELEMENT >::doc_solution(), CantileverProblem< ELEMENT >::doc_solution(), AxisymFreeSurfaceNozzleAdvDiffRobinProblem< ELEMENT >::doc_solution(), FluxPoissonMGProblem< ELEMENT, MESH >::doc_solution(), UnitCubePoissonMGProblem< ELEMENT, MESH >::doc_solution(), BrethertonProblem< ELEMENT >::doc_solution(), ChannelWithLeafletProblem< ELEMENT >::doc_solution(), QuarterCircleDrivenCavityProblem2< ELEMENT >::doc_solution(), OscEllipseProblem< ELEMENT, TIMESTEPPER >::doc_solution(), RayleighProblem< ELEMENT, TIMESTEPPER >::doc_solution(), RayleighTractionProblem< ELEMENT, TIMESTEPPER >::doc_solution(), FpTestProblem::doc_solution(), ChannelSpineFlowProblem< ELEMENT >::doc_solution(), SpikedChannelSpineFlowProblem< ELEMENT >::doc_solution(), ThreeDimBethertonProblem< ELEMENT >::doc_solution(), ElasticInterfaceProblem< ELEMENT, TIMESTEPPER >::doc_solution(), TurekNonFSIProblem< ELEMENT >::doc_solution(), RefineablePoissonProblem< ELEMENT >::doc_solution(), PMLFourierDecomposedHelmholtzProblem< ELEMENT >::doc_solution(), PMLProblem< ELEMENT >::doc_solution(), ElasticAnnulusProblem< ELASTICITY_ELEMENT >::doc_solution(), EighthSpherePoissonProblem< ELEMENT >::doc_solution(), FishPoissonProblem< ELEMENT >::doc_solution(), SimpleRefineableFishPoissonProblem< ELEMENT >::doc_solution(), RefineableOneDPoissonProblem< ELEMENT >::doc_solution(), PRefineableOneDPoissonProblem< ELEMENT >::doc_solution(), FluxPoissonProblem< ELEMENT >::doc_solution(), TwoMeshFluxPoissonProblem< ELEMENT >::doc_solution(), PolarNSProblem< ELEMENT >::doc_solution(), oomph::StreamfunctionProblem::doc_solution(), StaticDiskCompressionProblem< ELEMENT >::doc_solution(), DiskOscillationProblem< ELEMENT >::doc_solution(), SimpleShearProblem< ELEMENT >::doc_solution(), ElasticFishProblem< ELEMENT >::doc_solution(), BlockCompressionProblem< ELEMENT >::doc_solution(), TwoMeshFluxSteadyAxisymAdvectionDiffusionProblem< ELEMENT >::doc_solution(), ThreeDPoissonProblem< ELEMENT >::doc_solution(), TestPoissonProblem< ELEMENT >::doc_solution(), TestRefineablePoissonProblem< ELEMENT >::doc_solution(), oomph::NonLinearElasticitySmoothMesh< ELEMENT >::doc_solution(), oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::doc_solution(), VorticityRecoveryProblem< ELEMENT >::doc_solution(), oomph::BiharmonicProblem< DIM >::doc_solution(), FSIChannelWithLeafletProblem< ELEMENT >::doc_solution(), FSICollapsibleChannelProblem< ELEMENT >::doc_solution(), FSIDrivenCavityProblem< ELEMENT >::doc_solution(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution(), CollapsibleChannelProblem< ELEMENT >::doc_solution(), ShellProblem< ELEMENT >::doc_solution(), YoungLaplaceProblem< ELEMENT >::doc_solution(), RefineableYoungLaplaceProblem< ELEMENT >::doc_solution(), DrivenCavityProblem< ELEMENT, MESH >::doc_solution(), RefineableSphericalSpinUpProblem< ELEMENT >::doc_solution(), SphericalSpinUpProblem< ELEMENT >::doc_solution(), oomph::WomersleyProblem< ELEMENT, DIM >::doc_solution(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::doc_solution(), OscRingNStProblem< ELEMENT >::doc_solution_historic(), SegregatedFSICollapsibleChannelProblem< ELEMENT >::doc_solution_steady(), SegregatedFSICollapsibleChannelProblem< ELEMENT >::doc_solution_unsteady(), AxisymmetricVibratingShellProblem< ELEMENT >::dump_it(), VibratingShellProblem< ELEMENT >::dump_it(), RefineableUnsteadyHeatProblem< ELEMENT >::dump_it(), FSIRingProblem::dynamic_run(), ElasticCollapsibleChannelMesh< ELEMENT >::ElasticCollapsibleChannelMesh(), ElasticRefineableCollapsibleChannelMesh< ELEMENT >::ElasticRefineableCollapsibleChannelMesh(), main(), MeltContactProblem< ELEMENT >::MeltContactProblem(), oomph::OcTreeForest::open_hanging_node_files(), oomph::QuadTreeForest::open_hanging_node_files(), oomph::NonLinearElasticitySmoothMesh< ELEMENT >::operator()(), PolarNSProblem< ELEMENT >::output_streamfunction(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), CapProblem< ELEMENT >::parameter_study(), PseudoSolidCapProblem< ELEMENT >::parameter_study(), StaticDiskCompressionProblem< ELEMENT >::parameter_study(), BrethertonProblem< ELEMENT >::parameter_study(), AirwayReopeningProblem< ELEMENT >::parameter_study(), ElasticRingProblem< ELEMENT >::parameter_study(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::perform_power_method(), RefineableFishPoissonProblem< ELEMENT >::RefineableFishPoissonProblem(), RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem(), AxisymmetricVibratingShellProblem< ELEMENT >::restart(), VibratingShellProblem< ELEMENT >::restart(), RefineableUnsteadyHeatProblem< ELEMENT >::restart(), DeformableFishPoissonProblem< ELEMENT >::run(), ElasticFishProblem< ELEMENT >::run(), SheetGlueProblem< ELEMENT >::run(), SimpleShearProblem< ELEMENT >::run(), BlockCompressionProblem< ELEMENT >::run(), run(), DiskShockWaveProblem< ELEMENT, TIMESTEPPER >::run(), DiskOscillationProblem< ELEMENT >::run(), DrivenCavityProblem< ELEMENT, MESH >::run(), run_impedance_tube(), ShellProblem< ELEMENT >::run_it(), run_it(), PoissonProblem< ELEMENT >::run_it(), run_navier_stokes_outflow(), run_prescribed_flux(), run_prescribed_pressure_gradient(), run_test(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_up_periodic_base_flow(), StefanBoltzmannProblem< ELEMENT >::setup_sb_radiation(), SolarRadiationProblem< ELEMENT >::SolarRadiationProblem(), ShellProblem< ELEMENT >::solve(), solve_with_fully_automatic_adaptation(), solve_with_incremental_adaptation(), solve_with_selected_refinement_pattern(), MeltSpinningProblem< ELEMENT >::steady_run(), SegregatedFSICollapsibleChannelProblem< ELEMENT >::steady_run(), AxisymFreeSurfaceNozzleAdvDiffRobinProblem< ELEMENT >::steady_run(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::steady_run(), SphericalSpinUpProblem< ELEMENT >::timestep(), ElasticRingProblem< ELEMENT >::unsteady_run(), LinearWaveProblem< ELEMENT, TIMESTEPPER >::unsteady_run(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::unsteady_run(), SegregatedFSICollapsibleChannelProblem< ELEMENT >::unsteady_run(), RotatingCylinderProblem< ELEMENT, TIMESTEPPER >::unsteady_run(), InterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run(), ElasticInterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run(), OscRingNStProblem< ELEMENT >::unsteady_run(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::unsteady_run(), RayleighProblem< ELEMENT, TIMESTEPPER >::unsteady_run(), RayleighTractionProblem< ELEMENT, TIMESTEPPER >::unsteady_run(), CollapsibleChannelProblem< ELEMENT >::unsteady_run(), FlowAroundCylinderProblem< ELEMENT >::unsteady_simulation(), and UnsteadyHeatMeltProblem< ELEMENT >::UnsteadyHeatMeltProblem().
number() [2/2]
unsigned oomph::DocInfo::number () const inline
Number used (e.g.) for labeling output files. Const version.
     {
       return Number;
     }
References oomph::Global_unsigned::Number.
number_as_string()
std::string oomph::DocInfo::number_as_string () const inline
Get number as a string (useful to completely avoid C-strings).
     {
       return StringConversion::to_string(Number);
     }
References oomph::Global_unsigned::Number, and oomph::StringConversion::to_string().
set_directory()
void oomph::DocInfo::set_directory (const std::string & directory_)
Set output directory (we try to open a file in it to see if the directory exists – if it doesn't we'll issue a warning – or, if directory_must_exist()==true, throw and OomphLibError
Set output directory (we try to open a file in it to see if the directory exists – if it doesn't we'll issue a warning – or, if directory_must_exist()==true, die by throwing and OomphLibError
   {
     // Try to open a file in output directory
     std::ostringstream filename;
     filename << directory_ << "/.dummy_check.dat";
     std::ofstream some_file;
     some_file.open(filename.str().c_str());
     if (!some_file.is_open())
     {
       // Construct the error message
       std::string error_message = "Problem opening output file.\n";
       error_message += "I suspect you haven't created the output directory ";
       error_message += directory_;
       error_message += "\n";
       // Issue a warning if the directory does not have to exist
       if (!Directory_must_exist)
       {
         // Create an Oomph Lib warning
         OomphLibWarning(
           error_message, "set_directory()", OOMPH_EXCEPTION_LOCATION);
       }
       // Otherwise throw an error
       else
       {
         error_message += "and the Directory_must_exist flag is true.\n";
         throw OomphLibError(
           error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
     }
     // Write to the dummy file
     some_file << "Dummy file, opened to check if output directory "
               << std::endl;
     some_file << "exists. Can be deleted...." << std::endl;
     some_file.close();
     // Set directory
     Directory = directory_;
   }
References Directory, Directory_must_exist, MergeRestartFiles::filename, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
Referenced by AnnularDiskProblem< ELASTICITY_ELEMENT >::AnnularDiskProblem(), BubbleInChannelProblem< ELEMENT >::BubbleInChannelProblem(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::CoatedDiskProblem(), ContactProblem< ELEMENT >::ContactProblem(), ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::ConvectionProblem(), DDConvectionProblem< NST_ELEMENT, AD_ELEMENT >::DDConvectionProblem(), demo_smoothing_with_linear_elasticity(), demo_smoothing_with_nonlinear_elasticity(), demo_smoothing_with_poisson(), doc_sparse_node_update(), DropInChannelProblem< ELEMENT >::DropInChannelProblem(), FSIRingProblem::dynamic_run(), ElasticAnnulusProblem< ELASTICITY_ELEMENT >::ElasticAnnulusProblem(), ElasticCollapsibleChannelMesh< ELEMENT >::ElasticCollapsibleChannelMesh(), ElasticRefineableCollapsibleChannelMesh< ELEMENT >::ElasticRefineableCollapsibleChannelMesh(), GeomObjectAsGeneralisedElementProblem::GeomObjectAsGeneralisedElementProblem(), main(), MeltContactProblem< ELEMENT >::MeltContactProblem(), output_both_versions(), parallel_test(), ElasticBeamProblem::parameter_study(), CapProblem< ELEMENT >::parameter_study(), PseudoSolidCapProblem< ELEMENT >::parameter_study(), StaticDiskCompressionProblem< ELEMENT >::parameter_study(), BrethertonProblem< ELEMENT >::parameter_study(), AirwayReopeningProblem< ELEMENT >::parameter_study(), PrescribedBoundaryDisplacementProblem< ELEMENT >::PrescribedBoundaryDisplacementProblem(), RefineableAdvectionDiffusionPipeProblem< ELEMENT >::RefineableAdvectionDiffusionPipeProblem(), RefineableAdvectionDiffusionProblem< ELEMENT >::RefineableAdvectionDiffusionProblem(), RefineableConvectionProblem< NST_ELEMENT, AD_ELEMENT >::RefineableConvectionProblem(), RefineableDDConvectionProblem< NST_ELEMENT, AD_ELEMENT >::RefineableDDConvectionProblem(), RefineableFishPoissonProblem< ELEMENT >::RefineableFishPoissonProblem(), RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem(), RingWithTRibProblem< ELASTICITY_ELEMENT >::RingWithTRibProblem(), DeformableFishPoissonProblem< ELEMENT >::run(), ElasticFishProblem< ELEMENT >::run(), SheetGlueProblem< ELEMENT >::run(), SimpleShearProblem< ELEMENT >::run(), BlockCompressionProblem< ELEMENT >::run(), run(), DiskShockWaveProblem< ELEMENT, TIMESTEPPER >::run(), DiskOscillationProblem< ELEMENT >::run(), DrivenCavityProblem< ELEMENT, MESH >::run(), run_impedance_tube(), ShellProblem< ELEMENT >::run_it(), CompressedSquareProblem< ELEMENT >::run_it(), CantileverProblem< ELEMENT >::run_it(), run_it(), run_navier_stokes_outflow(), run_prescribed_flux(), run_prescribed_pressure_gradient(), run_test(), CantileverProblem< ELEMENT >::run_tests(), SolarRadiationProblem< ELEMENT >::SolarRadiationProblem(), ShellProblem< ELEMENT >::solve(), solve_with_fully_automatic_adaptation(), solve_with_incremental_adaptation(), solve_with_selected_refinement_pattern(), MeltSpinningProblem< ELEMENT >::steady_run(), SegregatedFSICollapsibleChannelProblem< ELEMENT >::steady_run(), AxisymFreeSurfaceNozzleAdvDiffRobinProblem< ELEMENT >::steady_run(), SUPGAdvectionDiffusionProblem< ELEMENT >::SUPGAdvectionDiffusionProblem(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::SurfactantProblem(), ThermalProblem< ELEMENT >::ThermalProblem(), SphericalSpinUpProblem< ELEMENT >::timestep(), TwoLayerInterfaceProblem< ELEMENT >::TwoLayerInterfaceProblem(), ElasticRingProblem< ELEMENT >::unsteady_run(), LinearWaveProblem< ELEMENT, TIMESTEPPER >::unsteady_run(), SegregatedFSICollapsibleChannelProblem< ELEMENT >::unsteady_run(), RotatingCylinderProblem< ELEMENT, TIMESTEPPER >::unsteady_run(), InterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run(), ElasticInterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run(), CollapsibleChannelProblem< ELEMENT >::unsteady_run(), UnsteadyHeatMeltProblem< ELEMENT >::UnsteadyHeatMeltProblem(), UnstructuredFluidProblem< ELEMENT >::UnstructuredFluidProblem(), UnstructuredImmersedEllipseProblem< ELEMENT >::UnstructuredImmersedEllipseProblem(), and UnstructuredSolidProblem< ELEMENT, MESH >::UnstructuredSolidProblem().
Member Data Documentation
Directory
std::string oomph::DocInfo::Directory private
Directory name.
Referenced by set_directory().
Directory_must_exist
bool oomph::DocInfo::Directory_must_exist private
Boolean flag to decide response if an output directory doesn't exist: If true, we terminate code execution by throwing an OomphLibError rather than just issuing a warning.
Referenced by set_directory().
Doc_flag
bool oomph::DocInfo::Doc_flag private
Doc or don't?
Label
std::string oomph::DocInfo::Label private
String to label output file, say.
Number
unsigned oomph::DocInfo::Number private
Number to label output file, say.
The documentation for this class was generated from the following files:
oomph_utilities.h
oomph_utilities.cc