MercuryDPM: Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device > Struct Template Reference
#include <TensorTrace.h>
Public Types
enum {
IsAligned = false , PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess , BlockAccess = false , PreferBlockAccess = TensorEvaluator<ArgType, Device>::PreferBlockAccess ,
CoordAccess = false , RawAccess = false
}
typedef TensorTraceOp< Dims, ArgType > XprType
typedef XprType::Index Index
typedef DSizes< Index, NumOutputDims > Dimensions
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorBlockNotImplemented TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
Static Public Attributes
static constexpr int NumInputDims
static constexpr int NumReducedDims = internal::array_size<Dims>::value
static constexpr int NumOutputDims = NumInputDims - NumReducedDims
static constexpr int PacketSize = internal::unpacket_traits<PacketReturnType>::size
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Protected Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index firstInput (Index index) const
Protected Attributes
Dimensions m_dimensions
TensorEvaluator< ArgType, Device > m_impl
Index m_traceDim
const Device EIGEN_DEVICE_REF m_device
array< bool, NumInputDims > m_reduced
array< Index, NumReducedDims > m_reducedDims
array< Index, NumOutputDims > m_outputStrides
array< Index, NumReducedDims > m_reducedStrides
array< Index, NumOutputDims > m_preservedStrides
Member Typedef Documentation
CoeffReturnType
template<typename Dims , typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::CoeffReturnType
Dimensions
template<typename Dims , typename ArgType , typename Device > typedef DSizes<Index, NumOutputDims> Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::Dimensions
EvaluatorPointerType
template<typename Dims , typename ArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::EvaluatorPointerType
Index
template<typename Dims , typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::Index
PacketReturnType
template<typename Dims , typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::PacketReturnType
Scalar
template<typename Dims , typename ArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::Scalar
Storage
template<typename Dims , typename ArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::Storage
TensorBlock
template<typename Dims , typename ArgType , typename Device > typedef internal::TensorBlockNotImplemented Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::TensorBlock
XprType
template<typename Dims , typename ArgType , typename Device > typedef TensorTraceOp<Dims, ArgType> Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename Dims , typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = false,
     PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess,
     BlockAccess = false,
     PreferBlockAccess = TensorEvaluator<ArgType, Device>::PreferBlockAccess,
     CoordAccess = false,
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename Dims , typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_impl(op.expression(), device), m_traceDim(1), m_device(device) {
     EIGEN_STATIC_ASSERT((NumOutputDims >= 0), YOU_MADE_A_PROGRAMMING_MISTAKE);
     EIGEN_STATIC_ASSERT((NumReducedDims >= 2) || ((NumReducedDims == 0) && (NumInputDims == 0)),
                         YOU_MADE_A_PROGRAMMING_MISTAKE);
     for (int i = 0; i < NumInputDims; ++i) {
       m_reduced[i] = false;
     }
     const Dims& op_dims = op.dims();
     for (int i = 0; i < NumReducedDims; ++i) {
       eigen_assert(op_dims[i] >= 0);
       eigen_assert(op_dims[i] < NumInputDims);
       m_reduced[op_dims[i]] = true;
     }
     // All the dimensions should be distinct to compute the trace
     int num_distinct_reduce_dims = 0;
     for (int i = 0; i < NumInputDims; ++i) {
       if (m_reduced[i]) {
         ++num_distinct_reduce_dims;
       }
     }
     EIGEN_ONLY_USED_FOR_DEBUG(num_distinct_reduce_dims);
     eigen_assert(num_distinct_reduce_dims == NumReducedDims);
     // Compute the dimensions of the result.
     const typename TensorEvaluator<ArgType, Device>::Dimensions& input_dims = m_impl.dimensions();
     int output_index = 0;
     int reduced_index = 0;
     for (int i = 0; i < NumInputDims; ++i) {
       if (m_reduced[i]) {
         m_reducedDims[reduced_index] = input_dims[i];
         if (reduced_index > 0) {
           // All the trace dimensions must have the same size
           eigen_assert(m_reducedDims[0] == m_reducedDims[reduced_index]);
         }
         ++reduced_index;
       } else {
         m_dimensions[output_index] = input_dims[i];
         ++output_index;
       }
     }
     if (NumReducedDims != 0) {
       m_traceDim = m_reducedDims[0];
     }
     // Compute the output strides
     if (NumOutputDims > 0) {
       if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
         m_outputStrides[0] = 1;
         for (int i = 1; i < NumOutputDims; ++i) {
           m_outputStrides[i] = m_outputStrides[i - 1] * m_dimensions[i - 1];
         }
       } else {
         m_outputStrides.back() = 1;
         for (int i = NumOutputDims - 2; i >= 0; --i) {
           m_outputStrides[i] = m_outputStrides[i + 1] * m_dimensions[i + 1];
         }
       }
     }
     // Compute the input strides
     if (NumInputDims > 0) {
       array<Index, NumInputDims> input_strides;
       if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
         input_strides[0] = 1;
         for (int i = 1; i < NumInputDims; ++i) {
           input_strides[i] = input_strides[i - 1] * input_dims[i - 1];
         }
       } else {
         input_strides.back() = 1;
         for (int i = NumInputDims - 2; i >= 0; --i) {
           input_strides[i] = input_strides[i + 1] * input_dims[i + 1];
         }
       }
       output_index = 0;
       reduced_index = 0;
       for (int i = 0; i < NumInputDims; ++i) {
         if (m_reduced[i]) {
           m_reducedStrides[reduced_index] = input_strides[i];
           ++reduced_index;
         } else {
           m_preservedStrides[output_index] = input_strides[i];
           ++output_index;
         }
       }
     }
   }
References Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, EIGEN_STATIC_ASSERT, i, Eigen::TensorEvaluator< Derived, Device >::Layout, and op.
Member Function Documentation
cleanup()
template<typename Dims , typename ArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::cleanup () inline
 { m_impl.cleanup(); }
Referenced by framework.Frame::__init__().
coeff()
template<typename Dims , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::coeff (Index index) const inline
{
     // Initialize the result
     CoeffReturnType result = internal::cast<int, CoeffReturnType>(0);
     Index index_stride = 0;
     for (int i = 0; i < NumReducedDims; ++i) {
       index_stride += m_reducedStrides[i];
     }
     // If trace is requested along all dimensions, starting index would be 0
     Index cur_index = 0;
     if (NumOutputDims != 0) cur_index = firstInput(index);
     for (Index i = 0; i < m_traceDim; ++i) {
       result += m_impl.coeff(cur_index);
       cur_index += index_stride;
     }
     return result;
   }
References i.
dimensions()
template<typename Dims , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::dimensions () const inline
 { return m_dimensions; }
evalSubExprsIfNeeded()
template<typename Dims , typename ArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
{
     m_impl.evalSubExprsIfNeeded(NULL);
     return true;
   }
firstInput()
template<typename Dims , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::firstInput (Index index) const inline protected
{
     Index startInput = 0;
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       for (int i = NumOutputDims - 1; i > 0; --i) {
         const Index idx = index / m_outputStrides[i];
         startInput += idx * m_preservedStrides[i];
         index -= idx * m_outputStrides[i];
       }
       startInput += index * m_preservedStrides[0];
     } else {
       for (int i = 0; i < NumOutputDims - 1; ++i) {
         const Index idx = index / m_outputStrides[i];
         startInput += idx * m_preservedStrides[i];
         index -= idx * m_outputStrides[i];
       }
       startInput += index * m_preservedStrides[NumOutputDims - 1];
     }
     return startInput;
   }
References Eigen::ColMajor, i, and Eigen::TensorEvaluator< Derived, Device >::Layout.
packet()
template<typename Dims , typename ArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::packet (Index index) const inline
{
     eigen_assert(index + PacketSize - 1 < dimensions().TotalSize());
     EIGEN_ALIGN_MAX std::remove_const_t<CoeffReturnType> values[PacketSize];
     for (int i = 0; i < PacketSize; ++i) {
       values[i] = coeff(index + i);
     }
     PacketReturnType result = internal::ploadt<PacketReturnType, LoadMode>(values);
     return result;
   }
References Eigen::TensorEvaluator< Derived, Device >::coeff(), Eigen::TensorEvaluator< Derived, Device >::dimensions(), EIGEN_ALIGN_MAX, eigen_assert, i, and Eigen::TensorEvaluator< Derived, Device >::PacketSize.
Member Data Documentation
Layout
template<typename Dims , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_device
template<typename Dims , typename ArgType , typename Device > const Device EIGEN_DEVICE_REF Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::m_device protected
m_dimensions
template<typename Dims , typename ArgType , typename Device > Dimensions Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::m_dimensions protected
m_impl
template<typename Dims , typename ArgType , typename Device > TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::m_impl protected
m_outputStrides
template<typename Dims , typename ArgType , typename Device > array<Index, NumOutputDims> Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::m_outputStrides protected
m_preservedStrides
template<typename Dims , typename ArgType , typename Device > array<Index, NumOutputDims> Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::m_preservedStrides protected
m_reduced
template<typename Dims , typename ArgType , typename Device > array<bool, NumInputDims> Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::m_reduced protected
m_reducedDims
template<typename Dims , typename ArgType , typename Device > array<Index, NumReducedDims> Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::m_reducedDims protected
m_reducedStrides
template<typename Dims , typename ArgType , typename Device > array<Index, NumReducedDims> Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::m_reducedStrides protected
m_traceDim
template<typename Dims , typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::m_traceDim protected
NumInputDims
template<typename Dims , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::NumInputDims static constexpr
Initial value:
=
      internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value
NumOutputDims
template<typename Dims , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::NumOutputDims = NumInputDims - NumReducedDims static constexpr
NumReducedDims
template<typename Dims , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::NumReducedDims = internal::array_size<Dims>::value static constexpr
PacketSize
template<typename Dims , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::PacketSize = internal::unpacket_traits<PacketReturnType>::size static constexpr
The documentation for this struct was generated from the following file:
TensorTrace.h