MercuryDPM: Eigen::internal::SparseTransposeImpl< MatrixType, CompressedAccessBit > Class Template Reference
Eigen::internal::SparseTransposeImpl< MatrixType, CompressedAccessBit > Class Template Reference
#include <SparseTranspose.h>
Public Types
typedef Base::Scalar Scalar
typedef Base::StorageIndex StorageIndex
Public Types inherited from Eigen::SparseCompressedBase< Transpose< MatrixType > >
typedef SparseMatrixBase< Transpose< MatrixType > > Base
Public Types inherited from Eigen::SparseMatrixBase< Transpose< MatrixType > >
enum
typedef internal::traits< Transpose< MatrixType > >::Scalar Scalar
typedef Scalar value_type
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef internal::traits< Transpose< MatrixType > >::StorageKind StorageKind
typedef internal::traits< Transpose< MatrixType > >::StorageIndex StorageIndex
typedef internal::add_const_on_value_type_if_arithmetic< typename internal::packet_traits< Scalar >::type >::type PacketReturnType
typedef SparseMatrixBase StorageBaseType
typedef Matrix< StorageIndex, Dynamic, 1 > IndexVector
typedef Matrix< Scalar, Dynamic, 1 > ScalarVector
typedef std::conditional_t< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, Eigen::Transpose< const Transpose< MatrixType > > >, Transpose< const Transpose< MatrixType > > > AdjointReturnType
typedef Transpose< Transpose< MatrixType > > TransposeReturnType
typedef Transpose< const Transpose< MatrixType > > ConstTransposeReturnType
typedef SparseMatrix< Scalar, Flags &RowMajorBit ? RowMajor :ColMajor, StorageIndex > PlainObject
typedef NumTraits< Scalar >::Real RealScalar
typedef std::conditional_t< HasDirectAccess_, const Scalar &, Scalar > CoeffReturnType
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, Matrix< Scalar, Dynamic, Dynamic > > ConstantReturnType
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime > DenseMatrixType
typedef Matrix< Scalar, internal::max_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime), internal::max_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime)> SquareMatrixType
typedef EigenBase< Transpose< MatrixType > > Base
Public Types inherited from Eigen::EigenBase< Transpose< MatrixType > >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Transpose< MatrixType > >::StorageKind StorageKind
Public Member Functions
Index nonZeros () const
const Scalar * valuePtr () const
const StorageIndex * innerIndexPtr () const
const StorageIndex * outerIndexPtr () const
const StorageIndex * innerNonZeroPtr () const
Scalar * valuePtr ()
StorageIndex * innerIndexPtr ()
StorageIndex * outerIndexPtr ()
StorageIndex * innerNonZeroPtr ()
Public Member Functions inherited from Eigen::SparseCompressedBase< Transpose< MatrixType > >
Index nonZeros () const
const Scalar * valuePtr () const
Scalar * valuePtr ()
const StorageIndex * innerIndexPtr () const
StorageIndex * innerIndexPtr ()
const StorageIndex * outerIndexPtr () const
StorageIndex * outerIndexPtr ()
const StorageIndex * innerNonZeroPtr () const
StorageIndex * innerNonZeroPtr ()
bool isCompressed () const
const Map< const Array< Scalar, Dynamic, 1 > > coeffs () const
Map< Array< Scalar, Dynamic, 1 > > coeffs ()
void sortInnerIndices (Index begin, Index end)
void sortInnerIndices ()
Index innerIndicesAreSorted (Index begin, Index end) const
Index innerIndicesAreSorted () const
Transpose< MatrixType > & operator= (const EigenBase< OtherDerived > &other)
Transpose< MatrixType > & operator= (const ReturnByValue< OtherDerived > &other)
Transpose< MatrixType > & operator= (const SparseMatrixBase< OtherDerived > &other)
Transpose< MatrixType > & operator= (const Transpose< MatrixType > &other)
Public Member Functions inherited from Eigen::SparseMatrixBase< Transpose< MatrixType > >
Transpose< MatrixType > & operator= (const EigenBase< OtherDerived > &other)
Transpose< MatrixType > & operator= (const ReturnByValue< OtherDerived > &other)
Transpose< MatrixType > & operator= (const SparseMatrixBase< OtherDerived > &other)
Transpose< MatrixType > & operator= (const Transpose< MatrixType > &other)
const Transpose< MatrixType > & derived () const
Transpose< MatrixType > & derived ()
Transpose< MatrixType > & const_cast_derived () const
Index rows () const
Index cols () const
Index size () const
bool isVector () const
Index outerSize () const
Index innerSize () const
bool isRValue () const
Transpose< MatrixType > & markAsRValue ()
SparseMatrixBase ()
Transpose< MatrixType > & operator+= (const SparseMatrixBase< OtherDerived > &other)
Transpose< MatrixType > & operator+= (const DiagonalBase< OtherDerived > &other)
Transpose< MatrixType > & operator+= (const EigenBase< OtherDerived > &other)
EIGEN_STRONG_INLINE Transpose< MatrixType > & operator+= (const SparseMatrixBase< OtherDerived > &other)
Transpose< MatrixType > & operator-= (const SparseMatrixBase< OtherDerived > &other)
Transpose< MatrixType > & operator-= (const DiagonalBase< OtherDerived > &other)
Transpose< MatrixType > & operator-= (const EigenBase< OtherDerived > &other)
EIGEN_STRONG_INLINE Transpose< MatrixType > & operator-= (const SparseMatrixBase< OtherDerived > &other)
Transpose< MatrixType > & operator*= (const Scalar &other)
Transpose< MatrixType > & operator*= (const SparseMatrixBase< OtherDerived > &other)
Transpose< MatrixType > & operator/= (const Scalar &other)
EIGEN_STRONG_INLINE const CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
EIGEN_STRONG_INLINE const SparseMatrixBase< Transpose< MatrixType > >::template CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
const Product< Transpose< MatrixType >, OtherDerived > operator* (const DiagonalBase< OtherDerived > &other) const
const Product< Transpose< MatrixType >, OtherDerived, AliasFreeProduct > operator* (const SparseMatrixBase< OtherDerived > &other) const
const Product< Transpose< MatrixType >, OtherDerived > operator* (const MatrixBase< OtherDerived > &other) const
SparseSymmetricPermutationProduct< Transpose< MatrixType >, Upper|Lower > twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > &perm) const
const TriangularView< const Transpose< MatrixType >, Mode > triangularView () const
ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
SparseMatrixBase< Transpose< MatrixType > >::template ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
SparseMatrixBase< Transpose< MatrixType > >::template SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
Scalar dot (const MatrixBase< OtherDerived > &other) const
Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
internal::traits< Transpose< MatrixType > >::Scalar dot (const MatrixBase< OtherDerived > &other) const
internal::traits< Transpose< MatrixType > >::Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
RealScalar squaredNorm () const
RealScalar norm () const
RealScalar blueNorm () const
TransposeReturnType transpose ()
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
DenseMatrixType toDense () const
bool isApprox (const SparseMatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isApprox (const MatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
const internal::eval< Transpose< MatrixType > >::type eval () const
Scalar sum () const
const SparseView< Transpose< MatrixType > > pruned (const Scalar &reference=Scalar(0), const RealScalar &epsilon=NumTraits< Scalar >::dummy_precision()) const
Public Member Functions inherited from Eigen::EigenBase< Transpose< MatrixType > >
constexpr EIGEN_DEVICE_FUNC Transpose< MatrixType > & derived ()
constexpr EIGEN_DEVICE_FUNC const Transpose< MatrixType > & derived () const
EIGEN_DEVICE_FUNC Transpose< MatrixType > & const_cast_derived () const
EIGEN_DEVICE_FUNC const Transpose< MatrixType > & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< Transpose< MatrixType >, Device > device (Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const Transpose< MatrixType >, Device > device (Device &device) const
Private Types
typedef SparseCompressedBase< Transpose< MatrixType > > Base
Additional Inherited Members
Protected Types inherited from Eigen::SparseCompressedBase< Transpose< MatrixType > >
typedef Base::IndexVector IndexVector
Protected Member Functions inherited from Eigen::SparseCompressedBase< Transpose< MatrixType > >
Eigen::Map< IndexVector > innerNonZeros ()
const Eigen::Map< const IndexVector > innerNonZeros () const
SparseCompressedBase ()
internal::LowerBoundIndex lower_bound (Index row, Index col) const
Protected Member Functions inherited from Eigen::SparseMatrixBase< Transpose< MatrixType > >
Transpose< MatrixType > & assign (const OtherDerived &other)
void assignGeneric (const OtherDerived &other)
Static Protected Member Functions inherited from Eigen::SparseMatrixBase< Transpose< MatrixType > >
static StorageIndex convert_index (const Index idx)
Protected Attributes inherited from Eigen::SparseMatrixBase< Transpose< MatrixType > >
bool m_isRValue
Member Typedef Documentation
Base
template<typename MatrixType > typedef SparseCompressedBase<Transpose<MatrixType> > Eigen::internal::SparseTransposeImpl< MatrixType, CompressedAccessBit >::Base private
Scalar
template<typename MatrixType > typedef Base::Scalar Eigen::internal::SparseTransposeImpl< MatrixType, CompressedAccessBit >::Scalar
StorageIndex
template<typename MatrixType > typedef Base::StorageIndex Eigen::internal::SparseTransposeImpl< MatrixType, CompressedAccessBit >::StorageIndex
Member Function Documentation
innerIndexPtr() [1/2]
template<typename MatrixType > StorageIndex* Eigen::internal::SparseTransposeImpl< MatrixType, CompressedAccessBit >::innerIndexPtr () inline
 { return derived().nestedExpression().innerIndexPtr(); }
References Eigen::SparseMatrixBase< Transpose< MatrixType > >::derived().
innerIndexPtr() [2/2]
template<typename MatrixType > const StorageIndex* Eigen::internal::SparseTransposeImpl< MatrixType, CompressedAccessBit >::innerIndexPtr () const inline
 { return derived().nestedExpression().innerIndexPtr(); }
References Eigen::SparseMatrixBase< Transpose< MatrixType > >::derived().
innerNonZeroPtr() [1/2]
template<typename MatrixType > StorageIndex* Eigen::internal::SparseTransposeImpl< MatrixType, CompressedAccessBit >::innerNonZeroPtr () inline
 { return derived().nestedExpression().innerNonZeroPtr(); }
References Eigen::SparseMatrixBase< Transpose< MatrixType > >::derived().
innerNonZeroPtr() [2/2]
template<typename MatrixType > const StorageIndex* Eigen::internal::SparseTransposeImpl< MatrixType, CompressedAccessBit >::innerNonZeroPtr () const inline
 { return derived().nestedExpression().innerNonZeroPtr(); }
References Eigen::SparseMatrixBase< Transpose< MatrixType > >::derived().
nonZeros()
template<typename MatrixType > Index Eigen::internal::SparseTransposeImpl< MatrixType, CompressedAccessBit >::nonZeros () const inline
 { return derived().nestedExpression().nonZeros(); }
References Eigen::SparseMatrixBase< Transpose< MatrixType > >::derived().
outerIndexPtr() [1/2]
template<typename MatrixType > StorageIndex* Eigen::internal::SparseTransposeImpl< MatrixType, CompressedAccessBit >::outerIndexPtr () inline
 { return derived().nestedExpression().outerIndexPtr(); }
References Eigen::SparseMatrixBase< Transpose< MatrixType > >::derived().
outerIndexPtr() [2/2]
template<typename MatrixType > const StorageIndex* Eigen::internal::SparseTransposeImpl< MatrixType, CompressedAccessBit >::outerIndexPtr () const inline
 { return derived().nestedExpression().outerIndexPtr(); }
References Eigen::SparseMatrixBase< Transpose< MatrixType > >::derived().
valuePtr() [1/2]
template<typename MatrixType > Scalar* Eigen::internal::SparseTransposeImpl< MatrixType, CompressedAccessBit >::valuePtr () inline
 { return derived().nestedExpression().valuePtr(); }
References Eigen::SparseMatrixBase< Transpose< MatrixType > >::derived().
valuePtr() [2/2]
template<typename MatrixType > const Scalar* Eigen::internal::SparseTransposeImpl< MatrixType, CompressedAccessBit >::valuePtr () const inline
 { return derived().nestedExpression().valuePtr(); }
References Eigen::SparseMatrixBase< Transpose< MatrixType > >::derived().
The documentation for this class was generated from the following file:
SparseTranspose.h