MercuryDPM: HertzianViscoelasticNormalSpecies Class Reference
HertzianViscoelasticNormalSpecies Class Reference
HertzianViscoelasticNormalSpecies contains the parameters used to describe a Hertzian normal force (The Mindlin model).
#include <HertzianViscoelasticNormalSpecies.h>
Public Types
typedef HertzianViscoelasticInteraction InteractionType
The correct Interaction type for this FrictionForceSpecies.
Public Member Functions
HertzianViscoelasticNormalSpecies ()
The default constructor.
HertzianViscoelasticNormalSpecies (const HertzianViscoelasticNormalSpecies &p)
The default copy constructor.
~HertzianViscoelasticNormalSpecies ()
The default destructor.
void read (std::istream &is)
Reads the species properties from an input stream.
void write (std::ostream &os) const
Writes the species properties to an output stream.
virtual std::string getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
Mdouble getCollisionTime (Mdouble particleDiameter, Mdouble particleDensity, Mdouble relativeVelocity) const
Used in Species::getName to obtain a unique name for each Species.
Public Member Functions inherited from BaseNormalForce
BaseNormalForce ()
BaseNormalForce (const BaseNormalForce &p)
bool getConstantRestitution () const
void setConstantRestitution (bool constantRestitution)
virtual void actionsAfterTimeStep (BaseParticle *particle) const
Public Member Functions inherited from BaseForce
BaseSpecies * getBaseSpecies () const
void setBaseSpecies (BaseSpecies *baseSpecies)
Detailed Description
HertzianViscoelasticNormalSpecies contains the parameters used to describe a Hertzian normal force (The Mindlin model).
See HertzianViscoelasticNormalInteraction::computeForce for a description of the force law.
Member Typedef Documentation
InteractionType
typedef HertzianViscoelasticInteraction HertzianViscoelasticNormalSpecies::InteractionType
The correct Interaction type for this FrictionForceSpecies.
Constructor & Destructor Documentation
HertzianViscoelasticNormalSpecies() [1/2]
HertzianViscoelasticNormalSpecies::HertzianViscoelasticNormalSpecies ()
The default constructor.
         : BaseNormalForce()
 {
     elasticModulus_ = 0;
     dissipation_ = 0;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"HertzianViscoelasticNormalSpecies::HertzianViscoelasticNormalSpecies() finished"<<std::endl;
 #endif
 }
HertzianViscoelasticNormalSpecies() [2/2]
HertzianViscoelasticNormalSpecies::HertzianViscoelasticNormalSpecies (const HertzianViscoelasticNormalSpecies & p)
The default copy constructor.
Parameters
[in] the species that is copied
         : BaseNormalForce(p)
 {
     elasticModulus_ = p.elasticModulus_;
     dissipation_ = p.dissipation_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"HertzianViscoelasticNormalSpecies::HertzianViscoelasticNormalSpecies(const HertzianViscoelasticNormalSpecies &p) finished"<<std::endl;
 #endif
 }
References p.
~HertzianViscoelasticNormalSpecies()
HertzianViscoelasticNormalSpecies::~HertzianViscoelasticNormalSpecies ()
The default destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"HertzianViscoelasticNormalSpecies::~HertzianViscoelasticNormalSpecies() finished"<<std::endl;
 #endif
 }
Member Function Documentation
getBaseName()
std::string HertzianViscoelasticNormalSpecies::getBaseName () const virtual
Used in Species::getName to obtain a unique name for each Species.
Returns
a string containing the name of the species (minus the word "Species")
Reimplemented in HertzianBSHPViscoelasticNormalSpecies.
 {
     return "HertzianViscoelastic";
 }
getCollisionTime()
Mdouble HertzianViscoelasticNormalSpecies::getCollisionTime (Mdouble particleDiameter, Mdouble particleDensity, Mdouble relativeVelocity) const
Used in Species::getName to obtain a unique name for each Species.
Parameters
[in] relativeVelocity input the maximum relative velocity in your system to get the mininimum collision time
[in] particleDiameter input the minimum particle diameter in your system to get the mininimum collision time
[in] particleDensity input the minimum particle density in your system to get the mininimum collision time
 {
     // Here is a very nice paper describing contact modelling
     //https://iopscience.iop.org/article/10.1209/0295-5075/94/50004 (Antypov_Elliott_EPL_2011)
     //caution: this function assumes the contact is elastic (no dissipation)
     //Mdouble omega0 = 2.0/constants::sqrt_pi*sqrt(getEffectiveElasticModulus()/particleDensity)/relativeVelocity;
     //Mdouble omega1 = sqrt(omega0*omega0-getDissipation()*getDissipation());
     return 2.214 * pow(mathsFunc::square(particleDensity / getEffectiveElasticModulus()) / relativeVelocity, 0.2) *
            particleDiameter;
 }
References Eigen::bfloat16_impl::pow(), and mathsFunc::square().
read()
void HertzianViscoelasticNormalSpecies::read (std::istream & is)
Reads the species properties from an input stream.
Parameters
[in] input stream (typically the restart file)
 {
     std::string dummy;
     is >> dummy >> elasticModulus_
        >> dummy >> dissipation_;
 }
References oomph::Global_string_for_annotation::string().
write()
void HertzianViscoelasticNormalSpecies::write (std::ostream & os) const
Writes the species properties to an output stream.
Parameters
[out] output stream (typically the restart file)
 {
     os << " elasticModulus " << elasticModulus_
        << " dissipation " << dissipation_;
 }
The documentation for this class was generated from the following files:
HertzianViscoelasticNormalSpecies.h
HertzianViscoelasticNormalSpecies.cc