MercuryDPM: Eigen::internal::IndexedViewHelper< AllRange< SizeAtCompileTime_ >, void > Struct Template Reference
Eigen::internal::IndexedViewHelper< AllRange< SizeAtCompileTime_ >, void > Struct Template Reference
#include <IndexedViewHelper.h>
Public Types
using Indices = AllRange< SizeAtCompileTime_ >
Static Public Member Functions
static Index first (const Indices &indices)
static Index size (const Indices &indices)
static Index incr (const Indices &indices)
Static Public Attributes
static constexpr Index FirstAtCompileTime = Indices::FirstAtCompileTime
static constexpr Index SizeAtCompileTime = Indices::SizeAtCompileTime
static constexpr Index IncrAtCompileTime = Indices::IncrAtCompileTime
Member Typedef Documentation
Indices
template<Index SizeAtCompileTime_> using Eigen::internal::IndexedViewHelper< AllRange< SizeAtCompileTime_ >, void >::Indices = AllRange<SizeAtCompileTime_>
Member Function Documentation
first()
template<Index SizeAtCompileTime_> static Index Eigen::internal::IndexedViewHelper< AllRange< SizeAtCompileTime_ >, void >::first (const Indices & indices) inline static
 { return indices.first(); }
References Eigen::internal::AllRange< SizeAtCompileTime_ >::first().
incr()
template<Index SizeAtCompileTime_> static Index Eigen::internal::IndexedViewHelper< AllRange< SizeAtCompileTime_ >, void >::incr (const Indices & indices) inline static
 { return indices.incr(); }
References Eigen::internal::AllRange< SizeAtCompileTime_ >::incr().
size()
template<Index SizeAtCompileTime_> static Index Eigen::internal::IndexedViewHelper< AllRange< SizeAtCompileTime_ >, void >::size (const Indices & indices) inline static
 { return indices.size(); }
References Eigen::internal::AllRange< SizeAtCompileTime_ >::size().
Member Data Documentation
FirstAtCompileTime
template<Index SizeAtCompileTime_> constexpr Index Eigen::internal::IndexedViewHelper< AllRange< SizeAtCompileTime_ >, void >::FirstAtCompileTime = Indices::FirstAtCompileTime static constexpr
IncrAtCompileTime
template<Index SizeAtCompileTime_> constexpr Index Eigen::internal::IndexedViewHelper< AllRange< SizeAtCompileTime_ >, void >::IncrAtCompileTime = Indices::IncrAtCompileTime static constexpr
SizeAtCompileTime
template<Index SizeAtCompileTime_> constexpr Index Eigen::internal::IndexedViewHelper< AllRange< SizeAtCompileTime_ >, void >::SizeAtCompileTime = Indices::SizeAtCompileTime static constexpr
The documentation for this struct was generated from the following file:
IndexedViewHelper.h