MercuryDPM: oomph::deriv_functions Namespace Reference
oomph::deriv_functions Namespace Reference
Classes
class DampedOscillation
A damped oscillation solution.
class SimpleStiffTest
Another stiff solution: Atkinson equation (8.1) pg 128.
class OrderReductionTest
Another stiff solution: Atkinson pg. 158, also example 8.2 pg 129.
Functions
Vector< double > cos (const double &time, const Vector< double > &x)
Vector< double > dcos (const double &t, const Vector< double > &x, const Vector< double > &u)
Vector< double > sin (const double &time, const Vector< double > &x)
Vector< double > dsin (const double &t, const Vector< double > &x, const Vector< double > &u)
Vector< double > exp (const double &time, const Vector< double > &x)
Vector< double > dexp (const double &t, const Vector< double > &x, const Vector< double > &u)
Vector< double > poly2 (const double &time, const Vector< double > &x)
Vector< double > dpoly2 (const double &t, const Vector< double > &x, const Vector< double > &u)
Vector< double > poly3 (const double &time, const Vector< double > &x)
Vector< double > dpoly3 (const double &t, const Vector< double > &x, const Vector< double > &u)
Vector< double > stiff_test (const double &time, const Vector< double > &x)
Vector< double > dstiff_test (const double &t, const Vector< double > &x, const Vector< double > &u)
Function Documentation
cos()
Vector<double> oomph::deriv_functions::cos (const double & time, const Vector< double > & x) inline
   {
    Vector<double> values(1);
    values[0] = std::cos(time);
    return values;
   }
References cos().
Referenced by oomph::ODEFactories::exact_solutions_factory().
dcos()
Vector<double> oomph::deriv_functions::dcos (const double & t, const Vector< double > & x, const Vector< double > & u) inline
   {
    Vector<double> deriv(1, 0.0);
    deriv[0] = -1*std::sin(t);
    return deriv;
   }
References sin(), and plotPSD::t.
Referenced by oomph::ODEFactories::exact_solutions_factory().
dexp()
Vector<double> oomph::deriv_functions::dexp (const double & t, const Vector< double > & x, const Vector< double > & u) inline
   {
    Vector<double> deriv(1, 0.0);
    deriv[0] = u[0];
    return deriv;
   }
Referenced by oomph::ODEFactories::exact_solutions_factory().
dpoly2()
Vector<double> oomph::deriv_functions::dpoly2 (const double & t, const Vector< double > & x, const Vector< double > & u) inline
   {
    double b1 = 0, b2 = 1;
    Vector<double> deriv(1, 0.0);
    deriv[0] = 2*t*b2 + b1;
    return deriv;
   }
References plotPSD::t.
Referenced by oomph::ODEFactories::exact_solutions_factory().
dpoly3()
Vector<double> oomph::deriv_functions::dpoly3 (const double & t, const Vector< double > & x, const Vector< double > & u) inline
   {
    double a1 = 0, a2 = 0, a3 = 1;
    Vector<double> deriv(1, 0.0);
    deriv[0] = 3*t*t*a3 + 2*t*a2 + a1;
    return deriv;
   }
References plotPSD::t.
Referenced by oomph::ODEFactories::exact_solutions_factory().
dsin()
Vector<double> oomph::deriv_functions::dsin (const double & t, const Vector< double > & x, const Vector< double > & u) inline
   {
    Vector<double> deriv(1, 0.0);
    deriv[0] = std::cos(t);
    return deriv;
   }
References cos(), and plotPSD::t.
Referenced by oomph::ODEFactories::exact_solutions_factory().
dstiff_test()
Vector<double> oomph::deriv_functions::dstiff_test (const double & t, const Vector< double > & x, const Vector< double > & u) inline
   {
    Vector<double> deriv(2, 0.0);
    deriv[0] = -100*u[0] + u[1];
    deriv[1] = 0*u[0] - 0.1*u[1];
    return deriv;
   }
Referenced by oomph::ODEFactories::exact_solutions_factory().
exp()
Vector<double> oomph::deriv_functions::exp (const double & time, const Vector< double > & x) inline
   {
    Vector<double> values(1);
    values[0] = std::exp(time);
    return values;
   }
Referenced by oomph::deriv_functions::DampedOscillation::derivative(), oomph::ODEFactories::exact_solutions_factory(), oomph::deriv_functions::DampedOscillation::operator()(), oomph::deriv_functions::SimpleStiffTest::operator()(), and stiff_test().
poly2()
Vector<double> oomph::deriv_functions::poly2 (const double & time, const Vector< double > & x) inline
   {
    double b0 = 0.5, b1 = 0, b2 = 1;
    Vector<double> values(1);
    values[0] =  b2*time*time + b1*time +b0;
    return values;
   }
Referenced by oomph::ODEFactories::exact_solutions_factory().
poly3()
Vector<double> oomph::deriv_functions::poly3 (const double & time, const Vector< double > & x) inline
   {
    double a0 = 0.5, a1 = 0, a2 = 0, a3 = 1;
    Vector<double> values(1);
    values[0] = a3*time*time*time + a2*time*time + a1*time +a0;
    return values;
   }
Referenced by oomph::ODEFactories::exact_solutions_factory().
sin()
Vector<double> oomph::deriv_functions::sin (const double & time, const Vector< double > & x) inline
   {
    Vector<double> values(1);
    values[0] = std::sin(time);
    return values;
   }
References sin().
Referenced by oomph::ODEFactories::exact_solutions_factory().
stiff_test()
Vector<double> oomph::deriv_functions::stiff_test (const double & time, const Vector< double > & x) inline
   {
    Vector<double> x1(2), x2(2);
    x1[0] = 0; x1[1] = 0;
    x2[0] = 1.0; x2[1] = 999.0/10;
    Vector<double> values(2);
    values[0] = std::exp(-100*time)*x1[0] + std::exp(-0.1*time)*x2[0];
    values[1] = std::exp(-100*time)*x1[1] + std::exp(-0.1*time)*x2[1];
    return values;
   }
References exp(), Global_parameters::x1(), and Global_parameters::x2().
Referenced by oomph::ODEFactories::exact_solutions_factory().