MercuryDPM: CGCoordinates::Y Class Reference
CGCoordinates::Y Class Reference
Defines the non-averaged directions on which spatial coarse-graining is applied (the y- direction for Y); all other directions are averaged
over homogeneously.
#include <Y.h>
Public Member Functions
void write (std::ostream &os) const
Writes the coordinates in human-readable form to an ostream.
Mdouble getDistanceSquared (const Vec3D &p) const
Returns the square of the distance between the particle p and the current CGPoint, in the non-averaged directions.
void setY (Mdouble x)
Returns the position of the current CGPoint, in the non-averaged directions.
Mdouble getINormal (const BaseInteraction &c, const Vec3D &normal) const
For the Interaction between particles/walls P and I, this function returns the dot product between the normal vector of the interaction and the branch vector from the current CGPoint towards I.
Mdouble getPNormal (const BaseInteraction &c, const Vec3D &normal) const
For the Interaction between particles/walls P and I, this function returns the dot product between the normal vector of the interaction and the branch vector from the current CGPoint towards P.
Mdouble getCNormal (const BaseInteraction &c, const Vec3D &normal) const
For the Interaction between particles/walls P and I, this function returns the dot product between the normal vector of the interaction and the branch vector from the current CGPoint towards the contact point.
Public Member Functions inherited from CGCoordinates::BaseCoordinates
virtual Mdouble getWeight ()
Static Public Member Functions
static void writeNames (std::ostream &os)
Writes the coordinate names in human-readable form to an ostream.
static Mdouble getVolumeOfAveragedDimensions (const Vec3D &min, const Vec3D &max)
returns the factor the CGFunction has to be divided by, due to integrating the variables over the averaged dimensions, 1.0 for XYZ.
static Mdouble getLength (const Vec3D &p)
Returns the length of the input vector in the non-averaged directions.
static bool isResolvedIn (unsigned i)
static std::string getName ()
Static Public Member Functions inherited from CGCoordinates::Base_X_Y_Z
static Mdouble getGaussPrefactor (Mdouble width, Mdouble cutoff)
Computes the prefactor of the Gauss CGFunction, which is dependent on the number of non-averaged dimensions.
static Mdouble getGaussIntegralPrefactor (Mdouble distance, Mdouble width, Mdouble cutoff)
Computes the prefactor of the Gauss line integral, which is dependent on the number of non-averaged dimensions.
static void normalisePolynomialCoefficients (std::vector< Mdouble > &coefficients, Mdouble cutoff)
Normalises the coefficients of Polynomial CGFunction such that the integral over all non-averaged dimensions is unity.
static const unsigned countVariables ()
Static Public Member Functions inherited from CGCoordinates::BaseCoordinates
static Mdouble getDomainVolume (const Vec3D &min, const Vec3D &max)
Protected Attributes
Mdouble y_
Detailed Description
Defines the non-averaged directions on which spatial coarse-graining is applied (the y- direction for Y); all other directions are averaged
over homogeneously.
See XYZ for details.
Member Function Documentation
getCNormal()
Mdouble Y::getCNormal (const BaseInteraction & c, const Vec3D & normal) const
For the Interaction between particles/walls P and I, this function returns the dot product between the normal vector of the interaction and the branch vector from the current CGPoint towards the contact point.
 {
     return (c.getContactPoint().Y - y_) * normal.Y;
 }
References calibrate::c, WallFunction::normal(), and y_.
getDistanceSquared()
Mdouble Y::getDistanceSquared (const Vec3D & p) const
Returns the square of the distance between the particle p and the current CGPoint, in the non-averaged directions.
 {
     return mathsFunc::square(p.Y - y_);
 }
References p, mathsFunc::square(), and y_.
getINormal()
Mdouble Y::getINormal (const BaseInteraction & c, const Vec3D & normal) const
For the Interaction between particles/walls P and I, this function returns the dot product between the normal vector of the interaction and the branch vector from the current CGPoint towards I.
 {
     return (c.getI()->getPosition().Y - y_) * normal.Y;
 }
References calibrate::c, WallFunction::normal(), and y_.
getLength()
Mdouble Y::getLength (const Vec3D & p) static
Returns the length of the input vector in the non-averaged directions.
Parameters
[in] p vector whose length should be determined
Returns
length of the vector in the non-averaged directions
Todo:
 {
     return fabs(p.Y);
 }
References boost::multiprecision::fabs(), and p.
getName()
std::string Y::getName () static
 {
     return "Y";
 }
getPNormal()
Mdouble Y::getPNormal (const BaseInteraction & c, const Vec3D & normal) const
For the Interaction between particles/walls P and I, this function returns the dot product between the normal vector of the interaction and the branch vector from the current CGPoint towards P.
 {
     return (c.getP()->getPosition().Y - y_) * normal.Y;
 }
References calibrate::c, WallFunction::normal(), and y_.
getVolumeOfAveragedDimensions()
Mdouble Y::getVolumeOfAveragedDimensions (const Vec3D & min, const Vec3D & max) static
returns the factor the CGFunction has to be divided by, due to integrating the variables over the averaged dimensions, 1.0 for XYZ.
Todo:
Generalise to 2D
 {
     return (max.X - min.X) * (max.Z - min.Z);
 }
References max, and min.
isResolvedIn()
static bool CGCoordinates::Y::isResolvedIn (unsigned i) inline static
 {return i==1?true:false;}
References i.
setY()
void Y::setY (Mdouble x)
Returns the position of the current CGPoint, in the non-averaged directions.
 {
     y_ = y;
 }
References y, and y_.
write()
void Y::write (std::ostream & os) const
Writes the coordinates in human-readable form to an ostream.
 {
     os << y_ << ' ';
 }
References y_.
writeNames()
void Y::writeNames (std::ostream & os) static
Writes the coordinate names in human-readable form to an ostream.
 {
     os << "y ";
 }
Member Data Documentation
y_
Mdouble CGCoordinates::Y::y_ protected
The y-position of the current CGPoint.
Referenced by getCNormal(), getDistanceSquared(), getINormal(), getPNormal(), setY(), and write().
The documentation for this class was generated from the following files:
Y.h
Y.cc