MercuryDPM: CGFields::StandardFieldsBinning Class Reference
CGFields::StandardFieldsBinning Class Reference
Contains the computed field values, like density, momentum and stress.
#include <StandardFieldsBinning.h>
Public Member Functions
StandardFieldsBinning ()
Default constructor, sets all field values to zero.
StandardFieldsBinning (const StandardFieldsBinning &P)=default
Default copy constructor, copies the values of all fields.
~StandardFieldsBinning ()=default
Destructor, it simply destructs the StandardFieldsBinning and all the objects it contains.
void addParticleStatistics (Mdouble phi, const StandardFieldsBinning &currentInteraction)
This function should be called from within a loop over all particles to compute all the fields that are defined as a sum over all particles (e.g. density, momentum).
void addParticleDifferentialStatistics (Vec3D &dphi, const StandardFieldsBinning &currentInteraction)
void addInteractionStatistics (Mdouble psi, const StandardFieldsBinning &currentInteraction)
This function should be called from within a loop over all Interactions to compute all the fields that are defined as a sum over all Interactions (e.g. stress).
void addContactPointStatistics (Mdouble phi, const StandardFieldsBinning &currentInteraction)
This function should be called from within a loop over all Interactions to compute all the fields that are defined as a sum over all Interactions with external objects (e.g. IFD).
void setFields (const BaseInteraction &c, IntegralType type)
void setCylindricalFields (const BaseInteraction &c, IntegralType type)
void setFields (const BaseParticle &p)
void setCylindricalFields (const BaseParticle &p)
Public Member Functions inherited from CGFields::StandardFields
StandardFields ()
Default constructor, sets all field values to zero.
StandardFields (const StandardFields &P)=default
Default copy constructor, copies the values of all fields.
~StandardFields ()=default
Destructor, it simply destructs the StandardFields and all the objects it contains.
void write (std::ostream &os) const
Writes class content into an output stream, typically a stat file.
void output (std::ostream &os) const
Writes human-readable class content into an output stream, typically a stat file.
void setZero ()
Sets all fields to zero.
StandardFields getSquared () const
Returns the square of all field values (to calculate standard deviation).
StandardFields & operator= (const StandardFields &P)
Copies all field values.
StandardFields & operator+= (const StandardFields &P)
Adds the field values on the RHS to the LHS of the equation.
StandardFields & operator-= (const StandardFields &P)
Subtracts the field values on the RHS from the LHS of the equation.
StandardFields & operator/= (Mdouble a)
Divides the field values on the LHS by the RHS of the equation.
StandardFields operator* (Mdouble a) const
Multiplies the field values on the left of the '*' by the scalar value on the right of the '*' and returns the answer.
void addParticleStatistics (Mdouble phi, const StandardFields &currentInteraction)
This function should be called from within a loop over all particles to compute all the fields that are defined as a sum over all particles (e.g. density, momentum).
void addParticleDifferentialStatistics (Vec3D &dphi, const StandardFields &currentInteraction)
void addInteractionStatistics (Mdouble psi, const StandardFields &currentInteraction)
This function should be called from within a loop over all Interactions to compute all the fields that are defined as a sum over all Interactions (e.g. stress).
void addContactPointStatistics (Mdouble phi, const StandardFields &currentInteraction)
This function should be called from within a loop over all Interactions to compute all the fields that are defined as a sum over all Interactions with external objects (e.g. IFD).
void setFields (const BaseInteraction &c, IntegralType type)
void setCylindricalFields (const BaseInteraction &c, IntegralType type)
void setFields (const BaseParticle &p)
void setCylindricalFields (const BaseParticle &p)
Mdouble getVolumeFraction () const
Mdouble getDensity () const
Vec3D getMomentum () const
MatrixSymmetric3D getMomentumFlux () const
Matrix3D getContactStress () const
Vec3D getInteractionForceDensity () const
Mdouble getParticleSizeDensity (size_t i) const
std::array< Mdouble, 6 > getParticleSizeDensity () const
std::array< Mdouble, 6 > getParticleSizeMomenta () const
std::array< Mdouble, 6 > getCentralParticleSizeMomenta () const
std::array< Mdouble, 6 > getStandardisedParticleSizeMomenta () const
void outputStandardisedParticleSizeMomenta (std::ostream &os) const
Public Member Functions inherited from CGFields::BaseFields
void setCG (BaseCG *cg)
BaseCG * getCG ()
Static Public Member Functions
static bool doInteractionStatistics ()
Returns true if the class contains fields that are defined as a sum over all Interactions (e.g. stress), else returns false.
static bool evaluateFixedParticles ()
static bool isDifferentialField ()
Static Public Member Functions inherited from CGFields::StandardFields
static void writeNames (std::ostream &os, unsigned countVariables)
static bool doInteractionStatistics ()
Returns true if the class contains fields that are defined as a sum over all Interactions (e.g. stress), else returns false.
static bool evaluateFixedParticles ()
static bool isDifferentialField ()
Additional Inherited Members
Protected Member Functions inherited from CGFields::StandardFields
void setContactStress (Matrix3D contactStress)
void addContactStress (Matrix3D contactStress)
void setInteractionForceDensity (Vec3D interactionForceDensity)
void addInteractionForceDensity (Vec3D interactionForceDensity)
Protected Attributes inherited from CGFields::BaseFields
BaseCG * cg_ = nullptr
Stores a pointer to the baseCG instance to get e.g. the handler and time information.
Detailed Description
Contains the computed field values, like density, momentum and stress.
CGPoints inherits from this class; CGPoints::evaluate adds to the values of these variables.
Todo:
These are currently the only fields that are computed. However, this class is destined to be extended to contain additional information such as fabric, energy, local angular momentum. Also, a simpler version is planned, where only particle statistics are evaluated (density and momentum).
Constructor & Destructor Documentation
StandardFieldsBinning() [1/2]
CGFields::StandardFieldsBinning::StandardFieldsBinning ()
Default constructor, sets all field values to zero.
     {
         setZero();
     #ifdef DEBUG_CONSTRUCTOR
         std::cerr << "StandardFieldsBinning::StandardFieldsBinning() finished" << std::endl;
     #endif
     }
References CGFields::StandardFields::setZero().
StandardFieldsBinning() [2/2]
CGFields::StandardFieldsBinning::StandardFieldsBinning (const StandardFieldsBinning & P) default
Default copy constructor, copies the values of all fields.
~StandardFieldsBinning()
CGFields::StandardFieldsBinning::~StandardFieldsBinning () default
Destructor, it simply destructs the StandardFieldsBinning and all the objects it contains.
Member Function Documentation
addContactPointStatistics()
void CGFields::StandardFieldsBinning::addContactPointStatistics (Mdouble phi, const StandardFieldsBinning & currentInteraction) inline
This function should be called from within a loop over all Interactions to compute all the fields that are defined as a sum over all Interactions with external objects (e.g. IFD).
 {};
addInteractionStatistics()
void CGFields::StandardFieldsBinning::addInteractionStatistics (Mdouble psi, const StandardFieldsBinning & currentInteraction) inline
This function should be called from within a loop over all Interactions to compute all the fields that are defined as a sum over all Interactions (e.g. stress).
 {};
addParticleDifferentialStatistics()
void CGFields::StandardFieldsBinning::addParticleDifferentialStatistics (Vec3D & dphi, const StandardFieldsBinning & currentInteraction) inline
 {};
addParticleStatistics()
void CGFields::StandardFieldsBinning::addParticleStatistics (Mdouble phi, const StandardFieldsBinning & currentInteraction)
This function should be called from within a loop over all particles to compute all the fields that are defined as a sum over all particles (e.g. density, momentum).
Parameters
[in] phi the value of the cg function at the current CGPoint
[in] currentInteraction the fields which are produced due to the particle at its centre
     {
         StandardFields::addParticleStatistics(phi, currentInteraction);
         addContactStress(currentInteraction.getContactStress()*phi);
         addInteractionForceDensity(currentInteraction.getInteractionForceDensity()*phi);
     }
References CGFields::StandardFields::addContactStress(), CGFields::StandardFields::addInteractionForceDensity(), CGFields::StandardFields::addParticleStatistics(), CGFields::StandardFields::getContactStress(), and CGFields::StandardFields::getInteractionForceDensity().
doInteractionStatistics()
static bool CGFields::StandardFieldsBinning::doInteractionStatistics () inline static
Returns true if the class contains fields that are defined as a sum over all Interactions (e.g. stress), else returns false.
Within binning all fields are evaluated on a per particle level so also the contact stress is averaged from the individual particles rather than from the individual interactions
     {
         return false;
     }
evaluateFixedParticles()
static bool CGFields::StandardFieldsBinning::evaluateFixedParticles () inline static
     {
         return false;
     }
isDifferentialField()
static bool CGFields::StandardFieldsBinning::isDifferentialField () inline static
A bool that determines if the derivative of the CG function has to be computed
     {
         return false;
     }
setCylindricalFields() [1/2]
void CGFields::StandardFieldsBinning::setCylindricalFields (const BaseInteraction & c, IntegralType type) inline
 {};
setCylindricalFields() [2/2]
void CGFields::StandardFieldsBinning::setCylindricalFields (const BaseParticle & p) inline
 {};
setFields() [1/2]
void CGFields::StandardFieldsBinning::setFields (const BaseInteraction & c, IntegralType type) inline
 {};
setFields() [2/2]
void CGFields::StandardFieldsBinning::setFields (const BaseParticle & p)
     {
         StandardFields::setFields(p);
         Matrix3D sumContactStress;
         Vec3D sumForces;
         // Using Eqs. 7, 11, and 15 from the following paper
         // https://www2.msm.ctw.utwente.nl/sluding/PAPERS/cdm2004_luding.pdf
         // or look here: https://doi.org/10.1016/j.ijsolstr.2004.05.048
         for (auto i: p.getInteractions())
         {
             if (i->getP() == &p)
             {
                 sumForces += i->getForce();
                 sumContactStress += Matrix3D::dyadic(i->getForce(), i->getCP());
             }
             else if (i->getI() == &p)
             {
                 sumForces += -i->getForce();
                 sumContactStress += Matrix3D::dyadic(i->getForce(), i->getIC());
             }
             else
             {
                 logger(ERROR, "Something went wrong in StandardFieldsBinning::setFields: handled particle is not part of its own interactions");
             }
         }
         setInteractionForceDensity(sumForces);
         setContactStress(sumContactStress);
     }
References Matrix3D::dyadic(), ERROR, i, logger, p, CGFields::StandardFields::setContactStress(), CGFields::StandardFields::setFields(), and CGFields::StandardFields::setInteractionForceDensity().
The documentation for this class was generated from the following files:
StandardFieldsBinning.h
StandardFieldsBinning.cc