MercuryDPM: RandomClusterInsertionBoundaryDemo.cpp File Reference
RandomClusterInsertionBoundaryDemo.cpp File Reference
#include <iostream>
#include "Mercury3D.h"
#include <Boundaries/RandomClusterInsertionBoundary.h>
#include "Species/LinearPlasticViscoelasticFrictionSpecies.h"
#include <Walls/InfiniteWall.h>
Classes
class RandomClusterInsertionBoundarySelfTest
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     logger(INFO,"Simple box for creating particles");
     RandomClusterInsertionBoundarySelfTest insertionBoundary_problem;
     insertionBoundary_problem.setMin(Vec3D(-0.5, -0.5, -0.5));
     insertionBoundary_problem.setMax(Vec3D(0.5, 0.5, 0.5));
     Mdouble constantMass = 2700 * 4 * constants::pi * pow(0.013, 3) / 3;
     Mdouble collisionTimeIntra = sqrt(constantMass * (pow(constants::pi, 2) + pow(log(0.5), 2)) /
                                       (2 * 1e3));
     LinearPlasticViscoelasticFrictionSpecies* species;
     species = new LinearPlasticViscoelasticFrictionSpecies;
     species->setConstantRestitution(true);
     species->setDensity(2700);
     species->setCollisionTimeAndRestitutionCoefficient(collisionTimeIntra, 0.5, 1);
     species->setUnloadingStiffnessMax(
             species->getLoadingStiffness() * 5);
     species->setCohesionStiffness(species->getUnloadingStiffnessMax() / 3);
     species->setPenetrationDepthMax(0.1);
     species->setSlidingFrictionCoefficient(0.1);
     species->setSlidingStiffness(species->getLoadingStiffness() * 2.0/7.0);
     species->setSlidingDissipation(species->getDissipation() * 2.0 / 7.0);
     insertionBoundary_problem.speciesHandler.copyAndAddObject(species);
     insertionBoundary_problem.setNumberOfDomains({1,2,1});
     insertionBoundary_problem.solve();
 }
References BaseHandler< T >::copyAndAddObject(), INFO, Eigen::bfloat16_impl::log(), logger, constants::pi, Eigen::ArrayBase< Derived >::pow(), ParticleSpecies::setDensity(), DPMBase::setMax(), DPMBase::setMin(), DPMBase::setNumberOfDomains(), DPMBase::solve(), DPMBase::speciesHandler, and sqrt().