MercuryDPM: LiquidMigrationLSInteraction Class Reference
LiquidMigrationLSInteraction Class Reference
Defines the liquid bridge LS interaction between two particles or walls.
#include <LiquidMigrationLSInteraction.h>
Public Types
typedef LiquidMigrationLSSpecies SpeciesType
An alias name for LiquidMigrationLSSpecies data type.
Public Member Functions
LiquidMigrationLSInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
Constructor.
LiquidMigrationLSInteraction ()
LiquidMigrationLSInteraction (const LiquidMigrationLSInteraction &p)
Copy constructor.
~LiquidMigrationLSInteraction () override
Destructor.
void actionsOnErase () override
If an interaction needs to do something before it gets erased, add it here. E.g. Liquid bridges rupture at the end of their lifetime, and the liquid bridge volume has to be redistributed. The reason this action is not done in the destructor is that this action should not be taken when erasing ghost interactions.
void actionsAfterTimeStep () override
test if particle needs to be ruptured
void computeAdhesionForce ()
Computes the adhesive forces for liquid bridge LS type of interaction.
void read (std::istream &is) override
Interaction read function, which accepts an std::istream as input.
void write (std::ostream &os) const override
Interaction print function, which accepts an std::ostream as input.
Mdouble getElasticEnergy () const override
Returns the amount of Elastic energy involved in an interaction. Basically used in case you want to write the elastic energy into an output file.
const LiquidMigrationLSSpecies * getSpecies () const
Returns a pointer to the adhesive force species LiquidMigrationLSSpecies.
std::string getBaseName () const
Returns the name of the interaction, see Interaction.h.
Mdouble getLiquidBridgeVolume () const
void setLiquidBridgeVolume (Mdouble liquidBridgeVolume)
void addLiquidBridgeVolume (Mdouble liquidBridgeVolume)
bool getWasInContact () const
void setWasInContact (bool wasInContact)
void rupture ()
void form ()
Mdouble getRuptureDistance ()
Mdouble getHalfFillingAngle ()
Mdouble getLimitingDistance ()
unsigned getNumberOfFieldsVTK () const override
std::string getTypeVTK (unsigned i) const override
std::string getNameVTK (unsigned i) const override
std::vector< Mdouble > getFieldVTK (unsigned i) const override
Public Member Functions inherited from BaseInteraction
BaseInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
A constructor takes the BaseInteractable objects which are interacting (come into contact) and time the interaction starts.
BaseInteraction ()
BaseInteraction (const BaseInteraction &p)
Copy constructor.
~BaseInteraction () override
The destructor. It removes this interactions from the objects that were interacting, and writes the time to a file when needed.
virtual void computeForce ()
Virtual function that contains the force law between the two objects interacting.
void read (std::istream &is) override
Interaction read function, which accepts an std::istream as input.
void write (std::ostream &os) const override
Interaction print function, which accepts an std::ostream as input.
void writeToFStat (std::ostream &os, Mdouble time) const
Writes forces data to the FStat file.
std::string getName () const override
Virtual function which allows interactions to be named.
void setDistance (Mdouble distance)
Sets the interaction distance between the two interacting objects.
void setNormal (Vec3D normal)
Sets the normal vector between the two interacting objects.
void setOverlap (Mdouble overlap)
Set the overlap between the two interacting object.
void setContactPoint (Vec3D contactPoint)
Set the location of the contact point between the two interacting objects.
void setTimeStamp (unsigned timeStamp)
Updates the time step of the interacting. Note, time steps used to find completed interactions.
void setSpecies (const BaseSpecies *species)
Set the Species of the interaction; note this can either be a Species or MixedSpecies.
void setP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void setI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
void importP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void importI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
Vec3D getIP () const
Vec3D getIC () const
Vec3D getCP () const
void setLagrangeMultiplier (Mdouble multiplier)
Mdouble getLagrangeMultiplier ()
void setHandler (InteractionHandler *handler)
Sets the pointer to the interaction hander which is storing this interaction.
InteractionHandler * getHandler () const
Gets a point to the interaction handlers to which this interaction belongs.
const Vec3D & getForce () const
Gets the current force (vector) between the two interacting objects.
const Vec3D & getTorque () const
Gets the current torque (vector) between the two interacting objects.
const Vec3D & getNormal () const
Gets the normal vector between the two interacting objects.
const Vec3D & getContactPoint () const
Gets constant reference to contact point (vector).
Mdouble getOverlap () const
Returns a Mdouble with the current overlap between the two interacting objects.
Mdouble getOverlapVolume () const
Returns the overlap volume between two interacting objects.
Mdouble getContactRadius () const
Returns a Mdouble with the current contact between the two interacting objects.
void removeFromHandler ()
Removes this interaction from its interaction hander.
void copySwitchPointer (const BaseInteractable *original, BaseInteractable *ghost) const
This copies the interactions of the original particle and replaces the original with the ghost copy.
void gatherContactStatistics ()
BaseInteractable * getP ()
Returns a pointer to first object involved in the interaction (normally a particle).
BaseInteractable * getI ()
Returns a pointer to the second object involved in the interaction (often a wall or a particle).
const BaseInteractable * getP () const
Returns a constant pointer to the first object involved in the interaction.
const BaseInteractable * getI () const
Returns a constant pointer to the second object involved in the interaction.
Mdouble getTimeStamp () const
Returns an Mdouble which is the time stamp of the interaction.
virtual void integrate (Mdouble timeStep)
integrates variables of the interaction which need to be integrate e.g. the tangential overlap.
virtual Mdouble getTangentialOverlap () const
get the length of the current tangential overlap
Mdouble getDistance () const
Returns an Mdouble which is the norm (length) of distance vector.
const Vec3D & getRelativeVelocity () const
Returns a constant reference to a vector of relative velocity.
Mdouble getNormalRelativeVelocity () const
Returns a double which is the norm (length) of the relative velocity vector.
Mdouble getAbsoluteNormalForce () const
Returns the absolute value of the norm (length) of the Normal force vector.
virtual BaseInteraction * copy () const =0
Makes a copy of the interaction and returns a pointer to the copy.
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseWall *I)
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseParticle *I)
unsigned int getMultiContactIdentifier () const
void setMultiContactIdentifier (unsigned int multiContactIdentifier_)
virtual void rotateHistory (Matrix3D &rotationMatrix)
When periodic particles are used, some interactions need certain history properties rotated (e.g. tangential springs). This is the function for that.
void addForce (Vec3D force)
add an force increment to the total force.
void addTorque (Vec3D torque)
add a torque increment to the total torque.
void setForce (Vec3D force)
set total force (this is used by the normal force, tangential forces are added use addForce)
void setTorque (Vec3D torque)
set the total force (this is used by the normal force, tangential torques are added use addTorque)
const BaseSpecies * getBaseSpecies () const
Return a constant point to BaseSpecies of the interaction.
virtual void createMPIType ()
virtual void * createMPIInteractionDataArray (unsigned int numberOfInteractions) const
virtual void deleteMPIInteractionDataArray (void *dataArray)
virtual void getMPIInteraction (void *historyDataArray, unsigned int index) const
copies the history interactions into the data array
virtual void getInteractionDetails (void *interactionDataArray, unsigned int index, unsigned int &identificationP, unsigned int &identificationI, bool &isWallInteraction, unsigned &timeStamp)
virtual void setMPIInteraction (void *interactionDataArray, unsigned int index, bool resetPointers)
void setBasicMPIInteractionValues (int P, int I, unsigned timeStamp, Vec3D force, Vec3D torque, bool isWallInteraction, bool resetPointers)
void setIdentificationP (unsigned int identification)
void setIdentificationI (int identification)
void setWallInteraction (bool flag)
unsigned int getIdentificationP ()
int getIdentificationI ()
bool isWallInteraction ()
virtual bool isBonded () const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Static Public Member Functions
static Mdouble getTotalLiquidFilmVolume (ParticleHandler &)
static Mdouble getTotalLiquidBridgeVolume (InteractionHandler &)
Private Member Functions
void distributeToOtherBridges (LiquidFilmParticle *particle, Mdouble distributableVolume)
Private Attributes
bool wasInContact_
A history parameter to store if the particles were in contact or not. Useful to compute adhesive forces.
Mdouble liquidBridgeVolume_
Additional Inherited Members
Protected Member Functions inherited from BaseInteraction
virtual const Vec3D getTangentialForce () const
Mdouble getEffectiveRadius () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
Mdouble getEffectiveMass () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
void setRelativeVelocity (Vec3D relativeVelocity)
set the relative velocity of the current of the interactions.
void setNormalRelativeVelocity (Mdouble normalRelativeVelocit)
set the normal component of the relative velocity.
void setAbsoluteNormalForce (Mdouble absoluteNormalForce)
the absolute values of the norm (length) of the normal force
virtual Mdouble getElasticEnergyAtEquilibrium (Mdouble adhesiveForce) const
virtual void reverseHistory ()
When periodic particles some interaction need certain history properties reversing. This is the function for that.
void writeInteraction (std::ostream &os, bool created) const
Writes information about a interaction to the interaction file.
Detailed Description
Defines the liquid bridge LS interaction between two particles or walls.
Member Typedef Documentation
SpeciesType
typedef LiquidMigrationLSSpecies LiquidMigrationLSInteraction::SpeciesType
An alias name for LiquidMigrationLSSpecies data type.
Constructor & Destructor Documentation
LiquidMigrationLSInteraction() [1/3]
LiquidMigrationLSInteraction::LiquidMigrationLSInteraction (BaseInteractable * P, BaseInteractable * I, unsigned timeStamp)
Constructor.
Parameters
[in] P
[in] I
[in] timeStamp
         : BaseInteraction(P, I, timeStamp)
 {
     liquidBridgeVolume_ = 0.0;
     wasInContact_ = false;
 #ifdef DEBUG_CONSTRUCTOR
     logger(INFO, "LiquidMigrationLSInteraction::LiquidMigrationLSInteraction() finished");
 #endif
 }
References INFO, liquidBridgeVolume_, logger, and wasInContact_.
LiquidMigrationLSInteraction() [2/3]
LiquidMigrationLSInteraction::LiquidMigrationLSInteraction ()
         : BaseInteraction()
 {
     liquidBridgeVolume_ = 0.0;
     wasInContact_ = false;
 #ifdef DEBUG_CONSTRUCTOR
     logger(INFO, "LiquidMigrationLSInteraction::LiquidMigrationLSInteraction() finished");
 #endif
 }
References INFO, liquidBridgeVolume_, logger, and wasInContact_.
LiquidMigrationLSInteraction() [3/3]
LiquidMigrationLSInteraction::LiquidMigrationLSInteraction (const LiquidMigrationLSInteraction & p)
Copy constructor.
Parameters
[in] p
         : BaseInteraction(p)
 {
     liquidBridgeVolume_ = p.liquidBridgeVolume_;
     wasInContact_ = p.wasInContact_;
 #ifdef DEBUG_CONSTRUCTOR
     logger(INFO, "LiquidMigrationLSInteraction::LiquidMigrationLSInteraction(const LiquidMigrationLSInteraction &p finished");
 #endif
 }
References INFO, liquidBridgeVolume_, logger, p, and wasInContact_.
~LiquidMigrationLSInteraction()
LiquidMigrationLSInteraction::~LiquidMigrationLSInteraction () override
Destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     logger(INFO, "LiquidMigrationLSInteraction::~LiquidMigrationLSInteraction() finished");
 #endif
 }
References INFO, and logger.
Member Function Documentation
actionsAfterTimeStep()
void LiquidMigrationLSInteraction::actionsAfterTimeStep () override virtual
test if particle needs to be ruptured
Reimplemented from BaseInteraction.
 {
     if (wasInContact_)
     {
         if (-getOverlap() >= getRuptureDistance())
         {
             rupture();
         }
     }
     else
     {
         if (getOverlap() >= 0)
         {
             form();
         }
     }
 }
References form(), BaseInteraction::getOverlap(), getRuptureDistance(), rupture(), and wasInContact_.
actionsOnErase()
void LiquidMigrationLSInteraction::actionsOnErase () override virtual
If an interaction needs to do something before it gets erased, add it here. E.g. Liquid bridges rupture at the end of their lifetime, and the liquid bridge volume has to be redistributed. The reason this action is not done in the destructor is that this action should not be taken when erasing ghost interactions.
Reimplemented from BaseInteraction.
 {
     rupture();
 };
References rupture().
addLiquidBridgeVolume()
void LiquidMigrationLSInteraction::addLiquidBridgeVolume (Mdouble liquidBridgeVolume)
 {
     liquidBridgeVolume_ += liquidBridgeVolume;
 }
References liquidBridgeVolume_.
computeAdhesionForce()
void LiquidMigrationLSInteraction::computeAdhesionForce ()
Computes the adhesive forces for liquid bridge LS type of interaction.
The contact model is based on the description given in (Zhang and Wu, 2020): https://www.sciencedirect.com/science/article/pii/S0032591019311258 This model includes a normal capillary force, a normal lubrication force and a tangential lubrication force. The capillary force is valid when particles are within rupture distance. The formulation is in (Lian and Seville, 2015): https://doi.org/10.1016/j.cis.2015.11.003. The lubrication force is valid when particles are within limiting distance. Note: the tangential lubrication force is added to sliding friction force through SlidingFrictionInteraction::addTangentialForce().
 {
     // Adding no capillary force for liquid bridge volume = 0
     if (getLiquidBridgeVolume() == 0) return;
     if (getOverlap() >= 0)
     {
         // if particles are in contact
         const LiquidMigrationLSSpecies* species = getSpecies();
         const Mdouble effectiveRadius = getEffectiveRadius();
         const Mdouble fdotn = -2.0 * species->getSurfaceTension() * effectiveRadius *
                               (2.0 * constants::pi - 2.082 * pow(getHalfFillingAngle(), 0.9197)) *
                               (std::cos(species->getContactAngle()) - 0.16 * getHalfFillingAngle() *
                               (1.0 + getHalfFillingAngle()) * std::tan(species->getContactAngle())); //max value of capillary;
         addForce(getNormal() * fdotn);
     }
     else if (wasInContact_)
     {
         // if particles are not in contact, but within their interaction distance
         const LiquidMigrationLSSpecies* species = getSpecies();
         const Mdouble effectiveRadius = getEffectiveRadius();
         const Mdouble s_nondim = -getOverlap()/getRuptureDistance() * (1.0 + 0.5 * species->getContactAngle() *
                             std::cos(species->getContactAngle()) * std::cos(getHalfFillingAngle() + species->getContactAngle()) ); //dimensionless S
         const Mdouble fdotnc = -2.0 * species->getSurfaceTension() * effectiveRadius *
                                 (2.0 * constants::pi - 2.082 * pow(getHalfFillingAngle(), 0.9197)) *
                                 (std::cos(species->getContactAngle()) - 0.16 * getHalfFillingAngle() *
                                 (1.0 + getHalfFillingAngle()) * std::tan(species->getContactAngle()))
                                 /(1.0 + 0.8438 * pow(getHalfFillingAngle(), -0.724) * s_nondim +
                                 1.3393 * pow(getHalfFillingAngle(), -1.459) * pow(s_nondim, 2.0));//capillary force
         Mdouble fdotnl = 0.0;//normal lubrication force in value
         Vec3D fdottl = Vec3D(0.0, 0.0, 0.0);//tangential lubrication force in vector
         if(-getOverlap() > getLimitingDistance())
         {
             fdotnl = -6.0 * constants::pi * species->getViscosity() * pow(effectiveRadius, 2.0)
                                     * getNormalRelativeVelocity()/(-getOverlap());
             Vec3D tangentialRelativeVelocity = getRelativeVelocity() - getNormal() * getNormalRelativeVelocity();
             fdottl = -6.0 * constants::pi * species->getViscosity() * effectiveRadius * tangentialRelativeVelocity
                      * (8.0/15.0 * std::log(effectiveRadius/(-getOverlap())) + 0.9588);
         }
         addForce(getNormal() * (fdotnc + fdotnl) + fdottl);
         //add tangential lubrication force to sliding friction force
         auto slidingFrictionInteraction = dynamic_cast<SlidingFrictionInteraction*>(this);
         slidingFrictionInteraction->addTangentialForce(fdottl);
     }
 }
References BaseInteraction::addForce(), SlidingFrictionInteraction::addTangentialForce(), cos(), LiquidMigrationLSSpecies::getContactAngle(), BaseInteraction::getEffectiveRadius(), getHalfFillingAngle(), getLimitingDistance(), getLiquidBridgeVolume(), BaseInteraction::getNormal(), BaseInteraction::getNormalRelativeVelocity(), BaseInteraction::getOverlap(), BaseInteraction::getRelativeVelocity(), getRuptureDistance(), getSpecies(), LiquidMigrationLSSpecies::getSurfaceTension(), LiquidMigrationLSSpecies::getViscosity(), Eigen::bfloat16_impl::log(), constants::pi, Eigen::bfloat16_impl::pow(), Eigen::bfloat16_impl::tan(), and wasInContact_.
distributeToOtherBridges()
void LiquidMigrationLSInteraction::distributeToOtherBridges (LiquidFilmParticle * particle, Mdouble distributableVolume) private
 {
     // Get the other valid liquid bridges that the particle has.
     std::vector<LiquidMigrationLSInteraction*> bridges;
     for (auto i : particle->getInteractions())
     {
         auto j = dynamic_cast<LiquidMigrationLSInteraction*>(i);
         if (j != this && j != nullptr && j->getLiquidBridgeVolume() != 0.0)
             bridges.push_back(j);
     }
     // When there are no other bridges, the particle should get all the liquid.
     if (bridges.empty())
         particle->addLiquidVolume(distributableVolume);
     else
     {
         // Calculate the particle and bridge volumes from to the distribution coefficient and the number of bridges.
         particle->addLiquidVolume(distributableVolume * (1.0 - getSpecies()->getDistributionCoefficient()));
         Mdouble bridgeVolume = distributableVolume * getSpecies()->getDistributionCoefficient() / bridges.size();
         for (auto i : bridges)
         {
             // Add liquid to the bridge, but keep within maximum. Any excess liquid is added to the particle.
             Mdouble excess = std::max(i->getLiquidBridgeVolume() + bridgeVolume - getSpecies()->getLiquidBridgeVolumeMax(), 0.0);
             i->addLiquidBridgeVolume(bridgeVolume - excess);
             particle->addLiquidVolume(excess);
         }
     }
 }
References LiquidFilm< Particle >::addLiquidVolume(), LiquidMigrationLSSpecies::getDistributionCoefficient(), getSpecies(), i, j, and max.
Referenced by rupture().
form()
void LiquidMigrationLSInteraction::form ()
 {
     //form a bridge
     //todo: extend to neighbours
     wasInContact_ = true;
     auto species = getSpecies();
     auto P = dynamic_cast<LiquidFilmParticle*>(getP());
     auto I = dynamic_cast<LiquidFilmParticle*>(getI());
     if (P == nullptr) //if P is a wall
     {
         logger(ERROR,"In LiquidMigrationLSInteraction::form, P should be a particle");
     }
     else if (I == nullptr) //if I is a wall
     {
         // Don't form a bridge when the volume is below the minimum bridge volume.
         if (P->getLiquidVolume() < species->getLiquidBridgeVolumeMin())
             return;
         // Don't exceed the maximum bridge volume. Remaining liquid will be kept in the particle.
         Mdouble liquidBridgeVolume = std::min(species->getLiquidBridgeVolumeMax(), P->getLiquidVolume());
         setLiquidBridgeVolume(liquidBridgeVolume);
         P->addLiquidVolume(-liquidBridgeVolume);
     }
     else //if P and I are particles
     {
         Mdouble distributableLiquidVolume = P->getLiquidVolume() + I->getLiquidVolume();
         // Don't form a bridge when the volume is below the minimum bridge volume.
         if (distributableLiquidVolume <= species->getLiquidBridgeVolumeMin())
             return;
         // Don't exceed the maximum bridge volume. Remaining liquid will be kept in the particles.
         Mdouble pFraction = P->getLiquidVolume() / distributableLiquidVolume;
         Mdouble liquidBridgeVolume = std::min(species->getLiquidBridgeVolumeMax(), distributableLiquidVolume);
         setLiquidBridgeVolume(liquidBridgeVolume);
         P->addLiquidVolume(-pFraction * liquidBridgeVolume);
         I->addLiquidVolume(-(1.0 - pFraction) * liquidBridgeVolume);
     }
 }
References ERROR, BaseInteraction::getI(), BaseInteraction::getP(), getSpecies(), I, logger, min, Global_Physical_Variables::P, setLiquidBridgeVolume(), and wasInContact_.
Referenced by actionsAfterTimeStep().
getBaseName()
std::string LiquidMigrationLSInteraction::getBaseName () const
Returns the name of the interaction, see Interaction.h.
Returns
std::string
 {
     return "LiquidMigrationLS";
 }
getElasticEnergy()
Mdouble LiquidMigrationLSInteraction::getElasticEnergy () const override virtual
Returns the amount of Elastic energy involved in an interaction. Basically used in case you want to write the elastic energy into an output file.
Returns
Mdouble
Todo:
TW
Reimplemented from BaseInteraction.
 {
     return 0.0;
 }
getFieldVTK()
std::vector< Mdouble > LiquidMigrationLSInteraction::getFieldVTK (unsigned i) const override virtual
Reimplemented from BaseInteraction.
 {
     return std::vector<Mdouble>(1, cbrt(liquidBridgeVolume_));
 }
References Eigen::numext::cbrt(), and liquidBridgeVolume_.
getHalfFillingAngle()
Mdouble LiquidMigrationLSInteraction::getHalfFillingAngle ()
 {
     const LiquidMigrationLSSpecies* species = getSpecies();
     return pow(liquidBridgeVolume_, 0.26) + (0.285 - 0.4594 * species->getContactAngle()) * pow(liquidBridgeVolume_, (0.6327 + 0.897 * species->getContactAngle()));
 }
References LiquidMigrationLSSpecies::getContactAngle(), getSpecies(), liquidBridgeVolume_, and Eigen::bfloat16_impl::pow().
Referenced by computeAdhesionForce().
getLimitingDistance()
Mdouble LiquidMigrationLSInteraction::getLimitingDistance ()
 {
     return getRuptureDistance()/4.0;
 }
References getRuptureDistance().
Referenced by computeAdhesionForce().
getLiquidBridgeVolume()
Mdouble LiquidMigrationLSInteraction::getLiquidBridgeVolume () const
 {
     return liquidBridgeVolume_;
 }
References liquidBridgeVolume_.
Referenced by computeAdhesionForce(), and rupture().
getNameVTK()
std::string LiquidMigrationLSInteraction::getNameVTK (unsigned i) const override virtual
Reimplemented from BaseInteraction.
 {
     return "liquidBridgeRadius";
 }
getNumberOfFieldsVTK()
unsigned LiquidMigrationLSInteraction::getNumberOfFieldsVTK () const override virtual
writes extra information to the VTK output
Reimplemented from BaseInteraction.
 {
     return 1;
 }
getRuptureDistance()
Mdouble LiquidMigrationLSInteraction::getRuptureDistance ()
 {
     const LiquidMigrationLSSpecies* species = getSpecies();
     return (1.0 + 0.5 * species->getContactAngle()) * (cbrt(liquidBridgeVolume_) + 0.1 * pow(liquidBridgeVolume_, 2.0/3.0));
 }
References Eigen::numext::cbrt(), LiquidMigrationLSSpecies::getContactAngle(), getSpecies(), liquidBridgeVolume_, and Eigen::bfloat16_impl::pow().
Referenced by actionsAfterTimeStep(), computeAdhesionForce(), and getLimitingDistance().
getSpecies()
const LiquidMigrationLSSpecies * LiquidMigrationLSInteraction::getSpecies () const
Returns a pointer to the adhesive force species LiquidMigrationLSSpecies.
Returns
const LiquidMigrationLSSpecies*
 {
     return static_cast<const LiquidMigrationLSSpecies*>(getBaseSpecies()->getAdhesiveForce());
 }
References BaseSpecies::getAdhesiveForce(), and BaseInteraction::getBaseSpecies().
Referenced by computeAdhesionForce(), distributeToOtherBridges(), form(), getHalfFillingAngle(), and getRuptureDistance().
getTotalLiquidBridgeVolume()
Mdouble LiquidMigrationLSInteraction::getTotalLiquidBridgeVolume (InteractionHandler & h) static
 {
     Mdouble volume = 0;
     for (auto i : h)
     {
         auto l = dynamic_cast<LiquidMigrationLSInteraction*>(i);
         if (l)
         {
             volume += l->getLiquidBridgeVolume();
         }
     }
     return volume;
 }
References i.
getTotalLiquidFilmVolume()
Mdouble LiquidMigrationLSInteraction::getTotalLiquidFilmVolume (ParticleHandler & h) static
 {
     Mdouble volume = 0;
     for (auto p : h)
     {
         auto l = dynamic_cast<LiquidFilmParticle*>(p);
         if (l)
         {
             volume += l->getLiquidVolume();
         }
     }
     return volume;
 }
References p.
getTypeVTK()
std::string LiquidMigrationLSInteraction::getTypeVTK (unsigned i) const override virtual
Reimplemented from BaseInteraction.
 {
     return "Float32";
 }
getWasInContact()
bool LiquidMigrationLSInteraction::getWasInContact () const
 {
     return wasInContact_;
 }
References wasInContact_.
read()
void LiquidMigrationLSInteraction::read (std::istream & is) override virtual
Interaction read function, which accepts an std::istream as input.
Parameters
[in,out] is
Implements BaseObject.
 {
     std::string dummy;
     is >> dummy >> wasInContact_;
     is >> dummy >> liquidBridgeVolume_;
 }
References liquidBridgeVolume_, oomph::Global_string_for_annotation::string(), and wasInContact_.
rupture()
void LiquidMigrationLSInteraction::rupture ()
 {
     // remove the contact history
     wasInContact_ = false;
     //if the bridge is already empty, do nothing
     if (getLiquidBridgeVolume() == 0.0)
         return;
     //else rupture a bridge
     auto P = dynamic_cast<LiquidFilmParticle*>(getP());
     auto I = dynamic_cast<LiquidFilmParticle*>(getI());
     if (P == nullptr) //if P is a wall
     {
         logger(ERROR,"In LiquidMigrationLSInteraction::rupture, P should be a particle");
     }
     else if (I == nullptr) //if I is a wall
     {
         distributeToOtherBridges(P, getLiquidBridgeVolume());
         setLiquidBridgeVolume(0.0);
     }
     else //if P and I are particles
     {
         distributeToOtherBridges(P, 0.5 * getLiquidBridgeVolume());
         distributeToOtherBridges(I, 0.5 * getLiquidBridgeVolume());
         setLiquidBridgeVolume(0.0);
     }
 }
References distributeToOtherBridges(), ERROR, BaseInteraction::getI(), getLiquidBridgeVolume(), BaseInteraction::getP(), I, logger, Global_Physical_Variables::P, setLiquidBridgeVolume(), and wasInContact_.
Referenced by actionsAfterTimeStep(), and actionsOnErase().
setLiquidBridgeVolume()
void LiquidMigrationLSInteraction::setLiquidBridgeVolume (Mdouble liquidBridgeVolume)
 {
     liquidBridgeVolume_ = liquidBridgeVolume;
 }
References liquidBridgeVolume_.
Referenced by form(), and rupture().
setWasInContact()
void LiquidMigrationLSInteraction::setWasInContact (bool wasInContact)
 {
     wasInContact_ = wasInContact;
 }
References wasInContact_.
write()
void LiquidMigrationLSInteraction::write (std::ostream & os) const override virtual
Interaction print function, which accepts an std::ostream as input.
Parameters
[in,out] os
Implements BaseObject.
 {
     os
             << " wasInContact " << wasInContact_
             << " liquidBridgeVolume " << liquidBridgeVolume_;
 }
References liquidBridgeVolume_, and wasInContact_.
Member Data Documentation
liquidBridgeVolume_
Mdouble LiquidMigrationLSInteraction::liquidBridgeVolume_ private
Referenced by addLiquidBridgeVolume(), getFieldVTK(), getHalfFillingAngle(), getLiquidBridgeVolume(), getRuptureDistance(), LiquidMigrationLSInteraction(), read(), setLiquidBridgeVolume(), and write().
wasInContact_
bool LiquidMigrationLSInteraction::wasInContact_ private
A history parameter to store if the particles were in contact or not. Useful to compute adhesive forces.
Referenced by actionsAfterTimeStep(), computeAdhesionForce(), form(), getWasInContact(), LiquidMigrationLSInteraction(), read(), rupture(), setWasInContact(), and write().
The documentation for this class was generated from the following files:
LiquidMigrationLSInteraction.h
LiquidMigrationLSInteraction.cc