MercuryDPM: oomph::XdaTetMesh< ELEMENT > Class Template Reference
oomph::XdaTetMesh< ELEMENT > Class Template Reference
Tet mesh made of quadratic (ten node) tets built from xda input file.
#include <xda_tet_mesh.template.h>
Public Member Functions
XdaTetMesh (const std::string xda_file_name, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
void setup_boundary_coordinates (const unsigned &b, const bool &switch_normal)
void setup_boundary_coordinates (const unsigned &b, const bool &switch_normal, std::ofstream &outfile)
unsigned nxda_boundary ()
Vector< unsigned > oomph_lib_boundary_ids (const unsigned &xda_boundary_id)
Public Member Functions inherited from oomph::TetMeshBase
TetMeshBase ()
Constructor.
TetMeshBase (const TetMeshBase &node)=delete
Broken copy constructor.
void operator= (const TetMeshBase &)=delete
Broken assignment operator.
virtual ~TetMeshBase ()
Destructor (empty)
void assess_mesh_quality (std::ofstream &some_file)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, const bool &switch_normal)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, const bool &switch_normal, std::ofstream &outfile)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, std::ofstream &outfile)
unsigned nboundary_element_in_region (const unsigned &b, const unsigned &r) const
Return the number of elements adjacent to boundary b in region r.
FiniteElement * boundary_element_in_region_pt (const unsigned &b, const unsigned &r, const unsigned &e) const
Return pointer to the e-th element adjacent to boundary b in region r.
int face_index_at_boundary_in_region (const unsigned &b, const unsigned &r, const unsigned &e) const
Return face index of the e-th element adjacent to boundary b in region r.
unsigned nregion ()
Return the number of regions specified by attributes.
unsigned nregion_element (const unsigned &r)
Return the number of elements in region r.
double region_attribute (const unsigned &i)
FiniteElement * region_element_pt (const unsigned &r, const unsigned &e)
Return the e-th element in the r-th region.
template<class ELEMENT >
void snap_to_quadratic_surface (const Vector< unsigned > &boundary_id, const std::string &quadratic_surface_file_name, const bool &switch_normal, DocInfo &doc_info)
template<class ELEMENT >
void snap_to_quadratic_surface (const Vector< unsigned > &boundary_id, const std::string &quadratic_surface_file_name, const bool &switch_normal)
void snap_nodes_onto_geometric_objects ()
template<class ELEMENT >
void split_elements_in_corners (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Private Attributes
Vector< Vector< unsigned > > Boundary_id
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::TetMeshBase
static double Tolerance_for_boundary_finding = 1.0e-5
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes inherited from oomph::TetMeshBase
Vector< Vector< FiniteElement * > > Region_element_pt
Vector< double > Region_attribute
Vector< std::map< unsigned, Vector< FiniteElement * > > > Boundary_region_element_pt
Storage for elements adjacent to a boundary in a particular region.
Vector< std::map< unsigned, Vector< int > > > Face_index_region_at_boundary
TetMeshFacetedClosedSurface * Outer_boundary_pt
Faceted surface that defines outer boundaries.
Vector< TetMeshFacetedSurface * > Internal_surface_pt
Vector to faceted surfaces that define internal boundaries.
std::map< unsigned, TetMeshFacetedSurface * > Tet_mesh_faceted_surface_pt
std::map< unsigned, TetMeshFacet * > Tet_mesh_facet_pt
std::map< unsigned, Vector< Vector< double > > > Triangular_facet_vertex_boundary_coordinate
TimeStepper * Time_stepper_pt
Timestepper used to build nodes.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Detailed Description
template<class ELEMENT>
class oomph::XdaTetMesh< ELEMENT >
Tet mesh made of quadratic (ten node) tets built from xda input file.
Constructor & Destructor Documentation
XdaTetMesh()
template<class ELEMENT > oomph::XdaTetMesh< ELEMENT >::XdaTetMesh (const std::string xda_file_name, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass name of xda file. Note that all boundary elements get their own ID – this is required for FSI problems. In this case; the vector containing the oomph-lib boundary IDs of all oomph-lib boundaries that collectively form a given boundary as specified in the xda input file can be obtained from the access function oomph_lib_boundary_ids(...). Timestepper defaults to steady pseudo-timestepper.
Constructor: Pass name of xda file. Note that all boundary elements get their own ID – this is required for FSI problems. The vector containing the oomph-lib boundary IDs of all oomph-lib boundaries that collectively form a given boundary as specified in the xda input file can be obtained from the access function oomph_lib_boundary_ids(...). Timestepper defaults to steady pseudo-timestepper.
   {
     // Mesh can only be built with 3D Telements.
     MeshChecker::assert_geometric_element<TElementGeometricBase, ELEMENT>(3);
     // Open and process xda input file
     std::ifstream infile(xda_file_name.c_str(), std::ios_base::in);
     unsigned n_node;
     unsigned n_element;
     unsigned n_bound_face;
     if (!infile.is_open())
     {
       std::ostringstream error_stream;
       error_stream << "Failed to open " << xda_file_name << "\n";
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Dummy storage to jump lines
     char dummy[101];
     // Ignore file format
     infile.getline(dummy, 100);
     // Get number of elements
     infile >> n_element;
     // Ignore rest of line
     infile.getline(dummy, 100);
     // Get number of nodes
     infile >> n_node;
     // Ignore rest of line
     infile.getline(dummy, 100);
     // Ignore sum of element weights (whatever that is...)
     infile.getline(dummy, 100);
     // Get number of enumerated boundary faces on which boundary conditions
     // are applied.
     infile >> n_bound_face;
     // Keep reading until "Title String"
     while (dummy[0] != 'T')
     {
       infile.getline(dummy, 100);
     }
     // Make space for nodes and elements
     Node_pt.resize(n_node);
     Element_pt.resize(n_element);
     // Read first line with node labels and count them
     std::string line;
     std::getline(infile, line);
     std::istringstream ostr(line);
     std::istream_iterator<std::string> it(ostr);
     std::istream_iterator<std::string> end;
     unsigned nnod_el = 0;
     Vector<unsigned> first_node;
     while (it != end)
     {
       first_node.push_back(atoi((*it).c_str()));
       it++;
       nnod_el++;
     }
     // Check
     if (nnod_el != 10)
     {
       std::ostringstream error_stream;
       error_stream
         << "XdaTetMesh can currently only be built with quadratic tets "
         << "with 10 nodes. The specified mesh file has " << nnod_el
         << "nodes per element.\n";
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Storage for the global node numbers listed element-by-element
     Vector<unsigned> global_node(n_element * nnod_el);
     // Read in nodes
     unsigned k = 0;
     // Copy across first nodes
     for (unsigned j = 0; j < nnod_el; j++)
     {
       global_node[k] = first_node[k];
       k++;
     }
     // Read the other ones
     for (unsigned i = 1; i < n_element; i++)
     {
       for (unsigned j = 0; j < nnod_el; j++)
       {
         infile >> global_node[k];
         k++;
       }
       infile.getline(dummy, 100);
     }
     // Create storage for coordinates
     Vector<double> x_node(n_node);
     Vector<double> y_node(n_node);
     Vector<double> z_node(n_node);
     // Get nodal coordinates
     for (unsigned i = 0; i < n_node; i++)
     {
       infile >> x_node[i];
       infile >> y_node[i];
       infile >> z_node[i];
     }
     // Read in boundaries for faces
     unsigned element_nmbr;
     unsigned bound_id;
     unsigned side_nmbr;
     unsigned max_bound = 0;
     // Make space for enumeration of sub-boundaries
     Boundary_id.resize(n_bound_face + 1);
     // Counter for number of separate boundary faces
     unsigned count = 0;
     Vector<std::set<unsigned>> boundary_id(n_node);
     for (unsigned i = 0; i < n_bound_face; i++)
     {
       // Number of the element
       infile >> element_nmbr;
       // Which side/face on the tet are we dealing with (xda enumeratation)?
       infile >> side_nmbr;
       // What's the boundary ID?
       infile >> bound_id;
       // Turn into zero-based oomph-lib mesh boundary id
       unsigned oomph_lib_bound_id = bound_id - 1;
       oomph_lib_bound_id = count;
       Boundary_id[bound_id].push_back(count);
       // Increment number of separate boundary faces
       count++;
       // Get ready for allocation of total number of boundaries
       if (oomph_lib_bound_id > max_bound) max_bound = oomph_lib_bound_id;
       // Identify the "side nodes" (i.e. the nodes on the faces of
       // the bulk tet) according to the
       // conventions in '.xda' mesh files so that orientation of the
       // faces is always the same (required for computation of
       // outer unit normals
       Vector<unsigned> side_node(6);
       switch (side_nmbr)
       {
         case 0:
           side_node[0] = global_node[nnod_el * element_nmbr + 1];
           side_node[1] = global_node[nnod_el * element_nmbr];
           side_node[2] = global_node[nnod_el * element_nmbr + 2];
           side_node[3] = global_node[nnod_el * element_nmbr + 4];
           side_node[4] = global_node[nnod_el * element_nmbr + 6];
           side_node[5] = global_node[nnod_el * element_nmbr + 5];
           break;
         case 1:
           side_node[0] = global_node[nnod_el * element_nmbr];
           side_node[1] = global_node[nnod_el * element_nmbr + 1];
           side_node[2] = global_node[nnod_el * element_nmbr + 3];
           side_node[3] = global_node[nnod_el * element_nmbr + 4];
           side_node[4] = global_node[nnod_el * element_nmbr + 8];
           side_node[5] = global_node[nnod_el * element_nmbr + 7];
           break;
         case 2:
           side_node[0] = global_node[nnod_el * element_nmbr + 1];
           side_node[1] = global_node[nnod_el * element_nmbr + 2];
           side_node[2] = global_node[nnod_el * element_nmbr + 3];
           side_node[3] = global_node[nnod_el * element_nmbr + 5];
           side_node[4] = global_node[nnod_el * element_nmbr + 9];
           side_node[5] = global_node[nnod_el * element_nmbr + 8];
           break;
         case 3:
           side_node[0] = global_node[nnod_el * element_nmbr + 2];
           side_node[1] = global_node[nnod_el * element_nmbr];
           side_node[2] = global_node[nnod_el * element_nmbr + 3];
           side_node[3] = global_node[nnod_el * element_nmbr + 6];
           side_node[4] = global_node[nnod_el * element_nmbr + 7];
           side_node[5] = global_node[nnod_el * element_nmbr + 9];
           break;
         default:
           throw OomphLibError(
             "Unexcpected side number in your '.xda' input file\n",
             OOMPH_CURRENT_FUNCTION,
             OOMPH_EXCEPTION_LOCATION);
       }
       // Associate boundaries with nodes
       for (unsigned j = 0; j < 6; j++)
       {
         boundary_id[side_node[j]].insert(oomph_lib_bound_id);
       }
     }
     // Set number of boundaries
     set_nboundary(max_bound + 1);
     // Vector of bools, will tell us if we already visited a node
     std::vector<bool> done(n_node, false);
     Vector<unsigned> translate(n_node);
     translate[0] = 0;
     translate[1] = 2;
     translate[2] = 1;
     translate[3] = 3;
     translate[4] = 5;
     translate[5] = 7;
     translate[6] = 4;
     translate[7] = 6;
     translate[8] = 8;
     translate[9] = 9;
     // Create the elements
     unsigned node_count = 0;
     for (unsigned e = 0; e < n_element; e++)
     {
       Element_pt[e] = new ELEMENT;
       // Loop over all nodes
       for (unsigned j = 0; j < nnod_el; j++)
       {
         unsigned j_global = global_node[node_count];
         if (done[j_global] == false)
         {
           if (boundary_id[j_global].size() == 0)
           {
             Node_pt[j_global] = finite_element_pt(e)->construct_node(
               translate[j], time_stepper_pt);
           }
           else
           {
             Node_pt[j_global] = finite_element_pt(e)->construct_boundary_node(
               translate[j], time_stepper_pt);
             for (std::set<unsigned>::iterator it =
                    boundary_id[j_global].begin();
                  it != boundary_id[j_global].end();
                  it++)
             {
               add_boundary_node(*it, Node_pt[j_global]);
             }
           }
           done[j_global] = true;
           Node_pt[j_global]->x(0) = x_node[j_global];
           Node_pt[j_global]->x(1) = y_node[j_global];
           Node_pt[j_global]->x(2) = z_node[j_global];
         }
         else
         {
           finite_element_pt(e)->node_pt(translate[j]) = Node_pt[j_global];
         }
         node_count++;
       }
     }
     // Figure out which elements are next to the boundaries.
     setup_boundary_element_info();
     // Setup boundary coordinates
     unsigned nb = nboundary();
     for (unsigned b = 0; b < nb; b++)
     {
       bool switch_normal = false;
       setup_boundary_coordinates(b, switch_normal);
     }
   }
References b, e(), Eigen::placeholders::end, i, j, k, calibrate::line, nb, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, size, and oomph::Global_string_for_annotation::string().
Member Function Documentation
nxda_boundary()
template<class ELEMENT > unsigned oomph::XdaTetMesh< ELEMENT >::nxda_boundary () inline
Access function to the number of distinct boundaries specified in the original xda enumeration.
     {
       return Boundary_id.size();
     }
References oomph::XdaTetMesh< ELEMENT >::Boundary_id.
oomph_lib_boundary_ids()
template<class ELEMENT > Vector<unsigned> oomph::XdaTetMesh< ELEMENT >::oomph_lib_boundary_ids (const unsigned & xda_boundary_id) inline
Access functions to the Vector of oomph-lib boundary ids that make up boundary b in the original xda enumeration
     {
       return Boundary_id[xda_boundary_id];
     }
References oomph::XdaTetMesh< ELEMENT >::Boundary_id.
setup_boundary_coordinates() [1/2]
template<class ELEMENT > void oomph::XdaTetMesh< ELEMENT >::setup_boundary_coordinates (const unsigned & b, const bool & switch_normal) inline
Setup boundary coordinate on boundary b while is temporarily flattened to simplex faces. Boundary coordinates are the x-y coordinates in the plane of that boundary with the x-axis along the line from the (lexicographically) "lower left" to the "upper right" node. The y axis is obtained by taking the cross-product of the positive x direction with the outer unit normal computed by the face elements (or its negative if switch_normal is set to true).
     {
       std::ofstream outfile;
       setup_boundary_coordinates(b, switch_normal, outfile);
     }
References b.
setup_boundary_coordinates() [2/2]
template<class ELEMENT > void oomph::XdaTetMesh< ELEMENT >::setup_boundary_coordinates (const unsigned & b, const bool & switch_normal, std::ofstream & outfile)
Setup boundary coordinate on boundary b while is temporarily flattened to simplex faces. Boundary coordinates are the x-y coordinates in the plane of that boundary with the x-axis along the line from the (lexicographically) "lower left" to the "upper right" node. The y axis is obtained by taking the cross-product of the positive x direction with the outer unit normal computed by the face elements (or its negative if switch_normal is set to true). Doc faces in output file.
   {
     // Temporary storage for face elements
     Vector<FiniteElement*> face_el_pt;
     // Backup for nodal positions
     std::map<Node*, Vector<double>> backup_position;
     // Loop over all elements on boundaries
     unsigned nel = this->nboundary_element(b);
     if (nel > 0)
     {
       // Loop over the bulk elements adjacent to boundary b
       for (unsigned e = 0; e < nel; e++)
       {
         // Get pointer to the bulk element that is adjacent to boundary b
         FiniteElement* bulk_elem_pt = this->boundary_element_pt(b, e);
         // Find the index of the face of element e along boundary b
         int face_index = this->face_index_at_boundary(b, e);
         // Create new face element
         DummyFaceElement<ELEMENT>* el_pt =
           new DummyFaceElement<ELEMENT>(bulk_elem_pt, face_index);
         face_el_pt.push_back(el_pt);
         // Backup nodal position
         Vector<double> pos(3);
         for (unsigned j = 3; j < 6; j++)
         {
           if (backup_position[el_pt->node_pt(j)].size() == 0)
           {
             el_pt->node_pt(j)->position(pos);
             backup_position[el_pt->node_pt(j)] = pos;
           }
         }
         // Temporarily flatten the element to a simplex
         for (unsigned i = 0; i < 3; i++)
         {
           // Node 3 is between vertex nodes 0 and 1
           el_pt->node_pt(3)->x(i) =
             0.5 * (el_pt->node_pt(0)->x(i) + el_pt->node_pt(1)->x(i));
           // Node 4 is between vertex nodes 1 and 2
           el_pt->node_pt(4)->x(i) =
             0.5 * (el_pt->node_pt(1)->x(i) + el_pt->node_pt(2)->x(i));
           // Node 5 is between vertex nodes 2 and 0
           el_pt->node_pt(5)->x(i) =
             0.5 * (el_pt->node_pt(2)->x(i) + el_pt->node_pt(0)->x(i));
         }
         // Output faces?
         if (outfile.is_open())
         {
           face_el_pt[face_el_pt.size() - 1]->output(outfile);
         }
       }
       // Loop over all nodes to find the lower left and upper right ones
       Node* lower_left_node_pt = this->boundary_node_pt(b, 0);
       Node* upper_right_node_pt = this->boundary_node_pt(b, 0);
       // Loop over all nodes on the boundary
       unsigned nnod = this->nboundary_node(b);
       for (unsigned j = 0; j < nnod; j++)
       {
         // Get node
         Node* nod_pt = this->boundary_node_pt(b, j);
         // Primary criterion for lower left: Does it have a lower z-coordinate?
         if (nod_pt->x(2) < lower_left_node_pt->x(2))
         {
           lower_left_node_pt = nod_pt;
         }
         // ...or is it a draw?
         else if (nod_pt->x(2) == lower_left_node_pt->x(2))
         {
           // If it's a draw: Does it have a lower y-coordinate?
           if (nod_pt->x(1) < lower_left_node_pt->x(1))
           {
             lower_left_node_pt = nod_pt;
           }
           // ...or is it a draw?
           else if (nod_pt->x(1) == lower_left_node_pt->x(1))
           {
             // If it's a draw: Does it have a lower x-coordinate?
             if (nod_pt->x(0) < lower_left_node_pt->x(0))
             {
               lower_left_node_pt = nod_pt;
             }
           }
         }
         // Primary criterion for upper right: Does it have a higher
         // z-coordinate?
         if (nod_pt->x(2) > upper_right_node_pt->x(2))
         {
           upper_right_node_pt = nod_pt;
         }
         // ...or is it a draw?
         else if (nod_pt->x(2) == upper_right_node_pt->x(2))
         {
           // If it's a draw: Does it have a higher y-coordinate?
           if (nod_pt->x(1) > upper_right_node_pt->x(1))
           {
             upper_right_node_pt = nod_pt;
           }
           // ...or is it a draw?
           else if (nod_pt->x(1) == upper_right_node_pt->x(1))
           {
             // If it's a draw: Does it have a higher x-coordinate?
             if (nod_pt->x(0) > upper_right_node_pt->x(0))
             {
               upper_right_node_pt = nod_pt;
             }
           }
         }
       }
       // Prepare storage for boundary coordinates
       Vector<double> zeta(2);
       // Unit vector connecting lower left and upper right nodes
       Vector<double> b0(3);
       b0[0] = upper_right_node_pt->x(0) - lower_left_node_pt->x(0);
       b0[1] = upper_right_node_pt->x(1) - lower_left_node_pt->x(1);
       b0[2] = upper_right_node_pt->x(2) - lower_left_node_pt->x(2);
       // Normalise
       double inv_length =
         1.0 / sqrt(b0[0] * b0[0] + b0[1] * b0[1] + b0[2] * b0[2]);
       b0[0] *= inv_length;
       b0[1] *= inv_length;
       b0[2] *= inv_length;
       // Get (outer) unit normal to first face element
       Vector<double> normal(3);
       Vector<double> s(2, 0.0);
       dynamic_cast<DummyFaceElement<ELEMENT>*>(face_el_pt[0])
         ->outer_unit_normal(s, normal);
       if (switch_normal)
       {
         normal[0] = -normal[0];
         normal[1] = -normal[1];
         normal[2] = -normal[2];
       }
 #ifdef PARANOID
       // Check that all elements have the same normal
       for (unsigned e = 0; e < nel; e++)
       {
         // Get (outer) unit normal to face element
         Vector<double> my_normal(3);
         dynamic_cast<DummyFaceElement<ELEMENT>*>(face_el_pt[0])
           ->outer_unit_normal(s, my_normal);
         // Dot product should be one!
         double error = normal[0] * my_normal[0] + normal[1] * my_normal[1] +
                        normal[2] * my_normal[2];
         error -= 1.0;
         if (switch_normal) error += 1.0;
         if (error > Tolerance_for_boundary_finding)
         {
           std::ostringstream error_message;
           error_message
             << "Error in alingment of normals (dot product-1) " << error
             << " for element " << e << std::endl
             << "exceeds tolerance specified by the static member data\n"
             << "TetMeshBase::Tolerance_for_boundary_finding = "
             << Tolerance_for_boundary_finding << std::endl
             << "This usually means that the boundary is not planar.\n\n"
             << "You can suppress this error message by recompiling \n"
             << "recompiling without PARANOID or by changing the tolerance.\n";
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
       }
 #endif
       // Cross-product to get second in-plane vector, normal to b0
       Vector<double> b1(3);
       b1[0] = b0[1] * normal[2] - b0[2] * normal[1];
       b1[1] = b0[2] * normal[0] - b0[0] * normal[2];
       b1[2] = b0[0] * normal[1] - b0[1] * normal[0];
       // Assign boundary coordinates: projection onto the axes
       for (unsigned j = 0; j < nnod; j++)
       {
         // Get node
         Node* nod_pt = this->boundary_node_pt(b, j);
         // Difference vector to lower left corner
         Vector<double> delta(3);
         delta[0] = nod_pt->x(0) - lower_left_node_pt->x(0);
         delta[1] = nod_pt->x(1) - lower_left_node_pt->x(1);
         delta[2] = nod_pt->x(2) - lower_left_node_pt->x(2);
         // Project
         zeta[0] = delta[0] * b0[0] + delta[1] * b0[1] + delta[2] * b0[2];
         zeta[1] = delta[0] * b1[0] + delta[1] * b1[1] + delta[2] * b1[2];
 #ifdef PARANOID
         // Check:
         double error = pow(lower_left_node_pt->x(0) + zeta[0] * b0[0] +
                              zeta[1] * b1[0] - nod_pt->x(0),
                            2) +
                        pow(lower_left_node_pt->x(1) + zeta[0] * b0[1] +
                              zeta[1] * b1[1] - nod_pt->x(1),
                            2) +
                        pow(lower_left_node_pt->x(2) + zeta[0] * b0[2] +
                              zeta[1] * b1[2] - nod_pt->x(2),
                            2);
         if (sqrt(error) > Tolerance_for_boundary_finding)
         {
           std::ostringstream error_message;
           error_message
             << "Error in setup of boundary coordinate " << sqrt(error)
             << std::endl
             << "exceeds tolerance specified by the static member data\n"
             << "TetMeshBase::Tolerance_for_boundary_finding = "
             << Tolerance_for_boundary_finding << std::endl
             << "This usually means that the boundary is not planar.\n\n"
             << "You can suppress this error message by recompiling \n"
             << "recompiling without PARANOID or by changing the tolerance.\n";
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         // Set boundary coordinate
         nod_pt->set_coordinates_on_boundary(b, zeta);
       }
     }
     // Indicate that boundary coordinate has been set up
     Boundary_coordinate_exists[b] = true;
     // Cleanup
     unsigned n = face_el_pt.size();
     for (unsigned e = 0; e < n; e++)
     {
       delete face_el_pt[e];
     }
     // Reset nodal position
     for (std::map<Node*, Vector<double>>::iterator it = backup_position.begin();
          it != backup_position.end();
          it++)
     {
       Node* nod_pt = (*it).first;
       Vector<double> pos((*it).second);
       for (unsigned i = 0; i < 3; i++)
       {
         nod_pt->x(i) = pos[i];
       }
     }
   }
References b, MultiOpt::delta, e(), calibrate::error, i, j, n, oomph::FiniteElement::node_pt(), WallFunction::normal(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Node::position(), Eigen::bfloat16_impl::pow(), s, oomph::Node::set_coordinates_on_boundary(), sqrt(), oomph::Node::x(), and Eigen::zeta().
Member Data Documentation
Boundary_id
template<class ELEMENT > Vector<Vector<unsigned> > oomph::XdaTetMesh< ELEMENT >::Boundary_id private
Vector of vectors containing the boundary IDs of the overall boundary specified in the xda file.
Referenced by oomph::XdaTetMesh< ELEMENT >::nxda_boundary(), and oomph::XdaTetMesh< ELEMENT >::oomph_lib_boundary_ids().
The documentation for this class was generated from the following files:
xda_tet_mesh.template.h
xda_tet_mesh.template.cc