MercuryDPM: oomph::RefineableLinearisedNavierStokesEquations Class Reference
oomph::RefineableLinearisedNavierStokesEquations Class Reference abstract
#include <refineable_linearised_navier_stokes_elements.h>
Public Member Functions
RefineableLinearisedNavierStokesEquations ()
Empty Constructor.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
void further_build ()
Further build: pass the pointers down to the sons.
Public Member Functions inherited from oomph::LinearisedNavierStokesEquations
LinearisedNavierStokesEquations ()
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
const double & lambda () const
const double & omega () const
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
double *& lambda_pt ()
Pointer to lambda.
double *& omega_pt ()
Pointer to frequency.
LinearisedNavierStokesEigenfunctionNormalisationElement * normalisation_element_pt ()
Pointer to normalisation element.
void set_eigenfunction_normalisation_element (LinearisedNavierStokesEigenfunctionNormalisationElement *const &normalisation_el_pt)
the boolean flag check_nodal_data is set to false.
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to the viscosity ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to the density ratio.
virtual unsigned npres_linearised_nst () const =0
virtual unsigned u_index_linearised_nst (const unsigned &i) const
double du_dt_linearised_nst (const unsigned &n, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
virtual double p_linearised_nst (const unsigned &n_p, const unsigned &i) const =0
virtual void pin_real_or_imag (const unsigned &real)=0
virtual void unpin_real_or_imag (const unsigned &real)=0
virtual void pin_pressure_normalisation_dofs ()=0
Pin the normalisation dofs.
virtual int p_index_linearised_nst (const unsigned &i) const
Which nodal value represents the pressure?
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate, const unsigned &real) const
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &nplot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
double interpolated_u_linearised_nst (const Vector< double > &s, const unsigned &i) const
double interpolated_p_linearised_nst (const Vector< double > &s, const unsigned &i) const
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
virtual unsigned required_nsons () const
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)=0
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void rebuild_from_sons (Mesh *&mesh_pt)=0
virtual void unbuild ()
virtual void deactivate_element ()
virtual bool nodes_built ()
Return true if all the nodes have been built, false if not.
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual unsigned ncont_interpolated_values () const =0
virtual void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
virtual void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)=0
virtual Node * interpolating_node_pt (const unsigned &n, const int &value_id)
virtual double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
virtual Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
virtual unsigned ninterpolating_node (const int &value_id)
virtual unsigned ninterpolating_node_1d (const int &value_id)
virtual void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
virtual void check_integrity (double &max_error)=0
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual RefineableElement * root_element_pt ()
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
virtual void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
virtual void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
Pre-build the element.
virtual void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
virtual void further_setup_hanging_nodes ()
void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
unsigned nshape_controlling_nodes ()
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Public Member Functions inherited from oomph::ElementWithZ2ErrorEstimator
ElementWithZ2ErrorEstimator ()
Default empty constructor.
ElementWithZ2ErrorEstimator (const ElementWithZ2ErrorEstimator &)=delete
Broken copy constructor.
void operator= (const ElementWithZ2ErrorEstimator &)=delete
Broken assignment operator.
virtual unsigned ncompound_fluxes ()
virtual void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
virtual void get_Z2_compound_flux_indices (Vector< unsigned > &flux_index)
virtual unsigned nvertex_node () const =0
Number of vertex nodes in the element.
virtual Node * vertex_node_pt (const unsigned &j) const =0
virtual unsigned nrecovery_order ()=0
Order of recovery shape functions.
virtual double geometric_jacobian (const Vector< double > &x)
Static Public Member Functions
static void pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > &element_pt)
static void unpin_all_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in Vector.
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Protected Member Functions
virtual Node * pressure_node_pt (const unsigned &n_p)
virtual void unpin_elemental_pressure_dofs ()=0
Unpin all pressure dofs in the element.
virtual void pin_elemental_redundant_nodal_pressure_dofs ()
Protected Member Functions inherited from oomph::LinearisedNavierStokesEquations
virtual int p_local_eqn (const unsigned &n, const unsigned &i)=0
virtual double dshape_and_dtest_eulerian_linearised_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_linearised_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual void pshape_linearised_nst (const Vector< double > &s, Shape &psi) const =0
Compute the pressure shape functions at local coordinate s.
virtual void pshape_linearised_nst (const Vector< double > &s, Shape &psi, Shape &test) const =0
Compute the pressure shape and test functions at local coordinate s.
virtual void get_base_flow_u (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result) const
virtual void get_base_flow_dudx (const double &time, const unsigned &ipt, const Vector< double > &x, DenseMatrix< double > &result) const
int eigenvalue_local_eqn (const unsigned &i)
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Private Member Functions
void fill_in_generic_residual_contribution_linearised_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Attributes inherited from oomph::LinearisedNavierStokesEquations
void(*&)(const double &time, const Vector< double > &x, Vector< double > &f) base_flow_u_fct_pt ()
Access function for the base flow solution pointer.
void(*&)(const double &time, const Vector< double > &x, DenseMatrix< double > &f) base_flow_dudx_fct_pt ()
Static Public Attributes inherited from oomph::LinearisedNavierStokesEquations
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Protected Attributes inherited from oomph::LinearisedNavierStokesEquations
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
double * Lambda_pt
Pointer to eigenvalue.
double * Omega_pt
Pointer to frequency.
LinearisedNavierStokesEigenfunctionNormalisationElement * Normalisation_element_pt
Pointer to the normalisation element.
unsigned Data_number_of_eigenvalue
Index of datum where eigenvalue is stored.
unsigned Index_of_eigenvalue
void(* Base_flow_u_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
Pointer to base flow solution (velocity components) function.
void(* Base_flow_dudx_fct_pt)(const double &time, const Vector< double > &x, DenseMatrix< double > &result)
bool ALE_is_disabled
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number – for plotting/validation purposes.
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Detailed Description
Refineable version of the linearised axisymmetric Navier–Stokes equations
Constructor & Destructor Documentation
RefineableLinearisedNavierStokesEquations()
oomph::RefineableLinearisedNavierStokesEquations::RefineableLinearisedNavierStokesEquations () inline
Empty Constructor.
       : LinearisedNavierStokesEquations(),
         RefineableElement(),
         ElementWithZ2ErrorEstimator()
     {
     }
Member Function Documentation
fill_in_generic_residual_contribution_linearised_nst()
void oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) private virtual
Add element's contribution to the elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector
Compute the residuals for the refineable linearised axisymmetric Navier–Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented from oomph::LinearisedNavierStokesEquations.
   {
     // Get the time from the first node in the element
     const double time = this->node_pt(0)->time_stepper_pt()->time();
     // Determine number of nodes in the element
     const unsigned n_node = nnode();
     // Determine how many pressure values there are associated with
     // a single pressure component
     const unsigned n_pres = npres_linearised_nst();
     const unsigned n_veloc = 4 * DIM;
     // Get the nodal indices at which the velocity is stored
     unsigned u_nodal_index[n_veloc];
     for (unsigned i = 0; i < n_veloc; ++i)
     {
       u_nodal_index[i] = u_index_linearised_nst(i);
     }
     // Which nodal values represent the two pressure components?
     // (Negative if pressure is not based on nodal interpolation).
     Vector<int> p_index(2);
     for (unsigned i = 0; i < 2; i++)
     {
       p_index[i] = this->p_index_linearised_nst(i);
     }
     // Local array of booleans that are true if the l-th pressure value is
     // hanging (avoid repeated virtual function calls)
     bool pressure_dof_is_hanging[n_pres];
     // If the pressure is stored at a node
     if (p_index[0] >= 0)
     {
       // Read out whether the pressure is hanging
       for (unsigned l = 0; l < n_pres; ++l)
       {
         pressure_dof_is_hanging[l] =
           pressure_node_pt(l)->is_hanging(p_index[0]);
       }
     }
     // Otherwise the pressure is not stored at a node and so cannot hang
     else
     {
       for (unsigned l = 0; l < n_pres; ++l)
       {
         pressure_dof_is_hanging[l] = false;
       }
     }
     // Set up memory for the fluid shape and test functions
     Shape psif(n_node), testf(n_node);
     DShape dpsifdx(n_node, DIM), dtestfdx(n_node, DIM);
     // Set up memory for the pressure shape and test functions
     Shape psip(n_pres), testp(n_pres);
     // Determine number of integration points
     const unsigned n_intpt = integral_pt()->nweight();
     // Set up memory for the vector to hold local coordinates (two dimensions)
     Vector<double> s(DIM);
     // Get physical variables from the element
     // (Reynolds number must be multiplied by the density ratio)
     const double scaled_re = re() * density_ratio();
     const double scaled_re_st = re_st() * density_ratio();
     const double visc_ratio = viscosity_ratio();
     const double eval_real = lambda();
     const double eval_imag = omega();
     const std::complex<double> eigenvalue(eval_real, eval_imag);
     // Integers used to store the local equation numbers
     int local_eqn = 0;
     // Local storage for pointers to hang info objects
     HangInfo* hang_info_pt = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of the local coordinates s
       for (unsigned i = 0; i < DIM; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       const double w = integral_pt()->weight(ipt);
       // Calculate the fluid shape and test functions, and their derivatives
       // w.r.t. the global coordinates
       const double J = dshape_and_dtest_eulerian_at_knot_linearised_nst(
         ipt, psif, dpsifdx, testf, dtestfdx);
       // Calculate the pressure shape and test functions
       pshape_linearised_nst(s, psip, testp);
       // Premultiply the weights and the Jacobian of the mapping between
       // local and global coordinates
       const double W = w * J;
       // Allocate storage for the position and the derivative of the
       // mesh positions w.r.t. time
       Vector<double> interpolated_x(DIM, 0.0);
       // Vector<double> mesh_velocity(2,0.0);
       // Allocate storage for the velocity components (six of these)
       // and their derivatives w.r.t. time
       Vector<std::complex<double>> interpolated_u(DIM);
       // Vector<double> dudt(6,0.0);
       // Allocate storage for the eigen function normalisation
       Vector<std::complex<double>> interpolated_u_normalisation(DIM);
       for (unsigned i = 0; i < DIM; ++i)
       {
         interpolated_u[i].real(0.0);
         interpolated_u[i].imag(0.0);
         interpolated_u_normalisation[i].real(0.0);
         interpolated_u_normalisation[i].imag(0.0);
       }
       // Allocate storage for the pressure components (two of these
       std::complex<double> interpolated_p(0.0, 0.0);
       std::complex<double> interpolated_p_normalisation(0.0, 0.0);
       // Allocate storage for the derivatives of the velocity components
       // w.r.t. global coordinates (r and z)
       Vector<Vector<std::complex<double>>> interpolated_dudx(DIM);
       for (unsigned i = 0; i < DIM; ++i)
       {
         interpolated_dudx[i].resize(DIM);
         for (unsigned j = 0; j < DIM; ++j)
         {
           interpolated_dudx[i][j].real(0.0);
           interpolated_dudx[i][j].imag(0.0);
         }
       }
       // Calculate pressure at the integration point
       // -------------------------------------------
       // Loop over pressure degrees of freedom (associated with a single
       // pressure component) in the element
       for (unsigned l = 0; l < n_pres; l++)
       {
         // Cache the shape function
         const double psip_ = psip(l);
         // Get the complex nodal pressure values
         const std::complex<double> p_value(this->p_linearised_nst(l, 0),
                                            this->p_linearised_nst(l, 1));
         // Add contribution
         interpolated_p += p_value * psip_;
         // Repeat for normalisation
         const std::complex<double> p_norm_value(this->p_linearised_nst(l, 2),
                                                 this->p_linearised_nst(l, 3));
         interpolated_p_normalisation += p_norm_value * psip_;
       }
       // End of loop over the pressure degrees of freedom in the element
       // Calculate velocities and their derivatives at the integration point
       // -------------------------------------------------------------------
       // Loop over the element's nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Cache the shape function
         const double psif_ = psif(l);
         // Loop over the DIM coordinate directions
         for (unsigned i = 0; i < DIM; i++)
         {
           interpolated_x[i] += this->nodal_position(l, i) * psif_;
         }
         // Loop over the DIM complex velocity components
         for (unsigned i = 0; i < DIM; i++)
         {
           // Get the value
           const std::complex<double> u_value(
             this->nodal_value(l, u_nodal_index[2 * i + 0]),
             this->nodal_value(l, u_nodal_index[2 * i + 1]));
           // Add contribution
           interpolated_u[i] += u_value * psif_;
           // Add contribution to dudt
           // dudt[i] += du_dt_linearised_nst(l,i)*psif_;
           // Loop over two coordinate directions (for derivatives)
           for (unsigned j = 0; j < DIM; j++)
           {
             interpolated_dudx[i][j] += u_value * dpsifdx(l, j);
           }
           // Interpolate the normalisation function
           const std::complex<double> normalisation_value(
             this->nodal_value(l, u_nodal_index[2 * (DIM + i)]),
             this->nodal_value(l, u_nodal_index[2 * (DIM + i) + 1]));
           interpolated_u_normalisation[i] += normalisation_value * psif_;
         }
       } // End of loop over the element's nodes
       // Get the mesh velocity if ALE is enabled
       /*if(!ALE_is_disabled)
        {
         // Loop over the element's nodes
         for(unsigned l=0;l<n_node;l++)
          {
           // Loop over the two coordinate directions
           for(unsigned i=0;i<2;i++)
            {
             mesh_velocity[i] += this->raw_dnodal_position_dt(l,i)*psif(l);
            }
          }
          }*/
       // Get velocities and their derivatives from base flow problem
       // -----------------------------------------------------------
       // Allocate storage for the velocity components of the base state
       // solution (initialise to zero)
       Vector<double> base_flow_u(DIM, 0.0);
       // Get the user-defined base state solution velocity components
       get_base_flow_u(time, ipt, interpolated_x, base_flow_u);
       // Allocate storage for the derivatives of the base state solution's
       // velocity components w.r.t. global coordinate (r and z)
       // N.B. the derivatives of the base flow components w.r.t. the
       // azimuthal coordinate direction (theta) are always zero since the
       // base flow is axisymmetric
       DenseMatrix<double> base_flow_dudx(DIM, DIM, 0.0);
       // Get the derivatives of the user-defined base state solution
       // velocity components w.r.t. global coordinates
       get_base_flow_dudx(time, ipt, interpolated_x, base_flow_dudx);
       // MOMENTUM EQUATIONS
       //------------------
       // Number of master nodes
       unsigned n_master = 1;
       // Storage for the weight of the shape function
       double hang_weight = 1.0;
       // Loop over the test functions
       for (unsigned l = 0; l < n_node; l++)
       {
         // Local boolean to indicate whether the node is hanging
         bool is_node_hanging = node_pt(l)->is_hanging();
         if (is_node_hanging)
         {
           hang_info_pt = node_pt(l)->hanging_pt();
           // Read out number of master nodes from hanging data
           n_master = hang_info_pt->nmaster();
         }
         // Otherwise the node is its own master
         else
         {
           n_master = 1;
         }
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // Loop over the velocity components
           for (unsigned i = 0; i < DIM; i++)
           {
             // Assemble the residuals
             // Time dependent term
             std::complex<double> residual_contribution =
               -scaled_re_st * eigenvalue * interpolated_u[i] * testf[l] * W;
             // Pressure term
             residual_contribution += interpolated_p * dtestfdx(l, i) * W;
             // Viscous terms
             for (unsigned k = 0; k < DIM; ++k)
             {
               residual_contribution -=
                 visc_ratio *
                 (interpolated_dudx[i][k] + Gamma[i] * interpolated_dudx[k][i]) *
                 dtestfdx(l, k) * W;
             }
             // Advective terms
             for (unsigned k = 0; k < DIM; ++k)
             {
               residual_contribution -=
                 scaled_re *
                 (base_flow_u[k] * interpolated_dudx[i][k] +
                  interpolated_u[k] * base_flow_dudx(i, k)) *
                 testf[l] * W;
             }
             // Now separate real and imaginary parts
             if (is_node_hanging)
             {
               local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                                u_nodal_index[2 * i]);
               hang_weight = hang_info_pt->master_weight(m);
             }
             // If node is not hanging number or not
             else
             {
               local_eqn = nodal_local_eqn(l, u_nodal_index[2 * i]);
               hang_weight = 1.0;
             }
             if (local_eqn >= 0)
             {
               residuals[local_eqn] +=
                 residual_contribution.real() * hang_weight;
             }
             if (is_node_hanging)
             {
               local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                                u_nodal_index[2 * i + 1]);
               hang_weight = hang_info_pt->master_weight(m);
             }
             // If node is not hanging number or not
             else
             {
               local_eqn = nodal_local_eqn(l, u_nodal_index[2 * i + 1]);
               hang_weight = 1.0;
             }
             if (local_eqn >= 0)
             {
               residuals[local_eqn] +=
                 residual_contribution.imag() * hang_weight;
             }
             // CALCULATE THE JACOBIAN
             /*if(flag)
               {
               //Loop over the velocity shape functions again
               for(unsigned l2=0;l2<n_node;l2++)
               {
               //Loop over the velocity components again
               for(unsigned i2=0;i2<DIM;i2++)
               {
               //If at a non-zero degree of freedom add in the entry
               local_unknown = nodal_local_eqn(l2,u_nodal_index[i2]);
               if(local_unknown >= 0)
               {
               //Add contribution to Elemental Matrix
               jacobian(local_eqn,local_unknown)
               -= visc_ratio*Gamma[i]*dpsifdx(l2,i)*dtestfdx(l,i2)*W;
               //Extra component if i2 = i
               if(i2 == i)
               {
               //Loop over velocity components
               for(unsigned k=0;k<DIM;k++)
               {
               jacobian(local_eqn,local_unknown)
               -= visc_ratio*dpsifdx(l2,k)*dtestfdx(l,k)*W;
               }
               }
               //Now add in the inertial terms
               jacobian(local_eqn,local_unknown)
               -= scaled_re*psif[l2]*interpolated_dudx(i,i2)*testf[l]*W;
               //Extra component if i2=i
               if(i2 == i)
               {
               //Add the mass matrix term (only diagonal entries)
               //Note that this is positive because the mass matrix
               //is taken to the other side of the equation when
               //formulating the generalised eigenproblem.
               if(flag==2)
               {
               mass_matrix(local_eqn,local_unknown) +=
               scaled_re_st*psif[l2]*testf[l]*W;
               }
               //du/dt term
               jacobian(local_eqn,local_unknown)
               -= scaled_re_st*
               node_pt(l2)->time_stepper_pt()->weight(1,0)*
               psif[l2]*testf[l]*W;
               //Loop over the velocity components
               for(unsigned k=0;k<DIM;k++)
               {
               double tmp=scaled_re*interpolated_u[k];
               if (!ALE_is_disabled) tmp-=scaled_re_st*mesh_velocity[k];
               jacobian(local_eqn,local_unknown) -=
               tmp*dpsifdx(l2,k)*testf[l]*W;
               }
               }
               }
               }
               }
               //Now loop over pressure shape functions
               //This is the contribution from pressure gradient
               for(unsigned l2=0;l2<n_pres;l2++)
               {
               //If we are at a non-zero degree of freedom in the entry
               local_unknown = p_local_eqn(l2);
               if(local_unknown >= 0)
               {
               jacobian(local_eqn,local_unknown)
               += psip[l2]*dtestfdx(l,i)*W;
               }
               }
               } //End of Jacobian calculation
               }*/ //End of if not boundary condition statement
           } // End of loop over dimension
         } // End of loop over master nodes
       } // End of loop over shape functions
       // CONTINUITY EQUATION
       //-------------------
       // Loop over the shape functions
       for (unsigned l = 0; l < n_pres; l++)
       {
         if (pressure_dof_is_hanging[l])
         {
           hang_info_pt = this->pressure_node_pt(l)->hanging_pt(p_index[0]);
           n_master = hang_info_pt->nmaster();
         }
         else
         {
           n_master = 1;
         }
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; ++m)
         {
           // Assemble the residuals
           std::complex<double> residual_contribution = interpolated_dudx[0][0];
           for (unsigned k = 1; k < DIM; ++k)
           {
             residual_contribution += interpolated_dudx[k][k];
           }
           if (pressure_dof_is_hanging[l])
           {
             local_eqn =
               this->local_hang_eqn(hang_info_pt->master_node_pt(m), p_index[0]);
             hang_weight = hang_info_pt->master_weight(m);
           }
           else
           {
             local_eqn = this->p_local_eqn(l, 0);
             hang_weight = 1.0;
           }
           // If not a boundary conditions
           if (local_eqn >= 0)
           {
             residuals[local_eqn] +=
               residual_contribution.real() * testp[l] * W * hang_weight;
           }
           if (pressure_dof_is_hanging[l])
           {
             local_eqn =
               this->local_hang_eqn(hang_info_pt->master_node_pt(m), p_index[1]);
             hang_weight = hang_info_pt->master_weight(m);
           }
           else
           {
             local_eqn = this->p_local_eqn(l, 1);
             hang_weight = 1.0;
           }
           // If not a boundary conditions
           if (local_eqn >= 0)
           {
             residuals[local_eqn] +=
               residual_contribution.imag() * testp[l] * W * hang_weight;
           }
         } // End of loop over master nodes
       } // End of loop over l
       // Normalisation condition. Leave this alone because there is
       // no test function involved.
       std::complex<double> residual_contribution =
         interpolated_p_normalisation * interpolated_p;
       for (unsigned k = 0; k < DIM; ++k)
       {
         residual_contribution +=
           interpolated_u_normalisation[k] * interpolated_u[k];
       }
       local_eqn = this->eigenvalue_local_eqn(0);
       if (local_eqn >= 0)
       {
         residuals[local_eqn] += residual_contribution.real() * W;
       }
       local_eqn = this->eigenvalue_local_eqn(1);
       if (local_eqn >= 0)
       {
         residuals[local_eqn] += residual_contribution.imag() * W;
       }
     } // End of loop over the integration points
   } // End of fill_in_generic_residual_contribution_linearised_nst
References oomph::LinearisedNavierStokesEquations::density_ratio(), DIM, oomph::LinearisedNavierStokesEquations::dshape_and_dtest_eulerian_at_knot_linearised_nst(), oomph::LinearisedNavierStokesEquations::eigenvalue_local_eqn(), oomph::LinearisedNavierStokesEquations::Gamma, oomph::LinearisedNavierStokesEquations::get_base_flow_dudx(), oomph::LinearisedNavierStokesEquations::get_base_flow_u(), oomph::Node::hanging_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::Node::is_hanging(), J, j, k, oomph::Integral::knot(), oomph::LinearisedNavierStokesEquations::lambda(), oomph::RefineableElement::local_hang_eqn(), m, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::LinearisedNavierStokesEquations::npres_linearised_nst(), oomph::Integral::nweight(), oomph::LinearisedNavierStokesEquations::omega(), oomph::LinearisedNavierStokesEquations::p_index_linearised_nst(), oomph::LinearisedNavierStokesEquations::p_linearised_nst(), oomph::LinearisedNavierStokesEquations::p_local_eqn(), pressure_node_pt(), oomph::LinearisedNavierStokesEquations::pshape_linearised_nst(), oomph::LinearisedNavierStokesEquations::re(), oomph::LinearisedNavierStokesEquations::re_st(), s, oomph::TimeStepper::time(), oomph::Data::time_stepper_pt(), oomph::LinearisedNavierStokesEquations::u_index_linearised_nst(), oomph::LinearisedNavierStokesEquations::viscosity_ratio(), w, oomph::QuadTreeNames::W, and oomph::Integral::weight().
further_build()
void oomph::RefineableLinearisedNavierStokesEquations::further_build () inline virtual
Further build: pass the pointers down to the sons.
Reimplemented from oomph::RefineableElement.
Reimplemented in oomph::RefineableLinearisedQCrouzeixRaviartElement.
     {
       // Find the father element
       RefineableLinearisedNavierStokesEquations* cast_father_element_pt =
         dynamic_cast<RefineableLinearisedNavierStokesEquations*>(
           this->father_element_pt());
       // Set the viscosity ratio pointer
       this->Viscosity_Ratio_pt = cast_father_element_pt->viscosity_ratio_pt();
       // Set the density ratio pointer
       this->Density_Ratio_pt = cast_father_element_pt->density_ratio_pt();
       // Set pointer to global Reynolds number
       this->Re_pt = cast_father_element_pt->re_pt();
       // Set pointer to global Reynolds number x Strouhal number (=Womersley)
       this->ReSt_pt = cast_father_element_pt->re_st_pt();
       if (cast_father_element_pt->normalisation_element_pt() != 0)
       {
         // Pass down the normalisation element
         this->set_eigenfunction_normalisation_element(
           cast_father_element_pt->normalisation_element_pt());
       }
       // Set the ALE_is_disabled flag
       this->ALE_is_disabled = cast_father_element_pt->ALE_is_disabled;
     }
References oomph::LinearisedNavierStokesEquations::ALE_is_disabled, oomph::LinearisedNavierStokesEquations::Density_Ratio_pt, oomph::LinearisedNavierStokesEquations::density_ratio_pt(), oomph::RefineableElement::father_element_pt(), oomph::LinearisedNavierStokesEquations::normalisation_element_pt(), oomph::LinearisedNavierStokesEquations::Re_pt, oomph::LinearisedNavierStokesEquations::re_pt(), oomph::LinearisedNavierStokesEquations::re_st_pt(), oomph::LinearisedNavierStokesEquations::ReSt_pt, oomph::LinearisedNavierStokesEquations::set_eigenfunction_normalisation_element(), oomph::LinearisedNavierStokesEquations::Viscosity_Ratio_pt, and oomph::LinearisedNavierStokesEquations::viscosity_ratio_pt().
Referenced by oomph::RefineableLinearisedQCrouzeixRaviartElement::further_build().
get_Z2_flux()
void oomph::RefineableLinearisedNavierStokesEquations::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) inline virtual
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
 #ifdef PARANOID
       unsigned num_entries = 2 * (DIM + ((DIM * DIM) - DIM) / 2);
       if (flux.size() != num_entries)
       {
         std::ostringstream error_message;
         error_message << "The flux vector has the wrong number of entries, "
                       << flux.size() << ", whereas it should be " << num_entries
                       << std::endl;
         throw OomphLibError(
           error_message.str(),
           "RefineableLinearisedNavierStokesEquations::get_Z2_flux()",
           OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Get strain rate matrix
       DenseMatrix<double> real_strainrate(DIM);
       this->strain_rate(s, real_strainrate, 0);
       DenseMatrix<double> imag_strainrate(DIM);
       this->strain_rate(s, imag_strainrate, 1);
       // Pack into flux Vector
       unsigned icount = 0;
       // Start with diagonal terms
       for (unsigned i = 0; i < DIM; i++)
       {
         flux[icount] = real_strainrate(i, i);
         icount++;
       }
       // Off diagonals row by row
       for (unsigned i = 0; i < DIM; i++)
       {
         for (unsigned j = i + 1; j < DIM; j++)
         {
           flux[icount] = real_strainrate(i, j);
           icount++;
         }
       }
       // Start with diagonal terms
       for (unsigned i = 0; i < DIM; i++)
       {
         flux[icount] = imag_strainrate(i, i);
         icount++;
       }
       // Off diagonals row by row
       for (unsigned i = 0; i < DIM; i++)
       {
         for (unsigned j = i + 1; j < DIM; j++)
         {
           flux[icount] = imag_strainrate(i, j);
           icount++;
         }
       }
     }
References DIM, ProblemParameters::flux(), i, j, OOMPH_EXCEPTION_LOCATION, and oomph::LinearisedNavierStokesEquations::strain_rate().
num_Z2_flux_terms()
unsigned oomph::RefineableLinearisedNavierStokesEquations::num_Z2_flux_terms () inline virtual
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       // 3 diagonal strain rates, 3 off diagonal real and imaginary parts
       return 2 * (DIM + ((DIM * DIM) - DIM) / 2);
     }
References DIM.
pin_elemental_redundant_nodal_pressure_dofs()
virtual void oomph::RefineableLinearisedNavierStokesEquations::pin_elemental_redundant_nodal_pressure_dofs () inline protected virtual
Pin unused nodal pressure dofs (empty by default, because by default pressure dofs are not associated with nodes)
Reimplemented in oomph::RefineableLinearisedQTaylorHoodElement.
 {}
Referenced by pin_redundant_nodal_pressures().
pin_redundant_nodal_pressures()
static void oomph::RefineableLinearisedNavierStokesEquations::pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > & element_pt) inline static
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function
RefineableLinearisedNavierStokesEquations:: pin_all_nodal_pressure_dofs()
which is empty by default and should be implemented for elements with nodal pressure degrees of freedom (e.g. for refineable Taylor-Hood.)
     {
       // Loop over all elements to brutally pin all nodal pressure degrees of
       // freedom
       const unsigned n_element = element_pt.size();
       for (unsigned e = 0; e < n_element; e++)
       {
         dynamic_cast<RefineableLinearisedNavierStokesEquations*>(element_pt[e])
           ->pin_elemental_redundant_nodal_pressure_dofs();
       }
     }
References e(), and pin_elemental_redundant_nodal_pressure_dofs().
Referenced by FlowAroundCylinderProblem< ELEMENT >::actions_after_adapt(), and FlowAroundCylinderProblem< ELEMENT >::add_eigenproblem().
pressure_node_pt()
virtual Node* oomph::RefineableLinearisedNavierStokesEquations::pressure_node_pt (const unsigned & n_p) inline protected virtual
Pointer to n_p-th pressure node (Default: NULL, indicating that pressure is not based on nodal interpolation).
Reimplemented in oomph::RefineableLinearisedQTaylorHoodElement.
     {
       return NULL;
     }
Referenced by fill_in_generic_residual_contribution_linearised_nst().
unpin_all_pressure_dofs()
static void oomph::RefineableLinearisedNavierStokesEquations::unpin_all_pressure_dofs (const Vector< GeneralisedElement * > & element_pt) inline static
Unpin all pressure dofs in elements listed in Vector.
     {
       // Loop over all elements to brutally unpin all nodal pressure degrees of
       // freedom and internal pressure degrees of freedom
       const unsigned n_element = element_pt.size();
       for (unsigned e = 0; e < n_element; e++)
       {
         dynamic_cast<RefineableLinearisedNavierStokesEquations*>(element_pt[e])
           ->unpin_elemental_pressure_dofs();
       }
     }
References e(), and unpin_elemental_pressure_dofs().
Referenced by FlowAroundCylinderProblem< ELEMENT >::actions_after_adapt().
unpin_elemental_pressure_dofs()
virtual void oomph::RefineableLinearisedNavierStokesEquations::unpin_elemental_pressure_dofs () protected pure virtual
Unpin all pressure dofs in the element.
Implemented in oomph::RefineableLinearisedQTaylorHoodElement, and oomph::RefineableLinearisedQCrouzeixRaviartElement.
Referenced by unpin_all_pressure_dofs().
The documentation for this class was generated from the following files:
refineable_linearised_navier_stokes_elements.h
refineable_linearised_navier_stokes_elements.cc