MercuryDPM: Eigen::TensorEvaluator< Derived, Device > Class Template Reference
Eigen::TensorEvaluator< Derived, Device > Class Template Reference
A cost model used to limit the number of threads used for evaluating tensor expression.
#include <TensorEvaluator.h>
Public Types
enum { IsAligned = Derived::IsAligned , PacketAccess = (PacketType<CoeffReturnType, Device>::size > 1) }
typedef Derived::Index Index
typedef Derived::Scalar Scalar
typedef Derived::Scalar CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef Derived::Dimensions Dimensions
typedef Derived XprType
typedef internal::traits< Derived >::template MakePointer< Scalar >::Type TensorPointerType
typedef StorageMemory< Scalar, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef std::remove_const_t< Scalar > ScalarNoConst
typedef internal::TensorBlockDescriptor< NumCoords, Index > TensorBlockDesc
typedef internal::TensorBlockScratchAllocator< Device > TensorBlockScratch
typedef internal::TensorMaterializedBlock< ScalarNoConst, NumCoords, Layout, Index > TensorBlock
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorEvaluator (const Derived &m, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType dest)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType & coeffRef (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
template<typename PacketReturnTypeT >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE std::enable_if_t< internal::unpacket_traits< PacketReturnTypeT >::masked_load_available, PacketReturnTypeT > partialPacket (Index index, typename internal::unpacket_traits< PacketReturnTypeT >::mask_t umask) const
template<int StoreMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void writePacket (Index index, const PacketReturnType &x) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (const array< DenseIndex, NumCoords > &coords) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType & coeffRef (const array< DenseIndex, NumCoords > &coords) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements getResourceRequirements () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock block (TensorBlockDesc &desc, TensorBlockScratch &scratch, bool=false) const
template<typename TensorBlock >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void writeBlock (const TensorBlockDesc &desc, const TensorBlock &block)
EIGEN_DEVICE_FUNC EvaluatorPointerType data () const
Static Public Attributes
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int NumCoords
static constexpr int Layout = Derived::Layout
Protected Attributes
EvaluatorPointerType m_data
Dimensions m_dims
const Device EIGEN_DEVICE_REF m_device
Detailed Description
template<typename Derived, typename Device>
class Eigen::TensorEvaluator< Derived, Device >
A cost model used to limit the number of threads used for evaluating tensor expression.
The tensor evaluator classes.
These classes are responsible for the evaluation of the tensor expression.
TODO: add support for more types of expressions, in particular expressions leading to lvalues (slicing, reshaping, etc...)
Member Typedef Documentation
CoeffReturnType
template<typename Derived , typename Device > typedef Derived::Scalar Eigen::TensorEvaluator< Derived, Device >::CoeffReturnType
Examples
/home/plath/mercurydpm2/mercurydpm/Eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
Dimensions
template<typename Derived , typename Device > typedef Derived::Dimensions Eigen::TensorEvaluator< Derived, Device >::Dimensions
Examples
/home/plath/mercurydpm2/mercurydpm/Eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
EvaluatorPointerType
template<typename Derived , typename Device > typedef Storage::Type Eigen::TensorEvaluator< Derived, Device >::EvaluatorPointerType
Examples
/home/plath/mercurydpm2/mercurydpm/Eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
Index
template<typename Derived , typename Device > typedef Derived::Index Eigen::TensorEvaluator< Derived, Device >::Index
Examples
/home/plath/mercurydpm2/mercurydpm/Eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
PacketReturnType
template<typename Derived , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< Derived, Device >::PacketReturnType
Examples
/home/plath/mercurydpm2/mercurydpm/Eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
Scalar
template<typename Derived , typename Device > typedef Derived::Scalar Eigen::TensorEvaluator< Derived, Device >::Scalar
Examples
/home/plath/mercurydpm2/mercurydpm/Eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
ScalarNoConst
template<typename Derived , typename Device > typedef std::remove_const_t<Scalar> Eigen::TensorEvaluator< Derived, Device >::ScalarNoConst
Storage
template<typename Derived , typename Device > typedef StorageMemory<Scalar, Device> Eigen::TensorEvaluator< Derived, Device >::Storage
Examples
/home/plath/mercurydpm2/mercurydpm/Eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
TensorBlock
template<typename Derived , typename Device > typedef internal::TensorMaterializedBlock<ScalarNoConst, NumCoords, Layout, Index> Eigen::TensorEvaluator< Derived, Device >::TensorBlock
Examples
/home/plath/mercurydpm2/mercurydpm/Eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
TensorBlockDesc
template<typename Derived , typename Device > typedef internal::TensorBlockDescriptor<NumCoords, Index> Eigen::TensorEvaluator< Derived, Device >::TensorBlockDesc
TensorBlockScratch
template<typename Derived , typename Device > typedef internal::TensorBlockScratchAllocator<Device> Eigen::TensorEvaluator< Derived, Device >::TensorBlockScratch
TensorPointerType
template<typename Derived , typename Device > typedef internal::traits<Derived>::template MakePointer<Scalar>::Type Eigen::TensorEvaluator< Derived, Device >::TensorPointerType
XprType
template<typename Derived , typename Device > typedef Derived Eigen::TensorEvaluator< Derived, Device >::XprType
Examples
/home/plath/mercurydpm2/mercurydpm/Eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
Member Enumeration Documentation
anonymous enum
template<typename Derived , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
        {
     IsAligned = Derived::IsAligned,
     PacketAccess = (PacketType<CoeffReturnType, Device>::size > 1),
     BlockAccess = internal::is_arithmetic<std::remove_const_t<Scalar>>::value,
     PreferBlockAccess = false,
     CoordAccess = NumCoords > 0,
     RawAccess = true
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorEvaluator< Derived, Device >::TensorEvaluator (const Derived & m, const Device & device) inline
Examples
/home/plath/mercurydpm2/mercurydpm/Eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
       : m_data(device.get((const_cast<TensorPointerType>(m.data())))), m_dims(m.dimensions()), m_device(device) {}
Member Function Documentation
block()
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock Eigen::TensorEvaluator< Derived, Device >::block (TensorBlockDesc & desc, TensorBlockScratch & scratch, bool = false) const inline
{
     eigen_assert(m_data != NULL);
     return TensorBlock::materialize(m_data, m_dims, desc, scratch);
   }
References eigen_assert, Eigen::TensorEvaluator< Derived, Device >::m_data, Eigen::TensorEvaluator< Derived, Device >::m_dims, and Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::materialize().
Referenced by Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::evalBlock(), Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::evalBlock(), Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::writeBlock(), Eigen::TensorEvaluator< Derived, Device >::writeBlock(), Eigen::TensorEvaluator< TensorReshapingOp< NewDimensions, ArgType >, Device >::writeBlock(), Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::writeBlock(), and Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::writeBlock().
cleanup()
template<typename Derived , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< Derived, Device >::cleanup () inline
Examples
/home/plath/mercurydpm2/mercurydpm/Eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
 {}
Referenced by framework.Frame::__init__(), Eigen::TensorContractionEvaluatorBase< Derived >::cleanup(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::evalTo(), Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::~TensorEvaluator(), and Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::~TensorLazyEvaluatorReadOnly().
coeff() [1/2]
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< Derived, Device >::coeff (const array< DenseIndex, NumCoords > & coords) const inline
{
     eigen_assert(m_data != NULL);
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       return m_data[m_dims.IndexOfColMajor(coords)];
     } else {
       return m_data[m_dims.IndexOfRowMajor(coords)];
     }
   }
References Eigen::ColMajor, eigen_assert, Eigen::TensorEvaluator< Derived, Device >::Layout, Eigen::TensorEvaluator< Derived, Device >::m_data, and Eigen::TensorEvaluator< Derived, Device >::m_dims.
coeff() [2/2]
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< Derived, Device >::coeff (Index index) const inline
Examples
/home/plath/mercurydpm2/mercurydpm/Eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
{
     eigen_assert(m_data != NULL);
     return m_data[index];
   }
References eigen_assert, and Eigen::TensorEvaluator< Derived, Device >::m_data.
Referenced by Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::coeff(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::evalTo(), Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::packetWithPossibleZero(), Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::packetWithPossibleZero(), Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::packetWithPossibleZero(), Eigen::internal::CoeffConv< SrcType, TargetType, IsSameT >::run(), Eigen::internal::CoeffConv< SrcType, TargetType, true >::run(), Eigen::internal::PacketConv< SrcPacket, TargetPacket, LoadMode, ActuallyVectorize, IsSameT >::run(), and Eigen::internal::PacketConv< SrcPacket, TargetPacket, LoadMode, false, true >::run().
coeffRef() [1/2]
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType& Eigen::TensorEvaluator< Derived, Device >::coeffRef (const array< DenseIndex, NumCoords > & coords) const inline
{
     eigen_assert(m_data != NULL);
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       return m_data[m_dims.IndexOfColMajor(coords)];
     } else {
       return m_data[m_dims.IndexOfRowMajor(coords)];
     }
   }
References Eigen::ColMajor, eigen_assert, Eigen::TensorEvaluator< Derived, Device >::Layout, Eigen::TensorEvaluator< Derived, Device >::m_data, and Eigen::TensorEvaluator< Derived, Device >::m_dims.
coeffRef() [2/2]
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType& Eigen::TensorEvaluator< Derived, Device >::coeffRef (Index index) const inline
Examples
/home/plath/mercurydpm2/mercurydpm/Eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
{
     eigen_assert(m_data != NULL);
     return m_data[index];
   }
References eigen_assert, and Eigen::TensorEvaluator< Derived, Device >::m_data.
Referenced by Eigen::internal::TensorLazyEvaluatorWritable< Dimensions, Expr, Device >::coeffRef(), Eigen::internal::Initializer< Derived, 0 >::run(), Eigen::internal::Initializer< Derived, 1 >::run(), Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::writePacket(), Eigen::TensorEvaluator< TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::writePacket(), Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::writePacket(), Eigen::TensorEvaluator< TensorReverseOp< ReverseDimensions, ArgType >, Device >::writePacket(), Eigen::TensorEvaluator< TensorRollOp< RollDimensions, ArgType >, Device >::writePacket(), Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::writePacket(), and Eigen::TensorEvaluator< TensorStridingOp< Strides, ArgType >, Device >::writePacket().
costPerCoeff()
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< Derived, Device >::costPerCoeff (bool vectorized) const inline
Examples
/home/plath/mercurydpm2/mercurydpm/Eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
{
     return TensorOpCost(sizeof(CoeffReturnType), 0, 0, vectorized, PacketType<CoeffReturnType, Device>::size);
   }
data()
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EvaluatorPointerType Eigen::TensorEvaluator< Derived, Device >::data () const inline
Examples
/home/plath/mercurydpm2/mercurydpm/Eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
 { return m_data; }
References Eigen::TensorEvaluator< Derived, Device >::m_data.
Referenced by Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::butterfly_1D_merge(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::butterfly_2(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::butterfly_4(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::butterfly_8(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Eigen::SyclDevice >::coeff(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::compute_1D_Butterfly(), Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::data(), Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::evalBlock(), Eigen::TensorEvaluator< const TensorConversionOp< TargetType, ArgType >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorCustomUnaryOp< CustomUnaryFunc, XprType >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const Derived, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorContractionOp< Indices, LeftArgType, RightArgType, OutputKernelType >, Eigen::SyclDevice >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorCustomUnaryOp< CustomUnaryFunc, XprType >, Device >::evalTo(), Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::evalTo(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::evalToBuf(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::executeEval(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Eigen::SyclDevice >::packet(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::processDataLineBluestein(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::scramble_FFT(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< Derived, Device >::dimensions () const inline
Examples
/home/plath/mercurydpm2/mercurydpm/Eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
 { return m_dims; }
References Eigen::TensorEvaluator< Derived, Device >::m_dims.
Referenced by Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::coeff(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::emptyBlock(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorCustomUnaryOp< CustomUnaryFunc, XprType >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::evalTo(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::executeEval(), Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::getInputIndex(), Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::packetColMajor(), Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::packetColMajor(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::packetNByOne(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::packetOneByN(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::packetOneByNByOne(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::packetRowMajor(), Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::packetRowMajor(), Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::reverseIndex(), Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::rollIndex(), Eigen::TensorContractionEvaluatorBase< Derived >::TensorContractionEvaluatorBase(), Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::TensorEvaluator(), Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::TensorLazyEvaluatorReadOnly(), Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::TensorReductionEvaluatorBase(), Eigen::TensorEvaluator< TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::writePacket(), Eigen::TensorEvaluator< TensorReverseOp< ReverseDimensions, ArgType >, Device >::writePacket(), Eigen::TensorEvaluator< TensorRollOp< RollDimensions, ArgType >, Device >::writePacket(), and Eigen::TensorEvaluator< TensorStridingOp< Strides, ArgType >, Device >::writePacket().
evalSubExprsIfNeeded()
template<typename Derived , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< Derived, Device >::evalSubExprsIfNeeded (EvaluatorPointerType dest) inline
Examples
/home/plath/mercurydpm2/mercurydpm/Eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
{
     if (!NumTraits<std::remove_const_t<Scalar>>::RequireInitialization && dest) {
       m_device.memcpy((void*)(m_device.get(dest)), m_device.get(m_data), m_dims.TotalSize() * sizeof(Scalar));
       return false;
     }
     return true;
   }
References Eigen::TensorEvaluator< Derived, Device >::m_data, Eigen::TensorEvaluator< Derived, Device >::m_device, and Eigen::TensorEvaluator< Derived, Device >::m_dims.
Referenced by Eigen::TensorContractionEvaluatorBase< Derived >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::evalTo(), and Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::TensorLazyEvaluatorReadOnly().
getResourceRequirements()
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements Eigen::TensorEvaluator< Derived, Device >::getResourceRequirements () const inline
{
     return internal::TensorBlockResourceRequirements::any();
   }
References Eigen::internal::TensorBlockResourceRequirements::any().
packet()
template<typename Derived , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< Derived, Device >::packet (Index index) const inline
Examples
/home/plath/mercurydpm2/mercurydpm/Eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
{
     return internal::ploadt<PacketReturnType, LoadMode>(m_data + index);
   }
References Eigen::TensorEvaluator< Derived, Device >::m_data.
Referenced by Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::evalPacket().
partialPacket()
template<typename Derived , typename Device > template<typename PacketReturnTypeT > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE std::enable_if_t<internal::unpacket_traits<PacketReturnTypeT>::masked_load_available, PacketReturnTypeT> Eigen::TensorEvaluator< Derived, Device >::partialPacket (Index index, typename internal::unpacket_traits< PacketReturnTypeT >::mask_t umask) const inline
{
     return internal::ploadu<PacketReturnTypeT>(m_data + index, umask);
   }
References Eigen::TensorEvaluator< Derived, Device >::m_data.
writeBlock()
template<typename Derived , typename Device > template<typename TensorBlock > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< Derived, Device >::writeBlock (const TensorBlockDesc & desc, const TensorBlock & block) inline
{
     eigen_assert(m_data != NULL);
     typedef typename TensorBlock::XprType TensorBlockExpr;
     typedef internal::TensorBlockAssignment<Scalar, NumCoords, TensorBlockExpr, Index> TensorBlockAssign;
     TensorBlockAssign::Run(
         TensorBlockAssign::target(desc.dimensions(), internal::strides<Layout>(m_dims), m_data, desc.offset()),
         block.expr());
   }
References Eigen::TensorEvaluator< Derived, Device >::block(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::dimensions(), eigen_assert, Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::expr(), Eigen::TensorEvaluator< Derived, Device >::m_data, Eigen::TensorEvaluator< Derived, Device >::m_dims, and Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::offset().
writePacket()
template<typename Derived , typename Device > template<int StoreMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< Derived, Device >::writePacket (Index index, const PacketReturnType & x) const inline
Examples
/home/plath/mercurydpm2/mercurydpm/Eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
{
     return internal::pstoret<Scalar, PacketReturnType, StoreMode>(m_data + index, x);
   }
References Eigen::TensorEvaluator< Derived, Device >::m_data, and plotDoE::x.
Member Data Documentation
Layout
template<typename Derived , typename Device > constexpr int Eigen::TensorEvaluator< Derived, Device >::Layout = Derived::Layout static constexpr
Examples
/home/plath/mercurydpm2/mercurydpm/Eigen/unsupported/Eigen/CXX11/src/Tensor/TensorLayoutSwap.h.
Referenced by Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::block(), Eigen::TensorEvaluator< Derived, Device >::coeff(), Eigen::TensorEvaluator< const Derived, Device >::coeff(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::coeff(), Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::coeff(), Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::coeff(), Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::coeff(), Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::coeff(), Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::coeff(), Eigen::TensorEvaluator< Derived, Device >::coeffRef(), Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::data(), Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::executeEval(), Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::extract_coordinates(), Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::extract_coordinates(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::firstInput(), Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::firstInput(), Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::gen_strides(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::getBaseOffsetFromIndex(), Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::GetBlockOutputIndex(), Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::getInputIndex(), Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::getResourceRequirements(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::packetNByOne(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::packetOneByN(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::packetOneByNByOne(), Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::reverseIndex(), Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::rollIndex(), Eigen::internal::TensorBlockAssignment< Scalar, NumDims, TensorBlockExpr, IndexType >::Run(), Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::srcCoeff(), Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::srcCoeff(), Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::srcCoeff(), Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::srcCoeff(), Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::TensorEvaluator(), Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::writePacket(), and Eigen::TensorEvaluator< TensorStridingOp< Strides, ArgType >, Device >::writePacket().
m_data
template<typename Derived , typename Device > EvaluatorPointerType Eigen::TensorEvaluator< Derived, Device >::m_data protected
Referenced by Eigen::TensorEvaluator< Derived, Device >::block(), Eigen::TensorEvaluator< const Derived, Device >::block(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::cleanup(), Eigen::TensorEvaluator< Derived, Device >::coeff(), Eigen::TensorEvaluator< const Derived, Device >::coeff(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::coeff(), Eigen::TensorEvaluator< Derived, Device >::coeffRef(), Eigen::TensorEvaluator< Derived, Device >::data(), Eigen::TensorEvaluator< const Derived, Device >::data(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::data(), Eigen::TensorEvaluator< const Derived, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< Derived, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< Derived, Device >::packet(), Eigen::TensorEvaluator< const Derived, Device >::packet(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::packet(), Eigen::TensorEvaluator< Derived, Device >::partialPacket(), Eigen::TensorEvaluator< const Derived, Device >::partialPacket(), Eigen::TensorEvaluator< Derived, Device >::writeBlock(), and Eigen::TensorEvaluator< Derived, Device >::writePacket().
m_device
template<typename Derived , typename Device > const Device EIGEN_DEVICE_REF Eigen::TensorEvaluator< Derived, Device >::m_device protected
Referenced by Eigen::TensorEvaluator< const TensorContractionOp< Indices, LeftArgType, RightArgType, OutputKernelType >, Eigen::SyclDevice >::cleanup(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::cleanup(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::cleanup(), Eigen::TensorEvaluator< const TensorCustomUnaryOp< CustomUnaryFunc, XprType >, Device >::cleanup(), Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::cleanup(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::cleanup(), Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::cleanup(), Eigen::TensorEvaluator< const TensorContractionOp< Indices, LeftArgType, RightArgType, OutputKernelType >, Eigen::SyclDevice >::device(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::device(), Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::device(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorCustomUnaryOp< CustomUnaryFunc, XprType >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const Derived, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorScanOp< Op, ArgType >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< Derived, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorContractionOp< Indices, LeftArgType, RightArgType, OutputKernelType >, Eigen::SyclDevice >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< const TensorCustomUnaryOp< CustomUnaryFunc, XprType >, Device >::evalTo(), Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::evalTo(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::evalToBuf(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::executeEval(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::getResourceRequirements(), Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::getResourceRequirements(), Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::getResourceRequirements(), Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::getResourceRequirements(), Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::getResourceRequirements(), Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::getResourceRequirements(), Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::getResourceRequirements(), Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::getResourceRequirements(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::preloadKernel(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::preloadKernel(), and Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::writeBlock().
m_dims
template<typename Derived , typename Device > Dimensions Eigen::TensorEvaluator< Derived, Device >::m_dims protected
Referenced by Eigen::TensorEvaluator< Derived, Device >::block(), Eigen::TensorEvaluator< const Derived, Device >::block(), Eigen::TensorEvaluator< Derived, Device >::coeff(), Eigen::TensorEvaluator< const Derived, Device >::coeff(), Eigen::TensorEvaluator< Derived, Device >::coeffRef(), Eigen::TensorEvaluator< Derived, Device >::dimensions(), Eigen::TensorEvaluator< const Derived, Device >::dimensions(), Eigen::TensorEvaluator< const Derived, Device >::evalSubExprsIfNeeded(), Eigen::TensorEvaluator< Derived, Device >::evalSubExprsIfNeeded(), and Eigen::TensorEvaluator< Derived, Device >::writeBlock().
NumCoords
template<typename Derived , typename Device > constexpr int Eigen::TensorEvaluator< Derived, Device >::NumCoords static constexpr
Initial value:
=
      internal::traits<Derived>::NumDimensions > 0 ? internal::traits<Derived>::NumDimensions : 0
PacketSize
template<typename Derived , typename Device > constexpr int Eigen::TensorEvaluator< Derived, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
Referenced by Eigen::TensorEvaluator< const TensorAssignOp< LeftArgType, RightArgType >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorConversionOp< TargetType, ArgType >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::costPerCoeff(), Eigen::TensorEvaluator< const TensorCustomUnaryOp< CustomUnaryFunc, XprType >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorCustomBinaryOp< CustomBinaryFunc, LhsXprType, RhsXprType >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::costPerCoeff(), Eigen::TensorEvaluator< const TensorCwiseUnaryOp< UnaryOp, ArgType >, Device >::getResourceRequirements(), Eigen::TensorEvaluator< const TensorCwiseBinaryOp< BinaryOp, LeftArgType, RightArgType >, Device >::getResourceRequirements(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorTraceOp< Dims, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::packet(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::packetColMajor(), Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::packetColMajor(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::packetNByOne(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::packetOneByN(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::packetOneByNByOne(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::packetRowMajor(), Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::packetRowMajor(), Eigen::TensorEvaluator< const TensorImagePatchOp< Rows, Cols, ArgType >, Device >::packetWithPossibleZero(), Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::packetWithPossibleZero(), Eigen::TensorEvaluator< const TensorVolumePatchOp< Planes, Rows, Cols, ArgType >, Device >::packetWithPossibleZero(), Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::PacketLoader< LoadMode, Self, ImplPacketAccess >::Run(), Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::PacketLoader< LoadMode, Self, true >::Run(), Eigen::TensorEvaluator< TensorChippingOp< DimId, ArgType >, Device >::writePacket(), Eigen::TensorEvaluator< TensorReverseOp< ReverseDimensions, ArgType >, Device >::writePacket(), Eigen::TensorEvaluator< TensorRollOp< RollDimensions, ArgType >, Device >::writePacket(), Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::writePacket(), and Eigen::TensorEvaluator< TensorStridingOp< Strides, ArgType >, Device >::writePacket().
The documentation for this class was generated from the following file:
TensorEvaluator.h