MercuryDPM: PeriodicBoundary Class Reference
PeriodicBoundary Class Reference
Defines a pair of periodic walls. Inherits from BaseBoundary.
#include <PeriodicBoundary.h>
Public Member Functions
PeriodicBoundary ()
default constructor
~PeriodicBoundary () override
destructor
PeriodicBoundary * copy () const override
copy method
PeriodicBoundary (const PeriodicBoundary &other)
copy constructor
void set (Vec3D normal, Mdouble distanceLeft, Mdouble distanceRight)
Defines a PeriodicBoundary by its normal and positions.
void set (Vec3D normal, Vec3D positionLeft, Vec3D positionRight)
As above, but by specifying two positions that the boundaries go through instead of distanceLeft and distanceRight.
void set (Vec3D normal, Mdouble distanceLeft, Mdouble distanceRight, Vec3D shiftDirection)
For general parallelogramic domains, the direction of the shift vector can to be set manually.
void setPlanewiseShift (Vec3D planewiseShift)
Set the planewise shift (projected onto the planewise direction, and zero by default).
Vec3D getNormal () const
returns the vector normal to the periodic boundary
Mdouble getDistanceLeft () const
Returns the distance of the left wall to the origin, in normal direction.
Mdouble getDistanceRight () const
Returns the distance of the right wall to the origin, in normal direction.
Vec3D getShift () const
Returns the vector going from the left to the right side of the periodic boundary.
void moveLeft (Mdouble distanceLeft)
Sets the distance from the origin of the 'left' periodic wall.
void moveRight (Mdouble distanceRight)
Sets the distance from the origin of the 'right' periodic wall.
Mdouble getDistance (const BaseParticle &p) const override
Returns the distance of the edge to the particle.
Mdouble getDistance (const Vec3D &position) const override
Returns the distance of the edge to the position.
virtual void shiftPosition (BaseParticle *p) const override
shifts the particle
void shiftPosition (Vec3D &p) const
virtual void shiftPositions (Vec3D &postition1, Vec3D &postion2) const
shifts two positions
virtual bool isClosestToLeftBoundary (const BaseParticle &p) const
Returns TRUE if particle checked is closest to the 'left' edge, and FALSE if it is closest to the 'right' edge.
bool isClosestToLeftBoundary (const Vec3D &p) const override
virtual void createPeriodicParticles (ParticleHandler &pH) override
Checks distance of particle to closer edge and creates a periodic copy if necessary.
void createGhostParticle (BaseParticle *pReal)
Creates and adds a ghost particle from a given real particle.
void createPeriodicParticle (BaseParticle *p, ParticleHandler &pH) override
Creates a single periodic particle if required from a given particle.
virtual void checkBoundaryAfterParticlesMove (ParticleHandler &pH) override
Loops over particles, checks if each particle has crossed either boundary edge, and applies a shift if that is the case.
virtual void read (std::istream &is) override
reads boundary properties from istream
MERCURYDPM_DEPRECATED void oldRead (std::istream &is)
deprecated version of CubeInsertionBoundary::read().
void write (std::ostream &os) const override
writes boundary properties to ostream
std::string getName () const override
Returns the name of the object.
Public Member Functions inherited from BasePeriodicBoundary
BasePeriodicBoundary ()
default constructor.
BasePeriodicBoundary (const BasePeriodicBoundary &b)
copy constructor
~BasePeriodicBoundary () override
destructor
void setPeriodicHandler (PeriodicBoundaryHandler *periodicHandler)
Sets the periodicBoundaryHandler, required for parallel periodic boundaries.
PeriodicBoundaryHandler * getPeriodicHandler () const
Returns the periodic boundary handler.
void createPeriodicParticles (ParticleHandler &pH) override
Creates periodic ocpies of given particle in case of periodic boundaries in serial build.
virtual void modifyPeriodicComplexity (std::vector< int > &complexity, int &totalPeriodicComplexity, BaseParticle *particle, int i) const
Modifies periodic complexity of a particle if necessary (i.e. maser boundary)
virtual void performActionsBeforeAddingParticles ()
Actions that need to be performed before adding new ghost particles.
Public Member Functions inherited from BaseBoundary
BaseBoundary ()
default constructor.
BaseBoundary (const BaseBoundary &b)
copy constructor
~BaseBoundary () override
destructor
virtual void createPeriodicParticle (BaseParticle *p UNUSED, ParticleHandler &pH UNUSED)
Creates a periodic particle in case of periodic boundaries in serial build.
virtual void createPeriodicParticles (ParticleHandler &pH UNUSED)
Creates periodic copies of given particle in case of periodic boundaries.
virtual void checkBoundaryBeforeTimeStep (DPMBase *md)
Virtual function that does things before each time step.
virtual void actionsBeforeTimeLoop ()
Virtual function that does something after DPMBase::setupInitialConditions but before the first time step.
virtual void modifyGhostAfterCreation (BaseParticle *particle, int i)
virtual void writeVTK (std::fstream &file)
void setHandler (BoundaryHandler *handler)
Sets the boundary's BoundaryHandler.
BoundaryHandler * getHandler () const
Returns the boundary's BoundaryHandler.
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Protected Attributes
Vec3D normal_
outward unit normal vector for right edge
Mdouble distanceLeft_
position of left edge, s.t. normal*x = distanceLeft_
Mdouble distanceRight_
position of right edge, s.t. normal*x = distanceRight_
Mdouble scaleFactor_
This is the normal to rescale the normal vector to a unit vectors.
Vec3D shift_
shift from left to right boundary
Detailed Description
Defines a pair of periodic walls. Inherits from BaseBoundary.
The particles are in {x: position_left<=normal*x <position_right}, with normal being the outward unit normal vector of the right wall. If a particle moves outside these boundaries, it will be shifted.
Constructor & Destructor Documentation
PeriodicBoundary() [1/2]
PeriodicBoundary::PeriodicBoundary ()
default constructor
constructor
         : BasePeriodicBoundary()
 {
     distanceLeft_ = std::numeric_limits<double>::quiet_NaN();
     distanceRight_ = std::numeric_limits<double>::quiet_NaN();
     scaleFactor_ = std::numeric_limits<double>::quiet_NaN();
     logger(DEBUG, "PeriodicBoundary::PeriodicBoundary() finished");
 }
References DEBUG, distanceLeft_, distanceRight_, logger, and scaleFactor_.
Referenced by copy().
~PeriodicBoundary()
PeriodicBoundary::~PeriodicBoundary () override
destructor
destructor
 {
     logger(DEBUG, "PeriodicBoundary::~PeriodicBoundary() finished");
 }
References DEBUG, and logger.
PeriodicBoundary() [2/2]
PeriodicBoundary::PeriodicBoundary (const PeriodicBoundary & other)
copy constructor
Copy constructor
     : BasePeriodicBoundary(other)
 {
     normal_ = other.normal_;
     scaleFactor_ = other.scaleFactor_;
     distanceLeft_ = other.distanceLeft_;
     distanceRight_ = other.distanceRight_;
     shift_ = other.shift_;
 }
References distanceLeft_, distanceRight_, normal_, scaleFactor_, and shift_.
Member Function Documentation
checkBoundaryAfterParticlesMove()
void PeriodicBoundary::checkBoundaryAfterParticlesMove (ParticleHandler & pH) override virtual
Loops over particles, checks if each particle has crossed either boundary edge, and applies a shift if that is the case.
Loops through all particles to see if they have become ghosts. If that is the case their position is shifted. Note: This is only for a serial build - periodic particles work different in paralle
Parameters
[in]
Reimplemented from BasePeriodicBoundary.
Reimplemented in SubcriticalMaserBoundaryTEST.
 {
 #ifdef MERCURYDPM_USE_MPI
     if (NUMBER_OF_PROCESSORS == 1)
     {
 #endif
     for (auto p = pH.begin(); p != pH.end(); ++p)
     {
         if (getDistance((*p)->getPosition()) < 0)
         {
             shiftPosition(*p);
             getHandler()->getDPMBase()->hGridUpdateMove(*p, shift_.getLengthSquared());
         }
     }
 #ifdef MERCURYDPM_USE_MPI
     }
 #endif
 }
References BaseHandler< T >::begin(), BaseHandler< T >::end(), getDistance(), BaseHandler< T >::getDPMBase(), BaseBoundary::getHandler(), Vec3D::getLengthSquared(), DPMBase::hGridUpdateMove(), NUMBER_OF_PROCESSORS, p, shift_, and shiftPosition().
copy()
PeriodicBoundary * PeriodicBoundary::copy () const override virtual
copy method
Copy method; creates a copy on the heap and returns its pointer.
Implements BasePeriodicBoundary.
Reimplemented in SubcriticalMaserBoundaryTEST.
 {
     return new PeriodicBoundary(*this);
 }
References PeriodicBoundary().
createGhostParticle()
void PeriodicBoundary::createGhostParticle (BaseParticle * pReal)
Creates and adds a ghost particle from a given real particle.
 {
     ParticleHandler& pH = getHandler()->getDPMBase()->particleHandler;
     //Step 1: Copy the particle to new ghost particle.
     BaseParticle* pGhost = pReal->copy();
     //Step 2: Copy the interactions of the ghost particle.
     pGhost->copyInteractionsForPeriodicParticles(*pReal);
     //Step 3: Shift the ghost to the 'reflected' location.
     shiftPosition(pGhost);
     //Step 4: If Particle is double shifted, get correct original particle
     BaseParticle* from = pReal;
     while (from->getPeriodicFromParticle() != nullptr)
         from = from->getPeriodicFromParticle();
     pGhost->setPeriodicFromParticle(from);
     pGhost->setPeriodicGhostParticle(true);
     pH.addObject(pGhost);
 }
References ParticleHandler::addObject(), BaseParticle::copy(), BaseInteractable::copyInteractionsForPeriodicParticles(), BaseHandler< T >::getDPMBase(), BaseBoundary::getHandler(), BaseParticle::getPeriodicFromParticle(), DPMBase::particleHandler, BaseParticle::setPeriodicFromParticle(), BaseParticle::setPeriodicGhostParticle(), and shiftPosition().
Referenced by createPeriodicParticle(), and SubcriticalMaserBoundaryTEST::createPeriodicParticle().
createPeriodicParticle()
void PeriodicBoundary::createPeriodicParticle (BaseParticle * p, ParticleHandler & pH) override
Creates a single periodic particle if required from a given particle.
Checks the distance of given particle to the closest of both periodic walls, and creates a periodic copy of the particle if needed (i.e. if the particle is closer to the periodic wall than the radius of the largest particle in the system).
Parameters
[in] p Particle to be checked and possibly periodically copied
[in,out] pH System's ParticleHandler, (1) from which the interaction radius of its largest particle is retrieved to determine the maximum distance from the wall at which a particle should still have a periodic copy created, and (2) to which a possible periodic copy of the particle will be added
 {
     //note that getDistance sets closestToLeftBoundary_ to true or false depending on which side is closest
     const Mdouble maxDistance = p->getMaxInteractionRadius() + pH.getLargestParticle()->getMaxInteractionRadius();
     if ((getDistance(*p) < maxDistance)&&(!p->isClump()))
     {
         createGhostParticle(p);
     }
 }
References createGhostParticle(), getDistance(), ParticleHandler::getLargestParticle(), BaseParticle::getMaxInteractionRadius(), and p.
Referenced by createPeriodicParticles().
createPeriodicParticles()
void PeriodicBoundary::createPeriodicParticles (ParticleHandler & pH) override virtual
Checks distance of particle to closer edge and creates a periodic copy if necessary.
Checks the distance of given particle to the closest of both periodic walls, and creates a periodic copy of the particle if needed (i.e. if the particle is closer to the periodic wall than the radius of the largest particle in the system).
Parameters
[in] p Particle to be checked and possibly periodically copied
[in,out] pH System's ParticleHandler, (1) from which the interaction radius of its largest particle is retrieved to determine the maximum distance from the wall at which a particle should still have a periodic copy created, and (2) to which a possible periodic copy of the particle will be added
 {
 #ifdef MERCURYDPM_USE_MPI
     if (NUMBER_OF_PROCESSORS == 1)
     {
 #endif
     unsigned numberOfParticles = pH.getSize();
     for (unsigned i = 0; i < numberOfParticles; i++)
     {
         createPeriodicParticle(pH.getObject(i), pH);
     }
 #ifdef MERCURYDPM_USE_MPI
     }
 #endif
 }
References createPeriodicParticle(), BaseHandler< T >::getObject(), BaseHandler< T >::getSize(), i, and NUMBER_OF_PROCESSORS.
getDistance() [1/2]
Mdouble PeriodicBoundary::getDistance (const BaseParticle & p) const override virtual
Returns the distance of the edge to the particle.
Returns the distance to the closest edge of the boundary to the particle. Since this function should be called before calculating any Particle-Wall interactions, it can also be used to set the shift vector in case of curved walls. Positive means that the particle is insid-> the periodic domain, negative means that it is outsid-> the periodic domain.
Parameters
[in] p A reference to the particle which distance to the periodic boundary is calculated
Implements BasePeriodicBoundary.
 {
     return getDistance(p.getPosition());
 }
References p.
Referenced by ChuteWithPeriodicInflow::Check_and_Duplicate_Periodic_Particle(), checkBoundaryAfterParticlesMove(), createPeriodicParticle(), SubcriticalMaserBoundaryTEST::getDistance(), and ChuteWithPeriodicInflow::integrateBeforeForceComputation().
getDistance() [2/2]
Mdouble PeriodicBoundary::getDistance (const Vec3D & position) const override virtual
Returns the distance of the edge to the position.
Returns the distance to the edge closest to the position
Parameters
[in] position A reference to the position which distance to the periodic boundary is to be calculated
Implements BasePeriodicBoundary.
Reimplemented in SubcriticalMaserBoundaryTEST.
 {
     Mdouble distanceFromPlaneThroughOrigin = Vec3D::dot(position, normal_);
     return std::min(distanceFromPlaneThroughOrigin - distanceLeft_,
                     distanceRight_ - distanceFromPlaneThroughOrigin);
 }
References distanceLeft_, distanceRight_, Vec3D::dot(), min, and normal_.
getDistanceLeft()
Mdouble PeriodicBoundary::getDistanceLeft () const
Returns the distance of the left wall to the origin, in normal direction.
Returns
The distance of the left wall to the origin, in normal direction
 {
     return distanceLeft_;
 }
References distanceLeft_.
Referenced by ConstantMassFlowMaserBoundary::ConstantMassFlowMaserBoundary(), and SubcriticalMaserBoundary::SubcriticalMaserBoundary().
getDistanceRight()
Mdouble PeriodicBoundary::getDistanceRight () const
Returns the distance of the right wall to the origin, in normal direction.
Returns
The distance of the left wall to the origin, in normal direction
 {
     return distanceRight_;
 }
References distanceRight_.
Referenced by ConstantMassFlowMaserBoundary::ConstantMassFlowMaserBoundary(), and SubcriticalMaserBoundary::SubcriticalMaserBoundary().
getName()
std::string PeriodicBoundary::getName () const override virtual
Returns the name of the object.
Returns the name of the object class
Returns
the object's class' name, i.e. 'CubeInsertionBoundary'
Implements BaseObject.
Reimplemented in SubcriticalMaserBoundaryTEST.
 {
     return "PeriodicBoundary";
 }
getNormal()
Vec3D PeriodicBoundary::getNormal () const
returns the vector normal to the periodic boundary
Returns
The vector perpendicular to the periodic boundary
 {
     return normal_;
 }
References normal_.
Referenced by ConstantMassFlowMaserBoundary::ConstantMassFlowMaserBoundary(), and SubcriticalMaserBoundary::SubcriticalMaserBoundary().
getShift()
Vec3D PeriodicBoundary::getShift () const
Returns the vector going from the left to the right side of the periodic boundary.
Returns
The vector going from the left to the right sid-> of the periodic boundary
 {
     return shift_;
 }
References shift_.
Referenced by ConstantMassFlowMaserBoundary::ConstantMassFlowMaserBoundary(), and SubcriticalMaserBoundary::SubcriticalMaserBoundary().
isClosestToLeftBoundary() [1/2]
bool PeriodicBoundary::isClosestToLeftBoundary (const BaseParticle & p) const virtual
Returns TRUE if particle checked is closest to the 'left' edge, and FALSE if it is closest to the 'right' edge.
 {
     return isClosestToLeftBoundary(p.getPosition());
 }
References p.
Referenced by ChuteWithPeriodicInflow::integrateBeforeForceComputation(), shiftPosition(), and shiftPositions().
isClosestToLeftBoundary() [2/2]
bool PeriodicBoundary::isClosestToLeftBoundary (const Vec3D & p) const override virtual
Returns TRUE if position checked is closest to the 'left' edge, and FALSE if it is closest to the 'right' edge`.
Implements BasePeriodicBoundary.
 {
     const Mdouble distance = Vec3D::dot(p, normal_);
     return (distanceRight_ - distance > distance - distanceLeft_);
 }
References distanceLeft_, distanceRight_, Vec3D::dot(), normal_, and p.
moveLeft()
void PeriodicBoundary::moveLeft (Mdouble distanceLeft)
Sets the distance from the origin of the 'left' periodic wall.
Allows the left periodic boundary to be moved to a new position and automatically changes its shift value
Parameters
[in] distanceLeft The distance (from the origin) to which the left boundary is moved
 {
     distanceLeft_ = distanceLeft * scaleFactor_;
     shift_ = normal_ * (distanceRight_ - distanceLeft_);
 }
References distanceLeft_, distanceRight_, normal_, scaleFactor_, and shift_.
moveRight()
void PeriodicBoundary::moveRight (Mdouble distanceRight)
Sets the distance from the origin of the 'right' periodic wall.
Allows the right periodic wall to be moved to a new position and automatically changes its shift value
Parameters
[in] distanceRight The distance (from the origin) to which the right boundary is moved
 {
     distanceRight_ = distanceRight * scaleFactor_;
     shift_ = normal_ * (distanceRight_ - distanceLeft_);
 }
References distanceLeft_, distanceRight_, normal_, scaleFactor_, and shift_.
oldRead()
void PeriodicBoundary::oldRead (std::istream & is)
deprecated version of CubeInsertionBoundary::read().
Deprecated version of read().
Deprecated:
Should be gone by Mercury 2.0. Instead, use CubeInsertionBoundary::read().
 {
     std::string dummy;
     is >> dummy >> normal_
        >> dummy >> scaleFactor_ // JMFT: I'd like to deprecate scaleFactor_
        >> dummy >> distanceLeft_
        >> dummy >> distanceRight_
        >> dummy >> shift_;
 }
References distanceLeft_, distanceRight_, normal_, scaleFactor_, shift_, and oomph::Global_string_for_annotation::string().
read()
void PeriodicBoundary::read (std::istream & is) override virtual
reads boundary properties from istream
Reads the boundary properties from an istream
Parameters
[in] is the istream
Reimplemented from BasePeriodicBoundary.
Reimplemented in SubcriticalMaserBoundaryTEST.
 {
     BasePeriodicBoundary::read(is);
     std::string dummy;
     is >> dummy >> normal_
        >> dummy >> scaleFactor_ // JMFT: I'd like to deprecate scaleFactor_
        >> dummy >> distanceLeft_
        >> dummy >> distanceRight_
        >> dummy >> shift_;
 }
References distanceLeft_, distanceRight_, normal_, BasePeriodicBoundary::read(), scaleFactor_, shift_, and oomph::Global_string_for_annotation::string().
Referenced by SubcriticalMaserBoundaryTEST::read().
set() [1/3]
void PeriodicBoundary::set (Vec3D normal, Mdouble distanceLeft, Mdouble distanceRight)
Defines a PeriodicBoundary by its normal and positions.
Defines the boundary, given a normal vector such that all particles are within {x: position_left<=normal*x<position_right}. The shift vector is set assuming that the domain is rectangular (shift parallel to normal).
Parameters
[in] normal The normal vector pointing from the left wall into the domain
[in] distanceLeft The (signed) distance between the left wall and the origin
[in] distanceRight The (signed) distance between the right wall and the origin
 {
     // factor is used to set normal to unit length
     scaleFactor_ = 1. / std::sqrt(Vec3D::dot(normal, normal));
     normal_ = normal * scaleFactor_;
     distanceLeft_ = distanceLeft * scaleFactor_;
     distanceRight_ = distanceRight * scaleFactor_;
     logger.assert_always(distanceRight_ > distanceLeft_,
             "PeriodicBoundary::set: left distance needs to be smaller than right distance");
     shift_ = normal_ * (distanceRight_ - distanceLeft_);
 }
References distanceLeft_, distanceRight_, Vec3D::dot(), logger, WallFunction::normal(), normal_, scaleFactor_, shift_, and sqrt().
Referenced by Chutebelt::actionsAfterTimeStep(), AngledPeriodicBoundaryUnitTest::AngledPeriodicBoundaryUnitTest(), ChutePeriodicDemo::ChutePeriodicDemo(), ChuteWithContraction::ChuteWithContraction(), ChuteWithPeriodicInflowAndContraction::ChuteWithPeriodicInflowAndContraction(), ContractionWithPeriodicInflow::ContractionWithPeriodicInflow(), Funnel::create_walls(), ChuteWithPeriodicInflow::ExtendInWidth(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), BoundaryHandler::readOldObject(), DPMBase::readParAndIniFiles(), StressStrainControlBoundary::set(), set(), MercuryLogo::setupInitialConditions(), my_problem::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), MaserRepeatedOutInMPI2Test::setupInitialConditions(), MpiPeriodicBoundaryUnitTest::setupInitialConditions(), PeriodicBounaryEnteringMPIDomainTest::setupInitialConditions(), CubicCell::setupInitialConditions(), Cstatic2d::setupInitialConditions(), SilbertPeriodic::setupInitialConditions(), SegregationPeriodic::setupInitialConditions(), Chutebelt::setupInitialConditions(), SingleParticleSegregation::setupInitialConditions(), ScalingTestInitialConditionsRelax::setupInitialConditions(), Tutorial6::setupInitialConditions(), FullRestartTest::setupInitialConditions(), MD_demo::setupInitialConditions(), MpiMaserChuteTest::setupInitialConditions(), PeriodicWalls::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), ChuteBottom::setupInitialConditions(), and Chute::setupSideWalls().
set() [2/3]
void PeriodicBoundary::set (Vec3D normal, Mdouble distanceLeft, Mdouble distanceRight, Vec3D shiftDirection)
For general parallelogramic domains, the direction of the shift vector can to be set manually.
like PeriodicBoundary::set(normal, distanceLeft, distanceRight), but including the possibility of setting the shift direction vector.
Parameters
[in] normal The normal vector pointing from the left wall into the domain
[in] distanceLeft The (signed) distance between the left wall and the origin
[in] distanceRight The (signed) distance between the right wall and the origin
[in] shiftDirection The vector over which particles will be shifted when moving through the PeriodicBoundary
 {
     // factor is used to set normal to unit length
     scaleFactor_ = 1. / std::sqrt(Vec3D::dot(normal, normal));
     normal_ = normal * scaleFactor_;
     distanceLeft_ = distanceLeft * scaleFactor_;
     distanceRight_ = distanceRight * scaleFactor_;
     // factor is used to set shift vector to correct length
     scaleFactor_ = (distanceRight_ - distanceLeft_) * Vec3D::dot(shiftDirection, normal_);
     shift_ = shiftDirection * scaleFactor_;
 }
References distanceLeft_, distanceRight_, Vec3D::dot(), WallFunction::normal(), normal_, scaleFactor_, shift_, and sqrt().
set() [3/3]
void PeriodicBoundary::set (Vec3D normal, Vec3D positionLeft, Vec3D positionRight)
As above, but by specifying two positions that the boundaries go through instead of distanceLeft and distanceRight.
 {
     set(normal, Vec3D::dot(positionLeft, normal), Vec3D::dot(positionRight, normal));
 }
References Vec3D::dot(), WallFunction::normal(), and set().
setPlanewiseShift()
void PeriodicBoundary::setPlanewiseShift (Vec3D planewiseShift)
Set the planewise shift (projected onto the planewise direction, and zero by default).
Sets the shift_ vector through setting the planewise shift. We delete the component of planewiseShift that is parallel to normal_.
 {
     planewiseShift -= Vec3D::dot(planewiseShift, normal_) / Vec3D::dot(normal_, normal_) * normal_;
     shift_ = normal_ * (distanceRight_ - distanceLeft_) + planewiseShift;
 }
References distanceLeft_, distanceRight_, Vec3D::dot(), normal_, and shift_.
shiftPosition() [1/2]
void PeriodicBoundary::shiftPosition (BaseParticle * p) const override virtual
shifts the particle
Parameters
[in] p A pointer to the particle which will be shifted.
Shifts the particle either to the left or right, using the method isClosestToLeftBoundary to determine which sid-> it should be shifted to.
Parameters
[in] p A pointer to the particle which will be shifted.
Implements BasePeriodicBoundary.
 {
     if (isClosestToLeftBoundary(*p))
     {
         p->move(shift_);
     }
     else
     {
         p->move(-shift_);
     }
 }
References isClosestToLeftBoundary(), p, and shift_.
Referenced by ChuteWithPeriodicInflow::Check_and_Duplicate_Periodic_Particle(), SubcriticalMaserBoundaryTEST::checkBoundaryAfterParticleMoved(), checkBoundaryAfterParticlesMove(), createGhostParticle(), and ChuteWithPeriodicInflow::integrateBeforeForceComputation().
shiftPosition() [2/2]
void PeriodicBoundary::shiftPosition (Vec3D & p) const
Shifts the particle either to the left or right, using the method isClosestToLeftBoundary to determine which sid-> it should be shifted to.
Parameters
[in] p A pointer to the particle which will be shifted.
 {
     if (isClosestToLeftBoundary(p))
     {
         p += shift_;
     }
     else
     {
         p -= shift_;
     }
 }
References isClosestToLeftBoundary(), p, and shift_.
shiftPositions()
void PeriodicBoundary::shiftPositions (Vec3D & position1, Vec3D & position2) const virtual
shifts two positions
Shifts two given positions by the shift_ vector.
Parameters
[in] position1 The first position to be shifted
[in] position2 The second position to be shifted
Todo:
(AT) see toDo of PeriodicBoundary::shiftPosition().
 {
     if (isClosestToLeftBoundary(position1))
     {
         position1 += shift_;
         position2 += shift_;
     }
     else
     {
         position1 -= shift_;
         position2 -= shift_;
     }
 }
References isClosestToLeftBoundary(), and shift_.
write()
void PeriodicBoundary::write (std::ostream & os) const override virtual
writes boundary properties to ostream
Writes boundary's properties to an ostream
Parameters
[in] os the ostream
Reimplemented from BasePeriodicBoundary.
Reimplemented in SubcriticalMaserBoundaryTEST.
 {
     BasePeriodicBoundary::write(os);
     os << " normal " << normal_
        << " scaleFactor " << scaleFactor_ // JMFT: I'd like to deprecate scaleFactor_
        << " distanceLeft " << distanceLeft_
        << " distanceRight " << distanceRight_
        << " shift " << shift_;
 }
References distanceLeft_, distanceRight_, normal_, scaleFactor_, shift_, and BasePeriodicBoundary::write().
Referenced by SubcriticalMaserBoundaryTEST::write().
Member Data Documentation
distanceLeft_
Mdouble PeriodicBoundary::distanceLeft_ protected
position of left edge, s.t. normal*x = distanceLeft_
Referenced by getDistance(), getDistanceLeft(), isClosestToLeftBoundary(), moveLeft(), moveRight(), oldRead(), PeriodicBoundary(), read(), set(), setPlanewiseShift(), SubcriticalMaserBoundaryTEST::SubcriticalMaserBoundaryTEST(), and write().
distanceRight_
Mdouble PeriodicBoundary::distanceRight_ protected
position of right edge, s.t. normal*x = distanceRight_
Referenced by getDistance(), SubcriticalMaserBoundaryTEST::getDistanceFromRight(), getDistanceRight(), isClosestToLeftBoundary(), moveLeft(), moveRight(), oldRead(), PeriodicBoundary(), read(), set(), setPlanewiseShift(), SubcriticalMaserBoundaryTEST::SubcriticalMaserBoundaryTEST(), and write().
normal_
Vec3D PeriodicBoundary::normal_ protected
outward unit normal vector for right edge
Referenced by getDistance(), SubcriticalMaserBoundaryTEST::getDistanceFromRight(), getNormal(), isClosestToLeftBoundary(), moveLeft(), moveRight(), oldRead(), PeriodicBoundary(), read(), set(), setPlanewiseShift(), and write().
scaleFactor_
Mdouble PeriodicBoundary::scaleFactor_ protected
This is the normal to rescale the normal vector to a unit vectors.
Referenced by moveLeft(), moveRight(), oldRead(), PeriodicBoundary(), read(), set(), and write().
shift_
Vec3D PeriodicBoundary::shift_ protected
shift from left to right boundary
Referenced by checkBoundaryAfterParticlesMove(), SubcriticalMaserBoundaryTEST::copyExtraParticles(), SubcriticalMaserBoundaryTEST::extendBottom(), getShift(), moveLeft(), moveRight(), oldRead(), PeriodicBoundary(), read(), set(), setPlanewiseShift(), shiftPosition(), shiftPositions(), and write().
The documentation for this class was generated from the following files:
PeriodicBoundary.h
PeriodicBoundary.cc