MercuryDPM: NurbsWall Class Reference
NurbsWall Class Reference
This function defines a wall via a NurbsSurface.
#include <NurbsWall.h>
Public Member Functions
NurbsWall ()
Default constructor: make a wall with default parameters.
NurbsWall (const NurbsWall &other)
Copy constructor, copies another wall.
NurbsWall (const NurbsSurface &nurbsSurface)
Constructor in which all parameters of the wall are set.
~NurbsWall ()
Default destructor.
NurbsWall * copy () const override
Copy this wall and return a pointer to the copy.
void set (const NurbsSurface &nurbsSurface)
Defines a wall, given a NurbsSurface.
bool getDistanceAndNormal (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return) const final
Compute the distance from the Screw for a given BaseParticle and return if there is a collision. If there is a collision, also return the normal vector of the interaction point.
void read (std::istream &is) override
Reads this wall from an input stream, for example a restart file.
void write (std::ostream &os) const override
Writes this wall to an output stream, for example a restart file.
std::string getName () const override
Returns the name of the object, here the string "Screw".
void writeVTK (VTKContainer &vtk) const override
void writeWallDetailsVTK (VTKData &data) const override
Public Member Functions inherited from BaseWall
BaseWall ()
Default constructor.
BaseWall (const BaseWall &w)
Copy constructor.
~BaseWall () override
Default destructor.
virtual bool getDistanceNormalOverlap (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual bool getDistanceNormalOverlapSuperquadric (const SuperQuadricParticle &p, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual Vec3D getFurthestPointSuperQuadric (const Vec3D &normalBodyFixed, const Vec3D &axes, Mdouble eps1, Mdouble eps2) const
virtual void setHandler (WallHandler *handler)
A function which sets the WallHandler for this BaseWall.
WallHandler * getHandler () const
A function which returns the WallHandler that handles this BaseWall.
void setIndSpecies (unsigned int indSpecies) override
Define the species of this wall using the index of the species in the SpeciesHandler in this DPMBase.
void setSpecies (const ParticleSpecies *species)
Defines the species of the current wall.
bool isFixed () const override
void setForceControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity={0, 0, 0})
Slowly adjusts the force on a wall towards a specified goal, by adjusting (prescribing) the velocity of the wall.
virtual bool isLocal (Vec3D &min, Vec3D &max) const
bool getLinePlaneIntersect (Vec3D &intersect, const Vec3D &p0, const Vec3D &p1, const Vec3D &n, const Vec3D &p)
bool isInsideWallVTK (const Vec3D &point, const Vec3D &normal, const Vec3D &position) const
void projectOntoWallVTK (Vec3D &point0, const Vec3D &point1, const Vec3D &normal, const Vec3D &position) const
void intersectVTK (std::vector< Vec3D > &points, Vec3D normal, Vec3D position) const
virtual BaseInteraction * getInteractionWithSuperQuad (SuperQuadricParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler)
void getVTK (std::vector< Vec3D > &points, std::vector< std::vector< double >> &triangleStrips)
const Vec3D getAxis () const
BaseInteraction * getInteractionWith (BaseParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler) override
Returns the interaction between this wall and a given particle, nullptr if there is no interaction.
virtual void actionsOnRestart ()
No implementation but can be overidden in its derived classes.
virtual void actionsAfterParticleGhostUpdate ()
No implementation but can be overidden in its derived classes.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
virtual void handleParticleRemoval (unsigned int id)
Handles the addition of particles to the particleHandler.
virtual void checkInteractions (InteractionHandler *interactionHandler, unsigned int timeStamp)
Check if all interactions are valid.
bool getVTKVisibility () const
void setVTKVisibility (bool vtkVisibility)
void addRenderedWall (BaseWall *w)
BaseWall * getRenderedWall (size_t i) const
std::vector< BaseWall * > getRenderedWalls () const
void removeRenderedWalls ()
void renderWall (VTKContainer &vtk)
void addParticlesAtWall (unsigned numElements=50)
void setVelocityControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity)
virtual void computeWear ()
Public Member Functions inherited from BaseInteractable
BaseInteractable ()
Default BaseInteractable constructor.
BaseInteractable (const BaseInteractable &p)
Copy constructor.
~BaseInteractable () override
Destructor, it simply destructs the BaseInteractable and all the objects it contains.
unsigned int getIndSpecies () const
Returns the index of the species associated with the interactable object.
const ParticleSpecies * getSpecies () const
Returns a pointer to the species of this BaseInteractable.
void setSpecies (const ParticleSpecies *species)
Sets the species of this BaseInteractable.
const Vec3D & getForce () const
Returns the force on this BaseInteractable.
const Vec3D & getTorque () const
Returns the torque on this BaseInteractable.
void setForce (const Vec3D &force)
Sets the force on this BaseInteractable.
void setTorque (const Vec3D &torque)
Sets the torque on this BaseInteractable.
void addForce (const Vec3D &addForce)
Adds an amount to the force on this BaseInteractable.
void addTorque (const Vec3D &addTorque)
Adds an amount to the torque on this BaseInteractable.
virtual void resetForceTorque (int numberOfOMPthreads)
void sumForceTorqueOMP ()
const Vec3D & getPosition () const
Returns the position of this BaseInteractable.
const Quaternion & getOrientation () const
Returns the orientation of this BaseInteractable.
virtual void setPosition (const Vec3D &position)
Sets the position of this BaseInteractable.
void setOrientationViaNormal (Vec3D normal)
Sets the orientation of this BaseInteractable by defining the vector that results from the rotation of the (1,0,0) vector.
void setOrientationViaEuler (Vec3D eulerAngle)
Sets the orientation of this BaseInteractable by defining the euler angles.
virtual void setOrientation (const Quaternion &orientation)
Sets the orientation of this BaseInteractable.
virtual void move (const Vec3D &move)
Moves this BaseInteractable by adding an amount to the position.
virtual void rotate (const Vec3D &angularVelocityDt)
Rotates this BaseInteractable.
const std::vector< BaseInteraction * > & getInteractions () const
Returns a list of interactions which belong to this interactable.
void addInteraction (BaseInteraction *I)
Adds an interaction to this BaseInteractable.
bool removeInteraction (BaseInteraction *I)
Removes an interaction from this BaseInteractable.
void copyInteractionsForPeriodicParticles (const BaseInteractable &p)
Copies interactions to this BaseInteractable whenever a periodic copy made.
void setVelocity (const Vec3D &velocity)
set the velocity of the BaseInteractable.
void setAngularVelocity (const Vec3D &angularVelocity)
set the angular velocity of the BaseInteractble.
void addVelocity (const Vec3D &velocity)
adds an increment to the velocity.
void addAngularVelocity (const Vec3D &angularVelocity)
add an increment to the angular velocity.
virtual const Vec3D & getVelocity () const
Returns the velocity of this interactable.
virtual const Vec3D & getAngularVelocity () const
Returns the angular velocity of this interactable.
void setPrescribedPosition (const std::function< Vec3D(double)> &prescribedPosition)
Allows the position of an infinite mass interactable to be prescribed.
void applyPrescribedPosition (double time)
Computes the position from the user defined prescribed position function.
void setPrescribedVelocity (const std::function< Vec3D(double)> &prescribedVelocity)
Allows the velocity of an infinite mass interactable to be prescribed.
void applyPrescribedVelocity (double time)
Computes the velocity from the user defined prescribed velocity function.
void setPrescribedOrientation (const std::function< Quaternion(double)> &prescribedOrientation)
Allows the orientation of the infinite mass interactbale to be prescribed.
void applyPrescribedOrientation (double time)
Computes the orientation from the user defined prescribed orientation function.
void setPrescribedAngularVelocity (const std::function< Vec3D(double)> &prescribedAngularVelocity)
Allows the angular velocity of the infinite mass interactable to be prescribed.
void applyPrescribedAngularVelocity (double time)
Computes the angular velocity from the user defined prescribed angular velocity.
virtual const Vec3D getVelocityAtContact (const Vec3D &contact) const
Returns the velocity at the contact point, use by many force laws.
void integrateBeforeForceComputation (double time, double timeStep)
This is part of integrate routine for objects with infinite mass.
void integrateAfterForceComputation (double time, double timeStep)
This is part of the integration routine for objects with infinite mass.
virtual Mdouble getInvMass () const
virtual Mdouble getCurvature (const Vec3D &labFixedCoordinates) const
virtual bool isFaceContact (const Vec3D &normal) const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Protected Attributes
NurbsSurface nurbsSurface_
Additional Inherited Members
Static Public Member Functions inherited from BaseWall
static void addToVTK (const std::vector< Vec3D > &points, VTKContainer &vtk)
Takes the points provided and adds a triangle strip connecting these points to the vtk container.
Detailed Description
This function defines a wall via a NurbsSurface.
Constructor & Destructor Documentation
NurbsWall() [1/3]
NurbsWall::NurbsWall ()
Default constructor: make a wall with default parameters.
Make a default NurbsWall which is centered in the origin, has a length of 1, one revelation, a radius of 1, turns with 1 revelation per second, is infinitely thin and starts at its normal initial point.
 {
     logger(DEBUG, "NurbsWall() constructor finished.");
 }
References DEBUG, and logger.
Referenced by copy().
NurbsWall() [2/3]
NurbsWall::NurbsWall (const NurbsWall & other)
Copy constructor, copies another wall.
Parameters
[in] other The NurbsWall that has to be copied.
     : BaseWall(other), nurbsSurface_(other.nurbsSurface_)
 {
     logger(DEBUG, "NurbsWall(const NurbsWall&) copy constructor finished.");
 }
References DEBUG, and logger.
NurbsWall() [3/3]
NurbsWall::NurbsWall (const NurbsSurface & nurbsSurface)
Constructor in which all parameters of the wall are set.
     : nurbsSurface_(nurbsSurface)
 {
     logger(DEBUG, "NurbsWall(const NurbsSurface&) constructor finished.");
 }
References DEBUG, and logger.
~NurbsWall()
NurbsWall::~NurbsWall ()
Default destructor.
 {
     logger(DEBUG, "~NurbsWall() finished, destroyed the wall.");
 }
References DEBUG, and logger.
Member Function Documentation
copy()
NurbsWall * NurbsWall::copy () const override virtual
Copy this wall and return a pointer to the copy.
Implements BaseWall.
Reimplemented in WearableNurbsWall.
 {
     return new NurbsWall(*this);
 }
References NurbsWall().
getDistanceAndNormal()
bool NurbsWall::getDistanceAndNormal (const BaseParticle & P, Mdouble & distance, Vec3D & normal_return) const final virtual
Compute the distance from the Screw for a given BaseParticle and return if there is a collision. If there is a collision, also return the normal vector of the interaction point.
Implements BaseWall.
 {
     //transform coordinates into position-orientation frame
     Vec3D position = p.getPosition() - getPosition();
     getOrientation().rotateBack(position);
     BaseSpecies* s = getHandler()->getDPMBase()->speciesHandler.getMixedObject(p.getSpecies(),getSpecies());
     if (nurbsSurface_.getDistance(position, p.getRadius()+s->getInteractionDistance(), distance, normal_return)) {
         getOrientation().rotate(normal_return);
         return true;
     } else {
         return false;
     }
 }
References NurbsSurface::getDistance(), BaseHandler< T >::getDPMBase(), BaseWall::getHandler(), SpeciesHandler::getMixedObject(), BaseInteractable::getOrientation(), BaseInteractable::getPosition(), BaseInteractable::getSpecies(), nurbsSurface_, p, Quaternion::rotate(), Quaternion::rotateBack(), s, and DPMBase::speciesHandler.
getName()
std::string NurbsWall::getName () const override virtual
Returns the name of the object, here the string "Screw".
Returns
The string "NurbsWall".
Implements BaseObject.
Reimplemented in WearableNurbsWall.
 {
     return "NurbsWall";
 }
read()
void NurbsWall::read (std::istream & is) override virtual
Reads this wall from an input stream, for example a restart file.
Parameters
[in,out] is Input stream from which the wall must be read.
Reimplemented from BaseWall.
Reimplemented in WearableNurbsWall.
 {
     BaseWall::read(is);
     std::string dummy;
     is >> dummy;
     is >> nurbsSurface_;
 }
References nurbsSurface_, BaseWall::read(), and oomph::Global_string_for_annotation::string().
Referenced by WearableNurbsWall::read().
set()
void NurbsWall::set (const NurbsSurface & nurbsSurface)
Defines a wall, given a NurbsSurface.
{
     nurbsSurface_ = nurbsSurface;
 }
References nurbsSurface_.
Referenced by main().
write()
void NurbsWall::write (std::ostream & os) const override virtual
Writes this wall to an output stream, for example a restart file.
Parameters
[in,out] os Output stream to which the wall must be written.
Reimplemented from BaseWall.
Reimplemented in WearableNurbsWall.
 {
     BaseWall::write(os);
     os << " NurbsSurface " << nurbsSurface_;
 }
References nurbsSurface_, and BaseWall::write().
Referenced by WearableNurbsWall::write().
writeVTK()
void NurbsWall::writeVTK (VTKContainer & vtk) const override virtual
adds extra information to the points and triangleStrips vectors needed to plot the wall in vtk format
Parameters
points Coordinates of the vertices of the triangulated surfaces (in the VTK file this is called POINTS)
triangleStrips Indices of three vertices forming one triangulated surface (in the VTK file this is called CELL)
Reimplemented from BaseWall.
 {
     unsigned nu = 5 * nurbsSurface_.getControlPoints().size();
     unsigned nv = 5 * nurbsSurface_.getControlPoints()[0].size();
     const double lbU = nurbsSurface_.getLowerBoundU();
     const double ubU = nurbsSurface_.getUpperBoundU();
     const double lbV = nurbsSurface_.getLowerBoundV();
     const double ubV = nurbsSurface_.getUpperBoundV();
     //create points
     size_t nPoints = vtk.points.size();
     for (double u = 0; u <= nu; u++) {
         for (double v = 0; v <= nv; v++) {
             Vec3D p = nurbsSurface_.evaluate(lbU+(ubU-lbU)*u/nu, lbV+(ubV-lbV)*v/nv);
             getOrientation().rotate(p);
             p += getPosition();
             vtk.points.push_back(p);
         }
     }
     //create connectivity matrix
     //vtk.triangleStrips.reserve(vtk.triangleStrips.size()+nu);
     for (unsigned i = 0; i < nu; ++i) {
         std::vector<double> cell;
         cell.reserve(2*nv);
         for (unsigned j = 0; j <= nv; ++j) {
             cell.push_back(nPoints + j + i * (nv+1));
             cell.push_back(nPoints + j + (i+1) * (nv+1));
         }
         vtk.triangleStrips.push_back(cell);
     }
 }
References NurbsSurface::evaluate(), NurbsSurface::getControlPoints(), NurbsSurface::getLowerBoundU(), NurbsSurface::getLowerBoundV(), BaseInteractable::getOrientation(), BaseInteractable::getPosition(), NurbsSurface::getUpperBoundU(), NurbsSurface::getUpperBoundV(), i, j, nurbsSurface_, p, VTKContainer::points, Quaternion::rotate(), VTKContainer::triangleStrips, and v.
writeWallDetailsVTK()
void NurbsWall::writeWallDetailsVTK (VTKData & data) const override virtual
Reimplemented from BaseWall.
Reimplemented in WearableNurbsWall.
 {
     const std::vector<std::vector<Vec3D>>& controlPoints = nurbsSurface_.getControlPoints();
     const std::vector<std::vector<double>>& weights = nurbsSurface_.getWeights();
     // Reserve memory for number of points and cells about to be added
     const unsigned int np = controlPoints.size() * controlPoints[0].size();
     const unsigned int nc = (controlPoints.size() - 1) * (controlPoints[0].size() - 1);
     data.reservePoints(np, { "Weight", "ID" });
     data.reserveCells(nc);
     // Number of points in v-direction
     size_t nv = controlPoints[0].size();
     // Point index offset, the point indices have to be offset by the number of points already present at the start (from previously added data)
     size_t pio = data.getPoints().size();
     // Get last id only when possible and increment it, otherwise start with 0
     double id = data.getPointData()["ID"].empty() ? 0 : data.getPointData()["ID"].back() + 1;
     for (int i = 0; i < controlPoints.size(); i++)
     {
         for (int j = 0; j < controlPoints[i].size(); j++)
         {
             Vec3D p = controlPoints[i][j];
             getOrientation().rotate(p);
             p += getPosition();
             data.addToPoints(p);
             data.addToPointData("Weight", weights[i][j]);
             data.addToPointData("ID", id);
             if (i > 0 && j > 0)
             {
                 // Basic 2D/1D mapping for indexing: nv * i + j (+ point index offset)
                 // 4 points to form a rectangle: point, point to the left, point down, point to the left and down
                 data.addToConnectivity({ nv*i+j+pio, nv*(i-1)+j+pio, nv*i+j-1+pio, nv*(i-1)+j-1+pio });
                 data.addToTypes(8);
             }
         }
     }
 }
References data, NurbsSurface::getControlPoints(), BaseInteractable::getOrientation(), BaseInteractable::getPosition(), NurbsSurface::getWeights(), i, j, nurbsSurface_, p, Quaternion::rotate(), size, and calibrate::weights.
Member Data Documentation
nurbsSurface_
NurbsSurface NurbsWall::nurbsSurface_ protected
Referenced by getDistanceAndNormal(), WearableNurbsWall::getVolumeUnderSurface(), WearableNurbsWall::moveControlPoint(), WearableNurbsWall::processDebris(), read(), set(), WearableNurbsWall::set(), WearableNurbsWall::storeDebris(), write(), writeVTK(), writeWallDetailsVTK(), and WearableNurbsWall::writeWallDetailsVTK().
The documentation for this class was generated from the following files:
NurbsWall.h
NurbsWall.cc