MercuryDPM: oomph::PMLTimeHarmonicIsotropicElasticityTensor Class Reference
oomph::PMLTimeHarmonicIsotropicElasticityTensor Class Reference
#include <pml_time_harmonic_elasticity_tensor.h>
Public Member Functions
PMLTimeHarmonicIsotropicElasticityTensor (const double &nu, const double &E)
PMLTimeHarmonicIsotropicElasticityTensor (const double &nu)
double nu () const
Poisson's ratio.
void update_constitutive_parameters (const double &nu, const double &E=1.0)
std::complex< double > independent_component (const unsigned &i) const
Overload the independent coefficient function.
Public Member Functions inherited from oomph::PMLTimeHarmonicElasticityTensor
virtual ~PMLTimeHarmonicElasticityTensor ()
Empty virtual Destructor.
std::complex< double > operator() (const unsigned &i, const unsigned &j, const unsigned &k, const unsigned &l) const
Private Member Functions
void set_lame_coefficients (const double &lambda, const double &mu)
Private Attributes
std::complex< double > C [4]
Storage for the independent components of the elasticity tensor.
double Nu
Poisson's ratio.
Static Private Attributes
static const unsigned StaticIndex [21]
Translation scheme for the isotropic elasticity tensor.
Additional Inherited Members
Protected Member Functions inherited from oomph::PMLTimeHarmonicElasticityTensor
void range_check (const unsigned &i, const unsigned &j, const unsigned &k, const unsigned &l) const
PMLTimeHarmonicElasticityTensor ()
Empty Constructor.
Detailed Description
An isotropic elasticity tensor defined in terms of Young's modulus and Poisson's ratio. The elasticity tensor is assumed to be non-dimensionalised on some reference value for Young's modulus so the value provided to the constructor (if any) is to be interpreted as the ratio of the actual Young's modulus to the Young's modulus used to non-dimensionalise the stresses/tractions in the governing equations.
Constructor & Destructor Documentation
PMLTimeHarmonicIsotropicElasticityTensor() [1/2]
oomph::PMLTimeHarmonicIsotropicElasticityTensor::PMLTimeHarmonicIsotropicElasticityTensor (const double & nu, const double & E) inline
Constructor. Passing in the values of the Poisson's ratio and Young's modulus (interpreted as the ratio of the actual Young's modulus to the Young's modulus (or other reference stiffness) used to non-dimensionalise stresses and tractions in the governing equations).
       : PMLTimeHarmonicElasticityTensor(), Nu(nu)
     {
       // Set the three indepdent components
       C[0] = std::complex<double>(0.0, 0.0);
       double lambda = E * nu / ((1.0 + nu) * (1.0 - 2.0 * nu));
       double mu = E / (2.0 * (1.0 + nu));
       this->set_lame_coefficients(lambda, mu);
     }
References Global_Physical_Variables::E, lambda, Global_Parameters::mu, nu(), and set_lame_coefficients().
PMLTimeHarmonicIsotropicElasticityTensor() [2/2]
oomph::PMLTimeHarmonicIsotropicElasticityTensor::PMLTimeHarmonicIsotropicElasticityTensor (const double & nu) inline
Constructor. Passing in the value of the Poisson's ratio. Stresses and tractions in the governing equations are assumed to have been non-dimensionalised on Young's modulus.
       : PMLTimeHarmonicElasticityTensor(), Nu(nu)
     {
       // Set the three indepdent components
       C[0] = std::complex<double>(0.0, 0.0);
       // reference value
       double E = 1.0;
       double lambda = E * nu / ((1.0 + nu) * (1.0 - 2.0 * nu));
       double mu = E / (2.0 * (1.0 + nu));
       this->set_lame_coefficients(lambda, mu);
     }
References Global_Physical_Variables::E, lambda, Global_Parameters::mu, nu(), and set_lame_coefficients().
Member Function Documentation
independent_component()
std::complex<double> oomph::PMLTimeHarmonicIsotropicElasticityTensor::independent_component (const unsigned & i) const inline virtual
Overload the independent coefficient function.
Reimplemented from oomph::PMLTimeHarmonicElasticityTensor.
     {
       return C[StaticIndex[i]];
     }
References i, and StaticIndex.
nu()
double oomph::PMLTimeHarmonicIsotropicElasticityTensor::nu () const inline
Poisson's ratio.
     {
       return Nu;
     }
References Nu.
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::nu(), PMLTimeHarmonicIsotropicElasticityTensor(), and update_constitutive_parameters().
set_lame_coefficients()
void oomph::PMLTimeHarmonicIsotropicElasticityTensor::set_lame_coefficients (const double & lambda, const double & mu) inline private
     {
       C[1] = lambda + 2.0 * mu;
       C[2] = lambda;
       C[3] = mu;
     }
References lambda, and Global_Parameters::mu.
Referenced by PMLTimeHarmonicIsotropicElasticityTensor(), and update_constitutive_parameters().
update_constitutive_parameters()
void oomph::PMLTimeHarmonicIsotropicElasticityTensor::update_constitutive_parameters (const double & nu, const double & E = 1.0) inline
Update parameters: Specify values of the Poisson's ratio and (optionally) Young's modulus (interpreted as the ratio of the actual Young's modulus to the Young's modulus (or other reference stiffness) used to non-dimensionalise stresses and tractions in the governing equations).
     {
       // Set the three indepdent components
       C[0] = std::complex<double>(0.0, 0.0);
       double lambda = E * nu / ((1.0 + nu) * (1.0 - 2.0 * nu));
       double mu = E / (2.0 * (1.0 + nu));
       this->set_lame_coefficients(lambda, mu);
     }
References Global_Physical_Variables::E, lambda, Global_Parameters::mu, nu(), and set_lame_coefficients().
Member Data Documentation
C
std::complex<double> oomph::PMLTimeHarmonicIsotropicElasticityTensor::C[4] private
Storage for the independent components of the elasticity tensor.
Nu
double oomph::PMLTimeHarmonicIsotropicElasticityTensor::Nu private
Poisson's ratio.
Referenced by nu().
StaticIndex
const unsigned oomph::PMLTimeHarmonicIsotropicElasticityTensor::StaticIndex static private
Initial value:
= {
    1, 0, 2, 3, 0, 1, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 0, 2, 3, 0, 1}
Translation scheme for the isotropic elasticity tensor.
Translation scheme between the 21 independent components of the general elasticity tensor and the isotropic case
Referenced by independent_component().
The documentation for this class was generated from the following files:
pml_time_harmonic_elasticity_tensor.h
pml_time_harmonic_elasticity_tensor.cc