MercuryDPM: Eigen::internal::random_default_impl< Scalar, true, false > Struct Template Reference
Eigen::internal::random_default_impl< Scalar, true, false > Struct Template Reference
#include <RandomImpl.h>
Public Types
typedef NumTraits< Scalar >::Real RealScalar
using Impl = random_impl< RealScalar >
Static Public Member Functions
static EIGEN_DEVICE_FUNC Scalar run (const Scalar &x, const Scalar &y, int numRandomBits)
static EIGEN_DEVICE_FUNC Scalar run (const Scalar &x, const Scalar &y)
static EIGEN_DEVICE_FUNC Scalar run (int numRandomBits)
static EIGEN_DEVICE_FUNC Scalar run ()
Member Typedef Documentation
Impl
template<typename Scalar > using Eigen::internal::random_default_impl< Scalar, true, false >::Impl = random_impl<RealScalar>
RealScalar
template<typename Scalar > typedef NumTraits<Scalar>::Real Eigen::internal::random_default_impl< Scalar, true, false >::RealScalar
Member Function Documentation
run() [1/4]
template<typename Scalar > static EIGEN_DEVICE_FUNC Scalar Eigen::internal::random_default_impl< Scalar, true, false >::run () inline static
 { return Scalar(Impl::run(), Impl::run()); }
References run().
run() [2/4]
template<typename Scalar > static EIGEN_DEVICE_FUNC Scalar Eigen::internal::random_default_impl< Scalar, true, false >::run (const Scalar & x, const Scalar & y) inline static
{
     return Scalar(Impl::run(x.real(), y.real()), Impl::run(x.imag(), y.imag()));
   }
References run(), plotDoE::x, and Eigen::internal::y.
run() [3/4]
template<typename Scalar > static EIGEN_DEVICE_FUNC Scalar Eigen::internal::random_default_impl< Scalar, true, false >::run (const Scalar & x, const Scalar & y, int numRandomBits) inline static
{
     return Scalar(Impl::run(x.real(), y.real(), numRandomBits), Impl::run(x.imag(), y.imag(), numRandomBits));
   }
References run(), plotDoE::x, and Eigen::internal::y.
run() [4/4]
template<typename Scalar > static EIGEN_DEVICE_FUNC Scalar Eigen::internal::random_default_impl< Scalar, true, false >::run (int numRandomBits) inline static
{
     return Scalar(Impl::run(numRandomBits), Impl::run(numRandomBits));
   }
References run().
The documentation for this struct was generated from the following file:
RandomImpl.h