MercuryDPM: GlMatrixHelper< true, Flags_ > Struct Template Reference
GlMatrixHelper< true, Flags_ > Struct Template Reference
#include <gpuhelper.h>
Static Public Member Functions
static void loadMatrix (const Matrix< float, 4, 4, Flags_, 4, 4 > &mat)
static void loadMatrix (const Matrix< double, 4, 4, Flags_, 4, 4 > &mat)
static void multMatrix (const Matrix< float, 4, 4, Flags_, 4, 4 > &mat)
static void multMatrix (const Matrix< double, 4, 4, Flags_, 4, 4 > &mat)
Member Function Documentation
loadMatrix() [1/2]
template<int Flags_> static void GlMatrixHelper< true, Flags_ >::loadMatrix (const Matrix< double, 4, 4, Flags_, 4, 4 > & mat) inline static
{
     glLoadMatrixd(mat.transpose().eval().data());
   }
References Eigen::SparseMatrixBase< Derived >::transpose().
loadMatrix() [2/2]
template<int Flags_> static void GlMatrixHelper< true, Flags_ >::loadMatrix (const Matrix< float, 4, 4, Flags_, 4, 4 > & mat) inline static
 { glLoadMatrixf(mat.transpose().eval().data()); }
References Eigen::SparseMatrixBase< Derived >::transpose().
multMatrix() [1/2]
template<int Flags_> static void GlMatrixHelper< true, Flags_ >::multMatrix (const Matrix< double, 4, 4, Flags_, 4, 4 > & mat) inline static
{
     glMultMatrixd(mat.transpose().eval().data());
   }
References Eigen::SparseMatrixBase< Derived >::transpose().
multMatrix() [2/2]
template<int Flags_> static void GlMatrixHelper< true, Flags_ >::multMatrix (const Matrix< float, 4, 4, Flags_, 4, 4 > & mat) inline static
 { glMultMatrixf(mat.transpose().eval().data()); }
References Eigen::SparseMatrixBase< Derived >::transpose().
The documentation for this struct was generated from the following file:
gpuhelper.h