MercuryDPM: oomph::OneDimensionalLegendreShape< NNODE_1D > Class Template Reference
oomph::OneDimensionalLegendreShape< NNODE_1D > Class Template Reference
Class that returns the shape functions associated with legendre.
#include <shape.h>
Public Member Functions
OneDimensionalLegendreShape (const double &s)
Constructor.
Public Member Functions inherited from oomph::Shape
Shape (const unsigned &N)
Constructor for a single-index set of shape functions.
Shape (const unsigned &N, const unsigned &M)
Constructor for a two-index set of shape functions.
Shape (const Shape &shape)=delete
Broken copy constructor.
Shape ()
void operator= (const Shape &shape)
void operator= (Shape *const &shape_pt)
~Shape ()
Destructor, clear up the memory allocated by the object.
void resize (const unsigned &N, const unsigned &M=1)
Change the size of the storage.
double & operator[] (const unsigned &i)
Overload the bracket operator to provide access to values.
const double & operator[] (const unsigned &i) const
Overload the bracket operator (const version)
double & operator() (const unsigned &i)
Overload the round bracket operator to provide access to values.
const double & operator() (const unsigned &i) const
Overload the round bracket operator (const version)
double & operator() (const unsigned &i, const unsigned &j)
Overload the round bracket operator, allowing for two indices.
const double & operator() (const unsigned &i, const unsigned &j) const
unsigned nindex1 () const
Return the range of index 1 of the shape function object.
unsigned nindex2 () const
Return the range of index 2 of the shape function object.
Static Public Member Functions
static void calculate_nodal_positions ()
Static function used to populate the stored positions.
static double nodal_position (const unsigned &n)
Static Public Attributes
static Vector< double > z
Static Private Attributes
static bool Nodes_calculated = false
Additional Inherited Members
Protected Member Functions inherited from oomph::Shape
void range_check (const unsigned &i, const unsigned &j) const
Private function that checks whether the index is in range.
Protected Attributes inherited from oomph::Shape
double * Psi
double * Allocated_storage
unsigned Index1
Size of the first index of the shape function.
unsigned Index2
Size of the second index of the shape function.
Detailed Description
template<unsigned NNODE_1D>
class oomph::OneDimensionalLegendreShape< NNODE_1D >
Class that returns the shape functions associated with legendre.
Constructor & Destructor Documentation
OneDimensionalLegendreShape()
template<unsigned NNODE_1D> oomph::OneDimensionalLegendreShape< NNODE_1D >::OneDimensionalLegendreShape (const double & s) inline
Constructor.
                                                  : Shape(NNODE_1D)
     {
       using namespace Orthpoly;
       unsigned p = NNODE_1D - 1;
       // Now populate the shape function
       for (unsigned i = 0; i < NNODE_1D; i++)
       {
         // If we're at one of the nodes, the value must be 1.0
         if (std::fabs(s - z[i]) < Orthpoly::eps)
         {
           (*this)[i] = 1.0;
         }
         // Otherwise use the lagrangian interpolant
         else
         {
           (*this)[i] = (1.0 - s * s) * dlegendre(p, s) /
                        (p * (p + 1) * legendre(p, z[i]) * (z[i] - s));
         }
       }
     }
References oomph::Orthpoly::dlegendre(), oomph::Orthpoly::eps, boost::multiprecision::fabs(), i, oomph::Orthpoly::legendre(), p, s, and oomph::OneDimensionalLegendreShape< NNODE_1D >::z.
Member Function Documentation
calculate_nodal_positions()
template<unsigned NNODE_1D> static void oomph::OneDimensionalLegendreShape< NNODE_1D >::calculate_nodal_positions () inline static
Static function used to populate the stored positions.
     {
       if (!Nodes_calculated)
       {
         Orthpoly::gll_nodes(NNODE_1D, z);
         Nodes_calculated = true;
       }
     }
References oomph::Orthpoly::gll_nodes(), oomph::OneDimensionalLegendreShape< NNODE_1D >::Nodes_calculated, and oomph::OneDimensionalLegendreShape< NNODE_1D >::z.
Referenced by oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::dshape_local(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::dshape_local(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::dshape_local(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::local_coordinate_of_node(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::local_coordinate_of_node(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::local_coordinate_of_node(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::local_one_d_fraction_of_node(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::local_one_d_fraction_of_node(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::local_one_d_fraction_of_node(), oomph::QSpectralElement< 1, NNODE_1D >::QSpectralElement(), oomph::QSpectralElement< 2, NNODE_1D >::QSpectralElement(), oomph::QSpectralElement< 3, NNODE_1D >::QSpectralElement(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::shape(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::shape(), and oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::shape().
nodal_position()
template<unsigned NNODE_1D> static double oomph::OneDimensionalLegendreShape< NNODE_1D >::nodal_position (const unsigned & n) inline static
     {
       return z[n];
     }
References n, and oomph::OneDimensionalLegendreShape< NNODE_1D >::z.
Referenced by oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::local_coordinate_of_node(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::local_coordinate_of_node(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::local_coordinate_of_node(), oomph::QSpectralElement< 1, NNODE_1D >::local_coordinate_of_node(), oomph::QSpectralElement< 2, NNODE_1D >::local_coordinate_of_node(), oomph::QSpectralElement< 3, NNODE_1D >::local_coordinate_of_node(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::local_one_d_fraction_of_node(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::local_one_d_fraction_of_node(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::local_one_d_fraction_of_node(), oomph::QSpectralElement< 1, NNODE_1D >::local_one_d_fraction_of_node(), oomph::QSpectralElement< 2, NNODE_1D >::local_one_d_fraction_of_node(), and oomph::QSpectralElement< 3, NNODE_1D >::local_one_d_fraction_of_node().
Member Data Documentation
Nodes_calculated
template<unsigned NNODE_1D> bool oomph::OneDimensionalLegendreShape< NNODE_1D >::Nodes_calculated = false static private
Referenced by oomph::OneDimensionalLegendreShape< NNODE_1D >::calculate_nodal_positions().
z
template<unsigned NNODE_1D> Vector< double > oomph::OneDimensionalLegendreShape< NNODE_1D >::z static
Referenced by oomph::OneDimensionalLegendreShape< NNODE_1D >::calculate_nodal_positions(), oomph::OneDimensionalLegendreShape< NNODE_1D >::nodal_position(), oomph::OneDimensionalLegendreDShape< NNODE_1D >::OneDimensionalLegendreDShape(), and oomph::OneDimensionalLegendreShape< NNODE_1D >::OneDimensionalLegendreShape().
The documentation for this class was generated from the following file:
shape.h