MercuryDPM: test_equal_order_galerkin.cc File Reference
test_equal_order_galerkin.cc File Reference
#include "generic.h"
#include "space_time_unsteady_heat_equal_order_galerkin.h"
#include "meshes/simple_cubic_mesh.h"
#include "space_time_block_preconditioner.h"
Classes
class UnsteadyHeatProblem< ELEMENT >
UnsteadyHeat problem.
Namespaces
GlobalParameters
Global parameters.
SinSolution
Namespace for forced exact solution for UnsteadyHeat equation.
Functions
double GlobalParameters::round (const double &d)
---------------------------------------—DOCUMENTATION HELPERS---—
void SinSolution::get_exact_u (const double &t, const Vector< double > &x, Vector< double > &u)
Exact solution as a vector.
void SinSolution::get_exact_u (const double &t, const Vector< double > &x, double &u)
Exact solution as a scalar.
void SinSolution::get_source (const double &t, const Vector< double > &x, double &source)
Source function to make it an exact solution.
int main (int argc, char *argv[])
Driver code for unsteady heat equation.
Variables
double GlobalParameters::L_x =1.0
------------------—Unsteady Heat Parameters---------------------—
double GlobalParameters::L_y =1.0
Length of the mesh in the y-direction.
unsigned GlobalParameters::N_x =10
Number of elements in the x-direction.
unsigned GlobalParameters::N_y =10
Number of elements in the y-direction.
unsigned GlobalParameters::Element_order =1
The order of the FE interpolation.
bool GlobalParameters::Apply_time_periodic_boundary_conditions =true
Should we apply time-periodic boundary conditions?
double SinSolution::U_shift =8.0
Function Documentation
main()
int main (int argc , char * argv[])
Driver code for unsteady heat equation.
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
 {
 #ifdef OOMPH_HAS_MPI
   // Initialise MPI
   MPI_Helpers::init(argc,argv);
   // Switch off output modifier
   oomph_info.output_modifier_pt()=&default_output_modifier;
   // Switch off oomph_info output for all processors but rank 0
   if (MPI_Helpers::communicator_pt()->my_rank()!=0)
   {
     oomph_info.stream_pt()=&oomph_nullstream;
     OomphLibWarning::set_stream_pt(&oomph_nullstream);
     OomphLibError::set_stream_pt(&oomph_nullstream);
   }
   else
   {
     oomph_info << "\n=====================================================\n"
                << "Number of processors: "
                << MPI_Helpers::communicator_pt()->nproc()
                << "\n=====================================================\n"
                << std::endl;
   }
 #endif
   // Output directory
   GlobalParameters::Doc_info.set_directory("RESLT");
   // Start the timer
   double timer_s=TimingHelpers::timer();
   // Typedef the block element type
   typedef RefineableQUnsteadyHeatSpaceTimeElement<2,3> ELEMENT;
   // -------
   // TEST 1:
   // -------
   // Solve the problem using time-periodic boundary conditions.
   // NOTE: We can't just re-apply the boundary conditions for TEST 2 (where
   // we solve the initial-value problem) as applying periodic boundary
   // conditions involves copying nodes so we'd also have to regenerate
   // the mesh. It's easier just to create another Problem...
   {
     // Tell the user
     oomph_info << ANSIEscapeCode::Green
                << "\nTest 1: Solving with time-periodic boundary conditions!"
                << ANSIEscapeCode::Reset << std::endl;
     // Use time-periodic boundary conditions
     GlobalParameters::Apply_time_periodic_boundary_conditions=true;
     // Create a Problem pointer
     UnsteadyHeatProblem<ELEMENT> problem(&SinSolution::get_source);
     // Solve the space-time problem
     problem.newton_solve();
     // Document the solution
     problem.doc_solution();
     // Take timestep
     problem.adapt();
     // Solve the space-time problem
     problem.newton_solve();
     // Document the solution
     problem.doc_solution();
   } // End of TEST 1
   // -------
   // TEST 2:
   // -------
   // Solve the problem using Dirichlet boundary conditions and an initial
   // condition.
   {
     // Tell the user
     oomph_info << ANSIEscapeCode::Green
                << "\nTest 2: Solving with an initial condition!"
                << ANSIEscapeCode::Reset << std::endl;
     // Reset the documentation counter
     GlobalParameters::Doc_info.number()=0;
     // Use time-periodic boundary conditions
     GlobalParameters::Apply_time_periodic_boundary_conditions=false;
     // Create a Problem pointer
     UnsteadyHeatProblem<ELEMENT> problem(&SinSolution::get_source);
     // Solve the space-time problem
     problem.newton_solve();
     // Document the solution
     problem.doc_solution();
     // Take timestep
     problem.adapt();
     // Solve the space-time problem
     problem.newton_solve();
     // Document the solution
     problem.doc_solution();
   } // End of TEST 2
   // Tell the user we're done
   oomph_info << "\n3D space-time simulation complete!"
              << "\nTotal time for simulation [sec]: "
              << TimingHelpers::timer()-timer_s << "\n" << std::endl;
 } // End of main
References GlobalParameters::Apply_time_periodic_boundary_conditions, oomph::default_output_modifier, GlobalParameters::Doc_info, SinSolution::get_source(), oomph::ANSIEscapeCode::Green, oomph::DocInfo::number(), oomph::oomph_info, oomph::oomph_nullstream, oomph::OomphInfo::output_modifier_pt(), problem, oomph::ANSIEscapeCode::Reset, oomph::DocInfo::set_directory(), and oomph::OomphInfo::stream_pt().