MercuryDPM: WallDetailsVTKWriter Class Reference
WallDetailsVTKWriter Class Reference final
#include <WallDetailsVTKWriter.h>
Public Member Functions
WallDetailsVTKWriter (WallHandler &wallHandler)
WallDetailsVTKWriter (const WallDetailsVTKWriter &)=default
void writeVTK () const override
std::string getName () const
Public Member Functions inherited from BaseVTKWriter< WallHandler >
BaseVTKWriter (WallHandler &handler)
BaseVTKWriter (const BaseVTKWriter &other)
unsigned getFileCounter () const
void setFileCounter (unsigned fileCounter)
void setOutputDirectory (const std::string &dir)
const std::string & getOutputDirectory () const
std::string getFileName () const
Private Member Functions
bool shouldWrite (WallHandler::DetailsVTKOptions) const
std::string generateFileName (const std::string &identifier) const
Additional Inherited Members
Protected Member Functions inherited from BaseVTKWriter< WallHandler >
std::fstream makeVTKFileWithHeader () const
void writeVTKFooterAndClose (std::fstream &file) const
Protected Attributes inherited from BaseVTKWriter< WallHandler >
WallHandler & handler_
particle handler from which the particles should be written
unsigned int fileCounter
std::string outputDirectory_
Constructor & Destructor Documentation
WallDetailsVTKWriter() [1/2]
WallDetailsVTKWriter::WallDetailsVTKWriter (WallHandler & wallHandler) inline explicit
Non-default constructor; sets the handler and fileCounter
                                                             : BaseVTKWriter(wallHandler)
     {}
WallDetailsVTKWriter() [2/2]
WallDetailsVTKWriter::WallDetailsVTKWriter (const WallDetailsVTKWriter &) default
Default copy constructor
Member Function Documentation
generateFileName()
std::string WallDetailsVTKWriter::generateFileName (const std::string & identifier) const private
 {
     return outputDirectory_ + "/" + handler_.getDPMBase()->getName() + "WallDetails" + identifier + "_" + std::to_string(fileCounter) + ".vtu";
 }
References BaseVTKWriter< WallHandler >::fileCounter, BaseHandler< T >::getDPMBase(), DPMBase::getName(), BaseVTKWriter< WallHandler >::handler_, BaseVTKWriter< WallHandler >::outputDirectory_, and oomph::StringConversion::to_string().
Referenced by writeVTK().
getName()
std::string WallDetailsVTKWriter::getName () const inline
The name of the class in the restart file
     { return "WallDetailsVTKWriter"; }
shouldWrite()
bool WallDetailsVTKWriter::shouldWrite (WallHandler::DetailsVTKOptions type) const private
 {
     FileType fileType = handler_.getWriteDetailsVTK(type);
     return (fileType == FileType::ONE_FILE && fileCounter == 0) || fileType == FileType::MULTIPLE_FILES || fileType == FileType::MULTIPLE_FILES_PADDED;
 }
References BaseVTKWriter< WallHandler >::fileCounter, WallHandler::getWriteDetailsVTK(), BaseVTKWriter< WallHandler >::handler_, MULTIPLE_FILES, MULTIPLE_FILES_PADDED, ONE_FILE, and compute_granudrum_aor::type.
Referenced by writeVTK().
writeVTK()
void WallDetailsVTKWriter::writeVTK () const override virtual
Writes a vtk file
Implements BaseVTKWriter< WallHandler >.
 {
     if (PROCESSOR_ID != 0) return;
     // For each type of wall a VTKData object needs to be created, as each type is written to a different vtu file
     VTKData dataNurbsWall;
     VTKData dataWearableNurbsWall;
     //VTKData dataOtherTypeOfWall;
     bool nw_sw = shouldWrite(WallHandler::DetailsVTKOptions::NURBSWALL);
     bool wnw_sw = shouldWrite(WallHandler::DetailsVTKOptions::WEARABLENURBSWALL);
     // Loop through all wall and check if they belong to a certain type and if the data should be written or not
     for (const auto& w : handler_)
     {
         // WearableNurbsWall inherits from NurbsWall, therefore make sure to differentiate between them.
         // To prevent many of the same castings, first check if any of the two needs to be written.
         if (nw_sw || wnw_sw)
         {
             // Just a single cast to WearableNurbsWall and NurbsWall
             auto wnw_ptr = dynamic_cast<WearableNurbsWall*>(w);
             // NurbsWall: should be written and correct type (a valid cast is possible)
             if (nw_sw && dynamic_cast<NurbsWall*>(w))
             {
                 // Make sure the NurbsWall vtk data is written, not the WearableNurbsWall implementation of writeWallDetailsVTK()
                 if (wnw_ptr)
                     wnw_ptr->NurbsWall::writeWallDetailsVTK(dataNurbsWall);
                 else
                     w->writeWallDetailsVTK(dataNurbsWall);
             }
             // WearableNurbsWall: should be written and of type
             if (wnw_sw && wnw_ptr)
             {
                 w->writeWallDetailsVTK(dataWearableNurbsWall);
             }
         }
         // Without inheritance differentiating a simple call could look like:
         //else if (shouldWrite(WallHandler::DetailsVTKOptions::OTHER_TYPE_OF_WALL) && dynamic_cast<OtherTypeOfWall*>(w))
         //{
         //    w->writeWallDetailsVTK(dataOtherTypeOfWall);
         //}
     }
     // Again, check if the data should be written and if so write the file(s).
     // When a certain wall type should be written, but none of the walls the handler are of that type, the file(s) will
     // be written anyway. This is closest to what a user would expect, even though the file(s) don't hold any data.
     if (nw_sw)
         dataNurbsWall.writeVTKData(generateFileName("NurbsWall"));
     if (wnw_sw)
         dataWearableNurbsWall.writeVTKData(generateFileName("WearableNurbsWall"));
     //if (shouldWrite(WallHandler::DetailsVTKOptions::OTHER_TYPE_OF_WALL))
     //    dataOtherTypeOfWall.writeVTKData(generateFileName("OtherTypeOfWall"));
     // Other stuff not strictly wall specific
     if (shouldWrite(WallHandler::DetailsVTKOptions::BOUNDINGBOX))
     {
         VTKData dataBoundingBox;
         handler_.writeWallDetailsVTKBoundingBox(dataBoundingBox);
         dataBoundingBox.writeVTKData(generateFileName("BoundingBox"));
     }
     fileCounter++;
 }
References WallHandler::BOUNDINGBOX, BaseVTKWriter< WallHandler >::fileCounter, generateFileName(), BaseVTKWriter< WallHandler >::handler_, WallHandler::NURBSWALL, PROCESSOR_ID, shouldWrite(), w, WallHandler::WEARABLENURBSWALL, VTKData::writeVTKData(), and WallHandler::writeWallDetailsVTKBoundingBox().
Referenced by DPMBase::writeVTKFiles().
The documentation for this class was generated from the following files:
WallDetailsVTKWriter.h
WallDetailsVTKWriter.cc