MercuryDPM: Eigen::internal::SumReducer< T > Struct Template Reference
Eigen::internal::SumReducer< T > Struct Template Reference
#include <TensorFunctors.h>
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void reduce (const T t, T *accum) const
template<typename Packet >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void reducePacket (const Packet &p, Packet *accum) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T initialize () const
template<typename Packet >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet initializePacket () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T finalize (const T accum) const
template<typename Packet >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet finalizePacket (const Packet &vaccum) const
template<typename Packet >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T finalizeBoth (const T saccum, const Packet &vaccum) const
Member Function Documentation
finalize()
template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T Eigen::internal::SumReducer< T >::finalize (const T accum) const inline
 { return accum; }
finalizeBoth()
template<typename T > template<typename Packet > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T Eigen::internal::SumReducer< T >::finalizeBoth (const T saccum, const Packet & vaccum) const inline
{
     internal::scalar_sum_op<T> sum_op;
     return sum_op(saccum, predux(vaccum));
   }
References Eigen::internal::predux().
finalizePacket()
template<typename T > template<typename Packet > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::SumReducer< T >::finalizePacket (const Packet & vaccum) const inline
{
     return vaccum;
   }
initialize()
template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T Eigen::internal::SumReducer< T >::initialize () const inline
{
     internal::scalar_cast_op<int, T> conv;
     return conv(0);
   }
Referenced by Eigen::internal::SumReducer< T >::initializePacket().
initializePacket()
template<typename T > template<typename Packet > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::SumReducer< T >::initializePacket () const inline
{
     return pset1<Packet>(initialize());
   }
References Eigen::internal::SumReducer< T >::initialize().
reduce()
template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::SumReducer< T >::reduce (const T t, T * accum) const inline
{
     internal::scalar_sum_op<T> sum_op;
     *accum = sum_op(*accum, t);
   }
References plotPSD::t.
reducePacket()
template<typename T > template<typename Packet > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::SumReducer< T >::reducePacket (const Packet & p, Packet * accum) const inline
{
     (*accum) = padd<Packet>(*accum, p);
   }
References p.
The documentation for this struct was generated from the following file:
TensorFunctors.h