MercuryDPM: OutputData Namespace Reference
OutputData Namespace Reference
Functions
def ParaviewOutputPebblesAnimated (OPT, DATA)
def ParaviewOutputPebblesStatic (OPT, DATA)
def SaveClumpMDPM (OPT, DATA)
def OutputClumpData (OPT, DATA)
Function Documentation
OutputClumpData()
def OutputData.OutputClumpData (OPT, DATA)
 def OutputClumpData(OPT, DATA):
     # Output clump data for MDPM + additional output (vtu, stl)
     import os
     # MDPM output
     OPT, DATA = SaveClumpMDPM(OPT, DATA)
     # Paraview output
     if OPT['paraviewOutput']:
         if OPT['verbose']: print("Output vtu data")
         if (OPT['animate']): ParaviewOutputPebblesAnimated(OPT, DATA)
         if not (OPT['animate']): ParaviewOutputPebblesStatic(OPT, DATA)
     # Pebble stl output
     if OPT['PebbleStlOutput']:
         if OPT['verbose']: print("Output pebble stl data")
         path = './Clumps/' + OPT['clumpName']
         if not os.path.exists(path):
             os.mkdir(path)
         path += '/' + OPT['stlOutputDir'] + '/'
         if not os.path.exists(path):
             os.mkdir(path)
         filename = path + OPT['outStlFileName']
         pebbles = DATA['pebbles']
         N_theta = OPT['stlThetaRes']
         N_phi = OPT['stlPhiRes']
         SavePebblesStl(filename, pebbles, N_theta, N_phi)
     # Voxel grid stl output
     if OPT['mode'] == 2 and OPT['VoxelStlOutput']:
         if OPT['verbose']: print("Output voxel grid stl data")
         path = './Clumps/' + OPT['clumpName']
         if not os.path.exists(path):
             os.mkdir(path)
         path += '/' + OPT['voxelStlOutputDir'] + '/'
         if not os.path.exists(path):
             os.mkdir(path)
         filename = path + OPT['voxStlFileName']
         vox, bbox, span = DATA['voxelGrid']
         SaveVoxelGridStl(filename, vox, bbox, span)
     return OPT, DATA
References ParaviewOutputPebblesAnimated(), ParaviewOutputPebblesStatic(), Eigen::internal.print(), SaveClumpMDPM(), SaveToStl.SavePebblesStl(), and SaveToStl.SaveVoxelGridStl().
Referenced by MClump.main().
ParaviewOutputPebblesAnimated()
def OutputData.ParaviewOutputPebblesAnimated (OPT, DATA)
 def ParaviewOutputPebblesAnimated(OPT, DATA):
     import os
     pebbles = DATA['pebbles']
     num_timesteps = OPT['numTimesteps']
     filename = './Clumps/' + OPT['clumpName']
     if not os.path.exists(filename):
         os.mkdir(filename)
     filename += '/' + OPT['paraviewOutputDir']
     if not os.path.exists(filename):
         os.mkdir(filename)
     filename += '/' + OPT['vtuFileName']
     if not os.path.exists(filename):
         os.mkdir(filename)
     positions = np.zeros([len(pebbles), num_timesteps, 3])
     velocities = np.zeros([len(pebbles), num_timesteps, 3])
     v1t = np.zeros([num_timesteps, 3])
     v2t = np.zeros([num_timesteps, 3])
     v3t = np.zeros([num_timesteps, 3])
     radii = np.zeros([len(pebbles), num_timesteps])
     for k in range(num_timesteps):
         v1 = np.array([np.cos(k * (2. * np.pi / (num_timesteps + 0.))),  -np.sin(k * (2. * np.pi / (num_timesteps + 0.))), 0.0])
         v2 = np.array([np.sin(k * (2. * np.pi / (num_timesteps + 0.))), np.cos(k * (2. * np.pi / (num_timesteps + 0.))), 0.0])
         v3 = np.array([0.0, 0.0, 1.0])
         v1c = np.array([np.cos(-k * (2. * np.pi / (num_timesteps + 0.))), -np.sin(-k * (2. * np.pi / (num_timesteps + 0.))), 0.0])
         v2c = np.array([np.sin(-k * (2. * np.pi / (num_timesteps + 0.))), np.cos(-k * (2. * np.pi / (num_timesteps + 0.))), 0.0])
         v3c = np.array([0.0, 0.0, 1.0])
         r_pebbles = RotateToPDPebbles(pebbles, v1, v2, v3)
         v1t[k][:] = v1c
         v2t[k][:] = v2c
         v3t[k][:] = v3c
         for i in range(len(pebbles)):
             positions[i][k][:] = r_pebbles[i][:3]
             radii[i][k] = r_pebbles[i][3]
     SavePebblesToVtu(filename, positions, velocities, radii)
     SavePDToVtu(filename, v1t, v2t, v3t)
     return
References InertiaComputationsPebbles.RotateToPDPebbles(), SaveToVtu.SavePDToVtu(), and SaveToVtu.SavePebblesToVtu().
Referenced by OutputClumpData().
ParaviewOutputPebblesStatic()
def OutputData.ParaviewOutputPebblesStatic (OPT, DATA)
 def ParaviewOutputPebblesStatic(OPT, DATA):
     import os
     pebbles = DATA['pebbles']
     filename = './Clumps/' + OPT['clumpName']
     if not os.path.exists(filename):
         os.mkdir(filename)
     filename += '/' + OPT['paraviewOutputDir']
     if not os.path.exists(filename):
         os.mkdir(filename)
     filename += '/' + OPT['vtuFileName']
     if not os.path.exists(filename):
         os.mkdir(filename)
     if os.path.exists(OPT['paraviewOutputDir']):  # Remove vtu files from the previous run
         os.chdir(OPT['paraviewOutputDir'])
         os.remove('*.vtu')
     positions = np.zeros([len(pebbles), 1, 3])
     velocities = np.zeros([len(pebbles), 1, 3])
     radii = np.zeros([len(pebbles), 1])
     for i in range(len(pebbles)):
         positions[i][0][:] = pebbles[i][:3]
         radii[i][0] = pebbles[i][3]
     SavePebblesToVtu(filename, positions, velocities, radii)
     return
References SaveToVtu.SavePebblesToVtu().
Referenced by OutputClumpData().
SaveClumpMDPM()
def OutputData.SaveClumpMDPM (OPT, DATA)
 def SaveClumpMDPM(OPT, DATA):
     import os
     path = './Clumps/' + OPT['clumpName']
     if not os.path.exists(path):
         os.mkdir(path)
     pathI = path + '/' + OPT['inertiaOutputDir'] + '/'
     if not os.path.exists(pathI):
         os.mkdir(pathI)
     pathC = path + '/' + OPT['clumpOutputDir'] + '/'
     if not os.path.exists(pathC):
         os.mkdir(pathC)
     np.savetxt(pathI + OPT['inertiaFileName'], DATA['toi'], delimiter=',')
     np.savetxt(pathI + OPT['pdFileName'], DATA['pd'], delimiter=',')
     np.savetxt(pathI + OPT['massFileName'], [DATA['mass']], delimiter=',')
     np.savetxt(pathC + OPT['outClumpFileName'], DATA['pebbles'], delimiter=',')
     return OPT, DATA
Referenced by OutputClumpData().