MercuryDPM: WallHandler Class Reference
WallHandler Class Reference final
Container to store all BaseWall.
#include <WallHandler.h>
Public Types
enum class DetailsVTKOptions { BOUNDINGBOX = 0 , NURBSWALL = 1 , WEARABLENURBSWALL = 2 }
Public Member Functions
WallHandler ()
Default constructor, it creates an empty WallHandler.
WallHandler (const WallHandler &BH)
Constructor that copies a pointer to the DPMBase and all BaseWall in the given WallHandler.
WallHandler & operator= (const WallHandler &rhs)
Assignment operator that copies the pointer to the DPMBase and all BaseWall in the given WallHandler.
~WallHandler () final
Destructor, it destructs the WallHandler and all BaseWall it contains.
void addObject (BaseWall *W) final
Adds a BaseWall to the WallHandler.
BaseWall * readAndCreateObject (std::istream &is)
Create a new wall, based on the information provided in a restart file.
void readAndAddObject (std::istream &is) final
Create a new wall in the WallHandler, based on the information provided in a restart file.
std::string getName () const final
Returns the name of the handler, namely the string "WallHandler".
unsigned readTriangleWall (std::string filename, ParticleSpecies *species, Mdouble scaleFactor=1, Vec3D centerOfRotation={0, 0, 0}, Vec3D velocity={0, 0, 0}, Vec3D angularVelocity={0, 0, 0})
Reads triangulated walls from vtk or stl files, and converts them into a set of TriangleWalls.
void actionsAfterParticleGhostUpdate ()
Calls the method actionsAfterParticleGhostUpdate of every wall in the handler.
void setWriteVTK (FileType)
Sets whether walls are written into a VTK file.
void setWriteVTK (bool)
Sets whether walls are written into a VTK file.
FileType getWriteVTK () const
Returns whether walls are written in a VTK file.
void setWriteDetailsVTK (DetailsVTKOptions, FileType)
void setWriteDetailsVTK (DetailsVTKOptions, bool)
FileType getWriteDetailsVTK (DetailsVTKOptions) const
bool getWriteDetailsVTKAny () const
std::unordered_map< DetailsVTKOptions, FileType > getWriteWallDetailsVTKAll () const
void writeWallDetailsVTKBoundingBox (VTKData &data) const
void setWriteWallSurfaceAreaVTK (bool writeWallSurfaceAreaVTK)
Enables/disables the calculation and writing of the surface area of the cells.
bool getWriteWallSurfaceAreaVTK () const
Public Member Functions inherited from BaseHandler< BaseWall >
BaseHandler ()
Default BaseHandler constructor, it creates an empty BaseHandler and assigns DPMBase_ to a null pointer.
BaseHandler (const BaseHandler< BaseWall > &BH)
Constructor that copies the objects of the given handler into itself and sets other variables to 0/nullptr.
virtual ~BaseHandler ()
Destructor, it destructs the BaseHandler and all Object it contains.
void copyContentsFromOtherHandler (const BaseHandler< BaseWall > &BH)
Function that copies the contents (vector of pointers, maxObject_, nextId_, DPMBase_) from one handler (container) to the other.
std::enable_if<!std::is_pointer< U >::value, U * >::type copyAndAddObject (const U &object)
Creates a copy of a Object and adds it to the BaseHandler.
std::enable_if< std::is_pointer< U >::value, U >::type copyAndAddObject (const U object)
Creates a copy of a Object and adds it to the BaseHandler.
std::enable_if<!std::is_pointer< U >::value, U * >::type copyAndAddGhostObject (const U &object)
Creates a copy of a Object and adds it to the BaseHandler. This is one locally for inserting mpi particles, they avoid the global check if the particle can actually be inserted, because the mpi domain already knows that is the case.
std::enable_if< std::is_pointer< U >::value, U >::type copyAndAddGhostObject (const U object)
Creates a copy of a Object and adds it to the BaseHandler. This is one locally for inserting mpi particles, they avoid the global check if the particle can actually be inserted, because the mpi domain already knows that is the case.
virtual void addExistingObject (BaseWall *O)
Adds an existing object to the BaseHandler without changing the id of the object.
virtual void addObject (BaseWall *object)
Adds a new Object to the BaseHandler.
virtual void addGhostObject (BaseWall *O)
Adds a new Object to the BaseHandler. called by the to avoid increasing the id.
void removeIf (const std::function< bool(BaseWall *)> cond)
virtual void removeObject (unsigned const int index)
Removes an Object from the BaseHandler.
virtual void removeObjects (std::vector< unsigned int > indices)
void removeLastObject ()
Removes the last Object from the BaseHandler.
virtual void clear ()
Empties the whole BaseHandler by removing all Objects and setting all other variables to 0.
void read (std::istream &is)
Reads all objects from restart data.
BaseWall * getObjectById (const unsigned int id)
Gets a pointer to the Object at the specified index in the BaseHandler.
std::vector< BaseWall * > getObjectsById (const unsigned int id)
Gets a vector of pointers to the objects with the specific id.
BaseWall * getObject (const unsigned int id)
Gets a pointer to the Object at the specified index in the BaseHandler.
const BaseWall * getObject (const unsigned int id) const
Gets a constant pointer to the Object at the specified index in the BaseHandler.
BaseWall * getLastObject ()
Gets a pointer to the last Object in this BaseHandler.
const BaseWall * getLastObject () const
Gets a constant pointer to the last Object in this BaseHandler.
virtual unsigned int getNumberOfObjects () const
Gets the number of real Object in this BaseHandler. (i.e. no mpi or periodic particles)
unsigned int getSize () const
Gets the size of the particleHandler (including mpi and periodic particles)
unsigned int getStorageCapacity () const
Gets the storage capacity of this BaseHandler.
void setStorageCapacity (const unsigned int N)
Sets the storage capacity of this BaseHandler.
void resize (const unsigned int N, const BaseWall &obj)
Resizes the container to contain N elements.
const std::vector< BaseWall * >::const_iterator begin () const
Gets the begin of the const_iterator over all Object in this BaseHandler.
const std::vector< BaseWall * >::iterator begin ()
Gets the begin of the iterator over all BaseBoundary in this BaseHandler.
const std::vector< BaseWall * >::const_iterator end () const
Gets the end of the const_iterator over all BaseBoundary in this BaseHandler.
const std::vector< BaseWall * >::iterator end ()
Gets the end of the iterator over all BaseBoundary in this BaseHandler.
void setDPMBase (DPMBase *DPMBase)
Sets the problem that is solved using this handler.
void setId (BaseWall *object, unsigned int id)
void increaseId ()
unsigned int getNextId ()
void setNextId (unsigned int id)
DPMBase * getDPMBase ()
Gets the problem that is solved using this handler.
DPMBase * getDPMBase () const
Gets the problem that is solved using this handler and does not change the class.
virtual void writeVTK () const
now empty function for writing VTK files.
unsigned getNextGroupId ()
Should be called each time you assign a groupId. Returns the value of nextGroupId_ and increases nextGroupId_ by one.
Static Public Member Functions
static BaseWall * createObject (const std::string &type)
Create a new wall, with the type given as a string (required for restarting).
Private Member Functions
BaseWall * readAndCreateOldObject (std::istream &is)
Create a new wall, based on the information from old-style restart data.
Private Attributes
FileType writeVTK_
std::unordered_map< DetailsVTKOptions, FileType > writeDetailsVTK_
unordered_map storing the file types corresponding to each of the enum DetailsVTKOptions
Additional Inherited Members
Protected Attributes inherited from BaseHandler< BaseWall >
std::vector< BaseWall * > objects_
The actual list of Object pointers.
Detailed Description
Container to store all BaseWall.
The WallHandler is a container to store all BaseWall. It is implemented by a vector of pointers to BaseWall.
Member Enumeration Documentation
DetailsVTKOptions
enum WallHandler::DetailsVTKOptions strong
Enumerator
BOUNDINGBOX
Writes a bounding box around the domain.
NURBSWALL
Writes the NURBS control points.
WEARABLENURBSWALL
Writes the debris.
     {
         // Used as keys for an unordered_map.
         // The actual enum values are written to the restart file and their meaning should therefore never change.
         // So when adding new options, be sure to hardcode a unique enum value!
         // The options can be in any order and their values are completely free to choose, as long as they're unique.
         BOUNDINGBOX = 0,
         NURBSWALL = 1,
         WEARABLENURBSWALL = 2
     };
Constructor & Destructor Documentation
WallHandler() [1/2]
WallHandler::WallHandler ()
Default constructor, it creates an empty WallHandler.
Constructor of the WallHandler class. It creates an empty WallHandler.
Todo:
why is this being done?
 {
     clear();
     writeVTK_ = FileType::NO_FILE;
 #ifdef DEBUG_CONSTRUCTOR
     std::cerr << "WallHandler::WallHandler() finished" << std::endl;
 #endif
 }
References BaseHandler< BaseWall >::clear(), NO_FILE, and writeVTK_.
WallHandler() [2/2]
WallHandler::WallHandler (const WallHandler & WH)
Constructor that copies a pointer to the DPMBase and all BaseWall in the given WallHandler.
Parameters
[in] WH The WallHandler that has to be copied.
This is not a copy constructor! It only copies the pointer to the DPMBase and the BaseWall in objects_, it sets the other data members to 0 or nullptr.
Todo:
why is this being done?
 {
     clear();
     setDPMBase(WH.getDPMBase());
     copyContentsFromOtherHandler(WH);
     writeVTK_ = WH.writeVTK_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cerr << "WallHandler::WallHandler(const WallHandler&) finished" << std::endl;
 #endif
 }
References BaseHandler< BaseWall >::clear(), BaseHandler< BaseWall >::copyContentsFromOtherHandler(), BaseHandler< T >::getDPMBase(), BaseHandler< BaseWall >::setDPMBase(), and writeVTK_.
~WallHandler()
WallHandler::~WallHandler () final
Destructor, it destructs the WallHandler and all BaseWall it contains.
 {
 #ifdef DEBUG_CONSTRUCTOR
     std::cerr << "WallHandler::~WallHandler() finished" << std::endl;
 #endif
 }
Member Function Documentation
actionsAfterParticleGhostUpdate()
void WallHandler::actionsAfterParticleGhostUpdate ()
Calls the method actionsAfterParticleGhostUpdate of every wall in the handler.
This function is called by DPMBase::computeOneTimeStep directly after the ghost particle update. It may be used to adjust wall properties based on the changed wall positions (for an example, look e.g. at MeshTriangle).
 {
     // #pragma omp parallel for //schedule(dynamic)
     for (auto w: *this)
     {
         w->actionsAfterParticleGhostUpdate();
     }
 }
References w.
Referenced by DPMBase::computeOneTimeStep().
addObject()
void WallHandler::addObject (BaseWall * W) final
Adds a BaseWall to the WallHandler.
Parameters
[in] W A pointer to the BaseWall (or derived class) that has to be added.
First the new BaseWall is added to the vector of BaseWall, then it is told that this is its handler.
 {
     if (W->getSpecies() == nullptr)
     {
         logger(WARN, "WARNING: The wall with ID % that is added in WallHandler::addObject "
                      "does not have a species yet. Please make sure that you have "
                      "set the species somewhere in the driver code.", W->getId());
     }
     //Puts the wall in the Wall list
     BaseHandler<BaseWall>::addObject(W);
     //set the particleHandler pointer
     W->setHandler(this);
 }
References BaseHandler< T >::addObject(), logger, oomph::QuadTreeNames::W, and WARN.
Referenced by readAndAddObject(), and Chutebelt::setupInitialConditions().
createObject()
BaseWall * WallHandler::createObject (const std::string & type) static
Create a new wall, with the type given as a string (required for restarting).
Todo:
Review this line. Problem came up in merging.
 {
     if (type == "CylindricalWall")
     {
         return new CylindricalWall;
     }
     else if (type == "AxisymmetricIntersectionOfWalls")
     {
         return new AxisymmetricIntersectionOfWalls;
     }
     else if (type == "ScrewsymmetricIntersectionOfWalls")
     {
         return new ScrewsymmetricIntersectionOfWalls;
     }
     else if (type == "IntersectionOfWalls")
     {
         return new IntersectionOfWalls;
     }
     else if (type == "BasicIntersectionOfWalls")
     {
         return new BasicIntersectionOfWalls;
     }
     else if (type == "BasicUnionOfWalls")
     {
         return new BasicUnionOfWalls;
     }
     else if (type == "InfiniteWall")
     {
         return new InfiniteWall;
     }
     else if (type == "InfiniteWallWithHole")
     {
         return new InfiniteWallWithHole;
     }
     else if (type == "Screw")
     {
         return new Screw;
     }
     else if (type == "Coil")
     {
         return new Coil;
     }
     else if (type == "TriangleWall")
     {
         return new TriangleWall;
     }
     else if (type == "MeshTriangle")
     {
         return new MeshTriangle;
     }
     else if (type == "VChute")
     {
         return new VChute;
     }
     else if (type == "NurbsWall")
     {
         return new NurbsWall();
     }
     else if (type == "WearableNurbsWall")
     {
         return new WearableNurbsWall();
     }
     else if (type == "TriangleMeshWall")
     {
         return new TriangleMeshWall;
     }
     else if (type == "WearableTriangleMeshWall")
     {
         return new WearableTriangleMeshWall;
     }
     //for backward compatibility (before svnversion ~2360)
     else if (type == "numFiniteWalls")
     {
         return new BasicIntersectionOfWalls;
     }
    // else if (!getDPMBase()->readUserDefinedWall(type,is))
     else
     {
         logger(WARN, "Wall type: % not understood in restart file", type);
         return nullptr;
     }
 }
References logger, compute_granudrum_aor::type, and WARN.
Referenced by BaseWall::read(), BasicIntersectionOfWalls::read(), BasicUnionOfWalls::read(), and readAndCreateObject().
getName()
std::string WallHandler::getName () const final virtual
Returns the name of the handler, namely the string "WallHandler".
Returns
The string "WallHandler".
Implements BaseHandler< BaseWall >.
 {
     return "WallHandler";
 }
getWriteDetailsVTK()
FileType WallHandler::getWriteDetailsVTK (DetailsVTKOptions option) const
 {
     // This function has to be marked constant, so accessing by key is not an option, as it will automatically add keys
     // not present in the map yet.
     // Try to find the option to see if it's already added to the map or not
     auto it = writeDetailsVTK_.find(option);
     // When the iterator does not equal the end, the key has been found
     if (it != writeDetailsVTK_.end())
         return it->second;
     else
         return FileType::NO_FILE; // Else return a default file type
 }
References NO_FILE, and writeDetailsVTK_.
Referenced by WallDetailsVTKWriter::shouldWrite(), and DPMBase::writePythonFileForVTKVisualisation().
getWriteDetailsVTKAny()
bool WallHandler::getWriteDetailsVTKAny () const
 {
     // Simple lambda expression to check if any of the file types are not of type NO_FILE
     return std::any_of(writeDetailsVTK_.begin(), writeDetailsVTK_.end(),
                        [](const auto& p) { return p.second != FileType::NO_FILE; });
 }
References p, and writeDetailsVTK_.
Referenced by DPMBase::initialiseVTK(), DPMBase::write(), and DPMBase::writeVTKFiles().
getWriteVTK()
FileType WallHandler::getWriteVTK () const
Returns whether walls are written in a VTK file.
 {
     return writeVTK_;
 }
References writeVTK_.
Referenced by DPMBase::getWallsWriteVTK(), DPMBase::initialiseVTK(), DPMBase::write(), DPMBase::writePythonFileForVTKVisualisation(), and DPMBase::writeVTKFiles().
getWriteWallDetailsVTKAll()
std::unordered_map< WallHandler::DetailsVTKOptions, FileType > WallHandler::getWriteWallDetailsVTKAll () const
 {
     return writeDetailsVTK_;
 }
References writeDetailsVTK_.
Referenced by DPMBase::write().
getWriteWallSurfaceAreaVTK()
bool WallHandler::getWriteWallSurfaceAreaVTK () const
 {
     return getDPMBase()->getWallVTKWriter().getWriteWallSurfaceAreaVTK();
 }
References BaseHandler< BaseWall >::getDPMBase(), DPMBase::getWallVTKWriter(), and WallVTKWriter::getWriteWallSurfaceAreaVTK().
operator=()
WallHandler & WallHandler::operator= (const WallHandler & rhs)
Assignment operator that copies the pointer to the DPMBase and all BaseWall in the given WallHandler.
Parameters
[in] rhs The WallHandler on the right hand side of the assignment.
This is not a copy assignment operator! It only copies the pointer to the DPMBase and the BaseWall in objects_, it sets the other data members to 0 or nullptr.
 {
     if (this != &rhs)
     {
         clear();
         setDPMBase(rhs.getDPMBase());
         copyContentsFromOtherHandler(rhs);
         writeVTK_ = rhs.writeVTK_;
     }
     return *this;
 #ifdef DEBUG_CONSTRUCTOR
     std::cerr << "WallHandler::operator =(const WallHandler&) finished" << std::endl;
 #endif
 }
References BaseHandler< BaseWall >::clear(), BaseHandler< BaseWall >::copyContentsFromOtherHandler(), BaseHandler< T >::getDPMBase(), BaseHandler< BaseWall >::setDPMBase(), and writeVTK_.
readAndAddObject()
void WallHandler::readAndAddObject (std::istream & is) final virtual
Create a new wall in the WallHandler, based on the information provided in a restart file.
As we add the object into the handler, we need to make sure that the object keeps its existing ID. This is not always the same as the index, e.g. if walls have been removed during the simulation.
Parameters
[in] is The input stream from which the information is read.
Implements BaseHandler< BaseWall >.
 {
     BaseWall* o = readAndCreateObject(is);
     unsigned int id = o->getId();
     addObject(o);
     getLastObject()->setId(id);
 }
References addObject(), BaseObject::getId(), BaseHandler< BaseWall >::getLastObject(), readAndCreateObject(), and BaseObject::setId().
Referenced by DPMBase::read().
readAndCreateObject()
BaseWall * WallHandler::readAndCreateObject (std::istream & is)
Create a new wall, based on the information provided in a restart file.
 {
     std::string type;
     is >> type;
     logger(DEBUG, "WallHandler::readAndAddObject(is): reading type %.", type);
     //for backward compatibility (before svnversion ~2360)
     if (type == "numFiniteWalls")
     {
         return readAndCreateOldObject(is);
     }
     else
     {
         BaseWall* wall = createObject(type);
         //check if wall is user-defined
         if (wall == nullptr)
         {
             wall = getDPMBase()->readUserDefinedWall(type);
         }
         //throw warning if wall could not be found
         if (wall == nullptr)
         {
             std::string line;
             getline(is, line);
             logger(WARN, "This wall could not be read; dummy wall is inserted instead:\n%%", type, line);
             BaseWall* wall = new InfiniteWall;
             wall->setHandler(this);
             wall->setSpecies(getDPMBase()->speciesHandler.getObject(0));
             return wall;
         }
         wall->setHandler(this);
         is >> *wall;
         wall->setSpecies(getDPMBase()->speciesHandler.getObject(wall->getIndSpecies()));
         return wall;
     }
 }
References createObject(), DEBUG, BaseHandler< BaseWall >::getDPMBase(), BaseInteractable::getIndSpecies(), calibrate::line, logger, readAndCreateOldObject(), DPMBase::readUserDefinedWall(), BaseWall::setHandler(), BaseWall::setSpecies(), oomph::Global_string_for_annotation::string(), compute_granudrum_aor::type, and WARN.
Referenced by readAndAddObject().
readAndCreateOldObject()
BaseWall * WallHandler::readAndCreateOldObject (std::istream & is) private
Create a new wall, based on the information from old-style restart data.
First determine whether or not the wall is an infinite wall. If it is an infinite wall, read the normal and position and add the wall to the handler. If it is a finite wall, read the normal and position of each part and construct an IntersectionOfWalls from it, which can then be added to the handler.
Parameters
[in,out] is The input stream from which the information is read.
Todo:
This is deprecated since r ~2360.
 {
     //read in next line
     std::stringstream line;
     helpers::getLineFromStringStream(is, line);
     logger(VERBOSE, line.str());
     std::string dummy;
     unsigned int numWalls;
     Mdouble position;
     Vec3D normal;
     line >> numWalls;
     if (numWalls == 0)
     {
         InfiniteWall* wall = new InfiniteWall();
         wall->setSpecies(getDPMBase()->speciesHandler.getObject(0));
         line >> dummy >> normal >> dummy >> position;
         wall->set(normal, position * normal);
         return wall;
     }
     else
     {
         IntersectionOfWalls* wall = new IntersectionOfWalls();
         wall->setSpecies(getDPMBase()->speciesHandler.getObject(0));
         for (unsigned int i = 0; i < numWalls; ++i)
         {
             line >> dummy >> normal >> dummy >> position;
             wall->addObject(normal, position * normal);
         }
         return wall;
     }
 }
References IntersectionOfWalls::addObject(), BaseHandler< BaseWall >::getDPMBase(), helpers::getLineFromStringStream(), i, calibrate::line, logger, WallFunction::normal(), InfiniteWall::set(), BaseWall::setSpecies(), IntersectionOfWalls::setSpecies(), oomph::Global_string_for_annotation::string(), and VERBOSE.
Referenced by readAndCreateObject().
readTriangleWall()
unsigned WallHandler::readTriangleWall (std::string filename, ParticleSpecies * species, Mdouble scaleFactor = 1, Vec3D centerOfRotation = {0,0,0}, Vec3D velocity = {0,0,0}, Vec3D angularVelocity = {0,0,0})
Reads triangulated walls from vtk or stl files, and converts them into a set of TriangleWalls.
The stl files have to be binary STL files. If you have ascii files, you need to convert them (use e.g. https://www.meshconvert.com/)
The vtk files need to be of type POLYDATA and contain triangle strips (see see www.cacr.caltech.edu/~slombey)
Parameters
[in] filename name of vtk input file, e.g. TriangulatedWallSelfTest.vtk
[in] species pointer to a species in the species handler that will be assigned to the walls
[in] scaleFactor allows the vertex positions to be scaled (necessary if the vtk file is written in different units than the Mercury implementation, e.g. if the stl file is given in mm, but the Mercury implementation uses meters)
 {
     const unsigned groupId = getNextGroupId();
     std::string fileType = filename.substr(filename.find_last_of('.') + 1);
     //define a default triangle wall
     TriangleWall triangleWall;
     triangleWall.setSpecies(species);
     triangleWall.setVelocity(velocity);
     triangleWall.setAngularVelocity(angularVelocity);
     triangleWall.setGroupId(groupId);
     if (helpers::lower(fileType) == "vtk")
     {
         //try open the input file
         std::fstream file;
         file.open(filename.c_str(), std::ios::in);
         logger.assert_always(file.is_open(), "File opening failed: %", filename);
         //skip the header lines
         std::string dummy;
         getline(file, dummy);
         getline(file, dummy);
         getline(file, dummy);
         getline(file, dummy);
         //read vertices, apply scaling
         unsigned num;
         file >> dummy >> num >> dummy;
         std::vector<Vec3D> vertex;
         vertex.reserve(num);
         Vec3D v;
         for (unsigned i = 0; i < num; i++)
         {
             file >> v.X >> v.Y >> v.Z;
             v *= scaleFactor;
             vertex.push_back(v);
         }
         //read faces
         unsigned n = getSize();
         file >> dummy >> num >> dummy;
         unsigned id0, id1, id2;
         for (unsigned i = 0; i < num; i++)
         {
             file >> dummy >> id0 >> id1 >> id2;
             triangleWall.setVertices(vertex[id0], vertex[id1], vertex[id2], centerOfRotation);
             copyAndAddObject(triangleWall);
         }
         //close file
         file.close();
         logger(INFO, "Read in % walls from %", getSize() - n,filename);
     }
     else if (helpers::lower(fileType) == "stl")
     {
         BinaryReader file(filename);
         STLTriangle triangle;
         std::string header = file.readString(80);
         unsigned numTriangles = file.readUnsignedInt(4);
         for (unsigned i = 0; i < numTriangles; i++)
         {
             triangle.normal.x() = file.readFloat(4);
             triangle.normal.y() = file.readFloat(4);
             triangle.normal.z() = file.readFloat(4);
             triangle.vertex1.x() = file.readFloat(4);
             triangle.vertex1.y() = file.readFloat(4);
             triangle.vertex1.z() = file.readFloat(4);
             triangle.vertex2.x() = file.readFloat(4);
             triangle.vertex2.y() = file.readFloat(4);
             triangle.vertex2.z() = file.readFloat(4);
             triangle.vertex3.x() = file.readFloat(4);
             triangle.vertex3.y() = file.readFloat(4);
             triangle.vertex3.z() = file.readFloat(4);
             triangle.vertex1 *= scaleFactor;
             triangle.vertex2 *= scaleFactor;
             triangle.vertex3 *= scaleFactor;
             //add to triangle wall
             triangleWall.setVertices(triangle.vertex1, triangle.vertex2, triangle.vertex3, centerOfRotation);
             copyAndAddObject(triangleWall);
             //Now ignore (read) the two dummy characters
             file.ignoreChar(2);
         }
         logger(INFO, "Read in % walls from %", numTriangles,filename);
     }
     else
     {
         logger(ERROR, "File type of % must be vtk or stl");
     }
     return groupId;
 }
References BaseHandler< BaseWall >::copyAndAddObject(), ERROR, MergeRestartFiles::filename, BaseHandler< BaseWall >::getNextGroupId(), BaseHandler< BaseWall >::getSize(), i, BinaryReader::ignoreChar(), INFO, logger, helpers::lower(), n, STLTriangle::normal, BinaryReader::readFloat(), BinaryReader::readString(), BinaryReader::readUnsignedInt(), BaseInteractable::setAngularVelocity(), BaseObject::setGroupId(), BaseWall::setSpecies(), BaseInteractable::setVelocity(), TriangleWall::setVertices(), oomph::Global_string_for_annotation::string(), v, Jeffery_Solution::velocity(), STLTriangle::vertex1, STLTriangle::vertex2, STLTriangle::vertex3, Vec3D::x(), Vec3D::y(), and Vec3D::z().
Referenced by MarbleRun::loadBigSeesaw(), MarbleRun::loadSmallSeesaw(), MarbleRun::loadSTLFile(), main(), ChangingTOIParticle::setupInitialConditions(), NozzleDemo::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), and AreaVTK::setupInitialConditions().
setWriteDetailsVTK() [1/2]
void WallHandler::setWriteDetailsVTK (DetailsVTKOptions option, bool writeVTK)
 {
     FileType fileType = writeVTK ? FileType::MULTIPLE_FILES : FileType::NO_FILE;
     setWriteDetailsVTK(option, fileType);
 }
References MULTIPLE_FILES, NO_FILE, setWriteDetailsVTK(), and BaseHandler< BaseWall >::writeVTK().
setWriteDetailsVTK() [2/2]
void WallHandler::setWriteDetailsVTK (DetailsVTKOptions option, FileType fileType)
 {
     // Automatically adds option when it doesn't exist in the map yet
     writeDetailsVTK_[option] = fileType;
 }
References writeDetailsVTK_.
Referenced by DPMBase::read(), and setWriteDetailsVTK().
setWriteVTK() [1/2]
void WallHandler::setWriteVTK (bool writeVTK)
Sets whether walls are written into a VTK file.
 {
     writeVTK_ = writeVTK ? FileType::MULTIPLE_FILES : FileType::NO_FILE;
 }
References MULTIPLE_FILES, NO_FILE, BaseHandler< BaseWall >::writeVTK(), and writeVTK_.
setWriteVTK() [2/2]
void WallHandler::setWriteVTK (FileType fileType)
Sets whether walls are written into a VTK file.
 {
     writeVTK_ = fileType;
 }
References writeVTK_.
Referenced by AxisymmetricWallSelfTest::AxisymmetricWallSelfTest(), HorizontalMixer::HorizontalMixer(), LaserOnLayer::LaserOnLayer(), main(), MaserRepeatedOutInMPI2Test::MaserRepeatedOutInMPI2Test(), protectiveWall::protectiveWall(), DPMBase::read(), RotatingDrumBidisperse::RotatingDrumBidisperse(), Calibration::setOutput(), ChangingTOIParticle::setupInitialConditions(), NautaMixer::setupInitialConditions(), NozzleDemo::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), VerticalMixer::setupInitialConditions(), MarbleRun::setupInitialConditions(), InitialBed::setupInitialConditions(), MeltableForceLaw2SelfTest::setupInitialConditions(), MeltableForceLawSelfTest::setupInitialConditions(), ThermalConductionSelfTest::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), Drum::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), TwoParticleBagheriCollision::setupInitialConditions(), TwoParticleClassicalWilletCollision::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), MovingWalls::setupInitialConditions(), AreaVTK::setupInitialConditions(), MercuryProblem::setupMercuryProblem(), DPMBase::setWallsWriteVTK(), T_protectiveWall::T_protectiveWall(), TangentialSpringEnergyConservationUnitTest::TangentialSpringEnergyConservationUnitTest(), and Tutorial11::Tutorial11().
setWriteWallSurfaceAreaVTK()
void WallHandler::setWriteWallSurfaceAreaVTK (bool writeWallSurfaceAreaVTK)
Enables/disables the calculation and writing of the surface area of the cells.
 {
     getDPMBase()->getWallVTKWriter().setWriteWallSurfaceAreaVTK(writeWallSurfaceAreaVTK);
 }
References BaseHandler< BaseWall >::getDPMBase(), DPMBase::getWallVTKWriter(), and WallVTKWriter::setWriteWallSurfaceAreaVTK().
Referenced by AreaVTK::setupInitialConditions().
writeWallDetailsVTKBoundingBox()
void WallHandler::writeWallDetailsVTKBoundingBox (VTKData & data) const
 {
     Vec3D P[2] = { getDPMBase()->getMax(), getDPMBase()->getMin() };
     for (const Vec3D& i : P)
     {
         for (const Vec3D& j : P)
         {
             for (const Vec3D& k : P)
             {
                 data.addToPoints(Vec3D(i.X, j.Y, k.Z));
             }
         }
     }
     data.addToConnectivity({ 0, 1, 3, 2, 0, 4, 5, 1, 5, 7, 3, 7, 6, 2, 6, 4 });
     data.addToTypes(4);
 }
References data, BaseHandler< BaseWall >::getDPMBase(), DPMBase::getMax(), DPMBase::getMin(), i, j, k, and Global_Physical_Variables::P.
Referenced by WallDetailsVTKWriter::writeVTK().
Member Data Documentation
writeDetailsVTK_
std::unordered_map<DetailsVTKOptions, FileType> WallHandler::writeDetailsVTK_ private
unordered_map storing the file types corresponding to each of the enum DetailsVTKOptions
The filetypes are only actually added to the map when setting or getting it. The getter automatically adds the default filetype NO_FILE when the requested options had not yet been added.
Referenced by getWriteDetailsVTK(), getWriteDetailsVTKAny(), getWriteWallDetailsVTKAll(), and setWriteDetailsVTK().
writeVTK_
FileType WallHandler::writeVTK_ private
Referenced by getWriteVTK(), operator=(), setWriteVTK(), and WallHandler().
The documentation for this class was generated from the following files:
WallHandler.h
WallHandler.cc