MercuryDPM: unstructured_acoustic_fsi.cc File Reference
unstructured_acoustic_fsi.cc File Reference
#include "generic.h"
#include "helmholtz.h"
#include "time_harmonic_linear_elasticity.h"
#include "multi_physics.h"
#include "meshes/annular_mesh.h"
#include "meshes/triangle_mesh.h"
Classes
class MyStraightLine
Straight 1D line in 2D space.
class CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >
Coated disk FSI.
Namespaces
Global_Parameters
Namespace for global parameters.
Functions
Vector< double > Global_Parameters::Omega_sq (2, 0.0)
Square of non-dim frequency for the two regions – dependent variable!
Vector< double > Global_Parameters::Density_ratio (2, 0.1)
Density ratio for the two regions: solid to fluid.
void Global_Parameters::update_parameter_values ()
Function to update dependent parameter values.
void Global_Parameters::pressure_load (const Vector< double > &x, const Vector< double > &n, Vector< std::complex< double > > &traction)
Pressure load (real and imag part)
int main (int argc, char **argv)
Driver for acoustic fsi problem.
Variables
unsigned Global_Parameters::ABC_order =3
Order of absorbing/appproximate boundary condition.
Vector< TimeHarmonicIsotropicElasticityTensor * > Global_Parameters::E_pt
The elasticity tensors for the two regions.
double Global_Parameters::P = 0.1
Uniform pressure.
Function Documentation
main()
int main (int argc , char ** argv)
Driver for acoustic fsi problem.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Output directory
  CommandLineArgs::specify_command_line_flag("--dir",
                                             &Global_Parameters::Directory);
  // Peakiness parameter for loading
  CommandLineArgs::specify_command_line_flag("--alpha",
                                             &Global_Parameters::Alpha);
  // Multiplier for number of elements in solid mesh
  CommandLineArgs::specify_command_line_flag("--el_multiplier",
                             &Global_Parameters::El_multiplier);
  // Outer radius of Helmholtz domain
  CommandLineArgs::specify_command_line_flag("--outer_radius",
                             &Global_Parameters::Outer_radius);
  // Validaton run?
  CommandLineArgs::specify_command_line_flag("--validation");
  // Max. number of adaptations
  unsigned max_adapt=3;
  CommandLineArgs::specify_command_line_flag("--max_adapt",&max_adapt);
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  //Set up the problem
  CoatedDiskProblem<ProjectableTimeHarmonicLinearElasticityElement
                    <TTimeHarmonicLinearElasticityElement<2,3> >,
                    RefineableQHelmholtzElement<2,3> > problem;
  // Set values for parameter values
  Global_Parameters::Q=5.0;
  Global_Parameters::Density_ratio[0]=0.1;
  Global_Parameters::Density_ratio[1]=0.1;
  Global_Parameters::update_parameter_values();
  //Parameter study
  unsigned nstep=3;
  if (CommandLineArgs::command_line_flag_has_been_set("--validation"))
   {
    nstep=1;
    max_adapt=2;
   }
  for(unsigned i=0;i<nstep;i++)
   {
    // Solve the problem with Newton's method, allowing
    // up to max_adapt mesh adaptations after every solve.
    problem.newton_solve(max_adapt);
    // Doc solution
    problem.doc_solution();
    // Make rib a lot heavier but keep its stiffness
    if (i==0)
     {
      Global_Parameters::E_pt[1]->update_constitutive_parameters(
       Global_Parameters::Nu,1.0);
      Global_Parameters::Density_ratio[1]=10.0;
      Global_Parameters::update_parameter_values();
     }
    // Make rib very soft and inertia-less
    if (i==1)
     {
      Global_Parameters::E_pt[1]->update_constitutive_parameters(
       Global_Parameters::Nu,1.0e-16);
      Global_Parameters::Density_ratio[1]=0.0;
      Global_Parameters::update_parameter_values();
     }
   }
 } //end of main
References Global_Parameters::Alpha, oomph::CommandLineArgs::command_line_flag_has_been_set(), Global_Parameters::Density_ratio, Global_Parameters::Directory, oomph::CommandLineArgs::doc_specified_flags(), Global_Parameters::E_pt, Global_Parameters::El_multiplier, i, Global_Parameters::Nu, Global_Parameters::Outer_radius, oomph::CommandLineArgs::parse_and_assign(), problem, Global_Parameters::Q, Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), and Global_Parameters::update_parameter_values().