MercuryDPM: Eigen::Barrier Class Reference
Eigen::Barrier Class Reference
#include <Barrier.h>
Public Member Functions
Barrier (unsigned int count)
~Barrier ()
void Notify ()
void Wait ()
Private Attributes
EIGEN_MUTEX mu_
EIGEN_CONDVAR cv_
std::atomic< unsigned int > state_
bool notified_
Constructor & Destructor Documentation
Barrier()
Eigen::Barrier::Barrier (unsigned int count) inline
                               : state_(count << 1), notified_(false) {
     eigen_plain_assert(((count << 1) >> 1) == count);
   }
References eigen_plain_assert.
~Barrier()
Eigen::Barrier::~Barrier () inline
 { eigen_plain_assert((state_ >> 1) == 0); }
References eigen_plain_assert, and state_.
Member Function Documentation
Notify()
void Eigen::Barrier::Notify () inline
                 {
     unsigned int v = state_.fetch_sub(2, std::memory_order_acq_rel) - 2;
     if (v != 1) {
       // Clear the lowest bit (waiter flag) and check that the original state
       // value was not zero. If it was zero, it means that notify was called
       // more times than the original count.
       eigen_plain_assert(((v + 2) & ~1) != 0);
       return;  // either count has not dropped to 0, or waiter is not waiting
     }
     EIGEN_MUTEX_LOCK l(mu_);
     eigen_plain_assert(!notified_);
     notified_ = true;
     cv_.notify_all();
   }
References cv_, eigen_plain_assert, mu_, notified_, state_, and v.
Referenced by Eigen::ForkJoinScheduler::ParallelFor(), Eigen::CoreThreadPoolDevice::parallelForImpl(), test_async_execute_binary_expr(), test_async_execute_unary_expr(), test_async_multithread_contraction_agrees_with_singlethread(), test_async_parallel_for(), test_large_number_of_tasks_no_spill(), test_large_number_of_tasks_with_spill(), and test_simple_thread_local().
Wait()
void Eigen::Barrier::Wait () inline
               {
     unsigned int v = state_.fetch_or(1, std::memory_order_acq_rel);
     if ((v >> 1) == 0) return;
     EIGEN_MUTEX_LOCK l(mu_);
     while (!notified_) {
       cv_.wait(l);
     }
   }
References cv_, mu_, notified_, state_, and v.
Referenced by Eigen::CoreThreadPoolDevice::parallelFor(), Eigen::ForkJoinScheduler::ParallelFor(), test_async_execute_binary_expr(), test_async_execute_unary_expr(), test_async_multithread_contraction_agrees_with_singlethread(), test_async_parallel_for(), test_large_number_of_tasks_no_spill(), test_large_number_of_tasks_with_spill(), and test_simple_thread_local().
Member Data Documentation
cv_
EIGEN_CONDVAR Eigen::Barrier::cv_ private
Referenced by Notify(), and Wait().
mu_
EIGEN_MUTEX Eigen::Barrier::mu_ private
Referenced by Notify(), and Wait().
notified_
bool Eigen::Barrier::notified_ private
Referenced by Notify(), and Wait().
state_
std::atomic<unsigned int> Eigen::Barrier::state_ private
Referenced by Notify(), Wait(), and ~Barrier().
The documentation for this class was generated from the following file:
Barrier.h