MercuryDPM: Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options > Class Template Reference
Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options > Class Template Reference
#include <DenseStorage.h>
Public Member Functions
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE DenseStorage_impl ()=default
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE DenseStorage_impl (const DenseStorage_impl &other)
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE DenseStorage_impl (Index size, Index rows, Index cols)
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE DenseStorage_impl (DenseStorage_impl &&other) noexcept
EIGEN_DEVICE_FUNC ~DenseStorage_impl ()
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE DenseStorage_impl & operator= (const DenseStorage_impl &other)
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE DenseStorage_impl & operator= (DenseStorage_impl &&other) noexcept
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE void swap (DenseStorage_impl &other) noexcept
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE void conservativeResize (Index size, Index rows, Index cols)
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE void resize (Index size, Index rows, Index cols)
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Index rows () const
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Index cols () const
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Index size () const
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE T * data ()
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE const T * data () const
Static Public Attributes
static constexpr int Size = Dynamic
Private Attributes
T * m_data = nullptr
Index m_rows = 0
Index m_cols = 0
Static Private Attributes
static constexpr bool Align = (Options & DontAlign) == 0
Constructor & Destructor Documentation
DenseStorage_impl() [1/4]
template<typename T , int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::DenseStorage_impl () constexpr default
DenseStorage_impl() [2/4]
template<typename T , int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::DenseStorage_impl (const DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options > & other) inline constexpr
       : m_data(conditional_aligned_new_auto<T, Align>(other.size())), m_rows(other.m_rows), m_cols(other.m_cols) {
     EIGEN_INTERNAL_DENSE_STORAGE_CTOR_PLUGIN(Index size = other.size())
     smart_copy(other.m_data, other.m_data + other.size(), m_data);
   }
References EIGEN_INTERNAL_DENSE_STORAGE_CTOR_PLUGIN, Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::m_data, size, Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::size(), and Eigen::internal::smart_copy().
DenseStorage_impl() [3/4]
template<typename T , int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::DenseStorage_impl (Index size, Index rows, Index cols) inline constexpr
       : m_data(conditional_aligned_new_auto<T, Align>(size)), m_rows(rows), m_cols(cols) {
     EIGEN_INTERNAL_DENSE_STORAGE_CTOR_PLUGIN({})
   }
References EIGEN_INTERNAL_DENSE_STORAGE_CTOR_PLUGIN.
DenseStorage_impl() [4/4]
template<typename T , int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::DenseStorage_impl (DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options > && other) inline constexpr noexcept
       : m_data(other.m_data), m_rows(other.m_rows), m_cols(other.m_cols) {
     other.m_data = nullptr;
     other.m_rows = 0;
     other.m_cols = 0;
   }
~DenseStorage_impl()
template<typename T , int Options> EIGEN_DEVICE_FUNC Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::~DenseStorage_impl () inline
 { conditional_aligned_delete_auto<T, Align>(m_data, size()); }
References size.
Member Function Documentation
cols()
template<typename T , int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Index Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::cols () const inline constexpr
 { return m_cols; }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
conservativeResize()
template<typename T , int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE void Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::conservativeResize (Index size, Index rows, Index cols) inline constexpr
{
     m_data = conditional_aligned_realloc_new_auto<T, Align>(m_data, size, this->size());
     m_rows = rows;
     m_cols = cols;
   }
References cols, rows, and size.
data() [1/2]
template<typename T , int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE T* Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::data () inline constexpr
 { return m_data; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
data() [2/2]
template<typename T , int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE const T* Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::data () const inline constexpr
 { return m_data; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
operator=() [1/2]
template<typename T , int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE DenseStorage_impl& Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::operator= (const DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options > & other) inline constexpr
{
     resize(other.size(), other.rows(), other.cols());
     smart_copy(other.m_data, other.m_data + other.size(), m_data);
     return *this;
   }
References Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::cols(), Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::m_data, resize(), Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::rows(), Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::size(), and Eigen::internal::smart_copy().
operator=() [2/2]
template<typename T , int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE DenseStorage_impl& Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::operator= (DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options > && other) inline constexpr noexcept
{
     this->swap(other);
     return *this;
   }
References Eigen::internal::swap().
resize()
template<typename T , int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE void Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::resize (Index size, Index rows, Index cols) inline constexpr
{
     Index oldSize = this->size();
     if (oldSize != size) {
       conditional_aligned_delete_auto<T, Align>(m_data, oldSize);
       m_data = conditional_aligned_new_auto<T, Align>(size);
       EIGEN_INTERNAL_DENSE_STORAGE_CTOR_PLUGIN({})
     }
     m_rows = rows;
     m_cols = cols;
   }
References cols, EIGEN_INTERNAL_DENSE_STORAGE_CTOR_PLUGIN, rows, and size.
rows()
template<typename T , int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Index Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::rows () const inline constexpr
 { return m_rows; }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
size()
template<typename T , int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Index Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::size () const inline constexpr
 { return m_rows * m_cols; }
swap()
template<typename T , int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE void Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::swap (DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options > & other) inline constexpr noexcept
{
     numext::swap(m_data, other.m_data);
     numext::swap(m_rows, other.m_rows);
     numext::swap(m_cols, other.m_cols);
   }
References Eigen::numext::swap().
Member Data Documentation
Align
template<typename T , int Options> constexpr bool Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::Align = (Options & DontAlign) == 0 static constexpr private
m_cols
template<typename T , int Options> Index Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::m_cols = 0 private
m_data
template<typename T , int Options> T* Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::m_data = nullptr private
m_rows
template<typename T , int Options> Index Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::m_rows = 0 private
Size
template<typename T , int Options> constexpr int Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::Size = Dynamic static constexpr
The documentation for this class was generated from the following file:
DenseStorage.h