MercuryDPM: ExactSoln Namespace Reference
ExactSoln Namespace Reference
Namespace for exact solution.
Functions
void get_exact_u (const double &t, const Vector< double > &x, Vector< double > &u)
Exact solution of the problem as a vector.
void get_exact_u (const double &t, const double &y, double &u)
Exact solution of the problem as a scalar.
void prescribed_traction (const double &t, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction)
Traction required at the top boundary.
Detailed Description
Namespace for exact solution.
Function Documentation
get_exact_u() [1/2]
void ExactSoln::get_exact_u (const double & t, const double & y, double & u)
Exact solution of the problem as a scalar.
  {
   // I=sqrt(-1)
   complex<double> I(0.0,1.0);
   // omega
   double omega=2.0*MathematicalConstants::Pi;
   // lambda
   complex<double> lambda(0.0,omega*Global_Parameters::ReSt);
   lambda = I*sqrt(lambda);
   // Solution
   complex<double> sol(
    exp(complex<double>(0.0,omega*t)) *
    (exp(lambda*complex<double>(0.0,y))-exp(lambda*complex<double>(0.0,-y)))
    /(exp(I*lambda)-exp(-I*lambda)) );
   // Assign real solution
   u=real(sol);
  }
References Eigen::bfloat16_impl::exp(), I, lambda, Eigen::internal::omega(), BiharmonicTestFunctions2::Pi, Global_Parameters::ReSt, sqrt(), plotPSD::t, and y.
get_exact_u() [2/2]
void ExactSoln::get_exact_u (const double & t, const Vector< double > & x, Vector< double > & u)
Exact solution of the problem as a vector.
  {
   double y=x[1];
   // I=sqrt(-1)
   complex<double> I(0.0,1.0);
   // omega
   double omega=2.0*MathematicalConstants::Pi;
   // lambda
   complex<double> lambda(0.0,omega*Global_Parameters::ReSt);
   lambda = I*sqrt(lambda);
   // Solution
   complex<double> sol(
    exp(complex<double>(0.0,omega*t)) *
    (exp(lambda*complex<double>(0.0,y))-exp(lambda*complex<double>(0.0,-y)))
    /(exp(I*lambda)-exp(-I*lambda)) );
   // Assign real solution
   u.resize(2);
   u[0]=real(sol);
   u[1]=0.0;
  }
References Eigen::bfloat16_impl::exp(), I, lambda, Eigen::internal::omega(), BiharmonicTestFunctions2::Pi, Global_Parameters::ReSt, sqrt(), plotPSD::t, plotDoE::x, and y.
Referenced by RayleighProblem< ELEMENT, TIMESTEPPER >::actions_before_implicit_timestep(), RayleighProblem< ELEMENT, TIMESTEPPER >::doc_solution(), RayleighTractionProblem< ELEMENT, TIMESTEPPER >::doc_solution(), RayleighProblem< ELEMENT, TIMESTEPPER >::set_initial_condition(), and RayleighTractionProblem< ELEMENT, TIMESTEPPER >::set_initial_condition().
prescribed_traction()
void ExactSoln::prescribed_traction (const double & t, const Vector< double > & x, const Vector< double > & n, Vector< double > & traction)
Traction required at the top boundary.
  {
   double y=x[1];
   // I=sqrt(-1)
   complex<double> I(0.0,1.0);
   // omega
   double omega=2.0*MathematicalConstants::Pi;
   // lambda
   complex<double> lambda(0.0,omega*Global_Parameters::ReSt);
   lambda = I*sqrt(lambda);
   // Solution
   complex<double> sol(
    exp(complex<double>(0.0,omega*t)) *
    (exp(lambda*complex<double>(0.0,y))+exp(lambda*complex<double>(0.0,-y)))
    *I*lambda/(exp(I*lambda)-exp(-I*lambda)) );
   //Extract real part and stick into vector
   traction.resize(2);
   traction[0]=real(sol);
   traction[1]=0.0;
  }
References Eigen::bfloat16_impl::exp(), I, lambda, Eigen::internal::omega(), BiharmonicTestFunctions2::Pi, Global_Parameters::ReSt, sqrt(), plotPSD::t, plotDoE::x, and y.
Referenced by RayleighTractionProblem< ELEMENT, TIMESTEPPER >::RayleighTractionProblem().