MercuryDPM: oomph::PMLHelmholtzPointSourceElement< ELEMENT > Class Template Reference
oomph::PMLHelmholtzPointSourceElement< ELEMENT > Class Template Reference
Class to impose point source to (wrapped) Helmholtz element.
Public Member Functions
PMLHelmholtzPointSourceElement ()
Constructor.
~PMLHelmholtzPointSourceElement ()
Destructor (empty)
void setup (const Vector< double > &s_point_source, const std::complex< double > &magnitude)
Set local coordinate and magnitude of point source.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Private Member Functions
void fill_in_point_source_contribution_to_residuals (Vector< double > &residuals)
Add the point source contribution to the residual vector.
Private Attributes
Vector< double > S_point_source
Local coordinates of point at which point source is applied.
std::complex< double > Point_source_magnitude
Magnitude of point source (complex!)
Detailed Description
template<class ELEMENT>
class oomph::PMLHelmholtzPointSourceElement< ELEMENT >
Class to impose point source to (wrapped) Helmholtz element.
Constructor & Destructor Documentation
PMLHelmholtzPointSourceElement()
template<class ELEMENT > oomph::PMLHelmholtzPointSourceElement< ELEMENT >::PMLHelmholtzPointSourceElement () inline
Constructor.
   {
    // Initialise
    Point_source_magnitude=std::complex<double>(0.0,0.0);
   }
~PMLHelmholtzPointSourceElement()
template<class ELEMENT > oomph::PMLHelmholtzPointSourceElement< ELEMENT >::~PMLHelmholtzPointSourceElement () inline
Destructor (empty)
 {}
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT > void oomph::PMLHelmholtzPointSourceElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline
Add the element's contribution to its residual vector and element Jacobian matrix (wrapper)
   {
    //Call the generic routine with the flag set to 1
    ELEMENT::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz(residuals,
                                                             jacobian,1);
    // Add point source contribution
    fill_in_point_source_contribution_to_residuals(residuals);
   }
fill_in_contribution_to_residuals()
template<class ELEMENT > void oomph::PMLHelmholtzPointSourceElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) inline
Add the element's contribution to its residual vector (wrapper)
   {
    //Call the generic residuals function with flag set to 0
    //using a dummy matrix argument
    ELEMENT::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz(
     residuals,GeneralisedElement::Dummy_matrix,0);
    // Add point source contribution
    fill_in_point_source_contribution_to_residuals(residuals);
   }
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_point_source_contribution_to_residuals()
template<class ELEMENT > void oomph::PMLHelmholtzPointSourceElement< ELEMENT >::fill_in_point_source_contribution_to_residuals (Vector< double > & residuals) inline private
Add the point source contribution to the residual vector.
   {
    // No further action
    if (S_point_source.size()==0) return;
    //Find out how many nodes there are
    const unsigned n_node = this->nnode();
    //Set up memory for the shape/test functions
    Shape psi(n_node);
    //Integers to store the local equation and unknown numbers
    int local_eqn_real=0;
    int local_eqn_imag=0;
    // Get shape/test fcts
    this->shape(S_point_source,psi);
    // Assemble residuals
    //--------------------------------
    // Loop over the test functions
    for(unsigned l=0;l<n_node;l++)
     {
      // first, compute the real part contribution
      //-------------------------------------------
      //Get the local equation
      local_eqn_real =
       this->nodal_local_eqn
       (l,this->u_index_pml_fourier_decomposed_helmholtz().real());
      /*IF it's not a boundary condition*/
      if(local_eqn_real >= 0)
       {
        residuals[local_eqn_real] -= 2.0*Point_source_magnitude.real()*psi(l);
       }
      // Second, compute the imaginary part contribution
      //------------------------------------------------
      //Get the local equation
      local_eqn_imag =
       this->nodal_local_eqn
       (l,this->u_index_pml_fourier_decomposed_helmholtz().imag());
      /*IF it's not a boundary condition*/
      if(local_eqn_imag >= 0)
       {
        // Add body force/source term and Helmholtz bit
        residuals[local_eqn_imag] -= 2.0*Point_source_magnitude.imag()*psi(l);
       }
     }
   }
References imag(), and oomph::OneDimLagrange::shape().
setup()
template<class ELEMENT > void oomph::PMLHelmholtzPointSourceElement< ELEMENT >::setup (const Vector< double > & s_point_source, const std::complex< double > & magnitude) inline
Set local coordinate and magnitude of point source.
   {
    S_point_source=s_point_source;
    Point_source_magnitude=magnitude;
   }
References oomph::VectorHelpers::magnitude().
Member Data Documentation
Point_source_magnitude
template<class ELEMENT > std::complex<double> oomph::PMLHelmholtzPointSourceElement< ELEMENT >::Point_source_magnitude private
Magnitude of point source (complex!)
S_point_source
template<class ELEMENT > Vector<double> oomph::PMLHelmholtzPointSourceElement< ELEMENT >::S_point_source private
Local coordinates of point at which point source is applied.
The documentation for this class was generated from the following file:
oscillating_sphere.cc