MercuryDPM: turek_flag_load_balance.cc File Reference
turek_flag_load_balance.cc File Reference
#include "generic.h"
#include "solid.h"
#include "navier_stokes.h"
#include "multi_physics.h"
#include "meshes/cylinder_with_flag_mesh.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >
Problem class.
Namespaces
Global_Parameters
Namespace for global parameters.
Functions
void Global_Parameters::gravity (const double &time, const Vector< double > &xi, Vector< double > &b)
Non-dimensional gravity as body force.
double Global_Parameters::flux (const double &t)
Flux: Pulsatile flow.
void Global_Parameters::set_parameters (const string &case_id)
Set parameters for the various test cases.
int main (int argc, char *argv[])
Driver.
Function Documentation
main()
int main (int argc , char * argv[])
Driver.
 {
 #ifdef OOMPH_HAS_MPI
   MPI_Helpers::init(argc,argv);
 #endif
   // Switch off output modifier
  oomph_info.output_modifier_pt() = &default_output_modifier;
  // Define processor-labeled output file for all on-screen stuff
  std::ofstream output_stream;
  char filename[100];
  sprintf(filename,"RESLT_TUREK_LOAD_BALANCE/OUTPUT.%i",
          MPI_Helpers::communicator_pt()->my_rank());
  output_stream.open(filename);
  oomph_info.stream_pt() = &output_stream;
  OomphLibWarning::set_stream_pt(&output_stream);
  OomphLibError::set_stream_pt(&output_stream);
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Get case id as string
  string case_id="FSI1";
  if (CommandLineArgs::Argc==1)
   {
    oomph_info << "No command line arguments; running self-test FSI1"
               << std::endl;
   }
  else if (CommandLineArgs::Argc==2)
   {
    case_id=CommandLineArgs::Argv[1];
   }
  else
   {
    oomph_info << "Wrong number of command line arguments" << std::endl;
    oomph_info << "Enter none (for default) or one (namely the case id"
               << std::endl;
    oomph_info << "which should be one of: FSI1, FSI2, FSI3, CSM1"
               << std::endl;
   }
  std::cout << "Running case " << case_id << std::endl;
  // Setup parameters for case identified by command line
  // argument
  Global_Parameters::set_parameters(case_id);
  // Length and height of domain
  double length=25.0;
  double height=4.1;
  //Set up the problem
  TurekProblem<AlgebraicElement<RefineableQTaylorHoodElement<2> >,
   RefineableQPVDElement<2,3> > problem(length, height);
  // Prepare output
  DocInfo doc_info;
  ofstream trace_file;
  doc_info.set_directory("RESLT_TUREK_LOAD_BALANCE");
  sprintf(filename,"%s/trace_on_proc%i.dat",doc_info.directory().c_str(),
          problem.communicator_pt()->my_rank());
  trace_file.open(filename);
  // Default number of timesteps
  unsigned nstep=4000;
  if (Global_Parameters::Case_ID=="FSI1")
   {
    std::cout << "Reducing number of steps for FSI1 " << std::endl;
    nstep=400;
   }
  if (CommandLineArgs::Argc==1)
   {
    std::cout << "Reducing number of steps for validation " << std::endl;
    nstep=2;
   }
  //Timestep:
  double dt=Global_Parameters::Dt;
  // Initialise timestep
  problem.initialise_dt(dt);
  // Impulsive start
  problem.assign_initial_values_impulsive(dt);
  // Doc the initial condition
  problem.doc_solution(doc_info,trace_file);
  doc_info.number()++;
 #ifdef OOMPH_HAS_MPI
  // Distribute the problem
  bool report_stats=true;
  // Are there command-line arguments?
  if (CommandLineArgs::Argc==1)
   {
    // No arguments, so it's a validation run
    std::ifstream input_file;
    // All meshes are partitioned
    unsigned n_partition=problem.mesh_pt()->nelement();
    Vector<unsigned> in_element_partition(n_partition,0);
    // Get partition from file
    sprintf(filename,"turek_flag_partition.dat");
    input_file.open(filename);
    std::string input_string;
    for (unsigned e=0;e<n_partition;e++)
     {
      getline(input_file,input_string,'\n');
      in_element_partition[e]=atoi(input_string.c_str());
     }
    // Now distribute the (still uniformly refined) problem
    problem.distribute(in_element_partition,report_stats);
    // This is a validation run, so use the default partition in load_balance()
    problem.set_default_partition_in_load_balance();
   }
  else
   {
    // There were command-line arguments, so distribute without
    // reference to any partition vector
    problem.distribute(report_stats);
   }
 #endif
  // Don't re-set the initial conditions when adapting during first
  // timestep
  bool first = false;
  // Max number of adaptation for time-stepping
  unsigned max_adapt=1;
  // Start of timestepping loop
  for(unsigned i=0;i<nstep;i++)
   {
    // Solve the problem
    problem.unsteady_newton_solve(dt,max_adapt,first);
    // Output the solution
    problem.doc_solution(doc_info,trace_file);
    // Step number
    doc_info.number()++;
    // Load balance the problem
    DocInfo load_doc_info;
    problem.load_balance(load_doc_info,report_stats);
   } // end of timestepping loop
  trace_file.close();
  oomph_info << "Done\n";
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::finalize();
 #endif
 }//end of main
References oomph::CommandLineArgs::Argc, oomph::CommandLineArgs::Argv, Global_Parameters::Case_ID, oomph::default_output_modifier, oomph::DocInfo::directory(), Global_Parameters::Dt, e(), MergeRestartFiles::filename, Global_Physical_Variables::height(), i, oomph::DocInfo::number(), oomph::oomph_info, oomph::OomphInfo::output_modifier_pt(), problem, oomph::DocInfo::set_directory(), Global_Parameters::set_parameters(), Flag_definition::setup(), oomph::OomphInfo::stream_pt(), and oomph::Global_string_for_annotation::string().