MercuryDPM: Eigen::internal::random_longdouble_impl< Specialize > Struct Template Reference
Eigen::internal::random_longdouble_impl< Specialize > Struct Template Reference
#include <RandomImpl.h>
Static Public Member Functions
static constexpr EIGEN_DEVICE_FUNC int mantissaBits ()
static EIGEN_DEVICE_FUNC long double run (int numRandomBits)
Static Public Attributes
static constexpr int Size = sizeof(long double)
Member Function Documentation
mantissaBits()
template<bool Specialize = (sizeof(long double) == 2 * sizeof(uint64_t)) && ((std::numeric_limits<long double>::digits != (2 * std::numeric_limits<double>::digits)))> static constexpr EIGEN_DEVICE_FUNC int Eigen::internal::random_longdouble_impl< Specialize >::mantissaBits () inline static constexpr
 { return NumTraits<long double>::digits() - 1; }
Referenced by Eigen::internal::random_longdouble_impl< Specialize >::run().
run()
template<bool Specialize = (sizeof(long double) == 2 * sizeof(uint64_t)) && ((std::numeric_limits<long double>::digits != (2 * std::numeric_limits<double>::digits)))> static EIGEN_DEVICE_FUNC long double Eigen::internal::random_longdouble_impl< Specialize >::run (int numRandomBits) inline static
{
     eigen_assert(numRandomBits >= 0 && numRandomBits <= mantissaBits());
     EIGEN_USING_STD(memcpy);
     int numLowBits = numext::mini(numRandomBits, 64);
     int numHighBits = numext::maxi(numRandomBits - 64, 0);
     uint64_t randomBits[2];
     long double result = 2.0L;
     memcpy(&randomBits, &result, Size);
     randomBits[0] |= getRandomBits<uint64_t>(numLowBits);
     randomBits[1] |= getRandomBits<uint64_t>(numHighBits);
     memcpy(&result, &randomBits, Size);
     result -= 3.0L;
     return result;
   }
References eigen_assert, EIGEN_USING_STD, Eigen::internal::random_longdouble_impl< Specialize >::mantissaBits(), Eigen::numext::maxi(), Eigen::numext::mini(), and Eigen::internal::random_longdouble_impl< Specialize >::Size.
Member Data Documentation
Size
template<bool Specialize = (sizeof(long double) == 2 * sizeof(uint64_t)) && ((std::numeric_limits<long double>::digits != (2 * std::numeric_limits<double>::digits)))> constexpr int Eigen::internal::random_longdouble_impl< Specialize >::Size = sizeof(long double) static constexpr
Referenced by Eigen::internal::random_longdouble_impl< Specialize >::run().
The documentation for this struct was generated from the following file:
RandomImpl.h