MercuryDPM: Eigen::internal::BaseTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, inner_dim_reordered, Alignment, MakePointer_ > Class Template Reference
Eigen::internal::BaseTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, inner_dim_reordered, Alignment, MakePointer_ > Class Template Reference
#include <TensorContractionMapper.h>
Public Types
typedef SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ > ParentMapper
Public Types inherited from Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >
enum
Public Member Functions
EIGEN_DEVICE_FUNC BaseTensorContractionMapper (const Tensor &tensor, const nocontract_t &nocontract_strides, const nocontract_t &ij_strides, const contract_t &contract_strides, const contract_t &k_strides)
template<typename PacketT , int AlignmentType>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE std::enable_if_t< internal::unpacket_traits< PacketT >::size==packet_size, PacketT > load (Index i, Index j) const
template<typename PacketT , int AlignmentType>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE std::enable_if_t< internal::unpacket_traits< PacketT >::size !=packet_size, PacketT > load (Index i, Index j) const
template<typename PacketT , int AlignmentType>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketT loadPacket (Index i, Index j) const
Public Member Functions inherited from Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >
EIGEN_DEVICE_FUNC SimpleTensorContractionMapper (const Tensor &tensor, const nocontract_t &nocontract_strides, const nocontract_t &ij_strides, const contract_t &contract_strides, const contract_t &k_strides)
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void offsetBuffer (typename Tensor::Index offset)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void prefetch (Index)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar operator() (Index row) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar operator() (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index computeIndex (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE IndexPair< Index > computeIndexPair (Index row, Index col, const Index distance) const
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Index firstAligned (Index size) const
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Index stride () const
const CoeffLoader< Tensor, Tensor::RawAccess, MakePointer_ > & tensor () const
const nocontract_t & nocontract_strides () const
const nocontract_t & ij_strides () const
const contract_t & contract_strides () const
const contract_t & k_strides () const
Additional Inherited Members
Protected Attributes inherited from Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >
CoeffLoader< Tensor, Tensor::RawAccess, MakePointer_ > m_tensor
const nocontract_t m_nocontract_strides
const nocontract_t m_ij_strides
const contract_t m_contract_strides
const contract_t m_k_strides
Member Typedef Documentation
ParentMapper
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, bool inner_dim_reordered, int Alignment, template< class > class MakePointer_> typedef SimpleTensorContractionMapper<Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_> Eigen::internal::BaseTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, inner_dim_reordered, Alignment, MakePointer_ >::ParentMapper
Constructor & Destructor Documentation
BaseTensorContractionMapper()
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, bool inner_dim_reordered, int Alignment, template< class > class MakePointer_> EIGEN_DEVICE_FUNC Eigen::internal::BaseTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, inner_dim_reordered, Alignment, MakePointer_ >::BaseTensorContractionMapper (const Tensor & tensor, const nocontract_t & nocontract_strides, const nocontract_t & ij_strides, const contract_t & contract_strides, const contract_t & k_strides) inline
       : ParentMapper(tensor, nocontract_strides, ij_strides, contract_strides, k_strides) {}
Member Function Documentation
load() [1/2]
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, bool inner_dim_reordered, int Alignment, template< class > class MakePointer_> template<typename PacketT , int AlignmentType> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE std::enable_if_t<internal::unpacket_traits<PacketT>::size == packet_size, PacketT> Eigen::internal::BaseTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, inner_dim_reordered, Alignment, MakePointer_ >::load (Index i, Index j) const inline
{
     // whole method makes column major assumption
     // don't need to add offsets for now (because operator handles that)
     // current code assumes packet size must be a multiple of 2
     EIGEN_STATIC_ASSERT(packet_size % 2 == 0, YOU_MADE_A_PROGRAMMING_MISTAKE);
     if (Tensor::PacketAccess && inner_dim_contiguous && !inner_dim_reordered) {
       const Index index = this->computeIndex(i, j);
       eigen_assert(this->computeIndex(i + packet_size - 1, j) == index + packet_size - 1);
       return this->m_tensor.template packet<AlignmentType>(index);
     }
     const IndexPair<Index> indexPair = this->computeIndexPair(i, j, packet_size - 1);
     const Index first = indexPair.first;
     const Index lastIdx = indexPair.second;
     // We can always do optimized packet reads from left hand side right now, because
     // the vertical matrix dimension on the left hand side is never contracting.
     // On the right hand side we need to check if the contracting dimensions may have
     // been shuffled first.
     if (Tensor::PacketAccess && (side == Lhs || internal::array_size<contract_t>::value <= 1 || !inner_dim_reordered) &&
         (lastIdx - first) == (packet_size - 1)) {
       return this->m_tensor.template packet<AlignmentType>(first);
     }
     EIGEN_ALIGN_MAX Scalar data[packet_size];
     data[0] = this->m_tensor.coeff(first);
     EIGEN_UNROLL_LOOP
     for (Index k = 1; k < packet_size - 1; k += 2) {
       const IndexPair<Index> internal_pair = this->computeIndexPair(i + k, j, 1);
       data[k] = this->m_tensor.coeff(internal_pair.first);
       data[k + 1] = this->m_tensor.coeff(internal_pair.second);
     }
     data[packet_size - 1] = this->m_tensor.coeff(lastIdx);
     return pload<PacketT>(data);
   }
References Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::computeIndex(), Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::computeIndexPair(), data, EIGEN_ALIGN_MAX, eigen_assert, EIGEN_STATIC_ASSERT, EIGEN_UNROLL_LOOP, Eigen::IndexPair< Idx >::first, j, k, Eigen::internal::Lhs, Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_tensor, Eigen::IndexPair< Idx >::second, and side.
load() [2/2]
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, bool inner_dim_reordered, int Alignment, template< class > class MakePointer_> template<typename PacketT , int AlignmentType> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE std::enable_if_t<internal::unpacket_traits<PacketT>::size != packet_size, PacketT> Eigen::internal::BaseTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, inner_dim_reordered, Alignment, MakePointer_ >::load (Index i, Index j) const inline
{
     const Index requested_packet_size = internal::unpacket_traits<PacketT>::size;
     EIGEN_ALIGN_MAX Scalar data[requested_packet_size];
     const IndexPair<Index> indexPair = this->computeIndexPair(i, j, requested_packet_size - 1);
     const Index first = indexPair.first;
     const Index lastIdx = indexPair.second;
     data[0] = this->m_tensor.coeff(first);
     for (Index k = 1; k < requested_packet_size - 1; k += 2) {
       const IndexPair<Index> internal_pair = this->computeIndexPair(i + k, j, 1);
       data[k] = this->m_tensor.coeff(internal_pair.first);
       data[k + 1] = this->m_tensor.coeff(internal_pair.second);
     }
     data[requested_packet_size - 1] = this->m_tensor.coeff(lastIdx);
     return pload<PacketT>(data);
   }
References Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::computeIndexPair(), data, EIGEN_ALIGN_MAX, Eigen::IndexPair< Idx >::first, j, k, Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::m_tensor, and Eigen::IndexPair< Idx >::second.
loadPacket()
template<typename Scalar , typename Index , int side, typename Tensor , typename nocontract_t , typename contract_t , int packet_size, bool inner_dim_contiguous, bool inner_dim_reordered, int Alignment, template< class > class MakePointer_> template<typename PacketT , int AlignmentType> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketT Eigen::internal::BaseTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, inner_dim_reordered, Alignment, MakePointer_ >::loadPacket (Index i, Index j) const inline
{
     return this->load<PacketT, AlignmentType>(i, j);
   }
References i, and j.
The documentation for this class was generated from the following file:
TensorContractionMapper.h