MercuryDPM: Eigen::internal::count_visitor< Scalar > Struct Template Reference
Eigen::internal::count_visitor< Scalar > Struct Template Reference
#include <Visitor.h>
Public Types
using result_type = Index
using Packet = typename packet_traits< Scalar >::type
Public Member Functions
EIGEN_DEVICE_FUNC void init (const Scalar &value, Index, Index)
EIGEN_DEVICE_FUNC void init (const Scalar &value, Index)
EIGEN_DEVICE_FUNC Index count_redux (const Packet &p) const
EIGEN_DEVICE_FUNC void initpacket (const Packet &p, Index, Index)
EIGEN_DEVICE_FUNC void initpacket (const Packet &p, Index)
EIGEN_DEVICE_FUNC void operator() (const Scalar &value, Index, Index)
EIGEN_DEVICE_FUNC void operator() (const Scalar &value, Index)
EIGEN_DEVICE_FUNC void packet (const Packet &p, Index, Index)
EIGEN_DEVICE_FUNC void packet (const Packet &p, Index)
Public Attributes
Index res = 0
Member Typedef Documentation
Packet
template<typename Scalar > using Eigen::internal::count_visitor< Scalar >::Packet = typename packet_traits<Scalar>::type
result_type
template<typename Scalar > using Eigen::internal::count_visitor< Scalar >::result_type = Index
Member Function Documentation
count_redux()
template<typename Scalar > EIGEN_DEVICE_FUNC Index Eigen::internal::count_visitor< Scalar >::count_redux (const Packet & p) const inline
{
     const Packet cst_one = pset1<Packet>(Scalar(1));
     Packet true_vals = pandnot(cst_one, pcmp_eq(p, pzero(p)));
     Scalar num_true = predux(true_vals);
     return static_cast<Index>(num_true);
   }
References p, Eigen::internal::pandnot(), Eigen::internal::pcmp_eq(), Eigen::internal::predux(), and Eigen::internal::pzero().
Referenced by Eigen::internal::count_visitor< Scalar >::initpacket(), and Eigen::internal::count_visitor< Scalar >::packet().
init() [1/2]
template<typename Scalar > EIGEN_DEVICE_FUNC void Eigen::internal::count_visitor< Scalar >::init (const Scalar & value, Index) inline
 { res = value != Scalar(0) ? 1 : 0; }
References Eigen::internal::count_visitor< Scalar >::res, and Eigen::value.
init() [2/2]
template<typename Scalar > EIGEN_DEVICE_FUNC void Eigen::internal::count_visitor< Scalar >::init (const Scalar & value, Index , Index) inline
 { res = value != Scalar(0) ? 1 : 0; }
References Eigen::internal::count_visitor< Scalar >::res, and Eigen::value.
initpacket() [1/2]
template<typename Scalar > EIGEN_DEVICE_FUNC void Eigen::internal::count_visitor< Scalar >::initpacket (const Packet & p, Index) inline
 { res = count_redux(p); }
References Eigen::internal::count_visitor< Scalar >::count_redux(), p, and Eigen::internal::count_visitor< Scalar >::res.
initpacket() [2/2]
template<typename Scalar > EIGEN_DEVICE_FUNC void Eigen::internal::count_visitor< Scalar >::initpacket (const Packet & p, Index , Index) inline
 { res = count_redux(p); }
References Eigen::internal::count_visitor< Scalar >::count_redux(), p, and Eigen::internal::count_visitor< Scalar >::res.
operator()() [1/2]
template<typename Scalar > EIGEN_DEVICE_FUNC void Eigen::internal::count_visitor< Scalar >::operator() (const Scalar & value, Index) inline
{
     if (value != Scalar(0)) res++;
   }
References Eigen::internal::count_visitor< Scalar >::res, and Eigen::value.
operator()() [2/2]
template<typename Scalar > EIGEN_DEVICE_FUNC void Eigen::internal::count_visitor< Scalar >::operator() (const Scalar & value, Index , Index) inline
{
     if (value != Scalar(0)) res++;
   }
References Eigen::internal::count_visitor< Scalar >::res, and Eigen::value.
packet() [1/2]
template<typename Scalar > EIGEN_DEVICE_FUNC void Eigen::internal::count_visitor< Scalar >::packet (const Packet & p, Index) inline
 { res += count_redux(p); }
References Eigen::internal::count_visitor< Scalar >::count_redux(), p, and Eigen::internal::count_visitor< Scalar >::res.
packet() [2/2]
template<typename Scalar > EIGEN_DEVICE_FUNC void Eigen::internal::count_visitor< Scalar >::packet (const Packet & p, Index , Index) inline
 { res += count_redux(p); }
References Eigen::internal::count_visitor< Scalar >::count_redux(), p, and Eigen::internal::count_visitor< Scalar >::res.
Member Data Documentation
res
template<typename Scalar > Index Eigen::internal::count_visitor< Scalar >::res = 0
Referenced by Eigen::internal::count_visitor< Scalar >::init(), Eigen::internal::count_visitor< Scalar >::initpacket(), Eigen::internal::count_visitor< Scalar >::operator()(), and Eigen::internal::count_visitor< Scalar >::packet().
The documentation for this struct was generated from the following file:
Visitor.h