MercuryDPM: Eigen::internal::psign_impl< Packet, std::enable_if_t<!NumTraits< typename unpacket_traits< Packet >::type >::IsComplex &&!NumTraits< typename unpacket_traits< Packet >::type >::IsSigned &&NumTraits< typename unpacket_traits< Packet >::type >::IsInteger > > Struct Template Reference
Eigen::internal::psign_impl< Packet, std::enable_if_t<!NumTraits< typename unpacket_traits< Packet >::type >::IsComplex &&!NumTraits< typename unpacket_traits< Packet >::type >::IsSigned &&NumTraits< typename unpacket_traits< Packet >::type >::IsInteger > > Struct Template Reference
#include <GenericPacketMathFunctions.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC Packet run (const Packet &a)
Member Function Documentation
run()
template<typename Packet > static EIGEN_DEVICE_FUNC Packet Eigen::internal::psign_impl< Packet, std::enable_if_t<!NumTraits< typename unpacket_traits< Packet >::type >::IsComplex &&!NumTraits< typename unpacket_traits< Packet >::type >::IsSigned &&NumTraits< typename unpacket_traits< Packet >::type >::IsInteger > >::run (const Packet & a) inline static
{
     using Scalar = typename unpacket_traits<Packet>::type;
     const Packet cst_one = pset1<Packet>(Scalar(1));
     const Packet cst_zero = pzero(a);
     const Packet zero_mask = pcmp_eq(cst_zero, a);
     return pandnot(cst_one, zero_mask);
   }
References a, Eigen::internal::pandnot(), Eigen::internal::pcmp_eq(), and Eigen::internal::pzero().
The documentation for this struct was generated from the following file:
GenericPacketMathFunctions.h