MercuryDPM: oomph::QElement2BulkCoordinateDerivatives Namespace Reference
oomph::QElement2BulkCoordinateDerivatives Namespace Reference
Functions
void faces0 (const Vector< double > &s, DenseMatrix< double > &dsbulk_dsface, unsigned &interior_direction)
Function for the east and west faces, along which s0 is fixed.
void faces1 (const Vector< double > &s, DenseMatrix< double > &dsbulk_dsface, unsigned &interior_direction)
Function for the north and south faces, along which s1 is fixed.
Detailed Description
Namespace for helper functions that calculate derivatives of the local coordinates in the bulk elements wrt the local coordinates in the face element.
Function Documentation
faces0()
void oomph::QElement2BulkCoordinateDerivatives::faces0 (const Vector< double > & s, DenseMatrix< double > & dsbulk_dsface, unsigned & interior_direction)
Function for the east and west faces, along which s0 is fixed.
     {
       // Bulk coordinate s[0] does not vary along the face
       dsbulk_dsface(0, 0) = 0.0;
       // Bulk coordinate s[1] is the face coordinate
       dsbulk_dsface(1, 0) = 1.0;
       // The interior direction is given by s[0]
       interior_direction = 0;
     }
Referenced by oomph::QHermiteElement< DIM >::build_face_element(), oomph::QSpectralElement< 2, NNODE_1D >::build_face_element(), and oomph::QElement< 2, NNODE_1D >::bulk_coordinate_derivatives_fct_pt().
faces1()
void oomph::QElement2BulkCoordinateDerivatives::faces1 (const Vector< double > & s, DenseMatrix< double > & dsbulk_dsface, unsigned & interior_direction)
Function for the north and south faces, along which s1 is fixed.
     {
       // Bulk coordinate s[0] is the face coordinate
       dsbulk_dsface(0, 0) = 1.0;
       // Bulk coordinate s[1] does not vary along the face
       dsbulk_dsface(1, 0) = 0.0;
       // The interior direction is given by s[1]
       interior_direction = 1;
     }
Referenced by oomph::QHermiteElement< DIM >::build_face_element(), oomph::QSpectralElement< 2, NNODE_1D >::build_face_element(), and oomph::QElement< 2, NNODE_1D >::bulk_coordinate_derivatives_fct_pt().