MercuryDPM: Eigen::internal::evaluator_wrapper_base< XprType > Struct Template Reference
Eigen::internal::evaluator_wrapper_base< XprType > Struct Template Reference
#include <CoreEvaluators.h>
Public Types
enum { CoeffReadCost = evaluator<ArgType>::CoeffReadCost , Flags = evaluator<ArgType>::Flags , Alignment = evaluator<ArgType>::Alignment }
typedef remove_all_t< typename XprType::NestedExpressionType > ArgType
typedef ArgType::Scalar Scalar
typedef ArgType::CoeffReturnType CoeffReturnType
Public Types inherited from Eigen::internal::evaluator_base< XprType >
enum
typedef traits< XprType > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE evaluator_wrapper_base (const ArgType &arg)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
template<int LoadMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType packet (Index index) const
template<int StoreMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void writePacket (Index row, Index col, const PacketType &x)
template<int StoreMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void writePacket (Index index, const PacketType &x)
Public Member Functions inherited from Eigen::internal::evaluator_base< XprType >
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE evaluator_base ()=default
Protected Attributes
evaluator< ArgType > m_argImpl
Member Typedef Documentation
ArgType
template<typename XprType > typedef remove_all_t<typename XprType::NestedExpressionType> Eigen::internal::evaluator_wrapper_base< XprType >::ArgType
CoeffReturnType
template<typename XprType > typedef ArgType::CoeffReturnType Eigen::internal::evaluator_wrapper_base< XprType >::CoeffReturnType
Scalar
template<typename XprType > typedef ArgType::Scalar Eigen::internal::evaluator_wrapper_base< XprType >::Scalar
Member Enumeration Documentation
anonymous enum
template<typename XprType > anonymous enum
Enumerator
CoeffReadCost
Flags
Alignment
        {
     CoeffReadCost = evaluator<ArgType>::CoeffReadCost,
     Flags = evaluator<ArgType>::Flags,
     Alignment = evaluator<ArgType>::Alignment
   };
Constructor & Destructor Documentation
evaluator_wrapper_base()
template<typename XprType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::evaluator_wrapper_base< XprType >::evaluator_wrapper_base (const ArgType & arg) inline explicit
 : m_argImpl(arg) {}
Member Function Documentation
coeff() [1/2]
template<typename XprType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::evaluator_wrapper_base< XprType >::coeff (Index index) const inline
 { return m_argImpl.coeff(index); }
coeff() [2/2]
template<typename XprType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::evaluator_wrapper_base< XprType >::coeff (Index row, Index col) const inline
{
     return m_argImpl.coeff(row, col);
   }
References col(), and row().
coeffRef() [1/2]
template<typename XprType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::evaluator_wrapper_base< XprType >::coeffRef (Index index) inline
 { return m_argImpl.coeffRef(index); }
coeffRef() [2/2]
template<typename XprType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::evaluator_wrapper_base< XprType >::coeffRef (Index row, Index col) inline
 { return m_argImpl.coeffRef(row, col); }
References col(), and row().
packet() [1/2]
template<typename XprType > template<int LoadMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType Eigen::internal::evaluator_wrapper_base< XprType >::packet (Index index) const inline
{
     return m_argImpl.template packet<LoadMode, PacketType>(index);
   }
packet() [2/2]
template<typename XprType > template<int LoadMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType Eigen::internal::evaluator_wrapper_base< XprType >::packet (Index row, Index col) const inline
{
     return m_argImpl.template packet<LoadMode, PacketType>(row, col);
   }
References col(), and row().
writePacket() [1/2]
template<typename XprType > template<int StoreMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::evaluator_wrapper_base< XprType >::writePacket (Index index, const PacketType & x) inline
{
     m_argImpl.template writePacket<StoreMode>(index, x);
   }
References plotDoE::x.
writePacket() [2/2]
template<typename XprType > template<int StoreMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::evaluator_wrapper_base< XprType >::writePacket (Index row, Index col, const PacketType & x) inline
{
     m_argImpl.template writePacket<StoreMode>(row, col, x);
   }
References col(), row(), and plotDoE::x.
Member Data Documentation
m_argImpl
template<typename XprType > evaluator<ArgType> Eigen::internal::evaluator_wrapper_base< XprType >::m_argImpl protected
The documentation for this struct was generated from the following file:
CoreEvaluators.h