MercuryDPM: oomph::RefineableSphericalNavierStokesEquations Class Reference
oomph::RefineableSphericalNavierStokesEquations Class Reference abstract
Refineable version of the Spherical Navier–Stokes equations.
#include <refineable_spherical_navier_stokes_elements.h>
Public Member Functions
RefineableSphericalNavierStokesEquations ()
Empty Constructor.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
double geometric_jacobian (const Vector< double > &x)
Fill in the geometric Jacobian, which in this case is r*r*sin(theta)
void further_build ()
Further build: pass the pointers down to the sons.
Public Member Functions inherited from oomph::SphericalNavierStokesEquations
double cot (const double &th) const
SphericalNavierStokesEquations ()
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const double & re_invro () const
Global Reynolds number multiplied by inverse Rossby number.
double *& re_invro_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
SphericalNavierStokesBodyForceFctPt & body_force_fct_pt ()
Access function for the body-force pointer.
SphericalNavierStokesBodyForceFctPt body_force_fct_pt () const
Access function for the body-force pointer. Const version.
SphericalNavierStokesSourceFctPt & source_fct_pt ()
Access function for the source-function pointer.
SphericalNavierStokesSourceFctPt source_fct_pt () const
Access function for the source-function pointer. Const version.
virtual unsigned npres_spherical_nst () const =0
Function to return number of pressure degrees of freedom.
double u_spherical_nst (const unsigned &n, const unsigned &i) const
double u_spherical_nst (const unsigned &t, const unsigned &n, const unsigned &i) const
virtual unsigned u_index_spherical_nst (const unsigned &i) const
double du_dt_spherical_nst (const unsigned &n, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
virtual double p_spherical_nst (const unsigned &n_p) const =0
virtual void fix_pressure (const unsigned &p_dof, const double &p_value)=0
Pin p_dof-th pressure dof and set it to value specified by p_value.
virtual int p_nodal_index_spherical_nst () const
double pressure_integral () const
Integral of pressure over element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute the vorticity vector at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
double d_kin_energy_dt () const
Get integral of time derivative of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j + du_j/dx_i)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction)
void get_load (const Vector< double > &s, const Vector< double > &N, Vector< double > &load)
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &nplot)
void full_output (std::ostream &outfile)
void full_output (std::ostream &outfile, const unsigned &nplot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void output_vorticity (std::ostream &outfile, const unsigned &nplot)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void compute_error_e (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, FiniteElement::SteadyExactSolutionFctPt exact_soln_dr_pt, FiniteElement::SteadyExactSolutionFctPt exact_soln_dtheta_pt, double &u_error, double &u_norm, double &p_error, double &p_norm)
void compute_shear_stress (std::ostream &outfile)
void extract_velocity (std::ostream &outfile)
Vector< double > actual (const Vector< double > &x)
Vector< double > actual_dr (const Vector< double > &x)
Vector< double > actual_dth (const Vector< double > &x)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void interpolated_u_spherical_nst (const Vector< double > &s, Vector< double > &veloc) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_spherical_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_dudx_spherical_nst (const Vector< double > &s, const unsigned &i, const unsigned &j) const
double interpolated_p_spherical_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
Public Member Functions inherited from oomph::FSIFluidElement
FSIFluidElement ()
Constructor.
FSIFluidElement (const FSIFluidElement &)=delete
Broken copy constructor.
void operator= (const FSIFluidElement &)=delete
Broken assignment operator.
virtual void identify_load_data (std::set< std::pair< Data *, unsigned >> &paired_load_data)=0
virtual void identify_pressure_data (std::set< std::pair< Data *, unsigned >> &paired_pressure_data)=0
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::NavierStokesElementWithDiagonalMassMatrices
NavierStokesElementWithDiagonalMassMatrices ()
Empty constructor.
virtual ~NavierStokesElementWithDiagonalMassMatrices ()
Virtual destructor.
NavierStokesElementWithDiagonalMassMatrices (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken copy constructor.
void operator= (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken assignment operator.
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
virtual unsigned required_nsons () const
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)=0
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void rebuild_from_sons (Mesh *&mesh_pt)=0
virtual void unbuild ()
virtual void deactivate_element ()
virtual bool nodes_built ()
Return true if all the nodes have been built, false if not.
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual unsigned ncont_interpolated_values () const =0
virtual void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
virtual void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)=0
virtual Node * interpolating_node_pt (const unsigned &n, const int &value_id)
virtual double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
virtual Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
virtual unsigned ninterpolating_node (const int &value_id)
virtual unsigned ninterpolating_node_1d (const int &value_id)
virtual void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
virtual void check_integrity (double &max_error)=0
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual RefineableElement * root_element_pt ()
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
virtual void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
virtual void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
Pre-build the element.
virtual void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
virtual void further_setup_hanging_nodes ()
void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
unsigned nshape_controlling_nodes ()
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Public Member Functions inherited from oomph::ElementWithZ2ErrorEstimator
ElementWithZ2ErrorEstimator ()
Default empty constructor.
ElementWithZ2ErrorEstimator (const ElementWithZ2ErrorEstimator &)=delete
Broken copy constructor.
void operator= (const ElementWithZ2ErrorEstimator &)=delete
Broken assignment operator.
virtual unsigned ncompound_fluxes ()
virtual void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
virtual void get_Z2_compound_flux_indices (Vector< unsigned > &flux_index)
virtual unsigned nvertex_node () const =0
Number of vertex nodes in the element.
virtual Node * vertex_node_pt (const unsigned &j) const =0
virtual unsigned nrecovery_order ()=0
Order of recovery shape functions.
Static Public Member Functions
static void pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > &element_pt)
static void unpin_all_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in vector.
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Protected Member Functions
virtual Node * pressure_node_pt (const unsigned &n_p)
virtual void unpin_elemental_pressure_dofs ()=0
Unpin all pressure dofs in the element.
virtual void pin_elemental_redundant_nodal_pressure_dofs ()
Protected Member Functions inherited from oomph::SphericalNavierStokesEquations
virtual int p_local_eqn (const unsigned &n) const =0
virtual double dshape_and_dtest_eulerian_spherical_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_spherical_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual void pshape_spherical_nst (const Vector< double > &s, Shape &psi) const =0
Compute the pressure shape functions at local coordinate s.
virtual void pshape_spherical_nst (const Vector< double > &s, Shape &psi, Shape &test) const =0
virtual void get_body_force_spherical_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
virtual double get_source_spherical_nst (double time, const unsigned &ipt, const Vector< double > &x)
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Private Member Functions
void fill_in_generic_residual_contribution_spherical_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Additional Inherited Members
Public Types inherited from oomph::SphericalNavierStokesEquations
typedef void(* SphericalNavierStokesBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
typedef double(* SphericalNavierStokesSourceFctPt) (const double &time, const Vector< double > &x)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Attributes inherited from oomph::SphericalNavierStokesEquations
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Protected Attributes inherited from oomph::SphericalNavierStokesEquations
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
double * ReInvFr_pt
double * ReInvRo_pt
Vector< double > * G_pt
Pointer to global gravity Vector.
SphericalNavierStokesBodyForceFctPt Body_force_fct_pt
Pointer to body force function.
SphericalNavierStokesSourceFctPt Source_fct_pt
Pointer to volumetric source function.
bool ALE_is_disabled
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number – for plotting/validation purposes.
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Detailed Description
Refineable version of the Spherical Navier–Stokes equations.
Constructor & Destructor Documentation
RefineableSphericalNavierStokesEquations()
oomph::RefineableSphericalNavierStokesEquations::RefineableSphericalNavierStokesEquations () inline
Empty Constructor.
       : SphericalNavierStokesEquations(),
         RefineableElement(),
         ElementWithZ2ErrorEstimator()
     {
     }
Member Function Documentation
fill_in_generic_residual_contribution_spherical_nst()
void oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) private virtual
Add element's contribution to the elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector
Add element's contribution to the elemental residual vector and/or Jacobian matrix. flag=1: compute both flag=0: compute only residual vector
Reimplemented from oomph::SphericalNavierStokesEquations.
   {
     // Find out how many nodes there are
     const unsigned n_node = nnode();
     // Get continuous time from timestepper of first node
     double time = node_pt(0)->time_stepper_pt()->time_pt()->time();
     // Find out how many pressure dofs there are
     const unsigned n_pres = npres_spherical_nst();
     // Get the local indices of the nodal coordinates
     unsigned u_nodal_index[3];
     for (unsigned i = 0; i < 3; ++i)
     {
       u_nodal_index[i] = this->u_index_spherical_nst(i);
     }
     // Which nodal value represents the pressure? (Negative if pressure
     // is not based on nodal interpolation).
     const int p_index = this->p_nodal_index_spherical_nst();
     // Local array of booleans that are true if the l-th pressure value is
     // hanging (avoid repeated virtual function calls)
     bool pressure_dof_is_hanging[n_pres];
     // If the pressure is stored at a node
     if (p_index >= 0)
     {
       // Read out whether the pressure is hanging
       for (unsigned l = 0; l < n_pres; ++l)
       {
         pressure_dof_is_hanging[l] = pressure_node_pt(l)->is_hanging(p_index);
       }
     }
     // Otherwise the pressure is not stored at a node and so cannot hang
     else
     {
       for (unsigned l = 0; l < n_pres; ++l)
       {
         pressure_dof_is_hanging[l] = false;
       }
     }
     // Set up memory for the shape and test functions
     Shape psif(n_node), testf(n_node);
     DShape dpsifdx(n_node, 2), dtestfdx(n_node, 2);
     // Set up memory for pressure shape and test functions
     Shape psip(n_pres), testp(n_pres);
     // Set the value of n_intpt
     const unsigned n_intpt = integral_pt()->nweight();
     // Set the Vector to hold local coordinates
     Vector<double> s(2);
     // Get Physical Variables from Element
     // Reynolds number must be multiplied by the density ratio
     const double dens_ratio = density_ratio();
     const double scaled_re = re() * dens_ratio;
     const double scaled_re_st = re_st() * dens_ratio;
     const double scaled_re_inv_ro = re_invro() * dens_ratio;
     // const double scaled_re_inv_fr = re_invfr()*dens_ratio;
     // const double visc_ratio = viscosity_ratio();
     Vector<double> G = g();
     // Integers to store the local equation and unknown numbers
     int local_eqn = 0, local_unknown = 0;
     // Local storage for pointers to hang info objects
     HangInfo *hang_info_pt = 0, *hang_info2_pt = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < 2; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the shape and test functions
       double J = dshape_and_dtest_eulerian_at_knot_spherical_nst(
         ipt, psif, dpsifdx, testf, dtestfdx);
       // Call the pressure shape and test functions
       pshape_spherical_nst(s, psip, testp);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Calculate local values of the pressure and velocity components
       //--------------------------------------------------------------
       double interpolated_p = 0.0;
       Vector<double> interpolated_u(3, 0.0);
       Vector<double> interpolated_x(2, 0.0);
       Vector<double> mesh_velocity(2, 0.0);
       Vector<double> dudt(3, 0.0);
       DenseMatrix<double> interpolated_dudx(3, 2, 0.0);
       // Calculate pressure
       for (unsigned l = 0; l < n_pres; l++)
       {
         interpolated_p += this->p_spherical_nst(l) * psip(l);
       }
       // Calculate velocities and derivatives
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Cache the shape function
         double psi_ = psif(l);
         // Loop over positions separately
         for (unsigned i = 0; i < 2; i++)
         {
           interpolated_x[i] += nodal_position(l, i) * psi_;
         }
         // Loop over velocity directions (three of these)
         for (unsigned i = 0; i < 3; i++)
         {
           const double u_value = this->nodal_value(l, u_nodal_index[i]);
           interpolated_u[i] += u_value * psi_;
           dudt[i] += du_dt_spherical_nst(l, i) * psi_;
           // Loop over derivative directions for gradients
           for (unsigned j = 0; j < 2; j++)
           {
             interpolated_dudx(i, j) += u_value * dpsifdx(l, j);
           }
         }
         // Only bother to calculate the mesh velocity if we are using an ALE
         // method
         if (!ALE_is_disabled)
         {
           throw OomphLibError(
             "ALE is not properly implemented for Refineable Spherical NS yet",
             OOMPH_CURRENT_FUNCTION,
             OOMPH_EXCEPTION_LOCATION);
           // Loop over directions (only DIM (2) of these)
           for (unsigned i = 0; i < 2; i++)
           {
             mesh_velocity[i] += this->dnodal_position_dt(l, i) * psi_;
           }
         }
       } // End of loop over the nodes
       // Get the user-defined body force terms
       Vector<double> body_force(3);
       this->get_body_force_spherical_nst(
         time, ipt, s, interpolated_x, body_force);
       // Get the user-defined source function
       // double
       // source=this->get_source_spherical_nst(time(),ipt,interpolated_x);
       // r is the first postition component
       const double r = interpolated_x[0];
       const double r2 = r * r;
       // const double theta = interpolated_x[1];
       const double sin_theta = sin(interpolated_x[1]);
       const double cos_theta = cos(interpolated_x[1]);
       const double cot_theta = cos_theta / sin_theta;
       const double u_r = interpolated_u[0];
       const double u_theta = interpolated_u[1];
       const double u_phi = interpolated_u[2];
       // Pre-calculate the scaling factor of the jacobian
       // double W_pure = W;
       // W *= r*r*sin(theta);
       // MOMENTUM EQUATIONS
       //==================
       // Number of master nodes and storage for the weight of the shape function
       unsigned n_master = 1;
       double hang_weight = 1.0;
       // Loop over the nodes for the test functions/equations
       //----------------------------------------------------
       for (unsigned l = 0; l < n_node; l++)
       {
         // Local boolean that indicates the hanging status of the node
         const bool is_node_hanging = node_pt(l)->is_hanging();
         // If the node is hanging
         if (is_node_hanging)
         {
           // Get the hanging pointer
           hang_info_pt = node_pt(l)->hanging_pt();
           // Read out number of master nodes from hanging data
           n_master = hang_info_pt->nmaster();
         }
         // Otherwise the node is its own master
         else
         {
           n_master = 1;
         }
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // Loop over velocity components for equations
           for (unsigned i = 0; i < 2 + 1; i++)
           {
             // Get the equation number
             // If the node is hanging
             if (is_node_hanging)
             {
               // Get the equation number from the master node
               local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                                u_nodal_index[i]);
               // Get the hang weight from the master node
               hang_weight = hang_info_pt->master_weight(m);
             }
             // If the node is not hanging
             else
             {
               // Local equation number
               local_eqn = this->nodal_local_eqn(l, u_nodal_index[i]);
               // Node contributes with full weight
               hang_weight = 1.0;
             }
             // If it's not a boundary condition...
             if (local_eqn >= 0)
             {
               // initialise for residual calculation
               double sum = 0.0;
               switch (i)
               {
                   // RADIAL MOMENTUM EQUATION
                 case 0:
                 {
                   // Convective r-terms
                   double conv = r * u_r * interpolated_dudx(0, 0);
                   // Convective theta-terms
                   conv += u_theta * interpolated_dudx(0, 1);
                   // Remaining convective terms
                   conv -= (u_theta * u_theta + u_phi * u_phi);
                   // Add the time-derivative and convective terms
                   sum += (scaled_re_st * dudt[0] * r2 + scaled_re * r * conv) *
                          sin_theta * testf(l);
                   // Add the user-defined body force term
                   sum -= r2 * sin_theta * body_force[0] * testf(l);
                   // Add the Coriolis term
                   sum -= 2.0 * scaled_re_inv_ro * sin_theta * u_phi * r2 *
                          sin_theta * testf(l);
                   // r-derivative test function component of stress tensor
                   sum += (-interpolated_p + 2 * interpolated_dudx(0, 0)) * r2 *
                          sin_theta * dtestfdx(l, 0);
                   // theta-derivative test function component of stress tensor
                   sum += (r * interpolated_dudx(1, 0) - u_theta +
                           interpolated_dudx(0, 1)) *
                          sin_theta * dtestfdx(l, 1);
                   // Undifferentiated test function component of stress tensor
                   sum += 2.0 *
                          ((-r * interpolated_p + +interpolated_dudx(1, 1) +
                            2.0 * u_r) *
                             sin_theta +
                           u_theta * cos_theta) *
                          testf(l);
                 }
                 break;
                 // THETA-COMPONENT MOMENTUM EQUATION
                 case 1:
                 {
                   // All convective terms
                   double conv =
                     (u_r * interpolated_dudx(1, 0) * r +
                      u_theta * interpolated_dudx(1, 1) + u_r * u_theta) *
                       sin_theta -
                     u_phi * u_phi * cos_theta;
                   // Add the time-derivative and convective terms to the
                   // residual
                   sum += (scaled_re_st * r2 * sin_theta * dudt[1] +
                           scaled_re * r * conv) *
                          testf(l);
                   // Add the user-defined body force term
                   sum -= r2 * sin_theta * body_force[1] * testf(l);
                   // Add the Coriolis term
                   sum -= 2.0 * scaled_re_inv_ro * cos_theta * u_phi * r2 *
                          sin_theta * testf(l);
                   // r-derivative test function component of stress tensor
                   sum += (r * interpolated_dudx(1, 0) - u_theta +
                           interpolated_dudx(0, 1)) *
                          r * sin_theta * dtestfdx(l, 0);
                   // theta-derivative test function component of stress tensor
                   sum += (-r * interpolated_p + 2.0 * interpolated_dudx(1, 1) +
                           2 * u_r) *
                          sin_theta * dtestfdx(l, 1);
                   // Undifferentiated test function component of stress tensor
                   sum -= ((r * interpolated_dudx(1, 0) - u_theta +
                            interpolated_dudx(0, 1)) *
                             sin_theta -
                           (-r * interpolated_p + 2.0 * u_r +
                            2.0 * u_theta * cot_theta) *
                             cos_theta) *
                          testf(l);
                 }
                 break;
                 // PHI-COMPONENT MOMENTUM EQUATION
                 case 2:
                 {
                   // Convective r-terms
                   double conv = u_r * interpolated_dudx(2, 0) * r * sin_theta;
                   // Convective theta-terms
                   conv += u_theta * interpolated_dudx(2, 1) * sin_theta;
                   // Remaining convective terms
                   conv += u_phi * (u_r * sin_theta + u_theta * cos_theta);
                   // Add the time-derivative and convective terms
                   sum += (scaled_re_st * r2 * dudt[2] * sin_theta +
                           scaled_re * conv * r) *
                          testf(l);
                   sum -= r2 * sin_theta * body_force[2] * testf(l);
                   // Add the Coriolis term
                   sum += 2.0 * scaled_re_inv_ro *
                          (cos_theta * u_theta + sin_theta * u_r) * r2 *
                          sin_theta * testf(l);
                   // r-derivative test function component of stress tensor
                   sum += (r2 * interpolated_dudx(2, 0) - r * u_phi) *
                          dtestfdx(l, 0) * sin_theta;
                   // theta-derivative test function component of stress tensor
                   sum +=
                     (interpolated_dudx(2, 1) * sin_theta - u_phi * cos_theta) *
                     dtestfdx(l, 1);
                   // Undifferentiated test function component of stress tensor
                   sum -= ((r * interpolated_dudx(2, 0) - u_phi) * sin_theta +
                           (interpolated_dudx(2, 1) - u_phi * cot_theta) *
                             cos_theta) *
                          testf(l);
                 }
                 break;
               }
               // Add contribution
               // Sign changed to be consistent with other NS implementations
               residuals[local_eqn] -= sum * W * hang_weight;
               // CALCULATE THE JACOBIAN
               if (flag)
               {
                 // Number of master nodes and weights
                 unsigned n_master2 = 1;
                 double hang_weight2 = 1.0;
                 // Loop over the velocity nodes for columns
                 for (unsigned l2 = 0; l2 < n_node; l2++)
                 {
                   // Local boolean for hanging status
                   const bool is_node2_hanging = node_pt(l2)->is_hanging();
                   // If the node is hanging
                   if (is_node2_hanging)
                   {
                     hang_info2_pt = node_pt(l2)->hanging_pt();
                     // Read out number of master nodes from hanging data
                     n_master2 = hang_info2_pt->nmaster();
                   }
                   // Otherwise the node is its own master
                   else
                   {
                     n_master2 = 1;
                   }
                   // Loop over the master nodes
                   for (unsigned m2 = 0; m2 < n_master2; m2++)
                   {
                     // Loop over the velocity components
                     for (unsigned i2 = 0; i2 < 2 + 1; i2++)
                     {
                       // Get the number of the unknown
                       // If the node is hanging
                       if (is_node2_hanging)
                       {
                         // Get the equation number from the master node
                         local_unknown = this->local_hang_eqn(
                           hang_info2_pt->master_node_pt(m2), u_nodal_index[i2]);
                         hang_weight2 = hang_info2_pt->master_weight(m2);
                       }
                       else
                       {
                         local_unknown =
                           this->nodal_local_eqn(l2, u_nodal_index[i2]);
                         hang_weight2 = 1.0;
                       }
                       // If the unknown is non-zero
                       if (local_unknown >= 0)
                       {
                         // Different results for i and i2
                         switch (i)
{
                             // RADIAL MOMENTUM EQUATION
                           case 0:
                             switch (i2)
{
                                 // radial component
                               case 0:
                                 // Add the mass matrix entries
                                 if (flag == 2)
{
                                   mass_matrix(local_eqn, local_unknown) +=
                                     scaled_re_st * psif(l2) * testf(l) * r2 *
                                     sin_theta * W * hang_weight * hang_weight2;
                                 }
{
                                   // Convective r-term contribution
                                   double jac_conv =
                                     r * (psif(l2) * interpolated_dudx(0, 0) +
                                          u_r * dpsifdx(l2, 0));
                                   // Convective theta-term contribution
                                   jac_conv += u_theta * dpsifdx(l2, 1);
                                   // Add the time-derivative contribution and
                                   // the convective
                                   // contribution to the sum
                                   double jac_sum =
                                     (scaled_re_st *
                                        node_pt(l2)->time_stepper_pt()->weight(
                                          1, 0) *
                                        psif(l2) * r2 +
                                      scaled_re * jac_conv * r) *
                                     testf(l);
                                   // Contribution from the r-derivative test
                                   // function
                                   // part of stress tensor
                                   jac_sum +=
                                     2.0 * dpsifdx(l2, 0) * dtestfdx(l, 0) * r2;
                                   // Contribution from the theta-derivative
                                   // test function part  of stress tensor
                                   jac_sum += dpsifdx(l2, 1) * dtestfdx(l, 1);
                                   // Contribution from the undifferentiated
                                   // test function part
                                   // of stress tensor
                                   jac_sum += 4.0 * psif[l2] * testf(l);
                                   // Add the total contribution to the
                                   // jacobian multiplied
                                   // by the jacobian weight
                                   jacobian(local_eqn, local_unknown) -=
                                     jac_sum * sin_theta * W * hang_weight *
                                     hang_weight2;
                                 }
                                 break;
                                 // axial component
                               case 1:
{
                                 // No time derivative contribution
                                 // Convective contribution
                                 double jac_sum =
                                   scaled_re *
                                   (interpolated_dudx(0, 1) - 2.0 * u_theta) *
                                   psif(l2) * r * sin_theta * testf(l);
                                 // Contribution from the theta-derivative
                                 // test function
                                 // part of stress tensor
                                 jac_sum += (r * dpsifdx(l2, 0) - psif(l2)) *
                                            dtestfdx(l, 1) * sin_theta;
                                 // Contribution from the undifferentiated
                                 // test function
                                 // part of stress tensor
                                 jac_sum += 2.0 *
                                            (dpsifdx(l2, 1) * sin_theta +
                                             psif(l2) * cos_theta) *
                                            testf(l);
                                 // Add the full contribution to the jacobian
                                 // matrix
                                 jacobian(local_eqn, local_unknown) -=
                                   jac_sum * W * hang_weight * hang_weight2;
                               } // End of i2 = 1 section
                               break;
                                 // azimuthal component
                               case 2:
{
                                 // Single convective-term contribution
                                 jacobian(local_eqn, local_unknown) +=
                                   2.0 * scaled_re * u_phi * psif[l2] * r *
                                   sin_theta * testf[l] * W * hang_weight *
                                   hang_weight2;
                                 // Add the Coriolis term
                                 jacobian(local_eqn, local_unknown) +=
                                   2.0 * scaled_re_inv_ro * sin_theta *
                                   psif(l2) * r2 * sin_theta * testf[l] * W *
                                   hang_weight * hang_weight2;
                               }
                               break;
                             } // End of contribution radial momentum eqn
                             break;
                             // AXIAL MOMENTUM EQUATION
                           case 1:
                             switch (i2)
{
                                 // radial component
                               case 0:
{
                                 // Convective terms
                                 double jac_sum =
                                   scaled_re *
                                   (r2 * interpolated_dudx(1, 0) + r * u_theta) *
                                   psif(l2) * sin_theta * testf(l);
                                 // Contribution from the r-derivative
                                 // test function part of stress tensor
                                 jac_sum += dpsifdx(l2, 1) * dtestfdx(l, 0) *
                                            sin_theta * r;
                                 // Contribution from the theta-derivative
                                 // test function
                                 // part of stress tensor
                                 jac_sum +=
                                   2.0 * psif(l2) * dtestfdx(l, 1) * sin_theta;
                                 // Contribution from the undifferentiated
                                 // test function
                                 // part of stress tensor
                                 jac_sum -= (dpsifdx(l2, 1) * sin_theta -
                                             2.0 * psif(l2) * cos_theta) *
                                            testf(l);
                                 // Add the sum to the jacobian
                                 jacobian(local_eqn, local_unknown) -=
                                   jac_sum * W * hang_weight * hang_weight2;
                               }
                               break;
                                 // axial component
                               case 1:
                                 // Add the mass matrix terms
                                 if (flag == 2)
{
                                   mass_matrix(local_eqn, local_unknown) +=
                                     scaled_re_st * psif[l2] * testf[l] * W *
                                     r2 * sin_theta * hang_weight * hang_weight2;
                                 }
{
                                   // Contribution from the convective terms
                                   double jac_conv =
                                     r * u_r * dpsifdx(l2, 0) +
                                     u_theta * dpsifdx(l2, 1) +
                                     (interpolated_dudx(1, 1) + u_r) * psif(l2);
                                   // Add the time-derivative term and the
                                   // convective terms
                                   double jac_sum =
                                     (scaled_re_st *
                                        node_pt(l2)->time_stepper_pt()->weight(
                                          1, 0) *
                                        psif(l2) * r2 +
                                      scaled_re * r * jac_conv) *
                                     testf(l) * sin_theta;
                                   // Contribution from the r-derivative test
                                   // function
                                   // part of stress tensor
                                   jac_sum += (r * dpsifdx(l2, 0) - psif(l2)) *
                                              r * dtestfdx(l, 0) * sin_theta;
                                   // Contribution from the theta-derivative
                                   // test function
                                   // part of stress tensor
                                   jac_sum += 2.0 * dpsifdx(l2, 1) *
                                              dtestfdx(l, 1) * sin_theta;
                                   // Contribution from the undifferentiated
                                   // test function
                                   // part of stress tensor
                                   jac_sum -=
                                     ((r * dpsifdx(l2, 0) - psif(l2)) *
                                        sin_theta -
                                      2.0 * psif(l2) * cot_theta * cos_theta) *
                                     testf(l);
                                   // Add the contribution to the jacobian
                                   jacobian(local_eqn, local_unknown) -=
                                     jac_sum * W * hang_weight * hang_weight2;
                                 }
                                 break;
                                 // azimuthal component
                               case 2:
{
                                 // Only a convective term contribution
                                 jacobian(local_eqn, local_unknown) +=
                                   scaled_re * 2.0 * r * psif(l2) * u_phi *
                                   cos_theta * testf(l) * W * hang_weight *
                                   hang_weight2;
                                 // Add the Coriolis term
                                 jacobian(local_eqn, local_unknown) +=
                                   2.0 * scaled_re_inv_ro * cos_theta *
                                   psif(l2) * r2 * sin_theta * testf[l] * W *
                                   hang_weight * hang_weight2;
                               }
                               break;
                             }
                             break;
                             // AZIMUTHAL MOMENTUM EQUATION
                           case 2:
                             switch (i2)
{
                                 // radial component
                               case 0:
{
                                 // Contribution from convective terms
                                 jacobian(local_eqn, local_unknown) -=
                                   scaled_re *
                                   (r * interpolated_dudx(2, 0) + u_phi) *
                                   psif(l2) * testf(l) * r * sin_theta * W *
                                   hang_weight * hang_weight2;
                                 // Coriolis term
                                 jacobian(local_eqn, local_unknown) -=
                                   2.0 * scaled_re_inv_ro * sin_theta *
                                   psif(l2) * r2 * sin_theta * testf[l] * W *
                                   hang_weight * hang_weight2;
                               }
                               break;
                               // axial component
                               case 1:
{
                                 // Contribution from convective terms
                                 jacobian(local_eqn, local_unknown) -=
                                   scaled_re *
                                   (interpolated_dudx(2, 1) * sin_theta +
                                    u_phi * cos_theta) *
                                   r * psif(l2) * testf(l) * W * hang_weight *
                                   hang_weight2;
                                 // Coriolis term
                                 jacobian(local_eqn, local_unknown) -=
                                   2.0 * scaled_re_inv_ro * cos_theta *
                                   psif(l2) * r2 * sin_theta * testf[l] * W *
                                   hang_weight * hang_weight2;
                               }
                               break;
                                 // azimuthal component
                               case 2:
                                 // Add the mass matrix terms
                                 if (flag == 2)
{
                                   mass_matrix(local_eqn, local_unknown) +=
                                     scaled_re_st * psif[l2] * testf[l] * W *
                                     r2 * sin_theta * hang_weight * hang_weight2;
                                 }
{
                                   // Convective terms
                                   double jac_conv =
                                     r * u_r * dpsifdx(l2, 0) * sin_theta;
                                   // Convective theta-term contribution
                                   jac_conv +=
                                     u_theta * dpsifdx(l2, 1) * sin_theta;
                                   // Contribution from the remaining convective
                                   // terms
                                   jac_conv +=
                                     (u_r * sin_theta + u_theta * cos_theta) *
                                     psif(l2);
                                   // Add the convective and time derivatives
                                   double jac_sum =
                                     (scaled_re_st *
                                        node_pt(l2)->time_stepper_pt()->weight(
                                          1, 0) *
                                        psif(l2) * r2 * sin_theta +
                                      scaled_re * r * jac_conv) *
                                     testf(l);
                                   // Contribution from the r-derivative test
                                   // function
                                   // part of stress tensor
                                   jac_sum += (r * dpsifdx(l2, 0) - psif(l2)) *
                                              dtestfdx(l, 0) * r * sin_theta;
                                   // Contribution from the theta-derivative
                                   // test function
                                   // part of stress tensor
                                   jac_sum += (dpsifdx(l2, 1) * sin_theta -
                                               psif(l2) * cos_theta) *
                                              dtestfdx(l, 1);
                                   // Contribution from the undifferentiated
                                   // test function
                                   // part of stress tensor
                                   jac_sum -=
                                     ((r * dpsifdx(l2, 0) - psif(l2)) *
                                        sin_theta +
                                      (dpsifdx(l2, 1) - psif(l2) * cot_theta) *
                                        cos_theta) *
                                     testf(l);
                                   // Add to the jacobian
                                   jacobian(local_eqn, local_unknown) -=
                                     jac_sum * W * hang_weight * hang_weight2;
                                 }
                                 break;
                             }
                             break;
                         }
                       }
                     }
                   }
                 } // End of loop over the nodes
                 // Loop over the pressure shape functions
                 for (unsigned l2 = 0; l2 < n_pres; l2++)
                 {
                   // If the pressure dof is hanging
                   if (pressure_dof_is_hanging[l2])
                   {
                     // Pressure dof is hanging so it must be nodal-based
                     hang_info2_pt = pressure_node_pt(l2)->hanging_pt(p_index);
                     // Get the number of master nodes from the pressure node
                     n_master2 = hang_info2_pt->nmaster();
                   }
                   // Otherwise the node is its own master
                   else
                   {
                     n_master2 = 1;
                   }
                   // Loop over the master nodes
                   for (unsigned m2 = 0; m2 < n_master2; m2++)
                   {
                     // Get the number of the unknown
                     // If the pressure dof is hanging
                     if (pressure_dof_is_hanging[l2])
                     {
                       // Get the unknown from the node
                       local_unknown = local_hang_eqn(
                         hang_info2_pt->master_node_pt(m2), p_index);
                       // Get the weight from the hanging object
                       hang_weight2 = hang_info2_pt->master_weight(m2);
                     }
                     else
                     {
                       local_unknown = p_local_eqn(l2);
                       hang_weight2 = 1.0;
                     }
                     // If the unknown is not pinned
                     if (local_unknown >= 0)
                     {
                       // Add in contributions to different equations
                       switch (i)
                       {
                           // RADIAL MOMENTUM EQUATION
                         case 0:
                           jacobian(local_eqn, local_unknown) +=
                             psip(l2) *
                             (r2 * dtestfdx(l, 0) + 2.0 * r * testf[l]) * W *
                             sin_theta * hang_weight * hang_weight2;
                           break;
                           // AXIAL MOMENTUM EQUATION
                         case 1:
                           jacobian(local_eqn, local_unknown) +=
                             psip(l2) * r *
                             (dtestfdx(l, 1) * sin_theta +
                              cos_theta * testf(l)) *
                             W * hang_weight * hang_weight2;
                           break;
                           // AZIMUTHAL MOMENTUM EQUATION
                         case 2:
                           break;
                       }
                     }
                   }
                 } // End of loop over pressure dofs
               } // End of Jacobian calculation
             } // End of if not boundary condition statement
           } // End of loop over velocity components
         } // End of loop over master nodes
       } // End of loop over nodes
       // CONTINUITY EQUATION
       //===================
       // Loop over the pressure shape functions
       for (unsigned l = 0; l < n_pres; l++)
       {
         // If the pressure dof is hanging
         if (pressure_dof_is_hanging[l])
         {
           // Pressure dof is hanging so it must be nodal-based
           hang_info_pt = pressure_node_pt(l)->hanging_pt(p_index);
           // Get the number of master nodes from the pressure node
           n_master = hang_info_pt->nmaster();
         }
         // Otherwise the node is its own master
         else
         {
           n_master = 1;
         }
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // Get the number of the unknown
           // If the pressure dof is hanging
           if (pressure_dof_is_hanging[l])
           {
             local_eqn =
               local_hang_eqn(hang_info_pt->master_node_pt(m), p_index);
             hang_weight = hang_info_pt->master_weight(m);
           }
           else
           {
             local_eqn = p_local_eqn(l);
             hang_weight = 1.0;
           }
           // If the equation is not pinned
           if (local_eqn >= 0)
           {
             // The entire continuity equation
             residuals[local_eqn] += ((2.0 * u_r + r * interpolated_dudx(0, 0) +
                                       interpolated_dudx(1, 1)) *
                                        sin_theta +
                                      u_theta * cos_theta) *
                                     r * testp(l) * W * hang_weight;
             // CALCULATE THE JACOBIAN
             //======================
             if (flag)
             {
               unsigned n_master2 = 1;
               double hang_weight2 = 1.0;
               // Loop over the velocity nodes for columns
               for (unsigned l2 = 0; l2 < n_node; l2++)
               {
                 // Local boolean to indicate whether the node is hanging
                 bool is_node2_hanging = node_pt(l2)->is_hanging();
                 // If the node is hanging
                 if (is_node2_hanging)
                 {
                   hang_info2_pt = node_pt(l2)->hanging_pt();
                   // Read out number of master nodes from hanging data
                   n_master2 = hang_info2_pt->nmaster();
                 }
                 // Otherwise the node is its own master
                 else
                 {
                   n_master2 = 1;
                 }
                 // Loop over the master nodes
                 for (unsigned m2 = 0; m2 < n_master2; m2++)
                 {
                   // Loop over the velocity components
                   for (unsigned i2 = 0; i2 < 2 + 1; i2++)
                   {
                     // Get the number of the unknown
                     // If the node is hanging
                     if (is_node2_hanging)
                     {
                       // Get the equation number from the master node
                       local_unknown = local_hang_eqn(
                         hang_info2_pt->master_node_pt(m2), u_nodal_index[i2]);
                       hang_weight2 = hang_info2_pt->master_weight(m2);
                     }
                     else
                     {
                       local_unknown =
                         this->nodal_local_eqn(l2, u_nodal_index[i2]);
                       hang_weight2 = 1.0;
                     }
                     // If the unknown is not pinned
                     if (local_unknown >= 0)
                     {
                       switch (i2)
                       {
                           // radial component
                         case 0:
                           jacobian(local_eqn, local_unknown) +=
                             (2.0 * psif(l2) + r * dpsifdx(l2, 0)) * r *
                             sin_theta * testp(l) * W * hang_weight *
                             hang_weight2;
                           break;
                           // axial component
                         case 1:
                           jacobian(local_eqn, local_unknown) +=
                             r *
                             (dpsifdx(l2, 1) * sin_theta +
                              psif(l2) * cos_theta) *
                             testp(l) * W * hang_weight * hang_weight2;
                           break;
                           // azimuthal component
                         case 2:
                           break;
                       }
                     }
                   }
                 }
               } // End of loop over nodes
               // NO PRESSURE CONTRIBUTIONS TO CONTINUITY EQUATION
             } // End of Jacobian calculation
           }
         }
       } // End of loop over pressure nodes
     } // end of loop over integration points
   }
References oomph::SphericalNavierStokesEquations::ALE_is_disabled, Global_Parameters::body_force(), cos(), oomph::SphericalNavierStokesEquations::density_ratio(), oomph::FiniteElement::dnodal_position_dt(), oomph::SphericalNavierStokesEquations::dshape_and_dtest_eulerian_at_knot_spherical_nst(), oomph::SphericalNavierStokesEquations::du_dt_spherical_nst(), G, oomph::SphericalNavierStokesEquations::g(), oomph::SphericalNavierStokesEquations::get_body_force_spherical_nst(), oomph::Node::hanging_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::Node::is_hanging(), J, j, oomph::Integral::knot(), oomph::RefineableElement::local_hang_eqn(), m, m2(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::SphericalNavierStokesEquations::npres_spherical_nst(), oomph::Integral::nweight(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::SphericalNavierStokesEquations::p_local_eqn(), oomph::SphericalNavierStokesEquations::p_nodal_index_spherical_nst(), oomph::SphericalNavierStokesEquations::p_spherical_nst(), pressure_node_pt(), oomph::SphericalNavierStokesEquations::pshape_spherical_nst(), UniformPSDSelfTest::r, oomph::SphericalNavierStokesEquations::re(), oomph::SphericalNavierStokesEquations::re_invro(), oomph::SphericalNavierStokesEquations::re_st(), s, sin(), oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Data::time_stepper_pt(), oomph::SphericalNavierStokesEquations::u_index_spherical_nst(), Global_Parameters::u_r(), Global_Parameters::u_theta(), w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and oomph::TimeStepper::weight().
further_build()
void oomph::RefineableSphericalNavierStokesEquations::further_build () inline virtual
Further build: pass the pointers down to the sons.
Reimplemented from oomph::RefineableElement.
Reimplemented in oomph::RefineableQSphericalCrouzeixRaviartElement.
     {
       // Find the father element
       RefineableSphericalNavierStokesEquations* cast_father_element_pt =
         dynamic_cast<RefineableSphericalNavierStokesEquations*>(
           this->father_element_pt());
       // Set the viscosity ratio pointer
       this->Viscosity_Ratio_pt = cast_father_element_pt->viscosity_ratio_pt();
       // Set the density ratio pointer
       this->Density_Ratio_pt = cast_father_element_pt->density_ratio_pt();
       // Set pointer to global Reynolds number
       this->Re_pt = cast_father_element_pt->re_pt();
       // Set pointer to global Reynolds number x Strouhal number (=Womersley)
       this->ReSt_pt = cast_father_element_pt->re_st_pt();
       // Set pointer to the global Reynolds number x inverse Rossby number
       this->ReInvRo_pt = cast_father_element_pt->re_invro_pt();
       // Set pointer to global Reynolds number x inverse Froude number
       this->ReInvFr_pt = cast_father_element_pt->re_invfr_pt();
       // Set pointer to global gravity Vector
       this->G_pt = cast_father_element_pt->g_pt();
       // Set pointer to body force function
       this->Body_force_fct_pt = cast_father_element_pt->body_force_fct_pt();
       // Set pointer to volumetric source function
       this->Source_fct_pt = cast_father_element_pt->source_fct_pt();
       // Set the ALE flag
       this->ALE_is_disabled = cast_father_element_pt->ALE_is_disabled;
     }
References oomph::SphericalNavierStokesEquations::ALE_is_disabled, oomph::SphericalNavierStokesEquations::Body_force_fct_pt, oomph::SphericalNavierStokesEquations::body_force_fct_pt(), oomph::SphericalNavierStokesEquations::Density_Ratio_pt, oomph::SphericalNavierStokesEquations::density_ratio_pt(), oomph::RefineableElement::father_element_pt(), oomph::SphericalNavierStokesEquations::G_pt, oomph::SphericalNavierStokesEquations::g_pt(), oomph::SphericalNavierStokesEquations::re_invfr_pt(), oomph::SphericalNavierStokesEquations::re_invro_pt(), oomph::SphericalNavierStokesEquations::Re_pt, oomph::SphericalNavierStokesEquations::re_pt(), oomph::SphericalNavierStokesEquations::re_st_pt(), oomph::SphericalNavierStokesEquations::ReInvFr_pt, oomph::SphericalNavierStokesEquations::ReInvRo_pt, oomph::SphericalNavierStokesEquations::ReSt_pt, oomph::SphericalNavierStokesEquations::Source_fct_pt, oomph::SphericalNavierStokesEquations::source_fct_pt(), oomph::SphericalNavierStokesEquations::Viscosity_Ratio_pt, and oomph::SphericalNavierStokesEquations::viscosity_ratio_pt().
Referenced by oomph::RefineableQSphericalCrouzeixRaviartElement::further_build().
geometric_jacobian()
double oomph::RefineableSphericalNavierStokesEquations::geometric_jacobian (const Vector< double > & x) inline virtual
Fill in the geometric Jacobian, which in this case is r*r*sin(theta)
Reimplemented from oomph::ElementWithZ2ErrorEstimator.
     {
       return x[0] * x[0] * sin(x[1]);
     }
References sin(), and plotDoE::x.
get_Z2_flux()
void oomph::RefineableSphericalNavierStokesEquations::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) inline virtual
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       // Specify the number of velocity dimensions
       unsigned DIM = 3;
 #ifdef PARANOID
       unsigned num_entries = DIM + ((DIM * DIM) - DIM) / 2;
       if (flux.size() < num_entries)
       {
         std::ostringstream error_message;
         error_message << "The flux vector is too small, size " << flux.size()
                       << ", whereas it should be " << num_entries << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Get strain rate matrix
       DenseMatrix<double> strainrate(DIM);
       this->strain_rate(s, strainrate);
       // Pack into flux Vector
       unsigned icount = 0;
       // Start with diagonal terms
       for (unsigned i = 0; i < DIM; i++)
       {
         flux[icount] = strainrate(i, i);
         icount++;
       }
       // Off diagonals row by row
       for (unsigned i = 0; i < DIM; i++)
       {
         for (unsigned j = i + 1; j < DIM; j++)
         {
           flux[icount] = strainrate(i, j);
           icount++;
         }
       }
     }
References DIM, ProblemParameters::flux(), i, j, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::SphericalNavierStokesEquations::strain_rate().
Referenced by oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::get_Z2_flux().
num_Z2_flux_terms()
unsigned oomph::RefineableSphericalNavierStokesEquations::num_Z2_flux_terms () inline virtual
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       // 3 diagonal strain rates, 3 off diagonal
       return 6;
     }
Referenced by oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::get_Z2_compound_flux_indices(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::get_Z2_flux(), and oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::num_Z2_flux_terms().
pin_elemental_redundant_nodal_pressure_dofs()
virtual void oomph::RefineableSphericalNavierStokesEquations::pin_elemental_redundant_nodal_pressure_dofs () inline protected virtual
Pin unused nodal pressure dofs (empty by default, because by default pressure dofs are not associated with nodes)
Reimplemented in oomph::RefineableQSphericalTaylorHoodElement.
 {}
Referenced by pin_redundant_nodal_pressures().
pin_redundant_nodal_pressures()
static void oomph::RefineableSphericalNavierStokesEquations::pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > & element_pt) inline static
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function
RefineableSphericalNavierStokesEquations:: pin_all_nodal_pressure_dofs()
which is empty by default and should be implemented for elements with nodal pressure degrees of freedom (e.g. for refineable Taylor-Hood.)
     {
       // Loop over all elements to brutally pin all nodal pressure degrees of
       // freedom
       unsigned n_element = element_pt.size();
       for (unsigned e = 0; e < n_element; e++)
       {
         dynamic_cast<RefineableSphericalNavierStokesEquations*>(element_pt[e])
           ->pin_elemental_redundant_nodal_pressure_dofs();
       }
     }
References e(), and pin_elemental_redundant_nodal_pressure_dofs().
pressure_node_pt()
virtual Node* oomph::RefineableSphericalNavierStokesEquations::pressure_node_pt (const unsigned & n_p) inline protected virtual
Pointer to n_p-th pressure node (Default: NULL, indicating that pressure is not based on nodal interpolation).
Reimplemented in oomph::RefineableQSphericalTaylorHoodElement.
     {
       return NULL;
     }
Referenced by fill_in_generic_residual_contribution_spherical_nst().
unpin_all_pressure_dofs()
static void oomph::RefineableSphericalNavierStokesEquations::unpin_all_pressure_dofs (const Vector< GeneralisedElement * > & element_pt) inline static
Unpin all pressure dofs in elements listed in vector.
     {
       // Loop over all elements to brutally unpin all nodal pressure degrees of
       // freedom and internal pressure degrees of freedom
       unsigned n_element = element_pt.size();
       for (unsigned e = 0; e < n_element; e++)
       {
         dynamic_cast<RefineableSphericalNavierStokesEquations*>(element_pt[e])
           ->unpin_elemental_pressure_dofs();
       }
     }
References e(), and unpin_elemental_pressure_dofs().
unpin_elemental_pressure_dofs()
virtual void oomph::RefineableSphericalNavierStokesEquations::unpin_elemental_pressure_dofs () protected pure virtual
Unpin all pressure dofs in the element.
Implemented in oomph::RefineableQSphericalCrouzeixRaviartElement, and oomph::RefineableQSphericalTaylorHoodElement.
Referenced by unpin_all_pressure_dofs().
The documentation for this class was generated from the following files:
refineable_spherical_navier_stokes_elements.h
refineable_spherical_navier_stokes_elements.cc