MercuryDPM: oomph::NavierStokesSchurComplementPreconditioner Class Reference
oomph::NavierStokesSchurComplementPreconditioner Class Reference
#include <navier_stokes_preconditioners.h>
Public Member Functions
NavierStokesSchurComplementPreconditioner (Problem *problem_pt)
Constructor - sets defaults for control flags.
virtual ~NavierStokesSchurComplementPreconditioner ()
Destructor.
NavierStokesSchurComplementPreconditioner (const NavierStokesSchurComplementPreconditioner &)=delete
Broken copy constructor.
void set_problem_pt (Problem *problem_pt)
Broken assignment operator.
Problem * problem_pt () const
void enable_accept_non_NavierStokesElementWithDiagonalMassMatrices_elements ()
void disable_accept_non_NavierStokesElementWithDiagonalMassMatrices_elements ()
void setup ()
Setup the preconditioner.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Apply preconditioner to Vector r.
void set_navier_stokes_mesh (Mesh *mesh_pt, const bool &allow_multiple_element_type_in_navier_stokes_mesh=false)
void set_p_preconditioner (Preconditioner *new_p_preconditioner_pt)
Function to set a new pressure matrix preconditioner (inexact solver)
void set_p_superlu_preconditioner ()
void set_f_preconditioner (Preconditioner *new_f_preconditioner_pt)
Function to set a new momentum matrix preconditioner (inexact solver)
void use_lsc ()
Use LSC version of the preconditioner.
void use_fp ()
Use Fp version of the preconditioner.
void set_f_superlu_preconditioner ()
void enable_doc_time ()
Enable documentation of time.
void disable_doc_time ()
Disable documentation of time.
void clean_up_memory ()
Helper function to delete preconditioner data.
void enable_robin_for_fp ()
Use Robin BC elements for the Fp preconditioner.
void disable_robin_for_fp ()
Don't use Robin BC elements for the Fp preconditioenr.
void pin_first_pressure_dof_in_press_adv_diff ()
void unpin_first_pressure_dof_in_press_adv_diff ()
template<class ELEMENT >
void validate (DocInfo &doc_info, Problem *orig_problem_pt)
void pin_all_non_pressure_dofs ()
Pin all non-pressure dofs.
void get_pressure_advection_diffusion_matrix (CRDoubleMatrix &fp_matrix)
Get the pressure advection diffusion matrix.
void reset_pin_status ()
Reset pin status of all values.
void setup (DoubleMatrixBase *matrix_pt)
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
virtual void setup ()=0
Public Member Functions inherited from oomph::BlockPreconditioner< CRDoubleMatrix >
BlockPreconditioner ()
Constructor.
BlockPreconditioner (const BlockPreconditioner &)=delete
Broken copy constructor.
virtual ~BlockPreconditioner ()
Destructor.
void operator= (const BlockPreconditioner &)=delete
Broken assignment operator.
CRDoubleMatrix * matrix_pt () const
void turn_on_recursive_debug_flag ()
void turn_off_recursive_debug_flag ()
void turn_on_debug_flag ()
Toggles on the debug flag.
void turn_off_debug_flag ()
Toggles off the debug flag.
void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> &doftype_coarsen_map_coarse)
virtual void block_setup ()
void block_setup (const Vector< unsigned > &dof_to_block_map)
void get_block (const unsigned &i, const unsigned &j, CRDoubleMatrix &output_matrix, const bool &ignore_replacement_block=false) const
CRDoubleMatrix get_block (const unsigned &i, const unsigned &j, const bool &ignore_replacement_block=false) const
void set_master_matrix_pt (CRDoubleMatrix *in_matrix_pt)
Set the matrix_pt in the upper-most master preconditioner.
void get_block_other_matrix (const unsigned &i, const unsigned &j, CRDoubleMatrix *in_matrix_pt, CRDoubleMatrix &output_matrix)
void get_blocks (DenseMatrix< bool > &required_blocks, DenseMatrix< CRDoubleMatrix * > &block_matrix_pt) const
void get_dof_level_block (const unsigned &i, const unsigned &j, CRDoubleMatrix &output_block, const bool &ignore_replacement_block=false) const
void get_dof_level_block (const unsigned &block_i, const unsigned &block_j, CRDoubleMatrix &output_block, const bool &ignore_replacement_block) const
CRDoubleMatrix get_concatenated_block (const VectorMatrix< BlockSelector > &selected_block)
void get_concatenated_block_vector (const Vector< unsigned > &block_vec_number, const DoubleVector &v, DoubleVector &b)
void return_concatenated_block_vector (const Vector< unsigned > &block_vec_number, const DoubleVector &b, DoubleVector &v) const
Takes concatenated block ordered vector, b, and copies its.
void get_block_vectors (const Vector< unsigned > &block_vec_number, const DoubleVector &v, Vector< DoubleVector > &s) const
void get_block_vectors (const DoubleVector &v, Vector< DoubleVector > &s) const
void return_block_vectors (const Vector< unsigned > &block_vec_number, const Vector< DoubleVector > &s, DoubleVector &v) const
void return_block_vectors (const Vector< DoubleVector > &s, DoubleVector &v) const
void get_block_vector (const unsigned &n, const DoubleVector &v, DoubleVector &b) const
void return_block_vector (const unsigned &n, const DoubleVector &b, DoubleVector &v) const
void get_block_ordered_preconditioner_vector (const DoubleVector &v, DoubleVector &w)
void return_block_ordered_preconditioner_vector (const DoubleVector &w, DoubleVector &v) const
unsigned nblock_types () const
Return the number of block types.
unsigned ndof_types () const
Return the total number of DOF types.
const Mesh * mesh_pt (const unsigned &i) const
unsigned nmesh () const
int block_number (const unsigned &i_dof) const
Return the block number corresponding to a global index i_dof.
int index_in_block (const unsigned &i_dof) const
const LinearAlgebraDistribution * block_distribution_pt (const unsigned &b) const
Access function to the block distributions (const version).
LinearAlgebraDistribution * block_distribution_pt (const unsigned b)
Access function to the block distributions (non-const version).
LinearAlgebraDistribution * dof_block_distribution_pt (const unsigned &b)
Access function to the dof-level block distributions.
const LinearAlgebraDistribution * master_distribution_pt () const
unsigned ndof_types_in_mesh (const unsigned &i) const
bool is_subsidiary_block_preconditioner () const
bool is_master_block_preconditioner () const
void set_block_output_to_files (const std::string &basefilename)
void disable_block_output_to_files ()
Turn off output of blocks (by clearing the basefilename string).
bool block_output_on () const
Test if output of blocks is on or not.
void output_blocks_to_files (const std::string &basefilename, const unsigned &precision=8) const
void post_block_matrix_assembly_partial_clear ()
BlockPreconditioner< CRDoubleMatrix > * master_block_preconditioner_pt () const
Access function to the master block preconditioner pt.
void clear_block_preconditioner_base ()
void document ()
Vector< Vector< unsigned > > doftype_coarsen_map_fine () const
Vector< unsigned > get_fine_grain_dof_types_in (const unsigned &i) const
unsigned nfine_grain_dof_types_in (const unsigned &i) const
MapMatrix< unsigned, CRDoubleMatrix * > replacement_dof_block_pt () const
Access function to the replaced dof-level blocks.
void setup_matrix_vector_product (MatrixVectorProduct *matvec_prod_pt, CRDoubleMatrix *block_pt, const Vector< unsigned > &block_col_indices)
void setup_matrix_vector_product (MatrixVectorProduct *matvec_prod_pt, CRDoubleMatrix *block_pt, const unsigned &block_col_index)
void internal_get_block_ordered_preconditioner_vector (const DoubleVector &v, DoubleVector &w) const
void internal_return_block_ordered_preconditioner_vector (const DoubleVector &w, DoubleVector &v) const
unsigned internal_nblock_types () const
unsigned internal_ndof_types () const
void internal_return_block_vector (const unsigned &n, const DoubleVector &b, DoubleVector &v) const
void internal_get_block_vector (const unsigned &n, const DoubleVector &v, DoubleVector &b) const
void internal_get_block_vectors (const Vector< unsigned > &block_vec_number, const DoubleVector &v, Vector< DoubleVector > &s) const
void internal_get_block_vectors (const DoubleVector &v, Vector< DoubleVector > &s) const
void internal_return_block_vectors (const Vector< unsigned > &block_vec_number, const Vector< DoubleVector > &s, DoubleVector &v) const
void internal_return_block_vectors (const Vector< DoubleVector > &s, DoubleVector &v) const
void internal_get_block (const unsigned &i, const unsigned &j, CRDoubleMatrix &output_block) const
void internal_get_block (const unsigned &block_i, const unsigned &block_j, CRDoubleMatrix &output_block) const
int internal_block_number (const unsigned &i_dof) const
int internal_index_in_block (const unsigned &i_dof) const
const LinearAlgebraDistribution * internal_block_distribution_pt (const unsigned &b) const
Access function to the internal block distributions.
void insert_auxiliary_block_distribution (const Vector< unsigned > &block_vec_number, LinearAlgebraDistribution *dist_pt)
void block_matrix_test (const unsigned &i, const unsigned &j, const CRDoubleMatrix *block_matrix_pt) const
int get_index_of_value (const Vector< myType > &vec, const myType val, const bool sorted=false) const
Public Member Functions inherited from oomph::Preconditioner
Preconditioner ()
Constructor.
Preconditioner (const Preconditioner &)=delete
Broken copy constructor.
void operator= (const Preconditioner &)=delete
Broken assignment operator.
virtual ~Preconditioner ()
Destructor (empty)
virtual void preconditioner_solve_transpose (const DoubleVector &r, DoubleVector &z)
void setup (DoubleMatrixBase *matrix_pt)
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
void enable_silent_preconditioner_setup ()
Set up the block preconditioner quietly!
void disable_silent_preconditioner_setup ()
Be verbose in the block preconditioner setup.
virtual void set_matrix_pt (DoubleMatrixBase *matrix_pt)
Set the matrix pointer.
virtual const OomphCommunicator * comm_pt () const
Get function for comm pointer.
virtual void set_comm_pt (const OomphCommunicator *const comm_pt)
Set the communicator pointer.
double setup_time () const
Returns the time to setup the preconditioner.
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> &doftype_coarsen_map_coarse)
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
void build_distribution (const LinearAlgebraDistribution &dist)
Private Member Functions
void assemble_inv_press_and_veloc_mass_matrix_diagonal (CRDoubleMatrix *&inv_p_mass_pt, CRDoubleMatrix *&inv_v_mass_pt, const bool &do_both)
Private Attributes
Preconditioner * P_preconditioner_pt
Pointer to the 'preconditioner' for the pressure matrix.
Preconditioner * F_preconditioner_pt
Pointer to the 'preconditioner' for the F matrix.
bool Using_default_f_preconditioner
flag indicating whether the default F preconditioner is used
bool Using_default_p_preconditioner
flag indicating whether the default P preconditioner is used
bool Preconditioner_has_been_setup
bool Accept_non_NavierStokesElementWithDiagonalMassMatrices_elements
bool F_preconditioner_is_block_preconditioner
bool Doc_time
Set Doc_time to true for outputting results of timings.
MatrixVectorProduct * QBt_mat_vec_pt
MatrixVectorProduct operator for Qv^{-1} Bt.
MatrixVectorProduct * Bt_mat_vec_pt
MatrixVectorProduct operator for Bt.
MatrixVectorProduct * F_mat_vec_pt
MatrixVectorProduct operator for F.
MatrixVectorProduct * E_mat_vec_pt
MatrixVectorProduct operator for E = Fp Qp^{-1} (only for Fp variant)
Mesh * Navier_stokes_mesh_pt
bool Allow_multiple_element_type_in_navier_stokes_mesh
bool Use_LSC
Boolean to indicate use of LSC (true) or Fp (false) variant.
bool Use_robin_for_fp
Use Robin BC elements for Fp preconditoner?
std::map< Data *, std::vector< int > > Eqn_number_backup
bool Pin_first_pressure_dof_in_press_adv_diff
Problem * Problem_pt
Additional Inherited Members
Protected Member Functions inherited from oomph::BlockPreconditioner< CRDoubleMatrix >
void set_nmesh (const unsigned &n)
void set_mesh (const unsigned &i, const Mesh *const mesh_pt, const bool &allow_multiple_element_type_in_mesh=false)
void set_replacement_dof_block (const unsigned &block_i, const unsigned &block_j, CRDoubleMatrix *replacement_dof_block_pt)
bool any_mesh_distributed () const
int internal_dof_number (const unsigned &i_dof) const
unsigned internal_index_in_dof (const unsigned &i_dof) const
unsigned internal_block_dimension (const unsigned &b) const
unsigned internal_dof_block_dimension (const unsigned &i) const
unsigned master_nrow () const
unsigned internal_master_dof_number (const unsigned &b) const
const LinearAlgebraDistribution * internal_preconditioner_matrix_distribution_pt () const
const LinearAlgebraDistribution * preconditioner_matrix_distribution_pt () const
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
Protected Attributes inherited from oomph::BlockPreconditioner< CRDoubleMatrix >
MapMatrix< unsigned, CRDoubleMatrix * > Replacement_dof_block_pt
The replacement dof-level blocks.
Vector< LinearAlgebraDistribution * > Block_distribution_pt
The distribution for the blocks.
Vector< Vector< unsigned > > Block_to_dof_map_coarse
Vector< Vector< unsigned > > Block_to_dof_map_fine
Mapping for the block types to the most fine grain dof types.
Vector< Vector< unsigned > > Doftype_coarsen_map_coarse
Vector< Vector< unsigned > > Doftype_coarsen_map_fine
Vector< LinearAlgebraDistribution * > Internal_block_distribution_pt
Storage for the default distribution for each internal block.
Vector< LinearAlgebraDistribution * > Dof_block_distribution_pt
Vector< unsigned > Allow_multiple_element_type_in_mesh
Vector< const Mesh * > Mesh_pt
Vector< unsigned > Ndof_types_in_mesh
unsigned Internal_nblock_types
unsigned Internal_ndof_types
Protected Attributes inherited from oomph::Preconditioner
bool Silent_preconditioner_setup
Boolean to indicate whether or not the build should be done silently.
std::ostream * Stream_pt
Pointer to the output stream – defaults to std::cout.
Detailed Description
///////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////// The least-squares commutator (LSC; formerly BFBT) Navier Stokes preconditioner. It uses blocks corresponding to the velocity and pressure unknowns, i.e. there are a total of 2x2 blocks, and all velocity components are treated as a single block of unknowns.
Here are the details: An "ideal" Navier-Stokes preconditioner would solve the system
\[ \left(\begin{array}{cc} {\bf F} & {\bf G} \\ {\bf D} & {\bf 0} \end{array} \right) \left(\begin{array}{c} {\bf z}_u \\ {\bf z}_p \end{array} \right) = \left(\begin{array}{c} {\bf r}_u \\ {\bf r}_p \end{array} \right) \]
where \({\bf F}\) is the momentum block, \({\bf G} \) the discrete gradient operator, and \({\bf D}\) the discrete divergence operator. (For unstabilised elements, we have \({\bf D} = {\bf G}^T \) and in much of the literature the divergence matrix is denoted by \({\bf B} \) .) The use of this preconditioner would ensure the convergence of any iterative linear solver in a single iteration but its application is, of course, exactly as expensive as a direct solve. The LSC/BFBT preconditioner replaces the exact Jacobian by a block-triangular approximation
\[ \left(\begin{array}{cc} {\bf F} & {\bf G} \\ {\bf 0} & -{\bf M}_s \end{array} \right) \left(\begin{array}{c} {\bf z}_u \\ {\bf z}_p \end{array} \right) = \left(\begin{array}{c} {\bf r}_u \\ {\bf r}_p \end{array} \right), \]
where \({\bf M}_s\) is an approximation to the pressure Schur-complement \({\bf S} = {\bf D} {\bf F}^{-1}{\bf G}. \) This system can be solved in two steps:
Solve the second row for \({\bf z}_p\) via
\[ {\bf z}_p = - {\bf M}_s^{-1} {\bf r}_p \]
Given \({\bf z}_p \) , solve the first row for \({\bf z}_u\) via
\[ {\bf z}_u = {\bf F}^{-1} \big({\bf r}_u - {\bf G} {\bf z}_p \big) \]
In the LSC/BFBT preconditioner, the action of the inverse pressure Schur complement
\[ {\bf z}_p = - {\bf M}_s^{-1} {\bf r}_p \]
is approximated by
\[ {\bf z}_p = - \big({\bf D} \widehat{\bf Q}^{-1}{\bf G} \big)^{-1} \big({\bf D} \widehat{\bf Q}^{-1}{\bf F} \widehat{\bf Q}^{-1}{\bf G}\big) \big({\bf D} \widehat{\bf Q}^{-1}{\bf G} \big)^{-1} {\bf r}_p, \]
where \(\widehat{\bf Q} \) is the diagonal of the velocity mass matrix. The evaluation of this expression involves two linear solves involving the matrix
\[ {\bf P} = \big({\bf D} \widehat{\bf Q}^{-1}{\bf G} \big) \]
which has the character of a matrix arising from the discretisation of a Poisson problem on the pressure space. We also have to evaluate matrix-vector products with the matrix
\[ {\bf E}={\bf D}\widehat{\bf Q}^{-1}{\bf F}\widehat{\bf Q}^{-1}{\bf G} \]
Details of the theory can be found in "Finite Elements and Fast Iterative Solvers with Applications in Incompressible Fluid Dynamics" by Howard C. Elman, David J. Silvester, and Andrew J. Wathen, published by Oxford University Press, 2006.
In our implementation of the preconditioner, the linear systems can either be solved "exactly", using SuperLU (in its incarnation as an exact preconditioner; this is the default) or by any other Preconditioner (inexact solver) specified via the access functions
NavierStokesSchurComplementPreconditioner::set_f_preconditioner(...)
or
NavierStokesSchurComplementPreconditioner::set_p_preconditioner(...)
Constructor & Destructor Documentation
NavierStokesSchurComplementPreconditioner() [1/2]
oomph::NavierStokesSchurComplementPreconditioner::NavierStokesSchurComplementPreconditioner (Problem * problem_pt) inline
Constructor - sets defaults for control flags.
       : BlockPreconditioner<CRDoubleMatrix>(), Problem_pt(problem_pt)
     {
       // Insist that all elements are of type
       // NavierStokesElementWithDiagonalMassMatrices and issue a warning
       // if one is not.
       Accept_non_NavierStokesElementWithDiagonalMassMatrices_elements = false;
       // Use Robin BC elements for Fp preconditioner -- yes by default
       Use_robin_for_fp = true;
       // Flag to indicate that the preconditioner has been setup
       // previously -- if setup() is called again, data can
       // be wiped.
       Preconditioner_has_been_setup = false;
       // By default we use the LSC version
       Use_LSC = true;
       // By default we use SuperLU for both p and f blocks
       Using_default_p_preconditioner = true;
       Using_default_f_preconditioner = true;
       // Pin pressure dof in press adv diff problem for Fp precond
       Pin_first_pressure_dof_in_press_adv_diff = true;
       Navier_stokes_mesh_pt = 0;
       // Set default preconditioners (inexact solvers) -- they are
       // members of this class!
       P_preconditioner_pt = 0;
       F_preconditioner_pt = 0;
       // set Doc_time to false
       Doc_time = false;
       // null the off diagonal Block matrix pt
       Bt_mat_vec_pt = 0;
       // null the F matrix vector product helper
       F_mat_vec_pt = 0;
       // null the QBt matrix vector product pt
       QBt_mat_vec_pt = 0;
       // null the E matrix vector product helper in Fp
       E_mat_vec_pt = 0;
       // Initially assume that there are no multiple element types in the
       // Navier-Stokes mesh
       Allow_multiple_element_type_in_navier_stokes_mesh = false;
     }
References Accept_non_NavierStokesElementWithDiagonalMassMatrices_elements, Allow_multiple_element_type_in_navier_stokes_mesh, Bt_mat_vec_pt, Doc_time, E_mat_vec_pt, F_mat_vec_pt, F_preconditioner_pt, Navier_stokes_mesh_pt, P_preconditioner_pt, Pin_first_pressure_dof_in_press_adv_diff, Preconditioner_has_been_setup, QBt_mat_vec_pt, Use_LSC, Use_robin_for_fp, Using_default_f_preconditioner, and Using_default_p_preconditioner.
~NavierStokesSchurComplementPreconditioner()
virtual oomph::NavierStokesSchurComplementPreconditioner::~NavierStokesSchurComplementPreconditioner () inline virtual
Destructor.
     {
       clean_up_memory();
     }
References clean_up_memory().
NavierStokesSchurComplementPreconditioner() [2/2]
oomph::NavierStokesSchurComplementPreconditioner::NavierStokesSchurComplementPreconditioner (const NavierStokesSchurComplementPreconditioner &) delete
Broken copy constructor.
Member Function Documentation
assemble_inv_press_and_veloc_mass_matrix_diagonal()
void oomph::NavierStokesSchurComplementPreconditioner::assemble_inv_press_and_veloc_mass_matrix_diagonal (CRDoubleMatrix *& inv_p_mass_pt, CRDoubleMatrix *& inv_v_mass_pt, const bool & do_both) private
Helper function to assemble the inverse diagonals of the pressure and velocity mass matrices from the elemental contributions defined in NavierStokesEquations<DIM>. If do_both=true, both are computed, otherwise only the velocity mass matrix (the LSC version of the preconditioner only needs that one)
Helper function to assemble the inverse diagonals of the pressure and velocity mass matrix from the elemental contributions defined in NavierStokesElementWithDiagonalMassMatrices:: get_pressure_and_velocity_mass_matrix_diagonal(...) If do_both=true, both are computed, otherwise only the velocity mass matrix (the LSC version of the preconditioner only needs that one)
   {
     // determine the velocity rows required by this processor
     unsigned v_first_row = this->block_distribution_pt(0)->first_row();
     unsigned v_nrow_local = this->block_distribution_pt(0)->nrow_local();
     unsigned v_nrow = this->block_distribution_pt(0)->nrow();
     // create storage for the diagonals
     double* v_values = new double[v_nrow_local];
     for (unsigned i = 0; i < v_nrow_local; i++)
     {
       v_values[i] = 0.0;
     }
     // Equivalent information for pressure mass matrix (only needed for
     // Fp version)
     unsigned p_first_row = 0;
     unsigned p_nrow_local = 0;
     unsigned p_nrow = 0;
     double* p_values = 0;
     if (!Use_LSC)
     {
       // determine the pressure rows required by this processor
       p_first_row = this->block_distribution_pt(1)->first_row();
       p_nrow_local = this->block_distribution_pt(1)->nrow_local();
       p_nrow = this->block_distribution_pt(1)->nrow();
       // create storage for the diagonals
       p_values = new double[p_nrow_local];
       for (unsigned i = 0; i < p_nrow_local; i++)
       {
         p_values[i] = 0.0;
       }
     }
     // if the problem is distributed
     bool distributed = false;
 #ifdef OOMPH_HAS_MPI
     if (problem_pt()->distributed() ||
         this->master_distribution_pt()->distributed())
     {
       distributed = true;
     }
 #endif
     // next we get the diagonal velocity mass matrix data
     if (distributed)
     {
 #ifdef OOMPH_HAS_MPI
       // the number of processors
       unsigned nproc = comm_pt()->nproc();
       // and my rank
       unsigned my_rank = comm_pt()->my_rank();
       // determine the rows for which we have lookup rows
       // if the problem is NOT distributed then we only classify global
       // equations on this processor to avoid duplication (as every processor
       // holds every element)
       unsigned first_lookup_row = 0;
       unsigned last_lookup_row = 0;
       first_lookup_row = this->master_distribution_pt()->first_row();
       last_lookup_row =
         first_lookup_row + this->master_distribution_pt()->nrow_local() - 1;
       // find number of local elements
       unsigned n_el = Navier_stokes_mesh_pt->nelement();
       // get the master distribution pt
       const LinearAlgebraDistribution* master_distribution_pt =
         this->master_distribution_pt();
       // Do the two blocks (0: veloc; 1: press)
       unsigned max_block = 0;
       if (!Use_LSC) max_block = 1;
       for (unsigned block_index = 0; block_index <= max_block; block_index++)
       {
         // Local working variables: Default to velocity
         unsigned v_or_p_first_row = v_first_row;
         double* v_or_p_values = v_values;
         // Switch to pressure
         if (block_index == 1)
         {
           v_or_p_first_row = p_first_row;
           v_or_p_values = p_values;
         }
         // the diagonal mass matrix contributions that have been
         // classified and should be sent to another processor
         Vector<double>* classified_contributions_send =
           new Vector<double>[nproc];
         // the corresponding block indices
         Vector<unsigned>* classified_indices_send = new Vector<unsigned>[nproc];
         // the matrix contributions that cannot be classified by this processor
         // and therefore must be sent to another for classification
         Vector<double>* unclassified_contributions_send =
           new Vector<double>[nproc];
         // the corresponding global indices that require classification
         Vector<unsigned>* unclassified_indices_send =
           new Vector<unsigned>[nproc];
         // get the velocity or pressure distribution pt
         const LinearAlgebraDistribution* velocity_or_press_dist_pt =
           this->block_distribution_pt(block_index);
         // get the contribution for each element
         for (unsigned e = 0; e < n_el; e++)
         {
           // Get element
           GeneralisedElement* el_pt = Navier_stokes_mesh_pt->element_pt(e);
           // check that the element is not halo
           if (!el_pt->is_halo())
           {
             // find number of degrees of freedom in the element
             // (this is slightly too big because it includes the
             // pressure dofs but this doesn't matter)
             unsigned el_dof = el_pt->ndof();
             // Allocate local storage for the element's contribution to the
             // mass matrix diagonal
             Vector<double> el_vmm_diagonal(el_dof, 0.0);
             Vector<double> el_pmm_diagonal(el_dof, 0.0);
             unsigned which_one = 2;
             if (block_index == 1) which_one = 1;
             NavierStokesElementWithDiagonalMassMatrices* cast_el_pt = 0;
             cast_el_pt =
               dynamic_cast<NavierStokesElementWithDiagonalMassMatrices*>(el_pt);
             if (cast_el_pt != 0)
             {
               cast_el_pt->get_pressure_and_velocity_mass_matrix_diagonal(
                 el_pmm_diagonal, el_vmm_diagonal, which_one);
             }
             // get the contribution for each dof
             for (unsigned i = 0; i < el_dof; i++)
             {
               // Get the equation number
               unsigned eqn_number = el_pt->eqn_number(i);
               // if I have lookup information on this processor
               if ((eqn_number >= first_lookup_row) &&
                   (eqn_number <= last_lookup_row))
               {
                 // Only use the dofs that we're dealing with here
                 if (this->block_number(eqn_number) == int(block_index))
                 {
                   // get the index in the block
                   unsigned index = this->index_in_block(eqn_number);
                   // determine which processor requires the block index
                   for (unsigned p = 0; p < nproc; p++)
                   {
                     if ((index >= velocity_or_press_dist_pt->first_row(p)) &&
                         (index < (velocity_or_press_dist_pt->first_row(p) +
                                   velocity_or_press_dist_pt->nrow_local(p))))
                     {
                       // if it is required by this processor then add the
                       // contribution
                       if (p == my_rank)
                       {
                         if (block_index == 0)
{
                           v_or_p_values[index - v_or_p_first_row] +=
                             el_vmm_diagonal[i];
                         }
                         else if (block_index == 1)
{
                           v_or_p_values[index - v_or_p_first_row] +=
                             el_pmm_diagonal[i];
                         }
                       }
                       // otherwise store it for communication
                       else
                       {
                         if (block_index == 0)
{
                           classified_contributions_send[p].push_back(
                             el_vmm_diagonal[i]);
                           classified_indices_send[p].push_back(index);
                         }
                         else if (block_index == 1)
{
                           classified_contributions_send[p].push_back(
                             el_pmm_diagonal[i]);
                           classified_indices_send[p].push_back(index);
                         }
                       }
                     }
                   }
                 }
               }
               // if we do not have the lookup information on this processor
               // then we send the mass matrix contribution to a processor
               // which we know to have the lookup information
               // the assumption: the processor for which the master block
               // preconditioner distribution will definitely hold the lookup
               // data for eqn_number (although others may)
               else if (problem_pt()->distributed())
               {
                 // determine which processor requires the block index
                 unsigned p = 0;
                 while (
                   !(eqn_number >= master_distribution_pt->first_row(p) &&
                     (eqn_number < (master_distribution_pt->first_row(p) +
                                    master_distribution_pt->nrow_local(p)))))
                 {
                   p++;
                 }
                 // store the data
                 if (block_index == 0)
                 {
                   unclassified_contributions_send[p].push_back(
                     el_vmm_diagonal[i]);
                   unclassified_indices_send[p].push_back(eqn_number);
                 }
                 else if (block_index == 1)
                 {
                   unclassified_contributions_send[p].push_back(
                     el_pmm_diagonal[i]);
                   unclassified_indices_send[p].push_back(eqn_number);
                 }
               }
             }
           }
         }
         // next the unclassified contributions are communicated to
         // processors that can classify them
         // first determine how many unclassified rows are to be sent to
         // each processor
         unsigned* n_unclassified_send = new unsigned[nproc];
         for (unsigned p = 0; p < nproc; p++)
         {
           if (p == my_rank)
           {
             n_unclassified_send[p] = 0;
           }
           else
           {
             n_unclassified_send[p] = unclassified_contributions_send[p].size();
           }
         }
         // then all-to-all com number of unclassified to be sent / recv
         unsigned* n_unclassified_recv = new unsigned[nproc];
         MPI_Alltoall(n_unclassified_send,
                      1,
                      MPI_UNSIGNED,
                      n_unclassified_recv,
                      1,
                      MPI_UNSIGNED,
                      comm_pt()->mpi_comm());
         // the base displacement for the sends
         MPI_Aint base_displacement;
         MPI_Get_address(v_or_p_values, &base_displacement);
         // allocate storage for the data to be received
         // and post the sends and recvs
         Vector<double*> unclassified_contributions_recv(nproc);
         Vector<unsigned*> unclassified_indices_recv(nproc);
         Vector<MPI_Request> unclassified_recv_requests;
         Vector<MPI_Request> unclassified_send_requests;
         Vector<unsigned> unclassified_recv_proc;
         for (unsigned p = 0; p < nproc; p++)
         {
           if (p != my_rank)
           {
             // recv
             if (n_unclassified_recv[p] > 0)
             {
               unclassified_contributions_recv[p] =
                 new double[n_unclassified_recv[p]];
               unclassified_indices_recv[p] =
                 new unsigned[n_unclassified_recv[p]];
               // data for the struct data type
               MPI_Datatype recv_types[2];
               MPI_Aint recv_displacements[2];
               int recv_sz[2];
               // contributions
               MPI_Type_contiguous(
                 n_unclassified_recv[p], MPI_DOUBLE, &recv_types[0]);
               MPI_Type_commit(&recv_types[0]);
               MPI_Get_address(unclassified_contributions_recv[p],
                               &recv_displacements[0]);
               recv_displacements[0] -= base_displacement;
               recv_sz[0] = 1;
               // indices
               MPI_Type_contiguous(
                 n_unclassified_recv[p], MPI_UNSIGNED, &recv_types[1]);
               MPI_Type_commit(&recv_types[1]);
               MPI_Get_address(unclassified_indices_recv[p],
                               &recv_displacements[1]);
               recv_displacements[1] -= base_displacement;
               recv_sz[1] = 1;
               // build the final recv type
               MPI_Datatype final_recv_type;
               MPI_Type_create_struct(
                 2, recv_sz, recv_displacements, recv_types, &final_recv_type);
               MPI_Type_commit(&final_recv_type);
               // and recv
               MPI_Request req;
               MPI_Irecv(v_or_p_values,
                         1,
                         final_recv_type,
                         p,
                         0,
                         comm_pt()->mpi_comm(),
                         &req);
               unclassified_recv_requests.push_back(req);
               unclassified_recv_proc.push_back(p);
               MPI_Type_free(&recv_types[0]);
               MPI_Type_free(&recv_types[1]);
               MPI_Type_free(&final_recv_type);
             }
             // send
             if (n_unclassified_send[p] > 0)
             {
               // data for the struct data type
               MPI_Datatype send_types[2];
               MPI_Aint send_displacements[2];
               int send_sz[2];
               // contributions
               MPI_Type_contiguous(
                 n_unclassified_send[p], MPI_DOUBLE, &send_types[0]);
               MPI_Type_commit(&send_types[0]);
               MPI_Get_address(&unclassified_contributions_send[p][0],
                               &send_displacements[0]);
               send_displacements[0] -= base_displacement;
               send_sz[0] = 1;
               // indices
               MPI_Type_contiguous(
                 n_unclassified_send[p], MPI_UNSIGNED, &send_types[1]);
               MPI_Type_commit(&send_types[1]);
               MPI_Get_address(&unclassified_indices_send[p][0],
                               &send_displacements[1]);
               send_displacements[1] -= base_displacement;
               send_sz[1] = 1;
               // build the final send type
               MPI_Datatype final_send_type;
               MPI_Type_create_struct(
                 2, send_sz, send_displacements, send_types, &final_send_type);
               MPI_Type_commit(&final_send_type);
               // and send
               MPI_Request req;
               MPI_Isend(v_or_p_values,
                         1,
                         final_send_type,
                         p,
                         0,
                         comm_pt()->mpi_comm(),
                         &req);
               unclassified_send_requests.push_back(req);
               MPI_Type_free(&send_types[0]);
               MPI_Type_free(&send_types[1]);
               MPI_Type_free(&final_send_type);
             }
           }
         }
         // next classify the data as it is received
         unsigned n_unclassified_recv_req = unclassified_recv_requests.size();
         while (n_unclassified_recv_req > 0)
         {
           // get the processor number and remove the completed request
           // for the vector of requests
           int req_num;
           MPI_Waitany(n_unclassified_recv_req,
                       &unclassified_recv_requests[0],
                       &req_num,
                       MPI_STATUS_IGNORE);
           unsigned p = unclassified_recv_proc[req_num];
           unclassified_recv_requests.erase(unclassified_recv_requests.begin() +
                                            req_num);
           unclassified_recv_proc.erase(unclassified_recv_proc.begin() +
                                        req_num);
           n_unclassified_recv_req--;
           // next classify the dofs
           // and store them for sending to other processors if required
           unsigned n_recv = n_unclassified_recv[p];
           for (unsigned i = 0; i < n_recv; i++)
           {
             unsigned eqn_number = unclassified_indices_recv[p][i];
             // Only deal with our block unknowns
             if (this->block_number(eqn_number) == int(block_index))
             {
               // get the index in the block
               unsigned index = this->index_in_block(eqn_number);
               // determine which processor requires the block index
               for (unsigned pp = 0; pp < nproc; pp++)
               {
                 if ((index >= velocity_or_press_dist_pt->first_row(pp)) &&
                     (index < (velocity_or_press_dist_pt->first_row(pp) +
                               velocity_or_press_dist_pt->nrow_local(pp))))
                 {
                   // if it is required by this processor then add the
                   // contribution
                   if (pp == my_rank)
                   {
                     v_or_p_values[index - v_or_p_first_row] +=
                       unclassified_contributions_recv[p][i];
                   }
                   // otherwise store it for communication
                   else
                   {
                     double v = unclassified_contributions_recv[p][i];
                     classified_contributions_send[pp].push_back(v);
                     classified_indices_send[pp].push_back(index);
                   }
                 }
               }
             }
           }
           // clean up
           delete[] unclassified_contributions_recv[p];
           delete[] unclassified_indices_recv[p];
         }
         delete[] n_unclassified_recv;
         // now all indices have been classified
         // next the classified contributions are communicated to
         // processors that require them
         // first determine how many classified rows are to be sent to
         // each processor
         unsigned* n_classified_send = new unsigned[nproc];
         for (unsigned p = 0; p < nproc; p++)
         {
           if (p == my_rank)
           {
             n_classified_send[p] = 0;
           }
           else
           {
             n_classified_send[p] = classified_contributions_send[p].size();
           }
         }
         // then all-to-all number of classified to be sent / recv
         unsigned* n_classified_recv = new unsigned[nproc];
         MPI_Alltoall(n_classified_send,
                      1,
                      MPI_UNSIGNED,
                      n_classified_recv,
                      1,
                      MPI_UNSIGNED,
                      comm_pt()->mpi_comm());
         // allocate storage for the data to be received
         // and post the sends and recvs
         Vector<double*> classified_contributions_recv(nproc);
         Vector<unsigned*> classified_indices_recv(nproc);
         Vector<MPI_Request> classified_recv_requests;
         Vector<MPI_Request> classified_send_requests;
         Vector<unsigned> classified_recv_proc;
         for (unsigned p = 0; p < nproc; p++)
         {
           if (p != my_rank)
           {
             // recv
             if (n_classified_recv[p] > 0)
             {
               classified_contributions_recv[p] =
                 new double[n_classified_recv[p]];
               classified_indices_recv[p] = new unsigned[n_classified_recv[p]];
               // data for the struct data type
               MPI_Datatype recv_types[2];
               MPI_Aint recv_displacements[2];
               int recv_sz[2];
               // contributions
               MPI_Type_contiguous(
                 n_classified_recv[p], MPI_DOUBLE, &recv_types[0]);
               MPI_Type_commit(&recv_types[0]);
               MPI_Get_address(classified_contributions_recv[p],
                               &recv_displacements[0]);
               recv_displacements[0] -= base_displacement;
               recv_sz[0] = 1;
               // indices
               MPI_Type_contiguous(
                 n_classified_recv[p], MPI_UNSIGNED, &recv_types[1]);
               MPI_Type_commit(&recv_types[1]);
               MPI_Get_address(classified_indices_recv[p],
                               &recv_displacements[1]);
               recv_displacements[1] -= base_displacement;
               recv_sz[1] = 1;
               // build the final recv type
               MPI_Datatype final_recv_type;
               MPI_Type_create_struct(
                 2, recv_sz, recv_displacements, recv_types, &final_recv_type);
               MPI_Type_commit(&final_recv_type);
               // and recv
               MPI_Request req;
               MPI_Irecv(v_or_p_values,
                         1,
                         final_recv_type,
                         p,
                         0,
                         comm_pt()->mpi_comm(),
                         &req);
               classified_recv_requests.push_back(req);
               classified_recv_proc.push_back(p);
               MPI_Type_free(&recv_types[0]);
               MPI_Type_free(&recv_types[1]);
               MPI_Type_free(&final_recv_type);
             }
             // send
             if (n_classified_send[p] > 0)
             {
               // data for the struct data type
               MPI_Datatype send_types[2];
               MPI_Aint send_displacements[2];
               int send_sz[2];
               // contributions
               MPI_Type_contiguous(
                 n_classified_send[p], MPI_DOUBLE, &send_types[0]);
               MPI_Type_commit(&send_types[0]);
               MPI_Get_address(&classified_contributions_send[p][0],
                               &send_displacements[0]);
               send_displacements[0] -= base_displacement;
               send_sz[0] = 1;
               // indices
               MPI_Type_contiguous(
                 n_classified_send[p], MPI_UNSIGNED, &send_types[1]);
               MPI_Type_commit(&send_types[1]);
               MPI_Get_address(&classified_indices_send[p][0],
                               &send_displacements[1]);
               send_displacements[1] -= base_displacement;
               send_sz[1] = 1;
               // build the final send type
               MPI_Datatype final_send_type;
               MPI_Type_create_struct(
                 2, send_sz, send_displacements, send_types, &final_send_type);
               MPI_Type_commit(&final_send_type);
               // and send
               MPI_Request req;
               MPI_Isend(v_or_p_values,
                         1,
                         final_send_type,
                         p,
                         0,
                         comm_pt()->mpi_comm(),
                         &req);
               classified_send_requests.push_back(req);
               MPI_Type_free(&send_types[0]);
               MPI_Type_free(&send_types[1]);
               MPI_Type_free(&final_send_type);
             }
           }
         }
         // next classify the data as it is received
         unsigned n_classified_recv_req = classified_recv_requests.size();
         while (n_classified_recv_req > 0)
         {
           // get the processor number and remove the completed request
           // for the vector of requests
           int req_num;
           MPI_Waitany(n_classified_recv_req,
                       &classified_recv_requests[0],
                       &req_num,
                       MPI_STATUS_IGNORE);
           unsigned p = classified_recv_proc[req_num];
           classified_recv_requests.erase(classified_recv_requests.begin() +
                                          req_num);
           classified_recv_proc.erase(classified_recv_proc.begin() + req_num);
           n_classified_recv_req--;
           // next classify the dofs
           // and store them for sending to other processors if required
           unsigned n_recv = n_classified_recv[p];
           for (unsigned i = 0; i < n_recv; i++)
           {
             v_or_p_values[classified_indices_recv[p][i] - v_or_p_first_row] +=
               classified_contributions_recv[p][i];
           }
           // clean up
           delete[] classified_contributions_recv[p];
           delete[] classified_indices_recv[p];
         }
         // wait for the unclassified sends to complete
         unsigned n_unclassified_send_req = unclassified_send_requests.size();
         if (n_unclassified_send_req > 0)
         {
           MPI_Waitall(n_unclassified_send_req,
                       &unclassified_send_requests[0],
                       MPI_STATUS_IGNORE);
         }
         delete[] unclassified_contributions_send;
         delete[] unclassified_indices_send;
         delete[] n_unclassified_send;
         // wait for the classified sends to complete
         unsigned n_classified_send_req = classified_send_requests.size();
         if (n_classified_send_req > 0)
         {
           MPI_Waitall(n_classified_send_req,
                       &classified_send_requests[0],
                       MPI_STATUS_IGNORE);
         }
         delete[] classified_indices_send;
         delete[] classified_contributions_send;
         delete[] n_classified_recv;
         delete[] n_classified_send;
         // Copy the values back where they belong
         if (block_index == 0)
         {
           v_values = v_or_p_values;
         }
         else if (block_index == 1)
         {
           p_values = v_or_p_values;
         }
       }
 #endif
     }
     // or if the problem is not distributed
     else
     {
       // find number of elements
       unsigned n_el = Navier_stokes_mesh_pt->nelement();
       // Fp needs pressure and velocity mass matrices
       unsigned which_one = 0;
       if (Use_LSC) which_one = 2;
       // get the contribution for each element
       for (unsigned e = 0; e < n_el; e++)
       {
         // Get element
         GeneralisedElement* el_pt = Navier_stokes_mesh_pt->element_pt(e);
         // find number of degrees of freedom in the element
         // (this is slightly too big because it includes the
         // pressure dofs but this doesn't matter)
         unsigned el_dof = el_pt->ndof();
         // allocate local storage for the element's contribution to the
         // pressure and velocity mass matrix diagonal
         Vector<double> el_vmm_diagonal(el_dof, 0.0);
         Vector<double> el_pmm_diagonal(el_dof, 0.0);
         NavierStokesElementWithDiagonalMassMatrices* cast_el_pt = 0;
         cast_el_pt =
           dynamic_cast<NavierStokesElementWithDiagonalMassMatrices*>(el_pt);
         if (cast_el_pt != 0)
         {
           cast_el_pt->get_pressure_and_velocity_mass_matrix_diagonal(
             el_pmm_diagonal, el_vmm_diagonal, which_one);
         }
         else
         {
 #ifdef PARANOID
           std::ostringstream error_message;
           error_message
             << "Navier-Stokes mesh contains element that is not of type \n"
             << "NavierStokesElementWithDiagonalMassMatrices. \n"
             << "The element is in fact of type " << typeid(*el_pt).name()
             << "\nWe'll assume that it does not make a used contribution \n"
             << "to the inverse diagonal mass matrix used in the "
                "preconditioner\n"
             << "and (to avoid divisions by zero) fill in dummy unit entries.\n"
             << "[This case currently arises with flux control problems\n"
             << "where for simplicity the NetFluxControlElement has been added "
                "\n"
             << "to the Navier Stokes mesh -- this should probably be changed "
                "at\n"
             << "some point -- if you get this warning in any other context\n"
             << "you should check your code very carefully]\n";
           OomphLibWarning(error_message.str(),
                           "NavierStokesSchurComplementPreconditioner::assemble_"
                           "inv_press_and_veloc_mass_matrix_diagonal()",
                           OOMPH_EXCEPTION_LOCATION);
 #endif
           // Fill in dummy entries to stop division by zero below
           for (unsigned j = 0; j < el_dof; j++)
           {
             el_vmm_diagonal[j] = 1.0;
             el_pmm_diagonal[j] = 1.0;
           }
         }
         // Get the contribution for each dof
         for (unsigned i = 0; i < el_dof; i++)
         {
           // Get the equation number
           unsigned eqn_number = el_pt->eqn_number(i);
           // Get the velocity dofs
           if (this->block_number(eqn_number) == 0)
           {
             // get the index in the block
             unsigned index = this->index_in_block(eqn_number);
             // if it is required on this processor
             if ((index >= v_first_row) &&
                 (index < (v_first_row + v_nrow_local)))
             {
               v_values[index - v_first_row] += el_vmm_diagonal[i];
             }
           }
           // Get the pressure dofs
           else if (this->block_number(eqn_number) == 1)
           {
             if (!Use_LSC)
             {
               // get the index in the block
               unsigned index = this->index_in_block(eqn_number);
               // if it is required on this processor
               if ((index >= p_first_row) &&
                   (index < (p_first_row + p_nrow_local)))
               {
                 p_values[index - p_first_row] += el_pmm_diagonal[i];
               }
             }
           }
         }
       }
     }
     // Create column index and row start for velocity mass matrix
     int* v_column_index = new int[v_nrow_local];
     int* v_row_start = new int[v_nrow_local + 1];
     for (unsigned i = 0; i < v_nrow_local; i++)
     {
 #ifdef PARANOID
       if (v_values[i] == 0.0)
       {
         std::ostringstream error_message;
         error_message << "Zero entry in diagonal of velocity mass matrix\n"
                       << "Index: " << i << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       v_values[i] = 1.0 / v_values[i];
       v_column_index[i] = v_first_row + i;
       v_row_start[i] = i;
     }
     v_row_start[v_nrow_local] = v_nrow_local;
     // Build the velocity mass matrix
     inv_v_mass_pt = new CRDoubleMatrix(this->block_distribution_pt(0));
     inv_v_mass_pt->build_without_copy(
       v_nrow, v_nrow_local, v_values, v_column_index, v_row_start);
     // Create pressure mass matrix
     if (!Use_LSC)
     {
       // Create column index and row start for pressure mass matrix
       int* p_column_index = new int[p_nrow_local];
       int* p_row_start = new int[p_nrow_local + 1];
       for (unsigned i = 0; i < p_nrow_local; i++)
       {
 #ifdef PARANOID
         if (p_values[i] == 0.0)
         {
           std::ostringstream error_message;
           error_message << "Zero entry in diagonal of pressure mass matrix\n"
                         << "Index: " << i << std::endl;
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         p_values[i] = 1.0 / p_values[i];
         p_column_index[i] = p_first_row + i;
         p_row_start[i] = i;
       }
       p_row_start[p_nrow_local] = p_nrow_local;
       // Build the pressure mass matrix
       inv_p_mass_pt = new CRDoubleMatrix(this->block_distribution_pt(1));
       inv_p_mass_pt->build_without_copy(
         p_nrow, p_nrow_local, p_values, p_column_index, p_row_start);
     }
   }
References oomph::BlockPreconditioner< CRDoubleMatrix >::block_distribution_pt(), oomph::BlockPreconditioner< CRDoubleMatrix >::block_number(), oomph::CRDoubleMatrix::build_without_copy(), oomph::Preconditioner::comm_pt(), oomph::DistributableLinearAlgebraObject::distributed(), e(), oomph::Mesh::element_pt(), oomph::GeneralisedElement::eqn_number(), oomph::LinearAlgebraDistribution::first_row(), oomph::NavierStokesElementWithDiagonalMassMatrices::get_pressure_and_velocity_mass_matrix_diagonal(), i, oomph::BlockPreconditioner< CRDoubleMatrix >::index_in_block(), int(), j, oomph::BlockPreconditioner< CRDoubleMatrix >::master_distribution_pt(), oomph::OomphCommunicator::my_rank(), Navier_stokes_mesh_pt, oomph::GeneralisedElement::ndof(), oomph::Mesh::nelement(), oomph::OomphCommunicator::nproc(), oomph::LinearAlgebraDistribution::nrow(), oomph::LinearAlgebraDistribution::nrow_local(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, p, problem_pt(), Use_LSC, and v.
clean_up_memory()
void oomph::NavierStokesSchurComplementPreconditioner::clean_up_memory () virtual
Helper function to delete preconditioner data.
Reimplemented from oomph::Preconditioner.
   {
     if (Preconditioner_has_been_setup)
     {
       // delete matvecs
       delete Bt_mat_vec_pt;
       Bt_mat_vec_pt = 0;
       delete F_mat_vec_pt;
       F_mat_vec_pt = 0;
       delete QBt_mat_vec_pt;
       QBt_mat_vec_pt = 0;
       delete E_mat_vec_pt;
       E_mat_vec_pt = 0;
       // delete stuff from velocity solve
       if (Using_default_f_preconditioner)
       {
         delete F_preconditioner_pt;
         F_preconditioner_pt = 0;
       }
       // delete stuff from Schur complement approx
       if (Using_default_p_preconditioner)
       {
         delete P_preconditioner_pt;
         P_preconditioner_pt = 0;
       }
     }
   }
References Bt_mat_vec_pt, E_mat_vec_pt, F_mat_vec_pt, F_preconditioner_pt, P_preconditioner_pt, Preconditioner_has_been_setup, QBt_mat_vec_pt, Using_default_f_preconditioner, and Using_default_p_preconditioner.
Referenced by oomph::PseudoElasticFSIPreconditioner::clean_up_memory(), and ~NavierStokesSchurComplementPreconditioner().
disable_accept_non_NavierStokesElementWithDiagonalMassMatrices_elements()
void oomph::NavierStokesSchurComplementPreconditioner::disable_accept_non_NavierStokesElementWithDiagonalMassMatrices_elements () inline
Do not accept presence of elements that are not of type NavierStokesElementWithDiagonalMassMatrices without issuing a warning.
     {
       Accept_non_NavierStokesElementWithDiagonalMassMatrices_elements = false;
     }
References Accept_non_NavierStokesElementWithDiagonalMassMatrices_elements.
disable_doc_time()
void oomph::NavierStokesSchurComplementPreconditioner::disable_doc_time () inline
Disable documentation of time.
     {
       Doc_time = false;
     }
References Doc_time.
disable_robin_for_fp()
void oomph::NavierStokesSchurComplementPreconditioner::disable_robin_for_fp () inline
Don't use Robin BC elements for the Fp preconditioenr.
     {
       Use_robin_for_fp = false;
     }
References Use_robin_for_fp.
Referenced by FpTestProblem::FpTestProblem().
enable_accept_non_NavierStokesElementWithDiagonalMassMatrices_elements()
void oomph::NavierStokesSchurComplementPreconditioner::enable_accept_non_NavierStokesElementWithDiagonalMassMatrices_elements () inline
Accept presence of elements that are not of type NavierStokesElementWithDiagonalMassMatrices without issuing a warning.
     {
       Accept_non_NavierStokesElementWithDiagonalMassMatrices_elements = true;
     }
References Accept_non_NavierStokesElementWithDiagonalMassMatrices_elements.
enable_doc_time()
void oomph::NavierStokesSchurComplementPreconditioner::enable_doc_time () inline
Enable documentation of time.
     {
       Doc_time = true;
     }
References Doc_time.
Referenced by main().
enable_robin_for_fp()
void oomph::NavierStokesSchurComplementPreconditioner::enable_robin_for_fp () inline
Use Robin BC elements for the Fp preconditioner.
     {
       Use_robin_for_fp = true;
     }
References Use_robin_for_fp.
Referenced by FpTestProblem::FpTestProblem().
get_pressure_advection_diffusion_matrix()
void oomph::NavierStokesSchurComplementPreconditioner::get_pressure_advection_diffusion_matrix (CRDoubleMatrix & fp_matrix) inline
Get the pressure advection diffusion matrix.
     {
       // Pin all non-pressure dofs
       pin_all_non_pressure_dofs();
       // Get the spatial dimension
       unsigned ndim = Navier_stokes_mesh_pt->finite_element_pt(0)->dim();
       // Backup assembly handler and set new one
       AssemblyHandler* backed_up_assembly_handler_pt =
         problem_pt()->assembly_handler_pt();
       problem_pt()->assembly_handler_pt() =
         new FpPreconditionerAssemblyHandler(ndim);
       // Backup submeshes (if any)
       unsigned n_sub_mesh = problem_pt()->nsub_mesh();
       Vector<Mesh*> backed_up_sub_mesh_pt(n_sub_mesh);
       for (unsigned i = 0; i < n_sub_mesh; i++)
       {
         backed_up_sub_mesh_pt[i] = problem_pt()->mesh_pt(i);
       }
       // Flush sub-meshes but don't call rebuild_global_mesh()
       // so we can simply re-instate the sub-meshes below.
       problem_pt()->flush_sub_meshes();
       // Backup the problem's own mesh pointer
       Mesh* backed_up_mesh_pt = problem_pt()->mesh_pt();
       problem_pt()->mesh_pt() = Navier_stokes_mesh_pt;
 #ifdef OOMPH_HAS_MPI
       // Backup the start and end elements for the distributed
       // assembly process
       Vector<unsigned> backed_up_first_el_for_assembly;
       Vector<unsigned> backed_up_last_el_for_assembly;
       problem_pt()->get_first_and_last_element_for_assembly(
         backed_up_first_el_for_assembly, backed_up_last_el_for_assembly);
       // Now re-assign
       problem_pt()->set_default_first_and_last_element_for_assembly();
 #endif
       // Identify pinned pressure dof
       int pinned_pressure_eqn = -2;
       if (Pin_first_pressure_dof_in_press_adv_diff)
       {
         // Loop over all Navier Stokes elements to find first non-pinned
         // pressure dof
         unsigned nel = Navier_stokes_mesh_pt->nelement();
         for (unsigned e = 0; e < nel; e++)
         {
           TemplateFreeNavierStokesEquationsBase* bulk_elem_pt =
             dynamic_cast<TemplateFreeNavierStokesEquationsBase*>(
               Navier_stokes_mesh_pt->element_pt(e));
           int local_eqn = bulk_elem_pt->p_local_eqn(0);
           if (local_eqn >= 0)
           {
             pinned_pressure_eqn = bulk_elem_pt->eqn_number(local_eqn);
             break;
           }
         }
 #ifdef OOMPH_HAS_MPI
         if (problem_pt()->distributed())
         {
           int pinned_pressure_eqn_local = pinned_pressure_eqn;
           int pinned_pressure_eqn_global = pinned_pressure_eqn;
           MPI_Allreduce(&pinned_pressure_eqn_local,
                         &pinned_pressure_eqn_global,
                         1,
                         MPI_INT,
                         MPI_MIN,
                         this->comm_pt()->mpi_comm());
           pinned_pressure_eqn = pinned_pressure_eqn_global;
         }
 #endif
       }
       // Loop over all Navier Stokes elements
       unsigned nel = Navier_stokes_mesh_pt->nelement();
       for (unsigned e = 0; e < nel; e++)
       {
         TemplateFreeNavierStokesEquationsBase* bulk_elem_pt =
           dynamic_cast<TemplateFreeNavierStokesEquationsBase*>(
             Navier_stokes_mesh_pt->element_pt(e));
         // Set pinned pressure equation
         bulk_elem_pt->pinned_fp_pressure_eqn() = pinned_pressure_eqn;
       }
       // Attach Robin BC elements
       unsigned nbound = Navier_stokes_mesh_pt->nboundary();
       if (Use_robin_for_fp)
       {
         // Loop over all boundaries of Navier Stokes mesh
         for (unsigned b = 0; b < nbound; b++)
         {
           // How many bulk elements are adjacent to boundary b?
           unsigned n_element = Navier_stokes_mesh_pt->nboundary_element(b);
           // Loop over the bulk elements adjacent to boundary b?
           for (unsigned e = 0; e < n_element; e++)
           {
             TemplateFreeNavierStokesEquationsBase* bulk_elem_pt =
               dynamic_cast<TemplateFreeNavierStokesEquationsBase*>(
                 Navier_stokes_mesh_pt->boundary_element_pt(b, e));
             // What is the index of the face of the bulk element e on bondary b
             int face_index =
               Navier_stokes_mesh_pt->face_index_at_boundary(b, e);
             // Build face element
             bulk_elem_pt->build_fp_press_adv_diff_robin_bc_element(face_index);
           } // end of loop over bulk elements adjacent to boundary b
         }
       }
       // Get "Jacobian" of the modified system
       DoubleVector dummy_residuals;
       problem_pt()->get_jacobian(dummy_residuals, fp_matrix);
       // Kill Robin BC elements
       if (Use_robin_for_fp)
       {
         // Loop over all boundaries of Navier Stokes mesh
         for (unsigned b = 0; b < nbound; b++)
         {
           // How many bulk elements are adjacent to boundary b?
           unsigned n_element = Navier_stokes_mesh_pt->nboundary_element(b);
           // Loop over the bulk elements adjacent to boundary b?
           for (unsigned e = 0; e < n_element; e++)
           {
             TemplateFreeNavierStokesEquationsBase* bulk_elem_pt =
               dynamic_cast<TemplateFreeNavierStokesEquationsBase*>(
                 Navier_stokes_mesh_pt->boundary_element_pt(b, e));
             // Kill associated Robin elements
             bulk_elem_pt->delete_pressure_advection_diffusion_robin_elements();
           } // end of loop over bulk elements adjacent to boundary b
         }
       }
       // Reset pin status
       reset_pin_status();
 #ifdef OOMPH_HAS_MPI
       // Reset start and end elements for the distributed
       // assembly process
       problem_pt()->set_first_and_last_element_for_assembly(
         backed_up_first_el_for_assembly, backed_up_last_el_for_assembly);
 #endif
       // Cleanup and reset assembly handler
       delete problem_pt()->assembly_handler_pt();
       problem_pt()->assembly_handler_pt() = backed_up_assembly_handler_pt;
       // Re-instate submeshes. (No need to call rebuild_global_mesh()
       // as it was never unbuilt).
       for (unsigned i = 0; i < n_sub_mesh; i++)
       {
         problem_pt()->add_sub_mesh(backed_up_sub_mesh_pt[i]);
       }
       // Reset the problem's mesh pointer
       problem_pt()->mesh_pt() = backed_up_mesh_pt;
     }
References oomph::Problem::add_sub_mesh(), oomph::Problem::assembly_handler_pt(), b, oomph::Mesh::boundary_element_pt(), oomph::TemplateFreeNavierStokesEquationsBase::build_fp_press_adv_diff_robin_bc_element(), oomph::Preconditioner::comm_pt(), oomph::TemplateFreeNavierStokesEquationsBase::delete_pressure_advection_diffusion_robin_elements(), oomph::FiniteElement::dim(), oomph::Problem::distributed(), e(), oomph::Mesh::element_pt(), oomph::GeneralisedElement::eqn_number(), oomph::Mesh::face_index_at_boundary(), oomph::Mesh::finite_element_pt(), oomph::Problem::flush_sub_meshes(), oomph::Problem::get_jacobian(), i, oomph::Problem::mesh_pt(), Navier_stokes_mesh_pt, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::Mesh::nelement(), oomph::Problem::nsub_mesh(), oomph::TemplateFreeNavierStokesEquationsBase::p_local_eqn(), pin_all_non_pressure_dofs(), Pin_first_pressure_dof_in_press_adv_diff, oomph::TemplateFreeNavierStokesEquationsBase::pinned_fp_pressure_eqn(), problem_pt(), reset_pin_status(), and Use_robin_for_fp.
pin_all_non_pressure_dofs()
void oomph::NavierStokesSchurComplementPreconditioner::pin_all_non_pressure_dofs () inline
Pin all non-pressure dofs.
     {
       // Backup pin status and then pin all non-pressure degrees of freedom
       unsigned nelem = Navier_stokes_mesh_pt->nelement();
       for (unsigned e = 0; e < nelem; e++)
       {
         // Get pointer to the bulk element that is adjacent to boundary b
         TemplateFreeNavierStokesEquationsBase* el_pt =
           dynamic_cast<TemplateFreeNavierStokesEquationsBase*>(
             Navier_stokes_mesh_pt->element_pt(e));
         // Pin
         el_pt->pin_all_non_pressure_dofs(Eqn_number_backup);
       }
     }
References e(), oomph::Mesh::element_pt(), Eqn_number_backup, Navier_stokes_mesh_pt, oomph::Mesh::nelement(), and oomph::TemplateFreeNavierStokesEquationsBase::pin_all_non_pressure_dofs().
Referenced by get_pressure_advection_diffusion_matrix().
pin_first_pressure_dof_in_press_adv_diff()
void oomph::NavierStokesSchurComplementPreconditioner::pin_first_pressure_dof_in_press_adv_diff () inline
Set boolean indicating that we want to pin first pressure dof in Navier Stokes mesh when assembling the pressure advection diffusion system for Fp preconditoner – needed at zero Reynolds number for non-enclosed flows but seems harmless in any case
     {
       Pin_first_pressure_dof_in_press_adv_diff = true;
     }
References Pin_first_pressure_dof_in_press_adv_diff.
preconditioner_solve()
void oomph::NavierStokesSchurComplementPreconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) virtual
Apply preconditioner to Vector r.
Apply preconditioner to r.
Implements oomph::Preconditioner.
  {
 #ifdef PARANOID
   if (Preconditioner_has_been_setup==false)
    {
     std::ostringstream error_message;
     error_message << "setup must be called before using preconditioner_solve";
     throw OomphLibError(
      error_message.str(),
      OOMPH_CURRENT_FUNCTION,
      OOMPH_EXCEPTION_LOCATION);
    }
   if (z.built())
    {
     if (z.nrow() != r.nrow())
      {
       std::ostringstream error_message;
       error_message << "The vectors z and r must have the same number of "
                     << "of global rows";
       throw OomphLibError(
        error_message.str(),
        OOMPH_CURRENT_FUNCTION,
        OOMPH_EXCEPTION_LOCATION);
      }
    }
 #endif
   // if z is not setup then give it the same distribution
   if (!z.distribution_pt()->built())
    {
     z.build(r.distribution_pt(),0.0);
    }
   // Step 1 - apply approximate Schur inverse to pressure unknowns (block 1)
   // -----------------------------------------------------------------------
   // Working vectors
   DoubleVector temp_vec;
   DoubleVector another_temp_vec;
   DoubleVector yet_another_temp_vec;
   // Copy pressure values from residual vector to temp_vec:
   // Loop over all entries in the global vector (this one
   // includes velocity and pressure dofs in some random fashion)
   this->get_block_vector(1,r,temp_vec);
   // NOTE: The vector temp_vec now contains the vector r_p.
   // LSC version
   if (Use_LSC)
    {
     // Solve first pressure Poisson system
 #ifdef PARANOID
     // check a solver has been set
     if (P_preconditioner_pt==0)
      {
       std::ostringstream error_message;
       error_message << "P_preconditioner_pt has not been set.";
       throw OomphLibError(
        error_message.str(),
        OOMPH_CURRENT_FUNCTION,
        OOMPH_EXCEPTION_LOCATION);
      }
 #endif
     // use some Preconditioner's preconditioner_solve function
     P_preconditioner_pt->preconditioner_solve(temp_vec, another_temp_vec);
     // NOTE: The vector another_temp_vec now contains the vector P^{-1} r_p
     // Multiply another_temp_vec by matrix E and stick the result into temp_vec
     temp_vec.clear();
     QBt_mat_vec_pt->multiply(another_temp_vec, temp_vec);
     another_temp_vec.clear();
     F_mat_vec_pt->multiply(temp_vec,another_temp_vec);
     temp_vec.clear();
     QBt_mat_vec_pt->multiply_transpose(another_temp_vec, temp_vec);
     // NOTE: The vector temp_vec now contains E P^{-1} r_p
     // Solve second pressure Poisson system using preconditioner_solve
     another_temp_vec.clear();
     P_preconditioner_pt->preconditioner_solve(temp_vec, another_temp_vec);
     // NOTE: The vector another_temp_vec now contains z_p = P^{-1} E P^{-1} r_p
     //       as required (apart from the sign which we'll fix in the
     //       next step.
    }
   // Fp version
   else
    {
     // Multiply temp_vec by matrix E and stick the result into
     // yet_another_temp_vec
     E_mat_vec_pt->multiply(temp_vec,yet_another_temp_vec);
     // NOTE: The vector yet_another_temp_vec now contains Fp Qp^{-1} r_p
     // Solve pressure Poisson system
 #ifdef PARANOID
     // check a solver has been set
     if (P_preconditioner_pt==0)
      {
       std::ostringstream error_message;
       error_message << "P_preconditioner_pt has not been set.";
       throw OomphLibError(
        error_message.str(),
        OOMPH_CURRENT_FUNCTION,
        OOMPH_EXCEPTION_LOCATION);
      }
 #endif
     // Solve second pressure Poisson system using preconditioner_solve
     another_temp_vec.clear();
     P_preconditioner_pt->preconditioner_solve(yet_another_temp_vec,
                                               another_temp_vec);
     // NOTE: The vector another_temp_vec now contains
     //       z_p = P^{-1} Fp Qp^{-1} r_p
     //       as required (apart from the sign which we'll fix in the
     //       next step.
    }
   // Now copy another_temp_vec (i.e. z_p) back into the global vector z.
   // Loop over all entries in the global results vector z:
   temp_vec.build(another_temp_vec.distribution_pt(),0.0);
   temp_vec -= another_temp_vec;
   return_block_vector(1,temp_vec,z);
   // Step 2 - apply preconditioner to velocity unknowns (block 0)
   // ------------------------------------------------------------
   // Recall that another_temp_vec (computed above) contains the
   // negative of the solution of the Schur complement systen, -z_p.
   // Multiply by G (stored in Block_matrix_pt(0,1) and store
   // result in temp_vec (vector resizes itself).
   temp_vec.clear();
   Bt_mat_vec_pt->multiply(another_temp_vec, temp_vec);
   // NOTE: temp_vec now contains -G z_p
   // The vector another_temp_vec is no longer needed -- re-use it to store
   // velocity quantities:
   another_temp_vec.clear();
   // Loop over all enries in the global vector and find the
   // entries associated with the velocities:
   get_block_vector(0,r,another_temp_vec);
   another_temp_vec += temp_vec;
   // NOTE:  The vector another_temp_vec now contains r_u - G z_p
   // Solve momentum system
 #ifdef PARANOID
   // check a solver has been set
   if (F_preconditioner_pt==0)
    {
     std::ostringstream error_message;
     error_message << "F_preconditioner_pt has not been set.";
     throw OomphLibError(
      error_message.str(),
      OOMPH_CURRENT_FUNCTION,
      OOMPH_EXCEPTION_LOCATION);
    }
 #endif
   // use some Preconditioner's preconditioner solve
   // and return
   if (F_preconditioner_is_block_preconditioner)
    {
     return_block_vector(0,another_temp_vec,z);
     F_preconditioner_pt->preconditioner_solve(z,z);
    }
   else
    {
     F_preconditioner_pt->preconditioner_solve(another_temp_vec, temp_vec);
     return_block_vector(0,temp_vec,z);
    }
  }
References oomph::DoubleVector::build(), oomph::DoubleVector::built(), oomph::LinearAlgebraDistribution::built(), oomph::DoubleVector::clear(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::DistributableLinearAlgebraObject::nrow(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and UniformPSDSelfTest::r.
Referenced by oomph::FSIPreconditioner::preconditioner_solve(), and oomph::PseudoElasticFSIPreconditioner::preconditioner_solve().
problem_pt()
Problem* oomph::NavierStokesSchurComplementPreconditioner::problem_pt () const inline
     {
 #ifdef PARANOID
       if (Problem_pt == 0)
       {
         std::ostringstream error_msg;
         error_msg << "Problem pointer is null, did you set it yet?";
         throw OomphLibError(
           error_msg.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return Problem_pt;
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and Problem_pt.
Referenced by assemble_inv_press_and_veloc_mass_matrix_diagonal(), get_pressure_advection_diffusion_matrix(), and set_problem_pt().
reset_pin_status()
void oomph::NavierStokesSchurComplementPreconditioner::reset_pin_status () inline
Reset pin status of all values.
     {
       // Reset pin status for nodes
       unsigned nnod = Navier_stokes_mesh_pt->nnode();
       for (unsigned j = 0; j < nnod; j++)
       {
         Node* nod_pt = Navier_stokes_mesh_pt->node_pt(j);
         unsigned nval = nod_pt->nvalue();
         for (unsigned i = 0; i < nval; i++)
         {
           nod_pt->eqn_number(i) = Eqn_number_backup[nod_pt][i];
         }
         // If it's a solid node deal with its positional data too
         SolidNode* solid_nod_pt = dynamic_cast<SolidNode*>(nod_pt);
         if (solid_nod_pt != 0)
         {
           Data* solid_posn_data_pt = solid_nod_pt->variable_position_pt();
           unsigned nval = solid_posn_data_pt->nvalue();
           for (unsigned i = 0; i < nval; i++)
           {
             solid_posn_data_pt->eqn_number(i) =
               Eqn_number_backup[solid_posn_data_pt][i];
           }
         }
       }
       // ... and internal data
       unsigned nelem = Navier_stokes_mesh_pt->nelement();
       for (unsigned e = 0; e < nelem; e++)
       {
         // Pointer to element
         GeneralisedElement* el_pt = Navier_stokes_mesh_pt->element_pt(e);
         // Pin/unpin internal data
         unsigned nint = el_pt->ninternal_data();
         for (unsigned j = 0; j < nint; j++)
         {
           Data* data_pt = el_pt->internal_data_pt(j);
           unsigned nvalue = data_pt->nvalue();
           for (unsigned i = 0; i < nvalue; i++)
           {
             data_pt->eqn_number(i) = Eqn_number_backup[data_pt][i];
           }
         }
       }
       // Free up storage
       Eqn_number_backup.clear();
     }
References e(), oomph::Mesh::element_pt(), oomph::Data::eqn_number(), Eqn_number_backup, i, oomph::GeneralisedElement::internal_data_pt(), j, Navier_stokes_mesh_pt, oomph::Mesh::nelement(), oomph::GeneralisedElement::ninternal_data(), oomph::Mesh::nnode(), oomph::Mesh::node_pt(), oomph::Data::nvalue(), and oomph::SolidNode::variable_position_pt().
Referenced by get_pressure_advection_diffusion_matrix().
set_f_preconditioner()
void oomph::NavierStokesSchurComplementPreconditioner::set_f_preconditioner (Preconditioner * new_f_preconditioner_pt) inline
Function to set a new momentum matrix preconditioner (inexact solver)
     {
       // If the default preconditioner has been used
       // clean it up now...
       if (Using_default_f_preconditioner)
       {
         delete F_preconditioner_pt;
       }
       F_preconditioner_pt = new_f_preconditioner_pt;
       Using_default_f_preconditioner = false;
     }
References F_preconditioner_pt, and Using_default_f_preconditioner.
Referenced by FpTestProblem::FpTestProblem(), main(), FSIChannelWithLeafletProblem< ELEMENT >::set_iterative_solver(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::set_pseudo_elastic_fsi_solver(), set_pseudo_elastic_fsi_solver(), TiltedCavityProblem< ELEMENT >::TiltedCavityProblem(), and TorusProblem< ELEMENT >::TorusProblem().
set_f_superlu_preconditioner()
void oomph::NavierStokesSchurComplementPreconditioner::set_f_superlu_preconditioner () inline
Function to (re-)set momentum matrix preconditioner (inexact solver) to SuperLU
     {
       if (!Using_default_f_preconditioner)
       {
         F_preconditioner_pt = new SuperLUPreconditioner;
         Using_default_f_preconditioner = true;
       }
     }
References F_preconditioner_pt, and Using_default_f_preconditioner.
set_navier_stokes_mesh()
void oomph::NavierStokesSchurComplementPreconditioner::set_navier_stokes_mesh (Mesh * mesh_pt, const bool & allow_multiple_element_type_in_navier_stokes_mesh = false) inline
Specify the mesh containing the block-preconditionable Navier-Stokes elements. The optional argument indicates if there are multiple types of elements in the same mesh.
     {
       // Store the mesh pointer.
       Navier_stokes_mesh_pt = mesh_pt;
       // Are there multiple element types in this mesh?
       Allow_multiple_element_type_in_navier_stokes_mesh =
         allow_multiple_element_type_in_navier_stokes_mesh;
     }
References Allow_multiple_element_type_in_navier_stokes_mesh, oomph::BlockPreconditioner< CRDoubleMatrix >::mesh_pt(), and Navier_stokes_mesh_pt.
Referenced by FpTestProblem::FpTestProblem(), main(), oomph::FSIPreconditioner::setup(), oomph::PseudoElasticFSIPreconditioner::setup(), TiltedCavityProblem< ELEMENT >::TiltedCavityProblem(), and TorusProblem< ELEMENT >::TorusProblem().
set_p_preconditioner()
void oomph::NavierStokesSchurComplementPreconditioner::set_p_preconditioner (Preconditioner * new_p_preconditioner_pt) inline
Function to set a new pressure matrix preconditioner (inexact solver)
     {
       // If the default preconditioner has been used
       // clean it up now...
       if (Using_default_p_preconditioner)
       {
         delete P_preconditioner_pt;
       }
       P_preconditioner_pt = new_p_preconditioner_pt;
       Using_default_p_preconditioner = false;
     }
References P_preconditioner_pt, and Using_default_p_preconditioner.
Referenced by FpTestProblem::FpTestProblem(), main(), FSIChannelWithLeafletProblem< ELEMENT >::set_iterative_solver(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::set_pseudo_elastic_fsi_solver(), set_pseudo_elastic_fsi_solver(), TiltedCavityProblem< ELEMENT >::TiltedCavityProblem(), and TorusProblem< ELEMENT >::TorusProblem().
set_p_superlu_preconditioner()
void oomph::NavierStokesSchurComplementPreconditioner::set_p_superlu_preconditioner () inline
Function to (re-)set pressure matrix preconditioner (inexact solver) to SuperLU
     {
       if (!Using_default_p_preconditioner)
       {
         P_preconditioner_pt = new SuperLUPreconditioner;
         Using_default_p_preconditioner = true;
       }
     }
References P_preconditioner_pt, and Using_default_p_preconditioner.
set_problem_pt()
void oomph::NavierStokesSchurComplementPreconditioner::set_problem_pt (Problem * problem_pt) inline
Broken assignment operator.
Set the problem pointer (non-const pointer, the problem WILL be changed) for use in get_pressure_advection_diffusion_matrix().
     {
       Problem_pt = problem_pt;
     }
References problem_pt(), and Problem_pt.
setup() [1/4]
void oomph::NavierStokesSchurComplementPreconditioner::setup () virtual
Setup the preconditioner.
Setup the least-squares commutator Navier Stokes preconditioner. This extracts blocks corresponding to the velocity and pressure unknowns, creates the matrices actually needed in the application of the preconditioner and deletes what can be deleted... Note that this preconditioner needs a CRDoubleMatrix.
///////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////// Setup the least-squares commutator Navier Stokes preconditioner. This extracts blocks corresponding to the velocity and pressure unknowns, creates the matrices actually needed in the application of the preconditioner and deletes what can be deleted... Note that this preconditioner needs a CRDoubleMatrix.
Implements oomph::Preconditioner.
  {
   //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   // NOTE: In the interest of minimising memory usage, several containers
   //       are recycled, therefore their content/meaning changes
   //       throughout this function. The code is carefully annotated
   //       but you'll have to read it line by line!
   //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   // make sure any old data is deleted
   clean_up_memory(); // hierher
 #ifdef PARANOID
   // paranoid check that the navier stokes mesh pt has been set
   if (Navier_stokes_mesh_pt == 0)
    {
     std::ostringstream error_message;
     error_message << "The navier stokes elements mesh pointer must be set.\n"
                   << "Use method set_navier_stokes_mesh(...)";
     throw OomphLibError(error_message.str(),
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
    }
 #endif
   // set the mesh
   this->set_nmesh(1);
   this->set_mesh(0,Navier_stokes_mesh_pt);
   // Get blocks
   // ----------
   // In comes the current Jacobian. Recast it to a CR double matrix;
   // shout if that can't be done.
   CRDoubleMatrix* cr_matrix_pt = dynamic_cast<CRDoubleMatrix*>(matrix_pt());
 #ifdef PARANOID
   if (cr_matrix_pt==0)
    {
     std::ostringstream error_message;
     error_message
      << "NavierStokesSchurComplementPreconditioner only works with "
      << "CRDoubleMatrix matrices" << std::endl;
     throw OomphLibError(error_message.str(),
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
    }
 #endif
   // Set up block look up schemes
   //-----------------------------
   // this preconditioner has two types of block:
   // type 0: velocity - corresponding to DOFs 0 to n-2
   // type 1: pressure - corresponding to DOF n-1
   unsigned ndof_types = 0;
   if (this->is_subsidiary_block_preconditioner())
    {
     ndof_types = this->ndof_types();
    }
   else
    {
     ndof_types = this->ndof_types_in_mesh(0);
    }
   // hierher
   Vector<unsigned> dof_to_block_map(ndof_types);
   dof_to_block_map[ndof_types-1]=1;
   this->block_setup(dof_to_block_map);
   // Get B (the divergence block)
   CRDoubleMatrix* b_pt = 0;
   this->get_block(1,0,b_pt);
   // // get the inverse velocity and pressure mass matrices
   // CRDoubleMatrix* inv_v_mass_pt = 0;
   // CRDoubleMatrix* inv_p_mass_pt = 0;
   // double ivmm_assembly_start_t = TimingHelpers::timer();
   // if (Use_LSC)
   //  {
   //   // We only need the velocity mass matrix
   //   bool do_both=false;
   //   assemble_inv_press_and_veloc_mass_matrix_diagonal(inv_p_mass_pt,
   //                                                     inv_v_mass_pt,
   //                                                     do_both);
   //  }
   // else
   //  {
   //   // We only need both mass matrices
   //   bool do_both=true;
   //   assemble_inv_press_and_veloc_mass_matrix_diagonal(inv_p_mass_pt,
   //                                                     inv_v_mass_pt,
   //                                                     do_both);
   //  }
   // Get gradient matrix Bt
   CRDoubleMatrix* bt_pt = 0;
   this->get_block(0,1,bt_pt);
   // Multiply inverse velocity mass matrix by gradient matrix B^T
   double t_QBt_matrix_start = TimingHelpers::timer();
   CRDoubleMatrix* qbt_pt = new CRDoubleMatrix;
   inv_v_mass_pt->multiply(*bt_pt, *qbt_pt);
   delete bt_pt;
   // Store product in bt_pt
   bt_pt = qbt_pt;
   delete inv_v_mass_pt;
   // Multiply B from left by divergence matrix B and store result in
   // pressure Poisson matrix.
   b_pt->multiply(*bt_pt, *p_matrix_pt);
   // Kill divergence matrix because we don't need it any more
   delete b_pt;
   // Build the matvec operator for QBt
   QBt_mat_vec_pt = new MatrixVectorProduct;
   //QBt_mat_vec_pt->setup(bt_pt);
   this->setup_matrix_vector_product(QBt_mat_vec_pt,
                                     bt_pt, 1);
   // Kill gradient matrix B^T (it's been overwritten anyway and
   // needs to be recomputed afresh below)
   delete bt_pt;
   // Get momentum block F
   CRDoubleMatrix* f_pt = 0;
   this->get_block(0,0,f_pt);
   // form the matrix vector product helper
   F_mat_vec_pt = new MatrixVectorProduct;
   //F_mat_vec_pt->setup(f_pt);
   this->setup_matrix_vector_product(F_mat_vec_pt,f_pt,0);
   // if F is a block preconditioner then we can delete the F matrix
   if (F_preconditioner_is_block_preconditioner)
    {
     delete f_pt;
    }
   // Rebuild Bt (remember that we temporarily overwrote
   // it by its product with the inverse velocity mass matrix)
   bt_pt = 0;
   this->get_block(0,1,bt_pt);
   // Form the matrix vector operator for Bt
   Bt_mat_vec_pt = new MatrixVectorProduct;
   //Bt_mat_vec_pt->setup(bt_pt);
   this->setup_matrix_vector_product(Bt_mat_vec_pt,bt_pt,1);
   delete bt_pt;
   // If the P preconditioner has not been setup
   P_preconditioner_pt = new SuperLUPreconditioner;
   P_preconditioner_pt->setup(p_matrix_pt,comm_pt());
   delete p_matrix_pt;
   p_matrix_pt=0;
   // Set up solver for solution of system with momentum matrix
   // ----------------------------------------------------------
   F_preconditioner_pt = new SuperLUPreconditioner;
   Using_default_f_preconditioner = true;
   // if F is a block preconditioner
   double t_f_prec_start = TimingHelpers::timer();
   if (F_preconditioner_is_block_preconditioner)
    {
     unsigned ndof_types = this->ndof_types();
     ndof_types--;
     Vector<unsigned> dof_map(ndof_types);
     for (unsigned i = 0; i < ndof_types; i++)
      {
       dof_map[i] = i;
      }
     F_block_preconditioner_pt->
      turn_into_subsidiary_block_preconditioner(this,dof_map);
     // Set the mesh in the subsidiary preconditioner.
     // RAYRAY This is incorrect. We never set the mesh for a subsidiary
     // block preconditioner. The self test still passes since this part of
     // the if-else condition is never executed.
     F_block_preconditioner_pt->set_nmesh(1);
     F_block_preconditioner_pt->set_mesh(0, Navier_stokes_mesh_pt);
     F_block_preconditioner_pt->setup(matrix_pt(),comm_pt());
    }
   // otherwise F is not a block preconditioner
   else
    {
     F_preconditioner_pt->setup(f_pt,comm_pt());
     delete f_pt;
    }
   double t_f_prec_finish = TimingHelpers::timer();
   if(Doc_time)
    {
     double t_f_prec_time = t_f_prec_finish - t_f_prec_start;
     oomph_info << "F sub-preconditioner setup time [sec]: "
                << t_f_prec_time << "\n";
    }
   // Remember that the preconditioner has been setup so
   // the stored information can be wiped when we
   // come here next...
   Preconditioner_has_been_setup = true;
  }
References oomph::TerminateHelper::clean_up_memory(), i, oomph::CRDoubleMatrix::multiply(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, and oomph::SuperLUPreconditioner::setup().
Referenced by oomph::FSIPreconditioner::setup().
setup() [2/4]
virtual void oomph::Preconditioner::setup virtual
for some reason we have to remind the compiler that there is a setup() function in Preconditioner base class.
Implements oomph::Preconditioner.
setup() [3/4]
void oomph::Preconditioner::setup inline virtual
for some reason we have to remind the compiler that there is a setup() function in Preconditioner base class.
Implements oomph::Preconditioner.
     {
       ObsoleteCode::obsolete();
       setup(matrix_pt);
     }
setup() [4/4]
void oomph::Preconditioner::setup inline virtual
for some reason we have to remind the compiler that there is a setup() function in Preconditioner base class.
Implements oomph::Preconditioner.
     {
       // Store matrix pointer
       set_matrix_pt(matrix_pt);
       // Extract and store communicator pointer
       DistributableLinearAlgebraObject* dist_obj_pt =
         dynamic_cast<DistributableLinearAlgebraObject*>(matrix_pt);
       if (dist_obj_pt != 0)
       {
         set_comm_pt(dist_obj_pt->distribution_pt()->communicator_pt());
       }
       else
       {
         set_comm_pt(0);
       }
       double setup_time_start = TimingHelpers::timer();
       setup();
       double setup_time_finish = TimingHelpers::timer();
       Setup_time = setup_time_finish - setup_time_start;
     }
unpin_first_pressure_dof_in_press_adv_diff()
void oomph::NavierStokesSchurComplementPreconditioner::unpin_first_pressure_dof_in_press_adv_diff () inline
Set boolean indicating that we do not want to pin first pressure dof in Navier Stokes mesh when assembling the pressure advection diffusion system for Fp preconditoner – needed at zero Reynolds number for non-enclosed flows but seems harmless in any case
     {
       Pin_first_pressure_dof_in_press_adv_diff = false;
     }
References Pin_first_pressure_dof_in_press_adv_diff.
use_fp()
void oomph::NavierStokesSchurComplementPreconditioner::use_fp () inline
Use Fp version of the preconditioner.
     {
       Use_LSC = false;
     }
References Use_LSC.
Referenced by FpTestProblem::FpTestProblem().
use_lsc()
void oomph::NavierStokesSchurComplementPreconditioner::use_lsc () inline
Use LSC version of the preconditioner.
     {
       Use_LSC = true;
     }
References Use_LSC.
Referenced by FpTestProblem::FpTestProblem(), and TiltedCavityProblem< ELEMENT >::TiltedCavityProblem().
validate()
template<class ELEMENT > void oomph::NavierStokesSchurComplementPreconditioner::validate (DocInfo & doc_info, Problem * orig_problem_pt) inline
Validate auxiliary pressure advection diffusion problem in 2D
     {
       FpPressureAdvectionDiffusionProblem<ELEMENT> aux_problem(
         Navier_stokes_mesh_pt, orig_problem_pt);
       aux_problem.validate(doc_info);
     }
References Navier_stokes_mesh_pt, and oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::validate().
Member Data Documentation
Accept_non_NavierStokesElementWithDiagonalMassMatrices_elements
bool oomph::NavierStokesSchurComplementPreconditioner::Accept_non_NavierStokesElementWithDiagonalMassMatrices_elements private
Boolean to indicate that presence of elements that are not of type NavierStokesElementWithDiagonalMassMatrices is acceptable (suppresses warning that issued otherwise).
Referenced by disable_accept_non_NavierStokesElementWithDiagonalMassMatrices_elements(), enable_accept_non_NavierStokesElementWithDiagonalMassMatrices_elements(), and NavierStokesSchurComplementPreconditioner().
Allow_multiple_element_type_in_navier_stokes_mesh
bool oomph::NavierStokesSchurComplementPreconditioner::Allow_multiple_element_type_in_navier_stokes_mesh private
Flag to indicate if there are multiple element types in the Navier-Stokes mesh.
Referenced by NavierStokesSchurComplementPreconditioner(), and set_navier_stokes_mesh().
Bt_mat_vec_pt
MatrixVectorProduct* oomph::NavierStokesSchurComplementPreconditioner::Bt_mat_vec_pt private
MatrixVectorProduct operator for Bt.
Referenced by clean_up_memory(), and NavierStokesSchurComplementPreconditioner().
Doc_time
bool oomph::NavierStokesSchurComplementPreconditioner::Doc_time private
Set Doc_time to true for outputting results of timings.
Referenced by disable_doc_time(), enable_doc_time(), and NavierStokesSchurComplementPreconditioner().
E_mat_vec_pt
MatrixVectorProduct* oomph::NavierStokesSchurComplementPreconditioner::E_mat_vec_pt private
MatrixVectorProduct operator for E = Fp Qp^{-1} (only for Fp variant)
Referenced by clean_up_memory(), and NavierStokesSchurComplementPreconditioner().
Eqn_number_backup
std::map<Data*, std::vector<int> > oomph::NavierStokesSchurComplementPreconditioner::Eqn_number_backup private
Map to store original eqn numbers of various Data values when assembling pressure advection diffusion matrix
Referenced by pin_all_non_pressure_dofs(), and reset_pin_status().
F_mat_vec_pt
MatrixVectorProduct* oomph::NavierStokesSchurComplementPreconditioner::F_mat_vec_pt private
MatrixVectorProduct operator for F.
Referenced by clean_up_memory(), and NavierStokesSchurComplementPreconditioner().
F_preconditioner_is_block_preconditioner
bool oomph::NavierStokesSchurComplementPreconditioner::F_preconditioner_is_block_preconditioner private
Boolean indicating whether the momentum system preconditioner is a block preconditioner
F_preconditioner_pt
Preconditioner* oomph::NavierStokesSchurComplementPreconditioner::F_preconditioner_pt private
Pointer to the 'preconditioner' for the F matrix.
Referenced by clean_up_memory(), NavierStokesSchurComplementPreconditioner(), set_f_preconditioner(), and set_f_superlu_preconditioner().
Navier_stokes_mesh_pt
Mesh* oomph::NavierStokesSchurComplementPreconditioner::Navier_stokes_mesh_pt private
the pointer to the mesh of block preconditionable Navier Stokes elements.
Referenced by assemble_inv_press_and_veloc_mass_matrix_diagonal(), get_pressure_advection_diffusion_matrix(), NavierStokesSchurComplementPreconditioner(), pin_all_non_pressure_dofs(), reset_pin_status(), set_navier_stokes_mesh(), and validate().
P_preconditioner_pt
Preconditioner* oomph::NavierStokesSchurComplementPreconditioner::P_preconditioner_pt private
Pointer to the 'preconditioner' for the pressure matrix.
Referenced by clean_up_memory(), NavierStokesSchurComplementPreconditioner(), set_p_preconditioner(), and set_p_superlu_preconditioner().
Pin_first_pressure_dof_in_press_adv_diff
bool oomph::NavierStokesSchurComplementPreconditioner::Pin_first_pressure_dof_in_press_adv_diff private
Boolean indicating if we want to pin first pressure dof in Navier Stokes mesh when assembling the pressure advection diffusion system for Fp preconditoner – needed at zero Reynolds number for non-enclosed flows but seems harmless in any case
Referenced by get_pressure_advection_diffusion_matrix(), NavierStokesSchurComplementPreconditioner(), pin_first_pressure_dof_in_press_adv_diff(), and unpin_first_pressure_dof_in_press_adv_diff().
Preconditioner_has_been_setup
bool oomph::NavierStokesSchurComplementPreconditioner::Preconditioner_has_been_setup private
Control flag is true if the preconditioner has been setup (used so we can wipe the data when the preconditioner is called again)
Referenced by clean_up_memory(), and NavierStokesSchurComplementPreconditioner().
Problem_pt
Problem* oomph::NavierStokesSchurComplementPreconditioner::Problem_pt private
Storage for the (non-const!) problem pointer for use in get_pressure_advection_diffusion_matrix().
Referenced by problem_pt(), and set_problem_pt().
QBt_mat_vec_pt
MatrixVectorProduct* oomph::NavierStokesSchurComplementPreconditioner::QBt_mat_vec_pt private
MatrixVectorProduct operator for Qv^{-1} Bt.
Referenced by clean_up_memory(), and NavierStokesSchurComplementPreconditioner().
Use_LSC
bool oomph::NavierStokesSchurComplementPreconditioner::Use_LSC private
Boolean to indicate use of LSC (true) or Fp (false) variant.
Referenced by assemble_inv_press_and_veloc_mass_matrix_diagonal(), NavierStokesSchurComplementPreconditioner(), use_fp(), and use_lsc().
Use_robin_for_fp
bool oomph::NavierStokesSchurComplementPreconditioner::Use_robin_for_fp private
Use Robin BC elements for Fp preconditoner?
Referenced by disable_robin_for_fp(), enable_robin_for_fp(), get_pressure_advection_diffusion_matrix(), and NavierStokesSchurComplementPreconditioner().
Using_default_f_preconditioner
bool oomph::NavierStokesSchurComplementPreconditioner::Using_default_f_preconditioner private
flag indicating whether the default F preconditioner is used
Referenced by clean_up_memory(), NavierStokesSchurComplementPreconditioner(), set_f_preconditioner(), and set_f_superlu_preconditioner().
Using_default_p_preconditioner
bool oomph::NavierStokesSchurComplementPreconditioner::Using_default_p_preconditioner private
flag indicating whether the default P preconditioner is used
Referenced by clean_up_memory(), NavierStokesSchurComplementPreconditioner(), set_p_preconditioner(), and set_p_superlu_preconditioner().
The documentation for this class was generated from the following files:
navier_stokes_preconditioners.h
driven_cavity_with_simple_lsc_preconditioner.cc
navier_stokes_preconditioners.cc