MercuryDPM: Eigen::bfloat16_impl Namespace Reference
Eigen::bfloat16_impl Namespace Reference
Classes
struct __bfloat16_raw
struct bfloat16_base
struct numeric_limits_bfloat16_impl
Functions
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR __bfloat16_raw raw_uint16_to_bfloat16 (unsigned short value)
template<bool AssumeArgumentIsNormalOrInfinityOrZero>
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC __bfloat16_raw float_to_bfloat16_rtne (float ff)
template<>
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC __bfloat16_raw float_to_bfloat16_rtne< false > (float ff)
template<>
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC __bfloat16_raw float_to_bfloat16_rtne< true > (float ff)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC float bfloat16_to_float (__bfloat16_raw h)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 operator+ (const bfloat16 &a, const bfloat16 &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 operator+ (const bfloat16 &a, const int &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 operator+ (const int &a, const bfloat16 &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 operator* (const bfloat16 &a, const bfloat16 &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 operator- (const bfloat16 &a, const bfloat16 &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 operator/ (const bfloat16 &a, const bfloat16 &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 operator- (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 & operator+= (bfloat16 &a, const bfloat16 &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 & operator*= (bfloat16 &a, const bfloat16 &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 & operator-= (bfloat16 &a, const bfloat16 &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 & operator/= (bfloat16 &a, const bfloat16 &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 operator++ (bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 operator-- (bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 operator++ (bfloat16 &a, int)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 operator-- (bfloat16 &a, int)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool operator== (const bfloat16 &a, const bfloat16 &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool operator!= (const bfloat16 &a, const bfloat16 &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool operator< (const bfloat16 &a, const bfloat16 &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool operator<= (const bfloat16 &a, const bfloat16 &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool operator> (const bfloat16 &a, const bfloat16 &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool operator>= (const bfloat16 &a, const bfloat16 &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 operator/ (const bfloat16 &a, Index b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC __bfloat16_raw truncate_to_bfloat16 (const float v)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR __bfloat16_raw raw_uint16_to_bfloat16 (numext::uint16_t value)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR numext::uint16_t raw_bfloat16_as_uint16 (const __bfloat16_raw &bf)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool() isinf (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool() isnan (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool() isfinite (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 abs (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 exp (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 exp2 (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 expm1 (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 log (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 log1p (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 log10 (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 log2 (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 sqrt (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 pow (const bfloat16 &a, const bfloat16 &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 atan2 (const bfloat16 &a, const bfloat16 &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 sin (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 cos (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 tan (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 asin (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 acos (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 atan (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 sinh (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 cosh (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 tanh (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 asinh (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 acosh (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 atanh (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 floor (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 ceil (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 rint (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 round (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 trunc (const bfloat16 &a)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 fmod (const bfloat16 &a, const bfloat16 &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16() min (const bfloat16 &a, const bfloat16 &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16() max (const bfloat16 &a, const bfloat16 &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 fmin (const bfloat16 &a, const bfloat16 &b)
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 fmax (const bfloat16 &a, const bfloat16 &b)
EIGEN_ALWAYS_INLINE std::ostream & operator<< (std::ostream &os, const bfloat16 &v)
Function Documentation
abs()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::abs (const bfloat16 & a)
{
   numext::uint16_t x = numext::bit_cast<numext::uint16_t>(a) & 0x7FFF;
   return numext::bit_cast<bfloat16>(x);
 }
References a, and plotDoE::x.
acos()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::acos (const bfloat16 & a)
 { return bfloat16(::acosf(float(a))); }
References a.
acosh()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::acosh (const bfloat16 & a)
 { return bfloat16(::acoshf(float(a))); }
References a.
Referenced by array_real(), and unary_ops_test().
asin()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::asin (const bfloat16 & a)
 { return bfloat16(::asinf(float(a))); }
References a.
Referenced by array_real(), ContactProblem< ELEMENT >::complete_problem_setup(), Quaternion::getEuler(), helpers::getMaximumVelocity(), oomph::CylinderWithFlagDomain::macro_element_boundary(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_IX(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_VIII(), EulerAngles< Scalar_ >::operator=(), packetmath_real(), Eigen::internal::pasin(), RingWithTRibProblem< ELASTICITY_ELEMENT >::RingWithTRibProblem(), slerp_gael(), slerp_rw(), and unary_ops_test().
asinh()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::asinh (const bfloat16 & a)
 { return bfloat16(::asinhf(float(a))); }
References a.
Referenced by array_real(), and unary_ops_test().
atan()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::atan (const bfloat16 & a)
 { return bfloat16(::atanf(float(a))); }
References a.
Referenced by QuarterCircleDrivenCavityProblem2< ELEMENT >::actions_before_newton_solve(), QuarterCircleDrivenCavityProblem< ELEMENT >::actions_before_newton_solve(), GranuHeap::actionsAfterTimeStep(), LawinenBox::actionsBeforeTimeStep(), alignedboxNonIntegralRotatable(), Jeffery_Solution::angle(), array_real(), AxiPoroProblem< ELEMENT, TIMESTEPPER >::AxiPoroProblem(), SinterLinInteraction::computeNormalForce(), CylinderAndInterfaceDomain::CylinderAndInterfaceDomain(), DiskOscillationProblem< ELEMENT >::DiskOscillationProblem(), DiskShockWaveProblem< ELEMENT, TIMESTEPPER >::DiskShockWaveProblem(), DrivenCavityProblem< ELEMENT, MESH >::DrivenCavityProblem(), ElasticRefineableQuarterCircleSectorMesh< ELEMENT >::ElasticRefineableQuarterCircleSectorMesh(), ElasticRingProblem< ELEMENT >::ElasticRingProblem(), EntryFlowProblem< ELEMENT >::EntryFlowProblem(), oomph::SarahBL::exact_soln(), SarahBL::exact_soln(), FSIRingProblem::FSIRingProblem(), oomph::SarahBL::full_exact_soln(), SarahBL::full_exact_soln(), ArcTanSolnForPoisson::get_exact_u(), ArcTanSolnForPoisson::get_source(), HomogenisationProblem< ELEMENT >::HomogenisationProblem(), Global::initial_condition(), oomph::RectangleWithHoleAndAnnularRegionDomain::macro_element_boundary(), RectangleWithHoleDomain::macro_element_boundary(), oomph::HalfRectangleWithHoleDomain::macro_element_boundary(), CylinderAndInterfaceDomain::macro_element_boundary(), oomph::CylinderWithFlagDomain::macro_element_boundary(), oomph::RectangleWithHoleDomain::macro_element_boundary(), main(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_IX(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_VIII(), OscRingNStProblem< ELEMENT >::OscRingNStProblem(), packetmath_real(), ElasticBeamProblem::parameter_study(), Eigen::internal::patan(), WarpedLine::position(), GranuDrum::printTime(), RotatingDrumBidisperse::printTime(), oomph::RectangleWithHoleAndAnnularRegionDomain::project_point_on_cylinder_to_annular_boundary(), QuarterCircleDrivenCavityProblem< ELEMENT >::QuarterCircleDrivenCavityProblem(), QuarterCircleDrivenCavityProblem2< ELEMENT >::QuarterCircleDrivenCavityProblem2(), WarpedLine::radius(), RayleighProblem< ELEMENT, TIMESTEPPER >::RayleighProblem(), oomph::RefineableQuadMeshWithMovingCylinder< MyRefineableQTaylorHoodElement >::RefineableQuadMeshWithMovingCylinder(), run_navier_stokes_outflow(), ChutePeriodic::set_chute_parameters(), BratuProblem< ELEMENT >::solve(), ABCProblem< ELEMENT, TIMESTEPPERT >::solve(), StaticDiskCompressionProblem< ELEMENT >::StaticDiskCompressionProblem(), unary_ops_test(), LawinenBox::writeEneTimeStep(), GranuDrum::writeResults(), RotatingDrumBidisperse::writeResults(), and WarpedLine::y_c().
atan2()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::atan2 (const bfloat16 & a, const bfloat16 & b)
{
   return bfloat16(::atan2f(float(a), float(b)));
 }
References a, and b.
atanh()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::atanh (const bfloat16 & a)
 { return bfloat16(::atanhf(float(a))); }
References a.
Referenced by array_real(), packetmath_real(), Eigen::internal::patanh(), and unary_ops_test().
bfloat16_to_float()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC float Eigen::bfloat16_impl::bfloat16_to_float (__bfloat16_raw h)
{
 #if defined(EIGEN_USE_HIP_BF16)
   return static_cast<float>(h);
 #else
   return numext::bit_cast<float>(static_cast<numext::uint32_t>(h.value) << 16);
 #endif
 }
References Eigen::bfloat16_impl::__bfloat16_raw::value.
Referenced by Eigen::internal::gemmbfloat16(), Eigen::internal::gemmMMAbfloat16(), gemv_bfloat16_col(), gemv_bfloat16_row(), Eigen::internal::gemvMMA_bfloat16_col(), Eigen::internal::gemvMMA_bfloat16_row(), and Eigen::bfloat16::operator float().
ceil()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::ceil (const bfloat16 & a)
 { return bfloat16(::ceilf(float(a))); }
References a.
Referenced by LawinenBox::actionsBeforeTimeStep(), Vreman::add_particles(), array_real(), Eigen::ArpackGeneralizedSelfAdjointEigenSolver< MatrixType, MatrixSolver, BisSPD >::compute(), Eigen::MatrixPowerAtomic< MatrixType >::computeSuperDiag(), SilbertHstop::continueSolve(), ContractionWithPeriodicInflow::ContractionWithPeriodicInflow(), RandomImpl< Eigen::SparseMatrix< Scalar, Options, DenseIndex > >::Create(), Funnel::create_funnel(), TriangleMeshWall::getNumberOfSegmentsAndResolution(), helpers::getPercentile(), ParticleHandler::getPSD(), helpers::getSaveCountFromNumberOfSavesAndTimeMaxAndTimeStep(), Eigen::internal::matrix_log_compute_2x2(), packetmath_real(), BaseCluster::printTime(), Eigen::internal::default_digits_impl< T, false, false >::run(), Eigen::internal::default_max_digits10_impl< T, false, false >::run(), simulate::runSimulations(), simulateAWS::runSimulations(), File::saveCurrentTimeStepNoFileTypeCheck(), Eigen::TensorSycl::internal::ScanInfo< Index >::ScanInfo(), StatisticsVector< T >::set_hx(), StatisticsVector< T >::set_hy(), StatisticsVector< T >::set_hz(), BaseCG::setHX(), BaseCG::setHY(), BaseCG::setHZ(), my_problem_HGRID::setupInitialConditions(), oomph::HSL_MA42::solve(), SolidProblem< ELEMENT_TYPE >::solveUnsteady(), test_basic_functions(), test_float_ceiling(), and unary_ops_test().
cos()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::cos (const bfloat16 & a)
 { return bfloat16(::cosf(float(a))); }
References a.
cosh()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::cosh (const bfloat16 & a)
 { return bfloat16(::coshf(float(a))); }
References a.
Referenced by array_complex(), array_real(), check_hyperbolic_functions(), oomph::TanhProfileConstitutiveEquation< DIM >::dviscosity_dinvariant(), TanhSolnForLinearWave::exact_d2udt2(), TanhSolnForLinearWave::exact_dudt(), TanhSolnForLinearWave::get_exact_gradient(), TanhSolnForPoisson::get_exact_gradient(), Eigen::internal::pcosh(), Eigen::internal::stem_function_cosh(), Eigen::internal::stem_function_sinh(), test2dHyperbolicRotation(), and unary_ops_test().
exp()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::exp (const bfloat16 & a)
 { return bfloat16(::expf(float(a))); }
References a.
Referenced by InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::actions_before_implicit_timestep(), UnstructuredFluidProblem< ELEMENT >::actions_before_implicit_timestep(), MeltSpinningProblem< ELEMENT >::actions_before_newton_solve(), AxisymFreeSurfaceNozzleAdvDiffRobinProblem< ELEMENT >::actions_before_newton_solve(), CFDDEMCoupleTest::actionsAfterTimeStep(), MeltableNormalSpecies::analyseTimeScales(), array_complex(), array_real(), array_special_functions(), CRBond_Bessel::bessik01a(), CRBond_Bessel::bessik01b(), CRBond_Bessel::bessiknb(), CRBond_Bessel::bessikv(), mathsFunc::beta(), ProblemParameters::body_force(), Global_Parameters::body_force(), Boundary_Items::boundary_velocity(), CRBond_Bessel::cbessik01(), CRBond_Bessel::cbessiknb(), CRBond_Bessel::cbessikv(), CRBond_Bessel::cbessjyva(), check_atan2(), mathsFunc::chi_squared(), oomph::HelmholtzBCElementBase< ELEMENT >::compute_contribution_to_fourier_components(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::compute_gamma_contribution(), LiquidBridgeClassicalWilletInteraction::computeAdhesionForce(), Eigen::MatrixPowerAtomic< MatrixType >::computeSuperDiag(), PSD::convertPdfPhiToPdfMeter(), MeltSpinningProblem< ELEMENT >::deform_free_surface(), AxisymFreeSurfaceNozzleAdvDiffRobinProblem< ELEMENT >::deform_free_surface(), Eigen::CholmodBase< MatrixType_, UpLo_, Derived >::determinant(), DenseLM< Scalar >::df(), chwirut2_functor::df(), misra1a_functor::df(), lanczos1_functor::df(), rat42_functor::df(), MGH10_functor::df(), BoxBOD_functor::df(), MGH17_functor::df(), rat43_functor::df(), eckerle4_functor::df(), oomph::SarahBL::Diss_sarah(), SarahBL::Diss_sarah(), oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::NicosConstitutiveEquation< DIM >::dviscosity_dinvariant(), EIGEN_DECLARE_TEST(), Eigen::MatrixComplexPowerReturnValue< Derived >::evalTo(), Global_Parameters::exact_solution(), expfn(), HeatFluidCoupledSpecies< NormalForceSpecies >::f(), Eigen::internal::F32ToBf16(), Eigen::internal::F32ToBf16Two(), fft_rmse(), GelfandBratuElement< NNODE_1D >::fill_in_generic_dresidual_contribution(), PredatorPreyElement::fill_in_generic_residual_contribution(), ABCElement::fill_in_generic_residual_contribution(), GelfandBratuElement< NNODE_1D >::fill_in_generic_residual_contribution(), Eigen::internal::unary_pow::exponent_helper< ScalarExponent, true >::floor_div_two(), Eigen::internal::unary_pow::exponent_helper< ScalarExponent, IsInteger >::floor_div_two(), foo(), ExactSoln::get_exact_u(), ExactSolnForUnsteadyHeat::get_exact_u(), RachelsAdvectionDiffusion::get_exact_u(), GlobalParameters::get_exact_u(), Boundary_Items::get_exact_u_b1(), CGCoordinates::Base_X_Y_Z::getGaussIntegralPrefactor(), CGCoordinates::Base_XY_XZ_YZ::getGaussIntegralPrefactor(), CGCoordinates::XYZ::getGaussIntegralPrefactor(), CGCoordinates::Base_XY_XZ_YZ::getGaussPrefactor(), CGCoordinates::XYZ::getGaussPrefactor(), helpers::getMaximumVelocity(), RNG::getPoissonVariate(), LinearPlasticViscoelasticNormalSpecies::getRestitutionCoefficient(), LinearViscoelasticNormalSpecies::getRestitutionCoefficient(), SinterLinNormalSpecies::getRestitutionCoefficient(), SPHNormalSpecies::getRestitutionCoefficient(), HGridOptimiser::histNumberParticlesPerCell(), mathsFunc::I0(), is_integer(), pow_helper< Exponent, ExpIsInteger >::is_integer_impl(), is_odd(), Eigen::internal::unary_pow::exponent_helper< ScalarExponent, true >::is_odd(), Eigen::internal::unary_pow::exponent_helper< ScalarExponent, IsInteger >::is_odd(), pow_helper< Exponent, ExpIsInteger >::is_odd_impl(), pow_helper< Exponent, true >::is_odd_impl(), CFDDEMCoupleTest::itterateL(), LaserOnLayer::LaserOnLayer(), mathsFunc::log(), oomph::Refineable_r_mesh< ELEMENT >::log_spacing(), TestProblem::mass_source(), DenseLM< Scalar >::model(), DenseLM< Scalar >::operator()(), chwirut2_functor::operator()(), misra1a_functor::operator()(), lanczos1_functor::operator()(), rat42_functor::operator()(), MGH10_functor::operator()(), BoxBOD_functor::operator()(), MGH17_functor::operator()(), rat43_functor::operator()(), eckerle4_functor::operator()(), packetmath_real(), rapidjson::GenericReader< Encoding, Allocator >::ParseNumber(), particleParticleTest(), Eigen::internal::pfrexp(), PlanarWave::plot(), OscillatingCylinder::position(), WarpedLine::position(), ExactSolnForUnsteadyHeat::prescribed_flux_on_fixed_y_boundary(), GlobalParameters::prescribed_incoming_flux(), ExactSoln::prescribed_traction(), Global_Parameters::pressure_load(), randomTest(), Eigen::internal::kissfft_impl< Scalar_ >::real_twiddles(), REF_FREXP(), REF_LDEXP(), exp_complex_test_impl< Scalar, Packet, HasExp >::run(), run_eigen(), Eigen::internal::unary_pow::exponent_helper< ScalarExponent, IsInteger >::safe_abs(), Eigen::internal::unary_pow::exponent_helper< ScalarExponent, true >::safe_abs(), ParhamiMcMeekingSinterSpecies::set(), RefineablePorousChannelProblem< ELEMENT >::set_boundary_conditions(), TorusProblem< ELEMENT >::set_boundary_conditions(), UnstructuredTorusProblem< ELEMENT >::set_boundary_conditions(), ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::set_boundary_conditions(), DDConvectionProblem< NST_ELEMENT, AD_ELEMENT >::set_boundary_conditions(), RefineableDDConvectionProblem< NST_ELEMENT, AD_ELEMENT >::set_boundary_conditions(), RefineableSphereConvectionProblem< ELEMENT >::set_boundary_conditions(), UnstructuredImmersedEllipseProblem< ELEMENT >::set_boundary_velocity(), RefineableAdvectionDiffusionPipeProblem< ELEMENT >::set_initial_condition(), RefineableOneDAdvectionDiffusionReactionProblem< ELEMENT >::set_initial_condition(), RefineableActivatorInhibitorProblem< ELEMENT >::set_initial_condition(), RefineableAdvectionDiffusionPipeProblem< ELEMENT >::set_inlet_concentration(), PSD::setDistributionLogNormal(), SinterNormalSpecies::setParhamiMcKeeping(), Calibration::setPSD(), Material::setPSD(), GlobalParameters::sin_cos_velocity_field(), GlobalParameters::sin_cos_vorticity(), SilbertHstop::solve_analytic(), sphericalHarmonics::sphericalHarmonics(), Eigen::internal::stem_function_exp(), test2dRotation(), test_3d(), test_basic_functions(), test_sigmoid(), testGonioFunctions(), oomph::SarahBL::U_sarah(), SarahBL::U_sarah(), unary_ops_test(), oomph::SarahBL::V_sarah(), SarahBL::V_sarah(), oomph::HerschelBulkleyPapRegConstitutiveEquation< DIM >::viscosity(), oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::viscosity(), oomph::NicosConstitutiveEquation< DIM >::viscosity(), Global_Physical_Variables::viscosity_ratio_function(), and wallParticleTest().
exp2()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::exp2 (const bfloat16 & a)
 { return bfloat16(::exp2f(float(a))); }
References a.
Referenced by calc_overflow_threshold(), packetmath_real(), Eigen::internal::pfrexp< Packet32h >(), Eigen::internal::pldexp< Packet32h >(), and unary_ops_test().
expm1()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::expm1 (const bfloat16 & a)
 { return bfloat16(numext::expm1(float(a))); }
References a.
Referenced by array_complex(), array_real(), Eigen::internal::generic_expm1(), Eigen::internal::scalar_expm1_op< Scalar >::operator()(), packetmath_real(), Eigen::internal::pexpm1(), and test_basic_functions().
float_to_bfloat16_rtne()
template<bool AssumeArgumentIsNormalOrInfinityOrZero> EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC __bfloat16_raw Eigen::bfloat16_impl::float_to_bfloat16_rtne (float ff)
float_to_bfloat16_rtne< false >()
template<> EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC __bfloat16_raw Eigen::bfloat16_impl::float_to_bfloat16_rtne< false > (float ff)
{
 #if defined(EIGEN_USE_HIP_BF16)
   return __bfloat16_raw(__bfloat16_raw::round_to_bfloat16(ff));
 #else
   __bfloat16_raw output;
   if (numext::isnan EIGEN_NOT_A_MACRO(ff)) {
     // If the value is a NaN, squash it to a qNaN with msb of fraction set,
     // this makes sure after truncation we don't end up with an inf.
     //
     // qNaN magic: All exponent bits set + most significant bit of fraction
     // set.
     output.value = std::signbit(ff) ? 0xFFC0 : 0x7FC0;
   } else {
     // Fast rounding algorithm that rounds a half value to nearest even. This
     // reduces expected error when we convert a large number of floats. Here
     // is how it works:
     //
     // Definitions:
     // To convert a float 32 to bfloat16, a float 32 can be viewed as 32 bits
     // with the following tags:
     //
     // Sign |  Exp (8 bits) | Frac (23 bits)
     //  S     EEEEEEEE         FFFFFFLRTTTTTTTTTTTTTTT
     //
     //  S: Sign bit.
     //  E: Exponent bits.
     //  F: First 6 bits of fraction.
     //  L: Least significant bit of resulting bfloat16 if we truncate away the
     //  rest of the float32. This is also the 7th bit of fraction
     //  R: Rounding bit, 8th bit of fraction.
     //  T: Sticky bits, rest of fraction, 15 bits.
     //
     // To round half to nearest even, there are 3 cases where we want to round
     // down (simply truncate the result of the bits away, which consists of
     // rounding bit and sticky bits) and two cases where we want to round up
     // (truncate then add one to the result).
     //
     // The fast converting algorithm simply adds lsb (L) to 0x7fff (15 bits of
     // 1s) as the rounding bias, adds the rounding bias to the input, then
     // truncates the last 16 bits away.
     //
     // To understand how it works, we can analyze this algorithm case by case:
     //
     // 1. L = 0, R = 0:
     //   Expect: round down, this is less than half value.
     //
     //   Algorithm:
     //   - Rounding bias: 0x7fff + 0 = 0x7fff
     //   - Adding rounding bias to input may create any carry, depending on
     //   whether there is any value set to 1 in T bits.
     //   - R may be set to 1 if there is a carry.
     //   - L remains 0.
     //   - Note that this case also handles Inf and -Inf, where all fraction
     //   bits, including L, R and Ts are all 0. The output remains Inf after
     //   this algorithm.
     //
     // 2. L = 1, R = 0:
     //   Expect: round down, this is less than half value.
     //
     //   Algorithm:
     //   - Rounding bias: 0x7fff + 1 = 0x8000
     //   - Adding rounding bias to input doesn't change sticky bits but
     //   adds 1 to rounding bit.
     //   - L remains 1.
     //
     // 3. L = 0, R = 1, all of T are 0:
     //   Expect: round down, this is exactly at half, the result is already
     //   even (L=0).
     //
     //   Algorithm:
     //   - Rounding bias: 0x7fff + 0 = 0x7fff
     //   - Adding rounding bias to input sets all sticky bits to 1, but
     //   doesn't create a carry.
     //   - R remains 1.
     //   - L remains 0.
     //
     // 4. L = 1, R = 1:
     //   Expect: round up, this is exactly at half, the result needs to be
     //   round to the next even number.
     //
     //   Algorithm:
     //   - Rounding bias: 0x7fff + 1 = 0x8000
     //   - Adding rounding bias to input doesn't change sticky bits, but
     //   creates a carry from rounding bit.
     //   - The carry sets L to 0, creates another carry bit and propagate
     //   forward to F bits.
     //   - If all the F bits are 1, a carry then propagates to the exponent
     //   bits, which then creates the minimum value with the next exponent
     //   value. Note that we won't have the case where exponents are all 1,
     //   since that's either a NaN (handled in the other if condition) or inf
     //   (handled in case 1).
     //
     // 5. L = 0, R = 1, any of T is 1:
     //   Expect: round up, this is greater than half.
     //
     //   Algorithm:
     //   - Rounding bias: 0x7fff + 0 = 0x7fff
     //   - Adding rounding bias to input creates a carry from sticky bits,
     //   sets rounding bit to 0, then create another carry.
     //   - The second carry sets L to 1.
     //
     // Examples:
     //
     //  Exact half value that is already even:
     //    Input:
     //    Sign |  Exp (8 bit)     | Frac (first 7 bit) | Frac (last 16 bit)
     //     S     E E E E E E E E      F F F F F F L     RTTTTTTTTTTTTTTT
     //     0     0 0 0 0 0 0 0 0      0 0 0 0 0 1 0     1000000000000000
     //
     //     This falls into case 3. We truncate the rest of 16 bits and no
     //     carry is created into F and L:
     //
     //    Output:
     //    Sign |  Exp (8 bit)     | Frac (first 7 bit)
     //     S     E E E E E E E E      F F F F F F L
     //     0     0 0 0 0 0 0 0 0      0 0 0 0 0 1 0
     //
     //  Exact half value, round to next even number:
     //    Input:
     //    Sign |  Exp (8 bit)     | Frac (first 7 bit) | Frac (last 16 bit)
     //     S     E E E E E E E E      F F F F F F L     RTTTTTTTTTTTTTTT
     //     0     0 0 0 0 0 0 0 0      0 0 0 0 0 0 1     1000000000000000
     //
     //     This falls into case 4. We create a carry from R and T,
     //     which then propagates into L and F:
     //
     //    Output:
     //    Sign |  Exp (8 bit)     | Frac (first 7 bit)
     //     S     E E E E E E E E      F F F F F F L
     //     0     0 0 0 0 0 0 0 0      0 0 0 0 0 1 0
     //
     //
     //  Max denormal value round to min normal value:
     //    Input:
     //    Sign |  Exp (8 bit)     | Frac (first 7 bit) | Frac (last 16 bit)
     //     S     E E E E E E E E      F F F F F F L     RTTTTTTTTTTTTTTT
     //     0     0 0 0 0 0 0 0 0      1 1 1 1 1 1 1     1111111111111111
     //
     //     This falls into case 4. We create a carry from R and T,
     //     propagate into L and F, which then propagates into exponent
     //     bits:
     //
     //    Output:
     //    Sign |  Exp (8 bit)     | Frac (first 7 bit)
     //     S     E E E E E E E E      F F F F F F L
     //     0     0 0 0 0 0 0 0 1      0 0 0 0 0 0 0
     //
     //  Max normal value round to Inf:
     //    Input:
     //    Sign |  Exp (8 bit)     | Frac (first 7 bit) | Frac (last 16 bit)
     //     S     E E E E E E E E      F F F F F F L     RTTTTTTTTTTTTTTT
     //     0     1 1 1 1 1 1 1 0      1 1 1 1 1 1 1     1111111111111111
     //
     //     This falls into case 4. We create a carry from R and T,
     //     propagate into L and F, which then propagates into exponent
     //     bits:
     //
     //    Sign |  Exp (8 bit)     | Frac (first 7 bit)
     //     S     E E E E E E E E      F F F F F F L
     //     0     1 1 1 1 1 1 1 1      0 0 0 0 0 0 0
     // At this point, ff must be either a normal float, or +/-infinity.
     output = float_to_bfloat16_rtne<true>(ff);
   }
   return output;
 #endif
 }
References EIGEN_NOT_A_MACRO, float_to_bfloat16_rtne< true >(), Eigen::numext::isnan(), output(), and Eigen::numext::signbit().
float_to_bfloat16_rtne< true >()
template<> EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC __bfloat16_raw Eigen::bfloat16_impl::float_to_bfloat16_rtne< true > (float ff)
{
 #if defined(EIGEN_USE_HIP_BF16)
   return __bfloat16_raw(__bfloat16_raw::round_to_bfloat16(ff));
 #else
   numext::uint32_t input = numext::bit_cast<numext::uint32_t>(ff);
   __bfloat16_raw output;
   // Least significant bit of resulting bfloat.
   numext::uint32_t lsb = (input >> 16) & 1;
   numext::uint32_t rounding_bias = 0x7fff + lsb;
   input += rounding_bias;
   output.value = static_cast<numext::uint16_t>(input >> 16);
   return output;
 #endif
 }
References output().
Referenced by float_to_bfloat16_rtne< false >().
floor()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::floor (const bfloat16 & a)
 { return bfloat16(::floorf(float(a))); }
References a.
Referenced by ChangingTOIParticle::actionsAfterTimeStep(), BaseCluster::actionsAfterTimeStep(), Slide::actionsBeforeTimeStep(), BaseCluster::actionsOnRestart(), NautaMixer::addParticlesAtWall(), array_real(), UnsteadyHeatProblem< ELEMENT >::assign_time_slab_id(), calc_overflow_threshold(), CircularPeriodicBoundary::checkBoundaryAfterParticleMoved(), Mercury2D::computeInternalForces(), Mercury3D::computeInternalForces(), DPM::computeLocalCGHGrid(), DPM::computeLocalVolumeFractionHGrid(), Mercury3D::computeWallForces(), BinArray::coords_to_bin_index(), BinArray::coords_to_vectorial_bin_index(), mathsFunc::cos(), SilbertPeriodic::create_inflow_particle(), Chute::createBottom(), CircularPeriodicBoundary::createPeriodicParticle(), NurbsUtils::findSpan(), DPMBase::get3DParametersFromRunNumber(), oomph::ImmersedRigidBodyTriangleMeshPolygon::get_initial_position(), oomph::QElement< 1, NNODE_1D >::get_node_at_local_coordinate(), oomph::QElement< 2, NNODE_1D >::get_node_at_local_coordinate(), oomph::QElement< 3, NNODE_1D >::get_node_at_local_coordinate(), DomainHandler::getParticleDomainGlobalIndex(), helpers::getPercentile(), Mercury2D::hGridFindParticleContacts(), Mercury3D::hGridFindParticleContacts(), Mercury2D::hGridGetInteractingParticleList(), Mercury3D::hGridGetInteractingParticleList(), Mercury2D::hGridHasParticleContacts(), Mercury3D::hGridHasParticleContacts(), Mercury2D::hGridUpdateParticle(), Mercury3D::hGridUpdateParticle(), HGridOptimiser::histNumberParticlesPerCell(), pow_helper< Exponent, ExpIsInteger >::is_integer_impl(), pow_helper< Exponent, ExpIsInteger >::is_odd_impl(), LaserOnLayer::LaserOnLayer(), oomph::ChannelWithLeafletDomain::macro_element_boundary(), main(), packetmath_real(), PlateProblem< ELEMENT >::PlateProblem(), HGridOptimiser::radius2Cell(), HGridOptimiser::radius2IntCell(), GlobalParameters::round(), Eigen::internal::default_digits10_impl< T, false, false >::run(), CoilSelfTest::setupInitialConditions(), BaseCluster::setupInitialConditions(), ShellProblem< ELEMENT >::ShellProblem(), mathsFunc::sin(), Eigen::MatrixPower< MatrixType >::split(), DPMBase::splitDomain(), RNG::test(), test_basic_functions(), test_float_flooring(), and unary_ops_test().
fmax()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::fmax (const bfloat16 & a, const bfloat16 & b)
{
   const float f1 = static_cast<float>(a);
   const float f2 = static_cast<float>(b);
   return bfloat16(::fmaxf(f1, f2));
 }
References a, b, Global_parameters::f1(), and Global_parameters::f2().
Referenced by LevelSetWall::setShapeCylinder(), Packing::setupInitialConditions(), and HorizontalBaseScrew::writeVTK().
fmin()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::fmin (const bfloat16 & a, const bfloat16 & b)
{
   const float f1 = static_cast<float>(a);
   const float f2 = static_cast<float>(b);
   return bfloat16(::fminf(f1, f2));
 }
References a, b, Global_parameters::f1(), and Global_parameters::f2().
Referenced by Packing::setupInitialConditions().
fmod()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::fmod (const bfloat16 & a, const bfloat16 & b)
{
   return bfloat16(::fmodf(float(a), float(b)));
 }
References a, and b.
Referenced by BaseCluster::actionsAfterTimeStep(), ScrewsymmetricIntersectionOfWalls::computeDeltaZ(), Eigen::MatrixPower< MatrixType >::computeIntPower(), NurbsSurface::getDistance(), TimeDependentPeriodicBoundary::getPlanewiseShift(), RNG::getRandomNumberFromLaggedFibonacciGenerator(), LaserOnLayer::LaserOnLayer(), and test_basic_functions().
isfinite()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool() Eigen::bfloat16_impl::isfinite (const bfloat16 & a)
{
   return !(isinf EIGEN_NOT_A_MACRO(a)) && !(isnan EIGEN_NOT_A_MACRO(a));
 }
References a, EIGEN_NOT_A_MACRO, isinf(), and isnan().
Referenced by Eigen::numext::isfinite().
isinf()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool() Eigen::bfloat16_impl::isinf (const bfloat16 & a)
{
   EIGEN_USING_STD(isinf);
 #if defined(EIGEN_USE_HIP_BF16)
   return (isinf)(a);  // Uses HIP hip_bfloat16 isinf operator
 #else
   return (isinf)(float(a));
 #endif
 }
References a, and EIGEN_USING_STD.
Referenced by isfinite(), and Eigen::numext::isinf().
isnan()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool() Eigen::bfloat16_impl::isnan (const bfloat16 & a)
{
   EIGEN_USING_STD(isnan);
 #if defined(EIGEN_USE_HIP_BF16)
   return (isnan)(a);  // Uses HIP hip_bfloat16 isnan operator
 #else
   return (isnan)(float(a));
 #endif
 }
References a, and EIGEN_USING_STD.
Referenced by isfinite(), and Eigen::numext::isnan().
log()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::log (const bfloat16 & a)
 { return bfloat16(::logf(float(a))); }
References a.
Referenced by MeltSpinningProblem< ELEMENT >::actions_before_newton_solve(), AxisymFreeSurfaceNozzleAdvDiffRobinProblem< ELEMENT >::actions_before_newton_solve(), array_complex(), array_real(), CRBond_Bessel::bessik01a(), CRBond_Bessel::bessik01b(), CRBond_Bessel::bessiknb(), CRBond_Bessel::bessikv(), CRBond_Bessel::bessjy01a(), CRBond_Bessel::bessjy01b(), CRBond_Bessel::bessjynb(), CRBond_Bessel::bessjyv(), CRBond_Bessel::cbessik01(), CRBond_Bessel::cbessiknb(), CRBond_Bessel::cbessikv(), CRBond_Bessel::cbessjy01(), CRBond_Bessel::cbessjynb(), CRBond_Bessel::cbessjyva(), CircularPeriodicBoundary::checkBoundaryAfterParticleMoved(), Eigen::internal::chkder(), cod(), Eigen::internal::MatrixLogarithmAtomic< MatrixType >::compute(), LiquidBridgeBagheriInteraction::computeAdhesionForce(), LiquidBridgeClassicalWilletInteraction::computeAdhesionForce(), LiquidMigrationLSInteraction::computeAdhesionForce(), LiquidMigrationWilletViscousInteraction::computeAdhesionForce(), helpers::computeDisptFromCollisionTimeAndRestitutionCoefficientAndTangentialRestitutionCoefficientAndEffectiveMass(), Eigen::MatrixPowerAtomic< MatrixType >::computeSuperDiag(), CircularPeriodicBoundary::createPeriodicParticle(), MeltSpinningProblem< ELEMENT >::deform_free_surface(), AxisymFreeSurfaceNozzleAdvDiffRobinProblem< ELEMENT >::deform_free_surface(), Bennett5_functor::df(), rat43_functor::df(), MD_demo::DistInt(), PoissonProblem< ELEMENT >::doc_solution(), EighthSpherePoissonProblem< ELEMENT >::doc_solution(), Global::exact_solution(), HeatFluidCoupledSpecies< NormalForceSpecies >::f(), PerturbationSolution::first_order_veloc_and_pressure(), GlobalParameters::get_exact_u(), RNG::getNormalVariate(), log2(), oomph::Refineable_r_mesh< ELEMENT >::log_spacing(), Eigen::SparseLU< MatrixType_, OrderingType_ >::logAbsDeterminant(), Eigen::CholmodBase< MatrixType_, UpLo_, Derived >::logDeterminant(), main(), Eigen::internal::matrix_log_compute_2x2(), packetmath_complex(), packetmath_real(), particleParticleTest(), Eigen::internal::plog(), Global_Parameters::pressure_couette(), qr_invertible(), exp_complex_test_impl< Scalar, Packet, HasExp >::run(), SlidingFrictionSpecies::setCollisionTimeAndNormalAndTangentialRestitutionCoefficient(), LinearPlasticViscoelasticNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), SinterLinNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), SinterNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), Calibration::setPSD(), Material::setPSD(), LinearPlasticViscoelasticNormalSpecies::setRestitutionCoefficient(), LinearViscoelasticNormalSpecies::setRestitutionCoefficient(), SinterLinNormalSpecies::setRestitutionCoefficient(), SPHNormalSpecies::setRestitutionCoefficient(), SinterLinNormalSpecies::setStiffnessAndRestitutionCoefficient(), SinterNormalSpecies::setStiffnessAndRestitutionCoefficient(), StressStrainControl::setupInitialConditions(), SegregationPeriodic::setupInitialConditions(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), oomph::SolubleSurfactantTransportInterfaceElement::sigma(), test_argmax_dim(), test_argmax_pair_reducer(), test_argmin_dim(), test_argmin_pair_reducer(), test_basic_functions(), test_index_pairs_dim(), test_simple_argmax(), test_simple_argmin(), test_simple_index_pairs(), ActivatorInhibitorProblem< ELEMENT >::timestep(), oomph::BermudezPMLMappingAndTransformedCoordinate::transformed_coordinate(), unary_ops_test(), and wallParticleTest().
log10()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::log10 (const bfloat16 & a)
 { return bfloat16(::log10f(float(a))); }
References a.
Referenced by array_complex(), array_real(), CRBond_Bessel::msta1(), CRBond_Bessel::msta2(), Eigen::internal::scalar_log10_op< Scalar >::operator()(), Eigen::internal::plog10(), MandelbrotThread::run(), Eigen::internal::default_digits10_impl< T, false, false >::run(), and Eigen::internal::default_max_digits10_impl< T, false, false >::run().
log1p()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::log1p (const bfloat16 & a)
 { return bfloat16(numext::log1p(float(a))); }
References a.
Referenced by array_real(), Eigen::MatrixPowerAtomic< MatrixType >::computeSuperDiag(), Eigen::internal::matrix_log_compute_2x2(), Eigen::internal::scalar_log1p_op< Scalar >::operator()(), packetmath_real(), Eigen::internal::plog1p(), and test_basic_functions().
log2()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::log2 (const bfloat16 & a)
{
   return bfloat16(static_cast<float>(EIGEN_LOG2E) * ::logf(float(a)));
 }
References a, and EIGEN_LOG2E.
max()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16() Eigen::bfloat16_impl::max (const bfloat16 & a, const bfloat16 & b)
{
   const float f1 = static_cast<float>(a);
   const float f2 = static_cast<float>(b);
   return f1 < f2 ? b : a;
 }
References a, b, Global_parameters::f1(), and Global_parameters::f2().
min()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16() Eigen::bfloat16_impl::min (const bfloat16 & a, const bfloat16 & b)
{
   const float f1 = static_cast<float>(a);
   const float f2 = static_cast<float>(b);
   return f2 < f1 ? b : a;
 }
References a, b, Global_parameters::f1(), and Global_parameters::f2().
operator!=()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool Eigen::bfloat16_impl::operator!= (const bfloat16 & a, const bfloat16 & b)
{
   return numext::not_equal_strict(float(a), float(b));
 }
References a, b, and Eigen::numext::not_equal_strict().
operator*()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::operator* (const bfloat16 & a, const bfloat16 & b)
{
   return bfloat16(float(a) * float(b));
 }
References a, and b.
operator*=()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16& Eigen::bfloat16_impl::operator*= (bfloat16 & a, const bfloat16 & b)
{
   a = bfloat16(float(a) * float(b));
   return a;
 }
References a, and b.
operator+() [1/3]
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::operator+ (const bfloat16 & a, const bfloat16 & b)
{
   return bfloat16(float(a) + float(b));
 }
References a, and b.
operator+() [2/3]
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::operator+ (const bfloat16 & a, const int & b)
{
   return bfloat16(float(a) + static_cast<float>(b));
 }
References a, and b.
operator+() [3/3]
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::operator+ (const int & a, const bfloat16 & b)
{
   return bfloat16(static_cast<float>(a) + float(b));
 }
References a, and b.
operator++() [1/2]
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::operator++ (bfloat16 & a)
{
   a += bfloat16(1);
   return a;
 }
References a.
Referenced by Eigen::internal::unary_evaluator< SparseView< ArgType >, IteratorBased >::InnerIterator::incrementToNonZero(), Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IteratorBased, IteratorBased >::InnerIterator::InnerIterator(), Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IteratorBased >::InnerIterator::InnerIterator(), Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IteratorBased, IndexBased >::InnerIterator::InnerIterator(), Eigen::internal::sparse_disjunction_evaluator< XprType, IteratorBased, IteratorBased >::InnerIterator::InnerIterator(), Eigen::internal::sparse_disjunction_evaluator< XprType, IndexBased, IteratorBased >::InnerIterator::InnerIterator(), Eigen::internal::sparse_disjunction_evaluator< XprType, IteratorBased, IndexBased >::InnerIterator::InnerIterator(), Eigen::internal::unary_evaluator< TriangularView< ArgType, Mode >, IteratorBased >::InnerIterator::InnerIterator(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IteratorBased >::InnerVectorInnerIterator::InnerVectorInnerIterator(), Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IteratorBased >::InnerIterator::operator++(), Eigen::internal::unary_evaluator< CwiseUnaryView< ViewOp, ArgType >, IteratorBased >::InnerIterator::operator++(), Eigen::internal::unary_evaluator< TriangularView< ArgType, Mode >, IteratorBased >::InnerIterator::operator++(), and Eigen::internal::unary_evaluator< SparseView< ArgType >, IteratorBased >::InnerIterator::operator++().
operator++() [2/2]
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::operator++ (bfloat16 & a, int)
{
   bfloat16 original_value = a;
   ++a;
   return original_value;
 }
References a.
operator+=()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16& Eigen::bfloat16_impl::operator+= (bfloat16 & a, const bfloat16 & b)
{
   a = bfloat16(float(a) + float(b));
   return a;
 }
References a, and b.
operator-() [1/2]
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::operator- (const bfloat16 & a)
{
   numext::uint16_t x = numext::bit_cast<uint16_t>(a) ^ 0x8000;
   return numext::bit_cast<bfloat16>(x);
 }
References a, and plotDoE::x.
operator-() [2/2]
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::operator- (const bfloat16 & a, const bfloat16 & b)
{
   return bfloat16(float(a) - float(b));
 }
References a, and b.
operator--() [1/2]
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::operator-- (bfloat16 & a)
{
   a -= bfloat16(1);
   return a;
 }
References a.
operator--() [2/2]
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::operator-- (bfloat16 & a, int)
{
   bfloat16 original_value = a;
   --a;
   return original_value;
 }
References a.
operator-=()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16& Eigen::bfloat16_impl::operator-= (bfloat16 & a, const bfloat16 & b)
{
   a = bfloat16(float(a) - float(b));
   return a;
 }
References a, and b.
operator/() [1/2]
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::operator/ (const bfloat16 & a, const bfloat16 & b)
{
   return bfloat16(float(a) / float(b));
 }
References a, and b.
operator/() [2/2]
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::operator/ (const bfloat16 & a, Index b)
{
   return bfloat16(static_cast<float>(a) / static_cast<float>(b));
 }
References a, and b.
operator/=()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16& Eigen::bfloat16_impl::operator/= (bfloat16 & a, const bfloat16 & b)
{
   a = bfloat16(float(a) / float(b));
   return a;
 }
References a, and b.
operator<()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool Eigen::bfloat16_impl::operator< (const bfloat16 & a, const bfloat16 & b)
{
   return float(a) < float(b);
 }
References a, and b.
operator<<()
EIGEN_ALWAYS_INLINE std::ostream& Eigen::bfloat16_impl::operator<< (std::ostream & os, const bfloat16 & v)
{
   os << static_cast<float>(v);
   return os;
 }
References v.
operator<=()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool Eigen::bfloat16_impl::operator<= (const bfloat16 & a, const bfloat16 & b)
{
   return float(a) <= float(b);
 }
References a, and b.
operator==()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool Eigen::bfloat16_impl::operator== (const bfloat16 & a, const bfloat16 & b)
{
   return numext::equal_strict(float(a), float(b));
 }
References a, b, and Eigen::numext::equal_strict().
operator>()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool Eigen::bfloat16_impl::operator> (const bfloat16 & a, const bfloat16 & b)
{
   return float(a) > float(b);
 }
References a, and b.
Referenced by Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator>().
operator>=()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bool Eigen::bfloat16_impl::operator>= (const bfloat16 & a, const bfloat16 & b)
{
   return float(a) >= float(b);
 }
References a, and b.
Referenced by Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator>=().
pow()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::pow (const bfloat16 & a, const bfloat16 & b)
{
   return bfloat16(::powf(float(a), float(b)));
 }
References a, and b.
Referenced by AxisymOscillatingDisk::accel(), units::accUnit(), PolarNSProblem< ELEMENT >::actions_before_solve(), CFDDEMCoupleTest::actionsAfterTimeStep(), oomph::RefineableGmshTetMesh< ELEMENT >::adapt(), oomph::Problem::adaptive_unsteady_newton_solve(), DropletBoundary::addDroplet(), ExactSolution::analytical_outer_unit_normal(), array_generic(), oomph::ImmersedRigidBodyTriangleMeshPolygon::assign_zeta(), CRBond_Bessel::bessik01a(), CRBond_Bessel::bessiknb(), CRBond_Bessel::bessikv(), CRBond_Bessel::bessjy01a(), CRBond_Bessel::bessjynb(), CRBond_Bessel::bessjyv(), Eigen::internal::blueNorm_impl(), Global_Parameters::body_force(), BoundariesSelfTest::BoundariesSelfTest(), ProblemParameters::boundary_d2fluxdt2_1(), ProblemParameters::boundary_dfluxdt_1(), ProblemParameters::boundary_displ_0(), ProblemParameters::boundary_displ_1(), ProblemParameters::boundary_flux_1(), Global_Parameters::boundary_traction(), ProblemParameters::boundary_traction(), oomph::BrickFromTetMesh< ELEMENT >::build_mesh(), Eigen::internal::gemm_class< Scalar, is_unit_inc >::c_update_1count(), Eigen::internal::gemm_class< Scalar, is_unit_inc >::c_update_1pow(), CFDDEMCoupleTest::CalcPhiPAndFz(), oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::calculate_cut_off_viscosity(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_cutoff_viscosity(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_cutoff_viscosity(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_fitting_parameters_of_cubic(), oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_fitting_parameters_of_cubic(), oomph::ComplexDampedJacobi< MATRIX >::calculate_omega(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_zero_shear_viscosity(), HGridOptimiser::calculateDiffWork(), HGridOptimiser::calculateWork(), CRBond_Bessel::cbessik01(), CRBond_Bessel::cbessiknb(), CRBond_Bessel::cbessikv(), CRBond_Bessel::cbessjy01(), CRBond_Bessel::cbessjynb(), CRBond_Bessel::cbessjyva(), oomph::Mesh::check_for_repeated_nodes(), Beam::checkBeamDeflection(), CircularPeriodicBoundary::checkBoundaryAfterParticleMoved(), cholesky(), oomph::ComplexGMRES< MATRIX >::complex_solve_helper(), Eigen::PolynomialSolver< Scalar_, Deg_ >::compute(), Eigen::MatrixPowerAtomic< MatrixType >::compute(), Eigen::MatrixPower< MatrixType >::compute(), Eigen::MatrixPowerAtomic< MatrixType >::compute2x2(), ModalPRefineableQPoissonElement< DIM >::compute_energy_error(), oomph::PRefineableQLinearElasticityElement< DIM >::compute_energy_error(), oomph::PRefineableQPoissonElement< DIM >::compute_energy_error(), ModalPoissonEquations< DIM >::compute_error(), oomph::SpaceTimeNavierStokesEquations< DIM >::compute_error(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::compute_error(), oomph::EulerEquations< DIM >::compute_error(), oomph::ScalarAdvectionEquations< DIM >::compute_error(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::compute_gamma_contribution(), oomph::NavierStokesEquations< DIM >::compute_norm(), oomph::SpaceTimeNavierStokesEquations< DIM >::compute_norm(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::compute_norm(), oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::compute_stabilisation_parameter(), LiquidBridgeBagheriInteraction::computeAdhesionForce(), LiquidBridgeClassicalWilletInteraction::computeAdhesionForce(), LiquidMigrationLSInteraction::computeAdhesionForce(), LiquidMigrationWilletViscousInteraction::computeAdhesionForce(), PSD::computeD50(), CFDDEMCoupleTest::computeExternalForces(), SuperQuadricParticle::computeHessianLabFixed(), ChuteWithPeriodicInflow::computeInternalForces(), BaseCluster::computeInternalStructure(), SinterInteraction::computeNormalForce(), SinterLinInteraction::computeNormalForce(), SuperQuadricParticle::computeShape(), SuperQuadricParticle::computeShapeGradientLabFixed(), sphericalHarmonics::computeSquaredFactorialValues(), ScalingTestInitialConditionsRelax::continueSolve(), oomph::StefanBoltzmannRadiationBase::contribution_to_stefan_boltzmann_radiation(), Multipole::convertMultipoleToLocal(), PSD::convertPdfPhiToPdfMeter(), CurvyChute::createBottom(), CircularPeriodicBoundary::createPeriodicParticle(), Eigen::BDCSVD< MatrixType_, Options_ >::deflation43(), Eigen::BDCSVD< MatrixType_, Options_ >::deflation44(), DenseLM< Scalar >::df(), Bennett5_functor::df(), rat43_functor::df(), HGridOptimiser::diffEndExpectedCellsIntegral(), HGridOptimiser::diffHExpectedCellsIntegralCellNumerator(), HGridOptimiser::diffPdfInt(), HGridOptimiser::diffStartExpectedCellsIntegral(), oomph::DiskTetMeshFacetedSurface::DiskTetMeshFacetedSurface(), MD_demo::DistInt(), Eigen::BDCSVD< MatrixType_, Options_ >::divide(), oomph::OcTree::doc_face_neighbours(), oomph::BinaryTree::doc_neighbours(), oomph::QuadTree::doc_neighbours(), DiskShockWaveProblem< ELEMENT, TIMESTEPPER >::doc_solution(), AirwayReopeningProblem< ELEMENT >::doc_solution(), CantileverProblem< ELEMENT >::doc_solution(), BrethertonProblem< ELEMENT >::doc_solution(), StaticDiskCompressionProblem< ELEMENT >::doc_solution(), ShellProblem< ELEMENT >::doc_solution(), oomph::OcTree::doc_true_edge_neighbours(), oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::WarpedCircularDisk::dwdphi(), ProblemParameters::exact_soln(), Global_Parameters::exact_solution_th(), HGridOptimiser::expectedCellsIntegralCellDenominator(), HGridOptimiser::expectedCellsIntegralCellNumerator(), oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::YoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::PVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::ScaleCoupledElement< ELEMENT >::fill_in_generic_contribution_to_residuals_pvd(), oomph::VolumeCoupledElement< ELEMENT >::fill_in_generic_contribution_to_residuals_pvd(), oomph::AxisymmetricPoroelasticityEquations::fill_in_generic_residual_contribution(), oomph::PolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), oomph::PVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), PerturbationSolution::first_order_veloc_and_pressure(), ProblemParameters::Fluid_body_force(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), foo(), PerturbationSolution::full_soln(), units::fUnit(), oomph::ComplexGMRES< MATRIX >::generate_plane_rotation(), oomph::HelmholtzGMRESMG< MATRIX >::generate_plane_rotation(), Eigen::internal::generic_pow(), NonRefineableBinArray::get_bin(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::get_body_force_spherical_nst(), oomph::MyProblem::get_error_norm(), PlanarWave::get_exact_u(), GlobalParameters::get_exact_u(), TanhSolnForSteadyAxisymAdvectionDiffusion::get_exact_u(), oomph::PressureAdvectionDiffusionValidation::get_exact_u(), oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::get_flux(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableAxisymmetricQTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableLinearisedQTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableQSphericalTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::get_interpolating_node_at_local_coordinate(), oomph::RefineableQTaylorHoodElement< DIM >::get_interpolating_node_at_local_coordinate(), oomph::RefineablePolarTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::get_interpolating_node_at_local_coordinate(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::get_interpolating_node_at_local_coordinate(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::get_interpolating_node_at_local_coordinate(), oomph::RefineablePVDEquationsWithPressure< DIM >::get_mass_matrix_diagonal(), oomph::PVDEquationsWithPressure< DIM >::get_mass_matrix_diagonal(), oomph::KirchhoffLoveBeamEquations::get_normal(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::NavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::RefineableNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::SpaceTimeNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::PVDEquationsBase< DIM >::get_principal_stress(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::get_reaction_adv_diff_react(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::get_reaction_adv_diff_react(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::get_reaction_deriv_adv_diff_react(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::get_reaction_deriv_adv_diff_react(), oomph::SegregatableFSIProblem::get_solid_change(), SinSolution::get_source(), TanhSolnForUnsteadyHeat::get_source(), TanhSolnForPoisson::get_source(), GlobalParameters::get_source(), ExactSolution::get_source_for_unsteady_heat_validation(), oomph::PVDEquationsBase< DIM >::get_strain(), oomph::PVDEquations< DIM >::get_stress(), oomph::PVDEquationsWithPressure< DIM >::get_stress(), oomph::StreamfunctionProblem::get_vels(), HertzianViscoelasticNormalSpecies::getCollisionTime(), Coil::getDistanceAndNormal(), Combtooth::getDistanceAndNormal(), CylindricalWall::getDistanceAndNormal(), InfiniteWallWithHole::getDistanceAndNormal(), ParabolaChute::getDistanceAndNormal(), SineWall::getDistanceAndNormal(), VChute::getDistanceAndNormal(), InfiniteWall::getFurthestPointSuperQuadric(), LiquidMigrationLSInteraction::getHalfFillingAngle(), InfiniteWallWithHole::getHoleDistance(), VolumeCoupling::getInvCoupledMassPerTime(), BaseInteraction::getOverlapVolume(), LiquidMigrationLSInteraction::getRuptureDistance(), PSDContinuous::getVolumetricMean(), PSD::getVolumetricMeanRadius(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_helmholtz(), Global_parameters::grad_f1(), Global_parameters::grad_f2(), Global_Parameters::grad_velocity_singularity1(), Global_Parameters::grad_velocity_singularity2(), GranuDrum::GranuDrum(), oomph::OcTree::gteq_edge_neighbour(), oomph::BinaryTree::gteq_edge_neighbour(), oomph::QuadTree::gteq_edge_neighbour(), oomph::OcTree::gteq_face_neighbour(), oomph::OcTree::gteq_true_edge_neighbour(), oomph::Node::hang_code(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation(), MercuryBase::hGridRebuild(), HGridOptimiser::histNumberParticlesPerCell(), HstopCurve(), GlobalParameters::incoming_sb_inside(), GlobalParameters::incoming_sb_outside(), HGridOptimiser::initialise(), HGridOptimiser::initialisePolyFunc(), Eigen::internal::TensorBlockMapper< NumDims, Layout, IndexType >::InitializeBlockDimensions(), Eigen::internal::gemm_class< Scalar, is_unit_inc >::innerkernel_1pow(), CFDDEMCoupleTest::itterateL(), PerturbationSolution::leading_order_veloc_and_pressure(), TwoDDGProblem< ELEMENT >::limit(), lpNorm(), main(), BaseCluster::makeDataAnalysis(), Eigen::internal::matrix_log_compute_big(), oomph::HelmholtzMGPreconditioner< DIM >::maximum_edge_width(), NonRefineableBinArray::min_distance(), Eigen::internal::minres(), mixingtypes(), sparseGaussianTest< Scalar >::model(), oomph::StreamfunctionProblem::my_output(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::ninterpolating_node(), oomph::RefineableQTaylorHoodElement< DIM >::ninterpolating_node(), oomph::RefineablePolarTaylorHoodElement::ninterpolating_node(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::ninterpolating_node(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::ninterpolating_node(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::ninterpolating_node(), oomph::QElementBase::nnode_on_face(), oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::npres_nst(), oomph::QTaylorHoodElement< DIM >::npres_nst(), oomph::QTaylorHoodSpaceTimeElement< DIM >::npres_nst(), oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::npres_nst(), oomph::QPVDElementWithContinuousPressure< DIM >::npres_solid(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::oc_hang_helper(), Eigen::internal::scalar_unary_pow_op< Scalar, ExponentScalar, IsBaseInteger, IsExponentInteger, IsBaseComplex, IsExponentComplex >::operator()(), Eigen::internal::scalar_unary_pow_op< Scalar, ExponentScalar, false, false, false, false >::operator()(), sparseGaussianTest< Scalar >::operator()(), Bennett5_functor::operator()(), rat43_functor::operator()(), oomph::HermiteBeamElement::output(), oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output(), oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::output_stefan_boltzmann_radiation(), oomph::SarahBL::P_sarah(), SarahBL::P_sarah(), packetmath(), packetmath_real(), HertzianBSHPInteractionTwoParticleElasticCollision::padeCoefficientOfRestitution(), pblueNorm(), HGridOptimiser::pdfIntCell(), NavierStokesProblem< ELEMENT >::pin_redundant_temporal_nodes(), planes(), oomph::SegregatableFSIProblem::pointwise_aitken_extrapolate(), PoissonProblem< ELEMENT >::PoissonProblem(), OscillatingWall::position(), AxisymOscillatingDisk::position(), oomph::BandedBlockTriangularPreconditioner< MATRIX >::preconditioner_solve(), TanhSolnForSteadyAxisymAdvectionDiffusion::prescribed_alpha_on_fixed_r_boundary(), TanhSolnForSteadyAxisymAdvectionDiffusion::prescribed_beta_on_fixed_r_boundary(), ExactSolution::prescribed_flux_for_unsteady_heat_validation(), TanhSolnForAdvectionDiffusion::prescribed_flux_on_fixed_x_boundary(), TanhSolnForPoisson::prescribed_flux_on_fixed_x_boundary(), SolnForPoisson::prescribed_flux_on_fixed_x_boundary(), GlobalParameters::prescribed_flux_on_fixed_y_boundary(), TanhSolnForUnsteadyHeat::prescribed_flux_on_fixed_y_boundary(), GlobalParameters::prescribed_incoming_flux(), Global_Parameters::pressure_load(), oomph::PseudoBucklingRing::PseudoBucklingRing(), QFaceTestProblem< ELEMENT >::QFaceTestProblem(), oomph::QHermiteElement< DIM >::QHermiteElement(), qr_invertible(), qr_kahan_matrix(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::quad_hang_helper(), MD_demo::RandomRadius(), oomph::TreeBasedRefineableMeshBase::refine_as_in_reference_mesh(), RefineablePoissonProblem< ELEMENT >::RefineablePoissonProblem(), units::rhoUnit(), CircularPeriodicBoundary::rotateParticle(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), helpers::round(), ref_pow< Base, Exponent, ExpIsInteger >::run(), ref_pow< Base, Exponent, true >::run(), Eigen::internal::matrix_exp_computeUV< MatrixType, float >::run(), Eigen::internal::matrix_exp_computeUV< MatrixType, double >::run(), Eigen::internal::matrix_exp_computeUV< MatrixType, long double >::run(), Eigen::internal::lpNorm_selector< Derived, p >::run(), TanhSolnForMultiPoisson::scalar_source(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::scale_basis(), oomph::TRaviartThomasDarcyElement< ORDER >::scale_basis(), oomph::TPoroelasticityElement< ORDER >::scale_basis(), PSD::scaleParticleSizeAuto(), PerturbationSolution::second_order_veloc_and_pressure(), oomph::SelfStartingBDF2::set_error_weights_bdf2(), RefineableOneDAdvectionDiffusionReactionProblem< ELEMENT >::set_initial_condition(), AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_initial_conditions(), Global_Physical_Variables::set_params(), Chutebelt::set_particle_numbers(), FlowRule::set_Polydispersity(), oomph::EBDF3::set_weights(), SuperQuadricParticle::setBoundingRadius(), LiquidMigrationLSSpecies::setInteractionDistance(), DropletBoundary::setLiquidFilmVolumeMaxFractionFromRadiusFraction(), VolumeCoupling::setNodalWeightOnCubicMesh(), FlowRule::setPolydispersity(), BaseCluster::setRadii(), SinterNormalSpecies::setSinterForceAndTime(), SegregationPeriodic::setSpeciesProperties(), MercuryProblem::setSpeciesProperties(), oomph::TetMeshBase::setup_boundary_coordinates(), oomph::XdaTetMesh< ELEMENT >::setup_boundary_coordinates(), MercuryLogo::setupInitialConditions(), Binary::setupInitialConditions(), my_problem::setupInitialConditions(), FreeCooling3DDemoProblem::setupInitialConditions(), FreeCooling3DinWallsDemo::setupInitialConditions(), HeaterBoundaryTest::setupInitialConditions(), SegregationPeriodic::setupInitialConditions(), Chutebelt::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), DrumRot::setupInitialConditions(), RotatingDrum::setupInitialConditions(), ScalingTestInitialConditionsRelax::setupInitialConditions(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), MD_demo::setupInitialConditions(), BaseCluster::setupInitialConditions(), CoupledBeam::setupOomph(), Siegen::Siegen(), units::sigUnit(), oomph::TetMeshBase::snap_nodes_onto_geometric_objects(), oomph::TetMeshBase::snap_to_quadratic_surface(), ProblemParameters::Solid_body_force(), ComplexHarmonicProblem< ELEMENT, EIGEN_SOLVER >::solve(), HarmonicProblem< ELEMENT, EIGEN_SOLVER >::solve(), ShellProblem< ELEMENT >::solve(), oomph::HelmholtzGMRESMG< MATRIX >::solve_helper(), oomph::HelmholtzFGMRESMG< MATRIX >::solve_helper(), Global_parameters::source_function(), TanhSolnForPoisson::source_function(), SolnForPoisson::source_function(), oomph::PressureAdvectionDiffusionValidation::source_function(), TanhSolnForAdvectionDiffusion::source_function(), TanhSolnForSteadyAxisymAdvectionDiffusion::source_function(), Eigen::MatrixPower< MatrixType >::split(), svd_fill_random(), test2dRotation(), test3dRotation(), test_basic_functions(), test_execute_reverse_rvalue(), test_nnls_random_problem(), testGeneral(), testVectorType(), TFaceTestProblem< ELEMENT >::TFaceTestProblem(), ActivatorInhibitorProblem< ELEMENT >::timestep(), oomph::SarahBL::Total_Diss_lead_sarah(), SarahBL::Total_Diss_lead_sarah(), LocalExpansion::translateLocalExpansion(), Multipole::TranslateMultipoleExpansionTo(), TriangleFaceTestProblem< ELEMENT >::TriangleFaceTestProblem(), oomph::TriangleMeshClosedCurve::TriangleMeshClosedCurve(), oomph::TriangleMeshOpenCurve::TriangleMeshOpenCurve(), oomph::TriangleMeshPolygon::TriangleMeshPolygon(), oomph::SarahBL::U_sarah(), SarahBL::U_sarah(), update_latest_fixed_point_iteration_guess_for_strain_rate(), oomph::SarahBL::V_sarah(), SarahBL::V_sarah(), AxisymOscillatingDisk::veloc(), MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::verify_mortared_nodes_coincide(), oomph::PowerLawBerEngRegConstitutiveEquation< DIM >::viscosity(), oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >::viscosity(), oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::viscosity(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity(), oomph::HerschelBulkleyPapRegConstitutiveEquation< DIM >::viscosity(), oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::viscosity(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity(), oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity(), oomph::VorticitySmootherElement< ELEMENT >::vorticity_error_squared(), oomph::WarpedCircularDisk::w(), oomph::PiecewiseGauss< DIM, NPTS_1D >::weight(), oomph::Gauss_Rescaled< DIM, NPTS_1D >::weight(), oomph::GmshTetScaffoldMesh::write_geo_file(), and CFile::writeP4P().
raw_bfloat16_as_uint16()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR numext::uint16_t Eigen::bfloat16_impl::raw_bfloat16_as_uint16 (const __bfloat16_raw & bf)
{
 #if defined(EIGEN_USE_HIP_BF16)
   return bf.data;
 #else
   return bf.value;
 #endif
 }
References Eigen::bfloat16_impl::__bfloat16_raw::value.
Referenced by Eigen::numext::bit_cast< uint16_t, Eigen::bfloat16 >().
raw_uint16_to_bfloat16() [1/2]
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR __bfloat16_raw Eigen::bfloat16_impl::raw_uint16_to_bfloat16 (numext::uint16_t value)
{
 #if defined(EIGEN_USE_HIP_BF16)
   __bfloat16_raw bf;
   bf.data = value;
   return bf;
 #else
   return __bfloat16_raw(value);
 #endif
 }
References Eigen::value.
raw_uint16_to_bfloat16() [2/2]
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR __bfloat16_raw Eigen::bfloat16_impl::raw_uint16_to_bfloat16 (unsigned short value)
Referenced by Eigen::numext::bit_cast< Eigen::bfloat16, uint16_t >(), Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< typename >::denorm_min(), Eigen::NumTraits< Eigen::bfloat16 >::dummy_precision(), Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< typename >::epsilon(), Eigen::NumTraits< Eigen::bfloat16 >::epsilon(), Eigen::NumTraits< Eigen::bfloat16 >::highest(), Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< typename >::infinity(), Eigen::NumTraits< Eigen::bfloat16 >::infinity(), Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< typename >::lowest(), Eigen::NumTraits< Eigen::bfloat16 >::lowest(), Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< typename >::max(), Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< typename >::min(), Eigen::internal::pfirst(), Eigen::internal::pfirst< Packet4bf >(), Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< typename >::quiet_NaN(), Eigen::NumTraits< Eigen::bfloat16 >::quiet_NaN(), Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< typename >::round_error(), and Eigen::bfloat16_impl::numeric_limits_bfloat16_impl< typename >::signaling_NaN().
rint()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::rint (const bfloat16 & a)
 { return bfloat16(::rintf(float(a))); }
References a.
Referenced by array_real(), packetmath_real(), and unary_ops_test().
round()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::round (const bfloat16 & a)
 { return bfloat16(::roundf(float(a))); }
References a.
Referenced by SpeciesTest::actionsAfterSolve(), Vreman::add_particles(), array_real(), ChuteWithContraction::ChuteWithContraction(), ChuteWithPeriodicInflowAndContraction::ChuteWithPeriodicInflowAndContraction(), VariableBottom::createBottom(), HorizontalScrew::getDistanceAndNormal(), Coil::getDistanceAndNormal(), Screw::getDistanceAndNormalLabCoordinates(), GranuHeap::GranuHeap(), packetmath_real(), plotResults::plotObservables(), PointIsAboveCurve(), FileReader::read(), Loadstatistics::read_restart(), DPMBase::readParAndIniFiles(), helpers::round(), AngleOfRepose::run(), run_impedance_tube(), run_navier_stokes_outflow(), run_prescribed_flux(), run_prescribed_pressure_gradient(), VariableBottom::set_chute_parameters(), AngleOfRepose::set_study(), SilbertPeriodic::set_study(), ClosedCSCStats::setupInitialConditions(), CSCStats::setupInitialConditions(), BaseCluster::setupInitialConditions(), ScaleCoupledBeam::setupOomph(), WearableNurbsWall::storeDebris(), test_float_rounding(), helpers::toString(), and unary_ops_test().
sin()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::sin (const bfloat16 & a)
 { return bfloat16(::sinf(float(a))); }
References a.
sinh()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::sinh (const bfloat16 & a)
 { return bfloat16(::sinhf(float(a))); }
References a.
Referenced by array_complex(), array_real(), check_hyperbolic_functions(), Eigen::MatrixPowerAtomic< MatrixType >::computeSuperDiag(), Eigen::internal::psinh(), Eigen::internal::stem_function_cosh(), Eigen::internal::stem_function_sinh(), test2dHyperbolicRotation(), and unary_ops_test().
sqrt()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::sqrt (const bfloat16 & a)
 { return bfloat16(::sqrtf(float(a))); }
References a.
tan()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::tan (const bfloat16 & a)
 { return bfloat16(::tanf(float(a))); }
References a.
Referenced by Jeffery_Solution::angle(), array_complex(), array_real(), BoundariesSelfTest::BoundariesSelfTest(), LiquidMigrationLSInteraction::computeAdhesionForce(), SinterLinInteraction::computeNormalForce(), oomph::SphericalNavierStokesEquations::cot(), SegregationWithHopper::create_inflow_particle(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), ArcTanSolnForPoisson::get_source(), VChute::getDistanceAndNormal(), SilbertHstop::IsAboveCurve(), LeesEdwardsDemo::LeesEdwardsDemo(), main(), packetmath_real(), GeneralCircle::position(), WarpedLine::position(), Eigen::internal::ptan(), SilbertHstop::solve_analytic(), test_trigonometric_functions(), TimeDependentPeriodicBoundary3DSelfTest::TimeDependentPeriodicBoundary3DSelfTest(), TimeDependentPeriodicBoundaryTest::TimeDependentPeriodicBoundaryTest(), TwoDDGMesh< ELEMENT >::TwoDDGMesh(), BiharmonicTestFunctions2::u_E(), BiharmonicTestFunctions2::u_N(), BiharmonicTestFunctions2::u_W(), unary_ops_test(), Camera::updateProjectionMatrix(), and WarpedLine::y_c().
tanh()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::tanh (const bfloat16 & a)
 { return bfloat16(::tanhf(float(a))); }
References a.
Referenced by PressureWaveFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_before_implicit_timestep(), array_complex(), array_real(), oomph::SolarRadiationBase::atmospheric_radiation(), check_hyperbolic_functions(), TanhSolnForLinearWave::exact_d2udt2(), TanhSolnForLinearWave::exact_u(), GlobalPhysicalParameters::get_boundary_values(), GlobalParameters::get_exact_u(), TanhSolnForUnsteadyHeat::get_exact_u(), TanhSolnForAdvectionDiffusion::get_exact_u(), TanhSolnForPoisson::get_exact_u(), SolnForPoisson::get_exact_u(), TanhSolnForSteadyAxisymAdvectionDiffusion::get_exact_u(), TanhSolnForUnsteadyHeat::get_source(), GlobalParameters::get_source(), packetmath_real(), TanhSolnForSteadyAxisymAdvectionDiffusion::prescribed_alpha_on_fixed_r_boundary(), TanhSolnForSteadyAxisymAdvectionDiffusion::prescribed_beta_on_fixed_r_boundary(), TanhSolnForAdvectionDiffusion::prescribed_flux_on_fixed_x_boundary(), TanhSolnForPoisson::prescribed_flux_on_fixed_x_boundary(), SolnForPoisson::prescribed_flux_on_fixed_x_boundary(), GlobalParameters::prescribed_flux_on_fixed_y_boundary(), TanhSolnForUnsteadyHeat::prescribed_flux_on_fixed_y_boundary(), ProblemParameters::pressure_magnitude(), Eigen::internal::ptanh(), TanhSolnForMultiPoisson::scalar_soln(), TanhSolnForMultiPoisson::scalar_source(), TanhSolnForPoisson::source_function(), SolnForPoisson::source_function(), TanhSolnForAdvectionDiffusion::source_function(), TanhSolnForSteadyAxisymAdvectionDiffusion::source_function(), GlobalParameters::step_position(), TanhSolnForUnsteadyHeat::step_position(), TanhSolnForAdvectionDiffusion::tanh_profile(), unary_ops_test(), and oomph::TanhProfileConstitutiveEquation< DIM >::viscosity().
trunc()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC bfloat16 Eigen::bfloat16_impl::trunc (const bfloat16 & a)
 { return bfloat16(::truncf(float(a))); }
References a.
Referenced by array_real(), packetmath_real(), and unary_ops_test().
truncate_to_bfloat16()
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC __bfloat16_raw Eigen::bfloat16_impl::truncate_to_bfloat16 (const float v)
{
 #if defined(EIGEN_USE_HIP_BF16)
   return __bfloat16_raw(__bfloat16_raw::round_to_bfloat16(v, __bfloat16_raw::truncate));
 #else
   __bfloat16_raw output;
   if (numext::isnan EIGEN_NOT_A_MACRO(v)) {
     output.value = std::signbit(v) ? 0xFFC0 : 0x7FC0;
     return output;
   }
   output.value = static_cast<numext::uint16_t>(numext::bit_cast<numext::uint32_t>(v) >> 16);
   return output;
 #endif
 }
References EIGEN_NOT_A_MACRO, Eigen::numext::isnan(), output(), Eigen::numext::signbit(), and v.