MercuryDPM: ChuteInsertionBoundary Class Reference
ChuteInsertionBoundary Class Reference
Used for modeling chute inflow. Inherits from InsertionBoundary.
#include <ChuteInsertionBoundary.h>
Public Member Functions
ChuteInsertionBoundary ()
Default constructor.
ChuteInsertionBoundary (const ChuteInsertionBoundary &other)
Copy constructor.
ChuteInsertionBoundary * copy () const override
Copy method; creates a copy on the heap.
void set (std::vector< BaseParticle * > particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, double fixedParticleRadius, double inflowVelocity, double inflowVelocityVariance)
Sets all boundary properties at once.
void set (BaseParticle *particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, double fixedParticleRadius, double inflowVelocity, double inflowVelocityVariance)
Sets all boundary properties at once.
void set (BaseParticle *particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, Mdouble rMin, Mdouble rMax, double fixedParticleRadius, double inflowVelocity, double inflowVelocityVariance)
old style set function which assumes a uniform psd.
void placeParticle (BaseParticle *p, RNG &random) override
void read (std::istream &is) override
reads boundary properties from istream
void write (std::ostream &os) const override
writes boundary properties to ostream
std::string getName () const override
Returns the name of the object.
Public Member Functions inherited from InsertionBoundary
InsertionBoundary ()
InsertionBoundary (const InsertionBoundary &other)
Copy constructor (with deep copy)
~InsertionBoundary () override
Destructor: delete the particle that has to be copied at every insertion.
virtual BaseParticle * generateParticle (RNG &random)
Sets the properties of the InsertionBoundary for a single particle type ‍/ virtual void set(BaseParticle* particleToCopy, unsigned int maxFailed, Vec3D velMin, Vec3D velMax, double radMin, double radMax)=0;.
virtual void shiftBoundary (Vec3D shift)
virtual function that shifts the boundary.
virtual void rotateBoundary (Vec3D angle)
virtual function that rotates the boundary.
void checkBoundaryBeforeTimeStep (DPMBase *md) override
Fills the boundary with particles.
void insertParticles (DPMBase *md)
Fill a certain domain with particles.
unsigned int getNumberOfParticlesInserted () const
Gets the number of particles inserted by the boundary.
Mdouble getMassOfParticlesInserted () const
Gets the mass of particles inserted by the boundary.
Mdouble getVolumeOfParticlesInserted () const
Gets the volume of particles inserted by the boundary.
void reset ()
resets particle property counter variables.
void activate ()
Turns on the InsertionBoundary.
void deactivate ()
Turns off the InsertionBoundary.
bool isActivated ()
Returns whether the InsertionBoundary is activated.
unsigned int getMaxFailed () const
Gets the number of times that the boundary may fail to insert a particle.
void setParticleToCopy (std::vector< BaseParticle * > particleToCopy)
Sets multiple different particles that will be inserted through the insertion boundary.
void setParticleToCopy (BaseParticle *particleToCopy)
Sets the particle that will be inserted through the insertion boundary.
std::vector< BaseParticle * > getParticleToCopy ()
Gets the particles that will be inserted through the insertion boundary.
void read (std::istream &is) override
Reads the boundary's id_ and maxFailed_.
void write (std::ostream &os) const override
Writes the boundary's id_ and maxFailed_.
Mdouble getVolumeFlowRate () const
Gets the volume flow rate of the insertion routine.
void setVolumeFlowRate (Mdouble volumeFlowRate)
Sets the volume flow rate of the insertion routine.
Mdouble getInitialVolume () const
Gets the initialVolume() .
void setInitialVolume (Mdouble initialVolume)
Gets the Volume which should be inserted by the insertion routine.
void setPSD (const PSD psd)
Sets the range of particle radii that may be generated from a user defined PSD.
void setPSD (std::vector< PSD > psd, std::vector< Mdouble > probability)
Sets the ranges of particle radii that may be generated from user defined PSDs.
std::vector< PSD > getPSD ()
Gets the particle size distributions set by the user.
void setVariableVolumeFlowRate (const std::vector< Mdouble > &variableCumulativeVolumeFlowRate, Mdouble samplingInterval)
Sets a variable volume flow rate.
bool insertParticle (Mdouble time)
Checks the inserted total volume and returns if a particle is still allowed to be inserted.
bool getCheckParticleForInteraction () const
Gets the variable that checks if a particle has an interaction.
void setCheckParticleForInteraction (bool checkParticleForInteraction)
Sets the variable that checks if a particle has an interaction.
void setManualInsertion (bool manualInsertion)
Set the flag for a manual PSD insertion routine.
Public Member Functions inherited from BaseBoundary
BaseBoundary ()
default constructor.
BaseBoundary (const BaseBoundary &b)
copy constructor
~BaseBoundary () override
destructor
virtual void createPeriodicParticle (BaseParticle *p UNUSED, ParticleHandler &pH UNUSED)
Creates a periodic particle in case of periodic boundaries in serial build.
virtual void createPeriodicParticles (ParticleHandler &pH UNUSED)
Creates periodic copies of given particle in case of periodic boundaries.
virtual void checkBoundaryAfterParticlesMove (ParticleHandler &pH)
Virtual function that does things to particles, each time step after particles have moved.
virtual void actionsBeforeTimeLoop ()
Virtual function that does something after DPMBase::setupInitialConditions but before the first time step.
virtual void modifyGhostAfterCreation (BaseParticle *particle, int i)
virtual void writeVTK (std::fstream &file)
void setHandler (BoundaryHandler *handler)
Sets the boundary's BoundaryHandler.
BoundaryHandler * getHandler () const
Returns the boundary's BoundaryHandler.
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
Vec3D posMin_
The two extremal corners of the cuboidal insertion boundary.
Vec3D posMax_
double fixedParticleRadius_
radius of the fixed bottom particles, mean particle velocity in X-direction, and allowed maximum randomly added/subtracted velocities in all three directions while generating particles (expressed as % of inflowVelocity_). NB: see also documentation of ChuteInsertionBoundary::generateParticle().
double inflowVelocity_
double inflowVelocityVariance_
Additional Inherited Members
Public Attributes inherited from InsertionBoundary
std::vector< BaseParticle * > particleToCopy_
read Distribution class from file. ‍/ friend std::istream& operator>>(std::istream& is, InsertionBoundary::Distribution& type);
unsigned int maxFailed_
Number of times that the wall may fail to insert a particle.
unsigned int numberOfParticlesInserted_
Number of particles that are already inserted.
Mdouble massInserted_
Total mass of particles inserted.
Mdouble volumeInserted_
Total volume of particles inserted.
bool isActivated_
The InsertionBoundary is activated by default. If the InsertionBoundary is deactivated, then it introduces no particles (useful for trying to maintain a certain insertion rate).
Mdouble volumeFlowRate_
Mdouble initialVolume_
std::vector< Mdouble > variableCumulativeVolumeFlowRate_
Mdouble samplingInterval_
bool checkParticleForInteraction_
Checks if a particle has an interaction with a wall or other particles.
std::vector< PSD > particleSizeDistributionVector_
Defines a particle size distribution as an object of the PSD class; if particleSizeDistributionVector_ is empty, distribution_ is used instead.
Vec3D velMin_
Minimum and maximum velocity of the particles to be inserted.
Vec3D velMax_
bool isManuallyInserting_
A flag to enable a top-down class-by-class manual insertion of a PSD; default is FALSE.
std::vector< Mdouble > probability_
vector of probabilities in range [0,1] which determine the mixing ratio of partice size distributions.
int chosenSpecies_
stores the chosen species for each timestep.
BaseParticle * p0 = nullptr
pointer to the next particle that should be inserted (needs to be stored across time steps).
Detailed Description
Used for modeling chute inflow. Inherits from InsertionBoundary.
Constructor & Destructor Documentation
ChuteInsertionBoundary() [1/2]
ChuteInsertionBoundary::ChuteInsertionBoundary ()
Default constructor.
Default constructor. Initiates all properties with 0 value.
                                                : InsertionBoundary()
 {
     posMax_ = Vec3D(0.0, 0.0, 0.0);
     posMin_ = Vec3D(0.0, 0.0, 0.0);
     fixedParticleRadius_ = 0.0;
     inflowVelocity_ = 0.0;
     inflowVelocityVariance_ = 0.0;
 }
References fixedParticleRadius_, inflowVelocity_, inflowVelocityVariance_, posMax_, and posMin_.
Referenced by copy().
ChuteInsertionBoundary() [2/2]
ChuteInsertionBoundary::ChuteInsertionBoundary (const ChuteInsertionBoundary & other)
Copy constructor.
Copy constructor. Calls InsertionBoundary parent copy constructor.
         : InsertionBoundary(other)
 {
     posMax_ = other.posMax_;
     posMin_ = other.posMin_;
     fixedParticleRadius_ = other.fixedParticleRadius_;
     inflowVelocity_ = other.inflowVelocity_;
     inflowVelocityVariance_ = other.inflowVelocityVariance_;
 }
References fixedParticleRadius_, inflowVelocity_, inflowVelocityVariance_, posMax_, and posMin_.
Member Function Documentation
copy()
ChuteInsertionBoundary * ChuteInsertionBoundary::copy () const override virtual
Copy method; creates a copy on the heap.
Copy method. Creates a copy on the heap.
Returns
Pointer to the copy.
Implements BaseBoundary.
 {
 #ifdef DEBUG_CONSTRUCTOR
     std::cout << "ChuteInsertionBoundary::copy() const finished" << std::endl;
 #endif
     return new ChuteInsertionBoundary(*this);
 }
References ChuteInsertionBoundary().
getName()
std::string ChuteInsertionBoundary::getName () const override virtual
Returns the name of the object.
Returns the name of the object class
Returns
the object's class' name, i.e. 'ChuteInsertionBoundary'
Implements BaseObject.
 {
     return "ChuteInsertionBoundary";
 }
placeParticle()
void ChuteInsertionBoundary::placeParticle (BaseParticle * p, RNG & random) override virtual
place a particle within the boundary with random radius, position and velocity (within the allowed intervals). Notable properties:
The minimal Z-position is fixedParticleRadius_ (the radius of the particles fixed at the bottom) above the minimal Z-value of the boundary
The particles have an mean velocity of inflowVelocity_ in the X-direction. Furthermore, each particle has a velocity added in all three directions, based on a given inflowVelocityVariance_, which is expressed as a percentage of the inflowVelocity_.
Parameters
[in] random a random number generator
Returns
pointer to the generated particle
Todo:
change to driver level (ask Thomas)
Implements InsertionBoundary.
 {
     Vec3D position, velocity;
     position.X = posMin_.X + p->getRadius();
 //    if (mathsFunc::isEqual(posMax_.Y - posMin_.Y, 2.0 * radMax_, 1e-10))
 //    {
 //        position.Y = posMin_.Y + p->getRadius();
 //    }
     position.Y = random.getRandomNumber(posMin_.Y - p->getRadius(), posMax_.Y + p->getRadius());
     position.Z = random.getRandomNumber(posMin_.Z - p->getRadius(), posMax_.Z + p->getRadius() + fixedParticleRadius_);
     // The velocity components are first stored in a Vec3D, because if you pass them
     // directly into setVelocity the compiler is allowed to change the order in
     // which the numbers are generated
     velocity.X = inflowVelocity_ * random.getRandomNumber(-inflowVelocityVariance_, inflowVelocityVariance_) +
                  inflowVelocity_;
     velocity.Y = inflowVelocity_ * random.getRandomNumber(-inflowVelocityVariance_, inflowVelocityVariance_);
     velocity.Z = inflowVelocity_ * random.getRandomNumber(-inflowVelocityVariance_, inflowVelocityVariance_);
     p->setPosition(position);
     p->setVelocity(velocity);
 }
References fixedParticleRadius_, RNG::getRandomNumber(), inflowVelocity_, inflowVelocityVariance_, p, posMax_, posMin_, Jeffery_Solution::velocity(), Vec3D::X, Vec3D::Y, and Vec3D::Z.
read()
void ChuteInsertionBoundary::read (std::istream & is) override virtual
reads boundary properties from istream
Reads the boundary properties from an istream
Parameters
[in,out] is the istream
Implements BaseBoundary.
 {
     InsertionBoundary::read(is);
     std::string dummy;
     is >> dummy >> posMin_
        >> dummy >> posMax_
        >> dummy >> fixedParticleRadius_
        >> dummy >> inflowVelocity_
        >> dummy >> inflowVelocityVariance_;
 }
References fixedParticleRadius_, inflowVelocity_, inflowVelocityVariance_, posMax_, posMin_, InsertionBoundary::read(), and oomph::Global_string_for_annotation::string().
set() [1/3]
void ChuteInsertionBoundary::set (BaseParticle * particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, double fixedParticleRadius, double inflowVelocity, double inflowVelocityVariance)
Sets all boundary properties at once.
Sets all the properties of the chute insertion boundary.
Parameters
[in] particleToCopy Pointer to the BaseParticle which is used as a basis for the particles to be inserted
[in] maxFailed The maximum number of times the insertion of a particle may be tried and failed before the insertion of particles is considered done. NB: this property is used in the parent's InsertionBoundary::checkBoundaryBeforeTimeStep().
[in] posMin First defining corner of the chute insertion boundary
[in] posMax Second defining corner of the chute insertion boundary
[in] fixedParticleRadius radius of the fixed bottom (i.e., positioned at the minimal Z-position) particles
[in] inflowVelocity the mean particle velocity, which is in the X-direction
[in] inflowVelocityVariance value of minimum (minus ~) and maximum added velocities which are added to the given mean in each of the three dimensions. Expressed as a percentage of inflowVelocity_. See also the documentation of ChuteInsertionBoundary::generateParticle().
 {
     setParticleToCopy(particleToCopy);
     posMin_ = posMin;
     posMax_ = posMax;
     maxFailed_ = maxFailed;
     fixedParticleRadius_ = fixedParticleRadius;
     inflowVelocity_ = inflowVelocity;
     inflowVelocityVariance_ = inflowVelocityVariance;
 }
References fixedParticleRadius_, inflowVelocity_, inflowVelocityVariance_, InsertionBoundary::maxFailed_, posMax_, posMin_, and InsertionBoundary::setParticleToCopy().
set() [2/3]
void ChuteInsertionBoundary::set (BaseParticle * particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, Mdouble rMin, Mdouble rMax, double fixedParticleRadius, double inflowVelocity, double inflowVelocityVariance)
old style set function which assumes a uniform psd.
old style set function which also assumes a uniform psd. Note if you want a specific PSD do not use but this is quicker for a uniform in size PSD
 {
     PSD uniformPSD;
     uniformPSD.setDistributionUniform(rMin, rMax, 2);
     setPSD(uniformPSD);
     set(particleToCopy, maxFailed, posMin, posMax, fixedParticleRadius, inflowVelocity, inflowVelocityVariance);
 }
References set(), PSD::setDistributionUniform(), and InsertionBoundary::setPSD().
set() [3/3]
void ChuteInsertionBoundary::set (std::vector< BaseParticle * > particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, double fixedParticleRadius, double inflowVelocity, double inflowVelocityVariance)
Sets all boundary properties at once.
Sets all the properties of the chute insertion boundary.
Parameters
[in] particleToCopy vector of pointers to the BaseParticles which are used as a basis for the particles to be inserted
[in] maxFailed The maximum number of times the insertion of a particle may be tried and failed before the insertion of particles is considered done. NB: this property is used in the parent's InsertionBoundary::checkBoundaryBeforeTimeStep().
[in] posMin First defining corner of the chute insertion boundary
[in] posMax Second defining corner of the chute insertion boundary
[in] fixedParticleRadius radius of the fixed bottom (i.e., positioned at the minimal Z-position) particles
[in] inflowVelocity the mean particle velocity, which is in the X-direction
[in] inflowVelocityVariance value of minimum (minus ~) and maximum added velocities which are added to the given mean in each of the three dimensions. Expressed as a percentage of inflowVelocity_. See also the documentation of ChuteInsertionBoundary::generateParticle().
 {
     setParticleToCopy(particleToCopy);
     posMin_ = posMin;
     posMax_ = posMax;
     maxFailed_ = maxFailed;
     fixedParticleRadius_ = fixedParticleRadius;
     inflowVelocity_ = inflowVelocity;
     inflowVelocityVariance_ = inflowVelocityVariance;
 }
References fixedParticleRadius_, inflowVelocity_, inflowVelocityVariance_, InsertionBoundary::maxFailed_, posMax_, posMin_, and InsertionBoundary::setParticleToCopy().
Referenced by set(), FullRestartTest::setupInitialConditions(), and Chute::setupInitialConditions().
write()
void ChuteInsertionBoundary::write (std::ostream & os) const override virtual
writes boundary properties to ostream
Writes boundary's properties to an ostream
Parameters
[in] os the ostream
Implements BaseBoundary.
 {
     InsertionBoundary::write(os);
     os << " posMin " << posMin_
        << " posMax " << posMax_
        << " fixedParticleRadius " << fixedParticleRadius_
        << " inflowVelocity " << inflowVelocity_
        << " inflowVelocityVariance " << inflowVelocityVariance_;
 }
References fixedParticleRadius_, inflowVelocity_, inflowVelocityVariance_, posMax_, posMin_, and InsertionBoundary::write().
Member Data Documentation
fixedParticleRadius_
double ChuteInsertionBoundary::fixedParticleRadius_ private
radius of the fixed bottom particles, mean particle velocity in X-direction, and allowed maximum randomly added/subtracted velocities in all three directions while generating particles (expressed as % of inflowVelocity_). NB: see also documentation of ChuteInsertionBoundary::generateParticle().
Referenced by ChuteInsertionBoundary(), placeParticle(), read(), set(), and write().
inflowVelocity_
double ChuteInsertionBoundary::inflowVelocity_ private
Referenced by ChuteInsertionBoundary(), placeParticle(), read(), set(), and write().
inflowVelocityVariance_
double ChuteInsertionBoundary::inflowVelocityVariance_ private
Referenced by ChuteInsertionBoundary(), placeParticle(), read(), set(), and write().
posMax_
Vec3D ChuteInsertionBoundary::posMax_ private
Referenced by ChuteInsertionBoundary(), placeParticle(), read(), set(), and write().
posMin_
Vec3D ChuteInsertionBoundary::posMin_ private
The two extremal corners of the cuboidal insertion boundary.
Referenced by ChuteInsertionBoundary(), placeParticle(), read(), set(), and write().
The documentation for this class was generated from the following files:
ChuteInsertionBoundary.h
ChuteInsertionBoundary.cc