MercuryDPM: MeltableParticle Class Reference
MeltableParticle Class Reference
#include <MeltableParticle.h>
Public Member Functions
MeltableParticle ()=default
Basic Particle constructor, creates a particle at (0,0,0) with radius, mass and inertia equal to 1.
MeltableParticle (const MeltableParticle &p)=default
Particle copy constructor, which accepts as input a reference to a Particle. It creates a copy of this Particle and all it's information. Usually it is better to use the copy() function for polymorphism.
MeltableParticle * copy () const override
Particle copy method. It calls to copy constructor of this Particle, useful for polymorphism.
std::string getName () const override
Mdouble getParticleProjectedArea ()
const MeltableNormalSpecies * getMeltableSpecies () const
void actionsBeforeTimeStep () override
void actionsAfterTimeStep () override
unsigned getNumberOfFieldsVTK () const override
std::string getTypeVTK (unsigned i) const override
std::string getNameVTK (unsigned i) const override
std::vector< Mdouble > getFieldVTK (unsigned i) const override
void setSpecies (const ParticleSpecies *species) override
void addHeat (double heat)
double getMeltRate (double solidRadius) const
double getSolidRadius () const
double getMoltenLayerThickness () const
Public Member Functions inherited from Thermal< Particle >
Thermal ()
Basic Particle constructor, creates a particle at (0,0,0) with radius, mass and inertia equal to 1.
Thermal (const Thermal &p)
Particle copy constructor, which accepts as input a reference to a Particle. It creates a copy of this Particle and all it's information. Usually it is better to use the copy() function for polymorphism.
~Thermal () override=default
Particle destructor, needs to be implemented and checked if it removes tangential spring information.
Thermal * copy () const override
Particle copy method. It calls to copy constructor of this Particle, useful for polymorfism.
void write (std::ostream &os) const override
std::string getName () const override
void read (std::istream &is) override
Mdouble getTemperature () const
void setTemperature (Mdouble temperature)
void addTemperature (Mdouble temperature)
void setTemperatureDependentDensity (const std::function< double(double)> &temperatureDependentDensity)
const std::function< double(double)> & getTemperatureDependentDensity () const
const std::function< double(double)> & getTimeDependentTemperature () const
void setTimeDependentTemperature (const std::function< double(double)> &timeDependentTemperature)
void actionsAfterTimeStep () override
bool isSphericalParticle () const override
Private Attributes
double heat_ = 0
const MeltableNormalSpecies * meltableSpecies_ = nullptr
Additional Inherited Members
Protected Attributes inherited from Thermal< Particle >
Mdouble temperature_
Constructor & Destructor Documentation
MeltableParticle() [1/2]
MeltableParticle::MeltableParticle () default
Basic Particle constructor, creates a particle at (0,0,0) with radius, mass and inertia equal to 1.
Referenced by copy().
MeltableParticle() [2/2]
MeltableParticle::MeltableParticle (const MeltableParticle & p) default
Particle copy constructor, which accepts as input a reference to a Particle. It creates a copy of this Particle and all it's information. Usually it is better to use the copy() function for polymorphism.
Member Function Documentation
actionsAfterTimeStep()
void MeltableParticle::actionsAfterTimeStep () override
Compute heat
Todo:
mass not kept!
 {
     // apply heat
     double heatCapacity = meltableSpecies_->getEffectiveHeatCapacity(getTemperature());
     double timeStep = getHandler()->getDPMBase()->getTimeStep();
     double temperatureStep = heat_*getInvMass()/heatCapacity*timeStep;
     addTemperature(temperatureStep);
 //    // add bonding radius
 //    for (auto i : getInteractions()) {
 //        if (i->getP()==this) {
 //            auto m = dynamic_cast<MeltableInteraction*>(i);
 //            m->addBondingOverlap()
 //        }
 //    }
     // thermal expansion
     if (meltableSpecies_->getThermalExpansionCoefficient()!=0)
     {
         setRadius(getRadius()+meltableSpecies_->getThermalExpansionCoefficient()*getRadius()*temperatureStep);
     }
 }
References Thermal< Particle >::addTemperature(), MeltableNormalSpecies::getEffectiveHeatCapacity(), Thermal< Particle >::getTemperature(), MeltableNormalSpecies::getThermalExpansionCoefficient(), heat_, and meltableSpecies_.
actionsBeforeTimeStep()
void MeltableParticle::actionsBeforeTimeStep () override
Compute heat
 {
     const auto s = meltableSpecies_;
     heat_ = s->getHeatInput(this);
     // add thermal convection
     heat_ += -s->getThermalConvectionCoefficient() * getParticleProjectedArea()
             * (getTemperature() - s->getAmbientTemperature());
     // add thermal radiation
     Mdouble radiationCoefficient = constants::stefanBoltzmanConstant
             * s->getMaterialEmissivity()
             * (getTemperature() + s->getAmbientTemperature())
             * (mathsFunc::square(getTemperature())
             + mathsFunc::square(s->getAmbientTemperature()));
     heat_ += -radiationCoefficient * getParticleProjectedArea() * (getTemperature() - s->getAmbientTemperature());
 }
References getParticleProjectedArea(), Thermal< Particle >::getTemperature(), heat_, meltableSpecies_, s, mathsFunc::square(), and constants::stefanBoltzmanConstant.
addHeat()
void MeltableParticle::addHeat (double heat) inline
{
         heat_ += heat;
     }
References heat_.
copy()
MeltableParticle * MeltableParticle::copy () const override
Particle copy method. It calls to copy constructor of this Particle, useful for polymorphism.
Copy method. Uses copy constructor to create a copy on the heap. Useful for polymorphism.
Returns
pointer to the particle's copy
 {
     return new MeltableParticle(*this);
 }
References MeltableParticle().
getFieldVTK()
std::vector< Mdouble > MeltableParticle::getFieldVTK (unsigned i) const override
 {
     double solidRadius = getSolidRadius();
     double moltenLayerThickness = getRadius() - solidRadius;
     if (i==0) {
         return std::vector<Mdouble>(1, moltenLayerThickness);
     } else if (i==1) {
         return std::vector<Mdouble>(1, solidRadius);
     } else {
         return std::vector<Mdouble>(1, temperature_);
     }
 }
References getSolidRadius(), i, and Thermal< Particle >::temperature_.
getMeltableSpecies()
const MeltableNormalSpecies* MeltableParticle::getMeltableSpecies () const inline
{
         return meltableSpecies_;
     }
References meltableSpecies_.
Referenced by getMeltRate().
getMeltRate()
double MeltableParticle::getMeltRate (double solidRadius) const inline
{
         return heat_/(4.0*constants::pi*solidRadius*solidRadius*getSpecies()->getDensity()*getMeltableSpecies()->getEffectiveLatentHeat());
     }
References MeltableNormalSpecies::getEffectiveLatentHeat(), getMeltableSpecies(), heat_, and constants::pi.
getMoltenLayerThickness()
double MeltableParticle::getMoltenLayerThickness () const inline
{
         return getRadius() - getSolidRadius();
     }
References getSolidRadius().
getName()
std::string MeltableParticle::getName () const override
Returns the name of the object; in this case 'MeltableParticle'.
Returns
The object name.
 {
     return "MeltableParticle";
 }
getNameVTK()
std::string MeltableParticle::getNameVTK (unsigned i) const override
 {
     if (i==0)
         return "MoltenLayerThickness";
     else if (i==1)
         return "SolidRadius";
     else /*i=2*/
         return "Temperature";
 }
References i.
getNumberOfFieldsVTK()
unsigned MeltableParticle::getNumberOfFieldsVTK () const inline override
 { return 3; }
getParticleProjectedArea()
Mdouble MeltableParticle::getParticleProjectedArea ()
 {
     return constants::pi * getRadius()*getRadius();
 }
References constants::pi.
Referenced by actionsBeforeTimeStep().
getSolidRadius()
double MeltableParticle::getSolidRadius () const inline
{
         return meltableSpecies_->getRelativeSolidRadius(temperature_)*getRadius();
     }
References MeltableNormalSpecies::getRelativeSolidRadius(), meltableSpecies_, and Thermal< Particle >::temperature_.
Referenced by getFieldVTK(), and getMoltenLayerThickness().
getTypeVTK()
std::string MeltableParticle::getTypeVTK (unsigned i) const inline override
 { return "Float32"; }
setSpecies()
void MeltableParticle::setSpecies (const ParticleSpecies * species) inline override
{
         BaseParticle::setSpecies(species);
         meltableSpecies_ = dynamic_cast<const MeltableNormalSpecies*>(species);
     }
References meltableSpecies_, and BaseParticle::setSpecies().
Member Data Documentation
heat_
double MeltableParticle::heat_ = 0 private
Referenced by actionsAfterTimeStep(), actionsBeforeTimeStep(), addHeat(), and getMeltRate().
meltableSpecies_
const MeltableNormalSpecies* MeltableParticle::meltableSpecies_ = nullptr private
Referenced by actionsAfterTimeStep(), actionsBeforeTimeStep(), getMeltableSpecies(), getSolidRadius(), and setSpecies().
The documentation for this class was generated from the following files:
MeltableParticle.h
MeltableParticle.cc