MercuryDPM: csvReader Class Reference
csvReader Class Reference
Enables reading of .csv files into MercuryDPM.
#include <csvReader.h>
Public Member Functions
csvReader ()
Constructor.
void read (const std::string &filename)
Reads .csv files into Mercury.
std::vector< std::string > getHeaderVector ()
Get the Header string vector of a .csv file.
void setHeader (bool headings)
Set the boolean hasHeader_.
std::vector< std::vector< std::string > > getNumArray ()
Get the 2D array with the .csv file values.
std::vector< Mdouble > getFirstColumn (Mdouble scalingFactor)
Get first column of a .csv file and return it as a double.
std::vector< Mdouble > getSecondColumn (Mdouble scalingFactor)
Get second column of a .csv file and return it as a double.
Private Attributes
std::vector< std::vector< std::string > > numArray_
std::vector< std::string > headerVector_
std::vector< Mdouble > CSVFirstColumn_
std::vector< Mdouble > CSVSecondColumn_
bool hasHeader_ = false
Detailed Description
Enables reading of .csv files into MercuryDPM.
the csvReader stores a 2D array of strings from a comma-separated value (.csv) file. In this way any data type from a .csv file can be read into Mercury and converted into other formats.
Constructor & Destructor Documentation
csvReader()
csvReader::csvReader () default
Constructor.
Default constructor; sets every data member to 0 or default.
Member Function Documentation
getFirstColumn()
std::vector< Mdouble > csvReader::getFirstColumn (Mdouble scalingFactor)
Get first column of a .csv file and return it as a double.
Gets the first column of the .csv file as a vector of doubles. It extracts the first column from the 2D array and converts the vector of strings into a vector of doubles.
Returns
A vector of doubles containing the values of the .csv file's first column.
 {
     for (int i = 0; i < numArray_.size(); i++)
     {
         // converts vector<string> to vector<double>
         // if std::stod throws an exception of an invalid argument there might be an encoding issue.
         CSVFirstColumn_.push_back(std::stod(numArray_[i][0].c_str()) / scalingFactor);
     }
     return CSVFirstColumn_;
 }
References CSVFirstColumn_, i, and numArray_.
Referenced by PSD::setPSDFromCSV().
getHeaderVector()
std::vector< std::string > csvReader::getHeaderVector ()
Get the Header string vector of a .csv file.
Gets the headerVector_ containing the values of the .csv file's first row.
Returns
A vector of strings containing the header values.
 {
     return headerVector_;
 }
References headerVector_.
getNumArray()
std::vector< std::vector< std::string > > csvReader::getNumArray ()
Get the 2D array with the .csv file values.
Gets the 2D array of strings which contains all the .csv file values from the read() function.
Returns
A 2D array of strings containing all the .csv file values.
 {
     return numArray_;
 }
References numArray_.
getSecondColumn()
std::vector< Mdouble > csvReader::getSecondColumn (Mdouble scalingFactor)
Get second column of a .csv file and return it as a double.
Gets the second column of the .csv file as a vector of doubles. It extracts the second column from the 2D array and converts the vector of strings into a vector of doubles.
Returns
A vector of doubles containing the values of the .csv file's second column.
 {
     for (int i = 0; i < numArray_.size(); i++)
     {
         // converts vector<string> to vector<double>
         // if std::stod throws an exception of an invalid argument there might be an encoding issue.
         CSVSecondColumn_.push_back(std::stod(numArray_[i][1].c_str()) / scalingFactor);
     }
     return CSVSecondColumn_;
 }
References CSVSecondColumn_, i, and numArray_.
Referenced by PSD::setPSDFromCSV().
read()
void csvReader::read (const std::string & filename)
Reads .csv files into Mercury.
Read function that divides each line of the .csv file into comma delimited fields which get stored in the numArray_. Further it checks for a byte order mark (BOM) and skips them if existent to avoid errors. If the hasHeader_ is set to TRUE the first row of the .csv file will be skipped.
Parameters
[in] filename Name of the .csv file.
 {
     // strings to catch each line of a file and separate it into fields
     std::string line, field;
     // array of values for one line only
     std::vector<std::string> v;
     // Create ifstream object to open the file
     std::ifstream file;
     file.open(filename);
     if (file.is_open())
     {
         // get first three bytes of the ifstream object (of your file)
         int ch1 = file.get();
         int ch2 = file.get();
         int ch3 = file.get();
         // if TRUE, the file contains UTF-8 BOM (problem usually encountered on Windows OS). A BOM is a mark which
         // distinguishes different file encodings from each other. They usually start with a combination of different
         // bytes (for UTF-8-BOM it is \uFEFF, but asking for it does not work, so it is seperated into three different
         // bytes). Another workaround is changing the encoding to UTF-8 without BOM which some readers are capable of.
         if (ch1 == 0xEF && ch2 == 0xBB && ch3 == 0xBF)
         {
             // skip first three bytes if BOM exists
             file.seekg(3);
             // drop a log message to tell the user that he has a byte-order-mark
             logger(INFO, "Your file contains a byte-order-mark. The first three bytes of this file will be skipped");
         }
         else
         {
             // ensure that the ifstream object starts at the first byte of the csv file
             file.seekg(0);
         }
         while (getline(file, line))    // get next line in file
         {
             v.clear();
             std::stringstream ss(line);
             while (getline(ss, field, ','))
             {
                 // break line into comma delimitted fields
                 v.push_back(field);  // add each field to the 1D array
             }
             if (hasHeader_)
             {
                 headerVector_ = v;  // add the 1D array to the 2D array
                 hasHeader_ = false;
             }
             else
             {
                 numArray_.push_back(v);  // add the 1D array to the 2D array
             }
         }
     }
     else
     {
         logger(ERROR, "File could not be opened");
     }
 }
References ERROR, MergeRestartFiles::filename, hasHeader_, headerVector_, INFO, calibrate::line, logger, numArray_, oomph::Global_string_for_annotation::string(), and v.
Referenced by PSD::setPSDFromCSV().
setHeader()
void csvReader::setHeader (bool hasHeader)
Set the boolean hasHeader_.
Sets the boolean hasHeader_ which determines if the .csv file has headings.
 {
     hasHeader_ = hasHeader;
 }
References hasHeader_.
Referenced by PSD::setPSDFromCSV().
Member Data Documentation
CSVFirstColumn_
std::vector<Mdouble> csvReader::CSVFirstColumn_ private
vector of doubles containing all values of the .csv file's first column.
Referenced by getFirstColumn().
CSVSecondColumn_
std::vector<Mdouble> csvReader::CSVSecondColumn_ private
vector of doubles containing all values of the .csv file's first column.
Referenced by getSecondColumn().
hasHeader_
bool csvReader::hasHeader_ = false private
if FALSE the file has no headers and if TRUE the file has headers and the first row will be skipped.
Referenced by read(), and setHeader().
headerVector_
std::vector<std::string> csvReader::headerVector_ private
vector of strings containing possible header values of the .csv file's first row. This vector is only filled when headerFlag is set to TRUE.
Referenced by getHeaderVector(), and read().
numArray_
std::vector<std::vector<std::string> > csvReader::numArray_ private
2D array containing all .csv file values
Referenced by getFirstColumn(), getNumArray(), getSecondColumn(), and read().
The documentation for this class was generated from the following files:
csvReader.h
csvReader.cc