MercuryDPM: locate_zeta_tester.cc File Reference
locate_zeta_tester.cc File Reference
#include "generic.h"
#include "poisson.h"
#include "meshes/simple_rectangular_quadmesh.h"
#include "locate_zeta_tester.h"
Classes
class SimpleRefineableRectangularQuadMesh< ELEMENT >
class RefineablePoissonProblem< ELEMENT >
Namespaces
GlobalParameters
Global parameters.
Functions
double GlobalParameters::distorted_y (const double &y_normalised)
Function to distort mesh.
void GlobalParameters::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void GlobalParameters::get_source (const Vector< double > &x, double &source)
Source function required to make the solution above an exact solution.
int main (int argc, char *argv[])
Driver code for 2D Poisson problem.
Function Documentation
main()
int main (int argc , char * argv[])
Driver code for 2D Poisson problem.
 {
 #ifdef OOMPH_HAS_CGAL
  oomph_info << "have it" << std::endl;
 #else
  oomph_info << "don't have it" << std::endl;
 #endif
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Validation of projection?
  CommandLineArgs::specify_command_line_flag("--distort_mesh");
  // Number of biased refinements for locate zeta test
  unsigned nrefine_for_locate_zeta_test=2; // hierher
  CommandLineArgs::specify_command_line_flag("--nrefine_for_locate_zeta_test",
                                             &nrefine_for_locate_zeta_test);
  // Number of genuine refinements for locate zeta test
  unsigned nrefine_genuine=2; // hierher
  CommandLineArgs::specify_command_line_flag("--nrefine_genuine",
                                             &nrefine_genuine);
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  //Set up the problem
  //------------------
  // Create the problem with 2D nine-node refineable elements from the
  // RefineableQuadPoissonElement family. Pass pointer to source function.
  RefineablePoissonProblem<RefineableQPoissonElement<2,3> >
   problem(&GlobalParameters::get_source);
  // Create label for output
  //------------------------
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory("RESLT");
  // Step number
  doc_info.number()=0;
  // Set the orientation of the "step" to 45 degrees
  GlobalParameters::TanPhi=1.0;
  // Choose a large value for the steepness of the "step"
  GlobalParameters::Alpha=50.0;
  // Solve the problem, performing adaptive refinements
  problem.newton_solve(nrefine_genuine);
  //Output the solution
  problem.doc_solution(doc_info);
  doc_info.number()++;
  // Setup fake error estimator: Boundaries of refinement region
  Vector<double> lower_left(2);
  Vector<double> upper_right(2);
  double box_size=0.7;
  lower_left[0]=0.2;
  lower_left[1]=0.9;
  upper_right[0]=lower_left[0]+box_size;
  upper_right[1]=lower_left[1]+box_size;
  unsigned central_node_number=8;
  // Stop unrefinement and allow for infinite refinement
  problem.mesh_pt()->min_permitted_error()=-1.0;
  problem.mesh_pt()->max_refinement_level()=UINT_MAX;
  // Adapt lots of times
  for (unsigned i=0;i<nrefine_for_locate_zeta_test;i++)
   {
    // Clean up
    delete problem.mesh_pt()->spatial_error_estimator_pt();
    // Make a new error estimator
    problem.mesh_pt()->spatial_error_estimator_pt()=
     new DummyErrorEstimator(problem.mesh_pt(),lower_left,upper_right,
                             central_node_number);
    // Adapt
    problem.adapt();
    // Shrink box
    box_size*=0.5;
    upper_right[0]=lower_left[0]+box_size;
    upper_right[1]=lower_left[1]+box_size;
   }
  //Output the solution
  problem.doc_solution(doc_info);
  // Check it out!
  check_locate_zeta(problem.mesh_pt());
 } //end of main
References GlobalParameters::Alpha, check_locate_zeta(), oomph::CommandLineArgs::doc_specified_flags(), GlobalParameters::get_source(), i, oomph::DocInfo::number(), oomph::oomph_info, oomph::CommandLineArgs::parse_and_assign(), problem, oomph::DocInfo::set_directory(), Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), and GlobalParameters::TanPhi.