MercuryDPM: Eigen::internal::OP< MatrixSolver, MatrixType, Scalar, true > Struct Template Reference
Eigen::internal::OP< MatrixSolver, MatrixType, Scalar, true > Struct Template Reference
#include <ArpackSelfAdjointEigenSolver.h>
Static Public Member Functions
static void applyOP (MatrixSolver &OP, const MatrixType &A, int n, Scalar *in, Scalar *out)
static void project (MatrixSolver &OP, int n, int k, Scalar *vecs)
Member Function Documentation
applyOP()
template<typename MatrixSolver , typename MatrixType , typename Scalar > static void Eigen::internal::OP< MatrixSolver, MatrixType, Scalar, true >::applyOP (MatrixSolver & OP, const MatrixType & A, int n, Scalar * in, Scalar * out) inline static
{
     // OP = L^{-1} A L^{-T}  (B = LL^T)
     //
     // First solve L^T out = in
     //
     Matrix<Scalar, Dynamic, 1>::Map(out, n) = OP.matrixU().solve(Matrix<Scalar, Dynamic, 1>::Map(in, n));
     Matrix<Scalar, Dynamic, 1>::Map(out, n) = OP.permutationPinv() * Matrix<Scalar, Dynamic, 1>::Map(out, n);
     // Then compute out = A out
     //
     Matrix<Scalar, Dynamic, 1>::Map(out, n) = A * Matrix<Scalar, Dynamic, 1>::Map(out, n);
     // Then solve L out = out
     //
     Matrix<Scalar, Dynamic, 1>::Map(out, n) = OP.permutationP() * Matrix<Scalar, Dynamic, 1>::Map(out, n);
     Matrix<Scalar, Dynamic, 1>::Map(out, n) = OP.matrixL().solve(Matrix<Scalar, Dynamic, 1>::Map(out, n));
   }
References Eigen::PlainObjectBase< Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ > >::Map(), n, and out().
project()
template<typename MatrixSolver , typename MatrixType , typename Scalar > static void Eigen::internal::OP< MatrixSolver, MatrixType, Scalar, true >::project (MatrixSolver & OP, int n, int k, Scalar * vecs) inline static
{
     // Solve L^T out = in
     //
     Matrix<Scalar, Dynamic, Dynamic>::Map(vecs, n, k) =
         OP.matrixU().solve(Matrix<Scalar, Dynamic, Dynamic>::Map(vecs, n, k));
     Matrix<Scalar, Dynamic, Dynamic>::Map(vecs, n, k) =
         OP.permutationPinv() * Matrix<Scalar, Dynamic, Dynamic>::Map(vecs, n, k);
   }
References k, Eigen::PlainObjectBase< Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ > >::Map(), and n.
The documentation for this struct was generated from the following file:
ArpackSelfAdjointEigenSolver.h