MercuryDPM: oomph::QElement3BulkCoordinateDerivatives Namespace Reference
oomph::QElement3BulkCoordinateDerivatives Namespace Reference
Functions
void faces0 (const Vector< double > &s, DenseMatrix< double > &dsbulk_dsface, unsigned &interior_direction)
Function for the back and front faces, along which s0 is fixed.
void faces1 (const Vector< double > &s, DenseMatrix< double > &dsbulk_dsface, unsigned &interior_direction)
Function for the up and down faces, along which s1 is fixed.
void faces2 (const Vector< double > &s, DenseMatrix< double > &dsbulk_dsface, unsigned &interior_direction)
Function for the left and right faces, along which s2 is fixed.
Detailed Description
Namespace for helper functions that calculate derivatives of the local coordinates in the bulk elements wrt the local coordinates in the face element.
Function Documentation
faces0()
void oomph::QElement3BulkCoordinateDerivatives::faces0 (const Vector< double > & s, DenseMatrix< double > & dsbulk_dsface, unsigned & interior_direction)
Function for the back and front faces, along which s0 is fixed.
     {
       // Bulk coordinate s[0] does not vary along the face
       dsbulk_dsface(0, 0) = 0.0;
       dsbulk_dsface(0, 1) = 0.0;
       // Bulk coordinate s[1] is the face coordinate 1
       dsbulk_dsface(1, 0) = 1.0;
       dsbulk_dsface(1, 1) = 0.0;
       // Bulk coordinate s[2] is the face coordinate 2
       dsbulk_dsface(2, 0) = 0.0;
       dsbulk_dsface(2, 1) = 1.0;
       // The interior direction is given by s[0]
       interior_direction = 0;
     }
Referenced by oomph::QSpectralElement< 3, NNODE_1D >::build_face_element(), and oomph::QElement< 3, NNODE_1D >::bulk_coordinate_derivatives_fct_pt().
faces1()
void oomph::QElement3BulkCoordinateDerivatives::faces1 (const Vector< double > & s, DenseMatrix< double > & dsbulk_dsface, unsigned & interior_direction)
Function for the up and down faces, along which s1 is fixed.
     {
       // Bulk coordinate s[0] is face coordinate 0
       dsbulk_dsface(0, 0) = 1.0;
       dsbulk_dsface(0, 1) = 0.0;
       // Bulk coordinate s[1] is fixed on the face
       dsbulk_dsface(1, 0) = 0.0;
       dsbulk_dsface(1, 1) = 0.0;
       // Bulk coordinate s[2] is the face coordinate 2
       dsbulk_dsface(2, 0) = 0.0;
       dsbulk_dsface(2, 1) = 1.0;
       // The interior direction is given by s[1]
       interior_direction = 1;
     }
Referenced by oomph::QSpectralElement< 3, NNODE_1D >::build_face_element(), and oomph::QElement< 3, NNODE_1D >::bulk_coordinate_derivatives_fct_pt().
faces2()
void oomph::QElement3BulkCoordinateDerivatives::faces2 (const Vector< double > & s, DenseMatrix< double > & dsbulk_dsface, unsigned & interior_direction)
Function for the left and right faces, along which s2 is fixed.
     {
       // Bulk coordinate s[0] is face coordinate 0
       dsbulk_dsface(0, 0) = 1.0;
       dsbulk_dsface(0, 1) = 0.0;
       // Bulk coordinate s[1] is face coordinate 1
       dsbulk_dsface(1, 0) = 0.0;
       dsbulk_dsface(1, 1) = 1.0;
       // Bulk coordinate s[2] is fixed on the face
       dsbulk_dsface(2, 0) = 0.0;
       dsbulk_dsface(2, 1) = 0.0;
       // The interior direction is given by s[2]
       interior_direction = 2;
     }
Referenced by oomph::QSpectralElement< 3, NNODE_1D >::build_face_element(), and oomph::QElement< 3, NNODE_1D >::bulk_coordinate_derivatives_fct_pt().