MercuryDPM: oomph::RungeKutta< ORDER > Class Template Reference
oomph::RungeKutta< ORDER > Class Template Reference
#include <explicit_timesteppers.h>
Public Member Functions
RungeKutta ()
Constructor, set the type.
RungeKutta (const RungeKutta &)=delete
Broken copy constructor.
void operator= (const RungeKutta &)=delete
Broken assignment operator.
void timestep (ExplicitTimeSteppableObject *const &object_pt, const double &dt)
Function that is used to advance time in the object.
void timestep (ExplicitTimeSteppableObject *const &object_pt, const double &dt)
Explicit specialisation for fourth-order RK scheme.
void timestep (ExplicitTimeSteppableObject *const &object_pt, const double &dt)
Explicit specialisation for second-order RK scheme.
Public Member Functions inherited from oomph::ExplicitTimeStepper
ExplicitTimeStepper ()
Empty Constructor.
ExplicitTimeStepper (const ExplicitTimeStepper &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeStepper &)=delete
Broken assignment operator.
virtual ~ExplicitTimeStepper ()
Empty virtual destructor — no memory is allocated in this class.
Additional Inherited Members
Protected Attributes inherited from oomph::ExplicitTimeStepper
std::string Type
Detailed Description
template<unsigned ORDER>
class oomph::RungeKutta< ORDER >
=========================================================== Standard Runge Kutta Timestepping
Constructor & Destructor Documentation
RungeKutta() [1/2]
template<unsigned ORDER> oomph::RungeKutta< ORDER >::RungeKutta () inline
Constructor, set the type.
     {
       Type = "RungeKutta";
     }
References oomph::ExplicitTimeStepper::Type.
RungeKutta() [2/2]
template<unsigned ORDER> oomph::RungeKutta< ORDER >::RungeKutta (const RungeKutta< ORDER > &) delete
Broken copy constructor.
Member Function Documentation
operator=()
template<unsigned ORDER> void oomph::RungeKutta< ORDER >::operator= (const RungeKutta< ORDER > &) delete
Broken assignment operator.
timestep() [1/3]
void oomph::RungeKutta< 4 >::timestep (ExplicitTimeSteppableObject *const & object_pt, const double & dt) virtual
Explicit specialisation for fourth-order RK scheme.
Implements oomph::ExplicitTimeStepper.
   {
     object_pt->actions_before_explicit_timestep();
     // Stage 1
     // ============================================================
     object_pt->actions_before_explicit_stage();
     // Store the initial values and initial time
     DoubleVector u;
     object_pt->get_dofs(u);
     // Now get the first unknowns
     DoubleVector k1;
     object_pt->get_dvaluesdt(k1);
     // Add to the residuals
     object_pt->add_to_dofs(0.5 * dt, k1);
     // Increment the time
     object_pt->time() += 0.5 * dt;
     object_pt->actions_after_explicit_stage();
     // Stage 2
     // ============================================================
     object_pt->actions_before_explicit_stage();
     // Get the next unknowns
     DoubleVector k2;
     object_pt->get_dvaluesdt(k2);
     // Now reset the residuals
     object_pt->set_dofs(u);
     object_pt->add_to_dofs(0.5 * dt, k2);
     // Time remains the same
     object_pt->actions_after_explicit_stage();
     // Stage 3
     // ============================================================
     object_pt->actions_before_explicit_stage();
     // Get the next unknowns
     DoubleVector k3;
     object_pt->get_dvaluesdt(k3);
     // Now reset the residuals
     object_pt->set_dofs(u);
     object_pt->add_to_dofs(dt, k3);
     // Increment the time (now at initial_time + dt)
     object_pt->time() += 0.5 * dt;
     object_pt->actions_after_explicit_stage();
     // Stage 4
     // ============================================================
     object_pt->actions_before_explicit_stage();
     // Get the final unknowns
     DoubleVector k4;
     object_pt->get_dvaluesdt(k4);
     // Set the final values of the unknowns
     object_pt->set_dofs(u);
     object_pt->add_to_dofs((dt / 6.0), k1);
     object_pt->add_to_dofs((dt / 3.0), k2);
     object_pt->add_to_dofs((dt / 3.0), k3);
     object_pt->add_to_dofs((dt / 6.0), k4);
     object_pt->actions_after_explicit_stage();
     object_pt->actions_after_explicit_timestep();
   }
References oomph::ExplicitTimeSteppableObject::actions_after_explicit_stage(), oomph::ExplicitTimeSteppableObject::actions_after_explicit_timestep(), oomph::ExplicitTimeSteppableObject::actions_before_explicit_stage(), oomph::ExplicitTimeSteppableObject::actions_before_explicit_timestep(), oomph::ExplicitTimeSteppableObject::add_to_dofs(), oomph::ExplicitTimeSteppableObject::get_dofs(), oomph::ExplicitTimeSteppableObject::get_dvaluesdt(), oomph::ExplicitTimeSteppableObject::set_dofs(), and oomph::ExplicitTimeSteppableObject::time().
timestep() [2/3]
void oomph::RungeKutta< 2 >::timestep (ExplicitTimeSteppableObject *const & object_pt, const double & dt) virtual
Explicit specialisation for second-order RK scheme.
Implements oomph::ExplicitTimeStepper.
   {
     object_pt->actions_before_explicit_timestep();
     // Stage 1
     // ============================================================
     object_pt->actions_before_explicit_stage();
     // Store the initial values
     DoubleVector u;
     object_pt->get_dofs(u);
     // Get f1 (time derivative at t0, y0) and add to dofs
     DoubleVector f1;
     object_pt->get_dvaluesdt(f1);
     object_pt->add_to_dofs(dt, f1);
     // Advance time to t1 = t0 + dt
     object_pt->time() += dt;
     object_pt->actions_after_explicit_stage();
     // Stage 2
     // ============================================================
     object_pt->actions_before_explicit_stage();
     // get f2 (with t=t1, y = y0 + h f0)
     DoubleVector f2;
     object_pt->get_dvaluesdt(f2);
     // Final answer is starting dofs + h/2 * (f1 + f2)
     object_pt->set_dofs(u);
     object_pt->add_to_dofs(0.5 * dt, f1);
     object_pt->add_to_dofs(0.5 * dt, f2);
     object_pt->actions_after_explicit_stage();
     // Done, do actions
     object_pt->actions_after_explicit_timestep();
   }
References oomph::ExplicitTimeSteppableObject::actions_after_explicit_stage(), oomph::ExplicitTimeSteppableObject::actions_after_explicit_timestep(), oomph::ExplicitTimeSteppableObject::actions_before_explicit_stage(), oomph::ExplicitTimeSteppableObject::actions_before_explicit_timestep(), oomph::ExplicitTimeSteppableObject::add_to_dofs(), Global_parameters::f1(), Global_parameters::f2(), oomph::ExplicitTimeSteppableObject::get_dofs(), oomph::ExplicitTimeSteppableObject::get_dvaluesdt(), oomph::ExplicitTimeSteppableObject::set_dofs(), and oomph::ExplicitTimeSteppableObject::time().
timestep() [3/3]
template<unsigned ORDER> void oomph::RungeKutta< ORDER >::timestep (ExplicitTimeSteppableObject *const & object_pt, const double & dt) virtual
Function that is used to advance time in the object.
Implements oomph::ExplicitTimeStepper.
   {
     std::ostringstream error_stream;
     error_stream << "Timestep not implemented for order " << ORDER << "\n";
     throw OomphLibError(
       error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
   }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
The documentation for this class was generated from the following files:
explicit_timesteppers.h
explicit_timesteppers.cc