MercuryDPM: CubeDeletionBoundary Class Reference
CubeDeletionBoundary Class Reference
#include <CubeDeletionBoundary.h>
Public Member Functions
CubeDeletionBoundary ()
default constructor
~CubeDeletionBoundary () override
destructor
CubeDeletionBoundary * copy () const override
Copy method; creates copy on the heap and returns a pointer to it.
void set (Vec3D posMin, Vec3D posMax)
Sets boundary position based on two opposite corners.
Mdouble getDistance (const Vec3D &position) const override
Returns a negative value if and only if the particle is inside the boundary.
void read (std::istream &is) override
reads boundary properties from istream
void write (std::ostream &os) const override
writes boundary properties to ostream
std::string getName () const override
Returns the name of the object.
Public Member Functions inherited from DeletionBoundary
DeletionBoundary ()
default constructor
DeletionBoundary (DeletionBoundary const &d)
default copy constructor
~DeletionBoundary () override
destructor
DeletionBoundary * copy () const override
Copy method; creates copy on the heap and returns a pointer to it.
void set (const Vec3D &normal, Mdouble distance)
Sets boundary position based on a normal and distance.
void move (Mdouble position)
Sets the boundary's distance property to the given one.
bool checkBoundaryAfterParticleMoved (BaseParticle *p, ParticleHandler &pH)
Checks if particle is inside the boundary, and deletes the particle if so.
void checkBoundaryAfterParticlesMove (ParticleHandler &pH) override
unsigned int getNumberOfParticlesDeleted () const
Gets the number of particles deleted by the boundary.
double getMassOfParticlesDeleted () const
double getVolumeOfParticlesDeleted () const
void reset ()
void activate ()
Turns on the DeletionBoundary.
void deactivate ()
Turns off the DeletionBoundary.
void trackOutflow (bool trackOutflow=true)
Turns on the outflow tracker.
void setTrackerCustom (std::function< void(std::ofstream &, BaseParticle *)> trackerCustom)
Sets a custom function for tracking the outflow.
void read (std::istream &is) override
Reads some boundary properties from an std::istream.
MERCURYDPM_DEPRECATED void oldRead (std::istream &is)
Deprecated read method. use DeletionBoundary::read() instead.
void write (std::ostream &os) const override
Writes the boundary properties to an std::ostream.
std::string getName () const override
Returns the name of the object.
Public Member Functions inherited from BaseBoundary
BaseBoundary ()
default constructor.
BaseBoundary (const BaseBoundary &b)
copy constructor
~BaseBoundary () override
destructor
virtual void createPeriodicParticle (BaseParticle *p UNUSED, ParticleHandler &pH UNUSED)
Creates a periodic particle in case of periodic boundaries in serial build.
virtual void createPeriodicParticles (ParticleHandler &pH UNUSED)
Creates periodic copies of given particle in case of periodic boundaries.
virtual void checkBoundaryBeforeTimeStep (DPMBase *md)
Virtual function that does things before each time step.
virtual void actionsBeforeTimeLoop ()
Virtual function that does something after DPMBase::setupInitialConditions but before the first time step.
virtual void modifyGhostAfterCreation (BaseParticle *particle, int i)
virtual void writeVTK (std::fstream &file)
void setHandler (BoundaryHandler *handler)
Sets the boundary's BoundaryHandler.
BoundaryHandler * getHandler () const
Returns the boundary's BoundaryHandler.
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
Vec3D posMin_
Minimal and maximal positions defining the boundary's boundaries.
Vec3D posMax_
Constructor & Destructor Documentation
CubeDeletionBoundary()
CubeDeletionBoundary::CubeDeletionBoundary ()
default constructor
                                            : DeletionBoundary()
 {
     posMin_ = Vec3D(0, 0, 0);
     posMax_ = Vec3D(0, 0, 0);
     logger(DEBUG, "CubeDeletionBoundary::CubeDeletionBoundary() finished", true);
 }
References DEBUG, logger, posMax_, and posMin_.
Referenced by copy().
~CubeDeletionBoundary()
CubeDeletionBoundary::~CubeDeletionBoundary () override
destructor
 {
     logger(DEBUG, "CubeDeletionBoundary::~CubeDeletionBoundary() finished", true);
 }
References DEBUG, and logger.
Member Function Documentation
copy()
CubeDeletionBoundary * CubeDeletionBoundary::copy () const override virtual
Copy method; creates copy on the heap and returns a pointer to it.
Implements BaseBoundary.
 {
     return new CubeDeletionBoundary(*this);
 }
References CubeDeletionBoundary().
getDistance()
Mdouble CubeDeletionBoundary::getDistance (const Vec3D & position) const override virtual
Returns a negative value if and only if the particle is inside the boundary.
Todo:
JMFT: Calculate the distance properly, not just 1 or -1.
Reimplemented from DeletionBoundary.
 {
     if (posMin_.X < position.X && position.X < posMax_.X
         && posMin_.Y < position.Y && position.Y < posMax_.Y
         && posMin_.Z < position.Z && position.Z < posMax_.Z
             )
         return -1;
     else
         return 1;
 }
References posMax_, posMin_, Vec3D::X, Vec3D::Y, and Vec3D::Z.
getName()
std::string CubeDeletionBoundary::getName () const override virtual
Returns the name of the object.
Returns the object's class name (i.e. 'CubeDeletionBoundary').
Returns
the object's class name
Implements BaseObject.
 {
     return "CubeDeletionBoundary";
 }
read()
void CubeDeletionBoundary::read (std::istream & is) override virtual
reads boundary properties from istream
Implements BaseBoundary.
 {
     DeletionBoundary::read(is);
     std::string dummy;
     is >> dummy >> posMin_
        >> dummy >> posMax_;
 }
References posMax_, posMin_, DeletionBoundary::read(), and oomph::Global_string_for_annotation::string().
set()
void CubeDeletionBoundary::set (Vec3D posMin, Vec3D posMax)
Sets boundary position based on two opposite corners.
 {
     posMin_ = posMin;
     posMax_ = posMax;
 }
References posMax_, and posMin_.
write()
void CubeDeletionBoundary::write (std::ostream & os) const override virtual
writes boundary properties to ostream
Implements BaseBoundary.
 {
     DeletionBoundary::write(os);
     os << " posMin " << posMin_ << " posMax " << posMax_;
 }
References posMax_, posMin_, and DeletionBoundary::write().
Member Data Documentation
posMax_
Vec3D CubeDeletionBoundary::posMax_ private
Referenced by CubeDeletionBoundary(), getDistance(), read(), set(), and write().
posMin_
Vec3D CubeDeletionBoundary::posMin_ private
Minimal and maximal positions defining the boundary's boundaries.
Referenced by CubeDeletionBoundary(), getDistance(), read(), set(), and write().
The documentation for this class was generated from the following files:
CubeDeletionBoundary.h
CubeDeletionBoundary.cc