MercuryDPM: BinaryReaderSTLOneTriangleUnitTest.cpp File Reference
BinaryReaderSTLOneTriangleUnitTest.cpp File Reference
#include <fstream>
#include <iostream>
#include <BinaryReader.h>
#include <Logger.h>
#include <Math/Vector.h>
#include <CMakeDefinitions.h>
Functions
int main ()
Test of the binary reader. The files used is STL file with containing one triange.
Function Documentation
main()
int main ()
Test of the binary reader. The files used is STL file with containing one triange.
This code users BinaryReader to open a binary file called SimpleTrianlge.stl and read in currently the single tringle from this file. The triangle was created using nclab.org and contains a single triangle with normal (0,0,1) and vertex (0,1,0), (1,0,0) and (1,1,0). This is currently a UnitTest as does not require selftest data; however, it does require he file SimpleTrianlge.stl to exist
 {
     std::ifstream STLFile;
     std::string directory(getMercuryDPMSourceDir());
     BinaryReader STLReader(directory+"/Drivers/ImportTools/ExampleSTLFiles/SimpleTrianlge.stl");
     //First read the 80 character header
     std::string header;
     header=STLReader.readString(80);
     //logger(INFO, "Header : %" ,header);
     //The next four characters contain at unsigned int which is the number of triangeles
     unsigned int numTriangles = STLReader.readUnsignedInt(4);
     //logger(INFO, "Number of traingles: %", numTriangles);
     if (numTriangles!=1)
         logger(FATAL,"Failed to read the correct number of triangles");
     double xTmp,yTmp,zTmp;
     for (unsigned int i=0; i<(numTriangles);i++)
     {
         xTmp = STLReader.readFloat(4);
         yTmp =  STLReader.readFloat(4);
         zTmp = STLReader.readFloat(4);
         Vec3D Normal(xTmp,yTmp,zTmp);
         if (!(Normal.isEqualTo(Vec3D(0,0,1),1e-10)))
             logger(FATAL,"The normal has been misread");
         xTmp = STLReader.readFloat(4);
         yTmp =  STLReader.readFloat(4);
         zTmp = STLReader.readFloat(4);
         Vec3D Point1(xTmp,yTmp,zTmp);
         if (!(Point1.isEqualTo(Vec3D(0,1,0),1e-10)))
             logger(FATAL,"The first vertex has been misread");
         xTmp = STLReader.readFloat(4);
         yTmp =  STLReader.readFloat(4);
         zTmp = STLReader.readFloat(4);
         Vec3D Point2(xTmp,yTmp,zTmp);
         if (!(Point2.isEqualTo(Vec3D(1,0,0),1e-10)))
             logger(FATAL,"The second vertex has been misread");
         xTmp = STLReader.readFloat(4);
         yTmp =  STLReader.readFloat(4);
         zTmp = STLReader.readFloat(4);
          Vec3D Point3(xTmp,yTmp,zTmp);
         if (!(Point3.isEqualTo(Vec3D(1,1,0),1e-10)))
             logger(FATAL,"The third vertex has been misread");
         //Now ignore (read) the two dummy characters
         STLReader.ignoreChar(2);
     }
 }
References e(), FATAL, getMercuryDPMSourceDir(), i, BinaryReader::ignoreChar(), Vec3D::isEqualTo(), logger, BinaryReader::readFloat(), BinaryReader::readString(), BinaryReader::readUnsignedInt(), and oomph::Global_string_for_annotation::string().