MercuryDPM: Eigen::internal::homogeneous_right_product_impl< Homogeneous< MatrixType, Horizontal >, Rhs > Struct Template Reference
Eigen::internal::homogeneous_right_product_impl< Homogeneous< MatrixType, Horizontal >, Rhs > Struct Template Reference
#include <Homogeneous.h>
Public Types
typedef remove_all_t< typename Rhs::Nested > RhsNested
Public Types inherited from Eigen::ReturnByValue< homogeneous_right_product_impl< Homogeneous< MatrixType, Horizontal >, Rhs > >
typedef internal::traits< homogeneous_right_product_impl< Homogeneous< MatrixType, Horizontal >, Rhs > >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Public Member Functions
EIGEN_DEVICE_FUNC homogeneous_right_product_impl (const MatrixType &lhs, const Rhs &rhs)
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
Public Member Functions inherited from Eigen::ReturnByValue< homogeneous_right_product_impl< Homogeneous< MatrixType, Horizontal >, Rhs > >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Public Attributes
MatrixType::Nested m_lhs
Rhs::Nested m_rhs
Member Typedef Documentation
RhsNested
template<typename MatrixType , typename Rhs > typedef remove_all_t<typename Rhs::Nested> Eigen::internal::homogeneous_right_product_impl< Homogeneous< MatrixType, Horizontal >, Rhs >::RhsNested
Constructor & Destructor Documentation
homogeneous_right_product_impl()
template<typename MatrixType , typename Rhs > EIGEN_DEVICE_FUNC Eigen::internal::homogeneous_right_product_impl< Homogeneous< MatrixType, Horizontal >, Rhs >::homogeneous_right_product_impl (const MatrixType & lhs, const Rhs & rhs) inline
 : m_lhs(lhs), m_rhs(rhs) {}
Member Function Documentation
cols()
template<typename MatrixType , typename Rhs > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::internal::homogeneous_right_product_impl< Homogeneous< MatrixType, Horizontal >, Rhs >::cols () const inline
 { return m_rhs.cols(); }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
evalTo()
template<typename MatrixType , typename Rhs > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::internal::homogeneous_right_product_impl< Homogeneous< MatrixType, Horizontal >, Rhs >::evalTo (Dest & dst) const inline
{
     // FIXME investigate how to allow lazy evaluation of this product when possible
     dst = m_lhs * Block < const RhsNested,
     RhsNested::RowsAtCompileTime == Dynamic ? Dynamic : RhsNested::RowsAtCompileTime - 1,
     RhsNested::ColsAtCompileTime > (m_rhs, 0, 0, m_rhs.rows() - 1, m_rhs.cols());
     dst += m_rhs.row(m_rhs.rows() - 1).colwise().template replicate<MatrixType::RowsAtCompileTime>(m_lhs.rows());
   }
References Eigen::Dynamic.
rows()
template<typename MatrixType , typename Rhs > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::internal::homogeneous_right_product_impl< Homogeneous< MatrixType, Horizontal >, Rhs >::rows () const inline
 { return m_lhs.rows(); }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_lhs
template<typename MatrixType , typename Rhs > MatrixType::Nested Eigen::internal::homogeneous_right_product_impl< Homogeneous< MatrixType, Horizontal >, Rhs >::m_lhs
m_rhs
template<typename MatrixType , typename Rhs > Rhs::Nested Eigen::internal::homogeneous_right_product_impl< Homogeneous< MatrixType, Horizontal >, Rhs >::m_rhs
The documentation for this struct was generated from the following file:
Homogeneous.h