MercuryDPM: adjoint_specific< true > Struct Reference
adjoint_specific< true > Struct Reference
Static Public Member Functions
template<typename Vec , typename Mat , typename Scalar >
static void run (const Vec &v1, const Vec &v2, Vec &v3, const Mat &square, Scalar s1, Scalar s2)
Member Function Documentation
run()
template<typename Vec , typename Mat , typename Scalar > static void adjoint_specific< true >::run (const Vec & v1, const Vec & v2, Vec & v3, const Mat & square, Scalar s1, Scalar s2) inline static
{
     VERIFY(test_isApproxWithRef((s1 * v1 + s2 * v2).dot(v3),
                                 numext::conj(s1) * v1.dot(v3) + numext::conj(s2) * v2.dot(v3), 0));
     VERIFY(test_isApproxWithRef(v3.dot(s1 * v1 + s2 * v2), s1 * v3.dot(v1) + s2 * v3.dot(v2), 0));
     // check compatibility of dot and adjoint
     VERIFY(test_isApproxWithRef(v1.dot(square * v2), (square.adjoint() * v1).dot(v2), 0));
   }
References conj(), dot(), Eigen::square(), Eigen::test_isApproxWithRef(), v1(), v2(), and VERIFY.
The documentation for this struct was generated from the following file:
adjoint.cpp