MercuryDPM: Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased > Struct Template Reference
Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased > Struct Template Reference
#include <CoreEvaluators.h>
Public Types
enum {
CoeffReadCost = int(evaluator<ArgType>::CoeffReadCost) + int(functor_traits<CastOp>::Cost) , PacketAccess = functor_traits<CastOp>::PacketAccess , ActualPacketAccessBit = PacketAccess ? PacketAccessBit : 0 , Flags = evaluator<ArgType>::Flags & (HereditaryBits | LinearAccessBit | ActualPacketAccessBit) ,
IsRowMajor = (evaluator<ArgType>::Flags & RowMajorBit) , Alignment = evaluator<ArgType>::Alignment
}
using CastOp = core_cast_op< SrcType, DstType >
using XprType = CwiseUnaryOp< CastOp, ArgType >
using SrcPacketType = typename packet_traits< SrcType >::type
template<typename DstPacketType >
using AltSrcScalarOp = std::enable_if_t<(unpacket_traits< DstPacketType >::size< SrcPacketSize &&!find_packet_by_size< SrcType, unpacket_traits< DstPacketType >::size >::value), bool >
template<typename DstPacketType >
using SrcPacketArgs1 = std::enable_if_t<(find_packet_by_size< SrcType, unpacket_traits< DstPacketType >::size >::value), bool >
template<typename DstPacketType >
using SrcPacketArgs2 = std::enable_if_t<(unpacket_traits< DstPacketType >::size)==(2 *SrcPacketSize), bool >
template<typename DstPacketType >
using SrcPacketArgs4 = std::enable_if_t<(unpacket_traits< DstPacketType >::size)==(4 *SrcPacketSize), bool >
template<typename DstPacketType >
using SrcPacketArgs8 = std::enable_if_t<(unpacket_traits< DstPacketType >::size)==(8 *SrcPacketSize), bool >
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE unary_evaluator (const XprType &xpr)
template<bool UseRowMajor = IsRowMajor, std::enable_if_t< UseRowMajor, bool > = true>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool check_array_bounds (Index, Index col, Index packetSize) const
template<bool UseRowMajor = IsRowMajor, std::enable_if_t<!UseRowMajor, bool > = true>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool check_array_bounds (Index row, Index, Index packetSize) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool check_array_bounds (Index index, Index packetSize) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE SrcType srcCoeff (Index row, Index col, Index offset) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE SrcType srcCoeff (Index index, Index offset) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstType coeff (Index index) const
template<int LoadMode, typename PacketType = SrcPacketType>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType srcPacket (Index row, Index col, Index offset) const
template<int LoadMode, typename PacketType = SrcPacketType>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType srcPacket (Index index, Index offset) const
template<int LoadMode, typename DstPacketType , AltSrcScalarOp< DstPacketType > = true>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstPacketType packet (Index row, Index col) const
template<int LoadMode, typename DstPacketType , SrcPacketArgs1< DstPacketType > = true>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstPacketType packet (Index row, Index col) const
template<int LoadMode, typename DstPacketType , SrcPacketArgs2< DstPacketType > = true>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstPacketType packet (Index row, Index col) const
template<int LoadMode, typename DstPacketType , SrcPacketArgs4< DstPacketType > = true>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstPacketType packet (Index row, Index col) const
template<int LoadMode, typename DstPacketType , SrcPacketArgs8< DstPacketType > = true>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstPacketType packet (Index row, Index col) const
template<int LoadMode, typename DstPacketType , AltSrcScalarOp< DstPacketType > = true>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstPacketType packet (Index index) const
template<int LoadMode, typename DstPacketType , SrcPacketArgs1< DstPacketType > = true>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstPacketType packet (Index index) const
template<int LoadMode, typename DstPacketType , SrcPacketArgs2< DstPacketType > = true>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstPacketType packet (Index index) const
template<int LoadMode, typename DstPacketType , SrcPacketArgs4< DstPacketType > = true>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstPacketType packet (Index index) const
template<int LoadMode, typename DstPacketType , SrcPacketArgs8< DstPacketType > = true>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstPacketType packet (Index index) const
constexpr EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rows () const
constexpr EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index cols () const
constexpr EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index size () const
Static Public Attributes
static constexpr int SrcPacketSize = unpacket_traits<SrcPacketType>::size
static constexpr int SrcPacketBytes = SrcPacketSize * sizeof(SrcType)
Protected Attributes
const evaluator< ArgType > m_argImpl
const variable_if_dynamic< Index, XprType::RowsAtCompileTime > m_rows
const variable_if_dynamic< Index, XprType::ColsAtCompileTime > m_cols
Member Typedef Documentation
AltSrcScalarOp
template<typename SrcType , typename DstType , typename ArgType > template<typename DstPacketType > using Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::AltSrcScalarOp = std::enable_if_t<(unpacket_traits<DstPacketType>::size < SrcPacketSize && !find_packet_by_size<SrcType, unpacket_traits<DstPacketType>::size>::value), bool>
CastOp
template<typename SrcType , typename DstType , typename ArgType > using Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::CastOp = core_cast_op<SrcType, DstType>
SrcPacketArgs1
template<typename SrcType , typename DstType , typename ArgType > template<typename DstPacketType > using Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::SrcPacketArgs1 = std::enable_if_t<(find_packet_by_size<SrcType, unpacket_traits<DstPacketType>::size>::value), bool>
SrcPacketArgs2
template<typename SrcType , typename DstType , typename ArgType > template<typename DstPacketType > using Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::SrcPacketArgs2 = std::enable_if_t<(unpacket_traits<DstPacketType>::size) == (2 * SrcPacketSize), bool>
SrcPacketArgs4
template<typename SrcType , typename DstType , typename ArgType > template<typename DstPacketType > using Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::SrcPacketArgs4 = std::enable_if_t<(unpacket_traits<DstPacketType>::size) == (4 * SrcPacketSize), bool>
SrcPacketArgs8
template<typename SrcType , typename DstType , typename ArgType > template<typename DstPacketType > using Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::SrcPacketArgs8 = std::enable_if_t<(unpacket_traits<DstPacketType>::size) == (8 * SrcPacketSize), bool>
SrcPacketType
template<typename SrcType , typename DstType , typename ArgType > using Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::SrcPacketType = typename packet_traits<SrcType>::type
XprType
template<typename SrcType , typename DstType , typename ArgType > using Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::XprType = CwiseUnaryOp<CastOp, ArgType>
Member Enumeration Documentation
anonymous enum
template<typename SrcType , typename DstType , typename ArgType > anonymous enum
Enumerator
CoeffReadCost
PacketAccess
ActualPacketAccessBit
Flags
IsRowMajor
Alignment
        {
     CoeffReadCost = int(evaluator<ArgType>::CoeffReadCost) + int(functor_traits<CastOp>::Cost),
     PacketAccess = functor_traits<CastOp>::PacketAccess,
     ActualPacketAccessBit = PacketAccess ? PacketAccessBit : 0,
     Flags = evaluator<ArgType>::Flags & (HereditaryBits | LinearAccessBit | ActualPacketAccessBit),
     IsRowMajor = (evaluator<ArgType>::Flags & RowMajorBit),
     Alignment = evaluator<ArgType>::Alignment
   };
Constructor & Destructor Documentation
unary_evaluator()
template<typename SrcType , typename DstType , typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::unary_evaluator (const XprType & xpr) inline explicit
       : m_argImpl(xpr.nestedExpression()), m_rows(xpr.rows()), m_cols(xpr.cols()) {
     EIGEN_INTERNAL_CHECK_COST_VALUE(functor_traits<CastOp>::Cost);
     EIGEN_INTERNAL_CHECK_COST_VALUE(CoeffReadCost);
   }
References EIGEN_INTERNAL_CHECK_COST_VALUE.
Member Function Documentation
check_array_bounds() [1/3]
template<typename SrcType , typename DstType , typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::check_array_bounds (Index index, Index packetSize) const inline
{
     return index + packetSize <= size();
   }
References size.
check_array_bounds() [2/3]
template<typename SrcType , typename DstType , typename ArgType > template<bool UseRowMajor = IsRowMajor, std::enable_if_t<!UseRowMajor, bool > = true> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::check_array_bounds (Index row, Index , Index packetSize) const inline
{
     return row + packetSize <= rows();
   }
References row(), and rows.
check_array_bounds() [3/3]
template<typename SrcType , typename DstType , typename ArgType > template<bool UseRowMajor = IsRowMajor, std::enable_if_t< UseRowMajor, bool > = true> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::check_array_bounds (Index , Index col, Index packetSize) const inline
{
     return col + packetSize <= cols();
   }
References col(), and cols.
coeff() [1/2]
template<typename SrcType , typename DstType , typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstType Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::coeff (Index index) const inline
{
     return cast<SrcType, DstType>(srcCoeff(index, 0));
   }
coeff() [2/2]
template<typename SrcType , typename DstType , typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstType Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::coeff (Index row, Index col) const inline
{
     return cast<SrcType, DstType>(srcCoeff(row, col, 0));
   }
References col(), and row().
cols()
template<typename SrcType , typename DstType , typename ArgType > constexpr EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::cols () const inline constexpr
 { return m_cols; }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
packet() [1/10]
template<typename SrcType , typename DstType , typename ArgType > template<int LoadMode, typename DstPacketType , AltSrcScalarOp< DstPacketType > = true> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstPacketType Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::packet (Index index) const inline
{
     constexpr int DstPacketSize = unpacket_traits<DstPacketType>::size;
     constexpr int SrcBytesIncrement = DstPacketSize * sizeof(SrcType);
     constexpr int SrcLoadMode = plain_enum_min(SrcBytesIncrement, LoadMode);
     SrcPacketType src;
     if (EIGEN_PREDICT_TRUE(check_array_bounds(index, SrcPacketSize))) {
       src = srcPacket<SrcLoadMode>(index, 0);
     } else {
       Array<SrcType, SrcPacketSize, 1> srcArray;
       for (size_t k = 0; k < DstPacketSize; k++) srcArray[k] = srcCoeff(index, k);
       for (size_t k = DstPacketSize; k < SrcPacketSize; k++) srcArray[k] = SrcType(0);
       src = pload<SrcPacketType>(srcArray.data());
     }
     return pcast<SrcPacketType, DstPacketType>(src);
   }
References Eigen::PlainObjectBase< Derived >::data(), EIGEN_PREDICT_TRUE, k, and Eigen::internal::plain_enum_min().
packet() [2/10]
template<typename SrcType , typename DstType , typename ArgType > template<int LoadMode, typename DstPacketType , SrcPacketArgs1< DstPacketType > = true> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstPacketType Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::packet (Index index) const inline
{
     constexpr int DstPacketSize = unpacket_traits<DstPacketType>::size;
     using SizedSrcPacketType = typename find_packet_by_size<SrcType, DstPacketSize>::type;
     constexpr int SrcBytesIncrement = DstPacketSize * sizeof(SrcType);
     constexpr int SrcLoadMode = plain_enum_min(SrcBytesIncrement, LoadMode);
     return pcast<SizedSrcPacketType, DstPacketType>(srcPacket<SrcLoadMode, SizedSrcPacketType>(index, 0));
   }
References Eigen::internal::plain_enum_min().
packet() [3/10]
template<typename SrcType , typename DstType , typename ArgType > template<int LoadMode, typename DstPacketType , SrcPacketArgs2< DstPacketType > = true> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstPacketType Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::packet (Index index) const inline
{
     constexpr int SrcLoadMode = plain_enum_min(SrcPacketBytes, LoadMode);
     return pcast<SrcPacketType, DstPacketType>(srcPacket<SrcLoadMode>(index, 0), srcPacket<SrcLoadMode>(index, 1));
   }
References Eigen::internal::plain_enum_min().
packet() [4/10]
template<typename SrcType , typename DstType , typename ArgType > template<int LoadMode, typename DstPacketType , SrcPacketArgs4< DstPacketType > = true> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstPacketType Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::packet (Index index) const inline
{
     constexpr int SrcLoadMode = plain_enum_min(SrcPacketBytes, LoadMode);
     return pcast<SrcPacketType, DstPacketType>(srcPacket<SrcLoadMode>(index, 0), srcPacket<SrcLoadMode>(index, 1),
                                                srcPacket<SrcLoadMode>(index, 2), srcPacket<SrcLoadMode>(index, 3));
   }
References Eigen::internal::plain_enum_min().
packet() [5/10]
template<typename SrcType , typename DstType , typename ArgType > template<int LoadMode, typename DstPacketType , SrcPacketArgs8< DstPacketType > = true> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstPacketType Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::packet (Index index) const inline
{
     constexpr int SrcLoadMode = plain_enum_min(SrcPacketBytes, LoadMode);
     return pcast<SrcPacketType, DstPacketType>(srcPacket<SrcLoadMode>(index, 0), srcPacket<SrcLoadMode>(index, 1),
                                                srcPacket<SrcLoadMode>(index, 2), srcPacket<SrcLoadMode>(index, 3),
                                                srcPacket<SrcLoadMode>(index, 4), srcPacket<SrcLoadMode>(index, 5),
                                                srcPacket<SrcLoadMode>(index, 6), srcPacket<SrcLoadMode>(index, 7));
   }
References Eigen::internal::plain_enum_min().
packet() [6/10]
template<typename SrcType , typename DstType , typename ArgType > template<int LoadMode, typename DstPacketType , AltSrcScalarOp< DstPacketType > = true> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstPacketType Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::packet (Index row, Index col) const inline
{
     constexpr int DstPacketSize = unpacket_traits<DstPacketType>::size;
     constexpr int SrcBytesIncrement = DstPacketSize * sizeof(SrcType);
     constexpr int SrcLoadMode = plain_enum_min(SrcBytesIncrement, LoadMode);
     SrcPacketType src;
     if (EIGEN_PREDICT_TRUE(check_array_bounds(row, col, SrcPacketSize))) {
       src = srcPacket<SrcLoadMode>(row, col, 0);
     } else {
       Array<SrcType, SrcPacketSize, 1> srcArray;
       for (size_t k = 0; k < DstPacketSize; k++) srcArray[k] = srcCoeff(row, col, k);
       for (size_t k = DstPacketSize; k < SrcPacketSize; k++) srcArray[k] = SrcType(0);
       src = pload<SrcPacketType>(srcArray.data());
     }
     return pcast<SrcPacketType, DstPacketType>(src);
   }
References col(), Eigen::PlainObjectBase< Derived >::data(), EIGEN_PREDICT_TRUE, k, Eigen::internal::plain_enum_min(), and row().
packet() [7/10]
template<typename SrcType , typename DstType , typename ArgType > template<int LoadMode, typename DstPacketType , SrcPacketArgs1< DstPacketType > = true> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstPacketType Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::packet (Index row, Index col) const inline
{
     constexpr int DstPacketSize = unpacket_traits<DstPacketType>::size;
     using SizedSrcPacketType = typename find_packet_by_size<SrcType, DstPacketSize>::type;
     constexpr int SrcBytesIncrement = DstPacketSize * sizeof(SrcType);
     constexpr int SrcLoadMode = plain_enum_min(SrcBytesIncrement, LoadMode);
     return pcast<SizedSrcPacketType, DstPacketType>(srcPacket<SrcLoadMode, SizedSrcPacketType>(row, col, 0));
   }
References col(), Eigen::internal::plain_enum_min(), and row().
packet() [8/10]
template<typename SrcType , typename DstType , typename ArgType > template<int LoadMode, typename DstPacketType , SrcPacketArgs2< DstPacketType > = true> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstPacketType Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::packet (Index row, Index col) const inline
{
     constexpr int SrcLoadMode = plain_enum_min(SrcPacketBytes, LoadMode);
     return pcast<SrcPacketType, DstPacketType>(srcPacket<SrcLoadMode>(row, col, 0),
                                                srcPacket<SrcLoadMode>(row, col, 1));
   }
References col(), Eigen::internal::plain_enum_min(), and row().
packet() [9/10]
template<typename SrcType , typename DstType , typename ArgType > template<int LoadMode, typename DstPacketType , SrcPacketArgs4< DstPacketType > = true> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstPacketType Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::packet (Index row, Index col) const inline
{
     constexpr int SrcLoadMode = plain_enum_min(SrcPacketBytes, LoadMode);
     return pcast<SrcPacketType, DstPacketType>(srcPacket<SrcLoadMode>(row, col, 0), srcPacket<SrcLoadMode>(row, col, 1),
                                                srcPacket<SrcLoadMode>(row, col, 2),
                                                srcPacket<SrcLoadMode>(row, col, 3));
   }
References col(), Eigen::internal::plain_enum_min(), and row().
packet() [10/10]
template<typename SrcType , typename DstType , typename ArgType > template<int LoadMode, typename DstPacketType , SrcPacketArgs8< DstPacketType > = true> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DstPacketType Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::packet (Index row, Index col) const inline
{
     constexpr int SrcLoadMode = plain_enum_min(SrcPacketBytes, LoadMode);
     return pcast<SrcPacketType, DstPacketType>(
         srcPacket<SrcLoadMode>(row, col, 0), srcPacket<SrcLoadMode>(row, col, 1), srcPacket<SrcLoadMode>(row, col, 2),
         srcPacket<SrcLoadMode>(row, col, 3), srcPacket<SrcLoadMode>(row, col, 4), srcPacket<SrcLoadMode>(row, col, 5),
         srcPacket<SrcLoadMode>(row, col, 6), srcPacket<SrcLoadMode>(row, col, 7));
   }
References col(), Eigen::internal::plain_enum_min(), and row().
rows()
template<typename SrcType , typename DstType , typename ArgType > constexpr EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::rows () const inline constexpr
 { return m_rows; }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
size()
template<typename SrcType , typename DstType , typename ArgType > constexpr EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::size () const inline constexpr
 { return m_rows * m_cols; }
srcCoeff() [1/2]
template<typename SrcType , typename DstType , typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE SrcType Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::srcCoeff (Index index, Index offset) const inline
{
     Index actualIndex = index + offset;
     return m_argImpl.coeff(actualIndex);
   }
srcCoeff() [2/2]
template<typename SrcType , typename DstType , typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE SrcType Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::srcCoeff (Index row, Index col, Index offset) const inline
{
     Index actualRow = IsRowMajor ? row : row + offset;
     Index actualCol = IsRowMajor ? col + offset : col;
     return m_argImpl.coeff(actualRow, actualCol);
   }
References col(), and row().
srcPacket() [1/2]
template<typename SrcType , typename DstType , typename ArgType > template<int LoadMode, typename PacketType = SrcPacketType> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::srcPacket (Index index, Index offset) const inline
{
     constexpr int PacketSize = unpacket_traits<PacketType>::size;
     Index actualIndex = index + (offset * PacketSize);
     eigen_assert(check_array_bounds(actualIndex, PacketSize) && "Array index out of bounds");
     return m_argImpl.template packet<LoadMode, PacketType>(actualIndex);
   }
References eigen_assert.
srcPacket() [2/2]
template<typename SrcType , typename DstType , typename ArgType > template<int LoadMode, typename PacketType = SrcPacketType> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::srcPacket (Index row, Index col, Index offset) const inline
{
     constexpr int PacketSize = unpacket_traits<PacketType>::size;
     Index actualRow = IsRowMajor ? row : row + (offset * PacketSize);
     Index actualCol = IsRowMajor ? col + (offset * PacketSize) : col;
     eigen_assert(check_array_bounds(actualRow, actualCol, PacketSize) && "Array index out of bounds");
     return m_argImpl.template packet<LoadMode, PacketType>(actualRow, actualCol);
   }
References col(), eigen_assert, and row().
Member Data Documentation
m_argImpl
template<typename SrcType , typename DstType , typename ArgType > const evaluator<ArgType> Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::m_argImpl protected
m_cols
template<typename SrcType , typename DstType , typename ArgType > const variable_if_dynamic<Index, XprType::ColsAtCompileTime> Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::m_cols protected
m_rows
template<typename SrcType , typename DstType , typename ArgType > const variable_if_dynamic<Index, XprType::RowsAtCompileTime> Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::m_rows protected
SrcPacketBytes
template<typename SrcType , typename DstType , typename ArgType > constexpr int Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::SrcPacketBytes = SrcPacketSize * sizeof(SrcType) static constexpr
SrcPacketSize
template<typename SrcType , typename DstType , typename ArgType > constexpr int Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::SrcPacketSize = unpacket_traits<SrcPacketType>::size static constexpr
The documentation for this struct was generated from the following file:
CoreEvaluators.h