MercuryDPM: Eigen::internal::Assignment< DstXprType, SparseSymmetricPermutationProduct< MatrixType, Mode >, internal::assign_op< Scalar, typename MatrixType::Scalar >, Sparse2Sparse > Struct Template Reference
Eigen::internal::Assignment< DstXprType, SparseSymmetricPermutationProduct< MatrixType, Mode >, internal::assign_op< Scalar, typename MatrixType::Scalar >, Sparse2Sparse > Struct Template Reference
#include <SparseSelfAdjointView.h>
Public Types
typedef SparseSymmetricPermutationProduct< MatrixType, Mode > SrcXprType
typedef DstXprType::StorageIndex DstIndex
Static Public Member Functions
template<int Options>
static void run (SparseMatrix< Scalar, Options, DstIndex > &dst, const SrcXprType &src, const internal::assign_op< Scalar, typename MatrixType::Scalar > &)
template<typename DestType , unsigned int DestMode>
static void run (SparseSelfAdjointView< DestType, DestMode > &dst, const SrcXprType &src, const internal::assign_op< Scalar, typename MatrixType::Scalar > &)
Member Typedef Documentation
DstIndex
template<typename DstXprType , typename MatrixType , int Mode, typename Scalar > typedef DstXprType::StorageIndex Eigen::internal::Assignment< DstXprType, SparseSymmetricPermutationProduct< MatrixType, Mode >, internal::assign_op< Scalar, typename MatrixType::Scalar >, Sparse2Sparse >::DstIndex
SrcXprType
template<typename DstXprType , typename MatrixType , int Mode, typename Scalar > typedef SparseSymmetricPermutationProduct<MatrixType, Mode> Eigen::internal::Assignment< DstXprType, SparseSymmetricPermutationProduct< MatrixType, Mode >, internal::assign_op< Scalar, typename MatrixType::Scalar >, Sparse2Sparse >::SrcXprType
Member Function Documentation
run() [1/2]
template<typename DstXprType , typename MatrixType , int Mode, typename Scalar > template<int Options> static void Eigen::internal::Assignment< DstXprType, SparseSymmetricPermutationProduct< MatrixType, Mode >, internal::assign_op< Scalar, typename MatrixType::Scalar >, Sparse2Sparse >::run (SparseMatrix< Scalar, Options, DstIndex > & dst, const SrcXprType & src, const internal::assign_op< Scalar, typename MatrixType::Scalar > &) inline static
{
     // internal::permute_symm_to_fullsymm<Mode>(m_matrix,_dest,m_perm.indices().data());
     SparseMatrix<Scalar, (Options & RowMajor) == RowMajor ? ColMajor : RowMajor, DstIndex> tmp;
     internal::permute_symm_to_fullsymm<Mode, false>(src.matrix(), tmp, src.perm().indices().data());
     dst = tmp;
   }
References Eigen::ColMajor, Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::indices(), Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >::matrix(), Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >::perm(), Eigen::RowMajor, and tmp.
run() [2/2]
template<typename DstXprType , typename MatrixType , int Mode, typename Scalar > template<typename DestType , unsigned int DestMode> static void Eigen::internal::Assignment< DstXprType, SparseSymmetricPermutationProduct< MatrixType, Mode >, internal::assign_op< Scalar, typename MatrixType::Scalar >, Sparse2Sparse >::run (SparseSelfAdjointView< DestType, DestMode > & dst, const SrcXprType & src, const internal::assign_op< Scalar, typename MatrixType::Scalar > &) inline static
{
     internal::permute_symm_to_symm<Mode, DestMode, false>(src.matrix(), dst.matrix(), src.perm().indices().data());
   }
References Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::indices(), Eigen::SparseSelfAdjointView< MatrixType, Mode_ >::matrix(), Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >::matrix(), and Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >::perm().
The documentation for this struct was generated from the following file:
SparseSelfAdjointView.h