MercuryDPM: NurbsSurfaceUnitTest.cpp File Reference
NurbsSurfaceUnitTest.cpp File Reference
#include "Nurbs/NurbsSurface.h"
#include "Walls/NurbsWall.h"
#include "Math/Helpers.h"
#include <sstream>
#include <DPMBase.h>
#include <Interactions/NormalForceInteractions/LinearViscoelasticInteraction.h>
#include <Species/LinearViscoelasticSpecies.h>
Functions
int main ()
Function Documentation
main()
int main ()
 {
     //define quarter circle as nurbs surface
     std::vector<double> knotsU = {0,0,0,1,1,1};
     std::vector<double> knotsV = {0,0,1,1};
     std::vector<std::vector<Vec3D>> controlPoints = {{{1,0,0},{1,0,2}},{{1,1,0},{1,1,2}},{{0,1,0},{0,1,2}}} ;
     std::vector<std::vector<Mdouble>> weights = {{1,1},{1,1},{2,2}};
     NurbsSurface nurbsSurface(knotsU,knotsV,controlPoints,weights);
     //output of the unit test: check if evaluation works
     Vec3D val = nurbsSurface.evaluate(0.5,0.5);
     helpers::check(val,{.6,.8,1},std::numeric_limits<double>::epsilon(),"Nurbs evaluation failed");
     //now demonstrate how nurbs wall can be defined:
     //create a basic dpm class
     DPMBase dpm;
     dpm.setName("NurbsSurfaceUnitTest");
     auto s = dpm.speciesHandler.copyAndAddObject(LinearViscoelasticSpecies());
     SphericalParticle p;
     p.setSpecies(s);
     p.setRadius(1);
     p.setPosition({1,1,.2});
     dpm.particleHandler.copyAndAddObject(p);
     //define nurbs wall and add to dpm class
     NurbsWall nurbsWall;
     nurbsWall.setSpecies(s);
     nurbsWall.set(nurbsSurface);
     auto w = dpm.wallHandler.copyAndAddObject(nurbsWall);
     //write vtk file
     dpm.wallHandler.setWriteVTK(FileType::ONE_FILE);
     dpm.forceWriteOutputFiles();
     //test if contact can be found
     Vec3D normal;
     double distance;
     w->getDistanceAndNormal(p,distance,normal);
     helpers::check(normal,{-sqrt(.5),-sqrt(.5),0},4*std::numeric_limits<double>::epsilon(),"Nurbs contact evaluation");
     return 0;
 }
References helpers::check(), oomph::SarahBL::epsilon, NurbsSurface::evaluate(), WallFunction::normal(), ONE_FILE, p, s, NurbsWall::set(), DPMBase::setName(), BaseWall::setSpecies(), sqrt(), calibrate::val, w, and calibrate::weights.