MercuryDPM: Eigen::internal::kissfft_impl< Scalar_ > Struct Template Reference
Eigen::internal::kissfft_impl< Scalar_ > Struct Template Reference
#include <ei_kissfft_impl.h>
Public Types
typedef Scalar_ Scalar
typedef std::complex< Scalar > Complex
Public Member Functions
void clear ()
void fwd (Complex *dst, const Complex *src, int nfft)
void fwd2 (Complex *dst, const Complex *src, int n0, int n1)
void inv2 (Complex *dst, const Complex *src, int n0, int n1)
void fwd (Complex *dst, const Scalar *src, int nfft)
void inv (Complex *dst, const Complex *src, int nfft)
void inv (Scalar *dst, const Complex *src, int nfft)
Protected Types
typedef kiss_cpx_fft< Scalar > PlanData
typedef std::map< int, PlanData > PlanMap
Protected Member Functions
int PlanKey (int nfft, bool isinverse) const
PlanData & get_plan (int nfft, bool inverse)
Complex * real_twiddles (int ncfft2)
Protected Attributes
PlanMap m_plans
std::map< int, std::vector< Complex > > m_realTwiddles
std::vector< Complex > m_tmpBuf1
std::vector< Complex > m_tmpBuf2
Member Typedef Documentation
Complex
template<typename Scalar_ > typedef std::complex<Scalar> Eigen::internal::kissfft_impl< Scalar_ >::Complex
PlanData
template<typename Scalar_ > typedef kiss_cpx_fft<Scalar> Eigen::internal::kissfft_impl< Scalar_ >::PlanData protected
PlanMap
template<typename Scalar_ > typedef std::map<int, PlanData> Eigen::internal::kissfft_impl< Scalar_ >::PlanMap protected
Scalar
template<typename Scalar_ > typedef Scalar_ Eigen::internal::kissfft_impl< Scalar_ >::Scalar
Member Function Documentation
clear()
template<typename Scalar_ > void Eigen::internal::kissfft_impl< Scalar_ >::clear () inline
                {
     m_plans.clear();
     m_realTwiddles.clear();
   }
References Eigen::internal::kissfft_impl< Scalar_ >::m_plans, and Eigen::internal::kissfft_impl< Scalar_ >::m_realTwiddles.
fwd() [1/2]
template<typename Scalar_ > void Eigen::internal::kissfft_impl< Scalar_ >::fwd (Complex * dst, const Complex * src, int nfft) inline
 { get_plan(nfft, false).work(0, dst, src, 1, 1); }
References Eigen::internal::kissfft_impl< Scalar_ >::get_plan(), and Eigen::internal::kiss_cpx_fft< Scalar_ >::work().
Referenced by Eigen::internal::kissfft_impl< Scalar_ >::fwd().
fwd() [2/2]
template<typename Scalar_ > void Eigen::internal::kissfft_impl< Scalar_ >::fwd (Complex * dst, const Scalar * src, int nfft) inline
{
     if (nfft & 3) {
       // use generic mode for odd
       m_tmpBuf1.resize(nfft);
       get_plan(nfft, false).work(0, &m_tmpBuf1[0], src, 1, 1);
       std::copy(m_tmpBuf1.begin(), m_tmpBuf1.begin() + (nfft >> 1) + 1, dst);
     } else {
       int ncfft = nfft >> 1;
       int ncfft2 = nfft >> 2;
       Complex *rtw = real_twiddles(ncfft2);
       // use optimized mode for even real
       fwd(dst, reinterpret_cast<const Complex *>(src), ncfft);
       Complex dc(dst[0].real() + dst[0].imag());
       Complex nyquist(dst[0].real() - dst[0].imag());
       int k;
       for (k = 1; k <= ncfft2; ++k) {
         Complex fpk = dst[k];
         Complex fpnk = conj(dst[ncfft - k]);
         Complex f1k = fpk + fpnk;
         Complex f2k = fpk - fpnk;
         Complex tw = f2k * rtw[k - 1];
         dst[k] = (f1k + tw) * Scalar(.5);
         dst[ncfft - k] = conj(f1k - tw) * Scalar(.5);
       }
       dst[0] = dc;
       dst[ncfft] = nyquist;
     }
   }
References Eigen::conj(), copy(), Eigen::internal::kissfft_impl< Scalar_ >::fwd(), Eigen::internal::kissfft_impl< Scalar_ >::get_plan(), Eigen::imag(), k, Eigen::internal::kissfft_impl< Scalar_ >::m_tmpBuf1, Eigen::real(), Eigen::internal::kissfft_impl< Scalar_ >::real_twiddles(), and Eigen::internal::kiss_cpx_fft< Scalar_ >::work().
fwd2()
template<typename Scalar_ > void Eigen::internal::kissfft_impl< Scalar_ >::fwd2 (Complex * dst, const Complex * src, int n0, int n1) inline
{
     EIGEN_UNUSED_VARIABLE(dst);
     EIGEN_UNUSED_VARIABLE(src);
     EIGEN_UNUSED_VARIABLE(n0);
     EIGEN_UNUSED_VARIABLE(n1);
   }
References EIGEN_UNUSED_VARIABLE.
get_plan()
template<typename Scalar_ > PlanData& Eigen::internal::kissfft_impl< Scalar_ >::get_plan (int nfft, bool inverse) inline protected
{
     // TODO look for PlanKey(nfft, ! inverse) and conjugate the twiddles
     PlanData &pd = m_plans[PlanKey(nfft, inverse)];
     if (pd.m_twiddles.size() == 0) {
       pd.make_twiddles(nfft, inverse);
       pd.factorize(nfft);
     }
     return pd;
   }
References Eigen::internal::kiss_cpx_fft< Scalar_ >::factorize(), inverse(), Eigen::internal::kissfft_impl< Scalar_ >::m_plans, Eigen::internal::kiss_cpx_fft< Scalar_ >::m_twiddles, Eigen::internal::kiss_cpx_fft< Scalar_ >::make_twiddles(), and Eigen::internal::kissfft_impl< Scalar_ >::PlanKey().
Referenced by Eigen::internal::kissfft_impl< Scalar_ >::fwd(), and Eigen::internal::kissfft_impl< Scalar_ >::inv().
inv() [1/2]
template<typename Scalar_ > void Eigen::internal::kissfft_impl< Scalar_ >::inv (Complex * dst, const Complex * src, int nfft) inline
 { get_plan(nfft, true).work(0, dst, src, 1, 1); }
References Eigen::internal::kissfft_impl< Scalar_ >::get_plan(), and Eigen::internal::kiss_cpx_fft< Scalar_ >::work().
Referenced by Eigen::internal::kissfft_impl< Scalar_ >::inv().
inv() [2/2]
template<typename Scalar_ > void Eigen::internal::kissfft_impl< Scalar_ >::inv (Scalar * dst, const Complex * src, int nfft) inline
{
     if (nfft & 3) {
       m_tmpBuf1.resize(nfft);
       m_tmpBuf2.resize(nfft);
       std::copy(src, src + (nfft >> 1) + 1, m_tmpBuf1.begin());
       for (int k = 1; k < (nfft >> 1) + 1; ++k) m_tmpBuf1[nfft - k] = conj(m_tmpBuf1[k]);
       inv(&m_tmpBuf2[0], &m_tmpBuf1[0], nfft);
       for (int k = 0; k < nfft; ++k) dst[k] = m_tmpBuf2[k].real();
     } else {
       // optimized version for multiple of 4
       int ncfft = nfft >> 1;
       int ncfft2 = nfft >> 2;
       Complex *rtw = real_twiddles(ncfft2);
       m_tmpBuf1.resize(ncfft);
       m_tmpBuf1[0] = Complex(src[0].real() + src[ncfft].real(), src[0].real() - src[ncfft].real());
       for (int k = 1; k <= ncfft / 2; ++k) {
         Complex fk = src[k];
         Complex fnkc = conj(src[ncfft - k]);
         Complex fek = fk + fnkc;
         Complex tmp = fk - fnkc;
         Complex fok = tmp * conj(rtw[k - 1]);
         m_tmpBuf1[k] = fek + fok;
         m_tmpBuf1[ncfft - k] = conj(fek - fok);
       }
       get_plan(ncfft, true).work(0, reinterpret_cast<Complex *>(dst), &m_tmpBuf1[0], 1, 1);
     }
   }
References Eigen::conj(), copy(), Eigen::internal::kissfft_impl< Scalar_ >::get_plan(), Eigen::internal::kissfft_impl< Scalar_ >::inv(), k, Eigen::internal::kissfft_impl< Scalar_ >::m_tmpBuf1, Eigen::internal::kissfft_impl< Scalar_ >::m_tmpBuf2, Eigen::real(), Eigen::internal::kissfft_impl< Scalar_ >::real_twiddles(), tmp, and Eigen::internal::kiss_cpx_fft< Scalar_ >::work().
inv2()
template<typename Scalar_ > void Eigen::internal::kissfft_impl< Scalar_ >::inv2 (Complex * dst, const Complex * src, int n0, int n1) inline
{
     EIGEN_UNUSED_VARIABLE(dst);
     EIGEN_UNUSED_VARIABLE(src);
     EIGEN_UNUSED_VARIABLE(n0);
     EIGEN_UNUSED_VARIABLE(n1);
   }
References EIGEN_UNUSED_VARIABLE.
PlanKey()
template<typename Scalar_ > int Eigen::internal::kissfft_impl< Scalar_ >::PlanKey (int nfft, bool isinverse) const inline protected
 { return (nfft << 1) | int(isinverse); }
References int().
Referenced by Eigen::internal::kissfft_impl< Scalar_ >::get_plan().
real_twiddles()
template<typename Scalar_ > Complex* Eigen::internal::kissfft_impl< Scalar_ >::real_twiddles (int ncfft2) inline protected
{
     using std::acos;
     std::vector<Complex> &twidref = m_realTwiddles[ncfft2];  // creates new if not there
     if ((int)twidref.size() != ncfft2) {
       twidref.resize(ncfft2);
       int ncfft = ncfft2 << 1;
       Scalar pi = acos(Scalar(-1));
       for (int k = 1; k <= ncfft2; ++k) twidref[k - 1] = exp(Complex(0, -pi * (Scalar(k) / ncfft + Scalar(.5))));
     }
     return &twidref[0];
   }
References acos(), Eigen::bfloat16_impl::exp(), k, Eigen::internal::kissfft_impl< Scalar_ >::m_realTwiddles, and constants::pi.
Referenced by Eigen::internal::kissfft_impl< Scalar_ >::fwd(), and Eigen::internal::kissfft_impl< Scalar_ >::inv().
Member Data Documentation
m_plans
template<typename Scalar_ > PlanMap Eigen::internal::kissfft_impl< Scalar_ >::m_plans protected
Referenced by Eigen::internal::kissfft_impl< Scalar_ >::clear(), and Eigen::internal::kissfft_impl< Scalar_ >::get_plan().
m_realTwiddles
template<typename Scalar_ > std::map<int, std::vector<Complex> > Eigen::internal::kissfft_impl< Scalar_ >::m_realTwiddles protected
Referenced by Eigen::internal::kissfft_impl< Scalar_ >::clear(), and Eigen::internal::kissfft_impl< Scalar_ >::real_twiddles().
m_tmpBuf1
template<typename Scalar_ > std::vector<Complex> Eigen::internal::kissfft_impl< Scalar_ >::m_tmpBuf1 protected
Referenced by Eigen::internal::kissfft_impl< Scalar_ >::fwd(), and Eigen::internal::kissfft_impl< Scalar_ >::inv().
m_tmpBuf2
template<typename Scalar_ > std::vector<Complex> Eigen::internal::kissfft_impl< Scalar_ >::m_tmpBuf2 protected
Referenced by Eigen::internal::kissfft_impl< Scalar_ >::inv().
The documentation for this struct was generated from the following file:
ei_kissfft_impl.h