MercuryDPM: solid_contact.cc File Reference
solid_contact.cc File Reference
#include <fenv.h>
#include "generic.h"
#include "solid.h"
#include "meshes/triangle_mesh.h"
#include "contact_elements.h"
Classes
class ContactProblem< ELEMENT >
Problem class.
Namespaces
ProblemParameters
Namespace for exact solution and problem parameters.
Functions
int main (int argc, char *argv[])
Driver code.
Variables
double ProblemParameters::Y_c_max =0.0
Initial/max y-position.
Function Documentation
main()
int main (int argc , char * argv[])
Driver code.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
 {
  FiniteElement::Accept_negative_jacobian=true;
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Suppress adaptation
  CommandLineArgs::specify_command_line_flag("--no_adapt");
  // Initial element size
  CommandLineArgs::specify_command_line_flag("--el_area",
                                             &ProblemParameters::El_area);
  // Resolve after adaptation
  // hierher CommandLineArgs::specify_command_line_flag("--resolve_after_adapt");
  // Suppress adaptation
  CommandLineArgs::specify_command_line_flag("--validate");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Create generalised Hookean constitutive equations
  ProblemParameters::Constitutive_law_pt =
   new GeneralisedHookean(&ProblemParameters::Nu);
  // Define centre of penetrator
  ProblemParameters::Centre.resize(2);
  ProblemParameters::Centre[0]=0.5;
  ProblemParameters::Centre[1]=1.15;
  // Initial/max y-position: Lift off the surface by a bit...
  ProblemParameters::Y_c_max=1.0+ProblemParameters::Radius+0.01;
  // Create penetrator
  ProblemParameters::Penetrator_pt =
   new CircularPenetrator(&ProblemParameters::Centre,
                          ProblemParameters::Radius);
  // Build problem
  ContactProblem<ProjectablePVDElement<TPVDElement<2,3> > > problem;
   //Output initial condition
  problem.doc_solution();
  unsigned max_adapt=1;
  if (CommandLineArgs::command_line_flag_has_been_set("--no_adapt"))
   {
    max_adapt=0;
   }
  // Number of parameter increments per period
  unsigned nstep_for_period=40; // 100;
  // Parameter variation
  unsigned nperiod=3;
  // Initial timestep
  double dt=1.0/double(nstep_for_period);
  // Initialise timestep -- also sets the weights for all timesteppers
  // in the problem.
  problem.initialise_dt(dt);
  double t_max=double(nperiod);
  if (CommandLineArgs::command_line_flag_has_been_set("--validate"))
   {
    t_max=10.0*dt;
   }
  //while (ProblemParameters::Centre[1]>1.08)
  while (problem.time_pt()->time()<t_max)
   {
    // Dummy double adaptivity (timestep is always accepted because
    // tolerance is set to huge value; mainly used to automatically
    // re-solve with smaller timestep increment after non-convergence
    double epsilon_t=DBL_MAX;
    bool first=false;
    unsigned suppress_resolve_after_spatial_adapt_flag=1;
    if (CommandLineArgs::command_line_flag_has_been_set("--resolve_after_adapt"))
     {
      suppress_resolve_after_spatial_adapt_flag=0;
     }
    // hierher
    suppress_resolve_after_spatial_adapt_flag=0;
    double next_dt=
     problem.doubly_adaptive_unsteady_newton_solve(
      dt,
      epsilon_t,
      max_adapt,
      suppress_resolve_after_spatial_adapt_flag,
      first);
    dt = next_dt;
    //Output solution
    problem.doc_solution();
   }
 } // end of main
References ProblemParameters::Centre, oomph::CommandLineArgs::command_line_flag_has_been_set(), ProblemParameters::Constitutive_law_pt, oomph::CommandLineArgs::doc_specified_flags(), ProblemParameters::El_area, ProblemParameters::Nu, oomph::CommandLineArgs::parse_and_assign(), ProblemParameters::Penetrator_pt, problem, ProblemParameters::Radius, Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), and ProblemParameters::Y_c_max.