MercuryDPM: oomph::OneDimDiscontinuousGalerkin Namespace Reference
oomph::OneDimDiscontinuousGalerkin Namespace Reference
Functions
template<unsigned NNODE_1D>
void shape (const double &s, double *Psi)
template<unsigned NNODE_1D>
void dshape (const double &s, double *DPsi)
template<unsigned NNODE_1D>
void d2shape (const double &s, double *DPsi)
template<>
void shape< 2 > (const double &s, double *Psi)
1D shape functions specialised to linear order (2 Nodes)
template<>
void dshape< 2 > (const double &s, double *DPsi)
Derivatives of 1D shape functions specialised to linear order (2 Nodes)
template<>
void d2shape< 2 > (const double &s, double *DPsi)
template<>
void shape< 3 > (const double &s, double *Psi)
1D shape functions specialised to quadratic order (3 Nodes)
template<>
void dshape< 3 > (const double &s, double *DPsi)
template<>
void d2shape< 3 > (const double &s, double *DPsi)
template<>
void shape< 4 > (const double &s, double *Psi)
1D shape functions specialised to cubic order (4 Nodes)
template<>
void dshape< 4 > (const double &s, double *DPsi)
Derivatives of 1D shape functions specialised to cubic order (4 Nodes)
template<>
void d2shape< 4 > (const double &s, double *DPsi)
Detailed Description
One dimensional shape functions and derivatives. Empty – simply establishes the template parameters.
Function Documentation
d2shape()
template<unsigned NNODE_1D> void oomph::OneDimDiscontinuousGalerkin::d2shape (const double & s, double * DPsi)
Definition for second derivatives of 1D Lagrange shape functions. The value of all the shape function derivatives at the local coordinate s are returned in the array DPsi.
     {
       // Create an output stream
       std::ostringstream error_stream;
       // Create the error message
       error_stream << "One dimensional Lagrange shape function "
                    << "second derivatives "
                    << "have not been defined "
                    << "for " << NNODE_1D << " nodes." << std::endl;
       // Throw the error message
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
d2shape< 2 >()
template<> void oomph::OneDimDiscontinuousGalerkin::d2shape< 2 > (const double & s, double * DPsi) inline
Second Derivatives of 1D shape functions, specialised to linear order (2 Nodes)
     {
       DPsi[0] = 0.0;
       DPsi[1] = 0.0;
     }
d2shape< 3 >()
template<> void oomph::OneDimDiscontinuousGalerkin::d2shape< 3 > (const double & s, double * DPsi) inline
Second Derivatives of 1D shape functions, specialised to quadratic order (3 Nodes)
     {
       DPsi[0] = 0.0;
       DPsi[1] = 0.0;
       DPsi[2] = 0.0;
     }
d2shape< 4 >()
template<> void oomph::OneDimDiscontinuousGalerkin::d2shape< 4 > (const double & s, double * DPsi) inline
Second derivatives of 1D shape functions specialised to cubic order (4 nodes)
     {
       DPsi[0] = 0.0;
       DPsi[1] = 1.0;
       DPsi[2] = -2.0;
       DPsi[3] = 1.0;
     }
dshape()
template<unsigned NNODE_1D> void oomph::OneDimDiscontinuousGalerkin::dshape (const double & s, double * DPsi)
Definition for derivatives of 1D Lagrange shape functions. The value of all the shape function derivatives at the local coordinate s are returned in the array DPsi.
     {
       // Create an output stream
       std::ostringstream error_stream;
       // Create the error message
       error_stream << "One dimensional Lagrange shape function derivatives "
                    << "have not been defined "
                    << "for " << NNODE_1D << " nodes." << std::endl;
       // Throw the error message
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
dshape< 2 >()
template<> void oomph::OneDimDiscontinuousGalerkin::dshape< 2 > (const double & s, double * DPsi) inline
Derivatives of 1D shape functions specialised to linear order (2 Nodes)
     {
       DPsi[0] = 0.0;
       DPsi[1] = 0.0;
     }
dshape< 3 >()
template<> void oomph::OneDimDiscontinuousGalerkin::dshape< 3 > (const double & s, double * DPsi) inline
Derivatives of 1D shape functions specialised to quadratic order (3 Nodes)
     {
       DPsi[0] = 0.0;
       DPsi[1] = -0.5;
       DPsi[2] = 0.5;
     }
Referenced by oomph::QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_nst().
dshape< 4 >()
template<> void oomph::OneDimDiscontinuousGalerkin::dshape< 4 > (const double & s, double * DPsi) inline
Derivatives of 1D shape functions specialised to cubic order (4 Nodes)
     {
       DPsi[0] = 0.0;
       DPsi[1] = s - 0.5;
       DPsi[2] = -2.0 * s;
       DPsi[3] = s + 0.5;
     }
References s.
shape()
template<unsigned NNODE_1D> void oomph::OneDimDiscontinuousGalerkin::shape (const double & s, double * Psi)
Definition for 1D Lagrange shape functions. The value of all the shape functions at the local coordinate s are returned in the array Psi.
     {
       // Create an output stream
       std::ostringstream error_stream;
       // Create the error message
       error_stream << "One dimensional Lagrange shape functions "
                    << "have not been defined "
                    << "for " << NNODE_1D << " nodes." << std::endl;
       // Throw the error message
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
shape< 2 >()
template<> void oomph::OneDimDiscontinuousGalerkin::shape< 2 > (const double & s, double * Psi) inline
1D shape functions specialised to linear order (2 Nodes)
     {
       Psi[0] = 0.0;
       Psi[1] = 1.0;
     }
shape< 3 >()
template<> void oomph::OneDimDiscontinuousGalerkin::shape< 3 > (const double & s, double * Psi) inline
1D shape functions specialised to quadratic order (3 Nodes)
     {
       Psi[0] = 0.0;
       Psi[1] = 0.5 * (1.0 - s);
       Psi[2] = 0.5 * (1.0 + s);
     }
References s.
Referenced by oomph::QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_nst(), and oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::shape_and_test_at_knot().
shape< 4 >()
template<> void oomph::OneDimDiscontinuousGalerkin::shape< 4 > (const double & s, double * Psi) inline
1D shape functions specialised to cubic order (4 Nodes)
     {
       Psi[0] = 0.0;
       Psi[1] = 0.5 * s * (s - 1.0);
       Psi[2] = 1.0 - s * s;
       Psi[3] = 0.5 * s * (s + 1.0);
     }
References s.