MercuryDPM: oomph::HerschelBulkleyPapRegConstitutiveEquation< DIM > Class Template Reference
oomph::HerschelBulkleyPapRegConstitutiveEquation< DIM > Class Template Reference
#include <generalised_newtonian_constitutive_models.h>
Public Member Functions
HerschelBulkleyPapRegConstitutiveEquation (double *yield_stress_pt, double *flow_index_pt, double *exponential_parameter_pt)
double viscosity (const double &second_invariant_of_rate_of_strain_tensor)
Public Member Functions inherited from oomph::GeneralisedNewtonianConstitutiveEquation< DIM >
GeneralisedNewtonianConstitutiveEquation ()
Empty constructor.
virtual ~GeneralisedNewtonianConstitutiveEquation ()
Empty virtual destructor.
virtual double dviscosity_dinvariant (const double &second_invariant_of_rate_of_strain_tensor)=0
Private Attributes
double * Yield_stress_pt
Yield stress tau_y.
double * Flow_index_pt
Power law index n.
double * Exponential_parameter_pt
Regularisation parameter m >> 1.
Detailed Description
template<unsigned DIM>
class oomph::HerschelBulkleyPapRegConstitutiveEquation< DIM >
A GeneralisedNewtonianConstitutiveEquation class defining a Herschel-Bulkley fluid using Papanastasiou's (1987) regularisation
Constructor & Destructor Documentation
HerschelBulkleyPapRegConstitutiveEquation()
template<unsigned DIM> oomph::HerschelBulkleyPapRegConstitutiveEquation< DIM >::HerschelBulkleyPapRegConstitutiveEquation (double * yield_stress_pt, double * flow_index_pt, double * exponential_parameter_pt) inline
       : GeneralisedNewtonianConstitutiveEquation<DIM>(),
         Yield_stress_pt(yield_stress_pt),
         Flow_index_pt(flow_index_pt),
         Exponential_parameter_pt(exponential_parameter_pt)
     {
     }
Member Function Documentation
viscosity()
template<unsigned DIM> double oomph::HerschelBulkleyPapRegConstitutiveEquation< DIM >::viscosity (const double & second_invariant_of_rate_of_strain_tensor) inline virtual
Function implementing the constitutive model Input: second invariant of the rate of strain Output: the viscosity For Newtonian behaviour this returns 1
Implements oomph::GeneralisedNewtonianConstitutiveEquation< DIM >.
     {
       // Calculate magnitude of the rate of strain tensor
       double measure_of_rate_of_strain =
         sqrt(std::fabs(second_invariant_of_rate_of_strain_tensor));
       return (1.0 - exp(-2.0 * (*Exponential_parameter_pt) *
                         measure_of_rate_of_strain)) /
                (2.0 * measure_of_rate_of_strain) * (*Yield_stress_pt) +
              (1.0 - exp(-2.0 * (*Exponential_parameter_pt) *
                         measure_of_rate_of_strain)) /
                (2.0 * measure_of_rate_of_strain) *
                pow((2.0 * measure_of_rate_of_strain), *Flow_index_pt);
     }
References Eigen::bfloat16_impl::exp(), oomph::HerschelBulkleyPapRegConstitutiveEquation< DIM >::Exponential_parameter_pt, boost::multiprecision::fabs(), oomph::HerschelBulkleyPapRegConstitutiveEquation< DIM >::Flow_index_pt, Eigen::bfloat16_impl::pow(), sqrt(), and oomph::HerschelBulkleyPapRegConstitutiveEquation< DIM >::Yield_stress_pt.
Member Data Documentation
Exponential_parameter_pt
template<unsigned DIM> double* oomph::HerschelBulkleyPapRegConstitutiveEquation< DIM >::Exponential_parameter_pt private
Regularisation parameter m >> 1.
Referenced by oomph::HerschelBulkleyPapRegConstitutiveEquation< DIM >::viscosity().
Flow_index_pt
template<unsigned DIM> double* oomph::HerschelBulkleyPapRegConstitutiveEquation< DIM >::Flow_index_pt private
Power law index n.
Referenced by oomph::HerschelBulkleyPapRegConstitutiveEquation< DIM >::viscosity().
Yield_stress_pt
template<unsigned DIM> double* oomph::HerschelBulkleyPapRegConstitutiveEquation< DIM >::Yield_stress_pt private
Yield stress tau_y.
Referenced by oomph::HerschelBulkleyPapRegConstitutiveEquation< DIM >::viscosity().
The documentation for this class was generated from the following file:
generalised_newtonian_constitutive_models.h