MercuryDPM: oomph::CubicTetMeshFacetedSurface Class Reference
oomph::CubicTetMeshFacetedSurface Class Reference
CubicTetMeshFacetedClosedSurface from (+/- half width)^2 x +/- half length.
#include <tetmesh_faceted_surfaces.h>
Public Member Functions
CubicTetMeshFacetedSurface (const double &box_half_width, const double &box_half_length, const unsigned &one_based_boundary_id_offset=0)
CubicTetMeshFacetedSurface (const double &box_half_width, const double &box_half_length, const Vector< double > &offset, const unsigned &one_based_boundary_id_offset=0)
CubicTetMeshFacetedSurface (const unsigned &one_based_region_id, const double &box_half_width, const double &box_half_length, const unsigned &one_based_boundary_id_offset=0)
CubicTetMeshFacetedSurface (const unsigned &one_based_region_id, const double &box_half_width, const double &box_half_length, const Vector< double > &offset, const unsigned &one_based_boundary_id_offset=0)
Public Member Functions inherited from oomph::TetMeshFacetedClosedSurface
TetMeshFacetedClosedSurface ()
Constructor:
virtual ~TetMeshFacetedClosedSurface ()
Empty destructor.
void enable_faceted_volume_represents_hole_for_gmsh ()
Declare closed surface to represent hole for gmsh.
void disable_faceted_volume_represents_hole_for_gmsh ()
Declare closed surface NOT to represent hole for gmsh.
bool faceted_volume_represents_hole_for_gmsh () const
Does closed surface represent hole for gmsh?
const double & internal_point_for_tetgen (const unsigned &j, const unsigned &i) const
i=th coordinate of the j-th internal point for tetgen
void set_hole_for_tetgen (const Vector< double > &hole_point)
Specify coordinate of hole for tetgen.
void set_region_for_tetgen (const unsigned &region_id, const Vector< double > &region_point)
unsigned ninternal_point_for_tetgen ()
const int & region_id_for_tetgen (const unsigned &j) const
bool internal_point_identifies_hole_for_tetgen (const unsigned &j)
Is j-th internal point for tetgen associated with a hole?
bool internal_point_identifies_region_for_tetgen (const unsigned &j)
Is j-th internal point for tetgen associated with a region?
Public Member Functions inherited from oomph::TetMeshFacetedSurface
TetMeshFacetedSurface ()
Constructor:
virtual ~TetMeshFacetedSurface ()
Empty destructor.
unsigned nvertex () const
Number of vertices.
unsigned nfacet () const
Number of facets.
unsigned one_based_facet_boundary_id (const unsigned &j) const
One-based boundary id of j-th facet.
unsigned one_based_vertex_boundary_id (const unsigned &j) const
First (of possibly multiple) one-based boundary id of j-th vertex.
double vertex_coordinate (const unsigned &j, const unsigned &i) const
i-th coordinate of j-th vertex
unsigned nvertex_on_facet (const unsigned &j) const
Number of vertices defining the j-th facet.
bool boundaries_can_be_split_in_tetgen ()
Test whether boundary can be split in tetgen.
void enable_boundaries_can_be_split_in_tetgen ()
Test whether boundaries can be split in tetgen.
void disable_boundaries_can_be_split_in_tetgen ()
Test whether boundaries can be split in tetgen.
TetMeshFacet * facet_pt (const unsigned &j) const
Pointer to j-th facet.
TetMeshVertex * vertex_pt (const unsigned &j) const
Pointer to j-th vertex.
DiskLikeGeomObjectWithBoundaries * geom_object_with_boundaries_pt ()
void output (std::ostream &outfile) const
Output.
void output (const std::string &filename) const
Output.
virtual void boundary_zeta01 (const unsigned &facet_id, const double &zeta_boundary, Vector< double > &zeta)
virtual void boundary_zeta12 (const unsigned &facet_id, const double &zeta_boundary, Vector< double > &zeta)
virtual void boundary_zeta20 (const unsigned &facet_id, const double &zeta_boundary, Vector< double > &zeta)
Vector< unsigned > vertex_index_in_tetgen (const unsigned &f)
Private Member Functions
void build_it (const unsigned &one_based_region_id, const double &box_half_width, const double &box_half_length, const Vector< double > &offset, const unsigned &one_based_boundary_id_offset)
Build the thing.
Additional Inherited Members
Protected Attributes inherited from oomph::TetMeshFacetedSurface
Vector< TetMeshVertex * > Vertex_pt
Vector pointers to vertices.
Vector< TetMeshFacet * > Facet_pt
Vector of pointers to facets.
bool Boundaries_can_be_split_in_tetgen
Vector< Vector< unsigned > > Facet_vertex_index_in_tetgen
DiskLikeGeomObjectWithBoundaries * Geom_object_with_boundaries_pt
GeomObject with boundaries associated with this surface.
Detailed Description
CubicTetMeshFacetedClosedSurface from (+/- half width)^2 x +/- half length.
//////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
CubicTetMeshFacetedSurface() [1/4]
oomph::CubicTetMeshFacetedSurface::CubicTetMeshFacetedSurface (const double & box_half_width, const double & box_half_length, const unsigned & one_based_boundary_id_offset = 0) inline
Constructor: The six faces are enumerated consecutively starting from boundary_id_offset (defaults to zero in which case the boundaries are enumerated (in one-based fashion) 1,...,6.
   {
    unsigned one_based_region_id=0;
    Vector<double> offset(3,0.0);
    build_it(one_based_region_id,
             box_half_width,
             box_half_length,
             offset,
             one_based_boundary_id_offset);
   }
References build_it().
CubicTetMeshFacetedSurface() [2/4]
oomph::CubicTetMeshFacetedSurface::CubicTetMeshFacetedSurface (const double & box_half_width, const double & box_half_length, const Vector< double > & offset, const unsigned & one_based_boundary_id_offset = 0) inline
Constructor: The six faces are enumerated consecutively starting from boundary_id_offset (defaults to zero in which case the boundaries are enumerated (in one-based fashion) 1,...,6.
   {
    unsigned one_based_region_id=0;
    build_it(one_based_region_id,
             box_half_width,
             box_half_length,
             offset,
             one_based_boundary_id_offset);
   }
References build_it().
CubicTetMeshFacetedSurface() [3/4]
oomph::CubicTetMeshFacetedSurface::CubicTetMeshFacetedSurface (const unsigned & one_based_region_id, const double & box_half_width, const double & box_half_length, const unsigned & one_based_boundary_id_offset = 0) inline
Constructor: Faceted surface defines region with (one-based!) ID one_based_region_id. If this parameter is zero, no region ID is assigned. The six faces are enumerated consecutively starting from boundary_id_offset (defaults to zero in which case the boundaries are enumerated (in one-based fashion) 1,...,6.
   {
    Vector<double> offset(3,0.0);
    build_it(one_based_region_id,
             box_half_width,
             box_half_length,
             offset,
             one_based_boundary_id_offset);
   }
References build_it().
CubicTetMeshFacetedSurface() [4/4]
oomph::CubicTetMeshFacetedSurface::CubicTetMeshFacetedSurface (const unsigned & one_based_region_id, const double & box_half_width, const double & box_half_length, const Vector< double > & offset, const unsigned & one_based_boundary_id_offset = 0) inline
Constructor: Faceted surface defines region with (one-based!) ID one_based_region_id. If this parameter is zero, no region ID is assigned. The six faces are enumerated consecutively starting from boundary_id_offset (defaults to zero in which case the boundaries are enumerated (in one-based fashion) 1,...,6.
   {
    build_it(one_based_region_id,
             box_half_width,
             box_half_length,
             offset,
             one_based_boundary_id_offset);
   }
References build_it().
Member Function Documentation
build_it()
void oomph::CubicTetMeshFacetedSurface::build_it (const unsigned & one_based_region_id, const double & box_half_width, const double & box_half_length, const Vector< double > & offset, const unsigned & one_based_boundary_id_offset) inline private
Build the thing.
   {
    // Make vertices
    unsigned n_vertex=8;
    Vertex_pt.resize(n_vertex);
    Vector<double> box_point(3);
    box_point[0] = offset[0]-box_half_width;
    box_point[1] = offset[1]-box_half_width;
    box_point[2] = offset[2]-box_half_length;
    Vertex_pt[0]=new TetMeshVertex(box_point);
    box_point[0] = offset[0]-box_half_width;
    box_point[1] = offset[1]+box_half_width;
    box_point[2] = offset[2]-box_half_length;
    Vertex_pt[1]=new TetMeshVertex(box_point);
    box_point[0] = offset[0]-box_half_width;
    box_point[1] = offset[1]+box_half_width;
    box_point[2] = offset[2]+box_half_length;
    Vertex_pt[2]=new TetMeshVertex(box_point);
    box_point[0] = offset[0]-box_half_width;
    box_point[1] = offset[1]-box_half_width;
    box_point[2] = offset[2]+box_half_length;
    Vertex_pt[3]=new TetMeshVertex(box_point);
    box_point[0] = offset[0]+box_half_width;
    box_point[1] = offset[1]-box_half_width;
    box_point[2] = offset[2]-box_half_length;
    Vertex_pt[4]=new TetMeshVertex(box_point);
    box_point[0] = offset[0]+box_half_width;
    box_point[1] = offset[1]+box_half_width;
    box_point[2] = offset[2]-box_half_length;
    Vertex_pt[5]=new TetMeshVertex(box_point);
    box_point[0] = offset[0]+box_half_width;
    box_point[1] = offset[1]+box_half_width;
    box_point[2] = offset[2]+box_half_length;
    Vertex_pt[6]=new TetMeshVertex(box_point);
    box_point[0] = offset[0]+box_half_width;
    box_point[1] = offset[1]-box_half_width;
    box_point[2] = offset[2]+box_half_length;
    Vertex_pt[7]=new TetMeshVertex(box_point);
    // Make facets
    unsigned n_facet=6;
    Facet_pt.resize(n_facet);
    unsigned n_vertex_on_facet=4;
    Facet_pt[0]=new TetMeshFacet(n_vertex_on_facet);
    unsigned one_based_boundary_id=1+one_based_boundary_id_offset;
    Facet_pt[0]->set_one_based_boundary_id(one_based_boundary_id);
    Facet_pt[0]->set_vertex_pt(0,Vertex_pt[0]);
    Facet_pt[0]->set_vertex_pt(1,Vertex_pt[4]);
    Facet_pt[0]->set_vertex_pt(2,Vertex_pt[7]);
    Facet_pt[0]->set_vertex_pt(3,Vertex_pt[3]);
    Facet_pt[1]=new TetMeshFacet(n_vertex_on_facet);
    one_based_boundary_id=2+one_based_boundary_id_offset;
    Facet_pt[1]->set_one_based_boundary_id(one_based_boundary_id);
    Facet_pt[1]->set_vertex_pt(0,Vertex_pt[4]);
    Facet_pt[1]->set_vertex_pt(1,Vertex_pt[5]);
    Facet_pt[1]->set_vertex_pt(2,Vertex_pt[6]);
    Facet_pt[1]->set_vertex_pt(3,Vertex_pt[7]);
    // top
    Facet_pt[2]=new TetMeshFacet(n_vertex_on_facet);
    one_based_boundary_id=3+one_based_boundary_id_offset;
    Facet_pt[2]->set_one_based_boundary_id(one_based_boundary_id);
    Facet_pt[2]->set_vertex_pt(0,Vertex_pt[3]);
    Facet_pt[2]->set_vertex_pt(1,Vertex_pt[7]);
    Facet_pt[2]->set_vertex_pt(2,Vertex_pt[6]);
    Facet_pt[2]->set_vertex_pt(3,Vertex_pt[2]);
    Facet_pt[3]=new TetMeshFacet(n_vertex_on_facet);
    one_based_boundary_id=4+one_based_boundary_id_offset;
    Facet_pt[3]->set_one_based_boundary_id(one_based_boundary_id);
    Facet_pt[3]->set_vertex_pt(0,Vertex_pt[6]);
    Facet_pt[3]->set_vertex_pt(1,Vertex_pt[5]);
    Facet_pt[3]->set_vertex_pt(2,Vertex_pt[1]);
    Facet_pt[3]->set_vertex_pt(3,Vertex_pt[2]);
    Facet_pt[4]=new TetMeshFacet(n_vertex_on_facet);
    one_based_boundary_id=5+one_based_boundary_id_offset;
    Facet_pt[4]->set_one_based_boundary_id(one_based_boundary_id);
    Facet_pt[4]->set_vertex_pt(0,Vertex_pt[3]);
    Facet_pt[4]->set_vertex_pt(1,Vertex_pt[2]);
    Facet_pt[4]->set_vertex_pt(2,Vertex_pt[1]);
    Facet_pt[4]->set_vertex_pt(3,Vertex_pt[0]);
    // bottom
    Facet_pt[5]=new TetMeshFacet(n_vertex_on_facet);
    one_based_boundary_id=6+one_based_boundary_id_offset;
    Facet_pt[5]->set_one_based_boundary_id(one_based_boundary_id);
    Facet_pt[5]->set_vertex_pt(0,Vertex_pt[5]);
    Facet_pt[5]->set_vertex_pt(1,Vertex_pt[1]);
    Facet_pt[5]->set_vertex_pt(2,Vertex_pt[0]);
    Facet_pt[5]->set_vertex_pt(3,Vertex_pt[4]);
    // Specify the adjacent region that is bounded by these facets
    for (unsigned f=0;f<6;f++)
     {
      Facet_pt[f]->set_one_based_adjacent_region_id(one_based_region_id);
     }
    // Is it a genuine region?
    if (one_based_region_id>0)
     {
      set_region_for_tetgen(one_based_region_id-1,offset);
     }
    // Otherwise declare it to be a hole
    else
     {
      set_hole_for_tetgen(offset);
      enable_faceted_volume_represents_hole_for_gmsh();
     }
   }
References oomph::TetMeshFacetedClosedSurface::enable_faceted_volume_represents_hole_for_gmsh(), f(), oomph::TetMeshFacetedSurface::Facet_pt, oomph::TetMeshFacetedClosedSurface::set_hole_for_tetgen(), oomph::TetMeshFacetedClosedSurface::set_region_for_tetgen(), and oomph::TetMeshFacetedSurface::Vertex_pt.
Referenced by CubicTetMeshFacetedSurface().
The documentation for this class was generated from the following file:
tetmesh_faceted_surfaces.h