MercuryDPM: refineable_young_laplace.cc File Reference
refineable_young_laplace.cc File Reference
#include "generic.h"
#include "young_laplace.h"
#include "meshes/rectangular_quadmesh.h"
#include "common_young_laplace_stuff.h"
Classes
class RefineableYoungLaplaceProblem< ELEMENT >
Functions
void run_it (const string &output_directory)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
Driver code for 2D RefineableYoungLaplace problem. Input arguments: none (for validation) or case (0,1,2,3 for all pinned, barrel with spines, barrel without spines, and T junction), and number of steps.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Cases to run (By default (validation) run all
  unsigned case_lo=0;
  unsigned case_hi=3;
  // No command line args: Running every case with
  // limited number of steps
  if (CommandLineArgs::Argc==1)
   {
    std::cout
     << "Running every case with limited number of steps for validation"
     << std::endl;
    // Number of steps
    GlobalParameters::Nsteps=2;
   }
  else
   {
    // Which case to run?
    case_lo=atoi(argv[1]);
    case_hi=atoi(argv[1]);
    // Number of steps
    GlobalParameters::Nsteps=atoi(argv[2]);
   }
  // Loop over chosen case(s)
  //-------------------------
  for (unsigned my_case=case_lo;my_case<=case_hi;my_case++)
   {
    // Choose
    switch (my_case)
     {
     case 0:
      cout << endl << endl
           << "//////////////////////////////////////////////////////////\n"
           << "All pinned solution \n"
           << "//////////////////////////////////////////////////////////\n\n";
      GlobalParameters::Case=GlobalParameters::All_pinned;
      // Run with spines
      GlobalParameters::Use_spines=true;
      run_it("RESLT_adapt_all_pinned");
      break;
     case 1:
      cout << endl << endl
           << "//////////////////////////////////////////////////////////\n"
           << "Barrel-shaped solution with spine \n"
           << "/////////////////////////////////////////////////////////\n\n";
      GlobalParameters::Case= GlobalParameters::Barrel_shape;
      GlobalParameters::Controlled_height_increment=0.025;
      GlobalParameters::Use_spines=true;
      run_it("RESLT_adapt_barrel_shape");
      break;
     case 2:
      cout << endl << endl
           << "//////////////////////////////////////////////////////////\n"
           << "Barrel-shaped solution without spines \n"
           << "/////////////////////////////////////////////////////////\n\n";
      GlobalParameters::Case= GlobalParameters::Barrel_shape;
      GlobalParameters::Controlled_height_increment=0.025;
      GlobalParameters::Use_spines=false;
      run_it("RESLT_adapt_barrel_shape_without_spines");
      break;
     case 3:
      cout << endl << endl
           << "//////////////////////////////////////////////////////////\n"
           << "T-junction solution \n"
           << "//////////////////////////////////////////////////////////\n\n";
      GlobalParameters::Case=
       GlobalParameters::T_junction_with_nonzero_contact_angle;
      GlobalParameters::Gamma=MathematicalConstants::Pi/6.0;
      GlobalParameters::L_x=1.0;
      GlobalParameters::L_y=5.0;
      // Run with spines
      GlobalParameters::Use_spines=true;
      run_it("RESLT_adapt_T_junction");
      break;
     default:
      std::cout << "Wrong case! Options are:\n"
                << "0: adaptive All pinned\n"
                << "1: adaptive Barrel with spines\n"
                << "2: adaptive Barrel without spines\n"
                << "3: adaptive T_junction\n"
            << std::endl;
      assert(false);
     }
   }
 } //end of main
References GlobalParameters::All_pinned, oomph::CommandLineArgs::Argc, assert, GlobalParameters::Barrel_shape, GlobalParameters::Case, GlobalParameters::Controlled_height_increment, GlobalParameters::Gamma, GlobalParameters::L_x, GlobalParameters::L_y, GlobalParameters::Nsteps, BiharmonicTestFunctions2::Pi, run_it(), Flag_definition::setup(), GlobalParameters::T_junction_with_nonzero_contact_angle, and GlobalParameters::Use_spines.
run_it()
void run_it (const string & output_directory)
Run code for current setting of parameter values – specify name of output directory
 {
  // Create label for output
  //------------------------
  DocInfo doc_info;
  // Set outputs
  //------------
  // Trace file
  ofstream trace_file;
  // Set output directory
  doc_info.set_directory(output_directory);
  // Open a trace file
  char filename[100];
  sprintf(filename,"%s/trace.dat",doc_info.directory().c_str());
  trace_file.open(filename);
  // Write kappa, exact kappa if exists and height values
  trace_file <<
   "VARIABLES=\"<GREEK>k</GREEK>\",\"<GREEK>k</GREEK>_{ex}\",\"h\""
             << std::endl;
  trace_file << "ZONE" << std::endl;
  //Set up the problem
  //------------------
  // Create the problem with 2D nine-node elements from the
  // RefineableQYoungLaplaceElement family.
  RefineableYoungLaplaceProblem<RefineableQYoungLaplaceElement<3> > problem;
  problem.refine_uniformly();
  //Output the solution
  problem.doc_solution(doc_info,trace_file);
  //Increment counter for solutions
  doc_info.number()++;
  // Parameter incrementation
  //-------------------------
  // Loop over steps
  for (unsigned istep=0;istep<GlobalParameters::Nsteps;istep++)
   {
    // Bump up parameters
    problem.increment_parameters();
    // Solve the problem
    unsigned max_adapt=1;
    problem.newton_solve(max_adapt);
    //Output the solution
    problem.doc_solution(doc_info,trace_file);
    //Increment counter for solutions
    doc_info.number()++;
   }
  // Close output file
  trace_file.close();
 } //end of run_it()
References oomph::DocInfo::directory(), MergeRestartFiles::filename, GlobalParameters::Nsteps, oomph::DocInfo::number(), problem, and oomph::DocInfo::set_directory().
Referenced by main().