MercuryDPM: oomph::RefineableSolidQElement< 3 > Class Reference
oomph::RefineableSolidQElement< 3 > Class Reference
Refineable version of Solid brick elements.
#include <refineable_brick_element.h>
Public Member Functions
RefineableSolidQElement ()
Constructor, just call the constructor of the RefineableQElement<2>
RefineableSolidQElement (const RefineableSolidQElement< 3 > &dummy)=delete
Broken copy constructor.
virtual ~RefineableSolidQElement ()
Broken assignment operator.
void set_macro_elem_pt (MacroElement *macro_elem_pt)
Final over-ride: Use version in QSolidElementBase.
void set_macro_elem_pt (MacroElement *macro_elem_pt, MacroElement *undeformed_macro_elem_pt)
Final over-ride: Use version in QSolidElementBase.
void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void get_face_solid_bcs (const int &edge, Vector< int > &solid_bound_cons) const
void get_solid_bcs (int bound, Vector< int > &solid_bound_cons) const
void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)
Public Member Functions inherited from oomph::RefineableQElement< 3 >
RefineableQElement ()
Constructor: Pass refinement level (default 0 = root)
RefineableQElement (const RefineableQElement< 3 > &dummy)=delete
Broken copy constructor.
virtual ~RefineableQElement ()
Broken assignment operator.
unsigned required_nsons () const
A refineable brick element has eight sons.
virtual Node * node_created_by_neighbour (const Vector< double > &s_fraction, bool &is_periodic)
virtual Node * node_created_by_son_of_neighbour (const Vector< double > &s_fraction, bool &is_periodic)
void check_integrity (double &max_error)
void output_corners (std::ostream &outfile, const std::string &colour) const
Print corner nodes, use colour.
OcTree * octree_pt ()
Pointer to octree representation of this element.
OcTree * octree_pt () const
Pointer to octree representation of this element.
void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
virtual void further_setup_hanging_nodes ()=0
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void rebuild_from_sons (Mesh *&mesh_pt)=0
virtual void unbuild ()
virtual void deactivate_element ()
virtual bool nodes_built ()
Return true if all the nodes have been built, false if not.
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual unsigned ncont_interpolated_values () const =0
virtual void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
virtual void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)=0
virtual Node * interpolating_node_pt (const unsigned &n, const int &value_id)
virtual double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
virtual Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
virtual unsigned ninterpolating_node (const int &value_id)
virtual unsigned ninterpolating_node_1d (const int &value_id)
virtual void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual RefineableElement * root_element_pt ()
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
virtual void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
virtual void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
Pre-build the element.
void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
unsigned nshape_controlling_nodes ()
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (std::ostream &outfile)
virtual void output (std::ostream &outfile, const unsigned &n_plot)
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output (FILE *file_pt)
virtual void output (FILE *file_pt, const unsigned &n_plot)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::BrickElementBase
BrickElementBase ()
Constructor. Empty.
virtual unsigned nvertex_node () const =0
Number of vertex nodes in the element.
virtual Node * vertex_node_pt (const unsigned &j) const =0
Pointer to the j-th vertex node in the element.
Public Member Functions inherited from oomph::QElementBase
QElementBase ()
Constructor: Initialise pointers to macro element reference coords.
QElementBase (const QElementBase &)=delete
Broken copy constructor.
virtual ~QElementBase ()
Broken assignment operator.
bool local_coord_is_valid (const Vector< double > &s)
Check whether the local coordinate are valid or not.
void move_local_coord_back_into_element (Vector< double > &s) const
double & s_macro_ll (const unsigned &i)
double & s_macro_ur (const unsigned &i)
double s_macro_ll (const unsigned &i) const
double s_macro_ur (const unsigned &i) const
void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
unsigned nnode_on_face () const
ElementGeometry::ElementGeometry element_geometry () const
It's a Q element!
Public Member Functions inherited from oomph::QElementGeometricBase
QElementGeometricBase ()
Empty default constructor.
QElementGeometricBase (const QElementGeometricBase &)=delete
Broken copy constructor.
Public Member Functions inherited from oomph::RefineableSolidElement
RefineableSolidElement ()
Constructor.
virtual ~RefineableSolidElement ()
Virtual Destructor, delete any allocated storage.
void assign_solid_local_eqn_numbers (const bool &store_local_dof_pt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void identify_geometric_data (std::set< Data * > &geometric_data_pt)
void fill_in_jacobian_from_solid_position_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
bool is_undeformed_macro_element_used_for_new_lagrangian_coords () const
void enable_use_of_undeformed_macro_element_for_new_lagrangian_coords ()
void disable_use_of_undeformed_macro_element_for_new_lagrangian_coords ()
DenseMatrix< int > & local_position_hang_eqn (Node *const &node_pt)
virtual void further_build ()
Public Member Functions inherited from oomph::SolidFiniteElement
void set_lagrangian_dimension (const unsigned &lagrangian_dimension)
virtual bool has_internal_solid_data ()
SolidFiniteElement ()
Constructor: Set defaults.
virtual ~SolidFiniteElement ()
Destructor to clean up any allocated memory.
SolidFiniteElement (const SolidFiniteElement &)=delete
Broken copy constructor.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void set_undeformed_macro_elem_pt (MacroElement *undeformed_macro_elem_pt)
MacroElement * undeformed_macro_elem_pt ()
Access function to pointer to "undeformed" macro element.
double dshape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi) const
virtual double dshape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi) const
double d2shape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
virtual double d2shape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
unsigned lagrangian_dimension () const
unsigned nnodal_lagrangian_type () const
Node * construct_node (const unsigned &n)
Construct the local node n and return a pointer to it.
Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Node * construct_boundary_node (const unsigned &n)
Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
double raw_lagrangian_position (const unsigned &n, const unsigned &i) const
double raw_lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double lagrangian_position (const unsigned &n, const unsigned &i) const
Return i-th Lagrangian coordinate at local node n.
double lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
virtual double interpolated_xi (const Vector< double > &s, const unsigned &i) const
virtual void interpolated_xi (const Vector< double > &s, Vector< double > &xi) const
virtual void interpolated_dxids (const Vector< double > &s, DenseMatrix< double > &dxids) const
virtual void J_lagrangian (const Vector< double > &s) const
virtual double J_lagrangian_at_knot (const unsigned &ipt) const
SolidInitialCondition *& solid_ic_pt ()
Pointer to object that describes the initial condition.
void enable_solve_for_consistent_newmark_accel ()
void disable_solve_for_consistent_newmark_accel ()
Set to reset the problem being solved to be the standard problem.
MultiplierFctPt & multiplier_fct_pt ()
MultiplierFctPt multiplier_fct_pt () const
virtual void get_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_for_newmark_accel (DenseMatrix< double > &jacobian)
void compute_norm (double &el_norm)
int position_local_eqn (const unsigned &n, const unsigned &k, const unsigned &j) const
Public Member Functions inherited from oomph::QSolidElementBase
QSolidElementBase ()
Constructor: Empty.
QSolidElementBase (const QSolidElementBase &)=delete
Broken copy constructor.
void get_x_and_xi (const Vector< double > &s, Vector< double > &x_fe, Vector< double > &x, Vector< double > &xi_fe, Vector< double > &xi) const
Additional Inherited Members
Public Types inherited from oomph::RefineableQElement< 3 >
typedef void(RefineableQElement< 3 >::* VoidMemFctPt) ()
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Types inherited from oomph::SolidFiniteElement
typedef double(* MultiplierFctPt) (const Vector< double > &xi)
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions inherited from oomph::RefineableQElement< 3 >
void setup_father_bounds ()
void get_face_bcs (const int &edge, Vector< int > &bound_cons) const
void get_boundaries (const int &edge, std::set< unsigned > &boundaries) const
void get_bcs (int bound, Vector< int > &bound_cons) const
void interpolated_zeta_on_face (const unsigned &boundary, const int &face, const Vector< double > &s, Vector< double > &zeta)
void setup_hang_for_value (const int &value_id)
virtual void oc_hang_helper (const int &value_id, const int &my_edge, std::ofstream &output_hangfile)
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::RefineableSolidElement
void assemble_local_to_lagrangian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_lagrangian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
double local_to_lagrangian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Protected Member Functions inherited from oomph::SolidFiniteElement
void fill_in_generic_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
void set_nnodal_lagrangian_type (const unsigned &nlagrangian_type)
virtual double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
void describe_solid_local_dofs (std::ostream &out, const std::string &current_string) const
Classifies dofs locally for solid specific aspects.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_solid_position_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_solid_position_fd ()
virtual void reset_after_solid_position_fd ()
virtual void update_in_solid_position_fd (const unsigned &i)
virtual void reset_in_solid_position_fd (const unsigned &i)
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number – for plotting/validation purposes.
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::RefineableSolidElement
bool Use_undeformed_macro_element_for_new_lagrangian_coords
Protected Attributes inherited from oomph::SolidFiniteElement
MacroElement * Undeformed_macro_elem_pt
Pointer to the element's "undeformed" macro element (NULL by default)
SolidInitialCondition * Solid_ic_pt
Pointer to object that specifies the initial condition.
bool Solve_for_consistent_newmark_accel_flag
Static Protected Attributes inherited from oomph::RefineableQElement< 3 >
static std::map< unsigned, DenseMatrix< int > > Father_bound
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
Refineable version of Solid brick elements.
Constructor & Destructor Documentation
RefineableSolidQElement() [1/2]
oomph::RefineableSolidQElement< 3 >::RefineableSolidQElement () inline
Constructor, just call the constructor of the RefineableQElement<2>
       : RefineableQElement<3>(), RefineableSolidElement()
     {
     }
RefineableSolidQElement() [2/2]
oomph::RefineableSolidQElement< 3 >::RefineableSolidQElement (const RefineableSolidQElement< 3 > & dummy) delete
Broken copy constructor.
~RefineableSolidQElement()
virtual oomph::RefineableSolidQElement< 3 >::~RefineableSolidQElement () inline virtual
Broken assignment operator.
Virtual Destructor
 {}
Member Function Documentation
build()
void oomph::RefineableSolidQElement< 3 >::build (Mesh *& mesh_pt, Vector< Node * > & new_node_pt, bool & was_already_built, std::ofstream & new_nodes_file) inline virtual
Build the element, i.e. give it nodal positions, apply BCs, etc. Incl. documention into new_nodes_file
Reimplemented from oomph::RefineableQElement< 3 >.
     {
       using namespace OcTreeNames;
       // Call the standard (non-elastic) build function
       RefineableQElement<3>::build(
         mesh_pt, new_node_pt, was_already_built, new_nodes_file);
       // Are we done?
       if (was_already_built) return;
       // Now need to loop over the nodes again and set solid variables
       // What type of son am I? Ask my quadtree representation...
       int son_type = octree_pt()->son_type();
       // Which element (!) is my father? (We must have a father
       // since was_already_built is false...)
       RefineableSolidQElement<3>* father_el_pt =
         dynamic_cast<RefineableSolidQElement<3>*>(
           Tree_pt->father_pt()->object_pt());
 #ifdef PARANOID
       // Currently we can't handle the case of generalised coordinates
       // since we haven't established how they should be interpolated
       // Buffer this case:
       if (static_cast<SolidNode*>(father_el_pt->node_pt(0))
             ->nlagrangian_type() != 1)
       {
         throw OomphLibError(
           "We can't handle generalised nodal positions (yet).\n",
           OOMPH_CURRENT_FUNCTION,
           OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Now get coordinates and stuff
       Vector<int> s_lo(3);
       Vector<int> s_hi(3);
       Vector<double> s(3);
       Vector<double> xi(3);
       Vector<double> xi_fe(3);
       Vector<double> x(3);
       Vector<double> x_fe(3);
       // Get the number of 1d nodes
       unsigned n_p = nnode_1d();
       // Setup vertex coordinates in father element:
       //--------------------------------------------
       // find the s_lo coordinates
       s_lo = octree_pt()->Direction_to_vector[son_type];
       // just scale them, because the Direction_to_vector
       // doesn't really gives s_lo;
       for (int i = 0; i < 3; i++)
       {
         s_lo[i] = (s_lo[i] + 1) / 2 - 1;
       }
       // setup s_hi (Actually s_hi[i]=s_lo[i]+1)
       for (int i = 0; i < 3; i++)
       {
         s_hi[i] = s_lo[i] + 1;
       }
       // Pass Undeformed macro element pointer on to sons and
       // set coordinates in macro element
       if (father_el_pt->Undeformed_macro_elem_pt != 0)
       {
         Undeformed_macro_elem_pt = father_el_pt->Undeformed_macro_elem_pt;
         for (unsigned i = 0; i < 3; i++)
         {
           s_macro_ll(i) =
             father_el_pt->s_macro_ll(i) +
             0.5 * (s_lo[i] + 1.0) *
               (father_el_pt->s_macro_ur(i) - father_el_pt->s_macro_ll(i));
           s_macro_ur(i) =
             father_el_pt->s_macro_ll(i) +
             0.5 * (s_hi[i] + 1.0) *
               (father_el_pt->s_macro_ur(i) - father_el_pt->s_macro_ll(i));
         }
       }
       unsigned jnod = 0;
       Vector<double> x_small(3);
       Vector<double> x_large(3);
       Vector<double> s_fraction(3);
       // Loop over nodes in element
       for (unsigned i0 = 0; i0 < n_p; i0++)
       {
         // Get the fractional position of the node in the direction of s[0]
         s_fraction[0] = local_one_d_fraction_of_node(i0, 0);
         // Local coordinate in father element
         s[0] = s_lo[0] + (s_hi[0] - s_lo[0]) * s_fraction[0];
         for (unsigned i1 = 0; i1 < n_p; i1++)
         {
           // Get the fractional position of the node in the direction of s[1]
           s_fraction[1] = local_one_d_fraction_of_node(i1, 1);
           // Local coordinate in father element
           s[1] = s_lo[1] + (s_hi[1] - s_lo[1]) * s_fraction[1];
           for (unsigned i2 = 0; i2 < n_p; i2++)
           {
             // Get the fractional position of the node in the direction of s[2]
             s_fraction[2] = local_one_d_fraction_of_node(i2, 2);
             // Local coordinate in father element
             s[2] = s_lo[2] + (s_hi[2] - s_lo[2]) * s_fraction[2];
             // Local node number
             jnod = i0 + n_p * i1 + n_p * n_p * i2;
             // Get position from father element -- this uses the macro
             // element representation(s) if appropriate. If the node
             // turns out to be a hanging node later on, then
             // its position gets adjusted in line with its
             // hanging node interpolation.
             father_el_pt->get_x_and_xi(s, x_fe, x, xi_fe, xi);
             // Cast the node to an Solid node
             SolidNode* elastic_node_pt = static_cast<SolidNode*>(node_pt(jnod));
             for (unsigned i = 0; i < 3; i++)
             {
               // x_fe is the FE representation -- this is all we can
               // work with in a solid mechanics problem. If you wish
               // to reposition nodes on curvilinear boundaries of
               // a domain to their exact positions on those boundaries
               // you'll have to do this yourself! [Note: We used to
               // use the macro-element-based representation
               // to assign the position of pinned nodes but this is not always
               // correct since pinning doesn't mean "pin in place" or
               // "pin to the curvilinear boundary". For instance, we could
               // impose the boundary displacement manually.
               elastic_node_pt->x(i) = x_fe[i];
               // Lagrangian coordinates can come from undeformed macro element
               if (Use_undeformed_macro_element_for_new_lagrangian_coords)
               {
                 elastic_node_pt->xi(i) = xi[i];
               }
               else
               {
                 elastic_node_pt->xi(i) = xi_fe[i];
               }
             }
             // Are there any history values to be dealt with?
             TimeStepper* time_stepper_pt =
               father_el_pt->node_pt(0)->time_stepper_pt();
             // Number of history values (incl. present)
             unsigned ntstorage = time_stepper_pt->ntstorage();
             if (ntstorage != 1)
             {
               // Loop over # of history values (excluding present which has been
               // done above)
               for (unsigned t = 1; t < ntstorage; t++)
               {
                 // History values can (and in the case of Newmark timestepping,
                 // the scheme most likely to be used for Solid computations, do)
                 // include non-positional values, e.g. velocities and accels.
                 // Set previous positions of the new node
                 for (unsigned i = 0; i < 3; i++)
                 {
                   elastic_node_pt->x(t, i) =
                     father_el_pt->interpolated_x(t, s, i);
                 }
               }
             }
           } // End of s2 loop
         } // End of vertical loop over nodes in element
       } // End of horizontal loop over nodes in element
     }
References oomph::QSolidElementBase::get_x_and_xi(), i, oomph::FiniteElement::interpolated_x(), oomph::SolidNode::nlagrangian_type(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, s, oomph::QElementBase::s_macro_ll(), oomph::QElementBase::s_macro_ur(), plotPSD::t, oomph::Data::time_stepper_pt(), oomph::SolidFiniteElement::Undeformed_macro_elem_pt, plotDoE::x, oomph::Node::x(), and oomph::SolidNode::xi().
get_face_solid_bcs()
void oomph::RefineableSolidQElement< 3 >::get_face_solid_bcs (const int & face, Vector< int > & solid_bound_cons) const
Determine vector of solid (positional) boundary conditions along face (R/L/U/D/B/F) [Pressure does not have to be included since it can't be subjected to bc at more than one node anyway]
Determine Vector of solid (positional) boundary conditions along the element's edge (S/N/W/E) – BC is the least restrictive combination of all the nodes on this edge
Usual convention:
solid_bound_cons[i]=0 if displacement in coordinate direction i on this boundary is free
solid_bound_cons[i]=1 if it's pinned
   {
     using namespace OcTreeNames;
     // Number of nodes along 1D edge
     unsigned n_p = nnode_1d();
     // the four corner nodes on the boundary
     unsigned node1, node2, node3, node4;
     // Set the four corner nodes for the face
     switch (face)
     {
       case U:
         node1 = n_p * n_p * n_p - 1;
         node2 = n_p * n_p - 1;
         node3 = n_p * (n_p - 1);
         node4 = n_p * (n_p * n_p - 1);
         break;
       case D:
         node1 = 0;
         node2 = n_p - 1;
         node3 = (n_p * n_p + 1) * (n_p - 1);
         node4 = n_p * n_p * (n_p - 1);
         break;
       case R:
         node1 = n_p - 1;
         node2 = (n_p * n_p + 1) * (n_p - 1);
         node3 = n_p * n_p * n_p - 1;
         node4 = n_p * n_p - 1;
         break;
       case L:
         node1 = 0;
         node2 = n_p * (n_p - 1);
         node3 = n_p * (n_p * n_p - 1);
         node4 = n_p * n_p * (n_p - 1);
         break;
       case B:
         node1 = 0;
         node2 = n_p - 1;
         node3 = n_p * n_p - 1;
         node4 = n_p * (n_p - 1);
         break;
       case F:
         node1 = n_p * n_p * n_p - 1;
         node2 = n_p * (n_p * n_p - 1);
         node3 = n_p * n_p * (n_p - 1);
         node4 = (n_p - 1) * (n_p * n_p + 1);
         break;
       default:
         std::ostringstream error_stream;
         error_stream << "Wrong edge " << face << " passed\n";
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Cast to solid nodes
     SolidNode* solid_node1_pt = dynamic_cast<SolidNode*>(node_pt(node1));
     SolidNode* solid_node2_pt = dynamic_cast<SolidNode*>(node_pt(node2));
     SolidNode* solid_node3_pt = dynamic_cast<SolidNode*>(node_pt(node3));
     SolidNode* solid_node4_pt = dynamic_cast<SolidNode*>(node_pt(node4));
     //#ifdef PARANOID
     if (solid_node1_pt == 0)
     {
       throw OomphLibError(
         "Corner node 1 cannot be cast to SolidNode --> something is wrong",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
     if (solid_node2_pt == 0)
     {
       throw OomphLibError(
         "Corner node 2 cannot be cast to SolidNode --> something is wrong",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
     if (solid_node3_pt == 0)
     {
       throw OomphLibError(
         "Corner node 3 cannot be cast to SolidNode --> something is wrong",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
     if (solid_node4_pt == 0)
     {
       throw OomphLibError(
         "Corner node 4 cannot be cast to SolidNode --> something is wrong",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
     //#endif
     // Number of coordinates
     unsigned n_dim = this->nodal_dimension();
     // Loop over all directions, the least restrictive value is
     // the multiplication of the boundary conditions at the 4 nodes
     // Assuming that free is always zero and pinned is one
     for (unsigned k = 0; k < n_dim; k++)
     {
       solid_bound_cons[k] = solid_node1_pt->position_is_pinned(k) *
                             solid_node2_pt->position_is_pinned(k) *
                             solid_node3_pt->position_is_pinned(k) *
                             solid_node4_pt->position_is_pinned(k);
     }
   }
References D, oomph::OcTreeNames::F, k, L, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::SolidNode::position_is_pinned(), R, and RachelsAdvectionDiffusion::U.
get_jacobian()
void oomph::RefineableSolidQElement< 3 >::get_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Use the generic finite difference routine defined in RefineableSolidElement to calculate the Jacobian matrix
Reimplemented from oomph::GeneralisedElement.
     {
       RefineableSolidElement::get_jacobian(residuals, jacobian);
     }
References oomph::GeneralisedElement::get_jacobian().
get_solid_bcs()
void oomph::RefineableSolidQElement< 3 >::get_solid_bcs (int bound, Vector< int > & solid_bound_cons) const
Determine vector of solid (positional) boundary conditions along edge (or on vertex) bound (S/W/N/E/SW/SE/NW/NE): For direction i, solid_bound_cons[i]=1 if displacement in this coordinate direction is pinned and 0 if it's free.
Determine vector of solid (positional) boundary conditions along the element's boundary (or vertex) bound (S/W/N/E/SW/SE/NW/NE).
This function assumes that the same boundary condition is applied along the entire length of an element's edge (of course, the vertices combine the boundary conditions of their two adjacent edges in the most restrictive combination. Hence, if we're at a vertex, we apply the most restrictive boundary condition of the two adjacent edges. If we're on an edge (in its proper interior), we apply the least restrictive boundary condition of all nodes along the edge.
Usual convention:
solid_bound_cons[i]=0 if displacement in coordinate direction i on this boundary is free.
solid_bound_cons[i]=1 if it's pinned.
   {
     using namespace OcTreeNames;
     // Spatial dimension of all nodes
     unsigned n_dim = this->nodal_dimension();
     // Set up temporary vectors to hold edge boundary conditions
     Vector<int> bound_cons1(n_dim), bound_cons2(n_dim);
     Vector<int> bound_cons3(n_dim);
     Vector<int> vect1(3), vect2(3), vect3(3);
     Vector<int> vect_elem;
     Vector<int> notzero;
     int n = 0;
     vect_elem = OcTree::Direction_to_vector[bound];
     // Just to see if bound is a face, an edge, or a vertex, n stores
     // the number of non-zero values in the vector reprensenting the bound
     // and the vector notzero stores the position of these values
     for (int i = 0; i < 3; i++)
     {
       if (vect_elem[i] != 0)
       {
         n++;
         notzero.push_back(i);
       }
     }
     switch (n)
     {
         // If there is only one non-zero value, bound is a face
       case 1:
         get_face_solid_bcs(bound, solid_bound_cons);
         break;
         // If there are two non-zero values, bound is an edge
       case 2:
         for (unsigned i = 0; i < 3; i++)
         {
           vect1[i] = 0;
           vect2[i] = 0;
         }
         // vect1 and vect2 are the vector of the two faces adjacent to bound
         vect1[notzero[0]] = vect_elem[notzero[0]];
         vect2[notzero[1]] = vect_elem[notzero[1]];
         get_face_solid_bcs(OcTree::Vector_to_direction[vect1], bound_cons1);
         get_face_solid_bcs(OcTree::Vector_to_direction[vect2], bound_cons2);
         // get the most restrictive bc
         for (unsigned k = 0; k < n_dim; k++)
         {
           solid_bound_cons[k] = (bound_cons1[k] || bound_cons2[k]);
         }
         break;
         // If there are three non-zero value, bound is a vertex
       case 3:
         for (unsigned i = 0; i < 3; i++)
         {
           vect1[i] = 0;
           vect2[i] = 0;
           vect3[i] = 0;
         }
         // vectors to the three adjacent faces of the vertex
         vect1[0] = vect_elem[0];
         vect2[1] = vect_elem[1];
         vect3[2] = vect_elem[2];
         get_face_solid_bcs(OcTree::Vector_to_direction[vect1], bound_cons1);
         get_face_solid_bcs(OcTree::Vector_to_direction[vect2], bound_cons2);
         get_face_solid_bcs(OcTree::Vector_to_direction[vect3], bound_cons3);
         // set the bcs to the most restrictive ones
         for (unsigned k = 0; k < n_dim; k++)
         {
           solid_bound_cons[k] =
             (bound_cons1[k] || bound_cons2[k] || bound_cons3[k]);
         }
         break;
       default:
         throw OomphLibError("Make sure you are not giving  OMEGA as bound",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
     }
   }
References oomph::OcTree::Direction_to_vector, i, k, n, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::OcTree::Vector_to_direction.
Referenced by oomph::RefineableQElement< 3 >::build(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::rebuild_from_sons(), and oomph::RefineableQSpectralElement< 3 >::rebuild_from_sons().
set_macro_elem_pt() [1/2]
void oomph::RefineableSolidQElement< 3 >::set_macro_elem_pt (MacroElement * macro_elem_pt) inline virtual
Final over-ride: Use version in QSolidElementBase.
Reimplemented from oomph::QSolidElementBase.
     {
       QSolidElementBase::set_macro_elem_pt(macro_elem_pt);
     }
References oomph::QSolidElementBase::set_macro_elem_pt().
set_macro_elem_pt() [2/2]
void oomph::RefineableSolidQElement< 3 >::set_macro_elem_pt (MacroElement * macro_elem_pt, MacroElement * undeformed_macro_elem_pt) inline virtual
Final over-ride: Use version in QSolidElementBase.
Reimplemented from oomph::QSolidElementBase.
     {
       QSolidElementBase::set_macro_elem_pt(macro_elem_pt,
                                            undeformed_macro_elem_pt);
     }
References oomph::QSolidElementBase::set_macro_elem_pt().
The documentation for this class was generated from the following files:
refineable_brick_element.h
refineable_brick_element.cc