MercuryDPM: PeriodicWallsUnitTest.cpp File Reference
PeriodicWallsUnitTest.cpp File Reference
#include "Mercury2D.h"
#include "Boundaries/PeriodicBoundary.h"
#include "Species/LinearViscoelasticSpecies.h"
#include <Logger.h>
Classes
class PeriodicWalls
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
Start off my solving the default problem
 {
     PeriodicWalls problem;
     LinearViscoelasticSpecies species;
     species.setDensity(2000);
     species.setStiffness(10000);
     species.setDissipation(1);
     problem.speciesHandler.copyAndAddObject(species);
     problem.setTimeMax(0.11);
     problem.setTimeStep(1.1e-05);
     problem.setSaveCount(helpers::getSaveCountFromNumberOfSavesAndTimeMaxAndTimeStep(20, problem.getTimeMax(),
                                                                                      problem.getTimeStep()));
     problem.setName("PeriodicWallsUnitTest");
     problem.solve();
     Vec3D goodPos;
     Vec3D goodVel;
     std::vector<BaseParticle*>::iterator pIt = problem.particleHandler.begin();
     goodPos = Vec3D(0.00950076062215577, 0.002, 0);
     goodVel = Vec3D(-0.005560409816604, 0, 0);
     if (!(*pIt)->getPosition().isEqualTo(goodPos, 1e-10))
     {
         logger(FATAL, "E0 The particle is in the wrong position. It is %, however is should be %",
                (*pIt)->getPosition(), goodPos);
     }
     if (!(*pIt)->getVelocity().isEqualTo(goodVel, 1e-10))
     {
         logger(FATAL, "E0 The particle has the wrong velocity. It is %, however is should be %", (*pIt)->getVelocity(),
                goodVel);
     }
     ++pIt;
     goodPos = Vec3D(0.000725163257251641, 0.002, 0);
     goodVel = Vec3D(-0.000808302139899, 0, 0);
     if (!(*pIt)->getPosition().isEqualTo(goodPos, 1e-10))
     {
         logger(FATAL, "E1 The particle is in the wrong position. It is %, however is should be %",
                (*pIt)->getPosition(), goodPos);
     }
     if (!(*pIt)->getVelocity().isEqualTo(goodVel, 1e-10))
     {
         logger(FATAL, "E1 The particle has the wrong velocity. It is %, however is should be %", (*pIt)->getVelocity(),
                goodVel);
     }
     ++pIt;
     goodPos = Vec3D(0.00950076062215577, 0.003, 0);
     goodVel = Vec3D(-0.005560409816604, 0, 0);
     if (!(*pIt)->getPosition().isEqualTo(goodPos, 1e-10))
     {
         logger(FATAL, "E2 The particle is in the wrong position. It is %, however is should be %",
                (*pIt)->getPosition(), goodPos);
     }
     if (!(*pIt)->getVelocity().isEqualTo(goodVel, 1e-10))
     {
         logger(FATAL, "E2 The particle has the wrong velocity. It is %, however is should be %", (*pIt)->getVelocity(),
                goodVel);
     }
     ++pIt;
     goodPos = Vec3D(0.000725163257251641, 0.003, 0);
     goodVel = Vec3D(-0.000808302139899, 0, 0);
     if (!(*pIt)->getPosition().isEqualTo(goodPos, 1e-10))
     {
         logger(FATAL, "E3 The particle is in the wrong position. It is %, however is should be %",
                (*pIt)->getPosition(), goodPos);
     }
     if (!(*pIt)->getVelocity().isEqualTo(goodVel, 1e-10))
     {
         logger(FATAL, "E3 The particle has the wrong velocity. It is %, however is should be %", (*pIt)->getVelocity(),
                goodVel);
     }
     ++pIt;
     goodPos = Vec3D(0.0004992393778432442, 0.004, 0);
     goodVel = Vec3D(0.00556040981661, 0, 0);
     if (!(*pIt)->getPosition().isEqualTo(goodPos, 1e-10))
     {
         logger(FATAL, "E4 The particle is in the wrong position. It is %, however is should be %",
                (*pIt)->getPosition(), goodPos);
     }
     if (!(*pIt)->getVelocity().isEqualTo(goodVel, 1e-10))
     {
         logger(FATAL, "E4 The particle has the wrong velocity. It is %, however is should be %", (*pIt)->getVelocity(),
                goodVel);
     }
     ++pIt;
     goodPos = Vec3D(0.00927483674274562, 0.004, 0);
     goodVel = Vec3D(0.0008083021398896, 0, 0);
     if (!(*pIt)->getPosition().isEqualTo(goodPos, 1e-10))
     {
         logger(FATAL, "E5 The particle is in the wrong position. It is %, however is should be %",
                (*pIt)->getPosition(), goodPos);
     }
     if (!(*pIt)->getVelocity().isEqualTo(goodVel, 1e-10))
     {
         logger(FATAL, "E5 The particle has the wrong velocity. It is %, however is should be %", (*pIt)->getVelocity(),
                goodVel);
     }
     ++pIt;
     goodPos = Vec3D(0.000499239377843248, 0.005, 0);
     goodVel = Vec3D(0.00556040981661, 0, 0);
     if (!(*pIt)->getPosition().isEqualTo(goodPos, 1e-10))
     {
         logger(FATAL, "E6 The particle is in the wrong position. It is %, however is should be %",
                (*pIt)->getPosition(), goodPos);
     }
     if (!(*pIt)->getVelocity().isEqualTo(goodVel, 1e-10))
     {
         logger(FATAL, "E6 The particle has the wrong velocity. It is %, however is should be %", (*pIt)->getVelocity(),
                goodVel);
     }
     ++pIt;
     goodPos = Vec3D(0.00927483674274562, 0.005, 0);
     goodVel = Vec3D(0.0008083021398892, 0, 0);
     if (!(*pIt)->getPosition().isEqualTo(goodPos, 1e-10))
     {
         logger(FATAL, "E7 The particle is in the wrong position. It is %, however is should be %",
                (*pIt)->getPosition(), goodPos);
     }
     if (!(*pIt)->getVelocity().isEqualTo(goodVel, 1e-10))
     {
         logger(FATAL, "E7 The particle has the wrong velocity. It is %, however is should be %", (*pIt)->getVelocity(),
                goodVel);
     }
     ++pIt;
     goodPos = Vec3D(0.00149923937784423, 0.006, 0);
     goodVel = Vec3D(0.005560409816606, 0, 0);
     if (!(*pIt)->getPosition().isEqualTo(goodPos, 1e-10))
     {
         logger(FATAL, "E8 The particle is in the wrong position. It is %, however is should be %",
                (*pIt)->getPosition(), goodPos);
     }
     if (!(*pIt)->getVelocity().isEqualTo(goodVel, 1e-10))
     {
         logger(FATAL, "E8 The particle has the wrong velocity. It is %, however is should be %", (*pIt)->getVelocity(),
                goodVel);
     }
     ++pIt;
     goodPos = Vec3D(0.000274836742748357, 0.006, 0);
     goodVel = Vec3D(0.0008083021398959, 0, 0);
     if (!(*pIt)->getPosition().isEqualTo(goodPos, 1e-10))
     {
         logger(FATAL, "E9 The particle is in the wrong position. It is %, however is should be %",
                (*pIt)->getPosition(), goodPos);
     }
     if (!(*pIt)->getVelocity().isEqualTo(goodVel, 1e-10))
     {
         logger(FATAL, "E9 The particle has the wrong velocity. It is %, however is should be %", (*pIt)->getVelocity(),
                goodVel);
     }
     ++pIt;
     goodPos = Vec3D(0.000368955529803987, 0.000368955529803987, 0);
     goodVel = Vec3D(0.005560480643586, 0.005560480643586, 0);
     if (!(*pIt)->getPosition().isEqualTo(goodPos, 1e-10))
     {
         logger(FATAL, "E10 The particle is in the wrong position. It is %, however is should be %",
                (*pIt)->getPosition(), goodPos);
     }
     if (!(*pIt)->getVelocity().isEqualTo(goodVel, 1e-10))
     {
         logger(FATAL, "E10 The particle has the wrong velocity. It is %, however is should be %", (*pIt)->getVelocity(),
                goodVel);
     }
     ++pIt;
     goodPos = Vec3D(0.0094902039201126, 0.0094902039201126, 0);
     goodVel = Vec3D(0.0008081850585628, 0.0008081850585628, 0);
     if (!(*pIt)->getPosition().isEqualTo(goodPos, 1e-10))
     {
         logger(FATAL, "E11 The particle is in the wrong position. It is %, however is should be %",
                (*pIt)->getPosition(), goodPos);
     }
     if (!(*pIt)->getVelocity().isEqualTo(goodVel, 1e-10))
     {
         logger(FATAL, "E11 The particle has the wrong velocity. It is %, however is should be %", (*pIt)->getVelocity(),
                goodVel);
     }
     ++pIt;
     goodPos = Vec3D(0.00963104447019111, 0.00963104447019111, 0.001);
     goodVel = Vec3D(-0.005560480643562, -0.005560480643562, 0);
     if (!(*pIt)->getPosition().isEqualTo(goodPos, 1e-10))
     {
         logger(FATAL, "E12 The particle is in the wrong position. It is %, however is should be %",
                (*pIt)->getPosition(), goodPos);
     }
     if (!(*pIt)->getVelocity().isEqualTo(goodVel, 1e-10))
     {
         logger(FATAL, "E12 The particle has the wrong velocity. It is %, however is should be %", (*pIt)->getVelocity(),
                goodVel);
     }
     ++pIt;
     goodPos = Vec3D(0.00050979607988006, 0.00050979607988006, 0.001);
     goodVel = Vec3D(-0.0008081850586013, -0.0008081850586013, 0);
     if (!(*pIt)->getPosition().isEqualTo(goodPos, 1e-10))
     {
         logger(FATAL, "E13 The particle is in the wrong position. It is %, however is should be %",
                (*pIt)->getPosition(), goodPos);
     }
     if (!(*pIt)->getVelocity().isEqualTo(goodVel, 1e-10))
     {
         logger(FATAL, "E13 The particle has the wrong velocity. It is %, however is should be %",
                (*pIt)->getVelocity(), goodVel);
     }
 }
References e(), FATAL, helpers::getSaveCountFromNumberOfSavesAndTimeMaxAndTimeStep(), logger, problem, ParticleSpecies::setDensity(), LinearViscoelasticNormalSpecies::setDissipation(), and LinearViscoelasticNormalSpecies::setStiffness().