MercuryDPM: oomph::WomersleyMesh< WOMERSLEY_ELEMENT > Class Template Reference
oomph::WomersleyMesh< WOMERSLEY_ELEMENT > Class Template Reference
#include <womersley_elements.h>
Public Member Functions
WomersleyMesh (Mesh *n_st_outflow_mesh_pt, TimeStepper *time_stepper_pt, const unsigned &fixed_coordinate, const unsigned &w_index)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void setup_boundary_element_info ()
virtual void setup_boundary_element_info (std::ostream &outfile)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Static Public Attributes inherited from oomph::TemplateFreeWomersleyMeshBase
static bool Suppress_warning_about_unpinned_nst_dofs
Static bool to suppress warning.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Detailed Description
template<class WOMERSLEY_ELEMENT>
class oomph::WomersleyMesh< WOMERSLEY_ELEMENT >
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Mesh of Womersley elements whose topology, nodal position etc. matches that of a given mesh of face elements in the outflow cross-section of a full Navier-Stokes mesh.
Constructor & Destructor Documentation
WomersleyMesh()
template<class WOMERSLEY_ELEMENT > oomph::WomersleyMesh< WOMERSLEY_ELEMENT >::WomersleyMesh (Mesh * n_st_outflow_mesh_pt, TimeStepper * time_stepper_pt, const unsigned & fixed_coordinate, const unsigned & w_index) inline
Constructor: Pass pointer to mesh of face elements in the outflow cross-section of a full Navier-Stokes mesh, the timestepper to be used for the Womersley elements, the coordinate (in the higher-dimensional Navier-Stokes mesh) that is constant in the outflow cross-section and the velocity component (in terms of the nodal index) that represents the outflow component – the latter is used to automatically apply the boundary conditions for the Womersley problem.
How many elements and nodes are there in the original mesh?
Create new elements
     {
       unsigned nelem = n_st_outflow_mesh_pt->nelement();
       // Navier-Stokes outflow mesh may not have any nodes stored (it usually
       // just acts as a container for traction elements) -->
       // Count number of distinct Navier-Stokes nodes by adding
       // the elements' nodes to a set
       std::set<Node*> n_st_nodes;
       for (unsigned e = 0; e < nelem; e++)
       {
         FiniteElement* el_pt = n_st_outflow_mesh_pt->finite_element_pt(e);
         unsigned nnod_el = el_pt->nnode();
         for (unsigned j = 0; j < nnod_el; j++)
         {
           n_st_nodes.insert(el_pt->node_pt(j));
           // Careful: It there are hanging nodes this won't work!
           if (el_pt->node_pt(j)->is_hanging())
           {
             throw OomphLibError(
               "Cannot build WomersleyMesh from mesh with hanging nodes!",
               OOMPH_CURRENT_FUNCTION,
               OOMPH_EXCEPTION_LOCATION);
           }
         }
       }
       // Extract size then wipe
       unsigned nnode_n_st = n_st_nodes.size();
       n_st_nodes.clear();
       // Create enough storage
       Node_pt.resize(nnode_n_st);
       for (unsigned e = 0; e < nelem; e++)
       {
         add_element_pt(new WOMERSLEY_ELEMENT);
 #ifdef PARANOID
         if (finite_element_pt(e)->nnode() !=
             n_st_outflow_mesh_pt->finite_element_pt(e)->nnode())
         {
           throw OomphLibError(
             "Number of nodes in existing and new elements don't match",
             OOMPH_CURRENT_FUNCTION,
             OOMPH_EXCEPTION_LOCATION);
         }
 #endif
       }
       // Map to record which Navier-Stokes nodes have been visited (default
       // return is false)
       std::map<Node*, bool> n_st_node_done;
       // Map to store the Womersley node that corresponds to a
       // Navier Stokes node
       std::map<Node*, Node*> equivalent_womersley_node_pt;
       // Initialise count of newly created nodes
       unsigned node_count = 0;
       // This is awkward do diagnose: We're assuming that
       // the boundary conditions have been applied for the
       // underlying Navier-Stokes problem before calling
       // this function (otherwise it's really tricky to
       // apply the right boundary conditions here), but it's
       // hard to police. Issue definite (but suppressable)
       // warning if nothing has been pinned at all.
       unsigned n_pinned_nodes = 0;
       // Loop over nst and womersley elements in tandem to sort out
       // which new nodes are required
       for (unsigned e = 0; e < nelem; e++)
       {
         FiniteElement* n_st_el_pt = n_st_outflow_mesh_pt->finite_element_pt(e);
         unsigned nnod_el = n_st_el_pt->nnode();
         for (unsigned j = 0; j < nnod_el; j++)
         {
           // Has the Navier Stokes node been done yet?
           Node* n_st_node_pt = n_st_el_pt->node_pt(j);
           // Hasn't been done: Create new node in Womersley element
           if (!n_st_node_done[n_st_node_pt])
           {
             // Create a new node in the Womersley element
             Node* new_node_pt =
               finite_element_pt(e)->construct_node(j, time_stepper_pt);
             // Add newly created node
             Node_pt[node_count] = new_node_pt;
             node_count++;
             // Set coordinates
             unsigned dim = n_st_node_pt->ndim();
             unsigned icount = 0;
             for (unsigned i = 0; i < dim; i++)
             {
               if (i != fixed_coordinate)
               {
                 new_node_pt->x(icount) = n_st_node_pt->x(i);
                 icount++;
               }
             }
             // Set pin status
             if (n_st_node_pt->is_pinned(w_index))
             {
               new_node_pt->pin(0);
               n_pinned_nodes++;
             }
             else
             {
               // shouldn't need this, but...
               new_node_pt->unpin(0);
             }
             // Record which Womersley node the
             // Navier Stokes node is associated with
             equivalent_womersley_node_pt[n_st_node_pt] = new_node_pt;
             // Now the Navier-Stokes node has been done
             n_st_node_done[n_st_node_pt] = true;
           }
           // The node has already been done -- set pointer to existing
           // Womersley node
           else
           {
             finite_element_pt(e)->node_pt(j) =
               equivalent_womersley_node_pt[n_st_node_pt];
           }
         }
         bool passed = true;
         finite_element_pt(e)->check_J_eulerian_at_knots(passed);
         if (!passed)
         {
           // Reverse the nodes
           unsigned nnod = finite_element_pt(e)->nnode();
           Vector<Node*> orig_nod_pt(nnod);
           for (unsigned j = 0; j < nnod; j++)
           {
             orig_nod_pt[j] = finite_element_pt(e)->node_pt(j);
           }
           for (unsigned j = 0; j < nnod; j++)
           {
             finite_element_pt(e)->node_pt(j) = orig_nod_pt[nnod - j - 1];
           }
           bool passed = true;
           finite_element_pt(e)->check_J_eulerian_at_knots(passed);
           if (!passed)
           {
             throw OomphLibError("Element remains inverted even after reversing "
                                 "the local node numbers",
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
           }
         }
       }
 #ifdef PARANOID
       if (!Suppress_warning_about_unpinned_nst_dofs)
       {
         if (n_pinned_nodes == 0)
         {
           std::stringstream bla;
           bla << "Boundary conditions must be applied in Navier-Stokes\n"
               << "problem before attaching impedance elements.\n"
               << "Note: This warning can be suppressed by setting the\n"
               << "global static boolean\n\n"
               << "     "
                  "TemplateFreeWomersleyMeshBase::Suppress_warning_about_"
                  "unpinned_nst_dofs\n\n"
               << "to true\n";
           OomphLibWarning(
             bla.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
         }
       }
 #endif
 #ifdef PARANOID
       if (nnode() != nnode_n_st)
       {
         throw OomphLibError(
           "Number of nodes in the new mesh don't match that in the old one",
           OOMPH_CURRENT_FUNCTION,
           OOMPH_EXCEPTION_LOCATION);
       }
 #endif
     }
References oomph::Mesh::add_element_pt(), oomph::FiniteElement::check_J_eulerian_at_knots(), oomph::FiniteElement::construct_node(), e(), oomph::Mesh::finite_element_pt(), i, oomph::Node::is_hanging(), oomph::Data::is_pinned(), j, oomph::Node::ndim(), oomph::Mesh::nelement(), oomph::FiniteElement::nnode(), oomph::Mesh::nnode(), oomph::FiniteElement::node_pt(), oomph::Mesh::Node_pt, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Data::pin(), oomph::TemplateFreeWomersleyMeshBase::Suppress_warning_about_unpinned_nst_dofs, oomph::Data::unpin(), and oomph::Node::x().
The documentation for this class was generated from the following file:
womersley_elements.h