MercuryDPM: Eigen::KroneckerProductBase< Derived > Class Template Reference
Eigen::KroneckerProductBase< Derived > Class Template Reference
The base class of dense and sparse Kronecker product.
#include <KroneckerTensorProduct.h>
Public Member Functions
KroneckerProductBase (const Lhs &A, const Rhs &B)
Constructor.
Index rows () const
Index cols () const
Scalar coeff (Index row, Index col) const
Scalar coeff (Index i) const
Public Member Functions inherited from Eigen::ReturnByValue< Derived >
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Protected Types
typedef Traits::Lhs Lhs
typedef Traits::Rhs Rhs
Protected Attributes
Lhs::Nested m_A
Rhs::Nested m_B
Private Types
typedef internal::traits< Derived > Traits
typedef Traits::Scalar Scalar
Additional Inherited Members
Public Types inherited from Eigen::ReturnByValue< Derived >
typedef internal::traits< Derived >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Detailed Description
template<typename Derived>
class Eigen::KroneckerProductBase< Derived >
The base class of dense and sparse Kronecker product.
Template Parameters
Derived is the derived type.
Member Typedef Documentation
Lhs
template<typename Derived > typedef Traits::Lhs Eigen::KroneckerProductBase< Derived >::Lhs protected
Rhs
template<typename Derived > typedef Traits::Rhs Eigen::KroneckerProductBase< Derived >::Rhs protected
Scalar
template<typename Derived > typedef Traits::Scalar Eigen::KroneckerProductBase< Derived >::Scalar private
Traits
template<typename Derived > typedef internal::traits<Derived> Eigen::KroneckerProductBase< Derived >::Traits private
Constructor & Destructor Documentation
KroneckerProductBase()
template<typename Derived > Eigen::KroneckerProductBase< Derived >::KroneckerProductBase (const Lhs & A, const Rhs & B) inline
Constructor.
 : m_A(A), m_B(B) {}
Member Function Documentation
coeff() [1/2]
template<typename Derived > Scalar Eigen::KroneckerProductBase< Derived >::coeff (Index i) const inline
This overrides ReturnByValue::coeff because this function is efficient enough.
{
     EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived);
     return m_A.coeff(i / m_A.size()) * m_B.coeff(i % m_A.size());
   }
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, i, Eigen::KroneckerProductBase< Derived >::m_A, and Eigen::KroneckerProductBase< Derived >::m_B.
coeff() [2/2]
template<typename Derived > Scalar Eigen::KroneckerProductBase< Derived >::coeff (Index row, Index col) const inline
This overrides ReturnByValue::coeff because this function is efficient enough.
{
     return m_A.coeff(row / m_B.rows(), col / m_B.cols()) * m_B.coeff(row % m_B.rows(), col % m_B.cols());
   }
References col(), Eigen::KroneckerProductBase< Derived >::m_A, Eigen::KroneckerProductBase< Derived >::m_B, and row().
cols()
template<typename Derived > Index Eigen::KroneckerProductBase< Derived >::cols () const inline
 { return m_A.cols() * m_B.cols(); }
References Eigen::KroneckerProductBase< Derived >::m_A, and Eigen::KroneckerProductBase< Derived >::m_B.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
rows()
template<typename Derived > Index Eigen::KroneckerProductBase< Derived >::rows () const inline
 { return m_A.rows() * m_B.rows(); }
References Eigen::KroneckerProductBase< Derived >::m_A, and Eigen::KroneckerProductBase< Derived >::m_B.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_A
template<typename Derived > Lhs::Nested Eigen::KroneckerProductBase< Derived >::m_A protected
Referenced by Eigen::KroneckerProductBase< Derived >::coeff(), Eigen::KroneckerProductBase< Derived >::cols(), and Eigen::KroneckerProductBase< Derived >::rows().
m_B
template<typename Derived > Rhs::Nested Eigen::KroneckerProductBase< Derived >::m_B protected
Referenced by Eigen::KroneckerProductBase< Derived >::coeff(), Eigen::KroneckerProductBase< Derived >::cols(), and Eigen::KroneckerProductBase< Derived >::rows().
The documentation for this class was generated from the following file:
KroneckerTensorProduct.h