MercuryDPM: Eigen::internal::pselect_impl< Packet, EnableIf > Struct Template Reference
Eigen::internal::pselect_impl< Packet, EnableIf > Struct Template Reference
#include <GenericPacketMath.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC Packet run (const Packet &mask, const Packet &a, const Packet &b)
Member Function Documentation
run()
template<typename Packet , typename EnableIf = void> static EIGEN_DEVICE_FUNC Packet Eigen::internal::pselect_impl< Packet, EnableIf >::run (const Packet & mask, const Packet & a, const Packet & b) inline static
{
     return por(pand(a, mask), pandnot(b, mask));
   }
References a, b, Eigen::internal::pand(), Eigen::internal::pandnot(), and Eigen::internal::por().
Referenced by Eigen::internal::pselect().
The documentation for this struct was generated from the following file:
GenericPacketMath.h