MercuryDPM: UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT > Class Template Reference
UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT > Class Template Reference
Unstructured 3D FSI problem.
Public Member Functions
UnstructuredFSIProblem ()
Constructor:
~UnstructuredFSIProblem ()
Destructor (empty)
void doc_solution (DocInfo &doc_info)
Doc the solution.
void create_parallel_flow_lagrange_elements ()
Create Lagrange multiplier elements that impose parallel flow.
void create_fsi_traction_elements ()
Create FSI traction elements.
void create_lagrange_multiplier_elements ()
void actions_before_implicit_timestep ()
Actions before timestep.
void actions_before_newton_convergence_check ()
Update no slip bc after update of unknowns.
void doc_parameters ()
Doc parameters.
UnstructuredFSIProblem ()
Constructor:
~UnstructuredFSIProblem ()
Destructor (empty)
void doc_solution (DocInfo &doc_info)
Doc the solution.
void actions_before_adapt ()
Actions before adapt.
void actions_after_adapt ()
Actions after adapt.
void output_strain_and_dissipation (std::ostream &trace)
UnstructuredFSIProblem ()
Constructor.
~UnstructuredFSIProblem ()
Destructor (empty)
FluidTriangleMesh< FLUID_ELEMENT > *& fluid_mesh_pt ()
Access function for the fluid mesh.
MySolidTriangleMesh< SOLID_ELEMENT > *& solid_mesh_pt ()
Access function for the solid mesh.
void doc_solution (DocInfo &doc_info)
Doc the solution.
UnstructuredFSIProblem ()
Constructor:
~UnstructuredFSIProblem ()
Destructor (empty)
void doc_solution (DocInfo &doc_info)
Doc the solution.
void create_fluid_traction_elements ()
Create fluid traction elements at inflow.
void create_fsi_traction_elements ()
Create FSI traction elements.
void create_lagrange_multiplier_elements ()
UnstructuredFSIProblem ()
Constructor:
~UnstructuredFSIProblem ()
Destructor (empty)
void doc_solution (DocInfo &doc_info)
Doc the solution.
void create_parallel_flow_lagrange_elements ()
Create Lagrange multiplier elements that impose parallel flow.
void create_fsi_traction_elements ()
Create FSI traction elements.
void create_lagrange_multiplier_elements ()
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Public Attributes
RefineableSolidTriangleMesh< FLUID_ELEMENT > * Fluid_mesh_pt
Bulk fluid mesh.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Private Member Functions
void doc_solid_boundary_coordinates (const unsigned &i)
Sanity check: Doc boundary coordinates on i-th solid FSI interface.
unsigned nfluid_inflow_traction_boundary ()
unsigned nfluid_outflow_traction_boundary ()
unsigned nfluid_traction_boundary ()
unsigned nsolid_fsi_boundary ()
unsigned nfluid_fsi_boundary ()
unsigned npinned_solid_boundary ()
void create_fsi_traction_elements ()
Create the traction element.
void delete_fsi_traction_elements ()
Delete the traction elements.
void create_lagrange_multiplier_elements ()
void delete_lagrange_multiplier_elements ()
Delete the traction elements.
double get_solid_strain_energy ()
Calculate the strain energy of the solid.
double get_fluid_dissipation ()
Calculate the fluid dissipation.
void create_fsi_traction_elements ()
Create FSI traction elements.
void create_lagrange_multiplier_elements ()
void doc_solid_boundary_coordinates ()
Sanity check: Doc boundary coordinates from solid side.
void doc_solid_boundary_coordinates (const unsigned &i)
Sanity check: Doc boundary coordinates on i-th solid FSI interface.
unsigned nfluid_inflow_traction_boundary ()
unsigned nfluid_outflow_traction_boundary ()
unsigned nfluid_traction_boundary ()
unsigned nsolid_fsi_boundary ()
unsigned nfluid_fsi_boundary ()
unsigned npinned_solid_boundary ()
void doc_solid_boundary_coordinates (const unsigned &i)
Sanity check: Doc boundary coordinates on i-th solid FSI interface.
unsigned nfluid_inflow_traction_boundary ()
unsigned nfluid_outflow_traction_boundary ()
unsigned nfluid_traction_boundary ()
unsigned nsolid_fsi_boundary ()
unsigned nfluid_fsi_boundary ()
unsigned npinned_solid_boundary ()
Private Attributes
SolidTetgenMesh< SOLID_ELEMENT > * Solid_mesh_pt
Bulk solid mesh.
Vector< SolidMesh * > Solid_fsi_traction_mesh_pt
Meshes of FSI traction elements.
SolidTetgenMesh< FLUID_ELEMENT > * Fluid_mesh_pt
Bulk fluid mesh.
Mesh * Inflow_flux_monitor_mesh_pt
Mesh containing the FaceElements that monitor the inflow.
Mesh * Inflow_flux_control_mesh_pt
Mesh of FaceElements that control the inflow.
Mesh * Inflow_flux_control_master_mesh_pt
Mesh containing the master flux control element.
Vector< Mesh * > Parallel_flow_lagrange_multiplier_mesh_pt
Meshes of Lagrange multiplier elements that impose parallel flow.
Vector< SolidMesh * > Lagrange_multiplier_mesh_pt
Meshes of Lagrange multiplier elements.
Vector< MeshAsGeomObject * > Solid_fsi_boundary_pt
GeomObject incarnations of the FSI boundary in the solid mesh.
Vector< unsigned > Pinned_solid_boundary_id
IDs of solid mesh boundaries where displacements are pinned.
Vector< unsigned > Solid_fsi_boundary_id
IDs of solid mesh boundaries which make up the FSI interface.
Vector< unsigned > Solid_outer_boundary_id
IDs of solid mesh boundaries which make up the outer surface.
Vector< unsigned > Inflow_boundary_id
Vector< unsigned > Outflow_boundary_id
Vector< unsigned > Fluid_fsi_boundary_id
IDs of fluid mesh boundaries which make up the FSI interface.
double Wall_thickness
RefineableSolidTriangleMesh< SOLID_ELEMENT > * Solid_mesh_pt
Bulk solid mesh.
Vector< SolidMesh * > Traction_mesh_pt
Vectors of pointers to mesh of traction elements.
TriangleMeshPolygon * Solid_outer_boundary_polyline_pt
Triangle mesh polygon for outer boundary.
TriangleMeshPolygon * Fluid_outer_boundary_polyline_pt
Triangle mesh polygon for outer boundary.
FluidTriangleMesh< FLUID_ELEMENT > * Fluid_mesh_pt
Fluid mesh.
MySolidTriangleMesh< SOLID_ELEMENT > * Solid_mesh_pt
Solid mesh.
SolidMesh * Lagrange_multiplier_mesh_pt
Pointers to mesh of Lagrange multiplier elements.
SolidMesh * Traction_mesh_pt
Vector of pointers to mesh of FSI traction elements.
MeshAsGeomObject * Solid_fsi_boundary_pt
GeomObject incarnation of fsi boundary in solid mesh.
MySolidTetgenMesh< SOLID_ELEMENT > * Solid_mesh_pt
Bulk solid mesh.
FluidTetMesh< FLUID_ELEMENT > * Fluid_mesh_pt
Bulk fluid mesh.
Vector< Mesh * > Fluid_traction_mesh_pt
Meshes of fluid traction elements that apply pressure at in/outflow.
MyFluidTetMesh< FLUID_ELEMENT > * Fluid_mesh_pt
Bulk fluid mesh.
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_solve ()
virtual void actions_after_newton_solve ()
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual void set_initial_condition ()
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class FLUID_ELEMENT, class SOLID_ELEMENT>
class UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >
Unstructured 3D FSI problem.
Unstructured FSI Problem.
Unstructured FSI problem.
//////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
UnstructuredFSIProblem() [1/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::UnstructuredFSIProblem
Constructor:
Constructor for unstructured FSI problem.
Constructor for unstructured solid problem.
Constructor for unstructured 3D FSI problem.
IDs of solid mesh boundaries where displacements are pinned
 {
  // We have a large number of sub-meshes with very few elements
  // in this problem: Reduce the number of bins in the MeshAsGeomObject
  // representations of these meshes to avoid memory problems
  NonRefineableBinArray::Default_n_bin_1d=1;
  // Allocate the timestepper for the Navier-Stokes equations
  BDF<2>* fluid_time_stepper_pt=new BDF<2>;
  // Add the fluid timestepper to the Problem's collection of timesteppers.
  add_time_stepper_pt(fluid_time_stepper_pt);
  // Create a Steady timestepper that stores two history values
  Steady<2>* wall_time_stepper_pt = new Steady<2>;
  // Add the wall timestepper to the Problem's collection of timesteppers.
  add_time_stepper_pt(wall_time_stepper_pt);
  // Read boundary enumeration
  string input_string;
  // Open input file
  ifstream* input_file_pt=new ifstream("boundary_enumeration.dat");
  // Check if it's been opened succesfully
  if (input_file_pt==0)
   {
    oomph_info << "ERROR while trying to open boundary enumeration file "
               << std::endl;
    exit(1);
   }
  getline(*input_file_pt,input_string,' ');
  unsigned fluid_fsi_lo=atoi(input_string.c_str());
  getline(*input_file_pt,input_string,'#');
  unsigned fluid_fsi_hi=atoi(input_string.c_str());
  input_file_pt->ignore(80,'\n');
  getline(*input_file_pt,input_string,' ');
  unsigned fluid_in_lo=atoi(input_string.c_str());
  getline(*input_file_pt,input_string,'#');
  unsigned fluid_in_hi=atoi(input_string.c_str());
  input_file_pt->ignore(80,'\n');
  getline(*input_file_pt,input_string,' ');
  unsigned fluid_out_lo=atoi(input_string.c_str());
  input_file_pt->ignore(80,'\n');
  getline(*input_file_pt,input_string,' ');
  getline(*input_file_pt,input_string,'#');
  unsigned fluid_out_hi=atoi(input_string.c_str());
  input_file_pt->ignore(80,'\n');
  getline(*input_file_pt,input_string,' ');
  unsigned solid_fsi_lo=atoi(input_string.c_str());
  getline(*input_file_pt,input_string,'#');
  unsigned solid_fsi_hi=atoi(input_string.c_str());
  input_file_pt->ignore(80,'\n');
  getline(*input_file_pt,input_string,' ');
  unsigned solid_pin_lo=atoi(input_string.c_str());
  input_file_pt->ignore(80,'\n');
  input_file_pt->ignore(80,'\n');
  getline(*input_file_pt,input_string,' ');
  getline(*input_file_pt,input_string,'#');
  unsigned solid_pin_hi=atoi(input_string.c_str());
  input_file_pt->ignore(80,'\n');
  getline(*input_file_pt,input_string,' ');
  unsigned solid_outer_lo=atoi(input_string.c_str());
  getline(*input_file_pt,input_string,'#');
  unsigned solid_outer_hi=atoi(input_string.c_str());
  input_file_pt->ignore(80,'\n');
   // Define fluid mesh and its distinguished boundaries
  //---------------------------------------------------
  //Create fluid bulk mesh, sub-dividing "corner" elements
  string node_file_name="fluid.1.node";
  string element_file_name="fluid.1.ele";
  string face_file_name="fluid.1.face";
  bool split_corner_elements=true;
  bool switch_normal=true;
  Fluid_mesh_pt =  new SolidTetgenMesh<FLUID_ELEMENT>(node_file_name,
                                                   element_file_name,
                                                   face_file_name,
                                                   split_corner_elements,
                                                   switch_normal,
                                                   fluid_time_stepper_pt);
  // Now update the nodal positions
  ifstream node_file;
  node_file.open("fluid_quadratic_nodes.dat");
  unsigned nnod=Fluid_mesh_pt->nnode();
  for (unsigned j=0;j<nnod;j++)
   {
    Node* nod_pt=Fluid_mesh_pt->node_pt(j);
    node_file >> nod_pt->x(0);
    node_file >> nod_pt->x(1);
    node_file >> nod_pt->x(2);
   }
  node_file.close();
  Fluid_mesh_pt->set_lagrangian_nodal_coordinates();
  // The following corresponds to the boundaries as specified by
  // facets in the xda input:
  // Fluid mesh inflow boundaries
  unsigned nfluid_in=fluid_in_hi-fluid_in_lo+1;
  Inflow_boundary_id.resize(nfluid_in);
  for(unsigned i=0; i<nfluid_in; i++)
   {
    Inflow_boundary_id[i]=fluid_fsi_hi+1+i;
   }
  // Fluid mesh outflow boundaries
  unsigned nfluid_out=fluid_out_hi-fluid_out_lo+1;
  Outflow_boundary_id.resize(nfluid_out);
  for(unsigned i=0; i<nfluid_out; i++)
   {
    Outflow_boundary_id[i]=fluid_out_lo+i;
   }
  // The FSI boundaries :
  unsigned nfluid_fsi=fluid_fsi_hi-fluid_fsi_lo+1;
  Fluid_fsi_boundary_id.resize(nfluid_fsi);
  for(unsigned i=0; i<nfluid_fsi; i++)
   {
    Fluid_fsi_boundary_id[i]=fluid_fsi_lo+i;
   }
  // Define solid mesh and its distinguished boundaries
  //---------------------------------------------------
    //Create solid bulk mesh
  node_file_name="solid.1.node";
  element_file_name="solid.1.ele";
  face_file_name="solid.1.face";
  Solid_mesh_pt =  new SolidTetgenMesh<SOLID_ELEMENT>(node_file_name,
                                                   element_file_name,
                                                   face_file_name,
                                                   wall_time_stepper_pt);
  // Now update the nodal positions
  node_file.open("solid_quadratic_nodes.dat");
  nnod=Solid_mesh_pt->nnode();
  for (unsigned j=0;j<nnod;j++)
   {
    Node* nod_pt=Solid_mesh_pt->node_pt(j);
    node_file >> nod_pt->x(0);
    node_file >> nod_pt->x(1);
    node_file >> nod_pt->x(2);
   }
  node_file.close();
  Solid_mesh_pt->set_lagrangian_nodal_coordinates();
  // The following corresponds to the boundaries as specified by
  // facets in the Tetgen input:
  unsigned nsolid_pin=solid_pin_hi-solid_pin_lo+1;
  Pinned_solid_boundary_id.resize(nsolid_pin);
  for(unsigned i=0; i<nsolid_pin; i++)
   {
    Pinned_solid_boundary_id[i]=solid_pin_lo+i;
   }
   // The solid and fluid fsi boundaries are numbered in the same way.
  unsigned nsolid_fsi=solid_fsi_hi-solid_fsi_lo+1;
  Solid_fsi_boundary_id.resize(nsolid_fsi);
  for(unsigned i=0; i<nsolid_fsi; i++)
   {
    Solid_fsi_boundary_id[i]=solid_fsi_lo+i;
   }
   // Outer solid boundary
  unsigned nsolid_outer=solid_outer_hi-solid_outer_lo+1;
  Solid_outer_boundary_id.resize(nsolid_outer);
  for(unsigned i=0; i<nsolid_outer; i++)
   {
    Solid_outer_boundary_id[i]=solid_outer_lo+i;
   }
  // Scale
  double factor=0.0666;
  Fluid_mesh_pt->scale_mesh(factor);
  Solid_mesh_pt->scale_mesh(factor);
  // Create (empty) meshes of lagrange multiplier elements at inflow/outflow
  //------------------------------------------------------------------------
  // Create the meshes
  unsigned n=nfluid_traction_boundary();
  Parallel_flow_lagrange_multiplier_mesh_pt.resize(n);
  for (unsigned i=0;i<n;i++)
   {
    Parallel_flow_lagrange_multiplier_mesh_pt[i]=new Mesh;
   }
  // Meshes of inflow elements
  Inflow_flux_monitor_mesh_pt=new Mesh;
  Inflow_flux_control_mesh_pt=new Mesh;
  Inflow_flux_control_master_mesh_pt=new Mesh;
  // Populate them with elements
  create_parallel_flow_lagrange_elements();
  cout << "Number of inflow flux monitor elements: "
       << Inflow_flux_monitor_mesh_pt->nelement() << std::endl;
 // Create FSI Traction elements
 //-----------------------------
 // Create (empty) meshes of FSI traction elements
  n=nsolid_fsi_boundary();
  Solid_fsi_traction_mesh_pt.resize(n);
  for (unsigned i=0;i<n;i++)
   {
    Solid_fsi_traction_mesh_pt[i]=new SolidMesh;
   }
  // Build the FSI traction elements
  create_fsi_traction_elements();
  // Compute average wall thickness
  //-------------------------------
  // Surface area of fsi interface
  double fsi_area=0.0;
  n=nsolid_fsi_boundary();
  for (unsigned i=0;i<n;i++)
   {
    unsigned nel=Solid_fsi_traction_mesh_pt[i]->nelement();
    for (unsigned e=0;e<nel;e++)
     {
      fsi_area+=Solid_fsi_traction_mesh_pt[i]->finite_element_pt(e)->size();
     }
   }
  // Volume of solid mesh
  double solid_vol=0.0;
  unsigned nel=Solid_mesh_pt->nelement();
  for (unsigned e=0;e<nel;e++)
   {
    solid_vol+=Solid_mesh_pt->finite_element_pt(e)->size();
   }
  Wall_thickness=solid_vol/fsi_area;
  std::cout << "Surface area          : " << fsi_area << std::endl;
  std::cout << "Solid volume          : " << solid_vol << std::endl;
  // Create Lagrange multiplier mesh for boundary motion of fluid mesh
  //------------------------------------------------------------------
  // Construct the mesh of elements that enforce prescribed boundary motion
  // of pseudo-solid fluid mesh by Lagrange multipliers
  n=nfluid_fsi_boundary();
  Lagrange_multiplier_mesh_pt.resize(n);
  for (unsigned i=0;i<n;i++)
   {
    Lagrange_multiplier_mesh_pt[i]=new SolidMesh;
   }
  // Create elements
  create_lagrange_multiplier_elements();
  // Combine the lot
  //----------------
  // Add sub meshes:
  // The solid bulk mesh
  add_sub_mesh(Solid_mesh_pt);
  // Fluid bulk mesh
  add_sub_mesh(Fluid_mesh_pt);
  // The fluid traction meshes
  n=nfluid_traction_boundary();
  for (unsigned i=0;i<n;i++)
   {
    add_sub_mesh(Parallel_flow_lagrange_multiplier_mesh_pt[i]);
   }
  // The solid fsi traction meshes
  n=nsolid_fsi_boundary();
  for (unsigned i=0;i<n;i++)
   {
    add_sub_mesh(Solid_fsi_traction_mesh_pt[i]);
   }
  // The Lagrange multiplier meshes for the fluid
  n=nfluid_fsi_boundary();
  for (unsigned i=0;i<n;i++)
   {
    add_sub_mesh(Lagrange_multiplier_mesh_pt[i]);
   }
  // Add flux control meshes if required
  if (!Global_Parameters::Prescribe_pressure)
   {
    add_sub_mesh(Inflow_flux_control_mesh_pt);
    add_sub_mesh(Inflow_flux_control_master_mesh_pt);
   }
  // Build global mesh
  build_global_mesh();
  // Apply BCs for fluid and Lagrange multiplier elements
  //-----------------------------------------------------
  // Doc position of pinned pseudo solid nodes
  std::ofstream pseudo_solid_bc_file("RESLT/pinned_pseudo_solid_nodes.dat");
  // Loop over inflow/outflow boundaries to pin pseudo-solid displacements
  for (unsigned in_out=0;in_out<2;in_out++)
   {
    // Loop over in/outflow boundaries
    unsigned n=nfluid_inflow_traction_boundary();
    if (in_out==1) n=nfluid_outflow_traction_boundary();
    for (unsigned i=0;i<n;i++)
     {
      // Get boundary ID
      unsigned b=0;
      if (in_out==0)
       {
        b=Inflow_boundary_id[i];
       }
      else
       {
        b=Outflow_boundary_id[i];
       }
      // Number of nodes on that boundary
      unsigned num_nod=Fluid_mesh_pt->nboundary_node(b);
      for (unsigned inod=0;inod<num_nod;inod++)
       {
        // Get the node
        SolidNode* nod_pt=Fluid_mesh_pt->boundary_node_pt(b,inod);
        // Pin the nodal (pseudo-solid) displacements
        for(unsigned i=0;i<3;i++)
         {
          nod_pt->pin_position(i);
          // Doc it as pinned
          pseudo_solid_bc_file << nod_pt->x(i) << " ";
         }
       }
     }
   }
  // Close
  pseudo_solid_bc_file.close();
 // Doc bcs for Lagrange multipliers
  ofstream pinned_file("RESLT/pinned_lagrange_multiplier_nodes.dat");
  // Loop over nodes on the FSI boundary in the fluid mesh
  unsigned nbound=nfluid_fsi_boundary();
  for(unsigned i=0;i<nbound;i++)
   {
    //Get the mesh boundary
    unsigned b = Fluid_fsi_boundary_id[i];
    unsigned num_nod=Fluid_mesh_pt->nboundary_node(b);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      // Get node
      Node* nod_pt= Fluid_mesh_pt->boundary_node_pt(b,inod);
      // Pin all velocities
      nod_pt->pin(0);
      nod_pt->pin(1);
      nod_pt->pin(2);
      // Find out whether node is also on in/outflow
      bool is_in_or_outflow_node=false;
      unsigned n=nfluid_inflow_traction_boundary();
      for (unsigned k=0;k<n;k++)
       {
        if (nod_pt->is_on_boundary(Inflow_boundary_id[k]))
         {
          is_in_or_outflow_node=true;
          break;
         }
       }
      if (!is_in_or_outflow_node)
       {
        unsigned n=nfluid_outflow_traction_boundary();
        for (unsigned k=0;k<n;k++)
         {
          if (nod_pt->is_on_boundary(Outflow_boundary_id[k]))
           {
            is_in_or_outflow_node=true;
            break;
           }
         }
       } // ...now we know if the node is on an in- or outflow boundary
      // Pin the Lagrange multipliers for the imposition of
      // parallel flow if the nodes is also on the in/outflow boundaries
      if(is_in_or_outflow_node)
       {
        //Cast to a boundary node
        BoundaryNode<SolidNode> *bnod_pt =
         dynamic_cast<BoundaryNode<SolidNode>*>
         ( Fluid_mesh_pt->boundary_node_pt(b,inod) );
        // Get the index of the first Lagrange multiplier
        unsigned first_index=bnod_pt->
         index_of_first_value_assigned_by_face_element(
          Global_Parameters::Parallel_flow_lagrange_multiplier_id);
        //Pin the Lagrange multipliers (as the velocity is already
        //determined via the no slip condition on the fsi boundary
        for (unsigned l=0;l<2;l++)
         {
          nod_pt->pin(first_index+l);
         }
        // Get the first index of the second Lagrange multiplier
        first_index=bnod_pt->index_of_first_value_assigned_by_face_element(
         Global_Parameters::FSI_interface_displacement_lagrange_multiplier_id);
        // Loop over the Lagrange multipliers that deform the FSI boundary
        // of the pseudo-solid fluid mesh.
        for (unsigned l=0;l<3;l++)
         {
          // Pin the Lagrange multipliers that impose the displacement
          // because the positon of the fluid nodes at the in/outflow
          // is already determined.
          nod_pt->pin(first_index+l);
         }
        // Doc that we've pinned the Lagrange multipliers at this node
        pinned_file << nod_pt->x(0) << " "
                    << nod_pt->x(1) << " "
                    << nod_pt->x(2) << endl;
       }
     }
   } // end of BC for fluid mesh
  // Done pinning Lagrange nultipliers
  pinned_file.close();
  // Complete the build of the fluid elements so they are fully functional
  //----------------------------------------------------------------------
  unsigned n_element = Fluid_mesh_pt->nelement();
  for(unsigned e=0;e<n_element;e++)
   {
    // Upcast from GeneralisedElement to the present element
    FLUID_ELEMENT* el_pt =
     dynamic_cast<FLUID_ELEMENT*>(Fluid_mesh_pt->element_pt(e));
    //Set the Reynolds number
    el_pt->re_pt() = &Global_Parameters::Re;
    el_pt->re_st_pt() = &Global_Parameters::Re;
    // Set the constitutive law for pseudo-elastic mesh deformation
    el_pt->constitutive_law_pt() =
     Global_Parameters::Constitutive_law_pt;
   } // end loop over elements
  // Apply BCs for solid
  //--------------------
  // Doc pinned solid nodes
  std::ofstream bc_file("RESLT/pinned_solid_nodes.dat");
  // Pin positions at inflow boundary (boundaries 0 and 1)
  n=npinned_solid_boundary();
  for (unsigned i=0;i<n;i++)
   {
    // Get boundary ID
    unsigned b=Pinned_solid_boundary_id[i];
    unsigned num_nod= Solid_mesh_pt->nboundary_node(b);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      // Get node
      SolidNode* nod_pt=Solid_mesh_pt->boundary_node_pt(b,inod);
      // Pin all directions
      for (unsigned i=0;i<3;i++)
       {
        nod_pt->pin_position(i);
        // ...and doc it as pinned
        bc_file << nod_pt->x(i) << " ";
       }
      bc_file << std::endl;
     }
   }
  bc_file.close();
  // Complete the build of Solid elements so they are fully functional
  //----------------------------------------------------------------
  n_element = Solid_mesh_pt->nelement();
  for(unsigned i=0;i<n_element;i++)
   {
    //Cast to a solid element
    SOLID_ELEMENT *el_pt = dynamic_cast<SOLID_ELEMENT*>(
     Solid_mesh_pt->element_pt(i));
    // Set the constitutive law
    el_pt->constitutive_law_pt() =
     Global_Parameters::Constitutive_law_pt;
    // Set the timescale ratio
    el_pt->lambda_sq_pt() =
     &Global_Parameters::Lambda_sq;
   }
  // Setup FSI
  //----------
  // The velocity of the fluid nodes on the fsi boundary
  // is set by the wall motion -- hence the no-slip condition must be
  // re-applied whenever a node update is performed for these nodes.
  // Such tasks may be performed automatically by the auxiliary node update
  // function specified by a function pointer:
  n=nfluid_fsi_boundary();
  for (unsigned i=0;i<n;i++)
   {
    // Get boundary ID
    unsigned b=Fluid_fsi_boundary_id[i];
    // How many nodes on boundary b?
    unsigned num_nod =  Fluid_mesh_pt->nboundary_node(b);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      Fluid_mesh_pt->boundary_node_pt(b,inod)->
       set_auxiliary_node_update_fct_pt(
        FSI_functions::apply_no_slip_on_moving_wall);
     }
   }
  // Work out which fluid dofs affect the residuals of the wall elements:
  // We pass the boundary between the fluid and solid meshes and
  // pointers to the meshes.
  n=nsolid_fsi_boundary();
  for (unsigned i=0;i<n;i++)
   {
    // Sanity check: Doc boundary coordinates from solid side
    doc_solid_boundary_coordinates(i);
    //Doc boundary coordinates in fluid
    char filename[100];
    sprintf(filename,"RESLT/fluid_boundary_coordinates%i.dat",i);
    Multi_domain_functions::Doc_boundary_coordinate_file.open(filename);
    // Setup FSI: Pass ID of fluid FSI boundary and associated
    // mesh of solid fsi traction elements.
    FSI_functions::setup_fluid_load_info_for_solid_elements<FLUID_ELEMENT,3>
     (this,Fluid_fsi_boundary_id[i],Fluid_mesh_pt,Solid_fsi_traction_mesh_pt[i]);
    // Close the doc file
    Multi_domain_functions::Doc_boundary_coordinate_file.close();
   }
  // Setup equation numbering scheme
  std::cout <<"Number of equations: " << assign_eqn_numbers() << std::endl;
 }
References oomph::FSI_functions::apply_no_slip_on_moving_wall(), b, Global_Parameters::Constitutive_law_pt, NonRefineableBinArray::Default_n_bin_1d, oomph::Multi_domain_functions::Doc_boundary_coordinate_file, e(), MergeRestartFiles::filename, FLUID_ELEMENT, Global_Parameters::FSI_interface_displacement_lagrange_multiplier_id, i, oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), oomph::Node::is_on_boundary(), j, k, Global_Parameters::Lambda_sq, n, oomph::oomph_info, Global_Parameters::Parallel_flow_lagrange_multiplier_id, oomph::Data::pin(), oomph::SolidNode::pin_position(), Global_Parameters::Prescribe_pressure, Global_Parameters::Re, and oomph::Node::x().
~UnstructuredFSIProblem() [1/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::~UnstructuredFSIProblem () inline
Destructor (empty)
 {}
UnstructuredFSIProblem() [2/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::UnstructuredFSIProblem ()
Constructor:
~UnstructuredFSIProblem() [2/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::~UnstructuredFSIProblem () inline
Destructor (empty)
 {}
UnstructuredFSIProblem() [3/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::UnstructuredFSIProblem ()
Constructor.
~UnstructuredFSIProblem() [3/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::~UnstructuredFSIProblem () inline
Destructor (empty)
 {}
UnstructuredFSIProblem() [4/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::UnstructuredFSIProblem ()
Constructor:
~UnstructuredFSIProblem() [4/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::~UnstructuredFSIProblem () inline
Destructor (empty)
 {}
UnstructuredFSIProblem() [5/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::UnstructuredFSIProblem ()
Constructor:
~UnstructuredFSIProblem() [5/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::~UnstructuredFSIProblem () inline
Destructor (empty)
 {}
Member Function Documentation
actions_after_adapt()
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_after_adapt () inline virtual
Actions after adapt.
Reimplemented from oomph::Problem.
   {
    //Ensure that the lagrangian coordinates of the mesh are set to be
    //the same as the eulerian
    Fluid_mesh_pt->set_lagrangian_nodal_coordinates();
    //Apply boundary conditions again
    // Pin both positions at lower boundary (boundary 3)
    unsigned ibound=3;
    unsigned num_nod= Solid_mesh_pt->nboundary_node(ibound);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      // Get node
      SolidNode* nod_pt=Solid_mesh_pt->boundary_node_pt(ibound,inod);
      // Pin both directions
      for (unsigned i=0;i<2;i++)
       {
        nod_pt->pin_position(i);
       }
     }
    // Complete the build of all elements so they are fully functional
    unsigned n_element = Solid_mesh_pt->nelement();
    for(unsigned i=0;i<n_element;i++)
     {
      //Cast to a solid element
      SOLID_ELEMENT *el_pt =
       dynamic_cast<SOLID_ELEMENT*>(Solid_mesh_pt->element_pt(i));
      // Set the constitutive law
      el_pt->constitutive_law_pt() =
       Global_Physical_Variables::Constitutive_law_pt;
     } // end complete solid build
    // Set the boundary conditions for fluid problem: All nodes are
    // free by default
    // --- just pin the ones that have Dirichlet conditions here.
    //Pin velocity everywhere apart from parallel outflow (boundary 4)
    unsigned nbound=Fluid_mesh_pt->nboundary();
    for(unsigned ibound=0;ibound<nbound;ibound++)
     {
      unsigned num_nod=Fluid_mesh_pt->nboundary_node(ibound);
      for (unsigned inod=0;inod<num_nod;inod++)
       {
        // Pin velocity everywhere apart from outlet where we
        // have parallel outflow
        if (ibound!=4)
         {
          Fluid_mesh_pt->boundary_node_pt(ibound,inod)->pin(0);
         }
        Fluid_mesh_pt->boundary_node_pt(ibound,inod)->pin(1);
        // Pin pseudo-solid positions everywhere apart from boundaries 0, 1, 2
        // the fsi boundaries
        if(ibound > 2)
         {
          for(unsigned i=0;i<2;i++)
           {
            // Pin the node
            SolidNode* nod_pt=Fluid_mesh_pt->boundary_node_pt(ibound,inod);
            nod_pt->pin_position(i);
           }
         }
       }
     } // end loop over boundaries
    // Complete the build of the fluid elements so they are fully functional
    n_element = Fluid_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement to the present element
      FLUID_ELEMENT* el_pt =
       dynamic_cast<FLUID_ELEMENT*>(Fluid_mesh_pt->element_pt(e));
      //Set the Reynolds number
      el_pt->re_pt() = &Global_Physical_Variables::Re;
      // Set the constitutive law for pseudo-elastic mesh deformation
      el_pt->constitutive_law_pt() =
       Global_Physical_Variables::Mesh_constitutive_law_pt;
     } // end loop over elements
    // Apply fluid boundary conditions: Poiseuille at inflow
    const unsigned n_boundary = Fluid_mesh_pt->nboundary();
    for (unsigned ibound=0;ibound<n_boundary;ibound++)
     {
      const unsigned num_nod= Fluid_mesh_pt->nboundary_node(ibound);
      for (unsigned inod=0;inod<num_nod;inod++)
       {
        // Parabolic inflow at the left boundary (boundary 6)
        if(ibound==6)
         {
          double y=Fluid_mesh_pt->boundary_node_pt(ibound,inod)->x(1);
          double veloc = y*(1.0-y);
          Fluid_mesh_pt->boundary_node_pt(ibound,inod)->set_value(0,veloc);
          Fluid_mesh_pt->boundary_node_pt(ibound,inod)->set_value(1,0.0);
         }
        // Zero flow elsewhere
        else
         {
          Fluid_mesh_pt->boundary_node_pt(ibound,inod)->set_value(0,0.0);
          Fluid_mesh_pt->boundary_node_pt(ibound,inod)->set_value(1,0.0);
         }
       }
     } // end Poiseuille
    //Recreate the boundary elements
    this->create_fsi_traction_elements();
    this->create_lagrange_multiplier_elements();
    //Rebuild the global mesh
    this->rebuild_global_mesh();
  // Setup FSI (again)
  //------------------
  // Work out which fluid dofs affect the residuals of the wall elements:
  // We pass the boundary between the fluid and solid meshes and
  // pointers to the meshes. The interaction boundary are boundaries 0, 1 and 2
  // of the 2D fluid mesh.
  for(unsigned b=0;b<3;b++)
   {
    FSI_functions::setup_fluid_load_info_for_solid_elements<FLUID_ELEMENT,2>
     (this,b,Fluid_mesh_pt,Traction_mesh_pt[b]);
   }
   }
References b, Global_Physical_Variables::Constitutive_law_pt, e(), FLUID_ELEMENT, i, Global_Physical_Variables::Mesh_constitutive_law_pt, oomph::SolidNode::pin_position(), Global_Physical_Variables::Re, and y.
actions_before_adapt()
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_before_adapt () inline virtual
Actions before adapt.
Reimplemented from oomph::Problem.
   {
    //Delete the boundary meshes
    this->delete_lagrange_multiplier_elements();
    this->delete_fsi_traction_elements();
    //Rebuild the global mesh
    this->rebuild_global_mesh();
   }
actions_before_implicit_timestep()
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_before_implicit_timestep () inline virtual
Actions before timestep.
Reimplemented from oomph::Problem.
   {
    // Get the current time
    double time=time_pt()->time();
    // Change inflow conditions
    if (Global_Parameters::Prescribe_pressure)
     {
      Global_Parameters::P_in=Global_Parameters::P_in_max*
       cos(2.0*MathematicalConstants::Pi/Global_Parameters::Period*time);
     }
    else
     {
      Global_Parameters::Prescribed_flow_rate=
       Global_Parameters::Peak_prescribed_flow_rate*
       cos(2.0*MathematicalConstants::Pi/Global_Parameters::Period*time);
      cout << "New imposed prescribed flow rate: "
           << Global_Parameters::Prescribed_flow_rate << std::endl;
     }
   }
References cos(), Global_Parameters::P_in, Global_Parameters::P_in_max, Global_Parameters::Peak_prescribed_flow_rate, Global_Parameters::Period, BiharmonicTestFunctions2::Pi, Global_Parameters::Prescribe_pressure, and Global_Parameters::Prescribed_flow_rate.
actions_before_newton_convergence_check()
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_before_newton_convergence_check () inline virtual
Update no slip bc after update of unknowns.
Reimplemented from oomph::Problem.
   {
    // The velocity of the fluid nodes on the fsi boundary
    // is set by the wall motion -- hence the no-slip condition must be
    // re-applied whenever a node update is performed for these nodes.
    // Such tasks may be performed automatically by the auxiliary node update
    // function specified by a function pointer:
    unsigned n=nfluid_fsi_boundary();
    for (unsigned i=0;i<n;i++)
     {
      // Get boundary ID
      unsigned b=Fluid_fsi_boundary_id[i];
      // How many nodes on boundary b?
      unsigned num_nod =  Fluid_mesh_pt->nboundary_node(b);
      for (unsigned inod=0;inod<num_nod;inod++)
       {
        FSI_functions::apply_no_slip_on_moving_wall(
         Fluid_mesh_pt->boundary_node_pt(b,inod));
       }
     }
   }
References oomph::FSI_functions::apply_no_slip_on_moving_wall(), b, i, and n.
create_fluid_traction_elements()
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fluid_traction_elements
Create fluid traction elements at inflow.
Create fluid traction elements.
 {
  // Counter for number of fluid traction meshes
  unsigned count=0;
  // Loop over inflow/outflow boundaries
  for (unsigned in_out=0;in_out<2;in_out++)
   {
    // Loop over boundaries with fluid traction elements
    unsigned n=nfluid_inflow_traction_boundary();
    if (in_out==1) n=nfluid_outflow_traction_boundary();
    for (unsigned i=0;i<n;i++)
     {
      // Get boundary ID
      unsigned b=0;
      if (in_out==0)
       {
        b=Inflow_boundary_id[i];
       }
      else
       {
        b=Outflow_boundary_id[i];
       }
      // How many bulk elements are adjacent to boundary b?
      unsigned n_element = Fluid_mesh_pt->nboundary_element(b);
      // Loop over the bulk elements adjacent to boundary b
      for(unsigned e=0;e<n_element;e++)
       {
        // Get pointer to the bulk element that is adjacent to boundary b
        FLUID_ELEMENT* bulk_elem_pt = dynamic_cast<FLUID_ELEMENT*>(
         Fluid_mesh_pt->boundary_element_pt(b,e));
        //What is the index of the face of the element e along boundary b
        int face_index = Fluid_mesh_pt->face_index_at_boundary(b,e);
        // Create new element
        NavierStokesTractionElement<FLUID_ELEMENT>* el_pt=
         new NavierStokesTractionElement<FLUID_ELEMENT>(bulk_elem_pt,
                                                        face_index);
        // Add it to the mesh
        Fluid_traction_mesh_pt[count]->add_element_pt(el_pt);
        // Set the pointer to the prescribed traction function
        if (in_out==0)
         {
          el_pt->traction_fct_pt() =
           &Global_Parameters::prescribed_inflow_traction;
         }
        else
         {
          el_pt->traction_fct_pt() =
           &Global_Parameters::prescribed_outflow_traction;
         }
       }
      // Bump up counter
      count++;
     }
   }
  } // end of create_traction_elements
References b, e(), FLUID_ELEMENT, i, n, Global_Parameters::prescribed_inflow_traction(), Global_Parameters::prescribed_outflow_traction(), and oomph::NavierStokesTractionElement< ELEMENT >::traction_fct_pt.
create_fsi_traction_elements() [1/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fsi_traction_elements
Create FSI traction elements.
 {
  // Loop over FSI boundaries in solid
  unsigned n=nsolid_fsi_boundary();
  for (unsigned i=0;i<n;i++)
   {
    // Get boundary ID
    unsigned b=Solid_fsi_boundary_id[i];
    // How many bulk elements are adjacent to boundary b?
    unsigned n_element = Solid_mesh_pt->nboundary_element(b);
    // Loop over the bulk elements adjacent to boundary b
    for(unsigned e=0;e<n_element;e++)
     {
      // Get pointer to the bulk element that is adjacent to boundary b
      SOLID_ELEMENT* bulk_elem_pt = dynamic_cast<SOLID_ELEMENT*>(
       Solid_mesh_pt->boundary_element_pt(b,e));
      //What is the index of the face of the element e along boundary b
      int face_index = Solid_mesh_pt->face_index_at_boundary(b,e);
      // Create new element
      FSISolidTractionElement<SOLID_ELEMENT,3>* el_pt=
       new FSISolidTractionElement<SOLID_ELEMENT,3>(bulk_elem_pt,face_index);
      // Add it to the mesh
      Solid_fsi_traction_mesh_pt[i]->add_element_pt(el_pt);
      // Specify boundary number
      el_pt->set_boundary_number_in_bulk_mesh(b);
      // Function that specifies the load ratios
      el_pt->q_pt() = &Global_Parameters::Q;
     }
   }
 } // end of create_fsi_traction_elements
References b, e(), i, n, Global_Parameters::Q, oomph::FSIWallElement::q_pt(), and oomph::FaceElement::set_boundary_number_in_bulk_mesh().
create_fsi_traction_elements() [2/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fsi_traction_elements () inline private
Create the traction element.
   {
    // Traction elements are located on boundaries 0 1 and 2 of solid bulk mesh
    for(unsigned b=0;b<3;++b)
     {
      // How many bulk elements are adjacent to boundary b?
      const unsigned n_element = Solid_mesh_pt->nboundary_element(b);
      // Loop over the bulk elements adjacent to boundary b
      for(unsigned e=0;e<n_element;e++)
       {
        // Get pointer to the bulk element that is adjacent to boundary b
        SOLID_ELEMENT* bulk_elem_pt = dynamic_cast<SOLID_ELEMENT*>(
         Solid_mesh_pt->boundary_element_pt(b,e));
        //What is the index of the face of the element e along boundary b
        int face_index = Solid_mesh_pt->face_index_at_boundary(b,e);
        // Create new element
        FSISolidTractionElement<SOLID_ELEMENT,2>* el_pt=
         new FSISolidTractionElement<SOLID_ELEMENT,2>(bulk_elem_pt,face_index);
        // Add it to the mesh
        Traction_mesh_pt[b]->add_element_pt(el_pt);
        // Specify boundary number
        el_pt->set_boundary_number_in_bulk_mesh(b);
        // Function that specifies the load ratios
        el_pt->q_pt() = &Global_Physical_Variables::Q;
       }
     }
   }
References b, e(), Global_Physical_Variables::Q, oomph::FSIWallElement::q_pt(), and oomph::FaceElement::set_boundary_number_in_bulk_mesh().
create_fsi_traction_elements() [3/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fsi_traction_elements () private
Create FSI traction elements.
create_fsi_traction_elements() [4/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fsi_traction_elements ()
Create FSI traction elements.
create_fsi_traction_elements() [5/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fsi_traction_elements ()
Create FSI traction elements.
create_lagrange_multiplier_elements() [1/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_lagrange_multiplier_elements
Create elements that enforce prescribed boundary motion for the pseudo-solid fluid mesh by Lagrange multipliers
Create elements that impose the prescribed boundary displacement for the pseudo-solid fluid mesh
 {
  // Make space
  unsigned n=nfluid_fsi_boundary();
  Solid_fsi_boundary_pt.resize(n);
  // Loop over FSI interfaces in fluid
  for (unsigned i=0;i<n;i++)
   {
    // Get boundary ID
    unsigned b=Fluid_fsi_boundary_id[i];
    // Create  GeomObject incarnation of fsi boundary in solid mesh
    Solid_fsi_boundary_pt[i]=
     new MeshAsGeomObject(Solid_fsi_traction_mesh_pt[i]);
    // How many bulk fluid elements are adjacent to boundary b?
    unsigned n_element = Fluid_mesh_pt->nboundary_element(b);
    // Loop over the bulk fluid elements adjacent to boundary b?
    for(unsigned e=0;e<n_element;e++)
     {
      // Get pointer to the bulk fluid element that is adjacent to boundary b
      FLUID_ELEMENT* bulk_elem_pt = dynamic_cast<FLUID_ELEMENT*>(
       Fluid_mesh_pt->boundary_element_pt(b,e));
      //Find the index of the face of element e along boundary b
      int face_index = Fluid_mesh_pt->face_index_at_boundary(b,e);
      // Create new element
      ImposeDisplacementByLagrangeMultiplierElement<FLUID_ELEMENT>* el_pt =
       new  ImposeDisplacementByLagrangeMultiplierElement<FLUID_ELEMENT>(
        bulk_elem_pt,face_index,
        Global_Parameters::FSI_interface_displacement_lagrange_multiplier_id);
      // Add it to the mesh
      Lagrange_multiplier_mesh_pt[i]->add_element_pt(el_pt);
      // Set the GeomObject that defines the boundary shape and set
      // which bulk boundary we are attached to (needed to extract
      // the boundary coordinate from the bulk nodes)
      el_pt->set_boundary_shape_geom_object_pt(Solid_fsi_boundary_pt[i],b);
     }
   }
 } // end of create_lagrange_multiplier_elements
References b, e(), FLUID_ELEMENT, Global_Parameters::FSI_interface_displacement_lagrange_multiplier_id, i, n, and oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt().
create_lagrange_multiplier_elements() [2/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_lagrange_multiplier_elements () inline private
Create the multipliers that add lagrange multipliers to the fluid elements that apply the solid displacement conditions
   {
    //Loop over the FSI boundaries
    for(unsigned b=0;b<3;b++)
     {
      // Create GeomObject incarnation of fsi boundary in solid mesh
      Solid_fsi_boundary_pt[b] = new MeshAsGeomObject(Traction_mesh_pt[b]);
      // How many bulk fluid elements are adjacent to boundary b?
      unsigned n_element = Fluid_mesh_pt->nboundary_element(b);
      // Loop over the bulk fluid elements adjacent to boundary b?
      for(unsigned e=0;e<n_element;e++)
       {
        // Get pointer to the bulk fluid element that is adjacent to boundary b
        FLUID_ELEMENT* bulk_elem_pt = dynamic_cast<FLUID_ELEMENT*>(
         Fluid_mesh_pt->boundary_element_pt(b,e));
        //Find the index of the face of element e along boundary b
        int face_index = Fluid_mesh_pt->face_index_at_boundary(b,e);
        // Create new element
        ImposeDisplacementByLagrangeMultiplierElement<FLUID_ELEMENT>* el_pt =
         new ImposeDisplacementByLagrangeMultiplierElement<FLUID_ELEMENT>(
          bulk_elem_pt,face_index);
        // Add it to the mesh
        Lagrange_multiplier_mesh_pt[b]->add_element_pt(el_pt);
        // Set the GeomObject that defines the boundary shape and set
        // which bulk boundary we are attached to (needed to extract
        // the boundary coordinate from the bulk nodes)
        el_pt->set_boundary_shape_geom_object_pt(Solid_fsi_boundary_pt[b],b);
        // Loop over the nodes to apply boundary conditions
        unsigned nnod=el_pt->nnode();
        for (unsigned j=0;j<nnod;j++)
         {
          Node* nod_pt = el_pt->node_pt(j);
          // How many nodal values were used by the "bulk" element
          // that originally created this node?
          unsigned n_bulk_value=el_pt->nbulk_value(j);
          // The remaining ones are Lagrange multipliers
          unsigned nval=nod_pt->nvalue();
          //If we have more than two Lagrange multipliers, pin the rest
          if(nval > n_bulk_value + 2)
           {
            for (unsigned j=n_bulk_value+2;j<nval;j++)
             {
              nod_pt->pin(j);
             }
           }
          //If I'm also on one of the base boundaries, pin the Lagrange
          //Multipliers
          if((nod_pt->is_on_boundary(7)) || (nod_pt->is_on_boundary(3)))
           {
            for(unsigned j=n_bulk_value;j<nval;j++)
             {
              nod_pt->pin(j);
             }
           }
         }
       }
     }
   } // end of create_lagrange_multiplier_elements
References b, e(), FLUID_ELEMENT, oomph::Node::is_on_boundary(), j, oomph::FaceElement::nbulk_value(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Data::nvalue(), oomph::Data::pin(), and oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt().
create_lagrange_multiplier_elements() [3/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_lagrange_multiplier_elements () private
Create elements that enforce prescribed boundary motion for the pseudo-solid fluid mesh by Lagrange multipliers
create_lagrange_multiplier_elements() [4/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_lagrange_multiplier_elements ()
Create elements that enforce prescribed boundary motion for the pseudo-solid fluid mesh by Lagrange multipliers
create_lagrange_multiplier_elements() [5/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_lagrange_multiplier_elements ()
Create elements that enforce prescribed boundary motion for the pseudo-solid fluid mesh by Lagrange multipliers
create_parallel_flow_lagrange_elements() [1/2]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_parallel_flow_lagrange_elements
Create Lagrange multiplier elements that impose parallel flow.
 {
  // Counter for number of Lagrange multiplier elements
  unsigned count=0;
  // Loop over inflow/outflow boundaries
  for (unsigned in_out=0;in_out<2;in_out++)
   {
    // Loop over boundaries with fluid traction elements
    unsigned n=nfluid_inflow_traction_boundary();
    if (in_out==1) n=nfluid_outflow_traction_boundary();
    for (unsigned i=0;i<n;i++)
     {
      // Get boundary ID
      unsigned b=0;
      if (in_out==0)
       {
        b=Inflow_boundary_id[i];
       }
      else
       {
        b=Outflow_boundary_id[i];
       }
      // How many bulk elements are adjacent to boundary b?
      unsigned n_element = Fluid_mesh_pt->nboundary_element(b);
      // Loop over the bulk elements adjacent to boundary b
      for(unsigned e=0;e<n_element;e++)
       {
        // Get pointer to the bulk element that is adjacent to boundary b
        FLUID_ELEMENT* bulk_elem_pt = dynamic_cast<FLUID_ELEMENT*>(
         Fluid_mesh_pt->boundary_element_pt(b,e));
        //What is the index of the face of the element e along boundary b
        int face_index = Fluid_mesh_pt->face_index_at_boundary(b,e);
        // Build the corresponding Lagrange multiplier element
        ImposeParallelOutflowElement<FLUID_ELEMENT>* el_pt
         = new ImposeParallelOutflowElement<FLUID_ELEMENT>
         (bulk_elem_pt, face_index,
          Global_Parameters::Parallel_flow_lagrange_multiplier_id);
        // Add it to the mesh
        Parallel_flow_lagrange_multiplier_mesh_pt[count]->add_element_pt(el_pt);
        // Set the pointer to the prescribed pressure
        if (in_out==0)
         {
          // Attach elements that monitor volume flux (etc).
          NavierStokesSurfacePowerElement<FLUID_ELEMENT>* power_element_pt = new
           NavierStokesSurfacePowerElement<FLUID_ELEMENT>(
            bulk_elem_pt,face_index);
          //Add the elements to the mesh
          Inflow_flux_monitor_mesh_pt->add_element_pt(power_element_pt);
          // Pressure or flux control
          if (Global_Parameters::Prescribe_pressure)
           {
            // Set inflow pressure
            el_pt->pressure_pt()= &Global_Parameters::P_in;
           }
          else
           {
            // Build the flux control element
            NavierStokesFluxControlElement<FLUID_ELEMENT>* flux_element_pt = new
             NavierStokesFluxControlElement<FLUID_ELEMENT>(bulk_elem_pt,
                                                           face_index);
            //Add the new element to its mesh
            Inflow_flux_control_mesh_pt->add_element_pt(flux_element_pt);
           }
         }
        else
         {
          el_pt->pressure_pt()= &Global_Parameters::P_out;
         }
        //end of element setup
       }
      // Bump up counter
      count++;
     }
   }
  // Build master flux control element
  if (!Global_Parameters::Prescribe_pressure)
   {
    // Build master element
    NetFluxControlElement* flux_control_el_pt =
     new NetFluxControlElement(Inflow_flux_control_mesh_pt,
                               &Global_Parameters::Prescribed_flow_rate);
    // Add NetFluxControlElement to its own mesh
    Inflow_flux_control_master_mesh_pt->add_element_pt(flux_control_el_pt);
    // Get pointer to the inflow pressure data
    Global_Parameters::P_in_data_pt = flux_control_el_pt->pressure_data_pt();
    // Loop over the elements in the sub mesh and add P_in_data_pt
    // to external data
    unsigned n_el = Inflow_flux_control_mesh_pt->nelement();
    for (unsigned e=0; e< n_el; e++)
     {
      // Get pointer to the element
      GeneralisedElement* el_pt = Inflow_flux_control_mesh_pt->element_pt(e);
      // Dynamic cast
      dynamic_cast<NavierStokesFluxControlElement<FLUID_ELEMENT>* >(el_pt)->
       add_pressure_data(Global_Parameters::P_in_data_pt);
     }
   }
 }  // end of create_parallel_flow_lagrange_elements
References b, e(), FLUID_ELEMENT, i, n, Global_Parameters::P_in, Global_Parameters::P_in_data_pt, Global_Parameters::P_out, Global_Parameters::Parallel_flow_lagrange_multiplier_id, Global_Parameters::Prescribe_pressure, Global_Parameters::Prescribed_flow_rate, oomph::NetFluxControlElement< ELEMENT >::pressure_data_pt(), and oomph::ImposeParallelOutflowElement< ELEMENT >::pressure_pt().
create_parallel_flow_lagrange_elements() [2/2]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_parallel_flow_lagrange_elements ()
Create Lagrange multiplier elements that impose parallel flow.
delete_fsi_traction_elements()
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::delete_fsi_traction_elements () inline private
Delete the traction elements.
   {
    //There are three traction element boundaries
    for(unsigned b=0;b<3;++b)
     {
      const unsigned n_element = Traction_mesh_pt[b]->nelement();
      //Delete the elements
      for(unsigned e=0;e<n_element;e++)
       {
        delete Traction_mesh_pt[b]->element_pt(e);
       }
      //Wipe the mesh
      Traction_mesh_pt[b]->flush_element_and_node_storage();
      //Also wipe out the Mesh as Geometric objects
      delete Solid_fsi_boundary_pt[b]; Solid_fsi_boundary_pt[b] = 0;
     }
   }
References b, and e().
delete_lagrange_multiplier_elements()
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::delete_lagrange_multiplier_elements () inline private
Delete the traction elements.
   {
    //There are three Lagrange-multiplier element boundaries
    for(unsigned b=0;b<3;++b)
     {
      const unsigned n_element = Lagrange_multiplier_mesh_pt[b]->nelement();
      //Delete the elements
      for(unsigned e=0;e<n_element;e++)
       {
        delete Lagrange_multiplier_mesh_pt[b]->element_pt(e);
       }
      //Wipe the mesh
      Lagrange_multiplier_mesh_pt[b]->flush_element_and_node_storage();
     }
   }
References b, and e().
doc_parameters()
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_parameters () inline
Doc parameters.
   {
    std::cout << "\n\n=================================================\n";
    std::cout << "Average wall thickness: " << Wall_thickness
              << std::endl << std::endl;
    double speed_index=
     sqrt(Global_Parameters::Q/(0.5*Wall_thickness*Global_Parameters::Re));
    std::cout << "Q                     : " << Global_Parameters::Q << std::endl;
    std::cout << "Re                    : " << Global_Parameters::Re
              << std::endl;
    std::cout << "Period                : " << Global_Parameters::Period
              <<std::endl;
    std::cout << "Speed index           : " << speed_index  << std::endl;
    std::cout << "Wavelength            : "
              << Global_Parameters::Period/speed_index << std::endl;
    double alpha_sq=Global_Parameters::Re/Global_Parameters::Period;
    std::cout << "Square of Womersley   : "
              << alpha_sq << std::endl;
    std::cout << "=================================================\n\n";
   }
References Global_Parameters::Period, Global_Parameters::Q, Global_Parameters::Re, and sqrt().
doc_solid_boundary_coordinates() [1/4]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solid_boundary_coordinates private
Sanity check: Doc boundary coordinates from solid side.
Doc boundary coordinates in solid and plot GeomObject representation of FSI boundary.
 {
  // Doc boundary coordinates for fsi boundary in solid mesh
  std::ofstream the_file("solid_boundary_test.dat");
  // Initialise max/min boundary coordinate
  double zeta_min= 1.0e40;
  double zeta_max=-1.0e40;
  // Loop over FSI traction elements
  unsigned n_face_element = Traction_mesh_pt->nelement();
  for(unsigned e=0;e<n_face_element;e++)
   {
    //Cast the element pointer
    FSISolidTractionElement<SOLID_ELEMENT,2>* el_pt=
     dynamic_cast<FSISolidTractionElement<SOLID_ELEMENT,2>*>
     (Traction_mesh_pt->element_pt(e));
    // Doc boundary coordinate
    Vector<double> s(1);
    Vector<double> zeta(1);
    Vector<double> x(2);
    unsigned n_plot=5;
    the_file << el_pt->tecplot_zone_string(n_plot);
    // Loop over plot points
    unsigned num_plot_points=el_pt->nplot_points(n_plot);
    for (unsigned iplot=0;iplot<num_plot_points;iplot++)
     {
      // Get local coordinates of plot point
      el_pt->get_s_plot(iplot,n_plot,s);
      el_pt->interpolated_zeta(s,zeta);
      el_pt->interpolated_x(s,x);
      for (unsigned i=0;i<2;i++)
       {
        the_file << x[i] << " ";
       }
      the_file << zeta[0] << " ";
      // Update max/min boundary coordinate
      if (zeta[0]<zeta_min) zeta_min=zeta[0];
      if (zeta[0]>zeta_max) zeta_max=zeta[0];
      the_file << std::endl;
     }
   }
  // Close doc file
  the_file.close();
  // Doc compound GeomObject
  the_file.open("fsi_geom_object.dat");
  unsigned nplot=10000;
  Vector<double> zeta(1);
  Vector<double> r(2);
  for (unsigned i=0;i<nplot;i++)
   {
    zeta[0]=zeta_min+(zeta_max-zeta_min)*double(i)/double(nplot-1);
    Solid_fsi_boundary_pt->position(zeta,r);
    the_file << r[0] << " " << r[1] << std::endl;
   }
  the_file.close();
 } //end doc_solid_zeta
References e(), oomph::FiniteElement::get_s_plot(), i, oomph::FaceElement::interpolated_x(), oomph::FiniteElement::interpolated_zeta(), oomph::FiniteElement::nplot_points(), UniformPSDSelfTest::r, s, oomph::FiniteElement::tecplot_zone_string(), plotDoE::x, and Eigen::zeta().
doc_solid_boundary_coordinates() [2/4]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solid_boundary_coordinates (const unsigned & i) private
Sanity check: Doc boundary coordinates on i-th solid FSI interface.
Doc boundary coordinates of i-th solid FSI boundary.
 {
  //Doc boundary coordinates in fluid
  char filename[100];
  sprintf(filename,"RESLT/solid_boundary_coordinates%i.dat",i);
  std::ofstream the_file(filename);
  // Loop over traction elements
  unsigned n_face_element = Solid_fsi_traction_mesh_pt[i]->nelement();
  for(unsigned e=0;e<n_face_element;e++)
   {
    //Cast the element pointer
    FSISolidTractionElement<SOLID_ELEMENT,3>* el_pt=
     dynamic_cast<FSISolidTractionElement<SOLID_ELEMENT,3>*>
     (Solid_fsi_traction_mesh_pt[i]->element_pt(e));
    // Doc boundary coordinate
    Vector<double> s(2);
    Vector<double> zeta(2);
    Vector<double> x(3);
    unsigned n_plot=3;
    the_file << el_pt->tecplot_zone_string(n_plot);
    // Loop over plot points
    unsigned num_plot_points=el_pt->nplot_points(n_plot);
    for (unsigned iplot=0;iplot<num_plot_points;iplot++)
     {
      // Get local coordinates of plot point
      el_pt->get_s_plot(iplot,n_plot,s);
      el_pt->interpolated_zeta(s,zeta);
      el_pt->interpolated_x(s,x);
      for (unsigned i=0;i<3;i++)
       {
        the_file << x[i] << " ";
       }
      for (unsigned i=0;i<2;i++)
       {
        the_file << zeta[i] << " ";
       }
      the_file << std::endl;
     }
    el_pt->write_tecplot_zone_footer(the_file,n_plot);
   }
  // Close doc file
  the_file.close();
 } // end doc_solid_zeta
References e(), MergeRestartFiles::filename, oomph::FiniteElement::get_s_plot(), i, oomph::FaceElement::interpolated_x(), oomph::FiniteElement::interpolated_zeta(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), oomph::FiniteElement::write_tecplot_zone_footer(), plotDoE::x, and Eigen::zeta().
doc_solid_boundary_coordinates() [3/4]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solid_boundary_coordinates (const unsigned & i) private
Sanity check: Doc boundary coordinates on i-th solid FSI interface.
doc_solid_boundary_coordinates() [4/4]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solid_boundary_coordinates (const unsigned & i) private
Sanity check: Doc boundary coordinates on i-th solid FSI interface.
doc_solution() [1/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
 {
  // Elements can still be inverted near boundary
  // even if they're non-inverted at the 3D Gauss points
  // thus code can die here when evaluating the fluid traction
  // Deal with this later...
  FiniteElement::Accept_negative_jacobian=true;
  ofstream some_file;
  char filename[100];
  // Number of plot points
  unsigned npts;
  npts=5;
  // Output solid boundaries
  //------------------------
  sprintf(filename,"%s/solid_boundaries%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  Solid_mesh_pt->output_boundaries(some_file);
  some_file.close();
  // Output solid solution
  //-----------------------
  sprintf(filename,"%s/solid_soln%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  Solid_mesh_pt->output(some_file,npts);
  some_file.close();
  // Output fluid boundaries
  //------------------------
  sprintf(filename,"%s/fluid_boundaries%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  Fluid_mesh_pt->output_boundaries(some_file);
  some_file.close();
  // Output fluid solution
  //-----------------------
  sprintf(filename,"%s/fluid_soln%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  Fluid_mesh_pt->output(some_file,npts);
  some_file.close();
  // Output fsi traction
  //--------------------
  sprintf(filename,"%s/fsi_traction%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  unsigned n=nsolid_fsi_boundary();
  for (unsigned i=0;i<n;i++)
   {
    Solid_fsi_traction_mesh_pt[i]->output(some_file,npts);
   }
  some_file.close();
  // Document the volume flux at inflow
  double inflow_volume_flux = 0.0;
  unsigned nel = Inflow_flux_monitor_mesh_pt->nelement();
  for (unsigned e=0;e<nel;e++)
   {
    NavierStokesSurfacePowerElement<FLUID_ELEMENT>* el_pt=dynamic_cast<
     NavierStokesSurfacePowerElement<FLUID_ELEMENT>*>(
      Inflow_flux_monitor_mesh_pt->element_pt(e));
    inflow_volume_flux += el_pt->get_volume_flux();
   }
  cout << "Volume flux at inflow: " << inflow_volume_flux << std::endl;
 } // end_of_doc
References oomph::DocInfo::directory(), e(), MergeRestartFiles::filename, oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_volume_flux(), i, n, and oomph::DocInfo::number().
doc_solution() [2/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
doc_solution() [3/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
doc_solution() [4/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
doc_solution() [5/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
fluid_mesh_pt()
template<class FLUID_ELEMENT , class SOLID_ELEMENT > FluidTriangleMesh<FLUID_ELEMENT>*& UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::fluid_mesh_pt () inline
Access function for the fluid mesh.
   {
    return Fluid_mesh_pt;
   }
get_fluid_dissipation()
template<class FLUID_ELEMENT , class SOLID_ELEMENT > double UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::get_fluid_dissipation () inline private
Calculate the fluid dissipation.
   {
    double dissipation=0.0;
    const unsigned n_element = Fluid_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      //Cast to a fluid element
      FLUID_ELEMENT *el_pt =
       dynamic_cast<FLUID_ELEMENT*>(Fluid_mesh_pt->element_pt(e));
      //Add to the dissipation
      dissipation += el_pt->dissipation();
     }
    return dissipation;
   }
References e(), and FLUID_ELEMENT.
get_solid_strain_energy()
template<class FLUID_ELEMENT , class SOLID_ELEMENT > double UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::get_solid_strain_energy () inline private
Calculate the strain energy of the solid.
   {
    double strain_energy=0.0;
    const unsigned n_element = Solid_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      //Cast to a solid element
      SOLID_ELEMENT *el_pt =
       dynamic_cast<SOLID_ELEMENT*>(Solid_mesh_pt->element_pt(e));
      double pot_en, kin_en;
      el_pt->get_energy(pot_en,kin_en);
      strain_energy += pot_en;
     }
    return strain_energy;
   }
References e().
nfluid_fsi_boundary() [1/3]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::nfluid_fsi_boundary () inline private
Return total number of mesh boundaries in the fluid mesh that make up the FSI interface
   {return Fluid_fsi_boundary_id.size();}
nfluid_fsi_boundary() [2/3]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::nfluid_fsi_boundary () inline private
Return total number of mesh boundaries in the fluid mesh that make up the FSI interface
   {return Fluid_fsi_boundary_id.size();}
nfluid_fsi_boundary() [3/3]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::nfluid_fsi_boundary () inline private
Return total number of mesh boundaries in the fluid mesh that make up the FSI interface
   {return Fluid_fsi_boundary_id.size();}
nfluid_inflow_traction_boundary() [1/3]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::nfluid_inflow_traction_boundary () inline private
Return total number of mesh boundaries that make up the inflow boundary
   {return Inflow_boundary_id.size();}
nfluid_inflow_traction_boundary() [2/3]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::nfluid_inflow_traction_boundary () inline private
Return total number of mesh boundaries that make up the inflow boundary
   {return Inflow_boundary_id.size();}
nfluid_inflow_traction_boundary() [3/3]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::nfluid_inflow_traction_boundary () inline private
Return total number of mesh boundaries that make up the inflow boundary
   {return Inflow_boundary_id.size();}
nfluid_outflow_traction_boundary() [1/3]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::nfluid_outflow_traction_boundary () inline private
Return total number of mesh boundaries that make up the outflow boundary
   {return Outflow_boundary_id.size();}
nfluid_outflow_traction_boundary() [2/3]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::nfluid_outflow_traction_boundary () inline private
Return total number of mesh boundaries that make up the outflow boundary
   {return Outflow_boundary_id.size();}
nfluid_outflow_traction_boundary() [3/3]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::nfluid_outflow_traction_boundary () inline private
Return total number of mesh boundaries that make up the outflow boundary
   {return Outflow_boundary_id.size();}
nfluid_traction_boundary() [1/3]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::nfluid_traction_boundary () inline private
Return total number of mesh boundaries that make up the in- and outflow boundaries where a traction has to be applied
   {return Inflow_boundary_id.size()+Outflow_boundary_id.size();}
nfluid_traction_boundary() [2/3]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::nfluid_traction_boundary () inline private
Return total number of mesh boundaries that make up the in- and outflow boundaries where a traction has to be applied
   {return Inflow_boundary_id.size()+Outflow_boundary_id.size();}
nfluid_traction_boundary() [3/3]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::nfluid_traction_boundary () inline private
Return total number of mesh boundaries that make up the in- and outflow boundaries where a traction has to be applied
   {return Inflow_boundary_id.size()+Outflow_boundary_id.size();}
npinned_solid_boundary() [1/3]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::npinned_solid_boundary () inline private
Return total number of mesh boundaries in the solid mesh where the position is pinned.
   {return Pinned_solid_boundary_id.size();}
npinned_solid_boundary() [2/3]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::npinned_solid_boundary () inline private
Return total number of mesh boundaries in the solid mesh where the position is pinned.
   {return Pinned_solid_boundary_id.size();}
npinned_solid_boundary() [3/3]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::npinned_solid_boundary () inline private
Return total number of mesh boundaries in the solid mesh where the position is pinned.
   {return Pinned_solid_boundary_id.size();}
nsolid_fsi_boundary() [1/3]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::nsolid_fsi_boundary () inline private
Return total number of mesh boundaries in the solid mesh that make up the FSI interface
   {return Solid_fsi_boundary_id.size();}
nsolid_fsi_boundary() [2/3]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::nsolid_fsi_boundary () inline private
Return total number of mesh boundaries in the solid mesh that make up the FSI interface
   {return Solid_fsi_boundary_id.size();}
nsolid_fsi_boundary() [3/3]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::nsolid_fsi_boundary () inline private
Return total number of mesh boundaries in the solid mesh that make up the FSI interface
   {return Solid_fsi_boundary_id.size();}
output_strain_and_dissipation()
template<class FLUID_ELEMENT , class SOLID_ELEMENT > void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::output_strain_and_dissipation (std::ostream & trace) inline
Output function to compute the strain energy in the solid and the dissipation in the fluid and write to the output stream trace
   {
    double strain_energy = this->get_solid_strain_energy();
    double dissipation = this->get_fluid_dissipation();
    trace << Global_Physical_Variables::Q <<
     " " << dissipation << " " << strain_energy << std::endl;
   }
References Global_Physical_Variables::Q.
solid_mesh_pt()
template<class FLUID_ELEMENT , class SOLID_ELEMENT > MySolidTriangleMesh<SOLID_ELEMENT>*& UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::solid_mesh_pt () inline
Access function for the solid mesh.
   {
    return Solid_mesh_pt;
   }
Member Data Documentation
Fluid_fsi_boundary_id
template<class FLUID_ELEMENT , class SOLID_ELEMENT > Vector< unsigned > UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Fluid_fsi_boundary_id private
IDs of fluid mesh boundaries which make up the FSI interface.
Fluid_mesh_pt [1/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > SolidTetgenMesh<FLUID_ELEMENT>* UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Fluid_mesh_pt private
Bulk fluid mesh.
Fluid_mesh_pt [2/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > RefineableSolidTriangleMesh<FLUID_ELEMENT>* UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Fluid_mesh_pt
Bulk fluid mesh.
Fluid_mesh_pt [3/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > FluidTriangleMesh<FLUID_ELEMENT>* UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Fluid_mesh_pt private
Fluid mesh.
Fluid_mesh_pt [4/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > FluidTetMesh<FLUID_ELEMENT>* UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Fluid_mesh_pt private
Bulk fluid mesh.
Fluid_mesh_pt [5/5]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > MyFluidTetMesh<FLUID_ELEMENT>* UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Fluid_mesh_pt private
Bulk fluid mesh.
Fluid_outer_boundary_polyline_pt
template<class FLUID_ELEMENT , class SOLID_ELEMENT > TriangleMeshPolygon* UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Fluid_outer_boundary_polyline_pt private
Triangle mesh polygon for outer boundary.
Fluid_traction_mesh_pt
template<class FLUID_ELEMENT , class SOLID_ELEMENT > Vector<Mesh*> UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Fluid_traction_mesh_pt private
Meshes of fluid traction elements that apply pressure at in/outflow.
Inflow_boundary_id
template<class FLUID_ELEMENT , class SOLID_ELEMENT > Vector< unsigned > UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Inflow_boundary_id private
IDs of fluid mesh boundaries along which inflow boundary conditions are applied
Inflow_flux_control_master_mesh_pt
template<class FLUID_ELEMENT , class SOLID_ELEMENT > Mesh* UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Inflow_flux_control_master_mesh_pt private
Mesh containing the master flux control element.
Inflow_flux_control_mesh_pt
template<class FLUID_ELEMENT , class SOLID_ELEMENT > Mesh* UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Inflow_flux_control_mesh_pt private
Mesh of FaceElements that control the inflow.
Inflow_flux_monitor_mesh_pt
template<class FLUID_ELEMENT , class SOLID_ELEMENT > Mesh* UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Inflow_flux_monitor_mesh_pt private
Mesh containing the FaceElements that monitor the inflow.
Lagrange_multiplier_mesh_pt [1/2]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > Vector< SolidMesh * > UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Lagrange_multiplier_mesh_pt private
Meshes of Lagrange multiplier elements.
Vector of pointers to mesh of Lagrange multiplier elements.
Lagrange_multiplier_mesh_pt [2/2]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > SolidMesh* UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Lagrange_multiplier_mesh_pt private
Pointers to mesh of Lagrange multiplier elements.
Outflow_boundary_id
template<class FLUID_ELEMENT , class SOLID_ELEMENT > Vector< unsigned > UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Outflow_boundary_id private
IDs of fluid mesh boundaries along which inflow boundary conditions are applied
Parallel_flow_lagrange_multiplier_mesh_pt
template<class FLUID_ELEMENT , class SOLID_ELEMENT > Vector< Mesh * > UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Parallel_flow_lagrange_multiplier_mesh_pt private
Meshes of Lagrange multiplier elements that impose parallel flow.
Pinned_solid_boundary_id
template<class FLUID_ELEMENT , class SOLID_ELEMENT > Vector< unsigned > UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Pinned_solid_boundary_id private
IDs of solid mesh boundaries where displacements are pinned.
Solid_fsi_boundary_id
template<class FLUID_ELEMENT , class SOLID_ELEMENT > Vector< unsigned > UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Solid_fsi_boundary_id private
IDs of solid mesh boundaries which make up the FSI interface.
Solid_fsi_boundary_pt [1/2]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > Vector< MeshAsGeomObject * > UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Solid_fsi_boundary_pt private
GeomObject incarnations of the FSI boundary in the solid mesh.
Solid_fsi_boundary_pt [2/2]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > MeshAsGeomObject* UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Solid_fsi_boundary_pt private
GeomObject incarnation of fsi boundary in solid mesh.
Solid_fsi_traction_mesh_pt
template<class FLUID_ELEMENT , class SOLID_ELEMENT > Vector< SolidMesh * > UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Solid_fsi_traction_mesh_pt private
Meshes of FSI traction elements.
Solid_mesh_pt [1/4]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > MySolidTetgenMesh< SOLID_ELEMENT > * UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Solid_mesh_pt private
Bulk solid mesh.
Solid_mesh_pt [2/4]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > RefineableSolidTriangleMesh<SOLID_ELEMENT>* UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Solid_mesh_pt private
Bulk solid mesh.
Solid_mesh_pt [3/4]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > MySolidTriangleMesh<SOLID_ELEMENT>* UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Solid_mesh_pt private
Solid mesh.
Solid_mesh_pt [4/4]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > MySolidTetgenMesh<SOLID_ELEMENT>* UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Solid_mesh_pt private
Bulk solid mesh.
Solid_outer_boundary_id
template<class FLUID_ELEMENT , class SOLID_ELEMENT > Vector<unsigned> UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Solid_outer_boundary_id private
IDs of solid mesh boundaries which make up the outer surface.
Solid_outer_boundary_polyline_pt
template<class FLUID_ELEMENT , class SOLID_ELEMENT > TriangleMeshPolygon* UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Solid_outer_boundary_polyline_pt private
Triangle mesh polygon for outer boundary.
Traction_mesh_pt [1/2]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > Vector<SolidMesh*> UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Traction_mesh_pt private
Vectors of pointers to mesh of traction elements.
Traction_mesh_pt [2/2]
template<class FLUID_ELEMENT , class SOLID_ELEMENT > SolidMesh* UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Traction_mesh_pt private
Vector of pointers to mesh of FSI traction elements.
Wall_thickness
template<class FLUID_ELEMENT , class SOLID_ELEMENT > double UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Wall_thickness private
Average wall thickness (computed from area of fsi interface and volume of solid mesh.
The documentation for this class was generated from the following files:
unsteady_vmtk_fsi.cc
unstructured_adaptive_2d_fsi.cc
unstructured_two_d_fsi.cc
unstructured_three_d_fsi.cc
vmtk_fsi.cc