MercuryDPM: Problem.h File Reference
Problem.h File Reference
#include <cereal/cereal.hpp>
#include <Mercury3D.h>
Classes
class SerializedProblem
Functions
template<class Archive >
void load (Archive &ar, SerializedProblem &base)
template<class Archive >
void save (Archive &ar, const SerializedProblem &base)
Function Documentation
load()
template<class Archive > void load (Archive & ar, SerializedProblem & base)
{
     using namespace cereal;
     std::string name;
     Mdouble tMax;
     Mdouble tStep;
     Vec3D gravity;
     Vec3D minimum;
     Vec3D maximum;
     ar( CEREAL_NVP( name )
         ,CEREAL_NVP( tMax )
         ,CEREAL_NVP( tStep )
         ,CEREAL_NVP( gravity )
         ,CEREAL_NVP( minimum )
         ,CEREAL_NVP( maximum )
         ,cereal::make_nvp("particles", base.particleHandler)
         ,cereal::make_nvp("walls", base.wallHandler)
     );
     base.setName( name );
     base.setTimeMax( tMax );
     base.setTimeStep( tStep );
     base.setGravity( gravity );
     base.setXMin(minimum.X);
     base.setYMin(minimum.Y);
     base.setZMin(minimum.Z);
     base.setXMax(maximum.X);
     base.setYMax(maximum.Y);
     base.setZMax(maximum.Z);
 }
References Gravity::gravity(), plotDoE::name, DPMBase::particleHandler, DPMBase::setGravity(), DPMBase::setName(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), DPMBase::setXMax(), DPMBase::setXMin(), DPMBase::setYMax(), DPMBase::setYMin(), DPMBase::setZMax(), DPMBase::setZMin(), oomph::Global_string_for_annotation::string(), DPMBase::wallHandler, Vec3D::X, Vec3D::Y, and Vec3D::Z.
save()
template<class Archive > void save (Archive & ar, const SerializedProblem & base)
{
     Vec3D minimum;
     Vec3D maximum;
     minimum.X = base.getXMin();
     minimum.Y = base.getYMin();
     minimum.Z = base.getZMin();
     maximum.X = base.getXMax();
     maximum.Y = base.getYMax();
     maximum.Z = base.getZMax();
     ar ( cereal::make_nvp("name", base.getName())
          ,CEREAL_NVP(minimum)
          ,CEREAL_NVP(maximum)
          ,cereal::make_nvp("tMax", base.getTimeMax())
          ,cereal::make_nvp("tStep", base.getTimeStep())
          ,cereal::make_nvp("gravity", base.getGravity())
          ,cereal::make_nvp("particles", base.particleHandler)
          ,cereal::make_nvp("walls", base.wallHandler)
        );
 }
References DPMBase::getGravity(), DPMBase::getName(), DPMBase::getTimeMax(), DPMBase::getTimeStep(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), DPMBase::getZMax(), DPMBase::getZMin(), DPMBase::particleHandler, DPMBase::wallHandler, Vec3D::X, Vec3D::Y, and Vec3D::Z.