MercuryDPM: Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ > Class Template Reference
Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ > Class Template Reference
Geometry » Reference » Geometry_Module
A parametrized line.
#include <ParametrizedLine.h>
Public Types
enum { AmbientDimAtCompileTime = AmbientDim_ , Options = Options_ }
typedef Scalar_ Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef Eigen::Index Index
typedef Matrix< Scalar, AmbientDimAtCompileTime, 1, Options > VectorType
Public Member Functions
EIGEN_DEVICE_FUNC ParametrizedLine ()
template<int OtherOptions>
EIGEN_DEVICE_FUNC ParametrizedLine (const ParametrizedLine< Scalar, AmbientDimAtCompileTime, OtherOptions > &other)
EIGEN_DEVICE_FUNC ParametrizedLine (Index _dim)
EIGEN_DEVICE_FUNC ParametrizedLine (const VectorType &origin, const VectorType &direction)
template<int OtherOptions>
EIGEN_DEVICE_FUNC ParametrizedLine (const Hyperplane< Scalar_, AmbientDim_, OtherOptions > &hyperplane)
EIGEN_DEVICE_FUNC ~ParametrizedLine ()
EIGEN_DEVICE_FUNC Index dim () const
EIGEN_DEVICE_FUNC const VectorType & origin () const
EIGEN_DEVICE_FUNC VectorType & origin ()
EIGEN_DEVICE_FUNC const VectorType & direction () const
EIGEN_DEVICE_FUNC VectorType & direction ()
EIGEN_DEVICE_FUNC RealScalar squaredDistance (const VectorType &p) const
EIGEN_DEVICE_FUNC RealScalar distance (const VectorType &p) const
EIGEN_DEVICE_FUNC VectorType projection (const VectorType &p) const
EIGEN_DEVICE_FUNC VectorType pointAt (const Scalar &t) const
template<int OtherOptions>
EIGEN_DEVICE_FUNC Scalar intersectionParameter (const Hyperplane< Scalar_, AmbientDim_, OtherOptions > &hyperplane) const
template<int OtherOptions>
EIGEN_DEVICE_FUNC Scalar intersection (const Hyperplane< Scalar_, AmbientDim_, OtherOptions > &hyperplane) const
template<int OtherOptions>
EIGEN_DEVICE_FUNC VectorType intersectionPoint (const Hyperplane< Scalar_, AmbientDim_, OtherOptions > &hyperplane) const
template<typename XprType >
EIGEN_DEVICE_FUNC ParametrizedLine & transform (const MatrixBase< XprType > &mat, TransformTraits traits=Affine)
template<int TrOptions>
EIGEN_DEVICE_FUNC ParametrizedLine & transform (const Transform< Scalar, AmbientDimAtCompileTime, Affine, TrOptions > &t, TransformTraits traits=Affine)
template<typename NewScalarType >
EIGEN_DEVICE_FUNC internal::cast_return_type< ParametrizedLine, ParametrizedLine< NewScalarType, AmbientDimAtCompileTime, Options > >::type cast () const
template<typename OtherScalarType , int OtherOptions>
EIGEN_DEVICE_FUNC ParametrizedLine (const ParametrizedLine< OtherScalarType, AmbientDimAtCompileTime, OtherOptions > &other)
EIGEN_DEVICE_FUNC bool isApprox (const ParametrizedLine &other, const typename NumTraits< Scalar >::Real &prec=NumTraits< Scalar >::dummy_precision()) const
template<int OtherOptions>
EIGEN_DEVICE_FUNC Scalar_ intersectionParameter (const Hyperplane< Scalar_, AmbientDim_, OtherOptions > &hyperplane) const
template<int OtherOptions>
EIGEN_DEVICE_FUNC Scalar_ intersection (const Hyperplane< Scalar_, AmbientDim_, OtherOptions > &hyperplane) const
Static Public Member Functions
static EIGEN_DEVICE_FUNC ParametrizedLine Through (const VectorType &p0, const VectorType &p1)
Protected Attributes
VectorType m_origin
VectorType m_direction
Detailed Description
template<typename Scalar_, int AmbientDim_, int Options_>
class Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >
A parametrized line.
\geometry_module
A parametrized line is defined by an origin point \(\mathbf{o} \) and a unit direction vector \(\mathbf{d} \) such that the line corresponds to the set \(l(t) = \mathbf{o} + t \mathbf{d} \), \(t \in \mathbf{R} \).
Template Parameters
Scalar_ the scalar type, i.e., the type of the coefficients
AmbientDim_ the dimension of the ambient space, can be a compile time value or Dynamic.
Member Typedef Documentation
Index
template<typename Scalar_ , int AmbientDim_, int Options_> typedef Eigen::Index Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::Index
Deprecated:
since Eigen 3.3
RealScalar
template<typename Scalar_ , int AmbientDim_, int Options_> typedef NumTraits<Scalar>::Real Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::RealScalar
Scalar
template<typename Scalar_ , int AmbientDim_, int Options_> typedef Scalar_ Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::Scalar
VectorType
template<typename Scalar_ , int AmbientDim_, int Options_> typedef Matrix<Scalar, AmbientDimAtCompileTime, 1, Options> Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::VectorType
Member Enumeration Documentation
anonymous enum
template<typename Scalar_ , int AmbientDim_, int Options_> anonymous enum
Enumerator
AmbientDimAtCompileTime
Options
 { AmbientDimAtCompileTime = AmbientDim_, Options = Options_ };
Constructor & Destructor Documentation
ParametrizedLine() [1/6]
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::ParametrizedLine () inline
Default constructor without initialization
 {}
Referenced by Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::cast(), and Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::Through().
ParametrizedLine() [2/6]
template<typename Scalar_ , int AmbientDim_, int Options_> template<int OtherOptions> EIGEN_DEVICE_FUNC Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::ParametrizedLine (const ParametrizedLine< Scalar, AmbientDimAtCompileTime, OtherOptions > & other) inline
       : m_origin(other.origin()), m_direction(other.direction()) {}
ParametrizedLine() [3/6]
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::ParametrizedLine (Index _dim) inline explicit
Constructs a dynamic-size line with _dim the dimension of the ambient space
 : m_origin(_dim), m_direction(_dim) {}
ParametrizedLine() [4/6]
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::ParametrizedLine (const VectorType & origin, const VectorType & direction) inline
Initializes a parametrized line of direction direction and origin origin.
Warning
the vector direction is assumed to be normalized.
       : m_origin(origin), m_direction(direction) {}
ParametrizedLine() [5/6]
template<typename Scalar_ , int AmbientDim_, int Options_> template<int OtherOptions> EIGEN_DEVICE_FUNC Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::ParametrizedLine (const Hyperplane< Scalar_, AmbientDim_, OtherOptions > & hyperplane) inline explicit
Constructs a parametrized line from a 2D hyperplane
Warning
the ambient space must have dimension 2 such that the hyperplane actually describes a line
{
   EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(VectorType, 2)
   direction() = hyperplane.normal().unitOrthogonal();
   origin() = -hyperplane.normal() * hyperplane.offset();
 }
References EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, and hyperplane().
~ParametrizedLine()
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::~ParametrizedLine () inline
 {}
ParametrizedLine() [6/6]
template<typename Scalar_ , int AmbientDim_, int Options_> template<typename OtherScalarType , int OtherOptions> EIGEN_DEVICE_FUNC Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::ParametrizedLine (const ParametrizedLine< OtherScalarType, AmbientDimAtCompileTime, OtherOptions > & other) inline explicit
Copy constructor with scalar type conversion
{
     m_origin = other.origin().template cast<Scalar>();
     m_direction = other.direction().template cast<Scalar>();
   }
References Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::direction(), Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::m_direction, Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::m_origin, and Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::origin().
Member Function Documentation
cast()
template<typename Scalar_ , int AmbientDim_, int Options_> template<typename NewScalarType > EIGEN_DEVICE_FUNC internal::cast_return_type<ParametrizedLine, ParametrizedLine<NewScalarType, AmbientDimAtCompileTime, Options> >::type Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
                    {
     return typename internal::cast_return_type<
         ParametrizedLine, ParametrizedLine<NewScalarType, AmbientDimAtCompileTime, Options> >::type(*this);
   }
References Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::ParametrizedLine(), and compute_granudrum_aor::type.
dim()
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC Index Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::dim () const inline
Returns
the dimension in which the line holds
 { return m_direction.size(); }
References Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::m_direction.
direction() [1/2]
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC VectorType& Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::direction (void) inline
 { return m_direction; }
References Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::m_direction.
direction() [2/2]
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC const VectorType& Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::direction (void) const inline
 { return m_direction; }
References Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::m_direction.
Referenced by Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Hyperplane(), Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::ParametrizedLine(), Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::projection(), Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::squaredDistance(), and Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::transform().
distance()
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC RealScalar Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::distance (const VectorType & p) const inline
Returns
the distance of a point p to its projection onto the line *this.
See also
squaredDistance()
{
     EIGEN_USING_STD(sqrt) return sqrt(squaredDistance(p));
   }
References EIGEN_USING_STD, p, sqrt(), and Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::squaredDistance().
intersection() [1/2]
template<typename Scalar_ , int AmbientDim_, int Options_> template<int OtherOptions> EIGEN_DEVICE_FUNC Scalar Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::intersection (const Hyperplane< Scalar_, AmbientDim_, OtherOptions > & hyperplane) const
intersection() [2/2]
template<typename Scalar_ , int AmbientDim_, int Options_> template<int OtherOptions> EIGEN_DEVICE_FUNC Scalar_ Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::intersection (const Hyperplane< Scalar_, AmbientDim_, OtherOptions > & hyperplane) const inline
Deprecated:
use intersectionParameter()
Returns
the parameter value of the intersection between *this and the given hyperplane
{
   return intersectionParameter(hyperplane);
 }
References hyperplane().
intersectionParameter() [1/2]
template<typename Scalar_ , int AmbientDim_, int Options_> template<int OtherOptions> EIGEN_DEVICE_FUNC Scalar Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::intersectionParameter (const Hyperplane< Scalar_, AmbientDim_, OtherOptions > & hyperplane) const
intersectionParameter() [2/2]
template<typename Scalar_ , int AmbientDim_, int Options_> template<int OtherOptions> EIGEN_DEVICE_FUNC Scalar_ Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::intersectionParameter (const Hyperplane< Scalar_, AmbientDim_, OtherOptions > & hyperplane) const inline
Returns
the parameter value of the intersection between *this and the given hyperplane
{
   return -(hyperplane.offset() + hyperplane.normal().dot(origin())) / hyperplane.normal().dot(direction());
 }
References hyperplane().
intersectionPoint()
template<typename Scalar_ , int AmbientDim_, int Options_> template<int OtherOptions> EIGEN_DEVICE_FUNC ParametrizedLine< Scalar_, AmbientDim_, Options_ >::VectorType Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::intersectionPoint (const Hyperplane< Scalar_, AmbientDim_, OtherOptions > & hyperplane) const inline
Returns
the point of the intersection between *this and the given hyperplane
{
   return pointAt(intersectionParameter(hyperplane));
 }
References hyperplane().
isApprox()
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC bool Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::isApprox (const ParametrizedLine< Scalar_, AmbientDim_, Options_ > & other, const typename NumTraits< Scalar >::Real & prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See also
MatrixBase::isApprox()
{
     return m_origin.isApprox(other.m_origin, prec) && m_direction.isApprox(other.m_direction, prec);
   }
References Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::m_direction, and Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::m_origin.
origin() [1/2]
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC VectorType& Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::origin () inline
 { return m_origin; }
References Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::m_origin.
origin() [2/2]
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC const VectorType& Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::origin () const inline
 { return m_origin; }
References Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::m_origin.
Referenced by Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Hyperplane(), Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::ParametrizedLine(), Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::projection(), Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::squaredDistance(), and Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::transform().
pointAt()
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC ParametrizedLine< Scalar_, AmbientDim_, Options_ >::VectorType Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::pointAt (const Scalar & t) const inline
Returns
the point at t along this line
{
   return origin() + (direction() * t);
 }
References plotPSD::t.
projection()
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC VectorType Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::projection (const VectorType & p) const inline
Returns
the projection of a point p onto the line *this.
{
     return origin() + direction().dot(p - origin()) * direction();
   }
References Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::direction(), Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::origin(), and p.
squaredDistance()
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC RealScalar Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::squaredDistance (const VectorType & p) const inline
Returns
the squared distance of a point p to its projection onto the line *this.
See also
distance()
{
     VectorType diff = p - origin();
     return (diff - direction().dot(diff) * direction()).squaredNorm();
   }
References Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::direction(), dot(), Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::origin(), and p.
Referenced by Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::distance().
Through()
template<typename Scalar_ , int AmbientDim_, int Options_> static EIGEN_DEVICE_FUNC ParametrizedLine Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::Through (const VectorType & p0, const VectorType & p1) inline static
Constructs a parametrized line going from p0 to p1.
{
     return ParametrizedLine(p0, (p1 - p0).normalized());
   }
References p0, p1, and Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::ParametrizedLine().
transform() [1/2]
template<typename Scalar_ , int AmbientDim_, int Options_> template<typename XprType > EIGEN_DEVICE_FUNC ParametrizedLine& Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::transform (const MatrixBase< XprType > & mat, TransformTraits traits = Affine) inline
Applies the transformation matrix mat to *this and returns a reference to *this.
Parameters
mat the Dim x Dim transformation matrix
traits specifies whether the matrix mat represents an Isometry or a more generic Affine transformation. The default is Affine.
{
     if (traits == Affine)
       direction() = (mat * direction()).normalized();
     else if (traits == Isometry)
       direction() = mat * direction();
     else {
       eigen_assert(0 && "invalid traits value in ParametrizedLine::transform()");
     }
     origin() = mat * origin();
     return *this;
   }
References Eigen::Affine, Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::direction(), eigen_assert, Eigen::Isometry, and Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::origin().
Referenced by Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::transform().
transform() [2/2]
template<typename Scalar_ , int AmbientDim_, int Options_> template<int TrOptions> EIGEN_DEVICE_FUNC ParametrizedLine& Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::transform (const Transform< Scalar, AmbientDimAtCompileTime, Affine, TrOptions > & t, TransformTraits traits = Affine) inline
Applies the transformation t to *this and returns a reference to *this.
Parameters
t the transformation of dimension Dim
traits specifies whether the transformation t represents an Isometry or a more generic Affine transformation. The default is Affine. Other kind of transformations are not supported.
{
     transform(t.linear(), traits);
     origin() += t.translation();
     return *this;
   }
References Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::origin(), plotPSD::t, and Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::transform().
Member Data Documentation
m_direction
template<typename Scalar_ , int AmbientDim_, int Options_> VectorType Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::m_direction protected
Referenced by Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::dim(), Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::direction(), Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::isApprox(), and Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::ParametrizedLine().
m_origin
template<typename Scalar_ , int AmbientDim_, int Options_> VectorType Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::m_origin protected
Referenced by Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::isApprox(), Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::origin(), and Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::ParametrizedLine().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
ParametrizedLine.h