MercuryDPM: Eigen::internal::trsmKernelL< Scalar, Index, Mode, Conjugate, TriStorageOrder, OtherInnerStride, Specialized > Struct Template Reference
Eigen::internal::trsmKernelL< Scalar, Index, Mode, Conjugate, TriStorageOrder, OtherInnerStride, Specialized > Struct Template Reference
#include <TriangularSolverMatrix.h>
Static Public Member Functions
static void kernel (Index size, Index otherSize, const Scalar *_tri, Index triStride, Scalar *_other, Index otherIncr, Index otherStride)
Member Function Documentation
kernel()
template<typename Scalar , typename Index , int Mode, bool Conjugate, int TriStorageOrder, int OtherInnerStride, bool Specialized> EIGEN_STRONG_INLINE void Eigen::internal::trsmKernelL< Scalar, Index, Mode, Conjugate, TriStorageOrder, OtherInnerStride, Specialized >::kernel (Index size, Index otherSize, const Scalar * _tri, Index triStride, Scalar * _other, Index otherIncr, Index otherStride) static
{
   typedef const_blas_data_mapper<Scalar, Index, TriStorageOrder> TriMapper;
   typedef blas_data_mapper<Scalar, Index, ColMajor, Unaligned, OtherInnerStride> OtherMapper;
   TriMapper tri(_tri, triStride);
   OtherMapper other(_other, otherStride, otherIncr);
   enum { IsLower = (Mode & Lower) == Lower };
   conj_if<Conjugate> conj;
   // tr solve
   for (Index k = 0; k < size; ++k) {
     // TODO write a small kernel handling this (can be shared with trsv)
     Index i = IsLower ? k : -k - 1;
     Index rs = size - k - 1;  // remaining size
     Index s = TriStorageOrder == RowMajor ? (IsLower ? 0 : i + 1) : IsLower ? i + 1 : i - rs;
     Scalar a = (Mode & UnitDiag) ? Scalar(1) : Scalar(Scalar(1) / conj(tri(i, i)));
     for (Index j = 0; j < otherSize; ++j) {
       if (TriStorageOrder == RowMajor) {
         Scalar b(0);
         const Scalar* l = &tri(i, s);
         typename OtherMapper::LinearMapper r = other.getLinearMapper(s, j);
         for (Index i3 = 0; i3 < k; ++i3) b += conj(l[i3]) * r(i3);
         other(i, j) = (other(i, j) - b) * a;
       } else {
         Scalar& otherij = other(i, j);
         otherij *= a;
         Scalar b = otherij;
         typename OtherMapper::LinearMapper r = other.getLinearMapper(s, j);
         typename TriMapper::LinearMapper l = tri.getLinearMapper(s, i);
         for (Index i3 = 0; i3 < rs; ++i3) r(i3) -= b * conj(l(i3));
       }
     }
   }
 }
References a, b, Eigen::conj(), i, j, k, Eigen::Lower, UniformPSDSelfTest::r, Eigen::RowMajor, s, size, tri, and Eigen::UnitDiag.
Referenced by Eigen::internal::trsmKernelL< double, Index, Mode, false, TriStorageOrder, 1, true >::kernel(), and Eigen::internal::trsmKernelL< float, Index, Mode, false, TriStorageOrder, 1, true >::kernel().
The documentation for this struct was generated from the following files:
TrsmKernel.h
TriangularSolverMatrix.h