MercuryDPM: LevelSetUnitTest.cpp File Reference
LevelSetUnitTest.cpp File Reference
#include "Mercury3D.h"
#include "Walls/LevelSetWall.h"
#include "Walls/InfiniteWall.h"
#include "Species/LinearViscoelasticSpecies.h"
Functions
int main ()
Function Documentation
main()
int main ()
            {
     DPMBase dpm;
     dpm.setName("LevelSetUnitTest");
     dpm.removeOldFiles();
     LinearViscoelasticSpecies* s = dpm.speciesHandler.copyAndAddObject(LinearViscoelasticSpecies());
     Mdouble r = 0.04;
     s->setCollisionTimeAndRestitutionCoefficient(0.5,0.5,s->getMassFromRadius(r));
     logger(INFO,"k % gam %",s->getStiffness(),s->getDissipation());
     LevelSetWall* w = dpm.wallHandler.copyAndAddObject(LevelSetWall(LevelSetWall::Shape::Diamond, 0.8, s));
     //w->setPosition({0,0,0}); //change this to check the transation properties
     w->setVelocity(Vec3D(-1,-1,0)*0.01);
     w->setAngularVelocity(Vec3D(0,0,1)*-0.05);
     dpm.wallHandler.copyAndAddObject(InfiniteWall({-1,0,0},{-1,0,0},s));
     dpm.wallHandler.copyAndAddObject(InfiniteWall({ 1,0,0},{ 0,0,0},s));
     dpm.wallHandler.copyAndAddObject(InfiniteWall({0,-1,0},{0,-1,0},s));
     dpm.wallHandler.copyAndAddObject(InfiniteWall({0, 1,0},{0, 0,0},s));
     dpm.wallHandler.copyAndAddObject(InfiniteWall({0,0,-1},{0,0,-r},s));
     dpm.wallHandler.copyAndAddObject(InfiniteWall({0,0, 1},{0,0, r},s));
     for (unsigned i=1; i<dpm.wallHandler.getNumberOfObjects(); ++i) {
         dpm.wallHandler.getObject(i)->setVTKVisibility(false);
     }
     dpm.setTimeMax(20);
     dpm.setTimeStep(0.01);
     dpm.setDomain({-1,-1,-1},{1,1,1});
     dpm.setGravity(Vec3D(1,1,0)*0.5*s->getStiffness());
     SphericalParticle p(s);
     Mdouble d;
     Vec3D n;
     p.setRadius(r);
     for (Mdouble x=-1+r; x<=0; x+=2*r)
         for (Mdouble y=-1+r; y<=0; y+=2*r)
             for (Mdouble z=0; z<=0; z+=2*r) {
                 p.setPosition({x,y,z});
                 if (!w->getDistanceAndNormal(p,d,n)) {
                     dpm.particleHandler.copyAndAddObject(p);
                 }
             }
     logger(INFO,"#particles %",dpm.particleHandler.getNumberOfObjects());
     dpm.wallHandler.setWriteVTK(FileType::MULTIPLE_FILES);
     dpm.setParticlesWriteVTK(true);
     dpm.solve();
     w->writeToFile(10,0.0);
     return 0;
 }
References BaseHandler< T >::copyAndAddObject(), LevelSetWall::Diamond, BaseHandler< T >::getNumberOfObjects(), ParticleHandler::getNumberOfObjects(), BaseHandler< T >::getObject(), i, INFO, logger, MULTIPLE_FILES, n, p, DPMBase::particleHandler, UniformPSDSelfTest::r, DPMBase::removeOldFiles(), s, DPMBase::setDomain(), DPMBase::setGravity(), DPMBase::setName(), DPMBase::setParticlesWriteVTK(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), BaseWall::setVTKVisibility(), WallHandler::setWriteVTK(), DPMBase::solve(), DPMBase::speciesHandler, w, DPMBase::wallHandler, plotDoE::x, and y.