MercuryDPM: adaptive_driven_cavity.cc File Reference
demo_drivers/mpi/distribution/adaptive_driven_cavity/adaptive_driven_cavity.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class RefineableDrivenCavityProblem< ELEMENT >
Namespaces
Global_Physical_Variables
Global variables.
Functions
int main (int argc, char **argv)
Driver for RefineableDrivenCavity test problem.
Function Documentation
main()
int main (int argc , char ** argv)
Driver for RefineableDrivenCavity test problem.
 {
 #ifdef OOMPH_HAS_MPI
  // Initialise MPI
  MPI_Helpers::init(argc,argv);
 #endif
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Set output directory
  DocInfo doc_info;
  doc_info.set_directory("RESLT");
  // Set max. number of black-box adaptation
  unsigned max_adapt=3;
  // Solve problem with Taylor Hood elements
  //---------------------------------------
  {
   //Build problem
   RefineableDrivenCavityProblem<RefineableQTaylorHoodElement<2> > problem;
   //Are there command-line arguments?
   if (CommandLineArgs::Argc==1)
    {
 #ifdef OOMPH_HAS_MPI
     // Provide storage for each element's partition number
     const unsigned n_element=problem.mesh_pt()->nelement();
     Vector<unsigned> out_element_partition(n_element);
     // Distribute the problem
     bool report_stats=true;
     out_element_partition=problem.distribute(report_stats);
     // Write partition to disk
     std::ofstream output_file;
     char filename[100];
     sprintf(filename,"out_adaptive_cavity_1_partition.dat");
     output_file.open(filename);
     for (unsigned e=0;e<n_element;e++)
      {
       output_file << out_element_partition[e] << std::endl;
      }
     // Check halo schemes (optional)
     problem.check_halo_schemes(doc_info);
 #endif
     // Solve the problem with automatic adaptation
     problem.newton_solve(max_adapt);
     //Output solution
     problem.doc_solution(doc_info);
    }
   // Validation run - read in partition from file
   else
    {
 #ifdef OOMPH_HAS_MPI
     // DocInfo object specifies directory in which we document
     // the distribution
     DocInfo mesh_doc_info;
     mesh_doc_info.set_directory("RESLT_TH_MESH");
     // Create storage for pre-determined partitioning
     const unsigned n_element=problem.mesh_pt()->nelement();
     Vector<unsigned> element_partition(n_element);
     // Read in partitioning from disk
     std::ifstream input_file;
     char filename[100];
     sprintf(filename,"adaptive_cavity_1_partition.dat");
     input_file.open(filename);
     std::string input_string;
     for (unsigned e=0;e<n_element;e++)
      {
       getline(input_file,input_string,'\n');
       element_partition[e]=atoi(input_string.c_str());
      }
     // Now perform the distribution and document it
     bool report_stats=true;
     problem.distribute(element_partition,mesh_doc_info,report_stats);
 #endif
     // solve with adaptation
     problem.newton_solve(max_adapt);
     //Output solution
     problem.doc_solution(doc_info);
 #ifdef OOMPH_HAS_MPI
     mesh_doc_info.number()=1;
     problem.mesh_pt()->doc_mesh_distribution(mesh_doc_info);
 #endif
    }
  } // end of Taylor Hood elements
  // Solve problem with Crouzeix Raviart elements
  //--------------------------------------------
  {
   // Build problem
   RefineableDrivenCavityProblem<RefineableQCrouzeixRaviartElement<2> > problem;
   //Are there command-line arguments?
   if (CommandLineArgs::Argc==1)
    {
 #ifdef OOMPH_HAS_MPI
     // Distribute the problem
     problem.distribute();
     // Check halo schemes (optional)
     problem.check_halo_schemes(doc_info);
 #endif
     // Solve the problem with automatic adaptation
     problem.newton_solve(max_adapt);
     // Step number
     doc_info.number()=1;
     //Output solution
     problem.doc_solution(doc_info);
    } // end of no command-line arguments
   else // Validation run - read in partition from file
    {
 #ifdef OOMPH_HAS_MPI
     DocInfo mesh_doc_info;
     mesh_doc_info.set_directory("RESLT_CR_MESH");
     mesh_doc_info.number()=0;
     std::ifstream input_file;
     char filename[100];
     // Get the partition to be used from file
     const unsigned n_element=problem.mesh_pt()->nelement();
     Vector<unsigned> element_partition(n_element);
     sprintf(filename,"adaptive_cavity_2_partition.dat");
     input_file.open(filename);
     std::string input_string;
     for (unsigned e=0;e<n_element;e++)
      {
       getline(input_file,input_string,'\n');
       element_partition[e]=atoi(input_string.c_str());
      }
     // Now perform the distribution
     bool report_stats=true;
     problem.distribute(element_partition,mesh_doc_info,report_stats);
 #endif
     // Re-solve with adaptation
     problem.newton_solve(max_adapt);
     // change doc_info number
     doc_info.number()=1;
     //Output solution
     problem.doc_solution(doc_info);
 #ifdef OOMPH_HAS_MPI
     mesh_doc_info.number()=1;
     problem.mesh_pt()->doc_mesh_distribution(mesh_doc_info);
 #endif
    }
  } // end of Crouzeix Raviart elements
 // Finalise MPI
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::finalize();
 #endif
 } // end_of_main
References oomph::CommandLineArgs::Argc, e(), MergeRestartFiles::filename, oomph::DocInfo::number(), problem, oomph::DocInfo::set_directory(), Flag_definition::setup(), and oomph::Global_string_for_annotation::string().