MercuryDPM: Tutorial_ReshapeMat2Vec.cpp File Reference
Tutorial_ReshapeMat2Vec.cpp File Reference
Functions
MatrixXf M1 (3, 3)
M1<< 1, 2, 3, 4, 5, 6, 7, 8, 9;Map< RowVectorXf > v1 (M1.data(), M1.size())
cout<< "v1:"<< endl<< v1<< endl;Matrix< float, Dynamic, Dynamic, RowMajor > M2 (M1)
Map< RowVectorXf > v2 (M2.data(), M2.size())
Function Documentation
M1()
MatrixXf M1 (3 , 3)
M2()
cout<< "v1:" << endl << v1 << endl;Matrix<float, Dynamic, Dynamic, RowMajor> M2 (M1)
v1()
M1<< 1, 2, 3, 4, 5, 6, 7, 8, 9;Map<RowVectorXf> v1 (M1. data(), M1. size())
Referenced by Membrane::addEdge(), adjoint(), as_scalar_product(), basicStuff(), block(), bug890(), bug_1264(), check_auto_reshape4x4(), check_indexed_view(), check_marketio_vector(), anonymous_namespace{skew_symmetric_matrix3.cpp}::constructors(), tetgenmesh::cross(), oomph::YoungLaplaceEquations::cross_product(), diagonalmatrices(), tetgenmesh::dot(), EIGEN_DECLARE_TEST(), Eigen::symbolic::AddExpr< Arg0, Arg1 >::eval_at_compile_time_impl(), Eigen::symbolic::ProductExpr< Arg0, Arg1 >::eval_at_compile_time_impl(), Eigen::symbolic::QuotientExpr< Arg0, Arg1 >::eval_at_compile_time_impl(), anonymous_namespace{skew_symmetric_matrix3.cpp}::exponentialIdentity(), anonymous_namespace{skew_symmetric_matrix3.cpp}::exponentialRotation(), MercuryOS::getEffectiveElasticModulus(), MercuryOS::getEffectiveShearModulus(), WearableNurbsWall::getVolumeUnderSurface(), WearableNurbsWall::getVolumeUnderSurfaceX(), householder(), integer_type_tests(), mathsFunc::isEqual(), main(), mapQuaternion(), PointPointMinimizer::minimumOnObjectObject(), miscMatrices(), anonymous_namespace{skew_symmetric_matrix3.cpp}::multiplyScale(), Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvTransMv(), non_projective_only(), noncopyable(), Eigen::internal::dhs_pack< bfloat16, DataMapper, Packet8bf, StorageOrder, PanelMode, true >::operator()(), Eigen::KdBVH< Scalar_, Dim_, _Object >::VectorComparator::operator()(), Eigen::internal::Packet1cd::operator*=(), Eigen::internal::Packet2cf::operator*=(), orthomethods_3(), planes(), anonymous_namespace{skew_symmetric_matrix3.cpp}::plusMinus(), Eigen::internal::Packet2cf::pmul(), Eigen::internal::pmul< Packet1cf >(), oomph::SegregatableFSIProblem::pointwise_aitken_extrapolate(), product(), product_extra(), product_selfadjoint(), quaternion(), ref_vector(), TriangleMeshWall::refineTriangle(), replicate(), reshape4x4(), reverse(), adjoint_specific< true >::run(), adjoint_specific< false >::run(), oomph::YoungLaplaceEquations::scalar_product(), Eigen::QuaternionBase< Derived >::setFromTwoVectors(), MercuryOS::setMaterialProperties(), sparse_block(), sparse_product(), sparse_vector(), WearableTriangleMeshWall::storeDebris(), test_stl_iterators(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Through(), transform_associativity(), transformations(), transformations_computed_scaling_continuity(), transformations_no_scale(), oomph::TriangleMeshClosedCurve::TriangleMeshClosedCurve(), oomph::TriangleMeshOpenCurve::TriangleMeshOpenCurve(), oomph::TriangleMeshPolygon::TriangleMeshPolygon(), trmv(), unaligned_objects(), update_latest_fixed_point_iteration_guess_for_strain_rate(), TriangleMeshWall::updateBoundingBoxGlobal(), oomph::YoungLaplaceEquations::vector_sum(), and vectorVisitor().
v2()
Map<RowVectorXf> v2 (M2. data(), M2. size())
Referenced by adjoint(), bug890(), bug_1264(), check_auto_reshape4x4(), check_marketio_vector(), tetgenmesh::cross(), oomph::YoungLaplaceEquations::cross_product(), diagonalmatrices(), tetgenmesh::dot(), EIGEN_DECLARE_TEST(), anonymous_namespace{skew_symmetric_matrix3.cpp}::exponentialIdentity(), anonymous_namespace{skew_symmetric_matrix3.cpp}::exponentialRotation(), fixedsizeVariadicVectorConstruction2(), MercuryOS::getEffectiveElasticModulus(), MercuryOS::getEffectiveShearModulus(), householder(), integer_type_tests(), mathsFunc::isEqual(), main(), PointPointMinimizer::minimumOnObjectObject(), anonymous_namespace{skew_symmetric_matrix3.cpp}::multiplyScale(), Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvTransMv(), Eigen::internal::dhs_pack< bfloat16, DataMapper, Packet8bf, StorageOrder, PanelMode, true >::operator()(), Eigen::KdBVH< Scalar_, Dim_, _Object >::VectorComparator::operator()(), Eigen::internal::Packet1cd::operator*=(), Eigen::internal::Packet2cf::operator*=(), orthomethods_3(), planes(), anonymous_namespace{skew_symmetric_matrix3.cpp}::plusMinus(), Eigen::internal::Packet2cf::pmul(), Eigen::internal::pmul< Packet1cf >(), oomph::SegregatableFSIProblem::pointwise_aitken_extrapolate(), product_selfadjoint(), quaternion(), ref_vector(), TriangleMeshWall::refineTriangle(), reshape4x4(), adjoint_specific< true >::run(), adjoint_specific< false >::run(), oomph::YoungLaplaceEquations::scalar_product(), MercuryOS::setMaterialProperties(), smallVectors(), sparse_product(), sparse_vector(), WearableTriangleMeshWall::storeDebris(), transform_associativity(), oomph::TriangleMeshClosedCurve::TriangleMeshClosedCurve(), oomph::TriangleMeshOpenCurve::TriangleMeshOpenCurve(), oomph::TriangleMeshPolygon::TriangleMeshPolygon(), triangular_square(), unaligned_objects(), update_latest_fixed_point_iteration_guess_for_strain_rate(), TriangleMeshWall::updateBoundingBoxGlobal(), oomph::YoungLaplaceEquations::vector_sum(), and vectorVisitor().