MercuryDPM: CalibrationTest.cpp File Reference
CalibrationTest.cpp File Reference
#include <Logger.h>
#include <Math/Helpers.h>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
 {
     //read in params
     // material type
     std::string type = helpers::readFromCommandLine(argc,argv,"-speciesType",std::string("X"));
     // type of fit function from in- to output
     std::string fit = helpers::readFromCommandLine(argc,argv,"-fit",std::string("X"));
     // the string that is written into the output file
     std::string out;
     // the name of the output file
     std::string outFile = "CalibrationTest_" + type;
     // case specific translation from in- to output
     if (fit == "identity1") {
         // 1D input, 1D output: f(x)=x
         // read param0
         std::string string0 = helpers::readFromCommandLine(argc, argv, "-param0", std::string("0"));
         double param0 = std::stof(string0);
         // prepare output
         out = std::to_string(param0);
         outFile += "_" + string0 ;
     } else if (fit == "identity2") {
         // 2D input, 2D output: f(x)=x
         // read param0
         std::string string0 = helpers::readFromCommandLine(argc, argv, "-param0", std::string("0"));
         double param0 = std::stof(string0);
         std::string string1 = helpers::readFromCommandLine(argc, argv, "-param1", std::string("0"));
         double param1 = std::stof(string1);
         // prepare output
         out = std::to_string(param0) + ' ' + std::to_string(param1);
         outFile += "_" + string0 + "_" + string1;
     } else if (fit == "calibration43") {
         // 4D input, 3D output
         // read param0
         std::string string0 = helpers::readFromCommandLine(argc, argv, "-restitutionCoefficient", std::string("0"));
         double restitutionCoefficient = std::stof(string0);
         std::string string1 = helpers::readFromCommandLine(argc, argv, "-slidingFriction", std::string("0"));
         double slidingFriction = std::stof(string1);
         std::string string2 = helpers::readFromCommandLine(argc, argv, "-rollingFriction", std::string("0"));
         double rollingFriction = std::stof(string2);
         std::string string3 = helpers::readFromCommandLine(argc, argv, "-bondNumber", std::string("0"));
         double bondNumber = std::stof(string3);
         // fit
         //double angleOfRepose = slidingFriction;
         //double drum = slidingFriction + rollingFriction;
         //double ffc = 1.0/(slidingFriction+rollingFriction+bondNumber);
         double ffc = 1.0/bondNumber;
         double angleOfRepose = slidingFriction;
         double drum = rollingFriction;
         // prepare output
         out = std::to_string(ffc) + ' ' + std::to_string(angleOfRepose) + ' ' + std::to_string(drum);
         outFile += "_" + string0 + "_" + string1 + "_" + string2 + "_" + string3;
     } else if (fit == "calibration44") {
         // 4D input, 4D output
         // read param0
         std::string string0 = helpers::readFromCommandLine(argc, argv, "-restitutionCoefficient", std::string("0"));
         double restitutionCoefficient = std::stof(string0);
         std::string string1 = helpers::readFromCommandLine(argc, argv, "-slidingFriction", std::string("0"));
         double slidingFriction = std::stof(string1);
         std::string string2 = helpers::readFromCommandLine(argc, argv, "-rollingFriction", std::string("0"));
         double rollingFriction = std::stof(string2);
         std::string string3 = helpers::readFromCommandLine(argc, argv, "-bondNumber", std::string("0"));
         double bondNumber = std::stof(string3);
         // fit
         double dummy = restitutionCoefficient;
         double ffc = 1.0/bondNumber;
         double angleOfRepose = slidingFriction;
         double drum = rollingFriction;
         // prepare output
         out = std::to_string(dummy) + ' ' + std::to_string(ffc) + ' ' + std::to_string(angleOfRepose) + ' ' + std::to_string(drum);
         outFile += "_" + string0 + "_" + string1 + "_" + string2 + "_" + string3;
     } else {
         logger(ERROR,"fit function % unknown", fit);
     }
     //write output
     helpers::writeToFile(outFile + ".txt", out);
     logger(INFO,"Output to %: %",outFile, out);
     return 0;
 }
References ERROR, INFO, logger, out(), helpers::readFromCommandLine(), oomph::Global_string_for_annotation::string(), oomph::StringConversion::to_string(), compute_granudrum_aor::type, and helpers::writeToFile().