MercuryDPM: Eigen::internal::gebp_kernel< float, std::complex< float >, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs > Struct Template Reference
Eigen::internal::gebp_kernel< float, std::complex< float >, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs > Struct Template Reference
#include <MatrixProduct.h>
Public Types
typedef Packet4f Packet
typedef Packet2cf Packetc
typedef Packet4f RhsPacket
Public Member Functions
void operator() (const DataMapper &res, const float *blockA, const std::complex< float > *blockB, Index rows, Index depth, Index cols, std::complex< float > alpha, Index strideA=-1, Index strideB=-1, Index offsetA=0, Index offsetB=0)
Member Typedef Documentation
Packet
template<typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef Packet4f Eigen::internal::gebp_kernel< float, std::complex< float >, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::Packet
Packetc
template<typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef Packet2cf Eigen::internal::gebp_kernel< float, std::complex< float >, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::Packetc
RhsPacket
template<typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef Packet4f Eigen::internal::gebp_kernel< float, std::complex< float >, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::RhsPacket
Member Function Documentation
operator()()
template<typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> void Eigen::internal::gebp_kernel< float, std::complex< float >, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator() (const DataMapper & res, const float * blockA, const std::complex< float > * blockB, Index rows, Index depth, Index cols, std::complex< float > alpha, Index strideA = -1, Index strideB = -1, Index offsetA = 0, Index offsetB = 0)
{
   const Index accRows = quad_traits<float>::rows;
   const Index accCols = quad_traits<float>::size;
   static void (*gemm_function)(const DataMapper&, const float*, const std::complex<float>*, Index, Index, Index,
                                std::complex<float>, Index, Index, Index, Index) =
 #ifdef EIGEN_MATRIX_PRODUCT_MMA_ALTIVEC_H
       (supportsMMA()) ? &Eigen::internal::gemm_complexMMA<float, std::complex<float>, std::complex<float>, float,
                                                           Packet, Packetc, RhsPacket, DataMapper, accRows, accCols,
                                                           ConjugateLhs, ConjugateRhs, true, false>
                       :
 #endif
                       &Eigen::internal::gemm_complex<float, std::complex<float>, std::complex<float>, float, Packet,
                                                      Packetc, RhsPacket, DataMapper, accRows, accCols, ConjugateLhs,
                                                      ConjugateRhs, true, false>;
   gemm_function(res, blockA, blockB, rows, depth, cols, alpha, strideA, strideB, offsetA, offsetB);
 }
References alpha, cols, Eigen::internal::gemm_complex(), Eigen::internal::gemm_complexMMA(), res, rows, and Eigen::internal::supportsMMA().
The documentation for this struct was generated from the following file:
MatrixProduct.h