MercuryDPM: oomph::TetMeshFacet Class Reference
oomph::TetMeshFacet Class Reference
#include <tet_mesh.h>
Public Member Functions
TetMeshFacet (const unsigned &nvertex)
Constructor: Specify number of vertices.
unsigned nvertex () const
Number of vertices.
TetMeshVertex * vertex_pt (const unsigned &j) const
Pointer to j-th vertex (const)
void set_vertex_pt (const unsigned &j, TetMeshVertex *vertex_pt)
unsigned one_based_boundary_id () const
Constant access to (one-based!) boundary IDs this facet lives on.
void set_one_based_boundary_id (const unsigned &one_based_id)
void set_one_based_adjacent_region_id (const unsigned &one_based_id)
std::set< unsigned > one_based_adjacent_region_id () const
Return set of (one-based!) region IDs this facet is adjacent to.
bool facet_is_embedded_in_a_specified_region ()
Boolean indicating that facet is embedded in a specified region.
void set_one_based_region_that_facet_is_embedded_in (const unsigned &one_based_region_id)
Facet is to be embedded in specified one-based region.
unsigned one_based_region_that_facet_is_embedded_in ()
void output (std::ostream &outfile) const
Output.
Private Attributes
Vector< TetMeshVertex * > Vertex_pt
Pointer to vertices.
unsigned One_based_boundary_id
(One-based!) boundary IDs this facet lives on
std::set< unsigned > One_based_adjacent_region_id
unsigned One_based_region_id_that_facet_is_embedded_in
Detailed Description
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Facet for Tet mesh generation. Can lie on boundary (identified via one-based enumeration!) and can have GeomObject associated with those boundaries.
Constructor & Destructor Documentation
TetMeshFacet()
oomph::TetMeshFacet::TetMeshFacet (const unsigned & nvertex) inline
Constructor: Specify number of vertices.
       : One_based_boundary_id(0), // Initialision implies not on any boundary
         One_based_region_id_that_facet_is_embedded_in(
           0) // Initialisation implies
     // not embedded in any region
     {
       Vertex_pt.resize(nvertex, 0);
     }
References nvertex(), and Vertex_pt.
Member Function Documentation
facet_is_embedded_in_a_specified_region()
bool oomph::TetMeshFacet::facet_is_embedded_in_a_specified_region () inline
Boolean indicating that facet is embedded in a specified region.
     {
       return (One_based_region_id_that_facet_is_embedded_in != 0);
     }
References One_based_region_id_that_facet_is_embedded_in.
Referenced by oomph::GmshTetScaffoldMesh::write_geo_file().
nvertex()
unsigned oomph::TetMeshFacet::nvertex () const inline
Number of vertices.
     {
       return Vertex_pt.size();
     }
References Vertex_pt.
Referenced by oomph::TetMeshBase::setup_boundary_coordinates(), oomph::TetMeshBase::snap_nodes_onto_geometric_objects(), TetMeshFacet(), and oomph::GmshTetScaffoldMesh::write_geo_file().
one_based_adjacent_region_id()
std::set<unsigned> oomph::TetMeshFacet::one_based_adjacent_region_id () const inline
Return set of (one-based!) region IDs this facet is adjacent to.
     {
       return One_based_adjacent_region_id;
     }
References One_based_adjacent_region_id.
Referenced by oomph::GmshTetScaffoldMesh::write_geo_file().
one_based_boundary_id()
unsigned oomph::TetMeshFacet::one_based_boundary_id () const inline
Constant access to (one-based!) boundary IDs this facet lives on.
     {
       return One_based_boundary_id;
     }
References One_based_boundary_id.
one_based_region_that_facet_is_embedded_in()
unsigned oomph::TetMeshFacet::one_based_region_that_facet_is_embedded_in () inline
Which (one-based) region is facet embedded in (if zero, it's not embedded in any region)
     {
       return One_based_region_id_that_facet_is_embedded_in;
     }
References One_based_region_id_that_facet_is_embedded_in.
Referenced by oomph::GmshTetScaffoldMesh::write_geo_file().
output()
void oomph::TetMeshFacet::output (std::ostream & outfile) const inline
Output.
     {
       unsigned n = Vertex_pt.size();
       outfile << "ZONE I=" << n + 1 << std::endl;
       for (unsigned j = 0; j < n; j++)
       {
         outfile << Vertex_pt[j]->x(0) << " " << Vertex_pt[j]->x(1) << " "
                 << Vertex_pt[j]->x(2) << " " << One_based_boundary_id
                 << std::endl;
       }
       outfile << Vertex_pt[0]->x(0) << " " << Vertex_pt[0]->x(1) << " "
               << Vertex_pt[0]->x(2) << " " << One_based_boundary_id
               << std::endl;
     }
References j, n, One_based_boundary_id, and Vertex_pt.
set_one_based_adjacent_region_id()
void oomph::TetMeshFacet::set_one_based_adjacent_region_id (const unsigned & one_based_id) inline
Set (one-based!) region ID this facet is adjacent to. Specification of zero argument is harmless as it indicates that that facet is not adjacent to any region.
     {
       One_based_adjacent_region_id.insert(one_based_id);
     }
References One_based_adjacent_region_id.
set_one_based_boundary_id()
void oomph::TetMeshFacet::set_one_based_boundary_id (const unsigned & one_based_id) inline
Set (one-based!) boundary IDs this facet lives on. Passed to any existing vertices and to any future ones
     {
       One_based_boundary_id = one_based_id;
       unsigned nv = Vertex_pt.size();
       for (unsigned j = 0; j < nv; j++)
       {
         TetMeshVertex* v_pt = Vertex_pt[j];
         if (v_pt != 0)
         {
           v_pt->set_one_based_boundary_id(one_based_id);
         }
       }
     }
References j, One_based_boundary_id, oomph::TetMeshVertex::set_one_based_boundary_id(), and Vertex_pt.
set_one_based_region_that_facet_is_embedded_in()
void oomph::TetMeshFacet::set_one_based_region_that_facet_is_embedded_in (const unsigned & one_based_region_id) inline
Facet is to be embedded in specified one-based region.
     {
       One_based_region_id_that_facet_is_embedded_in = one_based_region_id;
     }
References One_based_region_id_that_facet_is_embedded_in.
set_vertex_pt()
void oomph::TetMeshFacet::set_vertex_pt (const unsigned & j, TetMeshVertex * vertex_pt) inline
Set pointer to j-th vertex and pass one-based boundary id that may already have been set for this facet.
     {
       Vertex_pt[j] = vertex_pt;
       // If not set yet, this is harmless since it simply over-writes
       // the dummy value in vertex
       TetMeshVertex* v_pt = Vertex_pt[j];
       if (v_pt != 0)
       {
         v_pt->set_one_based_boundary_id(One_based_boundary_id);
       }
     }
References j, One_based_boundary_id, oomph::TetMeshVertex::set_one_based_boundary_id(), vertex_pt(), and Vertex_pt.
Referenced by oomph::DiskWithTorusAroundEdgeTetMeshFacetedSurface::DiskWithTorusAroundEdgeTetMeshFacetedSurface().
vertex_pt()
TetMeshVertex* oomph::TetMeshFacet::vertex_pt (const unsigned & j) const inline
Pointer to j-th vertex (const)
     {
       return Vertex_pt[j];
     }
References j, and Vertex_pt.
Referenced by set_vertex_pt(), oomph::TetMeshBase::setup_boundary_coordinates(), oomph::TetMeshBase::snap_nodes_onto_geometric_objects(), and oomph::GmshTetScaffoldMesh::write_geo_file().
Member Data Documentation
One_based_adjacent_region_id
std::set<unsigned> oomph::TetMeshFacet::One_based_adjacent_region_id private
Set of one-based adjacent region ids; no adjacent region if it's zero.
Referenced by one_based_adjacent_region_id(), and set_one_based_adjacent_region_id().
One_based_boundary_id
unsigned oomph::TetMeshFacet::One_based_boundary_id private
(One-based!) boundary IDs this facet lives on
Referenced by one_based_boundary_id(), output(), set_one_based_boundary_id(), and set_vertex_pt().
One_based_region_id_that_facet_is_embedded_in
unsigned oomph::TetMeshFacet::One_based_region_id_that_facet_is_embedded_in private
Facet is to be embedded in specified one-based region. Defaults to zero, indicating that its not embedded.
Referenced by facet_is_embedded_in_a_specified_region(), one_based_region_that_facet_is_embedded_in(), and set_one_based_region_that_facet_is_embedded_in().
Vertex_pt
Vector<TetMeshVertex*> oomph::TetMeshFacet::Vertex_pt private
Pointer to vertices.
Referenced by nvertex(), output(), set_one_based_boundary_id(), set_vertex_pt(), TetMeshFacet(), and vertex_pt().
The documentation for this class was generated from the following file:
tet_mesh.h