MercuryDPM: oomph::QElement< 2, NNODE_1D > Class Template Reference
oomph::QElement< 2, NNODE_1D > Class Template Reference
General QElement class specialised to two spatial dimensions.
#include <Qelements.h>
Public Member Functions
QElement ()
Constructor.
QElement (const QElement &)=delete
Broken copy constructor.
void shape (const Vector< double > &s, Shape &psi) const
Broken assignment operator.
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Derivatives of shape functions for specific QElement<2,..>
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double s_min () const
Min. value of local coordinate.
double s_max () const
Max. value of local coordinate.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
Get local coordinates of node j in the element; vector sets its own size.
void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
Get the local fraction of node j in the element.
double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
Node * get_node_at_local_coordinate (const Vector< double > &s) const
Get the node at the specified local coordinate.
unsigned nnode_1d () const
Number of nodes along each element edge.
unsigned nplot_points_paraview (const unsigned &nplot) const
unsigned nsub_elements_paraview (const unsigned &nplot) const
void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
void output (std::ostream &outfile)
Output.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at n_plot points.
void output (FILE *file_pt)
C-style output.
void output (FILE *file_pt, const unsigned &n_plot)
C_style output at n_plot points.
void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &use_equally_spaced_interior_sample_points=false) const
std::string tecplot_zone_string (const unsigned &nplot) const
unsigned nplot_points (const unsigned &nplot) const
unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::QuadElementBase
QuadElementBase ()
Constructor. Empty.
Public Member Functions inherited from oomph::QElementBase
QElementBase ()
Constructor: Initialise pointers to macro element reference coords.
QElementBase (const QElementBase &)=delete
Broken copy constructor.
virtual ~QElementBase ()
Broken assignment operator.
bool local_coord_is_valid (const Vector< double > &s)
Check whether the local coordinate are valid or not.
void move_local_coord_back_into_element (Vector< double > &s) const
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
double & s_macro_ll (const unsigned &i)
double & s_macro_ur (const unsigned &i)
double s_macro_ll (const unsigned &i) const
double s_macro_ur (const unsigned &i) const
void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
unsigned nnode_on_face () const
ElementGeometry::ElementGeometry element_geometry () const
It's a Q element!
Public Member Functions inherited from oomph::QElementGeometricBase
QElementGeometricBase ()
Empty default constructor.
QElementGeometricBase (const QElementGeometricBase &)=delete
Broken copy constructor.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Static Private Attributes
static Gauss< 2, NNODE_1D > Default_integration_scheme
Assign the spatial integration scheme.
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<unsigned NNODE_1D>
class oomph::QElement< 2, NNODE_1D >
General QElement class specialised to two spatial dimensions.
Constructor & Destructor Documentation
QElement() [1/2]
template<unsigned NNODE_1D> oomph::QElement< 2, NNODE_1D >::QElement () inline
Constructor.
     {
       // There are NNODE_1D*NNODE_1D nodes in this element
       this->set_n_node(NNODE_1D * NNODE_1D);
       // Set the dimensions of the element and the nodes, by default, both 2D
       set_dimension(2);
       // Assign default (full) spatial integration scheme
       set_integration_scheme(&Default_integration_scheme);
     }
QElement() [2/2]
template<unsigned NNODE_1D> oomph::QElement< 2, NNODE_1D >::QElement (const QElement< 2, NNODE_1D > &) delete
Broken copy constructor.
Member Function Documentation
bulk_coordinate_derivatives_fct_pt()
template<unsigned NNODE_1D> BulkCoordinateDerivativesFctPt oomph::QElement< 2, NNODE_1D >::bulk_coordinate_derivatives_fct_pt (const int & face_index) const inline virtual
Get a pointer to the derivative of the mapping from face to bulk coordinates.
Reimplemented from oomph::FiniteElement.
     {
       if (face_index == 1)
       {
         return &QElement2BulkCoordinateDerivatives::faces0;
       }
       else if (face_index == -1)
       {
         return &QElement2BulkCoordinateDerivatives::faces0;
       }
       else if (face_index == -2)
       {
         return &QElement2BulkCoordinateDerivatives::faces1;
       }
       else if (face_index == 2)
       {
         return &QElement2BulkCoordinateDerivatives::faces1;
       }
       else
       {
         std::string err = "Face index should be in {-1, +1}.";
         throw OomphLibError(
           err, OOMPH_EXCEPTION_LOCATION, OOMPH_CURRENT_FUNCTION);
       }
     }
References oomph::QElement2BulkCoordinateDerivatives::faces0(), oomph::QElement2BulkCoordinateDerivatives::faces1(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
d2shape_local()
template<unsigned NNODE_1D> void oomph::QElement< 2, NNODE_1D >::d2shape_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const virtual
Compute the geometric shape functions, derivatives and second derivatives w.r.t. local coordinates at local coordinate s d2psids(i,0) = \(\partial^2 \psi_j / \partial s_0^2 \) d2psids(i,1) = \(\partial^2 \psi_j / \partial s_1^2 \) d2psids(i,2) = \(\partial^2 \psi_j / \partial s_0 \partial s_1 \)
Second derivatives of shape functions for specific QElement<2,..>: d2psids(i,0) = \(\partial^2 \psi_j / \partial s_0^2 \) d2psids(i,1) = \(\partial^2 \psi_j / \partial s_1^2 \) d2psids(i,2) = \(\partial^2 \psi_j / \partial s_0 \partial s_1 \)
Reimplemented from oomph::FiniteElement.
   {
     // Local storage
     double Psi[2][NNODE_1D];
     double DPsi[2][NNODE_1D];
     double D2Psi[2][NNODE_1D];
     // Index for the assembly process
     unsigned index = 0;
     // Call the shape functions and derivatives
     OneDimLagrange::shape<NNODE_1D>(s[0], Psi[0]);
     OneDimLagrange::shape<NNODE_1D>(s[1], Psi[1]);
     OneDimLagrange::dshape<NNODE_1D>(s[0], DPsi[0]);
     OneDimLagrange::dshape<NNODE_1D>(s[1], DPsi[1]);
     OneDimLagrange::d2shape<NNODE_1D>(s[0], D2Psi[0]);
     OneDimLagrange::d2shape<NNODE_1D>(s[1], D2Psi[1]);
     // Loop over shape functions in element
     for (unsigned i = 0; i < NNODE_1D; i++)
     {
       for (unsigned j = 0; j < NNODE_1D; j++)
       {
         // Assign the values
         psi[index] = Psi[1][i] * Psi[0][j];
         // First derivatives
         dpsids(index, 0) = Psi[1][i] * DPsi[0][j];
         dpsids(index, 1) = DPsi[1][i] * Psi[0][j];
         // Second derivatives
         // N.B. index 2 is the mixed derivative
         d2psids(index, 0) = Psi[1][i] * D2Psi[0][j];
         d2psids(index, 1) = D2Psi[1][i] * Psi[0][j];
         d2psids(index, 2) = DPsi[1][i] * DPsi[0][j];
         // Increment the index
         ++index;
       }
     }
   }
References i, j, and s.
dshape_local()
template<unsigned NNODE_1D> void oomph::QElement< 2, NNODE_1D >::dshape_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const virtual
Derivatives of shape functions for specific QElement<2,..>
Compute the geometric shape functions and derivatives w.r.t. local coordinates at local coordinate s
Reimplemented from oomph::FiniteElement.
   {
     // Local storage
     double Psi[2][NNODE_1D];
     double DPsi[2][NNODE_1D];
     unsigned index = 0;
     // Call the shape functions and derivatives
     OneDimLagrange::shape<NNODE_1D>(s[0], Psi[0]);
     OneDimLagrange::shape<NNODE_1D>(s[1], Psi[1]);
     OneDimLagrange::dshape<NNODE_1D>(s[0], DPsi[0]);
     OneDimLagrange::dshape<NNODE_1D>(s[1], DPsi[1]);
     // Loop over shape functions in element
     for (unsigned i = 0; i < NNODE_1D; i++)
     {
       for (unsigned j = 0; j < NNODE_1D; j++)
       {
         // Assign the values
         dpsids(index, 0) = Psi[1][i] * DPsi[0][j];
         dpsids(index, 1) = DPsi[1][i] * Psi[0][j];
         psi[index] = Psi[1][i] * Psi[0][j];
         // Increment the index
         ++index;
       }
     }
   }
References i, j, and s.
face_outer_unit_normal_sign()
template<unsigned NNODE_1D> int oomph::QElement< 2, NNODE_1D >::face_outer_unit_normal_sign (const int & face_index) const inline virtual
Get the sign of the outer unit normal on the face given by face_index.
Reimplemented from oomph::FiniteElement.
     {
       if (face_index < 0)
       {
         return 1;
       }
       else if (face_index > 0)
       {
         return -1;
       }
       else
       {
         std::string err = "Face index should be one of {-1, +1, -2, +2}.";
         throw OomphLibError(
           err, OOMPH_EXCEPTION_LOCATION, OOMPH_CURRENT_FUNCTION);
       }
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
face_to_bulk_coordinate_fct_pt()
template<unsigned NNODE_1D> CoordinateMappingFctPt oomph::QElement< 2, NNODE_1D >::face_to_bulk_coordinate_fct_pt (const int & face_index) const inline virtual
Get a pointer to the function mapping face coordinates to bulk coordinates
Reimplemented from oomph::FiniteElement.
     {
       if (face_index == 1)
       {
         return &QElement2FaceToBulkCoordinates::face2;
       }
       else if (face_index == -1)
       {
         return &QElement2FaceToBulkCoordinates::face0;
       }
       else if (face_index == -2)
       {
         return &QElement2FaceToBulkCoordinates::face1;
       }
       else if (face_index == 2)
       {
         return &QElement2FaceToBulkCoordinates::face3;
       }
       else
       {
         std::string err = "Face index should be in {-1, +1}.";
         throw OomphLibError(
           err, OOMPH_EXCEPTION_LOCATION, OOMPH_CURRENT_FUNCTION);
       }
     }
References oomph::QElement2FaceToBulkCoordinates::face0(), oomph::QElement2FaceToBulkCoordinates::face1(), oomph::QElement2FaceToBulkCoordinates::face2(), oomph::QElement2FaceToBulkCoordinates::face3(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
get_bulk_node_number()
template<unsigned NNODE_1D> unsigned oomph::QElement< 2, NNODE_1D >::get_bulk_node_number (const int & face_index, const unsigned & i) const inline virtual
Get the number of the ith node on face face_index (in the bulk node vector).
Reimplemented from oomph::FiniteElement.
     {
       face_node_number_error_check(i);
       const unsigned nn1d = nnode_1d();
       if (face_index == -1)
       {
         return i * nn1d;
       }
       else if (face_index == +1)
       {
         return nn1d * i + nn1d - 1;
       }
       else if (face_index == -2)
       {
         return i;
       }
       else if (face_index == +2)
       {
         return nn1d * (nn1d - 1) + i;
       }
       else
       {
         std::string err = "Face index should be in {-1, +1, -2, +2}.";
         throw OomphLibError(
           err, OOMPH_EXCEPTION_LOCATION, OOMPH_CURRENT_FUNCTION);
       }
     }
References i, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
get_node_at_local_coordinate()
template<unsigned NNODE_1D> Node * oomph::QElement< 2, NNODE_1D >::get_node_at_local_coordinate (const Vector< double > & s) const virtual
Get the node at the specified local coordinate.
Return the node at the specified local coordinate.
Reimplemented from oomph::FiniteElement.
   {
     // Load the tolerance into a local variable
     double tol = FiniteElement::Node_location_tolerance;
     // There are two possible indices.
     Vector<int> index(2);
     // Loop over the coordinates and determine the indices
     for (unsigned i = 0; i < 2; i++)
     {
       // If we are at the lower limit, the index is zero
       if (std::fabs(s[i] + 1.0) < tol)
       {
         index[i] = 0;
       }
       // If we are at the upper limit, the index is the number of nodes minus 1
       else if (std::fabs(s[i] - 1.0) < tol)
       {
         index[i] = NNODE_1D - 1;
       }
       // Otherwise, we have to calculate the index in general
       else
       {
         // For uniformly spaced nodes the node number would be
         double float_index = 0.5 * (1.0 + s[i]) * (NNODE_1D - 1);
         // Convert to an integer by taking the floor (rounding down)
         index[i] = static_cast<int>(std::floor(float_index));
         // What is the excess. This should be safe because the
         // we have rounded down
         double excess = float_index - index[i];
         // If the excess is bigger than our tolerance there is no node,
         // return null
         // Note that we test at both lower and upper ends.
         if ((excess > tol) && ((1.0 - excess) > tol))
         {
           return 0;
         }
         // If we are at the upper end (i.e. the system has actually rounded up)
         // we need to add one to the index
         if ((1.0 - excess) <= tol)
         {
           index[i] += 1;
         }
       }
     }
     // If we've got here we have a node, so let's return a pointer to it
     return node_pt(index[0] + NNODE_1D * index[1]);
   }
References boost::multiprecision::fabs(), Eigen::bfloat16_impl::floor(), i, oomph::FiniteElement::Node_location_tolerance, and s.
get_s_plot()
template<unsigned NNODE_1D> void oomph::QElement< 2, NNODE_1D >::get_s_plot (const unsigned & i, const unsigned & nplot, Vector< double > & s, const bool & use_equally_spaced_interior_sample_points = false) const inline virtual
Get cector of local coordinates of plot point i (when plotting nplot points in each "coordinate direction).
Reimplemented from oomph::FiniteElement.
     {
       if (nplot > 1)
       {
         unsigned i0 = i % nplot;
         unsigned i1 = (i - i0) / nplot;
         s[0] = -1.0 + 2.0 * double(i0) / double(nplot - 1);
         s[1] = -1.0 + 2.0 * double(i1) / double(nplot - 1);
         if (use_equally_spaced_interior_sample_points)
         {
           double range = 2.0;
           double dx_new = range / double(nplot);
           double range_new = double(nplot - 1) * dx_new;
           s[0] = -1.0 + 0.5 * dx_new + range_new * (1.0 + s[0]) / range;
           s[1] = -1.0 + 0.5 * dx_new + range_new * (1.0 + s[1]) / range;
         }
       }
       else
       {
         s[0] = 0.0;
         s[1] = 0.0;
       }
     }
References i, and s.
Referenced by oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::output(), oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::output(), and oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::output().
invert_jacobian_mapping()
template<unsigned NNODE_1D> double oomph::QElement< 2, NNODE_1D >::invert_jacobian_mapping (const DenseMatrix< double > & jacobian, DenseMatrix< double > & inverse_jacobian) const inline virtual
Overload the template-free interface for the calculation of inverse jacobian matrix. This is a two-dimensional element, so use the two-d version.
Reimplemented from oomph::FiniteElement.
     {
       return FiniteElement::invert_jacobian<2>(jacobian, inverse_jacobian);
     }
local_coordinate_of_node()
template<unsigned NNODE_1D> void oomph::QElement< 2, NNODE_1D >::local_coordinate_of_node (const unsigned & j, Vector< double > & s) const inline virtual
Get local coordinates of node j in the element; vector sets its own size.
Reimplemented from oomph::FiniteElement.
     {
       s.resize(2);
       unsigned j0 = j % NNODE_1D;
       unsigned j1 = j / NNODE_1D;
       const double S_min = this->s_min();
       const double S_range = this->s_max() - S_min;
       s[0] = S_min + double(j0) / double(NNODE_1D - 1) * S_range;
       s[1] = S_min + double(j1) / double(NNODE_1D - 1) * S_range;
     }
References j, and s.
local_fraction_of_node()
template<unsigned NNODE_1D> void oomph::QElement< 2, NNODE_1D >::local_fraction_of_node (const unsigned & j, Vector< double > & s_fraction) inline virtual
Get the local fraction of node j in the element.
Reimplemented from oomph::FiniteElement.
     {
       s_fraction.resize(2);
       unsigned j0 = j % NNODE_1D;
       unsigned j1 = j / NNODE_1D;
       s_fraction[0] = double(j0) / double(NNODE_1D - 1);
       s_fraction[1] = double(j1) / double(NNODE_1D - 1);
     }
References j.
local_one_d_fraction_of_node()
template<unsigned NNODE_1D> double oomph::QElement< 2, NNODE_1D >::local_one_d_fraction_of_node (const unsigned & n1d, const unsigned & i) inline virtual
This function returns the local fraction of ant nodes in the n-th positoin in a one dimensional expansion along the i-th local coordinate
Reimplemented from oomph::FiniteElement.
     {
       // It's just the value of the node divided by the number of 1-D nodes
       return double(n1d) / double(NNODE_1D - 1);
     }
nnode_1d()
template<unsigned NNODE_1D> unsigned oomph::QElement< 2, NNODE_1D >::nnode_1d () const inline virtual
Number of nodes along each element edge.
Reimplemented from oomph::FiniteElement.
     {
       return NNODE_1D;
     }
nplot_points()
template<unsigned NNODE_1D> unsigned oomph::QElement< 2, NNODE_1D >::nplot_points (const unsigned & nplot) const inline virtual
Return total number of plot points (when plotting nplot points in each "coordinate direction)
Reimplemented from oomph::FiniteElement.
     {
       unsigned DIM = 2;
       unsigned np = 1;
       for (unsigned i = 0; i < DIM; i++)
       {
         np *= nplot;
       }
       return np;
     };
References DIM, and i.
Referenced by oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::output(), oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::output(), and oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::output().
nplot_points_paraview()
template<unsigned NNODE_1D> unsigned oomph::QElement< 2, NNODE_1D >::nplot_points_paraview (const unsigned & nplot) const inline virtual
Return the number of actual plot points for paraview plot with parameter nplot.
Reimplemented from oomph::FiniteElement.
     {
       return nplot * nplot;
     }
nsub_elements_paraview()
template<unsigned NNODE_1D> unsigned oomph::QElement< 2, NNODE_1D >::nsub_elements_paraview (const unsigned & nplot) const inline virtual
Return the number of local sub-elements for paraview plot with parameter nplot.
Reimplemented from oomph::FiniteElement.
     {
       return (nplot - 1) * (nplot - 1);
     }
nvertex_node()
template<unsigned NNODE_1D> unsigned oomph::QElement< 2, NNODE_1D >::nvertex_node () const inline virtual
Number of vertex nodes in the element.
Implements oomph::QuadElementBase.
Reimplemented in oomph::RefineableQYoungLaplaceElement< NNODE_1D >, oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >, oomph::RefineableQSphericalAdvectionDiffusionElement< 3 >, and oomph::RefineableQAxisymAdvectionDiffusionElement< 3 >.
     {
       return 4;
     }
Referenced by oomph::RefineableQAxisymAdvectionDiffusionElement< NNODE_1D >::nvertex_node(), oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >::nvertex_node(), and oomph::RefineableQYoungLaplaceElement< NNODE_1D >::nvertex_node().
output() [1/4]
template<unsigned NNODE_1D> void oomph::QElement< 2, NNODE_1D >::output (FILE * file_pt) virtual
C-style output.
C-style output function for QElement<2,NNODE_1D>
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >, oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::SolidQElement< 2, NNODE_1D >, and oomph::QAxisymAdvectionDiffusionElement< 3 >.
   {
     output(file_pt, NNODE_1D);
   }
References oomph::output().
output() [2/4]
template<unsigned NNODE_1D> void oomph::QElement< 2, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) virtual
C_style output at n_plot points.
C-style output function for n_plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >, oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::SolidQElement< 2, NNODE_1D >, and oomph::QAxisymAdvectionDiffusionElement< 3 >.
   {
     // Local variables
     Vector<double> s(2);
     // Find the dimension of the nodes
     unsigned n_dim = this->nodal_dimension();
     // Tecplot header info
     // outfile << "ZONE I=" << n_plot << ", J=" << n_plot << std::endl;
     fprintf(file_pt, "ZONE I=%i, J=%i\n", n_plot, n_plot);
     // Loop over element nodes
     for (unsigned l2 = 0; l2 < n_plot; l2++)
     {
       s[1] = -1.0 + l2 * 2.0 / (n_plot - 1);
       for (unsigned l1 = 0; l1 < n_plot; l1++)
       {
         s[0] = -1.0 + l1 * 2.0 / (n_plot - 1);
         // Output the coordinates
         for (unsigned i = 0; i < n_dim; i++)
         {
           // outfile << interpolated_x(s,i) << " " ;
           fprintf(file_pt, "%g ", interpolated_x(s, i));
         }
         // outfile << std::endl;
         fprintf(file_pt, "\n");
       }
     }
     // outfile << std::endl;
     fprintf(file_pt, "\n");
   }
References i, and s.
output() [3/4]
template<unsigned NNODE_1D> void oomph::QElement< 2, NNODE_1D >::output (std::ostream & outfile) virtual
Output.
The output function for QElement<2,NNODE_1D>
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QYoungLaplaceElement< NNODE_1D >, oomph::QTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >, oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::SolidQElement< 2, NNODE_1D >, and oomph::QAxisymAdvectionDiffusionElement< 3 >.
   {
     output(outfile, NNODE_1D);
   }
References oomph::output().
output() [4/4]
template<unsigned NNODE_1D> void oomph::QElement< 2, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) virtual
Output at n_plot points.
The output function for n_plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QYoungLaplaceElement< NNODE_1D >, oomph::QTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >, oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::SolidQElement< 2, NNODE_1D >, and oomph::QAxisymAdvectionDiffusionElement< 3 >.
   {
     // Local variables
     Vector<double> s(2);
     // Tecplot header info
     outfile << "ZONE I=" << n_plot << ", J=" << n_plot << std::endl;
     // Find the dimension of the nodes
     unsigned n_dim = this->nodal_dimension();
     // Loop over plot points
     for (unsigned l2 = 0; l2 < n_plot; l2++)
     {
       s[1] = -1.0 + l2 * 2.0 / (n_plot - 1);
       for (unsigned l1 = 0; l1 < n_plot; l1++)
       {
         s[0] = -1.0 + l1 * 2.0 / (n_plot - 1);
         // Output the coordinates
         for (unsigned i = 0; i < n_dim; i++)
         {
           outfile << interpolated_x(s, i) << " ";
         }
         outfile << std::endl;
       }
     }
     outfile << std::endl;
   }
References i, and s.
s_max()
template<unsigned NNODE_1D> double oomph::QElement< 2, NNODE_1D >::s_max () const inline virtual
Max. value of local coordinate.
Reimplemented from oomph::FiniteElement.
     {
       return 1.0;
     }
s_min()
template<unsigned NNODE_1D> double oomph::QElement< 2, NNODE_1D >::s_min () const inline virtual
Min. value of local coordinate.
Reimplemented from oomph::FiniteElement.
     {
       return -1.0;
     }
shape()
template<unsigned NNODE_1D> void oomph::QElement< 2, NNODE_1D >::shape (const Vector< double > & s, Shape & psi) const virtual
Broken assignment operator.
Calculate the geometric shape functions at local coordinate s
Shape function for specific QElement<2,..>
Implements oomph::FiniteElement.
   {
     // Local storage
     double Psi[2][NNODE_1D];
     // Call the OneDimensional Shape functions
     OneDimLagrange::shape<NNODE_1D>(s[0], Psi[0]);
     OneDimLagrange::shape<NNODE_1D>(s[1], Psi[1]);
     // Index for the shape functions
     unsigned index = 0;
     // Now let's loop over the nodal points in the element
     // s1 is the "x" coordinate, s2 the "y"
     for (unsigned i = 0; i < NNODE_1D; i++)
     {
       for (unsigned j = 0; j < NNODE_1D; j++)
       {
         // Multiply the two 1D functions together to get the 2D function
         psi[index] = Psi[1][i] * Psi[0][j];
         // Incremenet the index
         ++index;
       }
     }
   }
References i, j, and s.
tecplot_zone_string()
template<unsigned NNODE_1D> std::string oomph::QElement< 2, NNODE_1D >::tecplot_zone_string (const unsigned & nplot) const inline virtual
Return string for tecplot zone header (when plotting nplot points in each "coordinate direction)
Reimplemented from oomph::FiniteElement.
     {
       std::ostringstream header;
       header << "ZONE I=" << nplot << ", J=" << nplot << "\n";
       return header.str();
     }
Referenced by oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::output(), oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::output(), and oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::output().
vertex_node_pt()
template<unsigned NNODE_1D> Node* oomph::QElement< 2, NNODE_1D >::vertex_node_pt (const unsigned & j) const inline virtual
Pointer to the j-th vertex node in the element.
Implements oomph::QuadElementBase.
Reimplemented in oomph::RefineableQYoungLaplaceElement< NNODE_1D >, oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >, oomph::RefineableQSphericalAdvectionDiffusionElement< 3 >, and oomph::RefineableQAxisymAdvectionDiffusionElement< 3 >.
     {
       unsigned n_node_1d = nnode_1d();
       Node* nod_pt;
       switch (j)
       {
         case 0:
           nod_pt = node_pt(0);
           break;
         case 1:
           nod_pt = node_pt(n_node_1d - 1);
           break;
         case 2:
           nod_pt = node_pt(n_node_1d * (n_node_1d - 1));
           break;
         case 3:
           nod_pt = node_pt(n_node_1d * n_node_1d - 1);
           break;
         default:
           std::ostringstream error_message;
           error_message << "Vertex node number is " << j
                         << " but must be from 0 to 3\n";
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
       }
       return nod_pt;
     }
References j, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::RefineableQAxisymAdvectionDiffusionElement< NNODE_1D >::vertex_node_pt(), oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >::vertex_node_pt(), and oomph::RefineableQYoungLaplaceElement< NNODE_1D >::vertex_node_pt().
write_paraview_offsets()
template<unsigned NNODE_1D> void oomph::QElement< 2, NNODE_1D >::write_paraview_offsets (std::ofstream & file_out, const unsigned & nplot, unsigned & offset_sum) const inline virtual
Return the offsets for the paraview sub-elements. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf
Reimplemented from oomph::FiniteElement.
     {
       // Loop over all local elements and add its offset to the overall
       // offset_sum
       unsigned local_loop = nsub_elements_paraview(nplot);
       for (unsigned i = 0; i < local_loop; i++)
       {
         offset_sum += 4;
         file_out << offset_sum << std::endl;
       }
     }
References i.
write_paraview_output_offset_information()
template<unsigned NNODE_1D> void oomph::QElement< 2, NNODE_1D >::write_paraview_output_offset_information (std::ofstream & file_out, const unsigned & nplot, unsigned & counter) const inline virtual
Fill in the offset information for paraview plot. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf
Reimplemented from oomph::FiniteElement.
     {
       // Number of local elements we want to plot over
       unsigned plot = nsub_elements_paraview(nplot);
       // loops over the i-th local element in parent element
       for (unsigned i = 0; i < plot; i++)
       {
         unsigned d = (i - (i % (nplot - 1))) / (nplot - 1);
         file_out << i % (nplot - 1) + d * nplot + counter << " "
                  << i % (nplot - 1) + 1 + d * nplot + counter << " "
                  << i % (nplot - 1) + 1 + (d + 1) * nplot + counter << " "
                  << i % (nplot - 1) + (d + 1) * nplot + counter << std::endl;
       }
       counter += nplot_points_paraview(nplot);
     }
References i, and PlanarWave::plot().
write_paraview_type()
template<unsigned NNODE_1D> void oomph::QElement< 2, NNODE_1D >::write_paraview_type (std::ofstream & file_out, const unsigned & nplot) const inline virtual
Return the paraview element type. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf Use type "VTK_QUAD" (== 9) for 2D quad elements
Reimplemented from oomph::FiniteElement.
     {
       unsigned local_loop = nsub_elements_paraview(nplot);
       for (unsigned i = 0; i < local_loop; i++)
       {
         file_out << "9" << std::endl;
       }
     }
References i.
Member Data Documentation
Default_integration_scheme
template<unsigned NNODE_1D> Gauss< 2, NNODE_1D > oomph::QElement< 2, NNODE_1D >::Default_integration_scheme static private
Assign the spatial integration scheme.
Default integration rule: Gaussian integration of same 'order' as the element
The documentation for this class was generated from the following files:
Qelements.h
Qelements.cc