MercuryDPM: extrude_triangle_generated_mesh.cc File Reference
extrude_triangle_generated_mesh.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "meshes/quad_from_triangle_mesh.h"
#include "meshes/extruded_cube_mesh_from_quad_mesh_with_macro_elements.h"
Classes
class MovingBlockProblem< ELEMENT >
Moving block problem.
Namespaces
GlobalParameters
Global parameters.
Functions
int main (int argc, char *argv[])
Variables
double GlobalParameters::Re =100.0
Reynolds number.
double GlobalParameters::L_z =3.0
Length of the mesh in the z-direction.
unsigned GlobalParameters::N_z =5
Number of elements in the z-direction.
DocInfo GlobalParameters::Doc_info
Helper for documenting.
Function Documentation
main()
int main (int argc , char * argv[])
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Driver for MovingBlock test problem – test drive with two different types of element.
 {
 #ifdef OOMPH_HAS_MPI
   // Initialise MPI
   MPI_Helpers::init(argc,argv);
   // Switch off output modifier
   oomph_info.output_modifier_pt()=&default_output_modifier;
   // Switch off oomph_info output for all processors but rank 0
   if (MPI_Helpers::communicator_pt()->my_rank()!=0)
   {
     oomph_info.stream_pt()=&oomph_nullstream;
     OomphLibWarning::set_stream_pt(&oomph_nullstream);
     OomphLibError::set_stream_pt(&oomph_nullstream);
   }
   else
   {
     oomph_info << "\n=====================================================\n"
                << "Number of processors: "
                << MPI_Helpers::communicator_pt()->nproc()
                << "\n=====================================================\n"
                << std::endl;
   }
 #endif
   // Record the start time
   double start_t=TimingHelpers::timer();
   // Set output directory
   GlobalParameters::Doc_info.set_directory("RESLT");
   // Step number
   GlobalParameters::Doc_info.number()=0;
   // Typedef the ELEMENT and MESH type
   typedef RefineableQTaylorHoodElement<2> ELEMENT;
   // Build the problem with QCrouzeixRaviartElements
   MovingBlockProblem<ELEMENT> problem;
   // Tell the user
   oomph_info << "Using RefineableQTaylorHoodElement<2>" << std::endl;
   // Solve the problem
   problem.newton_solve();
   // Output the solution
   problem.doc_solution();
   // Solve the problem
   problem.adapt();
   // Solve the problem
   problem.newton_solve();
   // Output the solution
   problem.doc_solution();
   // Record the end time and compute the mesh setup time
   oomph_info << "Simulation complete.\n\nTime taken for simulation [sec]: "
              << TimingHelpers::timer()-start_t << std::endl;
 #ifdef OOMPH_HAS_MPI
   // Initialise MPI
   MPI_Helpers::finalize();
 #endif
 } // end_of_main
References oomph::MPI_Helpers::communicator_pt(), oomph::default_output_modifier, GlobalParameters::Doc_info, oomph::MPI_Helpers::finalize(), oomph::MPI_Helpers::init(), oomph::OomphCommunicator::nproc(), oomph::DocInfo::number(), oomph::oomph_info, oomph::oomph_nullstream, oomph::OomphInfo::output_modifier_pt(), problem, oomph::DocInfo::set_directory(), oomph::OomphLibError::set_stream_pt(), oomph::OomphLibWarning::set_stream_pt(), oomph::OomphInfo::stream_pt(), and oomph::TimingHelpers::timer().