MercuryDPM: TriangulatedWall Class Reference
TriangulatedWall Class Reference
A TriangulatedWall is a triangulation created from a set of vertices and a n-by-3 connectivity matrix defining n faces.
#include <TriangulatedWall.h>
Classes
struct Face
Public Member Functions
TriangulatedWall ()
Default constructor.
TriangulatedWall (const TriangulatedWall &other)
Copy constructor.
TriangulatedWall (std::string filename, const ParticleSpecies *species)
Constructor setting values.
TriangulatedWall (const std::vector< Vec3D > &points, const std::vector< std::vector< unsigned >> &cells, const ParticleSpecies *species)
Constructor setting values.
void set (const std::vector< Vec3D > &points, const std::vector< std::vector< unsigned >> &cells)
void readVTK (std::string filename)
void writeVTK (VTKContainer &vtk) const override
~TriangulatedWall () override
Destructor.
TriangulatedWall & operator= (const TriangulatedWall &other)
TriangulatedWall * copy () const override
Wall copy method. It calls the copy constructor of this Wall, useful for polymorphism.
bool getDistanceAndNormal (const BaseParticle &p, Mdouble &distance, Vec3D &normal_return) const override
Compute the distance from the wall for a given BaseParticle and return if there is a collision. If there is a collision, also return the normal vector.
void move (const Vec3D &move) override
Move the TriangulatedWall to a new position, which is a Vec3D from the old position.
void read (std::istream &is) override
Reads an TriangulatedWall from an input stream, for example a restart file.
void write (std::ostream &os) const override
Writes an TriangulatedWall to an output stream, for example a restart file.
std::string getName () const override
Returns the name of the object, here the string "TriangulatedWall".
BaseInteraction * getInteractionWith (BaseParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler) override
Get the interaction between this TriangulatedWall and given BaseParticle at a given time.
Public Member Functions inherited from BaseWall
BaseWall ()
Default constructor.
BaseWall (const BaseWall &w)
Copy constructor.
~BaseWall () override
Default destructor.
virtual bool getDistanceNormalOverlap (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual bool getDistanceNormalOverlapSuperquadric (const SuperQuadricParticle &p, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual Vec3D getFurthestPointSuperQuadric (const Vec3D &normalBodyFixed, const Vec3D &axes, Mdouble eps1, Mdouble eps2) const
virtual void setHandler (WallHandler *handler)
A function which sets the WallHandler for this BaseWall.
WallHandler * getHandler () const
A function which returns the WallHandler that handles this BaseWall.
void setIndSpecies (unsigned int indSpecies) override
Define the species of this wall using the index of the species in the SpeciesHandler in this DPMBase.
void setSpecies (const ParticleSpecies *species)
Defines the species of the current wall.
bool isFixed () const override
void setForceControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity={0, 0, 0})
Slowly adjusts the force on a wall towards a specified goal, by adjusting (prescribing) the velocity of the wall.
virtual bool isLocal (Vec3D &min, Vec3D &max) const
bool getLinePlaneIntersect (Vec3D &intersect, const Vec3D &p0, const Vec3D &p1, const Vec3D &n, const Vec3D &p)
bool isInsideWallVTK (const Vec3D &point, const Vec3D &normal, const Vec3D &position) const
void projectOntoWallVTK (Vec3D &point0, const Vec3D &point1, const Vec3D &normal, const Vec3D &position) const
void intersectVTK (std::vector< Vec3D > &points, Vec3D normal, Vec3D position) const
virtual BaseInteraction * getInteractionWithSuperQuad (SuperQuadricParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler)
void getVTK (std::vector< Vec3D > &points, std::vector< std::vector< double >> &triangleStrips)
const Vec3D getAxis () const
virtual void actionsOnRestart ()
No implementation but can be overidden in its derived classes.
virtual void actionsAfterParticleGhostUpdate ()
No implementation but can be overidden in its derived classes.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
virtual void handleParticleRemoval (unsigned int id)
Handles the addition of particles to the particleHandler.
virtual void checkInteractions (InteractionHandler *interactionHandler, unsigned int timeStamp)
Check if all interactions are valid.
bool getVTKVisibility () const
void setVTKVisibility (bool vtkVisibility)
void addRenderedWall (BaseWall *w)
BaseWall * getRenderedWall (size_t i) const
std::vector< BaseWall * > getRenderedWalls () const
void removeRenderedWalls ()
void renderWall (VTKContainer &vtk)
void addParticlesAtWall (unsigned numElements=50)
void setVelocityControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity)
virtual void writeWallDetailsVTK (VTKData &data) const
virtual void computeWear ()
Public Member Functions inherited from BaseInteractable
BaseInteractable ()
Default BaseInteractable constructor.
BaseInteractable (const BaseInteractable &p)
Copy constructor.
~BaseInteractable () override
Destructor, it simply destructs the BaseInteractable and all the objects it contains.
unsigned int getIndSpecies () const
Returns the index of the species associated with the interactable object.
const ParticleSpecies * getSpecies () const
Returns a pointer to the species of this BaseInteractable.
void setSpecies (const ParticleSpecies *species)
Sets the species of this BaseInteractable.
const Vec3D & getForce () const
Returns the force on this BaseInteractable.
const Vec3D & getTorque () const
Returns the torque on this BaseInteractable.
void setForce (const Vec3D &force)
Sets the force on this BaseInteractable.
void setTorque (const Vec3D &torque)
Sets the torque on this BaseInteractable.
void addForce (const Vec3D &addForce)
Adds an amount to the force on this BaseInteractable.
void addTorque (const Vec3D &addTorque)
Adds an amount to the torque on this BaseInteractable.
virtual void resetForceTorque (int numberOfOMPthreads)
void sumForceTorqueOMP ()
const Vec3D & getPosition () const
Returns the position of this BaseInteractable.
const Quaternion & getOrientation () const
Returns the orientation of this BaseInteractable.
virtual void setPosition (const Vec3D &position)
Sets the position of this BaseInteractable.
void setOrientationViaNormal (Vec3D normal)
Sets the orientation of this BaseInteractable by defining the vector that results from the rotation of the (1,0,0) vector.
void setOrientationViaEuler (Vec3D eulerAngle)
Sets the orientation of this BaseInteractable by defining the euler angles.
virtual void setOrientation (const Quaternion &orientation)
Sets the orientation of this BaseInteractable.
virtual void rotate (const Vec3D &angularVelocityDt)
Rotates this BaseInteractable.
const std::vector< BaseInteraction * > & getInteractions () const
Returns a list of interactions which belong to this interactable.
void addInteraction (BaseInteraction *I)
Adds an interaction to this BaseInteractable.
bool removeInteraction (BaseInteraction *I)
Removes an interaction from this BaseInteractable.
void copyInteractionsForPeriodicParticles (const BaseInteractable &p)
Copies interactions to this BaseInteractable whenever a periodic copy made.
void setVelocity (const Vec3D &velocity)
set the velocity of the BaseInteractable.
void setAngularVelocity (const Vec3D &angularVelocity)
set the angular velocity of the BaseInteractble.
void addVelocity (const Vec3D &velocity)
adds an increment to the velocity.
void addAngularVelocity (const Vec3D &angularVelocity)
add an increment to the angular velocity.
virtual const Vec3D & getVelocity () const
Returns the velocity of this interactable.
virtual const Vec3D & getAngularVelocity () const
Returns the angular velocity of this interactable.
void setPrescribedPosition (const std::function< Vec3D(double)> &prescribedPosition)
Allows the position of an infinite mass interactable to be prescribed.
void applyPrescribedPosition (double time)
Computes the position from the user defined prescribed position function.
void setPrescribedVelocity (const std::function< Vec3D(double)> &prescribedVelocity)
Allows the velocity of an infinite mass interactable to be prescribed.
void applyPrescribedVelocity (double time)
Computes the velocity from the user defined prescribed velocity function.
void setPrescribedOrientation (const std::function< Quaternion(double)> &prescribedOrientation)
Allows the orientation of the infinite mass interactbale to be prescribed.
void applyPrescribedOrientation (double time)
Computes the orientation from the user defined prescribed orientation function.
void setPrescribedAngularVelocity (const std::function< Vec3D(double)> &prescribedAngularVelocity)
Allows the angular velocity of the infinite mass interactable to be prescribed.
void applyPrescribedAngularVelocity (double time)
Computes the angular velocity from the user defined prescribed angular velocity.
virtual const Vec3D getVelocityAtContact (const Vec3D &contact) const
Returns the velocity at the contact point, use by many force laws.
void integrateBeforeForceComputation (double time, double timeStep)
This is part of integrate routine for objects with infinite mass.
void integrateAfterForceComputation (double time, double timeStep)
This is part of the integration routine for objects with infinite mass.
virtual Mdouble getInvMass () const
virtual Mdouble getCurvature (const Vec3D &labFixedCoordinates) const
virtual bool isFaceContact (const Vec3D &normal) const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Protected Attributes
std::vector< Vec3D > vertex_
std::vector< Face > face_
Private Member Functions
void setNormalsAndNeighbours ()
Additional Inherited Members
Static Public Member Functions inherited from BaseWall
static void addToVTK (const std::vector< Vec3D > &points, VTKContainer &vtk)
Takes the points provided and adds a triangle strip connecting these points to the vtk container.
Detailed Description
A TriangulatedWall is a triangulation created from a set of vertices and a n-by-3 connectivity matrix defining n faces.
It is initialised by a unstructured grid vtk file:
TriangulatedWall w("TriangulatedWallSimple.vtk",speciesHandler.getLastObject());
The file consists of a set of vertices and a n-by-3 connectivity matrix defining n faces. Three vertices form a face; the face normal is oriented such that the vertices are ordered in anticlockwise direction around the normal.
Particles interact with a TriangulatedWall when they contact a face (from either side), a edge, or a vertex.
For a demonstration on how to use this class, see TriangulatedWallSelfTest (shown in the image below).
Constructor & Destructor Documentation
TriangulatedWall() [1/4]
TriangulatedWall::TriangulatedWall ()
Default constructor.
 {
     logger(DEBUG, "TriangulatedWall() constructed.");
 }
References DEBUG, and logger.
Referenced by copy().
TriangulatedWall() [2/4]
TriangulatedWall::TriangulatedWall (const TriangulatedWall & other)
Copy constructor.
Parameters
[in] other The TriangulatedWall that must be copied.
         : BaseWall(other)
 {
     face_ = other.face_;
     vertex_ = other.vertex_;
     //now reset the pointers
     for (unsigned f = 0; f < face_.size(); f++)
     {
         for (unsigned i = 0; i < 3; i++)
         {
             if (other.face_[f].neighbor[i])
             {
                 face_[f].neighbor[i] = &face_[other.face_[f].neighbor[i] - &other.face_[0]];
             } //else nullptr
             face_[f].vertex[i] = &vertex_[other.face_[f].vertex[i] - &other.vertex_[0]];
         }
     }
     logger(DEBUG, "TriangulatedWall(TriangulatedWall&) constructed.");
 }
References DEBUG, f(), face_, i, logger, and vertex_.
TriangulatedWall() [3/4]
TriangulatedWall::TriangulatedWall (std::string filename, const ParticleSpecies * species)
Constructor setting values.
 {
     setSpecies(species);
     readVTK(filename);
 }
References MergeRestartFiles::filename, readVTK(), and BaseWall::setSpecies().
TriangulatedWall() [4/4]
TriangulatedWall::TriangulatedWall (const std::vector< Vec3D > & points, const std::vector< std::vector< unsigned >> & cells, const ParticleSpecies * species)
Constructor setting values.
~TriangulatedWall()
TriangulatedWall::~TriangulatedWall () override
Destructor.
 {
     logger(DEBUG, "~TriangulatedWall() has been called.");
 }
References DEBUG, and logger.
Member Function Documentation
copy()
TriangulatedWall * TriangulatedWall::copy () const override virtual
Wall copy method. It calls the copy constructor of this Wall, useful for polymorphism.
Returns
pointer to a TriangulatedWall object allocated using new.
Implements BaseWall.
Reimplemented in WearableTriangulatedWall.
 {
     return new TriangulatedWall(*this);
 }
References TriangulatedWall().
Referenced by operator=().
getDistanceAndNormal()
bool TriangulatedWall::getDistanceAndNormal (const BaseParticle & p, Mdouble & distance, Vec3D & normal_return) const override virtual
Compute the distance from the wall for a given BaseParticle and return if there is a collision. If there is a collision, also return the normal vector.
Parameters
[in] p BaseParticle we want to calculate the distance and whether it collided of.
[out] distance The distance of the BaseParticle to this wall.
[out] normal_return If there was a collision, the normal vector to this wall will be placed here.
Returns
A boolean which says whether or not there was a collision.
This function computes whether or not there is a collision between a given BaseParticle and this TriangulatedWall. If there is a collision, this function also computes the distance between the BaseParticle and TriangulatedWall and the normal of the TriangulatedWall at the intersection point. It does this by calling TriangulatedWall::getDistanceAndNormal(const Vec3D& , Mdouble , Mdouble&, Vec3D&) const. Since this function should be called before calculating any Particle-Wall interactions, it can also be used to set the normal vector in case of curved walls.
NOTE: THIS ONLY RETURNS ONE OF POSSIBLY MANY INTERACTIONS; it's only used for finding out if interactions exist, so should be fine
Implements BaseWall.
 {
     Mdouble interactionRadius = p.getWallInteractionRadius(this);
     //it's important to use a reference here, as the faces use pointers
     for (const auto& face : face_)
     {
         if (face.getDistanceAndNormal(p, distance, normal_return, interactionRadius))
             return true;
     }
     return false;
 }
References face_, and p.
getInteractionWith()
BaseInteraction * TriangulatedWall::getInteractionWith (BaseParticle * p, unsigned timeStamp, InteractionHandler * interactionHandler) override virtual
Get the interaction between this TriangulatedWall and given BaseParticle at a given time.
Gets the interaction with this wall. In case of multiple contact points return the one with the shortest distance (i.e. largest overlap)
Parameters
[in] p Pointer to the BaseParticle which we want to check the interaction for.
[in] timeStamp The time at which we want to look at the interaction.
[in] interactionHandler A pointer to the InteractionHandler in which the interaction can be found.
Returns
A pointer to the BaseInteraction that happened between this wall and the BaseParticle at the timeStamp.
Reimplemented from BaseWall.
 {
     Mdouble distance, minDistance = constants::inf;
     Vec3D normal, minNormal;
     Mdouble interactionRadius = p->getWallInteractionRadius(this);
     for (const auto& face : face_)
     {
         if (face.getDistanceAndNormal(*p, distance, normal,interactionRadius) && distance < minDistance)
         {
             minDistance = distance;
             minNormal = normal;
         }
     }
     if (minDistance != constants::inf)
     {
         distance = minDistance;
         normal = -minNormal;
         BaseInteraction* const c = interactionHandler->getInteraction(p, this, timeStamp, normal);
         c->setNormal(normal);
         c->setDistance(distance);
         c->setOverlap(p->getRadius() - distance);
         c->setContactPoint(p->getPosition() - distance * normal);
         return c;
     }
     return nullptr;
 }
References calibrate::c, face_, InteractionHandler::getInteraction(), constants::inf, WallFunction::normal(), and p.
getName()
std::string TriangulatedWall::getName () const override virtual
Returns the name of the object, here the string "TriangulatedWall".
Returns
The string "TriangulatedWall".
Implements BaseObject.
Reimplemented in WearableTriangulatedWall.
 {
     return "TriangulatedWall";
 }
move()
void TriangulatedWall::move (const Vec3D & move) override virtual
Move the TriangulatedWall to a new position, which is a Vec3D from the old position.
Parameters
[in] move A reference to a Vec3D that denotes the direction and length it should be moved with.
A function that moves the TriangulatedWall in a certain direction by both moving the walls and all intersections. Note that the directions of the intersections are not moved since they don't change when moving the TriangulatedWall as a whole.
Todo:
We should use the position_ and orientation_ of the TriangulatedWall; that way, TriangulatedWall can be moved with the standard BaseInteractable::move function, getting rid of an anomaly in the code and removing the virtual from the move function.
Author
weinhartt
Reimplemented from BaseInteractable.
 {
     BaseInteractable::move(move);
     for (auto& v : vertex_)
     {
         v += move;
     }
 }
References BaseInteractable::move(), v, and vertex_.
operator=()
TriangulatedWall & TriangulatedWall::operator= (const TriangulatedWall & other)
Copy assignment operator.
Parameters
[in] other The TriangulatedWall that must be copied.
 {
     logger(DEBUG, "TriangulatedWall::operator= called.");
     if (this == &other)
     {
         return *this;
     }
     return *(other.copy());
 }
References copy(), DEBUG, and logger.
read()
void TriangulatedWall::read (std::istream & is) override virtual
Reads an TriangulatedWall from an input stream, for example a restart file.
Parameters
[in] is The input stream from which the TriangulatedWall is read, usually a restart file.
Todo:
Reimplemented from BaseWall.
Reimplemented in WearableTriangulatedWall.
 {
 }
Referenced by WearableTriangulatedWall::read().
readVTK()
void TriangulatedWall::readVTK (std::string filename)
Parameters
[in] filename name of vtk input file, e.g. TriangulatedWallSelfTest.vtk
 {
     std::fstream file;
     file.open(filename.c_str(), std::ios::in);
     logger.assert_always(file.is_open(), "File opening failed: %", filename);
     std::string dummy;
     getline(file, dummy);
     getline(file, dummy);
     getline(file, dummy);
     getline(file, dummy);
     //read points
     unsigned num;
     file >> dummy >> num >> dummy;
     vertex_.reserve(num);
     Vec3D v;
     for (unsigned i = 0; i < num; i++)
     {
         file >> v.X >> v.Y >> v.Z;
         vertex_.push_back(v);
     }
     //read faces
     file >> dummy >> num >> dummy;
     face_.reserve(num);
     Face f;
     unsigned id0, id1, id2;
     for (unsigned i = 0; i < num; i++)
     {
         file >> dummy >> id0 >> id1 >> id2;
         f.vertex[0] = &vertex_[id0];
         f.vertex[1] = &vertex_[id1];
         f.vertex[2] = &vertex_[id2];
         face_.push_back(f);
     }
     file.close();
     setNormalsAndNeighbours();
 }
References f(), face_, MergeRestartFiles::filename, i, logger, setNormalsAndNeighbours(), oomph::Global_string_for_annotation::string(), v, and vertex_.
Referenced by TriangulatedWall().
set()
void TriangulatedWall::set (const std::vector< Vec3D > & points, const std::vector< std::vector< unsigned >> & cells)
 {
     //points
     vertex_ = points;
     //cells
     unsigned num = cells.size();
     face_.reserve(num);
     Face f;
     for (unsigned i = 0; i < num; i++)
     {
         f.vertex[0] = &vertex_[cells[i][0]];
         f.vertex[1] = &vertex_[cells[i][1]];
         f.vertex[2] = &vertex_[cells[i][2]];
         face_.push_back(f);
     }
     //normals, positions, neighbours
     setNormalsAndNeighbours();
 }
References f(), face_, i, setNormalsAndNeighbours(), and vertex_.
Referenced by WearableTriangulatedWall::WearableTriangulatedWall().
setNormalsAndNeighbours()
void TriangulatedWall::setNormalsAndNeighbours () private
 {
     //set normals and positions
     for (auto& face: face_)
     {
         face.normal = Vec3D::getUnitVector(
                 Vec3D::cross(*face.vertex[1] - *face.vertex[0], *face.vertex[2] - *face.vertex[0]));
     }
     //set neighbours
     for (auto face0 = face_.begin(); face0 + 1 != face_.end(); face0++)
     {
         for (auto face1 = face0 + 1; face1 != face_.end(); face1++)
         {
             if (face0->vertex[0] == face1->vertex[0])
             {
                 if (face0->vertex[1] == face1->vertex[2])
                 { //edge 0=2
                     face0->neighbor[0] = &*face1;
                     face1->neighbor[2] = &*face0;
                 }
                 else if (face0->vertex[2] == face1->vertex[1])
                 { //edge 2=0
                     face0->neighbor[2] = &*face1;
                     face1->neighbor[0] = &*face0;
                 }
             }
             else if (face0->vertex[0] == face1->vertex[1])
             {
                 if (face0->vertex[1] == face1->vertex[0])
                 { //edge 0=0
                     face0->neighbor[0] = &*face1;
                     face1->neighbor[0] = &*face0;
                 }
                 else if (face0->vertex[2] == face1->vertex[2])
                 { //edge 2=1
                     face0->neighbor[2] = &*face1;
                     face1->neighbor[1] = &*face0;
                 }
             }
             else if (face0->vertex[0] == face1->vertex[2])
             {
                 if (face0->vertex[1] == face1->vertex[1])
                 { //edge 0=1
                     face0->neighbor[0] = &*face1;
                     face1->neighbor[1] = &*face0;
                 }
                 else if (face0->vertex[2] == face1->vertex[0])
                 { //edge 2=2
                     face0->neighbor[2] = &*face1;
                     face1->neighbor[2] = &*face0;
                 }
             }
             else if (face0->vertex[1] == face1->vertex[0])
             {
                 if (face0->vertex[2] == face1->vertex[2])
                 { //edge 1=2
                     face0->neighbor[1] = &*face1;
                     face1->neighbor[2] = &*face0;
                 }
             }
             else if (face0->vertex[1] == face1->vertex[1])
             {
                 if (face0->vertex[2] == face1->vertex[0])
                 { //edge 1=0
                     face0->neighbor[1] = &*face1;
                     face1->neighbor[0] = &*face0;
                 }
             }
             else if (face0->vertex[1] == face1->vertex[2])
             {
                 if (face0->vertex[2] == face1->vertex[1])
                 { //edge 1=1
                     face0->neighbor[1] = &*face1;
                     face1->neighbor[1] = &*face0;
                 }
             }
         }
     }
     //set edge normals (inwards facing)
     for (auto& face: face_)
     {
         face.edgeNormal[0] = Vec3D::getUnitVector(Vec3D::cross(face.normal, *face.vertex[1] - *face.vertex[0]));
         face.edgeNormal[1] = Vec3D::getUnitVector(Vec3D::cross(face.normal, *face.vertex[2] - *face.vertex[1]));
         face.edgeNormal[2] = Vec3D::getUnitVector(Vec3D::cross(face.normal, *face.vertex[0] - *face.vertex[2]));
     }
 }
References Vec3D::cross(), oomph::QElement1FaceToBulkCoordinates::face0(), oomph::QElement1FaceToBulkCoordinates::face1(), face_, and Vec3D::getUnitVector().
Referenced by readVTK(), and set().
write()
void TriangulatedWall::write (std::ostream & os) const override virtual
Writes an TriangulatedWall to an output stream, for example a restart file.
Parameters
[in] os The output stream where the TriangulatedWall must be written to, usually a restart file.
Reimplemented from BaseWall.
Reimplemented in WearableTriangulatedWall.
 {
     os << "Vertices " << vertex_.size();
     for (const auto& vertex: vertex_)
     {
         os << "  " << vertex;
     }
     os << std::endl;
     //os << "Faces " << face_.size() << std::endl;
     unsigned counter = 0;
     for (const auto& face: face_)
     {
         os << "Face " << counter++
            << " vertex " << face.vertex[0] - &vertex_[0]
            << " " << face.vertex[1] - &vertex_[0]
            << " " << face.vertex[2] - &vertex_[0]
            << " neighbor " << (face.neighbor[0] ? (face.neighbor[0] - &face_[0]) : -1)
            << " " << (face.neighbor[1] ? (face.neighbor[1] - &face_[0]) : -1)
            << " " << (face.neighbor[2] ? (face.neighbor[2] - &face_[0]) : -1)
            << " normal " << face.normal
            << " edgeNormal " << face.edgeNormal[0]
            << "  " << face.edgeNormal[1]
            << "  " << face.edgeNormal[2]
            << std::endl;
     }
 }
References face_, and vertex_.
Referenced by WearableTriangulatedWall::write().
writeVTK()
void TriangulatedWall::writeVTK (VTKContainer & vtk) const override virtual
adds extra information to the points and triangleStrips vectors needed to plot the wall in vtk format
Parameters
points Coordinates of the vertices of the triangulated surfaces (in the VTK file this is called POINTS)
triangleStrips Indices of three vertices forming one triangulated surface (in the VTK file this is called CELL)
Reimplemented from BaseWall.
 {
     const int s = vtk.points.size();
     for (auto v : vertex_)
     {
         vtk.points.push_back(v);
     }
     for (auto f : face_)
     {
         std::vector<double> cell;
         cell.reserve(3);
         cell.push_back(s + f.vertex[0] - &vertex_[0]);
         cell.push_back(s + f.vertex[1] - &vertex_[0]);
         cell.push_back(s + f.vertex[2] - &vertex_[0]);
         vtk.triangleStrips.push_back(cell);
     }
 }
References f(), face_, VTKContainer::points, s, VTKContainer::triangleStrips, v, and vertex_.
Member Data Documentation
face_
std::vector<Face> TriangulatedWall::face_ protected
stores the face properties
Referenced by getDistanceAndNormal(), getInteractionWith(), WearableTriangulatedWall::processDebris(), readVTK(), set(), setNormalsAndNeighbours(), WearableTriangulatedWall::storeDebris(), TriangulatedWall(), WearableTriangulatedWall::WearableTriangulatedWall(), write(), and writeVTK().
vertex_
std::vector<Vec3D> TriangulatedWall::vertex_ protected
stores the vertex coordinates
Referenced by move(), readVTK(), set(), TriangulatedWall(), write(), and writeVTK().
The documentation for this class was generated from the following files:
TriangulatedWall.h
TriangulatedWall.cc