MercuryDPM: Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType > Struct Template Reference
Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType > Struct Template Reference
#include <SparseLU.h>
Public Types
typedef MatrixLType::Scalar Scalar
Public Member Functions
SparseLUMatrixUReturnType (const MatrixLType &mapL, const MatrixUType &mapU)
Index rows () const
Index cols () const
template<typename Dest >
void solveInPlace (MatrixBase< Dest > &X) const
template<bool Conjugate, typename Dest >
void solveTransposedInPlace (MatrixBase< Dest > &X) const
SparseMatrix< Scalar, RowMajor, Index > toSparse ()
Public Attributes
const MatrixLType & m_mapL
const MatrixUType & m_mapU
Member Typedef Documentation
Scalar
template<typename MatrixLType , typename MatrixUType > typedef MatrixLType::Scalar Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::Scalar
Constructor & Destructor Documentation
SparseLUMatrixUReturnType()
template<typename MatrixLType , typename MatrixUType > Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::SparseLUMatrixUReturnType (const MatrixLType & mapL, const MatrixUType & mapU) inline
 : m_mapL(mapL), m_mapU(mapU) {}
Member Function Documentation
cols()
template<typename MatrixLType , typename MatrixUType > Index Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::cols () const inline
 { return m_mapL.cols(); }
References Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::m_mapL.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::toSparse().
rows()
template<typename MatrixLType , typename MatrixUType > Index Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::rows () const inline
 { return m_mapL.rows(); }
References Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::m_mapL.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::toSparse().
solveInPlace()
template<typename MatrixLType , typename MatrixUType > template<typename Dest > void Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::solveInPlace (MatrixBase< Dest > & X) const inline
{
     Index nrhs = X.cols();
     // Backward solve with U
     for (Index k = m_mapL.nsuper(); k >= 0; k--) {
       Index fsupc = m_mapL.supToCol()[k];
       Index lda = m_mapL.colIndexPtr()[fsupc + 1] - m_mapL.colIndexPtr()[fsupc];  // leading dimension
       Index nsupc = m_mapL.supToCol()[k + 1] - fsupc;
       Index luptr = m_mapL.colIndexPtr()[fsupc];
       if (nsupc == 1) {
         for (Index j = 0; j < nrhs; j++) {
           X(fsupc, j) /= m_mapL.valuePtr()[luptr];
         }
       } else {
         // FIXME: the following lines should use Block expressions and not Map!
         Map<const Matrix<Scalar, Dynamic, Dynamic, ColMajor>, 0, OuterStride<>> A(&(m_mapL.valuePtr()[luptr]), nsupc,
                                                                                   nsupc, OuterStride<>(lda));
         typename Dest::RowsBlockXpr U = X.derived().middleRows(fsupc, nsupc);
         U = A.template triangularView<Upper>().solve(U);
       }
       for (Index j = 0; j < nrhs; ++j) {
         for (Index jcol = fsupc; jcol < fsupc + nsupc; jcol++) {
           typename MatrixUType::InnerIterator it(m_mapU, jcol);
           for (; it; ++it) {
             Index irow = it.index();
             X(irow, j) -= X(jcol, j) * it.value();
           }
         }
       }
     }  // End For U-solve
   }
References j, k, lda, Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::m_mapL, Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::m_mapU, RachelsAdvectionDiffusion::U, and X.
solveTransposedInPlace()
template<typename MatrixLType , typename MatrixUType > template<bool Conjugate, typename Dest > void Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::solveTransposedInPlace (MatrixBase< Dest > & X) const inline
{
     using numext::conj;
     Index nrhs = X.cols();
     // Forward solve with U
     for (Index k = 0; k <= m_mapL.nsuper(); k++) {
       Index fsupc = m_mapL.supToCol()[k];
       Index lda = m_mapL.colIndexPtr()[fsupc + 1] - m_mapL.colIndexPtr()[fsupc];  // leading dimension
       Index nsupc = m_mapL.supToCol()[k + 1] - fsupc;
       Index luptr = m_mapL.colIndexPtr()[fsupc];
       for (Index j = 0; j < nrhs; ++j) {
         for (Index jcol = fsupc; jcol < fsupc + nsupc; jcol++) {
           typename MatrixUType::InnerIterator it(m_mapU, jcol);
           for (; it; ++it) {
             Index irow = it.index();
             X(jcol, j) -= X(irow, j) * (Conjugate ? conj(it.value()) : it.value());
           }
         }
       }
       if (nsupc == 1) {
         for (Index j = 0; j < nrhs; j++) {
           X(fsupc, j) /= (Conjugate ? conj(m_mapL.valuePtr()[luptr]) : m_mapL.valuePtr()[luptr]);
         }
       } else {
         Map<const Matrix<Scalar, Dynamic, Dynamic, ColMajor>, 0, OuterStride<>> A(&(m_mapL.valuePtr()[luptr]), nsupc,
                                                                                   nsupc, OuterStride<>(lda));
         typename Dest::RowsBlockXpr U = X.derived().middleRows(fsupc, nsupc);
         if (Conjugate)
           U = A.adjoint().template triangularView<Lower>().solve(U);
         else
           U = A.transpose().template triangularView<Lower>().solve(U);
       }
     }  // End For U-solve
   }
References conj(), Eigen::conj(), j, k, lda, Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::m_mapL, Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::m_mapU, RachelsAdvectionDiffusion::U, and X.
toSparse()
template<typename MatrixLType , typename MatrixUType > SparseMatrix<Scalar, RowMajor, Index> Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::toSparse () inline
{
     ArrayXi rowCount = ArrayXi::Zero(rows());
     for (Index i = 0; i < cols(); i++) {
       typename MatrixLType::InnerIterator iter(m_mapL, i);
       for (; iter; ++iter) {
         if (iter.row() <= iter.col()) {
           rowCount(iter.row())++;
         }
       }
     }
     SparseMatrix<Scalar, RowMajor, Index> sU(rows(), cols());
     sU.reserve(rowCount);
     for (Index i = 0; i < cols(); i++) {
       typename MatrixLType::InnerIterator iter(m_mapL, i);
       for (; iter; ++iter) {
         if (iter.row() <= iter.col()) {
           sU.insert(iter.row(), iter.col()) = iter.value();
         }
       }
     }
     sU.makeCompressed();
     const SparseMatrix<Scalar, RowMajor, Index> u = m_mapU;  // convert to RowMajor
     sU += u;
     return sU;
   }
References Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::cols(), i, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insert(), Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::m_mapL, Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::m_mapU, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::makeCompressed(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::reserve(), Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::rows(), and oomph::PseudoSolidHelper::Zero.
Member Data Documentation
m_mapL
template<typename MatrixLType , typename MatrixUType > const MatrixLType& Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::m_mapL
Referenced by Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::cols(), Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::rows(), Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::solveInPlace(), Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::solveTransposedInPlace(), and Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::toSparse().
m_mapU
template<typename MatrixLType , typename MatrixUType > const MatrixUType& Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::m_mapU
Referenced by Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::solveInPlace(), Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::solveTransposedInPlace(), and Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::toSparse().
The documentation for this struct was generated from the following file:
SparseLU.h