MercuryDPM: TwoParticleCollisionInteractionWithLiquidMigrationWilletViscousSelfTest.cpp File Reference
TwoParticleCollisionInteractionWithLiquidMigrationWilletViscousSelfTest.cpp File Reference
#include "Mercury3D.h"
#include "Walls/InfiniteWall.h"
#include <Species/LinearViscoelasticFrictionLiquidMigrationWilletViscousSpecies.h>
#include "Particles/LiquidFilmParticle.h"
#include "DPMBase.h"
Classes
class TwoParticleCollisionInteraction
In this file two particles are symmetrically placed in a domain with opposite initial velocities, to test the liquid bridge force after colliding.
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
{
         TwoParticleCollisionInteraction wpw;
         wpw.setName("TwoParticleCollisionInteractionWithLiquidMigrationWilletViscousSelfTest");
         wpw.setMax({0.01,0.01,0.02});
         wpw.setGravity({0.0,0.0,0.0});
         wpw.Radius = 1.74e-3*0.5;//d=1.74mm
         wpw.vel_x = 0.4;
         wpw.vel_y = 0;
         wpw.vel_z = 0;
         wpw.setParticlesWriteVTK(true);
         wpw.wallHandler.setWriteVTK(FileType::ONE_FILE);
         wpw.solve(argc,argv);
         return 0;
     }
References ONE_FILE, TwoParticleCollisionInteraction::Radius, DPMBase::setGravity(), DPMBase::setMax(), DPMBase::setName(), DPMBase::setParticlesWriteVTK(), WallHandler::setWriteVTK(), DPMBase::solve(), TwoParticleCollisionInteraction::vel_x, TwoParticleCollisionInteraction::vel_y, TwoParticleCollisionInteraction::vel_z, and DPMBase::wallHandler.