MercuryDPM: Eigen::internal::gemv_static_vector_if< Scalar, Size, MaxSize, true > Struct Template Reference
Eigen::internal::gemv_static_vector_if< Scalar, Size, MaxSize, true > Struct Template Reference
#include <GeneralProduct.h>
Public Member Functions
constexpr EIGEN_STRONG_INLINE Scalar * data ()
Public Attributes
internal::plain_array< Scalar, internal::min_size_prefer_fixed(Size, MaxSize)+EIGEN_MAX_ALIGN_BYTES, 0 > m_data
Member Function Documentation
data()
template<typename Scalar , int Size, int MaxSize> constexpr EIGEN_STRONG_INLINE Scalar* Eigen::internal::gemv_static_vector_if< Scalar, Size, MaxSize, true >::data () inline constexpr
{
     return reinterpret_cast<Scalar*>((std::uintptr_t(m_data.array) & ~(std::size_t(EIGEN_MAX_ALIGN_BYTES - 1))) +
                                      EIGEN_MAX_ALIGN_BYTES);
   }
References EIGEN_MAX_ALIGN_BYTES.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
Member Data Documentation
m_data
template<typename Scalar , int Size, int MaxSize> internal::plain_array<Scalar, internal::min_size_prefer_fixed(Size, MaxSize) + EIGEN_MAX_ALIGN_BYTES, 0> Eigen::internal::gemv_static_vector_if< Scalar, Size, MaxSize, true >::m_data
The documentation for this struct was generated from the following file:
GeneralProduct.h