MercuryDPM: matrix_square_root.cpp File Reference
matrix_square_root.cpp File Reference
#include "matrix_functions.h"
Functions
template<typename MatrixType >
void testMatrixSqrt (const MatrixType &m)
EIGEN_DECLARE_TEST (matrix_square_root)
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (matrix_square_root)
{
   for (int i = 0; i < g_repeat; i++) {
     CALL_SUBTEST_1(testMatrixSqrt(Matrix3cf()));
     CALL_SUBTEST_2(testMatrixSqrt(MatrixXcd(12, 12)));
     CALL_SUBTEST_3(testMatrixSqrt(Matrix4f()));
     CALL_SUBTEST_4(testMatrixSqrt(Matrix<double, Dynamic, Dynamic, RowMajor>(9, 9)));
     CALL_SUBTEST_5(testMatrixSqrt(Matrix<float, 1, 1>()));
     CALL_SUBTEST_5(testMatrixSqrt(Matrix<std::complex<float>, 1, 1>()));
   }
 }
References CALL_SUBTEST_1, CALL_SUBTEST_2, CALL_SUBTEST_3, CALL_SUBTEST_4, CALL_SUBTEST_5, Eigen::g_repeat, i, and testMatrixSqrt().
testMatrixSqrt()
template<typename MatrixType > void testMatrixSqrt (const MatrixType & m)
{
   MatrixType A;
   generateTestMatrix<MatrixType>::run(A, m.rows());
   MatrixType sqrtA = A.sqrt();
   VERIFY_IS_APPROX(sqrtA * sqrtA, A);
 }
References m, run(), sqrtA, and VERIFY_IS_APPROX.
Referenced by EIGEN_DECLARE_TEST().