MercuryDPM: Eigen::internal::linspaced_op_impl< Scalar, false > Struct Template Reference
Eigen::internal::linspaced_op_impl< Scalar, false > Struct Template Reference
#include <NullaryFunctors.h>
Public Types
typedef NumTraits< Scalar >::Real RealScalar
Public Member Functions
EIGEN_DEVICE_FUNC linspaced_op_impl (const Scalar &low, const Scalar &high, Index num_steps)
template<typename IndexType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar operator() (IndexType i) const
template<typename Packet , typename IndexType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Packet packetOp (IndexType i) const
Public Attributes
const Scalar m_low
const Scalar m_high
const Index m_size1
const Scalar m_step
const bool m_flip
Member Typedef Documentation
RealScalar
template<typename Scalar > typedef NumTraits<Scalar>::Real Eigen::internal::linspaced_op_impl< Scalar, false >::RealScalar
Constructor & Destructor Documentation
linspaced_op_impl()
template<typename Scalar > EIGEN_DEVICE_FUNC Eigen::internal::linspaced_op_impl< Scalar, false >::linspaced_op_impl (const Scalar & low, const Scalar & high, Index num_steps) inline
       : m_low(low),
         m_high(high),
         m_size1(num_steps == 1 ? 1 : num_steps - 1),
         m_step(num_steps == 1 ? Scalar() : Scalar((high - low) / RealScalar(num_steps - 1))),
         m_flip(numext::abs(high) < numext::abs(low)) {}
Member Function Documentation
operator()()
template<typename Scalar > template<typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar Eigen::internal::linspaced_op_impl< Scalar, false >::operator() (IndexType i) const inline
{
     if (m_flip)
       return (i == 0) ? m_low : Scalar(m_high - RealScalar(m_size1 - i) * m_step);
     else
       return (i == m_size1) ? m_high : Scalar(m_low + RealScalar(i) * m_step);
   }
References i.
packetOp()
template<typename Scalar > template<typename Packet , typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Packet Eigen::internal::linspaced_op_impl< Scalar, false >::packetOp (IndexType i) const inline
{
     // Principle:
     // [low, ..., low] + ( [step, ..., step] * ( [i, ..., i] + [0, ..., size] ) )
     if (m_flip) {
       Packet pi = plset<Packet>(Scalar(i - m_size1));
       Packet res = padd(pset1<Packet>(m_high), pmul(pset1<Packet>(m_step), pi));
       if (EIGEN_PREDICT_TRUE(i != 0)) return res;
       Packet mask = pcmp_lt(pset1<Packet>(0), plset<Packet>(0));
       return pselect<Packet>(mask, res, pset1<Packet>(m_low));
     } else {
       Packet pi = plset<Packet>(Scalar(i));
       Packet res = padd(pset1<Packet>(m_low), pmul(pset1<Packet>(m_step), pi));
       if (EIGEN_PREDICT_TRUE(i != m_size1 - unpacket_traits<Packet>::size + 1)) return res;
       Packet mask = pcmp_lt(plset<Packet>(0), pset1<Packet>(unpacket_traits<Packet>::size - 1));
       return pselect<Packet>(mask, res, pset1<Packet>(m_high));
     }
   }
References EIGEN_PREDICT_TRUE, i, Eigen::internal::padd(), Eigen::internal::pcmp_lt(), constants::pi, Eigen::internal::pmul(), and res.
Member Data Documentation
m_flip
template<typename Scalar > const bool Eigen::internal::linspaced_op_impl< Scalar, false >::m_flip
m_high
template<typename Scalar > const Scalar Eigen::internal::linspaced_op_impl< Scalar, false >::m_high
m_low
template<typename Scalar > const Scalar Eigen::internal::linspaced_op_impl< Scalar, false >::m_low
m_size1
template<typename Scalar > const Index Eigen::internal::linspaced_op_impl< Scalar, false >::m_size1
m_step
template<typename Scalar > const Scalar Eigen::internal::linspaced_op_impl< Scalar, false >::m_step
The documentation for this struct was generated from the following file:
NullaryFunctors.h