MercuryDPM: level2_cplx_impl.h File Reference
level2_cplx_impl.h File Reference
#include "common.h"
Functions
if (UPLO(*uplo)==INVALID) info = 1
else if * lda (1, *n)) info=5;else if(*incx==0) info=7;else if(*incy==0) info=10;if(info) return xerbla_(SCALAR_SUFFIX_UP "HEMV ", &info
if (beta !=Scalar(1))
if (alpha !=Scalar(0))
if (actual_x !=x) delete[] actual_x
if (actual_y !=y) delete[] copy_back(actual_y
EIGEN_BLAS_FUNC() hpr (char *uplo, int *n, RealScalar *palpha, RealScalar *px, int *incx, RealScalar *pap)
if (info) return xerbla_(SCALAR_SUFFIX_UP "HPR2 "
if (alpha==Scalar(0)) return
if (code >=2||func[code]==0) return
if (x_cpy !=x) delete[] x_cpy
if (y_cpy !=y) delete[] y_cpy
EIGEN_BLAS_FUNC() her (char *uplo, int *n, RealScalar *palpha, RealScalar *px, int *incx, RealScalar *pa, int *lda)
matrix (a, *n, *n, *lda).diagonal().imag().setZero()
Variables
const char * uplo
const char const int * n
const char const int const RealScalar * palpha
const char const int const RealScalar const RealScalar * pa
const char const int const RealScalar const RealScalar const int * lda
const char const int const RealScalar const RealScalar const int const RealScalar * px
const char const int const RealScalar const RealScalar const int const RealScalar const int * incx
const char const int const RealScalar const RealScalar const int const RealScalar const int const RealScalar * pbeta
const char const int const RealScalar const RealScalar const int const RealScalar const int const RealScalar RealScalar * py
const char const int const RealScalar const RealScalar const int const RealScalar const int const RealScalar RealScalar const int * incy
static const functype func [2]
const Scalar * a = reinterpret_cast<const Scalar *>(pa)
const Scalar * x = reinterpret_cast<const Scalar *>(px)
Scalar * y = reinterpret_cast<Scalar *>(py)
Scalar alpha = *reinterpret_cast<const Scalar *>(palpha)
Scalar beta = *reinterpret_cast<const Scalar *>(pbeta)
int info = 0
if n return
const Scalar * actual_x = get_compact_vector(x, *n, *incx)
Scalar * actual_y = get_compact_vector(y, *n, *incy)
char int RealScalar RealScalar int RealScalar int RealScalar * pap
Scalar * ap = reinterpret_cast<Scalar *>(pap)
Scalar * x_cpy = get_compact_vector(x, *n, *incx)
Scalar * y_cpy = get_compact_vector(y, *n, *incy)
int code = UPLO(*uplo)
int * m
Function Documentation
her()
EIGEN_BLAS_FUNC() her (char * uplo, int * n, RealScalar * palpha, RealScalar * px, int * incx, RealScalar * pa, int * lda)
ZHER performs the hermitian rank 1 operation
A := alpha*x*conjg(x') + A,
where alpha is a real scalar, x is an n element vector and A is an n by n hermitian matrix.
{
   typedef void (*functype)(int, Scalar *, int, const Scalar *, const Scalar *, const Scalar &);
   static const functype func[2] = {
       // array index: UP
       (Eigen::selfadjoint_rank1_update<Scalar, int, Eigen::ColMajor, Eigen::Upper, false, Conj>::run),
       // array index: LO
       (Eigen::selfadjoint_rank1_update<Scalar, int, Eigen::ColMajor, Eigen::Lower, false, Conj>::run),
   };
   Scalar *x = reinterpret_cast<Scalar *>(px);
   Scalar *a = reinterpret_cast<Scalar *>(pa);
   RealScalar alpha = *reinterpret_cast<RealScalar *>(palpha);
   int info = 0;
   if (UPLO(*uplo) == INVALID)
     info = 1;
   else if (*n < 0)
     info = 2;
   else if (*incx == 0)
     info = 5;
   else if (*lda < std::max(1, *n))
     info = 7;
   if (info) return xerbla_(SCALAR_SUFFIX_UP "HER  ", &info);
   if (alpha == RealScalar(0)) return;
   Scalar *x_cpy = get_compact_vector(x, *n, *incx);
   int code = UPLO(*uplo);
   if (code >= 2 || func[code] == 0) return;
   func[code](*n, a, *lda, x_cpy, x_cpy, alpha);
   matrix(a, *n, *n, *lda).diagonal().imag().setZero();
   if (x_cpy != x) delete[] x_cpy;
 }
References a, alpha, code, get_compact_vector(), incx, info, int(), INVALID, lda, matrix(), max, n, pa, palpha, px, SCALAR_SUFFIX_UP, UPLO, uplo, x, x_cpy, and xerbla_().
hpr()
EIGEN_BLAS_FUNC() hpr (char * uplo, int * n, RealScalar * palpha, RealScalar * px, int * incx, RealScalar * pap)
ZHBMV performs the matrix-vector operation
y := alpha*A*x + beta*y,
where alpha and beta are scalars, x and y are n element vectors and A is an n by n hermitian band matrix, with k super-diagonals. ZHPMV performs the matrix-vector operation
y := alpha*A*x + beta*y,
where alpha and beta are scalars, x and y are n element vectors and A is an n by n hermitian matrix, supplied in packed form. ZHPR performs the hermitian rank 1 operation
A := alpha*x*conjg(x') + A,
where alpha is a real scalar, x is an n element vector and A is an n by n hermitian matrix, supplied in packed form.
{
   typedef void (*functype)(int, Scalar *, const Scalar *, RealScalar);
   static const functype func[2] = {
       // array index: UP
       (Eigen::internal::selfadjoint_packed_rank1_update<Scalar, int, Eigen::ColMajor, Eigen::Upper, false, Conj>::run),
       // array index: LO
       (Eigen::internal::selfadjoint_packed_rank1_update<Scalar, int, Eigen::ColMajor, Eigen::Lower, false, Conj>::run),
   };
   Scalar *x = reinterpret_cast<Scalar *>(px);
   Scalar *ap = reinterpret_cast<Scalar *>(pap);
   RealScalar alpha = *palpha;
   int info = 0;
   if (UPLO(*uplo) == INVALID)
     info = 1;
   else if (*n < 0)
     info = 2;
   else if (*incx == 0)
     info = 5;
   if (info) return xerbla_(SCALAR_SUFFIX_UP "HPR  ", &info);
   if (alpha == Scalar(0)) return;
   Scalar *x_cpy = get_compact_vector(x, *n, *incx);
   int code = UPLO(*uplo);
   if (code >= 2 || func[code] == 0) return;
   func[code](*n, ap, x_cpy, alpha);
   if (x_cpy != x) delete[] x_cpy;
 }
References alpha, ap, code, get_compact_vector(), incx, info, int(), INVALID, n, palpha, pap, px, SCALAR_SUFFIX_UP, UPLO, uplo, x, x_cpy, and xerbla_().
if() [1/10]
if (actual_x ! = x)
if() [2/10]
if (actual_y ! = y)
if() [3/10]
if (alpha ! = Scalar(0))
{
     int code = UPLO(*uplo);
     if (code >= 2 || func[code] == 0) return;
     func[code](*n, a, *lda, actual_x, actual_y, alpha);
   }
References a, actual_x, actual_y, alpha, code, lda, n, UPLO, and uplo.
if() [4/10]
if (alpha = =Scalar(0))
if() [5/10]
if (beta ! = Scalar(1))
{
     if (beta == Scalar(0))
       make_vector(actual_y, *n).setZero();
     else
       make_vector(actual_y, *n) *= beta;
   }
References actual_y, beta, make_vector(), and n.
if() [6/10]
if (code >=2|| func[code] = =0)
if() [7/10]
if (info)
if() [8/10]
if (UPLO * uplo = =INVALID) = 1
{
     matA.triangularView<Upper>() = matrix(a, size, size, *lda);
     matA.triangularView<Lower>() = matrix(a, size, size, *lda).transpose();
   } else if (UPLO(*uplo) == LO) {
References a, lda, Eigen::Lower, matA(), matrix(), size, and Eigen::Upper.
Referenced by blas.Blas::__init__(), lapack.Lapack::__init__(), framework.Frame::__init__(), blacs.Blacs::check_blacs(), blas.Blas::check_blas(), lapack.Lapack::check_lapack(), framework.Frame::check_linking(), framework.Frame::check_mpicc(), framework.Frame::check_mpif77(), Eigen::Serializer< DenseBase< Derived >, void >::deserialize(), Eigen::Serializer< SparseMatrix< Scalar, Options, StorageIndex >, void >::deserialize(), Eigen::Serializer< SparseVector< Scalar, Options, StorageIndex >, void >::deserialize(), scalapack.Scalapack::down_install(), blacs.Blacs::down_install_blacs(), blas.Blas::down_install_blas(), lapack.Lapack::down_install_lapack(), utils::downloader(), utils::fixpaths(), fpdiff::fpdiff_helper(), utils::killfiles(), framework.Frame::look_for_mpibinaries(), framework.Frame::look_for_mpih(), Eigen::SluMatrix::Map(), framework.Frame::parse_args(), fpdiff::read_file(), framework.Frame::set_download(), lapack.Lapack::set_etime(), framework.Frame::set_mangling(), blacs.Blacs::set_transcomm(), and test_empty_runqueue().
if() [9/10]
if (x_cpy ! = x)
if() [10/10]
if (y_cpy ! = y)
lda()
else if* lda (1 , * n) &
matrix()
matrix (a , * n, * n, * lda)
Referenced by her().
Variable Documentation
a
const Scalar * a = reinterpret_cast<const Scalar *>(pa)
Referenced by __attribute__(), Eigen::internal::__UNPACK_TYPE__(), Eigen::internal::_mm_extract_epi64_0(), Eigen::internal::_mm_extract_epi64_1(), Eigen::bfloat16_impl::abs(), Eigen::half_impl::abs(), Jeffery_Solution::acceleration(), Eigen::bfloat16_impl::acos(), Eigen::half_impl::acos(), Eigen::bfloat16_impl::acosh(), MercuryProblem::actionsAfterTimeStep(), VolumeCoupling::actionsAfterTimeStep(), adjoint_extra(), aliasing_with_resize(), alignedboxRotatable(), alignedboxTranslatable(), Eigen::SimplicialCholeskyBase< Derived >::analyzePattern(), Eigen::SimplicialLLT< MatrixType_, UpLo_, Ordering_ >::analyzePattern(), Eigen::SimplicialLDLT< MatrixType_, UpLo_, Ordering_ >::analyzePattern(), Eigen::SimplicialNonHermitianLLT< MatrixType_, UpLo_, Ordering_ >::analyzePattern(), Eigen::SimplicialNonHermitianLDLT< MatrixType_, UpLo_, Ordering_ >::analyzePattern(), Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::analyzePattern(), Eigen::AccelerateImpl< MatrixType_, UpLo_, Solver_, EnforceSquare_ >::analyzePattern(), Eigen::PardisoImpl< Derived >::analyzePattern(), Jeffery_Solution::angle(), oomph::VectorHelpers::angle(), angleToVec(), Quaternion< float >::angularVelocityBodyFixedFrameToAngularDisplacement(), AnnularDiskProblem< ELASTICITY_ELEMENT >::AnnularDiskProblem(), Eigen::test::areApprox(), Eigen::test::areApproxAbs(), Eigen::test::areEqual(), Eigen::numext::arithmetic_shift_right(), Eigen::internal::array_apply(), Eigen::internal::array_apply_and_reduce(), Eigen::internal::array_get(), Eigen::internal::array_prod(), array_special_functions(), Eigen::internal::array_zip(), Eigen::internal::array_zip_and_reduce(), Eigen::bfloat16_impl::asin(), Eigen::half_impl::asin(), Eigen::bfloat16_impl::asinh(), oomph::OneDLagrangianMesh< ELEMENT >::assign_undeformed_positions(), ShellMesh< ELEMENT >::assign_undeformed_positions(), FlatPlateMesh< ELEMENT >::assign_undeformed_positions(), oomph::CircularCylindricalShellMesh< ELEMENT >::assign_undeformed_positions(), Eigen::internal::assign_op< DstScalar, SrcScalar >::assignCoeff(), Eigen::internal::add_assign_op< DstScalar, SrcScalar >::assignCoeff(), Eigen::internal::sub_assign_op< DstScalar, SrcScalar >::assignCoeff(), Eigen::internal::mul_assign_op< DstScalar, SrcScalar >::assignCoeff(), Eigen::internal::div_assign_op< DstScalar, SrcScalar >::assignCoeff(), Eigen::internal::swap_assign_op< Scalar >::assignCoeff(), Eigen::internal::assign_op< DstScalar, SrcScalar >::assignPacket(), Eigen::internal::add_assign_op< DstScalar, SrcScalar >::assignPacket(), Eigen::internal::sub_assign_op< DstScalar, SrcScalar >::assignPacket(), Eigen::internal::mul_assign_op< DstScalar, SrcScalar >::assignPacket(), Eigen::internal::div_assign_op< DstScalar, SrcScalar >::assignPacket(), Eigen::bfloat16_impl::atan(), Eigen::half_impl::atan(), Eigen::atan2(), Eigen::bfloat16_impl::atan2(), Eigen::half_impl::atan2(), Eigen::bfloat16_impl::atanh(), Eigen::half_impl::atanh(), BaseSpecies::average(), BaseSpecies::averageInf(), SmallMatrix< numberOfRows, numberOfColumns >::axpy(), SmallVector< numberOfRows >::axpy(), bandmatrix(), Eigen::Spline< Scalar_, Dim_, Degree_ >::BasisFunctionDerivativesImpl(), bench(), bench_prod(), bench_svd(), benchBasic_loop(), benchVec(), CRBond_Bessel::bessik01a(), CRBond_Bessel::bessjy01a(), CRBond_Bessel::bessjynb(), CRBond_Bessel::bessjyv(), Eigen::betainc(), Eigen::internal::Bf16ToF32(), Eigen::internal::bytewise_bitwise_helper< T >::binary(), binary_op_test(), Eigen::test::biteq(), Eigen::internal::operator_bitwise_helper< T >::bitwise_and(), Eigen::internal::bytewise_bitwise_helper< T >::bitwise_and(), Eigen::internal::operator_bitwise_helper< T >::bitwise_not(), Eigen::internal::bytewise_bitwise_helper< T >::bitwise_not(), Eigen::internal::operator_bitwise_helper< T >::bitwise_or(), Eigen::internal::bytewise_bitwise_helper< T >::bitwise_or(), Eigen::internal::operator_bitwise_helper< T >::bitwise_xor(), Eigen::internal::bytewise_bitwise_helper< T >::bitwise_xor(), BlockCompressionProblem< ELEMENT >::BlockCompressionProblem(), Eigen::internal::lapacke_helpers::lapacke_partial_lu< Scalar, StorageOrder >::blocked_lu(), Eigen::internal::bruteforce_det3_helper(), NurbsUtils::bsplineDerBasis(), bug_127(), Eigen::AccelerateImpl< MatrixType_, UpLo_, Solver_, EnforceSquare_ >::buildAccelSparseMatrix(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::calc_post(), oomph::HomogenisedLinearElasticityEquations< DIM >::calculate_effective_modulus(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_fitting_parameters_of_cubic(), oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_fitting_parameters_of_cubic(), GlobalParameters::calculate_strouhal_number(), call_ref(), call_ref_1(), call_ref_2(), call_ref_3(), call_ref_4(), call_ref_5(), call_ref_6(), call_ref_7(), pcast_array< SrcPacket, TgtPacket, 2, 1 >::cast(), pcast_array< SrcPacket, TgtPacket, 4, 1 >::cast(), pcast_array< SrcPacket, TgtPacket, 8, 1 >::cast(), Eigen::internal::cat256(), Eigen::internal::cat256i(), CRBond_Bessel::cbessik01(), CRBond_Bessel::cbessjy01(), CRBond_Bessel::cbessjynb(), Eigen::bfloat16_impl::ceil(), Eigen::half_impl::ceil(), check_eigensolver_for_given_mat(), Eigen::internal::check_implication(), check_indexed_view(), oomph::VectorHelpers::check_lengths_match(), check_shift(), cholesky(), NurbsUtils::close(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::CoatedDiskProblem(), CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::CoatedSphereProblem(), Eigen::internal::scalar_inner_product_op< LhsScalar, RhsScalar, Conj >::coeff(), Eigen::internal::conditional_conj< Scalar, true >::coeff(), Eigen::internal::conditional_conj< Scalar, false >::coeff(), Eigen::internal::scalar_inner_product_op< Scalar, Scalar, Conj >::coeff(), Eigen::internal::combine2Packet16h(), compare(), Eigen::internal::minmax_compare< Scalar, NaNPropagation, is_min >::compare(), Eigen::internal::minmax_compare< Scalar, NaNPropagation, false >::compare(), compare_bdc_jacobi(), CompareFunction(), comparisons(), Eigen::internal::complex_log(), oomph::CompressedMatrixCoefficient::CompressedMatrixCoefficient(), Eigen::LDLT< MatrixType_, UpLo_ >::compute(), Eigen::LLT< MatrixType_, UpLo_ >::compute(), Eigen::GeneralizedEigenSolver< MatrixType_ >::compute(), Eigen::AccelerateImpl< MatrixType_, UpLo_, Solver_, EnforceSquare_ >::compute(), Eigen::PardisoImpl< Derived >::compute(), Eigen::BDCSVD< MatrixType_, Options_ >::compute_impl(), Eigen::JacobiSVD< MatrixType_, Options_ >::compute_impl(), LiquidBridgeBagheriInteraction::computeAdhesionForce(), Eigen::ThreadPoolTempl< Environment >::ComputeCoprimes(), ChuteWithPeriodicInflow::computeInternalForces(), Eigen::BDCSVD< MatrixType_, Options_ >::computeSingVals(), oomph::OcTree::construct_rotation_matrix(), constructorTest(), constructorTest< float >(), oomph::FaceElement::continuous_tangent_and_outer_unit_normal(), Eigen::bfloat16_impl::cos(), Eigen::half_impl::cos(), Eigen::bfloat16_impl::cosh(), Eigen::createRandomPIMatrixOfRank(), Matrix3D::cross(), Vec3D::cross(), oomph::CylinderWithFlagMesh< ELEMENT >::CylinderWithFlagMesh(), oomph::Ellipse::d2position(), dense_storage_swap(), HGridOptimiser::diffEndExpectedCellsIntegral(), HGridOptimiser::diffHExpectedCellsIntegralCellNumerator(), HGridOptimiser::diffPdfInt(), HGridOptimiser::diffStartExpectedCellsIntegral(), Vec3D::divideElementwise(), CantileverProblem< ELEMENT >::doc_solution(), dontalign(), Vec3D::dot(), oomph::VectorHelpers::dot(), PSD::drawSample(), Eigen::DSizes< DenseIndex, NumDims >::DSizes(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant(), Matrix3D::dyadic(), EIGEN_DECLARE_TEST(), Eigen::numext::EIGEN_MATHFUNC_RETVAL(), Eigen::internal::lapacke_helpers::lapacke_llt< Scalar, Mode >::EIGEN_STATIC_ASSERT(), eigensolver(), eigensolver_generic_extra(), eigensolver_verify_assert(), ElasticAnnulusProblem< ELASTICITY_ELEMENT >::ElasticAnnulusProblem(), Eigen::internal::enum_eq_not_dynamic(), Eigen::internal::enum_ge_not_dynamic(), Eigen::internal::enum_gt_not_dynamic(), Eigen::internal::enum_le_not_dynamic(), Eigen::internal::enum_lt_not_dynamic(), eulerangles(), eulerangles_rand(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::evalToBuf(), Eigen::bfloat16_impl::exp(), Eigen::half_impl::exp(), Eigen::bfloat16_impl::exp2(), Eigen::half_impl::exp2(), HGridOptimiser::expectedCellsIntegralCellDenominator(), HGridOptimiser::expectedCellsIntegralCellNumerator(), Eigen::bfloat16_impl::expm1(), Eigen::half_impl::expm1(), Eigen::internal::extract2Packet16h(), Eigen::internal::F32ToBf16(), boost::multiprecision::fabs(), Eigen::SimplicialCholeskyBase< Derived >::factorize(), Eigen::SimplicialLLT< MatrixType_, UpLo_, Ordering_ >::factorize(), Eigen::SimplicialLDLT< MatrixType_, UpLo_, Ordering_ >::factorize(), Eigen::SimplicialNonHermitianLLT< MatrixType_, UpLo_, Ordering_ >::factorize(), Eigen::SimplicialNonHermitianLDLT< MatrixType_, UpLo_, Ordering_ >::factorize(), Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::factorize(), Eigen::AccelerateImpl< MatrixType_, UpLo_, Solver_, EnforceSquare_ >::factorize(), Eigen::PardisoImpl< Derived >::factorize(), Eigen::SuperLU< MatrixType_ >::factorize(), oomph::ODEElement::fill_in_contribution_to_jacobian(), oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_residuals_beam(), oomph::KirchhoffLoveShellEquations::fill_in_contribution_to_residuals_shell(), oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::HomogenisedLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity(), oomph::LinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity(), oomph::RefineableLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity(), oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::PVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::ScaleCoupledElement< ELEMENT >::fill_in_generic_contribution_to_residuals_pvd(), oomph::VolumeCoupledElement< ELEMENT >::fill_in_generic_contribution_to_residuals_pvd(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::TimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::AxisymmetricPoroelasticityEquations::fill_in_generic_residual_contribution(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_lin_axi_nst(), oomph::RefineablePVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), oomph::PVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), fixedSizeMatrixConstruction(), Eigen::internal::float2half(), float_pow_test_impl(), Eigen::bfloat16_impl::floor(), Eigen::half_impl::floor(), Eigen::bfloat16_impl::fmax(), boost::multiprecision::fmax(), Eigen::bfloat16_impl::fmin(), Eigen::bfloat16_impl::fmod(), Eigen::half_impl::fmod(), Eigen::numext::fmod(), Eigen::Quaternion< Scalar_, Options_ >::FromTwoVectors(), gemm(), Eigen::internal::gemm_kern_avx512(), gemv_complex_col(), GeneralEllipse::GeneralEllipse(), generalized_eigensolver_real(), Eigen::internal::generic_ceil(), Eigen::internal::generic_floor(), Eigen::internal::generic_ndtri(), Eigen::internal::generic_rint(), Eigen::internal::generic_round(), Eigen::internal::generic_trunc(), oomph::GeompackQuadScaffoldMesh::GeompackQuadScaffoldMesh(), oomph::RefineableQElement< 3 >::get_boundaries(), oomph::KirchhoffLoveShellEquations::get_energy(), oomph::KirchhoffLoveBeamEquations::get_energy(), Global_Physical_Variables::get_exact_u(), RachelsAdvectionDiffusion::get_exact_u(), oomph::CRDoubleMatrix::get_matrix_transpose(), oomph::KirchhoffLoveShellEquations::get_strain_and_bend(), PolarNSProblem< ELEMENT >::get_symmetry(), oomph::StreamfunctionProblem::get_vels(), get_xpr_with_temps(), Vec3D::getDistance(), NurbsSurface::getDistance(), Quaternion< float >::getDistance(), AxisymmetricIntersectionOfWalls::getDistanceAndNormal(), HorizontalBaseScrew::getDistanceAndNormal(), SineWall::getDistanceAndNormal(), Vec3D::getDistanceSquared(), CGCoordinates::Base_X_Y_Z::getGaussIntegralPrefactor(), CGCoordinates::Base_XY_XZ_YZ::getGaussIntegralPrefactor(), CGCoordinates::XYZ::getGaussIntegralPrefactor(), Quaternion< float >::getLength(), Vec3D::getLength(), Vec3D::getLengthSquared(), Quaternion< float >::getRotationMatrix(), Vec3D::getUnitVector(), TriangleMeshWall::getVolumeTetrahedron(), Eigen::internal::h_array_apply(), Eigen::internal::h_array_zip(), Eigen::internal::h_array_zip_and_reduce(), Eigen::internal::half2float(), her(), HstopCurve(), if(), Eigen::igamma(), Eigen::igamma_der_a(), Eigen::igammac(), oomph::CRDoubleMatrix::inf_norm(), Eigen::SuperLUBase< MatrixType_, Derived >::initFactorization(), initializerListArrayConstruction(), initializerListVectorConstruction(), PSD::insertManuallyByVolume(), inv_cond(), exp_complex_test_impl< Scalar, Packet, HasExp >::is_exactly_equal(), is_same_block(), is_same_eq(), is_same_seq(), is_same_seq_type(), is_same_symb(), SilbertHstop::IsAboveCurve(), Eigen::test::isApproxAbs(), Eigen::bfloat16_impl::isfinite(), Eigen::half_impl::isfinite(), Eigen::bfloat16_impl::isinf(), Eigen::half_impl::isinf(), Eigen::bfloat16_impl::isnan(), Eigen::half_impl::isnan(), jacobi(), Eigen::internal::trsmKernelL< Scalar, Index, Mode, Conjugate, TriStorageOrder, OtherInnerStride, Specialized >::kernel(), Eigen::internal::trsmKernelR< Scalar, Index, Mode, Conjugate, TriStorageOrder, OtherInnerStride, Specialized >::kernel(), Eigen::kroneckerProduct(), lerp(), lerpFrame(), oomph::Refineable_r_mesh< ELEMENT >::linear_spacing(), lines(), LoadConf(), Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::loadLhs(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadLhs(), Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, ConjRhs_, Arch, PacketSize_ >::loadLhs(), Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadLhs(), Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadLhsUnaligned(), Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::loadLhsUnaligned(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadLhsUnaligned(), Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, ConjRhs_, Arch, PacketSize_ >::loadLhsUnaligned(), LoadMass(), LoadPD(), LoadPebbles(), LoadTOI(), Eigen::bfloat16_impl::log(), Eigen::half_impl::log(), Eigen::bfloat16_impl::log10(), Eigen::half_impl::log10(), Eigen::bfloat16_impl::log1p(), Eigen::half_impl::log1p(), Eigen::bfloat16_impl::log2(), Eigen::half_impl::log2(), oomph::Refineable_r_mesh< ELEMENT >::log_spacing(), Eigen::numext::logical_shift_left(), Eigen::numext::logical_shift_right(), Eigen::internal::logical_xor(), Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::madd(), Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::madd(), Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, ConjRhs_, Arch, PacketSize_ >::madd(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::madd(), Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::madd_impl(), Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, ConjRhs_, Arch, PacketSize_ >::madd_impl(), mag2(), oomph::VectorHelpers::magnitude(), main(), Eigen::internal::main_igamma_term(), Eigen::internal::make_packet2d(), Eigen::internal::make_packet2f(), Eigen::internal::make_packet4f(), Eigen::internal::manage_caching_sizes_helper(), mapQuaternion(), matlab_real_cplx(), Eigen::bfloat16_impl::max(), Eigen::half_impl::max(), Vec3D::max(), Eigen::internal::max_size_prefer_dynamic(), Eigen::bfloat16_impl::min(), Eigen::half_impl::min(), Vec3D::min(), Eigen::internal::min_size_prefer_dynamic(), Eigen::internal::min_size_prefer_fixed(), msvc_workaround(), Vec3D::multiplyElementwise(), Eigen::internal::muluh(), negative_or_zero(), nlerp(), non_projective_only(), oomph::DGEulerFaceElement< ELEMENT >::numerical_flux(), Eigen::bfloat16_impl::operator!=(), Eigen::half_impl::operator!=(), Eigen::internal::scalar_sqrt_op< bool >::operator()(), Eigen::internal::scalar_square_op< bool >::operator()(), Eigen::internal::scalar_cube_op< bool >::operator()(), Eigen::internal::bit_not< bool >::operator()(), Eigen::internal::bit_and< bool >::operator()(), Eigen::internal::bit_or< bool >::operator()(), Eigen::internal::bit_xor< bool >::operator()(), Eigen::internal::bind2nd_op< BinaryOp >::operator()(), Eigen::internal::scalar_sum_op< LhsScalar, RhsScalar >::operator()(), Eigen::internal::scalar_product_op< LhsScalar, RhsScalar >::operator()(), Eigen::internal::scalar_conj_product_op< LhsScalar, RhsScalar >::operator()(), Eigen::internal::scalar_min_op< LhsScalar, RhsScalar, NaNPropagation >::operator()(), Eigen::internal::scalar_max_op< LhsScalar, RhsScalar, NaNPropagation >::operator()(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_EQ, UseTypedComparators >::operator()(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_LT, UseTypedComparators >::operator()(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_LE, UseTypedComparators >::operator()(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_GT, UseTypedComparators >::operator()(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_GE, UseTypedComparators >::operator()(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_UNORD, UseTypedComparators >::operator()(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_NEQ, UseTypedComparators >::operator()(), Eigen::internal::scalar_difference_op< LhsScalar, RhsScalar >::operator()(), Eigen::internal::scalar_quotient_op< LhsScalar, RhsScalar >::operator()(), Eigen::internal::scalar_absolute_difference_op< LhsScalar, RhsScalar >::operator()(), Eigen::internal::scalar_disjunction_op< DupFunctor, LhsScalar, RhsScalar >::operator()(), Eigen::internal::abs_knowing_score< Scalar, typename scalar_score_coeff_op< Scalar >::Score_is_abs >::operator()(), scalar_norm1_op::operator()(), Eigen::internal::scalar_opposite_op< Scalar >::operator()(), Eigen::internal::scalar_abs_op< Scalar >::operator()(), Eigen::internal::scalar_abs2_op< Scalar >::operator()(), Eigen::internal::squared_norm_functor< Scalar, IsComplex >::operator()(), Eigen::internal::scalar_conjugate_op< Scalar >::operator()(), Eigen::internal::scalar_arg_op< Scalar >::operator()(), Eigen::internal::scalar_carg_op< Scalar >::operator()(), Eigen::internal::scalar_cast_op< Scalar, NewType >::operator()(), Eigen::internal::scalar_shift_right_op< Scalar, N >::operator()(), Eigen::internal::scalar_shift_left_op< Scalar, N >::operator()(), Eigen::internal::scalar_real_op< Scalar >::operator()(), Eigen::internal::scalar_imag_op< Scalar >::operator()(), Eigen::internal::scalar_real_ref_op< Scalar >::operator()(), Eigen::internal::scalar_exp_op< Scalar >::operator()(), Eigen::internal::scalar_exp2_op< Scalar >::operator()(), Eigen::internal::scalar_expm1_op< Scalar >::operator()(), Eigen::internal::scalar_log_op< Scalar >::operator()(), Eigen::internal::scalar_log1p_op< Scalar >::operator()(), Eigen::internal::scalar_log10_op< Scalar >::operator()(), Eigen::internal::scalar_log2_op< Scalar >::operator()(), Eigen::internal::scalar_sqrt_op< Scalar >::operator()(), Eigen::internal::scalar_cbrt_op< Scalar >::operator()(), Eigen::internal::scalar_rsqrt_op< Scalar >::operator()(), Eigen::internal::scalar_cos_op< Scalar >::operator()(), Eigen::internal::scalar_sin_op< Scalar >::operator()(), Eigen::internal::scalar_tan_op< Scalar >::operator()(), Eigen::internal::scalar_acos_op< Scalar >::operator()(), Eigen::internal::scalar_asin_op< Scalar >::operator()(), Eigen::internal::scalar_atan_op< Scalar >::operator()(), Eigen::internal::scalar_tanh_op< Scalar >::operator()(), Eigen::internal::scalar_atanh_op< Scalar >::operator()(), Eigen::internal::scalar_sinh_op< Scalar >::operator()(), Eigen::internal::scalar_asinh_op< Scalar >::operator()(), Eigen::internal::scalar_cosh_op< Scalar >::operator()(), Eigen::internal::scalar_acosh_op< Scalar >::operator()(), Eigen::internal::scalar_inverse_op< Scalar >::operator()(), Eigen::internal::scalar_square_op< Scalar >::operator()(), Eigen::internal::scalar_cube_op< Scalar >::operator()(), Eigen::internal::scalar_round_op< Scalar >::operator()(), Eigen::internal::scalar_floor_op< Scalar >::operator()(), Eigen::internal::scalar_rint_op< Scalar >::operator()(), Eigen::internal::scalar_ceil_op< Scalar >::operator()(), Eigen::internal::scalar_trunc_op< Scalar >::operator()(), Eigen::internal::scalar_isnan_op< Scalar, UseTypedPredicate >::operator()(), Eigen::internal::scalar_isnan_op< Scalar, true >::operator()(), Eigen::internal::scalar_isinf_op< Scalar, UseTypedPredicate >::operator()(), Eigen::internal::scalar_isinf_op< Scalar, true >::operator()(), Eigen::internal::scalar_isfinite_op< Scalar, UseTypedPredicate >::operator()(), Eigen::internal::scalar_isfinite_op< Scalar, true >::operator()(), Eigen::internal::scalar_boolean_not_op< Scalar >::operator()(), Eigen::internal::scalar_bitwise_not_op< Scalar >::operator()(), Eigen::internal::scalar_sign_op< Scalar >::operator()(), Eigen::internal::scalar_unary_pow_op< Scalar, ExponentScalar, IsBaseInteger, IsExponentInteger, IsBaseComplex, IsExponentComplex >::operator()(), Eigen::internal::scalar_unary_pow_op< Scalar, ExponentScalar, false, false, false, false >::operator()(), Eigen::internal::scalar_unary_pow_op< Scalar, ExponentScalar, BaseIsInteger, true, false, false >::operator()(), Eigen::internal::test_signbit_op< Scalar >::operator()(), Eigen::internal::scalar_dummy_op< Scalar, Vectorize >::operator()(), Eigen::internal::scalar_mod_op< Scalar >::operator()(), Eigen::internal::scalar_lgamma_op< Scalar >::operator()(), Eigen::internal::scalar_digamma_op< Scalar >::operator()(), Eigen::internal::scalar_erf_op< Scalar >::operator()(), Eigen::internal::scalar_erfc_op< Scalar >::operator()(), Eigen::internal::scalar_ndtri_op< Scalar >::operator()(), Eigen::internal::scalar_pow_op< Scalar, Exponent >::operator()(), MakeComplexOp< Scalar >::operator()(), Eigen::internal::scalar_boolean_and_op< Scalar >::operator()(), Eigen::internal::scalar_boolean_or_op< Scalar >::operator()(), Eigen::internal::scalar_boolean_xor_op< Scalar >::operator()(), Eigen::internal::scalar_bitwise_and_op< Scalar >::operator()(), Eigen::internal::scalar_bitwise_or_op< Scalar >::operator()(), Eigen::internal::scalar_bitwise_xor_op< Scalar >::operator()(), Eigen::internal::scalar_mod2_op< Scalar >::operator()(), Eigen::internal::scalar_fmod_op< Scalar >::operator()(), Eigen::internal::scalar_igamma_op< Scalar >::operator()(), Eigen::internal::scalar_igamma_der_a_op< Scalar >::operator()(), Eigen::internal::scalar_igammac_op< Scalar >::operator()(), Eigen::internal::abs_knowing_score< Scalar, typename >::operator()(), Eigen::internal::scalar_betainc_op< Scalar >::operator()(), Eigen::internal::bit_not< T >::operator()(), Eigen::internal::bit_and< T >::operator()(), Eigen::internal::bit_or< T >::operator()(), Eigen::internal::bit_xor< T >::operator()(), Eigen::internal::scalar_boolean_select_op< ThenScalar, ElseScalar, ConditionScalar >::operator()(), Eigen::internal::TripletComp< Iterator, IsColMajor >::operator()(), Eigen::internal::scalar_imag_ref_op< Scalar >::operator()(), Eigen::internal::gemm_pack_lhs< Scalar, Index, DataMapper, Pack1, Pack2, Packet, RowMajor, Conjugate, PanelMode >::operator()(), Eigen::bfloat16_impl::operator*(), Eigen::half_impl::operator*(), Vec3D::operator*(), Eigen::internal::operator*(), Eigen::symbolic::BaseExpr< Derived_ >::operator*(), CGFields::DisplacementField::operator*(), CGFields::GradVelocityField::operator*(), CGFields::LiquidMigrationFields::operator*(), CGFields::OrientationField::operator*(), CGFields::StandardFields::operator*(), Matrix3D::operator*(), MatrixSymmetric3D::operator*(), Quaternion::operator*(), Eigen::bfloat16_impl::operator*=(), Eigen::half_impl::operator*=(), Quaternion::operator*=(), Quaternion< float >::operator*=(), Vec3D::operator*=(), Eigen::bfloat16_impl::operator+(), Eigen::half_impl::operator+(), Eigen::operator+(), Quaternion::operator+(), Vec3D::operator+(), Matrix3D::operator+(), MatrixSymmetric3D::operator+(), Eigen::bfloat16_impl::operator++(), Eigen::half_impl::operator++(), Eigen::bfloat16_impl::operator+=(), Quaternion::operator+=(), Vec3D::operator+=(), Eigen::half_impl::operator+=(), Eigen::bfloat16_impl::operator-(), Eigen::half_impl::operator-(), Eigen::operator-(), Quaternion::operator-(), Vec3D::operator-(), operator-(), Eigen::symbolic::BaseExpr< Derived_ >::operator-(), Matrix3D::operator-(), MatrixSymmetric3D::operator-(), Eigen::bfloat16_impl::operator--(), Eigen::half_impl::operator--(), Eigen::bfloat16_impl::operator-=(), Quaternion::operator-=(), Vec3D::operator-=(), Eigen::half_impl::operator-=(), Eigen::bfloat16_impl::operator/(), Eigen::half_impl::operator/(), Eigen::symbolic::BaseExpr< Derived_ >::operator/(), Matrix3D::operator/(), MatrixSymmetric3D::operator/(), Quaternion::operator/(), Vec3D::operator/(), Eigen::bfloat16_impl::operator/=(), Vec3D::operator/=(), Eigen::half_impl::operator/=(), CGFields::DisplacementField::operator/=(), CGFields::GradVelocityField::operator/=(), CGFields::LiquidMigrationFields::operator/=(), CGFields::OrientationField::operator/=(), CGFields::StandardFields::operator/=(), Matrix3D::operator/=(), MatrixSymmetric3D::operator/=(), Eigen::bfloat16_impl::operator<(), oomph::CompressedMatrixCoefficient::operator<(), Eigen::half_impl::operator<(), Vec3D::operator<(), oomph::operator<<(), Eigen::bfloat16_impl::operator<=(), Eigen::half_impl::operator<=(), oomph::CompressedMatrixCoefficient::operator=(), Eigen::bfloat16_impl::operator==(), Eigen::half_impl::operator==(), Vec3D::operator==(), Eigen::bfloat16_impl::operator>(), Eigen::half_impl::operator>(), Eigen::bfloat16_impl::operator>=(), Eigen::half_impl::operator>=(), Vec3D::operator>=(), Eigen::SimplicialCholeskyBase< Derived >::ordering(), OscEllipseProblem< ELEMENT, TIMESTEPPER >::OscEllipseProblem(), Eigen::internal::pabs(), Eigen::internal::pabs< Packet2d >(), Eigen::internal::pabs< Packet32h >(), Eigen::internal::pabs< Packet4c >(), Eigen::internal::pabs< Packet4f >(), Eigen::internal::pabs< Packet4i >(), Eigen::internal::pabsdiff(), Eigen::internal::pabsdiff< Packet16c >(), Eigen::internal::pabsdiff< Packet16uc >(), Eigen::internal::pabsdiff< Packet2f >(), Eigen::internal::pabsdiff< Packet2i >(), Eigen::internal::pabsdiff< Packet2ui >(), Eigen::internal::pabsdiff< Packet4bf >(), Eigen::internal::pabsdiff< Packet4c >(), Eigen::internal::pabsdiff< Packet4f >(), Eigen::internal::pabsdiff< Packet4i >(), Eigen::internal::pabsdiff< Packet4s >(), Eigen::internal::pabsdiff< Packet4uc >(), Eigen::internal::pabsdiff< Packet4ui >(), Eigen::internal::pabsdiff< Packet4us >(), Eigen::internal::pabsdiff< Packet8c >(), Eigen::internal::pabsdiff< Packet8s >(), Eigen::internal::pabsdiff< Packet8uc >(), Eigen::internal::pabsdiff< Packet8us >(), Eigen::internal::conditional_conj< Scalar, true >::packet(), Eigen::internal::conditional_conj< Scalar, false >::packet(), Eigen::internal::scalar_inner_product_op< Scalar, Scalar, Conj >::packet(), Eigen::internal::Packet1cd::Packet1cd(), Eigen::internal::Packet2cf::Packet2cf(), Eigen::internal::bind2nd_op< BinaryOp >::packetOp(), Eigen::internal::scalar_opposite_op< Scalar >::packetOp(), Eigen::internal::scalar_abs_op< Scalar >::packetOp(), Eigen::internal::scalar_abs2_op< Scalar >::packetOp(), Eigen::internal::squared_norm_functor< Scalar, IsComplex >::packetOp(), Eigen::internal::scalar_conjugate_op< Scalar >::packetOp(), Eigen::internal::scalar_arg_op< Scalar >::packetOp(), Eigen::internal::scalar_carg_op< Scalar >::packetOp(), Eigen::internal::scalar_shift_right_op< Scalar, N >::packetOp(), Eigen::internal::scalar_shift_left_op< Scalar, N >::packetOp(), Eigen::internal::scalar_exp_op< Scalar >::packetOp(), Eigen::internal::scalar_exp2_op< Scalar >::packetOp(), Eigen::internal::scalar_expm1_op< Scalar >::packetOp(), Eigen::internal::scalar_log_op< Scalar >::packetOp(), Eigen::internal::scalar_log1p_op< Scalar >::packetOp(), Eigen::internal::scalar_log10_op< Scalar >::packetOp(), Eigen::internal::scalar_log2_op< Scalar >::packetOp(), Eigen::internal::scalar_sqrt_op< Scalar >::packetOp(), Eigen::internal::scalar_sqrt_op< bool >::packetOp(), Eigen::internal::scalar_rsqrt_op< Scalar >::packetOp(), Eigen::internal::scalar_cos_op< Scalar >::packetOp(), Eigen::internal::scalar_sin_op< Scalar >::packetOp(), Eigen::internal::scalar_tan_op< Scalar >::packetOp(), Eigen::internal::scalar_acos_op< Scalar >::packetOp(), Eigen::internal::scalar_asin_op< Scalar >::packetOp(), Eigen::internal::scalar_atan_op< Scalar >::packetOp(), Eigen::internal::scalar_sinh_op< Scalar >::packetOp(), Eigen::internal::scalar_cosh_op< Scalar >::packetOp(), Eigen::internal::scalar_inverse_op< Scalar >::packetOp(), Eigen::internal::scalar_square_op< Scalar >::packetOp(), Eigen::internal::scalar_square_op< bool >::packetOp(), Eigen::internal::scalar_cube_op< Scalar >::packetOp(), Eigen::internal::scalar_cube_op< bool >::packetOp(), Eigen::internal::scalar_round_op< Scalar >::packetOp(), Eigen::internal::scalar_floor_op< Scalar >::packetOp(), Eigen::internal::scalar_rint_op< Scalar >::packetOp(), Eigen::internal::scalar_ceil_op< Scalar >::packetOp(), Eigen::internal::scalar_trunc_op< Scalar >::packetOp(), Eigen::internal::scalar_isnan_op< Scalar, true >::packetOp(), Eigen::internal::scalar_isinf_op< Scalar, true >::packetOp(), Eigen::internal::scalar_isfinite_op< Scalar, true >::packetOp(), Eigen::internal::scalar_boolean_not_op< Scalar >::packetOp(), Eigen::internal::scalar_bitwise_not_op< Scalar >::packetOp(), Eigen::internal::scalar_sign_op< Scalar >::packetOp(), Eigen::internal::scalar_unary_pow_op< Scalar, ExponentScalar, false, false, false, false >::packetOp(), Eigen::internal::scalar_unary_pow_op< Scalar, ExponentScalar, BaseIsInteger, true, false, false >::packetOp(), Eigen::internal::test_signbit_op< Scalar >::packetOp(), Eigen::internal::scalar_dummy_op< Scalar, Vectorize >::packetOp(), Eigen::internal::scalar_lgamma_op< Scalar >::packetOp(), Eigen::internal::scalar_digamma_op< Scalar >::packetOp(), Eigen::internal::scalar_erfc_op< Scalar >::packetOp(), Eigen::internal::scalar_ndtri_op< Scalar >::packetOp(), Eigen::internal::scalar_sum_op< LhsScalar, RhsScalar >::packetOp(), Eigen::internal::scalar_product_op< LhsScalar, RhsScalar >::packetOp(), Eigen::internal::scalar_conj_product_op< LhsScalar, RhsScalar >::packetOp(), Eigen::internal::scalar_min_op< LhsScalar, RhsScalar, NaNPropagation >::packetOp(), Eigen::internal::scalar_max_op< LhsScalar, RhsScalar, NaNPropagation >::packetOp(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_EQ, UseTypedComparators >::packetOp(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_LT, UseTypedComparators >::packetOp(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_LE, UseTypedComparators >::packetOp(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_GT, UseTypedComparators >::packetOp(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_GE, UseTypedComparators >::packetOp(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_UNORD, UseTypedComparators >::packetOp(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_NEQ, UseTypedComparators >::packetOp(), Eigen::internal::scalar_pow_op< Scalar, Exponent >::packetOp(), Eigen::internal::scalar_difference_op< LhsScalar, RhsScalar >::packetOp(), Eigen::internal::scalar_quotient_op< LhsScalar, RhsScalar >::packetOp(), Eigen::internal::scalar_boolean_and_op< Scalar >::packetOp(), Eigen::internal::scalar_boolean_or_op< Scalar >::packetOp(), Eigen::internal::scalar_boolean_xor_op< Scalar >::packetOp(), Eigen::internal::scalar_bitwise_and_op< Scalar >::packetOp(), Eigen::internal::scalar_bitwise_or_op< Scalar >::packetOp(), Eigen::internal::scalar_bitwise_xor_op< Scalar >::packetOp(), Eigen::internal::scalar_absolute_difference_op< LhsScalar, RhsScalar >::packetOp(), Eigen::internal::scalar_boolean_select_op< ThenScalar, ElseScalar, ConditionScalar >::packetOp(), Eigen::internal::scalar_igamma_op< Scalar >::packetOp(), Eigen::internal::scalar_igamma_der_a_op< Scalar >::packetOp(), Eigen::internal::scalar_igammac_op< Scalar >::packetOp(), Eigen::internal::scalar_betainc_op< Scalar >::packetOp(), Eigen::internal::pacos(), Eigen::internal::padd(), padd(), Eigen::internal::padd< Packet16b >(), Eigen::internal::padd< Packet16bf >(), Eigen::internal::padd< Packet16c >(), Eigen::internal::padd< Packet16f >(), Eigen::internal::padd< Packet16h >(), Eigen::internal::padd< Packet16i >(), Eigen::internal::padd< Packet16uc >(), Eigen::internal::padd< Packet1cd >(), Eigen::internal::padd< Packet1cf >(), Eigen::internal::padd< Packet2cd >(), Eigen::internal::padd< Packet2cf >(), Eigen::internal::padd< Packet2d >(), Eigen::internal::padd< Packet2f >(), Eigen::internal::padd< Packet2i >(), Eigen::internal::padd< Packet2l >(), Eigen::internal::padd< Packet2ui >(), Eigen::internal::padd< Packet2ul >(), Eigen::internal::padd< Packet32h >(), Eigen::internal::padd< Packet4bf >(), Eigen::internal::padd< Packet4c >(), Eigen::internal::padd< Packet4cd >(), Eigen::internal::padd< Packet4cf >(), Eigen::internal::padd< Packet4d >(), Eigen::internal::padd< Packet4f >(), Eigen::internal::padd< Packet4i >(), Eigen::internal::padd< Packet4s >(), Eigen::internal::padd< Packet4uc >(), Eigen::internal::padd< Packet4ui >(), Eigen::internal::padd< Packet4us >(), Eigen::internal::padd< Packet8bf >(), Eigen::internal::padd< Packet8c >(), Eigen::internal::padd< Packet8cf >(), Eigen::internal::padd< Packet8d >(), Eigen::internal::padd< Packet8f >(), Eigen::internal::padd< Packet8h >(), Eigen::internal::padd< Packet8i >(), Eigen::internal::padd< Packet8l >(), Eigen::internal::padd< Packet8s >(), Eigen::internal::padd< Packet8uc >(), Eigen::internal::padd< Packet8ui >(), Eigen::internal::padd< Packet8us >(), Eigen::internal::padd< PacketXf >(), Eigen::internal::padd< PacketXi >(), Eigen::internal::padds< Packet2d >(), Eigen::internal::padds< Packet4f >(), Eigen::internal::paddsub(), Eigen::internal::paddsub< Packet2d >(), Eigen::internal::paddsub< Packet2f >(), Eigen::internal::paddsub< Packet4f >(), Eigen::internal::pand(), Eigen::internal::pand< Packet16b >(), Eigen::internal::pand< Packet16c >(), Eigen::internal::pand< Packet16f >(), Eigen::internal::pand< Packet16i >(), Eigen::internal::pand< Packet16uc >(), Eigen::internal::pand< Packet1cd >(), Eigen::internal::pand< Packet1cf >(), Eigen::internal::pand< Packet2cd >(), Eigen::internal::pand< Packet2cf >(), Eigen::internal::pand< Packet2d >(), Eigen::internal::pand< Packet2f >(), Eigen::internal::pand< Packet2i >(), Eigen::internal::pand< Packet2l >(), Eigen::internal::pand< Packet2ui >(), Eigen::internal::pand< Packet2ul >(), Eigen::internal::pand< Packet4c >(), Eigen::internal::pand< Packet4cd >(), Eigen::internal::pand< Packet4cf >(), Eigen::internal::pand< Packet4d >(), Eigen::internal::pand< Packet4f >(), Eigen::internal::pand< Packet4i >(), Eigen::internal::pand< Packet4s >(), Eigen::internal::pand< Packet4uc >(), Eigen::internal::pand< Packet4ui >(), Eigen::internal::pand< Packet4us >(), Eigen::internal::pand< Packet8bf >(), Eigen::internal::pand< Packet8c >(), Eigen::internal::pand< Packet8cf >(), Eigen::internal::pand< Packet8d >(), Eigen::internal::pand< Packet8f >(), Eigen::internal::pand< Packet8i >(), Eigen::internal::pand< Packet8l >(), Eigen::internal::pand< Packet8s >(), Eigen::internal::pand< Packet8uc >(), Eigen::internal::pand< Packet8ui >(), Eigen::internal::pand< Packet8us >(), Eigen::internal::pand< PacketXf >(), Eigen::internal::pand< PacketXi >(), Eigen::internal::pandnot(), Eigen::internal::pandnot< Packet16c >(), Eigen::internal::pandnot< Packet16f >(), Eigen::internal::pandnot< Packet16i >(), Eigen::internal::pandnot< Packet16uc >(), Eigen::internal::pandnot< Packet1cd >(), Eigen::internal::pandnot< Packet1cf >(), Eigen::internal::pandnot< Packet2cd >(), Eigen::internal::pandnot< Packet2cf >(), Eigen::internal::pandnot< Packet2d >(), Eigen::internal::pandnot< Packet2f >(), Eigen::internal::pandnot< Packet2i >(), Eigen::internal::pandnot< Packet2l >(), Eigen::internal::pandnot< Packet2ui >(), Eigen::internal::pandnot< Packet2ul >(), Eigen::internal::pandnot< Packet4c >(), Eigen::internal::pandnot< Packet4cd >(), Eigen::internal::pandnot< Packet4cf >(), Eigen::internal::pandnot< Packet4d >(), Eigen::internal::pandnot< Packet4f >(), Eigen::internal::pandnot< Packet4i >(), Eigen::internal::pandnot< Packet4s >(), Eigen::internal::pandnot< Packet4uc >(), Eigen::internal::pandnot< Packet4ui >(), Eigen::internal::pandnot< Packet4us >(), Eigen::internal::pandnot< Packet8c >(), Eigen::internal::pandnot< Packet8cf >(), Eigen::internal::pandnot< Packet8d >(), Eigen::internal::pandnot< Packet8f >(), Eigen::internal::pandnot< Packet8i >(), Eigen::internal::pandnot< Packet8l >(), Eigen::internal::pandnot< Packet8s >(), Eigen::internal::pandnot< Packet8uc >(), Eigen::internal::pandnot< Packet8ui >(), Eigen::internal::pandnot< Packet8us >(), Eigen::internal::pandnot< PacketXf >(), Eigen::internal::pandnot< PacketXi >(), Eigen::internal::parg(), Eigen::internal::parithmetic_shift_right(), Eigen::internal::pasin(), Eigen::internal::patan(), Eigen::internal::patanh(), Eigen::internal::pbetainc(), Eigen::internal::pbroadcast2(), Eigen::internal::pbroadcast4(), Eigen::internal::pbroadcast4< Packet2d >(), Eigen::internal::pbroadcast4< Packet4f >(), Eigen::internal::pbroadcast4< Packet4i >(), Eigen::internal::pbroadcast4_common(), Eigen::internal::pcarg(), Eigen::internal::pcast(), Eigen::internal::pcast< float, Packet1cf >(), Eigen::internal::pcast< Packet16b, Packet16f >(), Eigen::internal::pcast< Packet16b, Packet4f >(), Eigen::internal::pcast< Packet16b, Packet8f >(), Eigen::internal::pcast< Packet16bf, Packet16f >(), Eigen::internal::pcast< Packet16c, Packet2d >(), Eigen::internal::pcast< Packet16c, Packet2l >(), Eigen::internal::pcast< Packet16c, Packet2ul >(), Eigen::internal::pcast< Packet16c, Packet4f >(), Eigen::internal::pcast< Packet16c, Packet4i >(), Eigen::internal::pcast< Packet16c, Packet4ui >(), Eigen::internal::pcast< Packet16c, Packet8s >(), Eigen::internal::pcast< Packet16c, Packet8us >(), Eigen::internal::pcast< Packet16f, Packet16b >(), Eigen::internal::pcast< Packet16f, Packet16bf >(), Eigen::internal::pcast< Packet16f, Packet16h >(), Eigen::internal::pcast< Packet16f, Packet16i >(), Eigen::internal::pcast< Packet16f, Packet8d >(), Eigen::internal::pcast< Packet16h, Packet16f >(), Eigen::internal::pcast< Packet16i, Packet16f >(), Eigen::internal::pcast< Packet16i, Packet8d >(), Eigen::internal::pcast< Packet16uc, Packet2d >(), Eigen::internal::pcast< Packet16uc, Packet2l >(), Eigen::internal::pcast< Packet16uc, Packet2ul >(), Eigen::internal::pcast< Packet16uc, Packet4f >(), Eigen::internal::pcast< Packet16uc, Packet4i >(), Eigen::internal::pcast< Packet16uc, Packet4ui >(), Eigen::internal::pcast< Packet16uc, Packet8s >(), Eigen::internal::pcast< Packet16uc, Packet8us >(), Eigen::internal::pcast< Packet2d, Packet16c >(), Eigen::internal::pcast< Packet2d, Packet16uc >(), Eigen::internal::pcast< Packet2d, Packet2l >(), Eigen::internal::pcast< Packet2d, Packet2ul >(), Eigen::internal::pcast< Packet2d, Packet4f >(), Eigen::internal::pcast< Packet2d, Packet4i >(), Eigen::internal::pcast< Packet2d, Packet4ui >(), Eigen::internal::pcast< Packet2d, Packet8s >(), Eigen::internal::pcast< Packet2d, Packet8us >(), Eigen::internal::pcast< Packet2f, Packet2cf >(), Eigen::internal::pcast< Packet2f, Packet2i >(), Eigen::internal::pcast< Packet2f, Packet2l >(), Eigen::internal::pcast< Packet2f, Packet2ui >(), Eigen::internal::pcast< Packet2f, Packet2ul >(), Eigen::internal::pcast< Packet2f, Packet4s >(), Eigen::internal::pcast< Packet2f, Packet4us >(), Eigen::internal::pcast< Packet2f, Packet8c >(), Eigen::internal::pcast< Packet2f, Packet8uc >(), Eigen::internal::pcast< Packet2i, Packet2f >(), Eigen::internal::pcast< Packet2i, Packet2l >(), Eigen::internal::pcast< Packet2i, Packet2ul >(), Eigen::internal::pcast< Packet2i, Packet4s >(), Eigen::internal::pcast< Packet2i, Packet4us >(), Eigen::internal::pcast< Packet2i, Packet8c >(), Eigen::internal::pcast< Packet2i, Packet8uc >(), Eigen::internal::pcast< Packet2l, Packet16c >(), Eigen::internal::pcast< Packet2l, Packet16uc >(), Eigen::internal::pcast< Packet2l, Packet2d >(), Eigen::internal::pcast< Packet2l, Packet2f >(), Eigen::internal::pcast< Packet2l, Packet2i >(), Eigen::internal::pcast< Packet2l, Packet2ui >(), Eigen::internal::pcast< Packet2l, Packet4c >(), Eigen::internal::pcast< Packet2l, Packet4f >(), Eigen::internal::pcast< Packet2l, Packet4i >(), Eigen::internal::pcast< Packet2l, Packet4s >(), Eigen::internal::pcast< Packet2l, Packet4uc >(), Eigen::internal::pcast< Packet2l, Packet4ui >(), Eigen::internal::pcast< Packet2l, Packet4us >(), Eigen::internal::pcast< Packet2l, Packet8c >(), Eigen::internal::pcast< Packet2l, Packet8s >(), Eigen::internal::pcast< Packet2l, Packet8uc >(), Eigen::internal::pcast< Packet2l, Packet8us >(), Eigen::internal::pcast< Packet2ui, Packet2f >(), Eigen::internal::pcast< Packet2ui, Packet2l >(), Eigen::internal::pcast< Packet2ui, Packet2ul >(), Eigen::internal::pcast< Packet2ui, Packet4s >(), Eigen::internal::pcast< Packet2ui, Packet4us >(), Eigen::internal::pcast< Packet2ui, Packet8c >(), Eigen::internal::pcast< Packet2ui, Packet8uc >(), Eigen::internal::pcast< Packet2ul, Packet16c >(), Eigen::internal::pcast< Packet2ul, Packet16uc >(), Eigen::internal::pcast< Packet2ul, Packet2d >(), Eigen::internal::pcast< Packet2ul, Packet2f >(), Eigen::internal::pcast< Packet2ul, Packet2i >(), Eigen::internal::pcast< Packet2ul, Packet2ui >(), Eigen::internal::pcast< Packet2ul, Packet4c >(), Eigen::internal::pcast< Packet2ul, Packet4f >(), Eigen::internal::pcast< Packet2ul, Packet4i >(), Eigen::internal::pcast< Packet2ul, Packet4s >(), Eigen::internal::pcast< Packet2ul, Packet4uc >(), Eigen::internal::pcast< Packet2ul, Packet4ui >(), Eigen::internal::pcast< Packet2ul, Packet4us >(), Eigen::internal::pcast< Packet2ul, Packet8c >(), Eigen::internal::pcast< Packet2ul, Packet8s >(), Eigen::internal::pcast< Packet2ul, Packet8uc >(), Eigen::internal::pcast< Packet2ul, Packet8us >(), Eigen::internal::pcast< Packet4c, Packet4f >(), Eigen::internal::pcast< Packet4c, Packet4i >(), Eigen::internal::pcast< Packet4c, Packet4s >(), Eigen::internal::pcast< Packet4c, Packet4ui >(), Eigen::internal::pcast< Packet4c, Packet4us >(), Eigen::internal::pcast< Packet4d, Packet4f >(), Eigen::internal::pcast< Packet4d, Packet4i >(), Eigen::internal::pcast< Packet4d, Packet8f >(), Eigen::internal::pcast< Packet4d, Packet8i >(), Eigen::internal::pcast< Packet4f, Packet16b >(), Eigen::internal::pcast< Packet4f, Packet16c >(), Eigen::internal::pcast< Packet4f, Packet16uc >(), Eigen::internal::pcast< Packet4f, Packet2d >(), Eigen::internal::pcast< Packet4f, Packet2l >(), Eigen::internal::pcast< Packet4f, Packet2ul >(), Eigen::internal::pcast< Packet4f, Packet4c >(), Eigen::internal::pcast< Packet4f, Packet4d >(), Eigen::internal::pcast< Packet4f, Packet4i >(), Eigen::internal::pcast< Packet4f, Packet4s >(), Eigen::internal::pcast< Packet4f, Packet4uc >(), Eigen::internal::pcast< Packet4f, Packet4ui >(), Eigen::internal::pcast< Packet4f, Packet4us >(), Eigen::internal::pcast< Packet4f, Packet8bf >(), Eigen::internal::pcast< Packet4f, Packet8c >(), Eigen::internal::pcast< Packet4f, Packet8s >(), Eigen::internal::pcast< Packet4f, Packet8uc >(), Eigen::internal::pcast< Packet4f, Packet8us >(), Eigen::internal::pcast< Packet4i, Packet16c >(), Eigen::internal::pcast< Packet4i, Packet16uc >(), Eigen::internal::pcast< Packet4i, Packet2d >(), Eigen::internal::pcast< Packet4i, Packet2l >(), Eigen::internal::pcast< Packet4i, Packet2ul >(), Eigen::internal::pcast< Packet4i, Packet4c >(), Eigen::internal::pcast< Packet4i, Packet4d >(), Eigen::internal::pcast< Packet4i, Packet4f >(), Eigen::internal::pcast< Packet4i, Packet4s >(), Eigen::internal::pcast< Packet4i, Packet4uc >(), Eigen::internal::pcast< Packet4i, Packet4us >(), Eigen::internal::pcast< Packet4i, Packet8c >(), Eigen::internal::pcast< Packet4i, Packet8s >(), Eigen::internal::pcast< Packet4i, Packet8uc >(), Eigen::internal::pcast< Packet4i, Packet8us >(), Eigen::internal::pcast< Packet4s, Packet2f >(), Eigen::internal::pcast< Packet4s, Packet2i >(), Eigen::internal::pcast< Packet4s, Packet2ui >(), Eigen::internal::pcast< Packet4s, Packet4c >(), Eigen::internal::pcast< Packet4s, Packet4f >(), Eigen::internal::pcast< Packet4s, Packet4i >(), Eigen::internal::pcast< Packet4s, Packet4uc >(), Eigen::internal::pcast< Packet4s, Packet4ui >(), Eigen::internal::pcast< Packet4s, Packet8c >(), Eigen::internal::pcast< Packet4s, Packet8uc >(), Eigen::internal::pcast< Packet4uc, Packet4f >(), Eigen::internal::pcast< Packet4uc, Packet4i >(), Eigen::internal::pcast< Packet4uc, Packet4s >(), Eigen::internal::pcast< Packet4uc, Packet4ui >(), Eigen::internal::pcast< Packet4uc, Packet4us >(), Eigen::internal::pcast< Packet4ui, Packet16c >(), Eigen::internal::pcast< Packet4ui, Packet16uc >(), Eigen::internal::pcast< Packet4ui, Packet2d >(), Eigen::internal::pcast< Packet4ui, Packet2l >(), Eigen::internal::pcast< Packet4ui, Packet2ul >(), Eigen::internal::pcast< Packet4ui, Packet4c >(), Eigen::internal::pcast< Packet4ui, Packet4f >(), Eigen::internal::pcast< Packet4ui, Packet4s >(), Eigen::internal::pcast< Packet4ui, Packet4uc >(), Eigen::internal::pcast< Packet4ui, Packet4us >(), Eigen::internal::pcast< Packet4ui, Packet8c >(), Eigen::internal::pcast< Packet4ui, Packet8s >(), Eigen::internal::pcast< Packet4ui, Packet8uc >(), Eigen::internal::pcast< Packet4ui, Packet8us >(), Eigen::internal::pcast< Packet4us, Packet2f >(), Eigen::internal::pcast< Packet4us, Packet2i >(), Eigen::internal::pcast< Packet4us, Packet2ui >(), Eigen::internal::pcast< Packet4us, Packet4c >(), Eigen::internal::pcast< Packet4us, Packet4f >(), Eigen::internal::pcast< Packet4us, Packet4i >(), Eigen::internal::pcast< Packet4us, Packet4uc >(), Eigen::internal::pcast< Packet4us, Packet4ui >(), Eigen::internal::pcast< Packet4us, Packet8c >(), Eigen::internal::pcast< Packet4us, Packet8uc >(), Eigen::internal::pcast< Packet8bf, Packet4f >(), Eigen::internal::pcast< Packet8bf, Packet8f >(), Eigen::internal::pcast< Packet8bf, Packet8us >(), Eigen::internal::pcast< Packet8c, Packet2f >(), Eigen::internal::pcast< Packet8c, Packet2i >(), Eigen::internal::pcast< Packet8c, Packet2ui >(), Eigen::internal::pcast< Packet8c, Packet4i >(), Eigen::internal::pcast< Packet8c, Packet4s >(), Eigen::internal::pcast< Packet8c, Packet4us >(), Eigen::internal::pcast< Packet8c, Packet8s >(), Eigen::internal::pcast< Packet8c, Packet8us >(), Eigen::internal::pcast< Packet8d, Packet16f >(), Eigen::internal::pcast< Packet8d, Packet16i >(), Eigen::internal::pcast< Packet8d, Packet8f >(), Eigen::internal::pcast< Packet8d, Packet8i >(), Eigen::internal::pcast< Packet8d, Packet8l >(), Eigen::internal::pcast< Packet8f, Packet16b >(), Eigen::internal::pcast< Packet8f, Packet4d >(), Eigen::internal::pcast< Packet8f, Packet8bf >(), Eigen::internal::pcast< Packet8f, Packet8d >(), Eigen::internal::pcast< Packet8f, Packet8h >(), Eigen::internal::pcast< Packet8f, Packet8i >(), Eigen::internal::pcast< Packet8h, Packet8f >(), Eigen::internal::pcast< Packet8i, Packet4d >(), Eigen::internal::pcast< Packet8i, Packet8d >(), Eigen::internal::pcast< Packet8i, Packet8f >(), Eigen::internal::pcast< Packet8l, Packet8d >(), Eigen::internal::pcast< Packet8s, Packet16c >(), Eigen::internal::pcast< Packet8s, Packet16uc >(), Eigen::internal::pcast< Packet8s, Packet2d >(), Eigen::internal::pcast< Packet8s, Packet2l >(), Eigen::internal::pcast< Packet8s, Packet2ul >(), Eigen::internal::pcast< Packet8s, Packet4f >(), Eigen::internal::pcast< Packet8s, Packet4i >(), Eigen::internal::pcast< Packet8s, Packet4ui >(), Eigen::internal::pcast< Packet8s, Packet8c >(), Eigen::internal::pcast< Packet8s, Packet8uc >(), Eigen::internal::pcast< Packet8uc, Packet2f >(), Eigen::internal::pcast< Packet8uc, Packet2i >(), Eigen::internal::pcast< Packet8uc, Packet2ui >(), Eigen::internal::pcast< Packet8uc, Packet4ui >(), Eigen::internal::pcast< Packet8uc, Packet8s >(), Eigen::internal::pcast< Packet8uc, Packet8us >(), Eigen::internal::pcast< Packet8us, Packet16c >(), Eigen::internal::pcast< Packet8us, Packet16uc >(), Eigen::internal::pcast< Packet8us, Packet2d >(), Eigen::internal::pcast< Packet8us, Packet2l >(), Eigen::internal::pcast< Packet8us, Packet2ul >(), Eigen::internal::pcast< Packet8us, Packet4f >(), Eigen::internal::pcast< Packet8us, Packet4i >(), Eigen::internal::pcast< Packet8us, Packet4ui >(), Eigen::internal::pcast< Packet8us, Packet8bf >(), Eigen::internal::pcast< Packet8us, Packet8c >(), Eigen::internal::pcast< Packet8us, Packet8uc >(), Eigen::internal::pcast< PacketXf, PacketXi >(), Eigen::internal::pcast< PacketXi, PacketXf >(), Eigen::internal::pcbrt(), Eigen::internal::pceil(), Eigen::internal::pceil< Packet16bf >(), Eigen::internal::pceil< Packet16f >(), Eigen::internal::pceil< Packet16h >(), Eigen::internal::pceil< Packet2d >(), Eigen::internal::pceil< Packet32h >(), Eigen::internal::pceil< Packet4bf >(), Eigen::internal::pceil< Packet4d >(), Eigen::internal::pceil< Packet4f >(), Eigen::internal::pceil< Packet8bf >(), Eigen::internal::pceil< Packet8d >(), Eigen::internal::pceil< Packet8f >(), Eigen::internal::pceil< Packet8h >(), Eigen::internal::pcmp_eq(), Eigen::internal::pcmp_eq< Packet16c >(), Eigen::internal::pcmp_eq< Packet16uc >(), Eigen::internal::pcmp_eq< Packet2d >(), Eigen::internal::pcmp_eq< Packet2f >(), Eigen::internal::pcmp_eq< Packet2i >(), Eigen::internal::pcmp_eq< Packet2l >(), Eigen::internal::pcmp_eq< Packet2ui >(), Eigen::internal::pcmp_eq< Packet2ul >(), Eigen::internal::pcmp_eq< Packet4bf >(), Eigen::internal::pcmp_eq< Packet4c >(), Eigen::internal::pcmp_eq< Packet4f >(), Eigen::internal::pcmp_eq< Packet4i >(), Eigen::internal::pcmp_eq< Packet4s >(), Eigen::internal::pcmp_eq< Packet4uc >(), Eigen::internal::pcmp_eq< Packet4ui >(), Eigen::internal::pcmp_eq< Packet4us >(), Eigen::internal::pcmp_eq< Packet8c >(), Eigen::internal::pcmp_eq< Packet8s >(), Eigen::internal::pcmp_eq< Packet8uc >(), Eigen::internal::pcmp_eq< Packet8us >(), Eigen::internal::pcmp_eq< PacketXf >(), Eigen::internal::pcmp_eq< PacketXi >(), Eigen::internal::pcmp_le(), Eigen::internal::pcmp_le< Packet16c >(), Eigen::internal::pcmp_le< Packet16uc >(), Eigen::internal::pcmp_le< Packet2d >(), Eigen::internal::pcmp_le< Packet2f >(), Eigen::internal::pcmp_le< Packet2i >(), Eigen::internal::pcmp_le< Packet2l >(), Eigen::internal::pcmp_le< Packet2ui >(), Eigen::internal::pcmp_le< Packet2ul >(), Eigen::internal::pcmp_le< Packet4bf >(), Eigen::internal::pcmp_le< Packet4c >(), Eigen::internal::pcmp_le< Packet4f >(), Eigen::internal::pcmp_le< Packet4i >(), Eigen::internal::pcmp_le< Packet4s >(), Eigen::internal::pcmp_le< Packet4uc >(), Eigen::internal::pcmp_le< Packet4ui >(), Eigen::internal::pcmp_le< Packet4us >(), Eigen::internal::pcmp_le< Packet8c >(), Eigen::internal::pcmp_le< Packet8s >(), Eigen::internal::pcmp_le< Packet8uc >(), Eigen::internal::pcmp_le< Packet8us >(), Eigen::internal::pcmp_le< PacketXf >(), Eigen::internal::pcmp_le< PacketXi >(), Eigen::internal::pcmp_lt(), Eigen::internal::pcmp_lt< Packet16c >(), Eigen::internal::pcmp_lt< Packet16uc >(), Eigen::internal::pcmp_lt< Packet2d >(), Eigen::internal::pcmp_lt< Packet2f >(), Eigen::internal::pcmp_lt< Packet2i >(), Eigen::internal::pcmp_lt< Packet2l >(), Eigen::internal::pcmp_lt< Packet2ui >(), Eigen::internal::pcmp_lt< Packet2ul >(), Eigen::internal::pcmp_lt< Packet4bf >(), Eigen::internal::pcmp_lt< Packet4c >(), Eigen::internal::pcmp_lt< Packet4f >(), Eigen::internal::pcmp_lt< Packet4i >(), Eigen::internal::pcmp_lt< Packet4s >(), Eigen::internal::pcmp_lt< Packet4uc >(), Eigen::internal::pcmp_lt< Packet4ui >(), Eigen::internal::pcmp_lt< Packet4us >(), Eigen::internal::pcmp_lt< Packet8c >(), Eigen::internal::pcmp_lt< Packet8s >(), Eigen::internal::pcmp_lt< Packet8uc >(), Eigen::internal::pcmp_lt< Packet8us >(), Eigen::internal::pcmp_lt< PacketXf >(), Eigen::internal::pcmp_lt< PacketXi >(), Eigen::internal::pcmp_lt_or_nan(), Eigen::internal::pcmp_lt_or_nan< Packet2d >(), Eigen::internal::pcmp_lt_or_nan< Packet2f >(), Eigen::internal::pcmp_lt_or_nan< Packet4bf >(), Eigen::internal::pcmp_lt_or_nan< Packet4f >(), Eigen::internal::pcmp_lt_or_nan< PacketXf >(), Eigen::internal::pconj(), pconj2(), Eigen::internal::pconj< Packet32h >(), pconjinv(), Eigen::internal::pcos(), Eigen::internal::pcos< Packet32h >(), Eigen::internal::pcos< Packet8bf >(), Eigen::internal::pcosh(), pcplxconjflip(), Eigen::internal::pcplxflip(), pcplxflip2(), Eigen::internal::pcplxflip< Packet1cf >(), pcplxflipconj(), pcplxflipnegate(), HGridOptimiser::pdfIntCell(), Eigen::internal::pdigamma(), Eigen::internal::pdiv(), Eigen::internal::pdiv< Packet16bf >(), Eigen::internal::pdiv< Packet16f >(), Eigen::internal::pdiv< Packet16h >(), Eigen::internal::pdiv< Packet16i >(), Eigen::internal::pdiv< Packet16uc >(), Eigen::internal::pdiv< Packet1cd >(), Eigen::internal::pdiv< Packet1cf >(), Eigen::internal::pdiv< Packet2cd >(), Eigen::internal::pdiv< Packet2cf >(), Eigen::internal::pdiv< Packet2d >(), Eigen::internal::pdiv< Packet2f >(), Eigen::internal::pdiv< Packet2l >(), Eigen::internal::pdiv< Packet2ul >(), Eigen::internal::pdiv< Packet32h >(), Eigen::internal::pdiv< Packet4bf >(), Eigen::internal::pdiv< Packet4cd >(), Eigen::internal::pdiv< Packet4cf >(), Eigen::internal::pdiv< Packet4d >(), Eigen::internal::pdiv< Packet4f >(), Eigen::internal::pdiv< Packet4i >(), Eigen::internal::pdiv< Packet4ui >(), Eigen::internal::pdiv< Packet8bf >(), Eigen::internal::pdiv< Packet8cf >(), Eigen::internal::pdiv< Packet8d >(), Eigen::internal::pdiv< Packet8f >(), Eigen::internal::pdiv< Packet8h >(), Eigen::internal::pdiv< Packet8i >(), Eigen::internal::pdiv< Packet8s >(), Eigen::internal::pdiv< Packet8us >(), Eigen::internal::pdiv< PacketXf >(), Eigen::internal::pdiv< PacketXi >(), Eigen::internal::pdiv_float_common(), Eigen::internal::perf(), Eigen::internal::perfc(), Eigen::internal::pexp(), Eigen::internal::pexp2(), Eigen::internal::pexp2< Packet8bf >(), Eigen::internal::pexp< Packet1cf >(), Eigen::internal::pexp< Packet2cf >(), Eigen::internal::pexp< Packet32h >(), Eigen::internal::pexp< Packet4cf >(), Eigen::internal::pexp< Packet8bf >(), Eigen::internal::pexp< Packet8cf >(), Eigen::internal::pexp_complex(), Eigen::internal::pexpm1(), Eigen::internal::pexpm1< Packet32h >(), Eigen::internal::pfirst(), Eigen::internal::pfirst< Packet16b >(), Eigen::internal::pfirst< Packet16c >(), Eigen::internal::pfirst< Packet16f >(), Eigen::internal::pfirst< Packet16i >(), Eigen::internal::pfirst< Packet16uc >(), Eigen::internal::pfirst< Packet1cd >(), Eigen::internal::pfirst< Packet1cf >(), Eigen::internal::pfirst< Packet2cd >(), Eigen::internal::pfirst< Packet2cf >(), Eigen::internal::pfirst< Packet2d >(), Eigen::internal::pfirst< Packet2f >(), Eigen::internal::pfirst< Packet2i >(), Eigen::internal::pfirst< Packet2l >(), Eigen::internal::pfirst< Packet2ui >(), Eigen::internal::pfirst< Packet2ul >(), Eigen::internal::pfirst< Packet4c >(), Eigen::internal::pfirst< Packet4cd >(), Eigen::internal::pfirst< Packet4cf >(), Eigen::internal::pfirst< Packet4d >(), Eigen::internal::pfirst< Packet4f >(), Eigen::internal::pfirst< Packet4i >(), Eigen::internal::pfirst< Packet4s >(), Eigen::internal::pfirst< Packet4uc >(), Eigen::internal::pfirst< Packet4ui >(), Eigen::internal::pfirst< Packet4us >(), Eigen::internal::pfirst< Packet8c >(), Eigen::internal::pfirst< Packet8cf >(), Eigen::internal::pfirst< Packet8d >(), Eigen::internal::pfirst< Packet8f >(), Eigen::internal::pfirst< Packet8i >(), Eigen::internal::pfirst< Packet8l >(), Eigen::internal::pfirst< Packet8s >(), Eigen::internal::pfirst< Packet8uc >(), Eigen::internal::pfirst< Packet8ui >(), Eigen::internal::pfirst< Packet8us >(), Eigen::internal::pfirst< PacketXf >(), Eigen::internal::pfirst< PacketXi >(), Eigen::internal::pfloor(), Eigen::internal::pfloor< Packet16bf >(), Eigen::internal::pfloor< Packet16f >(), Eigen::internal::pfloor< Packet16h >(), Eigen::internal::pfloor< Packet2d >(), Eigen::internal::pfloor< Packet32h >(), Eigen::internal::pfloor< Packet4bf >(), Eigen::internal::pfloor< Packet4d >(), Eigen::internal::pfloor< Packet4f >(), Eigen::internal::pfloor< Packet8bf >(), Eigen::internal::pfloor< Packet8d >(), Eigen::internal::pfloor< Packet8f >(), Eigen::internal::pfloor< Packet8h >(), Eigen::internal::pfloor< PacketXf >(), Eigen::internal::pfrexp(), Eigen::internal::pfrexp< Packet16f >(), Eigen::internal::pfrexp< Packet2d >(), Eigen::internal::pfrexp< Packet2f >(), Eigen::internal::pfrexp< Packet32h >(), Eigen::internal::pfrexp< Packet4d >(), Eigen::internal::pfrexp< Packet4f >(), Eigen::internal::pfrexp< Packet8bf >(), Eigen::internal::pfrexp< Packet8d >(), Eigen::internal::pfrexp< Packet8f >(), Eigen::internal::pfrexp< PacketXf >(), Eigen::internal::pfrexp_generic(), Eigen::internal::pfrexp_generic_get_biased_exponent(), Eigen::internal::pgather_common(), Eigen::internal::pgerMMA(), Eigen::internal::phypot_complex(), Eigen::internal::pigamma(), Eigen::internal::pigamma_der_a(), Eigen::internal::pigammac(), SolidProblem< ELEMENT_TYPE >::pinBoundaries(), Eigen::internal::pisinf(), Eigen::internal::pisnan(), Eigen::internal::plain_enum_max(), Eigen::internal::plain_enum_min(), Eigen::internal::pldexp(), Eigen::internal::pldexp< Packet16f >(), Eigen::internal::pldexp< Packet2d >(), Eigen::internal::pldexp< Packet2f >(), Eigen::internal::pldexp< Packet32h >(), Eigen::internal::pldexp< Packet4d >(), Eigen::internal::pldexp< Packet4f >(), Eigen::internal::pldexp< Packet8bf >(), Eigen::internal::pldexp< Packet8d >(), Eigen::internal::pldexp< Packet8f >(), Eigen::internal::pldexp< PacketXf >(), Eigen::internal::pldexp_fast(), Eigen::internal::pldexp_fast< Packet2d >(), Eigen::internal::pldexp_fast< Packet4d >(), Eigen::internal::pldexp_generic(), Eigen::internal::plgamma(), Eigen::internal::pload1(), Eigen::internal::ploaddup< Packet16bf >(), Eigen::internal::ploaddup< Packet16h >(), Eigen::internal::ploaddup< Packet32h >(), Eigen::internal::ploaddup< Packet4c >(), Eigen::internal::ploaddup< Packet4cf >(), Eigen::internal::ploaddup< Packet4uc >(), Eigen::internal::ploaddup< Packet8c >(), Eigen::internal::ploaddup< Packet8h >(), Eigen::internal::ploaddup< Packet8i >(), Eigen::internal::ploaddup< Packet8uc >(), Eigen::internal::ploaddup< Packet8ui >(), Eigen::internal::ploadquad(), Eigen::internal::ploadquad< Packet32h >(), Eigen::internal::ploadquad< Packet8h >(), Eigen::internal::plog(), Eigen::internal::plog10(), Eigen::internal::plog1p(), Eigen::internal::plog1p< Packet32h >(), Eigen::internal::plog2(), Eigen::internal::plog2< Packet32h >(), Eigen::internal::plog< Packet1cd >(), Eigen::internal::plog< Packet1cf >(), Eigen::internal::plog< Packet2cd >(), Eigen::internal::plog< Packet2cf >(), Eigen::internal::plog< Packet32h >(), Eigen::internal::plog< Packet4cd >(), Eigen::internal::plog< Packet4cf >(), Eigen::internal::plog< Packet8bf >(), Eigen::internal::plog< Packet8cf >(), Eigen::internal::plogical_shift_left(), Eigen::internal::plogical_shift_right(), Eigen::internal::plset(), Eigen::internal::plset< Packet16bf >(), Eigen::internal::plset< Packet16c >(), Eigen::internal::plset< Packet16f >(), Eigen::internal::plset< Packet16h >(), Eigen::internal::plset< Packet16i >(), Eigen::internal::plset< Packet16uc >(), Eigen::internal::plset< Packet2d >(), Eigen::internal::plset< Packet2f >(), Eigen::internal::plset< Packet2i >(), Eigen::internal::plset< Packet2l >(), Eigen::internal::plset< Packet2ui >(), Eigen::internal::plset< Packet2ul >(), Eigen::internal::plset< Packet32h >(), Eigen::internal::plset< Packet4bf >(), Eigen::internal::plset< Packet4c >(), Eigen::internal::plset< Packet4d >(), Eigen::internal::plset< Packet4f >(), Eigen::internal::plset< Packet4i >(), Eigen::internal::plset< Packet4s >(), Eigen::internal::plset< Packet4uc >(), Eigen::internal::plset< Packet4ui >(), Eigen::internal::plset< Packet4us >(), Eigen::internal::plset< Packet8bf >(), Eigen::internal::plset< Packet8c >(), Eigen::internal::plset< Packet8d >(), Eigen::internal::plset< Packet8f >(), Eigen::internal::plset< Packet8h >(), Eigen::internal::plset< Packet8i >(), Eigen::internal::plset< Packet8l >(), Eigen::internal::plset< Packet8s >(), Eigen::internal::plset< Packet8uc >(), Eigen::internal::plset< Packet8ui >(), Eigen::internal::plset< Packet8us >(), Eigen::internal::plset< PacketXf >(), Eigen::internal::plset< PacketXi >(), Eigen::internal::pmadd(), Eigen::internal::pmadd< Packet1cd >(), Eigen::internal::pmadd< Packet2cf >(), pmadd_complex_complex(), pmadd_complex_real(), Eigen::internal::pmax(), Eigen::internal::pmax< Packet16bf >(), Eigen::internal::pmax< Packet16c >(), Eigen::internal::pmax< Packet16f >(), Eigen::internal::pmax< Packet16h >(), Eigen::internal::pmax< Packet16i >(), Eigen::internal::pmax< Packet16uc >(), Eigen::internal::pmax< Packet2d >(), Eigen::internal::pmax< Packet2f >(), Eigen::internal::pmax< Packet2i >(), Eigen::internal::pmax< Packet2l >(), Eigen::internal::pmax< Packet2ui >(), Eigen::internal::pmax< Packet2ul >(), Eigen::internal::pmax< Packet32h >(), Eigen::internal::pmax< Packet4bf >(), Eigen::internal::pmax< Packet4c >(), Eigen::internal::pmax< Packet4d >(), Eigen::internal::pmax< Packet4f >(), Eigen::internal::pmax< Packet4i >(), Eigen::internal::pmax< Packet4s >(), Eigen::internal::pmax< Packet4uc >(), Eigen::internal::pmax< Packet4ui >(), Eigen::internal::pmax< Packet4us >(), Eigen::internal::pmax< Packet8bf >(), Eigen::internal::pmax< Packet8c >(), Eigen::internal::pmax< Packet8d >(), Eigen::internal::pmax< Packet8f >(), Eigen::internal::pmax< Packet8h >(), Eigen::internal::pmax< Packet8i >(), Eigen::internal::pmax< Packet8l >(), Eigen::internal::pmax< Packet8s >(), Eigen::internal::pmax< Packet8uc >(), Eigen::internal::pmax< Packet8ui >(), Eigen::internal::pmax< Packet8us >(), Eigen::internal::pmax< PacketXf >(), Eigen::internal::pmax< PacketXi >(), Eigen::internal::pmax< PropagateNaN, Packet16f >(), Eigen::internal::pmax< PropagateNaN, Packet2d >(), Eigen::internal::pmax< PropagateNaN, Packet2f >(), Eigen::internal::pmax< PropagateNaN, Packet4bf >(), Eigen::internal::pmax< PropagateNaN, Packet4d >(), Eigen::internal::pmax< PropagateNaN, Packet4f >(), Eigen::internal::pmax< PropagateNaN, Packet8d >(), Eigen::internal::pmax< PropagateNaN, Packet8f >(), Eigen::internal::pmax< PropagateNaN, PacketXf >(), Eigen::internal::pmax< PropagateNumbers, Packet16f >(), Eigen::internal::pmax< PropagateNumbers, Packet2d >(), Eigen::internal::pmax< PropagateNumbers, Packet4bf >(), Eigen::internal::pmax< PropagateNumbers, Packet4d >(), Eigen::internal::pmax< PropagateNumbers, Packet4f >(), Eigen::internal::pmax< PropagateNumbers, Packet8d >(), Eigen::internal::pmax< PropagateNumbers, Packet8f >(), Eigen::internal::pmax< PropagateNumbers, PacketXf >(), Eigen::internal::pmin(), Eigen::internal::pmin< Packet16bf >(), Eigen::internal::pmin< Packet16c >(), Eigen::internal::pmin< Packet16f >(), Eigen::internal::pmin< Packet16h >(), Eigen::internal::pmin< Packet16i >(), Eigen::internal::pmin< Packet16uc >(), Eigen::internal::pmin< Packet2d >(), Eigen::internal::pmin< Packet2f >(), Eigen::internal::pmin< Packet2i >(), Eigen::internal::pmin< Packet2l >(), Eigen::internal::pmin< Packet2ui >(), Eigen::internal::pmin< Packet2ul >(), Eigen::internal::pmin< Packet32h >(), Eigen::internal::pmin< Packet4bf >(), Eigen::internal::pmin< Packet4c >(), Eigen::internal::pmin< Packet4d >(), Eigen::internal::pmin< Packet4f >(), Eigen::internal::pmin< Packet4i >(), Eigen::internal::pmin< Packet4s >(), Eigen::internal::pmin< Packet4uc >(), Eigen::internal::pmin< Packet4ui >(), Eigen::internal::pmin< Packet4us >(), Eigen::internal::pmin< Packet8bf >(), Eigen::internal::pmin< Packet8c >(), Eigen::internal::pmin< Packet8d >(), Eigen::internal::pmin< Packet8f >(), Eigen::internal::pmin< Packet8h >(), Eigen::internal::pmin< Packet8i >(), Eigen::internal::pmin< Packet8l >(), Eigen::internal::pmin< Packet8s >(), Eigen::internal::pmin< Packet8uc >(), Eigen::internal::pmin< Packet8ui >(), Eigen::internal::pmin< Packet8us >(), Eigen::internal::pmin< PacketXf >(), Eigen::internal::pmin< PacketXi >(), Eigen::internal::pmin< PropagateNaN, Packet16f >(), Eigen::internal::pmin< PropagateNaN, Packet2d >(), Eigen::internal::pmin< PropagateNaN, Packet2f >(), Eigen::internal::pmin< PropagateNaN, Packet4bf >(), Eigen::internal::pmin< PropagateNaN, Packet4d >(), Eigen::internal::pmin< PropagateNaN, Packet4f >(), Eigen::internal::pmin< PropagateNaN, Packet8d >(), Eigen::internal::pmin< PropagateNaN, Packet8f >(), Eigen::internal::pmin< PropagateNaN, PacketXf >(), Eigen::internal::pmin< PropagateNumbers, Packet16f >(), Eigen::internal::pmin< PropagateNumbers, Packet2d >(), Eigen::internal::pmin< PropagateNumbers, Packet4bf >(), Eigen::internal::pmin< PropagateNumbers, Packet4d >(), Eigen::internal::pmin< PropagateNumbers, Packet4f >(), Eigen::internal::pmin< PropagateNumbers, Packet8d >(), Eigen::internal::pmin< PropagateNumbers, Packet8f >(), Eigen::internal::pmin< PropagateNumbers, PacketXf >(), Eigen::internal::pminmax_propagate_nan(), Eigen::internal::pminmax_propagate_numbers(), PMLHelmholtzMGProblem< ELEMENT >::PMLHelmholtzMGProblem(), PMLProblem< ELEMENT >::PMLProblem(), Eigen::internal::pmsub(), Eigen::internal::Packet2cf::pmul(), Eigen::internal::pmul(), Eigen::internal::pmul< Packet16b >(), Eigen::internal::pmul< Packet16bf >(), Eigen::internal::pmul< Packet16c >(), Eigen::internal::pmul< Packet16f >(), Eigen::internal::pmul< Packet16h >(), Eigen::internal::pmul< Packet16i >(), Eigen::internal::pmul< Packet16uc >(), Eigen::internal::pmul< Packet1cd >(), Eigen::internal::pmul< Packet1cf >(), Eigen::internal::pmul< Packet2cf >(), Eigen::internal::pmul< Packet2d >(), Eigen::internal::pmul< Packet2f >(), Eigen::internal::pmul< Packet2i >(), Eigen::internal::pmul< Packet2l >(), Eigen::internal::pmul< Packet2ui >(), Eigen::internal::pmul< Packet2ul >(), Eigen::internal::pmul< Packet32h >(), Eigen::internal::pmul< Packet4bf >(), Eigen::internal::pmul< Packet4c >(), Eigen::internal::pmul< Packet4cd >(), Eigen::internal::pmul< Packet4d >(), Eigen::internal::pmul< Packet4f >(), Eigen::internal::pmul< Packet4i >(), Eigen::internal::pmul< Packet4s >(), Eigen::internal::pmul< Packet4uc >(), Eigen::internal::pmul< Packet4ui >(), Eigen::internal::pmul< Packet4us >(), Eigen::internal::pmul< Packet8bf >(), Eigen::internal::pmul< Packet8c >(), Eigen::internal::pmul< Packet8cf >(), Eigen::internal::pmul< Packet8d >(), Eigen::internal::pmul< Packet8f >(), Eigen::internal::pmul< Packet8h >(), Eigen::internal::pmul< Packet8i >(), Eigen::internal::pmul< Packet8l >(), Eigen::internal::pmul< Packet8s >(), Eigen::internal::pmul< Packet8uc >(), Eigen::internal::pmul< Packet8ui >(), Eigen::internal::pmul< Packet8us >(), Eigen::internal::pmul< PacketXf >(), Eigen::internal::pmul< PacketXi >(), Eigen::internal::pndtri(), Eigen::internal::pnegate(), pnegate2(), Eigen::internal::pnegate< Packet32h >(), Eigen::internal::pnegate< Packet4bf >(), Eigen::internal::pnegate< Packet8bf >(), Eigen::internal::pnmadd(), Eigen::internal::pnmsub(), Eigen::internal::pnot(), PointIsAboveCurve(), Eigen::internal::por(), Eigen::internal::por< Packet16b >(), Eigen::internal::por< Packet16c >(), Eigen::internal::por< Packet16f >(), Eigen::internal::por< Packet16i >(), Eigen::internal::por< Packet16uc >(), Eigen::internal::por< Packet1cd >(), Eigen::internal::por< Packet1cf >(), Eigen::internal::por< Packet2cd >(), Eigen::internal::por< Packet2cf >(), Eigen::internal::por< Packet2d >(), Eigen::internal::por< Packet2f >(), Eigen::internal::por< Packet2i >(), Eigen::internal::por< Packet2l >(), Eigen::internal::por< Packet2ui >(), Eigen::internal::por< Packet2ul >(), Eigen::internal::por< Packet4c >(), Eigen::internal::por< Packet4cd >(), Eigen::internal::por< Packet4cf >(), Eigen::internal::por< Packet4d >(), Eigen::internal::por< Packet4f >(), Eigen::internal::por< Packet4i >(), Eigen::internal::por< Packet4s >(), Eigen::internal::por< Packet4uc >(), Eigen::internal::por< Packet4ui >(), Eigen::internal::por< Packet4us >(), Eigen::internal::por< Packet8bf >(), Eigen::internal::por< Packet8c >(), Eigen::internal::por< Packet8cf >(), Eigen::internal::por< Packet8d >(), Eigen::internal::por< Packet8f >(), Eigen::internal::por< Packet8i >(), Eigen::internal::por< Packet8l >(), Eigen::internal::por< Packet8s >(), Eigen::internal::por< Packet8uc >(), Eigen::internal::por< Packet8ui >(), Eigen::internal::por< Packet8us >(), Eigen::internal::por< PacketXf >(), Eigen::internal::por< PacketXi >(), Eigen::bfloat16_impl::pow(), Eigen::half_impl::pow(), Eigen::internal::preciprocal(), Eigen::internal::preciprocal< Packet2f >(), Eigen::internal::preciprocal< Packet32h >(), Eigen::internal::preciprocal< Packet4f >(), Eigen::internal::predux(), Eigen::internal::scalar_sum_op< LhsScalar, RhsScalar >::predux(), Eigen::internal::scalar_product_op< LhsScalar, RhsScalar >::predux(), Eigen::internal::scalar_min_op< LhsScalar, RhsScalar, NaNPropagation >::predux(), Eigen::internal::scalar_max_op< LhsScalar, RhsScalar, NaNPropagation >::predux(), Eigen::internal::predux< Packet16b >(), Eigen::internal::predux< Packet16c >(), Eigen::internal::predux< Packet16f >(), Eigen::internal::predux< Packet16i >(), Eigen::internal::predux< Packet16uc >(), Eigen::internal::predux< Packet1cd >(), Eigen::internal::predux< Packet1cf >(), Eigen::internal::predux< Packet2cd >(), Eigen::internal::predux< Packet2cf >(), Eigen::internal::predux< Packet2d >(), Eigen::internal::predux< Packet2f >(), Eigen::internal::predux< Packet2i >(), Eigen::internal::predux< Packet2l >(), Eigen::internal::predux< Packet2ui >(), Eigen::internal::predux< Packet2ul >(), Eigen::internal::predux< Packet32h >(), Eigen::internal::predux< Packet4bf >(), Eigen::internal::predux< Packet4c >(), Eigen::internal::predux< Packet4cd >(), Eigen::internal::predux< Packet4cf >(), Eigen::internal::predux< Packet4d >(), Eigen::internal::predux< Packet4f >(), Eigen::internal::predux< Packet4i >(), Eigen::internal::predux< Packet4s >(), Eigen::internal::predux< Packet4uc >(), Eigen::internal::predux< Packet4ui >(), Eigen::internal::predux< Packet4us >(), Eigen::internal::predux< Packet8bf >(), Eigen::internal::predux< Packet8c >(), Eigen::internal::predux< Packet8cf >(), Eigen::internal::predux< Packet8d >(), Eigen::internal::predux< Packet8f >(), Eigen::internal::predux< Packet8h >(), Eigen::internal::predux< Packet8i >(), Eigen::internal::predux< Packet8l >(), Eigen::internal::predux< Packet8s >(), Eigen::internal::predux< Packet8uc >(), Eigen::internal::predux< Packet8ui >(), Eigen::internal::predux< Packet8us >(), Eigen::internal::predux< PacketXf >(), Eigen::internal::predux< PacketXi >(), Eigen::internal::predux_any(), predux_complex(), Eigen::internal::predux_half_dowto4(), Eigen::internal::predux_half_dowto4< Packet16bf >(), Eigen::internal::predux_half_dowto4< Packet16f >(), Eigen::internal::predux_half_dowto4< Packet16h >(), Eigen::internal::predux_half_dowto4< Packet16i >(), Eigen::internal::predux_half_dowto4< Packet32h >(), Eigen::internal::predux_half_dowto4< Packet8cf >(), Eigen::internal::predux_half_dowto4< Packet8d >(), Eigen::internal::predux_half_dowto4< Packet8f >(), Eigen::internal::predux_half_dowto4< Packet8i >(), Eigen::internal::predux_half_dowto4< Packet8l >(), Eigen::internal::predux_half_dowto4< Packet8ui >(), Eigen::internal::predux_helper(), Eigen::internal::predux_max(), Eigen::internal::predux_max< Packet16c >(), Eigen::internal::predux_max< Packet16f >(), Eigen::internal::predux_max< Packet16h >(), Eigen::internal::predux_max< Packet16i >(), Eigen::internal::predux_max< Packet16uc >(), Eigen::internal::predux_max< Packet2d >(), Eigen::internal::predux_max< Packet2f >(), Eigen::internal::predux_max< Packet2i >(), Eigen::internal::predux_max< Packet2l >(), Eigen::internal::predux_max< Packet2ui >(), Eigen::internal::predux_max< Packet2ul >(), Eigen::internal::predux_max< Packet4bf >(), Eigen::internal::predux_max< Packet4c >(), Eigen::internal::predux_max< Packet4d >(), Eigen::internal::predux_max< Packet4f >(), Eigen::internal::predux_max< Packet4i >(), Eigen::internal::predux_max< Packet4s >(), Eigen::internal::predux_max< Packet4uc >(), Eigen::internal::predux_max< Packet4ui >(), Eigen::internal::predux_max< Packet4us >(), Eigen::internal::predux_max< Packet8bf >(), Eigen::internal::predux_max< Packet8c >(), Eigen::internal::predux_max< Packet8d >(), Eigen::internal::predux_max< Packet8f >(), Eigen::internal::predux_max< Packet8h >(), Eigen::internal::predux_max< Packet8l >(), Eigen::internal::predux_max< Packet8s >(), Eigen::internal::predux_max< Packet8uc >(), Eigen::internal::predux_max< Packet8us >(), Eigen::internal::predux_max< PacketXf >(), Eigen::internal::predux_max< PacketXi >(), Eigen::internal::predux_min(), Eigen::internal::predux_min< Packet16c >(), Eigen::internal::predux_min< Packet16f >(), Eigen::internal::predux_min< Packet16h >(), Eigen::internal::predux_min< Packet16i >(), Eigen::internal::predux_min< Packet16uc >(), Eigen::internal::predux_min< Packet2d >(), Eigen::internal::predux_min< Packet2f >(), Eigen::internal::predux_min< Packet2i >(), Eigen::internal::predux_min< Packet2l >(), Eigen::internal::predux_min< Packet2ui >(), Eigen::internal::predux_min< Packet2ul >(), Eigen::internal::predux_min< Packet4bf >(), Eigen::internal::predux_min< Packet4c >(), Eigen::internal::predux_min< Packet4d >(), Eigen::internal::predux_min< Packet4f >(), Eigen::internal::predux_min< Packet4i >(), Eigen::internal::predux_min< Packet4s >(), Eigen::internal::predux_min< Packet4uc >(), Eigen::internal::predux_min< Packet4ui >(), Eigen::internal::predux_min< Packet4us >(), Eigen::internal::predux_min< Packet8bf >(), Eigen::internal::predux_min< Packet8c >(), Eigen::internal::predux_min< Packet8d >(), Eigen::internal::predux_min< Packet8f >(), Eigen::internal::predux_min< Packet8h >(), Eigen::internal::predux_min< Packet8l >(), Eigen::internal::predux_min< Packet8s >(), Eigen::internal::predux_min< Packet8uc >(), Eigen::internal::predux_min< Packet8us >(), Eigen::internal::predux_min< PacketXf >(), Eigen::internal::predux_min< PacketXi >(), Eigen::internal::predux_mul(), Eigen::internal::predux_mul< Packet16b >(), Eigen::internal::predux_mul< Packet16c >(), Eigen::internal::predux_mul< Packet16f >(), Eigen::internal::predux_mul< Packet16i >(), Eigen::internal::predux_mul< Packet16uc >(), Eigen::internal::predux_mul< Packet1cd >(), Eigen::internal::predux_mul< Packet1cf >(), Eigen::internal::predux_mul< Packet2cd >(), Eigen::internal::predux_mul< Packet2cf >(), Eigen::internal::predux_mul< Packet2d >(), Eigen::internal::predux_mul< Packet2f >(), Eigen::internal::predux_mul< Packet2i >(), Eigen::internal::predux_mul< Packet2l >(), Eigen::internal::predux_mul< Packet2ui >(), Eigen::internal::predux_mul< Packet2ul >(), Eigen::internal::predux_mul< Packet4bf >(), Eigen::internal::predux_mul< Packet4c >(), Eigen::internal::predux_mul< Packet4cd >(), Eigen::internal::predux_mul< Packet4cf >(), Eigen::internal::predux_mul< Packet4d >(), Eigen::internal::predux_mul< Packet4f >(), Eigen::internal::predux_mul< Packet4i >(), Eigen::internal::predux_mul< Packet4s >(), Eigen::internal::predux_mul< Packet4uc >(), Eigen::internal::predux_mul< Packet4ui >(), Eigen::internal::predux_mul< Packet4us >(), Eigen::internal::predux_mul< Packet8bf >(), Eigen::internal::predux_mul< Packet8c >(), Eigen::internal::predux_mul< Packet8cf >(), Eigen::internal::predux_mul< Packet8d >(), Eigen::internal::predux_mul< Packet8f >(), Eigen::internal::predux_mul< Packet8h >(), Eigen::internal::predux_mul< Packet8l >(), Eigen::internal::predux_mul< Packet8s >(), Eigen::internal::predux_mul< Packet8uc >(), Eigen::internal::predux_mul< Packet8us >(), Eigen::internal::predux_mul< PacketXf >(), Eigen::internal::predux_mul< PacketXi >(), predux_real(), Eigen::internal::preinterpret(), Eigen::internal::preinterpret< Packet16c, Packet16uc >(), Eigen::internal::preinterpret< Packet16f, Packet16i >(), Eigen::internal::preinterpret< Packet16f, Packet4f >(), Eigen::internal::preinterpret< Packet16f, Packet8d >(), Eigen::internal::preinterpret< Packet16f, Packet8f >(), Eigen::internal::preinterpret< Packet16i, Packet16f >(), Eigen::internal::preinterpret< Packet16uc, Packet16c >(), Eigen::internal::preinterpret< Packet2d, Packet2l >(), Eigen::internal::preinterpret< Packet2d, Packet2ul >(), Eigen::internal::preinterpret< Packet2d, Packet4d >(), Eigen::internal::preinterpret< Packet2d, Packet4f >(), Eigen::internal::preinterpret< Packet2d, Packet4i >(), Eigen::internal::preinterpret< Packet2d, Packet8d >(), Eigen::internal::preinterpret< Packet2f, Packet2i >(), Eigen::internal::preinterpret< Packet2f, Packet2ui >(), Eigen::internal::preinterpret< Packet2f, Packet4f >(), Eigen::internal::preinterpret< Packet2i, Packet2f >(), Eigen::internal::preinterpret< Packet2i, Packet2ui >(), Eigen::internal::preinterpret< Packet2i, Packet4i >(), Eigen::internal::preinterpret< Packet2l, Packet2d >(), Eigen::internal::preinterpret< Packet2l, Packet2ul >(), Eigen::internal::preinterpret< Packet2ui, Packet2f >(), Eigen::internal::preinterpret< Packet2ui, Packet2i >(), Eigen::internal::preinterpret< Packet2ui, Packet4ui >(), Eigen::internal::preinterpret< Packet2ul, Packet2d >(), Eigen::internal::preinterpret< Packet2ul, Packet2l >(), Eigen::internal::preinterpret< Packet4c, Packet16c >(), Eigen::internal::preinterpret< Packet4c, Packet4uc >(), Eigen::internal::preinterpret< Packet4c, Packet8c >(), Eigen::internal::preinterpret< Packet4d, Packet8d >(), Eigen::internal::preinterpret< Packet4f, Packet16f >(), Eigen::internal::preinterpret< Packet4f, Packet2d >(), Eigen::internal::preinterpret< Packet4f, Packet4i >(), Eigen::internal::preinterpret< Packet4f, Packet4ui >(), Eigen::internal::preinterpret< Packet4f, Packet8f >(), Eigen::internal::preinterpret< Packet4i, Packet16i >(), Eigen::internal::preinterpret< Packet4i, Packet2d >(), Eigen::internal::preinterpret< Packet4i, Packet4f >(), Eigen::internal::preinterpret< Packet4i, Packet4ui >(), Eigen::internal::preinterpret< Packet4i, Packet8i >(), Eigen::internal::preinterpret< Packet4s, Packet4us >(), Eigen::internal::preinterpret< Packet4s, Packet8s >(), Eigen::internal::preinterpret< Packet4uc, Packet16uc >(), Eigen::internal::preinterpret< Packet4uc, Packet4c >(), Eigen::internal::preinterpret< Packet4uc, Packet8uc >(), Eigen::internal::preinterpret< Packet4ui, Packet4f >(), Eigen::internal::preinterpret< Packet4ui, Packet4i >(), Eigen::internal::preinterpret< Packet4ui, Packet8ui >(), Eigen::internal::preinterpret< Packet4us, Packet4s >(), Eigen::internal::preinterpret< Packet4us, Packet8us >(), Eigen::internal::preinterpret< Packet8bf, Packet16bf >(), Eigen::internal::preinterpret< Packet8c, Packet16c >(), Eigen::internal::preinterpret< Packet8c, Packet8uc >(), Eigen::internal::preinterpret< Packet8d, Packet16f >(), Eigen::internal::preinterpret< Packet8d, Packet2d >(), Eigen::internal::preinterpret< Packet8d, Packet4d >(), Eigen::internal::preinterpret< Packet8d, Packet8l >(), Eigen::internal::preinterpret< Packet8f, Packet16f >(), Eigen::internal::preinterpret< Packet8f, Packet8i >(), Eigen::internal::preinterpret< Packet8h, Packet16h >(), Eigen::internal::preinterpret< Packet8i, Packet16i >(), Eigen::internal::preinterpret< Packet8i, Packet8f >(), Eigen::internal::preinterpret< Packet8i, Packet8ui >(), Eigen::internal::preinterpret< Packet8l, Packet8d >(), Eigen::internal::preinterpret< Packet8s, Packet8us >(), Eigen::internal::preinterpret< Packet8uc, Packet16uc >(), Eigen::internal::preinterpret< Packet8uc, Packet8c >(), Eigen::internal::preinterpret< Packet8ui, Packet8i >(), Eigen::internal::preinterpret< Packet8us, Packet8s >(), Eigen::internal::preinterpret< PacketXf, PacketXi >(), Eigen::internal::preinterpret< PacketXi, PacketXf >(), Eigen::internal::preverse(), Eigen::internal::preverse< Packet4bf >(), Eigen::internal::print(), Eigen::internal::print< Packet16bf >(), Eigen::internal::print< Packet16f >(), Eigen::internal::print< Packet16h >(), Eigen::internal::print< Packet2d >(), Eigen::internal::print< Packet32h >(), Eigen::internal::print< Packet4bf >(), Eigen::internal::print< Packet4d >(), Eigen::internal::print< Packet4f >(), Eigen::internal::print< Packet8bf >(), Eigen::internal::print< Packet8d >(), Eigen::internal::print< Packet8f >(), Eigen::internal::print< Packet8h >(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::processDataLineBluestein(), prod(), product_large_regressions(), propagate_nan_max(), propagate_nan_min(), propagate_number_max(), propagate_number_min(), Eigen::internal::pround(), Eigen::internal::pround< Packet16bf >(), Eigen::internal::pround< Packet16f >(), Eigen::internal::pround< Packet16h >(), Eigen::internal::pround< Packet2d >(), Eigen::internal::pround< Packet32h >(), Eigen::internal::pround< Packet4bf >(), Eigen::internal::pround< Packet4d >(), Eigen::internal::pround< Packet4f >(), Eigen::internal::pround< Packet8bf >(), Eigen::internal::pround< Packet8d >(), Eigen::internal::pround< Packet8f >(), Eigen::internal::pround< Packet8h >(), Eigen::internal::prsqrt(), Eigen::internal::prsqrt< Packet32h >(), Eigen::internal::prsqrt_float_common(), Eigen::internal::prsqrt_float_unsafe(), Eigen::internal::pscatter_common(), Eigen::internal::pselect(), Eigen::internal::pselect< bool >(), Eigen::internal::pselect< Packet4d >(), Eigen::internal::pselect< Packet8f >(), Eigen::internal::pselect< Packet8i >(), Eigen::internal::pselect< Packet8ui >(), Eigen::internal::pset1(), Eigen::internal::psign(), Eigen::internal::psignbit(), Eigen::internal::psignbit< Packet32h >(), Eigen::internal::psin(), Eigen::internal::psin< Packet32h >(), Eigen::internal::psin< Packet8bf >(), Eigen::internal::psinh(), Eigen::internal::psqrt(), Eigen::internal::psqrt< Packet1cd >(), Eigen::internal::psqrt< Packet1cf >(), Eigen::internal::psqrt< Packet2cd >(), Eigen::internal::psqrt< Packet2cf >(), Eigen::internal::psqrt< Packet32h >(), Eigen::internal::psqrt< Packet4cd >(), Eigen::internal::psqrt< Packet4cf >(), Eigen::internal::psqrt< Packet4f >(), Eigen::internal::psqrt< Packet8cf >(), Eigen::internal::psqrt< PacketXf >(), Eigen::internal::psqrt_complex(), Eigen::internal::psqrt_float_common(), Eigen::internal::pstore1(), Eigen::internal::pstore1< Packet16f >(), Eigen::internal::pstore1< Packet16i >(), Eigen::internal::pstore1< Packet2d >(), Eigen::internal::pstore1< Packet4d >(), Eigen::internal::pstore1< Packet4f >(), Eigen::internal::pstore1< Packet8d >(), Eigen::internal::pstore1< Packet8f >(), Eigen::internal::pstore1< Packet8i >(), Eigen::internal::pstore1< Packet8l >(), pstoreu_pmadd_complex(), Eigen::internal::psub(), Eigen::internal::psub< Packet16b >(), Eigen::internal::psub< Packet16bf >(), Eigen::internal::psub< Packet16c >(), Eigen::internal::psub< Packet16f >(), Eigen::internal::psub< Packet16h >(), Eigen::internal::psub< Packet16i >(), Eigen::internal::psub< Packet16uc >(), Eigen::internal::psub< Packet1cd >(), Eigen::internal::psub< Packet1cf >(), Eigen::internal::psub< Packet2cd >(), Eigen::internal::psub< Packet2cf >(), Eigen::internal::psub< Packet2d >(), Eigen::internal::psub< Packet2f >(), Eigen::internal::psub< Packet2i >(), Eigen::internal::psub< Packet2l >(), Eigen::internal::psub< Packet2ui >(), Eigen::internal::psub< Packet2ul >(), Eigen::internal::psub< Packet32h >(), Eigen::internal::psub< Packet4bf >(), Eigen::internal::psub< Packet4c >(), Eigen::internal::psub< Packet4cd >(), Eigen::internal::psub< Packet4cf >(), Eigen::internal::psub< Packet4d >(), Eigen::internal::psub< Packet4f >(), Eigen::internal::psub< Packet4i >(), Eigen::internal::psub< Packet4s >(), Eigen::internal::psub< Packet4uc >(), Eigen::internal::psub< Packet4ui >(), Eigen::internal::psub< Packet4us >(), Eigen::internal::psub< Packet8bf >(), Eigen::internal::psub< Packet8c >(), Eigen::internal::psub< Packet8cf >(), Eigen::internal::psub< Packet8d >(), Eigen::internal::psub< Packet8f >(), Eigen::internal::psub< Packet8h >(), Eigen::internal::psub< Packet8i >(), Eigen::internal::psub< Packet8l >(), Eigen::internal::psub< Packet8s >(), Eigen::internal::psub< Packet8uc >(), Eigen::internal::psub< Packet8ui >(), Eigen::internal::psub< Packet8us >(), Eigen::internal::psub< PacketXf >(), Eigen::internal::psub< PacketXi >(), Eigen::internal::ptan(), Eigen::internal::ptanh(), Eigen::internal::ptanh< Packet32h >(), Eigen::internal::ptranspose(), Eigen::internal::ptrue(), Eigen::internal::ptrue< Packet16f >(), Eigen::internal::ptrue< Packet1cd >(), Eigen::internal::ptrue< Packet2cd >(), Eigen::internal::ptrue< Packet2cf >(), Eigen::internal::ptrue< Packet2d >(), Eigen::internal::ptrue< Packet2l >(), Eigen::internal::ptrue< Packet4cd >(), Eigen::internal::ptrue< Packet4cf >(), Eigen::internal::ptrue< Packet4d >(), Eigen::internal::ptrue< Packet4f >(), Eigen::internal::ptrue< Packet4i >(), Eigen::internal::ptrue< Packet8cf >(), Eigen::internal::ptrue< Packet8d >(), Eigen::internal::ptrue< Packet8f >(), Eigen::internal::ptrue< Packet8i >(), Eigen::internal::ptrunc(), Eigen::internal::ptrunc< Packet16bf >(), Eigen::internal::ptrunc< Packet16f >(), Eigen::internal::ptrunc< Packet16h >(), Eigen::internal::ptrunc< Packet2d >(), Eigen::internal::ptrunc< Packet32h >(), Eigen::internal::ptrunc< Packet4bf >(), Eigen::internal::ptrunc< Packet4d >(), Eigen::internal::ptrunc< Packet4f >(), Eigen::internal::ptrunc< Packet8bf >(), Eigen::internal::ptrunc< Packet8d >(), Eigen::internal::ptrunc< Packet8f >(), Eigen::internal::ptrunc< Packet8h >(), Eigen::internal::pxor(), Eigen::internal::pxor< Packet16b >(), Eigen::internal::pxor< Packet16c >(), Eigen::internal::pxor< Packet16f >(), Eigen::internal::pxor< Packet16i >(), Eigen::internal::pxor< Packet16uc >(), Eigen::internal::pxor< Packet1cd >(), Eigen::internal::pxor< Packet1cf >(), Eigen::internal::pxor< Packet2cd >(), Eigen::internal::pxor< Packet2cf >(), Eigen::internal::pxor< Packet2d >(), Eigen::internal::pxor< Packet2f >(), Eigen::internal::pxor< Packet2i >(), Eigen::internal::pxor< Packet2l >(), Eigen::internal::pxor< Packet2ui >(), Eigen::internal::pxor< Packet2ul >(), Eigen::internal::pxor< Packet4c >(), Eigen::internal::pxor< Packet4cd >(), Eigen::internal::pxor< Packet4cf >(), Eigen::internal::pxor< Packet4d >(), Eigen::internal::pxor< Packet4f >(), Eigen::internal::pxor< Packet4i >(), Eigen::internal::pxor< Packet4s >(), Eigen::internal::pxor< Packet4uc >(), Eigen::internal::pxor< Packet4ui >(), Eigen::internal::pxor< Packet4us >(), Eigen::internal::pxor< Packet8bf >(), Eigen::internal::pxor< Packet8c >(), Eigen::internal::pxor< Packet8cf >(), Eigen::internal::pxor< Packet8d >(), Eigen::internal::pxor< Packet8f >(), Eigen::internal::pxor< Packet8i >(), Eigen::internal::pxor< Packet8l >(), Eigen::internal::pxor< Packet8s >(), Eigen::internal::pxor< Packet8uc >(), Eigen::internal::pxor< Packet8ui >(), Eigen::internal::pxor< Packet8us >(), Eigen::internal::pxor< PacketXf >(), Eigen::internal::pxor< PacketXi >(), Eigen::internal::pzero(), qr(), qr_invertible(), quaternion(), quatmul_default(), quatmul_novec(), Eigen::internal::r1mpyq(), REF_ABS_DIFF(), REF_ADD(), REF_DIV(), REF_MADD(), REF_MSUB(), REF_MUL(), REF_NMADD(), REF_NMSUB(), REF_RECIPROCAL(), REF_SUB(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::RefineableSolidCubicMesh< ELEMENT >::RefineableSolidCubicMesh(), oomph::RefineableTwoDAnnularMesh< ELEMENT >::RefineableTwoDAnnularMesh(), RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem(), regression_bug_654(), oomph::AugmentedBlockFoldLinearSolver::resolve(), oomph::AugmentedBlockPitchForkLinearSolver::resolve(), Eigen::bfloat16_impl::rint(), Eigen::half_impl::rint(), Quaternion::rotateInverseInertiaTensor(), rotg(), Eigen::bfloat16_impl::round(), Eigen::half_impl::round(), TestMethodDispatching< Scalar, 1 >::run(), Eigen::internal::pardiso_run_selector< IndexType >::run(), Eigen::internal::pardiso_run_selector< long long int >::run(), Eigen::internal::reduce< Reducer, A >::run(), Eigen::internal::not_op::run(), Eigen::internal::negation_op::run(), Eigen::internal::greater_equal_zero_op::run(), Eigen::internal::not_equal_op::run(), Eigen::internal::logical_and_op::run(), Eigen::internal::product_op::run(), Eigen::internal::greater_op::run(), Eigen::internal::greater_equal_op::run(), Eigen::internal::sum_op::run(), Eigen::internal::lesser_op::run(), Eigen::internal::lesser_equal_op::run(), Eigen::internal::equal_op::run(), Eigen::internal::logical_or_op::run(), Eigen::internal::reduce< Reducer, A, Ts... >::run(), Eigen::internal::squared_norm_impl< Derived, Scalar >::run(), Eigen::internal::squared_norm_impl< Derived, bool >::run(), Eigen::internal::cast_impl< float, half >::run(), Eigen::internal::cast_impl< half, float >::run(), Eigen::internal::LU_kernel_bmod< 1 >::run(), Eigen::internal::cast_impl< int, half >::run(), Eigen::internal::default_inner_product_impl< Lhs, Rhs, Conj >::run(), Eigen::internal::psign_impl< Packet, std::enable_if_t<!NumTraits< typename unpacket_traits< Packet >::type >::IsComplex &&!NumTraits< typename unpacket_traits< Packet >::type >::IsInteger > >::run(), Eigen::internal::psign_impl< Packet, std::enable_if_t<!NumTraits< typename unpacket_traits< Packet >::type >::IsComplex &&NumTraits< typename unpacket_traits< Packet >::type >::IsSigned &&NumTraits< typename unpacket_traits< Packet >::type >::IsInteger > >::run(), Eigen::internal::psign_impl< Packet, std::enable_if_t<!NumTraits< typename unpacket_traits< Packet >::type >::IsComplex &&!NumTraits< typename unpacket_traits< Packet >::type >::IsSigned &&NumTraits< typename unpacket_traits< Packet >::type >::IsInteger > >::run(), Eigen::internal::psign_impl< Packet, std::enable_if_t< NumTraits< typename unpacket_traits< Packet >::type >::IsComplex &&unpacket_traits< Packet >::vectorizable > >::run(), Eigen::internal::preinterpret_generic< Target, Packet, false >::run(), Eigen::internal::preinterpret_generic< Packet, Packet, true >::run(), Eigen::internal::pcast_generic< Packet, Packet, true, false >::run(), Eigen::internal::psign_impl< Packet, EnableIf >::run(), Eigen::internal::psignbit_impl< Packet, true, IsInteger >::run(), Eigen::internal::psignbit_impl< Packet, false, false >::run(), Eigen::internal::psignbit_impl< Packet, false, true >::run(), Eigen::internal::generic_reciprocal_newton_step< Packet, Steps >::run(), Eigen::internal::generic_rsqrt_newton_step< Packet, Steps >::run(), Eigen::internal::generic_sqrt_newton_step< Packet, Steps >::run(), Eigen::internal::pminmax_impl< NaNPropagation >::run(), Eigen::internal::pminmax_impl< PropagateNaN >::run(), Eigen::internal::pminmax_impl< PropagateNumbers >::run(), Eigen::internal::pselect_impl< Packet, EnableIf >::run(), Eigen::internal::pselect_impl< Packet, std::enable_if_t< is_scalar< Packet >::value > >::run(), Eigen::internal::quat_product< Architecture::Target, Derived, OtherDerived, float >::run(), Eigen::internal::quat_product< Arch, Derived1, Derived2, Scalar >::run(), negative_or_zero_impl< Scalar, IsSigned >::run(), Eigen::numext::signbit_impl< Scalar, false, true >::run(), Eigen::internal::pcast_generic< SrcPacket, TgtPacket, false, false >::run(), Eigen::internal::pcast_generic< SrcPacket, TgtPacket, true, TgtIsHalf >::run(), Eigen::internal::pcast_generic< SrcPacket, TgtPacket, false, true >::run(), evaluate_defaults_action_t::run(), Eigen::internal::cross3_impl< Architecture::Target, VectorLhs, VectorRhs, float, true >::run(), Eigen::internal::zeta_impl_series< double >::run(), Eigen::internal::zeta_impl_series< float >::run(), Eigen::internal::matrix_swap_impl< MatrixTypeA, MatrixTypeB, SwapPointers >::run(), Eigen::internal::matrix_swap_impl< MatrixTypeA, MatrixTypeB, true >::run(), Eigen::internal::igammac_cf_impl< Scalar, mode >::run(), Eigen::internal::igamma_series_impl< Scalar, mode >::run(), Eigen::internal::zeta_impl< Scalar >::run(), Eigen::internal::bitwise_binary_impl< Scalar, IsComplex >::run_and(), Eigen::internal::bitwise_binary_impl< Scalar, true >::run_and(), Eigen::internal::bitwise_unary_impl< Scalar, IsComplex >::run_not(), Eigen::internal::bitwise_unary_impl< Scalar, true >::run_not(), Eigen::internal::bitwise_binary_impl< Scalar, IsComplex >::run_or(), Eigen::internal::bitwise_binary_impl< Scalar, true >::run_or(), Eigen::internal::bitwise_binary_impl< Scalar, IsComplex >::run_xor(), Eigen::internal::bitwise_binary_impl< Scalar, true >::run_xor(), ScatteringProblem< ELEMENT >::ScatteringProblem(), selfadjointeigensolver(), MatrixSymmetric3D::selfDyadic(), oomph::Ellipse::set_A_ellips(), my_problem::set_Amplitude(), BaseStateProblem< BASE_ELEMENT >::set_boundary_conditions(), AxisymmetricIntersectionOfWalls::setAxis(), HorizontalBaseScrew::setAxis(), ScrewsymmetricIntersectionOfWalls::setAxis(), SimpleDrumSuperquadrics::setAxis(), Eigen::QuaternionBase< Derived >::setFromTwoVectors(), Binary::setInitialAmplitude(), RNG::setLinearCongruentialGeneratorParmeters(), ClosedCSCWalls::setupInitialConditions(), CSCInit::setupInitialConditions(), CSCWalls::setupInitialConditions(), Drum::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), TriangulatedScrewSelfTest::setupInitialConditions(), Eigen::internal::shuffle(), Eigen::internal::shuffle1(), Eigen::internal::shuffle2(), Eigen::internal::shuffle2< true >(), SimpleShearProblem< ELEMENT >::SimpleShearProblem(), Eigen::bfloat16_impl::sin(), Eigen::half_impl::sin(), Eigen::bfloat16_impl::sinh(), slerp_eigen(), slerp_gael(), slerp_legacy(), slerp_legacy_nlerp(), slerp_rw(), oomph::AugmentedBlockFoldLinearSolver::solve(), oomph::AugmentedBlockPitchForkLinearSolver::solve(), oomph::ANASAZI::solve_eigenproblem(), solveQuad(), sparse_basic(), DPMBase::splitDomain(), Eigen::bfloat16_impl::sqrt(), Eigen::half_impl::sqrt(), Vec3D::sqrt(), Vec3D::square(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::square_of_l2_norm_of_error(), StefanBoltzmannProblem< ELEMENT >::StefanBoltzmannProblem(), WearableTriangulatedWall::storeDebris(), oomph::Refineable_r_mesh< ELEMENT >::stretch_mesh(), sub(), Eigen::swap(), Eigen::internal::swap(), Eigen::numext::swap(), Eigen::internal::swap_plain_array(), MatrixSymmetric3D::symmetrisedDyadic(), Eigen::bfloat16_impl::tan(), Eigen::half_impl::tan(), Eigen::bfloat16_impl::tanh(), Eigen::half_impl::tanh(), test_array_reverse_and_reduce(), test_array_zip_and_apply(), test_complex_operators(), test_conversion(), test_exponent(), test_hypot(), test_id_helper(), test_initialization(), test_isApprox(), boost::multiprecision::test_isApprox(), Eigen::test_isApprox(), test_isApprox_abs(), Eigen::test_isApproxOrLessThan(), boost::multiprecision::test_isApproxOrLessThan(), Eigen::test_isApproxWithRef(), test_isMuchSmallerThan(), boost::multiprecision::test_isMuchSmallerThan(), Eigen::test_isMuchSmallerThan(), test_parallelize_gemm(), Eigen::test_relative_error(), test_relative_error(), boost::multiprecision::test_relative_error(), test_std_initializers_tensor(), test_stl_iterators(), test_threadpool_allocate(), transform_products(), transformations(), transformations_no_scale(), Multipole::TranslateMultipoleExpansionTo(), Eigen::bfloat16_impl::trunc(), Eigen::half_impl::trunc(), oomph::VectorHelpers::two_norm(), oomph::TwoDAnnularMesh< ELEMENT >::TwoDAnnularMesh(), Eigen::internal::bytewise_bitwise_helper< T >::unary(), unary_op_test(), Eigen::Quaternion< Scalar_, Options_ >::UnitRandom(), Membrane::updateFaceNeighbors(), upperbidiag(), Eigen::internal::random_without_cast_overflow< SrcScalar, TgtScalar, std::enable_if_t< NumTraits< SrcScalar >::IsInteger &&NumTraits< SrcScalar >::IsSigned &&NumTraits< TgtScalar >::IsInteger &&!NumTraits< TgtScalar >::IsSigned &&(std::numeric_limits< SrcScalar >::digits< std::numeric_limits< TgtScalar >::digits||(std::numeric_limits< SrcScalar >::digits==std::numeric_limits< TgtScalar >::digits &&NumTraits< SrcScalar >::IsSigned))> >::value(), Eigen::internal::random_without_cast_overflow< SrcScalar, TgtScalar, std::enable_if_t< NumTraits< SrcScalar >::IsInteger &&!NumTraits< SrcScalar >::IsSigned &&NumTraits< TgtScalar >::IsInteger &&!NumTraits< TgtScalar >::IsSigned &&(std::numeric_limits< SrcScalar >::digits< std::numeric_limits< TgtScalar >::digits||(std::numeric_limits< SrcScalar >::digits==std::numeric_limits< TgtScalar >::digits &&NumTraits< SrcScalar >::IsSigned))> >::value(), Eigen::internal::random_without_cast_overflow< SrcScalar, TgtScalar, std::enable_if_t<!NumTraits< SrcScalar >::IsInteger &&!NumTraits< SrcScalar >::IsComplex &&NumTraits< TgtScalar >::IsInteger &&NumTraits< TgtScalar >::IsSigned &&(std::numeric_limits< TgtScalar >::digits > std::numeric_limits< SrcScalar >::digits)> >::value(), Eigen::internal::random_without_cast_overflow< SrcScalar, TgtScalar, std::enable_if_t<!NumTraits< SrcScalar >::IsInteger &&!NumTraits< SrcScalar >::IsComplex &&NumTraits< TgtScalar >::IsInteger &&!NumTraits< TgtScalar >::IsSigned &&(std::numeric_limits< TgtScalar >::digits > std::numeric_limits< SrcScalar >::digits)> >::value(), Eigen::internal::vec2d_swizzle2(), Eigen::internal::vec2d_unpackhi(), Eigen::internal::vec2d_unpacklo(), Eigen::internal::vec4f_movehl(), Eigen::internal::vec4f_movelh(), Eigen::internal::vec4f_swizzle1(), Eigen::internal::vec4f_swizzle2(), Eigen::internal::vec4f_unpackhi(), Eigen::internal::vec4f_unpacklo(), oomph::VectorHelpers::vector_diff(), Jeffery_Solution::velocity(), verifyIsApprox(), Eigen::verifyIsApprox(), Eigen::verifyIsCwiseApprox(), oomph::OcTree::vertex_node_to_vector(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity(), oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity(), oomph::TwoDAnnularMesh< ELEMENT >::wrap_into_annular_shape(), and zero_sized_objects().
actual_x
const Scalar* actual_x = get_compact_vector(x, *n, *incx)
Referenced by if().
actual_y
Scalar* actual_y = get_compact_vector(y, *n, *incy)
Referenced by if().
alpha
Scalar alpha = *reinterpret_cast<const Scalar *>(palpha)
Referenced by her(), hpr(), and if().
ap
Scalar* ap = reinterpret_cast<Scalar *>(pap)
Referenced by Eigen::SimplicialCholeskyBase< Derived >::analyzePattern_preordered(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::calc_etree(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::calc_hadj_inner(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::calc_hadj_outer(), Eigen::SimplicialCholeskyBase< Derived >::factorize_preordered(), hpr(), Eigen::SimplicialCholeskyBase< Derived >::ordering(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::run(), test_autodiff_vector(), tpmv(), and tpsv().
beta
RealScalar beta = *reinterpret_cast<const Scalar *>(pbeta)
Referenced by Eigen::HessenbergDecomposition< MatrixType_ >::_compute(), Eigen::internal::bicgstab(), Eigen::internal::bicgstabl(), Eigen::internal::cm_factorize_p(), Eigen::internal::cm_factorize_p< SuiteSparse_long >(), oomph::ComplexGMRES< MATRIX >::complex_solve_helper(), Eigen::GeneralizedEigenSolver< MatrixType_ >::compute(), helpers::computeDisptFromCollisionTimeAndRestitutionCoefficientAndTangentialRestitutionCoefficientAndEffectiveMass(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::internal::conjugate_gradient(), Multipole::convertMultipoleToLocal(), Eigen::DGMRES< MatrixType_, Preconditioner_ >::dgmres(), Eigen::DGMRES< MatrixType_, Preconditioner_ >::dgmresCycle(), Eigen::internal::erf_over_x_double_small(), eulerangles_manual(), Eigen::TensorContractionEvaluatorBase< Derived >::evalGemmPartial(), Eigen::SparseQR< MatrixType_, OrderingType_ >::factorize(), oomph::DisplacementBasedFoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_adv_diff_flux(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_spherical_adv_diff_flux(), oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::RefineableUnsteadyHeatEquations< DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::UnsteadyHeatEquations< DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::LAPACK_QZ::find_eigenvalues(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::get_beta(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::get_beta(), RachelsAdvectionDiffusion::get_exact_u(), InfiniteWall::getFurthestPointSuperQuadric(), Eigen::internal::gmres(), householder(), Eigen::internal::householder_qr_inplace_update(), Eigen::internal::idrs(), Eigen::internal::idrstabl(), if(), Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::invoke(), oomph::Orthpoly::jacobi(), LawinenBox::LawinenBox(), Eigen::internal::least_square_conjugate_gradient(), Eigen::internal::llt_rank_update_lower(), main(), Eigen::MatrixBase< Derived >::makeHouseholder(), Eigen::MatrixBase< Derived >::makeHouseholderInPlace(), Eigen::internal::minres(), Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvAddMv(), Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvTimesMatAddMv(), HertzianBSHPInteractionTwoParticleElasticCollision::padeCoefficientOfRestitution(), Eigen::internal::patanh_double(), Eigen::RealSchur< MatrixType_ >::performFrancisQRStep(), Eigen::internal::plog_impl_float(), oomph::GMRESBlockPreconditioner::preconditioner_solve(), TanhSolnForSteadyAxisymAdvectionDiffusion::prescribed_beta_on_fixed_r_boundary(), Global_Physical_Variables::prescribed_beta_on_fixed_r_boundary(), Eigen::internal::ptanh_double(), Eigen::internal::ptanh_float(), Eigen::internal::patan_reduced< Scalar >::run(), Eigen::internal::generic_fast_erf< Scalar >::run(), Eigen::general_product_to_triangular_selector< MatrixType, ProductType, UpLo, true >::run(), Eigen::general_product_to_triangular_selector< MatrixType, ProductType, UpLo, false >::run(), Eigen::internal::tridiagonalization_inplace_selector< MatrixType, 3, false >::run(), ParhamiMcMeekingSinterSpecies::set(), SilbertPeriodic::set_study(), SuperQuadricParticle::setBoundingRadius(), SlidingFrictionSpecies::setCollisionTimeAndNormalAndTangentialRestitutionCoefficient(), SlidingFrictionSpecies::setCollisionTimeAndNormalAndTangentialRestitutionCoefficientNoDispt(), SinterNormalSpecies::setParhamiMcKeeping(), oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::sigma(), oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::sigma(), SilbertPeriodic::SilbertPeriodic(), oomph::LAPACK_QZ::solve_eigenproblem(), oomph::CG< MATRIX >::solve_helper(), oomph::BiCGStab< MATRIX >::solve_helper(), oomph::GMRES< MATRIX >::solve_helper(), oomph::AugmentedProblemGMRES::solve_helper(), oomph::HelmholtzGMRESMG< MATRIX >::solve_helper(), oomph::HelmholtzFGMRESMG< MATRIX >::solve_helper(), Eigen::RealQZ< MatrixType_ >::step(), test_scalar_sugar_add_mul(), test_scalar_sugar_sub_div(), LocalExpansion::translateLocalExpansion(), Multipole::TranslateMultipoleExpansionTo(), and Eigen::internal::tridiagonalization_inplace().
code
int code = UPLO(*uplo)
Referenced by her(), hpr(), and if().
func
func static
Initial value:
= {
      (Eigen::internal::selfadjoint_matrix_vector_product<Scalar, int, Eigen::ColMajor, Eigen::Upper, false,
                                                          false>::run),
      (Eigen::internal::selfadjoint_matrix_vector_product<Scalar, int, Eigen::ColMajor, Eigen::Lower, false,
                                                          false>::run),
  }
incx
int int RealScalar RealScalar int* incx
Referenced by her(), and hpr().
incy
int int RealScalar RealScalar int RealScalar int* incy
Initial value:
{
  typedef void (*functype)(int, const Scalar *, int, const Scalar *, Scalar *, Scalar)
info
else if k info = 0
Referenced by Eigen::KLU< MatrixType_ >::_solve_impl(), Eigen::SuperLU< MatrixType_ >::_solve_impl(), Eigen::internal::lapacke_helpers::lapacke_partial_lu< Scalar, StorageOrder >::blocked_lu(), Eigen::ArpackGeneralizedSelfAdjointEigenSolver< MatrixType, MatrixSolver, BisSPD >::compute(), CFile::copy(), ei_test_init_gpu(), Eigen::internal::lapacke_helpers::lapacke_llt< Scalar, Mode >::EIGEN_STATIC_ASSERT(), Eigen::SparseLU< MatrixType_, OrderingType_ >::factorize(), Eigen::SuperLU< MatrixType_ >::factorize(), oomph::LAPACK_QZ::find_eigenvalues(), her(), hpr(), SmallMatrix< numberOfRows, numberOfColumns >::inverse(), Eigen::LevenbergMarquardt< FunctorType_ >::lmdif1(), SmallMatrix< numberOfRows, numberOfColumns >::LUfactorisation(), Eigen::COLAMDOrdering< StorageIndex >::operator()(), Eigen::internal::gemm_functor< Scalar, Index, Gemm, Lhs, Rhs, Dest, BlockingType >::operator()(), compile_time_device_info::operator()(), oomph::HSL_MA42::reorder_elements(), Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, RowMajor, ResInnerStride >::run(), Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride >::run(), Eigen::internal::arpack_wrapper< double, double >::saupd(), Eigen::internal::arpack_wrapper< float, float >::saupd(), BaseParticle::setInfo(), oomph::TriangleMeshBase::setup_boundary_element_info(), SmallMatrix< numberOfRows, numberOfColumns >::solve(), oomph::ARPACK::solve_eigenproblem(), oomph::LAPACK_QZ::solve_eigenproblem(), test_lmder(), test_minimizeLM(), test_minimizeSteps(), test_sparseLM_T(), testHybrd(), testHybrd1(), testHybrj(), testHybrj1(), testLmder(), testLmder1(), testLmdif(), testLmdif1(), testLmstr(), testLmstr1(), testNistBennett5(), testNistBoxBOD(), testNistChwirut2(), testNistEckerle4(), testNistHahn1(), testNistLanczos1(), testNistMGH09(), testNistMGH10(), testNistMGH17(), testNistMisra1a(), testNistMisra1d(), testNistRat42(), testNistRat43(), testNistThurber(), Eigen::umfpack_report_info(), and xerbla_().
lda
else if * lda
Initial value:
{
  typedef void (*functype)(int, Scalar *, int, const Scalar *, const Scalar *, Scalar)
Referenced by Eigen::internal::lapacke_helpers::lapacke_partial_lu< Scalar, StorageOrder >::blocked_lu(), Eigen::internal::SparseLUImpl< MatrixType_::Scalar, MatrixType_::StorageIndex >::column_bmod(), Eigen::internal::lapacke_helpers::lapacke_llt< Scalar, Mode >::EIGEN_STATIC_ASSERT(), her(), if(), Eigen::internal::SparseLUImpl< Scalar, StorageIndex >::panel_bmod(), Eigen::internal::SparseLUImpl< Scalar, StorageIndex >::pivotL(), Eigen::internal::LU_kernel_bmod< SegSizeAtCompileTime >::run(), Eigen::internal::LU_kernel_bmod< 1 >::run(), Eigen::internal::lapacke_helpers::lapacke_hqr< MatrixQR, HCoeffs >::run(), Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::solveInPlace(), Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::solveInPlace(), Eigen::SparseLUMatrixUReturnType< MatrixLType, MatrixUType >::solveTransposedInPlace(), and Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::solveTransposedInPlace().
m
Eigen::internal::gemm_blocking_space< ColMajor, Scalar, Scalar, Dynamic, Dynamic, Dynamic > blocking * m
ZGERU performs the rank 1 operation
A := alpha*x*y' + A,
where alpha is a scalar, x is an m element vector, y is an n element vector and A is an m by n matrix.
ZGERC performs the rank 1 operation
A := alpha*x*conjg(y') + A,
where alpha is a scalar, x is an m element vector, y is an n element vector and A is an m by n matrix.
Referenced by __attribute__(), rapidjson::GenericValue< Encoding, Allocator >::Accept(), PolarNSProblem< ELEMENT >::actions_before_solve(), CFDDEMCoupleTest::actionsAfterTimeStep(), oomph::Problem::adapt(), VTKPointDescriptor< T >::addProperty(), adjoint(), aliasing_with_resize(), Eigen::internal::TensorContractionBlockMemAllocator< LhsScalar, RhsScalar >::allocateSlices(), Eigen::SparseQR< MatrixType_, OrderingType_ >::analyzePattern(), Eigen::SparseLU< MatrixType_, OrderingType_ >::analyzePattern(), Eigen::AngleAxis< Scalar_ >::AngleAxis(), array_complex(), array_for_matrix(), array_generic(), array_real(), as_scalar_product(), oomph::VectorMatrix< VALUE_TYPE >::assign(), oomph::RefineableElement::assign_hanging_local_eqn_numbers(), oomph::RefineableSolidElement::assign_solid_hanging_local_eqn_numbers(), sphericalHarmonics::associatedLegendrePolynomials(), AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::AxialSpineQuarterTubeMesh(), bandmatrix(), basicStuff(), basicStuffComplex(), bdcsvd_method(), bench(), bench_mnk(), bench_svd(), benchBasic(), benchBasic_loop(), CRBond_Bessel::bessikna(), CRBond_Bessel::bessiknb(), CRBond_Bessel::bessikv(), CRBond_Bessel::bessjyna(), CRBond_Bessel::bessjynb(), CRBond_Bessel::bessjyv(), Eigen::internal::kiss_cpx_fft< Scalar_ >::bfly2(), Eigen::internal::kiss_cpx_fft< Scalar_ >::bfly3(), Eigen::internal::kiss_cpx_fft< Scalar_ >::bfly4(), Eigen::internal::kiss_cpx_fft< Scalar_ >::bfly5(), Eigen::internal::kiss_cpx_fft< Scalar_ >::bfly_generic(), oomph::Problem::bifurcation_adapt_helper(), big_sparse_triplet(), block(), oomph::BlockPreconditioner< MATRIX >::block_setup(), Eigen::internal::llt_inplace< Scalar, Lower >::blocked(), Eigen::internal::lapacke_helpers::lapacke_partial_lu< Scalar, StorageOrder >::blocked_lu(), Eigen::internal::BlockedInPlaceTranspose(), NurbsUtils::bsplineOneBasis(), bug1150(), bug_1014(), bug_159(), bug_854(), oomph::CRMatrix< T >::build(), oomph::CCMatrix< T >::build(), MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::build_constraint_elements(), MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::build_mortaring_elements(), oomph::VectorMatrix< VALUE_TYPE >::build_vectors(), oomph::VectorMatrix< VALUE_TYPE >::build_vectors_and_value(), oomph::CRMatrix< T >::build_without_copy(), oomph::CCMatrix< T >::build_without_copy(), oomph::HomogenisedLinearElasticityEquations< DIM >::calculate_effective_modulus(), CauchyBounds(), CRBond_Bessel::cbessikna(), CRBond_Bessel::cbessiknb(), CRBond_Bessel::cbessikv(), CRBond_Bessel::cbessjyna(), CRBond_Bessel::cbessjynb(), CRBond_Bessel::cbessjyva(), oomph::CCMatrix< T >::CCMatrix(), check_auto_reshape4x4(), check_direct_access_reshape4x4(), check_index(), check_inf_nan(), check_left_top(), check_qtvector_matrix(), check_random_matrix(), check_stddeque_matrix(), check_stdlist_matrix(), check_stdvector_matrix(), check_tutorial_examples(), DropletBoundary::checkBoundaryAfterParticlesMove(), Eigen::internal::chkder(), cholesky(), cholesky_bug241(), cholesky_cplx(), cholesky_definiteness(), Eigen::internal::cofactor_3x3(), Eigen::internal::coletree(), Eigen::internal::SparseLUImpl< Scalar, StorageIndex >::column_dfs(), compact_size_triple(), compare_bdc_jacobi(), compare_bdc_jacobi_instance(), compare_using_data_and_stride(), comparisons(), oomph::TreeBasedRefineableMeshBase::complete_hanging_nodes_recursively(), Eigen::IterScaling< MatrixType_ >::compute(), VolumeCoupling::computeCouplingOnDPM(), VolumeCoupling::computeCouplingOnFEM(), Eigen::internal::computeProductBlockingSizes(), computeRoots(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::computeRoots(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::computeRoots(), Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >::computeRotationScaling(), Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >::computeScalingRotation(), Eigen::BDCSVD< MatrixType_, Options_ >::computeSingVecs(), sphericalHarmonics::computeSquaredFactorialValues(), Eigen::BDCSVD< MatrixType_, Options_ >::computeSVDofM(), constructorTest(), constructorTest< float >(), Multipole::convertMultipoleToLocal(), oomph::Problem::copy(), copy_matrix(), corners(), Eigen::createRandomPIMatrixOfRank(), oomph::CRMatrix< T >::CRMatrix(), ctor_init1(), cwise_min_max(), cwise_ref(), data_and_stride(), Domain::debugInformation(), oomph::Mesh::delete_all_external_storage(), oomph::DenseMatrix< T >::DenseMatrix(), Eigen::internal::determinant_impl< Derived, 4 >::det2(), Eigen::internal::determinant_impl< Derived, 4 >::det3(), determinant(), DenseLM< Scalar >::df(), sparseGaussianTest< Scalar >::df(), Eigen::DGMRES< MatrixType_, Preconditioner_ >::dgmresComputeDeflationData(), diagonal(), diagonal_assert(), diagonalmatrices(), oomph::RefineableAdvectionDiffusionEquations< DIM >::dinterpolated_u_adv_diff_ddata(), oomph::RefineableAxisymAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), oomph::RefineableSphericalAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), oomph::RefineableAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::DiskWithTorusAroundEdgeTetMeshFacetedSurface::DiskWithTorusAroundEdgeTetMeshFacetedSurface(), oomph::DGFaceElement::dnumerical_flux_du(), oomph::BiharmonicProblem< 2 >::doc_solution(), dontalign(), oomph::ClampedHermiteShellBoundaryConditionElement::dshape_local(), oomph::Problem::dump(), eigen2support(), EIGEN_DECLARE_TEST(), Eigen::internal::lapacke_helpers::lapacke_llt< Scalar, Mode >::EIGEN_STATIC_ASSERT(), eigensolver(), eigensolver_verify_assert(), eulerangles(), eulerangles_rand(), Eigen::TensorContractionEvaluatorBase< Derived >::evalGemmPartial(), Eigen::internal::kernel_retval< FullPivLU< MatrixType_, PermutationIndex_ > >::evalTo(), Eigen::SparseQR_QProduct< SparseQRType, Derived >::evalTo(), Eigen::internal::evaluateProductBlockingSizesHeuristic(), Eigen::internal::extract_data(), oomph::MumpsSolver::factorise(), oomph::SuperLUSolver::factorise_serial(), Eigen::SparseQR< MatrixType_, OrderingType_ >::factorize(), Eigen::SparseLU< MatrixType_, OrderingType_ >::factorize(), oomph::SpineLineMarangoniFluidInterfaceElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::FixedVolumeSpineLineMarangoniFluidInterfaceElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::SpinePointMarangoniSurfactantFluidInterfaceBoundingElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::HomogenisedLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity(), oomph::RefineableLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity(), oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), GelfandBratuElement< NNODE_1D >::fill_in_generic_dresidual_contribution(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), PredatorPreyElement::fill_in_generic_residual_contribution(), oomph::RefineablePolarNavierStokesEquations::fill_in_generic_residual_contribution(), GelfandBratuElement< NNODE_1D >::fill_in_generic_residual_contribution(), oomph::RefineablePolarStreamfunctionEquations::fill_in_generic_residual_contribution(), oomph::RefineableAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_adv_diff(), oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_generic_residual_contribution_adv_diff_react(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::BiharmonicFluxElement< DIM >::fill_in_generic_residual_contribution_biharmonic_flux(), oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_cons_adv_diff(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc(), oomph::RefineableFpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc(), oomph::RefineableFpPressureAdvDiffRobinBCElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc(), oomph::RefineableHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::RefineablePMLHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::PointFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::RefineableLinearWaveEquations< DIM >::fill_in_generic_residual_contribution_lin_wave(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineablePoissonEquations< DIM >::fill_in_generic_residual_contribution_poisson(), oomph::RefineablePVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::RefineableUnsteadyHeatEquations< DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::GeneralisedElement::fill_in_jacobian_from_external_by_fd(), oomph::ElementWithExternalElement::fill_in_jacobian_from_external_interaction_field_by_fd(), oomph::ElementWithExternalElement::fill_in_jacobian_from_external_interaction_geometric_by_fd(), oomph::ElementWithMovingNodes::fill_in_jacobian_from_geometric_data(), oomph::GeneralisedElement::fill_in_jacobian_from_internal_by_fd(), oomph::FiniteElement::fill_in_jacobian_from_nodal_by_fd(), oomph::RefineableElement::fill_in_jacobian_from_nodal_by_fd(), oomph::SolidFiniteElement::fill_in_jacobian_from_solid_position_by_fd(), oomph::RefineableSolidElement::fill_in_jacobian_from_solid_position_by_fd(), RefineableQCrouzeixRaviartElementWithExternalElement< DIM >::fill_in_off_diagonal_block_analytic(), RefineableQAxisymCrouzeixRaviartBoussinesqElement::fill_in_off_diagonal_block_analytic(), RefineableQAxisymAdvectionDiffusionBoussinesqElement::fill_in_off_diagonal_block_analytic(), RefineableQCrouzeixRaviartElementWithTwoExternalElement< DIM >::fill_in_off_diagonal_block_analytic(), RefineableQAdvectionDiffusionElementWithExternalElement< DIM >::fill_in_off_diagonal_block_analytic(), oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic(), RefineableBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd(), oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_by_fd(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd(), oomph::PseudoSolidNodeUpdateElement< BASIC, SOLID >::fill_in_shape_derivatives_by_fd(), oomph::RefineablePseudoSolidNodeUpdateElement< BASIC, SOLID >::fill_in_shape_derivatives_by_fd(), Eigen::internal::first_aligned(), Eigen::internal::first_default_aligned(), fixedSizeMatrixConstruction(), foo(), CRBond_Bessel::gamma(), Eigen::internal::gemm_kern_avx512(), generalized_eigensolver_real(), oomph::RefineableSolidElement::geom_data_pt(), oomph::GeompackQuadScaffoldMesh::GeompackQuadScaffoldMesh(), RefineableModalPoissonEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineableNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineablePoissonEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::Problem::get_hessian_vector_products(), oomph::FoldHandler::get_jacobian(), oomph::PitchForkHandler::get_jacobian(), oomph::HopfHandler::get_jacobian(), oomph::RefineablePVDEquationsWithPressure< DIM >::get_mass_matrix_diagonal(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::RefineableNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal(), Eigen::MetisOrdering< StorageIndex >::get_symmetrized_graph(), MeshTriangle::getBaricentricWeight(), ParticleHandler::getCentreOfMass(), oomph::VolumeCoupledElement< ELEMENT >::getCouplingStiffness(), VolumeCoupling::getInvCoupledMassPerTime(), Eigen::internal::traits< SimplicialLLT< MatrixType_, UpLo_, Ordering_ > >::getL(), Eigen::internal::traits< SimplicialLDLT< MatrixType_, UpLo_, Ordering_ > >::getL(), Eigen::internal::traits< SimplicialNonHermitianLLT< MatrixType_, UpLo_, Ordering_ > >::getL(), Eigen::internal::traits< SimplicialNonHermitianLDLT< MatrixType_, UpLo_, Ordering_ > >::getL(), Eigen::internal::LDLT_Traits< MatrixType, Lower >::getL(), Eigen::internal::LDLT_Traits< MatrixType, Upper >::getL(), Eigen::internal::LLT_Traits< MatrixType, Lower >::getL(), Eigen::internal::LLT_Traits< MatrixType, Upper >::getL(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::getLog2(), ParticleHandler::getMassLocal(), TimeDependentPeriodicBoundary::getPlanewiseShift(), VolumeCoupling::getProjectionAndProjected(), VolumeCoupling::getProjectionMatrix(), Eigen::internal::traits< SimplicialLLT< MatrixType_, UpLo_, Ordering_ > >::getU(), Eigen::internal::traits< SimplicialLDLT< MatrixType_, UpLo_, Ordering_ > >::getU(), Eigen::internal::traits< SimplicialNonHermitianLLT< MatrixType_, UpLo_, Ordering_ > >::getU(), Eigen::internal::traits< SimplicialNonHermitianLDLT< MatrixType_, UpLo_, Ordering_ > >::getU(), Eigen::internal::LDLT_Traits< MatrixType, Lower >::getU(), Eigen::internal::LDLT_Traits< MatrixType, Upper >::getU(), Eigen::internal::LLT_Traits< MatrixType, Lower >::getU(), Eigen::internal::LLT_Traits< MatrixType, Upper >::getU(), MeshTriangle::getVelocityAtContact(), Eigen::internal::gmres(), oomph::HalfRectangleWithHoleMesh< ELEMENT >::HalfRectangleWithHoleMesh(), hessenberg(), SpineGravityTractionElement< ELEMENT >::hijack_all_nodes(), householder(), householder_update(), oomph::RefineableElement::identify_field_data_for_interactions(), oomph::RefineablePseudoSolidNodeUpdateElement< BASIC, SOLID >::identify_geometric_data(), oomph::RefineableSolidElement::identify_geometric_data(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::identify_load_data(), oomph::RefineableQTaylorHoodElement< DIM >::identify_load_data(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::identify_load_data(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::identify_load_data(), Global::initial_left(), Global::initial_right(), initializerListArrayConstruction(), initializerListMatrixConstruction(), initializerListVectorConstruction(), Eigen::internal::gemm_blocking_space< StorageOrder, LhsScalar_, RhsScalar_, MaxRows, MaxCols, MaxDepth, KcFactor, false >::initParallel(), Eigen::internal::LLT_Traits< MatrixType, Lower >::inplace_decomposition(), Eigen::internal::LLT_Traits< MatrixType, Upper >::inplace_decomposition(), oomph::RefineablePolarTaylorHoodElement::insert_load_data(), Eigen::internal::unary_pow::int_pow(), integer_type_tests(), inverse(), inverse_general_4x4(), inverse_permutation_4x4(), size_triple_t::is_cubic(), jacobi(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableDarcyElement< DARCY_ELEMENT >::jacobian_and_shape_of_field(), jacobisvd_full_options(), jacobisvd_method(), jacobisvd_thin_options(), jacobisvd_verify_assert(), jacobisvd_verify_inputs(), Eigen::internal::least_square_conjugate_gradient(), linearStructure(), Eigen::LevenbergMarquardt< FunctorType_ >::lmder1(), Eigen::LevenbergMarquardt< FunctorType_ >::lmdif1(), Eigen::LevenbergMarquardt< FunctorType_ >::lmstr1(), Eigen::internal::LUnumTempV(), Eigen::internal::LUTempSpace(), oomph::RectangleWithHoleAndAnnularRegionDomain::macro_element_boundary(), RectangleWithHoleDomain::macro_element_boundary(), oomph::HalfRectangleWithHoleDomain::macro_element_boundary(), CylinderAndInterfaceDomain::macro_element_boundary(), oomph::CylinderWithFlagDomain::macro_element_boundary(), oomph::RectangleWithHoleDomain::macro_element_boundary(), main(), main_gemm(), main_gemv(), Eigen::JacobiRotation< Scalar >::makeJacobi(), map_class_matrix(), map_class_vector(), Map_MatrixXd_delete(), Map_MatrixXd_get_coeff(), Map_MatrixXd_print(), Map_MatrixXd_set_coeff(), Map_MatrixXd_set_zero(), map_static_methods(), Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::MappedSuperNodalMatrix(), mapstaticmethods(), TestProblem::mass_source(), Eigen::internal::matrix_function_compute_above_diagonal(), Eigen::internal::matrix_function_solve_triangular_sylvester(), matrix_l1_norm(), matrixRedux(), matrixVisitor(), MatrixXd_data(), MatrixXd_delete(), MatrixXd_get_coeff(), MatrixXd_print(), MatrixXd_resize(), MatrixXd_set_coeff(), MatrixXd_set_zero(), Eigen::internal::SparseLUImpl< Scalar, StorageIndex >::memInit(), MortaringHelpers::MergedSolidMesh::MergedSolidMesh(), min_max(), Eigen::LevenbergMarquardt< FunctorType_ >::minimizeInit(), Eigen::LevenbergMarquardt< FunctorType_ >::minimizeOptimumStorageInit(), Eigen::LevenbergMarquardt< FunctorType_ >::minimizeOptimumStorageOneStep(), miscMatrices(), DenseLM< Scalar >::model(), sparseGaussianTest< Scalar >::model(), MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::MortaringValidationProblem(), move_matrix(), oomph::BlockPreconditioner< MATRIX >::ndof_types(), oomph::RefineableSolidElement::ngeom_data(), nomalloc(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::oc_hang_helper(), OneByM(), Eigen::MetisOrdering< StorageIndex >::operator()(), Eigen::COLAMDOrdering< StorageIndex >::operator()(), oomph::RankFiveTensor< T >::operator()(), DenseLM< Scalar >::operator()(), sparseGaussianTest< Scalar >::operator()(), Eigen::internal::gemm_pack_lhs< Scalar, Index, DataMapper, Pack1, Pack2, Packet, RowMajor, Conjugate, PanelMode >::operator()(), SmallMatrix< numberOfRows, numberOfColumns >::operator()(), operator<<(), Eigen::DenseBase< Derived >::operator<<(), Eigen::operator<<(), oomph::DenseMatrix< T >::operator=(), Eigen::Rotation2D< Scalar_ >::operator=(), EulerAngles< Scalar_ >::operator=(), oomph::RankFiveTensor< T >::operator=(), oomph::RankFourTensor< T >::operator=(), oomph::RankThreeTensor< T >::operator=(), MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::output(), Eigen::internal::scalar_logistic_op< float >::packetOp(), Eigen::internal::SparseLUImpl< Scalar, StorageIndex >::panel_bmod(), Eigen::internal::SparseLUImpl< Scalar, StorageIndex >::panel_dfs(), Eigen::internal::pblend(), permutationmatrices(), Eigen::BDCSVD< MatrixType_, Options_ >::perturbCol0(), Eigen::internal::pexp_float(), Eigen::internal::pfrexp_generic(), oomph::Legendre_functions_helper::plgndr2(), Eigen::internal::pminmax_propagate_nan(), Eigen::internal::pminmax_propagate_numbers(), oomph::Node::position(), oomph::Node::position_gen(), Eigen::internal::preverse(), Eigen::internal::print_matrix(), LiquidMigrationMPI2Test::printTime(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::processDataLineBluestein(), product(), product_extra(), product_large_regressions(), product_notemporary(), product_selfadjoint(), product_sweep(), Eigen::internal::ptranspose(), Eigen::internal::detail::ptranspose_impl(), qr(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::quad_hang_helper(), Eigen::internal::r1mpyq(), Eigen::internal::r1updt(), randomTest(), oomph::RankFiveTensor< T >::range_check(), oomph::RankFiveTensor< T >::RankFiveTensor(), oomph::Problem::read(), helpers::readArrayFromFile(), Eigen::internal::real_2x2_jacobi_svd(), real_qz(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::rebuild_from_sons(), ref_matrix(), ref_vector(), oomph::RefineableSolidTractionElement< ELEMENT >::refineable_fill_in_contribution_to_residuals_solid_traction(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), oomph::RefineableNavierStokesTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), oomph::RefineableQuadMeshWithMovingCylinder< ELEMENT >::RefineableQuadMeshWithMovingCylinder(), rapidjson::GenericValue< Encoding, Allocator >::RemoveMember(), replicate(), reshape4x4(), reshape_helper(), resize(), oomph::VectorMatrix< VALUE_TYPE >::resize(), oomph::DenseMatrix< T >::resize(), oomph::RankFiveTensor< T >::resize(), oomph::AugmentedBlockFoldLinearSolver::resolve(), oomph::AugmentedBlockPitchForkLinearSolver::resolve(), reverse(), Eigen::Rotation2D< Scalar_ >::Rotation2D(), casting_test< SrcScalar, TgtScalar >::run(), TestMethodDispatching< Scalar, 1 >::run(), shift_test_impl< ArrayType >::run(), typed_logicals_test_impl< ArrayType >::run(), Eigen::internal::first_aligned_impl< Alignment, Derived, false >::run(), Eigen::internal::determinant_impl< Derived, DeterminantType >::run(), Eigen::internal::determinant_impl< Derived, 1 >::run(), Eigen::internal::determinant_impl< Derived, 2 >::run(), Eigen::internal::determinant_impl< Derived, 3 >::run(), Eigen::internal::determinant_impl< Derived, 4 >::run(), Eigen::internal::lpNorm_selector< Derived, p >::run(), Eigen::internal::lpNorm_selector< Derived, 1 >::run(), Eigen::internal::eigenvalues_selector< Derived, IsComplex >::run(), Eigen::internal::eigenvalues_selector< Derived, false >::run(), mapstaticmethods_impl< PlainObjectType, false, IsVector >::run(), mapstaticmethods_impl< PlainObjectType, true, false >::run(), Eigen::internal::rotation_base_generic_product_selector< RotationDerived, DiagonalMatrix< Scalar, Dim, MaxDim >, false >::run(), Eigen::internal::rotation_base_generic_product_selector< RotationDerived, MatrixType, false >::run(), Eigen::internal::extract_data_selector< T, HasUsableDirectAccess >::run(), Eigen::internal::projective_transform_inverse< TransformType, Projective >::run(), Eigen::internal::setIdentity_impl< Derived, Big >::run(), Eigen::internal::setIdentity_impl< Derived, true >::run(), Eigen::internal::eulerangles_assign_impl< System, Other, 3, 3 >::run(), Eigen::internal::lapacke_helpers::lapacke_hqr< MatrixQR, HCoeffs >::run(), Eigen::internal::inplace_transpose_selector< MatrixType, true, false >::run(), Eigen::internal::inplace_transpose_selector< MatrixType, true, true >::run(), Eigen::internal::inplace_transpose_selector< MatrixType, false, MatchPacketSize >::run(), Eigen::internal::transform_take_affine_part< TransformType >::run(), Eigen::internal::transform_take_affine_part< Transform< Scalar, Dim, AffineCompact, Options > >::run(), processTriangularMatrix< MatrixType, 0 >::run(), run_matrix_tests(), run_nesting_ops_1(), run_vector_tests(), rvalue_copyassign(), rvalue_move(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::scramble_FFT(), Eigen::BDCSVD< MatrixType_, Options_ >::secularEq(), selfadjoint(), selfadjointeigensolver(), selfadjointeigensolver_essential_check(), oomph::BiharmonicProblem< DIM >::set_dirichlet_boundary_condition(), oomph::Problem::set_pinned_values_to_zero(), Eigen::QuaternionBase< Derived >::setFromTwoVectors(), Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::setInfos(), RenderingWidget::setLerpMode(), RNG::setLinearCongruentialGeneratorParmeters(), RenderingWidget::setNavMode(), IntersectionOfWalls::setPointsAndLines(), RenderingWidget::setRotationMode(), MortaringHelpers::setup_constraint_elements_at_nodes(), MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::setup_elements(), MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::setup_refinement(), Wall::setupInitialConditions(), SpeciesTest::setupInitialConditions(), oomph::ClampedHermiteShellBoundaryConditionElement::shape(), shift_test(), Eigen::internal::shuffle(), Eigen::internal::shuffle1(), Eigen::internal::shuffle2(), Eigen::internal::shuffle2< true >(), signed_integer_type_tests(), size_triple_t::size_triple_t(), anonymous_namespace{skew_symmetric_matrix3.cpp}::skewSymmetricMultiplication(), oomph::AugmentedBlockFoldLinearSolver::solve(), oomph::AugmentedBlockPitchForkLinearSolver::solve(), oomph::BlockHopfLinearSolver::solve(), oomph::BlockHopfLinearSolver::solve_for_two_rhs(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_lists(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_maps(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_two_arrays(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_two_vectors(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_vectors_of_pairs(), sparse_basic(), sparse_block(), sparse_extra(), specificTest1(), specificTest2(), sphericalHarmonics::sphericalHarmonics(), SpineGravityTractionElement< ELEMENT >::SpineGravityTractionElement(), stable_norm(), Trackball::start(), svd_check_full(), svd_check_max_size_matrix(), svd_compare_to_full(), svd_compute_checks(), svd_fill_random(), svd_inf_nan(), svd_least_square(), svd_min_norm(), svd_option_checks_full_only(), svd_preallocate(), svd_test_solvers(), svd_thin_option_checks(), svd_verify_assert(), svd_verify_assert_full_only(), svd_verify_constructor_options_assert(), swap(), syrk(), test_block_io_zero_stride(), test_chip_as_lvalue(), test_chip_as_lvalue_sycl(), test_compute_block_size(), test_const_slice(), test_contiguous_ref_no_copy(), test_cwise_complex(), test_cwise_real(), test_holes(), Eigen::test_isMuchSmallerThan(), Eigen::test_isUnitary(), test_linear_but_not_vectorizable(), test_mutable_unaryview(), test_nested_ops_with_ref(), test_nnls_returns_NoConvergence_when_maxIterations_is_too_low(), test_nnls_special_case_solves_in_n_iterations(), test_nnls_special_case_solves_in_zero_iterations(), test_reference(), test_spqr_scalar(), test_type2index_list(), testChkder(), testGeneral(), testLmder(), testLmdif(), testLogThenExp(), testMatrixSqrt(), testMatrixType(), testSingular(), testVectorType(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Through(), topLeft2x2Corner(), topLeftCorner(), transformations(), LocalExpansion::translateLocalExpansion(), Multipole::TranslateMultipoleExpansionTo(), triangular_deprecated(), triangular_rect(), triangular_square(), triggerMatrixBadAlloc(), trmv(), typed_logicals_test(), Eigen::umeyama(), unaligned_objects(), unaryview_stride(), UnstructuredImmersedEllipseProblem< ELEMENT >::UnstructuredImmersedEllipseProblem(), MindlinInteraction::updateK_t(), upperbidiag(), Eigen::internal::useSpecificBlockingSizes(), oomph::Node::value(), oomph::VectorMatrix< VALUE_TYPE >::VectorMatrix(), vectorwiseop_array(), vectorwiseop_matrix(), verify_euler(), Eigen::internal::kiss_cpx_fft< Scalar_ >::work(), DPMBase::writeEneTimeStep(), LawinenBox::writeEneTimeStep(), BaseCoupling< M, O >::writeEneTimeStep(), zero_sized_objects(), zeroReduction(), zeroSizedMatrix(), and rapidjson::GenericValue< Encoding, Allocator >::~GenericValue().
n
int int* n
Referenced by her(), hpr(), and if().
pa
const char const char const int const int const RealScalar const RealScalar * pa
Referenced by her(), Eigen::internal::pstore1< Packet16f >(), Eigen::internal::pstore1< Packet16i >(), Eigen::internal::pstore1< Packet2d >(), Eigen::internal::pstore1< Packet4d >(), Eigen::internal::pstore1< Packet4f >(), Eigen::internal::pstore1< Packet8d >(), Eigen::internal::pstore1< Packet8f >(), Eigen::internal::pstore1< Packet8i >(), Eigen::internal::pstore1< Packet8l >(), ClumpParticle::rotatePrincipalDirections(), and rotg().
palpha
int int RealScalar* palpha
Referenced by her(), and hpr().
pap
char int RealScalar RealScalar int RealScalar int RealScalar* pap
Initial value:
{
  typedef void (*functype)(int, Scalar *, const Scalar *, const Scalar *, Scalar)
Referenced by hpr(), tpmv(), and tpsv().
pbeta
const char const char const int const int const RealScalar const RealScalar const int const RealScalar const int const RealScalar * pbeta
px
int int RealScalar RealScalar* px
Referenced by her(), and hpr().
py
int int RealScalar RealScalar int RealScalar* py
return
if n return
uplo
const char * uplo
ZHEMV performs the matrix-vector operation
y := alpha*A*x + beta*y,
where alpha and beta are scalars, x and y are n element vectors and A is an n by n hermitian matrix.
ZHPR2 performs the hermitian rank 2 operation
A := alpha*x*conjg(y') + conjg(alpha)*y*conjg(x') + A,
where alpha is a scalar, x and y are n element vectors and A is an n by n hermitian matrix, supplied in packed form.
ZHER2 performs the hermitian rank 2 operation
A := alpha*x*conjg(y') + conjg(alpha)*y*conjg(x') + A,
where alpha is a scalar, x and y are n element vectors and A is an n by n hermitian matrix.
DTBSV solves one of the systems of equations
A*x = b, or A'*x = b,
where b and x are n element vectors and A is an n by n unit, or non-unit, upper or lower triangular band matrix, with (k + 1) diagonals.
No test for singularity or near-singularity is included in this routine. Such tests must be performed before calling this routine.
DSPR2 performs the symmetric rank 2 operation
A := alpha*x*y' + alpha*y*x' + A,
where alpha is a scalar, x and y are n element vectors and A is an n by n symmetric matrix, supplied in packed form.
Referenced by check_uplo(), Eigen::internal::lapacke_helpers::lapacke_llt< Scalar, Mode >::EIGEN_STATIC_ASSERT(), her(), hpr(), and if().
x
Scalar* x = reinterpret_cast<const Scalar *>(px)
Referenced by her(), and hpr().
x_cpy
Scalar * x_cpy = get_compact_vector(x, *n, *incx)
Referenced by copy_back(), her(), hpr(), Eigen::internal::psincos_double(), and Eigen::internal::psincos_float().
y
Scalar* y = reinterpret_cast<Scalar *>(py)
y_cpy
Scalar * y_cpy = get_compact_vector(y, *n, *incy)