MercuryDPM: geometry.cpp File Reference
geometry.cpp File Reference
#include <iostream>
#include <Eigen/Geometry>
#include <bench/BenchTimer.h>
Classes
struct ToRotationMatrixWrapper< T >
struct get_dim< T >
struct get_dim< Matrix< S, R, C, O, MR, MC > >
struct bench_impl< Transformation, N >
struct bench_impl< Transformation, 0 >
Macros
#define SCALAR float
#define SIZE 8
Typedefs
typedef SCALAR Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef Matrix< RealScalar, Dynamic, Dynamic > A
typedef Matrix< Scalar, Dynamic, Dynamic > B
typedef Matrix< Scalar, Dynamic, Dynamic > C
typedef Matrix< RealScalar, Dynamic, Dynamic > M
Functions
template<typename Transformation , typename Data >
EIGEN_DONT_INLINE void transform (const Transformation &t, Data &data)
template<typename Scalar , typename Data >
EIGEN_DONT_INLINE void transform (const Quaternion< Scalar > &t, Data &data)
template<typename QType , typename Data >
EIGEN_DONT_INLINE void transform (const ToRotationMatrixWrapper< QType > &t, Data &data)
template<typename Scalar , int Dim, typename Data >
EIGEN_DONT_INLINE void transform (const Transform< Scalar, Dim, Projective > &t, Data &data)
template<typename Transformation >
EIGEN_DONT_INLINE void bench (const std::string &msg, const Transformation &t)
int main (int argc, char **argv)
Macro Definition Documentation
SCALAR
#define SCALAR float
SIZE
#define SIZE 8
Typedef Documentation
A
typedef Matrix<RealScalar, Dynamic, Dynamic> A
B
typedef Matrix< Scalar, Dynamic, Dynamic> B
C
typedef Matrix<Scalar, Dynamic, Dynamic> C
M
typedef Matrix<RealScalar, Dynamic, Dynamic> M
RealScalar
typedef NumTraits<Scalar>::Real RealScalar
Scalar
typedef SCALAR Scalar
Function Documentation
bench()
template<typename Transformation > EIGEN_DONT_INLINE void bench (const std::string & msg, const Transformation & t)
{
   cout << msg << " ";
   bench_impl<Transformation, SIZE>::run(t);
   std::cout << "\n";
 }
References bench_impl< Transformation, N >::run(), and plotPSD::t.
Referenced by main().
main()
int main (int argc , char ** argv)
{
   Matrix<Scalar, 3, 4> mat34;
   mat34.setRandom();
   Transform<Scalar, 3, Isometry> iso3(mat34);
   Transform<Scalar, 3, Affine> aff3(mat34);
   Transform<Scalar, 3, AffineCompact> caff3(mat34);
   Transform<Scalar, 3, Projective> proj3(mat34);
   Quaternion<Scalar> quat;
   quat.setIdentity();
   ToRotationMatrixWrapper<Quaternion<Scalar> > quatmat(quat);
   Matrix<Scalar, 3, 3> mat33;
   mat33.setRandom();
   cout.precision(4);
   std::cout << "N          ";
   for (int i = 0; i < SIZE; ++i) {
     cout.width(9);
     cout << i + 1 << " ";
   }
   cout << "\n";
   bench("matrix 3x3", mat33);
   bench("quaternion", quat);
   bench("quat-mat  ", quatmat);
   bench("isometry3 ", iso3);
   bench("affine3   ", aff3);
   bench("c affine3 ", caff3);
   bench("proj3     ", proj3);
 }
References bench(), i, Eigen::QuaternionBase< Derived >::setIdentity(), Eigen::PlainObjectBase< Derived >::setRandom(), and SIZE.
transform() [1/4]
template<typename Scalar , typename Data > EIGEN_DONT_INLINE void transform (const Quaternion< Scalar > & t, Data & data)
{
   EIGEN_ASM_COMMENT("begin quat");
   for (int i = 0; i < data.cols(); ++i) data.col(i) = t * data.col(i);
   EIGEN_ASM_COMMENT("end quat");
 }
References data, EIGEN_ASM_COMMENT, i, and plotPSD::t.
transform() [2/4]
template<typename QType , typename Data > EIGEN_DONT_INLINE void transform (const ToRotationMatrixWrapper< QType > & t, Data & data)
{
   EIGEN_ASM_COMMENT("begin quat via mat");
   data = t.object.toRotationMatrix() * data;
   EIGEN_ASM_COMMENT("end quat via mat");
 }
References data, EIGEN_ASM_COMMENT, and plotPSD::t.
transform() [3/4]
template<typename Scalar , int Dim, typename Data > EIGEN_DONT_INLINE void transform (const Transform< Scalar, Dim, Projective > & t, Data & data)
{
   data = (t * data.colwise().homogeneous()).template block<Dim, Data::ColsAtCompileTime>(0, 0);
 }
References data, and plotPSD::t.
transform() [4/4]
template<typename Transformation , typename Data > EIGEN_DONT_INLINE void transform (const Transformation & t, Data & data)
{
   EIGEN_ASM_COMMENT("begin");
   data = t * data;
   EIGEN_ASM_COMMENT("end");
 }
References data, EIGEN_ASM_COMMENT, and plotPSD::t.
Referenced by addObject(), helpers::lower(), SmallMatrix< numberOfRows, numberOfColumns >::operator*(), SmallVector< numberOfRows >::operator*(), SmallVector< numberOfRows >::operator*=(), SmallMatrix< numberOfRows, numberOfColumns >::operator*=(), SmallMatrix< numberOfRows, numberOfColumns >::operator+(), SmallVector< numberOfRows >::operator+(), SmallMatrix< numberOfRows, numberOfColumns >::operator+=(), SmallVector< numberOfRows >::operator+=(), SmallMatrix< numberOfRows, numberOfColumns >::operator-(), SmallVector< numberOfRows >::operator-(), SmallMatrix< numberOfRows, numberOfColumns >::operator-=(), SmallVector< numberOfRows >::operator-=(), SmallVector< numberOfRows >::operator/(), SmallMatrix< numberOfRows, numberOfColumns >::operator/(), SmallVector< numberOfRows >::operator/=(), SmallMatrix< numberOfRows, numberOfColumns >::operator/=(), Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::permute_inner(), bench_impl< Transformation, N >::run(), Eigen::internal::transform_construct_from_matrix< Other, AffineCompact, Options, Dim, HDim, HDim, HDim >::run(), Eigen::internal::transform_construct_from_matrix< Other, Mode, Options, Dim, HDim, Dim, Dim >::run(), Eigen::internal::transform_construct_from_matrix< Other, Mode, Options, Dim, HDim, Dim, HDim >::run(), Eigen::internal::transform_construct_from_matrix< Other, Mode, Options, Dim, HDim, HDim, HDim >::run(), and BasicUnionOfWalls::writeVTK().