MercuryDPM: GlobalParameters::TestPMLMapping Class Reference
GlobalParameters::TestPMLMapping Class Reference
Public Member Functions
TestPMLMapping ()
Default constructor (empty)
std::complex< double > gamma (const double &nu_i, const double &pml_width_i, const double &k_squared_local, const double &alpha_shift)
TestPMLMapping ()
Default constructor (empty)
std::complex< double > gamma (const double &nu_i, const double &pml_width_i, const double &k_squared_local, const double &alpha_shift)
TestPMLMapping ()
Default constructor (empty)
std::complex< double > gamma (const double &nu_i, const double &pml_width_i, const double &k_squared_local, const double &alpha_shift=0.0)
Public Member Functions inherited from oomph::PMLMapping
PMLMapping ()
Default constructor (empty)
Detailed Description
New mapping function that makes the mapping independent of the PML thickness
Constructor & Destructor Documentation
TestPMLMapping() [1/3]
GlobalParameters::TestPMLMapping::TestPMLMapping () inline
Default constructor (empty)
 {};
TestPMLMapping() [2/3]
GlobalParameters::TestPMLMapping::TestPMLMapping () inline
Default constructor (empty)
 {};
TestPMLMapping() [3/3]
GlobalParameters::TestPMLMapping::TestPMLMapping () inline
Default constructor (empty)
 {};
Member Function Documentation
gamma() [1/3]
std::complex<double> GlobalParameters::TestPMLMapping::gamma (const double & nu_i, const double & pml_width_i, const double & k_squared_local, const double & alpha_shift) inline virtual
Overwrite the pure PML mapping coefficient function to return the coeffcients proposed by Bermudez et al
Implements oomph::PMLMapping.
    {
     // The "effective k^2" is shifted, so we shift the k used in the
     // transformation too
     std::complex<double> k_shifted=
      sqrt(k_squared_local*std::complex<double>(1.0,alpha_shift));
     // Return the gamma in J++, with the shifted k
     return (1.0/k_shifted)*std::complex<double>
      (0.0,1.0/(std::fabs(pml_width_i-nu_i)));
    } // End of gamma
References boost::multiprecision::fabs(), and sqrt().
gamma() [2/3]
std::complex<double> GlobalParameters::TestPMLMapping::gamma (const double & nu_i, const double & pml_width_i, const double & k_squared_local, const double & alpha_shift) inline virtual
Overwrite the pure PML mapping coefficient function to return the coeffcients proposed by Bermudez et al
Implements oomph::PMLMapping.
    {
     // If we're disabling PMLs
     if (!Disable_pml_flag)
     {
      // The "effective k^2" is shifted, so we shift the k used in the
      // transformation too
      std::complex<double> k_shifted=
       sqrt(k_squared_local*std::complex<double>(1.0,alpha_shift));
      // Return the gamma in J++, with the shifted k
      return (1.0/k_shifted)*std::complex<double>
       (0.0,1.0/(std::fabs(pml_width_i-nu_i)));
     }
     else
     {
      // Otherwise just return the value 1.0
      return 1.0;
     }
    } // End of gamma
References GlobalParameters::Disable_pml_flag, boost::multiprecision::fabs(), and sqrt().
gamma() [3/3]
std::complex<double> GlobalParameters::TestPMLMapping::gamma (const double & nu_i, const double & pml_width_i, const double & k_squared_local, const double & alpha_shift = 0.0) inline virtual
Overwrite the pure PML mapping coefficient function to return the coeffcients proposed by Bermudez et al
Implements oomph::PMLMapping.
    {
       // (return) gamma = 1 + (1/k) * (i/|outer_boundary - x|)
       /*return 1.0 + (1.0 / std::complex<double> (sqrt(k_squared_local), 0))
        * std::complex<double>
         (0.0, 1.0/(std::fabs(pml_width_i - nu_i)));*/
      return 1.0 + (1.0 / std::complex<double> (sqrt(k_squared_local), 0))
           * std::complex<double>
            (0.0, 2.0/(std::fabs(pml_width_i - nu_i)));
    }
References boost::multiprecision::fabs(), and sqrt().
The documentation for this class was generated from the following files:
structured_cubic_point_source.cc
multigrid/helmholtz_multigrid/unstructured_two_d_helmholtz.cc
unstructured_two_d_helmholtz_scattering.cc