MercuryDPM: RectangleWithHoleMesh< ELEMENT > Class Template Reference
RectangleWithHoleMesh< ELEMENT > Class Template Reference
Domain-based mesh for rectangular mesh with circular hole.
Public Member Functions
RectangleWithHoleMesh (GeomObject *cylinder_pt, const double &length, const double &height, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
RectangleWithHoleDomain * domain_pt ()
Access function to the domain.
RectangleWithHoleMesh (GeomObject *cylinder_pt, const double &length, const double &height, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
RectangleWithHoleDomain * domain_pt ()
Access function to the domain.
const double & length ()
Access function to length.
const double & height ()
Access function to height.
RectangleWithHoleMesh (GeomObject *cylinder_pt, const double &length, const double &height, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
RectangleWithHoleDomain * domain_pt ()
Access function to the domain.
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void setup_boundary_element_info ()
virtual void setup_boundary_element_info (std::ostream &outfile)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Protected Attributes
RectangleWithHoleDomain * Domain_pt
Pointer to the domain.
double Length
double Height
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Detailed Description
template<class ELEMENT>
class RectangleWithHoleMesh< ELEMENT >
Domain-based mesh for rectangular mesh with circular hole.
/////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
RectangleWithHoleMesh() [1/3]
template<class ELEMENT > RectangleWithHoleMesh< ELEMENT >::RectangleWithHoleMesh (GeomObject * cylinder_pt, const double & length, const double & height, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Constructor: Pass pointer to geometric object that represents the cylinder, the length and height of the domain. The GeomObject must be parametrised such that \(\zeta \in [0,2\pi]\) sweeps around the circumference in anticlockwise direction. Timestepper defaults to Steady default timestepper.
   {
    //Create the domain
    Domain_pt = new RectangleWithHoleDomain(cylinder_pt,length,height);
    //Initialise the node counter
    unsigned long node_count=0;
    //Vectors used to get data from domains
    Vector<double> s(2),r(2);
    //Setup temporary storage for the Node
    Vector<Node*> Tmp_node_pt;
    //Now blindly loop over the macro elements and associate and finite
    //element with each
    unsigned nmacro_element = Domain_pt->nmacro_element();
    for(unsigned e=0;e<nmacro_element;e++)
     {
      //Create the FiniteElement and add to the Element_pt Vector
      Element_pt.push_back(new ELEMENT);
      //Read out the number of linear points in the element
      unsigned np =
       dynamic_cast<ELEMENT*>(finite_element_pt(e))->nnode_1d();
      //Loop over nodes in the column
      for(unsigned l1=0;l1<np;l1++)
       {
        //Loop over the nodes in the row
        for(unsigned l2=0;l2<np;l2++)
         {
          //Allocate the memory for the node
          Tmp_node_pt.push_back(finite_element_pt(e)->
                                construct_node(l1*np+l2,time_stepper_pt));
          //Read out the position of the node from the macro element
          s[0] = -1.0 + 2.0*(double)l2/(double)(np-1);
          s[1] = -1.0 + 2.0*(double)l1/(double)(np-1);
          Domain_pt->macro_element_pt(e)->macro_map(s,r);
          //Set the position of the node
          Tmp_node_pt[node_count]->x(0) = r[0];
          Tmp_node_pt[node_count]->x(1) = r[1];
          //Increment the node number
          node_count++;
         }
       }
     } //End of loop over macro elements
    //Now the elements have been created, but there will be nodes in
    //common, need to loop over the common edges and sort it, by reassigning
    //pointers and the deleting excess nodes
    //Read out the number of linear points in the element
    unsigned np=dynamic_cast<ELEMENT*>(finite_element_pt(0))->nnode_1d();
    //Edge between Elements 0 and 8
    for(unsigned n=0;n<np;n++)
     {
      finite_element_pt(8)->node_pt(n*np + (np-1)) =
       finite_element_pt(0)->node_pt(n*np);
      //Remover the nodes in element 8 from the temporary node list
      delete Tmp_node_pt[8*np*np + n*np + (np-1)];
      Tmp_node_pt[8*np*np + n*np + (np-1)] = 0;
     }
    //Edge between Elements 0 and 1
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 1 to be the same as in element 0
      finite_element_pt(1)->node_pt(n*np)
       = finite_element_pt(0)->node_pt((np-1)*np+np-1-n);
      //Remove the nodes in element 1 from the temporary node list
      delete Tmp_node_pt[np*np + n*np];
      Tmp_node_pt[np*np + n*np] = 0;
     }
    //Edge between Elements 0 and 3
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 3 to be the same as in element 0
      finite_element_pt(3)->node_pt(n*np)
       = finite_element_pt(0)->node_pt(n);
      //Remove the nodes in element 3 from the temporary node list
      delete Tmp_node_pt[3*np*np + n*np];
      Tmp_node_pt[3*np*np + n*np] = 0;
     }
    //Edge between Element 1 and 2
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 2 to be the same as in element 1
      finite_element_pt(2)->node_pt(np*(np-1)+n)
       = finite_element_pt(1)->node_pt(np*n+np-1);
      //Remove the nodes in element 2 from the temporary node list
      delete Tmp_node_pt[2*np*np + np*(np-1)+n];
      Tmp_node_pt[2*np*np + np*(np-1)+n] = 0;
     }
    //Edge between Element 3 and 2
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 2 to be the same as in element 3
      finite_element_pt(2)->node_pt(n)
       = finite_element_pt(3)->node_pt(np*(np-n-1)+np-1);
      //Remove the nodes in element 2 from the temporary node list
      delete Tmp_node_pt[2*np*np + n];
      Tmp_node_pt[2*np*np + n] = 0;
     }
    //Edge between Element 2 and 4
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 4 to be the same as in element 2
      finite_element_pt(4)->node_pt(n*np)
       = finite_element_pt(2)->node_pt(np*n+np-1);
      //Remove the nodes in element 4 from the temporary node list
      delete Tmp_node_pt[4*np*np + n*np];
      Tmp_node_pt[4*np*np + n*np] = 0;
     }
    //Edge between Element 4 and 5
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 5 to be the same as in element 4
      finite_element_pt(5)->node_pt(n*np)
       = finite_element_pt(4)->node_pt(np*n+np-1);
      //Remove the nodes in element 5 from the temporary node list
      delete Tmp_node_pt[5*np*np + n*np];
      Tmp_node_pt[5*np*np + n*np] = 0;
     }
    //Edge between Element 5 and 6
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 6 to be the same as in element 5
      finite_element_pt(6)->node_pt(n*np)
       = finite_element_pt(5)->node_pt(np*n+np-1);
      //Remove the nodes in element 6 from the temporary node list
      delete Tmp_node_pt[6*np*np + n*np];
      Tmp_node_pt[6*np*np + n*np] = 0;
     }
    //Edge between Element 6 and 7
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 7 to be the same as in element 6
      finite_element_pt(7)->node_pt(n*np)
       = finite_element_pt(6)->node_pt(np*n+np-1);
      //Remove the nodes in element 7 from the temporary node list
      delete Tmp_node_pt[7*np*np + n*np];
      Tmp_node_pt[7*np*np + n*np] = 0;
     }
    //Now set the actual true nodes
    for(unsigned long n=0;n<node_count;n++)
     {
      if(Tmp_node_pt[n]!=0) {Node_pt.push_back(Tmp_node_pt[n]);}
     }
    //Finally set the nodes on the boundaries
    set_nboundary(5);
    for(unsigned n=0;n<np;n++)
     {
      //Left hand side
      Node* nod_pt=finite_element_pt(8)->node_pt(n*np);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(3,nod_pt);
      //Right hand side
      nod_pt=finite_element_pt(7)->node_pt(n*np+np-1);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(1,nod_pt);
      //First part of lower boundary
      nod_pt = finite_element_pt(8)->node_pt(n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(0,nod_pt);
      //First part of upper boundary
      nod_pt = finite_element_pt(8)->node_pt(np*(np-1) + n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(2,nod_pt);
      //First part of hole boundary
      nod_pt=finite_element_pt(3)->node_pt(np*(np-1)+n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(4,nod_pt);
     }
    for(unsigned n=1;n<np;n++)
     {
      //Second part of lower boundary
      Node* nod_pt=finite_element_pt(3)->node_pt(n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(0,nod_pt);
      //Third part of lower boundary
      nod_pt=finite_element_pt(4)->node_pt(n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(0,nod_pt);
      //Second part of upper boundary
      nod_pt=finite_element_pt(1)->node_pt(np*(np-1)+n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(2,nod_pt);
      //Third part of upper boundary
      nod_pt=finite_element_pt(4)->node_pt(np*(np-1)+n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(2,nod_pt);
      //Next part of hole
      nod_pt=finite_element_pt(2)->node_pt(n*np);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(4,nod_pt);
     }
    for(unsigned n=1;n<np;n++)
     {
      //Third part of lower boundary
      Node* nod_pt=finite_element_pt(5)->node_pt(n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(0,nod_pt);
      //Third part of upper boundary
      nod_pt=finite_element_pt(5)->node_pt(np*(np-1)+n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(2,nod_pt);
     }
    for(unsigned n=1;n<np;n++)
     {
      //Fourth part of lower boundary
      Node* nod_pt=finite_element_pt(6)->node_pt(n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(0,nod_pt);
      //Fourth part of upper boundary
      nod_pt=finite_element_pt(6)->node_pt(np*(np-1)+n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(2,nod_pt);
     }
    for(unsigned n=1;n<np;n++)
     {
      //Final part of lower boundary
      Node* nod_pt=finite_element_pt(7)->node_pt(n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(0,nod_pt);
      //Final part of upper boundary
      nod_pt=finite_element_pt(7)->node_pt(np*(np-1)+n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(2,nod_pt);
      //Next part of hole
      nod_pt=finite_element_pt(1)->node_pt(np-n-1);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(4,nod_pt);
     }
    for(unsigned n=1;n<np-1;n++)
     {
      //Final part of hole
      Node* nod_pt=finite_element_pt(0)->node_pt(np*(np-n-1)+np-1);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(4,nod_pt);
     }
  }
References e(), Global_Physical_Variables::height(), n, UniformPSDSelfTest::r, and s.
RectangleWithHoleMesh() [2/3]
template<class ELEMENT > RectangleWithHoleMesh< ELEMENT >::RectangleWithHoleMesh (GeomObject * cylinder_pt, const double & length, const double & height, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Constructor: Pass pointer to geometric object that represents the cylinder, the length and height of the domain. The GeomObject must be parametrised such that \(\zeta \in [0,2\pi]\) sweeps around the circumference in anticlockwise direction. Timestepper defaults to Steady default timestepper.
   {
    //Create the domain
    Domain_pt = new RectangleWithHoleDomain(cylinder_pt,length,height);
    Length = length; Height = height;
    //Initialise the node counter
    unsigned long node_count=0;
    //Vectors used to get data from domains
    Vector<double> s(2),r(2);
    //Setup temporary storage for the Node
    Vector<Node*> Tmp_node_pt;
    //Now blindly loop over the macro elements and associate and finite
    //element with each
    unsigned nmacro_element = Domain_pt->nmacro_element();
    for(unsigned e=0;e<nmacro_element;e++)
     {
      //Create the FiniteElement and add to the Element_pt Vector
      Element_pt.push_back(new ELEMENT);
      //Read out the number of linear points in the element
      unsigned np =
       dynamic_cast<ELEMENT*>(finite_element_pt(e))->nnode_1d();
      //Loop over nodes in the column
      for(unsigned l1=0;l1<np;l1++)
       {
        //Loop over the nodes in the row
        for(unsigned l2=0;l2<np;l2++)
         {
          //Allocate the memory for the node
          Tmp_node_pt.push_back(finite_element_pt(e)->
                                construct_node(l1*np+l2,time_stepper_pt));
          //Read out the position of the node from the macro element
          s[0] = -1.0 + 2.0*(double)l2/(double)(np-1);
          s[1] = -1.0 + 2.0*(double)l1/(double)(np-1);
          Domain_pt->macro_element_pt(e)->macro_map(s,r);
          //Set the position of the node
          Tmp_node_pt[node_count]->x(0) = r[0];
          Tmp_node_pt[node_count]->x(1) = r[1];
          //Increment the node number
          node_count++;
         }
       }
     } //End of loop over macro elements
    //Now the elements have been created, but there will be nodes in
    //common, need to loop over the common edges and sort it, by reassigning
    //pointers and the deleting excess nodes
    //Read out the number of linear points in the element
    unsigned np=dynamic_cast<ELEMENT*>(finite_element_pt(0))->nnode_1d();
    //Edge between Elements 0 and 8
    for(unsigned n=0;n<np;n++)
     {
      finite_element_pt(8)->node_pt(n*np + (np-1)) =
       finite_element_pt(0)->node_pt(n*np);
      //Remover the nodes in element 8 from the temporary node list
      delete Tmp_node_pt[8*np*np + n*np + (np-1)];
      Tmp_node_pt[8*np*np + n*np + (np-1)] = 0;
     }
    //Edge between Elements 0 and 1
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 1 to be the same as in element 0
      finite_element_pt(1)->node_pt(n*np)
       = finite_element_pt(0)->node_pt((np-1)*np+np-1-n);
      //Remove the nodes in element 1 from the temporary node list
      delete Tmp_node_pt[np*np + n*np];
      Tmp_node_pt[np*np + n*np] = 0;
     }
    //Edge between Elements 0 and 3
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 3 to be the same as in element 0
      finite_element_pt(3)->node_pt(n*np)
       = finite_element_pt(0)->node_pt(n);
      //Remove the nodes in element 3 from the temporary node list
      delete Tmp_node_pt[3*np*np + n*np];
      Tmp_node_pt[3*np*np + n*np] = 0;
     }
    //Edge between Element 1 and 2
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 2 to be the same as in element 1
      finite_element_pt(2)->node_pt(np*(np-1)+n)
       = finite_element_pt(1)->node_pt(np*n+np-1);
      //Remove the nodes in element 2 from the temporary node list
      delete Tmp_node_pt[2*np*np + np*(np-1)+n];
      Tmp_node_pt[2*np*np + np*(np-1)+n] = 0;
     }
    //Edge between Element 3 and 2
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 2 to be the same as in element 3
      finite_element_pt(2)->node_pt(n)
       = finite_element_pt(3)->node_pt(np*(np-n-1)+np-1);
      //Remove the nodes in element 2 from the temporary node list
      delete Tmp_node_pt[2*np*np + n];
      Tmp_node_pt[2*np*np + n] = 0;
     }
    //Edge between Element 2 and 4
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 4 to be the same as in element 2
      finite_element_pt(4)->node_pt(n*np)
       = finite_element_pt(2)->node_pt(np*n+np-1);
      //Remove the nodes in element 4 from the temporary node list
      delete Tmp_node_pt[4*np*np + n*np];
      Tmp_node_pt[4*np*np + n*np] = 0;
     }
    //Edge between Element 4 and 5
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 5 to be the same as in element 4
      finite_element_pt(5)->node_pt(n*np)
       = finite_element_pt(4)->node_pt(np*n+np-1);
      //Remove the nodes in element 5 from the temporary node list
      delete Tmp_node_pt[5*np*np + n*np];
      Tmp_node_pt[5*np*np + n*np] = 0;
     }
    //Edge between Element 5 and 6
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 6 to be the same as in element 5
      finite_element_pt(6)->node_pt(n*np)
       = finite_element_pt(5)->node_pt(np*n+np-1);
      //Remove the nodes in element 6 from the temporary node list
      delete Tmp_node_pt[6*np*np + n*np];
      Tmp_node_pt[6*np*np + n*np] = 0;
     }
    //Edge between Element 6 and 7
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 7 to be the same as in element 6
      finite_element_pt(7)->node_pt(n*np)
       = finite_element_pt(6)->node_pt(np*n+np-1);
      //Remove the nodes in element 7 from the temporary node list
      delete Tmp_node_pt[7*np*np + n*np];
      Tmp_node_pt[7*np*np + n*np] = 0;
     }
    //Now set the actual true nodes
    for(unsigned long n=0;n<node_count;n++)
     {
      if(Tmp_node_pt[n]!=0) {Node_pt.push_back(Tmp_node_pt[n]);}
     }
    //Finally set the nodes on the boundaries
    set_nboundary(5);
    for(unsigned n=0;n<np;n++)
     {
      //Left hand side
      Node* nod_pt=finite_element_pt(8)->node_pt(n*np);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(3,nod_pt);
      //Right hand side
      nod_pt=finite_element_pt(7)->node_pt(n*np+np-1);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(1,nod_pt);
      //First part of lower boundary
      nod_pt = finite_element_pt(8)->node_pt(n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(0,nod_pt);
      //First part of upper boundary
      nod_pt = finite_element_pt(8)->node_pt(np*(np-1) + n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(2,nod_pt);
      //First part of hole boundary
      nod_pt=finite_element_pt(3)->node_pt(np*(np-1)+n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(4,nod_pt);
     }
    for(unsigned n=1;n<np;n++)
     {
      //Second part of lower boundary
      Node* nod_pt=finite_element_pt(3)->node_pt(n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(0,nod_pt);
      //Third part of lower boundary
      nod_pt=finite_element_pt(4)->node_pt(n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(0,nod_pt);
      //Second part of upper boundary
      nod_pt=finite_element_pt(1)->node_pt(np*(np-1)+n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(2,nod_pt);
      //Third part of upper boundary
      nod_pt=finite_element_pt(4)->node_pt(np*(np-1)+n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(2,nod_pt);
      //Next part of hole
      nod_pt=finite_element_pt(2)->node_pt(n*np);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(4,nod_pt);
     }
    for(unsigned n=1;n<np;n++)
     {
      //Third part of lower boundary
      Node* nod_pt=finite_element_pt(5)->node_pt(n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(0,nod_pt);
      //Third part of upper boundary
      nod_pt=finite_element_pt(5)->node_pt(np*(np-1)+n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(2,nod_pt);
     }
    for(unsigned n=1;n<np;n++)
     {
      //Fourth part of lower boundary
      Node* nod_pt=finite_element_pt(6)->node_pt(n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(0,nod_pt);
      //Fourth part of upper boundary
      nod_pt=finite_element_pt(6)->node_pt(np*(np-1)+n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(2,nod_pt);
     }
    for(unsigned n=1;n<np;n++)
     {
      //Final part of lower boundary
      Node* nod_pt=finite_element_pt(7)->node_pt(n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(0,nod_pt);
      //Final part of upper boundary
      nod_pt=finite_element_pt(7)->node_pt(np*(np-1)+n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(2,nod_pt);
      //Next part of hole
      nod_pt=finite_element_pt(1)->node_pt(np-n-1);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(4,nod_pt);
     }
    for(unsigned n=1;n<np-1;n++)
     {
      //Final part of hole
      Node* nod_pt=finite_element_pt(0)->node_pt(np*(np-n-1)+np-1);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(4,nod_pt);
     }
  }
References e(), GlobalParameters::Height, Global_Physical_Variables::height(), Global_Physical_Variables::Length, n, UniformPSDSelfTest::r, and s.
RectangleWithHoleMesh() [3/3]
template<class ELEMENT > RectangleWithHoleMesh< ELEMENT >::RectangleWithHoleMesh (GeomObject * cylinder_pt, const double & length, const double & height, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Constructor: Pass pointer to geometric object that represents the cylinder, the length and height of the domain. The GeomObject must be parametrised such that \(\zeta \in [0,2\pi]\) sweeps around the circumference in anticlockwise direction. Timestepper defaults to Steady default timestepper.
   {
    //Create the domain
    Domain_pt = new RectangleWithHoleDomain(cylinder_pt,length,height);
    //Initialise the node counter
    unsigned long node_count=0;
    //Vectors used to get data from domains
    Vector<double> s(2),r(2);
    //Setup temporary storage for the Node
    Vector<Node*> Tmp_node_pt;
    //Now blindly loop over the macro elements and associate and finite
    //element with each
    unsigned nmacro_element = Domain_pt->nmacro_element();
    for(unsigned e=0;e<nmacro_element;e++)
     {
      //Create the FiniteElement and add to the Element_pt Vector
      Element_pt.push_back(new ELEMENT);
      //Read out the number of linear points in the element
      unsigned np =
       dynamic_cast<ELEMENT*>(finite_element_pt(e))->nnode_1d();
      //Loop over nodes in the column
      for(unsigned l1=0;l1<np;l1++)
       {
        //Loop over the nodes in the row
        for(unsigned l2=0;l2<np;l2++)
         {
          //Allocate the memory for the node
          Tmp_node_pt.push_back(finite_element_pt(e)->
                                construct_node(l1*np+l2,time_stepper_pt));
          //Read out the position of the node from the macro element
          s[0] = -1.0 + 2.0*(double)l2/(double)(np-1);
          s[1] = -1.0 + 2.0*(double)l1/(double)(np-1);
          Domain_pt->macro_element_pt(e)->macro_map(s,r);
          //Set the position of the node
          Tmp_node_pt[node_count]->x(0) = r[0];
          Tmp_node_pt[node_count]->x(1) = r[1];
          //Increment the node number
          node_count++;
         }
       }
     } //End of loop over macro elements
    //Now the elements have been created, but there will be nodes in
    //common, need to loop over the common edges and sort it, by reassigning
    //pointers and the deleting excess nodes
    //Read out the number of linear points in the element
    unsigned np=dynamic_cast<ELEMENT*>(finite_element_pt(0))->nnode_1d();
    //Edge between Elements 0 and 1
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 1 to be the same as in element 0
      finite_element_pt(1)->node_pt(n*np)
       = finite_element_pt(0)->node_pt((np-1)*np+np-1-n);
      //Remove the nodes in element 1 from the temporary node list
      delete Tmp_node_pt[np*np + n*np];
      Tmp_node_pt[np*np + n*np] = 0;
     }
    //Edge between Elements 0 and 3
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 3 to be the same as in element 0
      finite_element_pt(3)->node_pt(n*np)
       = finite_element_pt(0)->node_pt(n);
      //Remove the nodes in element 3 from the temporary node list
      delete Tmp_node_pt[3*np*np + n*np];
      Tmp_node_pt[3*np*np + n*np] = 0;
     }
    //Edge between Element 1 and 2
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 2 to be the same as in element 1
      finite_element_pt(2)->node_pt(np*(np-1)+n)
       = finite_element_pt(1)->node_pt(np*n+np-1);
      //Remove the nodes in element 2 from the temporary node list
      delete Tmp_node_pt[2*np*np + np*(np-1)+n];
      Tmp_node_pt[2*np*np + np*(np-1)+n] = 0;
     }
    //Edge between Element 3 and 2
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 2 to be the same as in element 3
      finite_element_pt(2)->node_pt(n)
       = finite_element_pt(3)->node_pt(np*(np-n-1)+np-1);
      //Remove the nodes in element 2 from the temporary node list
      delete Tmp_node_pt[2*np*np + n];
      Tmp_node_pt[2*np*np + n] = 0;
     }
    //Edge between Element 2 and 4
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 4 to be the same as in element 2
      finite_element_pt(4)->node_pt(n*np)
       = finite_element_pt(2)->node_pt(np*n+np-1);
      //Remove the nodes in element 4 from the temporary node list
      delete Tmp_node_pt[4*np*np + n*np];
      Tmp_node_pt[4*np*np + n*np] = 0;
     }
    //Edge between Element 4 and 5
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 5 to be the same as in element 4
      finite_element_pt(5)->node_pt(n*np)
       = finite_element_pt(4)->node_pt(np*n+np-1);
      //Remove the nodes in element 5 from the temporary node list
      delete Tmp_node_pt[5*np*np + n*np];
      Tmp_node_pt[5*np*np + n*np] = 0;
     }
    //Edge between Element 5 and 6
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 6 to be the same as in element 5
      finite_element_pt(6)->node_pt(n*np)
       = finite_element_pt(5)->node_pt(np*n+np-1);
      //Remove the nodes in element 6 from the temporary node list
      delete Tmp_node_pt[6*np*np + n*np];
      Tmp_node_pt[6*np*np + n*np] = 0;
     }
    //Edge between Element 6 and 7
    for(unsigned n=0;n<np;n++)
     {
      //Set the nodes in element 7 to be the same as in element 6
      finite_element_pt(7)->node_pt(n*np)
       = finite_element_pt(6)->node_pt(np*n+np-1);
      //Remove the nodes in element 7 from the temporary node list
      delete Tmp_node_pt[7*np*np + n*np];
      Tmp_node_pt[7*np*np + n*np] = 0;
     }
    //Now set the actual true nodes
    for(unsigned long n=0;n<node_count;n++)
     {
      if(Tmp_node_pt[n]!=0) {Node_pt.push_back(Tmp_node_pt[n]);}
     }
    //Finally set the nodes on the boundaries
    set_nboundary(5);
    for(unsigned n=0;n<np;n++)
     {
      //Left hand side
      Node* nod_pt=finite_element_pt(0)->node_pt(n*np);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(3,nod_pt);
      //Right hand side
      nod_pt=finite_element_pt(7)->node_pt(n*np+np-1);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(1,nod_pt);
      //First part of lower boundary
      nod_pt=finite_element_pt(3)->node_pt(n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(0,nod_pt);
      //First part of upper boundary
      nod_pt=finite_element_pt(1)->node_pt(np*(np-1)+n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(2,nod_pt);
      //First part of hole boundary
      nod_pt=finite_element_pt(3)->node_pt(np*(np-1)+n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(4,nod_pt);
     }
    for(unsigned n=1;n<np;n++)
     {
      //Second part of lower boundary
      Node* nod_pt=finite_element_pt(4)->node_pt(n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(0,nod_pt);
      //Second part of upper boundary
      nod_pt=finite_element_pt(4)->node_pt(np*(np-1)+n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(2,nod_pt);
      //Next part of hole
      nod_pt=finite_element_pt(2)->node_pt(n*np);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(4,nod_pt);
     }
    for(unsigned n=1;n<np;n++)
     {
      //Third part of lower boundary
      Node* nod_pt=finite_element_pt(5)->node_pt(n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(0,nod_pt);
      //Third part of upper boundary
      nod_pt=finite_element_pt(5)->node_pt(np*(np-1)+n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(2,nod_pt);
     }
    for(unsigned n=1;n<np;n++)
     {
      //Fourth part of lower boundary
      Node* nod_pt=finite_element_pt(6)->node_pt(n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(0,nod_pt);
      //Fourth part of upper boundary
      nod_pt=finite_element_pt(6)->node_pt(np*(np-1)+n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(2,nod_pt);
     }
    for(unsigned n=1;n<np;n++)
     {
      //Final part of lower boundary
      Node* nod_pt=finite_element_pt(7)->node_pt(n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(0,nod_pt);
      //Final part of upper boundary
      nod_pt=finite_element_pt(7)->node_pt(np*(np-1)+n);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(2,nod_pt);
      //Next part of hole
      nod_pt=finite_element_pt(1)->node_pt(np-n-1);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(4,nod_pt);
     }
    for(unsigned n=1;n<np-1;n++)
     {
      //Final part of hole
      Node* nod_pt=finite_element_pt(0)->node_pt(np*(np-n-1)+np-1);
      convert_to_boundary_node(nod_pt);
      add_boundary_node(4,nod_pt);
     }
  }
References e(), Global_Physical_Variables::height(), n, UniformPSDSelfTest::r, and s.
Member Function Documentation
domain_pt() [1/3]
template<class ELEMENT > RectangleWithHoleDomain* RectangleWithHoleMesh< ELEMENT >::domain_pt () inline
Access function to the domain.
 {return Domain_pt;}
domain_pt() [2/3]
template<class ELEMENT > RectangleWithHoleDomain* RectangleWithHoleMesh< ELEMENT >::domain_pt () inline
Access function to the domain.
 {return Domain_pt;}
domain_pt() [3/3]
template<class ELEMENT > RectangleWithHoleDomain* RectangleWithHoleMesh< ELEMENT >::domain_pt () inline
Access function to the domain.
 {return Domain_pt;}
height()
template<class ELEMENT > const double& RectangleWithHoleMesh< ELEMENT >::height () inline
Access function to height.
 {return Height;}
References GlobalParameters::Height.
length()
template<class ELEMENT > const double& RectangleWithHoleMesh< ELEMENT >::length () inline
Access function to length.
 {return Length;}
References Global_Physical_Variables::Length.
Member Data Documentation
Domain_pt
template<class ELEMENT > RectangleWithHoleDomain* RectangleWithHoleMesh< ELEMENT >::Domain_pt protected
Pointer to the domain.
Height
template<class ELEMENT > double RectangleWithHoleMesh< ELEMENT >::Height protected
Length
template<class ELEMENT > double RectangleWithHoleMesh< ELEMENT >::Length protected
The documentation for this class was generated from the following files:
adaptive_hopf.cc
adaptive_hopf_with_separate_meshes.cc
flow_past_cylinder.cc