MercuryDPM: oomph::StrainEnergyFunction Class Reference
oomph::StrainEnergyFunction Class Reference abstract
#include <constitutive_laws.h>
Public Member Functions
StrainEnergyFunction ()
Constructor takes no arguments.
virtual ~StrainEnergyFunction ()
Empty virtual destructor.
virtual double W (const DenseMatrix< double > &gamma)
Return the strain energy in terms of the strain tensor.
virtual double W (const Vector< double > &I)
Return the strain energy in terms of the strain invariants.
virtual void derivative (const DenseMatrix< double > &gamma, DenseMatrix< double > &dWdgamma)
virtual void derivatives (Vector< double > &I, Vector< double > &dWdI)
virtual bool requires_incompressibility_constraint ()=0
Detailed Description
Base class for strain energy functions to be used in solid mechanics computations.
Constructor & Destructor Documentation
StrainEnergyFunction()
oomph::StrainEnergyFunction::StrainEnergyFunction () inline
Constructor takes no arguments.
 {}
~StrainEnergyFunction()
virtual oomph::StrainEnergyFunction::~StrainEnergyFunction () inline virtual
Empty virtual destructor.
 {}
Member Function Documentation
derivative()
virtual void oomph::StrainEnergyFunction::derivative (const DenseMatrix< double > & gamma, DenseMatrix< double > & dWdgamma) inline virtual
Return the derivatives of the strain energy function with respect to the components of the strain tensor (default is to use finite differences).
     {
       throw OomphLibError(
         "Sorry, the FD setup of dW/dgamma hasn't been implemented yet",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
derivatives()
virtual void oomph::StrainEnergyFunction::derivatives (Vector< double > & I, Vector< double > & dWdI) inline virtual
Return the derivatives of the strain energy function with respect to the strain invariants. Default version is to use finite differences
Reimplemented in oomph::GeneralisedMooneyRivlin, and oomph::MooneyRivlin.
     {
       // Calculate the derivatives of the strain-energy-function wrt the strain
       // invariants
       double FD_Jstep = 1.0e-8; // Usual comments about global stuff
       double energy = W(I);
       // Loop over the strain invariants
       for (unsigned i = 0; i < 3; i++)
       {
         // Store old value
         double I_prev = I[i];
         // Increase ith strain invariant
         I[i] += FD_Jstep;
         // Get the new value of the strain energy
         double energy_new = W(I);
         // Calculate the value of the derivative
         dWdI[i] = (energy_new - energy) / FD_Jstep;
         // Reset value of ith strain invariant
         I[i] = I_prev;
       }
     }
References i, I, and W().
Referenced by oomph::IsotropicStrainEnergyFunctionConstitutiveLaw::calculate_second_piola_kirchhoff_stress().
requires_incompressibility_constraint()
virtual bool oomph::StrainEnergyFunction::requires_incompressibility_constraint () pure virtual
Pure virtual function in which the user must declare if the constitutive equation requires an incompressible formulation in which the volume constraint is enforced explicitly. Used as a sanity check in PARANOID mode.
Implemented in oomph::GeneralisedMooneyRivlin, and oomph::MooneyRivlin.
Referenced by oomph::IsotropicStrainEnergyFunctionConstitutiveLaw::requires_incompressibility_constraint().
W() [1/2]
virtual double oomph::StrainEnergyFunction::W (const DenseMatrix< double > & gamma) inline virtual
Return the strain energy in terms of the strain tensor.
Reimplemented in oomph::GeneralisedMooneyRivlin, and oomph::MooneyRivlin.
     {
       std::string error_message =
         "The strain-energy function as a function of the strain-tensor,\n";
       error_message +=
         "gamma, is not implemented for this strain energy function.\n";
       throw OomphLibError(
         error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       return 0.0;
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
Referenced by derivatives(), oomph::MooneyRivlin::W(), and oomph::GeneralisedMooneyRivlin::W().
W() [2/2]
virtual double oomph::StrainEnergyFunction::W (const Vector< double > & I) inline virtual
Return the strain energy in terms of the strain invariants.
Reimplemented in oomph::GeneralisedMooneyRivlin, and oomph::MooneyRivlin.
     {
       std::string error_message =
         "The strain-energy function as a function of the strain\n ";
       error_message +=
         "invariants, I1, I2, I3, is not implemented for this strain\n ";
       error_message += "energy function\n";
       throw OomphLibError(
         error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       return 0.0;
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
The documentation for this class was generated from the following file:
constitutive_laws.h