MercuryDPM: Eigen::internal::BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options > Class Template Reference
Eigen::internal::BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Represents a rectangular matrix with a banded storage.
#include <BandMatrix.h>
Public Types
typedef internal::traits< BandMatrix >::Scalar Scalar
typedef internal::traits< BandMatrix >::StorageIndex StorageIndex
typedef internal::traits< BandMatrix >::CoefficientsType CoefficientsType
Public Types inherited from Eigen::internal::BandMatrixBase< BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options > >
enum
typedef internal::traits< BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options > >::Scalar Scalar
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime > DenseMatrixType
typedef DenseMatrixType::StorageIndex StorageIndex
typedef internal::traits< BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options > >::CoefficientsType CoefficientsType
typedef EigenBase< BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options > > Base
Public Types inherited from Eigen::EigenBase< BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options > >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options > >::StorageKind StorageKind
Public Member Functions
BandMatrix (Index rows=Rows, Index cols=Cols, Index supers=Supers, Index subs=Subs)
EIGEN_CONSTEXPR Index rows () const
EIGEN_CONSTEXPR Index cols () const
EIGEN_CONSTEXPR Index supers () const
EIGEN_CONSTEXPR Index subs () const
const CoefficientsType & coeffs () const
CoefficientsType & coeffs ()
Public Member Functions inherited from Eigen::internal::BandMatrixBase< BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options > >
Index supers () const
Index subs () const
const CoefficientsType & coeffs () const
CoefficientsType & coeffs ()
Block< CoefficientsType, Dynamic, 1 > col (Index i)
Block< CoefficientsType, 1, SizeAtCompileTime > diagonal ()
const Block< const CoefficientsType, 1, SizeAtCompileTime > diagonal () const
DiagonalIntReturnType< N >::Type diagonal ()
const DiagonalIntReturnType< N >::Type diagonal () const
Block< CoefficientsType, 1, Dynamic > diagonal (Index i)
const Block< const CoefficientsType, 1, Dynamic > diagonal (Index i) const
void evalTo (Dest &dst) const
DenseMatrixType toDenseMatrix () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
constexpr EIGEN_DEVICE_FUNC BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options > & derived ()
constexpr EIGEN_DEVICE_FUNC const BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options > & derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
Public Member Functions inherited from Eigen::EigenBase< BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options > >
constexpr EIGEN_DEVICE_FUNC BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options > & derived ()
constexpr EIGEN_DEVICE_FUNC const BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options > & derived () const
EIGEN_DEVICE_FUNC BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options > & const_cast_derived () const
EIGEN_DEVICE_FUNC const BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options > & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options >, Device > device (Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options >, Device > device (Device &device) const
Protected Attributes
CoefficientsType m_coeffs
internal::variable_if_dynamic< Index, Rows > m_rows
internal::variable_if_dynamic< Index, Supers > m_supers
internal::variable_if_dynamic< Index, Subs > m_subs
Additional Inherited Members
Protected Types inherited from Eigen::internal::BandMatrixBase< BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options > >
enum
Protected Member Functions inherited from Eigen::internal::BandMatrixBase< BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options > >
Index diagonalLength (Index i) const
Detailed Description
template<typename Scalar_, int Rows, int Cols, int Supers, int Subs, int Options>
class Eigen::internal::BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options >
Represents a rectangular matrix with a banded storage.
Template Parameters
Scalar_ Numeric type, i.e. float, double, int
Rows_ Number of rows, or Dynamic
Cols_ Number of columns, or Dynamic
Supers_ Number of super diagonal
Subs_ Number of sub diagonal
Options_ A combination of either RowMajor or ColMajor, and of SelfAdjoint The former controls storage order, and defaults to column-major. The latter controls whether the matrix represents a selfadjoint matrix in which case either Supers of Subs have to be null.
See also
class TridiagonalMatrix
Member Typedef Documentation
CoefficientsType
template<typename Scalar_ , int Rows, int Cols, int Supers, int Subs, int Options> typedef internal::traits<BandMatrix>::CoefficientsType Eigen::internal::BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options >::CoefficientsType
Scalar
template<typename Scalar_ , int Rows, int Cols, int Supers, int Subs, int Options> typedef internal::traits<BandMatrix>::Scalar Eigen::internal::BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options >::Scalar
StorageIndex
template<typename Scalar_ , int Rows, int Cols, int Supers, int Subs, int Options> typedef internal::traits<BandMatrix>::StorageIndex Eigen::internal::BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options >::StorageIndex
Constructor & Destructor Documentation
BandMatrix()
template<typename Scalar_ , int Rows, int Cols, int Supers, int Subs, int Options> Eigen::internal::BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options >::BandMatrix (Index rows = Rows, Index cols = Cols, Index supers = Supers, Index subs = Subs) inline explicit
       : m_coeffs(1 + supers + subs, cols), m_rows(rows), m_supers(supers), m_subs(subs) {}
Member Function Documentation
coeffs() [1/2]
template<typename Scalar_ , int Rows, int Cols, int Supers, int Subs, int Options> CoefficientsType& Eigen::internal::BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options >::coeffs () inline
 { return m_coeffs; }
coeffs() [2/2]
template<typename Scalar_ , int Rows, int Cols, int Supers, int Subs, int Options> const CoefficientsType& Eigen::internal::BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options >::coeffs () const inline
 { return m_coeffs; }
cols()
template<typename Scalar_ , int Rows, int Cols, int Supers, int Subs, int Options> EIGEN_CONSTEXPR Index Eigen::internal::BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options >::cols () const inline
Returns
the number of rows
 { return m_coeffs.cols(); }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
rows()
template<typename Scalar_ , int Rows, int Cols, int Supers, int Subs, int Options> EIGEN_CONSTEXPR Index Eigen::internal::BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options >::rows () const inline
Returns
the number of columns
 { return m_rows.value(); }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
subs()
template<typename Scalar_ , int Rows, int Cols, int Supers, int Subs, int Options> EIGEN_CONSTEXPR Index Eigen::internal::BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options >::subs () const inline
Returns
the number of sub diagonals
 { return m_subs.value(); }
supers()
template<typename Scalar_ , int Rows, int Cols, int Supers, int Subs, int Options> EIGEN_CONSTEXPR Index Eigen::internal::BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options >::supers () const inline
Returns
the number of super diagonals
 { return m_supers.value(); }
Member Data Documentation
m_coeffs
template<typename Scalar_ , int Rows, int Cols, int Supers, int Subs, int Options> CoefficientsType Eigen::internal::BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options >::m_coeffs protected
m_rows
template<typename Scalar_ , int Rows, int Cols, int Supers, int Subs, int Options> internal::variable_if_dynamic<Index, Rows> Eigen::internal::BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options >::m_rows protected
m_subs
template<typename Scalar_ , int Rows, int Cols, int Supers, int Subs, int Options> internal::variable_if_dynamic<Index, Subs> Eigen::internal::BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options >::m_subs protected
m_supers
template<typename Scalar_ , int Rows, int Cols, int Supers, int Subs, int Options> internal::variable_if_dynamic<Index, Supers> Eigen::internal::BandMatrix< Scalar_, Rows, Cols, Supers, Subs, Options >::m_supers protected
The documentation for this class was generated from the following file:
BandMatrix.h