MercuryDPM: fsi_channel_with_leaflet_precond.cc File Reference
fsi_channel_with_leaflet_precond.cc File Reference
#include "generic.h"
#include "beam.h"
#include "navier_stokes.h"
#include "multi_physics.h"
#include "constitutive.h"
#include "solid.h"
#include "meshes/channel_with_leaflet_mesh.h"
#include "meshes/one_d_lagrangian_mesh.h"
Classes
class oomph::PseudoElasticBulkElement< ELEMENT >
class oomph::FaceGeometry< PseudoElasticBulkElement< ELEMENT > >
FaceGeometry of wrapped element is the same as the underlying element.
class UndeformedLeaflet
GeomObject: Undeformed straight, vertical leaflet.
class FSIChannelWithLeafletProblem< ELEMENT >
FSI leaflet in channel.
Namespaces
oomph
DRAIG: Change all instances of (SPATIAL_DIM) to (DIM-1).
Global_Parameters
Namespace for global parameters.
Functions
double Global_Parameters::flux (const double &t)
Flux: Pulsatile flow.
int main (int argc, char **argv)
Driver code.
Variables
double Global_Parameters::Leaflet_x0 = 1.0
x-position of root of leaflet
double Global_Parameters::Leaflet_height =0.5
height of leaflet
double Global_Parameters::Fluid_length_left =1.0
length of fluid mesh to left of leaflet
double Global_Parameters::Fluid_length_right =3.0
length of fluid mesh to right of leaflet
double Global_Parameters::Fluid_height =1.0
height of fluid mesh
unsigned Global_Parameters::Mesh_nleft =4
Num elements to left of leaflet in coarse mesh.
unsigned Global_Parameters::Mesh_nright =12
Num elements to right of leaflet in coarse mesh.
unsigned Global_Parameters::Mesh_ny1 =2
Num elements in fluid mesh in y dirn adjacent to leaflet.
unsigned Global_Parameters::Mesh_ny2 =2
Num elements in fluid mesh in y dirn above leaflet.
double Global_Parameters::ReSt =50.0
Womersley number: Product of Reynolds and Strouhal numbers.
double Global_Parameters::U_base =1.0
Min. flux.
double Global_Parameters::U_perturbation =0.5
Max. flux.
double Global_Parameters::Lambda_sq_beam =0.0
Beam mass density.
Function Documentation
main()
int main (int argc , char ** argv)
Driver code.
 {
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::init(argc,argv);
 #endif
  // Switch off output modifier
  oomph_info.output_modifier_pt() = &default_output_modifier;
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Multiplier for number of elements in coordinate directions.
  // Used for uniform mesh refinement studies.
  unsigned mesh_multiplier = 2;
  CommandLineArgs::specify_command_line_flag("--mesh_multiplier",
                                             &mesh_multiplier);
  // Suppress use of LSC preconditioner for Navier Stokes block
  CommandLineArgs::specify_command_line_flag("--suppress_lsc");
  // Use direct solver (SuperLU)
  CommandLineArgs::specify_command_line_flag("--use_direct_solver");
  // Use SuperLU for all block solves
  CommandLineArgs::specify_command_line_flag("--superlu_for_blocks");
  // Validation only?
  CommandLineArgs::specify_command_line_flag("--validate");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  //Set up the problem
  FSIChannelWithLeafletProblem<PseudoSolidNodeUpdateElement
                               <QTaylorHoodElement<2>,
                                PseudoElasticBulkElement<QPVDElement<2,3> > > >*
   problem_pt = new
   FSIChannelWithLeafletProblem<PseudoSolidNodeUpdateElement
                                <QTaylorHoodElement<2>,
                                 PseudoElasticBulkElement<QPVDElement<2,3> > > >
   (mesh_multiplier);
  // Initialise timestep
  problem_pt->initialise_dt(Global_Parameters::Dt);
  // Label for output
  DocInfo doc_info;
  doc_info.set_directory("RESLT");
  // Define processor-labeled output file for all on-screen stuff
  std::ofstream output_stream;
  char filename[1000];
 #ifdef OOMPH_HAS_MPI
  sprintf(filename,"%s/OUTPUT_STEADY.%i",doc_info.directory().c_str(),
          MPI_Helpers::communicator_pt()->my_rank());
 #else
  sprintf(filename,"%s/OUTPUT_STEADY.%i",doc_info.directory().c_str(),0);
 #endif
  output_stream.open(filename);
  oomph_info.stream_pt() = &output_stream;
  OomphLibWarning::set_stream_pt(&output_stream);
  OomphLibError::set_stream_pt(&output_stream);
  // Output initial configuration
  problem_pt->doc_solution(doc_info);
  doc_info.number()++;
  // Switch to iterative solver?
  if (!CommandLineArgs::command_line_flag_has_been_set("--use_direct_solver"))
   {
    problem_pt->set_iterative_solver();
   }
  // Steady solves
  //--------------
  // Increment Re and Womersley numbers in increments of 25.
  double target_re = Global_Parameters::Re;
  Global_Parameters::Re=25.0;
  Global_Parameters::ReSt=25.0;
  while (Global_Parameters::Re<target_re)
   {
    problem_pt->steady_newton_solve();
    problem_pt->doc_parameters();
    Global_Parameters::Re+=25.0;
    Global_Parameters::ReSt+=25.0;
    problem_pt->doc_solution(doc_info);
    doc_info.number()++;
   }
  // Do final solve at desired Re
  Global_Parameters::Re=target_re;
  Global_Parameters::ReSt=target_re;
  problem_pt->steady_newton_solve();
  problem_pt->doc_parameters();
  problem_pt->doc_solution(doc_info);
  doc_info.number()++;
  // Unsteady solves
  //----------------
  // Define processor-labeled output file for all on-screen stuff
  output_stream.close();
 #ifdef OOMPH_HAS_MPI
  sprintf(filename,"%s/OUTPUT_UNSTEADY.%i",doc_info.directory().c_str(),
          MPI_Helpers::communicator_pt()->my_rank());
 #else
  sprintf(filename,"%s/OUTPUT_UNSTEADY.%i",doc_info.directory().c_str(),0);
 #endif
  output_stream.open(filename);
  oomph_info.stream_pt() = &output_stream;
  OomphLibWarning::set_stream_pt(&output_stream);
  OomphLibError::set_stream_pt(&output_stream);
  // Loop over timesteps for specified number of periods of fluctuating
  // inflow
  unsigned n_period=1;
  unsigned nstep=unsigned(double(n_period)
                          *Global_Parameters::T/Global_Parameters::Dt);
  if (CommandLineArgs::command_line_flag_has_been_set("--validate"))
   {
    nstep=3;
   }
  for (unsigned r = 0; r < nstep; r++)
   {
    problem_pt->unsteady_newton_solve(Global_Parameters::Dt);
    problem_pt->doc_parameters();
    problem_pt->doc_solution(doc_info);
    doc_info.number()++;
   }
  // clean up
  delete problem_pt;
  // Shut down
  oomph_info << "Done\n";
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::finalize();
 #endif
 } // end_of_main
References oomph::CommandLineArgs::command_line_flag_has_been_set(), oomph::default_output_modifier, oomph::DocInfo::directory(), oomph::CommandLineArgs::doc_specified_flags(), Global_Parameters::Dt, MergeRestartFiles::filename, oomph::DocInfo::number(), oomph::oomph_info, oomph::OomphInfo::output_modifier_pt(), oomph::CommandLineArgs::parse_and_assign(), UniformPSDSelfTest::r, Global_Parameters::Re, Global_Parameters::ReSt, oomph::DocInfo::set_directory(), Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), oomph::OomphInfo::stream_pt(), and Global_Parameters::T.