MercuryDPM: Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType > Class Template Reference
Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType > Class Template Reference
#include <SparseRef.h>
Public Types
typedef internal::SparseRefBase< Ref > Base
Public Types inherited from Eigen::internal::SparseRefBase< Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType > >
typedef SparseMapBase< Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType > > Base
Public Member Functions
template<typename Derived >
Ref (const SparseMatrixBase< Derived > &expr)
Ref (const Ref &other)
template<typename OtherRef >
Ref (const RefBase< OtherRef > &other)
~Ref ()
Public Member Functions inherited from Eigen::internal::SparseRefBase< Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType > >
SparseRefBase ()
Protected Member Functions
template<typename Expression >
void construct (const Expression &expr, internal::true_type)
template<typename Expression >
void construct (const Expression &expr, internal::false_type)
Protected Member Functions inherited from Eigen::internal::SparseRefBase< Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType > >
void construct (Expression &expr)
Protected Attributes
internal::aligned_storage< sizeof(TPlainObjectType), EIGEN_ALIGNOF(TPlainObjectType)>::type m_storage
bool m_hasCopy
Private Types
typedef SparseVector< MatScalar, MatOptions, MatIndex > TPlainObjectType
typedef internal::traits< Ref > Traits
Member Typedef Documentation
Base
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > typedef internal::SparseRefBase<Ref> Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Base
TPlainObjectType
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > typedef SparseVector<MatScalar, MatOptions, MatIndex> Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::TPlainObjectType private
Traits
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > typedef internal::traits<Ref> Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Traits private
Constructor & Destructor Documentation
Ref() [1/3]
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > template<typename Derived > Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref (const SparseMatrixBase< Derived > & expr) inline
                                                     : m_hasCopy(false) {
     construct(expr.derived(), typename Traits::template match<Derived>::type());
   }
References Eigen::RefBase< Ref< PlainObjectType, Options, StrideType > >::construct(), Eigen::SparseMatrixBase< Derived >::derived(), and compute_granudrum_aor::type.
Ref() [2/3]
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref (const Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType > & other) inline
                                : Base(other), m_hasCopy(false) {
     // copy constructor shall not copy the m_object, to avoid unnecessary malloc and copy
   }
Ref() [3/3]
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > template<typename OtherRef > Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref (const RefBase< OtherRef< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType > > & other) inline
                                              : m_hasCopy(false) {
     construct(other.derived(), typename Traits::template match<OtherRef>::type());
   }
References Eigen::RefBase< Ref< PlainObjectType, Options, StrideType > >::construct(), and compute_granudrum_aor::type.
~Ref()
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::~Ref () inline
          {
     if (m_hasCopy) {
       internal::destroy_at(reinterpret_cast<TPlainObjectType*>(&m_storage));
     }
   }
References Eigen::internal::destroy_at().
Member Function Documentation
construct() [1/2]
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > template<typename Expression > void Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::construct (const Expression & expr, internal::false_type) inline protected
{
     TPlainObjectType* obj = internal::construct_at(reinterpret_cast<TPlainObjectType*>(&m_storage), expr);
     m_hasCopy = true;
     Base::construct(*obj);
   }
References Eigen::RefBase< Derived >::construct(), and Eigen::internal::construct_at().
construct() [2/2]
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > template<typename Expression > void Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::construct (const Expression & expr, internal::true_type) inline protected
{
     Base::construct(expr);
   }
References Eigen::RefBase< Derived >::construct().
Member Data Documentation
m_hasCopy
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > bool Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::m_hasCopy protected
m_storage
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > internal::aligned_storage<sizeof(TPlainObjectType), EIGEN_ALIGNOF(TPlainObjectType)>::type Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::m_storage protected
The documentation for this class was generated from the following file:
SparseRef.h