MercuryDPM: roughBottomSelfTest.cpp File Reference
roughBottomSelfTest.cpp File Reference
#include <sstream>
#include <Species/LinearViscoelasticSpecies.h>
#include "Chute.h"
Functions
int main ()
[RB:headers]
Function Documentation
main()
int main ()
[RB:headers]
[RB:headers]
This is a demo on how to implement a chute flow with a rough bottom. Note that this is the same code as roughBottomSelfTest, but with a bigger chute, a larger gravity and a longer simulation time. [RB:main]
 {
     //Print description
     logger(INFO, "\nDemo of the chute flow with a rough bottom");
     //Construct the problem and assign a name
     Chute roughBottomSelfTest;
     roughBottomSelfTest.setName("roughBottomMultiLayer");
     //Set time stepping parameters
     roughBottomSelfTest.setTimeStep(1e-4);
     roughBottomSelfTest.setTimeMax(0.1);
     //Set output parameter: write to the output files every 50 time steps
     roughBottomSelfTest.setSaveCount(50);
     //Set the particle radii and the type of the rough bottom
     roughBottomSelfTest.setInflowParticleRadius(0.5);
     roughBottomSelfTest.setFixedParticleRadius(0.5);
     roughBottomSelfTest.setRoughBottomType(MULTILAYER);
     //Set the particle properties
     LinearViscoelasticSpecies* species = roughBottomSelfTest.speciesHandler.copyAndAddObject(LinearViscoelasticSpecies());
     species->setDensity(6.0/constants::pi);
     species->setStiffness(2e5);
     species->setDissipation(25.0);
     //Set the chute properties
     roughBottomSelfTest.setChuteAngleAndMagnitudeOfGravity(24.0, 1.0);
     roughBottomSelfTest.setChuteLength(3.0);
     roughBottomSelfTest.setChuteWidth(3.0);
     //Solve the system
     roughBottomSelfTest.solve();
 }
References BaseHandler< T >::copyAndAddObject(), e(), INFO, logger, MULTILAYER, constants::pi, Chute::setChuteAngleAndMagnitudeOfGravity(), Chute::setChuteLength(), Chute::setChuteWidth(), ParticleSpecies::setDensity(), LinearViscoelasticNormalSpecies::setDissipation(), Chute::setFixedParticleRadius(), Chute::setInflowParticleRadius(), DPMBase::setName(), Chute::setRoughBottomType(), DPMBase::setSaveCount(), LinearViscoelasticNormalSpecies::setStiffness(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), DPMBase::solve(), and DPMBase::speciesHandler.