MercuryDPM: static2d.cpp File Reference
static2d.cpp File Reference
#include "Chute.h"
#include "StatisticsVector.h"
#include "Walls/InfiniteWall.h"
#include <iostream>
#include <Species/LinearViscoelasticSlidingFrictionSpecies.h>
Classes
class Cstatic2d
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
Start off my solving the default problem
 {
     Cstatic2d static2d;
     static2d.setName("static2d");
     static2d.set_particle_properties();
     static2d.setSaveCount(12000);
     static2d.setTimeMax(400);
     static2d.solve();
     //~ static2d.write(cout,true);
 }
References Cstatic2d::set_particle_properties(), DPMBase::setName(), DPMBase::setSaveCount(), DPMBase::setTimeMax(), and DPMBase::solve().