MercuryDPM: space_time_oscillating_cylinder.cc File Reference
space_time_oscillating_cylinder.cc File Reference
#include <cstring>
#include <limits>
#include "generic.h"
#include "navier_stokes.h"
#include "space_time_navier_stokes.h"
#include "meshes/rectangle_with_moving_cylinder_mesh.h"
#include "meshes/extruded_cube_mesh_from_quad_mesh_with_macro_elements.h"
#include "space_time_block_preconditioner.h"
Classes
class oomph::MyRefineableQTaylorHoodElement
Overloaded element that allows projection of use as PML element.
class oomph::PMLLayerElement< MyRefineableQTaylorHoodElement >
Policy class defining the elements to be used in the PML layers. Same!
class oomph::FaceGeometry< MyRefineableQTaylorHoodElement >
class OscillatingCylinder
Oscillating cylinder class.
class NavierStokesProblem< ELEMENT >
Entry flow problem in quarter tube domain.
Namespaces
oomph
DRAIG: Change all instances of (SPATIAL_DIM) to (DIM-1).
NodeReordering
Contains helper function to reorganise nodes.
GlobalParameters
Global parameters.
SubsidiaryPreconditionerHelper
Functions
bool NodeReordering::node_global_position_comparison (Node *nd1_pt, Node *nd2_pt)
void NodeReordering::get_node_reordering (Mesh *mesh_pt, Vector< Node * > &reordering, const bool &use_old_ordering)
void NodeReordering::reorder_nodes (Mesh *mesh_pt, const bool &use_old_ordering)
double GlobalParameters::calculate_strouhal_number (const double &re)
void GlobalParameters::update_physical_parameters ()
void GlobalParameters::update_mesh_parameters ()
void GlobalParameters::set_up_dof_to_block_mapping (Vector< unsigned > &dof_to_block_map)
void GlobalParameters::doc_maximum_central_box_deformation ()
Document the maximum deformation inside the central box.
std::string GlobalParameters::parameter_to_string (const double *const parameter_pt)
void GlobalParameters::find_node_on_centerline (Mesh *mesh_pt, FiniteElement **el_centerline_pt, unsigned &node_index)
--------------------—Documentation Helpers----------------------—
double GlobalParameters::round (const double &d)
---------------------------------------—DOCUMENTATION HELPERS---—
Preconditioner * SubsidiaryPreconditionerHelper::get_new_preconditioner ()
int main (int argc, char **argv)
Driver code for unsteady heat equation.
Variables
double GlobalParameters::Amplitude_target =0.50
unsigned GlobalParameters::N_amplitude_step =5
The number of steps used to reach the target amplitude.
double GlobalParameters::Period_ratio_target =1.0
unsigned GlobalParameters::N_period_ratio_step =1
The number of steps used to reach the target Period_ratio value.
unsigned GlobalParameters::N_re_step =2
double GlobalParameters::L_t =1.0
The length of the mesh in the time direction.
unsigned GlobalParameters::N_t =25
The number of elements in the time direction.
unsigned GlobalParameters::Preconditioner =0
----------------------—Domain Properties------------------------—
unsigned GlobalParameters::N_dof_type =0
std::ofstream GlobalParameters::Trace_file
Trace file to doc. asymmetry norm data in.
bool GlobalParameters::Document_solution =true
Helper variable to indicate whether or not to document the solution.
Function Documentation
main()
int main (int argc , char ** argv)
Driver code for unsteady heat equation.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
 {
 #ifdef OOMPH_HAS_MPI
   // Initialise MPI
   MPI_Helpers::init(argc,argv);
   // Switch off output modifier
   oomph_info.output_modifier_pt()=&default_output_modifier;
   // Switch off oomph_info output for all processors but rank 0
   if (MPI_Helpers::communicator_pt()->my_rank()!=0)
   {
     oomph_info.stream_pt()=&oomph_nullstream;
     OomphLibWarning::set_stream_pt(&oomph_nullstream);
     OomphLibError::set_stream_pt(&oomph_nullstream);
   }
   else
   {
     oomph_info << "\n=====================================================\n"
                << "Number of processors: "
                << MPI_Helpers::communicator_pt()->nproc()
                << "\n=====================================================\n"
                << std::endl;
   }
 #endif
   // Output directory
   GlobalParameters::Doc_info.set_directory("RESLT");
   //----------------------
   // Problem setup & solve
   //----------------------
   // Typedef the block preconditionable element type
   typedef BlockPrecQTaylorHoodMixedOrderSpaceTimeElement ELEMENT;
   // Start the clock
   double timer_s=TimingHelpers::timer();
   // Build problem
   NavierStokesProblem<ELEMENT> problem;
   // Tell the user
   oomph_info << ANSIEscapeCode::Red
              << "\nSolving with the following problem parameters:"
              << ANSIEscapeCode::Reset
              << ANSIEscapeCode::Red << "\n - Re: " << ANSIEscapeCode::Reset
              << GlobalParameters::Re
              << ANSIEscapeCode::Red << "\n - ReSt: " << ANSIEscapeCode::Reset
              << GlobalParameters::ReSt
              << ANSIEscapeCode::Red << "\n - A: " << ANSIEscapeCode::Reset
              << GlobalParameters::Amplitude
              << ANSIEscapeCode::Red << "\n - T_e/T_s: " << ANSIEscapeCode::Reset
              << GlobalParameters::Period_ratio
              << std::endl;
   // Solve the problem again
   problem.newton_solve();
   // Doc the solution
   problem.doc_solution();
   // Use parameter continuation in the Reynolds number
   problem.run_natural_continuation(GlobalParameters::Re,
                                    GlobalParameters::Re_target,
                                    GlobalParameters::N_re_step);
   // Doc the solution
   problem.doc_solution();
   // Use parameter continuation for the amplitude value
   problem.run_natural_continuation(GlobalParameters::Amplitude,
                                    GlobalParameters::Amplitude_target,
                                    GlobalParameters::N_amplitude_step);
   // Doc the solution
   problem.doc_solution();
   // Tell the user we're done
   oomph_info << "\nSimulation complete!\nTotal time for simulation [sec]: "
              << TimingHelpers::timer()-timer_s << std::endl;
 #ifdef OOMPH_HAS_MPI
   MPI_Helpers::finalize();
 #endif
 } // End of main
References GlobalParameters::Amplitude, GlobalParameters::Amplitude_target, oomph::default_output_modifier, GlobalParameters::Doc_info, GlobalParameters::N_amplitude_step, GlobalParameters::N_re_step, oomph::oomph_info, oomph::oomph_nullstream, oomph::OomphInfo::output_modifier_pt(), GlobalParameters::Period_ratio, problem, GlobalParameters::Re, GlobalParameters::Re_target, oomph::ANSIEscapeCode::Red, oomph::ANSIEscapeCode::Reset, GlobalParameters::ReSt, oomph::DocInfo::set_directory(), and oomph::OomphInfo::stream_pt().