MercuryDPM: time_harmonic_elasticity_driver.cc File Reference
time_harmonic_elasticity_driver.cc File Reference
#include <fenv.h>
#include "math.h"
#include <complex>
#include "generic.h"
#include "pml_time_harmonic_linear_elasticity.h"
#include "oomph_crbond_bessel.h"
#include "meshes/triangle_mesh.h"
Classes
class ElasticAnnulusProblem< ELASTICITY_ELEMENT >
Annular disk.
Namespaces
Global_Parameters
Namespace for global parameters.
Macros
#define ADAPTIVE
Functions
void Global_Parameters::compute_dependent_parameters ()
Function to compute dependent parameters.
void Global_Parameters::Hankel_first (const unsigned &n, const double &x, Vector< std::complex< double > > &h, Vector< std::complex< double > > &hp)
void Global_Parameters::exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector: {u_x_real, u_y_real, u_x_imag, u_y_imag}.
int main (int argc, char **argv)
Driver for annular disk loaded by pressure.
Variables
double Global_Parameters::Element_area = 0.01
helper to set target mesh element size
double Global_Parameters::T_start = 0.0
helpers to time the code
double Global_Parameters::T_end = 0.0
unsigned Global_Parameters::N_pml_multiplier = 1
PML width in elements for the right layer.
double Global_Parameters::L_pml_multiplier = 1.0
unsigned Global_Parameters::N_x_right_pml = 8
PML width in elements for the right layer.
unsigned Global_Parameters::N_y_top_pml = 8
PML width in elements for the top layer.
unsigned Global_Parameters::N_x_left_pml = 8
PML width in elements for the left layer.
unsigned Global_Parameters::N_y_bottom_pml = 8
PML width in elements for the left layer.
double Global_Parameters::Width_x_right_pml = 2.0
double Global_Parameters::Width_y_top_pml = 2.0
double Global_Parameters::Width_x_left_pml = 2.0
double Global_Parameters::Width_y_bottom_pml = 2.0
double Global_Parameters::H_annulus =0.5
Thickness of annulus.
Macro Definition Documentation
ADAPTIVE
#define ADAPTIVE
Function Documentation
main()
int main (int argc , char ** argv)
Driver for annular disk loaded by pressure.
Number of elements for each layer
Thickness of each layer
Target element size
Target element size
Update dependent parameters
 {
  // Start timing of the code
  Global_Parameters::T_start=TimingHelpers::timer();
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Over-write PML layers element number in each dimension
  CommandLineArgs::specify_command_line_flag("--n_pml",
                  &Global_Parameters::N_pml_multiplier);
  // Over-write PML layers physical length in each dimension
  CommandLineArgs::specify_command_line_flag("--l_pml",
                  &Global_Parameters::L_pml_multiplier);
  // Output directory
  CommandLineArgs::specify_command_line_flag(
   "--dir", &Global_Parameters::Directory);
 #ifdef ADAPTIVE
  // Max. number of adaptations
  unsigned max_adapt=0;
  CommandLineArgs::specify_command_line_flag("--max_adapt",&max_adapt);
 #endif
  // Validation run?
  CommandLineArgs::specify_command_line_flag("--validation");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Validation run?
  if (CommandLineArgs::command_line_flag_has_been_set("--validation"))
   {
    oomph_info << "Using coarser resolution for self-test\n";
    Global_Parameters::N_x_right_pml  = 2;
    Global_Parameters::N_y_top_pml    = 2;
    Global_Parameters::N_x_left_pml   = 2;
    Global_Parameters::N_y_bottom_pml = 2;
    Global_Parameters::Width_x_right_pml  = 1.0;
    Global_Parameters::Width_y_top_pml    = 1.0;
    Global_Parameters::Width_x_left_pml   = 1.0;
    Global_Parameters::Width_y_bottom_pml = 1.0;
    Global_Parameters::Element_area  = 0.025;
    Global_Parameters::Omega_sq  = 10.0;
   }
  Global_Parameters::compute_dependent_parameters();
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory(Global_Parameters::Directory);
  // Build elasticity tensor
  Global_Parameters::E_pt=new PMLTimeHarmonicIsotropicElasticityTensor(
     Global_Parameters::Nu);
 #ifdef ADAPTIVE
  //Set up the problem
  ElasticAnnulusProblem<
  ProjectablePMLTimeHarmonicLinearElasticityElement
   <TPMLTimeHarmonicLinearElasticityElement<2,3> >
  > problem;
 #else
  //Set up the problem
  ElasticAnnulusProblem<TPMLTimeHarmonicLinearElasticityElement<2,3> >
   problem;
 #endif
 #ifdef ADAPTIVE
  // Solve the problem with Newton's method, allowing
  // up to max_adapt mesh adaptations after every solve.
  problem.newton_solve(max_adapt);
 #else
  // Solve the problem using Newton's method
  problem.newton_solve();
 #endif
  // End timing of the code
  Global_Parameters::T_end=TimingHelpers::timer();
  // Doc solution
  problem.doc_solution(doc_info);
 } //end of main
References oomph::CommandLineArgs::command_line_flag_has_been_set(), Global_Parameters::compute_dependent_parameters(), Global_Parameters::Directory, oomph::CommandLineArgs::doc_specified_flags(), Global_Parameters::E_pt, Global_Parameters::Element_area, Global_Parameters::L_pml_multiplier, Global_Parameters::N_pml_multiplier, Global_Parameters::N_x_left_pml, Global_Parameters::N_x_right_pml, Global_Parameters::N_y_bottom_pml, Global_Parameters::N_y_top_pml, Global_Parameters::Nu, Global_Parameters::Omega_sq, oomph::oomph_info, oomph::CommandLineArgs::parse_and_assign(), problem, oomph::DocInfo::set_directory(), Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), Global_Parameters::T_end, Global_Parameters::T_start, Global_Parameters::Width_x_left_pml, Global_Parameters::Width_x_right_pml, Global_Parameters::Width_y_bottom_pml, and Global_Parameters::Width_y_top_pml.