MercuryDPM: CGStaticBalanceSelfTest.cpp File Reference
CGStaticBalanceSelfTest.cpp File Reference
#include "Mercury3D.h"
#include "StatisticsVector.h"
#include "Walls/InfiniteWall.h"
#include "CG/CG.h"
#include "CG/TimeSmoothedCG.h"
#include "CG/TimeAveragedCG.h"
#include "CG/Functions/Lucy.h"
#include "CG/Functions/Linear.h"
#include "CG/Functions/Heaviside.h"
#include "CG/Functions/Gauss.h"
#include <cmath>
#include <iostream>
#include <iomanip>
#include <Species/LinearViscoelasticSpecies.h>
Classes
class CGStaticBalanceSelfTest
Tests if the different CG templates work correctly.
Functions
void setCGHandler (DPMBase &problem)
void testCGHandler (DPMBase &problem)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
 {
     //declare the DPM problem and set the name
     CGStaticBalanceSelfTest problem;
     problem.setName("CGStaticBalanceSelfTest");
     //problem is steady after t=0.6, see gnuplot:
     //set logscale y; p 'CGStaticBalanceSelfTest.ene' u 1:3
     setCGHandler(problem);
     //run the simulation
     problem.solve(argc, argv);
     //problem is steady after t=0.6, see gnuplot:
     //set logscale y; p 'CGStaticBalanceSelfTest.ene' u 1:3
     testCGHandler(problem);
 }
References problem, setCGHandler(), and testCGHandler().
setCGHandler()
void setCGHandler (DPMBase & problem)
 {
     //define the different coarse-graining objects
     //case 0: create global average rho(t)
     CG<CGCoordinates::O> cg0;
     cg0.statFile.setSaveCount(20);
     cg0.statFile.setName(problem.getName() + ".LucyO.stat");
     problem.cgHandler.copyAndAddObject(cg0);
 //    TimeSmoothedCG<CGCoordinates::O> cg1;
 //    cg1.setWidthTime(0.01);
 //    cg1.setTimeStep(0.004);
 //    cg1.setTimeMax(0.2);
 //    cg1.statFile.setSaveCount(5);
 //    cg1.statFile.setName(problem.getName() + ".LucyO.TS.stat");
 //    problem.cgHandler.copyAndAddObject(cg1);
 //
 //    TimeAveragedCG<CGCoordinates::O> cg2;
 //    cg2.setTimeMin(0.6);
 //    cg2.statFile.setSaveCount(50);
 //    cg2.statFile.setName(problem.getName() + ".LucyO.TA.stat");
 //    problem.cgHandler.copyAndAddObject(cg2);
 //
     CG<CGCoordinates::Z> cgB;
     cgB.setNZ(200);
     cgB.setWidth(0.3);
     cgB.statFile.setSaveCount(20000);
     cgB.statFile.setName(problem.getName() + ".LucyZ.stat");
     problem.cgHandler.copyAndAddObject(cgB);
 //
 //    CG<CGFunctions::LinearZ> cgC;
 //    cgC.setNZ(200);
 //    cgC.setWidth(0.3);
 //    cgC.statFile.setSaveCount(20000);
 //    cgC.statFile.setName(problem.getName() + ".LinearZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgC);
 //
 //    CG<CGFunctions::HeavisideZ> cgD;
 //    cgD.setNZ(200);
 //    cgD.setWidth(0.3);
 //    cgD.statFile.setSaveCount(20000);
 //    cgD.statFile.setName(problem.getName() + ".HeavisideZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgD);
 //
 //    CG<CGFunctions::GaussZ> cgE;
 //    cgE.setNZ(200);
 //    cgE.setWidth(0.1);
 //    cgE.statFile.setSaveCount(20000);
 //    cgE.statFile.setName(problem.getName() + ".GaussZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgE);
 //
 //    CG<CGCoordinates::XZ> cgF;
 //    cgF.setNX(30);
 //    cgF.setNZ(30);
 //    cgF.setWidth(0.45);
 //    cgF.statFile.setSaveCount(20000);
 //    cgF.statFile.setName(problem.getName() + ".LucyXZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgF);
 //
 //    CG<CGFunctions::LinearXZ> cgG;
 //    cgG.setNX(30);
 //    cgG.setNZ(30);
 //    cgG.setWidth(0.45);
 //    cgG.statFile.setSaveCount(20000);
 //    cgG.statFile.setName(problem.getName() + ".LinearXZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgG);
 //
 //    CG<CGFunctions::HeavisideXZ> cgH;
 //    cgH.setNX(30);
 //    cgH.setNZ(30);
 //    cgH.setWidth(0.45);
 //    cgH.statFile.setSaveCount(20000);
 //    cgH.statFile.setName(problem.getName() + ".HeavisideXZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgH);
 //
 //    CG<CGFunctions::GaussXZ> cgI;
 //    cgI.setNX(30);
 //    cgI.setNZ(30);
 //    cgI.setWidth(0.15);
 //    cgI.statFile.setSaveCount(20000);
 //    cgI.statFile.setName(problem.getName() + ".GaussXZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgI);
 //
 //    CG<CGCoordinates::XYZ> cgJ;
 //    cgJ.setNX(10);
 //    cgJ.setNY(10);
 //    cgJ.setNZ(10);
 //    cgJ.setWidth(0.45);
 //    cgJ.statFile.setSaveCount(20000);
 //    cgJ.statFile.setName(problem.getName() + ".LucyXYZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgJ);
 //
 //    CG<CGFunctions::LinearXYZ> cgK;
 //    cgK.setNX(10);
 //    cgK.setNY(10);
 //    cgK.setNZ(10);
 //    cgK.setWidth(0.45);
 //    cgK.statFile.setSaveCount(20000);
 //    cgK.statFile.setName(problem.getName() + ".LinearXYZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgK);
 //
 //    CG<CGFunctions::HeavisideXYZ> cgL;
 //    cgL.setNX(10);
 //    cgL.setNY(10);
 //    cgL.setNZ(10);
 //    cgL.setWidth(0.45);
 //    cgL.statFile.setSaveCount(20000);
 //    cgL.statFile.setName(problem.getName() + ".HeavisideXYZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgL);
 //
 //    CG<CGFunctions::GaussXYZ> cgM;
 //    cgM.setNX(10);
 //    cgM.setNY(10);
 //    cgM.setNZ(10);
 //    cgM.setWidth(0.15);
 //    cgM.statFile.setSaveCount(20000);
 //    cgM.statFile.setName(problem.getName() + ".GaussXYZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgM);
 //
 //    CG<CGFunctions::GaussY> cg7;
 //    cg7.setNY(200);
 //    cg7.setWidth(0.15);
 //    cg7.statFile.setSaveCount(20000);
 //    cg7.statFile.setName(problem.getName() + ".GaussY.stat");
 //    problem.cgHandler.copyAndAddObject(cg7);
 //
 //    CG<CGFunctions::GaussX> cg8;
 //    cg8.setNX(200);
 //    cg8.setWidth(0.15);
 //    cg8.statFile.setSaveCount(20000);
 //    cg8.statFile.setName(problem.getName() + ".GaussX.stat");
 //    problem.cgHandler.copyAndAddObject(cg8);
 //
 //    CG<CGFunctions::GaussYZ> cg9;
 //    cg9.setNY(30);
 //    cg9.setNZ(30);
 //    cg9.setWidth(0.15);
 //    cg9.statFile.setSaveCount(20000);
 //    cg9.statFile.setName(problem.getName() + ".GaussYZ.stat");
 //    problem.cgHandler.copyAndAddObject(cg9);
 //
 //    CG<CGFunctions::GaussXY> cgA;
 //    cgA.setNX(30);
 //    cgA.setNY(30);
 //    cgA.setWidth(0.15);
 //    cgA.statFile.setSaveCount(20000);
 //    cgA.statFile.setName(problem.getName() + ".GaussXY.stat");
 //    problem.cgHandler.copyAndAddObject(cgA);
 }
References problem, File::setName(), BaseCG::setNZ(), File::setSaveCount(), CG< Coordinates, BaseFunction, Fields >::setWidth(), and BaseCG::statFile.
Referenced by main().
testCGHandler()
void testCGHandler (DPMBase & problem)
 {
     Mdouble totalMass;
     Vec3D momentumBalance;
     logger(INFO, "Analysing #0: spatially averaged statistics rho(t) at t=1");
     // cg0 stores the last available time step for analysis
     CG<CGCoordinates::O>& cg0 =
             *dynamic_cast<CG<CGCoordinates::O>*>(problem.cgHandler.getObject(0));
     cg0.writeAll(std::cout);
     //check total mass
     totalMass = cg0.getPoint(0).getDensity() - 0.8;
     momentumBalance = cg0.getPoint(0).getInteractionForceDensity()
                       + cg0.getPoint(0).getDensity() * problem.getGravity();
     logger(INFO, "Error in totalMass=%\n"
                  "Error in momentumBalance=%", totalMass, Vec3D::getLength(momentumBalance));
     //case B: z-statistics
     CG<CGCoordinates::Z>& cgB =
             *dynamic_cast<CG<CGCoordinates::Z>*>(problem.cgHandler.getObject(1));
     cgB.writeAll(std::cout);
     std::cout << std::endl;
     totalMass = 0.0;
     momentumBalance.setZero();
     for (auto& p: cgB.getPoints())
     {
         logger(INFO, "z=%", p.coordinates.getZ());
         totalMass += p.getDensity();
         momentumBalance += p.getInteractionForceDensity()
                            + p.getDensity() * problem.getGravity();
     }
     totalMass = totalMass / cgB.getPoints().size() - 0.8;
     momentumBalance /= cgB.getPoints().size();
     logger(INFO, "Error in totalMass=%\n"
                  "Error in momentumBalance=%", totalMass, Vec3D::getLength(momentumBalance));
 }
References CGFields::StandardFields::getDensity(), CGFields::StandardFields::getInteractionForceDensity(), Vec3D::getLength(), CG< Coordinates, BaseFunction, Fields >::getPoint(), CG< Coordinates, BaseFunction, Fields >::getPoints(), INFO, logger, p, problem, Vec3D::setZero(), and CG< Coordinates, BaseFunction, Fields >::writeAll().
Referenced by main().