MercuryDPM: oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM > Class Template Reference
oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM > Class Template Reference
#include <db_navier_st_elements.h>
Public Member Functions
DoubleBuoyantQCrouzeixRaviartElement ()
void unfix_pressure (const unsigned &p_dof)
UnPin p_dof-th pressure dof.
unsigned required_nvalue (const unsigned &n) const
const double & ra_t () const
Access function for the thermal Rayleigh number (const version)
double *& ra_t_pt ()
Access function for the pointer to the thermal Rayleigh number.
const double & ra_s () const
Access function for the solutal Rayleigh number (const version)
double *& ra_s_pt ()
Access function for the pointer to the solutal Rayleigh number.
void disable_ALE ()
Final override for disable ALE.
void enable_ALE ()
Final override for enable ALE.
void output (std::ostream &outfile)
Overload the standard output function with the broken default.
void output (std::ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
C-style output function: Broken default.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: Broken default.
void output_fct (std::ostream &outfile, const unsigned &Nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: Broken default.
void output_fct (std::ostream &outfile, const unsigned &Nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
unsigned c_index_adv_diff_react (const unsigned &i) const
void compute_norm (double &norm)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void get_wind_adv_diff_react (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &wind) const
void get_body_force_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_off_diagonal_jacobian_blocks_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
DoubleBuoyantQCrouzeixRaviartElement ()
void unfix_pressure (const unsigned &p_dof)
UnPin p_dof-th pressure dof.
unsigned required_nvalue (const unsigned &n) const
const double & ra_t () const
Access function for the thermal Rayleigh number (const version)
double *& ra_t_pt ()
Access function for the pointer to the thermal Rayleigh number.
const double & ra_s () const
Access function for the solutal Rayleigh number (const version)
double *& ra_s_pt ()
Access function for the pointer to the solutal Rayleigh number.
void disable_ALE ()
Final override for disable ALE.
void enable_ALE ()
Final override for enable ALE.
void output (std::ostream &outfile)
Overload the standard output function with the broken default.
void output (std::ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
C-style output function: Broken default.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: Broken default.
void output_fct (std::ostream &outfile, const unsigned &Nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: Broken default.
void output_fct (std::ostream &outfile, const unsigned &Nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
unsigned c_index_adv_diff_react (const unsigned &i) const
void compute_norm (double &norm)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void get_wind_adv_diff_react (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &wind) const
void get_body_force_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_off_diagonal_jacobian_blocks_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
DoubleBuoyantQCrouzeixRaviartElement ()
void unfix_pressure (const unsigned &p_dof)
UnPin p_dof-th pressure dof.
unsigned required_nvalue (const unsigned &n) const
const double & km () const
Access function for the transfer constant.
double *& km_pt ()
Access function for the pointer to transfer constant.
const double & n () const
Access function for the number of monomers in the micelle.
double *& n_pt ()
Access function for the pointer to the number of monomers in the micelle.
void disable_ALE ()
Final override for disable ALE.
void enable_ALE ()
Final override for enable ALE.
void get_reaction_adv_diff_react (const unsigned &ipt, const Vector< double > &C, Vector< double > &R) const
void get_reaction_deriv_adv_diff_react (const unsigned &ipt, const Vector< double > &C, DenseMatrix< double > &dRdC) const
void compute_norm (double &norm)
void output (std::ostream &outfile)
Overload the standard output function with the broken default.
void output (std::ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
C-style output function: Broken default.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: Broken default.
void output_fct (std::ostream &outfile, const unsigned &Nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: Broken default.
void output_fct (std::ostream &outfile, const unsigned &Nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
unsigned c_index_adv_diff_react (const unsigned &i) const
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void get_wind_adv_diff_react (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &wind) const
void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_off_diagonal_jacobian_blocks_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void integrated_C_and_M (double &int_C, double &int_M)
Public Member Functions inherited from oomph::QAdvectionDiffusionReactionElement< 2, DIM, 3 >
QAdvectionDiffusionReactionElement ()
QAdvectionDiffusionReactionElement (const QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D > &dummy)=delete
Broken copy constructor.
void operator= (const QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D > &)=delete
Broken assignment operator.
unsigned required_nvalue (const unsigned &n) const
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &n_plot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &n_plot)
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Public Member Functions inherited from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >
AdvectionDiffusionReactionEquations ()
AdvectionDiffusionReactionEquations (const AdvectionDiffusionReactionEquations &dummy)=delete
Broken copy constructor.
void operator= (const AdvectionDiffusionReactionEquations &)=delete
Broken assignment operator.
double dc_dt_adv_diff_react (const unsigned &n, const unsigned &r) const
void dc_dt_adv_diff_react (const unsigned &n, Vector< double > &dc_dt) const
void disable_ALE ()
void enable_ALE ()
void compute_norm (double &norm)
Compute norm of the solution: sum of squares of L2 norms for reagents.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
AdvectionDiffusionReactionSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
AdvectionDiffusionReactionSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
AdvectionDiffusionReactionWindFctPt & wind_fct_pt ()
Access function: Pointer to wind function.
AdvectionDiffusionReactionWindFctPt wind_fct_pt () const
Access function: Pointer to reaction function. Const version.
AdvectionDiffusionReactionReactionFctPt & reaction_fct_pt ()
Access function: Pointer to reaction function.
AdvectionDiffusionReactionReactionFctPt reaction_fct_pt () const
Access function: Pointer to reaction function. Const version.
AdvectionDiffusionReactionReactionDerivFctPt & reaction_deriv_fct_pt ()
Access function: Pointer to reaction derivatives function.
AdvectionDiffusionReactionReactionDerivFctPt reaction_deriv_fct_pt () const
Access function: Pointer to reaction function. Const version.
const Vector< double > & diff () const
Vector of diffusion coefficients.
Vector< double > *& diff_pt ()
Pointer to vector of diffusion coefficients.
const Vector< double > & tau () const
Vector of dimensionless timescales.
Vector< double > *& tau_pt ()
Pointer to vector of dimensionless timescales.
virtual void get_source_adv_diff_react (const unsigned &ipt, const Vector< double > &x, Vector< double > &source) const
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux: \(\mbox{flux}[DIM r + i] = \mbox{d}C_{r} / \mbox{d}x_i \).
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
double interpolated_c_adv_diff_react (const Vector< double > &s, const unsigned &i) const
Return FE representation of function value c_i(s) at local coordinate s.
unsigned self_test ()
Self-test: Return 0 for OK.
void integrate_reagents (Vector< double > &C) const
Return the integrated reagent concentrations.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::QCrouzeixRaviartElement< DIM >
QCrouzeixRaviartElement ()
Constructor, there are DIM+1 internal values (for the pressure)
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
double p_nst (const unsigned &i) const
double p_nst (const unsigned &t, const unsigned &i) const
unsigned npres_nst () const
Return number of pressure values.
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)
void identify_load_data (std::set< std::pair< Data *, unsigned >> &paired_load_data)
void identify_pressure_data (std::set< std::pair< Data *, unsigned >> &paired_pressure_data)
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void full_output (std::ostream &outfile)
void full_output (std::ostream &outfile, const unsigned &nplot)
unsigned ndof_types () const
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
void pshape_nst (const Vector< double > &s, Shape &psi) const
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
void pshape_nst (const Vector< double > &s, Shape &psi) const
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Public Member Functions inherited from oomph::NavierStokesEquations< DIM >
NavierStokesEquations ()
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
NavierStokesBodyForceFctPt & body_force_fct_pt ()
Access function for the body-force pointer.
NavierStokesBodyForceFctPt body_force_fct_pt () const
Access function for the body-force pointer. Const version.
NavierStokesSourceFctPt & source_fct_pt ()
Access function for the source-function pointer.
NavierStokesSourceFctPt source_fct_pt () const
Access function for the source-function pointer. Const version.
NavierStokesPressureAdvDiffSourceFctPt & source_fct_for_pressure_adv_diff ()
NavierStokesPressureAdvDiffSourceFctPt source_fct_for_pressure_adv_diff () const
int & pinned_fp_pressure_eqn ()
double u_nst (const unsigned &n, const unsigned &i) const
double u_nst (const unsigned &t, const unsigned &n, const unsigned &i) const
virtual unsigned u_index_nst (const unsigned &i) const
unsigned n_u_nst () const
double du_dt_nst (const unsigned &n, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
virtual int p_nodal_index_nst () const
double pressure_integral () const
Integral of pressure over element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute the vorticity vector at local coordinate s.
void get_vorticity (const Vector< double > &s, double &vorticity) const
Compute the scalar vorticity at local coordinate s (2D)
double kin_energy () const
Get integral of kinetic energy over element.
double d_kin_energy_dt () const
Get integral of time derivative of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j + du_j/dx_i)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction_p, Vector< double > &traction_visc_n, Vector< double > &traction_visc_t)
void get_load (const Vector< double > &s, const Vector< double > &N, Vector< double > &load)
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
std::string scalar_name_paraview (const unsigned &i) const
void full_output (std::ostream &outfile)
void full_output (std::ostream &outfile, const unsigned &nplot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void output_vorticity (std::ostream &outfile, const unsigned &nplot)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_norm (double &norm)
Compute norm of solution: square of the L2 norm of the velocities.
void compute_norm (Vector< double > &norm)
Compute the vector norm of the FEM solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Compute the element's residual Vector.
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
void fill_in_pressure_advection_diffusion_residuals (Vector< double > &residuals)
void fill_in_pressure_advection_diffusion_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void pin_all_non_pressure_dofs (std::map< Data *, std::vector< int >> &eqn_number_backup)
Pin all non-pressure dofs and backup eqn numbers.
void output_pressure_advection_diffusion_robin_elements (std::ostream &outfile)
void delete_pressure_advection_diffusion_robin_elements ()
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
void interpolated_u_nst (const Vector< double > &s, Vector< double > &veloc) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void dinterpolated_u_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
virtual double interpolated_p_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_p_nst (const unsigned &t, const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s at time level t.
double interpolated_dudx_nst (const Vector< double > &s, const unsigned &i, const unsigned &j) const
void point_output_data (const Vector< double > &s, Vector< double > &data)
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
void get_vorticity (const Vector< double > &s, double &vorticity) const
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute 3D vorticity vector at local coordinate s.
Public Member Functions inherited from oomph::FSIFluidElement
FSIFluidElement ()
Constructor.
FSIFluidElement (const FSIFluidElement &)=delete
Broken copy constructor.
void operator= (const FSIFluidElement &)=delete
Broken assignment operator.
Public Member Functions inherited from oomph::TemplateFreeNavierStokesEquationsBase
TemplateFreeNavierStokesEquationsBase ()
Constructor (empty)
virtual ~TemplateFreeNavierStokesEquationsBase ()
Virtual destructor (empty)
Public Member Functions inherited from oomph::NavierStokesElementWithDiagonalMassMatrices
NavierStokesElementWithDiagonalMassMatrices ()
Empty constructor.
virtual ~NavierStokesElementWithDiagonalMassMatrices ()
Virtual destructor.
NavierStokesElementWithDiagonalMassMatrices (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken copy constructor.
void operator= (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken assignment operator.
Private Member Functions
double Default_Physical_Constant_Value
Set the default physical value to be zero.
double Default_Physical_Constant_Value
Set the default physical value to be zero.
double Default_Physical_Constant_Value
Set the default physical value to be one.
Private Attributes
double * Ra_T_pt
Pointer to a private data member, the thermal Rayleigh number.
double * Ra_S_pt
Pointer to privare data member, the solutal Rayleigh number.
double * Km_pt
Pointer to private data. The value of Km.
double * N_pt
Static Private Attributes
static double Default_Physical_Constant_Value
The static default value of the Rayleigh number.
Additional Inherited Members
Public Types inherited from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >
typedef void(* AdvectionDiffusionReactionSourceFctPt) (const Vector< double > &x, Vector< double > &f)
typedef void(* AdvectionDiffusionReactionReactionFctPt) (const Vector< double > &c, Vector< double > &R)
Function pointer to reaction terms.
typedef void(* AdvectionDiffusionReactionReactionDerivFctPt) (const Vector< double > &c, DenseMatrix< double > &dRdC)
Function pointer to derivative of reaction terms.
typedef void(* AdvectionDiffusionReactionWindFctPt) (const double &time, const Vector< double > &x, Vector< double > &wind)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Types inherited from oomph::NavierStokesEquations< DIM >
typedef void(* NavierStokesBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
typedef double(* NavierStokesSourceFctPt) (const double &time, const Vector< double > &x)
typedef double(* NavierStokesPressureAdvDiffSourceFctPt) (const Vector< double > &x)
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Public Attributes inherited from oomph::NavierStokesEquations< DIM >
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Protected Member Functions inherited from oomph::QAdvectionDiffusionReactionElement< 2, DIM, 3 >
double dshape_and_dtest_eulerian_adv_diff_react (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_adv_diff_react (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Protected Member Functions inherited from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >
virtual void fill_in_generic_residual_contribution_adv_diff_react (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::QCrouzeixRaviartElement< DIM >
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Protected Member Functions inherited from oomph::NavierStokesEquations< DIM >
virtual void get_body_force_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
virtual double get_source_nst (const double &time, const unsigned &ipt, const Vector< double > &x)
virtual void get_source_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
virtual void fill_in_generic_residual_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
virtual void fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
virtual void fill_in_generic_dresidual_contribution_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, unsigned flag)
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Protected Attributes inherited from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >
Vector< double > * Diff_pt
Pointer to global diffusion coefficients.
Vector< double > * Tau_pt
Pointer to global timescales.
AdvectionDiffusionReactionSourceFctPt Source_fct_pt
Pointer to source function:
AdvectionDiffusionReactionWindFctPt Wind_fct_pt
Pointer to wind function:
AdvectionDiffusionReactionReactionFctPt Reaction_fct_pt
Pointer to reaction function.
AdvectionDiffusionReactionReactionDerivFctPt Reaction_deriv_fct_pt
Pointer to reaction derivatives.
bool ALE_is_disabled
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::QCrouzeixRaviartElement< DIM >
unsigned P_nst_internal_index
Protected Attributes inherited from oomph::NavierStokesEquations< DIM >
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
double * ReInvFr_pt
Vector< double > * G_pt
Pointer to global gravity Vector.
NavierStokesBodyForceFctPt Body_force_fct_pt
Pointer to body force function.
NavierStokesSourceFctPt Source_fct_pt
Pointer to volumetric source function.
NavierStokesPressureAdvDiffSourceFctPt Press_adv_diff_source_fct_pt
bool ALE_is_disabled
Vector< FpPressureAdvDiffRobinBCElementBase * > Pressure_advection_diffusion_robin_element_pt
int Pinned_fp_pressure_eqn
Static Protected Attributes inherited from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >
static const unsigned N_reagent
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<unsigned DIM>
class oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >
A class that solves the Boussinesq approximation of the Navier–Stokes and energy equations by coupling two pre-existing classes. The QAdvectionDiffusionReactionElement with bi-quadratic interpolation for the scalar variables (temperature and concentration) and QCrouzeixRaviartElement which solves the Navier–Stokes equations using bi-quadratic interpolation for the velocities and a discontinuous bi-linear interpolation for the pressure. Note that we are free to choose the order in which we store the variables at the nodes. In this case we choose to store the variables in the order fluid velocities followed by temperature. We must, therefore, overload the function AdvectionDiffusionReactionEquations<2,DIM>::u_index_adv_diff_react() to indicate that the temperature is stored at the DIM-th position not the 0-th. We do not need to overload the corresponding function in the NavierStokesEquations<DIM> class because the velocities are stored first.
A class that solves the Boussinesq approximation of the Navier–Stokes and energy equations by coupling two pre-existing classes. The QAdvectionDiffusionReactionElement with bi-quadratic interpolation for the scalar variables (temperature and concentration) and QCrouzeixRaviartElement which solves the Navier–Stokes equations using bi-quadratic interpolation for the velocities and a discontinuous bi-linear interpolation for the pressure. Note that we are free to choose the order in which we store the variables at the nodes. In this case we choose to store the variables in the order fluid velocities followed by bulk concentration followed by micelle concentration. We must, therefore, overload the function AdvectionDiffusionReactionEquations<2,DIM>::u_index_adv_diff_react() to indicate that the concentraion is stored at the DIM-th position not the 0-th. We do not need to overload the corresponding function in the NavierStokesEquations<DIM> class because the velocities are stored first.
Constructor & Destructor Documentation
DoubleBuoyantQCrouzeixRaviartElement() [1/3]
template<unsigned DIM> oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::DoubleBuoyantQCrouzeixRaviartElement () inline
Constructor: call the underlying constructors and initialise the pointer to the Rayleigh number to point to the default value of 0.0.
                                         :
   QAdvectionDiffusionReactionElement<2,DIM,3>(),
   QCrouzeixRaviartElement<DIM>()
   {
    Ra_T_pt = &Default_Physical_Constant_Value;
    Ra_S_pt = &Default_Physical_Constant_Value;
   }
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Default_Physical_Constant_Value, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Ra_S_pt, and oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Ra_T_pt.
DoubleBuoyantQCrouzeixRaviartElement() [2/3]
template<unsigned DIM> oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::DoubleBuoyantQCrouzeixRaviartElement () inline
Constructor: call the underlying constructors and initialise the pointer to the Rayleigh number to point to the default value of 0.0.
                                         :
   QAdvectionDiffusionReactionElement<2,DIM,3>(),
   QCrouzeixRaviartElement<DIM>()
   {
    Ra_T_pt = &Default_Physical_Constant_Value;
    Ra_S_pt = &Default_Physical_Constant_Value;
   }
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Default_Physical_Constant_Value, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Ra_S_pt, and oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Ra_T_pt.
DoubleBuoyantQCrouzeixRaviartElement() [3/3]
template<unsigned DIM> oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::DoubleBuoyantQCrouzeixRaviartElement () inline
Constructor: call the underlying constructors and initialise the pointer to the Rayleigh number to point to the default value of 0.0.
                                         :
   QAdvectionDiffusionReactionElement<2,DIM,3>(),
   QCrouzeixRaviartElement<DIM>()
   {
     Km_pt = &Default_Physical_Constant_Value;
     N_pt = &Default_Physical_Constant_Value;
   }
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Default_Physical_Constant_Value, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Km_pt, and oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::N_pt.
Member Function Documentation
c_index_adv_diff_react() [1/3]
template<unsigned DIM> unsigned oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::c_index_adv_diff_react (const unsigned & i) const inline virtual
Overload the index at which the temperature and solute concentration variables are stored.
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
   {return DIM+i;}
References DIM, and i.
Referenced by oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::get_body_force_nst(), and oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::integrated_C_and_M().
c_index_adv_diff_react() [2/3]
template<unsigned DIM> unsigned oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::c_index_adv_diff_react (const unsigned & i) const inline virtual
Overload the index at which the temperature and solute concentration variables are stored.
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
   {return DIM+i;}
References DIM, and i.
c_index_adv_diff_react() [3/3]
template<unsigned DIM> unsigned oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::c_index_adv_diff_react (const unsigned & i) const inline virtual
Overload the index at which the temperature and solute concentration variables are stored.
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
   {return DIM+i;}
References DIM, and i.
compute_error() [1/6]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) inline virtual
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element Call the broken default
Reimplemented from oomph::FiniteElement.
   {FiniteElement::compute_error(outfile,exact_soln_pt,error,norm);}
References oomph::FiniteElement::compute_error(), and calibrate::error.
compute_error() [2/6]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) inline virtual
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element Call the broken default
Reimplemented from oomph::FiniteElement.
   {FiniteElement::compute_error(outfile,exact_soln_pt,error,norm);}
References oomph::FiniteElement::compute_error(), and calibrate::error.
compute_error() [3/6]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) inline virtual
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element Call the broken default
Reimplemented from oomph::FiniteElement.
   {FiniteElement::compute_error(outfile,exact_soln_pt,error,norm);}
References oomph::FiniteElement::compute_error(), and calibrate::error.
compute_error() [4/6]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) inline virtual
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element Call the broken default
Reimplemented from oomph::FiniteElement.
   {FiniteElement::compute_error(outfile,exact_soln_pt,
                                 time,error,norm);}
References oomph::FiniteElement::compute_error(), and calibrate::error.
compute_error() [5/6]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) inline virtual
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element Call the broken default
Reimplemented from oomph::FiniteElement.
   {FiniteElement::compute_error(outfile,exact_soln_pt,
                                 time,error,norm);}
References oomph::FiniteElement::compute_error(), and calibrate::error.
compute_error() [6/6]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) inline virtual
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element Call the broken default
Reimplemented from oomph::FiniteElement.
   {FiniteElement::compute_error(outfile,exact_soln_pt,
                                 time,error,norm);}
References oomph::FiniteElement::compute_error(), and calibrate::error.
compute_norm() [1/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::compute_norm (double & norm) inline virtual
Compute norm of solution – broken virtual can be overloaded by element writer to implement whatever norm is desired for the specific element
Reimplemented from oomph::GeneralisedElement.
   {QCrouzeixRaviartElement<DIM>::compute_norm(norm);}
References oomph::NavierStokesEquations< DIM >::compute_norm().
compute_norm() [2/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::compute_norm (double & norm) inline virtual
Compute norm of solution – broken virtual can be overloaded by element writer to implement whatever norm is desired for the specific element
Reimplemented from oomph::GeneralisedElement.
   {QCrouzeixRaviartElement<DIM>::compute_norm(norm);}
References oomph::NavierStokesEquations< DIM >::compute_norm().
compute_norm() [3/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::compute_norm (double & norm) inline virtual
Compute norm of solution – broken virtual can be overloaded by element writer to implement whatever norm is desired for the specific element
Reimplemented from oomph::GeneralisedElement.
   {QCrouzeixRaviartElement<DIM>::compute_norm(norm);}
References oomph::NavierStokesEquations< DIM >::compute_norm().
Default_Physical_Constant_Value() [1/3]
double oomph::DoubleBuoyantQCrouzeixRaviartElement< 2 >::Default_Physical_Constant_Value private
Set the default physical value to be zero.
Default_Physical_Constant_Value() [2/3]
double oomph::DoubleBuoyantQCrouzeixRaviartElement< 2 >::Default_Physical_Constant_Value private
Set the default physical value to be zero.
Default_Physical_Constant_Value() [3/3]
double oomph::DoubleBuoyantQCrouzeixRaviartElement< 2 >::Default_Physical_Constant_Value private
Set the default physical value to be one.
disable_ALE() [1/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::disable_ALE () inline virtual
Final override for disable ALE.
Reimplemented from oomph::FiniteElement.
   {
    //Disable ALE in both sets of equations
    NavierStokesEquations<DIM>::disable_ALE();
    AdvectionDiffusionReactionEquations<2,DIM>::disable_ALE();
   }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::disable_ALE(), and oomph::NavierStokesEquations< DIM >::disable_ALE().
disable_ALE() [2/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::disable_ALE () inline virtual
Final override for disable ALE.
Reimplemented from oomph::FiniteElement.
   {
    //Disable ALE in both sets of equations
    NavierStokesEquations<DIM>::disable_ALE();
    AdvectionDiffusionReactionEquations<2,DIM>::disable_ALE();
   }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::disable_ALE(), and oomph::NavierStokesEquations< DIM >::disable_ALE().
disable_ALE() [3/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::disable_ALE () inline virtual
Final override for disable ALE.
Reimplemented from oomph::FiniteElement.
   {
    //Disable ALE in both sets of equations
    NavierStokesEquations<DIM>::disable_ALE();
    AdvectionDiffusionReactionEquations<2,DIM>::disable_ALE();
   }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::disable_ALE(), and oomph::NavierStokesEquations< DIM >::disable_ALE().
enable_ALE() [1/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::enable_ALE () inline virtual
Final override for enable ALE.
Reimplemented from oomph::FiniteElement.
   {
    //Enable ALE in both sets of equations
    NavierStokesEquations<DIM>::enable_ALE();
    AdvectionDiffusionReactionEquations<2,DIM>::enable_ALE();
   }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::enable_ALE(), and oomph::NavierStokesEquations< DIM >::enable_ALE().
enable_ALE() [2/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::enable_ALE () inline virtual
Final override for enable ALE.
Reimplemented from oomph::FiniteElement.
   {
    //Enable ALE in both sets of equations
    NavierStokesEquations<DIM>::enable_ALE();
    AdvectionDiffusionReactionEquations<2,DIM>::enable_ALE();
   }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::enable_ALE(), and oomph::NavierStokesEquations< DIM >::enable_ALE().
enable_ALE() [3/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::enable_ALE () inline virtual
Final override for enable ALE.
Reimplemented from oomph::FiniteElement.
   {
    //Enable ALE in both sets of equations
    NavierStokesEquations<DIM>::enable_ALE();
    AdvectionDiffusionReactionEquations<2,DIM>::enable_ALE();
   }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::enable_ALE(), and oomph::NavierStokesEquations< DIM >::enable_ALE().
fill_in_contribution_to_jacobian() [1/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Compute the element's residual Vector and the Jacobian matrix. Use finite-differencing only for the off-diagonal blocks.
Reimplemented from oomph::GeneralisedElement.
   {
    //Calculate the Navier-Stokes contributions (diagonal block and residuals)
    NavierStokesEquations<DIM>::
     fill_in_contribution_to_jacobian(residuals,jacobian);
    //Calculate the advection-diffusion contributions
    //(diagonal block and residuals)
    AdvectionDiffusionReactionEquations<2,DIM>::
     fill_in_contribution_to_jacobian(residuals,jacobian);
    //Add in the off-diagonal blocks
    fill_in_off_diagonal_jacobian_blocks_by_fd(residuals,jacobian);
   } //End of jacobian calculation
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_contribution_to_jacobian(), oomph::NavierStokesEquations< DIM >::fill_in_contribution_to_jacobian(), and oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd().
fill_in_contribution_to_jacobian() [2/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Compute the element's residual Vector and the Jacobian matrix. Use finite-differencing only for the off-diagonal blocks.
Reimplemented from oomph::GeneralisedElement.
   {
    //Calculate the Navier-Stokes contributions (diagonal block and residuals)
    NavierStokesEquations<DIM>::
     fill_in_contribution_to_jacobian(residuals,jacobian);
    //Calculate the advection-diffusion contributions
    //(diagonal block and residuals)
    AdvectionDiffusionReactionEquations<2,DIM>::
     fill_in_contribution_to_jacobian(residuals,jacobian);
    //Add in the off-diagonal blocks
    fill_in_off_diagonal_jacobian_blocks_by_fd(residuals,jacobian);
   } //End of jacobian calculation
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_contribution_to_jacobian(), oomph::NavierStokesEquations< DIM >::fill_in_contribution_to_jacobian(), and oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd().
fill_in_contribution_to_jacobian() [3/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Compute the element's residual Vector and the Jacobian matrix. Use finite-differencing only for the off-diagonal blocks.
Reimplemented from oomph::GeneralisedElement.
   {
    //Calculate the Navier-Stokes contributions (diagonal block and residuals)
    NavierStokesEquations<DIM>::
     fill_in_contribution_to_jacobian(residuals,jacobian);
    //Calculate the advection-diffusion contributions
    //(diagonal block and residuals)
    AdvectionDiffusionReactionEquations<2,DIM>::
     fill_in_contribution_to_jacobian(residuals,jacobian);
    //Add in the off-diagonal blocks
    fill_in_off_diagonal_jacobian_blocks_by_fd(residuals,jacobian);
   } //End of jacobian calculation
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_contribution_to_jacobian(), oomph::NavierStokesEquations< DIM >::fill_in_contribution_to_jacobian(), and oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd().
fill_in_contribution_to_jacobian_and_mass_matrix() [1/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) inline virtual
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix
Reimplemented from oomph::GeneralisedElement.
   {
    NavierStokesEquations<DIM>::
     fill_in_contribution_to_jacobian_and_mass_matrix(
      residuals,jacobian,mass_matrix);
    AdvectionDiffusionReactionEquations<2,DIM>::
     fill_in_contribution_to_jacobian_and_mass_matrix(
      residuals,jacobian,mass_matrix);
    fill_in_off_diagonal_jacobian_blocks_by_fd(residuals,jacobian);
   }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::NavierStokesEquations< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), and oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd().
fill_in_contribution_to_jacobian_and_mass_matrix() [2/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) inline virtual
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix
Reimplemented from oomph::GeneralisedElement.
   {
    NavierStokesEquations<DIM>::
     fill_in_contribution_to_jacobian_and_mass_matrix(
      residuals,jacobian,mass_matrix);
    AdvectionDiffusionReactionEquations<2,DIM>::
     fill_in_contribution_to_jacobian_and_mass_matrix(
      residuals,jacobian,mass_matrix);
    fill_in_off_diagonal_jacobian_blocks_by_fd(residuals,jacobian);
   }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::NavierStokesEquations< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), and oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd().
fill_in_contribution_to_jacobian_and_mass_matrix() [3/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) inline virtual
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix
Reimplemented from oomph::GeneralisedElement.
   {
    NavierStokesEquations<DIM>::
     fill_in_contribution_to_jacobian_and_mass_matrix(
      residuals,jacobian,mass_matrix);
    AdvectionDiffusionReactionEquations<2,DIM>::
     fill_in_contribution_to_jacobian_and_mass_matrix(
      residuals,jacobian,mass_matrix);
    fill_in_off_diagonal_jacobian_blocks_by_fd(residuals,jacobian);
   }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::NavierStokesEquations< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), and oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd().
fill_in_contribution_to_residuals() [1/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Calculate the element's contribution to the residual vector. Recall that fill_in_* functions MUST NOT initialise the entries in the vector to zero. This allows us to call the fill_in_* functions of the constituent single-physics elements sequentially, without wiping out any previously computed entries.
Reimplemented from oomph::GeneralisedElement.
   {
    //Fill in the residuals of the Navier-Stokes equations
    NavierStokesEquations<DIM>::fill_in_contribution_to_residuals(residuals);
    //Fill in the residuals of the advection-diffusion eqautions
    AdvectionDiffusionReactionEquations<2,DIM>::
     fill_in_contribution_to_residuals(residuals);
   }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_contribution_to_residuals(), and oomph::NavierStokesEquations< DIM >::fill_in_contribution_to_residuals().
fill_in_contribution_to_residuals() [2/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Calculate the element's contribution to the residual vector. Recall that fill_in_* functions MUST NOT initialise the entries in the vector to zero. This allows us to call the fill_in_* functions of the constituent single-physics elements sequentially, without wiping out any previously computed entries.
Reimplemented from oomph::GeneralisedElement.
   {
    //Fill in the residuals of the Navier-Stokes equations
    NavierStokesEquations<DIM>::fill_in_contribution_to_residuals(residuals);
    //Fill in the residuals of the advection-diffusion eqautions
    AdvectionDiffusionReactionEquations<2,DIM>::
     fill_in_contribution_to_residuals(residuals);
   }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_contribution_to_residuals(), and oomph::NavierStokesEquations< DIM >::fill_in_contribution_to_residuals().
fill_in_contribution_to_residuals() [3/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Calculate the element's contribution to the residual vector. Recall that fill_in_* functions MUST NOT initialise the entries in the vector to zero. This allows us to call the fill_in_* functions of the constituent single-physics elements sequentially, without wiping out any previously computed entries.
Reimplemented from oomph::GeneralisedElement.
   {
    //Fill in the residuals of the Navier-Stokes equations
    NavierStokesEquations<DIM>::fill_in_contribution_to_residuals(residuals);
    //Fill in the residuals of the advection-diffusion eqautions
    AdvectionDiffusionReactionEquations<2,DIM>::
     fill_in_contribution_to_residuals(residuals);
   }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_contribution_to_residuals(), and oomph::NavierStokesEquations< DIM >::fill_in_contribution_to_residuals().
fill_in_off_diagonal_jacobian_blocks_by_fd() [1/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline
Helper function to get the off-diagonal blocks of the Jacobian matrix by finite differences
   {
    //Local storage for the index in the nodes at which the
    //Navier-Stokes velocities are stored (we know that this should be 0,1,2)
    unsigned u_nodal_nst[DIM];
    for(unsigned i=0;i<DIM;i++)
     {u_nodal_nst[i] = this->u_index_nst(i);}
    //Local storage for the  index at which the temperature and
    //solute are  stored
    unsigned C_nodal_adv_diff_react[2];
    for(unsigned r=0;r<2;r++)
     {C_nodal_adv_diff_react[r] = this->c_index_adv_diff_react(r);}
    //Find the total number of unknowns in the elements
    unsigned n_dof = this->ndof();
    //Temporary storage for residuals
    Vector<double> newres(n_dof);
    //Storage for local unknown and local equation
    int local_unknown =0, local_eqn = 0;
    //Set the finite difference step
    double fd_step = FiniteElement::Default_fd_jacobian_step;
    //Find the number of nodes
    unsigned n_node = this->nnode();
    //Calculate the contribution of the Navier--Stokes velocities to the
    //advection-diffusion equations
    //Loop over the nodes
    for(unsigned n=0;n<n_node;n++)
     {
      //There are DIM values of the  velocities
      for(unsigned i=0;i<DIM;i++)
       {
        //Get the local velocity equation number
        local_unknown = this->nodal_local_eqn(n,u_nodal_nst[i]);
        //If it's not pinned
        if(local_unknown >= 0)
         {
          //Get a pointer to the velocity value
          double *value_pt = this->node_pt(n)->value_pt(u_nodal_nst[i]);
          //Save the old value
          double old_var = *value_pt;
          //Increment the value
          *value_pt += fd_step;
          //Get the altered advection-diffusion residuals.
          //Do this using fill_in because get_residuals has never been
          //overloaded, and will actually compute all residuals which
          //is slightly inefficient.
          for(unsigned m=0;m<n_dof;m++) {newres[m] = 0.0;}
          AdvectionDiffusionReactionEquations<2,DIM>::
           fill_in_contribution_to_residuals(newres);
          //Now fill in the Advection-Diffusion-Reaction sub-block
          //of the jacobian
          for(unsigned m=0;m<n_node;m++)
           {
            for(unsigned r=0;r<2;r++)
             {
              //Local equation for temperature or solute
              local_eqn = this->nodal_local_eqn(m,C_nodal_adv_diff_react[r]);
              //If it's not a boundary condition
              if(local_eqn >= 0)
               {
                double sum = (newres[local_eqn] - residuals[local_eqn])/fd_step;
                jacobian(local_eqn,local_unknown) = sum;
               }
             }
           }
          //Reset the nodal data
          *value_pt = old_var;
         }
       }
      //Calculate the contribution of the temperature to the Navier--Stokes
      //equations
      for(unsigned r=0;r<2;r++)
       {
        //Get the local equation number
        local_unknown = this->nodal_local_eqn(n,C_nodal_adv_diff_react[r]);
        //If it's not pinned
        if(local_unknown >= 0)
         {
          //Get a pointer to the concentration value
          double *value_pt =
           this->node_pt(n)->value_pt(C_nodal_adv_diff_react[r]);
          //Save the old value
          double old_var = *value_pt;
          //Increment the value (Really need access)
          *value_pt += fd_step;
          //Get the altered Navier--Stokes residuals
          //Do this using fill_in because get_residuals has never been
          //overloaded, and will actually compute all residuals which
          //is slightly inefficient.
          for(unsigned m=0;m<n_dof;m++) {newres[m] = 0.0;}
          NavierStokesEquations<DIM>::fill_in_contribution_to_residuals(newres);
          //Now fill in the Navier-Stokes sub-block
          for(unsigned m=0;m<n_node;m++)
           {
            //Loop over the fluid velocities
            for(unsigned j=0;j<DIM;j++)
             {
              //Local fluid equation
              local_eqn = this->nodal_local_eqn(m,u_nodal_nst[j]);
              if(local_eqn >= 0)
               {
                double sum = (newres[local_eqn] - residuals[local_eqn])/fd_step;
                jacobian(local_eqn,local_unknown) = sum;
               }
             }
           }
          //Reset the nodal data
          *value_pt = old_var;
         }
       } //End of loop over reagents
     } //End of loop over nodes
   }
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::c_index_adv_diff_react(), oomph::GeneralisedElement::Default_fd_jacobian_step, DIM, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_contribution_to_residuals(), oomph::NavierStokesEquations< DIM >::fill_in_contribution_to_residuals(), i, j, m, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::n(), oomph::GeneralisedElement::ndof(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), UniformPSDSelfTest::r, oomph::NavierStokesEquations< DIM >::u_index_nst(), and oomph::Data::value_pt().
Referenced by oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian(), and oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix().
fill_in_off_diagonal_jacobian_blocks_by_fd() [2/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline
Helper function to get the off-diagonal blocks of the Jacobian matrix by finite differences
   {
    //Local storage for the index in the nodes at which the
    //Navier-Stokes velocities are stored (we know that this should be 0,1,2)
    unsigned u_nodal_nst[DIM];
    for(unsigned i=0;i<DIM;i++)
     {u_nodal_nst[i] = this->u_index_nst(i);}
    //Local storage for the  index at which the temperature and
    //solute are  stored
    unsigned C_nodal_adv_diff_react[2];
    for(unsigned r=0;r<2;r++)
     {C_nodal_adv_diff_react[r] = this->c_index_adv_diff_react(r);}
    //Find the total number of unknowns in the elements
    unsigned n_dof = this->ndof();
    //Temporary storage for residuals
    Vector<double> newres(n_dof);
    //Storage for local unknown and local equation
    int local_unknown =0, local_eqn = 0;
    //Set the finite difference step
    double fd_step = FiniteElement::Default_fd_jacobian_step;
    //Find the number of nodes
    unsigned n_node = this->nnode();
    //Calculate the contribution of the Navier--Stokes velocities to the
    //advection-diffusion equations
    //Loop over the nodes
    for(unsigned n=0;n<n_node;n++)
     {
      //There are DIM values of the  velocities
      for(unsigned i=0;i<DIM;i++)
       {
        //Get the local velocity equation number
        local_unknown = this->nodal_local_eqn(n,u_nodal_nst[i]);
        //If it's not pinned
        if(local_unknown >= 0)
         {
          //Get a pointer to the velocity value
          double *value_pt = this->node_pt(n)->value_pt(u_nodal_nst[i]);
          //Save the old value
          double old_var = *value_pt;
          //Increment the value
          *value_pt += fd_step;
          //Get the altered advection-diffusion residuals.
          //Do this using fill_in because get_residuals has never been
          //overloaded, and will actually compute all residuals which
          //is slightly inefficient.
          for(unsigned m=0;m<n_dof;m++) {newres[m] = 0.0;}
          AdvectionDiffusionReactionEquations<2,DIM>::
           fill_in_contribution_to_residuals(newres);
          //Now fill in the Advection-Diffusion-Reaction sub-block
          //of the jacobian
          for(unsigned m=0;m<n_node;m++)
           {
            for(unsigned r=0;r<2;r++)
             {
              //Local equation for temperature or solute
              local_eqn = this->nodal_local_eqn(m,C_nodal_adv_diff_react[r]);
              //If it's not a boundary condition
              if(local_eqn >= 0)
               {
                double sum = (newres[local_eqn] - residuals[local_eqn])/fd_step;
                jacobian(local_eqn,local_unknown) = sum;
               }
             }
           }
          //Reset the nodal data
          *value_pt = old_var;
         }
       }
      //Calculate the contribution of the temperature to the Navier--Stokes
      //equations
      for(unsigned r=0;r<2;r++)
       {
        //Get the local equation number
        local_unknown = this->nodal_local_eqn(n,C_nodal_adv_diff_react[r]);
        //If it's not pinned
        if(local_unknown >= 0)
         {
          //Get a pointer to the concentration value
          double *value_pt =
           this->node_pt(n)->value_pt(C_nodal_adv_diff_react[r]);
          //Save the old value
          double old_var = *value_pt;
          //Increment the value (Really need access)
          *value_pt += fd_step;
          //Get the altered Navier--Stokes residuals
          //Do this using fill_in because get_residuals has never been
          //overloaded, and will actually compute all residuals which
          //is slightly inefficient.
          for(unsigned m=0;m<n_dof;m++) {newres[m] = 0.0;}
          NavierStokesEquations<DIM>::fill_in_contribution_to_residuals(newres);
          //Now fill in the Navier-Stokes sub-block
          for(unsigned m=0;m<n_node;m++)
           {
            //Loop over the fluid velocities
            for(unsigned j=0;j<DIM;j++)
             {
              //Local fluid equation
              local_eqn = this->nodal_local_eqn(m,u_nodal_nst[j]);
              if(local_eqn >= 0)
               {
                double sum = (newres[local_eqn] - residuals[local_eqn])/fd_step;
                jacobian(local_eqn,local_unknown) = sum;
               }
             }
           }
          //Reset the nodal data
          *value_pt = old_var;
         }
       } //End of loop over reagents
     } //End of loop over nodes
   }
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::c_index_adv_diff_react(), oomph::GeneralisedElement::Default_fd_jacobian_step, DIM, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_contribution_to_residuals(), oomph::NavierStokesEquations< DIM >::fill_in_contribution_to_residuals(), i, j, m, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::n(), oomph::GeneralisedElement::ndof(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), UniformPSDSelfTest::r, oomph::NavierStokesEquations< DIM >::u_index_nst(), and oomph::Data::value_pt().
fill_in_off_diagonal_jacobian_blocks_by_fd() [3/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline
Helper function to get the off-diagonal blocks of the Jacobian matrix by finite differences
   {
    //Local storage for the index in the nodes at which the
    //Navier-Stokes velocities are stored (we know that this should be 0,1,2)
    unsigned u_nodal_nst[DIM];
    for(unsigned i=0;i<DIM;i++)
     {u_nodal_nst[i] = this->u_index_nst(i);}
    //Local storage for the  index at which the temperature and
    //solute are  stored
    unsigned C_nodal_adv_diff_react[2];
    for(unsigned r=0;r<2;r++)
     {C_nodal_adv_diff_react[r] = this->c_index_adv_diff_react(r);}
    //Find the total number of unknowns in the elements
    unsigned n_dof = this->ndof();
    //Temporary storage for residuals
    Vector<double> newres(n_dof);
    //Storage for local unknown and local equation
    int local_unknown =0, local_eqn = 0;
    //Set the finite difference step
    double fd_step = FiniteElement::Default_fd_jacobian_step;
    //Find the number of nodes
    unsigned n_node = this->nnode();
    //Calculate the contribution of the Navier--Stokes velocities to the
    //advection-diffusion equations
    //Loop over the nodes
    for(unsigned n=0;n<n_node;n++)
     {
      //There are DIM values of the  velocities
      for(unsigned i=0;i<DIM;i++)
       {
        //Get the local velocity equation number
        local_unknown = this->nodal_local_eqn(n,u_nodal_nst[i]);
        //If it's not pinned
        if(local_unknown >= 0)
         {
          //Get a pointer to the velocity value
          double *value_pt = this->node_pt(n)->value_pt(u_nodal_nst[i]);
          //Save the old value
          double old_var = *value_pt;
          //Increment the value
          *value_pt += fd_step;
          //Get the altered advection-diffusion residuals.
          //Do this using fill_in because get_residuals has never been
          //overloaded, and will actually compute all residuals which
          //is slightly inefficient.
          for(unsigned m=0;m<n_dof;m++) {newres[m] = 0.0;}
          AdvectionDiffusionReactionEquations<2,DIM>::
           fill_in_contribution_to_residuals(newres);
          //Now fill in the Advection-Diffusion-Reaction sub-block
          //of the jacobian
          for(unsigned m=0;m<n_node;m++)
           {
            for(unsigned r=0;r<2;r++)
             {
              //Local equation for temperature or solute
              local_eqn = this->nodal_local_eqn(m,C_nodal_adv_diff_react[r]);
              //If it's not a boundary condition
              if(local_eqn >= 0)
               {
                double sum = (newres[local_eqn] - residuals[local_eqn])/fd_step;
                jacobian(local_eqn,local_unknown) = sum;
               }
             }
           }
          //Reset the nodal data
          *value_pt = old_var;
         }
       }
      //Calculate the contribution of the temperature to the Navier--Stokes
      //equations
      for(unsigned r=0;r<2;r++)
       {
        //Get the local equation number
        local_unknown = this->nodal_local_eqn(n,C_nodal_adv_diff_react[r]);
        //If it's not pinned
        if(local_unknown >= 0)
         {
          //Get a pointer to the concentration value
          double *value_pt =
           this->node_pt(n)->value_pt(C_nodal_adv_diff_react[r]);
          //Save the old value
          double old_var = *value_pt;
          //Increment the value (Really need access)
          *value_pt += fd_step;
          //Get the altered Navier--Stokes residuals
          //Do this using fill_in because get_residuals has never been
          //overloaded, and will actually compute all residuals which
          //is slightly inefficient.
          for(unsigned m=0;m<n_dof;m++) {newres[m] = 0.0;}
          NavierStokesEquations<DIM>::fill_in_contribution_to_residuals(newres);
          //Now fill in the Navier-Stokes sub-block
          for(unsigned m=0;m<n_node;m++)
           {
            //Loop over the fluid velocities
            for(unsigned j=0;j<DIM;j++)
             {
              //Local fluid equation
              local_eqn = this->nodal_local_eqn(m,u_nodal_nst[j]);
              if(local_eqn >= 0)
               {
                double sum = (newres[local_eqn] - residuals[local_eqn])/fd_step;
                jacobian(local_eqn,local_unknown) = sum;
               }
             }
           }
          //Reset the nodal data
          *value_pt = old_var;
         }
       } //End of loop over reagents
     } //End of loop over nodes
   }
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::c_index_adv_diff_react(), oomph::GeneralisedElement::Default_fd_jacobian_step, DIM, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_contribution_to_residuals(), oomph::NavierStokesEquations< DIM >::fill_in_contribution_to_residuals(), i, j, m, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::n(), oomph::GeneralisedElement::ndof(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), UniformPSDSelfTest::r, oomph::NavierStokesEquations< DIM >::u_index_nst(), and oomph::Data::value_pt().
get_body_force_nst() [1/2]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::get_body_force_nst (const double & time, const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & result) inline virtual
Overload the body force in the Navier-Stokes equations This provides the coupling from the advection-diffusion equations to the Navier–Stokes equations, the body force is the temperature multiplied by the Rayleigh number acting in the direction opposite to gravity.
Reimplemented from oomph::NavierStokesEquations< DIM >.
   {
    // Get vector that indicates the direction of gravity from
    // the Navier-Stokes equations
    Vector<double> gravity(NavierStokesEquations<DIM>::g());
    //Get the indices at which the temp and concentration are stored
    unsigned c_index[2];
    for(unsigned r=0;r<2;r++)
     {c_index[r] = this->c_index_adv_diff_react(r);}
    //Now get the shape function
    const unsigned n_node = this->nnode();
    Shape psi(n_node);
    //Get the shape functions
    this->shape(s,psi);
    //Storage for the local values of advected quantities
    Vector<double> interpolated_c(2,0.0);
    //Get the values
    for(unsigned l=0;l<n_node;l++)
     {
      for(unsigned r=0;r<2;r++)
       {
        interpolated_c[r] += this->raw_nodal_value(l,c_index[r])*psi(l);
       }
     }
    // Temperature and concentration-dependent body force:
    for(unsigned i=0;i<DIM;i++)
     {
      result[i] = -gravity[i]*
       //Thermal contribution      //Concentration contribution
       (interpolated_c[0]*ra_t() + interpolated_c[1]*ra_s());
     }
   }
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::c_index_adv_diff_react(), DIM, Gravity::gravity(), i, oomph::FiniteElement::nnode(), UniformPSDSelfTest::r, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::ra_s(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::ra_t(), oomph::FiniteElement::raw_nodal_value(), and oomph::FiniteElement::shape().
get_body_force_nst() [2/2]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::get_body_force_nst (const double & time, const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & result) inline virtual
Overload the body force in the Navier-Stokes equations This provides the coupling from the advection-diffusion equations to the Navier–Stokes equations, the body force is the temperature multiplied by the Rayleigh number acting in the direction opposite to gravity.
Reimplemented from oomph::NavierStokesEquations< DIM >.
   {
    // Get vector that indicates the direction of gravity from
    // the Navier-Stokes equations
    Vector<double> gravity(NavierStokesEquations<DIM>::g());
    //Get the indices at which the temp and concentration are stored
    unsigned c_index[2];
    for(unsigned r=0;r<2;r++)
     {c_index[r] = this->c_index_adv_diff_react(r);}
    //Now get the shape function
    const unsigned n_node = this->nnode();
    Shape psi(n_node);
    //Get the shape functions
    this->shape(s,psi);
    //Storage for the local values of advected quantities
    Vector<double> interpolated_c(2,0.0);
    //Get the values
    for(unsigned l=0;l<n_node;l++)
     {
      for(unsigned r=0;r<2;r++)
       {
        interpolated_c[r] += this->raw_nodal_value(l,c_index[r])*psi(l);
       }
     }
    // Temperature and concentration-dependent body force:
    for(unsigned i=0;i<DIM;i++)
     {
      result[i] = -gravity[i]*
       //Thermal contribution      //Concentration contribution
       (interpolated_c[0]*ra_t() + interpolated_c[1]*ra_s());
     }
   }
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::c_index_adv_diff_react(), DIM, Gravity::gravity(), i, oomph::FiniteElement::nnode(), UniformPSDSelfTest::r, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::ra_s(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::ra_t(), oomph::FiniteElement::raw_nodal_value(), and oomph::FiniteElement::shape().
get_reaction_adv_diff_react()
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::get_reaction_adv_diff_react (const unsigned & ipt, const Vector< double > & C, Vector< double > & R) const inline virtual
Overload the reaction terms to couple the concentration and micelle terms
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
   {
     //Compute the flux between equations (equation (2.22))
     const double J_m = this->km()*(pow(C[0],this->n()) - C[1]);
     //Return the reaction terms
     R[0] = J_m;
     R[1] = -J_m;
   }
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::km(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::n(), Eigen::bfloat16_impl::pow(), and R.
get_reaction_deriv_adv_diff_react()
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::get_reaction_deriv_adv_diff_react (const unsigned & ipt, const Vector< double > & C, DenseMatrix< double > & dRdC) const inline virtual
Get the derivatives of the reaction terms with respect to the concentration variables. If no explicit function pointer is set, these will be calculated by finite differences
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
   {
     const double Km = this->km(); const double N = this->n();
     //Fill in the derivative terms
     dRdC(0,0) = Km*N*pow(C[0],N-1); dRdC(0,1) = -Km;
     dRdC(1,0) = -dRdC(0,0); dRdC(1,1) = -dRdC(0,1);
   }
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::km(), N, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::n(), and Eigen::bfloat16_impl::pow().
get_wind_adv_diff_react() [1/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::get_wind_adv_diff_react (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & wind) const inline virtual
Overload the wind function in the advection-diffusion equations. This provides the coupling from the Navier–Stokes equations to the advection-diffusion equations because the wind is the fluid velocity.
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
  {
    //The wind function is simply the velocity at the points
    this->interpolated_u_nst(s,wind);
  }
References oomph::NavierStokesEquations< DIM >::interpolated_u_nst().
get_wind_adv_diff_react() [2/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::get_wind_adv_diff_react (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & wind) const inline virtual
Overload the wind function in the advection-diffusion equations. This provides the coupling from the Navier–Stokes equations to the advection-diffusion equations because the wind is the fluid velocity.
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
  {
    //The wind function is simply the velocity at the points
    this->interpolated_u_nst(s,wind);
  }
References oomph::NavierStokesEquations< DIM >::interpolated_u_nst().
get_wind_adv_diff_react() [3/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::get_wind_adv_diff_react (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & wind) const inline virtual
Overload the wind function in the advection-diffusion equations. This provides the coupling from the Navier–Stokes equations to the advection-diffusion equations because the wind is the fluid velocity.
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
  {
    //The wind function is simply the velocity at the points
    this->interpolated_u_nst(s,wind);
  }
References oomph::NavierStokesEquations< DIM >::interpolated_u_nst().
integrated_C_and_M()
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::integrated_C_and_M (double & int_C, double & int_M) inline
  {
   //Vector to store the integrals
   Vector<double> sum(2,0.0);
   //Find the number of nodes
   const unsigned n_node = this->nnode();
   //Storage for the shape functions
   Shape psi(n_node);
   unsigned C_index[2];
   for(unsigned r=0;r<2;++r)
    {C_index[r] = this->c_index_adv_diff_react(r);}
   //Loop over the integration points
   const unsigned n_intpt = this->integral_pt()->nweight();
   for(unsigned ipt=0;ipt<n_intpt;ipt++)
    {
     //Get the integral weight
     double w = this->integral_pt()->weight(ipt);
     //Get the value of the Jacobian of the mapping to global coordinates
     double J = this->J_eulerian_at_knot(ipt);
     double W = w*J;
     //Get the shape function at the know
     this->shape_at_knot(ipt,psi);
     //Get the interpolated values
     Vector<double> interpolated_C(2,0.0);
     for(unsigned l=0;l<n_node;++l)
      {
       const double psi_ = psi(l);
       for(unsigned r=0;r<2;++r)
        {
         interpolated_C[r] += this->nodal_value(l,C_index[r])*psi_;
        }
      }
     for(unsigned r=0;r<2;++r)
      {
       sum[r] += interpolated_C[r]*W;
      }
    } //End of integration loop
   //Return the values
   int_C = sum[0]; int_M = sum[1];
  }
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::c_index_adv_diff_react(), oomph::FiniteElement::integral_pt(), J, oomph::FiniteElement::J_eulerian_at_knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::Integral::nweight(), UniformPSDSelfTest::r, oomph::FiniteElement::shape_at_knot(), w, oomph::QuadTreeNames::W, and oomph::Integral::weight().
km()
template<unsigned DIM> const double& oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::km () const inline
Access function for the transfer constant.
 {return *Km_pt;}
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Km_pt.
Referenced by oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::get_reaction_adv_diff_react(), and oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::get_reaction_deriv_adv_diff_react().
km_pt()
template<unsigned DIM> double* & oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::km_pt () inline
Access function for the pointer to transfer constant.
 {return Km_pt;}
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Km_pt.
n()
template<unsigned DIM> const double& oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::n () const inline
Access function for the number of monomers in the micelle.
 {return *N_pt;}
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::N_pt.
Referenced by oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::get_reaction_adv_diff_react(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::get_reaction_deriv_adv_diff_react(), and oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::required_nvalue().
n_pt()
template<unsigned DIM> double* & oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::n_pt () inline
Access function for the pointer to the number of monomers in the micelle.
 {return N_pt;}
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::N_pt.
output() [1/12]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output (FILE * file_pt) inline virtual
C-style output function: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output(file_pt);}
References oomph::FiniteElement::output().
output() [2/12]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output (FILE * file_pt) inline virtual
C-style output function: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output(file_pt);}
References oomph::FiniteElement::output().
output() [3/12]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output (FILE * file_pt) inline virtual
C-style output function: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output(file_pt);}
References oomph::FiniteElement::output().
output() [4/12]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output (FILE * file_pt, const unsigned & n_plot) inline virtual
C-style output function: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output(file_pt,n_plot);}
References oomph::FiniteElement::output().
output() [5/12]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output (FILE * file_pt, const unsigned & n_plot) inline virtual
C-style output function: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output(file_pt,n_plot);}
References oomph::FiniteElement::output().
output() [6/12]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output (FILE * file_pt, const unsigned & n_plot) inline virtual
C-style output function: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output(file_pt,n_plot);}
References oomph::FiniteElement::output().
output() [7/12]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output (std::ostream & outfile) inline virtual
Overload the standard output function with the broken default.
Reimplemented from oomph::FiniteElement.
 {FiniteElement::output(outfile);}
References oomph::FiniteElement::output().
output() [8/12]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output (std::ostream & outfile) inline virtual
Overload the standard output function with the broken default.
Reimplemented from oomph::FiniteElement.
 {FiniteElement::output(outfile);}
References oomph::FiniteElement::output().
output() [9/12]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output (std::ostream & outfile) inline virtual
Overload the standard output function with the broken default.
Reimplemented from oomph::FiniteElement.
 {FiniteElement::output(outfile);}
References oomph::FiniteElement::output().
output() [10/12]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) inline virtual
Output function:
Output x, y, u, v, p, theta at Nplot^DIM plot points
Reimplemented from oomph::FiniteElement.
   {
    //vector of local coordinates
    Vector<double> s(DIM);
    // Tecplot header info
    outfile << this->tecplot_zone_string(nplot);
    // Loop over plot points
    unsigned num_plot_points=this->nplot_points(nplot);
    for (unsigned iplot=0;iplot<num_plot_points;iplot++)
     {
      // Get local coordinates of plot point
      this->get_s_plot(iplot,nplot,s);
      // Output the position of the plot point
      for(unsigned i=0;i<DIM;i++)
       {outfile << this->interpolated_x(s,i) << " ";}
      // Output the fluid velocities at the plot point
      for(unsigned i=0;i<DIM;i++)
       {outfile << this->interpolated_u_nst(s,i) << " ";}
      // Output the fluid pressure at the plot point
      outfile << this->interpolated_p_nst(s)  << " ";
      //Output the temperature and the solute concentration
      for(unsigned i=0;i<2;i++)
       {
        outfile << this->interpolated_c_adv_diff_react(s,i) << " ";
       }
      outfile << "\n";
     }
    outfile << std::endl;
    // Write tecplot footer (e.g. FE connectivity lists)
    this->write_tecplot_zone_footer(outfile,nplot);
   } //End of output function
References DIM, oomph::FiniteElement::get_s_plot(), i, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::interpolated_c_adv_diff_react(), oomph::NavierStokesEquations< DIM >::interpolated_p_nst(), oomph::NavierStokesEquations< DIM >::interpolated_u_nst(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [11/12]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) inline virtual
Output function:
Output x, y, u, v, p, theta at Nplot^DIM plot points
Reimplemented from oomph::FiniteElement.
   {
    //vector of local coordinates
    Vector<double> s(DIM);
    // Tecplot header info
    outfile << this->tecplot_zone_string(nplot);
    // Loop over plot points
    unsigned num_plot_points=this->nplot_points(nplot);
    for (unsigned iplot=0;iplot<num_plot_points;iplot++)
     {
      // Get local coordinates of plot point
      this->get_s_plot(iplot,nplot,s);
      // Output the position of the plot point
      for(unsigned i=0;i<DIM;i++)
       {outfile << this->interpolated_x(s,i) << " ";}
      // Output the fluid velocities at the plot point
      for(unsigned i=0;i<DIM;i++)
       {outfile << this->interpolated_u_nst(s,i) << " ";}
      // Output the fluid pressure at the plot point
      outfile << this->interpolated_p_nst(s)  << " ";
      //Output the temperature and the solute concentration
      for(unsigned i=0;i<2;i++)
       {
        outfile << this->interpolated_c_adv_diff_react(s,i) << " ";
       }
      outfile << "\n";
     }
    outfile << std::endl;
    // Write tecplot footer (e.g. FE connectivity lists)
    this->write_tecplot_zone_footer(outfile,nplot);
   } //End of output function
References DIM, oomph::FiniteElement::get_s_plot(), i, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::interpolated_c_adv_diff_react(), oomph::NavierStokesEquations< DIM >::interpolated_p_nst(), oomph::NavierStokesEquations< DIM >::interpolated_u_nst(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [12/12]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) inline virtual
Output function:
Output x, y, u, v, p, theta at Nplot^DIM plot points
Reimplemented from oomph::FiniteElement.
   {
    //vector of local coordinates
    Vector<double> s(DIM);
    // Tecplot header info
    outfile << this->tecplot_zone_string(nplot);
    // Loop over plot points
    unsigned num_plot_points=this->nplot_points(nplot);
    for (unsigned iplot=0;iplot<num_plot_points;iplot++)
     {
      // Get local coordinates of plot point
      this->get_s_plot(iplot,nplot,s);
      // Output the position of the plot point
      for(unsigned i=0;i<DIM;i++)
       {outfile << this->interpolated_x(s,i) << " ";}
      // Output the fluid velocities at the plot point
      for(unsigned i=0;i<DIM;i++)
       {outfile << this->interpolated_u_nst(s,i) << " ";}
      // Output the fluid pressure at the plot point
      outfile << this->interpolated_p_nst(s)  << " ";
      //Output the temperature and the solute concentration
      for(unsigned i=0;i<2;i++)
       {
        outfile << this->interpolated_c_adv_diff_react(s,i) << " ";
       }
      outfile << "\n";
     }
    outfile << std::endl;
    // Write tecplot footer (e.g. FE connectivity lists)
    this->write_tecplot_zone_footer(outfile,nplot);
   } //End of output function
References DIM, oomph::FiniteElement::get_s_plot(), i, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::interpolated_c_adv_diff_react(), oomph::NavierStokesEquations< DIM >::interpolated_p_nst(), oomph::NavierStokesEquations< DIM >::interpolated_u_nst(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_fct() [1/6]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output_fct (std::ostream & outfile, const unsigned & Nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) inline virtual
Output function for a time-dependent exact solution: Broken default.
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
   {
    FiniteElement::
     output_fct(outfile,Nplot,time,exact_soln_pt);
   }
References oomph::FiniteElement::output_fct().
output_fct() [2/6]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output_fct (std::ostream & outfile, const unsigned & Nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) inline virtual
Output function for a time-dependent exact solution: Broken default.
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
   {
    FiniteElement::
     output_fct(outfile,Nplot,time,exact_soln_pt);
   }
References oomph::FiniteElement::output_fct().
output_fct() [3/6]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output_fct (std::ostream & outfile, const unsigned & Nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) inline virtual
Output function for a time-dependent exact solution: Broken default.
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
   {
    FiniteElement::
     output_fct(outfile,Nplot,time,exact_soln_pt);
   }
References oomph::FiniteElement::output_fct().
output_fct() [4/6]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output_fct (std::ostream & outfile, const unsigned & Nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) inline virtual
Output function for an exact solution: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output_fct(outfile,Nplot,exact_soln_pt);}
References oomph::FiniteElement::output_fct().
output_fct() [5/6]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output_fct (std::ostream & outfile, const unsigned & Nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) inline virtual
Output function for an exact solution: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output_fct(outfile,Nplot,exact_soln_pt);}
References oomph::FiniteElement::output_fct().
output_fct() [6/6]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output_fct (std::ostream & outfile, const unsigned & Nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) inline virtual
Output function for an exact solution: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output_fct(outfile,Nplot,exact_soln_pt);}
References oomph::FiniteElement::output_fct().
ra_s() [1/2]
template<unsigned DIM> const double& oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::ra_s () const inline
Access function for the solutal Rayleigh number (const version)
 {return *Ra_S_pt;}
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Ra_S_pt.
Referenced by oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::get_body_force_nst().
ra_s() [2/2]
template<unsigned DIM> const double& oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::ra_s () const inline
Access function for the solutal Rayleigh number (const version)
 {return *Ra_S_pt;}
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Ra_S_pt.
ra_s_pt() [1/2]
template<unsigned DIM> double* & oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::ra_s_pt () inline
Access function for the pointer to the solutal Rayleigh number.
 {return Ra_S_pt;}
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Ra_S_pt.
ra_s_pt() [2/2]
template<unsigned DIM> double* & oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::ra_s_pt () inline
Access function for the pointer to the solutal Rayleigh number.
 {return Ra_S_pt;}
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Ra_S_pt.
ra_t() [1/2]
template<unsigned DIM> const double& oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::ra_t () const inline
Access function for the thermal Rayleigh number (const version)
 {return *Ra_T_pt;}
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Ra_T_pt.
Referenced by oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::get_body_force_nst().
ra_t() [2/2]
template<unsigned DIM> const double& oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::ra_t () const inline
Access function for the thermal Rayleigh number (const version)
 {return *Ra_T_pt;}
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Ra_T_pt.
ra_t_pt() [1/2]
template<unsigned DIM> double* & oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::ra_t_pt () inline
Access function for the pointer to the thermal Rayleigh number.
 {return Ra_T_pt;}
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Ra_T_pt.
ra_t_pt() [2/2]
template<unsigned DIM> double* & oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::ra_t_pt () inline
Access function for the pointer to the thermal Rayleigh number.
 {return Ra_T_pt;}
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Ra_T_pt.
required_nvalue() [1/3]
template<unsigned DIM> unsigned oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::required_nvalue (const unsigned & n) const inline virtual
The required number of values stored at the nodes is the sum of the required values of the two single-physics elements. Note that this step is generic for any multi-physics element of this type.
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
   {return (QAdvectionDiffusionReactionElement<2,DIM,3>::required_nvalue(n) +
            QCrouzeixRaviartElement<DIM>::required_nvalue(n));}
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::n().
required_nvalue() [2/3]
template<unsigned DIM> unsigned oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::required_nvalue (const unsigned & n) const inline virtual
The required number of values stored at the nodes is the sum of the required values of the two single-physics elements. Note that this step is generic for any multi-physics element of this type.
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
   {return (QAdvectionDiffusionReactionElement<2,DIM,3>::required_nvalue(n) +
            QCrouzeixRaviartElement<DIM>::required_nvalue(n));}
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::n().
required_nvalue() [3/3]
template<unsigned DIM> unsigned oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::required_nvalue (const unsigned & n) const inline virtual
The required number of values stored at the nodes is the sum of the required values of the two single-physics elements. Note that this step is generic for any multi-physics element of this type.
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
   {return (QAdvectionDiffusionReactionElement<2,DIM,3>::required_nvalue(n) +
            QCrouzeixRaviartElement<DIM>::required_nvalue(n));}
References oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::n().
unfix_pressure() [1/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::unfix_pressure (const unsigned & p_dof) inline
UnPin p_dof-th pressure dof.
   {
    this->internal_data_pt(this->P_nst_internal_index)->unpin(p_dof);
   }
References oomph::GeneralisedElement::internal_data_pt(), oomph::QCrouzeixRaviartElement< DIM >::P_nst_internal_index, and oomph::Data::unpin().
unfix_pressure() [2/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::unfix_pressure (const unsigned & p_dof) inline
UnPin p_dof-th pressure dof.
   {
    this->internal_data_pt(this->P_nst_internal_index)->unpin(p_dof);
   }
References oomph::GeneralisedElement::internal_data_pt(), oomph::QCrouzeixRaviartElement< DIM >::P_nst_internal_index, and oomph::Data::unpin().
unfix_pressure() [3/3]
template<unsigned DIM> void oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::unfix_pressure (const unsigned & p_dof) inline
UnPin p_dof-th pressure dof.
   {
    this->internal_data_pt(this->P_nst_internal_index)->unpin(p_dof);
   }
References oomph::GeneralisedElement::internal_data_pt(), oomph::QCrouzeixRaviartElement< DIM >::P_nst_internal_index, and oomph::Data::unpin().
Member Data Documentation
Default_Physical_Constant_Value
template<unsigned DIM> static double oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Default_Physical_Constant_Value static private
The static default value of the Rayleigh number.
Referenced by oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::DoubleBuoyantQCrouzeixRaviartElement().
Km_pt
template<unsigned DIM> double* oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Km_pt private
Pointer to private data. The value of Km.
Referenced by oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::DoubleBuoyantQCrouzeixRaviartElement(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::km(), and oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::km_pt().
N_pt
template<unsigned DIM> double* oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::N_pt private
Referenced by oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::DoubleBuoyantQCrouzeixRaviartElement(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::n(), and oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::n_pt().
Ra_S_pt
template<unsigned DIM> double * oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Ra_S_pt private
Pointer to privare data member, the solutal Rayleigh number.
Referenced by oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::DoubleBuoyantQCrouzeixRaviartElement(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::ra_s(), and oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::ra_s_pt().
Ra_T_pt
template<unsigned DIM> double * oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::Ra_T_pt private
Pointer to a private data member, the thermal Rayleigh number.
Referenced by oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::DoubleBuoyantQCrouzeixRaviartElement(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::ra_t(), and oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::ra_t_pt().
The documentation for this class was generated from the following files:
db_navier_st_elements.h
soluble_surfactant/double_buoyant_navier_stokes_elements.h