MercuryDPM: oomph::ChannelSpineMesh< ELEMENT > Class Template Reference
oomph::ChannelSpineMesh< ELEMENT > Class Template Reference
#include <channel_spine_mesh.template.h>
Public Member Functions
ChannelSpineMesh (const unsigned &nx0, const unsigned &nx1, const unsigned &nx2, const unsigned &ny, const double &lx0, const double &lx1, const double &lx2, const double &h, GeomObject *wall_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
ChannelSpineMesh (const unsigned &nx0, const unsigned &nx1, const unsigned &nx2, const unsigned &ny, const double &lx0, const double &lx1, const double &lx2, const double &h, GeomObject *wall_pt, const bool &periodic_in_x, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
FiniteElement *& left_element_pt (const unsigned long &i)
FiniteElement *& centre_element_pt (const unsigned long &i)
FiniteElement *& right_element_pt (const unsigned long &i)
unsigned long nleft () const
Number of elements in left region.
unsigned long ncentre () const
Number of elements in centre region.
unsigned long nright () const
Number of elements in right region.
unsigned long nbulk () const
Number of elements in bulk.
void element_reorder ()
virtual void spine_node_update (SpineNode *spine_node_pt)
virtual double x_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode)
Spine *& left_spine_pt (const unsigned long &i)
Access function for spines in left region.
Spine *& centre_spine_pt (const unsigned long &i)
Access function for spines in centre region.
Spine *& right_spine_pt (const unsigned long &i)
Access function for spines in right region.
unsigned nleft_spine ()
Access function for the number of spines in the left region.
unsigned ncentre_spine ()
Access function for the number of spines in the centre region.
unsigned nright_spine ()
Access function for the number of spines in the right region.
GeomObject * wall_pt ()
Access function to the GeomObject for upper wall.
GeomObject * straight_wall_pt ()
Access function to the GeomObject for the straight upper wall.
Public Member Functions inherited from oomph::RectangularQuadMesh< ELEMENT >
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &xmin, const double &xmax, const double &ymin, const double &ymax, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly, const bool &periodic_in_x, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &xmin, const double &xmax, const double &ymin, const double &ymax, const bool &periodic_in_x, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
const unsigned & nx () const
Return number of elements in x direction.
const unsigned & ny () const
Return number of elements in y direction.
const double x_min () const
Return the minimum value of x coordinate.
const double x_max () const
Return the maximum value of x coordinate.
const double y_min () const
Return the minimum value of y coordinate.
const double y_max () const
Return the maximum value of y coordinate.
virtual double y_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode)
Public Member Functions inherited from oomph::QuadMeshBase
QuadMeshBase ()
Constructor (empty)
QuadMeshBase (const QuadMeshBase &node)=delete
Broken copy constructor.
void operator= (const QuadMeshBase &)=delete
Broken assignment operator.
virtual ~QuadMeshBase ()
Destructor (empty)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Public Member Functions inherited from oomph::SpineMesh
virtual ~SpineMesh ()
Destructor to clean up the memory allocated to the spines.
Spine *& spine_pt (const unsigned long &i)
Return the i-th spine in the mesh.
const Spine * spine_pt (const unsigned long &i) const
Return the i-th spine in the mesh (const version)
unsigned long nspine () const
Return the number of spines in the mesh.
void add_spine_pt (Spine *const &spine_pt)
Add a spine to the mesh.
SpineNode * node_pt (const unsigned long &n)
Return a pointer to the n-th global SpineNode.
SpineNode * element_node_pt (const unsigned long &e, const unsigned &n)
unsigned long assign_global_spine_eqn_numbers (Vector< double * > &Dof_pt)
Assign spines to Spine_pt vector of element.
void describe_spine_dofs (std::ostream &out, const std::string &current_string) const
void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_spine_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Assign time stepper to spines data.
void set_consistent_pinned_spine_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
bool does_pointer_correspond_to_spine_data (double *const &parameter_pt)
void node_update (const bool &update_all_solid_nodes=false)
void dump (std::ofstream &dump_file) const
Overload the dump function so that the spine data is dumped.
void read (std::ifstream &restart_file)
Overload the read function so that the spine data is also read.
Protected Member Functions
virtual void build_channel_spine_mesh (TimeStepper *time_stepper_pt)
Protected Member Functions inherited from oomph::RectangularQuadMesh< ELEMENT >
void build_mesh (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Generic mesh construction function: contains all the hard work.
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &xmin, const double &xmax, const double &ymin, const double &ymax, const bool &periodic_in_x, const bool &build, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes
Vector< FiniteElement * > Left_element_pt
Vector of pointers to element in the left region.
Vector< FiniteElement * > Centre_element_pt
Vector of pointers to element in the centre region.
Vector< FiniteElement * > Right_element_pt
Vector of pointers to element in the right region.
unsigned Nx0
Number of elements in the left region.
unsigned Nx1
Number of elements in the centre region.
unsigned Nx2
Number of elements in the right region.
double Lx0
Length of left region.
double Lx1
Length of centre region.
double Lx2
Length of right region.
unsigned Nleft_spine
Number of spines in left region.
unsigned Ncentre_spine
Number of spines in centre region.
unsigned Nright_spine
Number of spines in right region.
GeomObject * Wall_pt
GeomObject for upper wall.
GeomObject * Straight_wall_pt
GeomObject for the straight upper wall.
Protected Attributes inherited from oomph::RectangularQuadMesh< ELEMENT >
unsigned Nx
Nx: number of elements in x-direction.
unsigned Ny
Ny: number of elements in y-direction.
unsigned Np
Np: number of (linear) points in the element.
double Xmin
Minimum value of x coordinate.
double Xmax
Maximum value of x coordinate.
double Ymin
Minimum value of y coordinate.
double Ymax
Maximum value of y coordinate.
bool Xperiodic
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Protected Attributes inherited from oomph::SpineMesh
Vector< Spine * > Spine_pt
A Spine mesh contains a Vector of pointers to spines.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Detailed Description
template<class ELEMENT>
class oomph::ChannelSpineMesh< ELEMENT >
Spine mesh class derived from standard 2D mesh. The mesh contains a StraightLine GeomObject which defines the height of the left and right regions (0,2) and another GeomObject is passed to the constructor to define the height in the central region.
Constructor & Destructor Documentation
ChannelSpineMesh() [1/2]
template<class ELEMENT > oomph::ChannelSpineMesh< ELEMENT >::ChannelSpineMesh (const unsigned & nx0, const unsigned & nx1, const unsigned & nx2, const unsigned & ny, const double & lx0, const double & lx1, const double & lx2, const double & h, GeomObject * wall_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass number of elements in x-direction in regions 0,1 and 2, number of elements in y-direction, length in x direction in regions 0,1 and 2, height mesh, pointer to the GeomObject defining the heightof the central region and pointer to timestepper (defaults to Steady timestepper)
Constructor for spine 2D mesh: Pass number of elements in x-direction, number of elements in y-direction, axial length and height of layer, and pointer to timestepper (defaults to Static timestepper).
The mesh contains a layer of spinified fluid elements (of type ELEMENT; e.g SpineElement<QCrouzeixRaviartElement<2>) and a surface layer of corresponding Spine interface elements of type INTERFACE_ELEMENT, e.g. SpineLineFluidInterfaceElement<ELEMENT> for 2D planar problems.
     : RectangularQuadMesh<ELEMENT>(nx0 + nx1 + nx2,
                                    ny,
                                    0.0,
                                    lx0 + lx1 + lx2,
                                    0.0,
                                    h,
                                    false,
                                    false,
                                    time_stepper_pt),
       Nx0(nx0),
       Nx1(nx1),
       Nx2(nx2),
       Lx0(lx0),
       Lx1(lx1),
       Lx2(lx2),
       Wall_pt(wall_pt)
   {
     // Mesh can only be built with 2D Qelements.
     MeshChecker::assert_geometric_element<QElementGeometricBase, ELEMENT>(2);
     // Mesh can only be built with spine elements
     MeshChecker::assert_geometric_element<SpineFiniteElement, ELEMENT>(2);
     // We've called the "generic" constructor for the RectangularQuadMesh
     // which doesn't do much...
     // Build the straight line object
     Straight_wall_pt = new StraightLine(h);
     // Now build the mesh:
     build_channel_spine_mesh(time_stepper_pt);
   }
References oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), and oomph::ChannelSpineMesh< ELEMENT >::Straight_wall_pt.
ChannelSpineMesh() [2/2]
template<class ELEMENT > oomph::ChannelSpineMesh< ELEMENT >::ChannelSpineMesh (const unsigned & nx0, const unsigned & nx1, const unsigned & nx2, const unsigned & ny, const double & lx0, const double & lx1, const double & lx2, const double & h, GeomObject * wall_pt, const bool & periodic_in_x, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass number of elements in x-direction in regions 0,1 and 2, number of elements in y-direction, length in x direction in regions 0,1 and 2, height mesh, pointer to the GeomObject defining the heightof the central region, a boolean flag to indicate whether or not the mesh is periodic and pointer to timestepper (defaults to Steady timestepper)
Constuctor for spine 2D mesh: Pass number of elements in x-direction, number of elements in y-direction, axial length and height of layer, a boolean flag to make the mesh periodic in the x-direction, and pointer to timestepper (defaults to Static timestepper).
The mesh contains a layer of elements (of type ELEMENT) and a surface layer of corresponding Spine interface elements (of type SpineLineFluidInterfaceElement<ELEMENT>).
     : RectangularQuadMesh<ELEMENT>(nx0 + nx1 + nx2,
                                    ny,
                                    0.0,
                                    lx0 + lx1 + lx2,
                                    0.0,
                                    h,
                                    periodic_in_x,
                                    false,
                                    time_stepper_pt),
       Nx0(nx0),
       Nx1(nx1),
       Nx2(nx2),
       Lx0(lx0),
       Lx1(lx1),
       Lx2(lx2),
       Wall_pt(wall_pt)
   {
     // Mesh can only be built with 2D Qelements.
     MeshChecker::assert_geometric_element<QElementGeometricBase, ELEMENT>(2);
     // Mesh can only be built with spine elements
     MeshChecker::assert_geometric_element<SpineFiniteElement, ELEMENT>(2);
     // We've called the "generic" constructor for the RectangularQuadMesh
     // which doesn't do much...
     // Build the straight line object
     Straight_wall_pt = new StraightLine(h);
     // Now build the mesh:
     build_channel_spine_mesh(time_stepper_pt);
   }
References oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), and oomph::ChannelSpineMesh< ELEMENT >::Straight_wall_pt.
Member Function Documentation
build_channel_spine_mesh()
template<class ELEMENT > void oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh (TimeStepper * time_stepper_pt) protected virtual
Helper function to actually build the channel-spine mesh (called from various constructors)
Helper function that actually builds the channel-spine mesh based on the parameters set in the various constructors
   {
     // Build the underlying quad mesh:
     RectangularQuadMesh<ELEMENT>::build_mesh(time_stepper_pt);
     // Read out the number of elements in the x-direction and y-direction
     // and in each of the left, centre and right regions
     unsigned n_x = this->Nx;
     unsigned n_y = this->Ny;
     unsigned n_x0 = this->Nx0;
     unsigned n_x1 = this->Nx1;
     unsigned n_x2 = this->Nx2;
     // Set up the pointers to elements in the left region
     unsigned nleft = n_x0 * n_y;
     ;
     Left_element_pt.reserve(nleft);
     unsigned ncentre = n_x1 * n_y;
     ;
     Centre_element_pt.reserve(ncentre);
     unsigned nright = n_x2 * n_y;
     ;
     Right_element_pt.reserve(nright);
     for (unsigned irow = 0; irow < n_y; irow++)
     {
       for (unsigned e = 0; e < n_x0; e++)
       {
         Left_element_pt.push_back(this->finite_element_pt(irow * n_x + e));
       }
       for (unsigned e = 0; e < n_x1; e++)
       {
         Centre_element_pt.push_back(
           this->finite_element_pt(irow * n_x + (n_x0 + e)));
       }
       for (unsigned e = 0; e < n_x2; e++)
       {
         Right_element_pt.push_back(
           this->finite_element_pt(irow * n_x + (n_x0 + n_x1 + e)));
       }
     }
 #ifdef PARANOID
     // Check that we have the correct number of elements
     if (nelement() != nleft + ncentre + nright)
     {
       throw OomphLibError("Incorrect number of element pointers!",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Allocate memory for the spines and fractions along spines
     //---------------------------------------------------------
     // Read out number of linear points in the element
     unsigned n_p = dynamic_cast<ELEMENT*>(finite_element_pt(0))->nnode_1d();
     unsigned nspine;
     // Allocate store for the spines:
     if (this->Xperiodic)
     {
       nspine = (n_p - 1) * n_x;
       Spine_pt.reserve(nspine);
       // Number of spines in each region
       // NOTE that boundary spines are in both regions
       Nleft_spine = (n_p - 1) * n_x0 + 1;
       Ncentre_spine = (n_p - 1) * n_x1 + 1;
       Nright_spine = (n_p - 1) * n_x2;
     }
     else
     {
       nspine = (n_p - 1) * n_x + 1;
       Spine_pt.reserve(nspine);
       // Number of spines in each region
       // NOTE that boundary spines are in both regions
       Nleft_spine = (n_p - 1) * n_x0 + 1;
       Ncentre_spine = (n_p - 1) * n_x1 + 1;
       Nright_spine = (n_p - 1) * n_x2 + 1;
     }
     // end Allocating memory
     // set up the vectors of geometric data & objects for building spines
     Vector<double> r_wall(2), zeta(1), s_wall(1);
     GeomObject* geometric_object_pt = 0;
     // LEFT REGION
     // ===========
     // SPINES IN LEFT REGION
     // ---------------------
     // Set up zeta increments
     double zeta_lo = 0.0;
     double dzeta = Lx0 / n_x0;
     // Initialise number of elements in previous regions:
     unsigned n_prev_elements = 0;
     // FIRST SPINE
     //-----------
     // Element 0
     // Node 0
     // Assign the new spine with unit length
     Spine* new_spine_pt = new Spine(1.0);
     new_spine_pt->spine_height_pt()->pin(0);
     Spine_pt.push_back(new_spine_pt);
     // Get pointer to node
     SpineNode* nod_pt = element_node_pt(0, 0);
     // Set the pointer to the spine
     nod_pt->spine_pt() = new_spine_pt;
     // Set the fraction
     nod_pt->fraction() = 0.0;
     // Pointer to the mesh that implements the update fct
     nod_pt->spine_mesh_pt() = this;
     // Set update fct id
     nod_pt->node_update_fct_id() = 0;
     // Provide spine with additional storage for wall coordinate
     // and wall geom object:
     {
       // Get the Lagrangian coordinate in the Lower Wall
       zeta[0] = 0.0;
       // Get the geometric object and local coordinate
       Straight_wall_pt->locate_zeta(zeta, geometric_object_pt, s_wall);
       // The local coordinate is a geometric parameter
       // This needs to be set (rather than added) because the
       // same spine may be visited more than once
       Vector<double> parameters(1, s_wall[0]);
       nod_pt->spine_pt()->set_geom_parameter(parameters);
       // Get position of wall
       Straight_wall_pt->position(s_wall, r_wall);
       // Adjust spine height
       nod_pt->spine_pt()->height() = r_wall[1];
       // The sub geom object is one (and only) geom object
       // for spine:
       Vector<GeomObject*> geom_object_pt(1);
       geom_object_pt[0] = geometric_object_pt;
       // Pass geom object(s) to spine
       nod_pt->spine_pt()->set_geom_object_pt(geom_object_pt);
     }
     // Loop vertically along the spine
     // Loop over the elements
     for (unsigned long i = 0; i < n_y; i++)
     {
       // Loop over the vertical nodes, apart from the first
       for (unsigned l1 = 1; l1 < n_p; l1++)
       {
         // Get pointer to node
         SpineNode* nod_pt = element_node_pt(i * n_x, l1 * n_p);
         // Set the pointer to the spine
         nod_pt->spine_pt() = new_spine_pt;
         // Set the fraction
         nod_pt->fraction() =
           (double(i) + double(l1) / double(n_p - 1)) / double(n_y);
         // Pointer to the mesh that implements the update fct
         nod_pt->spine_mesh_pt() = this;
         // Set update fct id
         nod_pt->node_update_fct_id() = 0;
       }
     } // end loop over elements
     // LOOP OVER OTHER SPINES
     //----------------------
     // Now loop over the elements horizontally
     for (unsigned long j = 0; j < n_x0; j++)
     {
       // Loop over the nodes in the elements horizontally, ignoring
       // the first column
       unsigned n_pmax = n_p;
       for (unsigned l2 = 1; l2 < n_pmax; l2++)
       {
         // Assign the new spine with unit height
         new_spine_pt = new Spine(1.0);
         new_spine_pt->spine_height_pt()->pin(0);
         Spine_pt.push_back(new_spine_pt);
         // Get the node
         SpineNode* nod_pt = element_node_pt(j, l2);
         // Set the pointer to spine
         nod_pt->spine_pt() = new_spine_pt;
         // Set the fraction
         nod_pt->fraction() = 0.0;
         // Pointer to the mesh that implements the update fct
         nod_pt->spine_mesh_pt() = this;
         // Set update fct id
         nod_pt->node_update_fct_id() = 0;
         {
           // Provide spine with additional storage for wall coordinate
           // and wall geom object:
           // Get the Lagrangian coordinate in the Lower Wall
           zeta[0] =
             zeta_lo + double(j) * dzeta + double(l2) * dzeta / (n_p - 1.0);
           // Get the geometric object and local coordinate
           Straight_wall_pt->locate_zeta(zeta, geometric_object_pt, s_wall);
           // The local coordinate is a geometric parameter
           // This needs to be set (rather than added) because the
           // same spine may be visited more than once
           Vector<double> parameters(1, s_wall[0]);
           nod_pt->spine_pt()->set_geom_parameter(parameters);
           // Get position of wall
           Straight_wall_pt->position(s_wall, r_wall);
           // Adjust spine height
           nod_pt->spine_pt()->height() = r_wall[1];
           // The sub geom object is one (and only) geom object
           // for spine:
           Vector<GeomObject*> geom_object_pt(1);
           geom_object_pt[0] = geometric_object_pt;
           // Pass geom object(s) to spine
           nod_pt->spine_pt()->set_geom_object_pt(geom_object_pt);
         }
         // Loop vertically along the spine
         // Loop over the elements
         for (unsigned long i = 0; i < n_y; i++)
         {
           // Loop over the vertical nodes, apart from the first
           for (unsigned l1 = 1; l1 < n_p; l1++)
           {
             // Get the node
             SpineNode* nod_pt = element_node_pt(i * n_x + j, l1 * n_p + l2);
             // Set the pointer to the spine
             nod_pt->spine_pt() = new_spine_pt;
             // Set the fraction
             nod_pt->fraction() =
               (double(i) + double(l1) / double(n_p - 1)) / double(n_y);
             // Pointer to the mesh that implements the update fct
             nod_pt->spine_mesh_pt() = this;
             // Set update fct id
             nod_pt->node_update_fct_id() = 0;
           }
         }
       }
     }
     // Increment number of previous elements
     n_prev_elements += n_x0 * n_y;
     // CENTRE REGION
     // ===========
     zeta_lo = Lx0;
     dzeta = Lx1 / n_x1;
     // SPINES IN LEFT REGION
     // ---------------------
     // LOOP OVER OTHER SPINES
     //----------------------
     // Now loop over the elements horizontally
     for (unsigned long j = n_x0; j < n_x0 + n_x1; j++)
     {
       // Loop over the nodes in the elements horizontally, ignoring
       // the first column
       unsigned n_pmax = n_p;
       for (unsigned l2 = 1; l2 < n_pmax; l2++)
       {
         // Assign the new spine with unit height
         new_spine_pt = new Spine(1.0);
         new_spine_pt->spine_height_pt()->pin(0);
         Spine_pt.push_back(new_spine_pt);
         // Get the node
         SpineNode* nod_pt = element_node_pt(j, l2);
         // Set the pointer to spine
         nod_pt->spine_pt() = new_spine_pt;
         // Set the fraction
         nod_pt->fraction() = 0.0;
         // Pointer to the mesh that implements the update fct
         nod_pt->spine_mesh_pt() = this;
         // Set update fct id
         nod_pt->node_update_fct_id() = 1;
         {
           // Provide spine with additional storage for wall coordinate
           // and wall geom object:
           // Get the Lagrangian coordinate in the Lower Wall
           zeta[0] = zeta_lo + double(j - n_x0) * dzeta +
                     double(l2) * dzeta / (n_p - 1.0);
           // Get the geometric object and local coordinate
           Wall_pt->locate_zeta(zeta, geometric_object_pt, s_wall);
           // The local coordinate is a geometric parameter
           // This needs to be set (rather than added) because the
           // same spine may be visited more than once
           Vector<double> parameters(1, s_wall[0]);
           nod_pt->spine_pt()->set_geom_parameter(parameters);
           // Get position of wall
           Wall_pt->position(s_wall, r_wall);
           // Adjust spine height
           nod_pt->spine_pt()->height() = r_wall[1];
           // The sub geom object is one (and only) geom object
           // for spine:
           Vector<GeomObject*> geom_object_pt(1);
           geom_object_pt[0] = geometric_object_pt;
           // Pass geom object(s) to spine
           nod_pt->spine_pt()->set_geom_object_pt(geom_object_pt);
         }
         // Loop vertically along the spine
         // Loop over the elements
         for (unsigned long i = 0; i < n_y; i++)
         {
           // Loop over the vertical nodes, apart from the first
           for (unsigned l1 = 1; l1 < n_p; l1++)
           {
             // Get the node
             SpineNode* nod_pt = element_node_pt(i * n_x + j, l1 * n_p + l2);
             // Set the pointer to the spine
             nod_pt->spine_pt() = new_spine_pt;
             // Set the fraction
             nod_pt->fraction() =
               (double(i) + double(l1) / double(n_p - 1)) / double(n_y);
             // Pointer to the mesh that implements the update fct
             nod_pt->spine_mesh_pt() = this;
             // Set update fct id
             nod_pt->node_update_fct_id() = 1;
           }
         }
       }
     }
     // Increment number of previous elements
     n_prev_elements += n_x1 * n_y;
     // RIGHT REGION
     // ===========
     // SPINES IN RIGHT REGION
     // ----------------------
     // Set up zeta increments
     zeta_lo = Lx0 + Lx1;
     dzeta = Lx2 / n_x2;
     // LOOP OVER OTHER SPINES
     //----------------------
     // Now loop over the elements horizontally
     for (unsigned long j = n_x0 + n_x1; j < n_x0 + n_x1 + n_x2; j++)
     {
       // Need to copy last spine in previous element over to first spine
       // in next elements, for all elements other than the first
       if (j > 0)
       {
         // For first spine, re-assign the geometric objects, since
         // we treat it as part of the right region.
         if (j == n_x0 + n_x1)
         {
           SpineNode* nod_pt = element_node_pt(j, 0);
           // Set update fct id
           nod_pt->node_update_fct_id() = 2;
           {
             // Provide spine with additional storage for wall coordinate
             // and wall geom object:
             // Get the Lagrangian coordinate in the Lower Wall
             zeta[0] = zeta_lo + double(j - n_x0 - n_x1) * dzeta;
             // Get the geometric object and local coordinate
             Straight_wall_pt->locate_zeta(zeta, geometric_object_pt, s_wall);
             // The local coordinate is a geometric parameter
             // This needs to be set (rather than added) because the
             // same spine may be visited more than once
             Vector<double> parameters(1, s_wall[0]);
             nod_pt->spine_pt()->set_geom_parameter(parameters);
             // Get position of wall
             Straight_wall_pt->position(s_wall, r_wall);
             // Adjust spine height
             nod_pt->spine_pt()->height() = r_wall[1];
             // The sub geom object is one (and only) geom object
             // for spine:
             Vector<GeomObject*> geom_object_pt(1);
             geom_object_pt[0] = geometric_object_pt;
             // Pass geom object(s) to spine
             nod_pt->spine_pt()->set_geom_object_pt(geom_object_pt);
           }
         }
       }
       // Loop over the nodes in the elements horizontally, ignoring
       // the first column
       // Last spine needs special treatment in x-periodic meshes:
       unsigned n_pmax = n_p;
       if ((this->Xperiodic) && (j == n_x - 1)) n_pmax = n_p - 1;
       for (unsigned l2 = 1; l2 < n_pmax; l2++)
       {
         // Assign the new spine with unit height
         new_spine_pt = new Spine(1.0);
         new_spine_pt->spine_height_pt()->pin(0);
         Spine_pt.push_back(new_spine_pt);
         // Get the node
         SpineNode* nod_pt = element_node_pt(j, l2);
         // Set the pointer to spine
         nod_pt->spine_pt() = new_spine_pt;
         // Set the fraction
         nod_pt->fraction() = 0.0;
         // Pointer to the mesh that implements the update fct
         nod_pt->spine_mesh_pt() = this;
         // Set update fct id
         nod_pt->node_update_fct_id() = 2;
         {
           // Provide spine with additional storage for wall coordinate
           // and wall geom object:
           // Get the Lagrangian coordinate in the Lower Wall
           zeta[0] = zeta_lo + double(j - n_x0 - n_x1) * dzeta +
                     double(l2) * dzeta / (n_p - 1.0);
           // Get the geometric object and local coordinate
           Straight_wall_pt->locate_zeta(zeta, geometric_object_pt, s_wall);
           // The local coordinate is a geometric parameter
           // This needs to be set (rather than added) because the
           // same spine may be visited more than once
           Vector<double> parameters(1, s_wall[0]);
           nod_pt->spine_pt()->set_geom_parameter(parameters);
           // Get position of wall
           Straight_wall_pt->position(s_wall, r_wall);
           // Adjust spine height
           nod_pt->spine_pt()->height() = r_wall[1];
           // The sub geom object is one (and only) geom object
           // for spine:
           Vector<GeomObject*> geom_object_pt(1);
           geom_object_pt[0] = geometric_object_pt;
           // Pass geom object(s) to spine
           nod_pt->spine_pt()->set_geom_object_pt(geom_object_pt);
         }
         // Loop vertically along the spine
         // Loop over the elements
         for (unsigned long i = 0; i < n_y; i++)
         {
           // Loop over the vertical nodes, apart from the first
           for (unsigned l1 = 1; l1 < n_p; l1++)
           {
             // Get the node
             SpineNode* nod_pt = element_node_pt(i * n_x + j, l1 * n_p + l2);
             // Set the pointer to the spine
             nod_pt->spine_pt() = new_spine_pt;
             // Set the fraction
             nod_pt->fraction() =
               (double(i) + double(l1) / double(n_p - 1)) / double(n_y);
             // Pointer to the mesh that implements the update fct
             nod_pt->spine_mesh_pt() = this;
             // Set update fct id
             nod_pt->node_update_fct_id() = 2;
           }
         }
       }
     }
     // Increment number of previous elements
     n_prev_elements += n_x2 * n_y;
     // Last spine needs special treatment for periodic meshes
     // because it's the same as the first one...
     if (this->Xperiodic)
     {
       // Last spine is the same as first one...
       Spine* final_spine_pt = Spine_pt[0];
       // Get the node
       SpineNode* nod_pt = element_node_pt((n_x - 1), (n_p - 1));
       // Set the pointer for the first node
       nod_pt->spine_pt() = final_spine_pt;
       // Set the fraction to be the same as for the nodes on the first row
       nod_pt->fraction() = element_node_pt(0, 0)->fraction();
       // Pointer to the mesh that implements the update fct
       nod_pt->spine_mesh_pt() = element_node_pt(0, 0)->spine_mesh_pt();
       // Now loop vertically along the spine
       for (unsigned i = 0; i < n_y; i++)
       {
         // Loop over the vertical nodes, apart from the first
         for (unsigned l1 = 1; l1 < n_p; l1++)
         {
           // Get the node
           SpineNode* nod_pt =
             element_node_pt(i * n_x + (n_x - 1), l1 * n_p + (n_p - 1));
           // Set the pointer to the spine
           nod_pt->spine_pt() = final_spine_pt;
           // Set the fraction to be the same as in first row
           nod_pt->fraction() = element_node_pt(i * n_x, l1 * n_p)->fraction();
           // Pointer to the mesh that implements the update fct
           nod_pt->spine_mesh_pt() =
             element_node_pt(i * n_x, l1 * n_p)->spine_mesh_pt();
         }
       }
     }
   } // end of build_channel_spine_mesh
References oomph::RectangularQuadMesh< ELEMENT >::build_mesh(), e(), oomph::SpineNode::fraction(), oomph::Spine::height(), i, j, oomph::SpineNode::node_update_fct_id(), GlobalParameters::Nx, GlobalParameters::Ny, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Data::pin(), oomph::Spine::set_geom_object_pt(), oomph::Spine::set_geom_parameter(), oomph::Spine::spine_height_pt(), oomph::SpineNode::spine_mesh_pt(), oomph::SpineNode::spine_pt(), and Eigen::zeta().
Referenced by oomph::ChannelSpineMesh< ELEMENT >::ChannelSpineMesh().
centre_element_pt()
template<class ELEMENT > FiniteElement*& oomph::ChannelSpineMesh< ELEMENT >::centre_element_pt (const unsigned long & i) inline
Access functions for pointers to the \(i \) -th element in the centre region.
     {
       return Centre_element_pt[i];
     }
References oomph::ChannelSpineMesh< ELEMENT >::Centre_element_pt, and i.
centre_spine_pt()
template<class ELEMENT > Spine*& oomph::ChannelSpineMesh< ELEMENT >::centre_spine_pt (const unsigned long & i) inline
Access function for spines in centre region.
     {
       if (i > Ncentre_spine)
       {
         throw OomphLibError("Arguemnt out of range",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       else
       {
         return Spine_pt[Nleft_spine + i];
       }
     }
References i, oomph::ChannelSpineMesh< ELEMENT >::Ncentre_spine, oomph::ChannelSpineMesh< ELEMENT >::Nleft_spine, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::SpineMesh::Spine_pt.
element_reorder()
template<class ELEMENT > void oomph::ChannelSpineMesh< ELEMENT >::element_reorder virtual
Reorder the elements so we loop over them vertically first (advantageous in "wide" domains if a frontal solver is used).
Reorder the elements, so we loop over them vertically first (advantageous in "wide" domains if a frontal solver is used).
Reimplemented from oomph::RectangularQuadMesh< ELEMENT >.
   {
     unsigned n_x = this->Nx;
     unsigned n_y = this->Ny;
     // Find out how many elements there are
     unsigned long Nelement = nelement();
     // Find out how many fluid elements there are
     unsigned long Nfluid = n_x * n_y;
     // Create a dummy array of elements
     Vector<FiniteElement*> dummy;
     // Loop over the elements in horizontal order
     for (unsigned long j = 0; j < n_x; j++)
     {
       // Loop over the elements in lower layer vertically
       for (unsigned long i = 0; i < n_y; i++)
       {
         // Push back onto the new stack
         dummy.push_back(finite_element_pt(n_x * i + j));
       }
       // Push back the line element onto the stack
       dummy.push_back(finite_element_pt(Nfluid + j));
     }
     // Now copy the reordered elements into the element_pt
     for (unsigned long e = 0; e < Nelement; e++)
     {
       Element_pt[e] = dummy[e];
     }
   } // end of element_reorder
References e(), i, j, GlobalParameters::Nx, and GlobalParameters::Ny.
left_element_pt()
template<class ELEMENT > FiniteElement*& oomph::ChannelSpineMesh< ELEMENT >::left_element_pt (const unsigned long & i) inline
Access functions for pointers to the \(i \) -th element in the left region.
     {
       return Left_element_pt[i];
     }
References i, and oomph::ChannelSpineMesh< ELEMENT >::Left_element_pt.
left_spine_pt()
template<class ELEMENT > Spine*& oomph::ChannelSpineMesh< ELEMENT >::left_spine_pt (const unsigned long & i) inline
Access function for spines in left region.
     {
 #ifdef PARNOID
       if (i > Nleft_spine)
       {
         throw OomphLibError("Arguemnt out of range",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return Spine_pt[i];
     }
References i, oomph::ChannelSpineMesh< ELEMENT >::Nleft_spine, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::SpineMesh::Spine_pt.
nbulk()
template<class ELEMENT > unsigned long oomph::ChannelSpineMesh< ELEMENT >::nbulk () const inline
Number of elements in bulk.
     {
       unsigned long Nbulk = Left_element_pt.size() + Centre_element_pt.size() +
                             Right_element_pt.size();
       return Nbulk;
     }
References oomph::ChannelSpineMesh< ELEMENT >::Centre_element_pt, oomph::ChannelSpineMesh< ELEMENT >::Left_element_pt, and oomph::ChannelSpineMesh< ELEMENT >::Right_element_pt.
ncentre()
template<class ELEMENT > unsigned long oomph::ChannelSpineMesh< ELEMENT >::ncentre () const inline
Number of elements in centre region.
     {
       return Centre_element_pt.size();
     }
References oomph::ChannelSpineMesh< ELEMENT >::Centre_element_pt.
ncentre_spine()
template<class ELEMENT > unsigned oomph::ChannelSpineMesh< ELEMENT >::ncentre_spine () inline
Access function for the number of spines in the centre region.
     {
       return Ncentre_spine;
     }
References oomph::ChannelSpineMesh< ELEMENT >::Ncentre_spine.
nleft()
template<class ELEMENT > unsigned long oomph::ChannelSpineMesh< ELEMENT >::nleft () const inline
Number of elements in left region.
     {
       return Left_element_pt.size();
     }
References oomph::ChannelSpineMesh< ELEMENT >::Left_element_pt.
nleft_spine()
template<class ELEMENT > unsigned oomph::ChannelSpineMesh< ELEMENT >::nleft_spine () inline
Access function for the number of spines in the left region.
     {
       return Nleft_spine;
     }
References oomph::ChannelSpineMesh< ELEMENT >::Nleft_spine.
nright()
template<class ELEMENT > unsigned long oomph::ChannelSpineMesh< ELEMENT >::nright () const inline
Number of elements in right region.
     {
       return Right_element_pt.size();
     }
References oomph::ChannelSpineMesh< ELEMENT >::Right_element_pt.
nright_spine()
template<class ELEMENT > unsigned oomph::ChannelSpineMesh< ELEMENT >::nright_spine () inline
Access function for the number of spines in the right region.
     {
       return Nright_spine;
     }
References oomph::ChannelSpineMesh< ELEMENT >::Nright_spine.
right_element_pt()
template<class ELEMENT > FiniteElement*& oomph::ChannelSpineMesh< ELEMENT >::right_element_pt (const unsigned long & i) inline
Access functions for pointers to the \(i \) -th element in the right region.
     {
       return Right_element_pt[i];
     }
References i, and oomph::ChannelSpineMesh< ELEMENT >::Right_element_pt.
right_spine_pt()
template<class ELEMENT > Spine*& oomph::ChannelSpineMesh< ELEMENT >::right_spine_pt (const unsigned long & i) inline
Access function for spines in right region.
     {
       if (i > Nright_spine)
       {
         throw OomphLibError("Arguemnt out of range",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       else
       {
         return Spine_pt[Nleft_spine + Ncentre_spine - 1 + i];
       }
     }
References i, oomph::ChannelSpineMesh< ELEMENT >::Ncentre_spine, oomph::ChannelSpineMesh< ELEMENT >::Nleft_spine, oomph::ChannelSpineMesh< ELEMENT >::Nright_spine, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::SpineMesh::Spine_pt.
spine_node_update()
template<class ELEMENT > virtual void oomph::ChannelSpineMesh< ELEMENT >::spine_node_update (SpineNode * spine_node_pt) inline virtual
General node update function implements pure virtual function defined in SpineMesh base class and performs specific node update actions: along vertical spines
Implements oomph::SpineMesh.
     {
       // Get spine node's fraction along the spine
       double W = spine_node_pt->fraction();
       // Get local coordinates
       Vector<double> s_wall(1);
       s_wall[0] = spine_node_pt->spine_pt()->geom_parameter(0);
       // Get position vector to wall
       Vector<double> position(2);
       spine_node_pt->spine_pt()->geom_object_pt(0)->position(s_wall, position);
       // Set the value of y
       spine_node_pt->x(1) = this->Ymin + W * position[1];
     }
References oomph::SpineNode::fraction(), oomph::Spine::geom_object_pt(), oomph::Spine::geom_parameter(), oomph::GeomObject::position(), oomph::SpineNode::spine_pt(), oomph::QuadTreeNames::W, oomph::Node::x(), and oomph::RectangularQuadMesh< ELEMENT >::Ymin.
straight_wall_pt()
template<class ELEMENT > GeomObject* oomph::ChannelSpineMesh< ELEMENT >::straight_wall_pt () inline
Access function to the GeomObject for the straight upper wall.
     {
       return Straight_wall_pt;
     }
References oomph::ChannelSpineMesh< ELEMENT >::Straight_wall_pt.
wall_pt()
template<class ELEMENT > GeomObject* oomph::ChannelSpineMesh< ELEMENT >::wall_pt () inline
Access function to the GeomObject for upper wall.
     {
       return Wall_pt;
     }
References oomph::ChannelSpineMesh< ELEMENT >::Wall_pt.
Referenced by doc_sparse_node_update().
x_spacing_function()
template<class ELEMENT > virtual double oomph::ChannelSpineMesh< ELEMENT >::x_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode) inline virtual
Return the value of the x-coordinate at the node given by the local node number (xnode, ynode) in the element (xelement,yelement). The description is in a "psudeo" two-dimensional coordinate system, so the range of xelement is [0,Nx-1], yelement is [0,Ny-1], and that of xnode and ynode is [0,Np-1]. The default is to return nodes that are equally spaced in the x coodinate.
Reimplemented from oomph::RectangularQuadMesh< ELEMENT >.
     {
       // Calculate the values of equal increments in nodal values in left region
       double xstep1 = Lx0 / ((this->Np - 1) * Nx0);
       // Calculate the values of equal increments in nodal values in centre
       // region
       double xstep2 = Lx1 / ((this->Np - 1) * Nx1);
       // Calculate the values of equal increments in nodal values in right
       // region
       double xstep3 = Lx2 / ((this->Np - 1) * Nx2);
       // left region
       if (xelement < Nx0)
       {
         // Return the appropriate value
         return (this->Xmin + xstep1 * ((this->Np - 1) * xelement + xnode));
       }
       // centre region
       else if (xelement < Nx0 + Nx1)
       {
         // Return the appropriate value
         return (Lx0 + xstep2 * ((this->Np - 1) * (xelement - Nx0) + xnode));
       }
       // right region
       else if (xelement < Nx0 + Nx1 + Nx2)
       {
         // Return the appropriate value
         return (Lx0 + Lx1 +
                 xstep3 * ((this->Np - 1) * (xelement - Nx0 - Nx1) + xnode));
       }
       else
       {
         throw OomphLibError("Should not have got here",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       // Dummy return to keep compiler from barking
       return 0.0;
     }
References oomph::ChannelSpineMesh< ELEMENT >::Lx0, oomph::ChannelSpineMesh< ELEMENT >::Lx1, oomph::ChannelSpineMesh< ELEMENT >::Lx2, oomph::RectangularQuadMesh< ELEMENT >::Np, oomph::ChannelSpineMesh< ELEMENT >::Nx0, oomph::ChannelSpineMesh< ELEMENT >::Nx1, oomph::ChannelSpineMesh< ELEMENT >::Nx2, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::RectangularQuadMesh< ELEMENT >::Xmin.
Member Data Documentation
Centre_element_pt
template<class ELEMENT > Vector<FiniteElement*> oomph::ChannelSpineMesh< ELEMENT >::Centre_element_pt protected
Vector of pointers to element in the centre region.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::centre_element_pt(), oomph::ChannelSpineMesh< ELEMENT >::nbulk(), and oomph::ChannelSpineMesh< ELEMENT >::ncentre().
Left_element_pt
template<class ELEMENT > Vector<FiniteElement*> oomph::ChannelSpineMesh< ELEMENT >::Left_element_pt protected
Vector of pointers to element in the left region.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::left_element_pt(), oomph::ChannelSpineMesh< ELEMENT >::nbulk(), and oomph::ChannelSpineMesh< ELEMENT >::nleft().
Lx0
template<class ELEMENT > double oomph::ChannelSpineMesh< ELEMENT >::Lx0 protected
Length of left region.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::x_spacing_function().
Lx1
template<class ELEMENT > double oomph::ChannelSpineMesh< ELEMENT >::Lx1 protected
Length of centre region.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::x_spacing_function().
Lx2
template<class ELEMENT > double oomph::ChannelSpineMesh< ELEMENT >::Lx2 protected
Length of right region.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::x_spacing_function().
Ncentre_spine
template<class ELEMENT > unsigned oomph::ChannelSpineMesh< ELEMENT >::Ncentre_spine protected
Number of spines in centre region.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::centre_spine_pt(), oomph::ChannelSpineMesh< ELEMENT >::ncentre_spine(), and oomph::ChannelSpineMesh< ELEMENT >::right_spine_pt().
Nleft_spine
template<class ELEMENT > unsigned oomph::ChannelSpineMesh< ELEMENT >::Nleft_spine protected
Number of spines in left region.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::centre_spine_pt(), oomph::ChannelSpineMesh< ELEMENT >::left_spine_pt(), oomph::ChannelSpineMesh< ELEMENT >::nleft_spine(), and oomph::ChannelSpineMesh< ELEMENT >::right_spine_pt().
Nright_spine
template<class ELEMENT > unsigned oomph::ChannelSpineMesh< ELEMENT >::Nright_spine protected
Number of spines in right region.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::nright_spine(), and oomph::ChannelSpineMesh< ELEMENT >::right_spine_pt().
Nx0
template<class ELEMENT > unsigned oomph::ChannelSpineMesh< ELEMENT >::Nx0 protected
Number of elements in the left region.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::x_spacing_function().
Nx1
template<class ELEMENT > unsigned oomph::ChannelSpineMesh< ELEMENT >::Nx1 protected
Number of elements in the centre region.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::x_spacing_function().
Nx2
template<class ELEMENT > unsigned oomph::ChannelSpineMesh< ELEMENT >::Nx2 protected
Number of elements in the right region.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::x_spacing_function().
Right_element_pt
template<class ELEMENT > Vector<FiniteElement*> oomph::ChannelSpineMesh< ELEMENT >::Right_element_pt protected
Vector of pointers to element in the right region.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::nbulk(), oomph::ChannelSpineMesh< ELEMENT >::nright(), and oomph::ChannelSpineMesh< ELEMENT >::right_element_pt().
Straight_wall_pt
template<class ELEMENT > GeomObject* oomph::ChannelSpineMesh< ELEMENT >::Straight_wall_pt protected
GeomObject for the straight upper wall.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::ChannelSpineMesh(), and oomph::ChannelSpineMesh< ELEMENT >::straight_wall_pt().
Wall_pt
template<class ELEMENT > GeomObject* oomph::ChannelSpineMesh< ELEMENT >::Wall_pt protected
GeomObject for upper wall.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::wall_pt().
The documentation for this class was generated from the following files:
channel_spine_mesh.template.h
channel_spine_mesh.template.cc