MercuryDPM: oomph::TetMeshVertex Class Reference
oomph::TetMeshVertex Class Reference
#include <tet_mesh.h>
Public Member Functions
TetMeshVertex (const Vector< double > &x)
Constructor: Pass coordinates (length 3!)
TetMeshVertex (Node *const &node_pt)
void set_zeta_in_geom_object (const Vector< double > &zeta)
Set intrinisic coordinates in GeomObject.
Vector< double > zeta_in_geom_object () const
double x (const unsigned &i) const
i-th coordinate
unsigned one_based_boundary_id () const
First (of possibly multiple) one-based boundary id.
Private Member Functions
void set_one_based_boundary_id (const unsigned &id)
Set of (one-based!) boundary IDs this vertex lives on.
Private Attributes
Vector< double > X
Coordinate vector.
std::set< unsigned > One_based_boundary_id
Set of (one-based!) boundary IDs this vertex lives on.
Vector< double > Zeta_in_geom_object
Friends
class TetMeshFacet
Only friends can set boundary ID – the facet is my only friend!
Detailed Description
Vertex for Tet mesh generation. Can lie on multiple boundaries (identified via one-based enumeration!) and can have intrinisic coordinates in a DiskLikeGeomObjectWithBoundaries.
Constructor & Destructor Documentation
TetMeshVertex() [1/2]
oomph::TetMeshVertex::TetMeshVertex (const Vector< double > & x) inline
Constructor: Pass coordinates (length 3!)
                                            : X(x)
     {
 #ifdef PARANOID
       if (X.size() != 3)
       {
         std::ostringstream error_stream;
         error_stream << "TetMeshVertex should only be used in 3D!\n"
                      << "Your Vector of coordinates, contains data for "
                      << x.size() << "-dimensional coordinates." << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, x(), and X.
TetMeshVertex() [2/2]
oomph::TetMeshVertex::TetMeshVertex (Node *const & node_pt) inline
     {
       const unsigned n_dim = node_pt->ndim();
 #ifdef PARANOID
       if (n_dim != 3)
       {
         std::ostringstream error_stream;
         error_stream << "TetMeshVertex should only be used in 3D!\n"
                      << "Your Node contains data for " << n_dim
                      << "-dimensional coordinates." << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Copy over the positions from the node
       X.resize(n_dim);
       for (unsigned i = 0; i < n_dim; ++i)
       {
         X[i] = node_pt->x(i);
       }
     }
References i, oomph::Node::ndim(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Node::x(), and X.
Member Function Documentation
one_based_boundary_id()
unsigned oomph::TetMeshVertex::one_based_boundary_id () const inline
First (of possibly multiple) one-based boundary id.
     {
       if (One_based_boundary_id.size() == 0)
       {
         return 0;
       }
       return *(One_based_boundary_id.begin());
     }
References One_based_boundary_id.
set_one_based_boundary_id()
void oomph::TetMeshVertex::set_one_based_boundary_id (const unsigned & id) inline private
Set of (one-based!) boundary IDs this vertex lives on.
     {
       One_based_boundary_id.insert(id);
     }
References One_based_boundary_id.
Referenced by oomph::TetMeshFacet::set_one_based_boundary_id(), and oomph::TetMeshFacet::set_vertex_pt().
set_zeta_in_geom_object()
void oomph::TetMeshVertex::set_zeta_in_geom_object (const Vector< double > & zeta) inline
Set intrinisic coordinates in GeomObject.
     {
 #ifdef PARANOID
       if (zeta.size() != 2)
       {
         std::ostringstream error_stream;
         error_stream
           << "TetMeshVertex should only be used in 3D!\n"
           << "Your Vector of intrinisic coordinates, contains data for "
           << zeta.size() << "-dimensional coordinates but should be 2!"
           << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       Zeta_in_geom_object = zeta;
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, Eigen::zeta(), and Zeta_in_geom_object.
x()
double oomph::TetMeshVertex::x (const unsigned & i) const inline
i-th coordinate
     {
       return X[i];
     }
References i, and X.
Referenced by oomph::TetMeshBase::setup_boundary_coordinates(), TetMeshVertex(), and oomph::GmshTetScaffoldMesh::write_geo_file().
zeta_in_geom_object()
Vector<double> oomph::TetMeshVertex::zeta_in_geom_object () const inline
Get intrinisic coordinates in GeomObject (returns zero sized vector if no such coordinates have been specified)
     {
       return Zeta_in_geom_object;
     }
References Zeta_in_geom_object.
Referenced by oomph::DiskTetMeshFacetedSurface::boundary_zeta01(), and oomph::TetMeshBase::snap_nodes_onto_geometric_objects().
Friends And Related Function Documentation
TetMeshFacet
friend class TetMeshFacet friend
Only friends can set boundary ID – the facet is my only friend!
Member Data Documentation
One_based_boundary_id
std::set<unsigned> oomph::TetMeshVertex::One_based_boundary_id private
Set of (one-based!) boundary IDs this vertex lives on.
Referenced by one_based_boundary_id(), and set_one_based_boundary_id().
X
Vector<double> oomph::TetMeshVertex::X private
Coordinate vector.
Referenced by TetMeshVertex(), and x().
Zeta_in_geom_object
Vector<double> oomph::TetMeshVertex::Zeta_in_geom_object private
Intrinisic coordinates in GeomObject (zero sized if there isn't one.
Referenced by set_zeta_in_geom_object(), and zeta_in_geom_object().
The documentation for this class was generated from the following file:
tet_mesh.h