MercuryDPM: oomph::ElementWithMortaringStatusAtNodes< ELEMENT > Class Template Reference
oomph::ElementWithMortaringStatusAtNodes< ELEMENT > Class Template Reference
#include <element_with_mortaring_status_at_nodes.h>
Public Member Functions
ElementWithMortaringStatusAtNodes ()
void set_output_mortared_status ()
void set_do_not_output_mortared_status ()
unsigned required_nvalue (const unsigned &n) const override
unsigned mortared_dof_index (const unsigned &n) const
double mortared_status (const unsigned &n) const
void set_mortared (const unsigned &n, const double &mortared_status=1.0)
void set_not_mortared (const unsigned &n, const double &mortared_status=0.0)
void pin_mortared_status_of_all_nodes ()
unsigned ncont_interpolated_values () const
double get_interpolated_mortared_status (const Vector< double > &s)
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
void output (std::ostream &outfile, const unsigned &nplot)
void further_build ()
Protected Member Functions
const double get_output_mortared_status () const
Private Attributes
bool Output_Mortared_Status
Constructor & Destructor Documentation
ElementWithMortaringStatusAtNodes()
template<class ELEMENT > oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::ElementWithMortaringStatusAtNodes () inline
                                      : ELEMENT(),
                                        Output_Mortared_Status(false) {}
Member Function Documentation
further_build()
template<class ELEMENT > void oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::further_build () inline
  {
   ELEMENT::further_build();
   Output_Mortared_Status = dynamic_cast<ElementWithMortaringStatusAtNodes<ELEMENT>*>(this->father_element_pt())->get_output_mortared_status();
  }
References oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::get_output_mortared_status(), and oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::Output_Mortared_Status.
get_interpolated_mortared_status()
template<class ELEMENT > double oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::get_interpolated_mortared_status (const Vector< double > & s) inline
  {
   double value = 0.0;
   // Find out how many nodes there are
   unsigned n_node = this->nnode();
   // Shape functions
   Shape psif(n_node);
   this->shape(s, psif);
   for (unsigned l = 0; l < n_node; l++)
   {
    value += this->mortared_status(l) * psif[l];
   }
   return value;
  }
References oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::mortared_status(), oomph::OneDimLagrange::shape(), and Eigen::value.
Referenced by oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::get_interpolated_values(), and oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::output().
get_interpolated_values() [1/2]
template<class ELEMENT > void oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) inline
  {
   ELEMENT::get_interpolated_values(t, s,values);
   values.push_back(get_interpolated_mortared_status(s));
  }
References oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::get_interpolated_mortared_status(), s, and plotPSD::t.
get_interpolated_values() [2/2]
template<class ELEMENT > void oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) inline
  {
   ELEMENT::get_interpolated_values(s,values);
   values.push_back(get_interpolated_mortared_status(s));
  }
References oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::get_interpolated_mortared_status(), and s.
get_output_mortared_status()
template<class ELEMENT > const double oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::get_output_mortared_status () const inline protected
  {
   return Output_Mortared_Status;
  }
References oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::Output_Mortared_Status.
Referenced by oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::further_build().
mortared_dof_index()
template<class ELEMENT > unsigned oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::mortared_dof_index (const unsigned & n) const inline
  {
   return required_nvalue(n) - 1;
  }
References n, and oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::required_nvalue().
Referenced by oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::mortared_status(), oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::pin_mortared_status_of_all_nodes(), oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::set_mortared(), and oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::set_not_mortared().
mortared_status()
template<class ELEMENT > double oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::mortared_status (const unsigned & n) const inline
  {
   return this->node_pt(n)->value(mortared_dof_index(n));
  }
References oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::mortared_dof_index(), and n.
Referenced by oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::get_interpolated_mortared_status(), oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::set_mortared(), and oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::set_not_mortared().
ncont_interpolated_values()
template<class ELEMENT > unsigned oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::ncont_interpolated_values () const inline
  {
   return ELEMENT::ncont_interpolated_values() + 1;
  }
output()
template<class ELEMENT > void oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) inline
  {
   if(Output_Mortared_Status)
   {
    // vector of local coordinates
    Vector<double> s(this->dim());
    // Tecplot header info
    outfile << this->tecplot_zone_string(nplot);
    // Loop over plot points
    unsigned num_plot_points = this->nplot_points(nplot);
    for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
    {
     // Get local coordinates of plot point
     this->get_s_plot(iplot, nplot, s);
     for (unsigned i = 0; i < this->dim(); i++)
     {
      outfile << this->interpolated_x(s, i) << " ";
     }
     outfile << get_interpolated_mortared_status(s);
     outfile << std::endl;
    }
    outfile << std::endl;
    // Write tecplot footer (e.g. FE connectivity lists)
    this->write_tecplot_zone_footer(outfile, nplot);
   }
   else
   {
    ELEMENT::output(outfile, nplot);
   }
  }
References oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::get_interpolated_mortared_status(), i, output(), oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::Output_Mortared_Status, and s.
pin_mortared_status_of_all_nodes()
template<class ELEMENT > void oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::pin_mortared_status_of_all_nodes () inline
  {
   for(unsigned n=0; n<this->nnode(); n++)
   {
    this->node_pt(n)->pin(mortared_dof_index(n));
   }
  }
References oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::mortared_dof_index(), and n.
required_nvalue()
template<class ELEMENT > unsigned oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::required_nvalue (const unsigned & n) const inline override
  {
   return ELEMENT::required_nvalue(n) + 1;
  }
References n.
Referenced by oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::mortared_dof_index().
set_do_not_output_mortared_status()
template<class ELEMENT > void oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::set_do_not_output_mortared_status () inline
  {
   Output_Mortared_Status = false;
  }
References oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::Output_Mortared_Status.
set_mortared()
template<class ELEMENT > void oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::set_mortared (const unsigned & n, const double & mortared_status = 1.0) inline
  {
   return this->node_pt(n)->set_value(mortared_dof_index(n), mortared_status);
  }
References oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::mortared_dof_index(), oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::mortared_status(), and n.
set_not_mortared()
template<class ELEMENT > void oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::set_not_mortared (const unsigned & n, const double & mortared_status = 0.0) inline
  {
   return this->node_pt(n)->set_value(mortared_dof_index(n), mortared_status);
  }
References oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::mortared_dof_index(), oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::mortared_status(), and n.
set_output_mortared_status()
template<class ELEMENT > void oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::set_output_mortared_status () inline
  {
   Output_Mortared_Status = true;
  }
References oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::Output_Mortared_Status.
Member Data Documentation
Output_Mortared_Status
template<class ELEMENT > bool oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::Output_Mortared_Status private
Referenced by oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::further_build(), oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::get_output_mortared_status(), oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::output(), oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::set_do_not_output_mortared_status(), and oomph::ElementWithMortaringStatusAtNodes< ELEMENT >::set_output_mortared_status().
The documentation for this class was generated from the following file:
element_with_mortaring_status_at_nodes.h