MercuryDPM: CGCoordinates::Base_XY_XZ_YZ Class Reference
CGCoordinates::Base_XY_XZ_YZ Class Reference
Contains common member functions of the XY, XZ, and YZ classes.
#include <Base_XY_XZ_YZ.h>
Static Public Member Functions
static Mdouble getGaussPrefactor (Mdouble width, Mdouble cutoff)
Computes the prefactor of the Gauss CGFunction, which is dependent on the number of non-averaged dimensions.
static Mdouble getGaussIntegralPrefactor (Mdouble distance, Mdouble width, Mdouble cutoff)
Computes the prefactor of the Gauss line integral, which is dependent on the number of non-averaged dimensions.
static void normalisePolynomialCoefficients (std::vector< Mdouble > &coefficients, Mdouble cutoff)
Normalises the coefficients of Polynomial CGFunction such that the integral over all non-averaged dimensions is unity.
static const unsigned countVariables ()
Static Public Member Functions inherited from CGCoordinates::BaseCoordinates
static Mdouble getDomainVolume (const Vec3D &min, const Vec3D &max)
Additional Inherited Members
Public Member Functions inherited from CGCoordinates::BaseCoordinates
virtual Mdouble getWeight ()
Detailed Description
Contains common member functions of the XY, XZ, and YZ classes.
As XY, XZ, and YZ share a lot of functionality, the shared functions are stored in this common base class.
Member Function Documentation
countVariables()
const unsigned Base_XY_XZ_YZ::countVariables () static
returns the number of variables (in this case two)
 {
     return 2;
 }
getGaussIntegralPrefactor()
Mdouble Base_XY_XZ_YZ::getGaussIntegralPrefactor (Mdouble distance, Mdouble width, Mdouble cutoff) static
Computes the prefactor of the Gauss line integral, which is dependent on the number of non-averaged dimensions.
 {
     Mdouble widthSqrt2 = width * constants::sqrt_2;
     Mdouble a = -cutoff;
     Mdouble b = cutoff + distance;
     //1D prefactor
     Mdouble prefactor_ = 1.0 / (widthSqrt2 * constants::sqrt_pi);
     prefactor_ /= erf(cutoff / (widthSqrt2));
     return prefactor_ * 0.5 / (
             +erf(b / widthSqrt2) * b
             + widthSqrt2 / constants::sqrt_pi * exp(-mathsFunc::square(b / widthSqrt2))
             - erf(a / widthSqrt2) * a
             - widthSqrt2 / constants::sqrt_pi * exp(-mathsFunc::square(a / widthSqrt2))
     );
 }
References a, b, Eigen::bfloat16_impl::exp(), constants::sqrt_2, constants::sqrt_pi, and mathsFunc::square().
getGaussPrefactor()
Mdouble Base_XY_XZ_YZ::getGaussPrefactor (Mdouble width, Mdouble cutoff) static
Computes the prefactor of the Gauss CGFunction, which is dependent on the number of non-averaged dimensions.
 {
     //Wolfram alpha: integrate(x*exp(-x^2/(2w^2)),{x,0,c})/integrate(x*exp(-x^2/(2w^2)),{x,0,inf})=1-e^(-c^2/(2 w^2))
     Mdouble prefactor = 1.0 / (constants::sqrt_2 * constants::sqrt_pi * width);
     return mathsFunc::square(prefactor) / (1.0 - exp(-0.5 * mathsFunc::square(cutoff / width)));
 }
References Eigen::bfloat16_impl::exp(), constants::sqrt_2, constants::sqrt_pi, and mathsFunc::square().
normalisePolynomialCoefficients()
void Base_XY_XZ_YZ::normalisePolynomialCoefficients (std::vector< Mdouble > & coefficients, Mdouble cutoff) static
Normalises the coefficients of Polynomial CGFunction such that the integral over all non-averaged dimensions is unity.
The volume is computed as
\[volume=\int_0^1\sum_{i=1}^n c_i r^i 2 pi r dr = 2 pi \sum_{i=1}^n c_i/(i+2) \]
with 2 pi r the circumference of a circle.
 {
     Mdouble volume = 0.0;
     for (std::size_t i = 0; i < coefficients.size(); i++)
         volume += coefficients[i] / static_cast<Mdouble>(i + 2);
     volume *= 2.0 * constants::pi * mathsFunc::square(cutoff);
     for (double& coefficient : coefficients)
         coefficient /= volume;
 }
References i, constants::pi, and mathsFunc::square().
The documentation for this class was generated from the following files:
Base_XY_XZ_YZ.h
Base_XY_XZ_YZ.cc