MercuryDPM: octree_test.cc File Reference
octree_test.cc File Reference
#include "generic.h"
#include "poisson.h"
#include "meshes/simple_cubic_mesh.h"
Classes
class oomph::Rotateable< ELEMENT >
class oomph::RotatableRefineableCubicMesh< ELEMENT >
class TestPoissonProblem< ELEMENT >
Poisson problem on rotatable, refineable cubic brick mesh.
Namespaces
oomph
DRAIG: Change all instances of (SPATIAL_DIM) to (DIM-1).
TanhSolnForPoisson
Namespace for exact solution for Poisson equation with "sharp step".
Functions
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, double &u)
Exact solution as a scalar.
void TanhSolnForPoisson::get_source (const Vector< double > &x, double &source)
Source function to make it an exact solution.
int main (int argc, char *argv[])
Driver code.
Function Documentation
main()
int main (int argc , char * argv[])
Driver code.
 {
  // Save command line arguments
  CommandLineArgs::setup(argc,argv);
  // Write header to trace file and close (also wipes any existing ones
  ofstream trace_file("trace.dat");
  trace_file << "rotation_index rotated_element success_flag" << std::endl;
  trace_file.close();
  // Create label for output
  //------------------------
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory("RESLT");
  // Step number
  doc_info.number()=0;
  //Set up the problems and doc
  //---------------------------
  // Loop over rotations
  for(unsigned r=1;r<24;r++)
   {
    // Loop over elements that are rotated
    for(unsigned rotated_element=0;rotated_element<27;rotated_element++)
     {
      std::cout << "Case: r, rotated_element"
                << r << " " << rotated_element << std::endl;
     //Create the problem with rotation r for element rotated_element
     TestPoissonProblem<Rotateable<RefineableQPoissonElement<3,2> > >
      problem(r,rotated_element,&TanhSolnForPoisson::get_source);
     //Output the solution
     problem.doc_solution(doc_info);
     doc_info.number()++;
     // We're not interested in the solution...
 //    problem.newton_solve();
    }
   }
 }
References TanhSolnForPoisson::get_source(), oomph::DocInfo::number(), problem, UniformPSDSelfTest::r, oomph::DocInfo::set_directory(), and Flag_definition::setup().