MercuryDPM: SinterLinNormalSpecies Class Reference
SinterLinNormalSpecies Class Reference
SinterLinNormalSpecies contains the parameters used to describe a plastic-cohesive normal force (Stefan Ludings plastic-cohesive force model) based on three different sintering mechanisms.
#include <SinterLinNormalSpecies.h>
Public Types
typedef SinterLinInteraction InteractionType
The correct Interaction type for this FrictionForceSpecies.
Public Member Functions
SinterLinNormalSpecies ()
The default constructor.
SinterLinNormalSpecies (const SinterLinNormalSpecies &p)
The default copy constructor.
~SinterLinNormalSpecies ()
The default destructor.
void read (std::istream &is)
Reads the species properties from an input stream.
void write (std::ostream &os) const
Writes the species properties to an output stream.
std::string getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
void mix (SinterLinNormalSpecies *S, SinterLinNormalSpecies *T)
creates default values for mixed species
void setCollisionTimeAndRestitutionCoefficient (Mdouble tc, Mdouble eps, Mdouble mass)
void setStiffnessAndRestitutionCoefficient (Mdouble k_, Mdouble eps, Mdouble mass)
Sets k, disp such that it matches a given tc and eps for a collision of two copies of P.
void setRestitutionCoefficient (double eps, Mdouble mass)
Sets disp to obtain a restitution coefficient eps for a collision of two particles of mass m.
Mdouble getCollisionTime (Mdouble mass) const
Calculates collision time for two copies of a particle of given disp, k, mass.
Mdouble getRestitutionCoefficient (Mdouble mass) const
Calculates restitution coefficient for two copies of given disp, k, mass.
void setPlasticParameters (Mdouble loadingStiffness, Mdouble unloadingStiffnessMax, Mdouble cohesionStiffness, Mdouble penetrationDepthMax)
Sets all parameters of the linear plastic-viscoelastic normal force at once.
Mdouble getLoadingStiffness () const
Returns the loading stiffness of the linear plastic-viscoelastic normal force.
Mdouble getUnloadingStiffnessMax () const
Returns the maximum unloading stiffness of the linear plastic-viscoelastic normal force.
Mdouble getCohesionStiffness () const
Returns the cohesive stiffness of the linear plastic-viscoelastic normal force.
Mdouble getPenetrationDepthMax () const
Returns the maximum penetration depth of the linear plastic-viscoelastic normal force.
void setLoadingStiffness (Mdouble loadingStiffness)
Sets the loading stiffness of the linear plastic-viscoelastic normal force.
void setUnloadingStiffnessMax (Mdouble unloadingStiffnessMax)
Sets the maximum unloading stiffness of the linear plastic-viscoelastic normal force.
void setCohesionStiffness (Mdouble cohesionStiffness)
Sets the cohesive stiffness of the linear plastic-viscoelastic normal force.
void setPenetrationDepthMax (Mdouble penetrationDepthMax)
Sets the maximum penetration depth of the linear plastic-viscoelastic normal force.
void setDissipation (Mdouble dissipation)
Sets the linear dissipation coefficient of the linear plastic-viscoelastic normal force.
MERCURYDPM_DEPRECATED void setLoadingStiffnessAndDissipation (helpers::KAndDisp new_)
Allows the spring and dissipation constants to be changed simultaneously.
Mdouble computeTimeStep (Mdouble mass)
Returns the optimal time step to resolve a collision of two particles of a given mass.
Mdouble getDissipation () const
Allows the normal dissipation to be accessed.
void setSinterAdhesion (Mdouble sinterAdhesion)
Sets sinterAdhesion_.
Mdouble getSinterAdhesion () const
Accesses sinterAdhesion_.
void setSinterRate (Mdouble sinterRate)
Sets sinterRate_.
Mdouble getSinterRate () const
Accesses sinterRate_.
void setComplianceZero (Mdouble complianceZero)
sets the instantaneous compliance (compliance zero)
Mdouble getComplianceZero () const
Accesses the instantaneous compliance (compliance zero)
void setSurfTension (Mdouble complianceZero)
sets the surface tension.
Mdouble getSurfTension () const
accesses the surface tension.
void setFluidity (Mdouble complianceOne)
sets the fluidity (inverse of viscosity).
Mdouble getFluidity () const
accesses the fluidity (inverse of viscosity).
void setSeparationDis (Mdouble separationDis)
sets the critical separation distance. This mimics inter-surface forces.
Mdouble getSeparationDis () const
accesses the critical separation distance. This mimics inter-surface forces.
void setSinterType (SINTER_APPROACH sinterType)
sets the sintering approach selected.
SINTER_APPROACH getSinterType () const
Public Member Functions inherited from BaseNormalForce
BaseNormalForce ()
BaseNormalForce (const BaseNormalForce &p)
bool getConstantRestitution () const
void setConstantRestitution (bool constantRestitution)
virtual void actionsAfterTimeStep (BaseParticle *particle) const
Public Member Functions inherited from BaseForce
BaseSpecies * getBaseSpecies () const
void setBaseSpecies (BaseSpecies *baseSpecies)
Private Attributes
Mdouble loadingStiffness_
(normal) spring constant (k_1)
Mdouble unloadingStiffnessMax_
the maximum elastic constant (k_2^max) for plastic deformations
Mdouble cohesionStiffness_
the adhesive spring constant (k^c) for plastic deformations
Mdouble penetrationDepthMax_
the depth (relative to the normalized radius) at which k_2^max is used (phi_f)
Mdouble dissipation_
linear dissipation coefficient
Mdouble sinterAdhesion_
Mdouble sinterRate_
Mdouble complianceZero_
Mdouble surfTension_
Mdouble fluidity
Mdouble separationDis_
SINTER_APPROACH sinterType_
Type of sintering.
Detailed Description
SinterLinNormalSpecies contains the parameters used to describe a plastic-cohesive normal force (Stefan Ludings plastic-cohesive force model) based on three different sintering mechanisms.
Ref: Visco-elastic sintering kinetics in virgin and aged polymer powders. Powder Technology, 2020.
Member Typedef Documentation
InteractionType
typedef SinterLinInteraction SinterLinNormalSpecies::InteractionType
The correct Interaction type for this FrictionForceSpecies.
Constructor & Destructor Documentation
SinterLinNormalSpecies() [1/2]
SinterLinNormalSpecies::SinterLinNormalSpecies ()
The default constructor.
         : BaseNormalForce()
 {
     loadingStiffness_ = 0.0;
     unloadingStiffnessMax_ = 0.0;
     cohesionStiffness_ = 0.0;
     penetrationDepthMax_ = 0.0;
     dissipation_ = 0.0;
     sinterAdhesion_ = 0.0;
     sinterRate_ = 0.0;
     complianceZero_ = 0.0;
     surfTension_ = 0.0;
     fluidity = 0.0;
     separationDis_ = 0.0;
     sinterType_ = SINTER_APPROACH::FRENKEL;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"SinterLinNormalSpecies::SinterLinNormalSpecies() finished"<<std::endl;
 #endif
 }
References cohesionStiffness_, complianceZero_, dissipation_, fluidity, FRENKEL, loadingStiffness_, penetrationDepthMax_, separationDis_, sinterAdhesion_, sinterRate_, sinterType_, surfTension_, and unloadingStiffnessMax_.
SinterLinNormalSpecies() [2/2]
SinterLinNormalSpecies::SinterLinNormalSpecies (const SinterLinNormalSpecies & p)
The default copy constructor.
Parameters
[in] SinterLinNormalSpecies the species that is copied
         : BaseNormalForce(p)
 {
     loadingStiffness_ = p.loadingStiffness_;
     unloadingStiffnessMax_ = p.unloadingStiffnessMax_;
     cohesionStiffness_ = p.cohesionStiffness_;
     penetrationDepthMax_ = p.penetrationDepthMax_;
     dissipation_ = p.dissipation_;
     sinterAdhesion_ = p.sinterAdhesion_;
     sinterRate_ = p.sinterRate_;
     complianceZero_ = p.complianceZero_;
     surfTension_ = p.surfTension_;
     fluidity = p.fluidity;
     separationDis_ = p.separationDis_;
     sinterType_ = p.sinterType_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"SinterLinNormalSpecies::SinterLinNormalSpecies(const SinterLinNormalSpecies &p) finished"<<std::endl;
 #endif
 }
References cohesionStiffness_, complianceZero_, dissipation_, fluidity, loadingStiffness_, p, penetrationDepthMax_, separationDis_, sinterAdhesion_, sinterRate_, sinterType_, surfTension_, and unloadingStiffnessMax_.
~SinterLinNormalSpecies()
SinterLinNormalSpecies::~SinterLinNormalSpecies ()
The default destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"SinterNormalSpecies::~SinterNormalSpecies() finished"<<std::endl;
 #endif
 }
Member Function Documentation
computeTimeStep()
Mdouble SinterLinNormalSpecies::computeTimeStep (Mdouble mass)
Returns the optimal time step to resolve a collision of two particles of a given mass.
Calculates collision time for stiffest spring constant, divides by 50
Parameters
[in] mass the optimal time step is computed to resolve a collision of two particles of this mass.
 {
     if (getConstantRestitution()) mass = 1;
     return 0.02 * constants::pi /
            std::sqrt(unloadingStiffnessMax_ / (.5 * mass) - mathsFunc::square(dissipation_ / mass));
 }
References dissipation_, BaseNormalForce::getConstantRestitution(), constants::pi, sqrt(), mathsFunc::square(), and unloadingStiffnessMax_.
getBaseName()
std::string SinterLinNormalSpecies::getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
Returns
a string containing the name of the species (minus the word "Species")
 {
     return "SinterLin";
 }
getCohesionStiffness()
Mdouble SinterLinNormalSpecies::getCohesionStiffness () const
Returns the cohesive stiffness of the linear plastic-viscoelastic normal force.
Returns
the cohesive stiffness of the linear plastic-viscoelastic normal force.
 {
     return cohesionStiffness_;
 }
References cohesionStiffness_.
Referenced by SinterLinInteraction::computeNormalForce().
getCollisionTime()
Mdouble SinterLinNormalSpecies::getCollisionTime (Mdouble mass) const
Calculates collision time for two copies of a particle of given disp, k, mass.
 {
     if (mass <= 0)
     {
         std::cerr << "Error in getCollisionTime(" << mass
                   << ") mass is not set or has an unexpected value, (getCollisionTime(" << mass << "))" << std::endl;
         exit(-1);
     }
     if (loadingStiffness_ <= 0)
     {
         std::cerr << "Error in getCollisionTime(" << mass << ") stiffness=" << loadingStiffness_
                   << " is not set or has an unexpected value, (getCollisionTime(" << mass << "), with stiffness="
                   << loadingStiffness_ << ")" << std::endl;
         exit(-1);
     }
     if (dissipation_ < 0)
     {
         std::cerr << "Error in getCollisionTime(" << mass << ") dissipation=" << dissipation_
                   << " is not set or has an unexpected value, (getCollisionTime(" << mass << "), with dissipation="
                   << dissipation_ << ")" << std::endl;
         exit(-1);
     }
     Mdouble tosqrt = loadingStiffness_ / (.5 * mass) - mathsFunc::square(dissipation_ / mass);
     if (tosqrt <= -1e-8 * loadingStiffness_ / (.5 * mass))
     {
         std::cerr << "Error in getCollisionTime(" << mass
                   << ") values for mass, stiffness and dissipation would lead to an overdamped system, (getCollisionTime("
                   << mass << "), with stiffness=" << loadingStiffness_ << " and dissipation=" << dissipation_ << ")"
                   << std::endl;
         exit(-1);
     }
     return constants::pi / std::sqrt(tosqrt);
 }
References dissipation_, e(), loadingStiffness_, constants::pi, sqrt(), and mathsFunc::square().
Referenced by getRestitutionCoefficient().
getComplianceZero()
Mdouble SinterLinNormalSpecies::getComplianceZero () const
Accesses the instantaneous compliance (compliance zero)
 {
     return complianceZero_;
 }
References complianceZero_.
Referenced by SinterLinInteraction::computeNormalForce().
getDissipation()
Mdouble SinterLinNormalSpecies::getDissipation () const
Allows the normal dissipation to be accessed.
Returns
the linear dissipation coefficient
 {
     return dissipation_;
 }
References dissipation_.
Referenced by SinterLinInteraction::computeNormalForce().
getFluidity()
Mdouble SinterLinNormalSpecies::getFluidity () const
accesses the fluidity (inverse of viscosity).
 {
     return fluidity;
 }
References fluidity.
Referenced by SinterLinInteraction::computeNormalForce().
getLoadingStiffness()
Mdouble SinterLinNormalSpecies::getLoadingStiffness () const
Returns the loading stiffness of the linear plastic-viscoelastic normal force.
Returns
the loading stiffness of the linear plastic-viscoelastic normal force.
 {
     return loadingStiffness_;
 }
References loadingStiffness_.
Referenced by SinterLinInteraction::computeNormalForce(), SinterLinInteraction::getElasticEnergy(), SinterLinInteraction::getUnloadingStiffness(), and setRestitutionCoefficient().
getPenetrationDepthMax()
Mdouble SinterLinNormalSpecies::getPenetrationDepthMax () const
Returns the maximum penetration depth of the linear plastic-viscoelastic normal force.
Returns
the maximum penetration depth of the linear plastic-viscoelastic normal force.
 {
     return penetrationDepthMax_;
 }
References penetrationDepthMax_.
Referenced by SinterLinInteraction::computeNormalForce(), and SinterLinInteraction::getUnloadingStiffness().
getRestitutionCoefficient()
Mdouble SinterLinNormalSpecies::getRestitutionCoefficient (Mdouble mass) const
Calculates restitution coefficient for two copies of given disp, k, mass.
 {
     if (getConstantRestitution()) mass = 1;
     return std::exp(-dissipation_ / mass * getCollisionTime(mass));
 }
References dissipation_, Eigen::bfloat16_impl::exp(), getCollisionTime(), and BaseNormalForce::getConstantRestitution().
getSeparationDis()
Mdouble SinterLinNormalSpecies::getSeparationDis () const
accesses the critical separation distance. This mimics inter-surface forces.
 {
     return separationDis_;
 }
References separationDis_.
Referenced by SinterLinInteraction::computeNormalForce().
getSinterAdhesion()
Mdouble SinterLinNormalSpecies::getSinterAdhesion () const
Accesses sinterAdhesion_.
Returns
value of sinterAdhesion_
 {
     return sinterAdhesion_;
 }
References sinterAdhesion_.
Referenced by SinterLinInteraction::computeNormalForce().
getSinterRate()
Mdouble SinterLinNormalSpecies::getSinterRate () const
Accesses sinterRate_.
Returns
value of sinterAdhesion_
 {
     return sinterRate_;
 }
References sinterRate_.
Referenced by SinterLinInteraction::computeNormalForce().
getSinterType()
SINTER_APPROACH SinterLinNormalSpecies::getSinterType () const
 {
     return sinterType_;
 }
References sinterType_.
Referenced by SinterLinInteraction::computeNormalForce().
getSurfTension()
Mdouble SinterLinNormalSpecies::getSurfTension () const
accesses the surface tension.
 {
     return surfTension_;
 }
References surfTension_.
Referenced by SinterLinInteraction::computeNormalForce().
getUnloadingStiffnessMax()
Mdouble SinterLinNormalSpecies::getUnloadingStiffnessMax () const
Returns the maximum unloading stiffness of the linear plastic-viscoelastic normal force.
Returns
the maximum unloading stiffness of the linear plastic-viscoelastic normal force.
 {
     return unloadingStiffnessMax_;
 }
References unloadingStiffnessMax_.
Referenced by SinterLinInteraction::computeNormalForce(), and SinterLinInteraction::getUnloadingStiffness().
mix()
void SinterLinNormalSpecies::mix (SinterLinNormalSpecies * S, SinterLinNormalSpecies * T)
creates default values for mixed species
For all parameters we assume that the harmonic mean of the parameters of the original two species is a sensible default.
Parameters
[in] S,T the two species whose properties are mixed to create the new species
 {
     loadingStiffness_ = BaseSpecies::average(S->getLoadingStiffness(), T->getLoadingStiffness());
     unloadingStiffnessMax_ = BaseSpecies::average(S->getUnloadingStiffnessMax(), T->getUnloadingStiffnessMax());
     cohesionStiffness_ = BaseSpecies::average(S->getCohesionStiffness(), T->getCohesionStiffness());
     penetrationDepthMax_ = BaseSpecies::average(S->getPenetrationDepthMax(), T->getPenetrationDepthMax());
     dissipation_ = BaseSpecies::average(S->getDissipation(), T->getDissipation());
     sinterAdhesion_ = BaseSpecies::average(S->getSinterAdhesion(), T->getSinterAdhesion());
     complianceZero_ = BaseSpecies::average(S->getComplianceZero(), T->getComplianceZero());
     surfTension_ = BaseSpecies::average(S->getSurfTension(), T->getSurfTension());
     fluidity= BaseSpecies::average(S->getFluidity(), T->getFluidity());
     separationDis_ = BaseSpecies::average(S->getSeparationDis(), T->getSeparationDis());
 }
References BaseSpecies::average(), cohesionStiffness_, complianceZero_, dissipation_, fluidity, loadingStiffness_, penetrationDepthMax_, oomph::QuadTreeNames::S, separationDis_, sinterAdhesion_, surfTension_, and unloadingStiffnessMax_.
read()
void SinterLinNormalSpecies::read (std::istream & is)
Reads the species properties from an input stream.
Parameters
[in] is input stream (typically the restart file)
 {
     std::string dummy;
     is >> dummy >> loadingStiffness_;
     is >> dummy >> unloadingStiffnessMax_;
     is >> dummy >> cohesionStiffness_;
     is >> dummy >> penetrationDepthMax_;
     is >> dummy >> dissipation_;
     is >> dummy >> sinterAdhesion_;
     is >> dummy >> complianceZero_;
     is >> dummy >> surfTension_;
     is >> dummy >> sinterRate_;
     is >> dummy >> fluidity;
     is >> dummy >> separationDis_;
     unsigned type;
     is >> dummy >> type;
     sinterType_ = (SINTER_APPROACH) type;
 }
References cohesionStiffness_, complianceZero_, dissipation_, fluidity, loadingStiffness_, penetrationDepthMax_, separationDis_, sinterAdhesion_, sinterRate_, sinterType_, oomph::Global_string_for_annotation::string(), surfTension_, compute_granudrum_aor::type, and unloadingStiffnessMax_.
setCohesionStiffness()
void SinterLinNormalSpecies::setCohesionStiffness (Mdouble cohesionStiffness)
Sets the cohesive stiffness of the linear plastic-viscoelastic normal force.
Parameters
[in] cohesionStiffness the cohesive stiffness of the linear plastic-viscoelastic normal force.
 {
     cohesionStiffness_ = cohesionStiffness;
 }
References cohesionStiffness_.
Referenced by setPlasticParameters().
setCollisionTimeAndRestitutionCoefficient()
void SinterLinNormalSpecies::setCollisionTimeAndRestitutionCoefficient (Mdouble tc, Mdouble eps, Mdouble mass)
Set k, disp such that is matches a given tc and eps for a collision of two different masses. Recall the resitution constant is a function of k, disp and the mass of each particle in the collision See also setCollisionTimeAndRestitutionCoefficient(Mdouble tc, Mdouble eps, Mdouble mass)
Sets k, disp such that it matches a given tc and eps for a collision of two copies of equal mass m
Parameters
[in] tc collision time
[in] eps restitution coefficient
[in] mass effective particle mass, \(\frac{2}{1/m1+1/m2}\)
Todo:
TW: check that the masses are described correctly here (m_eff or m_p?))
 {
     if (eps == 0.0)
     {
         loadingStiffness_ = .5 * mass * mathsFunc::square(constants::pi / tc);
         dissipation_ = std::sqrt(2.0 * mass * loadingStiffness_);
     }
     else
     {
         dissipation_ = -mass / tc * std::log(eps);
         loadingStiffness_ =
                 .5 * mass * (mathsFunc::square(constants::pi / tc) + mathsFunc::square(dissipation_ / mass));
     }
     unloadingStiffnessMax_ = loadingStiffness_;
 }
References dissipation_, CRBond_Bessel::eps, loadingStiffness_, Eigen::bfloat16_impl::log(), constants::pi, sqrt(), mathsFunc::square(), and unloadingStiffnessMax_.
setComplianceZero()
void SinterLinNormalSpecies::setComplianceZero (Mdouble complianceZero)
sets the instantaneous compliance (compliance zero)
 {
     if (complianceZero < 0)
     {
         logger(ERROR, "complianceZero(%)", complianceZero);
     }
     complianceZero_ = complianceZero;
 }
References complianceZero_, ERROR, and logger.
setDissipation()
void SinterLinNormalSpecies::setDissipation (Mdouble dissipation)
Sets the linear dissipation coefficient of the linear plastic-viscoelastic normal force.
should be non-negative
Parameters
[in] dissipation the linear dissipation coefficient of the linear plastic-viscoelastic normal force.
 {
     if (dissipation < 0)
     {
         logger(ERROR, "setDissipation(%)", dissipation);
         exit(-1);
     }
     dissipation_ = dissipation;
 }
References dissipation_, ERROR, and logger.
Referenced by setLoadingStiffnessAndDissipation().
setFluidity()
void SinterLinNormalSpecies::setFluidity (Mdouble complianceOne)
sets the fluidity (inverse of viscosity).
 {
     if (complianceOne < 0)
     {
         logger(ERROR, "ComplianceOne(%)", complianceOne);
     }
     fluidity = complianceOne;
 }
References ERROR, fluidity, and logger.
setLoadingStiffness()
void SinterLinNormalSpecies::setLoadingStiffness (Mdouble loadingStiffness)
Sets the loading stiffness of the linear plastic-viscoelastic normal force.
Parameters
[in] loadingStiffness the loading stiffness of the linear plastic-viscoelastic normal force.
 {
     loadingStiffness_ = loadingStiffness;
 }
References loadingStiffness_.
Referenced by setLoadingStiffnessAndDissipation(), and setPlasticParameters().
setLoadingStiffnessAndDissipation()
void SinterLinNormalSpecies::setLoadingStiffnessAndDissipation (helpers::KAndDisp new_)
Allows the spring and dissipation constants to be changed simultaneously.
 {
     setLoadingStiffness(new_.k);
     setDissipation(new_.disp);
 }
References helpers::KAndDisp::disp, helpers::KAndDisp::k, setDissipation(), and setLoadingStiffness().
setPenetrationDepthMax()
void SinterLinNormalSpecies::setPenetrationDepthMax (Mdouble penetrationDepthMax)
Sets the maximum penetration depth of the linear plastic-viscoelastic normal force.
Parameters
[in] penetrationDepthMax the maximum penetration depth of the linear plastic-viscoelastic normal force.
 {
     penetrationDepthMax_ = penetrationDepthMax;
 }
References penetrationDepthMax_.
Referenced by setPlasticParameters().
setPlasticParameters()
void SinterLinNormalSpecies::setPlasticParameters (Mdouble loadingStiffness, Mdouble unloadingStiffnessMax, Mdouble cohesionStiffness, Mdouble penetrationDepthMax)
Sets all parameters of the linear plastic-viscoelastic normal force at once.
Parameters
[in] loadingStiffness the loading stiffness of the linear plastic-viscoelastic normal force.
[in] unloadingStiffnessMax the maximum unloading stiffness of the linear plastic-viscoelastic normal force.
[in] cohesionStiffness the cohesive stiffness of the linear plastic-viscoelastic normal force.
[in] penetrationDepthMax the maximum penetration depth of the linear plastic-viscoelastic normal force.
 {
     if (loadingStiffness <= 0 || unloadingStiffnessMax < loadingStiffness || cohesionStiffness < 0 ||
         penetrationDepthMax < 0)
     {
         std::cerr << "Error: arguments of setPlasticParameters do not make sense" << std::endl;
         exit(-1);
     }
     setLoadingStiffness(loadingStiffness);
     setUnloadingStiffnessMax(unloadingStiffnessMax);
     setCohesionStiffness(cohesionStiffness);
     setPenetrationDepthMax(penetrationDepthMax);
 }
References setCohesionStiffness(), setLoadingStiffness(), setPenetrationDepthMax(), and setUnloadingStiffnessMax().
setRestitutionCoefficient()
void SinterLinNormalSpecies::setRestitutionCoefficient (double eps, Mdouble mass)
Sets disp to obtain a restitution coefficient eps for a collision of two particles of mass m.
 {
     if (getConstantRestitution()) mass = 1;
     if (eps == 0.0) {
         dissipation_ = std::sqrt(2.0 * mass * getLoadingStiffness());
     } else {
         const Mdouble logEps = log(eps);
         dissipation_ = -std::sqrt(2.0 * mass * getLoadingStiffness()
                                   / (constants::sqr_pi + mathsFunc::square(logEps))) * logEps;
     }
 }
References dissipation_, CRBond_Bessel::eps, BaseNormalForce::getConstantRestitution(), getLoadingStiffness(), Eigen::bfloat16_impl::log(), constants::sqr_pi, sqrt(), and mathsFunc::square().
setSeparationDis()
void SinterLinNormalSpecies::setSeparationDis (Mdouble separationDis)
sets the critical separation distance. This mimics inter-surface forces.
 {
     if (separationDis < 0)
     {
         logger(ERROR, "SeparationDis(%)", separationDis);
     }
     separationDis_ = separationDis;
 }
References ERROR, logger, and separationDis_.
setSinterAdhesion()
void SinterLinNormalSpecies::setSinterAdhesion (Mdouble sinterAdhesion)
Sets sinterAdhesion_.
 {
     if (sinterAdhesion < 0)
     {
         logger(ERROR, "setSinterAdhesion(%)", sinterAdhesion);
         exit(-1);
     }
     sinterAdhesion_ = sinterAdhesion;
 }
References ERROR, logger, and sinterAdhesion_.
setSinterRate()
void SinterLinNormalSpecies::setSinterRate (Mdouble sinterRate)
Sets sinterRate_.
 {
     if (sinterRate < 0)
     {
         logger(ERROR, "setSinterRate(%)", sinterRate);
     }
     sinterRate_ = sinterRate;
 }
References ERROR, logger, and sinterRate_.
setSinterType()
void SinterLinNormalSpecies::setSinterType (SINTER_APPROACH sinterType)
sets the sintering approach selected.
 {
     sinterType_ = sinterType;
     if (sinterType_ == SINTER_APPROACH::FRENKEL)
         logger(INFO, "Sintertype set to Frenkel");
     else if (sinterType_ == SINTER_APPROACH::VISCOELASTIC_CONTACT)
         logger(INFO, "Sintertype set to Three different mechanisms");
     else
         logger(ERROR, "Sintertype not understood");
 }
References ERROR, FRENKEL, INFO, logger, sinterType_, and VISCOELASTIC_CONTACT.
setStiffnessAndRestitutionCoefficient()
void SinterLinNormalSpecies::setStiffnessAndRestitutionCoefficient (Mdouble stiffness, Mdouble eps, Mdouble mass)
Sets k, disp such that it matches a given tc and eps for a collision of two copies of P.
Sets k, disp such that it matches a given tc and eps for a collision of two copies of P
Parameters
[in] stiffness stiffness
[in] eps restitution coefficient
[in] mass effective particle mass, \(\frac{2}{1/m1+1/m2}\)
 {
     loadingStiffness_ = stiffness;
     if (eps == 0.0)
     {
         dissipation_ = std::sqrt(2.0 * mass * stiffness);
     }
     else
     {
         dissipation_ =
                 -std::sqrt(2.0 * mass * stiffness / (constants::sqr_pi + mathsFunc::square(log(eps)))) * log(eps);
     }
     unloadingStiffnessMax_ = loadingStiffness_;
 }
References dissipation_, CRBond_Bessel::eps, loadingStiffness_, Eigen::bfloat16_impl::log(), constants::sqr_pi, sqrt(), mathsFunc::square(), and unloadingStiffnessMax_.
setSurfTension()
void SinterLinNormalSpecies::setSurfTension (Mdouble complianceZero)
sets the surface tension.
 {
     if (surfTension < 0)
     {
         logger(ERROR, "SurfTension(%)", surfTension);
     }
     surfTension_ = surfTension;
 }
References ERROR, logger, and surfTension_.
setUnloadingStiffnessMax()
void SinterLinNormalSpecies::setUnloadingStiffnessMax (Mdouble unloadingStiffnessMax)
Sets the maximum unloading stiffness of the linear plastic-viscoelastic normal force.
Parameters
[in] unloadingStiffnessMax the maximum unloading stiffness of the linear plastic-viscoelastic normal force.
 {
     unloadingStiffnessMax_ = unloadingStiffnessMax;
 }
References unloadingStiffnessMax_.
Referenced by setPlasticParameters().
write()
void SinterLinNormalSpecies::write (std::ostream & os) const
Writes the species properties to an output stream.
Parameters
[out] os output stream (typically the restart file)
 {
     os << " loadingStiffness " << loadingStiffness_;
     os << " maxUnloadingStiffness " << unloadingStiffnessMax_;
     os << " cohesionStiffness " << cohesionStiffness_;
     os << " maxPenetration " << penetrationDepthMax_;
     os << " dissipation " << dissipation_;
     os << " sinterAdhesion " << sinterAdhesion_;
     os << " sinterRate " << sinterRate_;
     os << " complianceZero " << complianceZero_;
     os << " surfTension  " << surfTension_;
     os << " complianceOne " << fluidity;
     os << " separationDis " << separationDis_;
     os << " sinterType " << (unsigned) sinterType_;
 }
References cohesionStiffness_, complianceZero_, dissipation_, fluidity, loadingStiffness_, penetrationDepthMax_, separationDis_, sinterAdhesion_, sinterRate_, sinterType_, surfTension_, and unloadingStiffnessMax_.
Member Data Documentation
cohesionStiffness_
Mdouble SinterLinNormalSpecies::cohesionStiffness_ private
the adhesive spring constant (k^c) for plastic deformations
Referenced by getCohesionStiffness(), mix(), read(), setCohesionStiffness(), SinterLinNormalSpecies(), and write().
complianceZero_
Mdouble SinterLinNormalSpecies::complianceZero_ private
Material property. C0 = (1-\nu^2)/E, E: young's Modulus, nu poisson ratio.
Referenced by getComplianceZero(), mix(), read(), setComplianceZero(), SinterLinNormalSpecies(), and write().
dissipation_
Mdouble SinterLinNormalSpecies::dissipation_ private
linear dissipation coefficient
Referenced by computeTimeStep(), getCollisionTime(), getDissipation(), getRestitutionCoefficient(), mix(), read(), setCollisionTimeAndRestitutionCoefficient(), setDissipation(), setRestitutionCoefficient(), setStiffnessAndRestitutionCoefficient(), SinterLinNormalSpecies(), and write().
fluidity
Mdouble SinterLinNormalSpecies::fluidity private
Material property, which represents the inverse of viscosity
Referenced by getFluidity(), mix(), read(), setFluidity(), SinterLinNormalSpecies(), and write().
loadingStiffness_
Mdouble SinterLinNormalSpecies::loadingStiffness_ private
(normal) spring constant (k_1)
Referenced by getCollisionTime(), getLoadingStiffness(), mix(), read(), setCollisionTimeAndRestitutionCoefficient(), setLoadingStiffness(), setStiffnessAndRestitutionCoefficient(), SinterLinNormalSpecies(), and write().
penetrationDepthMax_
Mdouble SinterLinNormalSpecies::penetrationDepthMax_ private
the depth (relative to the normalized radius) at which k_2^max is used (phi_f)
Referenced by getPenetrationDepthMax(), mix(), read(), setPenetrationDepthMax(), SinterLinNormalSpecies(), and write().
separationDis_
Mdouble SinterLinNormalSpecies::separationDis_ private
Critical separation distance, to describe inter-surface forces.
Referenced by getSeparationDis(), mix(), read(), setSeparationDis(), SinterLinNormalSpecies(), and write().
sinterAdhesion_
Mdouble SinterLinNormalSpecies::sinterAdhesion_ private
Determines sinter adhesion force fa=sinterAdhesion_*radius in sinter rate: d(delta0)/dt = (fa+fep)/nu
Referenced by getSinterAdhesion(), mix(), read(), setSinterAdhesion(), SinterLinNormalSpecies(), and write().
sinterRate_
Mdouble SinterLinNormalSpecies::sinterRate_ private
Determines sinter rate: d(delta0)/dt = (fa+fep)/nu
Referenced by getSinterRate(), read(), setSinterRate(), SinterLinNormalSpecies(), and write().
sinterType_
SINTER_APPROACH SinterLinNormalSpecies::sinterType_ private
Type of sintering.
Referenced by getSinterType(), read(), setSinterType(), SinterLinNormalSpecies(), and write().
surfTension_
Mdouble SinterLinNormalSpecies::surfTension_ private
Material property.
Referenced by getSurfTension(), mix(), read(), setSurfTension(), SinterLinNormalSpecies(), and write().
unloadingStiffnessMax_
Mdouble SinterLinNormalSpecies::unloadingStiffnessMax_ private
the maximum elastic constant (k_2^max) for plastic deformations
Referenced by computeTimeStep(), getUnloadingStiffnessMax(), mix(), read(), setCollisionTimeAndRestitutionCoefficient(), setStiffnessAndRestitutionCoefficient(), setUnloadingStiffnessMax(), SinterLinNormalSpecies(), and write().
The documentation for this class was generated from the following files:
SinterLinNormalSpecies.h
SinterLinNormalSpecies.cc