MercuryDPM: Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > Class Template Reference
Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > Class Template Reference
Sparse linear algebra » Reference » SparseCore_Module
A versatile sparse matrix representation where each element is a block.
#include <BlockSparseMatrix.h>
Classes
class BlockInnerIterator
class InnerIterator
Public Types
enum {
Options = Options_ , Flags = Options , BlockSize = _BlockAtCompileTime , RowsAtCompileTime = Dynamic ,
ColsAtCompileTime = Dynamic , MaxRowsAtCompileTime = Dynamic , MaxColsAtCompileTime = Dynamic , IsVectorAtCompileTime = 0 ,
IsColMajor = Flags & RowMajorBit ? 0 : 1
}
typedef Scalar_ Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef StorageIndex_ StorageIndex
typedef internal::ref_selector< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > >::type Nested
typedef Matrix< Scalar, _BlockAtCompileTime, _BlockAtCompileTime, IsColMajor ? ColMajor :RowMajor > BlockScalar
typedef Matrix< RealScalar, _BlockAtCompileTime, _BlockAtCompileTime, IsColMajor ? ColMajor :RowMajor > BlockRealScalar
typedef std::conditional_t< _BlockAtCompileTime==Dynamic, Scalar, BlockScalar > BlockScalarReturnType
typedef BlockSparseMatrix< Scalar, BlockSize, IsColMajor ? ColMajor :RowMajor, StorageIndex > PlainObject
Public Types inherited from Eigen::SparseMatrixBase< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > >
enum
typedef internal::traits< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > >::Scalar Scalar
typedef Scalar value_type
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef internal::traits< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > >::StorageKind StorageKind
typedef internal::traits< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > >::StorageIndex StorageIndex
typedef internal::add_const_on_value_type_if_arithmetic< typename internal::packet_traits< Scalar >::type >::type PacketReturnType
typedef SparseMatrixBase StorageBaseType
typedef Matrix< StorageIndex, Dynamic, 1 > IndexVector
typedef Matrix< Scalar, Dynamic, 1 > ScalarVector
typedef std::conditional_t< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, Eigen::Transpose< const BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > > >, Transpose< const BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > > > AdjointReturnType
typedef Transpose< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > > TransposeReturnType
typedef Transpose< const BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > > ConstTransposeReturnType
typedef SparseMatrix< Scalar, Flags &RowMajorBit ? RowMajor :ColMajor, StorageIndex > PlainObject
typedef NumTraits< Scalar >::Real RealScalar
typedef std::conditional_t< HasDirectAccess_, const Scalar &, Scalar > CoeffReturnType
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, Matrix< Scalar, Dynamic, Dynamic > > ConstantReturnType
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime > DenseMatrixType
typedef Matrix< Scalar, internal::max_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime), internal::max_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime)> SquareMatrixType
typedef EigenBase< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > > Base
Public Types inherited from Eigen::EigenBase< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > >::StorageKind StorageKind
Public Member Functions
BlockSparseMatrix ()
BlockSparseMatrix (Index brow, Index bcol)
Construct and resize.
BlockSparseMatrix (const BlockSparseMatrix &other)
Copy-constructor.
BlockSparseMatrix & operator= (BlockSparseMatrix other)
~BlockSparseMatrix ()
template<typename MatrixType >
BlockSparseMatrix (const MatrixType &spmat)
Constructor from a sparse matrix.
template<typename MatrixType >
BlockSparseMatrix & operator= (const MatrixType &spmat)
Assignment from a sparse matrix with the same storage order.
template<typename MatrixType >
void setBlockStructure (const MatrixType &blockPattern)
Set the nonzero block pattern of the matrix.
void resize (Index brow, Index bcol)
Set the number of rows and columns blocks.
void setBlockSize (Index blockSize)
set the block size at runtime for fixed-size block layout
void setBlockLayout (const VectorXi &rowBlocks, const VectorXi &colBlocks)
Set the row and column block layouts,.
void reserve (const Index nonzerosblocks)
Allocate the internal array of pointers to blocks and their inner indices.
template<typename InputIterator >
void setFromTriplets (const InputIterator &begin, const InputIterator &end)
Fill values in a matrix from a triplet list.
Index rows () const
Index cols () const
Index innerSize () const
Index outerSize () const
Index blockRows () const
Index blockCols () const
Index outerBlocks () const
Index innerBlocks () const
Index outerToBlock (Index outer) const
Index innerToBlock (Index inner) const
Ref< BlockScalar > coeffRef (Index brow, Index bcol)
Map< const BlockScalar > coeff (Index brow, Index bcol) const
template<typename VecType >
BlockSparseTimeDenseProduct< BlockSparseMatrix, VecType > operator* (const VecType &lhs) const
Index nonZerosBlocks () const
Index nonZeros () const
BlockScalarReturnType * valuePtr ()
StorageIndex * innerIndexPtr ()
const StorageIndex * innerIndexPtr () const
StorageIndex * outerIndexPtr ()
const StorageIndex * outerIndexPtr () const
bool isCompressed () const
for compatibility purposes with the SparseMatrix class
Index blockRowsIndex (Index bi) const
Index blockColsIndex (Index bj) const
Index blockOuterIndex (Index bj) const
Index blockInnerIndex (Index bi) const
Index blockInnerSize (Index bi) const
Index blockOuterSize (Index bj) const
Index blockPtr (Index id) const
Public Member Functions inherited from Eigen::SparseMatrixBase< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > >
BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & operator= (const EigenBase< OtherDerived > &other)
BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & operator= (const ReturnByValue< OtherDerived > &other)
BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & operator= (const SparseMatrixBase< OtherDerived > &other)
BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & operator= (const BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > &other)
const BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & derived () const
BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & derived ()
BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & const_cast_derived () const
Index rows () const
Index cols () const
Index size () const
bool isVector () const
Index outerSize () const
Index innerSize () const
bool isRValue () const
BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & markAsRValue ()
SparseMatrixBase ()
BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & operator+= (const SparseMatrixBase< OtherDerived > &other)
BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & operator+= (const DiagonalBase< OtherDerived > &other)
BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & operator+= (const EigenBase< OtherDerived > &other)
EIGEN_STRONG_INLINE BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & operator+= (const SparseMatrixBase< OtherDerived > &other)
BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & operator-= (const SparseMatrixBase< OtherDerived > &other)
BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & operator-= (const DiagonalBase< OtherDerived > &other)
BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & operator-= (const EigenBase< OtherDerived > &other)
EIGEN_STRONG_INLINE BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & operator-= (const SparseMatrixBase< OtherDerived > &other)
BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & operator*= (const Scalar &other)
BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & operator*= (const SparseMatrixBase< OtherDerived > &other)
BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & operator/= (const Scalar &other)
EIGEN_STRONG_INLINE const CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
EIGEN_STRONG_INLINE const SparseMatrixBase< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > >::template CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
const Product< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >, OtherDerived > operator* (const DiagonalBase< OtherDerived > &other) const
const Product< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >, OtherDerived, AliasFreeProduct > operator* (const SparseMatrixBase< OtherDerived > &other) const
const Product< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >, OtherDerived > operator* (const MatrixBase< OtherDerived > &other) const
SparseSymmetricPermutationProduct< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >, Upper|Lower > twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > &perm) const
const TriangularView< const BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >, Mode > triangularView () const
ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
SparseMatrixBase< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > >::template ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
SparseMatrixBase< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > >::template SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
Scalar dot (const MatrixBase< OtherDerived > &other) const
Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
internal::traits< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > >::Scalar dot (const MatrixBase< OtherDerived > &other) const
internal::traits< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > >::Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
RealScalar squaredNorm () const
RealScalar norm () const
RealScalar blueNorm () const
TransposeReturnType transpose ()
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
DenseMatrixType toDense () const
bool isApprox (const SparseMatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isApprox (const MatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
const internal::eval< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > >::type eval () const
Scalar sum () const
const SparseView< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > > pruned (const Scalar &reference=Scalar(0), const RealScalar &epsilon=NumTraits< Scalar >::dummy_precision()) const
Public Member Functions inherited from Eigen::EigenBase< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > >
constexpr EIGEN_DEVICE_FUNC BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & derived ()
constexpr EIGEN_DEVICE_FUNC const BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & derived () const
EIGEN_DEVICE_FUNC BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & const_cast_derived () const
EIGEN_DEVICE_FUNC const BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >, Device > device (Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >, Device > device (Device &device) const
Protected Member Functions
Map< BlockScalar > insert (Index brow, Index bcol)
Protected Member Functions inherited from Eigen::SparseMatrixBase< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > >
BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & assign (const OtherDerived &other)
void assignGeneric (const OtherDerived &other)
Protected Attributes
Index m_innerBSize
Index m_outerBSize
StorageIndex * m_innerOffset
StorageIndex * m_outerOffset
Index m_nonzerosblocks
Index m_nonzeros
Scalar * m_values
StorageIndex * m_blockPtr
StorageIndex * m_indices
StorageIndex * m_outerIndex
Index m_blockSize
Protected Attributes inherited from Eigen::SparseMatrixBase< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > >
bool m_isRValue
Friends
void swap (BlockSparseMatrix &first, BlockSparseMatrix &second)
std::ostream & operator<< (std::ostream &s, const BlockSparseMatrix &m)
Additional Inherited Members
Static Protected Member Functions inherited from Eigen::SparseMatrixBase< BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > >
static StorageIndex convert_index (const Index idx)
Detailed Description
template<typename Scalar_, int _BlockAtCompileTime, int Options_, typename StorageIndex_>
class Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >
A versatile sparse matrix representation where each element is a block.
This class provides routines to manipulate block sparse matrices stored in a BSR-like representation. There are two main types :
All blocks have the same number of rows and columns, called block size in the following. In this case, if this block size is known at compile time, it can be given as a template parameter like
BlockSparseMatrix<Scalar, 3, ColMajor> bmat(b_rows, b_cols);
Here, bmat is a b_rows x b_cols block sparse matrix where each coefficient is a 3x3 dense matrix. If the block size is fixed but will be given at runtime,
BlockSparseMatrix<Scalar, Dynamic, ColMajor> bmat(b_rows, b_cols);
bmat.setBlockSize(block_size);
The second case is for variable-block sparse matrices. Here each block has its own dimensions. The only restriction is that all the blocks in a row (resp. a column) should have the same number of rows (resp. of columns). It is thus required in this case to describe the layout of the matrix by calling setBlockLayout(rowBlocks, colBlocks).
In any of the previous case, the matrix can be filled by calling setFromTriplets(). A regular sparse matrix can be converted to a block sparse matrix and vice versa. It is obviously required to describe the block layout beforehand by calling either setBlockSize() for fixed-size blocks or setBlockLayout for variable-size blocks.
Template Parameters
Scalar_ The Scalar type
_BlockAtCompileTime The block layout option. It takes the following values Dynamic : block size known at runtime a numeric number : fixed-size block known at compile time
Member Typedef Documentation
BlockRealScalar
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > typedef Matrix<RealScalar, _BlockAtCompileTime, _BlockAtCompileTime, IsColMajor ? ColMajor : RowMajor> Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockRealScalar
BlockScalar
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > typedef Matrix<Scalar, _BlockAtCompileTime, _BlockAtCompileTime, IsColMajor ? ColMajor : RowMajor> Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockScalar
BlockScalarReturnType
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > typedef std::conditional_t<_BlockAtCompileTime == Dynamic, Scalar, BlockScalar> Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockScalarReturnType
Nested
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > typedef internal::ref_selector<BlockSparseMatrix<Scalar_, _BlockAtCompileTime, Options_, StorageIndex_> >::type Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::Nested
PlainObject
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > typedef BlockSparseMatrix<Scalar, BlockSize, IsColMajor ? ColMajor : RowMajor, StorageIndex> Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::PlainObject
RealScalar
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > typedef NumTraits<Scalar>::Real Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::RealScalar
Scalar
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > typedef Scalar_ Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::Scalar
StorageIndex
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > typedef StorageIndex_ Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::StorageIndex
Member Enumeration Documentation
anonymous enum
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > anonymous enum
Enumerator
Options
Flags
BlockSize
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
IsVectorAtCompileTime
IsColMajor
        {
     Options = Options_,
     Flags = Options,
     BlockSize = _BlockAtCompileTime,
     RowsAtCompileTime = Dynamic,
     ColsAtCompileTime = Dynamic,
     MaxRowsAtCompileTime = Dynamic,
     MaxColsAtCompileTime = Dynamic,
     IsVectorAtCompileTime = 0,
     IsColMajor = Flags & RowMajorBit ? 0 : 1
   };
Constructor & Destructor Documentation
BlockSparseMatrix() [1/4]
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockSparseMatrix () inline
       : m_innerBSize(0),
         m_outerBSize(0),
         m_innerOffset(0),
         m_outerOffset(0),
         m_nonzerosblocks(0),
         m_values(0),
         m_blockPtr(0),
         m_indices(0),
         m_outerIndex(0),
         m_blockSize(BlockSize) {}
BlockSparseMatrix() [2/4]
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockSparseMatrix (Index brow, Index bcol) inline
Construct and resize.
       : m_innerBSize(IsColMajor ? brow : bcol),
         m_outerBSize(IsColMajor ? bcol : brow),
         m_innerOffset(0),
         m_outerOffset(0),
         m_nonzerosblocks(0),
         m_values(0),
         m_blockPtr(0),
         m_indices(0),
         m_outerIndex(0),
         m_blockSize(BlockSize) {}
BlockSparseMatrix() [3/4]
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockSparseMatrix (const BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & other) inline
Copy-constructor.
       : m_innerBSize(other.m_innerBSize),
         m_outerBSize(other.m_outerBSize),
         m_nonzerosblocks(other.m_nonzerosblocks),
         m_nonzeros(other.m_nonzeros),
         m_blockPtr(0),
         m_blockSize(other.m_blockSize) {
     // should we allow copying between variable-size blocks and fixed-size blocks ??
     eigen_assert(m_blockSize == BlockSize && " CAN NOT COPY BETWEEN FIXED-SIZE AND VARIABLE-SIZE BLOCKS");
     std::copy(other.m_innerOffset, other.m_innerOffset + m_innerBSize + 1, m_innerOffset);
     std::copy(other.m_outerOffset, other.m_outerOffset + m_outerBSize + 1, m_outerOffset);
     std::copy(other.m_values, other.m_values + m_nonzeros, m_values);
     if (m_blockSize != Dynamic) std::copy(other.m_blockPtr, other.m_blockPtr + m_nonzerosblocks, m_blockPtr);
     std::copy(other.m_indices, other.m_indices + m_nonzerosblocks, m_indices);
     std::copy(other.m_outerIndex, other.m_outerIndex + m_outerBSize, m_outerIndex);
   }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockSize, copy(), Eigen::Dynamic, eigen_assert, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockPtr, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockSize, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_indices, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_innerBSize, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_innerOffset, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_nonzeros, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_nonzerosblocks, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerBSize, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerIndex, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerOffset, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_values.
~BlockSparseMatrix()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::~BlockSparseMatrix () inline
{
     delete[] m_outerIndex;
     delete[] m_innerOffset;
     delete[] m_outerOffset;
     delete[] m_indices;
     delete[] m_blockPtr;
     delete[] m_values;
   }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockPtr, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_indices, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_innerOffset, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerIndex, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerOffset, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_values.
BlockSparseMatrix() [4/4]
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > template<typename MatrixType > Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockSparseMatrix (const MatrixType & spmat) inline
Constructor from a sparse matrix.
                                                     : m_blockSize(BlockSize) {
     EIGEN_STATIC_ASSERT((m_blockSize != Dynamic), THIS_METHOD_IS_ONLY_FOR_FIXED_SIZE);
     *this = spmat;
   }
References Eigen::Dynamic, EIGEN_STATIC_ASSERT, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockSize.
Member Function Documentation
blockCols()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockCols () const inline
Returns
the number of columns grouped by blocks
 { return (IsColMajor ? m_outerBSize : m_innerBSize); }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::IsColMajor, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_innerBSize, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerBSize.
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::coeff(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::coeffRef(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::operator=().
blockColsIndex()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockColsIndex (Index bj) const inline
Returns
the starting index of the bj col block
 { return IsColMajor ? blockOuterIndex(bj) : blockInnerIndex(bj); }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockInnerIndex(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockOuterIndex(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::IsColMajor.
blockInnerIndex()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockInnerIndex (Index bi) const inline
{
     return (m_blockSize == Dynamic) ? m_innerOffset[bi] : (bi * m_blockSize);
   }
References Eigen::Dynamic, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockSize, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_innerOffset.
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockColsIndex(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockRowsIndex().
blockInnerSize()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockInnerSize (Index bi) const inline
{
     return (m_blockSize == Dynamic) ? (m_innerOffset[bi + 1] - m_innerOffset[bi]) : m_blockSize;
   }
References Eigen::Dynamic, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockSize, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_innerOffset.
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::coeff(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::coeffRef(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::operator=(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockStructure().
blockOuterIndex()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockOuterIndex (Index bj) const inline
{
     return (m_blockSize == Dynamic) ? m_outerOffset[bj] : (bj * m_blockSize);
   }
References Eigen::Dynamic, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockSize, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerOffset.
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockColsIndex(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockRowsIndex(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::operator=().
blockOuterSize()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockOuterSize (Index bj) const inline
{
     return (m_blockSize == Dynamic) ? (m_outerOffset[bj + 1] - m_outerOffset[bj]) : m_blockSize;
   }
References Eigen::Dynamic, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockSize, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerOffset.
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::coeff(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::coeffRef(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::operator=(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockStructure().
blockPtr()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockPtr (Index id) const inline
Returns
the starting position of the block id in the array of values
{
     if (m_blockSize == Dynamic)
       return m_blockPtr[id];
     else
       return id * m_blockSize * m_blockSize;
     // return blockDynIdx(id, std::conditional_t<(BlockSize==Dynamic), internal::true_type, internal::false_type>());
   }
References Eigen::Dynamic, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockPtr, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockSize.
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::coeff(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::coeffRef(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setFromTriplets().
blockRows()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockRows () const inline
Returns
the number of rows grouped by blocks
 { return (IsColMajor ? m_innerBSize : m_outerBSize); }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::IsColMajor, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_innerBSize, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerBSize.
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::coeff(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::coeffRef(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::operator=().
blockRowsIndex()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockRowsIndex (Index bi) const inline
Returns
the starting index of the bi row block
 { return IsColMajor ? blockInnerIndex(bi) : blockOuterIndex(bi); }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockInnerIndex(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockOuterIndex(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::IsColMajor.
coeff()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Map<const BlockScalar> Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::coeff (Index brow, Index bcol) const inline
Returns
the value of the (i,j) block as an Eigen Dense Matrix
{
     eigen_assert(brow < blockRows() && "BLOCK ROW INDEX OUT OF BOUNDS");
     eigen_assert(bcol < blockCols() && "BLOCK COLUMN OUT OF BOUNDS");
     StorageIndex rsize = IsColMajor ? blockInnerSize(brow) : blockOuterSize(bcol);
     StorageIndex csize = IsColMajor ? blockOuterSize(bcol) : blockInnerSize(brow);
     StorageIndex inner = IsColMajor ? brow : bcol;
     StorageIndex outer = IsColMajor ? bcol : brow;
     StorageIndex offset = m_outerIndex[outer];
     while (offset < m_outerIndex[outer + 1] && m_indices[offset] != inner) offset++;
     if (m_indices[offset] == inner) {
       return Map<const BlockScalar>(&(m_values[blockPtr(offset)]), rsize, csize);
     } else
       //        return BlockScalar::Zero(rsize, csize);
       eigen_assert("NOT YET SUPPORTED");
   }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockCols(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockInnerSize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockOuterSize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockPtr(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockRows(), eigen_assert, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::IsColMajor, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_indices, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerIndex, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_values.
coeffRef()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Ref<BlockScalar> Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::coeffRef (Index brow, Index bcol) inline
Returns
a reference to the (i,j) block as an Eigen Dense Matrix
{
     eigen_assert(brow < blockRows() && "BLOCK ROW INDEX OUT OF BOUNDS");
     eigen_assert(bcol < blockCols() && "BLOCK nzblocksFlagCOLUMN OUT OF BOUNDS");
     StorageIndex rsize = IsColMajor ? blockInnerSize(brow) : blockOuterSize(bcol);
     StorageIndex csize = IsColMajor ? blockOuterSize(bcol) : blockInnerSize(brow);
     StorageIndex inner = IsColMajor ? brow : bcol;
     StorageIndex outer = IsColMajor ? bcol : brow;
     StorageIndex offset = m_outerIndex[outer];
     while (offset < m_outerIndex[outer + 1] && m_indices[offset] != inner) offset++;
     if (m_indices[offset] == inner) {
       return Map<BlockScalar>(&(m_values[blockPtr(offset)]), rsize, csize);
     } else {
       // FIXME the block does not exist, Insert it !!!!!!!!!
       eigen_assert("DYNAMIC INSERTION IS NOT YET SUPPORTED");
     }
   }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockCols(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockInnerSize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockOuterSize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockPtr(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockRows(), eigen_assert, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::IsColMajor, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_indices, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerIndex, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_values.
cols()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::cols () const inline
Returns
the number of cols
{
     //      return blockCols();
     return (IsColMajor ? outerSize() : innerSize());
   }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::innerSize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::IsColMajor, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::outerSize().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockInnerIterator::value(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockInnerIterator::valueRef().
innerBlocks()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::innerBlocks () const inline
 { return m_innerBSize; }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_innerBSize.
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockLayout().
innerIndexPtr() [1/2]
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > StorageIndex* Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::innerIndexPtr () inline
 { return m_indices; }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_indices.
innerIndexPtr() [2/2]
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > const StorageIndex* Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::innerIndexPtr () const inline
 { return m_indices; }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_indices.
innerSize()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::innerSize () const inline
{
     if (m_blockSize == Dynamic)
       return m_innerOffset[m_innerBSize];
     else
       return (m_innerBSize * m_blockSize);
   }
References Eigen::Dynamic, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockSize, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_innerBSize, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_innerOffset.
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::cols(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::innerToBlock(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::rows().
innerToBlock()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::innerToBlock (Index inner) const inline
Returns
the block index where inner belongs to
{
     eigen_assert(inner < innerSize() && "OUTER INDEX OUT OF BOUNDS");
     if (m_blockSize != Dynamic) return (inner / m_blockSize);  // Integer division
     StorageIndex b_inner = 0;
     while (m_innerOffset[b_inner] <= inner) ++b_inner;
     return b_inner - 1;
   }
References Eigen::Dynamic, eigen_assert, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::innerSize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockSize, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_innerOffset.
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::operator=().
insert()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Map<BlockScalar> Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::insert (Index brow, Index bcol) protected
isCompressed()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > bool Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::isCompressed () const inline
for compatibility purposes with the SparseMatrix class
 { return true; }
nonZeros()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::nonZeros () const inline
Returns
the total number of nonzero elements, including eventual explicit zeros in blocks
 { return m_nonzeros; }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_nonzeros.
nonZerosBlocks()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::nonZerosBlocks () const inline
Returns
the number of nonzero blocks
 { return m_nonzerosblocks; }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_nonzerosblocks.
operator*()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > template<typename VecType > BlockSparseTimeDenseProduct<BlockSparseMatrix, VecType> Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::operator* (const VecType & lhs) const inline
{
     return BlockSparseTimeDenseProduct<BlockSparseMatrix, VecType>(*this, lhs);
   }
operator=() [1/2]
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > BlockSparseMatrix& Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::operator= (BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > other) inline
{
     // Copy-and-swap paradigm ... avoid leaked data if thrown
     swap(*this, other);
     return *this;
   }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::swap.
operator=() [2/2]
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > template<typename MatrixType > BlockSparseMatrix& Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::operator= (const MatrixType & spmat) inline
Assignment from a sparse matrix with the same storage order.
Convert from a sparse matrix to block sparse matrix.
Warning
Before calling this function, tt is necessary to call either setBlockLayout() (matrices with variable-size blocks) or setBlockSize() (for fixed-size blocks).
{
     eigen_assert((m_innerBSize != 0 && m_outerBSize != 0) &&
                  "Trying to assign to a zero-size matrix, call resize() first");
     eigen_assert(((MatrixType::Options & RowMajorBit) != IsColMajor) && "Wrong storage order");
     typedef SparseMatrix<bool, MatrixType::Options, typename MatrixType::Index> MatrixPatternType;
     MatrixPatternType blockPattern(blockRows(), blockCols());
     m_nonzeros = 0;
     // First, compute the number of nonzero blocks and their locations
     for (StorageIndex bj = 0; bj < m_outerBSize; ++bj) {
       // Browse each outer block and compute the structure
       std::vector<bool> nzblocksFlag(m_innerBSize, false);  // Record the existing blocks
       blockPattern.startVec(bj);
       for (StorageIndex j = blockOuterIndex(bj); j < blockOuterIndex(bj + 1); ++j) {
         typename MatrixType::InnerIterator it_spmat(spmat, j);
         for (; it_spmat; ++it_spmat) {
           StorageIndex bi = innerToBlock(it_spmat.index());  // Index of the current nonzero block
           if (!nzblocksFlag[bi]) {
             // Save the index of this nonzero block
             nzblocksFlag[bi] = true;
             blockPattern.insertBackByOuterInnerUnordered(bj, bi) = true;
             // Compute the total number of nonzeros (including explicit zeros in blocks)
             m_nonzeros += blockOuterSize(bj) * blockInnerSize(bi);
           }
         }
       }  // end current outer block
     }
     blockPattern.finalize();
     // Allocate the internal arrays
     setBlockStructure(blockPattern);
     for (StorageIndex nz = 0; nz < m_nonzeros; ++nz) m_values[nz] = Scalar(0);
     for (StorageIndex bj = 0; bj < m_outerBSize; ++bj) {
       // Now copy the values
       for (StorageIndex j = blockOuterIndex(bj); j < blockOuterIndex(bj + 1); ++j) {
         // Browse the outer block column by column (for column-major matrices)
         typename MatrixType::InnerIterator it_spmat(spmat, j);
         for (; it_spmat; ++it_spmat) {
           StorageIndex idx = 0;                              // Position of this block in the column block
           StorageIndex bi = innerToBlock(it_spmat.index());  // Index of the current nonzero block
           // Go to the inner block where this element belongs to
           while (bi > m_indices[m_outerIndex[bj] + idx]) ++idx;  // Not expensive for ordered blocks
           StorageIndex idxVal;  // Get the right position in the array of values for this element
           if (m_blockSize == Dynamic) {
             // Offset from all blocks before ...
             idxVal = m_blockPtr[m_outerIndex[bj] + idx];
             // ... and offset inside the block
             idxVal += (j - blockOuterIndex(bj)) * blockOuterSize(bj) + it_spmat.index() - m_innerOffset[bi];
           } else {
             // All blocks before
             idxVal = (m_outerIndex[bj] + idx) * m_blockSize * m_blockSize;
             // inside the block
             idxVal += (j - blockOuterIndex(bj)) * m_blockSize + (it_spmat.index() % m_blockSize);
           }
           // Insert the value
           m_values[idxVal] = it_spmat.value();
         }  // end of this column
       }    // end of this block
     }      // end of this outer block
     return *this;
   }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockCols(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockInnerSize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockOuterIndex(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockOuterSize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockRows(), Eigen::Dynamic, eigen_assert, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::innerToBlock(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::IsColMajor, j, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockPtr, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockSize, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_indices, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_innerBSize, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_innerOffset, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_nonzeros, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerBSize, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerIndex, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_values, Mesh_Parameters::nz, Eigen::RowMajorBit, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockStructure().
outerBlocks()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::outerBlocks () const inline
 { return m_outerBSize; }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerBSize.
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockLayout().
outerIndexPtr() [1/2]
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > StorageIndex* Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::outerIndexPtr () inline
 { return m_outerIndex; }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerIndex.
outerIndexPtr() [2/2]
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > const StorageIndex* Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::outerIndexPtr () const inline
 { return m_outerIndex; }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerIndex.
outerSize()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::outerSize () const inline
{
     if (m_blockSize == Dynamic)
       return m_outerOffset[m_outerBSize];
     else
       return (m_outerBSize * m_blockSize);
   }
References Eigen::Dynamic, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockSize, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerBSize, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerOffset.
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::cols(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::outerToBlock(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::rows().
outerToBlock()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::outerToBlock (Index outer) const inline
Returns
the block index where outer belongs to
{
     eigen_assert(outer < outerSize() && "OUTER INDEX OUT OF BOUNDS");
     if (m_blockSize != Dynamic) return (outer / m_blockSize);  // Integer division
     StorageIndex b_outer = 0;
     while (m_outerOffset[b_outer] <= outer) ++b_outer;
     return b_outer - 1;
   }
References Eigen::Dynamic, eigen_assert, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockSize, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerOffset, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::outerSize().
reserve()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > void Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::reserve (const Index nonzerosblocks) inline
Allocate the internal array of pointers to blocks and their inner indices.
Note
For fixed-size blocks, call setBlockSize() to set the block. And For variable-size blocks, call setBlockLayout() before using this function
Parameters
nonzerosblocks Number of nonzero blocks. The total number of nonzeros is is computed in setBlockLayout() for variable-size blocks
See also
setBlockSize()
{
     eigen_assert((m_innerBSize != 0 && m_outerBSize != 0) &&
                  "TRYING TO RESERVE ZERO-SIZE MATRICES, CALL resize() first");
     // FIXME Should free if already allocated
     m_outerIndex = new StorageIndex[m_outerBSize + 1];
     m_nonzerosblocks = nonzerosblocks;
     if (m_blockSize != Dynamic) {
       m_nonzeros = nonzerosblocks * (m_blockSize * m_blockSize);
       m_blockPtr = 0;
     } else {
       // m_nonzeros  is already computed in setBlockLayout()
       m_blockPtr = new StorageIndex[m_nonzerosblocks + 1];
     }
     m_indices = new StorageIndex[m_nonzerosblocks + 1];
     m_values = new Scalar[m_nonzeros];
   }
References Eigen::Dynamic, eigen_assert, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockPtr, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockSize, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_indices, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_innerBSize, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_nonzeros, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_nonzerosblocks, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerBSize, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerIndex, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_values.
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockStructure(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setFromTriplets().
resize()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > void Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::resize (Index brow, Index bcol) inline
Set the number of rows and columns blocks.
{
     m_innerBSize = IsColMajor ? brow : bcol;
     m_outerBSize = IsColMajor ? bcol : brow;
   }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::IsColMajor, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_innerBSize, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerBSize.
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockStructure().
rows()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::rows () const inline
Returns
the number of rows
{
     //      return blockRows();
     return (IsColMajor ? innerSize() : outerSize());
   }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::innerSize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::IsColMajor, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::outerSize().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockInnerIterator::value(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockInnerIterator::valueRef().
setBlockLayout()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > void Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockLayout (const VectorXi & rowBlocks, const VectorXi & colBlocks) inline
Set the row and column block layouts,.
This function set the size of each row and column block. So this function should be used only for blocks with variable size.
Parameters
rowBlocks : Number of rows per row block
colBlocks : Number of columns per column block
See also
resize(), setBlockSize()
{
     const VectorXi& innerBlocks = IsColMajor ? rowBlocks : colBlocks;
     const VectorXi& outerBlocks = IsColMajor ? colBlocks : rowBlocks;
     eigen_assert(m_innerBSize == innerBlocks.size() && "CHECK THE NUMBER OF ROW OR COLUMN BLOCKS");
     eigen_assert(m_outerBSize == outerBlocks.size() && "CHECK THE NUMBER OF ROW OR COLUMN BLOCKS");
     m_outerBSize = outerBlocks.size();
     //  starting index of blocks... cumulative sums
     m_innerOffset = new StorageIndex[m_innerBSize + 1];
     m_outerOffset = new StorageIndex[m_outerBSize + 1];
     m_innerOffset[0] = 0;
     m_outerOffset[0] = 0;
     std::partial_sum(&innerBlocks[0], &innerBlocks[m_innerBSize - 1] + 1, &m_innerOffset[1]);
     std::partial_sum(&outerBlocks[0], &outerBlocks[m_outerBSize - 1] + 1, &m_outerOffset[1]);
     // Compute the total number of nonzeros
     m_nonzeros = 0;
     for (StorageIndex bj = 0; bj < m_outerBSize; ++bj)
       for (StorageIndex bi = 0; bi < m_innerBSize; ++bi) m_nonzeros += outerBlocks[bj] * innerBlocks[bi];
   }
References eigen_assert, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::innerBlocks(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::IsColMajor, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_innerBSize, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_innerOffset, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_nonzeros, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerBSize, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerOffset, and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::outerBlocks().
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setFromTriplets().
setBlockSize()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > void Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockSize (Index blockSize) inline
set the block size at runtime for fixed-size block layout
Call this only for fixed-size blocks
 { m_blockSize = blockSize; }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockSize.
setBlockStructure()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > template<typename MatrixType > void Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockStructure (const MatrixType & blockPattern) inline
Set the nonzero block pattern of the matrix.
Given a sparse matrix describing the nonzero block pattern, this function prepares the internal pointers for values. After calling this function, any nonzero block (bi, bj) can be set with a simple call to coeffRef(bi,bj).
Warning
Before calling this function, tt is necessary to call either setBlockLayout() (matrices with variable-size blocks) or setBlockSize() (for fixed-size blocks).
Parameters
blockPattern Sparse matrix of boolean elements describing the block structure
See also
setBlockLayout()
setBlockSize()
{
     resize(blockPattern.rows(), blockPattern.cols());
     reserve(blockPattern.nonZeros());
     // Browse the block pattern and set up the various pointers
     m_outerIndex[0] = 0;
     if (m_blockSize == Dynamic) m_blockPtr[0] = 0;
     for (StorageIndex nz = 0; nz < m_nonzeros; ++nz) m_values[nz] = Scalar(0);
     for (StorageIndex bj = 0; bj < m_outerBSize; ++bj) {
       // Browse each outer block
       // First, copy and save the indices of nonzero blocks
       // FIXME : find a way to avoid this ...
       std::vector<int> nzBlockIdx;
       typename MatrixType::InnerIterator it(blockPattern, bj);
       for (; it; ++it) {
         nzBlockIdx.push_back(it.index());
       }
       std::sort(nzBlockIdx.begin(), nzBlockIdx.end());
       // Now, fill block indices and (eventually) pointers to blocks
       for (StorageIndex idx = 0; idx < nzBlockIdx.size(); ++idx) {
         StorageIndex offset = m_outerIndex[bj] + idx;  // offset in m_indices
         m_indices[offset] = nzBlockIdx[idx];
         if (m_blockSize == Dynamic)
           m_blockPtr[offset] = m_blockPtr[offset - 1] + blockInnerSize(nzBlockIdx[idx]) * blockOuterSize(bj);
         // There is no blockPtr for fixed-size blocks... not needed !???
       }
       // Save the pointer to the next outer block
       m_outerIndex[bj + 1] = m_outerIndex[bj] + nzBlockIdx.size();
     }
   }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockInnerSize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockOuterSize(), Eigen::Dynamic, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockPtr, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockSize, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_indices, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_nonzeros, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerBSize, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerIndex, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_values, Mesh_Parameters::nz, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::reserve(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::resize().
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::operator=().
setFromTriplets()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > template<typename InputIterator > void Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setFromTriplets (const InputIterator & begin, const InputIterator & end) inline
Fill values in a matrix from a triplet list.
Each triplet item has a block stored in an Eigen dense matrix. The InputIterator class should provide the functions row(), col() and value()
Note
For fixed-size blocks, call setBlockSize() before this function.
FIXME Do not accept duplicates
{
     eigen_assert((m_innerBSize != 0 && m_outerBSize != 0) && "ZERO BLOCKS, PLEASE CALL resize() before");
     /* First, sort the triplet list
      * FIXME This can be unnecessarily expensive since only the inner indices have to be sorted
      * The best approach is like in SparseMatrix::setFromTriplets()
      */
     internal::TripletComp<InputIterator, IsColMajor> tripletcomp;
     std::sort(begin, end, tripletcomp);
     /* Count the number of rows and column blocks,
      * and the number of nonzero blocks per outer dimension
      */
     VectorXi rowBlocks(m_innerBSize);  // Size of each block row
     VectorXi colBlocks(m_outerBSize);  // Size of each block column
     rowBlocks.setZero();
     colBlocks.setZero();
     VectorXi nzblock_outer(m_outerBSize);  // Number of nz blocks per outer vector
     VectorXi nz_outer(m_outerBSize);       // Number of nz per outer vector...for variable-size blocks
     nzblock_outer.setZero();
     nz_outer.setZero();
     for (InputIterator it(begin); it != end; ++it) {
       eigen_assert(it->row() >= 0 && it->row() < this->blockRows() && it->col() >= 0 && it->col() < this->blockCols());
       eigen_assert((it->value().rows() == it->value().cols() && (it->value().rows() == m_blockSize)) ||
                    (m_blockSize == Dynamic));
       if (m_blockSize == Dynamic) {
         eigen_assert((rowBlocks[it->row()] == 0 || rowBlocks[it->row()] == it->value().rows()) &&
                      "NON CORRESPONDING SIZES FOR ROW BLOCKS");
         eigen_assert((colBlocks[it->col()] == 0 || colBlocks[it->col()] == it->value().cols()) &&
                      "NON CORRESPONDING SIZES FOR COLUMN BLOCKS");
         rowBlocks[it->row()] = it->value().rows();
         colBlocks[it->col()] = it->value().cols();
       }
       nz_outer(IsColMajor ? it->col() : it->row()) += it->value().rows() * it->value().cols();
       nzblock_outer(IsColMajor ? it->col() : it->row())++;
     }
     // Allocate member arrays
     if (m_blockSize == Dynamic) setBlockLayout(rowBlocks, colBlocks);
     StorageIndex nzblocks = nzblock_outer.sum();
     reserve(nzblocks);
     // Temporary markers
     VectorXi block_id(m_outerBSize);  // To be used as a block marker during insertion
     // Setup outer index pointers and markers
     m_outerIndex[0] = 0;
     if (m_blockSize == Dynamic) m_blockPtr[0] = 0;
     for (StorageIndex bj = 0; bj < m_outerBSize; ++bj) {
       m_outerIndex[bj + 1] = m_outerIndex[bj] + nzblock_outer(bj);
       block_id(bj) = m_outerIndex[bj];
       if (m_blockSize == Dynamic) {
         m_blockPtr[m_outerIndex[bj + 1]] = m_blockPtr[m_outerIndex[bj]] + nz_outer(bj);
       }
     }
     // Fill the matrix
     for (InputIterator it(begin); it != end; ++it) {
       StorageIndex outer = IsColMajor ? it->col() : it->row();
       StorageIndex inner = IsColMajor ? it->row() : it->col();
       m_indices[block_id(outer)] = inner;
       StorageIndex block_size = it->value().rows() * it->value().cols();
       StorageIndex nz_marker = blockPtr(block_id[outer]);
       memcpy(&(m_values[nz_marker]), it->value().data(), block_size * sizeof(Scalar));
       if (m_blockSize == Dynamic) {
         m_blockPtr[block_id(outer) + 1] = m_blockPtr[block_id(outer)] + block_size;
       }
       block_id(outer)++;
     }
     // An alternative when the outer indices are sorted...no need to use an array of markers
     //      for(Index bcol = 0; bcol < m_outerBSize; ++bcol)
     //      {
     //      Index id = 0, id_nz = 0, id_nzblock = 0;
     //      for(InputIterator it(begin); it!=end; ++it)
     //      {
     //        while (id<bcol) // one pass should do the job unless there are empty columns
     //        {
     //          id++;
     //          m_outerIndex[id+1]=m_outerIndex[id];
     //        }
     //        m_outerIndex[id+1] += 1;
     //        m_indices[id_nzblock]=brow;
     //        Index block_size = it->value().rows()*it->value().cols();
     //        m_blockPtr[id_nzblock+1] = m_blockPtr[id_nzblock] + block_size;
     //        id_nzblock++;
     //        memcpy(&(m_values[id_nz]),it->value().data(), block_size*sizeof(Scalar));
     //        id_nz += block_size;
     //      }
     //      while(id < m_outerBSize-1) // Empty columns at the end
     //      {
     //        id++;
     //        m_outerIndex[id+1]=m_outerIndex[id];
     //      }
     //      }
   }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockPtr(), Eigen::Dynamic, eigen_assert, Eigen::placeholders::end, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::IsColMajor, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockPtr, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockSize, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_indices, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_innerBSize, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerBSize, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerIndex, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_values, Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::reserve(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockLayout().
valuePtr()
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > BlockScalarReturnType* Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::valuePtr () inline
 { return static_cast<BlockScalarReturnType*>(m_values); }
References Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_values.
Friends And Related Function Documentation
operator<<
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > std::ostream& operator<< (std::ostream & s, const BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & m) friend
{
     for (StorageIndex j = 0; j < m.outerBlocks(); ++j) {
       BlockInnerIterator itb(m, j);
       for (; itb; ++itb) {
         s << "(" << itb.row() << ", " << itb.col() << ")\n";
         s << itb.value() << "\n";
       }
     }
     s << std::endl;
     return s;
   }
swap
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > void swap (BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & first, BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ > & second) friend
{
     std::swap(first.m_innerBSize, second.m_innerBSize);
     std::swap(first.m_outerBSize, second.m_outerBSize);
     std::swap(first.m_innerOffset, second.m_innerOffset);
     std::swap(first.m_outerOffset, second.m_outerOffset);
     std::swap(first.m_nonzerosblocks, second.m_nonzerosblocks);
     std::swap(first.m_nonzeros, second.m_nonzeros);
     std::swap(first.m_values, second.m_values);
     std::swap(first.m_blockPtr, second.m_blockPtr);
     std::swap(first.m_indices, second.m_indices);
     std::swap(first.m_outerIndex, second.m_outerIndex);
     std::swap(first.m_BlockSize, second.m_blockSize);
   }
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::operator=().
Member Data Documentation
m_blockPtr
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > StorageIndex* Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockPtr protected
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockPtr(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockSparseMatrix(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::operator=(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::reserve(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockStructure(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setFromTriplets(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::~BlockSparseMatrix().
m_blockSize
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_blockSize protected
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockInnerIndex(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockInnerSize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockOuterIndex(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockOuterSize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockPtr(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockSparseMatrix(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::innerSize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::innerToBlock(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::operator=(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::outerSize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::outerToBlock(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::reserve(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockSize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockStructure(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setFromTriplets().
m_indices
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > StorageIndex* Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_indices protected
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockSparseMatrix(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::coeff(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::coeffRef(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::innerIndexPtr(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::operator=(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::reserve(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockStructure(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setFromTriplets(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::~BlockSparseMatrix().
m_innerBSize
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_innerBSize protected
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockCols(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockRows(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockSparseMatrix(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::innerBlocks(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::innerSize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::operator=(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::reserve(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::resize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockLayout(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setFromTriplets().
m_innerOffset
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > StorageIndex* Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_innerOffset protected
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockInnerIndex(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockInnerSize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockSparseMatrix(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::innerSize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::innerToBlock(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::operator=(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockLayout(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::~BlockSparseMatrix().
m_nonzeros
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_nonzeros protected
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockSparseMatrix(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::nonZeros(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::operator=(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::reserve(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockLayout(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockStructure().
m_nonzerosblocks
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_nonzerosblocks protected
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockSparseMatrix(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::nonZerosBlocks(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::reserve().
m_outerBSize
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Index Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerBSize protected
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockCols(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockRows(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockSparseMatrix(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::operator=(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::outerBlocks(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::outerSize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::reserve(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::resize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockLayout(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockStructure(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setFromTriplets().
m_outerIndex
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > StorageIndex* Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerIndex protected
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockSparseMatrix(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::coeff(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::coeffRef(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::operator=(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::outerIndexPtr(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::reserve(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockStructure(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setFromTriplets(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::~BlockSparseMatrix().
m_outerOffset
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > StorageIndex* Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_outerOffset protected
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockOuterIndex(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::blockOuterSize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockSparseMatrix(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::outerSize(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::outerToBlock(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockLayout(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::~BlockSparseMatrix().
m_values
template<typename Scalar_ , int _BlockAtCompileTime, int Options_, typename StorageIndex_ > Scalar* Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::m_values protected
Referenced by Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::BlockSparseMatrix(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::coeff(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::coeffRef(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::operator=(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::reserve(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setBlockStructure(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::setFromTriplets(), Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::valuePtr(), and Eigen::BlockSparseMatrix< Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ >::~BlockSparseMatrix().
The documentation for this class was generated from the following file:
BlockSparseMatrix.h