MercuryDPM: time_harmonic_elastic_annulus.cc File Reference
time_harmonic_elastic_annulus.cc File Reference
#include "generic.h"
#include "time_harmonic_linear_elasticity.h"
#include "oomph_crbond_bessel.h"
#include "meshes/annular_mesh.h"
Classes
class AnnularDiskProblem< ELASTICITY_ELEMENT >
Annular disk.
Namespaces
Global_Parameters
Namespace for global parameters.
Functions
TimeHarmonicIsotropicElasticityTensor Global_Parameters::E (Nu)
The elasticity tensor for the solid.
void Global_Parameters::solid_boundary_displacement (const Vector< double > &x, Vector< double > &u)
Real-valued, radial displacement field on inner boundary.
void Global_Parameters::constant_pressure (const Vector< double > &x, const Vector< double > &n, Vector< std::complex< double > > &traction)
Constant pressure load (real and imag part)
double Global_Parameters::BesselY (const double &n, const double &x)
Helper function to evaluate Y_n(x) from bloody maple output.
double Global_Parameters::BesselJ (const double &n, const double &x)
Helper function to evaluate J_n(x) from bloody maple output.
void Global_Parameters::exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector: {u_x_real, u_y_real, u_x_imag, u_y_imag}.
int main (int argc, char **argv)
Driver for annular disk loaded by pressure.
Variables
double Global_Parameters::Displacement_amplitude =0.1
Displacement amplitude on inner radius.
unsigned Global_Parameters::Ntheta =20
Number of elements in azimuthal direction.
Function Documentation
main()
int main (int argc , char ** argv)
Driver for annular disk loaded by pressure.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Number of elements in azimuthal direction
  CommandLineArgs::specify_command_line_flag(
   "--ntheta",
   &Global_Parameters::Ntheta);
  // Number of elements in radial direction
  CommandLineArgs::specify_command_line_flag(
   "--nr",
   &Global_Parameters::Nr);
  // Do have a gap in the annulus?
  CommandLineArgs::specify_command_line_flag("--have_gap");
 #ifdef ADAPTIVE
  // Max. number of adaptations
  unsigned max_adapt=3;
  CommandLineArgs::specify_command_line_flag("--max_adapt",&max_adapt);
  // Number of uniform refinements
  unsigned nrefine=0;
  CommandLineArgs::specify_command_line_flag("--nrefine",&nrefine);
 #endif
  // P increment
  double p_increment=0.1;
  CommandLineArgs::specify_command_line_flag("--p_increment",&p_increment);
  // Number of steps
  unsigned nstep=3;
  CommandLineArgs::specify_command_line_flag("--nstep",&nstep);
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
 #ifdef ADAPTIVE
  //Set up the problem
  AnnularDiskProblem<RefineableQTimeHarmonicLinearElasticityElement<2,3> >
   problem;
  // Refine unformly
  for (unsigned i=0;i<nrefine;i++)
   {
    problem.refine_uniformly();
   }
 #else
  //Set up the problem
  AnnularDiskProblem<QTimeHarmonicLinearElasticityElement<2,3> > problem;
 #endif
  // Initial values for parameter values
  Global_Parameters::P=0.0;
  //Parameter incrementation
  for(unsigned i=0;i<nstep;i++)
   {
 #ifdef ADAPTIVE
    // Solve the problem with Newton's method, allowing
    // up to max_adapt mesh adaptations after every solve.
    problem.newton_solve(max_adapt);
 #else
    // Solve the problem using Newton's method
    problem.newton_solve();
 #endif
    // Doc solution
    problem.doc_solution();
    // Increment pressure
    Global_Parameters::P+=p_increment;
   }
 } //end of main
References oomph::CommandLineArgs::doc_specified_flags(), i, Global_Parameters::Nr, Global_Parameters::Ntheta, Global_Parameters::P, oomph::CommandLineArgs::parse_and_assign(), problem, Flag_definition::setup(), and oomph::CommandLineArgs::specify_command_line_flag().