MercuryDPM: BVH_Example.cpp File Reference
BVH_Example.cpp File Reference
#include <Eigen/StdVector>
#include <unsupported/Eigen/BVH>
#include <iostream>
Classes
struct PointPointMinimizer
Namespaces
Eigen
Namespace containing all symbols from the Eigen library.
Typedefs
typedef AlignedBox< double, 2 > Box2d
Functions
Box2d Eigen::bounding_box (const Vector2d &v)
int main ()
Typedef Documentation
Box2d
typedef AlignedBox<double, 2> Box2d
Function Documentation
main()
int main ()
            {
   typedef std::vector<Vector2d, aligned_allocator<Vector2d> > StdVectorOfVector2d;
   StdVectorOfVector2d redPoints, bluePoints;
   for (int i = 0; i < 100; ++i) {  // initialize random set of red points and blue points
     redPoints.push_back(Vector2d::Random());
     bluePoints.push_back(Vector2d::Random());
   }
   PointPointMinimizer minimizer;
   double minDistSq = std::numeric_limits<double>::max();
   // brute force to find closest red-blue pair
   for (int i = 0; i < (int)redPoints.size(); ++i)
     for (int j = 0; j < (int)bluePoints.size(); ++j)
       minDistSq = std::min(minDistSq, minimizer.minimumOnObjectObject(redPoints[i], bluePoints[j]));
   std::cout << "Brute force distance = " << sqrt(minDistSq) << ", calls = " << minimizer.calls << std::endl;
   // using BVH to find closest red-blue pair
   minimizer.calls = 0;
   KdBVH<double, 2, Vector2d> redTree(redPoints.begin(), redPoints.end()),
       blueTree(bluePoints.begin(), bluePoints.end());    // construct the trees
   minDistSq = BVMinimize(redTree, blueTree, minimizer);  // actual BVH minimization call
   std::cout << "BVH distance         = " << sqrt(minDistSq) << ", calls = " << minimizer.calls << std::endl;
   return 0;
 }
References Eigen::BVMinimize(), PointPointMinimizer::calls, i, int(), j, max, min, PointPointMinimizer::minimumOnObjectObject(), and sqrt().