MercuryDPM: Eigen::internal::generic_j0< T, double > Struct Template Reference
Eigen::internal::generic_j0< T, double > Struct Template Reference
#include <BesselFunctionsImpl.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T run (const T &x)
Member Function Documentation
run()
template<typename T > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T Eigen::internal::generic_j0< T, double >::run (const T & x) inline static
{
     /*  j0.c
      *  Bessel function of order zero
      *
      *
      *
      * SYNOPSIS:
      *
      * double x, y, j0();
      *
      * y = j0( x );
      *
      *
      *
      * DESCRIPTION:
      *
      * Returns Bessel function of order zero of the argument.
      *
      * The domain is divided into the intervals [0, 5] and
      * (5, infinity). In the first interval the following rational
      * approximation is used:
      *
      *
      *        2         2
      * (w - r  ) (w - r  ) P (w) / Q (w)
      *       1         2    3       8
      *
      *            2
      * where w = x  and the two r's are zeros of the function.
      *
      * In the second interval, the Hankel asymptotic expansion
      * is employed with two rational functions of degree 6/6
      * and 7/7.
      *
      *
      *
      * ACCURACY:
      *
      *                      Absolute error:
      * arithmetic   domain     # trials      peak         rms
      *    DEC       0, 30       10000       4.4e-17     6.3e-18
      *    IEEE      0, 30       60000       4.2e-16     1.1e-16
      *
      */
     const double PP[] = {7.96936729297347051624E-4, 8.28352392107440799803E-2, 1.23953371646414299388E0,
                          5.44725003058768775090E0,  8.74716500199817011941E0,  5.30324038235394892183E0,
                          9.99999999999999997821E-1};
     const double PQ[] = {9.24408810558863637013E-4, 8.56288474354474431428E-2, 1.25352743901058953537E0,
                          5.47097740330417105182E0,  8.76190883237069594232E0,  5.30605288235394617618E0,
                          1.00000000000000000218E0};
     const double QP[] = {-1.13663838898469149931E-2, -1.28252718670509318512E0, -1.95539544257735972385E1,
                          -9.32060152123768231369E1,  -1.77681167980488050595E2, -1.47077505154951170175E2,
                          -5.14105326766599330220E1,  -6.05014350600728481186E0};
     const double QQ[] = {1.00000000000000000000E0, 6.43178256118178023184E1, 8.56430025976980587198E2,
                          3.88240183605401609683E3, 7.24046774195652478189E3, 5.93072701187316984827E3,
                          2.06209331660327847417E3, 2.42005740240291393179E2};
     const double RP[] = {-4.79443220978201773821E9, 1.95617491946556577543E12, -2.49248344360967716204E14,
                          9.70862251047306323952E15};
     const double RQ[] = {1.00000000000000000000E0,  4.99563147152651017219E2,  1.73785401676374683123E5,
                          4.84409658339962045305E7,  1.11855537045356834862E10, 2.11277520115489217587E12,
                          3.10518229857422583814E14, 3.18121955943204943306E16, 1.71086294081043136091E18};
     const T DR1 = pset1<T>(5.78318596294678452118E0);
     const T DR2 = pset1<T>(3.04712623436620863991E1);
     const T SQ2OPI = pset1<T>(7.9788456080286535587989E-1); /* sqrt(2 / pi) */
     const T NEG_PIO4 = pset1<T>(-0.7853981633974483096);    /* pi / 4 */
     T y = pabs(x);
     T z = pmul(y, y);
     T y_le_five = pselect(pcmp_lt(y, pset1<T>(1.0e-5)), pmadd(z, pset1<T>(-0.25), pset1<T>(1.0)),
                           pmul(pmul(psub(z, DR1), psub(z, DR2)),
                                pdiv(internal::ppolevl<T, 3>::run(z, RP), internal::ppolevl<T, 8>::run(z, RQ))));
     T s = pdiv(pset1<T>(25.0), z);
     T p = pdiv(internal::ppolevl<T, 6>::run(s, PP), internal::ppolevl<T, 6>::run(s, PQ));
     T q = pdiv(internal::ppolevl<T, 7>::run(s, QP), internal::ppolevl<T, 7>::run(s, QQ));
     T yn = padd(y, NEG_PIO4);
     T w = pdiv(pset1<T>(-5.0), y);
     p = pmadd(p, pcos(yn), pmul(w, pmul(q, psin(yn))));
     T y_gt_five = pmul(p, pmul(SQ2OPI, prsqrt(y)));
     return pselect(pcmp_le(y, pset1<T>(5.0)), y_le_five, y_gt_five);
   }
References p, Eigen::internal::pabs(), Eigen::internal::padd(), Eigen::internal::pcmp_le(), Eigen::internal::pcmp_lt(), Eigen::internal::pcos(), Eigen::internal::pdiv(), Eigen::internal::pmadd(), Eigen::internal::pmul(), Eigen::internal::prsqrt(), Eigen::internal::pselect(), Eigen::internal::psin(), Eigen::internal::psub(), Eigen::numext::q, s, w, plotDoE::x, and Eigen::internal::y.
The documentation for this struct was generated from the following file:
BesselFunctionsImpl.h