MercuryDPM: Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device > Struct Template Reference
#include <TensorStriding.h>
Public Types
enum {
IsAligned = false , PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess , BlockAccess = false , PreferBlockAccess = TensorEvaluator<ArgType, Device>::PreferBlockAccess ,
CoordAccess = false , RawAccess = false
}
typedef TensorStridingOp< Strides, ArgType > XprType
typedef XprType::Index Index
typedef DSizes< Index, NumDims > Dimensions
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorBlockNotImplemented TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC Storage::Type data () const
Static Public Attributes
static constexpr int NumDims = internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Protected Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index srcCoeff (Index index) const
Protected Attributes
Dimensions m_dimensions
array< Index, NumDims > m_outputStrides
array< Index, NumDims > m_inputStrides
TensorEvaluator< ArgType, Device > m_impl
Member Typedef Documentation
CoeffReturnType
template<typename Strides , typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::CoeffReturnType
Dimensions
template<typename Strides , typename ArgType , typename Device > typedef DSizes<Index, NumDims> Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::Dimensions
EvaluatorPointerType
template<typename Strides , typename ArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::EvaluatorPointerType
Index
template<typename Strides , typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::Index
PacketReturnType
template<typename Strides , typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::PacketReturnType
Scalar
template<typename Strides , typename ArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::Scalar
Storage
template<typename Strides , typename ArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::Storage
TensorBlock
template<typename Strides , typename ArgType , typename Device > typedef internal::TensorBlockNotImplemented Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::TensorBlock
XprType
template<typename Strides , typename ArgType , typename Device > typedef TensorStridingOp<Strides, ArgType> Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename Strides , typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = /*TensorEvaluator<ArgType, Device>::IsAligned*/ false,
     PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess,
     BlockAccess = false,
     PreferBlockAccess = TensorEvaluator<ArgType, Device>::PreferBlockAccess,
     CoordAccess = false,  // to be implemented
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename Strides , typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
                                                                                : m_impl(op.expression(), device) {
     m_dimensions = m_impl.dimensions();
     for (int i = 0; i < NumDims; ++i) {
       m_dimensions[i] = Eigen::numext::ceil(static_cast<float>(m_dimensions[i]) / op.strides()[i]);
     }
     const typename TensorEvaluator<ArgType, Device>::Dimensions& input_dims = m_impl.dimensions();
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       m_outputStrides[0] = 1;
       m_inputStrides[0] = 1;
       for (int i = 1; i < NumDims; ++i) {
         m_outputStrides[i] = m_outputStrides[i - 1] * m_dimensions[i - 1];
         m_inputStrides[i] = m_inputStrides[i - 1] * input_dims[i - 1];
         m_inputStrides[i - 1] *= op.strides()[i - 1];
       }
       m_inputStrides[NumDims - 1] *= op.strides()[NumDims - 1];
     } else {  // RowMajor
       m_outputStrides[NumDims - 1] = 1;
       m_inputStrides[NumDims - 1] = 1;
       for (int i = NumDims - 2; i >= 0; --i) {
         m_outputStrides[i] = m_outputStrides[i + 1] * m_dimensions[i + 1];
         m_inputStrides[i] = m_inputStrides[i + 1] * input_dims[i + 1];
         m_inputStrides[i + 1] *= op.strides()[i + 1];
       }
       m_inputStrides[0] *= op.strides()[0];
     }
   }
References Eigen::numext::ceil(), Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), i, Eigen::TensorEvaluator< Derived, Device >::Layout, and op.
Member Function Documentation
cleanup()
template<typename Strides , typename ArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::cleanup () inline
 { m_impl.cleanup(); }
Referenced by framework.Frame::__init__().
coeff()
template<typename Strides , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::coeff (Index index) const inline
{
     return m_impl.coeff(srcCoeff(index));
   }
costPerCoeff()
template<typename Strides , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     double compute_cost = (NumDims - 1) * (TensorOpCost::AddCost<Index>() + TensorOpCost::MulCost<Index>() +
                                            TensorOpCost::DivCost<Index>()) +
                           TensorOpCost::MulCost<Index>();
     if (vectorized) {
       compute_cost *= 2;  // packet() computes two indices
     }
     const int innerDim = (static_cast<int>(Layout) == static_cast<int>(ColMajor)) ? 0 : (NumDims - 1);
     return m_impl.costPerCoeff(vectorized && m_inputStrides[innerDim] == 1) +
            // Computation is not vectorized per se, but it is done once per packet.
            TensorOpCost(0, 0, compute_cost, vectorized, PacketSize);
   }
References Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::Layout, and Eigen::TensorEvaluator< Derived, Device >::PacketSize.
data()
template<typename Strides , typename ArgType , typename Device > EIGEN_DEVICE_FUNC Storage::Type Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename Strides , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::dimensions () const inline
 { return m_dimensions; }
evalSubExprsIfNeeded()
template<typename Strides , typename ArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
{
     m_impl.evalSubExprsIfNeeded(NULL);
     return true;
   }
packet()
template<typename Strides , typename ArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::packet (Index index) const inline
{
     EIGEN_STATIC_ASSERT((PacketSize > 1), YOU_MADE_A_PROGRAMMING_MISTAKE)
     eigen_assert(index + PacketSize - 1 < dimensions().TotalSize());
     Index inputIndices[] = {0, 0};
     Index indices[] = {index, index + PacketSize - 1};
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       EIGEN_UNROLL_LOOP
       for (int i = NumDims - 1; i > 0; --i) {
         const Index idx0 = indices[0] / m_outputStrides[i];
         const Index idx1 = indices[1] / m_outputStrides[i];
         inputIndices[0] += idx0 * m_inputStrides[i];
         inputIndices[1] += idx1 * m_inputStrides[i];
         indices[0] -= idx0 * m_outputStrides[i];
         indices[1] -= idx1 * m_outputStrides[i];
       }
       inputIndices[0] += indices[0] * m_inputStrides[0];
       inputIndices[1] += indices[1] * m_inputStrides[0];
     } else {  // RowMajor
       EIGEN_UNROLL_LOOP
       for (int i = 0; i < NumDims - 1; ++i) {
         const Index idx0 = indices[0] / m_outputStrides[i];
         const Index idx1 = indices[1] / m_outputStrides[i];
         inputIndices[0] += idx0 * m_inputStrides[i];
         inputIndices[1] += idx1 * m_inputStrides[i];
         indices[0] -= idx0 * m_outputStrides[i];
         indices[1] -= idx1 * m_outputStrides[i];
       }
       inputIndices[0] += indices[0] * m_inputStrides[NumDims - 1];
       inputIndices[1] += indices[1] * m_inputStrides[NumDims - 1];
     }
     if (inputIndices[1] - inputIndices[0] == PacketSize - 1) {
       PacketReturnType rslt = m_impl.template packet<Unaligned>(inputIndices[0]);
       return rslt;
     } else {
       EIGEN_ALIGN_MAX std::remove_const_t<CoeffReturnType> values[PacketSize];
       values[0] = m_impl.coeff(inputIndices[0]);
       values[PacketSize - 1] = m_impl.coeff(inputIndices[1]);
       EIGEN_UNROLL_LOOP
       for (int i = 1; i < PacketSize - 1; ++i) {
         values[i] = coeff(index + i);
       }
       PacketReturnType rslt = internal::pload<PacketReturnType>(values);
       return rslt;
     }
   }
References Eigen::TensorEvaluator< Derived, Device >::coeff(), Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), EIGEN_ALIGN_MAX, eigen_assert, EIGEN_STATIC_ASSERT, EIGEN_UNROLL_LOOP, i, Eigen::TensorEvaluator< Derived, Device >::Layout, and Eigen::TensorEvaluator< Derived, Device >::PacketSize.
srcCoeff()
template<typename Strides , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::srcCoeff (Index index) const inline protected
{
     Index inputIndex = 0;
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       EIGEN_UNROLL_LOOP
       for (int i = NumDims - 1; i > 0; --i) {
         const Index idx = index / m_outputStrides[i];
         inputIndex += idx * m_inputStrides[i];
         index -= idx * m_outputStrides[i];
       }
       inputIndex += index * m_inputStrides[0];
     } else {  // RowMajor
       EIGEN_UNROLL_LOOP
       for (int i = 0; i < NumDims - 1; ++i) {
         const Index idx = index / m_outputStrides[i];
         inputIndex += idx * m_inputStrides[i];
         index -= idx * m_outputStrides[i];
       }
       inputIndex += index * m_inputStrides[NumDims - 1];
     }
     return inputIndex;
   }
References Eigen::ColMajor, EIGEN_UNROLL_LOOP, i, and Eigen::TensorEvaluator< Derived, Device >::Layout.
Member Data Documentation
Layout
template<typename Strides , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_dimensions
template<typename Strides , typename ArgType , typename Device > Dimensions Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::m_dimensions protected
m_impl
template<typename Strides , typename ArgType , typename Device > TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::m_impl protected
m_inputStrides
template<typename Strides , typename ArgType , typename Device > array<Index, NumDims> Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::m_inputStrides protected
m_outputStrides
template<typename Strides , typename ArgType , typename Device > array<Index, NumDims> Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::m_outputStrides protected
NumDims
template<typename Strides , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::NumDims = internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value static constexpr
PacketSize
template<typename Strides , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorStridingOp< Strides, ArgType >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorStriding.h