MercuryDPM: oomph::HyprePreconditioner Class Reference
oomph::HyprePreconditioner Class Reference
#include <hypre_solver.h>
Public Member Functions
HyprePreconditioner (const std::string &context_string="")
~HyprePreconditioner ()
Destructor.
HyprePreconditioner (const HyprePreconditioner &)=delete
Broken copy constructor.
void operator= (const HyprePreconditioner &)=delete
Broken assignment operator.
void enable_report_my_cumulative_preconditioner_solve_time ()
Enable reporting of cumulative solve time in destructor.
void disable_report_my_cumulative_preconditioner_solve_time ()
Disable reporting of cumulative solve time in destructor.
void enable_doc_time ()
Enable documentation of preconditioner timings.
void disable_doc_time ()
Disable documentation of preconditioner timings.
unsigned & hypre_method ()
Access function to Hypre_method flag – specified via enumeration.
unsigned & internal_preconditioner ()
void use_BoomerAMG ()
Function to select BoomerAMG as the preconditioner.
void set_amg_iterations (const unsigned &amg_iterations)
Function to set the number of times to apply BoomerAMG.
unsigned & amg_iterations ()
Return function for Max_iter.
void amg_using_simple_smoothing ()
unsigned & amg_simple_smoother ()
Access function to AMG_simple_smoother flag.
void amg_using_complex_smoothing ()
unsigned & amg_complex_smoother ()
Access function to AMG_complex_smoother flag.
bool & amg_using_simple_smoothing_flag ()
Return function for the AMG_using_simple_smoothing_flag.
unsigned & amg_print_level ()
Access function to AMG_print_level.
unsigned & amg_smoother_iterations ()
Access function to AMG_smoother_iterations.
unsigned & amg_coarsening ()
Access function to AMG_coarsening flag.
unsigned & amg_max_levels ()
Access function to AMG_max_levels.
double & amg_damping ()
Access function to AMG_damping parameter.
double & amg_strength ()
Access function to AMG_strength.
double & amg_max_row_sum ()
Access function to AMG_max_row_sum.
double & amg_truncation ()
Access function to AMG_truncation.
void use_ParaSails ()
Function to select ParaSails as the preconditioner.
int & parasails_symmetry ()
Access function to ParaSails symmetry flag.
int & parasails_nlevel ()
Access function to ParaSails nlevel parameter.
double & parasails_thresh ()
Access function to ParaSails thresh parameter.
double & parasails_filter ()
Access function to ParaSails filter parameter.
void use_Euclid ()
Function to select use Euclid as the preconditioner.
double & euclid_droptol ()
Access function to Euclid drop tolerance parameter.
int & euclid_level ()
Access function to Euclid level parameter for ILU(k) factorization.
void enable_euclid_rowScale ()
Enable euclid rowScaling.
void disable_euclid_rowScale ()
Disable euclid row scaling.
void enable_euclid_using_BJ ()
void disable_euclid_using_BJ ()
void euclid_using_ILUK ()
void euclid_using_ILUT ()
unsigned & euclid_print_level ()
void enable_delete_matrix ()
void disable_delete_matrix ()
void setup ()
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Preconditioner_solve uses a hypre solver to precondition vector r.
void clean_up_memory ()
Function deletes all solver data.
Public Member Functions inherited from oomph::Preconditioner
Preconditioner ()
Constructor.
Preconditioner (const Preconditioner &)=delete
Broken copy constructor.
void operator= (const Preconditioner &)=delete
Broken assignment operator.
virtual ~Preconditioner ()
Destructor (empty)
virtual void preconditioner_solve_transpose (const DoubleVector &r, DoubleVector &z)
void setup (DoubleMatrixBase *matrix_pt)
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
void enable_silent_preconditioner_setup ()
Set up the block preconditioner quietly!
void disable_silent_preconditioner_setup ()
Be verbose in the block preconditioner setup.
virtual DoubleMatrixBase * matrix_pt () const
Get function for matrix pointer.
virtual void set_matrix_pt (DoubleMatrixBase *matrix_pt)
Set the matrix pointer.
virtual const OomphCommunicator * comm_pt () const
Get function for comm pointer.
virtual void set_comm_pt (const OomphCommunicator *const comm_pt)
Set the communicator pointer.
double setup_time () const
Returns the time to setup the preconditioner.
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> &doftype_coarsen_map_coarse)
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
void build_distribution (const LinearAlgebraDistribution &dist)
Public Member Functions inherited from oomph::HypreInterface
HypreInterface ()
Constructor.
~HypreInterface ()
Destructor.
HypreInterface (const HypreInterface &)=delete
Broken copy constructor.
void operator= (const HypreInterface &)=delete
Broken assignment operator.
void enable_hypre_error_messages ()
Turn on the hypre error messages.
void disable_hypre_error_messages ()
Turn off hypre error messages.
unsigned existing_solver ()
Function to return value of which solver (if any) is currently stored.
unsigned existing_preconditioner ()
Function return value of which preconditioner (if any) is stored.
Static Public Member Functions
static void report_cumulative_solve_times ()
static void reset_cumulative_solve_times ()
Reset cumulative solve times.
Static Public Attributes
static double Cumulative_preconditioner_solve_time = 0.0
static std::map< std::string, double > Context_based_cumulative_solve_time
static unsigned Cumulative_npreconditioner_solve = 0
static std::map< std::string, unsigned > Context_based_cumulative_npreconditioner_solve
static std::map< std::string, unsigned > Context_based_nrow
Private Attributes
bool Delete_matrix
bool Doc_time
double My_cumulative_preconditioner_solve_time
bool Report_my_cumulative_preconditioner_solve_time
std::string Context_string
String can be used to provide context for annotation.
Additional Inherited Members
Public Types inherited from oomph::HypreInterface
enum Hypre_method_types {
CG , GMRES , BiCGStab , BoomerAMG ,
Euclid , ParaSails , None
}
Public Attributes inherited from oomph::HypreInterface
bool AMGEuclidSmoother_use_block_jacobi
bool AMGEuclidSmoother_use_row_scaling
bool AMGEuclidSmoother_use_ilut
unsigned AMGEuclidSmoother_level
double AMGEuclidSmoother_drop_tol
unsigned AMGEuclidSmoother_print_level
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
Protected Member Functions inherited from oomph::HypreInterface
void hypre_clean_up_memory ()
Function deletes all solver data.
void hypre_matrix_setup (CRDoubleMatrix *matrix_pt)
void hypre_solver_setup ()
void hypre_solve (const DoubleVector &rhs, DoubleVector &solution)
Protected Attributes inherited from oomph::Preconditioner
bool Silent_preconditioner_setup
Boolean to indicate whether or not the build should be done silently.
std::ostream * Stream_pt
Pointer to the output stream – defaults to std::cout.
Protected Attributes inherited from oomph::HypreInterface
bool Output_info
Flag is true to output info and results of timings.
unsigned Max_iter
Maximum number of iterations used in solver.
double Tolerance
Tolerance used to terminate solver.
unsigned Hypre_method
Hypre method flag. Valid values are specified in enumeration.
unsigned Internal_preconditioner
unsigned AMG_print_level
unsigned AMG_max_levels
Maximum number of levels used in AMG.
double AMG_max_row_sum
Parameter to identify diagonally dominant parts of the matrix in AMG.
bool AMG_using_simple_smoothing
unsigned AMG_simple_smoother
unsigned AMG_complex_smoother
unsigned AMG_smoother_iterations
The number of smoother iterations to apply.
double AMG_damping
Damping factor for BoomerAMG smoothed Jacobi or hybrid SOR.
double AMG_strength
Connection strength threshold parameter for BoomerAMG.
double AMG_truncation
Interpolation truncation factor for BoomerAMG.
unsigned AMG_coarsening
int ParaSails_symmetry
int ParaSails_nlevel
ParaSails nlevel parameter.
double ParaSails_thresh
ParaSails thresh parameter.
double ParaSails_filter
ParaSails filter parameter.
double Euclid_droptol
Euclid drop tolerance for ILU(k) and ILUT factorization.
bool Euclid_rowScale
Flag to switch on Euclid row scaling.
bool Euclid_using_ILUT
Flag to determine if ILUT (if true) or ILU(k) is used in Euclid.
bool Euclid_using_BJ
Flag to determine if Block Jacobi is used instead of PILU.
int Euclid_level
Euclid level parameter for ILU(k) factorization.
unsigned Euclid_print_level
unsigned Krylov_print_level
bool Hypre_error_messages
bool Delete_input_data
Detailed Description
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// An Preconditioner class using the suite of Hypre preconditioners to allow
 BoomerAMG (Algebraic Multi Grid),
 Euclid (ILU) or
 ParaSails (Approximate inverse)
to be used for Preconditioner::preconditioner_solve(...). By default BoomerAMG is used.
Constructor & Destructor Documentation
HyprePreconditioner() [1/2]
oomph::HyprePreconditioner::HyprePreconditioner (const std::string & context_string = "") inline
Constructor. Provide optional string that is used in annotation of performance
     {
       Context_string = context_string;
       // Hypre copies matrix data from oomph-lib's CRDoubleMatrix
       // or DistributedCRDoubleMatrix into its own data structures,
       // doubling the memory requirements for the matrix.
       // As far as the Hypre solvers are concerned the oomph-lib matrix
       // is no longer required and could be deleted to save memory.
       // However, this will not be the expected behaviour and therefore
       // needs to be requested explicitly by the user by changing this
       // flag from false (its default) to true.
       Delete_matrix = false;
       // Do we want to output results of timings?
       Doc_time = true;
       // General control paramaters for using HYPRE as preconditioner
       Tolerance = 0.0;
       Max_iter = 1;
       Hypre_method = BoomerAMG;
       Internal_preconditioner = None;
       // Initialise private double that accumulates the preconditioner
       // solve time of thi instantiation of this class. Is reported
       // in destructor if Report_my_cumulative_preconditioner_solve_time
       // is set to true
       My_cumulative_preconditioner_solve_time = 0.0;
       Report_my_cumulative_preconditioner_solve_time = false;
     }
References oomph::HypreInterface::BoomerAMG, Context_string, Delete_matrix, Doc_time, oomph::HypreInterface::Hypre_method, oomph::HypreInterface::Internal_preconditioner, oomph::HypreInterface::Max_iter, My_cumulative_preconditioner_solve_time, oomph::HypreInterface::None, Report_my_cumulative_preconditioner_solve_time, and oomph::HypreInterface::Tolerance.
~HyprePreconditioner()
oomph::HyprePreconditioner::~HyprePreconditioner () inline
Destructor.
     {
       if (Report_my_cumulative_preconditioner_solve_time)
       {
         oomph_info << "~HyprePreconditioner() in context \" " << Context_string
                    << "\": My_cumulative_preconditioner_solve_time = "
                    << My_cumulative_preconditioner_solve_time << std::endl;
       }
     }
References Context_string, My_cumulative_preconditioner_solve_time, oomph::oomph_info, and Report_my_cumulative_preconditioner_solve_time.
HyprePreconditioner() [2/2]
oomph::HyprePreconditioner::HyprePreconditioner (const HyprePreconditioner &) delete
Broken copy constructor.
Member Function Documentation
amg_coarsening()
unsigned& oomph::HyprePreconditioner::amg_coarsening () inline
Access function to AMG_coarsening flag.
     {
       return AMG_coarsening;
     }
References oomph::HypreInterface::AMG_coarsening.
Referenced by oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg2v22_for_3D_momentum(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_2D_momentum_simple_visc(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_2D_momentum_stressdiv_visc(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_2D_poisson_problem(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_3D_momentum(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_3D_poisson_problem(), oomph::Hypre_default_settings::set_defaults_for_2D_poisson_problem(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::set_pseudo_elastic_fsi_solver(), and set_pseudo_elastic_fsi_solver().
amg_complex_smoother()
unsigned& oomph::HyprePreconditioner::amg_complex_smoother () inline
Access function to AMG_complex_smoother flag.
     {
       return AMG_complex_smoother;
     }
References oomph::HypreInterface::AMG_complex_smoother.
amg_damping()
double& oomph::HyprePreconditioner::amg_damping () inline
Access function to AMG_damping parameter.
     {
       return AMG_damping;
     }
References oomph::HypreInterface::AMG_damping.
Referenced by oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg2v22_for_3D_momentum(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_2D_momentum_simple_visc(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_2D_momentum_stressdiv_visc(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_2D_poisson_problem(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_3D_momentum(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_3D_poisson_problem(), main(), and oomph::Hypre_default_settings::set_defaults_for_navier_stokes_momentum_block().
amg_iterations()
unsigned& oomph::HyprePreconditioner::amg_iterations () inline
Return function for Max_iter.
     {
       return Max_iter;
     }
References oomph::HypreInterface::Max_iter.
Referenced by set_amg_iterations().
amg_max_levels()
unsigned& oomph::HyprePreconditioner::amg_max_levels () inline
Access function to AMG_max_levels.
     {
       return AMG_max_levels;
     }
References oomph::HypreInterface::AMG_max_levels.
amg_max_row_sum()
double& oomph::HyprePreconditioner::amg_max_row_sum () inline
Access function to AMG_max_row_sum.
     {
       return AMG_max_row_sum;
     }
References oomph::HypreInterface::AMG_max_row_sum.
amg_print_level()
unsigned& oomph::HyprePreconditioner::amg_print_level () inline
Access function to AMG_print_level.
     {
       return AMG_print_level;
     }
References oomph::HypreInterface::AMG_print_level.
amg_simple_smoother()
unsigned& oomph::HyprePreconditioner::amg_simple_smoother () inline
Access function to AMG_simple_smoother flag.
     {
       return AMG_simple_smoother;
     }
References oomph::HypreInterface::AMG_simple_smoother.
Referenced by oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg2v22_for_3D_momentum(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_2D_momentum_simple_visc(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_2D_momentum_stressdiv_visc(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_2D_poisson_problem(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_3D_momentum(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_3D_poisson_problem(), main(), oomph::Hypre_default_settings::set_defaults_for_2D_poisson_problem(), oomph::Hypre_default_settings::set_defaults_for_navier_stokes_momentum_block(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::set_pseudo_elastic_fsi_solver(), and set_pseudo_elastic_fsi_solver().
amg_smoother_iterations()
unsigned& oomph::HyprePreconditioner::amg_smoother_iterations () inline
Access function to AMG_smoother_iterations.
     {
       return AMG_smoother_iterations;
     }
References oomph::HypreInterface::AMG_smoother_iterations.
Referenced by oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg2v22_for_3D_momentum(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_2D_momentum_simple_visc(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_2D_momentum_stressdiv_visc(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_2D_poisson_problem(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_3D_momentum(), and oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_3D_poisson_problem().
amg_strength()
double& oomph::HyprePreconditioner::amg_strength () inline
Access function to AMG_strength.
     {
       return AMG_strength;
     }
References oomph::HypreInterface::AMG_strength.
Referenced by oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg2v22_for_3D_momentum(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_2D_momentum_simple_visc(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_2D_momentum_stressdiv_visc(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_2D_poisson_problem(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_3D_momentum(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_3D_poisson_problem(), main(), oomph::Hypre_default_settings::set_defaults_for_2D_poisson_problem(), oomph::Hypre_default_settings::set_defaults_for_3D_poisson_problem(), oomph::Hypre_default_settings::set_defaults_for_navier_stokes_momentum_block(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::set_pseudo_elastic_fsi_solver(), and set_pseudo_elastic_fsi_solver().
amg_truncation()
double& oomph::HyprePreconditioner::amg_truncation () inline
Access function to AMG_truncation.
     {
       return AMG_truncation;
     }
References oomph::HypreInterface::AMG_truncation.
amg_using_complex_smoothing()
void oomph::HyprePreconditioner::amg_using_complex_smoothing () inline
Function to select use of 'complex' AMG smoothers as controlled by the flag AMG_complex_smoother
     {
       AMG_using_simple_smoothing = false;
     }
References oomph::HypreInterface::AMG_using_simple_smoothing.
amg_using_simple_smoothing()
void oomph::HyprePreconditioner::amg_using_simple_smoothing () inline
Function to select use of 'simple' AMG smoothers as controlled by the flag AMG_simple_smoother
     {
       AMG_using_simple_smoothing = true;
     }
References oomph::HypreInterface::AMG_using_simple_smoothing.
Referenced by main(), oomph::Hypre_default_settings::set_defaults_for_2D_poisson_problem(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::set_pseudo_elastic_fsi_solver(), and set_pseudo_elastic_fsi_solver().
amg_using_simple_smoothing_flag()
bool& oomph::HyprePreconditioner::amg_using_simple_smoothing_flag () inline
Return function for the AMG_using_simple_smoothing_flag.
     {
       return AMG_using_simple_smoothing;
     }
References oomph::HypreInterface::AMG_using_simple_smoothing.
clean_up_memory()
void oomph::HyprePreconditioner::clean_up_memory () virtual
Function deletes all solver data.
clean_up_memory() deletes any existing Hypre solver and Hypre matrix
Reimplemented from oomph::Preconditioner.
   {
     hypre_clean_up_memory();
   }
References oomph::HypreInterface::hypre_clean_up_memory().
Referenced by setup().
disable_delete_matrix()
void oomph::HyprePreconditioner::disable_delete_matrix () inline
Hypre copies matrix data from oomph-lib's CRDoubleMatrix or DistributedCRDoubleMatrix into its own data structures, doubling the memory requirements for the matrix. Calling this function ensures that the matrix is not deleted.
     {
       Delete_matrix = false;
     }
References Delete_matrix.
disable_doc_time()
void oomph::HyprePreconditioner::disable_doc_time () inline
Disable documentation of preconditioner timings.
     {
       Doc_time = false;
     }
References Doc_time.
Referenced by FSIChannelWithLeafletProblem< ELEMENT >::FSIChannelWithLeafletProblem(), PreconditionedFSICollapsibleChannelProblem< ELEMENT >::PreconditionedFSICollapsibleChannelProblem(), FSIChannelWithLeafletProblem< ELEMENT >::set_iterative_solver(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::set_pseudo_elastic_fsi_solver(), set_pseudo_elastic_fsi_solver(), and TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem().
disable_euclid_rowScale()
void oomph::HyprePreconditioner::disable_euclid_rowScale () inline
Disable euclid row scaling.
     {
       Euclid_rowScale = false;
     }
References oomph::HypreInterface::Euclid_rowScale.
disable_euclid_using_BJ()
void oomph::HyprePreconditioner::disable_euclid_using_BJ () inline
Disable use of Block Jacobi, so PILU will be used
     {
       Euclid_using_BJ = false;
     }
References oomph::HypreInterface::Euclid_using_BJ.
disable_report_my_cumulative_preconditioner_solve_time()
void oomph::HyprePreconditioner::disable_report_my_cumulative_preconditioner_solve_time () inline
Disable reporting of cumulative solve time in destructor.
     {
       Report_my_cumulative_preconditioner_solve_time = false;
     }
References Report_my_cumulative_preconditioner_solve_time.
enable_delete_matrix()
void oomph::HyprePreconditioner::enable_delete_matrix () inline
Hypre copies matrix data from oomph-lib's CRDoubleMatrix or DistributedCRDoubleMatrix into its own data structures, doubling the memory requirements for the matrix. As far as the Hypre solvers are concerned the oomph-lib matrix is no longer required and could be deleted to save memory. However, this will not be the expected behaviour and therefore needs to be requested explicitly by the user by calling this function which changes the flag from false (its default) to true.
     {
       Delete_matrix = true;
     }
References Delete_matrix.
enable_doc_time()
void oomph::HyprePreconditioner::enable_doc_time () inline
Enable documentation of preconditioner timings.
     {
       Doc_time = true;
     }
References Doc_time.
enable_euclid_rowScale()
void oomph::HyprePreconditioner::enable_euclid_rowScale () inline
Enable euclid rowScaling.
     {
       Euclid_rowScale = true;
     }
References oomph::HypreInterface::Euclid_rowScale.
enable_euclid_using_BJ()
void oomph::HyprePreconditioner::enable_euclid_using_BJ () inline
Enable use of Block Jacobi as opposed to PILU
     {
       Euclid_using_BJ = true;
     }
References oomph::HypreInterface::Euclid_using_BJ.
enable_report_my_cumulative_preconditioner_solve_time()
void oomph::HyprePreconditioner::enable_report_my_cumulative_preconditioner_solve_time () inline
Enable reporting of cumulative solve time in destructor.
     {
       Report_my_cumulative_preconditioner_solve_time = true;
     }
References Report_my_cumulative_preconditioner_solve_time.
euclid_droptol()
double& oomph::HyprePreconditioner::euclid_droptol () inline
Access function to Euclid drop tolerance parameter.
     {
       return Euclid_droptol;
     }
References oomph::HypreInterface::Euclid_droptol.
euclid_level()
int& oomph::HyprePreconditioner::euclid_level () inline
Access function to Euclid level parameter for ILU(k) factorization.
     {
       return Euclid_level;
     }
References oomph::HypreInterface::Euclid_level.
euclid_print_level()
unsigned& oomph::HyprePreconditioner::euclid_print_level () inline
Function to set the level of printing from Euclid when the Euclid destructor is called 0: no printing (default) 1: prints summary of runtime settings and timings 2: as 1 plus prints memory usage
     {
       return Euclid_print_level;
     }
References oomph::HypreInterface::Euclid_print_level.
euclid_using_ILUK()
void oomph::HyprePreconditioner::euclid_using_ILUK () inline
Function to switch on ILU(k) factorization for Euclid (default is ILU(k) factorization)
     {
       Euclid_using_ILUT = false;
     }
References oomph::HypreInterface::Euclid_using_ILUT.
euclid_using_ILUT()
void oomph::HyprePreconditioner::euclid_using_ILUT () inline
Function to switch on ILUT factorization for Euclid (default is ILU(k) factorization)
     {
       Euclid_using_ILUT = true;
     }
References oomph::HypreInterface::Euclid_using_ILUT.
hypre_method()
unsigned& oomph::HyprePreconditioner::hypre_method () inline
Access function to Hypre_method flag – specified via enumeration.
     {
       return Hypre_method;
     }
References oomph::HypreInterface::Hypre_method.
Referenced by main(), oomph::Hypre_default_settings::set_defaults_for_2D_poisson_problem(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::set_pseudo_elastic_fsi_solver(), and set_pseudo_elastic_fsi_solver().
internal_preconditioner()
unsigned& oomph::HyprePreconditioner::internal_preconditioner () inline
Access function to Internal_preconditioner flag – specified via enumeration.
     {
       return Internal_preconditioner;
     }
References oomph::HypreInterface::Internal_preconditioner.
operator=()
void oomph::HyprePreconditioner::operator= (const HyprePreconditioner &) delete
Broken assignment operator.
parasails_filter()
double& oomph::HyprePreconditioner::parasails_filter () inline
Access function to ParaSails filter parameter.
     {
       return ParaSails_filter;
     }
References oomph::HypreInterface::ParaSails_filter.
parasails_nlevel()
int& oomph::HyprePreconditioner::parasails_nlevel () inline
Access function to ParaSails nlevel parameter.
     {
       return ParaSails_nlevel;
     }
References oomph::HypreInterface::ParaSails_nlevel.
parasails_symmetry()
int& oomph::HyprePreconditioner::parasails_symmetry () inline
Access function to ParaSails symmetry flag.
     {
       return ParaSails_symmetry;
     }
References oomph::HypreInterface::ParaSails_symmetry.
parasails_thresh()
double& oomph::HyprePreconditioner::parasails_thresh () inline
Access function to ParaSails thresh parameter.
     {
       return ParaSails_thresh;
     }
References oomph::HypreInterface::ParaSails_thresh.
preconditioner_solve()
void oomph::HyprePreconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) virtual
Preconditioner_solve uses a hypre solver to precondition vector r.
Function applies solver to vector r for preconditioning. This requires a call to setup(...) first. Note: Hypre copies matrix data from oomph-lib's CRDoubleMatrix or DistributedCRDoubleMatrix into its own data structures, doubling the memory requirements for the matrix. As far as the Hypre solvers are concerned, the oomph-lib matrix is no longer required and could be deleted to save memory. However, this will not be the expected behaviour and therefore needs to be requested explicitly by the user with the delete_matrix() function.
Implements oomph::Preconditioner.
   {
     // Store time
     double t_start = TimingHelpers::timer();
 #ifdef PARANOID
     // check solver data exists
     if (existing_solver() == None)
     {
       std::ostringstream error_message;
       error_message << "preconditioner_solve(...) requires that data has "
                     << "been set up using the function setup(...)" << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // check that rhs has the same distribution as the matrix (now stored
     // in Distribution_pt)
     if (*this->distribution_pt() != *r.distribution_pt())
     {
       std::ostringstream error_message;
       error_message << "The distribution of the rhs vector and the matrix "
                     << " must be the same" << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // if the solution is setup make sure it has the same distribution as
     // the matrix as well
     if (z.built())
     {
       if (*this->distribution_pt() != *z.distribution_pt())
       {
         std::ostringstream error_message;
         error_message << "The distribution of the solution vector is setup "
                       << "there it must be the same as the matrix."
                       << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
     }
 #endif
     // Switch off any timings for the solve
     Output_info = false;
     // perform hypre_solve
     hypre_solve(r, z);
     // Add to cumulative solve time
     double t_end = TimingHelpers::timer();
     Cumulative_preconditioner_solve_time += (t_end - t_start);
     Cumulative_npreconditioner_solve++;
     My_cumulative_preconditioner_solve_time += (t_end - t_start);
     if (Context_string != "")
     {
       Context_based_cumulative_solve_time[Context_string] += (t_end - t_start);
       Context_based_cumulative_npreconditioner_solve[Context_string]++;
     }
   }
References oomph::DoubleVector::built(), Context_based_cumulative_npreconditioner_solve, Context_based_cumulative_solve_time, Context_string, Cumulative_npreconditioner_solve, Cumulative_preconditioner_solve_time, oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::HypreInterface::existing_solver(), oomph::HypreInterface::hypre_solve(), My_cumulative_preconditioner_solve_time, oomph::HypreInterface::None, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::HypreInterface::Output_info, UniformPSDSelfTest::r, and oomph::TimingHelpers::timer().
report_cumulative_solve_times()
void oomph::HyprePreconditioner::report_cumulative_solve_times () static
Report cumulative solve times of all instantiations of this class
   {
     oomph_info << "\n\n=====================================================\n";
     oomph_info << "Cumulative HyprePreconditioner solve time "
                << HyprePreconditioner::Cumulative_preconditioner_solve_time
                << " for " << Cumulative_npreconditioner_solve << " solves";
     if (Cumulative_npreconditioner_solve != 0)
     {
       oomph_info << " ( "
                  << HyprePreconditioner::Cumulative_preconditioner_solve_time /
                       double(Cumulative_npreconditioner_solve)
                  << " per solve )";
     }
     oomph_info << std::endl << std::endl;
     if (Context_based_cumulative_solve_time.size() > 0)
     {
       oomph_info << "Breakdown by context: " << std::endl;
       for (std::map<std::string, double>::iterator it =
              Context_based_cumulative_solve_time.begin();
            it != Context_based_cumulative_solve_time.end();
            it++)
       {
         oomph_info
           << (*it).first << " " << (*it).second << " for "
           << Context_based_cumulative_npreconditioner_solve[(*it).first]
           << " solves";
         if (Context_based_cumulative_npreconditioner_solve[(*it).first] != 0)
         {
           oomph_info
             << " ( "
             << (*it).second /
                  double(
                    Context_based_cumulative_npreconditioner_solve[(*it).first])
             << " per solve; "
             << (*it).second /
                  double(
                    Context_based_cumulative_npreconditioner_solve[(*it)
                                                                     .first]) /
                  double(Context_based_nrow[(*it).first])
             << " per solve per dof )";
         }
         oomph_info << std::endl;
       }
     }
     oomph_info << "\n=====================================================\n";
     oomph_info << std::endl;
   }
References Context_based_cumulative_npreconditioner_solve, Context_based_cumulative_solve_time, Context_based_nrow, Cumulative_npreconditioner_solve, Cumulative_preconditioner_solve_time, and oomph::oomph_info.
reset_cumulative_solve_times()
void oomph::HyprePreconditioner::reset_cumulative_solve_times () static
Reset cumulative solve times.
   {
     Cumulative_preconditioner_solve_time = 0.0;
     Context_based_cumulative_solve_time.clear();
     Cumulative_npreconditioner_solve = 0;
     Context_based_cumulative_npreconditioner_solve.clear();
     Context_based_nrow.clear();
   }
References Context_based_cumulative_npreconditioner_solve, Context_based_cumulative_solve_time, Context_based_nrow, Cumulative_npreconditioner_solve, and Cumulative_preconditioner_solve_time.
set_amg_iterations()
void oomph::HyprePreconditioner::set_amg_iterations (const unsigned & amg_iterations) inline
Function to set the number of times to apply BoomerAMG.
     {
       Max_iter = amg_iterations;
     }
References amg_iterations(), and oomph::HypreInterface::Max_iter.
Referenced by oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg2v22_for_3D_momentum(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_2D_momentum_simple_visc(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_2D_momentum_stressdiv_visc(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_2D_poisson_problem(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_3D_momentum(), oomph::Lagrange_Enforced_Flow_Preconditioner_Subsidiary_Operator_Helper::boomer_amg_for_3D_poisson_problem(), main(), oomph::Hypre_default_settings::set_defaults_for_2D_poisson_problem(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::set_pseudo_elastic_fsi_solver(), and set_pseudo_elastic_fsi_solver().
setup()
void oomph::HyprePreconditioner::setup () virtual
Function to set up a preconditioner for the linear system defined by matrix_pt. This function is required when preconditioning and must be called before using the preconditioner_solve(...) function. This interface allows HyprePreconditioner to be used as a Preconditioner object for oomph-lib's own IterativeLinearSolver class. Note: matrix_pt must point to an object of type CRDoubleMatrix or DistributedCRDoubleMatrix. Note: Hypre copies matrix data from oomph-lib's CRDoubleMatrix and DistributedCRDoubleMatrix into its own data structures, doubling the memory requirements for the matrix. As far as the Hypre solvers are concerned, the oomph-lib matrix is no longer required and could be deleted to save memory. However, this will not be the expected behaviour and therefore needs to be requested explicitly by the user by calling the enable_delete_matrix() function.
An interface to allow HypreSolver to be used as a Preconditioner for the oomph-lib IterativeLinearSolver class. Matrix has to be of type CRDoubleMatrix or DistributedCRDoubleMatrix.
Implements oomph::Preconditioner.
   {
     // Set Output_info flag for HypreInterface
     Output_info = Doc_time;
 #ifdef PARANOID
     // check the matrix is square
     if (matrix_pt()->nrow() != matrix_pt()->ncol())
     {
       std::ostringstream error_message;
       error_message << "HyprePreconditioner require a square matrix. "
                     << "Matrix is " << matrix_pt()->nrow() << " by "
                     << matrix_pt()->ncol() << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // clean up any previous solver data
     clean_up_memory();
     // set flag to decide if oomphlib matrix can be deleted
     // (Recall that Delete_matrix defaults to false).
     Delete_input_data = Delete_matrix;
     // Try casting to a CRDoubleMatrix
     CRDoubleMatrix* cr_matrix_pt = dynamic_cast<CRDoubleMatrix*>(matrix_pt());
     // If cast successful set things up for a serial solve
     if (cr_matrix_pt)
     {
       this->build_distribution(cr_matrix_pt->distribution_pt());
       hypre_matrix_setup(cr_matrix_pt);
     }
     else
     {
 #ifdef PARANOID
       std::ostringstream error_message;
       error_message << "HyprePreconditioner only work with "
                     << "CRDoubleMatrix matrices" << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
 #endif
     }
     if (Context_string != "")
     {
       oomph_info << "Setup of HyprePreconditioner in context \" "
                  << Context_string << "\": nrow, nrow_local, nnz "
                  << cr_matrix_pt->nrow() << " " << cr_matrix_pt->nrow_local()
                  << " " << cr_matrix_pt->nnz() << std::endl;
     }
     Context_based_nrow[Context_string] = cr_matrix_pt->nrow();
     // call hypre_solver_setup
     hypre_solver_setup();
   }
References oomph::DistributableLinearAlgebraObject::build_distribution(), clean_up_memory(), Context_based_nrow, Context_string, oomph::HypreInterface::Delete_input_data, Delete_matrix, oomph::DistributableLinearAlgebraObject::distribution_pt(), Doc_time, oomph::HypreInterface::hypre_matrix_setup(), oomph::HypreInterface::hypre_solver_setup(), oomph::Preconditioner::matrix_pt(), oomph::DoubleMatrixBase::ncol(), oomph::CRDoubleMatrix::nnz(), oomph::DistributableLinearAlgebraObject::nrow(), oomph::CRDoubleMatrix::nrow(), oomph::DoubleMatrixBase::nrow(), oomph::DistributableLinearAlgebraObject::nrow_local(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, and oomph::HypreInterface::Output_info.
use_BoomerAMG()
void oomph::HyprePreconditioner::use_BoomerAMG () inline
Function to select BoomerAMG as the preconditioner.
     {
       Hypre_method = BoomerAMG;
     }
References oomph::HypreInterface::BoomerAMG, and oomph::HypreInterface::Hypre_method.
Referenced by main().
use_Euclid()
void oomph::HyprePreconditioner::use_Euclid () inline
Function to select use Euclid as the preconditioner.
     {
       Hypre_method = Euclid;
     }
References oomph::HypreInterface::Euclid, and oomph::HypreInterface::Hypre_method.
use_ParaSails()
void oomph::HyprePreconditioner::use_ParaSails () inline
Function to select ParaSails as the preconditioner.
     {
       Hypre_method = ParaSails;
     }
References oomph::HypreInterface::Hypre_method, and oomph::HypreInterface::ParaSails.
Member Data Documentation
Context_based_cumulative_npreconditioner_solve
std::map< std::string, unsigned > oomph::HyprePreconditioner::Context_based_cumulative_npreconditioner_solve static
Static unsigned that accumulates the number of preconditioner solves of all instantiations of this class, labeled by context string. Reset it manually, e.g. after every Newton solve, using reset_cumulative_solve_times().
Referenced by preconditioner_solve(), report_cumulative_solve_times(), and reset_cumulative_solve_times().
Context_based_cumulative_solve_time
std::map< std::string, double > oomph::HyprePreconditioner::Context_based_cumulative_solve_time static
Static double that accumulates the preconditioner solve time of all instantiations of this class, labeled by context string. Reset it manually, e.g. after every Newton solve, using reset_cumulative_solve_times().
map of static doubles that accumulates the preconditioner solve time of all instantiations of this class, labeled by context string. Reset it manually, e.g. after every Newton solve, using reset_cumulative_solve_times().
Referenced by preconditioner_solve(), report_cumulative_solve_times(), and reset_cumulative_solve_times().
Context_based_nrow
std::map< std::string, unsigned > oomph::HyprePreconditioner::Context_based_nrow static
Static unsigned that stores nrow for the most recent instantiations of this class, labeled by context string. Reset it manually, e.g. after every Newton solve, using reset_cumulative_solve_times().
Referenced by report_cumulative_solve_times(), reset_cumulative_solve_times(), and setup().
Context_string
std::string oomph::HyprePreconditioner::Context_string private
String can be used to provide context for annotation.
Referenced by HyprePreconditioner(), preconditioner_solve(), setup(), and ~HyprePreconditioner().
Cumulative_npreconditioner_solve
unsigned oomph::HyprePreconditioner::Cumulative_npreconditioner_solve = 0 static
Static unsigned that accumulates the number of preconditioner solves of all instantiations of this class. Reset it manually, e.g. after every Newton solve, using reset_cumulative_solve_times().
Referenced by preconditioner_solve(), report_cumulative_solve_times(), and reset_cumulative_solve_times().
Cumulative_preconditioner_solve_time
double oomph::HyprePreconditioner::Cumulative_preconditioner_solve_time = 0.0 static
Static double that accumulates the preconditioner solve time of all instantiations of this class. Reset it manually, e.g. after every Newton solve, using reset_cumulative_solve_times().
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Static double that accumulates the preconditioner solve time of all instantiations of this class. Reset it manually, e.g. after every Newton solve, using reset_cumulative_solve_times().
Referenced by preconditioner_solve(), report_cumulative_solve_times(), and reset_cumulative_solve_times().
Delete_matrix
bool oomph::HyprePreconditioner::Delete_matrix private
Hypre copies matrix data from oomph-lib's CRDoubleMatrix or DistributedCRDoubleMatrix into its own data structures, doubling the memory requirements for the matrix. As far as the Hypre solvers are concerned the oomph-lib matrix is no longer required and could be deleted to save memory. However, this will not be the expected behaviour and therefore needs to be requested explicitly by the user by changing this flag from false (its default) to true.
Referenced by disable_delete_matrix(), enable_delete_matrix(), HyprePreconditioner(), and setup().
Doc_time
bool oomph::HyprePreconditioner::Doc_time private
Referenced by disable_doc_time(), enable_doc_time(), HyprePreconditioner(), and setup().
My_cumulative_preconditioner_solve_time
double oomph::HyprePreconditioner::My_cumulative_preconditioner_solve_time private
Private double that accumulates the preconditioner solve time of thi instantiation of this class. Is reported in destructor if Report_my_cumulative_preconditioner_solve_time is set to true
Referenced by HyprePreconditioner(), preconditioner_solve(), and ~HyprePreconditioner().
Report_my_cumulative_preconditioner_solve_time
bool oomph::HyprePreconditioner::Report_my_cumulative_preconditioner_solve_time private
Bool to request report of My_cumulative_preconditioner_solve_time in destructor
Referenced by disable_report_my_cumulative_preconditioner_solve_time(), enable_report_my_cumulative_preconditioner_solve_time(), HyprePreconditioner(), and ~HyprePreconditioner().
The documentation for this class was generated from the following files:
hypre_solver.h
hypre_solver.cc