MercuryDPM: Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV3D > Struct Template Reference
Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV3D > Struct Template Reference
#include <TensorConvolutionSycl.h>
Public Types
typedef cl::sycl::accessor< CoeffReturnType, 1, cl::sycl::access::mode::read_write, cl::sycl::access::target::local > Local_accessor
Public Member Functions
EigenConvolutionKernel (Local_accessor local_acc_, Evaluator device_evaluator_, Kernel_accessor kernel_filter_, Buffer_accessor buffer_acc_, internal::IndexMapper< Index, InputDims, 3, Evaluator::Layout > indexMapper_, const cl::sycl::range< 3 > kernel_size_, const cl::sycl::range< 3 > input_range_, const size_t numP_)
template<typename BooleanDim3 >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool boundary_check (const BooleanDim3 boolean_check) const
void operator() (cl::sycl::nd_item< 3 > itemID) const
Public Attributes
Local_accessor local_acc
Evaluator device_evaluator
Kernel_accessor kernel_filter
Buffer_accessor buffer_acc
internal::IndexMapper< Index, InputDims, 3, Evaluator::Layout > indexMapper
const cl::sycl::range< 3 > kernel_size
const cl::sycl::range< 3 > input_range
const size_t numP
Member Typedef Documentation
Local_accessor
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > typedef cl::sycl::accessor<CoeffReturnType, 1, cl::sycl::access::mode::read_write, cl::sycl::access::target::local> Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV3D >::Local_accessor
Constructor & Destructor Documentation
EigenConvolutionKernel()
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV3D >::EigenConvolutionKernel (Local_accessor local_acc_, Evaluator device_evaluator_, Kernel_accessor kernel_filter_, Buffer_accessor buffer_acc_, internal::IndexMapper< Index, InputDims, 3, Evaluator::Layout > indexMapper_, const cl::sycl::range< 3 > kernel_size_, const cl::sycl::range< 3 > input_range_, const size_t numP_) inline
       : local_acc(local_acc_),
         device_evaluator(device_evaluator_),
         kernel_filter(kernel_filter_),
         buffer_acc(buffer_acc_),
         indexMapper(indexMapper_),
         kernel_size(kernel_size_),
         input_range(input_range_),
         numP(numP_) {}
Member Function Documentation
boundary_check()
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > template<typename BooleanDim3 > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV3D >::boundary_check (const BooleanDim3 boolean_check) const inline
{
     return (boolean_check[0] && boolean_check[1] && boolean_check[2]);
   }
operator()()
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > void Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV3D >::operator() (cl::sycl::nd_item< 3 > itemID) const inline
fill the shared memory
{
     auto buffer_ptr = buffer_acc;
     auto kernel_ptr = kernel_filter;
     const auto num_input = cl::sycl::range<3>{itemID.get_local_range() + kernel_size - 1};
     const auto input_offset = cl::sycl::range<3>{itemID.get_group().get_id() * itemID.get_local_range()};
     const auto output_offset =
         cl::sycl::range<3>{itemID.get_group().get_id() * itemID.get_local_range() + itemID.get_local_id()};
     for (size_t p = 0; p < numP; p++) {
       const size_t plane_input_offset = indexMapper.mapGpuInputPlaneToTensorInputOffset(p);
       for (size_t k = itemID.get_local_id(2); k < num_input[2]; k += itemID.get_local_range()[2]) {
         size_t local_index_dim2 = num_input[0] * num_input[1] * k;
         bool cond_k_dim = (k + input_offset[2] < (input_range[2] + kernel_size[2] - 1));
         for (size_t j = itemID.get_local_id(1); j < num_input[1]; j += itemID.get_local_range()[1]) {
           bool cond_j_dim = cond_k_dim && (j + input_offset[1] < (input_range[1] + kernel_size[1] - 1));
           size_t local_index_dim1 = (num_input[0] * j) + local_index_dim2;
           for (size_t i = itemID.get_local_id(0); i < num_input[0]; i += itemID.get_local_range()[0]) {
             bool conds = cond_j_dim && (i + input_offset[0] < (input_range[0] + kernel_size[0] - 1));
             const size_t local_index = local_index_dim1 + i;
             const size_t tensor_index =
                 plane_input_offset + indexMapper.mapGpuInputKernelToTensorInputOffset(
                                          i + input_offset[0], j + input_offset[1], k + input_offset[2]);
             local_acc[local_index] = conds ? device_evaluator.coeff(tensor_index) : CoeffReturnType(0);
           }
         }
       }
       itemID.barrier(cl::sycl::access::fence_space::local_space);
       // calculate the convolution
       if (boundary_check(itemID.get_global_id() < input_range)) {
         CoeffReturnType result = static_cast<CoeffReturnType>(0);
         for (size_t k = 0; k < kernel_size[2]; k++) {
           for (size_t j = 0; j < kernel_size[1]; j++) {
             for (size_t i = 0; i < kernel_size[0]; i++) {
               const size_t kernel_index = i + kernel_size[0] * (j + kernel_size[1] * k);
               const size_t local_index =
                   ((i + itemID.get_local_id(0)) +
                    num_input[0] * ((j + itemID.get_local_id(1)) + num_input[1] * (k + itemID.get_local_id(2))));
               result += (local_acc[local_index] * kernel_ptr[kernel_index]);
             }
           }
         }
         const size_t tensor_index =
             indexMapper.mapGpuOutputPlaneToTensorOutputOffset(p) +
             indexMapper.mapGpuOutputKernelToTensorOutputOffset(output_offset[0], output_offset[1], output_offset[2]);
         buffer_ptr[tensor_index] = result;
       }
       itemID.barrier(cl::sycl::access::fence_space::local_space);
     }
   }
References i, j, k, Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapGpuInputKernelToTensorInputOffset(), Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapGpuInputPlaneToTensorInputOffset(), Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapGpuOutputKernelToTensorOutputOffset(), Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapGpuOutputPlaneToTensorOutputOffset(), and p.
Member Data Documentation
buffer_acc
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > Buffer_accessor Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV3D >::buffer_acc
device_evaluator
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > Evaluator Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV3D >::device_evaluator
indexMapper
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > internal::IndexMapper<Index, InputDims, 3, Evaluator::Layout> Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV3D >::indexMapper
input_range
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > const cl::sycl::range<3> Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV3D >::input_range
kernel_filter
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > Kernel_accessor Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV3D >::kernel_filter
kernel_size
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > const cl::sycl::range<3> Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV3D >::kernel_size
local_acc
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > Local_accessor Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV3D >::local_acc
numP
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > const size_t Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV3D >::numP
The documentation for this struct was generated from the following file:
TensorConvolutionSycl.h