MercuryDPM: ModalPRefineableQElement< DIM > Class Template Reference
ModalPRefineableQElement< DIM > Class Template Reference
Public Member Functions
ModalPRefineableQElement ()
void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
void pre_build (Mesh *&, Vector< Node * > &)
void further_build ()
void p_refine (const int &inc, Mesh *const &mesh_pt, GeneralisedElement *const &clone_pt)
void shape (const Vector< double > &s, Shape &psi) const
void basis (const Vector< double > &s, Shape &basis) const
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsi) const
void dbasis_local (const Vector< double > &s, Shape &basis, DShape &dbasis) const
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
void d2basis_local (const Vector< double > &s, Shape &basis, DShape &dbasisds, DShape &d2basisds) const
void initial_setup (Tree *const &adopted_father_pt, const unsigned &initial_p_order)
void pre_build (Mesh *&, Vector< Node * > &)
void p_refine (const int &inc, Mesh *const &mesh_pt, GeneralisedElement *const &clone_pt)
Public Member Functions inherited from oomph::PRefineableQElement< DIM, 2 >
PRefineableQElement ()
Empty constuctor.
Constructor & Destructor Documentation
ModalPRefineableQElement()
template<unsigned DIM> ModalPRefineableQElement< DIM >::ModalPRefineableQElement () inline
 : PRefineableQElement<DIM,2>() {}
Member Function Documentation
basis()
template<unsigned DIM> void ModalPRefineableQElement< DIM >::basis (const Vector< double > & s, Shape & basis) const
 {
  // Get nnode-1d and p-order
  unsigned p_order = this->p_order();
  //Call the shape functions
  OneDimensionalModalShape psi1(p_order, s[0]);
  // Loop over shapes and copy across
  for(unsigned i=0;i<p_order;i++)
   {
    basis(i) = psi1[i];
   }
 }
References i, and s.
Referenced by ModalPRefineableQPoissonElement< DIM >::basis().
d2basis_local()
template<unsigned DIM> void ModalPRefineableQElement< DIM >::d2basis_local (const Vector< double > & s, Shape & basis, DShape & dbasisds, DShape & d2basisds) const
 {
  std::ostringstream error_message;
  error_message <<"\nd2basis_local currently not implemented for this element\n";
  throw OomphLibError(error_message.str(),
                      OOMPH_CURRENT_FUNCTION,
                      OOMPH_EXCEPTION_LOCATION);
 }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by ModalPRefineableQPoissonElement< DIM >::d2basis_local().
d2shape_local()
template<unsigned DIM> void ModalPRefineableQElement< DIM >::d2shape_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const
 {
  std::ostringstream error_message;
  error_message <<"\nd2shape_local currently not implemented for this element\n";
  throw OomphLibError(error_message.str(),
                      OOMPH_CURRENT_FUNCTION,
                      OOMPH_EXCEPTION_LOCATION);
 }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
dbasis_local()
template<unsigned DIM> void ModalPRefineableQElement< DIM >::dbasis_local (const Vector< double > & s, Shape & basis, DShape & dbasis) const
 {
  // Get nnode-1d and p-order
  unsigned p_order = this->p_order();
  //Call the shape functions and derivatives
  OneDimensionalModalShape psi1(p_order, s[0]);
  OneDimensionalModalDShape dpsi1ds(p_order, s[0]);
  // Loop over shapes and copy across
  for(unsigned i=0;i<p_order;i++)
   {
    basis(i) = psi1[i];
    dbasis(i,0) = dpsi1ds[i];
   }
 }
References i, and s.
Referenced by ModalPRefineableQPoissonElement< DIM >::dbasis_local().
dshape_local()
template<unsigned DIM> void ModalPRefineableQElement< DIM >::dshape_local (const Vector< double > & s, Shape & psi, DShape & dpsi) const
 {
  // Shape functions
  psi(0) = 0.5*(1.0 - s[0]);
  psi(1) = 0.5*(1.0 + s[0]);
  // dShape/dlocal
  dpsi(0,0) = -0.5;
  dpsi(1,0) = 0.5;
 }
References s.
further_build()
template<unsigned DIM> void ModalPRefineableQElement< DIM >::further_build () inline
   {
    PRefineableQElement<DIM,2>::further_build(); //(Empty)
   }
Referenced by ModalPRefineableQPoissonElement< DIM >::further_build().
initial_setup() [1/2]
void ModalPRefineableQElement< 1 >::initial_setup (Tree *const & adopted_father_pt, const unsigned & initial_p_order)
/ How to interpolate for the initial guess?
 {
  // Create storage for internal data
  if (this->ninternal_data()==0)
   {
    this->add_internal_data(new Data(0));
   }
  //Storage for pointer to my father (in binarytree impersonation)
  BinaryTree* father_pt;
  // Check if an adopted father has been specified
  if (adopted_father_pt!=0)
   {
    //Get pointer to my father (in binarytree impersonation)
    father_pt = dynamic_cast<BinaryTree*>(adopted_father_pt);
   }
  // Check if element is in a tree
  else if (Tree_pt!=0)
   {
    //Get pointer to my father (in binarytree impersonation)
    father_pt = dynamic_cast<BinaryTree*>(binary_tree_pt()->father_pt());
   }
  else
   {
    throw OomphLibError(
           "Element not in a tree, and no adopted father has been specified!",
           OOMPH_CURRENT_FUNCTION,
           OOMPH_EXCEPTION_LOCATION);
   }
  // Check if element has father
  if (father_pt!=0)
   {
    if (PRefineableQElement<1,2>* father_el_pt =
           dynamic_cast<PRefineableQElement<1,2>*>
           (father_pt->object_pt()))
     {
      unsigned father_p_order = father_el_pt->p_order();
      // Set the correct p-order of the element
      this->p_order() = father_p_order;
      // Now sort out the element...
      // Set integration scheme
      delete this->integral_pt();
      switch(this->p_order())
      {
      case 2:
       this->set_integration_scheme(new GaussLobattoLegendre<1,2>);
       break;
      case 3:
       this->set_integration_scheme(new GaussLobattoLegendre<1,3>);
       break;
      case 4:
       this->set_integration_scheme(new GaussLobattoLegendre<1,4>);
       break;
      case 5:
       this->set_integration_scheme(new GaussLobattoLegendre<1,5>);
       break;
      case 6:
       this->set_integration_scheme(new GaussLobattoLegendre<1,6>);
       break;
      case 7:
       this->set_integration_scheme(new GaussLobattoLegendre<1,7>);
       break;
      default:
       oomph_info << "\n ERROR: Exceeded maximum polynomial order for";
       oomph_info << "\n        integration scheme." << std::endl;
       break;
      }
      // Set the size of the internal data
      if (this->internal_data_pt(0)->nvalue() <= this->p_order()-this->nnode())
       {
        this->internal_data_pt(0)->resize(this->p_order()-this->nnode());
       }
      else
       {
        Data* new_data_pt = new Data(this->p_order()-this->nnode());
        delete internal_data_pt(0);
        internal_data_pt(0) = new_data_pt;
       }
      if(this->ninternal_data()==0) delete this->internal_data_pt(0);
      // Interpolate initial guess from father to modes
      // Set to zero for now, don't do projection problem
      for (unsigned i=0; i<this->p_order()-this->nnode_1d(); i++)
       {
        this->internal_data_pt(0)->set_value(i, 0.0);
       }
     }
    else
     {
         oomph_info << "Dynamic cast FAILURE :-(" << endl;
     }
   }
 }
References i, oomph::Tree::object_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::oomph_info.
initial_setup() [2/2]
template<unsigned DIM> void ModalPRefineableQElement< DIM >::initial_setup (Tree *const & adopted_father_pt = 0, const unsigned & initial_p_order = 0)
p_refine() [1/2]
template<unsigned DIM> void ModalPRefineableQElement< DIM >::p_refine (const int & inc, Mesh *const & mesh_pt, GeneralisedElement *const & clone_pt)
p_refine() [2/2]
void ModalPRefineableQElement< 1 >::p_refine (const int & inc, Mesh *const & mesh_pt, GeneralisedElement *const & clone_pt)
 {
  // BENFLAG: In this case we do not need the pointer to a clone of the
  //          element, or to the mesh, but they are required in the
  //          interface because we are overloading this function from
  //          the class PRefineableElement in which they are present.
  // Create storage for modes if none exists
  if (this->ninternal_data()==0)
   {
    this->add_internal_data(new Data(0));
   }
  // Increment p-order of the element
  this->p_order() += inc;
  // Change integration scheme
  delete this->integral_pt();
  switch(this->p_order())
  {
  case 2:
   this->set_integration_scheme(new GaussLobattoLegendre<1,2>);
   break;
  case 3:
   this->set_integration_scheme(new GaussLobattoLegendre<1,3>);
   break;
  case 4:
   this->set_integration_scheme(new GaussLobattoLegendre<1,4>);
   break;
  case 5:
   this->set_integration_scheme(new GaussLobattoLegendre<1,5>);
   break;
  case 6:
   this->set_integration_scheme(new GaussLobattoLegendre<1,6>);
   break;
  case 7:
   this->set_integration_scheme(new GaussLobattoLegendre<1,7>);
   break;
  default:
   oomph_info << "\n ERROR: Exceeded maximum polynomial order for";
   oomph_info << "\n        integration scheme." << std::endl;
   break;
  }
  // Add/remove new modes
  if (this->internal_data_pt(0)->nvalue() <= this->p_order()-this->nnode())
   {
    this->internal_data_pt(0)->resize(this->p_order()-this->nnode());
   }
  else
   {
    Data* new_data_pt = new Data(this->p_order()-this->nnode());
    delete internal_data_pt(0);
    internal_data_pt(0) = new_data_pt;
   }
  if(this->ninternal_data()==0) delete this->internal_data_pt(0);
 }
References oomph::oomph_info.
pre_build() [1/2]
template<unsigned DIM> void ModalPRefineableQElement< DIM >::pre_build (Mesh *& , Vector< Node * > &)
pre_build() [2/2]
void ModalPRefineableQElement< 1 >::pre_build (Mesh *& , Vector< Node * > &)
 {}
shape()
template<unsigned DIM> void ModalPRefineableQElement< DIM >::shape (const Vector< double > & s, Shape & psi) const
 {
  // Shape functions
  psi(0) = 0.5*(1.0 - s[0]);
  psi(1) = 0.5*(1.0 + s[0]);
 }
References s.
The documentation for this class was generated from the following file:
one_d_poisson_hp_adapt.cc