MercuryDPM: Eigen::internal::generic_y0< T, float > Struct Template Reference
Eigen::internal::generic_y0< T, float > Struct Template Reference
#include <BesselFunctionsImpl.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T run (const T &x)
Member Function Documentation
run()
template<typename T > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T Eigen::internal::generic_y0< T, float >::run (const T & x) inline static
{
     /* j0f.c
      *  Bessel function of the second kind, order zero
      *
      *
      *
      * SYNOPSIS:
      *
      * float x, y, y0f();
      *
      * y = y0f( x );
      *
      *
      *
      * DESCRIPTION:
      *
      * Returns Bessel function of the second kind, of order
      * zero, of the argument.
      *
      * The domain is divided into the intervals [0, 2] and
      * (2, infinity). In the first interval a rational approximation
      * R(x) is employed to compute
      *
      *                  2         2         2
      * y0(x)  =  (w - r  ) (w - r  ) (w - r  ) R(x)  +  2/pi ln(x) j0(x).
      *                 1         2         3
      *
      * Thus a call to j0() is required.  The three zeros are removed
      * from R(x) to improve its numerical stability.
      *
      * In the second interval, the modulus and phase are approximated
      * by polynomials of the form Modulus(x) = sqrt(1/x) Q(1/x)
      * and Phase(x) = x + 1/x S(1/x^2) - pi/4.  Then the function is
      *
      *   y0(x) = Modulus(x) sin( Phase(x) ).
      *
      *
      *
      *
      * ACCURACY:
      *
      *  Absolute error, when y0(x) < 1; else relative error:
      *
      * arithmetic   domain     # trials      peak         rms
      *    IEEE      0,  2       100000      2.4e-7      3.4e-8
      *    IEEE      2, 32       100000      1.8e-7      5.3e-8
      *
      */
     const float YP[] = {9.454583683980369E-008f, -9.413212653797057E-006f, 5.344486707214273E-004f,
                         -1.584289289821316E-002f, 1.707584643733568E-001f};
     const float MO[] = {-6.838999669318810E-002f, 1.864949361379502E-001f,  -2.145007480346739E-001f,
                         1.197549369473540E-001f,  -3.560281861530129E-003f, -4.969382655296620E-002f,
                         -3.355424622293709E-006f, 7.978845717621440E-001f};
     const float PH[] = {3.242077816988247E+001f,  -3.630592630518434E+001f, 1.756221482109099E+001f,
                         -4.974978466280903E+000f, 1.001973420681837E+000f,  -1.939906941791308E-001f,
                         6.490598792654666E-002f,  -1.249992184872738E-001f};
     const T YZ1 = pset1<T>(0.43221455686510834878f);
     const T TWOOPI = pset1<T>(0.636619772367581343075535f); /* 2 / pi */
     const T NEG_PIO4F = pset1<T>(-0.7853981633974483096f);  /* -pi / 4 */
     const T NEG_MAXNUM = pset1<T>(-NumTraits<float>::infinity());
     T z = pmul(x, x);
     T x_le_two = pmul(TWOOPI, pmul(plog(x), generic_j0<T, float>::run(x)));
     x_le_two = pmadd(psub(z, YZ1), internal::ppolevl<T, 4>::run(z, YP), x_le_two);
     x_le_two = pselect(pcmp_le(x, pset1<T>(0.0)), NEG_MAXNUM, x_le_two);
     T q = pdiv(pset1<T>(1.0), x);
     T w = prsqrt(x);
     T p = pmul(w, internal::ppolevl<T, 7>::run(q, MO));
     T u = pmul(q, q);
     T xn = pmadd(q, internal::ppolevl<T, 7>::run(u, PH), NEG_PIO4F);
     T x_gt_two = pmul(p, psin(padd(xn, x)));
     return pselect(pcmp_le(x, pset1<T>(2.0)), x_le_two, x_gt_two);
   }
References p, Eigen::internal::padd(), Eigen::internal::pcmp_le(), Eigen::internal::pdiv(), Eigen::internal::plog(), Eigen::internal::pmadd(), Eigen::internal::pmul(), Eigen::internal::prsqrt(), Eigen::internal::pselect(), Eigen::internal::psin(), Eigen::internal::psub(), Eigen::numext::q, w, and plotDoE::x.
The documentation for this struct was generated from the following file:
BesselFunctionsImpl.h