MercuryDPM: oomph::TetMeshFacetedSurface Class Reference
oomph::TetMeshFacetedSurface Class Reference
#include <tet_mesh.h>
Public Member Functions
TetMeshFacetedSurface ()
Constructor:
virtual ~TetMeshFacetedSurface ()
Empty destructor.
unsigned nvertex () const
Number of vertices.
unsigned nfacet () const
Number of facets.
unsigned one_based_facet_boundary_id (const unsigned &j) const
One-based boundary id of j-th facet.
unsigned one_based_vertex_boundary_id (const unsigned &j) const
First (of possibly multiple) one-based boundary id of j-th vertex.
double vertex_coordinate (const unsigned &j, const unsigned &i) const
i-th coordinate of j-th vertex
unsigned nvertex_on_facet (const unsigned &j) const
Number of vertices defining the j-th facet.
bool boundaries_can_be_split_in_tetgen ()
Test whether boundary can be split in tetgen.
void enable_boundaries_can_be_split_in_tetgen ()
Test whether boundaries can be split in tetgen.
void disable_boundaries_can_be_split_in_tetgen ()
Test whether boundaries can be split in tetgen.
TetMeshFacet * facet_pt (const unsigned &j) const
Pointer to j-th facet.
TetMeshVertex * vertex_pt (const unsigned &j) const
Pointer to j-th vertex.
DiskLikeGeomObjectWithBoundaries * geom_object_with_boundaries_pt ()
void output (std::ostream &outfile) const
Output.
void output (const std::string &filename) const
Output.
virtual void boundary_zeta01 (const unsigned &facet_id, const double &zeta_boundary, Vector< double > &zeta)
virtual void boundary_zeta12 (const unsigned &facet_id, const double &zeta_boundary, Vector< double > &zeta)
virtual void boundary_zeta20 (const unsigned &facet_id, const double &zeta_boundary, Vector< double > &zeta)
Vector< unsigned > vertex_index_in_tetgen (const unsigned &f)
Protected Attributes
Vector< TetMeshVertex * > Vertex_pt
Vector pointers to vertices.
Vector< TetMeshFacet * > Facet_pt
Vector of pointers to facets.
bool Boundaries_can_be_split_in_tetgen
Vector< Vector< unsigned > > Facet_vertex_index_in_tetgen
DiskLikeGeomObjectWithBoundaries * Geom_object_with_boundaries_pt
GeomObject with boundaries associated with this surface.
Private Member Functions
void setup_facet_connectivity_for_tetgen ()
Setup facet connectivity for tetgen.
Detailed Description
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Base class for tet mesh boundary defined by polygonal planar facets
Constructor & Destructor Documentation
TetMeshFacetedSurface()
oomph::TetMeshFacetedSurface::TetMeshFacetedSurface () inline
Constructor:
       : Boundaries_can_be_split_in_tetgen(true),
         Geom_object_with_boundaries_pt(0)
     {
     }
~TetMeshFacetedSurface()
virtual oomph::TetMeshFacetedSurface::~TetMeshFacetedSurface () inline virtual
Empty destructor.
 {}
Member Function Documentation
boundaries_can_be_split_in_tetgen()
bool oomph::TetMeshFacetedSurface::boundaries_can_be_split_in_tetgen () inline
Test whether boundary can be split in tetgen.
     {
       return Boundaries_can_be_split_in_tetgen;
     }
References Boundaries_can_be_split_in_tetgen.
Referenced by oomph::TetgenMesh< ELEMENT >::TetgenMesh().
boundary_zeta01()
virtual void oomph::TetMeshFacetedSurface::boundary_zeta01 (const unsigned & facet_id, const double & zeta_boundary, Vector< double > & zeta) inline virtual
Virtual function that specifies the variation of the zeta coordinates in the GeomObject along the boundary connecting vertices 0 and 1 in facet facet_id. Default implementation: Linear interpolation between edges. zeta_boundary=0.0: we're on vertex 0; zeta_boundary=1.0: we're on vertex 1.
Reimplemented in oomph::DiskTetMeshFacetedSurface.
     {
       Vector<Vector<double>> zeta_vertex(2);
       zeta_vertex[0] = Facet_pt[facet_id]->vertex_pt(0)->zeta_in_geom_object();
       zeta_vertex[1] = Facet_pt[facet_id]->vertex_pt(1)->zeta_in_geom_object();
       zeta[0] = zeta_vertex[0][0] +
                 (zeta_vertex[1][0] - zeta_vertex[0][0]) * zeta_boundary;
       zeta[1] = zeta_vertex[0][1] +
                 (zeta_vertex[1][1] - zeta_vertex[0][1]) * zeta_boundary;
     }
References Facet_pt, and Eigen::zeta().
Referenced by oomph::TetMeshBase::snap_nodes_onto_geometric_objects().
boundary_zeta12()
virtual void oomph::TetMeshFacetedSurface::boundary_zeta12 (const unsigned & facet_id, const double & zeta_boundary, Vector< double > & zeta) inline virtual
Virtual function that specifies the variation of the zeta coordinates in the GeomObject along the boundary connecting vertices 1 and 2 in facet facet_id. Default implementation: Linear interpolation between edges. zeta_boundary=0.0: we're on vertex 1; zeta_boundary=1.0: we're on vertex 2.
     {
       Vector<Vector<double>> zeta_vertex(2);
       zeta_vertex[0] = Facet_pt[facet_id]->vertex_pt(1)->zeta_in_geom_object();
       zeta_vertex[1] = Facet_pt[facet_id]->vertex_pt(2)->zeta_in_geom_object();
       zeta[0] = zeta_vertex[0][0] +
                 (zeta_vertex[1][0] - zeta_vertex[0][0]) * zeta_boundary;
       zeta[1] = zeta_vertex[0][1] +
                 (zeta_vertex[1][1] - zeta_vertex[0][1]) * zeta_boundary;
     }
References Facet_pt, and Eigen::zeta().
Referenced by oomph::TetMeshBase::snap_nodes_onto_geometric_objects().
boundary_zeta20()
virtual void oomph::TetMeshFacetedSurface::boundary_zeta20 (const unsigned & facet_id, const double & zeta_boundary, Vector< double > & zeta) inline virtual
Virtual function that specifies the variation of the zeta coordinates in the GeomObject along the boundary connecting vertices 2 and 0 in facet facet_id. Default implementation: Linear interpolation between edges. zeta_boundary=0.0: we're on vertex 2; zeta_boundary=1.0: we're on vertex 0.
     {
       Vector<Vector<double>> zeta_vertex(2);
       zeta_vertex[0] = Facet_pt[facet_id]->vertex_pt(2)->zeta_in_geom_object();
       zeta_vertex[1] = Facet_pt[facet_id]->vertex_pt(0)->zeta_in_geom_object();
       zeta[0] = zeta_vertex[0][0] +
                 (zeta_vertex[1][0] - zeta_vertex[0][0]) * zeta_boundary;
       zeta[1] = zeta_vertex[0][1] +
                 (zeta_vertex[1][1] - zeta_vertex[0][1]) * zeta_boundary;
     }
References Facet_pt, and Eigen::zeta().
Referenced by oomph::TetMeshBase::snap_nodes_onto_geometric_objects().
disable_boundaries_can_be_split_in_tetgen()
void oomph::TetMeshFacetedSurface::disable_boundaries_can_be_split_in_tetgen () inline
Test whether boundaries can be split in tetgen.
     {
       Boundaries_can_be_split_in_tetgen = false;
     }
References Boundaries_can_be_split_in_tetgen.
enable_boundaries_can_be_split_in_tetgen()
void oomph::TetMeshFacetedSurface::enable_boundaries_can_be_split_in_tetgen () inline
Test whether boundaries can be split in tetgen.
     {
       Boundaries_can_be_split_in_tetgen = true;
     }
References Boundaries_can_be_split_in_tetgen.
facet_pt()
TetMeshFacet* oomph::TetMeshFacetedSurface::facet_pt (const unsigned & j) const inline
Pointer to j-th facet.
     {
       return Facet_pt[j];
     }
References Facet_pt, and j.
Referenced by oomph::GmshTetMesh< ELEMENT >::build_it(), oomph::TetgenMesh< ELEMENT >::setup_reverse_lookup_schemes_for_faceted_surface(), oomph::TetMeshBase::snap_nodes_onto_geometric_objects(), and oomph::GmshTetScaffoldMesh::write_geo_file().
geom_object_with_boundaries_pt()
DiskLikeGeomObjectWithBoundaries* oomph::TetMeshFacetedSurface::geom_object_with_boundaries_pt () inline
Access to GeomObject with boundaries associated with this surface (Null if there isn't one!)
     {
       return Geom_object_with_boundaries_pt;
     }
References Geom_object_with_boundaries_pt.
Referenced by oomph::TetMeshBase::snap_nodes_onto_geometric_objects().
nfacet()
unsigned oomph::TetMeshFacetedSurface::nfacet () const inline
Number of facets.
     {
       return Facet_pt.size();
     }
References Facet_pt.
Referenced by oomph::GmshTetMesh< ELEMENT >::build_it(), oomph::TetgenMesh< ELEMENT >::build_tetgenio(), setup_facet_connectivity_for_tetgen(), oomph::TetgenMesh< ELEMENT >::setup_reverse_lookup_schemes_for_faceted_surface(), oomph::TetMeshBase::snap_nodes_onto_geometric_objects(), oomph::RefineableTetgenMesh< ELEMENT >::update_faceted_surface_using_face_mesh(), vertex_index_in_tetgen(), oomph::GmshTetScaffoldMesh::write_geo_file(), and oomph::TetMeshFacetedClosedSurfaceForRemesh::~TetMeshFacetedClosedSurfaceForRemesh().
nvertex()
unsigned oomph::TetMeshFacetedSurface::nvertex () const inline
Number of vertices.
     {
       return Vertex_pt.size();
     }
References Vertex_pt.
Referenced by oomph::TetgenMesh< ELEMENT >::build_tetgenio(), oomph::GmshTetScaffoldMesh::write_geo_file(), and oomph::TetMeshFacetedClosedSurfaceForRemesh::~TetMeshFacetedClosedSurfaceForRemesh().
nvertex_on_facet()
unsigned oomph::TetMeshFacetedSurface::nvertex_on_facet (const unsigned & j) const inline
Number of vertices defining the j-th facet.
     {
       return Facet_pt[j]->nvertex();
     }
References Facet_pt, and j.
one_based_facet_boundary_id()
unsigned oomph::TetMeshFacetedSurface::one_based_facet_boundary_id (const unsigned & j) const inline
One-based boundary id of j-th facet.
     {
       return Facet_pt[j]->one_based_boundary_id();
     }
References Facet_pt, and j.
Referenced by oomph::GmshTetMesh< ELEMENT >::build_it(), oomph::TetgenMesh< ELEMENT >::build_tetgenio(), oomph::TetgenMesh< ELEMENT >::setup_reverse_lookup_schemes_for_faceted_surface(), oomph::TetMeshBase::snap_nodes_onto_geometric_objects(), oomph::RefineableTetgenMesh< ELEMENT >::update_faceted_surface_using_face_mesh(), and oomph::GmshTetScaffoldMesh::write_geo_file().
one_based_vertex_boundary_id()
unsigned oomph::TetMeshFacetedSurface::one_based_vertex_boundary_id (const unsigned & j) const inline
First (of possibly multiple) one-based boundary id of j-th vertex.
     {
       return Vertex_pt[j]->one_based_boundary_id();
     }
References j, and Vertex_pt.
Referenced by oomph::TetgenMesh< ELEMENT >::build_tetgenio().
output() [1/2]
void oomph::TetMeshFacetedSurface::output (const std::string & filename) const inline
Output.
     {
       std::ofstream outfile;
       outfile.open(filename.c_str());
       output(outfile);
       outfile.close();
     }
References MergeRestartFiles::filename, and output().
output() [2/2]
void oomph::TetMeshFacetedSurface::output (std::ostream & outfile) const inline
Output.
     {
       unsigned n = Facet_pt.size();
       for (unsigned j = 0; j < n; j++)
       {
         Facet_pt[j]->output(outfile);
       }
     }
References Facet_pt, j, and n.
Referenced by FallingBlockProblem< ELEMENT >::FallingBlockProblem(), output(), and TetmeshPoissonProblem< ELEMENT >::TetmeshPoissonProblem().
setup_facet_connectivity_for_tetgen()
void oomph::TetMeshFacetedSurface::setup_facet_connectivity_for_tetgen () inline private
Setup facet connectivity for tetgen.
     {
       unsigned nv_overall = Vertex_pt.size();
       unsigned nf = nfacet();
       Facet_vertex_index_in_tetgen.resize(nf);
       for (unsigned f = 0; f < nf; f++)
       {
         unsigned nv = Facet_pt[f]->nvertex();
         Facet_vertex_index_in_tetgen[f].resize(nv);
         for (unsigned v = 0; v < nv; v++)
         {
           TetMeshVertex* my_vertex_pt = Facet_pt[f]->vertex_pt(v);
           for (unsigned j = 0; j < nv_overall; j++)
           {
             if (my_vertex_pt == Vertex_pt[j])
             {
               Facet_vertex_index_in_tetgen[f][v] = j;
               break;
             }
           }
         }
       }
     }
References f(), Facet_pt, Facet_vertex_index_in_tetgen, j, nfacet(), v, and Vertex_pt.
Referenced by vertex_index_in_tetgen().
vertex_coordinate()
double oomph::TetMeshFacetedSurface::vertex_coordinate (const unsigned & j, const unsigned & i) const inline
i-th coordinate of j-th vertex
     {
       return Vertex_pt[j]->x(i);
     }
References i, j, and Vertex_pt.
Referenced by oomph::TetgenMesh< ELEMENT >::build_tetgenio().
vertex_index_in_tetgen()
Vector<unsigned> oomph::TetMeshFacetedSurface::vertex_index_in_tetgen (const unsigned & f) inline
Facet connectivity: vertex_index[j] is the index of the j-th vertex (in the Vertex_pt vector) in facet f. Bit of an obscure functionality that's only needed for setup tetgen_io.
     {
       if (Facet_vertex_index_in_tetgen.size() != nfacet())
       {
         setup_facet_connectivity_for_tetgen();
       }
       return Facet_vertex_index_in_tetgen[f];
     }
References f(), Facet_vertex_index_in_tetgen, nfacet(), and setup_facet_connectivity_for_tetgen().
Referenced by oomph::TetgenMesh< ELEMENT >::build_tetgenio().
vertex_pt()
TetMeshVertex* oomph::TetMeshFacetedSurface::vertex_pt (const unsigned & j) const inline
Pointer to j-th vertex.
     {
       return Vertex_pt[j];
     }
References j, and Vertex_pt.
Referenced by oomph::DiskTetMeshFacetedSurface::boundary_zeta01(), and oomph::GmshTetScaffoldMesh::write_geo_file().
Member Data Documentation
Boundaries_can_be_split_in_tetgen
bool oomph::TetMeshFacetedSurface::Boundaries_can_be_split_in_tetgen protected
Boolean to indicate whether extra vertices can be added on the boundary in tetgen
Referenced by boundaries_can_be_split_in_tetgen(), disable_boundaries_can_be_split_in_tetgen(), and enable_boundaries_can_be_split_in_tetgen().
Facet_pt
Vector<TetMeshFacet*> oomph::TetMeshFacetedSurface::Facet_pt protected
Vector of pointers to facets.
Referenced by oomph::DiskTetMeshFacetedSurface::boundary_zeta01(), boundary_zeta01(), boundary_zeta12(), boundary_zeta20(), oomph::RectangularTetMeshFacetedSurface::build_it(), oomph::CubicTetMeshFacetedSurface::build_it(), oomph::DiskTetMeshFacetedSurface::DiskTetMeshFacetedSurface(), oomph::DiskWithTorusAroundEdgeTetMeshFacetedSurface::DiskWithTorusAroundEdgeTetMeshFacetedSurface(), oomph::DiskWithTwoLayersTetMeshFacetedSurface::DiskWithTwoLayersTetMeshFacetedSurface(), facet_pt(), nfacet(), nvertex_on_facet(), one_based_facet_boundary_id(), output(), setup_facet_connectivity_for_tetgen(), oomph::TetMeshFacetedClosedSurfaceForRemesh::TetMeshFacetedClosedSurfaceForRemesh(), and oomph::TetMeshFacetedClosedSurfaceForRemesh::~TetMeshFacetedClosedSurfaceForRemesh().
Facet_vertex_index_in_tetgen
Vector<Vector<unsigned> > oomph::TetMeshFacetedSurface::Facet_vertex_index_in_tetgen protected
Facet connectivity: Facet_vertex_index[f][j] is the index of the j-th vertex (in the Vertex_pt vector) in facet f.
Referenced by setup_facet_connectivity_for_tetgen(), and vertex_index_in_tetgen().
Geom_object_with_boundaries_pt
DiskLikeGeomObjectWithBoundaries* oomph::TetMeshFacetedSurface::Geom_object_with_boundaries_pt protected
GeomObject with boundaries associated with this surface.
Referenced by oomph::DiskTetMeshFacetedSurface::boundary_zeta01(), oomph::DiskTetMeshFacetedSurface::DiskTetMeshFacetedSurface(), oomph::DiskWithTorusAroundEdgeTetMeshFacetedSurface::DiskWithTorusAroundEdgeTetMeshFacetedSurface(), and geom_object_with_boundaries_pt().
Vertex_pt
Vector<TetMeshVertex*> oomph::TetMeshFacetedSurface::Vertex_pt protected
Vector pointers to vertices.
Referenced by oomph::RectangularTetMeshFacetedSurface::build_it(), oomph::CubicTetMeshFacetedSurface::build_it(), oomph::DiskTetMeshFacetedSurface::DiskTetMeshFacetedSurface(), oomph::DiskWithTorusAroundEdgeTetMeshFacetedSurface::DiskWithTorusAroundEdgeTetMeshFacetedSurface(), oomph::DiskWithTwoLayersTetMeshFacetedSurface::DiskWithTwoLayersTetMeshFacetedSurface(), nvertex(), one_based_vertex_boundary_id(), setup_facet_connectivity_for_tetgen(), oomph::TetMeshFacetedClosedSurfaceForRemesh::TetMeshFacetedClosedSurfaceForRemesh(), vertex_coordinate(), vertex_pt(), and oomph::TetMeshFacetedClosedSurfaceForRemesh::~TetMeshFacetedClosedSurfaceForRemesh().
The documentation for this class was generated from the following file:
tet_mesh.h