MercuryDPM: ChuteDemo.cpp File Reference
ChuteDemo.cpp File Reference
#include <iostream>
#include <Species/LinearViscoelasticSpecies.h>
#include "Chute.h"
Functions
int main ()
[ChuteDemo:include]
Function Documentation
main()
int main ()
[ChuteDemo:include]
[ChuteDemo:include]
[ChuteDemo:initial]
[ChuteDemo:initial]
[ChuteDemo:particles]
[ChuteDemo:particles]
[ChuteDemo:chute]
[ChuteDemo:chute]
[ChuteDemo:inflow]
[ChuteDemo:inflow]
 {
     // Problem parameters
     Chute problem;
     problem.setName("ChuteDemo");   // data output file name
     problem.setGravity({0,-1,0});
     problem.setSaveCount(102);      // number of time steps skipped between saves
     Mdouble tc = 2.5e-3;            // collision time
     problem.setTimeStep(0.02 * tc); // actual time step
     problem.setTimeMax(0.5);        // maximum time
                                     // NB: number of time steps saved to output files
                                     // is timeMax/(timeStep*saveCount)
     // Particle radii
     problem.setFixedParticleRadius(0.001);  // radius of fixed chute bottom particles
     problem.setInflowParticleRadius(0.001); // radius of (monodisperse) inflow particles
     // Particle species
     LinearViscoelasticSpecies species;              // initialise species
     species.setHandler(&problem.speciesHandler);    // assign problem species handler to species
     species.setDensity(2000);                       // particle density
     species.setCollisionTimeAndRestitutionCoefficient( tc,
             0.8, species.getMassFromRadius(problem.getInflowParticleRadius())); // material properties
     problem.speciesHandler.copyAndAddObject(species);   // assign species to problem species handler
     // Chute properties
     problem.setChuteAngle(30.0);                    // set angle of chute relative to horizontal
     problem.setXMax(0.1);                           // chute length = 0.1
     problem.setYMax(2.0 * problem.getInflowParticleRadius()); // chute width = 1 particle diameter
     // Inflow properties
     problem.setInflowHeight(0.1);                   // particle inflow between 0 <= Z <= 0.1
     problem.setInflowVelocity(0.1);                 // particle inflow mean velocity
     problem.setInflowVelocityVariance(0.02);        // particle inflow velocity variance (in ratio of the mean velocity)
     //Write paraview data
     problem.setParticlesWriteVTK(true);
     problem.wallHandler.setWriteVTK(true);
     /*problem.setParticlesWriteVTK(true);
     problem.wallHandler.setWriteVTK(true);*/
     //solve
     problem.solve();
 } // the end
References ParticleSpecies::getMassFromRadius(), problem, LinearViscoelasticNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), ParticleSpecies::setDensity(), and BaseSpecies::setHandler().