MercuryDPM: Eigen::Solve< Decomposition, RhsType > Class Template Reference
Eigen::Solve< Decomposition, RhsType > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Pseudo expression representing a solving operation.
#include <Solve.h>
Public Types
typedef internal::traits< Solve >::PlainObject PlainObject
typedef internal::traits< Solve >::StorageIndex StorageIndex
Public Types inherited from Eigen::SolveImpl< Decomposition, RhsType, internal::traits< RhsType >::StorageKind >
typedef internal::generic_xpr_base< Solve< Decomposition, RhsType >, MatrixXpr, internal::traits< RhsType >::StorageKind >::type Base
Public Member Functions
Solve (const Decomposition &dec, const RhsType &rhs)
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC const Decomposition & dec () const
EIGEN_DEVICE_FUNC const RhsType & rhs () const
Protected Attributes
const Decomposition & m_dec
const internal::ref_selector< RhsType >::type m_rhs
Detailed Description
template<typename Decomposition, typename RhsType>
class Eigen::Solve< Decomposition, RhsType >
Pseudo expression representing a solving operation.
Template Parameters
Decomposition the type of the matrix or decomposition object
Rhstype the type of the right-hand side
This class represents an expression of A.solve(B) and most of the time this is the only way it is used.
Member Typedef Documentation
PlainObject
template<typename Decomposition , typename RhsType > typedef internal::traits<Solve>::PlainObject Eigen::Solve< Decomposition, RhsType >::PlainObject
StorageIndex
template<typename Decomposition , typename RhsType > typedef internal::traits<Solve>::StorageIndex Eigen::Solve< Decomposition, RhsType >::StorageIndex
Constructor & Destructor Documentation
Solve()
template<typename Decomposition , typename RhsType > Eigen::Solve< Decomposition, RhsType >::Solve (const Decomposition & dec, const RhsType & rhs) inline
 : m_dec(dec), m_rhs(rhs) {}
Member Function Documentation
cols()
template<typename Decomposition , typename RhsType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::Solve< Decomposition, RhsType >::cols () const inline
 { return m_rhs.cols(); }
References Eigen::Solve< Decomposition, RhsType >::m_rhs.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::internal::Assignment< DstXprType, Solve< DecType, RhsType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Solve< Transpose< const DecType >, RhsType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Solve< CwiseUnaryOp< internal::scalar_conjugate_op< typename DecType::Scalar >, const Transpose< const DecType > >, RhsType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Solve< DecType, RhsType >, internal::assign_op< Scalar, Scalar >, Sparse2Sparse >::run(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
dec()
template<typename Decomposition , typename RhsType > EIGEN_DEVICE_FUNC const Decomposition& Eigen::Solve< Decomposition, RhsType >::dec () const inline
 { return m_dec; }
References Eigen::Solve< Decomposition, RhsType >::m_dec.
Referenced by Eigen::internal::Assignment< DstXprType, Solve< DecType, RhsType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Solve< Transpose< const DecType >, RhsType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Solve< CwiseUnaryOp< internal::scalar_conjugate_op< typename DecType::Scalar >, const Transpose< const DecType > >, RhsType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >::run(), and Eigen::internal::Assignment< DstXprType, Solve< DecType, RhsType >, internal::assign_op< Scalar, Scalar >, Sparse2Sparse >::run().
rhs()
template<typename Decomposition , typename RhsType > EIGEN_DEVICE_FUNC const RhsType& Eigen::Solve< Decomposition, RhsType >::rhs () const inline
 { return m_rhs; }
References Eigen::Solve< Decomposition, RhsType >::m_rhs.
Referenced by Eigen::internal::Assignment< DstXprType, Solve< DecType, RhsType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Solve< Transpose< const DecType >, RhsType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Solve< CwiseUnaryOp< internal::scalar_conjugate_op< typename DecType::Scalar >, const Transpose< const DecType > >, RhsType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >::run(), and Eigen::internal::Assignment< DstXprType, Solve< DecType, RhsType >, internal::assign_op< Scalar, Scalar >, Sparse2Sparse >::run().
rows()
template<typename Decomposition , typename RhsType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::Solve< Decomposition, RhsType >::rows () const inline
 { return m_dec.cols(); }
References Eigen::Solve< Decomposition, RhsType >::m_dec.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::internal::Assignment< DstXprType, Solve< DecType, RhsType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Solve< Transpose< const DecType >, RhsType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Solve< CwiseUnaryOp< internal::scalar_conjugate_op< typename DecType::Scalar >, const Transpose< const DecType > >, RhsType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >::run(), Eigen::internal::Assignment< DstXprType, Solve< DecType, RhsType >, internal::assign_op< Scalar, Scalar >, Sparse2Sparse >::run(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_dec
template<typename Decomposition , typename RhsType > const Decomposition& Eigen::Solve< Decomposition, RhsType >::m_dec protected
Referenced by Eigen::Solve< Decomposition, RhsType >::dec(), and Eigen::Solve< Decomposition, RhsType >::rows().
m_rhs
template<typename Decomposition , typename RhsType > const internal::ref_selector<RhsType>::type Eigen::Solve< Decomposition, RhsType >::m_rhs protected
Referenced by Eigen::Solve< Decomposition, RhsType >::cols(), and Eigen::Solve< Decomposition, RhsType >::rhs().
The documentation for this class was generated from the following file:
Solve.h