MercuryDPM: STSpineMesh< ELEMENT, INTERFACE_ELEMENT > Class Template Reference
STSpineMesh< ELEMENT, INTERFACE_ELEMENT > Class Template Reference
#include <st_mesh.h>
Public Member Functions
STSpineMesh (const unsigned int &nel_can, const unsigned int &nel, const unsigned int &nel_liq, const double &alpha, const double &length_can, const double &length_tip, const double &length_liq, const double &height, const double &radius, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
FiniteElement *& interface_element_pt (const unsigned long &i)
Access functions for pointers to interface elements.
unsigned long ninterface_element () const
Number of elements on interface.
FiniteElement *& interface_line_element_pt (const unsigned long &i)
Access functions for pointers to interface line elements.
unsigned long ninterfaceline () const
Number of elements on the line interface.
FiniteElement *& bulk_element_pt (const unsigned long &i)
Access functions for pointers to elements in bulk.
unsigned long nbulk () const
Number of elements in bulk.
FiniteElement *& bulk_outlet_element_pt (const unsigned long &i)
unsigned long nbulkoutlet () const
FiniteElement *& bulk_inlet_element_pt (const unsigned long &i)
unsigned long nbulkinlet () const
int face_index_outlet ()
int face_index_inlet ()
void full_output (std::ostream &outfile, const unsigned &n_plot)
void surface_output (std::ostream &outfile, const unsigned &n_plot)
virtual void spine_node_update (SpineNode *spine_node_pt)
Public Member Functions inherited from oomph::SpineMesh
virtual ~SpineMesh ()
Destructor to clean up the memory allocated to the spines.
Spine *& spine_pt (const unsigned long &i)
Return the i-th spine in the mesh.
const Spine * spine_pt (const unsigned long &i) const
Return the i-th spine in the mesh (const version)
unsigned long nspine () const
Return the number of spines in the mesh.
void add_spine_pt (Spine *const &spine_pt)
Add a spine to the mesh.
SpineNode * node_pt (const unsigned long &n)
Return a pointer to the n-th global SpineNode.
SpineNode * element_node_pt (const unsigned long &e, const unsigned &n)
unsigned long assign_global_spine_eqn_numbers (Vector< double * > &Dof_pt)
Assign spines to Spine_pt vector of element.
void describe_spine_dofs (std::ostream &out, const std::string &current_string) const
void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_spine_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Assign time stepper to spines data.
void set_consistent_pinned_spine_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
bool does_pointer_correspond_to_spine_data (double *const &parameter_pt)
void node_update (const bool &update_all_solid_nodes=false)
void dump (std::ofstream &dump_file) const
Overload the dump function so that the spine data is dumped.
void read (std::ifstream &restart_file)
Overload the read function so that the spine data is also read.
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void setup_boundary_element_info ()
virtual void setup_boundary_element_info (std::ostream &outfile)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Protected Member Functions
virtual void build_single_layer_mesh (TimeStepper *time_stepper_pt)
void add_side_spinemesh (unsigned int bound1, CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT > *addmesh_pt, int *addmesh_map_boundary, int total_boundaries, unsigned flag)
void add_mesh (unsigned int bound1, Mesh *addmesh_pt, int *addmesh_map_boundary, int total_boundaries, unsigned spine_flag)
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes
unsigned int Nel_can
unsigned int Nel
unsigned int Nel_liq
double Alpha
Aspect ratio, length, height and radius.
double Length_can
double Length_tip
double Length_liq
double Height
double Radius
double Xsim
double Zsim
double Ysim
int Face_index_outlet
int Face_index_inlet
Vector< FiniteElement * > Bulk_element_pt
Vector of pointers to element in the fluid layer.
Vector< FiniteElement * > Interface_element_pt
Vector of pointers to interface elements.
Vector< FiniteElement * > Bulk_outlet_element_pt
Vector of pointers to the bulk outlet elements in the fluid layer.
Vector< FiniteElement * > Bulk_inlet_element_pt
Vector of pointers to the bulk inlet elements in the fluid layer.
Vector< FiniteElement * > Interface_line_element_pt
Protected Attributes inherited from oomph::SpineMesh
Vector< Spine * > Spine_pt
A Spine mesh contains a Vector of pointers to spines.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Detailed Description
template<class ELEMENT, class INTERFACE_ELEMENT>
class STSpineMesh< ELEMENT, INTERFACE_ELEMENT >
Mesh for the Saffman-Taylor problem in a cell of arbitrary aspect ratio The mesh contains a layer of spinified fluid elements (of type ELEMENT; e.g SpineElement<CrozierRaviartElement<2>) in the boundary 5
Remarck, we set the flag of every mesh twice. it is not logical but saves programming time
Constructor & Destructor Documentation
STSpineMesh()
template<class ELEMENT , class INTERFACE_ELEMENT > STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::STSpineMesh (const unsigned int & nel_can, const unsigned int & nel, const unsigned int & nel_liq, const double & alpha, const double & length_can, const double & length_tip, const double & length_liq, const double & height, const double & radius, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass number of elements in x-direction, number of The composed mesh is too complicated for giving xmin,xmax etc.. Nevertheless we keep nx, ny, nz making reference
Constructor for spine 3D mesh:
The mesh contains a layer of spinified fluid elements (of type ELEMENT; e.g SpineElement<CrozierRaviartElement<2>)
                                                                                            :
  Nel_can(nel_can), Nel(nel), Nel_liq(nel_liq), Alpha(alpha), Length_can(length_can), Length_tip(length_tip), Length_liq(length_liq), Height(height), Radius(radius)
 {
  // We've called the "generic" constructor for the RectangularQuadMesh
  // which doesn't do much...
  // Now set up the parameters that characterise the mesh geometry
  // then call the constructor
  // Now build the mesh:
  build_single_layer_mesh(time_stepper_pt);
 }
References STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh().
Member Function Documentation
add_mesh()
template<class ELEMENT , class INTERFACE_ELEMENT > void STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::add_mesh (unsigned int bound1, Mesh * addmesh_pt, int * addmesh_map_boundary, int total_boundaries, unsigned spine_flag) protected
////////////////////////////////////////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////////////////////////////////////////
 {
    int bound2 = -1;
    Mesh *mesh_pt = this;
 //Map of the commom nodes from the nodes in the added mesh to the old mesh (It is needed for the added elements to point to the old nodes and not duplicate this nodes)
   std::map<Node*,Node*> map_bound_node;
 // We have to look for the shared boundary of the second mwsh. We identify it giving a value of -1 in the mappring of the old to the new boundary conditions
    for(unsigned i = 0; i<addmesh_pt->nboundary(); i++)
   {
     if(addmesh_map_boundary[i] == -1)
        bound2 = i;
    }
 //#ifdef PARANOID
   if(bound2 == -1) {
    throw OomphLibError("Error setting the shared boundary conditions\n",
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
   }
 // Another control. Test that the two shared boundaries have the same number of nodes
   if(addmesh_pt->nboundary_node(bound2) != mesh_pt->nboundary_node(bound1) )
    {
     std::ostringstream error_stream;
     error_stream
      <<"Different number of nodes in the shared boundaries:\n" <<
      "Boundary "<<bound1<<" in the original mesh has "
      <<mesh_pt->nboundary_node(bound1)<<" nodes \n"<<
      "and Boundary "<<bound2<<" in the added mesh has "
      <<addmesh_pt->nboundary_node(bound2)<<" nodes.\n";
     throw OomphLibError(error_stream.str(),
                         OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
    }
 //#endif
 //We create the mappping
   //square distance between two nodes
   double d;
 // Minimun distance between two nodes (only useful in case of error)
   double dmin;
   //Dimession of the space
   unsigned dim = addmesh_pt->node_pt(0)->ndim();
   unsigned long nodecounter;
   for( unsigned long i = 0; i< addmesh_pt->nboundary_node(bound2);i++)
    {
      nodecounter =0;
      dmin = 100.0;
      do
      {
       d = 0.0;
       for(unsigned int k=0;k<dim;k++)
        {
          d += (addmesh_pt->boundary_node_pt(bound2,i)->x(k) -  mesh_pt->boundary_node_pt(bound1,nodecounter)->x(k) )*
               (addmesh_pt->boundary_node_pt(bound2,i)->x(k) -  mesh_pt->boundary_node_pt(bound1,nodecounter)->x(k) );
        }
       nodecounter++;
       if(dmin>d) dmin = d;
      }while((nodecounter < mesh_pt->nboundary_node(bound1)) && (d>1E-10));
      if((nodecounter == mesh_pt->nboundary_node(bound1)) && (d>1E-10))
      {
       std::ostringstream error_stream;
       error_stream
        <<"Error doing the mapping between shared boundaries:\n" <<
        "it could not be found minimum distance in node "<<i<<"\n"
        <<"Minimum found distance = "<<sqrt(dmin)<<"\n"
        <<"Position in the added mesh  = "
        <<addmesh_pt->boundary_node_pt(bound2,i)->x(0)<<"  "
        <<addmesh_pt->boundary_node_pt(bound2,i)->x(1)<<"   "
        <<addmesh_pt->boundary_node_pt(bound2,i)->x(2)<<"\n";
       throw OomphLibError(error_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
      else
       {
        // Creating the nodes map
         map_bound_node[addmesh_pt->boundary_node_pt(bound2,i)] =  mesh_pt->boundary_node_pt(bound1,nodecounter-1);
       }
   }
    //Now we loop over the elements of the added mesh on the shared boundary and reasign the node  pointers to the ones
   // of the original mesh.
 // REMARCK!!!!!  the boundary_element scheme was not implemented in the mesh design, so that we have to loop over all the elements
    for(unsigned int i = 0; i< addmesh_pt->nelement(); i++ )
    {
 //Pointer to the element
     ELEMENT* el_pt = dynamic_cast<ELEMENT*>( addmesh_pt->element_pt(i));
     // Loop over the nodes in the element
      for(unsigned j =0;j< el_pt->nnode();j++)
      {
       //In case the node is in the boundary (and therefore in the map), we reasign the node
         if(map_bound_node[ el_pt->node_pt(j) ] != 0)
        {
         el_pt->node_pt(j) = map_bound_node[ el_pt->node_pt(j)];
        }
      }
   }
 //We add the nodes which are not in the shared boundary
   unsigned long n_nodes_addmesh = addmesh_pt->nnode();
   unsigned int zaehler = 0;
    for(unsigned j=0;j<n_nodes_addmesh;j++)
   {
    if( map_bound_node[ addmesh_pt->node_pt(j)] == 0)
     {
        SpineNode* nod_pt =  dynamic_cast<SpineNode*>(addmesh_pt->node_pt(j));
        nod_pt->spine_mesh_pt() = this;
        nod_pt->node_update_fct_id() = spine_flag;
        mesh_pt->add_node_pt( addmesh_pt->node_pt(j) );
     }
    else
     {
        zaehler++;
     }
   }
 //#ifdef PARANOID
 // Another control
   if(zaehler != addmesh_pt->nboundary_node(bound2))
    {
     std::ostringstream error_stream;
     error_stream
      <<"You have added "
      <<(zaehler-addmesh_pt->nboundary_node(bound2))
      <<" nodes too much to the mesh.\n"
      <<"(This control should be removed in case we do not want to copy all the nodes of the shared boundaries)\n";
     throw OomphLibError(error_stream.str(),
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
    }
 //#endif
  //We add the elements to the mesh
   for(unsigned i = 0; i< addmesh_pt->nelement(); i++)
   {
      ELEMENT* el_pt = dynamic_cast<ELEMENT*>( addmesh_pt->element_pt(i));
    //  FiniteElement* el_pt =    addmesh_pt->finite_element_pt(i);
     Element_pt.push_back(el_pt);
     Bulk_element_pt.push_back(el_pt );
   }
   // We reset the number of boundaries
   mesh_pt->set_nboundary(total_boundaries);
  //We reset the boundary conditions of the old mesh (the shared boundary is not more in a boundary)
     mesh_pt->remove_boundary_nodes(bound1);
     //We reset the boundary conditions of the new nodes
   for(int i=0;i<(int)(addmesh_pt->nboundary());i++)
    {
     //Loop over the boundary nodes
      for(unsigned long j =0;j<addmesh_pt->nboundary_node(i);j++)
      {
          //We do not reset the commom boundary,whose nodes will be deleted  at the end
        if(i!=bound2)
         {
           //Create a pointer to the node
           Node* node_pt =  addmesh_pt->boundary_node_pt(i,j);
           // We remove the old boundaries in case it is not yet included in a new boundary
            bool alr_included = 0;
            for(unsigned k =0;k<this->nboundary_node(i);k++)
            {
              if(node_pt == this->boundary_node_pt(i,k) )
                    alr_included = 1;
            }
            if(!alr_included)
              node_pt->remove_from_boundary(i);
           // We test again not to include the nodes which will be deleted
            if( map_bound_node[node_pt] == 0)
            {
               mesh_pt->add_boundary_node( addmesh_map_boundary[i], node_pt );
            }
             // if not we have to include to the boundarie (in the case that they were not included before)the maped nodes
            else
             {
              Node* map_node_pt =  map_bound_node[node_pt];
              if(!map_node_pt->is_on_boundary(addmesh_map_boundary[i]) )
                   mesh_pt->add_boundary_node(addmesh_map_boundary[i], map_node_pt );
             }
          }
        }
    }
 // At the end we remove the shared nodes of the second mesh for avoiding problems with memory leaking
   for(unsigned long j =0;j<addmesh_pt->nboundary_node(bound2);j++)
      delete addmesh_pt->boundary_node_pt(bound2,j);
  // We reset the number of boundaries
   mesh_pt->set_nboundary(total_boundaries);
 // Small control
 //#ifdef PARANOID
   for(unsigned i = 0; i<mesh_pt->nboundary(); i ++)
    {
     std::cout<<"Boundary "<<i
              <<" has "<<mesh_pt->nboundary_node(i)<<" nodes."<<std::endl;
    }
 //#endif
   }
References oomph::Mesh::add_boundary_node(), oomph::Mesh::add_node_pt(), oomph::Mesh::boundary_node_pt(), dmin, Global_Physical_Variables::E, oomph::Mesh::element_pt(), i, int(), oomph::Node::is_on_boundary(), j, k, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_node(), oomph::Node::ndim(), oomph::Mesh::nelement(), oomph::Mesh::nnode(), oomph::Mesh::node_pt(), oomph::SpineNode::node_update_fct_id(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Mesh::remove_boundary_nodes(), oomph::Node::remove_from_boundary(), oomph::Mesh::set_nboundary(), oomph::SpineNode::spine_mesh_pt(), sqrt(), and oomph::Node::x().
add_side_spinemesh()
template<class ELEMENT , class INTERFACE_ELEMENT > void STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::add_side_spinemesh (unsigned int bound1, CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT > * addmesh_pt, int * addmesh_map_boundary, int total_boundaries, unsigned flag) protected
 {
  //Call the generic function
  MeshHelper::merge_spine_meshes(this,bound1,addmesh_pt,addmesh_map_boundary,
                                 total_boundaries,spine_flag);
 // add the bulk elements to the mesh
   for(unsigned i = 0; i< addmesh_pt->nbulk(); i++)
   {
     this->Bulk_element_pt.push_back(addmesh_pt->bulk_element_pt(i));
   }
    // add the interface elements to the mesh
 for(unsigned i = 0; i< addmesh_pt->ninterface_element(); i++)
   {
     this->Interface_element_pt.push_back(addmesh_pt->interface_element_pt(i));
   }
 }
References CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::bulk_element_pt(), i, CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::interface_element_pt(), oomph::MeshHelper::merge_spine_meshes(), CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::nbulk(), and CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::ninterface_element().
build_single_layer_mesh()
template<class ELEMENT , class INTERFACE_ELEMENT > void STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh (TimeStepper * time_stepper_pt) protected virtual
Helper function to actually build the single-layer spine mesh (called from various constructors)
Helper function that actually builds the single-layer spine mesh based on the parameters set in the various constructors
 {
 // Axis pf simmetry
  Xsim = 0.0;
  Ysim = 0.0;
  Zsim = 1.0 * Height/2;
  // Build first canion mesh with flag 0
  CombCanSpineMesh<ELEMENT,INTERFACE_ELEMENT >* mesh1_pt = new CombCanSpineMesh<ELEMENT,INTERFACE_ELEMENT > (Nel,Nel_can,Alpha,Length_can,Height,Radius,0,time_stepper_pt);
  mesh1_pt->node_update();
 // We copy this mesh to our problem mesh
 // add the nodes to the mesh
 //we reasign the spine_nodes to point to the ptoblem mesh
  for(unsigned i = 0; i< mesh1_pt->nnode(); i++)
   {
    //Set spine update flag equal to 0 for the nodes of this function
     mesh1_pt->node_pt(i)->node_update_fct_id() = 0;
     mesh1_pt->node_pt(i)->spine_mesh_pt() = this;
     this->add_node_pt(mesh1_pt->node_pt(i));
   }
    // add the bulk elements to the mesh
  for(unsigned i = 0; i< mesh1_pt->nbulk(); i++)
   {
     Bulk_element_pt.push_back(mesh1_pt->bulk_element_pt(i));
   }
    // add the interface elements to the mesh
 for(unsigned i = 0; i< mesh1_pt->ninterface_element(); i++)
   {
     Interface_element_pt.push_back(mesh1_pt->interface_element_pt(i));
   }
 // add all the elements to the mesh
 for(unsigned i = 0; i< mesh1_pt->nelement(); i++)
   {
     Element_pt.push_back(mesh1_pt->element_pt(i));
   }
    // add the spines  to the mesh
 for(unsigned i = 0; i< mesh1_pt->nspine(); i++)
   {
     Spine_pt.push_back(mesh1_pt->spine_pt(i));
   }
 //add the boundaries
  set_nboundary( mesh1_pt->nboundary());
 for(unsigned b =0; b< mesh1_pt->nboundary(); b++)
   {
    for(unsigned i = 0; i<mesh1_pt->nboundary_node(b); i++)
     {
      // We remove the node from the old boundary mesh ( This is not necessary and it is mainly wrotten for avoiding the warning message)
      Node* node_pt =  mesh1_pt->boundary_node_pt(b,i );
      node_pt->remove_from_boundary(b);
      this->add_boundary_node( b , node_pt);
     }
   }
 // Set the outlet bulk elements
  for(unsigned long e =0;e< mesh1_pt->nbulkoutlet();e++)
   Bulk_outlet_element_pt.push_back(mesh1_pt->bulk_outlet_element_pt(e));
  this->Face_index_outlet = mesh1_pt->face_index_outlet();
  for(unsigned long e =0;e< mesh1_pt->ninterfaceline();e++)
   Interface_line_element_pt.push_back(mesh1_pt->interface_line_element_pt(e));
 //We create the tip mesh with flag 1
  CombTipSpineMesh<ELEMENT,INTERFACE_ELEMENT >* mesh2_pt = new  CombTipSpineMesh<ELEMENT,INTERFACE_ELEMENT > (Nel,Alpha,Length_tip,Height,Radius,1,time_stepper_pt);
 //Resignation pointer for the boundary conditions of the second mesh
   int addmesh_map_boundary[7];
   for(unsigned int i =0;i<7;i++)
    {
     addmesh_map_boundary[i] = i;
    }
    addmesh_map_boundary[3] = -1;
 // Add the tip mesh
     add_side_spinemesh(1, mesh2_pt ,addmesh_map_boundary, 7,1);
     std::cout<<"Tip mesh added"<<std::endl;
 //Creating the cubic mesh
    double lycubicmin = -(Length_tip + Length_liq);
     double lycubicmax = -Length_tip;
    unsigned Nzcubic =  2*Nel;
    double heightcubic = Height;
    double alphacubic = Alpha/2;
  SimpleCubicMesh<ELEMENT >* mesh3_pt = new  SimpleCubicMesh<ELEMENT >(Nel,Nel_liq,Nzcubic,0,alphacubic,lycubicmin,lycubicmax,0, heightcubic,time_stepper_pt);
 // Set the inlet elementes
  //  int nxin = mesh3_pt->nx();  //It is not working in this way (ask Andrew)
  //  int nyin = mesh3_pt->ny();
  //  int nzin = mesh3_pt->nz();
  int nxin = Nel;
  int nyin = Nel_liq;
  int nzin = Nzcubic;
    int jin = 0;
     for(int k =0; k<nzin;k++)
     {
      for(int i =0; i<nxin;i++)
       {
        ELEMENT *el_pt = dynamic_cast<ELEMENT*>(mesh3_pt->element_pt(i+jin*nxin+k*nxin*nyin));
        Bulk_inlet_element_pt.push_back(el_pt);
       }
     }
   // Constant coordinate for the face inlet elementes
    Face_index_inlet = -2;
 //Resignation pointer for the boundary conditions of the third mesh
    for(unsigned int i =0;i<7;i++)
    {
     addmesh_map_boundary[i] = i;
    }
     addmesh_map_boundary[3] = -1;
     addmesh_map_boundary[5] = 6;
 // Add the cubic mesh with flag 2
   add_mesh(1, mesh3_pt, addmesh_map_boundary,7,2);
 //   cout<<"Cubic mesh added"<<endl;
    std::cout<<"The complete mesh consists of  "<<nbulk()<< " bulk elements and "<<ninterface_element()<<" interface elements"<<std::endl;
 // At the end we destroy the block meshes in two steps
 // 1. We disconect the meshesh from the nodes and elements (if not we delete them at the time we delete the meshes)
   mesh1_pt->flush_spine_element_and_node_storage();
   mesh2_pt->flush_spine_element_and_node_storage();
   mesh3_pt->flush_element_and_node_storage();
 //2. Simply delete (this function can give a segmentation fault error when there are spines still attached to the old update functions written in the constructor)
   delete mesh1_pt;
   delete mesh2_pt;
   delete mesh3_pt;
 }
References TanhSolnForAdvectionDiffusion::Alpha, b, oomph::Mesh::boundary_node_pt(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::bulk_element_pt(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::bulk_outlet_element_pt(), e(), oomph::Mesh::element_pt(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::face_index_outlet(), oomph::Mesh::flush_element_and_node_storage(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::flush_spine_element_and_node_storage(), CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::flush_spine_element_and_node_storage(), GlobalParameters::Height, i, CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::interface_element_pt(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::interface_line_element_pt(), k, Global_Physical_Variables::Length_can, Global_Physical_Variables::Length_liq, Global_Physical_Variables::Length_tip, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_node(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::nbulk(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::nbulkoutlet(), oomph::Mesh::nelement(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::ninterface_element(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::ninterfaceline(), oomph::Mesh::nnode(), oomph::SpineMesh::node_pt(), oomph::SpineMesh::node_update(), oomph::SpineNode::node_update_fct_id(), oomph::SpineMesh::nspine(), Global_Physical_Variables::Radius, oomph::Node::remove_from_boundary(), oomph::SpineNode::spine_mesh_pt(), and oomph::SpineMesh::spine_pt().
Referenced by STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::STSpineMesh().
bulk_element_pt()
template<class ELEMENT , class INTERFACE_ELEMENT > FiniteElement* & STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::bulk_element_pt (const unsigned long & i) inline
Access functions for pointers to elements in bulk.
   {return Bulk_element_pt[i];}
References i.
bulk_inlet_element_pt()
template<class ELEMENT , class INTERFACE_ELEMENT > FiniteElement* & STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::bulk_inlet_element_pt (const unsigned long & i) inline
   {return Bulk_inlet_element_pt[i];}
References i.
bulk_outlet_element_pt()
template<class ELEMENT , class INTERFACE_ELEMENT > FiniteElement* & STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::bulk_outlet_element_pt (const unsigned long & i) inline
   {return Bulk_outlet_element_pt[i];}
References i.
face_index_inlet()
template<class ELEMENT , class INTERFACE_ELEMENT > int STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::face_index_inlet () inline
 {return  Face_index_inlet;}
face_index_outlet()
template<class ELEMENT , class INTERFACE_ELEMENT > int STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::face_index_outlet () inline
 {return  Face_index_outlet;}
full_output()
template<class ELEMENT , class INTERFACE_ELEMENT > void STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::full_output (std::ostream & outfile, const unsigned & n_plot) inline
General node update function implements pure virtual function defined in SpineMesh base class and performs specific node update actions: along vertical spines
  {
  //Loop over the elements and call their output functions
  //Assign Element_pt_range
  unsigned long Element_pt_range = Bulk_element_pt.size();
  for(unsigned long e=0;e<Element_pt_range;e++)
   {
    // Try to cast to Navier Stokes Element
    NavierStokesEquations<3>* el_pt=dynamic_cast<NavierStokesEquations<3>* >(Bulk_element_pt[e]);
    if (el_pt==0)
     {
      oomph_info << "Can't execute output(...) for non Navier Stokes Elements"
                << std::endl;
     }
    else
     {
      el_pt->full_output(outfile,n_plot);
     }
   }
  }
References e(), oomph::NavierStokesEquations< DIM >::full_output(), and oomph::oomph_info.
interface_element_pt()
template<class ELEMENT , class INTERFACE_ELEMENT > FiniteElement* & STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::interface_element_pt (const unsigned long & i) inline
Access functions for pointers to interface elements.
   {return Interface_element_pt[i];}
References i.
interface_line_element_pt()
template<class ELEMENT , class INTERFACE_ELEMENT > FiniteElement* & STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::interface_line_element_pt (const unsigned long & i) inline
Access functions for pointers to interface line elements.
   {return Interface_line_element_pt[i];}
References i.
nbulk()
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned long STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::nbulk () const inline
Number of elements in bulk.
 {return Bulk_element_pt.size();}
nbulkinlet()
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned long STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::nbulkinlet () const inline
 {return Bulk_inlet_element_pt.size();}
nbulkoutlet()
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned long STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::nbulkoutlet () const inline
 {return Bulk_outlet_element_pt.size();}
ninterface_element()
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned long STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::ninterface_element () const inline
Number of elements on interface.
 {return Interface_element_pt.size();}
ninterfaceline()
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned long STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::ninterfaceline () const inline
Number of elements on the line interface.
 {return Interface_line_element_pt.size();}
spine_node_update()
template<class ELEMENT , class INTERFACE_ELEMENT > virtual void STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update (SpineNode * spine_node_pt) inline virtual
Update function for given spine node – this must be implemented by all specific SpineMeshes.
Implements oomph::SpineMesh.
   {
  //Get de flag
    unsigned flag = spine_node_pt->node_update_fct_id();
 // Lets first chech whether it is a real SpinNode (not in the liquid mesh)
    if(flag != 2)
     {
      //Get fraction along the spine
      double W = spine_node_pt->fraction();
      //Get spine height
      double H = spine_node_pt->h();
      //Get the position of the node at the origin
       Vector<double> origin_pt(3);
      origin_pt[0] = spine_node_pt->spine_pt()->geom_parameter(0);
      origin_pt[1] = spine_node_pt->spine_pt()->geom_parameter(1);
      origin_pt[2] = spine_node_pt->spine_pt()->geom_parameter(2);
      if(flag ==0) // Canyon mesh
       {
         //set scale norm vector
         double norm = sqrt( (Xsim -  origin_pt[0] ) *  (Xsim -  origin_pt[0] )+(Zsim -  origin_pt[2] ) *  (Zsim -  origin_pt[2])  );
         //Set th x coordinate
         spine_node_pt->x(0) = origin_pt[0] + H*W* (Xsim -  origin_pt[0] )/norm;
         //Set the value of z
         spine_node_pt->x(2) = origin_pt[2] + H*W* (Zsim -  origin_pt[2] )/norm;
       }
      if(flag ==1) //Tip mesh
       {
         //set scale norm vector
          double norm = sqrt( (Xsim -  origin_pt[0] ) *  (Xsim -  origin_pt[0] )+ (Ysim -  origin_pt[1] ) *  (Ysim -  origin_pt[1] ) +
                              (Zsim-  origin_pt[2] ) *  (Zsim -  origin_pt[2])  );
         //Set the x coordinate
          spine_node_pt->x(0) = origin_pt[0] + H*W* (Xsim -  origin_pt[0] )/norm;
          //Set the y coordinate
          spine_node_pt->x(1) = origin_pt[1] + H*W* (Ysim -  origin_pt[1] )/norm;
          //Set the value of z
           spine_node_pt->x(2) = origin_pt[2] + H*W* (Zsim -  origin_pt[2] )/norm;
       }
     }
   }
References oomph::SpineNode::fraction(), oomph::Spine::geom_parameter(), H, oomph::SpineNode::h(), oomph::SpineNode::node_update_fct_id(), oomph::SpineNode::spine_pt(), sqrt(), oomph::QuadTreeNames::W, and oomph::Node::x().
surface_output()
template<class ELEMENT , class INTERFACE_ELEMENT > void STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::surface_output (std::ostream & outfile, const unsigned & n_plot) inline
  {
  //Loop over the elements and call their output functions
  //Assign Element_pt_range
  unsigned long Element_pt_range = Interface_element_pt.size();
  for(unsigned long e=0;e<Element_pt_range;e++)
   {
    // Try to cast to Navier Stokes Element
    FiniteElement* el_pt=dynamic_cast<FiniteElement* >(Interface_element_pt[e]);
    if (el_pt==0)
     {
      oomph_info << "Can't execute surface output(...) for non Finite Element elements"
                << std::endl;
     }
    else
     {
      el_pt->output(outfile,n_plot);
     }
   }
  }
References e(), oomph::oomph_info, and oomph::FiniteElement::output().
Member Data Documentation
Alpha
template<class ELEMENT , class INTERFACE_ELEMENT > double STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Alpha protected
Aspect ratio, length, height and radius.
Bulk_element_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Vector<FiniteElement *> STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Bulk_element_pt protected
Vector of pointers to element in the fluid layer.
Bulk_inlet_element_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Vector<FiniteElement *> STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Bulk_inlet_element_pt protected
Vector of pointers to the bulk inlet elements in the fluid layer.
Bulk_outlet_element_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Vector<FiniteElement *> STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Bulk_outlet_element_pt protected
Vector of pointers to the bulk outlet elements in the fluid layer.
Face_index_inlet
template<class ELEMENT , class INTERFACE_ELEMENT > int STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Face_index_inlet protected
Face_index_outlet
template<class ELEMENT , class INTERFACE_ELEMENT > int STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Face_index_outlet protected
Height
template<class ELEMENT , class INTERFACE_ELEMENT > double STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Height protected
Interface_element_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Vector<FiniteElement *> STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Interface_element_pt protected
Vector of pointers to interface elements.
Interface_line_element_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Vector<FiniteElement *> STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Interface_line_element_pt protected
Length_can
template<class ELEMENT , class INTERFACE_ELEMENT > double STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Length_can protected
Length_liq
template<class ELEMENT , class INTERFACE_ELEMENT > double STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Length_liq protected
Length_tip
template<class ELEMENT , class INTERFACE_ELEMENT > double STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Length_tip protected
Nel
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned int STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Nel protected
Nel_can
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned int STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Nel_can protected
Nel_liq
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned int STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Nel_liq protected
Radius
template<class ELEMENT , class INTERFACE_ELEMENT > double STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Radius protected
Xsim
template<class ELEMENT , class INTERFACE_ELEMENT > double STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Xsim protected
Ysim
template<class ELEMENT , class INTERFACE_ELEMENT > double STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Ysim protected
Zsim
template<class ELEMENT , class INTERFACE_ELEMENT > double STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Zsim protected
The documentation for this class was generated from the following file:
st_mesh.h