MercuryDPM: Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version > Class Template Reference
Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version > Class Template Reference
#include <AssignEvaluator.h>
Public Types
typedef DstEvaluatorTypeT DstEvaluatorType
typedef SrcEvaluatorTypeT SrcEvaluatorType
typedef DstEvaluatorType::Scalar Scalar
typedef copy_using_evaluator_traits< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor > AssignmentTraits
typedef AssignmentTraits::PacketType PacketType
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE generic_dense_assignment_kernel (DstEvaluatorType &dst, const SrcEvaluatorType &src, const Functor &func, DstXprType &dstExpr)
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index innerSize () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index outerSize () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index outerStride () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC DstEvaluatorType & dstEvaluator () EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC const SrcEvaluatorType & srcEvaluator () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignCoeff (Index row, Index col)
Assign src(row,col) to dst(row,col) through the assignment functor.
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignCoeff (Index index)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignCoeffByOuterInner (Index outer, Index inner)
template<int StoreMode, int LoadMode, typename Packet >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignPacket (Index row, Index col)
template<int StoreMode, int LoadMode, typename Packet >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignPacket (Index index)
template<int StoreMode, int LoadMode, typename Packet >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignPacketByOuterInner (Index outer, Index inner)
EIGEN_DEVICE_FUNC const Scalar * dstDataPtr () const
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rowIndexByOuterInner (Index outer, Index inner)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index colIndexByOuterInner (Index outer, Index inner)
Protected Types
typedef DstEvaluatorTypeT::XprType DstXprType
typedef SrcEvaluatorTypeT::XprType SrcXprType
Protected Attributes
DstEvaluatorType & m_dst
const SrcEvaluatorType & m_src
const Functor & m_functor
DstXprType & m_dstExpr
Member Typedef Documentation
AssignmentTraits
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> typedef copy_using_evaluator_traits<DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor> Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::AssignmentTraits
DstEvaluatorType
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> typedef DstEvaluatorTypeT Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::DstEvaluatorType
DstXprType
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> typedef DstEvaluatorTypeT::XprType Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::DstXprType protected
PacketType
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> typedef AssignmentTraits::PacketType Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::PacketType
Scalar
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> typedef DstEvaluatorType::Scalar Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::Scalar
SrcEvaluatorType
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> typedef SrcEvaluatorTypeT Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::SrcEvaluatorType
SrcXprType
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> typedef SrcEvaluatorTypeT::XprType Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::SrcXprType protected
Constructor & Destructor Documentation
generic_dense_assignment_kernel()
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::generic_dense_assignment_kernel (DstEvaluatorType & dst, const SrcEvaluatorType & src, const Functor & func, DstXprType & dstExpr) inline
       : m_dst(dst), m_src(src), m_functor(func), m_dstExpr(dstExpr) {
 #ifdef EIGEN_DEBUG_ASSIGN
     AssignmentTraits::debug();
 #endif
   }
Member Function Documentation
assignCoeff() [1/2]
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignCoeff (Index index) inline
See also
assignCoeff(Index,Index)
{
     m_functor.assignCoeff(m_dst.coeffRef(index), m_src.coeff(index));
   }
assignCoeff() [2/2]
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignCoeff (Index row, Index col) inline
Assign src(row,col) to dst(row,col) through the assignment functor.
{
     m_functor.assignCoeff(m_dst.coeffRef(row, col), m_src.coeff(row, col));
   }
References col(), and row().
assignCoeffByOuterInner()
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignCoeffByOuterInner (Index outer, Index inner) inline
See also
assignCoeff(Index,Index)
{
     Index row = rowIndexByOuterInner(outer, inner);
     Index col = colIndexByOuterInner(outer, inner);
     assignCoeff(row, col);
   }
References col(), and row().
assignPacket() [1/2]
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> template<int StoreMode, int LoadMode, typename Packet > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignPacket (Index index) inline
{
     m_functor.template assignPacket<StoreMode>(&m_dst.coeffRef(index), m_src.template packet<LoadMode, Packet>(index));
   }
assignPacket() [2/2]
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> template<int StoreMode, int LoadMode, typename Packet > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignPacket (Index row, Index col) inline
{
     m_functor.template assignPacket<StoreMode>(&m_dst.coeffRef(row, col),
                                                m_src.template packet<LoadMode, Packet>(row, col));
   }
References col(), and row().
assignPacketByOuterInner()
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> template<int StoreMode, int LoadMode, typename Packet > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignPacketByOuterInner (Index outer, Index inner) inline
{
     Index row = rowIndexByOuterInner(outer, inner);
     Index col = colIndexByOuterInner(outer, inner);
     assignPacket<StoreMode, LoadMode, Packet>(row, col);
   }
References col(), and row().
colIndexByOuterInner()
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::colIndexByOuterInner (Index outer, Index inner) inline static
{
     typedef typename DstEvaluatorType::ExpressionTraits Traits;
     return int(Traits::ColsAtCompileTime) == 1          ? 0
            : int(Traits::RowsAtCompileTime) == 1        ? inner
            : int(DstEvaluatorType::Flags) & RowMajorBit ? inner
                                                         : outer;
   }
References int(), and Eigen::RowMajorBit.
cols()
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::cols () const inline
 { return m_dstExpr.cols(); }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
dstDataPtr()
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> EIGEN_DEVICE_FUNC const Scalar* Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::dstDataPtr () const inline
 { return m_dstExpr.data(); }
dstEvaluator()
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> EIGEN_DEVICE_FUNC DstEvaluatorType& Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::dstEvaluator () inline
 { return m_dst; }
innerSize()
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::innerSize () const inline
 { return m_dstExpr.innerSize(); }
outerSize()
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::outerSize () const inline
 { return m_dstExpr.outerSize(); }
outerStride()
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::outerStride () const inline
 { return m_dstExpr.outerStride(); }
rowIndexByOuterInner()
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::rowIndexByOuterInner (Index outer, Index inner) inline static
{
     typedef typename DstEvaluatorType::ExpressionTraits Traits;
     return int(Traits::RowsAtCompileTime) == 1          ? 0
            : int(Traits::ColsAtCompileTime) == 1        ? inner
            : int(DstEvaluatorType::Flags) & RowMajorBit ? outer
                                                         : inner;
   }
References int(), and Eigen::RowMajorBit.
rows()
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::rows () const inline
 { return m_dstExpr.rows(); }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
size()
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::size () const inline
 { return m_dstExpr.size(); }
srcEvaluator()
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> EIGEN_DEVICE_FUNC const SrcEvaluatorType& Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::srcEvaluator () const inline
 { return m_src; }
Member Data Documentation
m_dst
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> DstEvaluatorType& Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_dst protected
Referenced by Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacket().
m_dstExpr
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> DstXprType& Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_dstExpr protected
m_functor
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> const Functor& Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_functor protected
m_src
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT , typename Functor , int Version = Specialized> const SrcEvaluatorType& Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_src protected
Referenced by Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacket().
The documentation for this class was generated from the following file:
AssignEvaluator.h