MercuryDPM: Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device > Struct Template Reference
#include <TensorEvaluator.h>
Classes
struct TensorSelectOpBlockFactory
Public Types
enum {
IsAligned = TensorEvaluator<ThenArgType, Device>::IsAligned & TensorEvaluator<ElseArgType, Device>::IsAligned , PacketAccess , BlockAccess , PreferBlockAccess ,
CoordAccess = false , RawAccess = false
}
typedef TensorSelectOp< IfArgType, ThenArgType, ElseArgType > XprType
typedef XprType::Scalar Scalar
using TernarySelectOp = internal::scalar_boolean_select_op< typename internal::traits< ThenArgType >::Scalar, typename internal::traits< ElseArgType >::Scalar, typename internal::traits< IfArgType >::Scalar >
typedef XprType::Index Index
typedef internal::traits< XprType >::Scalar CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef TensorEvaluator< IfArgType, Device >::Dimensions Dimensions
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorBlockDescriptor< NumDims, Index > TensorBlockDesc
typedef internal::TensorBlockScratchAllocator< Device > TensorBlockScratch
typedef TensorEvaluator< const IfArgType, Device >::TensorBlock IfArgTensorBlock
typedef TensorEvaluator< const ThenArgType, Device >::TensorBlock ThenArgTensorBlock
typedef TensorEvaluator< const ElseArgType, Device >::TensorBlock ElseArgTensorBlock
typedef internal::TensorTernaryExprBlock< TensorSelectOpBlockFactory, IfArgTensorBlock, ThenArgTensorBlock, ElseArgTensorBlock > TensorBlock
Public Member Functions
EIGEN_DEVICE_FUNC TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC CoeffReturnType coeff (Index index) const
template<int LoadMode, bool UseTernary = TernaryPacketAccess, std::enable_if_t<!UseTernary, bool > = true>
EIGEN_DEVICE_FUNC PacketReturnType packet (Index index) const
template<int LoadMode, bool UseTernary = TernaryPacketAccess, std::enable_if_t< UseTernary, bool > = true>
EIGEN_DEVICE_FUNC PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements getResourceRequirements () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock block (TensorBlockDesc &desc, TensorBlockScratch &scratch, bool=false) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EvaluatorPointerType data () const
Static Public Attributes
static constexpr bool TernaryPacketAccess
static constexpr int Layout = TensorEvaluator<IfArgType, Device>::Layout
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int NumDims = internal::array_size<Dimensions>::value
Private Attributes
TensorEvaluator< IfArgType, Device > m_condImpl
TensorEvaluator< ThenArgType, Device > m_thenImpl
TensorEvaluator< ElseArgType, Device > m_elseImpl
Member Typedef Documentation
CoeffReturnType
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > typedef internal::traits<XprType>::Scalar Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::CoeffReturnType
Dimensions
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > typedef TensorEvaluator<IfArgType, Device>::Dimensions Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::Dimensions
ElseArgTensorBlock
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > typedef TensorEvaluator<const ElseArgType, Device>::TensorBlock Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::ElseArgTensorBlock
EvaluatorPointerType
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::EvaluatorPointerType
IfArgTensorBlock
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > typedef TensorEvaluator<const IfArgType, Device>::TensorBlock Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::IfArgTensorBlock
Index
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::Index
PacketReturnType
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::PacketReturnType
Scalar
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::Scalar
Storage
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::Storage
TensorBlock
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > typedef internal::TensorTernaryExprBlock<TensorSelectOpBlockFactory, IfArgTensorBlock, ThenArgTensorBlock, ElseArgTensorBlock> Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::TensorBlock
TensorBlockDesc
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > typedef internal::TensorBlockDescriptor<NumDims, Index> Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::TensorBlockDesc
TensorBlockScratch
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > typedef internal::TensorBlockScratchAllocator<Device> Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::TensorBlockScratch
TernarySelectOp
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > using Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::TernarySelectOp = internal::scalar_boolean_select_op<typename internal::traits<ThenArgType>::Scalar, typename internal::traits<ElseArgType>::Scalar, typename internal::traits<IfArgType>::Scalar>
ThenArgTensorBlock
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > typedef TensorEvaluator<const ThenArgType, Device>::TensorBlock Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::ThenArgTensorBlock
XprType
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > typedef TensorSelectOp<IfArgType, ThenArgType, ElseArgType> Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = TensorEvaluator<ThenArgType, Device>::IsAligned & TensorEvaluator<ElseArgType, Device>::IsAligned,
     PacketAccess = (TensorEvaluator<ThenArgType, Device>::PacketAccess &&
                     TensorEvaluator<ElseArgType, Device>::PacketAccess && PacketType<Scalar, Device>::HasBlend) ||
                    TernaryPacketAccess,
     BlockAccess = TensorEvaluator<IfArgType, Device>::BlockAccess &&
                   TensorEvaluator<ThenArgType, Device>::BlockAccess &&
                   TensorEvaluator<ElseArgType, Device>::BlockAccess,
     PreferBlockAccess = TensorEvaluator<IfArgType, Device>::PreferBlockAccess ||
                         TensorEvaluator<ThenArgType, Device>::PreferBlockAccess ||
                         TensorEvaluator<ElseArgType, Device>::PreferBlockAccess,
     CoordAccess = false,  // to be implemented
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > EIGEN_DEVICE_FUNC Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_condImpl(op.ifExpression(), device),
         m_thenImpl(op.thenExpression(), device),
         m_elseImpl(op.elseExpression(), device) {
     EIGEN_STATIC_ASSERT((static_cast<int>(TensorEvaluator<IfArgType, Device>::Layout) ==
                          static_cast<int>(TensorEvaluator<ThenArgType, Device>::Layout)),
                         YOU_MADE_A_PROGRAMMING_MISTAKE);
     EIGEN_STATIC_ASSERT((static_cast<int>(TensorEvaluator<IfArgType, Device>::Layout) ==
                          static_cast<int>(TensorEvaluator<ElseArgType, Device>::Layout)),
                         YOU_MADE_A_PROGRAMMING_MISTAKE);
     eigen_assert(dimensions_match(m_condImpl.dimensions(), m_thenImpl.dimensions()));
     eigen_assert(dimensions_match(m_thenImpl.dimensions(), m_elseImpl.dimensions()));
   }
References Eigen::dimensions_match(), eigen_assert, and EIGEN_STATIC_ASSERT.
Member Function Documentation
block()
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::block (TensorBlockDesc & desc, TensorBlockScratch & scratch, bool = false) const inline
{
     // It's unsafe to pass destination buffer to underlying expressions, because
     // output might be aliased with one of the inputs.
     desc.DropDestinationBuffer();
     return TensorBlock(m_condImpl.block(desc, scratch), m_thenImpl.block(desc, scratch),
                        m_elseImpl.block(desc, scratch), TensorSelectOpBlockFactory());
   }
References Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::DropDestinationBuffer().
cleanup()
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::cleanup () inline
{
     m_condImpl.cleanup();
     m_thenImpl.cleanup();
     m_elseImpl.cleanup();
   }
Referenced by framework.Frame::__init__().
coeff()
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > EIGEN_DEVICE_FUNC CoeffReturnType Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::coeff (Index index) const inline
{
     return m_condImpl.coeff(index) ? m_thenImpl.coeff(index) : m_elseImpl.coeff(index);
   }
costPerCoeff()
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     return m_condImpl.costPerCoeff(vectorized) +
            m_thenImpl.costPerCoeff(vectorized).cwiseMax(m_elseImpl.costPerCoeff(vectorized));
   }
References Eigen::TensorOpCost::cwiseMax().
data()
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EvaluatorPointerType Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > EIGEN_DEVICE_FUNC const Dimensions& Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::dimensions () const inline
{
     // TODO: use then or else impl instead if they happen to be known at compile time.
     return m_condImpl.dimensions();
   }
evalSubExprsIfNeeded()
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
{
     m_condImpl.evalSubExprsIfNeeded(NULL);
     m_thenImpl.evalSubExprsIfNeeded(NULL);
     m_elseImpl.evalSubExprsIfNeeded(NULL);
     return true;
   }
getResourceRequirements()
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::getResourceRequirements () const inline
{
     auto then_req = m_thenImpl.getResourceRequirements();
     auto else_req = m_elseImpl.getResourceRequirements();
     auto merged_req = internal::TensorBlockResourceRequirements::merge(then_req, else_req);
     merged_req.cost_per_coeff = then_req.cost_per_coeff.cwiseMax(else_req.cost_per_coeff);
     return internal::TensorBlockResourceRequirements::merge(m_condImpl.getResourceRequirements(), merged_req);
   }
References Eigen::internal::TensorBlockResourceRequirements::merge().
packet() [1/2]
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > template<int LoadMode, bool UseTernary = TernaryPacketAccess, std::enable_if_t<!UseTernary, bool > = true> EIGEN_DEVICE_FUNC PacketReturnType Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::packet (Index index) const inline
{
     internal::Selector<PacketSize> select;
     EIGEN_UNROLL_LOOP
     for (Index i = 0; i < PacketSize; ++i) {
       select.select[i] = m_condImpl.coeff(index + i);
     }
     return internal::pblend(select, m_thenImpl.template packet<LoadMode>(index),
                             m_elseImpl.template packet<LoadMode>(index));
   }
References EIGEN_UNROLL_LOOP, i, Eigen::TensorEvaluator< Derived, Device >::PacketSize, Eigen::internal::pblend(), and Eigen::internal::Selector< N >::select.
packet() [2/2]
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > template<int LoadMode, bool UseTernary = TernaryPacketAccess, std::enable_if_t< UseTernary, bool > = true> EIGEN_DEVICE_FUNC PacketReturnType Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::packet (Index index) const inline
{
     return TernarySelectOp().template packetOp<PacketReturnType>(m_thenImpl.template packet<LoadMode>(index),
                                                                  m_elseImpl.template packet<LoadMode>(index),
                                                                  m_condImpl.template packet<LoadMode>(index));
   }
Member Data Documentation
Layout
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::Layout = TensorEvaluator<IfArgType, Device>::Layout static constexpr
m_condImpl
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > TensorEvaluator<IfArgType, Device> Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::m_condImpl private
m_elseImpl
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > TensorEvaluator<ElseArgType, Device> Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::m_elseImpl private
m_thenImpl
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > TensorEvaluator<ThenArgType, Device> Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::m_thenImpl private
NumDims
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::NumDims = internal::array_size<Dimensions>::value static constexpr
PacketSize
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
TernaryPacketAccess
template<typename IfArgType , typename ThenArgType , typename ElseArgType , typename Device > constexpr bool Eigen::TensorEvaluator< const TensorSelectOp< IfArgType, ThenArgType, ElseArgType >, Device >::TernaryPacketAccess static constexpr
Initial value:
=
      TensorEvaluator<ThenArgType, Device>::PacketAccess && TensorEvaluator<ElseArgType, Device>::PacketAccess &&
      TensorEvaluator<IfArgType, Device>::PacketAccess && internal::functor_traits<TernarySelectOp>::PacketAccess
The documentation for this struct was generated from the following file:
TensorEvaluator.h