MercuryDPM: Eigen::internal::generic_j0< T, float > Struct Template Reference
Eigen::internal::generic_j0< T, float > Struct Template Reference
#include <BesselFunctionsImpl.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T run (const T &x)
Member Function Documentation
run()
template<typename T > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T Eigen::internal::generic_j0< T, float >::run (const T & x) inline static
{
     /* j0f.c
      *  Bessel function of order zero
      *
      *
      *
      * SYNOPSIS:
      *
      * float x, y, j0f();
      *
      * y = j0f( x );
      *
      *
      *
      * DESCRIPTION:
      *
      * Returns Bessel function of order zero of the argument.
      *
      * The domain is divided into the intervals [0, 2] and
      * (2, infinity). In the first interval the following polynomial
      * approximation is used:
      *
      *
      *        2         2         2
      * (w - r  ) (w - r  ) (w - r  ) P(w)
      *       1         2         3
      *
      *            2
      * where w = x  and the three r's are zeros of the function.
      *
      * In the second interval, the modulus and phase are approximated
      * by polynomials of the form Modulus(x) = sqrt(1/x) Q(1/x)
      * and Phase(x) = x + 1/x R(1/x^2) - pi/4.  The function is
      *
      *   j0(x) = Modulus(x) cos( Phase(x) ).
      *
      *
      *
      * ACCURACY:
      *
      *                      Absolute error:
      * arithmetic   domain     # trials      peak         rms
      *    IEEE      0, 2        100000      1.3e-7      3.6e-8
      *    IEEE      2, 32       100000      1.9e-7      5.4e-8
      *
      */
     const float JP[] = {-6.068350350393235E-008f, 6.388945720783375E-006f, -3.969646342510940E-004f,
                         1.332913422519003E-002f, -1.729150680240724E-001f};
     const float MO[] = {-6.838999669318810E-002f, 1.864949361379502E-001f,  -2.145007480346739E-001f,
                         1.197549369473540E-001f,  -3.560281861530129E-003f, -4.969382655296620E-002f,
                         -3.355424622293709E-006f, 7.978845717621440E-001f};
     const float PH[] = {3.242077816988247E+001f,  -3.630592630518434E+001f, 1.756221482109099E+001f,
                         -4.974978466280903E+000f, 1.001973420681837E+000f,  -1.939906941791308E-001f,
                         6.490598792654666E-002f,  -1.249992184872738E-001f};
     const T DR1 = pset1<T>(5.78318596294678452118f);
     const T NEG_PIO4F = pset1<T>(-0.7853981633974483096f); /* -pi / 4 */
     T y = pabs(x);
     T z = pmul(y, y);
     T y_le_two = pselect(pcmp_lt(y, pset1<T>(1.0e-3f)), pmadd(z, pset1<T>(-0.25f), pset1<T>(1.0f)),
                          pmul(psub(z, DR1), internal::ppolevl<T, 4>::run(z, JP)));
     T q = pdiv(pset1<T>(1.0f), y);
     T w = prsqrt(y);
     T p = pmul(w, internal::ppolevl<T, 7>::run(q, MO));
     w = pmul(q, q);
     T yn = pmadd(q, internal::ppolevl<T, 7>::run(w, PH), NEG_PIO4F);
     T y_gt_two = pmul(p, pcos(padd(yn, y)));
     return pselect(pcmp_le(y, pset1<T>(2.0)), y_le_two, y_gt_two);
   }
References p, Eigen::internal::pabs(), Eigen::internal::padd(), Eigen::internal::pcmp_le(), Eigen::internal::pcmp_lt(), Eigen::internal::pcos(), Eigen::internal::pdiv(), Eigen::internal::pmadd(), Eigen::internal::pmul(), Eigen::internal::prsqrt(), Eigen::internal::pselect(), Eigen::internal::psub(), Eigen::numext::q, w, plotDoE::x, and Eigen::internal::y.
The documentation for this struct was generated from the following file:
BesselFunctionsImpl.h