MercuryDPM: oomph::MacroElement Class Reference
oomph::MacroElement Class Reference abstract
#include <macro_element.h>
Public Member Functions
MacroElement (Domain *domain_pt, const unsigned &macro_element_number)
MacroElement ()
Default constructor (empty and broken)
MacroElement (const MacroElement &dummy)=delete
Broken copy constructor.
void operator= (const MacroElement &)=delete
Broken assignment operator.
virtual ~MacroElement ()
Empty destructor.
void output (std::ostream &outfile, const int &nplot)
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &nplot)=0
void macro_map (const Vector< double > &s, Vector< double > &r)
The mapping from local to global coordinates at the current time : r(s)
virtual void macro_map (const unsigned &t, const Vector< double > &s, Vector< double > &r)=0
virtual void macro_map (const double &t, const Vector< double > &s, Vector< double > &r)
Get global position r(s) at continuous time value, t.
virtual void output_macro_element_boundaries (std::ostream &outfile, const unsigned &nplot)=0
Output all macro element boundaries as tecplot zones.
virtual void assemble_macro_to_eulerian_jacobian (const unsigned &t, const Vector< double > &s, DenseMatrix< double > &jacobian)
virtual void assemble_macro_to_eulerian_jacobian2 (const unsigned &t, const Vector< double > &s, DenseMatrix< double > &jacobian2)
void assemble_macro_to_eulerian_jacobian (const Vector< double > &s, DenseMatrix< double > &jacobian)
void assemble_macro_to_eulerian_jacobian2 (const Vector< double > &s, DenseMatrix< double > &jacobian2)
unsigned & macro_element_number ()
Access function to the Macro_element_number.
Domain *& domain_pt ()
Access function to the Domain_pt.
Protected Attributes
Domain * Domain_pt
Pointer to domain.
unsigned Macro_element_number
What is the number of the current macro element within its domain.
Detailed Description
Base class for MacroElement s that are used during mesh refinement in domains with curvlinear and/or time-dependent boundaries; see the description of the Domain class for more details.
A macro element provides a parametrisation of a sub-domain by providing a mapping between a set of local coordinates \({\bf S} \) and global coordinates \({\bf r} ({\bf S}) \) . This must be implemented in the function
MacroElement::macro_map(...)
The time-dependent version of the macro map returns the mapping from local to global coordinates: \({\bf r} (t,{\bf S}) \) where t is the discrete timelevel: t=0: current time; t>0: previous timestep.
The MacroElement s establish the current (and previous) domain shape via member function pointers to the Domain 's
Domain::macro_element_boundary(...)
member function.
Constructor & Destructor Documentation
MacroElement() [1/3]
oomph::MacroElement::MacroElement (Domain * domain_pt, const unsigned & macro_element_number) inline
Constructor: Pass pointer to Domain and the number of the MacroElement within that Domain.
       : Domain_pt(domain_pt), Macro_element_number(macro_element_number)
     {
 #ifdef LEAK_CHECK
       LeakCheckNames::MacroElement_build += 1;
 #endif
     }
MacroElement() [2/3]
oomph::MacroElement::MacroElement () inline
Default constructor (empty and broken)
     {
       throw OomphLibError("Don't call empty constructor for MacroElement!",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
MacroElement() [3/3]
oomph::MacroElement::MacroElement (const MacroElement & dummy) delete
Broken copy constructor.
~MacroElement()
virtual oomph::MacroElement::~MacroElement () inline virtual
Empty destructor.
     {
 #ifdef LEAK_CHECK
       LeakCheckNames::MacroElement_build -= 1;
 #endif
     }
Member Function Documentation
assemble_macro_to_eulerian_jacobian() [1/2]
virtual void oomph::MacroElement::assemble_macro_to_eulerian_jacobian (const unsigned & t, const Vector< double > & s, DenseMatrix< double > & jacobian) inline virtual
the jacobian of the mapping from the macro coordinates to the global coordinates
Reimplemented in oomph::QMacroElement< 2 >.
     {
       // error message stream
       std::ostringstream error_message;
       error_message << "assemble_macro_to_eulerian_jacobian(...) not \n"
                     << "implemented for this element\n"
                     << std::endl;
       // throw error
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by assemble_macro_to_eulerian_jacobian().
assemble_macro_to_eulerian_jacobian() [2/2]
void oomph::MacroElement::assemble_macro_to_eulerian_jacobian (const Vector< double > & s, DenseMatrix< double > & jacobian) inline
Assembles the jacobian of the mapping from the macro coordinates to the global coordinates
     {
       unsigned t = 0;
       assemble_macro_to_eulerian_jacobian(t, s, jacobian);
     }
References assemble_macro_to_eulerian_jacobian(), s, and plotPSD::t.
assemble_macro_to_eulerian_jacobian2() [1/2]
virtual void oomph::MacroElement::assemble_macro_to_eulerian_jacobian2 (const unsigned & t, const Vector< double > & s, DenseMatrix< double > & jacobian2) inline virtual
Assembles the second derivative jacobian of the mapping from the macro coordinates to the global coordinates
Reimplemented in oomph::QMacroElement< 2 >.
     {
       // error message stream
       std::ostringstream error_message;
       error_message << "assemble_macro_to_eulerian_jacobian2(...) not \n"
                     << "implemented for this element\n"
                     << std::endl;
       // throw error
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by assemble_macro_to_eulerian_jacobian2().
assemble_macro_to_eulerian_jacobian2() [2/2]
void oomph::MacroElement::assemble_macro_to_eulerian_jacobian2 (const Vector< double > & s, DenseMatrix< double > & jacobian2) inline
Assembles the second derivative jacobian of the mapping from the macro coordinates to the global coordinates
     {
       unsigned t = 0;
       assemble_macro_to_eulerian_jacobian2(t, s, jacobian2);
     }
References assemble_macro_to_eulerian_jacobian2(), s, and plotPSD::t.
domain_pt()
Domain*& oomph::MacroElement::domain_pt () inline
Access function to the Domain_pt.
     {
       return Domain_pt;
     }
References Domain_pt.
Referenced by oomph::ExtrudedCubeMeshFromQuadMesh< ELEMENT >::build_mesh().
macro_element_number()
unsigned& oomph::MacroElement::macro_element_number () inline
Access function to the Macro_element_number.
     {
       return Macro_element_number;
     }
References Macro_element_number.
Referenced by oomph::ExtrudedCubeMeshFromQuadMesh< ELEMENT >::build_mesh().
macro_map() [1/3]
virtual void oomph::MacroElement::macro_map (const double & t, const Vector< double > & s, Vector< double > & r) inline virtual
Get global position r(s) at continuous time value, t.
Reimplemented in oomph::QMacroElement< 2 >.
     {
       // Create an output stream
       std::ostringstream error_message_stream;
       // Create an error message
       error_message_stream << "The function macro_map(...) is broken virtual\n"
                            << "If you need it, please implement it!"
                            << std::endl;
       // Throw an error
       throw OomphLibError(error_message_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     } // End of macro_map
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
macro_map() [2/3]
virtual void oomph::MacroElement::macro_map (const unsigned & t, const Vector< double > & s, Vector< double > & r) pure virtual
The time-dependent mapping from local to global coordinates: r(t,s). t is the discrete timelevel: t=0: current time; t>0: previous timestep.
Implemented in oomph::QMacroElement< 3 >, oomph::QMacroElement< 2 >, and oomph::QExtrudedMacroElement< 3 >.
macro_map() [3/3]
void oomph::MacroElement::macro_map (const Vector< double > & s, Vector< double > & r) inline
The mapping from local to global coordinates at the current time : r(s)
     {
       // Evaluate at current timestep
       unsigned t = 0;
       macro_map(t, s, r);
     }
References UniformPSDSelfTest::r, s, and plotPSD::t.
Referenced by CylinderAndInterfaceMesh< ELEMENT >::CylinderAndInterfaceMesh(), oomph::EighthSphereMesh< ELEMENT >::EighthSphereMesh(), oomph::FullCircleMesh< ELEMENT >::FullCircleMesh(), oomph::QSolidElementBase::get_x_and_xi(), oomph::QElementBase::get_x_from_macro_element(), oomph::ExtrudedDomain::macro_element_boundary(), oomph::QExtrudedMacroElement< 3 >::output(), oomph::QMacroElement< 2 >::output(), oomph::QMacroElement< 3 >::output(), oomph::QuarterCircleSectorMesh< ELEMENT >::QuarterCircleSectorMesh(), oomph::QuarterTubeMesh< ELEMENT >::QuarterTubeMesh(), oomph::RectangleWithHoleMesh< ELEMENT >::RectangleWithHoleMesh(), and oomph::TubeMesh< ELEMENT >::TubeMesh().
operator=()
void oomph::MacroElement::operator= (const MacroElement &) delete
Broken assignment operator.
output() [1/2]
virtual void oomph::MacroElement::output (const unsigned & t, std::ostream & outfile, const unsigned & nplot) pure virtual
Plot: x,y (or x,y,z) in tecplot format at time level t (t=0: current; t>0: previous)
Implemented in oomph::QMacroElement< 3 >, oomph::QMacroElement< 2 >, and oomph::QExtrudedMacroElement< 3 >.
output() [2/2]
void oomph::MacroElement::output (std::ostream & outfile, const int & nplot) inline
Plot: x,y (or x,y,z) at current time in tecplot format
     {
       unsigned t = 0;
       output(t, outfile, nplot);
     }
References plotPSD::t.
output_macro_element_boundaries()
virtual void oomph::MacroElement::output_macro_element_boundaries (std::ostream & outfile, const unsigned & nplot) pure virtual
Output all macro element boundaries as tecplot zones.
Implemented in oomph::QMacroElement< 3 >, oomph::QMacroElement< 2 >, and oomph::QExtrudedMacroElement< 3 >.
Referenced by oomph::Domain::output_macro_element_boundaries().
Member Data Documentation
Domain_pt
Domain* oomph::MacroElement::Domain_pt protected
Pointer to domain.
Referenced by oomph::QMacroElement< 2 >::assemble_macro_to_eulerian_jacobian(), oomph::QMacroElement< 2 >::assemble_macro_to_eulerian_jacobian2(), domain_pt(), oomph::QMacroElement< 2 >::macro_map(), oomph::QMacroElement< 3 >::macro_map(), oomph::QMacroElement< 2 >::output_macro_element_boundaries(), and oomph::QMacroElement< 3 >::output_macro_element_boundaries().
Macro_element_number
unsigned oomph::MacroElement::Macro_element_number protected
What is the number of the current macro element within its domain.
Referenced by oomph::QMacroElement< 2 >::assemble_macro_to_eulerian_jacobian(), oomph::QMacroElement< 2 >::assemble_macro_to_eulerian_jacobian2(), macro_element_number(), oomph::QMacroElement< 2 >::macro_map(), oomph::QExtrudedMacroElement< 3 >::macro_map(), oomph::QMacroElement< 3 >::macro_map(), oomph::QExtrudedMacroElement< 3 >::output_macro_element_boundaries(), oomph::QMacroElement< 2 >::output_macro_element_boundaries(), and oomph::QMacroElement< 3 >::output_macro_element_boundaries().
The documentation for this class was generated from the following file:
macro_element.h