MercuryDPM: oomph::NodeOrdering Namespace Reference
oomph::NodeOrdering Namespace Reference
Functions
bool node_global_position_comparison (Node *nd1_pt, Node *nd2_pt)
Detailed Description
///////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////
Function Documentation
node_global_position_comparison()
bool oomph::NodeOrdering::node_global_position_comparison (Node * nd1_pt, Node * nd2_pt) inline
Function for ordering nodes. Return true if first node's position is "before" second nodes. Dimension 0 checked first, then... until they are different (by more than tol=1e-10). If they are both in exactly the same place an error is thrown.
     {
       unsigned ndim = nd1_pt->ndim();
       unsigned j;
       for (j = 0; j < ndim; j++)
       {
         if (std::abs(nd1_pt->x(j) - nd2_pt->x(j)) > 1e-10)
         {
           if (nd1_pt->x(j) < nd2_pt->x(j))
           {
             return true;
           }
           else
           {
             return false;
           }
         }
         // otherwise they are the same in this dimension, check next one.
       }
       std::string err = "Nodes are at the same point to ~ 1e-10!";
       err += " difference is " +
              StringConversion::to_string(std::abs(nd1_pt->x(j) - nd2_pt->x(j)));
       throw OomphLibError(
         err, OOMPH_EXCEPTION_LOCATION, OOMPH_CURRENT_FUNCTION);
     }
References abs(), e(), j, oomph::Node::ndim(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Global_string_for_annotation::string(), oomph::StringConversion::to_string(), and oomph::Node::x().
Referenced by oomph::Mesh::get_node_reordering().