MercuryDPM: oomph::EighthSphereMesh< ELEMENT > Class Template Reference
oomph::EighthSphereMesh< ELEMENT > Class Template Reference
#include <eighth_sphere_mesh.template.h>
Public Member Functions
EighthSphereMesh (const double &radius, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
~EighthSphereMesh ()
Destructor.
Public Member Functions inherited from oomph::BrickMeshBase
BrickMeshBase ()
Constructor (empty)
BrickMeshBase (const BrickMeshBase &)=delete
Broken copy constructor.
virtual ~BrickMeshBase ()
Broken assignment operator.
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Protected Attributes
Domain * Domain_pt
Pointer to the domain.
double Radius
Radius of the sphere.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Detailed Description
template<class ELEMENT>
class oomph::EighthSphereMesh< ELEMENT >
Eight of a sphere brick mesh, based on the EightSphereDomain Non-refineable version with four brick elements. The eighth-sphere is located in the positive octant, centred at the origin. The mesh boundaries are numbered as follows:
Boundary 0: Plane x=0
Boundary 1: Plane y=0
Boundary 2: Plane z=0
Boundary 3: The surface of the sphere.
Constructor & Destructor Documentation
EighthSphereMesh()
template<class ELEMENT > oomph::EighthSphereMesh< ELEMENT >::EighthSphereMesh (const double & radius, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass radius and timestepper; defaults to static default timestepper
Constructor for the eighth of a sphere mesh: Pass timestepper; defaults to static default timestepper.
     : Radius(radius)
   {
     // Mesh can only be built with 3D Qelements.
     MeshChecker::assert_geometric_element<QElementGeometricBase, ELEMENT>(3);
     // Set the number of boundaries
     this->set_nboundary(4);
     // Provide storage for the four elements
     this->Element_pt.resize(4);
     // Set the domain pointer: Pass the radius of the sphere
     Domain_pt = new EighthSphereDomain(Radius);
     Vector<double> s(3), s_fraction(3);
     Vector<double> r(3);
     // Create first element
     //--------------------
     this->Element_pt[0] = new ELEMENT;
     // Give it nodes
     // How many 1D nodes are there?
     unsigned nnode1d = this->finite_element_pt(0)->nnode_1d();
     // Loop over nodes
     for (unsigned i = 0; i < nnode1d; i++)
     {
       for (unsigned j = 0; j < nnode1d; j++)
       {
         for (unsigned k = 0; k < nnode1d; k++)
         {
           unsigned jnod = k * nnode1d * nnode1d + j * nnode1d + i;
           // If we're on a boundary, make a boundary node
           if ((i == 0) || (j == 0) || (k == 0))
           {
             // Allocate the node according to the element's wishes
             this->Node_pt.push_back(
               this->finite_element_pt(0)->construct_boundary_node(
                 jnod, time_stepper_pt));
           }
           // Otherwise it's a normal node
           else
           {
             // Allocate the node according to the element's wishes
             this->Node_pt.push_back(this->finite_element_pt(0)->construct_node(
               jnod, time_stepper_pt));
           }
           // Work out the node's coordinates in the finite element's local
           // coordinate system
           this->finite_element_pt(0)->local_fraction_of_node(jnod, s_fraction);
           // Get the position of the node from macro element mapping
           s[0] = -1.0 + 2.0 * s_fraction[0];
           s[1] = -1.0 + 2.0 * s_fraction[1];
           s[2] = -1.0 + 2.0 * s_fraction[2];
           Domain_pt->macro_element_pt(0)->macro_map(s, r);
           // Assign coordinates
           this->finite_element_pt(0)->node_pt(jnod)->x(0) = r[0];
           this->finite_element_pt(0)->node_pt(jnod)->x(1) = r[1];
           this->finite_element_pt(0)->node_pt(jnod)->x(2) = r[2];
           // Add the node to the appropriate boundary
           if (i == 0)
             add_boundary_node(0, this->finite_element_pt(0)->node_pt(jnod));
           if (j == 0)
             add_boundary_node(1, this->finite_element_pt(0)->node_pt(jnod));
           if (k == 0)
             add_boundary_node(2, this->finite_element_pt(0)->node_pt(jnod));
         }
       }
     }
     // Create a second element
     //------------------------
     this->Element_pt[1] = new ELEMENT;
     ;
     // Give it nodes
     // Loop over nodes
     for (unsigned i = 0; i < nnode1d; i++)
     {
       for (unsigned j = 0; j < nnode1d; j++)
       {
         for (unsigned k = 0; k < nnode1d; k++)
         {
           unsigned jnod = k * nnode1d * nnode1d + j * nnode1d + i;
           // If node has not been yet created, create it
           if (i > 0)
           {
             // If the node is on a boundary, make a boundary node
             if ((i == nnode1d - 1) || (j == 0) || (k == 0))
             {
               this->Node_pt.push_back(
                 this->finite_element_pt(1)->construct_boundary_node(
                   jnod, time_stepper_pt));
             }
             // Otherwise make a normal node
             else
             {
               this->Node_pt.push_back(
                 this->finite_element_pt(1)->construct_node(jnod,
                                                            time_stepper_pt));
             }
             // Work out the node's coordinates in the finite element's local
             // coordinate system
             this->finite_element_pt(1)->local_fraction_of_node(jnod,
                                                                s_fraction);
             // Get the position of the node from macro element mapping
             s[0] = -1.0 + 2.0 * s_fraction[0];
             s[1] = -1.0 + 2.0 * s_fraction[1];
             s[2] = -1.0 + 2.0 * s_fraction[2];
             Domain_pt->macro_element_pt(1)->macro_map(s, r);
             // Assign coordinate
             this->finite_element_pt(1)->node_pt(jnod)->x(0) = r[0];
             this->finite_element_pt(1)->node_pt(jnod)->x(1) = r[1];
             this->finite_element_pt(1)->node_pt(jnod)->x(2) = r[2];
             // Add the node to the approriate boundary
             if (j == 0)
               add_boundary_node(1, this->finite_element_pt(1)->node_pt(jnod));
             if (k == 0)
               add_boundary_node(2, this->finite_element_pt(1)->node_pt(jnod));
             if (i == nnode1d - 1)
               add_boundary_node(3, this->finite_element_pt(1)->node_pt(jnod));
           }
           // ...else use the node already created
           else
           {
             this->finite_element_pt(1)->node_pt(jnod) =
               this->finite_element_pt(0)->node_pt(jnod + nnode1d - 1);
           }
         }
       }
     }
     // Create a third element
     //------------------------
     this->Element_pt[2] = new ELEMENT;
     // Give it nodes
     // Loop over nodes
     for (unsigned i = 0; i < nnode1d; i++)
     {
       for (unsigned j = 0; j < nnode1d; j++)
       {
         for (unsigned k = 0; k < nnode1d; k++)
         {
           unsigned jnod = k * nnode1d * nnode1d + j * nnode1d + i;
           // If the node has not been yet created, create it
           if ((i < nnode1d - 1) && (j > 0))
           {
             // If it's on a boundary, make a boundary node
             if ((i == 0) || (j == nnode1d - 1) || (k == 0))
             {
               // Allocate the node according to the element's wishes
               this->Node_pt.push_back(
                 this->finite_element_pt(2)->construct_boundary_node(
                   jnod, time_stepper_pt));
             }
             // Otherwise allocate a normal node
             else
             {
               // Allocate the node according to the element's wishes
               this->Node_pt.push_back(
                 this->finite_element_pt(2)->construct_node(jnod,
                                                            time_stepper_pt));
             }
             // Work out the node's coordinates in the finite element's local
             // coordinate system
             this->finite_element_pt(2)->local_fraction_of_node(jnod,
                                                                s_fraction);
             // Get the position of the node from macro element mapping
             s[0] = -1.0 + 2.0 * s_fraction[0];
             s[1] = -1.0 + 2.0 * s_fraction[1];
             s[2] = -1.0 + 2.0 * s_fraction[2];
             Domain_pt->macro_element_pt(2)->macro_map(s, r);
             // Assign coordinates
             this->finite_element_pt(2)->node_pt(jnod)->x(0) = r[0];
             this->finite_element_pt(2)->node_pt(jnod)->x(1) = r[1];
             this->finite_element_pt(2)->node_pt(jnod)->x(2) = r[2];
             // Add the node to the appropriate boundary
             if (i == 0)
               add_boundary_node(0, this->finite_element_pt(2)->node_pt(jnod));
             if (k == 0)
               add_boundary_node(2, this->finite_element_pt(2)->node_pt(jnod));
             if (j == nnode1d - 1)
               add_boundary_node(3, this->finite_element_pt(2)->node_pt(jnod));
           }
           // ...else use the nodes already created
           else
           {
             // If the node belongs to the element 0
             if (j == 0)
               this->finite_element_pt(2)->node_pt(jnod) =
                 this->finite_element_pt(0)->node_pt(jnod +
                                                     nnode1d * (nnode1d - 1));
             // ...else it belongs to the element 1
             else if (i == nnode1d - 1)
               this->finite_element_pt(2)->node_pt(jnod) =
                 this->finite_element_pt(1)->node_pt(nnode1d * nnode1d * k + j +
                                                     i * nnode1d);
           }
         }
       }
     }
     // Create the fourth element
     //-------------------------
     this->Element_pt[3] = new ELEMENT;
     // Give it nodes
     // Loop over nodes
     for (unsigned i = 0; i < nnode1d; i++)
     {
       for (unsigned j = 0; j < nnode1d; j++)
       {
         for (unsigned k = 0; k < nnode1d; k++)
         {
           unsigned jnod = k * nnode1d * nnode1d + j * nnode1d + i;
           // If the node has not been yet created, create it
           if ((k > 0) && (i < nnode1d - 1) && (j < nnode1d - 1))
           {
             // If it's on a boundary, allocate a boundary node
             if ((i == 0) || (j == 0) || (k == nnode1d - 1))
             {
               // Allocate the node according to the element's wishes
               this->Node_pt.push_back(
                 this->finite_element_pt(3)->construct_boundary_node(
                   jnod, time_stepper_pt));
             }
             // Otherwise allocate a normal node
             else
             {
               // Allocate the node according to the element's wishes
               this->Node_pt.push_back(
                 this->finite_element_pt(3)->construct_node(jnod,
                                                            time_stepper_pt));
             }
             // Work out the node's coordinates in the finite element's local
             // coordinate system
             this->finite_element_pt(3)->local_fraction_of_node(jnod,
                                                                s_fraction);
             // Get the position of the node from macro element mapping
             s[0] = -1.0 + 2.0 * s_fraction[0];
             s[1] = -1.0 + 2.0 * s_fraction[1];
             s[2] = -1.0 + 2.0 * s_fraction[2];
             Domain_pt->macro_element_pt(3)->macro_map(s, r);
             // Assign coordinates
             this->finite_element_pt(3)->node_pt(jnod)->x(0) = r[0];
             this->finite_element_pt(3)->node_pt(jnod)->x(1) = r[1];
             this->finite_element_pt(3)->node_pt(jnod)->x(2) = r[2];
             // Add the node to the appropriate boundary
             if (i == 0)
               add_boundary_node(0, this->finite_element_pt(3)->node_pt(jnod));
             if (j == 0)
               add_boundary_node(1, this->finite_element_pt(3)->node_pt(jnod));
             if (k == nnode1d - 1)
               add_boundary_node(3, this->finite_element_pt(3)->node_pt(jnod));
           }
           // ...otherwise the node was already created: use it.
           else
           {
             // if k=0 then the node belongs to element 0
             if (k == 0)
             {
               this->finite_element_pt(3)->node_pt(jnod) =
                 this->finite_element_pt(0)->node_pt(jnod + nnode1d * nnode1d *
                                                              (nnode1d - 1));
             }
             else
             {
               // else if i==nnode1d-1 the node already exists in element 1
               if (i == nnode1d - 1)
               {
                 this->finite_element_pt(3)->node_pt(jnod) =
                   this->finite_element_pt(1)->node_pt(
                     k + i * nnode1d * nnode1d + j * nnode1d);
               }
               else
               // else, the node exists in element 2
               {
                 this->finite_element_pt(3)->node_pt(jnod) =
                   this->finite_element_pt(2)->node_pt(i + k * nnode1d +
                                                       j * nnode1d * nnode1d);
               }
             }
           }
         }
       }
     }
     // Setup boundary element lookup schemes
     setup_boundary_element_info();
   }
References oomph::Mesh::add_boundary_node(), oomph::EighthSphereMesh< ELEMENT >::Domain_pt, oomph::Mesh::Element_pt, oomph::Mesh::finite_element_pt(), i, j, k, oomph::FiniteElement::local_fraction_of_node(), oomph::Domain::macro_element_pt(), oomph::MacroElement::macro_map(), oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::node_pt(), oomph::Mesh::Node_pt, oomph::Mesh::node_pt(), UniformPSDSelfTest::r, oomph::EighthSphereMesh< ELEMENT >::Radius, s, oomph::Mesh::set_nboundary(), oomph::BrickMeshBase::setup_boundary_element_info(), and oomph::Node::x().
~EighthSphereMesh()
template<class ELEMENT > oomph::EighthSphereMesh< ELEMENT >::~EighthSphereMesh () inline
Destructor.
     {
       delete Domain_pt;
       Domain_pt = 0;
     }
References oomph::EighthSphereMesh< ELEMENT >::Domain_pt.
Member Data Documentation
Domain_pt
template<class ELEMENT > Domain* oomph::EighthSphereMesh< ELEMENT >::Domain_pt protected
Pointer to the domain.
Referenced by oomph::EighthSphereMesh< ELEMENT >::EighthSphereMesh(), oomph::RefineableEighthSphereMesh< ELEMENT >::RefineableEighthSphereMesh(), and oomph::EighthSphereMesh< ELEMENT >::~EighthSphereMesh().
Radius
template<class ELEMENT > double oomph::EighthSphereMesh< ELEMENT >::Radius protected
Radius of the sphere.
Referenced by oomph::EighthSphereMesh< ELEMENT >::EighthSphereMesh().
The documentation for this class was generated from the following files:
eighth_sphere_mesh.template.h
eighth_sphere_mesh.template.cc