MercuryDPM: GlMatrixHelper< false, Flags_ > Struct Template Reference
GlMatrixHelper< false, Flags_ > Struct Template Reference
#include <gpuhelper.h>
Static Public Member Functions
static void loadMatrix (const Matrix< float, 4, 4, Flags_, 4, 4 > &mat)
static void loadMatrix (const Matrix< double, 4, 4, Flags_, 4, 4 > &mat)
static void multMatrix (const Matrix< float, 4, 4, Flags_, 4, 4 > &mat)
static void multMatrix (const Matrix< double, 4, 4, Flags_, 4, 4 > &mat)
Member Function Documentation
loadMatrix() [1/2]
template<int Flags_> static void GlMatrixHelper< false, Flags_ >::loadMatrix (const Matrix< double, 4, 4, Flags_, 4, 4 > & mat) inline static
 { glLoadMatrixd(mat.data()); }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::data().
loadMatrix() [2/2]
template<int Flags_> static void GlMatrixHelper< false, Flags_ >::loadMatrix (const Matrix< float, 4, 4, Flags_, 4, 4 > & mat) inline static
 { glLoadMatrixf(mat.data()); }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::data().
multMatrix() [1/2]
template<int Flags_> static void GlMatrixHelper< false, Flags_ >::multMatrix (const Matrix< double, 4, 4, Flags_, 4, 4 > & mat) inline static
 { glMultMatrixd(mat.data()); }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::data().
multMatrix() [2/2]
template<int Flags_> static void GlMatrixHelper< false, Flags_ >::multMatrix (const Matrix< float, 4, 4, Flags_, 4, 4 > & mat) inline static
 { glMultMatrixf(mat.data()); }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::data().
The documentation for this struct was generated from the following file:
gpuhelper.h