MercuryDPM: CoilSelfTest.cpp File Reference
CoilSelfTest.cpp File Reference
#include "Mercury3D.h"
#include "Walls/InfiniteWall.h"
#include "Walls/InfiniteWallWithHole.h"
#include "Walls/Coil.h"
#include "Species/LinearViscoelasticSpecies.h"
Classes
class CoilSelfTest
[CST:headers]
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
[CST:class]
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
[CST:class]
[CST:main]
[CSTproblemSetup]
[CSTproblemSetup]
[CST:species]
[CST:species]
[CST:solve]
[CST:solve]
 {
     // create CoilSelfTest object
     CoilSelfTest problem;
     // set some basic problem properties
     problem.setName("CoilSelfTest");
     problem.setSystemDimensions(3);
     problem.setGravity(Vec3D(0.0, -9.8, 0.0));
     // set problem geometry
     problem.setXMax(1.0);
     problem.setYMax(5.0);
     problem.setZMax(2.0);
     problem.setXMin(-1.0);
     problem.setYMin(-1.0);
     problem.setTimeMax(0.5);
     problem.particleRadius = 0.2;
     LinearViscoelasticSpecies species;
     species.setDensity(1000);
     Mdouble tc = 0.05;
     Mdouble restitutionCoefficient = 0.8;
     Mdouble particleMass = pow(problem.particleRadius, 3) * constants::pi * 4.0 / 3.0 * species.getDensity();
     species.setCollisionTimeAndRestitutionCoefficient(tc, restitutionCoefficient, particleMass);
     problem.speciesHandler.copyAndAddObject(species);
     problem.setTimeStep(0.02 * 0.05);
     problem.setSaveCount(helpers::getSaveCountFromNumberOfSavesAndTimeMaxAndTimeStep(1000, problem.getTimeMax(),
                                                                                      problem.getTimeStep()));
     problem.solve();
 }
References ParticleSpecies::getDensity(), helpers::getSaveCountFromNumberOfSavesAndTimeMaxAndTimeStep(), constants::pi, Eigen::ArrayBase< Derived >::pow(), problem, LinearViscoelasticNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), and ParticleSpecies::setDensity().