MercuryDPM: circular_driven_cavity_hp_adapt.cc File Reference
circular_driven_cavity_hp_adapt.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "meshes/quarter_circle_sector_mesh.h"
Classes
class QuarterCircleDrivenCavityProblem< ELEMENT >
Namespaces
Global_Physical_Variables
Global variables.
Functions
Vector< double > Global_Physical_Variables::Gravity (2)
Gravity vector.
void Global_Physical_Variables::body_force (const double &time, const Vector< double > &x, Vector< double > &result)
Functional body force.
void Global_Physical_Variables::zero_body_force (const double &time, const Vector< double > &x, Vector< double > &result)
Zero functional body force.
int main ()
Driver for QuarterCircleDrivenCavityProblem test problem.
Function Documentation
main()
int main ()
Driver for QuarterCircleDrivenCavityProblem test problem.
 {
  //Drive straight and curved boundaries in turn
  for(unsigned driven_bdry=0; driven_bdry<2; driven_bdry++)
   {
    // Set output directory
    DocInfo doc_info;
    if(driven_bdry==0)
     doc_info.set_directory("RESLT_circ_bdry0");
    else
     doc_info.set_directory("RESLT_circ_bdry1");
    // Solve problem 1 with hp-refineable Crouzeix-Raviart elements
    //-------------------------------------------------------------
    {
     // Set up downwards-Gravity vector
     Global_Physical_Variables::Gravity[0] = 0.0;
     Global_Physical_Variables::Gravity[1] = -1.0;
     // Set up Gamma vector for stress-divergence form
     NavierStokesEquations<2>::Gamma[0]=1;
     NavierStokesEquations<2>::Gamma[1]=1;
     // Build problem with Gravity vector in stress divergence form,
     // using zero body force function
     QuarterCircleDrivenCavityProblem<PRefineableQCrouzeixRaviartElement<2> >
      problem(&Global_Physical_Variables::zero_body_force,driven_bdry);
     //Set initial doc_info number
     doc_info.number()=10;
     // Initial refinement level
     problem.refine_uniformly();
     problem.refine_uniformly();
     problem.p_refine_uniformly();
     problem.newton_solve();
     cout << "output file: " << doc_info.number() << endl;
     problem.doc_solution(doc_info);
     doc_info.number()++;
     problem.adapt();
     problem.newton_solve();
     cout << "output file: " << doc_info.number() << endl;
     problem.doc_solution(doc_info);
     doc_info.number()++;
     problem.p_adapt();
     problem.newton_solve();
     cout << "output file: " << doc_info.number() << endl;
     problem.doc_solution(doc_info);
     doc_info.number()++;
     problem.adapt();
     problem.newton_solve();
     cout << "output file: " << doc_info.number() << endl;
     problem.doc_solution(doc_info);
     doc_info.number()++;
     //Doc again for check
     doc_info.number()=0;
     problem.doc_solution(doc_info);
    } // end of problem 1
    // Solve problem 2 with hp-refineable Crouzeix-Raviart elements
    //-------------------------------------------------------------
    {
     // Set up zero-Gravity vector
     Global_Physical_Variables::Gravity[0] = 0.0;
     Global_Physical_Variables::Gravity[1] = 0.0;
     // Set up Gamma vector for simplified form
     NavierStokesEquations<2>::Gamma[0]=0;
     NavierStokesEquations<2>::Gamma[1]=0;
     // Build problem with body force function and simplified form,
     // using body force function
     QuarterCircleDrivenCavityProblem<PRefineableQCrouzeixRaviartElement<2> >
      problem(&Global_Physical_Variables::body_force,driven_bdry);
     //Set initial doc_info number
     doc_info.number()=20;
     // Initial refinement level
     problem.refine_uniformly();
     problem.refine_uniformly();
     problem.p_refine_uniformly();
     problem.newton_solve();
     cout << "output file: " << doc_info.number() << endl;
     problem.doc_solution(doc_info);
     doc_info.number()++;
     problem.adapt();
     problem.newton_solve();
     cout << "output file: " << doc_info.number() << endl;
     problem.doc_solution(doc_info);
     doc_info.number()++;
     problem.p_adapt();
     problem.newton_solve();
     cout << "output file: " << doc_info.number() << endl;
     problem.doc_solution(doc_info);
     doc_info.number()++;
     problem.adapt();
     problem.newton_solve();
     cout << "output file: " << doc_info.number() << endl;
     problem.doc_solution(doc_info);
     doc_info.number()++;
     //Doc again for check
     doc_info.number()=1;
     problem.doc_solution(doc_info);
    } // end of problem 2
   }//end of both boundaries
 } // end_of_main
References Global_Physical_Variables::body_force(), Global_Physical_Variables::Gravity, oomph::DocInfo::number(), problem, oomph::DocInfo::set_directory(), and Global_Physical_Variables::zero_body_force().