MercuryDPM: oomph::TanhProfileConstitutiveEquation< DIM > Class Template Reference
oomph::TanhProfileConstitutiveEquation< DIM > Class Template Reference
#include <generalised_newtonian_constitutive_models.h>
Public Member Functions
TanhProfileConstitutiveEquation (double *mu_inf_pt, double *mu_0_pt, double *alpha_pt, double *critical_second_invariant_pt)
double viscosity (const double &second_invariant_of_rate_of_strain_tensor)
double dviscosity_dinvariant (const double &second_invariant_of_rate_of_strain_tensor)
Public Member Functions inherited from oomph::GeneralisedNewtonianConstitutiveEquation< DIM >
GeneralisedNewtonianConstitutiveEquation ()
Empty constructor.
virtual ~GeneralisedNewtonianConstitutiveEquation ()
Empty virtual destructor.
Private Attributes
double * Mu_inf_pt
high shear rate viscosity
double * Mu_0_pt
zero shear rate viscosity
double * Alpha_pt
double * Critical_second_invariant_pt
Detailed Description
template<unsigned DIM>
class oomph::TanhProfileConstitutiveEquation< DIM >
A GeneralisedNewtonianConstitutiveEquation class defining a fluid following a tanh-profile
Constructor & Destructor Documentation
TanhProfileConstitutiveEquation()
template<unsigned DIM> oomph::TanhProfileConstitutiveEquation< DIM >::TanhProfileConstitutiveEquation (double * mu_inf_pt, double * mu_0_pt, double * alpha_pt, double * critical_second_invariant_pt) inline
       : GeneralisedNewtonianConstitutiveEquation<DIM>(),
         Mu_inf_pt(mu_inf_pt),
         Mu_0_pt(mu_0_pt),
         Alpha_pt(alpha_pt),
         Critical_second_invariant_pt(critical_second_invariant_pt)
     {
     }
Member Function Documentation
dviscosity_dinvariant()
template<unsigned DIM> double oomph::TanhProfileConstitutiveEquation< DIM >::dviscosity_dinvariant (const double & second_invariant_of_rate_of_strain_tensor) inline virtual
Function returning the derivative of the viscosity w.r.t. the second invariant of the rate of strain tensor For Newtonian behaviour this returns 0.0
Implements oomph::GeneralisedNewtonianConstitutiveEquation< DIM >.
     {
       // Pre-multiply the second invariant with +/-1 depending on whether it's
       // positive or not
       double sign = -1.0;
       if (second_invariant_of_rate_of_strain_tensor >= 0.0)
       {
         sign = 1.0;
       }
       return -sign * ((*Mu_0_pt) - (*Mu_inf_pt)) * 10.0 /
              (2.0 * (*Critical_second_invariant_pt)) * 1.0 /
              cosh(((*Critical_second_invariant_pt) -
                    sign * second_invariant_of_rate_of_strain_tensor) *
                   (*Alpha_pt)) *
              1.0 /
              cosh(((*Critical_second_invariant_pt) -
                    sign * second_invariant_of_rate_of_strain_tensor) *
                   (*Alpha_pt));
     }
References Eigen::bfloat16_impl::cosh(), oomph::TanhProfileConstitutiveEquation< DIM >::Critical_second_invariant_pt, and SYCL::sign().
viscosity()
template<unsigned DIM> double oomph::TanhProfileConstitutiveEquation< DIM >::viscosity (const double & second_invariant_of_rate_of_strain_tensor) inline virtual
Function implementing the constitutive model Input: second invariant of the rate of strain Output: the viscosity For Newtonian behaviour this returns 1
Implements oomph::GeneralisedNewtonianConstitutiveEquation< DIM >.
     {
       // Pre-multiply the second invariant with +/-1 depending on whether it's
       // positive or not
       double sign = -1.0;
       if (second_invariant_of_rate_of_strain_tensor >= 0.0)
       {
         sign = 1.0;
       }
       return ((*Mu_0_pt) - (*Mu_inf_pt)) / 2.0 *
                tanh(((*Critical_second_invariant_pt) -
                      sign * second_invariant_of_rate_of_strain_tensor) *
                     (*Alpha_pt)) -
              ((*Mu_0_pt) - (*Mu_inf_pt)) / 2.0 + (*Mu_0_pt);
     }
References oomph::TanhProfileConstitutiveEquation< DIM >::Alpha_pt, oomph::TanhProfileConstitutiveEquation< DIM >::Critical_second_invariant_pt, oomph::TanhProfileConstitutiveEquation< DIM >::Mu_0_pt, oomph::TanhProfileConstitutiveEquation< DIM >::Mu_inf_pt, SYCL::sign(), and Eigen::bfloat16_impl::tanh().
Member Data Documentation
Alpha_pt
template<unsigned DIM> double* oomph::TanhProfileConstitutiveEquation< DIM >::Alpha_pt private
parameter controlling the steepness of the step nb – I used 10.0/(*Critical_second_invariant_pt)
Referenced by oomph::TanhProfileConstitutiveEquation< DIM >::viscosity().
Critical_second_invariant_pt
template<unsigned DIM> double* oomph::TanhProfileConstitutiveEquation< DIM >::Critical_second_invariant_pt private
parameter that controls the location of the step – assumed to be always positive
Referenced by oomph::TanhProfileConstitutiveEquation< DIM >::dviscosity_dinvariant(), and oomph::TanhProfileConstitutiveEquation< DIM >::viscosity().
Mu_0_pt
template<unsigned DIM> double* oomph::TanhProfileConstitutiveEquation< DIM >::Mu_0_pt private
zero shear rate viscosity
Referenced by oomph::TanhProfileConstitutiveEquation< DIM >::viscosity().
Mu_inf_pt
template<unsigned DIM> double* oomph::TanhProfileConstitutiveEquation< DIM >::Mu_inf_pt private
high shear rate viscosity
Referenced by oomph::TanhProfileConstitutiveEquation< DIM >::viscosity().
The documentation for this class was generated from the following file:
generalised_newtonian_constitutive_models.h