MercuryDPM: SinterForceUnitTest.cpp File Reference
SinterForceUnitTest.cpp File Reference
#include "DPMBase.h"
#include <iostream>
#include <vector>
#include <Species/SinterSpecies.h>
#include <Logger.h>
Classes
class SinterForceUnitTest
[T11:contactModel]
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     SinterForceUnitTest sf;
     double k1=5.0;
     sf.radius = 2e-6;
     sf.species->setDensity(6.0/constants::pi);
     sf.species->setPlasticParameters(k1, 5.0*k1, k1, 0.5);
     sf.setParticleDimensions(3);
     sf.setSystemDimensions(3);
     sf.species->setSinterRate(1000);
     Mdouble mass=sf.species->getDensity()*constants::pi/6.0*mathsFunc::cubic(2.0*sf.radius);
     sf.species->setDissipation(5e5*mass);
     sf.setTimeStep(sf.species->computeTimeStep(mass)*2.0);
     sf.setTimeMax(sf.getTimeStep()*400.0);
     sf.setFileType(FileType::ONE_FILE);
     sf.setSaveCount(1);
     logger(INFO,"Testing particle particles collision for elastic plastic forces. \n"
         "This will be done for several values of scaled relative velocity chi");
     //Set up constant data that will be used
     const std::vector<double> chi = {0.34, 0.69, 1.05, 1.25};
     //Loop over all test cases
     for (int i=0; i<4; i++)
     {
         logger(INFO, "Running for chi=%",chi[i]);
         sf.set_chi(chi[i]);
         std::stringstream ss("");
         ss << "SinterForceUnitTest" << sf.get_chi();
         sf.setName(ss.str().c_str());
         sf.solve();
         sf.writeRestartFile();
     }
     //A longer simulation, with sintering activated
     sf.set_chi(1.15);
     sf.setName("LongSinterForceUnitTest");
     sf.setSaveCount(2500);
     sf.setTimeMax(5e-4);
     sf.solve();
     sf.writeRestartFile();
     logger(INFO, "Execute 'gnuplot SinterForceUnitTest.gnu' to view output");
     helpers::writeToFile("SinterForceUnitTest.gnu",
                          "set xlabel 'displacement'\n"
                          "set ylabel 'force'\n"
                          "plot 'SinterForceUnitTest1.05.fstat' u 7:9 w lp\n"
     );
     logger(INFO, "Execute 'gnuplot LongSinterForceUnitTest.gnu' to view output");
     helpers::writeToFile("LongSinterForceUnitTest.gnu",
                          "sinterRate = 1000\n"
                          "radius = 2e-6\n"
                          "set xlabel 'time'\n"
                          "set ylabel 'displacement'\n"
                          "plot 'LongSinterForceUnitTest.fstat' u 1:(sqrt(2.0*$7/radius)), sqrt((sinterRate*x)+0.5**2)\n"
             //"plot 'LongSinterForceUnitTest.fstat' u 1:(sqrt(2.0*$7/radius)), sqrt((2.0/radius*sinterRate*x)+0.77**2)\n"
             //"plot 'LongSinterForceUnitTest.fstat' u 1:(sqrt(2.0*$7/radius)), sqrt(sinterRate*x)\n"
     );
 }
References mathsFunc::cubic(), e(), SinterForceUnitTest::get_chi(), ParticleSpecies::getDensity(), DPMBase::getTimeStep(), i, INFO, logger, ONE_FILE, constants::pi, SinterForceUnitTest::radius, SinterForceUnitTest::set_chi(), ParticleSpecies::setDensity(), DPMBase::setFileType(), DPMBase::setName(), DPMBase::setParticleDimensions(), DPMBase::setSaveCount(), DPMBase::setSystemDimensions(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), DPMBase::solve(), SinterForceUnitTest::species, DPMBase::writeRestartFile(), and helpers::writeToFile().