MercuryDPM: oomph::ComplexMatrixBase Class Reference
oomph::ComplexMatrixBase Class Reference abstract
#include <complex_matrices.h>
Public Member Functions
ComplexMatrixBase ()
(Empty) constructor.
ComplexMatrixBase (const ComplexMatrixBase &matrix)=delete
Broken copy constructor.
void operator= (const ComplexMatrixBase &)=delete
Broken assignment operator.
virtual unsigned long nrow () const =0
Return the number of rows of the matrix.
virtual unsigned long ncol () const =0
Return the number of columns of the matrix.
virtual ~ComplexMatrixBase ()
virtual (empty) destructor
virtual std::complex< double > operator() (const unsigned long &i, const unsigned long &j) const =0
virtual int ludecompose ()
virtual void lubksub (Vector< std::complex< double >> &rhs)
virtual void solve (Vector< std::complex< double >> &rhs)
virtual void solve (const Vector< std::complex< double >> &rhs, Vector< std::complex< double >> &soln)
virtual void residual (const Vector< std::complex< double >> &x, const Vector< std::complex< double >> &b, Vector< std::complex< double >> &residual)=0
Find the residual, i.e. r=b-Ax the residual.
virtual double max_residual (const Vector< std::complex< double >> &x, const Vector< std::complex< double >> &rhs)
virtual void multiply (const Vector< std::complex< double >> &x, Vector< std::complex< double >> &soln)=0
Multiply the matrix by the vector x: soln=Ax.
virtual void multiply_transpose (const Vector< std::complex< double >> &x, Vector< std::complex< double >> &soln)=0
Multiply the transposed matrix by the vector x: soln=A^T x.
Detailed Description
Abstract base class for matrices of complex doubles – adds abstract interfaces for solving, LU decomposition and multiplication by vectors.
Constructor & Destructor Documentation
ComplexMatrixBase() [1/2]
oomph::ComplexMatrixBase::ComplexMatrixBase () inline
(Empty) constructor.
 {}
ComplexMatrixBase() [2/2]
oomph::ComplexMatrixBase::ComplexMatrixBase (const ComplexMatrixBase & matrix) delete
Broken copy constructor.
~ComplexMatrixBase()
virtual oomph::ComplexMatrixBase::~ComplexMatrixBase () inline virtual
virtual (empty) destructor
 {}
Member Function Documentation
lubksub()
virtual void oomph::ComplexMatrixBase::lubksub (Vector< std::complex< double >> & rhs) inline virtual
LU backsubstitue a previously LU-decomposed matrix; The passed rhs will be over-written with the solution vector
Reimplemented in oomph::CCComplexMatrix, oomph::CRComplexMatrix, and oomph::DenseComplexMatrix.
     {
       throw OomphLibError(
         "lubksub() has not been written for this matrix class\n",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by solve().
ludecompose()
virtual int oomph::ComplexMatrixBase::ludecompose () inline virtual
LU decomposition of the matrix using the appropriate linear solver. Return the sign of the determinant
Dummy return
Reimplemented in oomph::CCComplexMatrix, oomph::CRComplexMatrix, and oomph::DenseComplexMatrix.
     {
       throw OomphLibError(
         "ludecompose() has not been written for this matrix class\n",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
       return 1;
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by solve().
max_residual()
virtual double oomph::ComplexMatrixBase::max_residual (const Vector< std::complex< double >> & x, const Vector< std::complex< double >> & rhs) inline virtual
Find the maximum residual r=b-Ax – generic version, can be overloaded for specific derived classes where the max. can be determined "on the fly"
     {
       unsigned long n = rhs.size();
       Vector<std::complex<double>> res(n);
       residual(x, rhs, res);
       double ans = 0.0;
       for (unsigned long i = 0; i < n; i++)
       {
         ans = std::max(ans, std::abs(res[i]));
       }
       return ans;
     }
References abs(), i, max, n, res, residual(), and plotDoE::x.
multiply()
virtual void oomph::ComplexMatrixBase::multiply (const Vector< std::complex< double >> & x, Vector< std::complex< double >> & soln) pure virtual
Multiply the matrix by the vector x: soln=Ax.
Implemented in oomph::CCComplexMatrix, oomph::CRComplexMatrix, and oomph::DenseComplexMatrix.
multiply_transpose()
virtual void oomph::ComplexMatrixBase::multiply_transpose (const Vector< std::complex< double >> & x, Vector< std::complex< double >> & soln) pure virtual
Multiply the transposed matrix by the vector x: soln=A^T x.
Implemented in oomph::CCComplexMatrix, oomph::CRComplexMatrix, and oomph::DenseComplexMatrix.
ncol()
virtual unsigned long oomph::ComplexMatrixBase::ncol () const pure virtual
Return the number of columns of the matrix.
Implemented in oomph::CCComplexMatrix, oomph::CRComplexMatrix, and oomph::DenseComplexMatrix.
Referenced by solve().
nrow()
virtual unsigned long oomph::ComplexMatrixBase::nrow () const pure virtual
Return the number of rows of the matrix.
Implemented in oomph::CCComplexMatrix, oomph::CRComplexMatrix, and oomph::DenseComplexMatrix.
Referenced by solve().
operator()()
virtual std::complex<double> oomph::ComplexMatrixBase::operator() (const unsigned long & i, const unsigned long & j) const pure virtual
Round brackets to give access as a(i,j) for read only (we're not providing a general interface for component-wise write access since not all matrix formats allow efficient direct access!)
Implemented in oomph::CCComplexMatrix, oomph::CRComplexMatrix, and oomph::DenseComplexMatrix.
operator=()
void oomph::ComplexMatrixBase::operator= (const ComplexMatrixBase &) delete
Broken assignment operator.
residual()
virtual void oomph::ComplexMatrixBase::residual (const Vector< std::complex< double >> & x, const Vector< std::complex< double >> & b, Vector< std::complex< double >> & residual) pure virtual
Find the residual, i.e. r=b-Ax the residual.
Implemented in oomph::DenseComplexMatrix, oomph::CCComplexMatrix, and oomph::CRComplexMatrix.
Referenced by max_residual().
solve() [1/2]
void oomph::ComplexMatrixBase::solve (const Vector< std::complex< double >> & rhs, Vector< std::complex< double >> & soln) virtual
Complete LU solve (Nothing gets overwritten!). The default should not need to be overwritten
Complete LU solve (Nothing gets overwritten!). This generic version should never need to be overwritten
   {
     // Set the solution vector equal to the rhs
     // N.B. This won't work if we change to another vector format
     soln = rhs;
     // Overwrite the solution vector (rhs is unchanged)
     solve(soln);
   }
References solve().
solve() [2/2]
void oomph::ComplexMatrixBase::solve (Vector< std::complex< double >> & rhs) virtual
Complete LU solve (replaces matrix by its LU decomposition and overwrites RHS with solution). The default should not need to be over-written
Complete LU solve (overwrites RHS with solution). This is the generic version which should not need to be over-written.
   {
 #ifdef PARANOID
     // Check Matrix is square
     if (nrow() != ncol())
     {
       throw OomphLibError(
         "This matrix is not square, the matrix MUST be square!",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
     // Check that size of rhs = nrow()
     if (rhs.size() != nrow())
     {
       std::ostringstream error_message_stream;
       error_message_stream << "The rhs vector is not the right size. It is "
                            << rhs.size() << ", it should be " << nrow()
                            << std::endl;
       throw OomphLibError(error_message_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Call the LU decomposition
     ludecompose();
     // Call the back substitution
     lubksub(rhs);
   }
References lubksub(), ludecompose(), ncol(), nrow(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by solve().
The documentation for this class was generated from the following files:
complex_matrices.h
complex_matrices.cc