MercuryDPM: two_d_parallel_unstructured_adaptive_poisson.cc File Reference
two_d_parallel_unstructured_adaptive_poisson.cc File Reference
#include <fenv.h>
#include "generic.h"
#include "poisson.h"
#include "meshes/triangle_mesh.h"
Classes
class PoissonProblem< ELEMENT >
Micky mouse Poisson problem.
Namespaces
TanhSolnForPoisson
Namespace for exact solution for Poisson equation with "sharp step".
TestArguments
Functions
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, double &u)
Exact solution as a scalar.
void TanhSolnForPoisson::get_source (const Vector< double > &x, double &source)
Source function to make it an exact solution.
int main (int argc, char *argv[])
Demonstrate how to solve Poisson problem using parallel.
Variables
unsigned TestArguments::Domain_configuration = 1
double TestArguments::Element_size = 1.0e-2
unsigned TestArguments::Max_adapt = 3
double TestArguments::Max_permitted_error = 1.0e-3
double TestArguments::Min_permitted_error = 1.0e-5
double TestArguments::Max_element_size = Element_size
double TestArguments::Min_element_size = 1.0e-14
unsigned TestArguments::Load_balance = 0
std::string TestArguments::Folder_distribution_file =""
Function Documentation
main()
int main (int argc , char * argv[])
Demonstrate how to solve Poisson problem using parallel.
Trace file to document error and norm of solution
 {
  // initialise MPI
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::init(argc,argv);
 #endif
  // Get the processor rank (we use this to name the trace file)
  const unsigned my_rank = MPI_Helpers::communicator_pt()->my_rank();
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Domain configurations: 1 Square domain
  //                        2 Half circle domain
  //                        3 Half circle domain with internal boundaries
  //                        4 Complex domain with holes
  // Domain configuration
  CommandLineArgs::specify_command_line_flag("--domain_configuration",
                                             &TestArguments::Domain_configuration);
  // Element size
  CommandLineArgs::specify_command_line_flag("--element_size",
                                             &TestArguments::Element_size);
  // Sample point container
  CommandLineArgs::specify_command_line_flag("--non_ref_bin");
  CommandLineArgs::specify_command_line_flag("--ref_bin");
 #ifdef OOMPH_HAS_CGAL
  CommandLineArgs::specify_command_line_flag("--cgal");
 #endif
  // Max adaptations
  CommandLineArgs::specify_command_line_flag("--max_adapt",
                                             &TestArguments::Max_adapt);
  // Max. permitted error
  CommandLineArgs::specify_command_line_flag("--max_permitted_error",
                                             &TestArguments::Max_permitted_error);
  // Min. permitted error
  CommandLineArgs::specify_command_line_flag("--min_permitted_error",
                                             &TestArguments::Min_permitted_error);
  // Max. element size
  CommandLineArgs::specify_command_line_flag("--max_element_size",
                                             &TestArguments::Max_element_size);
  // Min. element size
  CommandLineArgs::specify_command_line_flag("--min_element_size",
                                             &TestArguments::Min_element_size);
  // Do load balance?
  CommandLineArgs::specify_command_line_flag("--load_balance",
                                             &TestArguments::Load_balance);
  // Max adaptations
  CommandLineArgs::specify_command_line_flag("--folder_distribution_file",
                                             &TestArguments::Folder_distribution_file);
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Label for output
  DocInfo doc_info;
  // Output directory
  doc_info.set_directory("RESLT");
  // Do not monitor memory usage
  MemoryUsage::Bypass_all_memory_usage_monitoring=true;
  // Swith timings on
  Global_timings::Doc_comprehensive_timings = true;
  // Only set one!
  unsigned count=0;
  if (CommandLineArgs::command_line_flag_has_been_set("--non_ref_bin"))
   {
    count++;
    MeshAsGeomObject_Helper::Default_sample_point_container_version=
     UseNonRefineableBinArray;
   }
  if (CommandLineArgs::command_line_flag_has_been_set("--ref_bin"))
   {
    count++;
    MeshAsGeomObject_Helper::Default_sample_point_container_version=
     UseRefineableBinArray;
   }
 #ifdef OOMPH_HAS_CGAL
  if (CommandLineArgs::command_line_flag_has_been_set("--cgal"))
   {
    count++;
    MeshAsGeomObject_Helper::Default_sample_point_container_version=
     UseCGALSamplePointContainer;
   }
 #endif
  if (count>1)
   {
    std::ostringstream error_message;
    error_message
     << "Can only choose one of --non_ref_bin, --ref_bin or --cgal!";
    throw OomphLibError(error_message.str(),
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
   }
  // Use quadratic elements to solve the problem
  //----------------------------------------------
  //Set up the problem
  PoissonProblem<ProjectablePoissonElement<TPoissonElement<2,3> > >
    problem(&TanhSolnForPoisson::get_source, TestArguments::Element_size, TestArguments::Domain_configuration);
  // Open the trace file (the name of the trace file is different for
  // each processor)
  char trace_filename[100];
  sprintf(trace_filename,"%s/trace_proc%i.dat",
          doc_info.directory().c_str(), my_rank);
  ofstream trace_file;
  trace_file.open(trace_filename);
  // Doc the initial mesh
  problem.doc_solution(doc_info, trace_file);
  //Increment counter for solutions
  doc_info.number()++;
  // Once the mesh has been created, suppress the generation of points
  // along the boundaries by Triangle during mesh adaptation
  problem.mesh_pt()->disable_automatic_creation_of_vertices_on_boundaries();
  // Set the number of bins for area transfer
  problem.mesh_pt()->nbin_x_for_area_transfer() = 100; // default values
  problem.mesh_pt()->nbin_y_for_area_transfer() = 100; // default values
 #ifdef OOMPH_HAS_MPI
  // Store the distribution of the elements
  Vector<unsigned> distributed_elements;
  // Should we read the distribution from file
  if(CommandLineArgs::command_line_flag_has_been_set("--folder_distribution_file"))
   {
    // Read a custom distribution from file
    Vector<unsigned> input_distribution;
    problem.read_custom_distribution_from_file(input_distribution);
    // Distribute the problem and store the distribution of the elements
    distributed_elements = problem.distribute(input_distribution);
   }
  else
   {
    // Distribute problem
    distributed_elements = problem.distribute();
    // Uncomment the next lines if you want to save the distribution to
    // file. Create a file with the custom distribution
    //problem.save_custom_distribution_to_file(distributed_elements);
   }
  // Output the initial distributed mesh
  char file_initial_distributed_mesh[100];
  // This show us the elements assigned to this processor (remember to
  // disable the output of halo elements)
  problem.mesh_pt()->disable_output_of_halo_elements();
  sprintf(file_initial_distributed_mesh,
          "%s/output_initial_distributed_mesh_%i.dat",
          doc_info.directory().c_str(), my_rank);
  problem.mesh_pt()->output(file_initial_distributed_mesh, 2);
 #endif // OOMPH_HAS_MPI
  // Solve the problem doing (parallel unstructured) mesh adaptation
  problem.newton_solve(TestArguments::Max_adapt);
  // Document the solution
  problem.doc_solution(doc_info, trace_file);
  //Increment counter for solutions
  doc_info.number()++;
  // Do load balance?
  if (TestArguments::Load_balance > 0)
   {
    // Perform load balance
    problem.load_balance();
   } // if (load_balance > 0)
  //Output solution (balanced solution)
  problem.doc_solution(doc_info, trace_file);
  //Increment counter for solutions
  doc_info.number()++;
  // Close the trace file
  trace_file.close();
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::finalize();
 #endif
  // Return exit successful
  return 0;
 }
References oomph::MemoryUsage::Bypass_all_memory_usage_monitoring, oomph::CommandLineArgs::command_line_flag_has_been_set(), oomph::MeshAsGeomObject_Helper::Default_sample_point_container_version, oomph::DocInfo::directory(), oomph::Global_timings::Doc_comprehensive_timings, oomph::CommandLineArgs::doc_specified_flags(), TestArguments::Domain_configuration, TestArguments::Element_size, TestArguments::Folder_distribution_file, TanhSolnForPoisson::get_source(), TestArguments::Load_balance, TestArguments::Max_adapt, TestArguments::Max_element_size, TestArguments::Max_permitted_error, TestArguments::Min_element_size, TestArguments::Min_permitted_error, oomph::DocInfo::number(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::CommandLineArgs::parse_and_assign(), problem, oomph::DocInfo::set_directory(), Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), oomph::UseNonRefineableBinArray, and oomph::UseRefineableBinArray.