MercuryDPM: ChuteWithHopper Class Reference
ChuteWithHopper Class Reference
ChuteWithHopper has a hopper as inflow.
#include <ChuteWithHopper.h>
Public Member Functions
ChuteWithHopper (const Chute &other)
This is a copy constructor for Chute problems.
ChuteWithHopper (const Mercury3D &other)
Copy constructor, converts an existing Mercury3D object into a ChuteWithHopper object.
ChuteWithHopper (const MercuryBase &other)
Copy constructor, converts an existing MercuryBase object into a ChuteWithHopper object.
ChuteWithHopper (const DPMBase &other)
Copy constructor, converts an existing DPMBase object into a ChuteWithHopper object.
ChuteWithHopper ()
This is the default constructor.
void setHopperFillingPercentage (Mdouble hopperFillingPercentage)
Sets the hopper filling percentage.
void setHopperLowestPoint (Mdouble hopperLowestPoint)
Sets the vertical distance of the lowest hopper point relative to the start of the chute.
Mdouble getHopperLowestPoint () const
Returns the vertical distance of the lowest hopper point relative to the start of the chute.
Mdouble getChuteLength () const
Allows chute length to be accessed.
void setChuteLength (Mdouble chuteLength) override
sets xMax to chuteLength+hopperlength_, and thus specifies the length off the runoff chute
void setIsHopperCentred (bool isHopperCentred)
Sets an extra shift in X-direction of the whole system.
void setHopperLowerFillingHeight (Mdouble hopperLowerFillingHeight)
Sets the height above which the hopper is filled with new particles.
void setHopperShift (Mdouble hopperShift)
Sets the shift in X-direction of the whole setup after rotation.
void setHopperLift (Mdouble hopperLift)
This lifts the hopper above the plane of the chute (after rotation)
Mdouble getHopperLift () const
Returns the hopper's lift above the chute bottom plane.
Mdouble getHopperShift () const
Returns the shift in X-direction of the whole setup after rotation.
void setHopperDimension (unsigned int hopperDimension)
Sets whether the hopper should have vertical (1) or inclined (2) walls in Y-direction.
void setIsHopperAlignedWithBottom (bool isHopperAlignedWithBottom)
Sets the alignment of hopper with chute bottom.
Mdouble getHopperAngle () const
Returns the angle of the hopper entrance relative to the vertical.
Mdouble getHopperLength () const
Returns the width of the hopper entrance.
Mdouble getHopperExitLength () const
Returns the width of the hopper exit.
Mdouble getHopperHeight () const
Returns the height of the hopper relative to the chute start.
Mdouble getHopperExitHeight () const
Returns the height of the lowest hopper point above the chute.
bool getIsHopperCentred () const
Returns whether the setup is shifted another 40 units in X-direction.
Mdouble getHopperFillingPercentage () const
Returns the vertical percentage of the hopper insertion boundary which is filled.
unsigned int getHopperDimension () const
Returns whether the hopper has vertical (1) or inclined (2) walls in Y-direction.
void setupInitialConditions () override
Sets up the initial conditions for the problem.
void setHopper (Mdouble exitLength, Mdouble exitHeight, Mdouble angle, Mdouble length, Mdouble height)
Sets the hopper's geometrical properties.
Mdouble getMaximumVelocityInducedByGravity () const
Returns the theoretical maximum particle velocity due to gravity.
Mdouble getTimeStepRatio () const
Returns smallest particle radius over maximum gravitational velocity.
void read (std::istream &is, ReadOptions opt=ReadOptions::ReadAll) override
Reads setup properties from an istream.
void write (std::ostream &os, bool writeAllParticles=true) const override
Writes setup properties to an ostream.
bool readNextArgument (int &i, int argc, char *argv[]) override
Reads setup properties from a string.
Public Member Functions inherited from Chute
Chute ()
This is the default constructor. All it does is set sensible defaults.
Chute (const DPMBase &other)
Copy constructor, converts an existing DPMBase problem into a Chute problem.
Chute (const MercuryBase &other)
Copy constructor, converts an existing MercuryBase problem into a Chute problem.
Chute (const Mercury3D &other)
Copy constructor, converts an existing Mercury3D problem into a Chute problem.
Chute (const Chute &other)
Default copy constructor.
void constructor ()
This is the actual constructor METHOD; it is called by all constructors above (except the default copy constructor).
void setupSideWalls ()
Creates chute side walls (either solid or periodic)
void makeChutePeriodic ()
This makes the chute periodic in Y.
bool getIsPeriodic () const
Returns whether the chute is periodic in Y.
void setFixedParticleRadius (Mdouble fixedParticleRadius)
Sets the particle radius of the fixed particles which constitute the (rough) chute bottom.
Mdouble getFixedParticleRadius () const
Returns the particle radius of the fixed particles which constitute the (rough) chute bottom.
void setFixedParticleSpacing (Mdouble fixedParticleSpacing)
Sets the spacing of the fixed particles which constitute the (rough) chute bottom; used in triangular packing only.
Mdouble getFixedParticleSpacing () const
Returns the particle radius of the fixed particles which constitute the (rough) chute bottom; used in triangular packing only.
void setRoughBottomType (RoughBottomType roughBottomType)
Sets the type of rough bottom of the chute.
void setRoughBottomType (std::string roughBottomTypeString)
Sets the type of rough bottom of the chute, using a string with the EXACT enum type as input.
RoughBottomType getRoughBottomType () const
Returns the type of (rough) bottom of the chute.
void setChuteAngle (Mdouble chuteAngle)
Sets gravity vector according to chute angle (in degrees)
void setChuteAngleAndMagnitudeOfGravity (Mdouble chuteAngle, Mdouble gravity)
Sets gravity vector according to chute angle (in degrees)
Mdouble getChuteAngle () const
Returns the chute angle (in radians)
Mdouble getChuteAngleDegrees () const
Returns the chute angle (in degrees)
void setMaxFailed (unsigned int maxFailed)
Sets the number of times a particle will be tried to be added to the insertion boundary.
unsigned int getMaxFailed () const
Returns the number of times a particle will be tried to be added to the insertion boundary.
void setInflowParticleRadius (Mdouble inflowParticleRadius)
Sets the radius of the inflow particles to a single one (i.e. ensures a monodisperse inflow).
void setInflowParticleRadius (Mdouble minInflowParticleRadius, Mdouble maxInflowParticleRadius)
Sets the minimum and maximum radius of the inflow particles.
void setMinInflowParticleRadius (Mdouble minInflowParticleRadius)
sets the minimum radius of inflow particles
void setMaxInflowParticleRadius (Mdouble maxInflowParticleRadius)
Sets the maximum radius of inflow particles.
Mdouble getInflowParticleRadius () const
Returns the average radius of inflow particles.
Mdouble getMinInflowParticleRadius () const
returns the minimum radius of inflow particles
Mdouble getMaxInflowParticleRadius () const
Returns the maximum radius of inflow particles.
void setInflowHeight (Mdouble inflowHeight)
Sets maximum inflow height (Z-direction)
Mdouble getInflowHeight () const
Returns the maximum inflow height (Z-direction)
void setInflowVelocity (Mdouble inflowVelocity)
Sets the average inflow velocity.
Mdouble getInflowVelocity () const
Returns the average inflow velocity.
void setInflowVelocityVariance (Mdouble inflowVelocityVariance)
Sets the inflow velocity variance.
Mdouble getInflowVelocityVariance () const
Returns the inflow velocity variance.
void setChuteWidth (Mdouble chuteWidth)
Sets the chute width (Y-direction)
Mdouble getChuteWidth () const
Returns the chute width (Y-direction)
Mdouble getChuteLength () const
Returns the chute length (X-direction)
void setInsertionBoundary (InsertionBoundary *insertionBoundary)
Sets the chute insertion boundary.
Public Member Functions inherited from Mercury3D
Mercury3D ()
This is the default constructor. All it does is set sensible defaults.
Mercury3D (const DPMBase &other)
Copy-constructor for creates an Mercury3D problem from an existing MD problem.
Mercury3D (const Mercury3D &other)
Copy-constructor.
void constructor ()
Function that sets the SystemDimension and ParticleDimension to 3.
std::vector< BaseParticle * > hGridFindParticleContacts (const BaseParticle *obj) override
Returns all particles that have a contact with a given particle.
Public Member Functions inherited from MercuryBase
MercuryBase ()
This is the default constructor. It sets sensible defaults.
~MercuryBase () override
This is the default destructor.
MercuryBase (const MercuryBase &mercuryBase)
Copy-constructor.
void constructor ()
This is the actual constructor, it is called do both constructors above.
void hGridActionsBeforeTimeLoop () override
This sets up the broad phase information, has to be done at this stage because it requires the particle size.
void hGridActionsBeforeTimeStep () override
Performs all necessary actions before a time-step, like updating the particles and resetting all the bucket information, etc.
void read (std::istream &is, ReadOptions opt=ReadOptions::ReadAll) override
Reads the MercuryBase from an input stream, for example a restart file.
void write (std::ostream &os, bool writeAllParticles=true) const override
Writes all data into a restart file.
Mdouble getHGridCurrentMaxRelativeDisplacement () const
Returns hGridCurrentMaxRelativeDisplacement_.
Mdouble getHGridTotalCurrentMaxRelativeDisplacement () const
Returns hGridTotalCurrentMaxRelativeDisplacement_.
void setHGridUpdateEachTimeStep (bool updateEachTimeStep)
Sets whether or not the HGrid must be updated every time step.
bool getHGridUpdateEachTimeStep () const final
Gets whether or not the HGrid is updated every time step.
void setHGridMaxLevels (unsigned int HGridMaxLevels)
Sets the maximum number of levels of the HGrid in this MercuryBase.
unsigned int getHGridMaxLevels () const
Gets the maximum number of levels of the HGrid in this MercuryBase.
HGridMethod getHGridMethod () const
Gets whether the HGrid in this MercuryBase is BOTTOMUP or TOPDOWN.
void setHGridMethod (HGridMethod hGridMethod)
Sets the HGridMethod to either BOTTOMUP or TOPDOWN.
HGridDistribution getHGridDistribution () const
Gets how the sizes of the cells of different levels are distributed.
void setHGridDistribution (HGridDistribution hGridDistribution)
Sets how the sizes of the cells of different levels are distributed.
Mdouble getHGridCellOverSizeRatio () const
Gets the ratio of the smallest cell over the smallest particle.
void setHGridCellOverSizeRatio (Mdouble cellOverSizeRatio)
Sets the ratio of the smallest cell over the smallest particle.
bool hGridNeedsRebuilding ()
Gets if the HGrid needs rebuilding before anything else happens.
virtual unsigned int getHGridTargetNumberOfBuckets () const
Gets the desired number of buckets, which is the maximum of the number of particles and 10.
virtual Mdouble getHGridTargetMinInteractionRadius () const
Gets the desired size of the smallest cells of the HGrid.
virtual Mdouble getHGridTargetMaxInteractionRadius () const
Gets the desired size of the largest cells of the HGrid.
bool checkParticleForInteraction (const BaseParticle &P) final
Checks if given BaseParticle has an interaction with a BaseWall or other BaseParticle.
bool checkParticleForInteractionLocal (const BaseParticle &P) final
Checks if the given BaseParticle has an interaction with a BaseWall or other BaseParticles in a local domain.
virtual Mdouble userHGridCellSize (unsigned int level)
Virtual function that enables inheriting classes to implement a function to let the user set the cell size of the HGrid.
void hGridInfo (std::ostream &os=std::cout) const
Writes the info of the HGrid to the screen in a nice format.
Public Member Functions inherited from DPMBase
void constructor ()
A function which initialises the member variables to default values, so that the problem can be solved off the shelf; sets up a basic two dimensional problem which can be solved off the shelf. It is called in the constructor DPMBase().
DPMBase ()
Constructor that calls the "void constructor()".
DPMBase (const DPMBase &other)
Copy constructor type-2.
virtual ~DPMBase ()
virtual destructor
void autoNumber ()
The autoNumber() function calls three functions: setRunNumber(), readRunNumberFromFile() and incrementRunNumberInFile().
std::vector< int > get1DParametersFromRunNumber (int size_x) const
This turns a counter into 1 index, which is a useful feature for performing 1D parameter study. The index run from 1:size_x, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get2DParametersFromRunNumber (int size_x, int size_y) const
This turns a counter into 2 indices which is a very useful feature for performing a 2D study. The indices run from 1:size_x and 1:size_y, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get3DParametersFromRunNumber (int size_x, int size_y, int size_z) const
This turns a counter into 3 indices, which is a useful feature for performing a 3D parameter study. The indices run from 1:size_x, 1:size_y and 1:size_z, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
int launchNewRun (const char *name, bool quick=false)
This launches a code from within this code. Please pass the name of the code to run.
void setRunNumber (int runNumber)
This sets the counter/Run number, overriding the defaults.
int getRunNumber () const
This returns the current value of the counter (runNumber_)
virtual void decompose ()
Sends particles from processorId to the root processor.
void solve ()
The work horse of the code.
void initialiseSolve ()
Beginning of the solve routine, before time stepping.
void finaliseSolve ()
End of the solve routine, after time stepping.
virtual void computeOneTimeStep ()
Performs everything needed for one time step, used in the time-loop of solve().
void checkSettings ()
Checks if the essentials are set properly to go ahead with solving the problem.
void forceWriteOutputFiles ()
Writes output files immediately, even if the current time step was not meant to be written. Also resets the last saved time step.
virtual void writeOutputFiles ()
Writes simulation data to all the main Mercury files: .data, .ene, .fstat, .xballs and .restart (see the Mercury website for more details regarding these files).
void solve (int argc, char *argv[])
The work horse of the code. Can handle flags from the command line.
virtual void writeXBallsScript () const
This writes a script which can be used to load the xballs problem to display the data just generated.
virtual Mdouble getInfo (const BaseParticle &P) const
A virtual function that returns some user-specified information about a particle.
ParticleVtkWriter * getVtkWriter () const
virtual void writeRestartFile ()
Stores all the particle data for current save time step to a "restart" file, which is a file simply intended to store all the information necessary to "restart" a simulation from a given time step (see also MercuryDPM.org for more information on restart files).
void writeDataFile ()
void writeEneFile ()
void writeFStatFile ()
void fillDomainWithParticles (unsigned N=50)
bool readRestartFile (ReadOptions opt=ReadOptions::ReadAll)
Reads all the particle data corresponding to a given, existing . restart file (for more details regarding restart files, refer to the training materials on the MercuryDPM website).Returns true if it is successful, false otherwise.
int readRestartFile (std::string fileName, ReadOptions opt=ReadOptions::ReadAll)
The same as readRestartFile(bool), but also reads all the particle data corresponding to the current saved time step.
virtual BaseWall * readUserDefinedWall (const std::string &type) const
Allows you to read in a wall defined in a Driver directory; see USER/Luca/ScrewFiller.
virtual void readOld (std::istream &is)
Reads all data from a restart file, e.g. domain data and particle data; old version.
bool readDataFile (std::string fileName="", unsigned int format=0)
This allows particle data to be reloaded from data files.
bool readParAndIniFiles (std::string fileName)
Allows the user to read par.ini files (useful to read files produced by the MDCLR simulation code - external to MercuryDPM)
bool readNextDataFile (unsigned int format=0)
Reads the next data file with default format=0. However, one can modify the format based on whether the particle data corresponds to 3D or 2D data- see Visualising data in xballs.
void readNextFStatFile ()
Reads the next fstat file.
bool findNextExistingDataFile (Mdouble tMin, bool verbose=true)
Finds and opens the next data file, if such a file exists.
bool readArguments (int argc, char *argv[])
Can interpret main function input arguments that are passed by the driver codes.
bool checkParticleForInteractionLocalPeriodic (const BaseParticle &P)
void readSpeciesFromDataFile (bool read=true)
void importParticlesAs (ParticleHandler &particleHandler, InteractionHandler &interactionHandler, const ParticleSpecies *species)
Copies particles, interactions assigning species from a local simulation to a global one. Useful for the creation of a cluster.
MERCURYDPM_DEPRECATED File & getDataFile ()
The non const version. Allows one to edit the File::dataFile.
MERCURYDPM_DEPRECATED File & getEneFile ()
The non const version. Allows to edit the File::eneFile.
MERCURYDPM_DEPRECATED File & getFStatFile ()
The non const version. Allows to edit the File::fStatFile.
MERCURYDPM_DEPRECATED File & getRestartFile ()
The non const version. Allows to edit the File::restartFile.
MERCURYDPM_DEPRECATED File & getStatFile ()
The non const version. Allows to edit the File::statFile.
File & getInteractionFile ()
Return a reference to the file InteractionsFile.
MERCURYDPM_DEPRECATED const File & getDataFile () const
The const version. Does not allow for any editing of the File::dataFile.
MERCURYDPM_DEPRECATED const File & getEneFile () const
The const version. Does not allow for any editing of the File::eneFile.
MERCURYDPM_DEPRECATED const File & getFStatFile () const
The const version. Does not allow for any editing of the File::fStatFile.
MERCURYDPM_DEPRECATED const File & getRestartFile () const
The const version. Does not allow for any editing of the File::restartFile.
MERCURYDPM_DEPRECATED const File & getStatFile () const
The const version. Does not allow for any editing of the File::statFile.
const File & getInteractionFile () const
Returns a constant reference to an Interactions file.
const std::string & getName () const
Returns the name of the file. Does not allow to change it though.
void setName (const std::string &name)
Allows to set the name of all the files (ene, data, fstat, restart, stat)
void setName (const char *name)
Calls setName(std::string)
void setSaveCount (unsigned int saveCount)
Sets File::saveCount_ for all files (ene, data, fstat, restart, stat)
void setFileType (FileType fileType)
Sets File::fileType_ for all files (ene, data, fstat, restart, stat)
void setOpenMode (std::fstream::openmode openMode)
Sets File::openMode_ for all files (ene, data, fstat, restart, stat)
void resetFileCounter ()
Resets the file counter for each file i.e. for ene, data, fstat, restart, stat)
void closeFiles ()
Closes all files (ene, data, fstat, restart, stat) that were opened to read or write.
void setVTKOutputDirectory (const std::string &dir)
Sets the output directory of the VTK files.
void setLastSavedTimeStep (unsigned int nextSavedTimeStep)
Sets the next time step for all the files (ene, data, fstat, restart, stat) at which the data is to be written or saved.
Mdouble getTime () const
Returns the current simulation time.
Mdouble getNextTime () const
Returns the current simulation time.
unsigned int getNumberOfTimeSteps () const
Returns the current counter of time-steps, i.e. the number of time-steps that the simulation has undergone so far.
void setTime (Mdouble time)
Sets a new value for the current simulation time.
void setTimeMax (Mdouble newTMax)
Sets a new value for the maximum simulation duration.
Mdouble getTimeMax () const
Returns the maximum simulation duration.
void setLogarithmicSaveCount (Mdouble logarithmicSaveCountBase)
Sets File::logarithmicSaveCount_ for all files (ene, data, fstat, restart, stat)
void setNToWrite (int nToWrite)
set the number of elements to write to the screen
int getNToWrite () const
get the number of elements to write to the
void setRotation (bool rotation)
Sets whether particle rotation is enabled or disabled.
bool getRotation () const
Indicates whether particle rotation is enabled or disabled.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (FileType writeWallsVTK)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (bool)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setInteractionsWriteVTK (bool)
Sets whether interactions are written into a VTK file.
void setParticlesWriteVTK (bool writeParticlesVTK)
Sets whether particles are written in a VTK file.
void setSuperquadricParticlesWriteVTK (bool writeSuperquadricParticlesVTK)
MERCURYDPM_DEPRECATED FileType getWallsWriteVTK () const
Returns whether walls are written in a VTK file.
bool getParticlesWriteVTK () const
Returns whether particles are written in a VTK file.
bool getSuperquadricParticlesWriteVTK () const
Mdouble getXMin () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMin() returns XMin.
Mdouble getXMax () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMax() returns XMax.
Mdouble getYMin () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMin() returns YMin.
Mdouble getYMax () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMax() returns XMax.
Mdouble getZMin () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMin() returns ZMin.
Mdouble getZMax () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMax() returns ZMax.
Mdouble getXCenter () const
Mdouble getYCenter () const
Mdouble getZCenter () const
Vec3D getCenter () const
get center of domain
Vec3D getMin () const
Returns the minimum coordinates of the problem domain.
Vec3D getMax () const
Returns the maximum coordinates of the problem domain.
void setXMin (Mdouble newXMin)
Sets the value of XMin, the lower bound of the problem domain in the x-direction.
void setYMin (Mdouble newYMin)
Sets the value of YMin, the lower bound of the problem domain in the y-direction.
void setZMin (Mdouble newZMin)
Sets the value of ZMin, the lower bound of the problem domain in the z-direction.
void setXMax (Mdouble newXMax)
Sets the value of XMax, the upper bound of the problem domain in the x-direction.
void setYMax (Mdouble newYMax)
Sets the value of YMax, the upper bound of the problem domain in the y-direction.
void setZMax (Mdouble newZMax)
Sets the value of ZMax, the upper bound of the problem domain in the z-direction.
void setMax (const Vec3D &max)
Sets the maximum coordinates of the problem domain.
void setMax (Mdouble, Mdouble, Mdouble)
Sets the maximum coordinates of the problem domain.
void setDomain (const Vec3D &min, const Vec3D &max)
Sets the minimum coordinates of the problem domain.
void setMin (const Vec3D &min)
Sets the minimum coordinates of the problem domain.
void setMin (Mdouble, Mdouble, Mdouble)
Sets the minimum coordinates of the problem domain.
void setTimeStep (Mdouble newDt)
Sets a new value for the simulation time step.
Mdouble getTimeStep () const
Returns the simulation time step.
void setNumberOfOMPThreads (int numberOfOMPThreads)
Sets the number of omp threads.
int getNumberOfOMPThreads () const
Returns the number of omp threads.
void setXBallsColourMode (int newCMode)
Set the xballs output mode.
int getXBallsColourMode () const
Get the xballs colour mode (CMode).
void setXBallsVectorScale (double newVScale)
Set the scale of vectors in xballs.
double getXBallsVectorScale () const
Returns the scale of vectors used in xballs.
void setXBallsAdditionalArguments (std::string newXBArgs)
Set the additional arguments for xballs.
std::string getXBallsAdditionalArguments () const
Returns the additional arguments for xballs.
void setXBallsScale (Mdouble newScale)
Sets the scale of the view (either normal, zoom in or zoom out) to display in xballs. The default is fit to screen.
double getXBallsScale () const
Returns the scale of the view in xballs.
void setGravity (Vec3D newGravity)
Sets a new value for the gravitational acceleration.
Vec3D getGravity () const
Returns the gravitational acceleration.
void setBackgroundDrag (Mdouble backgroundDrag)
Simple access function to turn on a background drag. The force of particleVelocity*drag is applied (note, it allowed to be negative i.e. create energy)
const Mdouble getBackgroundDrag () const
Return the background drag.
void setDimension (unsigned int newDim)
Sets both the system dimensions and the particle dimensionality.
void setSystemDimensions (unsigned int newDim)
Sets the system dimensionality.
unsigned int getSystemDimensions () const
Returns the system dimensionality.
void setParticleDimensions (unsigned int particleDimensions)
Sets the particle dimensionality.
unsigned int getParticleDimensions () const
Returns the particle dimensionality.
std::string getRestartVersion () const
This is to take into account for different Mercury versions. Returns the version of the restart file.
void setRestartVersion (std::string newRV)
Sets restart_version.
bool getRestarted () const
Returns the flag denoting if the simulation was restarted or not.
void setRestarted (bool newRestartedFlag)
Allows to set the flag stating if the simulation is to be restarted or not.
bool getAppend () const
Returns whether the "append" option is on or off.
void setAppend (bool newAppendFlag)
Sets whether the "append" option is on or off.
Mdouble getElasticEnergy () const
Returns the global elastic energy within the system.
Mdouble getKineticEnergy () const
Returns the global kinetic energy stored in the system.
Mdouble getGravitationalEnergy (Vec3D origin={0, 0, 0}) const
Returns the global gravitational potential energy stored relative to a user-defined origin in the system. Note, if no origin is specified the real origin i.e. (0,0,0) is taken.
Mdouble getRotationalEnergy () const
Returns the global rotational energy stored in the system.
Mdouble getTotalEnergy () const
Mdouble getTotalMass () const
JMFT: Return the total mass of the system, excluding fixed particles.
Vec3D getCentreOfMass () const
JMFT: Return the centre of mass of the system, excluding fixed particles.
Vec3D getTotalMomentum () const
JMFT: Return the total momentum of the system, excluding fixed particles.
double getCPUTime ()
double getWallTime ()
virtual void hGridInsertParticle (BaseParticle *obj UNUSED)
virtual void hGridUpdateParticle (BaseParticle *obj UNUSED)
virtual void hGridRemoveParticle (BaseParticle *obj UNUSED)
bool mpiIsInCommunicationZone (BaseParticle *particle)
Checks if the position of the particle is in an mpi communication zone or not.
bool mpiInsertParticleCheck (BaseParticle *P)
Function that checks if the mpi particle should really be inserted by the current domain.
void insertGhostParticle (BaseParticle *P)
This function inserts a particle in the mpi communication boundaries.
void updateGhostGrid (BaseParticle *P)
Checks if the Domain/periodic interaction distance needs to be updated and updates it accordingly.
virtual void gatherContactStatistics (unsigned int index1, int index2, Vec3D Contact, Mdouble delta, Mdouble ctheta, Mdouble fdotn, Mdouble fdott, Vec3D P1_P2_normal_, Vec3D P1_P2_tangential)
//Not unsigned index because of possible wall collisions.
void setNumberOfDomains (std::vector< unsigned > direction)
Sets the number of domains in x-,y- and z-direction. Required for parallel computations.
void splitDomain (DomainSplit domainSplit)
std::vector< unsigned > getNumberOfDomains ()
returns the number of domains
Domain * getCurrentDomain ()
Function that returns a pointer to the domain corresponding to the processor.
void removeOldFiles () const
void setMeanVelocity (Vec3D V_mean_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
void setMeanVelocityAndKineticEnergy (Vec3D V_mean_goal, Mdouble Ek_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
Mdouble getTotalVolume () const
Get the total volume of the cuboid system.
Matrix3D getKineticStress () const
Calculate the kinetic stress tensor in the system averaged over the whole volume.
Matrix3D getStaticStress () const
Calculate the static stress tensor in the system averaged over the whole volume.
Matrix3D getTotalStress () const
Calculate the total stress tensor in the system averaged over the whole volume.
virtual void handleParticleRemoval (unsigned int id)
Handles the removal of particles from the particleHandler.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
void writePythonFileForVTKVisualisation () const
writes .py file for ParaView
void setWritePythonFileForVTKVisualisation (bool forceWritePythonFileForVTKVisualisation)
bool getWritePythonFileForVTKVisualisation () const
WallVTKWriter & getWallVTKWriter ()
Protected Member Functions
void addHopper ()
This creates the hopper on top of the chute, see diagram in class description for details of the points.
Protected Member Functions inherited from Chute
void actionsBeforeTimeStep () override
Calls Chute::cleanChute().
void cleanChute ()
Deletes all outflow particles once every 100 time steps.
virtual void createBottom ()
Creates the chute bottom, which can be either flat or one of three flavours of rough.
virtual void addFlowParticlesCompactly ()
Add initial flow particles in a dense packing.
virtual SphericalParticle createFlowParticle ()
void printTime () const override
prints time, max time and number of particles
Protected Member Functions inherited from Mercury3D
void hGridFindContactsWithinTargetCell (int x, int y, int z, unsigned int l)
Finds contacts between particles in the target cell.
void hGridFindContactsWithTargetCell (int x, int y, int z, unsigned int l, BaseParticle *obj)
Finds contacts between the BaseParticle and the target cell.
void computeWallForces (BaseWall *w) override
Compute contacts with a wall.
void hGridFindParticlesWithTargetCell (int x, int y, int z, unsigned int l, BaseParticle *obj, std::vector< BaseParticle * > &list)
Finds particles within target cell and stores them in a list.
void hGridGetInteractingParticleList (BaseParticle *obj, std::vector< BaseParticle * > &list) override
Obtains all neighbour particles of a given object, obtained from the hgrid.
void computeInternalForces (BaseParticle *obj) override
Finds contacts with the BaseParticle; avoids multiple checks.
bool hGridHasContactsInTargetCell (int x, int y, int z, unsigned int l, const BaseParticle *obj) const
Tests if the BaseParticle has contacts with other Particles in the target cell.
bool hGridHasParticleContacts (const BaseParticle *obj) override
Tests if a BaseParticle has any contacts in the HGrid.
void hGridRemoveParticle (BaseParticle *obj) override
Removes a BaseParticle from the HGrid.
void hGridUpdateParticle (BaseParticle *obj) override
Updates the cell (not the level) of a BaseParticle.
Protected Member Functions inherited from MercuryBase
void hGridRebuild ()
This sets up the parameters required for the contact model.
void hGridInsertParticle (BaseParticle *obj) final
Inserts a single Particle to current grid.
void hGridUpdateMove (BaseParticle *iP, Mdouble move) final
Computes the relative displacement of the given BaseParticle and updates the currentMaxRelativeDisplacement_ accordingly.
void hGridActionsBeforeIntegration () override
Resets the currentMaxRelativeDisplacement_ to 0.
void hGridActionsAfterIntegration () override
This function has to be called before integrateBeforeForceComputation.
HGrid * getHGrid ()
Gets the HGrid used by this problem.
const HGrid * getHGrid () const
Gets the HGrid used by this problem, const version.
bool readNextArgument (int &i, int argc, char *argv[]) override
Reads the next command line argument.
Protected Member Functions inherited from DPMBase
virtual void computeAllForces ()
Computes all the forces acting on the particles using the BaseInteractable::setForce() and BaseInteractable::setTorque()
virtual void computeInternalForce (BaseParticle *, BaseParticle *)
Computes the forces between two particles (internal in the sense that the sum over all these forces is zero i.e. fully modelled forces)
virtual void computeExternalForces (BaseParticle *)
Computes the external forces, such as gravity, acting on particles.
virtual void computeForcesDueToWalls (BaseParticle *, BaseWall *)
Computes the forces on the particles due to the walls (normals are outward normals)
virtual void actionsOnRestart ()
A virtual function where the users can add extra code which is executed only when the code is restarted.
virtual void actionsBeforeTimeLoop ()
A virtual function. Allows one to carry out any operations before the start of the time loop.
virtual void computeAdditionalForces ()
A virtual function which allows to define operations to be executed prior to the OMP force collect.
virtual void actionsAfterSolve ()
A virtual function which allows to define operations to be executed after the solve().
virtual void actionsAfterTimeStep ()
A virtual function which allows to define operations to be executed after time step.
void writeVTKFiles () const
virtual void outputXBallsData (std::ostream &os) const
This function writes the location of the walls and particles in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void outputXBallsDataParticle (unsigned int i, unsigned int format, std::ostream &os) const
This function writes out the particle locations into an output stream in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void writeEneHeader (std::ostream &os) const
Writes a header with a certain format for ENE file.
virtual void writeFstatHeader (std::ostream &os) const
Writes a header with a certain format for FStat file.
virtual void writeEneTimeStep (std::ostream &os) const
Write the global kinetic, potential energy, etc. in the system.
virtual void initialiseStatistics ()
virtual void outputStatistics ()
void gatherContactStatistics ()
virtual void processStatistics (bool)
virtual void finishStatistics ()
virtual void integrateBeforeForceComputation ()
Update particles' and walls' positions and velocities before force computation.
virtual void integrateAfterForceComputation ()
Update particles' and walls' positions and velocities after force computation.
virtual void checkInteractionWithBoundaries ()
There are a range of boundaries one could implement depending on ones' problem. This methods checks for interactions between particles and such range of boundaries. See BaseBoundary.h and all the boundaries in the Boundaries folder.
void setFixedParticles (unsigned int n)
Sets a number, n, of particles in the particleHandler as "fixed particles".
virtual bool continueSolve () const
A virtual function for deciding whether to continue the simulation, based on a user-specified criterion.
void outputInteractionDetails () const
Displays the interaction details corresponding to the pointer objects in the interaction handler.
bool isTimeEqualTo (Mdouble time) const
Checks whether the input variable "time" is the current time in the simulation.
void removeDuplicatePeriodicParticles ()
Removes periodic duplicate Particles.
void checkAndDuplicatePeriodicParticles ()
For simulations using periodic boundaries, checks and adds particles when necessary into the particle handler. See DPMBase.cc and PeriodicBoundary.cc for more details.
void performGhostParticleUpdate ()
When the Verlet scheme updates the positions and velocities of particles, ghost particles will need an update as wel. Their status will also be updated accordingly.
void deleteGhostParticles (std::set< BaseParticle * > &particlesToBeDeleted)
void synchroniseParticle (BaseParticle *, unsigned fromProcessor=0)
void performGhostVelocityUpdate ()
updates the final time-step velocity of the ghost particles
void disableSoftStop ()
This prevents the initialisation of the soft stop feature.
void discontinueSolve ()
This discontinues the solve loop after the current time step is finished.
Private Member Functions
void constructor ()
This is the actually constructor, get called by all constructors above.
Private Attributes
Mdouble hopperLength_
Dimension of the hopper in vertical direction.
Mdouble hopperHeight_
Dimension of the hopper in horizontal direction.
Mdouble hopperAngle_
Angle between the two pieces of the hopper walls.
Mdouble hopperExitLength_
Dimension of the hopper exit in vertical direction.
Mdouble hopperExitHeight_
Dimension of the hopper exit in vertical direction.
Mdouble hopperShift_
The x position where the Chute starts (defined as the beginning of the hopper)
Mdouble hopperLowerFillingHeight_
Relative height (in [0,1)) above which the hopper is replenished with new particles.
bool isHopperCentred_
If this flag is set, the hopper will be constructed in the xy-center of the domain, and not next to the xmin-domain boundary; by default off.
Mdouble hopperLift_
This is the vertical distance the chute is lifted above the plane.
unsigned int hopperDimension_
This is the dimension of the hopper, my default it is one dimensional and hence does not have side wall.
bool isHopperAlignedWithBottom_
This is the flag, which sets if the chute bottom is aligned with the hopper, by default it is.
Mdouble hopperFillingPercentage_
This is which percentage of the hopper is used for creating new partices;.
Mdouble hopperLowestPoint_
The NEGATIVE z coordinate of the right C point (when the left C point is in the origin)
Additional Inherited Members
Public Types inherited from DPMBase
enum class ReadOptions : int { ReadAll , ReadNoInteractions , ReadNoParticlesAndInteractions }
enum class DomainSplit {
X , Y , Z , XY ,
XZ , YZ , XYZ
}
Static Public Member Functions inherited from DPMBase
static void incrementRunNumberInFile ()
Increment the run Number (counter value) stored in the file_counter (COUNTER_DONOTDEL) by 1 and store the new value in the counter file.
static int readRunNumberFromFile ()
Read the run number or the counter from the counter file (COUNTER_DONOTDEL)
static bool areInContact (const BaseParticle *pI, const BaseParticle *pJ)
Checks if two particle are in contact or is there any positive overlap.
Public Attributes inherited from DPMBase
SpeciesHandler speciesHandler
A handler to that stores the species type i.e. LinearViscoelasticSpecies, etc.
RNG random
This is a random generator, often used for setting up the initial conditions etc...
ParticleHandler particleHandler
An object of the class ParticleHandler, contains the pointers to all the particles created.
ParticleHandler paoloParticleHandler
Fake particleHandler created by Paolo needed temporary by just Paolo.
WallHandler wallHandler
An object of the class WallHandler. Contains pointers to all the walls created.
BoundaryHandler boundaryHandler
An object of the class BoundaryHandler which concerns insertion and deletion of particles into or from regions.
PeriodicBoundaryHandler periodicBoundaryHandler
Internal handler that deals with periodic boundaries, especially in a parallel build.
DomainHandler domainHandler
An object of the class DomainHandler which deals with parallel code.
InteractionHandler interactionHandler
An object of the class InteractionHandler.
CGHandler cgHandler
Object of the class cgHandler.
File dataFile
An instance of class File to handle in- and output into a .data file.
File fStatFile
An instance of class File to handle in- and output into a .fstat file.
File eneFile
An instance of class File to handle in- and output into a .ene file.
File restartFile
An instance of class File to handle in- and output into a .restart file.
File statFile
An instance of class File to handle in- and output into a .stat file.
File interactionFile
File class to handle in- and output into .interactions file. This file hold information about interactions.
Time clock_
record when the simulation started
Detailed Description
ChuteWithHopper has a hopper as inflow.
The hopper has two parts as follows to create the finite hopper walls, we take vector between two wall points in xz-plane, then rotate clockwise and make unit length.
Sketch of the hopper
A,B,C denote three points on the left and right hopper walls which are used to construct the hopper. Shift denotes the space by which the chute has to be shifted to the right such that the hopper is in the domain. Note: the wall direction has to be set separately either period of walls.
Constructor & Destructor Documentation
ChuteWithHopper() [1/5]
ChuteWithHopper::ChuteWithHopper (const Chute & other) explicit
This is a copy constructor for Chute problems.
Bug:
This copy construct is untested
Bug:
This copy construct is untested
Copy constructor with a Chute object as an argument. This constructor basically 'upgrades' the Chute object to one of the ChuteWithHopper class. NB: The copy constructor of DPMBase has to be called because the link from DPMBase to MercuryBase is virtual.
Parameters
[in] other object of Chute class
         : DPMBase(other), Chute(other)
 {
     constructor();
 }
References constructor().
ChuteWithHopper() [2/5]
ChuteWithHopper::ChuteWithHopper (const Mercury3D & other) explicit
Copy constructor, converts an existing Mercury3D object into a ChuteWithHopper object.
Copy constructor with a Mercury3D object as an argument. This constructor basically 'upgrades' the Mercury3D object to one of the ChuteWithHopper class. NB: The copy constructor of DPMBase has to be called because the link from DPMBase to MercuryBase is virtual.
Parameters
[in] other object of Mercury3D class
         : DPMBase(other), Chute(other)
 {
     constructor();
 }
References constructor().
ChuteWithHopper() [3/5]
ChuteWithHopper::ChuteWithHopper (const MercuryBase & other) explicit
Copy constructor, converts an existing MercuryBase object into a ChuteWithHopper object.
Copy constructor with a MercuryBase object as an argument. This constructor basically 'upgrades' the MercuryBase object to one of the ChuteWithHopper class. NB: The copy constructor of DPMBase has to be called because the link from DPMBase to MercuryBase is virtual.
Parameters
[in] other object of MercuryBase class
         : DPMBase(other), Chute(other)
 {
     constructor();
 }
References constructor().
ChuteWithHopper() [4/5]
ChuteWithHopper::ChuteWithHopper (const DPMBase & other) explicit
Copy constructor, converts an existing DPMBase object into a ChuteWithHopper object.
Copy constructor with a DPMBase object as an argument. This constructor basically 'upgrades' the DPMBase object to one of the ChuteWithHopper class. NB: The copy constructor of DPMBase has to be called because the link from DPMBase to MercuryBase is virtual.
Parameters
[in] other object of DPMBase class
         : DPMBase(other), Chute(other)
 {
     constructor();
 }
References constructor().
ChuteWithHopper() [5/5]
ChuteWithHopper::ChuteWithHopper ()
This is the default constructor.
Default constructor. Calls the constructor() method.
 {
     constructor();
 }
References constructor().
Member Function Documentation
addHopper()
void ChuteWithHopper::addHopper () protected
This creates the hopper on top of the chute, see diagram in class description for details of the points.
Creates the actual hopper and rotates it so as to fit in a geometry in which the chute is parallel to the X-axis.
Todo:
Waarom had ik deze ook al weer gecomment? IFCD: this was probably BvdH
Todo:
Why shift A by arbitrary number of 40, when isHopperCentred_ = True? NB: this is probably the same shift of 40 as happens in HopperInsertionBoundary::generateParticle(RNG) with the calculation of 'point A'. NB2: seems to be just generating a nice 'view' of the hopper (in the center of the viewer...?)
 {
     //hopper walls
     //to create the finite hopper walls, we take vector between two wall points in xz-plane, then rotate clockwise and make unit length
     // A\       /A
     //   \     /       A,B,C denote three points on the left and right hopper walls which are used to construct the hopper
     //    \   /        shift denotes the space by which the chute has to be shifted to the right such that the hopper is in the domain
     //   B|   |B
     //    |   |
     //   C|   |
     //        |C
     Vec3D A, B, C, temp, normal;
     const Mdouble s = mathsFunc::sin(getChuteAngle());
     const Mdouble c = mathsFunc::cos(getChuteAngle());
     // height of the lowest part of the hopper (right C in diagram above) as compared to
     // the vertical position of the start of the chute (left C in diagram above).
     hopperLowestPoint_ = hopperExitHeight_ - hopperExitLength_ * s / c;
     // "0.5*(hopperLength_+hopperExitLength_) / tan(hopperAngle_)" is the minimum heigth of the hopper, to make sure things should flow down and not to the sides.
     // hopperHeight_ is now an input variable
     // hopperHeight_ = hopperLowestPoint_ + 1.1 * 0.5*(hopperLength_+hopperExitLength_) / tan(hopperAngle_);
     const Mdouble HopperCornerHeight =
             hopperHeight_ - 0.5 * (hopperLength_ - hopperExitLength_) / mathsFunc::tan(getChuteAngle());
     //if (HopperCornerHeight<=0.0) { hopperHeight_ += -HopperCornerHeight + P0.getRadius(); HopperCornerHeight = P0.getRadius(); }
     // first we create the LEFT hopper wall
     // coordinates of A,B,C in (vertical parallel to flow, vertical normal to flow, horizontal) direction
     A = Vec3D(-0.5 * (hopperLength_ - hopperExitLength_), 0.0, hopperHeight_);
     B = Vec3D(0.0, 0.0, HopperCornerHeight);
     C = Vec3D(0.0, 0.0, 0.0);
     // now rotate the coordinates of A,B,C to be in (x,y,z) direction
     A = Vec3D(c * A.X - s * A.Z, 0.0, s * A.X + c * A.Z);
     B = Vec3D(c * B.X - s * B.Z, 0.0, s * B.X + c * B.Z);
     C = Vec3D(c * C.X - s * C.Z, 0.0, s * C.X + c * C.Z);
     // the position of A determines hopper shift and zmax
     if (isHopperCentred_)
     {
         setHopperShift(-A.X + 40);
     }
     else
     {
         setHopperShift(-A.X);
     }
     setZMax(A.Z);
     A.X += hopperShift_;
     B.X += hopperShift_;
     C.X += hopperShift_;
     //This lifts the hopper a distance above the chute
     A.Z += hopperLift_;
     B.Z += hopperLift_;
     C.Z += hopperLift_;
     //create a finite wall from B to A and from C to B on the left hand side
     IntersectionOfWalls w_Left;
     w_Left.setSpecies(speciesHandler.getObject(0));
     temp = B - A;
     normal = Vec3D(temp.Z, 0.0, -temp.X) / std::sqrt(temp.getLengthSquared());
     w_Left.addObject(normal, A);
     temp = C - B;
     normal = Vec3D(temp.Z, 0.0, -temp.X) / std::sqrt(temp.getLengthSquared());
     w_Left.addObject(normal, B);
     temp = A - C;
     normal = Vec3D(temp.Z, 0.0, -temp.X) / std::sqrt(temp.getLengthSquared());
     w_Left.addObject(normal, C);
     wallHandler.copyAndAddObject(w_Left);
     //next, do the same for the right wall
     A = Vec3D(hopperLength_ - 0.5 * (hopperLength_ - hopperExitLength_), 0.0, hopperHeight_);
     B = Vec3D(0.5 * (hopperLength_ + hopperExitLength_) - 0.5 * (hopperLength_ - hopperExitLength_), 0.0,
               HopperCornerHeight);
     C = Vec3D(0.5 * (hopperLength_ + hopperExitLength_) - 0.5 * (hopperLength_ - hopperExitLength_), 0.0,
               hopperLowestPoint_);
     //This rotates the right points
     A = Vec3D(c * A.X - s * A.Z + hopperShift_, 0.0, s * A.X + c * A.Z);
     B = Vec3D(c * B.X - s * B.Z + hopperShift_, 0.0, s * B.X + c * B.Z);
     C = Vec3D(c * C.X - s * C.Z + hopperShift_, 0.0, s * C.X + c * C.Z);
     //This lifts the hopper a distance above the chute
     A.Z += hopperLift_;
     B.Z += hopperLift_;
     C.Z += hopperLift_;
     //create a finite wall from B to A and from C to B on the right hand side
     IntersectionOfWalls w_Right;
     w_Right.setSpecies(speciesHandler.getObject(0));
     temp = A - B;
     normal = Vec3D(temp.Z, 0.0, -temp.X) / std::sqrt(temp.getLengthSquared());
     w_Right.addObject(normal, A);
     temp = B - C;
     normal = Vec3D(temp.Z, 0.0, -temp.X) / std::sqrt(temp.getLengthSquared());
     w_Right.addObject(normal, B);
     temp = C - A;
     normal = Vec3D(temp.Z, 0.0, -temp.X) / std::sqrt(temp.getLengthSquared());
     w_Right.addObject(normal, C);
     wallHandler.copyAndAddObject(w_Right);
     setZMax(A.Z);
     // if hopperDimension_ == 2, create inclined hopper walls (like in the X-direction) also in the Y-direction.
     // (Else, place vertical (possibly periodic) walls in Y-direction. -> not mentioned here, where is this arranged? (BvdH))
     if (hopperDimension_ == 2)
     {
         //coordinates of A,B,C in (vertical parallel to flow,vertical normal to flow, horizontal) direction
         A = Vec3D(0.0, (getYMax() - getYMin() - hopperLength_) / 2.0, hopperHeight_);
         B = Vec3D(0.0, (getYMax() - getYMin() - hopperExitLength_) / 2.0, HopperCornerHeight);
         C = Vec3D(0.0, (getYMax() - getYMin() - hopperExitLength_) / 2.0, 0.0);
         //now rotate the coordinates of A,B,C to be in (x,y,z) direction
         A = Vec3D(c * A.X - s * A.Z, A.Y, s * A.X + c * A.Z);
         B = Vec3D(c * B.X - s * B.Z, B.Y, s * B.X + c * B.Z);
         C = Vec3D(c * C.X - s * C.Z, C.Y, s * C.X + c * C.Z);
         // the position of A determines shift and zmax
         A.X += hopperShift_;
         B.X += hopperShift_;
         C.X += hopperShift_;
         //This lifts the hopper a distance above the chute
         A.Z += hopperLift_;
         B.Z += hopperLift_;
         C.Z += hopperLift_;
         //create a finite wall from B to A and from C to B
         IntersectionOfWalls w_Back;
         temp = B - A;
         normal = Vec3D::cross(Vec3D(-c, 0, -s), temp) / std::sqrt(temp.getLengthSquared());
         //normal  = Vec3D(0.0,temp.Z,-temp.Y) / std::sqrt(temp.GetLength2());
         w_Back.addObject(normal, A);
         temp = C - B;
         //normal  = Vec3D(0.0,temp.Z,-temp.Y) / std::sqrt(temp.GetLength2());
         normal = Vec3D::cross(Vec3D(-c, 0, -s), temp) / std::sqrt(temp.getLengthSquared());
         w_Back.addObject(normal, B);
         temp = A - C;
         //normal = Vec3D(0.0,temp.Z,-temp.Y)/std::sqrt(temp.GetLength2());
         normal = Vec3D::cross(Vec3D(-c, 0, -s), temp) / std::sqrt(temp.getLengthSquared());
         w_Back.addObject(normal, C);
         wallHandler.copyAndAddObject(w_Back);
         //Now for the right y-wall
         A = Vec3D(0.0, (getYMax() - getYMin() + hopperLength_) / 2.0, hopperHeight_);
         B = Vec3D(0.0, (getYMax() - getYMin() + hopperExitLength_) / 2.0, HopperCornerHeight);
         C = Vec3D(0.0, (getYMax() - getYMin() + hopperExitLength_) / 2.0, 0.0);
         //now rotate the coordinates of A,B,C to be in (x,y,z) direction
         A = Vec3D(c * A.X - s * A.Z, A.Y, s * A.X + c * A.Z);
         B = Vec3D(c * B.X - s * B.Z, B.Y, s * B.X + c * B.Z);
         C = Vec3D(c * C.X - s * C.Z, C.Y, s * C.X + c * C.Z);
         // the position of A determines shift and zmax
         A.X += hopperShift_;
         B.X += hopperShift_;
         C.X += hopperShift_;
         //This lifts the hopper a distance above the chute
         A.Z += hopperLift_;
         B.Z += hopperLift_;
         C.Z += hopperLift_;
         //create a finite wall from B to A and from C to B
         IntersectionOfWalls w_Front;
         temp = A - B;
         normal = Vec3D::cross(Vec3D(-c, 0, -s), temp) / std::sqrt(temp.getLengthSquared());
         //normal  = Vec3D(0.0,-temp.Z,temp.Y) / std::sqrt(temp.GetLength2());
         w_Front.addObject(normal, A);
         temp = B - C;
         //normal  = Vec3D(0.0,-temp.Z,temp.Y) / std::sqrt(temp.GetLength2());
         normal = Vec3D::cross(Vec3D(-c, 0, -s), temp) / std::sqrt(temp.getLengthSquared());
         w_Front.addObject(normal, B);
         temp = C - A;
         //normal = Vec3D(0.0,-temp.Z,temp.Y)/std::sqrt(temp.GetLength2());
         normal = Vec3D::cross(Vec3D(-c, 0, -s), temp) / std::sqrt(temp.getLengthSquared());
         w_Front.addObject(normal, C);
         wallHandler.copyAndAddObject(w_Front);
     }
     //now shift the chute as well, i.e. apply the shift to all the fixed particles
     // at the bottom of the chute
     for (BaseParticle* particle : particleHandler)
     {
         particle->move(Vec3D(hopperShift_, 0.0, 0.0));
     }
 }
References IntersectionOfWalls::addObject(), calibrate::c, BaseHandler< T >::copyAndAddObject(), mathsFunc::cos(), Vec3D::cross(), Chute::getChuteAngle(), Vec3D::getLengthSquared(), BaseHandler< T >::getObject(), DPMBase::getYMax(), DPMBase::getYMin(), hopperDimension_, hopperExitHeight_, hopperExitLength_, hopperHeight_, hopperLength_, hopperLift_, hopperLowestPoint_, hopperShift_, isHopperCentred_, WallFunction::normal(), DPMBase::particleHandler, s, setHopperShift(), IntersectionOfWalls::setSpecies(), DPMBase::setZMax(), mathsFunc::sin(), DPMBase::speciesHandler, sqrt(), mathsFunc::tan(), DPMBase::wallHandler, Vec3D::X, and Vec3D::Z.
Referenced by setupInitialConditions().
constructor()
void ChuteWithHopper::constructor () private
This is the actually constructor, get called by all constructors above.
constructor METHOD, which sets all ChuteWithHopper properties to something sensible.
 {
     hopperLowerFillingHeight_ = 0.5;
     hopperLift_ = 0.0;
     setHopper(0.01, 0.01, 60.0, 0.08, 0.04);
     hopperShift_ = 0.0;
     hopperDimension_ = 1;
     isHopperAlignedWithBottom_ = true;
     hopperFillingPercentage_ = 50.0;
     isHopperCentred_ = false;
 }
References hopperDimension_, hopperFillingPercentage_, hopperLift_, hopperLowerFillingHeight_, hopperShift_, isHopperAlignedWithBottom_, isHopperCentred_, and setHopper().
Referenced by ChuteWithHopper().
getChuteLength()
Mdouble ChuteWithHopper::getChuteLength () const
Allows chute length to be accessed.
Todo:
this hides the non-virtual function Chute::getChuteLength
Returns the length of the chute. The start of the view, at x = 0, is hopperShift_ to the left of the start of the chute.
Returns
the hopper length
 {
     return getXMax() - hopperShift_;
 }
References DPMBase::getXMax(), and hopperShift_.
Referenced by AngleOfRepose::actionsBeforeTimeStep(), AngleOfRepose::create_inflow_particle(), and AngleOfRepose::setupInitialConditions().
getHopperAngle()
Mdouble ChuteWithHopper::getHopperAngle () const
Returns the angle of the hopper entrance relative to the vertical.
Returns the hopper angle (relative to the vertical) in RADIANS
 {
     return hopperAngle_;
 }
References hopperAngle_.
Referenced by SegregationWithHopper::create_inflow_particle().
getHopperDimension()
unsigned int ChuteWithHopper::getHopperDimension () const
Returns whether the hopper has vertical (1) or inclined (2) walls in Y-direction.
Returns the hopperDimension_ property, which determines whether the hopper entrance walls in the Y-direction are inclined (2) or vertical (1).
 {
     return hopperDimension_;
 }
References hopperDimension_.
getHopperExitHeight()
Mdouble ChuteWithHopper::getHopperExitHeight () const
Returns the height of the lowest hopper point above the chute.
Returns the (vertical) height of the lowest point of the hopper (hopperLowestPoint_) above the (inclined) chute bottom
 {
     return hopperExitHeight_;
 }
References hopperExitHeight_.
getHopperExitLength()
Mdouble ChuteWithHopper::getHopperExitLength () const
Returns the width of the hopper exit.
Returns the width of the (rectangular) hopper exit
 {
     return hopperExitLength_;
 }
References hopperExitLength_.
Referenced by SegregationWithHopper::create_inflow_particle().
getHopperFillingPercentage()
Mdouble ChuteWithHopper::getHopperFillingPercentage () const
Returns the vertical percentage of the hopper insertion boundary which is filled.
Returns the percentage of the height of the hopper insertion boundary up to which it should be filled. The part to be filled reaches from the top of the hopper down to {fillPercent * (top - 'position A')}. See also the documentation of the HopperInsertionBoundary class.
 {
     return hopperFillingPercentage_;
 }
References hopperFillingPercentage_.
getHopperHeight()
Mdouble ChuteWithHopper::getHopperHeight () const
Returns the height of the hopper relative to the chute start.
Returns the (vertical) height of the hopper relative to the start of the chute
 {
     return hopperHeight_;
 }
References hopperHeight_.
Referenced by SegregationWithHopper::create_inflow_particle().
getHopperLength()
Mdouble ChuteWithHopper::getHopperLength () const
Returns the width of the hopper entrance.
Returns the horizontal width of the hopper input (at the top of the hopper)
 {
     return hopperLength_;
 }
References hopperLength_.
Referenced by SegregationWithHopper::create_inflow_particle().
getHopperLift()
Mdouble ChuteWithHopper::getHopperLift () const
Returns the hopper's lift above the chute bottom plane.
Returns the amount the hopper is lifted above the X-axis (in Z-direction, i.e. AFTER rotation of the system to have the chute parallel to the X-axis)
 {
     return hopperLift_;
 }
References hopperLift_.
getHopperLowestPoint()
Mdouble ChuteWithHopper::getHopperLowestPoint () const
Returns the vertical distance of the lowest hopper point relative to the start of the chute.
 {
     return hopperLowestPoint_;
 }
References hopperLowestPoint_.
Referenced by setHopper().
getHopperShift()
Mdouble ChuteWithHopper::getHopperShift () const
Returns the shift in X-direction of the whole setup after rotation.
Returns the distance the whole setup is shifted in the X-direction relative from the position at which the start of the CHUTE is at X = 0.
 {
     return hopperShift_;
 }
References hopperShift_.
getIsHopperCentred()
bool ChuteWithHopper::getIsHopperCentred () const
Returns whether the setup is shifted another 40 units in X-direction.
Returns the isHopperCentered_ property, which determines whether the whole setup is shifted another 40 units of length in the X-direction. See also ChuteWithHopper::addHopper().
Returns
if TRUE, the whole setup is shifted 40 units of length towards the positive X-direction.
 {
     return isHopperCentred_;
 }
References isHopperCentred_.
getMaximumVelocityInducedByGravity()
Mdouble ChuteWithHopper::getMaximumVelocityInducedByGravity () const
Returns the theoretical maximum particle velocity due to gravity.
Returns the maximum velocity a particle could theoretically reach by gravity, would it fall from the top of the hopper straight to the bottom of the system.
Returns
The maximum velocity possible due to gravity
 {
     const Mdouble height = hopperHeight_ + (getXMax() - hopperShift_) * mathsFunc::sin(getChuteAngle());
     return std::sqrt(2.0 * getGravity().getLength() * height);
 }
References Chute::getChuteAngle(), DPMBase::getGravity(), DPMBase::getXMax(), Global_Physical_Variables::height(), hopperHeight_, hopperShift_, mathsFunc::sin(), and sqrt().
Referenced by getTimeStepRatio().
getTimeStepRatio()
Mdouble ChuteWithHopper::getTimeStepRatio () const
Returns smallest particle radius over maximum gravitational velocity.
Returns the ratio of minimum particle radius over maximum distance travelled per time step due to gravitational acceleration, and returns a warning when this is smaller then a certain threshold.
Todo:
Consider generalising this method by implementing it in the MercuryBase class.
Author
BvdH NB: this method is used in ChuteWithHopper::setupInitialConditions().
 {
     const Mdouble dx = getTimeStep() * getMaximumVelocityInducedByGravity();
     const Mdouble rmin = getMinInflowParticleRadius();
     if (rmin / dx < 10.)
         logger(WARN,
                "[ChuteWithHopper::getTimeStepRatio()] ratio of minimum particle radius over max distance travelled per time step due to gravity is only %; consider reducing the time step size!",
                rmin / dx);
     return rmin / dx;
 }
References getMaximumVelocityInducedByGravity(), Chute::getMinInflowParticleRadius(), DPMBase::getTimeStep(), logger, Global_Parameters::rmin, and WARN.
Referenced by setupInitialConditions().
read()
void ChuteWithHopper::read (std::istream & is, ReadOptions opt = ReadOptions::ReadAll) override virtual
Reads setup properties from an istream.
Reads the setup properties from an istream
Parameters
[in,out] is the istream
Reimplemented from Chute.
 {
     Chute::read(is,opt);
     is >> hopperExitLength_ >> hopperExitHeight_ >> hopperLength_
        >> hopperAngle_ >> hopperHeight_ >> hopperShift_;
 }
References hopperAngle_, hopperExitHeight_, hopperExitLength_, hopperHeight_, hopperLength_, hopperShift_, and Chute::read().
readNextArgument()
bool ChuteWithHopper::readNextArgument (int & i, int argc, char * argv[]) override virtual
Reads setup properties from a string.
this reads parameters from a string.
Parameters
[in] i the index of the input parameter to be read
[in] argc number of input parameters
[in] argv[] pointer to the (first character of the) actual string
Reimplemented from Chute.
 {
     if (!strcmp(argv[i], "-hopperLength"))
     {
         hopperLength_ = (atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-hopperHeight"))
     {
         hopperHeight_ = (atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-hopperAngle"))
     {
         hopperAngle_ = (atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-hopperExitLength"))
     {
         hopperExitLength_ = (atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-hopperExitHeight"))
     {
         hopperExitHeight_ = (atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-hopperLowerFillingHeight_"))
     {
         hopperLowerFillingHeight_ = (atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-isHopperCentred"))
     {
         isHopperCentred_ = static_cast<bool>(atoi(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-alignBase"))
     {
         isHopperAlignedWithBottom_ = static_cast<bool>(atoi(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-shift"))
     {
         hopperShift_ = (atof(argv[i + 1]));
     }
     else if (!strcmp(argv[i], "-lift"))
     {
         hopperLift_ = (atof(argv[i + 1]));
     }
     else
         return Chute::readNextArgument(i, argc, argv); //if argv[i] is not found, check the commands in Chute
     return true; //returns true if argv[i] is found
 }
References hopperAngle_, hopperExitHeight_, hopperExitLength_, hopperHeight_, hopperLength_, hopperLift_, hopperLowerFillingHeight_, hopperShift_, i, isHopperAlignedWithBottom_, isHopperCentred_, and Chute::readNextArgument().
setChuteLength()
void ChuteWithHopper::setChuteLength (Mdouble chuteLength) override virtual
sets xMax to chuteLength+hopperlength_, and thus specifies the length off the runoff chute
Sets xMax_ such that the total chute length matches the argument.
Parameters
[in] chuteLength The chute length according to which xMax is to be adapted
Reimplemented from Chute.
 {
     if (chuteLength >= 0.0)
     {
         setXMax(chuteLength + hopperShift_);
         setXMin(0.0);
     }
     else
     {
         logger(WARN,
                "[ChuteWithHopper::setChuteLength()] Chute length unchanged, value must be greater than or equal to zero");
     }
 }
References hopperShift_, logger, DPMBase::setXMax(), DPMBase::setXMin(), and WARN.
Referenced by AngleOfRepose::AngleOfRepose().
setHopper()
void ChuteWithHopper::setHopper (Mdouble exitLength, Mdouble exitHeight, Mdouble angle, Mdouble length, Mdouble height)
Sets the hopper's geometrical properties.
Sets all the geometrical properties of the hopper at once
Parameters
[in] exitLength Horizontal width of the (rectangular) hopper exit
[in] exitHeight The vertical position of the lowest point of the right side of the hopper relative to the chute bottom
[in] angle The angle of the hopper inlet, relative to the vertical (in DEGREES)
[in] length Horizontal width of the hopper entrance (i.e., at the top of the hopper)
[in] height The (vertical) height of the hopper relative to the start of the chute
Todo:
: check whether hopperCornerHeight >=0, if not change hopperangle, line 105, I do not yet understand what the criteria is...
 {
     // hopperCornerHeight: helper variable, just here to check some things
     const Mdouble hopperCornerHeight =
             height - 0.5 * (length - exitLength) / mathsFunc::tan(angle * constants::pi / 180.0);
     if (exitLength >= 0.0)
     {
         hopperExitLength_ = exitLength;
     }
     else
     {
         logger(ERROR, "[ChuteWithHopper::setHopper()] Hopper exit length must be greater than or equal to zero");
         exit(-1);
     }
     // hopperExitHeight_
     if (exitHeight < 0.0)
     {
         logger(ERROR, "[ChuteWithHopper::setHopper()] Hopper exit height must be greater than or equal to zero");
         exit(-1);
     }
     else if (exitHeight > hopperCornerHeight + mathsFunc::tan(getChuteAngle()) * exitLength)
     {
         logger(ERROR,
                "[ChuteWithHopper::setHopper()] Hopper exit height (%) may not exceed height of hopper corner above chute bottom (%)",
                exitHeight, hopperCornerHeight + mathsFunc::tan(getChuteAngle()) * exitLength);
         exit(-1);
     }
     else //(exitHeight >= 0.0) /// \todo write check: exitHeight may NOT exceed vertical distance between chute base and hopper corner!
     {
         hopperExitHeight_ = exitHeight;
     }
     setHopperLowestPoint(hopperExitHeight_ - hopperExitLength_ * mathsFunc::tan(getChuteAngle()));
     if (angle > 0.0 && angle < 90.0)
     {
         hopperAngle_ = angle * constants::pi / 180.0;
     }
     else
     {
         logger(ERROR, "[ChuteWithHopper::setHopper()] Hopper angle must in (0,90)");
         exit(-1);
     }
     if (length > exitLength)
     {
         hopperLength_ = length;
     }
     else
     {
         logger(ERROR, "[ChuteWithHopper::setHopper()] Hopper length must be greater than exit length");
         exit(-1);
     }
     // check hopper 'corner height', i.e. the vertical position of point 'B' as compared to the start of the hopper
     // Mdouble hopperCornerHeight = height - 0.5 * (length - exitLength) / std::tan(hopperAngle_ * constants::pi / 180.0);
     if (hopperCornerHeight <= 0.0)
     {
         // hopperHeight_ += -hopperCornerHeight + problem.getMaxInflowParticleRadius();
         // hopperCornerHeight = problem.getMaxInflowParticleRadius();
         logger(ERROR,
                "[ChuteWithHopper::setHopper()] height of hopper corner (%) may not be below 0. Increase hopper height to fix.",
                hopperCornerHeight);
         exit(-1);
     }
     const Mdouble heightCompare = (getHopperLowestPoint() +
                                    0.5 * (hopperLength_ + hopperExitLength_) / mathsFunc::tan(hopperAngle_));
     logger(VERBOSE, " ");
     logger(VERBOSE, "[ChuteWithHopper::setHopper()] Setting the following hopper geometrical properties:");
     logger(VERBOSE, " hopperLowestPoint_: %, ", getHopperLowestPoint());
     logger(VERBOSE, " hopperLength_: %, ", hopperLength_);
     logger(VERBOSE, " hopperExitLength_: %, ", hopperExitLength_);
     logger(VERBOSE, " hopperAngle_: %, ", hopperAngle_);
     logger(VERBOSE, " height: %, ", height);
     logger(VERBOSE, " comparing height: % ", heightCompare);
     logger(VERBOSE, " ");
     //This a semi-ugly fix to check whether height>=Heightcompare and does not take into account rounding errors
     if ((height - heightCompare) > -1e-6 * heightCompare)
     {
         hopperHeight_ = height;
     }
     else
     {
         logger(ERROR,
                "[ChuteWithHopper::setHopper()] For these settings, hopper height must be greater then or equal to %, see drawing",
                heightCompare);
         exit(-1);
     }
     logger(VERBOSE, " ");
     logger(VERBOSE, "[ChuteWithHopper::setHopper()] Hopper geometry: ");
     logger(VERBOSE, "hopperHeight_: \t %", hopperHeight_);
     logger(VERBOSE, "hopperExitLength_: \t %", hopperExitLength_);
     logger(VERBOSE, "hopperExitHeight_: \t %", hopperExitHeight_);
     logger(VERBOSE, "hopperAngle_: \t %", hopperAngle_);
     logger(VERBOSE, "hopperLength_: \t %", hopperLength_);
     logger(VERBOSE, " ");
 }
References Jeffery_Solution::angle(), e(), ERROR, Chute::getChuteAngle(), getHopperLowestPoint(), Global_Physical_Variables::height(), hopperAngle_, hopperExitHeight_, hopperExitLength_, hopperHeight_, hopperLength_, logger, constants::pi, setHopperLowestPoint(), mathsFunc::tan(), and VERBOSE.
Referenced by constructor().
setHopperDimension()
void ChuteWithHopper::setHopperDimension (unsigned int hopperDimension)
Sets whether the hopper should have vertical (1) or inclined (2) walls in Y-direction.
Sets the hopperDimension_ property, which determines whether the hopper entrance walls in the Y-direction are inclined (2) or vertical (1).
 {
     hopperDimension_ = hopperDimension;
 }
References hopperDimension_.
setHopperFillingPercentage()
void ChuteWithHopper::setHopperFillingPercentage (Mdouble hopperFillingPercentage)
Sets the hopper filling percentage.
Sets the hopper filling percentage. See also the documentation of the HopperInsertionBoundary class.
Parameters
[in] hopperFillingPercentage Percentage of the height of the hopper insertion boundary up to which it should be filled. The part to be filled reaches from the top of the hopper down to {hopperFillingPercentage * (top - 'position A')}.
 {
     hopperFillingPercentage_ = hopperFillingPercentage;
 }
References hopperFillingPercentage_.
setHopperLift()
void ChuteWithHopper::setHopperLift (Mdouble hopperLift)
This lifts the hopper above the plane of the chute (after rotation)
Sets the amount the hopper is lifted above the X-axis (in Z-direction, i.e. AFTER rotation of the system to have the chute parallel to the X-axis)
 {
     hopperLift_ = hopperLift;
 }
References hopperLift_.
setHopperLowerFillingHeight()
void ChuteWithHopper::setHopperLowerFillingHeight (Mdouble hopperLowerFillingHeight)
Sets the height above which the hopper is filled with new particles.
Sets the relative height (in [0,1)) above which the hopper is replenished with new particles
 {
     hopperLowerFillingHeight_ = hopperLowerFillingHeight;
 }
References hopperLowerFillingHeight_.
setHopperLowestPoint()
void ChuteWithHopper::setHopperLowestPoint (Mdouble hopperLowestPoint)
Sets the vertical distance of the lowest hopper point relative to the start of the chute.
Sets the height difference between left hopper bottom (where the chute starts) and right hopper bottom (which 'hovers' above the chute).
Parameters
[in] hopperLowestPoint the lowest point of the right side of the hopper
 {
     hopperLowestPoint_ = hopperLowestPoint;
 }
References hopperLowestPoint_.
Referenced by setHopper().
setHopperShift()
void ChuteWithHopper::setHopperShift (Mdouble hopperShift)
Sets the shift in X-direction of the whole setup after rotation.
Sets the distance the whole setup is shifted in the X-direction relative from the position at which the start of the CHUTE is at X = 0.
Parameters
[in] hopperShift The hopper shift to be set
 {
     if (hopperShift >= 0.0)
     {
         //keeps the ChuteLength constant
         setXMax(getXMax() + hopperShift - hopperShift_);
         hopperShift_ = hopperShift;
     }
     else
     {
         logger(WARN,
                "[ChuteWithHopper::setHopperShift()] Shift length unchanged, value must be greater than or equal to zero");
     }
 }
References DPMBase::getXMax(), hopperShift_, logger, DPMBase::setXMax(), and WARN.
Referenced by addHopper().
setIsHopperAlignedWithBottom()
void ChuteWithHopper::setIsHopperAlignedWithBottom (bool isHopperAlignedWithBottom)
Sets the alignment of hopper with chute bottom.
This sets the flag, which determines if the chute bottom is aligned with the hopper
 {
     isHopperAlignedWithBottom_ = isHopperAlignedWithBottom;
 }
References isHopperAlignedWithBottom_.
setIsHopperCentred()
void ChuteWithHopper::setIsHopperCentred (bool isHopperCentred)
Sets an extra shift in X-direction of the whole system.
Sets the isHopperCentered_ property, which determines whether the whole setup is shifted another 40 units of length in the X-direction. See also ChuteWithHopper::addHopper().
Parameters
[in] isHopperCentred if TRUE, the whole setup is shifted 40 units of length towards the positive X-direction.
 {
     isHopperCentred_ = isHopperCentred;
 }
References isHopperCentred_.
setupInitialConditions()
void ChuteWithHopper::setupInitialConditions () override virtual
Sets up the initial conditions for the problem.
Sets up the problem initial conditions:
Creates chute side walls
Creates a hopper insertion boundary
Creates a chute bottom
Creates a hopper at the start of the chute
Reimplemented from Chute.
 {
     // check time step ratio
     getTimeStepRatio();
     // create chute side walls (either periodic or solid, based on (the inherited)
     // boolean Chute::isChutePeriodic_ data member).
     setupSideWalls();
     // create insertion boundary for the hopper and set a fill percentage
     SphericalParticle* p1 = new SphericalParticle();
     p1->setSpecies(speciesHandler.getObject(0));
     PSD psd;
     psd.setDistributionUniform(getMinInflowParticleRadius(), getMaxInflowParticleRadius(), 50);
     HopperInsertionBoundary b1;
     b1.set(p1, getMaxFailed(), getYMin(), getYMax(), getChuteAngle(),
            getFixedParticleRadius(), isHopperCentred_, hopperDimension_, hopperAngle_, hopperLength_,
            hopperExitLength_, hopperHeight_, hopperLift_, hopperFillingPercentage_);
     b1.setPSD(psd);
     InsertionBoundary* b1Added = boundaryHandler.copyAndAddObject(b1);
     setInsertionBoundary(b1Added);
     // create the chute bottom
     createBottom();
     // create the hopper
     addHopper();
 }
References addHopper(), DPMBase::boundaryHandler, BaseHandler< T >::copyAndAddObject(), Chute::createBottom(), Chute::getChuteAngle(), Chute::getFixedParticleRadius(), Chute::getMaxFailed(), Chute::getMaxInflowParticleRadius(), Chute::getMinInflowParticleRadius(), BaseHandler< T >::getObject(), getTimeStepRatio(), DPMBase::getYMax(), DPMBase::getYMin(), hopperAngle_, hopperDimension_, hopperExitLength_, hopperFillingPercentage_, hopperHeight_, hopperLength_, hopperLift_, isHopperCentred_, p1, HopperInsertionBoundary::set(), PSD::setDistributionUniform(), Chute::setInsertionBoundary(), InsertionBoundary::setPSD(), Chute::setupSideWalls(), and DPMBase::speciesHandler.
Referenced by Vreman::setupInitialConditions(), and AirySavageHutter::setupInitialConditions().
write()
void ChuteWithHopper::write (std::ostream & os, bool writeAllParticles = true) const override virtual
Writes setup properties to an ostream.
Writes object's properties to an ostream
Parameters
[in] os the ostream
[in] writeAllParticles If TRUE, the properties of ALL particles in the particleHandler are written to the ostream. If FALSE, only the properties of the first two particles in the handler are written to the ostream (see DPMBase::write(std::ostream& os, bool writeAllParticles)).
Reimplemented from Chute.
 {
     Chute::write(os, writeAllParticles);
     os << hopperExitLength_ << " " << hopperExitHeight_ << " " << hopperLength_
        << " " << hopperAngle_ << " " << hopperHeight_ << " " << hopperShift_ << " " << '\n';
 }
References hopperAngle_, hopperExitHeight_, hopperExitLength_, hopperHeight_, hopperLength_, hopperShift_, and Chute::write().
Referenced by AirySavageHutter::actionsOnRestart(), and AngleOfRepose::setupInitialConditions().
Member Data Documentation
hopperAngle_
Mdouble ChuteWithHopper::hopperAngle_ private
Angle between the two pieces of the hopper walls.
Referenced by getHopperAngle(), read(), readNextArgument(), setHopper(), setupInitialConditions(), and write().
hopperDimension_
unsigned int ChuteWithHopper::hopperDimension_ private
This is the dimension of the hopper, my default it is one dimensional and hence does not have side wall.
Referenced by addHopper(), constructor(), getHopperDimension(), setHopperDimension(), and setupInitialConditions().
hopperExitHeight_
Mdouble ChuteWithHopper::hopperExitHeight_ private
Dimension of the hopper exit in vertical direction.
Referenced by addHopper(), getHopperExitHeight(), read(), readNextArgument(), setHopper(), and write().
hopperExitLength_
Mdouble ChuteWithHopper::hopperExitLength_ private
Dimension of the hopper exit in vertical direction.
Referenced by addHopper(), getHopperExitLength(), read(), readNextArgument(), setHopper(), setupInitialConditions(), and write().
hopperFillingPercentage_
Mdouble ChuteWithHopper::hopperFillingPercentage_ private
This is which percentage of the hopper is used for creating new partices;.
Referenced by constructor(), getHopperFillingPercentage(), setHopperFillingPercentage(), and setupInitialConditions().
hopperHeight_
Mdouble ChuteWithHopper::hopperHeight_ private
Dimension of the hopper in horizontal direction.
Referenced by addHopper(), getHopperHeight(), getMaximumVelocityInducedByGravity(), read(), readNextArgument(), setHopper(), setupInitialConditions(), and write().
hopperLength_
Mdouble ChuteWithHopper::hopperLength_ private
Dimension of the hopper in vertical direction.
Referenced by addHopper(), getHopperLength(), read(), readNextArgument(), setHopper(), setupInitialConditions(), and write().
hopperLift_
Mdouble ChuteWithHopper::hopperLift_ private
This is the vertical distance the chute is lifted above the plane.
Referenced by addHopper(), constructor(), getHopperLift(), readNextArgument(), setHopperLift(), and setupInitialConditions().
hopperLowerFillingHeight_
Mdouble ChuteWithHopper::hopperLowerFillingHeight_ private
Relative height (in [0,1)) above which the hopper is replenished with new particles.
Referenced by constructor(), readNextArgument(), and setHopperLowerFillingHeight().
hopperLowestPoint_
Mdouble ChuteWithHopper::hopperLowestPoint_ private
The NEGATIVE z coordinate of the right C point (when the left C point is in the origin)
Referenced by addHopper(), getHopperLowestPoint(), and setHopperLowestPoint().
hopperShift_
Mdouble ChuteWithHopper::hopperShift_ private
The x position where the Chute starts (defined as the beginning of the hopper)
Referenced by addHopper(), constructor(), getChuteLength(), getHopperShift(), getMaximumVelocityInducedByGravity(), read(), readNextArgument(), setChuteLength(), setHopperShift(), and write().
isHopperAlignedWithBottom_
bool ChuteWithHopper::isHopperAlignedWithBottom_ private
This is the flag, which sets if the chute bottom is aligned with the hopper, by default it is.
Referenced by constructor(), readNextArgument(), and setIsHopperAlignedWithBottom().
isHopperCentred_
bool ChuteWithHopper::isHopperCentred_ private
If this flag is set, the hopper will be constructed in the xy-center of the domain, and not next to the xmin-domain boundary; by default off.
Referenced by addHopper(), constructor(), getIsHopperCentred(), readNextArgument(), setIsHopperCentred(), and setupInitialConditions().
The documentation for this class was generated from the following files:
ChuteWithHopper.h
ChuteWithHopper.cc