MercuryDPM: cxx11_tensor_move.cpp File Reference
cxx11_tensor_move.cpp File Reference
#include "main.h"
#include <Eigen/CXX11/Tensor>
#include <utility>
Functions
static void calc_indices (int i, int &x, int &y, int &z)
static void test_move ()
EIGEN_DECLARE_TEST (cxx11_tensor_move)
Function Documentation
calc_indices()
static void calc_indices (int i, int & x, int & y, int & z) static
{
   x = i / 4;
   y = (i % 4) / 2;
   z = i % 2;
 }
References i, plotDoE::x, and y.
Referenced by test_move().
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (cxx11_tensor_move)
 { CALL_SUBTEST(test_move()); }
References CALL_SUBTEST, and test_move().
test_move()
static void test_move () static
{
   int x;
   int y;
   int z;
   Tensor<int, 3> tensor1(2, 2, 2);
   Tensor<int, 3, RowMajor> tensor2(2, 2, 2);
   for (int i = 0; i < 8; i++) {
     calc_indices(i, x, y, z);
     tensor1(x, y, z) = i;
     tensor2(x, y, z) = 2 * i;
   }
   // Invokes the move constructor.
   Tensor<int, 3> moved_tensor1 = std::move(tensor1);
   Tensor<int, 3, RowMajor> moved_tensor2 = std::move(tensor2);
   VERIFY_IS_EQUAL(tensor1.size(), 0);
   VERIFY_IS_EQUAL(tensor2.size(), 0);
   for (int i = 0; i < 8; i++) {
     calc_indices(i, x, y, z);
     VERIFY_IS_EQUAL(moved_tensor1(x, y, z), i);
     VERIFY_IS_EQUAL(moved_tensor2(x, y, z), 2 * i);
   }
   Tensor<int, 3> moved_tensor3(2, 2, 2);
   Tensor<int, 3, RowMajor> moved_tensor4(2, 2, 2);
   moved_tensor3.setZero();
   moved_tensor4.setZero();
   // Invokes the move assignment operator.
   moved_tensor3 = std::move(moved_tensor1);
   moved_tensor4 = std::move(moved_tensor2);
   for (int i = 0; i < 8; i++) {
     calc_indices(i, x, y, z);
     VERIFY_IS_EQUAL(moved_tensor3(x, y, z), i);
     VERIFY_IS_EQUAL(moved_tensor4(x, y, z), 2 * i);
   }
 }
References calc_indices(), i, Eigen::TensorBase< Derived, AccessLevel >::setZero(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::size(), VERIFY_IS_EQUAL, plotDoE::x, and y.
Referenced by EIGEN_DECLARE_TEST().