MercuryDPM: SlidingFrictionUnitTest.cpp File Reference
SlidingFrictionUnitTest.cpp File Reference
#include "DPMBase.h"
#include <Species/LinearViscoelasticSlidingFrictionBondedSpecies.h>
#include <cassert>
Classes
class SlidingFrictionUnitTest
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     //Unit diameter
     Mdouble radius = 0.5;
     //Equilibrium overlap
     Mdouble overlap = 0.1*radius;
     //Collision time (determines time step)
     Mdouble tc = 50e-3;
     //rotation velocity
     Mdouble velocity = 1.0;
     SlidingFrictionUnitTest sf;
     sf.setGravity({0,0,0});
     sf.setTimeStep(0.02*tc);
     sf.setName("SlidingFrictionUnitTest");
     sf.setMin(-radius*Vec3D(2,2,2));
     sf.setMax( radius*Vec3D(2,2,2));
     sf.setDimension(3);
     sf.setTimeMax(2.0);
     sf.eneFile.setSaveCount(1);
     //Add species
     auto s = sf.speciesHandler.copyAndAddObject(LinearViscoelasticSlidingFrictionBondedSpecies());
     //Set unit density
     s->setDensity(1.0);
     //Make particles relatively soft and dissipative
     Mdouble mass = s->getMassFromRadius(radius);
     s->setCollisionTimeAndNormalAndTangentialRestitutionCoefficient(tc,0.5,1.0,mass);
     //Set a high friction, so sliding movement is mostly elastic
     s->setSlidingFrictionCoefficient(1e20);
     //10% overlap in equilibrium position
     s->setBondForceMax(overlap*s->getStiffness());
     // check that stiffness is not too small
     logger(INFO,"Stiffness k=%",s->getStiffness());
     //Add particles
     SphericalParticle p;
     p.setSpecies(s);
     p.setRadius(radius);
     p.setPosition({ radius-0.5*overlap,0,0});
     p.setVelocity(velocity*Vec3D(0,0,1));
     auto p0 = sf.particleHandler.copyAndAddObject(p);
     p.setPosition({-radius+0.5*overlap,0,0});
     p.setVelocity(velocity*Vec3D(0,0,-1));
     auto p1 = sf.particleHandler.copyAndAddObject(p);
     //Add bonded interaction
     auto i = dynamic_cast<LinearViscoelasticSlidingFrictionBondedSpecies::InteractionType*>(sf.interactionHandler.getInteraction(p0,p1,0));
     i->bond();
     i->setSlidingSpring({0,0,overlap});
     sf.solve();
     helpers::writeToFile("SlidingFrictionUnitTest.gnu","set size ratio -1; p 'SlidingFrictionUnitTest.ene' u 2:4 w lp");
 }
References BaseHandler< T >::copyAndAddObject(), e(), DPMBase::eneFile, InteractionHandler::getInteraction(), i, INFO, DPMBase::interactionHandler, logger, p, p0, p1, DPMBase::particleHandler, UniformPSDSelfTest::radius, s, DPMBase::setDimension(), DPMBase::setGravity(), DPMBase::setMax(), DPMBase::setMin(), DPMBase::setName(), File::setSaveCount(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), DPMBase::solve(), DPMBase::speciesHandler, Jeffery_Solution::velocity(), and helpers::writeToFile().