MercuryDPM: unstructured_adaptive_mesh_two_outer_boundaries_crossed.cc File Reference
unstructured_adaptive_mesh_two_outer_boundaries_crossed.cc File Reference
#include "generic.h"
#include "poisson.h"
#include "meshes/triangle_mesh.h"
Classes
class PoissonProblem< ELEMENT >
Micky mouse Poisson problem.
Namespaces
TanhSolnForPoisson
Namespace for exact solution for Poisson equation with "sharp step".
Functions
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, double &u)
Exact solution as a scalar.
void TanhSolnForPoisson::get_source (const Vector< double > &x, double &source)
Source function to make it an exact solution.
int main (int argc, char *argv[])
Demonstrate how to solve Poisson problem.
Function Documentation
main()
int main (int argc , char * argv[])
Demonstrate how to solve Poisson problem.
Trace file to document norm of solution
 {
  // initialise MPI
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::init(argc,argv);
 #endif
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Sample point container
  CommandLineArgs::specify_command_line_flag("--non_ref_bin");
  CommandLineArgs::specify_command_line_flag("--ref_bin");
 #ifdef OOMPH_HAS_CGAL
  CommandLineArgs::specify_command_line_flag("--cgal");
 #endif
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  const unsigned max_adapt = 3;
  // Only set one!
  unsigned count=0;
  if (CommandLineArgs::command_line_flag_has_been_set("--non_ref_bin"))
   {
    count++;
    MeshAsGeomObject_Helper::Default_sample_point_container_version=
     UseNonRefineableBinArray;
   }
  if (CommandLineArgs::command_line_flag_has_been_set("--ref_bin"))
   {
    count++;
    MeshAsGeomObject_Helper::Default_sample_point_container_version=
     UseRefineableBinArray;
   }
 #ifdef OOMPH_HAS_CGAL
  if (CommandLineArgs::command_line_flag_has_been_set("--cgal"))
   {
    count++;
    MeshAsGeomObject_Helper::Default_sample_point_container_version=
     UseCGALSamplePointContainer;
   }
 #endif
  if (count>1)
   {
    std::ostringstream error_message;
    error_message
     << "Can only choose one of --non_ref_bin, --ref_bin or --cgal!";
    throw OomphLibError(error_message.str(),
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
   }
  // Label for output
  DocInfo doc_info;
  // Output directory
  doc_info.set_directory("RESLT");
  // Do the problem with quadratic elements
  //---------------------------------------
  {
   cout << std::endl  << "Quadratic elements" << std::endl;
   cout <<               "===================" << std::endl << std::endl;
   //Set up the problem
   PoissonProblem<ProjectablePoissonElement<TPoissonElement<2,3> > >
    problem(&TanhSolnForPoisson::get_source);
   // Solve the problem
   problem.newton_solve(max_adapt);
   // Open trace file
   char trace_filename[100];
   sprintf(trace_filename,"%s/trace.dat",
           doc_info.directory().c_str());
   ofstream trace_file;
   trace_file.open(trace_filename);
   //Output solution
   problem.doc_solution(doc_info, trace_file);
   //Increment counter for solutions
   doc_info.number()++;
   // Close the trace file
   trace_file.close();
  }
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::finalize();
 #endif
 }
References oomph::CommandLineArgs::command_line_flag_has_been_set(), oomph::MeshAsGeomObject_Helper::Default_sample_point_container_version, oomph::DocInfo::directory(), oomph::CommandLineArgs::doc_specified_flags(), TanhSolnForPoisson::get_source(), oomph::DocInfo::number(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::CommandLineArgs::parse_and_assign(), problem, oomph::DocInfo::set_directory(), Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), oomph::UseNonRefineableBinArray, and oomph::UseRefineableBinArray.