MercuryDPM: Eigen::Transpose< MatrixType > Class Template Reference
Eigen::Transpose< MatrixType > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Expression of the transpose of a matrix.
#include <Transpose.h>
Public Types
typedef internal::ref_selector< MatrixType >::non_const_type MatrixTypeNested
typedef TransposeImpl< MatrixType, typename internal::traits< MatrixType >::StorageKind >::Base Base
typedef internal::remove_all_t< MatrixType > NestedExpression
Public Types inherited from Eigen::TransposeImpl< MatrixType, internal::traits< MatrixType >::StorageKind >
typedef internal::generic_xpr_base< Transpose< MatrixType > >::type Base
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Transpose (MatrixType &matrix)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const internal::remove_all_t< MatrixTypeNested > & nestedExpression () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE std::remove_reference_t< MatrixTypeNested > & nestedExpression ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void resize (Index nrows, Index ncols)
Protected Attributes
internal::ref_selector< MatrixType >::non_const_type m_matrix
Detailed Description
template<typename MatrixType>
class Eigen::Transpose< MatrixType >
Expression of the transpose of a matrix.
Template Parameters
MatrixType the type of the object of which we are taking the transpose
This class represents an expression of the transpose of a matrix. It is the return type of MatrixBase::transpose() and MatrixBase::adjoint() and most of the time this is the only way it is used.
See also
MatrixBase::transpose(), MatrixBase::adjoint()
Member Typedef Documentation
Base
template<typename MatrixType > typedef TransposeImpl<MatrixType, typename internal::traits<MatrixType>::StorageKind>::Base Eigen::Transpose< MatrixType >::Base
MatrixTypeNested
template<typename MatrixType > typedef internal::ref_selector<MatrixType>::non_const_type Eigen::Transpose< MatrixType >::MatrixTypeNested
NestedExpression
template<typename MatrixType > typedef internal::remove_all_t<MatrixType> Eigen::Transpose< MatrixType >::NestedExpression
Constructor & Destructor Documentation
Transpose()
template<typename MatrixType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::Transpose< MatrixType >::Transpose (MatrixType & matrix) inline explicit
 : m_matrix(matrix) {}
Member Function Documentation
cols()
template<typename MatrixType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index Eigen::Transpose< MatrixType >::cols () const inline
 { return m_matrix.rows(); }
References Eigen::Transpose< MatrixType >::m_matrix.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
nestedExpression() [1/2]
template<typename MatrixType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE std::remove_reference_t<MatrixTypeNested>& Eigen::Transpose< MatrixType >::nestedExpression () inline
Returns
the nested expression
{
     return m_matrix;
   }
References Eigen::Transpose< MatrixType >::m_matrix.
nestedExpression() [2/2]
template<typename MatrixType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const internal::remove_all_t<MatrixTypeNested>& Eigen::Transpose< MatrixType >::nestedExpression () const inline
Returns
the nested expression
{
     return m_matrix;
   }
References Eigen::Transpose< MatrixType >::m_matrix.
Referenced by Eigen::internal::generic_product_impl< Lhs, Transpose< Rhs >, MatrixShape, TranspositionsShape, ProductTag >::evalTo(), and Eigen::internal::generic_product_impl< Transpose< Lhs >, Rhs, TranspositionsShape, MatrixShape, ProductTag >::evalTo().
resize()
template<typename MatrixType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::Transpose< MatrixType >::resize (Index nrows, Index ncols) inline
 { m_matrix.resize(ncols, nrows); }
References Eigen::Transpose< MatrixType >::m_matrix.
rows()
template<typename MatrixType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index Eigen::Transpose< MatrixType >::rows () const inline
 { return m_matrix.cols(); }
References Eigen::Transpose< MatrixType >::m_matrix.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_matrix
template<typename MatrixType > internal::ref_selector<MatrixType>::non_const_type Eigen::Transpose< MatrixType >::m_matrix protected
Referenced by Eigen::Transpose< MatrixType >::cols(), Eigen::Transpose< MatrixType >::nestedExpression(), Eigen::Transpose< MatrixType >::resize(), and Eigen::Transpose< MatrixType >::rows().
The documentation for this class was generated from the following file:
Transpose.h