MercuryDPM: MyEllipse Class Reference
MyEllipse Class Reference
Public Member Functions
MyEllipse (const double &a, const double &b, const double &a_hat, const double &b_hat, const double &period, Time *time_pt)
virtual ~MyEllipse ()
Destructor: Empty.
void position (const Vector< double > &xi, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &xi, Vector< double > &r) const
MyEllipse (const double &a, const double &a_hat, const double &period, Time *time_pt)
virtual ~MyEllipse ()
Destructor: Empty.
void position (const Vector< double > &xi, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &xi, Vector< double > &r) const
MyEllipse (const double &a, const double &b)
Constructor: Pass half axes.
virtual ~MyEllipse ()
Destructor: Empty.
void position (const Vector< double > &xi, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &xi, Vector< double > &r) const
MyEllipse (const double &a, const double &b, const double &a_hat, const double &b_hat, const double &period, Time *time_pt)
virtual ~MyEllipse ()
Destructor: Empty.
void position (const Vector< double > &xi, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &xi, Vector< double > &r) const
MyEllipse (const double &a, const double &b, const double &a_hat, const double &b_hat, const double &period, Time *time_pt)
virtual ~MyEllipse ()
Destructor: Empty.
void position (const Vector< double > &xi, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &xi, Vector< double > &r) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual unsigned ngeom_data () const
virtual Data * geom_data_pt (const unsigned &j)
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Protected Attributes
double A
x-half axis
double B
y-half axis
double A_hat
Amplitude of variation in x-half axis.
double B_hat
Amplitude of variation in y-half axis.
double T
Period of oscillation.
Time * Time_pt
Pointer to time object.
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
Oscillating ellipse
\[ x = (a + \widehat{a} \sin(2\Pi t/T)) \cos(\xi) \]
\[ y = (b + \widehat{b} \sin(2\Pi t/T)) \sin(\xi) \]
Oscillating ellipse
\[ x = (A + \widehat{A} \cos(2\pi t/T)) \cos(\xi) \]
\[ y = \frac{\sin(\xi)}{A + \widehat{A} \cos(2\pi t/T)} \]
Note that cross-sectional area is conserved.
Ellipse
\[ x = a \cos(\xi) \]
\[ y = b \sin(\xi) \]
Constructor & Destructor Documentation
MyEllipse() [1/5]
MyEllipse::MyEllipse (const double & a, const double & b, const double & a_hat, const double & b_hat, const double & period, Time * time_pt) inline
Constructor: Pass half axes, amplitudes of their variation, period of oscillation and pointer to time object.
                                                 :
   GeomObject(1,2), A(a), B(b), A_hat(a_hat), B_hat(b_hat),
   T(period), Time_pt(time_pt) {}
~MyEllipse() [1/5]
virtual MyEllipse::~MyEllipse () inline virtual
Destructor: Empty.
 {}
MyEllipse() [2/5]
MyEllipse::MyEllipse (const double & a, const double & a_hat, const double & period, Time * time_pt) inline
Constructor: Pass initial x-half axis, amplitude of x-variation, period of oscillation and pointer to time object.
                                                 :
   GeomObject(1,2), A(a), A_hat(a_hat), T(period), Time_pt(time_pt) {}
~MyEllipse() [2/5]
virtual MyEllipse::~MyEllipse () inline virtual
Destructor: Empty.
 {}
MyEllipse() [3/5]
MyEllipse::MyEllipse (const double & a, const double & b) inline
Constructor: Pass half axes.
                                              :
   GeomObject(1,2), A(a), B(b) {}
~MyEllipse() [3/5]
virtual MyEllipse::~MyEllipse () inline virtual
Destructor: Empty.
 {}
MyEllipse() [4/5]
MyEllipse::MyEllipse (const double & a, const double & b, const double & a_hat, const double & b_hat, const double & period, Time * time_pt) inline
Constructor: Pass half axes, amplitudes of their variation, period of oscillation and pointer to time object.
                                                 :
   GeomObject(1,2), A(a), B(b), A_hat(a_hat), B_hat(b_hat),
   T(period), Time_pt(time_pt) {}
~MyEllipse() [4/5]
virtual MyEllipse::~MyEllipse () inline virtual
Destructor: Empty.
 {}
MyEllipse() [5/5]
MyEllipse::MyEllipse (const double & a, const double & b, const double & a_hat, const double & b_hat, const double & period, Time * time_pt) inline
Constructor: Pass half axes, amplitudes of their variation, period of oscillation and pointer to time object.
                                                 :
   GeomObject(1,2), A(a), B(b), A_hat(a_hat), B_hat(b_hat),
   T(period), Time_pt(time_pt) {}
~MyEllipse() [5/5]
virtual MyEllipse::~MyEllipse () inline virtual
Destructor: Empty.
 {}
Member Function Documentation
position() [1/10]
void MyEllipse::position (const unsigned & t, const Vector< double > & xi, Vector< double > & r) const inline virtual
Parametrised position on object: r(xi). Evaluated at previous time level. t=0: current time; t>0: previous time level.
Reimplemented from oomph::GeomObject.
   {
    // Get current time:
    double time=Time_pt->time(t);
    // Position vector
    r[0] = (A+A_hat*sin(2.0*MathematicalConstants::Pi*time/T))*cos(xi[0]);
    r[1] = (B+B_hat*sin(2.0*MathematicalConstants::Pi*time/T))*sin(xi[0]);
   } // end of position(...)
References Global_Physical_Variables::A_hat, cos(), BiharmonicTestFunctions2::Pi, UniformPSDSelfTest::r, sin(), plotPSD::t, oomph::Time::time(), and Flag_definition::Time_pt.
position() [2/10]
void MyEllipse::position (const unsigned & t, const Vector< double > & xi, Vector< double > & r) const inline virtual
Parametrised position on object: r(xi). Evaluated at previous time level. t=0: current time; t>0: previous time level.
Reimplemented from oomph::GeomObject.
   {
    // Get current time:
    double time=Time_pt->time(t);
    // Position vector
    double axis=A+A_hat*cos(2.0*MathematicalConstants::Pi*time/T);
    r[0] = axis*cos(xi[0]);
    r[1] = (1.0/axis)*sin(xi[0]);
   }
References Global_Physical_Variables::A_hat, cos(), BiharmonicTestFunctions2::Pi, UniformPSDSelfTest::r, sin(), plotPSD::t, oomph::Time::time(), and Flag_definition::Time_pt.
position() [3/10]
void MyEllipse::position (const unsigned & t, const Vector< double > & xi, Vector< double > & r) const inline virtual
Parametrised position on object: r(xi). Evaluated at previous time level. t=0: current time; t>0: previous time level.
Reimplemented from oomph::GeomObject.
   {
    // Call steady version
    position(xi,r);
   } // end of position(...)
References UniformPSDSelfTest::r.
position() [4/10]
void MyEllipse::position (const unsigned & t, const Vector< double > & xi, Vector< double > & r) const inline virtual
Parametrised position on object: r(xi). Evaluated at previous time level. t=0: current time; t>0: previous time level.
Reimplemented from oomph::GeomObject.
   {
    // Get current time:
    double time=Time_pt->time(t);
    // Position vector
    r[0] = (A+A_hat*sin(2.0*MathematicalConstants::Pi*time/T))*cos(xi[0]);
    r[1] = (B+B_hat*sin(2.0*MathematicalConstants::Pi*time/T))*sin(xi[0]);
   } // end of position(...)
References Global_Physical_Variables::A_hat, cos(), BiharmonicTestFunctions2::Pi, UniformPSDSelfTest::r, sin(), plotPSD::t, oomph::Time::time(), and Flag_definition::Time_pt.
position() [5/10]
void MyEllipse::position (const unsigned & t, const Vector< double > & xi, Vector< double > & r) const inline virtual
Parametrised position on object: r(xi). Evaluated at previous time level. t=0: current time; t>0: previous time level.
Reimplemented from oomph::GeomObject.
   {
    // Get current time:
    double time=Time_pt->time(t);
    // Position vector
    r[0] = (A+A_hat*sin(2.0*MathematicalConstants::Pi*time/T))*cos(xi[0]);
    r[1] = (B+B_hat*sin(2.0*MathematicalConstants::Pi*time/T))*sin(xi[0]);
   } // end of position(...)
References Global_Physical_Variables::A_hat, cos(), BiharmonicTestFunctions2::Pi, UniformPSDSelfTest::r, sin(), plotPSD::t, oomph::Time::time(), and Flag_definition::Time_pt.
position() [6/10]
void MyEllipse::position (const Vector< double > & xi, Vector< double > & r) const inline virtual
Current position vector to material point at Lagrangian coordinate xi
Implements oomph::GeomObject.
   {
    // Get current time:
    double time=Time_pt->time();
    // Position vector
    r[0] = (A+A_hat*sin(2.0*MathematicalConstants::Pi*time/T))*cos(xi[0]);
    r[1] = (B+B_hat*sin(2.0*MathematicalConstants::Pi*time/T))*sin(xi[0]);
   } // end of position(...)
References Global_Physical_Variables::A_hat, cos(), BiharmonicTestFunctions2::Pi, UniformPSDSelfTest::r, sin(), oomph::Time::time(), and Flag_definition::Time_pt.
position() [7/10]
void MyEllipse::position (const Vector< double > & xi, Vector< double > & r) const inline virtual
Current position vector to material point at Lagrangian coordinate xi
Implements oomph::GeomObject.
   {
    // Get current time:
    double time=Time_pt->time();
    // Position vector
    double axis=A+A_hat*cos(2.0*MathematicalConstants::Pi*time/T);
    r[0] = axis*cos(xi[0]);
    r[1] = (1.0/axis)*sin(xi[0]);
   }
References Global_Physical_Variables::A_hat, cos(), BiharmonicTestFunctions2::Pi, UniformPSDSelfTest::r, sin(), oomph::Time::time(), and Flag_definition::Time_pt.
position() [8/10]
void MyEllipse::position (const Vector< double > & xi, Vector< double > & r) const inline virtual
Current position vector to material point at Lagrangian coordinate xi
Implements oomph::GeomObject.
   {
    // Position vector
    r[0] = A*cos(xi[0]);
    r[1] = B*sin(xi[0]);
   } // end of position(...)
References cos(), UniformPSDSelfTest::r, and sin().
position() [9/10]
void MyEllipse::position (const Vector< double > & xi, Vector< double > & r) const inline virtual
Current position vector to material point at Lagrangian coordinate xi
Implements oomph::GeomObject.
   {
    // Get current time:
    double time=Time_pt->time();
    // Position vector
    r[0] = (A+A_hat*sin(2.0*MathematicalConstants::Pi*time/T))*cos(xi[0]);
    r[1] = (B+B_hat*sin(2.0*MathematicalConstants::Pi*time/T))*sin(xi[0]);
   } // end of position(...)
References Global_Physical_Variables::A_hat, cos(), BiharmonicTestFunctions2::Pi, UniformPSDSelfTest::r, sin(), oomph::Time::time(), and Flag_definition::Time_pt.
position() [10/10]
void MyEllipse::position (const Vector< double > & xi, Vector< double > & r) const inline virtual
Current position vector to material point at Lagrangian coordinate xi
Implements oomph::GeomObject.
   {
    // Get current time:
    double time=Time_pt->time();
    // Position vector
    r[0] = (A+A_hat*sin(2.0*MathematicalConstants::Pi*time/T))*cos(xi[0]);
    r[1] = (B+B_hat*sin(2.0*MathematicalConstants::Pi*time/T))*sin(xi[0]);
   } // end of position(...)
References Global_Physical_Variables::A_hat, cos(), BiharmonicTestFunctions2::Pi, UniformPSDSelfTest::r, sin(), oomph::Time::time(), and Flag_definition::Time_pt.
Member Data Documentation
A
double MyEllipse::A protected
x-half axis
A_hat
double MyEllipse::A_hat protected
Amplitude of variation in x-half axis.
B
double MyEllipse::B protected
y-half axis
B_hat
double MyEllipse::B_hat protected
Amplitude of variation in y-half axis.
T
double MyEllipse::T protected
Period of oscillation.
Time_pt
Time * MyEllipse::Time_pt protected
Pointer to time object.
The documentation for this class was generated from the following files:
two_d_unsteady_heat_2adapt_load_balance.cc
osc_quarter_ellipse.cc
ray_circ_cavity_adapt.cc
two_d_unsteady_heat_2adapt.cc
two_d_unsteady_heat_ALE.cc