MercuryDPM: Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ > Class Template Reference
Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Permutation matrix.
#include <PermutationMatrix.h>
Public Types
typedef const PermutationMatrix & Nested
typedef Traits::IndicesType IndicesType
typedef Traits::StorageIndex StorageIndex
Public Types inherited from Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ > >
enum
typedef Traits::IndicesType IndicesType
typedef Traits::StorageIndex StorageIndex
typedef Matrix< StorageIndex, RowsAtCompileTime, ColsAtCompileTime, 0, MaxRowsAtCompileTime, MaxColsAtCompileTime > DenseMatrixType
typedef PermutationMatrix< IndicesType::SizeAtCompileTime, IndicesType::MaxSizeAtCompileTime, StorageIndex > PlainPermutationType
typedef PlainPermutationType PlainObject
typedef Inverse< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ > > InverseReturnType
typedef void Scalar
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
PermutationMatrix ()
PermutationMatrix (Index size)
template<typename OtherDerived >
PermutationMatrix (const PermutationBase< OtherDerived > &other)
template<typename Other >
PermutationMatrix (const MatrixBase< Other > &indices)
template<typename Other >
PermutationMatrix (const TranspositionsBase< Other > &tr)
template<typename Other >
PermutationMatrix & operator= (const PermutationBase< Other > &other)
template<typename Other >
PermutationMatrix & operator= (const TranspositionsBase< Other > &tr)
const IndicesType & indices () const
IndicesType & indices ()
template<typename Other >
PermutationMatrix (const InverseImpl< Other, PermutationStorage > &other)
template<typename Lhs , typename Rhs >
PermutationMatrix (internal::PermPermProduct_t, const Lhs &lhs, const Rhs &rhs)
Public Member Functions inherited from Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ > >
PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ > & operator= (const PermutationBase< OtherDerived > &other)
PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ > & operator= (const TranspositionsBase< OtherDerived > &tr)
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index size () const
void evalTo (MatrixBase< DenseDerived > &other) const
DenseMatrixType toDenseMatrix () const
const IndicesType & indices () const
IndicesType & indices ()
void resize (Index newSize)
void setIdentity ()
void setIdentity (Index newSize)
PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ > & applyTranspositionOnTheLeft (Index i, Index j)
PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ > & applyTranspositionOnTheRight (Index i, Index j)
InverseReturnType inverse () const
InverseReturnType transpose () const
PlainPermutationType operator* (const PermutationBase< Other > &other) const
PlainPermutationType operator* (const InverseImpl< Other, PermutationStorage > &other) const
Index determinant () const
constexpr EIGEN_DEVICE_FUNC PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ > & derived ()
constexpr EIGEN_DEVICE_FUNC const PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ > & derived () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
constexpr EIGEN_DEVICE_FUNC Derived & derived ()
constexpr EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< Derived, Device > device (Device &device)
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const Derived, Device > device (Device &device) const
Protected Attributes
IndicesType m_indices
Private Types
typedef PermutationBase< PermutationMatrix > Base
typedef internal::traits< PermutationMatrix > Traits
Additional Inherited Members
Protected Member Functions inherited from Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ > >
void assignTranspose (const PermutationBase< OtherDerived > &other)
void assignProduct (const Lhs &lhs, const Rhs &rhs)
Detailed Description
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename StorageIndex_>
class Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >
Permutation matrix.
Template Parameters
SizeAtCompileTime the number of rows/cols, or Dynamic
MaxSizeAtCompileTime the maximum number of rows/cols, or Dynamic. This optional parameter defaults to SizeAtCompileTime. Most of the time, you should not have to specify it.
StorageIndex_ the integer type of the indices
This class represents a permutation matrix, internally stored as a vector of integers.
See also
class PermutationBase, class PermutationWrapper, class DiagonalMatrix
Member Typedef Documentation
Base
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename StorageIndex_ > typedef PermutationBase<PermutationMatrix> Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::Base private
IndicesType
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename StorageIndex_ > typedef Traits::IndicesType Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::IndicesType
Nested
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename StorageIndex_ > typedef const PermutationMatrix& Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::Nested
StorageIndex
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename StorageIndex_ > typedef Traits::StorageIndex Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::StorageIndex
Traits
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename StorageIndex_ > typedef internal::traits<PermutationMatrix> Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::Traits private
Constructor & Destructor Documentation
PermutationMatrix() [1/7]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename StorageIndex_ > Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::PermutationMatrix () inline
 {}
PermutationMatrix() [2/7]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename StorageIndex_ > Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::PermutationMatrix (Index size) inline explicit
Constructs an uninitialized permutation matrix of given size.
                                                 : m_indices(size) {
     eigen_internal_assert(size <= NumTraits<StorageIndex>::highest());
   }
References eigen_internal_assert, and Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ > >::size().
PermutationMatrix() [3/7]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename StorageIndex_ > template<typename OtherDerived > Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::PermutationMatrix (const PermutationBase< OtherDerived > & other) inline
Copy constructor.
 : m_indices(other.indices()) {}
PermutationMatrix() [4/7]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename StorageIndex_ > template<typename Other > Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::PermutationMatrix (const MatrixBase< Other > & indices) inline explicit
Generic constructor from expression of the indices. The indices array has the meaning that the permutations sends each integer i to indices[i].
Warning
It is your responsibility to check that the indices array that you passes actually describes a permutation, i.e., each value between 0 and n-1 occurs exactly once, where n is the array's size.
 : m_indices(indices) {}
PermutationMatrix() [5/7]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename StorageIndex_ > template<typename Other > Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::PermutationMatrix (const TranspositionsBase< Other > & tr) inline explicit
Convert the Transpositions tr to a permutation matrix
                                                                   : m_indices(tr.size()) {
     *this = tr;
   }
PermutationMatrix() [6/7]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename StorageIndex_ > template<typename Other > Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::PermutationMatrix (const InverseImpl< Other, PermutationStorage > & other) inline
       : m_indices(other.derived().nestedExpression().size()) {
     eigen_internal_assert(m_indices.size() <= NumTraits<StorageIndex>::highest());
     StorageIndex end = StorageIndex(m_indices.size());
     for (StorageIndex i = 0; i < end; ++i)
       m_indices.coeffRef(other.derived().nestedExpression().indices().coeff(i)) = i;
   }
References Eigen::InverseImpl< XprType, StorageKind >::coeff(), eigen_internal_assert, Eigen::placeholders::end, i, and Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::m_indices.
PermutationMatrix() [7/7]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename StorageIndex_ > template<typename Lhs , typename Rhs > Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::PermutationMatrix (internal::PermPermProduct_t , const Lhs & lhs, const Rhs & rhs) inline
                                                                                : m_indices(lhs.indices().size()) {
     Base::assignProduct(lhs, rhs);
   }
References Eigen::PermutationBase< Derived >::assignProduct().
Member Function Documentation
indices() [1/2]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename StorageIndex_ > IndicesType& Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::indices () inline
Returns
a reference to the stored array representing the permutation.
 { return m_indices; }
References Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::m_indices.
indices() [2/2]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename StorageIndex_ > const IndicesType& Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::indices () const inline
const version of indices().
 { return m_indices; }
References Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::m_indices.
Referenced by Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::_solve_impl_transposed(), Eigen::SparseLU< MatrixType_, OrderingType_ >::analyzePattern(), Eigen::SimplicialCholeskyBase< Derived >::factorize(), Eigen::SparseLU< MatrixType_, OrderingType_ >::factorize(), Eigen::internal::lmqrsolv(), Eigen::internal::minimum_degree_ordering(), Eigen::MetisOrdering< StorageIndex >::operator()(), Eigen::COLAMDOrdering< StorageIndex >::operator()(), Eigen::internal::Assignment< DstXprType, SparseSymmetricPermutationProduct< MatrixType, Mode >, internal::assign_op< Scalar, typename MatrixType::Scalar >, Sparse2Sparse >::run(), testLmder(), and testLmdif().
operator=() [1/2]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename StorageIndex_ > template<typename Other > PermutationMatrix& Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::operator= (const PermutationBase< Other > & other) inline
Copies the other permutation into *this
{
     m_indices = other.indices();
     return *this;
   }
References Eigen::PermutationBase< Derived >::indices(), and Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::m_indices.
operator=() [2/2]
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename StorageIndex_ > template<typename Other > PermutationMatrix& Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::operator= (const TranspositionsBase< Other > & tr) inline
Assignment from the Transpositions tr
{
     return Base::operator=(tr.derived());
   }
References Eigen::TranspositionsBase< Derived >::derived(), and Eigen::PermutationBase< Derived >::operator=().
Member Data Documentation
m_indices
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename StorageIndex_ > IndicesType Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::m_indices protected
Referenced by Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::indices(), Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::operator=(), and Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::PermutationMatrix().
The documentation for this class was generated from the following file:
PermutationMatrix.h