MercuryDPM: check_sqrt_impl< T > Struct Template Reference
check_sqrt_impl< T > Struct Template Reference
Static Public Member Functions
static void run ()
Member Function Documentation
run()
template<typename T > static void check_sqrt_impl< T >::run () inline static
                     {
     for (int i = 0; i < 1000; ++i) {
       const T x = numext::abs(internal::random<T>());
       const T sqrtx = numext::sqrt(x);
       VERIFY_IS_APPROX(sqrtx * sqrtx, x);
     }
     // Corner cases.
     const T zero = T(0);
     const T one = T(1);
     const T inf = std::numeric_limits<T>::infinity();
     const T nan = std::numeric_limits<T>::quiet_NaN();
     VERIFY_IS_EQUAL(numext::sqrt(zero), zero);
     VERIFY_IS_EQUAL(numext::sqrt(inf), inf);
     VERIFY((numext::isnan)(numext::sqrt(nan)));
     VERIFY((numext::isnan)(numext::sqrt(-one)));
   }
References abs(), i, constants::inf, isnan, sqrt(), VERIFY, VERIFY_IS_APPROX, VERIFY_IS_EQUAL, plotDoE::x, and zero().
Referenced by check_sqrt().
The documentation for this struct was generated from the following file:
numext.cpp