MercuryDPM: GeneralEllipse Class Reference
GeneralEllipse Class Reference
My own Ellipse class.
Public Member Functions
GeneralEllipse (const double &centre_x, const double &centre_y, const double &a, const double &b)
Constructor.
~GeneralEllipse ()
Destructor (empty)
void position (const Vector< double > &xi, Vector< double > &r) const
Return the position.
double & centre_x ()
Access to x-coordinate of centre.
double & centre_y ()
Access to y-coordinate of centre.
double & a ()
Access to x-half axis.
double & b ()
Access to y-half axis.
GeneralEllipse (const double &centre_x, const double &centre_y, const double &a, const double &b)
Constructor.
~GeneralEllipse ()
Destructor (empty)
void position (const Vector< double > &xi, Vector< double > &r) const
Return the position.
double & centre_x ()
Access to x-coordinate of centre.
double & centre_y ()
Access to y-coordinate of centre.
double & a ()
Access to x-half axis.
double & b ()
Access to y-half axis.
GeneralEllipse (const double &centre_x, const double &centre_y, const double &a, const double &b)
~GeneralEllipse ()
void position (const Vector< double > &xi, Vector< double > &r) const
Parametrised position on object at current time: r(zeta).
GeneralEllipse (const double &centre_x, const double &centre_y, const double &a, const double &b)
Constructor.
~GeneralEllipse ()
Destructor (empty)
void position (const Vector< double > &xi, Vector< double > &r) const
Return the position.
double & centre_x ()
Access to x-coordinate of centre.
double & centre_y ()
Access to y-coordinate of centre.
double & a ()
Access to x-half axis.
double & b ()
Access to y-half axis.
GeneralEllipse (const double &centre_x, const double &centre_y, const double &a, const double &b)
~GeneralEllipse ()
Empty Destructor.
void position (const Vector< double > &xi, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &xi, Vector< double > &r) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual unsigned ngeom_data () const
virtual Data * geom_data_pt (const unsigned &j)
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Private Attributes
double Centre_x
x-coordinate of centre
double Centre_y
y-coordinate of centre
double A
x-half axis
double B
y-half axis
double * centre_x_pt
double * centre_y_pt
double * a_pt
double * b_pt
Additional Inherited Members
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
My own Ellipse class.
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////// //////////////////////////////////////////////////////// //////////////////////////////////////////////////////// A geometric object for an ellipse with initial centre of mass at (centre_x, centre_y) with axis in the x direction given by 2a and in the y-direction given by 2b. The boundary of the ellipse is parametrised by its angle.
Constructor & Destructor Documentation
GeneralEllipse() [1/5]
GeneralEllipse::GeneralEllipse (const double & centre_x, const double & centre_y, const double & a, const double & b) inline
Constructor.
   : GeomObject(1,2), Centre_x(centre_x), Centre_y(centre_y), A(a), B(b)
   {}
~GeneralEllipse() [1/5]
GeneralEllipse::~GeneralEllipse () inline
Destructor (empty)
 {}
GeneralEllipse() [2/5]
GeneralEllipse::GeneralEllipse (const double & centre_x, const double & centre_y, const double & a, const double & b) inline
Constructor.
   : GeomObject(1,2), Centre_x(centre_x), Centre_y(centre_y), A(a), B(b)
   {}
~GeneralEllipse() [2/5]
GeneralEllipse::~GeneralEllipse () inline
Destructor (empty)
 {}
GeneralEllipse() [3/5]
GeneralEllipse::GeneralEllipse (const double & centre_x, const double & centre_y, const double & a, const double & b) inline
   : GeomObject(1,2), centre_x_pt(0), centre_y_pt(0), a_pt(0), b_pt(0)
   {
    centre_x_pt = new double(centre_x);
    centre_y_pt = new double(centre_y);
    a_pt = new double(a);
    b_pt = new double(b);
   }
References a, and b.
~GeneralEllipse() [3/5]
GeneralEllipse::~GeneralEllipse () inline
   {
    delete centre_x_pt;
    delete centre_y_pt;
    delete a_pt;
    delete b_pt;
   }
GeneralEllipse() [4/5]
GeneralEllipse::GeneralEllipse (const double & centre_x, const double & centre_y, const double & a, const double & b) inline
Constructor.
   : GeomObject(1,2), Centre_x(centre_x), Centre_y(centre_y), A(a), B(b)
   {}
~GeneralEllipse() [4/5]
GeneralEllipse::~GeneralEllipse () inline
Destructor (empty)
 {}
GeneralEllipse() [5/5]
GeneralEllipse::GeneralEllipse (const double & centre_x, const double & centre_y, const double & a, const double & b) inline
Simple Constructor that transfers appropriate geometric parameters into internal data
   : GeomObject(1,2), Centre_x(centre_x), Centre_y(centre_y), A(a), B(b)
   {}
~GeneralEllipse() [5/5]
GeneralEllipse::~GeneralEllipse () inline
Empty Destructor.
 {}
Member Function Documentation
a() [1/3]
double& GeneralEllipse::a () inline
Access to x-half axis.
 {return A;}
a() [2/3]
double& GeneralEllipse::a () inline
Access to x-half axis.
 {return A;}
a() [3/3]
double& GeneralEllipse::a () inline
Access to x-half axis.
 {return A;}
b() [1/3]
double& GeneralEllipse::b () inline
Access to y-half axis.
 {return B;}
References Global_Parameters::B.
b() [2/3]
double& GeneralEllipse::b () inline
Access to y-half axis.
 {return B;}
b() [3/3]
double& GeneralEllipse::b () inline
Access to y-half axis.
 {return B;}
centre_x() [1/3]
double& GeneralEllipse::centre_x () inline
Access to x-coordinate of centre.
 {return Centre_x;}
References Global_Parameters::Centre_x.
centre_x() [2/3]
double& GeneralEllipse::centre_x () inline
Access to x-coordinate of centre.
 {return Centre_x;}
References Global_Parameters::Centre_x.
centre_x() [3/3]
double& GeneralEllipse::centre_x () inline
Access to x-coordinate of centre.
 {return Centre_x;}
References Global_Parameters::Centre_x.
centre_y() [1/3]
double& GeneralEllipse::centre_y () inline
Access to y-coordinate of centre.
 {return Centre_y;}
References Global_Parameters::Centre_y.
centre_y() [2/3]
double& GeneralEllipse::centre_y () inline
Access to y-coordinate of centre.
 {return Centre_y;}
References Global_Parameters::Centre_y.
centre_y() [3/3]
double& GeneralEllipse::centre_y () inline
Access to y-coordinate of centre.
 {return Centre_y;}
References Global_Parameters::Centre_y.
position() [1/6]
void GeneralEllipse::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Works for t=0 but needs to be overloaded if genuine time-dependence is required.
Reimplemented from oomph::GeomObject.
   {
    return position(xi,r);
   }
References UniformPSDSelfTest::r.
position() [2/6]
void GeneralEllipse::position (const Vector< double > & xi, Vector< double > & r) const inline virtual
Return the position.
Implements oomph::GeomObject.
   {
    r[0] = Centre_x + A*cos(xi[0]);
    r[1] = Centre_y + B*sin(xi[0]);
   }
References Global_Parameters::Centre_x, Global_Parameters::Centre_y, cos(), UniformPSDSelfTest::r, and sin().
position() [3/6]
void GeneralEllipse::position (const Vector< double > & xi, Vector< double > & r) const inline virtual
Return the position.
Implements oomph::GeomObject.
   {
    r[0] = Centre_x + A*cos(xi[0]);
    r[1] = Centre_y + B*sin(xi[0]);
   }
References Global_Parameters::Centre_x, Global_Parameters::Centre_y, cos(), UniformPSDSelfTest::r, and sin().
position() [4/6]
void GeneralEllipse::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object at current time: r(zeta).
Implements oomph::GeomObject.
   {
    r[0] = *centre_x_pt + *a_pt*cos(xi[0]);
    r[1] = *centre_y_pt + *b_pt*sin(xi[0]);
   }
References cos(), UniformPSDSelfTest::r, and sin().
position() [5/6]
void GeneralEllipse::position (const Vector< double > & xi, Vector< double > & r) const inline virtual
Return the position.
Implements oomph::GeomObject.
   {
    r[0] = Centre_x + A*cos(xi[0]);
    r[1] = Centre_y + B*sin(xi[0]);
   }
References Global_Parameters::Centre_x, Global_Parameters::Centre_y, cos(), UniformPSDSelfTest::r, and sin().
position() [6/6]
void GeneralEllipse::position (const Vector< double > & xi, Vector< double > & r) const inline virtual
Return the position of the ellipse boundary as a function of the angle xi[0]
Implements oomph::GeomObject.
   {
    r[0] = Centre_x + A*cos(xi[0]);
    r[1] = Centre_y + B*sin(xi[0]);
   }
References Global_Parameters::Centre_x, Global_Parameters::Centre_y, cos(), UniformPSDSelfTest::r, and sin().
Member Data Documentation
A
double GeneralEllipse::A private
x-half axis
a_pt
double * GeneralEllipse::a_pt private
B
double GeneralEllipse::B private
y-half axis
b_pt
double * GeneralEllipse::b_pt private
Centre_x
double GeneralEllipse::Centre_x private
x-coordinate of centre
centre_x_pt
double* GeneralEllipse::centre_x_pt private
Centre_y
double GeneralEllipse::Centre_y private
y-coordinate of centre
centre_y_pt
double * GeneralEllipse::centre_y_pt private
The documentation for this class was generated from the following files:
adaptive_hopf.cc
adaptive_hopf_with_separate_meshes.cc
adaptive_interface.cc
flow_past_cylinder.cc
jeffery_orbit.cc