MercuryDPM: unstructured_time_harmonic_elastic_annulus.cc File Reference
unstructured_time_harmonic_elastic_annulus.cc File Reference
#include "generic.h"
#include "time_harmonic_linear_elasticity.h"
#include "meshes/triangle_mesh.h"
Classes
class MyStraightLine
Straight 1D line in 2D space.
class RingWithTRibProblem< ELASTICITY_ELEMENT >
Annular disk.
Namespaces
Global_Parameters
Namespace for global parameters.
Functions
void Global_Parameters::pressure_load (const Vector< double > &x, const Vector< double > &n, Vector< std::complex< double > > &traction)
Pressure load (real and imag part)
int main (int argc, char **argv)
Driver for annular disk loaded by pressure.
Variables
Vector< double > Global_Parameters::Omega_sq_region (2, Omega_sq)
Square of non-dim frequency for the two regions.
Function Documentation
main()
int main (int argc , char ** argv)
Driver for annular disk loaded by pressure.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
 #ifdef ADAPTIVE
  // Max. number of adaptations
  unsigned max_adapt=3;
  CommandLineArgs::specify_command_line_flag("--max_adapt",&max_adapt);
 #endif
  // Peakiness parameter for loading
  CommandLineArgs::specify_command_line_flag("--alpha",
                                             &Global_Parameters::Alpha);
  // Validation run?
  CommandLineArgs::specify_command_line_flag("--validation");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
 #ifdef ADAPTIVE
  //Set up the problem
  RingWithTRibProblem<ProjectableTimeHarmonicLinearElasticityElement
                     <TTimeHarmonicLinearElasticityElement<2,3> > >
   problem;
 #else
  //Set up the problem
  RingWithTRibProblem<TTimeHarmonicLinearElasticityElement<2,3> > problem;
 #endif
  // Initial values for parameter values
  Global_Parameters::P=0.1;
  //Parameter incrementation
  unsigned nstep=2;
  for(unsigned i=0;i<nstep;i++)
   {
 #ifdef ADAPTIVE
    // Solve the problem with Newton's method, allowing
    // up to max_adapt mesh adaptations after every solve.
    problem.newton_solve(max_adapt);
 #else
    // Solve the problem using Newton's method
    problem.newton_solve();
 #endif
    // Doc solution
    problem.doc_solution();
    // Now reduce the stiffness of the rib and set its inertia to
    // zero, then re-solve. Resulting displacement field should
    // be approximately axisymmetric in the annular region.
    Global_Parameters::E_pt[1]->update_constitutive_parameters(
     Global_Parameters::Nu,1.0e-10);
    Global_Parameters::Omega_sq_region[1]=0.0;
   }
 } //end of main
References Global_Parameters::Alpha, oomph::CommandLineArgs::doc_specified_flags(), Global_Parameters::E_pt, i, Global_Parameters::Nu, Global_Parameters::Omega_sq_region, Global_Parameters::P, oomph::CommandLineArgs::parse_and_assign(), problem, Flag_definition::setup(), and oomph::CommandLineArgs::specify_command_line_flag().