MercuryDPM: oomph::PiecewiseGauss< DIM, NPTS_1D > Class Template Reference
oomph::PiecewiseGauss< DIM, NPTS_1D > Class Template Reference
#include <contact_elements.h>
Public Member Functions
PiecewiseGauss (const double &lower, const double &upper)
PiecewiseGauss (const PiecewiseGauss &dummy)
Broken copy constructor.
virtual unsigned nweight () const
Return the number of integration points of the scheme.
double knot (const unsigned &i, const unsigned &j) const
Return the rescaled knot values s[j] at integration point i.
double weight (const unsigned &i) const
Return the rescaled weight at integration point i.
Private Attributes
double Lower
Store for the lower and upper limits of integration and the range.
double Upper
double Range
Detailed Description
template<unsigned DIM, unsigned NPTS_1D>
class oomph::PiecewiseGauss< DIM, NPTS_1D >
Piecewise Gauss integration rule. Uses Gauss rules of specified order in three sub-intervals of element.
Constructor & Destructor Documentation
PiecewiseGauss() [1/2]
template<unsigned DIM, unsigned NPTS_1D> oomph::PiecewiseGauss< DIM, NPTS_1D >::PiecewiseGauss (const double & lower, const double & upper) inline
Constructor: Pass in lower and upper limits of 1D coordinate over which we're integrating
                                                             :
    Lower(lower), Upper(upper)
     {
      //Set the range of integration
      Range = upper - lower;
     }
References helpers::lower(), and oomph::PiecewiseGauss< DIM, NPTS_1D >::Range.
PiecewiseGauss() [2/2]
template<unsigned DIM, unsigned NPTS_1D> oomph::PiecewiseGauss< DIM, NPTS_1D >::PiecewiseGauss (const PiecewiseGauss< DIM, NPTS_1D > & dummy) inline
Broken copy constructor.
     {
      BrokenCopy::broken_copy("PiecewiseGauss");
     }
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
knot()
template<unsigned DIM, unsigned NPTS_1D> double oomph::PiecewiseGauss< DIM, NPTS_1D >::knot (const unsigned & i, const unsigned & j) const inline
Return the rescaled knot values s[j] at integration point i.
    {
     if (i<Gauss<DIM,NPTS_1D>::nweight())
      {
       double range=0.25*Range;
       double lower=Lower+0.0;
       //double upper=Lower+0.25*Range;
       unsigned ii=i;
       return (lower+(0.5*(1.0+Gauss<DIM,NPTS_1D>::knot(ii,j))*range));
      }
     else if (i<2*Gauss<DIM,NPTS_1D>::nweight())
      {
       double range=0.5*Range;
       double lower=Lower+0.25*Range;
       //double upper=Lower+0.75*Range;
       unsigned ii=i-Gauss<DIM,NPTS_1D>::nweight();
       return (lower+(0.5*(1.0+Gauss<DIM,NPTS_1D>::knot(ii,j))*range));
      }
     else
      {
       double range=0.25*Range;
       double lower=Lower+0.75*Range;
       //double upper=Upper;
       unsigned ii=i-2*Gauss<DIM,NPTS_1D>::nweight();
       return (lower+(0.5*(1.0+Gauss<DIM,NPTS_1D>::knot(ii,j))*range));
      }
    }
References i, j, helpers::lower(), oomph::PiecewiseGauss< DIM, NPTS_1D >::Lower, and oomph::PiecewiseGauss< DIM, NPTS_1D >::Range.
nweight()
template<unsigned DIM, unsigned NPTS_1D> virtual unsigned oomph::PiecewiseGauss< DIM, NPTS_1D >::nweight () const inline virtual
Return the number of integration points of the scheme.
    {
     return 3*Gauss<DIM,NPTS_1D>::nweight();
    }
weight()
template<unsigned DIM, unsigned NPTS_1D> double oomph::PiecewiseGauss< DIM, NPTS_1D >::weight (const unsigned & i) const inline
Return the rescaled weight at integration point i.
    {
     if (i<Gauss<DIM,NPTS_1D>::nweight())
       {
        double range=0.25*Range;
        unsigned ii=i;
        return Gauss<DIM,NPTS_1D>::weight(ii)*
         pow(0.5*range,static_cast<int>(DIM));
       }
     else if (i<2*Gauss<DIM,NPTS_1D>::nweight())
      {
       double range=0.5*Range;
       unsigned ii=i-Gauss<DIM,NPTS_1D>::nweight();
       return Gauss<DIM,NPTS_1D>::weight(ii)*
        pow(0.5*range,static_cast<int>(DIM));
      }
     else
      {
       double range=0.25*Range;
       unsigned ii=i-2*Gauss<DIM,NPTS_1D>::nweight();
       return Gauss<DIM,NPTS_1D>::weight(ii)*
        pow(0.5*range,static_cast<int>(DIM));
      }
    }
References DIM, i, Eigen::bfloat16_impl::pow(), and oomph::PiecewiseGauss< DIM, NPTS_1D >::Range.
Member Data Documentation
Lower
template<unsigned DIM, unsigned NPTS_1D> double oomph::PiecewiseGauss< DIM, NPTS_1D >::Lower private
Store for the lower and upper limits of integration and the range.
Referenced by oomph::PiecewiseGauss< DIM, NPTS_1D >::knot().
Range
template<unsigned DIM, unsigned NPTS_1D> double oomph::PiecewiseGauss< DIM, NPTS_1D >::Range private
Referenced by oomph::PiecewiseGauss< DIM, NPTS_1D >::knot(), oomph::PiecewiseGauss< DIM, NPTS_1D >::PiecewiseGauss(), and oomph::PiecewiseGauss< DIM, NPTS_1D >::weight().
Upper
template<unsigned DIM, unsigned NPTS_1D> double oomph::PiecewiseGauss< DIM, NPTS_1D >::Upper private
The documentation for this class was generated from the following file:
contact_elements.h