MercuryDPM: cxx11_tensor_scan_sycl.cpp File Reference
cxx11_tensor_scan_sycl.cpp File Reference
#include "main.h"
#include <unsupported/Eigen/CXX11/Tensor>
Macros
#define EIGEN_TEST_NO_LONGDOUBLE
#define EIGEN_TEST_NO_COMPLEX
#define EIGEN_DEFAULT_DENSE_INDEX_TYPE int64_t
#define EIGEN_USE_SYCL
Typedefs
typedef Tensor< float, 1 >::DimensionPair DimPair
Functions
template<typename DataType , int DataLayout, typename IndexType >
void test_sycl_cumsum (const Eigen::SyclDevice &sycl_device, IndexType m_size, IndexType k_size, IndexType n_size, int consume_dim, bool exclusive)
template<typename DataType , typename Dev >
void sycl_scan_test_exclusive_dim0_per_device (const Dev &sycl_device)
template<typename DataType , typename Dev >
void sycl_scan_test_exclusive_dim1_per_device (const Dev &sycl_device)
template<typename DataType , typename Dev >
void sycl_scan_test_exclusive_dim2_per_device (const Dev &sycl_device)
template<typename DataType , typename Dev >
void sycl_scan_test_inclusive_dim0_per_device (const Dev &sycl_device)
template<typename DataType , typename Dev >
void sycl_scan_test_inclusive_dim1_per_device (const Dev &sycl_device)
template<typename DataType , typename Dev >
void sycl_scan_test_inclusive_dim2_per_device (const Dev &sycl_device)
EIGEN_DECLARE_TEST (cxx11_tensor_scan_sycl)
Macro Definition Documentation
EIGEN_DEFAULT_DENSE_INDEX_TYPE
#define EIGEN_DEFAULT_DENSE_INDEX_TYPE int64_t
EIGEN_TEST_NO_COMPLEX
#define EIGEN_TEST_NO_COMPLEX
EIGEN_TEST_NO_LONGDOUBLE
#define EIGEN_TEST_NO_LONGDOUBLE
EIGEN_USE_SYCL
#define EIGEN_USE_SYCL
Typedef Documentation
DimPair
typedef Tensor<float, 1>::DimensionPair DimPair
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (cxx11_tensor_scan_sycl)
{
   for (const auto& device : Eigen::get_sycl_supported_devices()) {
     std::cout << "Running on " << device.template get_info<cl::sycl::info::device::name>() << std::endl;
     QueueInterface queueInterface(device);
     auto sycl_device = Eigen::SyclDevice(&queueInterface);
     CALL_SUBTEST_1(sycl_scan_test_exclusive_dim0_per_device<float>(sycl_device));
     CALL_SUBTEST_2(sycl_scan_test_exclusive_dim1_per_device<float>(sycl_device));
     CALL_SUBTEST_3(sycl_scan_test_exclusive_dim2_per_device<float>(sycl_device));
     CALL_SUBTEST_4(sycl_scan_test_inclusive_dim0_per_device<float>(sycl_device));
     CALL_SUBTEST_5(sycl_scan_test_inclusive_dim1_per_device<float>(sycl_device));
     CALL_SUBTEST_6(sycl_scan_test_inclusive_dim2_per_device<float>(sycl_device));
   }
 }
References CALL_SUBTEST_1, CALL_SUBTEST_2, CALL_SUBTEST_3, CALL_SUBTEST_4, CALL_SUBTEST_5, and CALL_SUBTEST_6.
sycl_scan_test_exclusive_dim0_per_device()
template<typename DataType , typename Dev > void sycl_scan_test_exclusive_dim0_per_device (const Dev & sycl_device)
{
   test_sycl_cumsum<DataType, ColMajor, int64_t>(sycl_device, 2049, 1023, 127, 0, true);
   test_sycl_cumsum<DataType, RowMajor, int64_t>(sycl_device, 2049, 1023, 127, 0, true);
 }
sycl_scan_test_exclusive_dim1_per_device()
template<typename DataType , typename Dev > void sycl_scan_test_exclusive_dim1_per_device (const Dev & sycl_device)
{
   test_sycl_cumsum<DataType, ColMajor, int64_t>(sycl_device, 1023, 2049, 127, 1, true);
   test_sycl_cumsum<DataType, RowMajor, int64_t>(sycl_device, 1023, 2049, 127, 1, true);
 }
sycl_scan_test_exclusive_dim2_per_device()
template<typename DataType , typename Dev > void sycl_scan_test_exclusive_dim2_per_device (const Dev & sycl_device)
{
   test_sycl_cumsum<DataType, ColMajor, int64_t>(sycl_device, 1023, 127, 2049, 2, true);
   test_sycl_cumsum<DataType, RowMajor, int64_t>(sycl_device, 1023, 127, 2049, 2, true);
 }
sycl_scan_test_inclusive_dim0_per_device()
template<typename DataType , typename Dev > void sycl_scan_test_inclusive_dim0_per_device (const Dev & sycl_device)
{
   test_sycl_cumsum<DataType, ColMajor, int64_t>(sycl_device, 2049, 1023, 127, 0, false);
   test_sycl_cumsum<DataType, RowMajor, int64_t>(sycl_device, 2049, 1023, 127, 0, false);
 }
sycl_scan_test_inclusive_dim1_per_device()
template<typename DataType , typename Dev > void sycl_scan_test_inclusive_dim1_per_device (const Dev & sycl_device)
{
   test_sycl_cumsum<DataType, ColMajor, int64_t>(sycl_device, 1023, 2049, 127, 1, false);
   test_sycl_cumsum<DataType, RowMajor, int64_t>(sycl_device, 1023, 2049, 127, 1, false);
 }
sycl_scan_test_inclusive_dim2_per_device()
template<typename DataType , typename Dev > void sycl_scan_test_inclusive_dim2_per_device (const Dev & sycl_device)
{
   test_sycl_cumsum<DataType, ColMajor, int64_t>(sycl_device, 1023, 127, 2049, 2, false);
   test_sycl_cumsum<DataType, RowMajor, int64_t>(sycl_device, 1023, 127, 2049, 2, false);
 }
test_sycl_cumsum()
template<typename DataType , int DataLayout, typename IndexType > void test_sycl_cumsum (const Eigen::SyclDevice & sycl_device, IndexType m_size, IndexType k_size, IndexType n_size, int consume_dim, bool exclusive)
{
   static const DataType error_threshold = 1e-4f;
   std::cout << "Testing for (" << m_size << "," << k_size << "," << n_size << " consume_dim : " << consume_dim << ")"
             << std::endl;
   Tensor<DataType, 3, DataLayout, IndexType> t_input(m_size, k_size, n_size);
   Tensor<DataType, 3, DataLayout, IndexType> t_result(m_size, k_size, n_size);
   Tensor<DataType, 3, DataLayout, IndexType> t_result_gpu(m_size, k_size, n_size);
   t_input.setRandom();
   std::size_t t_input_bytes = t_input.size() * sizeof(DataType);
   std::size_t t_result_bytes = t_result.size() * sizeof(DataType);
   DataType* gpu_data_in = static_cast<DataType*>(sycl_device.allocate(t_input_bytes));
   DataType* gpu_data_out = static_cast<DataType*>(sycl_device.allocate(t_result_bytes));
   array<IndexType, 3> tensorRange = {{m_size, k_size, n_size}};
   TensorMap<Tensor<DataType, 3, DataLayout, IndexType>> gpu_t_input(gpu_data_in, tensorRange);
   TensorMap<Tensor<DataType, 3, DataLayout, IndexType>> gpu_t_result(gpu_data_out, tensorRange);
   sycl_device.memcpyHostToDevice(gpu_data_in, t_input.data(), t_input_bytes);
   sycl_device.memcpyHostToDevice(gpu_data_out, t_input.data(), t_input_bytes);
   gpu_t_result.device(sycl_device) = gpu_t_input.cumsum(consume_dim, exclusive);
   t_result = t_input.cumsum(consume_dim, exclusive);
   sycl_device.memcpyDeviceToHost(t_result_gpu.data(), gpu_data_out, t_result_bytes);
   sycl_device.synchronize();
   for (IndexType i = 0; i < t_result.size(); i++) {
     if (static_cast<DataType>(std::fabs(static_cast<DataType>(t_result(i) - t_result_gpu(i)))) < error_threshold) {
       continue;
     }
     if (Eigen::internal::isApprox(t_result(i), t_result_gpu(i), error_threshold)) {
       continue;
     }
     std::cout << "mismatch detected at index " << i << " CPU : " << t_result(i) << " vs SYCL : " << t_result_gpu(i)
               << std::endl;
     assert(false);
   }
   sycl_device.deallocate(gpu_data_in);
   sycl_device.deallocate(gpu_data_out);
 }
References assert, Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::data(), Eigen::TensorBase< Derived, AccessLevel >::device(), error_threshold, boost::multiprecision::fabs(), i, Eigen::internal::isApprox(), Eigen::TensorBase< Derived, AccessLevel >::setRandom(), and Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::size().