MercuryDPM: TwoParticleElasticCollisionSelfTest.cpp File Reference
TwoParticleElasticCollisionSelfTest.cpp File Reference
#include "Mercury2D.h"
#include "Walls/InfiniteWall.h"
#include "Species/Species.h"
#include "Species/LinearViscoelasticSpecies.h"
Classes
class TwoParticleElasticCollision
In this file two particles are symmetrically placed in a bi-axial box are allowed to jump around under gravity. It tests walls gravity and symmetry.
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     TwoParticleElasticCollision twoParticleElasticCollisionProblem;
     twoParticleElasticCollisionProblem.setName("TwoParticleElasticCollisionSelfTest");
     LinearViscoelasticSpecies species;
     species.setDensity(2000);
     species.setStiffness(1e4);
     twoParticleElasticCollisionProblem.speciesHandler.copyAndAddObject(species);
     twoParticleElasticCollisionProblem.setTimeMax(0.25);
     twoParticleElasticCollisionProblem.setSaveCount(10);
     twoParticleElasticCollisionProblem.setTimeStep(2e-5);
     twoParticleElasticCollisionProblem.fStatFile.setFileType(FileType::NO_FILE);
     twoParticleElasticCollisionProblem.solve();
 }
References BaseHandler< T >::copyAndAddObject(), e(), DPMBase::fStatFile, NO_FILE, ParticleSpecies::setDensity(), File::setFileType(), DPMBase::setName(), DPMBase::setSaveCount(), LinearViscoelasticNormalSpecies::setStiffness(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), DPMBase::solve(), and DPMBase::speciesHandler.