MercuryDPM: ParticleSpecies Class Reference
ParticleSpecies Class Reference abstract
#include <ParticleSpecies.h>
Public Types
typedef BaseInteraction InteractionType
typedef BaseSpecies MixedSpeciesType
Public Member Functions
ParticleSpecies ()
The default constructor.
ParticleSpecies (const ParticleSpecies &p)
The default copy constructor.
ParticleSpecies (BaseNormalForce *normalForce, BaseFrictionForce *frictionForce, BaseAdhesiveForce *adhesiveForce)
~ParticleSpecies ()
The default destructor.
ParticleSpecies * copy () const override=0
Creates a deep copy of the object from which it is called.
virtual BaseSpecies * copyMixed () const =0
Creates a new MixedSpecies with the same force properties as the Species from which it is called. See Species::copyMixed for details.
void read (std::istream &is) override
Reads the species properties from an input stream.
void write (std::ostream &os) const override
Writes the species properties to an output stream.
std::string getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
void setDensity (Mdouble density)
Mdouble getMassFromRadius (Mdouble radius) const
Mdouble getMassFromRadius (const Mdouble radius, SpeciesHandler &speciesHandler)
Mdouble getVolumeFromRadius (Mdouble radius) const
Mdouble getDensity () const
Allows density_ to be accessed.
void computeMass (BaseParticle *p) const
Compute Particle mass function, which required a reference to the Species vector. It computes the Particles mass, Inertia and the inverses.
void setTemperatureDependentDensity (const std::function< double(double)> &temperatureDependentDensity)
const std::function< double(double)> & getTemperatureDependentDensity () const
Mdouble getSmallestParticleMass () const
Computes mass of the lightest particle (by mass) belonging to this species. This computation calls getLightestInverseParticleMassLocal, such that the computation is done on each node.
Mdouble getMaxInteractionDistance () const
returns the largest separation distance at which adhesive short-range forces can occur.
void setMaxInteractionDistance (Mdouble interactionDistance=0)
Sets maxInteractionDistance_.
const BaseSpecies * getMixedSpecies (const ParticleSpecies *s) const
virtual void actionsAfterTimeStep (BaseParticle *particle) const
Public Member Functions inherited from BaseSpecies
BaseSpecies ()
The default constructor.
BaseSpecies (BaseNormalForce *normalForce, BaseFrictionForce *frictionForce_, BaseAdhesiveForce *adhesiveForce)
BaseSpecies (const BaseSpecies &p)
The copy constructor.
~BaseSpecies ()
The default destructor.
virtual void copyInto (BaseSpecies *s) const =0
void setHandler (SpeciesHandler *handler)
Sets the pointer to the handler to which this species belongs.
SpeciesHandler * getHandler () const
Returns the pointer to the handler to which this species belongs.
virtual void mixAll (BaseSpecies *S, BaseSpecies *T)=0
creates default values for mixed species
virtual bool getUseAngularDOFs () const =0
Returns true if torques (i.e. angular degrees of freedom) have to be calculated.
virtual BaseInteraction * getNewInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp) const =0
returns new Interaction object.
virtual BaseInteraction * getEmptyInteraction () const =0
virtual void deleteEmptyInteraction (BaseInteraction *interaction) const =0
Mdouble getInteractionDistance () const
returns the largest separation distance at which adhesive short-range forces can occur.
BaseNormalForce * getNormalForce () const
BaseFrictionForce * getFrictionForce () const
BaseAdhesiveForce * getAdhesiveForce () const
void setInteractionDistance (Mdouble interactionDistance)
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual std::string getName () const =0
A purely virtual function.
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Member Functions
Mdouble getLargestInverseParticleMassLocal () const
Computes inverse mass of the lightest particle (by mass) belonging to this species. If MPI is used, this computation is done locally on each node.
Private Attributes
Mdouble density_
The mass density.
std::function< double(double temperature)> temperatureDependentDensity_
Mdouble maxInteractionDistance_
Additional Inherited Members
Static Public Member Functions inherited from BaseSpecies
static Mdouble average (Mdouble a, Mdouble b)
Returns the harmonic mean of two variables.
static Mdouble averageInf (Mdouble a, Mdouble b)
Returns the harmonic mean of two variables, returning inf if either is inf.
Protected Attributes inherited from BaseSpecies
BaseNormalForce * normalForce_
A pointer to the normal force parameters.
BaseFrictionForce * frictionForce_
A pointer to the friction force parameters.
BaseAdhesiveForce * adhesiveForce_
A pointer to the adhesive force parameters.
Member Typedef Documentation
InteractionType
typedef BaseInteraction ParticleSpecies::InteractionType
MixedSpeciesType
typedef BaseSpecies ParticleSpecies::MixedSpeciesType
Constructor & Destructor Documentation
ParticleSpecies() [1/3]
ParticleSpecies::ParticleSpecies ()
The default constructor.
     : BaseSpecies(), density_(1.0), maxInteractionDistance_(0.0)
 {
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"ParticleSpecies::ParticleSpecies() finished"<<std::endl;
 #endif
 }
ParticleSpecies() [2/3]
ParticleSpecies::ParticleSpecies (const ParticleSpecies & p)
The default copy constructor.
Parameters
[in] p the species that is copied
     : BaseSpecies(p)
 {
     density_ = p.density_;
     temperatureDependentDensity_ = p.temperatureDependentDensity_;
     maxInteractionDistance_ = p.maxInteractionDistance_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"ParticleSpecies::ParticleSpecies(const ParticleSpecies &p) finished"<<std::endl;
 #endif
 }
References density_, maxInteractionDistance_, p, and temperatureDependentDensity_.
ParticleSpecies() [3/3]
ParticleSpecies::ParticleSpecies (BaseNormalForce * normalForce, BaseFrictionForce * frictionForce, BaseAdhesiveForce * adhesiveForce)
     : BaseSpecies(normalForce,frictionForce, adhesiveForce), density_(1.0), maxInteractionDistance_(0.0)
 {
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"ParticleSpecies::ParticleSpecies(n,f,a) finished"<<std::endl;
 #endif
 }
~ParticleSpecies()
ParticleSpecies::~ParticleSpecies ()
The default destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"ParticleSpecies::~ParticleSpecies() finished"<<std::endl;
 #endif
 }
Member Function Documentation
actionsAfterTimeStep()
virtual void ParticleSpecies::actionsAfterTimeStep (BaseParticle * particle) const inline virtual
Reimplemented in Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >, Species< LinearViscoelasticNormalSpecies >, Species< LinearViscoelasticNormalSpecies, FrictionSpecies >, Species< LinearPlasticViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, and Species< LinearViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >.
 {};
computeMass()
void ParticleSpecies::computeMass (BaseParticle * p) const
Compute Particle mass function, which required a reference to the Species vector. It computes the Particles mass, Inertia and the inverses.
Compute BaseParticle mass function, which required a reference to the Species vector. It computes the Particles mass, Inertia and the inverses. this function is called, if BaseParticleHandler::addObject, SpeciesHandler::addObject, ParticleSpecies::setDensity, BaseParticle::setRadius or DPMBase::setParticleDimensions is called
 {
     p->computeMass(*this);
 }
References p.
Referenced by SuperQuadricParticle::setAxes(), SuperQuadricParticle::setExponents(), BaseParticle::setRadius(), WallParticleCollision::setupInitialConditions(), and BaseParticle::unfix().
copy()
ParticleSpecies* ParticleSpecies::copy () const override pure virtual
Creates a deep copy of the object from which it is called.
See BaseSpecies::copy for details
Implements BaseSpecies.
Implemented in Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >, Species< LinearViscoelasticNormalSpecies >, Species< LinearViscoelasticNormalSpecies, FrictionSpecies >, Species< LinearPlasticViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, and Species< LinearViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >.
Referenced by CurvyChute::createBottom().
copyMixed()
virtual BaseSpecies* ParticleSpecies::copyMixed () const pure virtual
Creates a new MixedSpecies with the same force properties as the Species from which it is called. See Species::copyMixed for details.
Implemented in Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >, Species< LinearViscoelasticNormalSpecies >, Species< LinearViscoelasticNormalSpecies, FrictionSpecies >, Species< LinearPlasticViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, and Species< LinearViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >.
getBaseName()
std::string ParticleSpecies::getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
Returns
a string containing the name of the species (minus the word "Species")
 {
     return "Particle";
 }
getDensity()
Mdouble ParticleSpecies::getDensity () const
Allows density_ to be accessed.
Returns
the particle density
 {
     return density_;
 }
References density_.
Referenced by OneParticleCoolingSelfTest::actionsAfterTimeStep(), DropletBoundary::addHeatTransfer(), Membrane::adjustVertexParticleSize(), Membrane::buildMesh(), InsertionBoundary::checkBoundaryBeforeTimeStep(), FlowRule::getDensityVariation(), getMassFromRadius(), main(), ShearStage::printTime(), FileReader::read(), FlowRule::setDensityVariation(), SuperQuadricParticle::setInertia(), NozzleDemo::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), and SinterForceUnitTest::setupInitialConditions().
getLargestInverseParticleMassLocal()
Mdouble ParticleSpecies::getLargestInverseParticleMassLocal () const private
Computes inverse mass of the lightest particle (by mass) belonging to this species. If MPI is used, this computation is done locally on each node.
Returns
A pointer to the to the lightest BaseParticle (by mass) in this ParticleHandler.
 {
     Mdouble maxInvMass = 0;
     logger.assert_debug(getHandler() != nullptr && getHandler()->getDPMBase() != nullptr,"speciesHandler must be set");
     for (BaseParticle* const p : getHandler()->getDPMBase()->particleHandler)
     {
         if (p->getSpecies()==this && !(p->isFixed() || p->isMPIParticle() || p->isPeriodicGhostParticle()) && p->getInvMass() > maxInvMass)
         {
             maxInvMass = p->getInvMass();
         }
     }
     return maxInvMass;
 }
References BaseSpecies::getHandler(), logger, and p.
Referenced by getSmallestParticleMass().
getMassFromRadius() [1/2]
Mdouble ParticleSpecies::getMassFromRadius (const Mdouble radius, SpeciesHandler & speciesHandler)
 {
     setHandler(&speciesHandler);
     return getMassFromRadius(radius);
 }
References getMassFromRadius(), UniformPSDSelfTest::radius, and BaseSpecies::setHandler().
getMassFromRadius() [2/2]
Mdouble ParticleSpecies::getMassFromRadius (Mdouble radius) const
Todo:
TW: should getMassFromRadius be removed? IFCD: it is used in at least one driver (AxisymmetricHopper).
 {
     return getDensity() * getVolumeFromRadius(radius);
 }
References getDensity(), getVolumeFromRadius(), and UniformPSDSelfTest::radius.
Referenced by RotatingDrumBidisperseInitialise::actionsAfterTimeStep(), BaseCluster::calculateTimeStep(), DropletBoundary::checkBoundaryAfterParticlesMove(), ClosedCSCWalls::ClosedCSCWalls(), CSCWalls::CSCWalls(), getMassFromRadius(), MarbleRun::getParticleMass(), main(), ChuteBottom::makeRoughBottom(), ParticleCreation::ParticleCreation(), regimeForceUnitTest::regimeForceUnitTest(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), CFDDEMCoupleTest::setupInitialConditions(), BaseCluster::setupInitialConditions(), and viscoElasticUnitTest::viscoElasticUnitTest().
getMaxInteractionDistance()
Mdouble ParticleSpecies::getMaxInteractionDistance () const inline
returns the largest separation distance at which adhesive short-range forces can occur.
returns the largest separation distance (negative overlap) at which (adhesive) short-range forces can occur (needed for contact detection). Defined in each of the AdhesiveForceSpecies It is defined as a virtual function here to allow the function to be called from a BaseSpecies pointer (which is the kind of pointer used for MixedSpecies).
 {return maxInteractionDistance_;}
References maxInteractionDistance_.
Referenced by BaseParticle::getMaxInteractionRadius().
getMixedSpecies()
const BaseSpecies * ParticleSpecies::getMixedSpecies (const ParticleSpecies * s) const
{
     return (getIndex()==s->getIndex())?this:getHandler()->getMixedObject(getIndex(),s->getIndex());
 }
References BaseSpecies::getHandler(), BaseObject::getIndex(), SpeciesHandler::getMixedObject(), and s.
Referenced by BaseParticle::getInteractionDistance().
getSmallestParticleMass()
Mdouble ParticleSpecies::getSmallestParticleMass () const
Computes mass of the lightest particle (by mass) belonging to this species. This computation calls getLightestInverseParticleMassLocal, such that the computation is done on each node.
 {
 #ifdef MERCURYDPM_USE_MPI
     Mdouble maxInvMass = 0;
     Mdouble invMassLocal = getLargestInverseParticleMassLocal();
     //Obtain the global value
     MPIContainer::Instance().allReduce(invMassLocal, maxInvMass, MPI_MAX);
     //return value
     return 1.0 / maxInvMass;
 #else
     return 1.0 / getLargestInverseParticleMassLocal();
 #endif
 }
References getLargestInverseParticleMassLocal(), and MPIContainer::Instance().
getTemperatureDependentDensity()
const std::function< double(double)> & ParticleSpecies::getTemperatureDependentDensity () const
 {
     return temperatureDependentDensity_;
 }
References temperatureDependentDensity_.
getVolumeFromRadius()
Mdouble ParticleSpecies::getVolumeFromRadius (Mdouble radius) const
Todo:
this should depend on the particle shape; thus, it should be a static function of BaseParticle
 {
     if (getHandler() == nullptr)
     {
         logger(ERROR,
                "[Species::VolumeFromRadius()] No handler has been set, therefore, I can't figure out the dimensions.");
         return 0;
     }
     unsigned int particleDimensions = getHandler()->getDPMBase()->getParticleDimensions();
     if (particleDimensions == 3)
     {
         return 4.0 / 3.0 * constants::pi * radius * radius * radius;
     }
     else if (particleDimensions == 2)
     {
         return constants::pi * radius * radius;
     }
     else if (particleDimensions == 1)
     {
         return 2.0 * radius;
     }
     else
     {
         logger(ERROR, "[Species::VolumeFromRadius()] the dimension of the particle is wrongly set to %",
                particleDimensions);
         return 0.0;
     }
 }
References ERROR, BaseHandler< T >::getDPMBase(), BaseSpecies::getHandler(), DPMBase::getParticleDimensions(), logger, constants::pi, and UniformPSDSelfTest::radius.
Referenced by getMassFromRadius().
read()
void ParticleSpecies::read (std::istream & is) override virtual
Reads the species properties from an input stream.
Parameters
[in] is input stream (typically the restart file)
Reimplemented from BaseSpecies.
Reimplemented in Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >, Species< LinearViscoelasticNormalSpecies >, Species< LinearViscoelasticNormalSpecies, FrictionSpecies >, Species< LinearPlasticViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, and Species< LinearViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >.
 {
     BaseObject::read(is);
     std::string dummy;
     is >> dummy >> density_;
     BaseSpecies::read(is);
 }
References density_, BaseSpecies::read(), BaseObject::read(), and oomph::Global_string_for_annotation::string().
Referenced by Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::read().
setDensity()
void ParticleSpecies::setDensity (Mdouble density)
Allows density_ to be changed
Todo:
recalculate masses when setting dim_particle or rho
Parameters
[in] density the particle density
 {
     logger.assert_always(density > 0, "[ParticleSpecies::setDensity(%)] value has to be positive", density);
     density_ = density;
     if (getHandler()) getHandler()->getDPMBase()->particleHandler.computeAllMasses(getIndex());
 }
References ParticleHandler::computeAllMasses(), UniformPSDSelfTest::density, density_, BaseHandler< T >::getDPMBase(), BaseSpecies::getHandler(), BaseObject::getIndex(), logger, and DPMBase::particleHandler.
Referenced by AngledPeriodicBoundarySecondUnitTest::AngledPeriodicBoundarySecondUnitTest(), AngledPeriodicBoundaryUnitTest::AngledPeriodicBoundaryUnitTest(), AngleOfRepose::AngleOfRepose(), BouncingSuperQuadric::BouncingSuperQuadric(), BoundariesSelfTest::BoundariesSelfTest(), Membrane::buildMesh(), CGDisplacementFieldUnitTest::CGDisplacementFieldUnitTest(), CGExactOverlapUnitTest::CGExactOverlapUnitTest(), CGForceDensityUnitTest::CGForceDensityUnitTest(), ChutePeriodicDemo::ChutePeriodicDemo(), ChuteWithWedge::ChuteWithWedge(), ClosedCSCWalls::ClosedCSCWalls(), ParameterStudy1DDemo::createSpecies(), ParameterStudy2DDemo::createSpecies(), ParameterStudy3DDemo::createSpecies(), CSCWalls::CSCWalls(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundaryPrescribedDistanceUnitTest::FluxBoundaryPrescribedDistanceUnitTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), FluxBoundaryUnitTest::FluxBoundaryUnitTest(), ForceLawsMPI2Test::ForceLawsMPI2Test(), MembraneDemo::initializeSpecies(), MembraneSelfTest::initializeSpecies(), InsertionBoundaryMPI2Test::InsertionBoundaryMPI2Test(), InsertionBoundarySelfTest::InsertionBoundarySelfTest(), LaserOnLayer::LaserOnLayer(), LiquidMigrationMPI2Test::LiquidMigrationMPI2Test(), main(), MaserRepeatedOutInMPI2Test::MaserRepeatedOutInMPI2Test(), MinimalExampleDrum::MinimalExampleDrum(), MultiParticlesInsertion::MultiParticlesInsertion(), ParticleCreation::ParticleCreation(), ParticleInclusion::ParticleInclusion(), protectiveWall::protectiveWall(), FileReader::read(), SpeciesHandler::readOldObject(), regimeForceUnitTest::regimeForceUnitTest(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), FlowRule::setDensityVariation(), MercuryOS::setMaterialProperties(), MarbleRun::setParticleDensity(), GranularJet::setSilbert(), ChutePeriodic::setup(), NozzleDemo::setupInitialConditions(), Drum::setupInitialConditions(), CubicCell::setupInitialConditions(), FreeCooling2DinWallsDemo::setupInitialConditions(), FreeCoolingDemoProblem::setupInitialConditions(), ShiftingConstantMassFlowMaserBoundarySelfTest::setupInitialConditions(), ShiftingMaserBoundarySelfTest::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), DistributionSelfTest::setupInitialConditions(), DistributionToPSDSelfTest::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), MultiplePSDSelfTest::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), PSDManualInsertionSelfTest::setupInitialConditions(), StressStrainControl::setupInitialConditions(), SubcriticalMaserBoundarySelfTest::setupInitialConditions(), ParticleParticleCollision::setupInitialConditions(), WallParticleCollision::setupInitialConditions(), ContactDetectionIntersectionOfWallsTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), EllipsoidsBouncingOnWallDemo::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), SlidingSpheresUnitTest::setupInitialConditions(), ShapesDemo::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), Packing::setupInitialConditions(), CreateDataAndFStatFiles::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), HertzianSinterForceUnitTest::setupInitialConditions(), MovingIntersectionOfWallsUnitTest_Basic::setupInitialConditions(), MovingWalls::setupInitialConditions(), MovingWall::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), PlasticForceUnitTest::setupInitialConditions(), SeparateFilesSelfTest::setupInitialConditions(), WallSpecies::setupInitialConditions(), Siegen::Siegen(), SilbertPeriodic::SilbertPeriodic(), SingleParticleSegregation::SingleParticleSegregation(), StressStrainControl::StressStrainControl(), SubcriticalMaserBoundaryTESTMPI2Test::SubcriticalMaserBoundaryTESTMPI2Test(), T_protectiveWall::T_protectiveWall(), and viscoElasticUnitTest::viscoElasticUnitTest().
setMaxInteractionDistance()
void ParticleSpecies::setMaxInteractionDistance (Mdouble interactionDistance = 0)
Sets maxInteractionDistance_.
Parameters
interactionDistance the interaction distance that has been changed
Sets maxInteractionDistance_
Parameters
interactionDistance the interaction distance that has been changed
{
     // if maxInteractionDistance_ has increased it's simple
     if (interactionDistance>=maxInteractionDistance_) {
         maxInteractionDistance_ = interactionDistance;
     } else /*else we need to recompute*/ {
         maxInteractionDistance_ = 0;
         int j = getIndex();
         for (int i=0; i<getHandler()->getSize(); ++i) {
             const auto mixedSpecies = getHandler()->getMixedObject(i,j);
             if (mixedSpecies) { //this check is necessary because the mixed species handler might not yet be built fully
                 maxInteractionDistance_ = std::max(maxInteractionDistance_,
                         mixedSpecies->getInteractionDistance());
             }
         }
     }
 }
References BaseSpecies::getHandler(), BaseObject::getIndex(), SpeciesHandler::getMixedObject(), BaseHandler< T >::getSize(), i, j, max, and maxInteractionDistance_.
Referenced by BaseSpecies::setInteractionDistance().
setTemperatureDependentDensity()
void ParticleSpecies::setTemperatureDependentDensity (const std::function< double(double)> & temperatureDependentDensity)
 {
     temperatureDependentDensity_ = temperatureDependentDensity;
 //    density_ = temperatureDependentDensity_(0);
 //    logger(INFO,"Setting initial density to %",temperature_);
 }
References temperatureDependentDensity_.
write()
void ParticleSpecies::write (std::ostream & os) const override virtual
Writes the species properties to an output stream.
Parameters
[out] os output stream (typically the restart file)
Reimplemented from BaseSpecies.
Reimplemented in Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >, Species< LinearViscoelasticNormalSpecies >, Species< LinearViscoelasticNormalSpecies, FrictionSpecies >, Species< LinearPlasticViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, and Species< LinearViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >.
 {
     //note we inherit from BaseObject, not BaseParticle
     BaseObject::write(os);
     os << " density " << density_;
     BaseSpecies::write(os);
     //todo flip the two values
 }
References density_, BaseObject::write(), and BaseSpecies::write().
Referenced by Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::write().
Member Data Documentation
density_
Mdouble ParticleSpecies::density_ private
The mass density.
Referenced by getDensity(), ParticleSpecies(), read(), setDensity(), and write().
maxInteractionDistance_
Mdouble ParticleSpecies::maxInteractionDistance_ private
Returns the max distance between particles of this species and any other species below which adhesive forces can occur (needed for contact detection)
Referenced by getMaxInteractionDistance(), ParticleSpecies(), and setMaxInteractionDistance().
temperatureDependentDensity_
std::function<double(double temperature)> ParticleSpecies::temperatureDependentDensity_ private
Change this function to let the particles expand due to temperature. The default value (empty) stands for constant density.
Referenced by getTemperatureDependentDensity(), ParticleSpecies(), and setTemperatureDependentDensity().
The documentation for this class was generated from the following files:
ParticleSpecies.h
ParticleSpecies.cc