MercuryDPM: SuperQuadricParticleVtkWriter Class Reference
SuperQuadricParticleVtkWriter Class Reference final
#include <SuperQuadricParticleVtkWriter.h>
Public Member Functions
SuperQuadricParticleVtkWriter (ParticleHandler &particleHandler)
void writeVTK () const override
~SuperQuadricParticleVtkWriter () override=default
std::string getName () const override
Public Member Functions inherited from ParticleVtkWriter
ParticleVtkWriter (ParticleHandler &particleHandler)
virtual ~ParticleVtkWriter ()=default
Public Member Functions inherited from BaseVTKWriter< ParticleHandler >
BaseVTKWriter (ParticleHandler &handler)
BaseVTKWriter (const BaseVTKWriter &other)
unsigned getFileCounter () const
void setFileCounter (unsigned fileCounter)
void setOutputDirectory (const std::string &dir)
const std::string & getOutputDirectory () const
std::string getFileName () const
Private Member Functions
void writeVTKOrientation (std::fstream &file) const
void writeVTKSuperquadricGeometry (std::fstream &file) const
Additional Inherited Members
Protected Member Functions inherited from ParticleVtkWriter
void writeExtraFields (std::fstream &file) const
void writeVTKIndSpecies (std::fstream &file) const
void writeVTKPositions (std::fstream &file) const
bool particleMustBeWritten (BaseParticle *particle) const
Protected Member Functions inherited from BaseVTKWriter< ParticleHandler >
std::fstream makeVTKFileWithHeader () const
void writeVTKFooterAndClose (std::fstream &file) const
Protected Attributes inherited from BaseVTKWriter< ParticleHandler >
ParticleHandler & handler_
particle handler from which the particles should be written
unsigned int fileCounter
std::string outputDirectory_
Constructor & Destructor Documentation
SuperQuadricParticleVtkWriter()
SuperQuadricParticleVtkWriter::SuperQuadricParticleVtkWriter (ParticleHandler & particleHandler) inline explicit
                                                                              : ParticleVtkWriter(particleHandler)
     {}
~SuperQuadricParticleVtkWriter()
SuperQuadricParticleVtkWriter::~SuperQuadricParticleVtkWriter () override default
Member Function Documentation
getName()
std::string SuperQuadricParticleVtkWriter::getName () const inline override virtual
Implements ParticleVtkWriter.
     {
         return "SuperQuadricParticleVtkWriter";
     }
writeVTK()
void SuperQuadricParticleVtkWriter::writeVTK () const override virtual
Implements BaseVTKWriter< ParticleHandler >.
 {
     std::fstream file = makeVTKFileWithHeader();
     file << "<Piece NumberOfPoints=\"" << handler_.getSize() << "\" NumberOfCells=\"" << 0 << "\">\n";
     writeVTKPositions(file);
     file << "<PointData Scalars=\"speciesType\" Vectors=\"axesScales\" Tensors=\"orientationTensor\">\n";
     writeVTKIndSpecies(file);
     writeVTKSuperquadricGeometry(file);
     writeVTKOrientation(file);
     file << "</PointData>\n";
     writeVTKFooterAndClose(file);
 }
References BaseHandler< T >::getSize(), BaseVTKWriter< ParticleHandler >::handler_, BaseVTKWriter< ParticleHandler >::makeVTKFileWithHeader(), BaseVTKWriter< ParticleHandler >::writeVTKFooterAndClose(), ParticleVtkWriter::writeVTKIndSpecies(), writeVTKOrientation(), ParticleVtkWriter::writeVTKPositions(), and writeVTKSuperquadricGeometry().
Referenced by ShapesDemo::setupInitialConditions().
writeVTKOrientation()
void SuperQuadricParticleVtkWriter::writeVTKOrientation (std::fstream & file) const private
 {
     file << "  <DataArray type=\"Float32\" Name=\"orientationTensor\" NumberOfComponents=\"9\" format=\"ascii\">\n";
     // Add orientationTensor
     for (const auto& p: handler_)
     {
         SmallMatrix<3, 3> A;
         p->getOrientation().getRotationMatrix(A);
         file << '\t';
         for (unsigned i = 0; i < 3; ++i)
         {
             for (unsigned j = 0; j < 3; ++j)
             {
                 file << A(i, j) << " ";
             }
         }
         file << '\n';
     }
     file << "  </DataArray>\n";
 }
References BaseVTKWriter< ParticleHandler >::handler_, i, j, and p.
Referenced by writeVTK().
writeVTKSuperquadricGeometry()
void SuperQuadricParticleVtkWriter::writeVTKSuperquadricGeometry (std::fstream & file) const private
 {
     file << "  <DataArray type=\"Float32\" Name=\"phiAndTheta\" NumberOfComponents=\"2\" format=\"ascii\">\n";
     // Add exponents eps1 and eps2. Note, they are defined in reverse order in Paraview!
     for (const auto& p: handler_)
     {
         file << '\t' << p->getExponentEps2() << " " <<  p->getExponentEps1()  << '\n';
     }
     file << "  </DataArray>\n";
     file << "  <DataArray type=\"Float32\" Name=\"axesScales\" NumberOfComponents=\"3\" format=\"ascii\">\n";
     // Add axesScales
     for (const auto& p: handler_)
     {
         file << '\t' << 2 * p->getAxes() << '\n';
     }
     file << "  </DataArray>\n";
 }
References BaseVTKWriter< ParticleHandler >::handler_, and p.
Referenced by writeVTK().
The documentation for this class was generated from the following files:
SuperQuadricParticleVtkWriter.h
SuperQuadricParticleVtkWriter.cc