MercuryDPM: Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator Class Reference
Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator Class Reference
#include <SparseCompressedBase.h>
Public Member Functions
ReverseInnerIterator (const SparseCompressedBase &mat, Index outer)
ReverseInnerIterator (const SparseCompressedBase &mat)
ReverseInnerIterator (const internal::CompressedStorage< Scalar, StorageIndex > &data)
ReverseInnerIterator & operator-- ()
ReverseInnerIterator & operator-= (Index i)
ReverseInnerIterator operator- (Index i)
const Scalar & value () const
Scalar & valueRef ()
StorageIndex index () const
Index outer () const
Index row () const
Index col () const
operator bool () const
Protected Types
typedef internal::variable_if_dynamic< Index, Derived::IsVectorAtCompileTime ? 0 :Dynamic > OuterType
Protected Attributes
const Scalar * m_values
const StorageIndex * m_indices
const OuterType m_outer
Index m_start
Index m_id
Member Typedef Documentation
OuterType
template<typename Derived > typedef internal::variable_if_dynamic<Index, Derived::IsVectorAtCompileTime ? 0 : Dynamic> Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::OuterType protected
Constructor & Destructor Documentation
ReverseInnerIterator() [1/3]
template<typename Derived > Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::ReverseInnerIterator (const SparseCompressedBase & mat, Index outer) inline
       : m_values(mat.valuePtr()), m_indices(mat.innerIndexPtr()), m_outer(outer) {
     if (Derived::IsVectorAtCompileTime && mat.outerIndexPtr() == 0) {
       m_start = 0;
       m_id = mat.nonZeros();
     } else {
       m_start = mat.outerIndexPtr()[outer];
       if (mat.isCompressed())
         m_id = mat.outerIndexPtr()[outer + 1];
       else
         m_id = m_start + mat.innerNonZeroPtr()[outer];
     }
   }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::innerNonZeroPtr(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::isCompressed(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::nonZeros(), and Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::outerIndexPtr().
ReverseInnerIterator() [2/3]
template<typename Derived > Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::ReverseInnerIterator (const SparseCompressedBase & mat) inline explicit
       : m_values(mat.valuePtr()), m_indices(mat.innerIndexPtr()), m_outer(0), m_start(0), m_id(mat.nonZeros()) {
     EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived);
   }
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
ReverseInnerIterator() [3/3]
template<typename Derived > Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::ReverseInnerIterator (const internal::CompressedStorage< Scalar, StorageIndex > & data) inline explicit
       : m_values(data.valuePtr()), m_indices(data.indexPtr()), m_outer(0), m_start(0), m_id(data.size()) {
     EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived);
   }
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
Member Function Documentation
col()
template<typename Derived > Index Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::col () const inline
 { return IsRowMajor ? index() : m_outer.value(); }
References Eigen::SparseCompressedBase< Derived >::IsRowMajor.
index()
template<typename Derived > StorageIndex Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::index () const inline
 { return m_indices[m_id - 1]; }
operator bool()
template<typename Derived > Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::operator bool () const inline
 { return (m_id > m_start); }
operator-()
template<typename Derived > ReverseInnerIterator Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::operator- (Index i) inline
{
     ReverseInnerIterator result = *this;
     result -= i;
     return result;
   }
References i.
operator--()
template<typename Derived > ReverseInnerIterator& Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::operator-- () inline
{
     --m_id;
     return *this;
   }
operator-=()
template<typename Derived > ReverseInnerIterator& Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::operator-= (Index i) inline
{
     m_id -= i;
     return *this;
   }
References i.
outer()
template<typename Derived > Index Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::outer () const inline
 { return m_outer.value(); }
row()
template<typename Derived > Index Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::row () const inline
 { return IsRowMajor ? m_outer.value() : index(); }
References Eigen::SparseCompressedBase< Derived >::IsRowMajor.
value()
template<typename Derived > const Scalar& Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::value () const inline
 { return m_values[m_id - 1]; }
valueRef()
template<typename Derived > Scalar& Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::valueRef () inline
 { return const_cast<Scalar&>(m_values[m_id - 1]); }
Member Data Documentation
m_id
template<typename Derived > Index Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::m_id protected
m_indices
template<typename Derived > const StorageIndex* Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::m_indices protected
m_outer
template<typename Derived > const OuterType Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::m_outer protected
m_start
template<typename Derived > Index Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::m_start protected
m_values
template<typename Derived > const Scalar* Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::m_values protected
The documentation for this class was generated from the following file:
SparseCompressedBase.h