MercuryDPM: BaseSpecies Class Reference
BaseSpecies Class Reference abstract
BaseSpecies is the class from which all other species are derived.
#include <BaseSpecies.h>
Public Member Functions
BaseSpecies ()
The default constructor.
BaseSpecies (BaseNormalForce *normalForce, BaseFrictionForce *frictionForce_, BaseAdhesiveForce *adhesiveForce)
BaseSpecies (const BaseSpecies &p)
The copy constructor.
~BaseSpecies ()
The default destructor.
virtual BaseSpecies * copy () const =0
Creates a deep copy of the object from which it is called.
virtual void copyInto (BaseSpecies *s) const =0
void setHandler (SpeciesHandler *handler)
Sets the pointer to the handler to which this species belongs.
SpeciesHandler * getHandler () const
Returns the pointer to the handler to which this species belongs.
virtual void mixAll (BaseSpecies *S, BaseSpecies *T)=0
creates default values for mixed species
virtual bool getUseAngularDOFs () const =0
Returns true if torques (i.e. angular degrees of freedom) have to be calculated.
virtual BaseInteraction * getNewInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp) const =0
returns new Interaction object.
virtual BaseInteraction * getEmptyInteraction () const =0
virtual void deleteEmptyInteraction (BaseInteraction *interaction) const =0
Mdouble getInteractionDistance () const
returns the largest separation distance at which adhesive short-range forces can occur.
BaseNormalForce * getNormalForce () const
BaseFrictionForce * getFrictionForce () const
BaseAdhesiveForce * getAdhesiveForce () const
void setInteractionDistance (Mdouble interactionDistance)
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual std::string getName () const =0
A purely virtual function.
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Static Public Member Functions
static Mdouble average (Mdouble a, Mdouble b)
Returns the harmonic mean of two variables.
static Mdouble averageInf (Mdouble a, Mdouble b)
Returns the harmonic mean of two variables, returning inf if either is inf.
Protected Member Functions
void write (std::ostream &os) const override
Sets the boolean constantRestitution_.
void read (std::istream &is) override
Protected Attributes
BaseNormalForce * normalForce_
A pointer to the normal force parameters.
BaseFrictionForce * frictionForce_
A pointer to the friction force parameters.
BaseAdhesiveForce * adhesiveForce_
A pointer to the adhesive force parameters.
Private Attributes
SpeciesHandler * handler_
A pointer to the handler to which this species belongs. It is initialized to nullptr and gets set when SpeciesHandler::addObject() is called.
Mdouble interactionDistance_
Detailed Description
BaseSpecies is the class from which all other species are derived.
A base species is almost empty, with the exception of a pointer to the particleHandler. All other properties get added in the inherited classes. See Species for more details.
Constructor & Destructor Documentation
BaseSpecies() [1/3]
BaseSpecies::BaseSpecies ()
The default constructor.
         : BaseObject(), handler_(nullptr), interactionDistance_(0)
 {
     logger(DEBUG, "BaseSpecies::BaseSpecies() finished");
 }
References DEBUG, and logger.
BaseSpecies() [2/3]
BaseSpecies::BaseSpecies (BaseNormalForce * normalForce, BaseFrictionForce * frictionForce_, BaseAdhesiveForce * adhesiveForce)
         : BaseObject(), normalForce_(normalForce), frictionForce_(frictionForce), adhesiveForce_(adhesiveForce),
         handler_(nullptr), interactionDistance_(0)
 {
     normalForce_->setBaseSpecies(this);
     frictionForce_->setBaseSpecies(this);
     adhesiveForce_->setBaseSpecies(this);
     logger(DEBUG, "BaseSpecies::BaseSpecies() finished");
 }
References adhesiveForce_, DEBUG, frictionForce_, logger, normalForce_, and BaseForce::setBaseSpecies().
BaseSpecies() [3/3]
BaseSpecies::BaseSpecies (const BaseSpecies & p)
The copy constructor.
Parameters
[in] p the species that is copied
         : BaseObject(p), handler_(p.handler_), interactionDistance_(p.interactionDistance_)
 {
     logger(DEBUG, "BaseSpecies::BaseSpecies(const BaseSpecies &p) finished");
 }
References DEBUG, and logger.
~BaseSpecies()
BaseSpecies::~BaseSpecies ()
The default destructor.
Todo:
the BaseSpecies destructor should delete all particles and wall belonging to that species; however, that will break all codes replacing a species (e.g. Sudeshna and Hao) so we need a proper way to replace a species
 {
     //for now, I added a particleHandler.clear(); wallHandler.clear() before speciesHandler.clear() in DPMBase::read()
 //    //if species gets removed, all particles/ walls of this type need to be removed as well
 //    if (getHandler()) {
 //        DPMBase* dpm = getHandler()->getDPMBase();
 //        for (const auto o : dpm->wallHandler) {
 //            if (o->getSpecies()==this) {
 //                dpm->wallHandler.removeObject(o->getIndex());
 //            }
 //        }
 //        for (const auto o : dpm->particleHandler) {
 //            if (o->getSpecies()==this) {
 //                dpm->particleHandler.removeObject(o->getIndex());
 //            }
 //        }
 //    }
     logger(DEBUG, "BaseSpecies::~BaseSpecies() finished");
 }
References DEBUG, and logger.
Member Function Documentation
average()
Mdouble BaseSpecies::average (Mdouble a, Mdouble b) static
Returns the harmonic mean of two variables.
Returns the harmonic mean of two variables. This function is used to define default mixed species.
Parameters
[in] a,b The two variables you want to average
Returns
The harmonic mean of a and b, \(\frac{2}{1/a+1/b}\)
 {
     //the second algorithm seems to have a better accuracy, at least for the case average(2e5,2e5)
     //return (a + b) != 0.0 ? (2. * (a * b) / (a + b)) : 0;
     return (a==0||b==0) ? 0.0 : (2. / (1.0 / a + 1.0 / b));
 }
References a, and b.
Referenced by averageInf(), BondedSpecies::mix(), ChargedBondedSpecies::mix(), FrictionSpecies::mix(), HertzianSinterNormalSpecies::mix(), JKRAdhesiveSpecies::mix(), LinearPlasticViscoelasticNormalSpecies::mix(), LinearViscoelasticNormalSpecies::mix(), LiquidBridgeBagheriSpecies::mix(), LiquidBridgeClassicalWilletSpecies::mix(), LiquidBridgeWilletSpecies::mix(), LiquidMigrationLSSpecies::mix(), LiquidMigrationWilletSpecies::mix(), LiquidMigrationWilletViscousSpecies::mix(), MeltableNormalSpecies::mix(), MindlinRollingTorsionSpecies::mix(), MindlinSpecies::mix(), ReversibleAdhesiveSpecies::mix(), SinterLinNormalSpecies::mix(), SinterNormalSpecies::mix(), SlidingFrictionSpecies::mix(), SolidifyingLiquidMigrationWilletSpecies::mix(), and SPHNormalSpecies::mix().
averageInf()
Mdouble BaseSpecies::averageInf (Mdouble a, Mdouble b) static
Returns the harmonic mean of two variables, returning inf if either is inf.
Returns the harmonic mean of two variables, returning inf if either is inf.
 {
     if (a == constants::inf || b == constants::inf)
         return constants::inf;
     else
         return average(a, b);
 }
References a, average(), b, and constants::inf.
Referenced by FrictionSpecies::mix().
copy()
virtual BaseSpecies* BaseSpecies::copy () const pure virtual
Creates a deep copy of the object from which it is called.
Creates a deep copy of the Species, or MixedSpecies from which it is called. As this depends on the template parameters of Species, the definition of this function is in the Species class.
It is defined as a virtual function here to allow the function to be called from a BaseSpecies pointer (which is the kind of pointer used for MixedSpecies).
To create a copy of a MixedSpecies, use
BaseSpecies* mixedSpecies->copy();
To create a copy of a Species, use
ParticleSpecies* species->copy();
Implemented in ParticleSpecies, Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >, Species< LinearViscoelasticNormalSpecies >, Species< LinearViscoelasticNormalSpecies, FrictionSpecies >, Species< LinearPlasticViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, Species< LinearViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, and MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >.
Referenced by SubcriticalMaserBoundary::addParticleToMaser(), SpeciesHandler::operator=(), and SpeciesHandler::SpeciesHandler().
copyInto()
virtual void BaseSpecies::copyInto (BaseSpecies * s) const pure virtual
Copies the content of this into the species bs, if they are of the same type.
Implemented in Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >, Species< LinearViscoelasticNormalSpecies >, Species< LinearViscoelasticNormalSpecies, FrictionSpecies >, Species< LinearPlasticViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, Species< LinearViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, and MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >.
Referenced by ConstantMassFlowMaserBoundary::addParticleToMaser().
deleteEmptyInteraction()
virtual void BaseSpecies::deleteEmptyInteraction (BaseInteraction * interaction) const pure virtual
Implemented in Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >, Species< LinearViscoelasticNormalSpecies >, Species< LinearViscoelasticNormalSpecies, FrictionSpecies >, Species< LinearPlasticViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, Species< LinearViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, and MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >.
Referenced by InteractionHandler::deleteEmptyInteraction(), and MPIContainer::initialiseMercuryMPITypes().
getAdhesiveForce()
BaseAdhesiveForce* BaseSpecies::getAdhesiveForce () const inline
 {return adhesiveForce_;}
References adhesiveForce_.
Referenced by ChargedBondedInteraction::getElasticEnergy(), BondedInteraction::getSpecies(), ChargedBondedInteraction::getSpecies(), EmptyAdhesiveInteraction::getSpecies(), IrreversibleAdhesiveInteraction::getSpecies(), LiquidBridgeBagheriInteraction::getSpecies(), LiquidBridgeClassicalWilletInteraction::getSpecies(), LiquidBridgeWilletInteraction::getSpecies(), LiquidMigrationLSInteraction::getSpecies(), LiquidMigrationWilletInteraction::getSpecies(), LiquidMigrationWilletViscousInteraction::getSpecies(), ParhamiMcMeekingSinterInteraction::getSpecies(), RegimeSinterInteraction::getSpecies(), ReversibleAdhesiveInteraction::getSpecies(), and SolidifyingLiquidMigrationWilletInteraction::getSpecies().
getEmptyInteraction()
virtual BaseInteraction* BaseSpecies::getEmptyInteraction () const pure virtual
Todo:
add documentation
Implemented in Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >, Species< LinearViscoelasticNormalSpecies >, Species< LinearViscoelasticNormalSpecies, FrictionSpecies >, Species< LinearPlasticViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, Species< LinearViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, and MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >.
Referenced by InteractionHandler::createEmptyInteraction(), and MPIContainer::initialiseMercuryMPITypes().
getFrictionForce()
BaseFrictionForce* BaseSpecies::getFrictionForce () const inline
 {return frictionForce_;}
References frictionForce_.
Referenced by EmptyFrictionInteraction::getSpecies(), FrictionInteraction::getSpecies(), MindlinInteraction::getSpecies(), MindlinRollingTorsionInteraction::getSpecies(), and SlidingFrictionInteraction::getSpecies().
getHandler()
SpeciesHandler * BaseSpecies::getHandler () const
Returns the pointer to the handler to which this species belongs.
Returns
the pointer to the handler to which this species belongs.
 {
     return handler_;
 }
References handler_.
Referenced by SuperQuadricParticle::getInteractionRadius(), ParticleSpecies::getLargestInverseParticleMassLocal(), ParticleSpecies::getMixedSpecies(), ParticleSpecies::getVolumeFromRadius(), ParticleSpecies::setDensity(), setInteractionDistance(), ParticleSpecies::setMaxInteractionDistance(), BaseInteractable::setSpecies(), BaseParticle::setSpecies(), BaseWall::setSpecies(), and BaseInteraction::writeInteraction().
getInteractionDistance()
Mdouble BaseSpecies::getInteractionDistance () const inline
returns the largest separation distance at which adhesive short-range forces can occur.
returns the largest separation distance (negative overlap) at which (adhesive) short-range forces can occur (needed for contact detection). Defined in each of the AdhesiveForceSpecies It is defined as a virtual function here to allow the function to be called from a BaseSpecies pointer (which is the kind of pointer used for MixedSpecies).
 {return interactionDistance_;}
References interactionDistance_.
Referenced by ChargedBondedInteraction::getElasticEnergy(), BaseParticle::getInteractionDistance(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), and ParticleWallInteraction::setupInitialConditions().
getNewInteraction()
virtual BaseInteraction* BaseSpecies::getNewInteraction (BaseInteractable * P, BaseInteractable * I, unsigned timeStamp) const pure virtual
returns new Interaction object.
As each Species has its own Interaction type, getNewInteraction can be used to access the right type of Interaction It is defined as a virtual function here to allow the function to be called from a BaseSpecies pointer (which is the kind of pointer used for MixedSpecies).
Implemented in Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >, Species< LinearViscoelasticNormalSpecies >, Species< LinearViscoelasticNormalSpecies, FrictionSpecies >, Species< LinearPlasticViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, Species< LinearViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, and MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >.
Referenced by InteractionHandler::addInteraction(), and InteractionHandler::getInteraction().
getNormalForce()
BaseNormalForce* BaseSpecies::getNormalForce () const inline
 {return normalForce_;}
References normalForce_.
Referenced by LinearPlasticViscoelasticInteraction::getElasticEnergy(), LinearViscoelasticInteraction::getElasticEnergy(), HertzianBSHPViscoelasticInteraction::getSpecies(), HertzianSinterInteraction::getSpecies(), HertzianViscoelasticInteraction::getSpecies(), LinearPlasticViscoelasticInteraction::getSpecies(), LinearViscoelasticInteraction::getSpecies(), SinterInteraction::getSpecies(), and SPHInteraction::getSpecies().
getUseAngularDOFs()
virtual bool BaseSpecies::getUseAngularDOFs () const pure virtual
Returns true if torques (i.e. angular degrees of freedom) have to be calculated.
returns true if torques have to be calculated. This is currently only true if a tangential force is applied, but can be true for non-spherical objects even if no tangential force is applied . Defined in FrictionForceSpecies. It is defined as a virtual function here to allow the function to be called from a BaseSpecies pointer (which is the kind of pointer used for MixedSpecies).
Implemented in Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >, Species< LinearViscoelasticNormalSpecies >, Species< LinearViscoelasticNormalSpecies, FrictionSpecies >, Species< LinearPlasticViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, Species< LinearViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, and MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >.
Referenced by SpeciesHandler::useAngularDOFs().
mixAll()
virtual void BaseSpecies::mixAll (BaseSpecies * S, BaseSpecies * T) pure virtual
creates default values for mixed species
returns the largest separation distance (negative overlap) at which (adhesive) short-range forces can occur (needed for contact detection). Defined in each of the AdhesiveForceSpecies It is defined as a virtual function here to allow the function to be called from a BaseSpecies pointer (which is the kind of pointer used for MixedSpecies).
Implemented in Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >, Species< LinearViscoelasticNormalSpecies >, Species< LinearViscoelasticNormalSpecies, FrictionSpecies >, Species< LinearPlasticViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, Species< LinearViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, and MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >.
read()
void BaseSpecies::read (std::istream & is) override protected virtual
Parameters
[in] is input stream (typically the restart file)
Implements BaseObject.
Reimplemented in ParticleSpecies, Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >, Species< LinearViscoelasticNormalSpecies >, Species< LinearViscoelasticNormalSpecies, FrictionSpecies >, Species< LinearPlasticViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, Species< LinearViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, and MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >.
 {
     //BaseObject::read(is);
     bool constantRestitution;
     if (helpers::readOptionalVariable(is, "constantRestitution", constantRestitution)) {
         normalForce_->setConstantRestitution(constantRestitution);
     }
 }
References normalForce_, helpers::readOptionalVariable(), and BaseNormalForce::setConstantRestitution().
Referenced by MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::read(), and ParticleSpecies::read().
setHandler()
void BaseSpecies::setHandler (SpeciesHandler * handler)
Sets the pointer to the handler to which this species belongs.
Parameters
[in] the pointer to the handler to which this species belongs.
 {
     handler_ = handler;
 }
References handler_.
Referenced by ParticleSpecies::getMassFromRadius(), main(), regimeForceUnitTest::regimeForceUnitTest(), and viscoElasticUnitTest::viscoElasticUnitTest().
setInteractionDistance()
void BaseSpecies::setInteractionDistance (Mdouble interactionDistance)
Sets BaseSpecies::interactionDistance_. This function should not be called by the user, only by functions in classes derived from BaseSpecies (in particular, the adhesive-force species). This function gets called every time a variable is set on which the interaction distance depends. See for example LiquidBridgeWilletSpecies::setLiquidBridgeVolume.
Parameters
interactionDistance
{
     interactionDistance_ = interactionDistance;
     SpeciesHandler* handler = getHandler();
     if (handler == nullptr) return;
     for (auto mixedSpecies : handler->getMixedObjects()) {
         if (mixedSpecies == this) {
             // get the two particlespecies id's
             unsigned mixedId = mixedSpecies->getIndex();
             unsigned maxId= 1;
             unsigned maxMixedId = (maxId * (maxId + 1)) / 2;
             while (maxMixedId<mixedId) {
                 ++maxId;
                 maxMixedId = (maxId * (maxId + 1)) / 2;
             }
             unsigned minId = (mixedId + maxId) - maxMixedId;
             handler->getObject(minId)->setMaxInteractionDistance(interactionDistance);
             handler->getObject(maxId)->setMaxInteractionDistance(interactionDistance);
             //logger(INFO,"setInteractionDistance(%) mixed % handler %",interactionDistance, getIndex(), getHandler());
             return;
         }
     }
     // if not a mixed species, check it's a species in the speciesHandler
     if (handler->getSize()>getId() && handler->getObject(getId()) == this) {
         handler->getObject(getId())->setMaxInteractionDistance(interactionDistance);
     }
     //logger(INFO,"setInteractionDistance(%) species % handler %",interactionDistance, getIndex(), getHandler());
 }
References getHandler(), BaseObject::getId(), SpeciesHandler::getMixedObjects(), BaseHandler< T >::getObject(), BaseHandler< T >::getSize(), interactionDistance_, and ParticleSpecies::setMaxInteractionDistance().
Referenced by ChargedBondedSpecies::setInteractionDistance(), LiquidBridgeBagheriSpecies::setInteractionDistance(), LiquidBridgeClassicalWilletSpecies::setInteractionDistance(), LiquidBridgeWilletSpecies::setInteractionDistance(), LiquidMigrationLSSpecies::setInteractionDistance(), LiquidMigrationWilletSpecies::setInteractionDistance(), and ReversibleAdhesiveSpecies::setInteractionDistance().
write()
void BaseSpecies::write (std::ostream & os) const override protected virtual
Sets the boolean constantRestitution_.
Parameters
[out] os output stream (typically the restart file)
Implements BaseObject.
Reimplemented in ParticleSpecies, Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >, Species< LinearViscoelasticNormalSpecies >, Species< LinearViscoelasticNormalSpecies, FrictionSpecies >, Species< LinearPlasticViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, Species< LinearViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, and MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >.
 {
     //BaseObject::write(os);
     if (normalForce_->getConstantRestitution()) os << " constantRestitution " << normalForce_->getConstantRestitution();
 }
References BaseNormalForce::getConstantRestitution(), and normalForce_.
Referenced by MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::write(), and ParticleSpecies::write().
Member Data Documentation
adhesiveForce_
BaseAdhesiveForce* BaseSpecies::adhesiveForce_ protected
A pointer to the adhesive force parameters.
This pointer is used by the Interaction's to get a pointer to the species The pointer is set in the constructors of SPecies and MixedSpecies
Referenced by BaseSpecies(), getAdhesiveForce(), MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::MixedSpecies(), and Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::Species().
frictionForce_
BaseFrictionForce* BaseSpecies::frictionForce_ protected
A pointer to the friction force parameters.
This pointer is used by the Interaction's to get a pointer to the species The pointer is set in the constructors of SPecies and MixedSpecies
Referenced by BaseSpecies(), getFrictionForce(), MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::MixedSpecies(), and Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::Species().
handler_
SpeciesHandler* BaseSpecies::handler_ private
A pointer to the handler to which this species belongs. It is initialized to nullptr and gets set when SpeciesHandler::addObject() is called.
Referenced by getHandler(), and setHandler().
interactionDistance_
Mdouble BaseSpecies::interactionDistance_ private
Returns the distance between particles of this species below which adhesive forces can occur (needed for contact detection) set by the adhesive species
Referenced by getInteractionDistance(), and setInteractionDistance().
normalForce_
BaseNormalForce* BaseSpecies::normalForce_ protected
A pointer to the normal force parameters.
This pointer is used by the Interaction's to get a pointer to the species The pointer is set in the constructors of SPecies and MixedSpecies
Referenced by BaseSpecies(), getNormalForce(), MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::MixedSpecies(), read(), Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::Species(), and write().
The documentation for this class was generated from the following files:
BaseSpecies.h
BaseSpecies.cc