MercuryDPM: oomph::AlgebraicFishMesh< ELEMENT > Class Template Reference
oomph::AlgebraicFishMesh< ELEMENT > Class Template Reference
Fish shaped mesh with algebraic node update function for nodes.
#include <fish_mesh.template.h>
Public Member Functions
AlgebraicFishMesh (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
AlgebraicFishMesh (GeomObject *back_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual ~AlgebraicFishMesh ()
Destructor: empty.
void algebraic_node_update (const unsigned &t, AlgebraicNode *&node_pt)
virtual void node_update (const bool &update_all_solid_nodes=false)
void update_node_update (AlgebraicNode *&node_pt)
Public Member Functions inherited from oomph::AlgebraicMesh
AlgebraicMesh ()
AlgebraicMesh (const AlgebraicMesh &)=delete
Broken copy constructor.
~AlgebraicMesh ()
Broken assignment operator.
AlgebraicNode * node_pt (const unsigned long &n)
Return a pointer to the n-th global AlgebraicNode.
unsigned self_test ()
Self test: check consistentency of multiple node updates.
void add_geom_object_list_pt (GeomObject *geom_object_pt)
unsigned ngeom_object_list_pt ()
Return number of geometric objects associated with AlgebraicMesh.
GeomObject * geom_object_list_pt (const unsigned &i)
Access function to the ith GeomObject.
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Public Member Functions inherited from oomph::FishMesh< ELEMENT >
FishMesh (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
FishMesh (GeomObject *back_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual ~FishMesh ()
GeomObject *& fish_back_pt ()
Access function to geom object that represents the fish's back.
FishDomain *& domain_pt ()
Access function to FishDomain.
Public Member Functions inherited from oomph::QuadMeshBase
QuadMeshBase ()
Constructor (empty)
QuadMeshBase (const QuadMeshBase &node)=delete
Broken copy constructor.
void operator= (const QuadMeshBase &)=delete
Broken assignment operator.
virtual ~QuadMeshBase ()
Destructor (empty)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Protected Member Functions
void node_update_in_body (const unsigned &t, AlgebraicNode *&node_pt)
Algebraic update function for nodes in upper/lower body.
void node_update_in_fin (const unsigned &t, AlgebraicNode *&node_pt)
Algebraic update function for nodes in upper/lower fin.
void setup_algebraic_node_update ()
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Member Functions inherited from oomph::FishMesh< ELEMENT >
void build_mesh (TimeStepper *time_stepper_pt)
Build the mesh, using the geometric object identified by Back_pt.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Types inherited from oomph::FishMesh< ELEMENT >
enum { Lower_body , Upper_body , Lower_fin , Upper_fin }
Remesh function ids.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Protected Attributes inherited from oomph::FishMesh< ELEMENT >
GeomObject * Back_pt
Pointer to fish back.
FishDomain * Domain_pt
Pointer to domain.
bool Must_kill_fish_back
Do I need to kill the fish back geom object?
Detailed Description
template<class ELEMENT>
class oomph::AlgebraicFishMesh< ELEMENT >
Fish shaped mesh with algebraic node update function for nodes.
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
AlgebraicFishMesh() [1/2]
template<class ELEMENT > oomph::AlgebraicFishMesh< ELEMENT >::AlgebraicFishMesh (TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Constructor: Pass pointer to timestepper. (defaults to (Steady) default timestepper defined in Mesh)
       : FishMesh<ELEMENT>(time_stepper_pt)
     {
       // Setup algebraic node update operations
       setup_algebraic_node_update();
     }
References oomph::AlgebraicFishMesh< ELEMENT >::setup_algebraic_node_update().
AlgebraicFishMesh() [2/2]
template<class ELEMENT > oomph::AlgebraicFishMesh< ELEMENT >::AlgebraicFishMesh (GeomObject * back_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Constructor: Pass pointer GeomObject that defines the fish's back and pointer to timestepper (defaults to (Steady) default timestepper defined in Mesh).
       : FishMesh<ELEMENT>(back_pt, time_stepper_pt)
     {
       // Add the geometric object to the list associated with this AlgebraicMesh
       AlgebraicMesh::add_geom_object_list_pt(back_pt);
       // Setup algebraic node update operations
       setup_algebraic_node_update();
     }
References oomph::AlgebraicMesh::add_geom_object_list_pt(), and oomph::AlgebraicFishMesh< ELEMENT >::setup_algebraic_node_update().
~AlgebraicFishMesh()
template<class ELEMENT > virtual oomph::AlgebraicFishMesh< ELEMENT >::~AlgebraicFishMesh () inline virtual
Destructor: empty.
 {}
Member Function Documentation
algebraic_node_update()
template<class ELEMENT > void oomph::AlgebraicFishMesh< ELEMENT >::algebraic_node_update (const unsigned & t, AlgebraicNode *& node_pt) inline virtual
Update nodal position at time level t (t=0: present; t>0: previous)
Implements oomph::AlgebraicMesh.
     {
       // Update with the update function for the node's first (default)
       // node update fct
       unsigned id = node_pt->node_update_fct_id();
       // Upper/lower body
       if ((id == this->Lower_body) || (id == this->Upper_body))
       {
         node_update_in_body(t, node_pt);
       }
       // Upper/lower fin
       else if ((id == this->Lower_fin) || (id == this->Upper_fin))
       {
         node_update_in_fin(t, node_pt);
       }
       else
       {
         std::ostringstream error_message;
         error_message << "The node update fct id is " << id
                       << ", but it should only be one of " << this->Lower_body
                       << ", " << this->Upper_body << ", " << this->Lower_fin
                       << " or " << this->Upper_fin << std::endl;
         std::string function_name =
           "AlgebraicFishMesh::algebraic_node_update()";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
     }
References oomph::FishMesh< ELEMENT >::Lower_body, oomph::FishMesh< ELEMENT >::Lower_fin, oomph::AlgebraicMesh::node_pt(), oomph::AlgebraicNode::node_update_fct_id(), oomph::AlgebraicFishMesh< ELEMENT >::node_update_in_body(), oomph::AlgebraicFishMesh< ELEMENT >::node_update_in_fin(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Global_string_for_annotation::string(), oomph::FishMesh< ELEMENT >::Upper_body, and oomph::FishMesh< ELEMENT >::Upper_fin.
node_update()
template<class ELEMENT > virtual void oomph::AlgebraicFishMesh< ELEMENT >::node_update (const bool & update_all_solid_nodes = false) inline virtual
Resolve the node update function (we neither want the broken empty one in the Mesh base class nor the macro-element-based one in the RefineableQuadMesh base class but the AlgebraicElement one). [It doesn't make sense to use this mesh with SolidElements so we buffer the case if update_all_solid_nodes is set to true.]
Reimplemented from oomph::AlgebraicMesh.
Reimplemented in oomph::AlgebraicRefineableFishMesh< ELEMENT >.
     {
 #ifdef PARANOID
       if (update_all_solid_nodes)
       {
         std::string error_message =
           "Doesn't make sense to use an AlgebraicMesh with\n";
         error_message +=
           "SolidElements so specifying update_all_solid_nodes=true\n";
         error_message += "doesn't make sense either\n";
         std::string function_name = "AlgebraicFishMesh::node_update()";
         throw OomphLibError(
           error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       AlgebraicMesh::node_update();
     }
References oomph::AlgebraicMesh::node_update(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
Referenced by oomph::AlgebraicRefineableFishMesh< ELEMENT >::node_update().
node_update_in_body()
template<class ELEMENT > void oomph::AlgebraicFishMesh< ELEMENT >::node_update_in_body (const unsigned & t, AlgebraicNode *& node_pt) protected
Algebraic update function for nodes in upper/lower body.
Algebraic update function: Update in (upper or lower) body according to wall shape at time level t (t=0: present; t>0: previous)
   {
     // Pointer to geometric object that represents the fish back:
     GeomObject* back_pt = node_pt->geom_object_pt(unsigned(0));
     // Fixed reference value: x-position of mouth
     double x_mouth = this->Domain_pt->x_mouth();
     // Fixed reference value: Lagrangian coordinate of point
     // over mouth
     double zeta_mouth = this->Domain_pt->xi_nose();
     // Fixed reference value: Lagrangian coordinate of point
     // near tail
     double zeta_near_tail = this->Domain_pt->xi_tail();
     // First reference value: fractional x-position
     double fract_x = node_pt->ref_value(unsigned(0));
     // Second reference value: fractional position along
     // straight line from position on horizontal symmetry line to
     // point on fish back
     double fract_y = node_pt->ref_value(1);
     // Third reference value: Sign (are we above or below the
     // symmetry line?)
     double sign = node_pt->ref_value(2);
     // Get position on fish back
     Vector<double> zeta(back_pt->nlagrangian());
     zeta[0] = zeta_mouth + fract_x * (zeta_near_tail - zeta_mouth);
     Vector<double> r_back(back_pt->ndim());
     back_pt->position(t, zeta, r_back);
     // Get position of point on fish back near tail
     zeta[0] = zeta_near_tail;
     Vector<double> r_near_tail(back_pt->ndim());
     back_pt->position(t, zeta, r_near_tail);
     // Get position on symmetry line
     Vector<double> r_sym(2);
     r_sym[0] = x_mouth + fract_x * (r_near_tail[0] - x_mouth);
     r_sym[1] = 0.0;
     // Assign new nodal coordinate
     node_pt->x(t, 0) = r_sym[0] + fract_y * (r_back[0] - r_sym[0]);
     node_pt->x(t, 1) = sign * (r_sym[1] + fract_y * (r_back[1] - r_sym[1]));
   }
References oomph::AlgebraicNode::geom_object_pt(), oomph::GeomObject::ndim(), oomph::GeomObject::nlagrangian(), oomph::GeomObject::position(), oomph::AlgebraicNode::ref_value(), SYCL::sign(), plotPSD::t, oomph::Node::x(), and Eigen::zeta().
Referenced by oomph::AlgebraicFishMesh< ELEMENT >::algebraic_node_update().
node_update_in_fin()
template<class ELEMENT > void oomph::AlgebraicFishMesh< ELEMENT >::node_update_in_fin (const unsigned & t, AlgebraicNode *& node_pt) protected
Algebraic update function for nodes in upper/lower fin.
Algebraic update function: Update in (upper or lower) fin according to wall shape at time level t (t=0: present; t>0: previous)
   {
     // Pointer to geometric object that represents the fish back:
     GeomObject* back_pt = node_pt->geom_object_pt(unsigned(0));
     // Fixed reference value: End coordinate on fish back
     double zeta_wall = this->Domain_pt->xi_tail();
     // Fixed reference value: x-position of end of tail
     double x_tail = this->Domain_pt->x_fin();
     // Fixed reference value: y-position of end of tail
     double y_tail = this->Domain_pt->y_fin();
     // First reference value: fractional position in x-direction
     double fract_x = node_pt->ref_value(unsigned(0));
     // Second reference value: fractional position along
     // vertical line from position on horizontal symmetry line to
     // point on upper end of tail
     double fract_y = node_pt->ref_value(1);
     // Third reference value: Sign (are we above or below the
     // symmetry line?)
     double sign = node_pt->ref_value(2);
     // Get position on fish back
     Vector<double> zeta(back_pt->nlagrangian());
     zeta[0] = zeta_wall;
     Vector<double> r_back(back_pt->ndim());
     back_pt->position(t, zeta, r_back);
     // y-position on top edge of fin:
     double y_fin_edge = r_back[1] + fract_x * (y_tail - r_back[1]);
     // Assign new nodal coordinate
     node_pt->x(t, 0) = r_back[0] + fract_x * (x_tail - r_back[0]);
     node_pt->x(t, 1) = sign * fract_y * y_fin_edge;
   }
References oomph::AlgebraicNode::geom_object_pt(), oomph::GeomObject::ndim(), oomph::GeomObject::nlagrangian(), oomph::GeomObject::position(), oomph::AlgebraicNode::ref_value(), SYCL::sign(), plotPSD::t, oomph::Node::x(), and Eigen::zeta().
Referenced by oomph::AlgebraicFishMesh< ELEMENT >::algebraic_node_update().
setup_algebraic_node_update()
template<class ELEMENT > void oomph::AlgebraicFishMesh< ELEMENT >::setup_algebraic_node_update protected
Setup algebraic update operation for all nodes (separate function because this task needs to be performed by both constructors)
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Setup algebraic update operation. Nodes are "suspended" from the fish's back and the upper edge of the fin. Nodes in the lower half are placed symmetrically.
   {
 #ifdef PARANOID
     AlgebraicElementBase* lower_body_pt =
       dynamic_cast<AlgebraicElementBase*>(Mesh::element_pt(0));
     if (lower_body_pt == 0)
     {
       std::ostringstream error_message;
       error_message << "Element in AlgebraicFishMesh must be\n"
                     << "derived from AlgebraicElementBase\n"
                     << "but it is of type: "
                     << typeid(Mesh::element_pt(0)).name() << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Read out the number of linear points in the element
     unsigned n_p =
       dynamic_cast<ELEMENT*>(FishMesh<ELEMENT>::Mesh::finite_element_pt(0))
         ->nnode_1d();
     // Element 0: Lower body
     //----------------------
     {
       unsigned ielem = 0;
       FiniteElement* el_pt = Mesh::finite_element_pt(ielem);
       // Loop over rows in y/s_1-direction
       for (unsigned i1 = 0; i1 < n_p; i1++)
       {
         // Loop over rows in x/s_0-direction
         for (unsigned i0 = 0; i0 < n_p; i0++)
         {
           // Local node number
           unsigned jnod = i0 + i1 * n_p;
           // One geometric object is involved in update operation
           Vector<GeomObject*> geom_object_pt(1);
           geom_object_pt[0] = this->Back_pt;
           // The update function requires three parameters:
           Vector<double> ref_value(3);
           // First reference value: fractional x-position
           ref_value[0] = double(i0) / double(n_p - 1);
           // Second reference value: fractional position along
           // straight line from position on horizontal symmetry line to
           // point on fish back
           ref_value[1] = 1.0 - double(i1) / double(n_p - 1);
           // Third reference value: Sign (are we above or below the
           // symmetry line?)
           ref_value[2] = -1.0;
           // Setup algebraic update for node: Pass update information
           dynamic_cast<AlgebraicNode*>(el_pt->node_pt(jnod))
             ->add_node_update_info(this->Lower_body, // enumerated ID
                                    this, // mesh
                                    geom_object_pt, // vector of geom objects
                                    ref_value); // vector of ref. values
         }
       }
     }
     // Element 1: Lower fin
     //---------------------
     {
       unsigned ielem = 1;
       FiniteElement* el_pt = Mesh::finite_element_pt(ielem);
       // Loop over rows in y/s_1-direction
       for (unsigned i1 = 0; i1 < n_p; i1++)
       {
         // Loop over rows in x/s_0-direction
         for (unsigned i0 = 0; i0 < n_p; i0++)
         {
           // Local node number
           unsigned jnod = i0 + i1 * n_p;
           // One geometric object is involved in update operation
           Vector<GeomObject*> geom_object_pt(1);
           geom_object_pt[0] = this->Back_pt;
           // The update function requires three parameters:
           Vector<double> ref_value(3);
           // First reference value: fractional x-position
           ref_value[0] = double(i0) / double(n_p - 1);
           // Second reference value: fractional position along
           // straight line from position on horizontal symmetry line to
           // point on fish back
           ref_value[1] = 1.0 - double(i1) / double(n_p - 1);
           // Third reference value: Sign (are we above or below the
           // symmetry line?)
           ref_value[2] = -1.0;
           // Setup algebraic update for node: Pass update information
           dynamic_cast<AlgebraicNode*>(el_pt->node_pt(jnod))
             ->add_node_update_info(this->Lower_fin, // enumerated ID
                                    this, // mesh
                                    geom_object_pt, // vector of geom objects
                                    ref_value); // vector of ref. values
         }
       }
     }
     // Element 2: Upper body
     //----------------------
     {
       unsigned ielem = 2;
       FiniteElement* el_pt = Mesh::finite_element_pt(ielem);
       // Loop over rows in y/s_1-direction
       for (unsigned i1 = 0; i1 < n_p; i1++)
       {
         // Loop over rows in x/s_0-direction
         for (unsigned i0 = 0; i0 < n_p; i0++)
         {
           // Local node number
           unsigned jnod = i0 + i1 * n_p;
           // One geometric object is involved in update operation
           Vector<GeomObject*> geom_object_pt(1);
           geom_object_pt[0] = this->Back_pt;
           // The update function requires three parameters:
           Vector<double> ref_value(3);
           // First reference value: fractional x-position
           ref_value[0] = double(i0) / double(n_p - 1);
           // Second reference value: fractional position along
           // straight line from position on horizontal symmetry line to
           // point on fish back
           ref_value[1] = double(i1) / double(n_p - 1);
           // Third reference value: Sign (are we above or below the
           // symmetry line?)
           ref_value[2] = 1.0;
           // Setup algebraic update for node: Pass update information
           dynamic_cast<AlgebraicNode*>(el_pt->node_pt(jnod))
             ->add_node_update_info(this->Upper_body, // enumerated ID
                                    this, // mesh
                                    geom_object_pt, // vector of geom objects
                                    ref_value); // vector of ref. values
         }
       }
     }
     // Element 3: Upper fin
     //---------------------
     {
       unsigned ielem = 3;
       FiniteElement* el_pt = Mesh::finite_element_pt(ielem);
       // Loop over rows in y/s_1-direction
       for (unsigned i1 = 0; i1 < n_p; i1++)
       {
         // Loop over rows in x/s_0-direction
         for (unsigned i0 = 0; i0 < n_p; i0++)
         {
           // Local node number
           unsigned jnod = i0 + i1 * n_p;
           // One geometric object is involved in update operation
           Vector<GeomObject*> geom_object_pt(1);
           geom_object_pt[0] = this->Back_pt;
           // The update function requires three parameters:
           Vector<double> ref_value(3);
           // First reference value: fractional x-position
           ref_value[0] = double(i0) / double(n_p - 1);
           // Second reference value: fractional position along
           // straight line from position on horizontal symmetry line to
           // point on fish back
           ref_value[1] = double(i1) / double(n_p - 1);
           // Third reference value: Sign (are we above or below the
           // symmetry line?)
           ref_value[2] = 1.0;
           // Setup algebraic update for node: Pass update information
           dynamic_cast<AlgebraicNode*>(el_pt->node_pt(jnod))
             ->add_node_update_info(this->Upper_fin, // enumerated ID
                                    this, // mesh
                                    geom_object_pt, // vector of geom objects
                                    ref_value); // vector of ref. values
         }
       }
     }
   }
References oomph::Mesh::element_pt(), oomph::Mesh::finite_element_pt(), plotDoE::name, oomph::FiniteElement::node_pt(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::AlgebraicFishMesh< ELEMENT >::AlgebraicFishMesh().
update_node_update()
template<class ELEMENT > void oomph::AlgebraicFishMesh< ELEMENT >::update_node_update (AlgebraicNode *& node_pt) inline virtual
Update the geometric references that are used to update node after mesh adaptation. We're assuming that the GeomObject that specifies the fish back does not have sub-objects, therefore no update is required – all reference values can simply be scaled. We simply paranoid-check that this is actually the case, by checking if locate_zeta() returns the original data.
Implements oomph::AlgebraicMesh.
     {
 #ifdef PARANOID
       // Get the start and end Lagrangian coordinates on the
       // wall from the domain:
       double xi_nose = this->Domain_pt->xi_nose();
       double xi_tail = this->Domain_pt->xi_tail();
       Vector<double> zeta(1);
       zeta[0] = 0.5 * (xi_nose + xi_tail);
       Vector<double> s(1);
       GeomObject* geom_obj_pt = 0;
       this->Back_pt->locate_zeta(zeta, geom_obj_pt, s);
       if ((geom_obj_pt != this->Back_pt) || (s[0] != zeta[0]))
       {
         std::ostringstream error_message;
         error_message << "AlgebraicFishMesh only works with GeomObjects\n"
                       << "that do not contain sub-elements (e.g. GeomObjects\n"
                       << "that represent a wall finite element mesh!\n"
                       << "Back_pt    : " << this->Back_pt << std::endl
                       << "geom_obj_pt: " << geom_obj_pt << std::endl
                       << "s[0]       : " << s[0] << std::endl
                       << "zeta[0]    : " << zeta[0] << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
     }
References oomph::FishMesh< ELEMENT >::Back_pt, oomph::FishMesh< ELEMENT >::Domain_pt, oomph::GeomObject::locate_zeta(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, s, oomph::FishDomain::xi_nose(), oomph::FishDomain::xi_tail(), and Eigen::zeta().
The documentation for this class was generated from the following files:
fish_mesh.template.h
fish_mesh.template.cc