MercuryDPM: CGReadFilesUnitTest.cpp File Reference
CGReadFilesUnitTest.cpp File Reference
#include <CG/TimeAveragedCG.h>
#include "Mercury3D.h"
#include "Math/ExtendedMath.h"
#include "Species/HertzianViscoelasticMindlinSpecies.h"
#include "CG/CG.h"
Classes
class CreateDataAndFStatFiles
Functions
int main ()
Function Documentation
main()
int main ()
 {
     logger(INFO,"Testing if data and fstat files are successfully read by the cgHandler.");
     CreateDataAndFStatFiles problem;
     problem.solve();
     //evaluate cg from data file
     DPMBase evaluate;
     evaluate.setName("CGReadFiles2");
     auto cg = evaluate.cgHandler.copyAndAddObject(CG<CGCoordinates::O>());
     cg->statFile.setName("CGReadFiles2.stat");
     evaluate.cgHandler.restartAndEvaluateDataFiles("CGReadFiles");
     //evaluate time-averaged cg from data file
     DPMBase evaluate2;
     evaluate2.setName("CGReadFiles3");
     auto cg2 = evaluate2.cgHandler.copyAndAddObject(TimeAveragedCG<CGCoordinates::O>());
     cg2->statFile.setName("CGReadFiles3.stat");
     cg2->setTimeMin(0);
     evaluate2.cgHandler.restartAndEvaluateDataFiles("CGReadFiles");
     helpers::check(cg->getPoint(0).getDensity(),1,1e-10, "Density");
     helpers::check(cg->getPoint(0).getMomentum().X,2,1e-10, "Momentum");
     helpers::check(cg2->getPoint(0).getDensity(),1,1e-10, "Time-averaged density");
     helpers::check(cg2->getPoint(0).getMomentum().X,1.5,1e-10, "Time-averaged momentum");
     return 0;
 }
References DPMBase::cgHandler, helpers::check(), BaseHandler< T >::copyAndAddObject(), e(), NurbsUtils::evaluate(), INFO, logger, problem, CGHandler::restartAndEvaluateDataFiles(), and DPMBase::setName().