MercuryDPM: PartialRedux_count.cpp File Reference
PartialRedux_count.cpp File Reference
Variables
Matrix3d m = Matrix3d::Random()
cout<< "Here is the matrix m:"<< endl<< m<< endl;Matrix< ptrdiff_t, 3, 1 > res = (m.array() >= 0.5).rowwise().count()
Variable Documentation
m
Matrix3d m = Matrix3d::Random()
res
cout<< "Here is the matrix m:" << endl << m << endl;Matrix<ptrdiff_t, 3, 1> res = (m.array() >= 0.5).rowwise().count()
Referenced by Eigen::accurateDot(), array_bessel_functions(), array_special_functions(), binom(), Eigen::internal::bload(), Eigen::internal::bstore(), bug_1311(), bug_942(), Eigen::EulerSystem< _AlphaAxis, _BetaAxis, _GammaAxis >::CalcEulerAngles(), Eigen::EulerSystem< _AlphaAxis, _BetaAxis, _GammaAxis >::CalcEulerAngles_imp(), Eigen::MatrixBase< Derived >::canonicalEulerAngles(), check_atan2(), Eigen::MatrixPowerAtomic< MatrixType >::compute(), Eigen::MatrixPower< MatrixType >::compute(), Eigen::MatrixPowerAtomic< MatrixType >::compute2x2(), Eigen::TensorSycl::internal::GeneralVectorTensor< OutScalar, OutAccessor, VectorMapper, TensorMapper, StorageIndex, Properties, KFactor, Vectorizable, is_lhs_vec, IsFinal >::compute_panel(), Eigen::MatrixPowerAtomic< MatrixType >::computeBig(), Eigen::MatrixPower< MatrixType >::computeFracPower(), Eigen::MatrixPower< MatrixType >::computeIntPower(), Eigen::MatrixPowerAtomic< MatrixType >::computePade(), Eigen::internal::imklfft::configure_descriptor(), Eigen::internal::conservative_sparse_sparse_product_impl(), Eigen::internal::convertArrayF32toBF16(), Eigen::internal::convertArrayF32toBF16Col(), Eigen::internal::convertArrayF32toBF16ColVSX(), Eigen::internal::convertArrayF32toBF16VSX(), Eigen::internal::convertF32toBF16(), Eigen::internal::convertF32toBF16VSX(), Eigen::AlignedBox< Scalar_, AmbientDim_ >::corner(), Eigen::VectorwiseOp< ExpressionType, Direction >::cross(), Eigen::Spline< Scalar_, Dim_, Degree_ >::derivatives(), Eigen::PermutationBase< Derived >::determinant(), diagonalmatrices(), Eigen::SparseMatrixBase< Derived >::dot(), dotcw(), dotuw(), BiharmonicTestProblem1::dump_jacobian(), Eigen::MatrixBase< Derived >::eulerAngles(), Eigen::SparseQR_QProduct< SparseQRType, Derived >::evalTo(), Eigen::SPQR_QProduct< SPQRType, Derived >::evalTo(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::extract_kernel(), Eigen::RealQZ< MatrixType_ >::findSmallDiagEntry(), Eigen::RealQZ< MatrixType_ >::findSmallSubdiagEntry(), Eigen::RealSchur< MatrixType_ >::findSmallSubdiagEntry(), Eigen::internal::gemm(), Eigen::internal::gemm_cols(), Eigen::internal::gemm_complex(), Eigen::internal::gemm_complex_cols(), Eigen::internal::gemm_complexMMA(), Eigen::internal::gemm_unrolled_complex_row_iteration(), Eigen::internal::gemm_unrolled_row_iteration(), Eigen::internal::gemmbfloat16(), Eigen::internal::gemmMMA(), Eigen::internal::gemmMMA_cols(), Eigen::internal::gemmMMA_complex_cols(), Eigen::internal::gemmMMAbfloat16(), gemv_bfloat16_col(), gemv_bfloat16_row(), gemv_col(), gemv_complex_col(), gemv_complex_row(), gemv_row(), Eigen::internal::gemvMMA_bfloat16_col(), Eigen::internal::gemvMMA_bfloat16_row(), oomph::FiniteElement::get_dresidual_dnodal_coordinates(), oomph::RefineableElement::get_dresidual_dnodal_coordinates(), oomph::Problem::get_jacobian(), oomph::Problem::get_residuals(), ClumpParticle::getKineticEnergy(), ClumpParticle::getRotationalEnergy(), Eigen::EulerAngles< Scalar_, _System >::inverse(), Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >::inverse(), lerp(), main(), make_companion(), Eigen::SluMatrix::Map(), oomph::DoubleMatrixBase::max_residual(), oomph::ComplexMatrixBase::max_residual(), Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvTimesMatAddMv(), oomph::TElement< 3, NNODE_1D >::nplot_points(), Eigen::internal::gebp_kernel< bfloat16, bfloat16, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()(), Eigen::internal::gebp_kernel< double, double, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()(), Eigen::internal::gebp_kernel< double, std::complex< double >, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()(), Eigen::internal::gebp_kernel< float, float, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()(), Eigen::internal::gebp_kernel< float, std::complex< float >, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()(), Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()(), Eigen::internal::lhs_process_one_packet< nr, LhsProgress, RhsProgress, LhsScalar, RhsScalar, ResScalar, AccPacket, LhsPacket, RhsPacket, ResPacket, GEBPTraits, LinearMapper, DataMapper >::operator()(), Eigen::internal::gebp_kernel< Scalar, Scalar, Index, DataMapper, mr, 8, ConjugateLhs, ConjugateRhs >::operator()(), Eigen::internal::gebp_kernel< std::complex< double >, double, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()(), Eigen::internal::gebp_kernel< std::complex< double >, std::complex< double >, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()(), Eigen::internal::gebp_kernel< std::complex< float >, float, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()(), Eigen::internal::gebp_kernel< std::complex< float >, std::complex< float >, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()(), Eigen::internal::last_row_process_16_packets< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs, SwappedLhsProgress >::operator()(), Eigen::internal::last_row_process_16_packets< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs, 16 >::operator()(), Eigen::internal::tribb_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjLhs, ConjRhs, ResInnerStride, UpLo >::operator()(), Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >::operator*(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::operator*(), Eigen::operator*(), Eigen::UniformScaling< Scalar_ >::operator*(), Eigen::Translation< Scalar_, Dim_ >::operator*(), Eigen::internal::pabs< Packet4f >(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::packet(), Eigen::internal::linspaced_op_impl< Scalar, false >::packetOp(), Eigen::internal::padd(), Eigen::internal::pand< Packet1cd >(), Eigen::internal::pand< Packet8d >(), Eigen::internal::pandnot< Packet1cd >(), Eigen::internal::pconj(), Eigen::internal::pfirst< Packet1cd >(), Eigen::internal::pfirst< Packet2cd >(), Eigen::internal::pfirst< Packet2cf >(), Eigen::internal::pfirst< Packet4cd >(), Eigen::internal::pgather< float, Packet2f >(), Eigen::internal::pgather< int16_t, Packet4s >(), Eigen::internal::pgather< int32_t, Packet2i >(), Eigen::internal::pgather< int8_t, Packet4c >(), Eigen::internal::pgather< int8_t, Packet8c >(), Eigen::internal::pgather< std::complex< double >, Packet1cd >(), Eigen::internal::pgather< uint16_t, Packet4us >(), Eigen::internal::pgather< uint32_t, Packet2ui >(), Eigen::internal::pgather< uint8_t, Packet4uc >(), Eigen::internal::pgather< uint8_t, Packet8uc >(), Eigen::internal::pload< Packet4c >(), Eigen::internal::pload< Packet4uc >(), Eigen::internal::pload_ignore< Packet2cf >(), Eigen::internal::ploadu< Packet4c >(), Eigen::internal::ploadu< Packet4uc >(), Eigen::internal::pmax< Packet4d >(), Eigen::internal::pmax< Packet8f >(), Eigen::internal::pmin< Packet4d >(), Eigen::internal::pmin< Packet8f >(), Eigen::internal::pmul< Packet1cd >(), Eigen::internal::pmul< Packet2cf >(), polyder(), Eigen::internal::por< Packet1cd >(), BoussinesqPreconditioner::preconditioner_solve(), oomph::FSIPreconditioner::preconditioner_solve(), oomph::PseudoElasticPreconditionerSubsidiaryBlockPreconditionerOld::preconditioner_solve(), Eigen::internal::predux_half_dowto4(), Eigen::internal::predux_half_dowto4< Packet8cf >(), Eigen::internal::predux_max< Packet16f >(), Eigen::internal::predux_max< Packet8d >(), Eigen::internal::predux_min< Packet16f >(), Eigen::internal::predux_min< Packet8d >(), Eigen::internal::predux_mul< Packet16f >(), Eigen::internal::predux_mul< Packet8d >(), Eigen::internal::preverse(), Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >::processRow(), Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, false >::processRow(), product(), product_extra(), Eigen::internal::pround< Packet4f >(), Eigen::internal::prsqrt< Packet4f >(), Eigen::internal::pselect(), Eigen::internal::pset1< Packet2cf >(), Eigen::internal::psqrt(), pstoreu_pmadd_complex(), Eigen::internal::pxor< Packet1cd >(), Eigen::LDLT< MatrixType_, UpLo_ >::reconstructedMatrix(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::reconstructedMatrix(), Eigen::PartialPivLU< MatrixType_, PermutationIndex_ >::reconstructedMatrix(), Eigen::MatrixPower< MatrixType >::revertSchur(), func< res, arg1, arg2, TMATVMAT >::run(), Eigen::internal::redux_impl< Func, Evaluator, DefaultTraversal, NoUnrolling >::run(), Eigen::internal::redux_impl< Func, Evaluator, LinearTraversal, NoUnrolling >::run(), Eigen::internal::redux_impl< Func, Evaluator, LinearVectorizedTraversal, NoUnrolling >::run(), Eigen::internal::redux_impl< Func, Evaluator, SliceVectorizedTraversal, Unrolling >::run(), Eigen::internal::redux_impl< Func, Evaluator, LinearVectorizedTraversal, CompleteUnrolling >::run(), Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, LhsMode, LhsOptions >, Transform< Scalar, Dim, RhsMode, RhsOptions >, false >::run(), Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, AffineCompact, LhsOptions >, Transform< Scalar, Dim, Projective, RhsOptions >, true >::run(), Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, Projective, LhsOptions >, Transform< Scalar, Dim, AffineCompact, RhsOptions >, true >::run(), Eigen::internal::conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, ColMajor, ColMajor, ColMajor >::run(), Eigen::internal::conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, RowMajor, ColMajor, ColMajor >::run(), Eigen::internal::conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, ColMajor, RowMajor, ColMajor >::run(), Eigen::internal::conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, RowMajor, RowMajor, ColMajor >::run(), Eigen::internal::conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, ColMajor, ColMajor, RowMajor >::run(), Eigen::internal::conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, RowMajor, ColMajor, RowMajor >::run(), Eigen::internal::conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, ColMajor, RowMajor, RowMajor >::run(), Eigen::internal::conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, RowMajor, RowMajor, RowMajor >::run(), Eigen::internal::sparse_sparse_to_dense_product_selector< Lhs, Rhs, ResultType, ColMajor, ColMajor >::run(), Eigen::internal::sparse_sparse_to_dense_product_selector< Lhs, Rhs, ResultType, RowMajor, ColMajor >::run(), Eigen::internal::sparse_sparse_to_dense_product_selector< Lhs, Rhs, ResultType, ColMajor, RowMajor >::run(), Eigen::internal::sparse_sparse_to_dense_product_selector< Lhs, Rhs, ResultType, RowMajor, RowMajor >::run(), Eigen::internal::sparse_sparse_product_with_pruning_selector< Lhs, Rhs, ResultType, ColMajor, ColMajor, ColMajor >::run(), Eigen::internal::sparse_sparse_product_with_pruning_selector< Lhs, Rhs, ResultType, ColMajor, ColMajor, RowMajor >::run(), Eigen::internal::sparse_sparse_product_with_pruning_selector< Lhs, Rhs, ResultType, RowMajor, RowMajor, RowMajor >::run(), Eigen::internal::sparse_sparse_product_with_pruning_selector< Lhs, Rhs, ResultType, RowMajor, RowMajor, ColMajor >::run(), Eigen::internal::sparse_sparse_product_with_pruning_selector< Lhs, Rhs, ResultType, ColMajor, RowMajor, RowMajor >::run(), Eigen::internal::sparse_sparse_product_with_pruning_selector< Lhs, Rhs, ResultType, RowMajor, ColMajor, RowMajor >::run(), Eigen::internal::sparse_sparse_product_with_pruning_selector< Lhs, Rhs, ResultType, ColMajor, RowMajor, ColMajor >::run(), Eigen::internal::sparse_sparse_product_with_pruning_selector< Lhs, Rhs, ResultType, RowMajor, ColMajor, ColMajor >::run(), Eigen::internal::sparse_solve_triangular_sparse_selector< Lhs, Rhs, Mode, UpLo, ColMajor >::run(), Eigen::internal::compute_inverse_size4< Architecture::Target, float, MatrixType, ResultType >::run(), Eigen::internal::compute_inverse_size4< Architecture::Target, double, MatrixType, ResultType >::run(), Eigen::internal::transform_left_product_impl< Other, AffineCompact, Options, Dim, HDim, HDim, HDim >::run(), Eigen::internal::transform_left_product_impl< Other, Mode, Options, Dim, HDim, Dim, HDim >::run(), Eigen::internal::transform_left_product_impl< Other, AffineCompact, Options, Dim, HDim, Dim, HDim >::run(), Eigen::internal::transform_left_product_impl< Other, Mode, Options, Dim, HDim, Dim, Dim >::run(), Eigen::internal::quat_product< Architecture::Target, Derived, OtherDerived, float >::run(), Eigen::internal::quat_conj< Architecture::Target, Derived, float >::run(), Eigen::internal::rotation_base_generic_product_selector< RotationDerived, DiagonalMatrix< Scalar, Dim, MaxDim >, false >::run(), Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, AlphaType, ColMajor, true >::run(), Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >::run(), Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, false >::run(), Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, ColMajor, false >::run(), Eigen::internal::projective_transform_inverse< TransformType, Projective >::run(), Eigen::internal::transform_right_product_impl< TransformType, MatrixType, 1, RhsCols >::run(), Eigen::internal::transform_right_product_impl< TransformType, MatrixType, 2, RhsCols >::run(), Eigen::internal::transform_right_product_impl< TransformType, MatrixType, 2, 1 >::run(), Eigen::internal::cross3_impl< Architecture::Target, VectorLhs, VectorRhs, float, true >::run(), Eigen::internal::triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, RowMajor, Version >::run(), Eigen::internal::triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, ColMajor, Version >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, Version >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, Version >::run(), Eigen::internal::etor_product_packet_impl< RowMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< ColMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< RowMajor, Dynamic, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< ColMajor, Dynamic, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< RowMajor, 1, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< ColMajor, 1, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::run(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::run(), general_matrix_vector_product_wrapper< Index, Scalar, StorageOrder, ConjugateLhs, ConjugateRhs >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, LhsSelfAdjoint, ConjugateLhs, RhsStorageOrder, RhsSelfAdjoint, ConjugateRhs, RowMajor, ResInnerStride >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, true, ConjugateLhs, RhsStorageOrder, false, ConjugateRhs, ColMajor, ResInnerStride >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, false, ConjugateLhs, RhsStorageOrder, true, ConjugateRhs, ColMajor, ResInnerStride >::run(), Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, RowMajor, ResInnerStride >::run(), Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, LhsIsTriangular, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, RowMajor, ResInnerStride, Version >::run(), Eigen::internal::packed_triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, ColMajor >::run(), Eigen::internal::packed_triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, RowMajor >::run(), Eigen::internal::selfadjoint_matrix_vector_product< Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, Version >::run(), Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, RowMajor, ResInnerStride, UpLo, Version >::run(), Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, UpLo, Version >::run(), Eigen::internal::etor_product_packet_impl< RowMajor, 0, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< ColMajor, 0, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > >::run(), Eigen::SluMatrixMapHelper< SparseMatrixBase< Derived > >::run(), Eigen::internal::pow_impl< ScalarX, ScalarY, true >::run(), Eigen::BDCSVD< MatrixType_, Options_ >::secularEq(), Eigen::PolynomialSolverBase< Scalar_, Deg_ >::selectComplexRoot_withRespectToNorm(), Eigen::PolynomialSolverBase< Scalar_, Deg_ >::selectRealRoot_withRespectToAbsRealPart(), Eigen::PolynomialSolverBase< Scalar_, Deg_ >::selectRealRoot_withRespectToRealPart(), PSD::setDistributionPhiNormal(), Eigen::internal::shuffle(), Eigen::internal::shuffle1(), Eigen::internal::shuffle2(), Eigen::internal::shuffle2< true >(), HomogenisationProblem< ELEMENT >::solve(), oomph::AugmentedBlockFoldLinearSolver::solve(), sparse_basic(), sparse_permutations(), Eigen::internal::sparse_selfadjoint_time_dense_product(), sparse_solvers(), Eigen::internal::sparse_sparse_product_with_pruning_impl(), Eigen::internal::sparse_sparse_to_dense_product_impl(), Eigen::internal::sparse_time_dense_product(), Eigen::internal::stem_function_cos(), Eigen::internal::stem_function_cosh(), Eigen::internal::stem_function_sin(), Eigen::internal::stem_function_sinh(), storeMaddData(), HomogenisationProblem< ELEMENT >::sub_solve(), Eigen::EigenBase< Derived >::subTo(), Eigen::SparseMatrixBase< Derived >::sum(), test_assign(), test_autodiff_scalar(), test_autodiff_vector(), test_coeff_wise(), test_complex_operators(), test_complex_sqrt(), test_diagonal(), test_eigenvalues_direct(), test_matrix_inverse(), test_product(), test_redux(), test_reshape_in_expr(), test_slice_in_expr(), Eigen::internal::BandMatrixBase< Derived >::toDenseMatrix(), Eigen::TriangularBase< Derived >::toDenseMatrix(), Eigen::QuaternionBase< Derived >::toRotationMatrix(), EulerAngles< Scalar_ >::toRotationMatrix(), Eigen::AngleAxis< Scalar_ >::toRotationMatrix(), tpmv(), trsolve(), use_n_times(), Eigen::viewAsCholmod(), and zero_sized_objects().