MercuryDPM: Eigen::internal::digamma_impl< Scalar > Struct Template Reference
Eigen::internal::digamma_impl< Scalar > Struct Template Reference
#include <SpecialFunctionsImpl.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC Scalar run (Scalar x)
Member Function Documentation
run()
template<typename Scalar > static EIGEN_DEVICE_FUNC Scalar Eigen::internal::digamma_impl< Scalar >::run (Scalar x) inline static
{
     /*
      *
      *     Psi (digamma) function (modified for Eigen)
      *
      *
      * SYNOPSIS:
      *
      * double x, y, psi();
      *
      * y = psi( x );
      *
      *
      * DESCRIPTION:
      *
      *              d      -
      *   psi(x)  =  -- ln | (x)
      *              dx
      *
      * is the logarithmic derivative of the gamma function.
      * For integer x,
      *                   n-1
      *                    -
      * psi(n) = -EUL  +   >  1/k.
      *                    -
      *                   k=1
      *
      * If x is negative, it is transformed to a positive argument by the
      * reflection formula  psi(1-x) = psi(x) + pi cot(pi x).
      * For general positive x, the argument is made greater than 10
      * using the recurrence  psi(x+1) = psi(x) + 1/x.
      * Then the following asymptotic expansion is applied:
      *
      *                           inf.   B
      *                            -      2k
      * psi(x) = log(x) - 1/2x -   >   -------
      *                            -        2k
      *                           k=1   2k x
      *
      * where the B2k are Bernoulli numbers.
      *
      * ACCURACY (float):
      *    Relative error (except absolute when |psi| < 1):
      * arithmetic   domain     # trials      peak         rms
      *    IEEE      0,30        30000       1.3e-15     1.4e-16
      *    IEEE      -30,0       40000       1.5e-15     2.2e-16
      *
      * ACCURACY (double):
      *    Absolute error,  relative when |psi| > 1 :
      * arithmetic   domain     # trials      peak         rms
      *    IEEE      -33,0        30000      8.2e-7      1.2e-7
      *    IEEE      0,33        100000      7.3e-7      7.7e-8
      *
      * ERROR MESSAGES:
      *     message         condition      value returned
      * psi singularity    x integer <=0      INFINITY
      */
     Scalar p, q, nz, s, w, y;
     bool negative = false;
     const Scalar nan = NumTraits<Scalar>::quiet_NaN();
     const Scalar m_pi = Scalar(EIGEN_PI);
     const Scalar zero = Scalar(0);
     const Scalar one = Scalar(1);
     const Scalar half = Scalar(0.5);
     nz = zero;
     if (x <= zero) {
       negative = true;
       q = x;
       p = numext::floor(q);
       if (p == q) {
         return nan;
       }
       /* Remove the zeros of tan(m_pi x)
        * by subtracting the nearest integer from x
        */
       nz = q - p;
       if (nz != half) {
         if (nz > half) {
           p += one;
           nz = q - p;
         }
         nz = m_pi / numext::tan(m_pi * nz);
       } else {
         nz = zero;
       }
       x = one - x;
     }
     /* use the recurrence psi(x+1) = psi(x) + 1/x. */
     s = x;
     w = zero;
     while (s < Scalar(10)) {
       w += one / s;
       s += one;
     }
     y = digamma_impl_maybe_poly<Scalar>::run(s);
     y = numext::log(s) - (half / s) - y - w;
     return (negative) ? y - nz : y;
   }
References EIGEN_PI, Eigen::numext::floor(), Eigen::numext::log(), Mesh_Parameters::nz, p, Eigen::numext::q, Eigen::internal::digamma_impl_maybe_poly< Scalar >::run(), s, Eigen::numext::tan(), w, Eigen::numext::x, Eigen::internal::y, and zero().
Referenced by Eigen::internal::igammac_cf_impl< Scalar, mode >::run(), and Eigen::internal::igamma_series_impl< Scalar, mode >::run().
The documentation for this struct was generated from the following file:
SpecialFunctionsImpl.h