MercuryDPM: Eigen::EulerAngles< Scalar_, _System > Class Template Reference
Eigen::EulerAngles< Scalar_, _System > Class Template Reference
Represents a rotation in a 3 dimensional space as three Euler angles.
#include <EulerAngles.h>
Public Types
typedef RotationBase< EulerAngles< Scalar_, _System >, 3 > Base
typedef Scalar_ Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef _System System
typedef Matrix< Scalar, 3, 3 > Matrix3
typedef Matrix< Scalar, 3, 1 > Vector3
typedef Quaternion< Scalar > QuaternionType
typedef AngleAxis< Scalar > AngleAxisType
Public Types inherited from Eigen::RotationBase< EulerAngles< Scalar_, _System >, 3 >
enum
typedef internal::traits< EulerAngles< Scalar_, _System > >::Scalar Scalar
typedef Matrix< Scalar, Dim, Dim > RotationMatrixType
typedef Matrix< Scalar, Dim, 1 > VectorType
Public Member Functions
EulerAngles ()
EulerAngles (const Scalar &alpha, const Scalar &beta, const Scalar &gamma)
EulerAngles (const Scalar *data)
template<typename Derived >
EulerAngles (const MatrixBase< Derived > &other)
template<typename Derived >
EulerAngles (const RotationBase< Derived, 3 > &rot)
const Vector3 & angles () const
Vector3 & angles ()
Scalar alpha () const
Scalar & alpha ()
Scalar beta () const
Scalar & beta ()
Scalar gamma () const
Scalar & gamma ()
EulerAngles inverse () const
EulerAngles operator- () const
template<class Derived >
EulerAngles & operator= (const MatrixBase< Derived > &other)
template<typename Derived >
EulerAngles & operator= (const RotationBase< Derived, 3 > &rot)
bool isApprox (const EulerAngles &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
Matrix3 toRotationMatrix () const
operator QuaternionType () const
template<typename NewScalarType >
EulerAngles< NewScalarType, System > cast () const
Public Member Functions inherited from Eigen::RotationBase< EulerAngles< Scalar_, _System >, 3 >
EIGEN_DEVICE_FUNC const EulerAngles< Scalar_, _System > & derived () const
EIGEN_DEVICE_FUNC EulerAngles< Scalar_, _System > & derived ()
EIGEN_DEVICE_FUNC RotationMatrixType toRotationMatrix () const
EIGEN_DEVICE_FUNC RotationMatrixType matrix () const
EIGEN_DEVICE_FUNC EulerAngles< Scalar_, _System > inverse () const
EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Isometry > operator* (const Translation< Scalar, Dim > &t) const
EIGEN_DEVICE_FUNC RotationMatrixType operator* (const UniformScaling< Scalar > &s) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::rotation_base_generic_product_selector< EulerAngles< Scalar_, _System >, OtherDerived, OtherDerived::IsVectorAtCompileTime >::ReturnType operator* (const EigenBase< OtherDerived > &e) const
EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode > operator* (const Transform< Scalar, Dim, Mode, Options > &t) const
EIGEN_DEVICE_FUNC VectorType _transformVector (const OtherVectorType &v) const
Static Public Member Functions
static Vector3 AlphaAxisVector ()
static Vector3 BetaAxisVector ()
static Vector3 GammaAxisVector ()
Private Attributes
Vector3 m_angles
Friends
std::ostream & operator<< (std::ostream &s, const EulerAngles< Scalar, System > &eulerAngles)
Detailed Description
template<typename Scalar_, class _System>
class Eigen::EulerAngles< Scalar_, _System >
Represents a rotation in a 3 dimensional space as three Euler angles.
Euler rotation is a set of three rotation of three angles over three fixed axes, defined by the EulerSystem given as a template parameter.
Here is how intrinsic Euler angles works:
first, rotate the axes system over the alpha axis in angle alpha
then, rotate the axes system over the beta axis(which was rotated in the first stage) in angle beta
then, rotate the axes system over the gamma axis(which was rotated in the two stages above) in angle gamma
Note
This class support only intrinsic Euler angles for simplicity, see EulerSystem how to easily overcome this for extrinsic systems.
Rotation representation and conversions
It has been proved(see Wikipedia link below) that every rotation can be represented by Euler angles, but there is no single representation (e.g. unlike rotation matrices). Therefore, you can convert from Eigen rotation and to them (including rotation matrices, which is not called "rotations" by Eigen design).
Euler angles usually used for:
convenient human representation of rotation, especially in interactive GUI.
gimbal systems and robotics
efficient encoding(i.e. 3 floats only) of rotation for network protocols.
However, Euler angles are slow comparing to quaternion or matrices, because their unnatural math definition, although it's simple for human. To overcome this, this class provide easy movement from the math friendly representation to the human friendly representation, and vise-versa.
All the user need to do is a safe simple C++ type conversion, and this class take care for the math. Additionally, some axes related computation is done in compile time.
Euler angles ranges in conversions
Rotations representation as EulerAngles are not single (unlike matrices), and even have infinite EulerAngles representations.
For example, add or subtract 2*PI from either angle of EulerAngles and you'll get the same rotation. This is the general reason for infinite representation, but it's not the only general reason for not having a single representation.
When converting rotation to EulerAngles, this class convert it to specific ranges When converting some rotation to EulerAngles, the rules for ranges are as follow:
If the rotation we converting from is an EulerAngles (even when it represented as RotationBase explicitly), angles ranges are undefined.
otherwise, alpha and gamma angles will be in the range [-PI, PI].
As for Beta angle:
If the system is Tait-Bryan, the beta angle will be in the range [-PI/2, PI/2].
otherwise:
If the beta axis is positive, the beta angle will be in the range [0, PI]
If the beta axis is negative, the beta angle will be in the range [-PI, 0]
See also
EulerAngles(const MatrixBase<Derived>&)
EulerAngles(const RotationBase<Derived, 3>&)
Convenient user typedefs
Convenient typedefs for EulerAngles exist for float and double scalar, in a form of EulerAngles{A}{B}{C}{scalar}, e.g. EulerAnglesXYZd, EulerAnglesZYZf.
Only for positive axes{+x,+y,+z} Euler systems are have convenient typedef. If you need negative axes{-x,-y,-z}, it is recommended to create you own typedef with a word that represent what you need.
Example
// This file is part of Eigen, a lightweight C++ template library
// for linear algebra.
//
// Copyright (C) 2015 Tal Hadad <tal_hd@hotmail.com>
//
// This Source Code Form is subject to the terms of the Mozilla
// Public License v. 2.0. If a copy of the MPL was not distributed
// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
#include "main.h"
EIGEN_DISABLE_DEPRECATED_WARNING
#include <unsupported/Eigen/EulerAngles>
using namespace Eigen;
// Unfortunately, we need to specialize it in order to work. (We could add it in main.h test framework)
template <typename Scalar, class System>
bool verifyIsApprox(const Eigen::EulerAngles<Scalar, System>& a, const Eigen::EulerAngles<Scalar, System>& b) {
  return verifyIsApprox(a.angles(), b.angles());
}
// Verify that x is in the approxed range [a, b]
#define VERIFY_APPROXED_RANGE(a, x, b)   \
  do {                                   \
    VERIFY_IS_APPROX_OR_LESS_THAN(a, x); \
    VERIFY_IS_APPROX_OR_LESS_THAN(x, b); \
  } while (0)
const char X = EULER_X;
const char Y = EULER_Y;
const char Z = EULER_Z;
template <typename Scalar, class EulerSystem>
void verify_euler(const EulerAngles<Scalar, EulerSystem>& e) {
  typedef EulerAngles<Scalar, EulerSystem> EulerAnglesType;
  typedef Matrix<Scalar, 3, 3> Matrix3;
  typedef Matrix<Scalar, 3, 1> Vector3;
  typedef Quaternion<Scalar> QuaternionType;
  typedef AngleAxis<Scalar> AngleAxisType;
  const Scalar ONE = Scalar(1);
  const Scalar HALF_PI = Scalar(EIGEN_PI / 2);
  const Scalar PI = Scalar(EIGEN_PI);
  // It's very important calc the acceptable precision depending on the distance from the pole.
  const Scalar longitudeRadius = std::abs(EulerSystem::IsTaitBryan ? std::cos(e.beta()) : std::sin(e.beta()));
  Scalar precision = test_precision<Scalar>() / longitudeRadius;
  Scalar betaRangeStart, betaRangeEnd;
  if (EulerSystem::IsTaitBryan) {
    betaRangeStart = -HALF_PI;
    betaRangeEnd = HALF_PI;
  } else {
    if (!EulerSystem::IsBetaOpposite) {
      betaRangeStart = 0;
      betaRangeEnd = PI;
    } else {
      betaRangeStart = -PI;
      betaRangeEnd = 0;
    }
  }
  const Vector3 I_ = EulerAnglesType::AlphaAxisVector();
  const Vector3 J_ = EulerAnglesType::BetaAxisVector();
  const Vector3 K_ = EulerAnglesType::GammaAxisVector();
  // Is approx checks
  VERIFY(e.isApprox(e));
  VERIFY_IS_APPROX(e, e);
  VERIFY_IS_NOT_APPROX(e, EulerAnglesType(e.alpha() + ONE, e.beta() + ONE, e.gamma() + ONE));
  const Matrix3 m(e);
  VERIFY_IS_APPROX(Scalar(m.determinant()), ONE);
  EulerAnglesType ebis(m);
  // When no roll(acting like polar representation), we have the best precision.
  // One of those cases is when the Euler angles are on the pole, and because it's singular case,
  //  the computation returns no roll.
  if (ebis.beta() == 0) precision = test_precision<Scalar>();
  // Check that eabis in range
  VERIFY_APPROXED_RANGE(-PI, ebis.alpha(), PI);
  VERIFY_APPROXED_RANGE(betaRangeStart, ebis.beta(), betaRangeEnd);
  VERIFY_APPROXED_RANGE(-PI, ebis.gamma(), PI);
  const Matrix3 mbis(AngleAxisType(ebis.alpha(), I_) * AngleAxisType(ebis.beta(), J_) *
                     AngleAxisType(ebis.gamma(), K_));
  VERIFY_IS_APPROX(Scalar(mbis.determinant()), ONE);
  VERIFY_IS_APPROX(mbis, ebis.toRotationMatrix());
  /*std::cout << "===================\n" <<
    "e: " << e << std::endl <<
    "eabis: " << eabis.transpose() << std::endl <<
    "m: " << m << std::endl <<
    "mbis: " << mbis << std::endl <<
    "X: " << (m * Vector3::UnitX()).transpose() << std::endl <<
    "X: " << (mbis * Vector3::UnitX()).transpose() << std::endl;*/
  VERIFY(m.isApprox(mbis, precision));
  // Test if ea and eabis are the same
  // Need to check both singular and non-singular cases
  // There are two singular cases.
  // 1. When I==K and sin(ea(1)) == 0
  // 2. When I!=K and cos(ea(1)) == 0
  // TODO: Make this test work well, and use range saturation function.
  /*// If I==K, and ea[1]==0, then there no unique solution.
  // The remark apply in the case where I!=K, and |ea[1]| is close to +-pi/2.
  if( (i!=k || ea[1]!=0) && (i==k || !internal::isApprox(abs(ea[1]),Scalar(EIGEN_PI/2),test_precision<Scalar>())) )
      VERIFY_IS_APPROX(ea, eabis);*/
  // Quaternions
  const QuaternionType q(e);
  ebis = q;
  const QuaternionType qbis(ebis);
  VERIFY(internal::isApprox<Scalar>(std::abs(q.dot(qbis)), ONE, precision));
  // VERIFY_IS_APPROX(eabis, eabis2);// Verify that the euler angles are still the same
  // A suggestion for simple product test when will be supported.
  /*EulerAnglesType e2(PI/2, PI/2, PI/2);
  Matrix3 m2(e2);
  VERIFY_IS_APPROX(e*e2, m*m2);*/
}
template <signed char A, signed char B, signed char C, typename Scalar>
void verify_euler_vec(const Matrix<Scalar, 3, 1>& ea) {
  verify_euler(EulerAngles<Scalar, EulerSystem<A, B, C> >(ea[0], ea[1], ea[2]));
}
template <signed char A, signed char B, signed char C, typename Scalar>
void verify_euler_all_neg(const Matrix<Scalar, 3, 1>& ea) {
  verify_euler_vec<+A, +B, +C>(ea);
  verify_euler_vec<+A, +B, -C>(ea);
  verify_euler_vec<+A, -B, +C>(ea);
  verify_euler_vec<+A, -B, -C>(ea);
  verify_euler_vec<-A, +B, +C>(ea);
  verify_euler_vec<-A, +B, -C>(ea);
  verify_euler_vec<-A, -B, +C>(ea);
  verify_euler_vec<-A, -B, -C>(ea);
}
template <typename Scalar>
void check_all_var(const Matrix<Scalar, 3, 1>& ea) {
  verify_euler_all_neg<X, Y, Z>(ea);
  verify_euler_all_neg<X, Y, X>(ea);
  verify_euler_all_neg<X, Z, Y>(ea);
  verify_euler_all_neg<X, Z, X>(ea);
  verify_euler_all_neg<Y, Z, X>(ea);
  verify_euler_all_neg<Y, Z, Y>(ea);
  verify_euler_all_neg<Y, X, Z>(ea);
  verify_euler_all_neg<Y, X, Y>(ea);
  verify_euler_all_neg<Z, X, Y>(ea);
  verify_euler_all_neg<Z, X, Z>(ea);
  verify_euler_all_neg<Z, Y, X>(ea);
  verify_euler_all_neg<Z, Y, Z>(ea);
}
template <typename Scalar>
void check_singular_cases(const Scalar& singularBeta) {
  typedef Matrix<Scalar, 3, 1> Vector3;
  const Scalar PI = Scalar(EIGEN_PI);
  for (Scalar epsilon = NumTraits<Scalar>::epsilon(); epsilon < 1; epsilon *= Scalar(1.2)) {
    check_all_var(Vector3(PI / 4, singularBeta, PI / 3));
    check_all_var(Vector3(PI / 4, singularBeta - epsilon, PI / 3));
    check_all_var(Vector3(PI / 4, singularBeta - Scalar(1.5) * epsilon, PI / 3));
    check_all_var(Vector3(PI / 4, singularBeta - 2 * epsilon, PI / 3));
    check_all_var(Vector3(PI * Scalar(0.8), singularBeta - epsilon, Scalar(0.9) * PI));
    check_all_var(Vector3(PI * Scalar(-0.9), singularBeta + epsilon, PI * Scalar(0.3)));
    check_all_var(Vector3(PI * Scalar(-0.6), singularBeta + Scalar(1.5) * epsilon, PI * Scalar(0.3)));
    check_all_var(Vector3(PI * Scalar(-0.5), singularBeta + 2 * epsilon, PI * Scalar(0.4)));
    check_all_var(Vector3(PI * Scalar(0.9), singularBeta + epsilon, Scalar(0.8) * PI));
  }
  // This one for sanity, it had a problem with near pole cases in float scalar.
  check_all_var(Vector3(PI * Scalar(0.8), singularBeta - Scalar(1E-6), Scalar(0.9) * PI));
}
template <typename Scalar>
void eulerangles_manual() {
  typedef Matrix<Scalar, 3, 1> Vector3;
  typedef Matrix<Scalar, Dynamic, 1> VectorX;
  const Vector3 Zero = Vector3::Zero();
  const Scalar PI = Scalar(EIGEN_PI);
  check_all_var(Zero);
  // singular cases
  check_singular_cases(PI / 2);
  check_singular_cases(-PI / 2);
  check_singular_cases(Scalar(0));
  check_singular_cases(Scalar(-0));
  check_singular_cases(PI);
  check_singular_cases(-PI);
  // non-singular cases
  VectorX alpha = VectorX::LinSpaced(20, Scalar(-0.99) * PI, PI);
  VectorX beta = VectorX::LinSpaced(20, Scalar(-0.49) * PI, Scalar(0.49) * PI);
  VectorX gamma = VectorX::LinSpaced(20, Scalar(-0.99) * PI, PI);
  for (int i = 0; i < alpha.size(); ++i) {
    for (int j = 0; j < beta.size(); ++j) {
      for (int k = 0; k < gamma.size(); ++k) {
        check_all_var(Vector3(alpha(i), beta(j), gamma(k)));
      }
    }
  }
}
template <typename Scalar>
void eulerangles_rand() {
  typedef Matrix<Scalar, 3, 3> Matrix3;
  typedef Matrix<Scalar, 3, 1> Vector3;
  typedef Array<Scalar, 3, 1> Array3;
  typedef Quaternion<Scalar> Quaternionx;
  typedef AngleAxis<Scalar> AngleAxisType;
  Scalar a = internal::random<Scalar>(-Scalar(EIGEN_PI), Scalar(EIGEN_PI));
  Quaternionx q1;
  q1 = AngleAxisType(a, Vector3::Random().normalized());
  Matrix3 m;
  m = q1;
  Vector3 ea = m.eulerAngles(0, 1, 2);
  check_all_var(ea);
  ea = m.eulerAngles(0, 1, 0);
  check_all_var(ea);
  // Check with purely random Quaternion:
  q1.coeffs() = Quaternionx::Coefficients::Random().normalized();
  m = q1;
  ea = m.eulerAngles(0, 1, 2);
  check_all_var(ea);
  ea = m.eulerAngles(0, 1, 0);
  check_all_var(ea);
  // Check with random angles in range [0:pi]x[-pi:pi]x[-pi:pi].
  ea = (Array3::Random() + Array3(1, 0, 0)) * Scalar(EIGEN_PI) * Array3(0.5, 1, 1);
  check_all_var(ea);
  ea[2] = ea[0] = internal::random<Scalar>(0, Scalar(EIGEN_PI));
  check_all_var(ea);
  ea[0] = ea[1] = internal::random<Scalar>(0, Scalar(EIGEN_PI));
  check_all_var(ea);
  ea[1] = 0;
  check_all_var(ea);
  ea.head(2).setZero();
  check_all_var(ea);
  ea.setZero();
  check_all_var(ea);
}
EIGEN_DECLARE_TEST(EulerAngles) {
  // Simple cast test
  EulerAnglesXYZd onesEd(1, 1, 1);
  EulerAnglesXYZf onesEf = onesEd.cast<float>();
  VERIFY_IS_APPROX(onesEd, onesEf.cast<double>());
  // Simple Construction from Vector3 test
  VERIFY_IS_APPROX(onesEd, EulerAnglesXYZd(Vector3d::Ones()));
  CALL_SUBTEST_1(eulerangles_manual<float>());
  CALL_SUBTEST_2(eulerangles_manual<double>());
  for (int i = 0; i < g_repeat; i++) {
    CALL_SUBTEST_3(eulerangles_rand<float>());
    CALL_SUBTEST_4(eulerangles_rand<double>());
  }
  // TODO: Add tests for auto diff
  // TODO: Add tests for complex numbers
}
Output:
Additional reading
If you're want to get more idea about how Euler system work in Eigen see EulerSystem.
More information about Euler angles: https://en.wikipedia.org/wiki/Euler_angles
Template Parameters
Scalar_ the scalar type, i.e. the type of the angles.
_System the EulerSystem to use, which represents the axes of rotation.
Member Typedef Documentation
AngleAxisType
template<typename Scalar_ , class _System > typedef AngleAxis<Scalar> Eigen::EulerAngles< Scalar_, _System >::AngleAxisType
the equivalent angle-axis type
Base
template<typename Scalar_ , class _System > typedef RotationBase<EulerAngles<Scalar_, _System>, 3> Eigen::EulerAngles< Scalar_, _System >::Base
Matrix3
template<typename Scalar_ , class _System > typedef Matrix<Scalar, 3, 3> Eigen::EulerAngles< Scalar_, _System >::Matrix3
the equivalent rotation matrix type
QuaternionType
template<typename Scalar_ , class _System > typedef Quaternion<Scalar> Eigen::EulerAngles< Scalar_, _System >::QuaternionType
the equivalent quaternion type
RealScalar
template<typename Scalar_ , class _System > typedef NumTraits<Scalar>::Real Eigen::EulerAngles< Scalar_, _System >::RealScalar
Scalar
template<typename Scalar_ , class _System > typedef Scalar_ Eigen::EulerAngles< Scalar_, _System >::Scalar
the scalar type of the angles
System
template<typename Scalar_ , class _System > typedef _System Eigen::EulerAngles< Scalar_, _System >::System
the EulerSystem to use, which represents the axes of rotation.
Vector3
template<typename Scalar_ , class _System > typedef Matrix<Scalar, 3, 1> Eigen::EulerAngles< Scalar_, _System >::Vector3
the equivalent 3 dimension vector type
Constructor & Destructor Documentation
EulerAngles() [1/5]
template<typename Scalar_ , class _System > Eigen::EulerAngles< Scalar_, _System >::EulerAngles () inline
Default constructor without initialization.
 {}
EulerAngles() [2/5]
template<typename Scalar_ , class _System > Eigen::EulerAngles< Scalar_, _System >::EulerAngles (const Scalar & alpha, const Scalar & beta, const Scalar & gamma) inline
Constructs and initialize an EulerAngles (alpha, beta, gamma).
 : m_angles(alpha, beta, gamma) {}
EulerAngles() [3/5]
template<typename Scalar_ , class _System > Eigen::EulerAngles< Scalar_, _System >::EulerAngles (const Scalar * data) inline explicit
Constructs and initialize an EulerAngles from the array data {alpha, beta, gamma}
 : m_angles(data) {}
EulerAngles() [4/5]
template<typename Scalar_ , class _System > template<typename Derived > Eigen::EulerAngles< Scalar_, _System >::EulerAngles (const MatrixBase< Derived > & other) inline explicit
Constructs and initializes an EulerAngles from either:
a 3x3 rotation matrix expression(i.e. pure orthogonal matrix with determinant of +1),
a 3D vector expression representing Euler angles.
Note
If other is a 3x3 rotation matrix, the angles range rules will be as follow:
Alpha and gamma angles will be in the range [-PI, PI].
As for Beta angle:
If the system is Tait-Bryan, the beta angle will be in the range [-PI/2, PI/2].
otherwise:
If the beta axis is positive, the beta angle will be in the range [0, PI]
If the beta axis is negative, the beta angle will be in the range [-PI, 0]
{
     *this = other;
   }
EulerAngles() [5/5]
template<typename Scalar_ , class _System > template<typename Derived > Eigen::EulerAngles< Scalar_, _System >::EulerAngles (const RotationBase< Derived, 3 > & rot) inline
Constructs and initialize Euler angles from a rotation rot.
Note
If rot is an EulerAngles (even when it represented as RotationBase explicitly), angles ranges are undefined. Otherwise, alpha and gamma angles will be in the range [-PI, PI].
As for Beta angle:
If the system is Tait-Bryan, the beta angle will be in the range [-PI/2, PI/2].
otherwise:
If the beta axis is positive, the beta angle will be in the range [0, PI]
If the beta axis is negative, the beta angle will be in the range [-PI, 0]
{
     System::CalcEulerAngles(*this, rot.toRotationMatrix());
   }
References rot().
Member Function Documentation
alpha() [1/2]
template<typename Scalar_ , class _System > Scalar& Eigen::EulerAngles< Scalar_, _System >::alpha () inline
Returns
A read-write reference to the angle of the first angle.
 { return m_angles[0]; }
References Eigen::EulerAngles< Scalar_, _System >::m_angles.
alpha() [2/2]
template<typename Scalar_ , class _System > Scalar Eigen::EulerAngles< Scalar_, _System >::alpha () const inline
Returns
The value of the first angle.
 { return m_angles[0]; }
References Eigen::EulerAngles< Scalar_, _System >::m_angles.
Referenced by Eigen::EulerAngles< Scalar_, _System >::operator QuaternionType().
AlphaAxisVector()
template<typename Scalar_ , class _System > static Vector3 Eigen::EulerAngles< Scalar_, _System >::AlphaAxisVector () inline static
Returns
the axis vector of the first (alpha) rotation
{
     const Vector3& u = Vector3::Unit(System::AlphaAxisAbs - 1);
     return System::IsAlphaOpposite ? -u : u;
   }
Referenced by Eigen::EulerAngles< Scalar_, _System >::operator QuaternionType().
angles() [1/2]
template<typename Scalar_ , class _System > Vector3& Eigen::EulerAngles< Scalar_, _System >::angles () inline
Returns
A read-write reference to the angle values stored in a vector (alpha, beta, gamma).
 { return m_angles; }
References Eigen::EulerAngles< Scalar_, _System >::m_angles.
angles() [2/2]
template<typename Scalar_ , class _System > const Vector3& Eigen::EulerAngles< Scalar_, _System >::angles () const inline
Returns
The angle values stored in a vector (alpha, beta, gamma).
 { return m_angles; }
References Eigen::EulerAngles< Scalar_, _System >::m_angles.
Referenced by Eigen::EulerAngles< Scalar_, _System >::cast(), and Eigen::EulerAngles< Scalar_, _System >::isApprox().
beta() [1/2]
template<typename Scalar_ , class _System > Scalar& Eigen::EulerAngles< Scalar_, _System >::beta () inline
Returns
A read-write reference to the angle of the second angle.
 { return m_angles[1]; }
References Eigen::EulerAngles< Scalar_, _System >::m_angles.
beta() [2/2]
template<typename Scalar_ , class _System > Scalar Eigen::EulerAngles< Scalar_, _System >::beta () const inline
Returns
The value of the second angle.
 { return m_angles[1]; }
References Eigen::EulerAngles< Scalar_, _System >::m_angles.
Referenced by Eigen::EulerAngles< Scalar_, _System >::operator QuaternionType().
BetaAxisVector()
template<typename Scalar_ , class _System > static Vector3 Eigen::EulerAngles< Scalar_, _System >::BetaAxisVector () inline static
Returns
the axis vector of the second (beta) rotation
{
     const Vector3& u = Vector3::Unit(System::BetaAxisAbs - 1);
     return System::IsBetaOpposite ? -u : u;
   }
Referenced by Eigen::EulerAngles< Scalar_, _System >::operator QuaternionType().
cast()
template<typename Scalar_ , class _System > template<typename NewScalarType > EulerAngles<NewScalarType, System> Eigen::EulerAngles< Scalar_, _System >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
{
     EulerAngles<NewScalarType, System> e;
     e.angles() = angles().template cast<NewScalarType>();
     return e;
   }
References Eigen::EulerAngles< Scalar_, _System >::angles(), and e().
gamma() [1/2]
template<typename Scalar_ , class _System > Scalar& Eigen::EulerAngles< Scalar_, _System >::gamma () inline
Returns
A read-write reference to the angle of the third angle.
 { return m_angles[2]; }
References Eigen::EulerAngles< Scalar_, _System >::m_angles.
gamma() [2/2]
template<typename Scalar_ , class _System > Scalar Eigen::EulerAngles< Scalar_, _System >::gamma () const inline
Returns
The value of the third angle.
 { return m_angles[2]; }
References Eigen::EulerAngles< Scalar_, _System >::m_angles.
Referenced by Eigen::EulerAngles< Scalar_, _System >::operator QuaternionType().
GammaAxisVector()
template<typename Scalar_ , class _System > static Vector3 Eigen::EulerAngles< Scalar_, _System >::GammaAxisVector () inline static
Returns
the axis vector of the third (gamma) rotation
{
     const Vector3& u = Vector3::Unit(System::GammaAxisAbs - 1);
     return System::IsGammaOpposite ? -u : u;
   }
Referenced by Eigen::EulerAngles< Scalar_, _System >::operator QuaternionType().
inverse()
template<typename Scalar_ , class _System > EulerAngles Eigen::EulerAngles< Scalar_, _System >::inverse () const inline
Returns
The Euler angles rotation inverse (which is as same as the negative), (-alpha, -beta, -gamma).
{
     EulerAngles res;
     res.m_angles = -m_angles;
     return res;
   }
References Eigen::EulerAngles< Scalar_, _System >::m_angles, and res.
Referenced by Eigen::EulerAngles< Scalar_, _System >::operator-().
isApprox()
template<typename Scalar_ , class _System > bool Eigen::EulerAngles< Scalar_, _System >::isApprox (const EulerAngles< Scalar_, _System > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See also
MatrixBase::isApprox()
{
     return angles().isApprox(other.angles(), prec);
   }
References Eigen::EulerAngles< Scalar_, _System >::angles().
operator QuaternionType()
template<typename Scalar_ , class _System > Eigen::EulerAngles< Scalar_, _System >::operator QuaternionType () const inline
Convert the Euler angles to quaternion.
{
     return AngleAxisType(alpha(), AlphaAxisVector()) * AngleAxisType(beta(), BetaAxisVector()) *
            AngleAxisType(gamma(), GammaAxisVector());
   }
References Eigen::EulerAngles< Scalar_, _System >::alpha(), Eigen::EulerAngles< Scalar_, _System >::AlphaAxisVector(), Eigen::EulerAngles< Scalar_, _System >::beta(), Eigen::EulerAngles< Scalar_, _System >::BetaAxisVector(), Eigen::EulerAngles< Scalar_, _System >::gamma(), and Eigen::EulerAngles< Scalar_, _System >::GammaAxisVector().
operator-()
template<typename Scalar_ , class _System > EulerAngles Eigen::EulerAngles< Scalar_, _System >::operator- (void) const inline
Returns
The Euler angles rotation negative (which is as same as the inverse), (-alpha, -beta, -gamma).
 { return inverse(); }
References Eigen::EulerAngles< Scalar_, _System >::inverse().
operator=() [1/2]
template<typename Scalar_ , class _System > template<class Derived > EulerAngles& Eigen::EulerAngles< Scalar_, _System >::operator= (const MatrixBase< Derived > & other) inline
Set *this from either:
a 3x3 rotation matrix expression(i.e. pure orthogonal matrix with determinant of +1),
a 3D vector expression representing Euler angles.
See EulerAngles(const MatrixBase<Derived, 3>&) for more information about angles ranges output.
{
     EIGEN_STATIC_ASSERT(
         (internal::is_same<Scalar, typename Derived::Scalar>::value),
         YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY)
     internal::eulerangles_assign_impl<System, Derived>::run(*this, other.derived());
     return *this;
   }
References EIGEN_STATIC_ASSERT, and run().
operator=() [2/2]
template<typename Scalar_ , class _System > template<typename Derived > EulerAngles& Eigen::EulerAngles< Scalar_, _System >::operator= (const RotationBase< Derived, 3 > & rot) inline
Set *this from a rotation.
See EulerAngles(const RotationBase<Derived, 3>&) for more information about angles ranges output.
{
     System::CalcEulerAngles(*this, rot.toRotationMatrix());
     return *this;
   }
References rot().
toRotationMatrix()
template<typename Scalar_ , class _System > Matrix3 Eigen::EulerAngles< Scalar_, _System >::toRotationMatrix (void) const inline
Returns
an equivalent 3x3 rotation matrix.
{
     // TODO: Calc it faster
     return static_cast<QuaternionType>(*this).toRotationMatrix();
   }
References Eigen::QuaternionBase< Derived >::toRotationMatrix().
Referenced by EulerAngles< Scalar_ >::operator QuaternionType().
Friends And Related Function Documentation
operator<<
template<typename Scalar_ , class _System > std::ostream& operator<< (std::ostream & s, const EulerAngles< Scalar, System > & eulerAngles) friend
{
     s << eulerAngles.angles().transpose();
     return s;
   }
Member Data Documentation
m_angles
template<typename Scalar_ , class _System > Vector3 Eigen::EulerAngles< Scalar_, _System >::m_angles private
Referenced by Eigen::EulerAngles< Scalar_, _System >::alpha(), Eigen::EulerAngles< Scalar_, _System >::angles(), Eigen::EulerAngles< Scalar_, _System >::beta(), EulerAngles< Scalar_ >::coeffs(), Eigen::EulerAngles< Scalar_, _System >::gamma(), Eigen::EulerAngles< Scalar_, _System >::inverse(), EulerAngles< Scalar_ >::operator=(), and EulerAngles< Scalar_ >::toRotationMatrix().
The documentation for this class was generated from the following file:
unsupported/Eigen/src/EulerAngles/EulerAngles.h