MercuryDPM: Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector > Class Reference
Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector > Class Reference
#include <trilinos_eigen_solver.h>
Static Public Member Functions
static Teuchos::RCP< oomph::DoubleMultiVector > Clone (const oomph::DoubleMultiVector &mv, const int numvecs)
Creates a new empty DoubleMultiVector containing numvecs columns. Return a reference-counted pointer to the new multivector.
static Teuchos::RCP< oomph::DoubleMultiVector > CloneCopy (const oomph::DoubleMultiVector &mv)
Creates a deep copy of the DoubleMultiVector mv return Reference-counted pointer to the new DoubleMultiVector.
static Teuchos::RCP< oomph::DoubleMultiVector > CloneCopy (const oomph::DoubleMultiVector &mv, const std::vector< int > &index)
Creates a new oomph::DoubleMultiVector and (deep) copies the contents of the vectors in index into the new vector return Reference-counted pointer to the new oomph::DoubleMultiVector.
static Teuchos::RCP< oomph::DoubleMultiVector > CloneCopy (const oomph::DoubleMultiVector &mv, const Teuchos::Range1D &index)
Deep copy of specified columns of oomph::DoubleMultiVector return Reference-counted pointer to the new oomph::DoubleMultiVector.
static Teuchos::RCP< oomph::DoubleMultiVector > CloneViewNonConst (oomph::DoubleMultiVector &mv, const std::vector< int > &index)
Creates a new oomph::DoubleMultiVector that contains shallow copies of selected entries of the oomph::DoubleMultiVector mv return Reference-counted pointer to the new oomph::DoubleMultiVector.
static Teuchos::RCP< oomph::DoubleMultiVector > CloneViewNonConst (oomph::DoubleMultiVector &mv, const Teuchos::Range1D &index)
Creates a new oomph::DoubleMultiVector that contains shallow copies of selected entries of the oomph::DoubleMultiVector mv return Reference-counted pointer to the new oomph::DoubleMultiVector.
static Teuchos::RCP< const oomph::DoubleMultiVector > CloneView (const oomph::DoubleMultiVector &mv, const std::vector< int > &index)
Creates a new oomph::DoubleMultiVector that contains shallow copies of selected entries of the oomph::DoubleMultiVector mv return Reference-counted pointer to the new oomph::DoubleMultiVector (const version)
static Teuchos::RCP< oomph::DoubleMultiVector > CloneView (oomph::DoubleMultiVector &mv, const std::vector< int > &index)
Creates a new oomph::DoubleMultiVector that contains shallow copies of selected entries of the oomph::DoubleMultiVector mv return Reference-counted pointer to the new oomph::DoubleMultiVector (Non-const version for Trilinos 9 interface)
static Teuchos::RCP< oomph::DoubleMultiVector > CloneView (oomph::DoubleMultiVector &mv, const Teuchos::Range1D &index)
Creates a new oomph::DoubleMultiVector that contains shallow copies of selected entries of the oomph::DoubleMultiVector mv return Reference-counted pointer to the new oomph::DoubleMultiVector (const version)
static int GetVecLength (const oomph::DoubleMultiVector &mv)
Obtain the global length of the vector.
static int GetNumberVecs (const oomph::DoubleMultiVector &mv)
Obtain the number of vectors in the multivector.
static void MvTimesMatAddMv (const double alpha, const oomph::DoubleMultiVector &A, const Teuchos::SerialDenseMatrix< int, double > &B, const double beta, oomph::DoubleMultiVector &mv)
Update mv with \(\alpha AB + \beta mv \).
static void MvAddMv (const double alpha, const oomph::DoubleMultiVector &A, const double beta, const oomph::DoubleMultiVector &B, oomph::DoubleMultiVector &mv)
Replace mv with \(\alpha A + \beta B\).
static void MvScale (oomph::DoubleMultiVector &mv, const double alpha)
Scale each element of the vectors in mv with alpha.
static void MvScale (oomph::DoubleMultiVector &mv, const std::vector< double > &alpha)
Scale each element of the i-th vector in mv with alpha[i].
static void MvTransMv (const double alpha, const oomph::DoubleMultiVector &A, const oomph::DoubleMultiVector &mv, Teuchos::SerialDenseMatrix< int, double > &B)
Compute a dense matrix B through the matrix-matrix multiply \(\alpha A^Hmv \).
static void MvDot (const oomph::DoubleMultiVector &mv, const oomph::DoubleMultiVector &A, std::vector< double > &b)
Compute a vector b where the components are the individual dot-products of the i-th columns of A and mv, i.e. \(b[i] = * A[i]^Hmv[i] \).
static void MvNorm (const oomph::DoubleMultiVector &mv, std::vector< double > &normvec)
Compute the 2-norm of each individual vector of mv. Upon return, normvec[i] holds the value of \(||mv_i||_2\), the i-th column of mv.
Initialization methods
static void SetBlock (const oomph::DoubleMultiVector &A, const std::vector< int > &index, oomph::DoubleMultiVector &mv)
Copy the vectors in A to a set of vectors in mv indicated by the indices given in index.
static void SetBlock (const oomph::DoubleMultiVector &A, const Teuchos::Range1D &index, oomph::DoubleMultiVector &mv)
Deep copy of A into specified columns of mv.
static void Assign (const oomph::DoubleMultiVector &A, oomph::DoubleMultiVector &mv)
mv := A
static void MvRandom (oomph::DoubleMultiVector &mv)
Replace the vectors in mv with random vectors.
static void MvInit (oomph::DoubleMultiVector &mv, const double alpha=Teuchos::ScalarTraits< double >::zero())
Replace each element of the vectors in mv with alpha.
Print method
static void MvPrint (const oomph::DoubleMultiVector &mv, std::ostream &os)
Print the mv multi-vector to the os output stream.
Detailed Description
Specialize the Anasazi traits class for the oomph-lib DoubleMultiVector. This provides the interfaces required by the Anasazi eigensolvers.
Member Function Documentation
Assign()
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::Assign (const oomph::DoubleMultiVector & A, oomph::DoubleMultiVector & mv) inline static
mv := A
Assign (deep copy) A into mv.
     {
       mv = A;
     }
Clone()
static Teuchos::RCP<oomph::DoubleMultiVector> Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::Clone (const oomph::DoubleMultiVector & mv, const int numvecs) inline static
Creates a new empty DoubleMultiVector containing numvecs columns. Return a reference-counted pointer to the new multivector.
     {
       return Teuchos::rcp(new oomph::DoubleMultiVector(numvecs, mv));
     }
CloneCopy() [1/3]
static Teuchos::RCP<oomph::DoubleMultiVector> Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::CloneCopy (const oomph::DoubleMultiVector & mv) inline static
Creates a deep copy of the DoubleMultiVector mv return Reference-counted pointer to the new DoubleMultiVector.
     {
       return Teuchos::rcp(new oomph::DoubleMultiVector(mv));
     }
CloneCopy() [2/3]
static Teuchos::RCP<oomph::DoubleMultiVector> Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::CloneCopy (const oomph::DoubleMultiVector & mv, const std::vector< int > & index) inline static
Creates a new oomph::DoubleMultiVector and (deep) copies the contents of the vectors in index into the new vector return Reference-counted pointer to the new oomph::DoubleMultiVector.
     {
       return Teuchos::rcp(new oomph::DoubleMultiVector(mv, index));
     }
CloneCopy() [3/3]
static Teuchos::RCP<oomph::DoubleMultiVector> Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::CloneCopy (const oomph::DoubleMultiVector & mv, const Teuchos::Range1D & index) inline static
Deep copy of specified columns of oomph::DoubleMultiVector return Reference-counted pointer to the new oomph::DoubleMultiVector.
     {
       return Teuchos::rcp(new oomph::DoubleMultiVector(mv, index));
     }
CloneView() [1/3]
static Teuchos::RCP<const oomph::DoubleMultiVector> Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::CloneView (const oomph::DoubleMultiVector & mv, const std::vector< int > & index) inline static
Creates a new oomph::DoubleMultiVector that contains shallow copies of selected entries of the oomph::DoubleMultiVector mv return Reference-counted pointer to the new oomph::DoubleMultiVector (const version)
     {
       return Teuchos::rcp(new oomph::DoubleMultiVector(mv, index, false));
     }
CloneView() [2/3]
static Teuchos::RCP<oomph::DoubleMultiVector> Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::CloneView (oomph::DoubleMultiVector & mv, const std::vector< int > & index) inline static
Creates a new oomph::DoubleMultiVector that contains shallow copies of selected entries of the oomph::DoubleMultiVector mv return Reference-counted pointer to the new oomph::DoubleMultiVector (Non-const version for Trilinos 9 interface)
     {
       return Teuchos::rcp(new oomph::DoubleMultiVector(mv, index, false));
     }
CloneView() [3/3]
static Teuchos::RCP<oomph::DoubleMultiVector> Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::CloneView (oomph::DoubleMultiVector & mv, const Teuchos::Range1D & index) inline static
Creates a new oomph::DoubleMultiVector that contains shallow copies of selected entries of the oomph::DoubleMultiVector mv return Reference-counted pointer to the new oomph::DoubleMultiVector (const version)
     {
       return Teuchos::rcp(new oomph::DoubleMultiVector(mv, index, false));
     }
CloneViewNonConst() [1/2]
static Teuchos::RCP<oomph::DoubleMultiVector> Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::CloneViewNonConst (oomph::DoubleMultiVector & mv, const std::vector< int > & index) inline static
Creates a new oomph::DoubleMultiVector that contains shallow copies of selected entries of the oomph::DoubleMultiVector mv return Reference-counted pointer to the new oomph::DoubleMultiVector.
     {
       return Teuchos::rcp(new oomph::DoubleMultiVector(mv, index, false));
     }
CloneViewNonConst() [2/2]
static Teuchos::RCP<oomph::DoubleMultiVector> Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::CloneViewNonConst (oomph::DoubleMultiVector & mv, const Teuchos::Range1D & index) inline static
Creates a new oomph::DoubleMultiVector that contains shallow copies of selected entries of the oomph::DoubleMultiVector mv return Reference-counted pointer to the new oomph::DoubleMultiVector.
     {
       return Teuchos::rcp(new oomph::DoubleMultiVector(mv, index, false));
     }
GetNumberVecs()
static int Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::GetNumberVecs (const oomph::DoubleMultiVector & mv) inline static
Obtain the number of vectors in the multivector.
     {
       return static_cast<int>(mv.nvector());
     }
References oomph::DoubleMultiVector::nvector().
GetVecLength()
static int Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::GetVecLength (const oomph::DoubleMultiVector & mv) inline static
Obtain the global length of the vector.
     {
       return static_cast<int>(mv.nrow());
     }
References oomph::DistributableLinearAlgebraObject::nrow().
MvAddMv()
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvAddMv (const double alpha, const oomph::DoubleMultiVector & A, const double beta, const oomph::DoubleMultiVector & B, oomph::DoubleMultiVector & mv) inline static
Replace mv with \(\alpha A + \beta B\).
     {
       const unsigned n_vector = A.nvector();
       const unsigned n_row_local = A.nrow_local();
       for (unsigned v = 0; v < n_vector; v++)
       {
         for (unsigned i = 0; i < n_row_local; i++)
         {
           mv(v, i) = alpha * A(v, i) + beta * B(v, i);
         }
       }
     }
References alpha, beta, i, and v.
MvDot()
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvDot (const oomph::DoubleMultiVector & mv, const oomph::DoubleMultiVector & A, std::vector< double > & b) inline static
Compute a vector b where the components are the individual dot-products of the i-th columns of A and mv, i.e. \(b[i] = * A[i]^Hmv[i] \).
     {
       mv.dot(A, b);
     }
References b, and oomph::DoubleMultiVector::dot().
MvInit()
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvInit (oomph::DoubleMultiVector & mv, const double alpha = Teuchos::ScalarTraits<double>::zero()) inline static
Replace each element of the vectors in mv with alpha.
     {
       mv.initialise(alpha);
     }
References alpha, and oomph::DoubleMultiVector::initialise().
MvNorm()
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvNorm (const oomph::DoubleMultiVector & mv, std::vector< double > & normvec) inline static
Compute the 2-norm of each individual vector of mv. Upon return, normvec[i] holds the value of \(||mv_i||_2\), the i-th column of mv.
     {
       mv.norm(normvec);
     }
References oomph::DoubleMultiVector::norm().
MvPrint()
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvPrint (const oomph::DoubleMultiVector & mv, std::ostream & os) inline static
Print the mv multi-vector to the os output stream.
     {
       mv.output(os);
     }
References oomph::DoubleMultiVector::output().
MvRandom()
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvRandom (oomph::DoubleMultiVector & mv) inline static
Replace the vectors in mv with random vectors.
     {
       const unsigned n_vector = mv.nvector();
       const unsigned n_row_local = mv.nrow_local();
       for (unsigned v = 0; v < n_vector; v++)
       {
         for (unsigned i = 0; i < n_row_local; i++)
         {
           mv(v, i) = Teuchos::ScalarTraits<double>::random();
         }
       }
     }
References i, oomph::DistributableLinearAlgebraObject::nrow_local(), oomph::DoubleMultiVector::nvector(), and v.
MvScale() [1/2]
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvScale (oomph::DoubleMultiVector & mv, const double alpha) inline static
Scale each element of the vectors in mv with alpha.
     {
       mv *= alpha;
     }
References alpha.
MvScale() [2/2]
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvScale (oomph::DoubleMultiVector & mv, const std::vector< double > & alpha) inline static
Scale each element of the i-th vector in mv with alpha[i].
     {
       const unsigned n_vector = mv.nvector();
       const unsigned n_row_local = mv.nrow_local();
       for (unsigned v = 0; v < n_vector; v++)
       {
         for (unsigned i = 0; i < n_row_local; i++)
         {
           mv(v, i) *= alpha[v];
         }
       }
     }
References alpha, i, oomph::DistributableLinearAlgebraObject::nrow_local(), oomph::DoubleMultiVector::nvector(), and v.
MvTimesMatAddMv()
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvTimesMatAddMv (const double alpha, const oomph::DoubleMultiVector & A, const Teuchos::SerialDenseMatrix< int, double > & B, const double beta, oomph::DoubleMultiVector & mv) inline static
Update mv with \(\alpha AB + \beta mv \).
     {
       // For safety let's (deep) copy A
       oomph::DoubleMultiVector C(A);
       // First pre-multiply by the scalars
       mv *= beta;
       C *= alpha;
       // Find the number of vectors in each multivector
       int mv_n_vector = mv.nvector();
       int A_n_vector = A.nvector();
       // Find the number of rows
       int n_row_local = A.nrow_local();
       // Now need to multiply by the matrix and add the result
       // to the appropriate entry in the multivector
       for (int i = 0; i < n_row_local; ++i)
       {
         for (int j = 0; j < mv_n_vector; j++)
         {
           double res = 0.0;
           for (int k = 0; k < A_n_vector; k++)
           {
             res += C(k, i) * B(k, j);
           }
           mv(j, i) += res;
         }
       }
     }
References alpha, beta, i, j, k, oomph::DoubleMultiVector::nvector(), and res.
MvTransMv()
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvTransMv (const double alpha, const oomph::DoubleMultiVector & A, const oomph::DoubleMultiVector & mv, Teuchos::SerialDenseMatrix< int, double > & B) inline static
Compute a dense matrix B through the matrix-matrix multiply \(\alpha A^Hmv \).
     {
       const unsigned A_nvec = A.nvector();
       const unsigned A_nrow_local = A.nrow_local();
       const unsigned mv_nvec = mv.nvector();
       // const unsigned mv_nrow_local = mv.nrow_local();
       for (unsigned v1 = 0; v1 < A_nvec; v1++)
       {
         for (unsigned v2 = 0; v2 < mv_nvec; v2++)
         {
           B(v1, v2) = 0.0;
           for (unsigned i = 0; i < A_nrow_local; i++)
           {
             B(v1, v2) += A(v1, i) * mv(v2, i);
           }
           B(v1, v2) *= alpha;
         }
       }
       // This will need to be communicated if we're in parallel and distributed
 #ifdef OOMPH_HAS_MPI
       if (A.distributed() &&
           A.distribution_pt()->communicator_pt()->nproc() > 1)
       {
         const int n_total_val = A_nvec * mv_nvec;
         // Pack entries into a vector
         double b[n_total_val];
         double b2[n_total_val];
         unsigned count = 0;
         for (unsigned v1 = 0; v1 < A_nvec; v1++)
         {
           for (unsigned v2 = 0; v2 < mv_nvec; v2++)
           {
             b[count] = B(v1, v2);
             b2[count] = b[count];
             ++count;
           }
         }
         MPI_Allreduce(&b,
                       &b2,
                       n_total_val,
                       MPI_DOUBLE,
                       MPI_SUM,
                       A.distribution_pt()->communicator_pt()->mpi_comm());
         count = 0;
         for (unsigned v1 = 0; v1 < A_nvec; v1++)
         {
           for (unsigned v2 = 0; v2 < mv_nvec; v2++)
           {
             B(v1, v2) = b2[count];
             ++count;
           }
         }
       }
 #endif
     }
References alpha, b, i, oomph::DoubleMultiVector::nvector(), v1(), and v2().
SetBlock() [1/2]
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::SetBlock (const oomph::DoubleMultiVector & A, const std::vector< int > & index, oomph::DoubleMultiVector & mv) inline static
Copy the vectors in A to a set of vectors in mv indicated by the indices given in index.
The numvecs vectors in A are copied to a subset of vectors in mv indicated by the indices given in index, i.e. mv[index[i]] = A[i].
     {
       // Check some stuff
       const unsigned n_index = index.size();
       if (n_index == 0)
       {
         return;
       }
       const unsigned n_row_local = mv.nrow_local();
       for (unsigned v = 0; v < n_index; v++)
       {
         for (unsigned i = 0; i < n_row_local; i++)
         {
           mv(index[v], i) = A(v, i);
         }
       }
     }
References i, oomph::DistributableLinearAlgebraObject::nrow_local(), and v.
SetBlock() [2/2]
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::SetBlock (const oomph::DoubleMultiVector & A, const Teuchos::Range1D & index, oomph::DoubleMultiVector & mv) inline static
Deep copy of A into specified columns of mv.
(Deeply) copy the first index.size() columns of A into the columns of mv specified by the given index range.
Postcondition: mv[i] = A[i - index.lbound()] for all i in [index.lbound(), index.ubound()]
Parameters
A [in] Source multivector
index [in] Inclusive index range of columns of mv; index set of the target
mv [out] Target multivector
     {
       // Check some stuff
       const unsigned n_index = index.size();
       if (n_index == 0)
       {
         return;
       }
       const unsigned n_row_local = mv.nrow_local();
       unsigned range_index = index.lbound();
       for (unsigned v = 0; v < n_index; v++)
       {
         for (unsigned i = 0; i < n_row_local; i++)
         {
           mv(range_index, i) = A(v, i);
         }
         ++range_index;
       }
     }
References i, oomph::DistributableLinearAlgebraObject::nrow_local(), and v.
The documentation for this class was generated from the following file:
trilinos_eigen_solver.h