MercuryDPM: oomph::StraightLine Class Reference
oomph::StraightLine Class Reference
#include <geom_objects.h>
Public Member Functions
StraightLine (const Vector< Data * > &geom_data_pt)
StraightLine (const double &height)
Constructor: Pass height (pinned by default)
StraightLine (const StraightLine &dummy)=delete
Broken copy constructor.
void operator= (const StraightLine &)=delete
Broken assignment operator.
~StraightLine ()
Destructor: Clean up if necessary.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position Vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
unsigned ngeom_data () const
How many items of Data does the shape of the object depend on?
Data * geom_data_pt (const unsigned &j)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Private Attributes
Vector< Data * > Geom_data_pt
Vector of pointers to Data items that affects the object's shape.
bool Must_clean_up
Do I need to clean up?
Additional Inherited Members
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Steady, straight 1D line in 2D space
\[ x = \zeta \]
\[ y = H \]
Constructor & Destructor Documentation
StraightLine() [1/3]
oomph::StraightLine::StraightLine (const Vector< Data * > & geom_data_pt) inline
Constructor: One item of geometric data:
Geom_data_pt[0]->value(0) = height
                                                     : GeomObject(1, 2)
     {
 #ifdef PARANOID
       if (geom_data_pt.size() != 1)
       {
         std::ostringstream error_message;
         error_message << "geom_data_pt should have size 1, not "
                       << geom_data_pt.size() << std::endl;
         if (geom_data_pt[0]->nvalue() != 1)
         {
           error_message << "geom_data_pt[0] should have 1 value, not "
                         << geom_data_pt[0]->nvalue() << std::endl;
         }
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       Geom_data_pt.resize(1);
       Geom_data_pt[0] = geom_data_pt[0];
       // Data has been created externally: Must not clean up
       Must_clean_up = false;
     }
References geom_data_pt(), Geom_data_pt, Must_clean_up, oomph::Data::nvalue(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
StraightLine() [2/3]
oomph::StraightLine::StraightLine (const double & height) inline
Constructor: Pass height (pinned by default)
                                        : GeomObject(1, 2)
     {
       // Create Data for straight-line object: The only geometric data is the
       // height which is pinned
       Geom_data_pt.resize(1);
       // Create data: One value, no timedependence, free by default
       Geom_data_pt[0] = new Data(1);
       // I've created the data, I need to clean up
       Must_clean_up = true;
       // Pin the data
       Geom_data_pt[0]->pin(0);
       // Give it a value: Initial height
       Geom_data_pt[0]->set_value(0, height);
     }
References Geom_data_pt, Global_Physical_Variables::height(), and Must_clean_up.
StraightLine() [3/3]
oomph::StraightLine::StraightLine (const StraightLine & dummy) delete
Broken copy constructor.
~StraightLine()
oomph::StraightLine::~StraightLine () inline
Destructor: Clean up if necessary.
     {
       // Do I need to clean up?
       if (Must_clean_up)
       {
         delete Geom_data_pt[0];
         Geom_data_pt[0] = 0;
       }
     }
References Geom_data_pt, and Must_clean_up.
Member Function Documentation
d2position() [1/2]
virtual void oomph::StraightLine::d2position (const Vector< double > & zeta, RankThreeTensor< double > & ddrdzeta) const inline virtual
2nd derivative of position Vector w.r.t. to coordinates: \(\frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}\) = ddrdzeta(alpha,beta,i). Evaluated at current time.
Reimplemented from oomph::GeomObject.
     {
       // Derivative of tangent vector
       ddrdzeta(0, 0, 0) = 0.0;
       ddrdzeta(0, 0, 1) = 0.0;
     }
d2position() [2/2]
virtual void oomph::StraightLine::d2position (const Vector< double > & zeta, Vector< double > & r, DenseMatrix< double > & drdzeta, RankThreeTensor< double > & ddrdzeta) const inline virtual
Posn Vector and its 1st & 2nd derivatives w.r.t. to coordinates: \(\frac{dR_i}{d \zeta_\alpha}\) = drdzeta(alpha,i). \(\frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}\) = ddrdzeta(alpha,beta,i). Evaluated at current time.
Reimplemented from oomph::GeomObject.
     {
       // Position Vector
       r[0] = zeta[0];
       r[1] = Geom_data_pt[0]->value(0);
       // Tangent vector
       drdzeta(0, 0) = 1.0;
       drdzeta(0, 1) = 0.0;
       // Derivative of tangent vector
       ddrdzeta(0, 0, 0) = 0.0;
       ddrdzeta(0, 0, 1) = 0.0;
     }
References Geom_data_pt, UniformPSDSelfTest::r, and Eigen::zeta().
dposition()
virtual void oomph::StraightLine::dposition (const Vector< double > & zeta, DenseMatrix< double > & drdzeta) const inline virtual
Derivative of position Vector w.r.t. to coordinates: \(\frac{dR_i}{d \zeta_\alpha}\) = drdzeta(alpha,i). Evaluated at current time.
Reimplemented from oomph::GeomObject.
     {
       // Tangent vector
       drdzeta(0, 0) = 1.0;
       drdzeta(0, 1) = 0.0;
     }
geom_data_pt()
Data* oomph::StraightLine::geom_data_pt (const unsigned & j) inline virtual
Return pointer to the j-th Data item that the object's shape depends on
Reimplemented from oomph::GeomObject.
     {
       return Geom_data_pt[j];
     }
References Geom_data_pt, and j.
Referenced by StraightLine().
ngeom_data()
unsigned oomph::StraightLine::ngeom_data () const inline virtual
How many items of Data does the shape of the object depend on?
Reimplemented from oomph::GeomObject.
     {
       return Geom_data_pt.size();
     }
References Geom_data_pt.
operator=()
void oomph::StraightLine::operator= (const StraightLine &) delete
Broken assignment operator.
position() [1/2]
void oomph::StraightLine::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep.
Reimplemented from oomph::GeomObject.
     {
 #ifdef PARANOID
       if (t > Geom_data_pt[0]->time_stepper_pt()->nprev_values())
       {
         std::ostringstream error_message;
         error_message << "t > nprev_values() " << t << " "
                       << Geom_data_pt[0]->time_stepper_pt()->nprev_values()
                       << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Position Vector at time level t
       r[0] = zeta[0];
       r[1] = Geom_data_pt[0]->value(t, 0);
     }
References Geom_data_pt, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, UniformPSDSelfTest::r, plotPSD::t, oomph::GeomObject::time_stepper_pt(), and Eigen::zeta().
position() [2/2]
void oomph::StraightLine::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position Vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
     {
       // Position Vector
       r[0] = zeta[0];
       r[1] = Geom_data_pt[0]->value(0);
     }
References Geom_data_pt, UniformPSDSelfTest::r, and Eigen::zeta().
Member Data Documentation
Geom_data_pt
Vector<Data*> oomph::StraightLine::Geom_data_pt private
Vector of pointers to Data items that affects the object's shape.
Referenced by d2position(), geom_data_pt(), ngeom_data(), position(), StraightLine(), and ~StraightLine().
Must_clean_up
bool oomph::StraightLine::Must_clean_up private
Do I need to clean up?
Referenced by StraightLine(), and ~StraightLine().
The documentation for this class was generated from the following file:
geom_objects.h