MercuryDPM: two_d_adv_diff_flux_bc.cc File Reference
two_d_adv_diff_flux_bc.cc File Reference
#include "generic.h"
#include "advection_diffusion.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >
Namespaces
TanhSolnForAdvectionDiffusion
Functions
void TanhSolnForAdvectionDiffusion::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForAdvectionDiffusion::get_exact_u (const Vector< double > &x, double &u)
Exact solution as a scalar.
void TanhSolnForAdvectionDiffusion::source_function (const Vector< double > &x_vect, double &source)
Source function required to make the solution above an exact solution.
void TanhSolnForAdvectionDiffusion::prescribed_flux_on_fixed_x_boundary (const Vector< double > &x, double &flux)
Flux required by the exact solution on a boundary on which x is fixed.
void TanhSolnForAdvectionDiffusion::wind_function (const Vector< double > &x, Vector< double > &wind)
Wind.
int main ()
Function Documentation
main()
int main ()
Demonstrate how to solve 2D AdvectionDiffusion problem with flux boundary conditions, using two meshes.
 {
  //Set up the problem
  //------------------
  //Set up the problem with 2D nine-node elements from the
  //RefineableQuadAdvectionDiffusionElement family.
  //Pass pointer to source function.
  TwoMeshFluxAdvectionDiffusionProblem<RefineableQAdvectionDiffusionElement<2,
   3> > problem(&TanhSolnForAdvectionDiffusion::source_function,
                &TanhSolnForAdvectionDiffusion::wind_function);
  // Create label for output
  //------------------------
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory("RESLT");
  // Step number
  doc_info.number()=0;
  // Check if we're ready to go:
  //----------------------------
  cout << "\n\n\nProblem self-test ";
  if (problem.self_test()==0)
   {
    cout << "passed: Problem can be solved." << std::endl;
   }
  else
   {
    throw OomphLibError("Self test failed",
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
   }
  // Set the orientation of the "step" to 45 degrees
  TanhSolnForAdvectionDiffusion::TanPhi=1.0;
  // Initial value for the steepness of the "step"
  TanhSolnForAdvectionDiffusion::Alpha=0.2;
  //Output solution
  problem.doc_solution(doc_info);
  // Do a couple of solutions for different forcing functions
  //---------------------------------------------------------
  unsigned nstep=4;
  for (unsigned istep=0;istep<nstep;istep++)
   {
    cout << "\n\nSolving for TanhSolnForAdvectionDiffusion::Alpha="
         << TanhSolnForAdvectionDiffusion::Alpha << std::endl << std::endl;
    // Solve the problem, allowing for up to four adaptations
    problem.newton_solve(4);
    //Output solution
    problem.doc_solution(doc_info);
    //Increment counter for solutions
    doc_info.number()++;
    // Increase the steepness of the step:
    TanhSolnForAdvectionDiffusion::Alpha=double(istep+1)*5.0;
   }
 } //end of main
References TanhSolnForAdvectionDiffusion::Alpha, oomph::DocInfo::number(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, problem, oomph::DocInfo::set_directory(), TanhSolnForAdvectionDiffusion::source_function(), TanhSolnForAdvectionDiffusion::TanPhi, and TanhSolnForAdvectionDiffusion::wind_function().