MercuryDPM: Eigen::internal::TensorPrinter< Tensor, rank, TensorIOFormatLegacy, std::enable_if_t< rank !=0 > > Struct Template Reference
Eigen::internal::TensorPrinter< Tensor, rank, TensorIOFormatLegacy, std::enable_if_t< rank !=0 > > Struct Template Reference
#include <TensorIO.h>
Public Types
using Format = TensorIOFormatLegacy
using Scalar = std::remove_const_t< typename Tensor::Scalar >
Static Public Member Functions
static void run (std::ostream &s, const Tensor &tensor, const Format &)
Member Typedef Documentation
Format
template<typename Tensor , std::size_t rank> using Eigen::internal::TensorPrinter< Tensor, rank, TensorIOFormatLegacy, std::enable_if_t< rank !=0 > >::Format = TensorIOFormatLegacy
Scalar
template<typename Tensor , std::size_t rank> using Eigen::internal::TensorPrinter< Tensor, rank, TensorIOFormatLegacy, std::enable_if_t< rank !=0 > >::Scalar = std::remove_const_t<typename Tensor::Scalar>
Member Function Documentation
run()
template<typename Tensor , std::size_t rank> static void Eigen::internal::TensorPrinter< Tensor, rank, TensorIOFormatLegacy, std::enable_if_t< rank !=0 > >::run (std::ostream & s, const Tensor & tensor, const Format &) inline static
{
     typedef typename Tensor::Index IndexType;
     // backwards compatibility case: print tensor after reshaping to matrix of size dim(0) x
     // (dim(1)*dim(2)*...*dim(rank-1)).
     const IndexType total_size = internal::array_prod(tensor.dimensions());
     if (total_size > 0) {
       const IndexType first_dim = Eigen::internal::array_get<0>(tensor.dimensions());
       Map<const Array<Scalar, Dynamic, Dynamic, Tensor::Layout>> matrix(tensor.data(), first_dim,
                                                                         total_size / first_dim);
       s << matrix;
       return;
     }
   }
References Eigen::internal::array_prod(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::data(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::dimensions(), matrix(), and s.
The documentation for this struct was generated from the following file:
TensorIO.h