MercuryDPM: MercuryBase Class Reference
MercuryBase Class Reference abstract
This is the base class for both Mercury2D and Mercury3D. Note the actually abstract grid is defined in the class Grid defined below.
#include <MercuryBase.h>
Public Member Functions
MercuryBase ()
This is the default constructor. It sets sensible defaults.
~MercuryBase () override
This is the default destructor.
MercuryBase (const MercuryBase &mercuryBase)
Copy-constructor.
void constructor ()
This is the actual constructor, it is called do both constructors above.
void hGridActionsBeforeTimeLoop () override
This sets up the broad phase information, has to be done at this stage because it requires the particle size.
void hGridActionsBeforeTimeStep () override
Performs all necessary actions before a time-step, like updating the particles and resetting all the bucket information, etc.
void read (std::istream &is, ReadOptions opt=ReadOptions::ReadAll) override
Reads the MercuryBase from an input stream, for example a restart file.
void write (std::ostream &os, bool writeAllParticles=true) const override
Writes all data into a restart file.
Mdouble getHGridCurrentMaxRelativeDisplacement () const
Returns hGridCurrentMaxRelativeDisplacement_.
Mdouble getHGridTotalCurrentMaxRelativeDisplacement () const
Returns hGridTotalCurrentMaxRelativeDisplacement_.
void setHGridUpdateEachTimeStep (bool updateEachTimeStep)
Sets whether or not the HGrid must be updated every time step.
bool getHGridUpdateEachTimeStep () const final
Gets whether or not the HGrid is updated every time step.
void setHGridMaxLevels (unsigned int HGridMaxLevels)
Sets the maximum number of levels of the HGrid in this MercuryBase.
unsigned int getHGridMaxLevels () const
Gets the maximum number of levels of the HGrid in this MercuryBase.
HGridMethod getHGridMethod () const
Gets whether the HGrid in this MercuryBase is BOTTOMUP or TOPDOWN.
void setHGridMethod (HGridMethod hGridMethod)
Sets the HGridMethod to either BOTTOMUP or TOPDOWN.
HGridDistribution getHGridDistribution () const
Gets how the sizes of the cells of different levels are distributed.
void setHGridDistribution (HGridDistribution hGridDistribution)
Sets how the sizes of the cells of different levels are distributed.
Mdouble getHGridCellOverSizeRatio () const
Gets the ratio of the smallest cell over the smallest particle.
void setHGridCellOverSizeRatio (Mdouble cellOverSizeRatio)
Sets the ratio of the smallest cell over the smallest particle.
bool hGridNeedsRebuilding ()
Gets if the HGrid needs rebuilding before anything else happens.
virtual unsigned int getHGridTargetNumberOfBuckets () const
Gets the desired number of buckets, which is the maximum of the number of particles and 10.
virtual Mdouble getHGridTargetMinInteractionRadius () const
Gets the desired size of the smallest cells of the HGrid.
virtual Mdouble getHGridTargetMaxInteractionRadius () const
Gets the desired size of the largest cells of the HGrid.
bool checkParticleForInteraction (const BaseParticle &P) final
Checks if given BaseParticle has an interaction with a BaseWall or other BaseParticle.
bool checkParticleForInteractionLocal (const BaseParticle &P) final
Checks if the given BaseParticle has an interaction with a BaseWall or other BaseParticles in a local domain.
virtual Mdouble userHGridCellSize (unsigned int level)
Virtual function that enables inheriting classes to implement a function to let the user set the cell size of the HGrid.
virtual std::vector< BaseParticle * > hGridFindParticleContacts (const BaseParticle *obj)=0
Purely virtual function that returns all particles that have a contact with a given particle.
void hGridInfo (std::ostream &os=std::cout) const
Writes the info of the HGrid to the screen in a nice format.
Public Member Functions inherited from DPMBase
void constructor ()
A function which initialises the member variables to default values, so that the problem can be solved off the shelf; sets up a basic two dimensional problem which can be solved off the shelf. It is called in the constructor DPMBase().
DPMBase ()
Constructor that calls the "void constructor()".
DPMBase (const DPMBase &other)
Copy constructor type-2.
virtual ~DPMBase ()
virtual destructor
void autoNumber ()
The autoNumber() function calls three functions: setRunNumber(), readRunNumberFromFile() and incrementRunNumberInFile().
std::vector< int > get1DParametersFromRunNumber (int size_x) const
This turns a counter into 1 index, which is a useful feature for performing 1D parameter study. The index run from 1:size_x, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get2DParametersFromRunNumber (int size_x, int size_y) const
This turns a counter into 2 indices which is a very useful feature for performing a 2D study. The indices run from 1:size_x and 1:size_y, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get3DParametersFromRunNumber (int size_x, int size_y, int size_z) const
This turns a counter into 3 indices, which is a useful feature for performing a 3D parameter study. The indices run from 1:size_x, 1:size_y and 1:size_z, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
int launchNewRun (const char *name, bool quick=false)
This launches a code from within this code. Please pass the name of the code to run.
void setRunNumber (int runNumber)
This sets the counter/Run number, overriding the defaults.
int getRunNumber () const
This returns the current value of the counter (runNumber_)
virtual void decompose ()
Sends particles from processorId to the root processor.
void solve ()
The work horse of the code.
void initialiseSolve ()
Beginning of the solve routine, before time stepping.
void finaliseSolve ()
End of the solve routine, after time stepping.
virtual void computeOneTimeStep ()
Performs everything needed for one time step, used in the time-loop of solve().
void checkSettings ()
Checks if the essentials are set properly to go ahead with solving the problem.
void forceWriteOutputFiles ()
Writes output files immediately, even if the current time step was not meant to be written. Also resets the last saved time step.
virtual void writeOutputFiles ()
Writes simulation data to all the main Mercury files: .data, .ene, .fstat, .xballs and .restart (see the Mercury website for more details regarding these files).
void solve (int argc, char *argv[])
The work horse of the code. Can handle flags from the command line.
virtual void setupInitialConditions ()
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
virtual void writeXBallsScript () const
This writes a script which can be used to load the xballs problem to display the data just generated.
virtual Mdouble getInfo (const BaseParticle &P) const
A virtual function that returns some user-specified information about a particle.
ParticleVtkWriter * getVtkWriter () const
virtual void writeRestartFile ()
Stores all the particle data for current save time step to a "restart" file, which is a file simply intended to store all the information necessary to "restart" a simulation from a given time step (see also MercuryDPM.org for more information on restart files).
void writeDataFile ()
void writeEneFile ()
void writeFStatFile ()
void fillDomainWithParticles (unsigned N=50)
bool readRestartFile (ReadOptions opt=ReadOptions::ReadAll)
Reads all the particle data corresponding to a given, existing . restart file (for more details regarding restart files, refer to the training materials on the MercuryDPM website).Returns true if it is successful, false otherwise.
int readRestartFile (std::string fileName, ReadOptions opt=ReadOptions::ReadAll)
The same as readRestartFile(bool), but also reads all the particle data corresponding to the current saved time step.
virtual BaseWall * readUserDefinedWall (const std::string &type) const
Allows you to read in a wall defined in a Driver directory; see USER/Luca/ScrewFiller.
virtual void readOld (std::istream &is)
Reads all data from a restart file, e.g. domain data and particle data; old version.
bool readDataFile (std::string fileName="", unsigned int format=0)
This allows particle data to be reloaded from data files.
bool readParAndIniFiles (std::string fileName)
Allows the user to read par.ini files (useful to read files produced by the MDCLR simulation code - external to MercuryDPM)
bool readNextDataFile (unsigned int format=0)
Reads the next data file with default format=0. However, one can modify the format based on whether the particle data corresponds to 3D or 2D data- see Visualising data in xballs.
void readNextFStatFile ()
Reads the next fstat file.
bool findNextExistingDataFile (Mdouble tMin, bool verbose=true)
Finds and opens the next data file, if such a file exists.
bool readArguments (int argc, char *argv[])
Can interpret main function input arguments that are passed by the driver codes.
bool checkParticleForInteractionLocalPeriodic (const BaseParticle &P)
void readSpeciesFromDataFile (bool read=true)
void importParticlesAs (ParticleHandler &particleHandler, InteractionHandler &interactionHandler, const ParticleSpecies *species)
Copies particles, interactions assigning species from a local simulation to a global one. Useful for the creation of a cluster.
MERCURYDPM_DEPRECATED File & getDataFile ()
The non const version. Allows one to edit the File::dataFile.
MERCURYDPM_DEPRECATED File & getEneFile ()
The non const version. Allows to edit the File::eneFile.
MERCURYDPM_DEPRECATED File & getFStatFile ()
The non const version. Allows to edit the File::fStatFile.
MERCURYDPM_DEPRECATED File & getRestartFile ()
The non const version. Allows to edit the File::restartFile.
MERCURYDPM_DEPRECATED File & getStatFile ()
The non const version. Allows to edit the File::statFile.
File & getInteractionFile ()
Return a reference to the file InteractionsFile.
MERCURYDPM_DEPRECATED const File & getDataFile () const
The const version. Does not allow for any editing of the File::dataFile.
MERCURYDPM_DEPRECATED const File & getEneFile () const
The const version. Does not allow for any editing of the File::eneFile.
MERCURYDPM_DEPRECATED const File & getFStatFile () const
The const version. Does not allow for any editing of the File::fStatFile.
MERCURYDPM_DEPRECATED const File & getRestartFile () const
The const version. Does not allow for any editing of the File::restartFile.
MERCURYDPM_DEPRECATED const File & getStatFile () const
The const version. Does not allow for any editing of the File::statFile.
const File & getInteractionFile () const
Returns a constant reference to an Interactions file.
const std::string & getName () const
Returns the name of the file. Does not allow to change it though.
void setName (const std::string &name)
Allows to set the name of all the files (ene, data, fstat, restart, stat)
void setName (const char *name)
Calls setName(std::string)
void setSaveCount (unsigned int saveCount)
Sets File::saveCount_ for all files (ene, data, fstat, restart, stat)
void setFileType (FileType fileType)
Sets File::fileType_ for all files (ene, data, fstat, restart, stat)
void setOpenMode (std::fstream::openmode openMode)
Sets File::openMode_ for all files (ene, data, fstat, restart, stat)
void resetFileCounter ()
Resets the file counter for each file i.e. for ene, data, fstat, restart, stat)
void closeFiles ()
Closes all files (ene, data, fstat, restart, stat) that were opened to read or write.
void setVTKOutputDirectory (const std::string &dir)
Sets the output directory of the VTK files.
void setLastSavedTimeStep (unsigned int nextSavedTimeStep)
Sets the next time step for all the files (ene, data, fstat, restart, stat) at which the data is to be written or saved.
Mdouble getTime () const
Returns the current simulation time.
Mdouble getNextTime () const
Returns the current simulation time.
unsigned int getNumberOfTimeSteps () const
Returns the current counter of time-steps, i.e. the number of time-steps that the simulation has undergone so far.
void setTime (Mdouble time)
Sets a new value for the current simulation time.
void setTimeMax (Mdouble newTMax)
Sets a new value for the maximum simulation duration.
Mdouble getTimeMax () const
Returns the maximum simulation duration.
void setLogarithmicSaveCount (Mdouble logarithmicSaveCountBase)
Sets File::logarithmicSaveCount_ for all files (ene, data, fstat, restart, stat)
void setNToWrite (int nToWrite)
set the number of elements to write to the screen
int getNToWrite () const
get the number of elements to write to the
void setRotation (bool rotation)
Sets whether particle rotation is enabled or disabled.
bool getRotation () const
Indicates whether particle rotation is enabled or disabled.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (FileType writeWallsVTK)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (bool)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setInteractionsWriteVTK (bool)
Sets whether interactions are written into a VTK file.
void setParticlesWriteVTK (bool writeParticlesVTK)
Sets whether particles are written in a VTK file.
void setSuperquadricParticlesWriteVTK (bool writeSuperquadricParticlesVTK)
MERCURYDPM_DEPRECATED FileType getWallsWriteVTK () const
Returns whether walls are written in a VTK file.
bool getParticlesWriteVTK () const
Returns whether particles are written in a VTK file.
bool getSuperquadricParticlesWriteVTK () const
Mdouble getXMin () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMin() returns XMin.
Mdouble getXMax () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMax() returns XMax.
Mdouble getYMin () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMin() returns YMin.
Mdouble getYMax () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMax() returns XMax.
Mdouble getZMin () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMin() returns ZMin.
Mdouble getZMax () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMax() returns ZMax.
Mdouble getXCenter () const
Mdouble getYCenter () const
Mdouble getZCenter () const
Vec3D getCenter () const
get center of domain
Vec3D getMin () const
Returns the minimum coordinates of the problem domain.
Vec3D getMax () const
Returns the maximum coordinates of the problem domain.
void setXMin (Mdouble newXMin)
Sets the value of XMin, the lower bound of the problem domain in the x-direction.
void setYMin (Mdouble newYMin)
Sets the value of YMin, the lower bound of the problem domain in the y-direction.
void setZMin (Mdouble newZMin)
Sets the value of ZMin, the lower bound of the problem domain in the z-direction.
void setXMax (Mdouble newXMax)
Sets the value of XMax, the upper bound of the problem domain in the x-direction.
void setYMax (Mdouble newYMax)
Sets the value of YMax, the upper bound of the problem domain in the y-direction.
void setZMax (Mdouble newZMax)
Sets the value of ZMax, the upper bound of the problem domain in the z-direction.
void setMax (const Vec3D &max)
Sets the maximum coordinates of the problem domain.
void setMax (Mdouble, Mdouble, Mdouble)
Sets the maximum coordinates of the problem domain.
void setDomain (const Vec3D &min, const Vec3D &max)
Sets the minimum coordinates of the problem domain.
void setMin (const Vec3D &min)
Sets the minimum coordinates of the problem domain.
void setMin (Mdouble, Mdouble, Mdouble)
Sets the minimum coordinates of the problem domain.
void setTimeStep (Mdouble newDt)
Sets a new value for the simulation time step.
Mdouble getTimeStep () const
Returns the simulation time step.
void setNumberOfOMPThreads (int numberOfOMPThreads)
Sets the number of omp threads.
int getNumberOfOMPThreads () const
Returns the number of omp threads.
void setXBallsColourMode (int newCMode)
Set the xballs output mode.
int getXBallsColourMode () const
Get the xballs colour mode (CMode).
void setXBallsVectorScale (double newVScale)
Set the scale of vectors in xballs.
double getXBallsVectorScale () const
Returns the scale of vectors used in xballs.
void setXBallsAdditionalArguments (std::string newXBArgs)
Set the additional arguments for xballs.
std::string getXBallsAdditionalArguments () const
Returns the additional arguments for xballs.
void setXBallsScale (Mdouble newScale)
Sets the scale of the view (either normal, zoom in or zoom out) to display in xballs. The default is fit to screen.
double getXBallsScale () const
Returns the scale of the view in xballs.
void setGravity (Vec3D newGravity)
Sets a new value for the gravitational acceleration.
Vec3D getGravity () const
Returns the gravitational acceleration.
void setBackgroundDrag (Mdouble backgroundDrag)
Simple access function to turn on a background drag. The force of particleVelocity*drag is applied (note, it allowed to be negative i.e. create energy)
const Mdouble getBackgroundDrag () const
Return the background drag.
void setDimension (unsigned int newDim)
Sets both the system dimensions and the particle dimensionality.
void setSystemDimensions (unsigned int newDim)
Sets the system dimensionality.
unsigned int getSystemDimensions () const
Returns the system dimensionality.
void setParticleDimensions (unsigned int particleDimensions)
Sets the particle dimensionality.
unsigned int getParticleDimensions () const
Returns the particle dimensionality.
std::string getRestartVersion () const
This is to take into account for different Mercury versions. Returns the version of the restart file.
void setRestartVersion (std::string newRV)
Sets restart_version.
bool getRestarted () const
Returns the flag denoting if the simulation was restarted or not.
void setRestarted (bool newRestartedFlag)
Allows to set the flag stating if the simulation is to be restarted or not.
bool getAppend () const
Returns whether the "append" option is on or off.
void setAppend (bool newAppendFlag)
Sets whether the "append" option is on or off.
Mdouble getElasticEnergy () const
Returns the global elastic energy within the system.
Mdouble getKineticEnergy () const
Returns the global kinetic energy stored in the system.
Mdouble getGravitationalEnergy (Vec3D origin={0, 0, 0}) const
Returns the global gravitational potential energy stored relative to a user-defined origin in the system. Note, if no origin is specified the real origin i.e. (0,0,0) is taken.
Mdouble getRotationalEnergy () const
Returns the global rotational energy stored in the system.
Mdouble getTotalEnergy () const
Mdouble getTotalMass () const
JMFT: Return the total mass of the system, excluding fixed particles.
Vec3D getCentreOfMass () const
JMFT: Return the centre of mass of the system, excluding fixed particles.
Vec3D getTotalMomentum () const
JMFT: Return the total momentum of the system, excluding fixed particles.
double getCPUTime ()
double getWallTime ()
virtual void hGridInsertParticle (BaseParticle *obj UNUSED)
virtual void hGridUpdateParticle (BaseParticle *obj UNUSED)
virtual void hGridRemoveParticle (BaseParticle *obj UNUSED)
bool mpiIsInCommunicationZone (BaseParticle *particle)
Checks if the position of the particle is in an mpi communication zone or not.
bool mpiInsertParticleCheck (BaseParticle *P)
Function that checks if the mpi particle should really be inserted by the current domain.
void insertGhostParticle (BaseParticle *P)
This function inserts a particle in the mpi communication boundaries.
void updateGhostGrid (BaseParticle *P)
Checks if the Domain/periodic interaction distance needs to be updated and updates it accordingly.
virtual void gatherContactStatistics (unsigned int index1, int index2, Vec3D Contact, Mdouble delta, Mdouble ctheta, Mdouble fdotn, Mdouble fdott, Vec3D P1_P2_normal_, Vec3D P1_P2_tangential)
//Not unsigned index because of possible wall collisions.
void setNumberOfDomains (std::vector< unsigned > direction)
Sets the number of domains in x-,y- and z-direction. Required for parallel computations.
void splitDomain (DomainSplit domainSplit)
std::vector< unsigned > getNumberOfDomains ()
returns the number of domains
Domain * getCurrentDomain ()
Function that returns a pointer to the domain corresponding to the processor.
void removeOldFiles () const
virtual void hGridGetInteractingParticleList (BaseParticle *obj, std::vector< BaseParticle * > &list)
Creates a list of neighbour particles obtained from the hgrid.
virtual void computeWallForces (BaseWall *w)
void setMeanVelocity (Vec3D V_mean_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
void setMeanVelocityAndKineticEnergy (Vec3D V_mean_goal, Mdouble Ek_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
Mdouble getTotalVolume () const
Get the total volume of the cuboid system.
Matrix3D getKineticStress () const
Calculate the kinetic stress tensor in the system averaged over the whole volume.
Matrix3D getStaticStress () const
Calculate the static stress tensor in the system averaged over the whole volume.
Matrix3D getTotalStress () const
Calculate the total stress tensor in the system averaged over the whole volume.
virtual void handleParticleRemoval (unsigned int id)
Handles the removal of particles from the particleHandler.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
void writePythonFileForVTKVisualisation () const
writes .py file for ParaView
void setWritePythonFileForVTKVisualisation (bool forceWritePythonFileForVTKVisualisation)
bool getWritePythonFileForVTKVisualisation () const
WallVTKWriter & getWallVTKWriter ()
Protected Member Functions
void hGridRebuild ()
This sets up the parameters required for the contact model.
void hGridInsertParticle (BaseParticle *obj) final
Inserts a single Particle to current grid.
virtual bool hGridHasParticleContacts (const BaseParticle *obj)=0
Purely virtual function that checks if the given particle has a possible contact with any other BaseParticle in the HGrid.
void hGridUpdateMove (BaseParticle *iP, Mdouble move) final
Computes the relative displacement of the given BaseParticle and updates the currentMaxRelativeDisplacement_ accordingly.
void hGridActionsBeforeIntegration () override
Resets the currentMaxRelativeDisplacement_ to 0.
void hGridActionsAfterIntegration () override
This function has to be called before integrateBeforeForceComputation.
HGrid * getHGrid ()
Gets the HGrid used by this problem.
const HGrid * getHGrid () const
Gets the HGrid used by this problem, const version.
bool readNextArgument (int &i, int argc, char *argv[]) override
Reads the next command line argument.
Protected Member Functions inherited from DPMBase
virtual void computeAllForces ()
Computes all the forces acting on the particles using the BaseInteractable::setForce() and BaseInteractable::setTorque()
virtual void computeInternalForces (BaseParticle *)
Computes the internal forces on particle i (internal in the sense that the sum over all these forces is zero i.e. fully modelled forces)
virtual void computeInternalForce (BaseParticle *, BaseParticle *)
Computes the forces between two particles (internal in the sense that the sum over all these forces is zero i.e. fully modelled forces)
virtual void computeExternalForces (BaseParticle *)
Computes the external forces, such as gravity, acting on particles.
virtual void computeForcesDueToWalls (BaseParticle *, BaseWall *)
Computes the forces on the particles due to the walls (normals are outward normals)
virtual void actionsOnRestart ()
A virtual function where the users can add extra code which is executed only when the code is restarted.
virtual void actionsBeforeTimeLoop ()
A virtual function. Allows one to carry out any operations before the start of the time loop.
virtual void actionsBeforeTimeStep ()
A virtual function which allows to define operations to be executed before the new time step.
virtual void computeAdditionalForces ()
A virtual function which allows to define operations to be executed prior to the OMP force collect.
virtual void actionsAfterSolve ()
A virtual function which allows to define operations to be executed after the solve().
virtual void actionsAfterTimeStep ()
A virtual function which allows to define operations to be executed after time step.
void writeVTKFiles () const
virtual void outputXBallsData (std::ostream &os) const
This function writes the location of the walls and particles in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void outputXBallsDataParticle (unsigned int i, unsigned int format, std::ostream &os) const
This function writes out the particle locations into an output stream in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void writeEneHeader (std::ostream &os) const
Writes a header with a certain format for ENE file.
virtual void writeFstatHeader (std::ostream &os) const
Writes a header with a certain format for FStat file.
virtual void writeEneTimeStep (std::ostream &os) const
Write the global kinetic, potential energy, etc. in the system.
virtual void initialiseStatistics ()
virtual void outputStatistics ()
void gatherContactStatistics ()
virtual void processStatistics (bool)
virtual void finishStatistics ()
virtual void integrateBeforeForceComputation ()
Update particles' and walls' positions and velocities before force computation.
virtual void integrateAfterForceComputation ()
Update particles' and walls' positions and velocities after force computation.
virtual void checkInteractionWithBoundaries ()
There are a range of boundaries one could implement depending on ones' problem. This methods checks for interactions between particles and such range of boundaries. See BaseBoundary.h and all the boundaries in the Boundaries folder.
void setFixedParticles (unsigned int n)
Sets a number, n, of particles in the particleHandler as "fixed particles".
virtual void printTime () const
Displays the current simulation time and the maximum simulation duration.
virtual bool continueSolve () const
A virtual function for deciding whether to continue the simulation, based on a user-specified criterion.
void outputInteractionDetails () const
Displays the interaction details corresponding to the pointer objects in the interaction handler.
bool isTimeEqualTo (Mdouble time) const
Checks whether the input variable "time" is the current time in the simulation.
void removeDuplicatePeriodicParticles ()
Removes periodic duplicate Particles.
void checkAndDuplicatePeriodicParticles ()
For simulations using periodic boundaries, checks and adds particles when necessary into the particle handler. See DPMBase.cc and PeriodicBoundary.cc for more details.
void performGhostParticleUpdate ()
When the Verlet scheme updates the positions and velocities of particles, ghost particles will need an update as wel. Their status will also be updated accordingly.
void deleteGhostParticles (std::set< BaseParticle * > &particlesToBeDeleted)
void synchroniseParticle (BaseParticle *, unsigned fromProcessor=0)
void performGhostVelocityUpdate ()
updates the final time-step velocity of the ghost particles
void disableSoftStop ()
This prevents the initialisation of the soft stop feature.
void discontinueSolve ()
This discontinues the solve loop after the current time step is finished.
Private Attributes
HGrid * grid
A pointer to the HGrid associated with this MercuryBase.
HGridMethod hGridMethod_
Indicator of which way the interactions between different levels are tested.
HGridDistribution hGridDistribution_
Indicator for the distribution of the sizes of the cells of different levels of the HGrid. The default is EXPONENTIAL.
Mdouble currentMaxRelativeDisplacement_
Mdouble that denotes the maximum of the displacement of a particle divided by the cell size of the level of that particle at the current time step. This is useful to see whether a particle could have moved more than one cell.
Mdouble totalCurrentMaxRelativeDisplacement_
After each time step, this Mdouble is increased by 2*currentMaxRelativeDisplacement_.
bool gridNeedsUpdate_
Boolean that indicates whether or not the grid needs to be updated.
bool updateEachTimeStep_
Boolean which indicates whether or not the cell in which a particle is must be updated every time step.
unsigned int hGridMaxLevels_
Unsigned integer that indicates the maximum number of levels of the HGrid.
Mdouble hGridCellOverSizeRatio_
The maximum ratio between the size of the cells and the BaseParticle they contain.
Additional Inherited Members
Public Types inherited from DPMBase
enum class ReadOptions : int { ReadAll , ReadNoInteractions , ReadNoParticlesAndInteractions }
enum class DomainSplit {
X , Y , Z , XY ,
XZ , YZ , XYZ
}
Static Public Member Functions inherited from DPMBase
static void incrementRunNumberInFile ()
Increment the run Number (counter value) stored in the file_counter (COUNTER_DONOTDEL) by 1 and store the new value in the counter file.
static int readRunNumberFromFile ()
Read the run number or the counter from the counter file (COUNTER_DONOTDEL)
static bool areInContact (const BaseParticle *pI, const BaseParticle *pJ)
Checks if two particle are in contact or is there any positive overlap.
Public Attributes inherited from DPMBase
SpeciesHandler speciesHandler
A handler to that stores the species type i.e. LinearViscoelasticSpecies, etc.
RNG random
This is a random generator, often used for setting up the initial conditions etc...
ParticleHandler particleHandler
An object of the class ParticleHandler, contains the pointers to all the particles created.
ParticleHandler paoloParticleHandler
Fake particleHandler created by Paolo needed temporary by just Paolo.
WallHandler wallHandler
An object of the class WallHandler. Contains pointers to all the walls created.
BoundaryHandler boundaryHandler
An object of the class BoundaryHandler which concerns insertion and deletion of particles into or from regions.
PeriodicBoundaryHandler periodicBoundaryHandler
Internal handler that deals with periodic boundaries, especially in a parallel build.
DomainHandler domainHandler
An object of the class DomainHandler which deals with parallel code.
InteractionHandler interactionHandler
An object of the class InteractionHandler.
CGHandler cgHandler
Object of the class cgHandler.
File dataFile
An instance of class File to handle in- and output into a .data file.
File fStatFile
An instance of class File to handle in- and output into a .fstat file.
File eneFile
An instance of class File to handle in- and output into a .ene file.
File restartFile
An instance of class File to handle in- and output into a .restart file.
File statFile
An instance of class File to handle in- and output into a .stat file.
File interactionFile
File class to handle in- and output into .interactions file. This file hold information about interactions.
Time clock_
record when the simulation started
Detailed Description
This is the base class for both Mercury2D and Mercury3D. Note the actually abstract grid is defined in the class Grid defined below.
Todo:
Discuss if we want to remove Mercury2D and Mercury3D and template MercuryBase as the interface for the user.
Constructor & Destructor Documentation
MercuryBase() [1/2]
MercuryBase::MercuryBase ()
This is the default constructor. It sets sensible defaults.
 {
     constructor();
     logger(DEBUG, "MercuryBase::MercuryBase() constructor finished");
 }
References constructor(), DEBUG, and logger.
~MercuryBase()
MercuryBase::~MercuryBase () override
This is the default destructor.
 {
     if (grid != nullptr)
     {
         delete grid;
         grid = nullptr;
     }
     logger(DEBUG, "MercuryBase::~MercuryBase() destructor finished.");
 }
References DEBUG, grid, and logger.
MercuryBase() [2/2]
MercuryBase::MercuryBase (const MercuryBase & mercuryBase)
Copy-constructor.
Parameters
[in] mercuryBase The MercuryBase that needs to be copied.
Copy constructor that copies almost all properties of the given MercuryBase into the new MercuryBase. Please note that the grid is not literally copied, but everything to make that grid is copied and the gridNeedsUpdate_ is set to true, so that the grid is made before anything else happens.
 {
     grid = nullptr;
     gridNeedsUpdate_ = true;
     hGridMethod_ = mercuryBase.hGridMethod_;
     hGridDistribution_ = mercuryBase.hGridDistribution_;
     currentMaxRelativeDisplacement_ = mercuryBase.currentMaxRelativeDisplacement_;
     totalCurrentMaxRelativeDisplacement_ = mercuryBase.totalCurrentMaxRelativeDisplacement_;
     updateEachTimeStep_ = mercuryBase.updateEachTimeStep_;
     hGridMaxLevels_ = mercuryBase.hGridMaxLevels_;
     hGridCellOverSizeRatio_ = mercuryBase.hGridCellOverSizeRatio_;
     logger(DEBUG, "HGRID_base(HGrid_base& other) constructor finished.");
 }
References currentMaxRelativeDisplacement_, DEBUG, grid, gridNeedsUpdate_, hGridCellOverSizeRatio_, hGridDistribution_, hGridMaxLevels_, hGridMethod_, logger, totalCurrentMaxRelativeDisplacement_, and updateEachTimeStep_.
Member Function Documentation
checkParticleForInteraction()
bool MercuryBase::checkParticleForInteraction (const BaseParticle & p) final virtual
Checks if given BaseParticle has an interaction with a BaseWall or other BaseParticle.
Parameters
[in] p The BaseParticle for which we want to check if there is an interaction.
Returns
A boolean which is false if there was an interaction and true if there was no interaction.
Check for the given BaseParticle if there is an interaction with any other object. First check all walls, then all particles.
Todo:
IFCD: I think it might be better if it returns true if there is an interaction.
Todo:
MX: use all reduce with the appropriate operator
Reimplemented from DPMBase.
 {
 #ifdef MERCURYDPM_USE_MPI
     bool interaction;
     if (NUMBER_OF_PROCESSORS == 1)
     {
         interaction = checkParticleForInteractionLocalPeriodic(p);
     }
     else
     {
         //check locally and then collectively come to a global conclusion
         bool interactionLocal = checkParticleForInteractionLocal(p);
         MPIContainer::Instance().allReduce(interactionLocal, interaction,  MPI_LAND);
     }
 #else
     bool interaction = checkParticleForInteractionLocalPeriodic(p);
 #endif
     return interaction;
 }
References checkParticleForInteractionLocal(), DPMBase::checkParticleForInteractionLocalPeriodic(), MPIContainer::Instance(), NUMBER_OF_PROCESSORS, and p.
Referenced by SmoothChute::actionsBeforeTimeStep(), AngleOfRepose::actionsBeforeTimeStep(), Chutebelt::actionsOnRestart(), ChutePeriodic::add_flow_particles(), SilbertPeriodic::add_flow_particles(), Chute::addFlowParticlesCompactly(), BaseCluster::computeInternalStructure(), Chute::createBottom(), InitialConditions< SpeciesType >::InitialConditions(), main(), BaseCluster::particleInsertionSuccessful(), LawinenBox::setupInitialConditions(), ClosedCSCWalls::setupInitialConditions(), CSCInit::setupInitialConditions(), CSCWalls::setupInitialConditions(), SmoothChute::setupInitialConditions(), CubicCell::setupInitialConditions(), MinimalExampleDrum::setupInitialConditions(), InitialBed::setupInitialConditions(), ParticleCreation::setupInitialConditions(), TriangulatedScrewSelfTest::setupInitialConditions(), TriangulatedWallSelfTest::setupInitialConditions(), DrumRot::setupInitialConditions(), RotatingDrum::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), MpiPeriodicBoundaryUnitTest::setupInitialConditions(), and ChuteBottom::setupInitialConditions().
checkParticleForInteractionLocal()
bool MercuryBase::checkParticleForInteractionLocal (const BaseParticle & p) final virtual
Checks if the given BaseParticle has an interaction with a BaseWall or other BaseParticles in a local domain.
Parameters
[in] p The BaseParticle for which we want to check if there is an interaction.
Returns
A boolean which is false if there was an interaction and true if there was no interaction.
Check for the given BaseParticle if there is an interaction with any other object. First check all walls, then all particles in the local domain.
Todo:
IFCD: I think it might be better if it returns true if there is an interaction.
Reimplemented from DPMBase.
 {
     Mdouble distance;
     Vec3D normal;
     //Check if it has no collision with walls
     for (BaseWall* w :wallHandler)
     {
         if (w->getDistanceAndNormal(p, distance, normal))
         {
             logger(VERBOSE, "Collision with wall %.", *w);
             return false;
         }
         else
         {
             logger(VERBOSE, "No collision with wall %.", *w);
         }
     }
     //Check if it has no collision with other particles
     if (hGridHasParticleContacts(&p))
     {
         logger(VERBOSE, "Collision with particle.");
         return false;
     }
     else
     {
         logger(VERBOSE, "No collision with particles.");
     }
     return true;
 }
References hGridHasParticleContacts(), logger, WallFunction::normal(), p, VERBOSE, w, and DPMBase::wallHandler.
Referenced by checkParticleForInteraction().
constructor()
void MercuryBase::constructor ()
This is the actual constructor, it is called do both constructors above.
Function that is called by the default constructor, it sets all parameters for the MercuryBase to sensible defaults.
 {
     grid = nullptr;
     gridNeedsUpdate_ = true;
     hGridMaxLevels_ = 3;
     hGridCellOverSizeRatio_ = 1.0;
     updateEachTimeStep_ = true;
     hGridDistribution_ = EXPONENTIAL;
     hGridMethod_ = TOPDOWN;
     currentMaxRelativeDisplacement_ = 0.0;
     totalCurrentMaxRelativeDisplacement_ = constants::inf;
 }
References currentMaxRelativeDisplacement_, EXPONENTIAL, grid, gridNeedsUpdate_, hGridCellOverSizeRatio_, hGridDistribution_, hGridMaxLevels_, hGridMethod_, constants::inf, TOPDOWN, totalCurrentMaxRelativeDisplacement_, and updateEachTimeStep_.
Referenced by MercuryBase().
getHGrid() [1/2]
HGrid* MercuryBase::getHGrid () inline protected
Gets the HGrid used by this problem.
Returns
A pointer to the HGrid associated with this MercuryBase.
     { return grid; }
References grid.
Referenced by EllipsoidsBouncingOnWallDemo::actionsAfterSolve(), EllipticalSuperQuadricCollision::actionsAfterSolve(), SphericalSuperQuadricCollision::actionsAfterSolve(), VisualisationTest::actionsAfterSolve(), Mercury2D::computeInternalForces(), Mercury3D::computeInternalForces(), DPM::computeLocalCGHGrid(), DPM::computeLocalVolumeFractionHGrid(), Mercury3D::computeWallForces(), hGridActionsBeforeTimeStep(), Mercury3D::hGridFindContactsWithinTargetCell(), Mercury2D::hGridFindContactsWithinTargetCell(), Mercury3D::hGridFindContactsWithTargetCell(), Mercury2D::hGridFindContactsWithTargetCell(), Mercury2D::hGridFindParticleContacts(), Mercury3D::hGridFindParticleContacts(), Mercury3D::hGridFindParticlesWithTargetCell(), Mercury2D::hGridFindParticlesWithTargetCell(), Mercury2D::hGridGetInteractingParticleList(), Mercury3D::hGridGetInteractingParticleList(), Mercury3D::hGridHasContactsInTargetCell(), Mercury2D::hGridHasContactsInTargetCell(), Mercury2D::hGridHasParticleContacts(), Mercury3D::hGridHasParticleContacts(), hGridNeedsRebuilding(), Mercury2D::hGridRemoveParticle(), Mercury3D::hGridRemoveParticle(), hGridUpdateMove(), Mercury2D::hGridUpdateParticle(), and Mercury3D::hGridUpdateParticle().
getHGrid() [2/2]
const HGrid* MercuryBase::getHGrid () const inline protected
Gets the HGrid used by this problem, const version.
Returns
A pointer to the HGrid associated with this MercuryBase.
     { return grid; }
References grid.
getHGridCellOverSizeRatio()
Mdouble MercuryBase::getHGridCellOverSizeRatio () const
Gets the ratio of the smallest cell over the smallest particle.
Returns
The maximum ratio between the cells and the size of the BaseParticle it contains.
 {
     return hGridCellOverSizeRatio_;
 }
References hGridCellOverSizeRatio_.
Referenced by hGridActionsAfterIntegration(), hGridActionsBeforeTimeStep(), and hGridRebuild().
getHGridCurrentMaxRelativeDisplacement()
Mdouble MercuryBase::getHGridCurrentMaxRelativeDisplacement () const
Returns hGridCurrentMaxRelativeDisplacement_.
Returns
currentMaxRelativeDisplacement_, which is the highest relative speed of a BaseParticle compared to the cell size of the grid in which the BaseParticle is.
 {
     return currentMaxRelativeDisplacement_;
 }
References currentMaxRelativeDisplacement_.
getHGridDistribution()
HGridDistribution MercuryBase::getHGridDistribution () const
Gets how the sizes of the cells of different levels are distributed.
Returns
The HGridDistribution (distribution of cell sizes) used by this MercuryBase.
 {
     return hGridDistribution_;
 }
References hGridDistribution_.
Referenced by hGridRebuild().
getHGridMaxLevels()
unsigned int MercuryBase::getHGridMaxLevels () const
Gets the maximum number of levels of the HGrid in this MercuryBase.
Returns
The maximum number of levels in the HGrid.
 {
     return hGridMaxLevels_;
 }
References hGridMaxLevels_.
Referenced by hGridRebuild().
getHGridMethod()
HGridMethod MercuryBase::getHGridMethod () const inline
Gets whether the HGrid in this MercuryBase is BOTTOMUP or TOPDOWN.
Returns
The HGridMethod used by this MercuryBase.
     { return hGridMethod_; }
References hGridMethod_.
Referenced by Mercury2D::computeInternalForces(), and Mercury3D::computeInternalForces().
getHGridTargetMaxInteractionRadius()
Mdouble MercuryBase::getHGridTargetMaxInteractionRadius () const virtual
Gets the desired size of the largest cells of the HGrid.
Returns
The interaction radius of the largest particle multiplied by the maximum ratio between the cell size and particle size.
Reimplemented in CubicCell.
 {
     if (particleHandler.getSize() == 0)
     {
         return 0.0;
     }
     else
     {
         return particleHandler.getLargestInteractionRadiusLocal();
     }
 }
References ParticleHandler::getLargestInteractionRadiusLocal(), BaseHandler< T >::getSize(), and DPMBase::particleHandler.
Referenced by CubicCell::getHGridTargetMaxInteractionRadius(), and hGridRebuild().
getHGridTargetMinInteractionRadius()
Mdouble MercuryBase::getHGridTargetMinInteractionRadius () const virtual
Gets the desired size of the smallest cells of the HGrid.
Returns
The interaction radius of the smallest particle multiplied by the maximum ratio between the cell size and particle size.
 {
     if (particleHandler.getSize() == 0)
     {
         return 0.0;
     }
     else
     {
         return particleHandler.getSmallestInteractionRadiusLocal();
     }
 }
References BaseHandler< T >::getSize(), ParticleHandler::getSmallestInteractionRadiusLocal(), and DPMBase::particleHandler.
Referenced by hGridRebuild().
getHGridTargetNumberOfBuckets()
unsigned int MercuryBase::getHGridTargetNumberOfBuckets () const virtual
Gets the desired number of buckets, which is the maximum of the number of particles and 10.
Returns
The number of possible values the hash function can have.
Todo:
TW SpeedCheckThomas revealed that adding a factor 10 here improved performance by 20% for monodisperse particles, 45% for highly polydisperse (this seems true for particle numbers 1e3 - 1e6); a larger factor seems to little extra effect; the memory cost is small compared to the number of particles, so I added the factor permanently. At Irana, please check this is ok to do.
 {
     unsigned int nParticles = particleHandler.getSize();
     if (nParticles > 10)
     {
         return 10 * nParticles;
     }
     else
     {
         return 10;
     }
 }
References BaseHandler< T >::getSize(), MergeRestartFiles::nParticles, and DPMBase::particleHandler.
Referenced by hGridNeedsRebuilding(), and hGridRebuild().
getHGridTotalCurrentMaxRelativeDisplacement()
Mdouble MercuryBase::getHGridTotalCurrentMaxRelativeDisplacement () const
Returns hGridTotalCurrentMaxRelativeDisplacement_.
Returns
totalCurrentMaxRelativeDisplacement_, which is the cumulative value of 2*currentMaxRelativeDisplacement_
 {
     return totalCurrentMaxRelativeDisplacement_;
 }
References totalCurrentMaxRelativeDisplacement_.
Referenced by DPM::actionsBeforeTimeStep(), and hGridActionsBeforeTimeStep().
getHGridUpdateEachTimeStep()
bool MercuryBase::getHGridUpdateEachTimeStep () const final virtual
Gets whether or not the HGrid is updated every time step.
Returns
A boolean which indicates if the HGrid must be updated every time step.
Reimplemented from DPMBase.
 {
     return updateEachTimeStep_;
 }
References updateEachTimeStep_.
Referenced by hGridActionsBeforeTimeStep(), and ChuteWithPeriodicInflow::integrateBeforeForceComputation().
hGridActionsAfterIntegration()
void MercuryBase::hGridActionsAfterIntegration () override protected virtual
This function has to be called before integrateBeforeForceComputation.
Sets the totalCurrentMaxRelativeDisplacement
Reimplemented from DPMBase.
 {
     currentMaxRelativeDisplacement_ = 2.0 * std::sqrt(currentMaxRelativeDisplacement_) * getHGridCellOverSizeRatio();
     totalCurrentMaxRelativeDisplacement_ += currentMaxRelativeDisplacement_;
 }
References currentMaxRelativeDisplacement_, getHGridCellOverSizeRatio(), sqrt(), and totalCurrentMaxRelativeDisplacement_.
hGridActionsBeforeIntegration()
void MercuryBase::hGridActionsBeforeIntegration () override protected virtual
Resets the currentMaxRelativeDisplacement_ to 0.
Sets the currentMaxRelativeDisplacement to zero
Reimplemented from DPMBase.
 {
     currentMaxRelativeDisplacement_ = 0.0;
 }
References currentMaxRelativeDisplacement_.
hGridActionsBeforeTimeLoop()
void MercuryBase::hGridActionsBeforeTimeLoop () override virtual
This sets up the broad phase information, has to be done at this stage because it requires the particle size.
Performs all actions that need to be done before the time loop. At the moment, this means nothing.
Reimplemented from DPMBase.
 {
 }
Referenced by SilbertPeriodic::add_flow_particles(), Chute::createBottom(), LawinenBox::setupInitialConditions(), and ChuteBottom::setupInitialConditions().
hGridActionsBeforeTimeStep()
void MercuryBase::hGridActionsBeforeTimeStep () override virtual
Performs all necessary actions before a time-step, like updating the particles and resetting all the bucket information, etc.
The actions that are done before each time step, it rebuilds the HGrid if necessary, otherwise it computes which cell each particle is in.
Reimplemented from DPMBase.
 {
     if (hGridNeedsRebuilding())
     {
         //logger(INFO, "HGrid needs rebuilding at nt=%",getNumberOfTimeSteps());
         hGridRebuild();
     }
     else
     {
 #ifndef CONTACT_LIST_HGRID
         getHGrid()->clearBucketIsChecked();
 #endif
         if (getHGridUpdateEachTimeStep() ||
             getHGridTotalCurrentMaxRelativeDisplacement() >= getHGridCellOverSizeRatio() - 1)
         {
 #ifndef CONTACT_LIST_HGRID
             getHGrid()->clearFirstBaseParticleInBucket();
 #endif
             //logger(INFO, "HGrid needs updating at nt=%",getNumberOfTimeSteps());
             for (BaseParticle* const p : particleHandler)
             {
                 hGridUpdateParticle(p);
             }
             totalCurrentMaxRelativeDisplacement_ = 0;
         }
     }
 }
References HGrid::clearBucketIsChecked(), HGrid::clearFirstBaseParticleInBucket(), getHGrid(), getHGridCellOverSizeRatio(), getHGridTotalCurrentMaxRelativeDisplacement(), getHGridUpdateEachTimeStep(), hGridNeedsRebuilding(), hGridRebuild(), DPMBase::hGridUpdateParticle(), p, DPMBase::particleHandler, and totalCurrentMaxRelativeDisplacement_.
Referenced by SilbertPeriodic::add_flow_particles(), Chute::createBottom(), and LawinenBox::setupInitialConditions().
hGridFindParticleContacts()
virtual std::vector<BaseParticle*> MercuryBase::hGridFindParticleContacts (const BaseParticle * obj) pure virtual
Purely virtual function that returns all particles that have a contact with a given particle.
Implemented in Mercury3D, and Mercury2D.
hGridHasParticleContacts()
virtual bool MercuryBase::hGridHasParticleContacts (const BaseParticle * obj) protected pure virtual
Purely virtual function that checks if the given particle has a possible contact with any other BaseParticle in the HGrid.
Implemented in Mercury3D, and Mercury2D.
Referenced by checkParticleForInteractionLocal().
hGridInfo()
void MercuryBase::hGridInfo (std::ostream & os = std::cout) const
Writes the info of the HGrid to the screen in a nice format.
 {
 #ifdef MERCURYDPM_USE_MPI
     MPIContainer& communicator = MPIContainer::Instance();
     int numberOfProcessors = communicator.getNumberOfProcessors();
 #else
     int numberOfProcessors = 1;
 #endif
     os << "hGrid"
        << " method " << hGridMethod_
        << " distribution " << hGridDistribution_
        << " cellOverSizeRatio " << hGridCellOverSizeRatio_;
     //os << " maxLevels " << hGridMaxLevels_;
     if (numberOfProcessors == 1 && grid != nullptr)
     {
         os << " numberOfBuckets " << grid->getNumberOfBuckets()
            << " cellSizes";
         for (const auto p: grid->getCellSizes()) os << " " << p;
     }
     os << " gridNeedsUpdate " << gridNeedsUpdate_
        << " updateEachTimeStep " << updateEachTimeStep_
        << " currentMaxRelativeDisplacement " << currentMaxRelativeDisplacement_
        << " totalCurrentMaxRelativeDisplacement " << totalCurrentMaxRelativeDisplacement_
        << std::endl;
 }
References currentMaxRelativeDisplacement_, HGrid::getCellSizes(), HGrid::getNumberOfBuckets(), MPIContainer::getNumberOfProcessors(), grid, gridNeedsUpdate_, hGridCellOverSizeRatio_, hGridDistribution_, hGridMethod_, MPIContainer::Instance(), p, totalCurrentMaxRelativeDisplacement_, and updateEachTimeStep_.
Referenced by main(), and write().
hGridInsertParticle()
void MercuryBase::hGridInsertParticle (BaseParticle * obj) final protected
Inserts a single Particle to current grid.
Parameters
[in] obj A pointer to the BaseParticle that needs to be inserted in the HGrid.
 {
     if (grid != nullptr)
     {
         grid->insertParticleToHgrid(obj);
     }
 }
References grid, and HGrid::insertParticleToHgrid().
Referenced by hGridRebuild().
hGridNeedsRebuilding()
bool MercuryBase::hGridNeedsRebuilding ()
Gets if the HGrid needs rebuilding before anything else happens.
Returns
A boolean which indicates if the HGrid needs to be rebuilt.
 {
     if (grid == nullptr)
     {
         logger(VERBOSE, "HGrid needs updating, because there is no grid.");
         return true;
     }
     else if (gridNeedsUpdate_)
     {
         logger(VERBOSE, "HGrid needs updating, because some of its initialisation parameters have changed.");
         return true;
     }
     else if (grid->getNeedsRebuilding())
     {
         logger(VERBOSE, "HGrid needs updating, because said so by the grid itself");
         return true;
     }
     else if (getHGrid()->getNumberOfBuckets() > 10 * getHGridTargetNumberOfBuckets() ||
              10 * getHGrid()->getNumberOfBuckets() < getHGridTargetNumberOfBuckets())
     {
         logger(VERBOSE, "HGrid needs updating, because of number of buckets, current = %, target = %.",
                grid->getNumberOfBuckets(), particleHandler.getSize());
         return true;
     }
     else if (particleHandler.getLargestParticle() != nullptr &&
              2.0 * particleHandler.getLargestParticle()->getMaxInteractionRadius() >
              getHGrid()->getCellSizes().back() * grid->getCellOverSizeRatio())
     {
         logger(VERBOSE, "HGrid needs updating, because of maximum cell size, current = %, required = %.",
                grid->getCellSizes().back() * hGridCellOverSizeRatio_,
                particleHandler.getLargestParticle()->getMaxInteractionRadius());
         return true;
     }
     else
     {
         //std::cout<<"HGrid does not need updating, because of number of buckets, current="<<grid->NUM_BUCKETS<<" target="<<particleHandler.getSize()<<std::endl;
         //std::cout<<"HGrid does not need updating, because of maximum cell size, current="<<grid->cellSizes_.back()*grid->cellOverSizeRatio_<<" required="<<2.0*particleHandler.getLargestParticle()->getInteractionRadius()<<std::endl;
         return false;
     }
 }
References HGrid::getCellOverSizeRatio(), HGrid::getCellSizes(), getHGrid(), getHGridTargetNumberOfBuckets(), ParticleHandler::getLargestParticle(), BaseParticle::getMaxInteractionRadius(), HGrid::getNeedsRebuilding(), HGrid::getNumberOfBuckets(), BaseHandler< T >::getSize(), grid, gridNeedsUpdate_, hGridCellOverSizeRatio_, logger, DPMBase::particleHandler, and VERBOSE.
Referenced by CubicCell::actionsAfterTimeStep(), hGridActionsBeforeTimeStep(), Mercury3D::hGridGetInteractingParticleList(), and ParticleCreation::setupInitialConditions().
hGridRebuild()
void MercuryBase::hGridRebuild () protected
This sets up the parameters required for the contact model.
Rebuild the HGrid with the current data. First compute the cell sizes of the new HGrid, then delete the old HGrid and build the new HGrid. Finally add all particles to the new HGrid. First check if either the ParticleHandler is empty or the particle distribution is monodispersed. If this is the case, make a grid that contains only one level which has a cell size defined by the diameter of the particle * hGridCellOverSizeRatio_. Otherwise, make cell sizes depending on the distribution given in hGridDistribution_. LINEAR and EXPONENTIAL first compute the smallest and biggest cell size, and then compute the ones in between according to the distribution. USER just takes the cell sizes given by the user. OLDHGRID computes the smallest cell size and then makes the cells of each subsequent level twice as big.
Todo:
 {
     std::vector<Mdouble> cellSizes;
     const Mdouble minParticleInteractionRadius = getHGridTargetMinInteractionRadius();
     const Mdouble maxParticleInteractionRadius = getHGridTargetMaxInteractionRadius();
     if (minParticleInteractionRadius == 0.0 || minParticleInteractionRadius == maxParticleInteractionRadius)
     {
         //this case is executed if the particleHandler is empty (minParticleInteractionRadius == 0)
         //or if the particle distribution is monodispersed.
         //nextafter(d,std::numeric_limits<Mdouble>::max()) chooses the smallest
         // Mdouble that is bigger than d.
         const Mdouble maxCellSize = nextafter(2.0 * maxParticleInteractionRadius * getHGridCellOverSizeRatio(),
                                               std::numeric_limits<Mdouble>::max());
         cellSizes.push_back(maxCellSize);
         if (getHGridMaxLevels() != 1)
         {
             logger(VERBOSE,
                    "While rebuilding the hgrid: the number of levels was set to one, as the particle distribution is monodispersed");
         }
     }
     else
     {
         switch (getHGridDistribution())
         {
             case LINEAR:
             {
                 const Mdouble minCellSize = nextafter(2.0 * minParticleInteractionRadius * getHGridCellOverSizeRatio(),
                                                       0.0);
                 const Mdouble maxCellSize = nextafter(2.0 * maxParticleInteractionRadius * getHGridCellOverSizeRatio(),
                                                       std::numeric_limits<Mdouble>::max());
                 //std::cout << "HGrid: using a linear cell size distribution from " << minCellSize << " to " << maxCellSize << " over " << getHGridMaxLevels() << " levels" << std::endl;
                 for (unsigned int i = 0; i + 1 < getHGridMaxLevels(); i++)
                 {
                     cellSizes.push_back(minCellSize + (maxCellSize - minCellSize)
                                                       * (static_cast<Mdouble>(i + 1)) / getHGridMaxLevels());
                 }
                 //The last cell is added separately because in some cases accuracy was lost when calculating it.
                 cellSizes.push_back(maxCellSize);
                 break;
             }
             case EXPONENTIAL:
             {
                 const Mdouble minCellSize = nextafter(2.0 * minParticleInteractionRadius * getHGridCellOverSizeRatio(),
                                                       0.0);
                 const Mdouble maxCellSize = nextafter(2.0 * maxParticleInteractionRadius * getHGridCellOverSizeRatio(),
                                                       std::numeric_limits<Mdouble>::max());
                 logger(INFO,"HGrid: using exponential cell size distribution from % to % over % levels",
                        minCellSize,maxCellSize,getHGridMaxLevels());
                 for (unsigned int i = 0; i + 1 < getHGridMaxLevels(); i++)
                 {
                     cellSizes.push_back(minCellSize
                                         * std::pow(maxCellSize / minCellSize, static_cast<Mdouble>(i + 1)
                                                                               / getHGridMaxLevels()));
                 }
                 //The last cell is added separately because in some cases accuracy was lost when calculating it.
                 cellSizes.push_back(maxCellSize);
                 break;
             }
             case USER:
             {
                 for (unsigned int i = 0; i < getHGridMaxLevels(); i++)
                 {
                     cellSizes.push_back(userHGridCellSize(i));
                 }
                 break;
             }
             case OLDHGRID:
             {
                 const Mdouble minCellSize = nextafter(2.0 * minParticleInteractionRadius * getHGridCellOverSizeRatio(),
                                                       0.0);
                 //std::cout<<"HGrid: using the old HGrid cell size distribution starting from " <<minCellSize<<std::endl;
                 for (unsigned int i = 0; i < getHGridMaxLevels(); i++)
                 {
                     cellSizes.push_back(minCellSize * std::pow(2, i));
                 }
                 break;
             }
         }
     }
 //    //Make sure the cell size is at less 10 times the smallest number
 //    for (unsigned int i = 0; i < getHGridMaxLevels(); i++)
 //    {
 //        if (cellSizes[i]<(10+i)*std::numeric_limits<double>::min()) cellSizes[i]=(10+i)*std::numeric_limits<double>::min();
 //    }
     delete grid;
     grid = new HGrid(getHGridTargetNumberOfBuckets(), getHGridCellOverSizeRatio(), cellSizes);
     for (BaseParticle* const p : particleHandler)
     {
         hGridInsertParticle(p);
         p->setHGridX(9999);
         hGridUpdateParticle(p);
     }
     gridNeedsUpdate_ = false;
 }
References EXPONENTIAL, getHGridCellOverSizeRatio(), getHGridDistribution(), getHGridMaxLevels(), getHGridTargetMaxInteractionRadius(), getHGridTargetMinInteractionRadius(), getHGridTargetNumberOfBuckets(), grid, gridNeedsUpdate_, hGridInsertParticle(), DPMBase::hGridUpdateParticle(), i, INFO, LINEAR, logger, max, Eigen::numext::nextafter(), OLDHGRID, p, DPMBase::particleHandler, Eigen::bfloat16_impl::pow(), USER, userHGridCellSize(), and VERBOSE.
Referenced by CubicCell::actionsAfterTimeStep(), Mercury3D::computeWallForces(), hGridActionsBeforeTimeStep(), Mercury2D::hGridFindParticleContacts(), Mercury3D::hGridFindParticleContacts(), Mercury3D::hGridGetInteractingParticleList(), Mercury2D::hGridHasParticleContacts(), Mercury3D::hGridHasParticleContacts(), InitialConditions< SpeciesType >::InitialConditions(), ParticleCreation::setupInitialConditions(), DrumRot::setupInitialConditions(), and RotatingDrum::setupInitialConditions().
hGridUpdateMove()
void MercuryBase::hGridUpdateMove (BaseParticle * iP, Mdouble move) final protected virtual
Computes the relative displacement of the given BaseParticle and updates the currentMaxRelativeDisplacement_ accordingly.
(the factor 2.0 is because the displacement is applied after and before the force computation in velocity verlet)
Parameters
[in] iP A pointer to the BaseParticle for which we want to compare the relative speed to the currentMaxRelativeDisplacement_ to.
[in] move An Mdouble that represents the square of the distance the BaseParticle has moved.
Reimplemented from DPMBase.
 {
     const Mdouble currentRelativeDisplacement = move / mathsFunc::square(getHGrid()->getCellSize(iP->getHGridLevel()));
     if (currentRelativeDisplacement > currentMaxRelativeDisplacement_)
     {
         currentMaxRelativeDisplacement_ = currentRelativeDisplacement;
     }
 }
References currentMaxRelativeDisplacement_, getHGrid(), BaseParticle::getHGridLevel(), and mathsFunc::square().
read()
void MercuryBase::read (std::istream & is, ReadOptions opt = ReadOptions::ReadAll) override virtual
Reads the MercuryBase from an input stream, for example a restart file.
Parameters
[in,out] is The input stream from which the MercuryBase must be read.
This function reads first the properties that are DPMBase related from the given input stream, after that it reads the hGridMaxLevels_ and the hGridCellOverSizeRatio_ from the input stream.
Reimplemented from DPMBase.
 {
     DPMBase::read(is, opt);
     std::stringstream line;
     helpers::getLineFromStringStream(is, line);
     std::string dummy;
     line >> dummy;
     // if-statement is needed in case a DPMBase (which does not contain the hGrid data)
     // is read into MercuryBase class
     if (dummy == "hGrid")
     {
         line >> dummy >> hGridMethod_;
         line >> dummy >> hGridDistribution_;
         line >> dummy >> hGridCellOverSizeRatio_;
         //the extra information here is not needed
         do
         {
             line >> dummy;
         } while (dummy != "gridNeedsUpdate");
         line >> gridNeedsUpdate_;
         line >> dummy >> updateEachTimeStep_;
         line >> dummy >> currentMaxRelativeDisplacement_;
         line >> dummy >> totalCurrentMaxRelativeDisplacement_;
     }
 }
References currentMaxRelativeDisplacement_, helpers::getLineFromStringStream(), gridNeedsUpdate_, hGridCellOverSizeRatio_, hGridDistribution_, hGridMethod_, calibrate::line, DPMBase::read(), oomph::Global_string_for_annotation::string(), totalCurrentMaxRelativeDisplacement_, and updateEachTimeStep_.
Referenced by MembraneDemo::read(), MembraneSelfTest::read(), BaseCluster::read(), and Chute::read().
readNextArgument()
bool MercuryBase::readNextArgument (int & i, int argc, char * argv[]) override protected virtual
Reads the next command line argument.
Parameters
[in] i The ordinal number in the input arguments we want to read.
[in] argc The number of arguments in the command line, not used.
[in] argv The command line input arguments.
Returns
A boolean which is true if the argument is found and false otherwise.
Reimplemented from DPMBase.
 {
     if (!strcmp(argv[i], "-hGridMaxLevels"))
     {
         setHGridMaxLevels(static_cast<unsigned int>(atoi(argv[i + 1])));
     }
     else if (!strcmp(argv[i], "-cellOverSizeRatio"))
     {
         setHGridCellOverSizeRatio(atof(argv[i + 1]));
     }
     else
     {
         return DPMBase::readNextArgument(i, argc, argv); //if argv[i] is not found, check the commands in MD
     }
     return true; //returns true if argv[i] is found
 }
References i, DPMBase::readNextArgument(), setHGridCellOverSizeRatio(), and setHGridMaxLevels().
Referenced by Chute::readNextArgument(), and Mercury3DRestart::readNextArgument().
setHGridCellOverSizeRatio()
void MercuryBase::setHGridCellOverSizeRatio (Mdouble hGridCellOverSizeRatio)
Sets the ratio of the smallest cell over the smallest particle.
Parameters
[in] hGridCellOverSizeRatio The desired maximum ratio between the cells and the size of the BaseParticle it contains.
Todo:
IFCD: I changed the if unequal to if equal, can someone check this is correct?
 {
     //If the hGridCellOverSizeRatio changes significantly, assign the given parameter.
     if (!mathsFunc::isEqual(hGridCellOverSizeRatio_, hGridCellOverSizeRatio, 1e-10))
     {
         gridNeedsUpdate_ = true;
         hGridCellOverSizeRatio_ = hGridCellOverSizeRatio;
     }
 }
References e(), gridNeedsUpdate_, hGridCellOverSizeRatio_, and mathsFunc::isEqual().
Referenced by readNextArgument().
setHGridDistribution()
void MercuryBase::setHGridDistribution (HGridDistribution hGridDistribution)
Sets how the sizes of the cells of different levels are distributed.
Parameters
[in] hGridDistribution The distribution of the cell sizes that will be used by this MercuryBase.
 {
     if (hGridDistribution_ != hGridDistribution)
     {
         gridNeedsUpdate_ = true;
         hGridDistribution_ = hGridDistribution;
     }
 }
References gridNeedsUpdate_, and hGridDistribution_.
Referenced by ChutePeriodic::add_flow_particles(), and main().
setHGridMaxLevels()
void MercuryBase::setHGridMaxLevels (unsigned int hGridMaxLevels)
Sets the maximum number of levels of the HGrid in this MercuryBase.
Parameters
[in] hGridMaxLevels The maximum number of levels that will be used in the HGrid.
 {
     if (hGridMaxLevels_ != hGridMaxLevels)
     {
         gridNeedsUpdate_ = true;
         hGridMaxLevels_ = hGridMaxLevels;
     }
 }
References gridNeedsUpdate_, and hGridMaxLevels_.
Referenced by main(), MultiParticlesInsertion::MultiParticlesInsertion(), readNextArgument(), DistributionToPSDSelfTest::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), MultiplePSDSelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), PSDManualInsertionSelfTest::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), and ChuteBottom::setupInitialConditions().
setHGridMethod()
void MercuryBase::setHGridMethod (HGridMethod hGridMethod)
Sets the HGridMethod to either BOTTOMUP or TOPDOWN.
Parameters
[in] hGridMethod The HGridMethod that will be used in this MercuryBase.
 {
     hGridMethod_ = hGridMethod;
 }
References hGridMethod_.
Referenced by main().
setHGridUpdateEachTimeStep()
void MercuryBase::setHGridUpdateEachTimeStep (bool updateEachTimeStep)
Sets whether or not the HGrid must be updated every time step.
Parameters
[in] updateEachTimeStep A boolean which indicates if the HGrid must be updated every time step.
 {
     updateEachTimeStep_ = updateEachTimeStep;
 }
References updateEachTimeStep_.
userHGridCellSize()
Mdouble MercuryBase::userHGridCellSize (unsigned int level) virtual
Virtual function that enables inheriting classes to implement a function to let the user set the cell size of the HGrid.
Parameters
[in] level The level of the cell we want to know the size set by the user for.
Returns
The size of the cells at the given level.
 {
     logger(WARN, "In Mdouble MercuryBase::userHGridCellSize(unsigned int level) with level= %", level);
     logger(WARN, "If you want to use user defined HGrid cell sizes, this function should be redefined");
     return 0.0;
 }
References logger, and WARN.
Referenced by hGridRebuild().
write()
void MercuryBase::write (std::ostream & os, bool writeAllParticles = true) const override virtual
Writes all data into a restart file.
Parameters
[in,out] os The output stream to which this MercuryBase must be written.
[in] writeAllParticles A boolean which indicates whether or not all BaseParticle from the ParticleHandler must be written to the ostream. If it is set to true or if there are at most 4 BaseParticle, all BaseParticle are written. If it is set to false, only the first two BaseParticle are written, followed by ...
Function that writes this MercuryBase to an output stream, for example a restart file. First writes the domain information, then the walls, followed by the boundaries and particles, and finally the HGrid information.
Reimplemented from DPMBase.
 {
     DPMBase::write(os, writeAllParticles);
     hGridInfo(os);
 }
References hGridInfo(), and DPMBase::write().
Referenced by ThermalConductionSelfTest::actionsBeforeTimeStep(), LaserOnLayer::LaserOnLayer(), main(), free_cooling::setupInitialConditions(), restart::setupInitialConditions(), ForceLawsMPI2Test::setupInitialConditions(), ShiftingConstantMassFlowMaserBoundarySelfTest::setupInitialConditions(), ShiftingMaserBoundarySelfTest::setupInitialConditions(), InitialBed::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), SubcriticalMaserBoundarySelfTest::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), ShapesDemo::setupInitialConditions(), SingleParticleIndenter::SingleParticleIndenter(), SegregationPeriodic::write(), MembraneDemo::write(), MembraneSelfTest::write(), BaseCluster::write(), and Chute::write().
Member Data Documentation
currentMaxRelativeDisplacement_
Mdouble MercuryBase::currentMaxRelativeDisplacement_ private
Mdouble that denotes the maximum of the displacement of a particle divided by the cell size of the level of that particle at the current time step. This is useful to see whether a particle could have moved more than one cell.
Referenced by constructor(), getHGridCurrentMaxRelativeDisplacement(), hGridActionsAfterIntegration(), hGridActionsBeforeIntegration(), hGridInfo(), hGridUpdateMove(), MercuryBase(), and read().
grid
HGrid* MercuryBase::grid private
A pointer to the HGrid associated with this MercuryBase.
Referenced by constructor(), getHGrid(), hGridInfo(), hGridInsertParticle(), hGridNeedsRebuilding(), hGridRebuild(), MercuryBase(), and ~MercuryBase().
gridNeedsUpdate_
bool MercuryBase::gridNeedsUpdate_ private
Boolean that indicates whether or not the grid needs to be updated.
The grid needs to be updated before the HGrid is constructed and whenever something of the HGrid changes, such as the distribution, the number of levels, etc.
Referenced by constructor(), hGridInfo(), hGridNeedsRebuilding(), hGridRebuild(), MercuryBase(), read(), setHGridCellOverSizeRatio(), setHGridDistribution(), and setHGridMaxLevels().
hGridCellOverSizeRatio_
Mdouble MercuryBase::hGridCellOverSizeRatio_ private
The maximum ratio between the size of the cells and the BaseParticle they contain.
The hGrifCellOverSizeRatio_ can be found by dividing the size of the smallest cell by the size of the smallest particle, so this can be set to give particles more space within a cell. Currently, the default is set to 1.
Referenced by constructor(), getHGridCellOverSizeRatio(), hGridInfo(), hGridNeedsRebuilding(), MercuryBase(), read(), and setHGridCellOverSizeRatio().
hGridDistribution_
HGridDistribution MercuryBase::hGridDistribution_ private
Indicator for the distribution of the sizes of the cells of different levels of the HGrid. The default is EXPONENTIAL.
Referenced by constructor(), getHGridDistribution(), hGridInfo(), MercuryBase(), read(), and setHGridDistribution().
hGridMaxLevels_
unsigned int MercuryBase::hGridMaxLevels_ private
Unsigned integer that indicates the maximum number of levels of the HGrid.
The number of levels in the HGrid is currently dependent on the maximum number of levels of the HGrid the user has given, either in the constructor or in setHGridMaxLevels, and whether the BaseParticle are monodispersed or not. If they are monodispersed, there is only one level in the HGrid, otherwise there are usually as many levels as the maximum set by the user. Note, by default the code sorts out these parameters itself but they can be overridden by the user.
Referenced by constructor(), getHGridMaxLevels(), MercuryBase(), and setHGridMaxLevels().
hGridMethod_
HGridMethod MercuryBase::hGridMethod_ private
Indicator of which way the interactions between different levels are tested.
If hGridMethod_ is TOPDOWN, then larger particles are inserted into the grid of smaller particles when looking for cross level interactions. If hGridMethod_ is BOTTOMUP, then smaller particles are inserted into the grid of larger particles when looking for cross-level interactions. The default for the hGridMethod_ is TOPDOWN.
Referenced by constructor(), getHGridMethod(), hGridInfo(), MercuryBase(), read(), and setHGridMethod().
totalCurrentMaxRelativeDisplacement_
Mdouble MercuryBase::totalCurrentMaxRelativeDisplacement_ private
After each time step, this Mdouble is increased by 2*currentMaxRelativeDisplacement_.
Referenced by constructor(), getHGridTotalCurrentMaxRelativeDisplacement(), hGridActionsAfterIntegration(), hGridActionsBeforeTimeStep(), hGridInfo(), MercuryBase(), and read().
updateEachTimeStep_
bool MercuryBase::updateEachTimeStep_ private
Boolean which indicates whether or not the cell in which a particle is must be updated every time step.
Referenced by constructor(), getHGridUpdateEachTimeStep(), hGridInfo(), MercuryBase(), read(), and setHGridUpdateEachTimeStep().
The documentation for this class was generated from the following files:
MercuryBase.h
MercuryBase.cc