MercuryDPM: Eigen::AutoDiffScalar< DerivativeType > Class Template Reference
Eigen::AutoDiffScalar< DerivativeType > Class Template Reference
A scalar type replacement with automatic differentiation capability.
#include <AutoDiffScalar.h>
Public Types
typedef internal::auto_diff_special_op< DerivativeType, !internal::is_same< typename internal::traits< internal::remove_all_t< DerivativeType > >::Scalar, typename NumTraits< typename internal::traits< internal::remove_all_t< DerivativeType > >::Scalar >::Real >::value > Base
typedef internal::remove_all_t< DerivativeType > DerType
typedef internal::traits< DerType >::Scalar Scalar
typedef NumTraits< Scalar >::Real Real
Public Member Functions
AutoDiffScalar ()
AutoDiffScalar (const Scalar &value, int nbDer, int derNumber)
AutoDiffScalar (const Real &value)
AutoDiffScalar (const Scalar &value, const DerType &der)
template<typename OtherDerType >
AutoDiffScalar (const AutoDiffScalar< OtherDerType > &other, std::enable_if_t< internal::is_same< Scalar, typename internal::traits< internal::remove_all_t< OtherDerType >>::Scalar >::value &&internal::is_convertible< OtherDerType, DerType >::value, void * >=0)
AutoDiffScalar (const AutoDiffScalar &other)
template<typename OtherDerType >
AutoDiffScalar & operator= (const AutoDiffScalar< OtherDerType > &other)
AutoDiffScalar & operator= (const AutoDiffScalar &other)
AutoDiffScalar & operator= (const Scalar &other)
const Scalar & value () const
Scalar & value ()
const DerType & derivatives () const
DerType & derivatives ()
bool operator< (const Scalar &other) const
bool operator<= (const Scalar &other) const
bool operator> (const Scalar &other) const
bool operator>= (const Scalar &other) const
bool operator== (const Scalar &other) const
bool operator!= (const Scalar &other) const
template<typename OtherDerType >
bool operator< (const AutoDiffScalar< OtherDerType > &b) const
template<typename OtherDerType >
bool operator<= (const AutoDiffScalar< OtherDerType > &b) const
template<typename OtherDerType >
bool operator> (const AutoDiffScalar< OtherDerType > &b) const
template<typename OtherDerType >
bool operator>= (const AutoDiffScalar< OtherDerType > &b) const
template<typename OtherDerType >
bool operator== (const AutoDiffScalar< OtherDerType > &b) const
template<typename OtherDerType >
bool operator!= (const AutoDiffScalar< OtherDerType > &b) const
AutoDiffScalar< DerType & > operator+ (const Scalar &other) const
AutoDiffScalar & operator+= (const Scalar &other)
template<typename OtherDerType >
auto operator+ (const AutoDiffScalar< OtherDerType > &other) const
template<typename OtherDerType >
AutoDiffScalar & operator+= (const AutoDiffScalar< OtherDerType > &other)
AutoDiffScalar< DerType & > operator- (const Scalar &b) const
AutoDiffScalar & operator-= (const Scalar &other)
template<typename OtherDerType >
auto operator- (const AutoDiffScalar< OtherDerType > &other) const
template<typename OtherDerType >
AutoDiffScalar & operator-= (const AutoDiffScalar< OtherDerType > &other)
AutoDiffScalar< CwiseUnaryOp< internal::scalar_opposite_op< Scalar >, const DerType > > operator- () const
auto operator* (const Scalar &other) const
auto operator/ (const Scalar &other) const
template<typename OtherDerType >
auto operator/ (const AutoDiffScalar< OtherDerType > &other) const
template<typename OtherDerType >
auto operator* (const AutoDiffScalar< OtherDerType > &other) const
AutoDiffScalar & operator*= (const Scalar &other)
template<typename OtherDerType >
AutoDiffScalar & operator*= (const AutoDiffScalar< OtherDerType > &other)
AutoDiffScalar & operator/= (const Scalar &other)
template<typename OtherDerType >
AutoDiffScalar & operator/= (const AutoDiffScalar< OtherDerType > &other)
Protected Attributes
Scalar m_value
DerType m_derivatives
Friends
std::ostream & operator<< (std::ostream &s, const AutoDiffScalar &a)
bool operator< (const Scalar &a, const AutoDiffScalar &b)
bool operator<= (const Scalar &a, const AutoDiffScalar &b)
bool operator> (const Scalar &a, const AutoDiffScalar &b)
bool operator>= (const Scalar &a, const AutoDiffScalar &b)
bool operator== (const Scalar &a, const AutoDiffScalar &b)
bool operator!= (const Scalar &a, const AutoDiffScalar &b)
AutoDiffScalar< DerType & > operator+ (const Scalar &a, const AutoDiffScalar &b)
AutoDiffScalar< CwiseUnaryOp< internal::scalar_opposite_op< Scalar >, const DerType > > operator- (const Scalar &a, const AutoDiffScalar &b)
auto operator* (const Scalar &other, const AutoDiffScalar &a)
auto operator/ (const Scalar &other, const AutoDiffScalar &a)
Detailed Description
template<typename DerivativeType>
class Eigen::AutoDiffScalar< DerivativeType >
A scalar type replacement with automatic differentiation capability.
Parameters
DerivativeType the vector type used to store/represent the derivatives. The base scalar type as well as the number of derivatives to compute are determined from this type. Typical choices include, e.g., Vector4f for 4 derivatives, or VectorXf if the number of derivatives is not known at compile time, and/or, the number of derivatives is large. Note that DerivativeType can also be a reference (e.g., VectorXf&) to wrap a existing vector into an AutoDiffScalar. Finally, DerivativeType can also be any Eigen compatible expression.
This class represents a scalar value while tracking its respective derivatives using Eigen's expression template mechanism.
It supports the following list of global math function:
std::abs, std::sqrt, std::pow, std::exp, std::log, std::sin, std::cos,
internal::abs, internal::sqrt, numext::pow, internal::exp, internal::log, internal::sin, internal::cos,
internal::conj, internal::real, internal::imag, numext::abs2.
AutoDiffScalar can be used as the scalar type of an Eigen::Matrix object. However, in that case, the expression template mechanism only occurs at the top Matrix level, while derivatives are computed right away.
Member Typedef Documentation
Base
template<typename DerivativeType > typedef internal::auto_diff_special_op< DerivativeType, !internal::is_same< typename internal::traits<internal::remove_all_t<DerivativeType> >::Scalar, typename NumTraits<typename internal::traits<internal::remove_all_t<DerivativeType> >::Scalar>::Real>::value> Eigen::AutoDiffScalar< DerivativeType >::Base
DerType
template<typename DerivativeType > typedef internal::remove_all_t<DerivativeType> Eigen::AutoDiffScalar< DerivativeType >::DerType
Real
template<typename DerivativeType > typedef NumTraits<Scalar>::Real Eigen::AutoDiffScalar< DerivativeType >::Real
Scalar
template<typename DerivativeType > typedef internal::traits<DerType>::Scalar Eigen::AutoDiffScalar< DerivativeType >::Scalar
Constructor & Destructor Documentation
AutoDiffScalar() [1/6]
template<typename DerivativeType > Eigen::AutoDiffScalar< DerivativeType >::AutoDiffScalar () inline
Default constructor without any initialization.
 {}
AutoDiffScalar() [2/6]
template<typename DerivativeType > Eigen::AutoDiffScalar< DerivativeType >::AutoDiffScalar (const Scalar & value, int nbDer, int derNumber) inline
Constructs an active scalar from its value, and initializes the nbDer derivatives such that it corresponds to the derNumber -th variable
                                                                 : m_value(value), m_derivatives(DerType::Zero(nbDer)) {
     m_derivatives.coeffRef(derNumber) = Scalar(1);
   }
References Eigen::AutoDiffScalar< DerivativeType >::m_derivatives.
AutoDiffScalar() [3/6]
template<typename DerivativeType > Eigen::AutoDiffScalar< DerivativeType >::AutoDiffScalar (const Real & value) inline
Conversion from a scalar constant to an active scalar. The derivatives are set to zero.
                                       : m_value(value) {
     if (m_derivatives.size() > 0) m_derivatives.setZero();
   }
References Eigen::AutoDiffScalar< DerivativeType >::m_derivatives.
AutoDiffScalar() [4/6]
template<typename DerivativeType > Eigen::AutoDiffScalar< DerivativeType >::AutoDiffScalar (const Scalar & value, const DerType & der) inline
Constructs an active scalar from its value and derivatives der
 : m_value(value), m_derivatives(der) {}
AutoDiffScalar() [5/6]
template<typename DerivativeType > template<typename OtherDerType > Eigen::AutoDiffScalar< DerivativeType >::AutoDiffScalar (const AutoDiffScalar< OtherDerType > & other, std::enable_if_t< internal::is_same< Scalar, typename internal::traits< internal::remove_all_t< OtherDerType >>::Scalar >::value &&internal::is_convertible< OtherDerType, DerType >::value, void * > = 0) inline
       : m_value(other.value()), m_derivatives(other.derivatives()) {
   }
AutoDiffScalar() [6/6]
template<typename DerivativeType > Eigen::AutoDiffScalar< DerivativeType >::AutoDiffScalar (const AutoDiffScalar< DerivativeType > & other) inline
 : m_value(other.value()), m_derivatives(other.derivatives()) {}
Member Function Documentation
derivatives() [1/2]
template<typename DerivativeType > DerType& Eigen::AutoDiffScalar< DerivativeType >::derivatives () inline
 { return m_derivatives; }
References Eigen::AutoDiffScalar< DerivativeType >::m_derivatives.
derivatives() [2/2]
template<typename DerivativeType > const DerType& Eigen::AutoDiffScalar< DerivativeType >::derivatives () const inline
 { return m_derivatives; }
References Eigen::AutoDiffScalar< DerivativeType >::m_derivatives.
Referenced by Eigen::AutoDiffScalar< DerivativeType >::operator*(), Eigen::AutoDiffScalar< DerivativeType >::operator+(), Eigen::AutoDiffScalar< DerivativeType >::operator-(), Eigen::AutoDiffScalar< DerivativeType >::operator/(), and Eigen::AutoDiffScalar< DerivativeType >::operator=().
operator!=() [1/2]
template<typename DerivativeType > template<typename OtherDerType > bool Eigen::AutoDiffScalar< DerivativeType >::operator!= (const AutoDiffScalar< OtherDerType > & b) const inline
{
     return m_value != b.value();
   }
References b, and Eigen::AutoDiffScalar< DerivativeType >::m_value.
operator!=() [2/2]
template<typename DerivativeType > bool Eigen::AutoDiffScalar< DerivativeType >::operator!= (const Scalar & other) const inline
 { return m_value != other; }
References Eigen::AutoDiffScalar< DerivativeType >::m_value.
operator*() [1/2]
template<typename DerivativeType > template<typename OtherDerType > auto Eigen::AutoDiffScalar< DerivativeType >::operator* (const AutoDiffScalar< OtherDerType > & other) const inline
{
     return MakeAutoDiffScalar(m_value * other.value(),
                               internal::MakeCoherentCwiseBinaryOp<internal::scalar_sum_op<Scalar>>(
                                   m_derivatives * other.value(), other.derivatives() * m_value));
   }
References Eigen::AutoDiffScalar< DerivativeType >::derivatives(), Eigen::AutoDiffScalar< DerivativeType >::m_derivatives, Eigen::AutoDiffScalar< DerivativeType >::m_value, Eigen::MakeAutoDiffScalar(), Eigen::internal::MakeCoherentCwiseBinaryOp(), and Eigen::AutoDiffScalar< DerivativeType >::value().
operator*() [2/2]
template<typename DerivativeType > auto Eigen::AutoDiffScalar< DerivativeType >::operator* (const Scalar & other) const inline
{
     return MakeAutoDiffScalar(m_value * other, m_derivatives * other);
   }
References Eigen::AutoDiffScalar< DerivativeType >::m_derivatives, Eigen::AutoDiffScalar< DerivativeType >::m_value, and Eigen::MakeAutoDiffScalar().
operator*=() [1/2]
template<typename DerivativeType > template<typename OtherDerType > AutoDiffScalar& Eigen::AutoDiffScalar< DerivativeType >::operator*= (const AutoDiffScalar< OtherDerType > & other) inline
{
     *this = *this * other;
     return *this;
   }
operator*=() [2/2]
template<typename DerivativeType > AutoDiffScalar& Eigen::AutoDiffScalar< DerivativeType >::operator*= (const Scalar & other) inline
{
     *this = *this * other;
     return *this;
   }
operator+() [1/2]
template<typename DerivativeType > template<typename OtherDerType > auto Eigen::AutoDiffScalar< DerivativeType >::operator+ (const AutoDiffScalar< OtherDerType > & other) const inline
{
     return MakeAutoDiffScalar(
         m_value + other.value(),
         internal::MakeCoherentCwiseBinaryOp<internal::scalar_sum_op<Scalar>>(m_derivatives, other.derivatives()));
   }
References Eigen::AutoDiffScalar< DerivativeType >::derivatives(), Eigen::AutoDiffScalar< DerivativeType >::m_derivatives, Eigen::AutoDiffScalar< DerivativeType >::m_value, Eigen::MakeAutoDiffScalar(), Eigen::internal::MakeCoherentCwiseBinaryOp(), and Eigen::AutoDiffScalar< DerivativeType >::value().
operator+() [2/2]
template<typename DerivativeType > AutoDiffScalar<DerType&> Eigen::AutoDiffScalar< DerivativeType >::operator+ (const Scalar & other) const inline
{
     return AutoDiffScalar<DerType&>(m_value + other, m_derivatives);
   }
References Eigen::AutoDiffScalar< DerivativeType >::m_derivatives, and Eigen::AutoDiffScalar< DerivativeType >::m_value.
operator+=() [1/2]
template<typename DerivativeType > template<typename OtherDerType > AutoDiffScalar& Eigen::AutoDiffScalar< DerivativeType >::operator+= (const AutoDiffScalar< OtherDerType > & other) inline
{
     (*this) = (*this) + other;
     return *this;
   }
operator+=() [2/2]
template<typename DerivativeType > AutoDiffScalar& Eigen::AutoDiffScalar< DerivativeType >::operator+= (const Scalar & other) inline
{
     value() += other;
     return *this;
   }
References Eigen::AutoDiffScalar< DerivativeType >::value().
operator-() [1/3]
template<typename DerivativeType > AutoDiffScalar<CwiseUnaryOp<internal::scalar_opposite_op<Scalar>, const DerType> > Eigen::AutoDiffScalar< DerivativeType >::operator- (void) const inline
{
     return AutoDiffScalar<CwiseUnaryOp<internal::scalar_opposite_op<Scalar>, const DerType>>(-m_value, -m_derivatives);
   }
References Eigen::AutoDiffScalar< DerivativeType >::m_derivatives, and Eigen::AutoDiffScalar< DerivativeType >::m_value.
operator-() [2/3]
template<typename DerivativeType > template<typename OtherDerType > auto Eigen::AutoDiffScalar< DerivativeType >::operator- (const AutoDiffScalar< OtherDerType > & other) const inline
{
     return MakeAutoDiffScalar(m_value - other.value(),
                               internal::MakeCoherentCwiseBinaryOp<internal::scalar_difference_op<Scalar>>(
                                   m_derivatives, other.derivatives()));
   }
References Eigen::AutoDiffScalar< DerivativeType >::derivatives(), Eigen::AutoDiffScalar< DerivativeType >::m_derivatives, Eigen::AutoDiffScalar< DerivativeType >::m_value, Eigen::MakeAutoDiffScalar(), Eigen::internal::MakeCoherentCwiseBinaryOp(), and Eigen::AutoDiffScalar< DerivativeType >::value().
operator-() [3/3]
template<typename DerivativeType > AutoDiffScalar<DerType&> Eigen::AutoDiffScalar< DerivativeType >::operator- (const Scalar & b) const inline
{
     return AutoDiffScalar<DerType&>(m_value - b, m_derivatives);
   }
References b, Eigen::AutoDiffScalar< DerivativeType >::m_derivatives, and Eigen::AutoDiffScalar< DerivativeType >::m_value.
operator-=() [1/2]
template<typename DerivativeType > template<typename OtherDerType > AutoDiffScalar& Eigen::AutoDiffScalar< DerivativeType >::operator-= (const AutoDiffScalar< OtherDerType > & other) inline
{
     *this = *this - other;
     return *this;
   }
operator-=() [2/2]
template<typename DerivativeType > AutoDiffScalar& Eigen::AutoDiffScalar< DerivativeType >::operator-= (const Scalar & other) inline
{
     value() -= other;
     return *this;
   }
References Eigen::AutoDiffScalar< DerivativeType >::value().
operator/() [1/2]
template<typename DerivativeType > template<typename OtherDerType > auto Eigen::AutoDiffScalar< DerivativeType >::operator/ (const AutoDiffScalar< OtherDerType > & other) const inline
{
     return MakeAutoDiffScalar(m_value / other.value(),
                               internal::MakeCoherentCwiseBinaryOp<internal::scalar_difference_op<Scalar>>(
                                   m_derivatives * other.value(), (other.derivatives() * m_value)) *
                                   (Scalar(1) / (other.value() * other.value())));
   }
References Eigen::AutoDiffScalar< DerivativeType >::derivatives(), Eigen::AutoDiffScalar< DerivativeType >::m_derivatives, Eigen::AutoDiffScalar< DerivativeType >::m_value, Eigen::MakeAutoDiffScalar(), Eigen::internal::MakeCoherentCwiseBinaryOp(), and Eigen::AutoDiffScalar< DerivativeType >::value().
operator/() [2/2]
template<typename DerivativeType > auto Eigen::AutoDiffScalar< DerivativeType >::operator/ (const Scalar & other) const inline
{
     return MakeAutoDiffScalar(m_value / other, (m_derivatives * (Scalar(1) / other)));
   }
References Eigen::AutoDiffScalar< DerivativeType >::m_derivatives, Eigen::AutoDiffScalar< DerivativeType >::m_value, and Eigen::MakeAutoDiffScalar().
operator/=() [1/2]
template<typename DerivativeType > template<typename OtherDerType > AutoDiffScalar& Eigen::AutoDiffScalar< DerivativeType >::operator/= (const AutoDiffScalar< OtherDerType > & other) inline
{
     *this = *this / other;
     return *this;
   }
operator/=() [2/2]
template<typename DerivativeType > AutoDiffScalar& Eigen::AutoDiffScalar< DerivativeType >::operator/= (const Scalar & other) inline
{
     *this = *this / other;
     return *this;
   }
operator<() [1/2]
template<typename DerivativeType > template<typename OtherDerType > bool Eigen::AutoDiffScalar< DerivativeType >::operator< (const AutoDiffScalar< OtherDerType > & b) const inline
{
     return m_value < b.value();
   }
References b, and Eigen::AutoDiffScalar< DerivativeType >::m_value.
operator<() [2/2]
template<typename DerivativeType > bool Eigen::AutoDiffScalar< DerivativeType >::operator< (const Scalar & other) const inline
 { return m_value < other; }
References Eigen::AutoDiffScalar< DerivativeType >::m_value.
operator<=() [1/2]
template<typename DerivativeType > template<typename OtherDerType > bool Eigen::AutoDiffScalar< DerivativeType >::operator<= (const AutoDiffScalar< OtherDerType > & b) const inline
{
     return m_value <= b.value();
   }
References b, and Eigen::AutoDiffScalar< DerivativeType >::m_value.
operator<=() [2/2]
template<typename DerivativeType > bool Eigen::AutoDiffScalar< DerivativeType >::operator<= (const Scalar & other) const inline
 { return m_value <= other; }
References Eigen::AutoDiffScalar< DerivativeType >::m_value.
operator=() [1/3]
template<typename DerivativeType > AutoDiffScalar& Eigen::AutoDiffScalar< DerivativeType >::operator= (const AutoDiffScalar< DerivativeType > & other) inline
{
     m_value = other.value();
     m_derivatives = other.derivatives();
     return *this;
   }
References Eigen::AutoDiffScalar< DerivativeType >::derivatives(), Eigen::AutoDiffScalar< DerivativeType >::m_derivatives, Eigen::AutoDiffScalar< DerivativeType >::m_value, and Eigen::AutoDiffScalar< DerivativeType >::value().
operator=() [2/3]
template<typename DerivativeType > template<typename OtherDerType > AutoDiffScalar& Eigen::AutoDiffScalar< DerivativeType >::operator= (const AutoDiffScalar< OtherDerType > & other) inline
{
     m_value = other.value();
     m_derivatives = other.derivatives();
     return *this;
   }
References Eigen::AutoDiffScalar< DerivativeType >::derivatives(), Eigen::AutoDiffScalar< DerivativeType >::m_derivatives, Eigen::AutoDiffScalar< DerivativeType >::m_value, and Eigen::AutoDiffScalar< DerivativeType >::value().
operator=() [3/3]
template<typename DerivativeType > AutoDiffScalar& Eigen::AutoDiffScalar< DerivativeType >::operator= (const Scalar & other) inline
{
     m_value = other;
     if (m_derivatives.size() > 0) m_derivatives.setZero();
     return *this;
   }
References Eigen::AutoDiffScalar< DerivativeType >::m_derivatives, and Eigen::AutoDiffScalar< DerivativeType >::m_value.
operator==() [1/2]
template<typename DerivativeType > template<typename OtherDerType > bool Eigen::AutoDiffScalar< DerivativeType >::operator== (const AutoDiffScalar< OtherDerType > & b) const inline
{
     return m_value == b.value();
   }
References b, and Eigen::AutoDiffScalar< DerivativeType >::m_value.
operator==() [2/2]
template<typename DerivativeType > bool Eigen::AutoDiffScalar< DerivativeType >::operator== (const Scalar & other) const inline
 { return m_value == other; }
References Eigen::AutoDiffScalar< DerivativeType >::m_value.
operator>() [1/2]
template<typename DerivativeType > template<typename OtherDerType > bool Eigen::AutoDiffScalar< DerivativeType >::operator> (const AutoDiffScalar< OtherDerType > & b) const inline
{
     return m_value > b.value();
   }
References b, and Eigen::AutoDiffScalar< DerivativeType >::m_value.
operator>() [2/2]
template<typename DerivativeType > bool Eigen::AutoDiffScalar< DerivativeType >::operator> (const Scalar & other) const inline
 { return m_value > other; }
References Eigen::AutoDiffScalar< DerivativeType >::m_value.
operator>=() [1/2]
template<typename DerivativeType > template<typename OtherDerType > bool Eigen::AutoDiffScalar< DerivativeType >::operator>= (const AutoDiffScalar< OtherDerType > & b) const inline
{
     return m_value >= b.value();
   }
References b, and Eigen::AutoDiffScalar< DerivativeType >::m_value.
operator>=() [2/2]
template<typename DerivativeType > bool Eigen::AutoDiffScalar< DerivativeType >::operator>= (const Scalar & other) const inline
 { return m_value >= other; }
References Eigen::AutoDiffScalar< DerivativeType >::m_value.
value() [1/2]
template<typename DerivativeType > Scalar& Eigen::AutoDiffScalar< DerivativeType >::value () inline
 { return m_value; }
References Eigen::AutoDiffScalar< DerivativeType >::m_value.
value() [2/2]
template<typename DerivativeType > const Scalar& Eigen::AutoDiffScalar< DerivativeType >::value () const inline
 { return m_value; }
References Eigen::AutoDiffScalar< DerivativeType >::m_value.
Referenced by Eigen::AutoDiffScalar< DerivativeType >::operator*(), Eigen::AutoDiffScalar< DerivativeType >::operator+(), Eigen::AutoDiffScalar< DerivativeType >::operator+=(), Eigen::AutoDiffScalar< DerivativeType >::operator-(), Eigen::AutoDiffScalar< DerivativeType >::operator-=(), Eigen::AutoDiffScalar< DerivativeType >::operator/(), and Eigen::AutoDiffScalar< DerivativeType >::operator=().
Friends And Related Function Documentation
operator!=
template<typename DerivativeType > bool operator!= (const Scalar & a, const AutoDiffScalar< DerivativeType > & b) friend
 { return a != b.value(); }
operator*
template<typename DerivativeType > auto operator* (const Scalar & other, const AutoDiffScalar< DerivativeType > & a) friend
{
     return MakeAutoDiffScalar(a.value() * other, a.derivatives() * other);
   }
operator+
template<typename DerivativeType > AutoDiffScalar<DerType&> operator+ (const Scalar & a, const AutoDiffScalar< DerivativeType > & b) friend
{
     return AutoDiffScalar<DerType&>(a + b.value(), b.derivatives());
   }
operator-
template<typename DerivativeType > AutoDiffScalar<CwiseUnaryOp<internal::scalar_opposite_op<Scalar>, const DerType> > operator- (const Scalar & a, const AutoDiffScalar< DerivativeType > & b) friend
{
     return AutoDiffScalar<CwiseUnaryOp<internal::scalar_opposite_op<Scalar>, const DerType>>(a - b.value(),
                                                                                              -b.derivatives());
   }
operator/
template<typename DerivativeType > auto operator/ (const Scalar & other, const AutoDiffScalar< DerivativeType > & a) friend
{
     return MakeAutoDiffScalar(other / a.value(), a.derivatives() * (Scalar(-other) / (a.value() * a.value())));
   }
operator<
template<typename DerivativeType > bool operator< (const Scalar & a, const AutoDiffScalar< DerivativeType > & b) friend
 { return a < b.value(); }
operator<<
template<typename DerivativeType > std::ostream& operator<< (std::ostream & s, const AutoDiffScalar< DerivativeType > & a) friend
 { return s << a.value(); }
operator<=
template<typename DerivativeType > bool operator<= (const Scalar & a, const AutoDiffScalar< DerivativeType > & b) friend
 { return a <= b.value(); }
operator==
template<typename DerivativeType > bool operator== (const Scalar & a, const AutoDiffScalar< DerivativeType > & b) friend
 { return a == b.value(); }
operator>
template<typename DerivativeType > bool operator> (const Scalar & a, const AutoDiffScalar< DerivativeType > & b) friend
 { return a > b.value(); }
operator>=
template<typename DerivativeType > bool operator>= (const Scalar & a, const AutoDiffScalar< DerivativeType > & b) friend
 { return a >= b.value(); }
Member Data Documentation
m_derivatives
template<typename DerivativeType > DerType Eigen::AutoDiffScalar< DerivativeType >::m_derivatives protected
Referenced by Eigen::AutoDiffScalar< DerivativeType >::AutoDiffScalar(), Eigen::AutoDiffScalar< DerivativeType >::derivatives(), Eigen::AutoDiffScalar< DerivativeType >::operator*(), Eigen::AutoDiffScalar< DerivativeType >::operator+(), Eigen::AutoDiffScalar< DerivativeType >::operator-(), Eigen::AutoDiffScalar< DerivativeType >::operator/(), and Eigen::AutoDiffScalar< DerivativeType >::operator=().
m_value
template<typename DerivativeType > Scalar Eigen::AutoDiffScalar< DerivativeType >::m_value protected
Referenced by Eigen::AutoDiffScalar< DerivativeType >::operator!=(), Eigen::AutoDiffScalar< DerivativeType >::operator*(), Eigen::AutoDiffScalar< DerivativeType >::operator+(), Eigen::AutoDiffScalar< DerivativeType >::operator-(), Eigen::AutoDiffScalar< DerivativeType >::operator/(), Eigen::AutoDiffScalar< DerivativeType >::operator<(), Eigen::AutoDiffScalar< DerivativeType >::operator<=(), Eigen::AutoDiffScalar< DerivativeType >::operator=(), Eigen::AutoDiffScalar< DerivativeType >::operator==(), Eigen::AutoDiffScalar< DerivativeType >::operator>(), Eigen::AutoDiffScalar< DerivativeType >::operator>=(), and Eigen::AutoDiffScalar< DerivativeType >::value().
The documentation for this class was generated from the following file:
AutoDiffScalar.h