MercuryDPM: CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT > Class Template Reference
CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT > Class Template Reference
Coated sphere FSI.
Public Member Functions
CoatedSphereProblem ()
Constructor:
void actions_before_newton_solve ()
Update function (empty)
void actions_after_newton_solve ()
Update function (empty)
void actions_before_newton_convergence_check ()
Recompute gamma integral before checking Newton residuals.
void doc_solution (DocInfo &doc_info)
Doc the solution.
CoatedSphereProblem ()
Constructor:
void actions_before_newton_solve ()
Update function (empty)
void actions_after_newton_solve ()
Update function (empty)
void actions_before_adapt ()
Actions before adapt: Wipe the face meshes.
void actions_after_adapt ()
Actions after adapt: Rebuild the face meshes.
void actions_before_newton_convergence_check ()
Recompute gamma integral before checking Newton residuals.
void doc_solution (DocInfo &doc_info)
Doc the solution.
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Private Member Functions
void create_fsi_traction_elements ()
Create FSI traction elements.
void create_helmholtz_fsi_flux_elements ()
Create Helmholtz FSI flux elements.
void setup_interaction ()
Setup interaction.
void create_helmholtz_DtN_elements ()
Create DtN elements on outer boundary.
void create_fsi_traction_elements ()
Create FSI traction elements.
void create_helmholtz_fsi_flux_elements ()
Create Helmholtz FSI flux elements.
void setup_interaction ()
Setup interaction.
void create_helmholtz_DtN_elements ()
Create DtN elements on outer boundary.
void create_solid_traction_elements ()
Create solid traction elements.
void delete_face_elements (Mesh *const &boundary_mesh_pt)
Delete (face) elements in specified mesh.
void complete_problem_setup ()
Private Attributes
TwoDAnnularMesh< ELASTICITY_ELEMENT > * Solid_mesh_pt
Pointer to solid mesh.
Mesh * FSI_traction_mesh_pt
Pointer to mesh of FSI traction elements.
TwoDAnnularMesh< HELMHOLTZ_ELEMENT > * Helmholtz_mesh_pt
Pointer to Helmholtz mesh.
Mesh * Helmholtz_fsi_flux_mesh_pt
Pointer to mesh of Helmholtz FSI flux elements.
FourierDecomposedHelmholtzDtNMesh< HELMHOLTZ_ELEMENT > * Helmholtz_DtN_mesh_pt
Pointer to mesh containing the DtN elements.
ofstream Trace_file
Trace file.
unsigned Upper_symmetry_boundary_id
Boundary ID of upper symmetry boundary.
unsigned Lower_symmetry_boundary_id
Boundary ID of lower symmetry boundary.
unsigned Upper_inner_boundary_id
Boundary ID of upper inner boundary.
unsigned Lower_inner_boundary_id
Boundary ID of lower inner boundary.
unsigned Outer_boundary_id
Boundary ID of outer boundary.
unsigned Rib_divider_boundary_id
Boundary ID of rib divider.
unsigned HH_outer_boundary_id
Boundary ID of outer boundary in Helmholtz mesh.
unsigned HH_inner_boundary_id
Boundary ID of inner boundary in Helmholtz mesh.
unsigned HH_upper_symmetry_boundary_id
Boundary ID of upper boundary in Helmholtz mesh.
unsigned HH_lower_symmetry_boundary_id
Boundary ID of lower boundary in Helmholtz mesh.
TriangleMesh< ELASTICITY_ELEMENT > * Solid_mesh_pt
Pointer to solid mesh.
Mesh * Solid_traction_mesh_pt
Pointer to mesh of solid traction elements.
TriangleMesh< HELMHOLTZ_ELEMENT > * Helmholtz_mesh_pt
Pointer to Helmholtz mesh.
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_before_implicit_timestep ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual void set_initial_condition ()
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
class CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >
Coated sphere FSI.
Constructor & Destructor Documentation
CoatedSphereProblem() [1/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::CoatedSphereProblem
Constructor:
 {
  // Parameters for meshes
  bool periodic=false;
  double azimuthal_fraction_of_coating=0.5;
  double phi=0.5*MathematicalConstants::Pi;
  // Solid mesh
  //-----------
  // Number of elements in azimuthal direction
  unsigned ntheta_solid=10*Global_Parameters::El_multiplier;
  // Number of elements in radial direction
  unsigned nr_solid=3*Global_Parameters::El_multiplier;
  // Innermost radius for solid mesh
  double a=1.0-Global_Parameters::H_coating;
  // Build solid mesh
  Solid_mesh_pt = new
   TwoDAnnularMesh<ELASTICITY_ELEMENT>(periodic,azimuthal_fraction_of_coating,
                                       ntheta_solid,nr_solid,a,
                                       Global_Parameters::H_coating,phi);
  // Helmholtz mesh
  //---------------
  // Number of elements in azimuthal direction in Helmholtz mesh
  unsigned ntheta_helmholtz=11*Global_Parameters::El_multiplier;
  // Number of elements in radial direction in Helmholtz mesh
  unsigned nr_helmholtz=3*Global_Parameters::El_multiplier;
  // Innermost radius of Helmholtz mesh
  a=1.0;
  // Thickness of Helmholtz mesh
  double h_thick_helmholtz=Global_Parameters::Outer_radius-a;
  // Build mesh
  Helmholtz_mesh_pt = new TwoDAnnularMesh<HELMHOLTZ_ELEMENT>
   (periodic,azimuthal_fraction_of_coating,
    ntheta_helmholtz,nr_helmholtz,a,h_thick_helmholtz,phi);
  // Create mesh for DtN elements on outer boundary
  unsigned nfourier=20;
  Helmholtz_DtN_mesh_pt=
   new FourierDecomposedHelmholtzDtNMesh<HELMHOLTZ_ELEMENT>(
    Global_Parameters::Outer_radius,nfourier);
  // Complete the solid problem setup to make the elements fully functional
  unsigned nel=Solid_mesh_pt->nelement();
  for (unsigned e=0;e<nel;e++)
   {
    // Cast to a bulk element
    ELASTICITY_ELEMENT* el_pt=dynamic_cast<ELASTICITY_ELEMENT*>(
     Solid_mesh_pt->element_pt(e));
    // Set the pointer to Fourier wavenumber
    el_pt->fourier_wavenumber_pt() = &Global_Parameters::Fourier_wavenumber;
    // Set the pointer to Poisson's ratio
    el_pt->nu_pt() = &Global_Parameters::Nu;
    // Set the pointer to square of the angular frequency
    el_pt->omega_sq_pt() = &Global_Parameters::Omega_sq;
   }
  // Complete the build of all Helmholtz elements so they are fully functional
  unsigned n_element = Helmholtz_mesh_pt->nelement();
  for(unsigned i=0;i<n_element;i++)
   {
    // Upcast from GeneralsedElement to the present element
    HELMHOLTZ_ELEMENT *el_pt = dynamic_cast<HELMHOLTZ_ELEMENT*>(
     Helmholtz_mesh_pt->element_pt(i));
    //Set the k_squared pointer
    el_pt->k_squared_pt()=&Global_Parameters::K_squared;
    // Set pointer to Fourier wave number
    el_pt->fourier_wavenumber_pt()=&Global_Parameters::Fourier_wavenumber;
   }
  // Output meshes and their boundaries so far so we can double
  // check the boundary enumeration
  Solid_mesh_pt->output("solid_mesh.dat");
  Helmholtz_mesh_pt->output("helmholtz_mesh.dat");
  Solid_mesh_pt->output_boundaries("solid_mesh_boundary.dat");
  Helmholtz_mesh_pt->output_boundaries("helmholtz_mesh_boundary.dat");
  // Create FaceElement meshes for boundary conditions
  //--------------------------------------------------
  // Construct the fsi traction element mesh
  FSI_traction_mesh_pt=new Mesh;
  create_fsi_traction_elements();
  // Construct the Helmholtz fsi flux element mesh
  Helmholtz_fsi_flux_mesh_pt=new Mesh;
  create_helmholtz_fsi_flux_elements();
  // Create DtN elements
  create_helmholtz_DtN_elements();
  // Combine sub meshes
  //-------------------
  add_sub_mesh(Solid_mesh_pt);
  add_sub_mesh(FSI_traction_mesh_pt);
  add_sub_mesh(Helmholtz_mesh_pt);
  add_sub_mesh(Helmholtz_fsi_flux_mesh_pt);
  add_sub_mesh(Helmholtz_DtN_mesh_pt);
  // Build the Problem's global mesh from its various sub-meshes
  build_global_mesh();
  // Solid boundary conditions:
  //---------------------------
  // Pin the solid inner boundary (boundary 0) in all directions
  unsigned b=0;
  unsigned n_node = Solid_mesh_pt->nboundary_node(b);
  Vector<std::complex<double> > u(2);
  Vector<double> x(2);
  //Loop over the nodes to pin and assign boundary displacements on
  //solid boundary
  for(unsigned i=0;i<n_node;i++)
   {
    Node* nod_pt=Solid_mesh_pt->boundary_node_pt(b,i);
    nod_pt->pin(0);
    nod_pt->pin(1);
    nod_pt->pin(2);
    nod_pt->pin(3);
    nod_pt->pin(4);
    nod_pt->pin(5);
    // Assign prescribed displacements
    x[0]=nod_pt->x(0);
    x[1]=nod_pt->x(1);
    Global_Parameters::solid_boundary_displacement(x,u);
    // Real part of radial displacement
    nod_pt->set_value(0,u[0].real());
    // Real part of axial displacement
    nod_pt->set_value(1,u[1].real());
    // Real part of azimuthal displacement
    nod_pt->set_value(2,0.0);
    // Imag part of radial displacement
    nod_pt->set_value(3,u[0].imag());
    // Imag part of axial displacement
    nod_pt->set_value(4,u[1].imag());
    // Imag part of azimuthal displacement
    nod_pt->set_value(5,0.0);
   }
  // Vertical Symmetry boundary (r=0 and z<0)
  {
   unsigned ibound=1;
   {
    unsigned num_nod= Solid_mesh_pt->nboundary_node(ibound);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      // Get pointer to node
      Node* nod_pt=Solid_mesh_pt->boundary_node_pt(ibound,inod);
      // Pin radial displacement (u_0 (real) and u_3 (imag))
      nod_pt->pin(0);
      nod_pt->set_value(0,0.0);
      nod_pt->pin(3);
      nod_pt->set_value(3,0.0);
      // Pin azimuthal displacement (u_2 (real) and u_5 (imag))
      nod_pt->pin(2);
      nod_pt->set_value(2,0.0);
      nod_pt->pin(5);
      nod_pt->set_value(5,0.0);
     }
   }
  }
  // Vertical Symmetry boundary (r=0 and z>0)
  {
   unsigned ibound=3;
   {
    unsigned num_nod= Solid_mesh_pt->nboundary_node(ibound);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      // Get pointer to node
      Node* nod_pt=Solid_mesh_pt->boundary_node_pt(ibound,inod);
      // Pin radial displacement (u_0 (real) and u_3 (imag))
      nod_pt->pin(0);
      nod_pt->set_value(0,0.0);
      nod_pt->pin(3);
      nod_pt->set_value(3,0.0);
      // Pin azimuthal displacement (u_2 (real) and u_5 (imag))
      nod_pt->pin(2);
      nod_pt->set_value(2,0.0);
      nod_pt->pin(5);
      nod_pt->set_value(5,0.0);
     }
   }
  } // done sym bc
  // Setup fluid-structure interaction
  //----------------------------------
  setup_interaction();
  // Open trace file
  char filename[100];
  sprintf(filename,"%s/trace.dat",Global_Parameters::Directory.c_str());
  Trace_file.open(filename);
  // Setup equation numbering scheme
  cout <<"Number of equations: " << assign_eqn_numbers() << std::endl;
 }//end_of_constructor
References a, b, Global_Parameters::Directory, e(), Global_Parameters::El_multiplier, MergeRestartFiles::filename, Global_Parameters::Fourier_wavenumber, Global_Parameters::H_coating, i, imag(), Global_Parameters::K_squared, Global_Parameters::Nu, Global_Parameters::Omega_sq, Global_Parameters::Outer_radius, oomph::MathematicalConstants::Pi, oomph::Data::pin(), oomph::Data::set_value(), Global_Parameters::solid_boundary_displacement(), oomph::Problem_Parameter::Trace_file, plotDoE::x, and oomph::Node::x().
CoatedSphereProblem() [2/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::CoatedSphereProblem ()
Constructor:
Member Function Documentation
actions_after_adapt()
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > void CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::actions_after_adapt virtual
Actions after adapt: Rebuild the face meshes.
Actions after adapt: Rebuild the meshes of face elements.
Reimplemented from oomph::Problem.
 {
  // Complete problem setup
  complete_problem_setup();
  // Construct the solid traction elements
  create_solid_traction_elements();
  // Create fsi traction elements from all elements that are
  // adjacent to FSI boundaries and add them to surface meshes
  create_fsi_traction_elements();
  // Create Helmholtz fsi flux elements
  create_helmholtz_fsi_flux_elements();
  // Create DtN elements from all elements that are
  // adjacent to the outer boundary of Helmholtz mesh
  create_helmholtz_DtN_elements();
  // Setup interaction
  setup_interaction();
  // Rebuild the Problem's global mesh from its various sub-meshes
  rebuild_global_mesh();
 }// end of actions_after_adapt
actions_after_newton_solve() [1/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > void CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::actions_after_newton_solve () inline virtual
Update function (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [2/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > void CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::actions_after_newton_solve () inline virtual
Update function (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_adapt()
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > void CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::actions_before_adapt virtual
Actions before adapt: Wipe the face meshes.
Actions before adapt: Wipe the meshes face elements.
Reimplemented from oomph::Problem.
 {
  // Kill the solid traction elements and wipe surface mesh
  delete_face_elements(Solid_traction_mesh_pt);
  // Kill the fsi traction elements and wipe surface mesh
  delete_face_elements(FSI_traction_mesh_pt);
  // Kill Helmholtz FSI flux elements
  delete_face_elements(Helmholtz_fsi_flux_mesh_pt);
  // Kill Helmholtz BC elements
  delete_face_elements(Helmholtz_DtN_mesh_pt);
  // Rebuild the Problem's global mesh from its various sub-meshes
  rebuild_global_mesh();
 }// end of actions_before_adapt
actions_before_newton_convergence_check() [1/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > void CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::actions_before_newton_convergence_check () inline virtual
Recompute gamma integral before checking Newton residuals.
Reimplemented from oomph::Problem.
   {
    Helmholtz_DtN_mesh_pt->setup_gamma();
   }
actions_before_newton_convergence_check() [2/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > void CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::actions_before_newton_convergence_check () inline virtual
Recompute gamma integral before checking Newton residuals.
Reimplemented from oomph::Problem.
   {
    Helmholtz_DtN_mesh_pt->setup_gamma();
   }
actions_before_newton_solve() [1/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > void CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::actions_before_newton_solve () inline virtual
Update function (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [2/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > void CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::actions_before_newton_solve () inline virtual
Update function (empty)
Reimplemented from oomph::Problem.
 {}
complete_problem_setup()
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > void CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::complete_problem_setup private
Complete problem setup: Apply boundary conditions and set physical properties
 {
  // Solid boundary conditions:
  //---------------------------
  // Pin real and imag part of horizontal and azimuthal displacement components
  //---------------------------------------------------------------------------
  // on vertical boundaries
  //-----------------------
  {
   //Loop over the nodes to pin and assign boundary displacements on
   //solid boundary
   unsigned n_node = Solid_mesh_pt->nboundary_node(Upper_symmetry_boundary_id);
   for(unsigned i=0;i<n_node;i++)
    {
     Node* nod_pt=Solid_mesh_pt->boundary_node_pt(Upper_symmetry_boundary_id,i);
     // Real part of r-displacement
     nod_pt->pin(0);
     nod_pt->set_value(0,0.0);
     // Imag part of r-displacement
     nod_pt->pin(3);
     nod_pt->set_value(3,0.0);
     // Real part of phi-displacement
     nod_pt->pin(2);
     nod_pt->set_value(2,0.0);
     // Imag part of phi-displacement
     nod_pt->pin(5);
     nod_pt->set_value(5,0.0);
    }
  }
  {
   //Loop over the nodes to pin and assign boundary displacements on
   //solid boundary
   unsigned n_node = Solid_mesh_pt->nboundary_node(Lower_symmetry_boundary_id);
   for(unsigned i=0;i<n_node;i++)
    {
     Node* nod_pt=Solid_mesh_pt->boundary_node_pt(Lower_symmetry_boundary_id,i);
     // Real part of r-displacement
     nod_pt->pin(0);
     nod_pt->set_value(0,0.0);
     // Imag part of r-displacement
     nod_pt->pin(3);
     nod_pt->set_value(3,0.0);
     // Real part of phi-displacement
     nod_pt->pin(2);
     nod_pt->set_value(2,0.0);
     // Imag part of phi-displacement
     nod_pt->pin(5);
     nod_pt->set_value(5,0.0);
    }
  }
  //Assign the physical properties to the elements
  //----------------------------------------------
  unsigned nreg=Solid_mesh_pt->nregion();
  for (unsigned r=0;r<nreg;r++)
   {
    unsigned nel=Solid_mesh_pt->nregion_element(r);
    for (unsigned e=0;e<nel;e++)
     {
      //Cast to a solid element
      ELASTICITY_ELEMENT *el_pt =
       dynamic_cast<ELASTICITY_ELEMENT*>(Solid_mesh_pt->
                                         region_element_pt(r,e));
      // Set the pointer to Fourier wavenumber
      el_pt->fourier_wavenumber_pt() = &Global_Parameters::Fourier_wavenumber;
      // Set the pointer to Poisson's ratio
      el_pt->nu_pt() = &Global_Parameters::Nu;
      // Square of non-dim frequency
      el_pt->omega_sq_pt()= &Global_Parameters::Omega_sq[r];
      // Set the pointer to non-dim Young's modulus
      el_pt->youngs_modulus_pt() = &Global_Parameters::E[r];
     }
   }
  // Complete the build of all Helmholtz elements so they are fully functional
  unsigned n_element = Helmholtz_mesh_pt->nelement();
  for(unsigned i=0;i<n_element;i++)
   {
    // Upcast from GeneralsedElement to the present element
    HELMHOLTZ_ELEMENT *el_pt = dynamic_cast<HELMHOLTZ_ELEMENT*>(
     Helmholtz_mesh_pt->element_pt(i));
    //Set the k_squared pointer
    el_pt->k_squared_pt()=&Global_Parameters::K_squared;
    // Set pointer to Fourier wave number
    el_pt->fourier_wavenumber_pt()=&Global_Parameters::Fourier_wavenumber;
   }
 }
References e(), Global_Parameters::E, Global_Parameters::Fourier_wavenumber, i, Global_Parameters::K_squared, Global_Parameters::Nu, Global_Parameters::Omega_sq, oomph::Data::pin(), UniformPSDSelfTest::r, and oomph::Data::set_value().
create_fsi_traction_elements() [1/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > void CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_fsi_traction_elements private
Create FSI traction elements.
Create fsi traction elements.
 {
  // We're on boundary 2 of the solid mesh
  unsigned b=2;
  // How many bulk elements are adjacent to boundary b?
  unsigned n_element = Solid_mesh_pt->nboundary_element(b);
  // Loop over the bulk elements adjacent to boundary b
  for(unsigned e=0;e<n_element;e++)
   {
    // Get pointer to the bulk element that is adjacent to boundary b
    ELASTICITY_ELEMENT* bulk_elem_pt = dynamic_cast<ELASTICITY_ELEMENT*>(
     Solid_mesh_pt->boundary_element_pt(b,e));
    //Find the index of the face of element e along boundary b
    int face_index = Solid_mesh_pt->face_index_at_boundary(b,e);
    // Create element
    FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement
     <ELASTICITY_ELEMENT,HELMHOLTZ_ELEMENT>* el_pt=
     new FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement
     <ELASTICITY_ELEMENT,HELMHOLTZ_ELEMENT>(bulk_elem_pt,
                                            face_index);
    // Add to mesh
    FSI_traction_mesh_pt->add_element_pt(el_pt);
    // Associate element with bulk boundary (to allow it to access
    // the boundary coordinates in the bulk mesh)
    el_pt->set_boundary_number_in_bulk_mesh(b);
    // Set FSI parameter
    el_pt->q_pt()=&Global_Parameters::Q;
   }
 } // end_of_create_fsi_traction_elements
References b, e(), Global_Parameters::Q, and oomph::FaceElement::set_boundary_number_in_bulk_mesh().
create_fsi_traction_elements() [2/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > void CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_fsi_traction_elements () private
Create FSI traction elements.
create_helmholtz_DtN_elements() [1/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > void CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_DtN_elements private
Create DtN elements on outer boundary.
Create BC elements on outer boundary.
 {
  // Outer boundary is boundary 2:
  unsigned b=2;
  // Loop over the bulk elements adjacent to boundary b?
  unsigned n_element = Helmholtz_mesh_pt->nboundary_element(b);
  for(unsigned e=0;e<n_element;e++)
   {
    // Get pointer to the bulk element that is adjacent to boundary b
    HELMHOLTZ_ELEMENT* bulk_elem_pt = dynamic_cast<HELMHOLTZ_ELEMENT*>(
     Helmholtz_mesh_pt->boundary_element_pt(b,e));
    //Find the index of the face of element e along boundary b
    int face_index = Helmholtz_mesh_pt->face_index_at_boundary(b,e);
    // Build the corresponding DtN element
    FourierDecomposedHelmholtzDtNBoundaryElement<HELMHOLTZ_ELEMENT>*
     flux_element_pt = new
     FourierDecomposedHelmholtzDtNBoundaryElement<HELMHOLTZ_ELEMENT>
     (bulk_elem_pt,face_index);
    //Add the flux boundary element to the  helmholtz_DtN_mesh
    Helmholtz_DtN_mesh_pt->add_element_pt(flux_element_pt);
    // Set pointer to the mesh that contains all the boundary condition
    // elements on this boundary
    flux_element_pt->set_outer_boundary_mesh_pt(Helmholtz_DtN_mesh_pt);
   }
 } // end_of_create_outer_bc_elements
References b, e(), and oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::set_outer_boundary_mesh_pt().
create_helmholtz_DtN_elements() [2/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > void CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_DtN_elements () private
Create DtN elements on outer boundary.
create_helmholtz_fsi_flux_elements() [1/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > void CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_fsi_flux_elements private
Create Helmholtz FSI flux elements.
Create Helmholtz fsi flux elements.
 {
  // Attach to inner boundary of Helmholtz mesh (0)
  unsigned b=0;
  // How many bulk elements are adjacent to boundary b?
  unsigned n_element = Helmholtz_mesh_pt->nboundary_element(b);
  // Loop over the bulk elements adjacent to boundary b
  for(unsigned e=0;e<n_element;e++)
   {
    // Get pointer to the bulk element that is adjacent to boundary b
    HELMHOLTZ_ELEMENT* bulk_elem_pt = dynamic_cast<HELMHOLTZ_ELEMENT*>(
     Helmholtz_mesh_pt->boundary_element_pt(b,e));
    //Find the index of the face of element e along boundary b
    int face_index = Helmholtz_mesh_pt->face_index_at_boundary(b,e);
    // Create element
    FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement
     <HELMHOLTZ_ELEMENT,ELASTICITY_ELEMENT>* el_pt=
     new FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement
     <HELMHOLTZ_ELEMENT,ELASTICITY_ELEMENT>(bulk_elem_pt,
                                            face_index);
    // Add to mesh
    Helmholtz_fsi_flux_mesh_pt->add_element_pt(el_pt);
    // Associate element with bulk boundary (to allow it to access
    // the boundary coordinates in the bulk mesh)
    el_pt->set_boundary_number_in_bulk_mesh(b);
   }
 } // end_of_create_helmholtz_fsi_flux_elements
References b, e(), and oomph::FaceElement::set_boundary_number_in_bulk_mesh().
create_helmholtz_fsi_flux_elements() [2/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > void CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_fsi_flux_elements () private
Create Helmholtz FSI flux elements.
create_solid_traction_elements()
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > void CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_solid_traction_elements private
Create solid traction elements.
 {
  // Loop over pressure loaded boundaries
  unsigned b=0;
  unsigned nb=3;
  for (unsigned i=0;i<nb;i++)
   {
    switch(i)
     {
     case 0:
      b=Upper_inner_boundary_id;
      break;
     case 1:
      b=Lower_inner_boundary_id;
      break;
     case 2:
      b=Rib_divider_boundary_id;
      break;
     }
    // We're attaching face elements to region 0
    unsigned r=0;
    // How many bulk elements are adjacent to boundary b?
    unsigned n_element = Solid_mesh_pt->nboundary_element_in_region(b,r);
    // Loop over the bulk elements adjacent to boundary b
    for(unsigned e=0;e<n_element;e++)
     {
      // Get pointer to the bulk element that is adjacent to boundary b
      ELASTICITY_ELEMENT* bulk_elem_pt = dynamic_cast<ELASTICITY_ELEMENT*>(
       Solid_mesh_pt->boundary_element_in_region_pt(b,r,e));
      //Find the index of the face of element e along boundary b
      int face_index = Solid_mesh_pt->face_index_at_boundary_in_region(b,r,e);
      // Create element
      TimeHarmonicFourierDecomposedLinearElasticityTractionElement
       <ELASTICITY_ELEMENT>* el_pt=
       new TimeHarmonicFourierDecomposedLinearElasticityTractionElement
       <ELASTICITY_ELEMENT>(bulk_elem_pt,face_index);
      // Add to mesh
      Solid_traction_mesh_pt->add_element_pt(el_pt);
      // Associate element with bulk boundary (to allow it to access
      // the boundary coordinates in the bulk mesh)
      el_pt->set_boundary_number_in_bulk_mesh(b);
      //Set the traction function
      el_pt->traction_fct_pt() = Global_Parameters::pressure_load;
     }
   }
 } // end of create_traction_elements
References b, e(), i, nb, Global_Parameters::pressure_load(), UniformPSDSelfTest::r, and oomph::FaceElement::set_boundary_number_in_bulk_mesh().
delete_face_elements()
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > void CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::delete_face_elements (Mesh *const & boundary_mesh_pt) private
Delete (face) elements in specified mesh.
Delete face elements and wipe the mesh.
 {
  // How many surface elements are in the surface mesh
  unsigned n_element = boundary_mesh_pt->nelement();
  // Loop over the surface elements
  for(unsigned e=0;e<n_element;e++)
   {
    //   Kill surface element
    delete boundary_mesh_pt->element_pt(e);
   }
  // Wipe the mesh
  boundary_mesh_pt->flush_element_and_node_storage();
 } // end of delete_face_elements
References e(), oomph::Mesh::element_pt(), oomph::Mesh::flush_element_and_node_storage(), and oomph::Mesh::nelement().
doc_solution() [1/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > void CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
 {
  // Doc parameters
  oomph_info << "Writing result for step " << doc_info.number()
             << ". Parameters: "<< std::endl;
  oomph_info << "Fourier mode number : N = "
             << Global_Parameters::Fourier_wavenumber << std::endl;
  oomph_info << "FSI parameter : Q = " << Global_Parameters::Q << std::endl;
  oomph_info << "Fluid outer radius : R = " << Global_Parameters::Outer_radius
             << std::endl;
  oomph_info << "Fluid wavenumber : k^2 = " << Global_Parameters::K_squared
             << std::endl;
  oomph_info << "Solid wavenumber : Omega_sq = " << Global_Parameters::Omega_sq
             << std::endl << std::endl;
  ofstream some_file,some_file2;
  char filename[100];
  // Number of plot points
  unsigned n_plot=5;
  // Compute/output the radiated power
  //----------------------------------
  sprintf(filename,"%s/power%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  // Accumulate contribution from elements
  double power=0.0;
  unsigned nn_element=Helmholtz_DtN_mesh_pt->nelement();
  for(unsigned e=0;e<nn_element;e++)
   {
    FourierDecomposedHelmholtzBCElementBase<HELMHOLTZ_ELEMENT> *el_pt =
     dynamic_cast<FourierDecomposedHelmholtzBCElementBase<HELMHOLTZ_ELEMENT>*>(
      Helmholtz_DtN_mesh_pt->element_pt(e));
    power += el_pt->global_power_contribution(some_file);
   }
  some_file.close();
  oomph_info << "Radiated power: " << power << std::endl;
  // Output displacement field
  //--------------------------
  sprintf(filename,"%s/elast_soln%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  Solid_mesh_pt->output(some_file,n_plot);
  some_file.close();
  // Output Helmholtz
  //-----------------
  sprintf(filename,"%s/helmholtz_soln%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  Helmholtz_mesh_pt->output(some_file,n_plot);
  some_file.close();
  // Output fsi traction elements
  //-----------------------------
  sprintf(filename,"%s/fsi_traction_soln%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  FSI_traction_mesh_pt->output(some_file,n_plot);
  some_file.close();
  // Output Helmholtz fsi flux elements
  //-----------------------------------
  sprintf(filename,"%s/fsi_flux_bc_soln%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  Helmholtz_fsi_flux_mesh_pt->output(some_file,n_plot);
  some_file.close();
  // Write trace file
  Trace_file << Global_Parameters::Q << " "
             << Global_Parameters::K_squared << " "
             << Global_Parameters::Density_ratio << " "
             << Global_Parameters::Omega_sq.real() << " "
             << power << " "
             << std::endl;
  // Bump up counter
  doc_info.number()++;
 } //end_of_doc_solution
References Global_Parameters::Density_ratio, oomph::DocInfo::directory(), e(), MergeRestartFiles::filename, Global_Parameters::Fourier_wavenumber, oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::global_power_contribution(), Global_Parameters::K_squared, oomph::DocInfo::number(), Global_Parameters::Omega_sq, oomph::oomph_info, Global_Parameters::Outer_radius, Global_Parameters::Q, and oomph::Problem_Parameter::Trace_file.
doc_solution() [2/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > void CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
setup_interaction() [1/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > void CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::setup_interaction private
Setup interaction.
Setup interaction between two fields.
 {
  // Setup Helmholtz "pressure" load on traction elements
  unsigned boundary_in_helmholtz_mesh=0;
  // Doc boundary coordinate for Helmholtz
  ofstream the_file;
  the_file.open("boundary_coordinate_hh.dat");
  Helmholtz_mesh_pt->Mesh::template doc_boundary_coordinates<HELMHOLTZ_ELEMENT>
   (boundary_in_helmholtz_mesh, the_file);
  the_file.close();
  // Setup interaction
   Multi_domain_functions::setup_bulk_elements_adjacent_to_face_mesh
   <HELMHOLTZ_ELEMENT,2>
   (this,boundary_in_helmholtz_mesh,Helmholtz_mesh_pt,FSI_traction_mesh_pt);
  // Setup Helmholtz flux from normal displacement interaction
  unsigned boundary_in_solid_mesh=2;
  // Doc boundary coordinate for solid mesh
  the_file.open("boundary_coordinate_solid.dat");
  Solid_mesh_pt->Mesh::template doc_boundary_coordinates<ELASTICITY_ELEMENT>
   (boundary_in_solid_mesh, the_file);
  the_file.close();
  // Setup interaction
  Multi_domain_functions::setup_bulk_elements_adjacent_to_face_mesh
   <ELASTICITY_ELEMENT,2>(
    this,boundary_in_solid_mesh,Solid_mesh_pt,Helmholtz_fsi_flux_mesh_pt);
 }// end_of_setup_interaction
References oomph::Multi_domain_functions::setup_bulk_elements_adjacent_to_face_mesh().
setup_interaction() [2/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > void CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::setup_interaction () private
Setup interaction.
Member Data Documentation
FSI_traction_mesh_pt
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > Mesh * CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::FSI_traction_mesh_pt private
Pointer to mesh of FSI traction elements.
Helmholtz_DtN_mesh_pt
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > FourierDecomposedHelmholtzDtNMesh< HELMHOLTZ_ELEMENT > * CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Helmholtz_DtN_mesh_pt private
Pointer to mesh containing the DtN elements.
Helmholtz_fsi_flux_mesh_pt
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > Mesh * CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Helmholtz_fsi_flux_mesh_pt private
Pointer to mesh of Helmholtz FSI flux elements.
Helmholtz_mesh_pt [1/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > TwoDAnnularMesh<HELMHOLTZ_ELEMENT>* CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Helmholtz_mesh_pt private
Pointer to Helmholtz mesh.
Helmholtz_mesh_pt [2/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > TriangleMesh<HELMHOLTZ_ELEMENT>* CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Helmholtz_mesh_pt private
Pointer to Helmholtz mesh.
HH_inner_boundary_id
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > unsigned CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::HH_inner_boundary_id private
Boundary ID of inner boundary in Helmholtz mesh.
HH_lower_symmetry_boundary_id
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > unsigned CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::HH_lower_symmetry_boundary_id private
Boundary ID of lower boundary in Helmholtz mesh.
HH_outer_boundary_id
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > unsigned CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::HH_outer_boundary_id private
Boundary ID of outer boundary in Helmholtz mesh.
HH_upper_symmetry_boundary_id
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > unsigned CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::HH_upper_symmetry_boundary_id private
Boundary ID of upper boundary in Helmholtz mesh.
Lower_inner_boundary_id
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > unsigned CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Lower_inner_boundary_id private
Boundary ID of lower inner boundary.
Lower_symmetry_boundary_id
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > unsigned CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Lower_symmetry_boundary_id private
Boundary ID of lower symmetry boundary.
Outer_boundary_id
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > unsigned CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Outer_boundary_id private
Boundary ID of outer boundary.
Rib_divider_boundary_id
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > unsigned CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Rib_divider_boundary_id private
Boundary ID of rib divider.
Solid_mesh_pt [1/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > TwoDAnnularMesh<ELASTICITY_ELEMENT>* CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Solid_mesh_pt private
Pointer to solid mesh.
Solid_mesh_pt [2/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > TriangleMesh<ELASTICITY_ELEMENT>* CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Solid_mesh_pt private
Pointer to solid mesh.
Solid_traction_mesh_pt
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > Mesh* CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Solid_traction_mesh_pt private
Pointer to mesh of solid traction elements.
Trace_file
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > ofstream CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Trace_file private
Trace file.
Upper_inner_boundary_id
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > unsigned CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Upper_inner_boundary_id private
Boundary ID of upper inner boundary.
Upper_symmetry_boundary_id
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT > unsigned CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Upper_symmetry_boundary_id private
Boundary ID of upper symmetry boundary.
The documentation for this class was generated from the following files:
fourier_decomposed_acoustic_fsi.cc
unstructured_fourier_decomposed_acoustic_fsi.cc