MercuryDPM: Eigen::internal::redux_impl< Func, Evaluator, DefaultTraversal, NoUnrolling > Struct Template Reference
Eigen::internal::redux_impl< Func, Evaluator, DefaultTraversal, NoUnrolling > Struct Template Reference
#include <Redux.h>
Public Types
typedef Evaluator::Scalar Scalar
Static Public Member Functions
template<typename XprType >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar run (const Evaluator &eval, const Func &func, const XprType &xpr)
Member Typedef Documentation
Scalar
template<typename Func , typename Evaluator > typedef Evaluator::Scalar Eigen::internal::redux_impl< Func, Evaluator, DefaultTraversal, NoUnrolling >::Scalar
Member Function Documentation
run()
template<typename Func , typename Evaluator > template<typename XprType > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar Eigen::internal::redux_impl< Func, Evaluator, DefaultTraversal, NoUnrolling >::run (const Evaluator & eval, const Func & func, const XprType & xpr) inline static
{
     eigen_assert(xpr.rows() > 0 && xpr.cols() > 0 && "you are using an empty matrix");
     Scalar res = eval.coeffByOuterInner(0, 0);
     for (Index i = 1; i < xpr.innerSize(); ++i) res = func(res, eval.coeffByOuterInner(0, i));
     for (Index i = 1; i < xpr.outerSize(); ++i)
       for (Index j = 0; j < xpr.innerSize(); ++j) res = func(res, eval.coeffByOuterInner(i, j));
     return res;
   }
References Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::cols(), eigen_assert, func(), i, j, res, and Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::rows().
The documentation for this struct was generated from the following file:
Redux.h