MercuryDPM: rapidjson Namespace Reference
rapidjson Namespace Reference
Namespaces
internal
Classes
class GenericValue
Represents a JSON value. Use Value for UTF8 encoding and default allocator.
class GenericDocument
A document for parsing JSON text as DOM.
class FileStream
Wrapper of C file stream for input or output.
class GenericReadStream
Wrapper of std::istream for input.
class GenericWriteStream
Wrapper of std::ostream for output.
class PrettyWriter
Writer with indentation and spacing.
class CrtAllocator
C-runtime library allocator.
class MemoryPoolAllocator
Default memory allocator used by the parser and DOM.
struct UTF8
UTF-8 encoding.
struct UTF16
UTF-16 encoding.
struct UTF32
UTF-32 encoding.
struct GenericStringStream
Read-only string stream.
struct GenericInsituStringStream
A read-write string stream.
struct BaseReaderHandler
Default implementation of Handler.
class GenericReader
SAX-style JSON parser. Use Reader for UTF8 encoding and default allocator.
struct GenericStringBuffer
Represents an in-memory output stream.
class Writer
JSON writer.
Typedefs
typedef GenericValue< UTF8<> > Value
Value with UTF8 encoding.
typedef GenericDocument< UTF8<> > Document
typedef unsigned SizeType
Use 32-bit array/string indices even for 64-bit platform, instead of using size_t.
typedef GenericStringStream< UTF8<> > StringStream
typedef GenericInsituStringStream< UTF8<> > InsituStringStream
typedef GenericReader< UTF8<> > Reader
Reader with UTF8 encoding and default allocator.
typedef GenericStringBuffer< UTF8<> > StringBuffer
Enumerations
enum Type {
kNull_Type = 0 , kFalseType = 1 , kTrueType = 2 , kObjectType = 3 ,
kArrayType = 4 , kStringType = 5 , kNumberType = 6
}
Type of JSON value.
enum ParseFlag { kParseDefaultFlags = 0 , kParseInsituFlag = 1 }
Combination of parseFlags.
Functions
template<>
void PutN (GenericWriteStream &stream, char c, size_t n)
template<typename Stream , typename Ch >
void PutN (Stream &stream, Ch c, size_t n)
Put N copies of a character to a stream.
template<typename Stream >
void SkipWhitespace (Stream &stream)
Skip the JSON white spaces in a stream.
template<>
void PutN (GenericStringBuffer< UTF8<> > &stream, char c, size_t n)
Implement specialized version of PutN() with memset() for better performance.
Typedef Documentation
Document
typedef GenericDocument<UTF8<> > rapidjson::Document
InsituStringStream
typedef GenericInsituStringStream<UTF8<> > rapidjson::InsituStringStream
Reader
typedef GenericReader<UTF8<> > rapidjson::Reader
Reader with UTF8 encoding and default allocator.
SizeType
typedef unsigned rapidjson::SizeType
Use 32-bit array/string indices even for 64-bit platform, instead of using size_t.
User may override the SizeType by defining RAPIDJSON_NO_SIZETYPEDEFINE.
StringBuffer
typedef GenericStringBuffer<UTF8<> > rapidjson::StringBuffer
StringStream
typedef GenericStringStream<UTF8<> > rapidjson::StringStream
Value
typedef GenericValue<UTF8<> > rapidjson::Value
Value with UTF8 encoding.
Enumeration Type Documentation
ParseFlag
enum rapidjson::ParseFlag
Combination of parseFlags.
Enumerator
kParseDefaultFlags
Default parse flags. Non-destructive parsing. Text strings are decoded into allocated buffer.
kParseInsituFlag
In-situ(destructive) parsing.
                    {
         kParseDefaultFlags = 0,
         kParseInsituFlag = 1
     };
Type
enum rapidjson::Type
Type of JSON value.
Enumerator
kNull_Type
null
kFalseType
false
kTrueType
true
kObjectType
object
kArrayType
array
kStringType
string
kNumberType
number
               {
         kNull_Type = 0,
         kFalseType = 1,
         kTrueType = 2,
         kObjectType = 3,
         kArrayType = 4,
         kStringType = 5,
         kNumberType = 6,
     };
Function Documentation
PutN() [1/3]
template<> void rapidjson::PutN (GenericStringBuffer< UTF8<> > & stream, char c, size_t n) inline
Implement specialized version of PutN() with memset() for better performance.
{
     memset(stream.stack_.Push<char>(n), c, n * sizeof(c));
 }
References calibrate::c, and n.
PutN() [2/3]
template<> void rapidjson::PutN (GenericWriteStream & stream, char c, size_t n) inline
{
       stream.PutN(c, n);
     }
References calibrate::c, n, and rapidjson::GenericWriteStream::PutN().
Referenced by rapidjson::PrettyWriter< Stream, Encoding, Allocator >::WriteIndent().
PutN() [3/3]
template<typename Stream , typename Ch > void rapidjson::PutN (Stream & stream, Ch c, size_t n) inline
Put N copies of a character to a stream.
{
         for (size_t i = 0; i < n; i++)
             stream.Put(c);
     }
References calibrate::c, i, and n.
SkipWhitespace()
template<typename Stream > void rapidjson::SkipWhitespace (Stream & stream)
Skip the JSON white spaces in a stream.
Parameters
stream A input stream for skipping white spaces.
Note
This function has SSE2/SSE4.2 specialization.
{
         Stream s = stream;  // Use a local copy for optimization
         while (s.Peek() == ' ' || s.Peek() == '\n' || s.Peek() == '\r' || s.Peek() == '\t')
             s.Take();
         stream = s;
     }
References s.
Referenced by rapidjson::GenericReader< Encoding, Allocator >::Parse(), rapidjson::GenericReader< Encoding, Allocator >::ParseArray(), and rapidjson::GenericReader< Encoding, Allocator >::ParseObject().