MercuryDPM: cast_test_impl< SrcType, DstType, RowsAtCompileTime, ColsAtCompileTime > Struct Template Reference
cast_test_impl< SrcType, DstType, RowsAtCompileTime, ColsAtCompileTime > Struct Template Reference
Classes
struct RandomOp
Public Types
using SrcArray = Array< SrcType, RowsAtCompileTime, ColsAtCompileTime >
using DstArray = Array< DstType, RowsAtCompileTime, ColsAtCompileTime >
Static Public Member Functions
static void run ()
Static Public Attributes
static constexpr int SrcPacketSize = internal::packet_traits<SrcType>::size
static constexpr int DstPacketSize = internal::packet_traits<DstType>::size
static constexpr int MaxPacketSize = internal::plain_enum_max(SrcPacketSize, DstPacketSize)
Member Typedef Documentation
DstArray
template<typename SrcType , typename DstType , int RowsAtCompileTime, int ColsAtCompileTime> using cast_test_impl< SrcType, DstType, RowsAtCompileTime, ColsAtCompileTime >::DstArray = Array<DstType, RowsAtCompileTime, ColsAtCompileTime>
SrcArray
template<typename SrcType , typename DstType , int RowsAtCompileTime, int ColsAtCompileTime> using cast_test_impl< SrcType, DstType, RowsAtCompileTime, ColsAtCompileTime >::SrcArray = Array<SrcType, RowsAtCompileTime, ColsAtCompileTime>
Member Function Documentation
run()
template<typename SrcType , typename DstType , int RowsAtCompileTime, int ColsAtCompileTime> static void cast_test_impl< SrcType, DstType, RowsAtCompileTime, ColsAtCompileTime >::run () inline static
                     {
     const Index testRows = RowsAtCompileTime == Dynamic ? ((10 * MaxPacketSize) + 1) : RowsAtCompileTime;
     const Index testCols = ColsAtCompileTime == Dynamic ? ((10 * MaxPacketSize) + 1) : ColsAtCompileTime;
     const Index testSize = testRows * testCols;
     const Index minTestSize = 100;
     const Index repeats = numext::div_ceil(minTestSize, testSize);
     SrcArray src(testRows, testCols);
     DstArray dst(testRows, testCols);
     for (Index repeat = 0; repeat < repeats; repeat++) {
       src = src.unaryExpr(RandomOp());
       dst = src.template cast<DstType>();
       for (Index j = 0; j < testCols; j++)
         for (Index i = 0; i < testRows; i++) {
           SrcType srcVal = src(i, j);
           DstType refVal = internal::cast_impl<SrcType, DstType>::run(srcVal);
           DstType dstVal = dst(i, j);
           bool isApprox = verifyIsApprox(dstVal, refVal);
           if (!isApprox)
             std::cout << type_name(srcVal) << ": [" << +srcVal << "] to " << type_name(dstVal) << ": [" << +dstVal
                       << "] != [" << +refVal << "]\n";
           VERIFY(isApprox);
         }
     }
   }
References Eigen::numext::div_ceil(), Eigen::Dynamic, i, Eigen::internal::isApprox(), j, cast_test_impl< SrcType, DstType, RowsAtCompileTime, ColsAtCompileTime >::MaxPacketSize, Eigen::internal::repeat(), run(), type_name(), VERIFY, and Eigen::verifyIsApprox().
Referenced by cast_tests_impl< RowsAtCompileTime, ColsAtCompileTime, ScalarTypes >::run().
Member Data Documentation
DstPacketSize
template<typename SrcType , typename DstType , int RowsAtCompileTime, int ColsAtCompileTime> constexpr int cast_test_impl< SrcType, DstType, RowsAtCompileTime, ColsAtCompileTime >::DstPacketSize = internal::packet_traits<DstType>::size static constexpr
MaxPacketSize
template<typename SrcType , typename DstType , int RowsAtCompileTime, int ColsAtCompileTime> constexpr int cast_test_impl< SrcType, DstType, RowsAtCompileTime, ColsAtCompileTime >::MaxPacketSize = internal::plain_enum_max(SrcPacketSize, DstPacketSize) static constexpr
Referenced by cast_test_impl< SrcType, DstType, RowsAtCompileTime, ColsAtCompileTime >::run().
SrcPacketSize
template<typename SrcType , typename DstType , int RowsAtCompileTime, int ColsAtCompileTime> constexpr int cast_test_impl< SrcType, DstType, RowsAtCompileTime, ColsAtCompileTime >::SrcPacketSize = internal::packet_traits<SrcType>::size static constexpr
The documentation for this struct was generated from the following file:
array_cwise.cpp