MercuryDPM: TanhSolnForPoisson Namespace Reference
TanhSolnForPoisson Namespace Reference
Namespace for exact solution for Poisson equation with "sharp step".
Functions
void get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void get_exact_u (const Vector< double > &x, double &u)
Exact solution as a scalar.
void get_source (const Vector< double > &x, double &source)
Source function to make it an exact solution.
void source_function (const Vector< double > &x, double &source)
Source function required to make the solution above an exact solution.
void zero (const Vector< double > &x, Vector< double > &u)
void get_exact_gradient (const Vector< double > &x, Vector< double > &dudx)
Exact gradient as a Vector.
void prescribed_flux_on_fixed_x_boundary (const Vector< double > &x, double &flux)
Flux required by the exact solution on a boundary on which x is fixed.
Variables
double Alpha =1.0
Parameter for steepness of step.
double N_x =-1.0
Orientation of non-normalised x-component of vector in plane direction.
double N_y =-1.0
Orientation of non-normalised y-component of vector in plane direction.
double N_z =1.0
Orientation of non-normalised z-component of vector in plane direction.
double X_0 =0.0
Orientation (x-coordinate of step plane)
double Y_0 =0.0
Orientation (y-coordinate of step plane)
double Z_0 =0.0
Orientation (z-coordinate of step plane)
double TanPhi =0.0
Parameter for angle Phi of "step".
double Beta
Parameter for angle of step.
double X_shift =8.0
Shift of step along x-direction.
bool TanhSoln =false
Flag for zero TanhSolution.
Detailed Description
Namespace for exact solution for Poisson equation with "sharp step".
Namespace for exact solution for Poisson equation.
Namespace for exact solution for Poisson equation with sharp step.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Function Documentation
get_exact_gradient()
void TanhSolnForPoisson::get_exact_gradient (const Vector< double > & x, Vector< double > & dudx)
Exact gradient as a Vector.
  {
   //dudx[0]=tanh(1.0-Alpha*(TanPhi*x[0]-x[1]));
   double CoshTerm = cosh(1.0-Alpha*(TanPhi*x[0]-x[1]))
                    *cosh(1.0-Alpha*(TanPhi*x[0]-x[1]));
   dudx[0] = -Alpha*TanPhi/CoshTerm;
   dudx[1] = Alpha/CoshTerm;
  }
References TanhSolnForAdvectionDiffusion::Alpha, Eigen::bfloat16_impl::cosh(), TanhSolnForAdvectionDiffusion::TanPhi, and plotDoE::x.
get_exact_u() [1/2]
void TanhSolnForPoisson::get_exact_u (const Vector< double > & x, double & u)
Exact solution as a scalar.
   {
     double d=std::sqrt(N_x*N_x+N_y*N_y+N_z*N_z);
     u=std::tanh(Alpha*((x[0]-X_0)*N_x+
                        (x[1]-Y_0)*N_y+
                        (x[2]-Z_0)*N_z)/d);
   } // End of get_exact_u
References Alpha, N_x, N_y, N_z, sqrt(), Eigen::bfloat16_impl::tanh(), plotDoE::x, X_0, Y_0, and Z_0.
Referenced by get_source().
get_exact_u() [2/2]
void TanhSolnForPoisson::get_exact_u (const Vector< double > & x, Vector< double > & u)
Exact solution as a Vector.
   {
     double d=std::sqrt(N_x*N_x+N_y*N_y+N_z*N_z);
     u[0]=std::tanh(Alpha*((x[0]-X_0)*N_x+
                           (x[1]-Y_0)*N_y+
                           (x[2]-Z_0)*N_z)/d);
   } // End of get_exact_u
References Alpha, N_x, N_y, N_z, sqrt(), Eigen::bfloat16_impl::tanh(), plotDoE::x, X_0, Y_0, and Z_0.
Referenced by PoissonProblem< ELEMENT >::actions_before_newton_solve(), RefineableTwoDPoissonProblem< ELEMENT >::actions_before_newton_solve(), RefineableTwoMeshFluxPoissonProblem< ELEMENT >::actions_before_newton_solve(), FluxPoissonMGProblem< ELEMENT, MESH >::actions_before_newton_solve(), UnitCubePoissonMGProblem< ELEMENT, MESH >::actions_before_newton_solve(), RefineablePoissonProblem< ELEMENT >::actions_before_newton_solve(), EighthSpherePoissonProblem< ELEMENT >::actions_before_newton_solve(), FluxPoissonProblem< ELEMENT >::actions_before_newton_solve(), TwoMeshFluxPoissonProblem< ELEMENT >::actions_before_newton_solve(), ThreeDPoissonProblem< ELEMENT >::actions_before_newton_solve(), TestPoissonProblem< ELEMENT >::actions_before_newton_solve(), TestRefineablePoissonProblem< ELEMENT >::actions_before_newton_solve(), ExtrudedMovingCylinderProblem< TWO_D_ELEMENT, THREE_D_ELEMENT >::apply_boundary_conditions(), UnstructuredPoissonProblem< ELEMENT >::apply_boundary_conditions(), PoissonProblem< ELEMENT >::apply_boundary_conditions(), ExtrudedMovingCylinderProblem< TWO_D_ELEMENT, THREE_D_ELEMENT >::doc_solution(), UnstructuredPoissonProblem< ELEMENT >::doc_solution(), PoissonProblem< ELEMENT >::doc_solution(), RefineableTwoDPoissonProblem< ELEMENT >::doc_solution(), RefineableTwoMeshFluxPoissonProblem< ELEMENT >::doc_solution(), FluxPoissonMGProblem< ELEMENT, MESH >::doc_solution(), UnitCubePoissonMGProblem< ELEMENT, MESH >::doc_solution(), RefineablePoissonProblem< ELEMENT >::doc_solution(), EighthSpherePoissonProblem< ELEMENT >::doc_solution(), FluxPoissonProblem< ELEMENT >::doc_solution(), and TwoMeshFluxPoissonProblem< ELEMENT >::doc_solution().
get_source()
void TanhSolnForPoisson::get_source (const Vector< double > & x, double & source)
Source function to make it an exact solution.
Source function required to make the solution above an exact solution.
   {
     // Storage for the solution
     double u=0.0;
     // Calculate the solution
     get_exact_u(x,u);
     // Calculate the source value
     source=-2.0*u*(1.0-pow(u,2.0))*Alpha*Alpha;
   } // End of get_source
References Alpha, get_exact_u(), Eigen::bfloat16_impl::pow(), TestProblem::source(), and plotDoE::x.
Referenced by UnstructuredPoissonProblem< ELEMENT >::complete_problem_setup(), oomph::BiharmonicEquations< DIM >::fill_in_generic_residual_contribution_biharmonic(), main(), UnitCubePoissonMGProblem< ELEMENT, MESH >::make_new_problem(), parallel_test(), run(), and run_test().
prescribed_flux_on_fixed_x_boundary()
void TanhSolnForPoisson::prescribed_flux_on_fixed_x_boundary (const Vector< double > & x, double & flux)
Flux required by the exact solution on a boundary on which x is fixed.
  {
   //The outer unit normal to the boundary is (1,0)
   double N[2] = {1.0, 0.0};
   //The flux in terms of the normal is
   flux =
    -(1.0-pow(tanh(-1.0+Alpha*(TanPhi*x[0]-x[1])),2.0))*Alpha*TanPhi*N[0]+(
    1.0-pow(tanh(-1.0+Alpha*(TanPhi*x[0]-x[1])),2.0))*Alpha*N[1];
  }
References TanhSolnForAdvectionDiffusion::Alpha, ProblemParameters::flux(), N, Eigen::bfloat16_impl::pow(), Eigen::bfloat16_impl::tanh(), TanhSolnForAdvectionDiffusion::TanPhi, and plotDoE::x.
Referenced by FluxPoissonMGProblem< ELEMENT, MESH >::create_flux_elements(), FluxPoissonProblem< ELEMENT >::FluxPoissonProblem(), RefineableTwoMeshFluxPoissonProblem< ELEMENT >::set_prescribed_flux_pt(), and TwoMeshFluxPoissonProblem< ELEMENT >::TwoMeshFluxPoissonProblem().
source_function()
void TanhSolnForPoisson::source_function (const Vector< double > & x, double & source)
Source function required to make the solution above an exact solution.
  {
   source = 2.0*tanh(-1.0+Alpha*(TanPhi*x[0]-x[1]))*
    (1.0-pow(tanh(-1.0+Alpha*(TanPhi*x[0]-x[1])),2.0))*
    Alpha*Alpha*TanPhi*TanPhi+2.0*tanh(-1.0+Alpha*(TanPhi*x[0]-x[1]))*
    (1.0-pow(tanh(-1.0+Alpha*(TanPhi*x[0]-x[1])),2.0))*Alpha*Alpha;
  }
References TanhSolnForAdvectionDiffusion::Alpha, Eigen::bfloat16_impl::pow(), TestProblem::source(), Eigen::bfloat16_impl::tanh(), TanPhi, and plotDoE::x.
Referenced by main(), and FluxPoissonMGProblem< ELEMENT, MESH >::make_new_problem().
zero()
void TanhSolnForPoisson::zero (const Vector< double > & x, Vector< double > & u)
Zero function – used to compute norm of the computed solution by computing the norm of the error when compared against this.
  {
   u[0]=0.0;
  }
Referenced by UnstructuredPoissonProblem< ELEMENT >::doc_solution().
Variable Documentation
Alpha
double TanhSolnForPoisson::Alpha =1.0
Parameter for steepness of step.
Parameter for steepness of "step".
Referenced by EighthSpherePoissonProblem< ELEMENT >::EighthSpherePoissonProblem(), ExtrudedMovingCylinderProblem< TWO_D_ELEMENT, THREE_D_ELEMENT >::ExtrudedMovingCylinderProblem(), get_exact_u(), get_source(), main(), PoissonProblem< ELEMENT >::PoissonProblem(), run(), ThreeDPoissonProblem< ELEMENT >::ThreeDPoissonProblem(), and UnitCubePoissonMGProblem< ELEMENT, MESH >::UnitCubePoissonMGProblem().
Beta
double TanhSolnForPoisson::Beta
Parameter for angle of step.
Referenced by main(), and PoissonProblem< ELEMENT >::PoissonProblem().
N_x
double TanhSolnForPoisson::N_x =-1.0
Orientation of non-normalised x-component of vector in plane direction.
Orientation (non-normalised x-component of unit vector in direction of step plane)
Referenced by get_exact_u().
N_y
double TanhSolnForPoisson::N_y =-1.0
Orientation of non-normalised y-component of vector in plane direction.
Orientation (non-normalised y-component of unit vector in direction of step plane)
Referenced by get_exact_u().
N_z
double TanhSolnForPoisson::N_z =1.0
Orientation of non-normalised z-component of vector in plane direction.
Orientation (non-normalised z-component of unit vector in direction of step plane)
Referenced by get_exact_u().
TanhSoln
bool TanhSolnForPoisson::TanhSoln =false
Flag for zero TanhSolution.
Referenced by main().
TanPhi
double TanhSolnForPoisson::TanPhi =0.0
Parameter for angle Phi of "step".
Parameter for angle Phi of "step" (45 degrees)
Referenced by main(), run(), and source_function().
X_0
double TanhSolnForPoisson::X_0 =0.0
Orientation (x-coordinate of step plane)
Referenced by get_exact_u(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::node_update_I(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::node_update_II(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::node_update_III(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::node_update_IV(), Leaflet::position(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::setup_algebraic_node_update(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::slanted_bound_up(), and Leaflet::x_0().
X_shift
double TanhSolnForPoisson::X_shift =8.0
Shift of step along x-direction.
Y_0
double TanhSolnForPoisson::Y_0 =0.0
Orientation (y-coordinate of step plane)
Referenced by get_exact_u().
Z_0
double TanhSolnForPoisson::Z_0 =0.0
Orientation (z-coordinate of step plane)
Referenced by get_exact_u().