MercuryDPM: ElasticAnnulusProblem< ELASTICITY_ELEMENT > Class Template Reference
ElasticAnnulusProblem< ELASTICITY_ELEMENT > Class Template Reference
Annular disk.
Public Member Functions
ElasticAnnulusProblem ()
Constructor:
~ElasticAnnulusProblem ()
Destructor (empty)
void actions_after_newton_solve ()
Update function (empty)
void actions_before_newton_solve ()
Update function (empty)
void create_pml_meshes ()
Create PML meshes.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of traction elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of traction elements.
void doc_solution (DocInfo &doc_info)
Doc the solution.
ElasticAnnulusProblem ()
Constructor:
~ElasticAnnulusProblem ()
Destructor (empty)
void actions_after_newton_solve ()
Update function (empty)
void actions_before_newton_solve ()
Update function (empty)
void create_pml_meshes ()
Create PML meshes.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of traction elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of traction elements.
void doc_solution (DocInfo &doc_info)
Doc the solution.
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Private Member Functions
void complete_problem_setup ()
Helper function to complete problem setup.
void complete_problem_setup ()
Helper function to complete problem setup.
Private Attributes
RefineableTriangleMesh< ELASTICITY_ELEMENT > * Solid_mesh_pt
Pointer to refineable solid mesh.
Mesh * PML_right_mesh_pt
Pointer to the right PML mesh.
Mesh * PML_top_mesh_pt
Pointer to the top PML mesh.
Mesh * PML_left_mesh_pt
Pointer to the left PML mesh.
Mesh * PML_bottom_mesh_pt
Pointer to the bottom PML mesh.
Mesh * PML_top_right_mesh_pt
Pointer to the top right corner PML mesh.
Mesh * PML_top_left_mesh_pt
Pointer to the top left corner PML mesh.
Mesh * PML_bottom_right_mesh_pt
Pointer to the bottom right corner PML mesh.
Mesh * PML_bottom_left_mesh_pt
Pointer to the bottom left corner PML mesh.
DocInfo Doc_info
DocInfo object for output.
unsigned Upper_inner_boundary_id
Boundary ID of upper inner boundary.
unsigned Upper_outer_boundary_id
Boundary ID of upper outer boundary.
unsigned Lower_inner_boundary_id
Boundary ID of lower inner boundary.
unsigned Lower_outer_boundary_id
Boundary ID of lower outer boundary.
RectangularQuadMesh< ELASTICITY_ELEMENT > * Solid_mesh_pt
Pointer to solid mesh.
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_convergence_check ()
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_before_implicit_timestep ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual void set_initial_condition ()
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class ELASTICITY_ELEMENT>
class ElasticAnnulusProblem< ELASTICITY_ELEMENT >
Annular disk.
Constructor & Destructor Documentation
ElasticAnnulusProblem() [1/2]
template<class ELASTICITY_ELEMENT > ElasticAnnulusProblem< ELASTICITY_ELEMENT >::ElasticAnnulusProblem
Constructor:
Number of elements in x direction in the bulk mesh
Number of elements in y direction in the bulk mesh
Start and end spatial coordinates of the bulk mesh in x direction
Start and end spatial coordinates of the bulk mesh in y direction
 {
  // Solid mesh
  //-----------
  // Create circle representing inner boundary
  double a=0.2;
  double x_c=0.0;
  double y_c=0.0;
  Circle* inner_circle_pt=new Circle(x_c,y_c,a);
  // Outer boundary
  //---------------
  TriangleMeshClosedCurve* outer_boundary_pt=0;
  unsigned n_segments = 16;
  Vector<TriangleMeshCurveSection*> outer_boundary_line_pt(4);
  // Each polyline only has three vertices, provide storage for their
  // coordinates
  Vector<Vector<double> > vertex_coord(2);
  for(unsigned i=0;i<2;i++)
   {
    vertex_coord[i].resize(2);
   }
  // First polyline
  vertex_coord[0][0]=-2.0;
  vertex_coord[0][1]=-2.0;
  vertex_coord[1][0]=-2.0;
  vertex_coord[1][1]=2.0;
  // Build the 1st boundary polyline
  unsigned boundary_id=2;
  outer_boundary_line_pt[0] = new TriangleMeshPolyLine(vertex_coord,
                                                       boundary_id);
  // Second boundary polyline
  vertex_coord[0][0]=-2.0;
  vertex_coord[0][1]=2.0;
  vertex_coord[1][0]=2.0;
  vertex_coord[1][1]=2.0;
  // Build the 2nd boundary polyline
  boundary_id=3;
  outer_boundary_line_pt[1] = new TriangleMeshPolyLine(vertex_coord,
                                                       boundary_id);
  // Third boundary polyline
  vertex_coord[0][0]=2.0;
  vertex_coord[0][1]=2.0;
  vertex_coord[1][0]=2.0;
  vertex_coord[1][1]=-2.0;
  // Build the 3rd boundary polyline
  boundary_id=4;
  outer_boundary_line_pt[2] = new TriangleMeshPolyLine(vertex_coord,
                                                       boundary_id);
  // Fourth boundary polyline
  vertex_coord[0][0]=2.0;
  vertex_coord[0][1]=-2.0;
  vertex_coord[1][0]=-2.0;
  vertex_coord[1][1]=-2.0;
  // Build the 4th boundary polyline
  boundary_id=5;
  outer_boundary_line_pt[3] = new TriangleMeshPolyLine(vertex_coord,
                                                       boundary_id);
  // Create the triangle mesh polygon for outer boundary
  outer_boundary_pt = new TriangleMeshPolygon(outer_boundary_line_pt);
  // Inner circular boundary
  //------------------------
  Vector<TriangleMeshCurveSection*> inner_boundary_line_pt(2);
  // The intrinsic coordinates for the beginning and end of the curve
  double s_start = 0.0;
  double s_end   = MathematicalConstants::Pi;
  boundary_id = 0;
  inner_boundary_line_pt[0]=
   new TriangleMeshCurviLine(inner_circle_pt,
                             s_start,
                             s_end,
                             n_segments,
                             boundary_id);
  // The intrinsic coordinates for the beginning and end of the curve
  s_start = MathematicalConstants::Pi;
  s_end   = 2.0*MathematicalConstants::Pi;
  boundary_id = 1;
  inner_boundary_line_pt[1]=
   new TriangleMeshCurviLine(inner_circle_pt,
                             s_start,
                             s_end,
                             n_segments,
                             boundary_id);
  // Combine to hole
  //----------------
  Vector<TriangleMeshClosedCurve*> hole_pt(1);
  Vector<double> hole_coords(2);
  hole_coords[0]=0.0;
  hole_coords[1]=0.0;
  hole_pt[0]=new TriangleMeshClosedCurve(inner_boundary_line_pt,
                                         hole_coords);
  // Use the TriangleMeshParameters object for helping on the manage
  // of the TriangleMesh parameters. The only parameter that needs to take
  // is the outer boundary.
  TriangleMeshParameters triangle_mesh_parameters(outer_boundary_pt);
  // Specify the closed curve using the TriangleMeshParameters object
  triangle_mesh_parameters.internal_closed_curve_pt() = hole_pt;
  // Target element size in bulk mesh
  triangle_mesh_parameters.element_area() = Global_Parameters::Element_area;
 #ifdef ADAPTIVE
  // Build the mesh
  Solid_mesh_pt=new
   RefineableTriangleMesh<ELASTICITY_ELEMENT>(triangle_mesh_parameters);
  // Set error estimator
  Solid_mesh_pt->spatial_error_estimator_pt()=new Z2ErrorEstimator;
  // Choose error tolerances to force some uniform refinement
  Solid_mesh_pt->min_permitted_error()=0.000001;
  Solid_mesh_pt->max_permitted_error()=0.00005;
 #else
  // Build the mesh
  Solid_mesh_pt=new
   TriangleMesh<ELASTICITY_ELEMENT>(triangle_mesh_parameters);
 #endif
  // Create the main triangular mesh
  add_sub_mesh(Solid_mesh_pt);
  // Create PML meshes and add them to the global mesh
  create_pml_meshes();
  // Build the entire mesh from its submeshes
  build_global_mesh();
  // Let's have a look where the boundaries are
  this->mesh_pt()->output("global_mesh.dat");
  this->mesh_pt()->output_boundaries("global_mesh_boundary.dat");
  // Complete problem setup
  complete_problem_setup();
  //Assign equation numbers
  cout << assign_eqn_numbers() << std::endl;
  // Set output directory
  Doc_info.set_directory(Global_Parameters::Directory);
 } //end_of_constructor
References a, Global_Parameters::Directory, GlobalParameters::Doc_info, Global_Parameters::Element_area, oomph::TriangleMeshParameters::element_area(), i, oomph::TriangleMeshParameters::internal_closed_curve_pt(), BiharmonicTestFunctions2::Pi, and oomph::DocInfo::set_directory().
~ElasticAnnulusProblem() [1/2]
template<class ELASTICITY_ELEMENT > ElasticAnnulusProblem< ELASTICITY_ELEMENT >::~ElasticAnnulusProblem () inline
Destructor (empty)
 {}
ElasticAnnulusProblem() [2/2]
template<class ELASTICITY_ELEMENT > ElasticAnnulusProblem< ELASTICITY_ELEMENT >::ElasticAnnulusProblem ()
Constructor:
~ElasticAnnulusProblem() [2/2]
template<class ELASTICITY_ELEMENT > ElasticAnnulusProblem< ELASTICITY_ELEMENT >::~ElasticAnnulusProblem () inline
Destructor (empty)
 {}
Member Function Documentation
actions_after_adapt() [1/2]
template<class ELASTICITY_ELEMENT > void ElasticAnnulusProblem< ELASTICITY_ELEMENT >::actions_after_adapt virtual
Actions after adapt: Rebuild the mesh of traction elements.
Actions after adapt: complete problem setup.
Reimplemented from oomph::Problem.
 {
  // Build PML meshes  and add them to the global mesh
  create_pml_meshes();
  // Build the entire mesh from its submeshes
  rebuild_global_mesh();
  // Complete problem setup
  complete_problem_setup();
 }// end of actions_after_adapt
actions_after_adapt() [2/2]
template<class ELASTICITY_ELEMENT > void ElasticAnnulusProblem< ELASTICITY_ELEMENT >::actions_after_adapt () virtual
Actions after adapt: Rebuild the mesh of traction elements.
Reimplemented from oomph::Problem.
actions_after_newton_solve() [1/2]
template<class ELASTICITY_ELEMENT > void ElasticAnnulusProblem< ELASTICITY_ELEMENT >::actions_after_newton_solve () inline virtual
Update function (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [2/2]
template<class ELASTICITY_ELEMENT > void ElasticAnnulusProblem< ELASTICITY_ELEMENT >::actions_after_newton_solve () inline virtual
Update function (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_adapt() [1/2]
template<class ELASTICITY_ELEMENT > void ElasticAnnulusProblem< ELASTICITY_ELEMENT >::actions_before_adapt virtual
Actions before adapt: Wipe the mesh of traction elements.
Actions before adapt: empty.
Reimplemented from oomph::Problem.
 {
  // Before adapting the added PML meshes must be removed
  // as they are not refineable and are to be rebuilt from the
  // newly refined triangular mesh
  delete PML_right_mesh_pt;
  PML_right_mesh_pt=0;
  delete PML_top_mesh_pt;
  PML_top_mesh_pt=0;
  delete PML_left_mesh_pt;
  PML_left_mesh_pt=0;
  delete PML_bottom_mesh_pt;
  PML_bottom_mesh_pt=0;
  delete PML_top_right_mesh_pt;
  PML_top_right_mesh_pt=0;
  delete PML_top_left_mesh_pt;
  PML_top_left_mesh_pt=0;
  delete PML_bottom_right_mesh_pt;
  PML_bottom_right_mesh_pt=0;
  delete PML_bottom_left_mesh_pt;
  PML_bottom_left_mesh_pt=0;
  // Rebuild the Problem's global mesh from its various sub-meshes
  // but first flush all its submeshes
  flush_sub_meshes();
  // Then add the triangular mesh back
  add_sub_mesh(Solid_mesh_pt);
  // Rebuild the global mesh such that it now stores
  // the triangular mesh only
  rebuild_global_mesh();
 }// end of actions_before_adapt
actions_before_adapt() [2/2]
template<class ELASTICITY_ELEMENT > void ElasticAnnulusProblem< ELASTICITY_ELEMENT >::actions_before_adapt () virtual
Actions before adapt: Wipe the mesh of traction elements.
Reimplemented from oomph::Problem.
actions_before_newton_solve() [1/2]
template<class ELASTICITY_ELEMENT > void ElasticAnnulusProblem< ELASTICITY_ELEMENT >::actions_before_newton_solve () inline virtual
Update function (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [2/2]
template<class ELASTICITY_ELEMENT > void ElasticAnnulusProblem< ELASTICITY_ELEMENT >::actions_before_newton_solve () inline virtual
Update function (empty)
Reimplemented from oomph::Problem.
 {}
complete_problem_setup() [1/2]
template<class ELASTICITY_ELEMENT > void ElasticAnnulusProblem< ELASTICITY_ELEMENT >::complete_problem_setup private
Helper function to complete problem setup.
Complete problem setup.
Upcast from PMLElement to time harmonic linear elasticity bulk element
Boundaries with id 0 and 1 represent the interior boundary and these are the only ones that need to be processed, hence the loop below only considers nodes on these two boundaries.
 {
 #ifdef ADAPTIVE
  // Min element size allowed during adaptation
  if (!CommandLineArgs::command_line_flag_has_been_set("--validation"))
   {
    Solid_mesh_pt->min_element_size()=1.0e-5;
   }
 #endif
  //Assign the physical properties to the elements
  //----------------------------------------------
  unsigned nel=this->mesh_pt()->nelement();
  for (unsigned e=0;e<nel;e++)
   {
    PMLTimeHarmonicLinearElasticityEquations<2> *el_pt =
     dynamic_cast<PMLTimeHarmonicLinearElasticityEquations<2>*>
     (mesh_pt()->element_pt(e));
    // Set the constitutive law
    el_pt->elasticity_tensor_pt() = Global_Parameters::E_pt;
    // Square of non-dim frequency
    el_pt->omega_sq_pt()= &Global_Parameters::Omega_sq;
   } // end_of_assignment
  for(unsigned b=0;b<2;b++)
   {
    unsigned n_node = Solid_mesh_pt->nboundary_node(b);
    for (unsigned n=0;n<n_node;n++)
     {
        Node* nod_pt=Solid_mesh_pt->boundary_node_pt(b,n);
        Vector<double> x_node(2);
        x_node[0]=nod_pt->x(0);
        x_node[1]=nod_pt->x(1);
        Vector<double> u_exact(4);
        Global_Parameters::exact_u(x_node,u_exact);
        for (unsigned k=0;k<4;k++)
         {
          nod_pt->pin(k);
          nod_pt->set_value(k,u_exact[k]);
         }
     }
   }
 } // end_of_complete_setup
References b, oomph::CommandLineArgs::command_line_flag_has_been_set(), e(), Global_Parameters::E_pt, oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::elasticity_tensor_pt(), Global_Parameters::exact_u(), k, n, Global_Parameters::Omega_sq, oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::omega_sq_pt(), oomph::Data::pin(), oomph::Data::set_value(), and oomph::Node::x().
complete_problem_setup() [2/2]
template<class ELASTICITY_ELEMENT > void ElasticAnnulusProblem< ELASTICITY_ELEMENT >::complete_problem_setup () private
Helper function to complete problem setup.
create_pml_meshes() [1/2]
template<class ELASTICITY_ELEMENT > void ElasticAnnulusProblem< ELASTICITY_ELEMENT >::create_pml_meshes
Create PML meshes.
Create PML meshes and add them to the problem's sub-meshes.
 {
  // Bulk mesh left boundary id
  unsigned int left_boundary_id = 2;
  // Bulk mesh top boundary id
  unsigned int top_boundary_id = 3;
  // Bulk mesh right boundary id
  unsigned int right_boundary_id = 4;
  // Bulk mesh bottom boundary id
  unsigned int bottom_boundary_id = 5;
  // Build the PML meshes based on the new adapted triangular mesh
  PML_right_mesh_pt =
   TwoDimensionalPMLHelper::create_right_pml_mesh
   <PMLLayerElement<ELASTICITY_ELEMENT> >
   (Solid_mesh_pt, right_boundary_id,
   Global_Parameters::N_x_right_pml,
   Global_Parameters::Width_x_right_pml);
  PML_top_mesh_pt   =
   TwoDimensionalPMLHelper::create_top_pml_mesh
   <PMLLayerElement<ELASTICITY_ELEMENT> >
   (Solid_mesh_pt, top_boundary_id,
    Global_Parameters::N_y_top_pml,
    Global_Parameters::Width_y_top_pml);
  PML_left_mesh_pt  =
   TwoDimensionalPMLHelper::create_left_pml_mesh
   <PMLLayerElement<ELASTICITY_ELEMENT> >
   (Solid_mesh_pt, left_boundary_id,
    Global_Parameters::N_x_left_pml,
    Global_Parameters::Width_x_left_pml);
  PML_bottom_mesh_pt=
   TwoDimensionalPMLHelper::create_bottom_pml_mesh
   <PMLLayerElement<ELASTICITY_ELEMENT> >
   (Solid_mesh_pt, bottom_boundary_id,
    Global_Parameters::N_y_bottom_pml,
    Global_Parameters::Width_y_bottom_pml);
  // Add submeshes to the global mesh
  add_sub_mesh(PML_right_mesh_pt);
  add_sub_mesh(PML_top_mesh_pt);
  add_sub_mesh(PML_left_mesh_pt);
  add_sub_mesh(PML_bottom_mesh_pt);
 // Rebuild corner PML meshes
  PML_top_right_mesh_pt    =
   TwoDimensionalPMLHelper::create_top_right_pml_mesh
   <PMLLayerElement<ELASTICITY_ELEMENT> >
   (PML_right_mesh_pt, PML_top_mesh_pt,
    Solid_mesh_pt, right_boundary_id);
  PML_bottom_right_mesh_pt =
   TwoDimensionalPMLHelper::create_bottom_right_pml_mesh
   <PMLLayerElement<ELASTICITY_ELEMENT> >
   (PML_right_mesh_pt,PML_bottom_mesh_pt,
    Solid_mesh_pt, right_boundary_id);
  PML_top_left_mesh_pt     =
   TwoDimensionalPMLHelper::create_top_left_pml_mesh
   <PMLLayerElement<ELASTICITY_ELEMENT> >
   (PML_left_mesh_pt, PML_top_mesh_pt,
    Solid_mesh_pt, left_boundary_id);
  PML_bottom_left_mesh_pt  =
   TwoDimensionalPMLHelper::create_bottom_left_pml_mesh
   <PMLLayerElement<ELASTICITY_ELEMENT> >
   (PML_left_mesh_pt, PML_bottom_mesh_pt,
    Solid_mesh_pt, left_boundary_id);
  // Add submeshes to the global mesh
  add_sub_mesh(PML_top_right_mesh_pt);
  add_sub_mesh(PML_bottom_right_mesh_pt);
  add_sub_mesh(PML_top_left_mesh_pt);
  add_sub_mesh(PML_bottom_left_mesh_pt);
 } // end of create_pml_meshes
References oomph::TwoDimensionalPMLHelper::create_bottom_left_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_bottom_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_bottom_right_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_left_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_right_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_top_left_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_top_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_top_right_pml_mesh(), Global_Parameters::N_x_left_pml, Global_Parameters::N_x_right_pml, Global_Parameters::N_y_bottom_pml, Global_Parameters::N_y_top_pml, Global_Parameters::Width_x_left_pml, Global_Parameters::Width_x_right_pml, Global_Parameters::Width_y_bottom_pml, and Global_Parameters::Width_y_top_pml.
create_pml_meshes() [2/2]
template<class ELASTICITY_ELEMENT > void ElasticAnnulusProblem< ELASTICITY_ELEMENT >::create_pml_meshes ()
Create PML meshes.
doc_solution() [1/2]
template<class ELASTICITY_ELEMENT > void ElasticAnnulusProblem< ELASTICITY_ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
 {
  ofstream some_file;
  char filename[100];
  // Number of plot points
  unsigned n_plot=5;
  // Output displacement field
  //--------------------------
  sprintf(filename,"%s/soln_bulk%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  Solid_mesh_pt->output(some_file,n_plot);
  some_file.close();
  sprintf(filename,"%s/soln_pml_right%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  PML_right_mesh_pt->output(some_file,n_plot);
  some_file.close();
  sprintf(filename,"%s/soln_pml_top%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  PML_top_mesh_pt->output(some_file,n_plot);
  some_file.close();
  sprintf(filename,"%s/soln_pml_left%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  PML_left_mesh_pt->output(some_file,n_plot);
  some_file.close();
  sprintf(filename,"%s/soln_pml_bottom%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  PML_bottom_mesh_pt->output(some_file,n_plot);
  some_file.close();
  sprintf(filename,"%s/soln_pml_top_right%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  PML_top_right_mesh_pt->output(some_file,n_plot);
  some_file.close();
  sprintf(filename,"%s/soln_pml_top_left%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  PML_top_left_mesh_pt->output(some_file,n_plot);
  some_file.close();
  sprintf(filename,"%s/soln_pml_bottom_right%i.dat",
          Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  PML_bottom_right_mesh_pt->output(some_file,n_plot);
  some_file.close();
  sprintf(filename,"%s/soln_pml_bottom_left%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  PML_bottom_left_mesh_pt->output(some_file,n_plot);
  some_file.close();
   // Output exact solution
  //----------------------
  sprintf(filename,"%s/exact_soln%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  Solid_mesh_pt->output_fct(some_file,n_plot,Global_Parameters::exact_u);
  some_file.close();
  // Doc error and return of the square of the L2 error
  //---------------------------------------------------
  double error,norm;
  sprintf(filename,"%s/error_and_norm%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  Solid_mesh_pt->compute_error(some_file,Global_Parameters::exact_u,
                           error,norm);
  some_file.open(filename);
  some_file << sqrt(error) << std::endl;
  some_file << sqrt(norm) << std::endl;
  some_file.close();
  // Doc L2 error and norm of solution
  cout << "\nNorm of error   : " << sqrt(error) << endl;
  cout << "Norm of exact solution: "   << sqrt(norm)  << endl;
  // Output runtime (wall clock time) in s in a file
  sprintf(filename,"%s/wall_clock_time%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  some_file << Global_Parameters::T_end-Global_Parameters::T_start << std::endl;
  some_file.close();
  // Output number of degrees of freedom in a file
  sprintf(filename,"%s/ndof%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  some_file << this->ndof() << std::endl;
  some_file.close();
  // Output norm of solution (to allow validation of solution even
  // if triangle generates a slightly different mesh)
  sprintf(filename,"%s/elast_soln_norm%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  double norm_soln=0.0;
  this->mesh_pt()->compute_norm(norm_soln);
  some_file << sqrt(norm_soln) << std::endl;
  cout << "Norm of computed solution: "   << sqrt(norm_soln)  << endl;
  // Increment label for output files
  Doc_info.number()++;
 } //end doc
References oomph::DocInfo::directory(), GlobalParameters::Doc_info, calibrate::error, Global_Parameters::exact_u(), MergeRestartFiles::filename, oomph::DocInfo::number(), sqrt(), Global_Parameters::T_end, and Global_Parameters::T_start.
doc_solution() [2/2]
template<class ELASTICITY_ELEMENT > void ElasticAnnulusProblem< ELASTICITY_ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Member Data Documentation
Doc_info
template<class ELASTICITY_ELEMENT > DocInfo ElasticAnnulusProblem< ELASTICITY_ELEMENT >::Doc_info private
DocInfo object for output.
Lower_inner_boundary_id
template<class ELASTICITY_ELEMENT > unsigned ElasticAnnulusProblem< ELASTICITY_ELEMENT >::Lower_inner_boundary_id private
Boundary ID of lower inner boundary.
Lower_outer_boundary_id
template<class ELASTICITY_ELEMENT > unsigned ElasticAnnulusProblem< ELASTICITY_ELEMENT >::Lower_outer_boundary_id private
Boundary ID of lower outer boundary.
PML_bottom_left_mesh_pt
template<class ELASTICITY_ELEMENT > Mesh * ElasticAnnulusProblem< ELASTICITY_ELEMENT >::PML_bottom_left_mesh_pt private
Pointer to the bottom left corner PML mesh.
PML_bottom_mesh_pt
template<class ELASTICITY_ELEMENT > Mesh * ElasticAnnulusProblem< ELASTICITY_ELEMENT >::PML_bottom_mesh_pt private
Pointer to the bottom PML mesh.
PML_bottom_right_mesh_pt
template<class ELASTICITY_ELEMENT > Mesh * ElasticAnnulusProblem< ELASTICITY_ELEMENT >::PML_bottom_right_mesh_pt private
Pointer to the bottom right corner PML mesh.
PML_left_mesh_pt
template<class ELASTICITY_ELEMENT > Mesh * ElasticAnnulusProblem< ELASTICITY_ELEMENT >::PML_left_mesh_pt private
Pointer to the left PML mesh.
PML_right_mesh_pt
template<class ELASTICITY_ELEMENT > Mesh * ElasticAnnulusProblem< ELASTICITY_ELEMENT >::PML_right_mesh_pt private
Pointer to the right PML mesh.
PML_top_left_mesh_pt
template<class ELASTICITY_ELEMENT > Mesh * ElasticAnnulusProblem< ELASTICITY_ELEMENT >::PML_top_left_mesh_pt private
Pointer to the top left corner PML mesh.
PML_top_mesh_pt
template<class ELASTICITY_ELEMENT > Mesh * ElasticAnnulusProblem< ELASTICITY_ELEMENT >::PML_top_mesh_pt private
Pointer to the top PML mesh.
PML_top_right_mesh_pt
template<class ELASTICITY_ELEMENT > Mesh * ElasticAnnulusProblem< ELASTICITY_ELEMENT >::PML_top_right_mesh_pt private
Pointer to the top right corner PML mesh.
Solid_mesh_pt [1/2]
template<class ELASTICITY_ELEMENT > RefineableTriangleMesh<ELASTICITY_ELEMENT>* ElasticAnnulusProblem< ELASTICITY_ELEMENT >::Solid_mesh_pt private
Pointer to refineable solid mesh.
Solid_mesh_pt [2/2]
template<class ELASTICITY_ELEMENT > RectangularQuadMesh<ELASTICITY_ELEMENT>* ElasticAnnulusProblem< ELASTICITY_ELEMENT >::Solid_mesh_pt private
Pointer to solid mesh.
Upper_inner_boundary_id
template<class ELASTICITY_ELEMENT > unsigned ElasticAnnulusProblem< ELASTICITY_ELEMENT >::Upper_inner_boundary_id private
Boundary ID of upper inner boundary.
Upper_outer_boundary_id
template<class ELASTICITY_ELEMENT > unsigned ElasticAnnulusProblem< ELASTICITY_ELEMENT >::Upper_outer_boundary_id private
Boundary ID of upper outer boundary.
The documentation for this class was generated from the following files:
time_harmonic_elasticity_driver.cc
time_harmonic_elasticity_driver_source.cc