MercuryDPM: Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > Class Template Reference
Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > Class Template Reference
The fixed sized version of the tensor class.
#include <TensorFixedSize.h>
Public Types
enum {
IsAligned = bool(EIGEN_MAX_ALIGN_BYTES > 0) , PacketAccess = (internal::packet_traits<Scalar>::size > 1) , BlockAccess = false , PreferBlockAccess = false ,
CoordAccess = true , RawAccess = true
}
typedef TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > Self
typedef TensorBase< TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > Base
typedef Eigen::internal::nested< Self >::type Nested
typedef internal::traits< Self >::StorageKind StorageKind
typedef internal::traits< Self >::Index Index
typedef Scalar_ Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef Base::CoeffReturnType CoeffReturnType
typedef internal::TensorBlockNotImplemented TensorBlock
typedef Dimensions_ Dimensions
Public Types inherited from Eigen::TensorBase< TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > >
typedef TensorBase< TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >, ReadOnlyAccessors > Base
typedef internal::traits< TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > DerivedTraits
typedef DerivedTraits::Scalar Scalar
typedef DerivedTraits::Index Index
typedef Scalar CoeffReturnType
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rank () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index dimension (std::size_t n) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions dimensions () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index size () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar * data ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar * data () const
Self & base ()
const Self & base () const
template<typename... IndexTypes>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & coeff (Index firstIndex, IndexTypes... otherIndices) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & coeff (const array< Index, NumIndices > &indices) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & coeff () const
template<typename... IndexTypes>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index firstIndex, IndexTypes... otherIndices)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (const array< Index, NumIndices > &indices)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef ()
template<typename... IndexTypes>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & operator() (Index firstIndex, IndexTypes... otherIndices) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & operator() (const array< Index, NumIndices > &indices) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & operator() (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & operator() () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & operator[] (Index index) const
template<typename... IndexTypes>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & operator() (Index firstIndex, IndexTypes... otherIndices)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & operator() (const array< Index, NumIndices > &indices)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & operator() (Index index)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & operator() ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & operator[] (Index index)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorFixedSize ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorFixedSize (const Self &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorFixedSize (Self &&other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorFixedSize (const TensorBase< OtherDerived, ReadOnlyAccessors > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorFixedSize (const TensorBase< OtherDerived, WriteAccessors > &other)
Public Member Functions inherited from Eigen::TensorBase< TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > & setZero ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > & setConstant (const Scalar &val)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > & setRandom ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > & setRandom ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > & setValues (const typename internal::Initializer< TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >, NumDimensions >::InitList &vals)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > & operator+= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > & operator-= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > & operator*= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > & operator/= (const OtherDerived &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorLayoutSwapOp< const TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > swap_layout () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorLayoutSwapOp< TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > swap_layout ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorConcatenationOp< const Axis, const TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >, const OtherDerived > concatenate (const OtherDerived &other, const Axis &axis) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorConcatenationOp< const Axis, TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >, OtherDerived > concatenate (const OtherDerived &other, const Axis &axis)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReshapingOp< const NewDimensions, const TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > reshape (const NewDimensions &newDimensions) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorReshapingOp< const NewDimensions, TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > reshape (const NewDimensions &newDimensions)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorSlicingOp< const StartIndices, const Sizes, const TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > slice (const StartIndices &startIndices, const Sizes &sizes) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorSlicingOp< const StartIndices, const Sizes, TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > slice (const StartIndices &startIndices, const Sizes &sizes)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorStridingSlicingOp< const StartIndices, const StopIndices, const Strides, const TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > stridedSlice (const StartIndices &startIndices, const StopIndices &stopIndices, const Strides &strides) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingSlicingOp< const StartIndices, const StopIndices, const Strides, TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > stridedSlice (const StartIndices &startIndices, const StopIndices &stopIndices, const Strides &strides)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorChippingOp< DimId, const TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > chip (const Index offset) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorChippingOp< DimId, TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > chip (const Index offset)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorChippingOp< Dynamic, const TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > chip (const Index offset, const Index dim) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorChippingOp< Dynamic, TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > chip (const Index offset, const Index dim)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReverseOp< const ReverseDimensions, const TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > reverse (const ReverseDimensions &rev) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorReverseOp< const ReverseDimensions, TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > reverse (const ReverseDimensions &rev)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorRollOp< const Rolls, const TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > roll (const Rolls &roll) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorRollOp< const Rolls, TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > roll (const Rolls &roll)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorShufflingOp< const Shuffle, const TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > shuffle (const Shuffle &shfl) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorShufflingOp< const Shuffle, TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > shuffle (const Shuffle &shfl)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorStridingOp< const Strides, const TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > stride (const Strides &strides) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorStridingOp< const Strides, TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > > stride (const Strides &strides)
TensorDevice< TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >, DeviceType > device (const DeviceType &dev)
TensorAsyncDevice< TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >, DeviceType, DoneCallback > device (const DeviceType &dev, DoneCallback done)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > & derived ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > & derived () const
Static Public Attributes
static constexpr int Options = Options_
static constexpr int Layout = Options_ & RowMajor ? RowMajor : ColMajor
static constexpr std::size_t NumIndices = Dimensions::count
Static Public Attributes inherited from Eigen::TensorBase< TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > >
static constexpr int NumDimensions
Protected Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool checkIndexRange (const array< Index, NumIndices > &) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index linearizedIndex (const array< Index, NumIndices > &indices) const
Protected Member Functions inherited from Eigen::TensorBase< TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType > & operator= (const OtherDerived &other)
Protected Attributes
TensorStorage< Scalar, Dimensions, Options > m_storage
Detailed Description
template<typename Scalar_, typename Dimensions_, int Options_, typename IndexType>
class Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >
The fixed sized version of the tensor class.
The fixed sized equivalent of Eigen::Tensor<float, 3> t(3, 5, 7); is Eigen::TensorFixedSize<float, Sizes<3,5,7>> t;
Member Typedef Documentation
Base
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > typedef TensorBase<TensorFixedSize<Scalar_, Dimensions_, Options_, IndexType> > Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::Base
CoeffReturnType
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > typedef Base::CoeffReturnType Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::CoeffReturnType
Dimensions
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > typedef Dimensions_ Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::Dimensions
Index
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > typedef internal::traits<Self>::Index Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::Index
Nested
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > typedef Eigen::internal::nested<Self>::type Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::Nested
RealScalar
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > typedef NumTraits<Scalar>::Real Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::RealScalar
Scalar
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > typedef Scalar_ Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::Scalar
Self
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > typedef TensorFixedSize<Scalar_, Dimensions_, Options_, IndexType> Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::Self
StorageKind
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > typedef internal::traits<Self>::StorageKind Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::StorageKind
TensorBlock
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > typedef internal::TensorBlockNotImplemented Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::TensorBlock
Member Enumeration Documentation
anonymous enum
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = bool(EIGEN_MAX_ALIGN_BYTES > 0),
     PacketAccess = (internal::packet_traits<Scalar>::size > 1),
     BlockAccess = false,
     PreferBlockAccess = false,
     CoordAccess = true,
     RawAccess = true
   };
Constructor & Destructor Documentation
TensorFixedSize() [1/5]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::TensorFixedSize () inline
 : m_storage() {}
TensorFixedSize() [2/5]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::TensorFixedSize (const Self & other) inline
 : Base(other), m_storage(other.m_storage) {}
TensorFixedSize() [3/5]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::TensorFixedSize (Self && other) inline
 : m_storage(other.m_storage) {}
TensorFixedSize() [4/5]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::TensorFixedSize (const TensorBase< OtherDerived, ReadOnlyAccessors > & other) inline
{
     typedef TensorAssignOp<TensorFixedSize, const OtherDerived> Assign;
     Assign assign(*this, other.derived());
     internal::TensorExecutor<const Assign, DefaultDevice>::run(assign, DefaultDevice());
   }
References Eigen::TensorBase< Derived, AccessLevel >::derived(), and Eigen::internal::TensorExecutor< Expression, Device, Vectorizable, Tiling >::run().
TensorFixedSize() [5/5]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::TensorFixedSize (const TensorBase< OtherDerived, WriteAccessors > & other) inline
{
     typedef TensorAssignOp<TensorFixedSize, const OtherDerived> Assign;
     Assign assign(*this, other.derived());
     internal::TensorExecutor<const Assign, DefaultDevice>::run(assign, DefaultDevice());
   }
References Eigen::TensorBase< Derived, AccessLevel >::derived(), and Eigen::internal::TensorExecutor< Expression, Device, Vectorizable, Tiling >::run().
Member Function Documentation
base() [1/2]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > Self& Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::base () inline
 { return *this; }
base() [2/2]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > const Self& Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::base () const inline
 { return *this; }
checkIndexRange()
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::checkIndexRange (const array< Index, NumIndices > &) const inline protected
{
     using internal::array_apply_and_reduce;
     using internal::array_zip_and_reduce;
     using internal::greater_equal_zero_op;
     using internal::lesser_op;
     using internal::logical_and_op;
     return true;
     // check whether the indices are all >= 0
     /*       array_apply_and_reduce<logical_and_op, greater_equal_zero_op>(indices) &&
   // check whether the indices fit in the dimensions
   array_zip_and_reduce<logical_and_op, lesser_op>(indices, m_storage.dimensions());*/
   }
References Eigen::internal::array_apply_and_reduce(), and Eigen::internal::array_zip_and_reduce().
Referenced by Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeff(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeffRef(), and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::operator()().
coeff() [1/4]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar& Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeff () const inline
{
     EIGEN_STATIC_ASSERT(NumIndices == 0, YOU_MADE_A_PROGRAMMING_MISTAKE);
     return m_storage.data()[0];
   }
References Eigen::TensorStorage< T, FixedDimensions, Options_ >::data(), EIGEN_STATIC_ASSERT, Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::m_storage, and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::NumIndices.
Referenced by Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeff(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::operator()(), and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::operator[]().
coeff() [2/4]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar& Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeff (const array< Index, NumIndices > & indices) const inline
{
     eigen_internal_assert(checkIndexRange(indices));
     return m_storage.data()[linearizedIndex(indices)];
   }
References Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::checkIndexRange(), Eigen::TensorStorage< T, FixedDimensions, Options_ >::data(), eigen_internal_assert, Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::linearizedIndex(), and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::m_storage.
coeff() [3/4]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > template<typename... IndexTypes> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar& Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeff (Index firstIndex, IndexTypes... otherIndices) const inline
{
     // The number of indices used to access a tensor coefficient must be equal to the rank of the tensor.
     EIGEN_STATIC_ASSERT(sizeof...(otherIndices) + 1 == NumIndices, YOU_MADE_A_PROGRAMMING_MISTAKE)
     return coeff(array<Index, NumIndices>{{firstIndex, otherIndices...}});
   }
References Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeff(), EIGEN_STATIC_ASSERT, and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::NumIndices.
coeff() [4/4]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar& Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeff (Index index) const inline
{
     eigen_internal_assert(index >= 0 && index < size());
     return m_storage.data()[index];
   }
References Eigen::TensorStorage< T, FixedDimensions, Options_ >::data(), eigen_internal_assert, Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::m_storage, and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::size().
coeffRef() [1/4]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeffRef () inline
{
     EIGEN_STATIC_ASSERT(NumIndices == 0, YOU_MADE_A_PROGRAMMING_MISTAKE);
     return m_storage.data()[0];
   }
References Eigen::TensorStorage< T, FixedDimensions, Options_ >::data(), EIGEN_STATIC_ASSERT, Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::m_storage, and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::NumIndices.
Referenced by Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeffRef(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::operator()(), and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::operator[]().
coeffRef() [2/4]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeffRef (const array< Index, NumIndices > & indices) inline
{
     eigen_internal_assert(checkIndexRange(indices));
     return m_storage.data()[linearizedIndex(indices)];
   }
References Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::checkIndexRange(), Eigen::TensorStorage< T, FixedDimensions, Options_ >::data(), eigen_internal_assert, Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::linearizedIndex(), and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::m_storage.
coeffRef() [3/4]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > template<typename... IndexTypes> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeffRef (Index firstIndex, IndexTypes... otherIndices) inline
{
     // The number of indices used to access a tensor coefficient must be equal to the rank of the tensor.
     EIGEN_STATIC_ASSERT(sizeof...(otherIndices) + 1 == NumIndices, YOU_MADE_A_PROGRAMMING_MISTAKE)
     return coeffRef(array<Index, NumIndices>{{firstIndex, otherIndices...}});
   }
References Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeffRef(), EIGEN_STATIC_ASSERT, and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::NumIndices.
coeffRef() [4/4]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeffRef (Index index) inline
{
     eigen_internal_assert(index >= 0 && index < size());
     return m_storage.data()[index];
   }
References Eigen::TensorStorage< T, FixedDimensions, Options_ >::data(), eigen_internal_assert, Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::m_storage, and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::size().
data() [1/2]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar* Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::data () inline
 { return m_storage.data(); }
References Eigen::TensorStorage< T, FixedDimensions, Options_ >::data(), and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::m_storage.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), test_0d(), test_fixed_size_broadcasting(), test_full_reductions_custom_sycl(), test_last_reductions_mean_sycl(), test_last_reductions_sum_sycl(), test_same_type(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
data() [2/2]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar* Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::data () const inline
 { return m_storage.data(); }
References Eigen::TensorStorage< T, FixedDimensions, Options_ >::data(), and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::m_storage.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimension()
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::dimension (std::size_t n) const inline
 { return m_storage.dimensions()[n]; }
References Eigen::TensorStorage< T, FixedDimensions, Options_ >::dimensions(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::m_storage, and n.
dimensions()
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::dimensions () const inline
 { return m_storage.dimensions(); }
References Eigen::TensorStorage< T, FixedDimensions, Options_ >::dimensions(), and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::m_storage.
Referenced by test_0d(), test_full_reductions_custom_sycl(), test_last_reductions_mean_sycl(), and test_last_reductions_sum_sycl().
linearizedIndex()
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::linearizedIndex (const array< Index, NumIndices > & indices) const inline protected
{
     if (Options & RowMajor) {
       return m_storage.dimensions().IndexOfRowMajor(indices);
     } else {
       return m_storage.dimensions().IndexOfColMajor(indices);
     }
   }
References Eigen::TensorStorage< T, FixedDimensions, Options_ >::dimensions(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::m_storage, Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::Options, and Eigen::RowMajor.
Referenced by Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeff(), and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeffRef().
operator()() [1/8]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::operator() () inline
{
     EIGEN_STATIC_ASSERT(NumIndices == 0, YOU_MADE_A_PROGRAMMING_MISTAKE);
     return coeffRef();
   }
References Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeffRef(), EIGEN_STATIC_ASSERT, and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::NumIndices.
operator()() [2/8]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar& Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::operator() () const inline
{
     EIGEN_STATIC_ASSERT(NumIndices == 0, YOU_MADE_A_PROGRAMMING_MISTAKE);
     return coeff();
   }
References Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeff(), EIGEN_STATIC_ASSERT, and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::NumIndices.
Referenced by Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::operator()().
operator()() [3/8]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::operator() (const array< Index, NumIndices > & indices) inline
{
     eigen_assert(checkIndexRange(indices));
     return coeffRef(indices);
   }
References Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::checkIndexRange(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeffRef(), and eigen_assert.
operator()() [4/8]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar& Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::operator() (const array< Index, NumIndices > & indices) const inline
{
     eigen_assert(checkIndexRange(indices));
     return coeff(indices);
   }
References Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::checkIndexRange(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeff(), and eigen_assert.
operator()() [5/8]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > template<typename... IndexTypes> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::operator() (Index firstIndex, IndexTypes... otherIndices) inline
{
     // The number of indices used to access a tensor coefficient must be equal to the rank of the tensor.
     EIGEN_STATIC_ASSERT(sizeof...(otherIndices) + 1 == NumIndices, YOU_MADE_A_PROGRAMMING_MISTAKE)
     return operator()(array<Index, NumIndices>{{firstIndex, otherIndices...}});
   }
References EIGEN_STATIC_ASSERT, Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::NumIndices, and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::operator()().
operator()() [6/8]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > template<typename... IndexTypes> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar& Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::operator() (Index firstIndex, IndexTypes... otherIndices) const inline
{
     // The number of indices used to access a tensor coefficient must be equal to the rank of the tensor.
     EIGEN_STATIC_ASSERT(sizeof...(otherIndices) + 1 == NumIndices, YOU_MADE_A_PROGRAMMING_MISTAKE)
     return this->operator()(array<Index, NumIndices>{{firstIndex, otherIndices...}});
   }
References EIGEN_STATIC_ASSERT, Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::NumIndices, and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::operator()().
operator()() [7/8]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::operator() (Index index) inline
{
     eigen_assert(index >= 0 && index < size());
     return coeffRef(index);
   }
References Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeffRef(), eigen_assert, and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::size().
operator()() [8/8]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar& Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::operator() (Index index) const inline
{
     eigen_internal_assert(index >= 0 && index < size());
     return coeff(index);
   }
References Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeff(), eigen_internal_assert, and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::size().
operator[]() [1/2]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::operator[] (Index index) inline
{
     // The bracket operator is only for vectors, use the parenthesis operator instead
     EIGEN_STATIC_ASSERT(NumIndices == 1, YOU_MADE_A_PROGRAMMING_MISTAKE)
     return coeffRef(index);
   }
References Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeffRef(), EIGEN_STATIC_ASSERT, and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::NumIndices.
operator[]() [2/2]
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar& Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::operator[] (Index index) const inline
{
     // The bracket operator is only for vectors, use the parenthesis operator instead.
     EIGEN_STATIC_ASSERT(NumIndices == 1, YOU_MADE_A_PROGRAMMING_MISTAKE);
     return coeff(index);
   }
References Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeff(), EIGEN_STATIC_ASSERT, and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::NumIndices.
rank()
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::rank () const inline
 { return NumIndices; }
References Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::NumIndices.
Referenced by test_0d(), and test_1d().
size()
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::size () const inline
 { return m_storage.size(); }
References Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::m_storage, and Eigen::TensorStorage< T, FixedDimensions, Options_ >::size().
Referenced by Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeff(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeffRef(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::operator()(), test_0d(), test_1d(), test_2d(), and test_3d().
Member Data Documentation
Layout
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > constexpr int Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::Layout = Options_ & RowMajor ? RowMajor : ColMajor static constexpr
m_storage
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > TensorStorage<Scalar, Dimensions, Options> Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::m_storage protected
Referenced by Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeff(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeffRef(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::data(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::dimension(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::dimensions(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::linearizedIndex(), and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::size().
NumIndices
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > constexpr std::size_t Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::NumIndices = Dimensions::count static constexpr
Referenced by Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeff(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::coeffRef(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::operator()(), Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::operator[](), and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::rank().
Options
template<typename Scalar_ , typename Dimensions_ , int Options_, typename IndexType > constexpr int Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::Options = Options_ static constexpr
Referenced by Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::linearizedIndex().
The documentation for this class was generated from the following file:
TensorFixedSize.h