MercuryDPM: oomph::ProjectionProblem< PROJECTABLE_ELEMENT > Class Template Reference
oomph::ProjectionProblem< PROJECTABLE_ELEMENT > Class Template Reference
#include <projection.h>
Public Member Functions
void enable_suppress_output_during_projection ()
Suppress all output during projection phases.
void disable_suppress_output_during_projection ()
Undo suppression of all output during projection phases.
bool use_iterative_solver_for_projection ()
void enable_use_iterative_solver_for_projection ()
Enables the use of an iterative solver for projection.
void disable_use_iterative_solver_for_projection ()
Disbales the use of an iterative solver for projection.
void project (Mesh *base_mesh_pt, const bool &dont_project_positions=false)
Project from base into the problem's own mesh.
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
virtual void actions_before_adapt ()
virtual void actions_after_adapt ()
Actions that are to be performed after a mesh adaptation.
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Private Member Functions
ProjectionProblem ()
~ProjectionProblem ()
void store_positions ()
void restore_positions ()
void pin_all ()
Pin all the field values and position unknowns (bit inefficient)
void unpin_all ()
Unpin all the field values and position unknowns (bit inefficient)
void unpin_dofs_of_coordinate (const unsigned &coord)
Helper function to unpin the values of coordinate coord.
void pin_dofs_of_coordinate (const unsigned &coord)
Helper function to unpin the values of coordinate coord.
void unpin_dofs_of_field (const unsigned &fld)
Helper function to unpin dofs of fld-th field.
void pin_dofs_of_field (const unsigned &fld)
Helper function to unpin dofs of fld-th field.
void set_time_level_for_projection (const unsigned &time_level)
Helper function to set time level for projection.
void set_coordinate_for_projection (const unsigned &i)
Set the coordinate for projection.
void set_lagrangian_coordinate_for_projection (const unsigned &i)
Set the Lagrangian coordinate for projection.
void set_current_field_for_projection (const unsigned &fld)
Set current field for projection.
Private Attributes
Vector< DenseMatrix< double > > Solid_backup
Backup for pin status of solid node's position Data.
bool Output_during_projection_suppressed
Flag to suppress output during projection.
bool Use_iterative_solver_for_projection
IterativeLinearSolver * Iterative_solver_projection_pt
Preconditioner * Preconditioner_projection_pt
Friends
template<class FRIEND_PROJECTABLE_ELEMENT >
class RefineableTriangleMesh
template<class FRIEND_PROJECTABLE_ELEMENT >
class RefineableTetgenMesh
template<class FRIEND_PROJECTABLE_ELEMENT >
class BackupMeshForProjection
template<class FRIEND_PROJECTABLE_ELEMENT >
class RefineableGmshTetMesh
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_solve ()
virtual void actions_after_newton_solve ()
virtual void actions_before_newton_convergence_check ()
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_before_implicit_timestep ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual void set_initial_condition ()
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class PROJECTABLE_ELEMENT>
class oomph::ProjectionProblem< PROJECTABLE_ELEMENT >
Projection problem. This is created during the adaptation of unstructured meshes and it is assumed that no boundary conditions have been set. If they have, they will be unset during the projection and must be reset afterwards.
Constructor & Destructor Documentation
ProjectionProblem()
template<class PROJECTABLE_ELEMENT > oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::ProjectionProblem () inline private
Default constructor (made this private so only the friend class can call the constructor)
     {
       // This is a linear problem so avoid checking the residual
       // after the solve
       Problem_is_nonlinear = false; // DO NOT CHANGE THIS -- EVER -- IN
                                     // SOLID MECHANICS PROBLEMS
       // By default suppress output during projection
       Output_during_projection_suppressed = true;
       // By default we use an iterative solver for projection
       Use_iterative_solver_for_projection = true;
       // Initialise the pointer to the solver and the preconditioner
       Iterative_solver_projection_pt = 0;
       Preconditioner_projection_pt = 0;
     }
References oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Iterative_solver_projection_pt, oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Output_during_projection_suppressed, oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Preconditioner_projection_pt, oomph::Problem::Problem_is_nonlinear, and oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Use_iterative_solver_for_projection.
~ProjectionProblem()
template<class PROJECTABLE_ELEMENT > oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::~ProjectionProblem () inline private
     {
       if (Iterative_solver_projection_pt != 0)
       {
         // Clean up memory
         delete Iterative_solver_projection_pt;
         Iterative_solver_projection_pt = 0;
       }
       if (Preconditioner_projection_pt != 0)
       {
         delete Preconditioner_projection_pt;
         Preconditioner_projection_pt = 0;
       }
     }
References oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Iterative_solver_projection_pt, and oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Preconditioner_projection_pt.
Member Function Documentation
disable_suppress_output_during_projection()
template<class PROJECTABLE_ELEMENT > void oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::disable_suppress_output_during_projection () inline
Undo suppression of all output during projection phases.
     {
       Output_during_projection_suppressed = false;
     }
References oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Output_during_projection_suppressed.
disable_use_iterative_solver_for_projection()
template<class PROJECTABLE_ELEMENT > void oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::disable_use_iterative_solver_for_projection () inline
Disbales the use of an iterative solver for projection.
     {
       Use_iterative_solver_for_projection = false;
     }
References oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Use_iterative_solver_for_projection.
enable_suppress_output_during_projection()
template<class PROJECTABLE_ELEMENT > void oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::enable_suppress_output_during_projection () inline
Suppress all output during projection phases.
     {
       Output_during_projection_suppressed = true;
     }
References oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Output_during_projection_suppressed.
enable_use_iterative_solver_for_projection()
template<class PROJECTABLE_ELEMENT > void oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::enable_use_iterative_solver_for_projection () inline
Enables the use of an iterative solver for projection.
     {
       Use_iterative_solver_for_projection = true;
     }
References oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Use_iterative_solver_for_projection.
pin_all()
template<class PROJECTABLE_ELEMENT > void oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::pin_all () inline private
Pin all the field values and position unknowns (bit inefficient)
Do we have a solid mesh?
     {
       // No need to do anything if there are no elements (in fact, we
       // probably never get here...)
       if (Problem::mesh_pt()->nelement() == 0) return;
       // Loop over all the elements
       const unsigned n_element = Problem::mesh_pt()->nelement();
       for (unsigned e = 0; e < n_element; ++e)
       {
         FiniteElement* el_pt = Problem::mesh_pt()->finite_element_pt(e);
         unsigned nint = el_pt->ninternal_data();
         for (unsigned j = 0; j < nint; j++)
         {
           Data* int_data_pt = el_pt->internal_data_pt(j);
           unsigned nval = int_data_pt->nvalue();
           for (unsigned i = 0; i < nval; i++)
           {
             int_data_pt->pin(i);
           }
         }
         unsigned nnod = el_pt->nnode();
         for (unsigned j = 0; j < nnod; j++)
         {
           Node* nod_pt = el_pt->node_pt(j);
           unsigned nval = nod_pt->nvalue();
           for (unsigned i = 0; i < nval; i++)
           {
             nod_pt->pin(i);
           }
         }
       }
       SolidFiniteElement* solid_el_pt =
         dynamic_cast<SolidFiniteElement*>(Problem::mesh_pt()->element_pt(0));
       if (solid_el_pt != 0)
       {
         // Find number of nodes
         const unsigned n_node = this->mesh_pt()->nnode();
         // If no nodes then return
         if (n_node == 0)
         {
           return;
         }
         // Read dimension and number of position values from the first node
         const unsigned n_dim = this->mesh_pt()->node_pt(0)->ndim();
         const unsigned n_position_type =
           this->mesh_pt()->node_pt(0)->nposition_type();
         // Loop over the nodes
         for (unsigned n = 0; n < n_node; n++)
         {
           SolidNode* solid_nod_pt =
             dynamic_cast<SolidNode*>(this->mesh_pt()->node_pt(n));
           for (unsigned i = 0; i < n_dim; i++)
           {
             for (unsigned k = 0; k < n_position_type; k++)
             {
               solid_nod_pt->pin_position(k, i);
             }
           }
         }
       }
     }
References e(), oomph::Mesh::element_pt(), oomph::Mesh::finite_element_pt(), i, oomph::GeneralisedElement::internal_data_pt(), j, k, oomph::Problem::mesh_pt(), n, oomph::Node::ndim(), oomph::Mesh::nelement(), oomph::GeneralisedElement::ninternal_data(), oomph::FiniteElement::nnode(), oomph::Mesh::nnode(), oomph::FiniteElement::node_pt(), oomph::Mesh::node_pt(), oomph::Node::nposition_type(), oomph::Data::nvalue(), oomph::Data::pin(), and oomph::SolidNode::pin_position().
Referenced by oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project().
pin_dofs_of_coordinate()
template<class PROJECTABLE_ELEMENT > void oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::pin_dofs_of_coordinate (const unsigned & coord) inline private
Helper function to unpin the values of coordinate coord.
     {
       // Loop over the nodes
       const unsigned n_node = Problem::mesh_pt()->nnode();
       // If there are no nodes return immediately
       if (n_node == 0)
       {
         return;
       }
       // Find the number of position values (should be the same for all nodes)
       const unsigned n_position_type =
         Problem::mesh_pt()->node_pt(0)->nposition_type();
       for (unsigned n = 0; n < n_node; ++n)
       {
         // Cache access to the Node as a solid node
         SolidNode* solid_nod_pt =
           static_cast<SolidNode*>(Problem::mesh_pt()->node_pt(n));
         // Unpin all position types associated with the given coordinate
         for (unsigned k = 0; k < n_position_type; ++k)
         {
           solid_nod_pt->pin_position(k, coord);
         }
       }
     }
References k, oomph::Problem::mesh_pt(), n, oomph::Mesh::nnode(), oomph::Mesh::node_pt(), oomph::Node::nposition_type(), and oomph::SolidNode::pin_position().
Referenced by oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project().
pin_dofs_of_field()
template<class PROJECTABLE_ELEMENT > void oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::pin_dofs_of_field (const unsigned & fld) inline private
Helper function to unpin dofs of fld-th field.
     {
       unsigned n_element = Problem::mesh_pt()->nelement();
       for (unsigned e = 0; e < n_element; e++)
       {
         PROJECTABLE_ELEMENT* new_el_pt =
           dynamic_cast<PROJECTABLE_ELEMENT*>(Problem::mesh_pt()->element_pt(e));
         Vector<std::pair<Data*, unsigned>> data =
           new_el_pt->data_values_of_field(fld);
         unsigned d_size = data.size();
         for (unsigned d = 0; d < d_size; d++)
         {
           data[d].first->pin(data[d].second);
         }
       }
     }
References data, e(), oomph::Mesh::element_pt(), oomph::Problem::mesh_pt(), and oomph::Mesh::nelement().
Referenced by oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project().
project()
template<class PROJECTABLE_ELEMENT > void oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project (Mesh * base_mesh_pt, const bool & dont_project_positions = false) inline
Project from base into the problem's own mesh.
Disable documentation of solve times
     {
       // Use an iterative solver?
       if (Use_iterative_solver_for_projection)
       {
         // If oomph-lib has Trilinos installed then use the CG version
         // from Trilinos, otherwise use oomph-lib's own CG implementation
 #ifdef OOMPH_HAS_TRILINOS
         // Check whether the problem is distributed?
         if (MPI_Helpers::mpi_has_been_initialised())
         {
           // Create a Trilinos Solver
           Iterative_solver_projection_pt = new TrilinosAztecOOSolver;
           // Select CG as the linear solver
           dynamic_cast<TrilinosAztecOOSolver*>(Iterative_solver_projection_pt)
             ->solver_type() = TrilinosAztecOOSolver::CG;
         }
         else
         {
           // Use CG to solve the projection problem
           Iterative_solver_projection_pt = new CG<CRDoubleMatrix>;
         }
         // Create the preconditioner
         Preconditioner_projection_pt = new MatrixBasedDiagPreconditioner();
         // Set the preconditioner for the solver
         Iterative_solver_projection_pt->preconditioner_pt() =
           Preconditioner_projection_pt;
         // Set CG as the linear solver
         Problem::linear_solver_pt() = Iterative_solver_projection_pt;
 #else
         // Check whether the problem is distributed?
         if (!(MPI_Helpers::mpi_has_been_initialised()))
         {
           // If we did not installed Trilinos and the problem is not
           // distributed then we can use a (serial) preconditioned
           // iterative solver, otherwise, if we did not installed Trilinos
           // but the problem is distributed then we cannot use a
           // preconditioned iterative solver. Matrix multiplication in a
           // distributed environment is only performed by Trilinos. We
           // then use a direct solver for the projection problem.
           // Use CG to solve the projection problem
           Iterative_solver_projection_pt = new CG<CRDoubleMatrix>;
           // Create the preconditioner
           Preconditioner_projection_pt = new MatrixBasedDiagPreconditioner();
           // Set the preconditioner for the solver
           Iterative_solver_projection_pt->preconditioner_pt() =
             Preconditioner_projection_pt;
           // Set CG as the linear solver
           Problem::linear_solver_pt() = Iterative_solver_projection_pt;
         }
         else
         {
           // Use a direct solver. Do nothing
         }
 #endif
       } // if (Use_iterative_solver_for_projection)
       // Backup verbosity in Newton solve status
       bool shut_up_in_newton_solve_backup = Shut_up_in_newton_solve;
       // Disable documentation of solve times
       bool backed_up_doc_time_enabled =
         linear_solver_pt()->is_doc_time_enabled();
       if (Output_during_projection_suppressed)
       {
         linear_solver_pt()->disable_doc_time();
       }
       // Display stats
       unsigned n_element = Problem::mesh_pt()->nelement();
       unsigned n_element1 = base_mesh_pt->nelement();
       unsigned n_node = Problem::mesh_pt()->nnode();
       unsigned n_node1 = base_mesh_pt->nnode();
       if (!Output_during_projection_suppressed)
       {
         oomph_info << "\n=============================\n";
         oomph_info << "Base mesh has " << n_element1 << " elements\n";
         oomph_info << "Target mesh has " << n_element << " elements\n";
         oomph_info << "Base mesh has " << n_node1 << " nodes\n";
         oomph_info << "Target mesh has " << n_node << " nodes\n";
         oomph_info << "=============================\n\n";
       }
       else
       {
         // Make Newton solver shut up too
         disable_info_in_newton_solve();
       }
       if (n_element == 0)
       {
         oomph_info << "Very odd -- no elements in target mesh; "
                    << " not doing anything in ProjectionProblem::project()\n";
         return;
       }
 #ifdef PARANOID
       unsigned nnod = Problem::mesh_pt()->nnode();
       if (nnod == 0)
       {
         std::ostringstream error_stream;
         error_stream
           << "Mesh has no nodes! Please populate the Node_pt vector\n"
           << "otherwise projection won't work!\n";
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // How many fields do we have to project?
       unsigned n_fields =
         dynamic_cast<PROJECTABLE_ELEMENT*>(Problem::mesh_pt()->element_pt(0))
           ->nfields_for_projection();
       // Spatial dimension of the problem
       unsigned n_dim = Problem::mesh_pt()->node_pt(0)->ndim();
       // Default number of history values
       unsigned n_history_values = 0;
       // Set things up for coordinate projection
       for (unsigned e = 0; e < n_element; e++)
       {
         PROJECTABLE_ELEMENT* el_pt =
           dynamic_cast<PROJECTABLE_ELEMENT*>(Problem::mesh_pt()->element_pt(e));
         // Switch to projection
         el_pt->enable_projection();
       }
       // Switch elements in base mesh to projection mode (required
       // to switch to use of Eulerian coordinates when identifying
       // corresponding points in the two meshes)
       for (unsigned e = 0; e < n_element1; e++)
       {
         PROJECTABLE_ELEMENT* el_pt =
           dynamic_cast<PROJECTABLE_ELEMENT*>(base_mesh_pt->element_pt(e));
         // Switch to projection
         el_pt->enable_projection();
       }
       // Set up multi domain interactions so we can locate the
       // values in the base mesh.
       // Note that it's important to switch elements to projection
       // mode first to ensure that matching is done based on Eulerian
       // rather than Lagrangian coordinates if pseudo-solid elements
       // are used.
       double t_start = TimingHelpers::timer();
       Multi_domain_functions::setup_multi_domain_interaction<
         PROJECTABLE_ELEMENT>(this, Problem::mesh_pt(), base_mesh_pt);
       if (!Output_during_projection_suppressed)
       {
         oomph_info
           << "CPU for setup of multi-domain interaction for projection: "
           << TimingHelpers::timer() - t_start << std::endl;
       }
       t_start = TimingHelpers::timer();
       // Let us first pin every degree of freedom
       // We shall unpin selected dofs for each different projection problem
       this->pin_all();
       if (!dont_project_positions)
       {
         //------------------Project coordinates first------------------------
         // If we have a solid element then we should also project Lagrangian
         // coordinates, but we can use the storage that MUST be provided for
         // the unknown positions for this.
         // If we can cast the first element of the mesh to a solid element,
         // then assume that we have solid elements
         if (dynamic_cast<SolidFiniteElement*>(
               Problem::mesh_pt()->element_pt(0)))
         {
           // Store current positions
           this->store_positions();
           // There are no history values for the Lagrangian coordinates
           // Set coordinate 0 for projection
           this->set_coordinate_for_projection(0);
           this->unpin_dofs_of_coordinate(0);
           // Loop over the Lagrangian coordinate
           const unsigned n_lagrangian =
             dynamic_cast<SolidNode*>(Problem::mesh_pt()->node_pt(0))
               ->nlagrangian();
           // Now loop over the lagrangian coordinates
           for (unsigned i = 0; i < n_lagrangian; ++i)
           {
             if (!Output_during_projection_suppressed)
             {
               oomph_info
                 << "\n\n=============================================\n";
               oomph_info << "Projecting values for Lagrangian coordinate " << i
                          << std::endl;
               oomph_info << "=============================================\n\n";
             }
             // Set the coordinate for projection
             this->set_lagrangian_coordinate_for_projection(i);
             // Assign equation number
             unsigned ndof_tmp = assign_eqn_numbers();
             if (!Output_during_projection_suppressed)
             {
               oomph_info << "Number of equations for projection of Lagrangian "
                             "coordinate "
                          << " : " << ndof_tmp << std::endl
                          << std::endl;
             }
             if (Problem_is_nonlinear)
             {
               std::ostringstream error_stream;
               error_stream
                 << "Solid mechanics problems will break if "
                    "Problem_is_nonlinear is\n"
                 << "set to true in the projection problem because we're using "
                    "the\n "
                 << "actual nodal positions to store the values of the "
                    "Lagrangian\n"
                 << "coords. There shouldn't be any need for \n"
                 << "Problem_is_nonlinear=true anyway, apart from debugging in "
                    "\n"
                 << "which case you now know why this case will break!\n";
               OomphLibWarning(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
             }
             // Projection and interpolation
             Problem::newton_solve();
             // Move values back into Lagrangian coordinate for all nodes
             unsigned n_node = Problem::mesh_pt()->nnode();
             for (unsigned n = 0; n < n_node; ++n)
             {
               // Cast it to a solid node
               SolidNode* solid_node_pt =
                 dynamic_cast<SolidNode*>(Problem::mesh_pt()->node_pt(n));
               // Now find number of types
               const unsigned n_position_type = solid_node_pt->nposition_type();
               // Find number of lagrangian types
               const unsigned n_lagrangian_type =
                 solid_node_pt->nlagrangian_type();
               // If these are not the same, throw an error
               if (n_position_type != n_lagrangian_type)
               {
                 std::ostringstream error_stream;
                 error_stream
                   << "The number of generalised position dofs "
                   << n_position_type
                   << "\n not the same as the number of generalised lagrangian "
                      "dofs "
                   << n_lagrangian_type << ".\n"
                   << "Projection cannot be done at the moment, sorry.\n";
                 throw OomphLibError(error_stream.str(),
                                     OOMPH_CURRENT_FUNCTION,
                                     OOMPH_EXCEPTION_LOCATION);
               }
               // Now transfer the information across
               // from the first coordinate which was used during the projection
               for (unsigned k = 0; k < n_position_type; ++k)
               {
                 solid_node_pt->xi_gen(k, i) = solid_node_pt->x_gen(k, 0);
                 // Reset real values so that the Jacobians are correctly
                 // computed next time around
                 solid_node_pt->x_gen(k, 0) = Solid_backup[n](k, 0);
               }
             }
           } // End of loop over lagrangian coordinates
           // Now repin the dofs
           this->pin_dofs_of_coordinate(0);
           // Now project the position histories
           // Check number of history values for coordinates
           n_history_values = dynamic_cast<PROJECTABLE_ELEMENT*>(
                                Problem::mesh_pt()->element_pt(0))
                                ->nhistory_values_for_coordinate_projection();
           // Projection the coordinates only if there are history values
           if (n_history_values > 1)
           {
             for (unsigned i = 0; i < n_dim; i++)
             {
               if (!Output_during_projection_suppressed)
               {
                 oomph_info
                   << "\n\n=============================================\n";
                 oomph_info << "Projecting history values for coordinate " << i
                            << std::endl;
                 oomph_info
                   << "=============================================\n\n";
               }
               // Set the coordinate for projection
               this->set_coordinate_for_projection(i);
               this->unpin_dofs_of_coordinate(i);
               // Loop over number of history values, beginning with the latest
               // one. Don't deal with current time.
               for (unsigned h_tim = n_history_values; h_tim > 1; h_tim--)
               {
                 unsigned time_level = h_tim - 1;
                 // Set time_level we are dealing with
                 this->set_time_level_for_projection(time_level);
                 // Assign equation number
                 unsigned ndof_tmp = assign_eqn_numbers();
                 if (!Output_during_projection_suppressed)
                 {
                   oomph_info
                     << "Number of equations for projection of coordinate " << i
                     << " at time level " << time_level << " : " << ndof_tmp
                     << std::endl
                     << std::endl;
                 }
                 // Projection and interpolation
                 Problem::newton_solve();
                 // Move values back into history value of coordinate
                 unsigned n_node = Problem::mesh_pt()->nnode();
                 for (unsigned n = 0; n < n_node; ++n)
                 {
                   // Cache the pointer to the node
                   Node* nod_pt = Problem::mesh_pt()->node_pt(n);
                   // Find the number of generalised dofs
                   const unsigned n_position_type = nod_pt->nposition_type();
                   // Now copy all back
                   for (unsigned k = 0; k < n_position_type; ++k)
                   {
                     nod_pt->x_gen(time_level, k, i) = nod_pt->x_gen(0, k, i);
                     // Reset real values so that the Jacobians are computed
                     // correctly next time around
                     nod_pt->x_gen(0, k, i) = Solid_backup[n](k, i);
                   }
                 }
               }
               // Repin the positions
               this->pin_dofs_of_coordinate(i);
             }
           } // End of history value projection
         } // End of SolidElement case
         // Now for non solid elements, we are going to hijack the
         // first value as storage to be used for the projection of the history
         // values
         else
         {
           // Prepare for projection in value 0
           this->set_current_field_for_projection(0);
           this->unpin_dofs_of_field(0);
 #ifdef PARANOID
           // The machinery used below  assumes that field 0 can actually
           // hold the coordinates i.e. that the field is interpolated
           // isoparametrically! The method will fail if there are no values
           // stored at the nodes.  Currently there are no examples of that --
           // the problem would only arise for elements that have all their
           // fields represented by internal data. Will fix this if/when such a
           // case arises...
           unsigned n_element = Problem::mesh_pt()->nelement();
           for (unsigned e = 0; e < n_element; e++)
           {
             FiniteElement* el_pt = Problem::mesh_pt()->finite_element_pt(e);
             unsigned nnod = el_pt->nnode();
             for (unsigned j = 0; j < nnod; j++)
             {
               Node* nod_pt = el_pt->node_pt(j);
               if (nod_pt->nvalue() == 0)
               {
                 std::ostringstream error_stream;
                 error_stream << "Node at  ";
                 unsigned n = nod_pt->ndim();
                 for (unsigned i = 0; i < n; i++)
                 {
                   error_stream << nod_pt->x(i) << " ";
                 }
                 error_stream
                   << "\nhas no values. Projection (of coordinates) doesn't "
                      "work\n"
                   << "for such cases (at the moment), sorry! Send us the code\n"
                   << "where the problem arises and we'll try to implement "
                      "this\n"
                   << "(up to now unnecessary) capability...\n";
                 throw OomphLibError(error_stream.str(),
                                     OOMPH_CURRENT_FUNCTION,
                                     OOMPH_EXCEPTION_LOCATION);
               }
             }
           }
 #endif
           // Check number of history values for coordinates
           n_history_values = dynamic_cast<PROJECTABLE_ELEMENT*>(
                                Problem::mesh_pt()->element_pt(0))
                                ->nhistory_values_for_coordinate_projection();
           // Projection the coordinates only if there are history values
           if (n_history_values > 1)
           {
             for (unsigned i = 0; i < n_dim; i++)
             {
               if (!Output_during_projection_suppressed)
               {
                 oomph_info
                   << "\n\n=============================================\n";
                 oomph_info << "Projecting history values for coordinate " << i
                            << std::endl;
                 oomph_info
                   << "=============================================\n\n";
               }
               // Set the coordinate for projection
               this->set_coordinate_for_projection(i);
               // Loop over number of history values, beginning with the latest
               // one. Don't deal with current time.
               for (unsigned h_tim = n_history_values; h_tim > 1; h_tim--)
               {
                 unsigned time_level = h_tim - 1;
                 // Set time_level we are dealing with
                 this->set_time_level_for_projection(time_level);
                 // Assign equation number
                 unsigned ndof_tmp = assign_eqn_numbers();
                 if (!Output_during_projection_suppressed)
                 {
                   oomph_info
                     << "Number of equations for projection of coordinate " << i
                     << " at time level " << time_level << " : " << ndof_tmp
                     << std::endl
                     << std::endl;
                 }
                 // Projection and interpolation
                 Problem::newton_solve();
                 // Move values back into history value of coordinate
                 unsigned n_element = Problem::mesh_pt()->nelement();
                 for (unsigned e = 0; e < n_element; e++)
                 {
                   PROJECTABLE_ELEMENT* new_el_pt =
                     dynamic_cast<PROJECTABLE_ELEMENT*>(
                       Problem::mesh_pt()->element_pt(e));
                   Vector<std::pair<Data*, unsigned>> data =
                     new_el_pt->data_values_of_field(0);
                   unsigned d_size = data.size();
                   for (unsigned d = 0; d < d_size; d++)
                   {
                     // Replace as coordinates
                     double coord = data[d].first->value(0, 0);
                     dynamic_cast<Node*>(data[d].first)->x(time_level, i) =
                       coord;
                   }
                 }
               }
             }
           } // End of history value projection
           // Repin the dofs for field 0
           this->pin_dofs_of_field(0);
         } // End of non-SolidElement case
       } // end if for projection of coordinates
       // Disable projection of coordinates
       for (unsigned e = 0; e < n_element; e++)
       {
         PROJECTABLE_ELEMENT* el_pt =
           dynamic_cast<PROJECTABLE_ELEMENT*>(Problem::mesh_pt()->element_pt(e));
         el_pt->set_project_values();
       }
       // Loop over fields
       for (unsigned fld = 0; fld < n_fields; fld++)
       {
         // Let us first pin every degree of freedom
         // We shall unpin selected dofs for each different projection problem
         this->pin_all();
         // Do actions for this field
         this->set_current_field_for_projection(fld);
         this->unpin_dofs_of_field(fld);
         // Check number of history values
         n_history_values =
           dynamic_cast<PROJECTABLE_ELEMENT*>(Problem::mesh_pt()->element_pt(0))
             ->nhistory_values_for_projection(fld);
         // Loop over number of history values
         // Beginning with the latest one
         for (unsigned h_tim = n_history_values; h_tim > 0; h_tim--)
         {
           unsigned time_level = h_tim - 1;
           if (!Output_during_projection_suppressed)
           {
             oomph_info << "\n=========================================\n";
             oomph_info << "Projecting field " << fld << " at time level "
                        << time_level << std::endl;
             oomph_info << "========================================\n";
           }
           // Set time_level we are dealing with
           this->set_time_level_for_projection(time_level);
           // Assign equation number
           unsigned ndof_tmp = assign_eqn_numbers();
           if (!Output_during_projection_suppressed)
           {
             oomph_info << "Number of equations for projection of field " << fld
                        << " at time level " << time_level << " : " << ndof_tmp
                        << std::endl
                        << std::endl;
           }
           // Projection and interpolation
           Problem::newton_solve();
           // Move computed values into the required time-level (not needed
           // for  current values which are done last -- they simply
           // stay where they are)
           if (time_level != 0)
           {
             for (unsigned e = 0; e < n_element; e++)
             {
               PROJECTABLE_ELEMENT* new_el_pt =
                 dynamic_cast<PROJECTABLE_ELEMENT*>(
                   Problem::mesh_pt()->element_pt(e));
               Vector<std::pair<Data*, unsigned>> data =
                 new_el_pt->data_values_of_field(fld);
               unsigned d_size = data.size();
               for (unsigned d = 0; d < d_size; d++)
               {
                 // Move into time level
                 double c_value = data[d].first->value(0, data[d].second);
                 data[d].first->set_value(time_level, data[d].second, c_value);
               }
             }
           }
         } // End of loop over time levels
       } // End of loop over fields
       // Reset parameters of external storage and interactions
       for (unsigned e = 0; e < n_element; e++)
       {
         PROJECTABLE_ELEMENT* new_el_pt =
           dynamic_cast<PROJECTABLE_ELEMENT*>(Problem::mesh_pt()->element_pt(e));
         // Flush information associated with the external elements
         new_el_pt->flush_all_external_element_storage();
         new_el_pt->disable_projection();
       }
       for (unsigned e = 0; e < n_element1; e++)
       {
         PROJECTABLE_ELEMENT* el_pt =
           dynamic_cast<PROJECTABLE_ELEMENT*>(base_mesh_pt->element_pt(e));
         // Flush information associated with the external elements
         el_pt->flush_all_external_element_storage();
         // Disable  projection
         el_pt->disable_projection();
       }
       // Now unpin everything to restore the problem to its virgin state
       this->unpin_all();
       // Now cleanup the storage
       Solid_backup.clear();
       /* unsigned ndof_tmp=this->assign_eqn_numbers(); */
       if (!Output_during_projection_suppressed)
       {
         /* oomph_info << "Number of unknowns after project: "  */
         /*            << ndof_tmp << std::endl; */
         // std::ostringstream warn_message;
         // warn_message
         // << "WARNING: Ensure to assign equations numbers in the new mesh,\n"
         // << "this is done by calling the assign_eqn_numbers() method from\n"
         // << "the original Problem object that has an instance of the mesh.\n"
         // << "This may be performed in actions_after_adapt() if the
         // projection\n"
         // << "was performed as part of the mesh adaptation process\n\n";
         // OomphLibWarning(warn_message.str(),
         //                OOMPH_CURRENT_FUNCTION,
         //                OOMPH_EXCEPTION_LOCATION);
       }
       else
       {
         // Reset verbosity in Newton solver
         Shut_up_in_newton_solve = shut_up_in_newton_solve_backup;
         if (backed_up_doc_time_enabled)
         {
           linear_solver_pt()->enable_doc_time();
         }
       }
     } // End of function Projection
References oomph::Problem::assign_eqn_numbers(), oomph::TrilinosAztecOOSolver::CG, data, oomph::LinearSolver::disable_doc_time(), oomph::Problem::disable_info_in_newton_solve(), e(), oomph::Mesh::element_pt(), oomph::LinearSolver::enable_doc_time(), oomph::Mesh::finite_element_pt(), i, oomph::LinearSolver::is_doc_time_enabled(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Iterative_solver_projection_pt, j, k, oomph::Problem::linear_solver_pt(), oomph::Problem::mesh_pt(), oomph::MPI_Helpers::mpi_has_been_initialised(), n, oomph::Node::ndim(), oomph::Mesh::nelement(), oomph::Problem::newton_solve(), oomph::SolidNode::nlagrangian_type(), oomph::FiniteElement::nnode(), oomph::Mesh::nnode(), oomph::FiniteElement::node_pt(), oomph::Mesh::node_pt(), oomph::Node::nposition_type(), oomph::Data::nvalue(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Output_during_projection_suppressed, oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::pin_all(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::pin_dofs_of_coordinate(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::pin_dofs_of_field(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Preconditioner_projection_pt, oomph::IterativeLinearSolver::preconditioner_pt(), oomph::Problem::Problem_is_nonlinear, oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::set_coordinate_for_projection(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::set_current_field_for_projection(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::set_lagrangian_coordinate_for_projection(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::set_time_level_for_projection(), oomph::Multi_domain_functions::setup_multi_domain_interaction(), oomph::Problem::Shut_up_in_newton_solve, oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Solid_backup, oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::store_positions(), oomph::TimingHelpers::timer(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::unpin_all(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::unpin_dofs_of_coordinate(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::unpin_dofs_of_field(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Use_iterative_solver_for_projection, plotDoE::x, oomph::Node::x(), oomph::Node::x_gen(), and oomph::SolidNode::xi_gen().
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::adapt(), and oomph::RefineableGmshTetMesh< ELEMENT >::adapt().
restore_positions()
template<class PROJECTABLE_ELEMENT > void oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::restore_positions () inline private
Helper function to restore positions (the only things that have been set before doing projection
     {
       // No need to do anything if there are no elements (in fact, we
       // probably never get here...)
       if (Problem::mesh_pt()->nelement() == 0) return;
       // Deal with positional dofs if (pseudo-)solid element
       // If we can cast the first element to a SolidFiniteElement then
       // assume that we have a solid mesh
       SolidFiniteElement* solid_el_pt =
         dynamic_cast<SolidFiniteElement*>(Problem::mesh_pt()->element_pt(0));
       if (solid_el_pt != 0)
       {
         const unsigned n_node = this->mesh_pt()->nnode();
         // Read dimension and number of position values from the first node
         const unsigned n_dim = this->mesh_pt()->node_pt(0)->ndim();
         const unsigned n_position_type =
           this->mesh_pt()->node_pt(0)->nposition_type();
         // Loop over the nodes
         for (unsigned n = 0; n < n_node; n++)
         {
           // Cache a pointer to a solid node
           SolidNode* const solid_nod_pt =
             dynamic_cast<SolidNode*>(this->mesh_pt()->node_pt(n));
           for (unsigned i = 0; i < n_dim; i++)
           {
             for (unsigned k = 0; k < n_position_type; k++)
             {
               solid_nod_pt->x_gen(k, i) = Solid_backup[n](k, i);
             }
           }
         }
       }
     }
References oomph::Mesh::element_pt(), i, k, oomph::Problem::mesh_pt(), n, oomph::Node::ndim(), oomph::Mesh::nnode(), oomph::Mesh::node_pt(), oomph::Node::nposition_type(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Solid_backup, and oomph::Node::x_gen().
set_coordinate_for_projection()
template<class PROJECTABLE_ELEMENT > void oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::set_coordinate_for_projection (const unsigned & i) inline private
Set the coordinate for projection.
     {
       unsigned n_element = Problem::mesh_pt()->nelement();
       for (unsigned e = 0; e < n_element; e++)
       {
         PROJECTABLE_ELEMENT* new_el_pt =
           dynamic_cast<PROJECTABLE_ELEMENT*>(Problem::mesh_pt()->element_pt(e));
         // Set that we are solving a projected coordinate problem
         new_el_pt->set_project_coordinates();
         // Set the projected coordinate
         new_el_pt->projected_coordinate() = i;
       }
     }
References e(), oomph::Mesh::element_pt(), i, oomph::Problem::mesh_pt(), and oomph::Mesh::nelement().
Referenced by oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project().
set_current_field_for_projection()
template<class PROJECTABLE_ELEMENT > void oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::set_current_field_for_projection (const unsigned & fld) inline private
Set current field for projection.
     {
       unsigned n_element = Problem::mesh_pt()->nelement();
       for (unsigned e = 0; e < n_element; e++)
       {
         PROJECTABLE_ELEMENT* new_el_pt =
           dynamic_cast<PROJECTABLE_ELEMENT*>(Problem::mesh_pt()->element_pt(e));
         // Set current field
         new_el_pt->projected_field() = fld;
       }
     }
References e(), oomph::Mesh::element_pt(), oomph::Problem::mesh_pt(), and oomph::Mesh::nelement().
Referenced by oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project().
set_lagrangian_coordinate_for_projection()
template<class PROJECTABLE_ELEMENT > void oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::set_lagrangian_coordinate_for_projection (const unsigned & i) inline private
Set the Lagrangian coordinate for projection.
     {
       unsigned n_element = Problem::mesh_pt()->nelement();
       for (unsigned e = 0; e < n_element; e++)
       {
         PROJECTABLE_ELEMENT* new_el_pt =
           dynamic_cast<PROJECTABLE_ELEMENT*>(Problem::mesh_pt()->element_pt(e));
         // Set that we are solving a projected Lagrangian coordinate problem
         new_el_pt->set_project_lagrangian();
         // Set the projected coordinate
         new_el_pt->projected_lagrangian_coordinate() = i;
       }
     }
References e(), oomph::Mesh::element_pt(), i, oomph::Problem::mesh_pt(), and oomph::Mesh::nelement().
Referenced by oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project().
set_time_level_for_projection()
template<class PROJECTABLE_ELEMENT > void oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::set_time_level_for_projection (const unsigned & time_level) inline private
Helper function to set time level for projection.
     {
       unsigned n_element = Problem::mesh_pt()->nelement();
       for (unsigned e = 0; e < n_element; e++)
       {
         PROJECTABLE_ELEMENT* el_pt =
           dynamic_cast<PROJECTABLE_ELEMENT*>(Problem::mesh_pt()->element_pt(e));
         // Set what time we are dealing with
         el_pt->time_level_for_projection() = time_level;
       }
     }
References e(), oomph::Mesh::element_pt(), oomph::Problem::mesh_pt(), and oomph::Mesh::nelement().
Referenced by oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project().
store_positions()
template<class PROJECTABLE_ELEMENT > void oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::store_positions () inline private
Helper function to store positions (the only things that have been set before doing projection
     {
       // No need to do anything if there are no elements (in fact, we
       // probably never get here...)
       if (Problem::mesh_pt()->nelement() == 0) return;
       // Deal with positional dofs if (pseudo-)solid element
       // If we can cast the first element to a SolidFiniteElement then
       // assume that we have a solid mesh
       SolidFiniteElement* solid_el_pt =
         dynamic_cast<SolidFiniteElement*>(Problem::mesh_pt()->element_pt(0));
       if (solid_el_pt != 0)
       {
         const unsigned n_node = this->mesh_pt()->nnode();
         Solid_backup.resize(n_node);
         // Read dimension and number of position values from the first node
         const unsigned n_dim = this->mesh_pt()->node_pt(0)->ndim();
         const unsigned n_position_type =
           this->mesh_pt()->node_pt(0)->nposition_type();
         // Loop over the nodes
         for (unsigned n = 0; n < n_node; n++)
         {
           // Cache a pointer to a solid node
           SolidNode* const solid_nod_pt =
             dynamic_cast<SolidNode*>(this->mesh_pt()->node_pt(n));
           // Now resize the appropriate storage
           Solid_backup[n].resize(n_position_type, n_dim);
           for (unsigned i = 0; i < n_dim; i++)
           {
             for (unsigned k = 0; k < n_position_type; k++)
             {
               Solid_backup[n](k, i) = solid_nod_pt->x_gen(k, i);
             }
           }
         }
       }
     }
References oomph::Mesh::element_pt(), i, k, oomph::Problem::mesh_pt(), n, oomph::Node::ndim(), oomph::Mesh::nnode(), oomph::Mesh::node_pt(), oomph::Node::nposition_type(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Solid_backup, and oomph::Node::x_gen().
Referenced by oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project().
unpin_all()
template<class PROJECTABLE_ELEMENT > void oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::unpin_all () inline private
Unpin all the field values and position unknowns (bit inefficient)
Do we have a solid mesh?
     {
       // No need to do anything if there are no elements (in fact, we
       // probably never get here...)
       if (Problem::mesh_pt()->nelement() == 0) return;
       // Loop over all the elements
       const unsigned n_element = Problem::mesh_pt()->nelement();
       for (unsigned e = 0; e < n_element; ++e)
       {
         // Cast the first element
         PROJECTABLE_ELEMENT* new_el_pt =
           dynamic_cast<PROJECTABLE_ELEMENT*>(Problem::mesh_pt()->element_pt(e));
         // Find the number of fields
         unsigned n_fields = new_el_pt->nfields_for_projection();
         // Now loop over all fields
         for (unsigned f = 0; f < n_fields; f++)
         {
           // Extract the data and value for the field
           Vector<std::pair<Data*, unsigned>> data =
             new_el_pt->data_values_of_field(f);
           // Now loop over all the data and unpin the appropriate values
           unsigned d_size = data.size();
           for (unsigned d = 0; d < d_size; d++)
           {
             data[d].first->unpin(data[d].second);
           }
         }
       }
       SolidFiniteElement* solid_el_pt =
         dynamic_cast<SolidFiniteElement*>(Problem::mesh_pt()->element_pt(0));
       if (solid_el_pt != 0)
       {
         // Find number of nodes
         const unsigned n_node = this->mesh_pt()->nnode();
         // If no nodes then return
         if (n_node == 0)
         {
           return;
         }
         // Read dimension and number of position values from the first node
         const unsigned n_dim = this->mesh_pt()->node_pt(0)->ndim();
         const unsigned n_position_type =
           this->mesh_pt()->node_pt(0)->nposition_type();
         // Loop over the nodes
         for (unsigned n = 0; n < n_node; n++)
         {
           SolidNode* solid_nod_pt =
             dynamic_cast<SolidNode*>(this->mesh_pt()->node_pt(n));
           for (unsigned i = 0; i < n_dim; i++)
           {
             for (unsigned k = 0; k < n_position_type; k++)
             {
               solid_nod_pt->unpin_position(k, i);
             }
           }
         }
       }
     }
References data, e(), oomph::Mesh::element_pt(), f(), i, k, oomph::Problem::mesh_pt(), n, oomph::Node::ndim(), oomph::Mesh::nelement(), oomph::Mesh::nnode(), oomph::Mesh::node_pt(), oomph::Node::nposition_type(), and oomph::SolidNode::unpin_position().
Referenced by oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project().
unpin_dofs_of_coordinate()
template<class PROJECTABLE_ELEMENT > void oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::unpin_dofs_of_coordinate (const unsigned & coord) inline private
Helper function to unpin the values of coordinate coord.
     {
       // Loop over the nodes
       const unsigned n_node = Problem::mesh_pt()->nnode();
       // If there are no nodes return immediately
       if (n_node == 0)
       {
         return;
       }
       // Find the number of position values (should be the same for all nodes)
       const unsigned n_position_type =
         Problem::mesh_pt()->node_pt(0)->nposition_type();
       for (unsigned n = 0; n < n_node; ++n)
       {
         // Cache access to the Node as a solid node
         SolidNode* solid_nod_pt =
           static_cast<SolidNode*>(Problem::mesh_pt()->node_pt(n));
         // Unpin all position types associated with the given coordinate
         for (unsigned k = 0; k < n_position_type; ++k)
         {
           solid_nod_pt->unpin_position(k, coord);
         }
       }
     }
References k, oomph::Problem::mesh_pt(), n, oomph::Mesh::nnode(), oomph::Mesh::node_pt(), oomph::Node::nposition_type(), and oomph::SolidNode::unpin_position().
Referenced by oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project().
unpin_dofs_of_field()
template<class PROJECTABLE_ELEMENT > void oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::unpin_dofs_of_field (const unsigned & fld) inline private
Helper function to unpin dofs of fld-th field.
     {
       unsigned n_element = Problem::mesh_pt()->nelement();
       for (unsigned e = 0; e < n_element; e++)
       {
         PROJECTABLE_ELEMENT* new_el_pt =
           dynamic_cast<PROJECTABLE_ELEMENT*>(Problem::mesh_pt()->element_pt(e));
         Vector<std::pair<Data*, unsigned>> data =
           new_el_pt->data_values_of_field(fld);
         unsigned d_size = data.size();
         for (unsigned d = 0; d < d_size; d++)
         {
           data[d].first->unpin(data[d].second);
         }
       }
     }
References data, e(), oomph::Mesh::element_pt(), oomph::Problem::mesh_pt(), and oomph::Mesh::nelement().
Referenced by oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project().
use_iterative_solver_for_projection()
template<class PROJECTABLE_ELEMENT > bool oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::use_iterative_solver_for_projection () inline
Return the value of the flag about using an iterative solver for projection
     {
       return Use_iterative_solver_for_projection;
     }
References oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Use_iterative_solver_for_projection.
Friends And Related Function Documentation
BackupMeshForProjection
template<class PROJECTABLE_ELEMENT > template<class FRIEND_PROJECTABLE_ELEMENT > friend class BackupMeshForProjection friend
RefineableGmshTetMesh
template<class PROJECTABLE_ELEMENT > template<class FRIEND_PROJECTABLE_ELEMENT > friend class RefineableGmshTetMesh friend
RefineableTetgenMesh
template<class PROJECTABLE_ELEMENT > template<class FRIEND_PROJECTABLE_ELEMENT > friend class RefineableTetgenMesh friend
RefineableTriangleMesh
template<class PROJECTABLE_ELEMENT > template<class FRIEND_PROJECTABLE_ELEMENT > friend class RefineableTriangleMesh friend
Member Data Documentation
Iterative_solver_projection_pt
template<class PROJECTABLE_ELEMENT > IterativeLinearSolver* oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Iterative_solver_projection_pt private
Referenced by oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::ProjectionProblem(), and oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::~ProjectionProblem().
Output_during_projection_suppressed
template<class PROJECTABLE_ELEMENT > bool oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Output_during_projection_suppressed private
Flag to suppress output during projection.
Referenced by oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::disable_suppress_output_during_projection(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::enable_suppress_output_during_projection(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project(), and oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::ProjectionProblem().
Preconditioner_projection_pt
template<class PROJECTABLE_ELEMENT > Preconditioner* oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Preconditioner_projection_pt private
Referenced by oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::ProjectionProblem(), and oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::~ProjectionProblem().
Solid_backup
template<class PROJECTABLE_ELEMENT > Vector<DenseMatrix<double> > oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Solid_backup private
Backup for pin status of solid node's position Data.
Referenced by oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::restore_positions(), and oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::store_positions().
Use_iterative_solver_for_projection
template<class PROJECTABLE_ELEMENT > bool oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::Use_iterative_solver_for_projection private
Referenced by oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::disable_use_iterative_solver_for_projection(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::enable_use_iterative_solver_for_projection(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::ProjectionProblem(), and oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::use_iterative_solver_for_projection().
The documentation for this class was generated from the following file:
projection.h