MercuryDPM: pretend_melt.cc File Reference
pretend_melt.cc File Reference
#include <fenv.h>
#include "generic.h"
#include "unsteady_heat.h"
#include "meshes/triangle_mesh.h"
#include "unsteady_heat_flux_pseudo_melt_elements.h"
Classes
class UnsteadyHeatProblem< ELEMENT >
UnsteadyHeat problem.
Namespaces
ProblemParameters
Namespace for exact solution and problem parameters.
Functions
void ProblemParameters::flux (const double &time, const Vector< double > &x, double &flux)
Get flux applied along boundary x=0.
int main (int argc, char *argv[])
Driver code for unsteady heat equation.
Function Documentation
main()
int main (int argc , char * argv[])
Driver code for unsteady heat equation.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Suppress adaptation
  CommandLineArgs::specify_command_line_flag("--no_adapt");
  // Melt everywhere?
  CommandLineArgs::specify_command_line_flag("--melt_everywhere");
  // Suppress melting?
  CommandLineArgs::specify_command_line_flag("--disable_melting");
  // Validation
  CommandLineArgs::specify_command_line_flag("--validate");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Build problem
  UnsteadyHeatProblem<ProjectableUnsteadyHeatElement
                      <TUnsteadyHeatElement<2,3> > > problem;
  // Setup labels for output
  DocInfo doc_info;
  // Output directory
  doc_info.set_directory("RESLT");
  // Output number
  doc_info.number()=0;
  // Choose simulation interval and timestep
  double t_max=0.5;
  double dt=0.01;
  // Initialise timestep -- also sets the weights for all timesteppers
  // in the problem.
  problem.initialise_dt(dt);
  // Set impulsive IC
  problem.assign_initial_values_impulsive(dt);
  //Output initial condition
  problem.doc_solution(doc_info);
  //Increment counter for solutions
  doc_info.number()++;
  unsigned max_adapt=1;
  bool first=false;
  if (CommandLineArgs::command_line_flag_has_been_set("--no_adapt"))
   {
    max_adapt=0;
   }
  // Find number of steps
  unsigned nstep = unsigned(t_max/dt);
  // Validation?
  if (CommandLineArgs::command_line_flag_has_been_set("--validate"))
   {
    nstep=5;
   }
  // Timestepping loop
  for (unsigned istep=0;istep<nstep;istep++)
   {
    cout << " Timestep " << istep << std::endl;
    // Take timestep
    problem.unsteady_newton_solve(dt,max_adapt,first);
    //Output solution
    problem.doc_solution(doc_info);
    //Increment counter for solutions
    doc_info.number()++;
   }
 }; // end of main
References oomph::CommandLineArgs::command_line_flag_has_been_set(), oomph::CommandLineArgs::doc_specified_flags(), oomph::DocInfo::number(), oomph::CommandLineArgs::parse_and_assign(), problem, oomph::DocInfo::set_directory(), Flag_definition::setup(), and oomph::CommandLineArgs::specify_command_line_flag().