MercuryDPM: Eigen::internal::quat_product< Architecture::Target, Derived, OtherDerived, float > Struct Template Reference
Eigen::internal::quat_product< Architecture::Target, Derived, OtherDerived, float > Struct Template Reference
#include <Geometry_SIMD.h>
Public Types
enum { AAlignment = traits<Derived>::Alignment , BAlignment = traits<OtherDerived>::Alignment , ResAlignment = traits<Quaternion<float> >::Alignment }
Static Public Member Functions
static Quaternion< float > run (const QuaternionBase< Derived > &_a, const QuaternionBase< OtherDerived > &_b)
Member Enumeration Documentation
anonymous enum
template<class Derived , class OtherDerived > anonymous enum
Enumerator
AAlignment
BAlignment
ResAlignment
        {
     AAlignment = traits<Derived>::Alignment,
     BAlignment = traits<OtherDerived>::Alignment,
     ResAlignment = traits<Quaternion<float> >::Alignment
   };
Member Function Documentation
run()
template<class Derived , class OtherDerived > static Quaternion<float> Eigen::internal::quat_product< Architecture::Target, Derived, OtherDerived, float >::run (const QuaternionBase< Derived > & _a, const QuaternionBase< OtherDerived > & _b) inline static
{
     evaluator<typename Derived::Coefficients> ae(_a.coeffs());
     evaluator<typename OtherDerived::Coefficients> be(_b.coeffs());
     Quaternion<float> res;
     const float neg_zero = numext::bit_cast<float>(0x80000000u);
     const float arr[4] = {0.f, 0.f, 0.f, neg_zero};
     const Packet4f mask = ploadu<Packet4f>(arr);
     Packet4f a = ae.template packet<AAlignment, Packet4f>(0);
     Packet4f b = be.template packet<BAlignment, Packet4f>(0);
     Packet4f s1 = pmul(vec4f_swizzle1(a, 1, 2, 0, 2), vec4f_swizzle1(b, 2, 0, 1, 2));
     Packet4f s2 = pmul(vec4f_swizzle1(a, 3, 3, 3, 1), vec4f_swizzle1(b, 0, 1, 2, 1));
     pstoret<float, Packet4f, ResAlignment>(
         &res.x(), padd(psub(pmul(a, vec4f_swizzle1(b, 3, 3, 3, 3)),
                             pmul(vec4f_swizzle1(a, 2, 0, 1, 0), vec4f_swizzle1(b, 1, 2, 0, 0))),
                        pxor(mask, padd(s1, s2))));
     return res;
   }
References a, b, Eigen::QuaternionBase< Derived >::coeffs(), Eigen::internal::padd(), Eigen::internal::ploadu< Packet4f >(), Eigen::internal::pmul(), Eigen::internal::psub(), Eigen::internal::pxor(), res, and Eigen::internal::vec4f_swizzle1().
The documentation for this struct was generated from the following file:
Geometry_SIMD.h