MercuryDPM: fsi_driven_cavity_driver.cc File Reference
fsi_driven_cavity_driver.cc File Reference
#include "fsi_driven_cavity_problem.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
Driver code for a collapsible channel problem with FSI. Presence of command line arguments indicates validation run with coarse resolution and small number of timesteps.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Number of elements in the domain (W. Wall standard resolution)
  unsigned nx=16; //32;
  unsigned ny=16; //32;
  // Length of the domain
  double lx=1.0;
  double ly=1.0;
  // Fractional height of the gap next to the moving lid
  double gap_fraction=1.0/16.0;
  // Period of lid oscillation
  double period=5.0;
  // Build the problem
  FSIDrivenCavityProblem
   <AlgebraicElement<QTaylorHoodElement<2> > >
   problem(nx, ny, lx, ly, gap_fraction, period);
  // Timestep.
  double dt=period/40.0;
  // Maximum time for simulation
  double t_max=50.0;
  // Initialise timestep
  problem.initialise_dt(dt);
  // Apply initial condition
  problem.set_initial_condition();
  //Set output directory
  DocInfo doc_info;
  doc_info.set_directory("RESLT");
  // Open a trace file
  ofstream trace_file;
  char filename[100];
  sprintf(filename,"%s/trace.dat",doc_info.directory().c_str());
  trace_file.open(filename);
  // Output the initial solution
  problem.doc_solution(doc_info, trace_file);
  // Increment step number
  doc_info.number()++;
  // Find number of timesteps (reduced for validation)
  unsigned nstep = unsigned(t_max/dt);
  if (CommandLineArgs::Argc>1)
   {
    nstep=3;
   }
  // Timestepping loop
  for (unsigned istep=0;istep<nstep;istep++)
   {
    // Solve the problem
    problem.unsteady_newton_solve(dt);
    // Outpt the solution
    problem.doc_solution(doc_info, trace_file);
    // Step number
    doc_info.number()++;
   }
  // Close trace file.
  trace_file.close();
 }//end of main
References oomph::CommandLineArgs::Argc, oomph::DocInfo::directory(), MergeRestartFiles::filename, Mesh_Parameters::lx, Mesh_Parameters::ly, oomph::DocInfo::number(), Mesh_Parameters::nx, Mesh_Parameters::ny, problem, oomph::DocInfo::set_directory(), and Flag_definition::setup().