MercuryDPM: Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ > Class Template Reference
Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ > Class Template Reference
#include <CompressedStorage.h>
Public Types
typedef Scalar_ Scalar
typedef StorageIndex_ StorageIndex
Public Member Functions
CompressedStorage ()
CompressedStorage (Index size)
CompressedStorage (const CompressedStorage &other)
CompressedStorage & operator= (const CompressedStorage &other)
void swap (CompressedStorage &other)
~CompressedStorage ()
void reserve (Index size)
void squeeze ()
void resize (Index size, double reserveSizeFactor=0)
void append (const Scalar &v, Index i)
Index size () const
Index allocatedSize () const
void clear ()
const Scalar * valuePtr () const
Scalar * valuePtr ()
const StorageIndex * indexPtr () const
StorageIndex * indexPtr ()
Scalar & value (Index i)
const Scalar & value (Index i) const
StorageIndex & index (Index i)
const StorageIndex & index (Index i) const
Index searchLowerIndex (Index key) const
Index searchLowerIndex (Index start, Index end, Index key) const
Scalar at (Index key, const Scalar &defaultValue=Scalar(0)) const
Scalar atInRange (Index start, Index end, Index key, const Scalar &defaultValue=Scalar(0)) const
Scalar & atWithInsertion (Index key, const Scalar &defaultValue=Scalar(0))
void moveChunk (Index from, Index to, Index chunkSize)
Protected Types
typedef NumTraits< Scalar >::Real RealScalar
Protected Member Functions
void reallocate (Index size)
Protected Attributes
Scalar * m_values
StorageIndex * m_indices
Index m_size
Index m_allocatedSize
Detailed Description
template<typename Scalar_, typename StorageIndex_>
class Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >
Stores a sparse set of values as a list of values and a list of indices.
Member Typedef Documentation
RealScalar
template<typename Scalar_ , typename StorageIndex_ > typedef NumTraits<Scalar>::Real Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::RealScalar protected
Scalar
template<typename Scalar_ , typename StorageIndex_ > typedef Scalar_ Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::Scalar
StorageIndex
template<typename Scalar_ , typename StorageIndex_ > typedef StorageIndex_ Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::StorageIndex
Constructor & Destructor Documentation
CompressedStorage() [1/3]
template<typename Scalar_ , typename StorageIndex_ > Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::CompressedStorage () inline
 : m_values(0), m_indices(0), m_size(0), m_allocatedSize(0) {}
CompressedStorage() [2/3]
template<typename Scalar_ , typename StorageIndex_ > Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::CompressedStorage (Index size) inline explicit
 : m_values(0), m_indices(0), m_size(0), m_allocatedSize(0) { resize(size); }
References Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::resize(), and Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::size().
CompressedStorage() [3/3]
template<typename Scalar_ , typename StorageIndex_ > Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::CompressedStorage (const CompressedStorage< Scalar_, StorageIndex_ > & other) inline
                                                     : m_values(0), m_indices(0), m_size(0), m_allocatedSize(0) {
     *this = other;
   }
~CompressedStorage()
template<typename Scalar_ , typename StorageIndex_ > Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::~CompressedStorage () inline
{
     conditional_aligned_delete_auto<Scalar, true>(m_values, m_allocatedSize);
     conditional_aligned_delete_auto<StorageIndex, true>(m_indices, m_allocatedSize);
   }
References Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_allocatedSize, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_indices, and Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_values.
Member Function Documentation
allocatedSize()
template<typename Scalar_ , typename StorageIndex_ > Index Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::allocatedSize () const inline
 { return m_allocatedSize; }
References Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_allocatedSize.
Referenced by bug1105(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertCompressedAtByOuterInner(), and Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertUncompressedAtByOuterInner().
append()
template<typename Scalar_ , typename StorageIndex_ > void Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::append (const Scalar & v, Index i) inline
{
     Index id = m_size;
     resize(m_size + 1, 1);
     m_values[id] = v;
     m_indices[id] = internal::convert_index<StorageIndex>(i);
   }
References i, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_indices, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_size, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_values, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::resize(), and v.
Referenced by Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertBackByOuterInner(), and Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertBackByOuterInnerUnordered().
at()
template<typename Scalar_ , typename StorageIndex_ > Scalar Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::at (Index key, const Scalar & defaultValue = Scalar(0)) const inline
Returns
the stored value at index key If the value does not exist, then the value defaultValue is returned without any insertion.
{
     if (m_size == 0)
       return defaultValue;
     else if (key == m_indices[m_size - 1])
       return m_values[m_size - 1];
     // ^^  optimization: let's first check if it is the last coefficient
     // (very common in high level algorithms)
     const Index id = searchLowerIndex(0, m_size - 1, key);
     return ((id < m_size) && (m_indices[id] == key)) ? m_values[id] : defaultValue;
   }
References Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_indices, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_size, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_values, and Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::searchLowerIndex().
atInRange()
template<typename Scalar_ , typename StorageIndex_ > Scalar Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::atInRange (Index start, Index end, Index key, const Scalar & defaultValue = Scalar(0)) const inline
Like at(), but the search is performed in the range [start,end)
{
     if (start >= end)
       return defaultValue;
     else if (end > start && key == m_indices[end - 1])
       return m_values[end - 1];
     // ^^  optimization: let's first check if it is the last coefficient
     // (very common in high level algorithms)
     const Index id = searchLowerIndex(start, end - 1, key);
     return ((id < end) && (m_indices[id] == key)) ? m_values[id] : defaultValue;
   }
References Eigen::placeholders::end, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_indices, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_values, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::searchLowerIndex(), and oomph::CumulativeTimings::start().
Referenced by Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::coeff().
atWithInsertion()
template<typename Scalar_ , typename StorageIndex_ > Scalar& Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::atWithInsertion (Index key, const Scalar & defaultValue = Scalar(0)) inline
Returns
a reference to the value at index key If the value does not exist, then the value defaultValue is inserted such that the keys are sorted.
{
     Index id = searchLowerIndex(0, m_size, key);
     if (id >= m_size || m_indices[id] != key) {
       if (m_allocatedSize < m_size + 1) {
         Index newAllocatedSize = 2 * (m_size + 1);
         m_values = conditional_aligned_realloc_new_auto<Scalar, true>(m_values, newAllocatedSize, m_allocatedSize);
         m_indices =
             conditional_aligned_realloc_new_auto<StorageIndex, true>(m_indices, newAllocatedSize, m_allocatedSize);
         m_allocatedSize = newAllocatedSize;
       }
       if (m_size > id) {
         internal::smart_memmove(m_values + id, m_values + m_size, m_values + id + 1);
         internal::smart_memmove(m_indices + id, m_indices + m_size, m_indices + id + 1);
       }
       m_size++;
       m_indices[id] = internal::convert_index<StorageIndex>(key);
       m_values[id] = defaultValue;
     }
     return m_values[id];
   }
References Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_allocatedSize, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_indices, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_size, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_values, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::searchLowerIndex(), and Eigen::internal::smart_memmove().
clear()
template<typename Scalar_ , typename StorageIndex_ > void Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::clear () inline
 { m_size = 0; }
References Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_size.
Referenced by Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::resize(), and Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::setZero().
index() [1/2]
template<typename Scalar_ , typename StorageIndex_ > StorageIndex& Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::index (Index i) inline
{
     eigen_internal_assert(m_indices != 0);
     return m_indices[i];
   }
References eigen_internal_assert, i, and Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_indices.
Referenced by Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::assignDiagonal(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::collapseDuplicates(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::findOrInsertCoeff(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertBackByOuterInner(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertBackUncompressed(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertByOuterInner(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertCompressed(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertCompressedAtByOuterInner(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertUncompressed(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertUncompressedAtByOuterInner(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::operator=(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::prune(), and Eigen::internal::set_from_triplets_sorted().
index() [2/2]
template<typename Scalar_ , typename StorageIndex_ > const StorageIndex& Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::index (Index i) const inline
{
     eigen_internal_assert(m_indices != 0);
     return m_indices[i];
   }
References eigen_internal_assert, i, and Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_indices.
indexPtr() [1/2]
template<typename Scalar_ , typename StorageIndex_ > StorageIndex* Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::indexPtr () inline
 { return m_indices; }
References Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_indices.
indexPtr() [2/2]
template<typename Scalar_ , typename StorageIndex_ > const StorageIndex* Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::indexPtr () const inline
 { return m_indices; }
References Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_indices.
Referenced by Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::innerIndexPtr().
moveChunk()
template<typename Scalar_ , typename StorageIndex_ > void Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::moveChunk (Index from, Index to, Index chunkSize) inline
{
     eigen_internal_assert(chunkSize >= 0 && to + chunkSize <= m_size);
     internal::smart_memmove(m_values + from, m_values + from + chunkSize, m_values + to);
     internal::smart_memmove(m_indices + from, m_indices + from + chunkSize, m_indices + to);
   }
References eigen_internal_assert, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_indices, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_size, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_values, and Eigen::internal::smart_memmove().
Referenced by Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::assignDiagonal(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertCompressedAtByOuterInner(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertUncompressedAtByOuterInner(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::makeCompressed(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::removeOuterVectors(), and Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::reserveInnerVectors().
operator=()
template<typename Scalar_ , typename StorageIndex_ > CompressedStorage& Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::operator= (const CompressedStorage< Scalar_, StorageIndex_ > & other) inline
{
     resize(other.size());
     if (other.size() > 0) {
       internal::smart_copy(other.m_values, other.m_values + m_size, m_values);
       internal::smart_copy(other.m_indices, other.m_indices + m_size, m_indices);
     }
     return *this;
   }
References Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_indices, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_size, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_values, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::resize(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::size(), and Eigen::internal::smart_copy().
reallocate()
template<typename Scalar_ , typename StorageIndex_ > void Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::reallocate (Index size) inline protected
{
 #ifdef EIGEN_SPARSE_COMPRESSED_STORAGE_REALLOCATE_PLUGIN
     EIGEN_SPARSE_COMPRESSED_STORAGE_REALLOCATE_PLUGIN
 #endif
     eigen_internal_assert(size != m_allocatedSize);
     m_values = conditional_aligned_realloc_new_auto<Scalar, true>(m_values, size, m_allocatedSize);
     m_indices = conditional_aligned_realloc_new_auto<StorageIndex, true>(m_indices, size, m_allocatedSize);
     m_allocatedSize = size;
   }
References eigen_internal_assert, EIGEN_SPARSE_COMPRESSED_STORAGE_REALLOCATE_PLUGIN, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_allocatedSize, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_indices, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_values, and Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::size().
Referenced by Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::reserve(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::resize(), and Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::squeeze().
reserve()
template<typename Scalar_ , typename StorageIndex_ > void Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::reserve (Index size) inline
{
     Index newAllocatedSize = m_size + size;
     if (newAllocatedSize > m_allocatedSize) reallocate(newAllocatedSize);
   }
References Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_allocatedSize, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_size, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::reallocate(), and Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::size().
Referenced by Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertCompressedAtByOuterInner(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::reserve(), and Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::reserveInnerVectors().
resize()
template<typename Scalar_ , typename StorageIndex_ > void Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::resize (Index size, double reserveSizeFactor = 0) inline
{
     if (m_allocatedSize < size) {
       // Avoid underflow on the std::min<Index> call by choosing the smaller index type.
       using SmallerIndexType =
           typename std::conditional<static_cast<size_t>((std::numeric_limits<Index>::max)()) <
                                         static_cast<size_t>((std::numeric_limits<StorageIndex>::max)()),
                                     Index, StorageIndex>::type;
       Index realloc_size =
           (std::min<Index>)(NumTraits<SmallerIndexType>::highest(), size + Index(reserveSizeFactor * double(size)));
       if (realloc_size < size) internal::throw_std_bad_alloc();
       reallocate(realloc_size);
     }
     m_size = size;
   }
References Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_allocatedSize, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_size, max, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::reallocate(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::size(), Eigen::internal::throw_std_bad_alloc(), and compute_granudrum_aor::type.
Referenced by Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::append(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::assignDiagonal(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::collapseDuplicates(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::CompressedStorage(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::conservativeResize(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertCompressedAtByOuterInner(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertUncompressedAtByOuterInner(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::makeCompressed(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::operator=(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::operator=(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::prune(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::reserveInnerVectors(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::resizeNonZeros(), and Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::setIdentity().
searchLowerIndex() [1/2]
template<typename Scalar_ , typename StorageIndex_ > Index Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::searchLowerIndex (Index key) const inline
Returns
the largest k such that for all j in [0,k) index[j]<key
 { return searchLowerIndex(0, m_size, key); }
References Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_size, and Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::searchLowerIndex().
Referenced by Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::assignDiagonal(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::at(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::atInRange(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::atWithInsertion(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::conservativeResize(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::findOrInsertCoeff(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertByOuterInner(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertCompressed(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertUncompressed(), and Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::searchLowerIndex().
searchLowerIndex() [2/2]
template<typename Scalar_ , typename StorageIndex_ > Index Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::searchLowerIndex (Index start, Index end, Index key) const inline
Returns
the largest k in [start,end) such that for all j in [start,k) index[j]<key
{
     return static_cast<Index>(std::distance(m_indices, std::lower_bound(m_indices + start, m_indices + end, key)));
   }
References Eigen::placeholders::end, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_indices, and oomph::CumulativeTimings::start().
size()
template<typename Scalar_ , typename StorageIndex_ > Index Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::size () const inline
 { return m_size; }
References Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_size.
Referenced by Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::assignDiagonal(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::CompressedStorage(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::conservativeResize(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::finalize(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertBackByOuterInner(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertCompressedAtByOuterInner(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::operator=(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::reallocate(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::reserve(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::resize(), and Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::startVec().
squeeze()
template<typename Scalar_ , typename StorageIndex_ > void Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::squeeze () inline
                  {
     if (m_allocatedSize > m_size) reallocate(m_size);
   }
References Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_allocatedSize, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_size, and Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::reallocate().
Referenced by Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::makeCompressed(), and Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::setIdentity().
swap()
template<typename Scalar_ , typename StorageIndex_ > void Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::swap (CompressedStorage< Scalar_, StorageIndex_ > & other) inline
{
     std::swap(m_values, other.m_values);
     std::swap(m_indices, other.m_indices);
     std::swap(m_size, other.m_size);
     std::swap(m_allocatedSize, other.m_allocatedSize);
   }
References Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_allocatedSize, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_indices, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_size, Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_values, and swap().
Referenced by Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::swap().
value() [1/2]
template<typename Scalar_ , typename StorageIndex_ > Scalar& Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::value (Index i) inline
{
     eigen_internal_assert(m_values != 0);
     return m_values[i];
   }
References eigen_internal_assert, i, and Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_values.
Referenced by Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::assignDiagonal(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::collapseDuplicates(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::findOrInsertCoeff(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertBackByOuterInner(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertBackByOuterInnerUnordered(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertBackUncompressed(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertByOuterInner(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertCompressedAtByOuterInner(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertUncompressed(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertUncompressedAtByOuterInner(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::operator=(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::prune(), and Eigen::internal::set_from_triplets_sorted().
value() [2/2]
template<typename Scalar_ , typename StorageIndex_ > const Scalar& Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::value (Index i) const inline
{
     eigen_internal_assert(m_values != 0);
     return m_values[i];
   }
References eigen_internal_assert, i, and Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_values.
valuePtr() [1/2]
template<typename Scalar_ , typename StorageIndex_ > Scalar* Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::valuePtr () inline
 { return m_values; }
References Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_values.
valuePtr() [2/2]
template<typename Scalar_ , typename StorageIndex_ > const Scalar* Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::valuePtr () const inline
 { return m_values; }
References Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_values.
Referenced by Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::valuePtr().
Member Data Documentation
m_allocatedSize
template<typename Scalar_ , typename StorageIndex_ > Index Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_allocatedSize protected
Referenced by Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::allocatedSize(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::atWithInsertion(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::reallocate(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::reserve(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::resize(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::squeeze(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::swap(), and Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::~CompressedStorage().
m_indices
template<typename Scalar_ , typename StorageIndex_ > StorageIndex* Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_indices protected
Referenced by Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::append(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::at(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::atInRange(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::atWithInsertion(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::index(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::indexPtr(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::moveChunk(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::operator=(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::reallocate(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::searchLowerIndex(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::swap(), and Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::~CompressedStorage().
m_size
template<typename Scalar_ , typename StorageIndex_ > Index Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_size protected
Referenced by Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::append(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::at(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::atWithInsertion(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::clear(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::moveChunk(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::operator=(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::reserve(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::resize(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::searchLowerIndex(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::size(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::squeeze(), and Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::swap().
m_values
template<typename Scalar_ , typename StorageIndex_ > Scalar* Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::m_values protected
Referenced by Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::append(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::at(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::atInRange(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::atWithInsertion(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::moveChunk(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::operator=(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::reallocate(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::swap(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::value(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::valuePtr(), and Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::~CompressedStorage().
The documentation for this class was generated from the following file:
CompressedStorage.h