MercuryDPM: PeriodicBoundaryEnteringMpiDomainMPI2Test.cpp File Reference
PeriodicBoundaryEnteringMpiDomainMPI2Test.cpp File Reference
#include "Mercury3D.h"
#include "Species/LinearViscoelasticFrictionSpecies.h"
#include "Boundaries/PeriodicBoundary.h"
#include "Walls/IntersectionOfWalls.h"
Classes
class PeriodicBounaryEnteringMPIDomainTest
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
 {
     //Create the problem
     PeriodicBounaryEnteringMPIDomainTest problem;
     problem.setName("PeriodicBounaryEnteringMPIDomainTest");
     //Create a species
     LinearViscoelasticFrictionSpecies* species = problem.speciesHandler.copyAndAddObject(
             LinearViscoelasticFrictionSpecies());
     species->setDensity(1.0);
     //Set domain accordingly (domain boundaries are not walls!)
     problem.setXMin(0);
     problem.setXMax(20);
     problem.setYMin(-10.0);
     problem.setYMax(10.0);
     problem.setZMin(0.0);
     problem.setZMax(100.0);
     //specify particle properties
     species->setDensity(6.0 / constants::pi);
     //specify body forces
     problem.setGravity(Vec3D(0.0, 0.0, 0.0));
     //Set the number of domains for parallel decomposition
     problem.setNumberOfDomains({2, 1, 1});
     //specify contact properties
     //normal forces
     species->setStiffness(1e5);
     species->setDissipation(0.63);
     //tangential (sliding) forces
     species->setSlidingFrictionCoefficient(0);
     //set other simulation parameters
     Mdouble MinParticleMass = species->getDensity() * 4.0 / 3.0 * constants::pi;
     //Mdouble tc = species->getCollisionTime(MinParticleMass);
     Mdouble tc = 0.02;
     logger(INFO, "tc: %", tc);
     problem.setTimeStep(tc / 50.0);
     problem.setTimeMax(3);
     problem.setSaveCount(500);
     //Set output to paraview
     problem.setParticlesWriteVTK(true);
     problem.solve(argc, argv);
     return 0;
 }
References ParticleSpecies::getDensity(), INFO, logger, constants::pi, problem, ParticleSpecies::setDensity(), LinearViscoelasticNormalSpecies::setDissipation(), SlidingFrictionSpecies::setSlidingFrictionCoefficient(), and LinearViscoelasticNormalSpecies::setStiffness().