MercuryDPM: oomph::SurfaceMeltElement< ELEMENT > Class Template Reference
oomph::SurfaceMeltElement< ELEMENT > Class Template Reference
#include <heat_transfer_and_melt_elements.h>
Public Member Functions
SurfaceMeltElement (FiniteElement *const &bulk_el_pt, const int &face_index, const unsigned &id=0, const bool &called_from_refineable_constructor=false)
double get_interpolated_lagrange_p (const Vector< double > &s)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Return the residuals.
double melt_temperature ()
Melt temperature.
double *& melt_temperature_pt ()
Pointer to (non-default) melt temperature.
void disable_melting ()
Switch off melting by pinning melt-rate dofs.
void set_lagrange_multiplier_pressure_to_zero ()
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_melt_rate (const Vector< double > &s, double &melt_flux)
Melt rate at local coordinate s.
void output_melt (std::ostream &outfile)
Public Member Functions inherited from oomph::SolidFaceElement
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
double interpolated_xi (const Vector< double > &s, const unsigned &i) const
void interpolated_xi (const Vector< double > &s, Vector< double > &xi) const
Public Member Functions inherited from oomph::FaceElement
FaceElement ()
Constructor: Initialise all appropriate member data.
virtual ~FaceElement ()
Empty virtual destructor.
FaceElement (const FaceElement &)=delete
Broken copy constructor.
const unsigned & boundary_number_in_bulk_mesh () const
Broken assignment operator.
void set_boundary_number_in_bulk_mesh (const unsigned &b)
Set function for the boundary number in bulk mesh.
double J_eulerian (const Vector< double > &s) const
double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
double interpolated_x (const Vector< double > &s, const unsigned &i) const
double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
void interpolated_x (const Vector< double > &s, Vector< double > &x) const
void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
int & normal_sign ()
int normal_sign () const
int & face_index ()
int face_index () const
const Vector< double > * tangent_direction_pt () const
Public access function for the tangent direction pointer.
void set_tangent_direction (Vector< double > *tangent_direction_pt)
Set the tangent direction vector.
void turn_on_warning_for_discontinuous_tangent ()
void turn_off_warning_for_discontinuous_tangent ()
void continuous_tangent_and_outer_unit_normal (const Vector< double > &s, Vector< Vector< double >> &tang_vec, Vector< double > &unit_normal) const
void continuous_tangent_and_outer_unit_normal (const unsigned &ipt, Vector< Vector< double >> &tang_vec, Vector< double > &unit_normal) const
void outer_unit_normal (const Vector< double > &s, Vector< double > &unit_normal) const
Compute outer unit normal at the specified local coordinate.
void outer_unit_normal (const unsigned &ipt, Vector< double > &unit_normal) const
Compute outer unit normal at ipt-th integration point.
FiniteElement *& bulk_element_pt ()
Pointer to higher-dimensional "bulk" element.
FiniteElement * bulk_element_pt () const
Pointer to higher-dimensional "bulk" element (const version)
CoordinateMappingFctPt & face_to_bulk_coordinate_fct_pt ()
CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt () const
BulkCoordinateDerivativesFctPt & bulk_coordinate_derivatives_fct_pt ()
BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt () const
Vector< double > local_coordinate_in_bulk (const Vector< double > &s) const
void get_local_coordinate_in_bulk (const Vector< double > &s, Vector< double > &s_bulk) const
void get_ds_bulk_ds_face (const Vector< double > &s, DenseMatrix< double > &dsbulk_dsface, unsigned &interior_direction) const
unsigned & bulk_position_type (const unsigned &i)
const unsigned & bulk_position_type (const unsigned &i) const
void bulk_node_number_resize (const unsigned &i)
Resize the storage for the bulk node numbers.
unsigned & bulk_node_number (const unsigned &n)
const unsigned & bulk_node_number (const unsigned &n) const
void bulk_position_type_resize (const unsigned &i)
Resize the storage for bulk_position_type to i entries.
unsigned & nbulk_value (const unsigned &n)
unsigned nbulk_value (const unsigned &n) const
void nbulk_value_resize (const unsigned &i)
void resize_nodes (Vector< unsigned > &nadditional_data_values)
void output_zeta (std::ostream &outfile, const unsigned &nplot)
Output boundary coordinate zeta.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::SolidFiniteElement
void set_lagrangian_dimension (const unsigned &lagrangian_dimension)
virtual bool has_internal_solid_data ()
SolidFiniteElement ()
Constructor: Set defaults.
virtual ~SolidFiniteElement ()
Destructor to clean up any allocated memory.
SolidFiniteElement (const SolidFiniteElement &)=delete
Broken copy constructor.
unsigned ngeom_data () const
Broken assignment operator.
Data * geom_data_pt (const unsigned &j)
void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual void get_x_and_xi (const Vector< double > &s, Vector< double > &x_fe, Vector< double > &x, Vector< double > &xi_fe, Vector< double > &xi) const
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt, MacroElement *undeformed_macro_elem_pt)
void set_undeformed_macro_elem_pt (MacroElement *undeformed_macro_elem_pt)
MacroElement * undeformed_macro_elem_pt ()
Access function to pointer to "undeformed" macro element.
double dshape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi) const
virtual double dshape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi) const
double d2shape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
virtual double d2shape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
unsigned lagrangian_dimension () const
unsigned nnodal_lagrangian_type () const
Node * construct_node (const unsigned &n)
Construct the local node n and return a pointer to it.
Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Node * construct_boundary_node (const unsigned &n)
Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
double raw_lagrangian_position (const unsigned &n, const unsigned &i) const
double raw_lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double lagrangian_position (const unsigned &n, const unsigned &i) const
Return i-th Lagrangian coordinate at local node n.
double lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void interpolated_dxids (const Vector< double > &s, DenseMatrix< double > &dxids) const
virtual void J_lagrangian (const Vector< double > &s) const
virtual double J_lagrangian_at_knot (const unsigned &ipt) const
SolidInitialCondition *& solid_ic_pt ()
Pointer to object that describes the initial condition.
void enable_solve_for_consistent_newmark_accel ()
void disable_solve_for_consistent_newmark_accel ()
Set to reset the problem being solved to be the standard problem.
MultiplierFctPt & multiplier_fct_pt ()
MultiplierFctPt multiplier_fct_pt () const
virtual void get_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_for_newmark_accel (DenseMatrix< double > &jacobian)
void compute_norm (double &el_norm)
int position_local_eqn (const unsigned &n, const unsigned &k, const unsigned &j) const
Public Member Functions inherited from oomph::UnsteadyHeatBaseFaceElement< ELEMENT >
UnsteadyHeatBaseFaceElement (FiniteElement *const &bulk_el_pt, const int &face_index)
Constructor.
virtual ~UnsteadyHeatBaseFaceElement ()
Destructor.
void interpolated_u (const Vector< double > &s, double &u)
Temperature at local coordinate s.
void output (std::ostream &outfile)
Output function.
void output (std::ostream &outfile, const unsigned &n_plot)
void output (FILE *file_pt)
C_style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function.
Public Member Functions inherited from oomph::TemplateFreeUnsteadyHeatBaseFaceElement
TemplateFreeUnsteadyHeatBaseFaceElement ()
Constructor.
virtual ~TemplateFreeUnsteadyHeatBaseFaceElement ()
Destrutor.
UnsteadyHeatPrescribedFluxFctPt & flux_fct_pt ()
Access function for the prescribed-flux function pointer.
Protected Member Functions
void fill_in_contribution_to_residuals_surface_melt (Vector< double > &residuals)
Helper function that actually calculates the residuals.
Protected Member Functions inherited from oomph::FaceElement
void add_additional_values (const Vector< unsigned > &nadditional_values, const unsigned &id)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::SolidFiniteElement
void fill_in_generic_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
void set_nnodal_lagrangian_type (const unsigned &nlagrangian_type)
virtual double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_lagrangian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void assign_solid_local_eqn_numbers (const bool &store_local_dof)
Assign local equation numbers for the solid equations in the element.
void describe_solid_local_dofs (std::ostream &out, const std::string &current_string) const
Classifies dofs locally for solid specific aspects.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void fill_in_jacobian_from_solid_position_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_solid_position_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_solid_position_fd ()
virtual void reset_after_solid_position_fd ()
virtual void update_in_solid_position_fd (const unsigned &i)
virtual void reset_in_solid_position_fd (const unsigned &i)
Protected Member Functions inherited from oomph::UnsteadyHeatBaseFaceElement< ELEMENT >
double shape_and_test (const Vector< double > &s, Shape &psi, Shape &test) const
Protected Member Functions inherited from oomph::TemplateFreeUnsteadyHeatBaseFaceElement
virtual void get_flux (const unsigned &ipt, const double &time, const Vector< double > &x, const Vector< double > &n, const double &u, double &flux)
Protected Attributes
unsigned Melt_id
Id of additional unknowns (Lagrange multiplier ("pressure") and melt rate)
double * Melt_temperature_pt
Pointer to non-default melt temperature.
Protected Attributes inherited from oomph::FaceElement
unsigned Boundary_number_in_bulk_mesh
The boundary number in the bulk mesh to which this element is attached.
FiniteElement * Bulk_element_pt
Pointer to the associated higher-dimensional "bulk" element.
Vector< unsigned > Bulk_node_number
Vector< unsigned > Nbulk_value
Vector< double > * Tangent_direction_pt
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::SolidFiniteElement
MacroElement * Undeformed_macro_elem_pt
Pointer to the element's "undeformed" macro element (NULL by default)
SolidInitialCondition * Solid_ic_pt
Pointer to object that specifies the initial condition.
bool Solve_for_consistent_newmark_accel_flag
Protected Attributes inherited from oomph::TemplateFreeUnsteadyHeatBaseFaceElement
unsigned U_index_ust_heat
Index at which temperature is stored.
unsigned Dim
The spatial dimension of the problem.
UnsteadyHeatPrescribedFluxFctPt Flux_fct_pt
Function pointer to the (global) prescribed-flux function.
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Types inherited from oomph::SolidFiniteElement
typedef double(* MultiplierFctPt) (const Vector< double > &xi)
Public Types inherited from oomph::TemplateFreeUnsteadyHeatBaseFaceElement
typedef void(* UnsteadyHeatPrescribedFluxFctPt) (const double &time, const Vector< double > &x, const Vector< double > &n, const double &u, double &flux)
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<class ELEMENT>
class oomph::SurfaceMeltElement< ELEMENT >
////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////// A class for elements that impose Stefan (melting) condition on adjacent pseudo-solid-based unsteady heat elements.
The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class.
Constructor & Destructor Documentation
SurfaceMeltElement()
template<class ELEMENT > oomph::SurfaceMeltElement< ELEMENT >::SurfaceMeltElement (FiniteElement *const & bulk_el_pt, const int & face_index, const unsigned & id = 0, const bool & called_from_refineable_constructor = false) inline
Constructor, which takes a "bulk" element and the value of the index and its limit
                                                                             :
   UnsteadyHeatBaseFaceElement<ELEMENT>(bulk_el_pt,face_index)
    {
 #ifdef PARANOID
     {
      //Check that the element is not a refineable 3d element
      if (!called_from_refineable_constructor)
       {
        if(bulk_el_pt->dim()==3)
         {
          //Is it refineable
          if(dynamic_cast<RefineableElement*>(bulk_el_pt))
           {
            //Issue a warning
            std::string error_string=
             "This face element will not work correctly if nodes are hanging.\n";
            error_string+="Use the refineable version instead. ";
            OomphLibWarning(error_string,
                            OOMPH_CURRENT_FUNCTION,
                            OOMPH_EXCEPTION_LOCATION);
           }
         }
       }
     }
 #endif
     // Use default melt temperature
     Melt_temperature_pt=0;
     //  Store the ID of the FaceElement -- this is used to distinguish
     // it from any others
     Melt_id=id;
     // We need two additional value for each FaceElement node:
     // (1) the normal traction (Lagrange multiplier) to be
     // exerted onto the pseudo-solid and (2) the melt rate
     unsigned n_nod=nnode();
     Vector<unsigned> n_additional_values(n_nod,2);
     // Now add storage for Lagrange multipliers and set the map containing
     // the position of the first entry of this face element's
     // additional values.
     add_additional_values(n_additional_values,id);
 #ifdef PARANOID
     // Check spatial dimension
     if (this->Dim!=2)
      {
       //Issue a warning
       throw OomphLibError(
        "This element will almost certainly not work in non-2D problems, though it should be easy enough to upgrade... Volunteers?\n",
        OOMPH_CURRENT_FUNCTION,
        OOMPH_EXCEPTION_LOCATION);
      }
 #endif
     /* // hierher */
     /* // Add positions of bulk nodes as external data */
     /* unsigned nnod_bulk=bulk_el_pt->nnode(); */
     /* unsigned count=0; */
     /* for (unsigned j=0;j<nnod_bulk;j++) */
     /*  { */
     /*   SolidNode* bulk_nod_pt=dynamic_cast<SolidNode*>(bulk_el_pt->node_pt(j)); */
     /*   unsigned do_it=true; */
     /*   for (unsigned k=0;k<n_nod;k++) */
     /*    { */
     /*     SolidNode* nod_pt=dynamic_cast<SolidNode*>(node_pt(k)); */
     /*     if (nod_pt==bulk_nod_pt) */
     /*      { */
     /*       do_it=false; */
     /*       break; */
     /*      } */
     /*    } */
     /*   if (do_it) */
     /*    { */
     /*     count++; */
     /*     add_external_data(bulk_nod_pt->variable_position_pt()); */
     /*     add_external_data(bulk_nod_pt); */
     /*    } */
     /*  } */
     /* oomph_info << "Added " << count << " position data from bulk\n"; */
    }
References oomph::FaceElement::add_additional_values(), oomph::TemplateFreeUnsteadyHeatBaseFaceElement::Dim, oomph::FiniteElement::dim(), oomph::SurfaceMeltElement< ELEMENT >::Melt_id, oomph::SurfaceMeltElement< ELEMENT >::Melt_temperature_pt, oomph::FiniteElement::nnode(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
Member Function Documentation
disable_melting()
template<class ELEMENT > void oomph::SurfaceMeltElement< ELEMENT >::disable_melting () inline
Switch off melting by pinning melt-rate dofs.
   {
    unsigned n_node=nnode();
    for(unsigned l=0;l<n_node;l++)
     {
      // get the node pt
      Node* nod_pt = node_pt(l);
      // Cast to a boundary node
      BoundaryNodeBase *bnod_pt =
       dynamic_cast<BoundaryNodeBase*>(nod_pt);
      // Get the index of the first nodal value associated with
      // this FaceElement
      unsigned first_index=
       bnod_pt->index_of_first_value_assigned_by_face_element(Melt_id);
      // Pin melt rate (second additional value created by this face element)
      nod_pt->pin(first_index+1);
     }
   }
References oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), oomph::SurfaceMeltElement< ELEMENT >::Melt_id, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::Data::pin().
Referenced by UnsteadyHeatMeltProblem< ELEMENT >::complete_problem_setup().
fill_in_contribution_to_residuals()
template<class ELEMENT > void oomph::SurfaceMeltElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Return the residuals.
Reimplemented from oomph::UnsteadyHeatBaseFaceElement< ELEMENT >.
   {
    fill_in_contribution_to_residuals_surface_melt(residuals);
   }
References oomph::SurfaceMeltElement< ELEMENT >::fill_in_contribution_to_residuals_surface_melt().
fill_in_contribution_to_residuals_surface_melt()
template<class ELEMENT > void oomph::SurfaceMeltElement< ELEMENT >::fill_in_contribution_to_residuals_surface_melt (Vector< double > & residuals) protected
Helper function that actually calculates the residuals.
Return the residuals for the SurfaceMeltElement equations.
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
  {
   // hierher kill oomph_info << "hierher: Number of dofs: " << ndof() << std::endl;
   // Get continuous time from timestepper of first node
   double time=node_pt(0)->time_stepper_pt()->time_pt()->time();
   //Find out how many nodes there are
   unsigned n_node = nnode();
   //Find out how many positional dofs there are
   unsigned n_position_type = this->nnodal_position_type();
   //Find out the dimension of the node
   unsigned n_dim = this->nodal_dimension();
   //Integer to hold the local equation number
   int local_eqn=0;
   /* // hierher kill */
   /* { */
   /*  for (unsigned j=0;j<n_node;j++) */
   /*   { */
   /*    SolidNode* nod_pt=dynamic_cast<SolidNode*>(node_pt(j)); */
   /*    unsigned nval=nod_pt->nvalue(); */
   /*    for (unsigned i=0;i<nval;i++) */
   /*     { */
   /*      oomph_info << "i_val, eqn_number: " << i << " "  */
   /*                 << nod_pt->eqn_number(i) << " " */
   /*                 << std::endl; */
   /*     } */
   /*    Data* data_pt=dynamic_cast<SolidNode*>(node_pt(j)) */
   /*     ->variable_position_pt(); */
   /*    nval=data_pt->nvalue(); */
   /*    for (unsigned i=0;i<nval;i++) */
   /*     { */
   /*      oomph_info << "i_pos, eqn_number: " << i << " "  */
   /*                 << data_pt->eqn_number(i) << " " */
   /*                 << std::endl; */
   /*     } */
   /*   } */
   /* } */
   //Set up memory for the shape functions
   //Note that in this case, the number of lagrangian coordinates is always
   //equal to the dimension of the nodes
   Shape psi(n_node,n_position_type);
   DShape dpsids(n_node,n_position_type,n_dim-1);
   //Set the value of n_intpt
   unsigned n_intpt = integral_pt()->nweight();
   //Loop over the integration points
   for(unsigned ipt=0;ipt<n_intpt;ipt++)
    {
     //Get the integral weight
     double w = integral_pt()->weight(ipt);
     //Only need to call the local derivatives
     dshape_local_at_knot(ipt,psi,dpsids);
     //Calculate the Eulerian and Lagrangian coordinates
     Vector<double> interpolated_x(n_dim,0.0);
     Vector<double> interpolated_dxdt(n_dim,0.0);
     Vector<double> interpolated_xi(n_dim,0.0);
     // Interpolated Lagrange multiplier (pressure acting on solid
     // to enforce melting)
     double interpolated_lambda_p=0.0;
     // Get temperature
     double u=0;
     // Melt rate
     double melt_rate=0.0;
     //Also calculate the surface Vectors (derivatives wrt local coordinates)
     DenseMatrix<double> interpolated_A(n_dim-1,n_dim,0.0);
     //Calculate stuff
     for(unsigned l=0;l<n_node;l++)
      {
       // Cast to a boundary node
       BoundaryNodeBase *bnod_pt =
        dynamic_cast<BoundaryNodeBase*>(node_pt(l));
       // Get the index of the first nodal value associated with
       // this FaceElement
       unsigned first_index=
        bnod_pt->index_of_first_value_assigned_by_face_element(Melt_id);
       // Add to Lagrange multiplier (acting as pressure on solid
       // to enforce melting motion)
       interpolated_lambda_p+=node_pt(l)->value(first_index)*psi[l];
       // Add to melt rate
       melt_rate+=node_pt(l)->value(first_index+1)*psi[l];
       // Add to temperature
       u+=node_pt(l)->value(this->U_index_ust_heat)*psi[l];
       //Loop over positional dofs
       for(unsigned k=0;k<n_position_type;k++)
        {
         //Loop over spatial dimension
         for(unsigned i=0;i<n_dim;i++)
          {
           //Calculate the Eulerian and Lagrangian positions
           interpolated_x[i] +=
            nodal_position_gen(l,bulk_position_type(k),i)*psi(l,k);
           interpolated_dxdt[i] +=
            this->dnodal_position_gen_dt(l,bulk_position_type(k),i)*psi(l,k);
           interpolated_xi[i] +=
            this->lagrangian_position_gen(l,bulk_position_type(k),i)*psi(l,k);
           //Loop over LOCAL derivative directions, to calculate the tangent(s)
           for(unsigned j=0;j<n_dim-1;j++)
            {
             interpolated_A(j,i) +=
              nodal_position_gen(l,bulk_position_type(k),i)*dpsids(l,k,j);
            }
          }
        }
      }
     //Now find the local deformed metric tensor from the tangent Vectors
     DenseMatrix<double> A(n_dim-1);
     for(unsigned i=0;i<n_dim-1;i++)
      {
       for(unsigned j=0;j<n_dim-1;j++)
        {
         //Initialise surface metric tensor to zero
         A(i,j) = 0.0;
         //Take the dot product
         for(unsigned k=0;k<n_dim;k++)
          {
           A(i,j) += interpolated_A(i,k)*interpolated_A(j,k);
          }
        }
      }
     // hierher replaced this in first sweep!
     //Get the outer unit normal
     Vector<double> interpolated_normal(n_dim);
     outer_unit_normal(ipt,interpolated_normal);
     // Local coordinate of integration point
     unsigned n_dim = this->nodal_dimension();
     Vector<double> s(n_dim-1);
     for (unsigned i=0;i<n_dim-1;i++)
      {
       s[i]=integral_pt()->knot(ipt,i);
      }
     /* // Outgoing Stefan Boltzmann radiative flux */
     /* //========================================= */
     /* double outgoing_stefan_boltzmann_flux=sigma()*pow((u+theta_0()),4); */
     /* // Incoming Stefan Boltzmann radiation */
     /* //==================================== */
     /* double incoming_sb_radiation=incoming_stefan_boltzmann_radiation */
     /*  (ipt,interpolated_x,interpolated_normal); */
     /* // Get the incoming atmospheric radiation */
     /* //======================================== */
     /* double incoming_atmospheric_radiation= */
     /*  atmospheric_radiation(ipt,time(),interpolated_x, */
     /*                        interpolated_normal); */
     /* // Get net heat flux  */
     /* //================== */
     /* double net_heat_flux=incoming_atmospheric_radiation+ */
     /*  incoming_sb_radiation-outgoing_stefan_boltzmann_flux; */
     //Get the imposed flux
     double flux=0.0;
     this->get_flux(ipt,time,interpolated_x,interpolated_normal,u,flux);
     // Calculate the "load" -- Lagrange multiplier acts as traction to
     //================================================================
     // to enforce required surface displacement
     //=========================================
     Vector<double> traction(n_dim);
     for (unsigned i=0;i<n_dim;i++)
      {
       traction[i]=-interpolated_lambda_p*interpolated_normal[i];
      }
     // Get normal velocity
     double normal_veloc=0.0;
     for (unsigned i=0;i<n_dim;i++)
      {
       normal_veloc+=interpolated_dxdt[i]*interpolated_normal[i];
      }
     //Find the determinant of the metric tensor
     double Adet =0.0;
     switch(n_dim)
      {
      case 2:
       Adet = A(0,0);
       break;
      case 3:
       Adet = A(0,0)*A(1,1) - A(0,1)*A(1,0);
       break;
      default:
       throw
        OomphLibError("Wrong dimension in SurfaceMeltElement",
                      OOMPH_CURRENT_FUNCTION,
                      OOMPH_EXCEPTION_LOCATION);
      }
     //Premultiply the weights and the square-root of the determinant of
     //the metric tensor
     double W = w*sqrt(Adet);
     //Loop over the test functions, nodes of the element
     for(unsigned l=0;l<n_node;l++)
      {
       // Contributions to bulk solid equations
       //--------------------------------------
       //Loop of types of dofs
       for(unsigned k=0;k<n_position_type;k++)
        {
         //Loop over the displacement components
         for(unsigned i=0;i<n_dim;i++)
          {
           local_eqn = this->position_local_eqn(l,bulk_position_type(k),i);
           if(local_eqn >= 0)
            {
             //Add the loading terms to the residuals
             residuals[local_eqn] -= traction[i]*psi(l,k)*W;
            }
          }
        } //End of if not boundary condition
       // Contributions to equation that determines the Lagrange multiplier
       //------------------------------------------------------------------
       // (pressure) from kinematic condition
       //------------------------------------
       // Cast to a boundary node
       BoundaryNodeBase *bnod_pt =
        dynamic_cast<BoundaryNodeBase*>(node_pt(l));
       // Get the index of the first nodal value associated with
       // this FaceElement
       unsigned first_index=
        bnod_pt->index_of_first_value_assigned_by_face_element(Melt_id);
       local_eqn=this->nodal_local_eqn(l,first_index);
       if (local_eqn>=0)
        {
         residuals[local_eqn]+=(normal_veloc+melt_rate)*psi[l]*W;
        }
       // Contribution to flux into bulk
       //-------------------------------
       local_eqn = nodal_local_eqn(l,this->U_index_ust_heat);
       if(local_eqn >= 0)
        {
         //Add the prescribed flux terms
         residuals[local_eqn] -= (flux-melt_rate)*psi[l]*W;
        }
      } //End of loop over shape functions
    } //End of loop over integration points
   // Collocation for melt rate:
   //---------------------------
   //Loop over the nodes
   for(unsigned l=0;l<n_node;l++)
    {
     // get the node pt
     Node* nod_pt = node_pt(l);
     // Cast to a boundary node
     BoundaryNodeBase *bnod_pt =
      dynamic_cast<BoundaryNodeBase*>(nod_pt);
     // Get the index of the first nodal value associated with
     // this FaceElement
     unsigned first_index=
      bnod_pt->index_of_first_value_assigned_by_face_element(Melt_id);
     // Melt rate equation is second added one
     local_eqn = nodal_local_eqn(l,first_index+1);
     /*IF it's not a boundary condition*/
     if(local_eqn >= 0)
      {
       double u=nod_pt->value(this->U_index_ust_heat);
       double melt_rate=nod_pt->value(first_index+1);
      // Piecewise linear variation
      if ((melt_temperature()-u)>melt_rate)
       {
        residuals[local_eqn]+=melt_rate;
       }
      else
       {
        residuals[local_eqn]+=(melt_temperature()-u);
       }
      }
    }
  }
References ProblemParameters::flux(), oomph::get_flux(), i, oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), j, k, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, s, sqrt(), oomph::Node::value(), w, and oomph::QuadTreeNames::W.
Referenced by oomph::SurfaceMeltElement< ELEMENT >::fill_in_contribution_to_residuals().
get_interpolated_lagrange_p()
template<class ELEMENT > double oomph::SurfaceMeltElement< ELEMENT >::get_interpolated_lagrange_p (const Vector< double > & s) inline
Get interpolated pressure (essentially a Lagrange multiplier that enforces the imposed boundary motion)
   {
    // Initialise pressure
    double p=0;
    //Find out how many nodes there are
    unsigned n_node = nnode();
    //Set up memory for the shape functions
    Shape psi(n_node);
    // Evaluate shape function
    shape(s,psi);
    // Build up Lagrange multiplier (pressure)
    for (unsigned j=0;j<n_node;j++)
     {
      // Cast to a boundary node
      BoundaryNodeBase *bnod_pt =
       dynamic_cast<BoundaryNodeBase*>(node_pt(j));
      // Get the index of the first nodal value associated with
      // this FaceElement
      unsigned first_index=
       bnod_pt->index_of_first_value_assigned_by_face_element(Melt_id);
      // Pressure (Lagrange multiplier) is the first of two additional
      // values created by this face element
      p+=node_pt(j)->value(first_index)*psi[j];
     }
    return p;
   }
References oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), j, oomph::SurfaceMeltElement< ELEMENT >::Melt_id, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), p, s, oomph::FiniteElement::shape(), and oomph::Node::value().
Referenced by oomph::SurfaceMeltElement< ELEMENT >::output_melt().
interpolated_melt_rate()
template<class ELEMENT > void oomph::SurfaceMeltElement< ELEMENT >::interpolated_melt_rate (const Vector< double > & s, double & melt_flux) inline
Melt rate at local coordinate s.
  {
   // Iinitialise
   melt_flux=0.0;
   //Find out how many nodes there are
   const unsigned n_node = nnode();
   //Set up memory for the shape functions
   Shape psi(n_node);
   // Get shape fct
   shape(s,psi);
   //Calculate stuff
   for(unsigned l=0;l<n_node;l++)
    {
     // get the node pt
     Node* nod_pt = node_pt(l);
     // Cast to a boundary node
     BoundaryNodeBase *bnod_pt = dynamic_cast<BoundaryNodeBase*>(nod_pt);
     // Get the index of the first nodal value associated with
     // this FaceElement
     unsigned first_index=
      bnod_pt->index_of_first_value_assigned_by_face_element(Melt_id);
     // Melt rate
     melt_flux+=nod_pt->value(first_index+1)*psi[l];
    }
  }
References oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), GlobalParameters::melt_flux(), oomph::SurfaceMeltElement< ELEMENT >::Melt_id, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), s, oomph::FiniteElement::shape(), and oomph::Node::value().
Referenced by StefanBoltzmannProblem< ELEMENT >::doc_solution(), and oomph::SurfaceMeltElement< ELEMENT >::output_melt().
melt_temperature()
template<class ELEMENT > double oomph::SurfaceMeltElement< ELEMENT >::melt_temperature () inline
Melt temperature.
   {
    if (Melt_temperature_pt==0)
     {
      return 0.0;
     }
    else
     {
      return *Melt_temperature_pt;
     }
   }
References oomph::SurfaceMeltElement< ELEMENT >::Melt_temperature_pt.
melt_temperature_pt()
template<class ELEMENT > double*& oomph::SurfaceMeltElement< ELEMENT >::melt_temperature_pt () inline
Pointer to (non-default) melt temperature.
   {
    return Melt_temperature_pt;
   }
References oomph::SurfaceMeltElement< ELEMENT >::Melt_temperature_pt.
Referenced by MeltContactProblem< ELEMENT >::complete_problem_setup(), UnsteadyHeatMeltProblem< ELEMENT >::complete_problem_setup(), and StefanBoltzmannProblem< ELEMENT >::create_melt_elements().
output_melt()
template<class ELEMENT > void oomph::SurfaceMeltElement< ELEMENT >::output_melt (std::ostream & outfile) inline
Generalised output function to include melt information: temperature, incoming flux, melt rate, outer unit normal
  {
   unsigned n_dim = this->nodal_dimension();
   Vector<double> x(n_dim);
   Vector<double> s(n_dim-1);
   Vector<double> unit_normal(n_dim);
   // Get continuous time from timestepper of first node
   double time=node_pt(0)->time_stepper_pt()->time_pt()->time();
   // Number of integration points
   unsigned n_intpt = integral_pt()->nweight();
   outfile << "ZONE\n";
   //Loop over the integration points
   for(unsigned ipt=0;ipt<n_intpt;ipt++)
    {
     // Local coordinate of integration point
     for (unsigned i=0;i<n_dim-1;i++)
      {
       s[i]=integral_pt()->knot(ipt,i);
      }
     // Get Eulerian coordinates
     this->interpolated_x(s,x);
     // Get temperature
     double interpolated_u=0;
     this->interpolated_u(s,interpolated_u);
     // Outer unit normal
     outer_unit_normal(s,unit_normal);
     // Get melt rate
     double interpolated_m=0.0;
     this->interpolated_melt_rate(s,interpolated_m);
     // Get "lagrange multiplier" pressure
     double lagrange_p=get_interpolated_lagrange_p(s);
     //Get the incoming flux
     double flux=0.0;
     this->get_flux(ipt,time,x,unit_normal,interpolated_u,flux);
     //Output the x,y,..
     for(unsigned i=0;i<n_dim;i++)
      {
       outfile << x[i] << " ";
      }
     // Temperature
     outfile << interpolated_u << " ";
     // Incoming flux
     outfile << flux << " ";
     // Melt rate
     outfile << interpolated_m << " ";
     // Lagrange multiplier-like pressure
     outfile << lagrange_p << " ";
     // Outer unit normal
     for(unsigned i=0;i<n_dim;i++)
      {
       outfile << unit_normal[i] << " ";
      }
     outfile << std::endl;
    }
  }
References ProblemParameters::flux(), oomph::TemplateFreeUnsteadyHeatBaseFaceElement::get_flux(), oomph::SurfaceMeltElement< ELEMENT >::get_interpolated_lagrange_p(), i, oomph::FiniteElement::integral_pt(), oomph::SurfaceMeltElement< ELEMENT >::interpolated_melt_rate(), oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::interpolated_u(), oomph::FaceElement::interpolated_x(), oomph::Integral::knot(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), s, oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Data::time_stepper_pt(), and plotDoE::x.
Referenced by StefanBoltzmannProblem< ELEMENT >::doc_solution().
set_lagrange_multiplier_pressure_to_zero()
template<class ELEMENT > void oomph::SurfaceMeltElement< ELEMENT >::set_lagrange_multiplier_pressure_to_zero () inline
Set "Lagrange multiplier pressure" to zero (to make things consistent with re-set Lagrangian coordinates
   {
    unsigned n_node=nnode();
    for(unsigned l=0;l<n_node;l++)
     {
      // get the node pt
      Node* nod_pt = node_pt(l);
      // Cast to a boundary node
      BoundaryNodeBase *bnod_pt =
       dynamic_cast<BoundaryNodeBase*>(nod_pt);
      // Get the index of the first nodal value associated with
      // this FaceElement
      unsigned first_index=
       bnod_pt->index_of_first_value_assigned_by_face_element(Melt_id);
      // Lagrange multiplier is first additional value created by this
      // face element)
      nod_pt->set_value(first_index,0.0);
     }
   }
References oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), oomph::SurfaceMeltElement< ELEMENT >::Melt_id, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::Data::set_value().
Referenced by UnsteadyHeatMeltProblem< ELEMENT >::actions_after_adapt(), MeltContactProblem< ELEMENT >::complete_problem_setup(), and UnsteadyHeatMeltProblem< ELEMENT >::complete_problem_setup().
zeta_nodal()
template<class ELEMENT > double oomph::SurfaceMeltElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const inline virtual
Specify the value of nodal zeta from the face geometry: The "global" intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Reimplemented from oomph::UnsteadyHeatBaseFaceElement< ELEMENT >.
Reimplemented in StefanBoltzmannMeltElement< ELEMENT >.
   {return FaceElement::zeta_nodal(n,k,i);}
References i, k, n, and oomph::FaceElement::zeta_nodal().
Member Data Documentation
Melt_id
template<class ELEMENT > unsigned oomph::SurfaceMeltElement< ELEMENT >::Melt_id protected
Id of additional unknowns (Lagrange multiplier ("pressure") and melt rate)
Referenced by oomph::SurfaceMeltElement< ELEMENT >::disable_melting(), oomph::SurfaceMeltElement< ELEMENT >::get_interpolated_lagrange_p(), oomph::SurfaceMeltElement< ELEMENT >::interpolated_melt_rate(), oomph::SurfaceMeltElement< ELEMENT >::set_lagrange_multiplier_pressure_to_zero(), and oomph::SurfaceMeltElement< ELEMENT >::SurfaceMeltElement().
Melt_temperature_pt
template<class ELEMENT > double* oomph::SurfaceMeltElement< ELEMENT >::Melt_temperature_pt protected
Pointer to non-default melt temperature.
Referenced by oomph::SurfaceMeltElement< ELEMENT >::melt_temperature(), oomph::SurfaceMeltElement< ELEMENT >::melt_temperature_pt(), and oomph::SurfaceMeltElement< ELEMENT >::SurfaceMeltElement().
The documentation for this class was generated from the following file:
heat_transfer_and_melt_elements.h