MercuryDPM: ABCProblem< ELEMENT, TIMESTEPPERT > Class Template Reference
ABCProblem< ELEMENT, TIMESTEPPERT > Class Template Reference
Public Member Functions
ABCProblem ()
Problem * make_copy ()
Make a copy for using in bifurcation tracking.
void actions_after_newton_solve ()
void actions_before_newton_solve ()
void actions_before_newton_convergence_check ()
void solve ()
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
virtual void actions_before_adapt ()
virtual void actions_after_adapt ()
Actions that are to be performed after a mesh adaptation.
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Private Attributes
unsigned count
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_before_implicit_timestep ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual void set_initial_condition ()
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Constructor & Destructor Documentation
ABCProblem()
template<class ELEMENT , class TIMESTEPPER > ABCProblem< ELEMENT, TIMESTEPPER >::ABCProblem
 {
  count=0;
  //Asssign the timestepper
  add_time_stepper_pt(new TIMESTEPPER);
  eigen_solver_pt() = new LAPACK_QZ();
  //Now create the mesh
  Problem::mesh_pt() = new Mesh;
  //Single element
  ELEMENT* elem_pt = new ELEMENT;
  //Create the internal data
  elem_pt->construct_internal_data(this->time_stepper_pt());
  //Add the element to the mesh
  mesh_pt()->add_element_pt(elem_pt);
  //Assign the physical parameters
  using namespace Global_Physical_Variables;
  //Set the load function
  elem_pt->p_pt() = &P;
  elem_pt->internal_data_pt(0)->set_value(0,0.5);
  elem_pt->internal_data_pt(0)->set_value(1,0.5);
  elem_pt->internal_data_pt(0)->set_value(2,2.0);
  cout << assign_eqn_numbers() << " Equation numbers assigned" << std::endl;
 }
References oomph::Mesh::add_element_pt(), and Global_Physical_Variables::P().
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT , class TIMESTEPPERT > void ABCProblem< ELEMENT, TIMESTEPPERT >::actions_after_newton_solve () inline virtual
Any actions that are to be performed after a complete Newton solve, e.g. post processing. CAREFUL: This step should (and if the FD-based LinearSolver FD_LU is used, must) only update values that are pinned!
Reimplemented from oomph::Problem.
 {}
actions_before_newton_convergence_check()
template<class ELEMENT , class TIMESTEPPERT > void ABCProblem< ELEMENT, TIMESTEPPERT >::actions_before_newton_convergence_check () inline virtual
Any actions that are to be performed before the residual is checked in the Newton method, e.g. update any boundary conditions that depend upon variables of the problem; update any ‘dependent’ variables; or perform an update of the nodal positions in SpineMeshes etc. CAREFUL: This step should (and if the FD-based LinearSolver FD_LU is used, must) only update values that are pinned!
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve()
template<class ELEMENT , class TIMESTEPPERT > void ABCProblem< ELEMENT, TIMESTEPPERT >::actions_before_newton_solve () inline virtual
Any actions that are to be performed before a complete Newton solve (e.g. adjust boundary conditions). CAREFUL: This step should (and if the FD-based LinearSolver FD_LU is used, must) only update values that are pinned!
Reimplemented from oomph::Problem.
 {}
make_copy()
template<class ELEMENT , class TIMESTEPPERT > Problem* ABCProblem< ELEMENT, TIMESTEPPERT >::make_copy () inline virtual
Make a copy for using in bifurcation tracking.
Reimplemented from oomph::Problem.
   {
    //Make a copy based on the current parameters
    return(new ABCProblem());
   }
solve()
template<class ELEMENT , class TIMESTEPPER > void ABCProblem< ELEMENT, TIMESTEPPER >::solve
 {
  //Assign memory for the eigenvalues and eigenvectors
  Vector<std::complex<double> > eigenvalues;
  Vector< DoubleVector > eigenvectors;
  Desired_newton_iterations_ds = 2;
  Desired_proportion_of_arc_length = 0.5;
  //Open an output trace file
  ofstream trace("trace.dat");
  double ds = 0.01;
  //Let's have a look at the solution
  for(unsigned i=0;i<13;i++)
   {
    //Take some arc-length steps, but ignore the return value
    /*ds = */arc_length_step_solve(&Global_Physical_Variables::P[0],ds);
    //Output the pressure
    trace << Global_Physical_Variables::P[0]  << " "
          << mesh_pt()->element_pt(0)->internal_data_pt(0)->value(0)
          << " "
          << mesh_pt()->element_pt(0)->internal_data_pt(0)->value(1)
          << " "
          << mesh_pt()->element_pt(0)->internal_data_pt(0)->value(2)
          << std::endl;
    this->solve_eigenproblem(3,eigenvalues,eigenvectors);
    for(unsigned e=0;e<eigenvalues.size();e++)
     {
      std::cout << eigenvalues[e] << std::endl;
     }
   }
  trace.close();
  //Now let's track the Hopf
  activate_hopf_tracking(&Global_Physical_Variables::P[0],
                         eigenvalues[0].imag(),
                         eigenvectors[0],eigenvectors[1]);
  this->steady_newton_solve();
  std::cout << "Hopf bifurcation found at "
            << Global_Physical_Variables::P[0]  << " "
            << dof(ndof()-1) << " "
            << mesh_pt()->element_pt(0)->internal_data_pt(0)->value(0)
            << " "
            << mesh_pt()->element_pt(0)->internal_data_pt(0)->value(1)
            << " "
            << mesh_pt()->element_pt(0)->internal_data_pt(0)->value(2)
            << std::endl;
  //Store the frequency
  double omega = dof(ndof()-1);
  //Go back to normal problem
  this->deactivate_bifurcation_tracking();
  //Increment the parameter a little bit
  Global_Physical_Variables::P[0] += 0.001;
  //Solve for the steady state
  this->steady_newton_solve();
  unsigned n_time_element=50;//200;
  //Find out how many time points we'd want
  Vector<double> time_point;
  {
   Mesh* temp_mesh_pt =
    new OneDMesh<QSpectralElement<1,7> >(n_time_element,1.0);
   const unsigned n_node = temp_mesh_pt->nnode();
   time_point.resize(n_node);
   for(unsigned n=0;n<n_node;n++)
    {
     time_point[n] = temp_mesh_pt->node_pt(n)->x(0);
    }
  }
  //Now assume we've been where we are for all time
  double period = (8.0*atan(1.0))/omega;
  double dt = 0.05*period;
  assign_initial_values_impulsive(dt);
  //Add a tiny kick
  double u = mesh_pt()->element_pt(0)->internal_data_pt(0)->value(0);
  mesh_pt()->element_pt(0)->internal_data_pt(0)->set_value(0,u*1.01);
  trace.open("time_trace.dat");
  //Output the details
  trace << time() << " "
        << mesh_pt()->element_pt(0)->internal_data_pt(0)->value(0)
        << " "
        << mesh_pt()->element_pt(0)->internal_data_pt(0)->value(1)
        << " "
        << mesh_pt()->element_pt(0)->internal_data_pt(0)->value(2)
        << std::endl;
  //Integrate over 10 putative periods and then start storing stuff
  //Let's have a look at the solution
  for(unsigned i=0;i<200;i++)
   {
    unsteady_newton_solve(dt);
    //Output the pressure
    trace << time() << " "
          << mesh_pt()->element_pt(0)->internal_data_pt(0)->value(0)
          << " "
          << mesh_pt()->element_pt(0)->internal_data_pt(0)->value(1)
          << " "
          << mesh_pt()->element_pt(0)->internal_data_pt(0)->value(2)
          << std::endl;
   }
  trace.close();
  //OK let's do this
  const unsigned n_time = time_point.size();
  const unsigned n_dof = this->ndof();
  DenseMatrix<double> initial_guess(n_time,n_dof);
  for(unsigned n=0;n<n_dof;n++)
   {
    initial_guess(0,n) = this->dof(n);
   }
  //Take a timestep
  //period = 8.4;
  for(unsigned t=1;t<n_time;t++)
   {
    dt = period*(time_point[t] - time_point[t-1]);
    unsteady_newton_solve(dt);
    for(unsigned n=0;n<n_dof;n++)
     {
      initial_guess(t,n) = this->dof(n);
     }
   }
  //Have now setup the initial guess time to try the timestepping again
  //Pepare a periodic orbit handler
  assembly_handler_pt() = new PeriodicOrbitAssemblyHandler<7>(this,
                                                              n_time_element,
                                                              initial_guess,
                                                              8.0*atan(1.0)/
                                                              period);
  //Now let's setup the initial values
  this->newton_solve();
  Max_newton_iterations = 100;
  std::cout << "Orbit found with period " << 1.0/
   this->dof(this->ndof()-1) << "\n";
  //Output
  std::ofstream junk("first_orbit.dat");
  dynamic_cast<PeriodicOrbitAssemblyHandler<7>*>(assembly_handler_pt())
   ->orbit_output(junk,5);
  junk.close();
  dynamic_cast<PeriodicOrbitAssemblyHandler<7>*>(
   assembly_handler_pt())->set_previous_dofs_to_current_dofs();
  std::ofstream orbit_trace("orbit_trace.dat");
  Max_newton_iterations = 10;
  Desired_proportion_of_arc_length = 0.01;
  //Now we can continue the orbit!
  char filename[100];
  ds = 0.0005;
  unsigned count=0;
  for(unsigned i=0;i<2;i++)
   {
    ++count;
    std::cout << "Taking ds " << ds << "\n";
    ds = this->arc_length_step_solve(&Global_Physical_Variables::P[0],ds);
    dynamic_cast<PeriodicOrbitAssemblyHandler<7>*>(
     assembly_handler_pt())->set_previous_dofs_to_current_dofs();
    sprintf(filename,"orbit%g_%g.dat",Global_Physical_Variables::P[0],
            1.0/this->dof(this->ndof()-1));
    std::ofstream crap(filename);
    dynamic_cast<PeriodicOrbitAssemblyHandler<7>*>(assembly_handler_pt())
     ->orbit_output(crap,5);
    crap.close();
    orbit_trace << Global_Physical_Variables::P[0] << " "
                << this->dof(this->ndof()-1) << " "
                << this->mesh_pt()->element_pt(0)->internal_data_pt(0)->value(10,0) << " "
                << this->mesh_pt()->element_pt(0)->internal_data_pt(0)->value(10,1) << " "
                << this->mesh_pt()->element_pt(0)->internal_data_pt(0)->value(10,2) << std::endl;
   }
  orbit_trace.close();
 }
References Eigen::bfloat16_impl::atan(), e(), MergeRestartFiles::filename, i, imag(), oomph::Locate_zeta_helpers::Max_newton_iterations, n, oomph::Mesh::nnode(), oomph::Mesh::node_pt(), Eigen::internal::omega(), Global_Physical_Variables::P, plotPSD::t, and oomph::Node::x().
Member Data Documentation
count
template<class ELEMENT , class TIMESTEPPERT > unsigned ABCProblem< ELEMENT, TIMESTEPPERT >::count private
The documentation for this class was generated from the following file:
periodic_orbit.cc