MercuryDPM: Eigen::MatrixLogarithmReturnValue< Derived > Class Template Reference
Eigen::MatrixLogarithmReturnValue< Derived > Class Template Reference
Proxy for the matrix logarithm of some matrix (expression).
#include <MatrixLogarithm.h>
Public Types
typedef Derived::Scalar Scalar
typedef Derived::Index Index
Public Types inherited from Eigen::ReturnByValue< MatrixLogarithmReturnValue< Derived > >
typedef internal::traits< MatrixLogarithmReturnValue< Derived > >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Public Member Functions
MatrixLogarithmReturnValue (const Derived &A)
Constructor.
template<typename ResultType >
void evalTo (ResultType &result) const
Compute the matrix logarithm.
Index rows () const
Index cols () const
Public Member Functions inherited from Eigen::ReturnByValue< MatrixLogarithmReturnValue< Derived > >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Protected Types
typedef internal::ref_selector< Derived >::type DerivedNested
Private Attributes
const DerivedNested m_A
Detailed Description
template<typename Derived>
class Eigen::MatrixLogarithmReturnValue< Derived >
Proxy for the matrix logarithm of some matrix (expression).
Template Parameters
Derived Type of the argument to the matrix function.
This class holds the argument to the matrix function until it is assigned or evaluated for some other reason (so the argument should not be changed in the meantime). It is the return type of MatrixBase::log() and most of the time this is the only way it is used.
Member Typedef Documentation
DerivedNested
template<typename Derived > typedef internal::ref_selector<Derived>::type Eigen::MatrixLogarithmReturnValue< Derived >::DerivedNested protected
Index
template<typename Derived > typedef Derived::Index Eigen::MatrixLogarithmReturnValue< Derived >::Index
Scalar
template<typename Derived > typedef Derived::Scalar Eigen::MatrixLogarithmReturnValue< Derived >::Scalar
Constructor & Destructor Documentation
MatrixLogarithmReturnValue()
template<typename Derived > Eigen::MatrixLogarithmReturnValue< Derived >::MatrixLogarithmReturnValue (const Derived & A) inline explicit
Constructor.
Parameters
[in] A Matrix (expression) forming the argument of the matrix logarithm.
 : m_A(A) {}
Member Function Documentation
cols()
template<typename Derived > Index Eigen::MatrixLogarithmReturnValue< Derived >::cols () const inline
 { return m_A.cols(); }
References Eigen::MatrixLogarithmReturnValue< Derived >::m_A.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
evalTo()
template<typename Derived > template<typename ResultType > void Eigen::MatrixLogarithmReturnValue< Derived >::evalTo (ResultType & result) const inline
Compute the matrix logarithm.
Parameters
[out] result Logarithm of A, where A is as specified in the constructor.
{
     typedef typename internal::nested_eval<Derived, 10>::type DerivedEvalType;
     typedef internal::remove_all_t<DerivedEvalType> DerivedEvalTypeClean;
     typedef internal::traits<DerivedEvalTypeClean> Traits;
     typedef std::complex<typename NumTraits<Scalar>::Real> ComplexScalar;
     typedef Matrix<ComplexScalar, Dynamic, Dynamic, 0, Traits::RowsAtCompileTime, Traits::ColsAtCompileTime>
         DynMatrixType;
     typedef internal::MatrixLogarithmAtomic<DynMatrixType> AtomicType;
     AtomicType atomic;
     internal::matrix_function_compute<typename DerivedEvalTypeClean::PlainObject>::run(m_A, atomic, result);
   }
References Eigen::MatrixLogarithmReturnValue< Derived >::m_A, and Eigen::internal::matrix_function_compute< MatrixType, IsComplex >::run().
rows()
template<typename Derived > Index Eigen::MatrixLogarithmReturnValue< Derived >::rows () const inline
 { return m_A.rows(); }
References Eigen::MatrixLogarithmReturnValue< Derived >::m_A.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_A
template<typename Derived > const DerivedNested Eigen::MatrixLogarithmReturnValue< Derived >::m_A private
Referenced by Eigen::MatrixLogarithmReturnValue< Derived >::cols(), Eigen::MatrixLogarithmReturnValue< Derived >::evalTo(), and Eigen::MatrixLogarithmReturnValue< Derived >::rows().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
MatrixLogarithm.h