MercuryDPM: oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement Class Reference
oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement Class Reference
GeneralisedNewtonianAxisymmetricTCrouzeix_Raviart elements are.
#include <generalised_newtonian_Taxisym_navier_stokes_elements.h>
Public Member Functions
void pshape_axi_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
void unpin_all_internal_pressure_dofs ()
Unpin all internal pressure dofs.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement ()
Constructor, there are 3 internal values (for the pressure)
GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement (const GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement &dummy)=delete
Broken copy constructor.
void operator= (const GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement &)=delete
Broken assignment operator.
virtual unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at local node n.
double p_axi_nst (const unsigned &i) const
unsigned npres_axi_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void identify_load_data (std::set< std::pair< Data *, unsigned >> &paired_load_data)
void identify_pressure_data (std::set< std::pair< Data *, unsigned >> &paired_pressure_data)
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
unsigned nrecovery_order ()
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
unsigned ndof_types () const
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::TBubbleEnrichedElement< 2, 3 >
const unsigned Central_node_on_face [3]
const unsigned Central_node_on_face [4]
void build_face_element (const int &face_index, FaceElement *face_element_pt)
The face element for is the same in the two-dimesional case.
void build_face_element (const int &face_index, FaceElement *face_element_pt)
Public Member Functions inherited from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations
GeneralisedNewtonianAxisymmetricNavierStokesEquations ()
Constructor: NULL the body force and source function.
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const double & re_invro () const
Global Reynolds number multiplied by inverse Rossby number.
double *& re_invro_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
GeneralisedNewtonianConstitutiveEquation< 3 > *& constitutive_eqn_pt ()
Access function for the constitutive equation pointer.
void use_current_strainrate_to_compute_second_invariant ()
Switch to fully implict evaluation of non-Newtonian const eqn.
void use_extrapolated_strainrate_to_compute_second_invariant ()
Use extrapolation for non-Newtonian const eqn.
virtual unsigned u_index_axi_nst (const unsigned &i) const
unsigned u_index_nst (const unsigned &i) const
unsigned n_u_nst () const
double du_dt_axi_nst (const unsigned &n, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
virtual int p_nodal_index_axi_nst () const
Which nodal value represents the pressure?
double pressure_integral () const
Integral of pressure over element.
void max_and_min_invariant_and_viscosity (double &min_invariant, double &max_invariant, double &min_viscosity, double &max_viscosity) const
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
void strain_rate (const unsigned &t, const Vector< double > &s, DenseMatrix< double > &strain_rate) const
virtual void extrapolated_strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
virtual void extrapolated_strain_rate (const unsigned &ipt, DenseMatrix< double > &strain_rate) const
void traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction) const
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
std::string scalar_name_paraview (const unsigned &i) const
void point_output_data (const Vector< double > &s, Vector< double > &data)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Compute the element's residual Vector.
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
void interpolated_u_axi_nst (const Vector< double > &s, Vector< double > &veloc) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_axi_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_axi_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
virtual void dinterpolated_u_axi_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
double interpolated_p_axi_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_duds_axi_nst (const Vector< double > &s, const unsigned &i, const unsigned &j) const
double interpolated_dudx_axi_nst (const Vector< double > &s, const unsigned &i, const unsigned &j) const
double interpolated_dudt_axi_nst (const Vector< double > &s, const unsigned &i) const
double interpolated_d_dudx_dX_axi_nst (const Vector< double > &s, const unsigned &p, const unsigned &q, const unsigned &i, const unsigned &k) const
double compute_physical_size () const
Compute the volume of the element.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::NavierStokesElementWithDiagonalMassMatrices
NavierStokesElementWithDiagonalMassMatrices ()
Empty constructor.
virtual ~NavierStokesElementWithDiagonalMassMatrices ()
Virtual destructor.
NavierStokesElementWithDiagonalMassMatrices (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken copy constructor.
void operator= (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken assignment operator.
Public Member Functions inherited from oomph::ElementWithZ2ErrorEstimator
ElementWithZ2ErrorEstimator ()
Default empty constructor.
ElementWithZ2ErrorEstimator (const ElementWithZ2ErrorEstimator &)=delete
Broken copy constructor.
void operator= (const ElementWithZ2ErrorEstimator &)=delete
Broken assignment operator.
virtual unsigned ncompound_fluxes ()
virtual void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
virtual void get_Z2_compound_flux_indices (Vector< unsigned > &flux_index)
virtual double geometric_jacobian (const Vector< double > &x)
Protected Member Functions
double dshape_and_dtest_eulerian_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
double dpshape_and_dptest_eulerian_axi_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Protected Member Functions inherited from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations
virtual void get_body_force_axi_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
Calculate the body force fct at a given time and Eulerian position.
virtual void get_body_force_gradient_axi_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
double get_source_fct (const double &time, const unsigned &ipt, const Vector< double > &x)
Calculate the source fct at given time and Eulerian position.
virtual void get_source_fct_gradient (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
virtual void get_viscosity_ratio_axisym_nst (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, double &visc_ratio)
virtual void fill_in_generic_residual_contribution_axi_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
virtual void fill_in_generic_dresidual_contribution_axi_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, unsigned flag)
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes
unsigned P_axi_nst_internal_index
Protected Attributes inherited from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
double * ReInvFr_pt
double * ReInvRo_pt
Vector< double > * G_pt
Pointer to global gravity Vector.
void(* Body_force_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
Pointer to body force function.
double(* Source_fct_pt)(const double &time, const Vector< double > &x)
Pointer to volumetric source function.
GeneralisedNewtonianConstitutiveEquation< 3 > * Constitutive_eqn_pt
Pointer to the generalised Newtonian constitutive equation.
bool Use_extrapolated_strainrate_to_compute_second_invariant
bool ALE_is_disabled
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Attributes inherited from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations
void(*&)(const double &time, const Vector< double > &x, Vector< double > &f) axi_nst_body_force_fct_pt ()
Access function for the body-force pointer.
double(*&)(const double &time, const Vector< double > &x) source_fct_pt ()
Access function for the source-function pointer.
Static Public Attributes inherited from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Attributes inherited from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations
static bool Pre_multiply_by_viscosity_ratio
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
GeneralisedNewtonianAxisymmetricTCrouzeix_Raviart elements are.
/////////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////// interpolation for velocities and positions enriched by a single cubic bubble function, but a discontinuous linear pressure interpolation
Constructor & Destructor Documentation
GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement() [1/2]
oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement () inline
Constructor, there are 3 internal values (for the pressure)
       : TBubbleEnrichedElement<2, 3>(),
         GeneralisedNewtonianAxisymmetricNavierStokesEquations()
     {
       // Allocate and a single internal datum with 3 entries for the
       // pressure
       P_axi_nst_internal_index = this->add_internal_data(new Data(3));
     }
References oomph::GeneralisedElement::add_internal_data(), and P_axi_nst_internal_index.
GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement() [2/2]
oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement (const GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement & dummy) delete
Broken copy constructor.
Member Function Documentation
dpshape_and_dptest_eulerian_axi_nst()
double oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::dpshape_and_dptest_eulerian_axi_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const inline protected
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
2D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
   {
     // Initalise with shape fcts and derivs. w.r.t. to local coordinates
     ppsi[0] = 1.0;
     ppsi[1] = s[0];
     ppsi[2] = s[1];
     dppsidx(0, 0) = 0.0;
     dppsidx(1, 0) = 1.0;
     dppsidx(2, 0) = 0.0;
     dppsidx(0, 1) = 0.0;
     dppsidx(1, 1) = 0.0;
     dppsidx(2, 1) = 1.0;
     // Get the values of the shape functions and their local derivatives
     Shape psi(7);
     DShape dpsi(7, 2);
     dshape_local(s, psi, dpsi);
     // Allocate memory for the inverse 2x2 jacobian
     DenseMatrix<double> inverse_jacobian(2);
     // Now calculate the inverse jacobian
     const double det = local_to_eulerian_mapping(dpsi, inverse_jacobian);
     // Now set the values of the derivatives to be derivs w.r.t. to the
     // Eulerian coordinates
     transform_derivatives(inverse_jacobian, dppsidx);
     // The test functions are equal to the shape functions
     ptest = ppsi;
     dptestdx = dppsidx;
     // Return the determinant of the jacobian
     return det;
   }
References oomph::FiniteElement::dshape_local(), oomph::FiniteElement::local_to_eulerian_mapping(), s, and oomph::FiniteElement::transform_derivatives().
dshape_and_dtest_eulerian_at_knot_axi_nst() [1/2]
double oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const inline protected virtual
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
   {
     // Call the geometrical shape functions and derivatives
     const double J = this->dshape_eulerian_at_knot(
       ipt, psi, dpsidx, djacobian_dX, d_dpsidx_dX);
     // Set the test functions equal to the shape functions
     test = psi;
     dtestdx = dpsidx;
     d_dtestdx_dX = d_dpsidx_dX;
     // Return the jacobian
     return J;
   }
References oomph::FiniteElement::dshape_eulerian_at_knot(), and J.
dshape_and_dtest_eulerian_at_knot_axi_nst() [2/2]
double oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const inline protected virtual
Velocity shape and test functions and their derivs w.r.t. to global coords at ipt-th integation point (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t. to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
   {
     // Call the geometrical shape functions and derivatives
     double J = this->dshape_eulerian_at_knot(ipt, psi, dpsidx);
     // The test functions are the shape functions
     test = psi;
     dtestdx = dpsidx;
     // Return the jacobian
     return J;
   }
References oomph::FiniteElement::dshape_eulerian_at_knot(), and J.
dshape_and_dtest_eulerian_axi_nst()
double oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::dshape_and_dtest_eulerian_axi_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const inline protected virtual
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t. to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
   {
     // Call the geometrical shape functions and derivatives
     double J = this->dshape_eulerian(s, psi, dpsidx);
     // The test functions are equal to the shape functions
     test = psi;
     dtestdx = dpsidx;
     // Return the jacobian
     return J;
   }
References oomph::FiniteElement::dshape_eulerian(), and J.
fix_pressure()
void oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::fix_pressure (const unsigned & p_dof, const double & p_value) inline
Pin p_dof-th pressure dof and set it to value specified by p_value.
     {
       this->internal_data_pt(P_axi_nst_internal_index)->pin(p_dof);
       this->internal_data_pt(P_axi_nst_internal_index)
         ->set_value(p_dof, p_value);
     }
References oomph::GeneralisedElement::internal_data_pt(), oomph::Data::pin(), and oomph::Data::set_value().
get_dof_numbers_for_unknowns()
void oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> & dof_lookup_list) const inline virtual
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the "DOF type" that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Velocity=0; Pressure=1
Reimplemented from oomph::GeneralisedElement.
     {
       // number of nodes
       unsigned n_node = this->nnode();
       // number of pressure values
       unsigned n_press = this->npres_axi_nst();
       // temporary pair (used to store dof lookup prior to being added to list)
       std::pair<unsigned, unsigned> dof_lookup;
       // pressure dof number
       unsigned pressure_dof_number = 3;
       // loop over the pressure values
       for (unsigned n = 0; n < n_press; n++)
       {
         // determine local eqn number
         int local_eqn_number = this->p_local_eqn(n);
         // ignore pinned values - far away degrees of freedom resulting
         // from hanging nodes can be ignored since these are be dealt
         // with by the element containing their master nodes
         if (local_eqn_number >= 0)
         {
           // store dof lookup in temporary pair: First entry in pair
           // is global equation number; second entry is dof type
           dof_lookup.first = this->eqn_number(local_eqn_number);
           dof_lookup.second = pressure_dof_number;
           // add to list
           dof_lookup_list.push_front(dof_lookup);
         }
       }
       // loop over the nodes
       for (unsigned n = 0; n < n_node; n++)
       {
         // find the number of values at this node
         unsigned nv = this->node_pt(n)->nvalue();
         // loop over these values
         for (unsigned v = 0; v < nv; v++)
         {
           // determine local eqn number
           int local_eqn_number = this->nodal_local_eqn(n, v);
           // ignore pinned values
           if (local_eqn_number >= 0)
           {
             // store dof lookup in temporary pair: First entry in pair
             // is global equation number; second entry is dof type
             dof_lookup.first = this->eqn_number(local_eqn_number);
             dof_lookup.second = v;
             // add to list
             dof_lookup_list.push_front(dof_lookup);
           }
         }
       }
     }
References oomph::GeneralisedElement::eqn_number(), oomph::GeneralisedElement::local_eqn_number(), n, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), npres_axi_nst(), oomph::Data::nvalue(), p_local_eqn(), and v.
get_Z2_flux()
void oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) inline virtual
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
 #ifdef PARANOID
       unsigned num_entries = 6;
       if (flux.size() < num_entries)
       {
         std::ostringstream error_message;
         error_message << "The flux vector has the wrong number of entries, "
                       << flux.size() << ", whereas it should be at least "
                       << num_entries << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Get strain rate matrix
       DenseMatrix<double> strainrate(3);
       this->strain_rate(s, strainrate);
       // Pack into flux Vector
       unsigned icount = 0;
       // Start with diagonal terms
       for (unsigned i = 0; i < 3; i++)
       {
         flux[icount] = strainrate(i, i);
         icount++;
       }
       // Off diagonals row by row
       for (unsigned i = 0; i < 3; i++)
       {
         for (unsigned j = i + 1; j < 3; j++)
         {
           flux[icount] = strainrate(i, j);
           icount++;
         }
       }
     }
References ProblemParameters::flux(), i, j, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::strain_rate().
identify_load_data()
void oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::identify_load_data (std::set< std::pair< Data *, unsigned >> & paired_load_data)
Add to the set paired_load_data pairs of pointers to data objects and unsignedegers that index the values in the data object that affect the load (traction), as specified in the get_load() function.
Add to the set paired_load_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
   {
     // Find the index at which the velocity is stored
     unsigned u_index[3];
     for (unsigned i = 0; i < 3; i++)
     {
       u_index[i] = this->u_index_axi_nst(i);
     }
     // Loop over the nodes
     unsigned n_node = this->nnode();
     for (unsigned n = 0; n < n_node; n++)
     {
       // Loop over the velocity components and add pointer to their data
       // and indices to the vectors
       for (unsigned i = 0; i < 3; i++)
       {
         paired_load_data.insert(std::make_pair(this->node_pt(n), u_index[i]));
       }
     }
     // Identify the pressure data
     identify_pressure_data(paired_load_data);
   }
References i, identify_pressure_data(), n, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::u_index_axi_nst().
identify_pressure_data()
void oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::identify_pressure_data (std::set< std::pair< Data *, unsigned >> & paired_pressure_data)
Add to the set paired_pressure_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for all pressure values that affect the load computed in the get_load(...) function.
Add to the set paired_pressue_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for all pressures values that affect the load computed in the get_load(...) function.
   {
     // Loop over the internal data
     unsigned n_internal = this->ninternal_data();
     for (unsigned l = 0; l < n_internal; l++)
     {
       unsigned nval = this->internal_data_pt(l)->nvalue();
       // Add internal data
       for (unsigned j = 0; j < nval; j++)
       {
         paired_pressure_data.insert(
           std::make_pair(this->internal_data_pt(l), j));
       }
     }
   }
References oomph::GeneralisedElement::internal_data_pt(), j, oomph::GeneralisedElement::ninternal_data(), and oomph::Data::nvalue().
Referenced by identify_load_data().
ndof_types()
unsigned oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::ndof_types () const inline virtual
The number of "DOF types" that degrees of freedom in this element are sub-divided into: Velocity and pressure.
Reimplemented from oomph::GeneralisedElement.
     {
       return 4;
     }
npres_axi_nst()
unsigned oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::npres_axi_nst () const inline virtual
Return number of pressure values.
Implements oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
     {
       return 3;
     }
Referenced by get_dof_numbers_for_unknowns(), and unpin_all_internal_pressure_dofs().
nrecovery_order()
unsigned oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::nrecovery_order () inline virtual
Order of recovery shape functions for Z2 error estimation: Same order as unenriched shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       return 2;
     }
num_Z2_flux_terms()
unsigned oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::num_Z2_flux_terms () inline virtual
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       // 3 diagonal strain rates, 3 off diagonal
       return 6;
     }
nvertex_node()
unsigned oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::nvertex_node () const inline virtual
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       return 3;
     }
operator=()
void oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::operator= (const GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement &) delete
Broken assignment operator.
output() [1/4]
void oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::output (FILE * file_pt) inline virtual
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
     {
       GeneralisedNewtonianAxisymmetricNavierStokesEquations::output(file_pt);
     }
References oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output().
output() [2/4]
void oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::output (FILE * file_pt, const unsigned & n_plot) inline virtual
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
     {
       GeneralisedNewtonianAxisymmetricNavierStokesEquations::output(file_pt,
                                                                     n_plot);
     }
References oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output().
output() [3/4]
void oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::output (std::ostream & outfile) inline virtual
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
     {
       GeneralisedNewtonianAxisymmetricNavierStokesEquations::output(outfile);
     }
References oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output().
output() [4/4]
void oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::output (std::ostream & outfile, const unsigned & nplot) inline virtual
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
     {
       GeneralisedNewtonianAxisymmetricNavierStokesEquations::output(outfile,
                                                                     nplot);
     }
References oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output().
p_axi_nst()
double oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::p_axi_nst (const unsigned & i) const inline virtual
Return the pressure values at internal dof i_internal (Discontinous pressure interpolation – no need to cater for hanging nodes).
Implements oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
     {
       return this->internal_data_pt(P_axi_nst_internal_index)->value(i);
     }
References i, oomph::GeneralisedElement::internal_data_pt(), and oomph::Data::value().
p_local_eqn()
int oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::p_local_eqn (const unsigned & n) const inline virtual
Return the local equation numbers for the pressure values.
Implements oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
     {
       return this->internal_local_eqn(P_axi_nst_internal_index, n);
     }
References oomph::GeneralisedElement::internal_local_eqn(), and n.
Referenced by get_dof_numbers_for_unknowns().
pshape_axi_nst() [1/2]
void oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::pshape_axi_nst (const Vector< double > & s, Shape & psi) const inline virtual
Pressure shape functions at local coordinate s.
Pressure shape functions.
Implements oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
   {
     psi[0] = 1.0;
     psi[1] = s[0];
     psi[2] = s[1];
   }
References s.
Referenced by pshape_axi_nst().
pshape_axi_nst() [2/2]
void oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::pshape_axi_nst (const Vector< double > & s, Shape & psi, Shape & test) const inline virtual
Pressure shape and test functions at local coordinte s.
Pressure shape and test functions.
Implements oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
   {
     // Call the pressure shape functions
     this->pshape_axi_nst(s, psi);
     // The test functions are the shape functions
     test = psi;
   }
References pshape_axi_nst().
required_nvalue()
virtual unsigned oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::required_nvalue (const unsigned & n) const inline virtual
Number of values (pinned or dofs) required at local node n.
Reimplemented from oomph::FiniteElement.
     {
       return 3;
     }
unpin_all_internal_pressure_dofs()
void oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::unpin_all_internal_pressure_dofs ()
Unpin all internal pressure dofs.
/////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
   {
     unsigned n_pres = this->npres_axi_nst();
     // loop over pressure dofs
     for (unsigned l = 0; l < n_pres; l++)
     {
       // unpin internal pressure
       this->internal_data_pt(P_axi_nst_internal_index)->unpin(l);
     }
   }
References oomph::GeneralisedElement::internal_data_pt(), npres_axi_nst(), P_axi_nst_internal_index, and oomph::Data::unpin().
vertex_node_pt()
Node* oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::vertex_node_pt (const unsigned & j) const inline virtual
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       return node_pt(j);
     }
References j, and oomph::FiniteElement::node_pt().
Member Data Documentation
P_axi_nst_internal_index
unsigned oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::P_axi_nst_internal_index protected
Internal index that indicates at which internal datum the pressure is stored
Referenced by GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement(), and unpin_all_internal_pressure_dofs().
The documentation for this class was generated from the following files:
generalised_newtonian_Taxisym_navier_stokes_elements.h
generalised_newtonian_Taxisym_navier_stokes_elements.cc