MercuryDPM: AdhesiveForceUnitTest.cpp File Reference
AdhesiveForceUnitTest.cpp File Reference
#include "Species/Species.h"
#include "Species/NormalForceSpecies/LinearViscoelasticNormalSpecies.h"
#include "Species/NormalForceSpecies/LinearPlasticViscoelasticNormalSpecies.h"
#include "Species/FrictionForceSpecies/SlidingFrictionSpecies.h"
#include "Species/AdhesiveForceSpecies/ReversibleAdhesiveSpecies.h"
#include "Species/AdhesiveForceSpecies/IrreversibleAdhesiveSpecies.h"
#include "DPMBase.h"
#include "Walls/InfiniteWall.h"
#include "Logger.h"
Classes
class ParticleParticleInteraction
class ParticleParticleInteractionWithPlasticForces
class ParticleWallInteraction
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     //First test Particle Particle interactions with no plastic forces so reverseable.
     ParticleParticleInteraction ParticleParticleInteractionProblem;
     ParticleParticleInteractionProblem.solve();
     logger(INFO,"Testing particle-particle collision for elastic adhesive forces");
     std::vector<BaseParticle*>::iterator pIt = ParticleParticleInteractionProblem.particleHandler.begin();
     if (!(*pIt)->getPosition().isEqualTo(Vec3D(-0.00101582359198137,0.0,0.0), 1e-7))
         logger(FATAL,"First particle is in the wrong position. It is at %",(*pIt)->getPosition());
     if (!(*pIt)->getVelocity().isEqualTo(Vec3D(-0.0436824,0.0,0.0)  , 1e-7))
         logger(FATAL,"First particle has the wrong velocity. It is at %",(*pIt)->getVelocity());
     ++pIt;
     if (!(*pIt)->getPosition().isEqualTo(Vec3D(0.00101582359198137,0.0,0.0), 1e-7))
         logger(FATAL,"Second particle is in the wrong position. It is at %",(*pIt)->getPosition());
     if (!(*pIt)->getVelocity().isEqualTo(Vec3D(0.0436824,0.0,0.0)  , 1e-7))
         logger(FATAL,"Second particle has the wrong velocity. It is at %",(*pIt)->getVelocity());
     //Second test Particle Particle interaction with a plastic force (non reverseable)
     ParticleParticleInteractionWithPlasticForces ParticleParticleInteractionWithPlasticForcesProblem;
     ParticleParticleInteractionWithPlasticForcesProblem.solve();
     logger(INFO,"Testing particle particles collision for plastic adhesive forces");
     std::vector<BaseParticle*>::iterator pIt2 = ParticleParticleInteractionWithPlasticForcesProblem.particleHandler.begin();
     if (!(*pIt2)->getPosition().isEqualTo(Vec3D(-0.00107858,0.0,0.0), 1e-7))
         logger(FATAL,"First particle is in the wrong position. It is at %",(*pIt2)->getPosition());
     if (!(*pIt2)->getVelocity().isEqualTo(Vec3D(-0.0352526,0.0,0.0)  , 1e-7))
         logger(FATAL,"First particle has the wrong velocity. It is at %",(*pIt2)->getVelocity());
     ++pIt2;
     if (!(*pIt2)->getPosition().isEqualTo(Vec3D(0.00107858,0.0,0.0), 1e-7))
         logger(FATAL,"Second particle is in the wrong position. It is at %",(*pIt2)->getPosition());
     if (!(*pIt2)->getVelocity().isEqualTo(Vec3D(0.0352526,0.0,0.0)  , 1e-7))
         logger(FATAL,"Second particle has the wrong velocity. It is at %",(*pIt2)->getVelocity());
     //Final test Particle-Wall interactions with a plastic force (non reversable)
     ParticleWallInteraction ParticleWallInteraction;
     ParticleWallInteraction.solve();
     logger(INFO,"Testing particle-wall collision for plastic adhesive forces");
     std::vector<BaseParticle*>::iterator pIt3 = ParticleWallInteraction.particleHandler.begin();
     if (!(*pIt3)->getPosition().isEqualTo(Vec3D(0.00104381,0.0,0.0), 1e-7))
         logger(FATAL,"The particle is in the wrong position. It is at %",(*pIt3)->getPosition());
     if (!(*pIt3)->getVelocity().isEqualTo(Vec3D(0.0362122,0.0,0.0)  , 1e-7))
         logger(FATAL,"The particle has the wrong velocity. It is at %",(*pIt3)->getVelocity());
     return 0;
 }
References BaseHandler< T >::begin(), e(), FATAL, INFO, logger, DPMBase::particleHandler, and DPMBase::solve().