MercuryDPM: oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT > Class Template Reference
oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT > Class Template Reference
#include <multi_domain_boussinesq_elements.h>
Public Member Functions
RefineableNavierStokesBoussinesqElement ()
const double & ra () const
Access function for the Rayleigh number (const version)
double *& ra_pt ()
Access function for the pointer to the Rayleigh number.
void further_build ()
void get_body_force_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &body_force)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual vector and the Jacobian matrix.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void get_dbody_force_nst_dexternal_element_data (const unsigned &ipt, DenseMatrix< double > &result, Vector< unsigned > &global_eqn_number)
void fill_in_off_diagonal_block_analytic (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Classify dof numbers as in underlying element.
unsigned ndof_types () const
Get number of dof types from underlying element.
Public Member Functions inherited from oomph::ElementWithExternalElement
ElementWithExternalElement ()
virtual ~ElementWithExternalElement ()
The destructor, clean up any allocated memory.
ElementWithExternalElement (const ElementWithExternalElement &)=delete
Broken copy constructor.
void operator= (const ElementWithExternalElement &)=delete
Broken assignment operator.
bool storage_has_been_allocated () const
Helper function to check if storage has actually been allocated.
FiniteElement *& external_element_pt (const unsigned &interaction_index, const unsigned &ipt)
FiniteElement *const & external_element_pt (const unsigned &interaction_index, const unsigned &ipt) const
Access function to source element, const version.
Vector< double > & external_element_local_coord (const unsigned &interaction_index, const unsigned &ipt)
Vector< double > const & external_element_local_coord (const unsigned &interaction_index, const unsigned &ipt) const
Access function to get source element's coords, const version.
void output_external_elements (std::ostream &outfile, const unsigned &interaction_index)
void initialise_external_element_storage ()
void flush_all_external_element_storage ()
Flush the storage for external elements.
void set_ninteraction (const unsigned &n_interaction)
unsigned ninteraction () const
Return the number of interactions in the element.
virtual void identify_all_field_data_for_external_interaction (Vector< std::set< FiniteElement * >> const &external_elements_pt, std::set< std::pair< Data *, unsigned >> &paired_interaction_data)
virtual void identify_all_geometric_data_for_external_interaction (Vector< std::set< FiniteElement * >> const &external_elements_pt, std::set< Data * > &external_geometric_data_pt)
unsigned nexternal_interaction_field_data () const
Vector< Data * > external_interaction_field_data_pt () const
unsigned nexternal_interaction_geometric_data () const
bool add_external_geometric_data ()
Are we including external geometric data in the element's Jacobian.
bool add_external_interaction_data ()
Are we including external data in the element's Jacobian.
Vector< Data * > external_interaction_geometric_data_pt () const
void ignore_external_geometric_data ()
void ignore_external_interaction_data ()
void include_external_geometric_data ()
void include_external_interaction_data ()
bool external_geometric_data_is_included () const
void describe_local_dofs (std::ostream &out, const std::string &curr_string) const
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (std::ostream &outfile)
virtual void output (std::ostream &outfile, const unsigned &n_plot)
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output (FILE *file_pt)
virtual void output (FILE *file_pt, const unsigned &n_plot)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Private Attributes
double * Ra_pt
Pointer to a private data member, the Rayleigh number.
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions inherited from oomph::ElementWithExternalElement
void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
void assign_external_interaction_data_local_eqn_numbers (const bool &store_local_dof_pt)
void fill_in_jacobian_from_external_interaction_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_by_fd (DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_field_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_field_by_fd (DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_geometric_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_geometric_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_external_interaction_field_fd ()
virtual void reset_after_external_interaction_field_fd ()
virtual void update_in_external_interaction_field_fd (const unsigned &i)
virtual void reset_in_external_interaction_field_fd (const unsigned &i)
virtual void update_before_external_interaction_geometric_fd ()
virtual void reset_after_external_interaction_geometric_fd ()
virtual void update_in_external_interaction_geometric_fd (const unsigned &i)
virtual void reset_in_external_interaction_geometric_fd (const unsigned &i)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes inherited from oomph::ElementWithExternalElement
bool Add_external_interaction_data
Boolean flag to indicate whether to include the external data.
bool Add_external_geometric_data
Boolean flag to indicate whether to include the external geometric data.
Data ** External_interaction_field_data_pt
Data ** External_interaction_geometric_data_pt
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<class NST_ELEMENT, class AD_ELEMENT>
class oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >
////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// Build a refineable Navier Stokes element that inherits from ElementWithExternalElement so that it can "communicate" with an advection diffusion element that provides the temperature in the body force term.
Constructor & Destructor Documentation
RefineableNavierStokesBoussinesqElement()
template<class NST_ELEMENT , class AD_ELEMENT > oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::RefineableNavierStokesBoussinesqElement () inline
Constructor: call the underlying constructors and initialise the pointer to the Rayleigh number to point to the default value of 0.0.
       : NST_ELEMENT(), ElementWithExternalElement()
     {
       Ra_pt = &MultiDomainBoussinesqHelper::Default_Physical_Constant_Value;
       // There is one interaction: The effect of the advection-diffusion
       // element onto the buoyancy term
       this->set_ninteraction(1);
     }
References oomph::MultiDomainBoussinesqHelper::Default_Physical_Constant_Value, oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::Ra_pt, and oomph::ElementWithExternalElement::set_ninteraction().
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class NST_ELEMENT , class AD_ELEMENT > void oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Compute the element's residual vector and the Jacobian matrix.
Reimplemented from oomph::ElementWithExternalElement.
     {
       // Get the analytical contribution from the basic Navier-Stokes element
       NST_ELEMENT::fill_in_contribution_to_jacobian(residuals, jacobian);
 #ifdef USE_FD_FOR_DERIVATIVES_WRT_EXTERNAL_DATA_IN_MULTI_DOMAIN_BOUSSINESQ
       // Get the off-diagonal terms by finite differencing
       this->fill_in_jacobian_from_external_interaction_by_fd(residuals,
                                                              jacobian);
 #else
       // Get the off-diagonal terms analytically
       this->fill_in_off_diagonal_block_analytic(residuals, jacobian);
 #endif
     }
References oomph::fill_in_contribution_to_jacobian(), oomph::ElementWithExternalElement::fill_in_jacobian_from_external_interaction_by_fd(), and oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic().
fill_in_contribution_to_jacobian_and_mass_matrix()
template<class NST_ELEMENT , class AD_ELEMENT > void oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) inline virtual
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix
Reimplemented from oomph::GeneralisedElement.
     {
       // Call the standard (Broken) function
       // which will prevent these elements from being used
       // in eigenproblems until replaced.
       FiniteElement::fill_in_contribution_to_jacobian_and_mass_matrix(
         residuals, jacobian, mass_matrix);
     }
References oomph::GeneralisedElement::fill_in_contribution_to_jacobian_and_mass_matrix().
fill_in_off_diagonal_block_analytic()
template<class NST_ELEMENT , class AD_ELEMENT > void oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline
Compute the contribution of the external degrees of freedom (temperatures) on the Navier-Stokes equations
     {
       // Local storage for the index in the nodes at which the
       // Navier-Stokes velocities are stored (we know that this
       // should be 0,1,2)
       const unsigned n_dim = this->dim();
       unsigned u_nodal_nst[n_dim];
       for (unsigned i = 0; i < n_dim; i++)
       {
         u_nodal_nst[i] = this->u_index_nst(i);
       }
       // Find out how many nodes there are
       const unsigned n_node = this->nnode();
       // Set up memory for the shape and test functions and their derivatives
       Shape psif(n_node), testf(n_node);
       DShape dpsifdx(n_node, n_dim), dtestfdx(n_node, n_dim);
       // Number of integration points
       const unsigned n_intpt = this->integral_pt()->nweight();
       // Integers to store the local equations and unknowns
       int local_eqn = 0, local_unknown = 0;
       // Local storage for pointers to hang_info objects
       HangInfo* hang_info_pt = 0;
       // Loop over the integration points
       for (unsigned ipt = 0; ipt < n_intpt; ipt++)
       {
         // Get the integral weight
         double w = this->integral_pt()->weight(ipt);
         // Call the derivatives of the shape and test functions
         double J = this->dshape_and_dtest_eulerian_at_knot_nst(
           ipt, psif, dpsifdx, testf, dtestfdx);
         // Premultiply the weights and the Jacobian
         double W = w * J;
         // Assemble the jacobian terms
         // Get the derivatives of the body force wrt the unknowns
         // of the external element
         DenseMatrix<double> dbody_dexternal_element_data;
         // Vector of global equation number corresponding to the external
         // element's data
         Vector<unsigned> global_eqn_number_of_external_element_data;
         // Get the appropriate derivatives
         this->get_dbody_force_nst_dexternal_element_data(
           ipt,
           dbody_dexternal_element_data,
           global_eqn_number_of_external_element_data);
         // Find out how many external data there are
         const unsigned n_external_element_data =
           global_eqn_number_of_external_element_data.size();
         // Loop over the test functions
         for (unsigned l = 0; l < n_node; l++)
         {
           // Assemble the contributions of the temperature to
           // the Navier--Stokes equations (which arise through the buoyancy
           // body-force term)
           unsigned n_master = 1;
           double hang_weight = 1.0;
           // Local bool (is the node hanging)
           bool is_node_hanging = this->node_pt(l)->is_hanging();
           // If the node is hanging, get the number of master nodes
           if (is_node_hanging)
           {
             hang_info_pt = this->node_pt(l)->hanging_pt();
             n_master = hang_info_pt->nmaster();
           }
           // Otherwise there is just one master node, the node itself
           else
           {
             n_master = 1;
           }
           // Loop over the master nodes
           for (unsigned m = 0; m < n_master; m++)
           {
             // If the node is hanging get weight from master node
             if (is_node_hanging)
             {
               // Get the hang weight from the master node
               hang_weight = hang_info_pt->master_weight(m);
             }
             else
             {
               // Node contributes with full weight
               hang_weight = 1.0;
             }
             // Loop over the velocity components in the Navier--Stokes equtions
             for (unsigned i = 0; i < n_dim; i++)
             {
               // Get the equation number
               if (is_node_hanging)
               {
                 // Get the equation number from the master node
                 local_eqn = this->local_hang_eqn(
                   hang_info_pt->master_node_pt(m), u_nodal_nst[i]);
               }
               else
               {
                 // Local equation number
                 local_eqn = this->nodal_local_eqn(l, u_nodal_nst[i]);
               }
               if (local_eqn >= 0)
               {
                 // Loop over the external data
                 for (unsigned l2 = 0; l2 < n_external_element_data; l2++)
                 {
                   // Find the local equation number corresponding to the global
                   // unknown
                   local_unknown = this->local_eqn_number(
                     global_eqn_number_of_external_element_data[l2]);
                   if (local_unknown >= 0)
                   {
                     // Add contribution to jacobian matrix
                     jacobian(local_eqn, local_unknown) +=
                       dbody_dexternal_element_data(i, l2) * testf(l) *
                       hang_weight * W;
                   }
                 }
               }
             }
           }
         }
       }
     }
References oomph::FiniteElement::dim(), oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::get_dbody_force_nst_dexternal_element_data(), oomph::Node::hanging_pt(), i, oomph::FiniteElement::integral_pt(), oomph::Node::is_hanging(), J, oomph::GeneralisedElement::local_eqn_number(), m, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), w, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_contribution_to_jacobian().
further_build()
template<class NST_ELEMENT , class AD_ELEMENT > void oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::further_build () inline
Call the underlying single-physics element's further_build() functions and make sure that the pointer to the Rayleigh number is passed to the sons. Also make sure that if the external geometric Data was ignored in the father it's also ignored in the sons
     {
       NST_ELEMENT::further_build();
       // Cast the pointer to the father element to the specific
       // element type
       RefineableNavierStokesBoussinesqElement<NST_ELEMENT, AD_ELEMENT>*
         cast_father_element_pt = dynamic_cast<
           RefineableNavierStokesBoussinesqElement<NST_ELEMENT, AD_ELEMENT>*>(
           this->father_element_pt());
       // Set the pointer to the Rayleigh number to be the same as that in
       // the father
       this->Ra_pt = cast_father_element_pt->ra_pt();
       // Retain ignorance about external geometric data...
       if (!cast_father_element_pt->external_geometric_data_is_included())
       {
         this->ignore_external_geometric_data();
       }
     }
References oomph::ElementWithExternalElement::external_geometric_data_is_included(), oomph::ElementWithExternalElement::ignore_external_geometric_data(), oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::ra_pt(), and oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::Ra_pt.
get_body_force_nst()
template<class NST_ELEMENT , class AD_ELEMENT > void oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::get_body_force_nst (const double & time, const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & body_force) inline
Overload get_body_force_nst() to return the temperature-dependent buoyancy force, using the temperature computed by the "external" advection diffusion element associated with integration point ipt.
     {
       // Set interaction index -- there's only one interaction...
       const unsigned interaction = 0;
       // Get a pointer to the external element that computes the
       // the temperature -- we know it's an advection diffusion element.
       const AD_ELEMENT* adv_diff_el_pt =
         dynamic_cast<AD_ELEMENT*>(external_element_pt(interaction, ipt));
       // Get the temperature interpolated from the external element
       const double interpolated_t = adv_diff_el_pt->interpolated_u_adv_diff(
         external_element_local_coord(interaction, ipt));
       // Get vector that indicates the direction of gravity from
       // the Navier-Stokes equations
       Vector<double> gravity(NST_ELEMENT::g());
       // Set the temperature-dependent body force:
       const unsigned n_dim = this->dim();
       for (unsigned i = 0; i < n_dim; i++)
       {
         body_force[i] = -gravity[i] * interpolated_t * ra();
       }
     } // end overloaded body force
References Global_Parameters::body_force(), oomph::FiniteElement::dim(), oomph::ElementWithExternalElement::external_element_local_coord(), oomph::ElementWithExternalElement::external_element_pt(), Gravity::gravity(), i, and oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::ra().
get_dbody_force_nst_dexternal_element_data()
template<class NST_ELEMENT , class AD_ELEMENT > void oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::get_dbody_force_nst_dexternal_element_data (const unsigned & ipt, DenseMatrix< double > & result, Vector< unsigned > & global_eqn_number)
Fill in the derivatives of the body force with respect to the external unknowns
Fill in the derivatives of the body force with respect to the external unknowns in the Navier–Stokes equations
   {
     // Get vector that indicates the direction of gravity from
     // the Navier-Stokes equations
     Vector<double> gravity(NST_ELEMENT::g());
     // The interaction index is 0 in this case
     unsigned interaction = 0;
     // Get the external element's derivatives
     Vector<double> du_adv_diff_ddata;
     // Dynamic cast "other" element to correct type
     AD_ELEMENT* source_el_pt =
       dynamic_cast<AD_ELEMENT*>(external_element_pt(interaction, ipt));
 #ifdef PARANOID
     if (source_el_pt == 0)
     {
       throw OomphLibError("External element could not be cast to AD_ELEMENT\n",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Get derivatives
     source_el_pt->dinterpolated_u_adv_diff_ddata(
       external_element_local_coord(interaction, ipt),
       du_adv_diff_ddata,
       global_eqn_number);
     // Find the number of external data
     unsigned n_external_element_data = du_adv_diff_ddata.size();
     // Set the size of the matrix to be returned
     const unsigned n_dim = this->dim();
     result.resize(n_dim, n_external_element_data);
     // Temperature-dependent body force:
     for (unsigned i = 0; i < n_dim; i++)
     {
       // Loop over the external data
       for (unsigned n = 0; n < n_external_element_data; n++)
       {
         result(i, n) = -gravity[i] * du_adv_diff_ddata[n] * ra();
       }
     }
   } // end_of_get_dbody_force
References Gravity::gravity(), i, n, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::DenseMatrix< T >::resize().
Referenced by oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic().
get_dof_numbers_for_unknowns()
template<class NST_ELEMENT , class AD_ELEMENT > void oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> & dof_lookup_list) const inline virtual
Classify dof numbers as in underlying element.
Reimplemented from oomph::GeneralisedElement.
     {
       // Call the underlying function
       NST_ELEMENT::get_dof_numbers_for_unknowns(dof_lookup_list);
     }
ndof_types()
template<class NST_ELEMENT , class AD_ELEMENT > unsigned oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::ndof_types () const inline virtual
Get number of dof types from underlying element.
Reimplemented from oomph::GeneralisedElement.
     {
       return NST_ELEMENT::ndof_types();
     }
ra()
template<class NST_ELEMENT , class AD_ELEMENT > const double& oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::ra () const inline
Access function for the Rayleigh number (const version)
     {
       return *Ra_pt;
     }
References oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::Ra_pt.
Referenced by oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::get_body_force_nst().
ra_pt()
template<class NST_ELEMENT , class AD_ELEMENT > double*& oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::ra_pt () inline
Access function for the pointer to the Rayleigh number.
     {
       return Ra_pt;
     }
References oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::Ra_pt.
Referenced by oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::further_build().
Member Data Documentation
Ra_pt
template<class NST_ELEMENT , class AD_ELEMENT > double* oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::Ra_pt private
Pointer to a private data member, the Rayleigh number.
Referenced by oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::further_build(), oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::ra(), oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::ra_pt(), and oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::RefineableNavierStokesBoussinesqElement().
The documentation for this class was generated from the following file:
multi_domain_boussinesq_elements.h